### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by phillc** [meteor/meteor#100]
I deployed my app. It was doing just fine, but I changed the data model a bit and wanted to refresh the db, so I did a `deploy --delete`  and now I cannot deploy to the same name again... `Error deploying application: Error creating application.`

**Comment by Peth404** [comment]
I deployed my app. It was doing just fine, but I changed the data model a bit and wanted to refresh the db, so I did a deploy --delete and now I cannot deploy to the same name again... Error deploying application: Error creating application.

**Comment by glasser** [comment]
@Peth404 Was this a consistent issue or did it work when you tried again later?

**Comment by zachdixon** [comment]
Apologize for the bump, but I'm getting a similar result here. I deployed an app to catskill-moc.meteor.com fine 2 days ago and did it multiple times. It's a very simple app (mostly static stuff, no collections or any Meteor stuff except for one Iron Router route). Today I tried deploying the same app to catskill-moc-v2.meteor.com and got this error the first time:
```
Error deploying application: <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
margin: 0;
text-align: center;
}
.meteor {
padding-top: 200px;
padding-bottom: 20px;
height: 142px;
}
.message {
padding-top: 50px;
font-size: 3em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.submessage {
padding-top: 20px;
font-size: 1.5em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.counter {
padding-top: 30px;
font-size: 1em;
color: #aaa;
letter-spacing: -1px;
}

</style>
</head>
<body>
<div class="meteor"><img src="//warehouse.meteor.com/mother-assets/meteor-logo-final.png"/></div>
<div class="message">
This site is down.
</div>
<div class="submessage">
Try again later.
</div>
<div id="counter" class="counter">
</div>


<script type="text/javascript">
var refreshTime = 0 ;
if (refreshTime) {
var counterDiv = document.getElementById("counter");
var countdown = function () {
if (refreshTime < 1) {
counterDiv.innerHTML =
"Retrying...";
location.reload(true);
} else {
counterDiv.innerHTML =
"Retrying in " + refreshTime + " seconds...";
refreshTime = refreshTime - 1;
setTimeout(countdown, 1000);
}
}
countdown();
}
</script>

</body>
</html>
```

Any new subdomain I try, I get that error the first time; then any subsequent time it says it deploys, but the app never loads. It's continually stuck on the "This site is loading" page. I even tried deploying the original app to the original location and it did the same thing.

I've tried from two different locations/internets and got the same result.

Here's the logs from one of them:
```
[Wed May 06 2015 23:03:00 GMT+0000 (UTC)] INFO STATUS null -> starting
[Wed May 06 2015 23:03:00 GMT+0000 (UTC)] NOTICE Starting application on port 25098
[Wed May 06 2015 23:03:01 GMT+0000 (UTC)] INFO STATUS starting -> crashed
[Wed May 06 2015 23:03:09 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:15 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:16 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
[Wed May 06 2015 23:03:21 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:22 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
[Wed May 06 2015 23:03:27 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:27 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
[Wed May 06 2015 23:03:28 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:33 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
[Wed May 06 2015 23:03:34 GMT+0000 (UTC)] INFO HIT / 71.97.28.19
[Wed May 06 2015 23:03:34 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
[Wed May 06 2015 23:03:40 GMT+0000 (UTC)] INFO HIT /favicon.ico 71.97.28.19
```

That IP address seems to be Verizon's (my ISP) but I'm not sure if that has anything to do with it? I was able to deploy from this internet before.

I also did the `curl deploy.meteor.com/has_password/www.meteor.com` command listed above and it returned false. `curl www.google.com` returns the html fine.

Any ideas? Thanks!

**Comment by pdroll** [comment]
I'm having the same issues as outlined by @zachdixon. Just came up for the first time today. Earlier this week, I was able to deploy without issues. Now, after running with --delete, deploy always fails with `Error deploying application:` message.

**Comment by ipstas** [comment]
Looks like it is the same issue again.
www.followlater.com fails
I can deploy to fll8r.meteor.com though

meteor deploy  www.followlater.com --debug
Deploying to www.followlater.com.

Error deploying application: <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
margin: 0;
text-align: center;
}
.meteor {
padding-top: 200px;
padding-bottom: 20px;
height: 142px;
}
.message {
padding-top: 50px;
font-size: 3em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.submessage {
padding-top: 20px;
font-size: 1.5em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.counter {
padding-top: 30px;
font-size: 1em;
color: #aaa;
letter-spacing: -1px;
}

</style>
</head>
<body>
<div class="meteor"><img src="//warehouse.meteor.com/mother-assets/meteor-logo-final.png"/></div>
<div class="message">
This site is down.
</div>
<div class="submessage">
Try again later.
</div>
<div id="counter" class="counter">
</div>


<script type="text/javascript">
var refreshTime = 0 ;
if (refreshTime) {
var counterDiv = document.getElementById("counter");
var countdown = function () {
if (refreshTime < 1) {
counterDiv.innerHTML =
"Retrying...";
location.reload(true);
} else {
counterDiv.innerHTML =
"Retrying in " + refreshTime + " seconds...";
refreshTime = refreshTime - 1;
setTimeout(countdown, 1000);
}
}
countdown();
}
</script>

</body>
</html>

**Comment by zachdixon** [comment]
Updating to see if this solution works for you other guys, or if there's another problem going on somewhere.

I tried redeploying again this morning with the same result.

I then tried deleting the app and received the same HTML error page saying "This site is down, try again later". Tried to delete again and said the site does not exist.

This seemed like similar behavior described [here](https://github.com/meteor/meteor/issues/1208)

That thread mentioned long names causing this problem which mine was only 15 characters long; shouldn't be an issue. I then tried a shorter name (6 characters long) and it worked just fine. I wasn't getting the error message that was supposedly put into place for this problem, so not sure what's going on exactly.

**Comment by ipstas** [comment]
OK, I have fixed the issue. 
1. meteor deploy -D appname
2. meteor reset (in the local app folder)
3. meteor deploy -------------with all the stuff

So it looks like the problem with the DB, it had something that prevented app starting

**Comment by pdroll** [comment]
@ipstas You nailed it. Running `meteor reset` before deploying again did the trick.

**Comment by guinunez** [comment]
@ipstas saved my day

**Comment by curiositry** [comment]
Getting the same issue now, but  @ipstas solution doesn’t seem to work; in fact, running `meteor deploy -D appname` produces the same error as a regular deploy…

**Comment by Calvinxc1** [comment]
Having the same issue, but the 'meteor reset' prior to deploying seemed to work.

**Comment by watsokel** [comment]
I'm having the same issue today that @zachdixon had, along with another error I'm getting, which is "Error deploying application: Connection error (socket hang up)."

I've done meteor reset before doing my meteor deploy, but I still get "Error deploying application: Connection error (socket hang up)." 

My application runs perfectly on localhost and has deployed without any issues prior to today.

**Comment by DomClaxton** [comment]
I'm getting the same error. Error deploying application: Connection error (socket hang up)
