### ISSUE TITLE
iPhone8 Sarari white screen because of ES6 async/await

### ISSUE THREAD

**Issue by musemind** [meteor/meteor#10004]
In the current Meteor 1.7 preset, the app crashes (white screen) on iPhone8 + Safari (older and newer iPhones do not have this issue!) with async/await. Case was reported by one of our users and was reproducable with browserstack.com.

`mobileSafari: Infinity` fixed the problem..

![image](https://user-images.githubusercontent.com/11320794/41501112-4b2c3e50-719e-11e8-8d24-cb62ffb48d74.png)

```
import {
  setMinimumBrowserVersions
} from 'meteor/modern-browsers'

setMinimumBrowserVersions({
  chrome: 45,
  firefox: 44,
  edge: 17,
  ie: Infinity,
  mobileSafari: Infinity,
  opera: 32,
  safari: [11, 1],
  electron: [0, 36]
}, 'service workers')
```

**Comment by benjamn** [comment]
Is there any version of mobile safari that supports native `async`/`await`?

**Comment by sakulstra** [comment]
hello, any update on this? I got kind of scared when i read this as we have a lot of ios users, but at least in browserstack i cannot reproduce the issue you're describing (tested on iphone 6/7/8) https://caniuse.com/#search=await

**Comment by musemind** [comment]
I don't know. In general, mobile safari seems to have a good async/await support without knowing details about specific versions -> except this issue on the iPhone8! Anyway, with `mobileSafari: Infinity` you can force the "old" compatible bundle version for iOS/safari.

**Comment by benjamn** [comment]
@musemind Can you share the `async` code that triggered this problem? Wondering if it's any kind of `async`/`await`, or something more specific.

**Comment by benjamn** [comment]
Possibly related minifier problem: https://github.com/meteor/meteor/issues/10034

**Comment by musemind** [comment]
I'm not able to reproduce it anymore. May updated meteor or some packages in the meantime.
