### ISSUE TITLE
When I update Meteor from 1.6.1.3 to 1.7, the webbrowser can't load correctly any more

### ISSUE THREAD

**Issue by moebiusever** [meteor/meteor#10016]
host: ubuntu 16.04

meteor: 1.6.1.3

web browser: Firefox 60.0.2 chrome 67.0.3396.87

    meteor update, it update to 1.7.03

192.168.1.9 is the host ip address

when I visit from anothor host through http://192.168.1.9:3000 the browser gives a tip can't find /node_modules/meteor/socket-stream-client/sockjs-0.3.4.js module

and the contents don't load completely.

when I visit in the host through http://127.0.0.1:3000, it loads completely with no error.

execute ROOT_URL=192.168.1.9：3000 meteor

and then visit http://192.168.1.9:3000, from another host the webbrowser can work well.

2.meteor update --release 1.6.1.3 everything goes properly.

The host side don't report any error, I can't fix this problem.

I asked this [question ](https://stackoverflow.com/questions/50960013/when-i-update-meteor-from-1-6-1-3-to-1-7-the-webbrowser-cant-load-correctly-an)on the stackoverflow

**Comment by benjamn** [comment]
Try `meteor update socket-stream-client` to get a version of that package that does not try to load `sockjs-0.3.4.js` with a dynamic `import()`.

**Comment by moebiusever** [comment]
After excute meteor update socket-stream-client,  can't find /node_modules/meteor/socket-stream-client/sockjs-0.3.4.js module disapper from the browser.
Thank you, @benjamn
