### ISSUE TITLE
[1.7.1-beta.4] lazy-loading MultiFileCachingCompiler ignores 'isRoot' function.

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10014]
I'm adapting `fourseven:scss` for https://github.com/meteor/meteor/pull/9983 .
Branch: https://github.com/fourseven/meteor-scss/tree/meteor/171

So far so good, but when I add a `compileOneFileLater` function, the `isRoot` function of the compiler is never called (and thus files which are imports by naming convention are now included by default).
The result is that I have files that are not root added directly to the page.

I'm not really getting the logic behind: https://github.com/meteor/meteor/blob/7a68a0d9ca03fc5f587932f68a1aede7205b2ee8/packages/caching-compiler/multi-file-caching-compiler.js#L150-L159

**Comment by benjamn** [comment]
The idea is that even if a file is not a root, it might need to be compiled later (effectively causing it to be treated as if it was a root), so we should always call `this.compileOneFileLater` to make that possible. With deferred compilation, the decision about whether to compile and include a file basically comes down to whether you pass `lazy: true` to `inputFile.addStylesheet` or `inputFile.addJavaScript`.

Perhaps this code could set a default value for `inputFile.getFileOptions().lazy`, to make sure that information is preserved by default if the plugin does not specify laziness:
```js
const options = inputFile.getFileOptions();
if (typeof options.lazy === "undefined") {
  options.lazy = ! this.isRoot(inputFile);
}
await this.compileOneFileLater(inputFile, getResult);
```

**Comment by benjamn** [comment]
Another way to fix this (I think) would be to pass `lazy: ! this.isRoot(inputFile)` [here](https://github.com/meteor/meteor/blob/f42629ce5e2a571d4f6d98999da528566812402b/packages/less/plugin/compile-less.js#L49):
```js
  compileOneFileLater(inputFile, getResult) {
    inputFile.addStylesheet({
      path: inputFile.getPathInPackage(),
      lazy: ! this.isRoot(inputFile),
    }, async () => {
      const result = await getResult();
      return result && {
        data: result.css,
        sourceMap: result.sourceMap,
      };
    });
  }
```

**Comment by sebakerckhof** [comment]
Got it, thanks!

**Comment by benjamn** [comment]
@sebakerckhof The `1.7.1-beta.5` release should work better with `isRoot`. Specifically, if `this.isRoot(inputFile)` returns false, that means the file was explicitly marked as an import/lazy (e.g. `*.import.less` for LESS or named with a `_` for SCSS). If `this.isRoot(inputFile)` returns true, however, we just let `compileOneFileLater` decide whether the file should be compiled (as before).

**Comment by sebakerckhof** [comment]
I have to admin that I didn't fully get https://github.com/meteor/meteor/issues/10014#issuecomment-399438336 , since it made me believe there could be compilers where files were not root and not lazy, although I couldn't think of how that would work. But the new PR, its commit message and comment now make it totally clear.  Thanks for always explaining things so thoroughly in the commit messages.
