### ISSUE TITLE
[1.7.0.3] Error when using custom ROOT_URL

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#10019]
Meteor version with the problem: `1.7.0.3`
Last tested Meteor version without the problem: `1.6.0.1`
OS: macOS High Sierra
Expected behavior: Should be able to visit page `localhost:3000/app` normally.
Actual behavior: App does not serve the page at all. See error below:

```
W20180622-04:14:07.379(-5)? (STDERR) (node:3757) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
W20180622-04:14:07.380(-5)? (STDERR)     at getArchAndPath (packages/webapp/webapp_server.js:520:15)
W20180622-04:14:07.380(-5)? (STDERR)     at getStaticFileInfo (packages/webapp/webapp_server.js:481:26)
W20180622-04:14:07.380(-5)? (STDERR)     at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:406:16)
W20180622-04:14:07.380(-5)? (STDERR)     at packages/webapp/webapp_server.js:781:21
W20180622-04:14:07.381(-5)? (STDERR)     at /Users/xch/.meteor/packages/promise/.0.11.1.e1cv1x.nf15w++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180622-04:14:07.381(-5)? (STDERR) (node:3757) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Simple** reproduction: 

```
meteor create --full foobar
cd foobar
meteor npm i
ROOT_URL=http://localhost:3000/app meteor
```
![image](https://user-images.githubusercontent.com/1815174/41768924-427340b8-75d3-11e8-9ca0-782e68e609bb.png)

Looks like the connection couldn't even be established.

**Comment by Zodiase** [comment]
FYI, `1.6.1` has a similar behavior (unable to load the page at all), just different error message.

**Comment by tall3n** [comment]
Our Application is currently experiencing this same exact problem.

We upgraded from 1.6.0.1 to 1.7.0.3 and we can visit url/sub/ but url/sub throws the above error. 

@Zodiase  Have you found a workaround for this?

**Comment by Zodiase** [comment]
@tall3n Unfortunately no. I reverted the project back to `1.6.0.1` and decided to stay at that version as long as I can.

I was trying out `1.7` to see if the minifier issue (importing a little too many npm packages would cause the minification process to take a very long time and eventually run out of memory) has been resolved. Now I have to stay at `1.6.0.1` and just serve all 6MB (and growing) of raw goods...

**Comment by benjamn** [comment]
Thanks for reporting this. If you're ever stuck waiting for us to respond to an issue, I would encourage you to look at the code where the error is happening. Maybe I'm underestimating how complex the code seems if you're unfamiliar with it, or maybe the code is hard to find, or maybe you just don't have time to help in this way (reporting the issue is still helpful, to be clear!). However, to my very biased eyes, [the code in question](https://github.com/meteor/meteor/blob/4502ad6e57aaa7333a677dcabdb0311d64bfdd78/packages/webapp/webapp_server.js#L520) seems pretty easy to understand, in this case.

If you ever need to modify someone else's Meteor package locally (e.g. the `webapp` package), just copy/clone it into the `packages` directory of your app, make your changes, and then `meteor run` to pick up the changes.

I hope this doesn't come across as asking too much. I just want you all to feel empowered to fix problems (which will help other developers in the community) rather than having to revert to previous Meteor versions.

**Comment by Zodiase** [comment]
@benjamn I tried copying `~/.meteor/packages/webapp/1.6.1` to `project/packages/webapp` but Meteor didn't seem to like those files. Do I have to download the source code from the repo?

**Comment by Zodiase** [comment]
After changing https://github.com/meteor/meteor/blob/4502ad6e57aaa7333a677dcabdb0311d64bfdd78/packages/webapp/webapp_server.js#L518 to `const archKey = pathParts.length > 1 ? pathParts[1] : '';` to get pass the type error, I get this error:

```
W20180628-20:58:24.195(-5)? (STDERR) (node:8723) UnhandledPromiseRejectionWarning: Error: url must be a relative URL: 
W20180628-20:58:24.196(-5)? (STDERR)     at RoutePolicy.classify (packages/routepolicy/routepolicy.js:109:13)
W20180628-20:58:24.196(-5)? (STDERR)     at appUrl (packages/webapp/webapp_server.js:169:19)
W20180628-20:58:24.196(-5)? (STDERR)     at packages/webapp/webapp_server.js:812:11
W20180628-20:58:24.196(-5)? (STDERR)     at /Users/xch/.meteor/packages/promise/.0.11.1.e1cv1x.nf15w++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180628-20:58:24.197(-5)? (STDERR) (node:8723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
W20180628-20:58:24.197(-5)? (STDERR) (node:8723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Somehow https://github.com/meteor/meteor/blob/4502ad6e57aaa7333a677dcabdb0311d64bfdd78/packages/webapp/webapp_server.js#L154 is called with an empty url (`''`).

**Comment by Zodiase** [comment]
After changing https://github.com/meteor/meteor/blob/4502ad6e57aaa7333a677dcabdb0311d64bfdd78/packages/webapp/webapp_server.js#L761 to `request.url = request.url.substring(pathPrefix.length) || "/";` so that `WebAppInternals.staticFilesMiddleware` would receive `'req.url': '/'` instead of `'req.url': ''`, now the server can serve out the index html, and the scaffolded app (`meteor create --full foobar`) seems to be working. But my other app that's using SSR is only rendering a blank page.

**Comment by Zodiase** [comment]
While I'm not sure what other implications this change may have, my original app that was having the issue and doesn't use SSR now seems to be working fine.

**Comment by Zodiase** [comment]
@tall3n
So I would suggest the workaround, until the official solution is deployed:
- Make sure you are using `webapp@1.6.1`.
- Head to https://kinolien.github.io/gitzip/, use the tool to download `webapp` package from https://github.com/meteor/meteor/tree/4502ad6e57aaa7333a677dcabdb0311d64bfdd78/packages/webapp.
- Unpack the content and put it at `project/packages/webapp`.
- Search in `project/packages/webapp/webapp_server.js` for `request.url = request.url.substring(pathPrefix.length);` and replace it with `request.url = request.url.substring(pathPrefix.length) || "/";`.

**Comment by tall3n** [comment]
Thanks @Zodiase 

@benjamn Agreed!, I had already started digging into the code, but we were in the middle of a roll out. 

Everything is good now, we changed our url scheme (which was in the books already, just got implemented quicker), which corrected it for us. 

Thanks to you both.

**Comment by benjamn** [comment]
Running `meteor update webapp` should now give you `webapp@1.6.2`, which contains a fix inspired by @Zodiase's workaround.
