### ISSUE TITLE
Invalid schema when running Meteor from a checkout

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#10012]
Error: Invalid schema, expected `mongodb` or `mongodb+srv`

OS: Windows
(Base) version: 1.7.0.3

meteor reset (called from either the original Meteor release listed in the application or from the checkout version) does not resolve the issue.

Any pointers?

**Comment by yorrd** [comment]
your mongodb connection string is not formatted correctly. It should be something like this `mongodb://user:pass@hostname:port/db`, and is at least missing the first `mongodb`. More a question for stackoverflow though...

**Comment by KoenLav** [comment]
The thing is, I'm running Meteor locally, without a connection string, so
it should just work out of the box.

Op wo 20 jun. 2018 13:00 schreef Yorrd <notifications@github.com>:

**Comment by sebakerckhof** [comment]
Had a similar issue when running test-packages sporadically: https://github.com/meteor/meteor/issues/9854
