### ISSUE TITLE
Mongo v3.6 allows nested fields to start with dollar sign ($) minimongo does not

### ISSUE THREAD

**Issue by dariusj18** [meteor/meteor#10023]
If you have documents with nested fields containing dollar signs, when you subscribe to a published collection you get an error.

**Meteor:** v1.7.0.3
**OS:** Windows 10 Pro

```
Uncaught Error: Key $text must not start with '$'
    at MinimongoError (common.js:1087)
    at assertIsValidFieldName (local_collection.js:1889)
    at Object.JSON.stringify (local_collection.js:1880)
    at JSON.stringify (<anonymous>)
    at assertHasValidFieldNames (local_collection.js:1879)
    at LocalCollection.insert (local_collection.js:94)
    at Object.update (collection.js:200)
    at Object.store.(anonymous function) [as update] (http://localhost:3000/packages/ddp-client.js?hash=7fae7e488e45468ea4fda5047b1baf99d39dfd73:604:38)
    at updateMessages.forEach.updateMessage (livedata_connection.js:1198)
    at Array.forEach (<anonymous>)
```

**Comment by sebakerckhof** [comment]
I believe this is a mongo limitation (you can not have keys starting with dollar signs or containing dots).
Does your query work outside of meteor (e.g. by querying mongo directly?)

**Comment by sebakerckhof** [comment]
Ow, I see now that you mention mongo 3.6 allows this. I was not aware and can't find anything in the release notes. Could you point me to where it says this has become possible?

**Comment by dariusj18** [comment]
https://docs.mongodb.com/manual/reference/limits/#naming-restrictions

Under `Restrictions on Field Names`

> Changed in version 3.6.
> 
> Field names can contain dots (i.e. .) and dollar signs (i.e. $). However, only nested field names may start with a dollar sign. For example, attempting to insert { "a" : { "$b": 1 } } will succeed but attempting to insert {"$a": 1} results in error.

**Comment by ctrlbrett** [comment]
What is the status on allowing "." and "$" on the  client side? Is it fixed by issue 10217?

**Comment by JanMP** [comment]
While the mongo server supposedly allows for `$` and `.` in field names, the official drivers don't. I just tried with `rawCollection()` and it doesn't work (even with nesting).

**Comment by sebakerckhof** [comment]
Yeah, and last year I started working on a PR to support thsi in minimongo, and it would be a really big change, which I don't think is justified.

**Comment by JanMP** [comment]
Since Mongo doesn't really support this, it would actually be bad if Minimongo did.
I suggest this thread be closed.

**Comment by dariusj18** [comment]
But Mongo does support this, it's in the documentation I linked to.

https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

**Comment by JanMP** [comment]
Read the 2nd paragraph in the orange box. The Server would allow it, but the drivers don't.

**Comment by dariusj18** [comment]
I see, I missed that, that is unfortunate. I guess then whether to close this ticket or not is a management decision on whether to leave tickets open if they are dependent on an external ticket.
