### ISSUE TITLE
Fails to Build When Too Many HTML Files

### ISSUE THREAD

**Issue by jlukic** [meteor/meteor#10028]
### Steps to Reproduce
* Create a meteor project with a large number of html files in `client/`. Me and @veered have repro'd with around 1500-2000 minimum. To be safe in repro you can use at least 3000 
* Run `meteor` in app

Touching new html files will cause issue to appear.

### Result
Meteor errors while building the project. The error is very long, and will show `Maximum call stack exceeded.` I've included the snippet that repeats below.

```javascript
 While processing files with templating-compiler (for target web.browser):

   /home/jack/.meteor/packages/templating-compiler/.1.3.3.19es70v.vxyp++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:320:29:
   Maximum call stack size exceeded
   at
  /home/jack/.meteor/packages/templating-compiler/.1.3.3.19es70v.vxyp++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:320:29
   at
   /home/jack/.meteor/packages/templating-compiler/.1.3.3.11uhi7d.jgc1++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish
(repeated many times)
   (/home/jack/.meteor/packages/templating-compiler/.1.3.3.11uhi7d.jgc1++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
   at
   /home/jack/.meteor/packages/templating-compiler/.1.3.3.11uhi7d.jgc1++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/home/jack/.meteor/packages/templating-compiler/.1.3.3.11uhi7d.jgc1++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-html-compiler/caching-html-compiler.js:40:5)
```

We've encountered this at Qualia for our main application, with `_.keys(Template)` ~ 1112 but it appears to be specifically related to the number of `html` files in the build directory. 

### Project to Repro
Reproduction in this repo. This is the meteor todo app with one commit to add 2000 html files
https://github.com/qualialabs/simple-todos

You can also create your own custom meteor project and just touch a bunch of html files in client
```
cd client/
irb
> (1..5000).each { |i| `touch template_#{i}.html` }
```

**Comment by benjamn** [comment]
For what it's worth, the `caching-compiler` package will no longer use the `async` library in Meteor 1.7.1: https://github.com/meteor/meteor/pull/9983/commits/ff82847cd6dfa31cb88f0e512a08c0935e5b500f

Can you try this test with `1.7.1-beta.5`?

**Comment by jlukic** [comment]
With `1.7.1-beta.5` it has same error but in `caching-compiler`. I guess this still depends on async?


```javascript
   /home/jack/.meteor/packages/templating-compiler/.1.3.3.107i1tj.v6gh++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/home/jack/.meteor/packages/templating-compiler/.1.3.3.107i1tj.v6gh++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-html-compiler/caching-html-compiler.js:40:5)
```

**Comment by benjamn** [comment]
Ah, that's because the `templating-compiler` package registers a build plugin that still uses the old version of `caching-compiler`.

You fix this by installing the `templating-compiler` packages locally:
```sh
cd path/to/simple-todos
mkdir -p packages
cd packages
ln -s /path/to/meteor/packages/non-core/blaze/packages/templating* .
```

The problem disappears for me after I do that, which is good news, but it's very useful to know these Blaze templating packages will need to be updated for Meteor 1.7.1.

**Comment by veered** [comment]
Thanks for the tips, I was able to workaround the issue by backporting https://github.com/qualialabs/qualia/pull/8512 to a fork of `caching-compiler`.

For some reason Meteor wasn't picking up on the fork of `caching-compiler` until I also forked `templating-compiler` and `caching-html-compiler` (without any modifications just putting them in `packages/`). Very strange.

Very fortunate that Meteor 1.7.1 looks like it'll fix the issues! Funny that the timing on that lined up so exactly with us hitting the template count limit.

**Comment by benjamn** [comment]
Packages that register compiler plugins get their own bundled copy of the packages used by the plugin, so you're stuck with whatever versions were current the last time the package was published. That's why we always have to publish a new version of `ecmascript` every time we republish `babel-compiler`, for example. Not defending the way it works, just explaining. 😉

**Comment by veered** [comment]
Ahhh... I thought I was going totally insane.

**Comment by veered** [comment]
@jlukic could you please close this issue since it's fixed in 1.7?

**Comment by elie222** [comment]
More info:

```
   /.../.meteor/packages/templating-compiler/.1.3.3.wb9s0z.mqocp++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/.../.meteor/packages/templating-compiler/.1.3.3.wb9s0z.mqocp++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-html-compiler/caching-html-compiler.js:40:5)
```

**Comment by elie222** [comment]
Sorry this seems to be the actual issue:

> While processing files with templating-compiler (for target web.browser):
packages/spacebars-compiler.js:791:15: {{> React}} must be used in a container element. Learn more at https://github.com/meteor/meteor/wiki/React-components-must-be-the-only-thing-in-their-wrapper-element

Couldn't see it in the infinite server logs, but was readable in the browser.
