### ISSUE TITLE
[1.7] production-only packages affect dev mode

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10020]
I have a package marked as `prodOnly: true`, this package depends on `qualia:profile` (which in itself is not marked as `prodOnly`). This is the only package with a dependency on `qualia:profile`

However, even in development mode, the code of `qualia:profile` seems to get executed, but the NPM dependencies of the package are not being installed, resulting in this error:

```
W20180622-17:02:30.265(2)? (STDERR) Error: Cannot find module '/node_modules/meteor/qualia:profile/node_modules/v8-profiler-node8'
W20180622-17:02:30.265(2)? (STDERR)     at resolve (/home/seba/dev/tests/meteorprodonly/.meteor/local/build/programs/server/npm-require.js:156:11)
W20180622-17:02:30.265(2)? (STDERR)     at resolve (/home/seba/dev/tests/meteorprodonly/.meteor/local/build/programs/server/npm-require.js:167:10)
W20180622-17:02:30.265(2)? (STDERR)     at npmRequire (/home/seba/dev/tests/meteorprodonly/.meteor/local/build/programs/server/npm-require.js:133:18)
W20180622-17:02:30.265(2)? (STDERR)     at Object.<anonymous> (/home/seba/dev/tests/meteorprodonly/.meteor/local/build/main.js:6:18)
W20180622-17:02:30.265(2)? (STDERR)     at Module._compile (module.js:652:30)
W20180622-17:02:30.266(2)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180622-17:02:30.266(2)? (STDERR)     at Module.load (module.js:565:32)
W20180622-17:02:30.266(2)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180622-17:02:30.266(2)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180622-17:02:30.266(2)? (STDERR)     at Function.Module.runMain (module.js:693:10)

```

Reproduction: https://github.com/sebakerckhof/meteor-prodonly

**Comment by veered** [comment]
Do you still get this error in dev when the `QUALIA_PROFILE_FOLDER` env variable is not set?

**Comment by sebakerckhof** [comment]
@veered no, only when the variable is set. But that's kinda beside the point.
I'd argue that if a package is only included by ancestors that are 'prodOnly', then it shouldn't be included in dev mode.

**Comment by veered** [comment]
Ok that makes sense; just wanted to make sure your development environment wasn't totally busted, since I'd feel personally culpable :)

**Comment by sebakerckhof** [comment]
Still happens in 1.8.2

**Comment by StorytellerCZ** [comment]
@sebakerckhof could you please update the reproduction to the latest Meteor to test if this is still relevant? I'm having some issues with the package getting V8 errors from it which I don't think is related to this issue.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
