### ISSUE TITLE
standard-minifier-js Safari syntax error with async/await class function.

### ISSUE THREAD

**Issue by Colkadome** [meteor/meteor#10034]
Hello,

I had an error with my minified javascript on my production app, and it resulted in a blank white screen on Safari for Mac. On mobile Safari, the app works as normal.

The error happens when a `return` statement is underneath an `await` call inside a `try catch` block, inside an `async` class method. I have tried some other code variations, but have only been able to reproduce it with the circumstances above.

Apologies if this is the wrong repo to report this issue, as I understand most of the minification is done with UglifyJS2?

## Reproduction

- Create minimal Meteor app with `meteor --minimal myApp`.
- Add the code below to `client/main.js`.
- Run `meteor --production` to cause minification.

```
function promiseReturningFunc () {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 1000, 'foo');
  });
}

class myClass {
  
  async myFunc() {

    try {

      await promiseReturningFunc();
      return;  // Removing this line this will remove the error.

    } catch (_) { }

  }
}
```

## The error

The following error is thrown in Safari:

`SyntaxError: Unexpected identifier 'e'. Expected a ';' following a return statement.`

The following minified code is produced, and is causing the error:

```
var require = meteorInstall({
        client: {
            "main.js": function() {
                function e() {
                    return new Promise((e, n) => {setTimeout(e, 1e3, "foo")})
                }
                class n {
                    async myFunc()
                    {
                        try {
                            return void await e()
                        } catch (e) {}
                    }
                }
            }
        }
    }, {
        extensions: [".js", ".json", ".html", ".css"]
    }),
    exports = require("/client/main.js");
```

## Specs

- Safari Version 11.0.2 (12604.4.7.1.4)
- macOS Sierra 10.12.6
- Meteor 1.7.0.3

Meteor package versions:
```
meteor@1.9.0
static-html
standard-minifier-css@1.4.1
standard-minifier-js@2.3.4
es5-shim@4.8.0
ecmascript@0.11.1
shell-server@0.3.1
webapp@1.6.0
server-render@0.3.1
```

**Comment by Colkadome** [comment]
I tried the new minifier (#10045) and still no luck.

`meteor create --minimal --release 1.7.1-beta.14 myApp`

I'm sure this issue is very rare for developers, but it might be worth leaving up in case somebody else experiences this. When I have time, I'll do more digging to see if its a terser issue.

**Comment by kzc** [comment]
Both `acorn` and recent versions of Node can parse the generated code above fine.

Node v8 and v10 can also execute this similar program without issue:

```
$ cat void_await.js 

    new class {
        async f() {
            try {
                return void await e()
            } catch (e) {}
        }
    }().f()
    function e() {
        console.log("PASS")
    }
```
```
$ cat void_await.js | node-v10.4.1 
PASS
```

If Safari 10/11 cannot successfully run the example above, then report the bug to the webkit project.

Assuming it is a webkit bug, if you can determine what minimal workaround to the `void_await.js` example above that will make it run successfully in Safari 10/11 (such as adding a semicolon or parentheses somewhere), then please open a ticket in the `terser` project with your findings - with a link to the webkit bug report.

Just for reference, here are two other known Safari 10/11  JS bugs:

* https://bugs.webkit.org/show_bug.cgi?id=176685
* https://bugs.webkit.org/show_bug.cgi?id=171041

**Comment by kzc** [comment]
It just occurred to me that Terser may already have a workaround for this Safari `await` bug.

```
$ node_modules/.bin/terser -V
terser 3.7.7
```
```
$ cat void_await.js | node_modules/.bin/terser -bcm
function e() {
    console.log("PASS");
}

new class {
    async f() {
        try {
            return void await e();
        } catch (c) {}
    }
}().f();
```
```
$ cat void_await.js | node_modules/.bin/terser --safari10 -bcm
function e() {
    console.log("PASS");
}

new class {
    async f() {
        try {
            return void (await e());
        } catch (c) {}
    }
}().f();
```
Notice the unnecessary parens that were placed around the `await` expression to placate Safari 10.

**Comment by smeijer** [comment]
This is quite an issue. I don't have a Mac, so I cannot test Safari. But it turned out my customers are unable to use my application due to a minification error. They only see a white screen:

```
Unexpected identifier 'e'. Cannot declare a lexical variable twice: 'e'
```

**Comment by smeijer** [comment]
@arggh, unfortunately; I'm already using `2.3.4`.

```
> meteor list

standard-minifier-css          1.4.1  Standard css minifier ...
standard-minifier-js           2.3.4  Standard javascript minifiers ...
```

**Comment by smeijer** [comment]
Am I the only one having this issue without a workable solution / work around?

**Comment by smeijer** [comment]
FINALLY, Safari is working again! I start to understand the saying: "Safari is the new IE" better by the day.

```js
import { setMinimumBrowserVersions } from 'meteor/modern-browsers';

setMinimumBrowserVersions(
  {
    mobile_safari: [9, 2],
    safari: Infinity,
  },
  'app',
);
```
