### ISSUE TITLE
meteor "\promise_server.js:218" error, app was run or create

### ISSUE THREAD

**Issue by archinmodi** [meteor/meteor#10030]
![screenshot 5](https://user-images.githubusercontent.com/18736127/41894886-0f2478ee-793e-11e8-972c-c85062da9f50.png)

meteor.js 1.7.0.3 is installed.

when i was create meteor app ,they given error "promise_server.js:218".

how can i solve this?

**Comment by preyasha2810** [comment]
@Archin-modi have you solve this error?

**Comment by Archin-modi** [comment]
Not solved, but upgrade to latest metro version. it's working.
