### ISSUE TITLE
.meteor/packages file relies on a specific order

### ISSUE THREAD

**Issue by bmajz** [meteor/meteor#10037]
Adding a package to a meteor app can break the app if it is added to the top of the packages file (prepended) instead of the bottom (appended). This is not terribly concerning if a user is simply adding packages to a new app via the **meteor add** functionality, however, in my case it broke a working app when upgrading past Meteor 1.6.1+

Repro steps:

- Create a new Meteor app with **meteor create**
- Edit the .meteor/packages file by adding **iron:router** to the top of the file (just below the comments and above **meteor-base**)

EXPECTED: App works, or at least gives a warning
ACTUAL: 
```
ReferenceError: Package is not defined
     at packages/underscore.js:1365:1
     at packages/underscore.js:1369:3
...
```

P.S. It appears when **meteor-platform** was removed in the 1.2 upgrade, the new **meteor-base** package was appended and **iron:router** ended up at the top of my app's packages file

P.P.S. I don't expect this bug to get fixed, but I wanted a searchable archive to save future victims of this behavior from wasting hours chasing down this type of an issue

**Comment by WilliamT-Streamba** [comment]
````
ReferenceError: Package is not defined
at packages/underscore.js:1365:1
at packages/underscore.js:1369:3
at /app/bundle/programs/server/boot.js:411:36
at Array.forEach (<anonymous>)
at /app/bundle/programs/server/boot.js:220:19
at /app/bundle/programs/server/boot.js:471:5
at Function.run (/app/bundle/programs/server/profile.js:510:12)
at /app/bundle/programs/server/boot.js:470:11
````
I had the same issue when deploying to Galaxy. Build would work locally but when deploying I would get the error above.

Moving `meteor-base` to the top of my __./meteor/packages__ file solved the problem.
