### ISSUE TITLE
Consider replacing uglify-es dependency in minifier-js package

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10042]
I'm not too familiar with the drama involved, but apparently some folks are changing `uglify-es` to either [terser](https://github.com/fabiosantoscode/terser) or [babel-minify](https://github.com/babel/minify).

The claims on `uglify-es` state that it's unmaintained among a few other bad things, and that it contains some serious bugs, known to create tricky situations especially with React.

[Parcel switching to terser](https://github.com/parcel-bundler/parcel/pull/1382)
[Ledger switching away from uglify](https://github.com/LedgerHQ/ledger-live-desktop/pull/782)
[Twitter thread about this
](https://twitter.com/greweb/status/1013122437884542978)

Like I said, I don't have any in-depth knowledge about the situation and this is just a heads-up about something I noticed by chance.

**Comment by benjamn** [comment]
Done! To try out the new minifier, run `meteor update --release 1.7.1-beta.14` or create a new app with `meteor create --release 1.7.1-beta.14 your-new-app`.

**Comment by arggh** [comment]
Well that was fast! 👍

**Comment by abernix** [comment]
I hadn't caught wind of this story change! Thanks for catching this and the suggestion, @arggh!  (And @benjamn for making the change!)
