### ISSUE TITLE
Cant read property "runClient" of undefined

### ISSUE THREAD

**Issue by DanteMA** [meteor/meteor#10046]
Im trying to start meteortesting:mocha via `meteor test --full-app --driver-package=meteortesting:mocha` but I get this error: 
```
client.js:42 Uncaught TypeError: Cannot read property 'runClient' of undefined
    at Object.runTests (client.js:42)
    at meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:1040
    at maybeReady (meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:821)
    at HTMLDocument.loadingCompleted (meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:833)
```

**Comment by benjamn** [comment]
What Meteor version (run `meteor --version` in your app) are you using?

**Comment by TheNewDante** [comment]
Uh sorry, 1.4.3.1

**Comment by DanteMA** [comment]
Where does the metertesting_mocha.js file gets saved? I searched manually but didnt find it

**Comment by sebitoelcheater** [comment]
any solutions? Version Meteor 1.4.2.7 here
