### ISSUE TITLE
*.graphql files don't trigger rebuild, aggressively cached

### ISSUE THREAD

**Issue by beaksandclaws** [meteor/meteor#10043]
Version 1.7.0.3 (according to google searches, occurred in 1.6.1 as well)
MacOS High Sierra

Expected behavior:
Changes to `*.graphql` files will trigger a rebuild of the Meteor server, including those `*.graphql` files.

Actual behavior:
Required to change a `*.js` file in order to trigger a rebuild of the server. In addition, that rebuild won't necessarily pick up changes to the `*.graphql` files. It seems like you need to wait an undetermined amount of time for whatever is caching the `*.graphql` files to expire before changes are picked up. This results in repeatedly changing a `*.js` until the server can properly rebuild with the changes in the `*.graphql` files.

Reproduction:
Clone the linked github repo, start the server, and watch the console. Uncommenting and saving `meteor-bug-example/imports/api/examples/Example.graphql#line4` will not trigger a rebuild.

In addition, uncommenting `meteor-bug-example/imports/api/examples/resolvers.js#line5` afterwards will trigger a rebuild, but not pick up the changes to `Example.graphql`. You will need to keep triggering rebuilds until the changes to `Example.graphql` are picked up. I haven't been able to figure out if it's based on a time-limit, the files changed, or just random. It does seem to take more than 5 minutes at times.

https://github.com/beaksandclaws/meteor-bug-example

**Comment by benjamn** [comment]
This seems like a problem with https://github.com/apollographql/meteor-integration, which implements the `apollo` package?

**Comment by stefanuddenberg** [comment]
I'm still encountering this kind of error where the app isn't rebuilt when changes are made to a .graphql file.
