### ISSUE TITLE
Facebook login not working in Chrome on Android/iOS

### ISSUE THREAD

**Issue by anthonymayer** [meteor/meteor#1004]
Repro steps:
1) Visit http://anthony-dev.meteor.com on Chrome for Android or iOS
2) Click "Sign in with Facebook button"
3) Enter Facebook credentials in new tab(authorize Facebook app if necessary) and submit

Expected: Facebook tab closes and user is logged into meteor app
Actual: Facebook tab takes awhile and eventually closes, but user is not logged into app. Repeated attempts ad clicking sign in button also don't log user in.

Meteor version: 0.6.2.1

Best guess at fixing it:
In 0c0345cc587246720e397b5d568c08fd6262b8d9 user agent detection was added for mobile browsers to display the mobile version of the Facebook login popup. Mobile Chrome is not on this list. I think that it would be best to just leave off the "display" param from the Facebook link and just allow Facebook to open the correct version of the popup. The commit doesn't indicate that the old version of the popup didn't work on all the devices, just that the version with display set is "smaller". It seems better to have working login popups over smaller ones(I'm not actually sure what it means that the popups are smaller). The other option is to add Chrome for Android and Chrome for iOS user agent detection, but this seems like it's likely to cause future issues(with new browsers, user agent changes, etc.). There also doesn't seem to be a simple user agent segment that can be used for detecting both versions of mobile Chrome.

Chrome for iOS user agent:

Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3

Chrome for Android example user agent:

Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B)
AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile
Safari/535.19

**Comment by brugnara** [comment]
adding `loginStyle` fixed for me on android but only if I login with chrome. If I choose to use facebook app, I'll end into a web-page container where I'm not logged in but in that page, if I redo facebook login, all goes ok. This is the web-page container shipped with facebook, the one that allow you to surf external web pages directly into the app without exiting the app. Any hint? Thanks.
