### ISSUE TITLE
[1.7.1-beta.15] Issues with importing package in Meteor, empty Object

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10065]
As usual I apologize for the unusual nature of our repo: we have a Yarn monorepo with a bunch of plugins that are required by the main Meteor app. I'm currently experimenting with the babel macro importAll, which can automatically import a bunch of packages/files based on a regexp, which means that we can automatically detect and import newly added packages, without having to manually add new import statements to the Meteor source code.

This works perfectly for all packages, except for some NPM packages, 'twit'/'Twitter' (all libraries I found to work with Twitter), as well as 'davefeedread' (to read RSS feeds).

In the futureNewnew branch (github.com/chili-epfl/FROG), I explicitly import the package into Meteor, and everything works perfectly. In the twitterRSS branch, I use importAll, and when I try to console.log the result of importing 'twit', I get an empty object.

I previously also noticed this occurring when I used `require` instead of `import`. However, when I just use `require('twit')` in a Node shell, and console log the result, I get a function, not an empty object.

Could you tell me why Meteor would treat some ways of importing different from other ways, and how I could overcome this? 

OSX 10.12.16

**Comment by KoenLav** [comment]
In our experience imports end up as empty objects if they somehow cause recursion; file A imports B, which imports C, which imports A (for instance).

We mainly saw this happening when importing by means of index.js files which export multiple files from the same directory (in this structure recursion tends to occur more easily).

**Comment by houshuang** [comment]
Yes, I've also found this - I had to move where I declared a function because of this. In this case, I would love for the Meteor build tool to give more explicit explanation, because this can be quite difficult to hunt down. However, in this case I'm importing an external npm package, so there should be no circular dependencies etc, and the issue seems to be a difference between how import, require, conditional import etc is handled. 

Would be happy to help debug this further if the Meteor team could point me in the right direction (where should I be looking)?

**Comment by houshuang** [comment]
So I thought I would try to inline the code, so I just copied all the code from `twit` to my library, and require it locally, and add the dependencies from `twit` to the dependencies from my library... And now `twit` loads OK, but I get an error stating `Promise is not a constructor` (it requires `bluebird`) - so now _its_ dependencies are not importing properly, this is an evil circle.

Again, if I try just node require in that directory with nothing special, it works perfectly...

**Comment by houshuang** [comment]
Anything I can do to help debug this?

**Comment by dmihal** [comment]
I'm seeing this issue on Meteor 1.8.0.1, are there any workarounds?

**Comment by ericmcgregor** [comment]
I'm having a tough time with the faker.js and casual.js libraries on 1.8.1.

**Comment by harryadel** [comment]
@ericmcgregor Thanks, mate. Worked for me 👍

**Comment by trusktr** [comment]
I'm having this issue in Meteor 2.5.6 still. I thought maybe it was a `moment` lib issue, but then I switched to `day.js` and same issue.

**Comment by trusktr** [comment]
Opened a new Meteor issue with reproduction: https://github.com/meteor/meteor/issues/11900
