### ISSUE TITLE
30-40 seconds build and rebuild times with meteor test

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#10069]
Our rebuild times with `meteor test` have skyrocketed to 30-40 seconds for every file change. 

I've tried to use `qualia:profile`, but I'm left with massive amounts of anonymous/fiber/underscore functions doing a lot of things except being clear about what they're doing.

Could someone with a bit of experience reading CPU profiles take a quick look at them and help identify what the potential problem(s) could be?

I keep having these kinds of issues with Meteor and would love to be able to better diagnose and fix them.

[profiles.zip](https://github.com/meteor/meteor/files/2188094/profiles.zip)

Using Meteor 1.6.1.1

**Comment by Floriferous** [comment]
Maybe related to #9969

**Comment by veered** [comment]
A lot of the rebuild time is spent doing file IO. Are you using an SSD?

Do you have a lot of stuff in `node_modules/`? The fact that it recently skyrocketed could be caused by adding a large new NPM package.

Also, it's possible that Meteor 1.7 could help your issues.
