### ISSUE TITLE
download speed is too slow from china

### ISSUE THREAD

**Issue by imhazige** [meteor/meteor#10060]
The download speed from china is too slow.  if you are using aws, that's will be the problem, could you set up a mirror for china user?

**Comment by imhazige** [comment]
please immediately consider our pain while we are very interest in the meteor framework.
 Downloading meteor-tool@1.7.0_1...        [==                       ] 7% 3477.0s

**Comment by goodideal** [comment]
suggest using vpn if in China mainland

**Comment by BodhiHu** [comment]
same issue here
using a vpn is still very slow (though youtube, google .etc are loading fast):

```
Downloading meteor-tool@2.1.1...          [                            ] 0% 0.0s
```
