### ISSUE TITLE
Testing on my local network no longer works because url is set wrong without setting ROOT_URL

### ISSUE THREAD

**Issue by schlaegerz** [meteor/meteor#10072]
This bug is a regression in Meteor 1.7, it worked fine in 1.6

Expected behavior:
From a different device on my network in can go to the ip address and have a fully functioning website
eg: 192.168.0.5:3000

Actual behavior:
I get an initial load of the webiste package, but then I get a websocket failure:

browser.js:169 WebSocket connection to 'ws://localhost:3000/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

And none of the actual data works.

If I setup the ROOT_URL in the environment this works fine so this isn't the end of the world so it is possible for me to test everything, but there are some packages I use that depend on the ROOT_URL being localhost for developing testing, so that means to test everything I need to keep changing the ROOT_URL in my environment settings which is a huge inconvenience.

In the past I've used my computer as a localhost server with 10 devices connected to it, so this is a new problem, and not related to my actual device

**Comment by LoriKarikari** [comment]
#9928
