### ISSUE TITLE
[1.7] When methods err on server, the error stack is just [object Object]

### ISSUE THREAD

**Issue by s7dhansh** [meteor/meteor#10078]
Whenever a Meteor.method execution fails on server, the exception stack is shown as `[object Object]`. Till Meteor 1.6, proper stack trace was displayed.

For instance,

Meteor 1.6
```
Exception while invoking method 'user.xyz' { stack: 'ReferenceError: test is not defined\n    at MethodInvocation.user.clearTokens (imports/startup/server/accounts.js:69:16)\n    at
MethodInvocation.methodMap.(anonymous function) (packages/montiapm_agent.js:2735:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n
  at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/montiapm_agent.js:2623:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)\n    at Session.sessionProto.protocol_handlers.method (packages/montiapm_agent.js:2622:44)\n    at packages/ddp-server/livedata_server.js:559:43',
I20180717-19:32:43.417(5.5)?   source: 'method' }
```

Meteor 1.7
```
Exception while invoking method 'user.xyz' [object Object]
```

**Comment by pasharayan** [comment]
Here's a temporary workaround while Meteor confirms its an issue for multiple people:

In Meteor.startup (while in server):

```
import util from 'util';

const originalMeteorDebug = Meteor._debug;
  Meteor._debug = (message, stack) => {
    if (Meteor.isDevelopment) {
      console.log('===== message =====', message);
      console.log('===== stack =====', stack);
      console.log(util.inspect(stack, false, null))

    }
    return originalMeteorDebug.apply(this, arguments);
  };

```

Credit to rjdavid on this thread for taking us 90% of the way to a fix: https://forums.meteor.com/t/error-messages-in-server-now-show-as-exception-while-invoking-method-methodname-object-object-since-upgrading-to-1-7/44542/4

**Comment by Floriferous** [comment]
Yep, seeing this as well.

**Comment by Floriferous** [comment]
The fix has not been working for me in the past few weeks, I guess it depends on the type of error. Here's what I see (have copy paste problems):

<img width="1453" alt="screen shot 2018-09-17 at 10 12 09" src="https://user-images.githubusercontent.com/10428082/45612116-38f5e300-ba62-11e8-8b27-493e8686e277.png">

Really slows down development when you have to manually put try-catch blocks around your own code.

**Comment by jamesmillerburgess** [comment]
This is happening for us as well. Thought I was doing something wrong until I saw this issue just now!

**Comment by houshuang** [comment]
I keep having the Meteor development server dying randomly, with this message

```js
/Users/stian/.meteor/packages/coffeescript/.1.0.17.ztkmml.8voq++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
[object Object]
```

Very annoying, especially when you don't notice and are waiting for a window to reload, etc.

**Comment by lmachens** [comment]
@benjamn I tried it out in two projects.
It works well in the first project, but the error is not printed in the second project. Then I removed kadira (https://github.com/lmachens/kadira) and the error message is printed like expected.
So I think it is related to kadira / mdg:meteor-apm-agent.

**Comment by zodern** [comment]
It is a bug in kadira. I fixed it in `montiapm:agent` with

https://github.com/monti-apm/monti-apm-agent/commit/abdfefa6edb68afa462f768dbf240a37437d0c47
https://github.com/monti-apm/monti-apm-agent/commit/aad278a45824b7218ba5dcd561df185abf16c884

**Comment by lmachens** [comment]
Thx @zodern this fixes it. See https://github.com/lmachens/kadira/commit/707a7776ba2f6b2c9304a1fe9b9042ca45b66afc

**Comment by Floriferous** [comment]
Thanks @lmachens, works like a charm :)
