### ISSUE TITLE
Multiple login handler logic in accounts-base flawed

### ISSUE THREAD

**Issue by corecache** [meteor/meteor#10079]
Versions:
accounts-base: 1.4.0
accounts-password: 1.5.0
meteor: any

The theory:
The accounts-base "runLoginHandlers" method states:
> Try all of the registered login handlers until one of them doesn't
> return `undefined`, meaning it handled this call to `login`. Return
> that return value.

During my quest to add an accounts-ldap module, I've tried adding another login handler for ldap. This login handler would verify a username|email/password based proceed with a login if successful and fail with an undefined so that a local password or other login handler could still proceed with the login.

After debugging accounts-base and accounts-password I've stumbled upon the impression that accounts-password throws errors when it can't find any local users, leading accounts-base to wrap up the error and proceed with the error as a defined result, instead of an undefined. 

This means that as soon as accounts-password or any other unbehaving loginHandler is loaded, no other login handler has a chance to react for themselves.

Fixing the "tryLoginMethod" in accounts-base did yield better results, especially when removing the forwarding of the error object as the login result. Although that was just a prototype fix to find the error. There are probably better ways to fix this in a sane and proper way.

**Comment by menelike** [comment]
I think that https://github.com/meteor/meteor/blob/af26e8b052a5135033e561cf4e4347eee585ab3b/packages/accounts-password/password_server.js#L283 is causing your problem.

Login handler determines if they should run based on the given options. You shouldn't use the key `password` if you don't want `accounts-password` to handle the login.

**Comment by corecache** [comment]
That is some weird logic there. I only want to extend an existing project with another "ldap" loginHandler by simply registering a new loginHandler. I certainly don't want to fiddle around with the already existing loginHandlers just to extend the possibilities of login types.
