### ISSUE TITLE
Segmentation fault (core dumped) on 32-bit platforms

### ISSUE THREAD

**Issue by j18ter** [meteor/meteor#10080]
This is likely the same as #9987, which was recently closed without solution.

Commit 5c1ba3a85ec17141f02c61cea03044596c9b4a78 added the following flag to the exec command in the main meteor script: ``--max-old-space-size=4096``

This either needs to be reduced somewhat, perhaps use 3072, or there needs to be a check for platform and if it is 32-bit platform a lower number must be used for that case. 4096 amounts to all addressable memory on 32-bit platforms.

The crash happens on 32-bit Linux platforms every time one runs meteor.

**Comment by benjamn** [comment]
What version of Meteor are you using?

**Comment by j18ter** [comment]
Was using Meteor 1.7.0.3.
