### ISSUE TITLE
[1.7.1-beta.19] Error: cyclic dependency detected when using MongoDB Atlas

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10087]
I tried using MongoDB Atlas and the system auto generated a MONGO_URL in this format:

`mongodb+srv://<USERNAME>:<PASSWORD>@cluster0-da3xd.mongodb.net/<DB>?retryWrites=true`

When I run the app, I was getting this errors

```
/home/rj/.meteor/packages/meteor-tool/.1.7.1-beta.19.jv82qt.q8od++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
                                             throw(ex);
                                             ^

 Error: cyclic dependency detected
     at serializeObject (/home/rj/.meteor/packages/npm-mongo/.3.0.7.88ubwo.3fs6j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:331:34)
     at serializeInto (/home/rj/.meteor/packages/npm-mongo/.3.0.7.88ubwo.3fs6j++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:934:17)
```

I have reasons to believe that this is happening even before 1.7.1-beta. My current fix is to remove `?retryWrites=true`

When I searched, this problem is not unique to meteor. Many projects were having problems with the MongoDB Atlas URL. This was recently fixed in Mongoose: https://github.com/Automattic/mongoose/issues/6109

**Comment by rj-david** [comment]
Here was this history from Mongoose with the related issue:

`fix: bump mongodb -> 3.0.11 to avoid cyclic dependency error with retryWrites #6109`

**Comment by rj-david** [comment]
This was fixed in mongodb driver for node version 3.0.9: https://github.com/mongodb/node-mongodb-native/blob/v3.0.9/HISTORY.md

> mongo-client: support retryWrites in connection strings (bdf0a24)

**Comment by benjamn** [comment]
So you're saying we should just bump the [`mongodb` version used by the `npm-mongo` package](https://github.com/meteor/meteor/blob/e91b3776e54ca9e1607bf89e0cebd32170eb2c1d/packages/npm-mongo/package.js#L11) to 3.0.9 to fix this?

**Comment by rj-david** [comment]
Yes. At least version 3.0.9 should fix this issue.

**Comment by jancurn** [comment]
For a reference, this just bit us too. We're on Meteor 1.8 and using Atlas MongoDB version 3.6.8. With `&retryWrites=true` in MONGO_URL, the number of database connections kept growing and many queries would time out, making the app unusable. When we removed the parameter, everything started to work well again. It would be worth to mention this in Meteor documentation.
