### ISSUE TITLE
EJSON: can crash 1.5+ server if Meteor.user() is called during instantiation of an EJSON type

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#10084]
This is the root cause of an error I already reported as #8950, but wasn't able to track down to its root cause until I did yet another thorough investigation today. And here it is:

- Assume you have defined an `EJSON` type, based on a class named `Notification`
- The constructor of this class calls `Meteor.user()` to set the sender of the notification
- Now during a Meteor method, an object of this type is being created and stored to a collection
- The receiver of the notification has subscribed to this collection to receive new notifications
- This causes a call to `EJSON.fromJSONValue()`, to send it over via DDP

The method `fromJSONValue()` wraps the constructor call inside a `Meteor._noYieldsAllowed()` block, for whatever reason. This causes the `Meteor.user()` call to fail, with this error message:

```
I20180719-21:40:31.860(2)? Error: Can't call yield in a noYieldsAllowed block!
I20180719-21:40:31.860(2)?     at Function.Fiber.yield (packages/meteor.js:677:11)
I20180719-21:40:31.860(2)?     at Function.wait (/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.19bnlyx.auvu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:187:14)
I20180719-21:40:31.860(2)?     at Future.wait (/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.19bnlyx.auvu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:448:10)
I20180719-21:40:31.860(2)?     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1017:47)
I20180719-21:40:31.860(2)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1051:22)
I20180719-21:40:31.861(2)?     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1061:10)
I20180719-21:40:31.861(2)?     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1085:17)
I20180719-21:40:31.861(2)?     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:875:44)
I20180719-21:40:31.861(2)?     at MongoConnection.findOne (packages/mongo/mongo_driver.js:782:56)
I20180719-21:40:31.861(2)?     at Mongo.Collection.findOne (packages/mongo/collection.js:334:29)
```

Even if you catch this error (as I did, in a try-catch-block), this can cause the whole server to crash, with this error message:

```
W20180719-21:40:31.888(2)? (STDERR) /Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.19bnlyx.auvu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180719-21:40:31.888(2)? (STDERR) 						throw(ex);
W20180719-21:40:31.888(2)? (STDERR) 						^
W20180719-21:40:31.889(2)? (STDERR) 
W20180719-21:40:31.889(2)? (STDERR) Error: expected to be _runningOrRunScheduled
W20180719-21:40:31.889(2)? (STDERR)     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:805:11)
W20180719-21:40:31.889(2)? (STDERR)     at packages/meteor.js:796:12
```

Funny thing is: This doesn't happen all the time. Sometimes, the subsequent method code runs through without crashing, sometimes it does not. And sometimes, after the server crashes and is auto-restarted, the methods runs trough again without any problems, sometimes it does not. It seems as if this exception is triggering a race condition inside the `fibers` package.

In effect this means, that `Meteor.user()` may not be called inside the constructor of an EJSON type, which is needed in my use-case. If I remove this call, everything works as expected.

Another thing I noticed: The code works more reliably on 1.5, but on 1.6 it will crash nearly all the time on the first attempt. In my case, the `ejson` library updated from `1.0.13` in 1.5 to `1.1.0` in 1.6. Funny thing is, the `_noYieldAllowed()` call had been there for many years. The only change that happened in 1.6 was to convert it to ES6 arrow syntax: https://github.com/meteor/meteor/commit/c6bddb331a8fd8c24336c6a7232406a3f108a6b5#diff-91868601b1609aa65a70a2ee9d2ec610R200

**Comment by derwaldgeist** [comment]
In principle, it is documented that `Meteor.user()` cannot be called during a publish. But in this case, instead of reporting an error, the server just crashed with a weird error message in `fibers` instead of reporting the cause in a readable way.

**Comment by mitar** [comment]
In general it would be great if EJSON would support async operations. :-( #6103

**Comment by derwaldgeist** [comment]
I wasn't aware of this limitation.
