### ISSUE TITLE
Safari 5.1.7 on Windows 10 isn't Supported Yet?

### ISSUE THREAD

**Issue by mu-hasan** [meteor/meteor#10086]
**Meteor Version**: 1.6.1.1
**Operating System**: Windows 10
**Web Browser**: Safari 5.1.7 for Windows

You can directly open my WebApp at http://dev.web.klikchat.com and then open the web browser's console to check the error `unexpected token '='`. I'm not sure this is a bugs from Meteor or a bugs from Safari Browser

**Comment by StorytellerCZ** [comment]
I don't see anything on Firefox. Is there any trace to where this is coming from?

**Comment by mu-hasan** [comment]
It work well on Chrome, Firefox, and Safari (macOS). But when open from Safari (Windows), it will be blank page and there is an error `unexpected token '='`

**Comment by mu-hasan** [comment]
If I open from Safari (Windows), it's blank like this picture

![screenshot from 2018-07-20 16 44 11](https://user-images.githubusercontent.com/8762248/42995998-76a3f8da-8c3c-11e8-91a4-8394d2d92ad7.png)
<br/>
![screenshot from 2018-07-20 16 43 36](https://user-images.githubusercontent.com/8762248/42995999-76d321fa-8c3c-11e8-9058-8f29749fa7d0.png)

**Comment by klaussner** [comment]
Do you get the same error with an unminified build?

I'm not sure if Meteor still supports such old browsers. Safari for Windows has been discontinued by Apple in 2012 and hasn't received any security updates since.

**Comment by mu-hasan** [comment]
I do not know what did you mean with `unminified build`. But it's working (with some bug) when I run using command `$ meteor run`. After it's deployed to server using command `$ meteor run`, it's blank like [this](https://github.com/meteor/meteor/issues/10086#issuecomment-406549628)

I got reference from [here](http://www.meteorpedia.com/read/Supported_Browsers) about Meteor's Supported Browser. I think according to that reference Meteor should be working on Safari 5.1.7

**Comment by benjamn** [comment]
Safari 5 is ancient, and [its usage is at 0.01% worldwide](http://browserl.ist/?q=safari+5), which doesn't even begin to approximate its usage just on Windows. You may be able to get a minimal Meteor app to work in Safari 5 or Internet Explorer 6 (try starting with `meteor create --minimal`), though your mileage may vary. We're not going to spend any effort supporting browsers that virtually no one uses, especially since the hacks required would hinder development in more recent browsers.

**Comment by mu-hasan** [comment]
Is there a way to check and provide info to users that the browser used is not supported?

**Comment by smeijer** [comment]
@mu-hasan, something like this: https://browser-update.org/en ? Or https://github.com/burocratik/Outdated-Browser/tree/master ?

Or show your warning based on `Meteor.isModern`

**Comment by aoede3** [comment]
For reference: this error you've detailed is directly related and replicable with the following https://github.com/meteor/meteor/issues/8928
