### ISSUE TITLE
onExternalLogin(func) handler behaves differently for existing user and new user

### ISSUE THREAD

**Issue by gerwinbrunner** [meteor/meteor#10097]
When using the onExternalLogin handler it behaves differently if the user already exists or not.

Consider the following handler:
```
Accounts.onExternalLogin( (options, user) => {
  const newUserData = _.defaultsDeep({ profile: options.profile, appState: 'installed' }, { profile: user && user.profile} );
  return newUserData;
});
```

This is what happens:

1. New User
for a new user only the `profile` gets set. The `appState` is missing!

2. Existing User
when you then again log in thru the external service, the `profile` is updated and the `appState` is set.

meteor code of the handler:
https://github.com/meteor/meteor/blob/release-1.7.1/packages/accounts-base/accounts_server.js#L142

**Comment by gerwinbrunner** [comment]
I figured out that the issue is in [insertUserDoc](https://github.com/meteor/meteor/blob/release-1.7.1/packages/accounts-base/accounts_server.js#L1055)
more specific that the [defaultCreateUserHook](https://github.com/meteor/meteor/blob/release-1.7.1/packages/accounts-base/accounts_server.js#L1500) only sets the profile

**Comment by gerwinbrunner** [comment]
My workaround for now is a custom `onCreateUser` handler

```
Accounts.onCreateUser( (options, user) => {
  const newUserData = _.defaultsDeep({ }, options, user );
  return newUserData;
});
```

**Comment by jamesmillerburgess** [comment]
Is this behavior only in the 1.7.1 beta or is it in earlier versions of accounts as well?
