### ISSUE TITLE
[1.7.1-beta.21]  Error in OAuth Server: header.reduce is not a function

### ISSUE THREAD

**Issue by nick-gudumac** [meteor/meteor#10094]
It seems like the last update to accounts packages (modernization) breaks twitter-oauth package. 

Error logged on the server when attempting to authenticate:
`Error in OAuth Server: header.reduce is not a function`

Related commit:
https://github.com/meteor/meteor/commit/c8f4ba74c74bdee3793f49aad3bb469e0cc1d62d#diff-6954d371e89d59bb7c5ffa2e6d80194f

**Comment by jamesmillerburgess** [comment]
Thank you for testing this out and finding a big bug!

There are a number of things wrong with that reduce function. I'll try to get to fixing it in the next day or so and look for similar errors.

**Comment by benjamn** [comment]
@jamesmillerburgess Please do have a look at fixing that, or let me know if you run out of time.

**Comment by nick-gudumac** [comment]
Thank you for your efforts @jamesmillerburgess 

I've just tried beta 22 and it looks like there is still some issues left:
`Error in OAuth Server: headers.map is not a function`

Perhaps we need to guard this line as well?
https://github.com/meteor/meteor/blob/af26e8b052a5135033e561cf4e4347eee585ab3b/packages/oauth1/oauth1_binding.js#L103

**Comment by jamesmillerburgess** [comment]
Thank you again for testing and picking up the slack on these changes! 👍

I’ll submit a fix as soon as I can and take a closer look at all the map
and reduce functions.

**Comment by benjamn** [comment]
I believe this is fixed in the latest beta (`1.7.1-beta.23`+).
