### ISSUE TITLE
Local web server dies in background

### ISSUE THREAD

**Issue by davinderkumar** [meteor/meteor#10096]
Meteor : 1.6.1

Assets from local web server fail to load when app is put in background and phone is locked.
Probably, local webserver dies as app is suspended from background.

There are few tickets in which this issue was reported last year : 
https://github.com/meteor/meteor/issues/7590
https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27

Do I need to use cordova-plugin-meteor-webapp plugin to resolve this issue? or there is fix for this in latest versions?

Thanks

**Comment by macrozone** [comment]
cordova-plugin-meteor-webapp should already be in your .meteor/cordova-plugins

check if you have version 1.6.0 or above
