### ISSUE TITLE
Meteor Vuejs. [Vue warn]: Error in destroyed hook: “TypeError: Cannot read property 'forEach' of null”

### ISSUE THREAD

**Issue by educob** [meteor/meteor#10093]
I have installed the latest version of meteor -vue in linux (linuxmint 18.3) and in windows (8.1) I am running this example: meteor-vuetify

In the javascript console (ctrl-shift-j) I get pages and pages with these 2 errors:

[Vue warn]: Error in destroyed hook: "TypeError: Cannot read property 'forEach' of null"
TypeError: Cannot read property 'forEach' of null
I get these, or similar errors in any app I develop. I am getting crazy.

Image: http://tinypic.com/m/jz9r9g/3 

How could I disable those messages? The code is generated. I don't know how to access the original code.

**Comment by educob** [comment]
Try this: modify this file: node_modules/vue-meteor-tracker/dist/vue-meteor-tracker.umd.js

Go to the error line and modify to check  that this._trackerHandles is not null:
if(!!this._trackerHandles) ...(old code)

**Comment by gustawdaniel** [comment]
Thank you @educob.

**Comment by gustawdaniel** [comment]
In

> https://github.com/meteor-vue/vue-meteor-tracker/pull/32

There was suggested that this package is abandoned. I recommend wait some days to explain this situation. Now I applied the following solution:

```
npm remove vue-meteor-tracker
npm i -s https://github.com/moslemir/vue-meteor-tracker
```

I tested this and it works.

**Comment by abernix** [comment]
The excellent `meteor-vue` integration is handled in a separate, community repository. Please report or find help for the problem you're looking for in its own repository: https://github.com/meteor-vue/vue-meteor

Thanks!
