### ISSUE TITLE
build time performance issues

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#10106]
We're facing some startup and rebuild issues with our production app. While on linux they are bearable on windows they are ~x10 worse (the provided logs are from linux though).

In our meteor setup we're using jest for unit testing and storybook for visual testing. Therefore we have some big dependencies in our node_modules folder(~200mb) which apparently slow down meteor a lot even if meteor is not using them at all. It seems like just adding some dependencies is responsible for a slow down of more than 100%. While that doesn't hurt that much at initial startup, it's especially annoying at rebuilds.

I created a small reproduction to show the issue with two dependencies: https://github.com/sakulstra/meteor-bugs/tree/storybook in our application we got some more testing specific deps like puppeteer, but I guess these two should be enough to showcase the issue - please let me know if I should add the other ones.

```
// raw project
| (#3) Total: 3,434 ms (Build App)
// with jest-cli & storybook
| (#3) Total: 5,253 ms (Build App)
```

Adding spaces to a completely empty server/main.js
```
// raw project
| (#10) Total: 351 ms (Rebuild App)
// with jest-cli & storybook
| (#10) Total: 507 ms (Rebuild App)
```

While the reproduction is about ms with more node_modules and some application code the issue seems to get more severe.

Related: #10064 

As a current workaround we moved the testing dependencies in a subfolder with a dedicated package.json which "works", but obviously isn't the nicest solution as we now install a lot of stuff multiple times and the testing/editor-autocomplete setup got slightly more complicated as node_modules have to be resolved from multiple places.

Did check meteor versions since 1.6 to the latest 1.7.1 beta and it doesn't seem to be specific to a meteor release.

**Comment by benjamn** [comment]
As a workaround in the meantime, have you tried adding big dependencies that are only used by jest or storybook to a `.meteorignore` file?

**Comment by sakulstra** [comment]
@benjamn you mean like node_modules/jest-cli?
tbh, i didn't think about that - although that was the solution to the issue in the linked issue :/

I guess it should be possible, but will by very cumbersome as I had to manually ignore all the packages and their dependencies which aren't used elsewhere.

**Comment by benjamn** [comment]
Right, I'm not suggesting `.meteorignore` as a final solution, or promising that it will be easy. It just might save your developers a lot of time, at least until we can find a better solution.

You might also try comparing the `METEOR_PROFILE` output for Linux vs. Windows, to see what specific parts of the Windows profile are taking so much longer.

**Comment by sakulstra** [comment]
seems like we went the easy road and no longer have developers working on windows :man_shrugging:
