### ISSUE TITLE
Remove underscore dependency from accounts-* packages

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#10105]
As Meteor in the process of stepping away from heavy `underscore` library, we are @VeliovGroup have already updated most of our packages removing `underscore` dependency.

Surprisingly (*at our end*) only `accounts-*` packages are left with `underscore` dependency.

If approved by MDG, I'm ready to send a PR removing `underscore` dependency from:

 - `accounts-base`
 - `accounts-password`

And later for other official `accounts-*` packages by MDG.

Let me know wdyt

**Comment by jamesmillerburgess** [comment]
Due to the changes in #9558, `underscore` will no longer be a dependency of any accounts-related packages in 1.7.1!

**Comment by dr-dimitru** [comment]
Closed in favor of #9558
@jamesmillerburgess thank you for amazing job!
