### ISSUE TITLE
Use private NPM package in meteor package

### ISSUE THREAD

**Issue by rockettomatooo** [meteor/meteor#10102]
I have a private npm package I want to depend on in a meteor package I'm about to write. 

Therefor I created a blank meteor package 
```bash
meteor create my-package --package
```
And then added the dependency to my npm package
```js
// package.js
...
Npm.depends({
  '@myorg/my-package': '1.0.0'
});
...
```
Whenever I try to add this package to my actual app, it gives me the following:
```bash
.../my-package$ meteor add my-package

...
error: there is no npm package named '@myorg/my-package' in the npm registry
```

I already tried to add an `.npmrc` file with a valid npm access token to the package folder but it didn't seem to work. And since I couldn't find much about `Npm`, I don't really know what else I could try.

I previously took this topic to [Stackoverflow](https://stackoverflow.com/questions/51539225/meteor-package-use-private-npm-package) but it couldn't really be answered so I'm opening this issue here.

SO suggested to link the private npm package as peer dependency in the project but is this really the *only* possible way?

Additional Info:
 - `meteor --version`: `1.7.0.3`
 - `meteor npm -v`: `5.10.0`
 - `meteor node -v`: `v8.11.3`

**Comment by dr-dimitru** [comment]
Hello @Rockettomatoo ,

I have expressive explanation about using local/private packages at [this thread](https://github.com/meteor/guide/issues/682).

Local:
```js
Npm.depends({
  "fs-extra": "file:///full/path/to/local/npm/package"
});
```

As I understood you publishing app to __private NPM organization__, then first tell NPM to use this org:
```shell
npm config set scope myorg
```


Then install it (__note: this may work only locally on your machine__):
```js
Npm.depends({
  '@myorg/my-package': '1.0.0'
});
```

**Comment by Rockettomatoo** [comment]
@smeijer my npm package is a general purpose package for usage at our company. The meteor package I want to create needs to have access to meteor variables like `Meteor` or `Mongo.Collection`. There for it has to be an atmosphere package.

**Comment by Rockettomatoo** [comment]
Hi @dr-dimitru ,

thanks for your suggestions. 

I used `npm login` to access my package for installing it in my project. The `meteor npm` command seems to use the logged in user to be able to install the package. `Npm.depends` doesn't seem to recognize either a logged in user nor a valid `.npmrc` file.

Since I'm working with colleagues on this project, a non-local dependent setup would be appreciated.

**Comment by dr-dimitru** [comment]
@Rockettomatoo have you tried to have it as outside of the package dependency (*in  `package.json`*), and access it inside package?

**Comment by coagmano** [comment]
Seeing the file url reminds me that you can use git+ssh urls for private repos, maybe that works?

```
Npm.depends({
  "@scope/package": "git+ssh://git@github.com:myorg/privateCode.git#v1.0.27"
});
```
https://docs.npmjs.com/cli/install

**Comment by jlsjonas** [comment]
This still seems like a very relevant issue today, `meteor npm config ls` indicates it knows about the `~/.npmrc` file, however `meteor npm install` ends up erroring out on authentication failure.
env vars are only a partial workaround as scopes can be on different registries.

**Comment by soolidtech** [comment]
Hi folks,
I think this issue should be reopened, as it's still relevant; and it looks like a proper bug.
What do you think ?
