### ISSUE TITLE
how to setup a meteor mirror?

### ISSUE THREAD

**Issue by bournewang** [meteor/meteor#10115]
Hello guys, I'm In China, I always get failed when I run '`meteor update`', most of the time, I got this error:

```
Sorry, this project uses Meteor 1.6.1.3, which is not installed and could not
be downloaded. Please check to make sure that you are online.
```
It seems that I can't access the update server from my location, so is there any way to build a mirror ? 
Please tell me, Thank you very much.

**Comment by mitar** [comment]
Hm, that has been done in the past. Maybe @laosb can help.
