### ISSUE TITLE
realy slow when i install meteor on centos with  curl https://install.meteor.com/ | sh

### ISSUE THREAD

**Issue by cuisc13** [meteor/meteor#10119]
realy slow when i install meteor on centos with  `curl https://install.meteor.com/ | sh`

**Comment by cuisc13** [comment]
![meteorslow](https://user-images.githubusercontent.com/5399228/43559204-a9e7d772-963f-11e8-86f3-ad7a32da58f8.png)

**Comment by rondip-geekyants** [comment]
![screen shot 2018-08-07 at 8 45 09 pm](https://user-images.githubusercontent.com/30038818/43784897-d55988aa-9a82-11e8-9aef-8752b2f7bfc9.png)
Same here when trying `meteor run`
