### ISSUE TITLE
Install should include windows-build-tools on Windows

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#10113]
I recently got a Windows machine, and first thing I tried was running Meteor on it, with a project I've been working on. I've also been working with some interns who are on Windows, and there are some onboarding challenges with Windows and Meteor. The hardest error to find info on was how to get node-gyp to compile bcrypt - that causes a few different errors depending on what's on your system (hence the vaguish specific error reported here).

To reproduce this, you'd probably have to:
1. Start with a fresh copy of Windows - or remove node.js and npm completely.
2. Install Meteor - bcrypt will not compile on a fresh windows install. It'll be missing a few things, including Python.
3. Try to install the dependencies of a project which uses a version of bcrypt that doesn't have a prebuilt binary (so that it falls back to build) - I am using version `^.3.0.0`. I usually use `meteor npm i` to grab node packages, and I think that's pretty standard.
4. This will probably fail for a couple of different reasons without good explanation - mostly related to missing build tools (even if you install Python manually - I tried that).

Here's the way to get it working:
1. Install Windows version of Node.js (which comes with npm).
3. Install the node package `windows-build-tools` globally with this command in an administrator Powershell or admin command prompt: `npm i -g windows-build-tools`
4. Restart Windows
5. Now when you run `meteor npm i` meteor should be able to compile bcrypt correctly.

It seems some of this could be avoided if `windows-build-tools` is installed through the choco package (I'm guessing this is where to do it) - or at least it may be useful to explain how to install `windows-build-tools` to get around the bcrypt build problems (and probably others).

(Another simple change to choco - maybe explain the virus scanner problem in the command line with a Note - it stalled on me several times before I figured out what to do to get it to install.)

Background - Node.js needs some build tools to be available for node-gyp to work properly. On macOS, enough build tools seem to be available that I've never seen these errors on macOS (either that or binaries are just always available - I don't know which). On Linux (Ubuntu for example) there are build tools can be installed with apt-get: `apt-get install build-essential` (same for WSL, though that has other problems).

**Comment by CaptainN** [comment]
That is the preferred way - also worth noting is that you need to have a separate node.js installed for that to work.

Some communication would at least be better (for all three platforms - macOS, Windows, Linux). The sense I get is that you don't have to install node.js (which is true on macOS and Linux) separately from meteor, but on Windows users may want to.

I actually thought that it would prompt me to install bcrypt (I remember that clearly always being nagged to install bcrypt from npm - and I still see that message when I deploy to now) - but I just tested to see when that prompt happens, and I didn't see that message now when I run locally. Has that message been removed?

**Comment by coagmano** [comment]
Looks like the wording comes from here:
https://github.com/meteor/meteor/blob/devel/packages/npm-bcrypt/wrapper.js

if you wanted to suggest an improvement

**Comment by am11** [comment]
bcrypt [releases](https://github.com/kelektiv/node.bcrypt.js/releases) inconsistently provide win32 binaries.

3.0.3 - No
3.0.2 -Yes
3.0.1 - No
3.0.0 - Yes
…

Perhaps meteor can lock down to fixed version of bcrypt that provides major binaries?

**Comment by coagmano** [comment]
Because bcrypt is installed directly by npm, I don't think it's feasible to fix which versions are available.

**But**, I think the idea of including `windows-build-tools` should be revisited now that the official nodejs installer for windows provides it as an option (since 10.12.0):
https://github.com/nodejs/node/pull/22645
