### ISSUE TITLE
[1.7.1-beta.27] DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10127]
The change of npm-mongo to version 3.1.x resulted to a deprecation warning:

`DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.`

**Comment by klaussner** [comment]
That will be fixed when #10058 is merged.

**Comment by benjamn** [comment]
This should be fixed now if you update to the latest beta: `meteor update --release 1.7.1-beta.32`
