### ISSUE TITLE
[1.7.1-beta.25] Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10126]
When I first run beta.25, I got this error message:

```
Unable to resolve some modules:

  "@babel/runtime/helpers/builtin/interopRequireDefault" in /home/rj/Projects/Bountee/imports/ui/navigations/AppNavigator.jsx (web.browser)
  "@babel/runtime/helpers/builtin/extends" in /home/rj/Projects/Bountee/imports/ui/navigations/AppNavigator.jsx (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime
```

My package.json had this after running the package install command above

```
"dependencies": {
        "@babel/runtime": "^7.0.0-beta.56",
```

Then I got this error:

```
W20180804-18:50:12.296(8)? (STDERR) /home/rj/Projects/Bountee/.meteor/local/build/programs/server/boot.js:475
W20180804-18:50:12.331(8)? (STDERR) }).run();
W20180804-18:50:12.332(8)? (STDERR)    ^
W20180804-18:50:12.332(8)? (STDERR)
W20180804-18:50:12.332(8)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180804-18:50:12.333(8)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180804-18:50:12.333(8)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180804-18:50:12.333(8)? (STDERR)     at Object.require (/home/rj/Projects/Bountee/.meteor/local/build/programs/server/boot.js:288:32)
W20180804-18:50:12.334(8)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180804-18:50:12.335(8)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180804-18:50:12.336(8)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180804-18:50:12.336(8)? (STDERR)     at livedata_connection.js (/home/rj/Projects/Bountee/.meteor/local/build/programs/server/packages/ddp-client.js:144:30)
W20180804-18:50:12.337(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180804-18:50:12.338(8)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180804-18:50:12.338(8)? (STDERR)     at Module.moduleLink [as link] (/home/rj/.meteor/packages/modules/.0.13.0-beta171.25.19sd9vv.ookh++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
```

I deleted .local and run `meteor npm update` and now I'm getting both errors above

**Comment by benjamn** [comment]
Right, you should stay on `@babel/runtime@7.0.0-beta.55` until you can update to Meteor 1.7.1-beta.27 (coming soon).

This error was the result of a deliberate breaking change in the runtime-related Babel 7.0.0-beta.56 packages (`@babel/runtime`, `@babel/plugin-transform-runtime`, `@babel/runtime-corejs2`): https://github.com/babel/babel/pull/8266

Removing the dependency on `core-js` is a big step in the right direction, but also a pretty big disruption between beta versions. I'm glad they did this before the final Babel 7 release.

**Comment by benjamn** [comment]
Ok, this should work if you update to the latest Meteor 1.7.1 beta and also update `@babel/runtime`:
```sh
meteor update --release 1.7.1-beta.27
meteor npm install @babel/runtime@latest
```
Please feel free to reopen if the same problem still happens!

**Comment by scottstensland** [comment]
just started to get this on my builds using

   meteor  1.7.0.3

even after issuing  meteor npm install @babel/runtime@latest

**Comment by benjamn** [comment]
@scottstensland `@babel/runtime@7.0.0-beta.55` is what you want ifyou’re still on 1.7.0.3. The `@babel/runtime@latest` version is appropriate only after you’ve updated to the latest Meteor 1.7.1 beta.

**Comment by rj-david** [comment]
@benjamn, is it possible to make some announcement related to this? Many meteor developers were getting stuck since yesterday. I'm not sure if the existing topics in the forum will suffice. Also considering that we are not yet in RC for 1.7.1 and not to be released anytime soon.

**Comment by benjamn** [comment]
I'm going to reopen this issue so that people can find it more easily when they come to report similar problems.

We could publish a new patch version of the Meteor `babel-runtime` package that complains if you install `@babel/runtime@7.0.0-beta.56`, but then folks would have to update `babel-runtime` before they saw the warning.

**Comment by hiei189** [comment]
I'm having a similar error after updating to 1.8.
It says that I should install @babel/runtime but I already did it, as suggested by the migration steps

**Comment by MHerszak** [comment]
@hiei189 same here. I am having problems, too. Updating to the latest version of babel doesn't help at the moment. Any suggestions?

**Comment by hiei189** [comment]
@MHerszak using `@babel/runtime@7.0.0-beta.55 `works fine. I'm still getting a warning though.

**Comment by linegel** [comment]
I'm on 1.7.0.3 and project not builds even with 7.0.0-beta.55

**Comment by miguelconde91** [comment]
I have Meteor 1.7.0.5, with 7.0.0-beta.55 and not work.
