### ISSUE TITLE
This project uses Meteor 1.7.1-beta.28, which isn't available on this platform. 

### ISSUE THREAD

**Issue by pgiani** [meteor/meteor#10135]
This appears when try to run meteor build on Ubuntu 16.04 

full message is:
`This project uses Meteor 1.7.1-beta.28, which isn't available on this platform. To work with this app on all
supported platforms, use meteor update --release METEOR@1.7.0.3 to pin this app to the newest compatible
release.`

**Comment by benjamn** [comment]
It should be published now. Try again?

**Comment by pgiani** [comment]
no still fails, may be I need to purge some cache ?

**Comment by benjamn** [comment]
1.7.1-beta.29 is out now, fyi

**Comment by pgiani** [comment]
Yes it works with 1.7.1-beta.29
