### ISSUE TITLE
Hangs in console after upgrade to 1.7.0.4

### ISSUE THREAD

**Issue by rooch84** [meteor/meteor#10139]
I've only just updated to 1.7.0.4 and already found it hanging twice in the console.  Even ctrl+c does't terminate it, I have to close the terminal window.  This hasn't happened at all with the previous version.

Meteor 1.7.0.4
Windows 10
Gitbash

**Comment by MurphyWants** [comment]
+1 here, using meteor in a team environment and meteor-tools just hangs on extraction. Windows 10, Meteor 1.7.0.4

**Comment by benjamn** [comment]
Yeah, [extracting with `7z.exe`](https://github.com/meteor/meteor/blob/aba03743ada9136138265d661e31b5aee9269058/tools/fs/files.js#L820) on Windows can be extraordinarily slow. However, I'm not sure that's the same problem @rooch84 is reporting. It sounds like the `meteor run` process (after successfully updating) isn't responding to `SIGINT` (control-c)?

**Comment by benjamn** [comment]
@rooch84 Have you tried running `meteor` via `cmd.exe` or PowerShell?

**Comment by NGTmeaty** [comment]
I can reproduce on Windows 10, Meteor 1.7.0.4. It tries to extract for 30-60 minutes, then re-downloads meteor-tool@1.7.0_4. control-c does not kill it.

**Comment by jcraigtt** [comment]
Yes, I as well.   Installing 1.7.04, 1.7.0.5 and the release/METEOR@1.7.1-rc.4 installed last night.  This week re-installed meteor via Choco with Elevated CMD.exe
All other installs with via Non-elevated CMD.exe

**Comment by NGTmeaty** [comment]
@benjamn would there be anyway to manually extract it? Can't get 1.7.0.4 or 1.7.0.5.
