### ISSUE TITLE
test-packages: _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by Sebl29** [meteor/meteor#10133]
We are currently suffering under a similar issue as https://github.com/meteor/meteor/issues/10126 , but only when executing tests in packges (something like TEST_WATCH=1 TEST_CLIENT=0 TEST_BROWSER_DRIVER=puppeteer meteor test-packages --driver-package meteortesting:mocha --port 3100).

`W20180806-16:53:08.924(2)? (STDERR) /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/boot.js:475
W20180806-16:53:08.987(2)? (STDERR) }).run();
W20180806-16:53:08.987(2)? (STDERR)    ^
W20180806-16:53:08.988(2)? (STDERR) 
W20180806-16:53:08.988(2)? (STDERR) TypeError: _interopRequireDefault is not a function
W20180806-16:53:08.988(2)? (STDERR)     at logging.js (/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/packages/logging.js:26:22)
W20180806-16:53:08.988(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180806-16:53:08.988(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180806-16:53:08.988(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180806-16:53:08.988(2)? (STDERR)     at /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/packages/logging.js:376:15
W20180806-16:53:08.989(2)? (STDERR)     at /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/packages/logging.js:383:3
W20180806-16:53:08.989(2)? (STDERR)     at /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/boot.js:411:36
W20180806-16:53:08.989(2)? (STDERR)     at Array.forEach (<anonymous>)
W20180806-16:53:08.989(2)? (STDERR)     at /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/boot.js:220:19
W20180806-16:53:08.989(2)? (STDERR)     at /tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
`

**Our versions:**
Meteor 1.7.0.3
"@babel/runtime": "7.0.0-beta.55", // from file "package-lock.json"
logging@1.1.20 // from file ".meteor/versions"

While the test-runner (in watch mode) is running, I can see many files named "interopRequireDefault.js":
`/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/@babel/runtime/helpers/esm/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@babel/runtime/helpers/builtin/es6/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@babel/runtime/helpers/es6/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/babel-runtime/helpers/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/johanbrook_publication-collector/node_modules/babel-runtime/helpers/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/lmieulet_meteor-coverage/node_modules/babel-runtime/helpers/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/@babel/runtime/helpers/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@babel/runtime/helpers/interopRequireDefault.js
/tmp/meteor-test-run1xfftsc.vzhk/.meteor/local/build/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js`

Running meteor is no problem, only executing tests. If anybody knows a workaround, plz share. We already switched to @babel/runtime": "7.0.0-beta.55" as seen in issue 10126, but this did not help. 
IMHO many other developers (with tests in packages) would also suffer under this issue.
Thx

**Comment by Sebl29** [comment]
Hi benjamn, thx for the fast reply.
We are unsure, whether we understood the problem completely. We were on version 7.0.0-beta.51 (without leading "^"), and suddenly this morning we could not execute our tests. No changes to any dependency version these days. So we are still unsure why the test-packages command does suddenly get this error. 

Without changes in packages.json, packages-lock.json and .meteor/versions, I would expect that the build result to be equal after the weekend. But as I can not reconstruct the build from friday, I can not compare whats different. How to solve such a problem?

**Comment by benjamn** [comment]
In this case, I believe the problem is that npm dependencies are automatically installed in the temporary test app created by `meteor test-packages`, so you're getting the latest version of `@babel/runtime`, because that's the default behavior for `npm install`.

Are you running `meteor test-packages` in an application directory with a local `packages` directory? If, so make sure you have `"@babel/runtime": "7.0.0-beta.55"` in the `dependencies` section of the app's `package.json`, rather than something like `"@babel/runtime": "^7.0.0-beta.55"`, which allows 7.0.0-beta.56 to get installed by accident.

**Comment by Sebl29** [comment]
yes, we have local packages in the `packages` folder and I execute the command in the app-folder.

As written above, we had it always _without_ the leading "^": until this morning in "7.0.0-beta.51", then changed to "7.0.0-beta.55"; but without success.
Searching in the project, there is no other match for "@babel/runtime", which could have  other version-descriptions.

**Comment by benjamn** [comment]
Ok, please try running
```sh
meteor update --release 1.7.0.4-rc.1
```
With `1.7.0.4-rc.1`, I was able to run `meteor test-packages` in an example application without running into the problem you reported, so I believe it may be solved!

**Comment by benjamn** [comment]
Can you give that command a try? We'd like to release 1.7.0.4 ASAP if it solves this problem for you.

**Comment by Sebl29** [comment]
yes, test running as before. Thx.

**Comment by sebakerckhof** [comment]
We also had this error and can also confirm 1.7.0.4-rc.1 fixes it.

**Comment by benjamn** [comment]
Running `meteor update --release 1.7.0.4` should fix this once and for all!
