### ISSUE TITLE
Add vue-simple-todo Tutorial 

### ISSUE THREAD

**Issue by riiccardo** [meteor/meteor#10145]
pls add example for vue and how to integrate vue, meteor and mongodb collections.

i found this on web [VueMeteor](https://github.com/meteor-vue/vue-meteor)
          
but it's better if it gets added to the site not just vue-icon

**Comment by eladcandroid** [comment]
Great idea.. can anyone move it forward?

**Comment by ashish979** [comment]
Will there be any official support for vue in meteor in 2019?

**Comment by StorytellerCZ** [comment]
I think this is more appropriate thread: https://github.com/meteor/meteor-feature-requests/issues/300
Efforts for Vue tutorials are already underway from my understanding.

**Comment by riiccardo** [comment]
@StorytellerCZ 

so pls make PR to add it ...but they must acc ur pull request anyway thanks
