### ISSUE TITLE
LitElement: simple import of { LitElement, html } throws errors

### ISSUE THREAD

**Issue by aadamsx** [meteor/meteor#10141]
I'm trying to integrate LitElement templating (new Polymer base class LitElement) into Meteor but I'm running into a build issue simply adding the following import statement:

```javascript
\\ client\index.js
import { LitElement, html } from '@polymer/lit-element';
```

The error:
```javascript
Uncaught SyntaxError: Unexpected token { 

modules.js?hash=182125a3fa97eaa24f6d313584ca593c3aed2103:984 
```

This error above points to this module:

![image](https://user-images.githubusercontent.com/5341158/43871443-4f13592c-9b42-11e8-9114-7e5f174309cd.png)

I'm using Meteor 1.7.1-beta.29.

Most all the details are posted here on the forum: 
https://forums.meteor.com/t/litelement-import-litelement-html/45042?u=aadams

Here's the issue I posted on the lit-element repo:
https://github.com/Polymer/lit-element/issues/142#issuecomment-411595139

-----

The feedback I got from one of their engineers:

@Westbrook:

In one of the screenshots above notated as "Points to this location:" the code is being delivered as:

function() {
  import {...
import statements have to be at the root. If meteor is building the code that way, it needs to transpile imports into something else for that to work.

-----

I've provided a reference repo here: https://github.com/aadamsx/meteor-lithtml

I can provide more info as needed.

**Comment by benjamn** [comment]
Replied on the forum thread: https://forums.meteor.com/t/litelement-import-litelement-html/45042/6
