### ISSUE TITLE
While upgrading to 1.7.1-beta.31

### ISSUE THREAD

**Issue by pgiani** [meteor/meteor#10144]
`**$ meteor update --release 1.7.1-beta.31**
=> Errors while initializing project:                                              
                                              
While selecting package versions:
error: unknown package: mongo-decimal
Required by: mongo 1.6.0-beta171.31
Required by: mongo 1.6.0-beta171.31

`

Tested on OSX 10.13.6

**Comment by benjamn** [comment]
Ah yes I forgot to publish the `mongo-decimal` package (a new non-core package). Try again?

**Comment by pgiani** [comment]
yes it works now
