### ISSUE TITLE
1.7.1-beta31 - IE 11 screen is blank / Access is Denied File: channel.html

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#10163]
Using 1.7.1-beta31 ... everything works fine on Chrome, Firefox, Safari... but IE11 the screen is blank

![screen shot 2018-08-17 at 10 35 26 am](https://user-images.githubusercontent.com/7233741/44241757-47ee3900-a209-11e8-9ea4-16a2b0b02ff1.png)

![screen shot 2018-08-17 at 10 32 16 am](https://user-images.githubusercontent.com/7233741/44241704-f2199100-a208-11e8-8352-530d48543756.png)
![screen shot 2018-08-17 at 10 32 06 am](https://user-images.githubusercontent.com/7233741/44241705-f2199100-a208-11e8-9068-ed8beab3192b.png)

Any ideas pls?

**Comment by benjamn** [comment]
That seems like a problem with the Strip `<iframe>` that you're embedding. Do they support IE11?

**Comment by adamgins** [comment]
Yep, this is all working fine with Meteor 1.6.0.x ... just happened as we upgraded to the 1.7.1 beta ... 

Working if related to my meta `<meta http-equiv="X-UA-Compatible" content="IE=edge">` Seems weird that it will start giving hassles now.

**Comment by adamgins** [comment]
I am not code any `setMinimumBrowserVersions` ... is this something I need to do explicitly with 1.7.1?

**Comment by adamgins** [comment]
@benjamn wondering if IE11 is be using the legacy browser package and it is not... ie I need to use `setMinimumBrowserVersions` to force it to be legacy?

I tried to add 

```
import {
  setMinimumBrowserVersions,
} from "meteor/modern-browsers";
setMinimumBrowserVersions({
  chrome: 45,
  firefox: 44,
  edge: 17,
  ie: Infinity,
  mobileSafari: [10, 3],
  opera: 32,
  safari: [11, 1],
  electron: [0, 36],
}, "async/await service workers");
```

to my `server`.. not 100% sure where I am meant to be inserting that code as when I tried via `lib` I got an error that it did not know what `setMinimumBrowserVersions` is

**Comment by adamgins** [comment]
@benjamn https://github.com/meteor/meteor/issues/9818 is there a way to force all IE to be legacy, to test this assumption?

**Comment by benjamn** [comment]
Can you evaluate `Meteor.isModern` in the IE11 browser console?

**Comment by adamgins** [comment]
I am getting ... some weird errors now... seems like Meteor not loading
I added this to a file on the server

```
import {
  setMinimumBrowserVersions,
} from "meteor/modern-browsers";

setMinimumBrowserVersions({
  chrome: 49,
  firefox: 45,
  edge: 12,
  ie: Infinity,
  mobile_safari: [9, 2],
  opera: 36,
  safari: 9,
  electron: 1,
}, "minimum versions for ECMAScript 2015 classes");

```
![screen shot 2018-08-17 at 12 28 41 pm](https://user-images.githubusercontent.com/7233741/44244845-3f056380-a219-11e8-990d-ec61a93daea7.png)


So `Meteor.isModern` won't even run

**Comment by adamgins** [comment]
@benjamn the error directly above for some reason the IE Javscript interpretter/compiler does not like something like

```
someFunc = function(){
  		const selfSomeFunc = this;
		this.someObj = {
			foo:"bar"
		}
		this.anotherFunc = function(){
			if (selfSomeFunc.someObj.foo === "bar"){
                              return "boo";
                         }

		}
	}
```

it's dying on the `if (selfSomeFunc.someObj.foo === "bar"){`  which works in Chrome, Safari & Firefox.

Also the other errors (eg Stripe) have gone away, but I suspect they are network latency and will come back, once the above error is fixed.

Not sure if the above approach is bad code or a better way to do it... but still seems weird that it works on Meteor 1.6

Also wondering if the local packages need to include some minimum browser code... or does it inherit this from there server?

Any ideas appreciated?

**Comment by adamgins** [comment]
Doh... I have ES2015 script in a custom npm package I am importing... mmm... not sure how how get to use the polyfills - need a tutorial in context of a Meteor project ??? I should close this. Any help appreciated... I will move to a Forum question https://forums.meteor.com/t/how-do-we-support-ie-with-ecmascript-in-a-custom-npm-package/45179

**Comment by adamgins** [comment]
https://github.com/meteor/meteor-feature-requests/issues/6

**Comment by adamgins** [comment]
@benjamn I am a bit confused I have `ecmascript` package installed but seem to still be getting ES6 code in an IE11 browser... on both Meteor 1.6.1.3 and Meteor 1.7.1 see this links for details pls https://forums.meteor.com/t/how-do-we-support-ie-with-ecmascript-in-a-custom-npm-package/45179 not sure if I should re-open this issue?
@robfallows FYI
