### ISSUE TITLE
*.test.* files not loaded

### ISSUE THREAD

**Issue by cmoses8626** [meteor/meteor#10170]
When running `meteor test --once --driver-package meteortesting:mocha` tests in the /tests directory are properly run and output to the console, but any `*.test.*` files outside of this directory are not loaded. Even when there's a syntax error in the `*.test.*` file, I get no error messages or failed tests. When deleting `"testModule": "tests/main.js"` from package.json, the `*.test.*` files are run, but then `/tests/main.js` is not run.

I'm on Meteor 1.7.0.5. [Here's a link](https://github.com/cmoses8626/app-boilerplate/blob/master/imports/api/users.test.js) to an example test file with a syntax error in the imports directory that is not loaded.

There's a [discussion on the Meteor Forum](https://forums.meteor.com/t/docs-and-tutorial-should-be-updated-for-running-meteor-test/43976) that mentions the same issue, but don't think the docs have been updated yet, and it doesn't resolve the issue with being able to run both unit test files and tests in /test.

Still learning Meteor and how to do testing, so thanks for the help!

Below is the console output without first deleting the testModule stanza. You'll see it does not load and run `users.test.js` (which has a syntax error), which lives in the /imports/api directory.
```
I20180820-11:30:39.851(-4)? --------------------------------
I20180820-11:30:39.851(-4)? ----- RUNNING SERVER TESTS -----
I20180820-11:30:39.851(-4)? --------------------------------
I20180820-11:30:39.852(-4)?
I20180820-11:30:39.852(-4)?
I20180820-11:30:39.853(-4)?
I20180820-11:30:39.857(-4)?   meteor-boilerplate
=> Started your app.

=> App running at: http://localhost:3000/
    ✓ package.json has correct name
    ✓ server is not client?
I20180820-11:30:39.875(-4)?
I20180820-11:30:39.877(-4)?
I20180820-11:30:39.877(-4)?   2 passing (24ms)
I20180820-11:30:39.877(-4)?
I20180820-11:30:39.877(-4)? Load the app in a browser to run client tests, or set the TEST_BROWSER_DRIVER environment variable. See https://github.com/meteortesting/meteor-mocha/blob/master/README.md#run-app-tests
```

**Comment by jamesmillerburgess** [comment]
I believe this is the intended behavior. If you specify an entry point with `testModule` meteor does not eagerly load test files that match the standard regular expressions `*.test.*`, `*.tests.*`, `*.spec.*`, and `*.specs.*`.

And when you do not have an entry point specified, the default meteor behavior takes precedence, which eagerly loads those files.

Not loading files from the `/tests` directory is also intended. From the [guide](https://guide.meteor.com/structure.html#javascript-structure):

> - **tests**
> 
> Any directory named `tests/` is not loaded anywhere. Use this for any test code you want to run using a test runner outside of Meteor’s built-in test tools.
