### ISSUE TITLE
Broken polyfill for parameter defaults with arrow functions on Edge

### ISSUE THREAD

**Issue by jimrandomh** [meteor/meteor#10171]
An issue on LessWrong (https://github.com/LessWrong2/Lesswrong2/issues/783) turned out to be caused by an incorrect polyfill: on Microsoft Edge, an arrow function in a class which has a default value for one of its parameters gets rewritten for Edge (but not for Chrome) to a broken function which refers to a nonexistent `_this`. (More details on the LessWrong issue).

**Comment by benjamn** [comment]
This seems like a Babel issue? Not exactly the same, but possibly related: https://github.com/babel/babel/issues/8019
