### ISSUE TITLE
1.6.1 and 1.7 completely changes behaviour of find() with undefined parameters, should be documented better

### ISSUE THREAD

**Issue by markreid** [meteor/meteor#10172]
_Have updated the original post because the problem's actually bit worse than I thought initially_

Howdy, 

Was doing an upgrade to 1.7 today and noticed an issue that appears related to using `{ someValueToQuery: undefined}` in a `find()` call.

To reproduce, fire this up in a fresh app:

```
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import assert from 'assert';

Meteor.startup(() => {
  const Things = new Mongo.Collection('things');

  Things.remove({});
  Things.insert({
    foo: 'bar',
  });

  
  const data = {};

  const things = Things.find({
    foo: data.foo
  }).fetch();

  assert.equal(things.length, 0);
});
```

This runs fine in **1.6.0.1**, the find query returns nothing. 
In **1.6.1 and above** the assertion breaks because the query finds the first document in the collection.

This was brought up in this PR https://github.com/meteor/meteor/pull/9444, where @romainkoenig has said "hey this is a pretty major change to legacy code, maybe it should be documented more clearly than being tucked away in a point release", and got a reply to the effect of "oh well it's still technically correct." 

Whether the change in behaviour is the RIGHT way to do it or not is beside the point. This is an absolutely critical change to the behaviour of find() queries and I can only assume that people haven't kicked up more of a fuss about it because they haven't noticed it's broken. 

I'm not voting to change the behaviour, I'm respectfully asking that the 1.6.1 changelog be retrospectively updated to mention the fact that in 1.6 a query with `undefined` did one thing, and in 1.6.1 it does something completely different. 

### This bug report should include:
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
- [x] The operating system you're running Meteor on.
- [x] The expected behavior.
- [x] The actual behavior.
- [x] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)

**Comment by markreid** [comment]
So I guess if it's agreed that `ignoreUndefined` is a good config option for the Mongo driver, there's not much that can be done about this, apart from potentially adding some upgrade notes to the changelog. 

I think a basic explanation of what's happening is that this query:

```
Collection.find({
  property: {
    $ne: undefined
  },
});
```

in 1.6.0.1 is passed to Mongo as:

```
Collection.find({
  property: {
    $ne: null,
  },
});
```

But in 1.6.1 and above is passed to Mongo as:

```
Collection.find({
  property: {},
});
```

Which are 2 pretty different queries. 

So the onus is now on the developer to ensure that they understand the difference.

**Comment by markreid** [comment]
Okay so another example we just dug up...

This code here
```
const requests = UserRequests.find({
groupId: 'foobarqux'
  $or: [{
    fromRoleId: userRole._id,
  }, {
    toRoleId: userRole._id,
  }],
});
```

Used to be sent to Mongo as:

```
const requests = UserRequests.find({
groupId: 'foobarqux'
  $or: [{
    fromRoleId: null,
  }, {
    toRoleId: null
  }],
});
```

But is now sent as 

```
const requests = UserRequests.find({
groupId: 'foobarqux'
  $or: [{}, {}],
});
```

Am I seriously the only person that this is affecting? Or did everybody else read the release notes in such fine-grained detail that they picked it up and modified their code to suit. 

These are two *completely* different queries. I honestly can't understand how this isn't worthy of some upgrade notes in the changelog, and I'm kind of amazed that nobody else appears to have been affected.

**Comment by menelike** [comment]
Still too late, but https://github.com/meteor/meteor/commit/b5081deb5f492a3695a4cdd912aa07894f2b7bc4 addresses this issue.

**Comment by markreid** [comment]
@menelike yes, the issue you linked _can be_ caused by the change to `ignoreUndefined`. There have been a couple of reports of people getting it in other circumstances though. 

I'm hoping to have some time next week to look at putting together a fix that will throw a clear error if your queries are using `undefined` keys.

**Comment by markreid** [comment]
closing this issue because a more obvious warning has been added to the changelog.
