### ISSUE TITLE
Failed to connect to static-meteor.netdna-ssl.com

### ISSUE THREAD

**Issue by carlbror** [meteor/meteor#10173]
Error message with `curl https://install.meteor.com/ | sh`:
Failed to connect to static-meteor.netdna-ssl.com port 443: Connection timed out

with just `meteor` on a project (after having manually installed meteor):
Sorry, this project uses Meteor 1.6.1.1, which is not installed and could not be downloaded. Please check to make sure that you are online.

This problem appeared just recently - one or two weeks ago it was working just fine. The problem comes up on a server in Singapore, but not on my home computer, so I'm guessing it's something with the particular connection of that serverhall to netdna-ssl. 

Maybe similar to [ Geographical CDN issue causing meteor & package install problem #6960 ](https://github.com/meteor/meteor/issues/6960)? Or is the connection error on my end?

Here's what I got from from traceroute:

> traceroute to static-meteor.netdna-ssl.com (151.139.107.3), 30 hops max, 60 byte packets
 1  111.221.44.1 (111.221.44.1)  0.471 ms  0.465 ms  0.457 ms
 2  10.13.196.5 (10.13.196.5)  1.386 ms  1.367 ms  1.364 ms
 3  v1051.core1.sin1.he.net (27.50.33.209)  1.354 ms  1.346 ms  1.341 ms
 4  100ge6-2.core1.mrs1.he.net (184.105.65.14)  138.509 ms  138.480 ms  138.494 ms
 5  100ge6-1.core1.mil2.he.net (184.105.80.13)  144.739 ms  144.709 ms  144.725 ms
 6  * * *
 7  * * *

**Comment by abernix** [comment]
Any luck with this?  I'm not aware of any problems, but as you identified with #6960, it wouldn't be the first time that network topography has affected the bootstrap CDN!

Does [this link](https://packages.meteor.com/bootstrap-link?arch=os.osx.x86_64) work for you?  It should (at least, as of this writing) redirect to `https://static-meteor.netdna-ssl.com/packages-bootstrap/1.7.0.5/meteor-bootstrap-os.osx.x86_64.tar.gz` and is working for me.

**Comment by carlbror** [comment]
No, unfortunately I get the same error message when trying to run meteor (`Sorry, this project uses Meteor 1.6.1.1, which is not installed and could not be downloaded. Please check to make sure that you are online`). Similarly with 

wget https://packages.meteor.com/bootstrap-link?arch=os.osx.x86_64

I just get:

> --2018-08-29 20:07:45--  https://packages.meteor.com/bootstrap-link?arch=os.osx.x86_64
Resolving packages.meteor.com (packages.meteor.com)... 52.205.234.125, 34.197.181.113, 18.232.23.235, ...
Connecting to packages.meteor.com (packages.meteor.com)|52.205.234.125|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://static-meteor.netdna-ssl.com/packages-bootstrap/1.7.0.5/meteor-bootstrap-os.osx.x86_64.tar.gz [following]
--2018-08-29 20:07:46--  https://static-meteor.netdna-ssl.com/packages-bootstrap/1.7.0.5/meteor-bootstrap-os.osx.x86_64.tar.gz
Resolving static-meteor.netdna-ssl.com (static-meteor.netdna-ssl.com)... 151.139.107.3
Connecting to static-meteor.netdna-ssl.com (static-meteor.netdna-ssl.com)|151.139.107.3|:443... failed: Connection timed out.
Retrying.

**Comment by abernix** [comment]
I'm afraid this is a connectivity problem that seems to be isolated, since I'm able to access that exact NetDNA Singapore datacenter via http://151.139.107.3/.  You're getting a straight up connection timeout (not a missing resource), so that leads me to believe that you're somehow firewalled from that server.

I can debug a bit more, but could you share your own IP, found via http://checkip.amazonaws.com/? (Feel free to message it to me on forums.meteor.com, where I'm also username `abernix` if you're hesitant to share it here.)

**Comment by carlbror** [comment]
Well, now it's working! :-)

I sent a message to the server company to see if they knew what could be happening.

**Comment by abernix** [comment]
Great! (slash "strange"!)  It does seem that we have access to some pretty good diagnostics/logs so write back it happens again!

**Comment by ewyler** [comment]
This doesn't seem resolved (or, it was and is broken again) - I'm hitting the 416 error right now as referenced in https://github.com/meteor/meteor/issues/9997 - my IP is 71.192.160.152

```
$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7782    0  7782    0     0  38662      0 --:--:-- --:--:-- --:--:-- 38524
Downloading Meteor distribution
######################################################################## 100.0%
curl: (56) Unexpected EOF
Retrying download in 5 seconds...
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...

```

**Comment by ewyler** [comment]
FWIW this appears to have resolved itself for reasons unknown, the last install worked.

**Comment by izackv** [comment]
Just happen to me as well.
Since I'm locating in Israel, and this might be related to geolocation, I set my VPN to connect to NY server.
Once my communication went through the US, it solved all issues.
I suspect the server is more stable in the US than in some other distant countries.
So if anyone get the same issue, I suggest to try and connect through a VPN and try different locations until getting to one that is working...

**Comment by ShrabaneeM** [comment]
Facing the same issue. Any solution or cause for this?
I have tried several times.
Trying in Ubuntu 18.04.
