### ISSUE TITLE
[1.7.1-rc.4] `meteor build` does not copy local node modules to output bundle

### ISSUE THREAD

**Issue by carlevans719** [meteor/meteor#10177]
- [x] The version of Meteor showing the problem. 
**1.7.1-rc.4**
- [x] The last version of Meteor where the problem did _not_ occur, if applicable. 
**tested every minor version back to 1.4, issue is the same on each**
- [x] The operating system you're running Meteor on. 
**Ubuntu 18.04.1. Also happens on node docker images**
- [x] The expected behavior. 
**Local node modules which are not devDependencies should be treated the same when using the development server and in the production bundles**
- [x] The actual behavior. 
**Local node modules are stripped from the built bundle's node_modules folder, causing module resolution errors**
- [x] A **simple** reproduction! 
**See [this repo](https://github.com/carlevans719/meteor-node-modules-symlink-repro)**

Sometimes we need to ship proprietary node modules with application source code. What would be nice is if we could put it all in a folder (say `/vendor`) and then have all the applications which depend on the modules reference them by using the local module syntax in `package.json`. i.e.
```javascript
{
  // ...
  "dependencies": {
    "foo-module": "file:/path/to/vendor/dir"
  }
}
```

However, there doesn't seem to be a location for this folder that works;
- if the `vendor` folder is placed inside the application folder (whether at the top-level or in `/imports`, with or without `meteor.mainModule`) an error is thrown: `error: Symlink cycle detected at XXX`
- if the `vendor` folder is placed outside the application folder, it is not copied to the production bundle, causing unexpected runtime errors

I've had a scan through the [isobuild/builder.js](https://github.com/meteor/meteor/blob/devel/tools/isobuild/builder.js) and _think_ I understand the reasoning behind the behaviour seen in the first scenario (although I think we could maybe improve this to be smarter about knowing whether we are _actually_ in a symlink loop or not). That being said - I don't think this location is very valuable - "why not just `import '/path/to/module'` instead of masking it in a node module?".

The second folder location seems to have an actual use-case though. When two (or more) apps both want to share a private node module.

I think at the very least, the behaviour should be consistent - either local node modules which reside outside the application folder is supported and works in both dev / prod, or it is not supported and does not work in dev or prod.

**edit:** spelling

**Comment by benjamn** [comment]
Thanks for reporting this problem @carlevans719! This should be fixed if you run `meteor update --release 1.7.1-rc.7`. Please feel free to reopen if you discover otherwise!
