### ISSUE TITLE
Dynamic Imports with No Connection Error

### ISSUE THREAD

**Issue by Colkadome** [meteor/meteor#10182]
Hello,

When the page attempts to load a dynamic import while theres temporarily no connection, the import will fail and subsequent imports will attempt to load the non-existent module.

I have recently been trying Dynamic Imports with Meteor (and loving it), however this edge case may effect people whose internet periodically drops out. If this issue were fixed, I think it would work very nicely with `react-loadable` that makes use of a "retry" prop for this exact scenario.

I unfortunately do not know enough about the codebase to suggest a fix or anything, so apologies on that.

## Reproduction

1. Create minimal app with `meteor create --minimal myApp`.
2. Create/modify files according to the code listed below.
3. Run app with `meteor`.
4. Go offline (in Chrome, Inspect -> Network -> Offline).
5. Click "Test Button" to get `Error: Connection lost at XMLHttpRequest.xhr.onreadystatechange`.
6. Go online again.
7. Subsequent Test Button clicks will result in `Error: Cannot find module '/imports/test.js'`.

#### /client/main.html
```
<head>
  <title>Minimal Meteor app</title>
</head>

<body>
  <h1>Minimal Meteor app</h1>
  <button id="test">Test Button</button>
</body>
```

#### /client/main.js
```
document.getElementById("test").addEventListener('click', async () => {

  const { default: testImport } = await import('/imports/test.js');

  console.log(testImport);

});
```

#### /imports/test.js
```

export default "Content Here";

```

## Specs

- METEOR@1.7.0.5
- macOS Sierra 10.12.6
- Google Chrome (68.0.3440.106)

Meteor package versions:
```
meteor@1.9.0
static-html
standard-minifier-css@1.4.1
standard-minifier-js@2.3.4
es5-shim@4.8.0
ecmascript@0.11.1
shell-server@0.3.1
webapp@1.6.0
server-render@0.3.1
```

**Comment by Gariest** [comment]
Hello @benjamn, 
could you please look into PR I've made for this issue, if you have enough spare time?
Thanks!

**Comment by benjamn** [comment]
Can you test this again after running `meteor update modules-runtime`?

**Comment by Gariest** [comment]
Hi, I did. Worked as expected for me. 
Cheers!

**Comment by sferoze** [comment]
I ran `meteor update modules-runtime` and have verified the new version in versions file but when I try to load my meteor app offline I get a console error

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at dynamic-import.js:169
    at meteor.js:1223
```

which in dynamic-imports.js it is pointing to this function

```
return fetch(url, {
    method: "POST",
    body: JSON.stringify(missingTree)
  }).then(function (res) {
    if (! res.ok) throw res;
    return res.json();
  });
```
