### ISSUE TITLE
`Package._define is not a function` in 1.6.0.1

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#10183]
(Can't currently upgrade to 1.6.1 due to some dependency issues.)

Basically 1.6.0.1 has lost backwards compatibility with many packages due to this change.

I noticed the problems with `zodern:standard-minifier-js` but also `qualia:profile` and I'm sure many more. I suspect packages built with a certain version of Meteor are being bundled in a way that is no longer compatible with the older version of Meteor though their `package.js` says that they should still be.

Reproduction here: https://github.com/hexsprite/meteor-issue-package-define

Interesting fact: if you change a file and it causes Meteor to reload then all of a sudden it works. Some kind of bootstrapping code must be using the old version of `Package` perhaps?

```
$ npm start

> meteor-issue-package-define@ start /Users/jbb/co/meteor-issue-package-define
> meteor run

[[[[[ ~/co/meteor-issue-package-define ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While loading plugin `minifyStdJS` from package `zodern:standard-minifier-js`:
   packages/meteor.js:1457:9: Package._define is not a function
   at packages/meteor.js:1457:9
   at packages/meteor.js:1463:3


=> Your application has errors. Waiting for file change.
=> A patch (Meteor 1.6.1.4) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
```

**Comment by abernix** [comment]
`Package._define` is provided by the [`meteor` package](https://github.com/meteor/meteor/tree/master/packages/meteor).  What version of `meteor` do you show in this application's `.meteor/versions` file?  What happens if you run `meteor update meteor`?

**Comment by hexsprite** [comment]
Hi @abernix, thanks for helping me with this.

I just tried to update and it is already at the latest version (including the reproduction I provided).

```
$ fgrep meteor .meteor/versions
meteor@1.8.6
meteor-base@1.2.0
$ npm start

> meteor-issue-package-define@ start /Users/jbb/co/meteor-issue-package-define
> meteor run

[[[[[ ~/co/meteor-issue-package-define ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While loading plugin `minifyStdJS` from package `zodern:standard-minifier-js`:
   packages/meteor.js:1457:9: Package._define is not a function
   at packages/meteor.js:1457:9
   at packages/meteor.js:1463:3
```

**Comment by abernix** [comment]
@hexsprite I'd highly recommend working out the problems with the upgrade to a newer 1.6 version if possible (sorry, but 1.6.0.x was a relatively short-lived series, soon superseded by 1.6.1), but as a work-around, can you try pinning to exactly `meteor@1.8.4`?  See 4a913bbd699960bc110e561f14b16e0a917039fc.

**Comment by abernix** [comment]
To be honest, I'd expect that `meteor@1.8.6` should work too, since it was also published with 1.6.0.1 as per the intention of https://github.com/meteor/meteor/commit/4a913bbd699960bc110e561f14b16e0a917039fc's commit message.

**Comment by hexsprite** [comment]
1.6.1 introduced some incompatible changes in coffeescript and babel that are causing a ton of work for me to upgrade. So I can't easily do that yet.

I have tried pinning to 1.8.4 and same thing.

**Comment by abernix** [comment]
@hexsprite Given that Meteor 1.7.1 has some explicit fixes for CoffeeScript and Babel, including better interaction with Babel 7, have you given `1.7.1-rc.5` a try?
