### ISSUE TITLE
Cordova: Application Error: Network error (http://localhost:12576)

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#10180]
When developing and building for Android sometimes the following error comes up when running the app on Android:

Application Error: Network error (http://localhost:12576)

Making a new build, with completely the same code, fixes it. Only for the error to reappear again in a later build.

Anyone else experiences this and/or found a workaround?

**Comment by rj-david** [comment]
Are you running the build on the same phone where you are doing development?

**Comment by KoenLav** [comment]
I have my Android phone connected via USB + wifi to my laptop and use meteor run android-device from my laptop to run the application on my Android phone.

So the issue appears during development. 

Production builds also suffer from the same problem; about one in every 4 builds produces the same error (when installed and launched on a Android device).

The problem is not specific to any Android device, when a faulty build is produced all devices will error on this build.

**Comment by rj-david** [comment]
@KoenLav, I normally get this error when I installed a production build on a phone where I also used to run a development build (meteor npm run android)

The solution for me was to uninstall the development build first or vice-versa.

Now, if you are sure the android phone where it is installed does not have any other version of your app, then it can be a different problem

**Comment by KoenLav** [comment]
@rj-david that's interesting! I don't think this is the exact case we are experiencing, but I'll keep an eye on that.

The problem definitely appears on other devices as well (as in not the device I was developing on).

**Comment by crapthings** [comment]
@KoenLav 
do u build with --mobile-server ?
if u do, you should check your html head ROOT_URL is what u set before.

**Comment by nabiltntn** [comment]
It's true that Cordova behavior is so random on development.
- Check that your router configuration allows client communication
- Build again
- Restart router. Yeah , it sounds funny but worked for me 2 times

**Comment by KoenLav** [comment]
@crapthings I do not build with --mobile-server, simply consecutive runs of meteor run android-device (without any arguments) deliver these results.

I did however notices the last days that the first time I install a production app over a development app, or the other way around, the build is messed up. So it seems related...

@nabiltntn the router allows client communication and meteor run android-device works 80% of the time, but sometimes it just doesn't.

**Comment by mklebrasseur** [comment]
I have had this issue catch me many times, though recently 3 attempts and still would not work. I removed a recent change `<base href="/">` from my `<head>` and it seemed to go through without a hitch. I am not saying they are related as the `--server` functionality seems to work most of the time.
