### ISSUE TITLE
Extremely long build and rebuild times (80 seconds)

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10185]
METEOR@1.7.1-beta.31, Mac OSX 10.12.16

As always I apologize for the complexity of our repo. We have a main Meteor app, and a bunch of different plugins. I have experimented with how we include these in the Meteor app, and we're now trying the babel-macro importAll to automatically import packages based on a path regexp. These imports are all cached, to the point that we have to forcibly delete the cache when we add a new package. We have also switched to having Meteor build all of our external packages by symlinking them to the imports/packages directory, which reduces conflicts between Meteor and external Babel versions, etc.

However, build times have increased hugely. I'm not sure if it is having Meteor build our packages, the importAll macro, or new Meteor versions, but it seems to spend a huge amount of time analyzing imports. The biggest problem for us is the rebuild times - in [this gist](https://gist.github.com/houshuang/bb15fe117f8c663e39f328e0434c610f) you see that the initial build takes 87 seconds (this is after having run the server before, so there is already a cache). However, even worse is that just changing a single line in a core app file leads to a rebuild that takes 59 seconds! (I also keep getting messages about delayed legacy builds that take 40-60 seconds). Is there something about our setup that leads to the cache not being useful or is there anything we can do, this is really crippling our development workflow.

For comparison, a [gist](https://gist.github.com/houshuang/aa1dc54521477497f7c7fe8c5cf83503) of a build process where I removed all of our plugins - with a very normal build speed. Of course this also means removing thousands of lines of code, but the point is that for the rebuild this shouldn't make a difference, since I didn't touch a single of those lines of code in my edit...

Our repo is https://github.com/chili-epfl/FROG. Checkout, run ./initial_setup.sh (just yarn plus symlinking node_modules to the meteor directory), go to frog, and run meteor.

**Comment by fangjj** [comment]
me too，rebuild takes too long time.
 METEOR@1.7.0.5 mac 10.13.3

**Comment by benjamn** [comment]
I don't have any great news on the initial build front, but if you update your app to the latest 1.7.1 release candidate, I think you'll be much happier with your rebuild times:
```bash
meteor update --release 1.7.1-rc.9
```
When I run your app with `METEOR_PROFILE=20 meteor run`, rebuild times are down from 24-25 seconds to 4-5 seconds. Initial build times are about 60 seconds, which is a little better than before.

Here's the main commit responsible for this improvement: https://github.com/meteor/meteor/pull/9942/commits/881390c553f641d71ee6c4393f07e2057178eeec

**Comment by houshuang** [comment]
Thanks. On my laptop (which might be slower than your computer), the time it takes from I save a tiny change in Vim, until the webpage in my browser is reloaded and rendered, is 25 seconds, fairly consistently (after initial build etc). This is definitively much better (I really appreciate it!), but still not ideal. Especially for working with CSS/layout etc. Since all of our components are pure/don't depend on Meteor, my colleague had the idea of making a Create-react-app which just renders the components, to allow us to work on layout etc much more quickly. I also saw someone experimenting with using webpack just for the front-end. I don't really want to spend a lot of time on experimental build setups, but quick feedback when you are developing UIs are really important.

Anyway I really appreciate your feedback and continuous efforts to improve Meteor!

**Comment by CaptainN** [comment]
I was seeing this same issue on WIndows (a very long delay after the rebuild completes, before the browser can access the app again), but switched to building over a network in a VM (Ubuntu) - for me this took rebuild times from 1.5 minutes to under 10 seconds (debugging with the same Windows browsers). It sounds like you are not on Window (due to use of symlinks) which suggests the problem may not be Windows as I had originally assumed.
