### ISSUE TITLE
[1.7.1-rc5] Request for option to disable web.browser.legacy stage

### ISSUE THREAD

**Issue by pmcochrane** [meteor/meteor#10186]
The 1.7 pattern of building two version of the application - modern and legacy is a great idea in principle and should provide a smaller bundle for a modern browser. I'm all for this.

The problem however is the extra time required in the compilation phase during DEVELOPMENT. I don't really care if it needs compiled twice to build the production version of the code as that is not time critical. I know everything gets cached once it has been compiled but some changes need to process every file twice for the modern and legacy bundles (e.g. if you change a shared service that is imported to pretty much every file then every file gets recompiled - twice). 

The recent change in 1.7.1 to delay building the legacy bundle is a good idea however in my app it does not work as intended. I use angular-meteor's compilers and although the page refreshes just before the delayed legacy compilation phase begins, the server does not respond so you still have to wait for the legacy compilation to complete before the server will respond. An example:

```
I20180829-09:32:32.521(1)? [Paul Cochrane@10.41.9.42] (methodUserHistoryAdd) Success - logged display of patients 5b7bd2431b2d09152587bdef Mr PAUL COCHRANE (2111710210)
[Client-Modern] HTML Files Compilation: 323.819ms
[Client-Modern] Starting web.browser compilation process...
[Client-Modern] Source File Counts: {"app":{"typescript":148,"types":7,"other":1},"npm":{"typescript":724,"types":0,"other":5}}
[Client-Modern] Searching for typescript files took: 22.843ms
[Client-Modern] Setup up for compilation took: 119.733ms
[Client-Modern] Starting to compile source code...
[Client-Modern] Compiled 148 files. Compilation took: 21375.721ms
[Client-Modern] Finished compilation of web.browser at Wed Aug 29 2018 09:33:34 GMT+0100 (BST)    Compile Time: 21518.676ms
[Client-Modern] SCSS Files Compilation: 1318.602ms
=> Client modified -- refreshing[Client-Legacy] HTML Files Compilation: 391.129ms
[Client-Legacy] Starting web.browser.legacy compilation process...
[Client-Legacy] Source File Counts: {"app":{"typescript":148,"types":7,"other":1},"npm":{"typescript":724,"types":0,"other":5}}
[Client-Legacy] Searching for typescript files took: 19.783ms
[Client-Legacy] Setup up for compilation took: 110.158ms
[Client-Legacy] Starting to compile source code...
[Client-Legacy] Compiled 148 files. Compilation took: 30663.776ms
[Client-Legacy] Finished compilation of web.browser.legacy at Wed Aug 29 2018 09:34:10 GMT+0100 (BST)    Compile Time: 30794.203ms
[Client-Legacy] SCSS Files Compilation: 2793.662ms

=> Finished delayed build of web.browser.legacy in 37593ms
I20180829-09:34:26.051(1)? [NotLoggedIn@10.41.9.42] onValidateLogin (methodRefreshUserActivationStatus) Paul Cochrane is now Active
```

I understand that this could be seen an issue with the compiler but I'm not convinced.

My plea to @benjamn is please please please please please please can we just have a command line flag / environment variable to skip the whole legacy browser phase? The legacy compilation should be enabled by default but allow us to override it when we are developing our code in a modern browser and the legacy is not required.

Yours hopefully
Paul

**Comment by fangjj** [comment]
meteor update --release 1.7.1-beta.19 detail in https://github.com/meteor/meteor/issues/9948 comments

**Comment by pmcochrane** [comment]
Yes, I've looked at #9948 and @benjamn's pull requests. This is a follow up to both. 9948 talks about a command line option but this was not implemented as far as I can see. 

We need to convince @benjamn that an option to skip either the legacy or modern build stage is required as he did not want to implement this by default as it goes against meteor's philosophy of zero configuration.

I'm happy for it to produce both by default but waiting an extra 30 seconds for each code change at each compilation seems a bit unnecessary. Especially when I'm not using the legacy bundle during development.

**Comment by sebakerckhof** [comment]
related: https://github.com/meteor/meteor-feature-requests/issues/333

**Comment by benjamn** [comment]
Yes, let's continue this discussion in https://github.com/meteor/meteor-feature-requests/issues/333. Feel free to copy/paste old comments there. Thanks!
