### ISSUE TITLE
Minimongo sorting bug with deeply nested sort fields

### ISSUE THREAD

**Issue by AJohnDoe** [meteor/meteor#10192]
The same bug as filed in #8279 is still present.

Another test case can be found [here](https://github.com/AJohnDoe/mongo-sorting-issue). Just clone, install the necessary packages and navigate to the web page. This repo is running on Meteor 1.7.0.5

### Working case

Sorting by level1.0.sortField is ok:

Natural Order

[{"text":"Entry A","arr":[{"sortField":5}],"_id":"SPQyS2qDjsdRiZRc3"},
{"text":"Entry B","arr": [{"sortField":7}],"_id":"bMSx94phbxbPXDkRX"},
{"text":"Entry C","arr": [{"sortField":1}],"_id":"kH7NN7Pzs6yqRWuGz"}]

Ascending Order

[{"text":"Entry C","arr":[{"sortField":1}],"_id":"kH7NN7Pzs6yqRWuGz"},
{"text":"Entry A","arr":[{"sortField":5}],"_id":"SPQyS2qDjsdRiZRc3"},
{"text":"Entry B","arr":[{"sortField":7}],"_id":"bMSx94phbxbPXDkRX"}]

Descending Order

[{"text":"Entry B","arr":[{"sortField":7}],"_id":"bMSx94phbxbPXDkRX"},
{"text":"Entry A","arr":[{"sortField":5}],"_id":"SPQyS2qDjsdRiZRc3"},
{"text":"Entry C","arr":[{"sortField":1}],"_id":"kH7NN7Pzs6yqRWuGz"}]

### Not working case

Sorting with a field that is nested even deeper, for example, container.arr.0.sortField, fails for the ascending sort:

Sorting by container.arr.0.sortField

Natural Order

[{"text":"Entry A","container":{"arr":[{"sortField":5}]},"_id":"CvJFgtNuxF4uedAaK"},
{"text":"Entry B","container":{"arr":[{"sortField":7}]},"_id":"tEQqbXbQyYMf2HaBY"},
{"text":"Entry C","container":{"arr":[{"sortField":1}]},"_id":"NfWxP6Tn3wjbbcCkg"}]

Ascending Order

[{"text":"Entry A","container":{"arr":[{"sortField":5}]},"_id":"CvJFgtNuxF4uedAaK"},
{"text":"Entry B","container":{"arr":[{"sortField":7}]},"_id":"tEQqbXbQyYMf2HaBY"},
{"text":"Entry C","container":{"arr":[{"sortField":1}]},"_id":"NfWxP6Tn3wjbbcCkg"}]

Descending Order

[{"text":"Entry B","container":{"arr":[{"sortField":7}]},"_id":"tEQqbXbQyYMf2HaBY"},
{"text":"Entry A","container":{"arr":[{"sortField":5}]},"_id":"CvJFgtNuxF4uedAaK"},
{"text":"Entry C","container":{"arr":[{"sortField":1}]},"_id":"NfWxP6Tn3wjbbcCkg"}]

As shown above (this is the output from my test repo), the descending sort orders the documents correctly, while the ascending sort returns documents in the natural order.

**Comment by benjamn** [comment]
Possibly related to #10212? cc @mitar

**Comment by mitar** [comment]
I do not think so, because here sorting is explicitly listing which array element to use.

**Comment by sebakerckhof** [comment]
Can confirm it's not related
