### ISSUE TITLE
[1.7.0.5] cli command 'meteor login' fails on existing user

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#10198]
**Problem:**

When trying to use the cli command `meteor login` I will never be able to log in by typing username and password.

Meteor: 1.7.0.5
The last version of Meteor where the problem did _not_ occur, if applicable: Unknown
OS: Ubuntu 18.04

**The expected behavior.**

Should log me in, as described in the [docs](https://docs.meteor.com/commandline.html#meteorloginlogout).

**The actual behavior.**

Returns `Login failed.` and exits.

**Reproduction repo**

https://github.com/jankapunkt/meteor-cli-loginfail

**Manual reproduction**

- create new project, add `accounts-base` and `accounts-password` and install `bcrypt`.

```
$ meteor create projectname
$ cd projectname
$ meteor add accounts-base accounts-password
$ meteor npm install --save bcrypt
$ meteor npm install # this is not required but to prevent comments like "you need to enter meteor npm install"
$ meteor # => App running at: http://localhost:3000/
```

Add the following code to your `/server/main.js` file

```javascript
import { Meteor } from 'meteor/meteor';

Meteor.startup(() => {
  // code to run on server at startup
  if (Meteor.users.find().count() === 0)
    Accounts.createUser({username:"admin", password: "password"})
});
```

You can verify the created user in the mongo shell:

```
$ meteor mongo
MongoDB shell version v3.6.4
connecting to: mongodb://127.0.0.1:3001/meteor
MongoDB server version: 3.6.4
meteor:PRIMARY> db.users.find().pretty()
{
	"_id" : "gcxqLYxwW63A5aa4W",
	"createdAt" : ISODate("2018-09-06T07:52:14.538Z"),
	"services" : {
		"password" : {
			"bcrypt" : "$2b$10$krw0ifHGikRZ1XXxKff4puWwUD99z6VjWP48BbztLCqvd8ggeP2nS"
		}
	},
	"username" : "admin"
}
meteor:PRIMARY> 
```

- now open a new shell in the app directory and login using the cli tool

```
$ cd projectname
$ meteor login
Username: admin
Password: # type here "password"                               
Login failed.                                 
$
```

**Comment by klaussner** [comment]
`meteor login` is used to log in to a Meteor developer account (after registering on meteor.com), not an application-level account.

**Comment by jankapunkt** [comment]
*Facepalm* 

You are totally right, will close it.
