### ISSUE TITLE
Unexpected token export error when importing npm package that uses esm export

### ISSUE THREAD

**Issue by notacouch** [meteor/meteor#10203]
Hello,

I'm trying to get amCharts to work in MeteorJS as an npm package. Our latest version [uses es2015 module exports](https://github.com/amcharts/amcharts4/blob/4.0.0-beta.49/dist/es2015/core.js#L8), which does not seem to be supported in Meteor if it's within an npm package. I've also tried to get it to work by using the latest meteor, ecmascript, babel-runtime, several babel plugins (es6 to cjs, reify), and even esm, but no dice. Could use some guidance/help!

- The error occurs in both Meteor versions 1.7.0.5 and 1.7.1-rc6
- I'm using Windows 7, Chrome Canary Version 71.0.3544.2 (Official Build) (64-bit) and Firefox 61.0.2.
- Expected behavior: [According to documentation](https://docs.meteor.com/packages/modules.html), es2015 modules should just work.
- Actual behavior: 
Chrome:

![meteorjs error - unexpected token export in modules js](https://user-images.githubusercontent.com/2334143/45183005-d7777e00-b1f0-11e8-831b-f976836a3d2d.PNG)
![meteorjs error - error on es6 export 2](https://user-images.githubusercontent.com/2334143/45183015-dd6d5f00-b1f0-11e8-911b-a99a50540ff5.PNG)
Firefox:
> SyntaxError: export declarations may only appear at top level of a module modules.js:1001 

- I've provided steps below to reproduce the error in two ways: 1) You can try adding the npm package manually or 2) cloning this repo: https://github.com/notacouch/meteor-esm-export-bug/

### 1) Reproducing manually in a basic app generated via `meteor create`
```bash
meteor npm install --save @amcharts/amcharts4
```

Add the following to your client/main.js:
```javascript
import * as am4core from "@amcharts/amcharts4/core";
```

Run `meteor`.

### 2) Reproducing via repo

I've revisited the steps myself.

Cloned the repo:
```bash
git clone https://github.com/notacouch/meteor-esm-export-bug.git
```
output:
> Cloning into 'clonetest'...
> remote: Counting objects: 29, done.
> remote: Compressing objects: 100% (22/22), done.
> remote: Total 29 (delta 2), reused 25 (delta 1), pack-reused 0
> Unpacking objects: 100% (29/29), done.

```bash
cd meteor-esm-export-bug
```

Installed packages...
```bash
meteor npm install
```
output:

> added 233 packages from 276 contributors and audited 1324 packages in 31.152s
> found 0 vulnerabilities

Ran meteor...
```bash
meteor
```
output:
> => Started proxy.
> => Started MongoDB.
> => Started your app.
> 
> => App running at: http://localhost:3000/
>    Type Control-C twice to stop.

Any help would be appreciated.

Thanks!

**Comment by benjamn** [comment]
Does this symlinking strategy help? https://forums.meteor.com/t/litelement-import-litelement-html/45042/8?u=benjamn

**Comment by notacouch** [comment]
Thanks!

I've updated locally to 1.7.1-rc.7.

Tried following the commands via Cmder (which seems to have just copied the folders), even tried `mklink /j imports\links\@amcharts` which did create a junction in Windows (however, git doesn't detect it as a symlink I think?).

After I do that, do I have to change where I'm importing from? I.e.

```javascript
import * as am4core from "@amcharts/amcharts4/core";
```

If I keep it the same, I get the same error (whether the directory is a copy or a junction).

I changed the import to:
```javascript
import * as am4core from "../../imports/links/@amcharts/amcharts4/core";
```
output:
![meteorjs error - ood babel corejs internal 404](https://user-images.githubusercontent.com/2334143/45188419-309bdd80-b202-11e8-9e8b-f9b7c45a6fbb.PNG)



the `'./.internal/core/System'` comes from amcharts' core.js:
```
export { System, system } from "./.internal/core/System";
```

I updated @babel/runtime, that didn't change anything.

Here's a branch with a hard copy of the package in imports/links:
https://github.com/notacouch/meteor-esm-export-bug/tree/imports-links

**Comment by benjamn** [comment]
Ah, prefixing a file or directory with a `.` is a well-established convention to make Meteor ignore the file, so that it won't be compiled or bundled. In that context, it's unfortunate that this package chose to name one of its directories `.internal`. However, I think you can solve both the symlinking problem and the `.` problem by turning things around. Specifically, you can clone the package, modify it as necessary, and then `meteor npm install` it into your `node_modules` directory. This approach is essentially what I described in my first long response [here](https://forums.meteor.com/t/litelement-import-litelement-html/45042/6?u=benjamn).

I know you're on Windows, so I apologize for the UNIX-style `/` separators and Bash commands. Hopefully you can translate these commands to whatever Windows shell you're using:
```bash
git rm -rf imports/@amcharts
cd imports
git clone git@github.com:amcharts/amcharts4.git
mv amcharts4/dist/es2015 amcharts
rm -rf amcharts4
cd amcharts
mv .internal internal
# find and replace references to .internal with internal in all .js files
# warning: there are quite a few!
cd ../..
meteor npm install ./imports/amcharts
```
Once you've done all that, the following `import` should work in your `client/main.js` module:
```js
import * as am4core from "@amcharts/amcharts4/core"
```
The symlinking problem should go away because now `npm` is responsible for creating the symlink `node_modules/@amcharts/amcharts4`, rather than `git`.

**Comment by benjamn** [comment]
Opened a pull request demonstrating the sequence of changes needed to implement what I described above: https://github.com/notacouch/meteor-esm-export-bug/pull/1

**Comment by ericm546** [comment]
@benjamn: I just stumble on another npm package (filestack-js) that set a esm package as the browser field of their package.json. As webpack support esm and is able to do tree shaking with it, I think more and more packages will be published this way. Also, beside the import/exports, these packages are already transpile to es5. 

So I was wondering if Meteor will have a more scalable solution that don't execute all the babel rules on already transpile files?

Thanks

**Comment by x5engine** [comment]
same happens here

https://github.com/superRaytin/react-monaco-editor/issues/176

**Comment by x5engine** [comment]
@benjamn what can I do to solve this, please?

**Comment by WayneUong** [comment]
@benjamn The same error is happening with `filestack-js`:
```
import * as filestack from 'filestack-js';
Uncaught SyntaxError: Unexpected token export
```

**Comment by arggh** [comment]
The latest and yet-unofficial `2.0` branch of `date-fns` seems to suffer from this same issue.

**Comment by benlavalley** [comment]
@WayneUong  - not sure if you fixed this or not but a resolution was posted in the Filestack repot here:
https://github.com/filestack/filestack-js/issues/142

Implementing this worked for me:
`import filestack from 'filestack-js/build/browser/filestack.min.js'; is a better solution I think.
`

**Comment by diadama** [comment]
got the same error with react-dnd
https://github.com/react-dnd/react-dnd

**Comment by dgan** [comment]
I'm having the same issue with react-dnd.

Uncaught SyntaxError: Unexpected token export

modules.js

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/react-dnd/lib/index.js                                                                                 //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
export * from './common';
export * from './hooks';
export * from './decorators';

**Comment by benjamn** [comment]
Please try updating to the latest Meteor 1.8.2 beta release:
```sh
meteor update --release 1.8.2-beta.16
```
Compiling ECMAScript module syntax found in `node_modules` is one of the headline features of Meteor 1.8.2.

**Comment by dgan** [comment]
Thank you! That did the trick!

**Comment by davidsavoie1** [comment]
I tried this solution in order to be able to use React-DnD, but unfortunately, it incurs some dependencies issues that I don't know how to solve properly... After updating to `release 1.8.2-beta.16`, I got a `@babel/runtime` issue. I updated this package with `meteor npm i @babel/runtime@latest`, but I now get this runtime error:
```
Uncaught ReferenceError: meteorBabelHelpers is not defined
```
Honestly, I don't know where to go from there... I'm not keen on using a beta version for production code in the first place, but I don't know how I could use React DnD otherwise...
