### ISSUE TITLE
[1.7.0.5] Build not producing runable code.

### ISSUE THREAD

**Issue by pnunn** [meteor/meteor#10213]
I am trying to build a meteor app that has been upgraded from 1.3 to 1.7.0.5 to deploy on our hardware.

The app has updated and is running happily from the dev box with "meteor"

I have tried building the app with build and with build --server-only and the bundle is produced seemingly correctly.

I have put that onto our server, unpacked it, installed node and pointed it to our Mongo DB. 

During npm install I get the message

```
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@ node npm-rebuild.js /opt/bundle/programs/server
added 131 packages in 13.857s
```

When I run it with 

` PORT=3080 MONGO_URL=mongodb://10.1.26.2:27017 ROOT_URL=http://appname node main.js`
I get no errors, however, I only get a blank page (favercon and site title are correct) with the following in the dev console

`Error: The core-js npm package could not be found in your node_modules directory. Please run the following command to install it: meteor npm install --save core-js `

As this is bundled and meteor does not exist I obviously can't do that.

I tried npm install --save core-js and npm installed a package, no change.

I can see core-js in the server node_modules directory.

**Comment by klaussner** [comment]
Are you running `npm install` as root?

**Comment by pnunn** [comment]
Yes I am running the install as root. This time it even offered to upgrade npm from 5.6.0 to 6.4.1 which I did, but still the same response from the app.

**Comment by klaussner** [comment]
For security reasons, npm doesn't run with root privileges, even if it is executed by the root user. You either have to run it as an unprivileged user or use the `--unsafe-perm` flag: `npm install --unsafe-perm`.

**Comment by pnunn** [comment]
I just removed the bundle, re-unpacked it, ran npm install from the server/programs directory as my user, started the node main.js as my user and have exactly the same error unfortunately. For some reason I am totally unable to find core-js.

**Comment by pnunn** [comment]
I just tried meteor npm install on the dev server first, no change. Tried running and installing as root, and as a user, no change. I'm running out of ideas here. It must surely be possible to bundle and deploy this app. It worked fine at version 1.3

**Comment by benjamn** [comment]
Did you run `npm install --save core-js` in the app before bundling it, or only inside the bundle?
