### ISSUE TITLE
Minimongo incompatibility with array sorting on MongoDB 3.6+

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#10212]
In MongoDB 3.6 they changed how sorting over the array behaves: https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#array-sort-behavior

Because of this, Minimongo's behavior does not match anymore underlying MongoDB bundled with Meteor. More precisely, the [`minimongo - array sort` test](https://github.com/meteor/meteor/blob/devel/packages/minimongo/minimongo_tests_client.js#L2187) now fails if it is run on the server. Instead of order 0, 1, 2, 3 which Minimongo produces, MongoDB returns documents in order 2, 0, 1, 3.

I would repeat again that Minimongo tests should be run on the server to assure such compatibility in the future.

**Comment by sebakerckhof** [comment]
Since I was looking into it and was initially confused: It's specifically about `A sort no longer takes the query predicate into account`, so the [test with the selector](https://github.com/meteor/meteor/blob/devel/packages/minimongo/minimongo_tests_client.js#L2219) fails.
