### ISSUE TITLE
[boilerplate-generator 1.6.0] Cordova build has duplicated head items in generated index.html

### ISSUE THREAD

**Issue by menelike** [meteor/meteor#10210]
Steps to reproduce:

1. Create minimal meteor app (`meteor create --minimal`)
2. Enable cordova (`meteor add-platform android`)
3. For better illustration add 
```
    <style id="myUniqStyle">
        :root {
            --foo: 0;
        }
    </style>
```
to the `<head>...</head>` section in `client/main.html`

4. Start the app with `meteor run android`
5. Go to `.meteor/local/cordova-build/www/application/index.html`
6. You'll see duplicate entries for `title` and `style`

I think that this is a regression from https://github.com/meteor/meteor/commit/282b450008a7e88412be4b0ec2c9c6a2e6bdc8c0#diff-3e89969160ac63e22788d1b032ebeaef

where this line https://github.com/meteor/meteor/blob/de6717da66c1bcdccfcaa01b5d16de1fdb383c7f/packages/boilerplate-generator/template-web.cordova.js#L71 should have been removed (like in `template-web.browser.js`).

Unfortunately, removing that line will only partially solve the issue, the initial index.html still has the duplicated items, but if a HCP is triggered (run `meteor add autoupdate` before) the refreshed index.html is fixed.

**Comment by menelike** [comment]
@benjamn Thanks for taking care of this, I'd have submitted a PR but I'm still failing to find the reason why the initial `index.html` won't be fixed with the applied change from above.

@rcurrier666 Do you have a clue on this one?

**Comment by rcurrier666** [comment]
@menelike I've been AWOL from the Meteor world due to working on a contract that sucked up 110% of my time. I finished that up yesterday and as soon as I figure out who the woman and child who are living in my house are I'll take a look at this as well as the other problem with my original change. But removing the duplicate \<head\> is a good start.

**Comment by menelike** [comment]
@rcurrier666 Same with me ;)

*it was just a question*, anyway thanks for all the effort you put into this, especially with that lack of time. 👍
