### ISSUE TITLE
Meteor.call returns a null error where it used to return undefined

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#10223]
Upon updating to 1.7.1-beta from 1.6 (skipping 1.7 because of buggy build problems) I noticed that calls to `Meteor.call` which used to return an undefined error, are now returning a null error.

While not exactly a bug - it would be good if this made it into the release notes of whichever release caused this problem (I'm not sure if its 1.7 or 1.7.1-beta as I can't build for 1.7).

```
Meteor.call("whatever", (err, res) => {
  if (err === undefined) {
   // handle result
  }
  else {
   // handle error - this now fails because we come into this branch with a null error
  }
});
```

**Comment by benjamn** [comment]
Can you create a small reproduction of this? When I was debugging #10078 earlier today, I didn't notice any `null` error arguments, only undefined. Perhaps there's a package you're using that's wrapping the method callbacks somehow?

**Comment by znewsham** [comment]
@benjamn I don't think it needs a repo - however, it isn't all method calls - it looks like its specifically callbacks for mongo collections (maybe specifically on the client side) seems this is where the bug may have been introduced:

https://github.com/meteor/meteor/blame/c42170568af7ce798a4b12ffdc7712f3ebb5a59f/packages/mongo/collection.js#L727

**Comment by benjamn** [comment]
This should be fixed if you update your app with `meteor update --release 1.8-rc.17`. Please feel free to open a new issue if you're still having problems!
