### ISSUE TITLE
Unmaintained mdg packages

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10229]
This is basically to catch the attention of someone at mdg that there are some outstanding PR's of MDG packages which nobody seems to be looking at anymore.

E.g. validated method: https://github.com/meteor/validated-method/pull/83

I understand the man-power assigned to Meteor is limited, but maybe you could move them to the non-core directory of this repo or assign some community maintainers so they don't get forgotten?

Then there are some that were released by @stubailo (e.g. https://github.com/stubailo/meteor-rest ) during his time at mdg. Since these are officially recommended packages (e.g. in the guide), maybe you guys could also work out with stubailo to move these packages to the meteor non-core repository or assign maintainers?

ping @benjamn @abernix

**Comment by hwillson** [comment]
Moving these packages into the main Meteor repo is something we'd like to avoid. If anything, there are packages here that we'd like to move out. We'd like to keep the main repo as tight and focused as possible, making it easier for maintainers to manage. I think the solution here is to get more community members involved. It would be awesome to get the community's help with packages like `validated-method`. @sebakerckhof, I've added you as a collaborator. If you know of anyone else that would be a good fit, definitely let me know. I can also talk to Sashko about adding new collaborators to `meteor-rest`, or if someone is interested in forking and maintaining a new version of that repo, we can get it into the Guide. Thanks!

**Comment by abernix** [comment]
We recommend a number of packages in the guide that are not directly maintained by MDG — it doesn't necessarily mean that they should be part of Meteor Core (this repository), just that we recommend their approaches.  As @hwillson mentioned, more maintainers who can assist with maintaining those packages would be great, but if others could even chime in on PR reviews and testing changes, it helps a lot!

All in all, we do see issues and PRs pop up in other repositories, but we have to prioritize carefully, and some PRs do get overlooked/forgotten if they don't get enough traction.  We'll review the PR you opened recently and referenced above within the scope of `validated-method`.

**Comment by sebakerckhof** [comment]
@abernix, @hwillson Thanks for jumping on this so fast! I'm happy to assist with the maintenance of these non-core packages, I often find myself with a little spare time at work which I can use for these things.
