### ISSUE TITLE
Accounts modernization breaks in IE11 (1.8 RC)

### ISSUE THREAD

**Issue by etyp** [meteor/meteor#10231]
## Issue
We tried updating to Meteor 1.8 rc 16 from #9942 and ran into issues with IE11 breaking in several places. One spot specifically was from the accounts oauth package - pretty sure it's related to modernization from @jamesmillerburgess 

## Reproduction
See simple reproduction repo: https://github.com/etyp/accounts-oauth-ie11#meteor-18-accounts-oauth-ie11-issue

**Comment by jamesmillerburgess** [comment]
I'm getting to this, I swear! Just had some unexpected events at work and have been fire-fighting for the past two days. Will try to work on it tomorrow morning.

**Comment by jamesmillerburgess** [comment]
@etyp 

So I used the Windows 8.1 VM you recommended to test on IE11, and I'm not seeing any sort of errors in the console by default.

However, I *did* find a way to reproduce it - if we set Document mode emulation to IE10, then we get a syntax error on the first `const`. But this means that IE11 is being served the modernized bundle but emulating without support for ES6+ features like `const` and arrow functions.

Vanilla IE11:
![screen shot 2018-09-27 at 8 30 44 am](https://user-images.githubusercontent.com/15968012/46123523-12893200-c230-11e8-9e33-86e985e3471b.png)

IE11 Document Mode Emulation IE10:
![screen shot 2018-09-27 at 8 34 49 am](https://user-images.githubusercontent.com/15968012/46123555-39dfff00-c230-11e8-9ca5-8dded16de4c7.png)

Is it possible you were running this with document mode 10 or earlier?

**Comment by etyp** [comment]
I'm not sure, we use browser stack to test this. I'll check it out when I get some time in the next day or two. Thanks for investigating.

**Comment by jamesmillerburgess** [comment]
It is possible to force a certain document mode for IE with a meta tag. Our company does this for some legacy applications that targeted IE9 and aren't actively maintained. Maybe it's worth checking if that is happening for your application.

**Comment by etyp** [comment]
@jamesmillerburgess but doesn't that mean that this will break out of the box Meteor applications which don't have this meta tag enabled?

Also do you know what the meta tag is?

**Comment by jamesmillerburgess** [comment]
I’m suggesting that if you do have those meta tags in your html you should remove them because they will cause errors.

We are using them on some very old non-meteor applications.

**Comment by etyp** [comment]
I'm not sure the [reproduction repo uses these meta tags](https://github.com/etyp/accounts-oauth-ie11#meteor-18-accounts-oauth-ie11-issue) --- it's just a sample meteor application with accounts-oauth added to it.

We've found that whenever we have issues like this, most of our users on IE11 also encounter it. I'm not sure we can control what document mode they use.

Maybe I'm misunderstanding something here?

**Comment by jamesmillerburgess** [comment]
I think 'IE11' was a bit of a red herring here, and your application is actually breaking on IE10. I was missing the `ecmascript` package in `accounts-oauth`, but it still works in IE11, just not IE10 and below.

Thanks for finding this!

The application still breaks in IE9, but for a different reason:

![screen shot 2018-10-01 at 7 51 57 am 3](https://user-images.githubusercontent.com/15968012/46268978-ed0d6880-c54e-11e8-83cc-5cb486d03514.png)
