### ISSUE TITLE
❗️Bug: Fixing LGTM errors 

### ISSUE THREAD

**Issue by lisaychuang** [meteor/meteor#10240]
Hi team @hwillson @laosb @abernix @lorensr

I'll like to work on some of the errors identified by LGTM, as listed below.

Please let me know if I can get started on this issue, and if you have any advice for the error on class imports `CordovaProject` and `ProjectContext`?

Thank you!
Lisa

[match_test.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/check/match_test.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x97acf15163ba56b9:1)
- missing semicolons
- Incorrect use of ES6 `const` vs `let` in Regression test 

[oauth1_binding.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/oauth1/oauth1_binding.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xc867c367495d33f7:1)
- Incorrect use of ES6 `const` vs `let` in `_getSignature()`

[appcache-server.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/appcache/appcache-server.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x1ea8ae6314336d1d:1)
- missing variable declaration on line 14 `value = options[option];`

[login_buttons_single.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/accounts-ui-unstyled/login_buttons_single.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x5fc53fe83663053a:1)
- missing variable declaration on line 93 `str = input == null ? '' : String(input);`

[package-source.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/tools/isobuild/package-source.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x82e20b88ca1d1882:1)
- missing variable declaration on line 1314 `dir = assetDirs.shift();`

[minifier.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/minifier-css/minifier.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x1daef0d9ae1f9cb4:1)
- missing variable declaration on line 55 `transformResult = f.wait();`

[commands.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/tools/cli/commands.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xa4840be52558660e:1)
- there appears to be an issue with the `{CordovaProject} import (line 1075), LGTM error shows this base class type is `undefined`. I'm not too sure on how this should be fixed.
- missing semicolons
- missing variable declaration on line 1086 `for (platform of cordovaPlatforms)`

[commands-cordova.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/tools/cli/commands-cordova.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x1b91683015a5c066:1)
- there appears to be an issue with the `{ProjectContext} import (line 14), LGTM error shows this base class type is `undefined`. I'm not too sure on how this should be fixed.
- missing semicolons
- missing variable declaration on:
  - line 37 `for (platform of platformsToAdd)`
  - line 82 `for (platform of platformsToRemove)`

[d3.v3.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/packages/deprecated/d3/d3.v3.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xbaeccc08874d1c5a:1)
- missing variable declaration on line 55 `transformResult = f.wait();`

[bump-all-version-numbers.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/scripts/admin/bump-all-version-numbers.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x153400165c55168f:1)
- missing variable declaration on line 13 `match = content.match(/\d+\.\d+\.\d+-winr.\d+/);`

[run-targets.js errors](https://lgtm.com/projects/g/meteor/meteor/snapshot/fd64c6d8eb631f982d43e6ede8732d0baf3d9810/files/tools/cordova/run-targets.js?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x7cd7721b70bceff9:1)
- missing variable declaration on:
  - line 176 `[, priority, tag, pid, message] = match;`
  - line 184 `[, logLevel, filename, lineNumber, message] = match;`

**Comment by StorytellerCZ** [comment]
This is a FOSS project, you don't need permission to create a pull request with fixes to bugs you see. Go ahead, the merit of the changes will be evaluated in detail with automated tests and review by the maintainers once you submit a PR. Discussion is needed only about new features or big fixes that require some formalization on how to approach the given problem (which this doesn't seem to be the case).

**Comment by lisaychuang** [comment]
Thanks @StorytellerCZ, I've opened a PR [#10241](https://github.com/meteor/meteor/pull/10241)

**Comment by aliogaili** [comment]
Thanks for the contribution @lisaychuang! I think the PR for this issue has been merged, can we close this?

**Comment by benjamn** [comment]
Feel free to reopen this issue if there are any changes beyond #10241 that need to be made! Thanks again for the contribution, @lisaychuang!
