### ISSUE TITLE
Integrate meteor project in existing php project under subfolder?

### ISSUE THREAD

**Issue by eagle49** [meteor/meteor#10243]
Is it possible to integrate meteor project in an existing php project under subfolder?
These two project will user same mysql server of origin php project and meteor project should be inside the php project under subfolder like http://app.com/meteor_project.
Is it possible?

For more detail in php project there is page that list the persons data and if admin click one user it will redirect meteor page like http://app.com/meteor_project/view/[user_id]
In meteor project it read some user`s data in same mysql database with [user_id]
Anyone know if it is possible?

**Comment by aliogaili** [comment]
Why is this even an  issue? it doesn't follow the issue template and it's not a Meteor issue. Why not [using meteor forums](https://forums.meteor.com/)?

**Comment by benjamn** [comment]
Yeah, the forums would be a better place for this kind of question. Meteor is a JavaScript framework, so integrating with other languages is not really a goal, though you may be able to get something to work, with some cleverness.
