### ISSUE TITLE
Meteor publication for Mongo View is disappearing from minimongo

### ISSUE THREAD

**Issue by jasonfontaine31** [meteor/meteor#10258]
so I created a view in my database using the command 
* "collection" in this instance is the collection I'm reading  from
* Meteor version = Meteor 1.6
* Mongo Instance Version  = Mongo 3.4

```
db.createView('testViewUSA',"collection", [{
 $group: { 
     _id:null,
      count: { $sum: 1 } }
}, 
{
     $project:{
           _id: "test", count:1 
    }
 }])
```
I have meteor read it as a collection as so testViewUSA;

```
import {Mongo} from "meteor/mongo"; 

export const testViewUSA = new Mongo.Collection('testViewUSA');
```
I also have a publication 
```
Meteor.publish({
 'testViewUSA.all': function(_id) { 
      // filler
      return testViewUSA.find({ _id }); 
},
});
```

the subscription being used on the client is here
```
Template.test.onCreated(function() {
     // filler
     this.subscribe('testViewUSA.all', "test")
    // filer 
});
```
and a helper on the client
```
getCount() {
     const countData = testViewUSA.findOne({});
     return countData; 
},
```
for some reason the data loads and then after a couple of seconds the web socket returns this message
```
"{"msg":"removed","collection":"testViewUSA","id":"test"}"
```
rather than updating when the data changes

can you help me

**Comment by benjamn** [comment]
What version of Meteor are you using?

**Comment by jasonfontaine31** [comment]
@benjamn Metoer 1.6

**Comment by FlyingTigra** [comment]
Actually, same thing happen in 1.8.0.1
I have pretty much similar setup: I query View with aggregation request and push docs to UI.
If I query documents just by their ids, I see 'added' fired and then empty 'changed' fired on those docs.
If I add more filters, like {_id: {"$in": [...], someField:"xxx"}} then I see 'added' fired and then, after 3-5 seconds, I see 'removed' fired on those docs.

Very bizarre behavior. Any suggestions? We really hope to be able to use Views in subscription.
Thank you!

**Comment by jasonfontaine31** [comment]
@FlyingTigra  We were able to get views to work
```
Meteor.publish('single.document', function(_id){
  check(_id, String);
  var data = Collection.find({_id: _id});
  if (data) {
    return data;
  }
  return this.ready();
});
```

my question for you is how did you get views to work with large documents

**Comment by DeanKamali** [comment]
I'm having the same issue : /
