### ISSUE TITLE
treat Edge as non-modern browser?

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10251]
babel and edge do not play nicely in certain situtation, see https://github.com/babel/babel/issues/8825 which breaks uniforms, see https://github.com/vazco/uniforms/issues/473

is it possible to treat ie as non-modern browser, so that it gets the full compiled code?

**Comment by benjamn** [comment]
You took the words out of my mouth! I agree we should continue to track this, but I’m confident this particular issue is something Babel can handle properly.

**Comment by macrozone** [comment]
i am also confident, as the fix has already been suggested (something like `(super(...), _this = this)`, but the issue seems not be active, so I am a bit worried :-/ 

at least it has been fixed in edge (but not released yet), so maybe i can set the minimum edge version to the next release one.

By the way, the problem in my case is because a native class extends the compiled `React.Component`-"class". Is it possible to use the non-compiled react code in meteor? If you feel like, you might give a comment on that question (question 3) here: https://forums.meteor.com/t/meteor-1-7-legacy-modern-compiling-and-node-modules-npm/44769

**Comment by Dartv** [comment]
Today I encountered a very strange bug with edge.
It failed to render app without any errors thrown. Turned out it was because of this syntax which edge doesn't support: `([{ ...obj }]) => ...`
I think it's clear that meteor should treat edge as legacy at this point
