### ISSUE TITLE
Meteor still warning about babel-runtime version issues

### ISSUE THREAD

**Issue by napei** [meteor/meteor#10253]
After updating to 1.8.1-beta.0, I still get the error that was removed in this commit, da784cbcfa76d1948496dda48ddd8667d214ba25, about the babel-runtime having a breaking change. currently I have @babel/runtime@7.1.2 in my node_module directory, but from that commit, that message shouldn't even show up anymore. 

Is there something I did wrong? All I did was run `meteor update --release 1.8.1-beta.0` and then updated all the packages through yarn.

This happens in 1.8.0 as well, using both npm and yarn. I can confirm that the actual version in my node_modules directory is 7.1.2. Is there a cache I can just clear?

Running on Ubuntu 18.04.

Thanks :)

**Comment by KoenLav** [comment]
Same here!

**Comment by benjamn** [comment]
What compiler plugin packages are you using? Anything that isn't a core Meteor package?

**Comment by KoenLav** [comment]
@benjamn 

shell-server@0.4.0            # Meteor command line code
meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.6.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
session@1.1.8                 # Client-side reactive dictionary for your app
jquery@1.11.10                # Helpful client-side library
tracker@1.2.0                 # Meteor's client-side reactive programming library
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.12.0              # Enable ECMAScript2015+ syntax in app code
dynamic-import@0.5.0          # Dynamically import modules

# Default
http@1.4.1
email@1.2.3
check@1.3.1
ejson@1.1.0
random@1.1.0
npm-bcrypt@0.9.3
underscore@1.0.10
reactive-dict@1.2.1
launch-screen@1.1.1

# Accounts & roles
accounts-base@1.4.3
accounts-password@1.5.1
alanning:roles

# Styles
fourseven:scss@4.5.4
less@2.8.0

# Minifiers
standard-minifier-js@2.4.0    # JS minifier run for production mode
standard-minifier-css@1.5.0   # CSS minifier run for production mode

# Collections & data
aldeed:collection2-core       # Performs schema validations based on simpl-schema
matb33:collection-hooks       # Perform actions before or after insert/update/delete
dburles:collection-helpers    # Define helpers on collections (format data, for instance)
tmeasday:publish-counts       # Publish the count of a Collection (do we really need a package for this?)
percolate:migrations

# Routing
iron:router

# Security
ongoworks:security
jparker:crypto-aes

# View & rendering
pcel:loading
manuel:viewmodel
react-template-helper
fortawesome:fontawesome

# User interface
aldeed:tabular
aldeed:autoform
aldeed:autoform-select2
chriswessels:glyphicons-halflings
mozfet:autoform-materialize
natestrauser:select2
utilities:avatar

# Translations
universe:i18n
universe:i18n-blaze

# Debugging & Profiling
lmachens:kadira

# TODO: remove/replace/fork
#ground:db@2.0.0-rc.7

# Files
ostrio:files

# Other
momentjs:moment
react-meteor-data
meteortesting:mocha
hwillson:stub-collections

**Comment by napei** [comment]
@benjamn 
Meteor Packages
`
meteor-base@1.4.0 
mobile-experience@1.0.5  
mongo@1.6.0  
blaze-html-templates  
reactive-var@1.0.11  
tracker@1.2.0 
standard-minifier-js@2.4.0  
es5-shim@4.8.0               
ecmascript@0.12.0             
shell-server@0.4.0          
kadira:flow-router     
kadira:blaze-layout 
meteortesting:mocha              
johanbrook:publication-collector 
seba:minifiers-autoprefixer
accounts-password@1.5.1
session@1.1.8
alanning:roles
aldeed:tabular
aldeed:collection2
aldeed:autoform
fourseven:scss
momentjs:moment
fortawesome:fontawesome
react-meteor-data
cultofcoders:meteor-react-routing
cultofcoders:persistent-session
`

Npm Packages
`
"dependencies": {
    "@babel/runtime": "^7.1.2",
    "bcrypt": "^3.0.0",
    "bootstrap": "^4.1.3",
    "history": "^4.7.2",
    "jquery": "^3.3.1",
    "meteor-node-stubs": "^0.4.1",
    "popper.js": "^1.14.4",
    "pretty-error": "^2.1.1",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-mounter": "^1.2.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "reactstrap": "^6.4.0",
    "simpl-schema": "^1.5.3",
    "yarn": "^1.10.1"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.6",
    "chai": "^4.1.2",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-import-resolver-meteor": "^0.4.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-meteor": "^5.1.0",
    "eslint-plugin-react": "^7.11.1",
    "prettier-eslint": "^8.8.2"
  }
`

**Comment by jamalcoder** [comment]
same here after updating from 1.7.0.5 to 1.8.0

**Comment by napei** [comment]
@benjamn 

After running a grep to find occurrences of the message using `grep -Ril "contains a breaking change which was introduced by" /` I found a lot of references to that message in the `seba_minifiers-autoprefixer` package under the `babel-runtime.js` under each version.

After removing that package and letting meteor re-download it, I get the following snippet inside the `1.1.1/packages/babel-runtime.js` file for that package. This appears for both meteor 1.8 and 1.8.1 beta.

```javascript
if (parseInt(babelRuntimeVersion, 10) < 6) {
  throw new Error([
    "",
    "The version of @babel/runtime installed in your node_modules directory ",
    "(" + babelRuntimeVersion + ") is out of date. Please upgrade it by running ",
    "",
    "  meteor npm install --save @babel/runtime",
    "",
    "in your application directory.",
    ""
  ].join("\n"));

} else if (parseInt(babelRuntimeVersion.split(".").shift()) >= 7) {
  // If Babel 7, only allow -beta.55 and earlier.  The final release, all RCs
  // and -beta.56 all suffere from the removal of the "builtins" helpers.
  var acceptableBabelRuntimeVersion =
    /^7\.0\.0-beta/.test(babelRuntimeVersion) &&
    parseInt(babelRuntimeVersion.split(".").pop(), 10) <= 55;

  if (! acceptableBabelRuntimeVersion) {
    console.warn([
      "The version of @babel/runtime installed in your node_modules directory ",
      "(" + babelRuntimeVersion + ") contains a breaking change which was introduced by ",
      "https://github.com/babel/babel/pull/8266. Please either downgrade by ",
      "running the following command:",
      "",
      "  meteor npm install --save-exact @babel/runtime@7.0.0-beta.55",
      "",
      "or update to the latest beta version of Meteor 1.7.1, as explained in ",
      "this pull request: https://github.com/meteor/meteor/pull/9942.",
      ""
    ].join("\n"));
  }
}
```

**Comment by banjerluke** [comment]
Glad you posted this, @napei. I was able to verify that swapping out `seba:minifiers-autoprefixer` for `standard-minifier-css` fixed the issue, and the message came back when I put `seba:minifiers-autoprefixer` back in.

I noticed that package has a dependency on `minifier-css` that is fixed to version 1.3.1 (current version is 1.5.1). Removing the version specifier fixes the issue. 

I'll submit a pull request to the `seba:minifiers-autoprefixer` package...

**Comment by sebakerckhof** [comment]
I'll publish a new version when I get to my working environment.

**Comment by sebakerckhof** [comment]
@banjerluke `1.1.2` has been released depending on `minifier-css` 1.4.0 (`1.4.0` being the last published version and since compiler plugins are compiled ahead of time, you need to depend on a specific version).

**Comment by banjerluke** [comment]
@sebakerckhof Just learned something new about compiler plugins! Anyway, works great now. Thank you!

**Comment by gotjoshua** [comment]
I was also getting this warning, and universe-i18n was the problem, but it is recently fixed, so:
`meteor update --all-packages` was all that was needed.
