### ISSUE TITLE
Error building 1.8.0 on CircleCI: Cannot read property 'getContentsAsString' of undefined

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#10259]
While building our app on CircleCI we receive the following error:

Errors prevented bundling:
While minifying app stylesheet:
packages/minifyStdCSS_plugin.js:130:34: Cannot read property
'getContentsAsString' of undefined
at packages/minifyStdCSS_plugin.js:130:34
at Array.map (<anonymous>)
at packages/minifyStdCSS_plugin.js:129:32
at CssToolsMinifier.processFilesForBundle
(packages/minifyStdCSS_plugin.js:33:16)

Any pointers?

**Comment by KoenLav** [comment]
This issue appears similar/to be the same:

https://github.com/meteor/meteor/issues/10112

**Comment by benjamn** [comment]
Ok, thanks for doing the research. Let's move this discussion back to #10112?
