### ISSUE TITLE
[1.7.0.5] WebAppInternals.setBundledJsCssPrefix does not handle web.browser.legacy properly

### ISSUE THREAD

**Issue by weisheng-p** [meteor/meteor#10250]
Sample app here: https://github.com/weisheng-p/meteor-broken-jscssprefix
Sample build here: https://github.com/weisheng-p/meteor-broken-jscssprefix/releases/tag/v1.0

Currently the meteor build generate both web.browser and web.browser.legacy

Since WebAppInternals.setBundledJsCssPrefix only take in one path, there is no way to handle url and pathing based on the build. Is there a workaround or another setting that will handle this?

**Comment by evolross** [comment]
Why do you need two _different_ URLs?  Wouldn't both builds use the same URL to JS, CSS, images?

**Comment by weisheng-p** [comment]
Actually it doesn't use the same url.

If meteor determine that your browser is a legacy browser. it choose to load the js file in the web.browser.legacy, in the example it will load 9d9f8bc6d005c3c5b34b8632a90713428000ffdf.js

and if you have a new browser it will load 16bb8b1bea7834b8de221c8d58413b2bf1417d34.js instead.

all from the root url.
