### ISSUE TITLE
OAuth package : WebApp.connectHandlers.use is called twice

### ISSUE THREAD

**Issue by tjaisson** [meteor/meteor#10265]
Somehow #9740 was reverted.

**Comment by StorytellerCZ** [comment]
Why do you think so? Looking at the code I don't see that.

**Comment by tjaisson** [comment]
[line 141](https://github.com/meteor/meteor/blob/ccb479f4e737a896c8ac4c4dbfdb0b9f7890f453/packages/oauth/oauth_server.js#L141)

[line 207](https://github.com/meteor/meteor/blob/ccb479f4e737a896c8ac4c4dbfdb0b9f7890f453/packages/oauth/oauth_server.js#L207)
