### ISSUE TITLE
[1.8] 4 times longer rebuild times

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10262]
My rebuild times with Meteor 1.8 have gotten up to 4 times slower. 

I tried to look into the cpu profile differences between Meteor 1.7 and Meteor 1.8 rebuilds and noticed almost all time was suddenly spend by the babel compiler inside `urigo:static-templates`, but not by work being done by `urigo:static-templates`.

I did update the dependencies of the package, but that's basically all that has changed:
https://github.com/Urigo/meteor-static-html-compiler/commit/6f59899c8c692ced6fbc65f58c942f1cb45917fd#diff-49fb32b6d8276ecd1268e47c0339d55c

The package isn't doing extra work and the actual babel compilation is very minimal:
https://github.com/Urigo/meteor-static-html-compiler/blob/master/src/template.ts#L54

What I don't understand is that when I'm using the older version of `urigo:static-templates` and I look at the processes of my Meteor 1.8 app, I see Meteor tool 1.7.0.5 doing work:
![screenshot from 2018-10-10 11-33-32](https://user-images.githubusercontent.com/88471/46727231-63f9de00-cc80-11e8-8a70-1807ab8c8d9b.png)

While if I use the new version of `urigo:static-templates`, it's Meteor tool 1.8.0.1 doing the work:
![screenshot from 2018-10-10 11-44-47](https://user-images.githubusercontent.com/88471/46727977-0f576280-cc82-11e8-9f38-ccc07317280d.png)

So some things I don't understand here:
- Why do the dependencies of a compile plugin change which meteor tool is being used
- Why is it so much slower with only updating meteor compiler dependencies
- Why am I seeing meteor-tool 1.7.0.5 doing any work in my meteor 1.8 app
- Why is the delayed build thing working if it's meteor 1.7.0.5
- Why are the cpu profiles so different, e.g. why is there so much work being done that's totally not present when using the old dependencies. It kinda looks like Meteor pi

Cpu profiles:
- Meteor 1.7 with old dependencies -> fast
- Meteor 1.8 with old dependencies -> fast
- Meteor 1.8 with new dependencies -> slow, and doing a lot of work which seems totally not present in the other profiles. E.g. between seconds 4 and 18. This is work that's not visible in the other profiles and doesn't seem to actually come from the template compiler.

[profiles.zip](https://github.com/meteor/meteor/files/2464077/profiles.zip)

**Comment by benjamn** [comment]
How should I try to reproduce this? I can clone https://github.com/Urigo/meteor-static-html-compiler into `packages/` and checkout the commit you mentioned above, but what kind of / how many files should the app have, to exercise this behavior?

**Comment by sebakerckhof** [comment]
Yeah, unfortunately I can't share my application. So I'm trying to limit the scope and make a reproduction.

**Comment by sebakerckhof** [comment]
@benjamn Is there a way to force a specific (down to the patch level) package version to be used?
The version of `urigo:static-templates` where the problem does not appear is 1.0.0 and the one where it does is 1.1.1, but Meteor will now always pick 1.1.1. 

So I tried to publish a new version with the Meteor version I originally published `urigo:static-templates@1.0.0` with (Meteor 1.6.1), but instead of `babel-compiler@7.0.0` which Meteor 1.6.1 came with at the time, it's now automatically using `babel-compiler@7.0.9`.

I'm currently testing by messing around with `~/.meteor/packages/` directories, but that makes it impossible to make a reproduction...

**Comment by benjamn** [comment]
Yes, just put `urigo:static-templates@=1.0.0` in your app's `.meteor/packages` file (not to be confused with the global `~/.meteor/packages` directory).

**Comment by sebakerckhof** [comment]
@benjamn I found the root cause. Well, causes.
3 things are happening to make this so obvious in my case, but it probably affects other people in less obvious ways:

1. The template compiler compiles every .html file in node_modules, and since nobody cares to remove their demo html files in their npm package, these are a lot of files in my case. This should actually be solveable now by making use of `compileOneFileLater` in `urigo:caching-templates` 
2. Somehow the cache of the caching compiler in `urigo:caching-templates` doesn't work and on every rebuild it will recompile all files. Still investigating if this is a bug in Meteor or in `urigo:caching-templates` 
3. **And this is the big one.** The cache in meteor-babel doesn't work, since it will generate different hashes for the same files each time. This also means it keeps growing in memory (siginificantly in my case because of point 1.)
So this line always gives separate results on each rebuild: https://github.com/meteor/babel/blob/master/cache.js#L61

I figured out that the difference is in `options.plugins`. This array keeps growing (exponentially I think) on each rebuild containing tens of thousands of duplicates more each rebuild. So the hash is always fed with different input.

![image](https://user-images.githubusercontent.com/88471/46797844-8d823a80-cd50-11e8-921d-07619220ad84.png)

**Comment by benjamn** [comment]
Ah, that explains why `util.deepHash` accounts for so much of the CPU profile.

**Comment by sebakerckhof** [comment]
Ok, 1 can be solved with `compileOneFileLater` and 2 was a bug in `urigo:caching-html-compiler`.

If I fix 2, the problem with 3 goes away since I'm never compiling twice the same file.
In fact, I'd like for meteor-babel to have an option to not warn about not using a cache, since that's taking up RAM we don't need. it's just a duplicate cache of the caching-compiler plugin.

So the 'bug' in meteor-babel / babel/core is because of this call:
https://github.com/meteor/babel/blob/master/index.js#L103
which adds plugins to the options.parserOpts.plugins array you give it.

`babel-compiler` doesn't have this problem since it always gets a new set of options ( https://github.com/meteor/meteor/blob/devel/packages/babel-compiler/babel-compiler.js#L107 )

But we re-used the options object: https://github.com/Urigo/meteor-static-html-compiler/blob/master/src/template.ts#L19

**Comment by benjamn** [comment]
Can you try running
```bash
meteor update babel-compiler ecmascript
```
to get the latest versions of those packages (7.2.1 and 0.12.1)?

**Comment by sebakerckhof** [comment]
@benjamn confirmed with those versions.
Thanks.
