### ISSUE TITLE
[1.8] Meteor.loginTokenExpires being set to 12/31/1969 - logging out after 2 sessions

### ISSUE THREAD

**Issue by michaelcbrook** [meteor/meteor#10264]
I've just updated to Meteor 1.8 from 1.7.0.3, and this issue only appeared after the update.

Upon logging into my app with password login, everything is initially fine. If I reload the page, everything still appears fine, but I notice `Meteor.loginTokenExpires` in Local Storage gets set to `Wed Dec 31 1969 18:00:00 GMT-0600 (Central Standard Time)`. As a result, the next time I reload the page, I am logged out. So I am only able to stay logged in for a maximum of 2 sessions, before appearing to have been logged out for no reason.

![screenshot from 2018-10-10 14 53 21](https://user-images.githubusercontent.com/4737526/46763076-7aaf2d80-cc9e-11e8-9a06-260e089fdf79.png)

I have checked on the server, and all resume login tokens are still there. I also do not touch Meteor.loginTokenExpires anywhere in my code. And it happens regardless if I use password login or login with a service. I am running this on Ubuntu 14.04 and using the Chrome browser.

Thanks,

Michael

**Comment by sebakerckhof** [comment]
I can't seem to reproduce this. Can you look at the websocket frames if that's the time that the expiration the server returns? That way we can narrow the scope down to frontend or backend.

**Comment by michaelcbrook** [comment]
Can you tell me how I can view the websocket frames? I have gone into dev tools, WS, websocket, but all I see is `(Opcode -1)`.

**Comment by michaelcbrook** [comment]
I think I've got a few issues at work that's making this difficult to debug. The Chrome extension doesn't seem to work for me, and others comment with the same issues. I don't know that it's maintained anymore. I think the reason I can't see the frames in the first place is because I've had `WebSocket connection to 'ws://localhost:3000/sockjs/079/_2whrbzp/websocket' failed: Connection closed before receiving a handshake response` errors now for several months, since using Apollo. And while it hasn't affected reactivity, I can't find a way to fix it and I believe it's stopping me from seeing the frames.

**Comment by michaelcbrook** [comment]
Alright, I finally got a new development on this. Here is the relevant frame coming down from websockets.

```json
{
  "msg": "result",
  "id": "1",
  "result": {
    "id": "8QeosLb6RegkJLqD5",
    "token": "H5YcjAHzecq6LJO2zbHELpquZNHvglbxAKCY2Js3RIV",
    "tokenExpires": {
      "$date": null
    },
    "type": "resume"
  }
}
```

`$date` is showing `null` I notice, only on the second reload. When I reload after this comes down, I'm logged out.

![screenshot from 2018-10-11 16 38 11](https://user-images.githubusercontent.com/4737526/46835655-7b19f800-cd74-11e8-80b2-19950b6c7f85.png)

**Comment by sebakerckhof** [comment]
Ok, so we now know the problem is at the server-side. That already narrows the scope quite a bit.
I think the next step you could try is locally cloning the  `accounts-base` package (by copying it in the packages directory of your application) and then step through it with a debugger. Here's a good starting point: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L268

**Comment by michaelcbrook** [comment]
Here is my `.meteor/versions` file while I work on the rest.

```
accounts-base@1.4.3
accounts-oauth@1.1.16
accounts-password@1.5.1
allow-deny@1.1.0
amplify@1.0.0
apollo@1.0.0
arillo:flow-router-helpers@0.5.2
autoupdate@1.5.0
babel-compiler@7.2.0
babel-runtime@1.3.0
base64@1.0.11
binary-heap@1.0.11
blaze@2.3.3
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.6.0
bojicas:inflections@0.0.9
caching-compiler@1.2.0
caching-html-compiler@1.1.3
callback-hook@1.1.0
check@1.3.1
coffeescript@1.0.17
cultofcoders:persistent-session@0.4.5
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.2.0
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.5.0
ecmascript@0.12.0
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.8.0
ecmascript-runtime-server@0.7.1
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0
fetch@0.1.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
id-map@1.1.0
inter-process-messaging@0.1.0
jamiesoncj:slingshot@0.7.2
johnantoni:meteor-transit@0.0.1
jquery@1.11.11
juliancwirko:postcss@2.0.3
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
meteor@1.9.2
meteor-base@1.4.0
meteorhacks:picker@1.0.3
meteorhacks:ssr@2.2.0
miktam:api-password@1.0.1
minifier-css@1.4.0
minifier-js@2.4.0
minimongo@1.4.5
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modern-browsers@0.1.2
modules@0.13.0
modules-runtime@0.10.2
momentjs:moment@2.22.2
mongo@1.6.0
mongo-decimal@0.1.0
mongo-dev-server@1.1.0
mongo-id@1.0.7
nicolaslopezj:excel-export@1.0.0
npm-bcrypt@0.9.3
npm-mongo@3.1.1
oauth@1.2.3
observe-sequence@1.0.16
ordered-dict@1.1.0
peerlibrary:aws-sdk@2.200.0_1
peerlibrary:blocking@0.5.2
promise@0.11.1
random@1.1.0
rate-limit@1.0.9
reactive-dict@1.2.1
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
reywood:publish-composite@1.7.0
routepolicy@1.1.0
sarasate:semantic-ui-datetimepicker@0.0.2
service-configuration@1.0.11
session@1.1.8
sha@1.0.9
shell-server@0.4.0
simple:json-routes@2.1.0
simple:rest-bearer-token-parser@1.0.1
simple:rest-json-error-handler@1.0.1
socket-stream-client@0.2.2
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.12
standard-minifier-js@2.4.0
swydo:blaze-apollo@0.5.0
swydo:graphql@0.4.0
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
ui@1.0.13
underscore@1.0.10
url@1.2.0
verso:intercom@1.5.0
webapp@1.7.0
webapp-hashing@1.0.9
xcv58:auth0-lock@8.0.0
zimme:active-route@2.3.2
```

**Comment by michaelcbrook** [comment]
@sebakerckhof I may need to be pointed in the right direction for this. I've cloned the meteor repository in order to get the accounts-base package from source. I've copied it into a top-level directory `packages` and named it `accounts-base2` and called `meteor add accounts-base2` and even tried `meteor remove accounts-base` beforehand to try to get it not to conflict. But I get `Error: There is already a collection named "users"` because I can't eliminate the dependency on `accounts-base`. How do I replace it with the version from source?

**Comment by michaelcbrook** [comment]
After a few hours debugging, I finally found the issue... and it's a very interesting one.

https://github.com/meteor/meteor/blob/308b4f1306521c986d0df9feac8334dc7dcd5936/packages/accounts-base/accounts_server.js#L1350-L1352

`user.services.resume.loginTokens` is an array and calling `find` on it should yield either `undefined` or the found object representing the token, if it is found, according to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find). It is finding it. However, it's returning `-1`. It turns out it is returning `-1` regardless of whether it is found or not.

My first instinct is this may be an issue with Node, so I ran some sample code in both the browser and the server. And they both come out with different results.

Test Code:
```javascript
const test = [{ bla: "test" }].find((val) => val.bla=="test");
console.log(test);
console.log(typeof test);
console.log(!!test);
```

Browser result:
```javascript
{bla: "test"}
object
true
```

Node result:
```javascript
-1
number
true
```

I checked my Node and NPM versions:
```bash
meteor node -v
v8.11.4
meteor npm -v
6.4.1
```

I originally had Node v6.6.0, but upgrading to v8.11.4, the second to the latest [LTS version](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.12.0), still did not fix the problem. And no one that I've found has ever reported this issue.

Am I right in assuming this is a problem with Node? And should I report it?

**Comment by michaelcbrook** [comment]
**Update:** I've actually narrowed this down to being caused by a package. `nicolaslopezj:excel-export` in particular. Have not found the fix or why exactly it's happening yet, but it only happens with this package added. My guess is something in it is replacing the standard `array.find` function. My apologies for taking you down this rabbit hole with me.

**Comment by brunoneumann** [comment]
Thank you so much @michaelcbrook !! This problem was happening to me too and you helped me a lot with your conclusion.

**Comment by sebakerckhof** [comment]
> **Update:** I've actually narrowed this down to being caused by a package. `nicolaslopezj:excel-export` in particular. Have not found the fix or why exactly it's happening yet, but it only happens with this package added. My guess is something in it is replacing the standard `array.find` function. My apologies for taking you down this rabbit hole with me.

That package is basically a wrapper around the (dead) `excel:export` npm package which seems to rely on an old version of `collections` ( https://www.npmjs.com/package/collections ) which is most likely the culprit.

**Comment by roylecj** [comment]
Thanks a lot - this is exactly the issue that we had, and exactly the same package causing the issue. This has taken us ages to find - appreciate your work.
