### ISSUE TITLE
[1.8] --production is treated as development for env variables

### ISSUE THREAD

**Issue by Rhywden** [meteor/meteor#10271]
So, I wanted to test whether environment variables get picked up under Windows. It seems they do just not in development, at least according to the warning message.

But that's what the flag `--production` is supposed to solve, right?

![image](https://user-images.githubusercontent.com/84586/46808116-d5fb2180-cd6b-11e8-98d3-2712d403c934.png)

It's probably an edge case but still...

**Comment by rj-david** [comment]
As indicated here:
https://guide.meteor.com/deployment.html#never-use-production-flag

> -`-production` flag is purely meant to simulate production minification, but does almost nothing else
