### ISSUE TITLE
react SSR with fibers and concurrency issues

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10279]
I have a strange concurrency problem with server side rendering with react and I think its related to fibers, so i will post it here as well for further discussion: https://github.com/facebook/react/issues/13854

To summarize: React.createContext might "leak" from one execution (fiber) to another

**Comment by minhna** [comment]
@macrozone I still have SSR problem with Meteor 1.8 and React 16.9. It can't handle multiple render requests at the same time.
