### ISSUE TITLE
[ISSUE] Legacy browsers - Unexpected token '>' - Problem with arrow function

### ISSUE THREAD

**Issue by phillx** [meteor/meteor#10274]
Hello, i'm facing issue which is limiting visitors with legacy browsers.
The output in sentry log / even in web-console / is 

> Unexpected token '>'

- The issue has been with meteor 1.7 also 1.8 - nothing changed.

- The issue is reported from Safari 9.1 (Most of visitors use safari on macOs or iPhone)
- Edit: Also IE11 ..

The expected behavior is that on legacy browser it will works like has to.

Link to testing environment : [here](https://isotopeticketing.herokuapp.com/event/ThSM2uQavt7DzQfJ3)

**Sentry report :**

![screen shot 2018-10-12 at 15 53 58](https://user-images.githubusercontent.com/1339027/46873531-1bd0ec00-ce37-11e8-8ce6-c0d6550d25f5.png)

**package.json**

```
{
  "name": "xyzcom",
  "private": true,
  "scripts": {
    "start": "meteor --port 4000 --settings settings.dev.json",
    "start:fast": "METEOR_OFFLINE_CATALOG=1 meteor --port 4000 --settings settings.dev.json",
    "start:debug": "meteor --settings settings.dev.json --inspect",
    "deploy": "DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy  --settings ./settings.prod.json",
    "lint": "eslint .",
    "pretest": "npm run lint --silent"
  },
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "babel-runtime": "^6.20.0",
    "bcrypt": "^1.0.3",
    "bufferutil": "^4.0.0",
    "classnames": "^2.2.5",
    "const": "^1.0.0",
    "dateformat": "^3.0.3",
    "dropbox-v2-api": "^2.1.19",
    "fs-extra": "^7.0.0",
    "lodash": "^4.17.10",
    "meteor-node-stubs": "~0.2.4",
    "moment": "^2.22.2",
    "node-qrcode": "0.0.4",
    "postmark": "^1.6.1",
    "qr-image": "^3.2.0",
    "qrcode": "^1.3.0",
    "qrcode.react": "^0.8.0",
    "query-string": "^6.1.0",
    "react": "^16.5.2",
    "react-copy-to-clipboard": "^5.0.1",
    "react-csv": "^1.0.14",
    "react-datepicker": "^1.6.0",
    "react-datetime": "^2.15.0",
    "react-dom": "^16.0.0",
    "react-moment": "^0.7.9",
    "react-qr-reader": "https://github.com/athyuttamre/react-qr-reader",
    "react-router-dom": "^4.2.2",
    "react-router-prop-types": "^1.0.4",
    "react-show-more-text": "^1.0.3",
    "react-spinner": "^0.2.7",
    "react-stripe-elements": "^1.1.0",
    "react-toastify": "^4.3.1",
    "reactstrap": "^6.5.0",
    "simpl-schema": "^0.3.2",
    "stripe": "^5.1.1",
    "svg-to-img": "^2.0.7",
    "tachyons": "^4.8.1",
    "tar-fs": "^1.16.3",
    "utf-8-validate": "^5.0.1",
    "zip-folder": "^1.0.0"
  },
  "devDependencies": {
    "@meteorjs/eslint-config-meteor": "^1.0.5",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-meteor": "^0.4.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-meteor": "^5.0.0",
    "eslint-plugin-react": "^7.9.1"
  }
}
```

**.meteor/packages**
```
cat .meteor/packages 
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.6.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.5.0   # CSS minifier run for production mode
standard-minifier-js@2.4.0    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.12.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.4.0            # Server-side component of the `meteor shell` command

react-meteor-data
dburles:collection-helpers
alanning:roles
aldeed:collection2-core@2.0.1
google-config-ui@1.0.1
mdg:validated-method
accounts-ui@1.3.1
mdg:meteor-apm-agent
meteorhacks:zones
fortawesome:fontawesome
percolate:migrations
meteorhacks:aggregate
mixmax:smart-disconnect
underscore@1.0.10
server-render@0.3.1
check@1.3.1
accounts-facebook@1.3.2
accounts-password@1.5.1
service-configuration@1.0.11
accounts-google@1.3.2
mdg:validation-error
email@1.2.3
ostrio:files
```

**.meteor/versions**

```
ccounts-base@1.4.3
accounts-facebook@1.3.2
accounts-google@1.3.2
accounts-oauth@1.1.16
accounts-password@1.5.1
accounts-ui@1.3.1
accounts-ui-unstyled@1.4.1
alanning:roles@1.2.16
aldeed:collection2-core@2.1.2
allow-deny@1.1.0
autoupdate@1.5.0
babel-compiler@7.2.1
babel-runtime@1.3.0
base64@1.0.11
binary-heap@1.0.11
blaze@2.3.3
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.6.0
caching-compiler@1.2.0
caching-html-compiler@1.1.3
callback-hook@1.1.0
check@1.3.1
dburles:collection-helpers@1.1.0
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.2.0
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.5.0
ecmascript@0.12.1
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.8.0
ecmascript-runtime-server@0.7.1
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0
facebook-oauth@1.5.0
fetch@0.1.0
fortawesome:fontawesome@4.7.0
geojson-utils@1.0.10
google-config-ui@1.0.1
google-oauth@1.2.6
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.1
id-map@1.1.0
inter-process-messaging@0.1.0
jquery@1.11.11
launch-screen@1.1.1
less@2.8.0
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
mdg:meteor-apm-agent@3.1.2
mdg:validated-method@1.2.0
mdg:validation-error@0.5.1
meteor@1.9.2
meteor-base@1.4.0
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
meteorhacks:inject-initial@1.0.4
meteorhacks:meteorx@1.4.1
meteorhacks:zones@1.6.0
minifier-css@1.4.0
minifier-js@2.4.0
minimongo@1.4.5
mixmax:smart-disconnect@0.0.4
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modern-browsers@0.1.2
modules@0.13.0
modules-runtime@0.10.2
mongo@1.6.0
mongo-decimal@0.1.0
mongo-dev-server@1.1.0
mongo-id@1.0.7
mongo-livedata@1.0.12
npm-bcrypt@0.9.3
npm-mongo@3.1.1
oauth@1.2.4
oauth2@1.2.1
observe-sequence@1.0.16
ordered-dict@1.1.0
ostrio:cookies@2.3.0
ostrio:files@1.10.2
percolate:migrations@1.0.2
promise@0.11.1
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
react-meteor-data@0.2.16
reactive-dict@1.2.1
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.1.0
server-render@0.3.1
service-configuration@1.0.11
session@1.1.8
sha@1.0.9
shell-server@0.4.0
socket-stream-client@0.2.2
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.12
standard-minifier-css@1.5.1
standard-minifier-js@2.4.0
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
ui@1.0.13
underscore@1.0.10
url@1.2.0
webapp@1.7.0
webapp-hashing@1.0.9
```

**.meteor/release**

```
METEOR@1.8
```

**Comment by benjamn** [comment]
It looks like the stray `>` is in the bundle for the `modules` package, which hosts everything installed in `node_modules`. Is there any way to identify the particular `>` character responsible (since there are a lot of candidates)?

**Comment by phillx** [comment]
@benjamn if you have a way how to find wrong one in production build tell me :))

**Comment by pmcochrane** [comment]
Try removing the minifier package and see if the error shows what package it is failing on.

**Comment by phillx** [comment]
> Try removing the minifier package and see if the error shows what package it is failing on.

I already did 

`meteor remove standard-minifier-js`

**Comment by phillx** [comment]
@benjamn Actually i found out that issue is "arrow function", can you help me resolve it ?

![screen shot 2018-10-15 at 21 54 22](https://user-images.githubusercontent.com/1339027/46974902-8eef9200-d0c5-11e8-9827-45d6bbc156b8.png)
![screen shot 2018-10-15 at 21 52 31](https://user-images.githubusercontent.com/1339027/46974903-8eef9200-d0c5-11e8-8b3e-62beba766d19.png)

**Comment by benjamn** [comment]
Are you using the npm package `dropbox-v2-api` anywhere in your app? If so, you can make sure that it gets compiled by the `ecmascript` package using [this technique](https://forums.meteor.com/t/litelement-import-litelement-html/45042/8?u=benjamn). In other words:
```bash
cd path/to/app
mkdir -p imports/links
cd imports/links
ln -s ../../node_modules/dropbox-v2-api .
cd ../..
meteor
```

**Comment by phillx** [comment]
@benjamn okay i tried this way, but now there is problem with const.
How to setup transpilation in meteor ? I have hard times finding this.

I tried browserstack.com - there is safari 9, used localtesting - so non minifed version is used, the errors in console are pretty long :

<img width="1291" alt="screenshot 2018-10-23 at 00 08 41" src="https://user-images.githubusercontent.com/1339027/47322418-228e0900-d658-11e8-87e4-1af056ea0b52.png">
<img width="1295" alt="screenshot 2018-10-23 at 00 09 09" src="https://user-images.githubusercontent.com/1339027/47322421-228e0900-d658-11e8-978b-115d84a7c1d6.png">
<img width="1290" alt="screenshot 2018-10-23 at 00 09 19" src="https://user-images.githubusercontent.com/1339027/47322420-228e0900-d658-11e8-8aeb-6b36a8ff8a4d.png">
<img width="1288" alt="screenshot 2018-10-23 at 00 09 28" src="https://user-images.githubusercontent.com/1339027/47322448-3e91aa80-d658-11e8-988d-9e042a1f9673.png">

**Comment by kiewietr** [comment]
I think im experiencing something similar with regards to the "const" usage in modules.js. IE11 is simply showing a blank page and fails (for starters) on modules.js row 28816:

```
for (const key of Object.keys(ansiStyles)) {
	ansiStyles[key].closeRe = new RegExp(escapeStringRegexp(ansiStyles[key].close), 'g');

	styles[key] = {
		get() {
			const codes = ansiStyles[key];
			return build.call(this, this._styles ? this._styles.concat(codes) : [codes], this._empty, key);
		}
	};
}
```

**Comment by phillx** [comment]
> I think im experiencing something similar with regards to the "const" usage in modules.js. IE11 is simply showing a blank page and fails (for starters) on modules.js row 28816:
> 
> ```
> for (const key of Object.keys(ansiStyles)) {
> 	ansiStyles[key].closeRe = new RegExp(escapeStringRegexp(ansiStyles[key].close), 'g');
> 
> 	styles[key] = {
> 		get() {
> 			const codes = ansiStyles[key];
> 			return build.call(this, this._styles ? this._styles.concat(codes) : [codes], this._empty, key);
> 		}
> 	};
> }
> ```
> * this is not 1.8 related, I also have this in 1.7. It seems related to some version(s) of NPM packages regarding babel (maybe others?)
> 
> update: ive added the exact same npm modules to a clean meteor app and this works fine. However; the modules.js looks completely different; so I dont know how to reproduce this currently.
> 
> Ive also reinstalled the npm modules with all kinds of different versions and different meteor versions (from 1.6 to 1.8) but it keeps breaking on the same thing in IE11.

From what i see this will be definitely issue with transpilation to < ES6, then the browsers which did not supported those features fails. I went through lot of issues having similar troubles, and no HowTo worked..

**Comment by kiewietr** [comment]
After some debugging of my production app, I was able to reproduce this issue with a **default** meteor app and using the [chalk](https://www.npmjs.com/package/chalk.) npm module: 

Simply installing this module, requiring it and adding "console.log(chalk.blue('Hello world!'));" somewhere in main.js breaks the application in IE11 for me.

**Comment by phillx** [comment]
Ok, @benjamn your workaround done the thing, i used browserstart with safari 9, on local non-production build, then just always checked first error / as rest is failing because of missing instances, declarations ... / then just read a code, and figure out which module i also need to link.

In my case i needed to link dropbox-v2-api, query-string, strict-uri-encode packages.

@kiewietr try this :
```
cd path/to/app
mkdir -p imports/links
cd imports/links
ln -s ../../node_modules/chalk .
cd ../..
meteor
```

**Comment by kiewietr** [comment]
@phillx @benjamn yea, I got it working using this workaround. Needed to link "chalk" and "ansi-style" packages.

Just for my understanding, why is this workaround required? Arent the node_modules compiled automatically or something?

**Comment by StorytellerCZ** [comment]
@kiewietr No, see: https://guide.meteor.com/using-npm-packages.html#recompile
