### ISSUE TITLE
[1.8] Unable to set NODE_ENV - It's always "development".

### ISSUE THREAD

**Issue by ogroppo** [meteor/meteor#10283]
Even with an empty meteor app `meteor create app` setting NODE_ENV becomes always "development" no matter the value. Only --production flag changes the value to "production", which shouldn't happen according to [https://guide.meteor.com/deployment.html#never-use-production-flag](https://guide.meteor.com/deployment.html#never-use-production-flag)

**Comment by StorytellerCZ** [comment]
The guide states that `--production flag is purely meant to simulate production minification, but does almost nothing else.`
The key word here being `almost`. I imagine that setting the node environment is part of the Meteor start.
But how are you setting the node environment now?

**Comment by ogroppo** [comment]
From a bash script
```sh
export NODE_ENV=local
meteor --settings settings/local.json
```
