### ISSUE TITLE
`Not authorized on admin to execute command { replSetGetStatus: ...` mongo logs 

### ISSUE THREAD

**Issue by Discordius** [meteor/meteor#10287]
I am running Meteor version 1.8.1 with hosting on Galaxy and Mlab, and using a standard DB connection string I am getting tons and tons of the following errors: 

```
`2018-10-16T15:28:35.771-0700 I ACCESS [conn89] Unauthorized: not authorized on admin to execute command { replSetGetStatus: "1", $db: "admin", $clusterTime: { clusterTime: Timestamp(1539728910, 20), signature: { hash: BinData(0, 56AB3F739F1E69C3E7EE371210D00106FA0ABE5D), keyId: 6613052065813889025 } }, lsid: { id: UUID("5ffa564e-ca6f-4a51-b1ff-6adeeed4ef0f") } }`
```

This seems to be the result of Meteor trying to access some kind of admin-level command. I chatted with Mlab support about this, and they said the following:

> I found a related issue in meteor, https://github.com/meteor/meteor/issues/9915. While some on that thread are suggesting to connect with admin, i think you should not rush on doing that and that the right thing to do here is consult with meteor, maybe by adding a comment on that issue or creating a new one. Does that help?

I agree with Mlab that admin access shouldn't be necessary, and I would prefer to avoid that. Is there any other way of fixing this bug? In any case, figured it might be useful to highlight this here.

**Comment by klaussner** [comment]
The only place where the `replSetGetStatus` command should be executed is in the Meteor tool (during startup):
https://github.com/meteor/meteor/blob/18762f97a285f05f868442a09a806699049e885b/tools/runners/run-mongo.js#L664-L665
Do you think you could create a small reproduction repo? Maybe the error is caused by a package?

**Comment by klaussner** [comment]
I'm closing this for now due to inactivity but feel free to reopen if you can share a reproduction. :slightly_smiling_face:
