### ISSUE TITLE
Two jquery versions in meteor initial bundle

### ISSUE THREAD

**Issue by ignl** [meteor/meteor#10289]
Meteor 1.8

Create simple-todos app.
Run meteor npm install --save jquery
Start an app with bundle visualizer

Expected:
From what I understand meteor will only use npm jquery version and the old one won't be used and should not be loaded in the bundle

Result:
There are two versions of jquery in the bundle

**Comment by arggh** [comment]
Just noticed the same while trying to reduce the size of our app bundle. I was also in belief that only the npm-originated version would be included, if available.

**Comment by arggh** [comment]
I even made a repro to make sure it wasn't anything funky with our app, but no it wasn't: https://github.com/arggh/meteor-jquery-issue

### How the repro was made
1. `meteor create app`
2. `cd app && meteor npm install --save jquery`

And here is a beautifully hand-crafted diagram visualizing the relative size that jQuery is occupying in the basic scaffolded app made with `meteor create` (it's about 50% or ~200kb).

<img width="1008" alt="starburst" src="https://user-images.githubusercontent.com/17210302/54077238-6ce9ec80-42be-11e9-8a2e-fe9569c5bf63.png">

**Comment by arggh** [comment]
Relevant issues:

https://github.com/meteor/meteor/issues/6864
https://github.com/meteor/meteor/issues/6626

**Comment by afrokick** [comment]
any news?

**Comment by evolross** [comment]
Did this get fixed in Meteor 1.8.2?

**Comment by filipenevola** [comment]
I don't think so as Ben's PR is not merged yet, I just marked as `confirmed` then stale bot will ignore it.
