### ISSUE TITLE
Email is not working after updating to 1.8, some kind of conflict with nodemailer

### ISSUE THREAD

**Issue by LukasDeco** [meteor/meteor#10296]
This is the file where I am using the Email.send method:

import { Mongo } from 'meteor/mongo';
import { Meteor } from 'meteor/meteor';
import { check } from 'meteor/check';
import { Email } from 'meteor/email';

export const Occasions = new Mongo.Collection('occasions');

if (Meteor.isServer) {
  Meteor.publish('occasions', function occasionsPublication() {
    return Occasions.find();
  });
}

Meteor.methods({

  'occasions.insert'(occasionName, occasionDate, gifteeId) {
    check(occasionName, String);

    if (! this.userId ) {
      throw new Meteor.Error('not-authorized');
    }
      var emailTo = "elconant.lukas@gmail.com";
      var from = "me@occasional.ly";
      var subject = "test";
      var text = "test";
      console.log(emailTo);
      
    Email.send({ emailTo, from, subject, text });
    return Occasions.insert({
            occasionName,
            occasionDate: new Date (occasionDate),
            createdAt: new Date(), // current time
            gifteeId,
            owner: Meteor.userId(),           // _id of logged in user
            username: Meteor.users.findOne(this.userId).username,
          });

  },

  'occasions.remove'(occasionId) {
    check(occasionId, String);

    if (! this.userId ) {
      throw new Meteor.Error('not-authorized');
    }

    Occasions.remove(occasionId)

  },

});

And this is the error that it is triggering:

I20181023-19:55:15.425(-4)? Exception while invoking method 'occasions.insert' {
 Error: No recipients defined
I20181023-19:55:15.426(-4)?     at SMTPConnection._formatError (C:\Users\Owner\A
ppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-
connection\index.js:558:19)
I20181023-19:55:15.427(-4)?     at SMTPConnection._setEnvelope (C:\Users\Owner\A
ppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-
connection\index.js:757:34)
I20181023-19:55:15.428(-4)?     at SMTPConnection.send (C:\Users\Owner\AppData\L
ocal\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connecti
on\index.js:394:14)
I20181023-19:55:15.428(-4)?     at PoolResource.send (C:\Users\Owner\AppData\Loc
al\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\pool-
resource.js:181:25)
I20181023-19:55:15.428(-4)?     at connect.err (C:\Users\Owner\AppData\Local\.me
teor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\pool-resour
ce.js:160:29)
I20181023-19:55:15.429(-4)?     at connection.login.err (C:\Users\Owner\AppData\
Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\po
ol-resource.js:137:25)
I20181023-19:55:15.429(-4)?     at SMTPConnection._actionAUTHComplete (C:\Users\
Owner\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\li
b\smtp-connection\index.js:1264:9)
I20181023-19:55:15.430(-4)?     at SMTPConnection._responseActions.push.str (C:\
Users\Owner\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mai
ler\lib\smtp-connection\index.js:341:26)
I20181023-19:55:15.430(-4)?     at SMTPConnection._processResponse (C:\Users\Own
er\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\s
mtp-connection\index.js:707:20)
I20181023-19:55:15.430(-4)?     at SMTPConnection._onData (C:\Users\Owner\AppDat
a\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-conne
ction\index.js:510:14)
I20181023-19:55:15.431(-4)?     at TLSSocket._socket.on.chunk (C:\Users\Owner\Ap
pData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-c
onnection\index.js:658:51)
I20181023-19:55:15.431(-4)?     at emitOne (events.js:116:13)
I20181023-19:55:15.432(-4)?     at TLSSocket.emit (events.js:211:7)
I20181023-19:55:15.432(-4)?     at addChunk (_stream_readable.js:263:12)
I20181023-19:55:15.432(-4)?     at readableAddChunk (_stream_readable.js:250:11)

I20181023-19:55:15.433(-4)?     at TLSSocket.Readable.push (_stream_readable.js:
208:10) code: 'EENVELOPE', command: 'API' }
W20181023-19:56:44.217(-4)? (STDERR) Note: you are using a pure-JavaScript imple
mentation of bcrypt.
W20181023-19:56:44.219(-4)? (STDERR) While this implementation will work correct
ly, it is known to be
W20181023-19:56:44.219(-4)? (STDERR) approximately three times slower than the n
ative implementation.
W20181023-19:56:44.220(-4)? (STDERR) In order to use the native implementation i
nstead, run
W20181023-19:56:44.221(-4)? (STDERR)
W20181023-19:56:44.221(-4)? (STDERR)   meteor npm install --save bcrypt
W20181023-19:56:44.222(-4)? (STDERR)
W20181023-19:56:44.222(-4)? (STDERR) in the root directory of your application.
I20181023-19:56:43.893(-4) (packages\percolate_synced-cron.js:87) SyncedCron: Sc
heduled "Reminders" next run @Tue Oct 23 2018 20:30:00 GMT-0400 (Eastern Dayligh
t Time)
=> Meteor server restarted
I20181023-19:56:53.902(-4)? elconant.lukas@gmail.com
I20181023-19:56:54.301(-4)? Exception while invoking method 'occasions.insert' {
 Error: No recipients defined
I20181023-19:56:54.303(-4)?     at SMTPConnection._formatError (C:\Users\Owner\A
ppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-
connection\index.js:558:19)
I20181023-19:56:54.304(-4)?     at SMTPConnection._setEnvelope (C:\Users\Owner\A
ppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-
connection\index.js:757:34)
I20181023-19:56:54.304(-4)?     at SMTPConnection.send (C:\Users\Owner\AppData\L
ocal\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connecti
on\index.js:394:14)
I20181023-19:56:54.305(-4)?     at PoolResource.send (C:\Users\Owner\AppData\Loc
al\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\pool-
resource.js:181:25)
I20181023-19:56:54.306(-4)?     at connect.err (C:\Users\Owner\AppData\Local\.me
teor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\pool-resour
ce.js:160:29)
I20181023-19:56:54.306(-4)?     at connection.login.err (C:\Users\Owner\AppData\
Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-pool\po
ol-resource.js:137:25)
I20181023-19:56:54.307(-4)?     at SMTPConnection._actionAUTHComplete (C:\Users\
Owner\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\li
b\smtp-connection\index.js:1264:9)
I20181023-19:56:54.308(-4)?     at SMTPConnection._responseActions.push.str (C:\
Users\Owner\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mai
ler\lib\smtp-connection\index.js:341:26)
I20181023-19:56:54.308(-4)?     at SMTPConnection._processResponse (C:\Users\Own
er\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\s
mtp-connection\index.js:707:20)
I20181023-19:56:54.309(-4)?     at SMTPConnection._onData (C:\Users\Owner\AppDat
a\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-conne
ction\index.js:510:14)
I20181023-19:56:54.310(-4)?     at TLSSocket._socket.on.chunk (C:\Users\Owner\Ap
pData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-c
onnection\index.js:658:51)
I20181023-19:56:54.310(-4)?     at emitOne (events.js:116:13)
I20181023-19:56:54.311(-4)?     at TLSSocket.emit (events.js:211:7)
I20181023-19:56:54.311(-4)?     at addChunk (_stream_readable.js:263:12)
I20181023-19:56:54.312(-4)?     at readableAddChunk (_stream_readable.js:250:11)

I20181023-19:56:54.312(-4)?     at TLSSocket.Readable.push (_stream_readable.js:
208:10) code: 'EENVELOPE', command: 'API' }

I have uninstalled and reinstalled meteor twice. I am on Windows 10 and running version 1.8. I have updated node4mailer to the latest available version.

Please let me know if you have any questions and thank you!

**Comment by LukasDeco** [comment]
Also, if it helps, here are my package.json dependencies:
"dependencies": {
    "@babel/runtime": "^7.1.2",
    "body-parser": "^1.18.3",
    "dotenv": "^6.1.0",
    "meteor-node-stubs": "^0.4.1",
    "moment": "^2.22.2",
    "react": "^16.5.2",
    "react-datepicker": "^1.6.0",
    "react-dom": "^16.5.2"
  },

And in my .meteor/packages file

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.6.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.5.0   # CSS minifier run for production mode
standard-minifier-js@2.4.0    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.12.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.4.0            # Server-side component of the `meteor shell` command

insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
accounts-base@1.4.3
useraccounts:core
useraccounts:unstyled
accounts-password@1.5.1
react-meteor-data
email
aldeed:template-extension
fourseven:scss
percolate:synced-cron

**Comment by od1k** [comment]
Error: No recipients defined
You are passing wrong arguments to Email.send()

This line:
Email.send({ **emailTo**, from, subject, text });
should be
Email.send({ **to: emailTo**, from, subject, text });

**Comment by LukasDeco** [comment]
Wow, so simple. Now it works.

But why does the docs show this? 

```
// Server: Define a method that the client can call.
Meteor.methods({
  sendEmail(to, from, subject, text) {
    // Make sure that all arguments are strings.
    check([to, from, subject, text], [String]);

    // Let other method calls from the same client start running, without
    // waiting for the email sending to complete.
    this.unblock();

    Email.send({ to, from, subject, text });
  }
});

// Client: Asynchronously send an email.
Meteor.call(
  'sendEmail',
  'Alice <alice@example.com>',
  'bob@example.com',
  'Hello from Meteor!',
  'This is a test of Email.send.'
);
```

That makes it look like I should do it the way I was doing it.

**Comment by LukasDeco** [comment]
You can close but just wanted to mention the docs.

**Comment by klaussner** [comment]
@LukasDeco The docs are correct. `Email.send({ to, ... })` is a [shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015) for `Email.send({ to: to, ... })`. :slightly_smiling_face:
