### ISSUE TITLE
Add ability to add classes to <html>

### ISSUE THREAD

**Issue by badslug** [meteor/meteor#103]
It would be useful to be able to inject html before or modify the outermost <html> element. Alternatively, just have a meteor setting/flag to specifically address <html> conditional styling.

The desired result is to use IE conditional comments to add styles to the outer <html> element for cleaner, cross browser styling. See:

http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/

This is a technique used in popular html frameworks like HTML5 Boilerplate, ZURB Foundation, etc.

Currently meteor does not allow us to access on affect the <html> tag that is generated (at least that I've found so far) preventing this technique from supporting older IE browsers.

**Comment by keyvanfatehi** [comment]
Hi so I wanted to add Modernizr and had to figure this out. I ended up with this code, which is working.

```js
Meteor.startup(function() {
  WebApp.addHtmlAttributeHook(function() {
    return {
      class: "no-js"
    }
  })
});
```
