### ISSUE TITLE
how to disable cordova hot code push?

### ISSUE THREAD

**Issue by yangchunboy** [meteor/meteor#10306]
in my ios App, I want to disable hot code push, i have search the solution, but all is useless, my meteor vesion is 1.4.2.3, run on mac

**Comment by aliogaili** [comment]
I think this should have been posted in the forum, can you please close this and follow-up [here](https://forums.meteor.com/t/disable-hot-code-push-on-mobile/38732/7).

**Comment by yangchunboy** [comment]
@aliogaili ok, i will close it
