### ISSUE TITLE
[BUG][meteor/oauth] Is not transpiled with ecmascript

### ISSUE THREAD

**Issue by phillx** [meteor/meteor#10305]
meteor-oauth:1.2.5
meteor 1.8

```
SyntaxError: Unexpected token ')'
(anonymous function)  end_of_popup_response.js:1
```

Browser Safari 9.1

Only experiencing with browser without support of ES6+

How i have to tell meteor to transpile it's core package ?

@benjamn do you have workaround for this also ? 🥇

**Comment by StorytellerCZ** [comment]
That is strange, the package does include the `ecmascript` package so it should work just fine. Maybe this could be related to #10251? What browser is the issue?

**Comment by phillx** [comment]
> That is strange, the package does include the `ecmascript` package so it should work just fine. Maybe this could be related to #10251? What browser is the issue?

Yes i checked that in repo, it contains, package.use ecmascript, so idk why its still as arrowFunction in the end. Question is if ECMAScript is compiling all files in folder as package even if they do not refer to each other .

**Comment by nathan-muir** [comment]
Those JS files are used as assets in static modals. They aren't compiled by `ecmascript` at all.

Will need to revert https://github.com/meteor/meteor/commit/fcd650bd46511e3192098d06e0be2f2083ebc745 for `end_of_popup_response.js` and `end_of_redirect_response.js`
