### ISSUE TITLE
[1.8] Unable to resolve some @babel modules

### ISSUE THREAD

**Issue by zeta-o** [meteor/meteor#10302]
Hi guys,
I just updated to meteor 1.8. When I run meteor this message appears:

Unable to resolve some modules:

  "@babel/runtime/helpers/builtin/interopRequireDefault" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/index.js (web.browser)
  "@babel/runtime/helpers/builtin/objectSpread" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/createMuiTheme.js (web.browser)
  "@babel/runtime/helpers/builtin/objectWithoutProperties" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/createMuiTheme.js (web.browser)
  "@babel/runtime/helpers/builtin/defineProperty" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/createMixins.js (web.browser)
  "@babel/runtime/helpers/builtin/interopRequireWildcard" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/MuiThemeProvider.js (web.browser)
  "@babel/runtime/helpers/builtin/classCallCheck" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/MuiThemeProvider.js (web.browser)
  "@babel/runtime/helpers/builtin/createClass" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/MuiThemeProvider.js (web.browser)
  "@babel/runtime/helpers/builtin/possibleConstructorReturn" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/MuiThemeProvider.js (web.browser)
  "@babel/runtime/helpers/builtin/inherits" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/MuiThemeProvider.js (web.browser)
  "@babel/runtime/helpers/builtin/extends" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/withStyles.js (web.browser)
  "@babel/runtime/helpers/builtin/typeof" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/styles/getStylesCreator.js (web.browser)
  "@babel/runtime/helpers/builtin/toConsumableArray" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/Select/SelectInput.js (web.browser)
  "@babel/runtime/helpers/builtin/assertThisInitialized" in /Users/alonzo/Workspace/dliver.io/node_modules/@material-ui/core/Modal/Modal.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime

But when I run the command above, it's updated to babel 7.1.2 but it doesn't fix the problem.

**Comment by dovydaskukalis** [comment]
This should automatically install all dependencies needed https://github.com/babel/babel-upgrade.
