### ISSUE TITLE
Android build fails with 1.8

### ISSUE THREAD

**Issue by honwlt** [meteor/meteor#10308]
- [ ] The version of Meteor showing the problem.
1.8
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable
1.6.x
- [ ] The operating system you're running Meteor on.
linux
- [ ] The expected behavior.
Android build success
- [ ] The actual behavior.
I get gradle build error:

 Building Cordova app for Android          /                       
:preBuild
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:processReleaseManifest
 FAILEDding Cordova app for Android          -                

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

- [ ] reproduction
Include android platform and cordova:phonegap-plugin-push@1.11.1 plugin in the project.

Workaround:
 [cordova build issue](https://github.com/invertase/react-native-firebase/issues/1194)
Per above link, if we push  jcenter() down the maven block in the build.gradle script, the build is successfull.
But requires manual intervention.  

Current: 
```
buildscript {
    repositories {
          jcenter()
        maven {
            url "https://maven.google.com"
        }
      
    }
```

Workaround: 
```
buildscript {
    repositories {
        
        maven {
            url "https://maven.google.com"
        }
  jcenter()
      
    }
```

**Comment by zhang2118** [comment]
Hi @honwlt , could you please specify which `build.gradle` file did you modify? What's the directory? Thanks!

**Comment by honwlt** [comment]
No fix yet, just a workaround.
The below file you need to modify before meteor completes cordova build.
<project folder>/.meteor/local/cordova-build/platforms/android/build.gradle

**Comment by lorensr** [comment]
I did the build, got the error, edited and saved the gradle file in root app directory. Then ran build again in one tab and this in another: `fswatch -1 .meteor/local/cordova-build/platforms/android/build.gradle; cp build.gradle .meteor/local/cordova-build/platforms/android/; say 'done copying gradle file'` (requires `brew install fswatch`)

**Comment by dagatsoin** [comment]
I have the same problem with https://github.com/mauron85/cordova-plugin-background-geolocation

The readme states: 
`Android is no longer supporting downloading support libraries through the SDK Manager. The support libraries are now available through Google's Maven repository.`
