### ISSUE TITLE
Run from a local checkout is not working with mdg:meteor-apm-agent

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#10317]
Hello, sometimes I need to run Meteor from a local checkout to add some logs or test some edge case but my application is failing to start with `mdg:meteor-apm-agent` package.

The error that happens is:
```
TypeError: Cannot read property 'constructor' of undefined
W20181031-10:34:59.185(-4)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
```

and `meteorhacks:meteorx` is added by `mdg:meteor-apm-agent`

The workaround is to remove the mdg:meteor-apm-agent to run from a local but that takes time and changes all the time.

Again, that only happens running from a local checkout.

**Comment by s7dhansh** [comment]
https://github.com/meteor/meteor/issues/10337#issuecomment-441717091 discusses the issue in detail. A PR has been added to the meteorx package, but needs to be merged.

**Comment by benjamn** [comment]
Working on removing the `meteorhacks:meteorx` dependency from `mdg:meteor-apm-agent`: https://github.com/meteor/meteor-apm-agent/pull/7

**Comment by filipenevola** [comment]
Closing this as the problem is already fixed.
