### ISSUE TITLE
Unable to debug Meteor 1.8 server code

### ISSUE THREAD

**Issue by mohammadidinani** [meteor/meteor#10315]
Greetings,

We use WS 2018.2.5 and Meteor 1.8. Debugging used to work fine in WS 2017.3 and Meteor 1.5, but it stopped working after migrating to the latest versions. More importantly, some server breakpoints are never get activated, the debugger does not stop on some breakpoints although they are activated and some breakpoints get hit but on different lines!

I tried the following with no luck!

- Downgrading WS to 2017.3
- Updating source-map package to the latest version
- Using --inspect and --inspect-brk

Any idea how to fix this?

Best,
Mohammad

**Comment by krizka** [comment]
Yes, its the problem with WS, for me helped to use WS 2017.1.6 for now, until bug will be fixed.
https://youtrack.jetbrains.com/issue/WEB-34012

**Comment by mohammadidinani** [comment]
WS 2018.1.6 does not seem to work either. Still having the same issues.

**Comment by krizka** [comment]
It is really strange. I remember, after update from 1.5 debugger started to work worse than before, like it `continued run` after I just wanted to `make one step`, but I could live with it, just making few more breakpoints. Have you done `meteor reset`?

**Comment by mohammadidinani** [comment]
Yes, I did. The new inspector seems to be problematic. [This](https://github.com/v8/v8/commit/a8f6869177685cfb9c199c454a86f4698c260515) may resolve some issues, but I have not tried it yet.
