### ISSUE TITLE
@babel/runtime not present in meteor build

### ISSUE THREAD

**Issue by krizka** [meteor/meteor#10318]
Suddenly I started to get this error on startup: 
```
.meteor/local/build/programs/server/boot.js:475
}).run();
   ^

TypeError: Cannot read property 'indexOf' of undefined
    at babel-runtime.js (packages/babel-runtime.js:36:26)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at packages/babel-runtime.js:85:15
    at packages/babel-runtime.js:92:3
    at .meteor/local/build/programs/server/boot.js:411:36
```
After some investigation, I found out that `@babel/runtime` directory is not present in `.meteor/local/build/programs/server/npm/node_modules`.
 I temporarely fixing this by creating symlink there from `node_modules/@babel/runtime`, but it is not working for production build where I can not get into the build process and add that link.
What I already tried:
* `meteor npm install @babel/runtime`
* meteor reset
* removal of `node_modules`

Using `meteor@1.8`

**Comment by benjamn** [comment]
Is `@babel/runtime` in the `dependencies` section of the `package.json` file in the root directory of your application?

**Comment by krizka** [comment]
Yes it is there, but it were in `devDependencies`, moved it to `dependencies` and it helped! Thanks!
But one more strange thing – it always were there in dev deps without any problems with any Meteor version. Maybe that happened after update of modules, but also I tried my old `versions` and `packages` without luck.

**Comment by gitren** [comment]
use `meteor npm install  -g @babel/runtime@latest` OK
