### ISSUE TITLE
[1.8] standard-minifier-css removes "-webkit-box-orient: vertical;"

### ISSUE THREAD

**Issue by ddett** [meteor/meteor#10319]
Meteor 1.8 removes the css property "-webkit-box-orient: vertical;" when building for production. this happens during minification as it is not a problem in dev environment. 

Steps to reproduce:
- Create new 1.8 project. 
- add "-webkit-box-orient: vertical;" to the body element in main.css 
- run meteor with the "--production" flag (e.g. meteor --production)
- inspect html with browser dev tools and check the css properties on the body element = see that the property is gone.

If running without the "--production" flag, the property will be visible in dev tools just fine.

When did this start:
This has not been an issue prior to 1.8.

Why I need this to work:
"-webkit-box-orient: vertical;" is a fairly old / weird css property but it is necessary to make css based line-clamping work in safari and chrome. https://css-tricks.com/line-clampin/

It seems autoprefixer also had this issue before. https://stackoverflow.com/questions/42967560/webkit-box-orient-vertical-in-sass-is-not-compiled-in-gulp

What I've tried so far: 
- I replaced "standard-minifier-css" with "seba:minifiers-autoprefixer" which fixes the issue when using "/* autoprefixer: off */" (see the link above) but introduced other problems specific to my app, so I rolled that back.
- I added "stlye='-webkit-box-orient: vertical;'" to all html elements that need to do line-clamping. this works fine and is my current work around, but it is a pretty dirty / hacky solution.

**Comment by Timmi-TS** [comment]
Having the same problem with "display: -webkit-flex".

We removed the "standard-minifier-css" package and used the "juliancwirko:postcss" instead, same problem. Maybe the "minifier-css" package causes this issue.
