### ISSUE TITLE
[1.8] Unexpected mongo exit code 14. Restarting. on Meteor 1.8 upgrade

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#10325]
When upgrading from Meteor 1.7.0.5 to Meteor 1.8 I ran into this issue again:

https://github.com/meteor/meteor/issues/9871

I ran the compatibility steps (also for Meteor 4.0) and started running into error code 14 (before it was 62). I've tried a few things, but haven't figured out a way to start Meteor locally.

Error:
```
Unexpected mongo exit code 14. Restarting.
```

**Comment by sdubrez** [comment]
I'm running into the same issue after `git pull` in my meteor project.

Also, using `meteor reset` seems to kinda fix this issue but it would be perfect if an alternative without reset exists. Reset is deleting the entire database which is annoying...

**Comment by yonuttoty** [comment]
I'm using docker with ubuntu 16.04 and I'm getting the same error. Using `meteor reset` does not work.
Any ideas?

**Comment by MJO9** [comment]
I have the same issue when I create a fresh project and I could not start it getting:

> Unexpected mongo exit code 14 Restarting.

then I tried Meteor reset and tried to delete db folder inside .meteor now getting the error:

> Unexpected mongo exit code null. Restarting.

:\
