### ISSUE TITLE
Meteor 1.8 create react APP & .babelrc file

### ISSUE THREAD

**Issue by DeanKamali** [meteor/meteor#10332]
on vanilla meteor 1.8, I have followed the docs to create react App like so:

```
meteor create --react testApp 
```
However my Babel plugins that support => v7.0 doesn't seem to work anymore, for example, ```"jsx-control-statements"```

I have created a cloud9 environment that shows the error.

https://ide.c9.io/amlife/test (github login is required) 

Your thoughts and ideas are highly appreciated.

**Comment by Deadly0** [comment]
Try `babel.config.js` instead (https://babeljs.io/docs/en/configuration#babelconfigjs)

**Comment by sakulstra** [comment]
@DeanKamali not sure if i get your question correctly, but 1.8 comes with babel 7, so you should be able to use v7 plugins (which means "jsx-control-statements@v4") - as far as i know meteor doesn't support `babel.config.js` yet as it uses its custom way to load babel files.

**Comment by benjamn** [comment]
That custom way being `.babelrc` files, specifically, and not `babel.config.js` (yet).

**Comment by DeanKamali** [comment]
@sakulstra I have tried using the following config but no luck, it doesn't seems that its being loaded, any other ideas? 
```
{
  "plugins": [
    "jsx-control-statements@v4"
  ]
}
```

![screen shot 2018-11-14 at 10 34 22 am](https://user-images.githubusercontent.com/1252959/48492973-f6018300-e7f8-11e8-9e6d-092182e5dd3d.png)

https://ide.c9.io/amlife/test (github login is required)

**Comment by sakulstra** [comment]
> which means "jsx-control-statements@v4"

with this i meant, you have to make sture that correct version is installed in your node_modules (package.json). jsx-control-statements@3.x is for babel 6 and @4.x it's for babel 7 (never used this package but it's what the readme says)

the .babelrc should just stay the same:
```
{
  "plugins": [
    "jsx-control-statements"
  ]
}
```

**Comment by DeanKamali** [comment]
I'm using `METEOR@1.8.1 ` and ` .babelrc ` config like so: 

```
{
    "plugins": ["jsx-control-statements"]
}

```
My JSX control statement like so

```
<For each="item" index="index" of={[1,2,3]}>
  <span key={item}>{item}</span>
</For>
```
But here is what I get: 
```
[1, 2, 3, 4].map(function (item, index) {
    > 53 |               return <span key={item}>{item}</span>;
        |               ^
     54 |             }, this)
```
I managed to fix it by wrapping the statement with curly braces, like so: 
```
{<For each="item" index="index" of={[1,2,3]}>
  <span key={item}>{item}</span>
</For>}
```
Then it worked
