### ISSUE TITLE
Possible memory leak in Mongo response?

### ISSUE THREAD

**Issue by carlopascual** [meteor/meteor#10333]
During load testing, we experienced an abnormally high amount of memory usage for logging in. We are using Meteor 1.8.1-beta.3/1.8.1-beta.4 with `loginWithPassword` from https://github.com/orionsoft/meteor-apollo-accounts. Upon checking the memory heap, we saw that Mongo’s `deserializeObject` was taking a big chunk of our memory.

![screenshot 2018-11-13 at 11 26 08](https://user-images.githubusercontent.com/13900345/48412467-0ce69d80-e745-11e8-99a4-89f2df566af9.png)

The CPU profile seems to be filled with small but plenty `deserializeObject` calls.

![screenshot 2018-11-13 at 11 38 53](https://user-images.githubusercontent.com/13900345/48412480-17a13280-e745-11e8-9adc-dd41238badc2.png)

![screenshot 2018-11-13 at 11 28 14](https://user-images.githubusercontent.com/13900345/48412485-1a9c2300-e745-11e8-9689-487b3c9cebe5.png)

Is this normal? Has anyone else experienced this? Here are the dumps if you’d like to check it out yourselves, which you can view using Chrome’s Node DevTools:

[mongo-leaks.zip](https://github.com/meteor/meteor/files/2576161/mongo-leaks.zip)

**Comment by KoenLav** [comment]
Do you subscribe to and/or change something in the publication after logging in?

We experienced similar performance hits when logging in because we subscribed to many collections before logging in and only populated then after a user logged in (if this.userId in the publication).

**Comment by AndrewMorsillo** [comment]
I may be running into this as well. deserializeObject appears to be a huge chunk of my heap allocations and they aren't getting released.

**Comment by Jeremias-Nater** [comment]
We load sample data into our DB and we experience 100% CPU load during 6 minutes after startup. The profile shows that during that time, `deserializeObject` takes up most of most of the resources. Also our publications have gotten slow lately and we are now using APM to try and find out the cause, but without success so far. Any hints?

**Comment by doronrk** [comment]
@Jeremias-Nater we are now experiencing this too, except using mongoose, not meteor. Did you ever get to the bottom of this?

**Comment by Grubba27** [comment]
Hey @doronrk, in what version of Meteor are you using? We had this issue again in 2.8, but it was solved in 2.8.2 and 2.9 is solved as well.
