### ISSUE TITLE
`node_modules` missing in `bundle-visualizer`

### ISSUE THREAD

**Issue by morloy** [meteor/meteor#10335]
_Originally posted by @sakulstra in https://github.com/meteor/meteor/pull/9942#issuecomment-401933736_

Seems like the `node_modules` got lost in the bundle visualizer since Meteor 1.8. Would be nice to have 'em back 😄

**Comment by benjamn** [comment]
Presumably due to another minifier update. Any guesses?

**Comment by morloy** [comment]
Nope.

**Comment by benjamn** [comment]
Having trouble reproducing this after a brief attempt. Any npm packages I install in the app show up under `web.browser > (modules) > node_modules > ...` in the visualizer:

![screenshot 2018-11-15 13 34 30](https://user-images.githubusercontent.com/5750/48573750-3802f580-e8db-11e8-92ff-65010e8c7be5.png)

If there's a problem with the way `standard-minifier-js` is [scanning the minified bundle to extract the stats](https://github.com/meteor/meteor/blob/devel/packages/standard-minifier-js/plugin/stats.js), it might be sensitive to the combination of packages (both Meteor and npm) that you're using. Would you mind sharing your `.meteor/packages` file and `package.json` dependencies? And just to be sure, are you still using the `standard-minifier-js` package?

**Comment by morloy** [comment]
Ah, true. Was using `zodern:standard-minifier-js`, which caused the behavior. Everything’s all right with the standard package, only source maps are missing. Thanks for pointing that out 😉

**Comment by benjamn** [comment]
@morloy Based on https://github.com/meteor/meteor/pull/10341, I'm guessing if `standard-minifier-js` supported production source maps, you'd be happy to switch back? Anything else we're missing?

**Comment by morloy** [comment]
Exactly, only source maps are missing.
