### ISSUE TITLE
[BUG][meteor/oauth] Is not transpiled with ecmascript

### ISSUE THREAD

**Issue by idmadj** [meteor/meteor#10347]
This is a followup to #10305.

IE11 errors out on the property shorthands in `end_of_popup_response.js`:
```
SCRIPT1003: Expected ':'
end_of_popup_response.js (12,24)
```
The shorthands need to be reverted to legacy JS like the rest.

**Comment by aliogaili** [comment]
I think you tagged the wrong issue in your fix.

**Comment by idmadj** [comment]
> I think you tagged the wrong issue in your fix.

Can you elaborate? Tags look fine to me

**Comment by aliogaili** [comment]
I think it's that commit https://github.com/idmadj/meteor/commit/1367da9c71d51f6aeb19226ca99a6978dc8f651c
it's referring to this issue https://github.com/meteor/meteor/issues/10346

**Comment by idmadj** [comment]
> I think it's that commit [idmadj@1367da9](https://github.com/idmadj/meteor/commit/1367da9c71d51f6aeb19226ca99a6978dc8f651c)
> it's referring to this issue #10346
> ignore me otherwise..

Gotcha, this is a cached dangling commit. The PR points to the right commit/issue.
