### ISSUE TITLE
Outdated comment in google-oauth package

### ISSUE THREAD

**Issue by vuhrmeister** [meteor/meteor#10344]
I just stumbled upon this comment: https://github.com/meteor/meteor/blob/devel/packages/google-oauth/package.js#L8-L9

Since the PR which is mentioned there (https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/366) got merged: is there anything to update in this package? At least the comment is not valid anymore.

**Comment by chrishanyu** [comment]
Bump.

Newer versions in `cordova-plugin-google`  package allow users to specify `PLAY_SERVICES_VERSION` which helps resolve gms version conflicts. Updating this dependency would save us some manual changes to `build.gradle` script every time we make an android build.
