### ISSUE TITLE
Installing version 1.8.0.1-rc.4 from install.meteor.com

### ISSUE THREAD

**Issue by benjii** [meteor/meteor#10351]
Hi,

We are using https://github.com/jshimko/meteor-launchpad to create Docker images for our application. It works great.

We have just upgraded to Meteor 1.8. However, due to certain issues, documented variously in the issues found here, we have had to use Meteor version 1.8.0.1-rc.4.

Unfortunately, it appears that this version is not available on install.meteor.com, which is the place where the Docker build tries to install Meteor from. We get this error:

```
[-] Installing Meteor 1.8.0.1-rc.4...

Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```

So my question is... would it be possible to release this version to install.meteor.com? Or perhaps there is some other alternative?

Thanks in advance,
Ben

**Comment by benjii** [comment]
Awesome, win-win! Thanks. 👍

**Comment by Larens94** [comment]
hello, I can't install version 1.8.0.1.

error:
  curl https://install.meteor.com/\?release\=1.8.0.1 | sh

Downloading Meteor distribution
curl: (22) The requested URL returned error: 403

Retrying download in 5 seconds...
curl: (22) The requested URL returned error: 403

Retrying download in 5 seconds...
curl: (22) The requested URL returned error: 403

Retrying download in 5 seconds...


Sincerely.
