### ISSUE TITLE
[1.8.0.1] meteor build produces inconsistent bundles

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#10360]
Hey,

I am still on my mission to fight the initial HCP that can happen on android/ios builds that's caused by inconsistent builds.
Thanks once again for handling this one: https://github.com/meteor/meteor/issues/9878
Unfortunately the issue came back and this time I have a really weird difference:

This is part from the produced production bundle:
```javascript
    }, {
        extensions: [".js", ".json", ".html", ".scss", ".protocol", ".css"]
    });
    var exports = require("/node_modules/meteor/modules/client.js");
    Package._define("modules", exports, {
        meteorInstall: meteorInstall
    })
```
and this is the same part but from another build:
```javascript
    }, {
        extensions: [".js", ".json", ".html", ".scss", ".css", ".protocol"]
    });
    var exports = require("/node_modules/meteor/modules/client.js");
    Package._define("modules", exports, {
        meteorInstall: meteorInstall
    })
}();
```
The difference is here:
extensions: [".js", ".json", ".html", ".scss", **".protocol", ".css"]**
extensions: [".js", ".json", ".html", ".scss", **".css", ".protocol"]**

so maybe it has to do something with build plugins lazy compilation?

**Comment by wojtkowiak** [comment]
Maybe just adding array sort is a simple and quick fix for this.

**Comment by wojtkowiak** [comment]
Perhaps here? https://github.com/meteor/meteor/blob/d5aa1ba5b9fa76678157b969ebbe398dd261af0c/tools/isobuild/compiler-plugin.js#L1131

**Comment by smeijer** [comment]
There are more changes to the bundle. 1.8.0.1 also exposes a lot more information trough the minified code. Filepaths and dependencies, are clearly stated. 

I had an error in my test build, which was reported as `error in /src/imports/modules/auth/components/Login.js`.

Searching the bundle, I see complete paths of every react component. And also dependencies like `@material-ui/core` and `react-router-dom`. These terms do not show up in our current production bundle.

Guess it's time for a revert.
