### ISSUE TITLE
[1.8] ReplicaSet can't begin with number

### ISSUE THREAD

**Issue by geekgonecrazy** [meteor/meteor#10362]
Starting with Meteor 1.8 if you try to connect to your mongo replicaset and the name begins with a number.  You will get: 

```
MongoError: no primary found in replicaset or invalid replica set name
```

Example of connection string:
```
MONGO_URL=mongodb://127.0.0.1:27017/rocketchat?replicaSet=001-rs
```

### tldr; 
Mongo driver 3.1.6 breaks replicaSet option starting with a number.  Mongo driver 3.1.9 includes the fix for it. 

We have this effecting several users.  Would be great to be able to get a patch out for this.

### Details

It looks like with Meteor 1.8 the mongo driver was updated to: 3.1.6 in https://github.com/meteor/meteor/commit/e0d9a66ec4ad22a5725ed593a2dc859f0732c3ef 

Previously it was 3.1.1 

A bit of digging looks like: https://github.com/mongodb-js/mongodb-core/commit/a4e0bb5f31749430d40340a78058b418a5a340bd#diff-e7988fe891fe85263e64ee22379a96b3 introduced some validation to the connection string in version 3.1.6 [history of the file](https://github.com/mongodb-js/mongodb-core/commits/v3.1.6/lib/uri_parser.js)

Here the issue looks to actually be fixed in the mongo driver core.  https://github.com/mongodb-js/mongodb-core/commit/d00b1ab that is present in 3.1.8

The mongodb package looks like adapts mongodb-core@3.1.8 in mongodb@[3.1.9](https://github.com/mongodb/node-mongodb-native/blob/master/HISTORY.md#319-2018-11-06)

**Comment by rodrigok** [comment]
@benjamn any idea when the 1.8.1 will land? Any chance of reave a 1.8.0.2 upgrading mongodb only to fix this? It's quite important for us.

Thanks

**Comment by sebakerckhof** [comment]
@rodrigok you could try locally cloning the package and upgrading the mongo driver in your /packages folder of your project for the time being.

**Comment by geekgonecrazy** [comment]
Not a big fan of this idea.  I’m not sure what kind of side effects differing from meteors shipped mongo driver might have?

**Comment by sebakerckhof** [comment]
Would have to be looked at on a case-by-case basis, but here it seems only the version got bumped: https://github.com/meteor/meteor/pull/10248/commits/29db9cbd44a6e3f42c435e4d6dedbf56f3056871 so should be low-risk.

**Comment by rodrigok** [comment]
@geekgonecrazy I think we need to go this way, @sampaiodiego can you upgrade it?

**Comment by xbiafra** [comment]
Any updates?

**Comment by geekgonecrazy** [comment]
I don’t believe this has actually been fixed

**Comment by filipenevola** [comment]
This should be resolved here https://github.com/meteor/meteor/pull/10723 but this PR is not merged yet.

**Comment by geekgonecrazy** [comment]
Not really closed from sale.  Closed from that PR being merged.  #10723
