### ISSUE TITLE
Aggregate count query is not working anymore in Meteor 1.8

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#10383]
I have been using Aggregate in queries for getting total records count, but today I migrated from Meteor 1.6 to 1.8, and now this following query is giving me an exception:

I am using meteorhacks:aggregate @ version 1.3.0 on server-side

Query:

```
getUserArticlesCounter: function () {

	return Articles.aggregate([
	      { $match: {userId: 'a767GGhrd743Ghe349sd'} },
	      { $group: { _id: null, count: { $sum: 1 } } }               
	])[0];
},
```

Exception:

`TypeError: Cannot read property \'count\' of undefined\n`

In Meteor 1.6 same query was giving me the counter but as I have updated to Meteor 1.8, now it is not working anymore.

**Comment by evolross** [comment]
`meteorhacks:aggregate` hasn't been updated in three years per its Github page. Have you tried any of the [forks](https://github.com/meteorhacks/meteor-aggregate/network) that have been updated more recently?  [One of them](https://github.com/fangjj/meteor-aggregate) looks like it was updated to work in 1.7.x.

**Comment by rijk** [comment]
It is because the interface has changed for the `aggregate()` method; it will now return a Mongo cursor instead of an array. To get the same return, you'd have to do a `.toArray()` call.

**Comment by aliogaili** [comment]
I just tested it using @rijk suggestion by awaiting to .toArray() and it seems to be working.

**Comment by aliogaili** [comment]
Should we close this issue? I think it's resolved.
