### ISSUE TITLE
 ❗️ 1.8.1-beta.9

### ISSUE THREAD

**Issue by pgiani** [meteor/meteor#10386]
On MacOS Mojave 10.14.2, can't update from beta.8 to beta.9 get the fallowing error.

 
        $ meteor update --release 1.8.1-beta.9

`This project uses Meteor 1.8.1-beta.9, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@1.8.0.1 to pin this app to the newest compatible release.
`

**Comment by benjamn** [comment]
You're totally right! The publish job stalled yesterday, but I restarted it just now. If it stalls again, I'll dig in and fix it.

**Comment by StorytellerCZ** [comment]
Fixed now.

**Comment by benjamn** [comment]
Yep, the `meteor login` credentials had expired on Jenkins. Thanks for your patience, and for testing the latest betas!
