### ISSUE TITLE
you are using a pure-JavaScript implementation of bcrypt

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor#10398]
Running

`"bcrypt": "^3.0.3",`
METEOR@1.8.0.1

Frustrated that this error still comes up all the time. Running `meteor npm install --save bcrypt` does absolutely nothing to fix this problem.

**Comment by stolinski** [comment]
Whatever the solution for this is, should be in the error message. I'd be happy to make the PR myself if someone can figure out why this error won't go away.

**Comment by klaussner** [comment]
Can you reproduce this with a new Meteor project? I tried the following (with Meteor 1.8.0.1 on macOS) and didn't get the warning:

```
meteor create --bare bcrypt-test
cd bcrypt-test
meteor add accounts-password
meteor npm i bcrypt
meteor
```

**Comment by CaptainN** [comment]
Make sure you have the [https://github.com/nodejs/node-gyp#on-unix](node-gyp build tools) installed and try installing bcrypt again.

bcrypt needs to build a binary, and the tools needed to do that are not installed on systems by default - installation on Linux, macOS and Windows are all different.

**Comment by stolinski** [comment]
It's just odd that this issue will go away for months, come back randomly and then not go away when I have installed bcrypt in the method the error says to do.  If installing node-gyp is the solution, I feel like that should be added to the error message.

**Comment by CaptainN** [comment]
I think the idea is that the bcrypt module itself has this documented, but I agree it would be handy if that message at least warned you about it. I had some interns on Windows and Ubuntu who were completely baffled by this, and I never noticed it since on macOS, I always shave X Code installed. The solution is easy enough once you find it, but not at all obvious.

**Comment by stolinski** [comment]
I am also MacOS with Xcode installed.

**Comment by alanionita** [comment]
This is still an issue with Meteor v1.8.1 and bcrypt v3.0.8. 

Even with node-gyp installed.
