### ISSUE TITLE
iPad Mini Chrome 63 legacy browser

### ISSUE THREAD

**Issue by rcsandell** [meteor/meteor#10395]
Chrome 63 produces white screen on iPad Mini. There is no console access making it difficult to debug.

The page works when using "Request Desktop site". According to Chrome devs only the UA string changes.

Request Mobile site UA identifies as Chrome 63.0.3239.73, WebKit 601.1:
`Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/13G36 Safari/601.1.46`

Request Desktop site UA identifies as Safari 8.0.7, WebKit 600.7.12:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.121`

The browser works fine with any test project version pre 1.7
`meteor create test --release 1.4 #works`
`meteor create test --release 1.5 #works`
`meteor create test --release 1.6 #works`
`meteor create test --release 1.7 #broken`
`meteor create test --release 1.8 #broken`

Note [https://docs.meteor.com/changelog.html#changes-6](https://docs.meteor.com/changelog.html#changes-6) the `setMinimumBrowserVersions` was introduced.

To patch add the following code somewhere on your server:
```javascript
import { setMinimumBrowserVersions } from "meteor/modern-browsers";
setMinimumBrowserVersions({
    chrome: 65, // Fixes Chrome 63 on iPad iOS 9.3.5
}, module.id);
```
**This patch does not fix the problem because it is only known to resolve for Chrome 63 on my legacy A1432 device running iOS 9.3.5 the maximum supported version. Chrome 66, 67, etc may be broken on other devices.**

**Comment by benjamn** [comment]
Can you try using [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) to catch the exception and perhaps `alert(message)`, so at least we can see what the problem is? You'll need to register the handler before the error occurs, so you might want to put it in a `<script>` tag in the `<head>` section one of your `.html` template files.

**Comment by rcsandell** [comment]
Okay, so I tried `window.onerror`, although that's not much use because now I realised it works fine again without the `setMinimumBrowserVersions`.

I didn't update any version of meteor or any packages, so Google must have updated something on Chrome.

**Comment by rcsandell** [comment]
Same issue resurfaced, had to re-implement fix given above.
