### ISSUE TITLE
Migrated from Meteor 1.2 to Meteor 1.8 resulted in extremely slow performance

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#10390]
I just migrated my application from **Meteor 1.2 (Angularjs)** to **Meteor 1.8** (Angularjs).

My application is **extremely slow**, I am fetching 20 records per page, and it loads like half of the records and then it gets stuck.
After that I have to kill my application, and relaunch, it works fine for 5 or 10m minutes max and gets slower again.
There is no error on the server terminal or browser console, what could be the issue here?
**Is there any way to debug this?** So that I can know if there is some issue with my queries or code that is causing this issue after migration?
For the record I am still using **Angular 1 on client**, since I have a huge web application.

**Comment by alanning** [comment]
Have you tried using Chrome's [performance tools](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/) to debug?  Should help identify which part of the code is causing the slowdown on the client-side.  Also check memory usage.  In my experience, slowdown after ~5 mins indicates a resource leak.

**Comment by MartiniHenry1988** [comment]
@alanning  Thanks for the reply! I have check my task manager and the node is taking 105% of cpu usage. I want to add one thing here that I am still using the older version of nodejs on my system.
Here is my system nodejs version:
```
nodejs -v
v0.10.25
```
Since I am using Meteor 1.8, could this older version of nodejs be causing issue?

**Comment by evolross** [comment]
Did you jump from 1.2. to 1.8? If so, it might be a good move to start your upgrade from 1.2 over again and go version by version testing for the issue.  Then you can isolate it to a particular version upgrade.

**Comment by MartiniHenry1988** [comment]
@evolross Sure I can try that, but actually I want to have complete control on my application, for example: I want see which part of code or query or any subscription is taking long or making my server heavier etc. Because my server goes 100%+ of CPU usage and at that time none of my mobile apps or web app works. I am assuming there is some piece of code which is causing this down time. I want to debug that. I use to work with PHP & MYSQL and there I used slow query logging to debug and that really helped me, but with Meteor, I am totally blind.

**Comment by evolross** [comment]
Meteor APM can show you slow queries. Also your MongoDB can also show slow queries as well and suggest indexes.  Plenty of info on Google about both of these.

**Comment by alanning** [comment]
You can also use regular Node.js tools that use the Inspector Protocol to help debug server-side code:
https://nodejs.org/en/docs/guides/debugging-getting-started/

The syntax to start Meteor server in 'inspect' mode is: 
`$ meteor run --inspect` 
...or 
`$ meteor run --inspect-brk`
