### ISSUE TITLE
"It looks like you are trying to access MongoDB over HTTP on the native driver port."

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10396]
I was building a Meteor package and created a simple helper app (Meteor version 1.6.1.4) to run the package with while developing.

Suddenly I get this on the browser after a rebuild (approx. 500th rebuild in a row)

```
It looks like you are trying to access MongoDB over HTTP on the native driver port.
```

And that's it. No errors in the console, browser & meteor tool.

I have `MONGO_URL` set in my env vars, so I wasn't using the bundled MongoDB.

Killing and restarting `meteor` solved the issue, but I thought I'd bring this up just in case.

**Comment by cjbrunnen** [comment]
I'm getting this sudden error too - meteor version 1.9.2

**Comment by Muhannad-issa** [comment]
I am using version 4.0.6 ( the current release) on Linux Mint. I installed Mongodb Compass(mongodb GUI) and I am able to interact with my databases. Here is the link: https://docs.mongodb.com/compass/master/install/

I hope this solves your problem.

**Comment by hamed6** [comment]
I installed compass and still getting same error, not able to use 27017 over http.

**Comment by Jimmea** [comment]
You may start mongodb with
    mongod --httpinterface
And then access 
http://localhost:28017/

Version 3.6. Its disable http

**Comment by cnscorpions** [comment]
@Jimmea Hi, it does not work for me. 
after exec `mongod --httpinterface` in my docker container,
it prints 'Error parsing command line: unrecognized option ...'

**Comment by surya-abs** [comment]
> You may start mongodb with mongod --httpinterface And then access http://localhost:28017/
> 
> Version 3.6. Its disable http
> 
> https://docs.mongodb.com/manual/release-notes/3.6-compatibility/index.html#http-interface-and-rest-api

thanks mate.. solved my issue. Now accessing using mongocompass.. working fine

**Comment by quangtuma** [comment]
> surya

How to use mongo working fine? Are you install Version 3.2? 
Thanks

**Comment by quangtuma** [comment]
> > You may start mongodb with mongod --httpinterface And then access http://localhost:28017/
> > Version 3.6. Its disable http
> > https://docs.mongodb.com/manual/release-notes/3.6-compatibility/index.html#http-interface-and-rest-api
> 
> thanks mate.. solved my issue. Now accessing using mongocompass.. working fine

How to use mongo working fine? Are you install Version 3.2?
Thanks
