### ISSUE TITLE
window10 install error

### ISSUE THREAD

**Issue by yueleiMaster** [meteor/meteor#10400]
I have been giving an error of choco install meteor.What happened in window10
![image](https://user-images.githubusercontent.com/25242674/50622430-fd672200-0f47-11e9-9415-2431d475c7cb.png)
Please help me

**Comment by CoppensEwen** [comment]
You run the command "choco install meteor." with a dot after "meteor", try to run the command "choco install meteor" without the dot

**Comment by CaptainN** [comment]
Disable Windows Defender while this is installing, keep an eye on the blinking cursor - when it stops, press enter. It was incredibly challenging to get Meteor installed on my Windows machine, but it eventually goes. Also, consider running Meteor in a VM instead, as it'll be much much faster.

**Comment by benjamn** [comment]
I'm going to close this because the `meteor.` issue flagged by @CoppensEwen above seems like the most immediate problem. Please open a new issue if you encounter other problems after typing `choco install meteor` (no `.`).
