### ISSUE TITLE
Tutorial broken!!!!

### ISSUE THREAD

**Issue by elDudarino** [meteor/meteor#10401]
Guys the OFFICIAL main tutorial for meteor and react (https://www.meteor.com/tutorials/react/components) on your site is broken..

Only works IF:
meteor remove blaze-html-templates
meteor add static-html

https://github.com/meteor/simple-todos-react/issues/71

Very frustrating for a brand new user when the intro tut doesn't work and you have no clue. Please update so others don't suffer like I did.

**Comment by benjamn** [comment]
The fixed content isn't live yet, but please refer to this comment for instructions about how you can review the new version of the tutorial, if you have time: https://github.com/meteor/simple-todos-react/issues/71#issuecomment-451710776
