### ISSUE TITLE
minimongo query order issue

### ISSUE THREAD

**Issue by haojia321** [meteor/meteor#10417]
Assume we have below code to query User collection.
var idList = ['A', 'B', 'C'];
var users = User.find({_id: {$in: idList}});

The issue is the users order is not sorted based on idList.
It is supposed to return users as 
[{_id: 'A'}, {_id: 'B'}, {_id: 'C'}]
But it returns the user object in random order.

If it is as expected behavior, is there simple anyway to achieve what i need please?

**Comment by haojia321** [comment]
I think Minimongo doesnt support aggregate or pipeline.

**Comment by Torgen** [comment]
I created a feature request to do a series of lookups for `_id: {$in: list}` instead of a collection scan:
https://github.com/meteor/meteor-feature-requests/issues/343
In my case it was for efficiency, though getting a consistent output order was a plus. Perhaps mark this as a dupe of that?
