### ISSUE TITLE
[1.8+] cannot import ipfs-http-client package

### ISSUE THREAD

**Issue by yuwiggin** [meteor/meteor#10411]
1. install ipfs-http-client package 
>meteor npm i ipfs-http-client --save

2. add ipfs.js file with the following

```
const ipfsClient = require('ipfs-http-client')
const ipfs = ipfsClient('localhost', '5001', { protocol: 'http' })
```
or 

```
import ipfsClient from 'ipfs-http-client'
const ipfs = ipfsClient('localhost', '5001', { protocol: 'http' })
```

3. run Meteor
>meteor

4. open browser, http://localhost:3000

An error occured in the browser's console
```
Uncaught TypeError: ipfsClient is not a function at ipfs.js
```
###test environment:
Meteor Version: Meteor 1.8.0, 1.8.0.2,  
OS: macOS Sierra V10.12.6,  
ipfs-http-client: 28.1.1,  

What's wrong?

**Comment by alanshaw** [comment]
resolved in https://github.com/ipfs/js-ipfs-http-client/pull/931

**Comment by filipenevola** [comment]
I'm considering this resolved because of the comment above.
