### ISSUE TITLE
[1.8] build performance is good, trying to make it awesome

### ISSUE THREAD

**Issue by yorrd** [meteor/meteor#10412]
I've done a quick rebuild analysis because I'm trying to optimize build times for typescript projects with a [fork of the `barbatus:typescript` plugin](https://atmospherejs.com/adornis/typescript). After bringing compile time down by quite a bit, I noticed that a lot of the time between `ctrl+s` and page reload is actually not due to the compilation. So I used `qualia:profile` to analyze what's happening in my average client rebuild and here's what I found. Out of the 11 seconds all in all until the profile finishes, 

- only ~6 seconds are actually compiling typescript (usually the whole end-to-end recompilation is only about 8 seconds with that change, probably profiling overhead). I got this from the flame chart.
- garbage collection takes almost 3 seconds. I'm aware of [this commit](https://github.com/meteor/meteor/commit/5c1ba3a85ec17141f02c61cea03044596c9b4a78) where the old-space-size was increased to avoid churn, would it help to even increase this number on systems with sufficient RAM? I'm don't know how to do it, because `NODE_OPTIONS` seems to only apply to the server process.

[CPU of the client rebuild profile](https://github.com/meteor/meteor/files/2744458/client-rebuild.cpuprofile.zip)

---

I'm wasn't sure how the overhead of profiling behaves exactly. When we run the project normally, the compiler tells me it needs less than a second for the same client recompilation, so the other 7 or so seconds would be Meteor, garbage collection (?) and browser response. For this reason, I've done a `METEOR_PROFILE=100` as well to compare numbers:

```
| Rebuild App...................................................4,607 ms (1)
| └─ bundler.bundle.............................................4,607 ms (1)
|    └─ files.withCache.........................................4,607 ms (1)
|       ├─ compiler.compile(the app)............................2,980 ms (1)
|       │  └─ files.withCache...................................2,980 ms (4)
|       │     └─ compileUnibuild (the app)......................2,979 ms (4)
|       │        ├─ PackageSource#_findSources....................300 ms (4)
|       │        │  └─ files.withCache............................298 ms (4)
|       │        │     ├─ files.realpath                           40 ms (670)
|       │        │     ├─ files.readdir                            40 ms (1340)
|       │        │     ├─ files.stat                               13 ms (1521)
|       │        │     └─ other files.withCache                   206 ms
|       │        ├─ files.readFile                                748 ms (490)
|       │        ├─ sha1                                          473 ms (490)
|       │        ├─ optimistic readFile                            38 ms (11049)
|       │        ├─ optimistic hashOrNull                          26 ms (11049)
|       │        └─ other compileUnibuild (the app)             1,388 ms
|       ├─ bundler.bundle..makeClientTarget.....................1,444 ms (1)
|       │  └─ Target#make.......................................1,444 ms (1)
|       │     ├─ Target#_runCompilerPlugins.......................379 ms (1)
|       │     │  ├─ plugin static-html                             12 ms (1)
|       │     │  ├─ plugin adornis:typescript                     334 ms (1)
|       │     │  └─ other Target#_runCompilerPlugins               14 ms
|       │     ├─ Target#_emitResources..........................1,007 ms (1)
|       │     │  └─ PackageSourceBatch.computeJsOutputFilesMap....995 ms (1)
|       │     │     ├─ ImportScanner#_getAbsModuleId               24 ms (1373)
|       │     │     ├─ ImportScanner#_realPath.....................95 ms (1165)
|       │     │     │  ├─ optimistic lstatOrNull...................47 ms (4570)
|       │     │     │  │  ├─ optimistic lstat......................14 ms (208)
|       │     │     │  │  │  └─ files.lstat                        12 ms (208)
|       │     │     │  │  └─ other optimistic lstatOrNull          23 ms
|       │     │     │  ├─ files.realpath                           21 ms (434)
|       │     │     │  └─ other ImportScanner#_realPath            27 ms
|       │     │     ├─ ImportScanner#scanImports for the app......183 ms (1)
|       │     │     │  ├─ ImportScanner#_resolve                   30 ms (1881)
|       │     │     │  ├─ ImportScanner#_realPath                  17 ms (410)
|       │     │     │  ├─ Babel.compile                            19 ms (130)
|       │     │     │  └─ other ImportScanner#scanImports for the app 98 ms
|       │     │     ├─ ImportScanner#scanMissingModules for jagi:astronomy.569 ms (1)
|       │     │     │  ├─ ImportScanner#_resolve                   76 ms (1221)
|       │     │     │  ├─ optimistic statOrNull                    19 ms (2232)
|       │     │     │  ├─ Babel.compile                            68 ms (224)
|       │     │     │  ├─ ImportScanner#_findImportedModuleIdentifiers 22 ms (477)
|       │     │     │  ├─ ImportScanner#_getAbsModuleId            46 ms (253)
|       │     │     │  ├─ ImportScanner#_realPath                  41 ms (253)
|       │     │     │  ├─ ImportScanner#_readFile..................57 ms (253)
|       │     │     │  │  ├─ optimistic hashOrNull                 21 ms (253)
|       │     │     │  │  └─ other ImportScanner#_readFile         31 ms
|       │     │     │  └─ other ImportScanner#scanMissingModules for jagi:astronomy 240 ms
|       │     │     └─ other PackageSourceBatch.computeJsOutputFilesMap 56 ms
|       │     ├─ Target#minifyJs                                   42 ms (1)
|       │     └─ sha512                                            10 ms (75)
|       └─ bundler writeTargetToPath..............................178 ms (1)
|          └─ ClientTarget#write..................................178 ms (1)
|             ├─ sha512                                            82 ms (141)
|             ├─ bundler writeFile                                 55 ms (216)
|             └─ other ClientTarget#write                          32 ms
|
| Top leaves:
| other compileUnibuild (the app)..........................1,388 ms (4)
| files.readFile.............................................748 ms (491)
| sha1.......................................................492 ms (2421)
| plugin adornis:typescript..................................334 ms (1)
| other ImportScanner#scanMissingModules for jagi:astronomy..240 ms (1)
| other files.withCache......................................209 ms (9)
| sha512.....................................................102 ms (291)
|
| (#7) Total: 4,607 ms (Rebuild App)
```

(ignore the `[COMPILER]` output, that's my debugging output) And it seems confirmed that the actual compilation is negligible compared to the 4.7 second rebuild time (+browser reloading). Am I misinterpreting? I'm trying to wrap my head around the isobuild system, don't have a good enough overview to really interpret those results and draw a conclusion where an optimization can be attempted yet. For example, there is a (4) behind the unibuild compilation. Does that mean we could just remove three of them and get 1-2 second rebuilds? probably not :stuck_out_tongue: Could the output file map not be cached even further if I'm just changing a leaf of the import hierarchy with my rebuild? Does the building (apart from TS compilation) scale linearly with the number of files we have? (there are roughly 450 .ts files in the project, half of which are linked node_modules). 

---

Side note / motivation: People seem to be of the opinion that 10 second rebuilds are fine just because there's worse. I don't think so, if we can do a better job. It's fine that I need to put in the time myself, but I'm certain that our team would get a lot out of rebuilds that take 1-2 seconds - and every millisecond that gets us there. We do certain work live with our customers, 10 seconds of waiting for a button to become green is just unbearable, it breaks the conversation. 

That's why I'll do everything to help improve the situation, I just need some pointers every now and then, for example [about how to get started with an HMR compiler](https://github.com/meteor/meteor-feature-requests/issues/285#issuecomment-452760531). I would love your input. HMR will help us get rid of the 1-2 seconds which are required just for the browser to reload the page.

**Comment by KoenLav** [comment]
Have you seen this: https://github.com/meteor/meteor/pull/10399

**Comment by yorrd** [comment]
@KoenLav I have and I have been in contact with @zodern . I'm testing on Linux, so I'm excited how much impact this has since it's tested on Windows. 

I have promised but yet to test the pull request. Will do so in the coming days and report back in 10399.

Thanks for the hint!
