### ISSUE TITLE
[METEOR@1.8.1-beta.15] Dev server frequently dies because of error (meteor-promise)

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10423]
Have been editing some CSS for a few hours, causing very frequent reloads. Almost every three or four times it reloads, it dies because I am editing a file and save while there is some error, instead of waiting to let me fix it. And the error message is also quite unhelpful.

```js
/Users/stian/.meteor/packages/coffeescript/.1.0.17.ztkmml.8voq++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
[object Object]
```

I'm stuck looking at my web page loading indicator, until I finally go to check the console and see that the process has died. Of course, starting from scratch takes much longer than reloading, so this in total slows down the process quite a lot.

Also strange that it's from a coffee script compiler, since there is no coffee script in our code.

**Comment by ArthurGerbelot** [comment]
Having the same issue with 1.8.1, do we have update on this ?

**Comment by geedmo** [comment]
In my case, I had copy/pasted a SASS import with tilde (~) and after realize that it was not supported, changed to a relative path and everything worked fine again.
I came to that after seen this post, https://stackoverflow.com/a/53383429
