### ISSUE TITLE
Oplog Tailing doesn't handle missing `ts` in transaction operations in applyOps

### ISSUE THREAD

**Issue by chrisbobbe** [meteor/meteor#10420]
Meteor version 1.8.0.1
Mongo package version 1.6.0 (https://atmospherejs.com/meteor/mongo)
MongoDB version 4.0.4

Oplog tailing doesn't completely handle the missing `ts` field on objects in the applyOps array of an oplog entry corresponding to a transaction. It can be solved by getting the `ts` field from the oplog entry itself, not from these individual objects.

Here is the stack trace for the error. When it says "Cannot read property 'toString' of undefined," the "undefined" refers to the `ts` field. The error occurs when a cursor returned by a Meteor publication includes documents that get updated inside a successful transaction after the publication is subscribed to. **The updates are never sent to the client, so the UI can't live-update.**

```
 Error in oplog callback TypeError: Cannot read property 'toString' of undefined
     at packages/mongo/oplog_observe_driver.js:575:5
     at Object.Meteor._noYieldsAllowed (packages/meteor.js:848:12)
     at OplogObserveDriver._handleOplogEntrySteadyOrFetching (packages/mongo/oplog_observe_driver.js:583:9)
     at packages/mongo/oplog_observe_driver.js:137:3
     at packages/mongo/oplog_observe_driver.js:12:1
     at Object.Meteor._noYieldsAllowed (packages/meteor.js:848:12)
     at packages/mongo/oplog_observe_driver.js:122:13
     at packages/mongo/oplog_tailing.js:105:7
     at runWithEnvironment (packages/meteor.js:1356:24)
     at Object.callback (packages/meteor.js:1369:14)
     at packages/ddp-server/crossbar.js:114:36
     at Array.forEach (<anonymous>)
     at Function._.each._.forEach (packages/underscore.js:139:11)
     at DDPServer._Crossbar.fire (packages/ddp-server/crossbar.js:112:7)
     at handleDoc (packages/mongo/oplog_tailing.js:318:11)
     at Array.forEach (<anonymous>)
```

We tested adding a few lines to fix this, and the error went away:

```javascript
    if (doc.ns === "admin.$cmd") {
          if (doc.o.applyOps) {
            // This was a successful transaction, so we need to apply the
            // operations that were involved.

            // We added this map function, which resolved the issue:
            doc.o.applyOps.map(function (op) {
                if (!op.ts) {
                    console.log('applying parent ts')
                    op.ts = doc.ts;
                }
                return op;
            }).forEach(handleDoc);
            return;
          }

          throw new Error("Unknown command " + EJSON.stringify(doc));
        }
```

Please see my comment on this pull request: https://github.com/meteor/meteor/pull/10201#discussion_r247592153

Thanks very much!

**Comment by benjamn** [comment]
Simplifying that loop a bit:
```js
doc.o.applyOps.forEach(op => {
  op.ts = op.ts || doc.ts;
  handleDoc(op);
});
```
@chrisbobbe Do you have a reliable test case for this problem that we could use as a regression test?

**Comment by chrisbobbe** [comment]
Sure! I'm not sure how to write a robust test case to be added directly to Meteor, but maybe you could provide some guidance on that? Or else you might find everything you need in this repository with a reproduction: https://github.com/chrisbobbe/issue-10420-reproduction.

I've set up a Meteor method you can call from the dev tools console that triggers the error as long as oplog tailing is properly set up locally with replica sets. For some reason (as noted in the repo), in this example, the error only gets triggered every _other_ time you call the method.

Let me know if I can be more helpful or clarify anything for you. Thank you!

**Comment by chrisbobbe** [comment]
Hi @benjamn, if you can point me to an example of an existing regression test, I'd be happy to make one for this issue.

**Comment by chrisbobbe** [comment]
Hi @generalleger, The error isn’t thrown by any code responsible for performing a transaction. We observe it when subscribing to a publication where the documents in the cursor returned by the publish function change (or should change, rather) as a result of a transaction. So in a simple todo app, for example, if you’re subscribed to all todos that are not marked as done, but then some todo(s) are added, changed, or removed within a transaction, in a way that is relevant to the query in the publication, these changes won’t be published to the client and you’ll start seeing this error.

So I would start by looking into which of your publications are currently subscribed to when you’re doing your transactions.

Good luck!

**Comment by generalleger** [comment]
@chrisbobbe awesome.  Thank you so much for the reply!

**Comment by benjamn** [comment]
This was released in Meteor 1.8, unless I'm mistaken. Thanks all!

**Comment by chrisbobbe** [comment]
@benjamn I don't think so; I'm not seeing the fix in the release-1.8.1 branch, it should be around line 273, I think -- https://github.com/meteor/meteor/blob/release-1.8.1/packages/mongo/oplog_tailing.js

**Comment by chrisbobbe** [comment]
@benjamn As listed at the top of the issue, the problem was first observed in Meteor 1.8, so it was definitely not fixed with the initial release of 1.8. As noted yesterday, it is also missing in 1.8.1 -- please consider reopening this issue.

**Comment by chrisbobbe** [comment]
Thank you @benjamn!!

**Comment by benjamn** [comment]
In case it wasn't clear, this fix can be obtained by running `meteor update --release 1.8.1-rc.1`.

**Comment by conorstrejcek** [comment]
While looking into a separate issue, I also noticed that this change (using `doc.ts` when `op.ts` is not defined) will cause the timestamps for some of the operations to be the same. Is it possible that this could cause issues? I did notice that `waitUntilCaughtUp` checks the `_lastProcessedTS` value to determine which operation was last processed, so if more than one operation shares the same timestamp, it could cause some operations to be skipped.

**Comment by benjamn** [comment]
@conorstrejcek I'm afraid you were right that this could be a problem. b0cb1ceda3dbe7e1b505d0017f2ccc50d6eb7c40 is my first attempt to solve this problem, but I'm honestly not sure it's a good idea to be using `Timestamp`s as keys, given the likelihood of a collision.
