### ISSUE TITLE
Meteor 1.8 server is going down randomly

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#10424]
I am using Meteor 1.8 on Ubuntu 15.

My server goes down randomly after sometime and I have to restart each time. After that it works fine for sometime, but it again hangs and goes down, I see the server console fine and running, but my application is totally down.

There are no errors on server console or anything.

I would really appreciate the help. My business is being effected to much.

I don’t know how can I debug this. Can you please help me with this?

**Comment by axelvaindal** [comment]
Hello @MartiniHenry1988 , can you please tell me what operating system you're running Meteor on ?
What is your appreciation of the following statement ? 

> My server goes down randomly after sometime

Days ? Hours ? Minutes ? Is there any logs on the client as well indicating a loss of connection between server and client ?
I've heard of a similar issue on W10, when the server seems to be asleep if not stimulated enough during a long period of time, but I've never noticed this myself on Linux and never tried to reproduce it as well.
Is that what you're experiencing ?

**Comment by axelvaindal** [comment]
Clearly seems like the same issue my mate had on W10, so perhaps it's not operating system related.
This being said, it's hard to reproduce, so do you think you would be able to create a minimal app I could clone to see if have the same issue on my machine ?
For example, have you tried running the todo example or something similar for a long time and experienced the issue ?

**Comment by MartiniHenry1988** [comment]
@axelvaindal Actually I also have a staging server on same machine same app. Staging works fine since it doesn't have that much database records and users. The live meteor server goes down

**Comment by airstep** [comment]
Same for me. It's about fibers and out of memory - v1.8.0.2

**Comment by batcode007** [comment]
As you mentioned the server works fine on staging server, it looks like there is a memory problem and hence the server is crashing. 
Check your subscriptions, global variables and other possbilities for memory leaks.
Also it helps alot if you set an OPLOG replica set with mongodb in production (memory usage comes down to 50%).
Use htop to see which process on the server is using majority of your memory

**Comment by airstep** [comment]
The server works fine on node v8.11.2, it's got down by meteor but rare one time per week than.

**Comment by MartiniHenry1988** [comment]
@batcode007  I have doubled check all of my subscriptions. All the subscriptions provides limited data sets and fields.

**Comment by airstep** [comment]
![2019_01_27_08 08 07](https://user-images.githubusercontent.com/5022948/51797381-59515d80-220b-11e9-989b-eb71202b71ad.png)
Moment of the Out of memory

**Comment by airstep** [comment]
24h
![2019_01_27_08 16 56](https://user-images.githubusercontent.com/5022948/51797424-01ffbd00-220c-11e9-8087-ed05bac3973b.png)

**Comment by MartiniHenry1988** [comment]
@airstep How are you able yo see these resource statistics graphs? Which tool are you using for meteor performance monitoring?

**Comment by airstep** [comment]
By DigitalOcean graphs

**Comment by airstep** [comment]
Next graphs like that (node v8.11.2):
![2019_01_27_19 47 05](https://user-images.githubusercontent.com/5022948/51804656-8f72f980-226c-11e9-9505-c73004208066.png)
![2019_01_27_19 46 46](https://user-images.githubusercontent.com/5022948/51804657-8f72f980-226c-11e9-978c-d6fcf0e326c0.png)

**Comment by MartiniHenry1988** [comment]
I have noticed a strange thing, the profile photo url of a user is being requested non stop.
I have like 20 users accessing my app.

Here is the code where i write image urls:

```
Meteor.startup(function () {

  // REWRITING URL DATA
  WebApp.connectHandlers.use(function(req, res, next) {

      var re = new RegExp('^\\/uploads\\/(.*)$').exec(req.url);

      if (re !== null) {

        var filePath = process.env["PWD"] + '/../.uploads~/' + re[1];
        
        if (!fs.existsSync(filePath) || !fs.lstatSync(filePath).isFile()) {

            res.writeHead(404, {'Content-Type': 'text/plain'});
            res.write("404 Not Found\n");
            res.end();
            return;
        }

        console.log(' accessing uploads: '+re[1]);

        var data = fs.readFileSync(filePath);

        res.writeHead(200, {'Content-Type': 'image'});
        res.write(data);
        res.end();          
      }
      else { next();/* Other urls will have default behaviors*/  }
  });


});
```

I am getting too many of these console.logs and non stop. I think this is causing my server down
