### ISSUE TITLE
Change facebook oauth request's default fields to not trigger App Review

### ISSUE THREAD

**Issue by hashcutdev** [meteor/meteor#10428]
In the current facebook_server.js file, the whitelisted fields are as follows:

```
Facebook.handleAuthFromAccessToken = (accessToken, expiresAt) => {
  // include basic fields from facebook
  // https://developers.facebook.com/docs/facebook-login/permissions/
  const whitelisted = ['id', 'email', 'name', 'first_name', 'last_name',
    'middle_name', 'name_format', 'picture', 'short_name', 'age_range',
    'birthday', 'friends', 'gender', 'hometown', 'link', 'location', 'locale'];
```
However, according to facebook's docs at https://developers.facebook.com/docs/facebook-login/permissions/

Most of these fields now require an app to be reviewed before being granted. Indeed, it seems the only fields that *don't* require App Review are:
- id
- email
- name
- first_name
- last_name
- middle_name
- name_format
- picture
- short_name

FB doesn't specify the locale field, so I'm not sure if it triggers App Review as well.

These fields can be gotten by specifying the default and email scopes. It seems that requiring any other scopes automatically triggers an app review.

I got bitten by this. I'm currently using the accounts system with accounts-ui, and a default setup, which worked fine until sometime last year when apparently FB changed their permissions, kicking my app into review. I couldn't figure out why I was all of a sudden getting FB OAuth errors until I went into FB's developer's dashboard and realized they disabled my app until the review is completed.

Can we change the default fields requested from FB so that the default won't trigger app review? And then perhaps some documentation about how to specify additional permissions to request if someone actually needs the other fields? Barring that, is there a way to manually specify which permissions are being requested?

Otherwise it appears the default configuration as it stands will end up triggering an app review on anyone who creates a new application with it.

**Comment by StorytellerCZ** [comment]
When I was adjusting those fields I left the old fields there for backward compatibility (for apps that use the older API). Though with the changes that you have pointed out it is time to get rid of it. I'll prepare a PR.

**Comment by hashcutdev** [comment]
Does removing those fields from the whitelist automatically prevent them from being requested from facebook? I just want to make sure that the actual OAuth request submitted to fb doesn't request any permissions besides default and email.

**Comment by StorytellerCZ** [comment]
Should be the case for the default ones that don't require review.
