### ISSUE TITLE
App requires re-submission to playstore every time some change is being made 

### ISSUE THREAD

**Issue by sourcerer52** [meteor/meteor#10437]
Hi,

Since last few days, Cordova app is failing to push new changes to the application. The problem is mainly with charts as charts fail to load after the change. And the problem seems to disappear on resubmitting the app. 

I'm using ChartJs
Meteor version is 1.7.0.4

Problem is for Android. On iOS, this is not the problem

**Comment by rj-david** [comment]
Relevant issue: https://github.com/meteor/meteor/issues/10277

**Comment by aishwaryasharma96** [comment]
hi, @rj-david. I see the issue #10277 is for iOS. interestingly in my case, it works on iOS. Is anyone else facing the issue with hot code push on android as well? What can be the workaround on this?

**Comment by rj-david** [comment]
If you check the entire discussion, it evolves to HCP in general. The fix is in 1.8.1-beta.14

For some, the solution is not to use the public folder
