### ISSUE TITLE
meteor deploy finishes too early with 'Unhealthy Container Replacement' disabled in Galaxy

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#10431]
Here is the help text for `--deploy-polling-timeout` on `meteor deploy`:
```
  --deploy-polling-timeout  The number of milliseconds to wait for build/deploy
                  success or failure after a successful upload of your app's
                  minified code; defaults to 15 minutes.
```

The 'deploy' part of this appears to be a disconnect with the actual behavior of the option.

### Expected behavior

Since we only run this command inside a CI/CD script, we want the success/failure of the CI/CD to match the success/failure of the deployment to Galaxy. With a setup of three containers, it is taking around 25 minutes to build and deploy - longer than the 15 minute polling default.

When we extend the timeout with `--deploy-polling-timeout` we expect that the script will continue polling through both build and deployment, so that we can verify that the deployment was successful via CI/CD.

### Observed behavior

`meteor deploy` (with no options) will upload the app's code and continue polling until build and deployment finishes or the 15 minute time limit expires.

Here is the output from the deployment step of our CI/CD script without `--deploy-polling-timeout`:

![screen shot 2019-01-24 at 8 48 09 am](https://user-images.githubusercontent.com/15968012/51655171-d931ba80-1fb4-11e9-9fa6-4a0666d5f1ad.png)

`meteor deploy --deploy-polling-timeout` will upload the app's code and continue polling until build (**but not deployment**) finishes or the specified time limit expires.

Here is the output from the deployment step of our CI/CD script with `--deploy-polling-timeout`:

![screen shot 2019-01-24 at 8 46 59 am](https://user-images.githubusercontent.com/15968012/51655124-a1c30e00-1fb4-11e9-9b25-33e6460467b6.png)

**Comment by jamesmillerburgess** [comment]
After testing this more thoroughly from a checkout, it turns out this had nothing to do with the polling timeout and instead is caused by a setting on Galaxy apps.

With 'Unhealthy Container Replacement' enabled, the polling response from Galaxy will only show `isFinished: true` after all containers have been deployed.

With 'Unhealthy Container Replacement' disabled, the polling response from Galaxy will show `isFinished: true` as soon as the app image has finished building, and not wait for any containers to deploy. So on an app with multiple containers, it will be 'finished' before any of the old version containers are replaced.

The relevant help text next to this option reads:

> * Galaxy will wait at least 10 minutes (longer for apps with many containers) for all containers of a newly deployed app version to become healthy before declaring the deploy a success, and will return to the previous active version on failure.

This doesn't make clear what should happen when the feature is disabled, but I think the current behavior is confusing. I get a success message that my app has been upgraded, but if I go visit my app, it will still be the old version for some period of time.

**Comment by glasser** [comment]
This feature is working as intended and as documented.  Turning off the "unhealthy container replacement" option is intended for apps which aren't really end-user-serving webapps (eg a worker node or something).  It effectively means "don't assume health checks really mean anything". We still avoid serving traffic to containers in that mode that are unhealthy, but we don't kill the containers, and we don't wait for them to be healthy after deploys.
