### ISSUE TITLE
[1.8.1-beta.16] Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#10440]
I'm getting the following error when building my project:
```
W20190201-09:13:13.431(5.5)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20190201-09:13:13.431(5.5)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20190201-09:13:13.432(5.5)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20190201-09:13:13.432(5.5)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20190201-09:13:13.432(5.5)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20190201-09:13:13.432(5.5)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
```

This error starts happening from 1.8.1-beta.3, in which the autoupdate, ddp-server and reactive-dict packages got updated.

It looks like the error is being thrown here in meteorx: https://github.com/meteorhacks/meteorx/blob/master/lib/livedata.js

And I think it is failing to find the constructor for something in autoupdate, which looks related to the changes here: https://github.com/meteor/meteor/pull/10248/commits/13308cf3417e7a0ec23b825f2fcc197ba228686d

I realize that meteorx is a third party package, but I'm pretty sure the only reason it is in my project is as a dependency of meteor-apm-agent, which is maintained by MDG. So I thought it was fair to post it here.

**Comment by jamesmillerburgess** [comment]
Ok I figured out there is a newer version of meteor-apm-agent that eliminates the dependency on meteorx and this is building successfully.

**Comment by sferoze** [comment]
@jamesmillerburgess  how are you feeling about the newest beta (beta 16) for 1.8.1? I am holding off from updating production until final release is out, but are we close? Is it pretty stable overall?

**Comment by jamesmillerburgess** [comment]
Our team hasn’t started using it yet due to the error mentioned in this issue.

We will start testing it tomorrow both in dev and from a Galaxy deployment.

**Comment by hounaine** [comment]
Any new test about that error... meteorhacks:meteorx ?

**Comment by lamhieu-vk** [comment]
Use `lamhieu:meteorx` instead of `meteorhacks:meteorx`, read more at [here](https://github.com/lamhieu-vk/meteorx)
