### ISSUE TITLE
meteor command Segmentation Fault on MacOs

### ISSUE THREAD

**Issue by gflores** [meteor/meteor#10450]
On my macbook pro the command `meteor` immediately gives me "Segmentation fault: 11" right after a clean install.

To reproduce I simply do:
`$> curl https:/install.meteor.com/ | sh`
`$> meteor`
`Segmentation fault: 11`

I'm running on macOS High Sierra.

Anyone else getting this issue on mac ?
On Ubuntu it works just fine

**Comment by aliogaili** [comment]
I just tried re-installing meteor on my machine (macOS High Sierrra) and it seems fine..

**Comment by wpdeema** [comment]
@aliogaili it does not help :(

**Comment by aliogaili** [comment]
I've never really ran into this issue, I tried to reproduce it on my macOS with no luck :(

**Comment by wpdeema** [comment]
My problem was the [Cylance](https://www.cylance.com). So issue is gone after uninstalling it.

**Comment by gflores** [comment]
Hi still no update ?
