### ISSUE TITLE
Error: Cannot find module 'stream' (fixed by using Yarn instead of npm)

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#10451]
Vulcan users have been reporting a `Error: Cannot find module 'stream'` error when trying to run the [Vulcan Starter repo](https://github.com/VulcanJS/Vulcan-Starter/) with `npm install` and then `npm start`. 

The weird part is that the error goes away if you do `yarn` instead of `npm install`. For that reason it's hard to know if this is an issue with Meteor or with npm itself (and I've also [posted this](https://npm.community/t/meteor-apps-crashes-when-initialized-with-npm-error-cannot-find-module-stream-but-works-with-yarn/5355) to the npm forums). Still, I thought I'd report it in case anybody knows what's going on. 

Also note that this has happened for multiple users cloning this repo including myself, but does not happen for other Meteor apps.

**Comment by SachaG** [comment]
Oh and this is with Meteor 1.8.0.2

**Comment by arggh** [comment]
Possibly related: https://github.com/meteor/meteor/issues/9791

**Comment by vale981** [comment]
browserify may be the issue...
