### ISSUE TITLE
[1.8] Error using gsap npm package during page load

### ISSUE THREAD

**Issue by nabiltntn** [meteor/meteor#10457]
Hi,

I am trying to use `gsap` npm package for client side animations. The recommended way to import modules is :
```
import { TweenMax, CSSPlugin } from 'gsap/all';
```
but i am getting errors during page load due to `Uncaught SyntaxError: Unexpected identifier`.

The error is because of `import` syntax inside meteor's `modules.js` . it looks like gsap modules are not transpiled.

Gsap package uses `browser` syntax inside package.json and esm modules
https://github.com/greensock/GreenSock-JS/blob/master/package.json

I have tried the same package with a project using `Parcel` bundler for example and it's working fine.

I created a simple repo for reproduction
https://github.com/nabiltntn/import-package-repro

**Comment by coagmano** [comment]
Just use
```
import { TweenMax, CSSPlugin } from 'gsap';
```
instead, and it will use the pre-compiled version that GSAP ship

----
Or you can force Meteor to compile the package by making it look like it's part of your app code. 
Here's the instructions from [1.7's changelog](https://github.com/meteor/meteor/blob/devel/History.md#v17-2018-05-28):

> Although Meteor does not recompile packages installed in node_modules by default, compilation of specific npm packages (for example, to support older browsers that the package author neglected) can now be enabled in one of two ways:
> 
> - Clone the package repository into your application's imports directory, make any modifications necessary, then use npm install to link the-package into node_modules:
> 
>     meteor npm install imports/the-package
> 
>   Meteor will compile the contents of the package exposed via imports/the-package, and this compiled code will be used when you import the-package in any of the usual ways:
> 
>     import stuff from "the-package"
>     require("the-package") === require("/imports/the-package")
>     import("the-package").then(...)
> 
>   This reuse of compiled code is the critical new feature that was added in Meteor 1.7.
> 
> - Install the package normally with meteor npm install the-package, then create a symbolic link to the installed package elsewhere in your application, outside of node_modules:
> 
>     meteor npm install the-package
>     cd imports
>     ln -s ../node_modules/the-package .
> 
>   Again, Meteor will compile the contents of the package because they are exposed outside of node_modules, and the compiled code will be used whenever the-package is imported from node_modules.
> 
>   > Note: this technique also works if you create symbolic links to individual files, rather than linking the entire package directory.
> 
> In both cases, Meteor will compile the exposed code as if it was part of your application, using whatever compiler plugins you have installed. You can influence this compilation using .babelrc files or any other techniques you would normally use to configure compilation of application code. PR #9771 Feature #6
> 
> ~~Note: since compilation of npm packages can now be enabled using the techniques described above, Meteor will no longer automatically scan node_modules directories for modules that can be compiled by compiler plugins. If you have been using that functionality to import compiled-to-JS modules from node_modules, you should start using the symlinking strategy instead.~~ Follow-up note: this optimization was reverted in Meteor 1.7.0.1 (see above).

**Comment by nabiltntn** [comment]
I have tried to import from 'gsap', but it's not exporting the PixiPlugin that i am using too.

thanks @coagmano for the reference to the chnagelog, i was not aware of symbolic link solution to force module compilation.

I fixed it by importing from the umd folder that contains compiled files for ES5 ( as mentionned in their documentation )
```
import { PixiPlugin } from "gsap/umd/PixiPlugin"; 
```
