### ISSUE TITLE
EventEmitter.prototype.prependListener does not exist

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10463]
Meteor's node stub for for events is outdated with regards to the current Meteor node API version (8.x.x).

This can result in errors on the client-side with functions like `prependListener` not existing.

PR: https://github.com/meteor/node-stubs/pull/17

**Comment by klaussner** [comment]
I think this has been resolved (https://github.com/meteor/node-stubs/pull/17#issuecomment-499074828, https://github.com/meteor/node-stubs/commit/4d70f1938a9b2c10eebcda86702f626d0a53603d).
