### ISSUE TITLE
Win 10 Range Error: Maxium call stack size on project creation

### ISSUE THREAD

**Issue by petercr** [meteor/meteor#10466]
# Keep getting Maximum call stack size exceeded on Windows 10 builds

I tried installing Meteor v. 1.8.0.2 via Chocolatey and using the Windows .msi installer.
While both of the processes said they were completed without any problems, whenever I go to create a new Meteor project I keep getting a `RangeError: Maximum call stack size exceeded`

I fully uninstalled each version before installing the new one. 
I'm using Windows 10 Home Build 1803
Also running Node v. 11.10.0 and NPM v. 6.7.0

Here is the exact error I'm getting when both creating a new project or trying to start a project.
```bash
$ C:\meteor> meteor create recipe-app
C:\Users\pcruc\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

RangeError: Maximum call stack size exceeded
```

**Comment by mk360** [comment]
Hello @petercr 
Any updates so far?
I have the same issue, did you solve this issue?

**Comment by petercr** [comment]
Yes so what I ended up doing is installing Meteor through Chocolatey package manager. That way I was able to get Meteor up and running without and problems.  The command is `choco install meteor`. You can find the [Chocolatey website here](https://chocolatey.org/)

I also had to remove the previous .MSI installation of Meteor before I got it working.
