### ISSUE TITLE
[1.8.0.2] SyntaxError for imported *.test.* files 

### ISSUE THREAD

**Issue by bhunjadi** [meteor/meteor#10481]
Versions showing problem: 1.8.0.2, 1.8.1-beta.20
Last working version: 1.8.0.1
OS: Ubuntu 16.04.6 LTS

### Description
Main test module cannot import another *.test.* file that uses ecmascript.
```
// package.js
Package.onTest(function (api) {
    ....
    api.mainModule('my-package-tests.js');
});

// my-package-tests.js
import './additional.tests';

// additional.tests.js
import fs from  'fs'; // SyntaxError because of this line
```

(see reproduction)

### Expected behaviour
Imported *.test.* files should be compiled as any other file.

### Actual behavior
SyntaxError occurs when importing *.test.* file from another test file.

### Reproduction
[repo](https://github.com/bhunjadi/meteor-package-testing)

**Comment by benjamn** [comment]
This should be fixed by 038e35357e58468d3760064d704d3c6a0b07b254 if you run
```bash
meteor update --release 1.8.1-rc.0
```
Thanks for reporting this, and putting together a reproduction!
