### ISSUE TITLE
Meteor ignore package version

### ISSUE THREAD

**Issue by Deadly0** [meteor/meteor#10487]
![Выбрать Windows PowerShell 2019-03-12 13 14 32](https://user-images.githubusercontent.com/4887213/54192605-72675280-44c9-11e9-9a53-33cfd30a37fc.png)

version 2.5.8 was declared, but latest version was installed
Meteor 1.8.0.2

**Comment by benjamn** [comment]
The syntax of package version constraints is slightly different in Meteor than you might be expecting. If you want to force the exact version, do this:
```sh
meteor add jagi:astronomy@=2.5.8
```
Without the `=`, the `@2.5.8` version constraint allows any `2.x.y` version of the package that's greater than 2.5.8. With the `=`, you'll get exactly 2.5.8, unless that version somehow makes it impossible to satisfy other constraints.

Another way to specify 2.5.8 without being too restrictive is to edit `.meteor/versions` after you install the package.
