### ISSUE TITLE
Not able to run multiple app at the same time on IOS  if the app id's start with `com.`

### ISSUE THREAD

**Issue by pramodrwt** [meteor/meteor#10486]
I am running multiple Meteor Apps on IOS platform and due to port conflict app clashing

        

*  So as per meteor repo code, i am able to find out where meteor generating port randomly

* I am running meteor 1.6.1.3 (On Mac OS)

In my case my both app id's contain `com.` (prefix) due to this it's generating same port for both the application

  `  // Convert the appId (a base 36 string) to a number
    const appIdAsNumber = parseInt(this.projectContext.appIdentifier, 36);
    // We use the appId to choose a local server port between 12000-13000.
    // This range should be large enough to avoid collisions with other
    // Meteor apps, and has also been chosen to avoid collisions
    // with other apps or services on the device (although this can never be
    // guaranteed).

    const localServerPort = 12000 + (appIdAsNumber % 1000);`

Reference: 
 https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js

**Comment by rj-david** [comment]
port number is derived from .meteor/.id

Check the .id file for both projects. Must be different.

**Comment by mirstan** [comment]
Ids are both different, but parseInt only looks at the first part until the dot so "com.mycomp.app" and "com.othercomp.app2" will be treated as "com". Hence any random two app developers who use Meteor and follow the reverse domain naming convention starting "com." won't be able to run two both apps at the same time on iOS.

**Comment by rj-david** [comment]
I'll repeat my post above. The app id being used is from the file .id under the folder .meteor

Update the value stored in the file .meteor/.id

I have 3 cordova apps running in an ios device with bundle identifier all starting with com.*.* without any port collision. The port number is not being derived from the bundle id

**Comment by mirstan** [comment]
OK, I misunderstood. Thanks for the help!

**Comment by pramodrwt** [comment]
As it works for me, so i am closing issue now
