### ISSUE TITLE
regression Facts package doesn't work anymore on 1.8

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#10492]
Facts._factsByPackage always returns {} on 1.8

It works in 1.6 so I don't know when the regression occurred.

**Comment by paulincai** [comment]
Did you consider this separation: "The facts package has been split into facts-base and facts-ui. The original facts package has been deprecated. PR #9629". This was part of 1.7 release.

**Comment by acemtp** [comment]
Oups, It was that.

It's disturbing that the old package is still almost work without a warning message or a that fact just install base + ui.

Anyway, thanks for pointing me it!
