### ISSUE TITLE
OIDC with POST method reqest

### ISSUE THREAD

**Issue by rooch84** [meteor/meteor#10491]
In our project we need to authenticate with a custom OIDC provider.  We need to use hybrid flow rather than implicit flow, and as a result, the redirect comes back with a POST request, as such the params are in the body rather than the query. 

In `packages/oauth/oauth_server.js`, line 161, it is  assumed the params are in the query...
 `handler(service, req.query, res);`

I propose checking the method type and retrieving the params from the body if the method in POST...

```
if (req.method === "POST") {
        const syncBody = Meteor.wrapAsync((request, cb) => {
          let body = [];
          request
            .on("data", chunk => {
              body.push(chunk);
            })
            .on("end", () => {
              body = Buffer.concat(body).toString();
              cb(null, body);
            });
        });
  
        let params = syncBody(req)
          .split("&")
          .reduce((a, kv) => {
            let kvArr = kv.split("=");
            a[kvArr[0]] = decodeURIComponent(kvArr[1]);
            return a;
          }, {});
  
        handler(service, params, res);
      } else {
        handler(service, req.query, res);
      }
```

I can confirm that this works with both our custom OIDC provider (POST), and Gitlab OIDC (GET). 

Meteor version:
- Unreleased, running from a checkout at 86b6086be (HEAD -> devel, origin/devel, origin/HEAD)

**Comment by benjamn** [comment]
Seems like a good idea. Do you have time to submit a PR? I would just ask that we avoid `Meteor.wrapAsync` and use `Promise`s instead, if possible.

Since this would not be a breaking change for the `oauth` package, we can release it whenever we like, and it doesn't need to be tied to the next Meteor release (1.8.1).

**Comment by rooch84** [comment]
Thanks.  I've changed it to a Promise and submitted pull request #10501

**Comment by jramer** [comment]
Also needed for "Sign in with Apple". More info in my closed issue(meteor/meteor-feature-requests#370).

**Comment by rooch84** [comment]
PR here: https://github.com/meteor/meteor/pull/10501

It's not clear what else is required.

**Comment by jramer** [comment]
This already taken care of in #10751  and #10501 is closed.
