### ISSUE TITLE
Occasional SIGSEV

### ISSUE THREAD

**Issue by maxonetiq** [meteor/meteor#10507]
Hi,
hope this is the place for this report.

* Current version: 1.6
* Last version (probably) not having this issue: v1.4 (not really sure)
* Host OS: Debian 8.6
* Current behaviour: we're experiencing occasional segmentation faults of our meteor instances. Every now and then an instance crashes with a SIGSEV.
* Preproduction: cannot reproduce
* Additional info
   * our meteor app has a REST API implemented with iron router which is used to request data from Mongo
   * the instances are managed by pm2 which runs them in cluster mode

After running lldb on the process I got this trace:

`Process 44752 stopped
* thread #1: tid = 44752, 0x00000e7798f55408, name = 'node /apps/WAP3/', stop reason = invalid address (fault address: 0x0)
    frame #0: 0x00000e7798f55408
-> 0xe7798f55408:  cmpq   %rdi, 0x7(%r9)
   0xe7798f5540c:  jne    0xe7798f55418
   0xe7798f5540e:  movq   0x2f(%rbx,%r8), %rdi
   0xe7798f55413:  jmp    0xe7798f5549f
(lldb) bt
* thread #1: tid = 44752, 0x00000e7798f55408, name = 'node /apps/WAP3/', stop reason = invalid address (fault address: 0x0)
  * frame #0: 0x00000e7798f55408
    frame #1: 0x00000e7798e8535f
    frame #2: 0x00000e7798f3d196
    frame #3: 0x00000e779955abf8
    frame #4: 0x00000e7798f3d196
    frame #5: 0x00000e7798f3d196
    frame #6: 0x00000e7798f3d196
    frame #7: 0x00000e7798e84239
    frame #8: 0x00000e7798e84101
    frame #9: 0x0000000000e12e4a node`v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 266
    frame #10: 0x0000000000ae61e3 node`v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 355
    frame #11: 0x0000000000af4c11 node`v8::Function::Call(v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 65
    frame #12: 0x00007f7d5855eb87 fibers.node`Fiber::RunFiber(void**) + 855
    frame #13: 0x00007f7d5855f70d fibers.node`Coroutine::trampoline(void*) + 189
    frame #14: 0x00007f7d5855fb77 fibers.node`coro_init + 55
    frame #15: 0x00007f7d5c7b0f00 libc.so.6`

Until now we haven't been able to reproduce this behaviour, it just "happens".
As the lldb trace is the only hopefully helpful info I can currently provide, is there anybody who has had this issue or knows where to look further?
Any help would be greatly appreciated.

**Comment by ramezrafla** [comment]
@maxonetiq 
Trying to help here, a segmentation error shouldn't happen with pure JS code as the node js garbage collector should clear references properly (i.e. no stray references that you may be trying to access) and you shouldn't be able to access external memory with JS code; so it's either a bug in nodejs ' v8 or you are using a node module that is compiled. I am not an expert in WASM, but there could be a malloc there .. to be checked (do you have WASM code in your app?)

Have you tried upgrading nodejs to another version (what version are you using?)
