### ISSUE TITLE
Android app refreshes once on every open

### ISSUE THREAD

**Issue by saikatharryc** [meteor/meteor#10506]
Hi, i'm facing an issue, which is neither logging any issue or anything related.
whenever i'm actually opening the app, it refreshes the current opened page [even if i navigate quickly to some other page it does the same].
and does not log anything related.
is it only me who is facing the issue? 
i have tried to run the app in remote server with `--once` flag as well. does not seem to work as expected.

*METEOR@1.8.0.1*
cordova plugins used:
```
cordova-android-support-gradle-release@2.0.1
cordova-plugin-background-mode@0.7.2
cordova-plugin-device@1.1.6
cordova-plugin-geolocation@4.0.1
cordova-plugin-inappbrowser@3.0.0
cordova-plugin-meteor-webapp@1.6.4
cordova-plugin-web-share@1.2.0
de.appplant.cordova.plugin.local-notification@0.8.5
phonegap-plugin-push@1.9.0

```

**Comment by rj-david** [comment]
Seems like a re-render is happening. Are you using react?

**Comment by saikatharryc** [comment]
this is happening still, but not happening in browsers. yes i'm using react.

**Comment by rj-david** [comment]
Are you using a UI framework? The page might have an onShow attribute or something similar that is being triggered and causing the re-render

**Comment by saikatharryc** [comment]
Not, not using anything like that.
But seems like it happens only in debug mode of the app.
Keeping an eye on the production published build. Its been a 4hours. And
not seem to have that issue in there. In apk i'm checking although.

**Comment by chaymankala** [comment]
Can you please show some code of your home page or index.js, if possible?

**Comment by saikatharryc** [comment]
i guess, this is because of Hot code reload system this is happening in development mode.
and stopped happening in published version in both [ios & android].
