### ISSUE TITLE
1.8.1-rc.1   MongoError: database name must be a string

### ISSUE THREAD

**Issue by scottstensland** [meteor/meteor#10508]
I have an app which runs fine on 

METEOR@1.8

which was using 

npm-mongo@3.1.1

however after trying out 

METEOR@1.8.1-rc.1

system auto bumped npm-mongo module up to

npm-mongo@3.1.2-rc181.1

which results in error

```
/tmp/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoError: database name must be a string
    at Function.create (/tmp/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)
    at validateDatabaseName (/tmp/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/db_ops.js:720:22)
    at new Db (/tmp/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:181:3)
    at MongoClient.db (/tmp/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:268:14)
    at packages/mongo/mongo_driver.js:186:25
    at runWithEnvironment (packages/meteor.js:1286:24)

```

I see same error message on previous meteor releases so looks like `npm-mongo` needs attention

**Comment by benjamn** [comment]
I haven't been able to reproduce this locally, so it would be great if you can provide a small runnable reproduction.

Is there anything even slightly out of the ordinary that you're doing with Mongo? The database name usually comes from the last part of the connection URL (`mongodb://127.0.0.1:3001/<db name>`), and is typically either `meteor` or `local`.

**Comment by jmark1m** [comment]
My app ran fine on METEOR@1.8 but started getting "MongoError: database name must be a string" errors under METEOR@1.8.1 also.  

I had my MONGO_URL set like this. 
export MONGO_URL=mongodb://localhost:27017

It seems to work if I change MONGO_URL to
export MONGO_URL=mongodb://localhost:27017/meteor

But now the database I was using previously is gone.

**Comment by jmark1m** [comment]
Setting 
export MONGO_URL=mongodb://localhost:27017/admin

fixes my "MongoError: database must be a string" error and I get my old database back.  Perhaps on the older version of meteor it just defaulted to admin and now that changed some how?

**Comment by erwzqsdsdsf** [comment]
1.8.1 ,mongo url must contain data base name now

**Comment by scottstensland** [comment]
OK its working after I populate database name as in

 export MONGO_URL=mongodb://localhost:27017/meteor
