### ISSUE TITLE
Too much recursion when importing mobx-react

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#10504]
When adding this single line to a meteor project
```
import {observer} from "mobx-react"
```
i get a `too much recursion` error in firefox (`maximum call stack size exceeded` in chrome).

This is probably related to meteor build tool. 

Meteor 1.8.0.2

Minimal repro showing the issue (just an app created with -minimal)
https://github.com/vjau/toomuchrecursionmeteor

**Comment by MastroLindus** [comment]
i use meteor 1.8.0.2 and mobx-react without any issue (even after upgrading to 1.8.1.rc1) however my project is in typescript so it gets precompiled before going through the meteor tool

**Comment by vjau** [comment]
This doesn't seem to happen anymore with Meteor 1.8.1
