### ISSUE TITLE
Secured imports broken in Meteor packages

### ISSUE THREAD

**Issue by imajus** [meteor/meteor#10503]
Meteor 1.8.0.2

I'm working on a Meteor package and trying to hide out server-only sensitive logic from the client using approach described here:
https://github.com/meteor/guide/blob/8d5605a8d0ee4326449c66cdc530fe5469621d9f/content/security.md#secret-server-code

```js
export function commonMethod() {
  if (Meteor.isServer) {
    import { securedMethod } from './server/secured.js';
    // This way I get exactly the same results:
    // const { securedMethod } = require('./server/secured.js');
    securedMethod();
  }
  return 'Hello, Client';
}
```

First signal of something being not right was this message appeared in Firefox console:
> SyntaxError: export declarations may only appear at top level of a module 

When I've started digging it, I've realized that a server-only source code required from common source was, in fact, presented to the client:
```js
///////////////////////////////////////////////////////////////////////
//                                                                   //
// node_modules/meteor/secure-imports/server/secured.js              //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
export function securedMethod() {
  return 'Hello, Server';
}
```

Moreover, it seems that it's not being processed by build plugin so ES6 modules aren't converted to CommonJS modules, as opposed to other source files shipped to the client.

I've created this sample Meteor project from scratch to showcase the issue:
https://github.com/imajus/meteor-package-secure-imports-case

Steps to reproduce:
1. `meteor npm i`
2. `meteor run`
3. Open `http://localhost:3000` in a browser
4. Open browser console drawer and note the error message
5. Alternatively, just open `http://localhost:3000/packages/secure-imports.js` and search for a string "Hello, Server" there. 

Expected behaviour:
* Server-only source code must not be revealed to the client.

This approach works for Meteor apps, but for some reason it doesn't for Meteor packages.

**Comment by pmogollons** [comment]
I think you cant use imports if not in the top level, but you can use ```require``` as in the code you mentioned.

**Comment by imajus** [comment]
Yeah, I know that as of standard I must use `import` in file root. But currently `import` work in any scope, so I prefer using them over `require`.

I've mentioned in the source code sample, that the problem is reproducible using `require` as well. So this way I will get the same outcome:
```js
export function commonMethod() {
  if (Meteor.isServer) {
    const { securedMethod } = require('./server/secured.js');
    securedMethod();
  }
  return 'Hello, Client';
}
```
