### ISSUE TITLE
1.8: underscore package is present in client bundle despite it not being used anywhere in client.

### ISSUE THREAD

**Issue by s7dhansh** [meteor/meteor#10514]
Based on https://github.com/meteor/meteor/issues/2853#issuecomment-283246145, I found the dependencies on `underscore`.
In my app, the `underscore` packages is only being used by `webapp`, but only on the server. That should ideally remove the package from the client, but it is present in the client bundle. Is that the desired behavior? Can we fix it somehow?

**Comment by benjamn** [comment]
Have you also tried running `meteor list --tree`? Same information?

**Comment by s7dhansh** [comment]
Thank you!
The result set is more complete and I can see `underscore` to be used by many other packages. Will dig deeper to find the culprit.
For now I will close this.
