### ISSUE TITLE
[!] Cannot deploy on iOS 12.2 because of missing support for Swift 4+

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#10516]
iOS 12.2 - Meteor 1.8.0.2 - Xcode 10.1

![Screen Shot 2019-04-07 at 19 10 22](https://user-images.githubusercontent.com/4126817/55687206-a28bff00-596a-11e9-8ca1-d8611e3def84.png)

The solution would obviously be to upgrade to Xcode 10.2. Unfortunately, as reported in this other [issue](https://github.com/meteor/cordova-plugin-meteor-webapp/issues/76), we cannot use Xcode 10.2 because Meteor is still using Swift 3, which has been deprecated and now removed from Xcode 10.2.

IMHO, this is now a hot issue because until support for Swift 4+ is added to Meteor, _**it's not possible to deploy on any iOS 12.2+ device**_.

**Comment by rj-david** [comment]
We also encountered this yesterday. We cannot side load our app using xcode 10.1 to all our ios devices because we upgraded to ios 12.2 (too late for us to realize it).

If we upgrade to xcode 10.2, we cannot build because of missing compatibility to swift 4.

I've submitted a new PR here: https://github.com/meteor/cordova-plugin-meteor-webapp/pull/78

**Comment by benjamn** [comment]
Ok, you can test the changes from https://github.com/meteor/cordova-plugin-meteor-webapp/pull/78 (thanks @rj-david!) by running the following command in any application directory:
```sh
meteor update --release 1.8.1-issue-10516.0
```
Note that this is just a way to validate the fix. Once we release `webapp@1.7.4`, everyone can just update to that version and keep using Meteor 1.8.1.

Are there any other changes we need to make? If we need to update `cordova-ios` (currently [4.5.5](https://github.com/meteor/meteor/blob/456314f0020b90207d051dbd1f86c216c208d40f/tools/cordova/index.js#L18)), that may require a new Meteor release (1.8.1.1). It would be nice to avoid that so soon after 1.8.1, but I'd be happy to do it if necessary.

**Comment by domramirez** [comment]
I'm so happy to see movement on this, but Xcode keeps telling me that the build is coming out in Swift 3. 

**Any other steps I should have taken?**

Here is the sequence of events I followed:
1. meteor add cordova:cordova-plugin-meteor-webapp@1.6.5 (this was before the issue release was made, but seems to take me to the same place)
2. meteor update --release 1.8.1-issue-10516.0
3. meteor remove-platform ios
4. meteor add-platform ios
5. [deleted several build and cache files from .meteor/local and my mobile build destination folder]
6. meteor build ../builds --server=https://blahblah.meteorapp.com --mobile-settings=private/settings.staging.json

And I still see this error message: 

> The target “Ciggy Tennis Training” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.
> 
> Use Xcode 10.1 to migrate the code to Swift 4.

**Comment by benjamn** [comment]
@domramirez Not sure if this will change anything, but the new version of `cordova-plugin-meteor-webapp` is 1.7.0, not 1.6.5. Maybe try `meteor remove cordova:cordova-plugin-meteor-webapp` (since I don't think that's necessary), or possibly updating to 1.7.0 instead?

**Comment by domramirez** [comment]
Oh, you're right, @benjamn. I guess it leveled up twice in recent history. Switching to 1.7.0 seems to build and run just fine in Swift 4.2.

**Comment by davidecantini** [comment]
@benjamn I followed these steps:
1) Installed Meteor 1.8.1
2) Installed Xcode 10.2
3) meteor update --release 1.8.1-issue-10516.0
Now everything seems to work properly with Swift 4.2! As per your question, I'm not experiencing any issue so far, so I'm not sure if there's any other change needed at the moment.
Thank you @rj-david @benjamn and anyone who promptly worked on fixing this issue.
