### ISSUE TITLE
Exception in setInterval callback: undefined

### ISSUE THREAD

**Issue by Slind14** [meteor/meteor#10539]
Hi there,

we are experiencing `Exception in setInterval callback: undefined` for intervals after a few days of them running on an hourly basis. Restarting resolves it for a few days until it breaks like this again. What could be the cause of this?

```
        Meteor.setInterval(
            startJob(),
            1000 * 60 * 60
        );
```

Meteor: 1.8.0.2

**Comment by benjamn** [comment]
Does the interval seem to be aborted due to the exception, or does it keep firing after the failure?

I'm assuming you know `startJob()` needs to return a function. If you want this code to repeatedly call `startJob()`, it should be
```js
Meteor.setInterval(
  () => startJob(),
  1000 * 60 * 60
);
```

**Comment by Slind14** [comment]
It works fine for the first 1-3 days running every hour. Then it breaks and throws this error. It keeps throwing the error every hour.
startJob() always returns a function.
