### ISSUE TITLE
Question: dynamic import's hidden baggage

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10532]
As I was working to reduce the size of our app's main bundle, by dynamically importing everything but the absolutely necessary for the first view to render, I noticed that the initial bundle was a lot bigger than I was expecting.

For example, I have a package from where I import only a few files (`import { thing } from 'meteor/arggh:pkg/path/to/file'`) which should total in at around ~5kb, and the rest would be dynamically imported later on. But for some reason the bundle visualizer indicates I'm instead getting about 100kb worth of _something_ included in the main bundle from that package.

Further inspection reveals, that the 95kb of extra baggage consists purely of strings that seem to be the file paths of files in that package and the import paths/declarations in those files. (see the details pane at the end for a sample).

When combined from several packages and `app.js`, these strings add up to about 300kb. Combine that with the weight of `dynamic-versions.js` at around 300kb, and it's getting bulky.

I'm not familiar with the challenges of implementing a dynamic importing mechanism in the Meteor platform and I'm sure these strings have a reason to exist in the main bundle, but still... I'm intrigued to ask, if it's...

**a) working as designed**
**b) a bug**
**c) a stupid user error?**

<summary>
<details>

```js
...
],"template.section_effect.js":[],"section_effect.js":[
  "./section_effect.html",
  "meteor/templating",
  "meteor/manuel:viewmodel",
  "../../../lib/loader"
]}}},"node_modules":{"date-fns":{"differenceInDays":{"package.json":[
  {}
],"index.js":[
  "../toDate/index.js",
  "../differenceInCalendarDays/index.js",
  "../compareAsc/index.js"
]},"toDate":{"index.js":[]},"differenceInCalendarDays":{"index.js":[
  "../_lib/getTimezoneOffsetInMilliseconds/index.js",
  "../startOfDay/index.js"
]},"_lib":{"getTimezoneOffsetInMilliseconds":{"index.js":[]},"toInteger":{"index.js":[]}},"startOfDay":{"index.js":[
  "../toDate/index.js"
]},"compareAsc":{"index.js":[
  "../toDate/index.js"
]},"differenceInHours":{"package.json":[
  {}
],"index.js":[
  "../differenceInMilliseconds/index.js"
]},"differenceInMilliseconds":{"index.js":[
  "../toDate/index.js"
]},"differenceInMinutes":{"package.json":[
  {}
],"index.js":[
  "../differenceInMilliseconds/index.js"
]},"differenceInSeconds":{"package.json":[
  {}
],"index.js":[
  "../differenceInMilliseconds/index.js"
]},"subDays":{"package.json":[
  {}
],"index.js":[
  "../_lib/toInteger/index.js",
  "../addDays/index.js"
]},"addDays":{"index.js":[
  "../_lib/toInteger/index.js",
  "../toDate/index.js"
]},"subHours":{"package.json":[
  {}
],"index.js":[
... 
...thousands of lines
```
</details>
</summary>

**Comment by benjamn** [comment]
I'd be happy to look at a reproduction to see if there's something unusual going on (300KB seems high), but in general this is working as designed. The initial JS bundle must include a complete description of the available dynamic modules and their dependencies to avoid multiple nested round-trips when requesting dynamic modules. This abstract description of the dynamic graph (module paths, hashes, and dependencies) is embedded in the initial JS bundle alongside the code for non-dynamic modules.

Although the abstract description takes up some space, it's almost always smaller than the modules themselves, so switching to dynamic imports will almost always shrink the initial JS bundle, compared to keeping everything static, even though there are still some remnants of those dynamic modules in the initial JS bundle.

**Comment by arggh** [comment]
I'll do some testing to see if the way I'm importing things makes a difference, since a few packages stand out in the bundle visualizer with high amount of non-code taking up space, but I suspect all is good - if not, I'll raise an issue. I'm sure your time is better used at something else. Thank you for explaining this.

For background, our initial bundle was > 6Mb before I started the process of implementing dynamic imports, now it's around 1.3Mb, so that probably is the reason for the relatively high amount of metadata needed about the modules (_hey, 300kb vs. ~5Mb, easy pick..._)

**Comment by mariusrak** [comment]
> The initial JS bundle must include a complete description of the available dynamic modules and their dependencies to avoid multiple nested round-trips when requesting dynamic modules. This abstract description of the dynamic graph (module paths, hashes, and dependencies) is embedded in the initial JS bundle alongside the code for non-dynamic modules.

I'm sorry, but I don't understand how this is preventing multiple nested round-trips, or how omitting those dirs and files would cause the multiple nested round trips. I would also like to get rid of majority of the content of the `app.js` file. Mostly because I have an application that is meant to contain many large modules and single user would need to load only minority of them.  Now it is required to provide every user with structure of every module in the application. 

Is there no way to include only statically bundled files, that are included using `import '...'` and omit those that are included using dynamic import `import()`? When dynamically loaded file is fetched it would "install" all its dependencies into the tree. 

This would also open new possibilities to control fetching and also allow for more dynamic fetching with something like `import('folder/'+someComputedSubFolder+'/file')`. And also allow to absolutely hide some modules that a user should not have access to.

Thanks for an explanation.

**Comment by jirikrepl** [comment]
Hi, after update from meteor@1.8.1 to meteor@1.10.2 file `dynamic-versions.js` suddenly increased in size by ~20KB in the bundle -visualizer.

I did `meteor --production` build and looked for the content of the `minified dynamic-versions.js`
I saw that in meteor@1.10.2 the file is bigger.

It seems to be that bundler.js puts [here](https://github.com/meteor/meteor/blob/master/packages/dynamic-import/dynamic-versions.js#L4) more stuff - in meteor@1.10.2 it included the deeper structure of moment.js 
 
```
// meteor@1.8.1
...
moment: {
    "package.json": "7370717f6decba3db4e2369071f04b64d09fa9f5",
    "moment.js": "45d6030fdd270061f9fb6a276f92f158a5343c69"
},
...
```

```
// meteor@1.10.2
...
moment: {
    "package.json": "97f191005e20639aef5cc6b180a58311f09ebc64",
        src: {
        "moment.js": "410c38baaaa723ceae33ca385b7980fd6680807a",
            lib: {
            utils: {
                "hooks.js": "f1952399b1939380ba4055bca1e165b66c573423",
                    "is-array.js": "666c5bc56aa657da61c8e327f4628abd5875193b",
                    "is-object.js": "29ec62de85648930dd74c3f1e14c097f5f58638f",
                    "is-object-empty.js": "c3635c0ee5e66082b0e902443e46c6c66286345b",
                    "has-own-prop.js": "dfc3668dc0107e50cf7c64360735f32083f50dd3",
                    ...

// plus another 500 lines of moment.js files
...
```
