### ISSUE TITLE
Bundle visualizer request fails with meteor 1.8.1

### ISSUE THREAD

**Issue by shenrenguo** [meteor/meteor#10533]
> web@0.2.2 bundle /Users/srg/workspaces/TENMIC/web
> TOOL_NODE_FLAGS='--max-old-space-size=4096' MAIL_URL='smtp://192.168.1.237:25' meteor run --settings .deploy/settings-deve.json --production

Warning: The --production flag should only be used to simulate production bundling
for testing purposes. Use meteor build to create a bundle for production deployment.
See: https://guide.meteor.com/deployment.html
[[[[[ ~/workspaces/TENMIC/web ]]]]]

=> Started proxy.
=> Started MongoDB.
W20190425-11:58:45.693(8)? (STDERR) => The "bundle-visualizer" package is currently enabled. Visit your application in a web browser to view the client bundle analysis and 'meteor remove' the package before building/deploying the final bundle.

But the request(localhost:3000) fails, it prompts: ERR_EMPTY_RESPONSE

**Comment by benjamn** [comment]
What version of Meteor are you using, and what version of `bundle-visualizer`?

**Comment by shenrenguo** [comment]
> What version of Meteor are you using, and what version of `bundle-visualizer`?

meteor: 1.8.1
bundle-visualizer: 1.2.2
