### ISSUE TITLE
Dynamic import breaks when updating Meteor to 1.8.1 from 1.5

### ISSUE THREAD

**Issue by Sergeyamir** [meteor/meteor#10536]
Good day! I faced the problem of dynamic import in my project (on IDE codeanywhere.com, Ubuntu 16.04) and to make sure that this is not a problem of my project, I decided to check it with a simple and clean example - [https://github.com/msavin/dynamic-import-example](https://github.com/msavin/dynamic-import-example) I copied this example and it worked fine with dynamic imports. Then I just updated the Meteor in this example 1.5 to version 1.8.1 and the import stopped working (just as in my more complex project). From which version of Meteor does this problem occur? The console displays the following message:
```
dynamic-import.js?hash=5b576949ecc253f90859e4ff6ce0af98751adbfc:164 POST http://localhost:3000/__meteor__/dynamic-import/fetch net::ERR_CONNECTION_REFUSED
fetchMissing @ dynamic-import.js?hash=5b576949ecc253f90859e4ff6ce0af98751adbfc:164
(anonymous) @ dynamic-import.js?hash=5b576949ecc253f90859e4ff6ce0af98751adbfc:79
(anonymous) @ meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
Promise.then (async)
Promise.then @ promise.js?hash=0bbd44021409d2a1858ff0fd3fd612863bf2cb96:132
meteorInstall.fetch @ dynamic-import.js?hash=5b576949ecc253f90859e4ff6ce0af98751adbfc:69
...
```

**Comment by benjamn** [comment]
Have you tried running `meteor update --all-packages` and/or `meteor reset`? A lot of things have changed since Meteor 1.5. The change most relevant to this issue is probably that the `dynamic-import` package switched from using a web socket to using an HTTP request. In general, running `meteor reset` to remove the `.meteor/local` directory is a good way to avoid many update-related problems.

**Comment by Sergeyamir** [comment]
I used the "meteor reset" to resolve the problem with Mongo immediately after the update.
There was a message:
```
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
```

And "meteor reset" then solved this problem.

Now, on your recommendation, I executed the command
meteor update - all-packages
The problem remained in the same form.

Are there any recommendations on best way to update to solve such problems? Will it be better to carry out in stages - 1.5 -> 1.6 -> 1.7 ->1.8? Could you tell me - In which version of the meteor is the dynamic-import package switched from using a web socket to using an HTTP request? I will try to update with this transition (to the latest version before and after the transition) and tell you about the results.

**Comment by benjamn** [comment]
Meteor 1.6.1 was the first version to use HTTP for dynamic `import()`, so I would try
```bash
meteor update --release 1.6.1.4
```
because that's the latest version on the 1.6.x line. You can see all published versions by running `meteor show METEOR`. I general, it's safer to update to 1.6.x then 1.7.x then 1.8.x, because fewer things change with each update, though there were some issues with the `@babel/runtime` npm package in 1.7.x that might make updating to 1.7.0.5 more trouble than it's worth (so I would just skip from 1.6.1.4 to 1.8.1).

**Comment by Sergeyamir** [comment]
Thanks for the information! Now the problem is clearer. I installed different versions of Meteor in several different cloud IDEs and found that the ability to work via HTTP request depends on the cloud IDE (in one of them, the old closing c9 HTTP request worked, the rest of the IDEs had the error message described above). Is it possible to use the web socket in newer versions of Meteor or otherwise get around this problem if using HTTP request is difficult for the development environment?

**Comment by Sergeyamir** [comment]
I managed to solve this problem with your information! :-) 
It may be useful for someone: after dynamic-import package switched from using a web socket to using an HTTP request, the address information for an application has become critical. Adding an environment variable to ENV (`ROOT_URL = "https: //a4efahaf..."` - preview address in IDE) allowed dynamic-import to start working. This problem is possible for many cloud IDEs (e.g. AWS c9, Codeanywhere, etc.), where the address of the application preview in WWW may vary and differs from the address of the application on the local computer - http://localhost:3000/

**Comment by benjamn** [comment]
Yep, one of the advantages of the socket implementation was that it worked no matter what hostname you were using, as long as the socket connection succeeded. The HTTP implementation is better in many ways (for example, HTTP requests can be initiated sooner than web sockets), but it definitely is sensitive to things like `ROOT_URL`. Thanks for continuing to investigate this!
