### ISSUE TITLE
My project can't run, he prompted me“Error: Cannot find module 'double-ended-queue'”

### ISSUE THREAD

**Issue by nikonikoCW** [meteor/meteor#10531]
My project used to work normally. I suddenly did this today. 
｛
=> Exited with code: 1
W20190424-14:15:53.162(8)? (STDERR) C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\fibers.js:90
W20190424-14:15:53.164(8)? (STDERR)                                     return fn.apply(this, arguments);
W20190424-14:15:53.165(8)? (STDERR)                                               ^
W20190424-14:15:53.166(8)? (STDERR)
W20190424-14:15:53.167(8)? (STDERR) Error: Cannot find module 'double-ended-queue'
W20190424-14:15:53.168(8)? (STDERR)     at Function.Module._resolveFilename (module.js:548:15)
W20190424-14:15:53.168(8)? (STDERR)     at Function.Module._load (module.js:475:25)
W20190424-14:15:53.169(8)? (STDERR)     at Module.require (module.js:597:17)
W20190424-14:15:53.169(8)? (STDERR)     at require (internal/module.js:11:18)
W20190424-14:15:53.170(8)? (STDERR)     at Object.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor\1.9.3\npm\node_modules\meteor-deque\index.js:1:18)
W20190424-14:15:53.170(8)? (STDERR)     at Module._compile (module.js:653:30)
W20190424-14:15:53.171(8)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20190424-14:15:53.171(8)? (STDERR)     at Module.load (module.js:566:32)
W20190424-14:15:53.172(8)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20190424-14:15:53.172(8)? (STDERR)     at Function.Module._load (module.js:498:3)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
｝

What should I do?
please help me！！！

**Comment by alwsBgood** [comment]
Any updates? Running into same issue

**Comment by filipenevola** [comment]
Hi @alwsBgood can you provide a reproduction?
