### ISSUE TITLE
1.8.2-beta.0 Fail build on Ubuntu

### ISSUE THREAD

**Issue by pgiani** [meteor/meteor#10540]
It looks like some binaries a missing for the Linux version of 1.8.2-beta.0
 
os: Ubuntu 18.04.2 64bit

`This project uses Meteor 1.8.2-beta.0, which isn't available on this platform. To work with this app on all supported platforms,`

**Comment by benjamn** [comment]
Ok, please try updating to 1.8.2-beta.1:
```sh
meteor update --release 1.8.2-beta.1
```
