### ISSUE TITLE
from 1.7 to 1.8 in development mode not livereload on assets changes

### ISSUE THREAD

**Issue by stefanocudini** [meteor/meteor#10558]
in one of my projects I realized that after switching from 1.7 to 1.8 meteor when I start in development mode meteor ignores changes to file assets, in my case .svg images

Before I used to change the svg images of icons and have autoreloading … for convenience, but now I can’t do it.

I have to destroy the meteor cache (.meteor / local) to make it load the new version of the modified assets !!!?

**Comment by aliogaili** [comment]
I noticed the same thing with css assets in the public folder , it's no longer refreshing on change.

**Comment by stefanocudini** [comment]
There is a way to refresh the cache in .meteor / local?
otherwise I am forced to do it by hand while working on my active images .. and this is very inconvenient

**Comment by aliogaili** [comment]
I'm also cleaning by hand but I'm not sure if this the expected behaviour going forward or an undesirable side effect of another change. It seems like a regress to me unless it speeding up client rebuild or something.

**Comment by stefanocudini** [comment]
I agree, this problem causes a great waste of time during development.

**Comment by sebakerckhof** [comment]
Confirmed that this is fixed by https://github.com/meteor/meteor/pull/10565

**Comment by stefanocudini** [comment]
good! then from what version?

**Comment by coagmano** [comment]
Looks like it was merged into 1.8.2
