### ISSUE TITLE
cordova and server-render

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10557]
I noticed that my app behaves strangely when running on cordova and hot-code-reload hits. It receives a weird layout.

then i saw in the logs, that my SSR tries to render the page "/__cordova/" (without any file) when hot-reload hits. I did not catch this and delivered just a default page to this users from SSR. So these apps got into a broken state, because they received a wrong html file (not the cordova index.html)

So i see two problems:
- cordova should ask for "/__cordova/index.html" and not just "/__cordova/", which would make it more obvious, what it does.
- server-render's `onPageLoad` should not be invoked for internal endpoints like `__cordova`

i am using https://github.com/abecks/meteor-fast-render instead of server-render directly, but that one uses `server-render`'s onPageLoad under the hood.

**Comment by macrozone** [comment]
this issue is still unresolved. it's probably an edge case but easy fixable

**Comment by filipenevola** [comment]
hi @macrozone thanks for bringing this up.

Could you write a PR with these improvements?

**Comment by Grubba27** [comment]
As this issue has not had any activities in the last months... I will be closing it!
If further information is added I will be happy to reopen this issue
