### ISSUE TITLE
Cannot read property constructor of undefined future.js

### ISSUE THREAD

**Issue by tticom** [meteor/meteor#10553]
\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'constructor' of undefined
    at exposeSubscription (packages\meteorhacks_meteorx.js:61:41)
    at exposeLivedata (packages\meteorhacks_meteorx.js:31:5)
    at packages\meteorhacks_meteorx.js:175:1
    at packages\meteorhacks_meteorx.js:200:4
    at packages\meteorhacks_meteorx.js:208:3
    at D:\source\sovereign\.meteor\local\build\programs\server\boot.js:419:36
    at Array.forEach (<anonymous>)
    at D:\source\sovereign\.meteor\local\build\programs\server\boot.js:228:19
    at D:\source\sovereign\.meteor\local\build\programs\server\boot.js:479:5
    at Function.run (D:\source\sovereign\.meteor\local\build\programs\server\profile.js:510:12)
    at D:\source\sovereign\.meteor\local\build\programs\server\boot.js:478:11
Exited with code: 1
Your application is crashing. Waiting for file change.

Sorry I have no background at all with meteor but a product I need to work with uses it.
I'd appreciate any help in trying to understand this.

Thanks.

**Comment by evolross** [comment]
Possibly consider using a linux version of Meteor on a virtual machine or in the Windows 10 [Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).  The official Windows version and support is kinda behind and buggy these days.  Using actual linux works the best.

**Comment by pmogollons** [comment]
@tticom Your issue might be related to this one meteorhacks/meteorx#8, you can fix it by using this package instead

https://github.com/lamhieu-vk/meteorx
