### ISSUE TITLE
Triaging issues

### ISSUE THREAD

**Issue by ksungha** [meteor/meteor#10566]
I have noticed some of the issues in the issue tracker do not have proper labels attached to them. Looking at the severity levels of some issues allow some newer developers to find low impact issues to work on.

Note: This issue was brought up as a possible inclusivity fix for an open source software course.

**Comment by filipenevola** [comment]
Hi, `pull-requests-encouraged` should be a good indication of something ready to be fixed and with enough information on the issue comments. If not you can ask for more information.

Also, the roadmap provides many areas where we want contributions https://github.com/meteor/meteor/blob/devel/Roadmap.md
