### ISSUE TITLE
FullText client side

### ISSUE THREAD

**Issue by stefanocudini** [meteor/meteor#10568]
Hi when I try to execute a query using operator *$text* I'm recevice this error mssage
```Uncaught Error: Unrecognized logical operator: $text```

how can I bypass the problem for a client-side so that the result also on the client side is similar to that obtained on the server side (where the $text operator works)
Because I use this query like a result of publish() and I want filter the results also client side using the same query function :(

server:
```
Places._ensureIndex({"name": "text"});
Places.find({
	$text: {$search: text}
},{
	fields: {
		score: {
			$meta: "textScore"
		}
	},
	sort: {
		score: {
			$meta: "textScore"
		}
	}
});
```
client?
```
Places.find({
	score: {
		$exists:true
	},
	name: new RegExp(text, 'i')
});
```

**Comment by arichter83** [comment]
Hi @stefanocudini 

the `$text` is not available in minimongo: see [here](https://github.com/meteor/meteor/blob/efc8a3525db6067bf1d381c033c6ac937c15d631/packages/minimongo/common.js#L17)

The `score` is only available from MongoDB. If you publish it to the client you can use it there. If you want to do matching similar to $text on the client your best bet is [$regexp](https://github.com/meteor/meteor/blob/efc8a3525db6067bf1d381c033c6ac937c15d631/packages/minimongo/common.js#L168), see MongoDB documentation for usage.

Good luck,
Andreas

**Comment by benjamn** [comment]
Thanks for the accurate analysis @arichter83!
