### ISSUE TITLE
meteor 1.8.1 occurs static-html build error

### ISSUE THREAD

**Issue by goodspeed666** [meteor/meteor#10569]
Hello,

When I use the meteor-1.7.0.5, it's fine.
I run Xcode 10.2, so I need upgrade meteor to 1.8.1-issue-10516.0.
And I try to upgrade to 1.8.1, 1.8.2-beta.4, 1.9-alpha.4.

`rm -rf .meteor/local/cordova-build/ && meteor run ios-device --port 4090 --settings settings.json --mobile-server 192.168.x.x`

It always show the errors.

> /.meteor/packages/static-html/.1.2.2.13o941j.atkz++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
> Error: Some Cordova plugins installation failed: (cordova-plugin-local-notifications).
>    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:769:13)
>    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:766:12)
>    at /tools/cordova/project.js:727:14
>    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
>    at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:585:18)
>    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:242:10)
>    at /tools/cordova/runner.js:78:27
>    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
>    at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
>    at /tools/runners/run-app.js:661:25
>    at Object.capture (/tools/utils/buildmessage.js:283:5)
>    at AppRunner._runOnce (/tools/runners/run-app.js:660:39)
>    at AppRunner._fiber (/tools/runners/run-app.js:922:28)
>    at /tools/runners/run-app.js:401:12
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I can't find the newest `static-html` package, and it still keep the 1.2.2 version.
Does anyone have idea ?

Thank you.

**Comment by michaelknoch** [comment]
did you manage to fix this issue? I'm facing the same issue @goodspeed666

**Comment by goodspeed666** [comment]
Hi @michaelknoch ,

I have given up meteor, Good luck !

**Comment by filipenevola** [comment]
@michaelknoch are you also using `cordova-plugin-local-notifications`? It seems like this plugin installation is failing and causing problems.

**Comment by crapthings** [comment]
same here 1.8.2

```
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a minimum version of 2.3.0 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you
         should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have a minimum version of 4.1.0 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you
         should adjust your dependencies.
Reinstalling Cordova plugins added from the local path
Plugin cordova-plugin-mobpush was not installed.
Retrying to install cordova-plugin-mobpush.
Plugin cordova-plugin-mobpush was not installed.
/Users/monsterstep/.meteor/packages/static-html/.1.2.2.ofx8rg.3hb1k++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: Some Cordova plugins installation failed: (cordova-plugin-mobpush).
    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:771:13)
    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:768:12)
    at buildmessage.enterJob (/tools/cordova/project.js:729:14)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:587:18)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:244:10)
    at buildmessage.enterJob (/tools/cordova/runner.js:78:27)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
    at buildmessage.capture (/tools/runners/run-app.js:661:25)
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at AppRunner._runOnce (/tools/runners/run-app.js:660:39)
    at AppRunner._fiber (/tools/runners/run-app.js:929:28)
    at /tools/runners/run-app.js:401:12
```

**Comment by filipenevola** [comment]
Hi, if the issue happens only when adding a specific plugin you should check the plugin code that is breaking your build.

If you provide a repository with a reproduction it would be also easier for people to investigate and help you.
