### ISSUE TITLE
Minimongo Decimal sorting not working

### ISSUE THREAD

**Issue by Gregivy** [meteor/meteor#10561]
Meteor 1.8.1
macOS 10.14.3 / Google Chrome

I am using Decimal128 type in MongoDB, I have added `decimal` meteor package https://github.com/meteor/meteor/tree/devel/packages/non-core/mongo-decimal .

**Expected behavior**
When I use minimongo sorting on Decimal it should work like if it was *Number*.

**Actual behavior**
```
Error: Sorting not supported on Javascript code
    at Object._cmp (matcher.js:344)
    at Object._cmp (matcher.js:294)
    at Object._cmp (matcher.js:281)
    at Array.<anonymous> (sorter.js:296)
    at Sorter._keyComparator (sorter.js:309)
    at Sorter._compareKeys (sorter.js:122)
    at sorter.js:255
    at Array.sort (<anonymous>)
    at Cursor._getRawObjects (cursor.js:480)
    at Cursor.count (cursor.js:59)
```
I've found out that *mongo-decimal* package introduces new EJSON type *Decimal* which returns *Object of Decimal Class*. That's why function `LocalCollection._f._type(v)` which is being called inside `_cmp` thinks that `v` is a function and returns code *13* and the error occurs.

**Comment by bhunjadi** [comment]
I've "fixed" that issue with the following code:

```
const originalType = LocalCollection._f._type;

LocalCollection._f._type = v => {
    if (v instanceof Decimal) {
        return 1;
    }

    return originalType(v);
};
```
