### ISSUE TITLE
Click-outs to meteor build websites from Instagram aren't responsive

### ISSUE THREAD

**Issue by Maikemon** [meteor/meteor#10579]

**Comment by Maikemon** [comment]
Hi, whenever I link to our Meteor built websites from Instagram (be it an ad, a story or bio link) it redirects to the desktop version of the sites instead of the mobile version. Any ideas how to resolve this issue?

**Comment by ninjaPixel** [comment]
How do you serve the mobile version of your site? And is this determined by the headers the node app receives?

**Comment by Maikemon** [comment]
Hi!the developers could fix the problem. Thanks so much for your support!

Maike
