### ISSUE TITLE
failed to build: The command '/bin/sh -c curl https://install.meteor.com/ | sh' returned a non-zero code: 2

### ISSUE THREAD

**Issue by viss3595** [meteor/meteor#10572]
when i try to install Meteor in docker using dockerfile. 

### **Error when i docker-compose up command.**
![image](https://user-images.githubusercontent.com/22858445/58700621-348a1400-83be-11e9-8cbf-65f54f71b769.png)

Step 4/27 : RUN curl https://install.meteor.com/ | sh
 ---> Running in 100c961b8757
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0   4180      0 --:--:--  0:00:01 --:--:--  4178
Downloading Meteor distribution
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
ERROR: Service 'ohifviewer' failed to build: The command '/bin/sh -c curl https://install.meteor.com/ | sh' returned a non-zero code: 2

### Here is my dockerfile anyone get idea where is the problem.

#First stage of multi-stage build
#Installs Meteor and builds node.js version
#This stage is named 'builder'
#The data for this intermediary image is not included
#in the final image.
FROM node:8.10.0-slim as builder

RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
	curl \
	g++ \
	git \
	python \
	build-essential
	
RUN curl https://install.meteor.com/ | sh

#Create a non-root user
RUN useradd -ms /bin/bash user
USER user
RUN mkdir /home/user/Viewers
COPY OHIFViewer/ /home/user/Viewers/OHIFViewer/
ADD --chown=user:user . /home/user/Viewers

WORKDIR /home/user/Viewers/OHIFViewer

ENV METEOR_PACKAGE_DIRS=../Packages
ENV METEOR_PROFILE=1
ADD package.json /home/user/Viewers/OHIFViewer
RUN meteor npm install
RUN meteor build --directory /home/user/app
WORKDIR /home/user/app/bundle/programs/server
RUN npm install --production

#Second stage of multi-stage build
#Creates a slim production image for the node.js application
FROM node:8.10.0-slim

RUN npm install -g pm2

WORKDIR /app
COPY --from=builder /home/user/app .
COPY dockersupport/app.json .

ENV ROOT_URL http://localhost:3000
ENV PORT 3000
ENV NODE_ENV production

EXPOSE 3000

CMD ["pm2-runtime", "app.json"]

**Comment by viss3595** [comment]
now i change docker script 

RUN curl https://install.meteor.com/ | sh
to
RUN curl https://install.meteor.com | bash

### Output :

Step 4/27 : RUN curl https://install.meteor.com | bash
 ---> Running in c48d0e1781c6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0   1353      0 --:--:--  0:00:05 --:--:--  2409
Downloading Meteor distribution

Meteor 1.8.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

### But there is one more issue when i meteor npm install.

![image](https://user-images.githubusercontent.com/22858445/58703277-c9444000-83c5-11e9-822b-0f5f6ffcbc3f.png)

Step 14/27 : RUN meteor npm install
 ---> Running in 17a45df140de
Downloading Meteor distribution
This is your first time using Meteor!
Installing a Meteor distribution in your home directory.
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@babel/core: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.3.4.8gfspn.1atd8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
ERROR: Service 'ohifviewer' failed to build: The command '/bin/sh -c meteor npm install' returned a non-zero code: 2

**Comment by klaussner** [comment]
This seems to be a problem with OverlayFS and `tar`: https://github.com/coreos/bugs/issues/1095. You could try to install `bsdtar` in the Docker container and replace the `tar` command (see https://github.com/coreos/bugs/issues/1095#issuecomment-336872867).
