### ISSUE TITLE
can't find module error only with meteor1.8.1 windows10 x86_64 

### ISSUE THREAD

**Issue by YUFAN2GA** [meteor/meteor#10570]
The project used to dev  on mac and deployed on Ubuntu, they all worked,  when I want to do dev on windows 10, exception as below thrown and exit 1

> => Started proxy.
> => Started MongoDB.
> W20190530-17:58:37.478(8)? (STDERR) C:\Users\XX\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
> W20190530-17:58:37.478(8)? (STDERR) 						throw(ex);
> W20190530-17:58:37.478(8)? (STDERR) 						^
> W20190530-17:58:37.478(8)? (STDERR) 
> W20190530-17:58:37.479(8)? (STDERR) Error: Cannot find module './build/Debug/addon'
> W20190530-17:58:37.479(8)? (STDERR)     at Function.Module._resolveFilename (module.js:548:15)
> W20190530-17:58:37.479(8)? (STDERR)     at Function.Module._load (module.js:475:25)
> W20190530-17:58:37.479(8)? (STDERR)     at Module.require (module.js:597:17)
> W20190530-17:58:37.479(8)? (STDERR)     at require (internal/module.js:11:18)
> W20190530-17:58:37.479(8)? (STDERR)     at Object.<anonymous> (C:\Users\YF\WebstormProjects\epsilon-trade-app-server\node_modules\heapdump\index.js:19:15)
> W20190530-17:58:37.479(8)? (STDERR)     at Module._compile (module.js:653:30)
> W20190530-17:58:37.480(8)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
> W20190530-17:58:37.480(8)? (STDERR)     at Module.load (module.js:566:32)
> W20190530-17:58:37.480(8)? (STDERR)     at tryModuleLoad (module.js:506:12)
> W20190530-17:58:37.480(8)? (STDERR)     at Function.Module._load (module.js:498:3)
> W20190530-17:58:37.480(8)? (STDERR)     at Module.require (module.js:597:17)
> W20190530-17:58:37.480(8)? (STDERR)     at require (internal/module.js:11:18)
> W20190530-17:58:37.480(8)? (STDERR)     at npmRequire (C:\Users\YF\WebstormProjects\epsilon-trade-app-server\.meteor\local\build\programs\server\npm-require.js:133:10)
> W20190530-17:58:37.480(8)? (STDERR)     at Module.useNode (packages\modules-runtime.js:664:18)
> W20190530-17:58:37.481(8)? (STDERR)     at index.js (packages\modules.js:325:8)
> W20190530-17:58:37.481(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
> => Exited with code: 1
>

**Comment by klaussner** [comment]
The `heapdump` npm package that you are using contains a native Node add-on that has to be compiled at installation time. Did you run `meteor npm install` on your Windows machine?

**Comment by YUFAN2GA** [comment]
I tried ```meteor npm install```
> C:\Users\WebstormProjects\app-server\node_modules\heapdump\build\addon.vcxproj(20,3): error MSB4019: not found import project “C:\Microsoft.Cpp.Default.props”. please confirm <Import> path and did exist
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\xx\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\node-gyp\lib\build.js:262:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Users\\xx\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\xx\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows
> .x86_64\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\xx\WebstormProjects\epsilon-trade-app-server\node_modules\heapdump
> gyp ERR! node -v v8.15.1
> gyp ERR! node-gyp -v v3.7.0
> gyp ERR! not ok

BTW, I found heapdump is not in use anymore, so I removed heapdump import and code with meteor 1.8.1 runs ok now on windows10.

**Comment by filipenevola** [comment]
as the problem was in a specific npm module and removing it resolved the issue I'm closing it.
