### ISSUE TITLE
Errors thrown on server methods dont log original stack trace

### ISSUE THREAD

**Issue by sajhu** [meteor/meteor#10574]
Hello

Since upgrading to meteor 1.8.0.2 from 1.6.x I've noticed that any method call that results in an error is printed on the server console as:

`Exception while invoking method 'login' [object Object]`

This happens both on development on my mac and deployed on Galaxy.

Before, the whole stack trace was printed, but this Object object logging doesnt help me figure out the actual problem. My solution so far has been to wrap method implementation in a try catch statement that logs the original exception and rethrows it for the client to know.

In this case, since the error is on the `login` method which is in a package, I cannot update it to print the real problem. On the client, all I get on any error is that there was a 500 error on the server, so no root cause either.

`{"isClientSafe":true,"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}`

Any ideas on how to temporarly solve this? I've been searching for a server level error handler but so far have found nothing.

I haven't updated to 1.8.1 since I pinpointed that version to failing android and iOS builds, which I have to report later.

thanks

**Comment by alihuber** [comment]
Hello
has this something to do with https://github.com/meteor/meteor/issues/10078 ?

**Comment by sajhu** [comment]
Yes, it does, thanks!
