### ISSUE TITLE
add-platform android error

### ISSUE THREAD

**Issue by hshaterian** [meteor/meteor#10584]
For build android app, after install prerequisites (jdk, android studio, set $ANDROID_HOME in PATH & ...) while

`meteor add-platform android`

 I got following error:

> /home/my_username/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

>Error: Error: couldn't install npm package cordova-lib@7.1.0: Command failed: /home/my_username/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install cordova-lib@7.1.0
npm ERR! path /home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!  { Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e',
npm ERR!   parent: 'tar' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/my_username/.npm/_logs/2019-06-13T12_37_24_344Z-debug.log
npm ERR! path /home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!  { Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, open '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/my_username/.npm/_cacache/index-v5/02/69/7d88d4e58d61f809c66638212ceeb8d6b09b61ec525cf6e881e52fbfb59e',
npm ERR!   parent: 'tar' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/my_username/.npm/_logs/2019-06-13T12_37_24_344Z-debug.log

   > at Object.error (/tools/utils/buildmessage.js:467:11)
    at meteorNpm.installNpmModule (/tools/isobuild/meteor-npm.js:1096:20)
    at Object.keys.forEach.dep (/tools/cli/dev-bundle-helpers.js:19:21)
    at Array.forEach (<anonymous>)
    at Object.ensureDependencies (/tools/cli/dev-bundle-helpers.js:19:6)
    at buildmessage.enterJob (/tools/cordova/index.js:33:10)
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at ensureDevBundleDependencies (/tools/cordova/index.js:27:16)
    at Command.func (/tools/cli/commands-cordova.js:124:3)
    at /tools/cli/main.js:1531:15

even install separately cordova-lib@7.1.0 or cordova-lib@9.0.1 like following did not help:

`meteor npm install cordova-lib`
`meteor npm install cordova-lib@7.1.0`
`meteor npm install cordova-lib@9.0.1`

my system versions:

meteor: 1.8.1
node version:
v8.16.0
jdk version:
openjdk version "1.8.0_191"
android studio version:
3.3
android sdk tools:
26.1.1
android sdk tools:
Q revision 3
jre: 1.8.0_152-release-1248-b01 amd64
Linux 4.15.0-45-generic

Can anyone help me?
Anyone have idea about it?

**Comment by paulincai** [comment]
Hi there, I don't see this being related to Meteor or Node. There are various resources which address this problem like this one: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
