### ISSUE TITLE
Metero 1.8.1 Tryng to `meteor build` with Cordova Failed to execute aapt

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#10589]
Trying to do a Meteor build with platform `android` I get the following error: 

> Failed to execute aaptp for Android          -
> com.android.ide.common.process.ProcessException: Failed to execute aapt
> 	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
> 

Meteor versions this happens with 1.8.02, 1.8.1 and METEOR@1.8.1-issue-10516.0 #10516 
Gradle version - tried with numerous versions includinga versions with 5.4, 5.4.1, 4.1 & 2.14.1  

current studio config
![Screen Shot 2019-06-21 at 8 52 12 am](https://user-images.githubusercontent.com/7233741/59886405-28640600-9402-11e9-8576-827ab7a142f0.png)
![Screen Shot 2019-06-21 at 8 52 03 am](https://user-images.githubusercontent.com/7233741/59886406-28640600-9402-11e9-9beb-7ff8b8992242.png)

If I do a `meteor run ios-device` it all works well. I can use X Code 10.1 and successfully build an iOS android app.

However when doing the `meteor build` with intent to create Android version it fails. 

between each build we've done `meteor reset` and intermittently removed and added platform `android` 

Have tried varius sdk options. Current settings are

```
App.setPreference('android-targetSdkVersion', '26');
App.setPreference('android-minSdkVersion', '19');

```

Have tried App.setPreference('android-compileSdkVersion', '26');

Have tried removing Crosswalk
Changing upgrading Cordova plugins

I tried following a bunch of similar issues and doing things like 
https://github.com/meteor/meteor/issues/9923

The current 1.8.0.2 cordova plugins
```
cordova-android-support-gradle-release@1.2.0
cordova-custom-config@4.0.2
cordova-plugin-calendar@4.4.7
cordova-plugin-compat@1.2.0
cordova-plugin-console@1.1.0
cordova-plugin-contacts@2.3.1
cordova-plugin-customurlscheme@https://github.com/EddyVerbruggen/Custom-URL-scheme.git#c3adccd39b116a1fc93b0dd741fc3fdb5e30989c
cordova-plugin-device@1.1.6
cordova-plugin-file@4.3.3
cordova-plugin-geolocation@2.4.3
cordova-plugin-image-picker@1.1.3
cordova-plugin-inappbrowser@1.7.2
cordova-plugin-ios-ble-permissions@1.0.1
cordova-plugin-media-capture@1.4.3
cordova-plugin-meteor-webapp@1.4.2
cordova-plugin-speech-recognition-feat-siri@2.1.1
cordova-plugin-speechrecognition@https://github.com/pbakondy/cordova-plugin-speechrecognition.git#9302a31f7007a0180bd291e52da4130b48661924

cordova-plugin-wkwebview-engine@1.1.4
cordova.plugins.diagnostic@3.0.2
phonegap-plugin-push@1.11.1
```
The 1.8.1 plugins
```
cordova-custom-config@4.0.2
cordova-plugin-calendar@4.4.7
cordova-plugin-console@1.1.0
cordova-plugin-contacts@2.3.1
cordova-plugin-customurlscheme@https://github.com/EddyVerbruggen/Custom-URL-scheme.git#c1a0de2ad3a03efc01f4656e33391c922279e8f3
cordova-plugin-device@1.1.6
cordova-plugin-file@4.3.3
cordova-plugin-geolocation@2.4.3
cordova-plugin-inappbrowser@1.7.2
cordova-plugin-ios-ble-permissions@1.0.1
cordova-plugin-media-capture@1.4.3
cordova-plugin-meteor-webapp@1.4.2
cordova-plugin-speech-recognition-feat-siri@2.1.1
cordova-plugin-speechrecognition@https://github.com/pbakondy/cordova-plugin-speechrecognition.git#9302a31f7007a0180bd291e52da4130b48661924
cordova-plugin-statusbar@2.4.2
cordova-plugin-wkwebview-engine@1.1.4
cordova.plugins.diagnostic@3.0.2
phonegap-plugin-push@1.11.1

```

I have played around with upgrading many of the above plugins... still the same issue

I have tried rolling back to a version of our app (based on Meteor 1.8.0.2) that was building and it's still not working. 

Completely Stumped!!!

**Comment by adamgins** [comment]
When I try with Gradle 3.0 I get this error 

```
  Building Cordova app for Android          \                          
:app:createReleaseCompatibleScreenManifests
/Users/adamginsburg/Documents/development/buzzy7/.meteor/local/cordova-build/platforms/android/app/src/main/AndroidManifest.xml:22:18-86 Error:
	Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-49:19 to override.


See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```
I did try and modify this via `mobile-config.js` with 
```
App.appendToConfig('<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge"><application tools:replace="android:appComponentFactory" android:appComponentFactory="whatever"/></edit-config>');
```
but no luck... I don't think that edit took properly. I checked the manifest and it seems to be there as-is.. not sure if that's correct?

**Comment by adamgins** [comment]
I changed the gradel back to 5.4.1 same error

```
* What went wrong:
Execution failed for task ':app:processReleaseManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
  	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-49:19 to override.


```

**Comment by adamgins** [comment]
trying `run android` to see if I can get it running on emulator with dev env .. but it won't start on emulator 

>  While running Cordova app for platform Android with options
>    --buildConfig,/Users/adamginsburg/Documents/development/buzzy7/.meteor/local/cordova-build/build.json,--emulator:

**Comment by chemarbraithwaite** [comment]
https://forums.meteor.com/t/meteor-apk-build-broken-with-accounts-google/49294

Had the same error, this resolved it.

**Comment by jhunlouiegonzales** [comment]
We encountered the same issue :(

**Comment by pixelfoundry-dev** [comment]
+1
