### ISSUE TITLE
[1.8.1] Meteor takes disproportionate time to begin serving pages after refresh

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10599]
I'm trying to reduce reload time on Meteor since it's impacting developer speed. I have about 40 plugins, which are NPM packages compiled by Meteor, and this drives up recompile time. When I remove these completely, and I make a small change to a client file, it takes about 20 seconds for the web browser to complete a refresh (which is quite good). If I make a small change in server or shared code, it doesn't take more than 15 seconds for the server to recompile and restart, however it is unresponsive for another 40 seconds leading to a total reload time of 55 seconds. Instead of waiting for the automatic refresh I also tried reloading the browser page manually several times after the server said "Restarted", and I only got "waiting for localhost" until 55 seconds, when it loaded.

Using the debug, it looks like the page does not load until "Finished delayed build of web.browser.legacy", which took 39 seconds (far longer than everything else). Not sure why - I'm using the latest version of Chrome.

Update: Seems like using the qualia plugin to only build the modern part improves this - but that still seems like a bug. Feel free to close if this is fixed in 1.8.2/1.9 (I'm waiting for #10598 to be able to check).

**Comment by harrisonhunter** [comment]
What is the plugin you're referencing?

**Comment by houshuang** [comment]
https://github.com/qualialabs/one
