### ISSUE TITLE
Transpilation errors on IE11 

### ISSUE THREAD

**Issue by aliogaili** [meteor/meteor#10595]
I had a client who was trying to access a Meteor app using IE11. The app JS couldn't load due to errors which I'm guessing is related the transpilation for the legacy browser.

If I use Meteor **1.8.1**, I see the following error(s):
<img width="931" alt="Screen Shot 2019-06-25 at 7 02 27 PM" src="https://user-images.githubusercontent.com/1675307/60109811-1248a380-977c-11e9-885a-32706e08615e.png">

If I trace the error I see this:
<img width="462" alt="Screen Shot 2019-06-25 at 7 04 08 PM" src="https://user-images.githubusercontent.com/1675307/60109873-2db3ae80-977c-11e9-9bab-42e6a177c9bf.png">

So it's an error due to the const declaration within the [url-regex ](https://github.com/kevva/url-regex/blob/master/index.js) module. So I tried updating to **1.8.2** to see if [PR#10541](https://github.com/meteor/meteor/pull/10541) would solve it, which I think it did but then I ran into the errors below:

<img width="997" alt="Screen Shot 2019-06-25 at 6 52 45 PM" src="https://user-images.githubusercontent.com/1675307/60109527-8fbfe400-977b-11e9-8769-d5b423ed7318.png">

Any ideas what might be happening here?

**Comment by benjamn** [comment]
Yep, that's an npm package using arrow function syntax. The first problem should be fixed in the latest betas of Meteor 1.8.2: `meteor update --release 1.8.2-beta.8`

The second problem is due to Meteor's JS compilation system assuming `meteorBabelHelpers` is defined, which it isn't (currently) for code in `node_modules`. I think I know how to fix that.

**Comment by benjamn** [comment]
@aliogaili Thanks for helping test Meteor 1.8.2, by the way!

**Comment by aliogaili** [comment]
Thanks for quick response ben! I did more testing with new release and I the previous error is gone but there are new ones. 

<img width="870" alt="Screen Shot 2019-06-25 at 10 03 25 PM" src="https://user-images.githubusercontent.com/1675307/60123386-69f50800-9798-11e9-9880-9d5f41915ce9.png">

And here is the file trace:

<img width="921" alt="Screen Shot 2019-06-25 at 10 04 11 PM" src="https://user-images.githubusercontent.com/1675307/60123526-b2acc100-9798-11e9-9f2e-421472bf739c.png">

I also noticed a regress in the cold startup time, I took several measurement and for us (we've tons of node modules) using 1.8.1 it was taking on average 32s and with 1.8.2 it is now taking around a minute to start, initially after the update I had to wait several minutes (~ 5 min) before it started, but then it was averaging around 1 min. I'm guessing the regress is due to scanning and compiling the node modules on startup to cover legacy? I'm hoping the server refresh time didn't regress. From my perspective, I had only one small package that was causing issues in legacy, so I'd have rather dealt with it then take the extra half minute regress, but I can't speak for everyone. Since most developers use modern browsers and then only test on legacy after, perhaps we can delay the legacy somehow (with a flag or a package) so can have speed up the dev experience and only build for legacy when needed.

**Comment by aliogaili** [comment]
I just reverted back to 1.8.1 for now and used the link solution you outlined in this [post](https://forums.meteor.com/t/litelement-import-litelement-html/45042/8) and it worked perfectly on IE11.

I think this the symbolic link is a very elegant and easy way to solve this legacy transpilation issue which I much prefer over the 1.8.2 aggressive transpilation strategy that seem to open a can of worms  :).

**Comment by aliogaili** [comment]
This issue seems to be resolved in METEOR@1.8.2-beta.15.
