### ISSUE TITLE
[Meteor 1.9+] Monti/Kadira Profiler compatibility issues

### ISSUE THREAD

**Issue by aliogaili** [meteor/meteor#10597]
This is more of a heads up on potential update issues for those using Monti/Kadira profilers When updating to Meteor 1.9+, I was hit with run error as soon as I execute the update command and I had to remove this package to proceed with the update.

It seems to be due to the [dependency](https://github.com/meteorhacks/kadira-binary-deps/blob/d7a1696134fa5a959f7417f08031a0d3e928708e/package.js#L9) on the [v8-profiler](https://github.com/node-inspector/v8-profiler) package, I've open an issue with the error log [here](https://github.com/monti-apm/meteor-profiler/issues/1).

The other package I had to update is the node [heapdump](https://github.com/bnoordhuis/node-heapdump) package for compatibility with node 12.

**Comment by sebakerckhof** [comment]
Same for qualia:profile

**Comment by sebakerckhof** [comment]
There's [v8-profiler-next](https://www.npmjs.com/package/v8-profiler-next) which should support node 12.

**Comment by sebakerckhof** [comment]
Others can use the branch from https://github.com/qualialabs/profile/pull/10 for now

**Comment by filipenevola** [comment]
qualia profile and quave profile packages are working in Node 12 so I'm closing this.
