### ISSUE TITLE
[1.9-alpha.5] Import statement in module.js breaking everything

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10594]
This was not a problem in 1.8.1. I just upgraded to 1.9-alpha without making any other changes. It compiles OK, but when I run the server, I get an error that there is a stray import statement in modules.js, seeming to come from `node_modules/css-vendor/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js`, which seems to crash everything else (leaving me with a blank screen). I guess something around the Babel config has changed, not sure why this file wouldn't be processed properly (seems like there is both a `helpers/toConsumableArray.js` and `helpers/esm/toConsumableArray.js` - not sure why it chooses the `esm` version). 

Reproduction: Check out https://github.com/chili-epfl/FROG/pull/1742, run `./initial_setup.sh`, and then `npm start server`.

<img width="1391" alt="Screenshot 2019-06-24 at 14 05 09" src="https://user-images.githubusercontent.com/61575/60019438-24e4af00-968e-11e9-81b0-0c1df4806089.png">

**Comment by benjamn** [comment]
This will probably be fixed the next time I merge `release-1.8.2` into `release-1.9`.

**Comment by houshuang** [comment]
Thanks for the rapid answer! Any easy way for me to track when that happens so I can test again? (I also tested out the 1.8.2-beta branch and it seems to never finish compiling my code).

**Comment by benjamn** [comment]
I'm optimistic that this will be fixed if you run
```sh
meteor update --release 1.9-alpha.6
```
The best way to track the 1.9 releases is to check https://github.com/meteor/meteor/pull/10527 and/or https://github.com/meteor/meteor/releases for new 1.9 releases.

**Comment by houshuang** [comment]
Cannot verify due to #10598

**Comment by houshuang** [comment]
This is also a problem in 1.8.2-beta.11. Exactly same thing.

**Comment by houshuang** [comment]
Again confirm fixed in 1.8.2-beta.13.
