### ISSUE TITLE
Running multiple meteor applications with different dbs on single mongo instance. Throw errors

### ISSUE THREAD

**Issue by DavidSichau** [meteor/meteor#10602]
We have multiple meteor applications which uses different dbs on the same mongo instance.

Therefore they throw the following error:

```
 Exception in defer callback: Error: Unexpected ns
    at handleDoc (packages/mongo/oplog_tailing.js:293:17)
    at doc.o.applyOps.forEach.op (packages/mongo/oplog_tailing.js:276:15)
    at Array.forEach (<anonymous>)
     at handleDoc (packages/mongo/oplog_tailing.js:273:28)
    at packages/mongo/oplog_tailing.js:341:11
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
```

The reason is the following code inside `packages/mongo/oplog_tailing.js:293:17`
```
        if (typeof doc.ns === "string" &&
            doc.ns.startsWith(self._dbName + ".")) {
          trigger.collection = doc.ns.slice(self._dbName.length + 1);
        } else {
          throw new Error("Unexpected ns");
        }
```

From this code an error is thrown as soon as there is an oplog entry which points to a different database name.

In my opinion the correct or expected behavior is to ignore these entries and not throw an error.

Is there a reason why it throws an error instead of ignoring these oplog entries?

Behavior was observed with Meteor 1.8.1 on a linux machines.

**Comment by benjamn** [comment]
> Is there a reason why it throws an error instead of ignoring these oplog entries?

Not to my knowledge. I agree that ignoring these entries seems more graceful.

**Comment by benjamn** [comment]
This should be fixed now if you run `meteor update mongo` to get `mongo@1.6.3`.
