### ISSUE TITLE
[1.8.2-beta.13] findImportedModule takes 10-20 sec with no cache

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10608]
Trying to figure out how we can shorten the rebuild times, I did some profiling of the latest 1.8.3-beta.13. I'm particularly interested in rebuild times when changing only client files or shared files. 

I'm attaching a log file of starting Meteor (not initial build), and making changes to backend and frontend (I once made a mistake, which is why the error is there). What I notice is that emitResources takes 20-35 seconds, and the biggest single chunk is importScanner#_findImportedModuleIdentifiers. 

The time taken here seems to not vary at all between the initial startup, and subsequent refreshes... It should be able to cache this if the only change I make is to add a console.log to a single file, no need to rescan every single file in the project?

I'm also attaching a log from 1.8.1 with the same code, for comparison. (Problem is prevalent there as well).

[meteor-run-1.8.1.log](https://github.com/meteor/meteor/files/3361567/meteor-run-1.8.1.log)
[meteor-run-1.8.2-13.log](https://github.com/meteor/meteor/files/3361574/meteor-run-1.8.2-13.log)

**Comment by benjamn** [comment]
I've been noticing this function taking longer than usual lately, too. Definitely think something is amiss.
