### ISSUE TITLE
Google signin using Meteor.loginWithGoogle fails in Cordova app

### ISSUE THREAD

**Issue by madc0w** [meteor/meteor#10609]
This issue, which is closed, is still present for me:
https://github.com/meteor/meteor/issues/8253

We tried the solution suggested here
https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients
namely to use loginStyle: "redirect", which had the effect of showing an error message (rather than the silent failure we were seeing). The message is, however, utterly unhelpful:
"SignInResult is null"

Note that Google signin works great in the web app. Not so much with Cordova.

google-oauth@1.2.6
METEOR@1.8.1

**Comment by nikdale** [comment]
Same issue here +1

**Comment by nastaransamui** [comment]
Same Issue still not work 
METEOR@1.8.1

**Comment by paulincai** [comment]
Hi,

could you show your login function please. Does it look anything like this:
(In case you are not familiar with Redux, dispatch is just a "do something" callback/function.)
```
const signInGoogle = () => {
  return dispatch => {
    const { scope, loginStyle } = ServiceConfiguration.configurations.findOne({ service: 'google' })

    console.log(scope, loginStyle)

    Meteor.loginWithGoogle({ requestPermissions: scope, loginStyle, requestOfflineToken: true }, err => {
      if (err) {
        console.log(err)
        if (err !== 'The user canceled the sign-in flow.') {
          toastr.error('Could not sign in', err)
        }
        dispatch({
          type: SIGN_IN_GOOGLE,
          payload: `Error logging Google: ${err}`
        })
      } else {
        dispatch(push('/feeds'))
        dispatch({
          type: SIGN_IN_GOOGLE,
          payload: 'with Google'
        })
      }
    })
  }
}

```

**Comment by nastaransamui** [comment]
@paulincai 
Thanks for the update, I tried same as your sample, still get "SignInResult is null" in all condition, even I created a new app in firebase or tried from cordova-plugin-googleplus, tried "PopUp" and "redirect" all same error "SignInResult is null" point to locallhost or live heroku url.

**Comment by nastaransamui** [comment]
for people that still have the same problem I solve it buy **trySilentLogin** with 3 SHA1 added to the firebase application
`if (Meteor.isCordova) {
            const { scope, loginStyle } = ServiceConfiguration.configurations.findOne({ service: 'google' })
            window.plugins.googleplus.trySilentLogin(
                {
                  'scopes': Meteor.settings.public.google.scope,
                 'webClientId': Meteor.settings.public.google.webClientId,
                  'offline': true 
                },
                console.log('majid'),
                
            );
        }`
