### ISSUE TITLE
--extra-packages flag modifies versions file, affecting version control

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#10615]
We use the `bundle-visualizer` package with the `--extra-packages` flag a lot, but every time we use it, it adds a line to our `versions` file:
```
bundle-visualizer@1.2.2
```

This is then flagged as a change in version control, but we have no intention of committing the change. Building again without `--extra-packages` will remove the line.

It would be nice to include the package in the build without modifying this file, as it is meant as a temporary usage, not something to commit.

**Comment by menewman** [comment]
AFAIK this is still a legit issue, albeit a very minor one
