### ISSUE TITLE
Optimize selection of long poll if websockets recently failed on a client

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#1061]
Filed as an issue at @avital's request:

Pusher has an interesting implementation: on the client they record in local storage which connection method worked last time, so a non-working method doesn't have to be tried again.  (http://blog.pusher.com/how-we-built-pusher20-part-1/)  They invalidate the cache after a time since the client environment might change.

[Engine.IO](https://github.com/learnboost/engine.io#goals) has another interesting option: it _always_ starts off with long polling, and then also attempts a websocket connection in the background.  If the websocket connection is successful, it drops the long poll connection and switches over to the websocket.

**Comment by glasser** [comment]
Nick's last suggestion was implemented a while ago in 0.6.4 (set the `DISABLE_WEBSOCKETS` environment variable).  Having some sort of local storage of sockjs method prioritization (and DDP version for that matter) would still help.

**Comment by hwillson** [comment]
I know this is a feature request and that the outstanding part (caching which connection method worked last) could be interesting to implement, but as part of the old issue cleanup process I vote to close this issue. The original feature request was made more than 3 years ago, and there aren't many outstanding complaints regarding the current websocket/long poll fallback approach.

**Comment by hwillson** [comment]
Closing (for the reasons mentioned in https://github.com/meteor/meteor/issues/1061#issuecomment-258438640). Thanks for posting this originally!
