### ISSUE TITLE
npm WARN on hawk, hoek, boom, snpt, cryptiles

### ISSUE THREAD

**Issue by rooch84** [meteor/meteor#10621]
I've stumbled on an unusual case where out-dated packed are being in stalled when meteor is run, but ONLY when the `--port` flag is specified. 

Steps to run:
- Create a bare meteor package
- Run `meteor --port 3001`
- Look for references to hawk@3.1.3 in the .meteor folder: `grep -R hawk@3.1.3 .`

Further details can be found at 
https://forums.meteor.com/t/npm-warn-when-building-for-production/49494

Meteor version is 1.8.1

/cc @robfallows (who can replicate the issue)

**Comment by klaussner** [comment]
I think this will be fixed in Meteor 1.8.2, thanks to https://github.com/meteor/meteor/commit/df6e2ac43b451bfbcef5102f45e7d81b0d728134. The commit updates `node-pre-gyp`, which depends on `request`, which depended on `hawk` in a previous version (the dependency was removed).

**Comment by filipenevola** [comment]
@klaussner can you confirm if this is fixed?

**Comment by klaussner** [comment]
It looks like `hoek` and the other packages mentioned in the linked forum post are no longer installed.
