### ISSUE TITLE
CircleCI fails because `npx` is not a meteor command.

### ISSUE THREAD

**Issue by nicu-chiciuc** [meteor/meteor#10632]
In commit `06b5f322159a4660c896fc6e` a check was added to ensure that there are no TypeScript errors. Since meteor doesn't have any `npx` commad, CircleCI fails.
Output:
```
#!/bin/bash -eo pipefail
eval $PRE_TEST_COMMANDS;
pushd tools
# Ensure that meteor/tools has no TypeScript errors.
../meteor npx tsc --noEmit
popd
./meteor --get-ready
~/project/tools ~/project
'npx' is not a Meteor command. See 'meteor --help'.
Exited with code 1
```

As an example, [pull request 10631](https://github.com/meteor/meteor/pull/10631) fails.
[Direct link to the build](https://circleci.com/gh/meteor/meteor/35016?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by nicu-chiciuc** [comment]
Was fixed in commit `e299c86ecff80b9870ff6a654831872049ef3da2`

**Comment by benjamn** [comment]
Sorry for the (temporary) annoyance!

**Comment by nicu-chiciuc** [comment]
No worries. Should I continue rebase-ing the pull requests to the latest version of the `release` branch?
