### ISSUE TITLE
MongoDB had an unspecified uncaught exception

### ISSUE THREAD

**Issue by officehax** [meteor/meteor#1064]
I've been trying to start a meteor app on a Linux CentOS server. This is the error that I get, if you need more details, please let me know!:

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ ~/innovation ]]]]]

Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start mongod

MongoDB had an unspecified uncaught exception.
Check to make sure that MongoDB is able to write to its database directory.

**Comment by Shekharrajak** [comment]
If you are in mounted drive then copy your code file to your home directory/file system then do:
 meteor reset and delete the mongodb.lock file .
Now start meteor , it should work.
