### ISSUE TITLE
Dynamic import does not work for external URLs

### ISSUE THREAD

**Issue by bcasselsND** [meteor/meteor#10651]
- [ ] The version of Meteor showing the problem.
  Meteor 1.8.1
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [ ] The operating system you're running Meteor on.
   MacOS
- [ ] The expected behavior.
```
const fullUrl = "https://veritas-test-2019-07-02.s3.amazonaws.com/PublicData/RTK_generated.js";
import(fullUrl).then(m => console.log("global module import fails in Meteor:", m));
```
... should work. Doing it outside of Meteor (using the browser's `import()`) works fine.

Note that my application requires importing from various different AWS buckets. So using ROOT_URL_PATH_PREFIX doesn't seem like a workable option. And the modules are coming from places unrelated to web site root.

- [ ] The actual behavior.
`Error: Cannot find module 'https://veritas-test-2019-07-02.s3.amazonaws.com/PublicData/RTK_generated.js'`

- [ ] A **simple** reproduction!
      https://github.com/NextDroid/meteor-import-bug-2019-07-24

**Comment by benjamn** [comment]
Are you comfortable with your code only working in modern browsers? We could theoretically leave unresolved dynamic `import(...)` expressions untouched, which would allow them to work in browsers that support dynamic import natively.

**Comment by bcasselsND** [comment]
I am comfortable limiting to a smallish set of (modern) browsers. I have a small number of customers; we are doing a very advanced application, so I can tell them what browser(s) to use.

**Comment by bcasselsND** [comment]
Has there been any progress here? Do you have a suggested workaround? (I don't mind using a non-standard version of Meteor, or other sorts of kludges. Ideally the kludge would be temporary.)

**Comment by bcasselsND** [comment]
Found a simple workaround. To get access to the underlying browser's version of `import`:
```const browserImport = new Function("url", "return import(url)");```
Of course, that just hides the call from Babel, or whoever is hijacking the use of `import`.

**Comment by edemaine** [comment]
I just ran into this bug again. It'd be really nice for import from URLs to fall back to the browser's import functionality.
