### ISSUE TITLE
Field conflicts with simultaneous subscriptions (with nested projection)

### ISSUE THREAD

**Issue by johanlef** [meteor/meteor#10657]
Meteor v1.8.1, Mac OS X 10.14.5
[simple reproduction](https://github.com/LEFapps/subscription-test)

**Description**
Two subscriptions on the same publish function:
- the first returns all records and has a field specifier for top-level and nested fields
- the second returns one specific document and has no field specifier

It is important to note that the field specifier contains at least one nested field, eg.:
```JS
{'top.nested_1': 1}
```

**Expectation**
The second subscription returns a document containing **all top-level and nested fields**.

**Result**
The returned document does contain all top-level fields, but the field `top` only contains `nested_1` and not the other fields nested in `top`.

>In the reproduction example, you will see that the field _Gears_ only lists _rear_ which was already fetched for the list items, the other field _front_ is not fetched.

**Comment by deepxlabs** [comment]
Could be this:

Note that the mergebox operates at the level of top-level fields, so if two subscriptions publish nested fields (e.g. sub1 publishes doc.a.b = 7 and sub2 publishes doc.a.c = 8), then the “merged” document might not look as you expect (in this case doc.a = {c: 8}, if sub2 happens second).

https://guide.meteor.com/data-loading.html

**Comment by johanlef** [comment]
In my case:

- sub1 publishes `doc.a.b = 7`
- sub2 should publish `doc.a = { b: 7, c: 8 }` and happens always second

**End result of doc.a remains incomplete as in sub1.**

_Ah, the rendering might have to do with floats not clearing (I'll fix that), check the console for the correct data!_

**Comment by johanlef** [comment]
Similar to #3764 which is now [feature request 67](https://github.com/meteor/meteor-feature-requests/issues/67).
