### ISSUE TITLE
1.5.4.2 - core-js npm module not found in deployed app

### ISSUE THREAD

**Issue by RavDanny** [meteor/meteor#10652]
Meteor v. 1.5.4.2 running on Ubuntu 16.04.6 LTS.

Deployed my app using meteor-up. The browser displayed a blank screen and in the console had the message:
```
Uncaught Error: The core-js npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save core-js

    at runtime.js (832c4d729492423edbe84f521d8f9169dd68a01e.js?meteor_js_resource=true:29)
    at l (832c4d729492423edbe84f521d8f9169dd68a01e.js?meteor_js_resource=true:9)
    at e (832c4d729492423edbe84f521d8f9169dd68a01e.js?meteor_js_resource=true:9)
    at 832c4d729492423edbe84f521d8f9169dd68a01e.js?meteor_js_resource=true:29
    at 832c4d729492423edbe84f521d8f9169dd68a01e.js?meteor_js_resource=true:29
```
Core-js was not part of the development app. I followed the above instruction, which installed core-js v.3.1.4 and deployed again, but it didn't make any difference.

Not sure if this is at all related, but the console also said:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
/favicon.ico:1 
```
although the `favicon.ico` file was in the top level of the development app.

I wasn't sure whether to raise this here or on Meteor-up, but since I've seen a similar issue raised regarding Meteor-up that didn't end up being Meteor-up specific, I thought there was a reasonable chance that this was the same.

**Comment by StorytellerCZ** [comment]
`/favicon.ico` should be in `public/` folder.

**Comment by RavDanny** [comment]
I solved it by creating a new app, reinstalling the packages and re-adding the code.
