### ISSUE TITLE
Provide ENV variable to repository folder

### ISSUE THREAD

**Issue by SimonSimCity** [meteor/meteor#10666]
It would be nice (and I guess not all too hard) to add an ENV variable which contains the path to the actual project repository. This would help a lot for testing tools. Here are some use-cases where this could be well suited:

* https://github.com/serut/meteor-coverage - the ENV variable `COVERAGE_APP_FOLDER` could get a good default value or could be set to a relative path
* https://github.com/meteortesting/meteor-mocha#write-tests-to-a-file - the ENV variable `SERVER_MOCHA_OUTPUT` could get a good default value or be set to a relative path
* Would ease dynamic imports of test-files :wink: https://github.com/meteor/meteor/pull/9714#issuecomment-519398680

**Comment by klaussner** [comment]
Sounds like a feature request. 🙂 Can you please open an issue in https://github.com/meteor/meteor-feature-requests instead?
