### ISSUE TITLE
DDP changed message treats $unset differently

### ISSUE THREAD

**Issue by ggerber** [meteor/meteor#10669]
An $unset operation on a document does not get updated on the client when using publication's changed hook.

Rob Fallows mentioned that I should raise this issue on the Meteor repo.
https://github.com/robfallows/tunguska-reactive-aggregate/issues/15#issuecomment-520411855

Steps to reproduce:
start with a new meteor project (1.8):
meteor create --bare test

Contents of test/server/main.js
```
import { Meteor } from "meteor/meteor";
import { Mongo } from "meteor/mongo";

const Things = new Mongo.Collection("Things");

Things.insert({a:1,b:2});
Things.insert({a:3,b:4});

Meteor.publish("testpub", function testpub() {
  const self = this;

  const thingsQuery = {};
  const fields = {
    a: 1,
    b:1
  };

  const collectionHandle = Things.find(thingsQuery, { fields }).observe({
    added(newThing) {
      const {_id} = newThing;
      console.log('added');
      self.added('ClientCollection', _id, newThing);
    },

    changed(newThing, oldThing) {
      const {_id} = newThing;
      console.log('changed');
      self.changed('ClientCollection', _id, newThing);
    },

    removed(oldThing) {
      const {_id} = oldThing;
      console.log('removed');
      self.removed('ClientCollection', _id);
    }
  });
  self.ready();

  self.onStop(() => {
    collectionHandle.stop();
  });
});
```

Contents of test/client/main.js
```
import {Meteor} from 'meteor/meteor';
import {Mongo} from 'meteor/mongo';
import {Tracker} from 'meteor/tracker'

const ClientCollection = new Mongo.Collection('ClientCollection');

Tracker.autorun(() => {
  const subscription = Meteor.subscribe('testpub');
  const isloading = !subscription.ready();

  const resp = {
    isloading
  };

  if (!isloading) resp.docs = ClientCollection.find({}).fetch();

  console.log('resp', resp);
});
```

Contents of test/client/main.html
```
<head>
  <meta charset="utf-8" />
  <title>Example</title>
  <meta name="description" content="Example" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
</head>

<body>
  <div id="react-root"></div>
</body>
```
In the mongo console you can do an $unset like so:
```
db.Things.update({a:1},{$unset:{b:''}})
```
The server picks up the 'changed' event, but the change is not pushed to the client.

**Comment by mitar** [comment]
Please create a reproduction as a stand-alone repository which can just be cloned.

**Comment by ggerber** [comment]
stale-botting doesn't make the issue dissappear from the codebase

**Comment by mitar** [comment]
But not providing a reproduction in half a year makes sense to close the issue.

**Comment by ggerber** [comment]
If you read the post you can see how to reproduce the issue.

Rob Fallows also confirmed the issue.

I do not work with github, so I dont know how to fork.

What I did was to show how to create it as a normal meteor user would.

**Comment by mitar** [comment]
Sadly, this is not a valid reproduction. Reproduction is a git repository which one can run directly. Developers have more important work than manually following the steps you are describing. Just follow your steps yourself, create a repository with results of your steps, and then share a link to that repository here.

If you didn't understand what "Please create a reproduction as a stand-alone repository which can just be cloned." meant or asked of you, you could have asked for clarification.

**Comment by ggerber** [comment]
Hi Mitar,

Can you point me to a resource that shows how to make such a reproduction
and link upload it to wherever Meteor wants it?

I also do not want to spend unnecessary time trying to learn a tool that I
hardly use.

Thanks

**Comment by mitar** [comment]
See [here for more information](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor).

**Comment by ggerber** [comment]
Hi Mitar,

Please see below the repo:
https://github.com/ggerber/meteor-issue-10669

Thanks

**Comment by mitar** [comment]
You should be using `observeChanges` and not `observe` there.
