### ISSUE TITLE
[Meteor 1.8.1] Unable to run meteor npm install on CircleCI xcode 10.1.0

### ISSUE THREAD

**Issue by srashish** [meteor/meteor#10676]
I'm not able to run meteor npm install on circleci machine running xcode version 1.8.1. This started to come since yesterday.

```meteor reset
rm -rf node_modules
meteor npm install
^D^DProject reset.
npm ERR! path /Users/distiller/.npm/_locks
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall open
npm ERR! EISDIR: illegal operation on a directory, open '/Users/distiller/.npm/_locks'

npm ERR! A complete log of this run can be found in:
npm ERR!     `/Users/distiller/.npm/_logs/2019-08-20T10_15_15_914Z-debug.log'```

**Comment by srashish** [comment]
This got resolve with a hot fix from meteor

**Comment by ziedmahdi** [comment]
I am facing the same problem on macOS Catalina. It's a fresh meteor installation. I even run meteor update but I got

>The latest version of Meteor, 1.8.1, is already installed on this computer. Run
'meteor update' inside of a particular project directory to update that project
to Meteor 1.8.1

I think it's a user permissions problem.

**Comment by ziedmahdi** [comment]
For any one facing the same problem, running `meteor npm cache clean --force` solved mine
