### ISSUE TITLE
Sourcemaps on development build with ROOT_URL

### ISSUE THREAD

**Issue by joaomframos** [meteor/meteor#10671]
As discussed [about a year ago,](https://github.com/meteor/meteor/issues/9747) I have an application that runs on top of other websites performing several external requests.

Although Meteor doesn't currently support Sourcemaps for production, there are specific use cases where we are required to test a development build on top of edge cases found on client's websites.

For the the first time ever, we noticed a slowdown on the client's webpage which would affect every user on that platform. We managed to pinpoint the root cause of the slowdown to the development sourcemaps being requested to the client's webserver, spamming it. Probably it's nothing but a really weak webserver but one of our main goals it to never negatively impact a client's webpage but if sourcemaps are set up like this, we can never achieve that goal.
Also, we have been forced to develop without sourcemaps for months already and having this issue fixed would also improve our development workflow.

In order to pinpoint the issue I forked the project and performed the changes locally. The changes were simple and only in two files for now: tools/isobuild/isopack.js and tools/isobuild/bundler.js

I still need to find out if there's a way to fix the imports from node_modules' CSS (like Google's Material CSS) which also enforce a sourcemap request to the current page instead of targeting the domain where the app is running.

The changes are mostly using ROOT_URL if available - which is our use case - but I'm not aware of every use case Meteor covers and that's where I require your help before submitting a PR.

This is one [example of a change to a meteor tool.](https://imgur.com/MHgzwTS)

Which results in a change from: 
//#sourceMappingURL=/dynamic/imports/[PATH_TO_FILE]/6f1a7e62594dde76996770d7b428fae06ad86cef.map

to:
//#sourceMappingURL=[ROOT_URL]/dynamic/imports/[PATH_TO_FILE]/6f1a7e62594dde76996770d7b428fae06ad86cef.map

these changes have been performed on top of Meteor 1.8.1.

**Comment by HugoMag** [comment]
Any news regarding this?

**Comment by joaomframos** [comment]
Sorry @filipenevola for the poke, but are there any updates regarding this?
I would like to at least know if there are any plans to address this issue.

**Comment by filipenevola** [comment]
Hi @joaomframos I would be glad to review your PR about this.
