### ISSUE TITLE
[1.8.1] Async methods are unblocked without specifying this.unblock()

### ISSUE THREAD

**Issue by jeffm24** [meteor/meteor#10672]
I'm not sure sure whether or not this is intended behavior, but I've noticed that methods defined as async on the server are not being awaited, which effectively makes them unblock as if you called this.unblock() within them. This does not happen if you use Promise.await() instead of native await. You can see this is the following example:

Server:
```javascript
const asyncTimeout = ms => new Promise(resolve => setTimeout(resolve, ms));

Meteor.methods({
    async unblockedMethod() {
        await asyncTimeout(10000);
        return 'unblockedMethod';
    },
    blockedMethod() {
        Promise.await(asyncTimeout(10000));
        return 'blockedMethod';
    },
    anotherMethod() {
        return 'anotherMethod';
    }
});
```

Client:
```javascript
function testAsyncAwait () {
    Meteor.call('unblockedMethod', console.log);
    Meteor.call('anotherMethod', console.log);
}
function testPromiseAwait() {
    Meteor.call('blockedMethod', console.log);
    Meteor.call('anotherMethod', console.log);
}
```

Running the first function will result in 'anotherMethod' logging immediately, and then 'unblockedMethod' logging in 10 seconds. On the other hand the second function works as you would expect; the Promise.await blocks the second method from running until the first has finished, so you see 'blockedMethod' log before 'anotherMethod'.

Because of the existence of this.unblock(), it seems like unintended behavior to be able to achieve the same result without explicitly calling it. A very easy fix that I've been employing is to override the Meteor.methods function to wrap all method calls in a Promise.await() call. This ensures that defining them as async will not cause them to unblock unless this.unblock() is called. It seems like this would be pretty easy to implement into the method handling code, or at least this behavior should be documented in the official Methods documentation.

**Comment by zodern** [comment]
This will need to be fixed for some methods in core packages to be able to use async/await.

**Comment by denihs** [comment]
I suspected this issue was going to be solved on this [PR](https://github.com/meteor/meteor/pull/12196), and it was. 

Before, this function [maybeAuditArgumentChecks](https://github.com/meteor/meteor/pull/12196/files#diff-173e69ea0353a765b98017d67abc45ec7ce1449178466dc74738324db83f9183L765-R791), was returning a Promise (when the method was declared async) without waiting for the result.

**Comment by denihs** [comment]
We're going to check if it's the case and follow up here later.

**Comment by nesbtesh** [comment]
@jeffm24 but this is how node js is suposed to work, why did you change it?
