### ISSUE TITLE
App.addResourceFile cannot handle relative paths for the source

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#10684]
Undocumented feature `App.addResourceFile` implies that it can handle a src **path** in it's documentation [here](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L770-L777).

But it does not work, it can only handle a source file name.

Maybe @eskan, can take a look?

### Details
This [code](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L393-L416) looks like the culprit:
```javascript
  configureAndCopyResourceFiles(resourceFiles, iosElement, androidElement) {
    _.each(resourceFiles, resourceFile => {
      // Copy file in cordova project root directory
      var filename = path.parse(resourceFile.src).base;
      files.copyFile(
        files.pathResolve(this.projectContext.projectDir, resourceFile.src),
        files.pathJoin(this.projectRoot, filename));
      // And entry in config.xml
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "android")) {
        androidElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
      }
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "ios")) {
        iosElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
      }
    });
  }
```

Essentially, the code copies from it's source location
```javascript
files.pathResolve(this.projectContext.projectDir, resourceFile.src)
```
then places it at the root of the cordova build:
```javascript
files.pathJoin(this.projectRoot, filename))
```
Which is fine, but then it creates a `resource-file` directive that is looking for the resource file relative to the root of the build tree:
```javascript
        androidElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
```
So if you place your resources at the root of the meteor project tree all will work.  To make it work with resources in folders either:
1. Need to make the files copy to a path relative to the cordova build root.
2. Change the `resource-file` directive to grab the file from the root.

Either way there is the potential for collision, but I think I like # 1.

**Comment by brucejo75** [comment]
PR #9748 has the problem.

**Comment by eskan** [comment]
hum ..if i remember copy a file is done in 2 steps .. first the resource should be copied to the cordova build directory then file is specified as a resource in config.xml to be copied to the right place in platform build. I see i copy file in the second step to the root, i understand it's not a good choice. What do you think is the best way to do this ? How to specify intermediate directory ?

**Comment by brucejo75** [comment]
How about:

1. copy the file with the meteor project path into the `/resources` folder.
2. then copy from the resources folder to the target

```javascript
  configureAndCopyResourceFiles(resourceFiles, iosElement, androidElement) {
    _.each(resourceFiles, resourceFile => {
      // Copy file int cordova project root/resources directory
      files.copyFile(
        files.pathResolve(this.projectContext.projectDir, resourceFile.src),
        files.pathJoin(`${this.projectRoot}/resources`, resourceFile.src));
      // And entry in config.xml
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "android")) {
        androidElement.element('resource-file', {
          src: `resources/${resourceFile.src}`,
          target: resourceFile.target
        });
      }
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "ios")) {
        iosElement.element('resource-file', {
          src: `resources/${resourceFile.src}`,
          target: resourceFile.target
        });
      }
    });
  }
```

You may have to make sure the full path is in place before doing the copy, or maybe that copy function will create the full path if necessary?

**Comment by brucejo75** [comment]
Just saw your PR.  It looks good.
