### ISSUE TITLE
Feature Request:  Session.toggle('variable')

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#1068]
Hi there,
Just a simple feature request to expand the Session API, and to add a toggle() function for boolean variables.  I've written a super tiny helper function that I use throughout my apps:

``` js
toggleSession = function(session_variable){
  if(Session.get(session_variable)){
     Session.set(session_variable, false)
  }else{
     Session.set(session_variable, true)
  }
};
```

I just now started yet another applet, and went to toggle a session, and realized I needed to copy over one of my libraries of helper functions, and then I thought...  'you know, I bet a bunch of other people are dealing with this also, so maybe I should just log a ticket, and see if we can get this elevated this syntax to something like `Session.toggle()`. 

Might need to detect variable type, in case a string or object gets passed in.  But otherwise, pretty straight forward.

**Comment by dotnetwise** [comment]
+1, this would be very handy

**Comment by awatson1978** [comment]
This functionality is available in either of the following packages:

clinical:extended-api
clinical:session-extended-api

https://atmospherejs.com/clinical/session-extended-api
