### ISSUE TITLE
Cordova-iOS UIWebView

### ISSUE THREAD

**Issue by flean** [meteor/meteor#10683]
New warning from apple, I"m using WKwebview but Cordova-iOS has it in code which creates this error.

https://github.com/apache/cordova-ios/issues/661

Can we get a quick patch for this once it's resolved on the Cordova package side? I'd like to keep being able to publish my apps.

Thanks

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview 2 for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by derman10** [comment]
same problem here.
