### ISSUE TITLE
[1.8.1 and 1.8.2-beta.17] build stuck in web.browser stage

### ISSUE THREAD

**Issue by agolomoodysaada** [meteor/meteor#10680]
### This bug report should include:
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
Last working version was 1.6.1
- [x] The operating system you're running Meteor on.
Linux and macOS
- [x] The expected behavior.
The build should complete with no issues
- [x] The actual behavior.
The build gets stuck. Here's the verbose log
```
   START 1 building for web.browser          /
     START 2 linking the program
     DONE 2 linking the program took 11
     START 2 processing files with ecmascript (for target web.browser)
     DONE 2 processing files with ecmascript (for target web.browser) took 7
     START 2 processing files with static-html (for target web.browser)
     DONE 2 processing files with static-html (for target web.browser) took 16
     START 2 processing files with meteor (for target web.browser)
     DONE 2 processing files with meteor (for target web.browser) took 19
     START 2 processing files with fourseven:scss (for target web.browser)
     DONE 2 processing files with fourseven:scss (for target web.browser) took 602
     START 2 minifying app stylesheet        \
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
     DONE 2 minifying app stylesheet took 233
     START 2 minifying app stylesheet
     DONE 2 minifying app stylesheet took 26
     START 2 minifying app stylesheet        /
     DONE 2 minifying app stylesheet took 80
     START 2 minifying app stylesheet
     DONE 2 minifying app stylesheet took 13
     START 2 minifying app stylesheet        -
     DONE 2 minifying app stylesheet took 82
```
No logs show up after that last line.

- [ ] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)
I cannot share code as it's private.

**Comment by vsheyanov** [comment]
Same for me. 
Upgrading our project to 1.8.1 from 1.8 leads to a build that gets stuck at `building for web.browser          /`.
I had `simple-todos` with an old meter version, upgrading it to 1.8.1 didn't lead to any issues.
How these projects differ:
- our project is huge, simple-todos is uber simple;
- our project was started ~ 3 years ago, .finished-upgraders has some entries;
- something else?..

Console output: https://gist.github.com/vsheyanov/bafa0aa03c3134ea52d7c32dd8b72521
