### ISSUE TITLE
A warning about "caniuse-lite" prints during minification

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#10682]
minifier-css depends recursively on `browserslist`, which you can see in its checked-in shrinkwrap file.

browserslist has [this code](https://github.com/browserslist/browserslist/blob/0ae7155a6c7d8f58eaeb3ea450c21bec76de2763/node.js#L291-L313) to print a warning if its dependency `caniuse-lite` is more than 6 months out of date. It was last updated in Meteor in February so it is printing for all users who minify right now.

I don't even know if minifier-css takes advantage of anything provided by browserslist or caniuse-lite. I suggest it should set the `$BROWSERSLIST_IGNORE_OLD_DATA` environment variable to disable this warning.

**Comment by benjamn** [comment]
Should be mitigated by c2499b1f21ef195f31652deac7443cc33b98af66, which will be released as part of Meteor 1.8.2. Disabling the warning is tempting, but I don't mind the additional incentive to keep these packages up-to-date.

**Comment by evolross** [comment]
FWIW I'm still seeing this after updating my app to Meteor 1.9.

**Comment by sunyamare** [comment]
Seeing this in Meteor 1.10.1

**Comment by linegel** [comment]
Appears in Meteor 1.10.1

**Comment by Natas0007** [comment]
Still in Meteor 1.10.2.  I've disabled with the env var, but just giving a heads up.

**Comment by afrokick** [comment]
There is PR https://github.com/meteor/meteor/pull/11075 for updating the version of PostCSS to resolve this issue.

**Comment by afrokick** [comment]
Will be released in 1.10.3 Thanks @filipenevola

**Comment by filipenevola** [comment]
minifier-css@1.5.1 is published.

**Comment by iancwinter** [comment]
Still there in 1.11. :-(

**Comment by afrokick** [comment]
Ok, i’ll update it later to use the latest version of PostCSS

**Comment by filipenevola** [comment]
Published minifier-css@1.5.3.                 

`meteor update minifier-css` should fix your warning.

**Comment by iancwinter** [comment]
Hmm… I already have standard-minifier-css@1.6.0 as part of Meteor 1.11 so not sure a downgrade to 1.5.3 would fix things (and may introduce other incompatibilities). Unless minifier-css is different to standard-minifier-css.

**Comment by afrokick** [comment]
@iancwinter you should update `minifier-css`, not `standard-minifier-css`

**Comment by afrokick** [comment]
@filipenevola so, we need to update standard-minifier-css to use the latest version of minifier-css, right?

**Comment by filipenevola** [comment]
Yeah, `meteor update standard-minifier-css` is also necessary (1.6.1 was published).

But I believe this warning can come back again and again, then we need to always bump these versions when PostCSS releases a new version.
