### ISSUE TITLE
Cordova android platform using gradleVersion 4.1.0 How to update?

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#10689]
Cannot figure out how to update gradle for meteor cordova builds.

### Environment
Meteor: 1.8.1
Platform: android

### Issue
I have installed gradle v5.5.1 via `brew install gradle` as described in the [mobile docs](https://guide.meteor.com/mobile.html#installing-prerequisites-android).

In my generated `build.gradle` it still refers to an older version of gradle:
```gradle
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral();
        jcenter()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.1.0'
}
```

The build script opens with Gradle 5.5.1 but the first thing `.meteor/local/cordova-build/platforms/android/app/build.gradle` does is to download gradle v4.1.0 and stuff it in `~/.gradle/wrapper/dists/`

And then use the older version of gradle `4.1.0`.

How can I update the version of gradle used by the cordova build?

I have plugins that are starting to use new gradle features.

**Comment by crapthings** [comment]
change this to

> classpath 'com.android.tools.build:gradle:3.3.2'

```bash
export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
meteor build android-device
```

**Comment by brucejo75** [comment]
Thanks @crapthings,

But I would love to change `classpath` but I cannot figure out how to do it.  `build.gradle` is generated by Meteor.

Any tips?  On where I can change that in a Meteor project?

Thanks!
