### ISSUE TITLE
TEST_CLIENT=0 will still build client and refresh

### ISSUE THREAD

**Issue by eric-burel** [meteor/meteor#10690]
Hi,
Server side tests are longer to start than necessary when using TEST_CLIENT=0. According to the log, the app is built for browser too, and the client get refreshed on changes, which is unnecessary.
Preventing this unnecessary build would provide a better testing experience.

- Meteor 1.8.1
- Ubuntu 18.04
- Expected: build only the server code when TEST_CLIENT=0
- Actual: app is also built for browser and client is refreshed

**Comment by eric-burel** [comment]
Not stale

**Comment by filipenevola** [comment]
@eric-burel thanks, I just labeled as pinned then stale bot will ignore it 😉

**Comment by sebakerckhof** [comment]
I could tackle this as part of https://github.com/meteor/meteor/pull/10824

**Comment by eric-burel** [comment]
It's from `meteor-mocha` actually, so maybe not a Meteor issue per se. As far as I understand how tests work, it seems that the test runner is triggered after the app is built and running, so it can't take control on the build process.

So maybe it could be interesting to handle this env variable directly in Meteor, in order to make the build faster during tests ?

**Comment by sebakerckhof** [comment]
I'd rather keep the same semantics already used by https://github.com/meteor/meteor/pull/10824 (using an `--exclude-archs` cli argument). But it should achieve what you want.

**Comment by eric-burel** [comment]
Sounds great indeed
