### ISSUE TITLE
Remove LaunchScreen from web clients

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#10702]
`LaunchScreen` is really used just on Cordova. For web clients it contains some code, but the code is just a placeholder and it looks even that it is expected just to work with Blaze.

I would simply remove all that code for the client as it is just adding weight to the bundle.

Moreover, effective loading screens on the web have to be made into static HTML content rendered by the server anyway, so that they can be shown even before JavaScript starts loading. So it cannot be made in JavaScript, to show the loading of primarily JavaScript.

Tested on Meteor 1.8.1.

**Comment by mitar** [comment]
Still relevant.

**Comment by mitar** [comment]
Still relevant.

**Comment by StorytellerCZ** [comment]
@mitar please check #11371 if that is what you had in mind.

**Comment by mitar** [comment]
Awesome!

**Comment by StorytellerCZ** [comment]
Will be released together with Meteor 2.3
