### ISSUE TITLE
static-html package should probably be moved back to core packages

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#10706]
It is not really possible to use Meteor without at least `static-html` package. Even `meteor create --react` uses it. But `static-html` is a non-core package and also it pull in many Blaze as dependencies. This seems that the package should be decoupled from Blaze and brought into core packages.

**Comment by mitar** [comment]
Still relevant.

**Comment by red-meadow** [comment]
Why not? HTML can be injected with JS. Also, [Svelte compiler](https://github.com/meteor-svelte/meteor-svelte) can be configured to handle .html files, and in that case `static-html` _must_ be removed to avoid `error: conflict: two packages are both trying to handle *.html`.

**Comment by mitar** [comment]
> Why not? 

This is why I wrote "at least". I am not saying you have to use it, you can use something else (any other compiler for .html) but you need one plugin for .html and it is strange that core does not have any.

**Comment by StorytellerCZ** [comment]
I'm for this.

**Comment by StorytellerCZ** [comment]
Fixed in Meteor 2.4.
