### ISSUE TITLE
Support mongodb findAndModify on server

### ISSUE THREAD

**Issue by mcbain** [meteor/meteor#1070]
**_5 Upvotes**_

**Comment by ricardodovalle** [comment]
:+1:

**Comment by MichaelJCole** [comment]
>  "There's no advantage to building an extra wrapping layer around every single Mongo feature unless we're actually adding Meteor-specific details."

We don't have to do every feature, just the important ones :-)  If you're going to promise a Meteor.Collection, it should use the features of the database needed for concurrency.

**Comment by craigbennett1981** [comment]
+1

**Comment by digz6666** [comment]
+1

**Comment by koolaang** [comment]
+1

**Comment by danwild** [comment]
+1

**Comment by joetidee** [comment]
+1

**Comment by yanndebelgique** [comment]
+1

**Comment by strobox** [comment]
+1  and for ones who use *findAndModify* for index generation or other atomic operations don't forget important warning from MongoDB officials:  [**Upsert and Unique Index**](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/#upsert-and-unique-index)

**Comment by sveinburne** [comment]
+1

**Comment by valentinvichnal** [comment]
#7694

**Comment by mitar** [comment]
While MongoInternals.NpmModule exists on the server, there is no support in Minimongo for it. I think this should be reopened and make official. `findAndModify` is really not "every single feature" but a pretty common one.

**Comment by mitar** [comment]
(Definitely more often used than geo queries which are supported.)

**Comment by mitar** [comment]
Reopening to make something which is supported both on client and server, and because it has many many upvotes.

But with MDGs focus on Apollo, I do not think this will happen by them. So pull requests encouraged.

**Comment by holmrenser** [comment]
+1

**Comment by Micjoyce** [comment]
At meteor 1.4.2.1
`
 { lastErrorObject: { updatedExisting: true, n: 1 },
 value: { _id: 'seer_username', seq: 1000005 },
I20ok: 1 }
`
I use it like this: 
`
if(Meteor.isServer){
  Future = Npm.require('fibers/future');
  Meteor.Collection.prototype.findAndModify = function(args){
    if(!this._name)
      throw new Meteor.Error(405,"findAndModify: Must have collection name.");
    if(!args)
      throw new Meteor.Error(405,"findAndModify: Must have args.");
    if(!args.query)
      throw new Meteor.Error(405,"findAndModify: Must have query.");
    if(!args.update && !args.remove)
      throw new Meteor.Error(405,"findAndModify: Must have update or remove.");
    var colname = this._name;
    var q = {};
    q.query = args.query;
    if(args.sort === undefined) q.sort = {};
    if(args.update)
      q.update = args.update;
    if(args.remove)
      q.remove = args.remove;
    q.options = {};
    if(args.new !== undefined) q.options.new = args.new;
    if(args.remove !== undefined) q.options.remove = args.remove;

    var db = MongoInternals.defaultRemoteCollectionDriver().mongo.db;
    var fut = new Future();

    db.collection(colname).findAndModify(
      q.query,
      q.sort,
      q.update,
      q.options,
      function(err, result) {
        if(err)
          fut.return(undefined);
        else
          fut.return(result);
      }
    );
    return fut.wait();
  };
}

this.CounterDB = new Mongo.Collection("counter_db");
CounterDB.allow({
  insert: function(){
    return true;
  },
  update: function(){
    return true;
  },
  remove: function(){
    return true;
  }
});
`

`
getIncUniqueByName = function(name) {
  let ret = CounterDB.findAndModify({
    query: {
      _id: name
    },
    update: {
      $inc: {
        seq: 1
      }
    },
    "new": true
  });
  console.log(ret, ret.seq, "'--=====---'")
  return ret.seq.toString();
}

getIncUniqueByName("seer_username")
`
I got Error : 
`
 { lastErrorObject: { updatedExisting: true, n: 1 },
 value: { _id: 'seer_username', seq: 1000005 },
I20ok: 1 }
`

**Comment by smeijer** [comment]
I don't understand it must take almost 4 years to implement this. This kind of functionality is essential when writing solid distributed "cron" jobs.

**Comment by derwaldgeist** [comment]
+1

**Comment by abernix** [comment]
If you're just here to "+1" the issue (or any issue) without adding any meaningful conversation, please use GitHub's 👍 emotion on the original post.  They are easy to search by and count in GitHub search and it avoids the ~2000 e-mails that are sent out for a "+1" which has no other value.

Just as a reminder, on the server side, you can use the (documented) [`Mongo.Collection#rawCollection()`](https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection) to access any Mongo collection method.  If there's not any additional Meteor functionality necessary to use a Mongo method, then that will likely be the preferred method.

If client functionality for `findAndModify` is what you need then, that would necessitate a change on the Meteor side of things to implement it within MiniMongo.  There are a lot of upvotes here, but it's not really clear how many people need this on the client-side.

Regardless, this is marked `pull-requested-encouraged`.  If you're interested, open the code, take a look and help spec out the changes necessary to make this work and consider making a [contribution](https://github.com/meteor/meteor/blob/devel/Contributing.md#making-changes-to-meteor-core) to Meteor instead of being confused why it's not done.

**Comment by mitar** [comment]
Client side would be great as well. Meteor's code isomorphism on client and server is a really important feature. So +1 this comment if you would like to see client side as well. :-)

**Comment by yanickrochon** [comment]
I do not understand the need for client side. Modifying collections should be made through methods, and received updates through Tracker, no? Is this only because of optimistic updates?

**Comment by mitar** [comment]
Yes, but Meteor methods can run both on the client and server. And the beauty is that the same code and same Mongo operations exist both on client and server. This helps with latency compensation.

**Comment by mitar** [comment]
I realized that one reason why this would be useful to have as a Meteor API (in contrast of just running it on `rawCollection`) is that returned document would  be send through `transform` as you are used to in Meteor.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20mongodb%20findAndModify%20on%20server&body=Migrated%20from:%20meteor/meteor%231070) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
