### ISSUE TITLE
Cordova: Hot Code Push (HCP) not working with page behind HTTP Basic Auth

### ISSUE THREAD

**Issue by DanielDornhardt** [meteor/meteor#10715]
Meteor Version: METEOR@1.8.1
Platform: iOS - yes, problem, Android: ?

We're building a Meteor / Cordova app and of course HCP is the Bees' Knees!

Now we tried to protect our apps' web application with a HTTP Basic Auth username + Password.

We build our mobile apps like this:

    meteor build ../build --architecture os.linux.x86_64 --server https://username:password@app.ourdomain.com --mobile-settings ./mobile-settings-live.json --directory

And we use `kit:basic-auth` ( https://atmospherejs.com/kit/basic-auth ) as a basic HTTP Basic Auth package by adding the auth settings to our meteor settings as shown in the package description, eg.:

    // settings.json
    {
      "basicAuth": {
        "username": "username",
        "password": "password"
      }
    }

To our general delight, this works! :) Even for the Cordova apps.

Or so we thought.

It worked, but the Hot Code Push didn't happen anymore.

After running the iOS App locally against our production system, I could see that the HCP mechanism received 401 messages ("access denied") when trying to request the `https://app.ourdomain.com/` (not quite sure right now about the full path) `__cordova/manifest.json` (or so).

Anyhow, it seems that the HTTP Request from the local HTTP Server Package doesn't include / send the Auth Headers.

Is there a possibility that

a) somebody could fix this? I guess it shouldn't be too hard I guess, but as these things go, I'm not sure of course, and also this probably needs to be checked against Android and iOS

b) maybe we can do a workaround by ourselves? I reckon if we could send out one request with the proper HTTP Auth data using the same connection the HCP code uses to fetch the data it might stay authenticated? Or maybe there is another way to finagle the username:password into the rootUrl of the HTTP Server Package?

2 more things:

-> I'm a little starved on time right now, sorry, if it would be useful I could try a reproduction next week.

-> I didn't check this on Android yet, this is also something I could try as well of course.

Thanks and I'm looking forward to any feedback of course! Thank you for the best ever Web Application Framework! :)

**Comment by brucejo75** [comment]
Hi @DanielDornhardt, did you get this sorted out?

**Comment by filipenevola** [comment]
@brucejo75 and @DanielDornhardt if you make a PR supporting optionally user/password basic authentication on manifest requests I would be happy to review and merge.
