### ISSUE TITLE
Meteor Cordova ongoing support?

### ISSUE THREAD

**Issue by wildhart** [meteor/meteor#10718]
This [post ](https://github.com/meteor/meteor/pull/10527#issuecomment-530067644)from @benjamn has me and others very concerned:

> Although we have done our best to keep Cordova working for the Meteor developers who depend on it, Cordova has a huge API beyond our control that isn't very backwards compatible from version to version. My honest recommendation would be to use React Native with Meteor if you can, and keep in mind that Cordova is not synonymous with Meteor.

One of the things I love about Meteor is the Cordova integration - I have one successful project with iOS and Android apps, and a 2nd project is just about to start beta testing.

I've regularly recommended Meteor in the forums for cross-platform development - I personally see that as one of Meteor's true strengths even though I know they aren't 'synonymous'.  It would be a real shame to lose that ability and have to rewrite some apps from scratch.

If, as this quote suggests, Cordova may at some point stop being supported within Meteor, then the community need as much warning of this as possible, so that we can develop a community maintained Cordova integration, or a clear guide of how to do-it-yourself.

I've created this issue so that hopefully we can get some official guidance/warning/reassurance/timeline and then discuss how to respond to that as a community...

**Comment by DanielDornhardt** [comment]
Hi, yes, that would indeed be a big surprise and not good for current development efforts based on cordova... the integration has always been tight + has always worked out one way or the other, if this wouldn't be the case anymore it'd indeed be very sad.

**Comment by evolross** [comment]
Here's hoping that with the new acquisition by Tiny, Cordova support will once again be a first class citizen in the Meteor universe.

**Comment by wildhart** [comment]
> I might hang out for a few months and see what happens.

That's precisely why I raised this issue.  Since Ben's comment quoted above there can only FUD surrounding the future of Cordova in Meteor.

We need some indication from Tiny ASAP so we can either get started on Plan B, or get back to developing on the platform we love.  Until then I can no longer and in good conscience continue to recommend and support Meteor in the forums for cross platform app development [[1]](https://forums.meteor.com/t/sign-in-page-for-an-android-application/49977/5) [[2]](https://forums.meteor.com/t/does-meteor-crash-alot/47874/6) [[3]](https://forums.meteor.com/t/best-practices-for-cross-platform-meteor-apps-with-a-single-codebase/48404/15) [[4]](https://forums.meteor.com/t/is-mobile-app-development-using-meteor-not-recommended/43809/7) [[5]](https://forums.meteor.com/t/cordova-ios-app-icon-multitasking-app-switcher-and-backgrounding-app-shows-different-icon/50274/2) [[6]](https://forums.meteor.com/t/is-it-possible-to-do-a-3rd-party-redirect-back-to-mobile-app/49949/2) [[7]](https://forums.meteor.com/t/meteor-cordova-and-play-store/50283/2)

**Comment by KoenLav** [comment]
I think it would be a good idea to have Cordova less tightly coupled with Meteor.

Basically Cordova support in Meteor core currently entails:
- CLI support (incl. config files);
- Meteor Cordova Webapp plugin;
- Am I missing anything?

I think a migration path should be researched for dropping the CLI support (or at least migrating it away from core) and including the Meteor Cordova Webapp plugin manually.

**Comment by rj-david** [comment]
Agreeing on the idea of moving Cordova out of the core of Meteor.

**Comment by filipenevola** [comment]
Hi @wildhart @DanielDornhardt @evolross @KoenLav @rj-david, sorry for the long delay, we (Meteor Software Ltd., the new company behind Meteor, a Tiny company) want to keep Meteor working very well and up-to-date with Cordova.

That said, I don't believe we need to remove things out of core right now but I'm open to specific suggestions.

I'm already working with community members like @renanccastro to keep Meteor Cordova integration up-to-date, every help is appreciated. For example, he is working on https://github.com/apache/cordova-ios/pull/719 which affects new Meteor iOS builds.

Please reach me out with specific concerns that you may have.

In my mind, the next step is to update the Cordova version used by Meteor.

**Comment by filipenevola** [comment]
Let's continue this discussion in the forums https://forums.meteor.com/t/meteor-cordova-integration-next-steps/50844

**Comment by raphinesse** [comment]
To chime in from the Cordova side:

Unfortunately, we sometimes have to make breaking changes to deal with technical debt and to be able to keep moving forward. Other times things are beyond our control: The ecosystems we are dealing with, especially Android and iOS runtimes and even more so their build systems, are very volatile and often we simply have to change to keep up with the upstream changes.

That being said, we always try to be as backwards compatible as we can. So if you notice any changes breaking your Cordova use-case please _do_ get in touch with us.

We also very much appreciate pre-release feedback. So if you see any pull requests that you think might break something for you, or if you notice any problems when testing your Cordova integration against our nightly builds `cordova@nightly`, don't be shy. We are curious about how people use Cordova and we appreciate the feedback. I'm sure we can figure out a solution together.

**Comment by filipenevola** [comment]
@raphinesse great to see you here! And yes, we will provide you feedback, for sure.

**Comment by derwaldgeist** [comment]
I really love the commitment you all put into the Cordova integration. To me, this integration is way underrated and was one of the key factors why I chose Meteor in the first place. React Native might me nice, but it forces you to develop the UI twice, while Cordova allows you to maintain just one code-base for Android, iOS, and web. Which is a huge plus for early-stage startups.
