### ISSUE TITLE
'undefined' Mongo selector value should throw up an error

### ISSUE THREAD

**Issue by xiaolin99** [meteor/meteor#10727]
Meteor 1.8.1

I know it is by design, so this is more of a feature request.

Current behavior of passing 'undefined' as mongo selector is that Meteor will change it to {} automatically, effectively selecting all records. For example, I have the following update statement:

```
ImportantDocument.update({ ID: ID_value }, { $set: { deleted: true }}, { multi: true });
```

if ID_value === undefined, every ImportantDocument record will be deleted.

the undefined ID_value most likely means there is a bug in my code, so it's better to have it throw up an error rather then trying to guess what the developer was trying to achieve, which could have really bad consequences.

**Comment by markreid** [comment]
Hi,

This has been discussed previously; you can find some issues that relate to it [here](https://github.com/meteor/meteor/issues?utf8=%E2%9C%93&q=ignoreundefined).
