### ISSUE TITLE
Unsupported Swift Version - Xcode 11

### ISSUE THREAD

**Issue by markshust** [meteor/meteor#10735]
Version: Meteor 1.8.1

OS: macOS Catalina 10.15, Xcode 11.1

Expected Behavior: `meteor run ios-device` opens Xcode for local build on device simulator

Actual Behavior: `meteor run ios-device` opens Xcode to prompt which says "Unsupported Swift Version" and the details:

The target “flow-backend” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.

![Screen Shot 2019-10-13 at 6 20 41 AM](https://user-images.githubusercontent.com/437029/66714255-8b4b2580-ed82-11e9-82fa-c254cba3b791.png)

Steps to replicate:
- Install latest stable version of Meteor 1.8.1.
- `sudo gem install cocoapods`
- `meteor add-platform ios`
- `meteor run ios-device`

**Comment by rj-david** [comment]
https://github.com/meteor/meteor/issues/10516

**Comment by crapthings** [comment]
same here xcode 11.1

![image](https://user-images.githubusercontent.com/1147704/67460613-07d8e080-f66e-11e9-8598-974548e55577.png)

**Comment by rj-david** [comment]
@crapthings have you tried this version?
https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.8.1-issue-10516.0

**Comment by AndyNormore** [comment]
Hey guys I got this fixed, you need to DELETE and then fresh install Xcode.

**Comment by NagendraMNK** [comment]
> Hey guys I got this fixed, you need to DELETE and then fresh install Xcode.

What version of Xcode did you installed to support swift 3.x version

Really helps me to save time to investigate on versions

**Comment by filipenevola** [comment]
Meteor 1.10.1 uses Swift 5.
