### ISSUE TITLE
Fix CSP violation for code that sets variable __meteor_runtime_config__

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor#10733]
At the moment, Meteor users are forced to weaken their Content Security Policy by setting `script-src 'unsafe-line'` because Meteor inserts an inline script right after the HTML body tag that sets the variable `__meteor_runtime_config__` and the inline script does not have a sha-256 hash or a nonce.

Example:
```
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.8.1%22%2C%22gitCommitHash%22%3A%22b33f59abbc33a3775913a32688025e8cd407d0e9%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22env%22%3A%22Production%22%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fmymeterapp.com%2Fmyapp%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%2Fmyapp%22%2C%22autoupdate%22%3A%7B%22versions%22%3A%7B%22web.browser%22%3A%7B%22version%22%3A%22bbe3e8df360739eca09be771b0b17854907ca5d3%22%2C%22versionRefreshable%22%3A%229b33f8fa391a81e22d7990a442924cf675d48ac8%22%2C%22versionNonRefreshable%22%3A%2234e081c8deb6b15d9acf6f05b1ecd422acd695cd%22%7D%2C%22web.browser.legacy%22%3A%7B%22version%22%3A%22f33d5526e7e135806b6f15b377fa4f35007910b6%22%2C%22versionRefreshable%22%3A%229b33f8fa391a81e22d7990a442924cf675d48ac8%22%2C%22versionNonRefreshable%22%3A%22b1c5a67a98b81d64235116636b5b30d7a4890e56%22%7D%7D%2C%22autoupdateVersion%22%3Anull%2C%22autoupdateVersionRefreshable%22%3Anull%2C%22autoupdateVersionCordova%22%3Anull%2C%22appId%22%3A%22zdem5b1w3gkqh8qfthu%22%7D%2C%22appId%22%3A%22zdem5b1w3gkqh8qfthu%22%2C%22accountsConfigCalled%22%3Atrue%2C%22isModern%22%3Atrue%7D"))</script>
```

The normal way of avoiding the need for a sha-256 hash or nonce is to move the inline script to an external .js file and include that from the main file.

In Meteor's case it is not that easy because the `__meteor_runtime_config__` variable is dynamically generated, so it cannot be served as a static .js asset.

In production, most of us have configured our web servers to directly serve files with the .js extension and other static assets without passing the request to Meteor.

To deal with this, Meteor must serve  `__meteor_runtime_config__` from a new special URL that does not have a .js prefix.

Perhaps something like this:

`/ROOT_URL/__meteor_runtime_config__/?hash=xxxxxxxxxxxxxx`
  
When this URL is accessed, Meteor will dynamically generate the script code on the server-side and set the HTTP Header `Content-Type` to `"text/javascript"`

Here's an example of how it could look with this approach that avoids the need for the weakened policy `script-src 'unsafe-line'`

```
<body>
<script type="text/javascript" src="/ROOT_URL/__meteor_runtime_config__/?hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"></script>
```

**Comment by vlasky** [comment]
It's a security issue so it should not become stale! Furthermore, this really isn't that difficult to resolve. I call on Meteor's new owner Tiny to give this proper attention.

**Comment by sebakerckhof** [comment]
One consideration here is that I can imagine some people have some reverse proxy configured to cache all JS resources (no matter what the cache headers say), which could break modern/legacy bundles etc. Sure, you can argue they should correctly configure the reverse proxy (typically nginx), but I've seen this a lot. And obviously it means an extra http request on each page load.

**Comment by sebakerckhof** [comment]
Btw, I see there is some part of the code that already accounts for this: 
https://github.com/meteor/meteor/blob/982181fff86e09a75f1d2681a78b9d784e666f4f/packages/webapp/webapp_server.js#L410-L413

I'll look further into this

**Comment by sebakerckhof** [comment]
@vlasky so, it turns out Meteor already supports this.
Add a file to your server:
```
import { BrowserPolicy } from 'meteor/browser-policy';
BrowserPolicy.content.disallowInlineScripts();
```

**Comment by vlasky** [comment]
@sebakerckhof thanks for your reply. I did not know about this feature

I am not using the browser-policy package so I enabled it by adding the following line at the top of Meteor.startup()

`WebAppInternals.setInlineScriptsAllowed(false);`

I think the implementation needs improvement to be production quality.

I just tested it and discovered that when the client loads /meteor_runtime_config.js, it doesn't append a hash to the URL. This means that the client could cache it and use a stale version after the next rebuild.

Would it be best to reopen this issue or to create a new one?

**Comment by sebakerckhof** [comment]
@vlasky the other JS files have a hash because they send cache headers. The runtime one doesn't send any cache related headers, so it shouldn't be cached by the browser. 
There is still the possibility that a reverse proxy would cache it, but that would be a bad configuration of the reverse proxy.
That being said, it's not hard to add a hash, and it might solve some issues and it could actually make the file cacheable by a reverse proxy in a correct way. So I'll make a PR to add the hash.

**Comment by vlasky** [comment]
@sebakerckhof when loaded resources have missing cache-control and expires headers, most browsers heuristically assign their own freshness time to that resource and use that for caching.

Quoting from [HTTP Heuristic Caching (Missing Cache-Control and Expires Headers) Explained](https://paulcalvano.com/index.php/2018/03/14/http-heuristic-caching-missing-cache-control-and-expires-headers-explained/):

> Since Firefox, Chrome and WebKit are open source, we can actually dig into the code and see how the spec is implemented. In the Chromium source as well as the Webkit source, we can see that the lifetimes.freshness variable is set to 10% of the time since the object was last modified (provided that a Last-Modified header was returned). The 10% since last modified heuristic is the same as the suggestion from the RFC. When we look at the Firefox source code, we can see that the same calculation is used, however Firefox uses the std:min() C++ function to select the less of the 10% calculation or 1 week. This explains why we only saw the resource cached for 7 days in Firefox. It would likely have been cached for 13 or 14 days in Chrome.

**Comment by sebakerckhof** [comment]
@vlasky These heuristics are based on the Last-Modified header, which is also not set.

**Comment by sebakerckhof** [comment]
Should be fixed in 1.10 since https://github.com/meteor/meteor/pull/10856 got merged.

**Comment by vlasky** [comment]
I did a test with a Meteor 1.9 project using Cloudflare as a reverse-proxy.

I confirm that Cloudflare sets a 14,400 second (4 hour) expiry header for meteor_runtime_config.js.

I had to create a Cloudflare Page Rule like this to ensure that meteor_runtime_config.js file is always served fresh:

```
https://mymeteorapp.com/*/meteor_runtime_config.js
Cache Level: Bypass
```

**Comment by alihussainiam** [comment]
I am using Meteor 2.2 with Angular as front using meteor-client bundler.

Nginx proxy is used to serve the angular bundle to the client while it forwards requests to the meteor server running at localhost:3000 at host container meteor server requests.

An exception is being raised for an XHR request   http://localhost/api/sockjs/info?cb=22oy1pevg0  which return  HTML code with js script fragment similar to the quoted in  
> At the moment, Meteor users are forced to weaken their Content Security Policy by setting `script-src 'unsafe-line'` because Meteor inserts an inline script right after the HTML body tag that sets the variable `__meteor_runtime_config__` and the inline script does not have a sha-256 hash or a nonce.
> 
> Example:
> 
> ```
> <body>
>   <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.8.1%22%2C%22gitCommitHash%22%3A%22b33f59abbc33a3775913a32688025e8cd407d0e9%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22env%22%3A%22Production%22%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fmymeterapp.com%2Fmyapp%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%2Fmyapp%22%2C%22autoupdate%22%3A%7B%22versions%22%3A%7B%22web.browser%22%3A%7B%22version%22%3A%22bbe3e8df360739eca09be771b0b17854907ca5d3%22%2C%22versionRefreshable%22%3A%229b33f8fa391a81e22d7990a442924cf675d48ac8%22%2C%22versionNonRefreshable%22%3A%2234e081c8deb6b15d9acf6f05b1ecd422acd695cd%22%7D%2C%22web.browser.legacy%22%3A%7B%22version%22%3A%22f33d5526e7e135806b6f15b377fa4f35007910b6%22%2C%22versionRefreshable%22%3A%229b33f8fa391a81e22d7990a442924cf675d48ac8%22%2C%22versionNonRefreshable%22%3A%22b1c5a67a98b81d64235116636b5b30d7a4890e56%22%7D%7D%2C%22autoupdateVersion%22%3Anull%2C%22autoupdateVersionRefreshable%22%3Anull%2C%22autoupdateVersionCordova%22%3Anull%2C%22appId%22%3A%22zdem5b1w3gkqh8qfthu%22%7D%2C%22appId%22%3A%22zdem5b1w3gkqh8qfthu%22%2C%22accountsConfigCalled%22%3Atrue%2C%22isModern%22%3Atrue%7D"))</script>
> ```
> 
> ```


but content type seems to be JSON hence an error is raised when doing JSON.parse.

> zone.js:182 Uncaught SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at utils.XHRLocalObject.xo.onfinish (scripts.js:51288)
>     at utils.XHRLocalObject.EventEmitter.emit (scripts.js:49186)
>     at XMLHttpRequest.that.xhr.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (scripts.js:50040)
>     at XMLHttpRequest.wrapFn (polyfills.js:1011)
>     at ZoneDelegate.invokeTask (polyfills.js:511)
>     at Zone.runTask (polyfills.js:199)
>     at ZoneTask.invokeTask [as invoke] (polyfills.js:663)
>     at invokeTask (polyfills.js:2084)
>     at XMLHttpRequest.globalZoneAwareCallback (polyfills.js:2116)
> core.js:28041 Angular is running in development mode. Call enableProdMode() to enable production mode.
> core.js:28041 Angular is running in development mode. Call enableProdMode() to enable production mode.
> zone.js:182 Uncaught SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at utils.XHRLocalObject.xo.onfinish (vendor.js:213689)
>     at utils.XHRLocalObject.EventEmitter.emit (vendor.js:211579)
>     at XMLHttpRequest.that.xhr.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (vendor.js:212435)
>     at XMLHttpRequest.wrapFn (polyfills.js:1011)
>     at ZoneDelegate.invokeTask (polyfills.js:511)
>     at Zone.runTask (polyfills.js:199)
>     at ZoneTask.invokeTask [as invoke] (polyfills.js:663)
>     at invokeTask (polyfills.js:2084)
>     at XMLHttpRequest.globalZoneAwareCallback (polyfills.js:2116)

This goes back to normal as soon as I change direction to the meteor server and not through Nginx. I tried this `WebAppInternals.setInlineScriptsAllowed(false);` but does not work.

**Comment by EmpowerPeople-Vik** [comment]
This thread is being [discussed on the Meteor Forum](https://forums.meteor.com/t/context-security-policy-error-is-blocking-meteor-runtime-config/63034/6). Has this been definitively fixed? Does any code need to be added to a Meteor app to support this?
