### ISSUE TITLE
Deprecated React Lifecycles

### ISSUE THREAD

**Issue by gotjoshua** [meteor/meteor#10737]
- [x] The version of Meteor showing the problem.
1.8.1
- [x] The operating system you're running Meteor on.
Mac OSX 10.13.6
- [x] The expected behavior.
no warnings indicating deprecated lifecycle functions
- [x] The actual behavior.
Several Warnings asking "Please update the following Components: ReactMeteorDataComponent"

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactMeteorDataComponent, Trigger
```
and similar one for componentWillUpdate.

**Comment by StorytellerCZ** [comment]
There are already many solutions available waiting for PR in the [React packages repo](https://github.com/meteor/react-packages).
There is an [easy, temporary patch](https://github.com/meteor/react-packages/pull/274) and then a [major improvement](https://github.com/meteor/react-packages/pull/273) which fixes this completely.
I would again like to request repository maintainers to merge one of those asap.

@gotjoshua If you can't stand it, I would recommend getting the version you want and copying it into your app package directory.

**Comment by gotjoshua** [comment]
Thanks for the head's up @StorytellerCZ...  
I can stand it for now, but yeah it i support your request that the maintainers push an update  with a fix.
