### ISSUE TITLE
Meteor can't run android

### ISSUE THREAD

**Issue by cecilcosta** [meteor/meteor#10744]
Meteor 1.8.1
OS X 10.15 (Catalina)
Zsh
Android SDK installed.

After creating a new project and using `meteor add-platform android`, try to run `meteor run android`

Expected result:
An Android simulator should appear

Result:
`*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "run android"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk`

**Comment by mattmcegg** [comment]
Hey @cecilcosta cecilcosta, for this issue, you need to open up Android Studio, and click the AVM Manager button on the top right. (Its small and kind of hard to find). Go through the wizard and create an AVM, then re-run your run command. It will find the available AVM and boot up your app.

**Comment by crapthings** [comment]
@mattmcegg do you mean AVD Manager?

**Comment by mattmcegg** [comment]
> @mattmcegg do you mean AVD Manager?

Yup

**Comment by StorytellerCZ** [comment]
Has the issue been resolved by #10810 ?

**Comment by filipenevola** [comment]
Yes, @cecilcosta can you try again on 1.10 betas?
