### ISSUE TITLE
[Feature] Hooks for loggedIn and loggedOut events

### ISSUE THREAD

**Issue by BenjaminRH** [meteor/meteor#1074]
It would be really useful in many ways if we could have reactive hooks that tie into "user logged in" and "user logged out" events. Examples use-cases include:

 * Redirecting to a certain page after the user logs in
 * Manipulating the DOM or a Collection the first time a user logs in, or when a user logs in
 * Notifying other clients when a user has logged in/out (perhaps chat participants receive a notification when their friends come online)
 * Etc.

**Comment by tmeasday** [comment]
Implemented in #7187

**Comment by laosb** [comment]
Sounds like @tmeasday accidentally reopened this.
