### ISSUE TITLE
When to shift the modern/legacy cutoff?

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10759]
More of a question / start of discussion: When do we shift the cutoff between modern/legacy?

Currently the cutoff seems to be native async/await. But as most browsers are so-called evergreen browsers, this is a shifting target. Therefore the ecmascript-runtime-client package now already contains some polyfills which do no longer seem necessary in todays browser landscape.
(in fact, `ecmascript-runtime-clinet` contains some polyfills for stuff introduced everywhere before native async await was introduced, I'll make a PR for that soon).

**Comment by smeijer** [comment]
Would be awesome if we could use `browserslist` for this, so it's user configurable and always actual.
