### ISSUE TITLE
$bit operator not supported on client

### ISSUE THREAD

**Issue by txgruppi** [meteor/meteor#10757]
- Meteor version: 1.8.1
- Minimongo version: 1.4.5

Problem: Expection on `$bit`

Proposed solution 1:

Implement `$bit` on the client with the JS Number (and, or and xor operations work with JS Number) so that the client don't throw when running a `$bit`.

It should be safe to run it with JS Numbers because the server is going to run the code on Mongo and return the correctly updated document to the client.

Proposed solution 2: (my preferred option)

Implement a client version of Mongo's Int32 and require the values in `$bit` to be `Int32` wrappers and not plain Numbers. On the server it should just be an alias for the original `Int32`

**Comment by yuwiggin** [comment]
Mongo only supports $bit on integers, and Meteor only supports native javascript numbers (doubles) so far, including server side.

**Comment by txgruppi** [comment]
@yuwiggin: Yes, that's exactly what the error message says and it is also the reason I created this issue.

I prefer the second proposed solution because by using a wrapper we can truncate the number to an integer and make it consistent client and server.
