### ISSUE TITLE
1.8.2-rc.4 initial load time is too long

### ISSUE THREAD

**Issue by yuwiggin** [meteor/meteor#10753]
The first load time become too long (> 1 minute !) when Meteor is upgraded from 1.8.1 to 1.8.2-rc.4 and the following packages are updated.

before update:

```
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
 ```   
after update:  
```  
    "@material-ui/core": "^4.4.2",
    "@material-ui/icons": "^4.4.1",
    "ipfs-http-client": "^39.0.2",
    "bcrypt": "^3.0.4",
    "bs58": "^4.0.1",
    "mmmagic": "^0.5.2",
``` 
How to improve the perfermance? 

Runtime environment:
Node: 8.15.1,
npm: 6.9.1

**Comment by filipenevola** [comment]
Hi @yuwiggin, for sure that is not ok, I think you can improve your code to have better results.

Just to confirm, when you say "first load time" you mean in the browser, right?

Did you use Chrome Dev Tools to record a profile and see what is running during the first loading?

https://developers.google.com/web/tools/chrome-devtools/evaluate-performance

If that is your first time using the Performance tab of Chrome this can be a little bit hard to understand but if you keep zooming-in and try to find your code running and not Meteor initialization code it starts to become easier with that as you get used to it.

Let me know if you can find more details in the profile.

**Comment by yuwiggin** [comment]
@filipenevola Yes, it is a long time to open the homepage in the browser. I tried to use the Performance tab of Chrome Dev Tools and got the profile, summary of which is render in the following image. But I can't any hint from it since I use it for the 1st time. Any suggestion?

<img width="559" alt="profile-summary" src="https://user-images.githubusercontent.com/812370/67917251-6ef91680-fbd3-11e9-92f3-69e62004da8e.png">

**Comment by filipenevola** [comment]
@yuwiggin you can export the profile then I can open in my dev tools and try to provide some insight to you.

See the screenshot with the export button, please attach the file here.
<img width="808" alt="2019-11-05_07-57-06" src="https://user-images.githubusercontent.com/437372/68202166-ef3bc500-ffa1-11e9-86e9-9cf9d82d0910.png">

**Comment by yuwiggin** [comment]
@filipenevola The profile is too large, so it is [zipped and store in a temporary repository]
(https://github.com/yuwiggin/engine/blob/master/Profile-20191031T102903.json.zip)

Thank you for your guide very much!

**Comment by filipenevola** [comment]
hi @yuwiggin, sorry for the long delay but according to this profile your app is loading fast in the browser.

See the image below
<img width="1172" alt="profile-screenshot" src="https://user-images.githubusercontent.com/437372/69345692-edcbf700-0c47-11ea-8203-3ffa0dee118d.png">

I believe you have something in your network that was preventing the loading but it was not the app itself.

Is this app published anywhere so I can take a look?
