### ISSUE TITLE
[1.8.2-rc.6] TypeScript: __importDefault is not defined

### ISSUE THREAD

**Issue by afrokick** [meteor/meteor#10764]
I have an issue with rc6(and rc4 too) + TypeScript (Meteor 1.8.2.rc6, MacOS 10.15.1, Chrome 78.0.3904.87, TypeScript 3.7.1rc/3.7.2 (Adornis/Meteor's))
 when run in browser:
```
Uncaught ReferenceError: __importDefault is not defined
    at index.js (app.js:102752)
    at fileEvaluate (modules-runtime.js:346)
    at Module.require (modules-runtime.js:248)
    at require (modules-runtime.js:268)
    at index.js (app.js:104983)
    at fileEvaluate (modules-runtime.js:346)
    at Module.require (modules-runtime.js:248)
    at Module.moduleLink [as link] (modules.js:373)
    at methods-hooks.js (app.js:110538)
    at fileEvaluate (modules-runtime.js:346)
```

I found the similar issue in Angular https://github.com/angular/angular/issues/32215#issuecomment-543459862

Now I fixed it with adding script in head.html file:
```
    <script type="text/javascript">
        var __importStar = (this && this.__importStar) || function (mod) {
            if (mod && mod.__esModule) return mod;
            var result = {};
            if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
            result["default"] = mod;
            return result;
        }
        
        var __importDefault = (this && this.__importDefault) || function (mod) { return (mod && mod.__esModule) ? mod : { "default": mod }; }
    </script>
```

Additionally I have .babelrc file:
```
{
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
}
```

With 1.8.1 it works perfect on TS3.7.2(Adornis) without any hacks.

**Comment by dvsingh9** [comment]
Same with me.

**Comment by benjamn** [comment]
Can you provide a reproduction?

It looks like TypeScript is injecting helpers from its [`tslib`](https://github.com/microsoft/tslib/blob/master/tslib.es6.js) library, even though the Meteor `typescript` package should only be transpiling TypeScript-specific syntax to modern JavaScript, so that Babel can handle the rest.

**Comment by afrokick** [comment]
@benjamn Sorry. Right now I have an issue with Adornis plugin only. Perhaps it depends on my custom tsconfig.

I'll add a comment if reproduce it with meteor's typescript.

**Comment by benjamn** [comment]
@afrokick For what it may be worth, I believe the `"esModuleInterop": true` option is what's responsible for injecting `__importDefault` and `__importStar`. Given that Babel handles the actual compilation of `import` and `export`, I think we have full interop by default, so maybe that option is not necessary?

**Comment by Gbuomprisco** [comment]
Not sure if it helps, but I fixed the issue by using "@angular-devkit/build-angular": "~0.900.0-rc.0"

**Comment by afrokick** [comment]
> @afrokick For what it may be worth, I believe the `"esModuleInterop": true` option is what's responsible for injecting `__importDefault` and `__importStar`. Given that Babel handles the actual compilation of `import` and `export`, I think we have full interop by default, so maybe that option is not necessary?

It doesn't work for me without `"esModuleInterop": true` in 1.8.1 with Adornis.

**Comment by afrokick** [comment]
Still exists. I'll try to create a test repo.

**Comment by afrokick** [comment]
@dvsingh9 @benjamn

I found an issue.

From 1.8.2 changelog:

> When bundling modern client code, the Meteor module system now prefers the "module" field in package.json (if defined) over the "main" field, which should unlock various import/export-based optimizations such as tree shaking in future versions of Meteor. As before, server code uses only the "main" field, like Node.js, and legacy client code prefers "browser", "main", and then "module". PR #10541, PR #10765.

- `adornis:typescript` uses `barbatus:typescript-runtime`
- `barbatus:typescript-runtime` uses `tslib` and exports some methods from it

Prior 1.8.2, meteor uses tslib/package.json main field, so all helpers were added to global

Starting from 1.8.2, meteor uses tslib/package.json module field, so only exported helpers added to global via `barbatus:typescript-runtime` plugin

**Workaround** 

- add `meteor npm install tslib`
- add `"importHelpers": true` option to tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["esnext", "dom"],
    "moduleResolution": "node",
    "types": ["node"],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "importHelpers": true         <----
  }
}
```

Why we don't like meteor's typescript? It doesn't support custom tsconfig...

**Comment by Giteon** [comment]
> @dvsingh9 @benjamn
> 
> I found an issue.
> 
> From 1.8.2 changelog:
> 
> > When bundling modern client code, the Meteor module system now prefers the "module" field in package.json (if defined) over the "main" field, which should unlock various import/export-based optimizations such as tree shaking in future versions of Meteor. As before, server code uses only the "main" field, like Node.js, and legacy client code prefers "browser", "main", and then "module". PR #10541, PR #10765.
> 
> * `adornis:typescript` uses `barbatus:typescript-runtime`
> * `barbatus:typescript-runtime` uses `tslib` and exports some methods from it
> 
> Prior 1.8.2, meteor uses tslib/package.json main field, so all helpers were added to global
> 
> Starting from 1.8.2, meteor uses tslib/package.json module field, so only exported helpers added to global via `barbatus:typescript-runtime` plugin
> 
> **Workaround**
> 
> * add `meteor npm install tslib`
> * add `"importHelpers": true` option to tsconfig.json:
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es5",
>     "lib": ["esnext", "dom"],
>     "moduleResolution": "node",
>     "types": ["node"],
>     "esModuleInterop": true,
>     "experimentalDecorators": true,
>     "importHelpers": true         <----
>   }
> }
> ```
> 
> Why we don't like meteor's typescript? It doesn't support custom tsconfig...

THANK YOU THIS WORKED!

**Comment by shivamkrpandey** [comment]
Faced same issue and added only below option in `tsconfig.json` to fix

` "importHelpers": true `

**Comment by 11kodykay11** [comment]
`'importHelpers': true` worked for me too. Thanks.

**Comment by lucgagan** [comment]
Stared to get the same error after updating next.js and typescript. Adding `importHelpers` does not help.
