### ISSUE TITLE
[1.8.2-rc.7] No Tinytest output after updating to TypeScript

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#10769]
Apologies for being a Tinytest necromancer, but in the process of updating an old Meteor package (https://github.com/TurkServer/turkserver-meteor) to support 1.8 and TypeScript I have run into a strange issue. We can look at it in three cases:

## Running the tests with Meteor 1.4.4.6 (works)

The package was originally written with Tinytest before `meteor test` came out. Here are the tests working on `master` on CI with Meteor 1.4.4.6: https://travis-ci.org/TurkServer/turkserver-meteor/builds/609866147

## Running the tests with Meteor 1.8.2-rc.7 (works)

The test can also be run on Meteor 1.8 by checking out `master` and running the following command. Here some of the tests fail, but it's due to Mongo version updates.

```
meteor --release 1.8.2-rc.7 test-packages ./
```

## Running the tests with Meteor 1.8.2-rc.7 and TypeScript (nothing happens)

Now here's the strange part. In the [`typescript-1.8` branch](https://github.com/TurkServer/turkserver-meteor/pull/103) I have attempted to update many of the server-side files to TS without making substantive changes to them, only doing the minimum to get by to get the compiler to stop complaining. After much futzing around and working through everything in `api.addFiles` I get no more TypeScript or compiler errors, but the test doesn't launch. Specifically, the following lines appear:

```
$ meteor --release 1.8.2-rc.7 test-packages ./
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
mizzao:turkserver: updating npm dependencies -- mturk-api, jspath, deepmerge, @babel/runtime...
=> Started MongoDB.                           
W20191111-02:02:11.529(-5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20191111-02:02:11.617(-5)? (STDERR) While this implementation will work correctly, it is known to be
W20191111-02:02:11.618(-5)? (STDERR) approximately three times slower than the native implementation.
W20191111-02:02:11.618(-5)? (STDERR) In order to use the native implementation instead, run
W20191111-02:02:11.618(-5)? (STDERR) 
W20191111-02:02:11.618(-5)? (STDERR)   meteor npm install --save bcrypt
W20191111-02:02:11.618(-5)? (STDERR) 
W20191111-02:02:11.618(-5)? (STDERR) in the root directory of your application.
```

but the following expected lines **don't show up**, and port 3000 is never opened (can't access from browser).

```
=> Started your app.

=> App running at: http://localhost:3000/
``` 

Now, this is strange, because all the files should be the same other than TS conversion, and no errors are given. It's entirely possible I am doing something stupid here due to the use of modules and imports, but in any case the app should still start, right?

## Other information:

OS: observed the same behavior with Ubuntu on WSL (Windows 10) and Gentoo Linux (in a VM).

**Comment by benjamn** [comment]
Any number of things could keep an application from doing something important during startup, and I'm afraid TS conversion changes are not (in my experience) completely risk-free. That's part of the reason I'm currently holding off on merging the open TS conversion PRs until after we release Meteor 1.8.2 (soon!). If your TS changes are separated into commits, maybe you can try bisecting them?

**Comment by mizzao** [comment]
If I understand what you're saying, I don't think I can bisect them because there are TS errors all the way until the most recent commits, whereby there are no errors but the app doesn't start.

However, it's good to know about the [TypeScript conversion PRs](https://github.com/meteor/meteor/pulls?utf8=%E2%9C%93&q=is%3Apr+typescript+). I'll definitely check these out and see if there's anything I can learn from them.
