### ISSUE TITLE
[1.8.1] Potential subscription performance issue

### ISSUE THREAD

**Issue by bhunjadi** [meteor/meteor#10770]
The version of Meteor showing the problem: 1.8.1
The last version of Meteor where the problem did _not_ occur: 1.8.0.2
OS: Ubuntu Server 18.04 (using Hyper-V)
Host OS: Win 10 x64

When trying to update my project from 1.8.0.2 to 1.8.1 I noticed a very big performance hit when using reactive queries.

I've made a [reproduction repo](https://github.com/bhunjadi/meteor-subscription-issue).
In the example composite publication is used (using [grapher](https://github.com/cult-of-coders/grapher)). There are two collections and the main collection has reference ids to linked collection (1..N relation).

I bisected devel branch when running from a checkout and it looks like the issue is in [this commit](https://github.com/meteor/meteor/commit/4a0bf12d0e58f146c6720af7f2f2aacc5d7d2de0).

However, when I changed `BUNDLE_VERSION` [here](https://github.com/meteor/meteor/commit/4a0bf12d0e58f146c6720af7f2f2aacc5d7d2de0) to 100.0.0, as suggested in dev docs, and did `./scripts/generate-dev-bundle.sh` the issue was NOT present anymore.
I tried running on Windows 10 and it looks like there is NO performance difference there for some reason.

Other notes:
- I turned on and off the AV - no change.
- I tested both Meteor versions on the VPS and got same results - 2x slowdown for 1.8.1. I did not test local meteor there, though.
- Tried both embedded and external database - same results

To conclude, it seems that problem might be on Linux and something to do with dev_bundle.

Right now I'm stuck here, any ideas what to try next?

**Comment by benjamn** [comment]
Can you try after running `meteor update --release 1.8.2-rc.7` in your application?

Commits where we bump the `BUNDLE_VERSION` typically follow commits where we change something about the "dev bundle," which includes dependencies like Node.js, MongoDB, and npm packages used by the Meteor command-line tool. In this case, the previous commit was https://github.com/meteor/meteor/commit/f16e76003caa3e0a6fd8e282a75e23a307392d17, which bumped Node.js to version 8.12.0. On the `release-1.8.2` branch, we're using Node.js 8.16.2, so there's a good chance many things have changed, which is why I think the update is worth a try.

**Comment by bhunjadi** [comment]
Thanks for prompt response.

It looks like 1.8.2 rc.7 solves the issue! I checked CPU profile and it looks like there were issues with garbage collector in 1.8.1 (ie node 8.15.1). I remember trying with 1.8.2.beta in the past and it was not working then. Perhaps 1.8.2 was still using node 8.15.1 that caused the problems.

However, I still cannot explain why running from the checkout and generating dev bundle locally would work for node.js 8.12.0 and 8.15.1.

I'll close this now and keep an eye on the performance in next few days.

**Comment by benjamn** [comment]
One theory about running from a checkout: when you run `scripts/generate-dev-bundle.sh`, you're reinstalling the latest versions of a bunch of npm dependencies, whereas the official Meteor 1.8.1 release will always use exactly the same npm versions from the time when 1.8.1 was published. So maybe something changed (for the better!) among those dependencies.
