### ISSUE TITLE
[accounts-password] enroll token lost when user initiates Forgot Password

### ISSUE THREAD

**Issue by alanning** [meteor/meteor#10775]
As part of the Forgot Password flow, [this code](https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js#L620-L622) replaces any existing reset field on the user's account.  Since the enrollment flow also uses the reset field, this wipes out any existing enrollment tokens the user may have.

This is causing trouble for some of our customers because employees will sometimes click the Forgot Password link in our Meteor app before clicking the link from the invite email.  Then when they eventually do click the link they get an error message since its no longer a valid token (having been deleted from their user account).  This means that our customers have to re-send the invite to the users in question.

Would a PR that resolved this issue be accepted?

At this time I'm not sure which would be easier but I would probably either:
* change the "services.password.reset" field to be an array, or
* split out the enrollment flow data into a separate db field, "services.password.enroll"

**Comment by pmogollons** [comment]
Not stale

**Comment by pmogollons** [comment]
Not stale

**Comment by Vallo** [comment]
reopen

**Comment by filipenevola** [comment]
Hi @alanning, I would prefer `split out the enrollment flow data into a separate db field, "services.password.enroll"`

**Comment by ritwik1233** [comment]
Hi, I have created a [PR]( https://github.com/meteor/meteor/pull/11429 ) for the above-proposed solution.
