### ISSUE TITLE
[Unreleased, checkout d84f4c208] Mocha + Typescript Unit Tests Don't Run -- Environment Not Initialized?

### ISSUE THREAD

**Issue by src-r-r** [meteor/meteor#10777]
I've created a repository to show the problem:

https://github.com/src-r-r/silver-palm-tree

Basically, I converted the tests to typescript. I see nothing in the documentation stating that typescript is not supported with mocha tests. However, as shown in the example, the script isn't run.

Typescript is compiled. I know this because if you intentionally add errors in the code, `meteor test` complains.

As mentioned in the title I think this might be an issue of not waiting for the environment to be set up. I modified a file in my meteor installation (`$HOME/.meteor/packages/barbatus_typescript/0.7.0/plugins.typescript.os/packages`). It seems as though this file is compiled from meteor's `compile_env.js` file, which is why I'm here.

Here are my modifications (just to see what's going on -- this is around line 1079):

```
var TEST_METADATA_STR;
if (Meteor.isClient) {
  TEST_METADATA_STR = meteorEnv.TEST_METADATA;
} else {
  TEST_METADATA_STR = process.env.TEST_METADATA;
  console.log(`srcrr: TEST_METADATA_STR=${TEST_METADATA_STR}`);
}
```

And in fact `srcrr: TEST_METADATA_STR={}` is printed to the console. Obviously, this is empty and no required variables (e.g. `isTest`) is set, so none of the tests are run.

What's more is that meteor sets `process.env.TEST_METADATA` *after* it executes `barbatus_typescript`. I added the following to `<meteor_source>/tools/cli/commands.js` around line 227:

```
if (self.testMetadata) {
      env.TEST_METADATA = JSON.stringify(self.testMetadata);
      process.env.TEST_METADATA = env.TEST_METADATA;
      console.log(`srcrr: Setting Metadata: ${process.env.TEST_METADATA}`);
    }
```

When running tests, `srcrr: Setting Metadata: {"driverPackage":"meteortesting:mocha","isAppTest":false,"isTest":true}` is printed, so the environment is being set, but--again--it's printed *after* the plugin is loaded.

I'd like to see if I can contribute in some way besides this verbose bug report.

**Comment by benjamn** [comment]
If you run
```sh
meteor npm i @babel/runtime
meteor add typescript
```
in that sample application, I believe you'll start to get errors that are less opaque (changing file extensions on your imports from `.js` to `.ts`, for example).

**Comment by src-r-r** [comment]
Attempted to run the commands as you specified, but I'm running into the same issue. I also realized I forgot to convert a lot of the js files to ts in the example repo (I updated this to the latest in the example repo).

I **checked meteor out from the repository**, so I'm using the latest meteor binary.

I also attempted to **set the environment manually** (`'{"driverPackage":"meteortesting:mocha","isAppTest":false,"isTest":true}'`).

This does invoke the testing for the typescript plugin. However, I'm running into a further issue I can't quite nail down...

It's in `test_environment.js` again on line 19.

```
var testDriverPackage = Package[testDriverPackageName];
```

This fails because `meteortesting:mocha` is not found.

`Package` is a `PackageRegistry` object, defined in `define-package.js`. It's a special type where a user can access elements by key, but `Object.keys` will not return anything.

So I decided to do a little sleuth work another way, but inserting a debug statement in the `_define` method:

```
PRp._define = function definePackage(name, pkg) {
  pkg = pkg || {};

  console.debug(`srcrr: package "${name}"`);
```

The result is either strange or telling:

```
srcrr: Reading combineds                     \
srcrr: path: <meteor_path>/.meteor/isopackets/combined
packages: {"_promiseInfoMap":{}}
Errors prevented isopacket load:              
                                              
While loading isopacket `combined`:
packages/meteor.js:1146:13: Can't find test driver package: meteortesting:mocha
at packages/meteor.js:1146:13
at Object.startup (packages/meteor.js:994:5)
at packages/meteor.js:1141:10
at packages/meteor.js:1167:4
at packages/meteor.js:1512:3


<meteor_path>/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: isopacket load failed?
    at loadIsopacketFromDisk (/tools/tool-env/isopackets.js:323:11)
    at /tools/tool-env/isopackets.js:114:9
    at Object.exports.noYieldsAllowed (/tools/utils/fiber-helpers.js:37:14)
    at loadIsopackage (/tools/tool-env/isopackets.js:105:34)
    at ProjectContext._buildResolver (/tools/project-context.js:817:34)
    at /tools/project-context.js:530:29
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:529:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:528:13)
    at /tools/project-context.js:300:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:290:18)
    at Profile.run (/tools/project-context.js:260:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.resolveConstraints (/tools/project-context.js:259:13)
    at /tools/runners/run-all.js:75:27
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at new Runner (/tools/runners/run-all.js:74:18)
    at Object.exports.run (/tools/runners/run-all.js:365:16)
    at runTestAppForPackages (/tools/cli/commands.js:2017:19)
    at doTestCommand (/tools/cli/commands.js:1899:10)
    at Command.func (/tools/cli/commands.js:1638:10)
    at /tools/cli/main.js:1531:15
```

None of the packages seem to load.

However, if I just do a `meteor` command (using the latest binary) I get output like this...
```
...
srcrr: package "blaze-tools"
srcrr: package "spacebars-compiler"
srcrr: package "templating-tools"
srcrr: package "caching-html-compiler"
srcrr: package "compileTemplatesBatch"
srcrr: package "meteor"ges                   |
srcrr: package "ecmascript-runtime"
srcrr: package "modules-runtime"
srcrr: package "modules"
srcrr: package "modern-browsers"
srcrr: package "promise"
srcrr: package "ecmascript-runtime-client"
srcrr: package "ecmascript-runtime-server"
srcrr: package "babel-compiler"
srcrr: package "ecmascript"
srcrr: package "babel-runtime"
srcrr: package "fetch"
srcrr: package "inter-process-messaging"
...
```
