### ISSUE TITLE
Wanting to contribute for Metadata Reflection and Decorators Support in TypeScript package

### ISSUE THREAD

**Issue by ardatan** [meteor/meteor#10784]
When using `typescript` package in an Angular project, it doesn't have metadata reflection which Angular needs to have `"experimentalDecorators": true` and `"emitDecoratorMetadata": true` in `compilerOptions` of TS Compiler configuration which is missing in `meteor-babel`'s `preCompileTypescript`. So this little change in `meteor-babel` wouldn't affect existing Meteor users but it would make Meteor support all those libraries using decorators and metadata reflection like Angular, TypeORM, TypeGraphQL, Inversify etc. I can create a PR for this issue if you want.
https://github.com/meteor/babel/blob/51258a2feb412131ec045a7fba613690d9854ad0/index.js#L149

But I think respecting `tsconfig.json` in the project would be better because there are some other `compilerOptions`, users may want to use now and later. If you want to force users in some options, you can throw an error during compilation process to make users change by themselves instead of overriding it which would be more consistent with the behavior of the IDE that respects `tsconfig.json`.

There is another option which is using `babel-typescript`(or respecting `babelrc` and add `ts` and `tsx` extensions to `ecmascript` package https://github.com/meteor/meteor/blob/3f88ccb387c545b4863027fb099bba4759af34c8/packages/ecmascript/plugin.js#L2) and disabling default `flow` plugins to prevent conflicts inside `meteor-babel` so there would be single compilation process handled in babel completely. And in this case not to break the existing behavior for flow users, we can remove `flow` plugin for `ts` files only in `meteor-babel` package.

What do you think? @benjamn

**Comment by benjamn** [comment]
Here are my thoughts on the challenges of paying attention to `tsconfig.json`: https://github.com/meteor/meteor/pull/10610#issuecomment-554403683

**Comment by ardatan** [comment]
@benjamn The actual issue is lack of these two additional options prevents users of Angular, Inversify and other kind of libraries to benefit from this `typescript` package. However adding those two options wouldn't affect the existing users. I also mentioned to use `babel-typescript` with the existing babel structure of meteor-babel that can be extended by other babel plugins. So my point wasn't only about respecting `tsconfig.json`.
I created a PR that makes people able to use this package with Angular and similar libraries/frameworks.
https://github.com/meteor/babel/pull/28

**Comment by MastroLindus** [comment]
@benjamn I have the feeling that only a very limited amount of tsconfig settings will impact meteor's build  (stuff like module, targets, etc), and that not allowing users to specify the other flags will create a lot more problems than the confusion of having that small set forced by meteor.

Couldn't we simply for the moment use a "best effort" approach to respect the tsconfig flags, and discard those that influence meteor's behaviour?
I am not a fan of this approach either, but between this and not been able to specify any flag at all I consider the latter much worse.

**Comment by afrokick** [comment]
not stale

**Comment by afrokick** [comment]
Also we use `resolveJsonModule` with decorators.

**Comment by afrokick** [comment]
@benjamn @filipenevola any news? It is blocker for us to migrate from Adornis package to "native" typescript.

**Comment by afrokick** [comment]
There is open PR to meteor-babel https://github.com/meteor/babel/pull/28

**Comment by MastroLindus** [comment]
I am also blocked in migrating from Adornis to the typescript package until some flags in tsconfig.json are allowed: https://github.com/meteor/meteor/pull/10610#issuecomment-554417233

In short I need at least 
```
strict: true,
experimentalDecorators: true
```
to be allowed.

I really really really hope they get supported.
Honestly I would still prefer to allow people to specify what they want in their own tsconfig, and have Meteor make a best-effort approach of supporting them, but overriding the ones that can be problematic (output directories, modules, etc)

**Comment by Urigo** [comment]
no stale.

I believe @ardatan gave a couple of possible solutions, can someone decide and offer one of them?
https://github.com/meteor/meteor/issues/10784#issuecomment-555361241

**Comment by Urigo** [comment]
no stale.

**Comment by ruohki** [comment]
is there a workaround until we can use that by default?

**Comment by ardatan** [comment]
You can use barbatus:typescript package instead of official one.

**Comment by ardatan** [comment]
no stale.

**Comment by filipenevola** [comment]
Hi @ardatan I've talked with @perbergland about his typescript package as well (https://github.com/ref-app/meteor-typescript) and we should join efforts here to update the official typescript package in the best way for the community.

@zodern is also going to take a look in this package from Per to check if the performance could be improved.

We need to select a package to be the candidate for the new official package and then make PRs to update the actual official package.

Any thoughts on this?

**Comment by ardatan** [comment]
@filipenevola I think it is fine. The most important point is to have enough flexibility to support user's tsconfig.json (at least decorators).

**Comment by afrokick** [comment]
1.12 should contains emitDecorator
