### ISSUE TITLE
Meteor includes unnecessary packages in unibuild packages

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10787]
Meteor seems to include unnecessary packages.

E.g. if you do `meteor add accounts-password`, it will include the `underscore` package in your client bundle, although nowhere in the dependency tree we depend on `underscore` on the client-side.

The thing is, this is only if you use the prebuild/published package. If you include the package locally, the `underscore` dependency is gone. 

Minimum reproduction repo:
https://github.com/sebakerckhof/meteor-packages-issue

Steps to reproduce:
1. clone the repo
2. run `meteor npm install`
3. run `meteor npm run visualize`

You can see in the bundle visualizer, that underscore is included.

Now if you comment out this line:
`https://github.com/sebakerckhof/meteor-packages-issue/blob/master/packages/accounts-password/package.js#L2`

It will use the local version (exact same package otherwise) and you'll notice that the underscore package disappears from the client bundle.

**Comment by benjamn** [comment]
Did this get fixed somehow??

**Comment by sebakerckhof** [comment]
@benjamn . Turned out to be this: https://github.com/meteor/meteor/issues/10788

**Comment by sebakerckhof** [comment]
Btw, the issue about including unnecessary node modules in packages (although technically different) is still open. I've looked a bit deeper into it yesterday and written down my thoughts on possible ways to fix it, it would be great to get your input:
https://github.com/meteor/meteor/issues/10230#issuecomment-557022580
