### ISSUE TITLE
Published accounts-password doesn't match repository

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10788]
I noticed that the published accounts-password 1.5.1 package is not up to date with the repository.

E.g. The package here on git, does no longer depend on underscore (and hasn't for the past 2 years), but the package.js file of the sources published on atmosphere still do:
https://warehouse.meteor.com/sources/Aw5o5YMrAYo9bGgRY/1519255742438/DLp2Wznwkc/accounts-password-1.5.1-source.tgz

I noticed this while searching why we still got underscore in our client bundle, but there might be more packages that need republishing.

**Comment by filipenevola** [comment]
1.5.2 is now published.

Thank you 😉
