### ISSUE TITLE
More information when a publication throws an error

### ISSUE THREAD

**Issue by mbatchkarov** [meteor/meteor#10782]
Whenever an exception is thrown in a publication, there is isn't enough information in the server logs to diagnose the problem. For example:

```
Meteor.publish("bug", function() {
  let options = { fields: { profile: 1 } };
  console.log(options.a.b.c);
  return Meteor.users.find();
});
```

When a client subscribes, the following is printed in the server console:

```
Exception from sub bug id iw7bzHXSsXZtz9QSK [object Object]
```
Spotting the error is easy enough with a 4 line subscriptions but gets very laborious as complexity increases. I appreciate there are arguments as to why error details should not be sent to the client, but I think the server-side log should be more verbose.

Meteor version: 1.8.1 on both Linux and OSX

**Comment by zodern** [comment]
@mbatchkarov are you using an APM package? Most of them, at least in the past, would cause the errors in methods and publications to appear as `[object Object]`.

**Comment by mbatchkarov** [comment]
I'm using Kadira in the app that prompted me to start investigating, but before I started this issue I also tried with a brand new minimal app and I saw the same. Based on #10807 I think this would also be the same

**Comment by filipenevola** [comment]
@mbatchkarov this version of `meteor-apm-agent` published today should help you https://github.com/meteor/meteor-apm-agent/blob/master/CHANGELOG.md#v325

Please open this issue again if this still happens.
