### ISSUE TITLE
nodeModules.recompile does not recompile dependencies of package

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#10785]
It's great that Meteor supports (re-)compiling node_modules since this [PR](https://github.com/meteor/meteor/pull/10603), but when doing so it doesn't take into account the dependencies of those modules.

A simple example is the latest version of the query-string module, which depends on the strict-uri-encode module. The only reason why we can't upgrade this module in our application, while still creating a working bundle for legacy clients, is because it makes use of an arrow function.

Suggested resolution: when a module is marked for recompilation it's dependencies should also be recompiled.

**Comment by KoenLav** [comment]
Let's not?

**Comment by KoenLav** [comment]
@sebakerckhof I'm getting tired of this. 

Stale-bot is not an excuse for MDG/Tinny to simply ignore issues and let them disappear. 

You guys said the stale-bot would be reevaluated, please consider this to be my personal revaluation: it's not working.

**Comment by filipenevola** [comment]
We are not doing this.

I was renaming labels, that was just what happened but I had a problem in my back and I had to stop working for a few days, this renamed is already finished and the stale-bot config as well.

I had never denied to re-open any issue 😉
