### ISSUE TITLE
1.8.2 Upgrade Babel Error on Start

### ISSUE THREAD

**Issue by carlosalvidrez** [meteor/meteor#10795]
Hi guys, just upgraded from 1.8.1 to 1.8.2 and got this error message... I have no clue what to do, please let me know what you think. Thanks!

```
W20191125-00:34:00.625(-5)? (STDERR) /Users/xxx/.meteor/packages/meteor-tool/.1.8.2.139kujy.965el++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/fibers.js:90
W20191125-00:34:00.625(-5)? (STDERR) 					return fn.apply(this, arguments);
W20191125-00:34:00.626(-5)? (STDERR) 					          ^
W20191125-00:34:00.626(-5)? (STDERR) 
W20191125-00:34:00.626(-5)? (STDERR) Error: Cannot find module '/Users/xxx/WEBAPP_ROOT/.meteor/local/build/programs/server/node_modules/@babel/runtime/helpers/objectSpread2'
W20191125-00:34:00.626(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:548:15)
W20191125-00:34:00.626(-5)? (STDERR)     at Function.Module._load (module.js:475:25)
W20191125-00:34:00.626(-5)? (STDERR)     at Module.require (module.js:597:17)
W20191125-00:34:00.626(-5)? (STDERR)     at require (internal/module.js:11:18)
W20191125-00:34:00.626(-5)? (STDERR)     at Object.require (/Users/xxx/WEBAPP_ROOT/.meteor/local/build/programs/server/boot.js:282:22)
W20191125-00:34:00.626(-5)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
W20191125-00:34:00.626(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:244:14)
W20191125-00:34:00.627(-5)? (STDERR)     at Module.moduleLink [as link] (/Users/xxx/.meteor/packages/modules/.0.14.0.n72pre.q41jp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20191125-00:34:00.627(-5)? (STDERR)     at livedata_connection.js (packages/ddp-client/common/livedata_connection.js:1:26)
W20191125-00:34:00.627(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by mwarren2** [comment]
Same here

**Comment by carlosalvidrez** [comment]
I solved it by:
(1) removing the /node_modules/ directory
(2) Changing the babel dependendy in package.json to v 7.7.4
(3) running meteor npm install

Hope that helps... yet to thoroughly test yet my app is at least now running again : )

**Comment by mwarren2** [comment]
Ah that's good.
I'm still stuck, but it's looking like the problem is ours, not Meteor's.

**Comment by mwarren2** [comment]
Ok, I've solved mine too, so you can close this.

I use docker-sync, which speeds up disk access in containers on a mac.
Removing docker-sync temporarily has solved the problem.

I now have to put it all back together again, but the problem is not 1.8.2.

So as far as I am concerned you can close this.

**Comment by mwarren2** [comment]
As far as I'm concerned I think you can close this.

At the moment it doesn't seem to be a 1.8.2 problem really.

**Comment by benjamn** [comment]
Pleas try running `meteor update babel-compiler ecmascript` to update to versions 7.4.1 and 0.13.1, which use the latest current Babel packages (7.7.4 in most cases).

**Comment by mwarren2** [comment]
@benjamn Thanks, Ben. That solved it!

**Comment by mwarren2** [comment]
One more small thing:
A `console.log('module', module)` appears to have been left hanging around. At least I can't find it among my stuff.

![Schermata 2019-11-26 alle 23 13 22](https://user-images.githubusercontent.com/10817233/69677119-7ca29e80-10a2-11ea-9779-4c2149159f91.png)

**Comment by mwarren2** [comment]
@benjamn Another rather similar problem has emerged when using docker-sync.

> Unable to resolve some modules:
> "exif-js" in /app/imports/client/ui/dbAdmin/FotoLocations.vue (web.cordova)
> 
> If you notice problems related to these missing modules, consider running:
> meteor npm install --save exif-js
> 

I can confirm that exif-js has been installed and is present in package.js,
and that without docker-sync, the problem goes away.

The same thing happens with any of the other exif modules I tried. 
I suppose they all have in common an interest in base64, can't think of anything else they all do.

**Comment by sebakerckhof** [comment]
Solved by https://github.com/meteor/meteor/issues/10795#issuecomment-558763429

**Comment by edu2969** [comment]
> I solved it by:
> (1) removing the /node_modules/ directory
> (2) Changing the babel dependendy in package.json to v 7.7.4
> (3) running meteor npm install
> 
> Hope that helps... yet to thoroughly test yet my app is at least now running again : )

Ty @carlosalvidrez, Im building in meteor 1.8.3, and changing babel depdendency (7.7.4) it works!, ty.
