### ISSUE TITLE
Custom babel plugins no longer have effect

### ISSUE THREAD

**Issue by mariusrak** [meteor/meteor#10793]
Hi, I've updated meteor from 1.9 alpha 4 to 1.9 beta 3 and then to 1.8.2. My custom babel plugins now have no effect. I've tried console output from them and it is outputting correctly, but the AST nodes are not changed.

Was there some change between the version which could cause this? I have no idea where to look, what could cause this.

I've also updated bunch of other stuff, but everything worked. When I've updated meteor, the plugin stopped working. So the only difference is meteor version from 1.9-alpha.4 to 1.8.2

**Comment by benjamn** [comment]
Have you tried `meteor reset`? Going backwards in Meteor versions isn't always as smooth as going the other direction with `meteor update`.

**Comment by mariusrak** [comment]
First I've upgraded from 1.9 alpha 4 to 1.9 beta, which was also breaking for my system. Then I've tried to go to 1.8.2. Anyway, I've tried `meteor reset` as You suggested, but it didn't help. I've also tried to downgrade to 1.8.1 and seems like this version works correctly.

**Comment by mariusrak** [comment]
I've found out that my project works with 1.9-alpha.10 and doesn't work on 1.9-beta.0 also works on 1.8.2-beta.15 but doesn't work on 1.8.2-beta.16 
After changing releases I've run meter reset.

**Comment by mariusrak** [comment]
So, I've isolated the code which wasn't working in my project into a bare installation of meteor and the code works now even on newest versions. It's weird because some plugins work and some only output to console and doesn't change the AST. I guess there's too much complexity, so I'll have to find it on my own.
