### ISSUE TITLE
nodeModules : recompile -> Doesn't recompile with array syntax

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#10791]
In Meteor 1.8.2, we now have the recompile flag (from PR #10603) - but the array syntax doesn't seem to be getting applied:

In my [Svelte Starter](https://github.com/CaptainN/meteor-svelte-starter), I had used the array syntax, and it worked in some earlier beta or RC, but it stopped working somewhere along the way.

You can see the change I needed to make to get it working again, [in this commit](https://github.com/CaptainN/meteor-svelte-starter/commit/f53b664453d76aac7210072334333fb38d8df1d6).

([Additional ref](https://github.com/meteor-svelte/meteor-svelte/issues/32))

**Comment by sebakerckhof** [comment]
@CaptainN I can't reproduce this. Can you try again? If I run the current svelte-starter with this reverted: https://github.com/CaptainN/meteor-svelte-starter/commit/f53b664453d76aac7210072334333fb38d8df1d6 (so back to array syntax). That seems to work fine for me (on Meteor 1.8.2)

**Comment by CaptainN** [comment]
Is it possible this is only a problem on Windows? I'll try it out some time this week and let you know if I'm still seeing it.

**Comment by CaptainN** [comment]
This does appear to be working again. If it turns up again I'll reopen.
