### ISSUE TITLE
Broken named import

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#10805]
### This bug report should include:
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
1.8.2
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [x] The operating system you're running Meteor on.
ubuntu
- [x] The expected behavior.
export {Products, pSchema}
import {Products} from './products/products.js'
// or {Products, pSchema}
console.log(typeof Products, 322) // == object
I20191201-08:45:01.022(0)? undefined 322

- [x] The actual behavior.
export {Products, pSchema}
import Products from './products/products.js'
I20191201-08:47:35.521(0)? object 322

- [x] A **simple** reproduction!
https://github.com/janat08/meteorShoppingCart/tree/5bcdaa4959415c2fcfdb84ce4da5d72065ef8287

**Comment by StorytellerCZ** [comment]
Your export statement is wrong.
You have `export {Products, pSchema}`
It should be `export default { Products, pSchema }`
Or you can add `export` before the individual const to achieve the same result, like:
```js
export const Products = new Mongo.Collection('products');

export const pSchema = new SimpleSchema({...});
```

**Comment by janat08** [comment]
export {a, b} is valid export statement. https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by StorytellerCZ** [comment]
:thinking: Never seen it used like that before, but the MDN docs say it should work. So the question then is how if the appropriate Babel plugin that Meteor uses accounts for this case.
@benjamn will most likely know more about this area.

**Comment by sebakerckhof** [comment]
It's because you have a circular import.
https://github.com/janat08/meteorShoppingCart/blob/5bcdaa4959415c2fcfdb84ce4da5d72065ef8287/imports/api/cols.js#L1

https://github.com/janat08/meteorShoppingCart/blob/5bcdaa4959415c2fcfdb84ce4da5d72065ef8287/imports/api/products/products.js#L6

**Comment by janat08** [comment]
closed?
