### ISSUE TITLE
Slow oplog tailing on Atlas

### ISSUE THREAD

**Issue by mbatchkarov** [meteor/meteor#10808]
Hi, 

we are using a hosted Mongo replica set on Atlas and recently started getting intermittent warnings like "Query Targeting: Scanned Objects / Returned has gone above 1000". This tends to appear once every couple of days, then we get the warning for a few hours and then it goes away on its own.

![Screenshot 2019-12-02 at 10 44 55](https://user-images.githubusercontent.com/937114/69953500-41183200-14f1-11ea-91a2-629484b15e4f.png)

The app is built in production mode with the following env variables:

```
MONGO_URL=mongodb://<USER:PASS:URL>/meteor?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
MONGO_OPLOG_URL=mongodb://<USER:PASS:URL>/local?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
```

The offending query seems to come from meteor's oplog tailing: 
```
{
  "query": {
    "find": "oplog.rs",
    "filter": {
      "ns": {
        "$regex": "^(?:meteor\\.|admin\\.\\$cmd)"
      },
      "$or": [
        {
          "op": {
            "$in": [
              "i",
              "u",
              "d"
            ]
          }
        },
        {
          "op": "c",
          "o.drop": {
            "$exists": true
          }
        },
        {
          "op": "c",
          "o.dropDatabase": 1
        },
        {
          "op": "c",
          "o.applyOps": {
            "$exists": true
          }
        }
      ],
      "ts": {
        "$gt": {
          "$timestamp": {
            "t": 1574080784,
            "i": 1
          }
        }
      }
    },
    "returnKey": false,
    "showRecordId": false,
    "tailable": true,
    "oplogReplay": true,
    "awaitData": true,
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": {
          "t": 1574524193,
          "i": 1
        }
      },
      "signature": {
        "hash": {
          "$binary": "PHh4eHh4eD4=",
          "$type": 0
        },
        "keyId": 6750552364303778000
      }
    },
    "$db": "local"
  },
  "planSummary": [
    {
      "COLLSCAN": {}
    }
  ],
  "cursorid": 37724749300,
  "keysExamined": 0,
  "docsExamined": 47116,
  "numYields": 371,
  "nreturned": 0,
  "reslen": 243,
  "locks": {
    "Global": {
      "acquireCount": {
        "r": 372
      }
    },
    "Database": {
      "acquireCount": {
        "r": 372
      }
    },
    "oplog": {
      "acquireCount": {
        "r": 372
      }
    }
  },
  "storage": {},
  "protocol": "op_query",
  "millis": 1022
}
```

Any ideas as to what might be happening would be greatly appreciated. I suspect #8598 might be related. 

- [ ] The version of Meteor showing the problem - 1.8.1
- [ ] The operating system you're running Meteor on- Linux

**Comment by StorytellerCZ** [comment]
Probably not related, but try updating your connection string to the new `mongodb+srv` version if you can. Also no additional parameters should be needed. I'm not sure if it was `retryWrites` or some other parameter that caused issues with Meteor apps.

**Comment by raphaelarias** [comment]
@StorytellerCZ We have `retryWrites` in our connection string and so far no problem (using `mongodb+srv`).

**Comment by mbatchkarov** [comment]
We tried migrating to the new mongo url format. The environment variables are now

```
MONGO_URL=mongodb+srv://user:pass@url/meteor?retryWrites=true&w=majority
MONGO_OPLOG_URL=mongodb+srv://user:pass@url/local?retryWrites=true&w=majority```

The problem still persists but seems to be happening less often. Any other tips would be very welcome. Thanks

**Comment by williamli** [comment]
If you google "meteor mongodb atlas Scanned Objects / Returned has gone above oplog" you will see that a lot of users are reporting this issue everywhere. The only way around this is to turn off the alert in Atlast until Meteor can come up with a more efficient way to scan oplog.rs.

**Comment by williamli** [comment]
The "Tuning oplog tailing" section at https://blog.meteor.com/tuning-meteor-mongo-livedata-for-scalability-13fe9deb8908 might help.

**Comment by mbatchkarov** [comment]
Thanks, that article is very helpful. One thing I'm missing is any tooling to help us decide which queries should be using tailing and which should be polling. The articles blog post fairly clear guidelines but identifying candidates for polling in a large codebase won't be easy. Is anyother aware of any good tools out there?

**Comment by sebakerckhof** [comment]
@mbatchkarov that article, while useful, actually doesn't address your issue.
Unless you disable oplog tailing in general (for every query, e.g. by including the `disable-oplog` package), every Meteor process will still tail the oplog.

The oplog is a so-called capped collection. Meaning it has a fixed size. Only those collections you can tail, meaning Mongo will notify you of updates on the collection in the natural order the updates happen. This is at the core of Meteor's reactive data layer. 
The downside of capped collections is that you can not add indexes to it. So every document has to be scanned and every matching document has to be returned and processed by Meteor.

So there's not much you can do about this warning except moving write-heavy loads on collections that are not relevant for your UI/publications to a separate cluster. Or alternatively, only use database polling, with the downsides that come with it.

The question here is, what does the warning actually imply? Is it bad to have 1000 objects returned from a tailed cursor? Our applications (of the company I work for) also runs on atlas, so I will ask the mongodb folks to get some more information regarding this warning in the light of oplog tailing.

**Comment by mbatchkarov** [comment]
At the moment it's probably not catastrophic that we get this warning since the system seems to work just fine and users are not complaining. The interesting thing is this happening in a staging/QA environment that has very little data and very few active users, so hardly anything should be writen to Mongo.

In case that helps, I attach a screenshot of all metrics available on Atlas for the past 2 months. The orange vertical bars indicate when a new master was elected. Nothing here jumps out as unusual- memory usage is perhaps a bit high but still lower than what's available.

![Screenshot_2020-02-24 Metrics Atlas MongoDB Atlas](https://user-images.githubusercontent.com/937114/75141403-c3775300-56e8-11ea-9222-5d8a22cde6c6.png)

**Comment by MarceloPrado** [comment]
Hi @mbatchkarov, we’re also facing a similar issue at my company.

We just migrated from mlab to Atlas and I’m receiving this warning 2-3 times per day. 

I noticed a weird issue which seems related to how atlas handles oplog: some callbacks from Meteor.methods don’t get fired, even though the DDP return messages correctly arrives from server. 

This issue seems to happen only on meteor methods that affects Collections with active subscriptions. The weird thing is the reactivity is working correctly, just the callback that’s never fired.

I could not reproduce this in either development or staging environment. I suppose it’s happening after a small pressure of concurrent users in production servers.

I’ll open a support ticket in atlas to ask for some help.

Did you notice any side effects with this oplog warning? Are all your subscriptions and methods working as expected?

Thanks

**Comment by Slavrix** [comment]
I have recently moved over from mLab to Atlas also.
Whilst I have not yet seen the errors that are being described above, something I have had happen is the connection timing out when a new primary is promoted.

**Comment by jnurkka** [comment]
> I noticed a weird issue which seems related to how atlas handles oplog: some callbacks from Meteor.methods don’t get fired, even though the DDP return messages correctly arrives from server.
> 
> This issue seems to happen only on meteor methods that affects Collections with active subscriptions. The weird thing is the reactivity is working correctly, just the callback that’s never fired.
> 
> I could not reproduce this in either development or staging environment. I suppose it’s happening after a small pressure of concurrent users in production servers.
> 
> I’ll open a support ticket in atlas to ask for some help.

Hi @MarceloPrado,

We're also experiencing both the MongoDB Atlas alert and this issue with method callbacks not getting fired. This cost us hours to debug and we had to write a very ugly workaround to know if the method actually completed successfully..

Did you hear back from the atlas folks? Would appreciate it if you'd share any insights you've gained on this!

**Comment by MarceloPrado** [comment]
Yes, sure @jnurkka!
I spent a week digging this issue before having Atlas to help me out. 

During this period, I created a workaround that I'm still using on production, it might make sense to share here:

```js
export const callApplyToFixDdpDelayError = (methodName, params) => {
  /*
    `Meteor.apply` fixes 'Meteor.call' not calling DDP "updated" msg on production environment for active subscriptions.
    This caused method callback to never fire.
    The root cause for the missing 'updated' msg is unknown. It seems related to the oplog collection stalling.
    
    Related Issues: 
      https://github.com/meteor/meteor/issues/7868
      https://github.com/meteor/meteor/issues/8598
      https://forums.meteor.com/t/meteor-login-method-never-invokes-callback-blocks-all-future-rpc-calls/36305

    - Marcelo T. Prado (09 March, 2020)
  */
  return new Promise((resolve, reject) => {
    Meteor.apply(methodName, [params], {
      onResultReceived: (err, res) => {
        if (err) return reject(err);
        return resolve(res);
      },
    });
  });
};
```

In the places where our callbacks weren't getting fired we changed native Meteor.call to this workaround.

When I asked Atlas if their oplog behaved differently than mLab, this is what they answered: 
> Hi Marcelo,
Sorry to hear about the issues being encountered.
One important difference we noticed between the configuration on mLab vs. Atlas is the permissions granted to the oploguser database user. The mLab oplog user is typically granted the readAnyDatabase role in addition to the read permissions on the oplog (https://docs.mlab.com/oplog/#q-how-do-i-create-a-database-user-that-can-read-both-the-oplog-and-my-database). However, the oploguser user on Atlas only has read on the 'local' database:
https://cloud.mongodb.com/v2/5e543aa32f8b4e74c2038513#security/database/users
**Could you try updating the oploguser to give the readAnyDatabase role and let us know if this resolves the issue?**

Unfortunately, I couldn't afford to test this because our customers already had suffered too much with this issue. I tried reproducing this bug in a small non-core feature in order to test the suggestion but I couldn't make it stall. Maybe you could try it out and let us know?

**Comment by vooteles** [comment]
I'm too experiencing the same issue. Yesterday I set up a new Meteor deployment on AWS Beanstalk (2 out of 5 instances running there) with Mongo on M10 in Atlas. The DB is almost empty and the app has seen almost no use during these 2 days, but despite this, I've already received about 50 alerts on email about "Query Targeting: Scanned Objects / Returned has gone above 1000". Pretty much once or twice per hour. The offending query is as @mbatchkarov described in the first post above, for oplog tailing.

I have deployed the same app before on single AWS EC2 containers with M2 and M5 tiers in Atlas during recent months and have not had any issues. Considering this, it seems odd why adding the readAnyDatabase role to the oplog user would be necessary. I'd assume there's thousands of deployments of Meteor apps running with Atlas without one.

If anyone has had any luck resolving this issue by now, please do share your experience.

**Comment by Wade-BuildOtto** [comment]
still no resolution?

**Comment by filipenevola** [comment]
Hi, if you are having issues please open a new issue.

Mostly Meteor users are using MongoDB Atlas without any issues.
