### ISSUE TITLE
[1.8.2]: typescript can't import package containing only .d.ts

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#10804]
Reproduction: https://github.com/hexsprite/meteor-repro-typescript-def-only

If a .TS file references a NPM which contains only type definitions, such as `ts-key-enum` then incorrect code is generated.

Expected: the enum is "compiled out" such that a module import is not necessary. `ts-key-enum` is an NPM package that *only* contains a .d.ts, therefore when Meteor tries to import this module it fails.

For example:

```
import { Key } from 'ts-key-enum'

alert(Key.Escape)
```

running `tsc index.ts` on this file generates:

```
"use strict";
exports.__esModule = true;
alert("Escape" /* Escape */);
```

Meteor generates this... 
```
let Key;
module.link("ts-key-enum", {
  Key(v) {
    Key = v;
  }

}, 0);
alert(Key.Escape);
```

**Comment by bbenoist** [comment]
`tsc index.ts` doesn't generates the same code because you're not using the same compiler options than meteor does. It should generate the same output if you add a `tsconfig.jon` file with correct settings (IDK where the meteor one is located).

**Comment by hexsprite** [comment]
@bbenoist the point is that the typescript enum is something that should be compiled down and not imported... and it's highlighting a difference that the Meteor build process introduces that is incompatible with an existing pure-npm TypeScript package.

I don't expect that it will be the exact same code but the generated code from TypeScript illustrates that in this scenario that it "compiles out" the module import, doing the correct thing in this case...

**Comment by bbenoist** [comment]
@hexsprite oh I see, thanks for the clarification 👍

**Comment by hexsprite** [comment]
Still relevant
