### ISSUE TITLE
Update Cordova to 9.0.1

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#10809]
Cordova lib is two versions behind.

We should update it and also its dependencies.

- Lib from 7.1.0 to 9.0.1 [release notes](https://github.com/apache/cordova-lib/blob/master/RELEASENOTES.md)
- Common from 2.1.1 to 3.2.1 [release notes](https://github.com/apache/cordova-common/blob/master/RELEASENOTES.md)
- Android from 7.1.4 to 8.1.0 [release notes](https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md)
- iOS from 4.5.5 to 5.1.1 [release notes](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md)

**Comment by CoconutTheSlayer** [comment]
Yes pleeease, this is huge because right now starting meteor app on ios with latest Xcode is impossible.

**Comment by CoconutTheSlayer** [comment]
@filipenevola do you have any estimate when this will be resolved? Sorry for spamming but we have a client presentation coming next week and we have to figure out how to run the app on ios :-D

**Comment by CyberCyclone** [comment]
@CoconutTheSlayer iOS builds find with the latest version of Xcode. The only setting I need to change is in File->Workspace Settings->Build System and use the "Legacy Build System".

The issues I'm facing a specifically to do with using Cordova plugins that have a minimum version of Cordova Android 8.

It does get a bit annoying when the main selling point of Meteor is building on multiple platforms but then isn't kept up to date.

**Comment by CoconutTheSlayer** [comment]
@CyberCyclone you are correct, the bare meteor app just started, so hopefully it will work for us. Regarding this issue they have to update https://github.com/meteor/cordova-plugin-meteor-webapp, because it's using requireCordovaModule instead of require.

**Comment by filipenevola** [comment]
@CoconutTheSlayer we are working on it, we will release a new version as soon as everything is working in the new versions.

If you want to try https://www.npmjs.com/package/cordova-plugin-meteor-webapp using `require` instead of `requireCordovaModule` check `1.7.1-beta.0`

**Comment by filipenevola** [comment]
@CyberCyclone from now on we are going to keep it as up-to-date as possible.

You can get involved here https://github.com/meteor/meteor/pull/10810

**Comment by filipenevola** [comment]
We are going to release this on Meteor 1.10. 1.10 beta is coming soon.

**Comment by filipenevola** [comment]
This was delivered in Meteor 1.10.1
