### ISSUE TITLE
Include React in “First-class citizen Technologies”

### ISSUE THREAD

**Issue by VikR0001** [meteor/meteor#10814]
In “First-class citizen Technologies”, shouldn’t React be included, as well as React Native?

**Comment by filipenevola** [comment]
@VikR0001 I think you are referring to the roadmap document https://github.com/meteor/meteor/blob/devel/Roadmap.md#first-class-citizen-technologies right? If so we probably should make clear in the roadmap document that React, Angular and Blaze are already considered as such, they even have tutorials on the Meteor website for them, examples, create command, etc.

Is that your point or am I missing something here?

Thanks for your feedback.

**Comment by VikR0001** [comment]
Awesome. Thanks, Felipe!

**Comment by filipenevola** [comment]
included https://github.com/meteor/meteor/commit/4c83f55a5b11152e137c0cf5bd08d844210a7d93
