### ISSUE TITLE
Remove console.log('module',module)

### ISSUE THREAD

**Issue by mwarren2** [meteor/meteor#10817]
Since 1.8.1 (I reckon) a `console.log('module', module)` has been appearing incessantly in my browser console.

It appears to be to do with **meteor/modules** and has been added to all of my .vue files.

```
         const modules = require('meteor/modules');

          modules.addStyles("\n.arrowTransform[data-v-1f038ea0] {\n    transform: rotate(0deg);\n    transform-origin: bottom center;\n}\n");

        var __vue_script__, __vue_template__; module.exportDefault = function(value) { __vue_script__ = value; }; (function(){ if (!module.watch) {console.log('module', module);} module.exportDefault({

```

![Schermata 2019-12-13 alle 17 30 28](https://user-images.githubusercontent.com/10817233/70825673-40cb4100-1de5-11ea-8ca3-12e027dc4c25.png)

If it's not Meteor that's doing this, please let me know.

**Comment by marvinside** [comment]
This is not meteor itself, it is vue-meteor.
See https://github.com/meteor-vue/vue-meteor/issues/382

**Comment by mwarren2** [comment]
Thanks. Closing this
