### ISSUE TITLE
How to declare "meteor.d.ts or index.d.ts" in meteor package?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#10828]
where to declare .d.ts?  1.8.2

```js
Package.describe({
  name: 'gooodrr',
  version: '0.0.1',
  summary: 'gooodrr',
  documentation: 'README.md'
})

Package.onUse(function (api) {
  api.use('typescript')
  api.mainModule('gooodrr.ts', 'server')
  api.export('Gooodrr', 'server')
})
```

where to put d.ts file?

```d.ts
declare module "meteor/gooodrr" {
    export module Gooodrr {
      function hello(say: string): string;
    }
  }
```

**Comment by benjamn** [comment]
For core packages, `meteor npm i @types/meteor` can provide some of the types, but a much better solution (in a future release of Meteor) would be for Meteor packages that use `typescript` to generate `node_modules/meteor/package-name.d.ts` files automatically, so any TypeScript-aware tool could find the most accurate types, automatically.

**Comment by afrokick** [comment]
@benjamn  But that about non-core packages? For example, i want to add a declaration file to kadira:flowrouter. What should i do?

**Comment by hexsprite** [comment]
I used the tsconfig option

```
"typeRoots": ["./typings"]
```

Then created  files inside like `meteor/iron:router.d.ts` and placed my custom typings there.

It's a stopgap until a solution like @benjamn talks about is available.

**Comment by afrokick** [comment]
@hexsprite ok, but if I'm maintainer of kadira:flowrouter, how can i include declaration file to package to prevent the developers to configure it manually via ./typings or @types/

**Comment by benjamn** [comment]
@afrokick The system I'm describing would work for any Meteor package, though I realize we might have to figure out a solution for the `:` on Windows.

**Comment by copleykj** [comment]
Is there a possibility this could be implemented in the near future?

**Comment by copleykj** [comment]
I'm not sure how much of a show stopper this would be, but I've just tried manually creating type def files under `node_modules/meteor/packageName` and it seems that any subsequent `meteor npm install` wipes these out completely. Is there any way to stop this from happening?

**Comment by SachaG** [comment]
Since Vulcan uses a package-based architecture (meaning all of our code lives inside packages) I would be very interested in this too.

**Comment by copleykj** [comment]
Would it be possible to create the definition files and store them somewhere withing the `.meteor` directory and have them found from there?

**Comment by wildhart** [comment]
Not stale.  As more people discover the benefits of typescript this will become more of a problem.

Forum discussion: https://forums.meteor.com/t/atmosphere-packages-with-typescript-definitions/54292

Possible dupe: https://github.com/meteor/meteor/issues/6177

**Comment by santiagopuentep** [comment]
> For core packages, `meteor npm i @types/meteor` can provide some of the types, but a much better solution (in a future release of Meteor) would be for Meteor packages that use `typescript` to generate `node_modules/meteor/package-name.d.ts` files automatically, so any TypeScript-aware tool could find the most accurate types, automatically.

@benjamn should I create a feature request for this? There are many problems with TypeScript and it now seems to be becoming the standard in Javascript.

**Comment by copleykj** [comment]
@santiagopuentep unfortunately when Tiny Capital aquired Meteor, @benjamn wasn't part of the deal :joy:, and so he's probably working on Apollo right now.

A feature request is probably fine, but I think the solution of adding types anywhere under the node_modules folder is going to  give problems for the simple fact that npm assumes total control of that domain and will obliterate the entire directory at will, erasing all of the changes you've made to it.

I'm not sure what the actually solution will be, but hopefully this is something that is being worked on.

**Comment by Grubba27** [comment]
We have a solution for this matter, and the docs for it are [here](https://docs.meteor.com/using-core-types.html).

[We have plans for a more robust approach](https://github.com/meteor/meteor/issues/12509), but due to Fibers matters, we have delayed this solution
