### ISSUE TITLE
findOne() defaults to polling due to missing `sort` and `ordered` options

### ISSUE THREAD

**Issue by wildhart** [meteor/meteor#10821]
Currently [`Mongo.collection.findOne()`](https://github.com/meteor/meteor/blob/2c6d316538833b1035fdaea0b0f9639e37b74275/packages/mongo/mongo_driver.js#L786) will use the polling driver by default, instead of the oplog driver, because it only uses `limit` and not `sort` or `ordered` options unless the user provides them.

This can make it less efficient if the user has oplog enabled.

I've been using my own [patch](https://forums.meteor.com/t/oplog-support-with-findone/49163/5?u=wildhart) in production for a while without any side effects:
```js
// patch findOne so that it can use oplog by explicitly stating sort & ordered parameters
const _origFindOne = Mongo.Collection.prototype.findOne;
Mongo.Collection.prototype.findOne = function() {
	if (!arguments[1]) arguments[1] = {sort: {_id: 1}};
	else if (!arguments[1].sort) arguments[1].sort = {_id: 1};
	arguments[1].ordered = false;
	return _origFindOne.apply(this, arguments);
}
```
I'd be happy to create a PR to fix [`MongoConnection.prototype.findOne()`](https://github.com/meteor/meteor/blob/2c6d316538833b1035fdaea0b0f9639e37b74275/packages/mongo/mongo_driver.js#L786) to add the `sort` and `ordered` options if they are not provided, so that everyone can benefit.

The only possible side-effect I can think of is where there are multiple matching documents, and by chance the natural sort order has been returning the 'correct' document for someone's code.  If this is considered a problem, then I could limit the addition of the extra fields to queries where an explicit `_id` is requested?

Refs:
 * https://forums.meteor.com/t/oplog-support-with-findone/49163
 * [Galaxy Guide](https://galaxy-guide.meteor.com/apm-optimize-your-app-for-oplog.html#Limit-Without-Sort)
 * https://github.com/peerlibrary/meteor-reactive-mongo/issues/5

Please either close as a non-issue, assign to a maintainer, or tag as PR's encouraged (in which case also comment on the side-effect question)...

Thanks!

**Comment by sebakerckhof** [comment]
I just verified that the change in execution plan because of the sort doesn't have an impact on DB performance. It doesn't seem to, makes sense since it can use the index, but wanted to make sure.

**Comment by wildhart** [comment]
But what if the `findOne` is on a field which **doesn't** have an index.  There is a performance hit.  My tests on localhost on a DB which otherwise only has 20 users:
```
if (!Meteor.users.findOne({testFindOne: true})) {
  console.log('creating test users..');
  for (let a=0; a<2000; a++) Meteor.users.insert({testFindOne: true, newField: 'hello'+a});
  console.log('  done');
}
console.log('total users', Meteor.users.find({}, {fields: {_id: 1}}).count());

const {performance} = require("perf_hooks")

let now = performance.now();
for (let a=0; a<2000; a++) Meteor.users.find({newField: 'hello'+a}, {
  limit: 1,
  ordered: false
}).fetch()[0];
let then = performance.now();
console.log('without sort', then - now);

now = performance.now();
for (let a=0; a<2000; a++) Meteor.users.find({newField: 'hello'+a}, {
  limit: 1,
  sort: {_id: 1},
  ordered: false
}).fetch()[0];
then = performance.now();
console.log('with sort   ', then - now);
```
The result:
```
total users 2020
without sort 3310.5404709987342
with sort    7589.222525000572
```
What's weird that it's the `fetch()` which is causing the extra delay, just doing a `find()` without a `fetch()` is quicker with sort:
```
total users 2020
without sort 46.13425400108099
with sort    32.4393410012126
```
How can that be?

This extra delay could again be eliminated by only adding the `sort` and `ordered` fields if the query is for an explicit `_id`.

**Comment by sebakerckhof** [comment]
Measuring performance in this way is not very reliable since it's mostly waiting for IO, which may vary for all kinds of reasons in an OS. Better to just look at what mongo is doing using mongo's `explain("executionStats")`

**Comment by wildhart** [comment]
In that case:
```
> db.users.find({newField: 'hello1302'}, {limit: 1}).explain("executionStats")
executionTimeMillis:  4, totalKeysExamined:    0, totalDocsExamined: 2020

> db.users.find({newField: 'hello1303'}, {limit: 1}).sort({_id:1}).explain("executionStats")
executionTimeMillis: 14, totalKeysExamined: 2020, totalDocsExamined: 2020

> db.users.find({newField: 'hello1304'}, {limit: 1}).sort({newField:1}).explain("executionStats")
executionTimeMillis:  4, totalKeysExamined:    0, totalDocsExamined: 2020
```

**Comment by sebakerckhof** [comment]
Ok, so in that case it should indeed be limited to simple `_id` selectors.
Personally, I think this behavior may confuse users even more than a simple rule (but it's not up to me to decide).

In the end, a user already has to do the same things for a regular `find`. So I think it makes more sense to just have the same rules instead of these small optimizations which aren't obvious to the user. This is also only relevant for users with one of those third-party packages anyway. So I think it should rather be added to the documentation of those packages.

**Comment by wildhart** [comment]
> This is also only relevant for users with one of those third-party packages anyway

You're right, I had gotten so used to using `reactive-publish` in all my apps over the years that I'd forgotten that publish functions aren't normally internally reactive (except for the cursor they return).  I thought this would benefit all users but it doesn't.

Either way, feel free to close as not an issue, or I'm still happy to do a PR with the caveat of only adding the extra fields on a simple `_id` query.

**Comment by sebakerckhof** [comment]
Let's keep it open until a decision has been made on the PR

**Comment by StorytellerCZ** [comment]
@wildhart if you could do a PR that would be great. I'm going to close this issue in the meantime.
