### ISSUE TITLE
package constraints error running from a checkout

### ISSUE THREAD

**Issue by pthevenet** [meteor/meteor#10822]
Hi,

I am trying to run meteor from a checkout, and when trying it on two different projects, I get similar constraint conflicts, this does not happen when running meteor installed with `curl https://install.meteor.com/ | sh`.

Operating System: 
Linux 4.19.88-1-lts x86_64 GNU/Linux

Here are the steps I did:

```sh
# getting the meteor app
git clone https://github.com/meteor/todos.git
cat todos/.meteor/release # prints METEOR@1.7.0.1

# getting the correct meteor release
git clone --branch release/METEOR@1.7.0.1 meteor-1.7.0.1
cd meteor-1.7.0.1
git submodule update --init --recursive
./meteor --help
cd ..

# now trying to run the todos app
cd todos
../meteor-1.7.0.1/meteor npm install
../meteor-1.7.0.1/meteor 
```

The last command giving me the output:

```
=> Running Meteor from a checkout -- overrides project version (Meteor 1.7.0.1)
[[[[[ ~/workspace/tmp/METEOR/todos ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.2.1_1.
   Constraints on package "coffeescript":
   * coffeescript@=2.2.1_1 <- top level
   * coffeescript@1.0.4 <- arillo:flow-router-helpers 0.5.2
   * coffeescript@1.0.4 <- zimme:active-route 2.3.2
   * coffeescript@1.0.4 <- tap:i18n 1.8.2
   * coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.11
   * coffeescript@1.0.3 <- practicalmeteor:chai 2.1.0_1
   * coffeescript@1.0.3 <- practicalmeteor:sinon 1.14.1_2

   Conflict: Constraint coffeescript@1.0.3 is not satisfied by coffeescript 2.2.1_1.
   Constraints on package "coffeescript":
   * coffeescript@=2.2.1_1 <- top level
   * coffeescript@1.0.4 <- arillo:flow-router-helpers 0.5.2
   * coffeescript@1.0.4 <- zimme:active-route 2.3.2
   * coffeescript@1.0.4 <- tap:i18n 1.8.2
   * coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.11
   * coffeescript@1.0.3 <- practicalmeteor:chai 2.1.0_1
   * coffeescript@1.0.3 <- practicalmeteor:sinon 1.14.1_2
```

I tried the same procedure on a different app with a different meteor version (following .meteor/release, 1.8.1), with similar results. I think I am missing something, but after reading the [dev guide](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md) I am stuck. I did not modify any app files nor meteor files.

Many thanks.

**Comment by sebakerckhof** [comment]
If you run meteor from a checkout, it will use the packages from the checkout. So you'll get the coffeescript package from the checkout, which is indeed not compatible with the coffeescript version required by the dependencies in your app. If you're not specifically trying to debug something in the coffeescript package, you can remove it from your meteor checkout packages folder.
