### ISSUE TITLE
After upgrade to 1.8.3 app won't load because "jQuery not found"

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#10835]
I upgraded my React-based app from 1.8.2 to 1.8.3 using `meteor update` and now the client won't load.

I get an initial error "jQuery not found"

dombackend.js:

var DOMBackend = {};
Blaze._DOMBackend = DOMBackend;

var $jq = (typeof jQuery !== ‘undefined’ ? jQuery :
(typeof Package !== ‘undefined’ ?
Package.jquery && Package.jquery.jQuery : null));
if (! $jq)
throw new Error(“jQuery not found”);

I noticed there was a new 1.8.3-split-jquery-from-blaze entry in the .finished-upgraders file so I tried adding jquery back, both as an npm package and through `meteor add jquery` but I still get that startup crash.

**Comment by sebakerckhof** [comment]
Can you share the contents of you .meteor/versions file and your package.json file?

Or even better, create a repo with a reproduction?

**Comment by KoenLav** [comment]
You need to:

meteor npm install jquery --save

**Comment by perbergland** [comment]
Solved by adding jquery as a meteor AND npm package

meteor add jquery
meteor yarn add jquery  (or meteor npm i jquery --save)

I think the upgrade notes could have been clearer (and I didn't even find them until someone pointed at the changelog)

**Comment by chmelevskij** [comment]
> Solved by adding jquery as a meteor AND npm package
> 
> meteor add jquery
> meteor yarn add jquery (or meteor npm i jquery --save)
> 
> I think the upgrade notes could have been clearer (and I didn't even find them until someone pointed at the changelog)

had similar issue following the react meteor tutorial. Fixed the same way.

**Comment by edejongh** [comment]
Brilliant guys, this worked for me too.

**Comment by yurijean** [comment]
bcrypt (meteor npm i bcrypt) npm package was causing this error on my Meteor 1.9 app, removing it solved the issue for me
