### ISSUE TITLE
How to change the value of EXPIRE_TOKENS_INTERVAL_MS

### ISSUE THREAD

**Issue by SongZhuhai** [meteor/meteor#10843]
![image](https://user-images.githubusercontent.com/18101314/71609824-9023b680-2bc6-11ea-8230-4dcbcc0f33fa.png)

**Comment by rj-david** [comment]
https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config

**Comment by sebakerckhof** [comment]
@rj-david Note that this is not exactly for what `EXPIRE_TOKENS_INTERVAL_MS` does. This is the interval at which Meteor will check for expired tokens. This can only be changed by cloning the package locally and changing the value. However, I can't think of any use case where one would want to change the interval value.

**Comment by rj-david** [comment]
Thanks for that correction @sebakerckhof

**Comment by sebakerckhof** [comment]
Closing since this isn't a bug and the question has been answered
