### ISSUE TITLE
1.8.3 does not have a Changelog - what has changed?

### ISSUE THREAD

**Issue by dns2utf8** [meteor/meteor#10846]
Dear all

https://docs.meteor.com/changelog.html does not have a changelog for 1.8.3.
Since it broke our CI pipeline I am wondering what has changed?

Cheers

**Comment by sebakerckhof** [comment]
The docs on the site haven't been updated yet, but the changelog is basically a copy of:
https://github.com/meteor/meteor/blob/devel/History.md which has the 1.8.3 info.

If your build breaks, it's likely related to the changes in the jquery package and the migration steps in the History.md file will show the necessary steps to take.

**Comment by sebakerckhof** [comment]
cc @filipenevola

**Comment by filipenevola** [comment]
It's updated now https://docs.meteor.com/changelog.html

Thanks.

**Comment by dns2utf8** [comment]
Thank you
