### ISSUE TITLE
1.8.1 - Accounts.setPassword() called on secondary Meteor-instance results in broken password for main instance

### ISSUE THREAD

**Issue by Twisterking** [meteor/meteor#10840]
So for some reason there seems to be a pretty severe bug somewhere in the `Accounts` package.

**Situation:**
- 2 Meteor instances running on separate DigitalOcean Droplets. Let's call them **main instance** and **secondary instance**.
- **main** has also a `mongod` database running on the same droplet.
- **secondary** is connected to the same `mongod` instance via standard `MONGO_URL`.

**Bug:**
- User connected to **secondary** calls `Accounts.setPassword()`.
- new password properly works on **secondary**.
- new password **DOES NOT work on main**!

**Current workaround:**
- connecting to **main** from **secondary** via `MainConnection = DDP.connect()`
- using returned DDP connection to do something like `MainConnection.call('setUserPassword')` which calls a Meteor method called 'setUserPassword' on **main**
- changed password now works on **main AND secondary** for some reason. (ha? Don't understand the logic behind this)

**expected behavior:**
Obviously changing the user's password on **secondary** should result in a password also working on **main**.

The issue was also posted here: https://forums.meteor.com/t/password-incorrect-for-login-after-accounts-setpassword-two-separate-meteor-apps-one-mongodb/51082

I hope someone can help ... I am switching to AWS Elastic Beanstalk soon and thus this is a pretty big problem for me - methods like `Accounts.setPassword()` have to work on every AWS EC2 instance/server - not only on one.

**Comment by afrokick** [comment]
Did you try to use `MONGO_OPLOG_URL`?

**Comment by Twisterking** [comment]
Until now I was not using OPLOG at all, so I have not set a `MONGO_OPLOG_URL` neither for **main** nor for **secondary**. This will change now tho, as I will switch to MongoDB Atlas.
I don't understand how this should make a difference with my password problem? Anybody any idea what the origin of my problem is?

**Comment by KoenLav** [comment]
We've experienced a similar issue which was due to a version mismatch of the bcrypt NPM package.

I would suggest comparing the bcrypt versions between these instances (and possibly other packages related to passwords).
