### ISSUE TITLE
[1.9] Error while updating from 1.8.2 to 1.9

### ISSUE THREAD

**Issue by Gorbus** [meteor/meteor#10859]
Hello,

The update did not work for me.

Some Context  :  
Tried to update from 1.8.2 to 1.9 using "meteor update". I am on Mac Os Mojave 10.14.6.
First I installed and set as current node version 12.14.0 with nvm.
I removed this line in my package.json : 

	"engines": {
		"node": "^8.15.1"
	},

Which had to be there otherwise the hosting I was using was forcing more recent version of node.

I did 

> meteor update

From the log it seems the error is with the fsevents package: 

```
916 info lifecycle fsevents@1.1.3~install: fsevents@1.1.3
917 verbose lifecycle fsevents@1.1.3~install: unsafe-perm in lifecycle true
918 verbose lifecycle fsevents@1.1.3~install: PATH: /Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ivonig/.meteor/packages/apollo/.3.0.1.t9llub.0dj7s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-1t3nqbl.72y1h/node_modules/fsevents/node_modules/.bin:/Users/ivonig/.meteor/packages/apollo/.3.0.1.t9llub.0dj7s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-1t3nqbl.72y1h/node_modules/.bin:/Users/ivonig/.meteor/packages/apollo/.3.0.1.t9llub.0dj7s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin:/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin:/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64:/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
919 verbose lifecycle fsevents@1.1.3~install: CWD: /Users/ivonig/.meteor/packages/apollo/.3.0.1.t9llub.0dj7s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-1t3nqbl.72y1h/node_modules/fsevents
920 silly lifecycle fsevents@1.1.3~install: Args: [ '-c', 'node install' ]
921 silly lifecycle fsevents@1.1.3~install: Returned: code: 1  signal: null
922 info lifecycle fsevents@1.1.3~install: Failed to exec install script
923 verbose stack Error: fsevents@1.1.3 install: `node install`
923 verbose stack Exit status 1
923 verbose stack     at EventEmitter.<anonymous> (/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
923 verbose stack     at EventEmitter.emit (events.js:210:5)
923 verbose stack     at ChildProcess.<anonymous> (/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
923 verbose stack     at ChildProcess.emit (events.js:210:5)
923 verbose stack     at maybeClose (internal/child_process.js:1021:16)
923 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
924 verbose pkgid fsevents@1.1.3
925 verbose cwd /Users/ivonig/.meteor/packages/apollo/.3.0.1.t9llub.0dj7s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-1t3nqbl.72y1h
926 verbose Darwin 18.7.0
927 verbose argv "/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/ivonig/.meteor/packages/meteor-tool/.1.9.0.xmridy.6ifyp++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
928 verbose node v12.14.0
929 verbose npm  v6.13.4
930 error code ELIFECYCLE
931 error errno 1
932 error fsevents@1.1.3 install: `node install`
932 error Exit status 1
933 error Failed at the fsevents@1.1.3 install script.
933 error This is probably not a problem with npm. There is likely additional logging output above.
934 verbose exit [ 1, true ]
```

I don't even have this package fsevents in my package-lock.json so I am a bit confused. From the logs it seems it may be caused by meteor apollo ?  Any help is welcome. I am staying at 1.8.2 for now on until further notice. Thanks in advance.

**Comment by YevhenKap** [comment]
I have the same problem. After I completely reinstall meteor, the new version doesn't work at all. I have NodeJS 13.6.0 and npm 6.13.4 installed. But  in my case the problem is with fourseven:scss package - `meteor npm` cannot fetch NPM registry: 
> **error network request to https://registry.npmjs.org/qrcode failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org**. 

I am confused now.

**Comment by benjamn** [comment]
@Gorbus Can you run `meteor npm ls | less` and search for `fsevents` by typing `/fsevents` and then enter? One way or another, you will need to make sure you have `fsevents@2.x` (ideally 2.1.2) installed, since `fsevents@1.x` is not compatible with Node.js 12 (their problem, not ours).

@YevhenKap That seems like a temporary npm registry problem that isn't related to this issue. Also, the versions of Node and npm that you have installed on your machine separately from Meteor are not likely to have any effect on Meteor's behavior, just so you know.

**Comment by Gorbus** [comment]
It says "Pattern not found" : that's the strangest thing, I don't seem to have this module anywhere and somehow it's blocking the update.

**Comment by benjamn** [comment]
@Gorbus I've just published a new version of the Meteor `apollo` package that should work better with Meteor 1.9. Try running `meteor update apollo` in your application?

**Comment by Gorbus** [comment]
@benjamn The second solution (to first remove, then update, then install) worked.

The first one said apollo package was up to date but still couldn't update meteor.

 Thanks a lot for the great and fast help ! Much appreciated.

**Comment by SachaG** [comment]
I just ran into this, fyi what worked for me was hardcoding the `3.1.0` version in my package.js (`apollo@3.1.0`). Just doing `meteor update apollo` didn't do anything, maybe because the dependency was coming from a package and not from Meteor's own `packages` file.
