### ISSUE TITLE
meteor update 1.8.3 -> 1.9: apollo@3.0.1 build failed : outdated fs-events library

### ISSUE THREAD

**Issue by nathanschwarz** [meteor/meteor#10869]
Hi there,

Can't migrate to 1.9 due to apollo package@3.0.1 installation failure.
Meteor is trying to compile  fs-events@1.1.3 to install apollo (which is very very old) because there's no prebuilds available for fs-events@1.1.3 on node@12.14.0.
any idea how to change fs-events version; or bypass apollo install on meteor@1.9 ?

I already was using apollo before the update, can we use it independently instead ?
I'm running on OSX 10.14.5.

c++ compiler: clang@9.0.0

`node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@12.14.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 

[...COMPILATION WARNINGS....]
`

**Comment by rj-david** [comment]
https://forums.meteor.com/t/meteor-1-9-is-out/51358/23?u=rjdavid

**Comment by benjamn** [comment]
Try this:
```sh
meteor remove apollo
meteor update
meteor add apollo
```
This should give you `apollo@3.1.0`, which I just released yesterday, which no longer depends on `fsevents` at all.
