### ISSUE TITLE
Excluding web.browser and web.browser.legacy throws error

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#10866]
We have a server-only process we host in Galaxy, and wanted to use the new `--exclude-archs` flag to exclude both `web.browser` and `web.browser.legacy`, since these are not necessary for this process.

However, doing so throws an error and the build fails: `Unknown run target: web.browser`

I realize this is non-standard use case, but even if we don't want to support it, we can probably display a better error message.

**Comment by sebakerckhof** [comment]
What is the full command?
`--exclude-archs` is not supported for builds, and if I try
`meteor build --exclude-archs web.browser`, it tells me: `--exclude-archs: unknown option`

**Comment by jamesmillerburgess** [comment]
Sorry, let me clarify. 

We are using `meteor run --exclude-archs web.browser.legacy, web.browser` for development on this process.

**Comment by sebakerckhof** [comment]
It's because you have a space in your arguments.

You  either need to remove the space:
`meteor run --exclude-archs web.browser.legacy,web.browser`

or add quotes
`meteor run --exclude-archs "web.browser.legacy, web.browser"`

Not much we can do on Meteor side, just how argument parsing works

**Comment by jamesmillerburgess** [comment]
Thanks!

**Comment by gregory** [comment]
i'm on 1.9 and it throws `--exclude-archs: unknown option`  - what am i doing wrong?

**Comment by hexsprite** [comment]
it's not part of 1.9, it's in 1.10 beta
