### ISSUE TITLE
node-sass@4.11 failure when upgrading to Meteor 1.9

### ISSUE THREAD

**Issue by matYang** [meteor/meteor#10871]
When upgrading to Meteor 1.9 from Meteor 1.8.1 on OSX, following error was encountered:

```
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
```

this Stackoverflow question is extremely similar to my situation:
[https://stackoverflow.com/questions/55973930/yarn-node-sass-does-not-yet-support-my-current-environment](https://stackoverflow.com/questions/55973930/yarn-node-sass-does-not-yet-support-my-current-environment)

suggested fix was updating node-sass to 4.12 from 4.11

**Comment by benjamn** [comment]
Are you using a Meteor SASS package like `fourseven:scss`, or just depending on the `node-sass` npm package in your `package.json`?

**Comment by sebakerckhof** [comment]
Meteor 1.9 runs node 12 and node-sass@4.11.0 does not work on node 12.
The suggested fix is the correct one.

**Comment by sourcerer52** [comment]
> Are you using a Meteor SASS package like `fourseven:scss`, or just depending on the `node-sass` npm package in your `package.json`?

We are using fourseven:scss and getting the same error.

**Comment by sourcerer52** [comment]
It worked now. Tried:

meteor remove fourseven:scss
meteor add fourseven:scss
meteor update

**Comment by eric-burel** [comment]
More precisely you need fourseven:scss version >= 4.12.0.
Previous version will load an older version of `node-sass` even if you update it manually using npm.
