### ISSUE TITLE
Fibers Failure unable to run project after update from 1.8.3 to 1.9

### ISSUE THREAD

**Issue by nosizejosh** [meteor/meteor#10875]
I am getting these errors preventing my app from running on windows 10 with node version 12.14.1

> d error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\oajos\AppData\Local\.meteor\packages\meteor-tool\1.9.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.9.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\oajos\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.9.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\xampp\htdocs\ns\20\SaaS\3as\node_modules\chimp\node_modules\fibers
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN tempusdominus-bootstrap-4@5.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN tempusdominus-bootstrap-4@5.1.1 requires a peer of tempusdominus-core@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\chimp\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I have tried to downgrade to 1.8.3 but still cant get past this error. Project is unable to run. I have reinstalled meteor and issue persists.
 I have tried various solutions including 

> npm install --global --production windows-build-tools    
> npm install --global node-gyp
 @benjamn @sebakerckhof 

but still no joy

**Comment by benjamn** [comment]
The `fibers@1.0.15` version is not compatible with Node.js 12. Try updating `chimp`, which seems to be depending on the old version of `fibers`?

**Comment by nosizejosh** [comment]
npm update chimp? is chimp a meteor dependency?

**Comment by nosizejosh** [comment]
As always! Thank you @benjamn  you saved me!

**Comment by nosizejosh** [comment]
hey @benjamn  this problem appears again when I try to deploy to heroku using buildpack. 
[full error reported here ](https://github.com/AdmitHub/meteor-buildpack-horse/issues/209)
do you have an idea how to force the buildpack to install a verions other than the incompatible 1.0.15?

**Comment by nesbtesh** [comment]
I have the same issue, @nosizejosh where you able to resolve it?
