### ISSUE TITLE
[1.10-beta.4] Update of mongo driver makes expired ssl on mongo connection to crash on app start (Breaking change)

### ISSUE THREAD

**Issue by pmogollons** [meteor/meteor#10876]
When updating to 1.10 on our staging env we found that app was failing to start because there was an ssl error on the mongo connection. This is actually ok and should be the default behavior, but is a breaking change as the driver on 1.9 doesnt complain or fail about this ssl issue and renewing the certs fixed the connection problem.

Should we add a disclaimer under breaking changes about this?

**Comment by filipenevola** [comment]
Hi @pmogollons yes, I think so.

It would be good to find the change in MongoDB driver that is causing this though.

Did you find it in any MongoDB release notes?

Maybe this was caused by this change `TLS Option Variants` (https://github.com/mongodb/node-mongodb-native/releases/tag/v3.4.0)
```
TLS Option Variants
This release also introduces a number of new connection string options related to TLS. In order to unify uri options across all MongoDB drivers, and to better signal the technology the driver is actually using, all ssl related options now have a corresponding tls variant. NOTE: your application will not break if you continue to use the ssl variants, but deprecation warnings will be introduced prior to the 4.x driver release.
```

**Comment by pmogollons** [comment]
Hi @filipenevola.

I was not able to find an entry on the history.md file on their repo, but comparing the 3.3 and 3.4 api docs I found that 3.3 has a default ```sslValidate: false``` and in 3.4 that should be overwriten by  the default ```tlsinsecure: false``` and the undefined ```tlsAllowInvalidCertificates```.

I think this are the changes that make the new driver fail to connect on 1.10 and not on 1.9.

**Comment by afrokick** [comment]
not stale

**Comment by filipenevola** [comment]
Hi @afrokick and @pmogollons could you try Meteor 1.10.2-beta.0 using this new option to set Mongo options https://github.com/meteor/meteor/pull/10976?

Check the docs to understand how to use it https://github.com/meteor/docs/pull/662/files
