### ISSUE TITLE
whitescreen on 1.10-beta.4

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#10879]
I've just tried upgrading from 1.8.1 to latest 1.10-beta and was facing a very strage infinite load/whitescreen error. The page was just instantly frozen and no error was logged on server/client... After some debugging it turned out that the offender was:
```
import {ChevronLeft, ChevronRight} from '@material-ui/icons';
```
Used within a Component which was dynamically imported. Changing it to:
```
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
```
made the problem go away, but still I guess there's some underlying issue worth looking into.

**Comment by sebakerckhof** [comment]
Yep, known problem: https://github.com/meteor/meteor/issues/10712
Closing as duplicate
