### ISSUE TITLE
Meteor 1.9 - Error with incompatible fibers preventing deploy to heroku with buildpack

### ISSUE THREAD

**Issue by nosizejosh** [meteor/meteor#10884]
I have been using this [heroku buildpack ](https://github.com/AdmitHub/meteor-buildpack-horse/)for a while now and just after updating to 1.9 [I am unable to deploy](https://github.com/AdmitHub/meteor-buildpack-horse/issues/209) with the buildpack. 
Error clearly has to do with incompatible fibers as seen in [previous issue](https://github.com/meteor/meteor/issues/10875). 

after several attempts, i am unsure how to solve this as I have already updated fibers to be able to get local build to work. 

Stuck and unable to deploy because of this. please help! @benjamn

**Comment by townmulti** [comment]
@nosizejosh Did you figure this out?

**Comment by townmulti** [comment]
Anyone coming here for a likely solution should look into where the compiling fails. In the example above, it fails when node is compiling `fibers@1.0.15 install` so I found that fibers verison 1.0.15 is not compatible with the currently used version of node so it crashes. The version of fibers use at this compilation or package will need to be upgraded to be compatible with the node version used. 

Use command `npm list | grep fibers` to see which package is using an outdated version.

Hope this helps.
