### ISSUE TITLE
[1.9] build-node-for-dev-bundle.sh missing nodejs makefile

### ISSUE THREAD

**Issue by holmrenser** [meteor/meteor#10885]
When trying to build meteor from a git checkout, building nodejs results in a failure due to the absence of a makefile in the downloaded tarball. This happens om my local machine (macOS 10.13.6), but also on the conda circleci client using CentOS 6.

**Expected behaviour**: a local nodejs binary built using `scripts/build-node-for-dev-bundle.sh`.

**Actual behaviour**: current scripts results in a downloaded tarball without a makefile and the following error: 
> make: *** No rule to make target `binary'.  Stop.

**Steps to reproduce**:
```
git clone https://github.com/meteor/meteor
cd meteor
git checkout 39cc07472f8f1dc820b29b8c5a30813051d62700 #V1.9.0 commit
./scripts/build-node-for-dev-bundle.sh
```
This is my first time trying to build the devbundle, so I have no record of how this worked in previous versions.

**Comment by holmrenser** [comment]
@klaussner @benjamn any thoughts?

**Comment by klaussner** [comment]
Is there a reason why you are trying to build Node.js for the dev bundle? If you run `./scripts/generate-dev-bundle.sh`, a pre-built version is downloaded automatically.

**Comment by holmrenser** [comment]
I am indeed aware of `./scripts/generate-dev-bundle.sh`, which is what I tried first. The reason for building node.js is that I am trying to deploy my [genenotebook](https://genenotebook.github.io/) through [(bio)conda](https://bioconda.github.io/). Bioconda uses centos6 for it's circleci builds, which results in a mismatch between the build containers' glibc and the glibc that was used to build meteor node. Building node in the circleci centos6 container should fix this.

Plus: regardless of my motivation for building node.js, I think this is a genuine bug?

**Comment by klaussner** [comment]
The build should work if you set `NODE_FROM_SRC` before running the script (I didn't wait until it finished but it started compiling): `NODE_FROM_SRC=true ./scripts/build-node-for-dev-bundle.sh`. If the environment variable isn't set, the script downloads a built Node.js version instead of the source.
