### ISSUE TITLE
How to use @ionic/react  normally 

### ISSUE THREAD

**Issue by gland2015** [meteor/meteor#10890]
I have these problems
1、ionicons can't be packaged, because it's SVG files.   and no related packages found，I realized one myself。
2、after, @ionic/core/dist/esm-es5/core-ca0488fc.js at line 74， 'import' is simply converted to 'module.dynamicImport', but at line 70 had use 'module' Keyword， this leads to errors.  (I have to modify it manually)
3、after, ionic component module is dynamic , like [import("./" + bundleId + ".entry.js")]，but builder is not pack those modules. I don't know what to do.
4、in addition,  I found CPU usage is still high after a successful run, 

Hope to solve the above problems, thanks

**Comment by hexsprite** [comment]
Duplicate of: https://github.com/meteor/meteor/issues/10495

See also: https://forums.meteor.com/t/meteor-does-not-work-with-ionic-react-4-or-5/51531

@gland2015, could you comment in the forums more on how you worked around 1), 2) and 3)? (code samples are great).

Here's hoping Meteor can be production-ready for Ionic soon!
