### ISSUE TITLE
METEOR@1.10-beta.4 on 127.0.0.1:9229 failed: address already in use

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [meteor/meteor#10893]
METEOR@1.10-beta.4
Windows 10

```
PS C:\localhost\DonationPhysics> meteor run
Debugger listening on ws://127.0.0.1:9229/8a82c830-b0ab-4cb5-8196-e529e967008e
For help, see: https://nodejs.org/en/docs/inspector
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

![image](https://user-images.githubusercontent.com/60403187/73581077-19b1f700-4499-11ea-8412-a0f29d793d9f.png)

of course the port is free

**Comment by klaussner** [comment]
> of course the port is free

How did you check if the port is free?

**Comment by sebakerckhof** [comment]
Either the port is not free, in which case you can pass a different port, like: --inspect=9239. Or, since you're on windows, you may be hitting this node/windows bug:
https://github.com/nodejs/node-inspect/pull/73

**Comment by MaxmaxmaximusGitHub** [comment]
> How did you check if the port is free?
How did you check if the port is free?

**Comment by sebakerckhof** [comment]
I missed the line stating the port is free. In that case you're likely seeing the node bug mentioned above. Meteor just launches a regular node process and passes those inspect variables along.

**Comment by filipenevola** [comment]
I'm closing this as we don't have any indication it is a Meteor bug.
