### ISSUE TITLE
Meteor 1.9: bad option --allow-superuser (METEOR BUILD)

### ISSUE THREAD

**Issue by raphaelarias** [meteor/meteor#10894]
We've updated our app from Meteor 1.8 to Meteor 1.9 and when deploying from our CI, we now get this error: 

```
exec: /builder/home/.meteor/packages/meteor-tool/.1.9.0.1mtsmz6.qnno++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: bad option: --allow-superuser
```

The only thing we did was update Meteor to 1.9. I checked the changelog, forum, etc but this option seems to be not very much used, so it's quite hard to find any info.

We are running the normal **meteor build** tool.

**Comment by klaussner** [comment]
I can't reproduce this with Meteor 1.9:

```
$ meteor --version
Meteor 1.9

$ meteor --allow-superuser
[[[[[ ~/Desktop/10894 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

According to the error message, you are passing `--allow-superuser` to `node` instead of Meteor. Are you using `TOOL_NODE_FLAGS`?

**Comment by raphaelarias** [comment]
This command is using when building meteor, not running in DEV. We're not passing to Node, we are passing to Meteor.

Here's the line of code: https://github.com/EducationLink/meteor-google-cloud/blob/master/src/lib/bundle.js

**Comment by klaussner** [comment]
Hm, I still can't reproduce it. I can run `meteor build --allow-superuser .` without getting an error. :thinking:

**Comment by afrokick** [comment]
@raphaelarias could you please share the output of a console/file when it building? Maybe some specific symbol in `workingDir` crash it.

**Comment by raphaelarias** [comment]
@afrokick The rest of the log doesn't really show much :/

```
> EducationLink@1.0.0 build:prod /workspace
> meteor-google-cloud --settings config/config.prod.json --app config/app.prod.yaml --docker Dockerfile --build-only --output-dir=./output --ci

info:    Validating settings file (config/config.prod.json)
info:    Validating app.yml file (config/app.prod.yaml)
info:    Reading Dockerfile (Dockerfile)
info:    Compiling application bundle

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local


WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
error:   exec: /builder/home/.meteor/packages/meteor-tool/.1.9.0.1mtsmz6.qnno++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: bad option: --allow-superuser

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! EducationLink@1.0.0 build:prod: `meteor-google-cloud --settings config/config.prod.json --app config/app.prod.yaml --docker Dockerfile --build-only --output-dir=./output --ci`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the EducationLink@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /builder/home/.npm/_logs/2020-01-31T14_35_38_105Z-debug.log
```

**Comment by sakulstra** [comment]
@raphaelarias did you ever figure out what is wrong? i'm actually running into the same error using your https://github.com/EducationLink/meteor-google-cloud library :sweat_smile:

**Comment by iamstevendao** [comment]
Hi guys, so the `bad option` error only throws when we check for the version of npm and node (`meteor npm -v --allow-superuser` and `meteor node -v --allow-superuser`), which it didn't happen before `1.9`.
@sakulstra Currently workaround is to pass `--node-version` and `--npm-version` to `meteor-google-cloud` `v1.2.0`.
