### ISSUE TITLE
[1.9] "ReferenceError: module is not defined" in reify on `module.runSetters` call

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10900]
I'm in Meteor 1.9, Linux.

I'm getting an error `Uncaught ReferenceError: module is not defined` on some output code that looks like this:

```js
        var newTarget;
        var hasNewTarget = false;
        if (supportsNewTarget) {
            module.runSetters(eval('newTarget = new.target'));
            if (newTarget)
                hasNewTarget = true;
        }
```

The original code before it goes into Meteor build looks like this:

```js
        var newTarget;
        var hasNewTarget = false;
        if (supportsNewTarget) {
            eval('newTarget = new.target');
            if (newTarget)
                hasNewTarget = true;
        }
```

Note, `newTarget` is not being `export`ed anywhere, it is a local variable inside the scope of a `function`, so I don't think there should even be a `module.runSetters` call being placed at that point.

The reason the error is uncovered at runtime is because that snippet of code is part of a `function` whose body is being retrieved with the use of `toString` in order to create a modified version of the function, and in the process of doing this, the `module` variable does not carry into the new function's scope.

I think that the `module.runSetters` call might be harmless there normally, despite it being there for a variable that is not exported (unless I misunderstand what it does), but my other code which is to `toString`ing the function is fumbling on it.

The way that I create the new Function is with explicit dependencies, like this:

```js
        newlessConstructor = Function('constructor, construct, setPrototype, requiresNew, supportsNewTarget', `
            var newlessConstructor = function ${name}() { ${code} };
            return newlessConstructor
        `)(constructor, construct, setPrototype, requiresNew, supportsNewTarget);
```

I can work around the problem by passing `module` in, although then it looks like an unused variable to anyone reading the code in the whole file:

```js
        newlessConstructor = Function('module, constructor, construct, setPrototype, requiresNew, supportsNewTarget', `
            var newlessConstructor = function ${name}() { ${code} };
            return newlessConstructor
        `)(module, constructor, construct, setPrototype, requiresNew, supportsNewTarget);
```

**Comment by trusktr** [comment]
Reproduction:

```
git clone git@github.com:infamous/umbrella.git
cd umbrella
git checkout meteor-issue-10900
cd apps/website
npm install
meteor
```

then when you open your browser console will log about 813 of these errors.

**Comment by suezzo** [comment]
I've encountered very similar problem. Did you find a solution?
