### ISSUE TITLE
[BUG] [1.9] Cannot find module 'foo', but it is there.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10909]
Meteor 1.9

I'm trying to understand if I have a Meteor issue or something else.

The runtime error I see is 

```
Uncaught Error: Cannot find module 'lowclass'
    at makeMissingError (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232)
    at Module.resolve (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:238)
    ...
```

but I'm not so sure the error is legitimate, and I _think_ that my `lowclass` module exists.

I also see this in my terminal (server-side):

```
The handle(5) returned by watching /home/trusktr/src/lume+umbrella/apps/website/node_modules/infamous/node_modules/element-behaviors/node_modules/lowclass/.git is the same with an already watched path(/home/trusktr/src/lume+umbrella/apps/website/node_modules/infamous/node_modules/lowclass/.git)
```

I wonder if it has anything to do with the problem.

When I step through the modules-runtime code, I see in `nodeModulesLookup` that it resolves to `"/node_modules/infamous/node_modules/lowclass"`, which in my case is a symlink (as hinted by the previous terminal output).

Here's what is in `/node_modules/infamous/node_modules/lowclass/package.json`:

```js
{
        "name": "lowclass",
        "type": "module",
        "main": "dist/index.js",
        "types": "dist/index.d.ts",
        "exports COMMENT:": "This removes 'dist' from import statements, as well as replaces the 'main' field. See https://github.com/nodejs/node/issues/14970#issuecomment-571887546",
        "exports": {
                ".": "./dist/index.js",
                "./": "./dist/"
        },
```

and the `dist` folder does have an index.js file:

```
❯ ls -l node_modules/infamous/node_modules/lowclass/dist/index.js
-rw-r--r-- 1 trusktr trusktr 385 Feb  9 09:54 node_modules/infamous/node_modules/lowclass/dist/index.js
```

So I am perplexed. The files are there (symlinked), but Meteor says it can not find the module.

Does this sound like a bug? Any ideas what else to check?

**Comment by trusktr** [comment]
I'm onto something. I think this is a bug. I replaced the lowclass symlink with an actual copy of the folder, and the error went away.

**Comment by trusktr** [comment]
Updated to include that I'm on Meteor 1.9

**Comment by StorytellerCZ** [comment]
`/node_modules/infamous/node_modules/lowclass/package.json`
I think your problem here is that `lowclass` is a dependency of `infamous`. Unless it is passed through `infamous` I don't think you will have access to it. The easiest option is to add `lowclass` as a direct dependency of your project.

**Comment by trusktr** [comment]
@StorytellerCZ I think it is a bug because when `/node_modules/infamous/node_modules/lowclass` is _not_ a symlink, it works. It only breaks if that file is a symlink to some other place outside of the project.

Although your suggestion might help, my project is not depending on `lowclass` APIs. The project is only importing and using APIs from `infamous`, and `infamous` uses APIs from `lowclass`, and this sort of scenario should work fine, otherwise we'd need to install every transitive dependency of the whole dependency tree.

**Comment by trusktr** [comment]
I'll see if I can swing back to post a reproduction when I get a chance.

Also, `/node_modules/infamous` is also a symlink. So both `infamous` and `lowclass` folders are actually outside of the project. I think this is somehow tripping Meteor's module resolution.

**Comment by trusktr** [comment]
Oh, and the reason things are symlinked like that is because I'm experimenting with "monorepo" tools like Lerna and Rush.js to manage multiple projects (in my case in an "umbrella repo" with git submodules), and these tool cross-link the dependencies to each other.
