### ISSUE TITLE
__dirname is not defined - markdown

### ISSUE THREAD

**Issue by marxo** [meteor/meteor#10904]
Hi,

I'm running into a problem on a fresh new app in Meteor 1.9. When I add the `markdown` package to the app, the client-side fails with the message `ReferenceError: __dirname is not defined`. No other new packages have been added. This error shows up only when `markdown` package is added. I'm using Ubuntu 18.04 LTS.

So, even this will fail with the `markdown` package added:

```
{{#markdown}} # test {{/markdown}}
```

**Comment by jordancortes** [comment]
This is a deprecated package #9737

**Comment by BrianMulhall** [comment]
I still fixed it because the only popular alternative markdown package https://atmospherejs.com/perak/markdown i found on atmosphere seemed to be abandoned. So the fix should get merged in and released in the first post 1.10 release.

**Comment by filipenevola** [comment]
I've published markdown@1.0.13.
