### ISSUE TITLE
[1.9] Compatibility with native Node.js ES Modules (in particular the package.json "exports" field).

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10906]
Meteor 1.9

The exports field is a new feature of Node.js ESM, and it is released into the wild now (Node 13.2+).

Some packages wishing to release pure-ESM code may have something like the following in package.json:

```js
	// This removes 'dist' from import statements, as well as replaces the 'main' field. See https://github.com/nodejs/node/issues/14970#issuecomment-571887546
	"exports": {
		".": "./dist/index.js",
		"./": "./dist/"
	},
```

It allows a dependent project to do this:

```js
import {foo} from 'some-dependency'
// foo was imported from node_modules/some-dependency/dist/index.js

import {bar} from 'some-dependency/path/bar.js'
// bar was imported from node_modules/some-dependency/dist/path/bar.js
```

From what I observed today on Meteor 1.8, meteor is not able to resolve dependencies that I have in my project which are publishing pure-ESM packages with `exports` maps, as Meteor will try to look for the imported files relative to the root of the package, not the mapped locations or mapped aliases.

**Comment by trusktr** [comment]
[`resolver.js`](https://github.com/meteor/meteor/blob/924b5e8c3c5ffb9c2e8b54b402eda3f8a4d28457/tools/isobuild/resolver.ts) is not to complicated and seems like the place to add `"exports"` support. I'd like to take a stab at it.

**Comment by trusktr** [comment]
Updated, added my Meteor version, 1.9.

**Comment by trusktr** [comment]
Another idea is, if Meteor can support [import maps](https://wicg.github.io/import-maps/), then it could be possible to generate import maps based on node_modules dependencies using existing tools in the JS community. 

@benjamn Any ideas on what direction to take this in?

**Comment by trusktr** [comment]
I found the following tool, which may serve as a good example (if not give us some re-usable code to build from) on how to generate import maps from Node.js-based projects using Node's module resolution rules: [@jsenv/node-module-import-map](https://www.npmjs.com/package/@jsenv/node-module-import-map).

One particular thing to note about Node.js ESM: The only way (out of the box) to import a CommonJS module into an ES Module is with `import default`, with no support for named exports (i.e CommonJS modules _only_ have a `default` export, nothing else).

For example:

```js
// ./commonjs-module-a.cjs
module.exports = {
  foo() {},
  bar() {}
}
```

```js
// ./commonjs-module-b.cjs
module.exports = function() {}
```

```js
import A from './commonjs-module-a.cjs'
// import {foo, bar} from './commonjs-module-a.cjs' // WRONG
import B from './commonjs-module-b.cjs'

A.foo()
A.bar()

B()
```

This behavior is effectively almost the same as TypeScript's `"allowSyntheticDefaultImports": true` option, which must be enabled for this to work as expected in TypeScript code.

I like this behavior, it is easy to reason about CJS exports inside ES Modules this way. Before Node ESM, it has been common to see code like

```js
/commonjs-module-c.cjs
module.exports = {
  default: function() {}
}
```

```js
// import A from './commonjs-module-a.cjs' // WRONG
import * as A from './commonjs-module-a.cjs'
import {foo, bar} from './commonjs-module-a.cjs' // OK
import * as B from './commonjs-module-b.cjs'
import C from './commonjs-module-c.cjs'

A.foo()
A.bar()
foo()
bar()

B()

C()
```

which I think has a higher mental tax and inconvenience.

**Comment by trusktr** [comment]
I really despise stale bots with a passion. They make me feel strong feelings of anger towards them. :robot::boom: • • • •  :boom::gun: 

@StorytellerCZ @filipenevola Can you please take a look and re-open this?

**Comment by trusktr** [comment]
https://github.com/meteor/meteor/issues/11631 is a duplicate of this.

**Comment by StorytellerCZ** [comment]
@trusktr we'll continue this in #11631
