### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by joshleblanc** [meteor/meteor#10913]
Meteor uses the `request` library in the HTTP package.

`request` was deprecated on February 11th, 2020.

https://github.com/request/request#deprecated

`request` is required in the following places:

* https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/http/httpcall_server.js#L2
* https://github.com/meteor/meteor/blob/1a5d6fb5b6c94f48539fa6337eb0731c23a2c127/tools/utils/http-helpers.js#L309

**Comment by harryadelb** [comment]
I have been thinking about the same thing yesterday, maybe we should consider some of the [alternatives](https://github.com/sindresorhus/got#comparison).

**Comment by sebakerckhof** [comment]
There's already the fetch package: https://github.com/meteor/meteor/tree/devel/packages/fetch
However, the semantics (especially error handling) of fetch are quite different, which is why it hasn't replaced request in HTTP.

I think the right thing to do is to deprecate the whole HTTP package and for users to migrate from HTTP to the fetch package.

The other request, in meteor tools, could quite easily be replaced with node-fetch.

**Comment by sebakerckhof** [comment]
Some related discussion: https://github.com/meteor/meteor/pull/10029#issuecomment-400231354

**Comment by evolross** [comment]
I think this might be what's causing these server console warnings:
```
(node:24729) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by evolross** [comment]
Freshen.

**Comment by StorytellerCZ** [comment]
So what should be the steps here?
Depracate the `http` package with directions to use the `fetch` package?
Then replace any use of `http` in core with `fetch`?

**Comment by hexsprite** [comment]
Sounds like deprecating the `http` package is the way to go, since `fetch` is a standard API.

**Comment by evolross** [comment]
Refresh.

**Comment by hexsprite** [comment]
I see only two usages of request, one is in the HTTP package (server only, client side uses XHR)

And in `tools/utils/http-helpers.js`.

This file has some interesting customizations on request that will need to be preserved.

```
  // A wrapper around request with the following improvements:
  //
  // - It will respect proxy environment variables if present
  //   (HTTP_PROXY or HTTPS_PROXY as appropriate).
  //
  // - It will set a reasonable User-Agent header.
  //
  // - If you omit the callback it will run synchronously. The return
  //   value will be an object with keys 'response' and 'body' (with
  //   the same meaning as the arguments to request's normal
  //   callback), or it will throw.
  //
  // - If Set-Cookie headers are present on the response, *and* you
  //   are using a callback, it will parse the cookies and include
  //   them as a setCookie attribute on the object passed to the
  //   callback. setCookie is a simple map from cookie name to cookie
  //   value. If you want expiration time and attributes you'll have
  //   to parse it yourself. If there are multiple Set-Cookie headers
  //   for the same cookie it is unspecified which one you'll get.
  //
  // - You can provide a 'bodyStream' option which is a stream that
  //   will be used for the body of the request.
  //
  // - For authenticated Meteor Software services, you can set the
  //   'useSessionHeader' and/or 'useAuthHeader' options (to true) to
  //   send X-Meteor-Session/X-Meteor-Auth headers using values from
  //   the session file.
  //
  // - forceSSL is always set to true. Always. And followRedirect is
  //   set to false since it doesn't understand origins (see comment
  //   in implementation).
  //
  // - An optional options.onRequest callback may be provided if the
  //   caller desires access to the request object.
```

**Comment by derwaldgeist** [comment]
Is there any progress on this?

**Comment by StorytellerCZ** [comment]
Started with an experimental deprecation on the `http` package today. I'll try to move the docs related to `http` package to the deprecated section and if I have enough time start on the `fetch` package documentation. But beyond that I don't feel confident time wise of being able to commit to anything more.

**Comment by jankapunkt** [comment]
If you still need to keep the `http` package (maybe it is deeply integrated in your code as in my case) but want to use the `fetch` package instead of `request` then check out my port: `jkuester:http` where I basically removed all `request` code with `fetch` from the core `fetch` package.

**Comment by StorytellerCZ** [comment]
@jankapunkt  Might be worth considering in some form in core.

**Comment by xet7** [comment]
@StorytellerCZ 

Any progress at https://github.com/meteor/meteor/pull/11305 ?

Unfortunately changing to `jkuester:http` from @jankapunkt did not help. I am unable to build Wekan https://github.com/wekan/wekan/issues/3524

**Comment by jankapunkt** [comment]
Problem is that some internal packages still use http which uses request. As a hotfix I want to PR jkuester:http into core. I was really busy whis and Last week but I intend to provide it asap.

**Comment by xet7** [comment]
@jankapunkt 

Thanks a lot !

**Comment by jankapunkt** [comment]
@xet7  Related draft PR: https://github.com/meteor/meteor/pull/11313
