### ISSUE TITLE
Typescript imported enums cause crash

### ISSUE THREAD

**Issue by ruohki** [meteor/meteor#10940]
When importing an enum from another file outside the project directory the app crashes with a message like
```Error: Cannot find module '../../types'``` the file is resolvable and other imports from that file work fine

Version: 1.9.2
This happens on Windows & the WSL

**Comment by hexsprite** [comment]
@ruohki I opened this issue earlier for something similar. Does it seem like the same issue to you?

**Comment by hexsprite** [comment]
https://github.com/meteor/meteor/issues/10804

**Comment by ruohki** [comment]
well when i run tsc over the file the correct enum values are transpiled into the code. However this just happens when i access a file outside the project folder

**Comment by MastroLindus** [comment]
in the typescript PR is stated that exporting enums is not supported: https://github.com/meteor/meteor/pull/10610
