### ISSUE TITLE
Authenticate user through multiple database on single meteor app

### ISSUE THREAD

**Issue by nasiruddin-saiyed** [meteor/meteor#10945]
I want to authenticate user on base of current Host running on browser, I'm new to meteor and  I have implemented rest api with connecting multiple databases but now to authenticate user i have implemented it using account-base, now i need to updated authentication flow with multiple database, so of the feature as database connection will be dynamic with respect to connected host.
For Ex: if request is coming from https://abcd.com then database will be name will be **abcd_db** and user collection will be **abcd_users**.

Till now for authenticating user was simple with one database, while migrating all of the collections i have managed to connect with multiple databases, but not able to find any solution for implementing user authentication with including ddp connection, I need just a single method / hook which is called after **Meteor.loginWithPassword** so i can pass my collection from my middle-ware  to the **Accounts** on server side. Below is an example for connecting / creating new collection and getting it into request action 

Also i was not able to find that request is coming from which browser url.

**Current Custom implementation** ::
![Untitled Diagram](https://user-images.githubusercontent.com/32707579/75454339-49222980-599b-11ea-97bc-702faca61b7f.png)

```
// router.js

PublicApi.addRoute('faq', {
	authRequired: true
}, {
	post: {
		authRequired: true,
		action: function () {
			const host = 'abcd'; // This is just for posting issue actual host is from connection.
			const _faq_collection = dynamicFaqs(host);
			var faq = new _faq_collection({
				showcase: showcase._id,
				title: newFaq.title,
				body: newFaq.body,
				status: newFaq.status
			});

			if (faq.save()) {
				return {
					statusCode: 200,
					body: { status: 'success' }
				};
			}
			else {
				return {
					statusCode: 400,
					body: { status: 'fail', message: 'ERROR. No se ha podido guardar el nuevo FAQ.' }
				};
			}
		}
	}
});
```
```
// faqCollection.js

var dynamicFaqsCollection = {};

const dynamicFaqs = (database_slug) => {
	
	const collection = () => {
		if (!dynamicFaqsCollection[`${database_slug}`]) {
			var database = new MongoInternals.RemoteCollectionDriver(`mongodb://localhost:27017/api-${database_slug}`);
			var coll = new Mongo.Collection(`${database_slug}_faqs`, { _driver: database });
			dynamicFaqsCollection[`${database_slug}`] = Class.create({
				name: `${database_slug}_faqs`,
				collection: coll,
				secured: true,
				fields: {
					showcase: {
						type: String,
						optional: false
					},
					title: {
						type: String,
						optional: false
					},
					body: {
						type: String,
						optional: false
					},
					status: {
						type: Boolean,
						optional: true,
						deafult: false
					}
				},
				helpers: {
					// Helpers
				},
				meteorMethods: {
					// Methods
				}
			});
		}
		return dynamicFaqsCollection[`${_slug}`];
	}

	return collection();
}

export { dynamicFaqs };

```

**Expected Output**
Implement authentication api router with user collections.

```
// router.js

PublicApi.addRoute('auth/login', {
	authRequired: false
}, {
	post: {
		authRequired: false,
		action: function () {
			const host = 'abcd'; // This is just for posting issue actual host is from connection.


			const _user_collection = dynamicUser(host);
			let auth_option = { 
                            collection: _user_collection // **Pass User collection** 
                        }; 
			let authentcate_user = Account.login(auth_option)

			if (authentcate_user) {
				return {
					statusCode: 200,
					body: { status: 'success' }
				};
			}
			else {
				return {
					statusCode: 401,
					body: { status: 'fail', message: 'ERROR. Credentials Wrong!' }
				};
			}
		}
	}
});
```

**Comment by hexsprite** [comment]
@nasiruddin-saiyed you might get a better response from the forums. Your question could be worded more clearly as well if you want the most help you can get. It sounds to me like you want to be able to pass a custom value for the user collection to the authentication functions.

**Comment by nasiruddin-saiyed** [comment]
> It sounds to me like you want to be able to pass a custom value for the user collection to the authentication functions.

I want to pass custom user collection to authentication function not custom value. Full User Collection while ongoing connection without need of recreating all connections.
