### ISSUE TITLE
Unable to upgrade to 1.10.1 release due to oauth constraints

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#10968]
Hello!

I saw the 1.10.1 release is available to test and went to give it a try... Release updates are painful on Windows :(. Takes about 3 minutes on my MacBook Pro and 30+ minutes on my Windows machine. I ultimately always end up killing node.exe the first go around and re-run the commands to update and it seems to go through better the second time?

Anyway, I'm stuck here:
```
meteor update --release=1.10.1
=> Errors while initializing project:

While selecting package versions:
error: No version of oauth satisfies all constraints: @=1.2.8, @~1.3.0
Constraints on package "oauth":
* oauth@=1.2.8 <- top level
* oauth@~1.3.0 <- top level
* oauth@1.3.0 <- accounts-oauth 1.2.0 <- accounts-facebook 1.3.2
* oauth@1.3.0 <- google-oauth 1.3.0 <- accounts-google 1.3.3
* oauth@1.3.0 <- oauth2 1.3.0 <- bluehive:accounts-instagram 0.2.2
* oauth@1.3.0 <- facebook-oauth 1.7.0 <- accounts-facebook 1.3.2
* oauth@1.2.1 <- bluehive:linkedin-oauth 3.1.0
* oauth@1.0.0 <- bluehive:accounts-instagram 0.2.2
* oauth@1.1.13 <- twitter-oauth 1.2.0 <- accounts-twitter 1.4.2
* oauth@1.3.0 <- oauth1 1.3.0 <- twitter-oauth 1.2.0 <- accounts-twitter 1.4.2
* oauth@1.1.6 <- q42:microsoft 0.1.0 <- q42:accounts-microsoft 0.1.0
```

I'm trying to understand what needs to happen here.... I'm guessing I need to update everything below 1.2.8 in the list above to something == 1.2.8 or 1.3.0? 

It shows
```
* oauth@1.3.0 <- oauth2 1.3.0 <- bluehive:accounts-instagram 0.2.2
```
though that package is actually using oauth@1.1.2? Maybe a good night's sleep will help.. I'll try again in the AM!

**Comment by filipenevola** [comment]
Hi @wreiske, it seems that q42:accounts-microsoft and bluehive:linkedin-oauth are also using old versions.

Were you able to solve this issue in your project?

**Comment by filipenevola** [comment]
I'm closing this as I didn't receive an update.

**Comment by wreiske** [comment]
Sorry, I hadn't had a chance to test. :'( I'll re-open if I find more detailed information for you. Thank you!
