### ISSUE TITLE
Pls update useraccounts-core to use latest roles and jquery.

### ISSUE THREAD

**Issue by xpressabhi** [meteor/meteor#10974]
No error.
It's not broken.
Just need some old packages to be replaced with new ones.

<img width="598" alt="Screenshot 2020-03-20 at 6 04 02 PM" src="https://user-images.githubusercontent.com/3841160/77164105-8f1f6880-6ad5-11ea-9ec5-413ea1d9c2c2.png">

**Comment by filipenevola** [comment]
Hi @xpressabhi are you sure these versions are coming from accounts-core packages?

Could you run `meteor list --tree` in your project to check where these versions are coming from?

Thanks

**Comment by xpressabhi** [comment]
Not all the packages depend upon useraccounts-core but jquery.
jquery old version is dependent upon kadira-blazelayout and core
<img width="434" alt="Screenshot 2020-03-20 at 6 35 42 PM" src="https://user-images.githubusercontent.com/3841160/77166258-efb0a480-6ad9-11ea-99a0-e3745670b476.png">
<img width="357" alt="Screenshot 2020-03-20 at 6 38 24 PM" src="https://user-images.githubusercontent.com/3841160/77166298-ffc88400-6ad9-11ea-9ff1-f668156e9892.png">

**Comment by xpressabhi** [comment]
Either update jquery to the latest version or make it npm dependent like Blaze.

**Comment by xpressabhi** [comment]
Currently jquery is bundled twice 1 for Blaze(jquery 3.0.0) and 1 for useraccounts-core(jquery 1.11.11).

**Comment by evolross** [comment]
Try doing a `meteor add jquery@3.0.0!` and that will use whatever version of `jquery` you install with `meteor npm` and not bundle it twice. It relaxes all the pre-3.0.0 requirements of your meteor packages.

**Comment by xpressabhi** [comment]
> Try doing a `meteor add jquery@3.0.0!` and that will use whatever version of `jquery` you install with `meteor npm` and not bundle it twice. It relaxes all the pre-3.0.0 requirements of your meteor packages.

Thanks
Yes, now it bundles only one jquery. 

Still, I feel all the community packages should be updated once in a while to the latest dependencies.

**Comment by filipenevola** [comment]
As `meteoraccounts:bootstrap` is [not](https://github.com/meteor-useraccounts/bootstrap) a core package I don't have a way to update it.

**Comment by xpressabhi** [comment]
The question started with useraccounts-core package.
<img width="334" alt="Screenshot 2020-03-27 at 7 31 25 AM" src="https://user-images.githubusercontent.com/3841160/77713684-020c7000-6ffd-11ea-9143-1096b916b441.png">

**Comment by hexsprite** [comment]
@xpressabhi you've opened this issue on the wrong tracker, useraccounts is not part of Meteor core.

**Comment by filipenevola** [comment]
Yeah, this would be the right repo https://github.com/meteor-useraccounts/core
