### ISSUE TITLE
Meteor Incompatible with Google Cloud Storage

### ISSUE THREAD

**Issue by asafratzon** [meteor/meteor#10984]
Hi all.

### General Description
Getting build warnings + blank screen on old mobile devices when using Meteor + Google Cloud Storage services. I run Meteor v1.10.1 (OSX) but as far as I can tell this bug was around in older Meteor versions as well.

### How To Reproduce
There are 2 different ways to access Google Cloud Storage from node.js:
1. With @google-cloud/storage library:
It's enough to run `meteor npm install @google-cloud/storage --save` and then add `const { Storage } = require('@google-cloud/storage');` somewhere in your server-side code to reproduce the build warning. [See official docs](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-nodejs).
2. With firebase-admin library:
It's enough to run `meteor npm install firebase-admin --save` and then add `let admin = require("firebase-admin");` somewhere in your server-side code to reproduce the build warning. [See official docs](https://firebase.google.com/docs/admin/setup).

### Expected Behavior
Successful build and access to google cloud storage services.

### Actual Behavior
Having tested both options 1 and 2 thoroughly, I have successfully gained access to google cloud storage services with both libraries. However both generate build warnings.
In addition it introduces compatibility issues with old apple devices (blank screens) which I suspect are related to these build issues because when I uninstall these packages the issues go away.

Here are the final output for each of the setup options:

**Option 1 Build Warning (using @google-cloud/storage):**
```
Unable to resolve some modules:

    "worker_threads" in /.../node_modules/write-file-atomic/index.js (web.browser.legacy)

If you notice problems related to these missing modules, consider running:

    meteor npm install --save meteor-node-stubs
```

**Option 2 Build Warning (using firebase-admin):**
```
Unable to resolve some modules:

    "worker_threads" in /.../node_modules/write-file-atomic/index.js (web.browser.legacy)
    "http2" in /.../node_modules/@grpc/grpc-js/build/src/call-stream.js (web.browser.legacy)
                                          
If you notice problems related to these missing modules, consider running:
                                            
    meteor npm install --save meteor-node-stubs 
```

### Important Notes
1. meteor-node-stubs doesn't solve these issues.
2. Looking at [this closed issue](https://github.com/npm/write-file-atomic/issues/41) suggests that the _worker_threads_ related warning should appear only when using node version <= v11.7.0 - but Meteor v1.10.1 uses node v12.16.1. This is the main reason I open this issue in this repository, seems like it's related to the Meteor environment.

Related Info:
 - [Related Issue in write-file-atomic module](https://github.com/npm/write-file-atomic/issues/41)
 - [VeliovGroup old similar issue](https://github.com/VeliovGroup/Meteor-Files/issues/684)
 - [Meteor Forums related thread](https://forums.meteor.com/t/meteor-1-10-1-with-google-cloud-storage-results-in-worker-threads-build-warning)

**Comment by benjamn** [comment]
Thanks for the detailed and easy-to-follow writeup @asafratzon! However, I'm not having any luck reproducing the warning, and I can successfully log the `Storage` and `admin` variables from `server/main.js` at application startup.

Just to be completely sure, what version does `meteor --version` print when you run it inside your application directory?

**Comment by asafratzon** [comment]
Thanks a lot @benjamn !

I just looked into it again and seems like you're right - printing the variables from server/main.js doesn't reproduce the warnings. You helped me notice that this issue occurs only if some file that is also required by the client is importing something from the Google Cloud Storage init file.
I hope you could have some advice on my use case, which I think is fairly common.

What I did is put the firebase setup in a `imports/firebase.js`.
Then I would like to access this connection ref from `imports/storage.js`.
`storage.js` contains a singleton which manages my storage - it is an abstraction layer so I won't need to be aware of the request context: from a client context it accesses the storage via the Firebase JS SDK and from the server context it accesses it via the node.js library (e.g. firebase-admin).

I thought it should be possible and easy with Meteor.

When I import the connection ref to this storage.js file (which is also imported by client code), I get the build warning and this warning in the browser:
```
======== WARNING! ========

firebase-admin appears to have been installed in an unsupported environment.
This package should only be used in server-side or backend Node.js environments,
and should not be used in web browsers or other client-side environments.

Use the Firebase JS SDK for client-side Firebase integrations:
```
This is totally understandable of course. But I don't understand why when I wrap the usage with a Meteor.isServer check, I don't get the browser message but I still get the build warnings.

I'm a bit puzzled now, because sometimes the use of the library server-side will be initiated by a client context (e.g. the client removes an item from mongo, I would prefer to manage the item storage removal server-side), and in that case, how could I avoid the warnings?

Even if I only import a general string from the storage init file to a client file I get the warnings (I did this test thinking of using a Meteor method for a server-side storage access).

Is this normal behavior? or is this a bad decision? Maybe I should always prefer the client SDK for storage access when I'm in a client context?

Any assistance is much appreciated.

**Comment by asafratzon** [comment]
Well I assume this is not a Meteor issue and have found and published a workaround in my previous comment. Thanks for the help.
Closing issue.
