### ISSUE TITLE
Meteor start up crash with AppCache and "--exclude-archs web.browser.legacy"

### ISSUE THREAD

**Issue by joaomframos** [meteor/meteor#10986]
Updated a Meteor app from 1.9.2 to 1.10.1 and now the following error is happening:

![image](https://user-images.githubusercontent.com/10920050/77543859-2c94e680-6ea0-11ea-8eb4-fa6d99883d66.png)
AppCache package is with version 1.2.5
Only occurs with '--exclude-archs web.browser.legacy' enabled.

**Comment by sebakerckhof** [comment]
Hmm, there's a check for that:
https://github.com/meteor/meteor/blob/devel/packages/appcache/appcache-server.js#L268

But it seems that 1.2.5 is not the latest code.

@filipenevola can you publish a new version of appcache?

**Comment by filipenevola** [comment]
Hi @sebakerckhof, it's done. Published appcache@1.2.6.
