### ISSUE TITLE
Verification failed while extracting reify@0.20.12

### ISSUE THREAD

**Issue by eugle** [meteor/meteor#10991]
meteor 1.10.1 Error deploying pm2 in docker: 
![image](https://user-images.githubusercontent.com/24447931/77875870-01d1d600-7284-11ea-9ac9-ab803ce7b96f.png)

The server is in Hong Kong, China

node version
![image](https://user-images.githubusercontent.com/24447931/77876036-74db4c80-7284-11ea-9b90-76ed89ad0a48.png)

**Comment by filipenevola** [comment]
Hi, have you tried to remove your node_modules cache and rerun it? 

Also, I see your `npm install` is not prefixed by `meteor` what can lead to different versions of npm being used. Any reason to run npm directly instead of `meteor npm install`?

**Comment by eugle** [comment]
Thank you for your reply. I used NPM when the server was deployed, and there was no meteor installed on the server，It's actually a production server deployment

**Comment by filipenevola** [comment]
I'm assuming this was solved.
