### ISSUE TITLE
Meteor less package outdated

### ISSUE THREAD

**Issue by DavidSichau** [meteor/meteor#10992]
I have some issues with the meteor less package:

1. It is quite outdated compared to less.js. This leads in our case to some problems with antd4 which requires some features available in less 3.7.0 or later. The new math mode.

2. I do not find the current location of the less package in meteor. All links point to /packages/less. However in the current develop branch this is missing. Where did it move?

3. In addition it would be nice to be able to pass options to the less compiler.

**Comment by DavidSichau** [comment]
I have created an new version with less 3.11.2:

https://github.com/DavidSichau/meteor-less

If there is an interest, I could merge my changes into the official meteor less package.

**Comment by filipenevola** [comment]
Hi @DavidSichau, Meteor less package is here https://github.com/meteor/meteor/tree/devel/packages/non-core/less

Please submit a PR updating it. Thanks.

**Comment by DavidSichau** [comment]
Hi @filipenevola 

thanks for pointing to it. I have created an pull request:

https://github.com/meteor/meteor/pull/10995

Thanks a lot.

**Comment by BrianMulhall** [comment]
@DavidSichau i tried to update this version recently, but couldn't get test group 3 and 8 to pass for some reason. the lru-cache node package that the caching-compiler atmosphere package relies on fails during testing. did you run into this problem too? i couldnt figure out what was causing it to fail

**Comment by DavidSichau** [comment]
@BrianMulhall I saw this error if an error occured in the `loadFile` methode. For example by not finding the file.

**Comment by BrianMulhall** [comment]
@DavidSichau i wasnt on the right track to fix that bug ... I am glad you came along and fixed it tho and showed me how you did it :) great work man
