### ISSUE TITLE
multiple apps on the same server: reversed proxy and meteor ressources

### ISSUE THREAD

**Issue by nathanschwarz** [meteor/meteor#10999]
Hi there,

I have 2 meteor apps on the same server.
I Have issues when I try to setup the reversed proxy for the 2 apps.

`BASE_URL` is set to `DOMAIN/auth` for the first app and `DOMAIN/customer` for the second.

I can't reach the meteor js resources because meteor set the files to the ROOT URL `/bdd878cac7f60606b37d6497341552599f743a9e.js?meteor_js_resource=true` instead of `/customer/bdd878cac7f60606b37d6497341552599f743a9e.js?meteor_js_resource=true` or `/auth/bdd878cac7f60606b37d6497341552599f743a9e.js?meteor_js_resource=true`

is it possible to set a url prefix for the compiled files ?

**Comment by larswolter** [comment]
You need to specify ROOT_URL for each app independently in their environment.
ROOT_URL=https://DOMAIN/auth for one app and ROOT_URL=https://DOMAIN/customer for the other app.

**Comment by filipenevola** [comment]
Hi @nathanschwarz I'm not sure if I understood your setup.

As you didn't reply to the last reply I'll close this but feel free to comment back here if you still have issues.
