### ISSUE TITLE
Updated to 1.10.1 - broke IOS

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/meteor#11000]
I updated the project from 1.8.3 to 1.10.1 and updated the packages to their compatible state, run it in the browser with no errors, but when I go to test it on simulator via ios-device via Xcode it just loads to a black screen, and errors all over the place. 

some of these should of come up if their were problems with the packages in the browser.

[Error] Error: Cannot find module '@babel/runtime/helpers/createSuper'
	(anonymous function) (modules-runtime.js:242)
	moduleLink (modules.js:359)
	module (random.js:398)
	fileEvaluate (modules-runtime.js:346)
	moduleLink (modules.js:366)
	module (random.js:41)
	fileEvaluate (modules-runtime.js:346)
	(anonymous function) (random.js:543)
	Global Code (random.js:550)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (mongo-id.js:19)
	Global Code (mongo-id.js:214)
[Error] TypeError: undefined is not an object (evaluating 'Package['mongo-id'].MongoID')
	(anonymous function) (minimongo.js:21)
	Global Code (minimongo.js:5020)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (retry.js:17)
	Global Code (retry.js:130)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (ddp-common.js:19)
	Global Code (ddp-common.js:604)
[Error] TypeError: undefined is not an object (evaluating 'Package.retry.Retry')
	(anonymous function) (socket-stream-client.js:17)
	Global Code (socket-stream-client.js:3403)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (ddp-client.js:19)
	Global Code (ddp-client.js:2413)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (ddp.js:14)
	Global Code (ddp.js:23)
[Error] TypeError: undefined is not an object (evaluating 'Package.minimongo.LocalCollection')
	(anonymous function) (allow-deny.js:17)
	Global Code (allow-deny.js:567)
[Error] TypeError: undefined is not an object (evaluating 'Package['allow-deny'].AllowDeny')
	(anonymous function) (mongo.js:17)
	Global Code (mongo.js:890)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (localstorage.js:17)
	Global Code (localstorage.js:100)
[Error] TypeError: undefined is not an object (evaluating 'Package['mongo-id'].MongoID')
	(anonymous function) (observe-sequence.js:19)
	Global Code (observe-sequence.js:403)
[Error] TypeError: undefined is not an object (evaluating 'Package['observe-sequence'].ObserveSequence')
	(anonymous function) (blaze.js:22)
	Global Code (blaze.js:3840)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (accounts-base.js:19)
	Global Code (accounts-base.js:1649)
[Error] TypeError: undefined is not an object (evaluating 'Package.random.Random')
	(anonymous function) (srp.js:17)
	Global Code (srp.js:1882)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (accounts-password.js:17)
	Global Code (accounts-password.js:341)
[Error] TypeError: Meteor.status is not a function. (In 'Meteor.status()', 'Meteor.status' is undefined)
	(anonymous function) (mizzao_timesync.js:158)
	_compute (tracker.js:362)
	Computation (tracker.js:232)
	(anonymous function) (tracker.js:675)
	module (mizzao_timesync.js:157)
	fileEvaluate (modules-runtime.js:346)
	(anonymous function) (mizzao_timesync.js:211)
	Global Code (mizzao_timesync.js:219)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (mizzao_user-status.js:17)
	Global Code (mizzao_user-status.js:241)
[Error] TypeError: undefined is not an object (evaluating 'Package['observe-sequence'].ObserveSequence')
	(anonymous function) (spacebars.js:17)
	Global Code (spacebars.js:331)
[Error] TypeError: undefined is not an object (evaluating 'Package.blaze.Blaze')
	(anonymous function) (templating-runtime.js:18)
	Global Code (templating-runtime.js:252)
[Error] TypeError: undefined is not an object (evaluating 'Package['templating-runtime'].Template')
	(anonymous function) (templating.js:14)
	Global Code (templating.js:23)
[Error] TypeError: undefined is not an object (evaluating 'Package['templating-runtime'].Template')
	(anonymous function) (dburles_google-maps.js:17)
	Global Code (dburles_google-maps.js:197)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (alanning_roles.js:18)
	Global Code (alanning_roles.js:966)
[Error] TypeError: undefined is not an object (evaluating 'Package.blaze.Blaze')
	(anonymous function) (ui.js:14)
	Global Code (ui.js:27)
[Error] TypeError: undefined is not an object (evaluating 'Package.ui.Blaze')
	(anonymous function) (iron_dynamic-template.js:17)
	Global Code (iron_dynamic-template.js:783)
[Error] TypeError: undefined is not an object (evaluating 'Package['templating-runtime'].Template')
	(anonymous function) (iron_layout.js:17)
	Global Code (iron_layout.js:548)
[Error] TypeError: undefined is not an object (evaluating 'Package['templating-runtime'].Template')
	(anonymous function) (iron_controller.js:21)
	Global Code (iron_controller.js:468)
[Error] TypeError: undefined is not an object (evaluating 'Package.blaze.Blaze')
	(anonymous function) (iron_router.js:17)
	Global Code (iron_router.js:1942)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (livedata.js:14)
	Global Code (livedata.js:27)
[Error] TypeError: undefined is not an object (evaluating 'Package.retry.Retry')
	(anonymous function) (autoupdate.js:19)
	Global Code (autoupdate.js:318)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	Global Code (global-imports.js:3)
[Error] ReferenceError: Can't find variable: meteorInstall
	Global Code (app.js:1)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (service-configuration.js:17)
	Global Code (service-configuration.js:73)
[Error] TypeError: undefined is not an object (evaluating 'a.ui.mouse')
	(anonymous function) (jquery.ui.touch-punch.min.js:11:361)
	Global Code (jquery.ui.touch-punch.min.js:11:1083)

**Comment by filipenevola** [comment]
Hi @Wade-BuildOtto, Node.js was also updated in Meteor 1.9, could you try to remove your node_modules and run `meteor reset` to ensure you don't have old binaries?

**Comment by Wade-BuildOtto** [comment]
worked well now down to just one error, 

Error: Cannot find module '@babel/runtime/helpers/createSuper'

**Comment by afrokick** [comment]
@Wade-BuildOtto did you try `meteor npm install @babel/runtime@latest` ?

**Comment by Wade-BuildOtto** [comment]
that worked thanks for all the help.

**Comment by trusktr** [comment]
Possibly related: https://github.com/meteor/meteor/issues/11668

It seems that due to user agent sniffing, someone may develop in Chrome but the application will not need to use ` '@babel/runtime/helpers/createSuper'` (?) but when trying to load the app in another browser, Meteor determines that ` '@babel/runtime/helpers/createSuper'` should be imported.

This is perhaps due to the more recent system that makes multiple bundles, so that it can pick which ones to use depending on old vs new browsers?
