### ISSUE TITLE
[1.10.1] Project local packages being used by build system (?!)

### ISSUE THREAD

**Issue by bolaum** [meteor/meteor#11017]
Ok, this is a weird one. Somehow, installing a specific package to meteor and to npm dependency makes android build fail. Here goes the steps to reproduce (I'm supposing android tools are properly installed):

```
$ meteor create simple-todos-build-error
$ cd simple-todos-build-error/
$ meteor add-platform android
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

...
BUILD SUCCESSFUL

$ meteor add nathantreid:css-modules
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

...
BUILD SUCCESSFUL

$ meteor npm i -S twilio
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   TypeError: outputs.join is not a function
   at Q.denodeify.then.msg
   (/home/bolaum/biscoint/tmp/simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/lib/check_reqs.js:201:40)
   at Promise_then_fulfilled (/home/bolaum/biscoint/tmp/simple-todos-build-error/node_modules/q/q.js:766:44)
   at Promise_done_fulfilled (/home/bolaum/biscoint/tmp/simple-todos-build-error/node_modules/q/q.js:835:31)
   ...

$ meteor remove nathantreid:css-modules
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

...
BUILD SUCCESSFUL

$ meteor add nathantreid:css-modules
$ meteor npm r -S twilio
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

...
BUILD SUCCESSFUL

$ meteor npm i -S twilio
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   TypeError: outputs.join is not a function
   at Q.denodeify.then.msg
   (/home/bolaum/biscoint/tmp/simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/lib/check_reqs.js:201:40)
   at Promise_then_fulfilled (/home/bolaum/biscoint/tmp/simple-todos-build-error/node_modules/q/q.js:766:44)
   at Promise_done_fulfilled (/home/bolaum/biscoint/tmp/simple-todos-build-error/node_modules/q/q.js:835:31)
   ...

$ meteor npm i -D q
$ meteor build --architecture=os.linux.x86_64 ../st-build --server=http://localhost:3000/

...
BUILD SUCCESSFUL
```

Well, as you can see, only when both `nathantreid:css-modules` and `twilio` are installed, the bug manifests. I noticed `twilio` has a dependency on `q` lib version 2.0.x and `cordova-android` depends on 1.5.1. It seems like `cordova-android` is using the version that `twilio` depends on and not its own `q` version and the `Q.denodeify()` changed its behavior between versions apparently. If I install `q` directly as a project dev dependency, it works again (WAT?!).

As to why this happens only when `nathantreid:css-modules` is installed, I couldn't find any clues.

It was a bit tricky to find the simplest way to reproduce this since it manifested in our project which is a bit huge. I'm not an expert on Meteor's build system, so I decided to open this discussion so I can get pointers from you guys on what could be happening and try to write a patch if that's the case.

**Comment by menelike** [comment]
@bolaum Not sure if this helps, but https://cordova.apache.org/announcements/2019/03/18/cordova-lib-release-9.0.0.html states that   they have dropped `q` (`GH-710 Drop Q Dependency and Use Native Promises`)

As a result, it might not be related to Meteor.

**Comment by bolaum** [comment]
@menelike I think the `cordova-android` version that meteor is currently using (8.1.0) still depends on `q`, take a look at the branch: https://github.com/apache/cordova-android/blob/f1f472297af7d3985a5769edd7272222bfd42416/bin/templates/cordova/lib/check_reqs.js#L197

Anyway, I don't think this is necessarily a meteor problem but something is not right somewhere and since it manifested here, we could join forces to investigate.

**Comment by menelike** [comment]
You're right, I don't understand why `q` is still used, especially because https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#800-feb-13-2019 states 

```
GH-463 Emulator: Add unit tests and remove Q
GH-462 Device: Add unit tests and remove Q
```


This issue might be related to https://github.com/meteor/meteor/issues/11005#issuecomment-611198592 . I am not an expert in Cordova but I assume that version 9.0 has changed the way how node modules were used.

Do `q` installed in `.meteor/local/cordova-build/node_modules` equal `1.5.1` and `q` installed in your project `node_modules` equal `2.0` even after your workaround with `meteor npm i -D q`?

What I don't understand is how `meteor npm i -D q` even lets you build as you have not installed `1.5.1`? Or in other words, `meteor npm i -D q` should have installed the same `q` version required by `twillio`?

**Comment by bolaum** [comment]
> You're right, I don't understand why `q` is still used, especially because https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#800-feb-13-2019 states
> 
> ```
> GH-463 Emulator: Add unit tests and remove Q
> GH-462 Device: Add unit tests and remove Q
> ```

Yeah. I don't get it either. 

> Do `q` installed in `.meteor/local/cordova-build/node_modules` equal `1.5.1` and `q` installed in your project `node_modules` equal `2.0` even after your workaround with `meteor npm i -D q`?

Before the workaround:
```
$ cat .meteor/local/cordova-build/node_modules/q/package.json | grep \"version\"
  "version": "1.5.1"
$ cat node_modules/q/package.json | grep \"version\"
  "version": "2.0.3"
```
After the workaround (`meteor npm i -D q`):
```
$ cat .meteor/local/cordova-build/node_modules/q/package.json | grep \"version\"
  "version": "1.5.1"
$ cat node_modules/q/package.json | grep \"version\"
  "version": "1.5.1"
```
> What I don't understand is how `meteor npm i -D q` even lets you build as you have not installed `1.5.1`? Or in other words, `meteor npm i -D q` should have installed the same `q` version required by `twillio`?

Well, at least this I can answer =D The latest version for `q` is `1.5.1` (see https://www.npmjs.com/package/q?activeTab=versions). Twilio forces the future version (https://github.com/twilio/twilio-node/blob/abf3470d89c68f5efbb6eeb811242404ec59762d/package.json#L28).

**Comment by menelike** [comment]
> The latest version for q is 1.5.1 (see https://www.npmjs.com/package/q?activeTab=versions). twilio forces the future version (2.0.x aka 2.0.3) (https://github.com/twilio/twilio-node/blob/abf3470d89c68f5efbb6eeb811242404ec59762d/package.json#L28).

Thank you, stupid me 🤦‍♂️

I think someone with some in-depth knowledge of the meteor build system needs to answer this.

What I could observe is the following (logged from `check_reqs.js`):

1. Without `nathantreid:css-modules` installed `module.paths` is:
```
[
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/lib/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/node_modules',
  'simple-todos-build-error/.meteor/local/node_modules',
  'simple-todos-build-error/.meteor/node_modules',
  'simple-todos-build-error/node_modules',
...
]
```

and `q` is resolved from `simple-todos-build-error/.meteor/local/cordova-build/node_modules`;

2. With `nathantreid:css-modules` installed `module.paths` is:
```
[
  'simple-todos-build-error/node_modules/',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/lib/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/node_modules',
  'simple-todos-build-error/.meteor/local/node_modules',
  'simple-todos-build-error/.meteor/node_modules',
  'simple-todos-build-error/node_modules',
...
]
```
and `q` is resolved from `simple-todos-build-error/node_modules/`

This leads me to the conclusion that somewhere in the build process the node packages scope is configured. I don't see any reason for the change, on both runs, the `module.paths` should be consistent. Adding `simple-todos-build-error/node_modules/` as the first element should be avoided as it is already included (AFAIK in the proper order).

**Comment by menelike** [comment]
I just saw that `nathantreid:css-modules` uses 'app-module-path': '1.0.4'.
https://github.com/patrick-steele-idem/app-module-path-node#additional-notes
says:

> App module paths will be added to the end of the default module search path. That is, if a module with the same name exists in both a node_modules directory and an application module directory then the module in the node_modules directory will be loaded since it is found first. This behavior is new in v2.x. In v1.x, this search order was reversed

https://github.com/akanix42/meteor-css-modules/blob/61c22d83698f5f2d8da3170e2085e566bd33dac8/package.js#L19

The last part made me think....

I cloned `nathantreid:css-modules` into `simple-todos-build-error/packages`, updated `app-module-path` to `2.2.0` and the build went through. 

The `module.path` now is:

```
[
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/lib/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/cordova/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/android/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/platforms/node_modules',
  'simple-todos-build-error/.meteor/local/cordova-build/node_modules',
  'simple-todos-build-error/.meteor/local/node_modules',
  'simple-todos-build-error/.meteor/node_modules',
  'simple-todos-build-error/node_modules',
...
  'simple-todos-build-error/node_modules/'
]
```
The ordering now has changed!

@bolaum Can you confirm this as well?

### Conclusion

I think this issue needs to be addressed in `nathantreid:css-modules` instead.

**Comment by bolaum** [comment]
@menelike wow! Congrats on the debugging skill =D

I'll try to reproduce your findings tomorrow and will open an issue on `nathantreid:css-modules` repo and refer this thread.

Thanks!!!
