### ISSUE TITLE
Cannot update meteor 1.4.2.7

### ISSUE THREAD

**Issue by anhpt86** [meteor/meteor#11019]
Hi,

I have a project which was built from 2017 and now client wants to reuse it to save time and cost but for some reason, I have to update the meteor for push notification issue.

I tried many times but still get the below issue.

=> Errors while initializing project:         
                                              
While selecting package versions:
error: Conflict: Constraint babel-compiler@6.8.0 is not satisfied by babel-compiler 7.5.3.
Constraints on package "babel-compiler":
* babel-compiler@~7.5.2 <- top level
* babel-compiler@7.5.2 <- ecmascript 0.14.2 <- allow-deny 1.1.0 <- mongo 1.9.0
* babel-compiler@7.5.2 <- ecmascript 0.14.2 <- angular2-compilers 0.6.0
* babel-compiler@7.5.0 <- standard-minifier-js 2.6.0
* babel-compiler@7.5.0 <- minifier-js 2.6.0 <- standard-minifier-js 2.6.0
* babel-compiler@6.8.0 <- urigo:static-html-compiler 0.1.8 <- angular2-compilers 0.6.0
* babel-compiler@6.6.4 <- barbatus:css-compiler 0.4.1 <- angular2-compilers 0.6.0

What can I do to resolve it?

Many thanks.

**Comment by brucejo75** [comment]
This is more of a question that is appropriate in the forum: https://forums.meteor.com/.  You should close this bug.

To answer your question: try upgrading `angular2-compilers` to the latest release.

**Comment by anhpt86** [comment]
I found the way to upgrade meteor. Pls remove all plugin in .meteor/packages file and run 'meteor update'.
