### ISSUE TITLE
meteor create --full references kadira:flow-router

### ISSUE THREAD

**Issue by vparpoil** [meteor/meteor#11014]
`meteor create --full` comes with these dependencies in `.meteor/packages` :
```
kadira:flow-router      # FlowRouter is a very simple router for Meteor
kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
```
(see [here](https://github.com/meteor/meteor/blob/efeccc85d6c192cfce955423f4db640e330d7d89/tools/static-assets/skel-full/.meteor/packages#L22))

Since [this PR](https://github.com/meteor/guide/pull/834) updates the recommended router in the Meteor Guide to `ostrio:flow-router-extra`, it seems a good idea to update the packages proposed in the full app as well.

I can work on a PR if you feel this is needed. And maybe also update the todos example app

**Comment by dr-dimitru** [comment]
@vparpoil Let me know if you need help with it, at least I'd be happy to review your PR.
Also, I'm working on removing `kadira:blaze-layout` from docs as FlowRouter Extra has it's own `this.render()` available in every hook.

**Comment by dr-dimitru** [comment]
Not stale, just pending

**Comment by filipenevola** [comment]
Please make a PR updating the skeleton.

**Comment by vparpoil** [comment]
@filipenevola already done : https://github.com/meteor/meteor/pull/11044

**Comment by filipenevola** [comment]
Yeah, my bad, it's merged 😉
