### ISSUE TITLE
[1.10.1] Create react is broken

### ISSUE THREAD

**Issue by linegel** [meteor/meteor#11029]
### This bug report should include:
`meteor --create react` just doesn't work 
- [ ] The version of Meteor showing the problem - 1.10.1
- [ ] OS - macOS
- [ ] The expected behavior - created app with react starter
- [ ] The actual behavior - help showed instead
- [ ] Re-pro: just run `meteor --create react`
<img width="562" alt="Screen Shot 2020-04-24 at 04 35 39" src="https://user-images.githubusercontent.com/1746296/80165998-7f6bd600-85e5-11ea-9eed-e93809b183c5.png">

**Comment by afrokick** [comment]
`meteor create --react my-react-app`

**Comment by abuuzayr** [comment]
I just ran this and its fine. @afrokick's command is correct, @linegel your command is wrong
