### ISSUE TITLE
Account.createUser throw exception with exactly email address

### ISSUE THREAD

**Issue by thanhpn** [meteor/meteor#11027]
I am using Meteor to 1.9.2 and Node to 12.16.1 
I had a bug when create account with email: dthieu@ictu.edu.vn
the function Account.createUser throw exception:

{"isClientSafe":true,"error":403,"reason":"Email already exists.","message":"Email already exists. [403]","errorType":"Meteor.Error"}

but i check in the DB, this email does not exited 

Something wrong

**Comment by pmogollons** [comment]
It might exist but with any of the letters capitalized. Try looking in the database for the same email but in a case insensitive query.
