### ISSUE TITLE
Accounts-base - Log out without unstore token

### ISSUE THREAD

**Issue by GabinH** [meteor/meteor#11028]
Hello,

I use accounts-base for my project, and I would like to open a connection from external people during x days.

To open this connection, I create a token (`Accounts._generateStampedLoginToken`) and I insert it in a special user (`Accounts._insertLoginToken`).

Next I can log in with this token (`Accounts.loginWithToken`).

The problem is when I log out, this destroy my token in my database whereas I would like the possibility to reconnect to this token.

How can I do that ? Is there a way the add an options or something to bypass the `this._unstoreLoginToken()`when log out ?

I use Meteor 1.8 and accounts-password 1.5.1

Thanks.

**Comment by StorytellerCZ** [comment]
We could potentially add a hook to check if the token is to be deleted. You could fork the package locally if you want. A workaround would be to create a new token for the user after login. This would probably also be a bit more secure.
