### ISSUE TITLE
[1.10.1] hot code push doesn't work on android

### ISSUE THREAD

**Issue by delki8** [meteor/meteor#11024]
### reproduction recipe:

```
meteor create hotcodepush-android-fail
cd hotcodepush-android-fail
meteor add-platform android
meteor run android
// wait for the emulator to be opened
// access localhost:3000 on your browser
// change anything inside main.css or main.js
```

the browser version will be refreshed as expected but the android app will not

if you open a chrome tab and inspect the app running on android (by typing chrome://inspect) you'll be able to see a few errors:

> Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED
> 10.0.2.2:3000/sockjs/info?cb=85s3p45w5l:1 Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED
> :12504/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> 10.0.2.2:3000/sockjs/info?cb=4c1uttvyid:1 Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED
> 10.0.2.2:3000/sockjs/info?cb=7jorzinuho:1 Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED
> socket-stream-client.js?hash=0fa9415090a2740bf6f5d60beaef76f661180b95:1065 GET http://10.0.2.2:3000/sockjs/info?cb=_biwrt3dzj net::ERR_CLEARTEXT_NOT_PERMITTED

Those errors disappear if you add a mobile-config.js with the following content:
```
App.appendToConfig('<edit-config file="app/src/main/AndroidManifest.xml"
                     mode="merge"
                     target="/manifest/application"
                     xmlns:android="http://schemas.android.com/apk/res/android">
        <application android:usesCleartextTraffic="true"></application>
    </edit-config>
');
```

After this, the error changes to

> Error: Error downloading asset manifest
>     at webapp_local_server.js:51
>     at Object.callbackFromNative (cordova.js:287)
>     at <anonymous>:1:9

~Which I believe to be almost the same issue reported here: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/91.~
I read the 91 cordova-plugin-meteor-webapp a little more and decided it wasn't the same problem. So I started a new issue to address the second error: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/93

The user shouldn't have to manually add the `mobile-config.js` file.

- env: ubuntu 19.04
- browser: chrome v 81.0.4044.92 (Official Build) (64-bit)
- android emulator: Pixel_3a_API_29

**Comment by joyjiyuan** [comment]
try add

**Comment by joyjiyuan** [comment]
App.appendToConfig(`
    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
        <application android:usesCleartextTraffic="true"></application>
    </edit-config>
`);

**Comment by joyjiyuan** [comment]
try add this  to you mobile-config.js

**Comment by menelike** [comment]
AFAIK this is the normal behavior since Android 6.0. See https://developer.android.com/training/articles/security-config for more information.

If you ask me this is nothing Meteor or Cordova can solve. Also, this should not happen in production as you usually use valid TLS certificates there.

One could argue, that Meteor or Cordova should add `android:usesCleartextTraffic="true"` when in development mode (maybe switch that in the gradle script), but this path might raise security concerns.

**Comment by alanning** [comment]
I was able to confirm hot code push is working with a default Meteor Android app when SSL is used.  

Here's the steps I used:

    1. Set up a free ngrok account.
    2. In one terminal: ./ngrok http 3000
    3. In another terminal: meteor run android --mobile-server https://<hashFromStep2>.ngrok.io

When I edit the main.html file the Android emulator refreshes as expected.

**Comment by delki8** [comment]
Meteor [docs](https://docs.meteor.com/packages/autoupdate.html) were updated to reflect this behavior and enable cleartext is now mandatory in order to have HCP working on Android. So I'm closing this issue.
