### ISSUE TITLE
[1.10.1] Some cordova plugins crash Cordova build 

### ISSUE THREAD

**Issue by mateusz-golebiowski** [meteor/meteor#11038]
Some cordova plugins (e.g [cordova-plugin-proximity](https://github.com/awoken-well/cordova-plugin-proximity)) makes  cordova build failed.
The problem also occurs with all scoped plugins which are stored on private npm repository
## Environment:
- Meteor v1.10.1
- The last version of Meteor where the problem did not occur.: 1.9

## How to reproduce
1. Clone [This repository](https://github.com/mateusz-golebiowski/meteor-cordova-bug)
2. Run meteor npm install
3. Run `meteor run android`

## Expected behavior:
Cordova plugin should be installed and Meteor android app should start

## Actual behavior:
Error during cordova-plugins installation 
<details>
  <summary>Log</summary>

  ```
=> Started proxy.                             
=> Meteor 1.10.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                                                                
/home/mateusz/.meteor/packages/meteor-tool/.1.10.1.q84j1g.hx5j++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Some Cordova plugins installation failed: (cordova-plugin-proximity).
    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:768:13)
    at CordovaProject.ensurePluginsWereInstalled (/tools/cordova/project.js:765:12)
    at /tools/cordova/project.js:726:14
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:584:18)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:242:10)
    at /tools/cordova/runner.js:78:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
    at /tools/runners/run-app.js:661:25
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at AppRunner._runOnce (/tools/runners/run-app.js:660:39)
    at AppRunner._fiber (/tools/runners/run-app.js:927:28)
    at /tools/runners/run-app.js:401:12


  ```
</details>

I think that there is problem with difference in id in plugin.xml name in package.json
For example:
-  [cordova-plugin-proximity](https://github.com/awoken-well/cordova-plugin-proximity) has in  `plugin.xml` `id="org.awokenwell.proximity"` and package.json  `name="cordova-plugin-proximity"`
- scoped plugins names looks like `@scope/pluginname` which also can be cause of fail in ` CordovaProject.ensurePluginsWereInstalled`

It looks like [commit](https://github.com/meteor/meteor/commit/b3c1700fdff4f7b671c8ba11f062b2b50da13172) makes problem. I reverted this commit locally and It started works.

**Comment by filipenevola** [comment]
It will be included on 1.10.3.
