### ISSUE TITLE
[1.10.1] Unable to authenticate when install cordova plugins from private repository

### ISSUE THREAD

**Issue by mateusz-golebiowski** [meteor/meteor#11032]
We use nexus repository to store some npm packages. After update to Meteor 1.10.1 authentication with our private repository stop works for cordova plugins (it still works for packages added in package.json)

To auth with nexus repo we store npm token in `.npmrc` which is located in our meteor project. 

## Environment:
- Meteor v1.10.1
- OS: MacOS v10.15.4
- The last version of Meteor where the problem did not occur.: 1.9

## How to reproduce
1. Add private plugin to `.meteor/cordova-plugins`
2. Configure private repository in `.npmrc` in meteor project
<details>
  <summary>Example</summary>

  ```
@scopeName:registry=https://nexus.url.com/repository/scopeName/
//nexus.url.com/repository/scopeName/:always-auth=true
//nexus.url.com/repository/scopeName/:_authToken=${NPM_TOKEN}

  ```
</details>
3. Run `meteor run android --verbose`

## Expected behavior:
Cordova plugin should be installed and Meteor android app should start

## Actual behavior:
Error during cordova-plugins installation 
<details>
  <summary>Log</summary>

  ```
%% fetch: Installing @scopeName/plugin-name@1.0.7 to /Users/mgolebiowski/meteor-project/.meteor/local/cordova-build
%% Running command: npm install @scopeName/plugin-name@1.0.7 --no-save            
%% Command finished with error code 1: npm install,@scopeName/plugin-name@1.0.7,--no-save
=> Errors executing Cordova commands:                                             
                                                                                  
   While adding plugin @scopeName/plugin-name@1.0.7 to Cordova project:           
   Cordova error: Failed to fetch plugin @scopeName/plugin-name@1.0.7 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: npm: Command failed with exit code 1 Error output:
   npm ERR! code E401
   npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

  ```
</details>

**Comment by loliarz** [comment]
I have same problem.
