### ISSUE TITLE
Update MongoDB to pull in ns not found fix

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#11046]
My contribution has finally made it upstream into MongoDB to help diagnose the "ns not found" errors commonly found in meteor projects I've worked within the past.

https://github.com/mongodb/mongo/commit/485fdf001d39c7f809ead645d5d892b5094e9431

I'm not sure what it would entail getting this included in Meteor's Mongo driver. I figured I'd post this here to get some visibility to it.

My commit to Mongo shows more debug information about the ns not found to give a clearer understanding to the person trying to debug the ns issues. 

More information here: https://github.com/mongodb/mongo/pull/1328

Before:
```
> db.test.dropIndex({});
{
        "ok" : 0,
        "errmsg" : "ns not found",
        "code" : 26,
        "codeName" : "NamespaceNotFound"
}
```
After:
```
> db.test.dropIndex({});
{
        "ok" : 0,
        "errmsg" : "Namespace 'test.test' not found when dropping index",
        "code" : 26,
        "codeName" : "NamespaceNotFound"
}
```

**Comment by sebakerckhof** [comment]
The mongo dev version is specified here: https://github.com/meteor/meteor/blob/devel/scripts/build-dev-bundle-common.sh#L9

and this is how meteor downloads it when you generate a new dev bundle.
https://github.com/meteor/meteor/blob/devel/scripts/generate-dev-bundle.sh#L58-L77

So the easiest way would be to modify that script or wait for a release of mongo that includes it.
