### ISSUE TITLE
[1.10.2] Creating new project on Windows lasts forever

### ISSUE THREAD

**Issue by alutom** [meteor/meteor#11040]
Hi, I would like to help, but don't know where to start. As many other Windows users, I experience random freezes when creating a new meteor app, especially on fresh install of meteor. The process doesn't end even after a few hours. I did some investigation, and found out the process always freezes in one of these two places:

https://github.com/meteor/meteor/blob/71f67d9dbac34aba34ceef733b2b51c2bd44b665/tools/utils/utils.js#L543
https://github.com/meteor/meteor/blob/71f67d9dbac34aba34ceef733b2b51c2bd44b665/tools/isobuild/meteor-npm.js#L901

This is probably the root cause of https://github.com/meteor/meteor/issues/7688, and many other similar issues I have found on the internet.

What I have found out is that if I change implementation of these two places to use `spawnSync` instead of `execFile`, everything runs smoothly, and the process finishes in a reasonable time. How can I proceed to get it possibly fixed in the official repo?

**Comment by sebakerckhof** [comment]
https://github.com/meteor/meteor/issues/7688 I believe is different. Since there it doesn't actually hang forever, just for a really long time (not hours though). That one seems related to windows defender.

**Comment by filipenevola** [comment]
The workaround didn't work. Even avoid the npm installation in the creation process for Windows it was hanging in a different spot "updating package catalog".

**Comment by diavrank** [comment]
Freeze on "Installing npm dependencies".

![image](https://user-images.githubusercontent.com/39581375/114321055-787ff100-9ade-11eb-80eb-27ffefe42803.png)

And Windows Defender is disabled:

![image](https://user-images.githubusercontent.com/39581375/114321106-acf3ad00-9ade-11eb-8ac7-c0252679ae97.png)
![image](https://user-images.githubusercontent.com/39581375/114321149-e0ced280-9ade-11eb-9f36-8175354c0c64.png)

**Comment by StorytellerCZ** [comment]
@zodern does #11608 help with this?

**Comment by filipenevola** [comment]
Yes, this issue should not happen anymore in Meteor 2.4.

**Comment by diavrank** [comment]
Good news for Windows users. I am not one of them anymore, but I will test that in my other computer.
