### ISSUE TITLE
[Typescript & Less] Import statements mistakenly imports .less 

### ISSUE THREAD

**Issue by javoire** [meteor/meteor#11041]
Hi. I encountered an odd behavior when upgrading my project to use Typescript, and after some time debugging I've narrowed it down to the Less package. But that's as far as I could get.

I have not found a solution nor this issue mentioned anywhere else so I believe it's new.

**Actual behavior**:
In a Typescript enabled project, when importing a file and there exists a `.less` file next to it (eg `App.tsx` and `App.less`) the `.less` file is imported and React crashes.

**Expected behavior**:
In a typescript enabled project, when importing a file and there exists `.less` file next to it (eg `App.tsx` and `App.less`) the `.tsx` file is imported.

**Test case**:
Here: https://github.com/javoire/meteor-typescript-less-testcase

And this is how to reproduce it:

```sh
# run the app without Less and it renders fine:
$ meteor

# Add Less
$ meteor add less

# run the app and React crashes on the import of '/imports/ui/App'
# as it reads the App.less instead of App.tsx
$ meteor
```

I did the same experiment with a fresh non-Typescript app (`meteor create --react`) and this error did not occur, so seems like a combo of Typescript and Less that's causing it.

I've also tried with a "vanilla" Typescript app (one file importing another) and it ignores the Less file as expected when invoking `tsc`. Also using the `tsconfig.json` from the meteor test case. So it does not seem to be connected to Typescripts module resolution.

**Version:** 1.10.2
**OS**: Linux on windows (WSL)

**Comment by afrokick** [comment]
It is the old issue. We use style.less filename as workaround.

**Comment by afrokick** [comment]
#10708

**Comment by javoire** [comment]
Ah yes that looks like the same issue. So it's not about less, but rather style files.

I have too thought about the workarounds mentioned in there, but a solution would be preferable!

I'll follow up in the other thread.

**Comment by javoire** [comment]
Any thoughts on https://github.com/meteor/meteor/issues/10708#issuecomment-623746555?

**Comment by jonlachlan** [comment]
Seems like you have a real bug there.
