### ISSUE TITLE
Fact-base package ,  `Facts.resetServerFacts()` function not available at runtime.

### ISSUE THREAD

**Issue by obonyojimmy** [meteor/meteor#11062]
### The Issue
When using fact-base package, exported function  `Facts.resetServerFacts()`  is not available in server runtime functions , see attached screen-shot of the error 

![fact-base-bug](https://user-images.githubusercontent.com/14318239/82107675-39acb400-9732-11ea-9f7c-708b17275acf.png)

### Expectation
Expected `Facts.resetServerFacts()` to be available as per https://github.com/meteor/meteor/blob/devel/packages/facts-base/facts_base_server.js#L48

### How Reproduce
Call _Facts.resetServerFacts()_ in forexample `Meteor.startup()` hook.

Reproduction Repo : https://github.com/obonyojimmy/meteor-facts_base-bug

**Comment by hexsprite** [comment]
Strange. It seems like the published code for `facts-base` is missing that method, even though it's present in the devel branch. Perhaps a new version needs to published.

Ahh, yes I checked the history and it seems like that method was added 3 months ago and a new release was never cut.
