### ISSUE TITLE
Cordova build: Cannot find plugin.xml

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#11065]
This is to revive #8998 (and #8196 and #7029) which has been closed, but the issue hasn't been resolved yet.

Even on Meteor 1.10.2, if you have Cordova plugins which reference other Cordova plugins, the Cordova build only works for one time. If you try to do it a second time, it fails because it can't delete files it expects to be there.

When I tried to trouble-shoot this a long time ago (see the other issues), I found out that plugin files are deleted while other parts of the build script still expect to delete them as well.

The only workaround so far is to delete `cordova-build` before each cordova build, which is increasing build times significantly. When I first encountered this problem, I could also workaround this by adding the plugins referenced by other plugins to the `cordova-plugins` file. But this trick doesn't work anymore.

**Comment by lnufnu** [comment]
I do not get the plugin.xml error. My build works but the default Cordova plugins are missing from my bundle. Following [this](https://github.com/meteor/meteor/issues/8196#issuecomment-355420160) from one of those issues, when I remove Cordova plugins and add them back in or remove `cordova-build`, some plugins are missing.

Here is a part of the log:

```
MeteorWebApp: Loading asset bundle from directory file:///android_asset/www/application
MeteorWebApp: Asset / found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application
MeteorWebApp: Asset /__cordova/packages/meteor.js found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application
MeteorWebApp: Asset /cordova.js not found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application, no parent bundle
MeteorWebApp: Asset /__cordova/packages/meteor-base.js found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file://
MeteorWebApp: Asset /cordova_plugins.js not found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application, no parent bundle
MeteorWebApp: Asset /plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js not found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application, no parent bundle
MeteorWebApp: Asset /plugins/cordova-plugin-splashscreen/www/splashscreen.js not found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application, no parent bundle
MeteorWebApp: Asset /plugins/cordova-plugin-statusbar/www/statusbar.js not found in bundle e4eff766174f200c60abee59b877c85a0d79c475:file:///android_asset/www/application, no parent bundle
```

Environment
Meteor 1.10.2
cordova-plugin-meteor-webapp@1.9.1 
cordova-plugin-splashscreen@4.1.0 
cordova-plugin-statusbar@2.3.0 
cordova-plugin-whitelist@1.3.3 
cordova-plugin-wkwebview-engine@1.1.4

**Comment by derwaldgeist** [comment]
@lnufnu Are you using Cordova plugins that reference other Cordova plugins? IIRC, this was part of the problem mentioned above and may explain why some experience it while others don't.

**Comment by lnufnu** [comment]
@derwaldgeist Was hoping these plugin issues were related, but as I do not believe the plugins I am using reference other Cordova plugins, they must be not be.

**Comment by derwaldgeist** [comment]
I am not 100% sure if this is actually the root cause, as it's already more than 4 years when I initially dug into this in #7029.

**Comment by filipenevola** [comment]
Hi @derwaldgeist, I would be happy to fix this issue.

Can you provide a small reproduction?

Maybe this needs a simple fix like this other case https://github.com/meteor/meteor/pull/11052
