### ISSUE TITLE
"meteor test" does not reload when Typescript implementation file has changed

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11074]
Meteor 1.10.2 on macos Catalina, using refapp:meteor-typescript 0.1.0 (with Typescript 3.9.2)
No mainModule or testModule sections in package.json.

When I develop TDD-style to first write a failing test and then modify the implementation in a file under server/, I find that Meteor does not notice the change when running in "meteor test" mode, so I have to modify the file containing the test to force a rebuild and re-run.

The typescript compiler is never invoked, so this must be some file watch issue in meteor. Meteor gets stuck at "SKIPPING CLIENT TESTS BECAUSE TEST_CLIENT=0".

When running "meteor run", changing the same file does cause a recompilation and restart.

Command line used (no client tests, only API tests):

`TEST_WATCH=1 TEST_CLIENT=0 MOCHA_TIMEOUT=60000 meteor test --raw-logs --driver-package meteortesting:mocha --inspect=9229 --exclude-archs web.browser,web.browser.legacy`

This has been a long standing issue and happened also with adornis:typescript but I have been told by others that when using javascript, this does work as expected.

**Comment by perbergland** [comment]
not stale

**Comment by perbergland** [comment]
I wonder if this could be caused by some limit for fsevents on my machine (macos Catalina) and also how I would find out. There’s no error thrown for the fs.watchFile call as far as I could tell.

**Comment by perbergland** [comment]
I investigated a bit more and this is caused by a bug in the meteor file watching logic. It’s quite complicated.

The source of the problem seems to be the handling of lazy files in the compiler-plugin handling. During tests, all non-test files (named *.spec.*, *.tests.* etc) are considered lazy unless explicitly marked as non-lazy:

https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/tools/isobuild/compiler-plugin.js#L645

Marking a source file as lazy then registers it with WatchSet.addPotentiallyUnusedFile which gives the effect that fireIfFileChanged ignores it:
https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/tools/fs/watch.ts#L459

This is supposed to be fixed by computeJsOutputFilesMap according to a comment, but computeJsOutputFilesMap will just emit the paths to the transpiled .js files (not on disk) and not the source files.
https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/tools/isobuild/compiler.js#L566

I think the fix is to modify computeJsOutputFilesMap so that it also watches the compiler plugin input files for files that are actually used.

**Comment by zodern** [comment]
Thanks for looking into this @perbergland. I think it will be fixed by https://github.com/meteor/meteor/pull/10455 since it will replace `addPotentiallyUnusedFile` and `computeJsOutputFilesMap` to only watch the files used by compilers.

**Comment by perbergland** [comment]
Thanks @zodern, looking forward to it. I’ll see if there’s a quick fix that could be applied to avoid needing to wait for that upcoming larger PR.

**Comment by perbergland** [comment]
Upon further inspection of the code, I think all I wrote above is wrong. The "lazy" file handling is not broken where I said.

Instead, when I reviewed _watchOutputFiles, I noticed that it takes the list of all output files (per module) and does try to add a watchset for the source files, except as I debug the code, the sourcePath field of the JsOutputResource is suddenly set to the produced js file (i.e. targetPath = sourcePath) which it isn’t in the JsOutputResource constructor so something along way has changed it.

Will check back in when I find that code.

**Comment by perbergland** [comment]
When I modified my typescript compiler to set the path property in the addJavaScript call to the *source file path* (path/to/myfile.ts, inputFile.getPathInPackage()) just like the BabelCompiler does, things now work.

The documentation on https://docs.meteor.com/api/packagejs.html is misleading as it the example shows that you should set path to the generated file, named ".js".

![image](https://user-images.githubusercontent.com/2690254/87855751-aa32a580-c91a-11ea-9a4f-ec5f2d953859.png)

The reason this matters is because the ImportScanner.checkSourceAndTargetPaths method is hardcoded to reset the source path to the target path (for reasons I couldn’t deduce).
https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/tools/isobuild/import-scanner.ts#L616

I will release an updated version of my compiler with this fix now. Ping @zodern 

This is now more of a documentation bug and possibly a bug in checkSourceAndTargetPaths - should it really force sourcePath to be the same as targetPath?

**Comment by perbergland** [comment]
Backtracking on the fix now because it broke the client builds even if meteor test now runs flawlessly

**Comment by perbergland** [comment]
Created a repro repo for this: https://github.com/perbergland/meteor-typescript-project

running `npm run test:server` with the core typescript compiler works fine - tests re-run when changing a dependency like import-methods.ts but not when using refapp:meteor-typescript

When I temporarily switched refapp:meteor-typescript to invoking addJavaScript with path set to sourcePath, the tests would re-run fine but then the web target could not be loaded in the browser (.js files were not found) so I had to revert that change.

**Comment by perbergland** [comment]
This can be closed now - the fix was to set path to the source file in addJavaScript
