### ISSUE TITLE
❗️'meteor create simple-todos' - takes wayy too long

### ISSUE THREAD

**Issue by tenzint** [meteor/meteor#11081]
### This bug report should include:

- [ ] Version - meteor@1.10.2
- [ ] The last version of Meteor where the problem did _not_ occur: N/A
- [ ] The operating system you're running Meteor on: Windows 10 x64
- [ ] The expected behavior: Takes relatively short time, like 1 minute (5 minutes max)
- [ ] The actual behavior: Takes infinity. My computer sleeps in the mean time.

First time meteor user here, I followed the steps in installing choco and then meteor. (Choco handled the system PATH automatically). Afterwards when I do 'meteor create simple-todos', the powershell or cmd prompt is stuck on ` Loading package typescript@3.7.6`. It was stuck earlier on another message like `Loading package standard-minifier-css` or something iirc. Just now, I selected and copied the new message it was stuck on (i.e. `Installing npm dependencies`), every time I select and do ctrl + c, the cmd prompt starts working and now this problem is solved while trying to explain it. wow.

Seriously, if I were to wait for the program to load all the stuff by itself, it would take hours. I did wait hours yesterday.

**Comment by tenzint** [comment]
I'm noticing that no matter what the terminal is (cmd, or powershell, git bash etc), once I click outside of the terminal, the terminal will hang until I refocus the terminal by copying and doing ctrl + c or something.

**Comment by tenzint** [comment]
Meteor's terminal output style of having only 1 output line at all time (old output messages get replaced with new message) is really not to my liking.

**Comment by delki8** [comment]
Hello @tenzint. :smile: 

A few days ago I was trying to replicate another issue in _Windows 10 x64_. First I tried to replicate it on a virtual machine and it worked fine, but then I installed Meteor on a real laptop running _Windows 10 x64_ and the thing you related happened to me. While using the PowerShell, Meteor took the whole night creating an app and it was just stuck on some message like you said. In the end, I had to abort the process and gave up replicating the issue.

Reading your issue I tried to run a simple `meteor create simple-todo` again on the same _Windows 10 x64_ and it worked like a charm :man_shrugging:. Don't know what happened, maybe some _windows reboot_ related issue...

**Comment by tenzint** [comment]
hello @delki8,

The exact same thing happened to me too. At one time, I wondered if there were some kind of corruption while installing meteor or choco, but it made no sense since I tried `meteor --version` and `choco upgrade meteor`. I also wasted one whole day/night on the installation/set up process ( mostly on `meteor create simple-todos` ). The comedy comes after waiting a few minutes the next day on `meteor create simple-todos` command, I was posting about this bug here and tried to copy the output message it was stuck on by selecting and doing ctrl + c, and then the powershell decided to continue with its process and work.

It's 2 days now, and so far everything is working smoothly for me :)

**Comment by jakobrosenberg** [comment]
Why was this issue closed? The bug is still there and is preventing a lot of people from using Meteor.

**Comment by filipenevola** [comment]
Hi @jakobrosenberg the author closed the issue, not us.

If the issue is also happening to you we should have a new one.

Maybe we should recommend a Windows restart after installation?

@zodern do you have any insights here?

**Comment by jakobrosenberg** [comment]
@filipenevola sorry, my post was actually intended towards @tenzint 🙂

The fix mentioned in this issue involves various key strokes during installation, which are in no way obvious and were discovered by accident by the OP.

Personally I've installed and rebooted multiple times with no luck. Mashing enter in the console however worked.

**Comment by tenzint** [comment]
Hi @jakobrosenberg, I remember the installation process just magically continued installing... I had no keystrokes that I entered to solve that.

Actually I recently learned that on windows' "cmd" terminal, you can right-click the title bar > then click on Properties > and uncheck the "Quick Edit Mode". 

This "Quick Edit Mode" is the culprit - it allows you to copy paste any terminal logs/messages. This also hangs the installation process waiting for the user to copy something. So try unchecking "Quick Edit Mode" and see if that helps you out!

If that does not help you, then we probably have different issues.

Personally, I have stopped using meteor for a few months... Good luck!
