### ISSUE TITLE
process.on("uncaughtException") not working

### ISSUE THREAD

**Issue by rsercano** [meteor/meteor#11083]
I saw the issue https://github.com/meteor/meteor/issues/4245 and suggestion to catch an unexpected error, and trying to catch an external API's unexpected error (nodejs mongodb driver's.) but neither both below ways are working;

```
Meteor.bindEnvironment(() => {
  process.on('uncaughtException', (err, origin) => {
    Error.createWithoutThrow({ type: Error.types.InternalError, externalError: err, metadataToLog: { origin } });
  });
});
```

 ```
 process.on('uncaughtException', (err, origin) => {
    Error.createWithoutThrow({ type: Error.types.InternalError, externalError: err, metadataToLog: { origin } });
  });
```

Your help would be appreciated

**Comment by rsercano** [comment]
Any news ? Is this project abandoned ?

**Comment by filipenevola** [comment]
Hi @rsercano could you provide a repository with a reproduction?

**Comment by rsercano** [comment]
Hello @filipenevola finally somebody showed up. I'm using nodejs mongodb driver internally and it was throwing an unexpected exception in nosqlclient which I couldn't manage to catch with below methods. This's not just me, if a node package throws something it's uncatchable with `process.on` I guess meteor overrides it?

**Comment by filipenevola** [comment]
Hi, no, Meteor does not overrides it. You can read in this comment a few possible root causes https://github.com/meteor/meteor/issues/8649#issuecomment-298324481

Please, provide a repository with a reproduction so we can help you in the analysis.
