### ISSUE TITLE
There are some @import rules in the middle of a file.

### ISSUE THREAD

**Issue by jjhesk** [meteor/meteor#11096]
app/client/styles.scss: warn: There are some @import rules in the middle of a file. This might be a bug, as imports are only valid at the beginning of a file.

it failed to compile the scss code as it works before.

**Comment by mfen** [comment]
I think there is a bug with `minifier-css` failing to hoist any `@import` that is preceded by a comment(s) in the asset. Does that match the imports that weren't hoisted in your project?

We hit the same warning attempting a custom integration with Fomantic UI's less only package, based on [Semantic-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor)'s approach.

It seems `minifier-css/minifier.js` is checking against `node.name` when looking for imports and comments to hoist, but PostCSS's Comment nodes don't have `name` and minifier should probably just check `node.type` for those instead.

Tested a quick fix for the above and it resolved the issue for us; I hope to submit a PR shortly.

**Comment by filipenevola** [comment]
Published minifier-css@1.5.2.
