### ISSUE TITLE
cordova build fails to copy local packages and link them properly

### ISSUE THREAD

**Issue by enryco** [meteor/meteor#11093]
xcode build error: `error: Build input file cannot be found: '/Users/Enrico/Developer/projectName/projectName/code/builds/ios/project/projectName/Plugins/packages/cordova-diagnostic-plugin/src/ios/Diagnostic_Notifications.m'`

When building for ios the local packages in `packages` referenced in `cordova-plugins` as `plugin-name@file://packages/plugin-name` are not getting copied into the build folder, and the path in project.pbxproj is not set properly. Instead, they are referenced in `project.pbxproj` as `path = "../../../../../../../packages/plugin-name` which throws an build error because this is not found.

Instead, it should be copied along with the other packages and referenced by `path = "plugin-name/somefile.h`

Checklist:
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
  - Meteor 1.10.2
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
  - Don't know
- [x] The operating system you're running Meteor on.
  - macOS 10.15.5
- [x] The expected behavior.
  - Cordova local plugins referenced with `plugin-name@file://packages/plugin-name` should properly be copied into the build folder
- [x] The actual behavior.
  - They are not, instead they are referenced by a relative path `path = "../../../../../../../packages/plugin-name`. (This is correct when they are being built for local dev in `.meteor/local/cordova-build/platforms/ios/projectName.xcodeproj` but not for the actual build.)
- [x] A **simple** reproduction!
  - Copy a package into `packages` and add them as `meteor add cordova:plugin-name@file://packages/plugin-name`. Build for ios

**Comment by filipenevola** [comment]
Hi @enryco could you set up a repo with this reproduction?
