### ISSUE TITLE
$bitsAllClear,  $bitsAnySet and $bitsAnyClear didn't work

### ISSUE THREAD

**Issue by yuwiggin** [meteor/meteor#11095]
I tested the bit operations of minimongo and found $bitsAllClear,  $bitsAnySet and $bitsAnyClear didn't work on Meteor1.8.1, mongo: 4.0.12.
Has the pull request https://github.com/meteor/meteor/pull/8350  really implemented?

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction? 😉

**Comment by yuwiggin** [comment]
Sorry, I made a mistake.
