### ISSUE TITLE
Dear sir,how I can install a low version meteor  version

### ISSUE THREAD

**Issue by codeneno** [meteor/meteor#11094]
si,we use the shell https://install.meteor.com install meteor,but our project rocket.chat is low version with low meteor version.how I can install a low version meteor  version?

**Comment by andreasemprebon** [comment]
Hi! You can get a specific version of Meteor by appending the parameter `release` to the install URL: [https://install.meteor.com/?release=1.10.1](https://install.meteor.com/?release=1.10.1) will get Meteor 1.10.1 instead of the latest 1.10.2, and so on.

**Comment by codeneno** [comment]
thank you

**Comment by coagmano** [comment]
Also, Meteor will install and use the version number in the file `.meteor/release` of a project, regardless of the globally installed version.

You can see that the latest Rocket Chat uses 1.10.2: 
https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/release

Where Rocket Chat 2.4.12 uses Meteor 1.8.3:
https://github.com/RocketChat/Rocket.Chat/blob/2.4.12/.meteor/release

**Comment by codeneno** [comment]
thank you every much
