### ISSUE TITLE
meteor is not recognized

### ISSUE THREAD

**Issue by dimpy17agg** [meteor/meteor#11091]
I have installed meteor on my system - windows10

but still, cmd shows meteor  is not recognized as an internal or external command,
operable program or batch file

And also unable to find .metor on the location C:\Users\username\AppData\Local\.meteor (to set path)..

**Comment by filipenevola** [comment]
Hi, is your installation producing any errors or warnings?

Are you using cmd or PowerShell? If you are using cmd, could you try PowerShell?

**Comment by dimpy17agg** [comment]
It shows no error.
I used cmd. Okay, I will try it with PowerShell.

**Comment by dimpy17agg** [comment]
Thanks, It correctly worked with PowerShell.
But why it didn't work with cmd??

**Comment by leonardoventurini** [comment]
I am not sure, but you could try comparing the path environment variables in both, for example:

`echo $Env:PATH` for powershell and `echo %PATH%` in cmd, and check if there are any differences between the two.

**Comment by edemaine** [comment]
Also, did you install Meteor (`choco install meteor`) in the same shell that you were trying to run it (`meteor`) from? If so, that is likely the problem: you need to `exit` that shell and run it again, so that its path updates.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster.
