### ISSUE TITLE
first meteor app problem

### ISSUE THREAD

**Issue by jayjshah** [meteor/meteor#11108]
when i try to create a new app in meteor it shows that your app is crashing & waiting for file changes.

**Comment by wollardj** [comment]
Not sure what version you're running, but I just tried `meteor create issue-11108` and it started up without any complaints. Version info:
```
Meteor 1.10.2
---
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101
```

**Comment by filipenevola** [comment]
Hi, as we don't have any details here I have to close this issue.
