### ISSUE TITLE
[1.10.3-beta.3] error: Constraint email@1.2.3 is not satisfied by email 2.0.0-beta1103.3

### ISSUE THREAD

**Issue by ixdi** [meteor/meteor#11103]
Hi,

When updating to Meteor 1.10.3-beta.3 there's a conflict with installed email package. 
It seems that accounts-password is the problem but package.js from accounts-password doesn't have an email version constraint.

```
While selecting package versions:
error: Conflict: Constraint email@1.2.3 is not satisfied by email 2.0.0-beta1103.3.
Constraints on package "email":
* email@~2.0.0-beta1103.3 <- top level
* email@1.2.3 <- accounts-password 1.6.1
``` 
Any idea? We have tried to reinstall email and accounts-password in any combination, also to remove .meteor/local or to add manually the packages to .meteor/versions and .meteor/packages. All without luck.

Thanks

**Comment by ixdi** [comment]
As a temporary solution we have forked accounts-password package and forced email dependency to be 2.0.0-beta1103.3

**Comment by ixdi** [comment]
It has been resolved in meteor@1.10.3-beta.5

**Comment by PrintHolamundo** [comment]
how do you forked accounts-password package and forced email dependency to be 2.0.0-beta1103.3 ?

**Comment by ixdi** [comment]
Hi,
You only need to fork the package into packages folder and edit the package.js.
Packages folder is loaded first.

**Comment by afrokick** [comment]
Another solution is manually change a line in .meteor/packages  as described on forum https://forums.meteor.com/t/meteor-1-11-released/53791/9?u=afrokick

**Comment by PrintHolamundo** [comment]
It seems that the email was resolved, but now I have the following message when trying to update meteor do you know something? I would appreciate it

JD@mx:/home/JD/Desktop/beta
$ meteor update --patch
=> Errors while initializing project:         
                                              
While loading package angular-meteor-auth@1.1.1:
error: Command failed:
/home/JD/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/JD/.npm/_logs/2020-09-30T14_40_26_506Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/JD/.npm/_logs/2020-09-30T14_40_26_506Z-debug.log


While loading package fourseven:scss@3.13.0:
error: Command failed:
/home/JD/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! node-sass@3.13.0 install: `node scripts/install.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/JD/.npm/_logs/2020-09-30T14_40_27_356Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! node-sass@3.13.0 install: `node scripts/install.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/JD/.npm/_logs/2020-09-30T14_40_27_356Z-debug.log
