### ISSUE TITLE
Cannot install an older version of Meteor

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#11111]
When I am trying to run:

```
curl https://install.meteor.com?release=1.0.3 | sh
```

I get:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7913    0  7913    0     0  28362      0 --:--:-- --:--:-- --:--:-- 28362
Removing your existing Meteor installation.
Downloading Meteor distribution
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O=#  #                                                                      
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O=#  #                                                                      
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O=#  #                                                                      
curl: (22) The requested URL returned error: 403 
Retrying download in 5 seconds...
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 
```

In fact, that happens also for `curl https://install.meteor.com?release=1.10 | sh`, which is a pretty new version.

This makes it hard for us to have reproducible builds. :-(

I am trying to do that on Linux. So URL which it tries to fetch is `https://static-meteor.netdna-ssl.com/packages-bootstrap/1.10/meteor-bootstrap-os.linux.x86_64.tar.gz`. So `https://static-meteor.netdna-ssl.com/packages-bootstrap/1.10/meteor-bootstrap-os.linux.x86_64.tar.gz` does not work, but `https://static-meteor.netdna-ssl.com/packages-bootstrap/1.10.1/meteor-bootstrap-os.linux.x86_64.tar.gz` does. Why?

**Comment by wollardj** [comment]
You might try putting the url in quotes to make sure that pesky `?` isn't getting interpreted by your shell:

```
curl "https://install.meteor.com?release=1.0.3" | sh
```

**Comment by StorytellerCZ** [comment]
If I remember correctly 1.10 was "special" (it is not even listed in the changelog) so that one does not surprises me. The same thing appears to be true for 1.0.3

**Comment by mitar** [comment]
Hm. Is there a better way to programmatically get a list of all released Meteor versions (without having Meteor installed)? I am currently using `git ls-remote --tags https://github.com/meteor/meteor.git tags/release/METEOR@* | cut -d '@' -f 2 | grep -v -`.

**Comment by mitar** [comment]
But `1.0.3` was released: https://github.com/meteor/meteor/blob/devel/History.md#v1103-2015-08-03

**Comment by StorytellerCZ** [comment]
Strange... my mistake.

**Comment by mitar** [comment]
No no, no mistake. Thanks for input about 1.10. But there are some strange things here. :-(

**Comment by klaussner** [comment]
@mitar Version 1.0.3 doesn't exist. The correct version number is 1.0.3.1, so `curl https://install.meteor.com?release=1.0.3.1 | sh` should work. @StorytellerCZ is right about 1.10. The oldest available 1.10.x version is 1.10.1, which can be installed with `curl https://install.meteor.com?release=1.10.1 | sh`.

**Comment by mitar** [comment]
Oh, you are right. I was looking wrong. So why are then tags? So I got those versions from tags on GitHub? What are those tags pointing to?

**Comment by klaussner** [comment]
Maybe these versions were released/tagged and then retracted due to issues like the one mentioned in https://github.com/meteor/meteor/issues/11111#issuecomment-653948517.

**Comment by filipenevola** [comment]
We got a [bug](https://github.com/meteor/meteor/commit/d274d8d7efe38cc9fe21494cc4ce9de346dc9375) on SQLite in the version resolution for Meteor 1.10 then we had to skip it, Ben did a workaround for this bug and it's not going to happen in next Meteor minor updates but 1.10 was ruined anyway.

Could we close this issue?

**Comment by mitar** [comment]
My questions is: how can I get programmatically all working versions of Meteor. I am trying to build Docker images for every Meteor version so that in production you can have a fixed version without anything changing under you. So using tags seems to not be the way?

**Comment by filipenevola** [comment]
We could delete invalid tags or you could connect to Troposphere (packages server) using DDP.connect and get the data from there for meteor-tool like Atmosphere does.

I saw on Slack that you created the images already so maybe you found a different workaround.

What do you think is better? I'm ok deleting the tags as they are not actual Meteor published versions.

**Comment by mitar** [comment]
My workaround currently is just to try to install and skip it if it fails. :-( So not a great workaround.

I forgot about DDP.connect. But I do think cleaning up tags would be beneficial in general. So I would prefer that one.

**Comment by filipenevola** [comment]
I've removed 1.10 tag as I know for sure this version was not released. I believe you are safe to get latest Meteor versions considering the tags now.

**Comment by mitar** [comment]
The following tags do not work as well:

* 0.9.4.1
* 1.0.3
* 1.4.2.2
* 1.4.4.6
* 1.5.4.2
* 1.6.1.2
* 1.6.1.3

**Comment by filipenevola** [comment]
Done for all 👍 thanks!

**Comment by mitar** [comment]
Thanks to you!

**Comment by mitar** [comment]
OK, so it seems some of the versions [on this list](https://github.com/meteor/meteor/issues/11111#issuecomment-689671141) have History entry, like 1.5.4.2 (see #11858). So are you saying that there are versions in History file which do not have a published installable version?

So I think we should do [another pass over this list](https://github.com/meteor/meteor/issues/11111#issuecomment-689671141) and for each version determine:
* If it has ever really be released, if so:
  * Then it should have a tag.
  * It should be installable.
* If not, then:
  * It should not have a History entry, or the entry should mention that the version was yanked.
  * There should probably be no tag either.

I noticed this issue because I wanted to upgrade to latest security patch of 1.5. version but it was not possible, despite being listed in History file.

**Comment by christopher-noble** [comment]
Update: tried everything here. Only worked for me when I opened my terminal in Rosetta
