### ISSUE TITLE
Password being inserted as plain text into db by accounts-password createUser method

### ISSUE THREAD

**Issue by VirgilioGM** [meteor/meteor#11113]
I just realized that new inserted users have a _password_ field with the password as plain text. I'm using acounts-pasword@1.6.0 and it seems the bug is due to insert the hashed password into _user.services.password_ but keeping _options.password_ as received, so the field is inserted when calling to `Accounts.insertUserDoc(options, user)` in password_server.js:1119.

To reproduce it, run anywhere from client side:
```javascript
const uid = Accounts.createUser({
  username: 'myuser',
  password: 'mypass',
});
console.log(Meteor.users.findOne(uid));
```

And will output:
```javascript
{
  _id: '9wMJd9j5z4sRYm3Lz',
  createdAt: 2020-07-07T11:38:39.183Z,
  services: {
    password: {
      bcrypt: '$2b$10$qDvTU6YKN07HJi.9HyMDVuNoH9cJYJcT7iDBxb6kQx.EWTzrv/ra.'
    }
  },
  username: 'myuser',
  password: 'mypass'
}

```

**Comment by StorytellerCZ** [comment]
@VirgilioGM Can you provide a reproduction? On first look I'm not seeing any relevant change in the code that deals with this.
Do you use on create user hook? That looks to me like a possible weakness here.

**Comment by VirgilioGM** [comment]
First of all, I'm really sorry that I wasted your time because the error doesn't happen as I reported it. It was caused by another Atmosphere package (developed by a colleague) that was extending the _onCreateUser_ hook. Thank you very much for pointing out the possible origin of my problem and I apologize again.
