### ISSUE TITLE
Accounts.onEmailVerificationLink throws console warning when being used

### ISSUE THREAD

**Issue by dcantatore** [meteor/meteor#11116]
When you use Accounts.onEmailVerificationLink() on the client side as instructed, in the console it says: 

```
Accounts.onEmailVerificationLink was called more than once. Only one callback added will be executed.
```

The meteor doc around it is:
https://docs.meteor.com/api/passwords.html#Accounts-onEmailVerificationLink

It says "This function should be called in top-level code".  Which it is, so I'm not sure where else I would put it to avoid this bug

I have seen this mentioned as a feature request but this is a bug

**Comment by dcantatore** [comment]
This is ignored not stale

**Comment by StorytellerCZ** [comment]
@dcantatore Can you share with us list of packages you are using? Just to cover all our bases.

**Comment by dcantatore** [comment]
```
meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.1.0       # Packages for a great mobile UX
mongo@1.9.0                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
jquery                  # Wrapper package for npm-installed jquery
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.6.0   # CSS minifier run for production mode
standard-minifier-js@2.6.0    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.14.2              # Enable ECMAScript2015+ syntax in app code
typescript@3.7.5              # Enable TypeScript syntax in .ts and .tsx modules
shell-server@0.5.0            # Server-side component of the `meteor shell` command

kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
less@2.8.0                    # Leaner CSS language

meteortesting:mocha               # A package for writing and running your meteor app and package tests with mocha
johanbrook:publication-collector  # Test a Meteor publication by collecting its output
tmeasday:publish-counts
random@1.2.0
natestrauser:publish-performant-counts
sibylsurveys:query-builder
http@1.4.2
accounts-ui@1.3.1
accounts-password@1.6.0
underscore@1.0.10
littledata:synced-cron
email
ostrio:flow-router-extra
ostrio:flow-router-title
ostrio:flow-router-meta
server-render
```

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by dcantatore** [comment]
Hi @filipenevola ,

It's really simple, create a new meteor project and add:

```
Accounts.onEmailVerificationLink((token, done) => {
    Accounts.verifyEmail(token, (err) => {
        if (err) {
            console.log('Error: ', err);
        } else {
            done();
            console.log('Success');

        }
    });
});
```

It can be put in any top level code 'This function should be called in top-level code, not inside Meteor.startup().' as stated here:
https://docs.meteor.com/api/passwords.html#Accounts-onEmailVerificationLink

**Comment by cfnelson** [comment]
Could be related to this reported problem/bug : [[1.8.3] onLogin handler fired twice #10853](https://github.com/meteor/meteor/issues/10853)

The above onLogin handler fired twice bug was reported to be related to this code change & commit:  [Simplify _startupCallback by passing callback rather than ID.](https://github.com/meteor/meteor/commit/ec0ed4dec988874c4c85fe18d9d2b5d26b553d55)  (https://github.com/meteor/meteor/commit/ec0ed4dec988874c4c85fe18d9d2b5d26b553d55)

Which was introduced in this [PR #10543](https://github.com/meteor/meteor/pull/10543) which was resolving this bug/issue: https://github.com/meteor/meteor/issues/10157

**Comment by carlosalvidrez** [comment]
I also have this issue. I understand there may not be an easy way to reproduce this, but thought I'd chime in for the record.
