### ISSUE TITLE
Deployed files in public folder are not available website

### ISSUE THREAD

**Issue by dcantatore** [meteor/meteor#11125]
I have been building and deploying several meteor apps for a while now and I still can't seem to work the reason for this "bug". I have items in the public folder that I can see and some that I can not. 

Here is the directory from the server:
![Screen Shot 2020-07-18 at 10 06 03 AM](https://user-images.githubusercontent.com/15852431/87854270-cadd0a00-c8de-11ea-987f-d8b7e2cbf230.png)

I can type in mywebsite.com/site.webmanifest and it loads the file

But I can not type in mywebsite.com/favicon-32x32.png and see the image.

What is going wrong in the build phase that these aren't made available? I have been casually looking into this for over a year and decided that this really shouldn't be an issue that I have to do a work around with nginx for. I also have some image files that are available in the folder shown in that screen shot and some images in the same images folder that are not. It's very confusing why something seemingly straightforward has unexpected behavior.

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by filipenevola** [comment]
As this is an old issue without a reproduction or updates from the author I'm closing it. Feel free to mention me here if that is an issue for you.
