### ISSUE TITLE
Probable syntax error ?

### ISSUE THREAD

**Issue by obonyojimmy** [meteor/meteor#11128]
Probable syntax error on `if` block in https://github.com/meteor/meteor/blob/71f67d9dbac34aba34ceef733b2b51c2bd44b665/packages/ddp-server/livedata_server.js#L1554-L1556

**Comment by hexsprite** [comment]
Because of lack of curly brackets? they're optional for single statements.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
