### ISSUE TITLE
Meteor.wrapAsync handling undefined properties wrong

### ISSUE THREAD

**Issue by nytamin** [meteor/meteor#11120]
I have come across an issue where `Meteor.wrapAsync` is not handling undefined properties as it should.

The [documentation states that](https://docs.meteor.com/api/core.html#Meteor-wrapAsync):
>Meteor.wrapAsync(func, [context])
>Wrap a function that takes a callback function as its final parameter.

But in the case of
```
const myWrapFunction = Meteor.wrapAsync((...args) => {
  console.log('arguments received in wrapped function:', args)

  const callback = args[args.length - 1] // Last argument
  if (typeof callback !== 'function') {
    throw new Meteor.Error(500, `Callback function is not a function!`)
  }
  callback() // to return
})
myWrapFunction(1, undefined) // does not throw, by pure luck
myWrapFunction(1, undefined, undefined) // throws "Callback function is not a function!"
```
The arguments provided into `myWrapFunction` is
```
myWrapFunction(1, undefined) // gives args = [1, Function] 
myWrapFunction(1, undefined, undefined) // gives args = [1, Function, undefined]
```
altough I expected this to happen:
```
myWrapFunction(1, undefined) // should give args = [1, undefined, Function] 
myWrapFunction(1, undefined, undefined) // should give args = [1, undefined, undefined, Function]
```

This creates a significant problem, since the callback *might not be the last parameter* - which is in direct conflict with the docs.
This means that `myWrapFunction(1, undefined)` and `myWrapFunction(1)` might produce different results, even though they are in general thought of as identical.

This has been addressed previously in #6816 , but I think it should be brought up again for review.

I see two possible solutions:
1. Fix the bug (but that might be breaking and have significant impact)
2. Change the documentation to instead say "Wrap a function that takes a callback function as its last (non-undefined) parameter".

Tested in Meteor 1.10.2
Repo for reproducing the issue: https://github.com/nytamin/meteor-wrapAsync-bug

**Comment by filipenevola** [comment]
Hi, I believe we should update the docs, do you agree @nytamin ?

> Change the documentation to instead say "Wrap a function that takes a callback function as its last (non-undefined) parameter".

Could you do that?

**Comment by nytamin** [comment]
Sure, I can look into it. It'll be a good exercise

**Comment by filipenevola** [comment]
Thanks @nytamin
