### ISSUE TITLE
MongoDB cursor.next() function

### ISSUE THREAD

**Issue by theabrad** [meteor/meteor#1112]
I found out that meteor doesn't have the MongoDB `cursor.next()` function referenced [here](http://docs.mongodb.org/manual/reference/method/cursor.next/)

**Comment by manuelro** [comment]
@glasser can you elaborate a little more on this? 

> It seems like you could just use fetch and keep an index into the list.

I'm facing the same issue as above, I send a `collection.find({foo: bar});` to one of my templates and want to access the items one by one programmatically, via a `Meteor.timeOut(...);` but so far I haven't had good luck, or perhaps I haven't got the documentation the right way.

If you know of any place of the exact URL to read about this, that would be greatly appreciated.

**Comment by glasser** [comment]
The fetch method turns a cursor into an array. You can then just keep in your state an index (ie a number from 0 to the length of the list) and add or subtract 1 from it.
