### ISSUE TITLE
[Mongo Package] allow-deny dependency

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#11137]
Is there a reason why this isn't a weak dependency? A lot of Meteor apps don't use `allow-deny` anymore these days I think?

https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/packages/mongo/package.js#L25

**Comment by SachaG** [comment]
Oh I did find one use here: https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/packages/mongo/collection.js#L770

But it seems like it wouldn't be hard to make it optional?

**Comment by filipenevola** [comment]
Hi @SachaG I think is a matter of what is the benefit and if the benefit is worth the breaking change.
