### ISSUE TITLE
Conflicting settings in tsconfig for generated TypeScript project 

### ISSUE THREAD

**Issue by chris-tse** [meteor/meteor#11135]
**Versions**: 
- Meteor: 1.10.2
- TypeScript: 3.9.6
- VSCode: 1.47.3

**OS**: 
- MacOS 10.15
- Fedora 31
- Ubuntu 20.04 via WSL

**Expected behavior**
No warnings/errors in tsconfig.json validation.

**Actual Behavior**
An error of `Option 'noEmit' cannot be specified with option 'incremental'` is shown due to both `noEmit` and `incremental` options being present and set to true.

**Steps to Reproduce**
1. Scaffold a new TypeScript project with the CLI using `meteor create --typescript new-ts-app`. 
2. Check problems reported by TypeScript compiler (with VSCode may need to first open up a .ts file to start up the TS language server).

**Possible Fix**
Remove the `noEmit` option? I'm not familiar with the reason behind the decision to include this, but I assume the `incremental` option would be good to keep, which needs `noEmit` to be false so that it can produce the incremental metadata.

The project will still build, unlike when TS errors are present in actual TS code.

**Comment by GaetanRouzies** [comment]
I have the same problem, and i don't know if the meteor typescript package is using this tsconfig file. Can we remove the `noEmit` option safely ?

**Comment by GaetanRouzies** [comment]
Even since 1.11.1 the error is showing when we execute **tsc**.

> TS5053: Option 'noEmit' cannot be specified with option 'incremental'.

**Comment by filipenevola** [comment]
Meteor 1.12 is coming out soon, I believe it will fix this issue.
