### ISSUE TITLE
Meteor build breaks on 1st refresh

### ISSUE THREAD

**Issue by robtoloy** [meteor/meteor#11132]
Packages:
meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.1.0       # Packages for a great mobile UX
mongo@1.10.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.6.0   # CSS minifier run for production mode
standard-minifier-js@2.6.0    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.14.3              # Enable ECMAScript2015+ syntax in app code
typescript@3.7.6              # Enable TypeScript syntax in .ts and .tsx modules
shell-server@0.5.0            # Server-side component of the `meteor shell` command

accounts-password@1.6.0
jquery
pfafman:filesaver
harrison:papa-parse
kadira:blaze-layout
kadira:flow-router
jkuester:blaze-bs4
accounts-google
accounts-twitter
lichthagel:accounts-discord
alanning:roles
jamgold:flow-animate-css
useraccounts:bootstrap
accounts-facebook
momentjs:moment
accounts-ui
service-configuration
sacha:spin
fourseven:scss
session
underscore
aldeed:template-extension

___

1. npm run meteor
2. Open incognito (Chrome or Firefox)
3. Visit localhost:3000
4. Hit refresh:

<img width="1186" alt="Screen Shot 2020-07-27 at 7 54 13 PM" src="https://user-images.githubusercontent.com/7201416/88742071-099c6c80-d0f6-11ea-8fef-c1377d5c95e9.png">
<img width="1187" alt="Screen Shot 2020-07-27 at 7 54 19 PM" src="https://user-images.githubusercontent.com/7201416/88742076-0c975d00-d0f6-11ea-9a20-4ddc07cd6c6f.png">
<img width="1188" alt="Screen Shot 2020-07-27 at 7 54 24 PM" src="https://user-images.githubusercontent.com/7201416/88742077-0dc88a00-d0f6-11ea-9450-2fae2d36c028.png">
<img width="1188" alt="Screen Shot 2020-07-27 at 7 54 29 PM" src="https://user-images.githubusercontent.com/7201416/88742078-0e612080-d0f6-11ea-9339-7d6e8d244527.png">

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by filipenevola** [comment]
As this is an old issue without a reproduction or updates from the author I'm closing it. Feel free to mention me here if that is an issue for you.
