### ISSUE TITLE
Meteor CLI throwing 2 HIGH SEVERITY vulnerabilities 

### ISSUE THREAD

**Issue by netanelmaroof** [meteor/meteor#11134]
Showing up in Meteor 1.2, I'm on windows 10. 
Both are from the elliptic package, signature malleability.

**Comment by DavidSichau** [comment]
Fix would be available but needs to be published:

https://github.com/meteor/node-stubs/pull/21

**Comment by filipenevola** [comment]
meteor-node-stubs@1.0.1 was published now.

On Meteor 1.10.3 the skeletons will be updated as well to use this version.
