### ISSUE TITLE
Meteor tool 1.10.2 breaks at cordova package install 

### ISSUE THREAD

**Issue by obonyojimmy** [meteor/meteor#11142]
Meteor tool 1.10.2  seems to break when there exists a  mobile platform specified when running `build` , `run` or `ensure-cordova-dependencies` sub-commands : 

commands : 
1. `meteor ensure-cordova-dependencies` or
2. `meteor run --mobile-server=http://localhost:3000` or 
3. `meteor build ../`

Error
```
/root/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/fibers.js:90
					return fn.apply(this, arguments);
					          ^
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at /tools/cli/main.js:834:12
```

Environment: 
- gitlab-ci
- node:12.16.1

Npm Dependency
- "meteor-desktop": "^2.2.5" (dev-dependency)

Reproduction
- create meteor --react project
- run in gitlab-ci (node:12.16.1) image
- in the run either above describe commands in the ci environment.

**Comment by filipenevola** [comment]
Hi, I believe you have a / somewhere in your code. Maybe in your mobile-config or package.json?

Could you provide a reproduction?

We are aware of many apps running on Meteor 1.10.2 so I believe this is something in your code but a reproduction could prove that I'm wrong in my guess.
