### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received null

### ISSUE THREAD

**Issue by ediopia** [meteor/meteor#11147]
After updated to 1.11, can't start my app.
It returns TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received null

**Comment by elliotcw** [comment]
I was having this issue and clearing all my local cached files fixed it

```
rm -rf node_modules
rm package-lock.json
meteor reset
rm -rf .meteor/local
curl https://install.meteor.com/ | sh
```

**Comment by tducasse** [comment]
I had the same issue, I only had to remove the node modules and reinstall the dependencies from the lockfile:
```sh
rm -rf node_modules
npm ci
```
