### ISSUE TITLE
importing issue from @material-ui/icons/

### ISSUE THREAD

**Issue by rockkoca** [meteor/meteor#11152]
This is fine.
` import Visibility  from "@material-ui/icons/Visibility"; `

This will cause extremely slow loading. More than one minute. The problem is caused by the following importing format not a specific icon.
` import {Visibility, VisibilityOff}  from "@material-ui/icons"; `

@material-ui/icons version  4.9.1
Meteor version 1.11

**Comment by hexsprite** [comment]
search the meteor issue tracker I recall something about this issue before...

**Comment by filipenevola** [comment]
Hi, this happens because Meteor does not have tree-shaking yet (coming soon https://github.com/meteor/meteor/pull/11164) so to avoid importing all the content from Material UI you should import the direct files.

@renanccastro this is a good test to be done when the tree-shaking is ready.
