### ISSUE TITLE
Get MongoDB Error Error in $cursor stage :: caused by :: operation was interrupted in Version 1.11.0

### ISSUE THREAD

**Issue by stefanskiasan** [meteor/meteor#11150]
Hi Guys i get an error after updating to 1.11.0.
Have anyone a Idea what is wrong ?

Kind of regards
Asan

MongoError: Error in $cursor stage :: caused by :: operation was interrupted
W20200827-13:13:09.940(2)? (STDERR)     at Connection.<anonymous> (/Users/asanstefanski/.meteor/packages/npm-mongo/.3.8.0.r9yyda.mm8u7++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:451:61)
W20200827-13:13:09.940(2)? (STDERR)     at Connection.emit (events.js:315:20)
W20200827-13:13:09.940(2)? (STDERR)     at Connection.EventEmitter.emit (domain.js:483:12)
W20200827-13:13:09.940(2)? (STDERR)     at processMessage (/Users/asanstefanski/.meteor/packages/npm-mongo/.3.8.0.r9yyda.mm8u7++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/connection.js:452:10)
W20200827-13:13:09.941(2)? (STDERR)     at TLSSocket.<anonymous> (/Users/asanstefanski/.meteor/packages/npm-mongo/.3.8.0.r9yyda.mm8u7++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/connection.js:621:15)
W20200827-13:13:09.941(2)? (STDERR)     at TLSSocket.emit (events.js:315:20)
W20200827-13:13:09.941(2)? (STDERR)     at TLSSocket.EventEmitter.emit (domain.js:483:12)
W20200827-13:13:09.941(2)? (STDERR)     at addChunk (_stream_readable.js:295:12)
W20200827-13:13:09.941(2)? (STDERR)     at readableAddChunk (_stream_readable.js:271:9)
W20200827-13:13:09.941(2)? (STDERR)     at TLSSocket.Readable.push (_stream_readable.js:212:10)
W20200827-13:13:09.941(2)? (STDERR)     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.

**Comment by aliaslam63** [comment]
Anyone found the solution ?
