### ISSUE TITLE
dynamic-import precaching is not always working and complicated to use with service workers (Meteor 1.11 dynamic import 0.5.2)

### ISSUE THREAD

**Issue by larswolter** [meteor/meteor#11157]
Normally precaching should occur when Package.appcache is available. Appcache is now deprecated and we use ServiceWorkers for caching, but need to define Package.appcache so that precaching of dynamic imports is automatically done. While doing this, we found the following error.

Precaching is not always done. The precaching is done in /packages/dynamic-import/dynamic-versions which is required wwhen meteorInstall.fetch is called.
This results in prefetching is only done when something is dynamically imported during initial loading. If no dynamic module is loaded during startup precache is never called.

[Reproduction](https://github.com/larswolter/meteor_dynamic-import-bug)
The reproduction also contains a slightly modified dynamic-import to log the registration and precaching to the console

Three things that should be changed:
1. Move registration for precaching to the client.js (and fix, that client.js is included from server.js)
2. Programmatically allow controlling the dynamic imports (register listeners on prefetch, allow remove of cache, allow precache) to better work with non-appcache caching
3. Allow an option to serve dynamic imports as single requests to optimize using a CDN and/or service worker

If wanted, i can submit a pull request for 1. and maybe for 2., later on

**Comment by larswolter** [comment]
I found another error, when precaching is working and dynamic imports from packages are used.
During precaching, the module to import can not be found
![dynamic import error-packages](https://user-images.githubusercontent.com/13793513/91978762-f9933080-ed24-11ea-92d5-7489d70144dc.jpg)
But when clicking the button, which does the dynamic import, the module gets successfully imported and can be executed.

I updated my reproduction to also include this case. you need to uncomment  the code in client/main.js:7 to fix precaching and then the error will be thrown.
I tried to understand why this error occurs, but was not successfull. I only found out, that the request for the missing module is never send to the server. It is abandoned on the client.

**Comment by larswolter** [comment]
After some more debugging, i found out why the dynamic module from the package is not prefetched. During prefetch the __DYNAMIC_VERSIONS__, that are generated during the build, are iterated and prefetched. In this Objekt the names of the imports get converted to file path compatible names, so :  is replaced with _  

![Versions](https://user-images.githubusercontent.com/13793513/92332288-0e512a80-f07d-11ea-9c73-027a468f3f73.png)

In the Module lookup (filesByModuleId) which is used during Module resolvement the original name is used.

![filesByModule](https://user-images.githubusercontent.com/13793513/92332287-0db89400-f07d-11ea-819d-77d9a40c542a.png)

When resolving during a normal import the module resolvement happens in the context of the package. In my example the module imported is `./myImportedPackageMethod.js` And everything works. But if the prefetch is done, the module to resolve is `/node_modules/meteor/larswolter_dynamic-package/myImportedPackageMethod.js` and it exits when trying to resolve `larswolter_dynamic-package` because only `larswolter:dynamic-package` exists.

One way of resolving this issue is to try a second time if an error occurs during module loading.

```javascript
  function prefetchInChunks(modules, amount) {
    Promise.all(modules.splice(0, amount).map(function (id) {
      return new Promise(function(resolve, reject) {
        module.prefetch(id).then((module)=>resolve(module)).catch((err)=>{
          // we probably have a : _ mismatch
          // what can get wrong if we do the replacement
          // 1. a package with a name like a_b:package will not resolve
          // 2. someone falsely imports a_package that does not exist but a package
          //    a:package exists, so this one gets imported and its usage will fail
          if(id.indexOf('/node_modules/meteor/')===0) {
            module.prefetch('/node_modules/meteor/'+id.replace('/node_modules/meteor/','').replace('_',':')
            ).then(resolve).catch(reject);
          } else reject(err);
        })
      });
    })).then(function () {
      if (modules.length > 0) {
        setTimeout(function () {
          prefetchInChunks(modules, amount);
        }, 0);
      }
    });
  }

```

A cleaner way would be to supply a correct Versions Object to the client without the replacement, but that would involve more then updating the `dynamic-import` package.

**Comment by filipenevola** [comment]
The fix will be available on Meteor 1.12

**Comment by afrokick** [comment]
@larswolter is it fixed for you?

**Comment by larswolter** [comment]
@afrokick Not completely, I still see issues with the dynamic imports especially when used with service workers, but the main errors where fixed. So I close this issue and hopefully put up a PR sometimes later, to address the rest of my problems.
