### ISSUE TITLE
command "meteor create --vue" : bad folder structure

### ISSUE THREAD

**Issue by StephaneRavet** [meteor/meteor#11153]
Hi,

Reproduction : https://github.com/StephaneRavet/meteor-create-vue-window-bug
Solution : https://github.com/StephaneRavet/meteor-create-vue-window-bug/tree/solution

This problem appeared with v1.11 which introduce command "meteor create --vue".

Actual behavior : `ReferenceError: window is not defined` if we use `window` in any `.vue` file.

In any `.vue` file, if we use `window.innerHeight` for example, the build will report : `ReferenceError: window is not defined`, because only folders `imports`, `client`, `public `and `test `are excluded from server build. I think, the `src` folder, used by skel-vue is not appropriate.

Ok, you can tell me : use `if (Meteor.isClient) { console.info(window) }` to fix it.
Yes, but if we use a library that uses windows, we can't write `if (Meteor.isClient) { import { Editor } from '@toast-ui/vue-editor' }` to fix it.

Solution found :
* rename the `src` folder into `imports`.
* New problem after that : `main.html` is not loaded. If I put it to `/client/main.html`, it builds without errors.

**Comment by StorytellerCZ** [comment]
@StephaneRavet Can you make a PR with the fix?

**Comment by StephaneRavet** [comment]
ok 👍
