### ISSUE TITLE
After upgrade from 1.10.2 to 1.11, Internet Explorer 11 hangs on initial page load when loading xregexp package

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11163]
My Typescript-based application no longer loads in Internet Explorer 11, but hangs on load with a "a script is taking a long time" error message.

If I break the execution manually, it shows a stack trace of some code in "reify" that it never seems to exit from.

Running in debug mode or in production bundle code doesn’t matter - the same thing happens.

Screenshots attached.

![Screenshot 2020-09-08 kl  20 08 35](https://user-images.githubusercontent.com/2690254/92512898-c8789b80-f20f-11ea-8e2c-b53e7f8afffb.png)

![Screenshot 2020-09-08 kl  20 09 15](https://user-images.githubusercontent.com/2690254/92512914-cb738c00-f20f-11ea-9e4c-f29bbfb80ecd.png)

**Comment by perbergland** [comment]
Ping @zodern  - you seem to be the current authority in the tools/build/reify area. Do you know what could have changed between 1.10.2 and 1.11 to trigger this behavior?

**Comment by perbergland** [comment]
I gave up after 15 minutes of loading time on browserstack (IE11 on Win10) but @zodern said on Slack that it does finally load in his environment.

The 1.10.2 version (all other things equal) loads in 20 seconds on browserstack.

**Comment by perbergland** [comment]
I compared the 1.10.2 and 1.11 versions of the produced .meteor/local/build/programs/web.browser.legacy/modules.js and they look identical save for some modules that were in different locations in the two files.

**Comment by perbergland** [comment]
The culprit is the upgrade of core-js, but need to investigate further.
Checking out ecmascript-runtime-client into packages and changing
```
Npm.depends({
  "core-js": "3.6.5"
});
```
to
```
Npm.depends({
  "core-js": "3.2.1"
});
```
as it was in meteor 1.10 makes IE11 load fine again.

**Comment by perbergland** [comment]
Tested with a few different core-js versions from https://github.com/zloirock/core-js/releases
3.4.8 - works fine
3.5.0 - works fine
3.6.0 - hangs

So something changed in core-js between 3.5.0 and 3.6.0

**Comment by perbergland** [comment]
https://github.com/zloirock/core-js/compare/v3.5.0...v3.6.0

**Comment by perbergland** [comment]
OK I'm pretty sure now that it's an incompatability between the xregexp package and the regex mods introduced by core-js 3.6.0. The app hangs when loading the xregexp package because something in regex.exec is now incompatible.

**Comment by perbergland** [comment]
Filed an issue with xregexp - https://github.com/slevithan/xregexp/issues/300

Unsure of what workaround I could use.

**Comment by perbergland** [comment]
I'm pretty sure now that this is just a regression/incompatibility between two non-meteor packages (core-js and xregexp) so I'm closing this one.

**Comment by CaptainN** [comment]
I wonder whether you could work around this by adding a meteor -> recompile setting to your own package.json file:

```json
{
  "meteor": {
    "mainModule": { ... },
    "nodeModules": {
      "recompile": {
        "xregexp": "legacy"
      }
    }
  }
}
```

**Comment by filipenevola** [comment]
Thank you @perbergland for all the analysis here.
