### ISSUE TITLE
METEOR_SETTINGS environment variable - store path to settings file instead of JSON

### ISSUE THREAD

**Issue by meteortester** [meteor/meteor#1116]
The current method of storing JSON in METEOR_SETTINGS instead of a path to a settings file causes some issues (that can be worked around), but I would like to request that METEOR_SETTINGS be changed to be the path to the settings file instead of just being JSON, for these reasons:

Setting the environment variable from a script is a little painful. There are several ways that I can see:
1. Embed JSON in login/startup scripts where environment variables are set. This would mean that when settings are changed, these scripts, or some scripts that they call in turn, have to be modified and re-run. If these called scripts live inside a meteor deployment, they will fail if the app is not currently deployed. If they live outside the meteor deployment, the deployment process is complicated by having to update and re-run these scripts (likely platform-specific) when the settings change.
2. Read JSON from a file during login/startup/etc scripts, and set an environment variable with its' contents. This will fail if the meteor app is not currently deployed, or eg. if the file is on a network share which is temporarily down or not yet started. This may not be possible to do so in some cases (eg. if environment variable values are being set by a script which reads a list of name/values from a file). So it adds a risk that login/startup scripts may fail or run slowly. 
3. Store a small amount of JSON in the environment variable eg. { "environment": "production" } and then have the app select some appropriate settings from within a JS file in server/. This would ideally need an API so that the app can manage Meteor.settings.
4. Write a script to set the environment variable and then start Meteor. But this still suffers from other issues:
- Some platforms have arbitrary limits on the size of an environment variable or total size of all environment variables. These are unlikely to be breached by the size of a settings file, but settings files be quite extensive.
- Have to write and/or regularly modify a platform-specific script to set the environment variable or pipe the settings from a settings file into an environment variable, instead of just deploying an updated settings JSON file.
- Changing settings by changing an environment variable means the app has to be stopped/started. Granted that this is likely to be needed anyway, here is a case where it would be better for meteor to reload my settings:

My app generates links to an external site. The base URL of this site is stored in my settings file. I could store this in the database, but I have to load those settings from somewhere when the app runs on an empty database, and I would like to start running my app without having to wait for a 'Settings' subscription. The URL is unlikely to change, but on the rare chance that I need to change it, I would like to be able to do so without modifying login/startup/other scripts with embedded JSON, or ideally without having to stop/start node.js.

Another general issue is that - dumping environment variables for viewing/saving is painful if there is a lot of JSON in the output.

These are all surmountable and have valid rebuttals, but using a path and having Meteor read the file would be a lot cleaner IMO. Better to use environment variables for values that almost never change, such as whether a server is development/test/production, and the location of settings files which do themselves change from time to time.

Alternatively, an API to allow an app to manage Meteor.settings would let users set them however they want.

**Comment by dcsan** [comment]
I just had someone ask me for clarification how to do this, this is what I'm doing

put your config file into /private eg

    /private/config.json

there you store the various keys, NOT in the public block
(note you'll have to remove comments in the JSON file)

```
{

 // secret stuff out of the way

  "loginServices": {
    "facebook": {
      "service": "facebook",
      "appId": "xxx",
      "secret": "xxx"
    },
    "twitter": {
      "service": "twitter",
      "consumerKey": "xxx",
      "secret": "xxx"
    }
  },

  "public": {

    "facebook": {
      "appId": "XXX"    // also needed here for API calls?
    },


    "login": "USERNAME_ONLY",  // not sure if this is needed too

    "AccountsUiConfig": {
      "passwordSignupFields": "USERNAME_AND_OPTIONAL_EMAIL",
      "requestPermissions": {
        "facebook": [
          "email",
          "user_friends",
          "friends_events",
          "friends_location",
          "friends_about_me",
          "friends_status"
        ]
      }
    },
}

```

now, you have to read them in and tell meteor to use them
note this will reset your config every restart

```coffee
Meteor.startup ->
  if Meteor.isServer
      # reset services
      Accounts.loginServiceConfiguration.remove({})
      Accounts.loginServiceConfiguration.insert(
        Meteor.settings.loginServices.facebook
      )
      Accounts.loginServiceConfiguration.insert(
        Meteor.settings.loginServices.twitter
      )

```

then when you run your meteor app, or deploy it you need to give 

    meteor --settings private/config.json

**Comment by dcsan** [comment]
if you want to force the UI to have certiain config fields only you'll have to do:


```
Meteor.startup ->
  # do this first, client only
  if Meteor.isClient
    Accounts.ui.config(cfg)
```

**Comment by dandv** [comment]
@glasser: any chance of reopening this, now that feature requests are tracked on GitHub? Thanks!

**Comment by glasser** [comment]
I don't think we have any current plans to redefine the interpretation of `METEOR_SETTINGS`.

**Comment by elidoran** [comment]
Workaround:

1. `git clone https://github.com/meteor/meteor.git`
2. do `git checkout <commit>` for the specific commit of the release version you're currently using (look that up at [releases](https://github.com/meteor/meteor/releases))
2. symlink its "packages/meteor" package into your app's "packages" directory as "meteor"
3. alter the file "server_environment.js" like below
4. provide an absolute path to your settings file as `METEOR_SETTINGS_FILE`

```javascript
if (process.env.METEOR_SETTINGS) {
  try {
    Meteor.settings = JSON.parse(process.env.METEOR_SETTINGS);
  } catch (e) {
    throw new Error("METEOR_SETTINGS are not valid JSON: " + process.env.METEOR_SETTINGS);
  }
} else if (process.env.METEOR_SETTINGS_FILE) {
  try {
    Meteor.settings = JSON.parse(
      Npm.require('fs').readFileSync(process.env.METEOR_SETTINGS_FILE, 'utf8')
    );
  } catch (e) {
    throw new Error("METEOR_SETTINGS_FILE is not a valid JSON file: " + process.env.METEOR_SETTINGS_FILE);
  }
}
```

This worked both in development mode and in a production build.
