### ISSUE TITLE
oplog_tailing.js bug

### ISSUE THREAD

**Issue by codeneno** [meteor/meteor#11187]
TypeError: Cannot read property 'u' of undefined 
![image](https://user-images.githubusercontent.com/66900278/94251824-ae4ff480-ff55-11ea-82f3-2fdfa095ba6d.png)\

![image](https://user-images.githubusercontent.com/66900278/94251948-db9ca280-ff55-11ea-993e-c7aa9c0f7627.png)

**Comment by pafik13** [comment]
@codeneno I think it's not meteor bug but just error in Rocket Chat logic.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
