### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#11180]
should the trailing comma be there?  https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/packages/accounts-password/password_server.js#L77

**Comment by StorytellerCZ** [comment]
Yes, that looks like a typo.

**Comment by harryadel** [comment]
I was double checking since I was afraid it'd get rejected :sweat_smile: 
https://github.com/meteor/meteor/pull/11182

**Comment by filipenevola** [comment]
This will be included on Meteor 1.12 https://github.com/meteor/meteor/pull/11182
