### ISSUE TITLE
unable to import @tweenjs/tween.js v18.6.0 from NPM

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#11205]
Meteor 1.11, Linux

### Expected:

Ability to import from `@tweenjs/tween.js` just like we can in other systems (f.e. it works fine in a Webpack-based app).

```js
import {Tween} from '@tweenjs/tween.js'
new Tween // this should work
```

### Actual:

`Tween` is `undefined` so `new Tween` fails.

### Reproduction:

```sh
git clone https://github.com/lume/website
git checkout meteor-issue-11205
npm install
meteor
```

then open the app in browser.

**Comment by trusktr** [comment]
### Reproduction

```
git clone https://github.com/lume/website
git checkout meteor-issue-11205
npm install
meteor
```

**Comment by StorytellerCZ** [comment]
Tween has only a default export, not named one, so your import should be:

`import Tween from '@tweenjs/tween.js'`

**Comment by trusktr** [comment]
Hmm, interesting, the `dist/tween.esm.js` file indeed has that, but the `dist/index.d.ts` file has

```ts
declare modue 'TWEEN' {
    // ...
    export default TWEEN;
}

declare module "@tweenjs/tween.js" {
    import TWEEN from "TWEEN";
    export = TWEEN;
}
```

and I've been importing it and using it as

```
import {Tween} from '@tweenjs/tween.sj'
```

in non-Meteor projects.

The Tween.js output should probably be fixed so the types matches the JS output exactly.

**Comment by trusktr** [comment]
I think I'll close this, because clearly the type def is different than the actual JS code, and probably the tooling I'm using outside of Meteor is handling this special case, but Meteor is handling only actual ESM semantics in this case (which is totally fine).

**Comment by trusktr** [comment]
Sidenote, I have since fixed Tween.js exports. TypeScript users will now see exactly what the exports are and they will match up with runtime expectations.
