### ISSUE TITLE
Examples directory is outdated 

### ISSUE THREAD

**Issue by OlivierJM** [meteor/meteor#11214]
I was going through the different parts of meteor and noticed that the examples haven't been updated more many years, most of them still have the version of meteor prior to v1. 

There are great examples in this directory though I don't think this is documented anywhere in the official docs

Source: https://github.com/meteor/meteor/tree/devel/examples

What could be done, this directory could be extracted into a separate repo and more updated examples can be pushed there, this will keep the codebase just meteor core and packages related only and in the documentation we can link where examples are. 

With some guidance, I am glad to work on getting this done 

cc: @filipenevola

**Comment by StorytellerCZ** [comment]
Oh wow, these should probably be moved out of the repository all together. Some interesting history there though. Might be interesting to update them and make them into tutorials or something along those lines.

**Comment by OlivierJM** [comment]
I totally agree, I think making a separate repository for examples or tutorials would be great.

**Comment by StorytellerCZ** [comment]
Tutorials are already moving in that direction. If I have noticed this a month ago, then updating examples would have been my Hacktoberfest project. :laughing:

**Comment by OlivierJM** [comment]
Looking forward to this. I hope I can make some contributions towards that.
