### ISSUE TITLE
Hiding the names of files from dynamic imports

### ISSUE THREAD

**Issue by schlaegerz** [meteor/meteor#11217]
I was looking into the security of my code and how to restrict what information is naturally put out and I was wondering if there is any way to hide the names of the files in the dynamic imports. If I look inside of the chrome console I can see each individual file I included which is not ideal as it presents a bit more information than I would like.

Is there any way to change it to just use the hash ID of the file instead of the original name?

On the same lines, is it possible to restrict access to a particular import, for instance if I only want admins on my site to be able to import a section of code.

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

In any case, why do you need to hide your file names? Dynamic imports are asking the files with the names specified in your imports, if you want to use a different name you could name your files differently. I don't see what is the problem on using the actual file names to fetch dynamic modules.

About your second comment, you could throw an error when evaluating a file based on what user is requesting this specific file but it seems to be an weird requirement, I'm not sure why you would need to do that.

Please send this question there and I'm sure you are going to get some help.
