### ISSUE TITLE
package-source discovery and caching does not respect --exclude-archs

### ISSUE THREAD

**Issue by mfen** [meteor/meteor#11216]
I was attempting to test a node_modules recompile for legacy with `--exclude-archs web.browser`s, but it did not recompile due to #11215 . I would have expected that `_findSources` would not run for the excluded archs, and so we’d avoid that caching bug and recompile for legacy.

Meteor v1.11.1
OS X v10.15.5

It seems package-source's `initFromAppDir()` builds `SourceArch`s for all `compiler.ALL_ARCHES`, hence the caching of web.browser sources even with `--exclude-archs`, triggering #11215.

Should the filtered `webArchs` be passed from bundler to package-source instead, so `SourceArch`'s are only created for the filtered webArchs  + ‘os’?

**Comment by filipenevola** [comment]
Hi @mfen can you double check if my fix also fixed this issue in the next 2.0 beta?

It's going to included in the beta after beta.9

**Comment by filipenevola** [comment]
Hi @mfen could you try on Meteor 2.0-rc.3?

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Comment by mfen** [comment]
Thanks for following up! Per https://github.com/meteor/meteor/issues/11215#issuecomment-773598669, I'm hoping to find time to test these out later this month and I'll post an update.
