### ISSUE TITLE
TypeError: formData is not a function

### ISSUE THREAD

**Issue by themak01** [meteor/meteor#11221]
This is front end ReactJs

`import React, {useState} from "react";
import { Link } from "react-router-dom";
import { isAutheticated } from "../auth/helper";
import Base from "../core/Base";
import { CreateaPost } from "./helper/userapicalls";

const Post = () => {

  const {user, token} = isAutheticated()

  const [values, setValues] = useState({
    postedby: "",
    description: "",
    photo: "",
    loading: false,
    error: "",
    createdPost: "",
    getaRedirect: false,
    formData: ""
  });

  const {
    postedby,
    description,
    loading,
    error,
    createdPost,
    getaRedirect,
    formData
  } = values;

  const onSubmit = (event) =>{
    event.preventDefault();
    setValues({...values, error:"", loading: true})
    CreateaPost(user._id,token,formData)
    .then(data => {
      if (data.error){
        setValues({...values, error: data.error})
      }else{
        setValues({
          ...values,
          postedby: "",
          description: "",
          photo: "", 
          loading: false,
          createdPost: data.post
        })
      }
    })
  }

  const handleChange = postedby => event => {
    var formdata = new FormData
    const value = postedby === "photo" ? event.target.files[0] : event.target.value;
    formdata.set(postedby, value)
    setValues({ ...values, [postedby]: value });
  };

  const successMessage = () => (
    <div className="alert alert-success mt-3"
    style = {{display: createdPost ? "" : "none"}}
    >
    
    </div>
  )

  const warningMessage = () => {
    if(error) {
      
        return <h4 className="alert alert-danger mt-3">Post could not be created</h4>
        console.log(error);
    }
}
    const AddPost = () =>{
      return (
        <div className="row">
          <div className="col-md-6 offset-sm-3 text-left">
            <form>
              <div className="form-group">
                <label className="text-light">Hi</label>
                <input
                placeholder="Add Product"
                  className="form-control"
                  type="text"
                  onChange={handleChange("description")}
                />
              </div>
              
              <input
            onChange={handleChange("photo")}
            type="file"
            name="photo"
            accept="image"
            placeholder="choose a file"
          />
              
              <button className="tweetBox__tweetButton"
              onClick = {onSubmit}
              >
                Realease
              </button>
            </form>
          </div>
          
        </div>
        
      );
    }
    
  return (
    <Base title="Add new post">
      {AddPost()}
      {successMessage()}
      {warningMessage()}
    </Base>
  );
};

export default Post;
`

This is how my frontend talk to backend
`import { API } from "../../backend";

//Create post
export const CreateaPost = (userId, token, post) => {
    return fetch(`${API}/post/create/${userId}`, {
        method: "POST",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${token}`
        },
        body: post
      })
        .then(response => {
          return response.json();
        })
        .catch(err => console.log(err));
}

//Delete POST
export const DeletePost = (postId,userId, token,) => {
    return fetch (`${API}/post/delete/${postId}/${userId}`,{
        method: 'DELETE',
        headers: {
            Accept: 'application/json',
            Authorization: `Bearer ${token}`
        }
    })
    .then(response => {
        return response.json()
    })
    .catch(error => console.log(error))
}
//Get a POST

    export const getPost = postId => {
        return fetch(`${API}/post/${postId}`,{
            method: 'GET',
        }).then(response => {
            return response.json()
        }).catch(error => console.log(error))
    }

//Update POST

export const UpdatePost = (postId,userId, token, post) => {
    return fetch (`${API}/post/update/${postId}/${userId}`,{
        method: 'PUT',
        headers: {
            Accept: 'application/json',
            Authorization: `Bearer ${token}`
        },
        body: post
    })
    .then(response => {
        return response.json()
    })
    .catch(error => console.log(error))
}

`

**Comment by stolinski** [comment]
This is not a Meteor issue. Check your code for JS syntax errors. Check the line `var formdata = new FormData` either way this is not related to Meteor.

**Comment by themak01** [comment]
> This is not a Meteor issue. Check your code for JS syntax errors. Check the line `var formdata = new FormData` either way this is not related to Meteor.

The code and syntax is ok but still I have tried another methods but getting same issue

**Comment by stolinski** [comment]
I can assure you that this is a syntax issue and not anything related to meteor. 

Here:
```
const [values, setValues] = useState({
postedby: "",
description: "",
photo: "",
loading: false,
error: "",
createdPost: "",
getaRedirect: false,
formData: ""
});
```
You are defining formData as a string

`formdata.set(postedby, value)`

Here, you are attempting to use the same formData variable as a function, giving you the error that formData is not a function.

**Comment by themak01** [comment]
I have used this also
const [values, setValues] = useState({
postedby: "",
description: "",
photo: "",
loading: false,
error: "",
createdPost: "",
getaRedirect: false,
formData: new FormData(),
});
But after this another problem comes out which is backend related and in backend there is no error in code

**Comment by stolinski** [comment]
Ok. It's difficult to see when the code isn't formatted. Either way this error specifically `formData is not a function` is not coming from Meteor. I'd recommend posting a reproducible repo here or a sandbox so people can test out. But this seems like a syntax error still to me. https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData 
I would def recommend against putting formData as a constructor in React state or re-using variable names that are defined as react state.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while and this doesn't look to be an issue in Meteor.

**Comment by attuchaudhary9** [comment]
const [values, setValues] = useState({
postedby: "",
description: "",
photo: "",
loading: false,
error: "",
createdPost: "",
getaRedirect: false,
formData: new FormData() //<--- fix it
});

**Comment by priyanshuk99** [comment]
const [values, setValues] = useState({
postedby: "",
description: "",
photo: "",
loading: false,
error: "",
createdPost: "",
getaRedirect: false,
formData: {} //<--- fix it
});

just do this and that's it. Cause previously formData was string, but now it is an empty object, and since function is also an object it would fix your code. I'm not sure it is the correct way or not but it save me 👍
