### ISSUE TITLE
HMR Not Quite Working Yet?

### ISSUE THREAD

**Issue by VikR0001** [meteor/meteor#11235]
I'm getting this error when trying to use HMR:

<img width="1052" alt="Screen Shot 2020-11-08 at 3 51 42 PM" src="https://user-images.githubusercontent.com/10912958/98501721-e315c380-2204-11eb-9b0c-5bd21b085f2b.png">

Does this mean anything to anybody?

Possibly relevant (?): I'm using [Swydo:ddp-Apollo](https://github.com/Swydo/ddp-apollo), and my app is a  PWA.

**Comment by filipenevola** [comment]
Hi @VikR0001 I believe this issue is already fixed here https://github.com/meteor/meteor/pull/11228. It'll be included in the next beta.

**Comment by VikR0001** [comment]
Fantastic. Thanks very much, @filipenevola !

**Comment by filipenevola** [comment]
Hi @VikR0001 I believe 2.0-beta.6 fixes this issue so I'm closing it.
