### ISSUE TITLE
bug: Getting blank screen on IE11/Edge - nodeModules compiling issue

### ISSUE THREAD

**Issue by Gorbus** [meteor/meteor#11239]
Hi,

Reporting a bug here which is causing us a major issue for our project. We have clients who are unfortunately using IE11 or old Edge and the app we developed in meteor/react seems to be crashing. We need to find a solution asap and so far nothing we tried helped.

**Title**: Blank screen on IE11/Edge / code not compiled to be readable by these browsers
**Meteor version**: 1.11.1
**Platforms**: Developing from mac OS, testing through local network on a windows 10 machine with IE11 / Edge
**Expected behavior**: for the node_modules mentioned in meteor.nodeModules.recompile to be recompiled and work on legacy browsers
**Actual behavior**: blank screen with multiple errors: 

> '(' is expected
> Unable to get the property 'meteorInstall' a null reference or undefined

**Reproduction**: 
I did a simple app with the module that's causing our issue. It seems to be an error because of regenerator.
https://github.com/Gorbus/meteor_blank_ie11

Thanks in advance for any help. We can't afford to change everything now so any idea/solution would be appreciated.

**Comment by filipenevola** [comment]
Hi @Gorbus, could you double check if it's not the same issue as here https://github.com/meteor/meteor/issues/11163?

**Comment by ruohki** [comment]
react 16 is not compatible with ie 11 you have to use polyfills to make it working

**Comment by renanccastro** [comment]
@Gorbus have you tried the suggestion from @ruohki ?

**Comment by StorytellerCZ** [comment]
@Gorbus Any update on this? Have you tried suggestion from @ruohki ? Could you please check that the issue persist on the latest Meteor version? If yes, could you provide us with a reproduction or steps to reproduce the issue?

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
