### ISSUE TITLE
Authentication on the  server rendering

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11236]
@filipenevola @zodern and Other ...
Hi, I have a really big problem that I did not get an answer for a long time .
You see, I have to use SSR and it is an important issue for me.
Now is there a way to detect if the user is logged in to the rendering server or not?
In fact, the server must render the components of the react according to the user's login status.
Also, the Client must render the components according to the user's login status.
And we can easily detect in the client whether the user is logged in or not and render accordingly.
But on the server, how can we find out if this **Request** is logged in or not ?
**In fact, meteor methods for detecting user login status do not work on the server**
This is an important issue and in any powerful framework, you can easily check the user login status in each request.

**Comment by Saeeed-B** [comment]
And we have to say that for some reason I just want to use the[ server-render ](https://docs.meteor.com/packages/server-render.html)package

**Comment by Saeeed-B** [comment]
I discussed this in more detail in the forum : 
[https://forums.meteor.com/t/authentication-on-the-server-rendering/54465](https://forums.meteor.com/t/authentication-on-the-server-rendering/54465)

Some friends said use the methods and get the user ID .
But this method is not correct because the user ID in the methods is only available when these methods are called by the client.
[SHOW More](https://forums.meteor.com/t/authentication-on-the-server-rendering/54465/4)

**Comment by Saeeed-B** [comment]
Some friends said use the pub/sub and get the user ID .
 I have to say about subscribe and publishing ,
This is not a logical method either because the subscription only works on the client.
And we can not wait for the client to load and then render on the server side.
And basically the server rendering and the client load should be simultaneous and maybe the server rendering will be faster.

[SHOW MORE](https://forums.meteor.com/t/authentication-on-the-server-rendering/54465/6)

**Comment by tjramage** [comment]
@Saeeed-B – I don't believe this is possible without storing a cookie of some sort. By default, Meteor stories client-session information in local storage (Meteor.loginToken), which of course is not sent in any request to the server. This is by design, and comes with some security benefits (cross site request forgery).

If you want to get around this, your best bet is probably to store a login token in a cookie, and then read that on the server request to lookup the user, check if the token is valid, etc.

**Comment by renanccastro** [comment]
Hi @Saeeed-B, exactly as @tjramage said, you will have to use cookies.
I did an implementation of this concept based on kadira's fast render code base. You can find it here:            https://www.github.com/pathable/meteor-fast-methods/tree/master/lib%2Fauth.js this file orchestrate it together with context.js. See the server.js file for an example on how to use it.

**Comment by Saeeed-B** [comment]
@tjramage @renanccastro Yes, you are right .
The only way is for us to check the login status of each request.
But implementing this requires great skill.
@filipenevola  And I think that's important enough for Meteor to think about.
And this problem must be solved in the core of the Meteor .
It's so important that a few years of my work on Meteor may be wasted and I will have to give up this formwork (despite my skepticism).

**Comment by Saeeed-B** [comment]
@tjramage @renanccastro Thank you very much for your help in solving this problem accurately .
Thank you very much if you can justify me with an example .

**Comment by renanccastro** [comment]
You are using "sink" with onPageLoad, right?
You can add the package I've done: meteor add pathable:meteor-fast-methods, and use it like this:

```
  onPageLoad(sink => {
    const loginToken = sink.request.cookies['meteor_login_token'];

    const context = new Context(loginToken, { headers: sink.request.headers });
    FastMethods.fastMethodsContext.withValue(context, function () {
            //here you can use: this.userId and Meteor.user() and run your logic
    })
})
```

**Comment by renanccastro** [comment]
Also, the best place to ask questions like this is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).
Please send this question there and I'm sure you are going to get some help.

**Comment by Saeeed-B** [comment]
Yes, I mentioned it in the forum, but here I wanted to know the official program of Meteor for this issue
