### ISSUE TITLE
isobuild crashes with ERR_INVALID_ARG_TYPE when encountering broken symlinks in 1.11

### ISSUE THREAD

**Issue by tchiers** [meteor/meteor#11241]
I encountered this on the upgrade to 1.11. My project has some broken symlinks in mode_modules/.bin (presumably legacy cruft). They didn't bother meteor pre-1.11, but now cause isobuild to crash with a tremendously cryptic error:
```
=> Started proxy.
/home/xxx/.meteor/packages/static-html/.1.2.2.1httr42.mghq++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.relative (path.js:1054:5)
    at Object.wrapper [as pathRelative] (/home/xxx/.meteor/packages/meteor-tool/.1.11.0.q6y7e2.89d8a++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/tools/static-assets/server/mini-files.ts:107:14)
```
I eventually figured it out. in meteor_tool/.../tools/isobuild/bundler.js you have

```
      return this._prodPackagePredicate = function isWithinProdPackage(path) {
        const parts = files.pathRelative(sourcePath, path).split(files.pathSep); // Normalize away trailing files.pathSep characters.

...
          if (fileStatus && fileStatus.isSymbolicLink()) {
            // If node_modules/.bin/command is a symlink, determine the
            // answer by calling isWithinProdPackage(real).
            return isWithinProdPackage(files.realpathOrNull(path));
          } // If node_modules/.bin/command is not a symlink, then it's hard
          // to tell which package is responsible for it, so don't strip it.
...
```

you have a potentially recursive call `return isWithinProdPackage(files.realpathOrNull(path));` where the value passed to isWithinProdPackage could be null, and that value will be used to call `files.pathRelative()` which cannot tolerate a null argument.

I would suggest going back to ignoring broken symlinks by checking for null before calling isWithinProdPackage, or at least throwing a more insightful error.

**Comment by filipenevola** [comment]
Hi @tchiers, if I understood correctly your issue was broken symlinks in your project.

So you are suggesting that we should ignore broken symlinks or at least throw a clear error about that, is that correct?

Are you willing to make this adjustment?

**Comment by tchiers** [comment]
You're correct.

I'll try to put together a PR for this.

**Comment by filipenevola** [comment]
Great @tchiers, make sure you read how to contribute first https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md

It seems intimidating but it's not and we are here to help 😉
