### ISSUE TITLE
Update event for method not returned from server.

### ISSUE THREAD

**Issue by DavidSichau** [meteor/meteor#11240]
We observer a very strange behavior of meteor on one of our instances. 

This behavior can be observed on one of our instances but not on others, where we run the exact same container, in which our meteor application is bundled. The behavior can be observed on around 20% of the initial load of the meteor application in this instance. We do not see any server of client side errors.

The main problem is, that for the method 'login' never the update event is send via the websocket. And therefore `dataVisible` is never called in the `MethodInvoker`.

From our understanding so far it seems that in `livedata_server.js` in the `ddp-server` package the fence is never committed and therefore the `onAllCommitted` is never executed (see https://github.com/meteor/meteor/blob/ab0affe98bb917d26338d96d1ea3520a6dc5cbff/packages/ddp-server/livedata_server.js#L655).

From our understanding this happens when there are still  outstanding_writes. But why this behavior can occur is unclear to us. 

If anyone has suggestion how to figure out the root cause of this problem this would be very helpful. If interested we could show you the behavior on this instance via zoom. 

Here the log of the messages send via the websocket:

```

o | 1 | 14:09:10.827
-- | -- | --
["{\"msg\":\"connect\",\"version\":\"1\",\"support\":[\"1\",\"pre2\",\"pre1\"]}"] | 81 | 14:09:10.828
["{\"msg\":\"method\",\"method\":\"login\",\"params\":[{\"resume\":\"TQmwt48n6-okJmdYa0aZ0zS1IJVdGPDAxik_Awi0Vca\"}],\"id\":\"1\"}"] | 132 | 14:09:10.828
["{\"msg\":\"sub\",\"id\":\"wgzdTqH4rLoZRSLMD\",\"name\":\"meteor.loginServiceConfiguration\",\"params\":[]}"] | 110 | 14:09:10.829
["{\"msg\":\"sub\",\"id\":\"rkxYtLmDgtmvjQoWv\",\"name\":\"meteor_autoupdate_clientVersions\",\"params\":[]}"] | 110 | 14:09:10.829
["{\"msg\":\"sub\",\"id\":\"ZjxQn5B4crfaDTD85\",\"name\":\"settings.getSemesters\",\"params\":[]}"] | 99 | 14:09:10.830
["{\"msg\":\"sub\",\"id\":\"7CNs72myi7CBtMySX\",\"name\":\"notifications.global\",\"params\":[]}"] | 98 | 14:09:10.830
["{\"msg\":\"sub\",\"id\":\"y7yWAxRCctmL44Avm\",\"name\":\"users.userProfile\",\"params\":[]}"] | 95 | 14:09:10.830
["{\"msg\":\"sub\",\"id\":\"HFXELYPhwEpzjEep2\",\"name\":\"settings.getHeaderColor\",\"params\":[]}"] | 101 | 14:09:10.831
a["{\"server_id\":\"0\"}"] | 26 | 14:09:10.835
a["{\"msg\":\"connected\",\"session\":\"7RNatieqfup698C52\"}"] | 62 | 14:09:10.836
a["{\"msg\":\"added\",\"collection\":\"users\",\"id\":\"AuDjSPPdvoieFnYhC\",\"fields\":{\"emails\":[{\"address\":\"sichau@inf.ethz.ch\",\"verified\":true}],\"username\":\"sichaud\"}}"] | 184 | 14:09:10.861
a["{\"msg\":\"added\",\"collection\":\"meteor_accounts_loginServiceConfiguration\",\"id\":\"-3c0d664695ad15dfc58bcefd\",\"fields\":{\"service\":\"eth\",\"url_authorize\":\"https://login.expert.ethz.ch/authorize\",\"url_token\":\"https://login.expert.ethz.ch/token\",\"url_identity\":\"https://login.expert.ethz.ch/user/info\",\"url_logout\":\"https://login.expert.ethz.ch/user/logout\",\"client_id\":\"3c0d664695ad15dfc58bcefd\"}}"] | 432 | 14:09:10.862
a["{\"msg\":\"ready\",\"subs\":[\"wgzdTqH4rLoZRSLMD\"]}"] | 57 | 14:09:10.863
a["{\"msg\":\"ready\",\"subs\":[\"rkxYtLmDgtmvjQoWv\"]}"] | 57 | 14:09:10.864
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version\",\"fields\":{\"version\":\"outdated\"}}"] | 133 | 14:09:10.864
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version-refreshable\",\"fields\":{\"version\":\"outdated\"}}"] | 145 | 14:09:10.865
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version-cordova\",\"fields\":{\"version\":\"outdated\"}}"] | 141 | 14:09:10.866
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"web.browser\",\"fields\":{\"version\":\"e06df00e650f78dafacd504923abacec24da76ad\",\"versionRefreshable\":\"41fe66637ec39b43e819c60e9707113bc1424c74\",\"versionNonRefreshable\":\"a89bf0d96f380a4dadc3f89c07456b7b69c73eaf\",\"assets\":[{\"url\":\"/669ee8ed6bb1488f03c76b9a6ba22413e00fe1a3.css?meteor_css_resource=true\"}]}}"] | 406 | 14:09:10.867
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"web.browser.legacy\",\"fields\":{\"version\":\"38d27d8e81a4ba8cff907f2466e536a50447ddc6\",\"versionRefreshable\":\"41fe66637ec39b43e819c60e9707113bc1424c74\",\"versionNonRefreshable\":\"b85b4b59cebca9b686758c438d5123cf145f4255\",\"assets\":[{\"url\":\"/669ee8ed6bb1488f03c76b9a6ba22413e00fe1a3.css?meteor_css_resource=true\"}]}}"] | 413 | 14:09:10.868
a["{\"msg\":\"added\",\"collection\":\"Settings\",\"id\":\"vCeLvHhvt3Je36BW3\",\"fields\":{\"key\":\"Semesters\",\"values\":[{\"index\":8,\"key\":\"AS20\",\"current\":true,\"visible\":true},{\"index\":7,\"key\":\"SS20\",\"current\":false,\"visible\":true},{\"index\":6,\"key\":\"AS19\",\"current\":false,\"visible\":true},{\"index\":5,\"key\":\"SS19\",\"current\":false,\"visible\":true},{\"index\":4,\"key\":\"AS18\",\"current\":false,\"visible\":true},{\"index\":3,\"key\":\"SS18\",\"current\":false,\"visible\":false},{\"index\":2,\"key\":\"AS17\",\"current\":false,\"visible\":false},{\"index\":1,\"key\":\"SS17\",\"current\":false,\"visible\":false},{\"index\":0,\"key\":\"AS16\",\"current\":false,\"visible\":false}]}}"] | 726 | 14:09:10.868
a["{\"msg\":\"ready\",\"subs\":[\"ZjxQn5B4crfaDTD85\"]}"] | 57 | 14:09:10.869
a["{\"msg\":\"result\",\"id\":\"1\",\"result\":{\"id\":\"AuDjSPPdvoieFnYhC\",\"token\":\"TQmwt48n6-okJmdYa0aZ0zS1IJVdGPDAxik_Awi0Vca\",\"tokenExpires\":{\"$date\":1612873740612},\"type\":\"resume\"}}"] | 201 | 14:09:10.870
a["{\"msg\":\"ready\",\"subs\":[\"7CNs72myi7CBtMySX\"]}"] | 57 | 14:09:10.871
a["{\"msg\":\"changed\",\"collection\":\"users\",\"id\":\"AuDjSPPdvoieFnYhC\",\"fields\":{\"email\":\"sichau@inf.ethz.ch\",\"firstname\":\"David\",\"gender\":\"m\",\"language\":\"en\",\"lastname\":\"Sichau\",\"legi\":\"00-000-000\",\"roles\":[\"staff\"],\"title\":\"Dr.\"}}"] | 275 | 14:09:10.871
a["{\"msg\":\"ready\",\"subs\":[\"y7yWAxRCctmL44Avm\"]}"] | 57 | 14:09:10.871
a["{\"msg\":\"ready\",\"subs\":[\"HFXELYPhwEpzjEep2\"]}"] | 57 | 14:09:10.872
a["{\"msg\":\"ping\"}"] | 23 | 14:09:40.834
["{\"msg\":\"pong\"}"]

```
From then on only ping/pong is exchanged.

**Comment by filipenevola** [comment]
Hi @DavidSichau is there any chance that one of your methods is never returning?

Sorry to ask this but do you know about Meteor `this.unblock()` for Methods? 

I usually unblock all my methods (and even publications) as it's very rare in my cases that one method will depend on the execution of another method. There is an article about unblock here https://pmuens.medium.com/meteor-defer-and-this-unblock-e610c8426065 and also the official doc here https://galaxy-guide.meteor.com/apm-managing-waittime.html#Using-this-unblock

Also, do you know how to reproduce this behavior or you only know it happens in ~20% of your containers?

I don't believe this is an issue in Meteor but of course if you provide a reproduction you could prove me wrong.

**Comment by DavidSichau** [comment]
Hi @filipenevola thanks for the answer. The method which is blocking is unfortunately an internal meteor method.

It is the login method of meteor which seems to block (https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/packages/accounts-base/accounts_client.js#L286), so we cannot use `this.unblock()`, as the code is out of our scope.

This is the method invocation in the websocket:

`["{\"msg\":\"method\",\"method\":\"login\",\"params\":[{\"resume\":\"TQmwt48n6-okJmdYa0aZ0zS1IJVdGPDAxik_Awi0Vca\"}],\"id\":\"1\"}"] | 132 | 14:09:10.828
`
and for this method we only see:

`a["{\"msg\":\"result\",\"id\":\"1\",\"result\":{\"id\":\"AuDjSPPdvoieFnYhC\",\"token\":\"TQmwt48n6-okJmdYa0aZ0zS1IJVdGPDAxik_Awi0Vca\",\"tokenExpires\":{\"$date\":1612873740612},\"type\":\"resume\"}}"] | 201 | 14:09:10.870
`

This websocket message is missing if we observe this behavior:

`a["{\"msg\":\"updated\",\"methods\":[\"1\"]}"]`

However ddp should return an update event, which we are able to observe if it is not blocking. If we manually trigger the function  `dataVisible` of meteor on the client side it then continues and everything works.

To reproduce it we need to reload our webpage and in around 2 of 10 tries we end with this strange behavior. Otherwise everything works as expected.

**Comment by filipenevola** [comment]
Hi @DavidSichau maybe you have publications re-running when you update your user and your method is waiting?

Are you running on Galaxy with Meteor APM enabled? You could see traces on APM if that is the case.

If you are a Galaxy client we could also help you at support@meteor.com

**Comment by DavidSichau** [comment]
@filipenevola Thanks for the hint with the publication. We will have look at them and see if they might cause the issue.

I will reopen this issue if we have further insights.

**Comment by filipenevola** [comment]
@DavidSichau perfect. This is always the idea, try to confirm if a problem is on Meteor or not, investigate, discuss here, in the Forums, on Slack, until we find a solution together.

Thanks 😄
