### ISSUE TITLE
Apple Silicon not supported

### ISSUE THREAD

**Issue by JanMP** [meteor/meteor#11249]
Trying to install meteor on new MacBook Pro sadly yields this result:
```
➜ curl https://install.meteor.com/ | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7915    0  7915    0     0  14390      0 --:--:-- --:--:-- --:--:-- 14364
Only 64-bit Intel processors are supported at this time.
```

**Comment by wreiske** [comment]
<img width="710" alt="Screen Shot 2020-11-20 at 9 30 20 AM" src="https://user-images.githubusercontent.com/6295044/99830764-06007b80-2b13-11eb-8ef3-cfce546d9d8e.png">

Seeing the same thing.

**Comment by hexsprite** [comment]
Until there's a native Apple Silicon version, will these steps work? https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/

**Comment by JanMP** [comment]
Thanks guys, both your solutions work like a charm. And despite running in Rosetta it still is quite a bit faster than my 2016 MacBook Pro 13'' 🎉

**Comment by renanccastro** [comment]
We still don't have native binaries for nodejs on Apple silicon's. It's important to keep an eye here: https://github.com/nodejs/build/issues/2474

I think a good workaround we can do right now is to change the meteor script to use -arch (rosetta 2) when it detects the arm architecture.

**Comment by jamesloper** [comment]
Homebrew is now hosting a native arm64 binary of nodejs.

https://homebrew.bintray.com/bottles/node-15.6.0.arm64_big_sur.bottle.tar.gz

**Comment by zvictor** [comment]
> Homebrew is now hosting a native arm64 binary of nodejs.
> https://homebrew.bintray.com/bottles/node-15.6.0.arm64_big_sur.bottle.tar.gz

Would it then be possible to run meteor using a different node binary than the bundled one?
Can I make Meteor use this node binary?

**Comment by jamesloper** [comment]
I dove into the `METEOR DEV BUNDLE` and tried to change it to grab node from the bottle. My thoughts were that Meteor has always bundled node since the beginning, so it's kind of unlikely that meteor would offer a feature to run the default node binary, so the most fitting way would be to get it from the bottle. But it was just outside of my area of expertise. I might have another go at it.

**Comment by satyavh** [comment]
Even though this allows you to install Meteor, it still means Meteor needs to run in Rosetta mode, losing performance.

**Comment by StorytellerCZ** [comment]
Looks like the support on this is going to be for Node 15+, so if we rush it, then we could get it to Meteor with Node 16 probably in July, but that is rushing it a lot.

**Comment by gainmedia-sakib** [comment]
### **it still not working for me** 

❯ arch -x86_64 /bin/sh -c "$(curl -fsSL https://install.meteor.com/)"
Only 64-bit Intel processors are supported at this time.

❯ arch -x86_64 zsh
curl https://install.meteor.com/ | sh

Only 64-bit Intel processors are supported at this time.

### **Already I trying some method but it's not working, trying Rosetta Terminal i get same error **
### anyone sagest me how can I do this?

**Comment by StorytellerCZ** [comment]
Since the support for Apple Silicon is from Node 16 we will be able to tackle this once we update there. Given that there are some major hurdles to get over in order to get Meteor to Node 16 don't expect this to happen till the end of the year at earliest (by my estimation).

**Comment by jamesloper** [comment]
Is there a branch for the Node 16 project? I just want to play with it, I'll happily publish whatever I make.

**Comment by StorytellerCZ** [comment]
Node 16 presents breaking changes for Meteor, but @filipenevola is working on them. We'll probably start one after 2.3 release, but don't expect it to work for a while, especially on Apple Silicon as I think that will require some extra changes in the CI to account for it.

**Comment by ANUBHAV04091998** [comment]
thank you it worked.!!
