### ISSUE TITLE
dynamic-import in 1.12 breaks Internet Explorer

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11264]
The prefetchInChunks function crashes in Internet Explorer because it uses an arrow function (err =>) without ecmascript transpiling defined in its package.js.

1.11.1 version:
```
function prefetchInChunks(modules, amount) {
    Promise.all(modules.splice(0, amount).map(function (id) {
      return module.prefetch(id);
    })).then(function () {
      if (modules.length > 0) {
        setTimeout(function () {
          prefetchInChunks(modules, amount);
        }, 0);
      }
    });
  }
```

1.12 version:
```
function prefetchInChunks(modules, amount) {
    Promise.all(modules.splice(0, amount).map(function (id) {
      return new Promise(function (resolve, reject) {
        module.prefetch(id).then(resolve).catch(
          (err) => {
            // we probably have a : _ mismatch
            // what can get wrong if we do the replacement
            // 1. a package with a name like a_b:package will not resolve
            // 2. someone falsely imports a_package that does not exist but a
            // package a:package exists, so this one gets imported and its usage
            // will fail
            if (id.indexOf(METEOR_PREFIX) === 0) {
              module.prefetch(
                METEOR_PREFIX + id.replace(METEOR_PREFIX, '').replace('_', ':')
              ).then(resolve).catch(reject);
            } else {
              reject(err);
            }
          })
      });
    })).then(function () {
      if (modules.length > 0) {
        setTimeout(function () {
          prefetchInChunks(modules, amount);
        }, 0);
      }
    });
  }
```

**Comment by jankapunkt** [comment]
Shouldn't this be covered by `web-browser.legacy`, respectively using the bluebird polyfill for `Promise`? Or is IE11 simply not considered legacy?

**Comment by perbergland** [comment]
It’s the arrow function that breaks IE

**Comment by jankapunkt** [comment]
I think that should also be covered by `web.browser.legacy` as it transpiles all code to ES5

**Comment by perbergland** [comment]
I don’t really know how it’s supposed to be done, but it was easy enough to fix in the source code by changing the arrow function to a classic one.

Maybe the package.js for the dynamic-import package should have included ecmascript to ensure that the published code was compatible with web.browser.legacy if they wanted to use "modern" features. I haven’t seen any description of how all this is to work tbh.

**Comment by perbergland** [comment]
Yes, looking at my ~/.meteor/packages folder, it looks very much that it is the package author that needs to publish different variants. E.g. ~/.meteor/packages/accounts-base/1.7.1/web.browser.legacy could have different content than web.browser by using babel to convert the code. At build/run/test time, meteor doesn’t touch the code in packages - it just serves it up as is.

**Comment by CaptainN** [comment]
The `dynamic-imports` package is not [compiled through ecmascript](https://github.com/meteor/meteor/blob/devel/packages/dynamic-import/package.js) - change it to IE safe syntax, and do a minor version bump.
