### ISSUE TITLE
Using different npm version in local dev bundle

### ISSUE THREAD

**Issue by jamesmillerburgess** [meteor/meteor#11260]
I'm attempting to run a local copy of meteor with npm set to 7.1.0 in order to experiment with some features that could simplify our monorepo setup. 

When I change the version in `build-dev-bundle-common.sh` and `dev-bundle-tool-package.js` and run `generate-dev-bundle.sh`, the output looks like npm 7.1.0 is installed:
<img width="674" alt="스크린샷 2020-12-08 오전 9 24 46" src="https://user-images.githubusercontent.com/15968012/101443596-3def2780-3937-11eb-8100-428b86f500ab.png">

However, checking the npm version returns the local one, and the npm 7 features aren't available when I try to run a project with the local copy:
![스크린샷 2020-12-08 오전 9 26 27](https://user-images.githubusercontent.com/15968012/101443691-77c02e00-3937-11eb-8a99-1c73ecb7ae4a.png)

How can I get this to run with a different version of npm?

**Comment by filipenevola** [comment]
hi @jamesmillerburgess sorry for the delay.

You need to delete your old dev_bundle, like this:

```shell
➜  meteor ✗ rm -rf dev_bundle
➜  meteor ✗ ./meteor npm --version
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
Skipping download and installing kit from /Users/filipe/Documents/meteor/ws/meteor/dev_bundle_Darwin_x86_64_12.20.1.1.tar.gz
Installed dependency kit v12.20.1.1 in dev_bundle.

7.1.0
```

or you can bump the BUNDLE_VERSION=12.20.1.1 first so it's going to be detected automatically.

This is explained here: https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#rebuilding-the-dev-bundle
