### ISSUE TITLE
Calling a function with collection update in Meteor.setTimeout resulting in Error: Author Required.

### ISSUE THREAD

**Issue by KreakEmp** [meteor/meteor#11267]
I am calling a function which do some processing on input and update the mongo collection. When calling this in Meteor.setTimeout() getting error like :
Error: Author is required at getErrorObject (packages\aldeed_collection2-core.js:480:15) 

Basically I want to run some process and update the collection after a timeout. Help me on how to resolve this Author is required ? 

Here is the code snipet:
`const testRunAllProcess = async (input)=>{
	let result = [];
	let allResultFormat = { 
		start_date: moment(input.start_date).format('DD-MM-YYYY'),
		end_date: moment(input.end_date).format('DD-MM-YYYY'),
		summary: result
	};
       await Meteor.call('updateTestAllResult', input._id, allResultFormat);
}

Meteor.setTimeout(()=>{testRunAllProcess(input); }, 0);

//update method
Meteor.methods({
    updateTestAllResult: async function(id, res){
        testTable.update(id, {
            $set: {
                test_all_summary: JSON.stringify(res)
            }
        });
    }
});

//testTable schema
TestTableSchema = new SimpleSchema({
 test_all_summary: {
        type: String,
        label: 'Test All Summary',
        optional: true,
        autoform: {
            type: 'hidden' 
        }
    },
    author: {
        type: String,
        label: 'Author',
        autoValue: function(){
            return this.userId
        },
        autoform: {
            type: 'hidden'
        }
    },
    created_at: {
        type: Date,
        label: 'Created At',
        autoValue: function() {
            return new Date()
        },
        autoform: {
            type: 'hidden'
        }
    }
});`

**Comment by KreakEmp** [comment]
I guess this is the reason for this. I found this excerpt from 'Meteor in Action' Book : 

In the scope of a method, you can read the value for userId just fine because Meteor automatically attaches various variables to the fiber. Methods allow you to access the given environment at the time it was called via this. Through this invocation object, you can access different attributes and functions such as this.userId, which relates to the user that called the method. If you call a function that’s executed outside the current fiber, you’ll lose access to these environmental variables.

When calling an asynchronous function (setTimeoutFor3sCb) that takes 3 seconds to return its result, the original environment gets lost inside the callback. Suddenly this has lost access to userId because it relates to the global object instead of the invocation object.[1] That’s the reason the first console.log can print out the current user ID to the terminal and the second attempt to log causes an error: “Meteor.userId can only be invoked in method calls.” To illustrate the problem, take a look at the following listing.

**Comment by KreakEmp** [comment]
Solution : 
When using asynchronous functions in a method that needs to be able to access the current environment, you can use Meteor’s bindEnvironment function. bindEnvironment creates a fiber and attaches the correct environment automatically.

**Comment by KreakEmp** [comment]
Meteor.setTimeout(()=>{Meteor.bindEnvironment(testRunAllProcess(input))}, 0);

Still getting same error .

**Comment by nathanschwarz** [comment]
this is not a meteor issue, you should go on **stackoverflow**.
you're getting this error because input is surely undefined or have a random value.

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.
