### ISSUE TITLE
Meteor server doesn't recover from mongo server connection

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#11278]
I occasionally get an error when starting a dyno:
Got exception while reading last entry MongoError: Server selection timed out
app/web.1     at Timeout._selectServer [as _onTimeout] (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:1136:18)
app/web.1     at listOnTimeout (internal/timers.js:549:17)
app/web.1     at processTimers (internal/timers.js:492:7)
app/web.1  => awaited here:
app/web.1     at Function.Promise.await (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
app/web.1     at packages/mongo/mongo_driver.js:1073:14
app/web.1     at /app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
app/web.1  => awaited here:
app/web.1     at Promise.await (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
app/web.1     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
app/web.1     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
app/web.1     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1146:10)
app/web.1     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1170:17)
app/web.1     at Cursor.<computed> [as fetch] (packages/mongo/mongo_driver.js:918:44)
app/web.1     at MongoConnection.findOne (packages/mongo/mongo_driver.js:825:56)
app/web.1     at OplogHandle.waitUntilCaughtUp (packages/mongo/oplog_tailing.js:147:52)
app/web.1     at OplogObserveDriver._doneQuerying (packages/mongo/oplog_observe_driver.js:798:36)
app/web.1     at OplogObserveDriver._runInitialQuery (packages/mongo/oplog_observe_driver.js:667:10)
app/web.1     at packages/mongo/oplog_observe_driver.js:191:10
app/web.1     at packages/mongo/oplog_observe_driver.js:15:9
app/web.1     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
app/web.1     at packages/meteor.js:550:25
app/web.1     at runWithEnvironment (packages/meteor.js:1286:24)

I am working on getting the root problem fixed, but the main problem with meteor is that it throws this error continuosly for like 20 minutes at a time, when what I need is for the server to just give up, reject all connections and then restart.

Is there a way to make sure that happens or a better what to handle these mongo errors?

**Comment by ToyboxZach** [comment]
I see there is an option to override connection parameters, but retry count and reconnect interval both get immediately overridden so we can't change them.

Is there any way to at least listen to the events so our code could handle this itself? If not then I think it would be a good feature to add

**Comment by filipenevola** [comment]
Hi @ToyboxZach I believe you could write a new issue here https://github.com/meteor/meteor-feature-requests requesting these new capabilities as a new feature.

If I understood correctly you know the root cause of your MongoDB problem and you are going to fix it in your side and here you are asking the options to try to handle errors and connections problems in Meteor, correct? So it would be better as a feature request as this is not really a problem in Meteor.
