### ISSUE TITLE
MongoDB driver does not support MongoDB 4.2 update method with aggregation

### ISSUE THREAD

**Issue by xwz** [meteor/meteor#11276]
MongoDB 4.2 allows updates such as

~~~
db.collection.update({}, [{$set: {b: '$a'}], {multi:true});
~~~

The driver code https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L526 check allows only object. It should allow for the aggregation array.

**Comment by radekmie** [comment]
I think it'd be counterintuitive to have it on the server only. On the other hand, implementing it in `minimongo` would be quite hard but not impossible. You can use [`rawCollection`](https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection) to access the original driver instance for now.

**Comment by filipenevola** [comment]
As @radekmie said, Meteor collection is intended to work in the client and also in the server.

If you are proposing a new feature for Minimongo then please open your feature request here to we can see how many users are going to support this new feature https://github.com/meteor/meteor-feature-requests

Now if you want to just use in the server side then I believe rawCollection is the way to go.
