### ISSUE TITLE
process.env.NODE_ENV is inconsistent for production build 

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#11287]
This bug reproduced on a freshly initialised (`meteor create`) app: https://github.com/Firfi/meteor-env-bug-repro

process.env.NODE_ENV is called from client/main.js and server/main.js

-----------------

**Meteor 1.12.1**
tried OS: **OSX and Ubuntu**

I cannot pinpoint a specific version this issue didn't occur; I have upgraded my app from one of previous major releases; it used to work consistently there, but with latest releases I noticed my staging behaving like production, scrambling up some user data as a result.

Description:

when I run a production build with NODE_ENV=staging, a function that returns `process.env.NODE_ENV` yields different results on client and on server.

**presumably, process.env.NODE_ENV gets hardcoded to 'production' during build, for client side code**

The expected behavior: process.env.NODE_ENV gives me the same NODE_ENV variable I run the process with

The actual behavior: in some cases, process.env.NODE_ENV is cemented to `production`

Reproduction: repo: https://github.com/Firfi/meteor-env-bug-repro

```
meteor build --directory=../env-bug-build
cd ../env-bug-build
(cd programs/server && npm install)
MONGO_URL="mongodb://localhost:27017/env-bug" ROOT_URL=http://localhost:3000 NODE_ENV=staging PORT=3000 node main.js
```

- check server console: it yields 'staging' 
- check client console: it yields 'production'
- run `process.env.NODE_ENV` in client console: it yields 'staging' again

**Comment by Firfi** [comment]
people 'solve' it with eval() https://github.com/meteor/meteor/issues/9779

**Comment by Firfi** [comment]
may be related https://github.com/meteor/meteor/issues/6399

**Comment by Firfi** [comment]
As a solution (probably it's even gonna be a permanent) I set NODE_ENV during 'meteor build' as well, in this case meteor doesn't substitute NODE_ENV to 'production' on build time. The issue however stays; this software behaviour is very unexpected.

**Comment by filipenevola** [comment]
Hi @Firfi, thank for your detailed report.

May I ask a (maybe) dummy question? Here we go:

Why do you need NODE_ENV in the client?

**Comment by Firfi** [comment]
Hey @filipenevola ! In my specific case, I have several pieces of business logic that are imported both on server and on client *and* depend on environment variable. 

More specifically, one of these pieces is code that takes User object and translates it into an external service format (i.e. Intercom) to be sent to such service 1) from client side by user code 2) from server side by migration code as part of user base migration. For such external service format, user object depends on environment i.e. it has 'env' field that I can operate with on external service side (for Intercom i.e. broadcast an announcement message only to staging users)

Going from specific to most general case again, I believe Meteor team already know more use cases, given they implemented this feature I rely on in 2016: https://docs.meteor.com/changelog.html#es2015modules `The client-side version of process.env.NODE_ENV (and other environment variables) now matches the corresponding server-side values. #6399`

**Comment by filipenevola** [comment]
Hmm, I get it.

In my projects I always add a custom property to my settings so I can define my environment there instead of depending on Node or some other way.

then usually I have a utility like this to get my current environment:

```js
import { Meteor } from 'meteor/meteor';

const ENVS = {
  PRODUCTION: 'PRODUCTION',
  STAGING: 'STAGING',
  DEVELOPMENT: 'DEVELOPMENT',
};

const publicSettings = Meteor.settings.public;

export const Environments = {
  isDevelopment() {
    return publicSettings.env === ENVS.DEVELOPMENT;
  },
  isStaging() {
    return publicSettings.env === ENVS.STAGING;
  },
  isProduction() {
    return publicSettings.env === ENVS.PRODUCTION;
  },
  getEnvironment() {
    return publicSettings.env;
  },
};

```

I'm not saying that your approach is wrong or this issue is not a bug, my point is just to let you know that maybe there are easier ways to define your environment without checking things not 100% in your control.

About the docs that you linked, and there we only have production or development, it's not possible to define a specific value as you are doing.

See:

> process.env.NODE_ENV is now defined on both client and server as either development or production, which also determines the boolean flags Meteor.isDevelopment and Meteor.isProduction

We currently don't support custom values I believe.

**Comment by Firfi** [comment]
This actually makes much sense. I don't *need* to depend on NODE_ENV but at some point I assumed it would be the most straight forward and expectable approach. And it may be not!
