### ISSUE TITLE
TypeError: formData.set is not a function

### ISSUE THREAD

**Issue by themak01** [meteor/meteor#11284]
//This is frontend Reactjs where I'm getting issue 

import React, {useState} from 'react';
import { Link } from 'react-router-dom';
import Base from '../core/Base';
import { createaPost } from './helper/userapicalls';
import { isAutheticated } from "../auth/helper/index";

const AddPost = () => {

  
    const { user, token } = isAutheticated();
    const [values, setValues] = useState({
        description:"",
        photo:"",
        loading: false,
        error:"",
        createdPost:"",
        getRedirect:false,
        formData:"",
    });

    const {description, loading, error, createdPost, getRedirect, formData} = values;

    const  onSubmit = (event) => {
        event.preventDefault();
        setValues({...values, error:"", loading:false})
        createaPost(user._id,token,formData).then(data => {
            if (data.error) {
                setValues({...values, error:data.error})
            }else {
                setValues({...values,
                description:"",
                photo:"",
                loading: false,
                createdPost:data.description
                })
            }
        })
    }

    const handleChange = name =>event =>{
        const value = name === "photo" ? event.target.files[0] : event.target.value
        formData.set(name, value)
        setValues({...values, [name]: value})
    }

    const successMessage = () => (
        <div
          className="alert alert-success mt-3"
          style={{ display: createdPost ? "" : "none" }}
        >
          <h4>{createdPost} created successfully</h4>
        </div>
      );

    const createPostForm = () => (
        <form >
          <span>Post photo</span>
          <div className="form-group">
            <label className="btn btn-block btn-success">
              <input
                onChange={handleChange("photo")}
                type="file"
                name="photo"
                accept="image"
                placeholder="choose a file"
              />
            </label>
          </div>
          
          <div className="form-group">
            <textarea
              onChange={handleChange("description")}
              name="photo"
              className="form-control"
              placeholder="Description"
              value={description}
            />
          </div>
   
          <button type="submit" onClick={onSubmit} className="btn btn-outline-success">
            Create Post
          </button>
        </form>
      );
    return (
        <Base title="Add Post" description= "Create a new post" className="container bg-info p-4">
        <Link to="/" className="btn btn-md btn-dark mb-3">
        Home
        </Link>
        <div className="row bg-dark text-white rounded">
        <div className="col-md-8 offset-md-2">
        {successMessage()}
        {createPostForm()}
        
        </div>
        </div>
        </Base>
    )
}

export default AddPost;

//BACKEND

//THIS IS MODEL OF POST

const mongoose = require('mongoose')
const {ObjectId} = mongoose.Schema 

const postSchema = new mongoose.Schema({
    postedBy:{
        type: ObjectId,
        ref:"User"
    },
    photo:{
        data: Buffer,
        contentType: String
    },
    description:{
        type:String,
    },
    likes:[
        {
            username: {
                type:ObjectId,
                ref:"User"
            }
        }
    ],
    comments:[
        {
            username: {
                type: ObjectId,
                ref:"User"
            },

            description:{
                type: String,
                required: true,
            },
            
            date: {
                type: Date,
                default:Date.now
            }
        }
    ],
    date:{
        type:Date,
        default:Date.now
    }
})

module.exports = mongoose.model("Post",postSchema)

//THIS IS CONTROLLER OF POST

const Post = require('../models/post')
const User = require('../models/user')
const Profile = require('../models/profile')
const formidable = require('formidable')
const _ = require('lodash')
const fs = require('fs')

exports.getPostById = (req,res,next,id) => {
    Post.findById(id).exec((err,post) => {
        if (err || !post) {
            return res.status(400).json({
                error:"NO Post found"
            })
        }
        req.post = post
        next()
    })
}

exports.createPost = (req, res) => {

  let form = new formidable.IncomingForm()
  form.keepExtensions = true

  form.parse(req, (err, fields, file) => {
    if (err) {
      return res.status(400).json({
        error:"Failed to upload image"
      })
    }

    //destructure the fields
    const {postedBy, description, likes, comments, date} = fields

    if (!description){
      return res.status(400).json({
        error:"Please include all fields"
      })
    }
    
    req.profile.salt = undefined;
    req.profile.encry_password = undefined;
    req.profile.posts = undefined;
    req.profile.role = undefined;

    let post = new Post({
      postedBy: req.profile,
      description,
      fields
    })

    //handle file here
    if (file.photo){
      if (file.photo.size>10000000000000){
        return res.status(400).json({
          error:"File is too big"
        })
      }
      post.photo.data = fs.readFileSync(file.photo.path)
      post.photo.contentType = file.photo.type
    }

    //save to DB
    post.save((err, post) => {
      if (err) {
        return res.status(400).json({
          error: "Failed to Post"
        })
      }
      res.json(post)
    })
  })
}

exports.getPost = (req, res) => {
  req.post.photo = undefined
  return res.json(req.post)
}
//middleware
exports.photo = (req, res, next) => {

  if(req.post.photo,data) {
    res.set("Content-Type", req.post.photo.contentType)
    return res.send(req.post.photo.data)
  }
  next()

}
exports.myPost = (req, res) => {
  Post.find({postedBy: req.profile})
  .populate("postedBy","_id username")
  .exec((err, myPost) => {
    if (err || !myPost){
      return res.status(400).json({
        error:"No post found"
      })
    }
    res.json(myPost)
  })
}

exports.getAllPosts = (req, res) => {
  Post.find()
  .populate("postedBy","_id username")
  .exec((err, posts) => {
    if(err || !posts){
      return res.status(400).json({
        error:"No Post found"
      })
    }
    res.json(posts)
  })
}

exports.deletePost = (req, res) => {
  let post = req.post
  post.remove((err, post)=>{
    if(err || !post){
      return res.status(400).json({
        error:"Failed to delete post"
      })
    }
    res.json({
      message:"Post deleted",
      post
    })
  })
}

exports.updatePost = (req, res) => {

  const post = req.post;
  post.description = req.body.description;

  post.save((err, updatedPost) => {
    if (err) {
      return res.status(400).json({
        error: "Failed to update post"
      });
    }
    res.json(updatedPost);
  });
}

exports.getLikePost = (req, res) => {

  
}

//WHEN I'm RUNNING THE CODE IN

 POSTMAN IT IS WORKING BUT WHEN I'm DOING IN FRONTEND IT SHOW THE ERROR

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.
