### ISSUE TITLE
Galaxy + Vue + Deploying for Production

### ISSUE THREAD

**Issue by flean** [meteor/meteor#11297]
This is in the console log of the browser
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

How do we set up Vue in production mode when using Galaxy?
I have not figured it out and tutorials don’t explain this with Galaxy.

We are using meteor/akryum:vue-router2 and meteor/akryum:vue

Meteor.isProduction is true
I console logged on Galaxy process.env.NODE_ENV and it is "production"

Any help would be appreciated.

**Comment by filipenevola** [comment]
Hi @flean, I was not able to see this console on my logs.

I just cloned https://github.com/meteor/simple-todos-vue and then `meteor update` so I could be on Meteor 2.0 and use the free deploy.

Then I deployed with `meteor deploy vue.meteorapp.com --free --mongo`

But I don't see any warning like yours in the browser at vue.meteorapp.com

Am I missing any step or information here?

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
