### ISSUE TITLE
Where is migration guide to 2.0?

### ISSUE THREAD

**Issue by gustawdaniel** [meteor/meteor#11299]
Is there any recommended article about differences? 

Anything i found is info about integration with cloud and improvements in HMR

https://docs.meteor.com/changelog.html

```
Breaking changes
http package has been deprecated. Please start on migrating towards the fetch package instead.
```

It is all?

---

Why major release? What happends or changed inside?

**Comment by filipenevola** [comment]
Hi, as we said in this post [here](https://blog.meteor.com/introducing-meteor-cloud-f25ddd3da535) the full announcement for 2.0 is coming next week, this week was reserved for the Cloud Announcement but of course, all the technical changes are explained in the docs.meteor.com/changelog.html linked by you.

You can read about Cloud [here](https://blog.meteor.com/introducing-meteor-cloud-f25ddd3da535)

Also, you can see our always up-to-date roadmap [here](https://github.com/meteor/meteor/blob/devel/Roadmap.md). Then you can have a better idea of plans and next features.

Why 2.0?
In short (more background next week), Meteor had already many big changes and evolutions but we never incremented the major version I don't know why. It was owned by a different company so I can't talk about the past. We are here for the future.

And of course, HMR is a big change in development experience and it's not related to React. React is just one case of HMR. For example, Blaze will have [very soon](https://github.com/meteor/blaze/pull/313) a final version of its HMR as well.

So enjoy 2.0 and there is a lot more to come as you can see in the [roadmap](https://github.com/meteor/meteor/blob/devel/Roadmap.md).

Is it not great to have a great new feature without breaking changes? That was and always will be the idea with Meteor. We are going to improve, accelerate without breaking things that we don't have to break.

We love to avoid breaking changes as we have more than 2,000 companies only on Cloud/Galaxy running real businesses with Meteor. We value our clients a lot and we don't want to break their businesses by requiring major rewrites even when we release major new features. Sometimes this is inevitable but not this time.

Also, make sure you deploy your app for free including MongoDB on Galaxy, this is only possible in 2.0 as well.

**Comment by filipenevola** [comment]
Hi @gustawdaniel, I've updated the changelog to include the migration step https://docs.meteor.com/changelog.html#migrationsteps. Thanks
