### ISSUE TITLE
Add official support for Mac

### ISSUE THREAD

**Issue by cweagans** [meteor/meteor#113]
Not sure if you guys have any Mac users, but node and mongo are very very easy to get running on a mac with Homebrew. I would like to get a Homebrew formula put together that just installs the Meteor framework in some location (without mongo or node), and just use the mongo and node versions provided by Homebrew.

Is this something that you guys would be interested in supporting? I think the main thing that I'd need is instructions on how to install Meteor if Node and Mongo are already installed.

**Comment by colinsf** [comment]
> I whipped up this quintessential Homebrew Meteor Formula. :) If I use it to install Meteor, will Meteor's self-updating feature work?

@mattdipasquale I would tap that. :wink: :beers:
