### ISSUE TITLE
 "error": "ACCESS DENIED" in my postman when I'm running my code in vsCode

### ISSUE THREAD

**Issue by themak01** [meteor/meteor#11302]
//Post Controllers
exports.getAllPosts = (req, res) => {
  Post.find()
  .populate("postedBy","_id username")
  .exec((err, posts) => {
    if(err || !posts){
      return res.status(400).json({
        error:"No Post found"
      })
    }
    res.json(posts)
  })
}

//Auth Controller
exports.isAuthenticated = (req, res, next) => {
  let checker = req.profile && req.auth && req.profile._id == req.auth._id;
  if (!checker) {
    console.log(checker);
    return res.status(403).json({
      error: "ACCESS DENIED",
      
    });
  }
  console.log(checker);
  next();

//Post routes
router.get("/all/posts", isSignedIn, isAuthenticated, getAllPosts)

![Access denied](https://user-images.githubusercontent.com/37306115/105669211-c71ce680-5f04-11eb-9241-2b88ca9760e7.png)

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.
