### ISSUE TITLE
dep is not a function?

### ISSUE THREAD

**Issue by makerhou** [meteor/meteor#11303]
![image](https://user-images.githubusercontent.com/22055477/105677806-4d4a2480-5f27-11eb-8fdf-a876416bbd08.png)

In windows 10 system, when I run "meteor" in powershell, I get an error "TypeError: dep is not a function", what should I do to use meteor

**Comment by diavrank** [comment]
@makerhou have you tried to create an app from C:\ ? It could be for that.

**Comment by filipenevola** [comment]
Hi @makerhou I just installed Meteor con Windows 10 Pro from scratch following the official instructions and it's working fine.

I was able to install, create an app and run it.

Do you have more info to provide?

If so, please comment here so we can re-open the issue.

Make sure you follow the instructions on how to install Meteor on Windows from here https://www.meteor.com/developers/install

**Comment by Aqueuse** [comment]
Hi, I'm facing the same issue, so I have tried your advice (I have moved to my C:// disk and retry) but it's not working. I don't have seen any package.json in my C:// root. I have installed with the x86_64 package and I'm on Windows 10, working with powershell. Ask me if you want more details. I can reproduce step by step if you need.

**Comment by filipenevola** [comment]
Hi @Aqueuse, could you provide a reproduction in a new issue? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)
