### ISSUE TITLE
Email Spoofing Vulnerability with Verification Tokens in Meteor Accounts

### ISSUE THREAD

**Issue by evolross** [meteor/meteor#11306]
Meteor Version: 1.10.2
Operating System: OS X & Galaxy

When using Meteor Accounts with email verification, upon creating a new account with `Accounts.createUser` OR calling the method `Accounts.sendVerificationEmail` after logged in, the actual email verification token is available **in the browser** in the websocket output (e.g. in Chrome in Developer Tools under Network → WS → websocket. Simply search for "verification" under "Messages").

The email verification token can then easily be copied out of the websocket logs and _pasted into_ the standard Meteor Accounts verification URL to the app:

`app.domain.com/#/verify-email/<verification token>`

Thus verifying and spoofing an email account without ever needing to log into the email account.

This was reported to me by a random security researcher. My Meteor app has been getting some traffic and I'm getting a lot of security vulnerability reports. 

Easily reproduced in any standard Meteor install using Meteor Accounts and email verification.

**Comment by evolross** [comment]
UPDATE: On deeper thinking, this _could_ be from my app over publishing fields on the user... looking into it.

**Comment by evolross** [comment]
Yep, over-published the entire `services` field when setting up Facebook login **years** ago. False alarm. My bad.

**Comment by StorytellerCZ** [comment]
Well at least the security issue is now fixed! :tada:
