### ISSUE TITLE
[CLI][publish]/[atmosphere]: documentation won't update

### ISSUE THREAD

**Issue by nathanschwarz** [meteor/meteor#11301]
Hey, there don't know if this is the right place for this.

I noticed that `meteor publish` and `meteor publish --update` isn't working correctly since Meteor Cloud release I believe (not exactly sure about the timing).

the documentation is not updating correctly on atmosphere.
(Btw the "atmosphere" drop down isn't working anymore).

I also opened a thread on the forum : https://forums.meteor.com/t/package-update-documentation-wont-update/55059
the repo I'm talking about : 

https://atmospherejs.com/nschwarz/cluster
https://github.com/nathanschwarz/meteor-cluster/

**Comment by filipenevola** [comment]
Hi @nathanschwarz, this was a bug in the latest Atmosphere, it should be fixed now.
