### ISSUE TITLE
installing meteor: static-meteor.netdna-ssl.com: AccessDenied

### ISSUE THREAD

**Issue by karawitan** [meteor/meteor#11317]
Hello,
 
    currently the installer for meteor fails when invoking the following command:

curl --progress-bar --fail --continue-at - https://static-meteor.netdna-ssl.com/packages-bootstrap/2.0/meteor-bootstrap-os.linux.x86_32.tar.gz --output .meteor-tarball-tmp
```

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F1C94A5B5B816A03</RequestId>
<HostId>
lq5zDSaTT8KFWDAc2XXiqLPZds3EPuD63L6sXTfIWkNdbn3WGsGZPS+3B7Py4fK48aluBQ2hZ7g=
</HostId>
</Error>

```

Please fix :-)

**Comment by karawitan** [comment]
Unfortunatelly, meteor support for 32bits architecture has been dropped since 1.10
https://github.com/meteor/meteor/pull/10933
https://github.com/meteor/meteor-feature-requests/issues/152

**Comment by filipenevola** [comment]
We've updated our install.sh script so it's going to report: "Meteor only supports x86_64 for now." instead of failing to get files that are not available due to architecture.
