### ISSUE TITLE
Unable to remove jquery@=3.0.0 top level dependency, getting build errors when building Wekan

### ISSUE THREAD

**Issue by xet7** [meteor/meteor#11314]
https://github.com/wekan/wekan/issues/3524#issuecomment-773432375

**Comment by filipenevola** [comment]
Hi @xet7 were you building wekan from a checkout in the past?

Meteor versions resolution works in a different way when using a checkout and I believe maybe that is what is causing the jquery top level dependency.

Did you try to run just overriding the packages with @jankapunkt changes in your local packages folder? This way you can test @jankapunkt changes without running from a checkout.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/commit/ea697f2238842893953dee76bed03ffd5b4a107e
