### ISSUE TITLE
Lifting the ban on meteor installation for Iranians

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11310]
Hello, is this link used in installing a meteor a sanction for Iran?

[https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz](https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz)

And because of this, the Iranians are not able to install a meteor.
Is it possible to fix it?

**Isn't this embargo against the open source community?**

**Comment by filipenevola** [comment]
Hi, sorry my ignorance here.

This link is used for many years and we didn't change anything.

What is going on with this link for Iran? I'm not aware. Could you link some news or more info about this?

Again, sorry my ignorance.

**Comment by Saeeed-B** [comment]
@filipenevola 
Exactly gives error 403.
That is, when the ip is Iran, the installation will not be done and the package will not be downloaded at all.
But as soon as the ip changes to another country, the installation is done.
Unfortunately, this has discouraged Iranian society from meteors

**Comment by Saeeed-B** [comment]
Nothing is available on the news of the embargo.
And this issue is the first, most explicit and official, question of the Iranian society about meteor.

**Comment by filipenevola** [comment]
Hi @Saeeed-B, I don't know anything about bans and we don't want to prevent any one from using Meteor, quite the opposite, we want more Meteor users from everywhere.

Is AWS S3 also causing issues for you?

If not, could you replace the beginning of the URL to this `https://s3.amazonaws.com/com.meteor.static/` in our install script to test and see if it works ok?

We need the CDN to serve our files faster and avoid connections problems as well. I'll contact our CDN provider to understand better the issue with Iran that you are reporting here.

**Comment by filipenevola** [comment]
Hi, I just contact our CDN provider and they said they don't have any bans to Iran as far as they can tell now. They are going to check in details and get back to me later. I'll update here as soon as I have more information.

They also want to know about your test using S3 URL directly. Please give me feedback on that asap.

**Comment by Saeeed-B** [comment]
@filipenevola Thank you very much for following up.


**Fortunately, Amazon's service has no limits so far. **
I tested with this variable : 
```
TARBALL_URL="https://s3.amazonaws.com/com.meteor.static/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
```

![image](https://user-images.githubusercontent.com/36485982/106558519-239d8880-6539-11eb-8c8a-bb28169e5393.png)



**But the netdna-ssl.com service, as I said before, is a sanction and cannot be used with Iran's ip.
As I documented:**
```
TARBALL_URL="https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
```

![image](https://user-images.githubusercontent.com/36485982/106555165-44161480-6532-11eb-8075-c4899950c5ab.png)

**Comment by jankapunkt** [comment]
@Saeeed-B you can actually download the install script by directly going to install.meteor.com, copying all the script code and save it in a file `install.sh` and replace all `curl` with `curl --verbose` and then run locally via `sh ./install.sh`

The verbose mode should give you much more detailed output about the failed requests.

**Comment by Saeeed-B** [comment]
@filipenevola @jankapunkt  Yes, the sanctioned domain is clear,
  There just has to be a serious will in the meteor to fix this problem.

Note, installing meteor is easy for me (despite the embargo), but I do not want this embargo for Iranian users and they have a bad mentality of meteor.

**Comment by filipenevola** [comment]
Our CDN provider didn't get back to me yet.

**Comment by Saeeed-B** [comment]
@filipenevola Hello again
This is just very urgent because we are starting metero training in Persian. And this situation does not get good feedback.
In short, we do not want to teach about circumventing sanctions.
  Without these drawbacks, the meteor will be more welcomed.
Thanks for following up.
This problem has also been reported again: 
[https://github.com/meteor/meteor/issues/11317](https://github.com/meteor/meteor/issues/11317)

**Comment by karawitan** [comment]
The issue reported in #11317 is due to the fact that I tried installing meteor on a 32bits host, for which support has been dropped since 1.10

**Comment by filipenevola** [comment]
Yes @karawitan, you are right.

@Saeeed-B what is the exact URL that you are getting the error?

**Comment by Saeeed-B** [comment]
@filipenevola I thought I explained the whole thing,
I have given a very practical example of the two links above.

This is exactly what we are facing, certainly error 443 which means no access (sanctions)
![image](https://user-images.githubusercontent.com/36485982/108173693-b0d50580-7113-11eb-9d91-ff89c4508ef6.png)


I said before that as soon as the ip is changed to a country other than Iran, this error will be fixed and the installation will be complete.
And this is a sign of sanctions.

**Our training has been waiting for several weeks to solve this problem!**

**Comment by filipenevola** [comment]
As explained here #11317 we don't support 32 bits platforms. This is the issue.

Look to the end of your URL in the print above: `..._32.tar.gz`. This file does not exist for Meteor 2.0.

<img width="1372" alt="S3 Management Console 2021-02-17 07-11-50" src="https://user-images.githubusercontent.com/437372/108196427-7bb6bc00-70ef-11eb-8894-19814eafa462.png">

Read why [here](https://github.com/meteor/meteor-feature-requests/issues/152)

**Comment by filipenevola** [comment]
We've updated our install.sh script so it's going to report: "Meteor only supports x86_64 for now." instead of failing to get files that are not available due to architecture.

**Comment by Saeeed-B** [comment]
My problem is really different from the answer you give.
**My system RAM is 4 GB and I use 64-bit Kali Linux.**
I did this tite for you again right now !!

![image](https://user-images.githubusercontent.com/36485982/108230899-78a2e680-7156-11eb-88ee-42479551f001.png)

**Comment by Saeeed-B** [comment]
@filipenevola The problem is not the lack of a 32-bit version, because this error is fixed right after the ip change and the installation is complete.

**Comment by Saeeed-B** [comment]
@filipenevola On the other hand, when I use the Amazon URL, I do not encounter these errors at all, as I previously sent the test results of both URLs.
Please follow

> @filipenevola Thank you very much for following up.
> 
> **Fortunately, Amazon's service has no limits so far. **
> I tested with this variable :
> 
> ```
> TARBALL_URL="https://s3.amazonaws.com/com.meteor.static/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
> ```
> 
> ![image](https://user-images.githubusercontent.com/36485982/106558519-239d8880-6539-11eb-8c8a-bb28169e5393.png)
> 
> **But the netdna-ssl.com service, as I said before, is a sanction and cannot be used with Iran's ip. As I documented:**
> 
> ```
> TARBALL_URL="https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
> ```
> 
> ![image](https://user-images.githubusercontent.com/36485982/106555165-44161480-6532-11eb-8075-c4899950c5ab.png)

**Comment by filipenevola** [comment]
Hi @Saeeed-B the only full URL provided by you was this one in the screenshot here https://github.com/meteor/meteor/issues/11310#issuecomment-780380126 

In this screenshot you are trying to install Meteor in a 32 bits architecture, this is not going to work.

All the other replies, comments, you don't show the full URL, only the TARBALL_URL variable in our script.

Our provider said they don't have any bans and then we don't have much to do here as the evidence shows that you were trying to install a version that doesn't exist.

**Comment by Saeeed-B** [comment]
@filipenevola 
Let's leave aside the variable I showed,
I said I have a 64-bit system, but I can not install. I do not care what version the script is trying to get, the question is, why I can not install with 64-bit operating system and 4 GB of RAM.
And why do I just have to change the ip to be able to install?

**Comment by Saeeed-B** [comment]
@filipenevola 
I am ready to resend any information you want, any test.
Or review again.
**Sincerely and honestly  , Saeed**

**Comment by Saeeed-B** [comment]
@filipenevola I recorded a video and it showed exactly that the installation is difficult only for ip Iran, and in this video, as soon as I turn on my VPN and my ip changes to Canada, the download starts and there is another problem. does not have.
Download only fails when my ip is Iran. I showed exactly, please watch the video.

video link : 


[https://drive.google.com/file/d/1nnhpW7kv3ZVNm5R1VKrCNcd0sSaofEuc/view?usp=sharing](https://drive.google.com/file/d/1nnhpW7kv3ZVNm5R1VKrCNcd0sSaofEuc/view?usp=sharing
)

**Comment by Saeeed-B** [comment]
@filipenevola I hope I was able to show exactly the problem by making this video.
Sincerely, Saeed

**Comment by Saeeed-B** [comment]
@filipenevola I showed in this video that although I have a 64-bit system, but the installation is not done, and I also showed that when the ip is changed to a country other than Iran, the download is done.

**Comment by Saeeed-B** [comment]
@filipenevola
Have you seen the video?
