### ISSUE TITLE
dynamic import failed on 1.9.3 with "Cannot destructure property 'dynamicRoot' of 'dynamicImportInfo[platform]' as it is undefined."

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#11325]
meteor runs with develop mode

> "Cannot destructure property 'dynamicRoot' of 'dynamicImportInfo[platform]' as it is undefined."

```
meteor 1.9.3
dynamic-import@0.5.5
```

```
async importLocales() {
  console.log(await import(`/imports/locales/en.json`))
}
```

![image](https://user-images.githubusercontent.com/1147704/108582515-d90c7080-736e-11eb-8714-d27e6d390c40.png)

![image](https://user-images.githubusercontent.com/1147704/108583809-3e645f80-7377-11eb-81c3-89e3282ad134.png)

https://github.com/meteor/meteor/blob/46e00a875726dff078c59eaf7fdc7b956cf0a996/packages/dynamic-import/server.js#L170

this reproduction repo based on meteor 1.9.3
https://github.com/crapthings/meteor-11325

this is working one with same code based on meteor 2.0
https://github.com/crapthings/dynamic-import-meteor

**Comment by filipenevola** [comment]
Hi @crapthings do you need this to be fixed on 1.9.3? What is preventing you to upgrade Meteor to latest?

**Comment by crapthings** [comment]
yes for some reason, we can't upgrade to 2.0 because some cordova plugin won't build with cordova 10

**Comment by filipenevola** [comment]
Hi @crapthings, Meteor 2.0 is not using Cordova 10. Could you give it a try?

**Comment by crapthings** [comment]
testing with 2.1, close for now
