### ISSUE TITLE
HMR fails working with some specific react packages and lazy loaded components

### ISSUE THREAD

**Issue by micnic** [meteor/meteor#11335]
Hi, when using HMR I get errors at different levels in an app that I am working on. I could narrow it down to a simpler structure like the following:

App.tsx:
```
import React, { lazy, Suspense } from 'react';

const VeryLazyComponent = lazy(() => import('./VeryLazyComponent'));

export default function App() {
  return (
    <div id="app">
      App
      <Suspense fallback={<div>Loading...</div>}>
        <VeryLazyComponent />
      </Suspense>
    </div>
  );
}
```

VeryLazyComponent.tsx:
```
import React from 'react';
import { AutoSizer } from 'react-virtualized';

console.log(AutoSizer); // After commenting this line multiple errors are thrown in the console

export default function VeryLazyComponent() {
  return <div id="very-lazy-component">Very lazy component</div>
}
```

It seems that adding or removing `react-virtualized` in a lazy component (sometimes it fails with usual import) breaks the process of HMR with the following errors:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1449826/109640172-c9540f80-7b58-11eb-828f-49c1d835537e.png">

**Comment by zodern** [comment]
I tried adding the code to a Meteor app and wasn't able to reproduce the error. Could you please create a [reproduction](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor) I can try?

**Comment by micnic** [comment]
I could not reproduce this with a new Meteor app, but it happens in an app that I try to migrate from Meteor 1.9 to Meteor 2.0. Will try to reproduce again with the newest Meteor version and come back with a more narrowed issue.

**Comment by micnic** [comment]
I could track the source of the error in the app in some packages that are importing `import window from 'global/window'` and it throws in `react-fast-refresh.js:827`:

```js
      case 'object':
        {
          if (type != null) {
            switch (type.$$typeof) { // !HERE "type" is a global window value
              case REACT_FORWARD_REF_TYPE:
              case REACT_MEMO_TYPE:
                // Definitely React components.
                return true;

              default:
                return false;
            }
          }
```

Still could not reproduce in a new Meteor app.

**Comment by filipenevola** [comment]
As we still don't have a reproduction in latest Meteor apps I'm closing this issue.

**Comment by zodern** [comment]
I was able to reproduce, and this will be fixed in my next PR.
