### ISSUE TITLE
Lifting the ban on meteor installation for Iranians

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11330]
@filipenevola I recorded a video and it showed exactly that the installation is difficult only for ip Iran, and in this video, as soon as I turn on my VPN and my ip changes to Canada, the download starts and there is another problem. does not have.
Download only fails when my ip is Iran. I showed exactly, please watch the video.
I hope I was able to show exactly the problem by making this video.
**I showed in this video that although I have a 64-bit system, but the installation is not done, and I also showed that when the ip is changed to a country other than Iran, the download is done.**

video link :
[https://drive.google.com/file/d/1nnhpW7kv3ZVNm5R1VKrCNcd0sSaofEuc/view?usp=sharing](https://drive.google.com/file/d/1nnhpW7kv3ZVNm5R1VKrCNcd0sSaofEuc/view?usp=sharing)

**Comment by filipenevola** [comment]
Hi @Saeeed-B, could you try now?

We are temporarily downloading it directly from S3.

**Comment by Saeeed-B** [comment]
@filipenevola 
Hello, thank you very much
Yes, the S3 Amazon service answers perfectly.
But I only tested on Linux.
Is there a problem with installing on Windows?

**Comment by filipenevola** [comment]
No, it should work fine.

Use the new installer for Windows: https://github.com/meteor/meteor/blob/devel/npm-packages/meteor-installer/README.md
