### ISSUE TITLE
METEOR@2.1 memory

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#11331]
release/METEOR@2.1 still seems to have some memory issues
(I'm going to downgrade to METEOR@2.0 now)

<img width="188" alt="Screenshot 2021-02-24 at 22 50 43" src="https://user-images.githubusercontent.com/635729/109070624-02245c80-76f3-11eb-9ccf-e882116ccf93.png">

**Comment by jorisroling** [comment]
This seemed to be a initial memory ramp, this is the picture after a day. Don't know why, but it seems OK now.
METEOR@2.1 seems to be fine!

<img width="468" alt="Screenshot 2021-02-25 at 14 42 21" src="https://user-images.githubusercontent.com/635729/109161828-ced7e100-7777-11eb-890a-0f97d22d496e.png">

**Comment by filipenevola** [comment]
Meteor 2.1 is just a Node.js update and they said it is a security update so I wouldn't expect memory problems.

I'm going to close this for now as you also believe it was not a problem but let me know if this comes back.
