### ISSUE TITLE
HMR doesn't work with CDN React

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#11339]
#### reproduction

https://github.com/crapthings/meteor-hmr-11339

> change component console.log

hot-module-replacement.js?hash=22d8cfbe1ca1509fc13b6f268883287a7c6b3b6c:564 HMR: updated 1 file

but screen doesn't rerender

![image](https://user-images.githubusercontent.com/1147704/110734816-8d5d3080-8263-11eb-8429-f61e44e7a4ba.png)

**Comment by tjramage** [comment]
@crapthings — have you tried manually adding `react-fast-refresh` to your Meteor packages? Might not work, but worth a shot.

**Comment by crapthings** [comment]
https://github.com/crapthings/meteor-hmr-11339/blob/main/.meteor/packages#L22

yes this repo has react-fast-refresh already

**Comment by filipenevola** [comment]
Hi @crapthings why are you using React from a CDN?

**Comment by crapthings** [comment]
hello @filipenevola 

due to https://github.com/meteor/meteor/issues/10712

we move node_modules like @material-ui/core and old material-ui to <head>
so react have to load first

**Comment by zodern** [comment]
react-dom needs to be loaded after react-refresh for it to work. You try moving the files loaded from the CDN into your app, or into a local package. They can still be used as globals to avoid the overhead of `module.link`, but this way they will be loaded after the `react-fast-refresh` package.

I'm curious how much https://github.com/benjamn/reify/pull/246 helps with the module.link performance. If you want to try it in your app, you can clone https://github.com/zodern/meteor-modules-reify-fork into your app's `packages` folder. If it isn't fast enough, you can try changing the [reify version](https://github.com/zodern/meteor-modules-reify-fork/blob/master/package.js#L9) to ` git+https://github.com/zodern/reify.git#c4b2a93ce900327613d08270ef9e9f52eebd796e`, which is an older commit that was faster in some situations but might not handle some edge cases correctly.
