### ISSUE TITLE
NPM windows only installer does not do the trick

### ISSUE THREAD

**Issue by silkentrance** [meteor/meteor#11349]
Why? Again, why? Windows only NPM installer?

Why don't you make this an `@meteor` organization over at npm and then have installers that work right out of the box with both windows and linux / macos?

E.g. `npm install -g @meteor/linux`.

That way, one can integrate this into for example `nvm` and similar solutions that exist for the windows platform, e.g. `nvm-windows`.

And if you want to publish top level npm packages, why not call them by their name, e.g.

`meteor-windows`
`meteor-linux`
`meteor-macos`

What are your thoughts about this?

For my part, the current situation is so that meteor becomes unusable for me, especially when switching between different node version and possibly also different meteor versions during development under linux.

**Comment by filipenevola** [comment]
Hi, the current npm installer is going to be for all platforms.

We focused on Windows first because the Unix installer is working really well but the Windows wasn't.

It is just a matter of prioritization.

**Comment by silkentrance** [comment]
Ok, can't wait until the "new current" installer becomes available on npm.

**Comment by silkentrance** [comment]
Not to mention that making the special case, here: windows, the standard is a very bad approach, in every aspect.
