### ISSUE TITLE
App does not load because `process.version.slice` is not defined

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#11345]
Since today, [my app](https://app.marblear.com) does not load correctly on Google Chrome on macOS. In the console, I see this error:

![image](https://user-images.githubusercontent.com/3984535/111148156-96b00b00-858b-11eb-9b9e-0ebe9eb1b5a8.png)

and this leads to an error in the `_stream_writable.js" module:

![image](https://user-images.githubusercontent.com/3984535/111148192-a16aa000-858b-11eb-9a38-d0bc9733525f.png)

Any idea what might cause this?

Sometimes, the app loads if I reload the page. But not on the first attempt. Only Chrome (macOS) is affected, Firefox and Safari show the page without this error message.

Meteor version is 1.10.2

**Comment by ecwyne** [comment]
I'm getting the same this morning after updating Chrome to `Version 89.0.4389.82 (Official Build) (arm64)`

**Comment by ecwyne** [comment]
I'm able to load my app in incognito  and @derwaldgeist it looks like yours begins to load for me in incognito but then crashes somehow

**Comment by derwaldgeist** [comment]
Thanks for the info. For me, it works in incognito somehow.

**Comment by ecwyne** [comment]
`process.browser` returns `true` in incognito but returns `undefined` in my normal browser window.

**Comment by ecwyne** [comment]
@derwaldgeist disabling the `Apollo Client Devtools` extension cleared up the issue for me

**Comment by ecwyne** [comment]
https://github.com/apollographql/apollo-client-devtools/issues/455

https://github.com/apollographql/apollo-client-devtools/issues/457

**Comment by derwaldgeist** [comment]
Yes, I was already suspecting that. I disabled all my plugins, including the Apollo client dev tools. And yes, YouTube was affected, too. So I guess this is actually a side-effect of this plugin. Closing this for now.

**Comment by csellis** [comment]
> @derwaldgeist disabling the `Apollo Client Devtools` extension cleared up the issue for me

This worked for me
