### ISSUE TITLE
check package does not respect Match.Maybe when validating fields as object properties

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#11342]
Meteor Version: 2.1
OS: Ubuntu 20.04

I am validating properties of an Object using check/Match and it actually throws although the properties are defined as optional using `Match.Maybe`.

**Actual Behavior:**

```javascript
function validatePartial (obj) {
  const { foo, bar } = obj
  check({ foo, bar }, {
    foo: Match.Maybe(Function),
    bar: Match.Maybe(Function),
  })
})

validatePartial({}) // throws Match error: Expected function, got undefined in field schema
```

**Expected Behaviour:**

no error should be thrown, because `foo` (and `bar`) is optional

**Reproduction:**

Create a new Meteor project and place the above code in `server/main.js` and see the error

**Sidenote:**
I could use SimpleSchema but I am writing package code that should not be dependent on it.
I could also use

```javascript
check(obj.foo, Match.Maybe(Function))
```
but that would not allow me anymore to see (and communicate to the user) which field of the object is actually causing a validation error.

**Comment by filipenevola** [comment]
Hi @jankapunkt I was analyzing the code and it seems to be intentional.

There is even a test for this case with comments on top, see:

https://github.com/meteor/meteor/blob/01bf44adffbb65e847e14c7158c57683afefff37/packages/check/match_test.js#L150-L155

I tend to agree with you but I don't know why people thought otherwise in the past.

What do you think?

**Comment by jankapunkt** [comment]
Interesting situation. I am not sure for what to vote. On the one hand this package is so old that changes may have implications down to any Meteor version out there. On the other hand I really think this current logic is just false, because Match.Maybe should always accept undefined or null, no matter which context.

**Comment by filipenevola** [comment]
@jankapunkt maybe one alternative is to create a new `Match`, for example, `Match.OptionalProperty`?

What do you think?

**Comment by jankapunkt** [comment]
May be a good alternative. I will Check out Match.Optional as well when I am back at home. If this does not work either I could go for a PR for optionalProperty.

**Comment by jankapunkt** [comment]
@filipenevola  I thought I could solve it unising `Match.ObjectIncluding`, which nicely works out for fixed Objects:

```javascript
const obj = {}
check(obj, Match.ObjectIncluding({
  foo: Match.Maybe(Function),
  bar: Match.Maybe(Function),
})) // works
```
but it also won't work for destructured parameters:


```javascript
const { foo, bar } = obj
check({foo , bar}, Match.ObjectIncluding({
  foo: Match.Maybe(Function),
  bar: Match.Maybe(Function),
}))
```

**Comment by StorytellerCZ** [comment]
@jankapunkt Is this resolved for you, or do you want to make this work with for destructured parameters?

**Comment by StorytellerCZ** [comment]
Workaround available, closing.
