### ISSUE TITLE
Production build uses code cached in dev mode

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11357]
I ran into a problem where our production build was crashing due to including code that was compiled in dev mode on the latest Meteor `2.1`.

The project was using `zodern:melte` to compile Svelte components.

Svelte has a different runtime in dev mode to enable warnings etc., those warnings shouldn't exist in production builds.

If I run the app in dev mode, then switch to a production build, I still get those warnings. Until I execute a `meteor reset` to wipe clear any caches.

I created a reproduction that helps demonstrate the issue and recorded a video of the flow.

https://github.com/arggh/meteor-caching-issue

https://user-images.githubusercontent.com/17210302/112438578-bd6efe00-8d50-11eb-8ba2-18d3a38e1929.mp4

### Expected behavior

I'd expect Meteor to not re-use bits of code for production builds that were compiled, transpiled & cached in dev mode.

### Actual behavior

Meteor re-uses the dev mode bits of code in production builds.

### The operating system you're running Meteor on

Mac OS Big Sur 11.2.3 (M1)

**Comment by zodern** [comment]
I published version 1.3.1 of `zodern:melte` to fix this. Many build plugins are able to safely reuse their cache entries between development and production builds, so Meteor lets the build plugin decide how to handle this.

**Comment by arggh** [comment]
Thank you @zodern 💯 

Any chance you could push the changes to the repo? I'd like to study & learn about the changes you made regarding cache re-use :)

**Comment by zodern** [comment]
Here is the commit: https://github.com/zodern/melte/commit/2b691f621fffc3b17e287759c6a01b44ed5e971c
