### ISSUE TITLE
adding package does not work with typescript

### ISSUE THREAD

**Issue by Kelvijn** [meteor/meteor#11358]
When I try to add different meteor packages via 

meteor add quave:collections

I cannot import this and neither can I find the package in my external libs:

import { createCollection } from 'meteor/quave:collections';

This is on Meteor 2.1 with the typescript and react option.
I tried on javascript an react and this works as expected.

**Comment by afrokick** [comment]
You should manually add package definition to your index.d.ts like

declare module “meteor/somepackage” { ...

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
