### ISSUE TITLE
Slow startup when importing mathjs package

### ISSUE THREAD

**Issue by bhunjadi** [meteor/meteor#11359]
Importing [mathjs](https://github.com/josdejong/mathjs) library on Meteor 2.1 takes more than 1 second causing slow startup. This is especially noticeable client-side if user opens a new tab and then has to wait. Expected time to import is around 200ms which we get in nodejs.

Time to import and Meteor version table:
| Meteor version | Time to import |
| ----------------- | ---------------- |
| 1.8 | 320ms |
| 1.8.1 | 320ms |
| 1.8.2 | 1000ms |
| 2.1 | 1000ms |

It appears that 1.8.1 -> 1.8.2 increased significantly import time of this package.

I'm running Ubuntu 20.04 on WSL2. Host is Windows 10 Pro 20H2 (build 19042.867).

**Expected behavior**
Import should take roughly the same amount of time as in pure NodeJS, which is around 200ms on my machine.

**Actual behavior**
Import takes a lot longer than expected.

**Reproduction**
[Meteor example](https://github.com/bhunjadi/mathjs-meteor/tree/master)
1000ms for import

Run `meteor` and open https://localhost:3000. Open the console and try refreshing a few times.
You'll see two logs:
APP <timestamp_1>
main.js <timestamp_2>

Deduct timestamps and you'll get duration in milliseconds which took to load `mathjs` package.

[Pure React example](https://github.com/bhunjadi/mathjs-pure-react)
around 200ms for import

Run `npm start` and open https://localhost:3000. Open the console and try refreshing a few times.
You'll see the logs same as in Meteor example.

Notes:
- I used the same Node version for React example
- Tried production build for Meteor, too. It didn't improve things

Node example (no React or any other dependency):
```
const START = Date.now();
const math = require('mathjs');
const END = Date.now()
console.log(END - START); // around 200ms
```

**Comment by zodern** [comment]
This has the same cause as #10712. Meteor's module system has a lot of overhead when importing large npm dependencies that are ecmascript modules. I am going to close this since it is being tracked in that issue.
