### ISSUE TITLE
Error when processing DDP message results for Meteor method calls that are in-flight (sent but not received) at the exact moment DDP reconnects - causing immediate log out

### ISSUE THREAD

**Issue by dkoo761** [meteor/meteor#11355]
**UPDATE: I've just updated this ticket to reflect the fact that I now understand how DDP's reconnection logic works, in particular the _callOnReconnectAndSendAppropriateOutstandingMethods() function.**

I've noticed recently that some Meteor method calls don't complete successfully.

Checking the browser console shows this error:

- `Methods should only receive results once`

After some troubleshooting, it appears that the ddp-client.js file generated by Meteor (via Babel?) contains an incorrect transpiling of `Array.prototype.find` in the `_livedata_result` function:

The original source code:

```
    const currentMethodBlock = self._outstandingMethodBlocks[0].methods;
    let i;
    const m = currentMethodBlock.find((method, idx) => {
      const found = method.methodId === msg.id;
      if (found) i = idx;
      return found;
    });
```

The generated code (difference explained below):

```
    var currentMethodBlock = self._outstandingMethodBlocks[0].methods;
    var m;

    for (var i = 0; i < currentMethodBlock.length; i++) {
      m = currentMethodBlock[i];
      if (m.methodId === msg.id) break;
    }
```

Looking at the logic for a DDP reconnect, I see that if there are Meteor method calls that have been sent JUST before the connection was established and have not received a response yet from the server, then those calls are dropped after the DDP connection has been made - and they are usually retried again after login. In that case, the currentMethodBlock will be missing the method invoker for the corresponding DDP result message (because the method invokers for in-flight method calls get moved to a different block behind the login method call). When this happens....

In the original code, if no method invoker is found in the `find()` function then:
- m === undefined
- i === undefined

In the generated code, if no method invoker is found in the `for` loop then:
- m === the last method invoker in the currentMethodBlock array
- i === (currentMethodBlock.length - 1)

As you can see with the generated code, it's possible for the same (last) method invoker to be used for multiple DDP message responses, which is exactly what's happening in my app when I send a bunch of method calls at the same time. In that case I see the `Methods should only receive results once` error on all of the method results that were in-flight at the time of DDP reconnection and their method results are never returned to the client caller. Right after this, the user is immediately logged out.

Meteor version: 1.11.1
OS: OS X 10.15.7

**Comment by StorytellerCZ** [comment]
@dkoo761 Could you please test the issue on latest Meteor and if it still persist on Meteor 2.3-beta.5? Recently minifiers have been updated.

**Comment by dkoo761** [comment]
@StorytellerCZ I didn't test my project since it's running on an older version of Meteor and I already implemented a workaround but instead I generated a new vanilla project to check the minified code in ddp-client.js in Meteor 2.3-beta.5 and it looks correct now. Should be fine to close this ticket.

**Comment by StorytellerCZ** [comment]
Glad to hear that! Thanks a lot for the check-up!
