### ISSUE TITLE
HMR code causes errors instead of gracefully disabling itself on IE11 regardless of whether hmr is added as a package or not

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11353]
Trying to test an application with the HMR package added in IE11 makes it crash on browser first load because the package contains code that is incompatible with IE:

![image](https://user-images.githubusercontent.com/2690254/111907995-cceffd80-8a57-11eb-8dbc-82f5060c8680.png)

I could not find a workaround, unfortunately, since removing the hot-module-reload package from the app was not enough - react-fast-refresh is always loaded as a dependency of the ecmascript package.

**Comment by perbergland** [comment]
![image](https://user-images.githubusercontent.com/2690254/111908131-56073480-8a58-11eb-94e7-9dc9a103c07c.png)

![image](https://user-images.githubusercontent.com/2690254/111908144-63242380-8a58-11eb-9e00-bf0c0eba3d2a.png)

**Comment by perbergland** [comment]
Maybe it could be fixed as easily as just supplying an empty legacy.js file in the hot-module-replacement package and adding 

```
api.addFiles([
    './legacy.js'
  ], 'legacy');
```

to its package.js?

**Comment by perbergland** [comment]
I mislabeled the severity on this one - it will only cause errors in the javascript console and prevent the two packages from loading

**Comment by zodern** [comment]
This is fixed in Meteor 2.5
