### ISSUE TITLE
util package use of sharedArrayBuffer() requires Cross-Origin-Embedder-Policy, Cross-Origin-Opener-Policy settings

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#11363]
I noticed this deprecation warning popping up in my client:

```
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021.
See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
```

Essentially, I am getting this because I am using the [`util`](https://www.npmjs.com/package/util) package which uses `sharedArrayBuffer()`

To manage this I need to adjust 2 policies, as described in the referenced [article](https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation):
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

Looking through the [`browser-policy`](https://github.com/meteor/meteor/tree/devel/packages/browser-policy) package I do not see a way to do this?  Maybe I am missing something?  Or am I expected to add my own headers for a case like this?

I am thinking the `util` package is pretty commonly used (**26M** weekly downloads) so this may be something Meteor should support.  There may be a number of meteor sites that are affected by this.

**Comment by brucejo75** [comment]
I tried to add the policy myself:
```javascript
WebApp.connectHandlers.use(function(req, res, next) {
  // add headers
  res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
});
```

But the website fails to download, making me think this is not the right way to add header information?

@filipenevola, this may be an urgent issue because as soon as Chrome 91 releases any user of `util` will need to address this.

**Comment by StorytellerCZ** [comment]
@brucejo75 Can you try with `WebApp.rawConnectHandlers` instead of `WebApp.connectHandlers` ?

**Comment by brucejo75** [comment]
@StorytellerCZ, thanks for following up!

It turns out that my original code works fine.  Also, you will note that I forgot to include a `next()` call which hung my application.  I am editing my original comment so that others won't hang on this...

This is a perfectly workable solution for the `SharedArrayBuffer` issue.
Closing.

**Comment by StorytellerCZ** [comment]
Glad to hear that you found a solution! Thanks for sharing!
