### ISSUE TITLE
"meteor npm clean-install" leaves broken symlinks behind

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [meteor/meteor#11361]
Axioms:
  1. meteor 2.0 uses npm 6.14.8
  2. npm 6.14.8 uses libcipm 4.0.8 with rimraf 2.7.1 to execute `npm clean-install`
  3. rimraf 2.7.1 uses glob 7.1.3
  4. [glob 7.1.3 does not include files or folders starting with a `.` (dot) when given a `*` pattern](https://github.com/isaacs/node-glob/tree/v7.1.3#dots)
  5. libcipm 4.0.8 cleans the `node_modules` directory using [`rimraf(path.join(this.prefix, 'node_modules/*'))`](https://github.com/npm/libcipm/blob/ef52f1e8ef5fd1b14de7b8b4938f45ef9e14f4e1/index.js#L140)
  6. The `node_mobules/.bin` directory contains symlinks that potentially break if some packages are removed.
  7. `npm clean-install` potentially removes packages.

Lemmas:
  8. Follows from 3 and 4: rimraf 2.7.1 does not delete files or folders starting with a `.` (dot) when given a `*` glob (see also https://github.com/isaacs/rimraf/issues/167#issuecomment-371288470).
  9. Follows from 1, 2, 5 and 8: With meteor 2.0, `meteor npm clean-install` does not remove the `node_mobules/.bin` directory.

Theorem:
  With meteor 2.0, `meteor npm clean-install` potentially breaks symlinks in  `node_mobules/.bin` without removing them.

Proof: Follows from 6, 7, and 9.

NB: this is fixed with npm 7.x. Do we have *meteor 2.1 uses npm 6.14.8* too?

**Comment by StorytellerCZ** [comment]
This should be fixed in Meteor 2.3+
Please comment if you encounter it again.
