### ISSUE TITLE
accounts-google: The http package has been deprecated

### ISSUE THREAD

**Issue by dfrankes** [meteor/meteor#11360]
Meteor Version: METEOR@2.1

accounts-google@1.3.3
accounts-oauth@1.2.0
accounts-password@1.7.0
service-configuration@1.0.11

As soon as your login with google it gives the following warnings in the server console (3 times)

```
D20210326-13:56:40.337(1) (http.js:169) The http package has been deprecated, please migrate to the fetch package and new web standards.
D20210326-13:56:40.415(1) (http.js:169) The http package has been deprecated, please migrate to the fetch package and new web standards.
D20210326-13:56:40.483(1) (http.js:169) The http package has been deprecated, please migrate to the fetch package and new web standards.
```

Followed https://docs.meteor.com/api/accounts.html#Meteor-loginWith%3CExternalService%3E to install this package

```bash
meteor update accounts-google accounts-oauth accounts-password service-configuration
> The specified packages are at their latest compatible versions.
```

(This is a new meteor project)

**Comment by filipenevola** [comment]
Yes, we have a few PRs in progress to solve these warnings: 

https://github.com/meteor/meteor/pull/11305

https://github.com/meteor/meteor/pull/11313

**Comment by StorytellerCZ** [comment]
The console warnings should no longer appear. More complete solution still in works.
