### ISSUE TITLE
When user logs out Meteor.user() becomes undefined while Meteor.userId() is still a string

### ISSUE THREAD

**Issue by ksinas** [meteor/meteor#11379]
During logout **sometimes** user becomes undefined while userId holds the previous value
Occurs on versions 2.1.1 and 1.11.1 on Chrome browser

### Reproduction

Register autorun on the client
```js
Tracker.autorun(() => {
  console.log(Meteor.user(), Meteor.userId());
});
```
Open the console and do the following several times
```js
// 1
Meteor.loginWithPassword({ username: 'user'}, 'password')
// 2
Meteor.logout()
```

Expected behaviour
```
// console output
someUserId, { _id: 'someUserId... }
null, null
```
Actual behaviour
```
// console output
someUserId, { _id: 'someUserId... }
someUserId, undefined
null, null
```

My guess would be that `Meteor.defer()` is not working correctly on chrome browser. I had issues related to that here
https://github.com/meteor/react-packages/issues/324#issuecomment-789137233

**Comment by afrokick** [comment]
AFAIK the logging out process is async operation. You can call Meteor.loggingOut() function to get a current state.

So, if you'll log it, it should be like:

```
// console output
someUserId, { _id: 'someUserId... }
someUserId, undefined, true <--- Meteor.loggingOut()
null, null, false
```

**Comment by ksinas** [comment]
My point is that behaviour was inconsistent between browsers. However, I can't reproduce the issue on chrome 90. I guess the issue can be closed
