### ISSUE TITLE
Cannot Import From server-side Module `client`

### ISSUE THREAD

**Issue by 67726e** [meteor/meteor#11378]
One cannot import from a server-side directory named `client`, this will cause a crash of the application.

### Reproduction

```
// server/main.js
import { foo } from './client/';

// server/client/index.js
export const foo = () => {};
```

### Environment

```
Version: Meteor 2.0
OS: Linux Mint 20 / x86_64
```

### Expected

One would expect to have imported a function `foo`.

### Result

```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
/home/USER/.meteor/packages/meteor-tool/.2.0.0.1s23swf.tzje++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Cannot find module './client/'
    at makeMissingError (packages/modules-runtime.js:222:12)
    at Module.resolve (packages/modules-runtime.js:228:17)
    at Module.moduleLink [as link] (/home/USER/.meteor/packages/modules/.0.16.0.16gel8o.edwa++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:45:25)
    at module (server/main.js:1:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/app/app.js:4176:15
    at /home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/boot.js:226:21
    at /home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/boot.js:464:7
    at Function.run (/home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/profile.js:280:14)
    at /home/USER/Documents/APPLICATION-application/meteor/.meteor/local/build/programs/server/boot.js:463:13
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by filipenevola** [comment]
Hi @67726e, are you using Meteor package.json config to inform your mainModules?

Otherwise `client` and `server` are special names.

**Comment by 67726e** [comment]
@filipenevola - thank you for the rapid response!

```
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  }
```

The (presumably) relevant portion of my `package.json` - if `/server/client/` cannot be used due to special-case considerations I can certainly use a different name. However I don't believe I've found this documented anywhere and so wanted to flag it.

**Comment by filipenevola** [comment]
Hi @67726e, yes the short answer would be: use a different name if possible.

The long answer would be: I believe as you are using mainModule config so Meteor could avoid using any special meaning for `client` or `server` folders/files but probably there are some leftovers when mainModule option was implemented.

**Comment by 67726e** [comment]
@filipenevola - Understood. I can proceed on my current project without issue, however this does appear to be a bug if the intent is to allow for these names to be usable.

I've created a public [reproduction repository](https://github.com/67726e/server-side-client-reproduction) with the latest (Meteor 2.1).

**Comment by radekmie** [comment]
Personally, I always treated it like a great way to fence out "incorrect" imports.

For example, a functionality that creates CSV exports will require a lot of dependencies not used elsewhere. Usually, it'll have a couple of "internal" helpers. Now, someone needs this helper on the client (they share some logic, whatever). Putting this whole feature in a `server` directory makes sure that the person will not be able to accidentally include all of these dependencies.

I do, however, vote for better error reporting. Instead of "cannot find module X", it could say something like "cannot import module X (cross-boundary import)".

**Comment by StorytellerCZ** [comment]
@zodern do you think it would be possible to add the error message per @radekmie suggestion. If I have some time I will look into it myself, but you know that area so you probably have a better idea.
