### ISSUE TITLE
Unable to read MONGO_URL env. 

### ISSUE THREAD

**Issue by pociej** [meteor/meteor#11373]
Hi. Im trying to run my app on ubuntu server without mup. As it is described in documentation MONGO_URL and ROOT_URL has to be specified. 
So i ssh to my server clone app, build it and run. `MONGO_URL=my_connection_string  ROOT_URL=root_url node main.js` It throws. `Error: MONGO_URL must be set in environment` It doesn't make sense as MONGO_URL is specified. What is more interesting is fact, that if I set some shit as `MONGO_URL` like `MONGO_URL=blahblah` it properly says that connection string is invalid. Is there something i don't know about way meteor read and parse connection string?

Anyways even for some reason connection string i took from mongo atlas is wrong, it shouldnt be throw like this.

**Comment by brucejo75** [comment]
@pociej, do you execute `MONGO_URL=my_connection_string ROOT_URL=root_url node main.js` from the command line?  Or is it an `npm` rule?

I believe setting variables that way only works in `npm` rules or you can use the `env` command.

A simple set of tests:
add rule `"scripts": {"envtest": "FOOBAR=bar echo \"$FOOBAR\""}` to your `package.json` file.

And run these tests:
```bash
bash$ FOOBAR=bar echo "$FOOBAR"

bash$ npm run envtest

> envtest@1.0.0 envtest /home/brucejo/tests/envtest
> FOOBAR=bar echo "$FOOBAR"

bar
bash$ env FOOBAR=bar echo "$FOOBAR"
bar
```

**Comment by filipenevola** [comment]
Hi @pociej, did the comment above solve your problem?

**Comment by pociej** [comment]
@filipenevola i executed it from command line, problem was that mongo connection string contained special chars. After i wrap it so i have MONGO_URL='my_connection_string' i started working. Anyways meteor throws bad error.
