### ISSUE TITLE
Hot module replacement behaves erratically

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11372]
It seems _Hot Module Replacement_ sometimes, or in some scenarios _always_, produces unreliable results.

While making changes in a Svelte-component, I'd get errors in the console after every change and the UI is not updating accordingly, or is acting all wonky, like duplicating the element, with one of the "versions" being the old presentation that was supposed to get replaced.

I'm also using `zodern:melte@1.3.1` combined with `svelte@3.35.0`. 

### The expected behavior

Code change, with Hot module replacement in use, replaces the code in place, without errors, and the view is updated accordingly.

### The actual behavior

Errors displayed in console, duplicated components in UI.
<img width="628" alt="Screenshot 2021-04-05 at 14 12 46" src="https://user-images.githubusercontent.com/17210302/113569424-2c830700-961b-11eb-966e-584c978c7b73.png">

<img width="297" alt="Screenshot 2021-04-05 at 14 20 25" src="https://user-images.githubusercontent.com/17210302/113569385-18d7a080-961b-11eb-8385-7f88fa094f60.png">

---------

- The version of Meteor showing the problem: 2.1
- The operating system you're running Meteor on: Mac OS Big Sur (M1)

- [ ] ~~simple reproduction!~~  I tried, but triggering this error seems to require a rather "deep" project structure, or some other missing ingredients that I've yet failed to discover. I will update with a repro once I manage to create one.

**Comment by zodern** [comment]
I haven't been able to reliably reproduce the error, but since the HMR changes in `zodern:melte@1.4.0` I haven't seen it. If you encounter the error again, we can re-open the issue.
