### ISSUE TITLE
[Types] Missing Meteor.isAppTest property in types of Meteor

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#11377]
Hello, I'm starting to test my endpoints and I found out that it is missing **Meteor.isAppTest** to add to `@types/meteor` . This env variable is necessary when you run `meteor test` command with [**full-app**](https://guide.meteor.com/testing.html#test-modes) flag.

I forked [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor/meteor.d.ts) to make this update, but when I try to generate globals through the script, it removes all globals and change the `meteor-test.ts` file.

```shell
(base) ➜  meteor git:(master) pwd
/Users/diavrank/Documents/DefinitelyTyped/types/meteor
(base) ➜  meteor git:(master) scripts/generate-globals
(base) ➜  meteor git:(master) ✗ gs
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    globals/accounts-base.d.ts
        deleted:    globals/blaze.d.ts
        deleted:    globals/browser-policy-common.d.ts
        deleted:    globals/check.d.ts
        deleted:    globals/ddp-rate-limiter.d.ts
        deleted:    globals/ddp.d.ts
        deleted:    globals/ejson.d.ts
        deleted:    globals/email.d.ts
        deleted:    globals/http.d.ts
        deleted:    globals/meteor.d.ts
        deleted:    globals/mongo.d.ts
        deleted:    globals/random.d.ts
        deleted:    globals/reactive-dict.d.ts
        deleted:    globals/reactive-var.d.ts
        deleted:    globals/session.d.ts
        deleted:    globals/templating.d.ts
        deleted:    globals/tiny-test.d.ts
        deleted:    globals/tools.d.ts
        deleted:    globals/tracker.d.ts
        modified:   test/globals/meteor-tests.ts

no changes added to commit (use "git add" and/or "git commit -a")
(base) ➜  meteor git:(master) ✗ 

```

So, I wonder if I can edit directly in the `globals/meteor.d.ts` or anyone can help me with this please?

**Notes:**

- Mac OS 11.2.2
- Node: 12.18

**Comment by StorytellerCZ** [comment]
You should reach out to the DefinitelyTyped repository maintainers as this is outside of this project.

**Comment by filipenevola** [comment]
Hi @diavrank I recommend that you do the same process that I did here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52258

Could you?

The update above was to update `setMinimumBrowserVersions` as suggested here https://github.com/meteor/babel-preset-meteor/issues/13#issuecomment-803578861

**Comment by diavrank** [comment]
> Hi @diavrank I recommend that you do the same process that I did here [DefinitelyTyped/DefinitelyTyped#52258](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52258)

Thank you, I will check it out.

**Comment by diavrank** [comment]
Fixed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55608)

**Comment by StorytellerCZ** [comment]
Thanks a lot @diavrank !
