### ISSUE TITLE
[2.1] fails to install cordova into Meteor Tool

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#11375]
Unable to install Cordova into Meteor Tool

## Environment
Meteor **v2.1**
Mac OS X: version **10.14.6** BuildVersion:18G6032

## Repro

1st remove your installation of meteor, mine was at `~/.meteor`.

```
$ curl https://install.meteor.com/ | sh
$ meteor create androidtest
$ cd androidtest
$ meteor
```
verify the app works on `localhost:3000`.  Kill the server `^C`.

```
$ meteor add-platform android
Installing Cordova in Meteor tool        /
```

"`Installing Cordova in Meteor tool`" never stops spinning.  Cordova never installs.

`ANDROID_HOME` & `JAVA_HOME` are set properly.
`PATH` includes android `platform-tools` & `build-tools/26.0.2`.

Any help or tips appreciated!

**Comment by filipenevola** [comment]
Hi @brucejo75 are you sure it's not something in your machine?

It's working fine here with your steps and also in production apps that I have.

```bash
➜  tests meteor create androidtest --release 2.1
Created a new Meteor app in 'androidtest'.    

To run your new app:                          
  cd androidtest                              
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials            
                                              
When you’re ready to deploy and host your new Meteor application, check out
Cloud:
  https://www.meteor.com/cloud                
                                              
➜  tests cd androidtest 
➜  androidtest meteor
[[[[[ ~/Documents/meteor/ws/tests/androidtest ]]]]]

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
^C
➜  androidtest meteor add-platform android
android: added platform                   
```

**Comment by brucejo75** [comment]
@filipenevola, forgot to mention.  This works fine in my Linux machine.  It only has a problem on MacOS.  Did you perform this on a Mac?

If you successfully made this work on Mac.  Any tips for helping me to debug would be helpful!

Thanks!

**Comment by filipenevola** [comment]
Yes @brucejo75, I did it on Mac.

Have you added METEOR_PROFILE=1 to see more logs? Maybe you could get where exactly it's hanging.

You could also add new logs to Meteor running from a checkout.

Let me know if you need help in the debugging process.

**Comment by brucejo75** [comment]
Thanks @filipenevola,

I will close this issue & dig into it...

**Comment by brucejo75** [comment]
@filipenevola, you forgot the most important step:

```
$ curl https://install.meteor.com/ | sh
```

Need to remove `~/.meteor` first.

The issue is installing Cordova not building for cordova...

If you could check that out, it would be super helpful.

Thanks!

**Comment by brucejo75** [comment]
@filipenevola, I found the issue on my machine.

For some reason I am unable to `npm install` some packages, in this case `cordova-lib` is hanging.  I will dig on this deeper...

I have no idea what is happening on this machine, but this is not a Meteor issue.
