### ISSUE TITLE
undocumented env variable DDP_DEFAULT_CONNECTION_URL

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#11406]
Meteor makes use of the `DDP_DEFAULT_CONNECTION_URL` environment variable to modify the `__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL` variable in the server.

`__meteor_runtime_config_.DDP_DEFAULT_CONNECTION_URL` is then transmitted by the server to the clients in the downloaded index files.

This variable is then used by the client to determine where to make the DDP client connection.

This all works great, except for 2 issues:
1. This does not work for `cordova` apk builds because `cordova` puts a static version of  `__meteor_runtime_config_.DDP_DEFAULT_CONNECTION_URL` in the build and does not use `process.env.DDP_DEFAULT_CONNECTION_URL` to determine that value.
2. The environment variable is not documented.

## Proposal

Let me know if you want me to submit PRs to do this...

### Fix cordova builds to use `process.env.DDP_DEFAULT_CONNECTION_URL`
Simple fix in [builder.js](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L499)

```diff
- DDP_DEFAULT_CONNECTION_URL: mobileServerUrl,
+ DDP_DEFAULT_CONNECTION_URL: process.env.DDP_DEFAULT_CONNECTION_URL || mobileServerUrl,
```

As a workaround for now I modified `~/.meteor/packages/meteor-tool/.2.2.0.cu6yc3.qzp56++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cordova/builder.js` in my local installation of meteor.

### Document `process.env.DDP_DEFAULT_CONNECTION_URL`
Here is my stab at documenting `DDP_DEFAULT_CONNECTION_URL` assuming that the fix above is applied:

> **DDP_DEFAULT_CONNECTION_URL**
> (_development, production_)
>
> Set this environment variable if you have a DDP host that is not your server host.  Set this environment variable when building `cordova` builds.   Set this environment variable when running the meteor server for `web.browser` & `web.browser.legacy` builds.

**Comment by StorytellerCZ** [comment]
Hi @brucejo75 ! Thank you for the report! Feel free to go ahead and submit the PR and feel free to also submit a PR to the [docs](https://github.com/meteor/docs). I'm mostly concerned here with how it will affect existing apps.
As for the documentation I think the description needs to be expanded on what the constant is and expand under which circumstances should you set it manually, because from your description it sounds that you need to tinker with it every time you make a build which is not the case.

**Comment by brucejo75** [comment]
@StorytellerCZ,

Will do.

Thanks for feedback, I see how my current suggested documentation is unclear 😸
