### ISSUE TITLE
IE11 compatibility (sorry)

### ISSUE THREAD

**Issue by nimpla** [meteor/meteor#11418]
When opening a new meteor project in IE11 it throws errors because some packages are not compiled to ES5. (e.g. arrow functions)

### Reproduction
1. create bare meteor project
```bash
$ meteor create --bare PROJECTNAME
```
2. open up project in IE11

### Environment
Version: Meteor 2.2
OS: Windows 10 / x86_64

### Expected
Basically the new Meteor app

### Result
![image](https://user-images.githubusercontent.com/9716355/117556324-d1a05d80-b067-11eb-80d9-76e24fd43fcc.png)

**Comment by StorytellerCZ** [comment]
I will boot into Windows later today and see what I can do about this, but no promises.

**Comment by StorytellerCZ** [comment]
I fixed the issues with `react-dast-refresh` issues and after a refresh the other error went away.

**Comment by StorytellerCZ** [comment]
Fix published in `react-fast-refresh@0.1.1`

**Comment by nimpla** [comment]
Thanks for fixing. Is there a way to make the null references work anyway? Is this due to the compilation on ES2018? Are there any polyfills for this?
![image](https://user-images.githubusercontent.com/9716355/118362246-0ee87c00-b58f-11eb-9b5e-b6bcbbc0fcc9.png)

**Comment by StorytellerCZ** [comment]
That is another bug, in my experience just refreshing the page should make it go away.

**Comment by nimpla** [comment]
> That is another bug, in my experience just refreshing the page should make it go away.

Unfortunately not, somehow IE11 cannot resolve the packages.

```
The property "X" of an undefined or null reference cannot be retrieved.
```

each error is thrown by the reference of `Packages`

```js
var meteorInstall = Package.modules.meteorInstall;
var DDP = Package['ddp-client'].DDP;
var Tracker = Package.tracker.Tracker;
```

**Comment by StorytellerCZ** [comment]
Strange I haven't encountered it when testing the previous one on IE. I'll take a look again when I boot to Windows.

**Comment by StorytellerCZ** [comment]
@nimpla I was unable to reproduce the issue. So my guess is that there might be some other package that is leaking modern JS to IE. If the issue still persist, please make a new issue.
