### ISSUE TITLE
static-html fails to download

### ISSUE THREAD

**Issue by LiuSuY** [meteor/meteor#11432]
=> Started proxy.
=> Started HMR server.
=> Started MongoDB.
   Downloading static-html@1.3.0... 一直锁定在此处

**Comment by crapthings** [comment]
被墙了？

试试 --verbose 启动，是不是因为网络

**Comment by StorytellerCZ** [comment]
@LiuSuY What OS are you using?

**Comment by StorytellerCZ** [comment]
Possible duplicate of #11431

**Comment by LiuSuY** [comment]
> @LiuSuY您正在使用什么操作系统？

Windows 10 专业版 20H2版本 ，主要是网络原因，有什么好的办法可以加速这个包的下载吗？我在https://npm.taobao.org/ 中没有找到有关的加速包，需要大量的时间下载此包

**Comment by LiuSuY** [comment]
> @LiuSuY您正在使用什么操作系统？

Windows 10 专业版 20H2版本 ，主要是网络原因，有什么好的办法可以加速这个包的下载吗？我在https://npm.taobao.org/ 中没有找到有关的加速包，需要大量的时间下载此包
