### ISSUE TITLE
Meteor.user() has wrong type

### ISSUE THREAD

**Issue by bartenra** [meteor/meteor#11435]
Since Meteor 1.10 `Meteor.user()` accepts an object where you can specify the fields to fetch, as per the [docs](https://guide.meteor.com/accounts.html#prevent-unnecessary-data-retrival). E.g.

```js
const name = Meteor.user({fields: {"profile.name": 1}}).profile.name;
```

However in `meteor.d.ts` (as of Meteor 2.2) it is typed as:

```ts
        function user(): User | null;
```

This should be changed to:

```ts
        function user(options?: {fields?: {[key: string]: 1}}): User | null;
```

**Comment by StorytellerCZ** [comment]
Hi @bartenra we do not maintain Typescript definitions, please submit a Pull Request over at Definitelly Typed repository to change the definition:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/793c6074221b7cb72a062bdba6cff77388ee999e/types/meteor/meteor.d.ts

**Comment by bartenra** [comment]
Sorry, didn't know that.

**Comment by StorytellerCZ** [comment]
@bartenra No worries. 🙂
