### ISSUE TITLE
Accounts.onLogin fired twice, the first time Meteor.user() is not available.

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#11446]
This bug was supposed to be fixed on 1.12 but it's not. Reopening the issue from https://github.com/meteor/meteor/issues/10853.

The Accounts.onLogin callback on the client is fired twice. Inside the first one, Meteor.user() is not available. Inside the second one it is.

```
// call this on the client's code before anything else, so that Meteor.user() is not loaded yet
Accounts.onLogin(() => {
    console.log(Meteor.user());
});
```

**Comment by StorytellerCZ** [comment]
@santiagopuentep you should have re-opened #10853, but that doesn't matter. Can you provide us more information (what version of Meteor and the packages are you using), can you provide a simple reproduction repository or event a better create a test?

**Comment by santiagopuentep** [comment]
@StorytellerCZ Sorry, I didn't know I could reopen it myself. I looked just know but I still don't see how. Could you please tell me how to do it? In the original issue is a reproduction.

**Comment by StorytellerCZ** [comment]
Re-opening #10853 and closing this issue.
