### ISSUE TITLE
how to install meteor 1.12?

### ISSUE THREAD

**Issue by MrCrazyCrab** [meteor/meteor#11441]
<!--
* ❓ Questions?
          how to install meteor 1.12? i want to inatsall the meteor 1.12 on windows, how should i do ?

**Comment by StorytellerCZ** [comment]
Use `meteor update --release 1.12`

**Comment by MrCrazyCrab** [comment]
@StorytellerCZ  i tried, but i stucked. i comes with the erroe-- Sorry, Meteor 1.12 is not installed and could not be downloaded. Please check to make sure that you are
online.
Do you know where ic can download the file of meteor 1.12, so i can install it offline.

**Comment by StorytellerCZ** [comment]
@MrCrazyCrab Try `1.12.1`.
I don't think we have a way to install new versions without access to Internet, do we? @filipenevola

**Comment by MrCrazyCrab** [comment]
@StorytellerCZ  i did do want you said. But the error mentioned that i am not online. i am sure i can surf the intetnet. The problem is only encountered when i run the code.

**Comment by StorytellerCZ** [comment]
Are you behind a corporate proxy or firewall or something of that sorts?

**Comment by StorytellerCZ** [comment]
@MrCrazyCrab any updates on this?

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while. If this issue persist feel free to re-open with new information.

**Comment by maxfi** [comment]
I've just had the same issue: `Sorry, this project uses Meteor 1.12.1, which is not installed and could not be downloaded. Please check to make sure that you are online.` on Bitbucket Pipelines. I haven't changed anything in the build process and it was been working fine for the last few months...

**Comment by StorytellerCZ** [comment]
Yes, there have been issues with servers. Should get resolved soon.

**Comment by maxfi** [comment]
> Yes, there have been issues with servers. Should get resolved soon.

Thanks @StorytellerCZ. It's working again now. What can I do to avoid this in the future? Is it possible to install a specific meteor version in my CI docker image and avoid server issues? TIA. 🙏

**Comment by MrCrazyCrab** [comment]
@StorytellerCZ  i pointed out this issue about two months ago, i didn't got any useful information to resolve it. So i have abandon and use other tools to replace it.
