### ISSUE TITLE
Nginx server running port is 4400 and docker container for wekan project running port is 7300. In Ngnix.conf file i have added the proxy_pass http://localhost:7300. But i could not get the wekan UI, I am facing the error given below.

### ISSUE THREAD

**Issue by rshylendar** [meteor/meteor#11459]
(index):4 GET http://localhost:4400/6d9994ceb11a3e28fabbb446ea219cb8fafdfcda.css?meteor_css_resource=true net::ERR_ABORTED 404 (Not Found)(index):11 GET http://localhost:4400/a3d94bab4aefc1e264932bc4ac7718d60ee2f185.js?meteor_js_resource=true net::ERR_ABORTED 404 (Not Found)(index):11 GET http://localhost:4400/a3d94bab4aefc1e264932bc4ac7718d60ee2f185.js?meteor_js_resource=true net::ERR_ABORTED 404 (Not Found)
--

![image](https://user-images.githubusercontent.com/37284927/120475190-aa1e8580-c3c6-11eb-8622-7f96c25948f8.png)

**Comment by StorytellerCZ** [comment]
Hi, could you provide a reproduction? 😉
You can read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor).

**Comment by rshylendar** [comment]
@StorytellerCZ 
Nginx server running port is 4400 and docker container for wekan project running port is 7300. In Nginx.conf file I have added the proxy_pass http://localhost:7300. But I could not get the wekan UI, I am facing the error given below.

1. Ngnix server running port is 4400.
2. Docker container running port is 7300.
3. In Ngnix server, i have used the proxy_pass in location /tenant1/.
4. `location /dev/ {
                proxy_pass http://localhost:7300;
                proxy_redirect http://localhost:7300 https://$host;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                # These settings are added for web-socket
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade; # allow websockets
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
        }
		location /tenant1.1/ {
			proxy_pass  http://localhost:7100/;
		}`

- The problem is Ngnix server is hitting with localhost:4400 (http://localhost:4400/6d9994ceb11a3e28fabbb446ea219cb8fafdfcda.css?meteor_css_resource=true)
- I will change the URL localhost:7300, the URL is working fine and we are getting 200 status. (http://localhost:7300/6d9994ceb11a3e28fabbb446ea219cb8fafdfcda.css?meteor_css_resource=true)
- In this case what is the problem in nginx server or wekan container in docker.
- Please help with this query.

**Comment by xet7** [comment]
@rshylendar 

You could look at:
- Nginx config https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
- Setting ROOT_URL https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

If you have problems with WeKan, please add issue to https://github.com/wekan/wekan/issues .
And not to these Meteor issues. Thanks!

@StorytellerCZ

You can close this issue, it's old.
