### ISSUE TITLE
[GALAXY][LOGIN] Uppercased username

### ISSUE THREAD

**Issue by nathanschwarz** [meteor/meteor#11456]
I've been trying to log in into my galaxy account for severals days now.
When I created my account I did put uppercases letters in my username.
But since last week the following error keep rising up in the console : 
```
Could not sync user from MD accounts [validation-error]
details: {username: "Username can only contain lowercase letters or numbers."}
```
I suppose an update was made internally...
could you fix this issue ? Thanks a lot 👍

**Comment by filipenevola** [comment]
Hi @nathanschwarz we are going to take a look.

In these cases the best way to get help asap is sending a ticket to support [at] meteor.com

**Comment by denihs** [comment]
Hi @nathanschwarz could you please open a ticket to support [at] meteor.com? We gonna need to ask for some personal information in order to fix this.
