### ISSUE TITLE
isolation client only mongo collection

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#11454]
```js
const a = new Mongo.Collection('doc', { connection: null })
a.insert({test:1})
const b = new Mongo.Collection('doc', { connection: null })
b.find().fetch()
```

how possible to use same name, but isolate records?

**Comment by StorytellerCZ** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.

**Comment by crapthings** [comment]
```js
a = new Mongo.Collection(null, { connection: null })
a.find({ test: 1 }).fetch()
b = new Mongo.Collection(null, { connection: null })
b.find().fetch()
```

it looks this work
