### ISSUE TITLE
Confilct meteor-apm-agent@3.4.0 with Meteor@2.3-beta.5

### ISSUE THREAD

**Issue by ixdi** [meteor/meteor#11460]
When adding meteor-apm-agent the following error appears:
```
error: Conflict: Constraint http@1.4.2 is not satisfied by http 2.0.0-beta230.5.
* http@1.4.2 <- mdg:meteor-apm-agent 3.4.0
```
Any idea how to solve this? Thanks

**Comment by StorytellerCZ** [comment]
I will release beta package of the apm agent that goes together with the beta and rc releases.

**Comment by StorytellerCZ** [comment]
More on why this fails in #11453
