### ISSUE TITLE
METEOR@2.3-beta.5 update errors

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#11461]
I get the following errors when trying to upgrade to the latest beta.
```
meteor update --release METEOR@2.3-beta.5
=> Errors while initializing project:         
                                              
While reading package from `/XXX/packages/meteor-accounts-t9n`:
package.js:20:9: Package.on_use is not a function

While reading package from `/XXX/packages/meteor-i18n`:
package.js:8:9: Package.on_use is not a function

```

**Comment by StorytellerCZ** [comment]
Yes, the API that those packages use has been deprecated since v1 and has been removed in the latest beta. Please use camel case API calls in `package.js` for packages.

**Comment by StorytellerCZ** [comment]
I have submitted PRs to those two packages mentioned to fix the issue.
