### ISSUE TITLE
Usage of npm-bcrypt

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#11466]
[npm-bcrypt](https://github.com/meteor/meteor/tree/devel/packages/npm-bcrypt) package is only used in accounts-password and internally it falls back to [bcryptjs](https://www.npmjs.com/package/bcryptjs) which hasn't been updated in a while. So wouldn't it be better if we simply added a new npm dependency to accounts-password with [bcrypt](https://github.com/kelektiv/node.bcrypt.js) and deprecated npm-bcrypt? 
https://github.com/meteor/meteor/blob/f5d3715431a2dd938afbf2f12d822476bd30b3fa/packages/accounts-password/package.js#L12

**Comment by StorytellerCZ** [comment]
I think that is viable, given that back then npm wasn't as integrated into the system as it is now that would work, though we should probably check the docs and notes in the code to make sure that we aren't missing something crucial.
