### ISSUE TITLE
Bug: createUser in accounts_password breaks api contract (release-2.3 branch)

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11471]
The 2.3 version of password_server.js has new parameter checks that are in conflict with

- my code
- the documentation in the file
- the typescript types on DefinitelyTyped

The new check on the password option disallows sending in strings, which is not only documented at the top of the file but is also the only option in the Typescript types for Accounts.

Old working code in release-2.2:
https://github.com/meteor/meteor/blob/f9a098a03541718a8cfcddee1e5ff2ce9be9355a/packages/accounts-password/password_server.js#L279

Working code in devel branch:
https://github.com/meteor/meteor/blob/f5d3715431a2dd938afbf2f12d822476bd30b3fa/packages/accounts-password/password_server.js#L279

New broken code in release-2.3:
https://github.com/meteor/meteor/blob/0dfc7a7a64969c0c1852775add6411133595fd90/packages/accounts-password/password_server.js#L277

Documentation at the top of  the file:
https://github.com/meteor/meteor/blob/f5d3715431a2dd938afbf2f12d822476bd30b3fa/packages/accounts-password/password_server.js#L15

**Comment by StorytellerCZ** [comment]
This was my fault when removing the old SRP code. I have reverted the check which I think should be all that is needed. I will release another beta later today with the fix.

**Comment by StorytellerCZ** [comment]
@perbergland Have you checked beta.7, fix should be there, can you please confirm?

**Comment by perbergland** [comment]
Oh sorry yes this can be confirmed as fixed

**Comment by filipenevola** [comment]
Thank you.
