### ISSUE TITLE
Custom sounds won't play if used custom-sound folder on rocket chat.

### ISSUE THREAD

**Issue by Resident1981** [meteor/meteor#11483]
Rocket chat 3.15.0
node v12.22.1
OS: CentOS Linux 7 (Core)
Built-in sounds work fine.
Permit: drwxr-xr-x 2 rocketchat rocketchat 4,0K jun 18 15:50 UserSounds
Error when try to listen:
\---------
Exception in callback of async function: TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"     at ServerResponse.setHeader (_http_outgoing.js:533:3)     at ServerResponse.res.setHeader (/home/rocketchat/RocketChatServer/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/lib/patch.js:132:22)     at app/custom-sounds/server/startup/custom-sounds.js:75:7     at runWithEnvironment (packages/meteor.js:1286:24)     at packages/meteor.js:1299:14     at /home/rocketchat/RocketChatServer/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   code: 'ERR_HTTP_INVALID_HEADER_VALUE' }
--------\
The emoji are okay.

**Comment by StorytellerCZ** [comment]
I'm closing this as this is not a Meteor bug. Please reach out to Rocket chat support/[Github](https://github.com/RocketChat)/forums to get help with this issue.
