### ISSUE TITLE
Meteor command won’t run, error: ‘ AssignProcessToJobObject: (87) The parameter is incorrect.’ 

### ISSUE THREAD

**Issue by njneer** [meteor/meteor#11482]
Meteor Version 2.2.0
OS: Windows 10
Expected behavior: meteor command should run and not end in error shown in description
Actual behavior: meteor command starts but dies with error in title

**Comment by StorytellerCZ** [comment]
What Meteor command are you running?

**Comment by njneer** [comment]
Every meteor command I run has the same error. meteor create, meteor npm install, meteor —settings , etc

**Comment by njneer** [comment]
Was issue with environment variable on my system.
