### ISSUE TITLE
SASS file from node_modules are not being transpiled only on --production mode

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#11499]
I had in a SASS file the following import:

@import '{}/node_modules/react-credit-cards/lib/styles.scss';

this file is inside this folder: imports/app/checkout/ui/components/CreditCardIssuers.scss

when compiling for development, everything works, but when compiling for production it breaks

```
  message: 'Scss compiler error: Error: File to import: {}/node_modules/react-credit-cards/lib/styles.scss not found in file: undefined\n' +
    '        on line 2 of {}/imports/app/checkout/ui/components/CreditCardIssuers.scss\n' +
```

even if I symlink it to the /imports folder, it doesn't work.

fourseven:scss is at version 4.14.2

**Comment by StorytellerCZ** [comment]
Could be related to #11486 ?

**Comment by StorytellerCZ** [comment]
Made update to less and minifiers: https://github.com/meteor/meteor/pull/11501
Thought I don't think those are going to solve it. Could it be related to #11498 ?

**Comment by renanccastro** [comment]
I'm closing this issue here in favor of: https://github.com/Meteor-Community-Packages/meteor-scss/issues/309
