### ISSUE TITLE
Server only file added on package.js is showing up on client bundle

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#11498]
In 2.3, the package east5th:package-scan is behaving oddly. Its package.js only specifies code to be added on the server (https://github.com/East5th/package-scan/blob/master/package.js), but on 2.3 (even in an empty project with only this package and nothing else) it seems that this file is getting added to the client bundle as well.

https://github.com/East5th/package-scan/blob/master/package.js

Author: @brianlukoff

**Comment by StorytellerCZ** [comment]
Tested this with another package and it goes the other way as well. In `dynamic-import` client code gets added to server. What I don't get is how the tests passed...

**Comment by renanccastro** [comment]
I'm closing this bug as we saw that meteor 2.3 is installing east5th:package version 0.0.1 by default, which is expected as after .1 they added a core dependency to the list (HTTP) which is incompatible with meteor 2.3 without the author update.
