### ISSUE TITLE
POSIX dependency crashes meteor tool on Windows

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#11497]
Example output attached.
Probably related to this: https://github.com/vlasky/whomst/issues/1

C:\Users\User\dev\dom_test>meteor
[[[[[ C:\Users\User\dev\dom_test ]]]]]

=> Started proxy.
=> Started HMR server.
=> Started MongoDB.
=> Errors prevented startup:

While loading package webapp@1.11.0:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c
C:\Users\User\AppData\Local.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
rebuild --update-binary
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit
(C:\Users\User\AppData\Local.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:375:28)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command
“C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\bin\node.exe”
“C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js”
“rebuild”
gyp ERR! cwd
C:\Users\User\AppData\Local.meteor\packages\webapp\1.11.0\npm\node_modules.temp-sce1hu.5yszl\node_modules\posix
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\User\AppData\Roaming\npm-cache_logs\2021-06-24T17_41_33_054Z-debug.log
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit
(C:\Users\User\AppData\Local.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:375:28)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command
“C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\bin\node.exe”
“C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js”
“rebuild”
gyp ERR! cwd
C:\Users\User\AppData\Local.meteor\packages\webapp\1.11.0\npm\node_modules.temp-sce1hu.5yszl\node_modules\posix
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\User\AppData\Roaming\npm-cache_logs\2021-06-24T17_41_33_054Z-debug.log

=> Your application has errors. Waiting for file change.

**Comment by StorytellerCZ** [comment]
@renanccastro I have created the issue in whomst, it is this.

**Comment by renanccastro** [comment]
Removing posix from npm-shinkwrap fixes the issue, as it's a optional dependency.
I will close this issue for now, as it's fixed on 2.3.1-beta.1, but @vlasky might want to revisit this.

https://github.com/meteor/meteor/pull/11491/commits/dcb7dcc82bcc0b0b87f5b82bee608ceae4d0aa28

**Comment by Ashedragon** [comment]
@renanccastro Is there a guide on how I'd install 2.3.1? I can't seem to even get started with meteor due to this issue.

**Comment by StorytellerCZ** [comment]
@Ashedragon on Windows I have just published version 2.2.2 of the installer, so you can go through there. 2.3.1 will come out in the next few days.

**Comment by vlasky** [comment]
> Removing posix from npm-shinkwrap fixes the issue, as it's a optional dependency.
> I will close this issue for now, as it's fixed on 2.3.1-beta.1, but @vlasky might want to revisit this.
> 
> [dcb7dcc](https://github.com/meteor/meteor/commit/dcb7dcc82bcc0b0b87f5b82bee608ceae4d0aa28)

I have released [@vlasky/whomst 0.1.7](https://www.npmjs.com/package/@vlasky/whomst).

`package-lock.json` has been removed, which should eliminate problems when building under platforms that don't support posix.

**Comment by StorytellerCZ** [comment]
I will get an update out ASAP.
