### ISSUE TITLE
Default skeleton outputs warning on react-meteor-data

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#11500]
We need to update react-meteor-data to use newest react 17, and update the default skel with the new version to stop showing this warning

![image](https://user-images.githubusercontent.com/3637255/123657523-3de94300-d807-11eb-9dcf-bcd59353c246.png)

**Comment by StorytellerCZ** [comment]
Published new versions, but `react-meteor-data` doesn't depend on React directly, only for testing. I have also bumped versions for skelets in this PR: https://github.com/meteor/meteor/pull/11501
Either way I was unable to reproduce. @renanccastro please try now within the 2.3.1 release branch and let me know if the problem persist for you.
