### ISSUE TITLE
Make AAB the default format for building Android apps

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#11509]
Instead of outputting an apk file, start outputting aab as the default. We should also give the option to produce apk files.

*Google Play will start requiring new apps to be published with the Android App Bundle starting August 2021* - https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html

**Comment by StorytellerCZ** [comment]
Wow, only a month of notice. Given that it is the new standard it should be the default, but I agree that we should still allow to create apk files as well for edge cases where it is still needed.

**Comment by StorytellerCZ** [comment]
Will, be released in Meteor 2.3.1

**Comment by ensemblebd** [comment]
`meteor run android`
```
=> Errors executing Cordova commands:

   While running Cordova app for platform Android with options --buildConfig,C:\the_app\.meteor\local\cordova-build\build.json,--device:
   Package type "bundle" is not supported during cordova run.
```

**Comment by renanccastro** [comment]
> `meteor run android-device`
> 
> ```
> => Errors executing Cordova commands:
> 
>    While running Cordova app for platform Android with options --buildConfig,C:\the_app\.meteor\local\cordova-build\build.json,--device:
>    Package type "bundle" is not supported during cordova run.
> ```

thanks for reporting @ensemblebd it must have used a local cache because I ran this command locally for testing.

Anyway, can you please give it a try on Meteor 2.3.2? Use meteor update --release 2.3.2

**Comment by ensemblebd** [comment]
confirmed fix for me, thank you!! 
Very awesome release this one, tons of great changes same as last release too. Thank you very much; you guys are the best <3
