### ISSUE TITLE
test-packages ./ can't load jquery / blaze

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#11529]
Meteor 2.2.1 (at least on Windows 10) doesn't seem to be able to run `meteor test-packages ./` on old repositories that use Blaze, because of a failure to include the `jquery` NPM package.

## Reproduction

Here's an example from [this post](https://github.com/meteortesting/meteor-mocha/issues/82#issuecomment-451548538):

1. `git clone https://github.com/cquencial/meteor-bpmn-engine.git`
2. `cd meteor-bpmn-engine`
3. `meteor test-packages ./`
4. Open `http://localhost:3000`

Here's one that used to work for me:

1. `git clone --recurse-submodules --remote-submodules https://github.com/edemaine/meteor-file-collection.git`
2. `cd meteor-file-collection`
3. `meteor test-packages ./`
4. Open `http://localhost:3000`

## Error message

The client gives the following warning from [this code](https://github.com/meteor/meteor/blob/ffcfa5062cf1bf8a64ea64fef681ffcd99fe7939/packages/non-core/jquery/main.js):

```
The jquery npm package could not be found in your node_modules directory.
Please run the following command to install it:

  meteor npm install jquery

If you previously relied on a specific version of jquery, it may be important
to install that version; for example:

  meteor npm install jquery@1.12.1
```

Subsequently, Blaze throws this error:

```
Uncaught Error: jQuery not found
    at module (dombackend.js:8)
    at fileEvaluate (modules-runtime.js?hash=834e737986edfacdf20bbc352d7f3f62e50d0b47:346)
    at Module.require (modules-runtime.js?hash=834e737986edfacdf20bbc352d7f3f62e50d0b47:248)
    at require (modules-runtime.js?hash=834e737986edfacdf20bbc352d7f3f62e50d0b47:268)
    at blaze.js?hash=697f9e905c3b1c595cec8a15f66f6cd9443dd4b7:5789
    at blaze.js?hash=697f9e905c3b1c595cec8a15f66f6cd9443dd4b7:5808
```

## Analysis

`.npm/package/node_modules/jquery` exists; it's presumably just not getting sent to the client. I suspect that this is caused by the move in Meteor package `jquery@3.0.0` move to peer NPM dependencies, and `test-packages` doesn't handle peer NPM dependencies.  But surprisingly I get the same behavior if I add
```js
Npm.depends({
  //...
  // Just needed for testing:
  jquery: '3.6.0' // also tried '1.12.1' recommended by error message
});
```
and if I add `require('jquery')` and/or `Npm.require('jquery')` to the test code, to tell the module system to load it.

Meteor is usually good at preserving backwards compatibility, but `test-packages` within a package doesn't have a way of specifying a Meteor version...  At this point I'd be happy with a workaround though.

I figured that switching from `jquery@3.0.0` to `jquery@1.11.9` (which inlines a specific `jquery` version) would fix the problem.  Unfortunately, `test-in-browser@1.3.0` depends on `jquery@3.0.0` (not the usual `jquery@1.11.9 || jquery@1.3.0`) so I can't get that to work.  `meteor test-packages ./ --driver-package test-in-browser@1.2.0` and/or `api.use('test-in-browser@1.2.0', ['server', 'client']);` doesn't seem to work; it still uses `test-in-browser@1.3.0` and thereby fails to resolve dependencies.

[Corresponding forum post](https://forums.meteor.com/t/meteor-test-packages-fails-to-find-npm/56244)

**Comment by StorytellerCZ** [comment]
Thanks for the reproduction! I'll take a look. It indeed sounds strange. Quickly looking at the package file of meteor-file-collection there are better ways to do the versions today (`api.versionsFrom`), but that is a mute point. After running it on Linux I also get errors about missing Blaze and other packages. I have seen this error before, I will dig around to see if the what needs to be done to fix this.

**Comment by StorytellerCZ** [comment]
I have tried both reproductions and I am unable to get the error. Please try updating to latest Meteor and check if things still fail for you. If you could provide a reproduction repository that would be great.

**Comment by edemaine** [comment]
Indeed, the latest Meteor (2.3.2) seems to fix the problem. Thanks!
