### ISSUE TITLE
production build fails with blaze-hot

### ISSUE THREAD

**Issue by lauff** [meteor/meteor#11538]
After adding 

- hot-module-replacement@0.2.1
- blaze-hot@1.1.0

the production build fails with error

`
Errors prevented bundling:
While building for web.browser:
packages/blaze-hot/hot.js: [BABEL]
/builds/lauff/clubmgr/packages/blaze-hot/hot.js: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "production".
`

It looks like the packages shall better be only active during development.
How can this be achieved?

Thanks, Markus

**Comment by zodern** [comment]
> Is this something that can be reported to the maintainer of the react-fast-refresh?

It is a core Meteor package.

I've transferred this issue to the Meteor repository since it has the react-fast-refresh package.
