### ISSUE TITLE
non-SMTP transport to email package?

### ISSUE THREAD

**Issue by xet7** [meteor/meteor#11544]
Hi,
for nodemailer service, it looks like email package only has SMTP transport?
- https://github.com/meteor/meteor/blob/devel/packages/email/email.js#L26
- https://github.com/meteor/meteor/blob/devel/packages/email/email.js#L156

Or is it possible to select another `service`? So if protocol is not `smtp`, for example

a) use protocol with URL like `Outlook365://username:password@...` ? Nodemailser `service`s are listed here: https://nodemailer.com/smtp/well-known/ .

b) is it possible to add `service` to `smtp` url like `smtp://....../?service=Outlook365` ?

For example, with this nodemailer code I can send email using O365:

```
var nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
  service: "Outlook365",
  auth: {
    user: 'firstname.lastname@hotmail.com',
    pass: 'topsecret'
  },
})

let info = transporter.sendMail({
  from: 'Support Team <firstname.lastname@hotmail.com>',
  to: 'customer@example.com',
  subject: 'Hi',
  text: 'Hi! Reminder: Meeting tomorrow.',
  html: '<h1>Hi! Reminder: Meeting tomorrow.</h1>'
})
```

Well, that email package is small amount of code, so I maybe could fork it, but I have already done so much forking I kind of have too big fork factory already ;)

**Comment by xet7** [comment]
@StorytellerCZ commented today at Meteor Slack: "I plan to start next week working on a new version of the e-mail package. I will look into this."

When I tested sending with O365 using this `service: "Outlook365"`, it did work.

But using [SMTP only with command line](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses-sending-email-with-command-line) for `smtp.office365.com:587` I got these errors both with STARTTLS and TLS, so using SMTP did not work at all. There could be some predefined correct settings and behaviours that are already included in working  `service: "Outlook365"`.

```
535 5.7.3 Authentication unsuccessful [HE1PR0202CA0021.eurprd02.prod.outlook.com]
530 5.7.57 Client not authenticated to send mail. Error: 535 5.7.3 Authentication unsuccessful [HE1PR0202CA0021.eurprd02.prod.outlook.com]
read:errno=0
```

**Comment by filipenevola** [comment]
Hi @xet7 I believe it would be nice as a [discussion](https://github.com/meteor/meteor/discussions) following our feature request [guidelines](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#feature-requests).

What do you think?
