### ISSUE TITLE
Package downloads not possible - the certificate of https://warehouse.meteor.com is invalid

### ISSUE THREAD

**Issue by larswolter** [meteor/meteor#11543]
Downloads of meteor packages arent possible anymore, because the certificate is not valid anymore.

**Comment by JH7** [comment]
I think the problem is the certificate of warehouse.meteor.com. According to this screenshot, the certificate has expired today:

<img width="651" alt="grafik" src="https://user-images.githubusercontent.com/8239699/125926187-b8178328-2ab7-4f60-b488-8297f9aa571c.png">

**Comment by macrozone** [comment]
this is very critical to me right now. Anyone knows a workaround for CI/CD pipelines? (its using a node:12 base image)

**Comment by JH7** [comment]
Maybe one could use the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` to skip the certificate validation of the `meteor` tool, I'm testing that right now

**Comment by macrozone** [comment]
@JH7 yeah, me too i am testing this right now, thank you :-)

**Comment by renanccastro** [comment]
Renewed, thanks for reporting guys.
Seems like this one passed our SSL monitoring list.
We have taken measures for this never to happen again!
Sorry for that!
