### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by lmf-git** [meteor/meteor#11542]
![image](https://user-images.githubusercontent.com/67340984/125845985-0896e0f6-587b-4d80-a090-b8b05b912487.png)

**Comment by StorytellerCZ** [comment]
As far as I know meter.com is not a meteor app.

**Comment by filipenevola** [comment]
Meteor.com is a Webflow website.

**Comment by lmf-git** [comment]
That’s even worse.

**Comment by lmf-git** [comment]
Does Meteor integrate with Webflow? Lol
