### ISSUE TITLE
App.launchScreens() is not working for iOS in Meteor 2.2

### ISSUE THREAD

**Issue by mjcctech** [meteor/meteor#11555]
### Description
In Meteor 2.2 cordova was updated to version 10. This cause update cordova-plugin-splashscreen which does not support Legacy splashscreens for iOS anymore. 
Here is cordova-plugin-splashscreen  documentation https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#ios-specific-information.
Here is similar issue https://github.com/apache/cordova-ios/issues/968

### The actual behavior.
Currently App.launchScreens() https://docs.meteor.com/api/mobile-config.html#App-launchScreens supports only Legacy splashscreens for iOS.

### The expected behavior.
App.launchScreens() allow to configure Launch Storyboard
```js
        App.launchScreens({
           'Default@2x~universal~anyany': 'public/splashscreens/ios/default.png'
});
```

**Comment by filipenevola** [comment]
Hi @mjcctech in which version were you using `App.launchScreens` this way?

In my projects I'm using like this:
```
App.appendToConfig(`
  <platform name="ios">
    <splash src="${iosSplashScreensFolder}/Default@2x~universal~anyany.png" />
  </platform>
`);
```
For at least 1 year already.

Of course we could improve `launchScreens` method to support this case as well but I first I would like to understand in which version it was working for you so we can narrow down the issue better. We want to improve the configurations available in the mobile-config so this would be a good start but I would like to understand a little bit better how you were using first.

Also, the workaround above, appending to the config directly, should solve your issue for now so your splash screen will work.

Recently I explained this in a Meetup that you can watch the recording [here](https://www.youtube.com/watch?v=4wNYW6XakXo) and also a good documentation about Cordova setup [here](https://github.com/meteor/examples/tree/main/cordova) in the README.

**Comment by mjcctech** [comment]
The last working Meteor version is 2.1.1. Previously I had 
```
       App.launchScreens({
            iphone: 'public/splashscreens/ios/iphone.png',
            iphone_2x: 'public/splashscreens/ios/iphone_2x.png',
            iphone5: 'public/splashscreens/ios/iphone5.png',
            iphone6: 'public/splashscreens/ios/iphone6.png',
            iphone6p_portrait: 'public/splashscreens/ios/iphone6p.png',
            iphoneX_portrait: 'public/splashscreens/ios/iphoneX_portrait.png',
            ipad_portrait: 'public/splashscreens/ios/ipad_portrait.png',
            ipad_portrait_2x: 'public/splashscreens/ios/ipad_portrait_2x.png'
        });
```
Now I have similar workaround as you - adding this config directly by `App.appendToConfig`. And thanks for your example, I will get some improvements from there.
