### ISSUE TITLE
Upgrade `typescript` to version `4.3.5` for meteor `2.4` because it fixes a critical typescript bug

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#11566]
Typescript `4.3.3` fixes a breaking changes https://github.com/microsoft/TypeScript/issues/44429

See also the description of release [typescript `4.3.3`](https://github.com/microsoft/TypeScript/releases/tag/v4.3.3) and follow the [fixed issues query for TypeScript v4.3.3.](https://github.com/Microsoft/TypeScript/issues?utf8=✓&q=is%3Aissue+milestone%3A%22TypeScript+4.3.2%22+is%3Aclosed+)

Therefore it would be great to update at least to typescript `4.3.3`

**Comment by StorytellerCZ** [comment]
I think we still have the space for it in 2.4.

**Comment by StorytellerCZ** [comment]
@afrokick, @scharf  would you be willing to do a PR or should I?

**Comment by StorytellerCZ** [comment]
Nevermind, already on it as I was going for the same files with another issue.

**Comment by StorytellerCZ** [comment]
Typescript is updated in the latest 2.4 beta. Please give it a try.

**Comment by StorytellerCZ** [comment]
I will backport this to the Meteor 2.3.5 release so that we can get it sooner.
