### ISSUE TITLE
Apollo Skeleton incompatible with Apollo Server v3

### ISSUE THREAD

**Issue by trevor-scheer** [meteor/meteor#11565]
**Meteor version**: 2.3.2
**OS**: MacOS Big Sur (11.4) *M1 running Rosetta

Hello! We recently released Apollo Server v3 and received a report from a Meteor user who's unable to upgrade due to a runtime error they're receiving. I was able to reproduce the issue with a basic Apollo skeleton (upgraded to AS3) with these steps:

```sh
meteor create apollo-app --apollo
meteor npm install apollo-server-express@latest
meteor npm install express@4
meteor
```
Navigate to http://localhost:3000/graphql and issue a simple query:
```graphql
query {
  getLinks {
    _id
  }
}
```

The error message we're seeing is:
>`Cannot await without a Fiber`

I'm not so familiar with Meteor myself, so I'm curious to know if we've introduced a compatibility issue on our end or if this seems like something that needs to be solved on the Meteor side / within the Apollo skeleton.

@benjamn pointed me to the AS/Meteor boundary which may be a point of interest:
https://github.com/meteor/meteor/blob/devel/tools/static-assets/skel-apollo/server/apollo.js
```js
const server = new ApolloServer(...);
server.applyMiddleware({
  app: WebApp.connectHandlers,
  cors: true
});
```
Specifically, `WebApp.connectHandlers`.

For reference, [here's the thread](https://community.apollographql.com/t/apollo-3-meteor-and-cannot-await-without-a-fiber/904/3) where the issue is being discussed.

Thanks in advance!

**Comment by StorytellerCZ** [comment]
Apollo skeleton is updated for Meteor 2.4. I'll write up an article on how to upgrade in the coming days.

**Comment by trevor-scheer** [comment]
Thanks for jumping on that thread @StorytellerCZ, and great to see this is already on your radar in the upcoming release. Cheers!
