### ISSUE TITLE
How to build meteor-tool from local clone ?

### ISSUE THREAD

**Issue by BodhiHu** [meteor/meteor#11570]
Hi,

Really a great framework meteor is : D

A quick question: how to build the meteor-tool from local meteor clone ?
As constantly, after installing meteor, when running ```meteor```, it will begin to download the meteor-tool:
```
Downloading meteor@2.1.1 ....
```

Which always hung, and just stops there, so I wonder if I can build the meteor tool locally ?

Thanks a lot

**Comment by StorytellerCZ** [comment]
Yes, all you need to know is documented in the development documentation:
https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout
