### ISSUE TITLE
Build Pagination in React

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11572]
Hello everyone, I’m looking for a way to create Pagination in React.
But I also use the following:
ssr
fast render
What do you think is the best solution?

**Comment by StorytellerCZ** [comment]
Hi @Saeeed-B, I would recommend asking this on the [Meteor forums](https://forums.meteor.com) to get guidance. The Meteor repository issues are for stuff (bugs, features) related directly to the framework itself.
