### ISSUE TITLE
Avoid find/fetch when selector is { _id: { $in: [] } }

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#11589]
This could be categorized as bug or a feature request, so I think it could go here.

We use grapher to do most of our queries, and frequently this query is made when looking for relationships (but it could apply to any app that performs this type of query):

```js
Collection.find({ _id: { $in: [] } }).fetch();
```

I see in my APM that many such queries are made, and every time it takes between 2 and 10ms to run this, even though we know for sure that it will always return an empty array. Could we short circuit this fetch call?

Is there any edge case, or reason why doing this could go wrong?

**Comment by StorytellerCZ** [comment]
That is a tough one. First of all, this is something that Grapher should address and it should short circuit. Having it in the core is questionable as this is something that the app should catch and I don't think we should provide fail saves for every potential pitfall that a developer can make as that would just increase the code base tremendously.

That being said, let's look at the fix for this:
```js
if (Object.keys(selector).length === 1 && selector._id?.$in?.length === 0) {
  // Now should we throw?
  throw new Meteor.Error('Empty array in _id $in lookup')
  // Or return null?
  return null
}
```

**Comment by filipenevola** [comment]
Hi @Floriferous I don't see why this should be implemented in Meteor.

This is a valid query that should create a valid cursor.

As Jan said it would be ok for Grapher to implement a short circuit in this case but not for Meteor.

**Comment by Floriferous** [comment]
I don't think we should patch `find`, but patching `fetch` sounds reasonable to me. What's the point in going to the database if we know for sure that the result will be an empty array?

**Comment by filipenevola** [comment]
I understand your point but that would introduce an unexpected behavior (of not accessing the database).

Wouldn't it be better if you patch your collections (for example using a [composer](https://github.com/quavedev/collections#composers)) to do this for you?
