### ISSUE TITLE
Using Accounts.resetPassword with enrollment is not working anymore

### ISSUE THREAD

**Issue by larswolter** [meteor/meteor#11600]
Using resetPassword throws an error, Invalid email [403] when used in the enrollment workflow.

The error is in
https://github.com/meteor/meteor/blob/721841ba900cae609da84a97938241874b39e07f/packages/accounts-password/password_server.js#L781

The reason field has been removed from services.password.xxx in Meteor 2.3.x But it is still used instead of `isEnroll`.

**Comment by StorytellerCZ** [comment]
@larswolter thanks for the notice! Looking into it now.

**Comment by StorytellerCZ** [comment]
@larswolter can you please check #11601 for the fix?

**Comment by larswolter** [comment]
Thanks @StorytellerCZ i tested the fix and it also works in my setup.

**Comment by StorytellerCZ** [comment]
Alright! I will release the patch now.
