### ISSUE TITLE
Error in 2.3.5 docs for node params for meteor run

### ISSUE THREAD

**Issue by olafthiele** [meteor/meteor#11606]
[Current docs](https://docs.meteor.com/commandline.html#meteorrun) refer to `SERVER_NODE_OPTIONS ` to be given as part of the meteor run command, but they should be provided via env options as [described here](https://forums.meteor.com/t/solved-how-to-provide-node-options-in-2-3-5/56551):

In Linux:

> SERVER_NODE_OPTIONS=--trace-deprecation meteor run

In Windows (PS):

> $env:SERVER_NODE_OPTIONS = '--trace-deprecation'
> meteor run

Thanks @robfallows for this information.

**Comment by olafthiele** [comment]
@filipenevola, thanks for the feedback. Didn't see the option to submit a PR that easily.

**Comment by filipenevola** [comment]
> @filipenevola, thanks for the feedback. Didn't see the option to submit a PR that easily.

If you scroll to the bottom of every doc page you see a link "Edit on GitHub" and then you can just click in the pencil on GitHub UI to suggest a change.
