### ISSUE TITLE
Meteor.http.call exception missing fields

### ISSUE THREAD

**Issue by alanning** [meteor/meteor#1160]
I believe the exception object is missing two fields:
- status
- message

Prior to Meteor v0.6.3, when an error was encountered, the error status and message could be obtained from the object returned from Meteor.http.call.

In v0.6.3 it seems that the only thing the exception object contains is a single field, 'stack', which is a string with the status and message included.  This makes it hard to obtain the status and message as they have to be parsed out.

Here is an example of the stringified exception object:

{"stack":"Error: failed [400] {   \"message\": \"Address already exists 'john@example.com'\" }\n    at Object.Future.wait (/Users/alanning/.meteorite/meteors/meteor/meteor/a33fcf6d8cef8486ffd4bce549645624fb23a0e3/dev_bundle/lib/node_modules/fibers/future.js:322:15)\n    at Object.Meteor.http.call (app/packages/http/httpcall_server.js:125:16)\n    at Object.Meteor.http.post (app/packages/http/httpcall_common.js:78:27)\n ...

The code to produce this is something like:

```
  try {
    Meteor.http.post(listUrl, {
      auth: Meteor.settings.email.auth,
      params: params
    })
  } catch (ex) {
    console.log(JSON.stringify(ex))
  }
```

**Comment by sonurajmca** [comment]
I am facing the issue to post the request over api
 my code is here 
         var options = {

                headers: {
                    "authorization": "Basic YmlndWFyZGluZTaG9ydHBhdGhJbmRpYQ==",
                    "content-type": "multipart/form-data",
                },
                data: {
                    'user_id': visitorWithoutQR.userId,
                    'lease_id': null,
                    'name': visitorWithoutQR.firstName + " " + visitorWithoutQR.lastName,
                    'company': visitorWithoutQR.company,
                    'email': visitorWithoutQR.email,
                    'citizen': null,
                    'country_code': null,
                    'notes': "Kiosk check in",
                    //'images': visitorWithoutQR.images,
                    'kiosk_setting_id': null,
                    'print_service_key': null,
                }
            }
            HTTP.call('POST', apiUrl, options, function (error, result) {
                if (error) {
                    console.log(error);
                } else
                    console.log('RESULT');
                console.log(result);
            });

and i am getting the error like below
  content: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n  <head>\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n   </h2>\n\t\t\t\t<br/>\n\t\t\t\t\t<p>If you need additional assistance, please contact us by:</p>\n\t\t\t\t\t<p><b>E-Mail:</b>             </div>\n\t        <div class="clear"></div>\n\t        <div id="footer">\n\t        </div>\n\n\t        <div id="status-container">\n\n\t        </div>\n\t      </div>\n\t    </div>\n  </body>\n</html>\n',
I20170531-21:59:20.886(5.5)?   headers:
I20170531-21:59:20.889(5.5)?    { server: 'nginx/1.8.1',
I20170531-21:59:20.893(5.5)?      date: 'Wed, 31 May 2017 16:29:20 GMT',
I20170531-21:59:20.894(5.5)?      'content-type': 'text/html',
I20170531-21:59:20.896(5.5)?      'content-length': '1909',
I20170531-21:59:20.897(5.5)?      connection: 'close',
I20170531-21:59:20.899(5.5)?      etag: '"592ebfbd-775"' },
I20170531-21:59:20.900(5.5)?   data: null }


please help
