### ISSUE TITLE
module.exportDefault is not a function

### ISSUE THREAD

**Issue by ocavue** [meteor/meteor#11617]
Hi. I'm a maintainer of an NPM package called `remirror`. One of all users found that the application crashes with `module.exportDefault is not a function` error when import `remirro` in meteor. 

Check the [origin issue](https://github.com/remirror/remirror/issues/1213) for detailed steps to reproduce it. I also prepared a [reproduction](https://github.com/issueset/remirror_meteor) if that can help.
 
---

- [x] The version of Meteor showing the problem. 
  Meteor 2.3.5
- [x] The last version of Meteor where the problem did _not_ occur, if applicable. 
  N/A
- [x] The operating system you're running Meteor on. 
  Ubuntu 18.04
- [x] The expected behavior.
  No error.
- [x] The actual behavior.
  `Uncaught TypeError: module.exportDefault is not a function`

**Comment by StorytellerCZ** [comment]
I guess we are both at a lost here :laughing: 
I'm going on a limb here, @zodern does anything comes to mind? We had this appear and disappear a few times in the past as far as I can tell: https://forums.meteor.com/t/module-exportdefault-is-not-a-function/54610?u=storyteller
Though it always seem to went away.

**Comment by StorytellerCZ** [comment]
OK, I have figured it out! It is the same issue as #11631 
I'm closing this issue in favor of #11631 to concentrate everything there.
