### ISSUE TITLE
Problems with minifier-js in Meteor 2.4

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor#11629]
I just upgraded an existing project to Meteor 2.4 which uses minifier-js@2.7.0

When creating a build, it is failing with the following error:

```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:Unexpected token: name
(package))
Source file: packages/iron_core/lib/iron_core.js  (258:29)
Line content: Iron.utils.debug = function (package) {

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:Unexpected token: name
(package))
Source file: packages/iron_core/lib/iron_core.js  (258:29)
Line content: Iron.utils.debug = function (package) {

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
```

[The line of code in question](https://github.com/iron-meteor/iron-core/blob/c782823607aefc732bd53ca6b3e2a923bb7efdd5/lib/iron_core.js#L258) is part of the Meteor package iron:router and is rather unremarkable:

`  Iron.utils.assert(typeof package === 'string', "debug requires a package name");`

**Comment by StorytellerCZ** [comment]
Yeah, that looks rather unremarkable. @vlasky co you have a quick reproduction?

**Comment by vlasky** [comment]
@StorytellerCZ this will reproduce the error:

```
meteor create --minimal minifiertest
cd minifiertest
meteor update --release 2.4
meteor remove static-html
meteor add blaze-html-templates
meteor add iron:router
meteor build --directory ../minifiertestbuild

```

**Comment by StorytellerCZ** [comment]
Having some issues with jQuery version resolution, in the meantime can you try with this PR: https://github.com/meteor/meteor/pull/11630

**Comment by vlasky** [comment]
Yes, iron:router has a dependency on the jQuery version that shipped with Meteor 0.9.2 - jquery@1.11.11.

This is due to the line `api.versionsFrom('METEOR@0.9.2');` in its package.js. It is annoying and I would want the various iron:router packages to be updated even just to fix this.

Anyhow, I accessed the above PR #11630 and copied the Meteor packages `minifier-js` and `standard-minifier-js` into the project's packages folder and this seems to have resolved the issue.

Strangely, copying `minifier-js` on its own was not enough. I had to copy `standard-minifier-js`  as well. Do you know why?

**Comment by StorytellerCZ** [comment]
That is strange, but to be on the safe side I will release `standard-minifier-js` along with `minifier-js` so that their versions align.

As for Iron Router, that is something for the community. I think the issue there is that none of the maintainers are responding.

**Comment by filipenevola** [comment]
Hi, `minifier-js@2.7.1` and `standard-minifier-js@2.7.1` are published.

A new `meteor update --release 2.4` should update these packages for you if you are already running Meteor 2.4.

**Comment by vlasky** [comment]
`meteor update --release 2.4` didn't update those packages in my existing Meteor 2.4 test project.

However, `meteor update --all-packages`  did.

**Comment by filipenevola** [comment]
Hmm, when I was updating atmosphere it updated without `--all-packages`.

Is everything working for you now @vlasky ?

**Comment by vlasky** [comment]
@filipenevola so far, so good.

**Comment by markdowney** [comment]
I'm still hitting this issue when using `meteor.nodeModules.recompile` on a private npm package (using yarn workspaces). This worked fine on 2.2 but seems to be broken in 2.4. Here's a reproduction repo:
https://github.com/markdowney/meteor-minify-repro

**Comment by filipenevola** [comment]
Hi @markdowney what is the error that you are getting? Could you open a specific issue for your problem?

It seems to be a different one as this one here is solved.

**Comment by markdowney** [comment]
The error seems pretty similar (although this one might be specific to recompiling npm packages). I'll open a different issue.

```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error
(SyntaxError:Unexpected token: operator (<))
Source file: node_modules/mypackage/index.js  (6:4)
Line content:     <div>My Component</div>

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:66:11)
```
