### ISSUE TITLE
Sorry, this project uses Meteor 1.12, which is not installed and could not be downloaded. 

### ISSUE THREAD

**Issue by fengzi2016** [meteor/meteor#11625]
After change the /etc/hosts for warehouse.meteor.com, but It'progress is still 0%
![image](https://user-images.githubusercontent.com/22490787/132674495-459a28bb-61b6-4769-8e4b-fbdf9fe4d586.png)

**Comment by StorytellerCZ** [comment]
Hi @fengzi2016 we will need a bit more information. Are you on Windows? Are you behind a corporate proxy or in China?

**Comment by fengzi2016** [comment]
I am in China，and use Mac 
my question is when I run with  METEOR@2.3.6 ，it starts to download static-html@1.3.0, but its progress is always 0% or downloaded 5% then go to 0% again, I need some help.

![image](https://user-images.githubusercontent.com/22490787/132695382-0283f6b0-77e3-435c-9124-32c4f52553a9.png)

**Comment by renanccastro** [comment]
Hi, @fengzi2016 .
We are not experiencing any outage or active blocks in our CDNs that provide downloads, at this moment.

As the answer in your original issue:
https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/issues/154

I do recommend you use another VPN, if that is the case.

**Comment by fengzi2016** [comment]
hello，my VPN can connect to your service, but can't download successfully, even it download 10% then down to 0%  again;
![image](https://user-images.githubusercontent.com/22490787/132783327-5400da0c-ec8d-48bc-a6cf-258dbd8a8bd6.png)
This is not caused by VPN

**Comment by fengzi2016** [comment]
Why did it download 10% and then go back to 0% instead of starting at 11%?

**Comment by fengzi2016** [comment]
when downloading meteor-tool@1.12.0, Its download progress is always 0%
![image](https://user-images.githubusercontent.com/22490787/132784133-8e585ab4-a56f-4831-ae30-7824dbdfa2cb.png)
when downloading static-html@1.3.0, even if you download 100%, you'll go back to 0% and start again

**Comment by fengzi2016** [comment]
![image](https://user-images.githubusercontent.com/22490787/132784446-e00966fc-431b-4a1b-81cc-7e50b2ceafbc.png)
Does the red box mean it's downloading? But it always comes back to 0%
