### ISSUE TITLE
Meteor 2.4 - chalk npm package incompatible with IE11, makes app crash on modules.js load

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11635]
After upgrading our app to meteor 2.4, it no longer loads in IE11 because one of the bundled npm packages in modules.js causes a syntax error which prevents further loading.

This time it seems to be "chalk". I’m not sure exactly which ecmascript feature that is used here and that is incompatible.

![image](https://user-images.githubusercontent.com/2690254/134184846-c0431c01-a2c8-4ccc-9729-fd749084b739.png)

![image](https://user-images.githubusercontent.com/2690254/134184910-7275338b-3171-4b50-8fde-af6784562062.png)

**Comment by StorytellerCZ** [comment]
We have run into this problem during the RC stage and me and @renanccastro worked on a fix and all the tests and manual testing have passed, so this is super strange to me. I will look into this again as the recompiling for the legacy is what should have happened already.
@perbergland can you provide us any additional details about your setup with IE11 that might help. Thanks!

**Comment by perbergland** [comment]
I just use a vanilla IE10 on Win10 with browserstack.

I upgraded my app from 2.3.5 without any attempt to clean out old builds or anything else in .meteor/local

**Comment by StorytellerCZ** [comment]
Interesting. :thinking: I think there might be something to your theory. Once I'm back on my Windows I will give it a try.

**Comment by renanccastro** [comment]
Hi @perbergland 
can you please try the package logging@1.3.1 ?
It should have been fixed in this version!

**Comment by perbergland** [comment]
Yes the updated logging package fixes the problem and the workaround is no longer necessary
