### ISSUE TITLE
Email.send silent fail

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#11640]
Email.send was failing silently because I failed to provide `from` property
```js
// process.env does contain MAIL_URL
const options = {
			to: user.emails[0].address,
			subject: 'test',
			html: `
      <!doctype html>
        <html lang="en">
          ...
        </html>
      `,
		};
		Meteor.defer(() => {
			Email.send(options);
		});
```
And in the [docs](https://docs.meteor.com/api/email.html#Email-send) `from` is considered to be a required field, so I was thinking maybe if we add a little `check` statement inside Email.send method to check for important properties and ensure they're of the correct type.
https://github.com/meteor/meteor/blob/devel/packages/email/email.js#L213

Just like how it's done in [validated-methods](https://github.com/meteor/validated-method/blob/master/validated-method.js#L7).

I guess the question is which properties should we check for? Given my use case, I'd say we can start with `from` and see if we need to add more later on.

Side note: Also, shouldn't validated-methods be moved into meteor repo similar to other packages currently being moved?

**Comment by StorytellerCZ** [comment]
@harryadel Good catch, I'll see about adding it in for 2.5. As for moving packages that is done in steps and right now focuses on npm packages.

**Comment by djroxx2000** [comment]
Can I take this up? As far as I understand, it only requires an import and a line to check 'from' to be a valid String with regex mail validation. Should I also add a todo comment for checking more fields? Also, I see that the check function Match patterns don't accept regex as a pattern. Should that be added or keeping regex separate was intentional?

**Comment by djroxx2000** [comment]
@StorytellerCZ I have created the pull request here [#11678](https://github.com/meteor/meteor/pull/11678). I didn't use the check function since the regex check for null and undefined as well. Please let me know if any other changes required here.
