### ISSUE TITLE
Problem downloading Meteor old version packages - while downloading.......certificate is invalid

### ISSUE THREAD

**Issue by ybico** [meteor/meteor#11658]
While creating a meteor project using 1.4.4.6 version, I get 62 warnings saying:

While downloading xyx@1.2.3....:
error: certificate has expired
How can I solve this problem?

![terminal-screenshot](https://user-images.githubusercontent.com/2661994/135615096-1179e934-1937-4e4b-a182-04ddd6c7610c.png)
My PC's date and time is up to date
Ubuntu 20.04

**Comment by StorytellerCZ** [comment]
This is an issue affecting all Meteor releases before 1.9. There is a workaround for this. Please see:
https://docs.meteor.com/expired-certificate.html
and
https://forums.meteor.com/t/certificate-errors-in-meteor-commands-before-v1-9-only/56740?u=storyteller
