### ISSUE TITLE
MongoError: Index with name: username_1 already exists with different options

### ISSUE THREAD

**Issue by kentonv** [meteor/meteor#11666]
Starting with Meteor 2.4, the `_ensureIndex()` method has different behavior: Previously, if the index already existed, regardless of options, then the call did nothing. Now, if the options differ, then the call throws an exception.

For new apps, the new behavior is clearly preferable.

Unfortunately, with Sandstorm, we've discovered that many of Meteor's own index-creation calls -- including the ones in accounts-base -- fail when run against older databases. It appears that Meteor used to create indexes with an option `"safe": true`, but no longer does. Mongo sees this as a change in options, and so all of Meteor's own calls to `createIndex()` fail if the indexes were originally created using a sufficiently old version of Meteor. This means the app cannot start unless the user manually goes and deletes all these indexes.

Note that the "safe" option was removed from Mongo quite some time ago, which may mean that users don't see this issue unless they are using old versions of Mongo. Sandstorm is, sadly, stuck on Mongo 2.6. The reason for this is, updating to a newer version of Mongo apparently requires some manual intervention to migrate data. Sandstorm is installed on thousands of individual users' machines where it has been auto-updating for over 7 years. Many of those users are non-technical, and we cannot ask them to take manual action to update their database. In order to update, we would need to build a fully-automated Mongo migration that happens in the background of live servers, which seems like a large engineering effort that we don't have time for.

I am not sure what to do about this. I think ideally, instead of failing when options differ, we'd drop and recreate the index with the correct options. But we need Meteor itself to do this with its own indexes. We have no way of knowing the full list of indexes that may need to be rebuilt, so it's hard for me to work around this.

**Comment by kentonv** [comment]
In one particularly-old Sandstorm instance I looked at, I found the following indexes on Meteor.users had `"safe": true`:

`username_1`, `emails.address_1`, `services.resume.loginTokens.hashedToken_1`, `services.resume.loginTokens.token_1`, `services.resume.haveLoginTokensToDelete_1`, `services.resume.loginTokens.when_1`, `services.github.id_1`, `services.google.id_1`

**Comment by StorytellerCZ** [comment]
Wow, that is a really old version of MongoDB. I don't even see the `safe` option in MongoDB 2.6 docs. Looking through recent commits I don't see any change that would indicate that we had changed anything about setting index options, so it might be some old MongoDB driver default. :thinking:

**Comment by kentonv** [comment]
Yes, it seems like the Mongo driver used to set "safe" by default, or something. AFAICT this option can't even be set explicitly with the current API / driver -- it's ignored when I try to set it, which unfortunately makes it kind of hard to reproduce the problem outside of production. Note that I'm not even 100% sure that the "safe" option is the problem, but it's the only apparent difference I can see between old indexes and new ones.

I think what would work for me is if there were some flag or environment variable or something that we could set that would cause createIndex and _ensureIndex to automatically delete and recreate indexes when the options differ, and log a warning to stderr.

**Comment by ocdtrekkie** [comment]
It looks like the "safe" option was removed in #4340 (in 2015) after being added in 2012. So I'd gather any Meteor app servers spun up in those three years or so, and still running, should have this problem?

**Comment by kentonv** [comment]
@ocdtrekkie Good find.

What's unclear to me is, if someone is _not_ stuck on Mongo 2.6 like we are, but rather is using a newer version of Mongo, will they still hit this problem? Or do newer versions of Mongo ignore / drop this flag (which apparently never meant anything in the first place)?

**Comment by menewman** [comment]
> It looks like the "safe" option was removed in #4340 (in 2015) after being added in 2012. So I'd gather any Meteor app servers spun up in those three years or so, and still running, should have this problem?

> What's unclear to me is, if someone is not stuck on Mongo 2.6 like we are, but rather is using a newer version of Mongo, will they still hit this problem? Or do newer versions of Mongo ignore / drop this flag (which apparently never meant anything in the first place)?

One more data point: We have a Meteor application that's been running since (I think) 2014, and we have indeed seen this type of index error on upgrade to Meteor 2.4. Our current MongoDB version is fairly recent at 4.4+.

For conflicts like this in our own code, we switched from using `_ensureIndex` (or `createIndex`) to a monkey-patched `ensureIndex` method that catches this error and removes/recreates the index with updated options if needed.

(This monkeypatch is available in this package: https://github.com/CodeSignal/meteor-protomongo)

Unfortunately, that doesn't really help if the index is being added in core Meteor or Accounts package code, where we don't have control over the index creation. To fix this, we had to resort to the manual fix described in the original issue above: removing the index from the DB before activating the new version so that it can be created again with the right options.

Perhaps a similar tweak could be used within Meteor/Accounts code to make sure conflicting options are overwritten when creating these core indexes?

**Comment by andreasheim** [comment]
Ran into this issue as well. Just want to point out it may be more important with which version (of Mongo or Meteor) the app was created, not what it is currently on. Our app is on Mongo 4, and I was unable to deploy with Meteor 2.4 or 2.5. 

Interestingly, it's not an issue locally, with a recent prod backup, nor on our staging env, which was created about a year ago with a prod Mongo backup.

**Comment by kentonv** [comment]
@StorytellerCZ it appears this affects everyone who has Meteor apps that have been running continuously for many years, even if their database is up-to-date.

Can Meteor add some code to automatically detect this problem and work around it, by either fixing the flags on the index or rebuilding it? It's very hard for us to do this at the application level since the failure happens at Meteor startup before the app gets a chance to run any code.

**Comment by StorytellerCZ** [comment]
@kentonv I'll try to figure out something. Could you give me a sample how the index looks like in MongodDB when inspected so that I could replicate it locally for testing?
I'm thinking that we would detect this specific index, write out a warning that it should be fixed manually, but then make sure that the app continues building and working. Thoughts?

**Comment by kentonv** [comment]
@StorytellerCZ as an example, I have this index on db.users:

```
	{
		"v" : 1,
		"key" : {
			"services.resume.loginTokens.token" : 1
		},
		"unique" : true,
		"ns" : "meteor.users",
		"name" : "services.resume.loginTokens.token_1",
		"safe" : true,
		"sparse" : 1
	}
```

AFAICT the `"safe": true` part causes the problem. All my very-old indexes have this flag.

**Comment by jthomaschewski** [comment]
I do experience this issue in an older Meteor App after upgrading to v2.4.
MongoDB `v4.4.4` is used, so no old 2.x version - the DB was started with an old Meteor & Mongo version though many years ago.
Don't see the `safe` flag though when inspection the indexes using `db.users.getIndexes()`.


Apparently this is now also hitting Rocket.Chat users as well (me included) after they upgraded to latest Meteor: https://github.com/RocketChat/Rocket.Chat/issues/24347

Not sure if this is _Impact:few_ after all - more like _Impact:long_time_users_.

Hope a fix can be found soon.
It would already help if this could be transformed into a warning instead of a fatal error with server crash.

**Comment by StorytellerCZ** [comment]
@shadoath that is the fastest option if you can do it, will fix any other old indexes as well.

**Comment by ocdtrekkie** [comment]
The biggest problem is there's no way to automate that fix from a Meteor-built app, I believe, which means deploying an upgrade to Meteor 2.4 will break people's servers.

**Comment by jaredloson** [comment]
I'm trying to deploy a v2.6 app (hosted on Galaxy, connected to MongoDB Atlas cluster using v5.0.6). I'm getting this error during deployment:

```
MongoServerError: not authorized on [DB NAME] to execute command { createIndexes: "users", indexes: [ { name: 
"username_1", key: { username: 1 }, unique: true, sparse: true } ], writeConcern: { w: "majority" }, lsid: { id: UUID("75294e64-
b9ca-46ae-9fc9-92223c27056b") }, $clusterTime: { clusterTime: Timestamp(1644590097, 1), signature: { hash: BinData(0, 
EAF9821C7A5DB8CC9FF8FD8D7BE5BF152B2C74A6), keyId: 7063442595833184260 } }, $db: "[DB NAME]" }
```

Couple notes:
- I spun up a test v4.4 database cluster from a backup on my production database cluster. Then I upgraded it to v5. Then deployed the Meteor 2.6 version of the app and encountered the error.
- I deleted the indexes on the users collection before deploying

**Comment by WilliamKelley** [comment]
@ocdtrekkie Couldn't you do `Meteor.users.rawCollection().dropIndexes()`? I don't see why not. That's automatable from code.

The biggest warning is that rebuilding can take time given collection size, and if any indexes are set one-off and not ensured/re-created on every startup, those will have to be migrated manually.

**Comment by kentonv** [comment]
@WilliamKelley The problem is that Meteor crashes at startup before any application code runs, so there's no opportunity for the application to call `dropIndexes()`.

**Comment by WilliamKelley** [comment]
> @WilliamKelley The problem is that Meteor crashes at startup before any application code runs, so there's no opportunity for the application to call `dropIndexes()`.

Understood, sorry I should've recognized that from the previous comments. 

I will attempt a fix. I'll try to recreate a similar index rejection (not sure i can recreate an index with legacy, unavailable options) and base the fix off that. The scope will be just the creation of indexes within Accounts.

To gather as much info as I can:

- I'm guessing it crashes because it's an unhandled promise rejection? The only direct error message i can see is from the RocketChat link, but the error class isnt clear to me.
- Do you have a sample legacy index information you can provide me? There's one in the RocketChat error log, but the more the merrier.

**Comment by champel** [comment]
@WilliamKelley ,example of error logs, after upgrading to `2.6.0`:

```
=> Started proxy.                             
=> Started MongoDB.                           
W20220212-18:25:13.013(1)? (STDERR) /Users/champel/.meteor/packages/meteor-tool/.2.6.0.6ytru8.6uhtx++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20220212-18:25:13.041(1)? (STDERR)                                             throw(ex);
W20220212-18:25:13.041(1)? (STDERR)                                             ^
W20220212-18:25:13.043(1)? (STDERR) 
W20220212-18:25:13.044(1)? (STDERR) MongoServerError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, key: { services.resume.haveLoginTokensToDelete: 1 }, name: "services.resume.haveLoginTokensToDelete_1", sparse: true }, existing index: { v: 2, key: { services.resume.haveLoginTokensToDelete: 1 }, name: "services.resume.haveLoginTokensToDelete_1", sparse: 1 }
W20220212-18:25:13.045(1)? (STDERR)     at MessageStream.messageHandler (/Users/champel/.meteor/packages/npm-mongo/.4.3.1.pbd1ac.uq76k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:462:30)
W20220212-18:25:13.046(1)? (STDERR)     at MessageStream.emit (events.js:400:28)
W20220212-18:25:13.046(1)? (STDERR)     at processIncomingData (/Users/champel/.meteor/packages/npm-mongo/.4.3.1.pbd1ac.uq76k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
W20220212-18:25:13.047(1)? (STDERR)     at MessageStream._write (/Users/champel/.meteor/packages/npm-mongo/.4.3.1.pbd1ac.uq76k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
W20220212-18:25:13.048(1)? (STDERR)     at writeOrBuffer (internal/streams/writable.js:358:12)
W20220212-18:25:13.048(1)? (STDERR)     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
W20220212-18:25:13.049(1)? (STDERR)     at Socket.ondata (internal/streams/readable.js:731:22)
W20220212-18:25:13.050(1)? (STDERR)     at Socket.emit (events.js:400:28)
W20220212-18:25:13.050(1)? (STDERR)     at addChunk (internal/streams/readable.js:293:12)
W20220212-18:25:13.051(1)? (STDERR)     at readableAddChunk (internal/streams/readable.js:267:9)
W20220212-18:25:13.052(1)? (STDERR)     at Socket.Readable.push (internal/streams/readable.js:206:10)
W20220212-18:25:13.052(1)? (STDERR)     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
W20220212-18:25:13.055(1)? (STDERR)   ok: 0,
W20220212-18:25:13.056(1)? (STDERR)   code: 85,
W20220212-18:25:13.057(1)? (STDERR)   codeName: 'IndexOptionsConflict',
W20220212-18:25:13.058(1)? (STDERR)   '$clusterTime': {
W20220212-18:25:13.059(1)? (STDERR)     clusterTime: Timestamp { low: 5, high: 1644686712, unsigned: true },
W20220212-18:25:13.063(1)? (STDERR)     signature: {
W20220212-18:25:13.063(1)? (STDERR)       hash: Binary {
W20220212-18:25:13.064(1)? (STDERR)         sub_type: 0,
W20220212-18:25:13.064(1)? (STDERR)         buffer: Buffer(20) [Uint8Array] [
W20220212-18:25:13.064(1)? (STDERR)           0, 0, 0, 0, 0, 0, 0,
W20220212-18:25:13.066(1)? (STDERR)           0, 0, 0, 0, 0, 0, 0,
W20220212-18:25:13.066(1)? (STDERR)           0, 0, 0, 0, 0, 0
W20220212-18:25:13.068(1)? (STDERR)         ],
W20220212-18:25:13.070(1)? (STDERR)         position: 20
W20220212-18:25:13.070(1)? (STDERR)       },
W20220212-18:25:13.072(1)? (STDERR)       keyId: 0
W20220212-18:25:13.073(1)? (STDERR)     }
W20220212-18:25:13.073(1)? (STDERR)   },
W20220212-18:25:13.073(1)? (STDERR)   operationTime: Timestamp { low: 5, high: 1644686712, unsigned: true }
W20220212-18:25:13.074(1)? (STDERR) }
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

Examples of indexes affected: `username_1`, `emails.address_1`, `services.resume.loginTokens.hashedToken_1`, `services.resume.loginTokens.token_1`

**Comment by champel** [comment]
I don't like the idea of removing manually the indexes, but, in case there is not a better solution before the Atlas upgrade, this is my workaround to avoid removing all indexes over the `users` collection:

```
db.users.dropIndex("username_1")
db.users.dropIndex("emails.address_1")
db.users.dropIndex("services.resume.loginTokens.hashedToken_1")
db.users.dropIndex("services.resume.loginTokens.token_1")
db.users.dropIndex("services.resume.haveLoginTokensToDelete_1")
db.users.dropIndex("services.resume.loginTokens.when_1")
db.users.dropIndex("services.password.reset.when_1")
db.users.dropIndex("services.email.verificationTokens.token_1")
db.users.dropIndex("services.password.reset.token_1")
```

**Comment by WilliamKelley** [comment]
@champel Thanks that's helpful. Do you know what version of Meteor your project was first created on?

**Comment by kentonv** [comment]
@WilliamKelley Meteor 0.8.0 for me.

**Comment by champel** [comment]
@WilliamKelley , my finished upgrades file starts like this:

```
notices-for-0.9.0
notices-for-0.9.1
0.9.4-platform-file
...
```

I guess a `0.8.x` too?

**Comment by ocdtrekkie** [comment]
So it looks like this should be fixed as of Meteor 2.7.2? Is that correct?

**Comment by StorytellerCZ** [comment]
@ocdtrekkie there will be a better error message and an option to quickly re-create the offending indexes.

**Comment by denihs** [comment]
Hey @ocdtrekkie, you should already be able to test it. We released a beta version yesterday: https://github.com/meteor/meteor/pull/11999.

You can update your project with `meteor update --release 2.7.2-beta.0`.

**Comment by denihs** [comment]
This should now be fixed in version 2.7.2: `meteor update --release 2.7.2`.

So I'm closing it now.

**Comment by neopostmodern** [comment]
I just observed this with an app that had already been updated to 2.7.2 and I tried to deploy now – I did not get a better error message (or any options).
(Fortunately I could simply do https://github.com/meteor/meteor/issues/11666#issuecomment-1036646355)

**Comment by theosp** [comment]
@neopostmodern Same here.

**Comment by StorytellerCZ** [comment]
@denihs
