### ISSUE TITLE
HMR not working consistently depending on file structure

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#11699]
Here's a reproduction of a HMR issue where it does not work the same way depending on where your code is located in the file-structure.

In one instance, all the code is in a single file, in the other instance, the code is split between 2 files, and some of the changes are not reflected until after you refresh the page.

Reproduction is here: https://github.com/Floriferous/meteor-pdf-hmr

**Comment by zodern** [comment]
Thanks @Floriferous for the reproduction. I see the same behavior with it.

**Comment by JanMP** [comment]
HMR quit working for me after update to Meteor 2.5
Can't say if it's depending on location of code (have not found module with working HMR in the project).

**Comment by ricaragao** [comment]
I'm seeing the same behavior with Meteor 2.5. In the version 2.4.1 it works fine. I'm using Blaze with files directly in the client folder. When I change a JS file, the app doesn't reload as before. And HMR isn't doing nothing, just in HTML template files.

**Comment by ghybs** [comment]
Hi @Floriferous 

It seems to me that the bug you pinpoint is actually the one that is targeted by PR https://github.com/meteor/meteor/pull/11795, i.e. failure to fallback to HCP when HMR cannot be used.

In your reproduction repo, reload fails within the `react-pdf/renderer/PDFViewer` component
```jsx
    <PDFViewer>
      <Pdf />
    </PDFViewer>
```

https://github.com/Floriferous/meteor-pdf-hmr/blob/76e68d30ddf4b1684c777d32e1900e3e85ec343c/imports/ui/App.jsx#L12-L14

If I am not mistaken, Meteor build does not perform Tree Shaking yet, so you end up with the entire renderer exports, which contain non React components, hence the module is not eligible to HMR.

Then in such case, Meteor in development mode should use Hot Code Push instead when a change affects such module, but fails to do so.

**Comment by zodern** [comment]
Meteor and its react refresh integration seem to be working correctly. This is a bug in react-pdf: https://github.com/diegomura/react-pdf/issues/1350.

If you want Meteor to use hot code push when you modify these types of files, you can add this to the files, though it will also disable HMR for any of the file's dependencies
```
if (module.hot) {
  setTimeout(() => module.hot.decline());
}
```

The timeout is needed to prevent react-fast-refresh from overriding `module.hot.decline()` (https://github.com/meteor/meteor/pull/11801)

**Comment by zodern** [comment]
@JanMP and @ricaragao the bug you found should be fixed with https://github.com/meteor/meteor/pull/11795
