### ISSUE TITLE
Installation of Meteor fails on M1 Max

### ISSUE THREAD

**Issue by rglover** [meteor/meteor#11729]
Following the instructions [here](https://docs.meteor.com/install.html) for installation on M1 and getting the error `The current architecture is not supported: arm64`

 I've attempted to use both the standalone `npm install -g meteor` command as well as the `arch -x86_64 npm install -g meteor` command and both return the same error.
 
 I also attempted to use the legacy curl URL which gave me the error `Only 64-bit Intel processors are supported at this time`.

OS: macOS Monterey 12.0
CPU: Apple M1 Max

**Comment by lmf-git** [comment]
Sigh

**Comment by filipenevola** [comment]
Meteor works on M1 now as you can read [here](https://blog.meteor.com/meteor-2-5-1-with-native-mac-m1-support-fb1c4b6990b5).
