### ISSUE TITLE
Feature request: add a method 'refresh' to Template

### ISSUE THREAD

**Issue by mcasimir** [meteor/meteor#1172]
I miss a way to re-trigger the rendering of a template. Consider this example: 

`tax_line_fields.html`

``` html
<template name="tax_line_fields">
{{#with tax_line}}

  <form action="javascript:void(0)">
      <input type="text" name="name" value="{{name}}" />
      <input type="checkbox" name="fixed" value="true" {{#if fixed}}checked="checked"{{/if}} />

      <input type="text" name="amount" value="{{amount}}" />
      <label>{{#if fixed}}
      €
      {{else}}
      %
      {{/if}}</label>

      <button>Commit</button>
  </form>

{{/with}}
</template>
```

`tax_line_fields.coffee`

``` coffee
Template.tax_line_fields.events "change": (e, t) ->
  obj = form2js t.find("form")
  _.extend(@, obj)
  # re-render the template ..but how? 
```

I wish the template updates itself when i check/uncheck the checkbox. I don't want to hit the database before the form is submitted, so i bind to `change` event and then i use `form2js` to merge updated values in the context.

So it's almost done.. but i miss a way to re-trigger the rendering of the template.

What about `t.refresh()`?

**Comment by weeger** [comment]
+1
