### ISSUE TITLE
Meteor CRASHES with React UI when importing a component folder that has an `index.tsx` and `index.css`

### ISSUE THREAD

**Issue by IanChok** [meteor/meteor#11742]
### Bug Report 
- The **app crashes** when importing a folder component that contains a `index.tsx` and `index.css` for a _React_ frontend with _typescript_.
- For e.g.,
![image](https://user-images.githubusercontent.com/33184246/139570148-6a955cf4-fda6-4cdc-9d9f-19b96efe3e67.png)
![image](https://user-images.githubusercontent.com/33184246/139570198-9cd19a60-b264-4b51-b659-6d3553b2bb05.png)
![image](https://user-images.githubusercontent.com/33184246/139570178-18901448-301c-4e84-9c67-335f04521a88.png)

- [This repo](https://github.com/IanChok/meteordebug) demonstrates the behavior (very minimal, created with `meteor create --typescript new-typescript-app`)
   - Steps to reproduce:
      - Simply `git pull` this repo
      - Run `meteor run`
      - Open `localhost:3000` in browser and look at the console logs.  
      - In _imports/ui/Component_, if you rename the `index.css` file to something else, such as `indexx.css` the app then no longer crashes

**Expected Behaviour**
- Be able to import a React component such as `import Component from './Component'`, with the _Component_ folder containing both a _index.tsx_ and _index.css_ file alongside eachother

Meteor version: 2.4
OS: Fedora 34 KDE 5.22

**Comment by nick-gudumac** [comment]
This issue has been discussed before:
https://github.com/meteor/meteor/issues/10708

It's expected behavior and probably won't be fixed.

**Comment by filipenevola** [comment]
Hi, as discussed in #10708 this is the expected behavior and it's hard to have a different behavior as without extension we would need to always prioritize a specific extension.

So unless we come up with a better solution there is nothing to do here.
