### ISSUE TITLE
Undocumented behavior when using async functions for autorun callbacks

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#11747]
I have been mixing `async` functions with Meteor for quite some time.  I encountered an issue today that was new for me.

I have an example where I am querying a collection intermixed with an `async` request to another system that does not reactively rerun on changes to the `users` collection.
Example 1 - changes to the user collection **will not** rerun this autorun:
```javascript
  Tracker.autorun(async function() {
    let asyncData = await  asyncDataFunction();
    let users = Meteor.users.find({}).fetch();
  });
```

However, if I simply change the order so there are no `async` calls prior to the reactive call to `Meteor.users.find` then the autorun will work as expected.
Example 2 - changes to the user collection **will** rerun this autorun:
```javascript
  Tracker.autorun(async function()  {
    let users = Meteor.users.find({}).fetch();
    let asyncData = await  asyncDataFunction();
  });
```

I believe `Meteor` cannot create a reactive dependency after the branching required by a Promise (essentially, under the covers this is like putting the reactive dependency in a Promise callback function). Maybe it is fixable?

More likely I assume this is "expected" behavior that cannot be "fixed". If so, this may be worth documenting in the Tracker documentation?  Here is a new proposed section.

## Tracker.autorun and async callbacks
`Tracker.autorun` can accept an `async` callback function.  However, to preserve the reactivity of the callback function all reactive statements must occur before any functions that return a promise.  Reactive functions after any Promise callbacks will fail to rerun the function.

[I could add the 2 examples above to belabor the point.]

**Comment by denihs** [comment]
Hi @brucejo75, are you able to provide reproduction? 

A repository with a clean project (as explained [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)) just with some of these scenarios that you mentioned.

**Comment by brucejo75** [comment]
Repro: https://github.com/brucejo75/11747-async-autorun

**Comment by brucejo75** [comment]
@denihs, so what do you think?  Should I just generate a PR for the docs?

**Comment by filipenevola** [comment]
Hi @brucejo75, yes, I believe a PR for the docs is the best solution in this case.

I have faced this same situation when working in the PR to implement async API for our Mongo package.

**Comment by brucejo75** [comment]
Submitted #11784
