### ISSUE TITLE
Subscription to users collection not returning the services object

### ISSUE THREAD

**Issue by pisacode** [meteor/meteor#11753]
After upgrading meteor from 2.2 to 2.5 we are facing a very intereting bug. When we make a subscription to users collection with 

```
Meteor.publish('app', function app() {
//users.services is not an empty object
  return [
    Meteor.users.find(
      { _id: this.userId },
      {
        fields: {
          emails: 1,
          profile: 1,
          services: 1,
          addresses: 1,
          profilePicture: 1,
        },
      },
    ),
  ]
})
```

`services` field always goes as empty object to the client. 

```
export default withTracker(() => {
  const subscription = Meteor.subscribe('app')
  const user = Meteor.users.findOne({ _id: Meteor.userId() }),

//user.services is an empty object
  return {
    loading: !subscription.ready(),
    user
  }
})(Profile)

```

What could be the reason for this difference between client and server values? 

Many thanks

**Comment by filipenevola** [comment]
By default, Meteor omits sensitive fields from the user default publication.

You can use https://github.com/meteor/meteor/blob/dae7af832d08a8b19384ac19aa5a5a9b6b005e55/packages/accounts-base/accounts_common.js#L125 to change this behavior.
