### ISSUE TITLE
Use of createIndex instead of ensureIndex fails on older indexes with `safe: true`

### ISSUE THREAD

**Issue by brianlukoff** [meteor/meteor#11750]
In this PR (https://github.com/meteor/meteor/pull/11556), Accounts started using `createIndex` instead of `ensureIndex` for indexes on `username`, `emails.address`, etc. The problem is that older Meteor apps (created prior to https://github.com/meteor/meteor/pull/4340) have many indexes created with the `safe: true` option (including important indexes like the unique constraint on `emails.address`). But upgrading to Meteor 2.4 -- which uses `createIndex` in place of `ensureIndex` -- fails on startup, because `createIndex` fails when an existing index with the same keys already exists but with `safe: true`.

For example, here's the underlying command that Accounts tries to run on startup:
````
> db.users.createIndex({'emails.address':1}, { unique: true, sparse: true });
{
	"ok" : 0,
	"errmsg" : "Index with name: emails.address_1 already exists with different options",
	"code" : 85,
	"codeName" : "IndexOptionsConflict"
}
````

The result is that it's impossible to upgrade to Meteor 2.4 or higher without manually dropping any existing indexes with `safe: true` and letting Accounts recreate them on startup. This isn't a problem in a development environment, but on a production database it would require either downtime or operating dangerously without a unique constraint on `emails.address` between the time it is dropped and recreated without `safe: true`.

Thanks to @StorytellerCZ for figuring this out!

**Comment by menewman** [comment]
Potentially a duplicate of #11666?

**Comment by brianlukoff** [comment]
Yes - thanks!

**Comment by WilliamKelley** [comment]
@brianlukoff I'm trying to get more, exact information to write a non-manual fix for this. If you haven't manually dropped the indexes yet, can you paste the direct output of `db.users.indexInformation()`? Or let me know the version of Meteor your project was first created on so I can pin down a reproduction? Thanks

**Comment by brianlukoff** [comment]
Thanks for working on this -- happy to help! That doesn't seem to work in the Mongo console though -- I am getting `uncaught exception: TypeError: db.users.indexInformation is not a function`. I believe we started with Meteor 1.1.0.1.

**Comment by WilliamKelley** [comment]
Sorry, that is a driver api. I think `db.users.getIndexes()` should work. Thanks for the reply and info

**Comment by brianlukoff** [comment]
Got it -- no problem. Is there an email address I can send to you privately (or can I send to you on the Meteor Slack)?

**Comment by WilliamKelley** [comment]
Meteor slack works, account has my same name

**Comment by brianlukoff** [comment]
Thanks! Just sent to you.
