### ISSUE TITLE
Minification issue with flow-router

### ISSUE THREAD

**Issue by brianlukoff** [meteor/meteor#11756]
At some point post-2.3.4, the minification process of JS files seems to have broken in some way. To reproduce, create a plain app and add `kadira:flow-router`:

```
meteor create repro
cd repro
meteor add kadira:flow-router
meteor run --production
```

Then look at the minified source code:

<img width="417" alt="Screen Shot 2021-11-11 at 3 40 46 PM" src="https://user-images.githubusercontent.com/518013/141388904-6a3235af-1ed3-426a-b24b-723d8ceefa14.png">

Compare this to the actual function -- the minification seems to have dropped the last part of `doRedirect`!

https://github.com/kadirahq/flow-router/blob/master/client/triggers.js#L91

**Comment by brianlukoff** [comment]
I think it's a bug in terser's `evaluate` option (possibly https://github.com/terser/terser/issues/837) and that we can avoid by adding `evaluate: false` to the terser `compress` options -- I've created this pull request: https://github.com/meteor/meteor/pull/11758

**Comment by filipenevola** [comment]
Published minifier-js@2.7.2.

**Comment by brianlukoff** [comment]
I'm having trouble getting this updated version to be used by Meteor. My `versions` file is now showing 2.7.2 in use, but it seems to be using an older version when actually minifying the code (since run into the same problem that started this issue). But if I add `standard-minifier-js` to my app's `packages` directory (i.e., from a checkout), then Meteor does seem to use 2.7.2 and minification works as expected. I'm not sure what I am missing here?

**Comment by filipenevola** [comment]
@brianlukoff I published the `standard-minifier-js` now as well.

Could you check if this solves the problem?

**Comment by brianlukoff** [comment]
Thanks! I'm not able to update to 2.7.2 though -- getting the following when I try to put `@2.7.2` in `packages`:

```
While selecting package versions:
error: No version of standard-minifier-js satisfies all constraints: @2.7.2, @=2.7.1, @~2.7.1
Constraints on package "standard-minifier-js":
* standard-minifier-js@2.7.2 <- top level
* standard-minifier-js@=2.7.1 <- top level
* standard-minifier-js@~2.7.1 <- top level
```

**Comment by filipenevola** [comment]
@brianlukoff maybe you still have the local copy?

Or are you running from a checkout without pulling devel?

**Comment by brianlukoff** [comment]
Oops -- you are right -- forgot to remove my local copy. Using `standard-minifier-js@2.7.2` fixed it -- thanks!

**Comment by filipenevola** [comment]
We need to find another fix for this problem.

As I had to revert this fix in 2.7.3.

https://github.com/meteor/meteor/issues/11775#issuecomment-976902874

**Comment by afrokick** [comment]
@brianlukoff There is recommended flow-router fork created by @dr-dimitru 

`meteor add ostrio:flow-router-extra`

It is more up-to-date with regular release cycle. Could you check it?

**Comment by filipenevola** [comment]
Yes, this is what I suggested [here](https://github.com/meteor/meteor/issues/11775#issuecomment-979341292) as well.

**Comment by brianlukoff** [comment]
@afrokick Thanks -- I'll definitely look into switching, but [see my comment in this thread](https://github.com/meteor/meteor/issues/11775#issuecomment-977935438) as to why I'm still concerned about the behavior of terser.

**Comment by filipenevola** [comment]
We are deprecating `kadira:flow-router` in favor of `ostrio:flow-router-extra`.

This issue only affects the [old flow-router due to old JS patterns](https://github.com/meteor/meteor/issues/11775#issuecomment-980475300).
