### ISSUE TITLE
$MONGO_OPLOG_URL does not support unix domain sockets

### ISSUE THREAD

**Issue by yghorbal** [meteor/meteor#11760]
Hello,

 When providing a unix socket mongodb URI : `mongodb:///path/to/socket.sock/local`, the following check fails https://github.com/meteor/meteor/blob/365604c91020db2c36b491e7ea332ed730492994/packages/mongo/oplog_tailing.js#L192 
 It's due to the fact that the `mongodb-uri` package does not parse unix sockets URIs "correctly" out of the box. For instance the output of `mongodbUri.parse(self._oplogUrl).database` is `path/to/socket.sock/local` and not `local` as one expects.

 Moreover, when socket path is [percent encoded](https://en.wikipedia.org/wiki/Percent-encoding) `mongodb://%2Fpath%2Fto%2Fsocket.sock/local`, `mongodb-uri` works as expected (producing the correct database name) so the previously provided check works, unfortunately it comes down short later :
https://github.com/meteor/meteor/blob/365604c91020db2c36b491e7ea332ed730492994/packages/mongo/oplog_tailing.js#L208-L209
In fact, `MongoConnection` does not expect percent encoded socket path mongo URI and fails with this error message
```
MongoError: failed to connect to server [%2Fpath%2Fto%2Fsocket.sock:27017] on first connect [MongoError: getaddrinfo ENOTFOUND %2Fpath%2Fto%2Fsocket.sock %2Fpath%2Fto%2Fsocket.sock:27017]
```

 I can't find out why the `$MONGO_URL` works out of the box though (without the percent encoding)

Thank you for your help

**Comment by renanccastro** [comment]
Hi, @yghorbal thanks for your report!
Have you tried on Meteor 2.5? Mongo driver updates can impact the issue you are describing.
Which version doesn't work?

> I can't find out why the $MONGO_URL works out of the box though (without the percent encoding)

Does this mean you currently have a workaround?

**Comment by yghorbal** [comment]
Hi @renanccastro you are right, the version I was investigating was very old. It's no longer an issue today !
