### ISSUE TITLE
Meteor.loginWithToken from accounts-passwordless overwrites loginWithToken from accounts-base

### ISSUE THREAD

**Issue by icellan** [meteor/meteor#11763]
The `Meteor.loginWithToken` from `accounts-base` is overwritten by `Meteor.loginWithToken` from `accounts-passwordless`.

A workaround is to import `Accounts` from `accounts-base` and directly use that instead of the `Meteor` global.

```
import { Accounts } from 'meteor/accounts-base';

Accounts.loginWithToken(loginToken, (err) => {
   ...
});
```

**Comment by StorytellerCZ** [comment]
Fix was released in Meteor 2.5.1
