### ISSUE TITLE
With HMR enabled in 2.5.0, application fails to load in IE11

### ISSUE THREAD

**Issue by perbergland** [meteor/meteor#11772]
Upgrading our app from 2.4.0 to 2.5.1 and running in developer mode it now crashes on initial load of bundles.

![image](https://user-images.githubusercontent.com/2690254/142581171-86a9f595-7870-4857-8b1d-3efba96718d3.png)

![image](https://user-images.githubusercontent.com/2690254/142581204-966925dc-77b3-4639-ac3c-0af4f4e3faaf.png)

![image](https://user-images.githubusercontent.com/2690254/142581254-705de241-3513-442f-9881-0f9726b84596.png)

**Comment by perbergland** [comment]
this is what modules.js looks like with 2.4.0 (no global.___INIT_METEOR_FAST_REFRESH)

![image](https://user-images.githubusercontent.com/2690254/142582540-1c5aa23a-e103-48b9-afa0-44ee3967e531.png)

**Comment by filipenevola** [comment]
As we don't have any changes in HMR in 2.5.1 I would assume the problem started in 2.5.

Could you confirm that @perbergland ?

**Comment by perbergland** [comment]
Confirmed with 2.5.0

**Comment by perbergland** [comment]
Tested again after disabling HMR and then it works.

```
export DISABLE_REACT_FAST_REFRESH=1
meteor run ...
```

**Comment by perbergland** [comment]
Can’t figure out how to make it not crash on production builds though. I get this error possibly caused by too new javascript code in react-fast-refresh

![image](https://user-images.githubusercontent.com/2690254/142723054-59179578-eac3-4251-913a-7b008c191a30.png)

![image](https://user-images.githubusercontent.com/2690254/142723049-ad774219-03c9-42bf-9c18-8d7e51397267.png)

**Comment by perbergland** [comment]
Could be as simple as changing this line to use IE-compatible syntax: `before: function (module) {`

https://github.com/meteor/meteor/blob/cd06a68d4fc34a9f5e0660fc4c4c5d7f49fc8d68/packages/react-fast-refresh/client.js#L21

**Comment by perbergland** [comment]
Current status:

Workaround for development builds: Set DISABLE_REACT_FAST_REFRESH=1 before `meteor run`
Fix for production/bundle builds: #11776

**Comment by filipenevola** [comment]
The fix for production/bundle builds is released here.

@zodern could you take a look at supporting IE11 in HMR?

**Comment by zodern** [comment]
The IE11 bug will be fixed by https://github.com/meteor/meteor/pull/11794
