### ISSUE TITLE
meteor add fourseven:scss@4.15.0   Command Failed!

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#11789]
### Discussed in https://github.com/meteor/meteor/discussions/11787

<div type='discussions-op-text'>

<sup>Originally posted by **modanwalrahul31** November 24, 2021</sup>
The below issue comes when I am upgrading the meteor from 1.6 to 2.2.3, I can not remove fourseven:scss package because that's one, not a direct dependency.  

meteor add fourseven:scss@4.15.0  
Unable to update package catalog (are you offline?)
                                              
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
                                              
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint caching-compiler@1.2.2 is not satisfied by caching-compiler 1.1.12.
Constraints on package "caching-compiler":
* caching-compiler@~1.1.9 <- top level
* caching-compiler@1.1.7 <- caching-html-compiler 1.1.3 <- static-html 1.2.2
* caching-compiler@1.0.0 <- cosmos:browserify 0.8.4 <- deanius:promise 3.1.3
* caching-compiler@1.0.4 <- coffeescript 1.0.17 <- cosmos:browserify 0.8.4 <- deanius:promise 3.1.3
* caching-compiler@1.0.4 <- coffeescript 1.0.17 <- nimble:restivus 0.8.12
* caching-compiler@1.2.2 <- fourseven:scss 4.15.0

Conflict: Constraint ecmascript@0.15.1 is not satisfied by ecmascript 0.10.9.
Constraints on package "ecmascript":
* ecmascript@0.10.6 <- top level
* ecmascript@~0.10.6 <- top level
* ecmascript@0.10.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- logging 1.1.20 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- logging 1.1.20 <- webapp 1.5.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- logging 1.1.20 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.9.0 <- ejson 1.1.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.9.0 <- ejson 1.1.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- base64 1.0.11 <- ejson 1.1.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- ddp-server 2.1.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- ddp-server 2.1.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- routepolicy 1.0.13 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- boilerplate-generator 1.4.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- boilerplate-generator 1.4.0 <- webapp 1.5.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- boilerplate-generator 1.4.0 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.4.3 <- webapp-hashing 1.0.9 <- webapp 1.5.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.4.3 <- webapp-hashing 1.0.9 <- webapp 1.5.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.4.3 <- webapp-hashing 1.0.9 <- webapp 1.5.0 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- check 1.3.1
* ecmascript@0.10.0 <- random 1.1.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- random 1.1.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- retry 1.1.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- retry 1.1.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- id-map 1.1.0 <- binary-heap 1.0.10 <- mongo 1.4.7
* ecmascript@0.10.0 <- callback-hook 1.1.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- callback-hook 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-common 1.4.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- ddp-common 1.4.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- ddp-common 1.4.0 <- mdg:meteor-apm-agent 3.1.2
* ecmascript@0.10.0 <- reload 1.2.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- reload 1.2.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- reload 1.2.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- reload 1.2.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- socket-stream-client 0.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- socket-stream-client 0.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- minimongo 1.4.4 <- aldeed:collection2 3.0.6
* ecmascript@0.10.0 <- diff-sequence 1.1.0 <- mongo 1.4.7
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- ddp-client 2.3.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- minimongo 1.4.4 <- aldeed:collection2 3.0.6
* ecmascript@0.10.0 <- mongo-id 1.0.7 <- mongo 1.4.7
* ecmascript@0.10.0 <- ddp-server 2.1.2 <- ddp 1.4.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- ddp-server 2.1.2 <- ddp 1.4.0 <- accounts-password 1.5.1
* ecmascript@0.9.0 <- minimongo 1.4.4 <- aldeed:collection2 3.0.6
* ecmascript@0.10.0 <- ordered-dict 1.1.0 <- blaze 2.3.3 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.10.0 <- ordered-dict 1.1.0 <- blaze 2.3.3 <- alanning:roles 1.2.16
* ecmascript@0.10.0 <- server-render 0.3.1 <- es5-shim 4.7.3
* ecmascript@0.10.0 <- shim-common 0.1.0 <- es5-shim 4.7.3
* ecmascript@0.10.0 <- autoupdate 1.4.0 <- hot-code-push 1.0.4 <- meteor-base 1.3.0
* ecmascript@0.10.0 <- autoupdate 1.4.0 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.10.0 <- mongo 1.4.7
* ecmascript@0.9.0 <- allow-deny 1.1.0 <- mongo 1.4.7
* ecmascript@0.9.0 <- reactive-dict 1.2.0
* ecmascript@0.10.0 <- minifier-css 1.3.1 <- standard-minifier-css 1.4.1
* ecmascript@0.10.8 <- standard-minifier-js 2.3.4
* ecmascript@0.10.0 <- rate-limit 1.0.9 <- ddp-rate-limiter 1.0.7
* ecmascript@0.5.8 <- static-html 1.2.2
* ecmascript@0.5.8 <- caching-html-compiler 1.1.3 <- static-html 1.2.2
* ecmascript@0.9.0 <- caching-compiler 1.1.12 <- caching-html-compiler 1.1.3 <- static-html 1.2.2
* ecmascript@0.9.0 <- caching-compiler 1.1.12 <- fourseven:scss 4.15.0
* ecmascript@0.5.8 <- templating-tools 1.1.2 <- caching-html-compiler 1.1.3 <- static-html 1.2.2
* ecmascript@0.5.8 <- templating-tools 1.1.2 <- static-html 1.2.2
* ecmascript@0.1.3 <- mdg:validated-method 1.1.0
* ecmascript@0.10.0 <- accounts-password 1.5.1
* ecmascript@0.9.0 <- accounts-base 1.4.2 <- accounts-password 1.5.1
* ecmascript@0.4.1 <- kadira:dochead 1.5.0
* ecmascript@0.4.3 <- coffeescript 1.0.17 <- cosmos:browserify 0.8.4 <- deanius:promise 3.1.3
* ecmascript@0.4.3 <- coffeescript 1.0.17 <- nimble:restivus 0.8.12
* ecmascript@0.6.1 <- aldeed:collection2 3.0.6
* ecmascript@0.1.5 <- mdg:validation-error 0.2.0 <- aldeed:simple-schema 1.5.4
* ecmascript@0.4.0-beta.11 <- tmeasday:check-npm-versions 0.3.2 <- aldeed:collection2 3.0.6
* ecmascript@0.4.1 <- react-meteor-data 2.0.1
* ecmascript@0.5.8 <- templating-compiler 1.2.15 <- templating 1.2.15 <- launch-screen 1.1.1 <- mobile-experience 1.0.5
* ecmascript@0.5.8 <- templating-compiler 1.2.15 <- templating 1.2.15 <- nitrolabs:cdn 1.3.0
* ecmascript@0.4.2 <- wellcraftedapps:smart-disconnect 1.0.0
* ecmascript@0.4.2 <- okgrow:analytics 3.0.5
* ecmascript@0.4.2 <- wellcraftedapps:reloader 1.3.1
* ecmascript@0.1.6 <- wellcraftedapps:static-subs 1.0.1
* ecmascript@0.15.1 <- fourseven:scss 4.15.0
* ecmascript@0.1.5 <- deanius:promise 3.1.3
* ecmascript@0.4.1 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.4.0-beta.11 <- tmeasday:test-reporter-helpers 0.2.1 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.4.1 <- practicalmeteor:mocha-core 1.0.1 <- practicalmeteor:mocha 2.4.5_6
* ecmascript@0.9.0 <- epotek:accounts-ui 1.5.3

Your package catalog may be out of date.      
Please connect to the internet and try again.
</div>

**Comment by filipenevola** [comment]
Are you running behind a proxy?

It seems that your catalog is not up-to-date. Is your Internet working fine?

See this part of your log: `Unable to update package catalog (are you offline?)`.

**Comment by vitorflores** [comment]
Hi, as we still don't have a way to reproduce this issue I'm closing it.

Of course, if we have a reproduction in the future we can re-open it. No problem.
