### ISSUE TITLE
Login with facebook and google could use the same user

### ISSUE THREAD

**Issue by leobastiani** [meteor/meteor#11810]
https://github.com/meteor/meteor/blob/7132723d1e3553be7e7e7e8c2966265918c502a1/packages/accounts-base/accounts_server.js#L1278-L1280

I think that `serviceIdKey` could call `Accounts.serviceIdKeyFactory(...args)` that could return a different key like `...email` and then we could be able to reuse the same user with different login services
Would it be possible?

**Comment by StorytellerCZ** [comment]
Possible, but undesirable. Personally I would see this as a security issue that you get access to a user account while using another service that is not associated with the user.
If you want to allow users to link and then sign from multiple services then you might want to consider `bozhao:link-accounts`: https://github.com/Meteor-Community-Packages/meteor-link-accounts
Other alternative would be to utilize account hooks in your app and make the connections you want as you want, but understand that there are security issues to consider.

**Comment by StorytellerCZ** [comment]
@filipenevola I think this can be closed since there are community alternatives and this has been rejected multiple times in the past.
