### ISSUE TITLE
oauth no longer works if app embedded in iframe, using the latest security settings on chrome

### ISSUE THREAD

**Issue by bogdanrn** [meteor/meteor#11817]
How to reproduce:
Step 1: Turn on the setting on google chrome "block third-party cookies" which i believe is enabled by default (at least in safari it is).
Step 2: Load the meteor app inside an iframe on a different domain

Because oAuth relies on sessionStorage, login flow will no longer work.

**Comment by bogdanrn** [comment]
I figured it out, it's a small bug in the oAuth package.

 In the [meteor/packages/oauth/end_of_popup_response.js](https://github.com/meteor/meteor/blob/devel/packages/oauth/end_of_popup_response.js#L24-L29) we have a try/catch when sessionStorage is used, but on the [meteor/packages/oauth/end_of_redirect_response.js](https://github.com/meteor/meteor/blob/devel/packages/oauth/end_of_redirect_response.js#L7) it is not added. 


Adding the try/catch in the second file fixes the bug in iframes on chrome

**Comment by StorytellerCZ** [comment]
@bogdanrn can you please create a PR with the fix?

**Comment by StorytellerCZ** [comment]
@bogdanrn please check #11825 if the solution is correct based on your fix.

**Comment by bogdanrn** [comment]
@StorytellerCZ thanks for the quick reply, that looks good. This would fix the problem i encountered.

PS:
For anyone who lands on this issue, the next step is to implement login tokens to resume the session. I did it by using Accounts.registerLoginHandler. Meteor will continue working as expected from this point on.

**Comment by filipenevola** [comment]
Published oauth@2.1.1.
