### ISSUE TITLE
metoer/oauth package dependency causing ios build to fail in meteor 2.5.1

### ISSUE THREAD

**Issue by chrishanyu** [meteor/meteor#11822]
After starting a new meteor project and add `accounts-google` package, `meteor run ios` will fail and give the following error:

```
/Users/hanyuzhu/workspace/javascript/simple-todos/.meteor/local/cordova-build/platforms/ios/simple-todos/Plugins/cordova-plugin-inappbrowser/CDVInAppBrowserNavigationController.m:78:42: error: 
      no known instance method for selector 'shouldAutorotateToInterfaceOrientation:'
        return [self.orientationDelegate shouldAutorotateToInterfaceOrientation:interfaceOrientation];
```

This issue can be found here:
https://github.com/apache/cordova-plugin-inappbrowser/issues/714

Looks like `meteor/oauth` package's cordova dependency `cordova-plugin-inappbrowser@3.2.0` is causing this error.

After copying `oauth` folder to `project/packages` file and change dependency version to latest (5.0.0), the error no longer exist.

**Comment by denihs** [comment]
Hi @chrishanyu, 

So you were able to fix it by updating the version? Or does the problem continue? Can you provide a reproduction?

**Comment by chrishanyu** [comment]
> Hi @chrishanyu,
> 
> So you were able to fix it by updating the version? Or does the problem continue? Can you provide a reproduction?

Yes, problem was fixed by updating the version

**Comment by chrishanyu** [comment]
@denihs 

`cordova-plugin-inappbrowser` is a dependency of `meteor/oauth` package. I was able to fix the issue by copying the package to local project and updating `package.js` file line 50

from: 
```
Cordova.depends({
  'cordova-plugin-inappbrowser': '3.2.0'
});
```

to:
```
Cordova.depends({
  'cordova-plugin-inappbrowser': '5.0.0'
});
```

The dependency version decleared [here](https://github.com/meteor/meteor/blob/ff2250427ecf8b4e0f069d0652144c659a20ed3a/packages/oauth/package.js#L51) is still causing the error as of Meteor version 2.5.2.

The steps defined by the original post is a reproduction of the issue. Let me know if I can clearify futher.
