### ISSUE TITLE
Meteor 2.5.2 both Login with Facebook and Google fail due to wrong redirect URI

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#11821]
Update to 2.5.2 with meteor update --release 2.5.2. Login with social services stopped working due to missing or incorrect redirect URI.

Revert back to 2.5.1 all ok.

**Comment by denihs** [comment]
Hi @paulincai, can you provide a reproduction? Here you can see how to create one:  https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor

**Comment by paulincai** [comment]
Ok, in order to login with Facebook or Google you need Facebook / Google apps/projects with valid keys and secrets.

I think the matter can be easily experienced if you already have a project that you can upgrade to 2.5.2 and see. What I actually see is that both the Facebook and Google popup windows reject my login due to incorrect redirect URI. As mentioned, just reverted back to 2.5.1 and all ok.

**Comment by paulincai** [comment]
Ok, forgot to ask @denihs, do you have API credentials for either FB or Google? In this case I can provide you with a reproduction.

**Comment by paulincai** [comment]
As I looked into commits of 2.5.2 and there hasn't been anything that might have affected oAuth or login with services, I cleared cache in my project, cleaned NPM etc ... meteor reset and redeployed with 2.5.2 and all seems ok now.
My apologies for not doing this before reporting this issue.

**Comment by juliomac** [comment]
I am having the same Issue with both Facbook and Google.

This is the reproduction made by FaceBook support people:

https://user-images.githubusercontent.com/3759295/155526427-0feccfb0-f625-490a-9d65-8cee0820304d.mp4

**Comment by renanccastro** [comment]
@juliomac have you whitelisted the redirect URI on Facebook client settings? There seems to be no code error on Meteor's side here.

**Comment by juliomac** [comment]
What do you mean? If it is the _Facebook Login / Configuration / Valid Oauth redirection_  I obviously have configured it with ```https://my.application.com/_oauth/facebook?close```
Is there any other place to it?
It was even validated with the tool on the Botton of the page.

**Comment by denihs** [comment]
Hey @juliomac, could you try to remove the `?close` and see what happens?

**Comment by juliomac** [comment]
It worked!

Strangely enough, if tested using the tool on the bottom, It does work!

**Comment by juliomac** [comment]
What about Google? I may have been doing wrong there too.. I simply can't find updated procedures on how to configure Google's login... only things from 2015 or so... I must admit I have been guessing from the information I have been able to find.

**Comment by denihs** [comment]
You need to create a [OAuth 2.0 client ID](https://developers.google.com/identity/protocols/oauth2). Go to https://console.developers.google.com/ > APIs and services > credentials (create a new project if needed).

Maybe you already did that. Then try to change your URL to `https://my.application.com/_oauth/google`.

But Google has more steps than Facebook to activate, so you need to check their documentation. Maybe this [video](https://youtu.be/8Gk4u3zNtDk) can help you. It's old but it didn't change that much.

But you're not wrong. We need to update our docs so that this setup can be easier.
