### ISSUE TITLE
Accounts.config.defaultFieldSelector is not considered in published default user fields

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#11827]
## Versions:

Meteor release 2.5
`accounts-base@2.2.0`
OS: Ubuntu 20.04 LTS
The last version of Meteor where the problem did _not_ occur, if applicable: not known to me right now

## The expected behavior:

```js
 Accounts.config({
    defaultFieldSelector: {
      _id: 1,
      username: 1,
      emails: 1,
      createdAt: 1,
      profile: 1,
      services: 1,
      customField: 1
    }
  });
```

should auto-add these fields to the current user `Meteor.user()` when logged-in (assuming these fields exist on the user document).
Related docs: https://guide.meteor.com/accounts.html#prevent-unnecessary-data-retrival

## The actual behavior:

Once logged in the `Meteor.user()` command only returns `{ _id: 'the userid', profile: {}, emails: [...] }`

## Reproduction:

Create meteor projectt, add Accounts and create a new user, then use the above `Accounts.config` and log in on the client. Open the Borwser console and run `Meteor.user()`

**Comment by brendonlamb** [comment]
TY for confirming and creating this issue.

If it's helpful, I was experiencing this issue in Meteor 2.4 as well.

**Comment by StorytellerCZ** [comment]
So a few observations:
* `Meteor.user()` will completely respect the default fields and limit the return to what you set
* If you limit it only to say the custom field you will still see fields that Meteor needs to run when you get data from `Meteor.users()`
* Retrieving recognized fields (ie. those retrieved) like `profile` works fine, but `customField` is not retrieved even when specified, I think this is the main problem.

**Comment by denihs** [comment]
The solution for this is now in version 2.6.1 https://github.com/meteor/meteor/pull/11850. 

I'm closing this issue. If the problem persists, we can open it again.

**Comment by jankapunkt** [comment]
@denihs @StorytellerCZ  Coming back to this issue I found that I can only make this work when using `Accounts.setDefaultPublishFields({ customField: 0 })` but this method is nowhere document :eyes: 

Using
```
Accounts.config({
    defaultFieldSelector: {
      customField1: 0,
      customField2: 0,
      customFieldN: 0
    }
  });
```

has no effect at all. I tested with 2.6.1

**Comment by StorytellerCZ** [comment]
😤 Looks like I will have to dive into the code again.

**Comment by jankapunkt** [comment]
@StorytellerCZ were you able to reproduce the issue?

**Comment by banjerluke** [comment]
Leaving a couple breadcrumbs here for anyone else who searches for this issue, which I was also encountering:

1) I too had to use the undocumented/untyped `Accounts.setDefaultPublishFields()` function instead of the `defaultPublishFields` key of `Accounts.config()`.

2) If using `meteor-vite`, the config does not take effect if you put it in `entry-vite.js`, as it seems `entry-vite.js` gets processed *after* `Meteor.startup()` and the autopublish will already be initialized. Had to move the code to `entry-meteor.js`.
