### ISSUE TITLE
Application won't start when a dependency has invalid JSON in a package.json

### ISSUE THREAD

**Issue by DavidShefcik** [meteor/meteor#11839]
# System Information
- Meteor version: `2.3.4`
- Operating system: `macOS 11.2.3`

# Description
## Expected Behavior
- Meteor starts without a problem

## Actual Behavior

When a node module has invalid JSON, it causes the meteor application to fail with an error like this
```
=> Started proxy.
/Users/username/.meteor/packages/meteor-tool/.2.3.4.17nyv2i.8atx++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
```

this was caused by an invalid JSON file in a node module. It is `node_modules/resolve/test/resolver/malformed_package_json/package.json` which contains the following package.json
```
{
```
when I fix that to be valid JSON, Meteor starts without a problem. I opened an issue with the package causing it but their dev was saying it is up to Meteor to not assume a package has valid JSON - https://github.com/browserify/resolve/issues/266

# Reproducible example
GitHub Repository: https://github.com/DavidShefcik/meteor-json-error

### Steps on a project from scratch:
1. Create a meteor project with version 2.3.4
2. Install the most recent version of the `resolve` package. This is the project I noticed this in due to it being a dependency of a bunch of different packages
3. Try to run the application, it will crash

# Notes
- I found this code in the repo that seems to be causing it. It doesn't look like JSON.parse is being catched even though it is in a try catch - https://github.com/meteor/meteor/blob/release-2.3.4/tools/fs/optimistic.ts#L321

**Comment by ljharb** [comment]
Additionally, if you're only looking for dependencies, you'd only want to look at the package.json at a package boundary - iow, `**/node_modules/*/package.json` and `**/node_modules/@*/*/package.json`. This one's in a nested text fixture and not inside a node_modules folder, so there shouldn't be any reason to look at it in the first place (assuming "finding deps" is the rationale)

**Comment by DavidShefcik** [comment]
It may be erroring out due to being called here - https://github.com/meteor/meteor/blob/e3ff09ef4464c1bda55155324c576036f52786e0/tools/isobuild/resolver.ts#L159

**Comment by ljharb** [comment]
Looks like there's an `allowSyntaxError` option (https://github.com/meteor/meteor/blob/e3ff09ef4464c1bda55155324c576036f52786e0/tools/fs/optimistic.ts#L324) which should be passed on that line.

**Comment by DavidShefcik** [comment]
I went and edited my local meteor package code and if I add the `allowSyntaxError` option to this call to `optimisticReadJsonOrNull` it starts fine - https://github.com/meteor/meteor/blob/release-2.3.4/tools/fs/optimistic.ts#L366. Makes sense that this is where it occurs because meteor is scanning the dependencies that are installed when the application is trying to start.
Hopefully someone from the meteor team responds to this because I'm wondering if there is a reason against adding that option to this function call. I would imagine there is a reason against adding the `allowSyntaxError` to this call because we shouldn't try to work with broken dependencies, so the scanning logic should be updated to only scan for the package json's that @ljharb said in this comment above - https://github.com/meteor/meteor/issues/11839#issuecomment-1006800500
