### ISSUE TITLE
v1.5.4.2 tag is missing

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#11858]
The repository is missing v1.5.4.2 tag.

**Comment by StorytellerCZ** [comment]
The tag is named `release/METEOR@1.5.4.2`. It is on the `release-1.5.4.2` branch, not on the main branch as it was a patch release. I have pushed the tag again just in case.
Here is the link:
https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.5.4.2

**Comment by mitar** [comment]
Hmmm. I promise I searched for it everywhere. Not sure how I missed it. :-(

Sorry for the noise.
