### ISSUE TITLE
Match.error only in IE 11 

### ISSUE THREAD

**Issue by KirillTertunov** [meteor/meteor#11852]
Get the error - "Exception in template helper: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation" in IE 11.
Code fails here - `return Connects.find({task: taskID},{sort: { time: 1, _id: 1 },limit: 10});`. Main problem is the field 'limit'. If I comment it all works perfect. FF, Safari, Сhrome work perfect without commenting field 'limit'.
Meteor version - 1.11

**Comment by StorytellerCZ** [comment]
Can you please try updating to at least Meteor v1.12.1, there were some IE fixes in that release.

**Comment by renanccastro** [comment]
Hello!
Can you please test with the latest Meteor version?
I'm closing this issue for now. Please open another one if it's still an issue for you, with a reproduction using a supported meteor version
For more details, please refer to this document: https://github.com/meteor/meteor/blob/devel/SECURITY.md#supported-versions

Thanks.
