### ISSUE TITLE
Requiring NPM devDependencies silently fails on server

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#11853]
If I `require` or `import` an NPM package that is `npm install`ed but listed under `devDependencies` in `package.json`, then
* On the server, I get an empty package (`{}`) instead of the correct contents.
* On the client, I get the correct package contents `{esm: <function>, standard: <function>}`.

If I move the dependency to `dependencies`, then I get the full package contents on client and server.

I'd be OK with `devDependencies` failing (though I'd rather it actually work, as this really is a dev dependency), but *failing without producing an error message* is especially tricky to track down.

Demo repo: https://github.com/edemaine/bug-meteor-devDependency

I'm running Meteor 2.5.3 on Windows 10.

**Comment by denihs** [comment]
This should already be fixed in version 2.7.1. Please try to update your project version using the command `meteor update`.

You can read more about the fix here: https://github.com/meteor/meteor/pull/11954.
