### ISSUE TITLE
Unable to install meteor via npm 

### ISSUE THREAD

**Issue by pociej** [meteor/meteor#11863]
I do `npm install -g meteor` but then when i try to use meteor i see `zsh: comman not found: meteor`. I thought it is some problem with PATH but it is not, other global opackages works properly. Only ting that is installed is meteor-installer. but not meteor. Node version 12.14.1 os macos 11.6.2

**Comment by vitorflores** [comment]
Have you tried to run `npm install -g meteor` instead?

**Comment by pociej** [comment]
@vitorflores of course i did `npm install -g meteor`, i changed content. I dont think that github issues is proper place for this kind of comments.

**Comment by filipenevola** [comment]
Hi @pociej, I don't think @vitorflores was malignant but anyway, what is the feedback you get after installing Meteor?

Could you paste the logs here to know if everything worked properly?

Is this the first time that you are installing Meteor? Is it working with the old curl command?

**Comment by pociej** [comment]
hi @filipenevola . 

After i install meteor using `npm install -g meteor` everything seems fine i see success messages like 

```Meteor has been installed!

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

```

etc 

However when i try to run i see `meteor` i see `zsh: command not found meteor`. I checked and indeed there is no binary in my `~/.meteor` directory it contains only `packages` dir. This happen on osx 11.6.2 with node 14.18.3 ( i tried  12.14.1 with same results ). Curl installation works fine. I checked now on digital ocena ubuntu 20.04 server and the problem is exactly the same.

**Comment by stalexxx** [comment]
having issue corresponding to this title
So, executing command `npm install -g meteor`
```

npm ERR! code 1
npm ERR! path /Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor
npm ERR! command failed
npm ERR! command sh -c node cli.js install
npm ERR! /Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor/node_modules/semver/classes/semver.js:38
npm ERR!       throw new TypeError(`Invalid Version: ${version}`)
npm ERR!       ^
npm ERR!
npm ERR! TypeError: Invalid Version: 2.6
npm ERR!     at new SemVer (/Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor/node_modules/semver/classes/semver.js:38:13)
npm ERR!     at compare (/Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor/node_modules/semver/functions/compare.js:3:3)
npm ERR!     at Object.gte (/Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor/node_modules/semver/functions/gte.js:2:30)
npm ERR!     at Object.<anonymous> (/Users/alex/.nvm/versions/node/v16.13.2/lib/node_modules/meteor/install.js:46:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)

```

Tried both: lts and latest node/npm versio
[2022-02-05T15_19_17_555Z-debug.log](https://github.com/meteor/meteor/files/8008252/2022-02-05T15_19_17_555Z-debug.log)
n

**Comment by renanccastro** [comment]
@stalexxx you are installing meteor using node 16, which is not supported. Please use node >= 12 <= 14

**Comment by stalexxx** [comment]
that's helpfull! But also wierd - i have succeed installing on latest node on my old mac

**Comment by dburles** [comment]
Ran into the same issue as @stalexxx. Are there plans to support Node 16+?
