### ISSUE TITLE
Meteor 2.6: Meteor publish no longer updating field correctly

### ISSUE THREAD

**Issue by mikowals** [meteor/meteor#11884]
A client doesn't receive the updated value for a field published by returning a cursor.

This example code is a `tests/main.js` file to replace the file in a new project from `meteor create`.  These tests pass in Meteor 2.5.6 but fail in Meteor 2.6.  Also, it might have to do with the updated field being an object as the client correctly receives an update like `{$set: {nested: {count: 1}}}`).  I focused on nested fields because I hit test failures in an app but I haven't checked whether nesting is essential to reproduce.

    import assert from "assert";
    import { Mongo } from "meteor/mongo";
    import { Meteor } from "meteor/meteor";

    describe("publish-bug", function () {
      const col = new Mongo.Collection("test");
      it("package.json has correct name", async function () {
        const { name } = await import("../package.json");
        assert.strictEqual(name, "publish-bug");
      });

      if (Meteor.isClient) {
        describe('client', function () {
          this.timeout(30000);
          let handle;
          after(() => {
            handle.stop();
          })
          it('subscribes', async () => {
            handle = Meteor.subscribe('test');
            await new Promise(resolve => setTimeout(resolve, 7000));

            const result = col.findOne();
            assert.strictEqual(result.count, 1);
            assert.strictEqual(!!result.nested?.state, true);
          })
        })
      } else {
        // server code
        col.remove({});
        col.insert({_id: 'test', count: 0});
        Meteor.setTimeout(() => {
          col.update({_id: 'test'}, {$set: {count: 1, nested: {state: {}}}});
        }, 5000);
        Meteor.publish(function() {
          return col.find({});
        })
      }
    });

This is probably related to #11883, though that describes a field dropping.

I was on an M1 MacBook seeing this test fail.

**Comment by renanccastro** [comment]
@mikowals can you give a try at this branch? [fix/oplog-converter-empty-object](https://github.com/meteor/meteor/tree/fix/oplog-converter-empty-object)

It's the same process as running meteor, but you run from the executable "meteor" inside the checkout at this branch.

We can validate if your tests are passing now with this change.

**Comment by mikowals** [comment]
@renanccastro, yes running that branch all my tests are passing.  Both in this repro and my larger project.

**Comment by filipenevola** [comment]
@mikowals we've published mongo@1.14.1.

If you run `meteor update` in your project using 2.6, you should be able to use this version of mongo package.

**Comment by polygonwood** [comment]
The issue is indeed related to [#11883](https://github.com/meteor/meteor/issues/11883#issue-1122309631) . My application also runs fine with the fix. Michaels repro hints why my repro did not do the job so far : it must be timing related because with an earlier branch I also did not have the issue using 2.6, the latest branch is doing more async stuff hence different timing behaviour.
Confirm that mongo@1.14.1 resolves the issue.

**Comment by renanccastro** [comment]
thanks you both for reporting!!
