### ISSUE TITLE
 Invalid DOM property `referrerpolicy`. Did you mean `referrerPolicy`?

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11899]
in meteor 2.6 :

![image](https://user-images.githubusercontent.com/36485982/153132462-75e668e9-ba1f-4805-ab3a-176a14d4b755.png)

**Comment by denihs** [comment]
Hi @Saeeed-B, are you able to provide a reproduction?

Did this warning start to show up just in meteor 2.6? And did you try to use `referrer-policy`? There were any errors?

Which system are you running?

**Comment by Saeeed-B** [comment]
I saw this error in versions 2.5.x and 2.6.
And I did not use referrerPolicy at all.
It may be related to the [meteor react router ssr](https://github.com/Meteor-Community-Packages/react-router-ssr) package.

**Comment by filipenevola** [comment]
Hi, @Saeeed-B. We need a reproduction that shows the problem comes from core packages or the meteor tool. In this case, your suspicion is in a package that is not part of the core, so you should open this issue there.
