### ISSUE TITLE
Fresh 2.6 install fails on M1

### ISSUE THREAD

**Issue by dburles** [meteor/meteor#11915]
On running `npm i -g meteor` on an M1 MacBook Pro, the following error is thrown: `TypeError: Invalid Version: 2.6`.

Which comes from this semver check: https://github.com/meteor/meteor/blob/devel/npm-packages/meteor-installer/install.js#L46 as it's provided an invalid version.

Here's a reproduction: https://codesandbox.io/s/cool-bhaskara-n2p5r?file=/src/index.js

A likely fix would be to use `semver.coerce`, to retain the official 2.6 versioning.

eg.
```js
semver.gte(semver.coerce("2.6"), "2.5.1-beta.3");
```

**Comment by renanccastro** [comment]
Hi, @dburles .
Thanks for reporting.
I've released on npm meteor@2.6.1 with the fix.

**Comment by dburles** [comment]
Thanks for the fix! It's working now :)
