### ISSUE TITLE
Meteor with Apollo-server v3?

### ISSUE THREAD

**Issue by imhazige** [meteor/meteor#11926]
Does Apollo server v3 works with Meteor 2+?

I have tried, but it seems not work, the server crash.

The client throw error like this, the meteor websocket closed.
https://stackoverflow.com/questions/50384609/meteor-apollo-subscription-websocket-connection-closed
The apollo client is able to connect(both http and websocket), but the meteor server crash after a while.

events.js:377
throw er; // Unhandled 'error' event
^

Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
at Socket.onerror (internal/streams/readable.js:750:14)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21) {
errno: -54,
code: 'ECONNRESET',
syscall: 'read'
}

I have try noServer option which is a v2 option to subscriptionserver.
https://github.com/Pitchlyapp/meteor-apollo2/issues/1

It make the meteor works, but apollo subscription not work.

**Comment by StorytellerCZ** [comment]
Yes it works. There is the Apollo skeleton which is build with Apollo v3.
If you are upgrading from Apollo v2, you can check out my article on how to do it:
https://dev.to/storytellercz/upgrading-to-apollo-3-in-meteor-in-3-steps-28pl

**Comment by imhazige** [comment]
Hey, @StorytellerCZ 

The problem is subscription, the example you post does not mentioned it, and I have read it at before.

**Comment by StorytellerCZ** [comment]
Meteor currently does not support Apollo subscriptions out of the box. I would recommend starting a GitHub discussion if you want this to be explored by the devs.
Though the general recommendation is against Apollo subscriptions in Meteor. Here is a relevant discussion on the Meteor forums: https://forums.meteor.com/t/meteor-collections-pubsub-vs-apollo-graphql/57509?u=storyteller

**Comment by imhazige** [comment]
Hey, @StorytellerCZ 

Thank you, now I get confirmed from your response.
