### ISSUE TITLE
Please restore `curl` command to Meteor Install page

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#11931]
I don't like telling people to use the `npm install -g meteor` command knowing that it might not work (it is fragile if anyone has more than a default `npmrc` configuration).

Please, can you please put back the `curl https://install.meteor.com/ | sh` command until the `npm` command is fixed?

The issues are already listed in https://forums.meteor.com/t/56987/20 .

I believe in Meteor, but if I tell people a command that isn't listed on the official Meteor Install page, then they will ask questions. I don't want to have to explain why they should avoid the `npm` command.

I'm trying to _sell_ Meteor, and it needs a command that works, consistent with the official primary recommendation.

**Comment by trusktr** [comment]
The docs where the Curl command is currently located say

> We recommend everybody to use the npm installer but we are still going to maintain this script as well.

But not everyone can use the `npm` command because it fails. It is not stable.

_The curl command is stable._

**Comment by denihs** [comment]
Hi @trusktr, as this isn't exactly a bug, I'm closing this issue. Feel free to open a discussion about this.
