### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH 

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/meteor#11939]
I see this error when receiving photos and dynamic import.
My routes are dynamic imports so the routes do not work .

` net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
`

website link :

[ghadr ](https://ghadr.org/)

**Comment by renanccastro** [comment]
Hi @Saeeed-B , your report is not enough to understand and reproduce the issue.

Please detail it more and provide us with a minimal project containing a reproduction so we have ways of acting on the issue you have reported.

I'm closing the issue for now. You can reopen it when there are more details aroundd it.
