### ISSUE TITLE
WARNING: Unsupported oplog operation,

### ISSUE THREAD

**Issue by blacelle** [meteor/meteor#11933]
### This bug report should include:
- While updating our app from Meteor 1.10.X to 2.6, we encounter the following error message:

```
I20220218-17:51:42.732(1)? ---
I20220218-17:51:42.733(1)? WARNING: Unsupported oplog operation, please fill an issue with this message at github.com/meteor/meteor
I20220218-17:51:42.733(1)? Oplog entry: {"a":true,"s0":{"u":{"message":"test local edit_benoit"}}}, prefixKey: comments., key: a
I20220218-17:51:42.733(1)? ---

```
- Version with given issue: Meteor 2.6
- Version OK: 1.10.X
- MacOs

I'm not proficient in Meteor|JS, hence it would be very difficult to provide a reproduction scenario. I hope the error message will be quite self-expressive, especially as it is generated by Meteor itself.

Thanks

**Comment by dan335** [comment]
Also getting this message after updating.

```
WARNING: Unsupported oplog operation, please fill an issue with this message at github.com/meteor/meteor
Oplog entry: {"a":true,"s85":{"u":{"hasBuilding":true,"nearbyBuildings":true}}}, prefixKey: hexes., key: a
```
