### ISSUE TITLE
Unsupported oplog operation with v2.6

### ISSUE THREAD

**Issue by tjramage** [meteor/meteor#11943]
Think I've managed to come across another oplog conversion issue, as per the problem in #11914.

Below is the debug log output. FYI: I've replaced the email address with duff data...

```
WARNING: Unsupported oplog operation, please fill an issue with this message at github.com/meteor/meteor

Oplog entry: {"a":true,"s0":{"u":{"address":"name@company.io"}}}, prefixKey: emails., key: a
```

@renanccastro Currently trying to pin down the exact query that triggered this... Do you need that or is the above info sufficient?

**Comment by tjramage** [comment]
Okay, I'm pretty sure this is the query:

```
Meteor.users.update({ _id: userId }, {
  $set: {
    username,
    'emails.0.address': email
  }
})
```

**Comment by renanccastro** [comment]
Hello @tjramage .
Have you updated the mongo version to the latest? I've shipped a patch that fix this exact case.

**Comment by tjramage** [comment]
@renanccastro – is this _another_ patch after the one we identified last week? I'll go check now, sorry, I assumed there hadn't been any additional movement on that. My bad...

**Comment by renanccastro** [comment]
Yes.
This message is actually a false positive in this  case, there is no parsing error.

No problem, let me know if it works.

**Comment by tjramage** [comment]
Yep, all good with the latest mongo package... Sorry! I'll go ahead and close.
