### ISSUE TITLE
Underscore package has a bug with Meteor 2.6

### ISSUE THREAD

**Issue by ricaragao** [meteor/meteor#11942]
After updating Meteor to version 2.6, I got this error on the server using Underscore:

```
TypeError: Cannot read property 'bind' of undefined
     at Function._.bind (packages/underscore.js:661:28)
```

Line 661 of the Underscore in the server is:
`    if (nativeBind && func.bind === nativeBind) return nativeBind.apply(func, slice.call(arguments, 1));
`

The variable `func` in this case is a rawCollection passed from the call. I guess there are something that changes to use this part of underscore.

To replicate the problem you need to use the package https://github.com/Konecty/meteor-mongo-counter

**Comment by renanccastro** [comment]
Hi, @ricaragao This package uses outdated raw collection methods and won't work with Meteor 2.6.

It uses findAndModify which was replaced to findOneAndUpdate

It's an easy modification to this package to make it work, let me know if you are willing to do it or we can also do it as a "compat" package - https://forums.meteor.com/t/introducing-meteor-compat-packages/56759

**Comment by renanccastro** [comment]
I'm closing this issue as there aren't any steps remaining from us. @ricaragao will handle the package update.

Thanks!
