### ISSUE TITLE
meteor 2.5 + 2.6 app no longer starts

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#11959]
We updated an older app from 1.12 to meteor 2.6

When I start the app with `meteor` i get a cryptic error:

```
/Users/my-user/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'undefined'
- 'boolean'
    at /tools/isobuild/bundler.js:1380:16
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:1375:32
    at Array.forEach (<anonymous>)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1359:19)
    at /tools/isobuild/bundler.js:864:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3260:14
    at /tools/isobuild/bundler.js:3413:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3367:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/Users/my-users/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/my-users/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1540:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/my-users/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'undefined',
  expected: 'boolean',
  operator: 'strictEqual'
}

```

does anyone have any idea what this is could be?

its this line: https://github.com/meteor/meteor/blob/devel/tools/isobuild/bundler.js#L1380

i am not sure what this array ` batch.unibuild.resources` represents

**Comment by zodern** [comment]
@macrozone could you please provide the content of `.meteor/packages` and `.meteor/versions`? There might be a bug when using a package published with very old Meteor versions.

**Comment by macrozone** [comment]
> @macrozone could you please provide the content of `.meteor/packages` and `.meteor/versions`? There might be a bug when using a package published with very old Meteor versions.

thank you for the hint, ill check

**Comment by macrozone** [comment]
ok i opened the bundler.js file in

`/Users/myuser/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/tools/isobuild`

and logged out which packages would violate the assertion by not having `_dataUsed`

The first package that complained was `launch-screen` which is at its latest version `1.3.0`. When i removed that, the next complaining package was `promise` which is as well on its latest version (0.12.0)

**Comment by srimenow** [comment]
@macrozone  What version of MongoDB are you running?
I have the exact same problem; I deleted my version file to create a new one automatically; then tried to run my app with just the basic packages required for startup and received an error that my Mongo was out of date. 

I completely forgot to follow the Meteor instructions that require Mongo v5. 

I will edit this post after I update the DB and let you know if that fixed things.
Good Luck!

**Comment by srimenow** [comment]
@macrozone 

I got my app running again by doing the following; just trying to help:

1. Updating MongoDB.... through lots of testing I came to the conclusion that the "bundled" MongoDB within the Meteor dev environment was sourcing its binaries from the MongoDB installation on the machine. I believe we should check this with the MDG team and verify if MongoDB is being completely independently bundled within the Meteor framework or not.

2. After fixing the MongoDB error; I traced the source package causing the conflict to:
edgee:slingshot

I do not know what in this package is causing the error yet. Maybe someone else may be able to help us.

Could you please remove the slingshot package and let me know the error message you get?

Thanks.

**Comment by srimenow** [comment]
I hope this helps you, try replacing

edgee:slingshot  with
mikkelking:slingshot

See: https://forums.meteor.com/t/maintaining-the-slingshot-package/54393

This is the very least you need to do. I was able to do that and update my MongoDB and my app is running again. You may have other outdated packages. Please do post an update when your issue is resolved.

Thank you, good luck

**Comment by macrozone** [comment]
> @macrozone
> 
> I got my app running again by doing the following; just trying to help:
> 
> 1. Updating MongoDB.... through lots of testing I came to the conclusion that the "bundled" MongoDB within the Meteor dev environment was sourcing its binaries from the MongoDB installation on the machine. I believe we should check this with the MDG team and verify if MongoDB is being completely independently bundled within the Meteor framework or not.
> 2. After fixing the MongoDB error; I traced the source package causing the conflict to:
>    edgee:slingshot
> 
> I do not know what in this package is causing the error yet. Maybe someone else may be able to help us.
> 
> Could you please remove the slingshot package and let me know the error message you get?
> 
> Thanks.

I know, thanks for your input!

will look at slingshot, maybe thats indeed a good hint.

@zodern do you have an input how to identifiy problematic packages?

**Comment by zodern** [comment]
@macrozone I created a new app and copied over the packages and versions files, and did not encounter the error.

> i opened the bundler.js file in
> /Users/myuser/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/tools/isobuild
> and logged out which packages would violate the assertion by not having _dataUsed

This would be a good way to check, using something like:
```
        if (typeof resource._dataUsed !== 'boolean') {
          console.dir(resource);
          return;
        }
```

Could you please try this and share the output here?

**Comment by macrozone** [comment]
> @macrozone I created a new app and copied over the packages and versions files, and did not encounter the error.
> 
> > i opened the bundler.js file in
> > /Users/myuser/.meteor/packages/meteor-tool/.2.6.1.12e6q0a.j47t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/tools/isobuild
> > and logged out which packages would violate the assertion by not having _dataUsed
> 
> This would be a good way to check, using something like:
> 
> ```
>         if (typeof resource._dataUsed !== 'boolean') {
>           console.dir(resource);
>           return;
>         }
> ```
> 
> Could you please try this and share the output here?

hi, thanks for helping!

i actually did that already, see my comment https://github.com/meteor/meteor/issues/11959#issuecomment-1059176451

**Comment by zodern** [comment]
Could you please do it again using the code in my comment? It would be helpful to see the full resource objects that are missing the _dataUsed property.

**Comment by StorytellerCZ** [comment]
@macrozone I'm closing the issue since we didn't get response in a while and the associated PR got merged and published. Feel free to re-open the issue if the problem remains.
