### ISSUE TITLE
Unexpected mongo exit code 48. Restarting. 

### ISSUE THREAD

**Issue by salpulse** [meteor/meteor#11978]
I'm porting my app from meteor 1.10.2 to 2.6 (with mongo upgrade to 5.0). It was working, but I had to checkout my old (1.10.2) branch to fix a bug and when checked out my 2.6 branch again, meteor startup now fails with:

```
Unexpected mongo exit code 48. Restarting. 
Check for other processes listening on port 3001
```
Steps I have taken to try and fix it (to no avail) are (in no particular order);
- meteor reset
- Checked that nothing else is running on 3001 using sudo lsof -nP
- Tried running meteor on a different port (doesn't work)
- Uninstalled and reinstalled meteor
- Restarted machine
- meteor update to 2.6.1
- Ran npm install to make sure all packages are up to date
- I followed one post suggestion and deleted /tmp/mongodb-27017.sock
- Tried creating a blank, new meteor project (meteor fails on it too).

**Comment by salpulse** [comment]
Any clues, anyone?

**Comment by denihs** [comment]
Hi @salpulse, I wasn't able to reproduce your issue. It's pretty odd that even a blank project is not running. Based on your description, my first thought is that the problem comes from your machine.

Could you provide a reproduction of this problem?

Also, are you running Meteor from which OS?

**Comment by salpulse** [comment]
Hi @denihs . I just had a freelancer help me with this and it is now fixed. It turned out that my global installation of mongo was corrupted. I reinstalled mongo community edition 5.0 and this fixed the problem.
