### ISSUE TITLE
DB connection issues with Meteor 2.7 (possibly 2.6 too)

### ISSUE THREAD

**Issue by dovydaskukalis** [meteor/meteor#11992]
we upgraded from Meteor 2.5.5 to Meteor 2.7 and are experiencing some huge issues with DB (Atlas) connection.
DB calls start to randomly never return any value and hang. We have health checks and I logged inside to see what happens, and simple call like Users.findOne() just never returns anything, it gets stuck. In our application it seems to happen every 1-2 hours, bringing some of the servers down (happens at different times on each server).

[Active connections](https://aws1.discourse-cdn.com/meteor/original/3X/0/7/07c51facd5bb1a9b2a66778402d49737b1c3c2c2.png)

Checking some stats (screenshot above), shows some interesting data. The red line is when we have deployed version 2.7, connections are varying massively and after slowly climbing up, we have an instant drop in connections (when the server goes down basically). Then you can clearly see the point we have rollbacked to 2.5.5. Connections are stable and at the very last moment the increase is when we tried 2.7 once more with the same results, had to abort it yet again.

We have upgraded to MongoDB 5.0 but I can confirm it’s not the problem here because rolling back our application to 2.5.5 fixes all issues even with MongoDB being 5.0 (it’s not a huge deal for us since we don’t use Mongo oplog).

Application for both versions is the exact same code, just with Meteor version updated.

There are no useful logs at all. It just stops working. Any ideas how could we debug it or what could cause it?

**Comment by StorytellerCZ** [comment]
Could this be related to #11993 ?

**Comment by dovydaskukalis** [comment]
I wouldn't think so. All other server and MongoDB server stats remain pretty much unchanged, only the active connections one behaves strangely. We have tried it again, with suggested fix of replacing Mongo "srv" url with non srv. Same issues.

Meteor 2.5.5 has same amount of active connections as we have the number of collections, multiplied by the amount of servers which makes sense to me.

In Meteor 2.7 (today we tried 2.7.1), connections keep growing until eventually crashing. 

[Active connections. Meteor 2.7.1 deployed at 13:00](https://i.ibb.co/7jtPsvs/Screenshot-2022-04-03-at-21-15-23.png)

**Comment by denihs** [comment]
Aren't you getting any errors, possibly `Unexpected mongo exit code 48. Restarting.`?

This may be related to this one: https://github.com/meteor/meteor/issues/11978.

**Comment by denihs** [comment]
Are you sure they're just hanging? Because this call could be crashing...

Could you try something like:

```
app.get('/health-check', async (req, res) => {
  console.log('HEALTH CHECK');
  try {
     Meteor.users.findOne({}, { fields: { _id: 1 } });
  } catch(e) {
    console.error(e);
    return;
 }
  console.log('HEALTH CHECK SUCCESS');
});
```

**Comment by dovydaskukalis** [comment]
@denihs Yea my example was not the best but we tried exact same code you have with try/catch. It doesn't log anything.

**Comment by one-pereyra** [comment]
We have same problem here. After updating to Meteor 2.7 with MongoDB 5 the same queries are taking 100 times more! We even double Galaxy Containers and still is unworkable. And galaxy logs don't show anything meaningful.

**Comment by dovydaskukalis** [comment]
So after quite a long delay we tried to update to Meteor 2.8.1 hoping this issue doesn't happen. Unfortunately it seems it still does. We managed to get a log this time

```
MongoNetworkTimeoutError: connection timed out
at connectionFailureError (/var/www/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:383:20)
at TLSSocket.<anonymous> (/var/www/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
```

No idea what is happening here because application code is idential between Meteor versions so it cannot have anything to do with Atlas or our servers etc. The only obvious related thing is the Mongo package version update.

**Comment by paulincai** [comment]
@dovydaskukalis could you please share your connection options. 
```mongodb+srv://xxx:yyy@aaa.bbbb.mongodb.net/meteor?option1&option2&option3 ...```
Or maybe you have the options in your settings.json.

**Comment by dovydaskukalis** [comment]
Tried Meteor 2.8.2 and it's running just fine for more than a week now. This is one of the weirdest issues I have ever had and hopefully it's finally gone...
