### ISSUE TITLE
Heads Up: programmatic api removed in npm v8.0.0

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#12016]
Heads up this is something that will need to be addressed...

I wanted to start using the `npm` `workspaces` feature which was introduced in `npm@7`.  So installed the latest `npm` into my `METEOR@2.7.1` distribution `meteor npm install -g npm` which loaded `npm@8.7.0`.

When I built I got this error message (I assume this is because I use `Npm.depends` in my packages)

```
.meteor/packages/meteor-tool/.2.7.1.19druq0.cywx++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/index.js:4
  throw new Error('The programmatic API was removed in npm v8.0.0
  ^

Error: The programmatic API was removed in npm v8.0.0
```

### Environment
Meteor: v2.7.1
Node: 14.19.1
Ubuntu: 20.04.4 LTS

**Comment by StorytellerCZ** [comment]
@brucejo75 thanks a lot for this report! That is not going to be pretty for us.

**Comment by rj-david** [comment]
https://github.com/npm/feedback/discussions/598

**Comment by StorytellerCZ** [comment]
@Grubba27 just want to ping on this to get get you aware of this and get your thoughts.

**Comment by Grubba27** [comment]
Thanks for the ping.
Well, for some time, I thought we did something like this:

https://github.com/meteor/meteor/blob/5e5fc1d958e9cfea2cb962f43ccf1fbc7abd7951/scripts/admin/update-semver/index.js#L12-L34

but we use the npm api. For now, it is okay. But when meteor 3 hits, we should have a migration path ready for it(mostly change the legacy API calls for this kind of utility).

**Comment by Grubba27** [comment]
Hey @brucejo75 can you test this using `meteor@3.0-alpha.11`? we think we have solved it for 3.0(is using npm 8)

**Comment by StorytellerCZ** [comment]
@Grubba27 I think this has been taken care of unless I am missing something. Do we have anything that the community needs to know in regards to this (any deprecation or functionality removals)?

**Comment by Grubba27** [comment]
For 3.0 all looks good from what I know https://github.com/meteor/meteor/blob/008c52df58bc0d2e3f0f1716d968a62482c135b4/scripts/build-dev-bundle-common.sh#L11
