### ISSUE TITLE
Unable to download bundle (403)

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#12021]
I'm trying to download the bundle for 2.5.7-beta.0 - the install script downloads fine: https://install.meteor.com/?release=2.5.7-beta.0, but when trying to access the generated `https://static-meteor.netdna-ssl.com/packages-bootstrap/2.5.7-beta.0/meteor-bootstrap-os.linux.x86_64.tar.gz` I get a 403. 

I need 2.5.7 to resolve the build issue here: https://github.com/meteor/meteor/issues/11905 and can't go to 2.6.1 due to the huge mongo API change.

The wild part: I installed 2.5.7-beta.0 on a different machine 1 hour ago, and it worked totally fine :O

**Comment by znewsham** [comment]
Note: when I installed 2.5.7 it was from an existing install, which is probably the difference

**Comment by denihs** [comment]
Hi @znewsham, do you need to go specifically to the beta version? Why not the final release version of 2.5.7?

Also, if you're trying to run from the checkout or something like that, maybe you can get the code from here https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%402.5.7-beta.0. Each release creates a tag, so perhaps it's this what you're looking for.

**Comment by znewsham** [comment]
@denihs I do not, is there a non-beta version? I don't see it in the changelog and the URL doesn't work - I'd love a non-beta version!

**Comment by fredmaiaarantes** [comment]
> @denihs I do not, is there a non-beta version? I don't see it in the changelog and the URL doesn't work - I'd love a non-beta version!

Version 2.5.7 was never out, it has been canceled in favor of releasing the version 2.6. So the nearest valid versions are 2.6 and 2.5.6 @znewsham, @denihs.

**Comment by znewsham** [comment]
Right - but as I mentioned, I can't take 2.6 because of the huge breaking changes it will incur @fredmaiaarantes

**Comment by donstephan** [comment]
I'm in the same boat here. Huge changes to jump to 2.6 (namely breaking issues in packages). Is there any chance 2.5.7 is going to get released? 2.5.6 works fine but initial build times are extremely slow.

**Comment by denihs** [comment]
@znewsham @donstephan Hey guys, which commands are you running? For instance, I did some tests where I created a new app using the command `meteor create --release 2.5.7-beta.0` and updated a project from 2.5.6 to 2.5.7-beta.0 by running the command `meteor update --release 2.5.7-beta.0`. 

I was also able to compare the build time between the two versions (2.5.6 and 2.5.7-beta.0), and it's about 5x faster.

**Comment by znewsham** [comment]
no dispute - it's faster, the problem is this doesn't work:

```RUN bash -c "curl https://install.meteor.com/?release=2.5.7-beta.0 --output /tmp/install-meteor.sh"```


which we use as part of a docker script to install the correct version of meteor. We can manage by downloading 2.5.6 then relying on the apps .meteor/release file to re-install 2.5.7, but it's...weird...

I also, can't understand the reluctance to release it?

**Comment by denihs** [comment]
Hey @znewsham, I was able to publish the tarballs for version `2.5.7-beta.0`. So now you should be able to run your `command RUN bash -c "curl https://install.meteor.com/?release=2.5.7-beta.0 --output /tmp/install-meteor.sh"`.

Could you test it and let me know if it works?

**Comment by znewsham** [comment]
@denihs Amazing, this is working great - thanks!
