### ISSUE TITLE
Account package

### ISSUE THREAD

**Issue by KheireddineAzzez** [meteor/meteor#12030]
- [Accounts.createUserVerifyingEmail is not a function
    at creatuser ] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [METEOR@2.7.1 ] The version of Meteor showing the problem.
- [ Windows] The operating system you're running Meteor on.
- [ Accounts.createUserVerifyingEmail is not a function
    at creatuser] The expected behavior.

![image](https://user-images.githubusercontent.com/59838139/167324901-c996de9a-ee48-44ee-93b9-eee442bf3fe7.png)
**The function in use:**
![image](https://user-images.githubusercontent.com/59838139/167325019-d1be4f31-2ba3-4199-afcd-3bfe3ba05c9c.png)

**My current packages:**
![image](https://user-images.githubusercontent.com/59838139/167325080-4f7909af-f6b5-41ac-bc50-41ea986e7376.png)

-->

**Comment by guncebektas** [comment]
The method Accounts.createUserVerifyingEmail is a server side method. You can check the doc https://docs.meteor.com/api/passwords.html  for more
