### ISSUE TITLE
Log errors from dynamic import 'ENOENT: no such file or directory...'

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#12041]
Our production logs get a good daily dose of logs such as this:

```
Error: ENOENT: no such file or directory, open '/built_app/programs/web.browser/dynamic/node_modules/meteor/svelte_sortable/node_modules/sortablejs/Sortable.js'
    at Object.openSync (fs.js:497:3)
    at readFileSync (fs.js:393:35)
    at read (packages/dynamic-import.js:209:29)
    at walk (packages/dynamic-import.js:160:14)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
    at packages/dynamic-import.js:167:22
    at Array.forEach (<anonymous>)
    at walk (packages/dynamic-import.js:165:23)
```

The files that are claimed to be missing seem completely random, there is no logic.

I thought maybe these are due to a stale client loading on a device and attempting to import code before realising that a reload is required to fetch a new version of the app? Don't know, just a guess.

- The version of Meteor showing the problem: 2.6.1
- The operating system you're running Meteor on: Ubuntu 20.04
- The expected behavior: No errors from dynamic import
- The actual behavior: Weird errors about missing files

**Comment by denihs** [comment]
Hi @arggh,

This is not an error related to Meteor, but in most cases, you just need to reset your project.

Try to run the following commands inside your project's root path:

$> meteor reset
$> rm -rf node_modules
$> meteor npm install

And then deploy your app again.

**Comment by arggh** [comment]
I'd love to understand what the root cause is, if you'd be so kind and elaborate a bit? I find it strange, if it's not related to Meteor, but resetting the Meteor project fixes it?

**Comment by denihs** [comment]
It usually happens if you forget to run `meteor npm install` before deploying the application and still import the package. The app will try to find the code, but it won't find it. Hence the error.

Some examples: [1](https://forums.meteor.com/t/meteor-error-enoent-nosuch-file-or-directory-open/43594), [2](https://github.com/meteor/meteor/issues/11690).

I think in this case, it's best to reset everything and try again. That's why I asked you to run the commands above.

Let me know if it works.

**Comment by arggh** [comment]
> It usually happens if you forget to run meteor npm install before deploying the application and still import the package. The app will try to find the code, but it won't find it. Hence the error.

Seems highly unlikely in our case, since
- some of these errors complain about a missing file in the `svelte` package and I'm 100% certain we have `svelte` installed, it's a Svelte app, after all
- the rest are mostly complaints about missing files in our local Meteor packages, even the one in the example provided above is actually a dependency pulled by a local Meteor package

I did reset everything and deploy again, though, so let's see 🤷‍♂️

**Comment by arggh** [comment]
For example, this:

```
Error: ENOENT: no such file or directory, open '/built_app/programs/web.browser/dynamic/node_modules/meteor/arggh_tools-models/cloud_images.js'
```

...is a local Meteor package.

**Comment by denihs** [comment]
Aren't you able to reproduce this locally? It may have to do with how you're importing these files. 

Could you share how you're using them?

Without a reproduction or some code snippet, it's hard to guess what could be wrong.

**Comment by arggh** [comment]
These only happen on production servers. Also, some of the errors are complaining about files that really aren't imported anymore, at all, which is why I suspected the issue was somehow related to clients running old/stale versions of our app while returning to the site.

For example, a recent error from today:

```
Error: ENOENT: no such file or directory, open '/built_app/programs/web.browser/dynamic/node_modules/meteor/arggh_tools-models/cloud_images.js'
```

...but we don't (anymore) have `cloud_images.js` inside `arggh:tools-models`. We used to have, but not anymore, for several versions now.

A regexp search from our codebase shows that we don't have this import **anywhere**.

**Comment by denihs** [comment]
I see... so you're saying your clients are running some old version of your system, and these old versions are trying to get files that don't exist anymore? I think that would make sense, but I don't see how we could help you here...

Please let me know if it's not this.

**Comment by arggh** [comment]
> I think that would make sense, but I don't see how we could help you here...

I'm not looking for help. I'm trying to report a possible bug in Meteor.

**Comment by ToyboxZach** [comment]
I expected it to be from just updating our server, but I was getting this logs about 10 hours after I updated the server. I don't know why anyone would be on old client code at that point.

It is very few instances of it compared to the number of users we have so I am kind of confused.

**Comment by arggh** [comment]
@denihs I managed to solve this mystery.

The problem involved dynamic imports, load balancer + multiple servers, changing subdomains for the same app, sticky sessions via cookies and a missing config option from `settings.json` all while deploying apps sequentially.

1. App was running in domain base.app.com, but also in a.app.com, b.app.com, c.app.com etc...
2. App was using dynamic imports
3. Dynamic import tries to fetch new code from `ROOT_URL` (aka base.app.com), but since user is on a.app.com, a different "site", `fetch` omits cookies...
4. ...thus breaking the sticky session, causing the client to potentially fetch code from a server running a different version of the app (if a deployment was currently taking place)

**Solution:**

```
{
  "public": {
      "packages": {
        "dynamic-import": {
          "useLocationOrigin": true
        }
      },
      ....
```

So, in hindsight should have been "obvious", but it could possibly be a good idea to improve dynamic import docs with a warning of some kind.

If the client fetches the "bad" modules via dynamic import, those do get persisted to indexedDB and will further break the app down the road when the `fetch` problem is cured. Only clearing IndexedDB from client storage resolved this situation.
