### ISSUE TITLE
Accounts.requestLoginTokenForUser fails silently if email address is capitalised

### ISSUE THREAD

**Issue by mikowals** [meteor/meteor#12040]
A request like below from the client, fails silently.  I believe it is the capital first letter in the email causing the failure.

```
Accounts.requestLoginTokenForUser({
  selector: 'Bob@example.com',
  userData: { email: 'Bob@example.com'}
})
```

### Independent packages

The only package added was `accounts-passwordless`.

### Reproduction

In Meteor 2.7.2, I created [a reproduction](https://github.com/mikowals/case-sensitive-email-bug) that fails on my M1 MacBook.  

To run the reproduction: 

```
git clone https://github.com/mikowals/case-sensitive-email-bug.git`
cd case-sensitive-email-bug
meteor
```

Browse to `http://localhost:3000` to trigger the client startup callback.  The startup requests two login tokens: one for a capitalised email and one for a lowercase email.  On the client it appears both succeed with a result being returned.  On the server there is no evidence of the capitalised email request.

**Comment by denihs** [comment]
Hi @mikowals, as you can see in the out put below, it works normally... It will "fail" silently probably [here](https://github.com/meteor/meteor/blob/0d46d56adf9c554789d9382093588a446772b7b1/packages/accounts-passwordless/passwordless_server.js#L182-L191) if the email provided isn't inside the user, meaning that the email `Bob@example.com` is considered different from `bob@example.com`. 

Make sure you're testing this with a clean base. To restart your local base, running at 3001, you can run a `meteor reset` and rerun your app. Everything should work.

But to avoid this type of situation my advice for you is to always normalize the emails before sending them to the server. Something like `email.toLowerCase().trim()` should solve most of the problems regarding things like this.

<details >
<summary>Output</summary>
<br>
=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
=> Client modified -- refreshing
I20220517-17:13:20.714(-4)? send true
I20220517-17:13:20.737(-4)? ====== BEGIN MAIL #0 ======
I20220517-17:13:20.738(-4)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20220517-17:13:20.738(-4)? Content-Type: multipart/alternative;
I20220517-17:13:20.738(-4)?  boundary="--_NmP-8549e8fc9ad20676-Part_1"
I20220517-17:13:20.738(-4)? To: bill@example.com
I20220517-17:13:20.739(-4)? Subject: Your login token for undefined
I20220517-17:13:20.739(-4)? Message-ID: <1c8f2533-432d-6711-3a1b-2e0191a115bb@denyhs>
I20220517-17:13:20.739(-4)? Date: Tue, 17 May 2022 21:13:20 +0000
I20220517-17:13:20.739(-4)? MIME-Version: 1.0
I20220517-17:13:20.739(-4)? 
I20220517-17:13:20.739(-4)? ----_NmP-8549e8fc9ad20676-Part_1
I20220517-17:13:20.739(-4)? Content-Type: text/plain; charset=utf-8
I20220517-17:13:20.739(-4)? Content-Transfer-Encoding: quoted-printable
I20220517-17:13:20.740(-4)? 
I20220517-17:13:20.740(-4)? Hello!
I20220517-17:13:20.740(-4)? 
I20220517-17:13:20.740(-4)? Type the following token in our login form to get logged in:
I20220517-17:13:20.740(-4)? 101138
I20220517-17:13:20.740(-4)? Or if you want, you can click the following link to be automatically logged=
I20220517-17:13:20.741(-4)?  in:
I20220517-17:13:20.741(-4)? http://localhost:3000/?loginToken=3D101138&selector=3Dbill@example.com
I20220517-17:13:20.741(-4)? 
I20220517-17:13:20.741(-4)? Thank you!
I20220517-17:13:20.741(-4)? 
I20220517-17:13:20.741(-4)? ----_NmP-8549e8fc9ad20676-Part_1
I20220517-17:13:20.741(-4)? Content-Type: text/html; charset=utf-8
I20220517-17:13:20.742(-4)? Content-Transfer-Encoding: quoted-printable
I20220517-17:13:20.742(-4)? 
I20220517-17:13:20.742(-4)? Hello!<br/>
I20220517-17:13:20.742(-4)? 
I20220517-17:13:20.742(-4)? Type the following token in our login form to get logged =
I20220517-17:13:20.742(-4)? in:<br/><br/>
I20220517-17:13:20.742(-4)? 101138<br/><br/>
I20220517-17:13:20.743(-4)? Or if you want, you can click the following =
I20220517-17:13:20.743(-4)? link to be automatically logged in:<br/><br/>
I20220517-17:13:20.743(-4)? http://localhost:3000/?=
I20220517-17:13:20.743(-4)? loginToken=3D101138&selector=3Dbill@example.com<br/>
I20220517-17:13:20.743(-4)? 
I20220517-17:13:20.743(-4)? Thank you!
I20220517-17:13:20.743(-4)? 
I20220517-17:13:20.743(-4)? ----_NmP-8549e8fc9ad20676-Part_1--
I20220517-17:13:20.744(-4)? ====== END MAIL #0 ======
I20220517-17:13:20.744(-4)? 
I20220517-17:13:20.744(-4)? Login Token url: http://localhost:3000/?loginToken=101138&selector=bill@example.com
I20220517-17:13:20.744(-4)? send true
I20220517-17:13:20.745(-4)? ====== BEGIN MAIL #1 ======
I20220517-17:13:20.745(-4)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20220517-17:13:20.745(-4)? Content-Type: multipart/alternative;
I20220517-17:13:20.745(-4)?  boundary="--_NmP-377496f2728614d4-Part_1"
I20220517-17:13:20.746(-4)? To: Bob@example.com
I20220517-17:13:20.746(-4)? Subject: Your login token for undefined
I20220517-17:13:20.746(-4)? Message-ID: <7cf55ff3-fad0-d405-f928-8cbc98ed85a3@denyhs>
I20220517-17:13:20.746(-4)? Date: Tue, 17 May 2022 21:13:20 +0000
I20220517-17:13:20.746(-4)? MIME-Version: 1.0
I20220517-17:13:20.746(-4)? 
I20220517-17:13:20.746(-4)? ----_NmP-377496f2728614d4-Part_1
I20220517-17:13:20.746(-4)? Content-Type: text/plain; charset=utf-8
I20220517-17:13:20.747(-4)? Content-Transfer-Encoding: quoted-printable
I20220517-17:13:20.747(-4)? 
I20220517-17:13:20.747(-4)? Hello!
I20220517-17:13:20.747(-4)? 
I20220517-17:13:20.747(-4)? Type the following token in our login form to get logged in:
I20220517-17:13:20.747(-4)? C05CB1
I20220517-17:13:20.747(-4)? Or if you want, you can click the following link to be automatically logged=
I20220517-17:13:20.747(-4)?  in:
I20220517-17:13:20.747(-4)? http://localhost:3000/?loginToken=3DC05CB1&selector=3DBob@example.com
I20220517-17:13:20.747(-4)? 
I20220517-17:13:20.747(-4)? Thank you!
I20220517-17:13:20.748(-4)? 
I20220517-17:13:20.748(-4)? ----_NmP-377496f2728614d4-Part_1
I20220517-17:13:20.748(-4)? Content-Type: text/html; charset=utf-8
I20220517-17:13:20.748(-4)? Content-Transfer-Encoding: quoted-printable
I20220517-17:13:20.748(-4)? 
I20220517-17:13:20.748(-4)? Hello!<br/>
I20220517-17:13:20.748(-4)? 
I20220517-17:13:20.748(-4)? Type the following token in our login form to get logged =
I20220517-17:13:20.748(-4)? in:<br/><br/>
I20220517-17:13:20.748(-4)? C05CB1<br/><br/>
I20220517-17:13:20.749(-4)? Or if you want, you can click the following =
I20220517-17:13:20.749(-4)? link to be automatically logged in:<br/><br/>
I20220517-17:13:20.749(-4)? http://localhost:3000/?=
I20220517-17:13:20.749(-4)? loginToken=3DC05CB1&selector=3DBob@example.com<br/>
I20220517-17:13:20.749(-4)? 
I20220517-17:13:20.749(-4)? Thank you!
I20220517-17:13:20.749(-4)? 
I20220517-17:13:20.749(-4)? ----_NmP-377496f2728614d4-Part_1--
I20220517-17:13:20.749(-4)? ====== END MAIL #1 ======
I20220517-17:13:20.749(-4)? 
I20220517-17:13:20.749(-4)? Login Token url: http://localhost:3000/?loginToken=C05CB1&selector=Bob@example.com

</details>

**Comment by mikowals** [comment]
You are correct and I must have run it once to set up the database with the existing lowercase email to trigger the failure.  And yes, setting the email to lowercase is how I have I have worked around this behaviour after discovering it.

Based on [the lengthy discussion of lowercasing here](https://guide.meteor.com/accounts.html#case-sensitivity), I expected that this was being handled within the method.  Would a pull request to make that check you highlighted case insensitive be accepted? 

The alternate fix would be to throw an error when the email can't be sent and to update the documentation so people expect it.

**Comment by denihs** [comment]
This matter of case sensitivity has lots of discussions. This is an example https://github.com/meteor/meteor/pull/11419, and the decision is to keep it as it is. You could open a PR, but all the implications and scenarios must be well tested. But I think it would make sense if in this [line](https://github.com/meteor/meteor/blob/0d46d56adf9c554789d9382093588a446772b7b1/packages/accounts-passwordless/passwordless_server.js#L185) we made everything lower case. But we have to test it.

For now, I'm closing this issue.

**Comment by mikowals** [comment]
Why is failing silently the correct behavior when no token is generated for the user?

**Comment by denihs** [comment]
Hey @mikowals, it's not. I closed because I thought you would proceed with the PR, but it's best to keep it open. I will check on this and open a PR with the fix.

Thank you!

**Comment by mvogttech** [comment]
My .02 here is that any type of authentication solely utilizing email addresses, like in accounts-passwordless, she not be case sensitive because email itself is not case sensitive.

This could be considered a security flaw due to user spoofing on platforms where users interact with one-another.

**Comment by denihs** [comment]
PR opened here https://github.com/meteor/meteor/pull/12047. Later today we'll release a new beta version with this change to be tested.

Hey @mvogttech, about your comment, I think you were concerned that we used `.toLowerCase()` [here](https://github.com/meteor/meteor/blob/0d46d56adf9c554789d9382093588a446772b7b1/packages/accounts-passwordless/passwordless_server.js#L185), correct? Thinking again, I went in another direction, as you can see in the PR. 

If it's not this, please let me know. I'm not sure I've understood your comment 100%.

**Comment by mikowals** [comment]
Thanks for fixing this!  I confirmed the problem doesn't occur in release 2.7.3.
