### ISSUE TITLE
When `The Mongo server and the Meteor query disagree on how many documents match your query.`, socket is broken.

### ISSUE THREAD

**Issue by chneau** [meteor/meteor#12063]
Using Meteor 2.7.3 on windows for development and debian/kubernetes for production.

Expected behavior: Do something else: Get an error, or close the connection and reconnect, make the client aware, or let the client as is, like a regular error that can happen on a publish.
Actual behavior: The client can't send anything back to the server.

Minimal reproduction:
https://github.com/chneau/meteor-bug 
```bash
npm i
npm start
```
On the UI you'll see ways to create links via methods or Collection (allowed server side), and a button to trigger the bug.
The bug is basically subscribing to a publish that trigger a specific mongo error.

```ts
const invalidDate = new Date("");
Meteor.publish("links.bugged", () => LinksCollection.find({ $or: [{ createdAt: { $gte: invalidDate } }] }));
```

Which trigger this error:

```bash
The Mongo server and the Meteor query disagree on how many documents match your query. Cursor description:  CursorDescription {
  collectionName: 'links',
  selector: { '$or': [ [Object] ] },
  options: { transform: null }
}
```

Unfortunately, I was not able to reproduce the exact same error I have on production:
> When the error happens from any client, all clients loose the "real time" part.
They can still call methods to mutate data, but they need to refresh the page to actually see the changes.
This was fixed by ensuring the dates passed to the publishes are not invalid/null.
>> It was looking like the server lost connection with the oplog, and no more real time updates was happening. 

If you try to subscribe to a publish that raise an error:
```ts
Meteor.publish("links.error", () => {
  throw new Error("Error");
});
```
At least the client can still do things, but not with the `Meteor query disagree` one.

**Comment by radekmie** [comment]
What exactly happens when this "disagree error" occurs? Is it the same as throwing an error in the publication? Or does it hang the server, i.e., the user cannot continue? If so, the fix should be rather easy, I think.

**Comment by chneau** [comment]
On the minimal reproduction it hangs the client silently. When looking at the websocket, the client don't send any method or publish message anymore.

On production, when a client triggered the malformed publish, all clients lost the live data.

**Comment by snowwolfjay** [comment]
I meet same error when use a optional selector at some (not know case): { channel:undefined ,scope:'xxx'}, which means when give a specific channel publish data under a scope and the channel, otherwise publish data under the scope and all channel. fixed by use  ...(channel?{channel}:{}) speard .
