### ISSUE TITLE
Improve the documentation and error message of `--container-size`

### ISSUE THREAD

**Issue by lilithkarapetyan** [meteor/meteor#12060]
When deploying from CLI, `--container-size` is only available in case `--plan` option is specified, otherwise it throws an error with message `Error deploying application: Internal error`. The documentation needs to indicate this relation between `--plan` and `--container-size` and in case of forgetting the `--plan` option, the error message needs to be more descriptive and informative.

Meteor version: 2.6.1

**Comment by Ayushi96** [comment]
@Grubba27  Could you assign this issue to me?

**Comment by Grubba27** [comment]
This was solved! will be closing this one
