### ISSUE TITLE
Passwordless - Invalid options

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#12074]
Options in Passwordless such as:
https://github.com/meteor/meteor/search?q=tokenSequenceLength

Don't seem to have been added to the Accounts-base package (accounts_common.js line 4-17): https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js

This results in this server side error: " Error: [Accounts.config: Invalid key: tokenSequenceLength]"

**Comment by denihs** [comment]
Fixed on https://github.com/meteor/meteor/pull/12088.

Just need to run `meteor update accounts-passwordless accounts-base`.
