### ISSUE TITLE
Minification error from 2.4.1 to 2.5.8

### ISSUE THREAD

**Issue by radekmie** [meteor/meteor#12070]
In one of our projects, we're still using the old `kadira:flow-router@2.12.1`. It works for us well and we don't feel the urge to migrate off it. But now I wanted to update our project to the latest pre-2.6 version (we're still behind the schedule with the MongoDB driver), and it fails.

The error says "redirect needs to be done in sync", and comes from [`runTriggers`](https://github.com/kadirahq/flow-router/blob/618b8eba24fedfa32f26153379ddad37d4e7f08b/client/triggers.js#L67-L112).

Now, here's the minified code from 2.4.1:
```js
h.runTriggers = function(t, e, r, n) {
    for (var i = !1, o = !0, a = !1, s = 0; s < t.length; s++) {
        var u;
        if ((0,
        t[s])(e, c, p),
        i)
            return
    }
    function c(t, e, n) {
        if (a)
            throw new Error("already redirected");
        if (!o)
            throw new Error("redirect needs to be done in sync");
        if (!t)
            throw new Error("trigger redirect requires an URL");
        i = !0,
        a = !0,
        r(t, e, n)
    }
    function p() {
        i = !0
    }
    o = !1,
    n()
}
```

And from 2.5.8:
```js
h.runTriggers = function(t, e, r, n) {
    for (var i = !1, o = !0, a = !1, s = 0; s < t.length; s++) {
        var u;
        if ((0,
        t[s])(e, c, p),
        i)
            return
    }
    function c(t, e, r) {
        if (a)
            throw new Error("already redirected");
        throw new Error("redirect needs to be done in sync")
    }
    function p() {
        i = !0
    }
    o = !1,
    n()
}
```

Most importantly, variable `o` vanishes in the latter. We're using `zodern:standard-minifier-js@4.1.1`, but the same happens with `standard-minifier-js@2.8.0`. (Downgrading them causes different errors.)

**Comment by zodern** [comment]
@harryadel and I published a fork of flow router that rewrites this function to avoid the minifier bug: https://atmospherejs.com/montiapm/flow-router

Some more information for this bug is in https://github.com/meteor/meteor/issues/11756.

**Comment by radekmie** [comment]
OK, it worked, thanks! We can close it as the workaround is pretty straightforward (although I couldn't find #11756 while looking for an existing report).
