### ISSUE TITLE
--port option value is not reflected in the App running at: message

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#12089]
Hi, I am having problems when I try to start my meteor app in a different port from 3000. I am getting this error in the js console:

![image](https://user-images.githubusercontent.com/39581375/179382889-0277af26-c727-4ddd-bb4d-51d55001285c.png)

Besides, it is not showing the correct port at the end.

````shell
/usr/local/bin/doppler run -- yarn start
yarn run v1.22.17
$ meteor run --port 4000
[[[[[ ~/Documents/logos-admin ]]]]]

=> Started proxy.
=> Started HMR server.
=> Started your app.

=> App running at: http://localhost:3000
````

Meteor 2.7.3
Node 14.19.1

**Comment by StorytellerCZ** [comment]
Strange, I'm running on custom port all the time and it is working fine. Is there something specific about your Meteor setup?

**Comment by diavrank** [comment]
mmm I don't know, I tried to run 2 meteor apps at the same time, one on port 3000 (meteor-react app) and the other on port 3600 (meteor-vue app), and the vue app had this error:

![image](https://user-images.githubusercontent.com/39581375/179421485-dea590ab-78f2-4fd0-99ce-411a19b7c4bc.png)

So, I tried to change the port of the meteor-react app to port 4000, but it got the error showed on my first [comment](https://github.com/meteor/meteor/issues/12089#issue-1306977624). So, I had to run the apps one per one to use the port 3000 to make them working.

this is the output of the meteor-vue app:

````shell
doppler run -- yarn start --port 3600
yarn run v1.22.17
$ meteor run --port 3600
[[[[[ ~/Documents/spa-cover-admin ]]]]]

=> Started proxy.
=> Meteor 2.7.3 is available. Check the changelog
https://docs.meteor.com/changelog.html and update this project with 'meteor
update'.
=> [HMR] Dev server listening on port 3603.
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
=> Started your app.

=> App running at: http://localhost:3000
````

Meteor-Vue app is using Meteor 2.7.2.
Meteor-React app is using Meteor 2.7.3.

I'm using Mac 12.4

**Comment by diavrank** [comment]
I think I found the cause of the problem. I'm using Doppler as a Secrets Manager, I forgot I was using the PORT environment variable, I was trying to change it with --port option from the command line, so, I guess if I only change environment variable I can solve that problem.

**Comment by diavrank** [comment]
Finally I found the cause of the problem, I had to update the next environment variables in Doppler:

ROOT_URL=http://localhost:3600
PORT=3600

Likewise, I had to specify the option `--port` in the yarn script, so, I could get the desired result:

```shell
doppler run -- yarn start
yarn run v1.22.17
$ meteor run --port 3600
[[[[[ ~/Documents/spa-cover-admin ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3603.
=> Meteor 2.7.3 is available. Check the changelog
https://docs.meteor.com/changelog.html and update this project with 'meteor
update'.
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
=> Started your app.

=> App running at: http://localhost:3600
```
