### ISSUE TITLE
 Cannot find module 'reify/lib/runtime'

### ISSUE THREAD

**Issue by a873054267** [meteor/meteor#12094]
I want to publish my project;
1: execute meteor build  ../output
2: tar -zxvf xxx.gz
3: cd the bundle and execute node main.js
![image](https://user-images.githubusercontent.com/30728610/180714647-5fcbb14f-4892-4bbb-845e-986af373e899.png)

**Comment by a873054267** [comment]
should execute npm install

**Comment by cuixiaotu** [comment]
i don't konw why need execute npm install again
