### ISSUE TITLE
Cursor.observe 'changed' callback is fired twice and with invalid documents - changed(newDocument, oldDocument)

### ISSUE THREAD

**Issue by wolasss** [meteor/meteor#12098]
# Reproduction repository

https://github.com/wolasss/meteor-cursor-observe-changed-bug (meteor react example)

Steps: 

1. run `meteor`
2. Go to the app, click on link 
3. Inspect console.log

# Description

I noticed that recently my meteor application was throwing an error, and I successfully traced the issue: 

[Cursor.observe](https://docs.meteor.com/api/collections.html#Mongo-Cursor-observe) 'changed' is called multiple times with invalid documents as parameters `(newDocument, oldDocument)`. 

Consider https://github.com/wolasss/meteor-cursor-observe-changed-bug repository which is a meteor react application created to reproduce this bug (`meteor create --react`).

The initial state of the application is that there are a few links in the collection, but I modified each link with the additional property `params: { a: 1, b: 2, c: 3 }`. If you start the application, and click on a link it will trigger an update to the link document, updating its `params` property (using $set) to ```{
                  a: 5,
                  d: 5,
                  e: new Mongo.ObjectID('5f953cde8ceca90030bdb86f')
              }```

Now if you observe the cursor `LinksCollection.find()` and provide changed callback as such:

```
cursor.observe({
          changed: (newDocument, oldDocument) => {
              console.log('changed', newDocument, oldDocument);
          }
});
```

you will notice that on every click it is fired TWICE, the first call is a valid call where `newDocument` has correct `params` property (the same as updated using $set), and `oldDocument` has an old params property. but THE SECOND call (why is it even called twice?) is called with some kind of union of two (old and new) as `newDocument`: 

```
{
    "a": 5,
    "b": 2,
    "c": 3,
    "d": 5,
    "e": {
        "_str": "5f953cde8ceca90030bdb86f"
    }
}
``` 

where, `oldDocument` is ```a: 1
b: 2
c: 3```

Please note, that Mongo.ObjectID() was casted to regular object with `_str` property.  

# The expected behavior 

1) The changed callback should be called only once with:

newDocument's params property: 

```
{
                  a: 5,
                  d: 5,
                  e: new Mongo.ObjectID('5f953cde8ceca90030bdb86f')
}
```

oldDocument's params property:
```
 { a: 1, b: 2, c: 3 }
```

2) The newDocument and oldDocuments properties of type Mongo.ObjectID should not be casted to regular objects

# The version of Meteor showing the problem

tested on 2.7.3 

# The last version of Meteor where the problem did _not_ occur

2.5.5 (didn't check 2.5.6, 2.5.7 - couldn't start mongo)

Change release to 2.5.5 and reproduce steps

# The operating system you're running Meteor on

MacOS 10.14.3

# Notes

This bug is quite a significant performance issue since every changed callback is fired twice (especially for those who use publish composite and depend on that callback). Not to mention that the received `newDocument` is invalid and if it has Mongo.ObjectID as a property it will be casted to a regular object causing additional bugs if one uses methods of ObjectID on that object

**Comment by radekmie** [comment]
I looked into it, and it has nothing to do with the `ObjectId`. The problem is still there even if you make it as simple as `Links.update(id, {$set: {params: {d: 5}}})`. As I checked, it looks like it's again a problem with the oplog converter, as while the input looks like this: `{"$v":2,"diff":{"u":{"params":{"d":5}}}}`, the output is clearly incorrect: `{"$v":2,"$set":{"params.d":5}}`. I'll create a PR for that.

**Comment by radekmie** [comment]
@wolasss It's all good. I already have the fix ready, and the `ObjectId` is correctly preserved (it's not casted to a plain object).
