### ISSUE TITLE
Running Cordova simulator only shows background or white page

### ISSUE THREAD

**Issue by crudenorway** [meteor/meteor#12108]
Tried running Cordova in the Svelte simple-todo app, but it does not work properly. Running `meteor run ios` makes the simulator open, but only the background is shown, not the actual app.

Tried with my own app too, but only a white page is showing.

I suspect that there is some incompatibilities with my hardware/OS and Cordova?

Meteor version 2.7.3
Xcode version 13.4
OS: macOS Monterey(12.0.1) on a M1 mac

Others having the same issue?

Easy to reproduce, just install step 11 from Svelte tutorial and run `meteor run ios`.

**Comment by crudenorway** [comment]
Suddenly after hours of debugging, it seems like this simple command solves it all:

```
$ cd imports
$ ln -s ../node_modules/svelte/
```

Credit:
https://forums.meteor.com/t/converted-a-project-to-svelte-ama/54282

This command should be added to the Svelte guide maybe?

**Comment by Grubba27** [comment]
Hello there! I have some great news on this issue. to solve this and run on Cordova, you should place this extra configuration in your ``package.json``:

```json

{
  ...

  "meteor": {
    "mainModule":{...},
    "nodeModules": {
      "recompile": {
        "svelte": ["legacy"]
      }
    }
  }
} 

```
Also, I’ve added to our skeleton with svelte in case someone has the same issue.
It will be available in future releases.
Best regards, and I will be closing this issue :)
