### ISSUE TITLE
Mongodb client.topology is undefined

### ISSUE THREAD

**Issue by denihs** [meteor/meteor#12118]
When testing the new Meteor version 2.8-beta.0 in one of our internal apps, an error came up on this [line](https://github.com/meteor/meteor/blob/54964c88e7843defd6e9fc25c894df715dcdad73/packages/mongo/mongo_driver.js#L203-L202). `self.client.topology` is undefined.

This app tries to connect to a MongoDB database in version 5.0.10.

I've tried version 2.8-beta.0 in an app that connects to a database in version 3.6, and it worked fine.

@radekmie thinks it looks like we should call `on` on the client itself and use the `topologyDescriptionChanged` event. 

We're going to test this theory soon.

**Comment by denihs** [comment]
Update on this:

@radekmie created this [PR](https://github.com/meteor/meteor/pull/12125) to solve this issue. Some tests are not passing, but we don't know for sure if it's related to the changes or not. 

It did work with the project where we first found the issue. But on another project, we started getting some errors like:

```
W20220810-11:55:46.694(-4)? (STDERR) (node:27991) UnhandledPromiseRejectionWarning: MongoServerSelectionError: self signed certificate
W20220810-11:55:46.704(-4)? (STDERR)     at Timeout._onTimeout (/home/denyhs/Documents/work/meteor/meteor/packages/npm-mongo/.npm/package/node_modules/mongodb/lib/sdam/topology.js:293:38)
W20220810-11:55:46.705(-4)? (STDERR)     at listOnTimeout (internal/timers.js:557:17)
W20220810-11:55:46.705(-4)? (STDERR)     at processTimers (internal/timers.js:500:7)
W20220810-11:55:46.706(-4)? (STDERR) (node:27991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
W20220810-11:55:46.706(-4)? (STDERR) (node:27991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 

We're investigating all the points mentioned above.

**Comment by radekmie** [comment]
@denihs, @Grubba27 I've made a small change in the PR and tested it again on a single node replica set - everything works fine. Then I tested it on a 3-node replica set and all tests have passed as well. Could you check it again?

**Comment by Grubba27** [comment]
Everything worked fine in the two projects I've tried, the branch. Except for the need to remove ``.await()`` from ``MongoInternals.RemoteCollectionDriver`` besides that, I believe things are ok
