### ISSUE TITLE
Client subscription goes out of sync when a nested object key is removed from db document

### ISSUE THREAD

**Issue by igal1c0de4n** [meteor/meteor#12114]
Help!
I notice weird subscriptions behavior with my meter v2.7.3 app (on macos locally and Linux in production). This may be a Meteor bug (I hope not!) 

Why?
The frontend app subscribes with a query to a publication which returns the full document (unrestricted projections).
I then externally updateOne the document which is clearly part of the query.
This is done via another nodejs+mongoose app, but can be reproduce manually with Robo3T.

The external updateOne uses $set to modify the doc. 
Expected result: the subscription will update the meteor client and findOne will return a document with the changes. 
Actual result: client side `findOne` returns a document without those changes.

Diving deeper, devtools DDP websocket traffic shows the server simply doesn't send the changes. 
As a result the client loses DB sync and client document data no longer matches the db document data.

The problem happens with a key under an object which has additional keys. 
For example:

```js
// before update, the document is:
{hash: {myValue: "hello", myOtherValue: "whaterver"}, ...}
``` 
When the key is removed from the hash using: 
```js
db.getCollection('story').updateOne(..., {$set: {hash: {myOtherValue: "whaterver"}}})
```
As this point, an update to the client is expected, however isn't sent from the Meteor server.

**Comment by Grubba27** [comment]
Hello there @igal1c0de4n can you provide a repo to reproduction?

**Comment by igal1c0de4n** [comment]
@Grubba27 I explained how to reproduce it. Anyone who's familiar a bit with meteor can spend 2 min on any existing project and reproduce it. 

If for some reason following those steps this isn't reproducible _everywhere_ I can create a github repo.

You may use the "no reproduction case - not working on it" approach and shelf this issue.
It'll probably be at the cost of affecting others who may not even understand this issue exist in their app and not know how to overcome it. But then again, this eventually hurts meteor.

Unfortunately I need to spend time working around this issue in my app (production).
If you are willing to go on screenshare I can show it to you on my project, or I can work with you to reproduce this on one of your existing projects. It's the best I can do now

**Comment by igal1c0de4n** [comment]
Perhaps useful, the issue occurs on mongodb5 
(5.0.7 locally and 5.0.10 on a mongodb.com cluster)

**Comment by igal1c0de4n** [comment]
Interesting, I could not reproduce this issue on with mongodb v4.4

**Comment by Grubba27** [comment]
Hello there!!  @igal1c0de4n  I’ve read the issue, and I think understood it and tested it in my own [repo](https://github.com/Grubba27/simple-todo-svelte)
If I’m doing something wrong, I would love to be able to change it to help, but if I understood your issue correctly, I has not able to reproduce it and you can even see the video as it follows me doing/following the

https://user-images.githubusercontent.com/70247653/182949139-f200ddd1-40a5-4ac1-99ad-58e37d45a30b.mov

 steps as you described them.

**Comment by igal1c0de4n** [comment]
@Grubba27 Thank you for testing this and providing the vid
 
I confirm the sequence of commands you run matches those I've described.

When I run a similar set of changes, the sequence results in no 'remove' update from the meteor server to the client.

Also, if in addition to the hash key removal I add or modify other fields in the hash, those changes are acknowledged by the Meteor server, however the response indicates the meteor server "imagines" that the removed key is still there.

For example, add a doc:
```js
db.getCollection('tasks').insert({_id: ... , hash: {a: 1, b: 2}})
```
Next subscribing to this document in the client, then in a mongo shell:
```js
db.getCollection('tasks').updateOne(_id, {$set: {hash: {b: 2, c: 3}}})
```
As expected, the db document is changed to: 
```js
{hash: {b: 2, c:3}}
```
Unexpectedly, the update sent to the client doesn't include the removal of the `a` key. 
Instead, it's sending something like this on the DDP:
```
a["{\"msg\":\"changed\",\"collection\":\"task\",\"id\":\"...uid...\",\"fields\":{\"hash\":{\"a\":\"1\",\"b\":\"2\",\"c\":3}}}"]
```
It literally sends `a` as if it's still there and hasn't been removed.

It's as if the server-side Meteor caches the document and incorrectly applies the oplog change: essentially applying a "merge" strategy to the data. It implies an assumption that a missing field in the `$set` object means it's previous value is kept vs removed.

Why your test isn't reproducing it - I also don't understand. 
From what I could tell the changes applied are very similar to the test I run. 
You tested against v5.0.6 which is older than v5.0.7 the db I tested against- but I doubt this is the issue (thou possible).
Do you have oplog configured? (I do)

I can confirm this issues started happening after I upgraded my mongodb.com Atlas cluster from v4.4 to v5.0.10 
I run a test on an online aws ec2 env:
1. Connecting it to the v5.0.10 Atlas 
2. Connecting it to the v4.4 Atlas. 
The issue definitely hasn't reproduced on the v4.4.

The problem is my production environment is already upgraded to v5.0.10. Downgrade isn't supported.
I created a new v4.4 cluster with the goal to replace my v5 production cluster. Issue is, Atlas does not support data migration from v5 to v4.4. IOW downgrade isn't possible 😞 

My only path forward is to help you reproduce the issue and deploy a Meteor fix, or refactor my app to work around the quirky behavior, which isn't trivial since my app is massive:  https://app.mapme.com

@Grubba27 If you are willing, I can quickly (in 2min) present the issue over screen-share. 
You may get an idea about the differences between our testing code/envs and figure out how to reproduce it. 

Please advise

**Comment by radekmie** [comment]
I haven't checked the reproduction, but isn't it similar to #12098? If so, it'll be fixed in the next version.

**Comment by paulincai** [comment]
> 

I suggest to delete all tickets with "fix my issue cause I'm busy" content or attitude ...

**Comment by igal1c0de4n** [comment]
@paulincai if you have fire in your living room but need to save the cars, would you have the fire department hang up on them just because they are unable to "reproduce the fire" in their testing facility?

**Comment by paulincai** [comment]
I see you edit your answers but mind you, the old versions remain. "meteor can spend 2 min" the exact 2 minutes that you can spend to do meteor create app, add a subscription and a publication etc.

It is not anyone's problem if something is burning anywhere.  You can always get a Meteor support package and have things burning 24/7.

The problem is bullying especially today with Rus bullying Ukr., Israel bullying Palestine, China on Taiwan etc etc... There is just too much of it everywhere and I will personally address it every time bullying shows up in the open source community. 0 tolerance to it!

Now that we agreed on the forum to just disregard each other's posts, I hope your issue gets solved soon and wish you all the best.

**Comment by igal1c0de4n** [comment]
Reproduction provided via https://github.com/meteor/meteor/issues/12119

Since this ticket contains unrefined/preliminary/testing info which may be confusing I'm ok with closing it and focusing on the new ticket.

**Comment by igal1c0de4n** [comment]
Reproduction provided via https://github.com/meteor/meteor/issues/12119

Since this ticket contains unrefined/preliminary/testing info which may be confusing I'm ok with closing it and focusing on the new ticket.
