### ISSUE TITLE
`meteor show meteor` command not updated since `v1.10.0`

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#12122]
I was trying to find out if `2.7.4` has been released.
- There is a branch `2.7.4`
- Only beta releases here: https://github.com/meteor/meteor/tags
- No `2.7.4` milestone here: https://github.com/meteor/meteor/milestones
- Thought I would check via `meteor show meteor`

`meteor show meteor` has not been updated since `v1.10.0`.

## Environment
`meteor@2.7.3`
OS: `ubuntu@20.04.4` using WSL

## Repro

```
$ meteor show meteor
```
Outputs:
```
Package: meteor@1.10.0
Maintainers: mdg
Exports: Meteor, global, meteorEnv

[Source code of released version](https://github.com/meteor/meteor/tree/master/packages/meteor) | [Source code of
development version](https://github.com/meteor/meteor/tree/devel/packages/meteor)
***

This is an internal Meteor package.

Recent versions:
  1.9.0   May 27th, 2018
  1.9.1   July 11th, 2018
  1.9.2   July 11th, 2018
  1.9.3   April 2nd, 2019       installed
  1.10.0  September 14th, 2021  installed

Older and pre-release versions of meteor have been hidden. To see all 338 versions, run
'meteor show --show-all meteor'.
```

## Expected
Expected to see all releases listed.

**Comment by zodern** [comment]
It is a little confusing, but `meteor show meteor` shows the information for the `meteor` Meteor package. To instead see the details of the official release track named METEOR, you can run `meteor show METEOR`.

**Comment by brucejo75** [comment]
D'oh, seems like I relearn this command every 6 months.  Closing and opening documentation issues...
