### ISSUE TITLE
removing fields from a document in mongo is not synchronized with client when using a `changed` callback in server side `observe`

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#12130]
Found this issue when digging around to understand #12128.

When I call `this.changed` within the publish function the document does not appear to be sent to the client until a corresponding `this.changed` is sent that has a value set.

## Environment
`METEOR@2.7.3`
OS: Ubuntu 20.04.4 (WSL)

## Expected
Immediately after calling `this.changed` within a publication I expect the client to pick up the change.

## Actual
If the only value is changed from a value to `undefined` the change is not published until the value is changed back to a defined value.

## Repro repository: https://github.com/brucejo75/observe_change_issue
To see the issue:

1. Click `Change Collection Value`.
2. Observe client console output
3. Click `Undefined Value`
4. Click `Change Collection Value`
5. Observe that the document with the `undefined` value only comes down to the client when the value is changed back

**Comment by radekmie** [comment]
It looks like I already covered it in https://github.com/meteor/meteor/issues/12128#issuecomment-1214125079.

**Comment by brucejo75** [comment]
Thanks @radekmie,

from: https://github.com/meteor/meteor/issues/12128#issuecomment-1214125079
>Lastly, the problem comes from the fact, that MongoDB removes a field when its value is `undefined`, making it **not** present in your `changed` callback, meaning that the client won't see any change - in the end, there's no new value for the field (it's simply not there). The only option I see now would be to somehow handle replace operations with field removals, although it's probably going to be backward-incompatible, I think.
>
>**EDIT**: As `undefined` is technically not an allowed MongoDB value, then I don't think it's an important case. However, removing them when they're removed, is.

I updated my repro with the `stop` fix & I disabled optimistic updates on the client.  This then gave me a repro of the 1 issue you identified: **removing a field is not handled by the Meteor pub/sub**.

I agree with you that field removal should be handled by pub/sub.

I did a search through the issues, thinking this would have surely been identified.  But I could not find one.

Should I open a separate issue with this problem?  Or just rename this issue?

Thanks!

**Comment by radekmie** [comment]
@brucejo75 Thanks for updating the reproduction. In any case, the most important part is that returning a cursor correctly handles removals - the only problem is the `changed` method.

I think that renaming this issue is fine. And I'll try to look into it later this week.

**Comment by Torgen** [comment]
When you return a cursor or list of cursors from a publish function, Meteor uses `observeChanges()` to observe them. The fields parameter passed to the `changed` callback matches what you have to pass to the subscription's `changed` method to get it to delete fields. The `changed` callback for an `observe()` call receives the whole new document and the whole old document, which is not what `subscription.changed` is expecting.

**Comment by santiagopuentep** [comment]
Could this be related to this issue from 5 months ago? https://github.com/meteor/meteor/issues/11977

I think these issues are big ones. In our case we've been stuck with Meteor 2.5.3 because we can't update without the app breaking silently.

**Comment by radekmie** [comment]
@santiagopuentep I don't think so - the issue you've mentioned looks like something that could be already solved with my PRs regarding the oplog converter. This one here is different.

**Comment by radekmie** [comment]
I dug more into it, and the thing is, that it's just how `observe` is meant to work. It presents you with both the previous and the next version of a document. At the same time, `subscription.changed` expects the changes, not the final state of a document. That means, you have to use `observeChanges`, just like the [`_publishCursor`](https://github.com/meteor/meteor/blob/d3c354c7f4f4dfae7a9c4bc134f32896567161d1/packages/mongo/collection.js#L411-L438) does.

Here's a slightly modified code of yours, that works:
```ts
Meteor.publish('change', function publishChanges() {
  const self = this;

  const handle = ChangeCollection.find({}).observeChanges({
    added(id, fields) {
      console.log('added doc: ', id, fields);
      self.added('change', id, fields);
      self.ready();
    },
    changed(id, fields) {
      console.log('changed doc: ', id, fields);
      self.changed('change', id, fields);
      self.ready();
    },
    removed(id) {
      console.log('removed doc: ', id);
      self.remove('change', id);
      self.ready();
    }
  });
  self.onStop(() => handle.stop());
  self.ready();
  return;
});
```

**Comment by brucejo75** [comment]
D'oh!  I should have thought to try that.  Thanks for digging in for me.
