### ISSUE TITLE
Errors attempting to run fresh svelte project + Android platform

### ISSUE THREAD

**Issue by NigelCunningham** [meteor/meteor#12173]
On Arch Linux, I am attempting to run a freshly made Svelte project in the Android emulator. With both 2.7.4 and the 2.8.0 merge request I'm getting:

`I20220903-14:01:59.691(10) (android:http://localhost:12560/__cordova/packages/modules.js:2011) Uncaught SyntaxError: Use of const in strict mode.
I20220903-14:01:59.692(10) (android:http://localhost:12560/__cordova/packages/modules-runtime-hot.js:665) Uncaught SyntaxError: Unexpected identifier
I20220903-14:01:59.692(10)? W/MeteorWebApp( 3335): Asset /cordova_plugins.js not found in bundle 12857da17d4e2e1a82d6699a6e24667e6cbc53f6:file:///android_asset/www/application, no parent bundle
I20220903-14:01:59.693(10) (android:http://localhost:12560/__cordova/packages/es5-shim.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.693(10) (android:http://localhost:12560/__cordova/packages/promise.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.693(10) (android:http://localhost:12560/__cordova/packages/ecmascript-runtime-client.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.693(10) (android:http://localhost:12560/__cordova/packages/hot-module-replacement.js:47) Uncaught SyntaxError: Unexpected identifier
I20220903-14:01:59.694(10) (android:http://localhost:12560/__cordova/packages/react-fast-refresh.js:31) Uncaught SyntaxError: Unexpected identifier
I20220903-14:01:59.694(10) (android:http://localhost:12560/__cordova/packages/fetch.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.694(10) (android:http://localhost:12560/__cordova/packages/dynamic-import.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.694(10) (android:http://localhost:12560/__cordova/packages/base64.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.695(10) (android:http://localhost:12560/__cordova/packages/ejson.js:17) Uncaught TypeError: Cannot read property 'Base64' of undefined
I20220903-14:01:59.695(10) (android:http://localhost:12560/__cordova/packages/diff-sequence.js:17) Uncaught TypeError: Cannot read property 'EJSON' of undefined
I20220903-14:01:59.695(10) (android:http://localhost:12560/__cordova/packages/geojson-utils.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.695(10) (android:http://localhost:12560/__cordova/packages/id-map.js:17) Uncaught TypeError: Cannot read property 'EJSON' of undefined
I20220903-14:01:59.696(10) (android:http://localhost:12560/__cordova/packages/random.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.696(10) (android:http://localhost:12560/__cordova/packages/mongo-id.js:17) Uncaught TypeError: Cannot read property 'EJSON' of undefined
I20220903-14:01:59.696(10) (android:http://localhost:12560/__cordova/packages/ordered-dict.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.696(10) (android:http://localhost:12560/__cordova/packages/tracker.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.696(10) (android:http://localhost:12560/__cordova/packages/minimongo.js:17) Uncaught TypeError: Cannot read property 'DiffSequence' of undefined
I20220903-14:01:59.697(10) (android:http://localhost:12560/__cordova/packages/check.js:17) Uncaught TypeError: Cannot read property 'EJSON' of undefined
I20220903-14:01:59.697(10) (android:http://localhost:12560/__cordova/packages/retry.js:17) Uncaught TypeError: Cannot read property 'Random' of undefined
I20220903-14:01:59.697(10) (android:http://localhost:12560/__cordova/packages/callback-hook.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.697(10) (android:http://localhost:12560/__cordova/packages/ddp-common.js:17) Uncaught TypeError: Cannot read property 'check' of undefined
I20220903-14:01:59.698(10) (android:http://localhost:12560/__cordova/packages/reload.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.698(10) (android:http://localhost:12560/__cordova/packages/socket-stream-client.js:17) Uncaught TypeError: Cannot read property 'Retry' of undefined
I20220903-14:01:59.698(10) (android:http://localhost:12560/__cordova/packages/ddp-client.js:17) Uncaught TypeError: Cannot read property 'check' of undefined
I20220903-14:01:59.698(10) (android:http://localhost:12560/__cordova/packages/ddp.js:14) Uncaught TypeError: Cannot read property 'DDP' of undefined
I20220903-14:01:59.698(10) (android:http://localhost:12560/__cordova/packages/allow-deny.js:17) Uncaught TypeError: Cannot read property 'LocalCollection' of undefined
I20220903-14:01:59.699(10) (android:http://localhost:12560/__cordova/packages/logging.js:17) Uncaught TypeError: Cannot read property 'EJSON' of undefined
I20220903-14:01:59.699(10) (android:http://localhost:12560/__cordova/packages/mongo.js:17) Uncaught TypeError: Cannot read property 'AllowDeny' of undefined
I20220903-14:01:59.699(10) (android:http://localhost:12560/__cordova/packages/reactive-var.js:17) Uncaught TypeError: Cannot read property 'Tracker' of undefined
I20220903-14:01:59.699(10) (android:http://localhost:12560/__cordova/packages/zodern_melte-compiler.js:67) Uncaught SyntaxError: Unexpected token =>
I20220903-14:01:59.700(10) (android:http://localhost:12560/__cordova/packages/zodern_melte.js:17) Uncaught TypeError: Cannot read property 'Tracker' of undefined
I20220903-14:01:59.700(10) (android:http://localhost:12560/__cordova/packages/tmeasday_check-npm-versions.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.700(10) (android:http://localhost:12560/__cordova/packages/rdb_svelte-meteor-data.js:17) Uncaught TypeError: Cannot read property 'Tracker' of undefined
I20220903-14:01:59.700(10) (android:http://localhost:12560/__cordova/packages/webapp.js:17) Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I20220903-14:01:59.700(10) (android:http://localhost:12560/__cordova/packages/autoupdate.js:17) Uncaught TypeError: Cannot read property 'Tracker' of undefined
I20220903-14:01:59.701(10) (android:http://localhost:12560/__cordova/app/global-imports.js:3) Uncaught TypeError: Cannot read property 'Mongo' of undefined
I20220903-14:01:59.701(10) (android:http://localhost:12560/__cordova/app/app.js:1) Uncaught ReferenceError: meteorInstall is not defined`

Steps to reproduce:

`meteor create --svelte test3
cd test3
meteor add-platform android
meteor run android
`

I'm happy to try patches. My JDK is 11 and I have Android SDKs from 26 to 33 installed. The full log from go to whoa is attached.
[meteor-bug-report-full.log.txt](https://github.com/meteor/meteor/files/9481788/meteor-bug-report-full.log.txt)

**Comment by Grubba27** [comment]
Hey! I hope it is all good out there :)  I feel this is related to this [issue](https://github.com/meteor/meteor/issues/12108).
I will also try this out to see if this works on this one.

**Comment by NigelCunningham** [comment]
It didn't for me sorry. I also tried the symlink, without success. I think the number of messages has however reduced, so maybe it's part of the solution.

**Comment by Grubba27** [comment]
Good! can you send the messages you got ? are they the same ones you sent above?  there is [this issue](https://github.com/meteor/meteor/issues/12154) too, but I'm not familiar with how android works with Cordova

**Comment by zodern** [comment]
This error is interesting: `Uncaught SyntaxError: Use of const in strict mode. I20220903-14:01:59.692(10)` since even IE supports const. What OS are you running the cordova app on? Do you know what web browser it is using?

**Comment by NigelCunningham** [comment]
@Grubba27, I'll check as soon as I get a chance (busy weekend).
@zodern, I'm running it on a Pixel 5 running Android 13. The app is started from Arch Linux. I'm pretty sure the browser is Chrome but will double check when I get the opportunity. That might be a while as I'm busy all this weekend - just taking a few minutes out now to check whether anything had changed on this issue and reply.

**Comment by NigelCunningham** [comment]
Let's close this - I've stopped running a git checkout and things have started to work.

**Comment by StorytellerCZ** [comment]
Closing per OP request.
