### ISSUE TITLE
Accounts.registerLoginHandler is still undocumented

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#12189]
The [docs for accounts](https://docs.meteor.com/api/accounts.html) still miss this method.

There are a few discussions in the community that state this as crucial to be documented:

- https://forums.meteor.com/t/meteor-login-using-webauthn-api/58296/4
- https://forums.meteor.com/t/add-official-documentation-for-accounts-registerloginhandler/37136

**Comment by Grubba27** [comment]
Hey @jankapunkt, Thanks a lot for reporting!!

**Comment by yunsuklee** [comment]
Hi! I'd love to contribute solving this issue :)

**Comment by StorytellerCZ** [comment]
@yunsuklee no need to ask for permission. Go ahead and submit a PR.

**Comment by shivam1646** [comment]
Hi @StorytellerCZ I have added the docs as part of PR #12218. Could you please take a look when you have some time.

**Comment by StorytellerCZ** [comment]
Closing this as #12218 has been merged and will be released as part of Meteor 2.8.1.
