### ISSUE TITLE
Meteor 1.8.2

### ISSUE THREAD

**Issue by yasaricli** [meteor/meteor#12213]
hi;

We are using our Meteor applications with version **1.8.2.**

but when we want to install version **1.8.2** with `https://install.meteor.com/?release=1.8.2`, it cannot find the file `https://static-meteor.netdna-ssl.com/packages-bootstrap/1.8.2/meteor-bootstrap-os.osx.arm64.tar.gz`.

Is there another **TARBALL_URL** where we can install old meteor versions?

<img width="742" alt="Screen Shot 2022-10-06 at 20 00 45" src="https://user-images.githubusercontent.com/1306620/194374375-1d55b75f-e9ce-4b60-a36b-c9debfc16d84.png">

Thanks.

**Comment by Grubba27** [comment]
Hey @yasaricli, for installing versions older than [2.5.1](https://github.com/meteor/meteor/blob/597402d64ca551e9699fa11afbd06a8a6c3b7f4f/npm-packages/meteor-installer/install.js#L59-L63) is only using osx 86_64
the URL for making the curl request is 
https://static-meteor.netdna-ssl.com/packages-bootstrap/1.8.2/meteor-bootstrap-os.osx.x86_64.tar.gz

I think it would be something like this:
```bash
curl https://static-meteor.netdna-ssl.com/packages-bootstrap/1.8.2/meteor-bootstrap-os.osx.x86_64.tar.gz | sh
```

**Comment by yasaricli** [comment]
Thanks @Grubba27 

I downloaded meteor-bootstrap-os.osx.x86_64.tar.gz and it worked for me.

<img width="394" alt="Screen Shot 2022-10-06 at 21 46 02" src="https://user-images.githubusercontent.com/1306620/194393846-7ec24a5f-b778-4a21-85cd-aec4687eff01.png">
