### ISSUE TITLE
_findUserByQuery should never do the case insensitve lookup without a limit of 2

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#12211]
In _findUserByQuery there is this code

```
      user = Meteor.users.findOne(selector, options);
      // If user is not found, try a case insensitive lookup
      if (!user) {
        selector = this._selectorForFastCaseInsensitiveLookup(fieldName, fieldValue);
        const candidateUsers = Meteor.users.find(selector, options).fetch();
        // No match if multiple candidates are found
        if (candidateUsers.length === 1) {
          user = candidateUsers[0];
        }
      }
```

_selectorForFastCaseInsensitiveLookup in rare cases can be very inefficient (if you have a lot of users with the same beginning)

So when we call this function from the password handler we don't have limit set to 2, which means this can be loading in way too many items

This is in the password handler:

```

  const user = Accounts._findUserByQuery(options.user, {fields: {
    services: 1,
    ...Accounts._checkPasswordUserFields,
  }});
```

Which is the case causing my issues.

Not sure if we should fix _findUserByQuery to always set the limit, or make sure it is always called correctly.

**Comment by StorytellerCZ** [comment]
Will be released in 2.8.1.
