### ISSUE TITLE
Add --open flag to open user browser when start serving

### ISSUE THREAD

**Issue by Grubba27** [meteor/meteor#12233]
When you want to run the project and wants to open the browser when it finishes building
it would look like this:

```bash
meteor run --open
```
_or_

```bash
meteor --open
```

it would start running the server then open your default browser

## How to implement?

 - [ ]  you are going to start here [file](thub.com/meteor/meteor/blob/ae7ccaf8051030f180d4adfcb157676703563a09/tools/cli/commands.js#L301-L302) adding the new option;
 - [ ] Maybe make changes [here](https://github.com/meteor/meteor/blob/8813bdd3df0e7fff61c5eca9683924e6d692f4f7/tools/runners/run-all.js#L19) as well
 - [ ] Install the [open](https://www.npmjs.com/package/open) npm package
 - [ ] use the ``ROOT_URL``variable to open in the browser

---
discussion for more context

Discussed in https://github.com/meteor/meteor/discussions/12226

**Comment by ankitzm** [comment]
Would love to take up this issue, can you assign me the same !!

**Comment by Jaya-sys** [comment]
Hi can you assign this issue to me?

**Comment by Grubba27** [comment]
hey @ankitzm how it is going? it is looking good?

**Comment by nameception** [comment]
Hello, i tried working on this issue but when importing the open package via `import { open } from 'open'` gives me this error: 

> Error [ERR_REQUIRE_ESM] [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\user\Desktop\meteor\node_modules\open\index.js
require() of ES modules is not supported.
require() of C:\Users\user\Desktop\meteor\node_modules\open\index.js from C:\Users\user\Desktop\meteor\tools\cli\commands.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\user\Desktop\meteor\node_modules\open\package.json.

I also attempted the solution suggested here: https://github.com/sindresorhus/file-type/issues/525#issuecomment-1013041630  but it doesn't seem to work, no errors but the browser window did not open as expected.
Here is how I tried to do it 
```javascript// Opens a browser window when it finishes building
main.registerCommand({
  name: '--open',
  requiresRelease: false,
  pretty: false,
  catalogRefresh: new catalog.Refresh.Never()
}, function (options) {
  (async () => {
    const { open } = await import('open')
    await open('https://www.google.com')
  });
});
```

**Comment by StorytellerCZ** [comment]
Maybe try the require syntax. Depending on where it is you will have to fall back to basic Node syntax without anything else.

**Comment by nameception** [comment]
Using open@8.4.2 worked with the require syntax, the following code now executes without any errors:
```js// Opens a browser window when it finishes building
main.registerCommand({
  name: '--open',
  requiresRelease: false,
  pretty: false,
  catalogRefresh: new catalog.Refresh.Never()
}, function (options) {
  open('https://google.com')
  Console.rawInfo('test')
});
```

However, despite no errors in the terminal output, it doesn't open any windows, I tested the package on other project and it worked. I'm not sure why it behaves this way, and I might not have the expertise to dig deeper into the issue.

terminal output:
``` 
PS C:\Users\andre\Desktop\meteor> ./meteor --open      
test
```
I hope this helps

**Comment by Grubba27** [comment]
I would ask for a draft pr to see what you are doing!

To add a dependency to the project, you need to add to this file https://github.com/meteor/meteor/blob/d852e9c018980de7711fa6ec8ee6050a6efe4f6e/scripts/dev-bundle-tool-package.js#L7-L13

Then run `./scripts/generate-dev-bundle.sh`. If you are in Windows without WSL, you can use `./scripts/generate-dev-bundle.ps1`.

This will add the library code to the tool, making it possible to be imported.

For adding a command for when you start serving, you should add the code that you commented on here:
https://github.com/meteor/meteor/blob/d852e9c018980de7711fa6ec8ee6050a6efe4f6e/tools/cli/commands.js#L312-L317

```js
    port: { type: String, short: "p", default: DEFAULT_PORT },
    open: { type: Boolean, short: "o", default: false }, // <- your code here for the open flag
    'mobile-server': { type: String },
    'cordova-server-port': { type: String },
```

Your call to the open library will probably be around here:
https://github.com/meteor/meteor/blob/d852e9c018980de7711fa6ec8ee6050a6efe4f6e/tools/cli/commands.js#L442-L446

**Comment by amnahid** [comment]
is this problem solved?
