### ISSUE TITLE
Indicate Meteor server port on app restart

### ISSUE THREAD

**Issue by Grubba27** [meteor/meteor#12230]
This would be a change from what we have

From:
```
=> Meteor server restarted
```

To:
```
=> Meteor server restarted on port http://localhost:3400

```

Or the same, but in case the user passes the ``ROOT_URL``

To:
```
=> Meteor server restarted on port http://127.0.0.1:3400
```
another thing is wrap the URL with the [Command.url](https://github.com/meteor/meteor/blob/0eaf07c90804811936acf3c98e9d981c0a736a3b/tools/cli/commands.js#L910) method

## How to implement?

 - [ ]  you are going to start here on this [file](https://github.com/meteor/meteor/blob/b6e127cfc9fd33a5fb16db540531e1fa1e8d7f48/tools/runners/run-log.js#L162);
 - [ ] get the ``ROOT_URL`` to show up along the console message as well
 - [ ] Adjusts tests that may break

---- 
_discussion for more context_
### Discussed in https://github.com/meteor/meteor/discussions/12226

<div type='discussions-op-text'>

<sup>Originally posted by **msavin** October 15, 2022</sup>
A lot of times, I have like 5 Meteor applications running. It's just easier to keep them all running than to constantly start and terminate servers. However, often times, I'll forget the port on which the apps are running.

I'm curious if anyone else runs into this situation. I thought a simple solution can be to indicate the server port on app restart

From:
```
=> Meteor server restarted
```

To:
```
=> Meteor server restarted on port 3400
```</div>

**Comment by ltsaiete** [comment]
Hello @Grubba27 
I'm not familiar with meteor, but I'm very familiar with JS/TS and I want to contribute for Hacktoberfest. I find this issue interesting and friendly. I'd like to try.

**Comment by StorytellerCZ** [comment]
@ltsaiete go ahead, try out Meteor following the [development guide](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md) and se if you can make this happen.

**Comment by ltsaiete** [comment]
Hello @ankitzm , I'm still working on it.

**Comment by shashwata27** [comment]
is this resolved?

**Comment by afrokick** [comment]
Released in 2.8.1. The issue should be closed. @Grubba27 @denihs

**Comment by Grubba27** [comment]
Done in 2.8.1

**Comment by afrokick** [comment]
@Grubba27 could you please change milestone?)
