### ISSUE TITLE
Cursor.observe 'changedAt' callback is not fired if document's nested property is updated

### ISSUE THREAD

**Issue by wolasss** [meteor/meteor#12277]
# Reproduction repository

https://github.com/wolasss/meteor-cursor-observe-changed-bug/tree/changed-at (branch `changed-at`)

Steps: 

1. run `meteor`
2. Go to the app, click on link 
3. Inspect console.log

# Description

**Please note that is is probably related to https://github.com/meteor/meteor/issues/12098 fixed by @radekmie in 2.8.0. I used the same repo for reproduction (but I created a separate branch - `changed-at`)**

[Cursor.observe](https://docs.meteor.com/api/collections.html#Mongo-Cursor-observe) 'changedAt' is not called if nested property is updated. 

Consider https://github.com/wolasss/meteor-cursor-observe-changed-bug/tree/changed-at repository which is a meteor react application created to reproduce this bug (`meteor create --react`).

The initial state of the application is that there are a few links in the collection, but I modified each link with the additional property `params: { a: 1, b: 2, c: 3 }`. If you start the application, and click on a link it will trigger an update to the link document, updating its `params` property (using $set) to ```{
                  a: 5,
                  d: 5,
                  e: new Mongo.ObjectID('5f953cde8ceca90030bdb86f')
              }```

Now if you observe the cursor `LinksCollection.find()` and provide changed callback as such:

```
cursor.observe({
          changedAt: (newDocument, oldDocument) => {
              console.log('changed at', newDocument, oldDocument);
          }
});
```

you will notice that this callback is never fired. However if you update the object as such: 

```
LinksCollection.update({
          _id
      }, {
          $set: {
              test: 1
          }
      }, (err, res) => {
         console.log(err, res);
      });
``` 

it seems to be working just fine. 

# The expected behaviour:

1) The changedAt callback should be called when document nested property is updated. 

# The version of Meteor showing the problem

tested on 2.8.0

# The last version of Meteor where the problem did _not_ occur

2.5.5

Change release to 2.5.5 and reproduce steps

# The operating system you're running Meteor on

MacOS 10.14.3

# Notes

This bug is quite a significant because `useFind` from `meteor-react-data` is dependent on that callback: https://github.com/meteor/react-packages/blob/8f39177821260427f8a0eb58fb8ddbd484236e6d/packages/react-meteor-data/useFind.ts#L107

**Comment by radekmie** [comment]
Thanks for the reproduction @wolasss! I'll look into it.

**Comment by radekmie** [comment]
@wolasss I checked your reproduction and it's either working correctly or I don't understand the problem. I run the app, and click on each link - all updates are logged in the console. Now I click on every one of them again, and nothing is logged, which is correct, because nothing changed (`update` didn't change anything, so there's no change logged). When I change the `$set` to modify another field (here: `test`), it also logs once, when the field is added, and then is ignored.

Can you confirm if that's the case?

**Comment by radekmie** [comment]
No problem. When it comes to using `observe` in `useTracker`, remember that they're not really compatible - `observe` is not a reactive function and it may be tricky to use it correctly. Even `useFind` uses `useEffect` to handle it properly.
