### ISSUE TITLE
[FIBERS] Deal with the very first Fiber call inside the boot.js file.

### ISSUE THREAD

**Issue by denihs** [meteor/meteor#12293]
A PR will be linked to this in the future. Refers to the [Fibers Plan](https://github.com/meteor/meteor/discussions/11505#discussioncomment-3327311).

**Comment by StorytellerCZ** [comment]
@denihs isn't this done already?

**Comment by denihs** [comment]
yes yes! This was just to keep track on [here](https://github.com/orgs/meteor/projects/10)
