### ISSUE TITLE
Document more properties on Meteor object

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12318]
https://docs.meteor.com/api/core.htm is missing:
- Meteor.isModern
- Meteor.gitCommitHash
- Meteor.isTest
- Meteor.isAppTest
- Meteor.isPackageTest

**Comment by radekmie** [comment]
These should also be reflected in types as well (CC @piotrpospiech).

**Comment by bakhtiarcr7** [comment]
where can I find there description?

**Comment by harryadel** [comment]
@bakhtiarcr7 Seems like most of them are defined [here](https://github.com/meteor/meteor/blob/ffcfa5062cf1bf8a64ea64fef681ffcd99fe7939/packages/meteor/client_environment.js#L61) but this is no ordinary copy/paste job, please lookup all over the codecase to better grasp what each individual config is meant to do. For instance, this [part](https://github.com/meteor/meteor/blob/5c4bdc18d9b7d468c450459bdc6e0c4f7a18d5c9/packages/modern-browsers/modern.js#L70) of the codebase contains more info about isModern. 

Also, don't forget to edit the [types file](https://github.com/meteor/meteor/blob/f60bfc7f75a24263539ef67fe856afab6eaf983e/packages/meteor/meteor.d.ts) like @radekmie suggested. Good luck!
