### ISSUE TITLE
Slow Cursor.count() for empty selectors

### ISSUE THREAD

**Issue by rubenhelsloot** [meteor/meteor#12335]
Hi all,

In #12219, you've replaced the deprecated `.count` function with `.countDocuments` for all types of counts, reasoning that it wasn't slower than `.count`. However, I think it is slower, at least for empty selectors returning the count of the entire collection.

I have a collection ("orders") of ~300k pretty large documents and I need a count over it to know how many pages to show in the paginated table of my app. To get that, I do something like `Orders.find({}).count()`, but this causes MongoDB to complain about a high scanned / returned ratio.

When I look in the MongoDB profiler, I get the following schema:

```
{
  "type": "command",
  "command": {
    "aggregate": "orders",
    "pipeline": [
      {
        "$match": {}
      },
      {
        "$group": {
          "_id": 1,
          "n": {
            "$sum": 1
          }
        }
      }
    ],
    "cursor": {},
    ...
  },
  "docsExamined": 272044,
  "durationMillis": 2601,
  ...
}
```

As you can see, the `count` has been replaced by an aggregation pipeline with `$groupby + $sum`, and it takes 2.6s to count all 272k documents in the collection!

I've traced this logic back to `npm-mongo`'s implemenation of [countDocuments](https://github.com/mongodb/node-mongodb-native/blob/main/src/operations/count_documents.ts#L17), so that is all logical, but I think that for empty selectors, `countDocuments()` is overkill.

According to [this SO answer](https://github.com/mongodb/node-mongodb-native/blob/main/src/operations/count_documents.ts#L17), `countDocuments({})` and `estimatedDocumentCount()` are equivalent, but the latter runs in O(1) instead of O(n).

Would it be possible to expose `estimatedDocumentCount()` directly, or to call it inside `.count()` when the selector of the cursor is known to be empty?

**Comment by Grubba27** [comment]
Hello @rubenhelsloot how are you doing? 
What version are you running? We had this discussion [here](https://github.com/meteor/meteor/discussions/12332).
Versions 2.8.2 and 2.9.0-rc.2 have newer versions of npm-mongo and adjustments in the count cursor especially

**Comment by rubenhelsloot** [comment]
Hi @Grubba27, thanks for your quick response!

I'm running 2.8.1, I didn't know 2.8.2 was in the works! Looking at the discussion around 2.8.2, it seems like the memory leak is unrelated to the way in which the documents are fetched. 

However, I think 2.9 (and specifically PR #12295) might expose exactly the methods I was looking for. I'll see if updating to the RC branch resolves the issue

**Comment by Grubba27** [comment]
Awesome! Let me know if you run into any issues regarding the updates.

**Comment by rubenhelsloot** [comment]
I've updated Meteor to `METEOR@2.9.0-rc.2`, but I don't see the `estimatedDocumentCount()` function on the mongo collections. This is the output of `collection.__proto__` in the debugger:

![image](https://user-images.githubusercontent.com/9203462/205253640-d84ae400-a3a0-4f81-88cb-f956beeb6e9d.png)

I did confirm that I am on rc2. Do you have any idea what I might be doing wrong?

**Comment by rubenhelsloot** [comment]
FYI, I've worked around it for now with the following code:

```
// util.js
export const getCount = (collection, query) => {
  if (!query || isEmpty(query)) {
    return Promise.await(collection.rawCollection().estimatedDocumentCount());
  }
  return collection.find(query).count();
};
```

```
// some_method.js
const total = getCount(Orders, query);
```

**Comment by Grubba27** [comment]
Hello @rubenhelsloot ! thx a lot for your report! I've found it, it was a mistake that I've made on the 2.9 rc, we have launched a quick update for 2.8.2 and because of that the mongo version for 2.9 was not available anymore.
2.9.0-rc.9 will do the trick as you can see for the image bellow:

![Screenshot 2022-12-05 at 09 16 02](https://user-images.githubusercontent.com/70247653/205635149-d3109d5f-f53e-4fac-b1f5-64676725185b.png)

I think this will never happen again, but if it do, you can reopen this issue, thx again for your report!
