### ISSUE TITLE
twitter-oauth/twitter_server.js whitelisted fields not included

### ISSUE THREAD

**Issue by arturspr** [meteor/meteor#12358]
Bug (line 29):
const { identity: fields } = Twitter.whitelistedFields;

Suggested fix: 
const fields = Twitter.whitelistedFields.reduce((o, k) => { if ( identity[k]) o[k] = identity[k]; return o}, {});

This causes email (and other profile data) not to be saved into serviceData object.

**Comment by Grubba27** [comment]
Hello @arturspr, would you like to make this change? Or can I open this up to the community? sounds a good feature to have these more data included

**Comment by arturspr** [comment]
Please make the change if you can.

Additionally, (not a bug) but would be desirable to add "name" field to the whiltelistedFields:

Twitter.whitelistedFields = ['profile_image_url', 'profile_image_url_https', 'lang', 'email', "name"]

**Comment by Atharshoyeb** [comment]
I would like to make the changes, please assign it to me

**Comment by Atharshoyeb** [comment]
Grubba27 please suggest the changes in my commit to be able to merge in main branch.

**Comment by Grubba27** [comment]
hey @Atharshoyeb I was not able to test it _yet_ but as soon as I can I will, when I merge it, I will let you know @arturspr as well so that you can test it on you project

**Comment by Atharshoyeb** [comment]
Okay

**Comment by Atharshoyeb** [comment]
hey please recommend the changes as needed .
