### ISSUE TITLE
New simpl-schema 3.4.0 incompatible with Meteor npm 6.14.17

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#12364]
Hi,
it looks that we are no longer able to update to new versions of simpl-schema (npm) as they are no longer compatible with the outdated version of NPM in Meteor.
Thank you

![Screen Shot 2022-12-13 at 1 26 19 PM](https://user-images.githubusercontent.com/26188915/207279999-abd5835f-ad5a-4573-8b40-82a83b532d19.png)

**Comment by StorytellerCZ** [comment]
There are other issues with `simpl-schema` v3.x.
Community is already looking into it: https://github.com/Meteor-Community-Packages/organization/issues/69
Npm version is going to be resolved once Node is upgraded in Meteor v3 and there are other issues tracking it already, so I'm closing this issue.

**Comment by paulincai** [comment]
Ok, got it, my mistake, I wrote that before checking the NPM version pair for our latest NODE 14.
