### ISSUE TITLE
2.9: window.DDP._allSubscriptionsReady()  always returns false 

### ISSUE THREAD

**Issue by niklasdahlheimer** [meteor/meteor#12376]
We use the function `window.DDP._allSubscriptionsReady()` for our Cypress test to check if all subscriptions are ready. After updating to Meteor 2.9 this function always return false.

The [Migration Guide](https://guide.meteor.com/2.9-migration.html) does not mention any changes here.

It's probably related to [this issue](https://github.com/meteor/meteor/issues/12375) but because it is a different package I open a new issue for this.

**Comment by Torgen** [comment]
I tried to bisect this, but running out of a checkout synced to release/METEOR@2.8.2 failed, when running with the released 2.8.2 passed.

**Comment by Torgen** [comment]
Running the bisect on the 2.9 release branch instead of the devel branch says b0856ba1701c14f2a73ff0c34c7cca3c6195e47a ("fix things up") broke this.

**Comment by Torgen** [comment]
Fairly sure the problem is that the `meteor.loginServiceConfiguration` publish doesn't call `this.ready();` if `service-configuration` isn't installed.
