### ISSUE TITLE
Using the --vue-2 flag creates a React project

### ISSUE THREAD

**Issue by mlanning** [meteor/meteor#12395]
OS: macOS Ventura 13.1
Meteor : version 2.9.0

### To Reproduce
Run the command
```
meteor create --vue-2 example
```

### Expected behavior
The app created should contain `*.vue` files in `/imports/ui`.

### Actual behavior
The app creates `*.jsx` react files in `/imports/ui`

### Notes:
- I realize that the [documentation](https://vue-tutorial.meteor.com/simple-todos/01-creating-app.html) shows the flag as `--vue2`, but that is incorrect. The flag should actually be `--vue-2` as used in the example above. I've created a [PR](https://github.com/meteor/vue-tutorial/pull/19) for the documentation. 
- The [documentation](https://vue-tutorial.meteor.com/simple-todos/01-creating-app.html) also uses a flag `--prototype`. I've tried that with this example and it also creates React (`*.jsx`) files.

**Comment by Grubba27** [comment]
Wow! Thanks a lot for opening this issue @mlanning! I think I miss understood the changes when I changed the command in the vue2 tutorial! Thx a lot!

Also, for the create command in 2.9.1, I will have this adjusted ASAP. Thanks a lot for your contribuition
