### ISSUE TITLE
Callback function in Meteor.call not returning error when calling createUserVerifyingEmail

### ISSUE THREAD

**Issue by mlanning** [meteor/meteor#12398]
OS: macOS Ventura 13.1
Meteor: 2.9.0

 [This repo](https://github.com/mlanning/meteor-bug-createUserVerifyingEmail) shows a bug that is coming up using the [createUserVerifyingEmail](https://docs.meteor.com/api/passwords.html#Accounts-createUserVerifyingEmail) in the `accounts-passwords` meteor package.

### Install project
- Clone [this repo](https://github.com/mlanning/meteor-bug-createUserVerifyingEmail)
- Run `meteor npm install`
- Run `npm run start`
- Open `http://localhost:3000` in your browser

### Create a second user
- There should already be one user in the database.
```
username: Neo,
email: neo@example.com
password: password 
```
- Try creating the same user again using those credentials, or try creating two new users with the same credentials.

## Expected behavior
Should show an alert message saying that "Username already exists.", and the error object should also show in the client console.

## Current behavior
Nothing shows on the client side. 

An error message shows in the server console:
```
W20221221-10:19:11.192(-7)? (STDERR) (node:29848) UnhandledPromiseRejectionWarning: Error: Username already exists. [403]
W20221221-10:19:11.192(-7)? (STDERR)     at AccountsServer._handleError (packages/accounts-base/accounts_server.js:1487:19)
W20221221-10:19:11.192(-7)? (STDERR)     at AccountsServer._checkForCaseInsensitiveDuplicates (packages/accounts-base/accounts_server.js:1456:14)
W20221221-10:19:11.192(-7)? (STDERR)     at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1469:10)
W20221221-10:19:11.193(-7)? (STDERR)     at packages/accounts-password/password_server.js:927:19
...
```
---
### Versions 
```
meteor@2.9.0
accounts-base@2.2.6
accounts-password@2.3.2
```
### Notes
This was working for me before upgrading from `METEOR@2.8.1` to `METEOR@2.9.0`. 

On the client side, I have the following Meteor call:
```js
      Meteor.call(
        "createUserAccount",
        {
          username: this.username,
          email: this.email,
          password: this.password,
        },
        error => {
          if (error) {
            console.log(error);
            alert(error.reason);
          } else {
            console.log("User was successfully created!");
          }
        }
      );
```
On the server side, I have this Meteor method. It only seems to be an issue with the `createUserVerifyingEmail` (which is the one I need for my project). However, if you replace that with `createUser`, it works as expected (the error is returned and an alert message pops up).
```js
Meteor.methods({
  createUserAccount(user) {
    /**
     * This seems to be the issue. 
     * Using the other method `createUser` works as expected.
     */
    Accounts.createUserVerifyingEmail({
      username: user.username,
      email: user.email,
      password: user.password,
    });
  },
  sendVerificationLinkEmail(email) {
    const user = Accounts.findUserByEmail(email);
    Accounts.sendVerificationEmail(user._id);
  },
});
``

**Comment by StorytellerCZ** [comment]
I ran into this the other way as well. Short answer, the `Accounts.createUserVerifyingEmail` is now async. So to make a quick fix just make the method function `async` and `await` the function if you need a return value.

**Comment by StorytellerCZ** [comment]
Potentially related to #12300 when something escaped a bit too early?

**Comment by mlanning** [comment]
Thank you so much @StorytellerCZ! This workaround was successful for me. I appreciate the quick response to this issue. For anyone else that may have run into this, here is the implementation of the fix that worked for me.

```js
// server/main.js
Meteor.methods({
  async createUserAccount(user) {
    await Accounts.createUserVerifyingEmail({
      username: user.username,
      email: user.email,
      password: user.password,
    });
  },
  sendVerificationLinkEmail(email) {
    const user = Accounts.findUserByEmail(email);
    Accounts.sendVerificationEmail(user._id);
  },
});
```
