### ISSUE TITLE
vite/vue can't build.

### ISSUE THREAD

**Issue by niceplugin** [meteor/meteor#12403]
- [✓] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [✓] The version of Meteor showing the problem.
  Meteor version: 2.9.0
- [?] The last version of Meteor where the problem did _not_ occur, if applicable.
  I don;t know.
- [✓] The operating system you're running Meteor on.
  M2 mac Ventura 13.1
- [✓] The expected behavior.
  Can build!
- [✓] The actual behavior.
  Not work with error.
- [✓] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)
  No repository required. It's just three lines of code.
```
meteor create --vue test-vue
cd ./test-vue
meteor build ../ --architecture os.linux.x86_64
```

Then you should see something like this in action:

![error](https://global.discourse-cdn.com/meteor/original/3X/b/8/b885f0385b0ece39e5d3408984e963c1d92c4032.png)

**Comment by notsorenzio** [comment]
found the problem,
```js
    {
      path: '/login',
      name: 'login',
      component: () => import('./components/LoginPage.vue'),
    },
```

replace with
```js
import LoginPagefrom './components/LoginPage.vue'

    {
      path: '/login',
      name: 'login',
      component: LoginPage,
    },
```

**Comment by Grubba27** [comment]
By changing your router.js file to be like this:

```js
import { createRouter, createWebHistory } from 'vue-router'
import Home from './Home.vue'
import About from './About.vue'

export const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home,
    },
    {
      path: '/about',
      name: 'about',
      component: About,
    },
  ],
})

```
Should work.

In the next release is planned to be solved in the skeleton as well
