### ISSUE TITLE
Accounts Passwordless login doesn't work with id and token

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#12401]
Hi, one option of Accounts Passwordless login is to login with user id and token.

This option is helpful when you don't have the email of this user.

But there is an inconsistent check:

This validator requires `id` instead of `_id` https://github.com/meteor/meteor/blob/4868a2bb9411b9620e640696ed2d3c400b30b12c/packages/accounts-passwordless/passwordless_server.js#L33

but the rest operator here https://github.com/meteor/meteor/blob/4868a2bb9411b9620e640696ed2d3c400b30b12c/packages/accounts-passwordless/passwordless_server.js#L16-L24 is not going to work to find the user as the `id` in Meteor collections is `_id`.

This code should check if `id` is in the selector and change to `_id`.

I never understood why Meteor had this `id` in Accounts packages but it does so I think it's easier to just fix the way to provide the selector to the query. 

> I got this problem during a [YouTube Live](https://www.youtube.com/watch?v=9Xer73xPk2s) in Portuguese so you can see how I detected the problem probably around 1hr and 15mins

**Comment by codesmith25103** [comment]
Hey, I am new to open source and want to contribute to this project. Can you please assign me this issue?

**Comment by filipenevola** [comment]
> Hey, I am new to open source and want to contribute to this project. Can you please assign me this issue?

We don't use assignments very often here but feel free to send a PR solving this issue.
