### ISSUE TITLE
Accounts onCreateUser hook doesn't support async

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#12400]
How to re-produce error: Just create a hook:
```
Accounts.onCreateUser(async (options, user) => {
  return user;
})
```
Try to create an user, Meteor.users record will have only one field: `_id`

I believe the problem can be found here: https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_server.js#L1176
We try to get the result from hook function which returns a promise:
```
fullUser = this._onCreateUserHook(options, user);
```

**Comment by StorytellerCZ** [comment]
Could this be related to #12398 ?

**Comment by minhna** [comment]
> Could this be related to #12398 ?

I don't think so.

**Comment by minhna** [comment]
Created pull request

**Comment by henriquealbert** [comment]
I can confirm I tried this week, and it does not support it. Are there any open PRs to fix this?
cc @denihs

**Comment by nachocodoner** [comment]
Closing this. I verified that after https://github.com/meteor/meteor/pull/12526 merge is fixed.

Verification reproduction steps:

- Created new app using 3.0 and accounts packages
- Added on server code the hook and altering the user value using the onCreateUser adding a new custom field
- Run the user creation on the client using createUser
- MongoDB shows properly the user with the custom field added

![image](https://github.com/meteor/meteor/assets/2581993/22eb29f4-08a4-41f7-a30c-e3a18855feb8)
![image](https://github.com/meteor/meteor/assets/2581993/051c2b29-c92e-4c18-909c-c40c09819792)

**Comment by nachocodoner** [comment]
Reopen it to verify it works as expected on 2.x.
