### ISSUE TITLE
Accounts.createUser -> Meteor.logginIn issue

### ISSUE THREAD

**Issue by copleykj** [meteor/meteor#1243]
Accounts.createUser when called from the client currently sets Meteor.loggingIn to true even if createUser fails and throws an error. This causes applications that use the Meteor.logging in to display a loading page to re-render their template potentially causing loss of form values and validation errors displayed.

My personal thinking is that Meteor.loggingIn should not enter a true state unless account creation is successful.

**Comment by dburles** [comment]
What's the solution?
