### ISSUE TITLE
info link from vue create skeleton points to solidjs

### ISSUE THREAD

**Issue by mattsouth** [meteor/meteor#12439]
https://github.com/meteor/meteor/blob/9cc480a1ab3bfc85ebc86a86a85bfa92a19103b9/tools/static-assets/skel-vue/server/main.js#L13

I think this url needs to be https://vuejs.org/

**Comment by mattsouth** [comment]
or maybe https://vuejs.org/guide/quick-start.html

**Comment by Grubba27** [comment]
Good catch! Do you want to fill in a PR for this one @mattsouth?
