### ISSUE TITLE
The meteor package `appcache` is deprecated

### ISSUE THREAD

**Issue by shiqimei** [meteor/meteor#12445]
Since the package `appcache`'s [implementation](https://github.com/meteor/meteor/blob/devel/packages/appcache/appcache-client.js) relies on  [applicationCache](https://developer.mozilla.org/en-US/docs/Web/API/Window/applicationCache), and `applicationCache` is deprecated and is not existing on latest Chrome. The `appcache` will be not working anymore.

We should remove the package from the main repo and mark `appcahce` from the official website as deprecated. Suggest people using `ServiceWorker` way to implement their own caching strategies.

**Comment by Grubba27** [comment]
Hey! @shiqimei, would you like to take this one?

**Comment by StorytellerCZ** [comment]
I did the first step in this process.

**Comment by Grubba27** [comment]
This was implemented in 2.11!
