### ISSUE TITLE
Accounts.resetPassword function has a faulty check for whether token and passwords are strings

### ISSUE THREAD

**Issue by Pakleni** [meteor/meteor#12454]
This issue is located in `packages/accounts-password/password_client.js` in Meteor 2.10.

The line at fault (and there are others like it) reads `if (!token instanceof String)`

the ! operand has a precedence of 14, while the instance of operator has a precedence of 9. which would equate the above to `false instanceof String`, which will never be true.

In addition to that, checking `instanceof String` only checks if it is a String object, which is rarely the case in js.

a correct solution would be

`if (!(typeof token === "string" || token instanceof String))`

**Comment by Grubba27** [comment]
This was fixed in 2.11. Please update your apps
