### ISSUE TITLE
The requested module '/@id/__x00__meteor/fetch' does not provide an export named 'Headers'

### ISSUE THREAD

**Issue by PatrickKaim** [meteor/meteor#12460]
- Version with problem: 2.10.0 (probably also 2.9.1 fetch was updated in that version)
- Version without problem: 2.9
- Macos Ventura
- Headers to be available without errors/hanging the application
- App will not run as it should, it errors out on a uncaught SyntaxError
- Reproduction:

1. Run `meteor create fetch-test --vue`
2. Run `cd fetch-test && meteor npm install`
3. Run `meteor add fetch`
4. Edit `imports/api/links.js`
5. Add `import {Headers} from 'meteor/fetch'` on top of the document
6. Add `const header = new Headers()` inside a running function, for example: Meteor.publish
7. Run `meteor`
8. Open `localhost:3000` in your browser with console open, error will show up in the browsers console

You could also clone my repo: https://github.com/PatrickKaim/fetch-test.git

**Comment by fredmaiaarantes** [comment]
Hey @PatrickKaim, thanks for reporting this issue.

I've tried several previous versions of Meteor with Vue3 + Vite and got the same error every time.
I've tested importing and using the `Header` from `meteor/fetch` inside `/server/main.js`, which is a server-only file. And that way, it worked.

Another test I did was to try this on another project using Vue 2 and the latest version of Meteor, and it worked fine.

So it looks to me like it's a limitation of our Vue 3 + Vite integration. Do you have a working repository with some previous version of Meteor + Vue 3 + Vite?

**Comment by PatrickKaim** [comment]
Hi @fredmaiaarantes,

I might look into that (placing the fetch inside server/main).

No I only started with vite with the 'meteor create project --vue' because that came with Vite. In my previous projects I never used Vite.

**Comment by fredmaiaarantes** [comment]
> 

All right. When you test it, please let us know if it solves your issue.

**Comment by PatrickKaim** [comment]
@fredmaiaarantes  I've created a clean test project and added an API call inside /server/main.js and it worked.
Placed the code inside a js file inside /server/external/, did the import {fetch, Header} .. in that file and called the function from within Meteor.startup.... and it worked!!

Now I have to recode this in one of my existing projects with more structure and a lot more PAI calls, but I guess that shouldn't be an issue. I'll let you know in a few days if this worked too. 
Thanks Fred for your time and the solution!
