### ISSUE TITLE
Cropped dropdown on official website

### ISSUE THREAD

**Issue by rinat-lucky** [meteor/meteor#12481]
Link to page: [https://www.meteor.com/developers/tutorials](https://www.meteor.com/developers/tutorials)
PC: Lenovo s240-15api , 15inch , 1920*1080 , Win10

![meteor](https://user-images.githubusercontent.com/64750426/215386623-95891c10-616b-4a40-8b4d-29895d0a4883.jpg)

**Comment by Grubba27** [comment]
I think I have solved it!
I will close this one as it seems to be solved, but if, for some reason, this issue reappears, you can open another issue. Thanks a gain for reporting this one!

<img width="1331" alt="Screenshot 2023-01-30 at 09 58 29" src="https://user-images.githubusercontent.com/70247653/215484129-e4a0593b-55b9-4f33-a740-99bdb8746c41.png">


Showing that is on 1920x1080

<img width="990" alt="Screenshot 2023-01-30 at 10 01 38" src="https://user-images.githubusercontent.com/70247653/215484789-4a187a13-93af-4e8c-9508-5729d001b873.png">

**Comment by rinat-lucky** [comment]
yes, that's ok now
