### ISSUE TITLE
vue-2 skeleton creates a broken project

### ISSUE THREAD

**Issue by mattsouth** [meteor/meteor#12499]
linux ubuntu 20
meteor 2.10

### To Reproduce

Run the command

```
meteor create --vue-2 example
```

### expected behaviour

The example project that's created should work as designed (i.e. a single page that shows a counter and the list of urls that can be added to) without errors in the console.

### actual behaviour

The project builds but the list of urls is not shown because the subscription fails, creating an error in the console.

### Notes

* this behaviour has been seen vue 2.7 was released (Jul 22)
* the fix is to pin the vue package dependency to 2.6 (see https://github.com/meteor-vue/vue-meteor-tracker/issues/75)

**Comment by Grubba27** [comment]
Hey @mattsouth, nice to see you here! 
We plan on solving this on version 2.11 which is currently in beta, but I'm working on making a release candidate ASAP. Thanks a lot for reporting this one

**Comment by mattsouth** [comment]
Thanks @Grubba27 - the new vue-2 skeleton in 2.11 looks good and suggests a fix for my underlying issue.
