### ISSUE TITLE
Android 6 failed to run

### ISSUE THREAD

**Issue by boomfly** [meteor/meteor#12514]
Release: METEOR@2.10.0

Try to run app on Android 6 but it seems target web.cordova transpiles to ES modules and Android 6 WebView does not support it:

![Снимок экрана 2023-02-16 в 13 48 59](https://user-images.githubusercontent.com/3257268/219301672-147c133e-a84d-4b10-9b66-98027ecb2373.png)

`.babelrc`

```json
{
  "presets": [
    ["meteor"],
    [
      "@babel/preset-env",
      {
        "targets": {
          "android": "6"
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-spread"
  ]
}
```

Does anyone know how to run app on older android versions.

**Comment by matheusccastroo** [comment]
@boomfly I think cordova uses the legacy bundle by default, the issue from your screenshot seems to be another thing. Seems that your packages weren't loaded. How did you build the app? Try cleaning the meteor cache (removing `.meteor/local/cordova-build`), cleaning the phone app cache and then run again, seems that something went wrong with your build

**Comment by boomfly** [comment]
@matheusccastroo web.cordova is es bundle
but this issue was only on one android 6 phone (LeEco which lost support i think in 2017), i was try on another android 6 and it work fine
close this issue
