### ISSUE TITLE
got Unexpected mongo exit code 62 after updated meteor 2.10.0 to 2.11.0

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#12532]
After update to 2.11.0,  I got this error.
```
=> Started proxy.                             
=> Started HMR server.                        
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Can't start Mongo server.                     
npm verb lifecycle banana@~debug: unsafe-perm in lifecycle true
```

I need to run `meteor reset` then start it again. It works.

// I had to go back to 2.10.0 then dump the database, then import it again after updated to 2.11.0
`mongodump -d meteor --host localhost:9002 -o ./meteor-2.10.0`
then
`mongorestore -d meteor --host localhost:9002  ./meteor-2.10.0/meteor/`

**Comment by Grubba27** [comment]
We have not yet published 100% the 2.11 version(got an issue with Jenkins) could you try with 2.11.0-rc.2 ? They both are the same version

**Comment by fredmaiaarantes** [comment]
This happened because we upgraded the built-in MongoDB from version 5 to 6, right @Grubba27?

Developing locally, a `meteor reset` (which erases your data, so be careful) will be required to recreate your database.

**Comment by Grubba27** [comment]
Yes! you are correct! probably this happend due to version changing. 
the solution above should work

I'm closing this one for now.
Please, if this come to happen again, I would happily re-open this issue

**Comment by alimgafar** [comment]
Should this be mentioned in the release notes?

**Comment by Grubba27** [comment]
It is only mentioned in the [migration guide](https://github.com/meteor/meteor/blob/342d444bb1eeeee7b137f2b2217c432ebff99e5a/guide/source/2.11-migration.md#L50-L51) I'was wondering if adding this to changelog makes sense or perhaps adding this to the 2.11 blogposts make more sense

**Comment by podeig** [comment]
It worked locally. But if I update on the prod server and I have mongo db 5.0.15 version.
I do not reset everything :) How should I upgrade. First upgrade database to v 6? so meteor to 2.11?
Thx!

**Comment by Grubba27** [comment]
As commented in the [migration guide](https://github.com/meteor/meteor/blob/342d444bb1eeeee7b137f2b2217c432ebff99e5a/guide/source/2.11-migration.md#L50-L51):

> Set up your staging database with MongoDB 6.x and restore your production data there, or populate this database in a way that you can reproduce the same cases as if you were in production

Also, since Meteor 2.3(I'm not sure, but it is something like that), you are able to use Mongo V6.x, I would first upgrade the Database(with backups) and then upgrade the Meteor version.

**Comment by podeig** [comment]
Hei @Grubba27 I updated database on prod, the project worked well with meteor 2.10. So then I updated meteor to 2.11 and it worked perfectly fine. Thank you for the advice :)

**Comment by alimgafar** [comment]
> It is only mentioned in the [migration guide](https://github.com/meteor/meteor/blob/342d444bb1eeeee7b137f2b2217c432ebff99e5a/guide/source/2.11-migration.md#L50-L51) I'was wondering if adding this to changelog makes sense or perhaps adding this to the 2.11 blogposts make more sense

I think including it in the appropriate context frames the context where it is addressed.

**Comment by VikR1000** [comment]
I'm updating from 2.10 to 2.12, and getting the "Unexpected mongo exit code 62. Restarting" message.

My app is in production, so I have to figure out the correct way to upgrade without taking down the production app, unless it is really necessary of course. 

I see above from @podeig :

>  I updated database on prod, the project worked well with meteor 2.10. So then I updated meteor to 2.11 and it worked perfectly fine. 

Could I get the exact steps for this listed out? I have a backup with the Meteor 2.10 copy of my app.

**Comment by Grubba27** [comment]
> E.g. "I updated database on prod" -- does that mean going to MongoDB where I'm hosting Mongo and update the version of Mongo there?

Yes, with backups there is nothing to fear, then you update your meteor version.

> I'm updating from 2.10 to 2.12, and getting the "Unexpected mongo exit code 62. Restarting" message

This is local correct? if your are in a local environment, probably is okay to run `meteor reset` be aware that it will erase your local data

**Comment by VikR1000** [comment]
Yes, this is on localhost. It's okay to erase local data here and restore from backup. 

But in production (hosted on Galaxy) -- is it enough for me to go to MongoDB and update the db there -- then update to v2.12 locally and push to my Galaxy production server? -- or will that cause me to get an error 62 on production?
