### ISSUE TITLE
Bulk insertion of documents to minimongo, or Meteor.Collection

### ISSUE THREAD

**Issue by alexhancock** [meteor/meteor#1255]
While working on a project with minimongo abstracted on its own, I noticed that the `minimongo` package, as well as `Meteor.Collection`s do not support bulk insertion when `insert` is passed an array of documents.

This mongodb manual [entry](http://docs.mongodb.org/manual/reference/method/db.collection.insert/#db.collection.insert) details the arguments that should be accepted by `insert`. The salient portion being...

> Changed in version 2.2: The insert() method can accept an array of documents to > perform a bulk insert of the documents into the collection.

I have prepared a small pull request (#1254) which adds support for bulk insertions to `minimongo` collections. I assume the server-side mongo driver already supports it, so this should bring minimongo's `insert` into parity with the actual mongo `insert` and the server-side mongo driver's implementation of this function.

I have not yet written code to have `Meteor.Collection` conform to this change, but wanted to file this issue in case someone who knows the `Meteor.Collection` code in `mongo-livedata` better than I do wants to knock it out quickly.

Again, the PR is #1254 

Cheers

**Comment by glasser** [comment]
Now that we (on devel) support Mongo 2.6 and are on a newer Node Mongo driver, and have @justinsb 's repeatable random work, we can implement bulk insert.  (And we are now tracking feature requests on GitHub.)

**Comment by glasser** [comment]
@ekatek has started this on the `mongo-bulk-inserts` branch; we'll see if it makes it in to 1.0.4 or has to wait until the next release.

**Comment by rclai** [comment]
Is the server-side implementation going to use [bulk writes](http://mongodb.github.io/node-mongodb-native/1.4/driver-articles/anintroductionto1_4_and_2_6.html#ordered-unordered-bulk-operations)? If you guys do, you may as well support multi-updates and multi-removes too.

**Comment by alexhancock** [comment]
@glasser Cool! Thanks for the heads up.

**Comment by glasser** [comment]
@rclai It uses the native driver's array-insert code, which internally uses bulk writes.  If you want to use the bulk writes API directly, you will be able to do that using `c.rawCollection()` which in 1.0.4 will give you direct access to the official Node MongoDB driver.  (This won't be isomorphic of course.)

BTW, this is currently targeted for the release after 1.0.4.

**Comment by aldeed** [comment]
@glasser, I'm being [asked to update collection2 to support bulk inserts](https://github.com/aldeed/meteor-collection2/issues/214). Apparently it works, but the `mongo-bulk-inserts` branch wasn't merged and it's not in the documentation for `insert`. Should people be using this yet?

**Comment by ekatek** [comment]
Hi @aldeed! That branch is not ready yet -- I was working on it for a while, and then got distracted by something else. My goal is to get it to the next code review stage this week (and then merge it soon after).

**Comment by mitar** [comment]
Can you also add bulk upsert? :-)

**Comment by ekatek** [comment]
Maybe? I don't remember what the current state of that branch is, and I would be a little surprised if upsert wasn't included in this. But, it has been a few weeks, and I remember very little about it, so give me a few days to figure this out.

**Comment by mitar** [comment]
Please please. :-) But no hurry. :-)

**Comment by aldeed** [comment]
Thanks @ekatek!

**Comment by chrbradley** [comment]
I'd love to have this soon too. We're stress testing an app with 50K users and seeding the DB is painfully slow.

**Comment by glasser** [comment]
As a workaround in the meantime, you can use `collection.rawCollection().insert` which supports bulk inserts (it's the underlying Node driver's insert function).  It doesn't do certain translations like the handling of EJSON custom types though.

**Comment by robertpitt** [comment]
@peterchoo, FYI.

**Comment by aks0020** [comment]
Meteor 1.4 still don't have function for this. When this will be added?
https://docs.mongodb.com/manual/reference/method/Bulk.insert/

**Comment by WayneUong** [comment]
Meteor 1.4.2 and mongo 3.2 now. Please consider this issue. Thanks!

**Comment by huttarichard** [comment]
Please consider ...

**Comment by voidale** [comment]
+1

**Comment by edemaine** [comment]
Mongo 3.2 seems to have moved to a new naming model: `insertOne`, `insertMany`, `updateOne`, `updateMany` (replacing the `multi` flag).  What about adding a `Collections.insertMany` method as an interface to Mongo's `insertMany`, at least on the server?

**Comment by mitar** [comment]
I think that would be a great new issue. :-)

**Comment by mitar** [comment]
And can this be marked as pull requests encouraged?

**Comment by edemaine** [comment]
@mitar Added #8377.  I don't have time to write a PR now, but got started on the code.  I hope to have some time to do a more complete implementation in the near future.

**Comment by fjms** [comment]
@luixal FYI

**Comment by hwillson** [comment]
Hi all - to help move this along, I've marked this issue as `pull-requests-encouraged`. Work on bulk inserts has already been started by MDG on the [`mongo-bulk-inserts`](https://github.com/meteor/meteor/tree/mongo-bulk-inserts) branch of this repo, but that work was not completed, and those changes were made 2 years ago (but from my quick review of that branch the work was almost completed). If anyone in the community is interested in blowing the dust off things and submitting a new mongo bulk insert PR, it will definitely be reviewed in a timely manner, and be considered for merging. Thanks!

**Comment by janat08** [comment]
https://atmospherejs.com/mikowals/batch-insert
Maybe you could just add this package?

**Comment by hwillson** [comment]
Thanks @janat08 - this issue is `pull-requests-encouraged`, so if anyone wants to submit a PR (based on that code or using another approach) we'll definitely take a look!

**Comment by janat08** [comment]
@mikowals If you'd like.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Bulk%20insertion%20of%20documents%20to%20minimongo%2C%20or%20Meteor.Collection&body=Migrated%20from:%20meteor/meteor%231255) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
