### ISSUE TITLE
error message for "meteor mongo" when your apps is running with $MONGO_URL is misleading

### ISSUE THREAD

**Issue by betacar** [meteor/meteor#1256]
Since I haven't received a answer about this in the [mailing list](https://groups.google.com/forum/#!topic/meteor-talk/0SULns9mxgE) and [StackOverflow](http://stackoverflow.com/questions/17886152/meteor-does-not-connect-to-mongodb), I'm gonna posted here to see if anyone can solve this.

I'm trying to connect Meteor to an existing MongoDB. I can't duplicate the database or change its name, because is used by other app.

I know [I have to set a `MONGO_URL` environment var](http://stackoverflow.com/a/12996674/315748) to connect with it. However, after I set it, Meteor is not connecting to the specified MongoDB database. I tried doing a `.find()` but it does not return any docs. An `.insert()` from the web console shows the info in the page, but it doesn't get inserted in the database. 

After running meteor with `meteor run`, I opened a new console window within project directory to run a meteor mongo console. However, after running `meteor mongo` I received the following:

``` bash
$ meteor mongo
mongo: Meteor isn't running.

This command only works while Meteor is running your application
locally. Start your application first.
```

Here are the codes:

``` bash
$ echo $MONGO_URL
mongodb://localhost:27017/autana_dev
```

./lib/models.js

``` javascript
Posts = new Meteor.Collection('posts');
```

./server/app.js

``` javascript
Meteor.publish('posts', function() {
  return Posts.find();
});
```

./client/app.js

``` javascript
Meteor.subscribe('posts');

Template.main.posts = function() {
  return Posts.find();
};
```

Any idea? Anyone? My Meteor version release is 0.6.4.1, and the MongoDB version is 2.4.1.

**Comment by engrpeters** [comment]
> Good point, the "meteor mongo" command only knows how to connect to two kinds of mongos:
> 
> * with no arguments, to a managed-by-meteor locally-running mongodb (but not to a specified-by-MONGO_URL one)
> * with an argument, to a mongo managed by "meteor deploy"
> 
> Changed the issue title to reflect this. "meteor mongo" really isn't too fancy though, you should just be able to run "mongo $MONGO_URL" if you have your own mongodb.

Hello I did't want to start this again. When using an external mongodb i.e MONGO_URL. How do I connect with meteor mongo
