### ISSUE TITLE
Question: Why does Meteor still use Node.js 14 while Node.js 19 has been released?

### ISSUE THREAD

**Issue by shiqimei** [meteor/meteor#12570]
Is there any technical debt preventing meteor from upgrading to the latest version of Node.js

**Comment by shiqimei** [comment]
Just to be here for a note, [Node.js 20 has been released a few days ago.](https://nodejs.org/en/blog/announcements/v20-release-announce)

**Comment by paulincai** [comment]
@shiqimei did you start losing profits because of the 2 versions in between?

**Comment by shiqimei** [comment]
> @shiqimei did you start losing profits because of the 2 versions in between?

I am sorry if some of my words are offensive. But facts are:

1. If a framework is burdened by its historical baggage and unable to undergo a renaissance, then there will be more and more users like me who will leave it in favor of more updated frameworks such as Next.js.

2. There are still users like me who are constantly keeping an eye on the progress of Meteor 3. If nobody cares about it anymore one day, it means that nobody wants to use it anymore.

3. While continuing to use Meteor 2 may not cause any direct loss of business, the progress of Meteor 3 will instill confidence in the community that we have abandoned the historical baggage of Fiber and embraced a new architecture that supports the latest Node.js versions. This will eliminate any concerns about future compatibility for new users when making technology decisions.
