### ISSUE TITLE
Implicit Collection Creation In Mongo Transaction Throws - Error: Unknown command `{ "o": { "create": ... }}`

### ISSUE THREAD

**Issue by jnecamp** [meteor/meteor#12627]
Meteor Version: 2.12 
Last working Meteor Version:  tested on 2.12 but likely affects all versions
Mongo Version: >=4.4 (Implicit collection creation in transaction supported as of 4.4)
OS: Mac OS 11.7.4 

## Expected Behavior
Can implicitly create a collection inside of a Mongo transaction

## Actual Behavior

An error is thrown here: https://github.com/meteor/meteor/blob/release-2.12/packages/mongo/oplog_tailing.js#L312

when a collection is created implicitly because there is no logic for handling `create` command.

```
Exception in defer callback: Error: Unknown command {"op":"c","ns":"meteor.$cmd","ui":{"sub_type":4,"buffer":{"$binary":"/P1C6u2fR+mkqMQSCFCcpA=="},"position":16},"o":{"create":"one","idIndex":{"v":2,"key":{"_id":1},"name":"_id_"}},"ts":{"$timestamp":"7231213085090906113"}}
I20230509-11:59:57.808(-4)?     at handleDoc (packages/mongo/oplog_tailing.js:312:19)
I20230509-11:59:57.808(-4)?     at packages/mongo/oplog_tailing.js:283:15
I20230509-11:59:57.808(-4)?     at Array.forEach (<anonymous>)
I20230509-11:59:57.809(-4)?     at handleDoc (packages/mongo/oplog_tailing.js:277:28)
I20230509-11:59:57.809(-4)?     at packages/mongo/oplog_tailing.js:346:11
I20230509-11:59:57.809(-4)?     at packages/meteor.js:365:18
I20230509-11:59:57.809(-4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20230509-11:59:57.809(-4)?     at packages/meteor.js:613:25
I20230509-11:59:57.809(-4)?     at runWithEnvironment (packages/meteor.js:1486:24)
```

Oplog entry:
```json
{
  "op": "c",
  "ns": "meteor.$cmd",
  "ui": {
    "sub_type": 4,
    "buffer": {
      "$binary": "/P1C6u2fR+mkqMQSCFCcpA=="
    },
    "position": 16
  },
  "o": {
    "create": "one",
    "idIndex": {
      "v": 2,
      "key": {
        "_id": 1
      },
      "name": "_id_"
    }
  },
  "ts": {
    "$timestamp": "7231213085090906113"
  }
}

```

[Mongo Create Command
](https://www.mongodb.com/docs/manual/reference/command/create/#definition)

## Simple Reproduction

GH repo with minimal Meteor app -> https://github.com/jnecamp/meteor_mongo_unknown_command_create

Call `Meteor.call('testCollectionCreation')`

**Comment by radekmie** [comment]
It should be as simple as ignoring such commands [here](https://github.com/meteor/meteor/blob/67750a1764a57645b1280aa8995841a27abab411/packages/mongo/oplog_tailing.js#L311) - there's nothing we have to do about newly created collections, I think. The only edge case I can think of that should be checked is subscrubing to a collection that does not exist yet, create it implicitly, and see if it's correctly published.

**Comment by rebound-software** [comment]
I'm also seeing a similar issue as follows:

```
Exception in defer callback: Error: Unknown command
{
  "op":"c",
  "ns": "admin.$cmd",
  "ui": {
    "sub_type":4,
    "buffer": {
      "$binary":"16KKxoL+TtCTzvmpeGPA+w=="
    },
    "position":16
  },
  "o": {
    "drop": "pbmRUsers"
  },
  "o2": {
    "numRecords":5
  },
  "ts": {
    "$timestamp":"7261642129519149061"
  },
  "t":37,
  "v":2,
  "wall": {
    "$date":1690732811979
  }
}
```

I'm using a local install of mongo (Percona) because my app must be able to run on a local network without internet access. I have also enabled a periodic backup which I believe is the source of these oplog operations.

I've updated to v2.13 and am still seeing these exceptions so I'm guessing the drop? operation should also be safely ignored?
