### ISSUE TITLE
Document how to use the Extended Support Maintenance of Node 14

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12631]
Currently it isn't documented anywhere besides some comments on the forum. The [Deployment](https://guide.meteor.com/deployment.html) guide should cover how to install and use this version of Node.

**Comment by Grubba27** [comment]
Yeah, currently, what we have is the updated Readme([commit](https://github.com/meteor/node-v14-esm/commit/86bbaf13d3dc411381c62acafde2467ea5db4617)).
Will ask @aquinoit if we can have a docker file and more text on how to use it to be added to the page!

**Comment by zodern** [comment]
There should be instructions on how to download the tarball, so people who maintain dockerfiles or deployment processes that don't use docker know how to use it.

**Comment by antobinary** [comment]
Hey! I have downloaded NodeJS 14.21.3 from your static page but in some commits I see references to 14.21.3 **.4**
When trying to pull those, I am not successful, so I stick to 14.21.3 (which was the last release prior to ESM anyway). Looking forward to your document and hoping it will shed light on how to obtain the `.4` version

https://github.com/meteor/meteor/pull/12606/files#diff-647d177cca8601046a3cb39e12f55bec5790bfcbc42199dd5fcf063200fac1d0R3

**Comment by ruohki** [comment]
While at it the roadmap could use some love as well. Still 2022 in there :)

**Comment by Grubba27** [comment]
We have created a  [docker image](https://hub.docker.com/r/meteor/node)  for people who want to deploy in their own/ use outside of meteor the node v14.21.4

**Comment by xet7** [comment]
I also built Node.js 14.21.4 for Windows from source, because at Meteor bundle I only found Node.js 14.21.3:

https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4

**Comment by Grubba27** [comment]
I will close this one as we have [added in the docs how to use the ESM node](https://guide.meteor.com/using-node-v14.21.4)
