### ISSUE TITLE
New Async API are not in the docs

### ISSUE THREAD

**Issue by Grubba27** [meteor/meteor#12649]
Currently, our docs page does not include the `*Async` methods that were added in [2.8](https://guide.meteor.com/v2.10/2.8-migration.html).
![Screenshot 2023-05-23 at 09 58 38](https://github.com/meteor/meteor/assets/70247653/02edce51-eb8a-41a4-ac34-73b08a5f4c4a)

We should or could add a section explaining their existence or add them like their normal counterpart.

This issue relates to #12646

**Comment by ciradu2204** [comment]
Hi @Grubba27, can I work on this?

**Comment by Grubba27** [comment]
Sure, @ciradu2204 ! PRs are welcomed!

**Comment by ciradu2204** [comment]
This is a bit more complicated than I expected😲. I guess I need to have
some experience using the AsyncApi in Meteor to be able to make any
changes. If yes, any resource to guide me would be appreciated. Or someone
with more experience can take it. Thanks

**Comment by Ekott2006** [comment]
Hello @ciradu2204, Any Progress???

**Comment by ankushdhavale** [comment]
can I work on this ?

**Comment by Grubba27** [comment]
PRs are welcomed!

**Comment by raunakkumarsingh** [comment]
can i work on this?

**Comment by Grubba27** [comment]
Hey, @raunakkumarsingh  PRs are welcome. You can create a section for every new method, just like you posted there, or just a new section explaining their existence
