### ISSUE TITLE
Large and increasing delay between result and updated DDP messages

### ISSUE THREAD

**Issue by armellarcier** [meteor/meteor#12657]
I have a Meteor method that inserts one `Engagement` (the main collection of my app)

It then inserts a lot of docs related to the engagement, synchronously.

It returns the inserted _id.

The oplog show it takes less that 1 sec to finish all the inserts.

I receive (observing the ws messages in devtools) the `result` message 1sec after calling the method, but the `updated` message arrives only 12 seconds later.

The more the app stays up, without restart, the longer the delay is.

I have absolutely NO idea what is the source of that delay. Does the writefence work as fast as it should ?

**Comment by Grubba27** [comment]
Would need more information.
Do you have a reproduction repo? What is the version you are using?

**Comment by Grubba27** [comment]
Since we did not have any movement, I will close this one for now. If you continue to have this issue/have a reproduction, I will happily open this issue again.
