### ISSUE TITLE
Document how to run older Meteor projects in M1 (ARM)

### ISSUE THREAD

**Issue by Grubba27** [meteor/meteor#12655]
When running older versions of meteor in arm processors, people normally run into the issue of not having it in the platform.

Problem:
```
This project uses Meteor <version>, which isn’t available on this platform. 
To work with this app on all supported platforms, use meteor update
```

They can run the following :

```bash
arch -x86_64 meteor
``` 
We should have this documented in the docs or guide, explaining how to use the `arch` along with Meteor.

**Comment by zodern** [comment]
Would it be possible for Meteor to handle this automatically? It would mostly involve having Meteor check for the x86_64 arch when downloading older versions on m1, and possibly updating the `meteor` script and how springboarding works.

**Comment by Grubba27** [comment]
/bounty $25 

This bounty is just for making the docs. 

will update soon how we would like it to be written

**Comment by rishi-raj-jain** [comment]
@Grubba27 

Isn't this already there at https://docs.meteor.com/install#old-versions-m1?

**Comment by Grubba27** [comment]
Yeah! I think someone did and forgot to close this one. My bad.

https://github.com/meteor/meteor/issues/12649 is still open. 
Thanks for the update.

**Comment by rishi-raj-jain** [comment]
@Grubba27 

Somebody PR'd for the other one 😔
