### ISSUE TITLE
Meteor are creating the "Do the Tutorial" link with wrong URL

### ISSUE THREAD

**Issue by vit0rr** [meteor/meteor#12676]
If you try to create an app using `meteor create --typescript`, it will generate the LinksCollection with an old URL.
It is simple to solve. I just need to change every `main` file at Meteor that refer to `https://www.meteor.com/tutorials/react/creating-an-app`, and change it to `https://react-tutorial.meteor.com/simple-todos/01-creating-app.html`

Follow:
 - [skel-apollo](https://github.com/meteor/meteor/blob/49f95f4a092c4753090bdebe27f0c04b39aff896/tools/static-assets/skel-apollo/server/main.js)
 - [skel-chakra](https://github.com/meteor/meteor/blob/49f95f4a092c4753090bdebe27f0c04b39aff896/tools/static-assets/skel-chakra-ui/server/main.js)
 - [skel-react](https://github.com/meteor/meteor/blob/49f95f4a092c4753090bdebe27f0c04b39aff896/tools/static-assets/skel-react/server/main.js)
 - [skel-tailwind](https://github.com/meteor/meteor/blob/49f95f4a092c4753090bdebe27f0c04b39aff896/tools/static-assets/skel-tailwind/server/main.js)
 - [skel-typescript](https://github.com/meteor/meteor/blob/49f95f4a092c4753090bdebe27f0c04b39aff896/tools/static-assets/skel-typescript/server/main.ts)

I'll send a pull-request to solve this issue.

**Comment by kunalshokeen051** [comment]
is the issue still persist?

**Comment by vit0rr** [comment]
> is the issue still persist?

Thanks for the interest, but I solved it on https://github.com/meteor/meteor/pull/12679

**Comment by namesarnav** [comment]
Hey, could you assign this issue to me if it's still open. I'd love to contribute. Thanks!

**Comment by StorytellerCZ** [comment]
@namesarnav there already is a PR to fix this issue.
