### ISSUE TITLE
Remove RegEx from the guide.meteor

### ISSUE THREAD

**Issue by vit0rr** [meteor/meteor#12689]
[RegEx](https://github.com/longshotlabs/simpl-schema#regex) is no longer supported by simpl-schema.

>Can also be a function that returns a regular expression or an array of them
Any regular expression that must be matched for the key to be valid, or an array of regular expressions that will be tested in order.

>In earlier releases, the SimpleSchema.RegEx object defined standard regular expressions that you could use as the value for the regEx key. However, many of these were prone to DDoS security risks, causing this package to be flagged by security audit tooling. We no longer include any built-in regular expressions. We encourage you to use a custom function or some other method of validating any strings with complex requirements. If necessary, you can look back at the code for previous SimpleSchema releases and copy specific built-in regular expressions into your codebase.

>Also, check out [recheck](https://makenowjust-labs.github.io/recheck/docs/intro/), which includes an ESLint plugin you can add to your project to avoid accidentally writing regular expressions that could be attacked.

So, update these files:
- [methods.md](https://github.com/vit0rr/meteor/blob/dc38e4325dcd88fb3c6d1be1639680c6ff6f5e80/guide/source/methods.md#L278-L301)
- [collections.md](https://github.com/vit0rr/meteor/blob/dc38e4325dcd88fb3c6d1be1639680c6ff6f5e80/guide/source/collections.md#L91-L99)

I'll send a pull request removing the no supported RegEx expressions

**Comment by StorytellerCZ** [comment]
This is correct, however the version that is used in collection2 only supports v1 which has the functionality described. In the community we are looking into forking Simple Schema into Meteor specific branch. The latest version of Simple Schema doesn't work with Meteor so this is a premature move.
