### ISSUE TITLE
node v14.21.4 does not exist

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#12737]
When building my app on a m1 mac I get the follwoing error

```
> fibers@5.0.3 install /Users/aeneas/op/gitRepos/ligenium-webapp/meteor_server/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download/release/v14.21.4/node-v14.21.4-headers.tar.gz
```

But there is not official version `v14.21.4` of node

# Update

The problem was that I have been installing `fibers` in `pakage.json`. Once I have removed the dependency, the problem was fixed!

**Comment by scharf** [comment]
see #12732

**Comment by scharf** [comment]
Here I am using meteor 2.12, but I tried to install the app on a new m1 mac

**Comment by xet7** [comment]
@scharf 

Hmm headers? I have not yet looked what that file has.

I did figure out where Node.js 14.21.4, and released it, so that I could use it in my builds:

https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4

**Comment by scharf** [comment]
How to reproduce it remove the ~/.meteor directory

It turns out that when you reinstall meteor it will install 2.13 which comes with  node `v14.21.3`.
But when Meteor `2.13` is downloaded and you want to build meteor `2.12` then it will use node ``v14.21.4` which comes with meteor `2.13`. 

Very very confusing! Why would a new version of meteor that is installed in parallel with an old version cause the old version to fail?

**Comment by xet7** [comment]
@scharf 

Well, I'm not a Meteor developer, so I don't know all details how builds are made.

I am WeKan maintainer https://wekan.github.io , WeKan is made with Meteor.

I did upgrade WeKan to newest Meteor with:
```
meteor update --release 2.13
```
But I have not tried after that to build with older Meteor.

**Comment by xet7** [comment]
@scharf 

Node.js 14 is EOL, their newest is 14.21.3, new ones will not appear to https://nodejs.org/dist/latest-v14.x/

Meteor only released 3 binaries for Node.js. They did not release all the remaining that were originally built by original Node.js developers like this https://nodejs.org/dist/latest-v14.x/ , so I built and combined files for remaining to https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4

But it's kind of:

1. Node.js devs => No updates to Node.js anymore
2. Meteor devs => Only 3 binaries.
3. Me => remaining binaries, because I release WeKan for more platforms than Meteor officially supports.

So I think I'm 3rd party developer.

I don't know does Meteor have time to release Node.js packages themselves.

**Comment by xet7** [comment]
Hmm, I'm thinking, does Node.js somewhere have crosscompile scripts that would generate these kind of files automatically? https://nodejs.org/dist/latest-v14.x/

Manually building and figuring it out did take me a lot of time.

**Comment by scharf** [comment]
OK, it turns out, when I remove `"fibers": "^5.0.3",` from my package.json, the problem is solved.

**Comment by xet7** [comment]
@scharf 

It could be that you need older fibers version. I recommend testing your builds so that all required dependencies are there. Fibers is not fully removed from Meteor yet.

**Comment by xet7** [comment]
But if I'm wrong, and Meteor works without fibers, please correct me. Thanks!

**Comment by scharf** [comment]
The solution is to remove `fibers` from the `package.json`

**Comment by scharf** [comment]
@xet7 
> But if I'm wrong, and Meteor works without fibers, please correct me. Thanks!

AFAIK `2.x` of Meteor still needs `fibers` (they are built in). There is quite some effort to release version `3` [without fibers](https://github.com/orgs/meteor/projects/10).

For some reason, had an additional installation of `fibers` in my package.json which caused the problem.

**Comment by KoenLav** [comment]
Removing Fibers may work locally / on Galaxy, but does not work in meteor-up yet.

**Comment by drone1** [comment]
I'm running into this with Meteor **2.15** when doing a build with ``meteor build <path> --server-only``. The resultant ``star.json`` looks like this.

``.meteor/{release,packages,versions}`` and ``star.json`` are all [here](https://pastebin.mozilla.org/9jX30Qhh).

Would love some help on this if anyone's got suggestions. Thank you.

**Comment by Grubba27** [comment]
Hey @drone1, what errors are you getting when running? Does it complain about the node not existing? Could you paste the error here?

The snippet from Mozilla was gave me a 404

**Comment by drone1** [comment]
Hey @Grubba27. Not sure what happened to the paste. I'll include here. Hopefully won't annoy people.

```
➜  bundle> cat star.json
{
  "format": "site-archive-pre1",
  "builtBy": "Meteor METEOR@2.15",
  "programs": [
    {
      "name": "web.browser",
      "arch": "web.browser",
      "path": "programs/web.browser/program.json"
    },
    {
      "name": "web.browser.legacy",
      "arch": "web.browser.legacy",
      "path": "programs/web.browser.legacy/program.json"
    },
    {
      "name": "server",
      "arch": "os",
      "path": "programs/server/boot.js"
    }
  ],
  "meteorRelease": "METEOR@2.15",
  "nodeVersion": "14.21.4",
  "npmVersion": "6.14.18",
  "gitCommitHash": "e4dcfd74a1aef993d04852d20423acbfd55ec08f"
}
➜  bundle> nvm exec 14.21.4 ./main.js
N/A: version "v14.21.4" is not yet installed.

You need to run "nvm install 14.21.4" to install it before using it.
➜  bundle> nvm install 14.21.4
Version '14.21.4' not found - try `nvm ls-remote` to browse available versions.
```
Build with the following .meteor files:
.meteor/release
```
METEOR@2.15
```
.meteor/packages
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.5.1             # Packages every Meteor app needs to have
mobile-experience@1.1.1       # Packages for a great mobile UX
mongo@1.16.8                   # The database Meteor supports right now
reactive-var@1.0.12            # Reactive variable for tracker
tracker@1.3.3                 # Meteor's client-side reactive programming library

es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.16.8              # Enable ECMAScript2015+ syntax in app code
shell-server@0.5.0            # Server-side component of the `meteor shell` command

ostrio:flow-router-extra
dynamic-import@0.7.3
email@2.2.5
mdg:seo
fongandrew:find-and-modify
yasinuslu:blaze-meta
facts@1.0.9
meteorhacks:ssr
session@1.2.1
seba:minifiers-autoprefixer
check@1.3.2
nolimits4web:swiper
froatsnook:valid-email
spacebars-compiler
mdg:validated-method
ddp-rate-limiter@1.2.1
server-render@0.4.1
dburles:collection-helpers
ostrio:flow-router-meta
jquery@3.0.0!
typescript@4.9.5
meteortesting:mocha
tunifight:loggedin-mixin
fourseven:scss
zodern:hide-production-sourcemaps
standard-minifier-js@2.8.1
fetch@0.1.4
hwillson:stub-collections
dburles:factory
mdg:meteor-apm-agent
blaze-html-templates
aldeed:collection2@4.0.0
accounts-base@2.2.10
alanning:roles
accounts-password@2.4.0
underscore@1.6.0
```
.meteor/versions
```
accounts-base@2.2.10
accounts-password@2.4.0
alanning:roles@3.6.1
aldeed:collection2@4.0.0
aldeed:simple-schema@1.13.1
allow-deny@1.1.1
autoupdate@1.8.0
babel-compiler@7.10.5
babel-runtime@1.5.1
base64@1.0.12
binary-heap@1.0.11
blaze@2.8.0
blaze-html-templates@2.0.1
blaze-tools@1.1.4
boilerplate-generator@1.7.2
caching-compiler@1.2.2
caching-html-compiler@1.2.2
callback-hook@1.5.1
check@1.3.2
dburles:collection-helpers@1.1.0
dburles:factory@1.5.0
ddp@1.4.1
ddp-client@2.6.1
ddp-common@1.4.0
ddp-rate-limiter@1.2.1
ddp-server@2.7.0
diff-sequence@1.1.2
dynamic-import@0.7.3
ecmascript@0.16.8
ecmascript-runtime@0.8.1
ecmascript-runtime-client@0.12.1
ecmascript-runtime-server@0.11.0
ejson@1.1.3
email@2.2.5
es5-shim@4.8.0
facts@1.0.9
fetch@0.1.4
fongandrew:find-and-modify@1.0.0
fourseven:scss@4.16.0
froatsnook:valid-email@1.0.0
geojson-utils@1.0.11
hot-code-push@1.0.4
html-tools@1.1.4
htmljs@1.2.0
http@2.0.0
hwillson:stub-collections@1.0.9
id-map@1.1.1
inter-process-messaging@0.1.1
jquery@3.0.0
launch-screen@2.0.0
livedata@1.0.18
localstorage@1.2.0
logging@1.3.3
mdg:meteor-apm-agent@3.5.1
mdg:seo@3.5.1
mdg:validated-method@1.3.0
meteor@1.11.5
meteor-base@1.5.1
meteorhacks:ssr@2.2.0
meteortesting:browser-tests@1.5.3
meteortesting:mocha@2.1.0
meteortesting:mocha-core@8.1.2
minifier-css@1.6.4
minifier-js@2.7.5
minimongo@1.9.3
mobile-experience@1.1.1
mobile-status-bar@1.1.0
modern-browsers@0.1.10
modules@0.20.0
modules-runtime@0.13.1
mongo@1.16.8
mongo-decimal@0.1.3
mongo-dev-server@1.1.0
mongo-id@1.0.8
mongo-livedata@1.0.12
nolimits4web:swiper@4.4.1
npm-mongo@4.17.2
observe-sequence@1.0.22
ordered-dict@1.1.0
ostrio:flow-router-extra@3.9.0
ostrio:flow-router-meta@2.1.3
ostrio:flow-router-title@3.2.2
promise@0.12.2
raix:eventemitter@1.0.0
random@1.2.1
rate-limit@1.1.1
react-fast-refresh@0.2.8
reactive-dict@1.3.1
reactive-var@1.0.12
reload@1.3.1
retry@1.1.0
routepolicy@1.1.1
seba:minifiers-autoprefixer@2.0.1
server-render@0.4.1
session@1.2.1
sha@1.0.9
shell-server@0.5.0
socket-stream-client@0.5.2
spacebars@1.5.0
spacebars-compiler@1.3.2
standard-minifier-js@2.8.1
templating@1.4.3
templating-compiler@1.4.2
templating-runtime@1.6.4
templating-tools@1.2.3
tracker@1.3.3
tunifight:loggedin-mixin@0.1.0
typescript@4.9.5
ui@1.0.13
underscore@1.6.0
url@1.3.2
webapp@1.13.8
webapp-hashing@1.1.1
yasinuslu:blaze-meta@0.3.3
zodern:hide-production-sourcemaps@1.2.0
zodern:types@1.0.11
```

**Comment by drone1** [comment]
I had even tried uninstalling and reinstalling meteor by deleting ~/.meteor and then running the standard curl command, but no change. 

I'm at a total loss here. Any suggestions? Thanks.

**Comment by Grubba27** [comment]
Sure! Have you seen this [doc](https://guide.meteor.com/using-node-v14.21.4)?

You are trying to run the bundle using `nvm`:
<details>
<summary>NVM command</summary>

```bash
➜  bundle> nvm exec 14.21.4 ./main.js
N/A: version "v14.21.4" is not yet installed.

You need to run "nvm install 14.21.4" to install it before using it.
➜  bundle> nvm install 14.21.4
Version '14.21.4' not found - try `nvm ls-remote` to browse available versions.
```
</details>

Try installing our node from one of those links.

- [Linux x64](https://static.meteor.com/dev-bundle-node-os/v14.21.4/node-v14.21.4-linux-x64.tar.gz)
- [MacOs x64](https://static.meteor.com/dev-bundle-node-os/v14.21.4/node-v14.21.4-darwin-x64.tar.gz)
- [MacOs ARM](https://static.meteor.com/dev-bundle-node-os/v14.21.4/node_Darwin_arm64_v14.21.4.tar.gz)
- [Windows x64](https://static.meteor.com/dev-bundle-node-os/v14.21.4/node-v14.21.4-win-x64.7z)


Alternatively, you can try running this script to install node 14.21.4 in your machine:

<details>
<summary>Script</summary>

```bash

```bash

#!/bin/bash

# Set environment variables
NODE_VERSION="14.21.4"
NODE_URL="https://static.meteor.com/dev-bundle-node-os/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz"
DIR_NODE="/usr/local"

# Download and install Node.js using wget
wget -qO- "$NODE_URL" | tar -xz -C "$DIR_NODE"/ && mv "$DIR_NODE"/node-v${NODE_VERSION}-linux-x64 "$DIR_NODE"/v$NODE_VERSION

# Add node and npm to the PATH so the commands are available
export NODE_PATH="$DIR_NODE/v$NODE_VERSION/lib/node_modules"
export PATH="$DIR_NODE/v$NODE_VERSION/bin:$PATH"

# Confirm the installation
node -v
npm -v

```

</details>
