### ISSUE TITLE
Can't use dots in cracked account username

### ISSUE THREAD

**Issue by luktpro** [meteor/meteor#12733]
When I put dots in cracked account username when adding an account, it just doesn't let me proceed. No idea why/

for those who dont wanna look at my newest comment: _alright, so pretty much if you try and create a cracked account everything works most of the time, im aware of the no letter boundaries etc, pretty sure you can put dots everywhere, and everything works everythings great, but when i try to make a cracked account with the username ".test" for example, when clicking create the loading animation doesnt play, nothing happens, im not sure if this is a local issue, as tlauncher and some cracked platforms can indeed have usernames like ".test", and sometimes when trying to do my daily aternos trolling by logging on with the owners username, they have a dot at the start of the username (as a THIRD example, ".comme_nt"). not a massive issue but can be annoying sometimes, thanks for responding_

**Comment by StorytellerCZ** [comment]
Hello, can you please be more specific? What cracked account usernames? Do you have a reproduction that with samples that we could analyze? What version of Meteor and accounts package are you using?

**Comment by coolBrown12** [comment]
be specfic some kind of the example what you are saying please explain that
be more clear what your point

**Comment by luktpro** [comment]
alright, so pretty much if you try and create a cracked account everything works most of the time, im aware of the no letter boundaries etc, pretty sure you can put dots everywhere, and everything works everythings great, but when i try to make a cracked account with the username ".test" for example, when clicking create the loading animation doesnt play, nothing happens, im not sure if this is a local issue, as tlauncher and some cracked platforms can indeed have usernames like ".test", and sometimes when trying to do my daily aternos trolling by logging on with the owners username, they have a dot at the start of the username (as a THIRD example, ".comme_nt"). not a massive issue but can be annoying sometimes, thanks for responding

**Comment by luktpro** [comment]
also my bad for commenting so late, i dont check github often

**Comment by StorytellerCZ** [comment]
I don't understand what you are saying. What do you mean by `cracked account`? What is `tlauncher`?
Are you sure you have the correct repository? From what you are describing this doesn't seem related to Meteor at the very least and usage of words like `cracked`, `when trying to do my daily aternos trolling by logging on with the owners username` suggest illegal activity at the worst.

**Comment by pmogollons** [comment]
@StorytellerCZ A quick search on google makes me think this has something to do with minecraft. Probably safe to close this issue @Grubba27.

https://meteorclient.com/
https://github.com/DAMcraft/MeteorServerSeeker

<img width="761" alt="image" src="https://github.com/meteor/meteor/assets/32210050/93a1463c-8c9b-4650-8a6c-2cb98e707749">
