### ISSUE TITLE
Compatibility with Gojs

### ISSUE THREAD

**Issue by tajohome** [meteor/meteor#12730]
1. Create a new meteor project.
2. import gojs or gojs-react in the app
3. you get error Uncaught TypeError: Cannot set property version of #<Object> which has only a getter at Ep.runGetters

I tried with meteor 2.11~13.
Any way of using gojs in meteor?

**Comment by StorytellerCZ** [comment]
Have you tried adding recompile option in `package.json` in your app?

```
"meteor": {
    "nodeModules": {
      "recompile": {
        "gojs": true
      }
    }
}
```

**Comment by tajohome** [comment]
"meteor": {
    "nodeModules": {
      "recompile": {
        "gojs": true
      }
    }
}

or

"nodeModules": {
      "recompile": {
        "gojs": true,
        "gojs-react": true
      }
    },

doesn't work for me.
Still having same issue

**Comment by Grubba27** [comment]
@tajohome can you provide an example/repo of what you are trying to do? so that we can test this and check what is going on?
