### ISSUE TITLE
Create project and run with Vue version 2 bugs!

### ISSUE THREAD

**Issue by DRBofa** [meteor/meteor#12770]
Hello sir please fix this bug when I create project with `vue-2` after created and I run it's show me like that 
`meteor create app --vue-2`
![telegram-cloud-photo-size-5-6265064388494996400-y](https://github.com/meteor/vue-tutorial/assets/35457763/1c7ce9eb-22f9-4e41-bff1-4d60bfda1bd4)

I fixed this bugs by run command `meteor add akryum:vue-component@0.15.2`
![telegram-cloud-photo-size-5-6265064388494996401-y](https://github.com/meteor/vue-tutorial/assets/35457763/21c55021-1b10-4815-a5fd-298e948a7f37)

**Comment by Grubba27** [comment]
This one will be closed with https://github.com/meteor/meteor/pull/12694
