### ISSUE TITLE
Feature - Make `meteor create` more interactive.

### ISSUE THREAD

**Issue by Grubba27** [meteor/meteor#12791]
## Currently

Today, when using `meteor create` we must provide the name and the template that we want to use. For example:

```bash
meteor create blaze-app --blaze
```
_if no flag is passed it does create a `--react` app_

## Proposal

What I propose is we do an upgrade in the overall experience while creating an app.

> [!IMPORTANT]
> *Current features should not be changed.*

If the user uses just `meteor create` it should work similar to what we have today in `meteor generate` [command](https://docs.meteor.com/commandline.html#meteorgenerate), asking what the name of their app and which template it should use is.

Image of how `meteor generate` works today:
![Screenshot 2023-09-26 at 12 46 21](https://github.com/meteor/meteor/assets/70247653/c5e3532b-3c86-4ef8-a5e9-6108a27e1b38)

What I was thinking is something like `vite` does in their `npm create vite` command

<img width="584" alt="Screenshot 2023-09-26 at 14 29 13" src="https://github.com/meteor/meteor/assets/70247653/79960039-eaf7-40cd-8ac1-cb25389649b7">

**Comment by StorytellerCZ** [comment]
I'm for it. I think this would be a nice addition to Meteor 3.

**Comment by StorytellerCZ** [comment]
I think it is more appropriate to leave it in 3 as it is a major change no how create works and will make 3 more enticing. Plus once 3 is released all the new projects will be started in it, so there is no need to waste resources on backporting it.

**Comment by mr-loop-1** [comment]
Hi @Grubba27  I would like to pick this. Can you assign to me.

**Comment by mr-loop-1** [comment]
@Grubba27 @StorytellerCZ 
Do we intend to use it only for selecting template or include example, package and proptotype as well ?
For ex. if I include example, then there would be one additional prompt for getting the repo name

**Comment by Grubba27** [comment]
We could add that as well but I would focus only on creating projects for now, creating packages can always be done later.

**Comment by ImranSah** [comment]
Hi, I would like to work on this.

**Comment by Amar-3** [comment]
I'm finding this issue interesting to work upon

**Comment by Grubba27** [comment]
This was implemented.
