### ISSUE TITLE
Add support for async functions for allow-deny package

### ISSUE THREAD

**Issue by soloviovmax** [meteor/meteor#12807]
Version of Meteor - 2.13.3

**The expected behavior**:
Support for async functions for a convenient transition to new asynchronous APIs.

**The actual behavior**:
The first example returns false.
Second one returns promise, it converts to boolean that’s why the update is always allowed.
<img width="329" alt="image" src="https://github.com/meteor/meteor/assets/3389196/eafe5af9-4051-4d25-95e1-4fd3b99e883b">

If we can no longer rely on fibers within the allow/deny rules in Meteor 3, it will require modifications to certain parts of our application. While this adjustment is not an immediate requirement, could you please clarify whether this change is planned for Meteor 2.x or 3.0?

**Comment by We13b-MD** [comment]
Hi @soloviovmax  i will love to collaborate with you on this issue.

**Comment by acemtp** [comment]
Hello,

This is really an important issue.

Lot of allow/deny functions use some mongo call that are async in meteor 3 and make allow/deny completely fail.

Since it's meteor 3 rc1 and allow/deny are a Meteor core feature, I wonder if meteor plan to take a look at it.

Any tips @StorytellerCZ ?

**Comment by acemtp** [comment]
@StorytellerCZ you should be able to close this one with rc4
