### ISSUE TITLE
Careers Page Grid Images are not Responsive in Mobile Device

### ISSUE THREAD

**Issue by crocmons** [meteor/meteor#12817]
I want to fix this issue ..
Problem: The careers page grid images on this website do not display correctly on mobile devices, rendering them non-responsive. This means that when users access your careers page from a mobile device, such as a smartphone or tablet, the images within the grid do not adapt to the smaller screen size as expected.

Expected Behavior: We expect the grid images on the careers page to be responsive, adjusting their size and layout appropriately to provide an optimal viewing experience on various mobile devices. This ensures that users can easily browse related content while using smaller screens.

Right now, it look like this -
![Screenshot (548)](https://github.com/meteor/meteor/assets/106610322/5e4c60aa-0aa1-42e2-8d9d-c00f73d0900e)

**Comment by Shashankpantiitbhilai** [comment]
please assign it to me

**Comment by StorytellerCZ** [comment]
Hello, this is the repository for Meteor.js, not the official website. As far as I know the website is not public so it can't be assigned to you as you don't have access to the code.
Thank you for the feedback, I'm sure Meteor Software is going to take a look on this.
@fredmaiaarantes @Grubba27 @denihs
