### ISSUE TITLE
Meteor 3 - Crosswalk was deprecated long ago.

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#12834]
Perhaps it is time to remove it entirely from Meteor. I saw it mentioned in the change log for Meteor 3.

https://github.com/meteor/meteor/tree/devel/packages/crosswalk

**Comment by harryadel** [comment]
If that's the case, why not start a PR?

**Comment by StorytellerCZ** [comment]
I think we can deprecate it already in Meteor 2.14. First time seeing this package honestly.

**Comment by datacarl** [comment]
adsf
