### ISSUE TITLE
Broken links in WebApp API docs

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12878]
I’d submit a PR but it looks like these sections of the API docs are embedded and maybe protected?

The IncomingMessage link should be: https://nodejs.org/api/http.html#class-httpincomingmessage

The ServerResponse link should be: https://nodejs.org/api/http.html#class-httpserverresponse

![IMG_8886](https://github.com/meteor/meteor/assets/1749828/9bfd6590-493c-4e73-9f24-ac79477ec300)

**Comment by Rai-Sahil** [comment]
Hi @StorytellerCZ 

Sure I'd like to work on this issue.

**Comment by StorytellerCZ** [comment]
Go ahead @Rai-Sahil

**Comment by Rai-Sahil** [comment]
@StorytellerCZ 

How to run this app, I want to fix the error, but it's written no where on how to run the app locally.

**Comment by StorytellerCZ** [comment]
https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#documentation

Go into the docs folder: https://github.com/meteor/meteor/tree/devel/docs
Install dependencies and run.

**Comment by raahul131** [comment]
Hi @StorytellerCZ, I would like to work on this issue.

**Comment by StorytellerCZ** [comment]
@raahul131, go ahead. No one needs to ask for permissions here. Submitting a PR is what matters.
