### ISSUE TITLE
`Console.log` is not a function

### ISSUE THREAD

**Issue by leonardoventurini** [meteor/meteor#12876]
I believe this line should be either calling `runLog.log` or `Console.error`:

https://github.com/meteor/meteor/blob/6922fb6457d339d7b4fc76c73d10df3ed54c1871/tools/runners/run-all.js#L182

I got this error

![image](https://github.com/meteor/meteor/assets/17411182/e35bfd43-225f-4e8c-ac6d-e41006c426e2)

When it should be outputting something like this

![image](https://github.com/meteor/meteor/assets/17411182/74ab5493-948e-447c-bec2-bbdd669ee02e)

It is happening on Meteor 3 Alpha 17, I am on a Mac M2

The mongo issue itself happens randomly for me, in the past cleaning the tmp folder fixed the issue, but now I had to reboot my machine to have it work again.

But in sum it should be showing the mongo error and not the `Console.log` is not a function error.

Meteor 2 seems to be calling `Console.error`

**Comment by vr-varad** [comment]
@StorytellerCZ 
if I am not wrong
The error TypeError: Console.log is not a function that indicates that there is a typo in your code. It seems like you intended to use console.log instead of Console.log. JavaScript is case-sensitive, so the correct syntax is console.log.
am I right

**Comment by snowwolfjay** [comment]
Console class doesnt have an log method. info/warn... is ok, really suggest use typescript for simple check avoid those small syntax error

**Comment by snowwolfjay** [comment]
or use github editor preview all method, i checked the console/console.js file, no log method

**Comment by StorytellerCZ** [comment]
Looking at the code it should probably be `runLog.log` as @leonardoventurini suggested.
