### ISSUE TITLE
[Meteor 3] Meteor.callAsync doesn't provide result from server

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12888]
To reproduce:
In a new app from Meteor 3.0-alpha.18, add this code to both the client and server:

```js
if (Meteor.isServer) {
  Meteor.methods({
    'server-only'() {
      return 'result'
    }
  });
} else {
  Meteor.callAsync('server-only').then(console.log);
}
```

Instead of logging `result`, it logs:
```
{stubValuePromise: Promise}
```

**Comment by paulincai** [comment]
A related conversation: https://forums.meteor.com/t/meteor-3-0-alpha-15-the-return-from-methods/60709
