### ISSUE TITLE
[Meteor 3] Improve logs when creating app with --release

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12887]
When creating an app with the `meteor create --release`, it shows in red:

```
Something has happened while creating your app using git clone.                    
Will use cached version of skeletons.
Error message:  Using release option
```

It would be nice if this message could be styled or phrased more as a warning or info instead of as an error.

**Comment by Grubba27** [comment]
Thanks for the feedback!! will add this to our board so that we can address this.

**Comment by denihs** [comment]
It's now fixed:

![image](https://github.com/user-attachments/assets/2b2cc78d-d1fc-4e44-87b5-3c5710712842)
