### ISSUE TITLE
[Meteor 3] Mongo.Cursor.observeChanges returns a Promise instead of a query handle

### ISSUE THREAD

**Issue by ebroder** [meteor/meteor#12918]
With the current alpha release of v3, calling `observeChanges` (at least on the server side - client might be different!) now returns a `Promise<LiveQueryHandle>`. Previously, it returned a `LiveQueryHandle` directly. This means that it's not possible to write code that works correctly on both v2 and v3.

Specifically, `MongoConnection.prototype._observeChanges` is now an [`async` function](https://github.com/meteor/meteor/blob/release/METEOR%403.0-alpha.19/packages/mongo/mongo_driver.js#L1433), causing it to return a Promise).

It seems ideal, if possible, to continue returning a `LiveQueryHandle` directly rather than returning a `Promise`. However, if that's not possible, then I would request renaming `observeChanges` to `observeChangesAsync` and introducing a wrapper in v2 so that there's a clean migration path.

**Comment by ebroder** [comment]
For the record I suspect that there's a similar issue in `observe`, but my code only uses `observeChanges` so I haven't verified that directly.

**Comment by radekmie** [comment]
These are definitely fine on the client (I just checked on [Simple Tasks](https://simpletasks.meteorapp.com)) and there's `isReadyPromise` to `await` if needed, so it's only a server-side problem.

**Comment by manueltimita** [comment]
I just noticed the same issue in [meteor-publish-composite](https://github.com/Meteor-Community-Packages/meteor-publish-composite), which depends on `observe`. I'm about to open an issue there and suggest a pull request

**Comment by Grubba27** [comment]
I just confirmed it; on the server, it does return a promise. The client is fine.

**Comment by champel** [comment]
The existing implementation of `observe` and `observeChanges` does not return until the initial fetch is complete. This enables the triggering of an action once the initial additions have been processed. However, if you solely return the LiveQueryHandler without the promise, it becomes impossible to detect the conclusion of the initial fetch. I would prefer a distinct implementation such as `observeAsync` or `observeChangesAsync` that returns the promise, enabling me to identify the completion of the initial fetch.

**Comment by champel** [comment]
The central concept here is that not returning a promise in version 3 will result in the inability to uphold the existing functionality (which involves tracking the completion of the initial fetch). While the inclusion of observerAsync may not be ideal, it facilitates a gradual migration and aligns with the rest of API modifications.

**Comment by ebroder** [comment]
I somehow missed that `observeAsync` and `observeChangesAsync` had landed in both 3.0 and 2.x, so I need to play with the API some, but that seems great. However, it does seem that both are missing in the TypeScript declarations in `mongo.d.ts`.

**Comment by nachocodoner** [comment]
Yes, observeAsync and observeChangesAsync were introduced in Meteor 3.x. In Meteor 2.x, it's not merged yet but is slated for release 2.16, expected this week. [Here's the pull request.](https://github.com/meteor/meteor/pull/13066)

Your point about TypeScript is valid. I'll include that. Thanks.

**Comment by denihs** [comment]
This should be fixed now be fixed.
