### ISSUE TITLE
[Meteor 3] Improve migration path for non-mongo packages

### ISSUE THREAD

**Issue by ebroder** [meteor/meteor#12920]
Looking through the v3 [changelog](https://github.com/meteor/meteor/blob/release-3.0/docs/generators/changelog/versions/3.0.md), there is a long list of methods which were previously synchronous but are now async. This makes the migration path quite challenging, as there's no way to write code that will run correctly on both v2 and v3.

For all of these methods, I would really love to see `Async` wrappers, similar to the `mongo` wrappers (i.e. `findOneAsync`, `Cursor.prototype.fetchAsync`, etc.). Even if the v3 versions of these methods have the same implementation as the non-`Async` methods, by having async variants in v2, we can port code over in advance of upgrading to v3.

**Comment by denihs** [comment]
I believe this is something we already did :tada:  I'm closing this one.
