### ISSUE TITLE
[Meteor 3] Rename or remove asyncLocalStorage global

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12929]
Meteor 3 adds a new global (`asyncLocalStorage`). This name seems like it would be relatively likely for app/package code to conflict. It would be nice if Meteor renamed it to something that is more likely to be unique (for example: `__meteorAsyncLocalStorage`) or avoided adding a new global by having outside code create it (the meteor-tool for build plugins, and boot.js for apps) and provide it to the `meteor` package using existing means to do so (either the `__meteor_bootstrap__` global or [specialArgs](https://github.com/meteor/meteor/blob/8d94099d61eda975c1f308ec953f6e5d7441bf0e/tools/static-assets/server/boot.js#L197-L222)).

**Comment by denihs** [comment]
Solved here https://github.com/meteor/meteor/pull/13224/
