### ISSUE TITLE
[Meteor 3] TypeScript declarations are out of date

### ISSUE THREAD

**Issue by ebroder** [meteor/meteor#12921]
It seems like the TypeScript type declarations are out of date for many of the methods which have been changed to become async. Just going through the [changelog](https://github.com/meteor/meteor/blob/release-3.0/docs/generators/changelog/versions/3.0.md), for instance, it looks like almost everything [under the `Accounts` namespace](https://github.com/meteor/meteor/blob/release-3.0/packages/accounts-base/accounts-base.d.ts#L150) should return a promise.

(Relatedly, and this is admittedly more minor, many of the jsdoc comments are also out of date - e.g. `Accounts.findUserByUsername` is [documented to return an `Object`](https://github.com/meteor/meteor/blob/release-3.0/packages/accounts-password/password_server.js#L124), but should probably say that it returns a `Promise<Object>`.)

**Comment by denihs** [comment]
This should be fixed now. I'm closing this one.

**Comment by derwaldgeist** [comment]
Hey, I just stumbled upon this, using the latest Meteor version 3.0.3 with TypeScript.

`Accounts.findUserByUsername()` is still being marked not returning a promise:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/b40306fa-1cb6-4709-8f18-114746a2b7dd">

Also, the Meteor React tutorial is outdated in this respect:

https://react-tutorial.meteor.com/simple-todos/07-adding-user-accounts
