### ISSUE TITLE
Adding a package with `meteor add` does not pull the latest version

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12933]
When I run `meteor add jam:easy-schema` on a fresh project, it's not pulling the latest version of the package. It's using `v1.1.0` instead of `1.2.0-alpha300.19`. 

Am I doing something wrong?

Atmosphere doesn't show that the version exists but Packosphere does:
<img width="1392" alt="Screenshot 2023-12-22 at 11 38 53 AM" src="https://github.com/meteor/meteor/assets/1749828/fde4ad2e-421d-4e2e-903b-83484f0be7cd">
<img width="1407" alt="Screenshot 2023-12-22 at 11 39 31 AM" src="https://github.com/meteor/meteor/assets/1749828/555feb44-725a-4904-8a28-4b972848d6c5">

This is what the `package.js` looks like:
```
Package.describe({
  name: 'jam:easy-schema',
  version: '1.2.0-alpha300.19',
  summary: 'An easy way to add schema validation for Meteor apps',
  git: 'https://github.com/jamauro/easy-schema',
  documentation: 'README.md'
});

Npm.depends({
  'flat': '5.0.2'
});

Package.onUse(function(api) {
  api.versionsFrom(['2.8.1', '3.0-alpha.19']);
  api.use('mongo');
  api.use('check');
  api.use('ecmascript');
  api.use('mdg:validation-error@0.5.1');
  api.mainModule('easy-schema-client.js', 'client');
  api.mainModule('easy-schema-server.js', 'server');
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('jam:easy-schema');
  api.use('mongo');
  api.use('mongo-decimal');
  api.mainModule('easy-schema-tests.js');
});
```

**Comment by Grubba27** [comment]
For meteor packages, in your case, the latest version is 1.1.0 ([code](https://github.com/meteor/meteor/blob/c5ba866e1a5febf7b0fd4cf60ece85a662fe38c7/tools/packaging/catalog/catalog.js#L217-L220)), if your version includes dashes it is assumed that is a prerelease version and so it ignores it as a "usable" version, if you want it to be installed you should pass the "@".

`meteor add jam:easy-schema@1.2.0-alpha300.19`

**Comment by jamauro** [comment]
Thanks, I didn't realize that's how it worked. :)

**Comment by fredmaiaarantes** [comment]
> For meteor packages, in your case, the latest version is 1.1.0 ([code](https://github.com/meteor/meteor/blob/c5ba866e1a5febf7b0fd4cf60ece85a662fe38c7/tools/packaging/catalog/catalog.js#L217-L220)), if your version includes dashes it is assumed that is a prerelease version and so it ignores it as a "usable" version, if you want it to be installed you should pass the "@".
> 
> `meteor add jam:easy-schema@1.2.0-alpha300.19`

Do we have this documented somewhere, @Grubba27?
