### ISSUE TITLE
Footer on Mobile screen could be better

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [meteor/meteor#12942]
![image](https://github.com/meteor/meteor/assets/78686630/9ed0792e-d8de-4f92-b4b1-aa9630dba0b8)
I am talking about this page.

**Comment by Grubba27** [comment]
Thanks for the feedback @ARYAN-CODES-STAR ! I will let the cloud team know!

**Comment by MZ-AD** [comment]
I can make it look better and responsive on mobile screen, if its not assigned already, I can work on it.

**Comment by StorytellerCZ** [comment]
Closing this as this is not part of this repository.
@fredmaiaarantes @leonardoventurini @denihs for your reference here.
