### ISSUE TITLE
Meteor 3 beta.0: Throwing an error inside of a meteor method doesn't throw on the client

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#12957]
Found a breaking change from the upgrade to version 3 that doesn't seem like it was intentional:

On Server:
```
Meteor.methods({
 throwAnError:function() {
    throw "Error";
  }
  }
```

On client:
```
  console.log("THROW", Meteor.call("throwAnError"));
```

On Meteor 2, this will correctly throw an error on the client that can be caught and handled, but on Meteor 3 it is returning a promise.

If you await the promise it will correctly throw, but this is a breaking change, and I am not sure if it was necessary?

If it was a necessary change, I think the types should be updated where if you don't have a callback it knows it is asynchronous and it needs to be called out in the change log 

To catch all the times this should have been async I locally changed the types to:
```
    type NotFunc<T> = Exclude<T, Function>;
    function call<T>(name: string, ...args: [...any, (e: Meteor.Error, res: T) => any]): void;
    function call(name: string, ...args: [...any, NotFunc<any>]): Promise<any>;
    function call(name: string): Promise<any>;
```

**Comment by AvinRai** [comment]
I'm working on this!

**Comment by nachocodoner** [comment]
I think this is behaving as expected. Maybe it was an issue on beta.0, but in current RC.4 doesn't return a promise and it does throw properly the error, as in Meteor 2.x. Attached the proof.

![image](https://github.com/meteor/meteor/assets/2581993/0fa4fd53-41ab-4ec4-afb1-fa7ab0c70ca6)

**Comment by ToyboxZach** [comment]
Yes I believe this issue is resolved
