### ISSUE TITLE
Meteor 3.0:  allow `async` functions to be registered in `Accounts.registerLoginHandler`  to become fiber free

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#12955]
In order to register fibers free LoginHandlers, [`registerLoginHandler`](https://github.com/meteor/meteor/blob/release-3.0/packages/accounts-base/accounts-base.d.ts#L316) should support async functions.

**Comment by ruohki** [comment]
Just stumbled upon this issue while implementing passkey login. This is infact a roadblock - sadly

**Comment by StorytellerCZ** [comment]
@ruohki that is one option, but it would be better if it supported async. Should be done before we get out of beta.

**Comment by ruohki** [comment]
Ofc this should be implemented, i was just providing a hint if someone needs it right now :)

**Comment by StorytellerCZ** [comment]
Last time I checked this has become the case in Meteor 3. Closing for now.
