### ISSUE TITLE
Meteor 3 changes the default behavior of Meteor.absoluteUrl()

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#12965]
If no ROOT_URL is specified On Meteor 2 
Metoer.absoluteUrl() returns localhost:3000
On Meteor 3 
Metoer.absoluteUrl() returns 127.0.01:3000

What's worse is you can't even force ROOT_URL = localhost as it seems to override it at some point.

Is this on purpose? 

It mostly is causing us tooling issues, but it is slightly annoying to our upgrade testing.

**Comment by Grubba27** [comment]
Yes, we did that change, primarily because there was an issue with using localhost, with Node 16 > in Windows, from what I recall. We will do a revision on this, maybe this should only change for Windows.

**Comment by ToyboxZach** [comment]
Ah got it. I am personally fine with it switching, it would just need to be explicitly mentioned in a changelog. And I think it is worth it being the same across all platforms.

At first glance it just seemed like an unnecessary change that was breaking our testing experience.

**Comment by ToyboxZach** [comment]
If we decide it shouldbe different between windows and others, IMO it should just be suggested to use ROOT_URL=127.0.0.1 when running on windows, instead of changing how the actual code runs. Having it be different would make it more annoying for our experience, if we ever got a developer who worked on windows.

**Comment by Grubba27** [comment]
It is being mentioned in the  changelog: https://github.com/meteor/meteor/blob/a8dbcd7d033be6ab865d68bad561fcb55e1e9965/docs/generators/changelog/versions/3.0.md#L367-L371.

You gave me a good idea. Run the windows tests exactly like you said, passing the argument `ROOT_URL`.

**Comment by ToyboxZach** [comment]
Ah got it, didn't see that when I first looked at the changelog (its a pretty hefty change log and obviously not finished so understandable)

That phrasing does make me still feel like I could force ROOT_URL=http://localhost so could use some fixing up. Also there is a typo as the url would be 127.0.0.1 not 127.0.1
