### ISSUE TITLE
[ Meteor v3 ] -`Email.sendAsync` fails, also impacting `accounts-password` methods

### ISSUE THREAD

**Issue by manueltimita** [meteor/meteor#12963]
`Email.sendAsync()` fails with the following error.

```
Error sending email {
  err: TypeError: Cannot read properties of undefined (reading 'cacheKey')
      at getTransport (packages/email/email.js:113:10)
      at Object.Email.sendAsync (packages/email/email.js:253:29)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

If wrapped in `Meteor.bindEnvironment`, then the error is swallowed. In fact, I am not sure it even executes.

Here is a repo to reproduce the error: [meteor-email-bug](https://github.com/manueltimita/meteor-email-bug).

EDIT: Importantly, this also affects all related `accounts-password` methods:
- `Accounts.sendResetPasswordEmail`
- `Accounts.sendEnrollmentEmail`
- `Accounts.sendVerificationEmail`

**Comment by denihs** [comment]
This [PR](https://github.com/meteor/meteor/pull/12977) should fix this. The solution will be in the next beta.
