### ISSUE TITLE
[Meteor 3] Server-only Method displays "Method stub took too long" warning in browser console when using Meteor.callAsync

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12999]
Version: `Meteor 3.0-beta.0`

I have a server-only Method that I'm calling, i.e. it has no stub, but I'm seeing this warning in the browser console when I use `Meteor.callAsync`. If I use `Meteor.applyAsync`, I don't see the warning.

```js
[Warning] Method stub (updateLink) took too long and could cause unexpected problems. Learn more at https://github.com/zodern/fix-async-stubs/#limitations (ddp-client.js, line 245)
```

Expected: I shouldn't see a stub warning if the Method doesn't have a stub. Also I don't think I should see this warning even if it were stubbed.

Here's the Method on the server:

```js
// /server/main.js
import { Links } from '/imports/api/links';

const updateLink = async () => {
  const { _id } = await Links.findOneAsync() || {};
  return Links.updateAsync({ _id }, { $set: { title: 'hello' }});
};

Meteor.methods({ updateLink })
```

```js
// on the client

const updateLink = async () => {
  try {
    await Meteor.callAsync('updateLink');
  } catch (error) {
    console.error(error)
  }
};
```

**Comment by nachocodoner** [comment]
This is going to be fixed here, https://github.com/meteor/meteor/pull/13055

**Comment by StorytellerCZ** [comment]
@nachocodoner can this now be closed?

**Comment by nachocodoner** [comment]
Yes, it is fixed and included on the next beta. Ty
