### ISSUE TITLE
3.0-beta.6 > Create VueJs App > Cannot find module 'fibers'

### ISSUE THREAD

**Issue by firewater** [meteor/meteor#13057]
Summary:

I am eager to use Meteor 3.0 so I figured I would test the latest beta version by creating a VueJs app.

`meteor run` returns:

```
While loading plugin `vite` from package `jorgenvatle:vite-bundler`:
packages/modules-runtime.js:222:12: Cannot find module 'fibers'
```

Commands to Reproduce Error:

```

- npm install -g meteor@3.0.0-beta.6
- meteor create --vue MyApp --release 3.0-beta.6

```

Meteor Version:
```
npm list -g --depth=0
/home/vscode/.nvm/versions/node/v20.11.1/lib
├── corepack@0.23.0
├── meteor@3.0.0-beta.6
└── npm@10.2.4
```

Environment:

- Host OS: Ubuntu 22.04.4 LTS
- Container: Docker version 25.0.4, build 1a576c5 (Rootless mode)

Full Error Message:

The following error message is returned in the console and at http://localhost:3000/:

```
meteor run
[[[[[ ~/My/Project/Directory ]]]]]

=> Started proxy.                             
=> Started HMR server.                        
=> Errors prevented startup:                  
   
   While loading plugin `vite` from package `jorgenvatle:vite-bundler`:
   packages/modules-runtime.js:222:12: Cannot find module 'fibers'
   at makeMissingError (packages/modules-runtime.js:222:12)
   at Module.require (packages/modules-runtime.js:241:17)
   at require (packages/modules-runtime.js:258:21)
   at module (packages/promise.js:41:7)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/promise.js:149:15
   at packages/promise.js:156:3
```
Really looking forward to the 3.0 release. Keep up the great work!

**Comment by StorytellerCZ** [comment]
@Grubba27 isn't the `vue` skeleton Vue 2?

**Comment by Grubba27** [comment]
Since this [PR](https://github.com/meteor/meteor/pull/12302) in Meteor v2.9, Vue 3 is called by `--vue` command. 

Thinking about it, this was a breaking change.

**Comment by Grubba27** [comment]
From my tests, vue 3 actually works with Meteor v3!

After you create your app, you should run the following:

```sh
meteor remove jorgenvatle:vite-bundler  

meteor add jorgenvatle:vite-bundler@2.0.0-beta.8
```

Meteor, for some reason, gets lost while choosing dependencies while creating a beta app for the 3.x version.
<img width="1280" alt="Screenshot 2024-03-11 at 09 41 20" src="https://github.com/meteor/meteor/assets/70247653/4ceb48fa-281f-40c3-8373-cc0b5db1a610">

**Comment by firewater** [comment]
@Grubba27 @StorytellerCZ Thank you for the quick reply! Just letting you know that my app is now working thanks to the recommendation provided above. Hopefully this is an easy fix for the devs to implement in the upcoming official 3.0 release.

**Comment by Grubba27** [comment]
Yes! I think pinning this version should do the trick 

```sh
jorgenvatle:vite-bundler@2.0.0-beta.8
```

**Comment by StorytellerCZ** [comment]
Just tested this in Meteor 3.0.1:
```
storyteller@storyteller-X570-AORUS-PRO:~/Web/meteor/vueMeteor3$ meteor
[[[[[ ~/Web/meteor/vueMeteor3 ]]]]]           

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
I20240719-19:25:53.818(2)? ⚡   Starting Vite server...
W20240719-19:25:53.827(2)? (STDERR) ⚡  You are using an out of date version of `meteor-vite`.
W20240719-19:25:53.827(2)? (STDERR)    Please update it: $ meteor npm i meteor-vite@1.10.3
W20240719-19:25:53.827(2)? (STDERR) ⚡  You are using an out of date version of `meteor-vite`.
W20240719-19:25:53.827(2)? (STDERR)    Please update it: $ meteor npm i meteor-vite@1.10.3
=> Started your app.

=> App running at: http://localhost:3000/
I20240719-19:25:54.123(2)?   ➜  Local:   http://localhost:5173/
I20240719-19:25:54.124(2)?   ➜  Network: use --host to expose
I20240719-19:25:54.138(2)? ⚡   Meteor-Vite ready for connections!
I20240719-19:25:54.144(2)? ⚡   Meteor-Vite ready for connections!
```

A small issue with out of data vite, but the original problem has been solved. Closing this for now.
