### ISSUE TITLE
Meteor 3.0-beta.7 not working

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#13073]
```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint mongo-decimal@0.1.4-beta300.7 is not satisfied by mongo-decimal 0.1.3.
   Constraints on package "mongo-decimal":
   * mongo-decimal@0.1.4-beta300.7 <- mongo 2.0.0-beta300.7 <- local-test:montiapm:agent 3.0.0-beta.5
   * mongo-decimal@0.1.4-beta300.7 <- minimongo 2.0.0-beta300.7 <- allow-deny 2.0.0-beta300.7 <- mongo 2.0.0-beta300.7 <-
   local-test:montiapm:agent 3.0.0-beta.5
   * mongo-decimal@0.1.4-beta300.7 <- minimongo 2.0.0-beta300.7 <- local-test:montiapm:agent 3.0.0-beta.5

 ```
It looks like mongo-decimal wasn't released.

**Comment by renanccastro** [comment]
@denihs @Grubba27 fyi

**Comment by Grubba27** [comment]
Hello @renanccastro, thanks for reporting. This issue has been solved; I've published a new version of mongo-decimal, as you can see in the image below.

We have not announced the beta.7 yet.

We are still solving some issues that we found in our tests (currently, working in  our npm installer)

<details>

<summary>Image</summary>

<img width="774" alt="Screenshot 2024-03-25 at 09 42 33" src="https://github.com/meteor/meteor/assets/70247653/0a6b7c7f-0ca1-486f-b9af-87f3402a81f8">

</details>
