### ISSUE TITLE
[3.0] error on boot.js TypeError: next.runImage.call is not a function

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#13104]
Hello, I was trying to update our application to the latest RC and after updating I booted our application to get this error:

![Selection_017](https://github.com/meteor/meteor/assets/6644545/6edd5f70-056a-436d-8a55-4d6031fc3a17)

**Comment by jamauro** [comment]
Sounds like the same issue here: https://forums.meteor.com/t/meteor-3-0-rc-0-is-out/61515/2?u=jam

Have you already tried `meteor reset` or `rm -rf .meteor/bundler-cache`?

**Comment by gustawdaniel** [comment]
In my case `meteor reset` solved this problem.

**Comment by harryadel** [comment]
Yup, that fixed. Thank you guys!

**Comment by denihs** [comment]
Nice! We're going to add this to the next rc

**Comment by dallman2** [comment]
Thank you for adding this in the next RC. Some of us would rather not clear our local db when doing a meteor version upgrade :)

**Comment by denihs** [comment]
This should be fixed now in version `3.0-rc.1`
