### ISSUE TITLE
[Meteor 3]  SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#13114]
After updating our application to the latest RC it's no longer recognizing `import` or `export` statements. Of course it'd be hard to share parts of our application so I tried my best to replicate the error [here](https://github.com/harryadel/wework).

All you've to do is to run the application and you'd get an error like so:
![Selection_025](https://github.com/meteor/meteor/assets/6644545/976b1663-bc1d-42db-beee-c1d4d5df0d16)

**Comment by harryadel** [comment]
@denihs I've tried disabling plenty of the packages to narrow it down but it's unclear.

**Comment by nachocodoner** [comment]
I looked into this issue.

I compared it with a new Meteor 3 project and noticed that it is missing the explicit definition of `ecmascript@0.16.9-rc300.2`. I also upgraded to the recent RC.2 on that project.

![image](https://github.com/meteor/meteor/assets/2581993/fc9dfd2c-c3a0-422c-8366-8ae4bb1ccdcc)

**Comment by harryadel** [comment]
Sorry for the late reply, I'll give it a go again after applying your solution. Thank you for your efforts <3
