### ISSUE TITLE
[Meteor 3] EnvironmentVariable.withValue has different return value on client and server

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#13113]
With this code:
```js
let ev1 = new Meteor.EnvironmentVariable();

console.log(ev1.withValue(10, () => 5));
```

On the client it logs `5`, and on the server it logs a promise. It should be the same on both the server and client.

Once #13112 is fixed, it should be fairly simple to have `withValue` synchronously return the value from the function, so it is only async if the passed function is also async, and it would behave the same on the client and server.

**Comment by denihs** [comment]
This is now fixed!
