### ISSUE TITLE
[Meteor 3] Environment Variables resets value too early

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#13112]
With this code:
```
let ev1 = new Meteor.EnvironmentVariable();

async function runAsyncFunction() {
  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log('value2', ev1.get());
}

ev1.withValue({ name: 'test' }, () => {
  runAsyncFunction();
  console.log('value 1', ev1.get());
});
```

In Meteor 1 and 2, it logs:
```
value 1 { name: 'test' }
value2 { name: 'test' }
```

However, in Meteor 3 it logs:
```
value 1 { name: 'test' }
value2 undefined
```

Meteor 1 and 2 preserve the value until all child async contexts complete. Async Local Storage does the same, which Environment Variables uses in Meteor 3, so it should be possible to preserve this behavior in Meteor 3.

**Comment by nachocodoner** [comment]
[These tests](https://github.com/meteor/meteor/pull/13063/files#diff-b7edc13b0161fd0d8b0fa8587cfee1f55eb9c5b969c16abc092b644133f6c655R19-R64) demonstrate the current behaviors and expected support in Meteor 3.0.

In your example, code might need adjustment to ensure you properly await children asyncs to maintain the env variable context. For instance:

``` javascript
let ev1 = new Meteor.EnvironmentVariable();

async function runAsyncFunction() {
  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log('value2', ev1.get());
}

ev1.withValue({ name: 'test' }, () => {
  ➡️ await runAsyncFunction();
  console.log('value 1', ev1.get());
});
```

With this you get the proper response.

``` javascript
value 1 { name: 'test' }
value2 { name: 'test' }
```

While achieving this might be possible, given my limited familiarity with this code or Async Local Storage behavior, further exploration is needed.

Thank you for bringing it to our attention.

cc @denihs

**Comment by zodern** [comment]
Preserving the env vars in async child contexts was an important part of the implementation in Meteor 1/2. Meteor wrapped most callback api's with Meteor.bindEnvironment, and had code in the `promise` package to preserve the env var values in async functions and promises. Since ALS works the same, it seems this behavior is generally expected.

You should be able to simply remove [these lines](https://github.com/meteor/meteor/blob/0a15d1a5b81f3b5970735a61e3f2e26090902c6a/packages/meteor/dynamics_nodejs.js#L70-L75).  ASL makes the store available to all child resources, so if you don't mutate it it will work the same as in Meteor 1/2. There's no need to unset `UPPER_CALL_DYNAMICS_KEY_NAME` - you're creating a new store object each time, so outside code isn't able to read it (earlier implementations didn't, which is probably why the code was added).

When working on using ALS in `montiapm:agent`, I found it helpful in my understanding to read Node's source code for ALS.

**Comment by leonardoventurini** [comment]
This is fixed.
