### ISSUE TITLE
Method only runs once on server, simulation on client does run - 3.0-rc.0

### ISSUE THREAD

**Issue by poetsmeniet** [meteor/meteor#13125]
OS: Debian 12
Expected behaviour: calling the method should update the collection every time it is called by the client.
Actual behaviour: the method is only run once on the server.

The server method:
```
  'parameters.upsert': function(orgId, parametersArr) {
  console.log('upsert params (orgId: ', orgId, '): ', parametersArr);
   
  Parameters.upsertAsync({orgId: orgId}, {
    createdAt: new Date(),
    orgId: orgId,
    parametersArr: parametersArr
  })
 .then(result => {
    console.log('Upsert operation successful:', result);
    return result;
  })
 .catch(error => {
    console.error('Error during upsert operation:', error);
    throw error; 
  });
}
```
On the client:
async function test(){
    await Meteor.call('parameters.upsert', 1, paramArr, (e, res) =>{
      if(res) handleClose(1);
      console.log('paramters.upsert came back: e: ', e, ' and res: ', res);
    });
}

**Comment by bmartin1134** [comment]
im not super good but shouldn't the 'function' be 'async function'?

Otherwise what happens when:

  'parameters.upsert': async function(orgId, parametersArr) {
  console.log('upsert params (orgId: ', orgId, '): ', parametersArr);
   try {
   const result =  await Parameters.upsertAsync({orgId: orgId}, {
    createdAt: new Date(),
    orgId: orgId,
    parametersArr: parametersArr
  }) 
    console.log('Upsert operation successful:', result);
    return result;
  } catch {
    console.error('Error during upsert operation:', error);
    throw error; 
  };
return this.ready()
}

**Comment by jamauro** [comment]
What happens when you use `Meteor.callAsync` instead?

**Comment by poetsmeniet** [comment]
> What happens when you use `Meteor.callAsync` instead?

Yes, that does work. So simple :D
