### ISSUE TITLE
Missing Update for Meteor 3.0

### ISSUE THREAD

**Issue by nesbtesh** [meteor/meteor#13148]
This line is missing update for Meteor 3.0

https://github.com/meteor/meteor/blob/c38e3c7f3834cb20e8f4cc0473a9011091301778/packages/accounts-base/accounts_server.js#L455C5-L455C94

**Comment by denihs** [comment]
I'm not sure from which branch this commit is, but in the current `release-3.0` branch, this [already uses](https://github.com/meteor/meteor/blob/4715e563a774ad7abb1c5d932fa4b08b98656384/packages/accounts-base/accounts_server.js#L458) `findOneAsync`.
