### ISSUE TITLE
[Meteor: 3.0.0-rc1] - github-oauth Using `findOne` instead of `findOneAsync`

### ISSUE THREAD

**Issue by brunoeduardodev** [meteor/meteor#13152]
# Describing the Issue

On the current latest release, `Meteor: 3.0.0-rc1` the `github-oauth` package is throwing a `W20240521-00:24:30.052(-3) (oauth_server.js:412) Error in OAuth Server: findOne +  is not available on the server. Please use findOneAsync() instead.`

![image](https://github.com/meteor/meteor/assets/50559336/df2cdefd-29fc-44e0-a6c2-9dfd12bc6f7e)

### OS
MacOS, M1 Pro

### Expected Behavior
Github sign in to complete successfully.

### Actual Behavior
Github sign in is not completed due to the unexpected error on the server.

# How to reproduce

### **NOTE** 
To reproduce the issue when cloning the github repository, you need to fill the `settings.json` file with the "clientId" and "secret" with valid values of a github oauth application (with callback_url set to `http://localhost:300`)

## Reproducing Step by Step
1. Create a new meteor project using Meteor 3.0.0-rc1
```bash
meteor create meteor-rc-300.1-github-oauth-error --release 3.0-rc.1
```
2. Add `accounts-github` package
```bash
meteor add accounts-github
```

It should install the following packages and versions:

<img width="421" alt="image" src="https://github.com/meteor/meteor/assets/50559336/982b0c0a-e268-4b6f-96bf-b3b790725e42">

3. On `App.jsx` file, add a simple button that invokes `Meteor.loginWithGithub()`

```tsx
import React from 'react';
import { Hello } from './Hello.jsx';
import { Info } from './Info.jsx';
import { Meteor } from 'meteor/meteor';

export const App = () => (
  <div>
    <h1>Welcome to Meteor!</h1>
    <button onClick={() => Meteor.loginWithGithub()}>Login with GitHub</button>
    <Hello/>
    <Info/>
  </div>
);

```

4. Create a `settings.json` file on the root of the project containing the `clientId` and `secret` of a github oauth application with `callback_url` set to `http://localhost:3000`

```json
{
  "packages": {
    "service-configuration": {
      "github": {
        "loginStyle": "popup",
        "clientId": "<ADD CLIENT ID>",
        "secret": "<ADD SECRET>"
      }
    }
  }
}
```

5. Run Meteor passing the JSON file as a flag

```bash
meteor -s settings.json
```

6. Now, open `http://localhost:3000` and click on the "Login with Github" button

7. See the error on terminal

<img width="1130" alt="image" src="https://github.com/meteor/meteor/assets/50559336/ec5c933c-0ded-4134-8b79-9c8c5379519b">

# Additional Notes:

While debugging this issue, I realized there was [a commit](https://github.com/meteor/meteor/commit/d397f770cf6f3fc54d68224010b8a4503c13c81b) on the `release-3.0` branch that updated the implementation of the github oauth server from `findOne` to `findOneAsync`.

But, this commit also updated the implementation to use `OAuth._fetch` instead of `fetch` for making http requests, and the `OAuth._fetch` has a different parameters signature.

On the `OAuth._fetch` method, it's expected to be called with three parameters, `url, method, options`
Right now, on the `release-3.0` branch, the `OAuth._fetch` is being called with only two parameters, where the second parameter is a object, rather than the method string, and this is causing the following error:

```
W20240521-00:59:02.084(-3) (oauth_server.js:414) Error in OAuth Server: Failed to complete OAuth handshake with Github. method.toUpperCase is not a function
```

<img width="853" alt="image" src="https://github.com/meteor/meteor/assets/50559336/2403b87c-2c8e-433d-b267-49954fb2e3a0">

Fixing this problem is very simple, just updating the parameters being passed to `OAuth._fetch`.

I've created a simple PR fixing this problem: #13153

**Comment by StorytellerCZ** [comment]
I believe this was fixed in rc.2

**Comment by brunoeduardodev** [comment]
The "findOne" was moved to "findOneAsync" on rc.2 correctly
but the problem I stated on the "additional notes", which I fixed on the #13153 PR is still there though

**Comment by brunoeduardodev** [comment]
right now, on the rc.2 the error while trying to invoke a `Meteor.loginWithGoogle` or `Meteor.loginWithGithub` went from 
```
W20240521-00:24:30.052(-3) (oauth_server.js:412) Error in OAuth Server: findOne +  is not available on the server. Please use findOneAsync() instead.
```

to:

```
W20240521-00:59:02.084(-3) (oauth_server.js:414) Error in OAuth Server: Failed to complete OAuth handshake with Github. method.toUpperCase is not a function
```

**Comment by brunoeduardodev** [comment]
I can open another issue since this is essentially a different issue now

**Comment by brunoeduardodev** [comment]
exactly, this PR #13153 fixes it

**Comment by nachocodoner** [comment]
Thank you a lot with the fix, now the _fetch works as expected. My fault on adapt it to use the standard mechanism.

**Comment by brunoeduardodev** [comment]
> Thank you a lot for the fix, now the _fetch works as expected. My fault on adapt it to use the standard mechanism.
> 
> More details on why this happened: [#13153 (review)](https://github.com/meteor/meteor/pull/13153#pullrequestreview-2070953575)

yeah I got it, pretty hard to reproduce it ahead of time without type checking lol
