### ISSUE TITLE
`Unexpected token 'const'` METEOR@3.0-rc.2

### ISSUE THREAD

**Issue by chneau** [meteor/meteor#13167]
```zsh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
$ uname -a                         59.8ms
Linux ncce 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
$ meteor --version                 19.9ms
Meteor 3.0-rc.2                               
$ meteor node --version            3.052s
v20.12.2
$  
```
Reproduction steps:
- start project https://github.com/chneau/meteor-template
- open browser
- open developer console and see errors `Unexpected token 'const'`

Has:
- White page, error on console

Expected
- Some Bootstrap webpage

Oddities:
- using bun for the packages but tried with npm (remove node_modules, `npm i`) still same issue

**Comment by chneau** [comment]
Ok it's now working, I tried to rebuild the whole thing from a fresh `meteor create --typescript --release=3.0-rc.2 .` and the major diff that made it fail before I think is because of:
```diff
- react-meteor-data@2.0.1
+ react-meteor-data@3.0.0-beta300.1
```

**Comment by chneau** [comment]
as a note, updating from 2.16 to 3.0-rc.2 failed to update this package apparently.

**Comment by nachocodoner** [comment]
We recently released an update for `react-meteor-data`, aligning with the new RC releases, `react-meteor-data@3.0.0-rc.0`.

When transitioning from Meteor 2.x to Meteor 3.x, it's essential to upgrade to at least the minimum compatible version for 3.x, as you've done.
