### ISSUE TITLE
Meteor 3 - Meteor.user() behavior on server vs client

### ISSUE THREAD

**Issue by alisnic** [meteor/meteor#13172]
Currently, it returns a promise on server and a user on client. This behavior is very confusing and impossible to catch via TypeScript.

Instead, it should throw an error (at least in development), so that the developers won't wrongly assume that Meteor.user() is isomorphic.

**Comment by denihs** [comment]
In the [migration guide](https://v3-migration-docs.meteor.com/breaking-changes/#meteor-userasync), we recommend that you use `Meteor.userAsync()` to keep to isomorphism. Still, maybe we could add some warnings for (or even deprecate) the `Meteor.user()` in the server. I'll take note of this. Thank you.

**Comment by lemontron** [comment]
wow thanks! this helps the documentation clarity a lot. consistency is key!
