### ISSUE TITLE
[Meteor 3] Meteor.applyAsync behaves differently than Meteor.callAsync

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#13208]
Version: `Meteor 3.0-rc.4`

When using `Meteor.applyAsync`, it's not possible to catch errors on the serverPromise in the same way you can with `Meteor.callAsync`. I thought `Meteor.applyAsync` would behave the same way as `Meteor.callAsync`.

Repro:

1. Set up a Meteor method and error on the server
```js
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

Meteor.methods({
  async something() {
    if (Meteor.isServer) {
      await wait(1000)
      throw new Meteor.Error('no')
    }
    const title = 'hi';

    const linkId = await LinksCollection.insertAsync({ title });
    console.log('linkId', linkId)
    return linkId;
  }
})
```

2. Use Meteor.callAsync on the client. It behaves as expected.
```js
const { stubPromise, serverPromise } = Meteor.callAsync('something')
const stub = await stubPromise;
console.log('stub', stub);
const serverResult = await serverPromise.catch(error => {
   // handle error, rollback changes as needed
   console.error('server error', error)
});
console.log('serverResult', serverResult);
```
<img width="1187" alt="Screenshot 2024-06-27 at 10 10 19 AM" src="https://github.com/meteor/meteor/assets/1749828/e769f453-5eff-49ec-8d41-b4b87eb7a7a0">

3. Use Meteor.applyAsync on the client. The server error isn't caught and the serverResult is returned immediately with the stub without waiting 1000 ms.
```js
const { stubPromise, serverPromise } = Meteor.applyAsync('something', [], {returnStubValue: true, throwStubExceptions: true})
const stub = await stubPromise;
console.log('stub', stub);
const serverResult = await serverPromise.catch(error => {
   // handle error, rollback changes as needed
   console.error('server error', error)
});
console.log('serverResult', serverResult);
```
<img width="1362" alt="Screenshot 2024-06-27 at 10 11 23 AM" src="https://github.com/meteor/meteor/assets/1749828/a7dc9ccb-183d-4053-8964-9416fa47bd1a">

**Comment by jamauro** [comment]
Hmm, I hadn't seen the `returnServerResultPromise` flag until I looked at the source code. From some initial experimentation, it seems I can get `Meteor.applyAsync` to behave like `Meteor.callAsync` when I set `returnServerResultPromise : true`. Should the docs be updated? https://v3-docs.meteor.com/api/meteor.html#Meteor-applyAsync

**Comment by denihs** [comment]
It makes sense, I'm going to take note of this so we can improve this part of the doc.

**Comment by jamauro** [comment]
Yeah I think so
