### ISSUE TITLE
Helper "loggingIn" modernization?

### ISSUE THREAD

**Issue by carlosalvidrez** [meteor/meteor#13200]
I suspect the Blaze helper "loggingIn" (accounts base package I think), is not behaving in v3 as it used to in v2.16... I see my login pane flashing for a split second now for users already authenticated and simply refreshing the site.

Perhaps the package needs some sort of "async" update?

**Comment by StorytellerCZ** [comment]
Strange that should still behave same otherwise the tests would fail. In essence it is a reactive variable, so if anything is wrong here it would be in the functions that set it.

**Comment by StorytellerCZ** [comment]
Could be related to #13212

**Comment by carlosalvidrez** [comment]
Not sure but I don't have an issue now.
Changed so many things that I don't even know what this was.
