### ISSUE TITLE
[3.0-rc.4] - "Failed to fetch examples"

### ISSUE THREAD

**Issue by kylemclaren** [meteor/meteor#13215]
Running on Apple M2 Pro Mac OS Sonoma 14.5, I tried to install with `npx` and also with the install script — both yield the same result.

```console
➜ meteor --version
Meteor 3.0-rc.4
```

```console
➜ meteor create --list
Available examples:
Failed to fetch examples:
Using cached examples.json
  vue: https://github.com/meteor/skel-vue
  react: https://github.com/meteor/skel-react
  full: https://github.com/meteor/skel-full
  bare: https://github.com/meteor/skel-bare
  blaze: https://github.com/meteor/skel-blaze
  chakra-ui: https://github.com/meteor/skel-chakra-ui
  apollo: https://github.com/meteor/skel-apollo
  minimal: https://github.com/meteor/skel-minimal
  solid: https://github.com/meteor/skel-solid
  svelte: https://github.com/meteor/skel-svelte
  tailwind: https://github.com/meteor/skel-tailwind
  typescript: https://github.com/meteor/skel-typescript

To create an example, simply 'meteor create <app-name> --example <name>'
```

**Comment by denihs** [comment]
At least on Ubuntu is working:

![image](https://github.com/meteor/meteor/assets/29639852/11078b1e-3df3-4803-a35f-e6135e3640d9)

I don't have an M2 to test it, though. @nachocodoner @leonardoventurini, are you guys able to reproduce this?

**Comment by kylemclaren** [comment]
@denihs Thanks, anything I can do to debug on my side? I don't see any verbose flags for that command

**Comment by nachocodoner** [comment]
Not on my M1.

![image](https://github.com/meteor/meteor/assets/2581993/aa0f0c98-0ac2-417c-b727-4a93d4df61f5)

[This is the part of the code](https://github.com/meteor/meteor/blob/release-3.0/tools/cli/commands.js#L797-L802) that seems to be errored. Specifically the [`getExamplesJSON` implementation](https://github.com/meteor/meteor/blob/release-3.0/tools/cli/commands.js#L588-L598). Could you try to mimic the http get request on your environment against `https://cdn.meteor.com/static/meteor.json`? does it work for you?

Anyway, you can always debug this part of the code running Meteor from a checkout. That is clone the repository, check out `release-3.0` branch and use the path of `meteor` binary within your cloned version to run the `cloned-repo/meteor create --list` command. Put any logs to understand the error thrown.

**Comment by kylemclaren** [comment]
Thanks for the help everyone—looks like this was related to my local Node version (22). Switched to 20 and all good:
```console
➜ node -v
v20.15.1

➜ meteor create --list --release 3.0-rc.4
Available examples:
  vue-2: https://github.com/meteor/skel-vue-2
  vue: https://github.com/meteor/skel-vue
  react: https://github.com/meteor/skel-react
  full: https://github.com/meteor/skel-full
  bare: https://github.com/meteor/skel-bare
  blaze: https://github.com/meteor/skel-blaze
  chakra-ui: https://github.com/meteor/skel-chakra-ui
  apollo: https://github.com/meteor/skel-apollo
  minimal: https://github.com/meteor/skel-minimal
  solid: https://github.com/meteor/skel-solid
  svelte: https://github.com/meteor/skel-svelte
  tailwind: https://github.com/meteor/skel-tailwind
  typescript: https://github.com/meteor/skel-typescript

To create an example, simply 'meteor create <app-name> --example <name>'
```
