### ISSUE TITLE
0.6.5 - ReferenceError: Meteor is not defined - app/lib/file.js

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#1322]
This may be by design, as part of the new "Namespacing" initiative... but after the update to `0.6.5` my app is crashing with:

```
W20130816-03:23:16.848(-4)? (STDERR) /Users/admin/.meteorite/meteors/meteor/meteor/d17795971cf2d55532bf7b9d00d0c925dec22014/dev_bundle/lib/node_modules/fibers/future.js:173
W20130816-03:23:16.848(-4)? (STDERR)                        throw(ex);
W20130816-03:23:16.848(-4)? (STDERR)                              ^
W20130816-03:23:16.850(-4)? (STDERR) ReferenceError: Meteor is not defined
W20130816-03:23:16.850(-4)? (STDERR)     at app/lib/meteor_helpers.js:10:1
W20130816-03:23:16.851(-4)? (STDERR)     at app/lib/meteor_helpers.js:107:3
W20130816-03:23:16.851(-4)? (STDERR)     at mains (/Development/Meteor/.meteor/local/build/programs/server/boot.js:153:10)
W20130816-03:23:16.851(-4)? (STDERR)     at Array.forEach (native)
W20130816-03:23:16.851(-4)? (STDERR)     at Function._.each._.forEach (/Users/admin/.meteorite/meteors/meteor/meteor/d17795971cf2d55532bf7b9d00d0c925dec22014/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20130816-03:23:16.852(-4)? (STDERR)     at /Development/Meteor/.meteor/local/build/programs/server/boot.js:80:5
```

The file in question `app/lib/meteor_helpers.js` on line `10` is simply defining a new method/function on the Meteor object...  

I was using it as a global object to join on general shortcuts/helpers.  

Perhaps this practice is frowned upon, and I can deal with that answer, but I'm amazed that the `Meteor` object isn't available here...

Instead, perhaps something "else" is not working right?

**Comment by titank90** [comment]
After upgrading to the latest meteor release 1.2.0.1 my previously running application crashed:
W20150924-00:46:56.066(2)? (STDERR)           
W20150924-00:46:56.067(2)? (STDERR) /home/bruno/.meteor/packages/meteor-tool/.1.1.8.jt1sde++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150924-00:46:56.067(2)? (STDERR) 						throw(ex);
W20150924-00:46:56.068(2)? (STDERR) 						      ^
W20150924-00:46:56.254(2)? (STDERR) Error: A method named '/Lists/insert' is already defined
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

Adding standard-app-packages in .meteor/packages followed by running meteor update solved my problem.

Thanks !
