### ISSUE TITLE
AppCache over 5mb warning, but I don't know where the size is coming from

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#1323]
After updating to `0.6.5` I'm now getting the following warning on the server console:

```
I20130816-11:22:33.711(-4)? ** You are using the appcache package but the total size of the
I20130816-11:22:33.711(-4)? ** cached resources is 5.0MB.
I20130816-11:22:33.712(-4)? **
I20130816-11:22:33.712(-4)? ** This is over the recommended maximum of 5 MB and may break your
I20130816-11:22:33.712(-4)? ** app in some browsers! See http://docs.meteor.com/#appcache
I20130816-11:22:33.712(-4)? ** for more information and fixes.
```

Firstly, I love informative error messages and warning, which tell you how to fix the problem... kudos.  

Unfortunately, it's not enough information.

```
/D/C/Meteor ❯❯❯ du -sh public
196K    public
/D/C/Meteor ❯❯❯ du -sh client
1.6M    client
/D/C/Meteor ❯❯❯ du -sh models
264K    models
/D/C/Meteor ❯❯❯ du -sh lib
192K    lib
```

= ~ 2.23M

I'm not able to find the 5MB of data, I suspect it's in a package (or as a result of all of my packages + my clientside code + being compiled into JS).

I see that there are some recommendations about how to exclude certain "public" assets from inclusion in AppCache, but nothing about client resources or packages (which makes sense because client resources are aggregated and minified on production.

after digging some more I was able to find a bunch of data in 

```
/D/C/Meteor ❯❯❯ du -sh .meteor/local/build/programs/client/*
644K    .meteor/local/build/programs/client/app
 24K    .meteor/local/build/programs/client/app.html
6.4M    .meteor/local/build/programs/client/packages
 60K    .meteor/local/build/programs/client/program.json
```

When I list out the sizes of all the packages, several are quite large:

```
/D/C/Meteor ❯❯❯ du -sh .meteor/local/build/programs/client/packages/*
...
 12K    .meteor/local/build/programs/client/packages/accounts-ui
164K    .meteor/local/build/programs/client/packages/accounts-ui-unstyled.js
 60K    .meteor/local/build/programs/client/packages/accounts-ui-unstyled.js.map
...
 12K    .meteor/local/build/programs/client/packages/jquery-cookie.js
4.0K    .meteor/local/build/programs/client/packages/jquery-cookie.js.map
328K    .meteor/local/build/programs/client/packages/jquery-history.js
 92K    .meteor/local/build/programs/client/packages/jquery-history.js.map
1.1M    .meteor/local/build/programs/client/packages/jquery.js
360K    .meteor/local/build/programs/client/packages/jquery.js.map
....
144K    .meteor/local/build/programs/client/packages/underscore.js
 52K    .meteor/local/build/programs/client/packages/underscore.js.map
....
```

I assume that these are in there uncompressed/un-minified state, perhaps with a lot of "cruft" alongside the asset.

So - I've got a wishlist of additional pieces of functionality related to AppCache and its warnings.
1. the ability to display the sizes and paths of all files being used to calculate the > 5M, for reference, so that you know what to "trim"
2. to see all the packages minified or something, so that they don't blow up AppCache
3. a better list of all "running" packages, and which ones are core, vs. 3rd party (with sizes?)
4. the ability to exclude "client" code, perhaps by folder/path from AppCache (not sure if that's possible).  (This is related to my deeper desire to have segmentable client side codebases... so that if you login as an admin, you get all the Admin client HTML/JS, but until you are an admin you don't.)

**Comment by glasser** [comment]
Also, the limit might be outdated now: #3738

**Comment by serkandurusoy** [comment]
I do confirm this behaviour and I believe a documentation update is in order.

If in fact what appcache sets to store locally is what actually gets delivered during production, than in my case I was warned about the app being 6MB (which is since jquery, ddp, blaze and a few packages actually exceed 5MB without even the application code/assets) but when I deployed to production, the actual data was around 800KB.

I guess, any barebones meteor app will be close to, if not already over, the 5MB warning threshold. So the warning becomes kind of pointless and scares away unsuspecting developers.

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers.  Realistically, documenting this probably won't be worthwhile.

Service Workers are supposed to be the replacement and is being tracked in #5982.
