### ISSUE TITLE
[Meteor 3] Regresssion with ddp changed message being sent without fields

### ISSUE THREAD

**Issue by ToyboxZach** [meteor/meteor#13232]
I have a fairly complex project and am running into my automated tests with some weird ddp messages.

I get this error:
```
collection.js:269 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.update (collection.js:269:31)
    at store.<computed> [as update] (livedata_connection.js:305:38)
    at Connection._performWritesClient (livedata_connection.js:1435:19)
    at Connection._flushBufferedWritesClient (livedata_connection.js:1360:10)
    at Connection._flushBufferedWrites (livedata_connection.js:1365:14)
    at Connection._livedata_data (livedata_connection.js:1308:18)
    at async Connection.onMessage (livedata_connection.js:1908:7)
```

```
// packages/mongo/collection
 } else if (msg.msg === 'changed') {
          if (!doc) throw new Error('Expected to find a document to change');
          const keys = Object.keys(msg.fields); // It crashes here
```

And when I dive into I see that the changed message is coming in with no fields in it which cause Object.keys(msg.fields) to throw an error.

Sadly this error is not consistent for me so I haven't been able to narrow down the exact cause, and I don't quite know what portion of the code could be an issue, these are tests that have been running on various versions of Meteor 2 and Meteor 3 rc and it only started occurring when I tried to make the final jump to version 3

My general flow for a test is to load all the data with a meteor method, run the tests and then remove all the data and generate it again before the next test runs, so a lot of messages are probably flowing at that point.

This crash ends up leaving me without some data I was depending on so it causes my tests to fail

If anyone has an idea of what to dive deeper into I can try isolating the core issue here, but it is definitely a recent regression since rc4

Oh and this is happening on my user collection

**Comment by nachocodoner** [comment]
> If anyone has an idea of what to dive deeper into I can try isolating the core issue here, but it is definitely a recent regression since rc4

So, do you say that before rc.4 you didn't get this issue ever? Or did it still happen sometimes?

Could you re-verify this statement so that you test in previous versions of rc.4? If this is affirmative then we can get an idea of what likely introduced this flakiness within rc.4 changes, and deep investigating it.
