### ISSUE TITLE
Meteor 3 add-platform android breaks meteor installation on windows 11

### ISSUE THREAD

**Issue by ibassoftware** [meteor/meteor#13250]
I’ve encountered a problem when attempting to add the Android platform to a Meteor project on a Windows 11 system. This is a fresh Meteor 3.0.1 installation by the way. Here are the details of the issue:

When running the command meteor add-platform android, the following error occurs:

`
Error: Error: couldn't install npm package cordova-common@4.0.2: Command failed: C:\Windows\system32\cmd.exe /c C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install cordova-common@4.0.2
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\bin\npm-cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1
`

After this error, attempting to run any meteor command results in the following error:

`
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '@meteorjs/reify/lib/runtime'
Require stack:
- C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\static-assets\server\runtime.js
- C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\tool-env\install-reify.js
- C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\tool-env\install-babel.js
- C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at enable (C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\static-assets\server\runtime.js:34:5)
    at Object.<anonymous> (C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\tool-env\install-reify.js:12:48)
    at Object.<anonymous> (C:\Users\rrd\AppData\Local\.meteor\packages\meteor-tool\3.0.1\mt-os.windows.x86_64\tools\tool-env\install-reify.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\rrd\\AppData\\Local\\.meteor\\packages\\meteor-tool\\3.0.1\\mt-os.windows.x86_64\\tools\\static-assets\\server\\runtime.js',
    'C:\\Users\\rrd\\AppData\\Local\\.meteor\\packages\\meteor-tool\\3.0.1\\mt-os.windows.x86_64\\tools\\tool-env\\install-reify.js',
    'C:\\Users\\rrd\\AppData\\Local\\.meteor\\packages\\meteor-tool\\3.0.1\\mt-os.windows.x86_64\\tools\\tool-env\\install-babel.js',
    'C:\\Users\\rrd\\AppData\\Local\\.meteor\\packages\\meteor-tool\\3.0.1\\mt-os.windows.x86_64\\tools\\index.js'
  ]
}

Node.js v20.15.1
`

Please let me know if I can clarify further.

**Comment by nachocodoner** [comment]
We have taken a note on this task as we were able to reproduce it. We will fix it for one of the next patches.

Thank you

**Comment by Arziel1992** [comment]
Is there a temporary workaround for this?
(I'm dealing with the same issue as well)

**Comment by nachocodoner** [comment]
I am currently working on a fix for the next release, 3.0.4. https://github.com/meteor/meteor/pull/13388

This PR will involve a complete review of Cordova on Windows, as additional issues have emerged. WSL functions well, but raw Windows has introduced problems in newer versions.

> Is there a temporary workaround for this?

To resolve this issue and continue working on your Meteor project after `meteor add-platform android`, please reinstall Meteor (`npx meteor uninstall` then `npx meteor`).

Note that you cannot work with Cordova projects using raw Windows until the next version is released. It should work well on Meteor 2 though, but ensure you install the installer with your Meteor 2 version (e.g `npx meteor@2.16.0`), not 3.0 at all.
If needed in Meteor 3, please use WSL or a UNIX-like system until next release. I will provide updates here once we address these issues.

**Comment by Leekao** [comment]
> > Is there a temporary workaround for this?
> 
> To resolve this issue and continue working on your Meteor project after `meteor add-platform android`, please reinstall Meteor (`npx meteor uninstall` then `npx meteor`).
> 
Workaround does not work for me, `npm meteor uninstall` does not work because of the error, manually deleting `.meteor` from my `appData/local` and `npx meteor` did work.

**Comment by nachocodoner** [comment]
There has been a full review on Meteor Cordova when working in Windows environments. The Meteor Cordova has been fully reviewed for Windows environments. The issue mentioned, along with others found during testing, has been resolved. [Documentation for Cordova on Windows](https://docs.meteor.com/about/cordova.html) has also been updated.

Release 3.0.4 is now available. Run `meteor update --release 3.0.4` to start using it. Please consider reinstalling Meteor completely, as these changes involve dev_bundle modifications that may only be effective on clean installations. (`npx meteor@latest uninstall` and then `npx meteor`).

**Related PRs**
https://github.com/meteor/meteor/pull/13388
https://github.com/meteor/meteor/pull/13396
