### ISSUE TITLE
Set ambiguousErrorMessages consistently across environments

### ISSUE THREAD

**Issue by alisnic** [meteor/meteor#13263]
See https://github.com/meteor/meteor/pull/12996

Whenever developers test and implement error handling locally, they expect that code will behave in the same way on production. Otherwise, a lot of time is wasted trying to understand different behaviour and failing to reproduce it locally.

cc @StorytellerCZ

**Comment by StorytellerCZ** [comment]
Should be super easy PR and a good start for a new person. In essence it is just removing the development check when no defaults are provided.

**Comment by vuongdovu** [comment]
Hey I would love to contribute to meteor. It's my first time contributing to an open source project and this seems like something I can do. @StorytellerCZ could you assign this issue to me please?
