### ISSUE TITLE
Minor typo on new v3 docs

### ISSUE THREAD

**Issue by camstuart** [meteor/meteor#13283]
Hello and congratulation on the v3 release!
I noticed a small typo on: https://v3-docs.meteor.com/

<img width="271" alt="image" src="https://github.com/user-attachments/assets/996099b1-0859-4da1-9c36-de5c3121b8b5">

"Never **rebuild** an authentication system again"

**Comment by LeoSantich** [comment]
I would love to contribute to meteor and fix this typo if possible.  Thank you for your consideration.
