### ISSUE TITLE
Meteor.userId() still returns the id on client when logging out and subscriptions restart

### ISSUE THREAD

**Issue by timhaines** [meteor/meteor#1331]
I've got a publish method that throws an error if the user isn't signed in.

If the user happens to be using the app, then signs out while subscribed to this, the subscription gets restarted as expected, and the publisher throws the 'Not signed in error'

However, the error handler for the subscription, when receiving the error from the publisher, seems to think the user is still signed in.  i.e. Meteor.userId() returns the user's ID.  At this time, I'd expect Meteor.userId() to return null, recognizing the user has signed out.  Or if that's not possible, a Meteor.loggingOut() method to show it's in process.

I can provide a simple reproduction if this isn't obvious.

**Comment by hwillson** [comment]
I've created PR #8271 to help address this issue (yes, I know, it's been a while ... but better late than never, right? 🙂 ). Thanks!

**Comment by hwillson** [comment]
PR #8271 has been merged, so `Meteor.loggingOut` functionality is coming soon - thanks all!
