### ISSUE TITLE
Fetching 2.8 tarball for linux.x86_64 returns 403

### ISSUE THREAD

**Issue by Matija8** [meteor/meteor#13310]
The url
https://static.meteor.com/packages-bootstrap/2.8/meteor-bootstrap-os.linux.x86_64.tar.gz
returns 403.

The url is needed for
`curl -k https://install.meteor.com/\?release\=2.8`
to work properly

**Comment by StorytellerCZ** [comment]
For Meteor v2.8 it should be `2.8.0`, there has been a departure from convention for that version, so you need to use the full length of the version.
