### ISSUE TITLE
Update is not available on the server

### ISSUE THREAD

**Issue by Uryon22** [meteor/meteor#13327]
Following the tutorial https://react-tutorial.meteor.com/simple-todos/08-adding-login-with-github, when i add the configuration part, the meteor server crash like this :

![meteor](https://github.com/user-attachments/assets/31c527e5-0268-48fc-af62-6a41c0d11374)

To Reproduce

Follow the [meteor tutorial](https://react-tutorial.meteor.com/simple-todos/08-adding-login-with-github)
Add your Github credentials in the ServiceConfiguration
Expected behavior

The meteor server should not crash

Versions (please complete the following information):

Meteor version: METEOR@3.0.2
Browser: Chrome
Version: Version 128.0.6613.84
It might be an issue depending on a dependance update ?

**Comment by StorytellerCZ** [comment]
I think this line:
```js
ServiceConfiguration.configurations.upsert(
```
should be:
```js
ServiceConfiguration.configurations.upsertAsync(
```

**Comment by fredmaiaarantes** [comment]
[This tutorial](https://react-tutorial.meteor.com/) is for Meteor v2, so we should clarify that at the start. You can find the tutorial for v3 [here](https://docs.meteor.com/tutorials/react/).

**Comment by Uryon22** [comment]
Oh, sorry for this, thanks for your help.
