### ISSUE TITLE
link directs to 404 error in meteor update warning 

### ISSUE THREAD

**Issue by guncebektas** [meteor/meteor#13321]
The link in the update warning which appears in CLI returns 404.

`Meteor 3.0.2 is available. Check the changelog https://docs.meteor.com/changelog.html and update this project with 'meteor update'.`

The version of Meteor showing the problem: 
2.16

The expected behavior:
It should open https://v3-docs.meteor.com/history.html

The actual behavior.
https://docs.meteor.com/changelog.html gives 404.

**Comment by mvorot** [comment]
Fixed. Please see pull request: https://github.com/meteor/meteor/pull/13322
