### ISSUE TITLE
DOCS: The installation link in all framework tutorials in Readme leads to a 404

### ISSUE THREAD

**Issue by aneesh98** [meteor/meteor#13334]
### The issue
The meteor tutorial documentations present in the Readme section of the repository have a wrong installation link that leads to a 404

### Steps To Reproduce
- Go to any one of the framework/library tutorial of either React, Blaze, Vue, Svelte in the "Getting Started" section of the documentation
![image](https://github.com/user-attachments/assets/b5a4346b-8380-4fcd-b1e7-69aaa17dd98b)

- Click on "Creating the App" Section of the tutorial from the side bar.
![image](https://github.com/user-attachments/assets/cf4902a0-8996-4292-a046-c65d5333f6a7)

- The very first part of the tutorial is about installing meteor with a installation link present. 
![image](https://github.com/user-attachments/assets/de7a11d3-7983-42fd-93df-ee82940b8149)

- Clicking on that link produces a 404
![image](https://github.com/user-attachments/assets/3e98ad35-3436-420c-ac0b-6da5e798a283)

The correct installation link is https://docs.meteor.com/about/install.html where as the one to which we are redirected is https://docs.meteor.com/install.html

Also in the Readme section for React tutorial, the link is pointing to a legacy react tutorial -> https://react-tutorial.meteor.com/simple-todos/01-creating-app. Should it be changed to point to the latest version?
https://docs.meteor.com/tutorials/react/

If it is indeed an issue, I would like to work on it by fixing the docs. 

Thanks

**Comment by aneesh98** [comment]
Hi @StorytellerCZ 
Will it be fine if I fix this?

**Comment by denihs** [comment]
Hi @aneesh98, Yes, it's an issue. If you want, you can go ahead and open a PR for this. We'd appreciate that very much!

**Comment by aneesh98** [comment]
Thanks, will work on this.

**Comment by denihs** [comment]
Nice job with the PRs! They are now all merged and deployed.
