### ISSUE TITLE
Documentation: Email.send

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#13340]
The "undefined" seems to be out of place. The table/grid for ```options``` could be squeezed a bit to match the maximum width of the central column so that scrolling horizontally won't be necessary.

Email.send and Email.sendAsync seem to be a copy of one another.

![Screenshot 2024-09-10 at 2 06 36 PM](https://github.com/user-attachments/assets/89f1cd2b-6419-48e6-a3a1-44e4c31fd4e7)

**Comment by denihs** [comment]
Hey, just created this PR to address these issues: https://github.com/meteor/meteor/pull/13343

> Email.send and Email.sendAsync seem to be a copy of one another.

Essentially, they are the same; that's why the description is almost identical. We could try to rewrite some parts, but in the end, we'd end up saying the same thing.

**Comment by denihs** [comment]
Just merged the PR with the fixes. Thank you!
