### ISSUE TITLE
Meteor falls over every time I change code on vagrant mountpoint (0.6.5)

### ISSUE THREAD

**Issue by pedantic-git** [meteor/meteor#1337]
I am developing a meteor app using [Vagrant](http://www.vagrantup.com/) (Linux host, Linux guest) which, in its normal mode of operation, mounts the application source code into the guest VM using VirtualBox Shared Folders (vboxsf).

Since upgrading to 0.6.5, every time I change a source file on this vboxsf mountpoint, the application attempts to restart and then crashes out with this error:

<pre>
/home/vagrant/.meteor/tools/4010e5731d/tools/run.js:425
    throw e;
          ^
Error: ENOTEMPTY, directory not empty '/vagrant/tutr/.meteor/local/build-garbage
-740gdb/programs'
    at Object.fs.rmdirSync (fs.js:456:18)
    at Object._.extend.rm_recursive (/home/vagrant/.meteor/tools/4010e5731d/tools/files.js:226:10)
    at _.extend.rm_recursive (/home/vagrant/.meteor/tools/4010e5731d/tools/files.js:224:15)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/vagrant/.meteor/tools/4010e5731d/lib/node_modules/underscore/underscore.js:79:11)
    at Object._.extend.rm_recursive (/home/vagrant/.meteor/tools/4010e5731d/tools/files.js:222:9)
    at Object._.extend.renameDirAlmostAtomically (/home/vagrant/.meteor/tools/4010e5731d/tools/files.js:517:13)
    at _.extend.complete (/home/vagrant/.meteor/tools/4010e5731d/tools/builder.js:436:11)
    at writeSiteArchive (/home/vagrant/.meteor/tools/4010e5731d/tools/bundler.js:1474:13)
    at /home/vagrant/.meteor/tools/4010e5731d/tools/bundler.js:1767:20
    at Object.capture (/home/vagrant/.meteor/tools/4010e5731d/tools/buildmessage.js:175:5)
    at Object.exports.bundle (/home/vagrant/.meteor/tools/4010e5731d/tools/bundler.js:1546:31)
    at /home/vagrant/.meteor/tools/4010e5731d/tools/run.js:531:32
    at exports.inFiber (/home/vagrant/.meteor/tools/4010e5731d/tools/fiber-helpers.js:24:12)
</pre>

Restarting meteor or mrt after this error works fine, and so I can work around this by sticking my meteor command in an infinite loop, but it looks like there's a bug here.

I have rebuilt my environment from scratch multiple times and still get this error, as do other members of my team.

**Comment by kidge** [comment]
Have same issue. But after symlinking the .meteor/local directory I get error 
``` bash
W20150118-12:37:51.908(5)? (STDERR) /home/vagrant/apps/.meteorlocal/build/progra
ms/server/shell.js:145
W20150118-12:37:51.909(5)? (STDERR)       throw new Error("Not a Meteor app dire
ctory");
W20150118-12:37:51.910(5)? (STDERR)             ^
W20150118-12:37:51.910(5)? (STDERR) Error: Not a Meteor app directory
```

Any ideas what is wrong?

**Comment by glasser** [comment]
@kidge This is #3437, which unfortunately didn't quite sneak in for 1.0.3.1.

@benjamn do you think we should put out a 1.0.3.2 with this fix?  Seems like vagrant users really haven't been able to use meteor for a while...

**Comment by bladesling** [comment]
I also was just attempting to get everything working in in Vagrant and ran into this issue.

I ended up just doing a meteor build and running it like I would on the server. It is a bit tedious especially when I have 2 vagrant boxes at the same time running the same codebase as I have to build for both.

**Comment by glasser** [comment]
The fix alluded to in my last comment went into 1.0.4, so I'm going to assume that this fixes @bladesling 's issue (unless that issue was different; it is hard to tell with so little details).

**Comment by bladesling** [comment]
@glasser I will give it a try next week and if it does not work hopefully I'm able to give you some more details. Thanks Guys!

**Comment by pedantic-git** [comment]
I can confirm that this is now working in Meteor 1.1. I only tried with a fresh installation of the todo app, but editing files on the vagrant mountpoint successfully rebuilt and restarted the server without any crash.

**Comment by binary1230** [comment]
hey I realize this is a very old thread, just wanted for future travelers to link to the bug report I filed with Oracle about the underlying vboxfs issue that @glasser put the repro together.   https://www.virtualbox.org/ticket/8761#  It's still unfixed quite a few years later.

**Comment by binary1230** [comment]
and thanks for the really excellent simple generic repro steps.
