### ISSUE TITLE
Boxes styles can be better

### ISSUE THREAD

**Issue by ayushrskiaa** [meteor/meteor#13395]
![image](https://github.com/user-attachments/assets/c8300614-6e53-477a-93a6-b2aadf5952de)
We can add some background shadow effect on the boxes.
please assign me this work I would like to work in this Repo.
Thank you

**Comment by chiragmalik2612** [comment]
i want to work on this, please assign

**Comment by StorytellerCZ** [comment]
The meteor.com is not in this repository.
@FredericoC @denihs just for reference.
