### ISSUE TITLE
Update copyright notice 2023 to 2024. 

### ISSUE THREAD

**Issue by Sandigupta** [meteor/meteor#13414]
The copyright notice currently states "© 2023 Meteor Software. All rights reserved", which is outdated as we are now in 2024. The notice should be updated to reflect the current year to maintain accuracy and ensure legal compliance.
![Screenshot 2024-10-14 194159](https://github.com/user-attachments/assets/5cd4d626-93e5-4d4a-8579-58c44be77fe7)

**Comment by Sandigupta** [comment]
@MitanshuKumawat 
Please label it under hacktoberfest.
Thanks

**Comment by MitanshuKumawat** [comment]
I'm getting some error while running the meteor app locally.

Your app is crashing. Here's the latest log:
Program has no main() function.
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by leonardoventurini** [comment]
Hey, thanks for letting us know, sadly the copyright notice you mentioned is in a private repo and cannot be contributed on from this repo.

@MitanshuKumawat please open a separate issue with more information, Meteor version, operating system and repro steps if possible. Thanks!

**Comment by Sandigupta** [comment]
got it.
