### ISSUE TITLE
Meteor 3: server-side `bindEnvironment` doesn't preserve all values

### ISSUE THREAD

**Issue by tmaarse** [meteor/meteor#13420]
Consider the following server-side code in a fresh application:

```js
const varA = new Meteor.EnvironmentVariable("a");
const varB = new Meteor.EnvironmentVariable("b");

Meteor.startup(async () => {
  varA.withValue(1, () => {
    varB.withValue(2, () => {
      Meteor.defer(() => {
        console.log(varA.get()); // undefined
        console.log(varB.get()); // undefined
      });
    });
  });

  varA.withValue(1, () => {
    varB.withValue(2, () => {
      Meteor.defer(
        Meteor.bindEnvironment(() => {
          console.log(varA.get()); // undefined
          console.log(varB.get()); // 2
        })
      );
    });
  });
});
```

Invoking `Meteor.bindEnvironment` should preserve the values of the active environment variables, but instead only the variable that is set last is preserved, and other variables return `undefined`. 

Meteor 2.16 does indeed print 1, 2, 1, 2, as expected.

Looking at [the implementation](https://github.com/meteor/meteor/blob/024061123a49ff1d4b89d69453ec9263ef8599e1/packages/meteor/dynamics_nodejs.js#L171), I don't understand how it should work. The comments seem a bit dated, but it appears that only the `CURRENT_VALUE_KEY_NAME` value is restored, which is the recent variable's value in this case. That value and all others seem to be stored in the `UPPER_CALL_DYNAMICS_KEY_NAME`, but that one is not (re)stored.

Strangely, `Meteor.defer` doesn't preserve any values although it uses `bindEnvironment` under the hood, but perhaps that has the same root cause.

The issue reproduces with a fresh Meteor 3.0.3 application on Linux.

**Comment by leonardoventurini** [comment]
Thanks, we will investigate

**Comment by Torgen** [comment]
So https://github.com/meteor/meteor/issues/12702 wasn't fixed?

**Comment by tmaarse** [comment]
It is now :)
