### ISSUE TITLE
elliptic 6.5.7 flagged as vulnerable in meteor-node-stubs

### ISSUE THREAD

**Issue by brianlukoff** [meteor/meteor#13426]
GitHub is [flagging version 6.5.7 of `elliptic` as vulnerable](https://github.com/advisories/GHSA-fc9h-whq2-v747) due to the version provided by `meteor-node-stubs`; is it possible to update the version of `elliptic`?

**Comment by leonardoventurini** [comment]
I logged a task for it, we might be able to get to it at the end of the release

**Comment by leonardoventurini** [comment]
@brianlukoff I released a new version for `meteor-node-stubs` upgrading `elliptic`

**Comment by brianlukoff** [comment]
Great -- thanks @leonardoventurini !
