### ISSUE TITLE
HMR Slowness with Meteor 3.0.3 + React + MUI6

### ISSUE THREAD

**Issue by bratelefant** [meteor/meteor#13430]
**Issue Summary:**  
Hot Module Replacement (HMR) in Meteor 3.0.3 has significant delays compared to version 2.16. With 2.16, HMR updates are almost instant (<1 second), but with 3.0.3, these updates take approximately 7 seconds. Profiling using `METEOR_PROFILE=20 meteor run` shows similar build times, but it takes significantly more time between the step "prepareProjectForBuild" and "Profiling: Rebuild App".

**Steps to Reproduce:**
1. Clone my fork of @Ritinha999's repo: [https://github.com/bratelefant/simple-app](https://github.com/bratelefant/simple-app)
2. Run the app using `meteor run`.
3. Make a minor change, such as adding a character in `Dummy.jsx`, and observe the HMR response time. This is as quick as it should be (it's on 2.16)
4. Run `meteor update` to update to any 3.0 version
5. Repeat steps 2.+3. Now changes take ~7 seconds to be visible in the browser.

**Observed Results:**
- **Meteor 2.16**: HMR response <1 second.
- **Meteor 3.0.3**: HMR response ~7 seconds.

**Environment:**
- React + MUI 6
- Using Meteor 3.0.3 (Issue not present in Meteor 2.16)

**Additional Notes:**
- Profiling logs indicate that additional processes introduced with Meteor 3.0 may contribute to this delay.
- We have [a forum post](https://forums.meteor.com/t/super-slow-hmr-in-meteor-3-0) on this issue.
- Some users suggest, that HTTP telemetry requests reporting package usage might contribute to this behavior.

**Comment by 9Morello** [comment]
Does that slowness persists if you run the project with the [Meteor 3.1.0 RC0](https://github.com/meteor/meteor/pull/13358)? I'm getting pretty fast hot reload with the Release Candidate build.

**Comment by nachocodoner** [comment]
In this PR we already identified the issues with HMR and fix them, https://github.com/meteor/meteor/pull/13448.

As in the comment above, as part of [Meteor 3.1.0-RC0](https://github.com/meteor/meteor/pull/13358) we included that fix.

To try it and confirm please do:

```
meteor update --release 3.1-rc.0
```

**Comment by nachocodoner** [comment]
Official [Meteor 3.1](https://dev.to/meteor/meteorjs-31-a-new-dawn-for-full-stack-javascript-development-4a13) has been released, including the fix on HMR and build slowness on Meteor 3.

Update your app and share any feedback.

```shell
meteor update --release 3.1
```
