### ISSUE TITLE
Incorrect documentation for getPublicationStrategy

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#13470]
This was [previously reported](https://github.com/meteor/meteor/issues/12022) for Meteor 2 and fix, but the Meteor 3 docs is [missing the fix](https://docs.meteor.com/api/meteor.html#setPublicationStrategy). The first argument is the collection name, not the publication name.

**Comment by fredmaiaarantes** [comment]
Tks for reporting, @zodern. I just created a PR: https://github.com/meteor/meteor/pull/13471.
