### ISSUE TITLE
Allow a cordova build to build only the cordova bundle & the cordova project, not everything else too.

### ISSUE THREAD

**Issue by DanielDornhardt** [meteor/meteor#13475]
Hi!

We're using the `meteor build` command to build our cordova app.

When running `meteor build`, there's no way to skip unnecessary architectures like `web.browser.legacy`, `web.browser` and the server bundle.

We noticed that Meteor builds all architectures, `web.browser.legacy`, `web.browser` and `web.cordova` although our cordova app itself should need only `web.cordova`.

In order to speed up the cordova build, which can be pretty annoyingly slow at times, it'd be nice if we could just skip these unneccessary (for that usecase in that moment) platforms.

Thank you and bye! :)

**Comment by matheusccastroo** [comment]
@DanielDornhardt we have the `--platforms` flag for that, you can read more of it here https://docs.meteor.com/cli/#meteor-build. It allows you to select for which platform you want to build.

**Comment by nachocodoner** [comment]
> You can also specify which platforms you want to build with the --platforms flag. Examples: --platforms=android, --platforms=ios, --platforms=web.browser.

Thank you @matheusccastroo. 😊 In dev mode, we have --exclude-archs for development, to speed up rebuilds. I forgot about these on `meteor build`, closing the issue.
