### ISSUE TITLE
Changelog not displaying content

### ISSUE THREAD

**Issue by gvanhorne** [meteor/meteor#13483]
### **1. Description**
   - **Bug Summary**: Content on https://docs.meteor.com/history.html displays briefly before disappearing when the `v3 (Current)` sidebar tab is selected
   - **Expected Behavior**: Content remains visible
   - **Frequency**: Occurs consistently upon page refresh and using different browsers

### **2. Environment**
   - **Operating System**: Windows 10
   - **Browser**: Chrome 131.0.6778.85 / Microsoft Edge Version 130.0.2849.68
   - **Device**: Desktop

### **3. Screenshot**
![image](https://github.com/user-attachments/assets/61dfd01c-d339-4c67-837e-ac7d5b6a89b9)

**Comment by 9Morello** [comment]
It's being displayed correctly on my end, both in Chromium and Firefox. 🤔
Clicking on "Meteor.js v3 (Current)" in the sidebar does nothing.

**Comment by gvanhorne** [comment]
Yes I think this has been resolved by recent commits for the release of Meteor 3.1. I'll close the issue since I can't replicate the behaviour I was seeing any longer! 👍
