### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by bnewland** [meteor/meteor#1357]
I'm using Recorder.js with Meteor for client-side audio recording, and it works wonderfully in development. However, when I run in production, the web worker associated with Recorder throws a syntax error (the aforementioned "unexpected token
'<'." I think it has something to do with concatenation of Javascript files in production mode, because the file has already been minified (works in development after minifying). A look at the development console also shows, "Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:3000/client/compatibility/recorderWorker.min.js"." Any help would be really appreciated.

**Comment by manojpanke** [comment]
I have to record audio on browser and i am using recorderWorker.js but this file gives me "Uncaught SyntaxError: Unexpected token <". Please help me for solution

**Comment by Haojen** [comment]
I have some solution too
