### ISSUE TITLE
When minifying js for production, important variables are not excluded from being mangled.

### ISSUE THREAD

**Issue by estk** [meteor/meteor#1360]
Some javascript libraries depend on the use of the "$super" variable for Prototype.js style class inheritance, namely the Rickshaw graphing library.

If we reserve the word "$super" from being mangled by uglifier-js we can avoid this issue. Perhaps in the future meteor should load options like this from a config file like environments.json?

https://gist.github.com/estk/6298222

**Comment by aendrew** [comment]
This was a really lame thing to have to deal with after coding all night. :(

**Comment by D1no** [comment]
Ran into the same problem today, waisting some debugging time. :(

Can we please add a convention that **files ending in `.min`** such as `rickshaw.min.js` or `superSensetiveStylesForStupidBrowsers.min.css` are **simply skipped** by the minifier?

There is a lot of code out there that already received some special treatment in their minified version. No need to just blindly drag them all again through an agnostic process and side-loading is surely no solution either.

**Comment by Testato** [comment]
+1

**Comment by abernix** [comment]
Files with the `.min.js` extension are no longer minified thanks to https://github.com/meteor/meteor/pull/6986.  You can avoid this problem by using that technique.
