### ISSUE TITLE
User profile is not created when account is created with accounts-password

### ISSUE THREAD

**Issue by jrullmann** [meteor/meteor#1369]
***1 Upvote*** From the [docs](http://docs.meteor.com/#accounts_createuser):
"By default the profile option is added directly to the new user document."

So I expect that if a user creates an account with accounts-password then a profile should be created for her.  Instead, I'm seeing that no profile is created.

Steps to reproduce:
1. Create the leaderboard example app (meteor create --example leaderboard)
2. Add accounts packages (meteor add accounts-ui accounts-password)
3. Add {{loginButtons}} to leaderboard.html
4. Run the app
5. Create an account with email/password
6. In the browser console, run Meteor.user().profile

Expected: Meteor.user().profile is an object
Actual: Meteor.user().profile is undefined

More info: 
- I'm using meteor version 0.6.5
- If I follow these steps using accounts-twitter the profile is created as expected

**Comment by leebenson** [comment]
Got me too - wasn't obvious why profile wasn't being saved, especially since it was being passed to .onCreateUser() and .validateNewUser()

The docs should definitely be updated - Accounts.createUser() explicitly states:

_profile Object
The user's profile, typically including the name field._

**Comment by dagatsoin** [comment]
+1

Juste found this issue page before hit "ask an question" on Stackoverflow.

Need update documentation.

**Comment by jsilverMDX** [comment]
Not sure if the current design is a bad or good idea in general. But I had this problem and I was able to get it to work. My specific gotcha is that I was trying to seed information while using a onCreateUser callback which checked the logged in user. I couldn't figure out how to check for login stuff on the server and Meteor.isServer didn't work the way I wanted (caused security problems in my case.) So I instead allowed it to slip by for the first record ever created. This allowed me to seed one admin user and then lock down the system from there. Not sure if this is entirely related but I ended up here with the exact same problem at one point.

**Comment by dtruel** [comment]
Thanks @thedavidmeister, your solution helped me.

**Comment by pascalodek** [comment]
Thanks @thedavidmeister ! Just found this after spending an hour looking for my options.profile.

**Comment by Scott-Hutcheson** [comment]
@thedavidmeister Thank you! I was very confused about this, but your solution has helped me get past this hurdle. I agree with the original point raised by @jrullmann, that the docs seem to imply the profile object is created by default.

**Comment by laosb** [comment]
This should be moved to meteor/docs.
