### ISSUE TITLE
Remove display type in Facebook login

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#1376]
`v0.6.5` with `accounts-ui` and `accounts-facebook`. When I click the "Sign in with Facebook" button, a popup appears with this message:

"
[APP_NAME] would like to access your email address.

You are using a display type of 'popup' in a large browser window or tab. For a better user experience, show this dialog with our JavaScript SDK without specifying an explicit display type. The SDK will choose the best display type for each environment. Alternatively, set height and width on your window.open() call to properly size this dialog if you have special requirements precluding you from using the SDK. This message is only visible to developers of your application.
"

**Comment by benjamn** [comment]
+1

**Comment by glasser** [comment]
Sorry for the delayed response. Does this error still occur with current Meteor?  Can you provide a reproduction like https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor ?
