### ISSUE TITLE
Global app variables under "use strict"

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1380]
It seems it is impossible to define global app variables when running code under "use strict". In documentation it is written:

> Notice that this is just the normal JavaScript syntax for declaring a variable that is local or global. Meteor scans your source code for global variable assignments and generates a wrapper that makes sure that your globals don't escape their appropriate namespace.

But this really makes "use strict" complicated to use. You have to limit it to just a part of the file. The way it was done before 0.6.5 (assigning to `this.variable`) was much better for this. Maybe there should be something in documentation explaining what is the best pattern to use both "use strict" (which we should encourage in Meteor, in my opinion - maybe even make it automatic for all files?) and global exports.

**Comment by yauh** [comment]
Looks like this issue may be related: https://github.com/meteor/meteor/issues/3510

**Comment by KrishnaPG** [comment]
So what is the meteor recommended way of doing this?

I am trying to use separate js files in my package to keep the code organized, with package-level global namespaces for communication across the files - but having problem with the 'globals' not being resolved properly in the strict mode. Wondering what is the right way.

**Comment by dandv** [comment]
Here's my approach: I created a "core" package:

    meteor create --package myapp:core

Then, export the variable. This is the entirety of package.js (you don't need tests):

```js
Package.describe({
  name: 'myapp:core',
  version: '0.0.1',
  summary: 'MyApp core',
  git: '',  // not public
});

Package.onUse(function(api) {
  api.addFiles('core.js');
  api.export('MyApp');
});
```

Then in `core.js`, just export your global:

```js
MyApp = {};
```
