### ISSUE TITLE
Assets API on Packages should have access to Application's Assets

### ISSUE THREAD

**Issue by marcfargas** [meteor/meteor#1382]
(this comes from meteor-tak: http://far.gs/18mGM8T)

Imagine you have a package that needs the user (application developer) to provide some files to it (configuration data), for example

> A package that verifies/creates RSA/DSA signatures (ie: cookie signatures, emails, HTTPS sessions, ...).
> For the package to work you need the user (application developer) to provide the certificates and/or keys to the package.

pre-0.6.5 the way to go would be to put the .PEM file somewhere and just load it with Node's "fs". But in the 0.6.5 **seems reasonable to use the shiny new Assets API**, that is: The user would put the .PEM files on private/ and the package would load them with Assets.getText()

But, for some reason Packages do not have access to Assets not defined in them, they cannot access the applications private/ via Assets calls.

So, Assets.get**\* should work inside packages giving access to:
1. the Assets of the packages this packages depends upon.
2. the Assets of the package
3. the Assets available on the application's private/

Note that for 2 to work you must define the assets in package.js (as far as I found out) but this is undocumented. My biggest concern now is 3 ;)

**Comment by jonjamz** [comment]
Aliasing `Assets` works for me too. It would be cool if we could specifically allow a package to access our assets with a flag, for example `meteor add some:package --trusted`.

**Comment by derwaldgeist** [comment]
I stumbled upon this limitation today as well. There are definitely use-cases for accessing the application's assets. In my case, I have a package that uploads fixture data to my database for testing purposes. But the actual data depends on the application, as the fixture upload package is used in several apps.
