### ISSUE TITLE
`meteor run --once` should not start a proxy server

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#1405]
The purpose of the `meteor run` proxy server is to display messages in the web browser if the server fails to run, so you can fix the bug and see the app restart without having to go to your command line. This won't actually work with `--once`, since if the inner server exits, so does the proxy server. So the proxy server never adds any value with `--once`. In addition, it means that if you are running `meteor --program some-cli-tool --once`, it will listen on a port even if the nested program is not a webapp.

I think that the proxy should not be created with `--once`; the "outer port" should be used directly as the inner port.

(Ideally, the proxy should not be created if the program does not use `webapp`, but that's more difficult. And mongod should not be run unless the program uses `mongo-livedata`...  Of course, you want these daemons to live over restarts, which makes this tricky.)

**Comment by paralin** [comment]
Any updates?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20run%20--once%60%20should%20not%20start%20a%20proxy%20server&body=Migrated%20from:%20meteor/meteor%231405) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
