### ISSUE TITLE
Make force-ssl a prodOnly package

### ISSUE THREAD

**Issue by SeriousM** [meteor/meteor#1442]
***5 Upvotes*** Hi, I'm using http://nitrous.io to develop my applications.

I would really like to use the force-ssl package but sadly i can't because only localhost-connections are not forced to be ssl.
The thing is, in cloud development there is no localhost, there is just a dedicated url that points to your virtual box.

Is it possible to add a environment variable that extends the list of allowed-non-https hosts?

**Comment by obiwarn** [comment]
+1

**Comment by keyvanfatehi** [comment]
FWIW, I ended up creating my own package with the same code as force-ssl and wrapped the code in blocks that checked if process.env.FORCE_SSL is truthy

**Comment by SeriousM** [comment]
> FWIW, I ended up creating my own package with the same code as force-ssl and wrapped the code in blocks that checked if process.env.FORCE_SSL is truthy

would you please publish it and post the link here?

**Comment by keyvanfatehi** [comment]
@SeriousM https://atmospherejs.com/keyvan/my-force-ssl

**Comment by keyvanfatehi** [comment]
i should mention it no longer wraps all the code as i had stated -- i put the if-statement in the Package.onUse callback, which i think works better

**Comment by stubailo** [comment]
In Meteor 1.2, we have the concept of prodOnly packages, so this should be much easier. I ran into this issue when testing a webhook with ngrok.

**Comment by danopia** [comment]
Any news?

**Comment by gabrielhpugliese** [comment]
:+1: cannot use force-ssl with vagrant :(

**Comment by SeriousM** [comment]
Wow, so after over two years waiting and bagging the package finally got a necessary modification. Thanks...?

**Comment by danopia** [comment]
I'm happy enough it shipped. No complaints here.

**Comment by allaire** [comment]
Move fast break things

**Comment by ddresch** [comment]
@benjamn Thanks for this update! I'm a bit confused. At the moment in the 1.3.2.4 Release force-ssl is available in version 1.0.11 which is already flagged as `prodOnly` as we can see here:

https://github.com/meteor/meteor/blob/release-1.3.2.4/packages/force-ssl/package.js

Are there any other changes somewhere which fix the problem using the package for a mobile app? At the moment it still tries to connect to https://localhost which is of course not working. 

Do we need to use the 1.3.3.beta release?
