### ISSUE TITLE
onStop callback for Meteor.subscribe

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1461]
Would it be possible to provide `onStop` callback for Meteor.subscribe? So that some additional cleanup can be done afterwards? In this way it is easier to have logic chained together: you first subscribe and do other initialization stuff, and when you move to another page, you just kill subscription and the rest will follow? I agree that many things can be done without it, but it seems to me that it opens sometimes a path to do some things easier.

**Comment by mitar** [comment]
Amazing!

**Comment by stubailo** [comment]
Hehe such a fast response time.

**Comment by steph643** [comment]
@bline:
Related issue: https://github.com/meteor/meteor/issues/3194
Related question: https://forums.meteor.com/t/how-to-know-when-a-subscription-has-finished-stopping/655

**Comment by steph643** [comment]
> In other words, how to get a callback when nosub message arrives?

@mitar, did you find any way to do that?

**Comment by mitar** [comment]
In next release of Meteor, there will be this `onStopped` callback mentioned in 085e02d525157905feb59b9dccd42765733f1667.

**Comment by steph643** [comment]
Thanks @mitar.

There is also a discussion on this [here](https://forums.meteor.com/t/how-to-know-when-a-subscription-has-finished-stopping/655).

**Comment by erperejildo** [comment]
Testing this but I can get this. Created issue here: https://github.com/Urigo/angular-meteor/issues/1584
Resuming: my callback doesn't work. Checked with `setTimeout` again the ddbb and it works
