### ISSUE TITLE
AppCache does not show cached images or fonts on refresh in any version of safari on os x or ios

### ISSUE THREAD

**Issue by akralj** [meteor/meteor#1470]
Hi,
I am developing an offline application which is using the appcache. I realised that safari on ios did not display the fontawesome font properly, when refreshing from offline. The same goes for safari on osx as well. I tested it with Safari 5 on Snow Leopard, Safari 6 on Mountain Lion, Safari 6.1 on ios 6 in the ipad simulator and on an ipad 3 with ios 6.

Images & fonts are not shown. All other browsers which support the appcache are working properly with the example below.

I created an minimal example on github:
https://github.com/akralj/meteor-appCacheSafariBug

and a version deployed on: http://appcachetest.meteor.com
Both versions use 0.6.5.1 but I also tested it with 0.66rc1

Please go to http://appcachetest.meteor.com with any version of safari, disconnect your network and press the refresh button or do window.location.reload(). The image and and home icon should be gone.

I tried the following: 
I created an app.manifest based on the last generated one, removed the long numbers after each static resource and put it into the public folder. Safari refreshes properly with a manifest like the one below.

```
  CACHE MANIFEST

  # e66d3c62bd7a3d30ffece6ba11765b31e821c97c

  CACHE:
  /
  /3eadd6b6588586d860cc106104537438f37ec271.js
  /7ce345f6e0d9d0904517543ad029bb7a7b2b7c1c.css
  /font/fontawesome.ttf
  /img/frog.jpg

  FALLBACK:
  / /
  /font/fontawesome.ttf 
  /img/frog.jpg

  NETWORK:
  /app.manifest
  /sockjs/
  *
```

It seems that safari has problems with the additional numbers.

Thank you for this great framework
andrej

**Comment by glasser** [comment]
Wondering if anyone is still seeing this issue.

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers.

Service Workers are supposed to be the replacement and is being tracked in #5982.
