### ISSUE TITLE
$within operator in minimongo

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#1473]
**_1 Upvote**_ Implement support for `$within` operator in minimongo.

**Comment by stefanocudini** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%24within%20operator%20in%20minimongo&body=Migrated%20from:%20meteor/meteor%231473) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
