### ISSUE TITLE
MAIL_URL doesn't accept password with % chacracter, not even when escaped

### ISSUE THREAD

**Issue by richieb** [meteor/meteor#1475]
MAIL_URL is quite a fussy fellow.

It wouldn't accept password with the % character, not even when the % character is escaped (with %25). I imagine it doesn't accept other escaped characters as well, but I didn't test for others.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
