### ISSUE TITLE
0.6.6 - Bus error: 10

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#1490]
I updated my projects and they began to give this error and stopped server.

OS : Macosx Maverick (10.9)

Thanx.

**Comment by rbaindourov** [comment]
This just happened to me today

```
Jeffs-MBP:angularmeteortesting rbaindourov$ meteor --port 3030 run
[[[[[ ~/angularmeteortesting ]]]]]

=> Started proxy.
=> Started MongoDB.
Bus error: 10or web.browser
```


I started a new meteor project and began following the angular meteor tutorial, and ended up with a broken project.

How can I fix this issue? What do I need to do to avoid it in the future?

Thanks
