### ISSUE TITLE
Provide a way to report and log CSP (browser policy) failures

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1493]
With 0.6.6 Meteor support CSP through `browser-policy` package. But for this to be really useful reporting by client browsers to an app when CSP fails should be added. This helps with development/debugging and also later on discovering possible attack attempts.

It could be an optional additional package which would modify CSP headers so that reporting URL would be added and then anything send to there could be stored into a collection. Collection might be a capped one.

I am not sure if this open DoS possibilities (if not using a capped collection, somebody could send fake reports, if using capped collection somebody could overflow it and hide its attack attempts). Maybe it should be limited per client IP or something.

**Comment by mitar** [comment]
Can this maybe be reopened as a feature request now?

**Comment by glasser** [comment]
I'm reasonably sure this can be done as a third-party Atmosphere package without any core changes, or maybe with small targeted core changes.  (That is, if it can even be done at all — I don't know if it's possible to detect CSP failures in JS!)

**Comment by mitar** [comment]
You do not have to detect CSP failure in JS. The only thing you have to do, is add a reporting URL in your CSP header, and then browser reports there automatically. So two things are necessary:
* adding CSP failure reporting URL header, by setting `report-url`, see here: https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_CSP_violation_reports
* listen to those failure HTTP requests and do something

BTW, why browser-policy package is not documented anymore on the docs?

So probably the first thing has to be done as part of browser policy package, and the second thing can be a third party package.

**Comment by glasser** [comment]
OK, yeah; I think a PR to `browser-policy-content` adding a `BrowserPolicy.content.setViolationReportUri` would likely be taken; handling the reports sounds like a good third-party package.

**Comment by egoldblum** [comment]
+1 to `BrowserPolicy.content.setViolationReportUri`

Furthermore, a way to set CSP report-only mode would be very welcome.  Adding this package into an existing package with many existing cross-origin dependencies and no ways to get reports is a non-starter.  I'd love to have CSP, but I'd need report-only and a way to collect those reports before turning it on for real.
