### ISSUE TITLE
Allow for configuration of MongoDB

### ISSUE THREAD

**Issue by zwippie** [meteor/meteor#15]
Or at least provide a way to disable MongoDB journaling when running the included examples.

With the current MongoDB settings, three `prealloc` files each about 1GB are created in `~/src/meteor/leaderboard/.meteor/local/db/journal`. These files are not deleted when the example is terminated. I think **9 GB** of diskspace for just 3 examples is way too much, although I understand these are the effect of the MongoDB defaults.

I could not find any mongodb.conf file related to Meteor. Perhaps I am missing some configuration options Meteor already provides when executing `meteor run`? As a temporary solution I modified `app/lib/mongo_runner.js` to include the mongodb `--nojournal` parameter in the launch_mongo function.

**Comment by bigwillstyle4ever** [comment]
So if I intend to run a Meteor app locally (LAN) and want to keep the internal MongoDB for convenience, is there a way to configure the internal Mongo instance?

**Comment by abernix** [comment]
The internal MongoDB will run so long as you are using `meteor run` in development.  If you need custom configurations, you'll need to run your own version of MongoDB locally, and then set the `MONGO_URL=mongodb://localhost:27017/database_name` (or as desired/configured).

Regardless, this is an incredibly old issue and not the place for questions.  Please try [the Meteor forums](https://forums.meteor.com/)!

**Comment by abernix** [comment]
It's worth pointing out that if an app doesn't depend on the `mongo` package in any way, the MongoDB server won't be started up in development either.  This is thanks to https://github.com/meteor/meteor/pull/8999.
