### ISSUE TITLE
Appcache: can it just cache some of the files in public folder?

### ISSUE THREAD

**Issue by zhouzhuojie** [meteor/meteor#1500]
**_1 Upvote**_ I realized that appcache package has an option that we can exclude some files we don't need to cache, like:

```
Meteor.AppCache.config({
  onlineOnly: [
    '/bigimage.jpg',
    '/largedata.json'
  ]
});
```

What if, say we have a lot of files in the public folder (which typically exceeds 5mb limit), and we want to cache those files that are frequently used. Sometimes, we cannot change or move those files to another subfolder in public folder (e.g.  dynamically loaded by a third party js library). Therefore, can we add an option like `offlineOnly` to AppCache?

```
Meteor.AppCache.config({
  offlineOnly: [
    '/a/b/c/1.jpg',
    '/a/d/e/2.json'
  ]
});
```

which means there are a lot of files and subfolders in public folder, and we only want to cache two files: `/a/b/c/1.jpg` and `/a/d/e/2.json`.

I might miss something important here, or maybe there are some workarounds you guys want to share. Thanks.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).
