### ISSUE TITLE
Allow comments in settings files (e.g. settings.json)

### ISSUE THREAD

**Issue by cacois** [meteor/meteor#1507]
Meteor's preferred option for app config is a .json file. Since strict json parsing doesn't allow comments, and comments are essential to well documented settings files, this choice causes some problems. One solution to the issue of commenting json, proposed by creator Douglas Crockford is to pipe json through JSmin (http://www.crockford.com/javascript/jsmin.html) before parsing to remove comments and import valid JSON (https://plus.google.com/118095276221607585885/posts/RK8qyGVaGSr). 

It seems like a fair solution for Meteor would be to use UglifyJS or one of the other minifiers already included somewhere in the system to do the same thing. I propose Meteor run settings.json files through some minifer before assigning them to Meteor.settings, allowing users to comment their JSON settings files at will.

**Comment by saliksaly** [comment]
+1.

**Comment by abecks** [comment]
npm's package.json allows for comments in the file, which is the closest cousin to Meteor's settings file. I don't see why it would be a bad thing, I even expect it after seeing it in other `package.json` files. Not being able to document the settings inline is a hinderance.

**Comment by jalik** [comment]
@abecks JSON format is for data only, there is no syntax for comments like `//` or `#`, if you add these, the syntax will not respect JSON constraints and thus will break the file parsing... As mentioned, there is nothing that stops you to add custom attributes like `{"myComment": "blabla"}`. Have you read all posts before digging up this issue ?

**Comment by benjamn** [comment]
@abecks Check your assumptions? Neither `//` nor `#` comments are tolerated by `npm` in `package.json`. In fact, I would be all for supporting comments in `package.json` if not for the fact that `npm` effectively forbids them.

**Comment by RobThree** [comment]
I like this style:

    {
      "//": "This sets identifier sent by the server when asked for it's name",
      "Servername": "Server-001",
      "//": "This defines the number of days before the world comes to an end",
      "Apocalypse": 42,
      "//": "Determines whether the flux capacitor is enabled",
      "FluxcapacitorEnabled": true
    }

**Comment by karelkral** [comment]
@RobThree: With this style, you are getting warnings about duplicate keys used "//".

**Comment by RobThree** [comment]
> @RobThree: With this style, you are getting warnings about duplicate keys used "//".

It is valid JSON? Where/what/how/why are you getting duplicate keys?

**Comment by karelkral** [comment]
I am getting warnings when editing appsettings.json in Visual Studio editor. The warnings can be ignored, of course, but I am a developer who works with 0 warnings.

**Comment by RobThree** [comment]
>  but I am a developer who works with 0 warnings.

I am too and you *should* IMHO. But that doesn't mean that these warnings are correct. In this case the warnings are just that: warnings. See if you can disable the warning or ignore this particular warning. And if you insist on making VS happy then simply don't use this comment style.
