### ISSUE TITLE
use socket.io engine.io for websocket and transport

### ISSUE THREAD

**Issue by keichii** [meteor/meteor#1508]
https://github.com/LearnBoost/engine.io is much mature than other ws interface that meteor is using. 

so we drop all related libraries and use only engine.io for that particular purpose

**Comment by arunoda** [comment]
please re-consider engine.io.

It first uses long polling to get data while creating the socket connection. Which is very nice.
I didn't give it a try, but I'll make our apps faster.

I hope you know it's not socket.io :)

**Comment by arunoda** [comment]
See this screencast: http://recordit.co/G81oZfZ8Bv

First it has a waiting time until connecting to the socket.
After that, things works pretty smoothly.

This is based on 4 mbps connection - yeah, this is the kind of fast internet we've :D here.
