### ISSUE TITLE
Meteor allows creating a new user in console even after removing insecure package

### ISSUE THREAD

**Issue by Elfoslav** [meteor/meteor#1548]
If I write into JavaScript console

```
Accounts.createUser({ email: 'abcd', password: 'asdf' });
```

User is created. Meteor version 0.6.6.2.
Expected behaviour is not to allow creating a new user from console/client after removing insecure package.

**Comment by avalanche1** [comment]
So how do I restrict visitor to create user only through sign-up form?
And to prohibit user creation from console.

**Comment by PeppeL-G** [comment]
Somehow the client needs to send the information in the sign up form to the server, and on the server you can't determine whether the client has used the sign up form or simply sent the same information to the server without using the form. This is a well known problem (it's actually not a problem, but I don't know a better word for it) not unique to Meteor. In Meteor you use [Accounts.onCreateUser](http://docs.meteor.com/#/full/accounts_oncreateuser) to determine whether the user should be allowed to be created or not.
