### ISSUE TITLE
Template render and HTML autofocus incompatibility

### ISSUE THREAD

**Issue by stephentcannon** [meteor/meteor#155]
I built a long page.

It had two forms on it.  

It had two templates on that which were subscribed.

A form had an input element with autofocus in the html tag.

Example 
`<input type="text" class="input-xlarge" id="name" name="name" maxlength="100" autofocus>`

When the two templates rendered data (either because other users changed the data or the data was changed on the server) the window focus would redirect to the html tag with autofocus and scroll the view for the user.  

Actions that stopped the side effect
1.  Removing the template subscriptions and this did not happen.  (obviously, undesirable solution)
2.  Removing the autofocus and this did not happen. (less desirable but lesser evil of solutions)

Autofocus seems to be a valid HTML5 dom attribute and it seems that it should work with Meteor.  

I am not sophisticated enough to debug what was happening under the hood only that it can be reproduced and the above two options stop the side effect and that autofocus html5 attribute support may be required.

S

**Comment by gcacars** [comment]
I can't focus input with autofocus tag nor with jQuery $('#id').focus(); on rendered template with Template.dynamic why?
