### ISSUE TITLE
BrowserPolicy should smooth over cross-browser discrepancies when possible (specifically "foo.com" origins)

### ISSUE THREAD

**Issue by estark37** [meteor/meteor#1575]
In Chrome, allowing "foo.com" in a CSP allows "http://foo.com"; in Firefox, it allows "http://foo.com" and "https://foo.com".

BrowserPolicy can hide this discrepancy by explicitly allowing either http or http/https when you allow "foo.com" (and document which one). Maybe there are other cross-browser discrepancies that we can smooth over for a better CSP user experience.

**Comment by hwillson** [comment]
Code to handle the main discrepancy mentioned in this issue [was implemented](https://github.com/meteor/meteor/blob/3801349437dc7be908f152783488d17ea6fb29d4/packages/browser-policy-content/browser-policy-content.js#L95-L99). If any other browser discrepancies come up that could be addressed in a similar way, they can be tracked in a new issue. Closing - thanks for noting this originally!
