### ISSUE TITLE
Upsert from client with allow/deny rules

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#1587]
Maybe one way to let it play well with `allow` and `deny` rules is another `upsert` rule?

It might be better than going through both update and insert validation checks.

**Comment by waiholiu** [comment]
Hi @glasser , in light of this issue, just to confirm, upsert is denied outright on the client?

Should the documentation http://docs.meteor.com/#/full/upsert be changed to say that upsert doesn't work "anywhere" but only on the server?

**Comment by glasser** [comment]
No, upsert works on both the client and the server. But it doesn't work on allow/deny-restricted update RPC methods.

So when can you use it on the client? You can use it within stubs on the client, and you can also use it from the client in `insecure` mode.

**Comment by llvasconcellos** [comment]
@glasser So GOD DAMN document it!!! 
Meteor documentation is frustrating. No examples. Lacks a lot of information. It makes me waste a HUGE amount of time in stupid things.

**Comment by merlinpatt** [comment]
@llvasconcellos please there is no need to curse. A simple polite request will go a long way.

Alternatively, if you find that things are not documented well, you can always make a PR to contribute to and improve the docs yourself. https://github.com/meteor/docs

**Comment by kakadais** [comment]
@llvasconcellos I believe that you can always run away from this meteor world or othes as well bro.

**Comment by kakadais** [comment]
@glasser I'm wondering that the idea of CRUD in client is just for making it easy for newbie? I thought that could be a new approach and one of the good idea to build an application if we could care the security things more. I just want to know we have to stop to use it on the security perspective.

**Comment by llvasconcellos** [comment]
@kakadais I did it! And I'm glad I did. Also, still mad with the time wasted on this piece of software.

**Comment by kakadais** [comment]
@llvasconcellos Congrats for you- but I want to carefully warn you that there's no best or worst tech in the world, but only appropriate tech with smart enough person to know where and how to use ;)

**Comment by llvasconcellos** [comment]
@kakadais I disagree. Some people are smart enough to understand that some techs aren't worth the effort.

**Comment by kakadais** [comment]
@llvasconcellos KKK Yeah but first of all, we don't call the people  'smart' who said that 'smart' to himself  bro ;) Nice to have a conversation- bye-
