### ISSUE TITLE
FB Auth in Chrome

### ISSUE THREAD

**Issue by BradRuderman** [meteor/meteor#1590]
Reopening: https://github.com/meteor/meteor/issues/1531#issuecomment-27415932
Repo URL: http://fbloginbug.meteor.com/
Repo Repo: https://github.com/BradRuderman/fbloginbug

Steps:
Using Chrome iOS Mobile - try to login into http://fbloginbug.meteor.com/

Thanks,
Brad

**Comment by stubailo** [comment]
As far as I know, this has been fixed.
