### ISSUE TITLE
DDP server can send duplicate ready messages for subs on setUserId

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#1593]
There is code in `_setUserId` in `livedata_server.js` to batch up all `ready` messages on the re-run subs until after all of them are re-run, but this can lead to `ready` messages being sent for subs that were already ready before the `setUserId` call. A given sub should receive at most one `ready` messages.

(There is the related issue of what the semantics of a sub that became ready, then was re-run due to a `setUserId` and is not ready again should be. Perhaps the real answer here is that we need out-of-band login.)

**Comment by hwillson** [comment]
A lot of the Meteor codebase has changed since this issue was created. Closing as part of the on-going old issue cleanup process. If anyone encounters this issue with a modern version of Meteor, please post back with the full details (and ideally a runnable reproduction). Thanks!
