### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by tcurdt** [meteor/meteor#16]
I would prefer to install meteor via homebrew.

**Comment by pwnall** [comment]
I would prefer to use Homebrew to install meteor too, so I don't have to spend time vetting the installer script.

**Comment by kevinSuttle** [comment]
Well, it's on npm now. https://www.npmjs.com/package/meteor

**Comment by pwnall** [comment]
@kevinSuttle Are you referring to [this](https://www.npmjs.com/package/meteor)? It seems super-old, and it's unclear if the author is connected to the MDG or not. The latter point matters, because [untrusted npm packages can wreck your machine](https://github.com/joaojeronimo/rimrafall).

**Comment by kevinSuttle** [comment]
So can untrusted _anything_. But this is the proper link. http://www.infoworld.com/article/3048806/javascript/meteor-javascript-framework-moves-to-npm.html

**Comment by laosb** [comment]
@kevinSuttle That package wasn't made by MDG, and MDG didn't move meteor itself to npm now. From 1.3 Meteor does begin to npm, but not on npm now.
