### ISSUE TITLE
Templates with a dash('-') in name compile but can't be used

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#1602]
In the new rendering engine:

If template has a dash in name, it will fail to be compiled. Example:

```
<template name="super-duper">
  Here I am!
</template>
```

See the reproduction: https://github.com/Slava/meteor-dashed-template-bug-repruduction

**Comment by rclai** [comment]
@avital does subexpressions account for the aforementioned `{{> foo(x-5)}}`?

**Comment by glasser** [comment]
It looks like the status quo is that `<template name="foo-bar">` compiles but `{{ > foo-bar }}` won't load it. Probably the template should fail to compile...

**Comment by glasser** [comment]
And notably, `{{> hello-bar}}` fails to compile whereas `{{> hello-1}}` compiles but tries to load `hello`.

**Comment by DerekTBrown** [comment]
This appears to also be true of Helpers

**Comment by ferhtgoldaraz** [comment]
There's something about identifiers in the (spacebar docs)[https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#identifiers-and-paths]

Has anybody tired something like `{{> ["hello-bar"]}}`? I'm wanting this, but using meteor jade, and it'd be interesting to know.

If y try it and works, will comment about it

**Comment by distalx** [comment]
@mitar moved this issue to https://github.com/meteor/blaze/issues/91
