### ISSUE TITLE
Triple stache doesn't allow `<script>` tags (template-engine-preview-5)

### ISSUE THREAD

**Issue by estark37** [meteor/meteor#1609]
Meteor UI does funny things when you try to put `<script>` tags inside a triple stache. Probably low priority -- I'm just trying to create an app with an XSS in it for demonstration purposes.

Repro: https://github.com/estark37/meteor-triple-stache-script-bug
Expected: contents of `document.body` is `<script>alert(1)</script>`.
Observed: contents of `document.body` is nothing

Also, doing a `Session.set("test", <script>)` behaves as expected, but `<script>alert(1)` results in an empty body.

**Comment by glasser** [comment]
@dgreensp is this the thing you fixed in #3797?

**Comment by estark37** [comment]
Remember back in the day when it was called "Meteor UI"? :)
