### ISSUE TITLE
LogoutOtherClients also logout current session in same browser

### ISSUE THREAD

**Issue by zapaz** [meteor/meteor#1616]
**_3 Upvotes**_ LogoutOtherClients on new Login works fine on other browsers or other devices loggued, good !

But when opening a Meteor App in a second tabs on the same browser, both windows are logout. Would be better to logout only the other one (or none !?).

Another way to get the same problem, being in a Meteor app, click on an external link, then comme back with the back button of the navigator, here only one tab but still logout (seems always two tabs in browser memory)

**Comment by cesarve77** [comment]
+1

**Comment by guncebektas** [comment]
+1

**Comment by MichaelJCole** [comment]
+1

**Comment by abernix** [comment]
Closing as duplicate per my comments here: https://github.com/meteor/meteor/issues/6777#issuecomment-222941379
