### ISSUE TITLE
minimongo use of `undefined` doesn't match mongo shell

### ISSUE THREAD

**Issue by datacarl** [meteor/meteor#1646]
Mini-mongo doesn't treat `undefined` in a $in lookup the same way as the server does. On the server it matches both null and undefined, but on the client it doesnt match any of them.

``` javascript
  Collection.insert({name: [null]});
  Collection.insert({name: [undefined]});
  Collection.insert({name: ['test']});

//server
console.log(Collection.find({name : {$in : [undefined]}}).count()); // -> 2

//client
console.log(Collection.find({name : {$in : [undefined]}}).count()); // -> 0
```

**Comment by dotnetwise** [comment]
undefined should be ignored - otherwise you need to delete a property by using the `very slow` operator `delete`. Please reopen this issue
