### ISSUE TITLE
If using stylus package it is not possible to run from anywhere else than root directory

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1655]
If using stylus package it is not possible to run Meteor from anywhere else than root directory. So if you run Meteor from `client` or `server` directory you get Stylus errors.

**Comment by stubailo** [comment]
I don't think this is the case anymore, especially not in Meteor 1.2 since we have rewritten this package from the ground up.

**Comment by vflyson** [comment]
I can confirm the bug still exists in Meteor 1.5:
```
=> Errors prevented startup:                  
   
   While processing files with stylus (for target web.browser):
   packages/app:core/css/main.styl: Stylus compiler error: css/main.styl:1:9
   1| @import 'general.import'
   --------------^
   2| 
   3| @import 'buttons.import'
   4| @import 'tabs.import'
   
   failed to locate @import file general.import.styl
   
   
=> Your application has errors. Waiting for file change.
```
As seen from the log, I'm using the legacy "packages/" structure within the app.
The error's only being thrown upon inital compilation though -- once I trigger the live reload Meteor won't throw this error any longer and start the app just fine.

**Comment by vflyson** [comment]
upd: to bypass the issue I have to trigger the live reload by modifying the file in which the error occurs (e.g. main.styl in case of the example). I now get two of these errors in my project, as I am now using stylus in more than one package. @meteor, please fix this one!

**Comment by hwillson** [comment]
@vflyson Can you link to a small, runnable reproduction (using Meteor 1.5.1) that demonstrates this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))?

**Comment by vflyson** [comment]
Fo shizzle @hwillson 
Here you go, [a link to a small, runnable reproduction (using Meteor 1.5.1) that demonstrates this issue](https://github.com/vflyson/meteor-stylus-package-bug)

**Comment by vflyson** [comment]
upd:
Tried to build my app, getting the same error (fails to build):
```
meteor build --architecture os.linux.x86_64 ../dist/live/
Errors prevented bundling:                    
While processing files with stylus (for target web.browser):
packages/app:core/css/main.styl: Stylus compiler error: css/main.styl:3:9
1| /* packages/core/css/main.styl */
2| 
3| @import 'general.import'
--------------^
...
```

**Comment by vflyson** [comment]
@benjamn @Slava Please let me know if you'd like me to create a separate issue for this, unless you're already working on fixing it for the next release.

**Comment by hwillson** [comment]
Hi @vflyson - if you adjust your `api.addFiles` call in `app/packages/core/package.js` to look like

```js
  api.addFiles([
    'css/main.styl',
    'css/general.import.styl',
    'html/index.html',
  ], 'client');
```

things should work properly. This isn't a `stylus` issue; your `general.import.styl` file just isn't being included in your package.

**Comment by vflyson** [comment]
Hey @hwillson 
I've tried doing that before, and it didn't work the same as including `general.import.styl` via `@import`.
It also does not explain why after triggering the live reload on `main.styl` the `stylus` package is able to find and import my `.import.styl` files.

**Comment by hwillson** [comment]
On my side when I run your repro locally (using the Meteor Tool), without making any changes, it works properly first try:

![screenshot 2017-07-23 12 19 39](https://user-images.githubusercontent.com/137740/28501207-21c1e28c-6fa5-11e7-858f-3147c06ce9e8.png)

![screenshot 2017-07-23 12 19 48](https://user-images.githubusercontent.com/137740/28501209-27cad774-6fa5-11e7-8a4f-7a31a946c8a9.png)

The only time I get an issue is when I try to `meteor build`. By adding that missing file to your `package.json` however (and still keeping the `@import 'general.import'` statement in your `main.styl`), I can then build properly.

**Comment by vflyson** [comment]
Could you please try running `meteor add stylus` and `meteor remove stylus` and see if it triggers the issue? I remember that I've managed to run my repo with `@import` the first time as well, and then it got somehow broken, possibly after removing and adding packages.

**Comment by vflyson** [comment]
Debian x86_64 here, here's the steps on my end:
```
git clone git@github.com:vflyson/meteor-stylus-package-bug.git bug
cd bug/app
meteor npm install
meteor --port 3090
```
And I get 
```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with stylus (for target web.browser):
   packages/app:core/css/main.styl: Stylus compiler error: css/main.styl:3:9
   1| /* packages/core/css/main.styl */
   2| 
   3| @import 'general.import'
   --------------^
   4| 
   
   failed to locate @import file general.import.styl
```
right away.

It is likely that the live reload conflicts with how stylus imports files upon initial Meteor start, and it is likely related to code responsible for inotify on Linux (perhaps you're using macOS, @hwillson?).

**Comment by hwillson** [comment]
Bizarre @vflyson - your repro is working for me on macOS and Ubuntu 16.

![screenshot 2017-07-23 20 37 31](https://user-images.githubusercontent.com/137740/28504538-e05f7484-6fe6-11e7-8e4b-978c04ce7e5f.png)
