### ISSUE TITLE
`meteor deploy` server gets non-ideal SSL grade (eg, allows RC4)

### ISSUE THREAD

**Issue by jagill** [meteor/meteor#1661]
It only seems to support TLS 1.0, as well as the deprecated SSL2 and SSL3.  TLS 1.2/3 should be enabled on the server to improve security.

It also doesn't support ssl session resumption, which speeds up connections.

You can check this out and more at:

https://www.ssllabs.com/ssltest/analyze.html?d=meteor.com&s=107.21.116.12&hideResults=on

**Comment by glasser** [comment]
`meteor deploy` now supports TLS 1.1 and 1.2, and does not support SSL2 and SSL3. We get a B on the SSL Labs test now (supporting RC4 seems to be the remaining issue).

**Comment by laosb** [comment]
Since Meteor.com Free Hosting was shutdown, closing.
