### ISSUE TITLE
App crashing on 0.7.0 version

### ISSUE THREAD

**Issue by adrdomeniconi** [meteor/meteor#1691]
Hi, I just updated the Meteor to the 0.7.0 version, and my application is crashing on startup. I tried to remove some packages e add again, I also tried to update de nodeJs version to 0.10.22, but didn't solved. The error is:

=> Errors prevented startup:

While building the application:
lib/node_modules/npm/html/doc/api/npm-bin.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-bugs.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-commands.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-config.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-deprecate.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-docs.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-edit.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-explore.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-help-search.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-init.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-install.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-link.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-load.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-ls.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-outdated.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-owner.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-pack.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-prefix.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-prune.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-publish.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-rebuild.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-restart.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-root.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-run-script.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-search.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-shrinkwrap.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-start.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-stop.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-submodule.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-tag.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-test.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-uninstall.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-unpublish.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-update.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-version.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-view.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm-whoami.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/npm.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/api/repo.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-adduser.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-bin.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-bugs.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-build.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-bundle.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-cache.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-completion.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-config.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-dedupe.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-deprecate.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-docs.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-edit.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-explore.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-help-search.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-help.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-init.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-install.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-link.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-ls.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-outdated.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-owner.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-pack.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-prefix.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-prune.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-publish.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-rebuild.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-restart.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-rm.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-root.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-run-script.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-search.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-shrinkwrap.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-star.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-stars.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-start.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-stop.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-submodule.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-tag.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-test.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-uninstall.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-unpublish.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-update.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-version.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-view.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm-whoami.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/npm.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/cli/repo.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/files/npm-folders.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/files/npm-global.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/files/npm-json.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/files/npmrc.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/files/package.json.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-coding-style.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-config.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-developers.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-disputes.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-faq.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-registry.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/npm-scripts.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/removing-npm.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/misc/semver.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/README.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/doc/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/docfoot-script.html:1: bad formatting in HTML template
lib/node_modules/npm/html/docfoot.html:1: bad formatting in HTML template
lib/node_modules/npm/html/dochead.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/html/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
lib/node_modules/npm/node_modules/ansi/examples/beep/index.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/ansi/examples/clear/index.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/ansi/examples/progress/index.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/ansi/examples/cursorPosition.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/ansi/examples/starwars.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/nopt/bin/nopt.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/nopt/examples/my-program.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/slide/lib/async-map-ordered.js:67:2: Unexpected token )
lib/node_modules/npm/node_modules/opener/opener.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/rimraf/bin.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/node_modules/semver/foot.js:8:1: Unexpected token }
lib/node_modules/npm/node_modules/semver/head.js:4:3: Unexpected end of input
lib/node_modules/npm/bin/npm-cli.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/scripts/index-build.js:1:15: Unexpected token ILLEGAL
lib/node_modules/npm/cli.js:1:15: Unexpected token ILLEGAL

=> Your application has errors. Waiting for file change.

Any ideas?

Thank you...

**Comment by svanderbleek** [comment]
:+1: this happened to me also stupid, accidentally installed npm into the current path as well because https://docs.npmjs.com/getting-started/installing-node has a period after the `-g` that if copied, yup.
