### ISSUE TITLE
[HTTP package] Pass unrecognized options through to request module

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#1703]
The HTTP package calls [request](https://github.com/mikeal/request), which in turn calls Node's http or https modules. The latter especially can take rather esoteric options for TSL configuration.

It would be great if `HTTP.call()` would pass through any options it doesn't recognize. This solves a [use case I ran into](http://stackoverflow.com/questions/20681044/how-can-i-pass-extra-options-to-node-in-meteors-http-call), where I had to set `{rejectUnauthorized: false}`.

**Comment by glasser** [comment]
Feedback has been heard.  We should make it much easier to use request directly via the HTTP module, with appropriate warnings that the API could change with updates.  I hope to do this for 1.0.4 if time permits.

**Comment by dandv** [comment]
Thanks @glasser !

**Comment by dandv** [comment]
@glasser, thanks for reconsidering this feature request and implementing a fix.

For others who check this issue - you can [now](https://github.com/meteor/meteor/commit/8dae78d48b80d7dab9154d912102a9ebb0a28f60) pass `npmRequestOptions` to [HTTP.call](http://docs.meteor.com/#/full/http_call).

**Comment by digz6666** [comment]
Any example using npmRequestOptions?

**Comment by digz6666** [comment]
Nevermind, I found it:
```javascript
HTTP.post(url, {
    npmRequestOptions: {
        rejectUnauthorized: false // TODO remove when deploy
    },
    timeout: 30000, // 30s
    data: xml
}, function(error, result) {
    console.log('error: ' + error);
    console.log('resultXml: ' + result);
});
```
