### ISSUE TITLE
Collection.upsert doesn't return _id if Document was only updated

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#1715]
Yeah, I think the title is self speaking.

Maybe it's not designed to do it, but I actually have an Issue, where I have to look into the DB a second time, to grab the Id.. Not cool so far..

What I actually get back from Collection.upsert is 
{ numberAffected: 1, insertedId: 'huY33sokXMYDGrkAJ' } // If just inserted
and 
{ numberAffected: 1} // if just updated...

Meteor 0.7.0.1

mmh, no Id of the doc..

But, I love meteor (4 Months with it (and JS after a couple of years with php, drupal and a common LAMP stack)) --- Meteor is really, really cool ;)

**Comment by lucendio** [comment]
Hi,

I ran into this issue and would like to ellaborate on the questin why this could lead to more efficient code:

In my case, the selector used in the upsert doesnt include the mongo ``_id`` and I dont have it before performing the upsert, but I would like to have the ``_id``afterwards for further usage. To do so, I need to query the database *again* for a simple lookup. Okay, I have to admit the fields within my selector are indexed, but the additional request to the database could be avoidable anyway, imho

NOTE: the documentation on upsert might be a bit confusing regarding ``insertedId:``. It days, its include in upsert but not in update. At least thats how I read the description.
