### ISSUE TITLE
POST part of request sometimes empty

### ISSUE THREAD

**Issue by siggioskarsson** [meteor/meteor#1722]
I have a small meteor app that is adding a connect handler to the WebApp object and needs to access the request body (POST data) and do something with it.

```
WebApp.connectHandlers.use(function(req, res, next) {
   var POST = req.body;
   console.log(POST);
   // do something with POST....
}
```

The POST variable is sometimes filled, and sometimes empty. I have tried to reproduce this, but cannot reliably, suggesting this has something to do with the asynchronous nature of node and that req.body is not done yet.

I have tried wrapping this in req.on('end', function() {....}), but this sometimes hangs and sometimes doesn't and POST is still sometimes filled and sometimes not. I have seen some hints about using npm.connect, but I don't believe this cannot be done in meteor directly.

What is the correct and reliable way of getting at the req.body (POST data) in meteor at this point in the execution?

**Comment by alex028502** [comment]
I am seeing the same problem.  I have put @siggioskarsson's example into a package that shows it with tinytest:

https://github.com/alex028502/meteor-issue-1722

The set of commands is in the readme.

I have also tried putting 
```
console.log(req);
```
into the api code and searched it for the posted data just in case it was somewhere else, but with no luck.
