### ISSUE TITLE
Command to add Meteor to existing project

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#1743]
I don't see anything about how to do this in the docs or help. Instead of `meteor create`, sometimes I have a project folder with a bunch of files already in progress, and then I decide to use Meteor in order to do something. It would be nice to easily add `.meteor`, etc. to the folder, same as when using `create`, except don't touch any of the existing files or add any example files.

``` bash
$ cd <existing project directory>
$ meteor ify
```

**Comment by virajhk** [comment]
@aldeed Thank you so much. :)

**Comment by avalanche1** [comment]
@glasser It's a shame you don't want to support this. On several occasions I wished there was such a command
