### ISSUE TITLE
memory leak: session/observers are not cleared on ungracefully closed websocket

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#1769]
Cc: @tmeasday @n1mmy 

After monitoring atmosphere over the past week (sorry about the downtime during this) I think i've found a potential issue when sockets are ungracefully closed. Meteor keeps these sessions in memory and they build up.

It's quite difficult to test this because its hard to emulate what ungraceful exit is. I could see lots of sessions in memory on atmosphere that were over 14 hours old so this is what I started to watch for.

Additionally meteorite, until last week, used `process.exit()` to exit instead of disconnecting the active socket. I'm not sure if this could have played a role in all this. 

There were about 430 active sessions in memory, 30% being from meteorite, most over 14 hours old (310 sessions). I say this because those 30% didn't subscribe to the typical methods one would on atmosphere). The meteorite `process.exit()` issue was fixed last week: https://github.com/oortcloud/meteorite/commit/6d8935186181ee4898cba1235562e4cd66fce5ad

 I tried to make an app with a modified livedata package that keeps track of all the active sockets at any given time. (Sorry about the js errors, I don't think linker plays well with custom modified core packages. it doesn't work without `--debug`) : https://github.com/Tarangp/Meteor-memory-leak-bug

To give you an idea, this is what the memory on atmosphere looks like at the moment, so this may be what is causing it.

![screen shot 2014-01-15 at 1 48 34 pm](https://f.cloud.github.com/assets/1616628/1950632/5eb9d988-8151-11e3-8b01-e223de41f97b.png)

## How to reproduce the issue

1. Deploy the app from : https://github.com/Tarangp/Meteor-memory-leak-bug (with `--debug`. Also hosted at : https://testsessionbug.meteor.com/

2. Visit the app in a web browser to monitor activity

3. Visit app on an iPhone (should work with android, etc but this is what I tried with). Ensure websockets are used/There isn't a proxy with the carrier like bytemobile (or just use https).

4. When iPhone's session is visible on the browser set the iPhone in airplane mode/switch off wifi (must have no 3g connectivity)

5. The iphone won't be cleared from the list (since `socket.on('close'..)` isn't firing) : https://github.com/meteor/meteor/blob/b5cd66dedd014a8df7990f9160284c78103ef955/packages/livedata/stream_server.js#L70

This might be a bug in sockjs or there might be a different way to handle the ungracefully closed connection? 

## Amplification

While this bug may be small, when a session is left in memory this way all its observer's and publish methods stay active. This is probably the memory used builds up so quickly. 

I tested this in a separate project similar to the above just monitoring to see if `onStop` was called. If the socket is closed ungracefully `onStop` isn't called and all the observers remain active. 

This is probably why Nick mentioned there might be a CPU leak too, likely from calculating the diffs on the observer methods from the publish functions. This would have been done for all these unclosed sessions wastefully when a document is changed. 

There are also > 800 packages on atmosphere which are subscribed to in entirety for each of these sessions. Meteor keeps track of each users subscription's documents too (to identify what to remove when the subscription is `unsub`'d and what to send `.changed` for a particular client) so this would add up for each of these sessions.

The issues on atmosphere started when the custom download counter was added in and its likely that it contributed to using more memory and cpu per session. 

Alongside higher traffic than usual this is what might have taken atmosphere down, especially when the sessions build over a weeks time. I've been redeploying atmosphere every 2 days for the moment to try and prevent this.

Related 

 - https://github.com/sockjs/sockjs-node/issues/129
 - https://github.com/sockjs/sockjs-node/issues/127

**Comment by glasser** [comment]
We're using the new http-proxy on `meteor deploy` these days, and we have DDP heartbeats, so I think this is done.
