### ISSUE TITLE
Deps.autorun is available on the server

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1798]
I just spend quite some time debugging why Deps.autorun does not work on the server. And now I see in documentation that it is available only on the client side. Then I think it should not be provided on the server side at all (not that it works, but not really), or it should be reactive as you expect on the server side. Why it is not reactive?

I was trying to achieve this:

```
Deps.autorun ->
  __meteor_runtime_config__.INSTALL = Meteor.users.find({}, limit: 1).count() == 0
```

**Comment by mitar** [comment]
Any progress on this?

**Comment by mitar** [comment]
This old package seems to [try to address this](https://github.com/Diggsey/meteor-server-deps/blob/master/lib/server-deps.coffee). Could anyone look into it?

**Comment by mitar** [comment]
I made this package: https://github.com/peerlibrary/meteor-server-autorun

**Comment by JobJob** [comment]
@mitar Great stuff, cheers! I'd also like to see this supported in core.
