### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jsalonen** [meteor/meteor#18]
Running `curl install.meteor.com | sh` on Windows suggest that support for Windows has been planned (gives message: "Sorry, this OS is not supported yet.").

I'm adding an issue to track progress on this!

**Comment by davewallace** [comment]
Tried a clone today, windows 10 with a selection of node versions: "Sorry, this OS is not supported yet."

**Comment by abernix** [comment]
@davewallace This issue has been closed for over 4 years.  Please see #7583 if you're trying to `curl`/ or `clone` using Bash on Windows 10 Anniversary (not supported yet).  But really, the usual [Windows 10 installer](https://install.meteor.com/windows) should still work fine using the Command Prompt (or PowerShell).  Either way, pick a newer, more relevant issue.
