### ISSUE TITLE
Meteor's bundler options are not available to smart packages

### ISSUE THREAD

**Issue by bminer** [meteor/meteor#180]
It would be really nice to see if the Meteor project is running in production or development mode from within a smart package.

For example, the Blade smart package may want to minify templates, removing unneeded error reporting and debugging information from the templates.

The production option is mapped to the minify option here: https://github.com/meteor/meteor/blob/master/app/meteor/meteor.js#L114

Ideally, Blade could have access to this option:
https://github.com/meteor/meteor/pull/152/files#L1R23

**Comment by v1nay** [comment]
I handle this situation by using this code in a server side file (eg. `server/lib/environment.js`)

```
Meteor.startup(function(){
  if(process.env.METEOR_ENV =="production") {
    console.log("Running in production");
    process.env.ROOT_URL="http://your-url" //production url
  }

});
```

and export a new environment variable at shell while running meteor application using `METEOR_ENV=production meteor run --production `
