### ISSUE TITLE
Improve CSS minifier

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#1816]
As of ca164d477dd364dd835c13f0b630ef04c126e54d, Meteor stopped using Clean-CSS and simply converts CSS AST to text omitting extra whitespace and redundant semicolons.

It would be nice to port most of Clean-CSS techniques to the new minifier code with tests.

**Comment by raquelhosein** [comment]
Hey if this issues is taken care of consider closing it! Thank you :)

**Comment by hwillson** [comment]
There has been very little activity/support on this issue in over 2 years, and a lot has changed with regards to Meteor's build plugin approach. There is now a proper [build plugin API](http://docs.meteor.com/api/packagejs.html#build-plugin-api) that makes integrating other minification  solutions much easier. As part of the on-going old issue cleanup process, I'll close this off. Thanks for opening this originally!
