### ISSUE TITLE
(Mini)MongoDB not working with Meteor locally

### ISSUE THREAD

**Issue by medicus** [meteor/meteor#1824]
When I start my meteor app with meteor run first, then open a new console window and type in meteor mongo, it always gives me the error: 
mongo: Meteor isn't running. 
This command only works while Meteor is running your application locally. Start your application first. 

But if I deploy the Meteor app first with meteor deploy appname, I can access the mongo shell with meteor mongo appname. 
Why is this?

**Comment by Tevinthuku** [comment]
Meteor mongo only works if the app is running so if you are on windows then open up a new command prompt, cd into the app directory and type meteor mongo.. This should work.
