### ISSUE TITLE
stringifyDDP: EJSON.clone on large binaries blocks UI

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#1828]
This issue is with current stable and current devel. It's easiest to see by running my repro repo: https://github.com/aldeed/stringifyDDP-issue
1. Clone the repo.
2. Start the app.
3. Open app in Chrome.
4. In browser console, enter `uploadTest()` and then try scrolling the page while it runs.

This simulates "uploading" 30 1MB chunks of data using DDP. They are sent to a meteor method that does nothing. Note that UI rendering is blocked during each `apply` call, causing scrolling the page to be choppy.

I tracked this issue to the fact that `stringifyDDP` calls `EJSON.clone` on an object containing the arguments here: 

https://github.com/meteor/meteor/blob/8eca012c32802abb7f877809c7ae83ad6e0eca41/packages/livedata/livedata_common.js#L86

When I comment out the cloning, the scrolling is smooth.

I think some amount of cloning is necessary due to the deletions and `EJSON._adjustTypesToJSONValue` that come next, but perhaps it can be done with more finesse? There are other places where we (collectionFS developers) have encountered issues with `EJSON.clone` and large binary data chunks, so maybe look into a partial clone method that clones most things but references binary data memory instead of cloning it? In places like `stringifyDDP` in particular, a brute force deep clone seems like overkill since we are just going to stringify it right away anyway. In fact, it's probably rare that we'd actually want to clone a binary data array in most of the current places where `EJSON.clone` is used.

**Comment by hwillson** [comment]
I've tested the supplied repro out and can't seem to re-create the initial issue. That being said, a lot has changed since this issue was created. As part of the on-going old issue cleanup process, I'll close this issue for now. Thanks for posting this originally!
