### ISSUE TITLE
Spiderable doesn't allow coping with PhantomJS failing due to unsupported SNI

### ISSUE THREAD

**Issue by advancingu** [meteor/meteor#1837]
This issue refers to https://github.com/ariya/phantomjs/issues/11239 where it is described that PhantomJS currently does not support [Server Name Include](https://en.wikipedia.org/wiki/Server_Name_Indication). Executing PhantomJS via spiderable on a host with SNI and where http is automatically redirected to https, the result is always that PhantomJS fails.

A workaround for PhantomJS is to set the parameter ``--ignore-ssl-errors=true``, however Spiderable currently does not permit specifying this parameter anywhere.

**Comment by glasser** [comment]
As mentioned above, you can configure this with `$METEOR_PKG_SPIDERABLE_PHANTOMJS_ARGS`.
