### ISSUE TITLE
[blaze] Shouldn't require <li> to be closed with </li>

### ISSUE THREAD

**Issue by jagill** [meteor/meteor#1842]
***1 Upvote*** Shark compiler dies on an unclosed `<li>`:

```
<ul>
  <li>The first item
  <li>The second item
</ul>
```

leads to

```
client/views/plans.html:10: Expected "li" end tag, found "ul"
... The second item </ul>
```

But according to the HTML5 spec, `<li>` can be unclosed if followed by another `<li>` or it finishes the `<ul>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

This was observed at the head of shark branch, currently 1d24565fb5ed6a5571cd6c037f1a60a092be8eaa

**Comment by stubailo** [comment]
Digging this up from the grave, but -1 for "strict" parsing. We should pick a real language definition like HTML5 and stick with it. If that means you can omit closing tags for your `<p>` tags, so be it. Template compiler !== linter, and I bet people wouldn't be very happy if our JavaScript compiler didn't support `==` or omitting semicolons.

**Comment by dgreensp** [comment]
I had the same point of view when we shipped it.  However, most people seem to actually prefer the strictness.

**Comment by dandv** [comment]
Lack of closing `</li>` is actually valid HTML5, so -1 as well.

Not sure *when* this would be an actual problem though. Maybe with HTML generated by 3rd party tools?

**Comment by mitar** [comment]
I am closing this in favor of strict HTML. Blaze is a special language which looks like HTML and I think it is good that it has stricter semantics than HTML. We want to catch much more bugs than what HTML allows. (React is even stricter, requiring `<tr>` tor example to be part of `<tbody>` and things like that.)
