### ISSUE TITLE
To handle IE9, I need to have Meteor NOT concatenate the css files

### ISSUE THREAD

**Issue by patmoore** [meteor/meteor#1876]
IE9 has a 4095 selectors / stylesheet limit. ( you can read a little bit about that here : http://stackoverflow.com/questions/9906794/internet-explorers-css-rules-limits ). Once that limit is hit, the rest of the styling rules are silently ignored. (thank you Microsoft employees for not even bothering with an error message to console)

I would like a clean solution from the Meteor community on how to have Meteor serve the original css files (minimizing is o.k. but not concatenated) to IE9-.

We are doing a temporary hack of asking user to upgrade but that seems really lame since the solution is "simply" get Meteor to not concatenate the css files.

see also : http://stackoverflow.com/questions/22117069/to-handle-ie9-i-need-to-have-meteor-not-concatenate-the-css-files

bug report filed per request by: http://stackoverflow.com/users/1626821/imslavko and http://stackoverflow.com/users/1007676/dave

**Comment by d4nyll** [comment]
Any update on this issue? Would it be much trouble if during the build, we generate ie9-specific CSS files, split it into chunks which fits the 4096 selector limit, ***but only if required***, and then add a HTML conditional comments ***if required*** so IE9 will load that CSS, and the rest will not bother with it.

And if this is not an issue, then the IE9 CSS won't be generated in the build, and conditional comments won't be in the final HTML.

Not looked much into it, but [this script](https://gist.github.com/psebborn/1885511) might be useful. There's also [this website](http://snippet.bevey.com/css/selectorCount.php).

**Comment by MiroHibler** [comment]
Hey @patmoore, are you using Iron.Router? If you do, would it be possible to manually split your CSS per routes? Than you'd be able to lazy-load them with [preloader](https://github.com/MiroHibler/meteor-preloader).

Not exactly what you're looking for, but may help...

**Comment by havays** [comment]
I used two CSS files and meteor doesn't concatenate them, for this i have created separate package which injects the CSS file, placed in public folder, directly into the head tag.
Below is the snapshot of the code:  

var head = document.getElementsByTagName('head')[0];

//Generate a style tag
var style1 = document.createElement('link');
style1.type = 'text/css';
style1.rel = "stylesheet";
style1.href = '/style1.css';

head.appendChild(style1);

**Comment by lassombra** [comment]
What is the status of this?  Meteor claims to support IE 8/9 but this is clearly a case of broken support.

**Comment by Slava** [comment]
Presumably the change proposed [here](https://meteor.hackpad.com/Proposal-New-phases-for-the-build-process-KQ8jqchouGs) will help.

**Comment by patmoore** [comment]
@MiroHibler Would preloader work to provide a print only css?
