### ISSUE TITLE
Storing custom EJSON in mongodb only sort of works

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#1890]
From what I can tell, the only reason mongodb throws a `not okForStorage` error when attempting to insert a custom EJSON type is because the keys begin with "$". But I don't see any good reason why Meteor needs to use "$" instead of any other unusual character. If [these lines](https://github.com/meteor/meteor/blob/f3b5aacb0dfc384249b4ab9353b5c4cd49e59c66/packages/ejson/ejson.js#L106) are changed to use `!type` and `!value`, for example, mongo does not have a problem. I think some other random places in the codebase would need changes, too, but not many.

If you change all outgoing code to use "!" and change all incoming code to recognize "!" or "$", this would be backwards compatible.

**Comment by xbtsw** [comment]
With meteor 1.1 supporting Mongo 3.0 & 2.6 is this considered fixed?

**Comment by glasser** [comment]
Yes, this seems to work as of Meteor 1.0.4 (or well, any use of Mongo 2.6 or newer).
