### ISSUE TITLE
Expose an API that can disable automatic resume logins 

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#1891]
It seems that earlier versions of Meteor had a semi-public API for preventing the resume login from being called automatically: https://github.com/possibilities/meteor-disable-auto-login.

This no longer works, because the global `enableAutoLogin` variable in `accounts-base` is not exposed in any way. However, this is unfortunate because smart packages may want to disable the resume login in certain cases. In particular, I have a package that authenticates users from Amazon Mechanical Turk (https://github.com/HarvardEconCS/turkserver-meteor) where users have short sessions and should not be able to log in to the app afterward. Before, I just didn't store the resume token for users (#1835), but that no longer seems to work, so I'd like to disable the resume login on the client side when the app is loaded with a specific URL/hash fragment. 

In general, it seems like `accounts-base` should be refactored to not include functions that are specific to `accounts-password` (https://github.com/meteor/meteor/blob/devel/packages/accounts-base/url_client.js). This would also allow other packages that deal with accounts to disable the resume login in certain cases.

Possibly related: #1815, which would allow handling this issue from the server side.

**Comment by lorensr** [comment]
Note for people finding this – when you use `Accounts.registerLoginHandler`, a resume token is **not** created by default, so once you refresh the browser or lose the connection, you will be logged out. 

If you'd like, you can add a resume token yourself. See the last section of this:

https://meteorhacks.com/extending-meteor-accounts/

**Comment by mizzao** [comment]
@lorensr that's interesting - I don't think that was always the case. Do you know off the top of your head which version of Meteor this started in?

**Comment by lorensr** [comment]
Oops, I'm sorry – article was written a while ago. The repo uses Meteor `0.6.3.1`. From the comments, it looks like that was before the point at which resume tokens started being created automatically. I assume they still are. What's the way you used with login hooks to login without resume tokens?

**Comment by mizzao** [comment]
I'm not sure it's possible; I just added logic to pull login tokens on certain disconnect/logout events.

**Comment by lorensr** [comment]
I see, thanks. My use case is a OTP link giving restricted access to your account for the duration of your session. I don't want to remove all login tokens (which would log them out of their full-access browsers) – just the one created during restricted login. I guess I'll do a `setTimeout` at the end of the `registerLoginHandler` that removes all `resume.loginTokens` with a recent `when` (will usually just be one such).

**Comment by lorensr** [comment]
This works as a connection-specific login:
```javascript
// client
Meteor.call('connectionLogin', function(e,r) {
  if (!e)
    Meteor.connection.setUserId(userId)
})

// server
Meteor.methods({
  connectionLogin: function() {
    this.setUserId(userId)
  }
})  
```
Are there any downsides to doing it this way, other than having to configure your own rate limiting?
