### ISSUE TITLE
Issue testing collections because there is no way to unregister them

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1919]
I have issues doing tests in my [package](https://github.com/peerlibrary/meteor-peerdb) because there is no way to unregister collections. So when tests create temporary collections, they fail the second time because collections are already defined. There should be a way for collections to be cleaned up (or that should be done automatically between tests reruns).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Issue%20testing%20collections%20because%20there%20is%20no%20way%20to%20unregister%20them&body=Migrated%20from:%20meteor/meteor%231919) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
