### ISSUE TITLE
Better OAuth error messages

### ISSUE THREAD

**Issue by piffie** [meteor/meteor#1920]
Hi,
I'm currently tracking an error, where Facebook logins are not working.

I still do not have a solution, but i have some suggestions already.

in the /packages/accounts-oauth/oauth_client.js line 12
you are reporting only the error.details back in the error Object.
but my object does not have details. just the rest.

This is my error Object in this line: 

```
 details: undefined
 error: 145546287
 errorType: "Meteor.Error"
 message: "No matching login attempt found [145546287]"
 reason: "No matching login attempt found"
```

So please, if error.details is undefined, return the message or the reason. 
thanks

**Comment by vaidyaanand** [comment]
I am also having same problem in my app but I am able to understand why it is happening

**Comment by abernix** [comment]
@vaidyaanand Based on the timing here, you're very likely experiencing the problem mentioned in #8534.

**Comment by vaidyaanand** [comment]
@abernix Thanks! you save my day. I have updated plugin and it is working fine now
