### ISSUE TITLE
When you open a crashed app, it does not reload on file change

### ISSUE THREAD

**Issue by Lobosque** [meteor/meteor#1924]
```
Your app is crashing. Here's the latest log.

=> Errors prevented startup:

While building the application:
input: Less compiler error: '../crashplease/constants.less' wasn't found

=> Your application has errors. Waiting for file change.
```

When an app crashes, it says it is waiting for a file to change, but when you change a file (even when your change stops the server from crashing) it doesn't reload.
I'm not sure if the client is really supposed to watch for file changes in this scenario, but if it's not, the message should be changed.

**Comment by glasser** [comment]
(Classifying this as "tool" because the "build error" page is generated by the tool, in run-proxy.js)

**Comment by stubailo** [comment]
#4873 is going to fix this!

**Comment by stubailo** [comment]
(https://github.com/meteor/meteor/pull/4881 is the new PR)

**Comment by hwillson** [comment]
I'll close this off since the activity/interest on this issue has been quite low over the past 2 years (and the 2 related PR's created to address parts of this issue have also been closed without being merged, and no one seems to mind). Thanks for originally reporting this issue!
