### ISSUE TITLE
[Blaze] Spacebars no longer supports block helpers around attributes

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#1930]
{{#unless status_time}}style="display: none"{{/unless}}

The above statement works in Handlebars, but has to be adjusted to:
 style={{#unless status_time}}"display: none"{{else}}""{{/unless}}

To work with spacebars.

The same holds true for {{#if}} and other tags.

The error generated is:
"Reactive HTML attributes must either have a constant name or consist of a single {{helper}} providing a dictionary of names and values.  A template tag of type BLOCKOPEN is not allowed here."

**Comment by tlianza** [comment]
That solution for "checked" doesn't work for things like HTML5's "required" which don't have a "falsey" syntax.  Any other solutions? Or, do we need to write all form fields twice for this?

**Comment by dgreensp** [comment]
`required` is like `checked`.  To make it false, you omit it.  There are a few ways of achieving this reactively in Blaze.  `<input required={{x}}>` will omit the attribute if x returns false, undefined or null.  You can also write `<input {{x}}>` where x reactively changes between "required" and "", or a dictionary of attributes and values.

**Comment by tlianza** [comment]
Thank you @dgreensp ! I guess I'm stumbling on a different issue.  I was writing code like this: `{{#unless x}}false{{/unless}}` because I had one boolean (`x`) that I wanted to use to make some fields required, and some fields not.  And, since spacebars doesn't seem to support a syntax like `{{!x}}` that's why I was writing it that way. So... is the workaround that you need to add a helper that provides another value `y` even if `y` is as simple as `!x` so that you can write templates in this way?

**Comment by dgreensp** [comment]
To make it required when x is true, `required={{x}}`.  To make it required when x is false, `required={{#unless x}}true{{/unless}}`.  I don't know where `{{#unless x}}false{{/unless}}` enters into it!

In general, though, you may need to define helpers for even simple expressions (though we are talking about adding expressions to the template language in the future).  If you want, you could register a global helper named `not` using `Template.registerHelper` and write `{{not x}}`.

**Comment by tlianza** [comment]
Thank you so much for the fantastic answer. And, sorry about the head-slap around that boolean logic example. That was indeed a bad example, and your general explanation helps cover the more realistic ones.

**Comment by dgreensp** [comment]
No prob!

**Comment by aviemet** [comment]
Any suggestions for conditionally setting which `<option>` is has a `selected` attribute? That attribute is not intended to have a value

**Comment by bmcgonag** [comment]
So, I understand what you guys are saying, but when I try `checked = {{myValue}}` which is true or false, the checkbox is always checked regardless.  A checkbox simply has an attribute of 'checked' or it doesn't as far as I can tell. 

So, how would I design my helper to fix this?
