### ISSUE TITLE
Meteor.status() not reporting correctly under OSX Chrome

### ISSUE THREAD

**Issue by nilnullzip** [meteor/meteor#1942]
I am finding that Meteor.status().status does not appear to be reported correctly under OSX Chrome. With all other clients I have tried (OSX Safari, IOS, and Android) when the network connection is lost, the change is immediately shown in Meteor.status().status. But with OSX Chrome, the status continues to indicate "connected" for ~45 seconds, after which it finally reports "waiting." I am using the latest OSX and Chrome releases. 

The behavior can be reproduced easily here:

> http://meteor-chrome-status-problem.meteor.com/

Visit this page to see Meteor.status().status reporting "connected". Then turn off your network connection. Compare behavior with mobile vs OSX Chrome.

Thanks!
-Juan

**Comment by almogdesign** [comment]
I'm having the same issue, always getting  Object {status: "connected", connected: true, retryCount: 0}

**Comment by laddi** [comment]
I'm also having this problem with an app.  Start it up, do some calls, and then restart it will trigger this exact behaviour, will report that the status is "connected" but will fail on all attempts at connecting the server (Meteor.call).

**Comment by vinaynb** [comment]
@nilnullzip as its now almost a year since the last update to this thread, did you in any way manage to solve this ?

I face the same issue right now, Meteor waits for 60 seconds to report offline connection.
