### ISSUE TITLE
Input is not preserved

### ISSUE THREAD

**Issue by felixrabe** [meteor/meteor#1969]
Repo: https://github.com/felixrabe/meteor-does-not-preserve-input-bug

Context:
- Meteor is running (OS X)
- Browser window (Chrome on OS X)
- Wrote some input into input box
- Input box has focus
- Code is changed by developer

Expected behavior:
- After automatic page refresh triggered by the code update, input box content and cursor position / selection remains the same as stated in the documentation

Actual behavior:
- After automatic page refresh triggered by the code update, **input box content is lost, contradicting the documentation**

**Comment by dandv** [comment]
Preserving the inputs on HCR would be a nice feature to have. Should I file a new feature request issue, or could this issue be reopened?

**Comment by glasser** [comment]
Yeah, file a feature request, now that we accept them.
