### ISSUE TITLE
Using data as a helper name should have a warning

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#1984]
If you do this

test.html

```
<body>

{{with values
    {{>xxx}}
{{/with}}

</body>

<template name='xxx'> {{what_is_}} </template>
```

client/test.js

```
Template.xxx.helpers({
   data: function() {
       return [] //No data at this time
  },
  what_is_: function () {
    console.log(this); //Wait what? it should say {value: 'this is data'}
  }
});

Handlebars.registerHelper('values', function() {
    return { value: 'this is data' }
});
```

`{ value: 'this is data' }` is expected, whereas `[]` is returned instead, which is a bit weird.

The issue above occurs with 0.8.0 (Using Blaze). With Spark it works as expected (tried on 0.7.2)

Perhaps a **[word] is a reserved word** warning could be used when defining helpers that extend themselves onto the Template.x when they already exist.

**Comment by hwillson** [comment]
I've confirmed the original problem mentioned in this issue is no longer happening with the current version of Blaze (2.1.9), and the extra issues mentioned have been addressed by deprecating `Template.foo.helperName` syntax. This issue can be closed - thanks!

**Comment by abernix** [comment]
Thanks, @hwillson.
