### ISSUE TITLE
Using UI.elseBlock throws an error when there is no else section in referencing the block helper

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#1996]
In Handlebars previously it was possible to use an if/else block helper without specifying the else part, and the rendering of this condition would just be empty. For example, I had this `#withif` helper:

``` coffeescript
Handlebars.registerHelper "withif", (obj, options) ->
  if obj then options.fn(obj) else options.inverse(this)
```

It was fine to use this without defining the else portion, like

```
{{#withif doc}}
    {{> doSomethingWith fooField}}
{{/withif}}
```

Trying to replicate this with the following Blaze template 

```
    {{#if this}}
        {{#with this}}
        {{> UI.contentBlock}}
        {{/with}}
    {{else}}
        {{> UI.elseBlock}}
    {{/if}}
```

now results in the error

> Uncaught Error: Expected null or template in return value from inclusion function, found: undefined 

...in spacebars-runtime.js:36. It would seem reasonable to have the UI.elseBlock be a no-op when rendered instead of throwing the error, to mimic the prior behavior. See this stackoverflow question for more details: http://stackoverflow.com/q/22792076/586086

**Comment by hwillson** [comment]
Seems to be fixed - closing - thanks!
