### ISSUE TITLE
meteor run doesn't pass the value of METEOR_SETTINGS to the server or client

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#2005]
`meteor run` parses the METEOR_SETTINGS environment variable, but doesn't store its value in `Meteor.settings`.

Reproduction:

``` sh
git clone git@github.com:dandv/meteor-settings-env-var-broken.git
cd meteor-settings-env-var-broken
meteor --settings=settings.json
```

Output:

```
[[[[[ ~/meteor-settings-env-var-broken ]]]]]

=> Started proxy.
=> Started MongoDB.
I20140403-01:50:09.205(-7)? { public: { foo: 'bar' }, private: 'secret' }
=> Started your app.
```

Now run `METEOR_SETTINGS=$(cat settings.json); meteor`, which will output an empty object. How do we know Meteor does still parse METEOR_SETTINGS but just doesn't store the value in `Meteor.settings`? We can bungle up the environment variable:

`METEOR_SETTINGS=$(cat settings.json; ls); meteor`

```
[[[[[ ~/meteor-settings-env-var-broken ]]]]]

=> Started proxy.
=> Started MongoDB.
Errors prevented unipackage load:
While loading unipackage:
packages/meteor/server_environment.js:31: Settings are not valid JSON
  at packages/meteor/server_environment.js:31
```

It would be great if Meteor adopted standard config file passing for the deployed app as well (#1116).

**Comment by tgoorden** [comment]
Some deployment environments (e.g.) currently simply do not support the `--settings` command line option and instead relied on the `METEOR_SETTINGS`. This effectively makes certain normal things impossible.

**Comment by glasser** [comment]
`--settings` is part of the development-mode runner, which runs your app in various ways that are inappropriate for production (eg, showing internal stack traces over HTTP, running everything through a proxy, etc).

**Comment by tgoorden** [comment]
OK, but then how to get Meteor.settings configured otherwise? What's the alternative mechanism if neither `--settings` or `METEOR_SETTINGS` is appropriate? We use this a lot for e.g. secret keys and appId's, that simply *have* to be loaded at client start.

**Comment by tgoorden** [comment]
(Incidentally, it's possible to use `--settings` with `meteor deploy`, which is not development mode, right?)

**Comment by glasser** [comment]
Use `--settings` in development using the dev-mode runner.

Use `METEOR_SETTINGS` in production, where you should be running the tarball produced by `meteor build`, not the dev-mode runner.

If you found any documentation from MDG encouraging you to use the dev-mode runner in production, I'd love to know where it is so I can fix it!

We're aware that current deployment practices for Meteor aren't ideal, which is why 'managed production-quality "meteor deploy"' is in the Present column of https://roadmap.meteor.com/

**Comment by tgoorden** [comment]
Here:
https://github.com/phusion/passenger/wiki/Phusion-Passenger:-Meteor-tutorial#development_vs_production_mode

They offer two options:

* Upload the app directly (this is where it definitely breaks).
* Build it and then unzip the tarball on the server. Now, I've noticed the contents of a build are very different, so not sure how the whole thing would react.

In neither cases is there any other option than to use `METEOR_SETTINGS`.

**Comment by glasser** [comment]
We don't support these Phusion Passenger installation instructions.  If they are offering "production" hosting of Meteor that runs the dev mode runner, they should probably fix that.

**Comment by stufa00** [comment]
If you don't like specifying settings in settings.json or in METEOR_SETTINGS, you can also specify them in your code like this (e.g in /settings.js file) : 

Meteor.settings = {
    public : {
          foo:'bar'
    }
}

**Comment by jononomo** [comment]
I don't want to set the MONGO_URL as an environment variable because I develop many different meteor projects, all of which use a different MONGO_URL.  But if I can't put MONGO_URL in my settings.json, then what can I do?

**Comment by kentonv** [comment]
@jononomo - This is offtopic, but FWIW you can set an environment variable for just one command by putting the assignment on the same line, before the command:

    MONGO_URL=mongodb://xxxxxxxxxxxxxxxxxxxxxxxxxxx meteor

You can of course write a little shell script to wrap this if you get sick of typing it.

(This all assumes a Unix shell; no idea about Windows.)

**Comment by jononomo** [comment]
@kentonv thanks so much
