### ISSUE TITLE
How to render a template to HTML with data

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#2007]
There's no API call at the moment to render a template to an HTML string with data, which of course used to be quite easy before version 0.8.

Until this is remedied, you can use this parallel function to `UI.renderWithData`:

```
var toHTMLWithData = function (kind, data) {
  return UI.toHTML(kind.extend({data: function () { return data; }}));
};
```

Note that `kind.extend` uses an internal API that may change.

**Comment by mitar** [comment]
Shouldn't this be closed? There is `Blaze.toHTMLWithData` now?

**Comment by dgreensp** [comment]
Good call, thanks.

**Comment by paulbalomiri** [comment]
?
