### ISSUE TITLE
Template.body.events({'keyup': ... }) doesn't work

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#2024]
Hi hi,
None of the keybinding events seem to be working on the UI.body template in Blaze.

``` js
UI.body.events({
  'keydown': function(){
    alert('keypress!');
  }
});
```

Medium-low priority, but would be nice to have all the events supported on the UI.body template.  Page-wide keybindings are a very useful thing!  :)

**Comment by keyscores** [comment]
I'm having issues getting UI.body.events, and UI.body.rendered to work. Is it Iron Router that is conflicting with this?

**Comment by PeppeL-G** [comment]
@keyscores, you're using the latest version of Meteor? Nowadays, it is called `Template.body` instead of `UI.body`, and according to [the docs](http://docs.meteor.com/#/full/template_body), you can only define helpers and event maps to it :S

**Comment by Booseink** [comment]
following

**Comment by keyscores** [comment]
My message was from April/2015, before Meteor 1.2 I can test if that would be helpful.

**Comment by keyscores** [comment]
@abernix following up nealy a year later. It would be nice if the Docs could clarify how this is done. With an up-to-date meteor the issue persists. 
Template.body.events , doesn't seem to initialize ANY listeners if you have nested templates. I also can't find Meteor's tests for this functionality.

**Comment by abernix** [comment]
@keyscores Thanks for bringing this up.  Let's try to get this resolved.  Any tests that might have existed for it would be probably in the [Blaze repository](https://github.com/meteor/blaze) now.

But honestly, I see no reason why this would be a part of Blaze or Meteor (or React, for that matter).  A `scroll` or `keydown` event or anything like this is realistically a browser event – anything that did exist in Blaze would just be a proxy to that.  It seems like it should be done with `document.addEventListener('scroll', ...`, (or jQuery, if you so prefer) as I believe it is done with React as well, if I'm not mistaken?

But ultimately, yes, this should be documented.  Do you mind looking through the [Meteor Guide](http://guide.meteor.com/), finding a place where this explanation would be helpful and opening an issue (or even better, a PR!) about it?

**Comment by hwillson** [comment]
This issue has been moved to meteor/blaze#214 - closing here. Thanks!
