### ISSUE TITLE
Need a way to stop reactive updates on a template

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2031]
(Originally reported by @tmeasday) Sometimes apps want to explicitly opt-out of the automatic page updates.

This is also related to #2023 -- right now there's no way to stop Deps computations that control live updates on a template. This introduces memory leaks and degraded performance over time (unless you always use jQuery to remove elements).

**Comment by MattiSG** [comment]
> 1. Are you trying to render a template that's reactive at first, and then at a later time stop its reactivity? I find it hard to come up with a use-case for this.

My use-case is pre-filling a `<textarea>`'s `value`, but avoiding losing user input due to latency on autosave. If the `value` is both the input and output of data, then latency on `update` make the latest keystrokes disappear.

**Comment by hwillson** [comment]
I've created meteor/blaze#147 to track this moving forward. This issue can be closed.

**Comment by mitar** [comment]
Thanks!
