### ISSUE TITLE
Easy way to escape `{{` in Spacebars

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#2052]
Problem: It's hard to escape `{{` in Spacebars.  Backslash would be an option, but then how do you escape a backslash?  Having an easy way to write a literal `{{foo}}` would make it much easier to talk about Spacebars in a Spacebars template.

Our idea is `{{|` expands to a literal `{{`, and `{{{|` expands to a literal `{{{`.  (That's a vertical bar.)  So `{{|foo}}` is a literal `{{foo}}`, and `{{||foo}}` is a literal `{{|foo}}`.

Just needs to be implemented.

**Comment by jagi** [comment]
Hi, it would be good to add documentation for it in the Spacebar's [README](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md)

**Comment by dgreensp** [comment]
Good idea.  Added a section: https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#escaping-curly-braces

**Comment by jagi** [comment]
That was fast :-) Thanks :-)
