### ISSUE TITLE
Automatically stop computations when template is destroyed

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2057]
When a template is destroyed, stop all computations (eg `Deps.autorun`) started in its created or rendered callback.

This work is being addressed as part of a component API rehaul which is in progress.

In the meanwhile, you have to keep track of computations and stop them manually, eg:
```js
Template.foo.rendered = function () {
  this.comp = Deps.autorun(function () { ... });
};

Template.foo.destroyed = function () {
  if (this.comp)
    this.comp.stop();
}
```

**Comment by mitar** [comment]
Should this ticket be closed?

**Comment by stubailo** [comment]
Yep!
