### ISSUE TITLE
Scaling issue with large collection

### ISSUE THREAD

**Issue by steveluscher** [meteor/meteor#207]
_Thanks to StackOverflow user [Lloyd](http://stackoverflow.com/users/1029644/lloyd) for [this question](http://stackoverflow.com/questions/11259796/template-keeps-redrawing-despite-no-change-to-the-underlying-data). I'm posting it here as an issue._

The rendered Live HTML in this example keeps clearing then redrawing, in an infinite loop. This example code maxes out the CPU on my laptop. **With smaller record sets (try 10 instead of 1000) the bug does not manifest itself.**

Environment:
- Meteor 0.3.7
- Mac OS Lion
- tested in Safari 5.1.7, Chrome Canary 22.0.1189, Chrome 21.0.1180, Firefox 11.0 & 13.0

initial project creation: 

```
meteor create test
cd test
meteor add coffeescript
mv test.js test.coffee
meteor
```

test.coffee: 

```
Records = new Meteor.Collection("records")

if Meteor.is_client
    Template.table.records = ->
        Records.find()
    Template.table.rowCount = ->
        Records.find().count()

if Meteor.is_server
    Meteor.startup ->
        if Records.find().count() is 0
            for i in [1..1000]
                Records.insert({some:"test#{i}", data: "just", to: "check"})
```

test.html:

```
<head>
  <title>test</title>
</head>

<body>
    {{> table}}
</body>

<template name="table">
    <table>
        <caption>{{rowCount}}</caption>
        {{#each records}}
        <tr>
            <td>{{some}}</td>
            <td>{{data}}</td>
            <td>{{to}}</td>
        </tr>
        {{/each}}
  </table>  
</template>
```

**Comment by AChusuei** [comment]
@glasser I am getting this same issue still with a very large Collection. What exactly was the solution for this? Or was there simply some sort of workaround?
