### ISSUE TITLE
minimongo seems to be have problems with $near

### ISSUE THREAD

**Issue by TimoRuetten** [meteor/meteor#2077]
When i use a mongoDb query on Server & Client Side the results are not the same.

Seems that minimongo does not support $near in the right way.

Repository to this problem:
https://github.com/Visudare/meteor-minimongo-bug

If you look at the results given in the browser console you can see that the client way of $near does not work. When searching on client with $near the result is 0 - everytime. The same searchquery on server side has 1 result.

**Comment by AnthonyAstige** [comment]
I believe I had the same problem demonstrated in [meteor-minimongo-bug](https://github.com/Visudare/meteor-minimongo-bug). I'm running Meteor 1.2.1 and Mongo 3.2.4. I patched for Meteor at https://github.com/AnthonyAstige/meteor/commit/a330e860d02513f698db5f6f2a75e515f1c39514.

I'm no pro in the minimongo code, haven't run tests, etc.  However I can send a pull request if desired.

## Problem code

Slightly modified for readability

I stored data like

```
loc: {
  x : -74,
  y : 41
}
```

And queried it like

```
var query = {
  $near: {
    $geometry: {
      type: 'Point',
      coordinates: [x, y]
    },
    // Convert [mi] to [km] to [m]
    $maxDistance: distanceInMiles * 1.60934 * 1000
  }
};
```

I would get results on the server, but never on the client.

## Other thoughts

I haven't tested this hypothesis, but it appears if I hacked my data as so my query code would have returned the same result set isomorphically.

```
loc: {
  type: "Point"
  x : -74,
  y : 41
}
```

With my patch there's still the ordering issues documented at https://github.com/meteor/meteor/issues/3599, but at least the documents returned are consistent for my use case.

**Comment by marfago** [comment]
I have the same problem as described by @AnthonyAstige but with minimongo@1.0.10.
The $near operator returns an empty collection while the same query executed on server returns not empty result.

**Comment by hwillson** [comment]
Hi @AnthonyAstige - I've taken a look at your suggested changes (https://github.com/meteor/meteor/issues/2077#issuecomment-203430061), and they make sense to me. Regarding:

> I'm no pro in the minimongo code, haven't run tests, etc. However I can send a pull request if desired.

Are you still interested in submitting a PR for this? If so I'll gladly help out where I can. Otherwise, let me know and I'll put a PR together for this. Thanks!

**Comment by AnthonyAstige** [comment]
@hwillson I've been out of the Meteor game for a few months, if you could put together a pull request that'd be great. Of course feel free to use the code I put together it looks like @ https://github.com/AnthonyAstige/meteor/commit/a330e860d02513f698db5f6f2a75e515f1c39514 Thanks~

**Comment by mutdmour** [comment]
@hwillson, I could work on this if you have not started as well as check for #3599

**Comment by hwillson** [comment]
By all means @mutdmour, that would be great! I got as far as creating a branch to start working on this last week, then left for vacation; I'm just getting back today and my mind is still completely in vacation mode. Your PR will be in better shape than mine would be, over the next couple of days 🙂. If plans change though let me know at any point, and I'll jump back on this. Thanks!

**Comment by mutdmour** [comment]
Thanks @hwillson. I will work on this.

**Comment by mutdmour** [comment]
This ticket should be closed.

**Comment by hwillson** [comment]
Thanks for the reminder @mutdmour, and the work on this! 🙂
