### ISSUE TITLE
Accounts-ui is inaccessible

### ISSUE THREAD

**Issue by Heydon** [meteor/meteor#2080]
Firstly, I just want to say what a relief it is to have an extension like `accounts-ui` that takes care of so much boring work for me as a developer.

Unfortunately, it's not as "out of the box" as I'd like since -- unless I've missed an update -- the buttons are unfocusable `<div>` elements and the links aren't focusable either (explanation below). This makes the UI completely inaccessible to keyboard users.

I _could_ hack the extension to render a more compliant template (and there are a couple of tutorials sort of covering this) but there's absolutely no reason why `<button>`s should not be used by default.

You could swap

```
<div id="login-buttons-password" class="login-button login-button-form-submit"> Sign in </div>
```

for

```
<button id="login-buttons-password" class="login-button login-button-form-submit"> Sign in </button>
```

with the minimum of effort.

The "forgot password" and "create account" links are also inaccessible by keyboard. Whoops! This is because removing `href` attributes make links non-focusable.

You could change 

```
<a id="signup-link" class="additional-link">Create account</a>
```

to

```
<a id="signup-link" class="additional-link" href="#null">Create account</a>
```

for instance. Not ideal "semantically" but infinitely better practically.

If you fix these in the core, then whenever anyone spins up any kind of Meteor app, it will be 100% more accessible. That would be pretty lush. 

Your guidelines state not to submit feature requests here. Keyboard accessibility should not, however, be considered a feature. This issue is a bug :-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Accounts-ui%20is%20inaccessible&body=Migrated%20from:%20meteor/meteor%232080) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
