### ISSUE TITLE
[blaze] The {{if}} parameter does not work when outputing a part of html

### ISSUE THREAD

**Issue by TimoRuetten** [meteor/meteor#2090]
Its a bit difficult to exlpain it, but the problem is, that it seems to be impossible to output just part of strings with {{if}}.

Simple example:

``` html

{{#each items}}
     {{#if smth}}
         <div class="row">
     {{/if}}
         <p>Some Content</p>
     {{#if smth}}
         </div>
     {{/if}}
{{/each}}

```

In my example "items" is an Array of objects and "smth" is a helper which returns true.

This template cant be rendered.
This error is what i get (on Server):

```
While building the application:
client/static/start.html:6: Unexpected closing template tag
...="row">          {{/if}}
```

**Comment by davidalonsobadia** [comment]
Anyone could solve this issue before with Meteor? I am exactly facing with the same problem and I don't wanna use JQuery to fix it..

Thanks
