### ISSUE TITLE
Error serving static file after hot code reload

### ISSUE THREAD

**Issue by patrickleet** [meteor/meteor#2091]
After making changes, my app tries to hot code reload, and the server starts spewing these errors nonstop until I kill it, or make another code change. The app eventually crashes the browser as well.

Any ideas?

E20140429-01:13:41.969(-4) (webapp_server.js:404) Error serving static file Error: ENOENT, stat '/Users/pat/dev/plus-more/device/.meteor/local/build/programs/client/app/collections/stays.js'
E20140429-01:13:41.971(-4) (webapp_server.js:404) Error serving static file Error: ENOENT, stat '/Users/pat/dev/plus-more/device/.meteor/local/build/programs/client/app/client/app.js'
E20140429-01:13:41.972(-4) (webapp_server.js:404) Error serving static file Error: ENOENT, stat '/Users/pat/dev/plus-more/device/.meteor/local/build/programs/client/app/router/router.js'
E20140429-01:13:41.999(-4) (webapp_server.js:404) Error serving static file Error: ENOENT, stat '/Users/pat/dev/plus-more/device/.meteor/local/build/programs/client/app/client/main.js'

**Comment by cmeheut** [comment]
Hi, I have the same problem today but not on meteor.com server
Exactly same issue on my own ubuntu server. I tried meteor update, so I have the very last version
Thank you if you could give more explanation bout issue reason
