### ISSUE TITLE
.findOne() inside of .insert() callback fails on client when run in package testing framework

### ISSUE THREAD

**Issue by vsivsi** [meteor/meteor#2105]
This is probably going to seem like a super esoteric issue, but this issue emerged from a failing test case I have been pulling my hair out trying to write/debug in my own package., After too many hours spent, I've been able to simplify it all the way down to just Meteor core code... 

The setup: insert a document and then findOne it back by _id:

``` js
testColl = new Meteor.Collection("testColl");

if (Meteor.isServer) {
  testColl.allow({
    insert: function () { return true; }
  });
}

// Synchronous insert followed by findOne.
// This always works everywhere.  Groovy.
var _id = testColl.insert({ });
var doc = testColl.findOne({_id : _id});
console.log("Sync ID: ", _id, " doc: ", doc);

// Asynchronous insert followed by findOne in callback.
// This always works on server. Nice
// This works on client when run in an application. That's good.
// This FAILs when run on client within the Meteor testing framework. WTF?
_id = testColl.insert({ }, function (err, retid) {
    doc = testColl.findOne({_id : retid});
    console.log("Sync ID: ", _id, "Async ID: ", retid, " doc: ", doc);
});
```

Okay, so here's what my TinyTest code for the second case above actually looks like:

``` js
Tinytest.addAsync('insert and findOne in callback', function(test, onComplete) {
  // testColl is already defined by package under test
  var _id = testColl.insert({ }, function (err, retid) {

    if (err) { test.fail(err); }
    test.equal(retid, _id, "findOne returned bad _id to callback");

    var doc = testColl.findOne({_id : retid});
    // This always passes on server
    // This always FAILS on client!!!  doc is in the database on server
    test.notEqual(doc, undefined, "findOne returned no result.");
    onComplete();
  });
  // A findOne() call here will always succeed, it only fails inside the callback above.
});
```

Reproduced here: https://github.com/vsivsi/TTT

If you go to the TTTtest subdir, you will find a meteor app that uses the package at the root of this project.  Everything works there in "app space".

If you run this from the project root, and load localhost:3000 in your browser, you should see the client failure on the async case:

```
 meteor test-packages ./
```

Am I doing something wrong here??!  This sure seems like a bug in the test framework, but I can't believe the core devs wouldn't have run into this...

**Comment by arjunrajeev52** [comment]
old id return on this format
{_isScalar: false}
