### ISSUE TITLE
`Google.retrieveCredential` should take a secret.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#2118]
Google OAuth credentials are stored with a secret, yet https://github.com/meteor/meteor/blob/devel/packages/google/google_server.js#L81-L83 doesn't take a secret as an argument.

**Comment by keslert** [comment]
@tmeasday This method no longer exists. What is the recommended way for retrieving the credential secret now?

**Comment by whitebeatle** [comment]
@tmeasday <code>OAuth._retrieveCredentialSecret(token);</code> for twitter is returning null. This worked when i used it for github and trello though. Could you help me with that? here is <a href="https://github.com/meteor/meteor/issues/4914#issuecomment-150820156">more</a>
Thanks!
