### ISSUE TITLE
Meteor.onExit?

### ISSUE THREAD

**Issue by MichaelABarger** [meteor/meteor#2167]
I've noticed the onExit callback registration function available in cleanup.js (https://github.com/meteor/meteor/blob/1bd0d4764a9ed8909d44b02871b55a0d440ace57/tools/cleanup.js) . Is there any way to reach this functionality from a normal Meteor program? If not, wouldn't it be a good idea to include this as a natural pairing to Meteor.Startup? Thank you.

**Comment by JorritPosthuma** [comment]
Because overriding process.on('SIGTERM') also kills restart functionality, I needed another solution. This is a hacky solution that works for now:

```coffeescript
cleanup = Meteor.npmRequire process.env.OLDPWD + "/tools/cleanup.js"
cleanup.onExit -> # Do something
```

**Comment by AlexFrazer** [comment]
Interested in this as well.

**Comment by Jimmer-Ball** [comment]
Following on from JorritPosthuma

So, with the version of Meteor as at Jan 2016 which uses meteor-tool version 1.1.10, I could add a termination function with something horrible like the following from within an isServer block in your main entry point

```javascript
  function addExitFunction(exitFunction) {
        var nodeExePath = process.execPath;
        var stripMe = Path.sep + 'dev_bundle' + Path.sep + 'bin' + Path.sep + 'node.exe';
        var rootPath = nodeExePath.replace(stripMe, "");
        var addMe = Path.sep + 'tools' + Path.sep + 'tool-env' + Path.sep + 'cleanup.js';
        var meteorShutdownJsScriptPath = rootPath + addMe;
        var cleanup = Npm.require(meteorShutdownJsScriptPath);
        cleanup.onExit(exitFunction);
    }
```
Just pass in a function. For example I've been using it to pass in a function that does a little bit of housekeeping and Winston logging of when the server goes down.

Obviously its very brittle, but it might help you out, and yes you shouldn't expect the server not to crash at any point in time, but whatever.

**Comment by Jimmer-Ball** [comment]
Getting this to work with a version of the app created with "meteor build" is another issue.  Am currently struggling to figure out the right place to look for this clenup utility when running in packed form against Node v0.10.40

**Comment by Ragsboss** [comment]
+1 we also need a way to execute code on server exit.

**Comment by Dev1an** [comment]
The code from @Jimmer-Ball is not working anymore in Meteor 1.6-beta.9
Anybody else experiencing this problem?

**Comment by TheGame2500** [comment]
@DenisGorbachev sorry to bug you, but can you guys please look into a way to enable `process.on('SIGTERM')` or `process.on('SIGKILL')`. I can't seem to hook into the events, and @Jimmer-Ball 's solution never worked for me, although it looks hacky enough to be picky about the environments it works in.

**Comment by totalvm** [comment]
I would like a solution as well, I deploy a new version almost daily and having to manually set some if the database entries when doing so is not nice.

**Comment by datacarl** [comment]
For anyone still coming here this might be useful https://github.com/meteor/ddp-graceful-shutdown
