### ISSUE TITLE
Meteor.defer() not in docs?

### ISSUE THREAD

**Issue by michael-mccrickard** [meteor/meteor#2176]
***1 Upvote*** Checking the page:  docs.meteor.com and I am unable to find the term 'defer' anywhere.  Someone on stackoverflow just helped me solve a fundamental problem that I was having with iron-router and meteor by using Meteor.defer().  I had never heard of this function until then!

**Comment by KrishnaPG** [comment]
Which is the recommended one? `Meteor.defer()` or `Meteor.setTimeout()`.

Looking for a way to handle `DOM ready / document loaded` events (Required by some external JS files)

**Comment by glasser** [comment]
We now do track doc [feature requests](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests) so I'll reopen this.  Pull requests to improve our docs are always welcome!

@KrishnaPG I don't think either of those functions responds to DOM ready.  You can use `Meteor.startup` for that though!

**Comment by keyscores** [comment]
Seems like this is a similar issue as this: https://forums.meteor.com/t/template-layout-rendered-cannot-initialize-jquery-components-for-sub-templates/2706/2

How should we use .startup or .defer in this case

**Comment by tcastelli** [comment]
+1 would be interested to know how to use startup in a similar context. Should we check the loaded template/url in a meteor startup function and then start the things?

**Comment by fightingtheboss** [comment]
Although I'm aware of `Meteor.defer`, I actually came across a situation where this would have easily solved my issue (and ultimately did!) and it would've definitely jogged my memory if it were part of the docs. I can try to make the time to contribute a pull request adding it to the docs if they're being accepted for documentation.

**Comment by michael-mccrickard** [comment]
I use Meteor.defer() quite regularly.  Anytime I have an instruction in my code that doesn’t seem to execute and then I run that same instruction in the console and it works, I wrap it in my code with Meteor.defer() and that usually works.  Typically, it seems to be cases where something in the DOM that I’m depending on has not yet rendered.  You would think that “after” hook in iron-router would allow you to avoid this, but I find that method unreliable.

**Comment by rclai** [comment]
It has been pretty problematic trying to get third party libraries to initialize onRendered mainly on giant templates because even though onRendered runs, the actual target element hasn't completely rendered, and the initializing script runs prematurely. The workaround is to have those target elements inside a separate template with its own onRendered callback and do the initializing there.

**Comment by woniesong92** [comment]
@rclai, @michael-mccrickard I came across this issue trying to solve the exactly same problem as yours: http://stackoverflow.com/questions/31353120/run-a-function-after-dom-is-updated-from-a-helper-function/31353151 The problem is, `onRendered` only gets called once in the beginning and not called when the DOM is updaeted from a helper function.

**Comment by fuzzybabybunny** [comment]
Has anyone found a good way to initialize 3rd party scripts reliably when the DOM is fully rendered and all the DOM nodes are there? `Meteor.defer` is simply a way to start running something asynchronously (same a running it in a `setTimeOut` of `0ms`) and as such is at best a blunt way of controlling load order.

**Comment by KrishnaPG** [comment]
@fuzzybabybunny if starting 3rd party script is required (once the DOM is ready), I typically do it in `Template.onRendered()` method. It works in most cases.

**Comment by fuzzybabybunny** [comment]
@KrishnaPG, right, that's the standard practice. Unfortunately it gets out of hand very quickly if you have a page with a lot of partial template includes and the scripts needing to, say, wait for the DOM to be loaded on three out of ten partials. Meteor's design philosophy of not re-rendering certain templates makes it even more cumbersome to make sure scripts initialize correctly.

**Comment by zilev** [comment]
@glasser, sorry maybe you've already answered this, but continues not clear for me, you said:
```
We're aware that our docs are incomplete, especially for functions whose APIs may change before 1.0.
```
then is fact that "Meteor.defer" wont change? will it?
Thank in advance :smile:

**Comment by zilev** [comment]
Found this https://www.discovermeteor.com/blog/advanced-latency-compensation/ :smile:

**Comment by ferhtgoldaraz** [comment]
It seems to work on the client and server, but if I understand things properly, it's not exactly the same as `setTimeout(fn, 0)`. That would schedule a macro-task after at least 4ms, this schedules a micro-task.
Although if postMessage is not supported it *will* fallback to setTimeout

Here's something about the matter: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

And here is the meteor code I found that leads me to think this:

https://github.com/meteor/meteor/blob/master/packages/meteor/timers.js#L67
https://github.com/meteor/meteor/blob/master/packages/meteor/setimmediate.js

**Comment by mitjajez** [comment]
Found this http://justmeteor.com/blog/meteor-defer-and-this-unblock/ about Meteor.defer

**Comment by brajt** [comment]
Spring of 2016. Meteor.defer() still not in the docs.

**Comment by stubailo** [comment]
It's in there now!

**Comment by stubailo** [comment]
(As in, it's in the repo, and will be deployed next time we deploy the docs)
