### ISSUE TITLE
Seen this exception in the client log.

### ISSUE THREAD

**Issue by inikkor** [meteor/meteor#2177]
Been there for a few release. It doesn't seem to effect anything as far as I can tell

Uncaught SyntaxError: Unexpected token Y sockjs-0.3.4.js:2018
InfoReceiver.doXhr.xo.onfinish sockjs-0.3.4.js:2018
EventEmitter.emit sockjs-0.3.4.js:151
AbstractXHRObject._start.that.xhr.onreadystatechange sockjs-0.3.4.js:848

Using Chrome Version 35.0.1916.114 m on Windows 8

**Comment by TravisDart** [comment]
An explanation of this error is given in the [Unofficial Meteor Faq](https://github.com/oortcloud/unofficial-meteor-faq#uncaught-syntaxerror-unexpected-token-y):
> Client-side error caused by the server crashing and sending a message starting with "Your app is crashing. Here's the latest log."

Other references to this error:
http://www.telescopeapp.org/docs/customizing/troubleshooting/
https://gist.github.com/Multiply/998e8c5d70881c99d121

**Comment by RobertLowe** [comment]
@glasser this shouldn't be closed, I feel like there is a more elegant way to handle this... 

Could we perhaps catch it and retry would be more appropriate no? 

I think this confuses developers and spams error monitoring services...

**Comment by Slava** [comment]
This error message appears when your server process crashes and Meteor serves a page with console messages starting with "Your app is crashing ...". A "solution" would be to have a mini-ddp server that sends a message like "the app is crashing, refresh the page to display the error messages".

**Comment by RobertLowe** [comment]
@Slava exactly, I feel it should be "just" intelligent enough to understand that these errors happen from time to time (a missed colon for example) and recover or refresh once resolved. I'm not sure a "mini-ddp" is necessary, perhaps just a `try`/`catch` and handling appropriately...

**Comment by Slava** [comment]
@RobertLowe Feel free to propose things in a new issue in a form of concrete code changes.
