### ISSUE TITLE
SVG <a> tags don't work

### ISSUE THREAD

**Issue by zocky** [meteor/meteor#2178]
`<a xlink:href="..">` tags inside `<svg>` don't get recognized and created as SVG tags, they're created as HTML tags instead. 

Simply adding them to the list of known SVG tags in package htmljs "fixes" this, but not correctly, because it causes all HTML `<a>` tags to be created as SVG tags.

**Comment by fvpDev** [comment]
I just ran into this problem myself; So how do I update meteor to devel version?
