### ISSUE TITLE
Support `{{foo.0.bar}}` in templates

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2195]
Should do the same as `{{foo.[0].bar}}` does now. Used to work in Meteor prior to 0.8.0 (when we used the Spark rendering engine).

We'll take pull requests with good tests. See the spacebars-compiler package.

**Comment by jagi** [comment]
But shouldn't syntax like {{0.bar}} be correct? What about situation when current context is array and I want to get object under 0 index? Even if context is object then trying to get something under 0 index will return undefined if there is no 0 property. But objects can have numeric properties.

**Comment by hwillson** [comment]
This issue is now being tracked at meteor/blaze#197 - closing here. Thanks!
