### ISSUE TITLE
UglifyJSMinify step results in RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by scald** [meteor/meteor#2214]
My app works fine when running Meteor normally. But,

meteor bundle bundle.tar.gz
meteor run --production

both result in:

=> Started proxy.
=> Started MongoDB.  
=> Starting your app...
/Users/steve/.meteor/tools/5bf1690853/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
RangeError: Maximum call stack size exceeded

Is there a good way to debug where things might be going wrong?

**EDIT**
I have tried running meteor from a checkout and applying the diff mentioned in #2037, but no dice.

**EDIT**
So this is for sure an issue in the minifyJs step. See this diff in tools/bundler.js line 464

```
464c464
< self.minifyJs(minifiers);

---
> // self.minifyJs(minifiers);
```

Once I comment that step, things start working properly. 

**EDIT**
When I wrap the `UglifyJSMinify` call in a try/catch block, I can see that the error is originating there. I tried downgrading uglify-js back to 2.4.7 (packages/minifiers/package.js) but that didn't work either. @glasser are you tracking a potential bug in this step?

**Comment by ramsunvtech** [comment]
I've faced this same problem recently and came across to this thread but my problem was with `React` App Build in Webpack and Uglify bundle error. Below changes in the node build command solved my issues.

## Syntax
```
node --stack-size=<your-size> scripts/build.js
```

## Example
```
node --stack-size=1000 scripts/build.js
```

## Why size is 1000 in max-old-space-size?
Basically, it varies depends on the call stack of your current application scripts.

## How to verify and give right size?
This is basically stay in our engine `v8`. below command helps you to understand the Call stack Size of your local node v8 engine.

```
node --v8-options | grep -B0 -A1 stack-size
```
