### ISSUE TITLE
On browsers that don't allow/support LocalStorage, account logins should still work across multiple tabs.

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2223]
Filing this as requested by @avital.

When localStorage fails to work on a browser, [this shim](https://github.com/meteor/meteor/blob/devel/packages/localstorage/localstorage.js) is triggered, which uses tab-local in-memory storage. We could use cookies instead to store authentication information, which is how normal HTTP apps work. The cookie(s) would need to be aware of distinct DDP connections.

See also: #1291, #1688, #2204. There is more than one way to reproduce this, such as with certain settings in IE and iOS Safari private browsing mode. I'll follow up on this issue with my own tests, but for now here are ways to trigger this in different browsers: http://stackoverflow.com/q/6600754/586086 and https://gist.github.com/splorp/776730.

There's also a really interesting discussion of how localStorage behavior should manifest in different browsers at http://blog.whatwg.org/tag/localstorage.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by stubailo** [comment]
Which browsers are these? As far as I know, all browsers that we support work with localStorage. On other browsers, there will be hosts of other issues. Going to close this issue since it doesn't seem efficient to add features targeting browsers we don't support.

**Comment by mizzao** [comment]
Hi @stubailo, see the links in the OP. Certain configurations on IE and Safari disable LocalStorage (i.e. the corporate network at Microsoft) which means that Meteor doesn't work as expected across multiple tabs. @avital just suggested that I post this as an issue.

Close if you must, but I don't mind - IE is actually super convenient for testing an app masquerading as several users at once.
