### ISSUE TITLE
Better Python DDP Client

### ISSUE THREAD

**Issue by hharnisc** [meteor/meteor#2228]
I'm working on this:

https://github.com/hharnisc/PythonDDPExperiment

I don't think modifying your code and generating a pull request is the right way to go since this could be a nice package to throw up on pypi.

I'm close to having something that's usable, but I've had some issues with the SRP key exchange. Any help would be awesome!

**Comment by dandv** [comment]
Has SRP been deprecated since this discussion took place a year ago? I still see it installed when I `meteor add accounts-password`:

```bat
> meteor add accounts-password      
                                                     
Changes to your project's package version selections:
                                                     
accounts-password  added, version 1.1.1              
email              added, version 1.0.6              
npm-bcrypt         added, version 0.7.8_2            
sha                added, version 1.0.3              
srp                added, version 1.0.3              
```

**Comment by glasser** [comment]
As you can see for yourself by searching for its export `SRP`, `accounts-password` still contains backwards-compatibility code allowing users who have only logged in using SRP to log in once and be automatically upgraded to bcrypt.
