### ISSUE TITLE
Query against a subscription

### ISSUE THREAD

**Issue by ShimShamSam** [meteor/meteor#2247]
Are there any plans for the ability to run a query against a published record set instead of the full collection? It seems odd that the accepted way to query specific records is to run a filter function on the server to publish them, and then run that exact same filter function on the client to filter the results from MiniMongo.

Surely Meteor must already store a linkage between a document and the subscriptions that published it. Why not expose that as a way to restrict queries? I think it could be added as an option in the second parameter of collection,find()

**Comment by dandv** [comment]
Can we reopen this now that MDG is taking feature requests on GitHub?

**Comment by rclai** [comment]
There a [package](https://atmospherejs.com/percolate/find-from-publication) for this.

**Comment by stubailo** [comment]
Reopening as a feature request.

**Comment by mitar** [comment]
You can also use this package in meantime: https://github.com/peerlibrary/meteor-subscription-scope

Not sure if this is needed to be in the core.

**Comment by hwillson** [comment]
As mentioned in earlier comments, this functionality can (and is) already handled by third party packages. Due to this fact, as well as the age of this issue and the lack of activity / +1's, I'll close this issue off. Thanks for opening this issue originally!
