### ISSUE TITLE
finer-grained reactivity for nested objects

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#2254]
Template.hello.helpers({
	user: function() {
		return Meteor.users.findOne(Meteor.userId(), {fields: {"game.blah":1}})
	}
})

If anything in Meteor.user().game changes then it invalidates this helper even though the fields specify that it only uses Meteor.user().game.blah.  So if Meteor.user().var is updated then this helper will re-run.

https://github.com/dan335/fieldtest
http://fieldtest.meteor.com/
https://groups.google.com/forum/#!topic/meteor-talk/zg2cElH-Aqw

**Comment by glasser** [comment]
Turned out this was related to #3571. Fixed!

**Comment by stubailo** [comment]
This is awesome! I can't wait to start using this functionality to optimize my helpers.

**Comment by dan335** [comment]
Wow yes that is awesome! Can't wait for this next release.

**Comment by Slava** [comment]
Great work, should help to make Blaze predictable in performance.

**Comment by rclai** [comment]
Whoa! Does this mean nested fields have fine-grained reactivity now??

**Comment by glasser** [comment]
Well, it depends what you mean by that.  `observeChanges` `changed` messages still have the same API: changes are reported at the top level.  But if your observed query has a fields filter like `{'a.b': 1}`, then `changed` will now be correctly emitted if and only if `a.b` has changed.
