### ISSUE TITLE
Calling functions with parameters on objects in template

### ISSUE THREAD

**Issue by jonasferagen** [meteor/meteor#2259]
Calling a function on an object seems to work within a spacebars template:

i.e. {{myobj.getSomething}}

Even {{myobj.getSomething.myfield}} works - provided that getSomething returns an object

But I can't seem to pass parameters to these functions  - i.e. something along the lines of {{myobj.getSomething(123)}} or {{myobj.getSomething 123}}

Is this possible to do?

**Comment by adriamooney** [comment]
I have this problem too.  Creating a helper function that takes parameters and returns an object causes an error.
