### ISSUE TITLE
infinite refresh after upgrading to 0.8.2 with appcache

### ISSUE THREAD

**Issue by miketucker** [meteor/meteor#2261]
Some combination of AppCache and the blaze template changes in 0.8.2 have caused infinite refreshes in Safari (mobile and desktop)

Theory: After deploying a new version to the server, AppCache attempts to reload the view with new data, but blaze also tries to update the views. Because neither is completed, it infinitely loops

http://drawntogether.org/
(might only be reproducible if previously deployed version is already cached in your browser)

**Comment by paralin** [comment]
I'm still getting this problem in 2016 :)

**Comment by elie222** [comment]
I also just ran into this issue. But it was on Chrome

**Comment by abernix** [comment]
Closing this issue as [appcache is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) by W3C and is being removed from browsers.  It is unlikely to see any further changes on the Meteor side of things and other issues are open to cover its successor, Service Workers: #5982
