### ISSUE TITLE
http://docs.meteor.com crashes on Apple mobile devices

### ISSUE THREAD

**Issue by Kristjan-S** [meteor/meteor#2263]
http://docs.meteor.com/ webpage crashes on Apple mobile devices.

Tested on my Iphone 4 iOS 7.1.1 in Chrome and Safari,
Tested on my Ipad 2 iOS 7.1.1 in Chrome and Safari,
Tested on my friend's Iphone 4s iOS 7.0.6 in Chrome and Safari, the webpage crashes in all scenarios.

**Comment by glasser** [comment]
We've refactored the docs site since then, so I'm going to close this unless people are still seeing it.
