### ISSUE TITLE
minimongo sort order puts allways undefined values first

### ISSUE THREAD

**Issue by piffie** [meteor/meteor#2282]
Hi,

i have a problem with the Minimongo sort functionality on the client side.
I have a sort property on some of the collection items, and want to have these first.
And no matter if i use {sort:['sort','desc']} or asc the items with the undefined values are first.
this is in contrast to how mongodb does this. (http://docs.mongodb.org/manual/reference/method/cursor.sort/)
with mongodb when using desc, the values are defined should be first.

**Comment by nsinfoPRO** [comment]
@piffie Did you solve this?🙂
