### ISSUE TITLE
Error deploying application: Connection error (socket hang up)

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#2295]
I was trying to deploy the win-install.meteor.com site which is very simple except it has a reasonably large amount of data in the public directory, and got the error:

```
Deploying to win-install.meteor.com. Bundling...
Uploading...

Error deploying application: Connection error (socket hang up)
```

I retried and got the same error.

Now as it happens, the site appears to have been deployed successfully, but I suspect that there is an issue with the deployment process.
Even locally the project takes a while to start and I suspect a timeout of some sort occurs while waiting for the site to kick into life.

Maybe a solution would be to send updates across the wire to prevent the timeout, and maybe even give more feedback to the user that the upload succeeded and the app is being started.

**Comment by fvpDev** [comment]
Getting this same issue today, can we re-open this?

**Comment by hwillson** [comment]
@fvpDev - issues like this are now best handled by the Galaxy support team. You should open an issue with Galaxy (when logged into the Galaxy admin, you can do this from within the top left hand menu under "Support").

**Comment by fvpDev** [comment]
Ok cool, will do. Thanks
