### ISSUE TITLE
OAuth redirect does not work properly on Chrome for iPhone

### ISSUE THREAD

**Issue by gdiab** [meteor/meteor#2302]
Chrome for iPhone version 35.0.1916.41

OAuth login redirect will either fail (blank white page in a new tab) or the redirect takes place but sign in does not take place.

the same steps work fine on Safari on iPhone as well as Chrome on the desktop.

**Comment by Krisa** [comment]
@estark37 Coming back on your latest comment, this is a quite old issue, which has been closed, but could it be that the callback is not yet called when the loginStyle is a redirect? This is at least what I see in my flow.
