### ISSUE TITLE
TypeError when using Meteor.loginWithPassword

### ISSUE THREAD

**Issue by pwldp** [meteor/meteor#2327]
When use loginWithPassword there is an error:

TypeError: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create meteor.js:451

in Mozilla Firefox 30.0.

**Comment by hwillson** [comment]
I've verified this is no longer an issue with recent versions of both Meteor and FireFox. Thanks for originally reporting this issue!
