### ISSUE TITLE
Meteor does not preserve cursor/caret position on a reactive contenteditable dom element

### ISSUE THREAD

**Issue by sferoze** [meteor/meteor#2328]
I have a contenteditable field in which I autosave the users draft when they stop typing for a certain time interval. 

When the draft is autosaved and put into mongodb, meteor attempts to reactively reload the contenteditable div, and it updates the content correctly but the cursor position goes back to the top. 

So if a user is typing and stops to think, then continues typing the cursor is at the top! Not good UX 

Is there a quick fix? Otherwise this needs to be addressed in meteors reactivity, to save and reload the caret position on contenteditable divs. 

I don't know if it will help but here is the code I use to autosave (as you can see a quick hack I used it to just place the caret at the end after the draft has been saved, but what if the user was updating middle portion of the draft?):

``` coffee
    saveDraftCallback = _.debounce () ->
      htmlJSON = editor.serialize()
      Research.update self.data.researchThread._id,
        $set: 
          draftHTML: htmlJSON['full-editor'].value
      , (error) ->
        if error
          console.log 'could not save draft'
        else
          console.log 'draft saved'
          placeCaretAtEnd($('#full-editor')[0])
    , 5000

    $('#full-editor').bind "DOMSubtreeModified", saveDraftCallback
```

Meteor's reactivity is amazing for auto savings drafts and reactively sharing text content between users! I am looking forward for this bug to be fixed, it will lead to great possibility.

**Comment by hamzazar** [comment]
Hi @sferoze for the cusor position how did you used Rangy in meteor? can you provide a sample code ?
