### ISSUE TITLE
disallowInlineScripts() conflicts with appcache

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#2331]
Reproduction:

```
$ meteor create foo
$ cd foo
$ meteor add browser-policy
```

In foo.js, add to the `isServer` block:

```
BrowserPolicy.content.disallowInlineScripts();
```

Run the app.  Notice it works correctly.  If you examine the page source, you'll see

```
<script type="text/javascript" src="/meteor_runtime_config.js"></script>
```

If you browse to localhost:3000/meteor_runtime_config.js, you'll see something like:

```
__meteor_runtime_config__ = {"meteorRelease":"0.8.2","ROOT_URL":"http://localhost:3000/","ROOT_URL_PATH_PREFIX":"","autoupdateVersion":"fc37a3865a292943c8df07f60f37877f43bf2cf4"};
```

Now add the appcache:

```
$ meteor add appcache
```

Run the Meteor server again, and refresh the app in the browser to load the browser's app cache.  Stop the Meteor server, and refresh the app page again.  Notice the error

```
Uncaught ReferenceError: __meteor_runtime_config__ is not defined 
```

With the Meteor server still **not** running, browse to localhost:3000/meteor_runtime_config.js again.  You'll see the app HTML, not the `__meteor_runtime_config__` assignment.

The problem is that any route not defined as a static or network route causes the app cache to fallback to serving the app HTML.  This is what allows the browser to open /some/arbitrary/client/path and get the Meteor client app by default.

The solution is to add the JavaScript scripts to the CACHE section of the app cache manifest file.  (See http://docs.meteor.com/app.manifest for an example of what the CACHE section of an app cache manifest file looks like).  This will cause the browser to cache the scripts.

We don't have an internal API to do this cleanly yet, but essentially what we want is to be able to specify a static file that is generated or stored in memory instead coming directly out of the client program manifest.  Or, to have an internal list of static files which is initially populated from the client program manifest that can be added to at runtime, and then have the appcache reference that internal list instead of `WebApp.clientProgram.manifest` directly.  (For the second option, the route-policy package could be extended to have a "static" route option, and the internal list of static files could be stored there).

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers.

Service Workers are supposed to be the replacement which is being tracked in #5982.
