### ISSUE TITLE
UI._parentData() and `..` don't work properly through UI.dynamic

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2337]
See the templates in https://github.com/mizzao/ui-dynamic-parent-data for a description of the problem.

In the `foo` template, we'd expect `..` or `UI._parentData(1)` to grab the data context for the `#with` helper. Instead, we have to actually "reach up" 3 times to get it. Here's the output if you run the example:

```
data:  Object {data: "otherData"} 

parent data with .. : 
constr {kind: "Template_foo", render: function, __helperHost: true, guid: "10", debug: function…}

parent data with ../.. : 
Object {template: "foo", data: Object}

parent data with ../../.. : Object {data: "firstData"}

parent data with _parentData(1):  
constr {kind: "Template_foo", render: function, __helperHost: true, guid: "10", debug: function…}

parent data with _parentData(2):  
Object {template: "foo", data: Object}

parent data with _parentData(3):  Object {data: "firstData"} 
```

Clearly this has to do with how `UI.dynamic` is implemented. However, running this example on 0.8.2 and 0.8.3-rc gives the same result, so I don't think it has anything to do with blaze-refactor.

**Comment by brylie** [comment]
I have recorded a [Firefox JS performance profile](https://github.com/brylie/meteor-autoform-recursion-ff-fix/blob/ec7440d79d8563770b74e57ccc7931dc2fa74e38/javascript.profile.json) while duplicating this bug. Please review.

**Comment by brylie** [comment]
@dohomi what modules are you using in your application?

**Comment by dohomi** [comment]
@brylie quite a lot of packages, nearly 30-40. Hard to tell where the error comes from, but I guess mainly through autoform and collectionFS

**Comment by brylie** [comment]
Hm, well I only installed meteor:autoform.

**Comment by Akash-dvd** [comment]
Template.parentdata behaves weirdly with Template.dynamic.
It has to cross three levels to climb one logical level with Template.dynamic.
It wrongly catches Template.dynamic and its two arguements template and data.

**Comment by Akash-dvd** [comment]
Please fix this asap

**Comment by mitar** [comment]
Accessing parent data context with absolute number of levels is anyway very fragile. I recommend you use [extension package](https://github.com/aldeed/meteor-template-extension#templateparentdatafun) which will allow you to provide a matcher function. I for example use it so that I make every data context be an instance of a JavaScript class and then use `instanceof` to find the data context I want. No matter how high it is.

**Comment by mitar** [comment]
Probably this should work similarly to block helpers which override parent view.

**Comment by hwillson** [comment]
This issue has been moved to meteor/blaze#198 - closing here. Thanks!
