### ISSUE TITLE
The insertElement UI hook doesn't fire when the template gets first rendered

### ISSUE THREAD

**Issue by frozeman** [meteor/meteor#2347]
**_1 Upvote**_ On following template renders, it gets fired.
Should i create a repro, or are you aware of this already?

**Comment by ramsaylanier** [comment]
I'm also having this issue, but only when I use the new {{#if Template.subscriptionsReady}} helper. 

The data gets rendered and I know it's ready, but the uihooks animation doesnt run.

**Comment by patrickml** [comment]
@ramsaylanier +1 im having the same issue

**Comment by ciclopes** [comment]
Same issue here. Meteor@1.1.0.3.

**Comment by rugor** [comment]
+1

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#188 - closing here. Thanks!
