### ISSUE TITLE
Error: getaddrinfo EADDRINFO

### ISSUE THREAD

**Issue by ClaysonIO** [meteor/meteor#2348]
I have a small app running on Modulus AWS. Every few days, it crashes and requires me to restart the application. Judging by the logs, it happens at times when there aren't any users active in the system, so I'm not certain what my code could be causing it.

Below is the error I get each time. It's an irritating 'silent error', as it kills the app (Modulus shows CPU and memory usage drop to 0), but Modulus doesn't recognize it as a crash, so I don't get an alert.

```
{ [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' }

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: getaddrinfo EADDRINFO
    at errnoException (dns.js:31:11)
    at Object.onanswer [as oncomplete] (dns.js:123:16)
```

**Comment by boustanihani** [comment]
I just got the same crash on modulus today :(

**Comment by glasser** [comment]
Sounds like a configuration issue on Modulus' part?

**Comment by boustanihani** [comment]
It was indeed a modulus issue, I had to stop my instance and start it again so that it uses an updated node version...
