### ISSUE TITLE
Meteor.Error thrown on the server and transported to the client should keep stack trace

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2364]
Meteor.Error thrown on the server and transported to the client should keep stack trace. Currently stack trace is removed and a client-only stack trace is created. Documentation says that "details" should contain a stack trace, but this is a bit cumbersome then:

```
new Meteor.Error 500, "Internal server error", new Error().stack
```

It would be better if stack trace would be preserved.

**Comment by sungwoncho** [comment]
I agree with @mitar that whether stack traces are sensitive information depends on the kind of app.

e.g. In an admin application, stack traces can be valuable so that admins can contact support with the relevant information.
