### ISSUE TITLE
Don't depend on naming of Meteor.loginWithFoo functions

### ISSUE THREAD

**Issue by sclausen** [meteor/meteor#2375]
accounts-meteor-developer doesn't follow the naming convention of account-packages, so for example mangasocial/meteor-accounts-ui-bootstrap-3 breaks if you want to use accounts-meteor-developer.
It could be fixed in mangasocial/meteor-accounts-ui-bootstrap-3, but as its related to not using the naming convention of account packages, I think this issue is filed here at right place.

**Comment by laosb** [comment]
Is anyone working on this? Would try this if no one did.

PS: My first comment as an adult!

**Comment by glasser** [comment]
Not that I know of!  We'd love the help.

**Comment by laosb** [comment]
Ah, done. Just see the PR above.
