### ISSUE TITLE
Meteor tool swallows Mongo's error message on low disk space

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#2378]
To reproduce:

- find a machine with no free disk available
- run the leaderboard example with released Meteor 0.8.3
- observe the error message with code "100" being printed
- run `mongod` manually and observe the "not enough disk space" error being printed

Expected:
- "not enough disk space" message being printed

**Comment by glasser** [comment]
```
ubuntu@ip-10-142-215-109:~/leaderboard$ ~/meteor/meteor
~/meteor/meteor
[[[[[ ~/leaderboard ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.

Looks like you are out of free disk space under .meteor/local.
```

**Comment by Slava** [comment]
:+1:
