### ISSUE TITLE
Incosistent inheritance of Meteor exceptions

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2397]
It seems various parts of Meteor uses different way to create subclass of exceptions:
- https://github.com/meteor/meteor/blob/devel/packages/meteor/errors.js#L5
- https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L139

This should probably be unifed?

**Comment by hwillson** [comment]
Closing as [`packages/accounts-base/accounts_common.js`](https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/packages/accounts-base/accounts_common.js#L291-L297) was updated to use `Meteor.makeErrorType` (from `packages/meteor/errors.js`). Thanks!

**Comment by mitar** [comment]
Can you go through code and make sure this is used everywhere? I am not sure I found of examples in the past.
