### ISSUE TITLE
Be more robust in handling exceptions in OAuth's end_of_login_response.html

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2401]
In OAuth's `end_of_login_response.html` code tries to access `window.opener.Package`. If for some reason dialog origin is different than opener origin this fails with security exception. (This happened to me because I opened my development instance as 127.0.0.1, but I had callback configured as `localhost`.) Dialog is still closed, but nothing happens. This was quite tricky to debug. I suggest that code is surrounded with try/catch and provide some message in such case.

**Comment by hwillson** [comment]
There hasn't been any interest/activity on this issue in over 2 years. While the [`oauth`](https://github.com/meteor/meteor/tree/devel/packages/oauth) package's exception handling could definitely be made more robust, there doesn't seem to be a strong need to do so (based on the lack in interest in this issue and the low number of complaints about `oauth` exception handling in other issues). As part of the on-going old issue cleanup process, I'll close this for now. Thanks for suggesting this originally!
