### ISSUE TITLE
Meteor.loginWithPassword support additional loginOptions

### ISSUE THREAD

**Issue by jordangarside** [meteor/meteor#2412]
I'm trying to setup a captcha for when the user misses 5 login attempts.

The issue is that I don't have a way of passing captcha data (or any data except for the login/password) to the server when using `Meteor.loginWithPassword( identityObject, passwordString, callbackFunction )`.
There is simply no way to pass additional data to `Accounts.validateLoginAttempt (options) ->` for validation.

I think this is a pretty important use case as many websites are now implementing capcha logins based on IP Address and missed login attempts.

**Comment by speciose** [comment]
Same problem here two year later :D
Continue here https://groups.google.com/forum/#!searchin/meteor-core/captcha%7Csort:relevance/meteor-core/xtSzPOsnNok/cZsVCsDaE8YJ
