### ISSUE TITLE
Collection.upsert working fine only on first call at the client

### ISSUE THREAD

**Issue by taromero** [meteor/meteor#2413]
When I make an `upsert` on an element of a collection like `Players.upsert(id, data)` on the client, it works **only for the first time**. The subsequent times the `upsert` call only has effect on the client, and doesn't reach the server.

Meteorpad with an example of `.upsert` failing [here](http://meteorpad.com/pad/RGTfGPSrzr7paHrog).

If I make the `upsert` by calling `Players.update(id, data, { upsert: true }`, it works fine every time.

Meteorpad with an exampe of `.update(..., { upsert: true })` working [here](http://meteorpad.com/pad/KeuPJnTqZG8h2MJsr).

You can test it by opening another browser at the same time with the URL provided at the top of the displayed content, and start touching players name. On the first meteorpad the score will be updated on the other browser only the first time.

**Comment by pokaxperia** [comment]
what was the solution?

**Comment by glasser** [comment]
The commit linked above.
