### ISSUE TITLE
Can't change name of package while test-package is runner

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#2424]
If you're testing a package by path (`meteor test-packages ./`), if you change the package name by editing the `name` field in `Package.describe`, it's not smart enough to update the use of that package in `.meteor/constraints` in the test runner app and dies.

Not planning to fix this for 0.9.0 (re-running `test-packages` works).

This would also be fixed if `.meteor/packages` grows the feature to use packages by path.

**Comment by hwillson** [comment]
While this is still an issue, I think it's safe to close it off. This issue has gained very little traction in 2.5 years and the chance of this issue being hit while testing a package is fairly low. Re-running `test-packages` is a suitable workaround given the low chance of this being an issue to most developers. Happy to re-open if anyone disagrees! (but please keep in mind that any disagreement will be the first discussion related to this issue in years ... 😄).
