### ISSUE TITLE
Typescript sourcemaps not working

### ISSUE THREAD

**Issue by smakhtin** [meteor/meteor#2426]
I'm developing my first meteor project with Typescript and compiling everything to Javascript by Webstorm. I'm automatically generate all source maps and it's working perfect with simple [reload](https://www.npmjs.org/package/reload) web server. But somehow, Meteor just ignoring all my source maps and i can see only js files in Chrome debugger. I checked [typescript-compiler](https://atmospherejs.com/package/typescript-compiler) package, but it's amazingly slow and source maps still not working.

**Comment by Urigo** [comment]
We are working on an official Typescript package which already exists in Beta.
Please follow the progress here - https://github.com/Urigo/angular2-meteor/issues/102
