### ISSUE TITLE
HTTP Cross-Domain IE8 IE9

### ISSUE THREAD

**Issue by boustanihani** [meteor/meteor#2430]
Please support Cross-Domain AJAX in IE8 and IE9.

Currently `HTTP.call(method, url [, options] [, asyncCallback])` is failing with the following Error: `Access is denied`

For this to work using `jQuery $.ajax()` one may add the `javascript dataType: 'jsonp'` option:

``` javascript
$.ajax({
    dataType: 'jsonp'
    //...
});
```

or the following javascript shim library: [jquery.xdomainrequest](https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest)

``` html
<head>
    <!--[if lte IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.3/jquery.xdomainrequest.min.js"></script>
    <![endif]-->
</head>
```

**Comment by hwillson** [comment]
Given that [IE 8/9/10 are no longer supported by Microsoft](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), the chances of this issue being worked on further are quite low. Given this and the fact this issue has received no attention in over 2 years, I'll close it off. Thanks for reporting the original issue!
