### ISSUE TITLE
Need a way to reset values of form fields

### ISSUE THREAD

**Issue by avital** [meteor/meteor#2431]
**_7 Upvotes**_ Say an app has an input field whose value is computed reactively:

``` html
<input value={{foo}} />
```

A user changes the value in the field directly in the browser (so the underlying value computed by `{{foo}}` hasn't changed). How does one implement a 'cancel' button that reverts the input fields back to their original value?

Since Deps and Blaze treat setting a reactive variable to the same value as a no-op, something like `Session.set("foo", Session.get("foo"));` won't do anything.

A (pretty bad) workaround for now is something like:

``` js
var original = Session.get("foo");
Session.set("foo", original + "--change-it-to-anything-but-the-original-value");
Deps.flush();
Session.set("foo", original);
```

Maybe we should have an explicit function for "reset form fields under a given DOM element"?

**Comment by gcacars** [comment]
Wow, this is extremely necessary! +1

**Comment by dohomi** [comment]
I'm looking for a fix too +1

**Comment by nate331** [comment]
+1

**Comment by dkoo761** [comment]
+1

**Comment by jagi** [comment]
Isn't it a matter of invalidating computation? From my console:

```js
var comp = Meteor.autorun(function() {
  console.log('Session var equals ' + Session.get('a'));
});
// Prints: Session var equals undefined
Session.set('a', 'x');
// Prints: Session var equals x
Session.set('a', 'x');
comp.invalidate();
// Prints: Session var equals x
```

However in Blaze there is a problem that computation is kept internally as a local variable. I've tried using `Tracker.currentComputation` but wasn't able to invalidate it.

**Comment by AleksiAhtiainen** [comment]
+1

**Comment by pcuci** [comment]
+1 Re: https://github.com/aldeed/meteor-autoform/issues/846 - submitting form forces redraw of entire form. 

Especially horrible UX on small mobile screens, the UI jumps around and changes the scroll location.

**Comment by laurentpayot** [comment]
+1

**Comment by dardanien** [comment]
+1

**Comment by vlddlv** [comment]
+1

**Comment by hwillson** [comment]
Moved to meteor/blaze#208 - closing here - thanks!

**Comment by nosizejosh** [comment]
adding `{{#autoForm collection="Activities" id="insertActivityForm" type="insert" doc=defaultValues}}`  in my case for a form `{{> afFieldInput name='orderPrice' readonly=true value=defaultValues}}` as suggested by aldeed from this [here](https://github.com/aldeed/meteor-autoform/issues/210) seems to have solved my problem.
