### ISSUE TITLE
Sorting minimongo documents by a field of an explicitly specified array element in ascending order fails

### ISSUE THREAD

**Issue by sschmitz** [meteor/meteor#2439]
A Minimongo query with a sort specifier like `{ 'arrayField.0.sortField': 1 }` returns the matched documents in their natural order, while the same specifier with descending order works as expected. The issue is demonstrated in https://github.com/sschmitz/minimongo-array-sorting-bug/; running meteor and looking at the page is enough. The same sort specifier works as expected in a regular mongo shell.

I've only looked at the code rather quickly, but the reason seems to be that the lookup function (returned by `makeLookupFunction`) first checks the literal integer index, and then also does a branching search. When the key `'0'` is not present in an element of `arrayField`, the `lookupRest` function will return a branch with a value of `undefined`, which is appended to the results of the top-level lookup function. In `Minimongo.Sorter.prototype._getMinKeyFromDoc`, where the branches are passed via `Minimongo.Sorter.prototype._generateKeysFromDoc`, a key with a value of `undefined` is chosen over any other keys for sort specifiers with ascending order, while it is not chosen in the case of descending order. If no document in the collection contains an object with a `'0'` key in its `arrayField`, the chosen minimum key will have a value of `undefined` for every document, so no sorting will occur.

My intuition would be that to fix this, either a branching search should only be performed when the next part of the sort specifier is non-numeric, or to not have `lookupRest` return `undefined` when the lookup function is created by `Minimongo.Sorter`. However, I don't know about the implications of changing the behavior of the lookup function, nor do I know what matches the MongoDB behavior best in other cases.

**Comment by cesarve77** [comment]
Same error Meteor 1.4 but for "a.b.0.c"
I made this simple repo for reproduce the bug
https://github.com/cesarve77/minimongo-sort-bug
