### ISSUE TITLE
Subscription overlapping and auto-resubscribe lead to temporary "broken" state

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#2440]
**_1 Upvote**_ Suppose you have two subscriptions `a` and `b` that both `add()` to the same document. Then if you have an autorun like:

```
Deps.autorun(function() {
  if (/* something */) {
    Meteor.subscribe('a');
  } else {
    Meteor.subscribe('b');
  }
});
```

Then, when the guard changes, the following will happen:
1. We'll subscribe to `b`. 
2. `b` goes ready. We are now subscribed to both `a` and `b`. Due to the oft discussed "arbitrary" subscription precedence (e.g. #998), temporarily `a`'s document will win.
3. `a` is un-subbed, and we get `b`'s document.

It's surprising because we aren't explicitly subscribing to two subs that publish the same document. And it leads to broken behaviour because the sub goes ready with the "wrong" data. 

It's also a pretty common scenario when you consider the _same_ subscription getting called with different reactive arguments.

Repro: https://github.com/tmeasday/publication-auto-override

Perhaps `b` should not become ready until `a` has finished unsubbing?

**Comment by mitar** [comment]
> temporarily `a`'s document will win.

Just to be clear. It is not that `a`'s document win as a whole. Only for overlapping top-level fields (those present in both `a` and `b`) fields from `a` win. If fields from `b` are present, which are not in `a`, then those are available. I think it is pretty rare to have same top-level field from two publications which are having different value, isn't it?

Am I understanding this correctly?

What are use cases when one subscribes to a different subscription as a whole inside autorun?

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/2440#issuecomment-305954006, the chances of this being a problem are pretty low. While there is still an issue here, developer demand to have this fixed has also been quite low. As part of the on-going old issue cleanup process, I'll close this for now. If anyone feels differently (and is interested in working on a patch for this), please let us know. Thanks!
