### ISSUE TITLE
Allow a good pattern for naming versions after upstream semver versions plus another bit

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2443]
When you removed the `package@>=version` syntax, @ekatek said that `package@version` implements this constraint. However, I am seeing errors like this now in 0.9:

```
Could not resolve the specified constraints for this project:
Error: conflict: mrt:bootstrap-3@3.2.0-1 vs 3.2.0-2
```

This is very bad, it means that there are only equality constraints on package versions and that packages will not be able to interoperate unless they all use the exact same version.

**Comment by glasser** [comment]
Wrapped version numbers were released in 0.9.3.
