### ISSUE TITLE
[Feature Request] Bundle Chrome, not Android browser for Meteor-Cordova

### ISSUE THREAD

**Issue by fungilation** [meteor/meteor#2444]
I don't know if Chrome is already bundled by Cordova, but Android browser is the new IE and its quirks blows. Famo.us said they are developing their own Cordova based wrapper that bundles the latest Chrome, overriding whatever is default browser in Android. Please have similar in Meteor-Cordova.

Re-post from https://github.com/stubailo/meteor-mobile-demo/issues/3

**Comment by boustanihani** [comment]
It would be really cool if meteor allows **optional Crosswalk integration** as part of the build process, so each one could decide for himself, if the extra 15 MB is a price worth paying :)

**Comment by fungilation** [comment]
+1 @boustanihani

**Comment by insaneinc01** [comment]
Hello
Did anyone successfully build Android/Crosswalk meteor app using @Slava 's [instructions] (https://meteor.hackpad.com/Building-Meteor-app-with-Crosswalk-kHKh4DzGxFQ )? 

I posted a question about this here: http://stackoverflow.com/questions/28762050/meteor-crosswalk-build-fails-at-second-ant-debug-step

I tried using multiple versions of crosswalk, but it always fails at the last 'ant debug/release' step. 

This is the last couple of lines from the log:
````
[javac] /Users/insaneinc/Projects/meteor/cross/.build/android/project/src/org/apache/cordova/file/FileUtils.java:151: error: cannot find symbol
    [javac]     	super.initialize(cordova, webView);
    [javac]     	^
    [javac]   symbol:   variable super
    [javac]   location: class FileUtils
    [javac] Note: /Users/insaneinc/Projects/meteor/cross/.build/android/project/src/org/apache/cordova/file/DirectoryManager.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /Users/insaneinc/Projects/meteor/cross/.build/android/project/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors
    [javac] 3 warnings

BUILD FAILED
/Users/insaneinc/.meteor/android_bundle/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/insaneinc/.meteor/android_bundle/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.
````

I know this is out of scope of the current meteor project. I just want to know if someone got this working, in which case, please do share your method!

**Comment by jperl** [comment]
@insaneinc01 We have a script that automates this, we will post an example today.

**Comment by Wenape** [comment]
@jperl That would be great. My build is also failing with almost the exact same error as @insaneinc01.

    [javac] import org.apache.cordova.PluginResult;
      [javac]                          ^
      [javac]   symbol:   class PluginResult
      [javac]   location: package org.apache.cordova
      [javac] Note: Some input files use or override a deprecated API.
      [javac] Note: Recompile with -Xlint:deprecation for details.
      [javac] Note: /Users/Master/Desktop/ProjectTest/.build/android/project/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
      [javac] Note: Recompile with -Xlint:unchecked for details.
      [javac] 100 errors
      [javac] 3 warnings
    
    BUILD FAILED
    /Users/Master/.meteor/android_bundle/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
    /Users/Master/.meteor/android_bundle/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

**Comment by insaneinc01** [comment]
@jperl Awesome! Eager to see your example. Thanks.

**Comment by jperl** [comment]
We copied over the scripts from our app into here https://github.com/DispatchMe/meteor-todos-crosswalk.

It is builds the todos app with crosswalk but when you run it the app crashes. Hopefully the scripts will give you a good start -- we will look into why the todos app crashes when we have a bit more time.

**Comment by dcworldwide** [comment]
:+1 for crosswalk integration. Anything to ensure we are running the latest web api's is worth doing imo

**Comment by insaneinc01** [comment]
Thanks @jperl. 
Unfortunately I'm unable to replicate the scripts in my project and build an apk. On one occasion I did manage to build an apk, but upon running it on a device, it doesn't go past the initial white screen. 

@Wenape You had any luck building your project? If yes, could you please give some pointers please?

**Comment by Wenape** [comment]
I'm sorry @insaneinc01, same as you. I tried @jperl solution as well, but as he stated, the app builds then crashes upon startup.

I've been following this thread to see if any one manages a solution for implementing Crosswalk, but it seems it's not that easy. 

It's a shame that there's not a solution for this. You can actually get clean 60fps animations within your app, enabling you to be up with the quality of native consumer apps, just not achievable without using Crosswalk.

**Comment by insaneinc01** [comment]
Came across this cool video - https://www.youtube.com/watch?v=vnU0VZM_KEo
Apparently it takes under 2 min to build crosswalk app using the Famo.us Android Wrapper which is still private beta :( 
I'm sure everyone's waiting since forever for this!

**Comment by fungilation** [comment]
+1 definitely for the famous wrapper as it bundles the latest chromium, newer than what crosswalk ships with last I checked. I'm struggling with client rendering performance on my iPhone app so there's a real need that's a common use case, for hybrid mobile apps. Common enough that meteor should support as an option out of the box.

**Comment by ArjunRajJain** [comment]
How did you get access to the famo.us wrapper?

**Comment by andreivolt** [comment]
@Wenape @jperl I actually made a fix for that because it was just a missing perms issue (actually, the cordova-build-over[ri]de dir was misspelled and I used the AndroidManifest.xml from the vanilla Meteor build instead of the one from the repo) **but** the app is still not working as it's showing a blank screen and `adb logcat` outputs some errors about `cordova.js`. But we should probably take this particular discussion to the project's repo...

**Comment by insaneinc01** [comment]
@fungilation Yes, did you get access to the famo.us wrapper? The last I wrote to them, I got a response that its private beta, but if we send them a cordova-ready build of a famo.us app, they would return an APK.  
Since my app's built on Meteor + famo.us (not vanilla famo.us), I wasn't too sure if I could send it to them.

**Comment by fungilation** [comment]
No I don't have access to famo.us wrapper. Just looks great, if only on paper for now. Something to watch for future integration, and I hope Meteor will have more love generally for mobile performance issues like https://github.com/meteor/meteor/issues/3976

**Comment by stubailo** [comment]
Reopening this as we are now tracking feature requests on GitHub.

**Comment by Slava** [comment]
Closing this in favor of https://github.com/meteor/meteor/issues/3076. It has a more recent discussions on what works and what doesn't.
