### ISSUE TITLE
[Feature Request] Sending files through HTTP.post request

### ISSUE THREAD

**Issue by lukejagodzinski** [meteor/meteor#2450]
It would be great to have possibility to send files using `HTTP` package like it's done in Node.js `request` module using `FormData` class. It could look like this:

```
HTTP.post({
  form: {
    file: {
      filename: 'test.png',
      contentType: 'image/png',
      data: imageData // data as a Buffer
    }
  }
});
```

It could automatically set proper headers and HTTP body message.

**Comment by hyouuu** [comment]
Hi Jagi - have you found a way to send file as normal binary? The server I'm trying to upload image to doesn't accept base64 :(

**Comment by jagi** [comment]
@hyouuu Hi, no I haven't. I was using base64.

**Comment by hyouuu** [comment]
@jagi sigh - so hard to get the basic thing work. Do you know why it wouldn't work with binary though? And thanks so much for sharing what you got so far!

**Comment by jagi** [comment]
No I don't know. I assume that entire data with headers should be put in Buffer not only the file data. However I haven't been playing with it.

You can always use Node.js request method if you don't need synchronized call. Or you could use wrapAsync method to make it synchronized. However, I wanted to use HTTP package.

**Comment by si4dev** [comment]
@jagi In fact the HTTP package does use the request nodejs module and with the HTTP option npmRequestOptions you can overrule the options. So you can also set the formData however you need a little trick to unset the body otherwise it will not populate the formData. This worked for me: { npmRequestOptions: {body: null, formData: formData} }

With this you can use the HTTP package. I'd like to make a note on the wrapAsync, in fact the http package is using also the wrapAsync under water. See https://github.com/meteor/meteor/blob/devel/packages/http/httpcall_server.js

**Comment by spingary** [comment]
Thanks to this thread (jagi, si4dev) I was able to get multi-part form POST to an API endpoint to work:
`Test
Test2`

`var a
two
            
var formData = {
              // Pass a simple key-value pair
                folder_paths: 'imported_images',
                files: {
                    value:  img,
                    options: {
                      filename: dest,
                      contentType: content_type
                    }
                }
            };
            var options = { npmRequestOptions: {body: null, formData: formData}  };
            //console.log(formData);
            res=Meteor.http.call("POST", "https://api.hubapi.com/filemanager/api/v2/files?access_token="+portalId,options);
`

**Comment by spingary** [comment]
Thanks to this thread (jagi, si4dev) I was able to get multi-part form POST to an API endpoint to work.

The problem I had, however, was that I too was struggling with binary data.  I needed to download an image, then upload it via a POST to an API endpoint.

Meteor's `http` package doesn't support retrieving binary data.  So I added the [froatsnook:request](https://atmospherejs.com/froatsnook/request) package to do just that.  Then all I had to do was use @si4dev's suggestion to post:

```
// For me, this code is on server-side.
var result = request.getSync(imageURL, {
    encoding: null
});
if (result.response.statusCode == 200)
{ 
  var imgData = result.body;
  var content_type = result.response.headers['content-type'];
  var content_length = result.response.headers['content-length'];
  // More info on formData here: https://www.npmjs.com/package/request#forms
  var formData = {
    // Pass a simple key-value pair
    folder_paths: 'imported_images',
    files: {
      value:  img,
      options: {
        filename: dest_filename,
        contentType: content_type
      }
    }
  }
  var options = { npmRequestOptions: {body: null, formData: formData}  };
  res=Meteor.http.call("POST", uploadUrl,options);
}
```

I suppose the last `http.call()` can be replaced with `request` as well.

**Comment by preetiksingh** [comment]
@
spingary  I have used the same code as yours but my png fil gets corrupted when i am uploading.
This is my formadata

	const formData = {
			file: {
				value: data.data,
				options: {
					filename: data.fileName,
					contentType: data.fileType
				}
			}
		};

**Comment by spingary** [comment]
@preetiksingh Are you also downloading the image from somewhere first, and then uploading?  If you are, make sure you're using the froatsnook:request to download the image.  You might want to check the downloaded file to make sure it wasn't corrupted before uploading/posting it elsewhere.

**Comment by preetiksingh** [comment]
@spingary

I have a file in my local. Which I am posting to the backend api through meteor. But then when I try to download it successfully downloads the text file and I am able to get it that in a readable form but when I download an image file it says

**Comment by preetiksingh** [comment]
@spingary  My code works perfect when I am doing it in my local but then when we test it in production server, even a .5 mb file fails to upload from browser to meteor. Did you face some issue like this before? I am making a rest call here.

**Comment by spingary** [comment]
@preetiksingh is the API you're calling from production the same as the one on local? If not, I'd check the production API service to make sure that's working properly.

**Comment by preetiksingh** [comment]
@spingary Thanks for your previous responses.
Uploading and downloading the file is working fine but then I am facing another issue where is the filename is in Japanese , I am not able to download it.
It gives me this error "There was an error downlaoding the file: TypeError: The header content contains invalid characters"

**Comment by spingary** [comment]
@preetiksingh It sounds like when you download the file, the file name contains characters in a different character set than anticipated.  I believe the HTTP library defaults to utf-8. So if your server is sending the file down to you with the filename in a different character set than utf-8, you might have to add an encoding header or use a different http package which is more forgiving with encoding.

Here's a thread I found that might help:

https://forums.meteor.com/t/wrong-character-encoding-from-http-get/8612/12

I'm afraid I won't be of much help here other than that. 

Good luck!
