### ISSUE TITLE
Default DDP heartbeat timeout of 15 secs causes Meteor to fail to load larger collections at start up

### ISSUE THREAD

**Issue by graemian** [meteor/meteor#2466]
Downloading large collections at start up crowds out the DDP heartbeats. If the client has only managed to download a part of a large collection, it starts again from scratch if the connection is declared dead due to DDP heartbeats not received. The client continues in this state of limbo forever.

If the client has an observer that the slows things down, the effect is more pronounced (i.e. occurs even in smaller collections)

Some ideas on how to fix:
- Only send heartbeats on idle connections
- Reduce record batch sizes
- Reset the heartbeat timeout timer on the receipt of any message, not just a heartbeat message (Andrew Wilcox)

Further discussion on the topic here:

https://groups.google.com/forum/#!topic/meteor-talk/8HYdlbTrYh0

**Comment by gchpaco** [comment]
d84c962 on devel implements the implicit pong described in #4298, and should hopefully fix your issue.  Could you check to see that it does?

**Comment by abernix** [comment]
Thanks for opening this originally.  We're closing some old issues and never heard back on this, but this should no longer be an issue.  If it is, you _could_ adjust the heartbeat yourself using:

    Meteor.connection._heartbeatTimeout = 20000;

But realistically, I don't think you need to do that.  Thanks again!

**Comment by quique1233** [comment]
@abernix it's also possible to modify heartbeatTimeout and heartbeatInterval server side?

**Comment by angryrancor** [comment]
@quique1233 I don't think it is possible to hook callbacks in to server->server heartbeats?  Could be wrong, but I think you need to add your own as a workaround like: 

    var heartbeatOutstanding = false;
    Meteor.setInterval(function () {
      if (!heartbeatOutstanding) {
        devLog.log("Sending heartbeat");
        remote.call("heartbeat", () => {
          devLog.log("Heartbeat returned");
          heartbeatOutstanding = false;
        });
        heartbeatOutstanding = true;
      }
    }, timeOutInMS);

    remote.onReconnect = function () {
      console.log("RECONNECTING REMOTE");
    };

I found this code on another issue log.  DDP v2 never got merged in to the meteor package from the developers fork, it seems... And DDP v2 was slated to fix this issue.
