### ISSUE TITLE
Give a bit more information on what packages are preventing an update

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#2508]
It would be useful if there was a way for package devs to know what package is preventing an update.

e.g

```
meteor update --release 0.9.2-rc0
This project is at the latest release which is compatible with your
current package constraints.
```

Since the packages are my own, this is very troubling. What is wrong? The `api.versionsFrom("METEOR@0.9.0")` constraint is set, this means 0.9.2-rc0 should work, right? (since `0.9.2 > 0.9.0`

**Comment by davidworkman9** [comment]
+1. Can't use anything above rc-10 for the 1.2 release right now and have no idea what package is causing the problem.
