### ISSUE TITLE
Meteor 9.1 Failed to receive keepalive! Exiting. => Exited with code: 1

### ISSUE THREAD

**Issue by ChadMartinson** [meteor/meteor#2536]
After updating to 9.1 Meteor won't keep running on localhost.  It happens on file save when refreshing the client.

**Comment by angjelo** [comment]
@aldeed about the edit that you were saying for the oldLink is right cause i had the same problem like you . I made some changes in my css file many times in a short time of period and i got the same error. I did a meteor reset and it fixed my problem.
