### ISSUE TITLE
Impossible to list all my packages which are release candidates

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2546]
It is impossible to really list all my packages. Even including `--show-old` I cannot get packages which are seen as release candidates. This means that it is really hard to maintain published packages because you cannot even know which packages are in the system.

Probably there should be additional switch which would show release candidates when searching.

**Comment by glasser** [comment]
I think this is fixed in 1.0.3.1; `--show-old` is now `--show-all`.

So I can now run, eg, `curmeteor search --maintainer mitar .  --show-all`, on devel.

(however, on 1.0.3.1 this fails for a couple unrelated reasons that I just fixed on devel.  See a56d73f and 9d8acb6.)
