### ISSUE TITLE
Npm.require in package.js sometimes works instead of never working

### ISSUE THREAD

**Issue by atrigent** [meteor/meteor#2559]
There is a an `Npm.require` function made available inside package.js files. It is implemented here: https://github.com/meteor/meteor/blob/devel/tools/package-source.js#L686. This allows you to `Npm.require` both modules in meteor's dev bundle and supposedly also modules that were specified in `Npm.depends`. Requiring stuff from the dev bundle works fine anywhere in the file. Obviously requiring things that were depended on could only work in an `onUse`/`onTest` function, because otherwise the dependencies could not have been downloaded yet. However, doing so in an `onUse`/`onTest` function is still unreliable. This seems to be because the sequence of events is (roughly):

1. Run package.js file (https://github.com/meteor/meteor/blob/devel/tools/package-source.js#L744)
2. Call `onUse`/`onTest` function (https://github.com/meteor/meteor/blob/devel/tools/package-source.js#L1193)
3. Install dependencies

The fact that 3 comes after 2 means that requiring things that were depended on does not work before the dependencies are installed. In other words, it doesn't work the first time that the server is started - the second time, the dependencies will have been downloaded and everything works.

Is `Npm.require` actually supposed to work with things that were specified in `Npm.depends`, or is this a relic of a bygone age? Because at present, this functionality is pretty much unusable. I realize that this function is completely undocumented, but it would be helpful if it were simply removed if it is not intended to work, or fixed if it is intended to work.

Our use case for this is that we are trying to package a client-side library that requires browserify, and we are trying to run the browserify bundling step in the `onUse` function. We haven't found a better way to do this, other than possibly using the plugin system somehow. If there is a better/more supported way of doing this, we'd love to hear it.

Thanks.

**Comment by glasser** [comment]
I fixed this in 10173c0.
