### ISSUE TITLE
Attributes on <body> not supported

### ISSUE THREAD

**Issue by html5cat** [meteor/meteor#2561]
From my understanding, attributes on `<body>` are not supported because Meteor apps can have multiple `<body>` tags that all get grouped together. If there's `<body attr="foo">` and another `<body attr="bar">` then it's not clear what the resulting class/attribut should be on `<body>` in the app.

I propose an error is showed in case there are two instances of `<body>` tag, rather than completely forbidding the use of attributes.

**Comment by netanelgilad** [comment]
#3467 Courtesy of the angular-meteor team :)
Currently creates a warning when the same attribute defined twice...

**Comment by stubailo** [comment]
Merged and fixed: https://github.com/meteor/meteor/pull/3467#issuecomment-75702175
