### ISSUE TITLE
Request: build for all supported architectures directly on the packages server

### ISSUE THREAD

**Issue by tanis2000** [meteor/meteor#2569]
I've been hitting the wall with my head in the last few days trying to fix all the problems that have arisen while porting my apps to Meteor 0.9.1.1
Most of the problems are due to the new packaging system and a feature that would really make my day would be to let the developer upload his package and then have the packaging server build the binaries for all the different architectures. 
That way we wouldn't have to rely on package maintainers to upload binaries for all the different architectures and would make it easier for them to just publish without having to spin up different servers just to compile a new release.

**Comment by splendido** [comment]
I've discovered this thread while searching for other stuff but...

I recentrly started [autopublish.meteor.com](https://autopublish.meteor.com) to support and ease the direct integration of 3rd party libraries (see also [this discussion](https://github.com/MeteorCommunity/discussions/issues/14)).

At the moment I'm running the build process on a VM I have on DigitalOcean, but the long term plan is to get more support from MDG in case the project will be able to get a good momentum...

(We already obtained that the page will never be put to sleep: see [this](https://github.com/MeteorPackaging/autopublish.meteor.com/issues/3#issuecomment-71300487))

So, to wrap up, having (free) access to build machines for the supported architectures would be great to spin the project to a next level. :)

After that, the only missing thing would be having the possibility to do a `meteor login` on the remote  build  machine for an arbitrary user for which we had a *Meteor Developer Account* token.

Is there anything on the roadmap for a Meteor OAuth API?

**Comment by glasser** [comment]
Since `meteor admin get-machine` is now released, I'm going to close this issue.  (@splendido, does that command work for your purposes?)

**Comment by splendido** [comment]
@glasser, I know there's a time limit (you can also specify the amount of minutes for the reservation with a --minutes option) and @raix reported he hitted the quota a couple of times while experimenting with [mbr](https://github.com/raix/Meteor-mrtbulkrelease)

I'm worried that there might be some other *quota* we'll hit soon in case a good number of packages start to user the *service*.

Do you think it would be a problem requesting e new VM for every new build operation to be spawned?
...in case it'd be always the same user requesting them, there some other limitation we should be aware of?

If MDG is comfortable with any (reasonable) number of build machine requests, we can start testing with it.
...lets consider that a number of devs could decide to rely on autopublish.meteor.com to release their packages, even if they don't need to publish for different architectures and they could do it from their console (but we won't have means, nor intentions, to prevent them to enable their packages on autopublish).

Tnx for asking, let me know.

**Comment by glasser** [comment]
For now, if you're using the build service for legitimate Meteor package building, go ahead, and let us know if you hit limits.  We'll see what we can do.

**Comment by splendido** [comment]
Ok, great, many thanks!
I'll let you know

**Comment by splendido** [comment]
...one more thing @glasser: do you think is there any chance to be able to run `meteor admin get-machine` directly from the server code of `autopublish.meteor.com`? Or wuold we need a proxy VM where to run `meteor login` plus `meteor admin get-machine` in any case?
What's the environment for the deployment on *.meteor.com?

**Comment by glasser** [comment]
The `meteor deploy` environment isn't particularly set up to facilitate spawning other jobs in an easy and managed way.  (A goal for Galaxy is that it should be.)
