### ISSUE TITLE
Cordova - ability to provide a custom app name (with spaces)

### ISSUE THREAD

**Issue by andrewreedy** [meteor/meteor#2578]
I want to use a custom name for my Cordova apps that is not the name of the directory and contains spaces. Currently builds are failing if the directory has spaces in the name. It would be great if I could just specify --name "Cool Meteor App" or even --ios-name "Cool Meteor" --android-name "COOL Meteor" .. etc because sometimes the names are different on different platforms.

**Comment by hems** [comment]
i still get this error, using the example mobile-config.js :(

**Comment by raix** [comment]
I'm getting errors on this too - It would be really nice if all "special" chars are stripped or have a setting for the "DisplayName" *(my ios build failed when using commas)*

I know we can workaround this - and it's not a Meteor issue, but it's a common problem - one newcomers have to deal with.
