### ISSUE TITLE
Constraint Solver doesn't filter incompatible builds

### ISSUE THREAD

**Issue by afuhrtrumpet** [meteor/meteor#2586]
So I have been trying to install the raix:famono package to reproduct a different issue, but for some reason I cannot do this because meteor is looking for an older build version that doesn't exist.

Reproduction:

```
meteor create reproduction
cd reproduction
meteor
meteor add raix:famono
```

Command-line output:

```
alex@alex-laptop:~/meteor/secondreproduction$ meteor update
Refreshing package metadata. This may take a moment.
This project is already at Meteor 0.9.1.1, the latest release.
alex@alex-laptop:~/meteor/secondreproduction$ meteor add raix:famono
Refreshing package metadata. This may take a moment.
No compatible build found for raix:famono@0.8.0
Package raix:famono has no compatible build for version 0.8.0
```

If it matters, my laptop's filesystem was full prior to this issue until I deleted about 7 GB worth of files.

**Comment by hwillson** [comment]
It doesn't look like there is an actionable issue left in this thread. Given this, and this issues age/inactivity, I'll close it off. Thanks!
