### ISSUE TITLE
Spacebars : no easy way to handle @first/@last/@index/@odd/@even ?

### ISSUE THREAD

**Issue by temsa** [meteor/meteor#2587]
**_2 Upvotes**_ Spacebars is inspired by Handlebars, yet it does not support [@data](http://handlebarsjs.com/reference.html#data) properties as far as I know (at least it is not in the reference).

How should we handle some "{{#each}}" which should not have some element for the last or the first one ?

How should we handle "stripes" as well ?

**Comment by wursttheke** [comment]
Awesome: @index seems to be coming! https://github.com/meteor/meteor/pull/3716

Maybe the rest can be build on top of that?

**Comment by rossmartin** [comment]
Please this would be awesome.

**Comment by Slava** [comment]
@wursttheke it is not hard to implement all of these on top of @index. That's not a priority though.

**Comment by wursttheke** [comment]
Thanks for your answer, @Slava. You're right. Having index is great and the rest shouldn't be too much of a problem. I guess it could be done easily inside a helper function.

**Comment by mitar** [comment]
But will parser allow us to use `@first` as a helper name?

**Comment by Slava** [comment]
@mitar no, it will not. You can implement others in helpers.

**Comment by mitar** [comment]
Crying. :-(

**Comment by mitar** [comment]
@dgreensp [said that if we do a pull request](https://github.com/meteor/meteor/commit/afd240fa6fb1bff4263e7d398e018b694a7033f4#commitcomment-11166036) for `@first` and others, he will take it. :-)

**Comment by calvin-evans** [comment]
:+1:

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#185 - closing here. Thanks!
