### ISSUE TITLE
Meteor 0.9.2.1 - White screen on Android

### ISSUE THREAD

**Issue by Compy** [meteor/meteor#2603]
I used the following commands:
meteor create mobileapptest
cd mobileapptest
meteor add-platform android
meteor run

The package builds and loads to my phone and I get nothing but a white screen. The console reports:

```
Jimmys-MacBook-Pro:mobileapptest compy$ meteor run android-device -p 10.0.0.3:3000
[[[[[ ~/Meteor-apps/mobileapptest ]]]]]

=> Started proxy.
=> Started MongoDB.     
=> Started Cordova (android-device).   
I20140916-08:50:13.861(-4)? --------- beginning of /dev/log/main
I20140916-08:50:13.921(-4)? --------- beginning of /dev/log/system
=> Started your app.   

=> App running at: http://10.0.0.3:3000/
I20140916-08:50:18.188(-4)? Changing log level to DEBUG(3)
I20140916-08:50:18.191(-4)? Found start page location: index.html
I20140916-08:50:18.597(-4)? Changing log level to DEBUG(3)
I20140916-08:50:18.598(-4)? Found start page location: index.html
I20140916-08:50:19.239(-4) (android:meteor_cordova_loader.js:180) Uncaught TypeError: Cannot read property 'applicationStorageDirectory' of undefined
```

The device is running Android 4.3 (Jellybean)

**Comment by NawazKhanMd** [comment]
Hi where is this $home file located in meteor project structure

**Comment by abernix** [comment]
@NawazKhanMd `$HOME` is your home directory.  On *nix this is usually `/home/<username>` and on Mac this is `/Users/<username`.  On Windows, `.meteor` is stored in a slightly different place: `%LOCALAPPDATA%\.meteor` (you can actually type `%LOCALAPPDATA%` into the Explorer bar).

You might also be interested in #7018.

This very old issue is closed so you're better off using more recent issues (and versions of Meteor). 🙂
