### ISSUE TITLE
Packages not being able to access their own assets at first run of the app that uses them

### ISSUE THREAD

**Issue by tanis2000** [meteor/meteor#2606]
If you use `Package._transitional_registerBuildPlugin` to run arbitrary code at build time when the package is being deployed inside an app, the first time the handler is being run, the `.meteor/local/build` folder with the content of the packages is not yet there and the package itself cannot access its own files.

The second time you run `meteor`, it will work as expected as the files have been copied there at the end of the first run.

If you run `meteor reset` this happens again as the folder is cleaned up. 

Is there a different solution or is it a bug? Is there any workaround?

**Comment by gbhatnag** [comment]
This is still happening on Meteor 1.2.0.2 with the https://github.com/meteoric/ionic-sass project.  Ionic-sass compiles files that are pointed to by client/ionic.scss.  For a while, this only happened the very first time running the server.  Not it's happening every time, even though I can see the files are clearly there.

**Comment by myrtleTree33** [comment]
@gbhatnag  +1

**Comment by myrtleTree33** [comment]
@gbhatnag this fix worked for me https://github.com/meteoric/ionic-sass/issues/16

**Comment by codeHatcher** [comment]
Can confirm, this is still happening.

**Comment by RaheelaKhan1172** [comment]
Hi everyone, 

I'm following a tutorial and I'm currently having this problem. When I attempt to run meteor, I receive this 

error: 
   While building the application: /Users/raheela/sampleMeteor/client/styles/styles.scss:2:2: Scss compiler error: file to import not found or
   unreadable: .meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic
   Current dir: /Users/raheela/sampleMeteor/client/styles/
   
I know the files are there-- I installed the packages more than 3 times. After each iteration, the result was that I already have the package installed.

Can anyone please help me? I'm just beginning with React and Meteor and I don't know where to look. I killed the app and restarted it numerous times as well.

**Comment by YonasBerhe** [comment]
+1

**Comment by der-ede** [comment]
Hi there,

 did anyone upload his/her meteoric utilizing app to apple's app store with success?
For the same reason it won't compile scss, Androids Play Store is fine.

Regards
