### ISSUE TITLE
No glyphicons on Firefox 9.2.1

### ISSUE THREAD

**Issue by zapaz** [meteor/meteor#2608]
On a Mac OSX configuration Bootstrap glyphicons are not displayed on Firefox with 9.2.1 (small numbers instead)

But they are displayed with other browser (Chrome and Safari) or with previous Meteor version 9.1.1

**Comment by glasser** [comment]
Sounds like this  was a problem in a particular third-party package, not Meteor.

**Comment by zapaz** [comment]
@glasser : yes, and solved now on these third-party bootstrap packages
