### ISSUE TITLE
ios run on device or on emulator, failing "ld: 114 duplicate symbols for architecture i386"

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#2636]
```
$ uname -a
Darwin AlanMacBook.local 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64
$ meteor --version
Meteor 0.9.2.2
$ meteor test-packages --verbose --ios zeroasterisk:cordova-geolocation-background
ld: 114 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

also, I can't find the logs, I found this, but it's empty:
```
$ cat ~/.meteor/android_bundle/Library/Logs/iOS\ Simulator/iOS\ Simulator.log
```

But I did capture the full console output here:
http://sebsauvage.net/paste/?2186cdf56e0d5cb7#DX0nXuwAVxv8GVC0sqsFm/ZwISui5v9mxXtLfP+Ob1Y=

**Comment by martijnwalraven** [comment]
Is this is still an issue with the new testing support in the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
