### ISSUE TITLE
How to specify Android emulator?

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#2637]
When running or testing on an android emulator, i'm on OSX and would like to use the Intel HAX, which I *did* install via `meteor configure-android` so it's in the SDK inside `~/.meteor`
 
But... it ends up using the ARM emulator.

```
Total time: 7 seconds
WARNING : no emulator specified, defaulting to meteor
Waiting for emulator...
```

What are the options to specify which to use?  We should update the wiki.

**Comment by Slava** [comment]
Hey @zeroasterisk, sorry for getting very late to this. I wonder if this is still a reoccurring problem? As far as I understand, in the latest versions of Meteor this was implemented to always have the x86 version of the emulator. Reinstalling the whole Meteor to the latest > 1.0 version should help with this.
