### ISSUE TITLE
Facebook login broken in iOS 8 Safari

### ISSUE THREAD

**Issue by fungilation** [meteor/meteor#2639]
This may very well be a Safari bug, but since updating to iOS 8 on my iPhone 5, hitting Sign In with Facebook in my Meteor 0.9.1.1 app results in a new safari tab that's blank and stuck there. I tried connecting to mobile safari through desktop safari's web debugger on the Develop menu and nothing shows up there, javascript and consoles are all empty.

Just want to know firstly if I'm the only one seeing broken Facebook login on iOS 8? I'm also using the Accounts-Entry package, but that shouldn't matter as it's using Meteor's standard oauth hooks. The blank facebook oauth page has this url if it's relevant: [domain]/_oauth/facebook?close&code=AQAyIvhYFJoa6BhFU14gYEn7JgisMpO3JaESrA9LVPpAluOyuuJBI9qKUUfi2jwBRB-a4KMVQw-TDzwprdozt6ROdHveFlMlA0X52pode3dOICIJaWlBhxjza8M4jbnKVKGdP2ZSm51CKp-bG9Yd3ClWDIeCwE2MeCgKZ4FhEM48N42cs3H1mLSD2FsZgjKlLU6wlsuQm108gYrnzxDLqEq5__3rVTF1ODJCK4h-drzgrW3-EjpnQErHV6G-zGSAnUuJGdlfEyQNqjtURxqKXGdmSoBltrle2hTyik33shaUDGUKAqrIdZbDf44S5DHjgOY&state=jM7RlYnzMy_cuDJ2-q4uW8RrPBgRPZBlXmatPJMpUCC#_=_

**Comment by baszero** [comment]
Is this somehow related to the fact that the Facebook Login does not work anymore on Safari Version 8.0.7 (10600.7.12) running on Mac OSX Yosemite?

**Comment by ccorcos** [comment]
+1 what an annoying issue!

**Comment by tomyo** [comment]
+1
