### ISSUE TITLE
Errors should be printed to console.error not console.log

### ISSUE THREAD

**Issue by wtfaremyinitials** [meteor/meteor#2646]

**Comment by glasser** [comment]
Yeah, this goes through `Meteor._debug` which uses `log`.  It's true that `console.error` probably makes more sense.

**Comment by lbergnehr** [comment]
Perhaps it should even be possible to add a callback, something like `Meteor.log(function(message, stackTrace) { ... })` in order for the application to handle logs in their own way?

**Comment by luccamordente** [comment]
I'd like to be able to see Meteor errors in specs results and logging errors with `console.error` would allow that. +1 for this change

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/2646#issuecomment-75878792, errors are being printed to the console via [`Meteor._debug`](https://github.com/meteor/meteor/blob/96db56b0bae5168fa852eead7cbf0131a12c0ec8/packages/meteor/debug.js). `Meteor._debug` isn't just being used for errors though, so addressing this isn't as easy as just switching `console.log` to `console.error`. 

The above being said, this isn't a bug with Meteor - things are implemented as designed. If anyone is still interested in seeing console logged errors use `console.error`, please consider opening a new feature request for this over in http://github.com/meteor/meteor-feature-requests. Thanks!
