### ISSUE TITLE
force-ssl does not force websocket connections to be SSL

### ISSUE THREAD

**Issue by doctorpangloss** [meteor/meteor#2647]
Using a `DDP` client like `Objective-DDP`, I can still connect to a server over a `ws://` (as opposed to `wss://` URL.

I would expect `force-ssl` to redirect the connection, if that is supportable, or to reject a non-secure connection.

**Comment by PotterDai** [comment]
having the same problem, wondering what's the solution for it? (seeing it has been closed)
Thank you!
