### ISSUE TITLE
Slow cordova app start

### ISSUE THREAD

**Issue by Batistleman** [meteor/meteor#2655]
I made cordova applications before, but it seems like my meteor app is starting very slow (~10 sec.). Without really doing anything; (I’m running this on a physical S4)

```
LAUNCH SUCCESS
Command finished with error code 0: /Users/batist/Projects/antobase-instructions/app/.meteor/local/cordova-build/platforms/android/cordova/run --device
I20140920-10:19:35.727(2) (android:meteor_cordova_loader.js:69) Starting the server on port 23873
I20140920-10:19:36.165(2) (android:http://10.80.67.209:23873/:18) Viewport target-densitydpi is not supported.
I20140920-10:19:41.551(2) (android:http://10.80.67.209:23873/cordova.js:1154) deviceready has not fired after 5 seconds.
I20140920-10:19:41.553(2) (android:http://10.80.67.209:23873/cordova.js:1147) Channel not fired: onPluginsReady
I20140920-10:19:41.556(2) (android:http://10.80.67.209:23873/cordova.js:1147) Channel not fired: onCordovaReady
I20140920-10:19:41.558(2) (android:http://10.80.67.209:23873/cordova.js:1147) Channel not fired: onDOMContentLoaded
```

Any idea’s on how to speed it up?

**Comment by crapthings** [comment]
this issue still found on old device

sumsong gt-s7562c
android 4.1.2

I20150107-17:04:42.291(8) (android:http://meteor.local/cordova.js:1154) deviceready has not fired after 5 seconds.
I20150107-17:04:42.408(8) (android:http://meteor.local/cordova.js:1147) Channel not fired: onPluginsReady
I20150107-17:04:42.408(8) (android:http://meteor.local/cordova.js:1147) Channel not fired: onCordovaReady
I20150107-17:04:42.409(8) (android:http://meteor.local/cordova.js:1147) Channel not fired: onDOMContentLoaded

**Comment by Ethaan** [comment]
@crapthings Did you find a solution to this issue?

Right now there is a SO question about this, if you resolve or find a workaround could you please come [here](http://stackoverflow.com/questions/28511910/meteorcordova-deviceready-has-not-fired-on-android)

Thanks

**Comment by crapthings** [comment]
@ethaan

Upgrade android os or use crosswalk, but i've failed to building crosswalk with meteor.

**Comment by glasser** [comment]
This should be fixed again in 1.0.4.

**Comment by chromonav** [comment]
its 1.1.0.4 now still not fixed guys pl pay attention :(

**Comment by rbwsam** [comment]
I'm experiencing this issue as well: 7 seconds to start on iPhone 5s @ 1.1.0.3

**Comment by obiwarn** [comment]
Meteor 1.2

Same issue. I use 15 plugins and get 'deviceready has not fired after 5 seconds.'

**Comment by guilhermedecampo** [comment]
I have this issue with android 4.4.4 in meteor 1.2 also. Would be nice to know how to debug this. 
Knowing which packages are taking more time to load.

**Comment by guilhermedecampo** [comment]
ping @martijnwalraven =)

**Comment by martijnwalraven** [comment]
@guilhermedecampo: Although some posts in this issue seem to refer to older problems, the general issue of Cordova startup being slow is something I plan on investigating as part of the file serving plugin rewrite I'm working on. No promises, but I'm aware of it and would at least like to understand better what is going on.

**Comment by guilhermedecampo** [comment]
ok @martijnwalraven keep us posted =).

**Comment by reexm** [comment]
Just note for anyone having trouble compiling Crosswalk with Meteor (mentioned by @crapthings), you can add it as a Cordova plugin as follows: `meteor add cordova:cordova-plugin-crosswalk-webview@https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview.git#cd24c9cf90ed7741b3364cbd8b2b73d9f7dacb93`. This works in Meteor 1.2 but probably won't work in earlier versions as I think they come with an older version of Cordova. As proof [here is a vid] (https://youtu.be/UEDg1rQCHrs) of Meteor running with Crosswalk on Android Wear.

**Comment by rbwsam** [comment]
**What fixed it for me:** I didn't have a .html file with a `<body>` tag. Added `<body></body>` and start time dropped from 8s to 2s. 

I am using `kadira:blaze-layout@2.3.0` maybe that has something to do with it.

**Comment by countcain** [comment]
My meteor cordova app uses angular. It starts really slow in ios devices. Always takes about 8 seconds to render the initial page.

**Comment by joncursi** [comment]
I'm also experiencing this running a bare bones react app on Meteor 1.3.2.4 (crosswalk enabled). ~10s startup time for initial page load (and that's with 0 retrieval of data from Mongo, simply rendering a React component to static HTML).

**Comment by fpaboim** [comment]
Same thing here. 10 second initial load on ionic with angular... removing lauch-screen package has no effect.

**Comment by countcain** [comment]
Due to this issue, finally I give up use meteor to developer my mobile app. :( 

Although Meteor is good, it causes much troubles if you need customized functionality.

**Comment by ddresch** [comment]
@rbwsam thx for this tip. Worked for me too. Simply added <body></body> to my header.html which I used already for META tags etc.

Not using Angular or React it's simple Blaze HTML with ´kadira:blaze-layout´ setup.
