### ISSUE TITLE
No way to build a release ready android apk

### ISSUE THREAD

**Issue by bellamystudio** [meteor/meteor#2658]
I was previously using the Cordova CLI, and when it came to put together an .apk for alpha testing I could use cordova build --release, and it would build me an unaligned .apk file that was relatively trivial to sign, align and upload. 

Without this functionality in the meteor command line, there's no (easy/good) way of creating a non-debug apk file, and this is a major problem as far as I can tell. I've spent the last couple of days trying to import an android build output by meteor into Android Studio, and then Eclipse, just so I could build a release-ready app, and both of them throw hundreds of errors. There seem to be no helpful threads/success stories out there from people that have managed to overcome these issues.

If the meteor cli could be extended to prepare a release ready unaligned apk (perhaps using cordova?) then that would save major headaches for anyone with an app that wants to actually get it into the play store; otherwise it's only really any good for demoing on local devices.

Please correct me if I'm wrong as I need to get this app out there!

**Comment by TrevorSayre** [comment]
@bellamystudio When you see an error like `Unable to resolve project target 'android-20'` it usually means you need to install the appropriate packages from the Android SDK Manager. Run the command `android` from your command line to launch the Android SDK Manager, then expand the `Android 4.4W.2 (API 20)` folder (this is what android-20 wants, you'll notice others with API 19, API 21, etc), check the SDK Platform file and click the `Install packages...` button. This is what resolved that for me.
