### ISSUE TITLE
handlebars support for <head> element

### ISSUE THREAD

**Issue by jaeh** [meteor/meteor#266]
hi devs :)

the title basically is my question,

is there a way to get handlebars to work in the head easily?
currently i am trying to get my page towards production state and i would really like to chang metatags and opengraph tags depending on the page where i am at.
this would also be great to load customized css based on database collections.

is there a way i completely overlooked already or would this need to get hacked in?

thanks for all that work anyways,
greetings
manarius

**Comment by shkomg** [comment]
+1

**Comment by YuukanOO** [comment]
:+1:

**Comment by innomonster** [comment]
+1

**Comment by maxlibin** [comment]
+1

**Comment by kenken17** [comment]
+1

**Comment by fulv** [comment]
+1

**Comment by mze3e** [comment]
+1 for blaze

**Comment by laosb** [comment]
Maybe we'd try to make a special "template" for `<head>`.

**Comment by mze3e** [comment]
I opened an issue at blaze : https://github.com/meteor/blaze/issues/11 pls vote there

**Comment by reduxdj** [comment]
+100

**Comment by yoh** [comment]
+1

**Comment by DanAncona** [comment]
yes plz to handle with blaze. external libraries to handle <head> tags is too much!

**Comment by NicoKnoll** [comment]
+1

**Comment by egoldblum** [comment]
+1 surprised there's not a better story for this yet

**Comment by delueg** [comment]
this iron-router SEO plugin worked for me: https://github.com/DerMambo/ms-seo

**Comment by saturnaut** [comment]
Would like to dynamically import Polymer web components in the head using templates, so ...
+1

**Comment by nazarposhta** [comment]
@delueg  
iron-router SEO package worked but - if I need to put <link rel="canonical" href="something">
can that package help me?

**Comment by delueg** [comment]
@nazarposhta sry but "put" what? Like http-PUT or what do you mean?

**Comment by nazarposhta** [comment]
@delueg Uh sorry - I need to put the link tag
`<link rel="canonical" href="somathing">`
can that package help me?

**Comment by nazarposhta** [comment]
@delueg I found that solution 
`link: [{
                rel: "canonical",
                href: "http://www.example.com/"
            }]`
