### ISSUE TITLE
Cordova app: SVG images not showing  (v0.9.2.2)

### ISSUE THREAD

**Issue by chvonrohr** [meteor/meteor#2667]
**_1 Upvote**_ We used Meteor 0.8.3 with Phonegap/Cordova Webview and got our app in the PlayStore and the Apple Store. For smaller filesize and better image quality most images are SVGs.

After upgrading that app to 0.9.2.2 and building with the new "meteor run ios / android", the app is working, but SVG images are not shown.
Even with a new project which only shows a PNG and a SVG image, result is that PNG works and SVG is shown as "image not found" icon. This problem occurs on Android and IOS.
The images are in the public folder and I tried with and without leading slash.

``` html
<template name="hello">
  SVG (not working):
  <img src="logo.svg" />

  PNG (working):
  <img src="logo.png" />
</template>
```

Can anybody confirm this behavior?

App: NZNZ (http://app.nznz.ch)

**Comment by jonykalavera** [comment]
i have this very same problem with my cordova app. how did you fix this??

**Comment by freeredpill** [comment]
I have the same problem as well.  How do we fix it?

**Comment by Aknilam** [comment]
+1

**Comment by hasahmed** [comment]
was this ever fixed?

**Comment by ogntng** [comment]
reading this might help 😉

> Hey chvonrohr,
> 
> we need a clonable reproduction that clearly shows that the code works for the browser and doesn't work for Cordova/Phonegap.

.
.
.
.
.
.

anyway I got the same problem. how did you fix this?

**Comment by chvonrohr** [comment]
It's quite a while ago ;) But, as far as I can remember, this was fixed back then.
So it's possibly a regression... I'm unfortunately not able to reproduce it as we're not further developing that tool..
