### ISSUE TITLE
Subscription does not re-run when logging in if threw error.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#2675]
According to the [docs](http://docs.meteor.com/#publish_userId) if you login, each publication should re-run with the new `userId` value. However, if the subscription threw an error, this does not happen.

Is this as designed? We use `check(this.userId, String);` all over the place in publications, which triggers this behaviour.

Reproduction: https://github.com/tmeasday/publication-error-login
1. Run server, hit URL. Notice error message in terminal.
2. Login. Notice nothing is logged in the terminal.
3. Refresh the page. Notice that the publication has run successfully.
4. Logout. Notice the error re-runs.

I would have expected the publication to re-run at step 2 (or it to be documented if not).

**Comment by hwillson** [comment]
I've verified this is still the case with the latest version of Meteor (1.5 as of today). Looking at this from an application usability point of view, I think it's safe to assume this is a bug, and that the [docs are correct](https://docs.meteor.com/api/pubsub.html#Subscription-userId).

**Comment by hwillson** [comment]
Instead of changing this in the codebase, we're going to document the current behaviour. See https://github.com/meteor/docs/issues/172. Closing here - thanks!
