### ISSUE TITLE
weird issue on programs.json

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#2677]
This is on meteor 0.9.2.2 
On Mac, programs.json looks like this: https://gist.github.com/arunoda/33639c353ae8e572bdba

All my local packages comes at the end, that makes issues on the `global-imports` package.
and the error is

```
TypeError: Cannot read property 'Metrics' of undefined
    at packages/global-imports.js:7:42
    at /private/tmp/bundle/programs/server/boot.js:161:10
    at Array.forEach (native)
    at Function._.each._.forEach (/private/tmp/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /private/tmp/bundle/programs/server/boot.js:82:5
```

This is first few lines of `global-imports.js`

```js
Showdown = Package.showdown.Showdown;
Metrics = Package['metrics-aggregations'].Metrics;
_ = Package.underscore._;
HTTP = Package.http.HTTP;
Email = Package.email.Email;
Retry = Package.retry.Retry;
```

But this works fine on Linux 64 on our CD server. see: https://gist.github.com/arunoda/780d182d75f1f613540b

What's going wrong here.
I re-installed meteor as well, no luck.

**Comment by glasser** [comment]
This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.
