### ISSUE TITLE
running iOS built app stuck on 'resetting plugins due to page load'

### ISSUE THREAD

**Issue by adnissen** [meteor/meteor#2684]
Whenever I try to run the ios app on my physical device, according to the xcode dev console it goes through all the stages of loading, then stops at 'Resetting plugins due to page load." It stays on this 'page', and on the device it's just an unresponsive white screen. I've put in debug statements, and I know for a fact that deviceready is firing correctly. 

Really weird things: Sometimes the simulators get past this stage. Not all the time though. The web version (quotable.meteor.com) loads perfectly and instantly, which isn't a surprise since the web builds don't use cordova. 

I can provide additional details if necessary.

**Comment by Jaspreet-Lamba** [comment]
I got the same error but solved just by simply turning off the wifi of my device and then turning it on.
