### ISSUE TITLE
Meteor 0.9.2.3 - White screen on IOS (simulator & device)

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#2692]
version:

> Meteor 0.9.3
> Macos X 10.9.5
> iOS Simulator Version 8.0 (550.1)
> Xcode Version 6.0.1 (6A317)

reproduction steps:

rm -rf $HOME/.meteor # just to be sure it's not related to old files
meteor create bug
cd bug
meteor add-plateform ios
meteor run ios

everything is fine until now. I edit a file (for example, in the .html, I change Welcome to Meteor into Welcome to Mobile). When I save the file, it reload correctly on browser and white screen on the ios simulator

I have to delete the app on the simulator and restart meteor run ios to have the displayed again (until I modify another file).

It's 100% reproductible on my computer.
It doesn't depend of which file you edit (same bug if you edit the css or js)
it's not only on ios simulator (same bug when I meteor run ios-device and run the app on my own iphone)

Here is the gist: https://gist.github.com/acemtp/7f4e593a5338c265ad12

I think it's related this log:

> FileTransferError {
> I20140926-10:39:03.451(2)? (ios)     body = "Could not create path to save downloaded file: The operation couldn\U2019t be completed. (Cocoa error 516.)";
> I20140926-10:39:03.452(2)? (ios)     code = 1;
> I20140926-10:39:03.452(2)? (ios)     "http_status" = 200;
> I20140926-10:39:03.452(2)? (ios)     source = "http://localhost:3000/__cordova/packages/base64.js?7dcMRCujD5vRDPYM7";
> I20140926-10:39:03.453(2)? (ios)     target = "file:///Users/acemtp/Library/Developer/CoreSimulator/Devices/B7FE6E00-132A-48F3-915D-B38DD72D3EA5/data/Containers/Data/Application/A6B3ADA4-F425-43AB-B49C-AC437D3A7979/Documents/meteor/b012c0dc93ff395296fdac654efcc0b43192e4f5/packages/base64.js";
> I20140926-10:39:03.453(2)? (ios) }
> I20140926-10:39:03.453(2)? (ios) File Transfer Error: Could not create path to save downloaded file: The operation couldn’t be completed. (Cocoa error 516.)

But I have no idea of why it cannot create path.

the file `Users/acemtp/Library/Developer/CoreSimulator/Devices/B7FE6E00-132A-48F3-915D-B38DD72D3EA5/data/Containers/Data/Application/A6B3ADA4-F425-43AB-B49C-AC437D3A7979/Documents/meteor/b012c0dc93ff395296fdac654efcc0b43192e4f5/packages/base64.js`exists and have the good mod, same for the directory packages.

> ❯ ll /Users/acemtp/Library/Developer/CoreSimulator/Devices/B7FE6E00-132A-48F3-915D-B38DD72D3EA5/data/Containers/Data/Application/A6B3ADA4-F425-43AB-B49C-AC437D3A7979/Documents/meteor/b012c0dc93ff395296fdac654efcc0b43192e4f5/packages/
> total 7920
> drwxr-xr-x  43 acemtp  staff     1462 26 sep 10:39 .
> drwxr-xr-x   8 acemtp  staff      272 26 sep 10:39 ..
> -rw-r--r--   1 acemtp  staff     1485 26 sep 10:39 application-configuration.js
> -rw-r--r--   1 acemtp  staff     1293 26 sep 10:39 autopublish.js
> -rw-r--r--   1 acemtp  staff    26240 26 sep 10:39 autoupdate.js
> -rw-r--r--   1 acemtp  staff    15685 26 sep 10:39 base64.js
> -rw-r--r--   1 acemtp  staff   380068 26 sep 10:39 blaze.js
> ...

**Comment by touins14** [comment]
I got the same error but solved just by simply turning off the wifi of my device and then turning it on.
