### ISSUE TITLE
 Meteor.wrapAsync(func, [context]) can be called Anywhere ?

### ISSUE THREAD

**Issue by lampe** [meteor/meteor#2694]
Hey,

http://docs.meteor.com/#meteor_wrapasync there is the info that you can call it Anywhere?

is this correct ?

**Comment by adamgins** [comment]
@estark37 sorry a bit confused... are you saying I can't use wrapAsynch... I was trying to use it like so https://forums.meteor.com/t/getting-wrapasync-to-work-on-the-client-with-meteor-subscribe-cordova-contacts/3570 is that not supported?

**Comment by jaredtmartin** [comment]
I'm also confused. Can we or can't we wrap function with async on the client?
