### ISSUE TITLE
Tracker.autorun does not save Meteor-EnvironmentVars

### ISSUE THREAD

**Issue by mcbain** [meteor/meteor#2695]
The tiny-test for Meteor.setTimout works, the one for Tracker.autorun fails in the 2nd run, because env-state is not saved. As a workaround one have to use Meteor.bindEnvironment to wrap autorun function.

```
TinyTest.addAsync('timeout should keep env-vars', function (test, complete) {
  var x = new Meteor.EnvironmentVariable();

  x.withValue('A', function () {
    Meteor.setTimeout(function () {
      test.equal(x.get(), 'A');
      complete();
    }, 1)
  });
});

TinyTest.addAsync('autorun should keep env-vars', function (test, complete) {
  var x = new Meteor.EnvironmentVariable();

  var d = new Tracker.Dependency();

  x.withValue('A', function () {
    Tracker.autorun(function (c) {
      test.equal(x.get(), 'A');

      if (!c.firstRun) {
        complete();
      }

      d.depend();
    })
  });

  d.changed();
});
```

**Comment by mitar** [comment]
Could maybe this be optional? I would prefer that also on the client setTimeout is patched. :-) If this means that the same code can run both on the client and server.

**Comment by mitar** [comment]
See [this package](https://github.com/Diggsey/meteor-server-deps/blob/master/lib/server-deps.coffee).

**Comment by mitar** [comment]
I made this package: https://github.com/peerlibrary/meteor-server-autorun
