### ISSUE TITLE
documentation for Session.setDefault is confusing

### ISSUE THREAD

**Issue by dradetsky** [meteor/meteor#2701]
Reading the documentation would lead you to believe

```
Session.setDefault('foo', 3)
Session.set('foo', undefined)
Session.setDefault('foo', 4)
Session.get('foo') // => 4
```

when in fact it will return undefined. Inexperienced developers will see Session.get('foo') returning undefined (rather than 'undefined') and be baffled. The docs should at least say that the above get will not return 4, even if explaining why is beyond the scope of the docs.

PS: Dear Meteor Core Team: Last time I sent one of these, it was unceremoniously closed. If you don't recognize the concept of "Bug in the Documentation" (fair enough; it's your project), let me know and I'll stop sending them.

**Comment by Cerealkillerway** [comment]
I have to say that as a new Meteor user, reading the Session.setDefault's documentation I've supposed exactly the behaviour that dradetsky wrote on his first post;
What is confusing in my opinion is this sentence: "Otherwise works exactly the same as Session.set".
For me that means that if the Session variable has been set before, then Session.setDefault will work same as Session.set, and so it will set the value; that's why I've found this issue while looking for clarifications ;)

**Comment by davidefendi** [comment]
help me for it's...---->>>>   ???

**Comment by mikkelking** [comment]
I reckon it is broken. This code is based on @lukejagodzinski code above, and if the first Session.set isn't called, then it works as he says, but with it there, it always returns undefined. I think it's more than a documentation problem

```
const testName = "borked"
Session.set(testName, null);
console.log("1 (expecting undefined)",Session.get(testName)); // undefined

Session.setDefault(testName, 'test1');
console.log("2 (expecting test1)",Session.get(testName)); // test1

Session.setDefault(testName, undefined);
console.log("3 (expecting test1",Session.get(testName)); // test1

Session.setDefault(testName, null);
console.log("4 (expecting test1)",Session.get(testName)); // test1

Session.setDefault(testName, 'test5');
console.log("5 (expecting test1)",Session.get(testName)); // test1

```

**Comment by lukejagodzinski** [comment]
When you take a look at the code of the `Session.setDefault` function, its only job is to set a value of the key that does not exist yet in the session. Session has the `Session.keys` object. The `Session.setDefault` function checks if a key being set exists in the `Session.keys`. If not then it will "set default value". It's almost like `Session.set` with that difference that `Session.set` will always set value, so it can override the current one.

And documentation says:

> Set a variable in the session if it hasn't been set before. Otherwise works exactly the same as Session.set.

So for me, it looks exactly the same what I've described. Of course, a little bit more information would always be welcomed.
