### ISSUE TITLE
Support Cordova Windows Phone 8/8.1

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#2722]
**_22 Upvotes**_ It's great that you support Cordova for Andorid and IOS but without WP8/WP8.1 our customers would never consider meteor.

**Comment by dotnetwise** [comment]
So now you have good support on windows. What about supporting windows phone 8.1 as well?

**Comment by bd-arc** [comment]
I second that. This would be awesome, since most of our clients require Windows Phone App as well. Unfortunately, the lack of support currently prevents our company from using Meteor in a production environment...

**Comment by Exilz** [comment]
@bd-arc +1

**Comment by laosb** [comment]
Second that, too.

And looking forward to Microsoft's Windows 10.

**Comment by dotnetwise** [comment]
Can you put it also on trello card so we know when will it be at least considered on the roadmap?

Thank you?

**Comment by vtntimo** [comment]
+1 for Windows Phone support. In Finland, WP has a large market share (over 20%), and it is very much hurting us right now after we went all Meteor.

**Comment by jsacra** [comment]
Another +1 for Windows Phone support.  It's definitely gaining ground...

**Comment by vNakamura** [comment]
+1. I probably won't be able to use Meteor for my next project because of the lack of Windows Phone support.

**Comment by marcingolenia** [comment]
+1 for Windows Phone support.

**Comment by delueg** [comment]
+1 for Windows ( even if i won´t do it and don´t like Windows ) just because same reason as @vNakamura

**Comment by pmp0x** [comment]
+1 for WindowsPhone

**Comment by john-osullivan** [comment]
What with the upcoming tools by Microsoft to allow for easily converting Android apps into Windows Phone 10 ones, it seems like adding in Windows Phone support could be relatively easy.  Has anyone on the team explored how these tools play with Meteor?

https://msdn.microsoft.com/en-us/library/windows/apps/Hh394031(v=VS.105).aspx

**Comment by claudiorafaels** [comment]
+1 for Windows Phone support.

**Comment by vtntimo** [comment]
Any updates on this?

**Comment by andrelug** [comment]
+1 for Windows Phone!

**Comment by ofcapl** [comment]
+1 for Windows Phone! In Poland there's a huge market for WP and many clients wants to support it.

**Comment by JStiller** [comment]
+1 for Windows for universal apps that includes windows phone but further more windows it self and xbox.

**Comment by jannesiera** [comment]
+1

**Comment by loevda** [comment]
+1 for Windows Phone

**Comment by pomarc** [comment]
+ for Windows Phone

**Comment by divzip** [comment]
+1 for Windows Phone

**Comment by d62remi** [comment]
+1 for poland market too :smiley:

**Comment by HedCET** [comment]
+1

**Comment by mcahornsirup** [comment]
+1

**Comment by divzip** [comment]
+1 Sweden

**Comment by pavankumarkatakam** [comment]
+1, if it also support WP then its ultimate you know ?

**Comment by alexbispo** [comment]
+1 Brazil

**Comment by BuffRobotiX** [comment]
+1 USA

**Comment by vtntimo** [comment]
Any news on this?

**Comment by DavidDono** [comment]
+1

**Comment by mburger81** [comment]
:+1: news?

**Comment by jthrons69** [comment]
Cancel me from meteor/meteor

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 29, 2016 at 2:12 AM, Timo<notifications@github.com> wrote:   
Any news on this?

**Comment by fschaeffler** [comment]
+1

**Comment by fschaeffler** [comment]
@Slava you mentioned win.meteor.com. As the meteor-hosting isn't available anymore, do you know where to checkout source code for that one?

**Comment by der-ede** [comment]
+1 for Windows Phone

**Comment by JavaWarrior** [comment]
+1 for Windows Phone. meteor now is widely used and needs this.

**Comment by mahmoudsalah1993** [comment]
+1 for windows phone

**Comment by der-ede** [comment]
Then again, would it be possible to develop something with the ddp.js client available? A web socket connection from js to the meteor server?
That is how the react native implementation functions so far, right?

**Comment by BuffRobotiX** [comment]
It's definitely possible to make a webapp that uses ddp.js or asteroid to connect to a meteor server and build that as a Windows phone app with Cordova, but it won't be using Blaze, Handlebars, minimongo, or Meteor's build tools. Meteor's system is very closed off and you can't get those tools by themselves, you'd have to use a different front end framework.

**Comment by der-ede** [comment]
Hi @David,

Right, I forgot. But didn't I see a meteor react native implementation that
still allows collection.find etc on the client?
I mean, Instead of blaze I could use angular.



Am Dienstag, 9. August 2016 schrieb David F. Buff :

**Comment by BuffRobotiX** [comment]
@der-ede Yeah, there are ddp clients for a lot of languages that allow you to connect to a meteor server. See here for a list of the ddp libraries http://meteorpedia.com/read/DDP_Clients
You could use any front end framework if you want. Angular 2 should be fine but I'd recommend against Angular 1 because it runs very poorly on mobile.

**Comment by der-ede** [comment]
@BuffRobotiX Thank you, maybe that is why I ran into problems with ngClick today. In the end it will be React/React Native anyway I guess, Apollo looks promising.
And Microsoft apparently will support React Native (https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/). Maybe then someone buys their phones.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20Cordova%20Windows%20Phone%208%2F8.1&body=Migrated%20from:%20meteor/meteor%232722) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
