### ISSUE TITLE
Allow specifying a comparator function for sorting a cursor

### ISSUE THREAD

**Issue by atrigent** [meteor/meteor#2730]
I couldn't find any existing tickets requesting this - my apologies if I missed it.

When a sort is requested using the `sort` option of `Collection#find` on the client side, it looks to me as if that sorting is done entirely on the client side. The mongo sort spec is converted into a comparator by a `Minimongo.Sorter` object which is simply passed to the built-in sort function. I would like the ability to simply specify the comparator directly. Currently, I can do this:

```
var cursor = MyCollection.find(query);
cursor.sorter = {
  getComparator: function() {
    return function(a, b) {
      // return 0, 1, or -1
    }
  }
};
```

This is essentially mimicking the interface of a `Minimongo.Sorter` object. It seems to work, but it involves mucking with the internals of cursors a little more than I'm comfortable with. `Minimongo.Sorter` contains a lot of code which I'm not duplicating and whose purpose I'm not sure of, so this might be missing something important.

Would it be possible to get a better and more official API for doing this? The following seems like it would be ideal:

```
MyCollection.find(query, {
  sort: function(a, b) {
    // return 0, 1, or -1
  }
});
```

Thanks.

**Comment by jagi** [comment]
I would like to reopen this issue. Providing custom sorting function would be handy as there is no `aggregate` method that could solve sorting with joins.

**Comment by JonathanHindi** [comment]
I would like to +1 for this as well.

**Comment by grsabreu** [comment]
Interesting

**Comment by mitar** [comment]
I needed this many times in the past, and now again. There is no other way to do something like:

```javascript
Posts.find({_id: {$in: listOfIds}}, {sort: sortByList(listOfIds)})
```

So, to get cursor of documents in the order of array of ids you have. Doing `fetch()` and then sort in JavaScript is inefficient inside a reactive context/Blaze.

Some more discussion on the topic:
* https://stackoverflow.com/questions/22797768/does-mongodbs-in-clause-guarantee-order

**Comment by mitar** [comment]
@glasser, this ticket should probably now be reopened and labeled as feature request and PR welcome.

**Comment by mitar** [comment]
I made a pull request: #6008.

**Comment by ephemer** [comment]
Just ran into this issue. It'd be ideal if Mongo just had a `$inAndSortedBy: Array` operator, but in the meantime this would be great.

**Comment by mitar** [comment]
Care to open a ticket in MongoDB for this and link it here? ;-)

**Comment by stubailo** [comment]
Going to merge the PR in 5 mins.

**Comment by ephemer** [comment]
@mitar it's a bit of a pipe dream, I gather db-level sorting of this kind isn't particularly performant, so we're probably better of just doing it on the client as per your PR

**Comment by MasterAM** [comment]
@stubailo, it seems that the `mongo` collection query spec should have been updated to reflect this (potentially creating a client variant). 

Right now, the `MyCollection.find({...}, {sort: myFn})` throws a `Match` error (due to [this line](https://github.com/meteor/meteor/blob/abe2c5e01121ef7734373ae215c95a44bf5f944e/packages/mongo/collection.js#L258)).

**Comment by mitar** [comment]
Oh, I missed this because I was testing only against Minimongo directly, not LocalCollection.

Would you care to create a pull request fixing this?

Also, local collections can be both on the client and server side, not just client.

**Comment by MasterAM** [comment]
Sure. 

@mitar, should we allow a function to be passed as the sort clause?

If we simply add `Function` to the spec, it works just fine with `LocalCollection` but will throw an error about the `sort` clause for `MongoInternals`.

Is this trivial solution acceptable, or should I set the spec based on the driver?

**Comment by hwillson** [comment]
This issue was resolved by PR's #6008 and #7164. Closing - thanks all!

**Comment by mitar** [comment]
Was it ever documented in proper docs (not just README)?

**Comment by abernix** [comment]
@mitar Good question.  I don't see anything linked to your PR and I suspect it should be here: https://docs.meteor.com/api/collections.html#sortspecifiers.  Maybe open an issue with `docs`?  If you can't just ping back and I'll do it.

**Comment by mitar** [comment]
I am at the moment a bit swamped with other things. :-(

**Comment by abernix** [comment]
Issue opened, thanks, @mitar

**Comment by dpatte** [comment]
It may just be my particular use-case, but supporting client side sorting using javascript functions, as implemented here, it one of the most useful features recently added to meteor!

I am the architect/designer of a commercial Meteor SaaS CRM product for sales management, and its just luck I discovered this change to sort specifiers this past week. The documentation seems a bit weak, but i looked it over and wondered if something like MyCollection._collection.find({},{sort:myFunc}) would work, and indeed it does! This means I can now sort alphas ignoring case (among other odd sorts) directly from the minimongo local colelction, and at the same time maintain reactivity as it changes.
Absolutly FANTABULOUS!

**Comment by dpatte** [comment]
All we need now is to support a custom filter function, and I'll be all set... Something like
MyCollection._collection.find({filter:myFilterFunc}) would be VERY handy. I could then filter using cross-collection logic.

**Comment by mitar** [comment]
You can do `MyCollection.collection.find().fetch().filter(myFilterFunc)`. :-)

**Comment by dpatte** [comment]
But don't I lose reactivity per document using fetch? The key to my enthusiasm is that the new sort maintains reactivity per document, whereas a fetch.forEach never did.

**Comment by mitar** [comment]
Not sure what you mean reactivity per document?
