### ISSUE TITLE
Web Workers, and pre-processors compatibility.

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#2751]
I've been coding on some beat detection/rhythm filtering stuff for a game, and everything is fine. I decided to refactor some of the code from  [createScriptProcessor](http://webaudio.github.io/web-audio-api/#widl-AudioContext-createScriptProcessor-ScriptProcessorNode-unsigned-long-bufferSize-unsigned-long-numberOfInputChannels-unsigned-long-numberOfOutputChannels) to web audio workers. As the API is deprecated and Web Workers are the [replacement](http://webaudio.github.io/web-audio-api/#the-audioworker).

Web Workers, must be served from a [URL](http://webaudio.github.io/web-audio-api/#widl-AudioContext-createAudioWorker-AudioWorkerNode-DOMString-scriptURL-unsigned-long-numberOfInputChannels-unsigned-long-numberOfOutputChannels), this presents two problems.
1. The file (javascript) should NOT be served with all other bundled javascript files
2. The file may still require pre-processors, such as `coffeescript`.

Both 1 & 2 are current issues. 

Currently the only solution is to the serve files from `public/`. This does not take into account the usage of pre-processor.

Perhaps, as a solution and rather then potentially cluttering public, we could allow for a special extension name: `<filename>.worker.js`, `audio.worker.js`, `audio.worker.coffee`, where the worker extension denotes a file to be bundled and processed, but not served until requested.

Thoughts?

**Comment by mitar** [comment]
See https://github.com/meteor/meteor/issues/6222 for a proposal how to address this.
