### ISSUE TITLE
Allow packages to load NPM dependencies from dependent packages

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2759]
I just published an updated version of [mizzao:sharejs](https://github.com/mizzao/meteor-sharejs) and saw the following message:

```
WARNING: Your package contains binary code and is only compatible with os.linux.x86_64 architecture.
Please use publish-for-arch to publish new builds of the package.
```

This package doesn't really have separate native dependencies, though. It just wants the same mongodb that is already being used by Meteor, although we have to specify this manually right now:

```
Npm.depends({
  share: "0.6.3",
  /*
      Mongo version used in 0.9 - we just use MongoInternals.
      Grabbed from https://github.com/meteor/meteor/blob/devel/packages/mongo/package.js
      Update this whenever we target a new Meteor version.
      This is necessary for ShareJS to require("mongodb") and not complain.
  */
  mongodb: "https://github.com/meteor/node-mongodb-native/tarball/cbd6220ee17c3178d20672b4a1df80f82f97d4c1"
});
```

What would be really nice would be the ability to pull in NPM dependencies that are the same version that some other package is using, similar to what `versionsFrom` is doing already for Meteor packages. Something like the following, which would throw an error if the package in question is not using the listed NPM dependency.

```
Npm.depends({
  share: "0.6.3",
  mongodb: {from: "mongo"}
});
```

What we have to do right now is very error-prone because we need to update this NPM version every time Meteor bumps the version, or risk pulling in an old mongodb client. Additionally, we need to `publish-for-arch` every version of the package even though this is just bundling a mongodb client that is the same version that Meteor is already using.

Would the above solution be satisfactory, or do you have a better idea?

**Comment by mitar** [comment]
Could this be reopen now that feature request can be tracked here?

**Comment by mizzao** [comment]
I basically have a package that wants to use the same `mongodb` that Meteor is using. However, I can't do that - I have to specify the `Npm.depends` myself, and this in turn results in some very unnecessary binary build crap for my package that will also break when used with the wrong version of meteor.

I can think of a really simple fix for this: a second argument to `Npm.require(package, context)`. Then, `Npm.require("mongodb", "mongo")` will grab the `mongodb` Npm package that was loaded by the `mongodb` Meteor package. Wouldn't that be straightforward enough to implement, as all the machinery is already in place?

**Comment by mitar** [comment]
> will grab the `mongodb` Npm package that was loaded by the `mongodb` Meteor package. 

The last `mongodb` should be `mongo`, no?

**Comment by mizzao** [comment]
Yes, and we could also consider putting this syntax inside `Npm.depends` instead of `Npm.require`.

**Comment by mitar** [comment]
Or maybe `api.use('mongo', ['npm'])` would provide all NPM packages from `mongo` package to this package.

**Comment by mizzao** [comment]
Yep, that would be a clearer version of the syntax I proposed in the original post :)

**Comment by glasser** [comment]
I still feel like, by default, packages should be able to keep their npm dependencies as an internal implementation detail rather than as part of their public API. But I'd like to start a pattern for having packages expose their npm dependencies as a choice in their API.  See https://rbcommons.com/s/meteor/r/13/diff/

**Comment by mitar** [comment]
Yes, but until that exposed NPM dependencies information is not available in `package.js`, then this is not really useful?

And why would not this be available automatically? So through some registry, maybe as part of `Packages` object?

**Comment by mitar** [comment]
In some way it would be great that you could access all information of the package through `Packages`, same as it is available through `meteor info`.

**Comment by glasser** [comment]
This is analogous to `Package`, which only contains the explicitly-declared exported variables, and not the package-scoped variables.
