### ISSUE TITLE
Unexpected mongo exit code 100

### ISSUE THREAD

**Issue by ChadMartinson** [meteor/meteor#2772]
It was working and now it isn't all of a sudden.  I start meteor and this is what I get.

```
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
```

I am using 0.9.3.1 

I have been working on this project for quite a while now so I don't know why it quit all of a sudden.  I ran a fresh install and so it's not a corrupted.  The only thing I can think is that I am running linux mint and there may have been some weird security updates because of that shellshock issue with mac and linux.  I know there have been a few bash updates.

I do have MongoDB installed locally and that is working just fine.

**Comment by cuginoAle** [comment]
@hitchcott, thanks that worked for me too!

**Comment by daraone** [comment]
It worked , but will have no data

**Comment by stvenyin** [comment]
YES,i use WSL Windows on linux appear this problem

**Comment by stvenyin** [comment]
![Untitled3](https://user-images.githubusercontent.com/32395964/54261468-d14ec980-45a6-11e9-8898-df90475442e6.png)
