### ISSUE TITLE
Why script tags are removed after triple brackets rendering?

### ISSUE THREAD

**Issue by LeCoupa** [meteor/meteor#2778]
Hello, I have a simple document like the one below that contains some text and a script tag.

```
{
  "content" : "The following script tag is removed after the triple brackets rendering\n\n<script>console.log(\"hello\");</script>",
}
```

When I render it with the triple brackets `{{{content}}}`, the text is displayed but the script tag doesn't even appear in the DOM (it is also not evaluated).

What's the good way to proceed? I thought that the triple brackets rendered html tags but it doesn't seem to work with script tags on my side.

**Comment by Slava** [comment]
Hey there.

After some investigation, it looks like Blaze uses jQuery to set the new content in the template. More specifically, Meteor uses [`$.parseHTML`](http://api.jquery.com/jquery.parsehtml/) which removes the `script` tags by default. It would keep them if you pass an additional second option to be `true` to the `keepScripts` option.  Blaze doesn't do this.

Now there is a choice: should Blaze always parse scripts or create a separate syntax for this super unsafe insertion (like quadruple stash or something similar: `{{{{superUnsafeStuff}}}}`).

**Comment by unwitting** [comment]
Is there a discussion on this? Would be a very nice feature and easy to implement?

**Comment by AntonAL** [comment]
I also would like to have a feature to render script tags to be able to insert google analytics and other counters codes to pages.

**Comment by laosb** [comment]
This should be move to `meteor/blaze`.

**Comment by hwillson** [comment]
Moved to meteor/blaze#205 - closing here. Thanks!
