### ISSUE TITLE
Cordova white screen with meteor build

### ISSUE THREAD

**Issue by Jaspermid** [meteor/meteor#2782]
Hi everyone, 

First of all, love the cordova implementation in Meteor. I am having some issues with it though 

My app works great within the iOS simulator or phone when running it with meteor run. When I build it in a new directory (meteor build ../iosbuilds/updated -p 192.168.1.13:3000) however my app runs for a short while then I get a white screen. This seems to happen on whenever the page gets reloaded 

2014-10-08 19:38:08.406 noticedwhat[653:60b] Resetting plugins due to page load.
2014-10-08 19:38:08.482 noticedwhat[653:60b] Finished load of: http://192.168.1.12:33084/friend/eNHMg3KJu97dPGKC

Is this a Hot Code push issue? 

My app is at https://github.com/Jaspermid/Noticed. Problem can be replicated by 
- Cloning
- Meteor build 
- Test on iPhone 
- When using should go to white screen within 5 minutes (if not try camera functionality)

Hope you can help out, have asked Meteor experts but they recommended I report this as an issue as we can;t find any bugs in the code itself. To be clear bug does not appear in any other platform/simulator. 

Hope you can help out!

**Comment by MoeBadr** [comment]
Hey All, I'm still having the issue. This is not a consistent issue, during some pushes the app gets updated and works fine and sometimes the app ends up with a white screen. The only way to resolve the issue once the app is on the white screen is to reinstall the app and at that point it gets updated without any issues. is anyone still experience this ?
