### ISSUE TITLE
Add ability to set cookies in HTTP.call

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#2791]
I noticed that the request() call is setting the `jar` property to false, therefore killing all cookie support. Are you guys able to somehow expose the tough-cookie functionality so that we can set custom cookies as shown here: https://github.com/mikeal/request#requestcookie

Here's the custom cookie functionality example as shown on the aforementioned page:

```
var j = request.jar();
var cookie = request.cookie('key1=value1');
var url = 'http://www.google.com';
j.setCookieSync(cookie, url);
request({url: url, jar: j}, function () {
  request('http://images.google.com')
})
```

**Comment by mitar** [comment]
Hm, but it is not possible to allow passing credentials using `withCredentials`?

**Comment by rclai** [comment]
I think you just concatenate it in the URL.

**Comment by glasser** [comment]
Great to hear you solved this problem!

@mitar I thought withCredentials is client-side?

**Comment by mitar** [comment]
Oh, I thought this ticket was about client side. My mistake.
