### ISSUE TITLE
Mongo package fails to report closure of inactive cursors.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#2792]
If the Mongo server closes an "inactive cursor" [1], no error is reported to the application.

Reproduction: https://github.com/tmeasday/migration-test/tree/timeout [timeout branch].
1. Run the app.
2. Notice it prints:

```
I20141010-16:05:28.665(11) (migration-test.js:16) There are 10 documents
I20141010-16:20:28.727(11) (migration-test.js:23) 1
I20141010-16:20:28.730(11) (migration-test.js:26) The loop ran 1 times
```

I would expect it to either run 10 times or throw some kind of exception.

This can be quite a headscratcher, eg. when running large migrations (cf https://groups.google.com/forum/#!msg/meteor-talk/UIIfRSVR93M/jJDhfKweke8J)

[1] See http://docs.mongodb.org/manual/core/cursors/#closure-of-inactive-cursors

**Comment by glasser** [comment]
Unfortunately, it doesn't look like I got to this as part of the 1.0.4 maintenance work. I do agree that it does seem important and definitely encourage folks to investigate it.

**Comment by hwillson** [comment]
I've verified this is no longer an issue with Meteor 1.5.1. As expected, a `MongoError: Cursor not found, cursor id: 35727810183` error is thrown. Closing - thanks!
