### ISSUE TITLE
Allow multiple created, rendered and destroyed callbacks on templates

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2805]
Deprecate `Template.someTemplate.rendered = ...` syntax  and instead provide:

```
Template.someTemplate.rendered(function () {

})
```

which can be called multiple times to register a series of hooks. This improves modularity and reusability of components.

**Comment by PeppeL-G** [comment]
Another pro is that you get an error message if you by accident misspell the property. For example, `Template.myTemplate.rendred = function(){}` won't raise an error, while `Template.myTemplate.onRendred(function(){})` will.

**Comment by Slava** [comment]
https://github.com/meteor/meteor/pull/3171 related

**Comment by aldeed** [comment]
FYI, [template-extension pkg](https://github.com/aldeed/meteor-template-extension) has support for this.

**Comment by mitar** [comment]
I think this is coming out in [next Meteor version](https://github.com/meteor/meteor/blob/devel/History.md).

**Comment by Slava** [comment]
This is released!
