### ISSUE TITLE
No Whitespace Control Syntax

### ISSUE THREAD

**Issue by jchristman** [meteor/meteor#2816]
This issue is a proposal for a syntax to be added to Blaze/Spacebars that would allow for whitespace control, similar to that introduced in Handlebars 1.1. The relevant pull request for the Handlebars whitespace control is shown at https://github.com/wycats/handlebars.js/pull/336.

I made an example project to demonstrate this problem at https://github.com/suntzuII/meteor-whitespace-control. The following command will execute the project.

```
git clone https://github.com/suntzuII/meteor-whitespace-control.git
cd meteor-whitespace-control
meteor
```

When you open the page in a web browser, you will see something like:

```
Whitespace Control Example
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
example start,
middle
, example end
```

The addition of whitespace-control would allow this to look like:

```
Whitespace Control Example
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
example start, middle, example end
```

The main issue seems to be that the Handlebars.SafeString() creates new lines on HTML tags, which then get interpreted as newlines in the HTML. If there were an option where we could render a context without whitespace, like {{~display_data~}}, this problem could be avoided.

**Comment by hypno2000** [comment]
This affects css :empty pseudo class. A good example is growl container where growl container includes top and bottom border and their original css wont work with simple {{each}} inside the container. Needed to remove the whitespace before and after the each tags and add comment to others so they dont remove it as it looks like code formating mistake :( not ideal.
