### ISSUE TITLE
Feature request: `meteor logs -f site-name` and/or  `meteor logs -n 500 site-name`

### ISSUE THREAD

**Issue by possibilities** [meteor/meteor#284]
Would be lovely if `meteor logs` had some options similar to `tail` so we can follow a log in realtime and/or request n lines from the log. -Mike

**Comment by ccorcos** [comment]
+1

**Comment by betacar** [comment]
+1

**Comment by lemmycaution** [comment]
+1

**Comment by joaopiopedreira** [comment]
+1

On 25 September 2015 at 18:06, onur uyar < notifications@github.com > wrote:
+1

**Comment by morenoh149** [comment]
+1
