### ISSUE TITLE
Blaze diffs arrays incorrectly

### ISSUE THREAD

**Issue by nkoren** [meteor/meteor#2845]
I encountered this bug while working on jQuery sortables (drag-and-drop re-orderable lists). At first I thought that I'd stumbled across #2003, but upon further digging I'm satisfied that it's a much more general problem with the way that Blaze manages DOM updates, since it can be made to happen without sortables in the mix.

The problem occurs when Spacebars  renders an Session array which changes in a particular way -- namely, if the first element is placed in the second-to-last position. (There are other triggers, but this is one of the more obvious ones). The bug can be reproduced as follows:

Template:
```html
<template name="test">
    {{#each colors}}
        {{ this }},
    {{/each}}
</template>
```

Javascript:
```javascript
Template.test.helpers({
    colors: function() {
        return Session.get( "colors" );
    }
});
```

Now in the console:
```javascript:
> Session.set( "colors", ["red","orange","yellow","green","blue"]);
// renders: "red, orange, yellow, green, blue," -- as expected

> Session.set( "colors", ["orange","yellow","green","red","blue"]);
// renders: "orange, yellow, green, blue, red" --  "blue" and "red" have been swapped!
```

At this point the screen rendering and the Session variable are out of sync with each other, which is unfortunate in any circumstance, but breaks the functionality of a sortable list entirely, since subsequent sorts will cause what's rendered to the screen to increasingly diverge from the contents of the array.

For now I'm using a workaround which produces an annoying flicker but at least it keeps the Session variables and the screen rendering intact:

```javascript
var setColors = function( colors ) {
    Session.set( "colors", [] );
    Meteor.setTimeout( function() {
        Session.set( "colors", colors );
    }, 0);
}
```

If anybody can suggest a non-flickery workaround,  I'd be most thankful!

**Comment by nkoren** [comment]
*bump*. Just ran into this issue again. It's pretty annoying, since it means I can't rely on the order of items in a list being rendered accurately to the screen. Anybody know how to fix it?

**Comment by Slava** [comment]
@nkoren Thanks for a clear and small reproduction!

This is indeed a bug in `observe-sequence`, the translation layer between the diffing and the DOM manipulations in Blaze. The diffing itself was correct.

I pushed a fix on a branch and will wait for someone to review it.

See #3907.

**Comment by Slava** [comment]
Fixed on devel.

**Comment by nkoren** [comment]
@Slava -- Brilliant, thank you!

**Comment by avital** [comment]
Nice
