### ISSUE TITLE
Some commands refresh the package catalog unnecessarily

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#2846]
In Meteor 0.9.4 and earlier, we refreshed the package catalog at relatively unpredictable times; essentially, any time that a low level operation failed to find metadata that it was looking for. This led to behavior that was unpredictable for users and for core developers.  Sometimes we would fail to refresh when refreshing was necessary; in other cases we would uselessly refresh many times per command.  We were also very inconsistent as to how refresh errors were displayed and if they were treated as fatal.

For Meteor 1.0, we have implemented a much simpler approach: depending on the command, it may either never refresh, or refresh once on startup. The command can declare if an error in the refresh is fatal or not.  Commands that don't deal with your local packages and app never refresh (eg 'meteor logs').  Most other commands refresh once.  (In addition, long-running commands like 'meteor run' refresh every 15 minutes in the background, non-blocking.)

This is a much simpler and less bug-prone approach than the previous approach.  But it has the disadvantage that some common commands like 'run' always refresh even if nothing package-related has changed.  To fix this, we need to do some deeper refactorings.

Post-1.0, we will refactor build, deploy, run, debug, and test-packages to not refresh on startup.  However, they will be refactored to have a centralized "make sure local packages can be parsed and the constraint solver runs successfully" point in the code, with well-defined error handling. We will ensure that it is easy to differentiate between errors that could be fixed with a refresh vs other errors.  We will then put into place a much higher level version of the old retry-and-refresh: specifically, we will "refresh and retry" if the high-level "parse and solve constraints" operation fails in such a way that a refresh might help.

Errors that could be fixed with refresh:
- constraint solver not finding a solution
- api.versionsFrom unknown release (though see #2979)
- unknown package name or version in api.use
- unknown package name or version in .meteor/packages
- unknown package name or version in .meteor/versions (though this is a more recoverable error, since if we don't know something even post-refresh we can just ignore .meteor/versions)

(other examples marked with XXX #2846 in the code.)

As a workaround for now, you can disable catalog refreshing entirely by setting the METEOR_OFFLINE_CATALOG environment variable. This will prevent you from getting any package or release updates (including updates that will fix this bug!) so I would avoid setting it permanently for every command.

**Comment by SauronTheGreat** [comment]
Hey guys,
Sorry I do understand this is an old thread.
I just wanted to clarify that I was working on meteor 1.0.2.1 and stiff facing this issue.
I used the method suggested by @glasser  and downgraded and its better.
Can someone please guide me regarding the same?

Thanks and Apologies again for posting in a slightly old thread.

**Comment by glasser** [comment]
@SauronTheGreat Sorry, but you'll need to explain more clearly what you're seeing and what the problem is if you need any guidance.

**Comment by SauronTheGreat** [comment]
@glasser  thanks and apologies for not being clear. The build process when I make a change in the file takes too long. This basically increases my dev time significantly. 
The time taken is lesser when i use the command:
 sudo METEOR_OFFLINE_CATALOG=1 meteor --release glasser:TPS-PREVIEW@1.0.1  run


But in normal meteor run, it takes about 10-15s to build.
Please do let me know in case I need to provide any other info to help you.

**Comment by glasser** [comment]
When running 1.0.2.1 (not a TPS preview, not with environment variable set), what message is shown in the progress bar during the bulk of the slow build?

**Comment by SauronTheGreat** [comment]
Apart from my own console logs, it just says "=> Client modified -- refreshing" thats all.
No error message is appearing on the screen.

**Comment by SauronTheGreat** [comment]
Hey guys, any help would be appreciated. I have tried a bunch of things but to no avail. This is really frustrating. Mine is now a fairly big and complex application and this kind of behaviour is really increase my Dev time significantly.

**Comment by justinsb** [comment]
@SauronTheGreat It is tricky if there's no messages to provide us a hint - both for us and for you!  One thing to try is to try running with the (not-officially-supported-at-the-moment) env var `METEOR_LOG=debug`

i.e. try this and see if gives any more information about what is going on and what is happening during the slow build:

```METEOR_LOG=debug meteor run```

You can combine METEOR_LOG=debug with other options (e.g. offline catalog etc)

**Comment by SauronTheGreat** [comment]
@justinsb I tried it but there is not output on the console. Are there other places where logs are created ?
Putting in my packages list so check if it helps:


accounts-facebook      1.0.3  Login service for Facebook accounts
accounts-github        1.0.3  Login service for Github accounts
accounts-google        1.0.3  Login service for Google accounts
accounts-password      1.0.5  Password support for accounts
accounts-twitter       1.0.3  Login service for Twitter accounts
cfs:filesystem         0.1.1  Filesystem storage adapter for CollectionFS
cfs:gridfs             0.0.27  GridFS storage adapter for CollectionFS
cfs:standard-packages  0.5.3  Filesystem for Meteor, collectionFS
cfs:ui                 0.1.3  CollectionFS, provides UI helpers
chrismbeckett:toastr   2.1.0  Gnome / Growl type non-blocking notifications
coffeescript           1.0.5  Javascript dialect with fewer braces and semico...
email                  1.0.5  Send email messages
gadicohen:headers      0.0.26  Access HTTP headers on both server and client
gfk:mailgun-api        1.0.0  Mailgun API - Mailgun api implementation for Me...
insecure               1.0.2  Allow all database writes by default
iron:router            0.9.4* Routing specifically designed for Meteor
linto:fontawesome      4.2.6  fontawesome 4.2.0 re-packaged for meteorjs
meteor-platform        1.2.1  Include a standard set of Meteor packages in yo...
meteorhacks:npm        1.2.2  Use npm modules with your Meteor App
mizzao:bootstrap-3     3.3.1_1  HTML, CSS, and JS framework for developing re...
mizzao:jquery-ui       1.11.2  Simple lightweight pull-in for jQuery UI in Me...
npm-container          1.0.0+ Contains all your npm dependencies
reactive-dict          1.0.5  Reactive dictionary
service-configuration  1.0.3  Manage the configuration for third-party services

**Comment by SauronTheGreat** [comment]
Also I think it might be a file watcher issue as well because I can see that it takes about 4-5 secs for meteor to recognise that I have changed the file. I am on OSX(yosemite).

**Comment by justinsb** [comment]
Can you paste whatever output you do get from running with `METEOR_LOG=debug meteor run`?  (Probably in a gist, as I expect it will be big!)

**Comment by SauronTheGreat** [comment]
And that is exactly my issue. As i make a change(only a spelling change in html) all I get is client modified...refreshing..thats all

**Comment by jeffschmitz** [comment]
I'm running meteor 1.2.0.2 and still have very long restart times of 10+ seconds for what I would consider a fairly small application.  I've set METEOR_OFFLINE_CATALOG=1, and it helped a little, but most of the time is spent in the Building Application phase, with a second or two spent in Loading Plugin phases.
It's really killing productivity and the image of Meteor here at Boeing.  Anything else I can try to get the reload time sped up to just a second or two?  

Here's the log when starting up meteor:

=> Started proxy.
=> Started MongoDB.
Local package version is up-to-date: accounts-base@1.2.1
Local package version is up-to-date: accounts-password@1.1.3
Local package version is up-to-date: aldeed:collection2@2.5.0
Local package version is up-to-date: aldeed:simple-schema@1.3.3
Local package version is up-to-date: amplify@1.0.0
Local package version is up-to-date: anti:i18n@0.4.3
Local package version is up-to-date: aslagle:reactive-table@0.8.12
Local package version is up-to-date: autoupdate@1.2.3
Local package version is up-to-date: babel-compiler@5.8.24_1
Local package version is up-to-date: babel-runtime@0.1.4
Local package version is up-to-date: base64@1.0.4
Local package version is up-to-date: binary-heap@1.0.4
Local package version is up-to-date: blaze@2.1.3
Local package version is up-to-date: blaze-tools@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.4
Local package version is up-to-date: caching-compiler@1.0.0
Local package version is up-to-date: caching-html-compiler@1.0.2
Local package version is up-to-date: callback-hook@1.0.4
Local package version is up-to-date: cfs:access-point@0.1.49
Local package version is up-to-date: cfs:base-package@0.0.30
Local package version is up-to-date: cfs:collection@0.5.5
Local package version is up-to-date: cfs:collection-filters@0.2.4
Local package version is up-to-date: cfs:data-man@0.0.6
Local package version is up-to-date: cfs:file@0.1.17
Local package version is up-to-date: cfs:filesystem@0.1.2
Local package version is up-to-date: cfs:http-methods@0.0.30
Local package version is up-to-date: cfs:http-publish@0.0.13
Local package version is up-to-date: cfs:power-queue@0.9.11
Local package version is up-to-date: cfs:reactive-list@0.0.9
Local package version is up-to-date: cfs:reactive-property@0.0.4
Local package version is up-to-date: cfs:standard-packages@0.5.9
Local package version is up-to-date: cfs:storage-adapter@0.2.2
Local package version is up-to-date: cfs:tempstore@0.1.5
Local package version is up-to-date: cfs:upload-http@0.0.20
Local package version is up-to-date: cfs:worker@0.1.4
Local package version is up-to-date: check@1.0.6
Local package version is up-to-date: chhib:fast-csv@0.0.1
Local package version is up-to-date: coffeescript@1.0.10
Local package version is up-to-date: ddp@1.2.2
Local package version is up-to-date: ddp-client@1.2.1
Local package version is up-to-date: ddp-common@1.2.1
Local package version is up-to-date: ddp-rate-limiter@1.0.0
Local package version is up-to-date: ddp-server@1.2.1
Local package version is up-to-date: deps@1.0.9
Local package version is up-to-date: diff-sequence@1.0.1
Local package version is up-to-date: ecmascript@0.1.5
Local package version is up-to-date: ecmascript-collections@0.1.6
Local package version is up-to-date: ejson@1.0.7
Local package version is up-to-date: email@1.0.7
Local package version is up-to-date: fastclick@1.0.7
Local package version is up-to-date: geojson-utils@1.0.4
Local package version is up-to-date: harrison:papa-parse@1.1.0
Local package version is up-to-date: html-tools@1.0.5
Local package version is up-to-date: htmljs@1.0.5
Local package version is up-to-date: http@1.1.1
Local package version is up-to-date: ian:accounts-ui-bootstrap-3@1.2.80
Local package version is up-to-date: id-map@1.0.4
Local package version is up-to-date: iron:controller@1.0.8
Local package version is up-to-date: iron:core@1.0.8
Local package version is up-to-date: iron:dynamic-template@1.0.8
Local package version is up-to-date: iron:layout@1.0.8
Local package version is up-to-date: iron:location@1.0.9
Local package version is up-to-date: iron:middleware-stack@1.0.9
Local package version is up-to-date: iron:router@1.0.9
Local package version is up-to-date: iron:url@1.0.9
Local package version is up-to-date: jquery@1.11.4
Local package version is up-to-date: launch-screen@1.0.4
Local package version is up-to-date: ldk:casperjs@0.1.8
Local package version is up-to-date: less@2.5.0_3
Local package version is up-to-date: livedata@1.0.15
Local package version is up-to-date: localstorage@1.0.5
Local package version is up-to-date: logging@1.0.8
Local package version is up-to-date: matb33:collection-hooks@0.8.0
Local package version is up-to-date: meteor@1.1.9
Local package version is up-to-date: meteor-platform@1.2.3
Local package version is up-to-date: meteorhacks:aggregate@1.3.0
Local package version is up-to-date: meteorhacks:async@1.0.0
Local package version is up-to-date: meteorhacks:collection-utils@1.2.0
Local package version is up-to-date: meteorhacks:kadira@2.23.4
Local package version is up-to-date: meteorhacks:meteorx@1.3.1
Local package version is up-to-date: meteorhacks:npm@1.5.0
Local package version is up-to-date: mikowals:batch-insert@1.1.13
Local package version is up-to-date: minifiers@1.1.7
Local package version is up-to-date: minimongo@1.0.10
Local package version is up-to-date: mizzao:bootstrap-3@3.3.1_1
Local package version is up-to-date: mizzao:build-fetcher@0.2.0
Local package version is up-to-date: mizzao:jquery-ui@1.11.4
Local package version is up-to-date: mobile-status-bar@1.0.6
Local package version is up-to-date: momentjs:moment@2.10.6
Local package version is up-to-date: mongo@1.1.2
Local package version is up-to-date: mongo-id@1.0.1
Local package version is up-to-date: mongo-livedata@1.0.9
Local package version is up-to-date: mrt:moment@2.8.1
Local package version is up-to-date: mrt:moment-timezone@0.2.1
Local package version is up-to-date: npm-bcrypt@0.7.8_2
Local package version is up-to-date: npm-mongo@1.4.39_1
Local package version is up-to-date: observe-sequence@1.0.7
Local package version is up-to-date: ordered-dict@1.0.4
Local package version is up-to-date: package-version-parser@3.0.4
Local package version is up-to-date: pfafman:filesaver@0.2.1
Local package version is up-to-date: pfafman:font-awesome-4@4.4.0_3
Local package version is up-to-date: practicalmeteor:chai@2.1.0_1
Local package version is up-to-date: practicalmeteor:loglevel@1.2.0_2
Local package version is up-to-date: promise@0.5.0
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: random@1.0.4
Local package version is up-to-date: rate-limit@1.0.0
Local package version is up-to-date: reactive-dict@1.1.2
Local package version is up-to-date: reactive-var@1.0.6
Local package version is up-to-date: reload@1.1.4
Local package version is up-to-date: retry@1.0.4
Local package version is up-to-date: routepolicy@1.0.6
Local package version is up-to-date: sacha:spin@2.3.1
Local package version is up-to-date: sanjo:jasmine@0.20.0
Local package version is up-to-date: sanjo:karma@3.0.2
Local package version is up-to-date: sanjo:long-running-child-process@1.1.3
Local package version is up-to-date: sanjo:meteor-files-helpers@1.2.0_1
Local package version is up-to-date: sanjo:meteor-version@1.0.0
Local package version is up-to-date: service-configuration@1.0.5
Local package version is up-to-date: session@1.1.1
Local package version is up-to-date: sha@1.0.4
Local package version is up-to-date: simple:reactive-method@1.0.2
Local package version is up-to-date: spacebars@1.0.7
Local package version is up-to-date: spacebars-compiler@1.0.7
Local package version is up-to-date: srp@1.0.4
Local package version is up-to-date: standard-app-packages@1.0.6
Local package version is up-to-date: standard-minifiers@1.0.1
Local package version is up-to-date: stylus@2.511.0_2
Local package version is up-to-date: templates:tabs@2.2.0
Local package version is up-to-date: templating@1.1.4
Local package version is up-to-date: templating-tools@1.0.0
Local package version is up-to-date: tracker@1.0.9
Local package version is up-to-date: ui@1.0.8
Local package version is up-to-date: underscore@1.0.4
Local package version is up-to-date: url@1.0.5
Local package version is up-to-date: velocity:chokidar@1.0.3_1
Local package version is up-to-date: velocity:core@0.10.0
Local package version is up-to-date: velocity:html-reporter@0.9.0
Local package version is up-to-date: velocity:meteor-internals@1.1.0_7
Local package version is up-to-date: velocity:meteor-stubs@1.1.0
Local package version is up-to-date: velocity:shim@0.1.0
Local package version is up-to-date: velocity:source-map-support@0.3.2_1
Local package version is up-to-date: votercircle:winston@0.0.3
Local package version is up-to-date: webapp@1.2.2
Local package version is up-to-date: webapp-hashing@1.0.5
Local package version is up-to-date: zephraph:namespace@1.2.1
Doing HTTP request:  POST
https://www.meteor.com/oauth2/authorize?state=2d3363775f3f2bc74569ac948785f755&r
esponse_type=code&client_id=LdpZEt7ubqXAfkDJ2&redirect_uri=https%3A%2F%2Factivit
y.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
=> Started your app.

=> App running at: http://localhost:3000/ahmtrain/gc
   Type Control-C twice to stop.

I20151009-14:26:56.026(-5)? [velocity] casperjs is starting a mirror at http://l
ocalhost:55075/ahmtrain/gc/.
I20151009-14:26:56.027(-5)? [velocity] You can see the mirror logs at: tail -f C
:\Users\si454a\GIT Folders\ground-control\meteor\ground-control\.meteor\local\lo
g\casperjs.log

**Comment by tiansiyuan** [comment]
localhost% METEOR_LOG=debug meteor run
Opening db file /Users/tiansiyuan/.meteor/package-metadata/v2.0.1/packages.data.db
[[[[[ ~/Documents/craftbeer/code/craftbeer ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
Local package version is up-to-date: autopublish@1.0.4
Local package version is up-to-date: autoupdate@1.2.3
Local package version is up-to-date: babel-compiler@5.8.24_1
Local package version is up-to-date: babel-runtime@0.1.4
Local package version is up-to-date: base64@1.0.4
Local package version is up-to-date: binary-heap@1.0.4
Local package version is up-to-date: blaze@2.1.3
Local package version is up-to-date: blaze-html-templates@1.0.1
Local package version is up-to-date: blaze-tools@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.4
Local package version is up-to-date: caching-compiler@1.0.0
Local package version is up-to-date: caching-html-compiler@1.0.2
Local package version is up-to-date: callback-hook@1.0.4
Local package version is up-to-date: check@1.0.6
Local package version is up-to-date: ddp@1.2.2
Local package version is up-to-date: ddp-client@1.2.1
Local package version is up-to-date: ddp-common@1.2.1
Local package version is up-to-date: ddp-server@1.2.1
Local package version is up-to-date: deps@1.0.9
Local package version is up-to-date: diff-sequence@1.0.1
Local package version is up-to-date: ecmascript@0.1.5
Local package version is up-to-date: ecmascript-collections@0.1.6
Local package version is up-to-date: ejson@1.0.7
Local package version is up-to-date: es5-shim@4.1.13
Local package version is up-to-date: fastclick@1.0.7
Local package version is up-to-date: geojson-utils@1.0.4
Local package version is up-to-date: hot-code-push@1.0.0
Local package version is up-to-date: html-tools@1.0.5
Local package version is up-to-date: htmljs@1.0.5
Local package version is up-to-date: http@1.1.1
Local package version is up-to-date: id-map@1.0.4
Local package version is up-to-date: insecure@1.0.4
Local package version is up-to-date: jquery@1.11.4
Local package version is up-to-date: launch-screen@1.0.4
Local package version is up-to-date: livedata@1.0.15
Local package version is up-to-date: logging@1.0.8
Local package version is up-to-date: meteor@1.1.9
Local package version is up-to-date: meteor-base@1.0.1
Local package version is up-to-date: minifiers@1.1.7
Local package version is up-to-date: minimongo@1.0.10
Local package version is up-to-date: mobile-experience@1.0.1
Local package version is up-to-date: mobile-status-bar@1.0.6
Local package version is up-to-date: mongo@1.1.2
Local package version is up-to-date: mongo-id@1.0.1
Local package version is up-to-date: npm-mongo@1.4.39_1
Local package version is up-to-date: observe-sequence@1.0.7
Local package version is up-to-date: ordered-dict@1.0.4
Local package version is up-to-date: promise@0.5.0
Local package version is up-to-date: random@1.0.4
Local package version is up-to-date: reactive-dict@1.1.2
Local package version is up-to-date: reactive-var@1.0.6
Local package version is up-to-date: reload@1.1.4
Local package version is up-to-date: retry@1.0.4
Local package version is up-to-date: routepolicy@1.0.6
Local package version is up-to-date: session@1.1.1
Local package version is up-to-date: spacebars@1.0.7
Local package version is up-to-date: spacebars-compiler@1.0.7
Local package version is up-to-date: standard-minifiers@1.0.1
Local package version is up-to-date: templating@1.1.4
Local package version is up-to-date: templating-tools@1.0.0
Local package version is up-to-date: tracker@1.0.9
Local package version is up-to-date: ui@1.0.8 
Local package version is up-to-date: underscore@1.0.4
Local package version is up-to-date: url@1.0.5
Local package version is up-to-date: webapp@1.2.2
Local package version is up-to-date: webapp-hashing@1.0.5
   Building for web.browser                  |

**Comment by maitrid** [comment]
Same issue here. It takes about 8 - 9 seconds to restart in my case.

**Comment by CodeOfDavid** [comment]
Same here. Takes too long, I have the latest, fastest Mac running the latest version of OS and its still slow.

**Comment by GitYong** [comment]
Me too. It takes too long. Can I use some thing like `meteor run default` to start meteor without checking packages?

**Comment by chrishowes** [comment]
+1 on this.

I've set METEOR_DEBUG_SQL (and DEBUG_SQL, not sure which one is the right one)=1, and when running `meteor` and changing a file, I'm seeing:

```
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  1
Transaction took:  2
Transaction took:  2
Transaction took:  1
SQL statement  SELECT content FROM versions WHERE packageName=?  took  20
Transaction took:  21
Transaction took:  1
Transaction took:  1
Transaction took:  1
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  5
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  3
Transaction took:  1
Transaction took:  4
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  1
Transaction took:  3
Transaction took:  5
Transaction took:  2
Transaction took:  3
Transaction took:  1
Transaction took:  2
Transaction took:  1
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  5
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  4
Transaction took:  4
Transaction took:  4
Transaction took:  3
Transaction took:  1
Transaction took:  2
Transaction took:  1
Transaction took:  2
Transaction took:  4
Transaction took:  1
Transaction took:  2
Transaction took:  1
SQL statement  SELECT content FROM versions WHERE packageName=?  took  20
Transaction took:  21
Transaction took:  3
Transaction took:  1
Transaction took:  3
Transaction took:  5
Transaction took:  4
Transaction took:  4
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  4
Transaction took:  3
Transaction took:  2
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  1
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  5
Transaction took:  2
Transaction took:  0
Transaction took:  1
Transaction took:  2
Transaction took:  1
Transaction took:  4
Transaction took:  3
Transaction took:  4
Transaction took:  2
Transaction took:  2
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  5
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  1
Transaction took:  5
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  4
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  4
Transaction took:  1
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  4
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  3
Transaction took:  4
Transaction took:  2
Transaction took:  1
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  3
Transaction took:  2
Transaction took:  2
Transaction took:  1
Transaction took:  3
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  3
Transaction took:  3
Transaction took:  2
Transaction took:  4
Transaction took:  2
Transaction took:  2
Transaction took:  5
Transaction took:  1
Transaction took:  1
Transaction took:  3
Transaction took:  1
Transaction took:  2
Transaction took:  6
Transaction took:  2
Transaction took:  2
Transaction took:  2
Transaction took:  1
Transaction took:  2
Transaction took:  4
Transaction took:  6
Transaction took:  6
Transaction took:  1
Transaction took:  1
Transaction took:  2
Transaction took:  3
Transaction took:  4
Transaction took:  2
Local package version is up-to-date: accounts-base@1.2.2
Local package version is up-to-date: accounts-facebook@1.0.6
Local package version is up-to-date: accounts-google@1.0.6
Local package version is up-to-date: accounts-oauth@1.1.8
Local package version is up-to-date: accounts-password@1.1.4
Local package version is up-to-date: adrianliaw:youtube-iframe-api@1.3.122
Local package version is up-to-date: aldeed:autoform@5.7.1
Local package version is up-to-date: aldeed:collection2@2.5.0
Local package version is up-to-date: aldeed:simple-schema@1.3.3
Local package version is up-to-date: aldeed:template-extension@3.4.3
Local package version is up-to-date: autopublish@1.0.4
Local package version is up-to-date: autoupdate@1.2.4
Local package version is up-to-date: babel-compiler@5.8.24_1
Local package version is up-to-date: babel-runtime@0.1.4
Local package version is up-to-date: base64@1.0.4
Local package version is up-to-date: binary-heap@1.0.4
Local package version is up-to-date: blaze@2.1.3
Local package version is up-to-date: blaze-html-templates@1.0.1
Local package version is up-to-date: blaze-tools@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.4
Local package version is up-to-date: caching-compiler@1.0.0
Local package version is up-to-date: caching-html-compiler@1.0.2
Local package version is up-to-date: callback-hook@1.0.4
Local package version is up-to-date: check@1.1.0
Local package version is up-to-date: coffeescript@1.0.11
Local package version is up-to-date: copleykj:stripe-sync@2.0.5
Local package version is up-to-date: ddp@1.2.2
Local package version is up-to-date: ddp-client@1.2.1
Local package version is up-to-date: ddp-common@1.2.2
Local package version is up-to-date: ddp-rate-limiter@1.0.0
Local package version is up-to-date: ddp-server@1.2.2
Local package version is up-to-date: deps@1.0.9
Local package version is up-to-date: diff-sequence@1.0.1
Local package version is up-to-date: ecmascript@0.1.6
Local package version is up-to-date: ecmascript-runtime@0.2.6
Local package version is up-to-date: ejson@1.0.7
Local package version is up-to-date: email@1.0.8
Local package version is up-to-date: fabienb4:autoform-semantic-ui@0.7.2
Local package version is up-to-date: facebook@1.2.2
Local package version is up-to-date: geojson-utils@1.0.4
Local package version is up-to-date: google@1.1.7
Local package version is up-to-date: hot-code-push@1.0.0
Local package version is up-to-date: html-tools@1.0.5
Local package version is up-to-date: htmljs@1.0.5
Local package version is up-to-date: http@1.1.1
Local package version is up-to-date: iandouglas:accounts-ui-semantic-ui@1.2.3
Local package version is up-to-date: id-map@1.0.4
Local package version is up-to-date: insecure@1.0.4
Local package version is up-to-date: iron:controller@1.0.12
Local package version is up-to-date: iron:core@1.0.11
Local package version is up-to-date: iron:dynamic-template@1.0.12
Local package version is up-to-date: iron:layout@1.0.12
Local package version is up-to-date: iron:location@1.0.11
Local package version is up-to-date: iron:middleware-stack@1.0.11
Local package version is up-to-date: iron:router@1.0.12
Local package version is up-to-date: iron:url@1.0.11
Local package version is up-to-date: jquery@1.11.4
Local package version is up-to-date: lepozepo:accounting@1.0.0
Local package version is up-to-date: lepozepo:s3@5.1.4
Local package version is up-to-date: livedata@1.0.15
Local package version is up-to-date: localstorage@1.0.5
Local package version is up-to-date: logging@1.0.8
Local package version is up-to-date: meteor@1.1.10
Local package version is up-to-date: meteor-base@1.0.1
Local package version is up-to-date: minifiers@1.1.7
Local package version is up-to-date: minimongo@1.0.10
Local package version is up-to-date: momentjs:moment@2.10.6
Local package version is up-to-date: mongo@1.1.3
Local package version is up-to-date: mongo-id@1.0.1
Local package version is up-to-date: mquandalle:jade@0.4.5
Local package version is up-to-date: mquandalle:jade-compiler@0.4.5
Local package version is up-to-date: npm-bcrypt@0.7.8_2
Local package version is up-to-date: npm-mongo@1.4.39_1
Local package version is up-to-date: oauth@1.1.6
Local package version is up-to-date: oauth2@1.1.5
Local package version is up-to-date: observe-sequence@1.0.7
Local package version is up-to-date: ongoworks:security@1.3.0
Local package version is up-to-date: ordered-dict@1.0.4
Local package version is up-to-date: promise@0.5.1
Local package version is up-to-date: random@1.0.5
Local package version is up-to-date: rate-limit@1.0.0
Local package version is up-to-date: reactive-dict@1.1.3
Local package version is up-to-date: reactive-var@1.0.6
Local package version is up-to-date: reload@1.1.4
Local package version is up-to-date: retry@1.0.4
Local package version is up-to-date: reywood:publish-composite@1.4.2
Local package version is up-to-date: routepolicy@1.0.6
Local package version is up-to-date: semantic:ui@2.1.4
Local package version is up-to-date: semantic:ui-data@2.1.4
Local package version is up-to-date: semantic:ui-icon@2.1.4
Local package version is up-to-date: service-configuration@1.0.5
Local package version is up-to-date: session@1.1.1
Local package version is up-to-date: sha@1.0.4
Local package version is up-to-date: softwarerero:accounts-t9n@1.1.4
Local package version is up-to-date: spacebars@1.0.7
Local package version is up-to-date: spacebars-compiler@1.0.7
Local package version is up-to-date: srp@1.0.4
Local package version is up-to-date: templating@1.1.5
Local package version is up-to-date: templating-tools@1.0.0
Local package version is up-to-date: tracker@1.0.9
Local package version is up-to-date: ui@1.0.8
Local package version is up-to-date: underscore@1.0.4
Local package version is up-to-date: url@1.0.5
Local package version is up-to-date: useraccounts:core@1.12.4
Local package version is up-to-date: useraccounts:semantic-ui@1.12.4
Local package version is up-to-date: webapp@1.2.3
Local package version is up-to-date: webapp-hashing@1.0.5
```

**Comment by mikemeier** [comment]
Im using METEOR@1.2.1, any updates or possibilities to speedup the building process in dev mode?

**Comment by weeger** [comment]
+100

**Comment by coffenbacher** [comment]
I seem to remember Meteor hot reloading being near instant when I tested it after the very first release. Now trying Meteor again I'm trying every trick I can think of just to get it <10 seconds :(

**Comment by mikkhait** [comment]
Would like to join this conversation. My reload time is at 16+ seconds.

**Comment by dcsan** [comment]
@mikemeier there is a build  `METEOR@1.2.2-faster-rebuilds.0`
that may help a bit. but meteor is still monolithic
best bet is to try and hack in webpack, which some people seem to have done.

**Comment by maximsko** [comment]
I am about to dump Meteor for this, I need to wait like 30 secs for every file change.

**Comment by CodeOfDavid** [comment]
I gave up a few weeks ago, sadly. Meteor could have been amazing

**Comment by JoaoFOliveira** [comment]
@dcsan Hacking this in webpack is also known as a big fuck you to Meteor altogether. When Meteor launched, file saves triggered a near instant page reload, on any computer. Now a dev prays to get a <10second rebuild, let alone the page. Its disastrous.

**Comment by dongaj** [comment]
can u remove this package
**lowi:audit-trail**
it's working fine

**Comment by 7immy** [comment]
The the date on the first post makes me sad :(

**Comment by 7immy** [comment]
I'm getting a vast improvement when running this update `meteor update --release METEOR@1.3-modules-beta.8`

**Comment by chbiel** [comment]
when the app grows (contains e.g. npm and meteor packages) also meteor 1.3 is very slow (around 10-15 sec).
please make this much faster...
or give the option to not check overtime for new packages (because i know when i add a new one..) thanks

**Comment by rclai** [comment]
There is a newer beta out: `meteor update --release METEOR@1.3-beta11`.

**Comment by maximsko** [comment]
It's becoming much better with the `METEOR@1.3-beta.11` release, at least for me. 5-7 secs until my browser starts to refresh and like 5 more seconds until he refreshed. If this can be tweaked just a bit more, I am actually more or less happy. 
Thanks for working on this, meteor folks!
