### ISSUE TITLE
Can't set the same header multiple times

### ISSUE THREAD

**Issue by pscanf** [meteor/meteor#2856]
In nodejs, the same header for an http response can be set multiple times, by passing an array as the second argument of the `http.ServerResponse.setHeader` method. ([Link to the docs](http://nodejs.org/api/http.html#http_response_setheader_name_value)).

The same doesn't seem to be possible in Meteor, as [this app tries to show](https://github.com/pscanf/headers-bug-reproduction). (It's deployed at [headers-bug-reproduction.meteor.com](http://headers-bug-reproduction.meteor.com)).

I'm trying to discover the cause of this behaviour, but so far no success. The issue doesn't seem to be related neither to `node` nor to `connect`, as I tried `node v0.10.29` with `connect v2.9.0` (the versions used by "default" meteor). In the next days, I'll try to dive deeper into the debugger.

**Comment by abernix** [comment]
As of Meteor 1.4 (and due to the update to Node 4), this is now working properly and compliant with [the HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

Closing!
