### ISSUE TITLE
Meteor is noisy if Internet connection does not exist

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2859]
When doing a simple `meteor run` without Internet connection, Meteor 0.9.4 is really noisy:

```
Error connecting to package server: Network error: wss://packages.meteor.com/websocket: getaddrinfo ENOTFOUND
Warning: could not connect to package server
```

Why is it even contacting the server every time I run `meteor run`? I would understand that it contacts the server if I run `meteor update` or something, but not on every `meteor run`?

This is also a privacy leak. I do not want you to track when and how I am developing software.

**Comment by xc8tlik** [comment]
> any serious application has a way to opt-in (preferably, or at least opt-out) from auto updates and home calling. It would be great to be able to configure Meteor not to contact your servers except when explicitly requested.

+1

**Comment by mitar** [comment]
Can this be reopened as a feature request to allow one to disable all home calling?
