### ISSUE TITLE
mobile-config.js only supports JavaScript, not arbitrary plugin-supported languages

### ISSUE THREAD

**Issue by neopostmodern** [meteor/meteor#2860]
I write all my code in CoffeeScript, so did I want to do for the `mobile-config.js`, thus being `mobile-config.coffee`.
If I have the file in CoffeeScript my app breaks with 

```
ReferenceError: App is not defined
     at ./mobile-config.coffee:3
```

I guess it is not recognized as a special file if written in CoffeeScript anymore, and it probably wouldn't work for packaging, but I can't confirm that.

**Comment by anymos** [comment]
+1, but after more than 2 years .... not sure if it will happens

**Comment by cosmin-dumitrache** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=mobile-config.js%20only%20supports%20JavaScript%2C%20not%20arbitrary%20plugin-supported%20languages&body=Migrated%20from:%20meteor/meteor%232860) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
