### ISSUE TITLE
Build for specific platforms

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#2867]
**_2 Upvotes**_ My Meteor app specifies the Android platform. I'd like to be able to run builds in specific, separate contexts. In particular:
1. My default Dockerfile shouldn't build Android or future IOS versions, because either it can't in the case of IOS, or it shouldn't. Docker builds are intended to run on the server, and only need the server-specific platform.
2. Android builds happen on my CI server with the Android SDKs pre-installed.
3. Future IOS builds will happen on a custom OS X box for that purpose, or on a third-party build server.

As it stands, the way "meteor build" is written is useless for me if I can't specify a list of platforms to build on. I'm a bit surprised there isn't a workaround for this already, since different platform builds almost certainly require different build environments.

Thanks.

**Comment by ndarilek** [comment]
Any chance this might get fixed in the 1.3 cycle?

The `meteor remove-platform` solution is somewhat ugly in that, if I try removing a platform that doesn't exist, the build explodes. Plus I'd have to update Dockerfiles, images, etc. if a project suddenly adds a new platform. This may seem like not much of an issue, but it would seem to complicate matters for projects like meteord/docker which aim to provide an easy path for packaging any Meteor app as a Docker container.

Maybe add a `--platforms` option that only builds the specified, comma-separated list of platforms? This is consistent with `--architecture`, which builds for an architecture different than the default (in that `--platforms` would build for a list of platforms different than the defaults specified in the project.)

**Comment by HQingYi** [comment]
We also need the options, the building for the android platform is wasting our time.

But when I remove the `android` platform, the tar file is smaller? So I compare them using Beyond Compare. The Differences are:
1) start.json: no `web.cordova` section
2) programs/server/config.json: no `web.cordova` clientPaths
3) programs/web.cordova: no this folder.

My question is whether these differences will affect the hot code push for installed android app?

**Comment by debovema** [comment]
+1 for this feature

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Build%20for%20specific%20platforms&body=Migrated%20from:%20meteor/meteor%232867) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
