### ISSUE TITLE
Cannot use a local npm package with npm link

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#2876]
Hey,

My use case is as follows - I have an npm package that my meteor package depends on that I link globally using:

sudo npm link

Problem is that when I try to run my app, meteor complains that it cannot find the npm package in the npm registry:

spacejam version 1.1.0 is not available in the npm registry

This makes it hard to develop wrapper packages for npm packages, since I'll need to push my changes every time to the npm registry in order to use and test my meteor wrapper package.

Workarounds, for now, would be appreciated.

Ronen

**Comment by trusktr** [comment]
@benjamn @glasser It'd be super awesome if the new `modules` system in 1.3 supports linked packages.

**Comment by mizzao** [comment]
Hey guys --- is it possible yet to do development on an NPM package as part of a Meteor app, like we do Meteor packages, using something like `npm link`?

Currently, if a NPM package has a bug (when used as part of a Meteor app) that we'd like to fix and submit a PR on, it's very difficult to set up a development version.

**Comment by benjamn** [comment]
I don't know why `npm link` wouldn't work for local `node_modules` directories, and if you're developing a Meteor package you can import npm packages from the app's top-level `node_modules` directory as "peer" dependencies. Give that a try?

**Comment by trusktr** [comment]
@mizzao `npm link` works fine for me. I'm using that right now to develop a NPM package while testing it in a Meteor app.

**Comment by kctang** [comment]
@mizzao fyi, i faced a similar situation today. After being puzzled for a while, I realised that the package's entry point was babel transpiled code. So, changing the package's (ES6) source alone will not make any difference. Run the package's "build script" ...then Meteor will pick up the changes. Hope this helps.

**Comment by cesarve77** [comment]
https://guide.meteor.com/writing-npm-packages.html#overriding-npm-packages
