### ISSUE TITLE
Uglify JS minification of diacritics creates symbols incompatible with IE9

### ISSUE THREAD

**Issue by Dsyko** [meteor/meteor#2877]
Just ran into this issue as we are trying to get our app working in IE9 (Yay!)

The javascript minification used when bundling or running meteor with the --production flag can sometimes create unicode characters that are not compatible with IE9. Specifically Diacritics cause the issue.

See here for some discussion of the issue: https://github.com/mishoo/UglifyJS2/issues/328

To reproduce the issue in Meteor:
* Open http://diacritics.meteor.com/ in IE9 (I used browserstack.com)
* Open the IE9 developer console to the javascript console
* Refresh the page

Please also see source here:
https://github.com/Dsyko/meteor-diacritics
Cloning that meteor project and running with the --production flag will surface the same issue in IE9.

I'd love to submit a PR to fix this issue, I'm not sure which would be the best way to tackle it. Either adding the options which solve the issue directly to the minify process used by Meteor: 
`output: { ascii_only: true, quote_keys: true }`

Or expose the options for the minify process to the developer somehow so they can pass their own options to uglify-js.

**Comment by glasser** [comment]
Not sure if this is the same as #3360 or not.  Once we upgrade Uglify to fix that (currently waiting on a new Uglify release) we should see if that fixes this too.

**Comment by mitar** [comment]
My package is also failing in production on IE because of Uglify: https://github.com/peerlibrary/meteor-urlify2/issues/1

**Comment by glasser** [comment]
I pinged mishoo/UglifyJS2#614 to see if they'll put out a new release.

**Comment by glasser** [comment]
Hmm. I can no longer replicate this: even trying diacritics.meteor.com in IE9 seems to work. Maybe IE9 has fixed its bug?

But in any case, UglifyJS 2.4.14 and newer seems to fix it: https://github.com/mishoo/UglifyJS2/commit/8fbe20001215887275b3cf053be675ebdbf331a9 (and I verified that the test case you showed gets its keys quoted).
