### ISSUE TITLE
Cordova-Android SockJS wrong url

### ISSUE THREAD

**Issue by BBLN** [meteor/meteor#2880]
I am not sure exactly about where is the bug, but when meteor bundle is used with mobile server SockJS opens connection to the wrong url. 

Build command:

```
ROOT_URL=https://y.meteor.com meteor build ~/v2_debug --server=https://y.meteor.com --debug
```

Log:

```
D/CordovaLog(18040): http://meteor.local/: Line 0 : XMLHttpRequest cannot load http://y.meteor.com/sockjs/info?cb=xxxxx. No 'Access-Control-Allow-Origin' header is present on the requeste
d resource. Origin 'http://meteor.local' is therefore not allowed access.
I/chromium(18040): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://y.meteor.com/sockjs/info?cb=xxxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Or
igin 'http://meteor.local' is therefore not allowed access.", source: http://meteor.local/ (0)
```

Resources are redirected to the url with https, SockJS opens without.

**Comment by pcuci** [comment]
@BBLN - I noticed sometimes meteor processes keep running even after exiting them, especially `meteor run android-device` ones, it may be that you had one of these zombies packaging an older version of your code.

It happened a few times, running Ubuntu 15.04
