### ISSUE TITLE
iPhone 6/6+ support for splash images

### ISSUE THREAD

**Issue by matb33** [meteor/meteor#2881]
Looks like support for slurping in the splash images for iPhone 6 and 6 plus is in 3.6.0+ (or perhaps 4.0.0, I'm having a hard time figuring out which version the change landed in). Of course we have the support from the mobile_settings.js perspective, but the splash images don't actually end up anywhere. Also probably want to have the `launch-screen` package use a newer version of the splashscreen cordova plugin (0.3.4 as of the time of this issue report -- you guys are on 0.3.3.).

Will Meteor be upgrading to a newer version of Cordova soon? In the meantime, is there any way to force a specific version of Cordova or is this baked in?

Original issue regarding the splash screens: https://issues.apache.org/jira/browse/CB-7604

**Comment by dotnetwise** [comment]
Still there is no upgrade to `cordova 3.6.3` / `cordova-cli 4.2.0` ?

**Comment by glasser** [comment]
Cordova CLI 4.2.0 shipped with 1.0.4.
