### ISSUE TITLE
Meteor search/show silently fails for cordova: plugins

### ISSUE THREAD

**Issue by justinsb** [meteor/meteor#2905]
It might be expected that meteor search/show would work for cordova: plugins.

```
meteor show cordova:org.apache.cordova.device
Unknown package or release: cordova:org.apache.cordova.device
```

I propose we pop a warning that the cordova: prefix is reserved.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20search%2Fshow%20silently%20fails%20for%20cordova%3A%20plugins&body=Migrated%20from:%20meteor/meteor%232905) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
