### ISSUE TITLE
Adding Packages from Git Repo

### ISSUE THREAD

**Issue by chrismbeckett** [meteor/meteor#2919]
**_6 Upvotes**_ One of the things we lost with the new package system was the ability to add a package from a Git repo. The only way to add a package now is to either have it local, or have it published. We have a number of packages in development that we do not want to publish, so we are using a lot of local packages in our app development.

The problem is that trying to integrate this scheme with the CI services like Travis, CodeShip or Shippable is almost impossible due to missing all the package dependencies when it pulls down the repo for the app. The only way I can see to resolve this would be to try to start using Git sub-modules or pre-build the app for download to the CI container. It's just getting too complicated.

Before I head down the heartache of trying to figure out a way to hack this problem, is there any near-term plans to support adding package dependencies directly from a Git repo? How are other people handling CI with the new package system if using unpublished packages?

**Comment by glasser** [comment]
Reopening, as we now do take  [feature requests](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by jperl** [comment]
:+1:

**Comment by jperl** [comment]
In case anyone is looking for something, we built a simple node helper to install private packages from github. https://github.com/DispatchMe/mgp

**Comment by ryneeverett** [comment]
+1

**Comment by offthegrass** [comment]
+1

**Comment by scmart** [comment]
+1

**Comment by firebait** [comment]
Hi everyone, has this been put on the roadmap? Definitely a great feature to have available.

**Comment by eggers** [comment]
+1

**Comment by willatpractichem** [comment]
:+1: So far we've had to rely on mgp and atmospheric npm modules to do this work and it's a pain because we have to remember to manually run either command whenever we update the version of a package or add a new one. Our packages are also mostly proprietary so publishing them is not an option.

IMHO, it seems like this is kind of a serious feature to lack. I've used gem, npm, and bower and they all allow you to do it. My PHP days stopped before Composer became big but I'm pretty sure that also allows it. My only guess is maybe the Meteor team hasn't implemented it yet to build up the library of public packages which I get and mean no disrespect because the Meteor team has worked hard on a platform I really enjoy using.

**Comment by jperl** [comment]
@willatpractichem 1.3 support node_modules -- while I have not tested it, I imagine you can use private npm packages. We are going to switch to that from mgp.

**Comment by willatpractichem** [comment]
@jperl So you're thinking wrap the meteor package as an npm package to install it that way a bit easier? I honestly kind of thought it was a bit odd that the Meteor team didn't just use npm or even potentially bower but I'm sure there is some reason for that that I'm not aware of.

**Comment by jperl** [comment]
Yep -- publish the meteor package directly to npm. I will post an example when 1.3 is released.

**Comment by willatpractichem** [comment]
@jperl sounds like a plan. Thanks for the heads up!

**Comment by meggarr** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Adding%20Packages%20from%20Git%20Repo&body=Migrated%20from:%20meteor/meteor%232919) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by Fabbok1x** [comment]
+1
