### ISSUE TITLE
Using cordova plugins in private repos or locally

### ISSUE THREAD

**Issue by matb33** [meteor/meteor#2925]
Currently, `Cordova.depends` is hardcoded to look for a URL starting with `http`/`https` and a commit hash. I've tried to use one of our private closed-source plugins but I just can't get Meteor to play nice with it. I even resorted to using npm to install it, then tar it, stuffing the commit hash in the filename... but then the regexp ^https? messes it all up...

I then tried copying it in to cordova-build-override/local-plugins/xxx but no joy since I don't have any control over that step -- I can't edit/transform files, just overwrite.

Having a local server just to host this plugin is overkill, and the build is automated and needs to work for the next person.

Anyway I'm at my wits end, I'm trying to get the client to temporarily make the repo public, but that isn't a good long-term solution.

Any thoughts?

**Comment by shirk3y** [comment]
+1 for using plugins from local files. It would be also cool if plugin will be re-loaded after its code is changed.

**Comment by dgtlife** [comment]
+1 for local repo.

From README of com.phonegap.plugins.facebookconnect:

>Installing this plugin directly from Cordova Registry results in Xcode using a broken FacebookSDK.framework, this is because the current publish procedure to NPM breaks symlinks CB-6092. Please install the plugin through a locally cloned copy or re-add the FacebookSDK.framework to Xcode after installation."

**Comment by dotnetwise** [comment]
+1

**Comment by jrhone** [comment]
+1

**Comment by dekelblip** [comment]
+1 Any prediction on when this will get priority? Thanks!

**Comment by Slava** [comment]
This feature was implemented in this PR: https://github.com/meteor/meteor/pull/4229

Afaik it is app-level only, but I think it is the most sane implementation. I don't think we can come up with a good semantics of a published package depending on a local plugin.
