### ISSUE TITLE
Meteor downloads packages again after every server code update?

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#2950]
If I just change one character in the server code it does this.

Is this expected behavior?

**Comment by gcacars** [comment]
Same here... when I update client files, is also very slow.

**Comment by hardforboys** [comment]
I've just started experiencing this in a Meteor/React project.

**Comment by gcacars** [comment]
Update client files in 1.1+ for me, is now fast, but updates on server is still slow

**Comment by nathanhornby** [comment]
I see this has been a historic issue - but it seems this was being 'resolved' over 6 months ago. I don't know if it was worse then as I'm new to meteor - but I personally find the server reload time annoyingly slow - it's no nodemon.

**Comment by maitrid** [comment]
I'm new to Meteor, and I'm using version 1.2. I have done this on the command line:
export METEOR_OFFLINE_CATALOG=1
The restart time is about 8 - 9 seconds. Is that normal, or did I do something wrong?

**Comment by wolispace** [comment]
This re-downloading 39 files each time meteor restart (and mine restarts regularly as I crash it or make a tiny edit and save) is rather annoying.
How can we do this download one at the start of a day and then not again until the next day?

Lets make Meteor fast and fun for everyone :-)

Thanks

**Comment by chrishowes** [comment]
Hey guys, just added the PR above that may help speed things up - would love your help w testing / feedback.

**Comment by hwroitzsch** [comment]
The issue still persists on Meteor 1.2.1. I'd rather not deactivate the downloads completely, but set a minimum time, which needs to pass by until meteor checks for newer package versions. The linked "Add in environment flag to assume package cache always valid #5609" seems to do something different and also there is some test failed, of which I don't know what it does, so I can't really use that.

Any news on this issue and how to solve it?

**Comment by devgrok** [comment]
I've found that no matter what I change it always checks the local packages are 'up-to-date' (if they've been modified and their version constraints.
The best logging information I got was by using
```
set METEOR_DEBUG_BUILD=1
set METEOR_PROFILE=1
```
I'm using windows but the problems seem consistent, both this empty project (created using the iron create) and my full project, spend roughly 2.6 seconds doing the "Input#loadFromCatalog" / "preparing project" --> "selecting package versions" step.

My best guess is that the dependency change check (that knows whether the project's or packages' metadata has changed) is always returning true.

Heres a snippet, full attached:
> START CAPTURE 0 undefined took NaN
>    START 1 preparing project
> ...
>      START CAPTURE 2 undefined took NaN
>        START 3 selecting package versions
> | 
> | Select Package Versions: 2496.8
> |     Input#loadFromCatalog (sqlite): 2421.7
> | 
> | Input#loadFromCatalog (sqlite): 2421.7
> | Total: 2421.7
>       DONE 3 selecting package versions took 2498
>     END CAPTURE 2 undefined took 2498
>     START CAPTURE 2 undefined took NaN
>       START 3 downloading missing packages
>         START 4 checking for autopublish@1.0.4
> ...
> END CAPTURE 0 undefined took 2565

**Comment by bitdivine** [comment]
Me too.  If this is going to be this slow I need a way to tell Meteor not to do it, so that I'm in control of when updates take place.  Is there such a mechanism?  (Short of simply blocking network access to the package server, which would work fine but is a bit of a sledge hammer.)

**Comment by nathanhornby** [comment]
> If this is going to be this slow I need a way to tell Meteor not to do it

Isn't simply ignoring the console as effective? If you're not waiting for the update then what does it matter how long it takes?

**Comment by bitdivine** [comment]
But it does wait.  It has a spinning bar until it has re-downloaded all the packages.  Besides a developer should always be in control of what their machine does.  It sounds as if iptables blocking is the answer?

**Comment by nathanhornby** [comment]
> But it does wait. It has a spinning bar until it has re-downloaded all the packages.

So your scenario is that you're publishing changes, whilst using the app, but don't want it to update? Seems like a pretty limited scenario to me.

I agree about giving us more control, I just wouldn't want MDG wasting resources on a feature that doesn't really make much sense.

**Comment by bitdivine** [comment]
I sometimes stop and then restart the service, so there are no code changes and yet it spends quite a lot of time re-downloading packages and then rebuilding the app.

**Comment by nathanhornby** [comment]
Ah I see - sorry that is indeed the subject in this issue after all… :no_mouth: I'd thrown myself off as I joined due to issues with restart times (but it's all part of the same issue).

Yes I must admit this confuses me. It's like Meteor runs the equivalent of an npm install each time it starts an app.

**Comment by hwroitzsch** [comment]
> So your scenario is that you're publishing changes, whilst using the app, but don't want it to update? Seems like a pretty limited scenario to me.

You got it all wrong. Every. Single. Time. I change some code, it needs approximately 5-10 seconds until I can finally see the result in the browser, spending most of that time doing stuff with packages. That's unacceptable. When using other frameworks like Flask for developing, the refresh is done almost instantly, because it doesn't check for new packages every single time or doesn't download them every single time, which is what Meteor seems to be doing.

Additionally a restart or start without code changes causes the same behavior and waiting time, but that case is much rarer than code changes obviously.

**Comment by nathanhornby** [comment]
@hwroitzsch As mentioned that comment was slightly out of context (but that wasn't what I was getting at, anyway).

I agree that changes that prompt a full restart (changes to server code, I assume?) take too long. Client changes, from what I've seen, don't have the same behaviour (the app refreshes much more quickly, like it would with a gulp/grunt etc.).

**Comment by hwroitzsch** [comment]
Well, I donwloaded Meteor 1 or 2 months ago, so it might have changed since. However, I am working in the client code (There is an "if" checking whether it's server or client and I am working in the client branch of that "if", just like taught in the online course I am doing. If there is any other way to separate the two of them so that Meteor gets it, I am unaware of it) and every single time I have that huge delay. So either Meteor works in different ways depending on your code or platform or Meteor has changed in the last 1 or 2 months or you're talking about a different use case than I am.

**Comment by hwroitzsch** [comment]
I could make a small screencast about it, but where to send it?

**Comment by bitdivine** [comment]
I think we are all agreed that if there is something akin to `npm install` on every run, that needs to stop.  Boot should be borderline instantaneous whenever possible.  Slow build test cycles are very bad for productivity, and if Meteor cannot honestly claim and keep fast development time it's as dead as a dodo.  However I notice that this ticket is closed, so at the moment this discussion is contributing nothing to improving the situation.  We need to either re-open this ticket or create another.  Has anyone "got the power"?

**Comment by nathanhornby** [comment]
@hwroitzsch 

> However, I am working in the client code (There is an "if" checking whether it's server or client and I am working in the client branch of that "if", just like taught in the online course I am doing.

If I understand correctly you have a single file with both client and server code in it (wrapped in a conditional) - this will prompt a full server restart as it needs to compile the _page_, not just the code you've changed (someone correct me if I'm wrong). I noticed gains in performance once I started moving code into the `/client` and `/server` folders - as then Meteor can compile code more intelligently.

A tip if you haven't tried it!

**Comment by hwroitzsch** [comment]
Didn't know that, thank you! Will definitely give that a try!

**Comment by chrishowes** [comment]
@hwroitzsch @bitdivine have you guys tried using the METEOR_OFFLINE_CATALOG flag, to see if there's improvement? Meteor will still perform the constraint solve, but will not query the server for updates.

`set METEOR_OFFLINE_CATALOG=1`

Also, are either of you on Windows?

**Comment by bitdivine** [comment]
Hello Chris.  I'm on Linux.  I did find that in another of the threads and tried it.  It made no difference.  Just checked again now and still, meteor spends oodles of time getting packages when not a line of code has changed.  If there is a "don't update dependencies" flag and a "don't rebuild" flag then I can put them in a shell script and check for changes myself.

**Comment by hwroitzsch** [comment]
I'm not on Windows. I tried your `set METEOR_OFFLINE_CATALOG=1`, however, it did not shorten the startup time, when changing server code.

**Comment by glasser** [comment]
Hey folks, it seems pretty clear from @devgrok's stats that this issue is *not* the same one that this issue was originally opened to solve where packages were being downloaded repeatedly, and instead is a new issue where loading data from sqlite is too slow. I'd suggest filing a new issue to track that, with the data from @devgrok's comment.

**Comment by nathanhornby** [comment]
@devgrok 's comment doesn't seem to relate to the continuing discussion @glasser so not sure who that's directed at.

**Comment by devgrok** [comment]
Yep sorry guys started investigating that one and dumped the problem in the thread base on the comments not the original description.
I'll find/open a correct issue.
