### ISSUE TITLE
Installing meteor-tool@1.0.35...  Killed

### ISSUE THREAD

**Issue by ramstein74** [meteor/meteor#2953]
Hello i was trying to upgrade from 0.9.4 to 1 and i cannot
i get the error 

Installing meteor-tool@1.0.35...  Killed

Help please

**Comment by Mattnificent** [comment]
Yeah, I also have a digital ocean server "Droplet" (cheapest one: 512MB Ram, 20GB SSD Disk) and I was getting the same error.  I installed meteor-tool on my virtual machine ( 4GB Ram, 120GB SSD Disk) no probs, though it took a while.

**Comment by MindBlowStudio** [comment]
I also have this problem, 512 mb ram in digitalocean, my app deploy was killed every timei run mup deploy or meteor deploy, i change my droplet to 1 gb and now is ok.

**Comment by mwaschkowski** [comment]
I just had this same problem today: 512 mb ram in digitalocean, my app deploy was killed every time I run mup deploy or meteor deploy, i change my droplet to 1 gb and now is ok.

**Comment by preexo** [comment]
Had the same issue in a 512 mb vagrant, increased the memory and everything runs smooth

**Comment by taxigy** [comment]
On Vscale.io, was having the same problem on a lowest-tier machine with 512MB RAM. Increased the size to 1024MB, and everything went smoothly.

**Comment by hyiltiz** [comment]
Wouldn't there be any way to workaround instead of increasing the RAM? It is not possible for me to increase the RAM.

**Comment by yy1193889747** [comment]
I'm 1024 mb ram  also have this problem ,  sad

**Comment by jakswa** [comment]
I have tried multiple times, get to 94-ish percent and get this message. Feels so close, but still so far. I was on the fence about using a meteor app already, and this kind of resource consumption looked to have decided things for me.
```
Downloading meteor-tool@1.1.10...         [======                    ] 24% 32.4s
```

**Comment by mohamad1980** [comment]
I have new way , create swap partation  at least 4 gb, and that will be fine.

**Comment by mohamad1980** [comment]
I have new way , create swap partition  at least 4GB, and that will be fine.

**Comment by kodie** [comment]
Ran into the same issue, would get this message when trying to start meteor: `Killednloading meteor-tool@1.4.3_2..` on a 1GB droplet. Upped it to 2GB and we're up and running!
