### ISSUE TITLE
"meteor install-sdk ios" fails when "xcode-select -p" return a non standard path

### ISSUE THREAD

**Issue by jlcanela** [meteor/meteor#2962]
Context : 

* MAC OSX Yosemite 10.10
* Xcode installed in /Volumes/data/Applications instead of /Applications
* Follow the https://www.meteor.com/install getting started
* Create the simple-todos sample 
* Execute it on Android is awesome :+1: 

When I have Xcode installed in a non standard path and I try to setup SDK for IOS, meteor says Xcode is not installed.

$ meteor install-sdk ios
✗ Xcode is not installed
Platform requirements not yet met
Please follow the instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Ios-on-Mac#xcode

$ xcode-select -p
/Volumes/data/Applications/Xcode.app/Contents/Developer

$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Maybe related to https://github.com/meteor/meteor/blob/10fc6ec6207436a162d6c1ce3fa663865d3a7ec6/tools/commands-cordova.js

**Comment by BenjaminConant** [comment]
Hey @justinsb running OSX El Capitan 10.11 ... just installed meteor and followed the  official tutorial and getting persistent  

```
~/D/simple-todos $ meteor install-sdk ios
Please follow the instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-iOS-on-Mac
```

I have followed the instructions, agreed to Xcode terms, entered password and can verify that Xcode.app is in my `/Applications`. 

```
/Applications $ ls | grep Xcode
Xcode.app
```

I can open Xcode see the welcome screen and have done basic things like restarting computer / googling the issue.

Any thoughts would be greatly appreciated! 

for the record I have Xcode 7.0.1

**Comment by BenjaminConant** [comment]
This i sort of resolved for my case ... read a bunch and ran

`meteor add-platform ios` which worked 

I was then able to run 

`meteor run ios` 

and get my app up and running on the simulator

still .... the error message for `meteor install-sdk ios` is misleading

**Comment by rgstephens** [comment]
@BenjaminConant Thanks for your post about doing the `meteor add-platform ios`. This worked for me to address the persistent error on the `install-sdk`.

**Comment by martijnwalraven** [comment]
It is not really an error message: `install-sdk` doesn't do anything in the current version of Meteor and simply refers you to the online installation instructions. But from this confusion it seems we should change the wording.
