### ISSUE TITLE
1.0 meteor update trying to update packages forever

### ISSUE THREAD

**Issue by tanis2000** [meteor/meteor#2968]
**_1 Upvote**_ I have a test case where Meteor 1.0 fails trying to update the packages of the app.

My .meteor/packages contains

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

#meteor-platform
standard-app-packages
jquery
alanning:roles
manuelschoebel:ms-seo
accounts-base
accounts-password
accounts-twitter
#arunoda:npm
gadicohen:headers
jeeeyul:moment-with-langs
accounts-facebook
accounts-google
sacha:spin
dandv:jquery-rateit
email

#mrt:iron-router-progress
gfk:notifications
less
raix:handlebar-helpers
meteorhacks:kadira
arunoda:subs-manager
underscore
meteorhacks:npm


rajit:bootstrap3-datepicker
cmather:handlebars-server
reactive-dict
spiderable
iron:router
gadicohen:phantomjs
gadicohen:messageformat
meteorhacks:inject-initial
altapp:urlify2-minifiable

npm-container
```

Running `meteor update` locks the process until the following error appears:

```
This project is already at Meteor 1.0, the latest release.
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Abort trap: 6
```

You can find a discussion about this issue there: https://groups.google.com/forum/#!topic/meteor-talk/sEmKTzgSLr8

And here's a repo with the test case: https://github.com/tanis2000/meteor-bug-packages-update

**Comment by applocalizations** [comment]
Does mup config update changes made to the packages?

**Comment by hwillson** [comment]
Many new versions of Meteor have been released since this issue was created / last updated. Closing as part of the old issue cleanup process. If you notice this issue still happens with the current version of Meteor, please post back. Thanks for posting this originally!
