### ISSUE TITLE
Broken examples in Meteor 1.0

### ISSUE THREAD

**Issue by odesey** [meteor/meteor#2969]
First, congrats on getting 1.0 out the door! 

So I am tying to test 1.0 by using the localmarket and todos examples by running:
`meteor create --example todos`
and
  `meteor create --example localmarket`

When I run both examples I get the following error in the console:
`Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?`

This is easily fixed by adding:
`this.next()` to the onBefore action of the respective home controllers.

Also in the localmarket example the following error is generated when I browse a dish to cook:
`Exception in template helper: TypeError: Cannot read property 'initial' of undefined
at Object.Template.nav.helpers.back (http://meteor.local/client/templates/nav.js?8237cc410bd603a18546af36a854ee0c418621bc:17:40)`

Not sure how to fix the second localmarket error.

Thanks.

**Comment by dzeitman** [comment]
Similar issue when trying to upload a photo.
Would be great if the Percolate folks did a tutorial based on this example app.

Error
I20150728-09:43:58.747(-7)? Exception while invoking method 'createActivity' TypeError: Cannot read property 'accuracy' of undefined
I20150728-09:43:58.748(-7)?     at getLocationPlace (app/lib/activities.js:101:34)
I20150728-09:43:58.748(-7)?     at [object Object].Meteor.methods.createActivity (app/lib/activities.js:30:24)
I20150728-09:43:58.748(-7)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150728-09:43:58.748(-7)?     at packages/ddp/livedata_server.js:648:1
I20150728-09:43:58.748(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150728-09:43:58.748(-7)?     at packages/ddp/livedata_server.js:647:1
I20150728-09:43:58.749(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150728-09:43:58.749(-7)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150728-09:43:58.749(-7)?     at packages/ddp/livedata_server.js:546:1

**Comment by immigrantsheep** [comment]
Has anyone managed to get the upload picture working?
