### ISSUE TITLE
`/bin/bash: /usr/local/bin/meteor: Permission denied` right after installing

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#2970]
Just installed Meteor on an Ubuntu 14.04 at [work](https://groups.google.com/forum/#!topic/meteor-talk/SKfuTVnuQnI) with `curl https://install.meteor.com/ | sh`. Running `meteor create foo` failed with `/bin/bash: /usr/local/bin/meteor: Permission denied`. Then,

``` bash
ls -al /usr/local/bin/meteor 
-rwxr-x--- 1 root root 3528 Oct 30 14:39 /usr/local/bin/meteor
$ sudo chmod +rx /usr/local/bin/meteor  # ok now
```

**Comment by ivan** [comment]
This happened for me when running the installer on Ubuntu 14.04.  My user had `umask 007` in `~/.zshrc` and I think `sudo` inherited the umask.  Maybe the installer should do a `chmod a+rx /usr/local/bin/meteor`?

**Comment by dandv** [comment]
A workaround is to add `~/.meteor` to $PATH:

    export PATH="$PATH:~/.meteor"

**Comment by juliustip** [comment]
Was having issue with `wercker`, somehow `$ sudo chmod +rx /usr/local/bin/wercker `solved it. Thanks
