### ISSUE TITLE
meteor configuration issue with existing Android SDK "The Android platform is not installed; please run: meteor install-sdk android"

### ISSUE THREAD

**Issue by priyankshah217** [meteor/meteor#2973]
Hi All,

I was trying to configure meteor in Ubuntu 14.04. I already had ANDROID SDK installed to my machine. But i was getting an error while configuring meteor with existing android sdk.

 meteor --verbose run android
%% Parsing the --port option                  
%% Will compile mobile builds                 
%% Running build for platforms: [ 'android' ] 
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which ant                    
Running command  uname -s                     
Running command  which jarsigner              
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command PATH=/home/adminuser/.genymotion:/home/adminuser/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools:/home/adminuser/Selendroid:/home/adminuser/Selenium/selenium-2.42.2:/home/adminuser/apache-maven-3.1.1/bin:/home/adminuser/apache-ant-1.9.4/bin:/opt/gradle-2.1/bin:/home/adminuser/.rvm/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools  /opt/android-sdk-linux/tools/android list target
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command  which android                
Using (global) Android SDK at /opt/android-sdk-linux
Running command PATH=/home/adminuser/.genymotion:/home/adminuser/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools:/home/adminuser/Selendroid:/home/adminuser/Selenium/selenium-2.42.2:/home/adminuser/apache-maven-3.1.1/bin:/home/adminuser/apache-ant-1.9.4/bin:/opt/gradle-2.1/bin:/home/adminuser/.rvm/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools  /opt/android-sdk-linux/tools/android list avd --compact
Found AVDS:                                   
Found /dev/kvm                                
The Android platform is not installed; please run: meteor install-sdk android

**Comment by stubailo** [comment]
We have completely rewritten this functionality in Meteor 1.2. If there is a similar problem in the future, please submit a new issue.
