### ISSUE TITLE
Browsing to docs.meteor.com link jumps to other anchors

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#2975]
In Chrome 38, navigating into a new tab to http://docs.meteor.com/#structuringyourapp redirects me to https://docs.meteor.com/#/full/structuringyourapp, but then ends up at https://docs.meteor.com/#/full/whatismeteor. I've seen other anchor fragments too. Oddly enough, this only seems to happen if I have no other docs.meteor.com tabs open.

**Comment by dandv** [comment]
Still there - http://docs.meteor.com/#/full/template_currentuser jumps to http://docs.meteor.com/#/full/template_loggingin

**Comment by glasser** [comment]
Confirmed @dandv 's report.

**Comment by abernix** [comment]
Thanks for opening this issue initially!  [The newly revamped Meteor Docs](http://docs.meteor.com) are here, and they are jumping correctly.  Closing this. :smile:
