### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#2980]
I am getting the following error at [this location](https://github.com/meteor/meteor/blob/devel/packages/blaze/domrange.js#L223):

```
Exception from Tracker recompute function: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at DOMRange.detach (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:508:24)
    at DOMRange.setMembers (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:467:12)
    at doMaterialize (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1866:22)
    at Object.Tracker.nonreactive (http://127.0.0.1:3000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:12)
    at doRender (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1856:15)
    at http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1795:16
    at Object.Blaze._withCurrentView (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:2029:12)
    at viewAutorun (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1794:18)
    at Tracker.Computation._compute (http://127.0.0.1:3000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:288:36) debug.js:41
```

![untitled](https://cloud.githubusercontent.com/assets/585279/4871364/348e4fc8-61b0-11e4-81a2-c39255046fe9.png)

Sadly I could not make a small reproduction.

**Comment by maxko87** [comment]
Getting the same issue using this:

http://mindmup.github.io/bootstrap-wysiwyg/

**Comment by ssadams11** [comment]
Same behavior with a strange twist.  My helper serving a {{#each}} returns an array of 3 strings that will populate a selectized option list.  If I return the array of strings retrieved from a Session variable I get the above error, but if I copy/past the same array of strings from a console.log of the array and return that literal array in my helper, everything works fine. == compare of the literal and computed arrays returns false, but they are identical from inspection.   So I tried setting the Session variable with the same literal array within the helper code before getting it as usual and all works fine.  But when I initialize the variable to the literal array in a Tracker.autorun that reacts to the user login, I get the same error.  Seems to have something to do with the reactivity middleware. Curiouser...

**Comment by jpmolinamatute** [comment]
I'm using TinyMCE and I'm getting the same error :-(

**Comment by jaschaephraim** [comment]
I was able to narrow down the simplest case to reproduce this problem, and found a workaround.

I was running up against this same issue using my own extremely minimal edit-in-place implementation. As a simple example, I might click on an empty `div` setting `contentEditable` to `true`, type some text, and then attach a handler to `focusout` to update the collection. Blaze would then insert that new text into the `div`, leaving 2 identical text nodes (`<div>dogdog</div>`). To remedy that, I had something like this:

```javascript
var n = div.textContent
div.textContent = null;
Animals.update(id, {field: n});
```

It's the `div.textContent = null` right before the update that's causing the problem. I also tried setting it to an empty string, and setting `innerHTML` instead, but no dice. To fix the problem, I remove the initial text node *after* the update:

```javascript
var n = div.textContent
var old = div.firstChild
Animals.update(id, {field: n});
div.removeChild(old);
```

**Comment by jancurn** [comment]
I was getting the same error when transforming a DIV to ACE editor using a code like this: 
```html
<div id="my_ace">{{value}}</div>
```
the problem occurred only when {{value}} was empty. A simple workaround is: 
```html
<div id="my_ace">{{#if value}}{{value}}{{else}} {{/if}}</div>
```

**Comment by balint42** [comment]
The solution by @jancurn seems to work for me as well:

`<div>{{#if value}}{{value}}{{else}} {{/if}}</div>`

**Comment by allenfuller** [comment]
@jancurn's solution worked for me as well when adding `{{else}}`. Otherwise the `{{#if}}` didn't work. I ran into the issue while using [chhib:selectize-bootstrap-3](https://github.com/chhib/meteor-selectize-bootstrap-3)

**Comment by jagi** [comment]
I get the same error when using contenteditable feature with CKEditor. My use case is much more complicated, however solution proposed by @jancurn does not work. It also does not happen all the time. It's hard to reproduce it.

Any update on this bug?

**Comment by joaobarcia** [comment]
Was having similar issue using selectize.js inside a custom accounts template.

**Comment by hwillson** [comment]
Moved to meteor/blaze#209 - closing here - thanks!
