### ISSUE TITLE
Unhandled install-sdk android error

### ISSUE THREAD

**Issue by justswim** [meteor/meteor#2983]
I'm getting this error when running meteor install-sdk android. It looks like Meteor is not downloading the SDK properly? My android_bundle directory is empty.

I tried reinstalling meteor, but still had the same error.

Thanks for your help with this!

      Erics-MacBook-Pro-3:kapwing ericlu$ meteor install-sdk android --verbose

      Installing Android bundle

      %% Running script /Users/ericlu/.meteor/packages/meteor-tool/.1.0.35.ggikwr++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/ensure_android_bundle.sh

      Running command USE_GLOBAL_ADK= METEOR_WAREHOUSE_DIR=/Users/ericlu/.meteor  bash /Users/ericlu/.meteor/packages/meteor-tool/.1.0.35.ggikwr++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/ensure_android_bundle.sh

      Running command  uname -s                    

      ✓ A JDK is installed                          

      Using (built-in) Android SDK at /Users/ericlu/.meteor/android_bundle/android-sdk

      Installing Android Platform tools            

      Using (built-in) Android SDK at /Users/ericlu/.meteor/android_bundle/android-sdk

      Using (built-in) Android SDK at /Users/ericlu/.meteor/android_bundle/android-sdk

      Running command PATH=/opt/local/bin:/opt/local/sbin:/Users/ericlu/anaconda/bin:/Users/ericlu/.rvm/gems/ruby-2.0.0-p247/bin:/Users/ericlu/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/ericlu/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/ericlu/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/ericlu/.meteor/android_bundle/android-sdk/tools:/Users/ericlu/.meteor/android_bundle/android-sdk/platform-tools ANDROID_SDK_HOME=/Users/ericlu/.meteor/android_bundle  /Users/ericlu/.meteor/android_bundle/android-sdk/tools/android update sdk -t platform-tools --all -u                                         

      events.js:72

              throw er; // Unhandled 'error' event

                    ^

      Error: write EPIPE

          at errnoException (net.js:904:11)

          at Object.afterWrite (net.js:720:19)

**Comment by Quinter** [comment]
Hi, having the same issue as johnsonqu and sail1972.  Have deleted android bundle and retried the download on two different macs on three different networks with the same error.  Is there something I can do with the curl configuration to fix this?

$ meteor install-sdk android
Installing Android bundle
✓ A JDK is installed                                                                
✓ Found Android Platform tools                
Installing Android Build Tools                
                                              
/Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:206
						throw(ex);
						      ^
Error: Failed to install android target: build-tools-21.0.0
    at [object Object]._.extend.installTarget (/Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2144:15)
    at [object Object]._.extend.checkRequirements (/Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2710:16)
    at checkPlatformRequirements (/Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1317:20)
    at Command.func (/Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:3082:19)
    at /Users/Andrew/.meteor/packages/meteor-tool/.1.0.40.n5kca++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1300:23

**Comment by Slava** [comment]
@Quinter hi, looks like your output is quite different from the one @sail1972 has.

The output from @sail1972 indicates that his machine can't connect to Google servers:
>   Failed to fetch URL https://dl-ssl.google.com/android/repository/addons_list-1.xml, reason: Connection to https://dl-ssl.google.com refused

Your error doesn't have any obvious messages. If you are concerned about your curl, you can post here the values of your `$PATH` env variable and the result of the `which curl` command.

**Comment by Quinter** [comment]
Nothing fancy going on in PATH, but: 

Andrew$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
Andrew$ which curl
/usr/bin/curl
Andrew$ curl --version
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz

**Comment by Quinter** [comment]
Fixed by installing this version of the JDK.  

http://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US

**Comment by JulianKingman** [comment]
I'm having a similar problem.

which curl
/opt/local/bin/curl

echo $PATH
/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/Users/Julian/.rvm/bin

I'm sure I messed with something at some point, unfortunately I don't have the know-how to fix it :\

**Comment by JulianKingman** [comment]
This is the --verbose output:

Julian$ meteor install-sdk android --verbose
✓ Found Android bundle
✓ A JDK is installed                          
Using (built-in) Android SDK at /Users/Julian/.meteor/android_bundle/android-sdk
✓ Found Android Platform tools                
Using (built-in) Android SDK at /Users/Julian/.meteor/android_bundle/android-sdk
Installing Android Build Tools                
Using (built-in) Android SDK at /Users/Julian/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /Users/Julian/.meteor/android_bundle/android-sdk
Running command                               
PATH=/Library/Frameworks/Python.framework/Versions/3.4/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/Users/Julian/.rvm/bin:/Users/Julian/.meteor/android_bundle/android-sdk/tools:/Users/Julian/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/Users/Julian/.meteor/android_bundle
/Users/Julian/.meteor/android_bundle/android-sdk/tools/android update sdk -t
build-tools-21.0.0 --all -u
Using (built-in) Android SDK at /Users/Julian/.meteor/android_bundle/android-sdk
stdout from sdk install was: Refresh Sources: 
Fetching https://dl.google.com/android/repository/addons_list-2.xml
Failed to fetch URL https://dl.google.com/android/repository/addons_list-2.xml,
reason: peer not authenticated
Fetched Add-ons List successfully
Refresh Sources
Fetching URL: https://dl.google.com/android/repository/repository-10.xml
Failed to fetch URL https://dl.google.com/android/repository/repository-10.xml,
reason: SSLPeerUnverified peer not authenticated
Refresh Sources:
Fetching URL: https://dl.google.com/android/repository/repository-10.xml
Failed to fetch URL https://dl.google.com/android/repository/repository-10.xml,
reason: SSLPeerUnverified peer not authenticated
There is nothing to install or update.

                                              
/Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: Failed to install android target: build-tools-21.0.0
    at [object Object]._.extend.installTarget (/Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2256:15)
    at [object Object]._.extend.checkRequirements (/Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2822:16)
    at checkPlatformRequirements (/Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3199:19)
    at /Users/Julian/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
Julians-MacBook-Pro:task-manager Julian$

**Comment by JulianKingman** [comment]
A work-around seems to be to open the android SDK manager and installing the packages it requires one-by-one. For me, it's located in ~/Users/[user]/.meteor/android_bundle/tools, then running "./android" (I'm on a mac).

**Comment by sail1972** [comment]
@JulianKingman 
Yeah, U R right, this is the key!

**Comment by Szeremeta** [comment]
+1 for @Quinter fix

my error message was slightly different.

Installing Android Build Tools                
                                              
/Users/alex/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: Failed to install android target: build-tools-21.0.0

**Comment by basco-johnkevin** [comment]
I'm also experiencing a similar issue.

```
meteor install-sdk android
✓ Found Android bundle
✓ A JDK is installed
✓ Found Android Platform tools
✓ Found Android Build Tools
✓ Found Android 19 API
Making sure Android Platform tools are up to date
Installing Android x86 image

/Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Failed to install android target: sys-img-x86-android-19
    at [object Object]._.extend.installTarget (/Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2256:15)
    at [object Object]._.extend.checkRequirements (/Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2879:16)
    at checkPlatformRequirements (/Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3199:19)
    at /Users/johnkevinmbasco/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
```

**Comment by stubailo** [comment]
In Meteor 1.2 we decided to avoid shipping the Android tools ourselves, and instead have directions for installing Android Studio and the required stuff yourself.
