### ISSUE TITLE
Allow <input {{#if isChecked}}checked{{/if}}> in Blaze templates

### ISSUE THREAD

**Issue by garrilla** [meteor/meteor#2988]
imagine the scenario

`<input type="checkbox" checked />`

In theory, we should be able to use a helper to determine if the `input` should be check when a template is loaded

``` javascript
Template.checkbox.helpers({
    isChecked: function(){ someTest ? true : false}
})
```

``` html
<template name="checkbox">
  <input type="checkbox" {{#if isChecked}}checked{{/if}} />
</template>
```

however this errors

```
 Reactive HTML attributes must either have a constant name or consist of a single {{helper}} providing a dictionary of names and values.  A template tag of type BLOCKOPEN is not allowed here.
...ox" {{#if clustered}}che...
```

Why is it not allowed here, it produces valid HTML

I know there are two workarounds here

1:

``` html
<template name="checkbox">
  {{#if isChecked}}
  <input type="checkbox" checked />
  {{else}}
   <input type="checkbox" />
   {{/if}}
</template>
```
1. 

``` javascript
Template.checkbox.helpers({
    checkbox: function(){ someTest ? 
                           " <input type="checkbox" checked />"  : 
                           " <input type="checkbox" />" 
                     }
})
```

``` html
<template name="checkbox">
  {{{checkbox}}}
</template>
```

but still, when its possible to do

``` html
<template name="checkbox">
  <input type="checkbox" anyAttribute="{{#if isChecked}}one thing{{else}}or another{{/if}}"" />
</template>
```

I don't understand why the original case isn't possible...

**Comment by wangbourne** [comment]
@dgreensp 
you mentioned: "
<input type="checkbox" checked={{isChecked}}>
If isChecked returns primitive false, null, or undefined, the checked attribute will be considered absent.
"

this conflicts with standard css usage. The standard css doesn't care what value is assigned to checked attribute, as soon as it sees checked in the checkbox input tag, it's flagged as checked.

any comments?

**Comment by dgreensp** [comment]
The relevant spec is the HTML spec, which indeed says that `<input type=checkbox checked="">` is a checked checkbox.  Any string, including the empty string, means true.  No string at all means false.

This still leaves some leeway in how a template language should handle `<input type="checkbox" checked={{active}}>` when `active` is a boolean, not a string.  Converting `false` into "no attribute at all" (which is then interpreted by the browser as `false`) is highly convenient and conforms to what people tend to expect.

The problem in the code above is the trailing slash.  HTML5 frowns on writing "void" elements like `<input>

**Comment by wangbourne** [comment]
got it. thanks for clarify :)
