### ISSUE TITLE
"Error: key $date must not start with '$'" when trying to insert an EJSON into a Collection

### ISSUE THREAD

**Issue by juanbernabo** [meteor/meteor#2990]
I was trying to have more than one type stored into a Collection and using EJSON addType seamed like a good way to go, but I runned into some trouble trying to insert an EJSON into the collection.

Now I'm reconsidering and maybe avoiding the storage of an EJSON into a collection, and just do it by hand, but anyway I just wanted to report this error if someone somehow needed really bad to persist EJSON objects into the mongodb collections.

Thanks in advance,
Juan.

**Comment by MathieuDerelle** [comment]
sorry to dig up an old post but I could not find a better answer via google
so for the people who will search an answer : 

I add the same error when passing an object directly : 
```
model.insert({
  "createdAt": {
    "$date": "2019-08-28T15:11:21+02:00"
  }
})
```

A workaround is to `JSON.stringify` the object : 
```
model.insert(JSON.stringify({
  "createdAt": {
    "$date": "2019-08-28T15:11:21+02:00"
  }
}))
```

**Comment by MathieuDerelle** [comment]
sorry to dig up an old post, but that's the best answer on google and I ppl are searching a workaround, I've got one

it happened when passing directly an EJSON object like so : 
```
const data = {
  createdAt: { $date: '2019-08-28T15:08:04+02:00' }
}

model.insert(data)
```

A work around is to parse EJSON yourself : 
```
import { EJSON } from 'meteor/ejson';

const data = {
  createdAt: { $date: '2019-08-28T15:08:04+02:00' }
}

model.insert(EJSON.parse(JSON.stringify(data)))
```

(it happened to me when using JsonRoutes to create to API)
