### ISSUE TITLE
Android App Hot Code Push

### ISSUE THREAD

**Issue by lugaru90** [meteor/meteor#2999]
Hey,

i've made an android App out of a simple Application.
I've tested it on two ways:
-build with -- debug
-build without --debug and signed it myself

The Problem: When i make any change to my Code, the Hot Code Push seems to be not working. The App Displays the Loading Icon. The Menu dont build and the page keeps white. 

When deleting the App Cache, the App opens up Displays everything correct but after a second the loading Icon appears again.

Any suggestions?

Edit: Hitting the back Button brings me back to the same screen. Hitting it twice exits the app.

**Comment by MoeBadr** [comment]
Hi @Slava   

I'm Having the same issue.  

currently I'm deploying meteor on aws using the following to build server, Android & ios: 
`meteor build --server http://www.notifyed.org --architecture os.linux.x86_64 build`

This works fine, If I use the same xxx.apk in the build.

but as soon as I push new version to the server, the xxx.apk stops working (stop on the please wait... screen which wait for `Meteor.loggingIn()`)

Any help I would be grateful. 

cheers.

**Comment by MoeBadr** [comment]
I have fixed the issue by setting env vars: 

`MOBILE_DDP_URL` 
`MOBILE_ROOT_URL`

please add to doc @Slava 

Thank you.

**Comment by MoeBadr** [comment]
@Slava my current work around this: 

server onStart:
`process.env.MOBILE_DDP_URL = 'x';`
`process.env.MOBILE_ROOT_URL = 'x;`
