### ISSUE TITLE
Facebook oauth error on handshake, appears as if not configured

### ISSUE THREAD

**Issue by fungilation** [meteor/meteor#3000]
This one is hard to reproduce, I can't myself either on desktop Chrome, Safari or iOS. I see a similar error reported on http://stackoverflow.com/questions/16934686/facebook-login-on-meteor-works-on-chrome-only but that's a year ago without resolution. I'm starting this issue to see if others are seeing a similar error like this now.

I'm using the Accounts-Entry package. Latest packages on Meteor 1.0 as of this writing. The app is at http://clubch.at/

The user on signup hit the following error, with screenshot on his android attached.
![10743686_10153258911754409_1506685917_n](https://cloud.githubusercontent.com/assets/3803466/4900200/50c539f6-6424-11e4-90d7-235ad5a4dbfa.jpg)

It appears as if my app wasn't configured for Facebook sign-in when it has. Despite the error, the user successfully registered and can see that he's already logged in, after reloading page on screenshot.

Error on server stdout:
```
I20141103-23:50:57.813(-8)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Facebook. failed [400] {"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100}}
I20141103-23:50:57.814(-8)?     at getTokenResponse (packages/facebook/facebook_server.js:62)
I20141103-23:50:57.814(-8)?     at Object.isJSON [as handleOauthRequest] (packages/facebook/facebook_server.js:8)
I20141103-23:50:57.815(-8)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8)
I20141103-23:50:57.815(-8)?     at middleware (packages/oauth/oauth_server.js:173)
I20141103-23:50:57.815(-8)?     at packages/oauth/oauth_server.js:146
```

**Comment by glasser** [comment]
This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.

**Comment by jchristman** [comment]
@fungilation, I had this same issue and found out that I had not enabled the settings for facebook app: ```Do you want to make this app and all its live features available to the general public?``` This was causing the above error. The app worked perfectly for me (as the developer) but not for my testing account (the general public). I realize this is a long closed issue, but I had the same issue which I figured I would post.

**Comment by fungilation** [comment]
Thanks, but my app on Facebook app "Status & Review" already had "general public" turned on. It's a incidental hit to this issue's original error

**Comment by andrejsm** [comment]
Hit same _handshake failure_.Only this time Chrome alone was failing. Found out that failure caused this little Chrome extension [SPOF-O-Matic](https://chrome.google.com/webstore/detail/spof-o-matic/plikhggfbplemddobondkeogomgoodeg)

**Comment by derwaldgeist** [comment]
I was having the very same problem after I tried to change the Facebook app URL to an IP instead of localhost. This did not work, so I changed it back. But even after that, I got this error message. The only solution I found was to set-up a new Facebook app. This worked, but is of course not a good option in real-life scenarios.

**Comment by mackbrowne** [comment]
I was working through this problem today.  Take a look at [this gist](https://gist.github.com/mackbrowne/30317eba75d13683566ead357b52bbcel)

Add this to your server code, you'll get the functionality you want.  The only recommendation is verify all your accounts by email mandatory.
