### ISSUE TITLE
Compress package sync data on the wire

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3007]
Doing a full synchronization of all package metadata (which happens rarely) can be slow.  We should consider compressing this data.  At the very least, we could do an ad-hoc compression that's specific to this method, but ideally we would implement [permessage-deflate](https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-18) in faye's websocket-driver, which would add optional compression of large messages to all DDP apps.

**Comment by glasser** [comment]
This was implemented but reverted pending https://github.com/faye/permessage-deflate-node/issues/1

**Comment by glasser** [comment]
Probably fixed by https://github.com/faye/permessage-deflate-node/pull/3/files, pending review/release

**Comment by glasser** [comment]
Note that this is stalled pending Faye fixing some major bugs in the deflate support: https://github.com/faye/permessage-deflate-node/issues/1 and https://github.com/faye/websocket-driver-node/issues/11

**Comment by glasser** [comment]
Support for this is back in the framework. I'll close this once troposphere is redeployed with the improvement.

**Comment by glasser** [comment]
... and reverted again due to bugginess.

**Comment by glasser** [comment]
OK, https://github.com/faye/permessage-deflate-node/issues/4 is fixed so we can probably try this again.  On the other hand, Node 0.10 (but not 0.8 or 0.12) has a problem which means that you can't get particularly good (cross-message) compression with its zlib anyway :(

**Comment by glasser** [comment]
OK, great, as of https://github.com/faye/permessage-deflate-node/commit/47b3b3614b68c56aee84415220ff0968489f1bdb it should work great on 0.10 too.

**Comment by glasser** [comment]
This is on `devel` now.  Still waiting to close this bug until we successfully put out a release using it and deploy to `packages`.

**Comment by brianmingus** [comment]
I switched to devel so that I could have this. Please include in release :)

**Comment by glasser** [comment]
This is in 1.2.

**Comment by brianmingus** [comment]
Thanks. For some reason when Googling this is as far as I got. So my collection with gobs of text that I'm syncing to clients is sent over the wire compressed, automatically?

**Comment by glasser** [comment]
Yup! More details in the release notes: https://github.com/meteor/meteor/blob/devel/History.md#v12-2015-sept-21

**Comment by bpartridge** [comment]
Since this is released (and confirmed to be working) should this issue be closed? Just helping to track!

**Comment by stubailo** [comment]
Thanks! we sure do compress data now!
