### ISSUE TITLE
Ensure that self-test runs faster and more reliably

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3008]
The self-test mechanism, added in Meteor 0.7.1, now runs a lot of tests that are slow and flaky, so we don't use it as consistently as we should.  We should clean this up so that we can run a basic set of tool tests quickly and efficiently.  (Fixing #2846 will help a lot here too.)

**Comment by abernix** [comment]
Closing in favor of #3569 which has more conversation on the same topic. :)
