### ISSUE TITLE
Ensure that package sync network errors are detected and handled promptly

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3009]
If we lose network midway through a package refresh, we now hang, because we turned off heartbeats to avoid #2789.  We should improve heartbeat support (at least in the Node client) so that any received byte counts as a pong, not just ping/pong messages, and turn heartbeats back on.

**Comment by abernix** [comment]
Closing as I believe #7267 resolved this by allowing network retries on package downloads.
