### ISSUE TITLE
Allow builds to be canceled mid-build if the watcher fires

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3011]
**_1 Upvote**_ Right now, if the runner is rebuilding your app and you change another file, it finishes the current build before immediately starting over.  We should allow the bundling process to be interrupted if it knows it is going to need to immediately rebuild again.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20builds%20to%20be%20canceled%20mid-build%20if%20the%20watcher%20fires&body=Migrated%20from:%20meteor/meteor%233011) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
