### ISSUE TITLE
CLI tool: Stream IO when possible instead of buffering in memory

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3014]
Various parts of the tool buffer entire files in memory before writing them to disk.  Switch these to streamed IO whenever possible.

**Comment by gabrielhpugliese** [comment]
I've just upgraded my project from 0.8.3 to 1.0.3.2 and I cannot deploy on a 512MB (Digital Ocean) machine anymore. Any `meteor command` I run gets killed. 
Is there any workaround for this except building on my machine and uploading to server?

**Comment by glasser** [comment]
Bundling on your machine and uploading to your server is in fact the recommended method of deploying Meteor apps.

**Comment by gabrielhpugliese** [comment]
Wow, didn't know about that. 
I've commented with Arunoda that he implemented that way in mup but my upload bandwidth is very low that makes it very painful to do continuous deployments. I'm used to do that with `git fetch` => `meteor build --directory`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=CLI%20tool%3A%20Stream%20IO%20when%20possible%20instead%20of%20buffering%20in%20memory&body=Migrated%20from:%20meteor/meteor%233014) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
