### ISSUE TITLE
Creating collection inside a stub throws error

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3025]
I am getting `Uncaught Error: Called retrieveOriginals without saveOriginals` when using a method on both client and server side.

**Comment by mitar** [comment]
How is this progressing?

**Comment by raedle** [comment]
I am having the same issue with `Uncaught Error: Called retrieveOriginals without saveOriginals` when creating `new Mongo.Collection` in the collection.observe added function. I would be very interested in the workaround.
