### ISSUE TITLE
Template.dynamic doesn't call uihooks

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3033]
See https://github.com/percolatestudio/meteor-momentum/issues/9

Apparently `Template.dynamic` doesn't call the `uihooks`? Is that intentional, and is there a way to make it work with the momentum package?

**Comment by avital** [comment]
Thanks. We'd like to investigate this but we'll need a small reproduction in the form of a git repository that we can clone and run (that doesn't have dependencies on external packages)

**Comment by aldeed** [comment]
It now works with latest Meteor release. Sorry for not closing this.
