### ISSUE TITLE
Meteor Developer Accounts emails should have a better email name than "contact"

### ISSUE THREAD

**Issue by jagill** [meteor/meteor#3041]
I deployed my first app (from a different email address), and got the helpful "Create a password" email from contact@meteor.com.  However, it has no "Real Name", which means it appears like spam in my inbox.  It should have a nice friendly name like "Meteor Accounts", or something with "Meteor" in its title, so I notice it and act on it right away.
![contact](https://cloud.githubusercontent.com/assets/495664/4962522/b8e49076-66e1-11e4-91f0-d064b194f7ce.png)

**Comment by glasser** [comment]
Thanks.  Fixed this in the app's code; it will be deployed sometime in the next few weeks.
