### ISSUE TITLE
Unexpected mongo exit code 48. Restarting. 

### ISSUE THREAD

**Issue by Zorig** [meteor/meteor#3058]
When i download meteor 1.0 and trying to run meteor app it shows 

```
Unexpected mongo exit code 48. Restarting.    
Can't start Mongo server.                     
MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB
```

I've installed mongoDB already, and trying to search solution over internet. Actually i tried delete .lock file too. but still same result

**Comment by famousky** [comment]
I am getting the same error **Unexpected mongo exit code 48. Restarting.** and I tried already everything including reinstalling node & npm. And I don't have any other *mongodb* installed in system.

![screen shot 2015-10-01 at 1 28 55 pm](https://cloud.githubusercontent.com/assets/4720153/10213508/b07dd008-6840-11e5-8642-1d6b4ec00cbe.png)

**Comment by panayi** [comment]
@01010000101001100 try the following to check if `mongod` is running:

```bash
$ ps aux | grep mongod

ppanagi         74251   0.4  0.2  2711840  38340 s004  S+    4:36PM   0:00.41
```

 and then do `sudo kill -9 PID` (where `PID` is `74251` in the above example).

**Comment by cpury** [comment]
Same error here. No `mongod` instances running, and nothing on the port either.

**Comment by thomasrivette** [comment]
C:\Users\Thomas Rivette\Documents\SoftwareProjects\simple-todos>netstat -a -n | findstr 3001
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING

**Comment by chip** [comment]
I had a similar issue, and for some reason `netstat` didn't list the port. However, using `lsof -i :3001` (on OSX) uncovered the culprit process running on that port, so I was able to kill it and then meteor ran fine.

**Comment by thomasrivette** [comment]
Thanks. also found the metoer --port=localhost:3006 subcommand to circumvent.

**Comment by proehlen** [comment]
I've got a new Lenovo Windows 10 laptop and it runs a program or process called LenovoPortalService.exe on port 3001.  I don't want to uninstall that because it's part of a larger component that I might need.

How can I change the default port that Meteor and Mongo run on?  I've got a new trainee starting that I want to learn Meteor and I don't want him to have to type ```meteor --port=locahost:<something else>``` every time he starts a meteor app.

**Comment by MedYOUNES** [comment]
I could solve it with the following

` 	
meteor -p 3005 you need to change the port to run meteor server 
`

**Comment by tanmayshahane** [comment]
MedYOUNES you saved the day, thanks that tip worked.

**Comment by plitex** [comment]
After update my MacBook to OS X 10.11.5 (15F34) I have the same problem:

```bash
=> Started proxy.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Can't start Mongo server.
MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB

Check for other processes listening on port 3001
or other Meteor instances running in the same project.
```

`lsof -i :3001` outputs nothing.

I've reinstalled Meteor completely, removed `~/.npm`, did `meteor reset`... And still not working. Any idea?

NOTE: Starting with sudo works, so there is something wrong with permissions, but I don't know where.

**Comment by abernix** [comment]
@plitex What about a fresh install of Meteor to (possibly) correct permissions?  `curl https://install.meteor.com/ | sh` should do it.

**Comment by abernix** [comment]
@plitex (deleted previous recommendation – Sorry, just realized you said you reinstalled Meteor) You don't have any other Meteor running?  What if you tried running it on another port?  `meteor -p 4000` for example.

**Comment by plitex** [comment]
It doesn't work using another port. I really don't understand where is the problem...

**Comment by plitex** [comment]
Finally I've found the problem. For some reason I don't understand, my **/tmp** folder was only writable by **root**. I really don't know when was changed, if by an apple update or whatever.

Meteor was trying to create a UNIX socket in **/tmp** and it couldn't. Now, magically VirtualBox is also working! XD

Hope this helps to anyone having the same problem.

**Comment by ldesiqueira** [comment]
@plitex Thank you so much.

**Comment by ihafeez** [comment]
If you are using port 3000 for meteor then MongoDB which is a part of meteor used 3001. But if some other application is also using 3001 or another instance of mongodb is using 3001 then you see this error "Unexpected mongo exit code 48. Restarting". Because Mongodb is trying to start at 3001 but due to some reasons this port is not available, that why given this error going to restart stage.
To Avoid kill all apps running at 3001 port and then restart meteor application.
If for example you are using 4000 then mongodb is taking 4001.

I hope it will help....
