### ISSUE TITLE
Every Cordova plugin is reinstalled on build

### ISSUE THREAD

**Issue by nicolsondsouza** [meteor/meteor#3064]
Is there a way to have the cordova www folder and build the app in cordova instead of using meteor cordova, as it is taking too much of time to build the app,
and few plugins doesn't support with command line,
so has to be build manually.

Please advice if there is any way.

**Comment by stubailo** [comment]
@martijnwalraven has totally rewritten the mobile code, so this should no longer be an issue in Meteor 1.2.
