### ISSUE TITLE
Canceling a Twitter sign-in results in logged error on server log

### ISSUE THREAD

**Issue by timhaines** [meteor/meteor#3067]
`Error in OAuth Server: invalid_credential_token_or_secret`

The error is generated here: https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_server.js#L278

It happens because OAuth._renderOauthResults is called without a credentialSecret.

This is because when you cancel a Twitter login, the request handler's oauth_token query param is undefined, so the credentialSecret never gets set.  https://github.com/meteor/meteor/blob/devel/packages/oauth1/oauth1_server.js#L66

I propose this shouldn't be logged as an error, as canceling a login is a valid action.

**Comment by glasser** [comment]
That does sound like a reasonable analysis.  (Can you be explicit as to what you mean by "cancel" --- you just mean closing the popup window or something?)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Canceling%20a%20Twitter%20sign-in%20results%20in%20logged%20error%20on%20server%20log&body=Migrated%20from:%20meteor/meteor%233067) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
