### ISSUE TITLE
Event handler not executed when fired from SVG <use /> element

### ISSUE THREAD

**Issue by Dev1an** [meteor/meteor#3072]
When binding a click event handler via <code>template.events(eventMap)</code> the handler is never executed if the event was fired from within a SVG <code>&lt;use /&gt;</code> element. Note that I only see this behavior in Safari 8.0 & 7.1 (older versions not tested).
Although this bug only appears in Safari, I don't think the problem lies within Safari.app because everything works just fine if I bind the event with normal vanilla Javascript like this: <code>element.addEventListener(handler);</code>
Look at the following pad for an example: http://meteorpad.com/pad/RKBN2dYwQD6L6fmuQ

**Comment by Slava** [comment]
Thanks for the clear reproduction!

Blaze uses jQuery internally for the events delegation. It looks like the version jQuery Blaze uses doesn't bubble events from `use`. So if you replace the second part of your reproduction (event handlers with DOM APIs "normal way") with this code, it will stop working too:

```js
  $('body').on('click', 'svg', function(event) {
    increment();
  });
```

jQuery doesn't officially support events delegation on SVGs but in practice it works most of the time. Here is an issue in jQuery bug-tracker that relates to this. http://bugs.jquery.com/ticket/13180

**Comment by t3db0t** [comment]
I'm also experiencing this problem in Chrome 41.0.2272.104. 'pointer-events="none"' didn't have any effect.  So if jQuery doesn't support this, are we just out of luck?

**Comment by Dev1an** [comment]
Just use vanilla javascript (like I showed on meteorpad) for now.

**Comment by hwillson** [comment]
Since the cause of this issue was jQuery and not Blaze, this issue can be closed.

**Comment by abernix** [comment]
And if it's not clear, you can install your own newer version of jQuery (using `meteor npm install`) and Meteor will prefer it over its (older) own version:

    meteor npm install jquery --save

Thanks, @hwillson.  Much appreciated.
