### ISSUE TITLE
Can't use helpers to set range input values

### ISSUE THREAD

**Issue by nkoren** [meteor/meteor#3077]
To reproduce:

``` javascript
Template.foobar.helpers({
  myValue: function() {
    return 20;
  }
});
```

And...

``` html
This doesn't work:
<input type='range' min='0' max='100' value='{{myValue}}'>

Yet this does:
<input type='number' min='0' max='100' value='{{myValue}}'>
```

**Comment by josmardias** [comment]
Can we reopen this issue based on this reproduction?
https://github.com/josmardias/meteor-issue-3077

Range is always on "100". Also, inpsecting the computed html, I noted that there is no "value" attribute on input range.
Tested on both Firefox and Chrome

```
$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)

$ uname -r
4.1.4-200.fc22.x86_64

$ firefox --version
Mozilla Firefox 39.0.3

$ google-chrome --version
Google Chrome 44.0.2403.155
```

**Comment by josmardias** [comment]
Just noted that on my application the input range doesn't work after route navigation (FlowRouter.go), but works if I manually call a page refresh later (ctrl+shift+r).

Unfortunately this behavior (correct range position after refresh) doesn't happen on the repo I just posted (josmardias/meteor-issue-3077).

**Comment by dan335** [comment]
I'm getting this also.
