### ISSUE TITLE
Multiple Meteor Apps *can't* run on the same domain, causes local storage collisions

### ISSUE THREAD

**Issue by stephengpope** [meteor/meteor#3078]
**_2 Upvotes**_ Running two Meteor apps on a single domain is causing local storage collisions.

We have a particular situation where we can't use subdomains to distinguish between multiple Meteor apps (a IT limitation with a client), and instead were forced to use the root level PATH /app1 or /app2 - like https://DOMAIN.com/appX. The two apps run of different servers, and a nginx process routes the incoming URLs, app1 or app2 to the correct server/app.

We updated the ROOT_URL to include the appX part of the path, however Meteor isn't using the path of the ROOT_URL in its local storage naming convention, so app1 and app2 struggle for power instead of being able to coexist.

We were able to solve the issue in the local storage package, adding the appX path to the keys of the storage, however we think it makes sense that core supports this pulling the path from ROOT_URL. Using subdomains is an easy, normal convention for getting around this, but large organizations have a lot of IT restrictions that actually make URL routing a very acceptable solution.

Thoughts?

**Comment by popestepheng** [comment]
we've come up with a solution for this, we'll post for consideration.

**Comment by benstr** [comment]
+1, this is a big "gotcha" that I am experiencing now that I am moving to production.

**Comment by glasser** [comment]
@popestepheng Looking forward to seeing it.

**Comment by glasser** [comment]
Specifically, this is about Meteor Accounts, right?

**Comment by spyrosk** [comment]
The PR above contains the simple solution @popestepheng mentioned, please let us know if you need us to make any changes or have any concerns with it.

**Comment by pbastowski** [comment]
Has there been any progress on this recently? I need the same ability to have virtual app roots, also called "junctions", in my apps. It would seem to me that each Meteor server has to know about the other Meteor servers on the same ip.address:port and then manage accounts accordingly. 
Perhaps that's already solved?

**Comment by glasser** [comment]
Well, I made some review comments on the PR (#3617) and the proposer didn't make any corresponding changes.

**Comment by dandv** [comment]
The blog post mentioning this, and a simple temporary solution (override `localstorage.js` locally): http://projectricochet.com/blog/multiple-meteor-apps-running-same-domain-how-override-packages

**Comment by pbastowski** [comment]
Thanks @dandv

**Comment by cristiandley** [comment]
is this dead ? is there any official solution to this ?

**Comment by abernix** [comment]
@cristiandley Have you confirmed that this is still a problem on the latest Meteor?  This issue is still open (so not completely dead) but it hasn't been a popular issue amongst others and the proposed PR (#3617) had some issues which were never worked out.

It would be nice to get this (old) issue resolved, so if you or anyone is willing to work on it, please consider discussing a proposed solution here.   Please be sure to keep in mind the concerns which were originally mentioned in the PR.

**Comment by hwillson** [comment]
I've verified this is still an issue - I'll work on a (backwards compatible) fix. 

Reproduction: https://github.com/hwillson/meteor-issue-3078
