### ISSUE TITLE
un-migrate d3 from Atmosphere?

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3082]
Now that [d3 is deprecated](https://github.com/meteor/meteor/tree/devel/packages/deprecated), perhaps it should be hidden from [Atmosphere](https://atmospherejs.com/meteor/d3) searches? It's already gotten 6 stars there.

**Comment by dandv** [comment]
@mbostock has [accepted the Meteor integration PR](https://github.com/mbostock/d3/pull/2130#issuecomment-73460165). Can the powers that be please update the Meteor docs and point to it?

**Comment by mizzao** [comment]
Maybe it would be helpful to have a way to alias package names - i.e. `d3` alias for `d3js:d3`, that way `meteor add d3` installs the official d3 package just as @mbostock requested.
