### ISSUE TITLE
Instructions for aws beanstalk pls

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#3087]
Hi, any chance we could get some instructions on how to build and deploy to beanstalk, please?

Things like bcrypt that are platform specific. There are some examples out there but things have changed significantly since they were created. Any help appreciated.

**Comment by Spiegelberg** [comment]
well offcourse its easier to deploy with meteor up. but u have no control off the deployment.
the "hackery" around elastic beanstalk is not a hack. the server can auto scale, and then offcourse it needs the right config everytime it deploy a new instance and so on..
put in the time on elastic beanstalk, you will be production ready. it took me hardly a month to get into the EB env. and kinda hard learning curve... but now im pr0
