### ISSUE TITLE
Why does `@` variable in coffeescript still work as app level variable?

### ISSUE THREAD

**Issue by hamxiaoz** [meteor/meteor#3091]
Previously, you can use `@` to denote an app level variable in CoffeeScript and my project is using that. Now I've updated to v1.0 and noticed the instruction about how to make app level variable is updated (use the `share` variable):

(this commit has the change)[https://github.com/meteor/meteor/commit/70883fdc425d434535bf841bbe39cff12a530ec4]

I haven't updated my code but my code still works in v1.0? Why? Is there a plan to deprecate that? Do I need to update all my projects?

**Comment by kostko** [comment]
> I'm not sure that using @varName creates globals within packages.

Indeed, using `@` in packages only seems to create a package-scoped variable. I do not see what is the point for having `share` then?

**Comment by kostko** [comment]
Ah nevermind, it seems that `@` creates a package-scoped variable only on the server side, but the variable still leaks into the global namespace on the client. Perhaps due to the server's use of VM?

**Comment by glasser** [comment]
There's other discussion of this at #3993
