### ISSUE TITLE
meteor semver is alphabetical?

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3104]
when i remove explicit version constraints, meteor picks the highest alphabetical version it seems.

ie 

```
app> meteor show splendido:accounts-templates-bootstrap
... # lots of versions
Version 0.9.16            Accounts Templates styled for Twitter Bootstrap.
...
Version 0.11.0            Accounts Templates styled for Twitter Bootstrap.
```

but speccing 
```
api.use([
'splendido:accounts-templates-bootstrap',
...
```

will result in 0.0.9 being picked, since 0.9 looks later than 0.11 - to meteor - I guess?

    package splendido:accounts-templates-bootstrap at 0.0.9 is incompatible with Meteor 0.9.0 or later. 

so i have to manually spec the higher version.

    'splendido:accounts-templates-bootstrap@0.11.0',

this seems like a bug, but maybe i'm not understanding how your semver is meant to work...

**Comment by dcsan** [comment]
is there no way to specify 1.0 and above?
meteor only seems to deal with exact version numbers, which means i have to go back and revise this all the time.

if i don't add a version number it will seem to default to the very OLDEST version it can find, which is almost always not what i want.

```
# remove semver specific version

   meteor update 
...
    aldeed:autoform        downgraded from 0.17.1 to 0.1.0

meteor run
W20150102-23:26:36.922(-8)? (STDERR) The package aldeed:autoform at 0.1.0 is incompatible with Meteor 0.9.0 or later. 
```

**Comment by dcsan** [comment]
oh so it seems:

```
aldeed:autoform@4.0.0   #means latest version greater than 4.0 eg 4.2.3 etc

aldeed:autoform  # means the very first vers it finds, eg 0.0.1 

```

there's no `package>4.0.0` type syntax.

**Comment by dcsan** [comment]
in .meteor/packages if i use

```
aldeed:autoform@4.1.0
aldeed:collection2@2.0.0
aldeed:simple-schema@1.0.0
```

I get:

```
$ meteor list
aldeed:autoform       4.2.2 
aldeed:collection2    2.3.0 
aldeed:simple-schema  1.3.0 
```

so I don't really see the logic here.

**Comment by paralin** [comment]
I'm pretty sure versions are stored in the meteor/versions file

**Comment by dcsan** [comment]
ok interesting. I more regarded the `versions` file as an output to check which versions had been used, than something to edit. 
so you think that the versions in .meteor/packages are basically ignored, and should be set in the `.meteor/versions`? that seems to duplicate all the info?

**Comment by glasser** [comment]
You can specify exact constraints with `foo@=1.2.3` and "compatible with" constranits with `foo@1.2.3` in `.meteor/packages` (or meteor add, etc).

**Comment by glasser** [comment]
Your original issue did not have enough details to replicate.  Please see https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor to learn how to submit a useful bug report.
