### ISSUE TITLE
`meteor run ios` fails if configured app name has spaces

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3105]
Reproduction: `meteor --release 1.0 create --example localmarket; cd localmarket; meteor run ios`.

(Note that localmarket has the name `Local Market`.)

The most relevant error is

```
error: InputFile    /Users/glasser/Projects/Meteor/testing-cordova/localmarket/.meteor/local/cordova-build/platforms/ios/Local Market/Local Market-Prefix.pch 0 1415849767 969 33188... malformed line 9; 'InputFile' should have exactly five arguments
```

Full output: https://gist.github.com/glasser/cc140c4a7820d2dc42f6

**Comment by kdanninger** [comment]
A lot of people are pointing to this issue from various other places on the web. So I'm just going to leave this little piece of info here.

A space in your path causes this issue:

/Users/karldanninger/*Legacy Drive*/okgrow/tomato/.meteor/local/cordova-build/platforms/ios/CordovaLib/CordovaLib_Prefix.pch 0 1421076393 838 33188... malformed line 9; 'InputFile' should have exactly five
arguments

I also speculate that xcode is looking at timestamps when files were last changed. So sometimes an older build will work with a space in the path, when new builds with inevitably fail.

**Comment by hellogerard** [comment]
I got this too. The workaround I found was: 

1. Take the space out of the name in `mobile-config.js`.
1. Allow Meteor/Cordova to build the Xcode project. 
1. In Xcode, rename the project in properties to have a space.

The OCD in me always wants the committed git repo to be pristine, but this works.

**Comment by hellogerard** [comment]
Hopefully, this will be fixed in the next version of Meteor, which upgrades the Cordova version.

https://issues.apache.org/jira/browse/CB-7821
