### ISSUE TITLE
todos example gear button doesn't work on iOS

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3106]
If I run the new todos example and view it on iOS (iOS simulator - iPhone 4 - iOS 8.0) either just via MobileSafari or via Cordova, the gear button on the list page doesn't work.  It does not pop up a private/delete select; it just displays the `< > Done` form interaction control at the bottom.

**Comment by Slava** [comment]
Just tested on the following: iPhone 4s, iPhone 5, iPhone 6. Everything worked including the mutiple choice menu on the bottom.

Closing this issue ;)
