### ISSUE TITLE
Transform in allow does not work properly when defined as null in deny

### ISSUE THREAD

**Issue by darkship** [meteor/meteor#3108]
Hi,
In my repo https://github.com/darkship/test_allow_helpers, you will find that I defined <code>transform : null </code> in <code>deny</code>. It results that transforms aren't applyed to <code>allow</code> too.

https://github.com/aldeed/meteor-collection2/issues/144

**Comment by glasser** [comment]
Agree. Would review a PR *with tests* to fix this.
