### ISSUE TITLE
Cannot permanently set IPHONEOS_DEPLOYMENT_TARGET for Cordova Xcode project, build fails

### ISSUE THREAD

**Issue by ephemer** [meteor/meteor#3113]
In Cordova I can make a boilerplate project, add a plugin (mine is written in Swift, which requires iOS 7.0 or greater), set the Deployment Target in my Xcode project to whatever I want and it'll stay that way. My project builds and runs, all good.

My meteor-cordova build with the same plugin fails because of the iOS 7.0+ requirement and I can't find a workaround in the meteor environment. If I run `meteor run ios-device` I can access the Xcode project to change its Deployment Target to 7.0. If I then try to add the cordova plugin and run either `meteor run ios` or `run ios-device`, Meteor builds a new Xcode project which overrides my Deployment Target, causing it to fail before it even gets to launching Xcode.

While it would be nice to have access to change the IPHONEOS_DEPLOYMENT_TARGET from the Cordova CLI (another issue, obviously), the real issue here is that my Xcode project keeps getting overwritten by meteor. Can we have an option in mobile_settings.js for the deployment_target? In the meantime, any workarounds would be appreciated.

Thank you!
Geordie

**Comment by ephemer** [comment]
Hi @Slava,

I think the issue will be that Cordova, or rather Xcode's Libtool (called by Cordova), overrides any relevant env vars itself, based on either the `build.xcconfig` file in `$CORDOVAPROJECT/platform/ios/cordova/` or, failing that, from within the Xcode project itself.

Frustratingly, `cordova build ios` does not pay attention to the `build.xcconfig` file unless you provide it the `--device` flag (which isn't always what we want). See: https://issues.apache.org/jira/browse/CB-8254

I notice that meteor is using its own fork of cordova anyway, maybe you could add the -xcconfig param to the build file in the meteor fork too?


In the meantime, I think the best solution would be to:

1) Avoid calling `cordova build ios` when adding a plugin and when running `meteor run ios`. Instead just run `cordova prepare ios` and show us the Xcode project. This would mean one more click in Xcode to get the simulator started, but would open a world of opportunity for customising the project before building/compiling. The main benefit is that we can add whichever plugins we want and sort out the dependencies ourselves if needed.

2) Avoid overwriting an existing Xcode project in the `.meteor/local` directory on `run`. I'd be interested to see how cordova does it and why it's different in the meteor implementation. It's unavoidable that the project gets overwritten when adding / removing cordova plugins, but otherwise we should be able to keep the same Xcode project the same and just change `/www` with code hot pushes.

I suspect a simple combination of those two would make for a clean and flexible solution suited to the vast majority of users.

**Comment by ephemer** [comment]
Hi @Slava, David @glasser,
Cordova has pushed a fix to this which would fix the issue, provided you have the right plugin hooks (see the [addSwiftOptions.js](https://gist.github.com/ephemer/b65d379d5a96237d186d) hook I'm using). You can find the
[commit](https://git-wip-us.apache.org/repos/asf?p=cordova-ios.git;a=blobdiff;f=bin/templates/scripts/cordova/lib/build.js;h=02d8113ac7dff63f656dc7842b07a70ba321d231;hp=b7a6bd05c30e2f948f9efb35f1433b0a947917cf;hb=875d699;hpb=fd941c3c7bbf7705087be7c2ecc23ca432036a56) on the Cordova issue at https://issues.apache.org/jira/browse/CB-8254. The commit is so simple, I imagine you could just cherry-pick it into Meteor's Cordova fork without issue, should you so choose...

The other option would be to just make everyone use iOS 7.0 (change cordova's default xcode template to always use iOS 7.0 – this would still have the issue of missing bridging headers though, so the first option is preferable and still gives users the ability to change the xcode project themselves)

**Comment by bastiRe** [comment]
Hi,
is there any progress on this? Did you use a workaround @ephemer? I'd like to use a geofencing plugin in my meteor cordova app but unfortunately it's written in swift.

**Comment by ephemer** [comment]
@bastiRe I gather the last version of meteor goes a long way to get around this by setting the deployment target to > 7 by default, among other things.

I'm yet to try to try it out with our swift plugins, would be great to hear your experiences with it. You'll probably have to set the swift bridging header via plugin hooks, otherwise you should be fine to go

**Comment by bastiRe** [comment]
I'm using 1.0.3.2 and target is still 6.0. Where did you get the information that the target is automatically set to > 7?

**Comment by ephemer** [comment]
See note here about upgrading to Cordova 4.3 (under meteor mobile):




https://github.com/meteor/meteor/blob/devel/History.md

**Comment by bastiRe** [comment]
You're right. But it's only with the release candidate of the newest Meteor version 1.0.4. I tried it out and the Swift plugin works without any problems.

**Comment by ephemer** [comment]
Awesome, thanks for letting me know!
