### ISSUE TITLE
make http://meteor.local/ as http://mydomain/

### ISSUE THREAD

**Issue by nicolsondsouza** [meteor/meteor#3114]
XMLHttpRequest cannot load https://www.facebook.com/impression.php. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.

What I see is meteor.local is predefined domain,
so if there is a chance to modifed the host of the domain to app url,
this will help to origin issue for meteor.local

**Comment by Lenin7** [comment]
Any updates on this? I can't seem to be able to upload any files in Cordova.
Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.

("origin": ["*"])

**Comment by nicolsondsouza** [comment]
I believe that's because there is a new update on meteor Cordova where you
have to provide special permission. On which domain to allow. Previously it
was all domains by default but now you have to white list the domain.

Even if you still face any difficulty you need to modify meteor Cordova
plugin and add you custom URL there and you are good to go.

Let me know how it goes, so I can keep my knowledge updated.

**Comment by Lenin7** [comment]
Does anyone know where the documentation for the new update is?
