### ISSUE TITLE
Meteor template events mouse when touchend

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3136]
When you touch and drag, you'll see no mouseup when you let go. But if you just tap, you'll see mouseup triggered after touchend!

https://github.com/ccorcos/meteor-mouseup-bug

**Comment by dgreensp** [comment]
Hi @ccorcos, this is not Meteor-specified, it's how the browser events work.  mouseup is a bit of a finicky event.  Even on desktop browsers, the cursor has to be inside the element in question for the mouseup event to be fired.  (This is often worked around by temporarily listening to mouseup on the window.)  On mobile browsers, there are additional factors that could cause mouseup to not fire.  For example, a drag might be interpreted as trying to scroll the window, and this may cancel mouseup.  I'm not sure about all the details, but the behavior you are talking about seems to be the same behavior you get from the browser's addEventListener.
