### ISSUE TITLE
Document the fact that cursor.observe runs the initial added callbacks in the current computation, but not any subsequent callbacks

### ISSUE THREAD

**Issue by michaelstephendavies** [meteor/meteor#3137]
**_1 Upvote**_ When calling `cursor.observe` inside a reactive computation, the initial synchronous `added` callbacks are run inside that computation, but any further async callbacks are not.

``` js
var coll = new Mongo.Collection(null);
coll.insert({x: 3});
Tracker.autorun(function () {
  coll.find().observe({
    added: function (doc) {
      console.log(doc.x, Tracker.active);
    }
  });
}); // logs "3 true"
coll.insert({x: 4}); // logs "4 false"
```

I find this quite surprising. In retrospect, it sort of makes sense - although personally, I expected neither of them to run in computations. Any way, I think it's non-obvious enough to justify being documented in http://docs.meteor.com/#/full/observe_changes, recommending wrapping the callback in `Tracker.nonreactive` if you want consistency.

**Comment by steph643** [comment]
+1 for having `cursor.observe` callbacks *not* triggering reactivity. I find it confusing.

**Comment by hwillson** [comment]
I've moved this over to https://github.com/meteor/docs/issues/156. Closing here - thanks!

**Comment by mitar** [comment]
Should this be a change that even initial callbacks are not run inside computation? But that might be breaking change.

**Comment by hwillson** [comment]
@mitar I agree; for now I'm thinking we should just document the current behavior (as requested in https://github.com/meteor/meteor/issues/3137#issue-49514253). Deciding to change this behavior is a much bigger issue for sure. Thanks!
