### ISSUE TITLE
[appcache package] can not sign-in with Twitter on Windows Firefox when using appcache

### ISSUE THREAD

**Issue by y-ich** [meteor/meteor#3154]
When an app uses accounts-twitter and appcache and you access the app using Windows Firefox(33.1.1), you can not sign-in.
Concretely, fails to access Twitter site and directly redirects callback URL in pop-up window.

**Comment by glasser** [comment]
We have disabled AppCache on Firefox on our apps (eg docs.meteor.com) due to lots of bug reports. It's possible that we should change the defaults.  See #2926

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers.  Realistically, this will not get resolved in time for it to be worthwhile.

Service Workers are supposed to be the replacement and is being tracked in #5982.
