### ISSUE TITLE
[Packages] Private directory in package

### ISSUE THREAD

**Issue by lukejagodzinski** [meteor/meteor#3172]
As far as I've tested it I can't define `private` directory in my package and have access to it using `Assets` API like it would be in the standard project directory. I think it should be possible to access such data for example by providing package name before file name:

``` js
Assets.getText('author:packageName/privateFile.json');
```

**Comment by boboci9** [comment]
Hi, 
This is not working for me and I don't know what am I doing wrong:
my folder structure is the following:
packages/bogi:multi-vendor/private/data/newcoShop.json
packages/bogi:multi-vendor/multiVendorShopSetup.js
            ......
             jsonFile =  Assets.getText("private/data/newoShop.json");
						      ^
Error: Unknown asset: private/data/newoShop.json
packages/bogi:multi-vendor/packages.js

       api.add_files('private/data/newcoShop.json', 'server', {isAsset: true});  

Can you tell me what am I doing wrong?
Thanks

**Comment by glasser** [comment]
You are missing a c in the filename.

**Comment by boboci9** [comment]
OMG! Thanks a lot if I wouldn't have glasses I would go and buy some, I have been looking at this nonsense for hours !
Sorry for this!!!

**Comment by tjconsult** [comment]
It appears that nowadays (I am using Meteor 1.2), one is supposed to use

```javascript
api.addAssets(...)
```
instead of the above-mentioned `{ isAsset: true }` argument on `addFiles`.

**Comment by AlexFrazer** [comment]
Can you access this via `Assets.getText()`?

**Comment by chrise86** [comment]
Still having issues with this, can you access them across packages? For instance, if I have an asset in a "core" package, can I then access it in another package that has core as a dependency?
