### ISSUE TITLE
Meteor.bindEnviroment changes the Function.length

### ISSUE THREAD

**Issue by nathan-muir** [meteor/meteor#3176]
If you pass a function with a signature `function(err, res)` to `Meteor.bindEnvironment`, you get back a function with the signature `function()` (no arguments).

This primarily affects `Meteor.wrapAsync`, as the callback function generated has a `.length == 0` 

So, a client library, looking at the callback function's length, could assume it does not follow the `function(err, res)` pattern. (eg, perhaps `function(res)`)

An example of this pattern is [Superget](https://github.com/visionmedia/superagent/blob/b36fd692139cf366486d45783ede45a4c90c4764/lib/client.js#L814) For example:

```js
/**
 * Invoke the callback with `err` and `res`
 * and handle arity check.
 *
 * @param {Error} err
 * @param {Response} res
 * @api private
 */

Request.prototype.callback = function(err, res){
  var fn = this._callback;
  this.clearTimeout();
  if (2 == fn.length) return fn(err, res);
  if (err) return this.emit('error', err);
  fn(res);
};
```

This results in some cryptic errors when using `Meteor.wrapAsync`

Some possible solutions

1. `Meteor.wrapAsync` can either use it's own version of `bindEnviroment` or wrap the callback from `bindEnvironment` in a function with the signature `function (err, res){ return callback.apply(this, arguments); }`

2. `Meteor.bindEnvironment` could try and maintain function length, eg:

```js
function wrapFnWithLength(length, fn){
  var args = [];
  for(var i = 0; i < length; i++){
    args.push(String.fromCharCode(97 + i));
  }
  return new Function(args.join(","), 'return fn.apply(this, arguments);');
}

Meteor.bindEnviroment = function(fn, onExcepption, _this){
  // .. snip .. 
  var boundFn = function (/* arguments */) {
  // .. snip ..
  };
  return wrapFnWithLength(fn.length, boundFn);
}
```

**Comment by glasser** [comment]
I'm going to say that function.length is a pretty bad feature to use in JS, given how pervasive wrapper functions like bindEnvironment are!  If you run into a place where you really need to use a length-sensitive API, you can always do:

```
var wrapped = Meteor.bindEnvironment(function (one, two, three) { ... });
poorlyDesignedApi(function (one, two, three) {
  return wrapped(one, two, three);
});
```
