### ISSUE TITLE
Server requires too much time to restart after code change

### ISSUE THREAD

**Issue by aram90** [meteor/meteor#3178]
After latest version releases when changing something in server code it takes a lot of time (about 20s) to restart the server. It shows `Downloading Packages` during all that time which is strange because after small code change which is not related to any packages they are not supposed to be downloaded.

**Comment by aram90** [comment]
This issue was supposed to be fixed after latest release however there is no any progress regarding server restart performance after code change, after trying new version it was working relatively faster however after trying it for some time still delay is still there, Here's the sequence of server status after code change:

    Preparing project
    Scanning local packages
    Initializing packages
    Selecting package versions
    Downloading missing packages
    Preparing to build package google-con...
    Preparing to build package google-
    Preparing to build package blocking
    Preparing to build package blockin
    Preparing to build package aws-sdk
    Preparing to build package meteorh
    Preparing to build package meteorhack...

Also all these outputs are broken, progress is shown one per line instead of being changed in place (i.e. after code change I see a bunch of lines printing `Downloading missing packages`). I wonder whether this is a common issue or related to one of the packages because it makes impossible to quickly test the code and thus development time is dramatically increased.

**Comment by glasser** [comment]
Hi Aram. We put a fair amount of effort into improving rebuild time in the 1.0.2/1.0.2.1 release.  I know the current situation isn't perfect, but it should be a lot better for most users. In order to help make it even better for users where it isn't great any more, we really need a much more specific reproduction, of a specific codebase that performs poorly.  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by avital** [comment]
(If we have a specific app we can run to see the slow behavior, we can re-open this ticket.)

**Comment by glasser** [comment]
Also feel free to open a separate bug about ugly progress bar appearance (with a full reproduction explanation including details of your OS, terminal, etc).
