### ISSUE TITLE
Updating Collection after pasting into contenteditable=true repeats its value

### ISSUE THREAD

**Issue by saeho** [meteor/meteor#3184]
Been working on an app and I've ran across a issue where using the following general code structure causes the Meteor's live updating engine to update new data with twice its value.

Hopefully this makes sense...

page is a collection

--TEMPLATE FILE--
[h1 contenteditable=true] {{page.title}} [/h1]

--JS FILE--
Template.Name.Events
  'click #save': function
    Meteor.call('update_page')

- At this point, the collection is updated and Meteor's live updating engine does the magic, updating all values on page with latest data from collection.

- IF collection was updated after manually typing into the <H!> everything will be fine.

- IF collection was updated after CMD+A (Select All) inside H1 and then CMD+V to paste, it duplicates its value. (i.e. If saved with value "EXAMPLE", Meteor live updates it to "EXAMPLEEXAMPLE")

- However, Collection shows the correct value ("EXAMPLE"). This leads me to believe Meteor is not really updating the H1, instead it is appending the new value on top of the existing H1 value for some reason.

**Comment by avital** [comment]
Dup of #1964 (this generally can't be made to work in Blaze). There are some workaround on that thread.
