### ISSUE TITLE
Disable re-render for some div (with attached Google Maps)

### ISSUE THREAD

**Issue by aksonov** [meteor/meteor#3199]
What is the way to disable re-rendering of some div inside HTML? For example I don't want to recreate Google Maps object which is attached to map div. Is there any way to cache such div?

**Comment by avital** [comment]
"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. Moreover, it would make it much easier for people to help you if there were an example attached.
