### ISSUE TITLE
Method calls on server return by reference

### ISSUE THREAD

**Issue by numtel** [meteor/meteor#3201]
When using a Meteor method call on the server, the return value is transferred by reference to the callback.

On the client, the value is obviously passed by value as it must be JSON serialized.

Please see the following very simple package I have created to display this: https://github.com/numtel/meteor-server-method-issue

I don't see anything in the documentation about this inconsistency. It would be nice to have it work the same on client and server but that may not be the best option?

**Comment by glasser** [comment]
Thanks for the helpful reproduction.
