### ISSUE TITLE
phantomjs keeps running after `meteor --test`

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#3205]
There seems to be something wrong with how `meteor --test` exits.

**Reproduce**
Download https://github.com/meteor-velocity/velocity-examples/tree/master/
1. Make sure no phantomjs processes are running
2. Start the app with the commands below
3. After the app has exited, there is still a phantomjs process running from the `meteor --test` run.

With leaderboard-mocha

``` bash
cd leaderboard-mocha
meteor --test
```

Or with leaderboard-jasmine

``` bash
cd leaderboard-jasmine
JASMINE_SINGLE_RUN=1 meteor --test
```

**Comment by ThePenguin1140** [comment]
It seems that the fix for this is not included in the current version (1.0.3.1).
When can I expect this to be released?

**Comment by glasser** [comment]
This got merged to devel during the release stabilization for 1.0.3(.1) so it should get into the next release.  (cd014c76004ed)

**Comment by ThePenguin1140** [comment]
Awesome, about how long will it take for the next version to be released?

**Comment by glasser** [comment]
We don't have a specific release schedule, but we have on average put out one non-patch release per month for the past three years.
