### ISSUE TITLE
Android emulator touch events not working

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#3206]
When I installed the android SDK I followed the instructions here:

https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux. I also installed the 32-bit libraries in there.

I'm running a 64 bit ubuntu 14.04. 

I ran the app using `meteor run android` and got the following logs:

```
[[[[[ ~/Meteor Projects/myapp ]]]]]        

=> Started proxy.                             
=> Started MongoDB.                           
Android emulator acceleration was not installed; the emulator will be very slow.
You can run 'meteor install-sdk android' for help.
=> Started app on Android Emulator.           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20141129-15:30:18.253(-5) (android:http://meteor.local/cordova.js:1154) deviceready has not fired after 5 seconds.
I20141129-15:30:18.294(-5) (android:http://meteor.local/cordova.js:1147) Channel not fired: onDOMContentLoaded

```

The app shows up on the emulator, but when I click on stuff, it doesn't do anything.

Does the `Android emulator acceleration was not installed; the emulator will be very slow.` have any thing to do with it?

Also my output of the following command `egrep -c '(vmx|svm)' /proc/cpuinfo` just gave me `8`, I'm guessing it's referring to the number of cores in my computer, but not sure if that has anything to do with KVM.

**Comment by unparalleled-js** [comment]
This is happening to me now. I am using Android Studio and getting no error messages. I can't figure out what is going on.

**Comment by developermithun** [comment]
This is happening to me also. Everything works Fine. No errors or no crashes, but the elements like switch button is not working on mouse click though its working on keyboard press. Usual button can be pressed using mouse clicks.

**Comment by filipenevola** [comment]
Hi, if you are still having this problem please open a new issue.
