### ISSUE TITLE
Meteor check function fails on Safari and Firefox but works in Chrome

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#3207]
A simple check if a value is a File fails in all browsers but Google Chrome

```
var f = document.getElementById('file').files[0];
check(f, window.File);
```

here is the output from the console on safari

```
> f
< FileConstructor

> window.File
< FileConstructor

> check(f, window.File)
Error: Match error: Expected plain object in field prototype
```

and firefox

```
f
File { size=587854, type="image/jpeg", name="14 - 1.jpg", more...}
window.File
[object File]
check(f, window.File)
Error: Bad pattern: unknown pattern type


...hrow Error("Bad pattern: unknown pattern type");                            // 2...
```

**Comment by davidworkman9** [comment]
This also came up with my app. ```typeof window.File``` is ```function``` in both Firefox and Chrome, but the check fails in Firefox and passes in Chrome. If this isn't going to be addressed than I think this part of the ```Check``` documentation should be reworded:

> Any constructor function (eg, Date)
> Matches any element that is an instance of that type.

**Comment by micchickenburger** [comment]
We also have failures in older-recent versions of Firefox, Safari, and IE where those browsers consider `Element instanceof Function // false`.  Conversely, in new versions of those browsers and in Chrome `Element instanceof Function // true`.  That allows checks to pass for elements only in new browsers:

    check(document.createElement('a'), Element);
    // new browsers, no problem
    // old browsers:  Error:  Match Error:  Expected plain object
