### ISSUE TITLE
Installation android sdk on vmware

### ISSUE THREAD

**Issue by hsd99** [meteor/meteor#3210]
I stuck with installing android sdk. I run my Ubuntu 14 on VMWare.
Here is a log from command **meteor install-sdk android**

```
✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
✓ Found Android Build Tools                   
✓ Found Android 19 API                        
✓ Found suitable Android x86 image            
✓ 'meteor' android virtual device (AVD) found 
✗ Android emulator acceleration is not installed
  (The Android emulator will be very slow without acceleration)
Platform requirements not yet met             
Please follow the instructions here:          
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux#haxm
```

I have two devices which work under Android control. I don't need emulator for test. I would like to skip this requirement for fast emulator. **Do you know some workaround for this limitation?**

**Comment by nothingofit** [comment]
It won't let me add the platform.

It says "The Android platform is not installed; please run: meteor install-sdk android"
