### ISSUE TITLE
this.unblock() does not work if Meteor method stub writes to Minimongo

### ISSUE THREAD

**Issue by fongandrew** [meteor/meteor#3211]
This might be intended behavior, but it definitely stumped me for a few hours.

Here's the Meteor method in question:

```javascript
Meteor.methods({
  "test/1": function() {
    this.unblock();
    var inserted = TestCollection.insert({name: "who"});
    if (! this.isSimulation) {
      Meteor._sleepForMs(5000);
    }
    return {inserted: inserted};
  }
});
```

Despite the `this.unblock()` call, this method will result in the client blocking on subsequent Meteor methods and subscriptions. Making the insert server-side only (i.e. moving it under the `if (! this.isSimulation)` block) resolves the issue.

The documentation for [Meteor.call](http://docs.meteor.com/#/full/meteor_call) does mention that "Meteor tracks the database writes performed by methods, both on the client and the server, and does not invoke asyncCallback until all of the server's writes replace the stub's writes in the local cache." I didn't read that as stating that the call would be blocking on other methods and subscriptions however.

**Comment by glasser** [comment]
Thanks for the clear reproduction.

This is in fact intended behavior.  Method 1's unblock is in fact working: If you click 1 and then immediately 3, you can see the "Method 3 start" immediately on the server.  And if you use the onResultReceived option to `Meteor.apply` (not available with `Meteor.call`) you can process the result immediately.

This behavior is documented as:

> Meteor tracks the database writes performed by methods, both on the client and the server, and does not invoke asyncCallback until all of the server's writes replace the stub's writes in the local cache. In some cases, there can be a lag between the method's return value being available and the writes being visible: for example, if another method still outstanding wrote to the same document, the local cache may not be up to date until the other method finishes as well. If you want to process the method's result as soon as it arrives from the server, even if the method's writes are not available yet, you can specify an onResultReceived callback to Meteor.apply.

Basically, Meteor waits until *all* latency-compensated changes (such as the stub's local insert from method 1) that are outstanding at the time that the method returns are visible to call the main callback.  We found that most users expected to be able to examine the DOM or minimongo in the callback and see real server values, not the stub changes, and so this delay was reasonable; onResultReceived allows you to explicitly get a callback as early as possible (with the tradeoff that visible data might still be stubbed).
