### ISSUE TITLE
white screen on adroid simulator 

### ISSUE THREAD

**Issue by pociej** [meteor/meteor#3228]
when i run app (even
 if it is app created with meteor create without any modifications) , then close android simulator and rerun , meteor run android i can see app anymore , white screen nothing more. Only way to solve it i founded is to reinstall android sdk . somebody knows whats going on ? im using ubuntu 12.04. thx in advance,

**Comment by NawazKhanMd** [comment]
do we need a virtual host to run my meteor app on mobile?

cuz am running meteor run android-device -p MyIp:3000 --mobile-server virtualHostIpToWhichMobileIsConnected:3000

this gives me a blank screen

am i doing it wrong pls Reply :)
