### ISSUE TITLE
DDP/sockjs JSON Parse error on iOS cordova

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3230]
When running an app using `meteor run ios-device`, at some point either when initially starting the app and/or when reloading due to a local code change, I always see this error in the Xcode console:

> Uncaught Error: SyntaxError: JSON Parse error: Unrecognized token '<':2083:http://meteor.local/packages/ddp.js?1f971b2ac9f4bdab7372cb5098ed1e26ff98dfb2

It's being thrown here: https://github.com/meteor/meteor/blob/devel/packages/ddp/sockjs-0.3.4.js#L2018

As far as I can tell, the app still functions correctly. It never happens in the browser, even in iOS browsers. How can I further debug this? Is it just a sockjs bug, or something strange in my data that isn't getting encoded/decoded properly?

**Comment by aldeed** [comment]
@Slava, getting back to this. The value of `text` when this error is thrown is my entire (blank) HTML file.

```html
<!DOCTYPE html>
<html>
<head>
 <!-- a bunch of scripts, mete, etc. -->
</head>
<body>
</body>
</html>
```

It makes sense that this does not parse as JSON, but I don't know enough about the use of DDP for mobile to figure out why it's happening.

**Comment by Slava** [comment]
@aldeed as I said above, it is possible that web-app package has a race condition where it serves the boilerplate (the initial html) by mistake.

**Comment by aldeed** [comment]
OK, yeah I see your earlier comment now. This is a gigantic app with NDA attached, so I'm not sure how feasible it would be to create a reproduction.

If you don't feel there's anything fixable here, I'm okay with closing this. It doesn't seem to break anything, although it does make me nervous. :)

**Comment by Slava** [comment]
Yesterday one of my friends PMed about hitting this same issue. Later he reported that it was caused by Cordova not copying some of his files to the app. In the end of the day, his description was matching #2920. So this might be one way to get this behavior consistently - having files not being copied by the cordova-cli.

But this particular issue looks different as the boilerplate is returned for a sockjs url. I still think this comment might help someone hitting a similar error for a different reason.

**Comment by sunlee-newyork** [comment]
Not sure if my two cents will be worth anything, but leaving here in case:
I had the same issue with a skeleton architecture (barely started) and the error went away when I added the forward slash to close off my meta tags in my main.html:

```html
<head>
	<meta charset="utf-8">
	<title>Shop Chop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<body></body>
```
turned into 
```html
<head>
	<meta charset="utf-8" />
	<title>Shop Chop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
</head>

<body></body>
```

**Comment by aldeed** [comment]
@sunlee-newyork That seems like very helpful information. Maybe you can create a new issue referencing this issue and MDG might be able to actually fix this with your new details to help reproduce.

**Comment by sunlee-newyork** [comment]
@aldeed will do!
