### ISSUE TITLE
Potentially bewildering auto-addition of packages

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#3236]
Hi everyone,
as far as i understand it, when a package "foo" needs another package "bar" to do it thing, with a "use('bar')" directive in its package.js, when adding the package "foo" with "meteor add foo", the command line reports that the "bar" package was added.
The problem with that is, again if i'm not wrong, that the aforementionned bar package is indeed NOT added to the main app but only added for the package foo to use.
This is bewildering for the fine developer who doesn't understand why the package that was reported to have been added should be added again for the main app to be able to use it.

Imho, either the "package added" mention should be clearer, or the auto-adding should be valid for the main app (but that would perhaps break the "imply" directive's goal).

Thank you very much.

**Comment by glasser** [comment]
As of 1.0.2, the message has a new header, "Changes to your project's package version selections".  I hope this is more clear.
