### ISSUE TITLE
/examples returning 404

### ISSUE THREAD

**Issue by stephen-puiszis** [meteor/meteor#3241]
https://www.meteor.com/examples - returns 404. Highest ranking search result for "Meteor Examples"
![screen shot 2014-12-05 at 5 34 07 pm](https://cloud.githubusercontent.com/assets/1960738/5324809/f3544e62-7ca4-11e4-870a-711133c3dd8f.png)
![screen shot 2014-12-05 at 5 33 42 pm](https://cloud.githubusercontent.com/assets/1960738/5324810/f3576638-7ca4-11e4-8b91-59165c4da232.png)

**Comment by avital** [comment]
This seems to have been fixed, thanks!
