### ISSUE TITLE
Meteor fails to install when running an x86_64 kernel with an i386 userland.

### ISSUE THREAD

**Issue by cscott** [meteor/meteor#3244]
I'm running debian/unstable i386, but:

```
$ uname -a
Linux skiffserv 3.16-3-amd64 #1 SMP Debian 3.16.5-1 (2014-10-10) x86_64 GNU/Linux
```

This is a not-so-uncommon configuration, when you want to be able to run x86_64 binaries but keep compatibility with i386 for binary plugins, etc.

But:

```
$ curl https://install.meteor.com | /bin/sh
$ meteor help update
/home/cananian/.meteor/meteor: line 133: /home/cananian/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/bin/node: No such file or directory
$ ldd /home/cananian/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/bin/node
    not a dynamic executable
cananian@skiffserv:~/MysteryHunt/codex-blackboard$ file /home/cananian/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/bin/node
/home/cananian/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, BuildID[sha1]=9f31fe62a147759c74773ff926665a1f2026da68, stripped
```

The node binary is dynamically linked, against x86_64 libraries which I don't have installed on my system.  I guess maybe I need a way to force meteor to use i386 binaries (or, ideally, the meteor installer should recognize this situation itself).

**Comment by glasser** [comment]
Hi @cscott .  In this case (64-bit kernel, 32-bit userland) should we be considering the system to be fully 32-bit and not at all 64-bit?

What's a good way to detect this configuration? We've been relying on uname parsing since our initial release 3 years ago and haven't gotten many complaints like this, so we'd want to make sure that any improvement doesn't break existing Linux users.

**Comment by cscott** [comment]
@glasser you can run a static-linked x64 binary on a 64-bit kernel, or dynamically-linked binaries that include all of their dependencies.  So the kernel can access the full 64-bit address space (the primary benefit), as can some binaries.  But (as stated in the OP) the node binary is dynamically linked in such a way that it fails to load.  It's probably safer to consider the system fully 32-bit.

At the moment I'm using the following as `~/bin/uname`:
```sh
#!/bin/bash
if [ -z "$METEOR_HACK" ]; then
    /bin/uname "$@"
else
    # lie
    /bin/uname "$@" | sed -e 's/x86_64/i686/g'
fi
```
and that works fine, buttressing the case for treating the system as fully 32-bit.

I'd guess that looking at the default libc would be sufficient to detect this configuration:
```
$ file /lib/i386-linux-gnu/libc-2.19.so
/lib/i386-linux-gnu/libc-2.19.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=ac65ae935e37547298d602bf61e2f35d4877833f, for GNU/Linux 2.6.32, stripped
```
Or equivalently:
```
cananian@skiffserv:/tmp/xyzpdq$ echo 'int main(){return 0;}' > foo.c
cananian@skiffserv:/tmp/xyzpdq$ gcc -o foo foo.c
cananian@skiffserv:/tmp/xyzpdq$ file foo
foo: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=94b8c7d9af25555078de9a4349061b3e8c0e8166, not stripped
```
But I'd settle for just having a `$METEOR_ARCH` env var or other explicit way to override Meteor's default architecture choice.  (But it would still be user-friendly to do a test like one of the above and suggest the use of `$METEOR_ARCH` if problems seem likely.)

**Comment by emgee3** [comment]
One simpler way to detect this, though I'm not sure if it's a canonical way of determining bitness is  `getconf LONG_BIT`

On a server I have with a 64 bit kernel and 32 bit userland, returns the following:

    # uname -m
    x86_64
    # getconf LONG_BIT
    32

**Comment by cscott** [comment]
@emgee3 works for me, too, FWIW:
```
cananian@skiffserv:/tmp/xyzpdq$ getconf LONG_BIT
32
cananian@skiffserv:/tmp/xyzpdq$ uname -a
Linux skiffserv 3.16-3-amd64 #1 SMP Debian 3.16.5-1 (2014-10-10) x86_64 GNU/Linux
```

**Comment by abernix** [comment]
Can anyone familiar with this issue speak on whether this is resolved?  A lot has changed and this ticket hasn't had much activity / +1's.  I propose closing it.

**Comment by hwillson** [comment]
Assuming fixed and closing due to a lack of activity. Thanks for reporting this originally!
