### ISSUE TITLE
Meteor documentation reloads into infinity

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3248]
It happened to me few times already. I come to Meteor documentation and it just starts reloading. Using Firefox 33.1.

In the console I have: `SyntaxError: syntax error` for JavaScript file.

It seems there is some caching issue. It seems HTML content is from previous version of docs site so it tries to load the old JavaScript file. For example, currently it is trying to load ` /9d9680d5aadc5699446f0e6295cd40e15aad638b.js`. If I look at it I see that it is a Meteor HTML file with has in fact `/1f5daafd65826351fd694cade3425cd694099569.js` for its JavaScript file. So it seems that docs site was upgraded in meantime, but my Firefox browser did not reread the HTML content. And then safety belt is reloading the page.

Is there a way to say to `document.location.reload` to clear the cache before? Because it does not seem to be doing that.

command-shift-r seems to fix the issue because a new page is loaded.

**Comment by glasser** [comment]
Not sure what's going on here. Are you still seeing this? I don't see it on Mac FF 34.0.5.  Guessing this is an appcache issue.

**Comment by mitar** [comment]
Yes. It was an appcache issue. It happens just when you upgrade to new version, sometimes. So it is hard to debug. I will report if/when it happens again.

**Comment by mpranjic** [comment]
Happened to me as well (reported on google group, got ignored), forcing cache reload fixes it.

**Comment by mpranjic** [comment]
Update: It happened again for me, but now it doesn't reload, it actually never loads.
It only happens in one browser (firefox stable).
Nothing ever loads into ```<body>```, it just spins forever.
The only thing in console is this:
```
"W20150123-15:45:59.646(1) (1a2b7453edaeed10ce00e77f31ae53be016a856f.js:52) Warning: Blaze.render without a parent element is deprecated. You must specify where to insert the rendered content."
```
I have no idea how to make it work. I just use another browser.

**Comment by mitar** [comment]
I made it work by flushing the appcache, see [here](https://github.com/meteor/meteor/issues/3380#issuecomment-68277268). Bu the issue is that then we missed the opportunity to debug. :-)

**Comment by glasser** [comment]
So it might just be that Firefox appcache is buggy. Before 0.9.0 we disabled appcache on FF by default, because it would give you a confusing popup if you ran it.  In 0.9.0 we changed that because the popup was gone, but I guess it's just buggy?  At the very least, maybe we should disable appcache on docs.meteor.com.

**Comment by glasser** [comment]
appcache should now be disabled on docs.meteor.com for firefox.  Let me know if you still see problems!

**Comment by scmart** [comment]
I still get this issue from time to time on firefox.  Keep getting a "The connection to ws://docs.meteor.com/....   was interrupted while the page was loading"
