### ISSUE TITLE
Request: Add mongofiles binary to dev bundle

### ISSUE THREAD

**Issue by lewislambert** [meteor/meteor#3256]
Hi,

I know that currently Meteor does not natively support GridFS collections, but with the addition of others adding support via atmosphere packages, I think it would be a nice addition to distribute the **mongofiles** binary within the dev bundles alongside **mongo** and **mongod**. This could then be accessed through the Meteor command line interface such as `meteor mongofiles`.

Thanks

**Comment by glasser** [comment]
I understand why you'd want this --- at MDG we use GridFS in one piece of infrastructure and were sad to not have trivial access to this binary when we needed to debug it recently. But there's a tradeoff — everything we include in the dev bundle / tool makes initial installs and upgrades of meteor slower.  mongofiles on my Mac is 25M uncompressed, which would be a pretty significant increase to the dev bundle size.  Most Meteor users won't use GridFS and I think the costs here outweigh the benefits; MongoDB does make it pretty easy to download binaries from their website.  (Also, we've been pretty unhappy with the reliability and performance of GridFS in our infrastructure and don't think it is the best choice for most users, compared to something like S3.)
