### ISSUE TITLE
The newfangled docs search is triggered by various special keys

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3257]
At http://docs.meteor.com, I can no longer scroll using the arrow keys. Whenever I press an arrow key, the page shows the search form.

Chrome 39.

**Comment by dandv** [comment]
Thanks! Can you exclude the Function keys from triggering the search as well? For example, in Chrome, F3 goes to the next browser search result, but on docs, the results will be hidden by the search form overlay.

**Comment by stubailo** [comment]
Thanks for reporting!

**Comment by abernix** [comment]
The previous newfangled docs have been replaced with other newfangled docs.  And docs now has it's own repository and ability to make contributions yourself!  If you have problems please check the existing issues or open new issues at [the newfangled Meteor Docs repo](http://github.com/meteor/docs/).

"Newfangled" is a great word.  Thanks for reporting this originally! :smile:
