### ISSUE TITLE
Consider building packages in parallel

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3263]
We build a dependency graph and then walk it in IsopackCache to build local packages. If there are two packages that don't depend on each other, we should be able to build them in parallel, which at least will mean that some IO (whatever is streamed) and calls to `npm ls --json` will run in parallel.

**Comment by danlg** [comment]
the build time in meteor is long for real production app with many packages. this is a pain. parallel build will help

**Comment by hwillson** [comment]
Meteor 1.4.2 has introduced many build tool performance improvements. I'll close this issue due to its age, but if anyone is still having build tool performance issues using the latest version of Meteor, please post back and let us know. Thanks!
