### ISSUE TITLE
Make `UI._escape` part of the public API.

### ISSUE THREAD

**Issue by cscott** [meteor/meteor#3267]
**_1 Upvote**_ If you are dealing with `Spacebars.SafeString`s, it is handy to have a reliable html-escaping method handy.

The `Handlebars._escape` method, which does basic HTML-safety escaping, isn't public, although it's now available at `UI._escape` as well.  Any chance this could be made public, perhaps as `Spacebars.SafeString.escape`?

**Comment by avital** [comment]
Sure, that's a good point! We should probably just expose it as `Spacebars.escape`. We'll take a pull request implementing this with newly written tests and docs.

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#200 - closing here - thanks!
