### ISSUE TITLE
Namespacing, inheritance, and single page components for Blaze.

### ISSUE THREAD

**Issue by zephraph** [meteor/meteor#3277]
I'm a pretty big fan of Blaze. It does what I need it to and it gets out of my way. There's no denying that it lacks some pretty crucial functionality though. What I'm about to go through has probably been suggested a billion times, but hopefully I can provide some interesting solutions. I've tried to make suggestions that keep Blaze working as is, but with added benefits if desired. 

### Namespacing
Blaze could really benefit from namespacing. I think it makes sense to simply add a namespace attribute to the template tag. 
 
```html
<template name="bar" namespace="foo">
```
The template would then be accessed through that namespace. 

```js
Templates.foo.bar.helpers({ ... });
```

**Shared helpers**

This would also be useful for sharing helper functions. It seems to me like it would make sense to be able to define helpers on a namespace and then have all the templates of that namespace inherit those helpers.

```js
// Accessible by all templates in the foo namespace
Templates.foo.helpers({
   nsHelper: function() { doSomething(); }
});
```
 So any helper defined in ```Templates.foo``` would be inherited by ```Templates.foo.bar``` with the caveat that the template has precedence over the namespace. 

**Default namespace**
By default without specifying a namespace the templates would be stored on the global namespace. It could get quite annoying to specify one's application namespace over and over though, so specifying a default namespace would be handy. 

```js
Blaze.defaultNamespace('myApp')
/* or */
Templates.defaultNamespace('myApp')
```
This would give module authors with existing modules an easy way to namespace their module without having to add attributes onto every single template tag. 

### Inheritance
Much like namespacing, I'd like to have extendable templates without completely destroying all the work I've already put into my components. Also like namespace, I suggest specifying the parent by using an attribute. 

```html
<template name="child" extends="parent">
<!-- Used in conjunction with namespacing -->
<template name="child" extends="otherNS.parent" namespace="myNS">
```

The effects of extending a template:

1.  All template specific methods properties would be inherited (events, helpers, and rendered, created, destroyed callbacks).
2.  Something of the effect of ```{{>super}}``` would be provided to the child template so it could reuse the parent's layout if desired.

### Single Page Components
*As a preface to this, I don't consider this feature needed. It's just something I would like to see but can live without*  I first encountered single page components through Vue via [vueify](https://github.com/vuejs/vueify). It would provide the ability to keep everything about that component in a single file. 

```html
<template name="myTemplate">
  <!-- stuff -->
</template>

<style>
  .myClass {
    display: block;
    ...
  }
</style>

<script>
  Templates.myTemplate.helpers({...});
</script>
```

I think that's all for now... what do you guys and gals think?

**Comment by avital** [comment]
Thanks for the time you put into writing this well-constructed feature request! I really appreciate the concreteness of your proposals. And I agree that you are touching upon real problems. But I don't think we can devote time right now to addressing these.

I'd like to keep a discussion open on GitHub about these proposals, but if you'd like that, I need to ask you to file each of these proposals as separate issues. The discussion on each would be a very different one.

You might also be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).
