### ISSUE TITLE
Run `npm ls --json` in parallel with rest of compilation

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3279]

**Comment by glasser** [comment]
One idea — move `updateDependencies` out of `compiler.compile` and into a new ProjectContext stage that comes *before* buildLocalPackages that runs updateNpmDependencies on all packages in parallel.

Downside — the current system doesn't call updateNpmDependencies at all on packages whose isopacks are up-to-date, so this might actually make things slower.

So we could go a step farther: buildLocalPackages (in IsopackCache) could first do a walk to determine the order of local packages to load and load all the ones that require no building while it does that (versioned packages and ones where the caches work).  Then, it could updateNpmDependencies on all the packages that need to be built in parallel.  Then compiler.compile them.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Run%20%60npm%20ls%20--json%60%20in%20parallel%20with%20rest%20of%20compilation&body=Migrated%20from:%20meteor/meteor%233279) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
