### ISSUE TITLE
Android: localmarket scrolling glitch

### ISSUE THREAD

**Issue by hieutang511** [meteor/meteor#3289]
Hi all,
I was trying the *localmarket* app on my device (LG-LU6200, Android 4.1.2) when I noticed the scroll effect didn't go smoothly. Here is the Youtube [link](https://www.youtube.com/watch?v=AJxr8LND670)

It went smoothly on another device LG-F340L (Korean G2), Android 4.4.2

**Comment by abernix** [comment]
Local Market is it's own repo now on GitHub and has had a lot of updates since this issue was reported.  This issue is very old and without reproduction or upvotes.  Closing.  

Report any continuing issues on https://github.com/meteor/localmarket 😄
