### ISSUE TITLE
App crashes spontaneously on http.js:731

### ISSUE THREAD

**Issue by axenkhan** [meteor/meteor#3291]
![screenshot 2014-12-15 01 12 51](https://cloud.githubusercontent.com/assets/4901399/5429308/51db0062-83f7-11e4-8b13-e5b804e42b53.png)
App consists of just 4 landing pages, simple routing and no headers used.

Nothing sends any headers but still app crashes without any reason. I can't understand what causes the problem. It just writes "throw new Error(' Can\'t render headers after they are sent to the client')".

I have no JS files for server, that could cause the problem. We use only client-side scripts for our interface.

That is our wesbite: http://sunrise.mg

Here's the code for routing:

Router.configure({
  loadingTemplate: 'loading'
});

Router.onBeforeAction('loading');

Router.onAfterAction(function() {
  // always start by resetting scroll to top of the page
  $(window).scrollTop(0);
  
  // if there is a hash in the URL, handle it
  if (this.params.hash) {
    // now this is important : Deps.afterFlush ensures that iron-router rendering
    // process has finished inserting the current route template into DOM so we
    // can manipulate it via jQuery, if you skip this part the HTML element you
    // want to scroll to might not yet be present in the DOM (this is probably
    // why your code fails in the first place)
    Deps.afterFlush(_.bind(function() {
      var scrollTop = $("#" + this.params.hash).offset().top;
      $("html,body").animate({
        scrollTop: scrollTop
      });
    }, this));
  }
});

Router.map(function() {

  this.route('home', {
    path: '/',
    layoutTemplate: 'landingLayout',
    yieldTemplates: { 'landingHome': {to: 'landing'} }
  });

  this.route('our-projects', {
    path: '/our-projects',
    layoutTemplate: 'landingLayout',
    yieldTemplates: { 'landingWork': {to: 'landing'} }
  });

  this.route('our-expertise', {
    path: '/our-expertise',
    layoutTemplate: 'landingLayout',
    yieldTemplates: { 'landingAbout': {to: 'landing'} }
  });

  this.route('get-in-touch', {
    path: '/get-in-touch',
    layoutTemplate: 'landingLayout',
    yieldTemplates: { 'landingContacts': {to: 'landing'} }
  });

});

**Comment by xumx** [comment]
I've noticed the same error today. 

Meteor runs fine on first load. 

but after I change some files, and try a hot code push, this error shows up. 
![image](https://cloud.githubusercontent.com/assets/357667/5691490/18a7a40e-9904-11e4-836e-c01e29fcf4f2.png)


Might have something to do with Cordova. I tried to build the Cordova version today.

**Comment by avital** [comment]
Closing due to lack of a [repro that we can clone and run](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor). Happy to re-open if one is supplied.
