### ISSUE TITLE
Blaze + Polymer

### ISSUE THREAD

**Issue by leebenson** [meteor/meteor#3292]
**_4 Upvotes**_ Not sure if this is Blaze or Polymer, but see: https://github.com/ecwyne/meteor-polymer/issues/19

in Chrome - click events fire on a web component natively.

in Safari/Firefox - template tags must be wrapped in a divfor any Template.name.events to fire on Polymer objects.

Blaze's event handling is being overridden (overwritten?) somewhere...

**Comment by avital** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by Pickachu** [comment]
:+1:

**Comment by luccamordente** [comment]
:+1:

**Comment by mattiLeBlanc** [comment]
Any fix already?

**Comment by brylie** [comment]
Please add your support and comments regarding web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment]
Use polymer as the default view layer using mwc:synthesis package 
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by hwillson** [comment]
I've moved this over to meteor/blaze#195 - thanks!
