### ISSUE TITLE
focus effect on main button

### ISSUE THREAD

**Issue by FezVrasta** [meteor/meteor#3294]
The big button (install v x.x.x) is blue when focused. Looks like you have overridden the style of :active and :hover but not of :focus

**Comment by benhohner** [comment]
I'd like to fix this and a bunch of anchor bugs in the docs. I take it the meteor.com repo is private though?

**Comment by glasser** [comment]
@benhohner The docs are in the main meteor repo.  I think we've fixed some of the anchor bugs recently, but maybe not all of them? It's just a Meteor app in the `docs` directory. (You need to run `scripts/admin/jsdoc/jsdoc.sh` to refresh some text from program comments into the app.)

**Comment by glasser** [comment]
Thanks for the report. I've moved it to the private repo with our frontpage app.

**Comment by benhohner** [comment]
@glasser thanks, I'll check that out. What about the core meteor.com site? How do I contribute to that?

**Comment by glasser** [comment]
As I said, it's private.
