### ISSUE TITLE
Scroll event

### ISSUE THREAD

**Issue by eterey** [meteor/meteor#3298]
I haven't found a way to add scroll event listener cleanly within "Template.template.events".

Right now I use jQuery for scroll event handler:

```
$(window).scroll(function(){//your code});
```

Things I was trying to use as the selector but to no avail were:
- `'scroll *'`
- `'scroll body'`
- `'scroll document'`
- `'scroll window'`

I propose add support of handling the scroll event in MeteorJS.

**Comment by bipin244** [comment]
how can we used scroll event in modal

**Comment by Borderliner** [comment]
It's a simple yet annoying problem with Meteor. I would like to see the scroll event in future releases.

**Comment by NitroBAY** [comment]
Totally agree, if Meteor has his own way of defining event listener we need to be able to have at least most of basic events.

**Comment by abernix** [comment]
@NitroBAY I believe if this is something you're interested in at this point, it would be best to take this up with the [Blaze repository](https://github.com/meteor/blaze) as I believe that's where that functionality would need to be implemented.

**Comment by NitroBAY** [comment]
Oh yeah sorry I forgot that you drop Blaze :D
