### ISSUE TITLE
[cordova] Upgrade the cordova cli / lib

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3299]
The current version is 3.5.0-0.2.4

I read that 9-patch images arent supported in the current cordova implementation - its fixed in https://github.com/apache/cordova-lib/commit/d50441c26fe8a912f33d1891a603ab8c92d3c5d1

3.5 got banned from google play 1. oct. *(got an email then)*

It a bit cumbersome to workaround, the workflow for ios is super nice - I'm sure theres a reason for using 3.5, but it would be cool if we could bump this to something like 4.1.2 - Let me know if I can help out/test etc. Thanks

cc @Slava

**Comment by raix** [comment]
@Slava

I'm using 1.0.3.1 accordingly to http://docs.meteor.com/#/full/App-launchScreens patch 9 screens are supported - thats not true since cordova is still at 3.5.1

I tried using the cordova-build-override, but this conflicts with files set by meteor (can I make prevent meteor from setting these?).

I've tested the `cordova-41.0` and it now names files correctly,

**Comment by davidwoody** [comment]
@raix maybe this resolves the issue - https://github.com/meteor/meteor/pull/3429

**Comment by raix** [comment]
For anybody that needs a solution:
Add `cordova-build-override/hooks/after_prepare/make9patch.sh` (`$ chmod +x make9patch.sh`)
```bash
# Fix patch 9 images for the Meteor Cordova implementation
# by RaiX 2015
# 
echo "Fix patch 9 launch screens"

# Point to the res folder
RESFOLDER="platforms/android/res/"

# Scan for screen.png and rename to screen.9.png
for file in $(find $RESFOLDER -type f -name "screen.png"); do
  # Make new filename
  name=${file/screen.png/screen.9.png}

  # Rename
  mv $file $name
done
```

**Comment by dotnetwise** [comment]
@Slava on `History.md` says you have already upgraded `Cordova CLI` to `4.2.0` on the version `1.0.3.2`

However after `meteor update --release 1.0.3.2` is still using `cordova 3.5.0` on `ios` and `3.5.1` on `android`

So when will you release the `cordova` to `4.2.0 cli` and `3.6.4 android` / `3.7.1 ios` ?

Also there is no blog about meteor `1.0.3.2`

**Comment by Slava** [comment]
No, history file says it was done for an unreleased version on devel.

**Comment by dotnetwise** [comment]
So when will it be really released?
We used to target 4.2/3.7.1/3.6.4 and now moved to meteor, but we stumble of cordova 3.5.0/3.5.1 :(

**Comment by Slava** [comment]
It is on `devel` branch. It is going to be released with 1.0.4.

**Comment by dotnetwise** [comment]
Released in a week / two ? How long?
Is there any way I can "try" the devel branch right now?

**Comment by Slava** [comment]
Upgraded as of 1.0.4

**Comment by dotnetwise** [comment]
Great! Thanks!
