### ISSUE TITLE
Allow exclusion of files/directories in packaging/deployment process

### ISSUE THREAD

**Issue by joscha** [meteor/meteor#330]
**_3 Upvotes**_ When using external dependencies such as npm packages and/or git submodules it would be nice to exclude some of them on either the server, the client or both.
A way to specify exclude directories would be nice - currently there is only the way to misuse the tests/ directory or add it below public, which doesn't make sense for all resources.

**Comment by onip** [comment]
another use case:
I've got some static content (jpg images) which I serve from public during development. In production there's a proxy handling those images and I'd like `meteor build` not to bundle those to have

* reduced bundle size
* a clear 404 if problems arise in proxy server: with the current way if proxy is misconfigured requests reach meteor which responds with older (and so *wrong* it is an artificial vision app) images without anyone noticing it.

Thanks

**Comment by wmodes** [comment]
+1 .meteorignore

**Comment by laosb** [comment]
+1 .meteorignore

I have a deploy shell script in the project.

**Comment by glasser** [comment]
We are tracking a better way of defining apps on the [roadmap](https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-apps-and-controlling-file-load-order)

**Comment by sevki** [comment]
:+1: .meteorignore

**Comment by sebastianconcept** [comment]
yes, I would use a `.meteorignore` config file :)

**Comment by robertpitt** [comment]
.meteorignore :+1:

**Comment by stephenbunch** [comment]
.meteorignore +1

**Comment by ctzurcanu** [comment]
.meteorignore +1

cannot build my project with many public files without it.

**Comment by rozzzly** [comment]
.meteorignore +1

**Comment by servel333** [comment]
From #4958

As a developer, I would like to have a way to include custom folders to be ignored by the Meteor file gobbler.

These could be

* unique files generated by my choice of editors
* files that are part of some tool I am using
* a `docs/` directory I put documentation in
* a `tmp/` directory I might put files that are not part of the codebase but are related to the project in
* personal notes files I put notes into (I sometimes put program extensions on them so I can put syntax highlighted code in my notes)
* etc.

### Possible solutions:

* Add an ignore file that works like `.gitignore` (List of regexes, `#` for comments, `!` to include files)
  * Possible file names: `.meteorignore`. `.meteor/ignore`
* Add a config file that lists files and folders to be ignore
  * Possible file names: `.meteor/config.json`, `.meteor/preload.js`

**Comment by tcurdt** [comment]
+1 ...and may I emphasize - this issue is open since 2012

**Comment by acidicX** [comment]
+1 .meteorignore

**Comment by mosleyjr** [comment]
+1 .meteorignore

**Comment by logankoester** [comment]
:+1:

**Comment by yogiben** [comment]
+1 .meteorignore

**Comment by gCardinal** [comment]
Adding my voice to the .meteorignore crowd. Hard to believe this was opened 3 years ago.

**Comment by laosb** [comment]
That's not the only open issue opened 3 years ago.

> On Feb 10 2016, at 10:46 pm, Guyllaume Cardinal
&lt;notifications@github.com&gt; wrote:  

>

> Adding my voice to the .meteorignore crowd. Hard to believe this was opened
3 years ago.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/meteor/
meteor/issues/330#issuecomment-182403358).![](https://github.com/notifications
/beacon/ACbWbUwr1UymPHQG1hrGl4jjAuno9iDPks5pi0TSgaJpZM4AJZPX.gif)

**Comment by Isigiel** [comment]
+1

**Comment by maximsko** [comment]
+1

**Comment by JIoJIaJIu** [comment]
+1

**Comment by emilianosantucci** [comment]
+1 for project with mixin platform like Meteor + Angular 2 + Polymer (last need exclusion from angular compiler)

**Comment by servel333** [comment]
@avital or anyone, do you think it might make sense to reopen this issue, since there seems to be a lot of interest in this?

**Comment by abernix** [comment]
@servel333 Maybe look at and +1 the related (and open) #6002 if that sounds like what you want?

**Comment by servel333** [comment]
Thanks. Perfect.
