### ISSUE TITLE
On meteor create installing meteor tool @ 1.0.36 takes a long time

### ISSUE THREAD

**Issue by charue808** [meteor/meteor#3308]
Has there been any experience when doing meteor create "appname" it logs installing meteor tool @ 1.0.36 and can take anywhere from 5 - 30 minutes on average to complete this task. Is this a common issue, I haven't found any documentation on this but it seems to be taking a longer time than I've experienced in the past.

**Comment by glasser** [comment]
That's the tool for 1.0.1, and we focused a lot on tool performance improvements in 1.0.2.  Hopefully this is somewhat better now.
