### ISSUE TITLE
Improve {{#each}} errors logging

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3312]
**_1 Upvote**_ If I pass a currently non-iterable variable to a Spacebars `{{#each}}`, I get the following exception:

> Exception from Tracker recompute function: {{#each}} currently only accepts arrays, cursors or falsey values.
> [very long stack trace]

However, I have no hint as to _which_ iterator failed. Even on a medium-sized app, it is extremely time-consuming to narrow down on the responsible template.

I expect the runtime to tell me the name of the template, and the line and column number of the failing iterator.

**Comment by avital** [comment]
Yes, you're right -- at the moment, it's very hard to figure out which line in your .html file triggers this error. It might be tricky to get this right so I don't see us resolving this very soon, but I'll leave this issue open so that we can track how frequently people hit it.

**Comment by jsilverMDX** [comment]
I'm hitting this issue. It happened randomly. I have tried returning false in all of my helpers.

**Comment by jsilverMDX** [comment]
Got around it, but not sure how. This is a hard one to debug. Just saying.

**Comment by art3i** [comment]
just happened now; got this same issue.

**Comment by samosfator** [comment]
+1 faced this right now

**Comment by webdevbrian** [comment]
Getting this currently as well.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#184 and added a repro. Closing here - thanks!
