### ISSUE TITLE
Need some progress output when stdout is not a TTY

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3316]
It's great that we've moved most of our progress messages to the progress bar, but this means that basically nothing shows up when you're running outside of a TTY (eg, from a scripted deploy).

**Comment by hwillson** [comment]
This has been addressed by leveraging the `METEOR_HEADLESS` environment variable (https://github.com/meteor/meteor/commit/5d0da71e2792c50320af910a85c6f2377df8965b) (or by using the `--headless` CLI option - #7245). Closing - thanks!
