### ISSUE TITLE
signing meteor android app incorrectly for < 4.4

### ISSUE THREAD

**Issue by zsal** [meteor/meteor#3318]
For any Android device running a version below 4.4, the Google Play store says the app is not signed correctly, even when I followed all the instructions on the wiki: https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store 

Does anyone know what could be the problem? My only guess would be that I didn't specify an expiration time during the kengen/sign, but thats not on the wiki.

**Comment by avital** [comment]
Looks like this is solved by setting a unique `id` property. On http://docs.meteor.com/#/full/App-info, looks like the docs do describe the `id` field, but maybe not with much details. Happy to consider pull requests to our docs (that live in the `docs/` subdirectory in the Meteor repository) clarifying this.
