### ISSUE TITLE
Typos in the docs

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3319]
In helpers:

- "or use the "nametag" template from above instead of `<p>` tags:" is wrong because there are still `<p>` tags in the subsequent code sample.
- `<p>There are {{commentCount 3}} comments.</p>` will result in printing `There are 3 comments comments`.

in events:

- the code sample after "To attach event handlers to the following template" has an empty template.
- `See the [Event Maps section](#eventmaps) for details.`

**Comment by avital** [comment]
@adnissen have you gotten to that pull request?

**Comment by glasser** [comment]
Not sure what the "Event Maps section" issue was, and the comments count was already fixed I believe, but fixed the rest on devel.
