### ISSUE TITLE
Sessions from the facts package is sometimes negative.

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#3331]
![image](https://cloud.githubusercontent.com/assets/499401/5476518/869c8302-85d7-11e4-9610-e565029051d5.png)

Sessions from the facts package is sometimes negative.  It goes up and down, sometimes negative sometimes positive.  This happens in production, haven't seen it in development.  It started happening recently.  Either during 1.0.1 or after upgrading to 1.0.2-rc.  It's still happening in 1.0.2.  Logs don't show any errors.

**Comment by glasser** [comment]
It would be great to hear if any other users of `facts` see this. Otherwise it's pretty tough to debug without a reproduction.

**Comment by glasser** [comment]
@dan335 Are you using Kadira?  (Could you share the contents of your `.meteor/versions`?)

**Comment by glasser** [comment]
@arunoda FYI we turned on Kadira for an internal app and immediately started observing this.  Is it possible that some of the wrapping that Kadira does prevents the sessions updates in livedata_server.js from happening properly?

**Comment by glasser** [comment]
hmm, managed to reproduce without kadira this time

**Comment by arunoda** [comment]
@glasser I don't think kadira is responsible for that. But I'll try to find if anything like that possible or not.

**Comment by glasser** [comment]
OK, we figured this out.  Should be a pretty simple fix.

We're not sure if this causes any serious problems other than the number being wrong.

**Comment by arunoda** [comment]
Is this something with kadira?

**Comment by glasser** [comment]
Doesn't seem to be (see above) though it is still suspicious that turning on Kadira made it happen immediately and to a much larger degree. It's possible that something about Kadira makes the bug case occur much more often.

**Comment by arunoda** [comment]
I'll look into that.
