### ISSUE TITLE
[1.0.2] File watcher fails with low fs resolution

### ISSUE THREAD

**Issue by pierre-b** [meteor/meteor#3335]
Hi,

The new file watcher takes more than 20 sec to detect a change in a template/js, and no more triggers on .less files to compile CSS.

I'm developping on vagrant with NFS, tried to add "export METEOR_WATCH_FORCE_POLLING=2" but it didn't help.

Is it possible to disable the new watcher and fallback to the CPU consuming one please ?

Thanks for your help

**Comment by pierre-b** [comment]
Hi @glasser , do you have new suggestions about this issue please ? 
I still can't upgrade to 1.0.2 because of it.
Is it because my project contains too many files to watch (300+) ?

**Comment by jagi** [comment]
My project contains around 1 500 files not including **packages** directory which contains around 13 000 files. But this number includes build files. Without build files its around 100. So everything is around **1 600** files.

**Comment by glasser** [comment]
Have you tried 1.0.2.1 instead of 1.0.2?  Did that fail too?  (And fail means "slow" not "crash" or "didn't detect changes", right?)

**Comment by pierre-b** [comment]
Yes 1.0.2.1 fails too, it takes 30+ sec to detect a change, even with METEOR_WATCH_FORCE_POLLING (NFS with Vagrant on OSX Yosemite).

Maybe a quick fix could be to watch a /tmp/restart.txt file like in Passenger to trigger a new build ? a maccro in my text editor would touch the file everytime I want to...

**Comment by jagi** [comment]
I'm also using Meteor 1.0.2.1 and the problem is still occurring.

**Comment by jagi** [comment]
I've noticed that the longer I run Meteor the slower it works. When I restart Meteor it works pretty fast. But after few hours of working it starts to work very very slow (I mean detection change). Maybe there is some problem with memory allocation and duplication of watched paths?

**Comment by pierre-b** [comment]
I noticed the problem comes from NFS wich takes time to propagate the diff in files (https://github.com/mitchellh/vagrant/issues/4204) it requires a new line to make it detectable.

So I switched to Virtualbox shared folders, the file updates are detected but I now get this crashing error:

```
/home/vagrant/.meteor/packages/meteor-tool/.1.0.38.41fy7p++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: ENOTEMPTY, directory not empty '/sites/Timebreak/meteor/.meteor/local/build-garbage-v5kr2o/programs'
  at Object.fs.rmdirSync (fs.js:623:18)
  at Object.files.rm_recursive (/home/vagrant/.meteor/packages/meteor-tool/.1.0.38.41fy7p++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/files.js:263:8)
```

Any ideas ? thank you for your help

**Comment by pierre-b** [comment]
I finally found a config that works fine, and posted the solution here in case: https://github.com/meteor/meteor/issues/3412

Feel free to close the issue ;)

**Comment by jagi** [comment]
It's not solving my problem because I'm not using VM.

**Comment by glasser** [comment]
OK. This issue was discussing several different things which got confusing. One of them was @pierre-b 's NFS misconfiguration.  The other is that watching gets slower over time, which seems to be the same as #3373. So I'll leave this closed.

(There's also the original "need to check again after a second" issue I guess.)
