### ISSUE TITLE
Apache ProxyPass websocket problem

### ISSUE THREAD

**Issue by fuatsengul** [meteor/meteor#3339]
Hi there,
I run my meteor app on my own server, It runs node and mongodb behind and there's an apache server at the front for routing for another websites that runs on my machine.

I'm also configured SSL on Apache and routed http layer to https with RewriteEngine, so any http requests automatically routed to https layer.

Everything is OK so far, but I see this error message in my console: 
WebSocket connection to 'wss://mydomain.com/sockjs/925/yb5xv02p/websocket' failed: Unexpected response code: 400

Request URL:wss://mydomain.com/sockjs/076/l1p9yvz8/websocket
Request Method:GET
Status Code:400 Bad Request
Request Headersview source
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,tr;q=0.6
Cache-Control:no-cache
Connection:Upgrade
Cookie:meteor_login_token=<my login token>; TAPi18next=en
Host:mydomain.com
Origin:https://mydomain.com
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:<my websocket key>
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Response Headersview source
Connection:close
Date:Sat, 20 Dec 2014 23:22:53 GMT
Transfer-Encoding:chunked

My checks:
Not every websocket requests drops, only this one.
If I use the original host (which I was proxied here) the error goes away, so there's a problem with proxy.
It's browser/platform independent.
I've also seen this, In web inspector's network tab, I can see the all requests, every websocket requests URL is on https:// but only this request uses wss://

**Comment by cellulosa** [comment]
Hi @fuatsengul could you please share your config?

I've got this error coming up:

    WebSocket connection to 'ws://website.com/sockjs/616/72ht6n8p/websocket' failed: Unexpected response code: 400

I'm on CentOS 7, Apache `2.4.6` and I've obviously got enabled 'mod_proxy`. I'm NOT on SSL, though. I've added the following line into `/etc/httpd/conf/httpd.conf` (just before declaring `ProxyPass`, like in the config example provided by the guy in your link):

    ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket

However, I still get the error. Is there anything else I need to do?

**Comment by fuatsengul** [comment]
Hello @cellulosa 
Sorry for late return, this setup is working for me:
The error page, SSL and rewrites(forcing ssl) are extra, you don't have to use them.

```
<VirtualHost *:443>
     ServerName mysite.com
     ServerAlias www.mysite.com

     SSLEngine on
     SSLProxyEngine On
     ProxyRequests Off

     SSLCertificateFile /etc/apache2/ssl/mysite.com.crt
     SSLCertificateKeyFile /etc/apache2/ssl/mysite.com.key
     SSLCertificateChainFile /etc/apache2/ssl/ca.cer

     DocumentRoot /var/www/errorPages

     ErrorDocument 503 /503.html
     ProxyPass /503.html !

     ProxyPass / http://localhost:3999/
     ProxyPassReverse / http://localhost:3999/


RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://localhost:3999%{REQUEST_URI} [P]


</VirtualHost>
```

**Comment by timbotnik** [comment]
@fuatsengul thanks for posting a working configuration.

**Comment by cellulosa** [comment]
@fuatsengul thanks for posting your configuration, however I'm still having issues with this.

I've also posted on StackOverflow [here](http://stackoverflow.com/questions/35270615/meteor-on-httpd-apache-2-4-6-centos-proxy-and-websockets) but no success so far.

Actually, on Android sometimes I get a security warning due to Name mismatch, but I don't have any ssl enabled... Maybe I should and that's the issue?

**Comment by cellulosa** [comment]
Ouch - resolved. My issue had to to with my Varnish configuration - I forgot all about it lol. I just disabled apache and the proxy as I'm passing the request straight to node.js via Varnish (more details in the StackOverflow question linked above).

**Comment by fuatsengul** [comment]
@cellulosa happy to hear that you've solved :+1:

**Comment by rachaelbe** [comment]
@fuatsengul this problem has been driving me nutty for months! your solution is the first one I've come across that doesn't work, or degrade the connection down to ajax. Thank you :-D

**Comment by evroza** [comment]
@fuatsengul Cheers mate, the rewrite conditions worked great for me.

**Comment by FaizanNoor** [comment]
@fuatsengul Thanks a lot bro for sharing the config. I was missing the "RewriteRule" rule. Added in the conf and it worked. Cheers!

**Comment by jobehi** [comment]
@fuatsengul 

Thank you very much ! that's exactly what I needed.

**Comment by rschiavi** [comment]
Has anyone seen this happen only using Safari? My chrome browser connects fine, but Safari spews all these 400 connect/websocket errors to the same aws/ec2 server

**Comment by HoucemEddine** [comment]
has anyone tried solving this avoiding the `hostname:port` , I have some micro services running on one server and we are implementing websocket stuff on one of them, these Micro Services already have proxyPass and proxyPassReverse configured to a load-balancer, though I'm still struggling with this conf for websockets 
example of my setup 
`ProxyPass /micro-service-a/ balancer://msa.dev.my.domain.com/`
`ProxyPassReverse /micro-service-a/ balancer://msa.dev.my.domain.com/`
`ProxyPass /micro-service-b/ balancer://msb.dev.my.domain.com/`
`ProxyPassReverse /micro-service-v/ balancer://msb.dev.my.domain.com/`
` ## I added these lines as an attempt 
  RewriteCond %{REQUEST_URI}  ^/micro-service-b            [NC]
  RewriteCond %{QUERY_STRING} transport=websocket    [NC]
  RewriteRule /(.*) ws://host:port/$1 [P,L]`

**Comment by Anishmourya** [comment]
ProxyPreserveHost On
   RequestHeader set X-Forwarded-Proto "http"
   ProxyPass /  http://127.0.0.1:3006/
   ProxyPassReverse /  http://127.0.0.1:3006/

RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:3006%{REQUEST_URI} [P]
working for me....................i am using port 3006 that connect to socket docker container.

**Comment by eduardoroseo** [comment]
> Hello @cellulosa
> Sorry for late return, this setup is working for me:
> The error page, SSL and rewrites(forcing ssl) are extra, you don't have to use them.
> Also, my apache on 2.4.10 and proxy_wstunnel has enabled.
> 
> ```
> <VirtualHost *:443>
>      ServerName mysite.com
>      ServerAlias www.mysite.com
> 
>      SSLEngine on
>      SSLProxyEngine On
>      ProxyRequests Off
> 
>      SSLCertificateFile /etc/apache2/ssl/mysite.com.crt
>      SSLCertificateKeyFile /etc/apache2/ssl/mysite.com.key
>      SSLCertificateChainFile /etc/apache2/ssl/ca.cer
> 
>      DocumentRoot /var/www/errorPages
> 
>      ErrorDocument 503 /503.html
>      ProxyPass /503.html !
> 
>      ProxyPass / http://localhost:3999/
>      ProxyPassReverse / http://localhost:3999/
> 
> 
> RewriteEngine on
> RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
> RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
> RewriteRule .* ws://localhost:3999%{REQUEST_URI} [P]
> 
> 
> </VirtualHost>
> ```

@fuatsengul YOU ARE THE BEST!!!
