### ISSUE TITLE
Assets is not defined in `meteor shell`

### ISSUE THREAD

**Issue by mltucker** [meteor/meteor#3343]
**_6 Upvotes**_ The new `meteor shell` is a fantastic feature that I've been eagerly awaiting since I started using meteor.  Thank you!

One error I noticed:

```
$ meteor shell
> console.log(Assets.getText("test.txt"));
ReferenceError: Assets is not defined
```

I'd be happy to jump on this if someone can point me in the right direction.

**Comment by MichaelErmer** [comment]
i second this

**Comment by chicagogrooves** [comment]
Just stumbled on this myself, +1 !

**Comment by dcsan** [comment]
I'm hitting this inside a client file in CS

in package.js

    api.add_files('data/cubes.json', "client", {isAsset: true})

then

```
  readData: ->
    str = Assets.getText("data/cubes.json")
    @rawData = JSON.parse(str)
```

Uncaught ReferenceError: Assets is not definedGameState.readData @ 

I'm sure i've used this pattern before... is Assets only available client side?

**Comment by Slava** [comment]
@dcsan Looks like your post is unrelated to the original issue. Assets are server-side only: http://docs.meteor.com/#/full/assets_getText

**Comment by dalgard** [comment]
+1 for Assets --> global assets.

**Comment by talha-asad** [comment]
+1 for global Assets in shell. Its bug actually.

**Comment by PEM--** [comment]
+1 : This is annoying when using the `meteor shell` :grin:

**Comment by Kostanos** [comment]
+1

**Comment by tomyo** [comment]
+1

**Comment by hexsprite** [comment]
+1

**Comment by dpankros** [comment]
+1

**Comment by mdorn** [comment]
:+1:

**Comment by yala** [comment]
+1

**Comment by adamczykjac** [comment]
Actually the workaround proposed by @Sanjo works like a charm, so easy! Thanks mate!

**Comment by cluxter** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Assets%20is%20not%20defined%20in%20%60meteor%20shell%60&body=Migrated%20from:%20meteor/meteor%233343) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
