### ISSUE TITLE
resetPassword call back not firing throwing error

### ISSUE THREAD

**Issue by sasikanth513** [meteor/meteor#3345]
![enroll](https://cloud.githubusercontent.com/assets/6153816/5521201/3d0bee2a-89c0-11e4-9923-9b22edd928e4.png)
I modified the enroll url 
```
Accounts.urls.enrollAccount = function (token) {
  return Meteor.absoluteUrl('enroll-account/' + token);
 };
```
In my iron-router my route is

```
this.route('enroll', {
		path: '/enroll-account/:token',
		template: 'enroll_page',
		onBeforeAction: function() {
			Meteor.logout();
			Session.set('_resetPasswordToken', this.params.token);
			s = this.subscribe('enrolledUser', this.params.token).wait();
		}
	}),
```

when I click on enroll account, I'm getting the resetpassword form and when I try to resetPassword it is throwing error

```
uncaught error extpected to find a document to change
```

my resetPassword code

```
Accounts.resetPassword(token, creds.password,function(error) {
						if (error) {
							toastr.error("Sorry we could not update your password. Please try again.");
							return false;
						}
						else{
							toastr.error("Logged In");
							Router.go('/');
						}
					});
```
This code is resetting the password, I'm able to login in the new session, but as normal behaviour it automatically needs to be login the user.

(the resetpassword token is deleted from the user record and I'm able to login) I supose this means this function is working but I'm unable to automatically login 

and in my console I'm getting the above error

```
uncaught error extpected to find a document to change
```

**Comment by sasikanth513** [comment]
Hi @estark37 , sorry for the late reply

I think the issues is because

in this code

```
this.route('enroll', {
        path: '/enroll-account/:token',
        template: 'enroll_page',
        onBeforeAction: function() {
            Meteor.logout();
            Session.set('_resetPasswordToken', this.params.token);
            s = this.subscribe('enrolledUser', this.params.token).wait();
        }
    })
```

I'm subscribing to the record using resetpasswordtoken,

```
Accounts.resetPassword(token, creds.password)
```
when I call resetPassword token the token will be deleted from client too and there are no subsciption records are on client.

Is that why that message appears?

when I subscribes to the user record using the id this problem is not existed.

```
this.route('enroll', {
        path: '/enroll-account/:token',
        template: 'enroll_page',
        onBeforeAction: function() {
            Meteor.logout();
            Session.set('_resetPasswordToken', this.params.token);
            s = this.subscribe('enrolledUser', this.params.token).wait();
        },
         onBeforeAction: function() {
           if(this.ready()){
            var userId=Meteor.users.findOne()._id;
             Meteor.subscribe("currentUserData",userId);
          }
        }
    })
```

**Comment by avital** [comment]
Hi. As @esark37 suggested above, we'd need a simple repro (that we can clone and run) to investigate this issue. Going to close this ticket but happy to re-open if we have a repro.
