### ISSUE TITLE
Clarify version constraint failures for local packages

### ISSUE THREAD

**Issue by paralin** [meteor/meteor#3351]
I have a fork of the bower package at `kidovate:bower@0.1.17`.

I try to add it to my project and get the following:

```
While selecting package versions:  
error: conflict: constraints on kidovate:bower cannot be satisfied.  
Constraints come from:  
<top level>
```

This makes no sense to me. What does `<top level>` mean? There's nothing below it. I was forced to add a constraint on `underscore` when trying to publish so I constrained it to `underscore@1.0.2` which matches the version of it in my project (and in Meteor). There are no other version constraints.

**Comment by glasser** [comment]
@dgreensp is currently rewriting the version solver and the new version should have better error messages.

**Comment by dgreensp** [comment]
There are better error messages on the `use-logic-solver` branch now, which will be released sometime in the coming weeks.  Without a cloneable reproduction, though, I can't verify whether this exact error message is better (e.g. old version of what in your local packages directory?).

**Comment by raquelhosein** [comment]
Hey all if this issue is remedied, please consider closing it :)

**Comment by hwillson** [comment]
Closing as this issue is no longer valid ([Version Solver](https://github.com/meteor/meteor/blob/devel/History.md#version-solver) launched in Meteor 1.1 and is a complete re-write of all package version resolution functionality). Thanks!
