### ISSUE TITLE
No documentation on using jQuery plugins

### ISSUE THREAD

**Issue by b2550** [meteor/meteor#3357]
I find myself using jQuery a lot but Meteor has absolutely no documentation, official or user created, about how to include jQuery plugins and control them through scripts.
For example, usually putting jQuery plugins in your page is as simple as calling the script using `<script src=""></script>` and then putting the parameters later in the page. In Meteor, I have no idea what you are suppose to do since Meteor has a specific way of loading and executing JS files and there is nothing telling you where to put things directory wise or file wise. I still don't know after weeks of searching for an answer and two StackOverflow questions. This needs to be addressed.

**Comment by avital** [comment]
We can have a discussion about integrating with specific jQuery plugins, but this ticket doesn't seem to have any specific details, so I'll close it.
