### ISSUE TITLE
"extend" for Built-In Handlebars Helpers

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#3358]
[add any attrs for template context]
```html
<div class="entry">
  {{#extend v1="1" v2="2"}}
    {{v1}} {{v2}}
  {{/extend}}
</div>
```

I've been using it for Meteor:

https://github.com/comerc/meteor-autoform-bs-more/blob/master/autoform-bs-more.js#L1-L5
https://github.com/comerc/meteor-autoform-bs-more/blob/master/autoform-bs-more.html#L16-L18

**Comment by stubailo** [comment]
We now have `#let`, which does basically this.
