### ISSUE TITLE
Problem with reusing subscriptions [repro included]

### ISSUE THREAD

**Issue by MaximDubrovin** [meteor/meteor#3361]
http://ext-excl-sub.meteor.com
https://github.com/MaximDubrovin/ext-excl-sub

Something in Meteor doesn't extend already received documents with new fields from later subscriptions.

Possible explanations

1 Meteor treats fields exclusion rule as a strict rule and if something was excluded in earlier subscription then while this subscription still alive no other subscription can get that excluded data.

If so then try to do step 2 or 3 and then step 1. If theory above is valid then subscription on step 1 should remove «title.unpublished» field and add only «title.published» field. But no one of that happened.

2 It seems that Meteor ignores later subscriptions that includes/excludes fields of the already received document.

Meteor do it on purpose which is unknown.

Or Meteor simply doesn't have mechanism to compare which fields of the already received documents should be extended/excluded after new subscription.

So we have earlier subscription data in favor of later subscription data.

**Comment by ankitv89** [comment]
> «Workaround for Meteor DDP limitation and client part of Meteor.subscribe() nuance if you want to subscribe for more nested fields of already received documents»
> 
> https://medium.com/@MaxDubrovin/workaround-for-meteor-limitations-if-you-want-to-sub-for-more-nested-fields-of-already-received-docs-eb3fdbfe4e07

This link is not available? Any alternative to have a look at the solution?
