### ISSUE TITLE
Meteor build of a simple mobile app 

### ISSUE THREAD

**Issue by chansdad** [meteor/meteor#3364]
When creating a simple mobile app app built is not being installed on android device

Steps followed 
meteor create testapp
cd testapp
meteor add-platform android
meteor build ../testbuildapp --server host:port

apk is generated in ant-build and when it is being installed on the device , permissions screen appears and after clicking next , app tries to get installed and is not being installed.

**Comment by mg91** [comment]
Hi,
This video can be very helpful. 
Check this: https://youtu.be/lg6G52-guBw
