### ISSUE TITLE
Can't use non-latin non-alphanumeric symbols in mobile app name

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#3367]
I have a meteor project called `company-project` when the ios app name is `company-project`, if I change it to `Company Project` with this:

    App.info({
       name: 'Company Project',
    });

meteor spawns a xcode project with no meteor file (only cordova lib)

I use the latest meteor 1.0.2.1

**Comment by Slava** [comment]
I believe this has been fixed on devel with the latest Cordova update to 5.0.

Here are my screenshots of my tests (I used the string "Мои задачи" for the todos app):
![screen shot 2015-05-21 at 5 45 10 pm](https://cloud.githubusercontent.com/assets/2608446/7761938/796e8e94-ffe1-11e4-9a6c-0f66194bd9c8.png)
![screen shot 2015-05-21 at 5 46 43 pm](https://cloud.githubusercontent.com/assets/2608446/7761939/79701570-ffe1-11e4-86b9-8ac17836626f.png)
