### ISSUE TITLE
<input type="file"> not working in the app

### ISSUE THREAD

**Issue by furoresu** [meteor/meteor#3368]
I've been developing a Meteor + Famo.us for some time, I achieved to create a functional APK on my Android Tablet, but for some reason I cannot pick any file, the box dialog doesn't even open. I've tried this on other mobile devices and it worked but not on the tablet.
What could this be? 
Thank you!

PD: My Tablet android version is 4.4.2

**Comment by glasser** [comment]
Agreed, please see https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor for guidance on filing useful bug reports.
