### ISSUE TITLE
How to sync template.autorun with DOM update?

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#3372]
If I write this:

```
Template.my.rendered = function () {
    this.autorun(function () {
        var data = Template.currentData();
    });
}
```

...when my autorun callback will be called — before or after DOM update? Or is it just async?

Actually, I’m trying to find the best place to initialize and reinitialize custom-scrolling-module. I need to react on DOM changes. I found that way to depend on data context not the fine one, because it no guarantees the fresh state of the DOM.

It’s even harder when you have child templates...

How do you solve such kind of problems?
# 

P. S. Maybe I’m wrong but I’m still missing **Template.my._updated_** callback that will be called when instance of a template is updated (including child instances).

**Comment by Alveoli** [comment]
Haha, afterFlush works like a dream thanks

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#176 - closing - thanks!
