### ISSUE TITLE
stopPropagation() events causes to helper execute many times vs twice.

### ISSUE THREAD

**Issue by voidale** [meteor/meteor#3374]
I'm not sure if this is an expected behavior, But maybe it's a problem

```
Template.sidebar.events({
  'click .sidebar-nav li': function(event){
    event.stopPropagation(); <-- problem with it removing it seems to work fine.
    var menuItem = event.currentTarget;
    $(menuItem).toggleClass('active').children('ul').collapse('toggle');
    $(menuItem).siblings().removeClass('active').children('ul.in').collapse('hide');
  }
});

UI.registerHelper('connectedChannels', function(){ <--tested with Template.helper as well doesn't matter
    console.log('wtf'); <-- using this to test "x" it was ran
    var user = Meteor.user();
    if (user && user.services) {
      var services = _.pick(user.services, 'one', 'two');
      services = _.map(services, function(val,key){ return {name: key.charAt(0).toUpperCase() + key.substring(1).toLowerCase()};});
      return services;
    }
  });

  <ul class="submenu collapse {{isActivePath regex='channels' className='in'}}">
    {{#each connectedChannels}} 
      {{> submenuChannel}} 
    {{/each}}
      .....
```

Without `event.stopPropagation();` I get 2 `wtf` on page load. After that if I click submenu I don't get any more `wtf` if I use `event.stopPropagation();`  I get 2 `wtf` and then every submenu click it will show 1 + 2. I only tried using stoppropagtion to avoid submenu clicks, so I only need to target the main menu li some how without children

**Comment by voidale** [comment]
Any update?

**Comment by voidale** [comment]
@stubailo I have created you step by step how to recreate this problem which confirms it's a problem/bug can you please check this?

**Comment by stubailo** [comment]
Right, good point - I will try to take a look soon.

**Comment by avital** [comment]
I'd love to get to the bottom of your problem, but honestly your reproduction is too complicated for us to easily try out. For example, I would need to configure facebook login on the meteorpad domain where I'm running the app. Also, there are lots of extra code in your repro that's unrelated to the issue, such as routes and elaborate HTML markup. All of these make it difficult for us to effectively understand what's going on.

Please create a /minimal/ reproduction of your issue and we'll be happy to take a look.  This reproduction should not require logging in. And it's best if it's a simple git repository that we can clone and run.

**Comment by hwillson** [comment]
Since this issue is for a much older version of Blaze, doesn't have a valid reproduction, hasn't been reported by others, and hasn't been updated in almost 2 years, I believe it can be closed. If this problem happens again a new issue can be opened in the [Blaze repo](http://github.com/meteor/blaze/issues).

**Comment by abernix** [comment]
Agree.  Thanks, @hwillson.  And regardless, thanks for reporting this originally, @voidale.
