### ISSUE TITLE
meteor publish will download build and install tool multiple times

### ISSUE THREAD

**Issue by silkentrance** [meteor/meteor#3381]
Given a meteor package build from an existing source, for example [vibejs/vibejs-namespaces](vibejs/vibejs-namespaces), which uses `grunt package-meteor` to build a meteor package ready for publishing. Of course, using `grunt clean` would clean said build directory.

When running `meteor publish` in the `build/meteor/vibejs:namespaces` directory will cause meteor every time that it is invoked to download what it calls "build" and then reinstall the meteor tool.

In order to prevent meteor from downloading and reinstalling, one would have to create a .versions file in the above mentioned directory with a proper set of package version references.

Would it be too much to ask of you that the meteor tool would simply check for updates, and, if none are available as per ~/.meteor/..., it would then simple create the required .versions file in order for it not to download and reinstall the same packages over and over again?

Heck, a build directory is meant to be cleaned :smile:

**Comment by glasser** [comment]
This sounds like an issue with @dandv 's https://github.com/MeteorPackaging/grunt-meteor project.  The `MeteorPackaging` Github org is slightly misleading; it's a pretty cool project but not officially part of Meteor.  It looks like @dandv et al are suggesting that you build a second grunt-based build process on top of Meteor's built-in build process; that may or may not be a good idea, but I don't really know how to debug issues with such a thing.

It sounds like you're saying that meteor downloads a tool even if it already exists, which is surprising. But I'd need a clear reproduction as described in https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor to debug.  Ideally this would only use meteor itself and not extra software like grunt.

**Comment by silkentrance** [comment]
While you are correct in that this is not a very good bug report :smile:, you somehow misunderstood me.

Above is merely prose for saying

1. Clone vibejs-namespace
2. cd to project root and run npm install
3. run grunt package-meteor
4. cd to build/meteor/vibejs:namespaces
5. run meteor publish without actually publishing it
6.  cd back to project root
7. run grun clean
8. rerun steps 3 - 5 and see meteor downloading the command once again unless you create the versions file manually, in which case it will not download the package all over again

**Comment by glasser** [comment]
At which step do you see "downloading the command", and what do you mean by that? I don't see any difference between the first and second execution of publish.

**Comment by silkentrance** [comment]
Just rerun my steps and look at that, it is no longer downloading the tool, which is what I meant with 'command'. Must have been a very late night then... Consider this a layer 8 failure.

**Comment by glasser** [comment]
Great to hear!
