### ISSUE TITLE
Force-SSL Package breaks Cordova Development

### ISSUE THREAD

**Issue by jordangarside** [meteor/meteor#3382]
I get this error:

    XMLHttpRequest cannot load http://192.168.1.11:3000/sockjs/info?cb=40wze3lvww. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://meteor.local' is therefore not allowed access.

When I have the Force-SSL package installed on local development running `meteor run android-device`. It results in the app installing to the android phone, but none of the connections working so no data is passed.

**Comment by glasser** [comment]
Is the point here that force-ssl should override the default mobile-server for cordova meteor run?  That does sound reasonable.

**Comment by slickdev** [comment]
+1

**Comment by teknologist** [comment]
In my case, not only production. If I have force-ssl package Cordova builds simply don't work. You don't even get the Google Login or FB login pages when using meteor accounts and social logins.

**Comment by lorensr** [comment]
Here are the periodic errors I get in Xcode when doing `run ios-device` with `force-ssl` installed:

![image](https://cloud.githubusercontent.com/assets/251288/6910289/f1d89244-d705-11e4-870b-d31037e655f8.png)

Adding `App.accessRule('https://localhost');` to `mobile-config.js` removes the error, but it looks like the app still is unable to make the DDP connection.

I imagine using my Mac's private IP `--mobile-server=https://192.168.1.105:3000` would work if my Mac had https set up, but it doesn't, and I believe that's the default state (loading https://localhost:3000 in browser gives ERR_CONNECTION_CLOSED).

My current solution is not ideal – removing the package during dev and adding it for prod.

**Comment by RobertLowe** [comment]
I ran into this as well, adding a `App.accessRule` does resolve this issue; maybe we should auto-magically add the `accessRule` while in a development environment? 

@glasser OT: it would be nice if packages has `groups` like in [bundler](http://bundler.io/v1.9/groups.html) this way `force-ssl` could only be applied to production for instance.

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
