### ISSUE TITLE
meteor install android sdk problem (Android emulator acceleration is not installed)

### ISSUE THREAD

**Issue by quickj** [meteor/meteor#3383]
When i install meteor android sdk with "meteor install-sdk android" command on my ubuntu. It occured an error that "Android emulator acceleration is not installed". I have no idea about this issue. Anybody met this problem before? I have installed jdk7. can you help me to solve this issue.Thanks a lot .

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
