### ISSUE TITLE
Do not crash on unavailable font-face

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3386]
**If** I `meteor add nooitaf:semantic-ui`,
And `googleapis.com` is unavailable (can be mimicked by disconnecting from the Internet),
**Then** my application does not receive any data through subscriptions,
And the console logs the error `Failed to load resource: A server with the specified hostname could not be found (fonts.googleapis.com)`,
**While** I expect this failure to lead only to using a fallback font.

**Comment by MattiSG** [comment]
> that error is pretty common in web dev and doesn't block the rest of the javascript from executing

Absolutely, which is why I thought Meteor perhaps did some optimistic wrapping around requests.

I tried to isolate the part of my app that requested the fonts, but I don't seem to be able to reproduce this anymore. I will close this issue and re-open it in case I get symptoms again.

**Comment by glasser** [comment]
Thanks @adnissen !
