### ISSUE TITLE
Ability to isolate assets/packages on page

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#3389]
As a package author, we need the ability to control which assets are served/used. 

For instance, when building an admin panel; one may choose to use bootstrap for the panel while the host application may have chosen to use polymer/paper-elements or foundation. And the stylesheets conflict as well as the javascript may conflict.

The current solution is quite hacky, for instance in [houston](https://github.com/gterrono/houston), it removes all stylesheets and injects it's own as a template: 

* https://github.com/gterrono/houston/blob/master/client/master_layout.html#L3-L8
* https://github.com/gterrono/houston/blob/master/client/router.coffee#L104

It also doesn't solve for possible javascript conflicts.

It would be useful if: packages could isolate which assets/packages are served/used. Maybe it could be configured in the `<head>`.

Maybe something like:

    <head>
      {{#packages 'bootstrap', 'underscore'}}
    </head>

If `#packages` isn't used on the page Meteor can load all packages on the page. 

Any thoughts on working with this problem? @AlexeyMK @gterrono ?

**Comment by glasser** [comment]
Thanks for the suggestion.  This is a major project that is being tracked on the [roadmap](https://trello.com/c/24s6vyxo/55-incremental-loading).
