### ISSUE TITLE
ReactiveVar.set() should return true on successful change

### ISSUE THREAD

**Issue by jonjamz** [meteor/meteor#3392]
Working on `templates:forms` package, I have my own logic for determining whether a value being set in a form element is different from the existing value. The package supports a pre-validation hook that allows for a transform into any data structure, so this is necessary.

``` coffeescript
unless _.isEqual(self.value.get(), value)
  self.value.set(value)
  self.changed.set(true)
```

This works fine, but it would be even better if I could do:

``` coffeescript
if self.value.set(value)
  self.changed.set(true)
```

And then I could use the ReactiveVar's `equalsFunc` to run `_.isEqual` and skip the default comparison.

As it is now, I could do something like this:

``` coffeescript
self.autorun ->
  newVal = self.value.get()
  self.changed.set(true)
```

But it seems a little heavy to have to run a whole reactive computation when I just need to change one value from one place.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

If we think this is compelling, probably ReactiveDict and Session should have a similar change.

**Comment by jonjamz** [comment]
Thanks for linking me to the guidelines--they make a lot of sense.

I've thought about this proposal a little bit more. If returning `true` is too much of a stretch, it might be good to just return the value that was successfully set, since that's what JS does.

**Comment by hwillson** [comment]
Instead of returning `true` if set, or the value that was set, what about falling more in-line with how JS `Map`'s and `Set`'s work by returning the `ReactiveVar` object itself? This would allow function chaining, so you could re-write your check like:

```js
self.changed.set(self.value.set(value).get() === value);
```

The above being said, this feature request hasn't gained much traction in a couple of years, but we'll leave it open for a bit longer (if anyone feels strongly about getting this in-place, please show your support and add your comments). Thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=ReactiveVar.set()%20should%20return%20true%20on%20successful%20change&body=Migrated%20from:%20meteor/meteor%233392) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
