### ISSUE TITLE
Meteor Docs - Missing options in "Match Patterns" for check function

### ISSUE THREAD

**Issue by Rathlan** [meteor/meteor#3394]
In the list of valid match patterns (http://docs.meteor.com/#/full/matchpatterns), it lists:
>String, Number, Boolean, undefined, null
>>Matches a primitive of the given type.

It can lead people to miss the fact that you can use *Date* as one of the types (as per the example for the check method (http://docs.meteor.com/#/full/check) ).

As a new Meteor developer, I assumed the list of Match Patterns was comprehensive, when it wasn't.

The documentation should do one of the following:
* Explain that there are other types, and how to find them
* List all the types that can be matched.

**Comment by avital** [comment]
Does the following snippet from the docs not clarify that Date is one of the acceptable arguments to `check`?

> Any constructor function (eg, Date)
> Matches any element that is an instance of that type.

**Comment by mbrookes** [comment]
@Rathlan, @avital:

> Does the following snippet from the docs not clarify that Date is one of the acceptable arguments to check?

It does (if you read the full pattern section), but not what the rest of the "out-of-the-box" patterns are. I have no idea what's available to match as a "constructor function", vs the built in patterns (`String, Number, Boolean, undefined, null`) vs the oddly named `Match.Integer` (why isn't that just `Integer` for example?

On a related note, is there a difference between `check()` and `Match.test()` if so it's not obvious (to me) from the docs...

I believe this issue should be reopened.

**Comment by Rathlan** [comment]
100% with you there mbrookes.   It's not obvious unless you read a whole lot of context around it, but I wasn't going to argue the point if it was just me who felt that way.  Hopefully someone will reopen the ticket and resolve it so that it's easier for future developers to understand.
