### ISSUE TITLE
Uncaught Error: INVALID_STATE_ERR ddp.js

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#3396]
a blank app start with these

autopublish
coffeescript
cordova:de.appplant.cordova.plugin.background-mode
cordova:org.chromium.power
cordova:org.stereolux.cordova.serial                
insecure
meteor-platform
mquandalle:jade
mquandalle:stylus

oppo find x909 / 3rd rom color os / android 4.2.2
samsung gt i9100g / 3rd rom  android 4.1.2

	=> App running at: http://localhost:3000/
	I20141231-14:03:16.528(8) (android:http://meteor.local/packages/ddp.js:1156) Uncaught Error: INVALID_STATE_ERR
	I20141231-14:03:21.583(8) (android:http://meteor.local/packages/ddp.js:1156) Uncaught Error: INVALID_STATE_ERR
	I20141231-14:03:30.146(8) (android:http://meteor.local/packages/meteor.js:913) Exception from Tracker afterFlush function: MutationObserver is not defined
	I20141231-14:03:30.147(8)? ReferenceError: MutationObserver is not defined
	I20141231-14:03:30.147(8)? at c.f.observeInserted (http://meteor.local/packages/peernohell_c3.js?a6b270f172e239895b37c71200b99033d79722ad:31:19641)
	I20141231-14:03:30.147(8)? at c.f.initWithData (http://meteor.local/packages/peernohell_c3.js?a6b270f172e239895b37c71200b99033d79722ad:31:7497)
	I20141231-14:03:30.148(8)? at c.f.init (http://meteor.local/packages/peernohell_c3.js?a6b270f172e239895b37c71200b99033d79722ad:31:4865)
	I20141231-14:03:30.148(8)? at new b (http://meteor.local/packages/peernohell_c3.js?a6b270f172e239895b37c71200b99033d79722ad:31:91)
	I20141231-14:03:30.148(8)? at Object.g.generate (http://meteor.local/packages/peernohell_c3.js?a6b270f172e239895b37c71200b99033d79722ad:31:4391)
	I20141231-14:03:30.149(8)? at Template.dashboard.rendered (http://meteor.local/client/templates/dashboard/dashboard.coffee.js?28483147625e947f3176da4205450d5a93ca54b7:30:21)
	I20141231-14:03:30.149(8)? at null.<anonymous> (http://meteor.local/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3008:21)
	I20141231-14:03:30.150(8)? at http://meteor.local/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1733:14
	I20141231-14:03:30.150(8)? at Object.Blaze._withCurrentView (http://meteor.local/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
	I20141231-14:03:30.151(8)? at http://meteor.local/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1732:15

**Comment by glasser** [comment]
This looks like an issue with using https://github.com/peernohell/meteor-c3.js/ .  Can you report it at their issue tracker?

**Comment by crapthings** [comment]
I've created a new project and tested.
This issue still exist on some mobile devices with android 4.0.x, 4.2.2, it will stuck and show white screen after launch screen then recover to normal app view with about 2min.

**Comment by glasser** [comment]
I'm sorry, I think you'll need to provide a more specific reproduction to get help.

**Comment by crapthings** [comment]
Found no problem after update android 4.2.2 to 4.4.2.
