### ISSUE TITLE
It seems that Meteor can't re-version the images from the project.

### ISSUE THREAD

**Issue by leonli** [meteor/meteor#3399]
Compare to Rails world, the asset-pipeline plugin could be able to re-version the image from both HTML and CSS background, but after I tried Meteor, I found that it's not able to do this.
I even searched the Atmosphere, no any related package was found. Anyone knows that how could I deal with the image re-versionning? Thanks!

![screen shot 2014-12-31 at 5 58 00 pm](https://cloud.githubusercontent.com/assets/345188/5586921/de973f12-9116-11e4-9b72-cdf57d7790fa.png)

**Comment by glasser** [comment]
I think what you're talking about is part of #773.
