### ISSUE TITLE
support new template languages with html files

### ISSUE THREAD

**Issue by netanelgilad** [meteor/meteor#3400]
Hi guys,
I was looking for a way to add new templates to my app that are not going to get compiled using Blaze.
So I looked at the templating package and how the jade package does it, and I can see that the only way to not get compiled by Blaze is to use a different file suffix other than html.
But I was thinking that adding a simple `lang` option on the `<template>` definition would allow other package to handle those templates however they want without clashing with Blaze, and even mixing templates on the same app.
Blaze could still stay the default option for backwards compatibility.

Several ways I could see this implemented. What do you think?

**Comment by mquandalle** [comment]
You can use sub-extensions, like `.something.html`. In which template language are you interested in?

**Comment by netanelgilad** [comment]
I'm looking for a solution for angular templates.
And the current solution we are implementing at angular-meteor is a sub-extension. 
About that, using `.sub.html` would still get meteor to compile it as if it were a blaze template nope? cause the extension used in the templating package is `html`.
But any way, I think the idea that meteor uses with having the tags `<head>` `<body>` and `<template>` in any file you want and even several in the same file is pretty cool.
Adding a `lang` attribute to the tags seems complement the current use of this tags.
My idea is that the templating package would scan the html files like it does today, but instead of having it  compile it with blaze right away all it would do it save the raw templates in the Template object.
Then other packages like that Blaze package, the jade one and our angular-meteor could use that Template object in any way we want.
Makes sense to anyone but me?

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by abernix** [comment]
This can be done (and has been possible for a while now) using the [Build Plugins API](https://github.com/meteor/meteor/wiki/Build-Plugins-API).  Closing.
