### ISSUE TITLE
is it possible to add fields to  'removed callback' for cursor.observeChanges?

### ISSUE THREAD

**Issue by shoyer2010** [meteor/meteor#3401]
some cases,  when a document removed from the collection(A), may another collection(B) need some info in the removed document to do some extra operations or logic. but so far, the 'removed callback'  only provide an 'id' in its callback.

**Comment by mquandalle** [comment]
You should take a look at the [collection-hooks](https://github.com/matb33/meteor-collection-hooks/) package. You are probably interested in the `.before.remove` hook.

**Comment by shoyer2010** [comment]
@mquandalle , yes , great, that is what i need.  thank you very much.

**Comment by glasser** [comment]
Thanks @mquandalle!
