### ISSUE TITLE
Placing test files in the same directory

### ISSUE THREAD

**Issue by dmitriz** [meteor/meteor#3403]
Just read the "Structuring your app" page suggesting to put all test into a dedicated directory.
However, a lot has been written about this being a bad practice.
It is much cleaner to name test files like "myfile.test.js" (or "myfile.spec.js") and put them next to "myfile.js". Is that supported by Meteor?

**Comment by Sanjo** [comment]
I think you can have tests directories anywhere and they will be ignored by Meteor. However Velocity currently doesn't support it. But that's something we can support in the near future. Please open a feature request here: https://github.com/meteor-velocity/velocity/issues if you use a Velocity powered testing solution.

When you structure your code in packages you can place your tests where you want. You must load the tests in the package.js explicitly anyways.

**Comment by dmitriz** [comment]
If I place my test file next to my source, how will Meteor know it is to be ignored? Is it documented anywhere?

PS. I don't use velocity, use `gulp` instead, so I can specify which files to be ignored right in the gulp code.

**Comment by Sanjo** [comment]
No, Meteor does not support ignoring files by file name convention. What I meant is that you can have modules that have their own tests folder.

If you want full control you should use smart packages to structure your app.

**Comment by glasser** [comment]
You can do this in packages but not in apps.  Getting rid of the dichotomy between what packages and apps support is part of the upcoming work tracked on our roadmap at https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order
