### ISSUE TITLE
accounts-twitter - error message

### ISSUE THREAD

**Issue by lpatmo** [meteor/meteor#3405]
Login using twitter seemed to work initially when I first set it up, but then new users seemed to have trouble creating accounts, and then I got this message when I clicked to register using twitter as a new user:
````
Whoa there!
The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.
````

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
