### ISSUE TITLE
Add a 'cordova' directory

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#3409]
**_24 Upvotes**_ At the moment, we have `Meteor.isClient`, `Meteor.isServer` and `Meteor.isCordova` to specify whether the code should run on the client, server or Cordova mobile environment respectively. But we only have special directories `client` and `server` (as well as their corresponding `public` and `private`). It may be nice to have a `cordova` directory, for code which should only run on mobile, to save developers typing `if (Meteor.isCordova)` many times.

**Comment by shirk3y** [comment]
+1

**Comment by davidyaha** [comment]
+1
This will also could potentially make smaller mobile apps that will live alongside a full blown web app.

**Comment by chetmurphy** [comment]
+1. Consider letting devs add their own conditional folders. For example, I would like to have different code for development and production configured via the command line or settings.

**Comment by servermeta** [comment]
I think you can already do it, by extending the meteor class or by creating your own global helper.

Meteor.isProduction check something of your choice, by a method defined by you, and reacts.

**Comment by chetmurphy** [comment]
How would you use Meteor.isProduction() to conditionally load source code? For example suppose I have a file assert.js for development and another file assert.js for production.

I also don't see how Meteor.isProduction() would work for me since I have my own server and isProduction is defined as:

 isProduction: function () {
    return getUniverse() === "www.meteor.com";
  },

**Comment by servermeta** [comment]
1) You can conditionally load source code in many ways. Here's an example

http://empire5.com/development/meteor-using-iron-router-to-conditionally-load-javascript-libraries/

there are packages which are built specifically for this

2) I dont know if you refer to the altimeter package. You can define isProduction as you want, unless you have installed altimeter. You could simply check a config file

**Comment by chetmurphy** [comment]
Hmm... It does not look like this works for all common code (in lib folder) that is running on the client. I used $.getScript to load the code (also in the lib folder), but assertEqual (my test function) was still undefined when it was evaluated. This looks like it may be a load order problem (not to mention that this seems like a hack). 

Details: I put the $.getScript call in lib/config/assert.js so it should have been evaluated first. The test call to assertEqual was in lib/schemas/profile.js. Both were called at the global level and both $.getScript and assertEqual were guarded by Meteor.isClient. 

//lib/config/assert.js
if (Meteor.isClient) {
    $.getScript("debug/assert.js")
        .done(function (script, textStatus) {
            console.log('debug/assert.js loaded');
        });
}

//lib/schemas/profile.js
if (Meteor.isClient) {
    assertEqual(1, -1, 'simple test of assertEqual');
}

Based on the console.log, assertEqual is evaluated before $.getScript is evaluated so assertEqual is undefined.

After $.getScript is called assertEqual is correctly defined. I did verify that assertEqual is available in functions that are not evaluated at the global level.

Note that there are at least four cases along with four different versions of the code to consider;

1) Common code for server in debug
2) Common code for client in debug
3) Common code for server in production
4) Common code for client in production

If it works for the common code then it should work for the client and server code.

**Comment by d4nyll** [comment]
Hi @chetmurphy and @servermeta, this issue is specifically about adding a `cordova` directory as part of the special directories, and not so much allowing users to create their own special directories. However, it could potentially be a good feature. I have thus created a new issue (referenced above). Please continue (or move) your discussions there. Thank you and have a good day!

**Comment by shirk3y** [comment]
There is little inconsistency. Cordova app would use both `cordova` and `client` directories, and browser app only `client` directory. To allow user to separate code only for browser, a `browser` directory should be introduced too. Does it make sense?

**Comment by yauh** [comment]
@shirk3y I agree. Eventually there should be one folder per platform that corresponds with each `Meteor.isServer()`, `Meteor.isBrowser()` (requires a rename from existing `client` to remove the ambiguity), and `Meteor.isCordova()`.

To me it looks like the client-server paradigm is too limited to cater to the needs of a variety of platforms.

**Comment by dude-awesome** [comment]
+1

**Comment by joshua1** [comment]
+1

**Comment by iggyvanlith** [comment]
+1

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

We should definitely have something like this, but right now it is hard to decide what should happen with client/browser/cordova folders, and we don't want to have an endless proliferation of new folder names. I think this calls for a more general solution around folder structure.

**Comment by yauh** [comment]
Agreed, an endless number of folders will not help anyone.
To me it seems that each `Meteor.is<Platform>` should have an associated folder. As such you would need to get rid of the generic `client` as well as `cordova` (transition it out to translate to `web.browser`, `ios`, and `android`) and end up with each of the platforms. That way you have better transparency.
To me `client` and `server` fell like legacy code from when only two platforms existed.

Certainly there will be the need for grouping. Where to put things that should go to all clients (browser and cordova) or how to even group cordova platforms. That I have no answer for, but I count on the swarm intelligence of the Meteor platform :-)

**Comment by dude-awesome** [comment]
platform/ios/ #just iOS - apps
platform/android/ #just Android - apps
platform/browser/ #all browsers - websites
platform/mobile/ #all mobile - apps


I prefer a global platform folder instead of using foldernames like is<Platform>

**Comment by dude-awesome** [comment]
platform/ios/ #just iOS - apps
platform/android/ #just Android - apps
platform/browser/ #all browsers - websites
platform/mobile/ #all mobile - apps


I prefer a global platform folder instead of using foldernames like isPlatform

**Comment by rjerrems** [comment]
As a workaround for this we have created a local package to add Cordova specific scss and javascript with the following syntax in our package.js
```javascript
// Add Cordova styling
  api.addFiles([
    'client/import_cordova.scss'
    ], ['web.cordova']);
```

**Comment by dotnetwise** [comment]
+1 This is mandatory for us as we do have different html entry point when coming from cordova or from website

**Comment by rjerrems** [comment]
I have written a blog post here about how you can use a local package in Meteor to separate your Cordova code and styling for anybody who is interested. https://thesauceco.de/blog/Add-Cordova-specific-styling-to-your-Meteor-project/

**Comment by meggarr** [comment]
+1

This is important to clearly specify client hierarchy if multiple types of client are supported. Probably *client* is for comment codes across all client types, e.g. browser/cordova, while *browser* or *cordova* is for its named client only.

**Comment by piotrraczynski** [comment]
+1

**Comment by AhmadEl-Banna** [comment]
+1

**Comment by joaopiopedreira** [comment]
+1

**Comment by eziante** [comment]
+1

**Comment by cleor41** [comment]
I think more specific client folders is the way to go in the future. But in the meantime, would it suffice to use packages? For example, create a package named web, and a package named mobile. Then use the "api.*" methods to conditionally include the package foregoing the entire client directory altogether.

**Comment by TheCCode** [comment]
+1

**Comment by adriangordon1231** [comment]
+1

**Comment by samnarain** [comment]
+1

**Comment by MaxShv** [comment]
+!

**Comment by santatic** [comment]
+1

**Comment by almasakchabayev** [comment]
+1

**Comment by triniwiz** [comment]
+1

**Comment by talha-asad** [comment]
+1

**Comment by JoeyAndres** [comment]
+1

**Comment by andrea689** [comment]
+1

**Comment by ciclopes** [comment]
+1

**Comment by AmanGupta-2210** [comment]
+1

**Comment by vonrussel** [comment]
+1

**Comment by vincentracine** [comment]
+1

**Comment by gg2001** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20'cordova'%20directory&body=Migrated%20from:%20meteor/meteor%233409) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
