### ISSUE TITLE
meteor support for window  ?

### ISSUE THREAD

**Issue by R008-Coder** [meteor/meteor#3415]
when meteor completely support for window ? i hope it support for window soon , anyone know ?

**Comment by avital** [comment]
Take a look at https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by avital** [comment]
This is one of the frontburner projects we're currently working on -- doesn't seem like there's much to do with a GitHub issue here, so closing. Hope you have a great experience using our Windows preview, and if you hit any problems definitely file issues on https://github.com/meteor/windows-preview/issues

**Comment by R008-Coder** [comment]
thank you for info :)
