### ISSUE TITLE
Boolean literal 'false' renders as empty string whereas 'true' renders as "true"

### ISSUE THREAD

**Issue by ggutoski** [meteor/meteor#3417]
The default behaviour in Meteor 1.0.2.1 for rendering boolean data in a template renders literal 'false' as the empty string whereas 'true' renders as "true".  Presumably, 'false' should render as "false" instead of the empty string.

Simple Meteor app to reproduce this behaviour:
```
git clone https://github.com/ggutoski/meteor-issue-boolean-false.git
cd meteor-issue-boolean-false/
meteor
```
Observe column two, the "Flag" column: the first row has "true", the second has the empty string.

Cropped screenshot:
![Screenshot: 'false' renders as the empty string](https://raw.githubusercontent.com/ggutoski/meteor-issue-boolean-false/master/screenshot.png)

This is my first contribution of any kind to Meteor.

**Comment by avital** [comment]
This is as designed --  https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#double-braced-tags

Happy to hear strong arguments for changing this behavior, but it seems fine to me.

**Comment by ggutoski** [comment]
The example above seems like a pretty strong argument to me.  Are there any good arguments for the status quo?  Thanks for the pointer.

**Comment by glasser** [comment]
We should probably change `true` to display as [䷼](http://www.fileformat.info/info/unicode/char/4dfc/index.htm).

**Comment by glasser** [comment]
(Honestly, I don't think that "displaying the words true and false in your webpage" tends to lead to a great app.  Most contexts, you'll use `#if` to display one thing or the other.  Certainly, people don't like when `undefined` and `null` randomly show up on their site.)

**Comment by carlevans719** [comment]
I agree that this shouldn't be default functionality, however there are times when this can be helpful. I use the following in my global template helpers file:
```Template.registerHelper('literalBool', function(bool) {
	var boolAsString = (typeof bool != "boolean") ? ""' : String (bool === true);
	return boolAsString;
}```
