### ISSUE TITLE
Set Strict-Transport-Security header in force-ssl package

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#342]
@pde suggested that the force-ssl package sets the Strict-Transport-Security header: https://secure.wikimedia.org/wikipedia/en/wiki/Strict_Transport_Security

This tells conforming browsers to always use SSL in the future to connect to the site.

The downside to this is that if a site later changes its mind about using force-ssl, browsers that have already hit the site will continue to force SSL until the header's TTL is reached. So we would have to choose the TTL carefully, and perhaps think of a better way to handle this case.

**Comment by hwillson** [comment]
There hasn't been any activity/interest in this issue for many years, and using the `force-ssl` package is no longer recommended (unless absolutely necessary - see the `force-ssl` [README](https://github.com/meteor/meteor/tree/a9cd336ed551ce70d1862c53cc84ce62746ec8b6/packages/force-ssl) for details). Given this, as part of the on-going old issue cleanup process, I'll close this off. Thanks!
