### ISSUE TITLE
Can't use chinese character as app name in mobile-config.js.

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#3421]
Building will fail if app.name is set to chinese.

-compile:
[javac] Compiling 39 source files to /Users/zhanghong/hademo/.meteor/local/cordova-build/platforms/android/ant-build/classes
[javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
[javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
[javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[javac] /Users/zhanghong/hademo/.meteor/local/cordova-build/platforms/android/src/com/id10b2xee16cjqoztuh3i/.java:25: error: <identifier> expected
[javac] public class  extends CordovaActivity
[javac]             ^
[javac] 1 error
[javac] 3 warnings

**Comment by mykhael** [comment]
@crapthings I reckon that meteor doesn't process correctly since it really hasn't been much translated or has worked around it in the pass, I'd recommend using a normal character for app names.

**Comment by crapthings** [comment]
can i change app name in xml file ?

**Comment by mykhael** [comment]
@crapthings this is kinda seems like issue #2578, read this and see if this may resolve your issue

**Comment by ianserlin** [comment]
Using mobile-config.js, iOS build fails for me if the App.info `name` key has a space in it also.

e.g.

```
App.info({
	id: 'com.company.app',
	name: 'Name With Spaces',
	version: "1.0.0"
});
```

Failure message is:
```
fatal error: file '/app-path/.meteor/local/cordova-build/platforms/ios/Name With Spaces/Name With Spaces-Prefix.pch' has been modified since the precompiled
header '/var/folders/bh/96_w0c8n6gl43402j6cs7n7c0000gn/C/com.apple.DeveloperTools/6.1.1-6A2008a/Xcode/SharedPrecompiledHeaders/Name With Spaces-Prefix-ckvhmqnqplwgwsadtcudxjtjevvu/Name With Spaces-Prefix.pch.pch' was built
note: please rebuild precompiled header '/var/folders/bh/96_w0c8n6gl43402j6cs7n7c0000gn/C/com.apple.DeveloperTools/6.1.1-6A2008a/Xcode/SharedPrecompiledHeaders/Name With Spaces-Prefix-ckvhmqnqplwgwsadtcudxjtjevvu/Name With Spaces-Prefix.pch.pch'
1 error generated.
```

Perhaps this issue should be "Cannot use non-latin-alphanumeric characters as mobile app names"?

**Comment by Slava** [comment]
I cannot rename this issue (some problems with GitHub), so I am going to close this as a dup of https://github.com/meteor/meteor/issues/3367.
