### ISSUE TITLE
Meteor.call() not working on IE9

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#3422]
I've defined some methods in `/server/methods.js`, and calling them from the client-side within <code>Template.<i>template</i>.events({})</code> using `Meteor.call()`. It works in Chrome, but none of the methods work in IE9. How can I make it work in IE9?

**Comment by PeppeL-G** [comment]
I'm guessing that it's you who have done something wrong in your event, and that this is not a bug in Meteor, but if you post your code for the event we can check. Otherwise you need to create a minimal reproduction project according to [these instructions](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor).

**Comment by d4nyll** [comment]
I have used a minimalistic test method and called it.

**/server/methods.js**
```javascript
Meteor.methods({
  testMethod: function(data) {
    return 'Method returned';
  }
});
```

**/client/js/main.js**
```javascript
Template.test.events({
  'click #testbutton': function (event) {
    Meteor.call('testMethod', 1, function (error, result) {
      console.log(error);
      console.log(result);
    });
  }
});
```

**/client/test.html**
```html
<template name="test">
	<button type="submit" name="testbutton" id="testbutton">Test Button</button>
</template>
```

In Chrome, I got the expected outcome:

`undefined`, which is what is returned immediately on the client-side
`Method returned`, which is what is returned from the server

In IE9, I get not console output whatsoever.

**Comment by PeppeL-G** [comment]
Your button is a submit button, and I guess that's why IE9 is acting weird. Try using `type="button"` instead. 

By the way, `console.log(error)` logs `undefined` because there is no error; it's not something the client returns immediately.

**Comment by d4nyll** [comment]
Thanks PeppeL-G for your help so far, I've updated my comment as not to confuse other people.

I have tried using `type=button` but it still doesn't work. Actually, I don't think `type=submit` is the culprit here. I have put the code at http://ie9.meteor.com/ and it works fine. So my best guess at the moment is that some configuration in my project, server, or other packages is preventing me from calling server methods. Will report back when I know more.

**Comment by d4nyll** [comment]
I have added all the packages into http://ie9.meteor.com/ and it still works fine in IE9, therefore, I am ruling out that packages are the culprit.

**Comment by d4nyll** [comment]
I found the problem. WebSocket was not configured properly on my server. I tried this on a different server and configure WebSocket from scratch and it worked. So I guess the fall-back for WebSocket didn't work in IE9 for some reason. Since this issue is resolved for me I will close this issue.

**Comment by glasser** [comment]
Glad to hear you fixed your issue!
