### ISSUE TITLE
Phonegap - JDK is not installed (use JDK_HOME/bin in search)

### ISSUE THREAD

**Issue by scottburch** [meteor/meteor#3426]
The only code which checks for a JDK on platforms other than Mac is this:

return !!Host.which('jarsigner');

Should also try JDK_HOME/bin

**Comment by Slava** [comment]
Can you please give more information: what is the bug and how to reproduce it?

**Comment by scottburch** [comment]
Yes.  I have a JDK installed, but JDK_HOME/bin is not in my path.  Most Java applications will look at JDK_HOME/bin as a path to JDK commands.  Not really required, I added JDK_HOME/bin to my path and everything worked.  I just have seen it as the norm.

JDK_HOME is an environment variable.

**Comment by scottburch** [comment]
The reason this was an issue for me is that I had to dig into the code to find out what the issue was.  Trying to make it easier for others.
