### ISSUE TITLE
Support --devicetypeid from ios-sim for meteor run ios command

### ISSUE THREAD

**Issue by ianserlin** [meteor/meteor#3430]
By default the `meteor run ios` command opens an iPhone 4s simulator on my machine (OS X 10.10.1 / Xcode 6.1.1). There is currently no way to change this default or use the simulator itself to re-launch simulating your desired device.

A workaround is to use `meteor run ios-device` and then use Xcode to launch the simulator with your appropriate device.

However, ios-sim supports a --devicetypeid command line parameter to specify what device you would like to open for simulation.

https://github.com/phonegap/ios-sim

```
--devicetypeid <device type>

The id of the device type that should be simulated (Xcode6+). Use 'showdevicetypes' to list devices.
e.g "com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone6, 8.0"
```

It's a small enhancement, but if supported and clearly documented will make iOS development that much smoother.

**Comment by Slava** [comment]
@ianserlin this is a very good idea. We already have the `feature` tag on this. Next time we work on new features for Cordova, we should consider providing more options to choose the iOS simulator device and the Android emulator by name.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20--devicetypeid%20from%20ios-sim%20for%20meteor%20run%20ios%20command&body=Migrated%20from:%20meteor/meteor%233430) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
