### ISSUE TITLE
Can we get a better section on meteor load order in the docs?

### ISSUE THREAD

**Issue by fuzzybabybunny** [meteor/meteor#3431]
The load order has been confusing me for quite some time. I didn't feel that the docs gave a very good timeline of when things get loaded so I created this little test project and some short docs:

https://github.com/fuzzybabybunny/meteor-load-order-test

I'm kind of a noob at coding. Would something like this be ok to contribute to the official Meteor docs? I'm not sure how to go about doing it.

**Comment by glasser** [comment]
I'm not sure that the text you wrote is a good fit for the style of our docs.  If you have specific edits you would suggest, feel free to send us a pull request to the docs or just describe what you'd change.

(Eventually, we plan to have the load order here just be the default for apps and let you configure the details of your desired load order: https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order )

There are community resources for explanatory docs also, like [Meteorpedia](http://www.meteorpedia.com/read/Main_Page).
