### ISSUE TITLE
Accounts commands are slowed down by old release used by accounts server

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3433]
meteor-accounts is running 0.9.0.1, which means that it doesn't speak DDP 1, which means that every login attempt from a modern tool wastes an extra roundtrip (~700 ms for me) discovering this over and over again.

@multilinear will upgrade the server as part of other infrastructure improvements.

**Comment by glasser** [comment]
(Specifically, this will be fixed by upgrading to 0.9.1.  We will probably upgrade to 1.0.2.1 as part of other infrastructure improvements.  If we want to upgrade in place instead of waiting for the other improvements, we really can only upgrade to 0.9.1.1 --- 0.9.2 is incompatible with the special infrastructure used for this particular app.)

**Comment by cmnjcs** [comment]
We're having some trouble in our application with using `Accounts.changePassword()` that appears to be a race issue--the short version is that when `Accounts.changePassword()` is called, more often than not the user is logged out. It looks like that's a result of the resume token being operated on when the server-side code clears out all the other tokens. If the client is forced to wait right after the call is made (through `console.log()` or `debugger` statements), `Accounts.changePassword()` works fine.

Do you think that this issue you've filed may be related to our issue?

**Comment by glasser** [comment]
That's definitely not related to this issue, which is about specific infrastructure issues affecting the server which handles 'meteor login'. Please file separately.

**Comment by glasser** [comment]
This has been fixed (thanks @multilinear )
