### ISSUE TITLE
Specify android target API version

### ISSUE THREAD

**Issue by shirk3y** [meteor/meteor#3434]
It's currently hardcoded to `1` here: https://github.com/meteor/meteor/blob/ddd2fe8e91ed0c5dbf0738922f3fb54336a805f1/tools/commands-cordova.js#L2298

I am using global SDK and have many API versions installed. Meteor defaults it to `1`, so in my case `android-10` version. Android 10 does not support `default/x86` ABI, so I receive error:

    Error: Invalid --abi x86 for the selected target.

**Comment by tacone** [comment]
Hello, I'm using the bundled sdk and I had the opposite problem. An API 17 device and a default API level at 19.
Adding `App.setPreference('android-targetSdkVersion', '17');` to `mobile-config.js` fixed it for me.

**Comment by stubailo** [comment]
@shirk3y, did setting that preference help for you?

**Comment by glasser** [comment]
Is the bug here that we should be using the result of android-targetSdkVersion to set the `--target` flag in createAvd?

**Comment by guilhermebruzzi** [comment]
@glasser Just like the other issue, i think you can solve the problem with a --target flag in meteor install-sdk android and let the user choose.
But in the case of having App.setPreference('android-targetSdkVersion', '17') in mobile-config.js, i agree that would be great if meteor can choose a target that support this sdk version in its installation.
Meteor can do the command:
android create avd --target android-17 --name meteor --abi default/x86 --path ~/.android/avd/meteor.avd
(17 being the android-targetSdkVersion in this case).

**Comment by ukabu** [comment]
I'm trying to use the `cordova:com.randdusing.bluetoothle@2.1.0` plugin. It requires android-21, setting the preference for android-targetSdkVersion to 21 does not solve the problem because it need 21 to compile and what is installed in 19 and the project.properties specify 19 (AndroidManifest.xml is ok though).

Is there any workaround this issue?

**Comment by ukabu** [comment]
I was able to workaround the issue. Steps:

* Install platform-21 [manually](http://stackoverflow.com/questions/17963508/how-to-install-android-sdk-build-tools-on-the-command-line) from the `~/.meteor/android_bundle/android-sdk` folder,
* Set the `android-targetSdkVersion` preference to 21 in `mobile-config.js`
* Create the `cordova-build-override/platforms/android/` folder
* Copy the `project.properties` from `.meteor/local/cordova-build/platforms/android/` to the `cordova-build-override/platforms/android/` folder
* Change the `android-19` in the `project.properties` file to `android-21`.

Needless to say that an easier way would be welcome ;-)

**Comment by pfafman** [comment]
+1

**Comment by devsignmy** [comment]
any suggestion to do this in meteor 1.2?

**Comment by forkmind** [comment]
@nizulzaim +1

**Comment by krizka** [comment]
@nizulzaim +1

**Comment by martijnwalraven** [comment]
Closing this issue, as this is not something we can fix in our Cordova integration. Rather, Cordova itself pins the target as part of its platform releases. In Meteor 1.3, we've upgraded to the latest Cordova versions and this requires target `android-23`.
