### ISSUE TITLE
Recompiling app in development

### ISSUE THREAD

**Issue by choyweston** [meteor/meteor#3436]
Hi, 

We're running a large app (Classcraft). We're on version 1.0.2.1. Since 1.0.2 (or maybe 1.0.1) development has become extremely slow. This is because the reloading of Meteor, when a file is changed has become horrendously long (up to 3 minutes to recompile the app after a simple change). 

We've narrowed it down, it seems there is something like an infinite loop happening... Indeed, after multiple saves, the node process seems to stall - in Activity Monitor on Mac, the `node` process takes up up to 99.5% of the CPU (2.8 GHz Intel Core i7, 16Gb Ram). When we first start Meteor, it takes about 5%. If you kill node when it's at 99.5%, then restart Meteor, the reload time becomes manageable again, for while. Then it goes back up to 99.5% (stalled). 

We're guessing that it's happening when you edit and save a file while Meteor is rebuilding the app, causing it to rebuild while it's rebuilding already.

We do have a fairly large app, but it hasn't become significantly larger in the last months and this just seems to be getting worse and worse. 

Shawn Young
CEO Classcraft

**Comment by glasser** [comment]
Does this happen consistently?

Does the same thing happen when if you set the `METEOR_WATCH_FORCE_POLLING` environment variable to a non-empty value?

**Comment by choyweston** [comment]
Yes, it happens consistently. Quick tests seem to indicate that setting `METEOR_WATCH_FORCE_POLLING` to a non-empty value fixes the issue. Recompile is slow, upwards of 10 - 15 sec, but nowhere near the 200 sec we've been getting. The team will develop with this var set tomorrow, I'll get you more feedback. What exactly is the effect of setting `METEOR_WATCH_FORCE_POLLING`? (PS Thanks for the reply)

**Comment by choyweston** [comment]
It seems this could be related to issue #3373 ?

**Comment by glasser** [comment]
It switches from the supposedly more efficient low-level path watching API (kqueue on OSX) to a dumber more CPU crunchy one.  But sounds like for some reason the fast API isn't fast for you.

If there's any way that you can make a reproduction of this, that would be great.

**Comment by choyweston** [comment]
What do you mean specifically by :
> "If there's any way that you can make a reproduction of this, that would be great."

**Comment by glasser** [comment]
A story about your experiences gives me sympathy.

Specific directions to enable me to have a similar enough setup to you in order to actually see the problem on my own machine gives me tools to fix it.

**Comment by choyweston** [comment]
The team developed for the last two days using `METEOR_WATCH_FORCE_POLLING` and finally are reporting that it doesn't really make a difference.

In terms of our setup : 
- The app is split up according to the recommended structure `client`, `server`, `public`, etc.
- We've got about 80 templates, with a `.tpl`, `.js` and `.styl` file for each template.   
- We have a LOT of static assets in `public`, 2500+ images, for a total of 250 mb.
- Client code is 1.5 Mb, Server 600kb, lib 200kb
- We're compiling our stylus stylesheets outside of Meteor, using grunt, and putting the css stylesheet in `public`
- Everyone is running recent (max 2 years old) Macs
- Packages used
    - accounts-base
    - accounts-password
    - application-configuration
    - browser-policy
    - browser-policy-content
    - classcraft:imagemagick
    - classcraft:knox
    - classcraft:meteor-emailreplyparser
    - classcraft:meteor-ua-parser
    - classcraft:meteor-wkhtmltopdf
    - cmather:blaze-layout
    - cmather:iron-core
    - cmather:iron-dynamic-template
    - cmather:iron-layout
    - follower-livedata
    - force-ssl
    - geojson-utils
    - id-map
    - iron:controller
    - iron:core
    - iron:dynamic-template
    - iron:layout
    - iron:location
    - iron:middleware-stack
    - iron:router
    - iron:url
    - jparker:crypto-core
    - jparker:crypto-md5
    - launch-screen
    - matb33:collection-hooks
    - meteor-platform
    - meteorhacks:async
    - meteorhacks:kadira
    - meteorhacks:kadira-binary-deps
    - meteorhacks:meteorx
    - meteorhacks:npm
    - meteorhacks:ssr
    - mrgalaxy:stripe
    - mrt:jquery-ui-sortable
    - mrt:moment
    - mrt:moment-timezone
    - mrt:numeral
    - npm-container
    - oauth-encryption
    - observe-sequence
    - ordered-dict
    - raix:ui-dropped-event
    - rajit:bootstrap3-datepicker
    - reactive-dict
    - reactive-var
    - sergeyt:typeahead
    - service-configuration
    - standard-app-packages

**Comment by choyweston** [comment]
I've tried removing the assets from the public folder and the issue goes away. Is there a way to tell meteor not to watch a specific folder (static assets folder)?

**Comment by avalanche1** [comment]
Cannot speak for Meteor bundle process, but as a workaround you can serve static assets from the file system.

**Comment by abernix** [comment]
This is relatively old and we're trying to clean up some duplicated issues so I'm going to close this in light of (already) improved build performance in newer versions of Meteor ( #7668 + #8044) and also #6002 (`.meteorignore`) and #6952 (large number of files in `public`).

Thanks for opening this originally!
