### ISSUE TITLE
Meteor 1.0.2 will not run at all using Vagrant from Windows

### ISSUE THREAD

**Issue by 1jerry** [meteor/meteor#3437]
W20150107-09:00:18.736(-8)? (STDERR) /home/vagrant/dotMeteor/todos/local/build/programs/server/shell.js:145
W20150107-09:00:18.737(-8)? (STDERR)       throw new Error("Not a Meteor app directory");

(I noticed this on 12/19/14, as soon as I first tried to update to 1.0.2, but it was not until now that I had time to try different solutions and write this up.  1.0.2.1 has same issue.)

### Background.
  Developing with the current Meteor version from Windows requires using a Linux VM via VirtualBox and Vagrant.  The .meteor/local directory *must* be somewhere in the Vagrant home directory, but in order to access all the application files from Windows they must be under the /vagrant directory.  This is accomplished with a symlink within Linux.

### Issue.
  When Meteor 1.0.2 starts, for some reason shell.js tries to find the "working" directory by traversing up the directory structure *from shell.js in the build directory*.  I don't know why or even why it is interfering with running the server (especially since I'm running Meteor from the "working" directory anyway).  Since the *build* folder location will never have a parent folder named ".meteor" since it is symlinked in the VM it fails without a fallback.

### Attempts at solving. 
 I tried hard coding the directory to "." or "/vagrant/todos".  It removed the error, but would not start the server.  It either stopped at "starting MongoDB", or at "LISTENING" (with no port listed) and would not respond to any HTTP requests.  Had to revert the whole repo to run 1.0.1.

**Comment by glasser** [comment]
Fixed in 1.0.4.
