### ISSUE TITLE
Where to ask for code-review help?

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3440]
:question: 

I have this swipe package I made and I could really use some help getting to the next level, but I don't know where to ask for help. I thought about a crater.io post, but that seems out of place. Is there any place you can think of to post this to the meteor community?

This is basically what I need help with:

https://github.com/ccorcos/meteor-swipe

1. I could probably use a block helper which may be more appropriate.
2. Managing all of the click and touch events is becoming a nightmare and a total mess. There's probably a better way of doing this with FRP.
3. Persisting the state of this package between hot-code pushes.

**Comment by ccorcos** [comment]
P.S. How do I add a question label?

**Comment by yaliceme** [comment]
Hi @ccorcos, right now the best place to do that is to post a new topic at meteor-talk https://groups.google.com/forum/#!forum/meteor-talk It's the Meteor forum for getting help with projects, asking questions, and discussing new ideas.

**Comment by ccorcos** [comment]
Thanks!
