### ISSUE TITLE
range rendering issue

### ISSUE THREAD

**Issue by ih** [meteor/meteor#3442]
There seems to be a problem with rendering when the DOM is changed by a [range](https://developer.mozilla.org/en-US/docs/Web/API/Range) object.

Steps for reproduction:

**1. Run server**

ih@Irvins-MacBook-Air~/Downloads$ git clone https://github.com/ih/range-rendering-issue.git
Cloning into 'range-rendering-issue'...
remote: Counting objects: 12, done.        
remote: Compressing objects: 100% (9/9), done.        
remote: Total 12 (delta 0), reused 12 (delta 0)        
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
ih@Irvins-MacBook-Air~/Downloads$ cd range-rendering-issue/
ih@Irvins-MacBook-Air~/Downloads/range-rendering-issue$ meteor
[[[[[ ~/Downloads/range-rendering-issue ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/

**2. Select text**
Navigate to the app in your browser and select some part of text 'hello hello hello' with the mouse.  On mouse up I would expect the text to be replaced with 'goodbye goodbye', but instead it gets inserted in the existing text.
![screen shot 2015-01-07 at 1 48 53 pm](https://cloud.githubusercontent.com/assets/45019/5655407/d538887e-969b-11e4-9892-8406ef903467.png)

![screen shot 2015-01-07 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/45019/5655353/17cb44de-969b-11e4-90a5-6a310624203a.png)

I've tried a few work-arounds in my real app like replacing the contents of the div containing {{renderContent}} with a blank string before the helper sets the session variable, but that didn't really work (weird things happen if you keep clicking the div).  Thanks for taking a look!

**Comment by stubailo** [comment]
Hi @ih!

This is a side effect of an intended feature. The feature is that if you render some text with Blaze, you can append new elements to the end of the container and they will not get deleted when the text is re-rendered. For example, consider a jQuery plugin that adds elements to the DOM - it would be unfortunate if it broke when you used Blaze to render some other part of that element.

In this case, from Blaze's point of view, this is what is happening (I will represent DOM text nodes as `<text />` here):

##### 1. Initial state
```html
<div class="content"><text /></div>
```

##### 2. Spans and text nodes are added
```html
<div class="content"><text /> <span></span> <text /> <span></span> <text /></div>
```

##### 3. The Session variable changes and Blaze re-renders the first text node, taking care not to delete any of the other nodes that were inserted.

There's a simple **workaround** that fixes your case - make the whole thing a single DOM node like this:

```html
<template name="hello">
	<div class="content">
		{{{renderContent}}}
	</div>
</template>
```

```js
Template.hello.helpers({
	renderContent: function () {
		return "<span>" + Session.get("content") + "</span>";
	}
});
```

If you change your code to the above, the reproduction you have submitted works as expected.
