### ISSUE TITLE
After deploying to Meteor Template.dynamic loses its reactivity

### ISSUE THREAD

**Issue by hettema** [meteor/meteor#3444]
I use a collection to manage the steps inside a wizard. 
I use a simple if/else in the helper for Template.dynamic to determine which template to serve.
Everything works locally, things break when I deploy (http://dinnerdish.meteor.com).
On dinnerdish.meteor.com I can see the Session variables and the Wizard collection items in the chrome console. 

home template:
```javascript    
{{#if wizard}}
  {{#with wizard}}
    {{> Template.dynamic template=wizardTemplate}}
  {{/with}}
    {{else}}
  <h4>Do you know what you are going to eat tonight?</h4>
    <p>
        <button type="button" class="btn btn-success yes">Yes! I can share my inspiration</button>
    </p>
    <p>
        <button type="button" class="btn btn-danger no">No :( Please give me some inspiration</button>
    </p>
{{/if}}
```

wizard and wizardTemplate helpers:
```javascript
Template.home.helpers({
    wizard: function() {
        var today = new Date();
        if (Wizard.find({
                onDay: today.setHours(0, 0, 0, 0)
            }).count() != 0) {
            Session.set("wizardStep", Wizard.findOne({createdBy: Meteor.userId(), onDay: today.setHours(0,0,0,0)}).wizardStep)
            return Wizard.findOne({
                createdBy: Meteor.userId(),
                onDay: today.setHours(0, 0, 0, 0)
            })
        } else {
            return false
        }
    },
    wizardTemplate: function() {
        if (this.wizardStep === "answeredNo" || Session.get("wizardStep") === "answeredNo") {
            console.log("executed if answeredNo")
            return "todayMeals"
        } else if (this.wizardStep === "answeredYes" || Session.get("wizardStep") === "answeredYes") {
            console.log("executed else if answeredYes")
            return "wizardAddTitle"
        } else if (this.wizardStep === "addedTitle" || Session.get("wizardStep") === "addedTitle") {
            console.log("executed else if addedTitle")
            return "wizardAddImage"
        } else if (this.wizardStep === "addedImage" || Session.get("wizardStep") === "addedImage") {
            console.log("executed else if addedImage")
            return "wizardAddDetails"
        } else if (this.wizardStep === "addedDetails"  || Session.get("wizardStep") === "addedDetails") {
            console.log("executed else if addedDetails")
            return "wizardSuccess"
        } else {
            console.log(this)
            console.log("something went wrong in the wizard")
        }
    }
});
```

Could this be a meteor deploy related bug? I noticed that the deployed code looks like this:
```javascript
wizardTemplate: function() {
    return "answeredNo" === this.wizardStep || "answeredNo" === Session.get("wizardStep") ? (console.log("executed if answeredNo"), "todayMeals") : "answeredYes" === Session.get("wizardStep") ? (console.log("executed else if answeredYes"), "wizardAddTitle") : "addedTitle" === this.wizardStep || "addedTitle" === Session.get("wizardStep") ? (console.log("executed else if addedTitle"), "wizardAddImage") : "addedImage" === this.wizardStep || "addedImage" === Session.get("wizardStep") ? (console.log("executed else if addedImage"), "wizardAddDetails") : "addedDetails" === this.wizardStep || "addedDetails" === Session.get("wizardStep") ? (console.log("executed else if addedDetails"), "wizardSuccess") : (console.log(this), void console.log("something went wrong in the wizard"))
}
````

My repo can be found here: https://github.com/hettema/dinnerdish2

**Comment by hettema** [comment]
I'm pretty confident this is something beyond my control (scary thing to say cause I'm a newb). 

I have created a simple test and deployed it here:
http://template_test.meteor.com/

the repo is here: 
https://github.com/hettema/template_dynamic_test

Locally this test works fine but as soon as I deploy the wizardTemplate helper fails to execute.

**Comment by PeppeL-G** [comment]
I think it's a timezone difference problem. You should work with UTC time instead of local time. Instead of using `setHours`, use `setUTCHours`. Does that fix your problem?

**Comment by hettema** [comment]
Thanks @PeppeL-G, sadly that didn't do the trick. 

I've been breaking my brain on this and I think I might've found the difference in local vs. deployed behaviour:

Locally my Template.dynamic if statement seems to be executed twice. On the server only once. 

**Locally** the if(mongo query) evaluates to undefined and breaks (without logging anything to the console), then the helper runs again, the mongo query finds a document and the correct template is served. 

**Deployed** the if statement runs only once. The mongo query evaluates to false and the Template.dynamic isn't being very dynamic :)

Does that make any sense?

**Comment by hettema** [comment]
OK, I've ruled out Template.dynamic as the problem. Somehow my collection gets polled one more time locally vs. deployed. 

I've rebuild the "wizard" (I'm starting to doubt I should use that name for my function :P) using iron:router:

```javascript
Router.map(function() {
    this.route("/", {

            path: "/",
            layoutTemplate: "layout",
            action: function() {
                this.wait(Meteor.subscribe("wizard"))
                if (this.ready()) {
                    this.next()
                } else {
                    this.render("loading")
                }
            },
            data: function() {
                var today = new Date()
                var currentWizardStep = Wizard.findOne({
                    createdBy: Meteor.userId(),
                    onDay: today.setHours(0, 0, 0, 0)
                });
                console.log(currentWizardStep)
                if (!currentWizardStep) {
                    this.render("wizardYesNo")
                } else {
                    if (currentWizardStep.wizardStep === "answeredYes") {
                        this.render("wizardAddTitle")
                    } else if (currentWizardStep.wizardStep === "answeredNo") {
                        this.render("wizardAnsweredNo")
                    } else {
                        this.render("wizardAddMedia")
                    }
                }
            }
        }),
        this.route("login", {
            path: "/login"
        }),
        this.route("loading", {
            path: "/loading"
        })
})
```

Works perfectly locally but after deploy (dinnerdish.meteor.com) it breaks again. Here are the two console.logs (local vs. deployed) of the currentWizardStep variable in Router.map:

**local**
"undefined"
"undefined"
"undefined"
Object {_id: "47uq2Yw5jpx3S9Jvj", createdBy: "SSS3kAkf7qzyvz7eM", createdOn: Mon Jan 12 2015 21:34:47 GMT+0100 (CET), onDay: 1421017200000, wizardStep: "answeredYes"}_id: "47uq2Yw5jpx3S9Jvj"createdBy: "SSS3kAkf7qzyvz7eM"createdOn: Mon Jan 12 2015 21:34:47 GMT+0100 (CET)onDay: 1421017200000wizardStep: "answeredYes"__proto__: Object

**deployed**
"undefined"
"undefined"
"undefined"

**Comment by hettema** [comment]
@PeppeL-G It looks like you were right all along, I merely fucked up testing your suggestion. I didn't implement UTCHours across the board. 

/me crawling back into his newbie hole :+1:

**Comment by glasser** [comment]
Thanks for helping, @PeppeL-G!
