### ISSUE TITLE
Google fonts with browser-poilcy

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#3448]
When I run my boilerplate locally I get following errors in the Javascript console.

```code
Refused to load the font 'data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjB5…AgAGIAeQAgAEkAYwBvAE0AbwBvAG4ALgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' because it violates the following Content Security Policy directive: "font-src 'self' http://*.googleapis.com https://*.googleapis.com http://*.gstatic.com https://*.gstatic.com http://*.bootstrapcdn.com https://*.bootstrapcdn.com".
```

This looks like a local font is being loaded and I thought the browser-policy doesn't restrict scripts, fonts etc. from local sources. Simply checkout https://github.com/matteodem/meteor-boilerplate, open it and check the client side console.

Reproduced in latest version of Chrome and Safari

**Comment by estark37** [comment]
Hi @matteodem. To load fonts from `data:` urls, you need to call `BrowserPolicy.content.allowFontDataUrl()`. (https://github.com/meteor/meteor/blob/devel/packages/browser-policy/README.md) Does that fix your problem?

**Comment by matteodem** [comment]
Perfect, thank you!

**Comment by MaxPleaner** [comment]
Is this possible if my site is being server in an iframe via _framing_? 

I'm getting `BrowserPolicy.framing.allowFontDataUrl is not a function`

**Comment by MaxPleaner** [comment]
Disregard last comment. `BrowserPolicy.content.allowFontDataUrl()` is still used on the server when the Meteor site is being served into an iframe.
