### ISSUE TITLE
Allow templates to be grouped

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#3449]
**_1 Upvote**_ At the moment, I have several templates which, when rendered, needs to run some Javascript to style it properly.

``` html
<template name="abc">
</template>
<template name="def">
</template>
<template name="ghi">
</template>
```

``` js
Template.abc.rendered = function() {
  renderSliderScrollbar();
}
Template.def.rendered = function() {
  renderSliderScrollbar();
}
Template.ghi.rendered = function() {
  renderSliderScrollbar();
}
```

It would be nice if we can apply a group to the template so when any member of this group is rendered, it would run the function.

``` html
<template name="abc:xyz">
</template>
<template name="def:xyz">
</template>
<template name="ghi:xyz">
</template>
```

``` js
Template.:xyz.rendered = function() {
  renderSliderScrollbar();
}
```

**Comment by laosb** [comment]
+1 for this idea. 

What's more, it will be good if we can group subscriptions.

**Comment by awatson1978** [comment]
You can do this with Template.registeHelper().  Subscriptions can return an array of cursors, which let one publish a subscription that acts as a group of other subscriptions.

**Comment by d4nyll** [comment]
@awatson1978 Hi Abigail! Can you give us a bit more details as to how grouping templates can be achieved using `Template.registerHelper()`? Thanks in advance.

**Comment by awatson1978** [comment]
This is the basic pattern, using a hidden element. 

```html
<template name="abc">
  <div class="hidden">{{renderScrollbar}}</div>
</template>
<template name="def">
  <div class="hidden">{{renderScrollbar}}</div>
</template>
<template name="ghi">
  <div class="hidden">{{renderScrollbar}}</div>
</template>
```

The helper is registered across all templates, and renders the slider as a side effect of rendering a time stamp to the invisible element.  The Template.foo.rendered() functions then opt-into the shared group by setting a timestamp to the reactive variable.

```javascript
Template.registerHelper('renderScrollbar', function(){
  renderSliderScrollbar();
  return Session.get('renderTrigger');
});
Template.abc.rendered = function() {
  Session.set('renderTrigger', new Date());
}
Template.def.rendered = function() {
  Session.set('renderTrigger', new Date());
}
Template.ghi.rendered = function() {
  Session.set('renderTrigger', new Date());
}
```

If you don't like the hidden element, you could also try something like this:
```html
<template name="abc">
  <div id="abc" last-rendered='{{xyz}}'>
  </div>
</template>
<template name="def">
  <div id="def" last-rendered='{{xyz}}'>
  </div>
</template>
<template name="ghi">
  <div id="ghi" last-rendered='{{xyz}}'>
  </div>
</template>
```

And maybe define your helper group trigger a bit more explicitly:
```javascript
Template.registerHelper('xyz', function(){
  renderSliderScrollbar();
  return Session.get('renderTrigger');
});
```

This pattern is extendable to window resize, device orientation change, re-theming, hardware events, button clicks, and other viewport modifications.  Simply update the renderTrigger with a new timestamp anytime you want the scroll bars to re render.

**Comment by d4nyll** [comment]
@awatson1978 Thank you very much for your detailed answer, I have learnt something new today! That is definitely a viable alternative and work-around for now, however, I still think, in terms of usability, allowing templates to be grouped can have further benefits:

 * Each group can have their own helpers, which doesn't need to be global
 * Finer granularity - The grouped templates can share functions, which when ran, only affects that particular template (through the use of `this`). If we use global helpers, every member of that group will be affected.
 * DRY - It'd save you doing `Session.set('renderTrigger', new Date());` three times for the three different templates, just do it once inside a group
 * Syntactically cleaner and logically easier to understand

**Comment by glasser** [comment]
Note that you can also just write `Template.a.rendered = Template.b.rendered = function () {}`.

This somewhat relates to https://trello.com/c/igqeUcwM/17-template-and-helper-namespacing

**Comment by ccorcos** [comment]
I think an elegant solution could be a functional programming perspective.

What if `Template.rendered` accepted a function? Then you could do something like this:

```
Template.abc.rendered ->
    renderSliderScrollbar()
```

Then we could do something like this:

```
renderSliderBeforeRendered = (names...) ->
  for name in names
    Template[name].rendered = ->
      renderSliderScrollbar()
      Template[name].rendered.apply(this, this.arguments)
```

I don't think the context of everything here is correct, but it should be close. All you're doing here is inserting a function before. Maybe there's a lodash function for doing exactly this, I'm not sure. But the point is, you could then do:

```
renderSliderBeforeRendered('abc', 'def', 'ghi')
```

Pretty sweet right?

**Comment by mitar** [comment]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) have namespaces. And for this it would be easy to have a common base class with the logic you want and then extend it into three components.

**Comment by hwillson** [comment]
Migrated this over to meteor/blaze#189 - closing here. Thanks!
