### ISSUE TITLE
Calling Accounts.changePassword() sometimes triggers logout of user

### ISSUE THREAD

**Issue by cmnjcs** [meteor/meteor#3451]
More often than not, calling `Accounts.changePassword()` results in the following error:
`Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`. No callback is triggered, even if one was defined. Notably, if there is a delay forced on the client (through the use of a `console.log()` or `debugger` call), the call to `Accounts.changePassword()` works fine, without issue.

Unfortunately, I'm not able to reproduce this bug in a demonstration application. I will explain as much information as I've been able to find out from my debugging below.

Upon calling `Accounts.changePassword()`, the [method](https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js#L271-L316) in `accounts-password/password-server.js` is called. The `Meteor.users.update()` call is made. Using the [meteor-collection-hooks package](https://github.com/matb33/meteor-collection-hooks), I observe the update to the collection. In particular, I've noticed that the `$pull` component of the update doesn't seem to look right. This is the output of calling `console.log(modifier)`:

```
{ '$set': { 'services.password.bcrypt': '$2a$10$ABpcBHazkyCfXn.AuP/Z5eBmPHC/qQ/wXFeW2pigsLYz/J..k/h6y' },
  '$pull': { 'services.resume.loginTokens': { hashedToken: [Object] } },
  '$unset': { 'services.password.reset': 1 } }
```

This is the output of calling `console.log(modifier.$pull["services.resume.loginTokens"].hashedToken)`:

```
{ '$ne': undefined }
```

Following this, I use a post-update hook to observe the User object. This is the output of `console.log(doc)`:

```
{ _id: 'XCfrk58zHt8gABoQn',
   createdAt: Fri Jan 09 2015 16:52:38 GMT-0500 (EST),
   emails: [ { address: 'john@abc.com', verified: false } ],
   profile: 
    { active: true,
      roles: [ 'User' ],
      name: 'John Farmer',
      traits: 
       { dexterity: 10,
         intelligence: 9,
         charisma: 11,
         beauty: 11,
         strength: 8,
         wisdom: 10 },
      avatar: null },
   roles: [ 'User' ],
   services: 
    { password: { bcrypt: '$2a$10$/rh4kQKcaA9kcUsjzpPNkuYLRvnaFXfeyoivG0QyioDP8I0Cly0w2' },
      resume: { loginTokens: [] } },
   username: 'john' }
```

Notably, the `loginTokens` array is empty. If there is a delay on the client, then `loginTokens` is not empty.

I've looked through our code, and can't find any router calls that are being triggered by a change in the user, or anything that has a dependency on `Meteor.users()`, `Meteor.userId()`, or the particular use that seem to be getting triggered by this.

**Comment by cmnjcs** [comment]
https://github.com/grovelabs/grove-os/issues/19

**Comment by glasser** [comment]
Thanks for all the details.  If it is possible for you to reproduce in a cloneable reproduction, that would help, but this is a good start.

Based on your logs, it sounds like there is no login token set during your changePassword method:

```js
  var currentToken = Accounts._getLoginToken(this.connection.id);
  Meteor.users.update(
    { _id: this.userId },
    {
      $set: { 'services.password.bcrypt': hashed },
      $pull: {
        'services.resume.loginTokens': { hashedToken: { $ne: currentToken } }
      },
      $unset: { 'services.password.reset': 1 }
    }
  );
```

Not sure how you got into a case where you are logged in and have no login token.

**Comment by cmnjcs** [comment]
I concur with the assessment that a login token is not being set. More specifically, I'm thinking that the call to `Accounts._getLoginToken()` is not returning the correct data. I can manually inspect the user object (using both Robomongo and the Meteor shell), and see that there is a token in the `services.resume.loginTokens` array prior to the update call in `changePassword()`. I'm trying to use the shell to see what data the Accounts package sees, like the `accountData` object, but not having much luck--any pointers?

**Comment by MHerszak** [comment]
I have the same problem. I am using changePassword() and Meteor logs out. It wouldn't be a problem if my callback would actually be called. All I receive is the message: "Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]" Is there a way to hook into the changePassword process? Any ideas?

**Comment by ko0stik** [comment]
In cas some have the same issue of being disconnected every time without having the callbacks fired.

Had the same issue last hour when I implemented our change password page. I use autoform and simple schema.
Turned out I was using `AutoForm.hooks onSubmit` and forgot to `return false` at the end, so the form not being attached to any collection was then also submitted by the browser, causing this disconnection.

**Comment by jamiedumont** [comment]
To add my two pence to this issue: I encountered the same recently.

Taking @ko0stik 's hint, I removed the form element and the `onSubmit` and instead used an `onClick` event to fire the exact same script from a button. This resolved my issue of being logged out with a 403 error everytime.

It would appear the `Accounts.changePassword()` objects to `<form>`'s

**Comment by hwillson** [comment]
Since this issue doesn't appear to be happening that frequently (lack of recent activity and +1's), as part of the on-going old issue cleanup process, I'll close it for now. If anyone is still encountering this issue and can supply a small, runnable reproduction demonstrating it with a recent version of Meteor (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), please post back and we'll re-open. Thanks for posting this originally!
