### ISSUE TITLE
jquery should be versioned separately from the Meteor release

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3456]
jquery should move into `packages/non-core` so that upgrades are decoupled from the release process.  (ie, you should be able to upgrade jquery without upgrading Meteor and vice versa.)  Dependencies on jquery from other packages such as blaze will specify a version constraint.

We can't do this right now because the cordova-support isopacket uses boilerplate-generator, which indirectly depends on jquery.  There must be some refactoring of the packages in question to ensure that you can evaluate a Spacebars template in Node without depending on jquery.

**Comment by skirunman** [comment]
Hi @abernix Is this not closed in [release 1.3.2](https://github.com/meteor/meteor/blob/devel/History.md#v132) as per https://github.com/meteor/meteor/issues/6626?

**Comment by hwillson** [comment]
Just jumping in here - yes it should be. Thanks for pointing this out @skirunman!
