### ISSUE TITLE
Error while running for mobile platforms: Can't build an iOS project from the /tmp directory.

### ISSUE THREAD

**Issue by Wenape** [meteor/meteor#3458]
I was messing around with the .plist file instead of using an override, also removed and re-added the ios platform and now I can't run my meteor application on ios simulator anymore.

I know this has to do with the bug: 

    Don't run your iOS apps from /tmp folder! The Ld linker will fail, there is nothing we can do about it. It happens because linker gets confused by symlinks in /private/tmp

But I don't understand how I'm running from the `/tmp`folder. I'm just running the project from it's usual dir using: `meteor run ios`

**Comment by Wenape** [comment]
Fixed! In my case it had to do with a duplicated cordova plugin. One was added via tarball and the other one was a default plugin.

**Comment by glasser** [comment]
Thanks for the followup.
