### ISSUE TITLE
launch-screen package doesnt work

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3460]
https://atmospherejs.com/meteor/launch-screen

I'm using iron router and everything. But this package doesnt prevent the white screen from showing while the content is loading... 

Try it out with this app: 

https://github.com/ccorcos/meteor-boilerplate

**Comment by Slava** [comment]
@ccorcos can you create a minimal reproduction demonstrating the problem? Remove all unnecessary packages, have clear reproduction steps.

**Comment by ccorcos** [comment]
https://github.com/ccorcos/meteor-launch-screen

I opened the site in mobile safari the iPhone 5 simulator. I added it to the home screen as a web app.

When I open the web app, I get a delay with a white screen before I get the rendered page. I made sure that there would be a good delay in by putting a loop in the created function. Clearly, the page is shown before rendered is called.

**Comment by Slava** [comment]
@ccorcos the repo you linked doesn't demonstrate a problem with IronRouter. Can you clarify the issue you are reporting?

**Comment by Slava** [comment]
@ccorcos actually, rereading your comment, I see that you expected launch screen to appear on a *mobile web app* that you launch from a iPhone's home screen icon. This is *not* the same as Cordova mobile apps, those are installed from App Store.

The launch-screen package doesn't do anything special on web apps at the moment.
