### ISSUE TITLE
Meteor installation stops in between 0% to 5%. 

### ISSUE THREAD

**Issue by akash-bhardwaj** [meteor/meteor#3464]
I'm trying to install meteor on my computer(Macbook, 10.10) using this command:
curl https://install.meteor.com/ | sh
But, the installation just stops in between 0% to 5%. After few minutes, it throws an error:

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 60
.meteor/package-metadata/v2.0.1/packages.data.db: (Empty error message)
tar: Error exit delayed from previous errors.
Installation failed

I've tried every possible solution on the internet, but I didn't find anything helpful.

Please help.

Thank you :)

**Comment by Stefan-Greffenius** [comment]
Maybe this one could help: http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error

**Comment by akash-bhardwaj** [comment]
I tried it already, but It didn't help.
Somehow I got it working, though the solution looks weird. I updated my curl and OMZsh, and It just works fine. 
By the way, thank you so much for your response.

**Comment by glasser** [comment]
Glad to hear this fixed itself.

**Comment by abbood** [comment]
@akash-bhardwaj how did you update your curl on mac?

**Comment by trung1008** [comment]
omg. thanks @akash-bhardwaj. update zsh help me. i fixed bug after fews day :+1:
