### ISSUE TITLE
Package.on_use(), api.add_files() does not handle css media queries correctly

### ISSUE THREAD

**Issue by fsalomon** [meteor/meteor#3465]
As far as I understand

    Package.on_use(function (api, where) {
        api.add_files('styles/some.css', 'client');
    }

should translate relative paths to absolute paths when bundling packages. This works for "regular" css, but not for css inside media queries.

Works:

    .awesome-marker-soft {
        background: url('../images/markers-soft.png') no-repeat 0 0;
    }

(URL will be translated to '/packages/[packagename]/images/markers-soft.png')

Does not work:

    @media (min--moz-device-pixel-ratio: 1.5),(-o-min-device-pixel-ratio: 3/2),(-webkit-min-device-pixel-ratio: 1.5),(min-device-pixel-ratio: 1.5),(min-resolution: 1.5dppx) {
        .awesome-marker {
            background-image: url('../images/markers-soft@2x.png');
        }
    }

(URL will stay '../images/markers-soft@2x.png')

To reproduce:

    meteor create reproduce
    cd reproduce
    git init
    git submodule add https://github.com/richsilv/meteor-leaflet-awesome-markers.git packages/richsilv:leaflet-awesome-markers
    meteor add richsilv:leaflet-awesome-markers
    meteor

**Comment by glasser** [comment]
This seems like a bug in our CssTools in https://github.com/meteor/meteor/blob/devel/packages/minifiers/minifiers.js.

**Comment by RobertLowe** [comment]
@fsalomon thank you for the clear report and steps to reproduce!
