### ISSUE TITLE
Help fixing atmosphere organization name.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#3471]
Hi, I wanted to have a namespace on atmospherejs called `infamous`, so I made an account via atmospherejs.com, but then I realized after the fact that it's possible to create organizations over at meteor.com. Can packages be published using organization names on atmosphere, for example `infamous:package`?

If so, I'd rather create an org with my already existing username, `trusktr`. In that case, would you guys be able to help me convert `infamous` over to an org on my `trusktr` account? I can verify both accounts via email, as they both are addresses in my domain `trusktr.io`.

Thanks!

**Comment by glasser** [comment]
Requests like this should go to contact@meteor.com!

**Comment by trusktr** [comment]
Thanks @glasser, I sent one!
