### ISSUE TITLE
Meteor.absoluteUrl does not strip query strings when appending paths

### ISSUE THREAD

**Issue by cuberoot** [meteor/meteor#3475]
I started using [xolvio:http-interceptor](https://github.com/xolvio/meteor-http-interceptor) to fake out external web sites in my application. However, the usage pattern uses Meteor.absoluteUrl() to append a relative path. This works fine, except in my Mocha tests in Velocity as the mirror ends up with a query string in the root url (e.g http://localhost:3000/?mocha=true). In this case, my use of absoluteUrl breaks as the relative path gets added after the query string. I would expect absoluteUrl to strip the query string.

I tried to create a simple test app, but http-interceptor has a dependency on the HTTP package that is failing in my small test app. I may have to log a bug against that.

**Comment by cuberoot** [comment]
Created [pull request 3476](https://github.com/meteor/meteor/pull/3476)

**Comment by glasser** [comment]
Oops, I saw the PR #3476 first.  Let's do discussion over there since that's where I started it.
