### ISSUE TITLE
TypeError: Cannot call method 'documentMatches' of undefined

### ISSUE THREAD

**Issue by wstucco** [meteor/meteor#3478]
After changing a file, Meteor restarted and gave me this error.
I tried to revert the changes, but it didn't work.
The strange thing is that I'm not using collections or mongodb in general in my project.

``` shell
W20150115-13:04:15.052(1)? (STDERR)
W20150115-13:04:15.054(1)? (STDERR) /Users/maks/.meteor/packages/meteor-tool/.1.0.38.14j6z57++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150115-13:04:15.054(1)? (STDERR)                         throw(ex);
W20150115-13:04:15.054(1)? (STDERR)                               ^
W20150115-13:04:15.106(1)? (STDERR) TypeError: Cannot call method 'documentMatches' of undefined
W20150115-13:04:15.106(1)? (STDERR)     at [object Object].LocalCollection.insert (packages/minimongo/minimongo.js:572:1)
W20150115-13:04:15.107(1)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/mongo/collection.js:574:1)
W20150115-13:04:15.107(1)? (STDERR)     at updateVersions (packages/autoupdate/autoupdate_server.js:97:1)
W20150115-13:04:15.107(1)? (STDERR)     at packages/autoupdate/autoupdate_server.js:161:1
W20150115-13:04:15.107(1)? (STDERR)     at /[working dir]/.meteor/local/build/programs/server/boot.js:182:5
```

**Comment by wstucco** [comment]
I tracked out the issue.
Turns out you can't override `Object.prototype`.
To replicate the problem you just add

```javascript
Object.prototype.a = function () {
};
```

to one of your server side packages and the error shows up.
using

```bash
$ meteor --version
Meteor 1.0.2.1
```

**Comment by glasser** [comment]
Good job tracking this down.  The most specific issue is fixed in #3511 but I'd rather have us fix ALL such issues in Meteor core before merging.  If somebody wants to extend that PR until it works, that would be great!

Note that most code should switch to using `_` iteration methods; however, in Blaze we avoid using Underscore and call Object.prototype.hasOwnProperty directly.

**Comment by wstucco** [comment]
I definitely agree with you that Object.prototype it's not a great style not a great way to add functionality to your app.   
I was in reality just aliasing some functions, to have a more "ruby like" syntax (I'm writing in Coffeescript and I much prefer snake case over camel).   
What I've done was this

```coffeescript
Object::to_s ?= Object::toString
```
That's why I didn't notice at first.   
I'm glad you're already working in this, thanks for the great work.

**Comment by hwillson** [comment]
This was fixed in https://github.com/meteor/meteor/commit/2bcb3893a7dd6e69b91005c57c6f21f0c087016f, so closing. Thanks for reporting this originally!
