### ISSUE TITLE
Using the install script with Curl results in a certificate verification failure

### ISSUE THREAD

**Issue by philp** [meteor/meteor#348]
I'm trying to install on Mac OS X 10.7.4 using the instructions on the example page.

However, I get a certificate verification failure:

```
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Even if I try to suppress Curl's verification using the -k switch, I still ge the same error — I'm guessing because there are subsequent downloads taking place.

I get a message telling me Meteor is installed, but it isn't ;)

**Comment by theduman** [comment]
https://stackoverflow.com/questions/17243032/curl-ca-cert-error-installing-meteor-on-mac/31275888#31275888

if you have ssl certificate issue that solved my problem.Ubuntu 14.04
