### ISSUE TITLE
Allow developers to create their own special directories

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#3482]
This issue stems from an idea from #3409, following a discussion initiated by @chetmurphy:

> Consider letting devs add their own conditional folders. For example, I would like to have different code for development and production configured via the command line or settings.

I have moved the topic here as I think it is off-topic from the initiate intent of the issue.

**Comment by stubailo** [comment]
This fits in a with a feature being tracked here: https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order

The idea is to replace the pre-defined special directories with a more functional "control file" that defines which directories do what and when.

Let's discuss ideas about this on the Trello card.
