### ISSUE TITLE
OS X binary packages break on Snow Leopard

### ISSUE THREAD

**Issue by fourseven** [meteor/meteor#3483]
I maintain `fourseven:scss` - which wraps node-sass. I've started using the `meteor admin get-machine os.osx.x86_64` etc commands, which are awesome, thank you!

However the binaries which get build by the OS X machine (and my own, in fact) don't work on 10.6.8 (Snow Leopard). 

a stack trace is [here](http://pastebin.com/y452BeDj) - and more details are at fourseven/meteor-scss#58

My question is: should I expect the build system to support 10.6.8? It'd be great to have an official line on what ABI compatibility is expected.

Thanks!

**Comment by mattlinares** [comment]
I'm keen to know about this one too! :)

**Comment by glasser** [comment]
I've fixed https://github.com/meteor/meteor/wiki/Supported-Platforms to show that we support 10.7 or newer.  (That's what the build machine we provide supports, intentionally.)

**Comment by fourseven** [comment]
Thanks!

**Comment by wuworkshop** [comment]
@glasser If that's the case for packages, should the [official Meteor website's install page](https://www.meteor.com/install) also get fixed? It currently says:

>The official installer supports Mac OS X 10.6 (Snow Leopard) and above, and Linux on x86 and x86_64 architectures.

**Comment by glasser** [comment]
Yup, fixed in git last night and deployed now that it's business hours.

**Comment by fourseven** [comment]
Nice work @glasser, cheers!
