### ISSUE TITLE
meteor installs wrong package version

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#3484]
It is 16th Jan

tap:i18n version in atmosphere is 1.3.1, came out three days ago
1.3 a week ago

when I call

meteor add tap:i18n 

it installs the 1.2.1 version from december

when I call 

meteor list

it shows tap:i18n* with the "update me" star

**Comment by glasser** [comment]
I couldn't reproduce with an empty app.  See https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor for advice on how to give a bug report that contains enough information for us to help you.

My guess is that some other package you have has dependencies that conflict with the new versions' dependencies.  If you run `meteor add tap:18n@1.3.1`, I suspect you'll get an error explaining where the conflict is.
