### ISSUE TITLE
package throws "Meteor._wrapAsync has been renamed to Meteor.wrapAsync"

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#3485]
One of my installed packages throws

=> Started proxy.                             
=> Started MongoDB.                           
I20150116-14:25:23.592(1)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Started your app.

How can I find out which package is throwing the error without uninstalling the step by step?

accounts-base                1.1.3  A user account system
accounts-password            1.0.5  Password support for accounts
aldeed:autoform              4.2.2  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2           2.3.1  Automatic validation of insert and update operations on the client and server.
cfs:gridfs                   0.0.27  GridFS storage adapter for CollectionFS
cfs:standard-packages        0.5.3  Filesystem for Meteor, collectionFS
chrismbeckett:fontawesome4   4.2.2  Scalable vector icons that can be customized with the power of CSS.
coffeescript                 1.0.5  Javascript dialect with fewer braces and semicolons
cryptoquick:stylus-multi     0.1.1  Stylus, packaged with Nib, Jeet, Rupture, and Axis
email                        1.0.5  Send email messages
ian:accounts-ui-bootstrap-3  1.2.17  Bootstrap-styled accounts-ui with multi-language support.
iron:router                  1.0.7  Routing specifically designed for Meteor
manuelschoebel:ms-seo        0.4.1  Easily config SEO for your routes
meteor-platform              1.2.1  Include a standard set of Meteor packages in your app
meteorhacks:npm              1.2.2  Use npm modules with your Meteor App
meteorhacks:ssr              2.1.2  Server Side Rendering for Meteor with Blaze
momentjs:moment              2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
npm-container                1.0.0+ Contains all your npm dependencies
raix:handlebar-helpers       0.2.4  Handlebar helpers
spiderable                   1.0.6  Makes the application crawlable to web spiders
tap:i18n                     1.0.3* A comprehensive internationalization solution for Meteor
tap:i18n-ui                  0.4.1  User interface for the tap-i18n package
twbs:bootstrap               3.3.1_2  Bootstrap (official): the most popular HTML/CSS/JS framework for responsive, mobile first projects
underscore                   1.0.2  Collection of small helpers: _.map, _.each, ...
vazco:maps                   0.0.1  Google Maps wrapper with gmaps.js plugin
yogiben:admin                1.0.9  A complete admin dashboard solution
yogiben:autoform-file        0.1.7  Upload and manage files easily with AutoForm and CollectionFS

**Comment by mitar** [comment]
`grep -r _wrapAsync .`

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. Good luck!

(For the record, your app should work fine even with this warning.)
