### ISSUE TITLE
Cannot install system packages on build servers

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3491]
To compile [pdf.js](https://github.com/peerlibrary/meteor-pdf.js) package, I have to install some system packages. It seems logged in user does not have sudo access?

**Comment by glasser** [comment]
If you want to do this, you can use your own build machines (running a similar version of the OS).

That said, though, does `pdf.js` actually statically link those system packages, or will you end up with a Meteor package that also doesn't work unless you have system packages on your deploy machine?  The goal of the Meteor binary package distribution system is that packages should be self-contained. So it sounds like a better approach would be trying to get the upstream package to have an option to its build system that allows it to statically link in a non-globally-installed version of its native dependencies.

(We actually don't think that it should be easy to accidentally build packages that require system libraries to be installed, so I think the current behavior is reasonable.)

**Comment by mitar** [comment]
The problem is in [node-canvas](https://github.com/Automattic/node-canvas) package. That is the one which has to be compiled. So I still don't get how does one compile use a node package which requires system dependencies? Currently, you do not provide a way for package to be compiled on the user's computer. And you want to make it hard to be compiled using system libraries. But how does one then do that?

I also don't get the argument that I would need my own build machine? I agree that it should be statically compiled, but this could be checked by your build system and publish of such package could fail. But compiling using system packages is a normal process.

BTW, Meteor packaging also lacks any way for me to hook into it. For example, to install non-system dependencies so that it works.

And why having a root access on the build system is forbidden? It is all virtualized anyway.
