### ISSUE TITLE
No way to search for all your packages which are missing architecture builds

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3493]
So I cannot verify if there is a package I published which would require that I also compile it for other platforms. This means that there might be packages which fail for users and I don't know that.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This sounds like a useful feature to have, maybe under `admin`.  All the data needed is in the local sqlite DB.  PRs welcome.

**Comment by mitar** [comment]
Feature requests are possible! What a great new year's present! :-)

**Comment by ekatek** [comment]
By the way -- in the interim, you can also script this, since --ejson output of `meteor show` will tell you what architectures are available for versions of your package. (And `meteor search` also takes an --ejson flag for `ejson` output).

That said, what @glasser says. Pull requests encouraged!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=No%20way%20to%20search%20for%20all%20your%20packages%20which%20are%20missing%20architecture%20builds&body=Migrated%20from:%20meteor/meteor%233493) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
