### ISSUE TITLE
[Blaze] {{#with}} adds text node before/after contents

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3501]
When using `{{#with}}` the tag adds empty text nodes before and after contents. The text nodes go away when removing the `{{#with}}`

**Comment by avital** [comment]
Yes, that happens when the contents of the `{{#with}}` block are empty. Does this cause problems?

**Comment by raix** [comment]
Yep, i had some code iterating over dom nodes, when adding "with" the code "broke" cause text nodes were added unexpected. If the html is inline "with" it's not adding text nodes, but it gets ugyldig/hard to read.
 I guess if in need of more arguments: it creates the overhead of appending two dom nodes - this is still a costly operation on older android.
If i wanted text nodes it would be natural to add Line breaks.
