### ISSUE TITLE
Cannot read property 'ServiceConfiguration' of undefined (Production)

### ISSUE THREAD

**Issue by Batistleman** [meteor/meteor#3506]
I get this error when deploying to my production server. (I don't have this when in development, I can reproduce the problem locally when running with the --production flag

    Error: Cannot read property 'ServiceConfiguration' of undefined
    TypeError: Cannot read property 'ServiceConfiguration' of undefined
        at http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:61:1630
        at o (http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:3:4908)
        at HTMLDocument.o (http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:3:4912)

    > Before: 233ms (diff: 233ms)
        at http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:3:4954
        at http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:3:5435
        at http://localhost:3000/7eeb16521b87637fbde8aa98cef5d22f0f3a69bb.js:3:7745

    > Before: 455ms (diff: 222ms)
        at Array.forEach (native)

I've read it can be due to a package not fit for 1.0.2.1, but I can't figure out how to debug what's going on...

    accounts-password            1.0.5  Password support for accounts
	alanning:roles               1.2.13  Role-based authorization
	aldeed:autoform              4.2.2  Easily create forms with automatic insert and update...
	aldeed:collection2           2.3.1  Automatic validation of insert and update operations...
	aldeed:simple-schema         1.3.0  A simple schema validation object with reactivity. U...
	autoupdate                   1.1.4  Update the client when new client code is available
	cfs:filesystem               0.1.1  Filesystem storage adapter for CollectionFS
	cfs:s3                       0.1.1  Amazon Web Services S3 storage adapter for CollectionFS
	cfs:standard-packages        0.5.3  Filesystem for Meteor, collectionFS
	chrismbeckett:fontawesome4   4.2.2  Scalable vector icons that can be customized with th...
	dburles:collection-helpers   1.0.2  Transform your collections with helpers that you define
	iron:router                  1.0.7  Routing specifically designed for Meteor
	jquery                       1.0.2  Manipulate the DOM using CSS selectors
	less                         1.0.12  The dynamic stylesheet language
	mdg:camera                   1.1.3  Photos with one function call on desktop and mobile.
	mdg:geolocation              1.0.2  Provides reactive geolocation on desktop and mobile.
	meteorhacks:fast-render      2.2.0  Render you app even before the DDP connection comes ...
	meteorhacks:npm              1.2.2  Use npm modules with your Meteor App
	meteorhacks:zones            1.4.0  Zone.Js integration for meteor
	mizzao:bootstrap-3           3.3.1_1  HTML, CSS, and JS framework for developing respons...
	mrt:accounts-ui-bootstrap-3  0.3.3  Bootstrap styled version of login widgets
	npm-container                1.0.0+ Contains all your npm dependencies
	standard-app-packages        1.0.4  Moved to meteor-platform
	underscore                   1.0.2  Collection of small helpers: _.map, _.each, ...
	zimme:iron-router-active     1.0.1  Active route/path template helpers for iron:router

	+ These packages are built locally from source.

Running meteor 1.0.2.1 and node 1.0.35

**Comment by stubailo** [comment]
Try adding the `service-configuration` package:

```
meteor add service-configuration
```

Then see if this still happens.

**Comment by Batistleman** [comment]
yes, that seems to remove the error, thanks! 

How can I find out what package was depending on it?

**Comment by stubailo** [comment]
I think this is actually a bug from not checking for undefined in: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L151

Not sure why it doesn't happen in development though?

**Comment by estark37** [comment]
@stubailo: I don't think we have to check for undefined there -- accounts-base depends on service-configuration, so there's no reason it shouldn't be defined.

**Comment by avital** [comment]
As for why it broke on production and not on development -- my guess would be that in production since we concatenate all files, if there's an error at the top-level of the concatenated javascript then rest of the code no longer executes, whereas in development it only halts loading of the specific javascript file with the error.

**Comment by avital** [comment]
(That is -- I think in development there was also an exception but it didn't cause the app to fail to load)

**Comment by avital** [comment]
@estark37 The accounts-base -> service-configuration dependency is unordered

**Comment by glasser** [comment]
This could be a bug in unordered package loading. But this read is inside `startup` so should occur after all packages are loaded, and that should include unordered packages.  I think maybe this error isn't coming from accounts-base.  Also, I'm confused about why accounts-base isn't listed on your list.

Really, we need an actual reproduction instead of just some snippets.  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by rjsmith** [comment]
+1 I have just hit this exact issue whilst trying to deploy a project to meteor.com for the first time, after successfully running it on my local development server for a couple of months.
I then was able to exactly reproduce the issue by runing the project locally using `meteor run --production`

In my case, the client-side code was missing the `service-configuration` and `spacebars` packages. Once I had explicitly added them to my project, everything worked OK. I have just successfully deployed to meteor.com

This was my project's `.meteor/packages` file when I hit the errors:

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
accounts-password
aslagle:reactive-table@0.6.9
ian:accounts-ui-bootstrap-3@1.2.33
iron:router
less
linto:fontawesome
nemo64:bootstrap
pahans:reactive-modal@1.0.2
sacha:spin
aldeed:simple-schema
plangy
workman:x-editable-reactive-template
reywood:publish-composite
froala
froala-reactive
meteorhacks:npm
browser-policy

momentjs:moment
natestrauser:select2
zimme:select2-bootstrap3-css
tmeasday:presence
ctjp:meteor-bootstrap-switch
mizzao:jquery-ui
dsyko:jquery-ui-touch-punch
meteorhacks:subs-manager
velocity:html-reporter
reactive-var

d3js:d3
plangy-diagram


npm-container
datatable
sanjo:jasmine@0.12.4

msavin:mongoinspector
sticklr
velocity-html-reporter-css
amcharts
meteorhacks:kadira
meteorhacks:zones
matb33:collection-hooks
```

And this is the now-working `packages` file:

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
accounts-password
aslagle:reactive-table@0.6.9
ian:accounts-ui-bootstrap-3@1.2.33
iron:router
less
linto:fontawesome
nemo64:bootstrap
pahans:reactive-modal@1.0.2
sacha:spin
aldeed:simple-schema
plangy
workman:x-editable-reactive-template
reywood:publish-composite
froala
froala-reactive
meteorhacks:npm
browser-policy

momentjs:moment
natestrauser:select2
zimme:select2-bootstrap3-css
tmeasday:presence
ctjp:meteor-bootstrap-switch
mizzao:jquery-ui
dsyko:jquery-ui-touch-punch
meteorhacks:subs-manager
velocity:html-reporter
reactive-var

d3js:d3
plangy-diagram


npm-container
datatable
sanjo:jasmine@0.12.4

msavin:mongoinspector
sticklr
velocity-html-reporter-css
amcharts
meteorhacks:kadira
meteorhacks:zones
matb33:collection-hooks
service-configuration
spacebars
```

**Comment by glasser** [comment]
That is still not a useful reproduction. Please read the link I posted above.

**Comment by tomyo** [comment]
First I removed mrt:accounts-ui-bootstrap-3 and helped a bit.
Finally I got it fixed by adding accounts-ui package too.
I should mention that I'm not using accounts-ui in my project (but using accounts-password).

**Comment by llaine** [comment]
Hi,
while trying to deploy on production I get this error and the hints from @stubailo didn't help me at all.

Here are my packages : 

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
accounts-password
accounts-ui
multiply:iron-router-progress
meteorhacks:kadira
less
fortawesome:fontawesome
sacha:spin
email
gadicohen:flag-webicons
underscore
http
meteorhacks:npm
comerc:autoform-placecomplete
mrt:jquery-ui
mrt:smart-publish
nemo64:bootstrap-data
mrt:fancybox
momentjs:moment
monbro:mongodb-mapreduce-aggregation
manuelschoebel:ms-seo
mrt:flash-messages
risul:accounting
reywood:iron-router-ga
spiderable
gadicohen:sitemaps
nemo64:bootstrap
mrt:imagemagick
npm-container
iron:router
service-configuration
```

**Comment by micktaiwan** [comment]
I'm reproducing this same error and I don't know how to help.

**Comment by micktaiwan** [comment]
In my case, was my code firing a exception. Was happy in dev, not in prod. Catching the exception or then just correcting the mistake fixed the issue.

**Comment by AdamBrodzinski** [comment]
+1 fixing an exception thrown early by FlowRouter fixed this without adding `service-configuration`

**Comment by digz6666** [comment]
Throw this error when I include highcharts.js and exporting.js.
It was running fine on my localhost even though it's throwing Highcharts not found, but on server it throws the error. So I renamed exporting,js > highcharts_exporting.js and the issue has gone.

By the way I use meteor-up to deploy it to my server.

**Comment by bompi88** [comment]
FYI I did get this issue if I turned on Mirage in Cloudflare. Make sure this is off 👍

**Comment by avalanche1** [comment]
My app was throwing an exception in dev mode. And `Cannot read property 'ServiceConfiguration' of undefined ` in production.
When I've fixed the error, production app began working correctly.

**Comment by rajpa** [comment]
I am getting this error now and have no clue how to fix it. Not sure how to detect any exception in the app's code - the console is not showing any errors.

The error is:

TypeError: Package['service-configuration'] is undefined
I<.node_modules.meteor["accounts-base"]["accounts_common.js

**Comment by abernix** [comment]
Meteor Docs on `service-configuration`:
> http://docs.meteor.com/api/accounts.html#service-configuration

You probably need to run:

    meteor add service-configuration

**Comment by rajpa** [comment]
Done that already - however I have only a basic username/email/password setup. So I haven't configured anything for the ServiceConfiguration object...

**Comment by abernix** [comment]
@rajpa In that case, you should open a new issue with a link to a Meteor project on GitHub which shows this problem, ensure you are using the latest version of Meteor and provide the full error with the stack-trace not cut off.

I would expect the usage of `accounts-password` to be all you need however this particular issue is very old and very closed.

**Comment by rajpa** [comment]
Thanks @abernix .. accounts-password is also an included package.. 

I moved from bootstrap to materialize and I am simply unable to run the application now. 

These are the errors:

be6a3bc….js?meteor_js_resource=true:242 Uncaught TypeError: Cannot read property 'easing' of undefined(anonymous function) @ be6a3bc….js?meteor_js_resource=true:242(anonymous function) @ be6a3bc….js?meteor_js_resource=true:246(anonymous function) @ be6a3bc….js?meteor_js_resource=true:246
be6a3bc….js?meteor_js_resource=true:102 Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined(anonymous function) @ be6a3bc….js?meteor_js_resource=true:102s @ be6a3bc….js?meteor_js_resource=true:3u @ be6a3bc….js?meteor_js_resource=true:3

This is my package list:
accounts-base 1.2.8* A user acc...
accounts-password 1.1.13* Password ...
accounts-ui 1.1.9 Simple tem...
alanning:roles 1.2.15 Authoriza...
aldeed:autoform 5.8.1 Easily cre...
aldeed:autoform-bs-datetimepicker 1.0.6 Custom boo...
aldeed:autoform-select2 2.0.2 Custom sel...
aldeed:collection2 2.9.1 Automatic ...
aldeed:schema-index 1.0.1 Control so...
aslagle:reactive-table 0.8.33* A reactiv...
blaze-html-templates 1.0.4 Compile HT...
chart:chart 1.0.1-beta.4 Cha...
chriswessels:glyphicons-halflings 2.1.0 This simpl...
cordova:cordova-plugin-inappbrowser 0.5.4
cordova:de.appplant.cordova.plugin.local-notification 0.8.4
dburles:collection-helpers 1.0.4 Transform ...
dispatch:deep-link 4.0.4 Handle dee...
ecmascript 0.4.8* Compiler p...
edgee:slingshot 0.7.1 Directly p...
es5-shim 4.5.13* Shims and...
fastclick 1.0.12 Faster to...
iron:router 1.0.13 Routing s...
jquery 1.11.9 Manipulat...
materialize:materialize 0.97.7 Materiali...
meteor-base 1.0.4 Packages t...
meteorhacks:kadira 2.30.0 Performan...
mizzao:autocomplete 0.5.1 Client/ser...
mobile-experience 1.0.4 Packages f...
momentjs:moment 2.14.4 Moment.js...
mongo 1.1.9_1* Adaptor ...
mpowaga:autoform-autocomplete 0.0.2 Autocomple...
mrt:jquery-easing 1.3.0 GSGD's jQu...
mrt:moment-timezone 0.2.1 Timezone s...
natestrauser:select2 4.0.2 Select2 is...
raix:handlebar-helpers 0.2.5 Handlebar ...
raix:push 3.0.2 Isomorphic...
random 1.0.10 Random nu...
reactive-var 1.0.10 Reactive ...
reywood:publish-composite 1.4.2 Publish a ...
sacha:spin 2.3.1 Simple spi...
service-configuration 1.0.10 Manage th...
session 1.1.6 Session va...
standard-minifier-css 1.0.8* Standard c...
standard-minifier-js 1.0.8* Standard j...
timbrandin:autoform-slingshot 1.1.2 File uploa...
tracker 1.0.15* Dependenc...
tsega:bootstrap3-datetimepicker 3.1.3_3* Bootstra...
udondan:slick 1.3.11_1 the las...
underscore 1.0.9 Collection...
utilities:state-transitions 0.1.3 A simplifi...
yogiben:admin 1.2.4* A complete...

**Comment by vladfr** [comment]
Hi, I am on Meteor 1.4.0.1 and can easily reproduce this on my local:

```
$> meteor create todos-react
$> meteor add service-configuration accounts-password accounts-facebook
```

```
# server/main.js
import { Meteor } from 'meteor/meteor';
import ServiceConfiguration from 'meteor/service-configuration'

Meteor.startup(() => {
  // code to run on server at startup
ServiceConfiguration.configurations.upsert(
    { service: "facebook" },
    {
        $set: {
            clientId: "myid",
            secret: "mysecret",
            loginStyle: "popup",
        }
    }
);
});
```

```
$> meteor
[[[[[ ~/Projects/meteor/todos-react ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160805-17:29:43.204(3)? (STDERR) /Users/vlad/.meteor/packages/meteor-tool/.1.4.0-1.b6dmzv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160805-17:29:43.268(3)? (STDERR) 						throw(ex);
W20160805-17:29:43.269(3)? (STDERR) 						^
W20160805-17:29:43.269(3)? (STDERR)
W20160805-17:29:43.269(3)? (STDERR) TypeError: Cannot read property 'upsert' of undefined
W20160805-17:29:43.270(3)? (STDERR)     at server/main.js:6:1
W20160805-17:29:43.270(3)? (STDERR)     at /Users/vlad/Projects/meteor/todos-react/.meteor/local/build/programs/server/boot.js:304:5
=> Exited with code: 1
```

**Comment by vladfr** [comment]
That's weird, I added 
`ServiceConfiguration.configurations = new Mongo.Collection('meteor.loginServiceConfiguration');` and I got it to start, but it wouldn't actually init the config (it's a different collection name in the package). Now, I removed this line, and it seems to work. Weird. Anything to do to init this collection in the DB?

**Comment by SPodjasek** [comment]
As in @micktaiwan & @AdamBrodzinski case uncaught exception (in my case fired in Bootstrap Tooltips) was causing all problems. 
Exactly as @avital suggested, exception stopped rest of application code from executing properly, giving totally unrelated errors.

**Comment by nolandg** [comment]
My cause of this error was improperly importing `ServiceConfiguration`. It should be:

```
  import { Meteor } from 'meteor/meteor';
  import { ServiceConfiguration } from 'meteor/service-configuration';

  ServiceConfiguration.configurations.upsert(
    { service: 'google' },
    {
      $set: {
        clientId: Meteor.settings.private.oauth.google.id,
        loginStyle: 'popup',
        secret: Meteor.settings.private.oauth.google.secret,
      },
    }
  );
```

**Comment by RobAWilkinson** [comment]
Careful, make sure that you have no other errors when running without `--production` if you do, they will trickle up and show as an error here. Fix them and then come back here.

**Comment by joaoeffting** [comment]
@RobAWilkinson Tks ... I remove all my console "warnings as errors" and then it worked. If I could I would pay you a beer :1st_place_medal:

**Comment by xxxshppee7xxx** [comment]
i have a problem here and tried every thing to fix it but still dont work:
this is my main.ts :

import { Meteor } from 'meteor/meteor';
    import { ServiceConfiguration } from 'meteor/service-configuration';

    Meteor.startup(() => {
         ServiceConfiguration.configurations.upsert(
                  { service: 'facebook' },
         {
           $set: {
                 appId: '1968736223170817',
                 loginStyle: 'redirect',
                 secret: '1118d00ec711f369f8f4d66704576d2d',
           },
         }
       );
     });
and this is the bug : 
cannot find module 'meteor/service-configuration'
can you answer me plz ??

**Comment by richardgsands** [comment]
I had this problem, and fixed it by getting rid of console errors that were present in the development build.

Think the reason my development build was working, but production build wasn't, is because of JS files being concatenated for production, meaning that this error was preventing subsequent code from running.

**So, motto is, make sure there are no errors being thrown, as they will lead to more issues when concatenating file for production!**

(The package in question was autoform-hint, but don't think that is particularly relevant.)
