### ISSUE TITLE
 Unexpected Doctype error for html files in `/private` directory.

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#3507]
Meteor throws `Error: Unexpected Doctype` for files in the `/private` directory, even though they are not going to be used as templates/ignored unless acquired by `Assets.getText`.

This is during the build process.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by reustle** [comment]
Having the same issue. Would it cause issues to exclude `/private` from the doctype check?

**Comment by glasser** [comment]
It is my understanding that this code doesn't run on `private`, which is why I requested a reproduction.

**Comment by jacobjuul** [comment]
having the same issue

**Comment by abernix** [comment]
You can likely work around this by renaming the file to `something.html.template`, or similar.

**Comment by SierraGolf** [comment]
same issue, renaming does not help.
