### ISSUE TITLE
Allow Plugin.registerSourceHandler() for .js source files

### ISSUE THREAD

**Issue by meonkeys** [meteor/meteor#3508]
(Feature request / idea)

Provide a way to hook into the development build process of plain old JavaScript (.js) files in a Meteor application. For example, I'd like to [lint files with JSLint, JSHint, or similar upon file change](https://groups.google.com/forum/#!msg/meteor-talk/f6uJL8Dxfnk/YoXq40LvX9kJ).

Currently, `Plugin.registerSourceHandler()` disallows adding handlers for `.js` files.

**Comment by stubailo** [comment]
This is a good idea! I've been interested in improving the build process for a while. I think this ties into the general feature of allowing multiple source handlers for a single extension.

**Comment by yauh** [comment]
+1 for the this
Also, I recently tried putting some `.js` code into public to dynamically load certain libraries for specific paths only. Although it may not be very elegant it would work but requires an extension of the current `.js` handler.

**Comment by yauh** [comment]
Some interesting perspective on that (plus a pretty good example that fragmentation of the community is very annoying):
https://github.com/MeteorCommunity/discussions/issues/51#issuecomment-67673611

**Comment by reneras** [comment]
Hi @stubailo I made a head start with this over here: https://github.com/reneras/meteor/commit/b45040d37015becd86ee886960c3975f2fae82fa

I went ahead and made Plugin.registerSourceHandler ( and it's dependants ) able to store multiple source handlers in an Array. And right now it seems like there needs to be some architecture decision making to be done.

When I run "meteor publish --existing-version" in the meteor-tool package I get a bunch of handlers without a "pkgName" and ( correct me if I'm wrong ) seems like a lot of internal .js files get registered multiple times. It would be great if you could point me in the right direction so I can proceed! Thanks.

**Comment by matteodem** [comment]
+1

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

There's some previous discussion at #1207.  My personal opinion is we should probably just do this at some point, though it's mostly useful for things like linting and not for post-processing (specifically, the obvious approach would NOT allow you to set a handler that runs on all JavaScript code including those produced by plugins like coffeescript and templating).

**Comment by steve8708** [comment]
Major +1 - the lack of an option to even lint feels like a big constraint when coming from the world of gulp and grunt - especially when considering using meteor for real production projects with teams of engineers working on them

Obviously the meteor build system is unique and has major advantages that also make this difficult (e.g. do you set an arbitrary priority for your build step if it works against the same file extension as another package, etc) but intermediary steps

I've looked through some prior conversations on the matter and this looked like the most recently discussed are so thought I'd throw my 2 center in here ;) 

Some examples
* js, coffee, scss, html linting (obviously)
* i18n translation extraction (e.g. [grunt-angular-translate](https://github.com/angular-translate/grunt-angular-translate) I'm not sure how I could live without). This simply would need to add a passive step to read html and then write a json file with translation keys 
* auto run unit tests when js source files change 
* injectors - e.g. part of my typical gulp build workflow is to [inject](https://github.com/klei/gulp-inject) css dependencies like so -
```
@import 'some-depenencty';

// inject: client/styles/**
@import 'this/is/automatically/inserted/by/the/build/so/you/dont/have/to/maintain/tediously/by/hand';
// endinject
```

While that last example might be a bit tricky, at least it's an example of some nice conveniences you can get from a build system that allows multiple source handlers :) 

For the time being I'm thinking of just adding gulp to my project and having to run it as a separate process while developing :cry:, with a meteor package that spawns a gulp watch child process in development mode and outputs results (e.g. lint fails) to the console, or writing a custom plugin that starts up when the server does and manually watches files and run lints/tests/tasks on them (ideally registered by other packages).

Happy to hear any other suggestions for workarounds for simple file watching build takss (lint, extract translations, run tests, inject, etc)

**Comment by steve8708** [comment]
Also per #1207 I think 'load order' floats would make a lot of sense. 

E.g. like angular directives - similarly they are not meant to be aware of what other directives could be on an element, so they use 'priority' numbers to say if they should be handled earlier or later in the processing of a dom element

**Comment by steve8708** [comment]
One more bit 2 cents :) 

per #1207 I think 'load order' floats would make a lot of sense. 

E.g. like angular directives - similarly they are not meant to be aware of what other directives could be on an element, so they use 'priority' numbers to say if they should be handled earlier or later in the processing of a dom element

**Comment by steve8708** [comment]
Just saw one more good example for this here Urigo/angular-meteor#109 which is [ng-annotate](https://github.com/olov/ng-annotate) which allows angular developers to write using a simpler (but minification unsafe) dependency injection format and ng-annotate, before minification, converts the contents of our js files to the more verbose but minifcation safe format

**Comment by steve8708** [comment]
Oh and don't forget the discussion regarding needing this for ASTs and even more features here MeteorCommunity/discussions#51 :)

**Comment by steve8708** [comment]
In case anyone is interested for now I'm working on a meteor package that lints and watches files on the server when in development mode. I'll post a link when it's ready to be published. It gets the job done for now (and does other things like scss @import injection from glob patterns like 'client/**') but it isn't part of a real build and would never integrate with a CI server, for example

![screen shot 2015-02-16 at 11 40 25 pm](https://cloud.githubusercontent.com/assets/844291/6224888/2b53c640-b638-11e4-8cb2-f5ad2b644ef6.png)

**Comment by steve8708** [comment]
One last suggestion - just having a Plugin.observeSource() or similar for passive tasks such as linting that don't actually modify any files or need to block any other steps 

It seems like the discussion of having the perfect solution for registerSourceHandler() has been going on for quite some time. But perhaps there is an intermediary solution like this to let us keep developing packages that can observe js/css/html files before having the perfect final answer fully solved

I'd be happy to create a PR if this is something anyone else would find to be a useful solution for now

**Comment by yauh** [comment]
I know I originally voted for this, but the linting use case is not very obvious to me. Can someone explain where the gains are on having linting at the server console? It feels we're taking a road that is not less but more work for developers eventually.

I do my linting either inside the editor (*Storm or Atom), so I can fix problems right away, or I use a CI server to generate a report. I fail to see the exact benefit of having lint results on the server console. It just seem too tedious to go back to the editor and find the occurrence, I'd rather use a proper editor that shows me (stylistic) errors right there in the edit window in the first place.

Now the use case about using some shorthand that gets extended or extracting l18n strings seems much stronger then the linting/stylistic logging, if you ask me. 
That said, I am still all in favor of having multiple build steps for the same file extension, e.g. *.js.

**Comment by Slava** [comment]
@steve8708 I am in a brainstorming phase on how to improve the build tool. I would appreciate your comments on [my wip proposal](https://meteor.hackpad.com/Proposal-streams-based-build-tool-kbqhWoYYfKR).

**Comment by steve8708** [comment]
@Slava a stream based build for meteor, that would be AMAZING, will take a look and add comments soon!

**Comment by zimme** [comment]
@yauh: With linting I'm thinking that if linting fails the build should fail and you should get a informative message so that you can fix it, once fixed the build restarts and is successful.

But one could argue that this should be setup as pre-commit hooks making sure that you only commit code which passes linting.

I see the use of linting code on bundle or deploy making sure the code is linted.

**Comment by meonkeys** [comment]
@zimme, @yauh mentioned other ways to get at the same information, and in a more relevant place (the editor - exactly where you can fix it).

@yauh, I agree that in-editor and CI server covers many cases, but I'm also always watching my server console during development and I like seeing the issue in both places. It's also fair to assume that some people don't have CI and/or use an editor that doesn't support inline error displays.

**Comment by yauh** [comment]
You are right @meonkeys and @zimme - All I care about is that the linting aspect is only a minor part of this feature request and I suggest we don't limit it to this because it gets very hard to argue the importance of this feature if all we ask for is linting.

Linting before bundling for production seems legit, as long as we're talking about a package and possibly bypassing warnings if I need to make a quick test deployment :)

**Comment by arturadib** [comment]
In addition to linting, this is also blocking one's ability to use a transpiler like Babel on the `.js` extension.

Any solution in sight?

**Comment by jedwards1211** [comment]
+1, I want to write a basic plugin to load the js and source map of a bundle output by Webpack...Meteor will load the js automatically, but not the source map, so I'm quite disappointed

**Comment by jedwards1211** [comment]
@steve8708 after failing to grok stream-based build systems very well I came to love Webpack's loader-based approach.  It's a lot easier to reason about and I haven't run into any limitations with it yet.

**Comment by glasser** [comment]
On devel, we've solved this in two different ways.

@slava has implemented a new build plugin API, registerLinter, which is explicitly designed for implementing lingers. We think that linters are semantically different than compilers and giving them their own API with special handling is the way to go.

We have also deprecated regosterSourceHandler in favor of a more powerful registerCompiler. One feature of registerCompiler is that you can use it to override the default handler for *.js; @benjamn's new ecmascript package (which implements ES2015) does exactly that.

**Comment by MichaelJCole** [comment]
Hey, sorry, I'm new here.  How do I use a linter with Meteor?

https://github.com/raix/Meteor-jshint

brought me here but not sure how to actually use this...

**Comment by Slava** [comment]
@MichaelJCole using the Build Plugins API since Meteor 1.2 (unreleased yet): https://github.com/meteor/meteor/wiki/Build-Plugins-API

**Comment by MichaelJCole** [comment]
thnx!
