### ISSUE TITLE
Meteor.com: WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by obvio171** [meteor/meteor#3509]
Using meteor.com hosting, I frequently get a "Loading..." screen that hangs forever and I see this in the network console:

    WebSocket is closed before the connection is established

This has happened to users in Chrome, Firefox and Safari, on OSX, Linux and Windows. 

I've tried disabling websockets (can't set environment variables on meteor.com, so I tried [something different](http://stackoverflow.com/questions/28052267/how-to-disable-websockets-on-meteor-com-hosting)), but that didn't work either. Any ideas on how to fix this? Thanks!

**Comment by glasser** [comment]
Can you show an example?  I don't know which loading screen you mean.  Is it your app's loading screen or the Meteor one?

**Comment by obvio171** [comment]
It's some basic template I passed to iron router as `loadingTemplate`. It seems like it hangs on waiting for the subscription forever (in the route's `waitOn` function) and nothing happens. It's a damn heisenbug though, so I haven't figured out exactly how to reproduce it. 

The code is all here: https://github.com/obvio171/rideboard

Sometimes it hangs, then I go to a different route (like /profile, different set of subscriptions), come back to the route where I was before and it works. It seems like it tries to use websockets, it doesn't work, but then it never falls back to the next thing (long polling, I guess) like it's supposed to.

**Comment by glasser** [comment]
How are you hosting your app?  This sounds like it might have something to do with your hosting.

**Comment by obvio171** [comment]
I'm hosting it at Meteor.com.

**Comment by glasser** [comment]
A specific URL would help with debugging.

**Comment by obvio171** [comment]
Hi David, I've sent you a test password at glasser@davidglasser.net. Thanks for helping!

**Comment by glasser** [comment]
I took a look at your app and I agree that it seems to get stuck in "Loading" when you log in.  Unfortunately we really don't have the bandwidth to debug every Meteor user's app as part of our GitHub issue triage process.  The good news is that you can probably get help from other Meteor users by asking questions on StackOverflow or the meteor-talk mailing list, not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. (I appreciate that you showed both your source and the deployed version, but it helps to put some effort into deleting things from a copy of your app until it is the smallest possible app that still shows the issue.)  Good luck!

By the way I didn't notice the error message you said, but I did see this warning in my console: "Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?"  Maybe this is relevant? It comes from Iron Router I think.

**Comment by gwendall** [comment]
+1. Having the same issue whilst everything works fine locally.

**Comment by nspangler** [comment]
+1 Same Issue

**Comment by liaujianjie** [comment]
+1 getting the same problem

**Comment by sungwoncho** [comment]
+1 seeing the same error except I am hosting my app on Ubuntu 14.04 on Digital Ocean

**Comment by sebakerckhof** [comment]
+1

**Comment by LDubya** [comment]
+1 I'm getting this websocket error on the console for iPhone's Safari (viewing the iPhone Safari console connected to desktop). I've only tested it on localhost. It happens when I refresh the page.

WebSocket connection to 'ws://172.20.10.2:3000/sockjs/256/x208zj5e/websocket' failed: WebSocket is closed before the connection is established.

**Comment by YalaHub** [comment]
+1 Same issue

**Comment by elie222** [comment]
+1 just saw this issue. Also Ubuntu 14.04 on Digital Ocean

**Comment by okpatil4u** [comment]
+1 Ubuntu 14.04 Digital Ocean Nginx

**Comment by stefanagapie** [comment]
+1 Same issue

**Comment by vhuerta** [comment]
+1

**Comment by massimosgrelli** [comment]
I'm having the same issue on *.meteor.com
WebSocket connection to 'wss://ddp--5143-<myapp here>.meteor.com/sockjs/505/40qfix89/websocket' failed: WebSocket is closed before the connection is established.

I guess it is a timeout issue connected to *.meteor.com workload. Locally on my dev machine I don't have any error.

**Comment by cddin** [comment]
+1

**Comment by jackcasey** [comment]
:+1: Just deleted and re-uploaded an old to the free meteor hosting and it is now doing this over and over.

**Comment by enricofoschi** [comment]
same issue on our live app, https://4scotty.com, and locally

**Comment by Leekao** [comment]
+1 same issue.

**Comment by tothradoslav** [comment]
+1 same issue

**Comment by LDubya** [comment]
this issue has existed for well over a year without a fix

**Comment by dan335** [comment]
Getting this also.

**Comment by FGM** [comment]
Just got this issue after migrating to Galaxy in the wake of the meteor.com termination announcement. This is on http://reactodos.audean.com (or https://reactodos.audean.com if you accept the CACert certificate).

**Comment by lukiies** [comment]
+1 same WebSocket connection to ... failed: WebSocket is closed before the connection is established.
private server on debian/openvz etc..  
only from one PC with slower internet; from everything else even my cellphone with weak carrier works fine ; dedicated server located in slovakia ; localy works good
(of course - this makes webapp working incredibly slower... )

where can we find solution?

**Comment by pmwisdom** [comment]
I've also been experiencing this issue on galaxy. Only happens on mobile devices. It doesn't happen all the time, the application can run fine for hours and then suddenly all data connections are lost until I restart the application.

**Comment by lukiies** [comment]
Hi,
i have news in this case.
Today i’ve used once again team viewer with this ‚wrong’ PC and i can’t catch such as problem any more.
There’s another question - site works just fine (response time <1sec) from every known computer and internet point - but from THIS PC. Now i’ve tested that from many computer from the same localization (which is one from cities in Poland). Server is in data center in Bratislava. There’s no problem to work with site from any place besides the one city (which is Radom). Site works good - but so slowly that You can’t imagine. If You test speediest.net - everything’s fine with internet. Now i begin to find internet provider - which is in every wrong working places Orange.
But if i move site and database into my mac and share this instance to those wrong-working PC’s - everything suddenly works absolutely fine.

Can anybody explain me what’s going on? If like to think that i have full control on my applications… and it’s not correct in this way.

pozdrawiam, Łukasz Robak

**Comment by dtruel** [comment]
I can't get even a clean project to work! I get this error on windows 7

```
WebSocket connection to 'ws://127.0.0.1:3000/sockjs/421/7qvrk9bg/websocket' failed: Error during WebSocket handshake: Invalid status line
```

**Comment by dtruel** [comment]
Similar issue:

https://github.com/meteor/meteor/issues/1140

**Comment by ElegantSudo** [comment]
I still have this issue...

**Comment by theodorDiaconu** [comment]
I still have this issue also.

**Comment by dtruel** [comment]
A great workaround is enabling Windows Subsytem for Linux for windows 10.  Then you can run meteor from ubuntu bash in Windows.  It also makes Meteor run about 5x faster.

**Comment by AlexCollin** [comment]
I still have this issue also.

**Comment by grundmanise** [comment]
Same issue cordova + meteor.

**Comment by B-raw** [comment]
I've just started experiencing this issue out of nowhere.

Meteor + heroku using accounts-base

**Comment by valorloff** [comment]
same issue on Google Compute Engine,

**Comment by eliezedeck** [comment]
+1 ... this is madness.

**Comment by musemega** [comment]
Any resolution here?  (on nginx/passenger/ubuntu 14.04)  Getting critical.

**Comment by eliezedeck** [comment]
Guys, I think this might **not be a problem with Meteor itself**.

I have used Caddy server, and I think there is a weird timeout feature in Caddy, which is 10 seconds by default. This has cause a lot of headache, because I have used Caddy before, and some recent update caused this, and it seemed like it's a problem from Meteor.

Most of us use a kind of front-end when running on production. **Check if it is your frontend which is causing the problem**.

**Comment by AlexCollin** [comment]
Due to this problem I threw meteorJS!!! All would halt! First simply break the connection then hanged and then tab the entire computer.

**Comment by abernix** [comment]
Problems like this are extremely common if the proxy (e.g. Nginx, HAProxy, etc.) in front of your Meteor application is improperly terminating WebSocket connections, failing to upgrade WebSocket connections, or otherwise mishandling WebSocket connections – something which Meteor requires to work properly.  It's quite easy to improperly configure WebSockets on a proxy so I'd suggest anyone having problems with this first consider other environmental factors.

As a suggestion, try testing your Meteor app directly (without a proxy) or deploying to a host which is known to work properly with WebSockets ([Galaxy](https://meteor.com/hosting), for example! :wink:)

**Comment by dtruel** [comment]
In case anybody wants a fix...

Basically acknowledge that Meteor for Windows is broken.  It has horrible reload times.  And move on... to linux.

Either dual boot your computer - I ended up doing this, and am extremely happy I did.  Linux is just SO much better for web developers.

Or run linux in a VM.

Or maybe the windows 10 creators update will finally work with Windows Subsystem for Linux and Meteor.

But the bottom line is using meteor with windows is a terrible idea and you should get on a linux platform asap.

**Comment by AlexCollin** [comment]
@abernix do you can put your proof link here?

**Comment by enricofoschi** [comment]
I do understand this issue is not strictly related to Meteor, but given that Meteor is often deployed with most of the configuration provided by either the Meteor team or shared in the few posts going around re. scaling Meteor with nginx as reverse proxy, this became an incredible Meteor-related pain for us. "Just switch to Galaxy or try and error it out" is not an option for us. This and other issues are ultimately what pushed us to move away from it as we're growing into a bigger platform.

**Comment by theodorDiaconu** [comment]
@enricofoschi I had those problems with Galaxy, but not with my own infrastructure, elastic load balanced aws, or a classic one with non-sticky-session. Meteor just works for us, so... I'm a bit sad you moved away from it.

**Comment by rschiavi** [comment]
for anyone having these problems, it most likely could be your nginx/ssl configuration. i just updated a cert, but had selected "2" as the option and the wss stopped working. selecting 1. fixed it (using let's encrypt)

1: Easy - Allow both HTTP and HTTPS access to these sites
2: Secure - Make all requests redirect to secure HTTPS access

**Comment by dr-dimitru** [comment]
Hi @rschiavi 

> for anyone having these problems, it most likely could be your nginx/ssl configuration. i just updated a cert, but had selected "2" as the option and the wss stopped working. selecting 1. fixed it (using let's encrypt)

What and where you changed from `2` to `1` ?

**Comment by javamon1174** [comment]
+1
