### ISSUE TITLE
Update "Adding new packages" on the Contributing wiki

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3513]
https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#adding-new-packages-to-meteor

> For historical reasons, some packages that really ought to be in Atmosphere are currently in core, like less, coffeescript, and d3. We welcome PRs against these packages but they may not get the highest priority. We'll probably bump the versions of some of these packages before 1.0

The "before 1.0" bit; also, d3 was extracted out into https://github.com/MeteorPackaging/d3 (see #3082).

**Comment by glasser** [comment]
Thanks, updated this and some other stuff in the same section.
