### ISSUE TITLE
bcrypt error in production deployment

### ISSUE THREAD

**Issue by geekrohit** [meteor/meteor#3517]
Hi,

Current Scenario : 
The `meteor build` currently produces a tar file, which contains the native build OS's precompiled bcrypt binary package. When you deploy such a file to another architecture, for example from Linux -> SunOS, the binary for obvious reasons becomes a hurdle in running the application.

Current Solution : 
`cd bundle/programs/server/npm/npm-bcrypt`
`rm -Rf ./node-modules/bcrypt`
`npm install bcrypt@0.7.7`

Issue:
Firstly, just following the README inside the built bundle is not sufficient. One needs to go inside
the app directories and remove the problematic module, and reinstall it so that it recompiles.
The fibers module recompiles fine, since its installed using `npm install` command after
extracting the built meteor app.
Second thing is, this complicates deployment. Before 1.0 the bcrypt module used to be installed from `npm install`. Now had to dig its path and make sure the process is followed everytime a build is carried out.
A little more streamlining of build process and deployment is required, so that it is predictable.

Another issue is, somewhere mongodb client is being bundled without bson being re-compiled. This I haven't been able to patch yet.

**Comment by geekrohit** [comment]
Bump..

**Comment by glasser** [comment]
There's a `--architecture` argument to `meteor build.

**Comment by geekrohit** [comment]
Yeah, am able to get the parts working no problem. Is it possible for me to change things during a build if --architecture is specified ?
I would like to work on the build architecture for SunOS if possible, since I've already got the bits and pieces figured out.

**Comment by glasser** [comment]
Feel free to work on whatever you like in your own fork, but every new officially supported architecture adds QA and release engineering overhead to every release.  As you can see from https://roadmap.meteor.com/ we are working on Windows support but official SunOS support is not something we're planning on at the moment.
