### ISSUE TITLE
Package summaires are not displayed when using meteor show

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3520]
This is confusing. I like displaying of readme, but probably summary should also be displayed. Probably after the `Package` line at the beginning.

**Comment by glasser** [comment]
@ekatek Is this intentional (to minimize duplication) or an oversight?

**Comment by ekatek** [comment]
This was intentional -- we figured that the longer-form paragraph printed contained enough information, and displaying the summary in addition to that was too overwhelming. However, we will print the summary if there is no README information.

You can still see the summary through 'meteor search'.

**Comment by mitar** [comment]
Wasn't this made into a feature request?

**Comment by glasser** [comment]
I mean, I think there's a difference between "users would like X to be implemented" and "the project team considered X and as a *design* choice decided not to do it"?

But people can still post comments on this bug.

**Comment by mitar** [comment]
Oh, sorry. I mixed it up with search over the description ticket. Sorry. I understand this one (I do not agree, but I understand).
