### ISSUE TITLE
meteor search should search through descriptions

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3521]
In `meteor search --help` it is written:

> Searches through the Meteor package and release database for items whose names or descriptions match the regular expression.

Not sure what "description" means here, but it does not search through `summary` nor `documentation`. Example:

```
meteor search references
```

I believe it should find [peerdb](https://github.com/peerlibrary/meteor-peerdb).

**Comment by glasser** [comment]
@ekatek Is this an issue in the docs or in the tool?  (Is search currently intended to search through descriptions?)

**Comment by mitar** [comment]
If it is not intended, I would make it a feature request. ;-)

**Comment by ekatek** [comment]
This is a docs issue. We decided that searching through descriptions was too confusing, but if there is demand for it...

**Comment by mitar** [comment]
I think it is really useful to search through descriptions. It is really hard to put all the keywords into the name.

**Comment by mitar** [comment]
I think this is important for package developers. That their packages can be discovered.

**Comment by glasser** [comment]
I fixed the docs to match the implementation and am converting this issue to a feature request.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=meteor%20search%20should%20search%20through%20descriptions&body=Migrated%20from:%20meteor/meteor%233521) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
