### ISSUE TITLE
Accounts.forgotPassword - allow hide message "email sent"

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#3522]
Allow hide message "email sent" in user settings for recovery account password (new error.reason in callback):

> The new default is to let people know when they've entered an email we don't recognize in the forgot password form. This will save their sanity, and yours. You can turn on the extra security of being coy about this, if you need it, via a site setting.

http://blog.codinghorror.com/the-god-login/

**Comment by stubailo** [comment]
You can easily check if an email exists by trying to register with it, so this doesn't add any security. It has been discussed many times in other issues.
