### ISSUE TITLE
Can't use tarball url as cordova plugin after upgraded to 1.0.3.1.

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#3528]
How do i use custom plugin with 1.0.3.1 ?

meteor add cordova:org.stereolux.cordova.serial@https://github.com/crapthings/cordovarduino/tarball/c026682ee53a04607ed9653b98998d2b3cab
Must declare exact version of dependency:
org.stereolux.cordova.serial@https://github.com/crapthings/cordovarduino/tarball/c026682ee53a04607ed9653b98998d2b3cab

is this a bug or a feature ?

**Comment by crapthings** [comment]
I've found a temporary solution.

subl .meteor/cordova-plugins add your plugin line by line

org.stereolux.cordova.serial@https://github.com/crapthings/cordovarduino/tarball/c026682ee53a04607ed9653b98998d2b3cabdd8a

**Comment by Slava** [comment]
@crapthings I tried to reproduce it and I get the same error with release 1.0.2. Can you please explain what was the expected result?

    ~/w/asdf> meteor --release 1.0.2 add cordova:org.stereolux.cordova.serial@https://github.com/crapthings/cordovarduino/tarball/c026682ee53a04607ed9653b98998d2b3cab
Must declare exact version of dependency: org.stereolux.cordova.serial@https://github.com/crapthings/cordovarduino/tarball/c026682ee53a04607ed9653b98998d2b3cab

**Comment by crapthings** [comment]
the old version add such url to .meteor/cordova-plugins.
it was the first time that i've saw Must declare exact version of dependency after a fresh osx and meteor installation.

i've used to upgrade meteor by using meteor update. meteor add cordova:name@url works from 1.0 ~ 1.0.2.1 i think.

**Comment by Slava** [comment]
I don't see a regression here. You have always been required to pass an exact url to a tarball with a sha in url.
