### ISSUE TITLE
Missing no-ops for Meteor.methods, publish and onConnection in non-webapp apps

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#3529]
Hey, 

In https://github.com/meteor/meteor/blob/devel/packages/ddp/server_convenience.js, you already define a no-op for Meteor.refresh, but no-ops are still missing for all of the above. This makes it impossible for meteor command line apps or non-webapp apps to use any of the community packages that actually use any of those functions, which drastically limits the package sphere for those apps.

This addresses the first bug in https://github.com/meteor/meteor/issues/2168 which was addresses a long time ago in pr https://github.com/meteor/meteor/pull/2173, but I'm splitting it into separate bugs and prs now, as discussed with @glasser. I will create the pr shortly.

Steps to reproduce (the ddpuser package in this app uses the 3 functions above):

```
git clone https://github.com/practicalmeteor/meteor-no-webapp-ddp-noops.git ddp-noops
cd ddp-noops
meteor --once
```

**Comment by glasser** [comment]
Oops, forgot to mention that this is fixed in 1.0.4.

**Comment by rbabayoff** [comment]
Actually, I saw it in the release notes.

**Comment by rbabayoff** [comment]
This one:

http://famo.us/docs/reference/

It seems it's being served from different servers than the main web site. Always problems loading pages there.
