### ISSUE TITLE
Minimongo has many differences with MongoDB

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3531]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. There are quite few differences. It seems that Minimongo implementation diverged from the server side implementation. Because this is hard to catch in practice, I suggest Meteor creates a similar suite which you should run regularly.

Some differences I see:
* Server side does not allow numeric `_id` fields, for no apparent reason, #3527
* Server side count does not use `applySkipLimit`, while Minimongo does https://github.com/meteor/meteor/issues/1201#issuecomment-70969151
* observes behave differently
* there are some edge cases with updates which behave differently
* queries with `$near` operator do not return the same results

I think this is really problematic because it is not possible to run the same code both on the client and server side. I was trying to implement reactive server side queries, but I see that even other types of queries do not work the same.

Run the above linked package with:

```
meteor test-packages ./
```

**Comment by glasser** [comment]
Let's track these as separate issues. Some of them already are. The ones that aren't are described pretty vaguely here.

I am planning on spending some time in the next few weeks on Mongo maintenance stuff; there's already a big list and they're not all of equal priority, but maybe some of this will slip in (#1201 is already on the list though not the highest priority).

**Comment by mitar** [comment]
Ehm ehm. I would really be against closing this ticket. I spend quite some time preparing you a reproducible example of all changes I found. Any maybe some things are vaguely described, if you would run the tests you would exactly see what I am talking about. And you would have exact code which triggers failing.

If you want, I can come on Thursday to devshop and we can go through time together.

**Comment by glasser** [comment]
I appreciate the work you put in, and I would like to address it, but I'd really like the 5 unrelated issues to be tracked as 5 separate GitHub issues.  It's really tough to have a conversation on a single GitHub issue (which has only flat discussion threads) about 5 different things.

If all the tickets link to the same test package but individually describe "this is about issue X which is demonstrated by this failing test" then that's fine... it's ideal to have a separate repo per issue but probably fine to bunch them.

**Comment by mitar** [comment]
I made tickets #3597, #3598, #3599, #3600, #3601. Do I get something for 3600th issue? :-)

**Comment by lorensr** [comment]
👏

**Comment by mitar** [comment]
I updated the [example](https://github.com/mitar/minimongo-diff) with latest Meteor code. There are still differences on the server side.

**Comment by mitar** [comment]
I would really argue that you start running Minimongo tests against MongoDB. This is the only way that you make sure Minimongo will stay in sync with MongoDB.
