### ISSUE TITLE
`meteor login` should detect use of an email address instead of requiring --email

### ISSUE THREAD

**Issue by paulvanbladel** [meteor/meteor#3532]
I can't publish anylonger because i can't login from command line via meteor login.
I'm 100% sure password is ok (i even did a reset).

**Comment by stubailo** [comment]
Which version of Meteor are you using, on which platform?

**Comment by paulvanbladel** [comment]
I use both ubuntu and windows. It started failing since I started using windows platform (but of course that might be coincidence). It fails now both on windows and ubuntu.
I'm doing from the command prompt meteor login.

**Comment by Slava** [comment]
Have you tried logging on meteor.com through the web interface?

**Comment by paulvanbladel** [comment]
Sure, and that works fine.

**Comment by Slava** [comment]
Well, it is weird, but unlikely to be the windows-port issue? In any case we need more information.

**Comment by paulvanbladel** [comment]
![image](https://cloud.githubusercontent.com/assets/4886272/5871904/ab222fea-a2e4-11e4-8c41-15877dec1002.png)
I use as login my email (i'm not aware of a username), exactly as I do when logging in into the meteor site and for the rest, I'm capable of typing passwords correctly :)

**Comment by colindensem** [comment]
Hi, 
Same issue here. I'm using a new build of Fedora F21, Meteor version 1.0.3.1. Reset passwords to be sure I'm not mad too.

**Comment by justinsb** [comment]
I was able to reproduce the problem where "meteor login" does not work with an email.  I'm not yet sure whether this is the intended behaviour.

As a workaround, you should be able to specify the --email flag:

```meteor login --email myemail@myemail.com```

It seems to ask you for your email again, which obviously isn't quite right, but let me know if this lets you log in.

It should also confirm your username ("Logged in as X."), which you can then use to log in without the workaround.

Let me know if this doesn't solve the problem (i.e. if you were trying to log in with a username, or the --email flag doesn't work)

**Comment by colindensem** [comment]
Confirm for me this has now succeeded. 

I'd also forgotten the username setup; new machine, hence login, which is email elsewhere.  TY.

**Comment by paulvanbladel** [comment]
Yep, it works via the --email switch.
My mistake, i should have done : meteor whoami to figure out my username.
Maybe, in case usernames can't have a @, the meteor login method could be a bit more intelligent and use either username or email ?

**Comment by paulvanbladel** [comment]
Haha, no way to figure out username if you aren't logged in.
meteor whoAmI works of course only when you are logged in :)
Never understood why account systems still use usernames (instead of email only). I can't find on meteor.com, a way to get my user name.

**Comment by justinsb** [comment]
Thanks to you both for confirming - that is good news.

It looks like a relatively easy fix to make meteor login in the CLI automatically accept an email (or just fallback if login-with-username fails).  I don't think it's incredibly high priority (given the workaround), but we have a "bug week" planned for a few weeks and I'll try to fix this then!

I also couldn't see my username when logged in on meteor.com (and I think we used to print it prominently), so I'll look into that issue as well.

**Comment by glasser** [comment]
Also, I think there's just a blatant bug in the code: the code is laid out as if `--email` should just be a boolean flag but written so that that it takes a string.  (ie, you are required to write a string after it which is completely ignored)

**Comment by glasser** [comment]
PR to just "look for an @" would be reviewed.  Note though that this would want changes to our tests, and the login tests are kind of flaky and slow.  This probably also involves changing the prompt to "Username or email" which would affect LOTS of flaky slow tests.  (We have plans to make the self-test suite better but they involve a few more pieces of infrastructure that we're currently working on.)

**Comment by glasser** [comment]
Fixed the "--email requires an argument for no reason" issue, but not the "you have to type it at all" issue.

**Comment by glasser** [comment]
Interestingly, `meteor deploy` has a different but related issue: it prompts for "Email:" but accepts a username too (the disambiguation here is done on the server).

**Comment by wordsforthewise** [comment]
Same issue when doing a fresh install of meteor--I can login fine from the website, but when using the same credentials in the initial meteor login screen during install, it won't login and tells me 'incorrect password'.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20login%60%20should%20detect%20use%20of%20an%20email%20address%20instead%20of%20requiring%20--email&body=Migrated%20from:%20meteor/meteor%233532) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
