### ISSUE TITLE
Error while publishing package: "Longform package description is too long. Meteor uses the section of"

### ISSUE THREAD

**Issue by 0a-** [meteor/meteor#3533]
When I tried to publish a package of mine (to a newer version), I got this error:

```
error: Longform package description is too long. Meteor uses the section of
```

I read up about longform description in the change log of 1.0.3.1 but I still don't quite get why I'm getting this error.

**Comment by djhi** [comment]
If Meteor extract the first section of the readme, your first paragraph may be too long ?

**Comment by 0a-** [comment]
Yup, that is what I think too. However, my first paragraph is actually pretty short. So I looked into how iron-router's README is written (since longform package description worked for it) and discovered that it starts a new paragraph with `##` and a space like this `## The Iron.Router Guide`  while mine doesn't use space: `#QuickStart`. So I added in the space between `#` and the word and it worked!

**Comment by 0a-** [comment]
Looks like this has to do with how `commonmark.DocParser` interprets what a `Header` is. (Line 126 of [package-source.js](https://github.com/meteor/meteor/blob/e4bd9b7a07147bb090004e5bb8418adda4e33fcf/tools/package-source.js#L126) )

**Comment by stubailo** [comment]
Ah maybe we should make it clear that we use commonmark.

**Comment by stubailo** [comment]
Looks like your PR will fix the underlying problem of the message being cut off, though, so I'm going to close this.

**Comment by yogiben** [comment]
Yes, you have to use `## Heading ##` opposed to `##Heading##`.

**Comment by cellog** [comment]
This is still happening with current meteor

**Comment by glasser** [comment]
@cellog The error message being cut off, or something else?

**Comment by cellog** [comment]
I had headings like:

#Heading

Instead of

# Heading 

The error message is confusing at best :)
