### ISSUE TITLE
[request] [package:accounts-password] Accounts.resetPasswordToken

### ISSUE THREAD

**Issue by Sivli-Embir** [meteor/meteor#3538]
Add a `Accounts.resetPasswordToken` function to the accounts-password package. This should do the same thing as `Accounts.sendResetPasswordEmail` but should not send an email and should return the token.

**Comment by Kestanous** [comment]
I originally proposed this in useraccounts:core but there was worry that the user object could change: https://github.com/meteor-useraccounts/core/issues/240

This would make it easier to customize Account emails or even use another verification service. This may also make it easier to reset passwords in Cordova apps.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
This issue is covered by PR https://github.com/meteor/meteor/pull/8207. Since that PR is still open, I'll leave this FR here for now (instead of migrating it to `meteor/meteor-feature-requests`).

**Comment by hwillson** [comment]
PR #8207 was merged. Closing - thanks!
