### ISSUE TITLE
`meteor build` does not produce bundle for out-of-the-box todos example

### ISSUE THREAD

**Issue by pzatrick** [meteor/meteor#3539]
Steps to reproduce using Meteor 1.0.2.1 on Mac OS 10.10.1:

```
meteor create --example todos
cd todos
meteor build .
```

The last command finishes and prints "Supply the server hostname and port in the --server option for mobile app builds." When I re-run the command providing the --server option, I get an error message concluding with "Current working directory is not a Cordova-based project." 

Seems like either there's a problem with the build command, or perhaps the build command's output could be more helpful.

**Comment by stubailo** [comment]
It worked for me just now with Meteor 1.0.2.1 on 10.10.1. Try deleting .meteor/local and try again?

**Comment by pzatrick** [comment]
Pretty sure I just did the steps outlined above to create the issue earlier. I just recreated the project with `meteor create --example todos` and it's not happening now. I already deleted the old copy of the todos app in which the issue occurred. I'll mark as closed.

**Comment by dandv** [comment]
I can actually reproduce this, and the error is that `meteor build` should assume the default value for `--server`, as the help says (`localhost:3000`).

```sh
~$ meteor create --example leaderboard
leaderboard: created.

To run your new app:
  cd leaderboard
  meteor

~$ cd leaderboard/

:~/leaderboard$ meteor build
build: not enough arguments.
Usage: meteor build <output path> [--debug] [--directory]
          [--mobile-settings settings.json] [--server http://example.com:3000]

[...]

Options:
  --debug             [...]
  --server            Location where mobile builds connect to the Meteor server.
                      Defaults to localhost:3000.   <---- THIS
  --architecture      [...]

~/leaderboard$ meteor build --directory ../leaderbuilt
Supply the server hostname and port in the --server option for mobile app builds.

~/leaderboard$ meteor build --directory ../leaderbuilt  --server localohost:3000
The Android platform is not installed; skipping build for it.
The iOS platform is not installed; skipping build for it.

12:27:09  [0s] :~/leaderbuilt$ meteor --version
Meteor 1.0.3.1
```
