### ISSUE TITLE
Possible documentation mistake for Template.dynamic

### ISSUE THREAD

**Issue by PeppeL-G** [meteor/meteor#3542]
[Current docs](http://docs.meteor.com/#/full/template_dynamic):

> {{> Template.dynamic template=template [data=data] }}
> Choose a template to include dynamically, by name.
> 
> Arguments
> template String
> The name of the template to include.
> 
> data Object
> Optional. The data context in which to include the template.

However, if I'm not mistaking, passing a function as the `data` parameter works as well, just as the `data` parameter for the [Blaze.renderWithData](http://docs.meteor.com/#/full/blaze_renderwithdata).

Is this a deliberately limitation of the public API, or is it a feature that has been failed to be documented?

**Comment by stubailo** [comment]
Hi @PeppeL-G, any argument to a helper or template inclusion can be passed as an object or function - in other words, Spacebars automatically evaluates functions when it comes across them (as does Handlebars before it).

See the documentation here: <https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#path-evaluation> (the part about "Spacebars will call functions for you")

I understand that the README is not that easy to find, we will hopefully improve that in the future.
