### ISSUE TITLE
Publish Packages documentation missing information

### ISSUE THREAD

**Issue by rafaelhdr** [meteor/meteor#3544]
Hello,

I followed the steps of [Publish Packages](https://atmospherejs.com/i/publishing) and did not work.
Login information is missing.
```
meteor login
```

Discussion [here](https://groups.google.com/forum/#!msg/meteor-talk/MyX_0Qf1zAY/j5-lhygsWmUJ).

Thanks

**Comment by glasser** [comment]
Seems to work for me with Meteor 1.0.3.1:

```
glasser@perseid 0 /tmp/glasser:nologin $ meteor logout
Logged out.
glasser@perseid 0 /tmp/glasser:nologin $ meteor publish --create
Please log in with your Meteor developer account. If you don't have one, you
can quickly create one at www.meteor.com.
Username: 
```

It prompts me for login.  Please show a more specific reproduction of exactly what you tried to do and what you saw.

**Comment by rafaelhdr** [comment]
I confirm it works with meteor logout (it promted me).
I will try to reproduce the same error.

Ps.: The same error happened [here](https://github.com/meteor/meteor/issues/3676) with an different solution (move the directory outside the Meteor directory), but i didn't need to move it.
