### ISSUE TITLE
adding js via compileStep.addJavaScript does not honor load order.

### ISSUE THREAD

**Issue by xaiki** [meteor/meteor#3547]
I'm building a riotjs handler for witch I need my compiled tags to be loaded before all other client javascript.

https://github.com/xaiki/metor-riotjs/blob/master/plugin/compile-riot.js#L18
so I prefix them with 'lib/' (tried 'client/lib' too) in oder to hint meteor to load them first, but when tracing the app load I can see that the client/ code loads first.

**Comment by xaiki** [comment]
e5eb8fac0810f9166b05b99840d4498556e6a913

sorts by final name

**Comment by stubailo** [comment]
There's a "hidden feature" where you can use the `isTemplate` option to `registerSourceHandler`: https://github.com/meteor/meteor/blob/devel/packages/templating/plugin/compile-templates.js#L47

It's intended for cases like this - does this solve your issue?

**Comment by glasser** [comment]
The "load order" heuristic is just the description of what order files in an app are processed.  Once files are processed, their resources are loaded in the order that they are processed.

As @stubailo said, we have some rudimentary support for letting you say that certain "template" packages should be processed before others in an app.  (In packages, you just have to list those files first.)  We may eventually have more sophisticated controls.
