### ISSUE TITLE
should documentation excerpt choose text before any header?

### ISSUE THREAD

**Issue by splendido** [meteor/meteor#3551]
HI all,
from the [v1.0.3.1 release notes](https://github.com/meteor/meteor/blob/devel/History.md#v1031-2015-jan-20) (second bullet) we can see it is now possible to include documentation within the `package.js` file.

Although it is not clear from that sentence that there's a new `documentation` field supported within [Package.describe](http://docs.meteor.com/#/full/packagedescription) options (which is the one actually set to `README.md` by default as somehow said within the above mentioned release notes), I bumped in a couple of bugs while publishing a new version for a couple of packages:

1) the error message when the documentation excerpt is too long appears on the console as:

`Error: Longform package description is too long. Meteor uses the section of`

hence missing a good part of the string. [Here](https://github.com/meteor/meteor/blob/f7b76857bfb8483518044b52a195a9d968ea10e6/tools/package-client.js#L478-484) is where I found the whole text...

See the following screenshot I captured while (deliberately) trying to update the package metadata with a too long section:

![docbug](https://cloud.githubusercontent.com/assets/6148980/5890946/d03e80b0-a476-11e4-9f1e-73aac0bc2c10.png)

2) the error text says:

> Meteor uses the section of the Markdown documentation file between the first and second headings.

This is not reported on the [Package.describe](http://docs.meteor.com/#/full/packagedescription) documentation.
Moreover if there's some text before the first heading, that is the only text which is eventually picked up.

For example, startring from this:

```
[![NPM version][npm-version-image]][npm-url] [![NPM downloads][npm-downloads-image]][npm-url] [![MIT License][license-image]][license-url] [![Build Status][travis-image]][travis-url]

# Twix

Twix is a simple but opinionated JS library for working with date ranges, and includes a customizable smart formatter. It's written in CoffeeScript and it depends on [Moment.js](http://momentjs.com/).

It allows you to do, among other things, this:

...

## Another header
```

this is what shows up:

``` shell
$ meteor show momentjs:twix@0.6.1
Package: momentjs:twix@0.6.1                  
Implies: momentjs:moment                      
Git: https://github.com/icambron/twix.js.git  

[![NPM version][npm-version-image]][npm-url] [![NPM downloads][npm-downloads-image]][npm-url] [![MIT License][license-image]][license-url] [![Build
Status][travis-image]][travis-url]

Depends on:                                   
  momentjs:moment@2.9.0                       

Published by splendido on January 24th, 2015.
```

So it is only the part **before the first heading** which is being excerpted in case the first line is not a header.

I also noticed that header written as `#Header` instead of the more correct `# Header` are not recognised as such...

Is this a problem with the commonmark doc parser?

See also [this line](https://github.com/meteor/meteor/blob/10173c0ca53cf323e189954e9b138be9a7f834c1/tools/package-source.js#L126)

3) Should the references to the various build statuses be striped out from the excerpt to get a more readable text?

``` shell
meteor show momentjs:twix@0.6.1
Package: momentjs:twix@0.6.1                  
Implies: momentjs:moment                      
Git: https://github.com/icambron/twix.js.git  

[![NPM version][npm-version-image]][npm-url] [![NPM downloads][npm-downloads-image]][npm-url] [![MIT License][license-image]][license-url] [![Build
Status][travis-image]][travis-url]


Twix is a simple but opinionated JS library for working with date ranges, and includes a customizable smart formatter. It s written in CoffeeScript and it depends on
[Moment.js](http://momentjs.com/).

It allows you to do, among other things, this:

...

And much more.

Depends on:                                   
  momentjs:moment@2.9.0                       

Published by splendido on January 24th, 2015.
```

4) In case there is not `README.md` file, the presence of `README.markdown` files could be checked a second attempt?

**Comment by glasser** [comment]
In the future, please file separate issues for separate bugs. It's easier to track them separately.

1) Already fixed on devel.

2) @ekatek Hmm, I thought the eventual decision was "first block of text after any header"?  Or is the current behavior expected?

3) Already suggested in #3519 .

4) Honestly I think that it does a service to the Meteor community to have a standard set of names instead of half of projects choosing one and half choosing the other.  If it's really important that you have the non-standard name, that's what the `documentation` field is for.

I'm renaming this issue to focus on the second thing you mentioned.

**Comment by ekatek** [comment]
2) Yeah -- that was the eventual decision. I guess, I thought that the error message would somehow be more legible this way and I was wrong.

I'll look into both that, and the build status thing.

**Comment by splendido** [comment]
Ok, sorry: I'll try to file separate issues next time.
...I recon you're right about 4) @glasser.

Thanks for looking into this @ekatek!

**Comment by ewall** [comment]
I appreciate the investigation & explanation on the 2nd item, @splendido -- helped me figure out how to edit my README.md to work around this for now!

**Comment by splendido** [comment]
...just to be even more fussy, trying to turn already existing libraries/repoitories into Meteor packages it might happen that you find out the README.md being a little different from what your pretending it to be.

See for example [Font-Awesome](https://github.com/FortAwesome/Font-Awesome/blob/master/README.md), for which there's a pending PR to get a `package.js` into it: in this case there's nothing between the first and the second header and I wouldn't like to ask them to change it.

Perhaps a better strategy would be going through header nodes starting from the very first one and stoping whenever (after stripping out build status images and the like...) some text is found.
Does this makes sense?

**Comment by ekatek** [comment]
>> Perhaps a better strategy would be going through header nodes starting
from the very first one and stoping whenever (after stripping out build
status images and the like...) some text is found.

That's actually what we ended up doing in practice, for similar reasons, I
think. So, in this case, the issue (that I will deal with next week) is
that the docs are wrong.

**Comment by splendido** [comment]
Any news on this?

I've just published a new version of [splendido:accounts-meld](https://atmospherejs.com/splendido/accounts-meld) and I had to temporarly patch the [README.md](https://github.com/splendido/meteor-accounts-meld/blob/master/README.md) by hands to prevent the build status image to be picked up as the only documentation excerpt.

tnx!

**Comment by jagi** [comment]
I had the same problem. Wouldn't it be better to have a separate field in the `Package.describe` for a long description?

**Comment by hwillson** [comment]
Given that the current package documentation excerpt process works for most projects, and that there  hasn't been any updates on this issue in quite some time, I'll close this issue off. Considering a new `Package.describe` property for long descriptions (as mentioned in https://github.com/meteor/meteor/issues/3551#issuecomment-104297192) is worth considering, if anyone still deems this issue to be relevant. If interested, please consider opening a new feature request for this over in https://github.com/meteor/meteor-feature-requests. Thanks!
