### ISSUE TITLE
X-code project keeps recreating when CL: meteor run ios-device

### ISSUE THREAD

**Issue by anthony-ng** [meteor/meteor#3553]
I am working on a ios app, and I would like to use meteor. When I run the command:
meteor run ios-device --mobile-server, it recreate xcode project every time.

Is it a bug or something? Or maybe I just need to re-config my setting in X-Code?

**Comment by tdesc** [comment]
Same opened issue https://github.com/meteor/meteor/issues/3397

**Comment by glasser** [comment]
Closing as duplicate
