### ISSUE TITLE
Why don't Meteor.methods fail when disconnected?

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3554]
It would be great if `Meteor.methods` would return with an `error.reason = "Cannot connect to server"` when the `Meteor.status().disconnected is true`. Otherwise its just loading forever...

**Comment by Tarang** [comment]
I think the way they're built is to try and succeed as over to fail with an error.

When disconnected they simply queue up, when you connect they are sent and you get the callbacks as if there was no disconnection.

**Comment by ccorcos** [comment]
I get that argument, but it just doesn't seems practical. Typically you will wait for the method callback to do something. This gives the app a feeling of being unresponsive...

I made this little shim that seems to work just fine:

```
@failDisconnected = (method, fail, args...) ->
  status = Meteor.status()
  if status.connected
    method.apply null, args  
  else
    fail() 
```

**Comment by glasser** [comment]
@Tarang is correct that this is our current design.  That said, it might make sense to allow timeouts.

**Comment by ccorcos** [comment]
Whether a method or simply inserting into mongo, I like that it queues up until there is a connection and latency compensates, but I think there ought to be more control over whether it should timeout, or queue, and free you up to other things in the meantime...
