### ISSUE TITLE
Meteor Cordova doesn't use viewport meta tag.

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#3555]
Meteor Cordova doesn't use viewport meta tag.  The viewport width is always the css pixel width.  From what I've read these need to be set in Java somewhere.

myWebView.getSettings().setUseWideViewPort(true);
myWebView.getSettings().setLoadWithOverviewMode(true);

I found a cordova plugin but couldn't get it to work.  https://github.com/gitawego/cordova-webview-setting

Here are some posts I found about it.

http://developer.android.com/reference/android/webkit/WebSettings.html#setLoadWithOverviewMode(boolean)
http://android-er.blogspot.com/2013/05/set-viewport-of-webview.html
https://groups.google.com/forum/#!topic/phonegap/0vrq3KHGfV0

**Comment by netpalantir** [comment]
I have the same problem. I am sorry if what follows is a hack, but I am really new to both meteor and cordova :-) I really agree that a configuration setting somewhere would be great. 

Anyway, in the meanwhile, this is what I did. From the root of the project:

`mkdir --parents cordova-build-override/platforms/android/CordovaLib/src/org/apache/cordova/`
`cp .meteor/local/cordova-build/platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java cordova-build-override/platforms/android/CordovaLib/src/org/apache/cordova/`

Then edit `CordovaActivity.java` deep in the `cordova-build-override` dir. In method `init`, line 349, before end, add this:

`this.appView.getSettings().setUseWideViewPort(true);`
`this.appView.getSettings().setLoadWithOverviewMode(true);`

If you have any better solution, please let me know.

**Comment by Slava** [comment]
@dan335 looks like the plugin is doing the right thing. The real issue here is: why didn't it work for you? Can you provide me details on what failed and how you were trying to add the plugin?

**Comment by dan335** [comment]
What's the correct way to use the plugin?  Just add the meteor package?

    meteor add cordova:com.darktalker.cordova.webviewsetting@0.1.0

It's been a while, can't remember what I tried.  Might be able to try again this weekend.

**Comment by Testato** [comment]
@Slava may the plugin solve this problem ?
https://forums.meteor.com/t/viewport-on-android-app/32827

The problem is present only on the href image link, it is not present on the App itself, i mean all the Android app appareance is good on all html template, only when I oped an image directly from an html link (a locsl image present in /public) there is the problem.
