### ISSUE TITLE
How to get access to $ meteor mongo for my-project.meteor.com?

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#3562]
I need access for debug.

**Comment by avital** [comment]
`meteor mongo my-project.meteor.com` should work.

**Comment by comerc** [comment]
😎 It works. May be I have access to shell? (I need to see server console.log)

**Comment by justinsb** [comment]
`meteor logs my-project.meteor.com` should work.

**Comment by comerc** [comment]
😺 It works, thanks!

Can I restrict access for mongo and logs?

**Comment by justinsb** [comment]
Only users that are authorized for the site should be able to access these commands.  Check out `meteor authorized`

**Comment by comerc** [comment]
I'm happy. This solution is not described in the documentation, and I have a sacred knowledge now. 😇

**Comment by justinsb** [comment]
Awesome.  It's not supposed to be closely-held knowledge, so perhaps we need to beef up the docs on this :-)
