### ISSUE TITLE
Blaze custom UI block

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3563]
I like how you can use `{{UI.elseBlock}}` but why can't I use a different name like `{{UI.toolbarBlock}}`? Right now, I'm just using `{{else}}` but thats clearly not ideal..

    {{#app toolbarHeight=2}}
      <div class="banner">Tax Write-offs</div>
    {{else}}
      <div class="toLogin">login</div>
      <div class="toSignup">signup</div>
    {{/app}}

**Comment by stubailo** [comment]
Currently, `{{else}}` and `Template.elseBlock` are hardcoded into Blaze, but this sounds like a great idea for letting components have multiple content sections.

**Comment by ccorcos** [comment]
Of course! :+1: 

Maybe you can bundle this with the `Template.instance()` and context fix and block helpers will be ready to go! I'm eagerly waiting.

P.S. How do you add labels to github issues?

**Comment by stubailo** [comment]
Sorry I'm not going to bundle it with that fix - that one is strictly a fix while this is a new feature. Also, only repository owners can add labels.

I'll put this on the list of exciting Blaze features to build, though!

**Comment by ccorcos** [comment]
haha sounds good.

**Comment by ccorcos** [comment]
Hey @stubailo I'd like to refine this feature request -- I think block helpers could be though of as more of a layout helper. Some way of specifying what goes where. Right now block helpers are very one dimensional. you can put something inside it but thats just about it. It would be great if you could structure the whole layout of your app with block helpers -- the sidebar, nav, menu items, etc.

**Comment by stubailo** [comment]
I agree that would be awesome. I'll look into this soon!
