### ISSUE TITLE
Modular Pattern a = a || {}; not working in Meteor

### ISSUE THREAD

**Issue by meepeek** [meteor/meteor#3564]
Placing Modular Pattern a = a || {}; in a js file produce error on meteor. As you start the server, it will report on the STDOUT that ReferenceError a is not defined, which is not regular behaviour that one would expected from javascript.

PS. I am using Meteor 1.0.3.1

**Comment by ShimShamSam** [comment]
Is "a" supposed to be a global variable? If so, do you have "use strict"; at the top of the file? Strict mode throws errors if you try to declare global variables implicity (by excluding the var keyword). The usual solution is to do window.a, but window doesn't exist on the server. My solution is to have a _globals.js file in myProject/lib/ that defines all globals and doesn't not have "use strict"; at the top.

**Comment by meepeek** [comment]
Yes, 'a' is a global variable but I have not placed any 'use strict' syntax. Is it possible that Meteor added during its process ?

My goal is to use a module pattern for example, I have 2 files define the same object, in this case, 'app'
app/account.js
```
app = app || {};
app.account = [some implementation]
```
app/data.js
```
app = app || {};
app.data = [some implementation]
```
The globals declaration is a good idea but it will make the files tie to the global declaration and the file not working buy just moving it in a project so I would love to hear other suggestion you may have in mind, that would achieve the earlier goal.

**Comment by chriswessels** [comment]
The equivalent of the browser's top-level `window` object in the Node.js environment is the `global` object. To get a generic top level object you could do something like this:

    var globalScope = window || global;
    globalScope.app = app || {};

Any files in a `lib` folder will be loaded before the files in the parent folder. So `app/lib/setup.js` will be loaded before `app/account.js`. You could use this pattern to ensure that the `app` global is defined as an object by the time `app.data = /* some implementation */` runs.

Personally, I would define something like `app.registerModule` as a `function (name, implementation)` in `app/lib/setup.js` and then use it to register further code (in say `app/account.js`). This gives you the opportunity to check that the module hasn't already been defined on `app`, amongst other things.

**Comment by ShimShamSam** [comment]
The problem is a lot of devs put "use strict"; at the top of their files, which makes your example fail because window is not declared (there's a difference between undefined and undeclared)

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  A code snippet is not a reproduction. Without a way to replicate your problem, we can't debug and fix it.

**Comment by meepeek** [comment]
1. Thanks for your advices @ShimShamSam @chriswessels. That was most helpful.
2. I have created a repository as @glasser suggested:
https://github.com/meepeek/meteor-issue-3564

Please feels free to let me know if there were anything I could be of help to you guys.

**Comment by meepeek** [comment]
I started to think that it was the recent web browser update. Could anyone cross-check with me that I had not mistaken ? My support information is as follow:

I tried typing an undeclared variable 'a' in debug console and expect the respond of 'undefined' but, instead, I have got error message "a is not defined"
I ran the test on on Chrome 40.0.2214.91 (64-bit), Firefox 35.0 and Safari 8.0.2 (10600.2.5)

**Comment by chriswessels** [comment]
@meepeek That behaviour is what I'd expect. Until you declare a variable you'll get that error when referencing it.

```
> a
Uncaught ReferenceError: a is not defined
```

Declaring it will give you `undefined`.

```
> var a;
> a
undefined
```

You could declare and assign a global variable without var:

```
> a = 1;
> a
1
```

Perhaps read a bit about JavaScript scoping and scope hoisting to get a clearer picture of undeclared vs undefined.

**Comment by ShimShamSam** [comment]
This is the difference between *undeclared* and *undefined*. This has been around for years.

The following will throw an error:
```JS
console.log(a);
```

The following will work:
```JS
var a;
console.log(a);
```
This also works:
```JS
a = 1;
console.log(a);
```
And this too:
```JS
var a = {};
console.log(a.foo);
```

The reason the first one fails is because **a** is never explicitly declared as a variable (first working example) or implicity declared as a global variable via assignment (second working example). When dealing with objects, you can always safely access undeclared properties without worrying about an error.

If you want to check if a variable is undeclared without throwing an error, use *typeof*. I suggest you google around for some JS tutorials, because this is fundamental to the language and you won't go very far unless you learn these rules.

**Comment by meepeek** [comment]
Thanks for the knowledge, as well as your patience.

**Comment by glasser** [comment]
i agree with @ShimShamSam here.  Use

```
if (typeof a === 'undefined')
  a = {};
```

for this pattern (when defining a global or exported pseudoglobal).
