### ISSUE TITLE
Put some of the content of the .meteor folder outside of the project itself

### ISSUE THREAD

**Issue by felipellrocha** [meteor/meteor#3565]
Hey guys!

I've been runing into a lot of issues, because of the contents of the .meteor directory. Mainly, I have run into a lot of issues trying to install meteor using vagrant on both osx, and windows. Those issues seem to mostly gravitate towards symlinks and vagrant's synced folders features.

As a result, it takes a lot of hacking to make that setup work on the host machines. Some of those hacks, as exemplified in the link below, are less than ideal (separating essential code that needs to be tracked by git, away from the repo):

https://gist.github.com/gabrielhpugliese/5855677

Granted, some things need to stay in a file somewhere in the repo, a list installed package names is a good example (I think a good rule of thumb is that anything that is plain text, or that should be trackable by git or another scm should be in that folder [Though, I think it could be simplified to be on simple dot file]), otherwise, it should reside somewhere else...

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I suspect we'll have more hooks on defining your project layout once we make it to 
https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order on our roadmap. We're also putting a lot of effort into official Windows support so that many people can stop using vagrant just to use Meteor on Windows.

Is there a specific thing that you *can't* do now that you need to do, or is the issue just that it's awkward and takes work?

**Comment by felipellrocha** [comment]
I still haven't been able to get it to work following that tutorial. I wanted to introduce two developers into the team (they haven't used meteor yet), and they use windows as their main system, so they're pretty much locked out of the project until I figure out a way to make it work in their machine.

Although the main problem is that I am based on OSX(so I don't have a machine to test and fix this issue on my own time), I've already spent 4+ hours on this already, so I'd say it's a bit more than just takes work at this point.

Just to add a little bit more context, I think that even if windows had full blown support for meteor I'd still like to use vagrant (I am using vagrant over osx right now, you see). I am using vagrant to isolate my home environment from my development environment so I could use Salt to deploy everything. Without vagrant, some of my home files would get overwritten by salt during deployment. I also get to the develop in the same environment I'm gonna be deploying into, so it helps simplify a lot of other things...

**Comment by glasser** [comment]
I appreciate that you're having trouble here, but without more specific concerns I don't know how much we can do to help (other than by making it much easier to use Meteor on Windows, which we have three developers on full time right now).  Maybe you can find help with your setup woes on StackOverflow or the meteor-talk list?
