### ISSUE TITLE
Renaming a field does not work correctly with observe using projection

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3571]
If I have an observe `collection.find({}, fields: 'type.name': 1).observe` and I rename `type` field to `typex`, `changed` callback is not triggered. I would assume `type: undefined` will be called, because from the view of the projection field `type` has been removed.

Reproduction is here: http://meteorpad.com/pad/uk6HCTtJt3gxHCFm6/observebug

(It does "not work" equally on Minimongo and MongoDB.)

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by mitar** [comment]
I linked it above??? That is a reproduction? You have also a "download" button if you want to get your local version of the app?

**Comment by stubailo** [comment]
Sorry, my mistake - I didn't see the link somehow.

**Comment by mitar** [comment]
Correction: It does work equally on Minimongo and MongoDB, in a sense, that it does "not work" equally. :-)

**Comment by glasser** [comment]
Turned out this was related to #2254. Fixed!

**Comment by mitar** [comment]
For me it didn't work with MongoDB as well. Is that fixed, too?

**Comment by glasser** [comment]
Yes, the same bad logic was used in OplogObserveDriver.  3674c12fc7b5181b8f74165498cdc2257e102cfd
