### ISSUE TITLE
Deps.nonreactive is running reactively

### ISSUE THREAD

**Issue by aashuagg** [meteor/meteor#3576]
I am using timesync library to get server time at client side. I want servertime only when needed instead of reactively updating it at client. here is how I am doing this:

getServerTime = function() {
    var serverTime;
    if (!TimeSync.isSynced()) {
        TimeSync.resync();
    } else {
        serverTime = Tracker.nonreactive(function() {
            console.log("getServerTime", TimeSync.serverTime());
            return TimeSync.serverTime();
        })
    }
    return serverTime;
}
It used to work fine till I was using 0.8.3 version. Recently I moved to 1.0 and it has broken. Now TimeSync.serverTime() runs continuously.

I tried replacing Deps with Tracker but the result is same.

Whats wrong here?

I opened same thread on stackoverflow but even after many suggestions and code changes, result is same: http://stackoverflow.com/questions/28185565/deps-nonreactive-is-running-reactively

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
