### ISSUE TITLE
Provide hook to process emails before sending

### ISSUE THREAD

**Issue by bshamblen** [meteor/meteor#3577]
In the **Email** package it would be nice to have a `beforeSend` hook, to allow processing of the email options before they are used to set the **MailComposer** options. This would give developers the flexibility to filter out blocked email addresses _(AWS SES and other email bulk email services require this)_, or add tracking codes to the HTML body of all emails before they are sent.  

Before I submit a pull request to add the hook I just want to make sure this idea hasn't already been shot down and there are no objections.

https://github.com/meteor/meteor/blob/devel/packages/email/email.js#L145

**Comment by stubailo** [comment]
It seems like you could easily implement this for your app by doing something like:

```
var oldEmailSend = Email.send;
Email.send = function (...) {
  // Filter blocked email addresses and add tracking codes here
  oldEmailSend(...);
}
```

Also, thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by bshamblen** [comment]
I thought about implementing it that way, but many of the calls to the Email.send function are embedded within the Accounts package (enrollment email, email verification, password reset...). I'd have to override each of those functions, and every time a new one was created I'd have to know to override it too. 

If you're on board I'll go ahead and add the few lines to create the hook and submit a PR, after signing the contributor agreement.

**Comment by stubailo** [comment]
Actually, I think if you overwrite the send function the Accounts package will use your new function as well.

**Comment by bshamblen** [comment]
You're absolutely right. I implemented all of the logic and it works wonderfully. Thanks!

**Comment by stubailo** [comment]
I'll leave this open to discuss this potential future more.

**Comment by hwillson** [comment]
There hasn't been any interest/activity on this issue in a while, and the suggestion outlined in https://github.com/meteor/meteor/issues/3577#issuecomment-71883396 works well. As part of the on-going old issue cleanup process, I'll close this off. Thanks for suggesting this originally!
