### ISSUE TITLE
Improve API for accessing parent template variables

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3580]
The only way I know of currently is:

If the parent template can be identified by a DOM selector (in this case the id parent), you can do this: 

```js
Blaze.getView($('#parent')[0]).templateInstance().templateVar
```

**Comment by stubailo** [comment]
I agree that is pretty janky. Since there are already workarounds for getting the parent template, it might make sense to introduce an official API for it.

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
You can use [template-extension](https://github.com/aldeed/meteor-template-extension) package.

Or you can use [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) which have this feature officially.
