### ISSUE TITLE
using Meteor with atom-shell or node-webkit

### ISSUE THREAD

**Issue by iurimatias** [meteor/meteor#3581]
Is there a way to run meteor inside atom-shell or node-webkit? It looks like a great combination to build desktop apps.

**Comment by Slava** [comment]
"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. Good luck!

To answer you question: you can build a bundle of your app that would give you a ready-to-deploy node app in one folder: `meteor help build`. Later you can put these files in your node-webkit app in a way you desire, so it is no different from building such apps with any other JS framework.

More discussion on that: https://github.com/MeteorCommunity/discussions/issues/6, http://www.meteorpedia.com/read/Building_for_the_client_only, https://groups.google.com/forum/#!topic/meteor-core/Pa2Zi0rA7Sg, https://github.com/meteor/meteor/issues/1223

**Comment by tenshis** [comment]
Sorry for continuing this closed topic, but there is no info online on this and many people would like to know how. Can you give us some more info on how to make a ready-to-deploy node app that would work in node-webkit?
