### ISSUE TITLE
`meteor update` doesn't change .meteor/versions

### ISSUE THREAD

**Issue by DenisGorbachev** [meteor/meteor#3582]
I have two console tabs open: one with Meteor app running, another for managing stuff. In the second tab, I try to update the package:

```
starfall@nx:~/workspace/foreach$ meteor update meteorhacks:kadira
                                              
Changes to your project's package version selections from updating package versions:
                                              
meteorhacks:kadira  upgraded from 2.17.1 to 2.17.3

starfall@nx:~/workspace/foreach$ grep kadira .meteor/versions
meteorhacks:kadira@2.17.1
meteorhacks:kadira-binary-deps@1.3.1
starfall@nx:~/workspace/foreach$ 
```

Meteor says it upgraded Kadira from 2.17.1 to 2.17.3, but .meteor/versions still holds 2.17.1.

If I stop my Meteor app in the first tab and then update with the same command, .meteor/versions is changed successfully.

I'm running Ubuntu 14.04, Meteor 1.0.3.1.

**Comment by glasser** [comment]
I'm going to guess what happens here is that the file is being updated but then is being updated again by the other tab.  (You can probably confirm this by looking at the file's modification times.  A full reproduction would make it possible for us to confirm this.)

That said, this seems surprising that it would decide to downgrade.  Maybe the runner tab isn't rereading the versions file even though it decided to re-run?

It would be great to have a full reproduction here, so this is easy to test, especially since @dgreensp is working on some changes to the version solver (which may or may not be at fault here).

As a workaround, `meteor update meteorhacks:kadira@2.17.3` should work (since that also writes the minimum compatible version to `.meteor/packages`).  If *that* doesn't work there's a pretty serious issue.

**Comment by peterchoo** [comment]
Confirming that this is occurring for me as well.

Ubuntu 14.04
Meteor 1.0.3.1
node v0.10.32
npm 1.4.28

With meteor running:

```
pchoo@pchoo-laptop:~/meteor/project$ ll .meteor/versions 
-rw-rw-r-- 1 pchoo pchoo 1529 Feb 18 14:18 .meteor/versions
pchoo@pchoo-laptop:~/meteor/project$ meteor update
This project is already at Meteor 1.0.3.1, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
smeevil:syntax-error-notifier  upgraded from 1.0.2 to 1.0.3

pchoo@pchoo-laptop:~/meteor/project$ ll .meteor/versions 
-rw-rw-r-- 1 pchoo pchoo 1529 Feb 18 14:19 .meteor/versions
pchoo@pchoo-laptop:~/meteor/project$ cat .meteor/versions |grep smeevil
smeevil:syntax-error-notifier@1.0.2
```

Hope this helps.

**Comment by peterchoo** [comment]
Also, I have manually edited .meteor/versions while the process is running and the change gets reverted when the meteor application restarts.

**Comment by DenisGorbachev** [comment]
I confirm the previous comment by @peterchoo, manual editing gets reverted.

**Comment by dgreensp** [comment]
Can either of you put together a reproduction in the form of a clonable repository?

**Comment by DenisGorbachev** [comment]
I tried, but it seems rather sporadic. Once I thought I nailed the steps to
reproduce — only to see it behave normally again... like there is a race
condition or something.

**Comment by peterchoo** [comment]
This repo has the issue and was created purely for this: https://github.com/peterchoo/meteorUpdateIssue

**Comment by glasser** [comment]
I was able to reproduce the issue with Meteor 1.0.3.1 (I ran `meteor update smeevil:syntax-error-notifier` instead of just `meteor update` to simplify what's going on).

**Comment by glasser** [comment]
Somewhat surprisingly, I could also reproduce with Meteor 1.1, even though I would have thought that the new code to detect incompatible changes would have prevented this. Must be a caching issue.

**Comment by glasser** [comment]
Note: in order to trigger this issue when running from a checkout, the app must actually have `.meteor/release` `none`.

**Comment by glasser** [comment]
Should be fixed! Thanks for the reproductions.
