### ISSUE TITLE
incorrect behavior of Client Collection.find method in contrast to Server Collection.find.

### ISSUE THREAD

**Issue by Shalimov** [meteor/meteor#3583]
Hi to All.

Some days ago I met unexpectable behavior of Collection.find on client side:
I use meteorhacks:subs-manager to cache subscriptions' data and create my own pagination control,
which saves current page in search string: (http://mymeteorapp.com/catalog?page=1)
I have the following workflow:
	1. I follow the url http://mymeteorapp/catalog?page=3 (Subscription options => limit = 25, skip = 75)
	2.	Server returns desired data
	3.	(Client) I use Collection.find({}, {limit: limit, skip: skip}); //where limit = 25 and skip = 75
	4. 	(Client) But Collection.find({}, {limit: limit, skip: skip}) on client doesn't return anything to me
	5. 	(Client) If I set skip to 0 or exclude skip at all I will get desired data.

It looks like incorrect behavior of Client Collection.find method in contrast to Server Collection.find.

PS: Because of caching of subscriptions' data I can not refuse from Skip parameter

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
