### ISSUE TITLE
In templates: accessing property of a helper called with an argument

### ISSUE THREAD

**Issue by wtfuii** [meteor/meteor#3584]
Given the following situation:

helper:

``` javascript
Template.a.helpers: {
    helper1: function(argument) {
        return {a: "b", c: "2", d: argument)
    }
}
```

I retrieve the whole object by calling
`{{helper1 myargument}}`

Now I would like to access a property of the returned object within my template. The only way I found to achieve this, is to wrap the call with a  `{{#with}}` statement, which is serious overhead for retrieving a property of an object.

Is there an easier way to achive this? A simple dot-notation as we know it from objects without arguments would be awesome.

**Comment by stubailo** [comment]
I think currently `#with` is the best way to do this. Having optional parentheses around helper arguments would help a lot, as would having variable assignments.

### Potential API ideas

_Variable assignment:_
```
{{#let x=helper1 myargument}}
  {{x.a}}
  {{x.b}}
{{/let}}
```

_Optional parentheses:_
```
{{helper1(myargument).a}}
{{helper1(myargument).b}}
```

Which one is more like what you are looking for?

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by wtfuii** [comment]
Hey @stubailo , thanks for the answer. I think your second idea is exactly what I'm looking for. I'd appreciate to find this feature in a future version!

**Comment by stubailo** [comment]
yeah I think we are hoping to work on this kind of project soon - basically enabling more JavaScript syntax inside of Spacebars.

**Comment by hwillson** [comment]
`#let` syntax was [added to Spacebars in Meteor 1.2](https://github.com/meteor/meteor/blob/devel/History.md#templatesblaze), so a slightly modified version of @stubailo's `#let` example now works:

```
{{#let x=(helper1 myargument)}}
  {{x.a}}
  {{x.c}}
  {{x.d}}
{{/let}}
```

This approach helps address the original issue, so I believe this issue can now be closed.

**Comment by abernix** [comment]
Agree.  Thanks, @hwillson.

Closing for the above reason. :smile:
