### ISSUE TITLE
Collection insertion/reset looping indefinitely when transferring large amounts of data

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3586]
On older devices (iPhone 3GS, iPad 2), transferring a large amount of data in a Collection will loop on inserts, reaching some variable maximum, then resetting the collection and retrying forever.

I would expect the transfer to stop and raise an exception, or at least log an error.

A [demo](http://collection-reset-bug-demo.meteor.com) is available, with [source code](https://github.com/MattiSG/meteor-collections-reset-bug-demo).

**Comment by glasser** [comment]
Thanks for the report.  Are these platforms that don't support WebSockets?  This might be a matter of hitting timeouts while the server is busy.

**Comment by MattiSG** [comment]
No, it does not seem linked to WebSockets per se, as I was able to reproduce this behavior on much more recent hardware by increasing the amount of transferred data.

**Comment by gchpaco** [comment]
d84c962 on devel implements the implicit pong described in #4298, and should hopefully fix your issue. Could you check to see that it does?

**Comment by gchpaco** [comment]
My run of your reproduction on `devel` indicates we have fixed the problem; if you are still plagued by it by all means reopen.

**Comment by MattiSG** [comment]
Thanks! Can't test that right now, but will come back to you if the issue is not solved  :)
