### ISSUE TITLE
_uihooks for non-templates

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3589]
Not sure how to phrase the title, but I want to be able to animate the insertion and deletion of this:

`<div class="something">{{myValue}}</div>`

Whenever myValue changes, I want to animate the change. Any ideas where or how I should do this? `_uihooks` does not trigger when this changes, probably because its not a template... Maybe I could put the animation code in the Template.helpers so it gets run every time it changes?

**Comment by stubailo** [comment]
By "animate the change", you mean animating something about the enclosing div?

**Comment by ccorcos** [comment]
Yes.

**Comment by stubailo** [comment]
The way that Blaze currently works, I'm pretty sure the `<div>` is actually not re-rendered at all, only the text node is replaced. There are some hacks to force it to rerender such as putting a `{{#each}}` with one element around it, but we should figure out some way to improve this situation.

**Comment by sokki** [comment]
+1 for this.
