### ISSUE TITLE
Clean up ReactiveDict keyDeps

### ISSUE THREAD

**Issue by wh0** [meteor/meteor#3590]
Remove `keyDeps` entries when nothing depends on a key.

**Comment by stubailo** [comment]
Can you be more specific about the result you're looking for?

Also, you might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by wh0** [comment]
After no more computations depend on a key, the `Tracker.Dependency` object in `keyDeps` stays around. The result I'm looking for is that the Dependency object gets cleaned up when no computations depend on it. `keyValueDeps` does something like that.

I admit that this would make more sense if there were an `unset` method on `ReactiveDict`, but there isn't.

**Comment by glasser** [comment]
Specifically, this is to avoid unbounded memory use?

**Comment by mitar** [comment]
Yes.

**Comment by mitar** [comment]
There were some `ReactiveDict` improvements recently in devel branch. Could this be also looked into? Maybe provide both `unset` and automatic cleaning of `keyDeps` if there are no dependencies?

**Comment by mitar** [comment]
So there are two issues with `ReactiveDict`:
* lack of `unset`
* lack of monitoring how many dependencies are on each key dependency, and when they reach zero, remove them

Currently this is leaking memory. See this example:

```javascript
dict = new ReactiveDict();
handle = Tracker.autorun(function () {
  dict.get(Random.id());
});
handle.stop();
```

Now `dict` has a dependency object stored which will never be used again. It should be cleaned.

I think this is a crucial fix if you want to use `ReactiveDict` for `state` or `args` in templates. cc @Slava

**Comment by Slava** [comment]
@mitar I think Sashko is doing this as part of https://github.com/meteor/meteor/pull/3561/, so please, don't tag me here

**Comment by Maxhodges** [comment]
why unset and not remove? ReactiveDict is a bundle of bad semantics. Some suggestions for improvement here: https://github.com/meteor/meteor/issues/4100#issuecomment-104796748

**Comment by mitar** [comment]
Whichever name. `unset`, `remove`, this is terminology, not semantics.

**Comment by aadamsx** [comment]
@mitar... but.... unset?  To me it is not clear what this means.  On the other hand, remove is crystal clear.

**Comment by stubailo** [comment]
Let's talk here: https://github.com/meteor/meteor/issues/4438

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Clean%20up%20ReactiveDict%20keyDeps&body=Migrated%20from:%20meteor/meteor%233590) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
