### ISSUE TITLE
Add Npm.depends  <=  >= behaviour

### ISSUE THREAD

**Issue by Urigo** [meteor/meteor#3592]
I want to include a NPM library in my package, but I want to give it a default version and that the programmers who use my package would be able to change that version. 
Mostly they would want to use earlier versions. 

Right now I can only specify a particular version.
Would be great if I could specify the minimum version that will work with it and then the user will be able to define the version he/she would want to use.

I guess part of it will be also to have an API in the Meteor app to add Npm modules and not only in packages.

**Comment by stubailo** [comment]
Hi Uri!

The intention is that you specify the version of the NPM package that you have tested this package with. We use SemVer constraints to resolve situations where multiple packages ask for different versions of a dependency, so saying you want a package at version "1.2.3" will actually also accept "1.3.5" or "1.1.7" (@ekate correct me if I'm wrong)

I think you could accomplish what you are looking for by publishing a single latest version of `urigo:angular`, and then people can override the version of Angular provided by explicitly adding `urigo:angular-lib@1.2.3` when they don't want the latest version.

**Comment by avital** [comment]
I think you meant @ekatek above.

**Comment by ekatek** [comment]
NPM packages are built into the Isopack, so what @stubailo describes is not entirely accurate with our current model. 

Here is one way that you can work around this for now:
1. Split the package into, for example, "angular" and "angular-npm-wrapper" where the latter is just a wrapper around the NPM module.
2. Publish versions of "angular-npm-wrapper" for the compatible versions of the NPM module that you want to use.
3. Set "angular" to depend on "angular-npm-wrapper" at a minimum version. People can then use Meteor's normal version selection process to specify the version of "angular-npm-wrapper" that works for them.

**Comment by Urigo** [comment]
@ekatek and if I want to make the latest version the default and not the earliest?
Let's say I will include angular-npm-wrapper@1.3.11 and then when a user will specific angular-npm-wrapper@1.2.12 , will it be OK?

**Comment by ekatek** [comment]
That won't work. I don't think that there is a way to make an older version an overridable default, unless some default behavior of the constraint solver has changed. (CC @dgreensp)

**Comment by glasser** [comment]
I thought that latest versions are typically the default for a newly created app or when running `meteor update`; older versions are only the default when doing other changes (ie, adding an unrelated package shouldn't randomly update the package in question).  Is that not the case?

**Comment by ekatek** [comment]
One upon a time, older versions were the default for indirect dependencies
as well, even when part of an app. I can imagine a world where that's not
the case any more though.

**Comment by dgreensp** [comment]
Ekate is correct.  We take the oldest possible version of indirect dependencies of your app.  Also, inexact dependencies are treated as >=.  So if your package asks for version 1.3 of the wrapper, it will not work with version 1.2 of the wrapper.

I can't think of a good argument for the current behavior, though, and this very class of issues is up for discussion this week, so we may well change it.

**Comment by hwillson** [comment]
The current Meteor package peer npm depenency recommendation is to avoid using `Npm.depends` (due to its fairly rigid nature) and instead leverage a solution that is more inline with npm's [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) approach. The [Meteor Guide](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) currently recommends using something like the [tmeasday:check-npm-versions](https://atmospherejs.com/tmeasday/check-npm-versions) package to help ensure package users have npm installed any necessary dependencies.

Given the above (and as part of the on-going old issue cleanup process), I believe this issue can be closed.

**Comment by hwillson** [comment]
As outlined in https://github.com/meteor/meteor/issues/3592#issuecomment-259027206, I'll close this off. Thanks!
