### ISSUE TITLE
Mobile: Add a --no-server parameter for purely-offline apps

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3594]
I have an offline cordova app. Using Meteor for build, Blaze, local collections, etc., but there's no web server associated with it and will never be. However, it won't let me do the cordova builds without the `--server` option. I can create the bundle and use cordova separately, but I'm wondering if there's some way to make it work through Meteor build, which is simpler. Will it break anything if I specify a dummy server address?

I haven't tried removing web app or other unused standard packages yet, but theoretically I shouldn't have to since I'm only building the client code.

**Comment by Slava** [comment]
The connection to server is also used for accounts and discovering new code from the server. If you don't need them, you can supply a dummy address, I don't think anything will break if your app is offline.

We require `--server` to be passed because most of the time people do need to set an url :)

**Comment by aldeed** [comment]
OK, good, I will try that. I agree requiring it makes sense, but maybe a `--no-server` option could be added eventually to make it less confusing. It's rare, but I'm sure I'm not the only one who will try building an offline app with it. :)

**Comment by sferoze** [comment]
Hello. I am having the same issue. Please include an option to specify no server. I will try with a dummy url and using Meteor.disconnect() in the Cordova startup function. But I don't like using dummy url. hope nothing breaks.

**Comment by sferoze** [comment]
I created a brand new test meteor click button app. Removed the server code and put all files in the client directory. I removed the meteor-platform package. And added these custom packages:

```
blaze
spacebars
tracker
reactive-dict
session
reactive-var
templating
webapp
```

When typing 'meteor run ios' the app shows up blank in the simulator. But in the browser it shows up normally and works fine.

**Comment by danlg** [comment]
It means you cannot make the build independent of the environment i.e  the same build for UAT and production environment which introduces some risk or complexity.

**Comment by isdzulqor** [comment]
I have this issue too. I want to build my Android App without server. Please give an option to build without specify server url

**Comment by kctang** [comment]
Any update on this feature request? A `--no-server` option can be useful.

**Comment by grundmanise** [comment]
+1 for --no-server

**Comment by cyclops24** [comment]
+1 for --no-server

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Mobile%3A%20Add%20a%20--no-server%20parameter%20for%20purely-offline%20apps&body=Migrated%20from:%20meteor/meteor%233594) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
