### ISSUE TITLE
Ordered observe without projection behaves differently on the client and server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3598]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. It exposes the issue with ordered observe without projection. Behavior is not the same with Minimongo and MongoDB collection.

**Comment by glasser** [comment]
I'm going to do my best to at least analyze if not fix this in the next few weeks as part of https://trello.com/c/xR0t2vRd/82-livequery-mongo-driver-and-minimongo-maintenance

**Comment by glasser** [comment]
I believe this is the same as what I said in #3597.
