### ISSUE TITLE
$near operator behaves differently on the client and server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3599]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. It exposes the issue with using `$near` operator. Behavior is not the same with Minimongo and MongoDB collection, documents are not ordered in the same order.

**Comment by glasser** [comment]
This seems like the sort of issue that is well suited to a pull request, since hopefully it should be relatively self-contained and testable!

**Comment by mitar** [comment]
I updated the [example](https://github.com/mitar/minimongo-diff) with latest Meteor code. There are still differences on the server side.

So if you run the test suite, `$near operator tests` test fails.

**Comment by mitar** [comment]
I made a branch where each difference is in its own test, so it is easy to see the issues: https://github.com/mitar/minimongo-diff/tree/split-tests

**Comment by mutdmour** [comment]
I will work on this

**Comment by hwillson** [comment]
#8642 has been merged, so these changes will be coming soon. Thanks for reporting this @mitar, and thanks for your work on the fix @mutdmour!

**Comment by mitar** [comment]
Should we also adapt the idea that we run all Minimongo tests on the server? Like I did to find this issue?

**Comment by mitar** [comment]
See [this app](https://github.com/mitar/minimongo-diff) for an example how I did it.
