### ISSUE TITLE
Updating the array behaves differently on the client and server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3600]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. Updating the array using `{"$set":{"a.01.b":99}}` behaves differently on Minimongo and MongoDB collection.

**Comment by glasser** [comment]
I'm going to do my best to at least analyze if not fix this in the next few weeks as part of https://trello.com/c/xR0t2vRd/82-livequery-mongo-driver-and-minimongo-maintenance

**Comment by glasser** [comment]
This was a behavior change between MongoDB 2.4 and MongoDB 2.6.  minimongo implements the newer MongoDB 2.6 semantics.

```
MongoDB shell version: 2.4.12
connecting to: 127.0.0.1:3001/meteor
meteor:PRIMARY> db.x.insert({a: [1,{a: 98},3]})
meteor:PRIMARY> db.x.update({},{$set: {'a.01.b': 99}})
meteor:PRIMARY> db.x.find()
{ "_id" : ObjectId("54f9165f6137ada0663c3c2c"), "a" : [  1,  {  "a" : 98 },  3 ] }
```

```
MongoDB shell version: 2.6.7
connecting to: 127.0.0.1:3001/meteor
meteor:PRIMARY> db.x.insert({a: [1,{a: 98},3]})
WriteResult({ "nInserted" : 1 })
meteor:PRIMARY> db.x.update({},{$set: {'a.01.b': 99}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
meteor:PRIMARY> db.x.find()
{ "_id" : ObjectId("54f91686a3784528d96f17bb"), "a" : [ 1, { "a" : 98, "b" : 99 }, 3 ] }
```

(the mongod versions match the mongo versions here)
