### ISSUE TITLE
Updating query succeeds on Minimongo, but fails on the server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3601]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. One update query from the tests above succeeds on Minimongo, but fails on MongoDB collection with:

> Cannot apply the positional operator without a corresponding query field containing an array.

**Comment by glasser** [comment]
I'm going to do my best to at least analyze if not fix this in the next few weeks as part of https://trello.com/c/xR0t2vRd/82-livequery-mongo-driver-and-minimongo-maintenance

**Comment by glasser** [comment]
It would have been helpful if you had just created a small reproduction with the specific failing query instead of leaving me to make sure I was running your reproduction at the same version of Meteor and track down the specific failure.

This is a behavior change between MongoDB 2.4 and MongoDB 2.6 and Meteor follows the MongoDB 2.6 semantics:

```
MongoDB shell version: 2.4.12
connecting to: 127.0.0.1:3001/meteor
meteor:PRIMARY> db.x.remove({})
meteor:PRIMARY> db.x.insert({a: [{x: 2}, {x: 4}]})
meteor:PRIMARY> db.x.update({$or: [{'a.x': 4}]}, {$set: {'a.$.z': 9}});
Cannot apply the positional operator without a corresponding query field containing an array.
```

```
MongoDB shell version: 2.6.7
connecting to: 127.0.0.1:3001/meteor
meteor:SECONDARY> db.x.remove({})
WriteResult({ "nRemoved" : 1 })
meteor:PRIMARY> db.x.insert({a: [{x: 2}, {x: 4}]})
WriteResult({ "nInserted" : 1 })
meteor:PRIMARY> db.x.update({$or: [{'a.x': 4}]}, {$set: {'a.$.z': 9}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
meteor:PRIMARY> db.x.find()
{ "_id" : ObjectId("54f9213f238077a7568269ec"), "a" : [ { "x" : 2 }, { "x" : 4, "z" : 9 } ] }
```
