### ISSUE TITLE
Requesting external login service permissions after signup

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3602]
**_1 Upvote**_ FR: add to eg `facebook` package the ability to do both:

A. Rerequest permissions: You need to add `auth_type: 'rerequest'` to the login call:

https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2#re-asking-declined-permissions

but there is no option for that under `Accounts.loginWith<ExternalService>`

B. Incremental requesting of permissions: requesting basic permissions during signup, but requesting "post on behalf" kind of permissions the first time actually required. This is facebook's recommended practice, but I just cannot figure out how to do that in its current form of the accounts facebook package. — @serkandurusoy

@avital's comment was: "I agree that this is something that users need. Can it be implemented in a package?"

Probably yes, but it would fit well in eg `facebook` package, since it already uses the `oauth` package in the right way. And if it was part of Accounts, then the way in which the user object is edited could be uniform across different services and non-conflicting with how Accounts already uses it. Like this feature would be using/editing `user.services.facebook.accessToken` and might add a `user.services.facebook.permissions` array.

**Comment by serkandurusoy** [comment]
:+1:

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by sungwoncho** [comment]
@lorensr Did you ever come up with a solution to "B. Incremental requesting of permissions"? I'm trying to do this with accounts-github package, but I see that the package does not provide a way.

**Comment by lorensr** [comment]
Nope, sorry!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Requesting%20external%20login%20service%20permissions%20after%20signup&body=Migrated%20from:%20meteor/meteor%233602) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
