### ISSUE TITLE
MongoDB $near doesn't work inside $and operator

### ISSUE THREAD

**Issue by m0g** [meteor/meteor#3604]
Hello,

I'm trying to do a geospatial query within an $and operator on the server side:

    var query = { $and: [
      {
        fromLoc: { $near : { 
          $geometry: { 
            type : "Point" ,
            coordinates: fromCoords
          },
          $maxDistance : 50,
          $minDistance : 10
        }}
      },
      {
        toLoc: { $near : { 
          $geometry: { 
            type : "Point" ,
            coordinates: toCoords
          },
          $maxDistance : 50,
          $minDistance : 10
        }}
      }
    ]};

    return Lifts.find(query);

Problem is that Mongo is telling me that it *can't find any special indices 2d (needs index) 2dsphere (needs index)*

I've google around, and it seems that it's a [bug](https://jira.mongodb.org/browse/SERVER-4572) from MongoDB 2.4, and that it has been corrected in newer version. However since Mongo is bundled with Meteor, I have no idea how I can update mongo itself.

Thanks

**Comment by glasser** [comment]
You can run current versions of Meteor against your own Mongo 2.6 server and just about everything will work (some upserts won't, see #2278), but the default server used by the dev mode runner will still be 2.4.  I am in the process of upgrading the default used by Meteor to 2.6; this is being tracked in #2036.
