### ISSUE TITLE
Add github irc integration for #meteor

### ISSUE THREAD

**Issue by fourq** [meteor/meteor#3605]
Could we enable this repo to post in irc when rull-requests are merged/denied and new issues are created (maybe not this if it's too spammy)

Thoughts?

**Comment by fourq** [comment]
[link to hook settings](https://github.com/meteor/meteor/settings/hooks/new?service=irc)

**Comment by rgoomar** [comment]
I like this idea. It shouldn't be too hard to setup either.

**Comment by fourq** [comment]
@rgoomar it would take 5 mins

**Comment by fourq** [comment]
I'll do it if added as a contrib.

**Comment by glasser** [comment]
None of the core developers actively use IRC these days (and we don't link to it from the official website), but sure, making the IRC channel better sounds nice.  If you tell us exactly what to put in the hook setup form, that should be OK.  We'll remove it if other IRC users complain.

**Comment by fourq** [comment]
Sure, here's a [screen shot](http://screencast.com/t/f5BFRpfZNrCn) of the settings.

Thanks!

**Comment by glasser** [comment]
OK, set up. Let me know if it works!

**Comment by fourq** [comment]
We'll have to wait for some activity on a branch

**Comment by fourq** [comment]
I didn't see any msg in the #meteor chan for any of the 3 branches that were updated 12 hours ago. Did you leave the Branches field blank so that it picks up all branch changes?

**Comment by glasser** [comment]
I think you told me the wrong port. I changed it to 6667.

**Comment by fourq** [comment]
ahh, sorry about that. Ok, let's see if that works. thanks

**Comment by fourq** [comment]
Ahh. Remove the `Message Without Join` checkbox. I would have to be an op on the chan to set that up. Sorry for the confusion.

**Comment by glasser** [comment]
ok, updated

**Comment by fourq** [comment]
it's working now. ty

**Comment by fourq** [comment]
One last thing (I swear I'm done after this). People don't like the Notice feature. Can you please uncheck `Notice`. ty.

**Comment by glasser** [comment]
ok, done!
