### ISSUE TITLE
Meteor.subscribe should throw or return an error if publication doesn't exist

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#3606]
Hey,

So right now, if I subscribe to a non-existent publication, Meteor.subscribe returns normally. Would be nice to get an exception or return null or some other kind of indication in the returned object that will let me know the publication doesn't exist.

Is this by design?

**Comment by Tarang** [comment]
Client side js has to be async so you have to use a callback for any errors, as when the object is returned the operation wouldn't have been completed in time. 

You can use the `onError` callback
```
Meteor.subscribe("something", {
    onError: function(err) {
        throw err;
    });
});
```

The last param can contain `onError`, and `onReady`

**Comment by rbabayoff** [comment]
Got it. Forgot about this. Tks! MDG, you can close this.

**Comment by glasser** [comment]
Thanks @Tarang!
