### ISSUE TITLE
Allow unprefixed packages in `meteor add/remove`

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3607]
FR: 

1. I only have one package with a suffix of "bootstrap3", and I want to remove it with `meteor remove bootstrap3` without looking up the full name in `meteor list` and copying the prefix, "pinglamb".
2. There is only one package on atmosphere with a suffix of "coinbase", and I want to add it with `meteor add coinbase` rather than looking up and typing who published it.

**Comment by ekatek** [comment]
We think that usernames are an important part of package names in the Meteor package system. The username prefix is part of the package name -- this creates an incentive for reasonable naming schemes, eliminates the race for the most-human-readable name, and gives credit to package authors.

**Comment by lorensr** [comment]
If it's important to know who a package is made by, how about just requiring the prefix when adding, and allowing the convenience of just using the suffix when removing?

**Comment by lorensr** [comment]
@ekatek, I understand why having prefixes in the package system is good, and can see how the desire to reinforce prefixes in people's minds might be an argument for not allowing #2, but what about #1? It's been the case so often when removing packages that I need to search through my long `meteor list` to find the prefix that I aliased `mlg` to `meteor list | grep`.
