### ISSUE TITLE
Keeps refresing mobile ios app

### ISSUE THREAD

**Issue by advany** [meteor/meteor#3608]
When I pass --mobile-server (to my host) with meteor run ios, the page keeps refresing. But when I just do meteor run ios (with the local server) everything works file. Both the code of the local server and the remove server are the same. How do I solve this? or even debug this?

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
