### ISSUE TITLE
'meteor build' does not include non js files in bundled file

### ISSUE THREAD

**Issue by camelCaseD** [meteor/meteor#3609]
I have a project in which I have one python script stored in the server folder and a binary file with a .model extension. When meteor bundles the app it doesn't include the binary file or python script which are needed for my app to work. Is there any way of having meteor bundle non js related files? I'm using the latest version of meteor which is 1.0.3.1.

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker.

You can put any files you would like to be bundled that don't have a build plugin (coffeescript, less, etc) into the `/private` directory of your project.
