### ISSUE TITLE
How to delete/remove a user account?

### ISSUE THREAD

**Issue by PeppeL-G** [meteor/meteor#3612]
I can't find anything in the docs about how to delete a user account. [This stackoverflow question](http://stackoverflow.com/q/17024263/2104665) suggests to simply remove the user from the `Meteor.users` collection. Is that the way to go? Then I suggest it should be written in the docs, otherwise I suggest you to add this feature.

**Comment by zimt28** [comment]
Yes. The users collection is a normal mongodb collection. You delete users by just deleting the corresponding document from the Mongo.Collection. You can actually [find this information](http://docs.meteor.com/#/full/meteor_users) in the docs.

> Meteor.users 
A Mongo.Collection containing user documents.

**Comment by PeppeL-G** [comment]
@zimt28, thanks for answering my question, but I disagree regarding that it's written in the docs. As far as we programmers using Meteor know, Meteor could store other account information internally that would outlive the removal of a doc from the `Meteor.users` collection.

**Comment by stubailo** [comment]
Thanks for the documentation feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
This issue has been moved to meteor/docs#120. Closing here - thanks!
