### ISSUE TITLE
Where to define rootUrl?

### ISSUE THREAD

**Issue by CaptSaltyJack** [meteor/meteor#3613]
When I run my Meteor app via `node main.js`, it complains about `ROOT_URL` or `options.rootUrl` not being defined. I'd like to know where to set the variables such as root URL, port number, etc, so I don't have to do it via the shell environment every time.

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. Good luck!

(Probably, you want to just write a shell script that includes setting the environment variable and running `node main.js`, but this is really dependent on your particular hosting choices.)

**Comment by dandv** [comment]
The full docs should mention ROOT_URL in the Deploy section, IMO. There are only two references to ROOT_URL, both at http://docs.meteor.com/#/full/meteor_absoluteurl.

**Comment by glasser** [comment]
Yeah. It is documented in the `README` in every built meteor app, though.
