### ISSUE TITLE
add commands to clean up unused packages

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3614]
While investigating low disk space, I realized `~/.meteor` was taking more than 1.1GB.

On the one hand, I finally discovered where these `meteor add` packages are stored.

On the other hand, I can't really understand why `meteor-tool` has 5 seemingly versioned subdirectories that take up more than 150MB each. If it is a built-in tool that auto-updates, as it seems to do since I never `meteor upgrade tool` then why doesn't it clean up after itself on updates? How can I safely clean this directory?

If there is no good way to automatically clean up this directory, then could Meteor at least output a message along the lines of `meteor-tool@1.0.40 installed, 152MB stored in ~/.meteor/meteor-tool` when it does its “updating packages” thing? Magic is nice, as long as it does not silently deplete resources.

**Comment by glasser** [comment]
Meteor is designed to let you have multiple releases installed at once so that you don't have to upgrade every app on your system in lockstep.  This means it doesn't make sense to automatically delete old versions as soon as you upgrade to a newer one.

One the other hand, adding some sort of command to help clean up old packages would be nice.  Maybe we could even add some local stat tracking to remember when you last used a package so you could say "remove packages I haven't used in a month".

That means this is a feature request, so you might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by MattiSG** [comment]
If you consider this a feature request, then there are probably two separate: one to clean up, and one for increased visibility, which I created as #3637.

- - - - 

> Meteor is designed to let you have multiple releases installed at once so that you don't have to upgrade every app on your system in lockstep.

Well… I see the point, but then sharing releases in `~` seems bad design, as it means older releases will never be cleaned up, even if I delete projects that requested them.
Your solution of automatic cleanup after n months/weeks/days might cut it, but it seems the fundamental design is flawed.

As you mentioned in #3616, `npm install` defaults to local install, and it needs a flag to do global install. Meteor’s intermediary “session-level” install seems to have the drawbacks of the global install (lack of cleanup when dependencies are removed) without its advantages (machine-wide sharing of packages).

**Comment by glasser** [comment]
See also #3637, which is about printing more information when the downloads happen.

**Comment by sschmitz** [comment]
Isn't meteor-tool kind of a special case? I don't really know much about Meteor's package architecture, but the way I understood it -- which might be completely wrong -- is that `meteor-tool` is the command-line application and not required by any project itself. As such, would it actually need to exist in more than the most recent version?

**Comment by glasser** [comment]
No, pinning your app to a specific version of meteor also fixes the version of the tool.

This has advantages and disadvantages. On the pro side, any backwards incompatible changes to the build logic won't affect your app until you make the conscious choice to upgrade it.

On the con side, changes to things like `meteor login` and `meteor deploy` which relate to services run by MDG require you to upgrade your app in order to see the new version.

**Comment by mizzao** [comment]
I have a 2.7GB `meteor-tool` directory, and it would be nice to be able to nuke all previously downloaded meteor versions from the extensive upgrading process and just re-download the ones that my projects are using now.

**Comment by Slava** [comment]
@mizzao just to be clear, this behavior can be achieved by nuking the directory and running `meteor` again in your project.

**Comment by glasser** [comment]
You can always just do a clean install with `curl https://install.meteor.com/ | sh` which will replace your `~/.meteor` without losing any irreplaceable state.

**Comment by vimes1984** [comment]
@glasser I can't like that last comment enough :D I had over 4 gb's on my .meteor folder...

**Comment by lc3t35** [comment]
OMG ! 
````
laurent$ du -sk .meteor
12078232	.meteor
```
Back to the future : oldest packages are from March 2013 ! No other explanation than I never cleaned .meteor since I got this computer ;)
Hopefully I changed it once since I use meteor (0.3.9 seems to be my first meteor update in august 2012).
+1 for a clean feature.

**Comment by braadworst** [comment]
How is this coming a long? I have nearly 3 Gig of meteor stuff, and i only installed it a month ago. I would like that option where you can see when it was used for the last time, there are many dependencies installed behind the scene so it is hard to track what is going on and do some cleanup yourself.

**Comment by laosb** [comment]
Sounds good to me. +1

**Comment by ahmedtabrez** [comment]
:+1:

**Comment by tomyo** [comment]
16.2 GB of packages... come on!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=add%20commands%20to%20clean%20up%20unused%20packages&body=Migrated%20from:%20meteor/meteor%233614) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by MattiSG** [comment]
Migrated to https://github.com/meteor/meteor-feature-requests/issues/77. Subscribers, you can 👍 this feature request there.
