### ISSUE TITLE
Allow sharing packages between users

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3616]
Packages are currently stored in `~/.meteor`. This means that they are not shared between users and end up taking a lot more space than they already do (as seen in #3614).

Is there any way to have `meteor install` behave like most other package managers do and put packages in some machine-specific folder rather than a user-specific folder, just like `npm install -g` or `gem install` does?

**Comment by glasser** [comment]
We think it's generally a feature that you don't need superuser access to install Meteor software and that users don't step on each others' toes.  Note your example: `gem install`, an older tool, defaults to global installation, whereas the more modern `npm install` requires a special flag for global installations, which is mostly used for installing command-line tools (which Meteor doesn't support).

You can always play games with making `~/.meteor` or `~/.meteor/packages` into a symlink to a directory with appropriate permissions if you'd like to share that data.
