### ISSUE TITLE
Document oauth package

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3621]
Looked through the `twitter` and `facebook` code, and they use `oauth` differently, and it wasn't apparent to me which of those differences I should carry over to the service I want to use `oauth` for, and I dread debugging whatever goes wrong 😄. Someone suggested I use passport (http://passportjs.org/), but don't think that would work with Meteor.

**Comment by glasser** [comment]
What do you mean by differently?  Is this just a matter of the fact that Twitter (the service itself, not just our code!) uses OAuth 1  and Facebook uses OAuth 2?

**Comment by lorensr** [comment]
That probably accounts for the differences between those two, but even
`google` and `facebook`, both OAuth 2, have some different code. It would
just be nice to have something saying what each Oauth.* function did, what
the args meant, how do to 2- versus 3-legged, etc. Also, bottom of

https://www.meteor.com/accounts

"Currently there is not yet any documentation of the internal interfaces
that you need to use to write a new OAuth provider package. But it is
fairly easy to look at a pair of packages such as facebook
<https://atmospherejs.com/meteor/facebook> and accounts-facebook
<https://atmospherejs.com/meteor/accounts-facebook> and follow the model."

And the links point to atmosphere, which doesn't have a link to the source.
Would be nice for the atmosphere packages to point to eg
`meteor/meteor/packages/facebook` for source, as I think most people won't
know that.

**Comment by glasser** [comment]
OK, we'll track this as a docs feature request. You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).
