### ISSUE TITLE
Unclear Meteor Method Error report

### ISSUE THREAD

**Issue by ngducthanh** [meteor/meteor#3622]
When I am creating my sample app, (Here is that repo: https://github.com/ngducthanh/meteor-404-unclear-error-report), I put Meteor method call in lib folder, which will run on both server and client. I get this error message:
```
 Your app is crashing. Here's the latest log.
/home/thanhtruc/.meteor/packages/meteor-tool/.1.0.40.1oh3mee++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Method not found [404]
    at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1485:1)
    at [object Object]._.extend.call (packages/ddp/livedata_server.js:1455:1)
    at app/lib/collections/titleCollection.js:3:10
    at app/lib/collections/titleCollection.js:8:3
    at /home/thanhtruc/404/sample/sampleApp/.meteor/local/build/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/thanhtruc/.meteor/packages/meteor-tool/.1.0.40.1oh3mee++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/thanhtruc/404/sample/sampleApp/.meteor/local/build/programs/server/boot.js:116:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```
This error report is not clear because the main reason is that I forgot putting callback function into meteor call. But the report says "Method not found". I think it would be better like: "You must provide callback function on client side".

**Comment by ngducthanh** [comment]
This error report is not clear because I mistakenly put method call in lib folder. I've defined method in server folder already. But the report says "Method not found". I think it would be better like: "Method call not found".

**Comment by glasser** [comment]
This is a file load order issue.  `lib` loads before everything else, and your `Meteor.call` in `lib/collections` runs (on the server — maybe you meant for this code to be client-only or server-only?) before the method is defined in `server/methods.js`.  Move things around so that methods are defined before they are used, or put the calls in a `Meteor.startup` block.

**Comment by glasser** [comment]
See http://docs.meteor.com/#/full/structuringyourapp for examples of app file load order.

**Comment by glasser** [comment]
By the way, thanks for giving a full reproduction!  This is exactly the reason that we ask for reproductions: the issue ended up being pretty different from what you thought it was.

**Comment by maxnowack** [comment]
I ran into the same error.
1+ for an error report like `You must provide callback function on client side` as mentioned by @ngducthanh

**Comment by glasser** [comment]
@maxnowack Did you read my response? @ngducthanh's analysis was incorrect. The problem was not the lack of a callback function (which is not required).

**Comment by maxnowack** [comment]
Yes, of course. But it's definitely not a load order issue in my case. I'll try to reproduce the error and open a new issue if the error isn't my fault.

Thank you for your very fast response David. I was reading this issue and it sounds exactly like my case. I quickly read your response and didn't read something about the suggested error report, only about the load order issue. Probably that was why I thought that the new error report has been rejected.
Sorry for the confusion.
