### ISSUE TITLE
Issue with transforming fetched document using custom object constructor

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#3623]
At first, I have to say that this isn't bug but still I think it should be considered to be resolved. I'm creating M(Model)vc layer for Meteor and have to transform documents fetched from collection. Here is the reproduction https://github.com/jagi/meteor-transform-reproduction

I have my custom constructor:

```js
Item = function (doc) {
  this._values = {};

  _.extend(this._values, doc);
};
```

and transform function:

```js
Items = new Mongo.Collection('items', {
  transform: function (doc) {
    return new Item(doc);
  }
});
```

As you can see, I don't store document properties just in the object but inside its `_value` property. It's because I have defined setters and getters for this constructor prototype.

```js
var define = function (proto, fieldName) {
  Object.defineProperty(proto, fieldName, {
    get: function () {
      console.log('get `' + fieldName + '` field value');
      return this._values[fieldName];
    },
    set: function (value) {
      console.log('set `' + fieldName + '` field with `' + value + '` value');
      this._values[fieldName] = value;
    }
  });
};

define(Item.prototype, '_id');
define(Item.prototype, 'name');
```

Now when I run this line of code:
```js
Items.findOne();
```

I get in the console:

```
set `_id` field with `5M88NKzK7sNaiNGob` value
set `_id` field with `5M88NKzK7sNaiNGob` value
```

As you can see the `_id` field was set two times but why? I've found the first assignment: https://github.com/meteor/meteor/blob/devel/packages/minimongo/wrap_transform.js#L36

I was looking for the second assignment, without success. But beside that, why at all is Meteor setting `_id` of the transformed object? If I'm transforming a document, I know what I'm doing and I will do it by my self :).

Why is it a problem for me? It's because I have also setters that not only set values but also are tracking modified fields so that when I run the `save()` method on my object it will only updated modified fields. I've made a workaround for that particular case but it would be nice to have it fixed in Meteor.

EDIT:

I've found some clue... The `transform` function here https://github.com/meteor/meteor/blob/devel/packages/minimongo/wrap_transform.js#L24 is the same function that is returned here https://github.com/meteor/meteor/blob/devel/packages/minimongo/wrap_transform.js#L14. So transformation happens twice. I think there is some error due to checking if transformation function exists and it's assigning transform function one more time.

**Comment by glasser** [comment]
I'm going to do my best to at least analyze if not fix this in the next few weeks as part of https://trello.com/c/xR0t2vRd/82-livequery-mongo-driver-and-minimongo-maintenance

**Comment by glasser** [comment]
I'm not sure that this is necessarily a bug — wrapTransform is basically idempotent, as long as you haven't hacked your returned object so that immediately after running `x._id = 'foo'`, `_.has(x, '_id')` is false. I suspect a lot of things in Meteor will break if you can't rely on these basic facts about objects.

That said, it's probably a minor inefficiency to doubly-wrap transforms, but it also makes sense to wrap them at every place that they arrive in the system.  So sure, I'll make sure that transforms don't get wrapped twice, even though I really don't think that what you're doing is particularly supported.
