### ISSUE TITLE
Add email param to password reset link

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3626]
When a user tries to reuse a password reset link, I get an error when calling `Accounts.resetPassword`. The best user experience would be for me to send them another reset email right away, but I first have to ask them to enter their email again, because I don't know who they are.

**Comment by stubailo** [comment]
We were going to do this, but explicitly decided against it. It is nice to be able to display the user's email as well, like "Reset password for user <email>". On the other hand, there is no way to confirm that the email in the URL is actually correct, so it could end up with weird security implications.

**Comment by lorensr** [comment]
You can keep the `resetPassword` API the same, just with a token and no
email. The only negative security implication I can think of is the dev
trusting the email and doing something that's not through the accounts
reset API. Like `Meteor.call 'login_without_pass', email`. You could make
it clear in the docs that it, like all URLs, are untrusted, and it was only
there for convenience.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20email%20param%20to%20password%20reset%20link&body=Migrated%20from:%20meteor/meteor%233626) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
