### ISSUE TITLE
Correctly document what passing a name to a Collection on the client does

### ISSUE THREAD

**Issue by wearhere** [meteor/meteor#3627]
I wish to define a collection on the client _only_, to serve as a target of the low-level `added/changed/removed` publication interface. This requires that the collection be named, which would normally cause it to be synchronized, per the documentation–but it appears that I can keep it from being so synchronized if I define it in a client-only file.

Is this guaranteed to work as I have observed? If so, the documentation should be updated to reflect that naming the collection does _not_ automatically cause the collection to be synchronized.

If this is not guaranteed, how else may I publish to a collection that exists only on the client?

---

(My use case: I am publishing records from a server-side [`RedisCollection`](https://github.com/meteor/redis-livedata) to a client-side `MongoCollection`.)

**Comment by bradvogel** [comment]
+1

**Comment by rclai** [comment]
Yes, you can do that as long as that collection is client only.

**Comment by stubailo** [comment]
There's some tradeoff here between confusing new users and making the behavior really explicit.

**Comment by stubailo** [comment]
This is a docs feature request, you might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by glasser** [comment]
I think the point isn't that leaving the collection out of the server code affects anything here: it's just that you're not *publishing* anything under that name from the server.

It sounds like you're doing the right thing.  There's no magic to make a publication from a Mongo collection come from nowhere (well, except for `autopublish`).

**Comment by wearhere** [comment]
Thanks for the confirmation @glasser. I actually am publishing from the server under the local collection's name, though. Here's some pseudo-code:

```js
// On the server.
Meteor.publish('trackedmessages', function() {
  var self = this;
  var trackedMessagesHandle = Redis.matching('users:jeff:*').observeChanges({
    added: function(key, item) {
      var message = EJSON.parse(item.value);
      self.added('trackedmessages', message._id, message);
    }
  });
  self.ready();
  self.onStop(function() {
    trackedMessagesHandle.stop();
  });
});

// On the client (in a client-only file).
TrackedMessages = new Mongo.Collection('trackedmessages');
```

So, my worry was that initializing `TrackedMessages` with a name–while necessary to use `added`–would cause it to appear on the server, given the following documentation:

> If you pass a name when you create the collection, then you are declaring a persistent collection — one that is stored on the server and seen by all users.

**Comment by hwillson** [comment]
I've moved this over to meteor/docs#109 - closing here - thanks!
