### ISSUE TITLE
suggestion: cd projFolder

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#3629]
T'would be nice if after creating new proj folder meteor would automatically cd that folder in terminal)

**Comment by ErickBastidas** [comment]
Totally agree. Seems the most natural/probable path after creating a project to do this, and it'll reduce one step which is nice too.

**Comment by glasser** [comment]
Unfortunately, this just isn't how the Unix process model works.  A process (such as `meteor`) cannot change the directory of its parent process (like your shell).  There are some very complicated hacky things one could do to make this sort of work, but they would definitely be flakier than just reminding you to run `cd` (and they would also be confusing to more experienced shell users who assume that commands can't change your current directory).
