### ISSUE TITLE
Document recommended createUser error handling

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3632]
Let devs know that if `error.reason is 'Email already exists.'`, they should tell the user that either they've already created an account, in which case they can try logging in, or someone else has signed up using their email, and they can recover the account by resetting the password.

http://docs.meteor.com/#/full/accounts_createuser

**Comment by glasser** [comment]
Thanks for the docs feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by abernix** [comment]
:smile:
