### ISSUE TITLE
Accounts.emailTemplates.resetPassword.html is very confusing! An optional method that i end up having to duplicate code

### ISSUE THREAD

**Issue by aj07mm** [meteor/meteor#3633]
I was having some troubles using this method, its not clear the usage. I had to check in this question on Stackoverflow: https://stackoverflow.com/questions/22569090/using-accounts-emailtemplates-resetpassword-html-correctly-in-meteor

And ended up having to duplicate code for both "text" and "html" instead of having an attribute for the type of email you have to send. Not so simple and neat

**Comment by glasser** [comment]
I'm not sure I understand your question.  (It sounds like StackOverflow is being more helpful for this.)

If you want to send an HTML-only email, set the html attribute. If you want to send a text-only email, set the text attribute.  If you want an email that works well with for both HTML and plaintext-only clients, set both.
