### ISSUE TITLE
Page doesn't jump to top on iOS when navigating

### ISSUE THREAD

**Issue by CaptSaltyJack** [meteor/meteor#3634]
I noticed something odd. When navigating a Meteor site on iOS Safari, the page doesn't jump to the top, though it does on desktops. I had to code this into `router.js` as a workaround:

    Router.onAfterAction ->
      $(window).scrollTop 0

Is this a known issue?

**Comment by stubailo** [comment]
Hi, this looks like an issue with Iron Router, which is not maintained by the same people as Meteor. Try filing an issue there: https://github.com/EventedMind/iron-router/issues
