### ISSUE TITLE
Spacebars compiler should fail when a contenteditable DIV has interpolation tags in it's contents

### ISSUE THREAD

**Issue by avital** [meteor/meteor#3635]
(See #1964 -- this use-case doesn't work.)

We should add an error when Spacebars parses a contenteditable DIV with any interpolation inside of it, eg `{{foo}}` or `{{> otherTemplate}}`.

Similar to React's https://github.com/facebook/react/issues/1466, but we can do better by allowing initial contents if they aren't dynamic.

**Comment by avital** [comment]
(For people looking for a workaround -- https://github.com/meteor/meteor/issues/1964#issuecomment-57948734 looks appropriate)

**Comment by mitar** [comment]
How would you detect if something is content editable? We enable that dynamically, when user clicks on "edit" button.

**Comment by avital** [comment]
Hmm. Interesting :)

React can do this because any time a property were to change it would re-run the render function completely... Don't have an answer off the top of my head.

**Comment by dkoo** [comment]
Not sure if this helps anyone, but I managed to work around the contentEditable bug by nesting the contentEditable elements inside their own child template.

````
<template name="parent">
	{{#each item}}
		{{> child}}
	{{/each}}
</template>
````

And then populating the child elements using `onRendered()`:

````
Template.child.onRendered(function() {
	var form = document.querySelector('.container'),
		fields = form.getElementsByTagName('div'), // the contentEditable elements
		data = Template.currentData(); // access to the data

	for ( var i = 0, len = fields.length; i < len; i++ ) {
		var field = self.getAttribute('data-name'),
			value = data[field];

		if ( value ) {
			fields[i].innerHTML = data[field];
		}
	}
});
````

Nesting them inside their own child template seems to be necessary, as the `onRendered()` function fires before all the child elements are ready in the DOM.

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#175 - closing. Thanks!
