### ISSUE TITLE
Log where are installed packages and how much they weigh

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3637]
As seen in #3614, to help users control Meteor’s disk usage, it would be useful to output a message along the lines of `meteor-tool@1.0.40 installed, 152MB stored in ~/.meteor/meteor-tool` when Meteor shows the “updating packages” spinner.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Log%20where%20are%20installed%20packages%20and%20how%20much%20they%20weigh&body=Migrated%20from:%20meteor/meteor%233637) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
