### ISSUE TITLE
Refactor minimongo and observe-sequence to remove dependency

### ISSUE THREAD

**Issue by murillo128** [meteor/meteor#3638]
Currently the meteor-observe-sequence package depends on meteor-minimongo only for a couple of LocalCollections functions:

_idStringify
_idParse
_diffQueryUnorderedChanges which also depends on 
_makeChangedFields
_diffObjects

I have already seen in the comments in minimongo/diff.js that some of this functionality should be moved out to an "ObserverHelper" package. 

The only missing functions in diff.js would be 
_diffQueryChanges
_diffQueryOrderedChanges

Which could go also to this ObserverHelper package.

We are currently working on lib with client only packages (we will provide more details quite soon), so been able to not include full minimongo code could save us about 20% in the total lib size.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

(The Blaze tag is because `observe-sequence` is primarily used by Blaze.)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Refactor%20minimongo%20and%20observe-sequence%20to%20remove%20dependency&body=Migrated%20from:%20meteor/meteor%233638) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
