### ISSUE TITLE
Using debugOnly = true on Package.describe makes api.export() not work

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#3639]
Is this intentional?

```js
Package.describe({
  name: 'lai:ddp-inspector',
  version: '0.0.3',
  summary: 'Allows you to see all DDP activity in the client-side.',
  git: 'https://github.com/rclai/meteor-ddp-inspector.git',
  documentation: 'README.md',
  debugOnly: true
});

Package.onUse(function(api) {
  api.versionsFrom('1.0');

  api.use([
    'templating',
    'session',
    'jquery'
  ]);

  api.addFiles([
    'console-log-polyfill.js',
    'lai:ddp-inspector.html',
    'lai:ddp-inspector.css',
    'lai:ddp-inspector.js'
  ], ['client']);

  // this doesn't work when debugOnly = true
  api.export('DDPInspector', 'client');
});
```

https://github.com/rclai/meteor-ddp-inspector
Right now it's not being exported so just make sure you add that line above.

**Comment by glasser** [comment]
Yes, this is intentional.  Exports from a package `D` become (pseudo-)globals in packages `P` that use them.  We didn't think it would be a good idea to make the set of globals in `P` depend on whether or not you're building in debug mode.  You can still access the exports via `Package.D.exportName`.

**Comment by natb1** [comment]
I can't find anything in the docs that would indicate this.

**Comment by mcbain** [comment]
As people start to mark all their test packages as debugOnly:true, you can remove the --production flag from test-packages - since it's not working anymore.
