### ISSUE TITLE
Document a way to access the Node Mongo driver

### ISSUE THREAD

**Issue by theduke** [meteor/meteor#3640]
Is there any way to lock the database on the server?

In mongo I would call db.fsyncLock().

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This is a subset of a frequently requested feature, which is direct access to all the various Mongo APIs that don't have special Meteor behavior.  I think we should actually do this finally.

We should provide access to:
- The raw Node Mongo driver module
- Its version number
- A simple wrapper or two to get you the `db` object for a given Meteor Mongo connection, and maybe a Collection

That said, people using this should be aware that future upgrades may replace the module with a backward-incompatible version.  (This would probably be a major version bump for the `mongo` package.)

**Comment by mitar** [comment]
https://github.com/peerlibrary/meteor-directcollection provide you with a way to send arbitrary commands through the Meteor Mongo connection.

**Comment by mitar** [comment]
(Do observe that methods which are provided by directcollection are blocking, so it is not just exposing the API, but also making sure that it plays nice with Meteor.)

**Comment by glasser** [comment]
Great; it looks like you should now be able to use these new documented APIs in implementing your package.

**Comment by theduke** [comment]
Greath, thank you guys.

**Comment by zstew** [comment]
Do I understand that the resolution is to use https://github.com/peerlibrary/meteor-directcollection 
to access the mongo connection?

I'm really hoping to be able to write something like:
var myLongedForMongoConnection = Meteor.getMongoConnection();

this would be super useful to me. The above library seams to expect fibers style code, and I've got a lot of code I'd like to reuse that uses callbacks.

**Comment by glasser** [comment]
No, I was referring to the rawCollection and rawDatabase methods on Mongo.Collection, added in 1.0.4.  You're probably looking for `var myLongedForMongoConnection = someCollection.rawDatabase()`.

**Comment by zstew** [comment]
yes! that's what I'm looking for!  Thanks glasser!  I'm reading up on it.
