### ISSUE TITLE
Provide an easy way to load NPM dependencies on the client

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3642]
I am trying to port React.js example to Meteor and I am spending much too much time on getting the Color NPM dependency to work on the client:

https://github.com/ryanflorence/reactconf-2015-HYPE/blob/master/demos/06-itunes-style-interface/utils/Colors.js

So simple code, but so hard to get it to work in Meteor.

If Meteor wants to compare with other frameworks, I really think it should be easy to load existing NPM dependencies on the client.

**Comment by glasser** [comment]
Is this basically the same as #1353?  A way to get files out of npm packages and into other parts of your app?  Or does it need something more to make it specifically in the client?

**Comment by mitar** [comment]
Hm, #1353 is to get a path to the file. This one is to get a NPM package on the client. Something like browserify. I think we had one other ticket to allow you to get a file out of the NPM as an asset. Then #1353 is to get path to a file. And this is to simply load a normal NPM code one the client and expose the symbols.

**Comment by hwillson** [comment]
Thanks to the [npm support added in Meteor 1.3](https://github.com/meteor/meteor/blob/devel/History.md#es2015modules), this issue can be closed. Thanks!
