### ISSUE TITLE
Make core docs that got moved to Atmosphere READMEs discoverable from docs.meteor.com

### ISSUE THREAD

**Issue by emgee3** [meteor/meteor#3643]
I was under the impression that the documentation for `browser-policy` was once listed on http://docs.meteor.com but I can no longer find it there. (I did find it eventually alongside the [source](https://github.com/meteor/meteor/blob/devel/packages/browser-policy/README.md).)

Additionally, both `showdown` and `markdown` are listed in the TOC under Packages, but the `showdown` listing is linked to a non-existent anchor, which scrolls one top of the page, as does the `stylus` listing. I also found it odd that the `spiderable` listing pointed to Atmosphere.

If the idea is keep the docs compact, then I'd recommend either listing all the MDG-packages, or linking to https://atmospherejs.com/mdg, but right now the Packages section is inconsistent and confusing.

**Comment by glasser** [comment]
I'm going to pull the "things are just broken" part into its own issue

**Comment by abernix** [comment]
I've opened an issue at meteor/docs#16 for the `browser-policy` documentation.  `showdown` has been merged into `markdown` and `markdown` is now documented [here in the newly revamped Meteor Docs](http://docs.meteor.com/packages/markdown.html).  Please open any additional issues (or help contribute!) at [the newly-created Meteor Docs repo](http://github.com/meteor/docs/).
