### ISSUE TITLE
Package description parsed as too long if there's no space after the `#` in the header

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3644]
Details at https://github.com/MeteorPackaging/proj4js/commit/82f0c98dd314c314d57f81e324fe953f692e3665#commitcomment-9595124

@mrjf - can you pitch in?

**Comment by glasser** [comment]
That's intentional — we follow the CommonMark spec.

http://spec.commonmark.org/0.16/#example-25

**Comment by mrjf** [comment]
Thank you, turns out this is also causing the README to not display as intended on NPM, so hopefully it can be fixed in the repo.

https://www.npmjs.com/package/proj4
