### ISSUE TITLE
Cordova: hide location bar in OAuth popups

### ISSUE THREAD

**Issue by teknologist** [meteor/meteor#3648]
Hi,

I have come across this issue. The rest is working great but that location bar is pretty ugly on android. (Cordova's InAppBrowser).

On the same project using ionic/Angularjs I managed to hide that by passing location=no,hidden=yes args to the window.open call.

If I am not mistaken, the modification needs to be made here:

meteor/packages/oauth/oauth_cordova.js

On line 63:
 var popup = window.open(url, '_blank', 'location=yes,hidden=yes');

changed by

 var popup = window.open(url, '_blank', 'location=no,hidden=yes');

Or at least make it configurable.

(For the moment I run a forked version with that modification but I would be so happy to use the official one)

By the way, I am literally falling in love with Meteor ! :-)

Thanks in advance,

Eric

**Comment by teknologist** [comment]
Hi @minimao,

I have already done this on my side and I am happy with how it works.

Was more wondering if this would make it into meteor ?

I see you have signed the contributor agreement so maybe we have chance for it to make it into next meteor release !

Thanks for accepting my proposal ! IMHO, that location bar is so ugly on android, it really screams "Low quality UI" to the end user. Plus it is of no use. Last but not least, considering the effort we put in gorgeous UI/UX, it is nice to see it go away. :-)

Cheers,

Eric

**Comment by estark37** [comment]
In some ways, it's nice for the user to be able to see the location bar to verify that they are on https://foo.com before they enter their foo.com password. Of course, a malicious app could always fake the location bar, but it's not so hard to imagine a bug in an oauth package that, for example, loads http://foo.com instead of https://foo.com in the InAppBrowser, and the location bar is the only thing that would stop such a bug from being completely disastrous. (Or maybe an open redirector bug in foo.com that can take you to an evil phishing site?) So maybe it should be shown by default but have a configuration option to turn it off?

**Comment by teknologist** [comment]
@estark37  I see your point.

I am ok if it is configurable. And I am aiming for best and most beautiful experience possible for my user. In that style state, that location bar cannot stay there. simply too ugly. Maybe someone should hack the cordova Inappbrowser and make a more stylish location bar. (plus as you said, that bar can be faked too)

Now, a few points:

1) that location bar screams "hybrid low end" to plain end user and is not very nice in a gorgeous mobile app.

2)when you use native apps they could also trick you into putting your password.And they could imitate it a lot better! ;-)

3) I think above all the number one security rule is don't install an app you don't trust. Native or Hybrid.

Last but not least, passwords are not secure, that is why I use 2 factor auth whenever it is available... but I understand most users don't. :-)

**Comment by estark37** [comment]
The real solution is probably to use native phonegap plugins for OAuth (e.g. https://github.com/Wizcorp/phonegap-facebook-plugin).

**Comment by teknologist** [comment]
@estark37 I would love that ! 
Indeed it'd be the best solution as it would let the user use the OS configured account. 
Also IMHO that'd be the most secure solution.

Best user experience + most secure option. It is a winner.

unfortunately it is beyond my skills.  Also haven't see a Google+ native plugin. Only FB.

Thanks again for your feedback @estark37 ! :-)

**Comment by mininao** [comment]
@estark37 @teknologist I'll try to make a PR with the configuration uption, perhaps by adding an option to Meteor.loginWith<ExternalService> ?

**Comment by teknologist** [comment]
@mininao Thanks!That'd be great.  

Now, I agree 200% with @estark37 , the real solution would be to use the native phonegap plugins for OAuth in meteor oauth. That'd be a game changer. Best Ergonomics (UX) and more secure.

That'd be really really sweet !

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by teknologist** [comment]
Thanks @glasser ! will have a look. I like how you changed the title... ;-)
You are right, ugly is subjective...

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Comment by shadowzick** [comment]
still getting this on 1.2.1 while using accounts-facebook, accounts-twitter and accounts-google. help!

**Comment by abernix** [comment]
@shadowzick Could you try this with Meteor 1.3.2.4 which has major upgrades to Cordova that could not be included in 1.2.1?
