### ISSUE TITLE
built issue with esprima

### ISSUE THREAD

**Issue by quickj** [meteor/meteor#3649]
When i use "meteor" command to build the application, the meteor throw some exception, it means lack the **"esprima"** module. so i used the "npm install esprima" and successfully installed this module.
i built the application again,but it throw another exception that **"node_modules/esprima/bin/esparse.js:1:15: Unexpected token ILLEGAL"**
somebody has any idea about this issue?

**Comment by glasser** [comment]
`npm install esprima` was not the correct solution to your problem.  (What directory did you run it in?)

If you can undo the effect of your npm command somehow (perhaps a clean install of meteor) and report the original "some exception", we can help you.

**Comment by simsketch** [comment]
I believe this was his original error.
MacBook-Pro:songroll-sky user$ meteor
[[[[[ ~/Github/songroll-sky ]]]]]             

=> Started proxy.                             
=> Started MongoDB.                           
   Loading plugin `initializing-npm-supp...  |

-> updated `npm-container` to support Meteor 1.2

                                              
Changes to your project's package version selections:
                                              
npm-container  upgraded from 1.0.0 to 1.1.0   

W20150809-21:38:23.916(-4)? (STDERR)          
W20150809-21:38:23.919(-4)? (STDERR) /Users/avivakadin/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150809-21:38:23.919(-4)? (STDERR) 						throw(ex);
W20150809-21:38:23.919(-4)? (STDERR) 						      ^
W20150809-21:38:23.919(-4)? (STDERR) Error: Cannot find module 'esprima'
W20150809-21:38:23.919(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150809-21:38:23.920(-4)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150809-21:38:23.920(-4)? (STDERR)     at Module.require (module.js:364:17)
W20150809-21:38:23.920(-4)? (STDERR)     at require (module.js:380:17)
W20150809-21:38:23.920(-4)? (STDERR)     at Object.Npm.require (/Users/avivakadin/Github/songroll-sky/.meteor/local/build/programs/server/boot.js:130:18)
W20150809-21:38:23.920(-4)? (STDERR)     at cmd (packages/mrt:server-eval/helpers.js:116:1)
W20150809-21:38:23.920(-4)? (STDERR)     at /Users/avivakadin/Github/songroll-sky/.meteor/local/build/programs/server/packages/mrt_server-eval.js:850:4
W20150809-21:38:23.920(-4)? (STDERR)     at /Users/avivakadin/Github/songroll-sky/.meteor/local/build/programs/server/packages/mrt_server-eval.js:906:3
W20150809-21:38:23.920(-4)? (STDERR)     at /Users/avivakadin/Github/songroll-sky/.meteor/local/build/programs/server/boot.js:222:10
W20150809-21:38:23.921(-4)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
