### ISSUE TITLE
Accessing parent and child templates in Blaze

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3650]
I just read [this article](https://medium.com/@stubailo/upcoming-features-in-meteor-blaze-b537cf9c09e9) so I thought I'd share some recommendations.

Last week or so I was reading through the Tracker source which is absolutely amazing and I ran across [this discussion](https://meteor.hackpad.com/Lickable-Forms-and-Components-6CVspZsVwJY) about building bidirectional binding forms into Blaze. 

I actually started working on this because I really liked the idea, but the problem I ran into is that the only way to get information from one template to the next is through helpers. I started out with a `{{#form name='new-user'}}` as suggested in the discussion, and the form had a reactive dict property. Any of the form elements like the `{{>text name='first name'}}` ought to be able to transparently reactively update the reactive dict in the `{{#form}}` instance without having to pass a bunch of helpers around. Finally, upon submit, the `{{#form}}` should catch the event, `event.preventDefault()`, etc., validate, and pass a nice object into the the `submit form[name=new-user]` event any containing templates. 

So here are the things you cannot do that I think you ought to be able to do:

1. access parent templates, for example, in the `text` template, you could do something like this to update the `form` template:

```
Template.text.created = ->
  @name = @data.name
  @value = new ReactiveVar()
  @autorun ->
    @parentTemplateInstance('form').formData.set(@name, @value.get())

Template.text.events
  'change input': (e,t) -> t.value.set(e.target.value)
```

While you're at it, it seems you may as well make a function the other way,  `@childTemplateInstance('form')` -- that may become useful at some point. Perhaps if there is no form, you could use a `{{>text name='search'}}` and `@autorun` to reactively get its value to update search results. This seems like the more meteor way of doing things as opposed to listening to events...

2. propagate events to parent templates.

```
Template.form.events
  'submit form': (e,t) ->
    e.preventDefault()
    e.preventPropagation()
    # get all the values out of the reactive dictionary. If there was a schema passed
    # to the form template, then validate the fields, etc.
    data = t.validateForm()  
    if data
      t.triggerEvent("submit form[name=#{t.name}]", [data])
    return false

Template.main.events
  'submit form[name=new-user]': (e, t, data) ->
    Players.insert(data)
```

As you can see, this entire form system is transparent to the end user! Anyways, I'd love to hear your thoughts.

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests). Looks nice! This is definitely the kind of thing we want to build soon. Thanks for the input.

**Comment by ccorcos** [comment]
Sweet! Let me know how I can help.

**Comment by ccorcos** [comment]
looks like [template-extensions](https://github.com/aldeed/meteor-template-extension) has this functionality...

**Comment by ccorcos** [comment]
Couple things... This has been helpful:

```
Blaze.TemplateInstance.prototype.getParentNamed = (name) ->
  template = this
  while template
    if name is template.view.name.split('.').splice(1).join('.')
      return template

    view = template.view.originalParentView or template.view.parentView
    
    while view and (not view.template or view.name is '(contentBlock)')
      view = view.originalParentView or view.parentView

    template = view.templateInstance?()

  return template
```

But now I'm trying to trigger an event in a parent template but there seems to be some kind of context issue -- I believe my error is because `Blaze.currentView` is null. I'm not sure how to dig deeper into this, but if you can help me figure out some way to trigger a parent template event, I'll be a happy camper :)

Here's why I'm trying to do

```
Template.nav.events
  'click .left': (e,t) ->
    for eventMap in t.view.view.template.__eventMaps
      if eventMap['nav.left']
        eventMap['nav.left'](e,t)
```

**Comment by ccorcos** [comment]
Oy, I got it. I was overwriting the `view` variable

```
Template.nav.created = ->
  @view = @getParentNamed('view')
```

I changed it to `@v = ...` and then use apply `eventMap['nav.left'].apply(t.view, [e,t])`

**Comment by lorensr** [comment]
I wound up doing something similar. Sometimes I'm in a child template, and I know the name of ancestor template whos data I need to access, and I know the data field name, but I don't know how many levels deep I am, so I have this UI helper:

```coffeescript
  tvar: (key, template_name) ->
    t = Template.instance()

    if t[key]?
      t[key].get()
    else
      cur = Template.instance().view
      while cur.parentView
        cur = cur.parentView
        if cur.name is 'Template.' + template_name
          return cur._templateInstance[key].get()
 ```       
It would be great to see something like `getParentNamed` added to meteor.

**Comment by ccorcos** [comment]
definitely. With the new release of meteor, they've changed some of the `Template.instance()` stuff so my code may be stale.

**Comment by mitar** [comment]
Please look at [template-extensions](https://github.com/aldeed/meteor-template-extension) package. There are functions for accessing parent templates. But I found it much better than trying to accessing by name is accessing it by field. So `.get` will allow you to access a filed on the first ancestor template instance which defines it. This makes code reuse and restructuring much easier. You do not really want to have to require developers to think who is "calling" (or including) them.

In [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components#user-content-reference_instance_componentParent) I went even further and you can now have both parent and children accessing.
