### ISSUE TITLE
App launch curtailed when Meteor builds for cordova and meteor-platform is itemized

### ISSUE THREAD

**Issue by dgtlife** [meteor/meteor#3657]
When `meteor-platform` is itemized in the `.meteor/packages` file, as in:
```
#meteor-platform
blaze
check
ddp
deps
ejson
fastclick
jquery
launch-screen
livedata
logging
meteor
mobile-status-bar
mongo
random
session
spacebars
templating
tracker
ui
underscore
webapp
```

and one runs
`meteor run ios`, `meteor run android`, `meteor run ios-device`, or `meteor run android-device`
the launch of the app will hang at the loading of the `index.html` file, as in (ios case):
```
I20150206-00:28:06.479(-8)? (ios) Finished load of: file:///Users/<username>/Library/Developer/CoreSimulator/Devices/<somealphastuff>/data/Containers/Bundle/Application/<somealphastuff>/<appname>.app/www/index.html
```
To reproduce, do the following:
```
$ meteor create someApp
$ cd someApp
$ meteor add-platform ios
$ meteor add-platform android
$ meteor run ios
```
Confirm that app loads completely in the simulator.
Edit `.meteor/packages` to comment out the `meteor-platform` line and replace it by the package list for `meteor-platform` (provided above). Then run
```
$ meteor run ios
```
Confirm that app launches and loads to generic splash screen and spinner spinning endlessly, and the last line in the meteor console reports the loading of the `index.html` file.
Repeat for `ios-device`, `android`, and `android-device`.

I experienced this on Mac OS X 10.10.2 with Meteor 1.0.3.1, Xcode 6.1.1, and Android SDK Tools 23.0.5.

**Comment by glasser** [comment]
That isn't all of the packages used by `meteor-platform`. Specifically, you're missing `reload` and `autoupdate`. Does it work when you add those?

**Comment by dgtlife** [comment]
It's the list derived from the result of `meteor show meteor-platform'. Adding `reload` and `autoupdate` to the list does not change the behavior. Loading still hangs at the loading of the `index.html` file.

**Comment by glasser** [comment]
Yes, that's the list of implied packages, but it doesn't include the used packages.  If you ask for the specific version (`meteor show meteor-platform@1.2.1`) you get those too at the bottom.  (@ekatek: this UX is intentional right?)

So this does actually seems like some cordova bug where it cares about whether some package was used vs implied?

**Comment by dgtlife** [comment]
I see. Implied vs used is just a tad counter-intuitive for me ... but I learnt something. I also went and looked at the `package.js` file in the `meteor-platform` package and observed that in addition to the implied and used packages, there are also the Cordova.depends packages. Once these Cordova packages are added at the command line, like so,
```
$ meteor add cordova:org.apache.cordova.device@0.2.11
added cordova plugin org.apache.cordova.device
$ meteor add cordova:com.meteor.cordova-update@'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2'
added cordova plugin com.meteor.cordova-update
```
everything behaves the way it should.
