### ISSUE TITLE
Meteor db connection resilience issues

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#3660]
If there is a Meteor app and a separate mongo database & the mongo database has issues Meteor apps have problems with getting back to normal once the mongo connection returns.

There is another issue #3038 on an initial connection. This is when there is a problem after a month of running for a short period of time. - I'm not entirely sure if they're similar.

The Meteor app won't reconnect automatically and seems to freeze up until its restarted.

We discovered the issues on our production apps (oplog enabled) and now that it has happened I can recover a few times its also happened on `meteor deploy` infrastructure. The thing is the app will restart after idle-ness on `meteor deploy`. A `meteor bundle` app running on node needs to be restarted.

The behaviour should be that it attempts to reconnect or try to, in case the mongo connection is temporarily cut for a short period of time as is more likely to be the case over periods of time.

**Comment by glasser** [comment]
There are definitely attempts in the code to make reconnection work.  So we're really going to need a reproduction to be able to work on this.  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by filosof86** [comment]
Hi,

Sorry for reopening, but I'm currently suffering from this issue and if we use the production bundle the STR is pretty simple:
CentOS 7:
1. Build meteor bundle and install it on the server.
2. Create a systemd service to handle the application.
3. Create mongo replication set to deal with meteor app which consists of 3 nodes.
4. Shut down(also you can kill them with kill -9 ) 2 or three mongo nodes, wait for some time, so the app throws some errors like "connection refused" or 'failed to connect to server', etc.
5. Check the application

Actual result: the app is hung until it's restarted.

Expected\proposed result\change: the meteor server is crashed with some error code > 0 so the systemd service restarts it by itself using 'on-failure' restart condition

TIA
