### ISSUE TITLE
Feature Request: Confirmation dialog on `meteor reset`

### ISSUE THREAD

**Issue by hitchcott** [meteor/meteor#3661]
**_2 Upvotes**_ As `meteor reset` is a destructive operation, would it make sense to require a `Y/N` confirmation in the CLI?

I just got stung by this, because I mistyped `meteor refresh` to resolve https://github.com/meteor/meteor/issues/3653. Doh!

**Comment by theosp** [comment]
+1

**Comment by mariorodriguespt** [comment]
:+1:

**Comment by lorensr** [comment]
I would find this helpful as well.

**Comment by glasser** [comment]
Commented on PR.

**Comment by hwillson** [comment]
There is a more recent/active discussion about this in #7789, so I'll close this issue. Thanks for posting this feature request originally!
