### ISSUE TITLE
6to5 build option

### ISSUE THREAD

**Issue by fourq** [meteor/meteor#3662]
How impossible is it to use 6to5 in the build process to allow a subset of es6 options while in development?

**Comment by Slava** [comment]
Sounds like it can be implemented in a package like this one using Google's traceur compiler: https://atmospherejs.com/mquandalle/harmony

**Comment by fourq** [comment]
I didn't think to look for a package. I'm not thrilled about named my files .next.js, but it's something to work with. Thank you!

**Comment by fourq** [comment]
btw, I tried that package you found but it didn't work. No errors, just didn't transpile. Here's a package I created to transpile with 6to5 https://atmospherejs.com/fourq/6to5
