### ISSUE TITLE
Allow object and keyword arguments to Spacebars inclusion & blocks

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3663]
A common desire I have is to do:

`{{> subtemplate item foo="bar"}}`

So that the data context in `subtemplate` has all the `item` fields plus a `foo` field. While I could make a helper (like http://stackoverflow.com/questions/28015971/pass-parameters-to-template-without-overriding-data-context), it would be nice if it was built-in – Spacebars would check to see whether `item` was a defined helper, and if it wasn't, it would combine it to be the data context.

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
Possible duplicate #3913. Probably useful for https://github.com/peerlibrary/meteor-blaze-components/issues/12 as well.

**Comment by stubailo** [comment]
The whole situation with positional and keyword arguments is pretty crazy, and it's not great that it isn't consistent for template inclusions and helpers. Personally I'd be in favor of dumping positional arguments entirely in favor of keyword args only (like React).

**Comment by lorensr** [comment]
Closing in favor of Guide-recommended keyword-only args :)

**Comment by mitar** [comment]
Also I think this would solve most similar issues: https://github.com/meteor/blaze/issues/5
