### ISSUE TITLE
Delays in tailable cursors

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3664]
I have a sample app which is writing to a capped collection and then uses a tailable cursor to read from it (using it as a message bus). The issue is that it does not perform well. This is first example. If I run the [reproduction](https://github.com/mitar/meteor-issue3664), it logs messages like:

```
I20150206-20:54:08.405(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:08 GMT-0800 (PST) }
I20150206-20:54:09.410(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:09 GMT-0800 (PST) }
I20150206-20:54:10.410(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:10 GMT-0800 (PST) }
I20150206-20:54:12.417(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:12 GMT-0800 (PST) }
I20150206-20:54:12.419(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:11 GMT-0800 (PST) }
I20150206-20:54:13.419(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:13 GMT-0800 (PST) }
I20150206-20:54:14.423(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:14 GMT-0800 (PST) }
I20150206-20:54:15.424(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:15 GMT-0800 (PST) }
I20150206-20:54:17.432(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:17 GMT-0800 (PST) }
I20150206-20:54:17.435(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:16 GMT-0800 (PST) }
I20150206-20:54:18.435(-8)? Message { type: 'test', data: Fri Feb 06 2015 20:54:18 GMT-0800 (PST) }
```

See one second delay at 10 and 15 second? This is regular. It happens exactly every 5 seconds.

(Tested on current `master` and `devel` branches.)

**Comment by glasser** [comment]
Thanks for the reproduction.  Will try to look into this soon.  For what it's worth, observeChanges tailable was kind of an experimental feature that we're not currently using for anything (I think).

**Comment by glasser** [comment]
Unfortunately, it doesn't look like I got to this as part of the 1.0.4 maintenance work :(  (Tailable observe is an experimental undocumented feature, but it uses the same code as oplog tailing so it's worth understanding this situation better.)

**Comment by hwillson** [comment]
I updated the repro to Meteor 1.5.1 and have verified that this issue no longer exists. Closing - thanks!
