### ISSUE TITLE
Strange behavior while having a running tailable cursor

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3665]
Not sure how to make a reproduction. Some time ago I was making a messaging channel for PeerDB and I tried to use capped collection with tailable observe on it for it. After I implemented it, [the whole site become very sluggish. All other publish functions become slow](https://github.com/peerlibrary/meteor-peerdb/commit/d20d057702fb6a438106bdb3d137f471fbd56044). I reimplemented everything with normal observe hopping for oplog, with TTL index on the collection. But now that you are putting work again into this part of the codebase, I decided to report it. It is hard to get that "whole site slow" reproduction, but [here is one which I think is a bit similar](https://github.com/mitar/meteor-issue3665).

If you run it and open a client side in the browser, you will get console output for the normal publish. What is strange that the order of documents in the observe does not progress in the timestamp order:

```
I20150206-21:20:02.520(-8)? vh2PpuNmXwc625DN3 { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:02.622(-8)? TdEXMWDQXDLwdanjg { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:02.724(-8)? Endn6xSD6yT7XA7ET { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:02.825(-8)? yXGQGdqKwQRaNEtD2 { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:03.036(-8)? Tp7HGQLkkWuSF9N6z { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.127(-8)? MSWYyXxdmDkM9x8xA { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:03.127(-8)? EqksBo54D7DkpD7Ay { test: Fri Feb 06 2015 21:20:02 GMT-0800 (PST) }
I20150206-21:20:03.135(-8)? RhfFwvHbyvhtgLXS9 { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.241(-8)? xPmyEj6wqsBfCR6pH { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.452(-8)? vBFdWkn9r7eK3Dr2x { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.554(-8)? ExPCi3DCPYkQNnKA8 { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.657(-8)? RNK3dfeFM6dniGhTf { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.761(-8)? wDkaKEELKtRSuAN9Z { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:03.966(-8)? 4JsZkMHpCCMn9H43p { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:04.069(-8)? zkzZJ5LdQvwrRQAHw { test: Fri Feb 06 2015 21:20:04 GMT-0800 (PST) }
I20150206-21:20:04.130(-8)? svH8CEgkBdsrLDqTW { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:04.131(-8)? B2TqNB7LDySJekBXm { test: Fri Feb 06 2015 21:20:03 GMT-0800 (PST) }
I20150206-21:20:04.174(-8)? ZDtHarHTz7TPwZSEt { test: Fri Feb 06 2015 21:20:04 GMT-0800 (PST) }
I20150206-21:20:04.383(-8)? gS2CHbzPg6R7QDZwK { test: Fri Feb 06 2015 21:20:04 GMT-0800 (PST) }
I20150206-21:20:04.484(-8)? R8q8WmLHSPyRAQeZS { test: Fri Feb 06 2015 21:20:04 GMT-0800 (PST) }
```

See those cases when there are some injected second 03 when second 04 already starts. Same for 02 when 03 is already printed out for the first time.

All this disappears if I remove the tailable observe code. Then documents are processed in the correct order.

**Comment by glasser** [comment]
Thanks.  Out of curiosity, is it any better with current `devel`?

**Comment by glasser** [comment]
Unfortunately, it doesn't look like I got to this as part of the 1.0.4 maintenance work.  (Tailable observe is an experimental undocumented feature, but it uses the same code as oplog tailing so it's worth understanding this situation better.)

**Comment by mitar** [comment]
No problem. This one is not critical. Much more is #2315 and #2691. We have now code ridden with workarounds because of this. This is really failing a lot.

**Comment by hwillson** [comment]
I just ran the linked to repro and was able to reproduce the output listed above. I then updated the repro to use 1.5.1 though, and the result change drastically. The client side `console.log` stopped, and if left running for a few minutes, my browser (Chrome 60) hung completely. Definitely still an issue lurking here somewhere.

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in 3 years. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed. Thanks!
