### ISSUE TITLE
Access child and parent template instances

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#3667]
My wish for the [upcoming features in Blaze](https://medium.com/@stubailo/upcoming-features-in-meteor-blaze-b537cf9c09e9) would be a way to access the child and parent template instances.
There seems no way to do this at the moment but it can be very helpful in situations where you include templates on different pages but still want a way to modify things on the included template (instance).

**Comment by stubailo** [comment]
Duplicate of #3650
