### ISSUE TITLE
Accounts-ui `allowChangingPassword` logic is not sound

### ISSUE THREAD

**Issue by hpx7** [meteor/meteor#3669]
See https://github.com/meteor/meteor/blob/devel/packages/accounts-ui-unstyled/login_buttons_dropdown.js#L46-L53

Checking for the `username` field doesn't work for me because I normalize the username across accounts-\* packages, so the `username` field is set for me even if I use an oauth package.

The more general question is how to figure out which service a user is currently logged into. The only way I can think of is intercepting the login event on the client and locally store the service being used. I suppose #3593 allows this?

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Have you considered using a different field than `username` for your normalized value?

As for finding out which service a user is currently logged into - do you have users with multiple services on the same user document? How do you manage them? Just curious here. #3593 might not include any information about the login and just fire an event that a login has occurred.

**Comment by hpx7** [comment]
If I normalize to a different value, there will still be a problem because then `allowChangingPassword` will always be false (I don't set an email).

Currently I have only one service per user document, but in the future I might use something like [accounts-meld](https://atmospherejs.com/splendido/accounts-meld) and have multiple services per document. Thus simply checking for the existence of a particular service on the user document wouldn't work.

If there is no other way to know which service a user is logged into, then ensuring #3593 allows this would be very helpful.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Accounts-ui%20%60allowChangingPassword%60%20logic%20is%20not%20sound&body=Migrated%20from:%20meteor/meteor%233669) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
