### ISSUE TITLE
Fix linker bug for package names starting with digits

### ISSUE THREAD

**Issue by fourq** [meteor/meteor#3670]
If I name a package plugin starting with an illegal char I'd like to see an error that indicates that it's the name, or whatever actually caused the issue. I see that it points to a line and location, but I'm not sure that file lives outside of the build process in memory after failing.

```javascript
Package.registerBuildPlugin({
  name: "6to5",
  use: [],
  sources: [
    'plugin/6to5.js'
  ],
  npmDependencies: {
    "gulp-6to5": "3.0.0",
    "gulp-sourcemaps": "1.3.0",
    "gulp": "3.8.10"
  }
});
```

```sh
❯ meteor add fourq:6to5
6to5: updating npm dependencies -- gulp-6to5, gulp-sourcemaps, gulp...
 => Errors while adding packages:

While loading plugin `6to5` from package `fourq:6to5`:
packages/6to5_plugin.js:36:10: Unexpected token ILLEGAL
```

**Comment by glasser** [comment]
No, this should be a valid package name.  I think this is a bug in the `packageDot` function in linker, which will generate a line like `Package.6to5 = {};` which is bogus.

It will make it easier to fix your bug if you provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

This should also be a pretty straightforward pull request.

**Comment by fourq** [comment]
~/Src/Code
❯ git clone git@github.com:fourq/meteor-issue-3670.git
Cloning into 'meteor-issue-3670'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 0), reused 14 (delta 0)
Receiving objects: 100% (14/14), done.
Checking connectivity... done.

~/Src/Code
❯ cd meteor-issue-3670/packages/6to5

meteor-issue-3670/packages/6to5 git/master
❯ meteor add issues:6to5
 => Errors while adding packages:

While loading plugin `6to5` from package `issues:6to5`:
packages/6to5_plugin.js:7:10: Unexpected token ILLEGAL

**Comment by fourq** [comment]
The issue title states that the a package cannot be named with a leading digit, but rather it's the build plugin name that fails with one.

**Comment by glasser** [comment]
agreed, but I think the same issue happens if your package name starts with a digit.

**Comment by dferber90** [comment]
Whoops, branch of first commit was not based on `devel`. Second commit is in a branch with the same name, based on `devel`. Sending PR now.

**Comment by ekatek** [comment]
Merged https://github.com/meteor/meteor/pull/4313, which maybe fixes this.

**Comment by laosb** [comment]
Closing.
