### ISSUE TITLE
Mobile app auto-update with --mobile-server

### ISSUE THREAD

**Issue by barbatus** [meteor/meteor#3672]
It might be not a bug but I didn't find any related information on the web, so posting here.

Whenever I add  "--meteor-server=localhost:3000" to "meteor run ios --port=3100" command, iOS app stops to auto-update after any change made to the code.
I created two simplest Meteor apps, server and mobile, to check it. Same thing - "meteor run ios --port=3100" works fine, when "meteor run ios --port=3100 --meteor-server=localhost:3000" - no updates.
It needs to restart mobile app and reset simulator in order to see up-to-date changes. 

What it could be? Do I miss something or is it a bug?

Thanks

**Comment by Slava** [comment]
@barbatus Hi Alex,

This is the intended behavior, but the design of this feature (hot code push) might be flawed. The design assumes that the server serving the code (for updates) is the same server for getting the data and executing the methods.

The more general issue (get code from one server, but data from another) is discussed a lot in this issue: #3852.

The general way to go about it is to keep the default server connection (the one that serves the mobile version of your site) and get all the code updates from it. And for data and methods use a different DDP connection that you can establish by calling [`DDP.connect`](docs.meteor.com/#/full/ddp_connect), you can later call Meteor methods on the connection object and pass it to the collections.
