### ISSUE TITLE
Method namespacing

### ISSUE THREAD

**Issue by meepeek** [meteor/meteor#3675]
After stumble with meteor for a while, I find myself repeating the task of reconstructing my api object before putting to Meteor.methods for I could not call the sub-method I send in the function, for example:

```
Meteor.methods({
    a: { b: function() { /*do something*/ }}
});
```

It would be really nice if Meteor automatically parse the object and reconstruct them as API function call on the client side on my stead.

So I would like to propose an idea to simplify how to use Meteor.methods Please consider the following code or you might want to clone the following repo for the demonstration (I have yet done the object reconstruction wrapper on the client side though):
https://github.com/meepeek/meteor-issue-3675-Meteor.methods-wrapup-idea

```
if (Meteor.isServer) {
    // Create API object
    var send = function (s) {
        return 'You\'ve called \'' + s + '\' method which trigger an excution at the server';
    };

    var api = {
        someObject: {
            c: function () {
                return send('c');
            },
            d: function () {
                return send('d');
            }
        },
        a: function () {
            return send('a');
        },
        b: function () {
            return send('b');
        }
    };

    var wrapApi = wrapUp(api, 'api');
    // Wrap the APIs
    function wrapUp(o, s) {
        var wrap = {};
        s = s + '.';
        _.each(o, function (v, i) {
            if (typeof v === 'object') {
                _.each(wrapUp(v, i), function (v2, i2) {
                    wrap[s + i2] = v2;
                });
            } else {
                wrap[s + i] = v;
            }
        });
        return wrap;
    }

    wrapApi.apiList = function () {
        return _.keys(wrapApi);
    };

    Meteor.methods(wrapApi);
}

if (Meteor.isClient) {
    Meteor.call('apiList', null, function (e, r) {
        console.log('You may call these methods with Meteor.call\n', r.join('\n'));
    });
}
```

**Comment by stubailo** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

It looks like what you are looking for is a way to define namespaced/nested methods?

Or is the question just that you like declaring methods inside a nested JavaScript object rather than with String names?

**Comment by meepeek** [comment]
Hi @stubailo,

Thanks for your respond.

My goal is to make a specific server api object virtually expose to the client. e.g. I create an api object at the server side:
```
// Server Side
api = {
    b:  { c: [function] },
    d: [function]
}
```
Then push them in Meteor.methods:
```
// Server Side
Meteor.methods(api)
```
With some workaround, the client side would be able to directly call something like this out of the box:
```
// Client Side
api.b.c(param, callback);

// Instead of calling Meteor.call('api.b.c', param, callback), which require to make the api flat to match Meteor.methods dictionary limitation
```
Given the current Meteor.call behaviour as a function dictionary, I will need to achieve things:
1. Automatically flatten multi-level object so Meteor.call may access the sub-object's method
2. Send the server api structures to the client, reconstruct the object at the client side and wrap all Method.call requires for all the methods sub-methods available.

The code in my comment above was my attempt to decompose the server object, making them flat so they could be called from the client after assign to Meteor.methods as a dictionary. Which makes the first goal done.

PS. When I look into Meteor.default_server.method_handlers, I think the autopublish plugin also doing something similar, there were so many flatten-like methods.

**Comment by meepeek** [comment]
Hi, I updated the repository.
- I implemented the api reconstruction at the client side so the client may access Meteor.api to call the methods.
- I have just noticed that .meteor has not included in github so I added usage section.

Let me hear what you think. I hope it would be useful.

**Comment by stubailo** [comment]
You should add the `.meteor` folder to github. It has its own .gitignore file inside that will put the right things online and keep the other things local only.

**Comment by stubailo** [comment]
I think it's pretty unlikely that we'll make such a big API change for methods soon, but it looks like you know how to implement what you want and the current API is sufficient as a base for your work.

Why not make a package with this functionality and publish it to Atmosphere? I think a lot of people will appreciate it.

**Comment by dandv** [comment]
I've started a MeteorCommunity discussion (and SO question) that might be of interest: [how to namespace Meteor methods in packages](https://github.com/MeteorCommunity/discussions/issues/48). See also #540.

**Comment by hwillson** [comment]
Now that Meteor has ES2015 module support, the need for Method namespacing has been greatly reduced. Leveraging imports/exports and packages like the Meteor Guide's recommended [mdg:validated-method](https://atmospherejs.com/mdg/validated-method) package, helps greatly reduce name collisions and keeps  your code nice and organized. Given this, the fact that you were able to extend the existing API to do what you wanted it to do, and the age of this issue, I'll close this off. Thanks!
