### ISSUE TITLE
Comments inside a head tag are not removed

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3677]
```
<head>
  {{! This should be removed }}
</head>
```

In the output static HTML file from Meteor, this tag is still present. But it should be removed.

**Comment by stubailo** [comment]
Currently, the `<head>` of the page is not compiled as spacebars code at all, but it would make a lot of sense if it were.

**Comment by hwillson** [comment]
Moved over to meteor/blaze#220 - closing here. Thanks!
