### ISSUE TITLE
allow `bare` javascript files on the server

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3681]
I know there was a lot of discussion about this already done, but I find this really the worst part of Meteor. Having to modify upstream code so that one can use a global symbol defined in a library is really painful. Meteor tries to be smart and differs between, at the top level:

```
var FileScope = {};
```

And:

```
PackageScope = {};
```

The first becomes file scoped, while the second package scoped (and potentially exported). I think this is an interesting approach, but it fails for 3rd party libraries, because for them both syntaxes are the same and when they are defining global (browser) scope, they almost always use the first scope. I am suggesting a simple extension to current packaging:

```
api.addFiles([
  'dist/library.js'
], 'client', {packageScope: ['FileScope']});
```

This would make variable `FileScope` behave like package scope, no matter if it was defined `var FileScope`. This would address 99% of issues I had encountered while trying to package 3rd party libraries.

**Comment by mitar** [comment]
(The other common use case is for libraries expecting `exports`, but let's leave this to some other time.)

**Comment by gadicc** [comment]
I've also been thinking about "wrapping options" to be specified in `package.js`.  My idea was a bit different but I think would also be really helpful for wrapping 3rd party packages.  What if we just had:

```
api.addFiles([
  'dist/library.js'
], 'client', { wrapper: 'AMD' });
```

etc.  The idea is actually that these "wrapper modules" could potentially be 3rd party Atmosphere packages, supporting different methods.  Generally it's just a matter of setting up the appropriate methods and objects (say `require`, `define`, `modules`, `exports`) beforehand in the right scope, and then processing/exporting afterwards.  If no wrapper is specified, the default Meteor policy is used, and either way, extra options could be specified (like the PackageScope stuff you suggest), i.e. the two ideas are not mutually exclusive but rather complementary.

This is also very relevant for ES6 / Harmony code, which currently is a total pain to get into Meteor.

**Comment by mitar** [comment]
Good ideas.

**Comment by glasser** [comment]
Apparently it's not documented (I thought it was at some point) but isn't this what the `{ bare: true }` option to `api.addFiles` does?  (And the `client/compatibility` directory in an app, which is documented.)

**Comment by glasser** [comment]
(Focusing on the original issue and not the followup comments here.)

**Comment by mitar** [comment]
But I would like to package things correctly. Yes, we can be putting everything with `bare`, but that then pollutes the global namespace. NPM and all other package systems already do that. Meteor should provide a way to piggy-back on top of them. And my proposal or @gadicc's proposal are trying to address that.

**Comment by glasser** [comment]
Oh, I see. You want to be able to do this at the per-symbol level?

It does seem a little surprising to me to assert that library authors who write `var FileScope = {}` intending that variable to be useful outside of the file will write other vars in the same file that they don't intend to be exported, though.  Do you have examples?

BTW, what bare does is "don't wrap this file in a closure". In the app, that means that top level vars end up as globals, but in packages it just means they end up as package variables --- it doesn't affect the *package-level* closure.  (Apps don't have a package-level closure, mostly to make use of the JS console easier.)

Right now most of what linker does is add code to existing scripts. This would also require finding and deleting the `var `.  Not impossible (we do it with coffeescript a bit) but definitely a little different.

**Comment by mitar** [comment]
I am saying that library authors writing `var FileScope` at the top level of the file expect it to be a global variable. To my knowledge, writing `var FileScope` and `FileScope` is exactly the same in JavaScript in browsers at the top level of a file? So there is nothing strange for them to do that, expecting that it will be included in a normal JavaScript environment, thus becoming global. Of course for Meteor we do not want things to be global, so we have to find a way to make extract them out.

Here [is example](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js). In normal use, `Handsontable` is a globally available symbol. If I would add it with `bare`, it would be available. But I do not want to use `bare`. That defeats the whole purpose of Meteor packaging and namespacing system.

> BTW, what bare does is "don't wrap this file in a closure". In the app, that means that top level vars end up as globals, but in packages it just means they end up as package variables --- it doesn't affect the package-level closure. 

Oh. This is a little known fact. Interesting. So I just user `bare` and then export the symbol and I am all set? It will not leak out to the global scope automatically?

> Right now most of what linker does is add code to existing scripts. This would also require finding and deleting the var. Not impossible (we do it with coffeescript a bit) but definitely a little different.

Aha. I thought you are already doing this for JavaScript as well.

**Comment by glasser** [comment]
OK, does this additional fact about `bare` satisfy your original needs here?  (Though `bare` should be documented.)

**Comment by onip** [comment]
just confirming thata `api.addFiles ('foo.js', 'client', {bare: true});` makes foo.js global variables ( `var Foo = ...` ) available at package-level closure so that they could be then exported via `api.export ('Foo', 'client');`. Other library variables won't pollute app global environment, unless exported of course.

This feature should definetely be documented on docs.meteor.com

**Comment by mitar** [comment]
I can confirm it woks.

**Comment by mitar** [comment]
I am reopening this because it `bare` does not work on the server side. How can I make a library which was made for a client with `var FileScope` symbol defined to work on the server? There is no strange things, it simply declares the symbol, no `window` stuff and other stuff.

**Comment by mitar** [comment]
It is exactly the same problem. Because it uses `var FileScope` the symbol is not available. If I modify it to `PackageScope`, it works.

**Comment by avital** [comment]
(Not necessarily to disagree, but this is the same problem that Node code
has in general -- if you copy a client library that uses top-level vars
expecting them to be globals into a node file and `require` it it won't
work)

**Comment by mitar** [comment]
Yes, but in Node I have then some toolchains I can use to make it work. :-) Is there a known workaround which does not require changing upstream code?

**Comment by glasser** [comment]
What do you mean by "`bare` does not work on the server side"?

**Comment by mitar** [comment]
You cannot use it. It throws an error saying that bare is available only on the client side.

**Comment by mitar** [comment]
So `api.addFiles ('foo.js', 'server', {bare: true});` throws an error.

**Comment by glasser** [comment]
Hmm, I forgot that.  You're right.  Looks like that goes back to the very first implementation of bare (in its initial name of `compatibility`): https://github.com/meteor/meteor/commit/fb61e884dbf4fa3edde6895385fac58339bf78b8#diff-2588798e782de3a0b93513cc522d73faR357

But that was back before linker.  I don't see any reason you shouldn't be able to bare-ify a server file as long as the whole package still gets closured.  I think we basically had this restriction because we didn't think there was a use case for it.  I think the argument basically was that it was common to find client code written assuming `var X = ` would be global, but rare for server code (as @avital said).

If our assumptions were wrong and there is a use case, I think the restriction could just be dropped...

**Comment by mitar** [comment]
Yes, please. This would really help packaging some libraries without having to modify them. The main use case is to package code made for client side to work also on the server side. As you are saying, client side code often has `var X =`. But if you want to use it on the server, then `bare` is useful.

**Comment by avital** [comment]
I'm curious @mitar -- what do people in vanilla Node do in this case? I think those libraries wouldn't be made to work in that case? Or do those libraries maybe check explicitly to see if `require` is defined and work a different way?

**Comment by mitar** [comment]
Yes, this is really to wrap some libraries targeting browsers. Not sure what they do, probably use grunt to modify the script during the build process.

**Comment by glasser** [comment]
OK, that's convincing, and it's an easy enough change. Thanks!

**Comment by mitar** [comment]
Great!

**Comment by trusktr** [comment]
I landed here due to the `'bare' option may only be used for web targets` error.

Besides this issue, I'm almost done making the first usable version of [`rocket:module`](https://atmospherejs.com/rocket/module), which aims to provide one solution to this problem of using 3rd party libraries in Meteor, plus it adds suport for CJS/AMD/ES6 modules (via Webpack) so you can use normal `require`/`module.exports`/`define`/`import`/`export` in your files. Basic info is [available here](https://forums.meteor.com/t/4620), and I'l update the README with uage instructions and documentation for the first release (1.0.0) very very soon. (don't use the current release of rocket:module, it won't do anything, I was testing Atmosphere publishing.)
