### ISSUE TITLE
Static resources in the packages are NOT shown

### ISSUE THREAD

**Issue by miraten** [meteor/meteor#3683]
Image files or fonts files in my packages can not be shown.

I created a package with the name 'leesangwon:bootstrap-less'.
There are some font files in the package.
The font files can not be read.

When I renamed the package name from 'leesangwon:bootstrap-less' to 'bootstrap-less',
they are shown well.

So I thought that the problem is caused by the colon character ':'.

How can I work around it?

**Comment by stubailo** [comment]
I don't understand what the issue is. Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.

**Comment by miraten** [comment]
I'm sorry.

check [this github url](https://github.com/miraten/meteor-package-bug).

**Comment by glasser** [comment]
Duplicate of #3684.
