### ISSUE TITLE
Static resources in the packages are NOT shown

### ISSUE THREAD

**Issue by miraten** [meteor/meteor#3684]
Image files or fonts files in my packages can not be shown.

I created a package with the name 'leesangwon:colon'.
There are some image files in the package.
The image files can not be shown.

When I renamed the package name from 'leesangwon:colon' to 'colon',
they are shown well.

So I thought that the problem is caused by the colon character ':'.

How can I work around it?

example source:
[https://github.com/miraten/meteor-package-bug](https://github.com/miraten/meteor-package-bug)

**Comment by glasser** [comment]
The colon is normalized to an `_`.  http://localhost:3000/packages/leesangwon_colon/meteor-cover.jpeg works (thanks for the easy reproduction).

We should have an API for getting this path.  This feature request is being tracked in #1193
