### ISSUE TITLE
Observable Streams for Blaze UI

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3687]
Observable streams would be a really cool feature for Blaze. [Here's a cool talk about them](https://www.youtube.com/watch?v=XRYN2xt11Ek).

I believe observable streams and Tracker are **very** similar already, but I think the observable streams syntax has advantages in some circumstances.

### Observable streams are functional and less stateful.
    
A common pattern in meteor is to define a reactive variable in `Template.created`, define a helper that depends on that variable in `Template.helpers`, and define an event to modify that variable in `Template.events`. This totally makes sense for certain components that are stateful, but sometimes this pattern can clog your app with an unnecessary about of state. A perfect example of this from the video is making an object draggable. 

        mousedown('.image')
          .map((down) -> mousemove.takeUntil(t.mouseUp))
          .concatAll()
          .forEach((pos) -> @elem.position = pos)

This pattern hides all the UI states so that the state you see defined in `Template.created` only handles the truly stateful parts of your component. I can tell you first hand that this would be immensely helpful. [Check out this absolutely unmaintainable mess I had to deal with](https://github.com/ccorcos/meteor-swipe/blob/master/swipe/swipe.coffee#L332).

Another good example is the typeahead. Whereas the draggable example may be defined in `Template.rendered`, this example can be defined in a `Template.helper`.
        
        keyPresses.throttle(250)
          .map((key) -> Items.find({name:t.find('input').value}))
          .concatAll()

This allows us to hide the throttling and the current text from polluting our template state. Instead we have a very declarative, functional programming solution. We can look at the helper and see exactly what's going on without having to trace the reactive variable throughout the app.

P.S. I'm hoping write a demo in the near future

**Comment by mquandalle** [comment]
I'm quite new to this concept of using a streaming API to handle events, but that makes some sense to me. Is there any difference between what you have in mind a something like https://github.com/baconjs/bacon.js?

**Comment by ccorcos** [comment]
Basically the same thing. I figured it would be useful to implement this using Tracker though. This way we can leverage all of Meteor's reactivity.

**Comment by Slava** [comment]
@ccorcos if you read the [README of Tracker](https://atmospherejs.com/meteor/tracker) you will find out that one of initial design goals of Tracker was to avoid FRP and its graph management preserving most of the useful functionality.

That being said, I agree that it would be nice to be able to add custom event types available from the event map.

**Comment by ccorcos** [comment]
Is it at all possible to register template events after a template is rendered?

**Comment by rclai** [comment]
I think [this guy's package](https://atmospherejs.com/chriswessels/hammer) did it. He used Eric's [template-extension package](https://atmospherejs.com/aldeed/template-extension) to do it [here](https://github.com/chriswessels/meteor-hammer/blob/master/template_integration.js#L41).

**Comment by ccorcos** [comment]
Whoa. template-extensions are great!

**Comment by ccorcos** [comment]
Alright people. Here it is!

https://github.com/ccorcos/meteor-tracker-streams
