### ISSUE TITLE
Clean-room "You've pressed the button" doesn't work on android/ios, but works on web?

### ISSUE THREAD

**Issue by salamanders** [meteor/meteor#3688]
I've done a fresh install of meteor, and while the "number of times clicked" works fine in a browser, it doesn't register clicks in either android or ios emulators.

I have a new install of my machine, which means all new SDKs and IDEs.
OSX 10.10.2, Xcode 6.1.1, etc.

```
meteor create oneshot
cd oneshot
mkdir server
mkdir private 
mkdir lib
mkdir client && mkdir client/lib && mkdir client/stylesheets && mkdir client/templates
touch mobile-config.js
touch README.md
meteor install-sdk android
meteor add-platform android 
```

This works:  meteor run
This does not: meteor run android    
Didn't see anything suspicious in the console log.

**Comment by adamgins** [comment]
@salamanders wondering how you solved this. I am not getting clicks on Android Device, but they work in Browser and iOS and Android Emulator

**Comment by salamanders** [comment]
I never did - and it looks like ecwyne:polymer-elements is still using pre-1.0 polymer, so I haven't tried it lately.

**Comment by martijnwalraven** [comment]
Clicks not working is usually a sign there has been a JavaScript error. Have you tried using Chrome remote debugging to see what could be going on?
