### ISSUE TITLE
Linux build box GCC version (question).

### ISSUE THREAD

**Issue by fourseven** [meteor/meteor#3689]
Are there plans to update the GCC version on the (linux) package build boxes? 

I've got a wrapper for node-sass (`fourseven:scss`), and I've stopped using them because node-sass requires a newer version of GCC than what's provided on the build boxes (which is 4.4), and using the boxes has provided all sorts of issues because of this https://github.com/fourseven/meteor-scss/issues/60 . 

This was made worse by - https://github.com/meteor/meteor/issues/2459 (not being able to yank packages).

**Comment by glasser** [comment]
There are no plans to update the boxes right now.  There's a tension between building with old versions of libc (which allows binaries to run on older distributions) vs having the newest build tool features.  We need to think about this further.  Do you understand what GCC features node-sass needs?  Is this pretty specific to node-sass or are lots of package authors seeing this?

**Comment by fourseven** [comment]
That's reasonable. 

I'm only asking in regard to node-sass, I have no idea about the wider community. FWIW, libsass/node-sass requires GCC 4.6+ or Clang/LLVM. 

Happy for you to close this now, as I have an official word on the matter, and will do what I can to work with it.

**Comment by chrisbutler** [comment]
@glasser @fourseven i came across the same issue and can't build `node-sass ` on the osx boxes either (https://github.com/sass/node-sass/issues/1009#issuecomment-114036996)

it's an issue for any package depending on `node-sass` https://github.com/lookback/meteor-emails/issues/23

**Comment by saper** [comment]
https://github.com/sass/libsass needs advanced C++11 language features (including variadic templates), so a modern C++11 compiler is required. If GCC upgrade is not possible/difficult, it can be compiled using clang, but care must be taken to use appropriate C++ runtime library.

**Comment by fourseven** [comment]
I have this as well now, it should probably be a separate issue, since it's with the OS X build boxes - they can't build libsass as is, so I'm building the OS X package via my own machine, and that's stopping older Mac OS X compatibility.

**Comment by fourseven** [comment]
node-sass has gotten more stable, so it builds on all boxes now. Closing!
