### ISSUE TITLE
Meteor installed to my ~/.meteor folder, is that right?

### ISSUE THREAD

**Issue by Jakobud** [meteor/meteor#3693]
Just trying out meteor tonight. I used `curl https://install.meteor.com/ | sh` and it installed (on my CentOS 6.x machine) to ~/.meteor. Is that where it was supposed to be installed? Because that folder isn't in my path and therefore `meteor` is not a global command. I have to do `# ~/.meteor/meteor create simple-todos`. 

Am I doing something wrong here or what? The doc's make it sound like the installation to should it a global command but it obviously didn't. And I did all this as root.

**Comment by glasser** [comment]
Did you read what it did at the end of the install script? It should also install a small shell script in `/usr/bin/meteor`, or if it fails to, it should tell you what to do to get it to work.

You can rerun the `curl|sh` if you'd like to try again.

**Comment by Jakobud** [comment]
Okay I'll look at it again, I must have missed this.
