### ISSUE TITLE
observe/observeChanges without initial set of documents

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3694]
Currently observe/observeChanges always go through all documents first, before continuing observing. This is problematic on huge collections. Imagine that you do `.find({}).observe` on a collection with millions of documents. Sometimes you do not need all those documents, you would just want to process changes from that point on.

This can be also used to help improving counting performance, that instead of going through all documents initially, one could first to a simple `.count()` and then just keep the count up to date by observing changes and adjusting the count.

It would be also useful for [PeerDB](https://github.com/peerlibrary/meteor-peerdb) where we are observing the database for changes for reactive relations between documents.

There were quite some discussion about this in various corners of Meteorlandia but I am not able to find them at the moment. One was about effective counting of documents.

**Comment by glasser** [comment]
As I said on #3695 (but you're right that these are different suggestions):

Thanks for the feature request! You might be interested in reading our feature request guidelines.

I agree that we'll need multiple strategies eventually for dealing with multiple kinds of queries. It is certainly the case that having the full cache helps with performance when the cache is small enough.

**Comment by mitar** [comment]
The main thing is that this should be two different things. One is cache which could be kept populated at every hit. Another is if we want to prepopulated whole cache when the query is opened initially.

I would go even so far that I would maybe have observeChanges version which just tells you the `_id` of the document which changed, but everything else you have to figure yourself (but you can still select which fields you are interested in observing using `fields`, just they are not used at all, they are just used to filter oplog changes out).

**Comment by maxnowack** [comment]
Any updates on this?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=observe%2FobserveChanges%20without%20initial%20set%20of%20documents&body=Migrated%20from:%20meteor/meteor%233694) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
