### ISSUE TITLE
observe/observeChanges without caching documents

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3695]
observe/observeChanges is a very powerful API abstraction and we love it. But one issue is how it scales to queries containing thousands of documents. As it is currently implemented (to my knowledge), it caches all the documents in the query resultset in the server side of the Meteor app, and then patches it up based on changes from the oplog.

I think that a way to limit the size of that cache is needed. By limiting (or even setting it to zero) Meteor would not cache all documents, but would after a change is detected, go and fetch a document from the database, and then provide it through the observe/observeChanges API. This means that there would be some additional latency and queries, but it would be much better for server side memory use.

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I agree that we'll need multiple strategies eventually for dealing with multiple kinds of queries.  It is certainly the case that having the full cache helps with performance when the cache is small enough.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=observe%2FobserveChanges%20without%20caching%20documents&body=Migrated%20from:%20meteor/meteor%233695) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
