### ISSUE TITLE
Change Meteor.publish to receive an object

### ISSUE THREAD

**Issue by PeppeL-G** [meteor/meteor#3696]
In Meteor, many (all?) functions similar to `Meteor.publish`, for example `Template.myTemplate.helpers`, `Template.myTemplate.events` and `Meteor.methods` receives an object with key/value pairs, but `Meteor.publish` receives a single key/value pair via two different parameters. I propose to change this so the public API overall is more consistent.

(yes, I just accidentally passed an object to `Meteor.publish` and got really sad when my code didn't work :()

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This seems like an improvement (as long as the old way still works).  A pull request (including docs improvements) could be considered.

**Comment by PeppeL-G** [comment]
I can give it a shoot.

Should the changes take place on [the Server object](https://github.com/meteor/meteor/blob/devel/packages/ddp/server_convenience.js#L27) or [the Meteor object](https://github.com/meteor/meteor/blob/devel/packages/ddp/livedata_server.js#L1375)?

Should `Meteor.publish(name, handler)` be deprecated (so no need to comment about it except for leaving a note about the backward compatibility code) in favor of `Meteor.publish(publications)`, or should they both be public ways to call the function (if so, how should the docs be written?)?

**Comment by glasser** [comment]
I'd say:

- The server object, which will make it automatically true for the Meteor object too (your links are backwards though)

- Let's just document them both for now and maybe decide to deprecate the first later.

- Hmm, maybe you have to still write `Meteor.publish(null, handler)` for universal publications (which frankly have lots of problems and might get removed from Meteor at some point; eg, you can't tell when they are ready!)

**Comment by PeppeL-G** [comment]
My first pull request ever (I'm not a git expert (yet!)) and the first time I'm diving into the core, but what about that?

By the way, I wrote `Meteor.publish({null: function(){ ... }})` could be used for the null publish, but it turned out that `null` turns into `"null"` when it's used as a key in an object, so I was wrong.

**Comment by PeppeL-G** [comment]
I've reconsider my proposal. In my projects, I usually add one publication/method per file (a common structure among folks?), so a better solution (for me) would be to change `Meteor.methods` to receive a name and a function, instead of an object with names and functions. But I'm happy as long as `Meteor.methods` and `Meteor.publish` are called in the same way.

**Comment by glasser** [comment]
Interesting.  I mean, I thought your analogy with `helpers` was good though.

**Comment by stubailo** [comment]
Hey, I think we should do the opposite of this - make `Meteor.methods` _not_ take an object, so that each method can take options. We're working on this for the Meteor guide here: https://github.com/meteor/guide/issues/54

Going to close this issue, since it's not something we should do.
