### ISSUE TITLE
New server side Accounts hooks : onBeforeLogin / onBeforeCreateUser

### ISSUE THREAD

**Issue by Tolmark12** [meteor/meteor#3710]
We like to use one additional layer of password security on account creation and login. When a user is created, we concatenate a server variable hash to their password like so : 

```coffeescript 
passwordToStore = SHA256(process.env.PASSWORD_SHA256_HASH + passwordString)
```

Would be very cool if there were two additional hooks that let the app transform the submitted data before it was stored in the database or submitted to the login function:

```coffeescript
if Meteor.isServer

  Accounts.onBeforeCreateUser (fields)->
    fields.password = SHA256(process.env.PASSWORD_SHA256_HASH + fields.password)
    return fields

  Accounts.onBeforeLogin (fields)->
    fields.password = SHA256(process.env.PASSWORD_SHA256_HASH + fields.password)
    return fields
```

**Comment by glasser** [comment]
I'm not sure why this would be helpful for your app.  Is this a standard generally considered secure approach to password storage?  We already pass the password (or password hash) received from the client through bcrypt, which does salting, etc.  Also, it's unclear how you would change that hash if it gets stolen.

(There is an onCreateUser hook already, though I don't know if it's helpful for your purposes.)
