### ISSUE TITLE
"deviceready has not fired" on Android Device

### ISSUE THREAD

**Issue by abhishekbatra** [meteor/meteor#3711]
Hi,
I saw #2583 and #2655 had this issue for earlier releases but I'm on Meteor 1.0.3.1 and see the following logs when running on an Android device: 

> I20150212-23:17:47.628(5.5) (android:http://meteor.local/cordova.js:1154) deviceready has not fired after 5 seconds.
> I20150212-23:17:47.631(5.5) (android:http://meteor.local/cordova.js:1147) Channel not fired: onPluginsReady
> I20150212-23:17:47.828(5.5) (android:http://meteor.local/cordova.js:1147) Channel not fired: onCordovaReady
> I20150212-23:17:47.829(5.5) (android:http://meteor.local/cordova.js:1147) Channel not fired: onDOMContentLoaded

The app does launch, but I'm unable to initialize Angular.

Also useful to mention: The device is a Samsung GT S7392 running Android 4.1.2

**Comment by Slava** [comment]
@abhishekbatra as far as I understand this is a warning that gets printed if the app was too slow to start. In my experience, this happens all the time with the Cordova apps and this is not a real error message (can be ignored given that it happens all the time).
