### ISSUE TITLE
Meteor upsert behavior is not consistent with MongoDB's upsert

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#3717]
I'm not sure you guys are aware of this but In MongoDB, if you do an upsert like this:

```
db.myCollection.update({
   prop1: 'blah'
}, {
   $set: {
       prop2: 'whee'
   }
}, { upsert:true })
```
On insert, the resulting document is supposed to include `prop1` in the document (yes, the criteria fields) like this:

```
{
   _id: ObjectId('alkwjefawef''),
   prop1: 'blah',
   prop2: 'whee'
}
```

[Proof](http://docs.mongodb.org/manual/reference/method/db.collection.update/#upsert-behavior).

Meteor's upsert during the insert scenario, does not include the `prop1` field (or any criteria fields):

```
MyCollection.upsert({ prop1: 'blah' }, { $set: { prop2: 'whee' } });

{
   _id: 'alkwjefawef',
   prop2: 'whee'
}
```

**Comment by glasser** [comment]
This (which is to say, your code above plus a bunch of support code I had to write) works for me, both  on 1.0.3.1 and on devel (where I recently made some upsert-related improvements).

If you're still seeing the issue, please provide a full reproduction following the guidelines at https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by rclai** [comment]
That's odd, it does work. I don't know why I saw this but if it happens I'll make sure to reproduce it.
