### ISSUE TITLE
Support HTTP Basic Authentication for a Mobile Server

### ISSUE THREAD

**Issue by alpjor** [meteor/meteor#3718]
https://groups.google.com/forum/#!topic/meteor-talk/9caIugBC8U4

There is a use case of supporting HTTP basic auth on the --server option for meteor build. This use case is for supporting an application in development mode where the in-development assets should be protected from outside access.

**Comment by Slava** [comment]
Hi @alpjor,

this is a valid feature request and a valid use-case. Unfortunately, we have so much engineering bandwidth and we cannot build every feature. Let's keep this issue open and see if anyone else is in urge of it.

**Comment by alpjor** [comment]
If someone could give me a quick point in the right direction. I might be able to make a pull request to address this. I just don't even know where to start in the meteor code.

**Comment by Slava** [comment]
https://github.com/meteor/com.meteor.cordova-update - this is the repo with the native code that runs the app files. The new files are downloaded in this package: https://github.com/meteor/meteor/blob/63df4b1ce5382ce70f63b76a66a1fdab3e6bfb4a/packages/autoupdate/autoupdate_cordova.js#L82

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20HTTP%20Basic%20Authentication%20for%20a%20Mobile%20Server&body=Migrated%20from:%20meteor/meteor%233718) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
