### ISSUE TITLE
Cordova update?

### ISSUE THREAD

**Issue by jhmacdon** [meteor/meteor#3719]
I am getting errors whenever I try running for android. It will say something like "Fetching plugin "org.apache.cordova.splashscreen@1.0.0" via plugin registry". 

I check the version for the package, and it's always outdated (seems to have been updated 5 hours ago?) then I update manually with "meteor add cordova:org.apache.cordova.splashscreen@1.0.0" and this would work and then another would come up. It kept working until splashscreen, and now the newest version doesnt seem to work. And idea what to do?

**Comment by thetwosents** [comment]
Bump. I have one meteor app that currently can run iOS or ios-device and all others are broken :(

**Comment by harfangeek** [comment]
I'm have the same problem. The error says that splashscreen@1.0.0 need Cordova >= 3.6.0.

**Comment by lorensr** [comment]
#3726 Is this your problem?

**Comment by Slava** [comment]
As @lorensr correctly pointed out, we are tracking this at #3726. In short: Cordova plugins registry is having an outrage, all older versions of every plugin seems to be purged.

**Comment by lorensr** [comment]
hopefully that outrage was [sic], because it's an outrageous outage :D
