### ISSUE TITLE
Cordova integration bug: assuming inside full browser

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3722]
Getting these errors when using Safari remote debugger on ios-device:

![image](https://cloud.githubusercontent.com/assets/251288/6197784/029aa9e2-b3a1-11e4-98a0-056606be23c0.png)

First three are core, using `userAgent`:
```
[Error] Deprecated attempt to access property 'userAgent' on a non-Navigator object.
	(anonymous function) (logging.js, line 345)
	global code (logging.js, line 354)
```
![image](https://cloud.githubusercontent.com/assets/251288/6197800/42ddc5ca-b3a1-11e4-8cc4-760816b1005e.png)

**Comment by Slava** [comment]
There are not errors, but rather deprecation warnings. They don't stop the page from working properly.

That being said, I would love to see us getting rid of these warnings.

**Comment by lorensr** [comment]
They do not currently affect functionality. Safari reports them as errors:

![image](https://cloud.githubusercontent.com/assets/251288/6198002/2a80c000-b3a5-11e4-8a22-4d22bbfe0cff.png)

**Comment by jamgold** [comment]
I am seeing the same, and also upon code reload I see
```
Can't find variable: cordova
```
as the very first error and the Cordova app is not reloading the modified code.

**Comment by ddresch** [comment]
Got the same error logs in Safari Debug console like @lorensr posted.

http://stackoverflow.com/questions/26654877/cordova-deprecated-attempt-to-access-property-useragent-on-a-non-navigator-o

As mentioned in the above answer it's a cordova.js issue which is solved, correct me if I'm wrong. Got code running in iOS 7 and errors like this in simulator running iOS 8.

**Comment by thetwosents** [comment]
I see that its not necessarily an error, but I am having trouble with tap events in the simulator. So weird.
