### ISSUE TITLE
reserved words (viewName) in templates?

### ISSUE THREAD

**Issue by appshore** [meteor/meteor#3723]
https://github.com/appshore/meteor-reserved-words-template

Got this error : 
(blaze.js:71) Warning: Assigning helper with `Template.test.viewName = ...` is deprecated.  Use `Template.test.helpers(...)` instead.

When using {{viewName}} in a template, {{this.viewName}} works

JS:

```
if (Meteor.isClient) {
  Template.test.helpers({
    reserved: function () {
      return {
          viewName: 'test'
      };
    }
  });
}
```

HTML:

```
<head>
  <title>reserved</title>
</head>
<body>
  {{> test}}
</body>
<template name="test">
    {{#with reserved}}
        <p>Show {{this.viewName}}</p>
        <p>Show {{viewName}}</p>
    {{/with}}
</template>
```

Output:

```
Show test
Show Template.test
```

**Comment by dgreensp** [comment]
We should document better what names are reserved, and either make this a better warning or error, or make it just work.

See also #3156 for another example of the same thing.

**Comment by hwillson** [comment]
Hi @mitar - do you see any value in keeping this issue and issue #3156 open? If so I'll move them over to the Blaze repo. I just thought I'd check with you first as I haven't seen or heard of many issues being caused by reserved word naming, with modern day Blaze. Let me know - thanks!

**Comment by mitar** [comment]
I think opening one ticket on Blaze to document reserved words (or mentioning that one should not use same words as existing methods) could be opened. I wonder though if this is will be a problem at all once we move to class-based templates. Because it is probably clear that you should not override other methods with your methods.

**Comment by hwillson** [comment]
meteor/blaze#156 has been created to track this. This issue can be closed. Thanks!
