### ISSUE TITLE
accounts-facebook user created with no email

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3724]
It is possible for the user to deselect email permissions in the Facebook auth dialog, in which case an account is created with an empty `emails` array. Might be useful to add a note to the `accounts-facebook` package `readme` saying that you should check the `emails` array on account creation, and if it's empty, prompt for one.

**Comment by glasser** [comment]
I think this is a subset of a bigger issue, where we don't actually document anywhere that `emails` can get filled in by OAuth providers at all.  That seems like a good possible doc PR.
