### ISSUE TITLE
Meteor.user() only returns _id and username

### ISSUE THREAD

**Issue by JackWReid** [meteor/meteor#3725]
After creating a users with the accounts-password and accounts-ui modules, when I call `Meteor.user()` in the console I don't get the full profile, only the `_id` and `username`, even though there is more on the document, like the `createdAt` record.

The same issue crops up if I use these templates:

```html
<template name="user_list">
	<div class="user-list">
	<h1>Users</h1>
		<ul>
		{{#each allUsers}}
			{{> user_item}}
		{{/each}}
		</ul>
	</div>
</template>
```

```html
<template name="user_item">
	<li class="user-item">
		<p><b>{{username}}</b></p>
		<p>Created: {{createdAt}}</p>
	</li>
</template>
```

... backed by this helper:

```js
Template.user_list.helpers({
  allUsers: function () {
    return Meteor.users.find({});
  }
});
```

In this case the user_list template iterates through users just fine, and shows the username, but the `createdAt` helper fails, even though if I go through `meteor mongo` the record is definitely there. I haven't removed autopublish; my setup is still fully open. Why can't I access the rest of the user records?

**Comment by PeppeL-G** [comment]
Even if `autopublish` is added, the entire user documents won't be send to the clients. See [the code here](https://github.com/meteor/meteor/blob/58869b050bf5cdc77991505b10c46112d85aff24/packages/accounts-base/accounts_server.js#L1210).

This is also mentioned in the [docs](http://docs.meteor.com/#/full/meteor_users):

> By default, the current user's username, emails and profile are published to the client.

And

> If the autopublish package is installed, information about all users on the system is published to all  clients. This includes username, profile, and any fields in services that are meant to be public (eg services.facebook.id, services.twitter.screenName).

However, the docs says something like this about `autopublish`:

> By default, Meteor automatically publishes every document in your collection to each connected client. To turn this behavior off, remove the autopublish package

So I understand that you expected the entire documents in the user collection on the client. Perhaps the docs about `autopublish` should clarify this?

**Comment by stephentcannon** [comment]
This is more of a stackoverflow question I think and not a bug.  The behavior described is what is intended by the Meteor docs.

If you want the user to see fields outside of Meteor.user().profile then you have to publish/subscribe to them.

On server...
````
Meteor.publish("myuser",
  function () {
    return Meteor.users.find(this.userId,
      {fields: {createdAt: 1}});
  }
);
````

On client...
````
if(Meteor.user()){
    Meteor.subscribe('myuser');
}
````

For an admin user to get all user documents maybe something like...

On server...
````
Meteor.publish("allusers",
  function () {
    return Meteor.users.find({_id: this.userId, admin: true},
      {fields: {createdAt: 1}});
  }
);
```` 

On client...
````
if(Meteor.user()){
    Meteor.subscribe('allusers');
}
````

Though I could be completely wrong here.

**Comment by glasser** [comment]
I agree that this is intentional and documented (under the accounts section), and also that a docs PR to improve the main documentation of `autopublish` to mention that `Meteor.users` is an exception would be good.
