### ISSUE TITLE
meteor mobile builds broken due to cordova server outage

### ISSUE THREAD

**Issue by thetwosents** [meteor/meteor#3726]
I can create a new project with meteor create and then add the iOS platform and do meteor run iso-device -p 3000 and get this error:

Error while running for mobile platforms: Error running                         
/Users/jonsenterfitt/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: version not found: 0.2.10 : org.apache.cordova.console/0.2.10
at RegClient.<anonymous>
(/Users/jonsenterfitt/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
at Request.self.callback
(/Users/jonsenterfitt/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/Users/jonsenterfitt/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/jonsenterfitt/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:943:16
at process._tickCallback (node.js:419:13)

Fetching plugin "org.apache.cordova.console@0.2.10" via plugin registry

Doesn't make any sense because my other install works fine?

**Comment by oriolnoya** [comment]
Same problem here.
It seems that version 0.2.10 of org.apache.cordova.console is removed from http://plugins.cordova.io/#/package/org.apache.cordova.console

**Comment by thetwosents** [comment]
Yep. Hoping someone from the meteor team can grab this one otherwise I can’t see myself using Meteor for the multiplatform app I’m about to start sadly

**Comment by Hellyna** [comment]
+1

**Comment by Slava** [comment]
What happened exactly? Did Cordova just delete all old versions of the plugin? I am working on a release that updates all Cordova dependencies, so it shouldn't be a problem soon.

In the meanwhile you can work-around it by adding the newest version directly:

`meteor add cordova:org.apache.cordova.console@0.2.13`

**Comment by thetwosents** [comment]
So essentially I hadn't run on an iOS device in a while and then tried, started having that error. I'll try the add, test and then let you know

**Comment by MartinKolb1987** [comment]
I had to add all of these apache plugins. Now it works fine.

org.apache.cordova.console@0.2.13
org.apache.cordova.file@1.3.3
org.apache.cordova.file-transfer@0.5.0
org.apache.cordova.device@0.3.0
org.apache.cordova.statusbar@0.1.10
org.apache.cordova.splashscreen@1.0.0

**Comment by Slava** [comment]
@MartinKolb1987 yes, looks like all cordova plugins have lost their older versions in the registry.

**Comment by Slava** [comment]
Looks like it was a release process mistake and the Cordova team is aware of it: http://markmail.org/message/wfpjqkjr2pyiairr

**Comment by thetwosents** [comment]
Friday the 13th...coincidence? Okay so heading to office now to try and fix my environment. Thanks guys!

**Comment by harfangeek** [comment]
MartinKolb1987>
I still have an error message saying:
"Failed to install 'org.apache.cordova.splashscreen':CordovaError: Plugin doesn't support this project's
cordova-android version. cordova-android: 3.5.1, failed version requirement: >=3.6.0"

What can I do?

**Comment by thetwosents** [comment]
I added all the apache plugins that you suggested and still had another issue

"org.apache.cordova.inappbrowser@0.5.1"

**Comment by thetwosents** [comment]
Thank you @n1mmy for the rename...was way too late last night

**Comment by harfangeek** [comment]
thetwosents>

Same, I addedd org.apache.cordova.inappbrowser@0.6.0

**Comment by n1mmy** [comment]
@thetwosents No worries... your title was fine. Just wanted to update for new people now that we know more =)

**Comment by thetwosents** [comment]
@harfangeek You deserve an award. I know it's a simple solution but that's definitely going to help some people get back on their feet. 

Just as a circle back: 

meteor add cordova:org.apache.cordova.console@0.2.13
meteor add cordova:org.apache.cordova.file@1.3.3
meteor add cordova:org.apache.cordova.file-transfer@0.5.0
meteor add cordova:org.apache.cordova.device@0.3.0
meteor add cordova:org.apache.cordova.statusbar@0.1.10
meteor add cordova:org.apache.cordova.splashscreen@1.0.0
meteor add cordova:org.apache.cordova.inappbrowser@0.6.0

will repair a project for the time being. Thanks @Slava and @harfangeek so much. I owe you both a drink.

**Comment by n1mmy** [comment]
Thanks for the explicit command list, @thetwosents. That should help new people coming here.

Re-opening the issue for now, until Cordova fixes the underlying issue.

**Comment by thetwosents** [comment]
Thanks @n1mmy !

**Comment by utopianami** [comment]
Thanks @thetwosents :]

**Comment by joseluisq** [comment]
@thetwosents :+1:

**Comment by joseluisq** [comment]
@n1mmy @thetwosents the same error occurs when it runs meteor for an **Android** device

```sh
$ meteor run android-device

Error while running for mobile platforms: Error running                            
/home/joseluis/.meteor/packages/meteor-tool/.1.0.40.us37k3++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/cordova-scripts/cordova.sh
Failed to install 'org.apache.cordova.splashscreen':CordovaError: Plugin doesn't
support this project's cordova-android version. cordova-android: 3.5.1, failed
version requirement: >=3.6.0
```
Any idea?

**Comment by harfangeek** [comment]
@joseluisq i'm still stuck at this point too

**Comment by htsh** [comment]
@joseluisq & @harfangeek 

+1. exactly the same thing when attempting "meteor run ios" or "meteor run android"

**Comment by joseluisq** [comment]
@harfangeek sure this looks an issue in Cordova packages..

**Comment by 3210jr** [comment]
@n1mmy Tried running all the cordova plugin updates but nothing.
@joseluisq & @harfangeek +1. Im stuck here too.
Please post something if anyone figures this out

**Comment by n1mmy** [comment]
Hrm. The dependecy on splashscreen comes from the `launch-screen` meteor package which is not essential. Try overriding it like this:

(in the top level directory of your project)
```
meteor remove cordova:org.apache.cordova.splashscreen

mkdir -p packages/launch-screen

cat > packages/launch-screen/package.js <<EOF
Package.describe({
  summary: "Dummy package to override launch-screen",
  version: '1.0.1'
});
EOF

```

This should cause your project to not need the `org.apache.cordova.splashscreen` plugin.

If you get an error from XCode about please rebuild precompiled headers, you may need to delete the directory it spits out. Eg (but replace with the directory from your error):

```
rm -rf '/var/folders/kj/mywgv4j54xqc25spf37z47pw0000gn/C/com.apple.DeveloperTools/6.1.1-6A2008a/Xcode/SharedPrecompiledHeaders/Local Market-Prefix-djxjkrukeccghsesvxufvnamkybk/
```

**Comment by 3210jr** [comment]
@n1mmy works like a charm!
Thanks!

**Comment by n1mmy** [comment]
@3210jr Great! Glad to hear it.

Sorry for the trouble. Hopefully Cordova manages to get their old package versions restored soon.

**Comment by thetwosents** [comment]
Meteor support gets 5 stars easily

**Comment by molleman** [comment]
Same for me too, i added the packages manually, but then got an error on
`Error: version not found: 0.3.2 : org.apache.cordova.camera/0.3.2`

then added it, and still get that error

**Comment by Slava** [comment]
@molleman you probable want to add that plugin of version 0.3.5. You can find the latest version here http://plugins.cordova.io/#/

**Comment by harfangeek** [comment]
@n1mmy thank you very much! I can begin having fun with mobile export :)

**Comment by molleman** [comment]
@Slava how do i add the plugin?

**Comment by harfangeek** [comment]
@molleman meteor add cordova:org.apache.cordova.camera@0.3.5

**Comment by MartinKolb1987** [comment]
you can add this with meteor add ... or you can put it right into .meteor/cordova-plugins file.

**Comment by molleman** [comment]
cheers that worked

**Comment by joseluisq** [comment]
@n1mmy works fine forn now !

![image](https://cloud.githubusercontent.com/assets/1700322/6205017/ee8d3bbc-b52c-11e4-80a1-7891cd39b474.png)

I hope Cordova can solve this.
Reagrds

**Comment by n1mmy** [comment]
Looks like Cordova has things going again and old plugins are back in the registry.

Things should be back to normal now.

Sorry for any inconvenience.

**Comment by wal-fazil** [comment]
@n1mmy thanks

**Comment by MFQ** [comment]
@n1mmy thanks

**Comment by andrerfneves** [comment]
Sweet! Thanks @n1mmy. Having to add those plugins manually was a pain. Cheers
