### ISSUE TITLE
FR: Make local storage async

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3729]
If Core wants us to use Meteor in Chrome Apps or React Native localstorage have to be async - eg. accounts etc. currently depends on sync.

(This is a really old feature request of mine)

**Comment by stubailo** [comment]
Can you be more specific with what you mean by "async"? You mean getting data from localstorage should involve a callback? Or that some implementations of localstorage only work via callbacks and we don't support this?

**Comment by raix** [comment]
Yes async requires callback,

https://github.com/meteor/meteor/issues/1860
https://github.com/meteor/meteor/issues/2643

**Comment by glasser** [comment]
This is a good feature request, but it would be helpful to be really specific and point out which target environments don't support any synchronous localstorage-style APIs.

**Comment by raix** [comment]
Platformes with async only localstorage:
* Chrome packaged apps - not sure if this counts chrome os and extensions
* react native (due to the bridge is async)

(Localforage from Mozilla looks Nice, but it's missing ability namespace stores + for account we want a saying about where tokens May be stored)
