### ISSUE TITLE
Spiderable only works if I remove all of my script tags

### ISSUE THREAD

**Issue by dasmodel** [meteor/meteor#3731]
I've been trying to implement the spiderable package today, and wasn't able to get it working for awhile because I was seeing this error when I went to  http://localhost:3000/?_escaped_fragment_=

`Meteor code must always run within a Fiber. `

After lots of debugging I got it to work when I removed all of the `<script>` tags in my `<head>`. The issue is that I need those tags in order to load services for my site like typekit, zopim, google analytics, etc. 

How can I get spiderable to work and keep my script tags?

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by dasmodel** [comment]
It's actually a conflict with iron-router + spiderable. The script tags were a red herring. You can literally just create a fresh meteor project with spiderable + iron router + phantomjs installed to reproduce.

**Comment by glasser** [comment]
OK, sounds like a bug worth raising on the `iron:router` repo. If the Iron Router maintainers diagnose it as an underlying Meteor bug then they/you can file a bug here with more precise details which doesn't require using iron:router. https://github.com/iron-meteor/iron-router
