### ISSUE TITLE
Improve Blaze performance in comparison to React.js

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3732]
**_2 Upvotes**_ At the [Hype! React Conf talk from 2015](https://www.youtube.com/watch?v=z5e7kWSHWTg) interesting demos were presented. One of them was also a performance test and comparison with other reactive rendering engines. Blaze was not among them. But I [implemented it](https://github.com/mitar/reactconf-2015-HYPE) and discovered that it sadly performs much slower than React.js. Could this be improved?
- You can see Meteor demo here: http://dbmon.meteor.com/
- Original source code: https://github.com/ryanflorence/reactconf-2015-HYPE
- My code: https://github.com/mitar/reactconf-2015-HYPE

See the video linked above to see how React.js performs, or just run it.

**Comment by wiber** [comment]
+1

**Comment by KingScooty** [comment]
+1

**Comment by murillo128** [comment]
I have been using your project to test the performance of my client side libraries, and found this issue https://github.com/meteor/meteor/issues/3890 which could be causing some delay in the rendering of the templates as it requires parsing HTML data instead of directly creating the DOM node.

**Comment by stubailo** [comment]
Hi @mitar! Thanks for creating a good example of a case where Blaze performance could be better. We definitely need more benchmarks so that we can track improvements in performance over time.

Do you think there is a way to convert this app to a benchmark that returns numbers about performance? Then it will be much easier to gather actionable data.

**Comment by mitar** [comment]
Yes, I think so. So it simply renders the content as fast as possible. So we could probably measure how many times it renders per second. There is also the memory usage widget, we could take the data about memory usage from there as well. Sadly, I do not have time to work more on this, but feel free to build upon this code.

**Comment by dai-shi** [comment]
@mitar @stubailo I think I did what is requested. Please see https://github.com/dai-shi/rendering-perf-demo-2015-hype
Meteor version is updated to 1.2.1 which is far better than before, but still slower than React.

**Comment by qbolec** [comment]
Hi,
I'm trying to render list of 800 divs, and it seems that Blaze is quite slow compared to other options.

| option | time in ms run 1 | time in ms run 2 | time in ms run 3 |
| --- | --- | --- | --- |
| 1 | 627 | 519 | 528 |
| 2 | 80 | 92 | 89 |
| 3 | 354 | 350 | 414 |
| 4 | 313 | 323 | 384 |
| 5 | 282 | 285 | 294 |

option 1 - the original code which was slow:
```
{{#each line in transcription}}		
					<div class="TranscriptionViewerComponent-line">
						<div class="TranscriptionViewerComponent-timestamp">{{formatSeconds line.startTime}}</div>
						<div class="TranscriptionViewerComponent-speaker">{{line.speaker.name}}</div>
						<div class="TranscriptionViewerComponent-text">{{line.text}}</div>
					</div>
				{{/each}}
```

option 2 - replaced the body of the loop with a single character "a": 
```
{{#each line in transcription}}		
  a					
{{/each}}
```

option 3 - replaced the bodies of mustaches with a single character "a":
```
{{#each line in transcription}}		
					<div class="TranscriptionViewerComponent-line">
						<div class="TranscriptionViewerComponent-timestamp">a</div>
						<div class="TranscriptionViewerComponent-speaker">a</div>
						<div class="TranscriptionViewerComponent-text">a</div>
					</div>
{{/each}}
```

option 4 - removed the divs, but leaving the mustaches intact:
```
{{#each line in transcription}}		
						{{formatSeconds line.startTime}}{{line.speaker.name}}{{line.text}}
{{/each}}
```

option 5 - using a manual html string generation in helper
```
{{#each line in transcription}}
  {{{helpMeRenderLine line}}}					
{{/each}}
```
```
helpMeRenderLine(line){
    const timestamp = this.formatSeconds(line.startTime);
    const name = line.speaker.name;
    const text = line.text;
    return `
    <div class="TranscriptionViewerComponent-line">
      <div class="TranscriptionViewerComponent-timestamp">${timestamp}</div>
      <div class="TranscriptionViewerComponent-speaker">${name}</div>
      <div class="TranscriptionViewerComponent-text">${text}</div>
    </div>`;
  }
```

In all options the implementation of formatSeconds was : 
```
formatSeconds(timestamp){
    if(!timestamp){
      return '';
    }
    const timestampMs = Math.floor(timestamp*1000);
    const seconds = Math.floor(timestampMs/1000)%60;
    const minutes = Math.floor(timestampMs/1000/60)%60;
    const hours = Math.floor(timestampMs/1000/60/60);
    function twoDigits(x){
      return x<10?'0'+x:''+x;
    }
    return (hours? hours + ':' + twoDigits(minutes) : minutes) + ':' + twoDigits(seconds);    
  }  
```

I'm using https://atmospherejs.com/peerlibrary/blaze-components package.
I'm not sure what is the reason this rendering is so slow.
It seems that the speed is correlated with the number of DOM nodes emitted (compare options 2 and 3).

**Comment by hwillson** [comment]
Moved to meteor/blaze#207 - closing here - thanks!
