### ISSUE TITLE
Meteor Android platform install wants /dev/kvm on VirtualBox guest

### ISSUE THREAD

**Issue by capouch** [meteor/meteor#3734]
I am trying to run a Meteor Android app on a VirtualBox guest using these instructions:
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux

On that page, it says:
"Note that KVM will not be enabled if you're running under virtualization (e.g. on EC2, on in VMWare/VirtualBox/Xen)."

I already have a full Android development environment set up on my guest instance, and am happily running all kinds of apps, both native-built and Cordova-based, on my Android phone. 

I try to install the Android plugin with this command:
env USE_GLOBAL_ADK=t meteor --verbose add-platform android
. . . . . . . . 
which fails thus:
/dev/kvm not found                            
Please add the Android platform to your project first.

I wonder if the first-linked documentation above is incorrect or incomplete, or whether the inability to install the platform on a VirtualBox guest is a bug in Meteor contrary to the quoted snippet indicating otherwise.

**Comment by Slava** [comment]
@capouch this looks like a real bug, that we should fix!

**Comment by capouch** [comment]
HOPING!!!  I'm not smart enough to fix it myself, and I really really really want to use Meteor with Android, developing on a VM.

**Comment by Slava** [comment]
@capouch what is the problem of installing the Meteor-specific ADK w/o using the global one? It would take up space on disk, but other than that it will be a valid workaround?

**Comment by capouch** [comment]
Maybe nothing, but our virtual machines are standardized and used for all kinds of different development tasks in an academic setting.  That includes a pair of Android environments, one via Eclipse and the other with Studio.  Adding a whole second SDK into the mix would be possible, but I worry it will introduce some inconsistencies because of required paths, etc.  Maybe people do this all the time, but I fear trying to roll it out with a broad group of students, some of whom are just getting started developing.  So "needless complexification" is the primary concern.  Does that make sense?
