### ISSUE TITLE
Issue with packages when there are globally scoped variables and package exports

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#3735]
If a js file exports something to `window.VariableName` *and* there is an `api.export('VariableName')`. The api.export definition will overwrite the definition already made within the package.

Reproduction:

```
meteor create bug
cd bug
meteor add hammer:hammer
```

1) Characteristic
Access `Hammer` in the js console, it is undefined

2)To fix it remove the `api.export("Hammer")` from the package.

While this is a 3rd party package the issue comes from the way Meteor asks for globals to be defined. The issue isn't caused by HammerJS. It's caused by it defining itself in the window namespace & Meteor overriding this.

**Comment by glasser** [comment]
I think this is working as intended.  `api.export` exports package-level variables, as documented.  So it's effectively exported your nonexistent package-level variable.

The theory here is that Meteor packages should not define globals on `window`, and it's your responsibility as a repackager to prevent your package from polluting the global namespace.
