### ISSUE TITLE
Issue when building app with external mongodb

### ISSUE THREAD

**Issue by linhkurt** [meteor/meteor#3737]
Hi all,

I have a remote meteor server which use and external mongodb:
<code>MONGO_URL="mongodb://demo:demo@128.199.99.75:27017/demo" meteor</code>
This works fine when I open the url <code>http://128.199.99.75:3000</code>

On client, I build the project with the following command:
<code>meteor build --debug /path/to/build/folder/  --server=http://128.199.99.75:3000 </code>

However, when I open the xcode project and run on ios simulator, the app (index page) displays for only 1 second and then dispappear, giving me error: "looks like there's no route on the client or the server for url: http://meteor.local"
And in the console, there are logs from "1 second display", and then:

<pre><code>
restartServer with location /Users/linhkurt/Library/Application Support/iPhone Simulator/7.1/Applications/78DF0243-D247-47F2-970E-9FF9328AD1EA/Library/NoCloud/meteor/e472f3cadba7d06a39fcb19f006df26c8d783ee6
2015-02-16 03:07:51.204 Demo[53606:60b] start serving (
    "/Users/linhkurt/Library/Application Support/iPhone Simulator/7.1/Applications/78DF0243-D247-47F2-970E-9FF9328AD1EA/Library/NoCloud/meteor/e472f3cadba7d06a39fcb19f006df26c8d783ee6",
    "/Users/linhkurt/Library/Application Support/iPhone Simulator/7.1/Applications/78DF0243-D247-47F2-970E-9FF9328AD1EA/Demo.app/www/"
)

2015-02-16 03:07:51.208 Sam Demo[53606:60b] Resetting plugins due to page load.
</code>
</pre>
I am using Meteor 1.0.3.1.
Please let me know if I am doing anything wrong. Thank you very much!

**Comment by linhkurt** [comment]
I would like to update. 
I just tested the app with localhost (working), and remote server (not working). 
In both cases, the line <code> restartServer with location ..... "Resetting plugins due to page load." </code>appears. So i think this is normal log, not an error.

However, I still don't know why the app does display for a moment, then redirect to a page says : "looks like there's no route on the client or the server for url: http://meteor.local"

**Comment by glasser** [comment]
I think that message comes from `iron:router`, a separate piece of software maintained by another team.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
