### ISSUE TITLE
Accounts.emailTemplates.enrollAccount.subject and title Not Working 

### ISSUE THREAD

**Issue by radiegtya** [meteor/meteor#3739]
Hi I can't change my email template for 
Accounts.emailTemplates.enrollAccount.subject and title while the siteName and from work perfectly.

Any Suggestion for this?

Thanks

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

**Comment by radiegtya** [comment]
ok Thanks @glasser
