### ISSUE TITLE
DDP is lacking backpressure control

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3740]
At the moment there is no backpressure control defined in DDP. When you subscribe to the publish function you are starting to get messages as fast as possible and if you are unable to handle them in your subscription at the provided speed, they just queue up. It would be great if there would be a way to influence with backpressure the speed with which messages are arriving.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
After more thought, I think that the best API would be to add a callback to `observeChanges` which you should call when you finished processing the change. This is similar to how [node.js is doing in streams](http://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback_1). They give you a callback (often named `next`) which you call to signal that you are ready for the next thing.

So on the client you would do something like:

```
collection.find().observeChanges({
  added: function (id, fields, next) {
    // do something
    next();
  }
})
```

On the server side callback would not be needed because we can use fibers.

So the idea is that if during processing of one change new changes come in, they are combined together. So if the program is processing one document `added` change, and in meantime both `added` and `removed` come for one other document, then after processing of `added` change for the first document, nothing more is called.

This would help also with oplog backlogs. If code is too slow to process all changes, instead of failing back to diff, maybe things can be simply aggregated together.

But probably not all observers like this. Some might like that really all changes are processed. Those could use this pattern:

```
collection.find().observeChanges({
  added: function (id, fields, next) {
    next();
    // do something
  }
})
```

So immediately call `next`, to mark next change as being interested in, and then continue with processing. This needs to not run the next change callback inside `next()`, but just use it to mark and still run the next callback after the current one returns.

Not sure how you would signal that inside a fiber though. Maybe fiber implementation should still get a callback.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=DDP%20is%20lacking%20backpressure%20control&body=Migrated%20from:%20meteor/meteor%233740) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
