### ISSUE TITLE
"Only 64-bit Intel processors are supported at this time" 

### ISSUE THREAD

**Issue by kylepierce** [meteor/meteor#3741]
I have had meteor installed for a few months. I tried to run a meteor app a few days ago and now I keep getting this error. "Only 64-bit Intel processors are supported at this time". I have tried reinstalling meteor, and deleting meteor in usr/local/bin. I am using a retina macbook pro so I assume that it has something todo with my path being messed up.

**Comment by glasser** [comment]
Can you tell me the result of the following commands in this order:

```
uname -p
sysctl -n hw.cpu64bit_capable
echo $?
```

**Comment by kylepierce** [comment]
i386
-bash: sysctl: command not found
0

**Comment by glasser** [comment]
Did you remove `/usr/sbin` from your PATH?

**Comment by kylepierce** [comment]
Someone had to make some changes to get play framework to work. I dont know if the PATH was changed.

**Comment by glasser** [comment]
Does `echo $PATH` list `/usr/sbin`?  I think you're missing it and that that's the problem.  Figure out how you edited your PATH (maybe look through files in your home directory starting with a `.`) and get `/usr/sbin` back in there.

**Comment by kylepierce** [comment]
echo $PATH
/usr/local/heroku/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/local/git/bin:/usr/bin:/bin

**Comment by kylepierce** [comment]
This thread helped me fix the $PATH issue. In case anyone else runs into this issue in the future. 

Thanks for your help. 

https://discussions.apple.com/thread/5364745

**Comment by amitesh786** [comment]
I got the same issue on "Darwin Kernel" and I looked in their installation code which was something like

" if [ "$UNAME" = "Darwin" ] ; then
 ### OSX
  if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
    # Can't just test uname -m = x86_64, because Snow Leopard can
    # return other values.
    echo "Only 64-bit Intel processors are supported at this time."
    exit 1
  fi "

So, guys solution is very simple could you try this on your terminal -

* export PATH=/usr/sbin:$PATH && curl https://install.meteor.com/ | sh
* meteor --help
* If you want you can checkout this "meteor npm" - https://www.npmjs.com/package/meteor

Hope it helps, if not let me know.

**Comment by SakibHasanCse** [comment]
### **I get the same error :(
any one can help me, I'm tired of trying all the methods**


```
❯ meteor
Only 64-bit Intel processors are supported at this time.
```
