### ISSUE TITLE
Alternatives to spiderable

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#3743]
I understand spiderable is the current solution to getting pages accessible by bots but is it a long term solution?

I find myself spending more time debugging and trying to understand the issue with spiderable than developing our app and its very frustrating. We spent so much time building it only to be let down by this & Google is definitely penalizing us when it doesn't see html.

I have a site now which spiderable can't seem to understand now. What worked a few weeks ago just breaks suddenly. This impacts our SEO and this is why I have to ask the question.

Here is a distilled reproducible version bit of the issue I face. This is the portion where spiderable delegates a request to phantomjs to request a URL & before it's able to serve it out as html.

Try running `phantomjs` on the below Meteor site, with `--debug=true`. There isn't anything to understand the issue. This code is distilled from the spiderable package. I have chosen this since it doesn't require access to the server end of things (since the rendering is done by the local phantomjs installation)

This used to work before, if there's any curiosity about something I may have missed on the server: publishes always return something & if you run the code under chrome it works fine (the code that checks when its ready)

```
var page = require('webpage').create();
console.log('Loading page...');
page.open("https://eato.co.in/", function(status) {
console.log('Page load status: ' + status);
phantom.exit();});
```

If I run it I get (on multiple servers, including on AWS/DO and my local computer) :
```
Loading page...
2015-02-16T20:02:46 [DEBUG] Network - Resource request error: 2 ( "Connection closed" )
Page load status: fail
```

There is no information from this, it works fine for an Apache site/any other site. It's just the Meteor site, or something about it that closes the connection.

The issue is that we're relying on phantomjs for a pretty important part of the app (SEO) and its not very reliable.

If the above reproduction does work for you without any issue is it possible we can have guidelines on what to use for spiderable (versions needed/known issues)

**Comment by glasser** [comment]
If you want help with your specific bug, I'd recommend trying to minimize the issue into a concise reproduction and reporting that as a bug.

As far as the general issue goes, https://trello.com/c/Lz07fBAm/7-server-side-rendering is on our roadmap, in the Future section.  Currently we do not have an ordering for the future of our roadmap.
