### ISSUE TITLE
Can't access an original TemplateInstace from the helper in Meteor

### ISSUE THREAD

**Issue by chompomonim** [meteor/meteor#3745]
I try to to access an original `TemplateInstance` from the meteor helper. I'm aware of the `Template.instance()` but it appears to return the template instance where the helper was called, not the template instance for which the helper was defined.

Imagine we have two tiny templates:
```html
<template name='demo'>
  <h1>{{helper}}</h1>
  {{# border}}
    <h2>{{helper}}</h2>
  {{/border}}
</template>

<template name='border'>
  <div style="border:1px solid red">
    {{> UI.contentBlock}}
  </div>
</template>
```

With the following behaviour:
```JavaScript
Template.demo.created = function() {
  this.result = "OK";
}

Template.demo.helpers({
  helper: function() {
    var tmpl = Template.instance();
    return tmpl.result || "FAILED";
  }
});
```

I've expected to obtain two "OK" for the demo template: the second one should be in the red border. But since `Template.instance()` returns original TemplateInstance only when helper is called at the top level of its owner template the result is "FAILED" (of course in the red border).

I think `Template.instance()` should show me instance of `demo` as it was called from there.

**Comment by rclai** [comment]
This was already addressed and fixed for the next release

**Comment by chompomonim** [comment]
When do you plan next release? I'm not sure if I should wait for fix or code some hack to solve my problem.

**Comment by rclai** [comment]
Run meteor like this:
`meteor --release TEMPLATE-CURRENT-DATA@0.0.1`

**Comment by rclai** [comment]
Another alternative is to use `aldeed:template-extensions`, which has super nice features, especially with dealing with template instances.

**Comment by stubailo** [comment]
As @rclai said above, this issue is already addressed and the fix will come out in the next release, probably 1.0.4.
