### ISSUE TITLE
How to display item at index 0 in an array

### ISSUE THREAD

**Issue by stlouisweb** [meteor/meteor#3746]
Is it possible through spacebars to display the value of an item at index 0 in an array, sort of like 
```
{{#each}}
  {{item}}
{{/each}}
```
but to only show the first item like
```
{{items[0]}}
```
something like that?

**Comment by Slava** [comment]
I think you want `{{items.[0]}}`, this might look strange but it fits into the Handlebars model of "paths".

You can read more here: https://github.com/meteor/meteor/tree/devel/packages/spacebars#identifiers-and-paths

**Comment by stlouisweb** [comment]
works like a charm
