### ISSUE TITLE
Add Meteor.isProduction var

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3748]
***3 Upvotes*** While everyone could make their own `Meteor.settings` entry, it would be helpful if this was standardized in core. This was helpful in Rails – the framework itself had a concept of which environment it was running in, and for instance by default used `sqlite` in devel and `pg` in production. One major way standardization would be helpful is for Meteor packages that want to do one thing in devel and something else in production, or only are for devel, like `insecure` or `rahul:animate-everything`.

This is mentioned in #3409. Pardon if there is already another issue specifically for this – it's getting harder to search through so many past issues!

**Comment by glasser** [comment]
One issue with this particular request is that it's unclear if, say, your staging server should count as production.  I do think we should make it easy to figure out if you're in the one development environment that meteor knows about: the dev-mode runner!

(And we should rename `run --production` to `run --minify`.)

**Comment by wursttheke** [comment]
Let's do it like Rails! There you can define your own environments (like staging) if you want. From the docs:

http://guides.rubyonrails.org/configuring.html#creating-rails-environments

>By default Rails ships with three environments: "development", "test", and "production". While these are sufficient for most use cases, there are circumstances when you want more environments.

>Imagine you have a server which mirrors the production environment but is only used for testing. Such a server is commonly called a "staging server". To define an environment called "staging" for this server, just create a file called config/environments/staging.rb. Please use the contents of any existing file in config/environments as a starting point and make the necessary changes from there.

>That environment is no different than the default ones, start a server with `rails server -e staging`, a console with rails console staging, Rails.env.staging? works, etc.

**Comment by wursttheke** [comment]
Just thinking...

```javascript
Meteor.addEnvironment("staging", {
  minify: true,
  sendEmails: false,
  whatEverConfig: "youNameIt",
});
```
Start the server with:
```bash
meteor -e stanging
```

Then in the code:
```javascript
Meteor.isEnvironment('staging') // => true
```

**Comment by lorensr** [comment]
I'd stylistically prefer `Meteor.env` as a var that held `'staging'`.

**Comment by mariorodriguespt** [comment]
@wursttheke I'm doing something similar using Meteor Settings, I have 2 files for development and production. Maybe we could use your suggestion `meteor -e stanging` but linked to the configuration/settings JSON files.

**Comment by wursttheke** [comment]
@mariorodriguespt You're absolutely right. Actually I'm currently doing it the same way. 

But there is no agreement on how to do it. (E.g check the current environment with `Meteor.settings.env === "staging"` ??)

You can essentially build whatever 'environment feature' you want with the settings param, which is great. But I think what Meteor needs (in general) is more conventions about how to do these things. I feel that at the moment everyone is doing their thing.

**Comment by mariorodriguespt** [comment]
Something tells that we're going to get such feature when MDG releases Galaxy.

**Comment by teknologist** [comment]
+1 for this. Especially when we use CI like Jenkins to automate build/test/deploy to UAT environments.

**Comment by d4nyll** [comment]
+1. But I think two environments are enough and don't see a need for anything more than development and production. In my opinion, the staging environment should be the same as the production environment, so we shouldn't need separate environment settings between staging and production.

I agree with @glasser that it should be `Meteor.isDevelopment` instead of `Meteor.isProduction`, since most code should go into production anyways, we should instead explicitly mark the ones that doesn't.

**Comment by jboulhous** [comment]
We may use the `debugOnly` introduced in v0.9.4

`meteor create --package dev`

in `package.js`
```javascript
Package.describe({
  name: 'dev', version: '0.0.1', summary: '', git: '', documentation: 'README.md',
  debugOnly: true
});

Package.onUse(function(api) {
  api.addFiles('dev.js');
});
```
in `dev.js`
```javascript
Meteor.isDevelopment = true;
```
`Meteor['isDevelopment']` will be undefined in the bundled/production code.

May be we could have such a package in core or meteor-platform.

I hope this helps.

**Comment by zimme** [comment]
Just thought I should mention that @jboulhous made a package based on his suggestion, [jboulhous:dev](https://atmospherejs.com/jboulhous/dev)

**Comment by gwendall** [comment]
This is how I tackle this problem. 

```javascript
Meteor.isDevelopment = (Meteor.isServer ? process.env.ROOT_URL : window.location.origin).indexOf('localhost') != -1;
```

**Comment by rhyslbw** [comment]
+1

**Comment by abernix** [comment]
@lorensr This [exists already](https://github.com/meteor/meteor/blob/devel/packages/meteor/server_environment.js#L10-L17) and is [in the docs](https://docs.meteor.com/api/core.html#Meteor-isProduction).  Can we close? :smile:

**Comment by lorensr** [comment]
No way! When was that added?! Thanks 😜

**Comment by lieuwex** [comment]
@lorensr it was added in dbebcd2d904c725b2634b6c26c5c1f29a79ecb25
