### ISSUE TITLE
Meteor Update Does Not Update Packages

### ISSUE THREAD

**Issue by panw** [meteor/meteor#3750]
I would like to report a bug regarding the update functionality of the packaging system.

`meteor update` or `meteor update <package>` has not been working for me.

When I run `meteor update`, I get a message telling me that some packages has been updated, but it does not reflect in  `.meteor/packages` nor does it pull in the new updated packages' code.

When I do `meteor add <package>@<version>`, the specific package is updated, but the `.meteor/package` file appends the version number to the package (`<package>@<version>`), which seems off.

To update packages, I have been removing and re-adding them.

**Comment by glasser** [comment]
Re the change to the packages file: this is intended.  `meteor add p@1.2.3` means "I want to record that the version of p I want to use must be compatible with 1.2.3".

As far as the rest of your report is concerned, we don't have enough information to debug it.  Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
