### ISSUE TITLE
Remove unused dependencies from WebApp: htmljs, Spacebars, and Blaze

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#3753]
Currently the core WebApp package [declares dependencies](https://github.com/meteor/meteor/blob/devel/packages/webapp/package.js#L17) on htmljs, Spacebars, and Blaze. I thought that was curious, even more curious that they were being used on the server, until I went and saw that they're not actually being used anywhere in the [server-side code of WebApp](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js).

What's the reasoning for having it like this? Can we get that line updated?

**Comment by stubailo** [comment]
Interesting - I wonder how that got in there. Good idea!

**Comment by glasser** [comment]
I think they were used by the code that got factored out into `boilerplate-generator`.  (So this doesn't actually reduce any transitive dependencies, but is still good housekeeping.)

**Comment by lourd** [comment]
Ah, that makes sense. Yeah `boilerplate-generator` sure doesn't have the cleanest of APIs... it would be awesome to decouple it from Blaze and expose some sort of API for making its `toHTML` function pluggable. 

Love that `eval` on [line 96](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate-generator.js#L96) haha :smiling_imp:
