### ISSUE TITLE
Error in Cordova dependencies: version not found: 0.2.10 : org.apache.cordova.console/0.2.10

### ISSUE THREAD

**Issue by phaggood** [meteor/meteor#3755]
Trying to execute 'meteor run android', it's unable to locate the specified version of org.apache.cordova.console.  Looking around for a config file with this version,  I found a temp file /.meteor/local/build-cordova-temp/star.json which has:

"cordovaDependencies": {
"org.apache.cordova.console": "0.2.10",

Although it was labelled temp, I changed to 2.13 (current on Cordova plugin registry) but I still get:

Error: version not found: 0.2.10 : org.apache.cordova.console/0.2.10

I even tried

meteor add cordova:com.phonegap.plugins.console@0.2.13

which appeared to run correctly but didn't change the config which is still looking for the old version.   How to I set the version of the Cordova plugin that Meteor is looking for?

**Comment by Slava** [comment]
Looks related to https://github.com/meteor/meteor/issues/3726. There were problems with the Cordova Plugins registry which should have been fixed by now.

Can you follow the linked thread please and see if the instructions there fix your problem?

**Comment by phaggood** [comment]
I added the files to .meteor/cordova-plugins per #3726, I did not run all the 'meteor add (plugin) commands, then I did 'meteor run android' and it built and ran w/o error.
