### ISSUE TITLE
Meteor application on docker wont update after upgrade from 1.0.2.1 to 1.0.3.1

### ISSUE THREAD

**Issue by moremeds** [meteor/meteor#3756]
I use last Node image as base image to build meteor project. The docker is behind the corporate proxy.

I tried curl and npm install -g. Both of them can go through the proxy and download packages.

However, when I try to use meteor update, error prompts as:

Unable to update package catalog (are you offline?) => Errors while upgrading packages: error: tunneling socket could not be established, cause=socket hang up

Then the next step is using run meteor build, and I sometimes also got the error as

error: tunneling socket could not be established, cause=140434436118336:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

I echoed the proxy setting by echo it before I ran meteor command. It shown correctly.

I am not sure if this is the same issue with #689 
https://github.com/meteor/meteor/issues/689

Can someone please help?

**Comment by glasser** [comment]
When you say "last Node image", what version is that?

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

**Comment by moremeds** [comment]
The issue has been resolved. 

If someone ever encountered similar issues, check the proxy setting. 

try to change https_proxy = http://yourdomain:yourport, so diverted the traffic to http
