### ISSUE TITLE
Invalid `meteor --settings` does not throw error

### ISSUE THREAD

**Issue by emgee3** [meteor/meteor#3757]
What the title says.

Reproduction:

```bash
    meteor create test
    cd test
    meteor --settings=nonexistentfile.json
    #or
    meteor --settings nonexistentfile.json
```

Neither throws an error, though they should. I spent an embarrassing amount of time debugging an app when all that was actually happening was my settings were not there.

**Comment by glasser** [comment]
Thanks, fixed.
