### ISSUE TITLE
Explain the format of Blaze templates on a badly constructed html

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#3758]
If i have a 'html' tag in my file, meteor doesn't compile with the following error: "bad formatting in HTML template"
I guess t'woud be nice if it gave a more thorough explanation than this.
Eg, 'html tag is not expected in a Meteor app..'

**Comment by thinklinux** [comment]
Can you give some example for bad formatting? Something we can test.

**Comment by avalanche1** [comment]
updated my wording

**Comment by Slava** [comment]
Every file with an `html` extension in the project is treated by Meteor as a file containing Blaze templates. These files have only `head`, `body` and `template` tags as described in the docs: http://docs.meteor.com/#/basic/defining-templates

**Comment by avalanche1** [comment]
That may be obvious to Meteor veterans but not to newbies. So my suggestion was to give a more detailed explanation of the error to the people used to having 'html' tag in their code.

**Comment by Slava** [comment]
@avalanche1 I see, I agree that the error message could have been better. I will reopen this ticket with a better title.

**Comment by dgreensp** [comment]
The new error is: `Expected <template>, <head>, or <body> tag in template file`.
