### ISSUE TITLE
Cordova Autoupdate can't be disabled.

### ISSUE THREAD

**Issue by serviewcare** [meteor/meteor#3759]
I have a Mobile application that I would really like to provide a single build for without autoupdates enabled.

First, I want to provide a single build with a build # to my QC team and not have the source code change while they are testing if the backend is pushed to.

Secondly, I am composing my application of two separate meteor projects, and the autoupdate code is causing one of my Activities webviews to "update" with code from the other.

Any help in how to go about accomplishing this in a clean way would be greatly appreciated.

**Comment by serviewcare** [comment]
I've spent hours and hours trying to figure out a way to alter, provide my own version of, or do anything to autoupdate, and it is extremely resilient.

I've tried adding:

packages/autoupdate/1.1.5/

And modifying the code inside of it.

meteor add autoupdate succeeds as if it is using the package, and then simply pulls its source from ~/.meteor anyways.

I've tried blowing away the subscription it depends on... getting rid of the version numbers in index.html.

Any suggested workarounds would really be appreciated.

**Comment by stubailo** [comment]
Hi @serviewcare!

The `autoupdate` package has an undocumented API to prevent reloads. You can use it inside a cordova-only block like so:

```
if (Meteor.isCordova) {
  Reload._onMigrate(function (retry) {
    return [false];
  });
}
```

To do this, add the `reload` package to your app.

See the source code of the `mdg:reload-on-resume` package for more ways to use this API: https://github.com/meteor/mobile-packages/blob/master/packages/mdg:reload-on-resume/reload-on-resume.js

**Comment by thedracle** [comment]
So, this prevents reloads, but it doesn't prevent downloading/replacing the source files for the application. The result is, you stop the application, and start it again, and it will load the 'new' updated sources.

Is there any way to stop it from updating period?

**Comment by glasser** [comment]
You can also remove the autoupdate package from your app by removing the `meteor-platform` dependency and replacing it with the contents of `meteor-platform` other than `autoupdate`.

**Comment by thedracle** [comment]
Following stubailo's suggestion, and reading the autoupdate source, I figured out how to disable it in a pretty hacky way by adding reload to my package, and then setting the reference to it in Packages to null.

This causes autoupdate to exit without attempting to download anything.

**Comment by cunneen** [comment]
I tried @glasser's suggestion, but I get the following:
```
ReferenceError: Meteor is not defined
```

**Comment by jirimusil** [comment]
Hi guys, did you succed in any way with this issue? I've spent some time on it, trying different approaches from 
```
if (Meteor.isCordova) {
  Reload._onMigrate(function (retry) {
    return [false];
  });
}
```
to edit autoupdate package directly but it seems to be quite pretty often used in ddp.js which is can force autoupdate when it needs to regardless the above code. Any help would be much appreciated :)

**Comment by akshaylive** [comment]
@thedracle I figured out how to disable it in a pretty hacky way by adding reload to my package, and then setting the reference to it in Packages to null. Could you elaborate on it?

**Comment by grsabreu** [comment]
@thedracle could you create a repo with your hack?

**Comment by thedracle** [comment]
I'll put something together when I get a moment.

**Comment by grsabreu** [comment]
Well, it's not possible to disable cordova hot code push with Reload._onMigrate because the migration mechanism is different. What I've done to prevent hot code push is cloning autoupdate into my app/packages and just commenting this line https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_cordova.js#L211.

**Comment by jamielob** [comment]
Hey @grsabreu - how did you clone autoupdate successfully?

**Comment by array-addu** [comment]
Can anybody tell me how to use the meteor autoupdate package, i can't see any documentation for this on Atmosphere and Github.?

**Comment by grsabreu** [comment]
@jamielob you can just copy it from Meteor repo and put within your app packages/ directory

**Comment by grundmanise** [comment]
Similar issue... can't disable hot-code-push/autoupdate. Any help would be appreciated.

**Comment by grundmanise** [comment]
@grsabreu what line did you commented out? Package has changed and there is a total of 76 lines..

**Comment by cunneen** [comment]
@grundmanise Looking at the version on the devel branch on 11 Oct 2015, it seems to be this line that @grsabreu is referring to:

https://github.com/meteor/meteor/blob/f5076908121576f5ba04437356554926a6904358/packages/autoupdate/autoupdate_cordova.js#L211

I'm guessing that you could get the same effect by cloning and commenting out these lines (I have not tested this):

https://github.com/meteor/meteor/blob/322d606b56925c03a6313b76ff37bd198f0f05aa/packages/autoupdate/autoupdate_cordova.js#L65-L71
