### ISSUE TITLE
Meteor.Users -> services.NAME.id should NOT be unique

### ISSUE THREAD

**Issue by ashah888** [meteor/meteor#3762]
I understand the idea behind services.NAME.id being unique for Meteor accounts login purposes. However this creates a HUGE problem for some apps and the account services ID should NOT be unique!!

FOR EXAMPLE, an app that allows searching Twitter/Instagram/etc (like Storify) may have other information attached such as an article (in the case of Storify). 

**IF** the social media account in question is already linked to another account, and if I try to authenticate using that SAME social media account while logged in as another user, I am forced to log out, lose all access to my first account and log in to another account.

There is a LinkWith[SERVICE] package but that package will not work because the social media ID is found elsewhere, thereby denying the attempt to link the current account with my social media account.

PLEASE, remove the services.NAME.id unique condition.

In the mean time, if there is another way to get user's social media accessKey/Token/Secret without the LogInWith[SERVICE] function, please share it here, I'd really appreciate it.

**Comment by Tarang** [comment]
If it is not unique it sounds like there would be a mess figuring out which user a third party OAuth login belongs to.

The intent of it is this exactly I think.

If you use linkWithXX shouldn't you delete an existing user first? You may run into more problems when you have, for example two users sharing the same facebook id.

**Comment by ashah888** [comment]
I get what you mean, and I AGREE with what you're saying.

Really all I want to do is use the OAUTH methods that LogInWith[SERVICE] and LinkInWith[SERVICE] functions use to get the social media service information, and store the returned Access Key/Token/Secret information inside a DIFFERENT object inside the user's document.

But as far as I know this is not possible and days of searching did not lead me to any alternate solution.

For example I just want to be able to do something like this:

USER DOCUMENT 1
{
  services: {
    password: { ... }
  },
  auth: {
    twitter: {
      key: 'ABCDEFGHIJKL',
      secret: '1234567890'
    }
  },
  ...
}

USER DOCUMENT 2
{
  services: {
    twitter: {
      key: 'ABCDEFGHIJKL',
      secret: '1234567890'
    }
  },
  ...
}

In the example above, User 1 and User 2 shares the same key/secret. This allows User 1 to log in and use Twitter API to do stuff like search Twitter, etc. And User 1 can do this WITHOUT logging out and loggin in as User 2.

Think about a situation where an app allows a single user to use Twitter/Instagram/Facebook api to search the respective social media services. What if that user created an account using Twitter, then tried to link that single account with Instagram/Facebook too? But what if he/she had previously created an account using Instagram????

This causes so much headache. That user cannot be forced to log out because then he loses all the data he had in first user account. And since Meteor forces the service ID to be unique, I cannot get the data I need. (LogInWith[service] attempt will fail and deny me any access to service data.)

*At the very least, I should be able to authenticate and get the authenticated data and NOT save the data to user document.*

If the service ID is to remain unique, that's fine. But at least provide a function to get authenticated data before saving it to user account.

**Comment by glasser** [comment]
So, the index is created by the [`accounts-oauth`](https://github.com/meteor/meteor/blob/7bfa78a7bf6549d2a370bb75be1d7b6e42a46212/packages/accounts-oauth/oauth_common.js#L17) package, which is used by login packages such as `accounts-facebook`.  It is *not* created by the non-`accounts` oauth-related packages.  So I think you can use functionality in packages such as `facebook` (without `accounts-`) to deal with non-login OAuth usage without the index. Is that incorrect?
