### ISSUE TITLE
Extra reactive call when helper is used both with #if and within an html attribute

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#3763]
**Case 1: pressing the button 3 times gives the expected console output**

``` html
<head>
  <title>hello</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>
  {{> hello}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
  <p>{{#if isCounterEven}}even{{else}}odd{{/if}}</p>
</template>
```

``` javascript
if (Meteor.isClient) {

    // counter starts at 0
    Session.set('counter', 0);

    Template.hello.helpers({

        counter: function () {
            return Session.get('counter');
        },

        isCounterEven: function () {
            var counter = Session.get('counter');
            console.log('Inside helper "isCounterEven" (counter=' + counter + ')');
            return counter % 2 === 0;
        }
    });

    Template.hello.events({
        'click button': function () {
            // increment the counter when button is clicked
            Session.set('counter', Session.get('counter') + 1);
        }
    });
}
```

```
Inside helper "isCounterEven" (counter=0)        // After page load
Inside helper "isCounterEven" (counter=1)        // After click 1
Inside helper "isCounterEven" (counter=2)        // After click 2
Inside helper "isCounterEven" (counter=3)        // After click 3
```

**Case 2: unexpected output with modified html**

``` html
<head>
  <title>hello</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>
  {{> hello}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p style="color:{{#if isCounterEven}}blue{{else}}red{{/if}}">
    You've pressed the button {{counter}} times.
  </p>
</template>
```

```
Inside helper "isCounterEven" (counter=0)        // After page load
Inside helper "isCounterEven" (counter=1)        // After click 1
Inside helper "isCounterEven" (counter=1)
Inside helper "isCounterEven" (counter=2)        // After click 2
Inside helper "isCounterEven" (counter=2)
Inside helper "isCounterEven" (counter=3)        // After click 3
Inside helper "isCounterEven" (counter=3)
```

The issue seems to occur only if **both** conditions are met:
- `isCounterEven` is used in an html attribute
- `isCounterEven` is called as an argument of `#if` or `#unless`

**Comment by steph643** [comment]
The issue has been tested on Meteor 1.0.3.1 and WINDOWS-PREVIEW@0.1.7.

Here is the repo for WINDOWS-PREVIEW@0.1.7: https://github.com/steph643/meteor-issue-3763

You can also create an empty project and copy/past the above code.

**Comment by stubailo** [comment]
Hi @steph643, we have looked at this and it is indeed a bug. That helper shouldn't have to rerun twice.

This doesn't seem like a high priority for now because helpers should be able to rerun multiple times without adverse effects. Is there a situation where this would cause undesirable behavior if your helpers don't have side effects?

**Comment by steph643** [comment]
Hi @stubailo. I got no such situation and have no urgent need for a fix.

**Comment by Legioth** [comment]
One issue with this is performance, especially if the helper does expensive computation.

That can of course be mitigated to some degree by caching the computed value, but then you have to write the kind of code that reactive templating promises to help you avoid.

For a trivial helper used inside a tight loop, you also get quite some overhead even though you cache the value in the helper.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#172; closing. Thanks!
