### ISSUE TITLE
Testing a new package doesn't work (wrong path)

### ISSUE THREAD

**Issue by Urigo** [meteor/meteor#3768]
When creating a new package and immediately running:

    meteor test-packages

0 tests are running.
But when running:

    meteor test-packages ./

It works.
Reproduction - just create a new package:

    meteor create --package temp:testpack

**Comment by glasser** [comment]
That's working as intended — with no args, test-packages runs all local packages (ie, packages in your current git repo of meteor, packages in your app's package directory, and packages found via `$PACKAGE_DIR`).  The current directory isn't part of the package search path for any commands other than publish.
