### ISSUE TITLE
Error at Mobile oAuth Login

### ISSUE THREAD

**Issue by mariorodriguespt** [meteor/meteor#3769]
I discovered that when I try my application on the mobile and click right away on the Google Login button I get an Error. If I try some seconds later it works.

My guess on this: The Accounts oAuth settings didn't loaded just in time and this could be the cause.

I fixed the problem by checking: Accounts.oauth.serviceNames().length ( yes, I feel bad for this )

How can I subscribe to the oAuth settings?

**Comment by glasser** [comment]
Are you looking for `Accounts.loginServicesConfigured()`?
