### ISSUE TITLE
Package naming convention

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#3774]
I develop on Windows. I want my dev environment to be close to production, so I run Ubuntu on Virtualbox. I also have a Samba share set up so that I can access the files on Ubuntu from Windows Explorer.
The problem: when creating a Meteor package, the documentation says to use 'username:packagename' . Windows doesn't support colons in folder names, so when i create a Meteor package on Ubuntu, the folder name is unrecognizable via Windows Explorer and also the contents of this folder cannot be modified (Windows OS says it already in use).

**Comment by stubailo** [comment]
We're fixing this in time for the official Windows release.

**Comment by avital** [comment]
As of Meteor 1.1, packages created with `meteor create --package` no longer contain colons, even if the argument passed does.
