### ISSUE TITLE
Untrusted code may only update documents by ID when updating array element using $

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3775]
A user I offered a [solution to on SO](http://stackoverflow.com/a/28466856/1269037) ran into this:

    Company.update({_id: company._id, tags.tag: tagName}, {$inc: {tags.$.count: 1}});

> Uncaught Error: Not permitted. Untrusted code may only update documents by ID.

Also found [a blog post](https://code4foodblog.wordpress.com/2015/02/11/meteor-uncaught-error-not-permitted-untrusted-code-may-only-update-documents-by-id-when-update-array-elementusing/) about it.

Since the _id is specified, the error message may be misleading (if this isn't a Minimongo bug outright).

**Comment by glasser** [comment]
This is working as intended. We don't allow arbitrary queries as part of update over the network, just checks by ID.  This is a fix to a security hole that older versions had.  Imagine if we allowed `C.update({_id: x, secretUnpublishedField: /a/}, {$inc: {'tags.$.count': 1}})`.  Then you could detect whether the secret field matches a regexp.

It would be nice to be able to use queries from the client in cases where you determine it to be secure; https://meteor.hackpad.com/Proposal-to-replace-allowdeny-with-insertupdateremove-methods-1WCvv4P9e2h is a proposal to generalize server-side handling of client-side collection mutators to be more flexible.

**Comment by Tarang** [comment]
Is `$` supported yet on the client side?

**Comment by glasser** [comment]
Yes, but that's unrelated to the issue being reported here.
