### ISSUE TITLE
Minimongo difference: projection error

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3778]
This succeeds:

```
a = new Mongo.Collection(null)
a.insert({a: 1})
a.find({}, {fields: {_id: 1, a: 0}}).fetch()[0]
```

But on the MongoDB server it fails. 2.4:

```
error: {
	"$err" : "You cannot currently mix including and excluding fields. Contact us if this is an issue.",
	"code" : 10053
}
```

2.6:

```
error: {
	"$err" : "Can't canonicalize query: BadValue Projection cannot have a mix of inclusion and exclusion.",
	"code" : 17287
}
```

I will not comment on the fact that they changed the code number for the error between versions.

**Comment by glasser** [comment]
Ah.  In general you can't provide both inclusions and exclusions in the same query, but there's a special case in Mongo to let you say `{a: 1, _id: 0}` (ie, "only include specified fields, and don't include `_id`).  Looks like our implementation also lets you do the opposite ("include all fields but specified fields, and include `_id`"), which actually is exactly the same as just leaving the `_id: 1` out.  So we're failing to return an error, but the actual result is moderately reasonable.

Would review a PR with tests to conform to Mongo's error handling here.

**Comment by glasser** [comment]
Fixed by @adhearn !
