### ISSUE TITLE
Make package load after my package?

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#3781]
I see the `unordered` options says:

_It's okay to load this dependency after your package. (In general, dependencies specified by api.use are loaded before your package.) You can use this option to break circular dependencies._

Does it guarantee that a package will load after the package that I'm trying to write?

I'm trying to make sure that if `accounts-base` is installed, that it loads after my package.

**Comment by Slava** [comment]
No, `unordered` doesn't guarantee any order. Forcing a dependency to load **after** your package seems like an odd thing to do. Usually, you either want your dependency to be loaded before your package, or load w/o any particular order to break the load order cycle.

"How can I do this?" questions are best posed on StackOverflow or the meteor-talk mailing list, not our bug tracker
