### ISSUE TITLE
Better error handling when putting non-EJSON data into minimongo

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3783]
If a Meteor method which is defined both on the client and server side updates the collection with a non-plain subdocument, an observe running on the client is called twice.

See [reproduction](https://github.com/mitar/meteor-issue3783). Click on the button and observe the browser console. You will see that you get two `changed` entries. Once with correct old and new documents, and the second time with old and new documents which differ only in methods, but not data.

The issue is probably that `EJSON.equals` returns false in the second case and Meteor thinks that simulation was incorrect and it has to fix it.

But I would claim that the issue is that a document with methods got into the local collection on the client in the first place. Probably `EJSON.clone` should be called before adding it in the simulation to the local collection. Not that on the client a version with methods is initially stored, which is then "reverted" to the one without methods.

Or at least update should fail on the client. Because debugging this was now quite painful.

**Comment by mitar** [comment]
I updated the issue. I managed to pinpoint the issue.

**Comment by glasser** [comment]
Thanks for the reproduction. You're right that the root issue seems to be inserting non-EJSON data into minimongo.  Perhaps we need to throw a better error if you try to use Minimongo with non-EJSON types?  I assume this works fine if you use EJSON.addType (on client and server) with this Document type?

**Comment by mitar** [comment]
> Perhaps we need to throw a better error if you try to use Minimongo with non-EJSON types?

Yes, I think the best would be that you throw an error.

> I assume this works fine if you use EJSON.addType (on client and server) with this Document type?

I do not know, but I would assume so as well.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Better%20error%20handling%20when%20putting%20non-EJSON%20data%20into%20minimongo&body=Migrated%20from:%20meteor/meteor%233783) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
