### ISSUE TITLE
Log warning when app can't make DDP connection

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3785]
While the below is printed if you're using Safari remote debugging, I'm often just looking at Xcode output, and it doesn't appear there.

![image](https://cloud.githubusercontent.com/assets/251288/6313328/8b06bf7e-b959-11e4-8ed0-554d506ce3dc.png)

I just spent 5 hours tearing apart my codebase trying to figure out why my `ios-device` app wasn't working (my phone's wifi was turned off), and I want to make sure this doesn't happen to others. It's a tricky bug, because code/templates load over USB, and the app starts fine, and depending on how your app acts when a subscription never becomes ready, and depending on the state of your db (mine was empty), what renders may not make it obvious that the problem is there's no data.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by lorensr** [comment]
As of `1.3.3`, there is no indication in xcode logs that the client can't connect to the server

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Log%20warning%20when%20app%20can't%20make%20DDP%20connection&body=Migrated%20from:%20meteor/meteor%233785) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
