### ISSUE TITLE
Is there support for a load event in Meteor.Template.events?

### ISSUE THREAD

**Issue by micahblu** [meteor/meteor#3787]
I have the need to run code once the dom is fully loaded. I attempted to use: `'load body': function()...` within Meteor.Template.events but it doesn't appear to trigger. If there is no support for this, is there another way to add a listener for when a view is loaded? Couldn't find anything in the docs. Thanks

**Comment by jhuenges** [comment]
Something like [Template.rendered?](http://docs.meteor.com/#/full/template_rendered)

**Comment by micahblu** [comment]
That seems to be what I'm looking for, however it doesn't work or I'm not implementing it correctly and the documentation doesn't provide an example. I have tried the following:

```javascript
Template.myTemplate.rendered(function () {
  // my callback
});
```
This didn't work, not only that but as I inspected the Templpate.myTemplate object I didn't see the rendered method, so I then I thought that maybe I had to bind it manually and it would be triggered but that didn't work either?

**Comment by jhuenges** [comment]
I am using it in the following way:

```Template.myTemplate.rendered = function () {
  // Do stuff
}```

Works fine for me :)

**Comment by micahblu** [comment]
Funny I did the exact and it must now have refreshed and I assumed it did. Its working. Thanks for the help :)

**Comment by glasser** [comment]
Note that as of 1.0.4, the new recommended usage is `Template.foo.onRendered(function(){ ... })`

**Comment by micahblu** [comment]
ah, I like that much better and "this" would refer to that template object I suppose?

**Comment by glasser** [comment]
The [template instance](http://docs.meteor.com/#/full/template_inst), yes.
