### ISSUE TITLE
Install script detecting if update is needed

### ISSUE THREAD

**Issue by juanpastas** [meteor/meteor#3788]
It would be better if install script detect current version to know if update is necessary.

About checking inconsistencies with current version, this might be skipped since people can just delete installation folder themselves and then run the installation script.

**Comment by stubailo** [comment]
You don't need to run the install script to update Meteor, you can just use `meteor update`.

What's the case where you need to run the install script to update?

**Comment by juanpastas** [comment]
oh, I forgot about that option.
