### ISSUE TITLE
[Cordova] Use latest version of cordova package if no version is specified

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3789]
Currently:

``` bash
$ meteor add cordova:org.apache.cordova.inappbrowser
org.apache.cordova.inappbrowser: exact version or tarball url is required
```

I think it would be nice if it defaulted to the latest version.

**Comment by Slava** [comment]
This is a valid feature and would be nice to have.

**Comment by lorensr** [comment]
Current output is:

`cordova-plugin-vibration: Meteor requires either an exact version (e.g. cordova-plugin-vibration@1.0.0), a Git URL with a SHA reference, or a local path.`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BCordova%5D%20Use%20latest%20version%20of%20cordova%20package%20if%20no%20version%20is%20specified&body=Migrated%20from:%20meteor/meteor%233789) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
