### ISSUE TITLE
[Velocity/Nightwatch Integration] meteor --test doesn't launch Nightwatch tests

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#3794]
Hi there,
This is part bug-report on ``meteor --test``, part feature-request, and part establishing a paper trail for a pull request; generated during the Velocity sprint at MDG headquarters on Feb 22nd.  Basically, we want to extend the ``meteor --test`` command so that it also runs end-to-end acceptance tests using the Nightwatch framework via Velocity.  

Mostly interested in these two lines in ``tools/commands.js``
https://github.com/meteor/meteor/blob/devel/tools/commands.js#L378
https://github.com/meteor/meteor/blob/devel/tools/commands.js#1458

Which call the ``tools/run-velocity.js`` file, and the contents therein:
https://github.com/meteor/meteor/blob/devel/tools/run-velocity.js

The ``velocity:nightwatch-framework`` package currently can launch this functionality from within the ``velocity:html-reporter`` package with the [following velocity:nightwatch-framework code](https://github.com/meteor-velocity/nightwatch-framework/blob/master/nightwatch.integration.js#L51-60 
):

````js
  Meteor.methods({
    'nightwatch/run':function(){
      console.log("Server received request to run Nightwatch script...");

      var nightwatchProcess = null;

      console.log("Installing Nightwatch bridge via Npm...");
      Npm.require('child_process').exec("npm install nightwatch@0.5.36", Meteor.bindEnvironment(function(error, result){
        Npm.require('sys').puts(result);

        console.log("Launching Nightwatch with JSON configuration file...");
        nightwatchProcess = Npm.require('child_process').exec("./node_modules/nightwatch/bin/nightwatch -c ./assets/packages/clinical_nightwatch/nightwatch_from_velocity.json", Meteor.bindEnvironment(function(error, stdout){
          Npm.require('sys').puts(stdout);
          console.log('Nightwatch exited.');
          Meteor.call('nightwatch/parse/xml');
        }));
      }));

    }
})
````

So, the thinking is to add the above code, or something like it, to  ``tools/run-velocity.js``.  Would appreciate any comments on approach, command arguments, api, etc.  Will be drafting a pull-request on this item as part of Velocity project efforts.  

If we can get this integrated, we'll be able to stop using the [run_nightwatch.sh script](https://github.com/awatson1978/clinical-nightwatch/blob/master/run_nightwatch.sample.sh) which was introduced as a workaround to the isopackages not supporting executable permissions on files, as per #2595.

**Comment by Pickachu** [comment]
+1

**Comment by glasser** [comment]
Hi @awatson1978.  Thanks!  Our general policy is to take pull requests to run-velocity.js (and the lines that invoke it) that are backed by the Velocity team, and to otherwise let you track issues in your own repo.  So when this is ready, a PR (including a statement that it's what the Velocity core team wants) will be great.

**Comment by awatson1978** [comment]
Hi.  You do realize that I've been a part of the Velocity core team since it's very beginning, right?

**Comment by Slava** [comment]
@awatson1978 David says that we accept PRs to the `run-velocity.js` file from Velocity team members. He didn't question your relation to the Velocity Core team.

**Comment by glasser** [comment]
Right, I said we take PRs, and this is not a PR.

**Comment by awatson1978** [comment]
Okay then.  I'll put together the pull-request, and reference this closed ticket then.
