### ISSUE TITLE
Make it easier to discover and add common 3rd-party packages

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3795]
Rails does this, and I think it would be a good thing for Meteor to consider. Possibilities include `iron:router`, `momentjs:moment`, and `meteorhacks:npm`. There are some things that are so commonly needed (like routing, handling date/time, using npm packages) that the benefit – new users don't fumble through trying to associate different templates with URLs on their own, etc – outweighs the cost – the rare person who's making a single-page site removing `iron:router`.

**Comment by stubailo** [comment]
The difference between this and rails is that in rails adding additional packages doesn't usually increase the size of the client-side javascript, whereas some of the Meteor packages would. I do however agree that it is hard for new users to discover these packages so we should mention them in a very prominent place.

-----

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by stubailo** [comment]
I think there's room for a project that could be called "Meteor on Rails" which is basically Meteor with autoform, simple-schema, iron:router, user-accounts, etc., and has generators that can make scaffolding for a model/controller/view set.

So something like

```
meteor generate scaffold schema.js
```

Where schema.js is a file defining a set of simple schemas and collections. The command would generate a bunch of directories with tests, routes, and create/edit/update templates with autoform.

**Comment by lorensr** [comment]
Haha, I like it.

**Comment by stubailo** [comment]
Yeah I'd love to help build something like this if someone else had the time to be in charge of it.

**Comment by Rebolon** [comment]
@lorensr that's an interesting idea, but i agree with @stubailo for the javascript impact those packages can have on client-side. I see two possibilities :
When we create a project with : "meteor create myProject", at the end of the process the console might suggest 3rd party packages with a short description of each (or just the main feature of the package).
The other possibility would be to modify completly the "meteor create" to be able to be interactive. It would suggest the 3rd party package that you want to include.
It would be interesting to have options for "meteor create" command. If we imagine Meteor project creation like a Meteor distribution, then anybody could install the distribution he needs :
 - Meteor standard distribution (the actual one)
 - Meteor server distribution (remove all client code part)
 - Meteor extended distribution (with 3rd packages)
 - Meteor CMS distribution (i think it's too early to suggest this one :-)
 - ...

**Comment by stubailo** [comment]
Yeah, people have filed related issues, such as: #3042 

I think the first solution is just having a list somewhere of packages every new Meteor developer should check out; the second is maybe some kind of community meta-package like `starter-pack` that basically adds all of the commonly used packages if you don't want to think too hard. Maybe @lorensr should make one! So basically the workflow could be:

```sh
meteor create # adds meteor-platform, insecure, autopublish
meteor add starter-pack # adds iron:router, autoform, etc and links to landing page
```

It's also maybe a good idea for `meteor create` to print a link to some page where we list useful resources for learning Meteor.

**Comment by lorensr** [comment]
The correct fn to use is imply, right? `api.imply('iron:router');`. The downside of this method vs default-include is that if you add `starter-pack`, you can't easily remove individual packages that it includes – you have to remove `starter-pack` and add everything minus the one you don't want, correct?

**Comment by stubailo** [comment]
@lorensr yes that's true, which is also a problem with `meteor-platform` - if you just want to remove `blaze`, for example, there's no easy way to do it. Is there some way people could create metapackages and then we could have a way to remove parts of them?

Maybe it doesn't matter because when you start removing packages you are probably an advanced user who can handle managing their packages individually.

**Comment by lorensr** [comment]
Well that took longer than expected. At least now after typing the names out over and over, I'm less concerned about #3607 :)

I thought I'd name it `standard-app-packages`? :) 

I got carried away initially, so I decided to split it into two. Did I do it right? Any suggestions?

https://github.com/parlaywithme/starter-pack
https://github.com/parlaywithme/full-pack

Have to fix versions in the latter before publishing.

**Comment by stubailo** [comment]
Hmm the full pack seems to have some things that might not be applicable to all apps, but looks like a pretty good list!

**Comment by stubailo** [comment]
Hey, so further action on this issue is as follows:

1. The Meteor guide will recommend a lot of these packages, so they will be more discoverable
2. We will probably be modifying `meteor create` to generate some standard boilerplate according to the best practices laid out in the guide

**Comment by lorensr** [comment]
Closing in favor of:

- guide package index: https://github.com/meteor/guide/issues/180
- `meteor create` #6974
