### ISSUE TITLE
Disable appcache in Cordova

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3796]
I'd like to use appcache in standalone browsers but not inside Cordova, since Meteor already puts a copy of the files on the device. Caching the files at both levels – in the app and in the in-app browser – unnecessarily adds to load time.

**Comment by Slava** [comment]
Is this a question? "How to" questions are best asked on StackOverflow or the meteor-talk mailing list.

A workaround from me: Don't add appcache for both mobile and web. Create a local package, that depends on appcache in browsers but not in mobile.

**Comment by lorensr** [comment]
I meant it as a feature request for default behavior change. Will use your
solution for now, thanks.

**Comment by avital** [comment]
I think the point is that it should be the default behavior. I think we should re-open this ticket.

**Comment by mirstan** [comment]
+1

**Comment by abernix** [comment]
Just as FYI for anyone +1'ing this...

AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) so it seems that this should get removed from not only Cordova, but everything.  I wouldn't recommend using it in any new projects.

Service Workers are supposed to be the replacement which is being tracked in #5982.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Disable%20appcache%20in%20Cordova&body=Migrated%20from:%20meteor/meteor%233796) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
