### ISSUE TITLE
Cordova integration doesn't work for Android <= 4.1.2

### ISSUE THREAD

**Issue by taromero** [meteor/meteor#3802]
I'm working on a Meteor app which I compile to an Android app. I can install it on my `Nexus 7` (Android `4.4.4`) and a `Moto G` (Android `4.3`), but not on either my `S3 mini` (`4.1.2`) or `Galaxy Core` (~`4.1.2`).

The error message is just an `Application not installed`-like (actually it's on spanish for me) message when trying to install it. I'm installing directly from the apk in all cases, and I have set the permission for non-app-store app on all devices.

This SO post seems to have more technical data: http://stackoverflow.com/questions/28585818/meteor-android-apps-does-not-install-on-4-1-1.

**Comment by Slava** [comment]
Can you provide instructions on how can I test it and reproduce the problem on my computer w/o buying a device running Android 4.1.2?

**Comment by taromero** [comment]
@Slava sorry I doubt I can provide those instructions (I'm not sure if it's even possible to reproduce this on a regular computer). I have few (if any) knowledge about Cordova/Android.

I can confirm it doesn't work on 4.1.1 either.

Can anyone confirm successful installation of a Meteor app on Android v <= 4.1.2?

**Comment by taromero** [comment]
Related (unresolved) SO question: http://stackoverflow.com/questions/28585818/meteor-android-apps-does-not-install-on-4-1-1.
