### ISSUE TITLE
DDP should not do exponential backoff in the dev mode runner

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3807]
Exponential backoff is designed to avoid overloading servers when they restart.  This isn't relevant to the dev mode runner; it just gets in the way of hot code push.

(Of course, this will mean that users who choose to use the dev mode runner in production will see worse performance.)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=DDP%20should%20not%20do%20exponential%20backoff%20in%20the%20dev%20mode%20runner&body=Migrated%20from:%20meteor/meteor%233807) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
