### ISSUE TITLE
Use hot code push (autoupdate) to switch between dev mode proxy error page and app

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3808]
The dev mode runner shows build-time error pages over a simple HTTP request.  But you have to hit reload explicitly to get into it and get out of it.  And (due to #3807) the main app's client goes into exponential backoff mode and takes a while to notice that you've fixed the issue if you don't reload.

If it was served from a mini meteor app (with `autoupdate`),  then we could easily just HCP between the error page and the app.

(It would be even awesomer if Session got preserved when you get back, but Session is not preserved by hitting reload to see the error page now anyway, only if you don't see the error page.)

**Comment by stubailo** [comment]
Is there a good reason why we call the same thing "autoupdate" sometimes, and "hot code push" other times? Should we rename this package to "hot-code-push"?

**Comment by glasser** [comment]
Personally I prefer autoupdate, which is the newer name.  I mostly say "hot code push" because I think people used to use that term :)

**Comment by stubailo** [comment]
Interesting! Personally I think hot code push sounds a lot more exciting (and autoupdate sounds a lot like `meteor update` which is totally different), but if we decided to call it autoupdate at some point we should update all of our marketing/docs/speech to use the new term. Otherwise it's very confusing. There's also the `reload`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Use%20hot%20code%20push%20(autoupdate)%20to%20switch%20between%20dev%20mode%20proxy%20error%20page%20and%20app&body=Migrated%20from:%20meteor/meteor%233808) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
