### ISSUE TITLE
Release 1.0.3.2

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3809]
This issue tracks the release of Meteor 1.0.3.2. Have any concerns? Mention them here. Finding that the RCs are working great? Mention that here. We will keep this top-level description updated with known issues.

This release is a cherry-pick fixing #3761.  There should be no other changes from 1.0.3.1; it is a tool-only change.

The current RC is `1.0.3.2-rc.0`. Update to the release candidate with: `meteor update --release 1.0.3.2-rc.0`!

**Comment by tgoorden** [comment]
I've tried it and it works for our (dev) app that had problems with the #3761 issue before.

**Comment by glasser** [comment]
1.0.3.2 is released!

**Comment by laosb** [comment]
Congratulations! And what changes in this version? Should note it in History.md.

**Comment by glasser** [comment]
It is in history.md on devel!
