### ISSUE TITLE
Cordova not being able to specify <access origin="tel:*" launch-external="yes" /> in mobile-config.js

### ISSUE THREAD

**Issue by dotnetwise** [meteor/meteor#3811]
Although, I found this in [the code](https://github.com/meteor/meteor/blob/0e3c992fd8f178efd9e832038257ae36cec90351/docs/client/data.js#L666) it is not yet documented.

Perhaps it was not yet being released?

When will it be?

**Comment by nspangler** [comment]
I am also interested in knowing when this will be incorporated.

**Comment by nspangler** [comment]
@dotnetwise every time I try to write a file to the local file system I am getting an `CONNECTION_ERR` could this stem from `<access origin>`. See: http://stackoverflow.com/questions/28842611/meteor-cordova-filetransfer-download-error-connection-err

**Comment by Slava** [comment]
This API is implemented on the `devel` branch but is not yet released. https://github.com/meteor/meteor/blob/419befbf5f42b69095454632618ea2cc64b9a6ef/History.md#meteor-mobile-updates
