### ISSUE TITLE
cordova_build_override files are being overwritten by the build process

### ISSUE THREAD

**Issue by dotnetwise** [meteor/meteor#3812]
If you add `cordova_build_override/platforms/android/platform_www/cordova.js` e.g. with your own version of `cordova.js` it will always be overwritten by when you do `meteor run android-device`

Also `cordova_build_override/merges/android/platform_www/cordova.js` is still being overwritten.

**Comment by Slava** [comment]
@dotnetwise it is `cordova-build-override` with hyphens and not underscores: https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration#advanced-build-customization

**Comment by dotnetwise** [comment]
Even so, The things mentioned are still valid

-----Original Message-----

**Comment by Slava** [comment]
@dotnetwise if so, please provide a clonable reproduction with steps to demonstrate the issue.
