### ISSUE TITLE
Appcache only works locally not in production 

### ISSUE THREAD

**Issue by almogdesign** [meteor/meteor#3813]
I know there are some strict guidelines for contributing, but I'm really having a hard time debugging this and wanted to see if anyone else has ran into this issue. 

When I run my app locally everything is fine however when I run it in production appcache is not working. It's stuck loading and I get the following message - 

I'm deploying to modules.io and an SSL cert. 

I did try it without the SSL but still noting. 

When online 
 Document was loaded from Application Cache with manifest https://xstaging.goplatfarm.com/app.manifest
xstaging.goplatfarm.com/:1 Application Cache Checking event
xstaging.goplatfarm.com/:1 Application Cache NoUpdate event

When offline 
Document was loaded from Application Cache with manifest https://xstaging.goplatfarm.com/app.manifest
(index):1 Application Cache Checking event
(index):1 Application Cache Error event: Manifest fetch failed (6) https://site/app.manifest

**Comment by almogdesign** [comment]
I can confirm it's not any package, browser cache limit or grondDB. It seems that appcache is not loading the minified javascript

**Comment by stubailo** [comment]
It works fine when you use `meteor deploy` - one example is <http://docs.meteor.com>.

**Comment by almogdesign** [comment]
@stubailo I'm deploying to modules.io using their CLI but I also tried meteor deploy and still noting. You can view the app at test_platfarm.meteor.com 

If you look at the developer tools when your online everything is fine and when your offline you get the error message - Application Cache Error event: Manifest fetch failed (6) https://site/app.manifest

**Comment by stubailo** [comment]
```
Document was loaded from Application Cache with manifest http://test_platfarm.meteor.com/app.manifest
(index):1 Application Cache Checking event
(index):1 Application Cache Error event: Manifest fetch failed (6) http://test_platfarm.meteor.com/app.manifest
```

This is what I get when I go offline and refresh <http://test_platfarm.meteor.com>. The page seems to load fine.

What browser are you using? Does appcache work for <http://docs.meteor.com> for that browser?

**Comment by almogdesign** [comment]
I'm on chrome, it's not I just doubled checked when your online you will see the sign in form or html when your offline you will not see the sign in. It's not loading the content. That's the issue and you get that error message.

**Comment by almogdesign** [comment]
Just tested docs.meteor.com this works I see the error message not even sure it's an error message but everything works it loads the content / html. 

Not sure why my app does not?

**Comment by almogdesign** [comment]
I'm thinking maybe something is happing with the minify when it's deployed but then why would it work when I'm online?

**Comment by stubailo** [comment]
Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.

**Comment by almogdesign** [comment]
@stubailo thanks for the help, got it to the bottom of the issue. Had to do with the subscriptions and local host even with the wifi off it takes a long time for chrome to clear.

**Comment by stubailo** [comment]
Glad to hear it!
