### ISSUE TITLE
{{#each}} data context in template

### ISSUE THREAD

**Issue by eshell** [meteor/meteor#3816]
I ran into an issue that took me a little while to figure out. Not sure if it's a bug or just the way it's supposed to be.

I have an {{#each items}} {{title}} - {{url}} {{/each}} in a template. It turns out I had a {{title}} helper for something else as well in the same template.  When {{#each}} is processed, it uses the {{title}} from the helper instead of {{title}} in the {{#each}} data context.  {{this.title}} works correctly within {{#each}}.

Shouldn't {{#each}} use {{title}} from it's context instead of using the {{title}} helper? Just curious.

I can see this probably isn't an issue as normally I wouldn't be so generic with my helpers. Just took a while to figure out because I thought {{#each items}} set a new context for each item.

**Comment by stubailo** [comment]
This is working as documented: https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#name-resolution

I agree that the documentation could be more prominent, though.
