### ISSUE TITLE
Webapp scope unclear

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3820]
Some packages, for instance https://github.com/meteor/meteor/tree/devel/packages/browser-policy , say they're "part of webapp". When I do `meteor show meteor-platform`, I see `webapp` under `Implies:`. That makes me think that I should have a `BrowserPolicy` global server-side, but I don't. Maybe `webapp` pkg should be named `webapp-core`?

**Comment by glasser** [comment]
This isn't a technical decision — it's a project management one.  Meteor is a big project with many subprojects, and so we've organized them (in places like https://www.meteor.com/projects and the labels we use on GitHub) into different subprojects.

The landing page for Webapp (which may at some point split into multiple subprojects itself) is at https://www.meteor.com/webapp  It includes both the `webapp` package and various optional packages that we like to think are closer to "Webapp" than to, say, "DDP" or "Isobuild".
