### ISSUE TITLE
[Docs] packagejs example imply format

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3821]
http://docs.meteor.com/#/full/packagejs has `api.imply('templating')`, which makes me think I don't need a version. However, when I use that syntax and try to publish, I get this error:
```
$ meteor publish --create
=> Errors while publishing:                   
                                              
While publishing the package:
error: You must specify a version constraint for package iron:router
```

**Comment by stubailo** [comment]
That's a good point!

**Comment by lorensr** [comment]
Fixed by https://github.com/meteor/docs/commit/59aa801d4d44ca8c692883d847e941002479c613
