### ISSUE TITLE
Named, But Unsynchronized, Client-Only Collections

### ISSUE THREAD

**Issue by wearhere** [meteor/meteor#3825]
> This is a follow-up to #3627. After talking about that issue with MDG I thought that named, but unsynchronized, client-only collections were supported, just not documented, but I have since found bugs that prevent them from working fully as I would expect.

I wish to publish a server-side _non-Mongo_ data source e.g. Redis to the client, but–for convenience–let the client manipulate the data using Minimongo. This can be done with the following code:

```
// On the server.
Redis = new Meteor.RedisCollection('redis');

Meteor.publish('trackedmessages', function() {
  var self = this;
  var trackedMessagesHandle = Redis.matching('users:jeff:*').observeChanges({
    added: function(key, item) {
      var message = EJSON.parse(item.value);
      self.added('trackedmessages', message._id, message);
    }
  });
  self.ready();
  self.onStop(function() {
    trackedMessagesHandle.stop();
  });
});

// On the client (in a client-only file).
TrackedMessages = new Mongo.Collection('trackedmessages');
```

`TrackedMessages` must be named in order to serve as a target of the low-level `added/changed/removed` publication interface, but defining it in a client-only file keeps it from being
 defined on the server. I do not wish `TrackedMessages` to be synchronized because the server's data source is not Mongo and the server does not need to monitor changes to the client-side collection.

The above code works just fine for publishing data from the server to the client: `TrackedMessages` is populated and can be queried just as I'd expect.

However, `TrackedMessages` cannot be manipulated client-side without triggering (at least) the following bugs:

1. `TrackedMessages.remove({})` fails with the error "Untrusted code may only remove documents by ID". This should not be an error because the `TrackedMessages` is client-side only.
2. `TrackedMessages.remove({ _id: 'some ID' })` fails with the error "remove failed: Method not found".

I am glad to break these bugs out into separate issues. I have not done so because I am pretty sure that they have the same root cause: naming the collection causes Meteor to try to synchronize changes back to the server even though the collection is really client-only.

These issues could be addressed in (at least) two ways:

1. Meteor could make it possible to publish to a client-side only collection without having to name it (and so fooling Meteor into thinking that it should be synchronized).
2. Meteor could somehow detect that the collection wasn't defined on the server.

**Comment by wearhere** [comment]
A work-around for the failure of `Mongo.Collection`'s methods is to access the `LocalCollection` directly at `TrackedMessages._collection`, however I would prefer to not use private methods.

**Comment by mitar** [comment]
Aren't they supported by specifying name, but for `connection` you use `null`, no?

**Comment by glasser** [comment]
I believe @mitar is correct: a named unsynchronized connection is `new Mongo.Connect('name', { connection: null })`.  It's documented, too.

**Comment by mitar** [comment]
s/connection/collection/

**Comment by glasser** [comment]
@mitar thanks

**Comment by wildeyes** [comment]
@glasser documented where? where can I find more about this subject?
