### ISSUE TITLE
Hook support for Collections initialization

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#3827]
**_5 Upvotes**_ I'm wondering if the magicians at MDG can create some kind of hook system for collections (and maybe even all of Meteor's API's). A lot of people have tried to wrap the function, but it doesn't look/feel clean. I've seen a couple of implementations of it, but all of them sometimes have an issue when the package that contains the hook is not listed on top of the package list.

See these issue for more details: 
https://github.com/dburles/mongo-collection-instances/issues/16
https://github.com/msavin/Mongol/issues/30

Maybe another way to solve this issue would be to provide something like Mongo.collections similar to Session.keys, and it would be nice if they were both reactive.

**Comment by rclai** [comment]
+1, this would solve a lot of issues with a bunch of packages that provide functionality to `Mongo.Collection`. I recently wrote a [package](https://github.com/rclai/meteor-collection-extensions) and have been getting package authors to depend on it to centralize the monkey patch that most package authors do to insert their custom functionality. If you guys are able to natively support something similar or better than what I'm doing, that would be great.

Something in the line of `Mongo.Collection.extend(function (name, options) { /* where 'this' is the collection instance */})` that not only run on instantiation but also possibly run on demand for collection instances that may have been instantiated prior to creating the extension.

**Comment by msavin** [comment]
The people have spoken!

**Comment by rclai** [comment]
Lol @msavin I saw you delete that message.

**Comment by msavin** [comment]
Haha I'll repost:

The people have spoken!

**Comment by krawalli** [comment]
+1
Collection.initialized hook

...and for all the default elements. It would be much easier to extend meteor basic functionality.

I like that idea - could be mine :)

**Comment by JackAdams** [comment]
+1 This really would solve a lot of problems regarding the interplay between packages that do deep Meteor magic.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mizzao** [comment]
Loading packages like collection-hooks and collection2 are just monkey patch on monkey patch :)

**Comment by Kestanous** [comment]
:+1:

**Comment by msavin** [comment]
Would be really nice for Meteor 1.2.0 :D this is becoming increasingly used

**Comment by jagi** [comment]
It would be great to have such hooks/events system. I wrote about it [here](https://github.com/meteor/meteor/issues/395#issuecomment-122974050). I would improve this idea a little bit.

What about creating a package that would be used internally in Meteor and could be used by packages authors. It could provide events [mixins](https://github.com/jagi/meteor-astronomy/blob/master/lib/core/events.js). It could have two sets of events reactive and nonreactive, depending on the use case.

**Comment by grsabreu** [comment]
+1
That would be great.

**Comment by mizzao** [comment]
While we're at it, why not consider support for hooking all collection operations (#395), which would significantly reduce the amount of monkey-patching and corresponding performance hit incurred by packages such as [collection-hooks](https://atmospherejs.com/matb33/collection-hooks) and [collection2](https://atmospherejs.com/aldeed/collection2).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Hook%20support%20for%20Collections%20initialization&body=Migrated%20from:%20meteor/meteor%233827) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
