### ISSUE TITLE
Package dependencies not being installed

### ISSUE THREAD

**Issue by jshimko** [meteor/meteor#3829]
I'm seeing a huge package dependency resolution issue right now.  If I add a package that has dependencies that are not currently in my project, the terminal says it installed those dependencies, but they're not actually getting installed.  A `meteor list` also shows that they aren't there.

For example, create a new project and do something like `meteor add aldeed:autoform-select2` .  You should see the expected behavior in the cli tool:
```
$ meteor add aldeed:autoform-select2

Changes to your project's package version selections:

aldeed:autoform          added, version 4.0.0
aldeed:autoform-select2  added, version 1.0.4
aldeed:simple-schema     added, version 1.1.0
mrt:moment               added, version 2.6.0
```
But then try to use Autoform or Simple Schema.  No dice.
```
ReferenceError: SimpleSchema is not defined
```
I also get the same results when adding the package directly to `.meteor/packages`.  

Another interesting note is when I explicitly remove that same package (via command or editing the packages file), the terminal tells me it removed all of those dependencies too.

```
$ meteor remove aldeed:autoform-select2

Changes to your project's package version selections:

aldeed:autoform          removed from your project
aldeed:autoform-select2  removed from your project
aldeed:simple-schema     removed from your project
mrt:moment               removed from your project
```

I've tested this with a variety of packages and can consistently reproduce it.  Can anyone else confirm they're seeing this issue?  Am I missing something here?

**Comment by PeppeL-G** [comment]
It's expected behavior. In your application you can only use exported variables from packages you have explicitly added with `meteor add`. So run `meteor add aldeed:simple-schema` if you want to use `SimpleSchema` in your application.

**Comment by jshimko** [comment]
Copy that.  Thanks for the reply.

**Comment by glasser** [comment]
Thanks @PeppeL-G !
