### ISSUE TITLE
Can't specify specific dependency

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#3830]
I had to do a hotfix yesterday, in the process Meteor upgraded one of my packages (sergeyt:typeahead@0.10.5_9 to 0.10.5_12) I didn't think much of it and pushed it along, however it broke some functionality in my app. So here I am today trying to rollback and Meteor won't let me. I did a remove and ```meteor add sergeyt:typeahead@0.10.5_9``` and this is what I get back:                                              
```
Changes to your project's package version selections:
                                              
sergeyt:typeahead  added, version 0.10.5_12   

                                              
sergeyt:typeahead: Autocomplete package for meteor powered by twitter typeahead.js
```

I've checked all my packages and nothing that I can see is making reference typeahead at all and the only other thing I changed in the hotfix commit was a couple of templates.

**Comment by glasser** [comment]
If you want to specify a specific version, use `meteor add sergeyt@=0.10.5_9`.  This means "exactly this version" whereas `@` means "compatible with this version".

That said, @dgreensp is working on an exciting rewrite of Version Solver that makes it easier to express exactly the heuristics that we want.
