### ISSUE TITLE
meteor build is slow. Execute builds on ios/android on parallell

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#3832]
Would be great if `android`/`ios` builds would run in parallel when you do `meteor build ios-device android-device` so would reduce the build time considerably

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
This feature request hasn't gained any interest in almost 2 years. As part of the on-going old issue cleanup process, I'll close it off. Happy to re-open if anyone feels otherwise. Thanks for submitting this originally!
