### ISSUE TITLE
Extend oAuth options

### ISSUE THREAD

**Issue by mariorodriguespt** [meteor/meteor#3834]
I've this use case: I want to subscribe a user a specific options at the Signup. If I use `Accounts.createUser` I cans simply extend the dictionary but If use `Meteor.loginWith<Service>`, what I get in the server is only information provided by the `<Service>`.

The best I can do is provide a callback that calls a Method to subscribe to the desired option, although there's is row for a timed attack and it's not an elegant solution at all. I would like to fix this.

Is this pull requestable?

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on StackOverflow or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

But maybe [Accounts.onCreateUser](http://docs.meteor.com/#/full/accounts_oncreateuser) is what you're looking for?

**Comment by mariorodriguespt** [comment]
I won't say that this is the type "How can I do this". I checked the source code and it passing the oAuth response to the `Accounts.onCreateUser` and I can't pass extra arguments to it. The same applies if I try to pass arguments in the oAuthOptions settings object.

I suggest something like Meteor.loginWith<Service>( oAuthOptions, privateOptions, callback ), so that I can create an account according to a promotion, etc. If this is pull requestable, I don't mind write the code :)
