### ISSUE TITLE
Feature: Subscription buffering

### ISSUE THREAD

**Issue by logan-the-developer** [meteor/meteor#3835]
We had this idea in IRC: 

It would be nice if there were a way to load subscriptions of routes that are accessible from your template, to be loaded while you are *on* that template.

I.E. you log in, and the app renders the dashboard. (it doesn't have to wait on any subscriptions.) While you are on the dashboard, it starts loading the posts subscription, so that when it's navigated to, there's no waiting for the promise to be fulfilled. 

Perhaps there is also a way to specify what subscriptions to be dumped from miniMongo on that route.

Maybe this already exists, but I couldn't think of how to search for it.

**Comment by PeppeL-G** [comment]
This is a feature request for `iron:router`? Then post it at [the iron:router repository](https://github.com/iron-meteor/iron-router).

**Comment by eshell** [comment]
i believe https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#subscriptions is what you are looking for. I assume a few things about what you want to do, and it looks like iron-router can do any of them.

**Comment by PeppeL-G** [comment]
@eshell, no that's not what he's looking for. He wants that when a page is loaded, all the subscriptions in the pages accessible from the current page should be loaded (so when he navigates to next page, the subscriptions in it are ready from the start).

**Comment by hitchcott** [comment]
Can't you just do the following?

```
Meteor.startup ->
  Metoer.subscribe 'mySubscription'
```

**Comment by hitchcott** [comment]
You could manually subscribe them in iron-router for the `onAfterAction` of a particular route.

**Comment by glasser** [comment]
I agree with @PeppeL-G : This sounds like a feature request for `iron:router`, not Meteor core.
