### ISSUE TITLE
DDP.connect options are not documented

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#3837]
You can pass options when creating a DDP connection with DDP.connect. But currently those are not documented and I had to dig through the code. I'm not sure if this is intentional, so I open this issue.

Available options can be found here: https://github.com/meteor/meteor/blob/devel/packages/ddp/livedata_connection.js#L29-L64

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by abernix** [comment]
Moved to meteor/docs#22!

**Comment by jankapunkt** [comment]
@filipenevola I think this should be reopened, the issue remains and docs are now part of this repo again.

**Comment by Grubba27** [comment]
Hey, @zodern is there any status on this? probably will be closing this and some others by end of the month

**Comment by zodern** [comment]
The docs for the options argument of `DDP.connect`  are still missing: https://docs.meteor.com/api/connections.html#DDP-connect
