### ISSUE TITLE
Email's for login are case sensitive

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#3838]
For example, logging in with 'max@domain.com' isn't the same as 'maX@domain.com'. I work around this by turning the strings to lowercase on sign in and sign up, but ideally it would take any form of capitalization.

**Comment by LostKobrakai** [comment]
This behavior is actually the right one as the local part of an email address is technically case sensitive, even though most providers don't care about it.

**Comment by msavin** [comment]
I hear that. Maybe it should keep the emails the way the user entered them, but only validate against lower case versions. Otherwise it could lead to a bad user experience.

**Comment by mikowals** [comment]
issue #550 has long discussion on this.

**Comment by glasser** [comment]
Duplicate of #550.
