### ISSUE TITLE
Messed up file load order

### ISSUE THREAD

**Issue by fardeemmunir** [meteor/meteor#3840]
For some reason, the files in my `client/views` folder is loading first, followed by files inside the `client/lib` and at last `client/compatibility`. Isn't this suppose to be in the reverse order?

I'm on v1.0.3.1.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
