### ISSUE TITLE
debugOnly not documented for packages

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#3843]
***1 Upvote*** I don't know if this is the right place to put it - but I think its a pretty cool feature that most Meteor devs are not aware of, and should be better versed on.

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by RobertLowe** [comment]
+1 didn't know about this! :scream:

**Comment by abernix** [comment]
Thanks for this, Max.  `debugOnly`, `prodOnly` and `testOnly` are all documented [here in the newly revamped Meteor Docs](http://docs.meteor.com/api/packagejs.html)!  In the future, doc requests can go into [the new Meteor Docs repo](http://github.com/meteor/docs/). :smile:
