### ISSUE TITLE
Accounts.createUser() is not working on server

### ISSUE THREAD

**Issue by manjugit** [meteor/meteor#3844]
Hi,

I am getting the following error on executing Accounts.createUser() on server side while it works perfect on client side:

TypeError: Object #<Object> has no method 'createUser' 

As it is working fine on cleints, I have added the package accounts-password. Please let me know if I am missing something.

Thanks!
Manju

**Comment by Tarang** [comment]
You may have a collection like `Accounts = new Mongo.Collection('xx')` effectively redefining `Accounts`.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
