### ISSUE TITLE
[docs] Organizations

### ISSUE THREAD

**Issue by rgoomar** [meteor/meteor#3850]
I have not seen anything in the docs mentioning organizations and how to manage them. 

It is an important part of the package system (IMO) and should be documented so that it can more easily be utilized. 

There should probably be something in the [meteor admin](http://docs.meteor.com/#/full/meteoradmin) section, [writing packages](http://docs.meteor.com/#/full/writingpackages) because I did not see how to manage organizations. But, I did end up finding it under [meteor.com/account-settings/organizations](https://www.meteor.com/account-settings/organizations)

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by rgoomar** [comment]
@glasser Where would you find it appropriate to write up a section on how to use Meteor organizations? Would it be it's own section under "Writing Packages"?

**Comment by glasser** [comment]
Organizations are documented to some degree along with the rest of the Meteor Developer Accounts service at https://www.meteor.com/services/developer-accounts

**Comment by rgoomar** [comment]
Ah I see. That should also be included in the docs, but expanded upon. Would you agree? And if so, where in the docs do you see it appropriate to include?

**Comment by rgoomar** [comment]
I just want to know so I know where to put it for the PR I want to make. :-)

**Comment by hwillson** [comment]
I've moved this over to meteor/guide#596 - closing here. Thanks!
