### ISSUE TITLE
Meteor dev login not working

### ISSUE THREAD

**Issue by andrerfneves** [meteor/meteor#3851]
I have added the meteor-developer-accounts and Js'ed:

```js
Meteor.startup(function() {
  ServiceConfiguration.configurations.remove({service: 'meteor-developer'});
  ServiceConfiguration.configurations.insert({
    service: 'meteor-developer',
    clientId: Meteor.settings.meteorDeveloper.clientId,
    secret: Meteor.settings.meteorDeveloper.secret
  });
});
```

I run meteor --settings setting-.json where I have:
```js
{
  "meteorDeveloper" : {
    "clientId" : "MY_APP_ID_ON_METEOR_DEV",
    "secret" : "MY_APP_SECRET_ON_METEOR_DEV"
  }
}
```

I set up the Redirect URI to http://127.0.0.1:3000/_oauth/ but when I try to log in, it gives me " Something went wrong: Invalid redirect URI [400] ".

What am I doing wrong fellow meteor enthusiasts?

Cheers!

**Comment by glasser** [comment]
The correct redirect URL is  http://localhost:3000/_oauth/meteor-developer

If you'd used the configuration wizard (running your app when there's no configuration set up and clicking the configuration button which `{{> loginButtons}}` presents you), it would have told you that URL.

But it's perfectly fine to not use the wizard, and our docs should tell you what redirect URL to use if you're updating ServiceConfiguration manually.

**Comment by glasser** [comment]
(This applies to any OAuth provider and is not specific to Meteor Developer Accounts.)

**Comment by andrerfneves** [comment]
Got it! I'll give it a try. Thanks for the help @glasser
