### ISSUE TITLE
How can DDP_DEFAULT_CONNECTION_URL be set

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#3852]
I am trying to create a client app that connects to an existing Meteor application to solve the problem with different assets for desktop and mobile. My initial attempt was something like the following function being called before I make any subscriptions on the client. It completely integrates with the remote Meteor site, users and all, and works
```
  Meteor.setConnection = function(url) {
    //
    //
    // Accounts._enableAutoLogin();
    this.connection = DDP.connect(url);
    Accounts.connection = this.connection;
    //
    // this is copied from https://github.com/meteor/meteor/blob/devel/packages/ddp/client_convenience.js#L52-L56
    // it makes sure all method calls are done with the correct connection
    //
    _.each(['subscribe', 'methods', 'call', 'apply', 'status', 'reconnect',                                         // 52
            'disconnect'],                                                                                          // 53
           function (name) {                                                                                        // 54
             Meteor[name] = _.bind(Meteor.connection[name], Meteor.connection);                                     // 55
           });                                                                                                      // 56
    //
    // we need re-declare the users collection so Meteor knows to use the remote one
    //
    this.users = new Meteor.Collection('users');
    //
    // now that we have our act together, try to re-login
    // unfortunately Accounts seems to have already run before
    // we did the Meteor.connection = DDP.connect part, so we manually
    // need to re-check the loginToken or hot code pushes log us out every time
    //
    var token = Accounts._storedLoginToken();
    if(token)
    {
      this.loginWithToken(token, function(err){
        // this is going to throw error if we logged out
        if(err) console.log(err);else console.log('loginWithToken');
      });
    }
  }
```
After looking through the source some more, it seems the best way to accomplish this would be if the server sent the bootstrap code to the client containing 

    __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL

which is being checked in https://github.com/meteor/meteor/blob/devel/packages/ddp/client_convenience.js#L25

But when I try to start the server with this env variable set to the desired value, the client bootstrap goes into an infinite loop.

Is this not intended (I think that is how Cordova works), or a bug?

**Comment by andrewreedy** [comment]
@jamgold The best way to accomplish connecting a mobile client to a server is by using the built in `--mobile-server` flag. Just pass the URL such as `--mobile-server website.com:8000`.

A side note: I have seen this infinite autoupdate loop when setting a `__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL` as well. I ended up having to remove the autoupdate package and then it works fine.

**Comment by Slava** [comment]
Keep in mind that your Meteor server should also have this variable set to the exact same destination (if it is different from your server's `ROOT_URL` env variable). Otherwise you risk to get a corrupted version from the first hot-code push pointed to the wrong server.

**Comment by crapthings** [comment]
How to pass url correctly?

    --server=http://website.com:8000

    --server website.com:8000

    --mobile-server=http://website.com:8000

    --mobile-server website.com:8000

**Comment by Slava** [comment]
@crapthings the cli documentation has all the information you asked for with examples:

```
meteor help run
meteor help build
```

**Comment by jamgold** [comment]
@andrewreedy sorry, but starting the app with --mobile-server does not work. It does not connect to the remote site and __meteor_runtime_config__ does not show DDP_DEFAULT_CONNECTION_URL

**Comment by rclai** [comment]
[Similar issue here with a workaround](https://github.com/meteor/meteor/issues/3815) to the infinite reload cycle of death.

**Comment by andrewreedy** [comment]
@jamgold I'm not sure what your setup is like but here is how I develop with two separate clients while still maintaining code reuse.

Directory Structure
* `appname`
  * `web`
    * `client` - Web based client 
    * `server` - Server code which works with web and mobile client
    * `lib` - Lib code which which works with web and mobile client
  * `mobile`
    * `client` - Cordova specific client
    * `server` - Symlink of `../web/server`
    * `lib` - Symlink of `../web/lib`

With this directory structure it allows me to share server and lib code between both clients for development and building. While running the app I can just spin up `meteor run ios-device` for general dev or `meteor run ios-device --mobile-server=https://example.com:443` if I want to test connecting to my production server. When I actually go to build my mobile application, I use `meteor build --server=https://example.com:443` which points to my production web-client's server.

**Comment by jamgold** [comment]
@andrewreedy that is what my current app looks like, but I want to separate mobile from desktop, which is why I am using DDP.connect. I don't want the desktop code to be sent to the mobile app. As I said in the original issue description, DDP.connect works great, but I am wondering if there is a way to make it work easier with DDP_DEFAULT_CONNECTION_URL.

When I start my mobile web app with ```meteor run --mobile-server=http://production.url``` it does not work (not running cordova yet)

**Comment by andrewreedy** [comment]
@jamgold In my example the desktop code is not sent to the mobile app. Web and mobile are two distinct Meteor applications just sharing code. The mobile app runs off of the web apps server.

**Comment by jamgold** [comment]
@andrewreedy I did not notice the symlink part, it makes a bit more sense now. Nevertheless, I can not make those options work for a simple app connecting to a remote server. As the subject states, I am interested in DDP_DEFAULT_CONNECTION_URL and how it is supposed to work.

**Comment by jamgold** [comment]
My above solution only works in certain cases; as soon as packages are involved (eg. benjaminrh:event-hooks, useraccounts and probably more) parts of the system/connection are initialized before I can ever call my Meteor.setConnection and thus half the remote methods do not exist ... there is just too much going on in the bootstrapping of meteor.

Also, it took me a while to figure out the [Meteor.startup on the client is called after the DOM is ready](http://docs.meteor.com/#/full/meteor_startup) and not when the client starts. It would be nice to have a hook that really runs at the start of the app on the client, or at least earlier than the DOM

It would be nice if there was a way to unequivocally tell an app and all its packages to connect to a remote server instead of the server the code is coming from so I wouldn't need my hack ...

**Comment by jamgold** [comment]
After a full nights sleep I was going back to reading the source and remembered setting the DDP_DEFAULT_CONNECTION_URL won't work because of hot code pushes and the confusion it causes (the issue @rclai linked to).

Reading the QA.md in in autoupdate I found the solution for my problem:

Start the mobile version with

```DDP_DEFAULT_CONNECTION_URL=<url to production site> meteor run ```

and make sure to remove autoupdate package (copied from autoupdate/QA.md)

```
meteor remove meteor-platform
meteor add meteor webapp logging tracker session ddp
meteor add mongo templating handlebars check underscore
meteor add jquery random ejson autoupdate spacebars
```

now my mobile version code patterns look exactly like as if the app was developed the usual way, I don't have to fiddle with DDP.connect and Accounts works as desired (login, registration, etc)

**Comment by jamgold** [comment]
Oh no, after doing this, Cordova apps stop working. Easy test is to remove meteor-platform form like above from leaderboard example, and the app will only show a white screen

**Comment by zeroasterisk** [comment]
Ha! @jamgold you got me excited for a minute there... 

As of now, I don't know of a means of making a *Cordova* app connect to a *Web* aside from the `DDP.connect()` method.  

Anything else seems to break `autoupdate` - which is a very important/nice feature of Meteor+Cordova.

Let me know what you come up with.

FWIW - I am ok with `DDP.connect()` -- but what I want is integration with Accounts & `Meteor.userId()` & all the built-in Meteor security... So far that seems less than obvious.

**Comment by rclai** [comment]
Have you guys tried modifying the `autoupdate` package locally to use the correct DDP endpoint for Cordova like I mentioned?

**Comment by jamgold** [comment]
@rclai that will be my next attempt

**Comment by jamgold** [comment]
I gave up on modifying ```autoupdate``` or any other hack, including my ```Meteor.setConnection``` from this issue. I just couldn't get it to work with Cordova, which still is a bunch of black magic to me (though the fog is slowly lifting).

I replaced it by ```DDP.connect```ing to the remote server and using the resulting connection handle for all my ```Meteor.subscribe```, new ```Meteor.Connection``` and ```Meteor.call``` occurrences.

The only tricky thing was Accounts, which I handled the old, hacky way

```
Meteor.remoteConnection = DDP.connect( <remote url> );
Accounts.connection = Meteor.remoteConnection;
Meteor.users = new Meteor.Collection('users',{connection: Meteor.remoteConnection});
// now instantiate my collections and subscriptions 
Collection = new Meteor.Collection('collection,{connection: Meteor.remoteConnection});
Meteor.remoteConnection.subscribe('collection');
```
etc.

**Comment by zeroasterisk** [comment]
Yup - I'm with you so far on the `DDP --> accounts` 

I have a couple of questions, for you, with that setup:

1. how do you "login" from the client?  is it "just like normal", because Accounts/Users are now backended onto the DDP remote?
2. on the client, does `Meteor.userId()` now work, again, because you updated Accounts?
3. on the remote DDP connection target, on the server, does it "know" authenticated users via `Meteor.userId()` for both `subscribe` and `call`?

Honestly, if the answer to all of that is "yes", then this is probably *enough* for me, and perhaps the best possible situation... I agree it's a little "hacky" and to use subscribes, you have to subscribe to the `remoteConnection` object instead of `Meteor`... but really, I don't think that's a huge problem...

**Comment by jamgold** [comment]
@zeroasterisk login from the client is __just like normal__ and I have access to Meteor.user and {{currentUser}} in my Templates. The remote has userId in in Methods as well. 

I should say that currently I only have accounts-password working, because I haven't found a solution for OAuth2 (G+) for Cordova yet and haven't had time to fiddle with the Facebook Cordova plugin.

Other than that the answer seems a resounding __yes__ and I have been pounding away at my Cordova ionic ever since I was able to make this work.

**Comment by zeroasterisk** [comment]
Thanks so much - this is what I was trying to get working, but I didn't have the right pattern to wire directly into `Accounts` and `Users` --- thanks for the *special sauce*!

**Comment by gwendall** [comment]
Struggled with the same problem so I created this package. Any help on the oauth front would be appreciated! https://github.com/gwendall/meteor-remote-ddp

**Comment by jamgold** [comment]
@gwendall how are you dealing with code autoupdat/reload ?

**Comment by gwendall** [comment]
Works just fine. Autoupdate relies on a subscription (https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_client.js#L62) that is not affected by the package (since you need to call from RemoteDDP function from outside packages, hence after the autoupdate package gets loaded).

**Comment by gwendall** [comment]
Tracking down the Oauth error, seems like it's coming from the accounts-base package that returns a "No matching login attempt found" when calling the login method on Accounts.connection. (https://github.com/meteor/meteor/blob/0e3c992fd8f178efd9e832038257ae36cec90351/packages/accounts-base/accounts_client.js#L214)

**Comment by jamgold** [comment]
@gwendall since this is the verbatim code I posted, I can tell you from experience it does not work with Cordova

**Comment by gwendall** [comment]
@jamgold Indeed. Also wondering how to best structure that. I think the best solution is to just:
1. point your mobile app to the server holding your app logic / data, etc. with --mobile-server (and still get Accounts, etc working out of the box)
2. patch autoupdate to get it point to the server hosting your mobile front-end code as mentioned by @rclai (so that you can still benefit from hot code pushes)
@rclai, does everything work fine with your patch?

**Comment by rclai** [comment]
@gwendall wow sorry for not getting back at you but yes, it works but I've only used it for browser apps but haven't tested modeling the Cordova auto update code.

**Comment by rclai** [comment]
@gwendall @jamgold @andrewreedy Guys, I created a [demo repo](https://github.com/rclai/meteor-app-with-remote-server) showing how to I got it to work both for web and mobile apps.

**Comment by jamgold** [comment]
Thank you @rclai, I will check it out

**Comment by iGroza** [comment]
Hi, try use the [DDP backend package](https://atmospherejs.com/xneon/ddp-backend). Just install and setup BACKEND_URL env
