### ISSUE TITLE
Spiderable, Server Route returning file, Fiber error

### ISSUE THREAD

**Issue by MichaelErmer** [meteor/meteor#3853]
i have a route that is only run on the server it retrieves an image from hdfs and streams it to the response object. It works fine for display in browser, also spiderable works fine for any other url of the page.

But when facebook is trying to retrieve that thumbnail by calling http://siteurl/thumb/3g3g4353g/thumb.jpg?_escaped_fragment_= the following error happens:

the Route:
````
Router.route('/thumb/:i/:_id',  thumbRoute, {where: 'server'});
````

The Result:
````
I20150303-00:52:59.902(1)? uri thumb request
I20150303-00:53:00.681(1)? hdfs result object
I20150303-00:53:13.391(1)? spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
I20150303-00:53:13.391(1)? stderr: 
W20150303-00:53:13.395(1)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150303-00:53:13.408(1)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150303-00:53:13.409(1)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20150303-00:53:13.409(1)? (STDERR)     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
W20150303-00:53:13.409(1)? (STDERR)     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
W20150303-00:53:13.410(1)? (STDERR)     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
W20150303-00:53:13.410(1)? (STDERR)     at Function.Route.createController (packages/iron:router/lib/route.js:133:1)
W20150303-00:53:13.410(1)? (STDERR)     at Function.Router.createController (packages/iron:router/lib/router.js:198:1)
W20150303-00:53:13.411(1)? (STDERR)     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
W20150303-00:53:13.411(1)? (STDERR)     at Object.router (packages/iron:router/lib/router.js:15:1)
W20150303-00:53:13.412(1)? (STDERR)     at next (/root/.meteor/packages/webapp/.1.1.6.1qtkey2++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)

**Comment by glasser** [comment]
Server routes are a part of the [`iron:router`](https://github.com/iron-meteor/iron-router) project, not Meteor core.  I suggest you file the issue at their repository.  If it turns out to be an issue with Meteor core, please follow a new issue here following our guidelines: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by MichaelErmer** [comment]
Its an issue with core in my opinion, there needs to be a check in spiderable if the reponse of the phantomrequest is content typ text/html to continue, else it should just proxy the response. This could 
 be achieved my a HEAD request in spiderable before the phanton stuff.

There is nothing iron router can do about it.

I've been searching for similar issue/bug reports for some hours now, so I created a workaround that can just skips spiderable if url contains a specific string, maybe this will be helpful for some:
https://github.com/MichaelErmer/spiderable-ssl/commit/63131d9628a9770f6df65b13978e973d32f8f8a3

**Comment by glasser** [comment]
Please follow the directions in the link I provided which explains how to demonstrate a bug in a reproducible manner.

**Comment by dr-dimitru** [comment]
BTW is someone got into this issue again, we have [spiderable fork](https://github.com/jazeee/jazeee-meteor-spiderable#ignoredroutes-string) with work around it
