### ISSUE TITLE
Error: Did not check() all arguments during call to 'login'

### ISSUE THREAD

**Issue by Hellyna** [meteor/meteor#3855]
Suppose we have an external DDP client that identifies itself to the server with the extra parameter `{ identifier: <uuid>}`. The original DDP call to the server method `login` should look like this:

```javascript
var ddp = DDP.connect('localhost:3000');
ddp.call({
  user: {username: <username>},
  password: {digest: <password_hash>, algorithm: 'sha-256'}
});
```

So we wanted to pass another extra parameter as mentioned above. The command now looks like this:

```javascript
var ddp = DDP.connect('localhost:3000');
ddp.call({
  user: {username: <username>},
  password: {digest: <password_hash>, algorithm: 'sha-256'}
}, {identifier: <uuid>});
```

We can access the extra parameter from within `Accounts.validateLoginAttempt({...})`. However, we noticed that the Meteor `audit-argument-checks` package does not allow the adding of one extra parameter, on which the above error mentioned in the title will occur. Apparently trying to check parameters in the validateLoginAttempt callback does not work as well. Scouring the `accounts-base` package it is evident that the following line is causing the problem:

```javascript
  // @returns {Object|null}
  //   If successful, returns {token: reconnectToken, id: userId}
  //   If unsuccessful (for example, if the user closed the oauth login popup),
  //     throws an error describing the reason
  login: function(options) {
    var self = this;

    // Login handlers should really also check whatever field they look at in
    // options, but we don't enforce it.
    // LINE BELOW TRIGGERS THE ERROR!
    check(options, Object);

    var result = runLoginHandlers(self, options);

    return attemptLogin(self, "login", arguments, result);
  },
```
Therefore I wish to enquire if there is a workaround other than fully implementing another loginHandler from scratch as described in https://meteorhacks.com/extending-meteor-accounts.html.

Thanks in advance.

**Comment by Hellyna** [comment]
Also, do note that if I DDP call instead including `identifier` in the object in the first argument, I will get the following error instead.
```javascript
var ddp = DDP.connect('localhost:3000');
ddp.call({
  user: {username: <username>},
  password: {digest: <password_hash>, algorithm: 'sha-256'}
  identifier: <uuid>
});
```
```
I20150303-17:59:19.744(8)? Exception while invoking method 'login' Error: Match error: Unknown key in field machineId
I20150303-17:59:19.744(8)?     at packages/check/match.js:299:1
I20150303-17:59:19.744(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20150303-17:59:19.744(8)?     at checkSubtree (packages/check/match.js:290:1)
I20150303-17:59:19.745(8)?     at check (packages/check/match.js:32:1)
I20150303-17:59:19.745(8)?     at [object Object].Accounts.registerLoginHandler.check.user (packages/accounts-password/password_server.js:144:1)
I20150303-17:59:19.745(8)?     at packages/accounts-base/accounts_server.js:383:1
I20150303-17:59:19.745(8)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:186:1)
I20150303-17:59:19.745(8)?     at runLoginHandlers (packages/accounts-base/accounts_server.js:380:1)
I20150303-17:59:19.745(8)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:434:1)
I20150303-17:59:19.745(8)?     at packages/check/match.js:109:1
I20150303-17:59:19.745(8)? Sanitized and reported to the client as: Match failed [400]
```

**Comment by glasser** [comment]
It sounds like you're trying to add features to `accounts-password` where there isn't an extension mechanism provided.

The signature of `login` is that it takes one argument; if you try to pass more arguments to it, that's not valid.  It's designed to be extended by allowing multiple login handlers to try to process the single argument.

It's annoying that validateLoginAttempt hooks can't use `check` to qualify for `audit-argument-checks`; that's because we always clone the arguments before we pass them to the hook (see `cloneAttemptWithConnection`). That's because we don't want hook callbacks to be able to mutate the current connection argument state!

I feel like what you are trying to do is probably best accomplished via a fork of `accounts-password`, or by identifying an extension point for `accounts-password` that allows you to accomplish what you want.
