### ISSUE TITLE
Packaging meteor for Arch Linux

### ISSUE THREAD

**Issue by xyproto** [meteor/meteor#3856]
Hi,

This is a support request.

I wish to package meteor for Arch Linux. Normally, programs offer a way to install the package for the user (something like: ./configure; make; make install) and in a system-wide fashion (something like: ./configure --prefix=/usr; make; DESTDIR="$pkgdir" make install).

`curl https://install.meteor.com/ | sh` works well as a user, but how do you install meteor in a system-wide fashion, so that it can be packaged as an official package for a Linux distro?

Best regards,
   Alexander F Rødseth

**Comment by glasser** [comment]
We don't support distributionized Meteor installs.  It's important to us that users be able to have multiple Meteor releases installed at once to use on different apps simultaneously, and most distribution systems don't support that.

Allowing some sort of `$PREFIX` to the install script would be nice, but there are some tricky bits I mentioned at https://github.com/meteor/meteor/issues/2268#issuecomment-49490715

That said, the install script does very little anyway; it basically just downloads and expands the "bootstrap tarball".  If you're going to be doing something that we don't officially support anyway, you can just make downloading the tarball be what your repackaging does.  In the current system, you can find the base URL of the current bootstrap tarball by fetching https://packages.meteor.com/bootstrap-link
