### ISSUE TITLE
npm update fails when removing a dependency that was a (de-duped) transitive dependency of another dependency

### ISSUE THREAD

**Issue by monbro** [meteor/meteor#3857]
I have a meteor package which is using the npm package 'sentencer'. This npm package depend on the npm package 'randy'. 

Now when I add 'randy' as a Npm.requirement to my meteor package, it works fine. Until I remove it from my meteor package again, meteor will complain with the following message:

```
my-meteor-package: updating npm dependencies -- sentencer, natural, articles...
npm ERR! missing: randy@~1.5.1, required by sentencer@0.1.1
npm ERR! not ok code 0

 => Errors while adding packages:             

While building package my-meteor-package:
error: couldn't read npm version lock information
```

I assume the npm package randy is then completely removed in my meteor package so that the npm package 'sentencer' is not able to use it anymore.

**Comment by monbro** [comment]
I can solve this by deleting the `.npm` folder in my meteor package.

**Comment by glasser** [comment]
In general it's easier to help with reported bugs if they contain a full reproduction as described in https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

Will try to look into this at some point, but a reproduction will help.

**Comment by glasser** [comment]
OK, reproduction:

```
glasser@perseid 0 /tmp $ git clone https://github.com/glasser/meteor-issue-3857.git
Cloning into 'meteor-issue-3857'...
remote: Counting objects: 44, done.        
remote: Compressing objects: 100% (22/22), done.        
remote: Total 44 (delta 10), reused 44 (delta 10), pack-reused 0        
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.
glasser@perseid 0 /tmp $ cd meteor-issue-3857/
glasser@perseid 0 /tmp/meteor-issue-3857 master u= $ meteor --version
Meteor 1.0.3.2
glasser@perseid 0 /tmp/meteor-issue-3857 master u= $ meteor --prepare-app
use-npm: updating npm dependencies -- randy, sentencer...
```

Edit `packages/use-npm/package.js` and remove the `randy: "1.5.1",`.

```
glasser@perseid 0 /tmp/meteor-issue-3857 master u= $ meteor --prepare-app
use-npm: updating npm dependencies -- sentencer...
npm ERR! missing: randy@~1.5.1, required by sentencer@0.1.1
npm ERR! not ok code 0

=> Errors while initializing project:

While building package use-npm:
error: couldn't read npm version lock information
```

**Comment by glasser** [comment]
I do believe that a workaround, as you mentioned, is to delete the `.npm` directory and let Meteor recreate it (which will lose sub-version pinning information).

**Comment by monbro** [comment]
Yes, thats the failure. Ok, thanks for creating the reproduction.

**Comment by hwillson** [comment]
This is no longer an issue with recent versions of Meteor (tested and verified working with Meteor 1.4.2.3). Thanks!
