### ISSUE TITLE
"Hidden" docs about Blaze and Spacebars

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3858]
http://stackoverflow.com/questions/28843646/return-array-value-in-a-meteor-spacebars-template

We should make it easy to discover the docs about blaze and spacebars.

**Comment by hwillson** [comment]
Hi @stubailo - I might be able to help out with this one. What are you thinking in terms of discoverability? My guess is a large portion of users are hitting the docs.meteor.com content first and foremost, before branching off to github, atmosphere, etc. (especially new users). The blaze and spacebars package README's have quite a bit of good content, so what if we updated the full API http://docs.meteor.com package table of contents to include links to the blaze and spacebars atmosphere projects? This would be very similar to the spiderable package link (which https://github.com/meteor/meteor/commit/104636c6a7b7b88aafc4837bdd65b4d7490ee148 made possible). 

After this is in place, we could then figure out how to expose the blaze wiki content referenced in the SO answer. At a very minimum we could just add a link to this content from the blaze package README. In the future though given that the wiki content is out of date it would probably be a better idea to extract the good parts and merge them into the README.

Regardless, let me know what you would like to see and I'll see what I can do. Thanks!

**Comment by stubailo** [comment]
Yeah, that sounds like a great start! We should add Spacebars to the table of contents somewhere under Templates. I welcome any improvements to the docs that make it easier to discover information.

**Comment by hwillson** [comment]
Hi guys - I've added a few minor changes in #3919. Regarding the original issue reported on SO (hidden mention of dotted helpers with numeric indices on the wiki), I'll open a separate PR for  https://github.com/meteor/meteor/tree/devel/packages/spacebars with modified README text that should help. Thanks!

**Comment by stubailo** [comment]
@hwillson Your PR was a great start, but I'm going to leave this issue open until we can figure out some even solution that involves the docs being more integrated.

**Comment by hwillson** [comment]
Thanks @stubailo, I agree - things are a bit all over the place right now.

**Comment by hwillson** [comment]
Blaze (including spacebars) now has its own documentation site at http://blazejs.org, so closing this off. Thanks!
