### ISSUE TITLE
Accounts API: Users can Squat on Email Addresses and Prevent Legitimate Signup

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#3861]
I'm using the Accounts API in my Meteor app to handle user signups, logins, forgotten passwords, etc., which requires a user's email address and password combination for authentication (username omitted).

I noticed that if someone enters your email address into the signup forms, a new document gets stored in Mongo with your address. If you then legitimately decide to signup using your address, the system will block you ("Email already exists") because of the old bogus registration.

Meteor shouldn't just look for existing emails, but should check to see if the verified flag is set to true. If the email has already been verified, that proves ownership and Meteor should block the new registration. But if the email hasn't yet been verified, it shouldn't block registration. If need be, the unverified account should be removed.

**Comment by stubailo** [comment]
The user who actually owns that email address can always use the "reset password" function to take control of the offending account, so it doesn't seem that bad to me?

**Comment by joncursi** [comment]
@stubailo That does sound like a plausible workaround, which is good. But I'm still concerned about the UX. Low priority, but something I wanted to bring to MDG's attention.

**Comment by zimme** [comment]
One thing you can do is to just send another "verify account email" if the email already exists on signup.

**Comment by hwillson** [comment]
Given that there is a workaround to this (https://github.com/meteor/meteor/issues/3861#issuecomment-77102639) and that this issue has had very little activity/traction in > 1.5 years, as part of the on-going old issue cleanup process, I'll close it off. Thanks for opening this originally!
