### ISSUE TITLE
Error occurred when using HTTP.get on the client

### ISSUE THREAD

**Issue by Hopewp** [meteor/meteor#3862]
Error:
WebSocket is already in CLOSING or CLOSED state.ddp.js:1361 WebSocketTransport.doSendddp.js:1291 SockJS.sendddp.js:2593 _.extend.sendddp.js:4417 _.extend._sendddp.js:3709 onMessageddp.js:2717 (anonymous function)underscore.js:156 _.each._.forEachddp.js:2716 _.extend._launchConnection.self.socket.onmessageddp.js:156 REventTarget.dispatchEventddp.js:1141 SockJS._dispatchMessageddp.js:1199 SockJS._didMessageddp.js:1346 SockJS.websocket.that.ws.onmessage

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
