### ISSUE TITLE
Meteor run ios/android not working anymore

### ISSUE THREAD

**Issue by jeangui** [meteor/meteor#3863]
Hello,

I post the problem first in the forums.meteor.com.

https://forums.meteor.com/t/problem-with-meteor-run-ios/738

But I am getting not so much help.

My meteor installation with XCode was working up to some days ago (I don't remember what I upgraded).

I have tried to uninstall everything (XCode, Meteor), remove all the .meteor files and change file ownership and acl (chown + chmod 777).

I have tried to reinstall everything and create a new meteor application (sample todos) and run again the command for getting the ios simulator.

But I am getting always the same error:

https://gist.github.com/jeangui/3732f838da614b4b98ec

OSX: 10.9.5
XCode: Version 6.1.1 (6A2008a)
Meteor: 1.0.3.2
Cordova: 4.3.0

I have tried for android as well, and it is not working either:

https://gist.github.com/jeangui/7bbfae39299d96e72962

what should I do ?

Thanks in advance for the help.

Best Regards,

**Comment by Slava** [comment]
@jeangui hi, looking at your logs, I can't figure out where is your main meteor project located?

**Comment by jeangui** [comment]
Hello Slava,

Sorry for not having updating this issue status...
Finally after 5 days of search (uninstall xcode, cordova, meteor & delete files ... several times) I found out that there was a small config.xml file in my $HOME folder.
When I deleted it, everything went ok again.

Thanks a lot for your help.

Best regards.
@jeangui

**Comment by Slava** [comment]
This is interesting. I would never guess that Cordova finds this file in your home dir. Glad you solved your issue.
