### ISSUE TITLE
Collaborating across platforms using Dropbox is not easy

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3864]
@Slava

**Comment by gadicc** [comment]
Not sure of the exact issues and don't use this myself, but did recall the following doc which I'll link for reference: http://meteorpedia.com/read/Dropbox.  The main line is:

```bash
$ dropbox exclude add .meteor/local .git .build packages
```

which should prevent platform-specific build data from being shared.

**Comment by stubailo** [comment]
You don't need to add the `packages` directory anymore unless you're still using Meteorite, since the packages for the new package system aren't stored there anymore.

**Comment by abernix** [comment]
I'm going to close this and leave it as a historical issue for those who are collaborating across platforms using Dropbox.  I think the above recommendation to exclude it sounds pretty reasonable if you find yourself in that situation. 🙊
