### ISSUE TITLE
onLogout callback on the server side

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3867]
***1 Upvote*** It would be great to have an onLogout callback on the server side. This would allow one to cleanup and react to login changes. Useful for SSO and special things associated with logged in state.

Probably a client side part would be useful as well, but you can get that in a way with the reactive `Meteor.userId()`.

**Comment by peterchoo** [comment]
This.  It would be incredibly useful.

I have a package which manages some per session data internally.  If the user refreshes, this data is no longer accessible, as it is restricted by sessionId.  But if the user logs out (in this case triggered from another package) I have no way of clearing my data.

**Comment by sbrych** [comment]
+1

**Comment by mitar** [comment]
The current workaround we are using is creating an empty publish on the server side to which client subscribes. And then that empty publish is keeping the local collection populated with information:

Server side:

```
sessions = new Mongo.Collection null

Meteor.onConnection (connection) ->
  id = share.sessions.insert
    _id: connection.id
    userId: null
  connection.onClose ->
    share.sessions.remove id

Meteor.publish 'sessionDummy', ->
  share.sessions.update @connection.id, $set:
    userId: @userId
  # Don't actually publish anything.
  []
```

Client:

```
Meteor.subscribe 'sessionDummy'
```

**Comment by stubailo** [comment]
Is this use case not covered by the user status package? https://github.com/mizzao/meteor-user-status

**Comment by mitar** [comment]
Yes, it has to use the same ugly trick with dummy empty subscription as I described above: https://github.com/mizzao/meteor-user-status/blob/master/status.coffee#L208

**Comment by peterchoo** [comment]
@stubailo Thanks for pointing that package out.  I'll look into using it for the time being.

I strongly feel that the accounts package should provide an onLogout hook system to mirror the onLogin hooks.  It would be extremely useful if the hooks had available to them the connection which triggered it, and the user object.

Thank you!

**Comment by stubailo** [comment]
Yep, sounds like a great idea. In general we don't have enough callbacks for all kinds of things.

**Comment by aunz** [comment]
@mitar 
connection.onClose  only works if a user closes the browser/
If the user only clicks the logout button, the onclose callback will not be called?

**Comment by mitar** [comment]
The logout you get through dummy subscription.

**Comment by jagill** [comment]
Would be very useful.

**Comment by lorensr** [comment]
@mitar On the client, after you do `Meteor.subscribe 'sessionDummy'`, how do you react to changes without a named collection to do `collection.find({}).observe` on?

**Comment by tmeasday** [comment]
Implemented in https://github.com/meteor/meteor/pull/7187
