### ISSUE TITLE
[docs] Meteor Debug is missing

### ISSUE THREAD

**Issue by rgoomar** [meteor/meteor#3868]
There is nothing in the "Command line" section of the docs about using `meteor debug` and it's a pretty new and important thing to have up there. 

It was originally pointed out here: https://forums.meteor.com/t/why-no-meteor-debug-mentioned-in-docs/861

**Comment by hwillson** [comment]
Hi guys - I've added some starter content in #3870. Thanks!

**Comment by glasser** [comment]
Thanks, @stubailo is looking at the PR!

**Comment by stubailo** [comment]
http://docs.meteor.com/#/full/meteordebug

Thanks @hwillson!
