### ISSUE TITLE
Template rendering and html attribute order

### ISSUE THREAD

**Issue by Buom01** [meteor/meteor#3869]
**_1 Upvote**_ Hi, this can be an real probleme with semantic-ui for exemple.

I have this:

> ```
>    <div class="ui {{#if smallScreen}}{{else}}three column grid{{/if}} stacked segment">
>        <div class="column">
>            <div class="ui {{#if smallScreen}}vertical{{else}}horizontal{{/if}} segment">
>                <h1 class="ui header">Gratuit</h1>
>                <p>....</p>
>            </div>
>        </div>
>        <div class="column">
>            <div class="ui {{#if smallScreen}}vertical{{else}}horizontal{{/if}} segment">
>                <h1 class="ui header">Moderne</h1>
>                <p>....</p>
>            </div>
>        </div>
>    </div>
> ```

Render is correctly on _smallScreen_ (and _largeScreen_);

> ```
>    <div class="column">
>        <div class="**ui vertical segment**">
>            <h1 class="ui header">Gratuit</h1>
>            <p></p>
>        </div>
>    </div>
> ```

But, if we resizing from _smallScreen_ to _largeScreen_ and revert, we obtain;
(Also obtain this when resize from _smallScreen_ to _largeScreen_ or  from _largeScreen_ to _smallScreen_)

> ```
>    <div class="column">
>        <div class="**ui segment vertical**">
>            <h1 class="ui header">Gratuit</h1>
>            <p></p>
>        </div>
>    </div>
> ```

The order and the display went wrong....

Normal;
![normal_largescreen](https://cloud.githubusercontent.com/assets/1537208/6514067/f2b06f00-c37f-11e4-9e25-ed6dc6d5beca.png)
![normal_smallscreen](https://cloud.githubusercontent.com/assets/1537208/6514068/f2b2d380-c37f-11e4-920a-462ffcb49a63.png)

Wrong;
![wrong_largescreen](https://cloud.githubusercontent.com/assets/1537208/6514069/f2b5f498-c37f-11e4-8f87-c9e11e6badcd.png)
![wrong_smallscreen](https://cloud.githubusercontent.com/assets/1537208/6514070/f2b98f22-c37f-11e4-87a1-c993a6debebb.png)

Sorry for my bad english.

**Comment by stubailo** [comment]
Hi @Buom01!

Thank you for the report. This is related to a larger overall issue of attribute handling in Blaze. For more details on this issue, please see this comment: https://github.com/meteor/meteor/issues/3765#issuecomment-78149378

I would love to see a pull request solving some of these attribute-related issues.

**Comment by maxnowack** [comment]
+1

**Comment by hwillson** [comment]
I've created meteor/blaze#159 to track this. This issue can be closed. Thanks!

**Comment by abernix** [comment]
👍 😄
