### ISSUE TITLE
Run Minimongo tests against MongoDB to assure future compatibility

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3872]
You should probably run Minimongo tests against MongoDB as part of your testing suite to assure compatibility in the future. Similar to how I am doing in: https://github.com/mitar/minimongo-diff

**Comment by glasser** [comment]
I agree that this would be helpful, although it is nice that minimongo tests run very fast :)

**Comment by mitar** [comment]
I really think we should be running Mongo compatibility tests for Minimongo.

Interestingly, most Minimongo tests are [currently running only on the client](https://github.com/meteor/meteor/blob/devel/packages/minimongo/package.js#L63). I have run [them on the server as an experiment](https://github.com/mitar/minimongo-diff) and found many incompatibilities (#5167, #5166, #5165, #3599).

I think we should [integrate core Mongo test](https://github.com/mongodb/mongo/tree/master/jstests/core) into Minimongo tests and run them on client and server to make sure they behave the same: to make sure Mongo continues to work across server-side MongoDB upgrades, and that the same queries work also on Minimongo.

There are probably still incompatibilities, but I think by having tests it would be then easy to create issues with pull-requests-encourages to get community to help. It seems there is quite some interest to improve Minimongo from the community.

**Comment by mitar** [comment]
cc @hwillson, can we mark this as `pull-requests-encouraged`?

**Comment by hwillson** [comment]
Yes, I agree @mitar - I think this makes a lot of sense. Anything we can do to get the differences resolved would be great! Marking as `pull-requests-encouraged` (cc @mutdmour and @mbrobbel - you guys are the most recent submitters of Minimongo PR's, so if you're interested in helping further, this would be a great next step! 🙂). Thanks!

**Comment by mitar** [comment]
I think it would be also interesting to see full-text search support in Minimongo. Maybe I should open another issue for that. :-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Run%20Minimongo%20tests%20against%20MongoDB%20to%20assure%20future%20compatibility&body=Migrated%20from:%20meteor/meteor%233872) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
