### ISSUE TITLE
Match.Optional should accept null in addition to undefined

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3876]
Checking arguments to methods becomes quite silly otherwise.

First of all, arguments that are passed in as `undefined` are converted to `null` by DDP, so you can't use `Match.Optional` in its current state to validate missing arguments in methods on the server.

Second, even if you used `Match.OneOf(null, <type>)`, it still wouldn't work because the method stub on the client actually _does_ get undefined.

Perhaps we should reconsider our code style guidelines of setting things to `null` instead of `undefined`, or modify our default tools to accept `null` as meaning "missing value".

**Comment by meonkeys** [comment]
+1

**Comment by rijk** [comment]
+1

**Comment by voidale** [comment]
+1

**Comment by panphora** [comment]
+1

**Comment by mjesuele** [comment]
This just bit me as well, and is rather unintuitive behavior. +1!!

**Comment by acemtp** [comment]
+1!!!

**Comment by Jank1310** [comment]
+1

**Comment by LewisW** [comment]
+1

**Comment by stubailo** [comment]
I would accept a pull request for a new call, `Match.Maybe`, which has the correct behaviour - accepts `undefined`, `null`, and the passed value.

Then we can deprecate `Optional`. I don't think it would be good to silently change the behavior because it could introduce undiscoverable security holes into people's apps.

If someone acts fast, we can get this into Meteor 1.3!!!

**Comment by stubailo** [comment]
Fixed this by adding `Match.Maybe`. Going to make the docs recommend that instead.

**Comment by mitar** [comment]
We developed those extensions: https://github.com/peerlibrary/meteor-check-extension

We have `Match.OptionalOrNull` to address this issue.

**Comment by lirbank** [comment]
A simple workaround, for pre 1.3, is to substitute Match.Optional(<type>) with Match.OneOf(null, undefined, <type>) - works on both client and server.

**Comment by maxenceC** [comment]
@lirbank thank you for the workaround !
