### ISSUE TITLE
Methods on the server and client get different arguments in case of undefined

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3877]
If you define a simple method on the server and the client:

```
Meteor.methods({
  myMethod: function (a, b) {
    check(a, Match.Optional(String));
    check(b, String);
  }
});
```

Then you call it like this:

```
Meteor.call("myMethod", undefined, "hello");
```

The check will fail on the server and pass on the client, because the server actually gets `null` instead of `undefined` in the first argument.

**Comment by zarvox** [comment]
I'm hitting this surprising behavior.

A somewhat-fragile workaround for users is to make the optional argument last, and then omit that argument from the Meteor.call invocation.  It works, but it's really easy to break down the line if you're not rigorous about manually counting arguments in function calls every time you change code.

**Comment by stubailo** [comment]
Yeah the current workaround I do for this is to always use `null` instead of `undefined` if possible.

**Comment by tschneid** [comment]
I'm running into this as well when using publish/subscribe (#4742). My problem here is that getting `null` does not allow for default parameters:
```js
Meteor.publish('publication', function(ids = []) {
  new SimpleSchema({ids: {type: [String]}).validate({ids});
  // ...
}
```
I was expecting this to work calling `Meteor.subscribe('publication')` without an argument. Instead, I run into validation errors and need to catch `null` as special case in every `publish` function.

**Comment by hwillson** [comment]
https://github.com/meteor/meteor/issues/3877#issuecomment-109487349 outlines why this is happening, and this is functioning as designed. If anyone is interested in seeing this work differently, please open a new issue over in http://github.com/meteor/meteor-feature-requests. Thanks!
