### ISSUE TITLE
DDP package having minimongo as a dependency

### ISSUE THREAD

**Issue by andrewreedy** [meteor/meteor#3879]
**_1 Upvote**_ It seems odd that the `ddp` package has `minimongo` as a dependency and contains Mongo specific code. Why not decouple these and have the `ddp` package be autonomous from the specific data providers?

**Comment by murillo128** [comment]
+1

maybe related with

https://github.com/meteor/meteor/issues/3638

**Comment by Slava** [comment]
I think the only reason for that is a weird fact that the `minimongo` package contains functions to diff arrays and objects. This is the same reason why `blaze` depends on `minimongo` (through `observe-sequence`). There is no a good reason for that.

**Comment by andrewreedy** [comment]
Error I get when I try and `Meteor.subscribe('xxx')`without the `mongo` package.

```
I20150307-14:12:51.192(-8)? Internal exception while processing message { msg: 'sub',
I20150307-14:12:51.193(-8)?   id: 'f5GtTJdY77MdvdsfE',
I20150307-14:12:51.193(-8)?   name: 'meteor_autoupdate_clientVersions',
I20150307-14:12:51.193(-8)?   params: [] } Mongo is not defined ReferenceError: Mongo is not defined
I20150307-14:12:51.193(-8)?     at [object Object].LocalCollection.Cursor._publishCursor (packages/minimongo/minimongo.js:247:1)
I20150307-14:12:51.193(-8)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:978:1)
I20150307-14:12:51.193(-8)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150307-14:12:51.194(-8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150307-14:12:51.194(-8)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by glasser** [comment]
Agreed that some refactorings could be done to pull the diffing and ID code out.  Though part of the issue is that `ddp` does depend on the ID stringification/parsing rules defined in LocalCollection, which include the mongo-specific-ish ObjectId type.  But maybe `object-id` should just be its own package instead of being part of `minimongo`.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=DDP%20package%20having%20minimongo%20as%20a%20dependency&body=Migrated%20from:%20meteor/meteor%233879) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
