### ISSUE TITLE
Tracker use Meteor._setImmediate instead of setTimeout 0

### ISSUE THREAD

**Issue by murillo128** [meteor/meteor#3880]
Currently setTimeout 0 is used on the invalidate to trigger the Tracker.flush, it should be better to use Meteor._setInmediate instead:

https://forums.meteor.com/t/why-use-settimeout-with-0ms-instead-of-any-setinmediate-variant-in-tracker/823/6

**Comment by murillo128** [comment]
created pull request https://github.com/meteor/meteor/pull/3889

**Comment by glasser** [comment]
Thanks, merged!
