### ISSUE TITLE
Autoupdate package with Mongo dependency 

### ISSUE THREAD

**Issue by andrewreedy** [meteor/meteor#3881]
It would be nice if the `mongo` package wasn't a requirement for a basic Meteor app and core packages such as `autoupdate`. It should at least be configurable or agnostic to the data layer. I don't see why we have to have `mongo` just to do something as simple as this.

**Comment by glasser** [comment]
You're right. Mongo itself isn't used at all, but the best abstraction we have for publishing data over DDP on the server and reading it on the client is `Mongo.Collection`.  @justinsb has some plans to refactor `mongo` into pieces which maintain the useful non-mongo-specific code as its own package.  Not sure where that will fall on our [roadmap](https://roadmap.meteor.com/).

**Comment by andrewreedy** [comment]
@glasser This is what I was thinking too. Just the simplest possible abstraction for publishing data over DDP and then have the specific database packages extend that. I might play around with some ideas in the mean time but excited to see what @justinsb comes up with.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Autoupdate%20package%20with%20Mongo%20dependency%20&body=Migrated%20from:%20meteor/meteor%233881) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
