### ISSUE TITLE
node-pre-gyp fails when used in a package with : in the pathname

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3882]
Steps to [reproduce](https://github.com/mitar/meteor-issue3882), on Mac OS X:

```
git clone https://github.com/mitar/meteor-issue3882.git peerlibrary:sqlite3
cd peerlibrary:sqlite3
meteor test-packages ./
```

There will be an error:

```
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
peerlibrary:sqlite3: updating npm dependencies -- sqlite3...
sh: node-pre-gyp: command not found           

npm ERR! sqlite3@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
```

If you install `node-pre-gyp` globally (`npm -g node-pre-gyp`) it works. If you rename the package directory to something else (`meteor-sqlite3` for example), it works.

But with current Meteor packaging scheme is normal to have packages in directories with `:` inside. And then it fails.

**Comment by Slava** [comment]
With the next release (1.0.4) we are going to force people to create directories with underscores (`_`) instead of colons but put the name attribute in `package.js`. This problem will stay, but at least will become less noticeable.

**Comment by mitar** [comment]
Hm, why you then decided for `:` to begin with? Aaaa. So many hacks because of that choice, in URLs, in directory names. You could simply use `/` or something, having subdirectories.

**Comment by mitar** [comment]
Oh, I didn't know that `_` already worked as `:` in `packages`. Nice.

**Comment by glasser** [comment]
I think I'm going to close this since we've taken steps to move towards no colons in the filesystem already.  I agree that it's a little strange to have them in package names but not on disk.
