### ISSUE TITLE
Spacebars : add support for {{#each object}} where object is an object

### ISSUE THREAD

**Issue by jeremyfourna** [meteor/meteor#3884]
Hello,

Actually {{#each}} can only iterate through an Array and spacebars doesn't have a {{#for key in object}} method.

It would be great if we don't have to use another templating language to iterate through the properties of an object.
Actually I have to know in advance what are the properties of my objects when I define my templates.

**Comment by stubailo** [comment]
Hi @dexterneo, thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Right now there is a workaround where you can serialize your object into an array using [`_.pairs`](http://underscorejs.org/#pairs), but I agree that it would be very useful for Spacebars to natively support iterating over objects.

**Comment by hwillson** [comment]
This issue has been moved to meteor/blaze#219 - closing here. Thanks!
