### ISSUE TITLE
Using afterflush to queue up changes

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3886]
I discovered this useful pattern for queuing up changes using Tracker.afterFlush, but I'm not sure how to rationalize the fact that afterFlush runs only once at a time:

```js


var a = {}
var b = new ReactiveVar(1);
var c = new ReactiveVar(2);
 
var needsUpdate = new Tracker.Dependency()
 
Tracker.autorun(function(){
  a.b = b.get()
  needsUpdate.changed()
})
Tracker.autorun(function(){
  a.c = c.get()
  needsUpdate.changed()
})
 
Tracker.autorun(function(c){
  needsUpdate.depend()
  Tracker.afterFlush(function() {
    console.log("update", a)
  })
})
 
 
// try just one at a time
b.set(3)
 
 
 
// then try this one
c.set(4)
 
 
 
 
// now try both of these at once
b.set(5)
c.set(6)

```

**Comment by glasser** [comment]
I'm sorry, I don't understand what you're saying here.

Is this literally the entire code?  Tracker flush doesn't run until you hit the event loop.  Am I supposed to interpret the large sets of newlines as "go back to the event loop"?  Are we supposed to be typing some of this into the browser console?

You also didn't tell me what you were expecting to see and what you actually saw.

Please follow the guidelines at https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor to express your issue more clearly.

**Comment by ccorcos** [comment]
Ok sorry for the poor explanation. Run a meteor project and open the browser console.

Paste this in and press enter:

```js
var a = {}
var b = new ReactiveVar(1);
var c = new ReactiveVar(2);

var needsUpdate = new Tracker.Dependency()

Tracker.autorun(function(){
  a.b = b.get()
  needsUpdate.changed()
})
Tracker.autorun(function(){
  a.c = c.get()
  needsUpdate.changed()
})

Tracker.autorun(function(c){
  needsUpdate.depend()
  Tracker.afterFlush(function() {
    console.log("update", a)
  })
})
```

Ok. Now just past this in and press enter:

```js
b.set(3)
```

You'll see it print as expected

```
> update Object {b: 3, c: 2}
```

Now same thing with c, as expected:

```js
c.set(4)
```

```
> update Object {b: 3, c: 4}
```

Now if you past both of these in at the same time:
```js
b.set(5)
c.set(6)
```

You'll see this print out
```
> update Object {b: 5, c: 6}
```

Now thats good! Thats what I want. I want to queue up all the changes and run them at once which is the point of afterflush. However `needsUpdate.changed()` gets called twice. Thus I would expect `Tracker.afterFlush` to be called twice.

I like this functionality of it only getting called once and it makes sense. But I dont see any mention in the docs of why this would only get called once.

**Comment by mikowals** [comment]
> Invalidating a computation that is currently invalidated or is stopped has no effect.

from http://docs.meteor.com/#/full/computation_invalidate

**Comment by ccorcos** [comment]
Hmm. That doesn't quite answer it for me. Is appears Tracker.afterFlush is invalidated as soons as Tracker.autorun is rerun...

**Comment by glasser** [comment]
What you're missing is that the third autorun only gets re-run once if it gets invalidated twice between flushes.  This is pretty important for performance: if a lot of things in a given part of the screen changes, it only needs to be re-rendered once per flush, not once per tiny thing that changed.

**Comment by glasser** [comment]
(Which is what @mikowals was referring to.)

**Comment by ccorcos** [comment]
ahhh. there we go. that makes sense. an autorun will only be run once per flush
