### ISSUE TITLE
SpacebarsCompiler div compiled as HTML.Raw instead of HTML.DIV

### ISSUE THREAD

**Issue by murillo128** [meteor/meteor#3890]
The following template is not properly compiled, as the  ```<div class="arrow"></div>``` is compiled to HTML.Raw instead of HTML.DIV, causing the render to be very slow due to the usage of parseHTML:

```html
<template name="query">
  <td class="Query {{className}}">
    {{#if elapsed}}{{formatElapsed elapsed}}{{/if}}
    <div class="popover left">
       <div class="popover-content">{{query}}</div>
       <div class="arrow"></div>
    </div>
  </td>
</template>
```
Outputs:

```javascript
(function () { var view = this; return ["\n  ", HTML.TD({"class": (function () { return ["Query ", Spacebars.mustache(view.lookup("className"))]; })}, "\n    ", Blaze.If(function () { return Spacebars.call(view.lookup("elapsed")); }, (function () { return Blaze.View(function () { return Spacebars.mustache(view.lookup("formatElapsed"), view.lookup("elapsed")); }); })), "\n    ", HTML.DIV({"class": "popover left"}, "\n       ", HTML.DIV({"class": "popover-content"}, Blaze.View(function () { return Spacebars.mustache(view.lookup("query")); })), "\n       ", HTML.Raw("<div class=\"arrow\"></div>"), "\n    "), "\n  "), "\n"]; })
```

**Comment by murillo128** [comment]
Problem seems to be on the OptimizerVisitor, it transfor this
```
tree[1].children[3].children[3]
HTMLTag {attrs: Object, constructor: function, tagName: "div", children: Array[0], htmljsType: Array[1]}
```
into
```
tree[1].children[3].children[3]
HTML.Raw {value: "<div class="arrow"></div>", htmljsType: Array[1]}
```

**Comment by murillo128** [comment]
Well, it seems that Optimizers does what it is intended to do, but at least in my tests HTML.DIV is performing better than HTML.Raw:

With HTML.Raw
5.18 s Loading
1.40 s Scripting
83.283 ms Rendering
38.706 ms Painting
32.043 ms Other

With HTML.DIV
1.16 s Scripting
65.247 ms Rendering
33.887 ms Painting
25.205 ms Other

**Comment by stubailo** [comment]
Hi @murillo128. This was an intentional decision because for some cases  we found that `HTML.Raw` is faster than `HTML.DIV`. Can you give me a reproduction where I can run the profiler and get the results above? Is `HTML.Raw` actually slower in all cases?

-----

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by murillo128** [comment]
I can't really reproduce the results just testing HTML.DIV vs HTML.Raw, so other things should be going on, or just the test result are not representative enough. Closing issue, I will re-open if I found anything meaningful.
