### ISSUE TITLE
Blaze Problem: Incorrect Parent Document With DOMBackend

### ISSUE THREAD

**Issue by jchristman** [meteor/meteor#3891]
When creating a new window with `window.open`, IE11 conforms to the standard and does not allow insertion of nodes created by the current document into the new window's document. It only allows nodes created by that new window's document. For example:

``` js
var newWindow = window.open('', '_blank', 'width=400,height=4000'); // Creates a new window

newWindow.appendChild(document.createElement('div')); // Fails, raising Hierarchy Request Error
newWindow.appendChild(newWindow.document.createElement('div')); // Succeeds 
```

This is relevant when attempting to use Blaze.render to create a second window with reactivity. For example, the following code, while working on Chrome and Firefox, fails on IE.

``` js
var newWindow = window.open('', '_blank', 'width=400,height=4000'); // Creates a new window
Blaze.renderWithData(Template[template], context, self.newWindow.document.body);
```

After much javascript debugging, I have determined that the code breaks on [line 94](https://github.com/meteor/meteor/blob/13e98f5a4ad85b6caf5dc3778f3e29aa3c500f30/packages/blaze/domrange.js#L94) of domrange.js, throwing an "Invalid Argument" exception in Internet Explorer. I believe this is an expression of the fact that the nodes being inserted have a document parent of the current view, rather than of the new window.

I believe this can be fixed by adding an argument to Blaze.render that would allow specifying a "document context" to pass to [jQuery.parseHTML](http://api.jquery.com/jquery.parsehtml/) (optional second argument). This "document context" would need to be passed all the way to [line 18](https://github.com/meteor/meteor/blob/a81fbf483efa4f40ea2d382f0c7275d408536e96/packages/blaze/dombackend.js#L18) of dombackend.js where the html nodes are created so that they are created with the correct document hierarchy. Another way of fixing the problem would be to look at the parent document of the [parentElement](https://github.com/meteor/meteor/blob/13e98f5a4ad85b6caf5dc3778f3e29aa3c500f30/packages/blaze/view.js#L551) and automatically passing that "document context" to the jquery.parseHTML.

To reproduce this, clone into the below repository.

```
git clone https://github.com/jchristman/meteor-popout.git
cd meteor-popout/example
meteor
```

Next, perform the following steps:
1. Open the running site in Internet Explorer
2. Open the javascript console
3. Click on any of the buttons that say "Popout State: false" to create a window and get the error

If you have any questions or need further details, please let me know.

**Comment by stubailo** [comment]
Hi @jchristman!

Thanks for identifying this case in which the Blaze API is not complete. Thank you also for tracking down which part of the code needs to change to enable your use case.

Hopefully we will be able to get to this soon. If not, I would welcome a pull request to add this option to `Blaze.render` and `Blaze.renderWithData`. Since `Blaze.renderWithData` already has 5 arguments, I think adding a 6th one will not be on a good path. So we should convert `render` and `renderWithData` to take a single argument, `options`, which basically has an unlimited number of keyword arguments, some of which are required and some are optional. Then, we can pass the new `documentContext` option down through the code to the right location.

Looks like this will be a great addition to Blaze that will allow people to do something they couldn't do before.

**Comment by jchristman** [comment]
Sounds good! I will take a crack at it here in the next few days.

Quick question for the PR: should we "deprecate" the old way by doing something like:

```js
Blaze.render = function (options, parentElement, nextNode, parentView) {
    if (typeof options !== 'object' || parentElement !== undefined || nextNode !== undefined || parentView !== undefined) {
        Blaze._warn("Blaze.render with multiple arguments is now deprecated. Use a single" +
                             " argument that is an object with kwargs.");
    }
}
```

Then, in some release down the road, the final code will look something like:

```js
Blaze.render = function (options) {}
'''

Obviously, we will also do the same thing with Blaze.renderWithData.

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#201 - closing here - thanks!
