### ISSUE TITLE
Provide an open source packages repository server

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3893]
**_1 Upvote**_ Is there an open source packages repository so that we could run one internally and not spam the official one will all temporary and buggy packages we want to use across the team? It seems that the code supports custom "universe", but the API is not yet documented, and also the code is not yet there? Or it is?

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by wursttheke** [comment]
Adding an additional package server would be cool. But for us it would be awesome to have an added package point to a git repository, just like you can do with [Bundler](http://bundler.io/gemfile.html):
```ruby
gem 'nokogiri', :git => 'https://github.com/tenderlove/nokogiri.git', :branch => '1.4'
```
With that feature, we could:
- share packages within a team during development without publishing
- quickly try out a fork of a package. Just point to the new git url or
- point to specific branch/tag
- use private packages on a git repository

In addition, it would be great to simply point to local folder. Currently it's a bit of a pain to test shared packages. It has to be placed inside the packages folder of a meteor app or you have to symlink to a seperate folder. Again, Bundler has a simple solution by adding a path:

```ruby
gem 'extracted_library', :path => './vendor/extracted_library'
```

**Comment by glasser** [comment]
@wursttheke That's a separate issue, #2919

**Comment by jperl** [comment]
We would pay for a hosted private package server.

**Comment by jperl** [comment]
@wursttheke FYI we are working around this with https://github.com/DispatchMe/mgp

**Comment by offthegrass** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20an%20open%20source%20packages%20repository%20server&body=Migrated%20from:%20meteor/meteor%233893) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
