### ISSUE TITLE
Ship MongoDB 3.0 with Meteor

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3894]
Meteor 1.0.4-rc.0 passes tests against a MongoDB 3.0.0 server, but we've chosen to be conservative and not ship this week-old major version bump by default with our tool for the development mode runner.  However, once 3.0 gets a little more mature we should upgrade it.

While we do believe that 1.0.4 will work with MongoDB 3.0, this issue is a good place to collect user experiences (positive or negative) using Meteor 1.0.4 or newer with MongoDB 3.0.

**Comment by maxnowack** [comment]
Any updates on this? I use 3.0 within my project for about one year and don't have any issues. I use some features of 3.0 in my app (e.g. `$dateToString`). Since 3.0 isn't shipped with meteor, I'm not able to test these parts of my app with the shipped mongodb version.

**Comment by ramijarrar** [comment]
@benjamn Is there any chance this could be included in 1.3.x?

**Comment by abernix** [comment]
This (or rather, Mongo 3.2) was done with #5809.  Closing. :smile:
