### ISSUE TITLE
Meteor build tool leaks memory when ran from checkout

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#3898]
Steps:

```
$ curmeteor create --example todos
$ cd todos
$ curmeteor
```

in a separate shell

``` bash
for ((i=0;i<1000;i++)); do
  echo " " >> todos/server/publish.js
  sleep 3
done
```

Observer the memory consumed by the build tool rise from 100mb to 500mb in 30s.

**Comment by hwillson** [comment]
I've confirmed this is no longer an issue with the latest `devel` version of Meteor (the memory used stays fairly constant). Closing - thanks!
