### ISSUE TITLE
Why one can't request more Facebook permissions which are not "whitelisted" ?

### ISSUE THREAD

**Issue by ernestorocha** [meteor/meteor#3900]
I always had a problem with the info the Facebook is sending to me when a user is trying to log in, and I think I've found the problem.

In this line, https://github.com/meteor/meteor/blob/611298fb50554b81a1889314ce8745b0b12b2f9d/packages/facebook/facebook_server.js#L19, everything which is not "whitelisted" is being removed. 

So, as I discovered Facebook is sending all the info to me, but it's being truncated due `_.pick(identity, whitelisted)`.

It's pretty easy to fix this, but my question is why it is like it is right now ? I can make a PR including the new fields of my interests right now ("user_location", "user_birthday"...) but I don't think this makes any sense. Everything should be taken from Facebook. It's not responsibility of the framework to decide what's important, it's the dev responsibility to decide what to do with the data.

What do you think ?

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

There was discussion about this on #636, which is what led to the PR #664 where this code was introduced.

I think that @gschmidt and @avital had a good point that apps should be in control of their own schema, but (a) maybe there are more things that didn't exist 2 years ago that should be added by default and (b) maybe we should add some key to `Accounts.config` to let you specify which fields you want if you don't like the default.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Why%20one%20can't%20request%20more%20Facebook%20permissions%20which%20are%20not%20%22whitelisted%22%20%3F&body=Migrated%20from:%20meteor/meteor%233900) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
