### ISSUE TITLE
Production mode not coming up

### ISSUE THREAD

**Issue by Akash-dvd** [meteor/meteor#3904]
We created a minimal test meteor app bundle in production mode and executed as per the README. I see that app is hung and here are the details 

READ ME :+1: 

This is a Meteor application bundle. It has only one external dependency:
Node.js 0.10.33 or newer. To run the application:

  $ (cd programs/server && npm install)
  $ export MONGO_URL='mongodb://user:password@host:port/databasename'
  $ export ROOT_URL='http://example.com'
  $ export MAIL_URL='smtp://user:password@mailhost:port/'
  $ node main.js

Use the PORT environment variable to set the port where the
application will listen. The default is 80, but that will require
root on most systems.

Find out more about Meteor at meteor.com.

When I follow this after I run node min.'s nothing happens.

$ (cd programs/server && npm instal
export MONGO_URL='mongodb://localhost:3001/meteor'
export ROOT_URL='http://localhost:3000'
node main.js

Any help/hint is appreciated

**Comment by glasser** [comment]
It seems like you are not setting the `PORT` environment variable. Did you try setting the `PORT` environment variable like it said?

**Comment by Akash-dvd** [comment]
thanks man :)
