### ISSUE TITLE
Meteor.absoluteUrl acting a bit oddly.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#3905]
I edit my /etc/hosts on my macbook to have the following line:
```
127.0.0.1 dev.afrazer.com
```
Then I start my meteor application, go to `dev.afrazer.com`, and everything works fine. However, I get a somewhat unexpected url in the following code:
```
var redirectUrl = Meteor.absoluteUrl("_oauth/battlenet?close");
console.log(redirectUrl);
```
This outputs: `http://localhost:3000/_oauth/battlenet?close` instead of `http://dev.afrazer.com/_oauth/battlenet?close`.

I'm a beginner so take this with a grain of salt. I might be doing something wrong myself.

EDIT: some additional information.
```
draenor :: (master*) » meteor --version                               ~/Development/code/draenor  
Meteor 1.0.3.2
```

**Comment by stubailo** [comment]
http://docs.meteor.com/#/full/meteor_absoluteurl

You should set the `ROOT_URL` env var like this: `ROOT_URL=deb.afrazer.com meteor`
