### ISSUE TITLE
Use of old "Meteor.Collection" API in autoupdate package

### ISSUE THREAD

**Issue by rjakobsson** [meteor/meteor#3906]
Should https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_cordova.js use "new Meteor.collection"? Is this a bug, or just something that should be?

**Comment by stubailo** [comment]
This was a backwards-compatible API change from ... 0.9.4 I think? It's not a bug, just a place we forgot to change to the new API. Not really a bug, but would be nice to change.

**Comment by glasser** [comment]
OK, this should be fixed by #3923.
