### ISSUE TITLE
Signups forbidden from client connected using DDP.connect()

### ISSUE THREAD

**Issue by PolGuixe** [meteor/meteor#3909]
I am having problems to signup new users from a client that it is connected using DDP.connect(). No problem when login with existing users. I can even change the password from this client. 

This is the code I am using to make the DDP connection the Accounts connection: 

``` javascript
if (Meteor.isClient) {
 Meteor.connection = DDP.connect('http://localhost:3030/');
 Accounts.connection = Meteor.connection;
 Meteor.users = new Meteor.Collection('users');
 Meteor.connection.subscribe('users');
}
```

The test project is basically the one created with `meteor create 'project_name'`. I added the `accounts-password` and the `accounts-ui` packages. Then I am using {{> loginButtons}} for the interface. Nothing else has been modified. 

**any ideas why the new signups are forbidden?**

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by PolGuixe** [comment]
I have been doing more testing. 

I've created two basic projects:
* Client: https://github.com/PolGuixe/DDP_test
* Host: https://github.com/PolGuixe/DDP_test_host

Between these two basic projects everything works **fine**. So I guess that I have some conflicts with my real project that acts as host. I'll check if any of the packages is creating the conflict.

**Comment by stubailo** [comment]
Thanks @PolGuixe - when you figure out the conflict, let me know!

**Comment by lzl** [comment]
@PolGuixe 

I have a similar issue #4286 so I checked out your reproduction. The result is, yes I can create new user account then logged in from DDP_test to DDP_test_host. But when I refresh the page of DDP_test. It logged me out automatically. Like the browser console shows:

```
Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]
```

Do you have this similar issue? If you do, how did you resolve that? Thank you.

**Comment by PolGuixe** [comment]
hi @lzl,

Finally I took a complete different approach. It is a bit hacky but it works fine in development and production. It may not work for your project. But it´s worth trying.
Basically I have two projects (web and mobile) but with the same `/server` and `/lib` code. Then I use the `--mobile-server` option to point the mobile app to the production server. 

More details and other solutions in the [Meteor Forum](https://forums.meteor.com/t/connecting-2-apps-over-ddp-how-to-login-across/977/28).

Let me know if you have any questions.
