### ISSUE TITLE
Meteor.connection.setUserId not documented

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3912]
Calling `this.setUserId` on the server in the method does not really change `userId` on the client. You also have to call `Meteor.connection.setUserId` on the client. But that is not really explained anywhere.

Non-working version: http://meteorpad.com/pad/7qLQAL46tytpPYacw/Leaderboard

Working version: http://meteorpad.com/pad/zSSmgQFrRjjCiRSH7/Leaderboard

**Comment by stubailo** [comment]
That's a good point. In general, it's not clear from the documentation how to concept of being logged in on a DDP connection works.

**Comment by mitar** [comment]
Of course, I always thought that server side `setUserId` automatically propagates to the client. Why is this (not) the case anymore?

**Comment by glasser** [comment]
That has actually never been the case.   User IDs are implemented at two levels.  At the `ddp` package level, it's just an arbitrary string that can be set independently by the server and client sides of the connection; there is no *DDP-level* mechanism for signaling a user ID change (in fact, it's not even part of the DDP wire protocol spec).  `accounts-base`, the most popular package used to manipulate a DDP session's user ID, returns the new user ID as part of the return value from the login method.

You're right that this needs better documentation, somewhere.  Most of our docs are user-level, not implementation-level.

**Comment by mitar** [comment]
This is development level. So `connection.setUserId` is not even documented. So this would be a first step. And then in method's `setUserId` there could be a reference saying that this sets only the server side and if one wants to set also the client side, use `connection.setUserId`.

**Comment by hwillson** [comment]
This is now mentioned in https://docs.meteor.com/api/methods.html#DDPCommon-MethodInvocation-setUserId:

> If you also want to change the logged-in user on the client, then after calling setUserId on the server, call Meteor.connection.setUserId(userId) on the client.

Closing - thanks for posting this originally!
