### ISSUE TITLE
Unable to pass arguments to data context method

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3913]
If I have a method on data context:

```
DataContext.prototype.foo = function (var1, var2) {
  return Template.fooTemplate;
}
```

It seems I cannot do `{{> foo 'foo' 'bar'}}` or `{{> foo a='foo' b='bar'}}`. This does not look like there is any reason why it would not work, except that it is not implemented?

**Comment by stubailo** [comment]
Have you tried using `Template.dynamic`?

**Comment by mitar** [comment]
Hm, I would really like some simple syntax like `{{> foo 'foo' 'bar'}}` or `{{> foo a='foo' b='bar'}}` or `{{foo 'foo' 'bar'}}` or `{{foo a='foo' b='bar'}}` which would allow you to return some template or view or anything dynamic/meta. It seems that helpers can return only values, and data context methods can return templates, but cannot accept arguments. So this makes it really hard to make a component system with data contexts at the moment.

**Comment by stubailo** [comment]
I think the real issue here is that you can't use `>` to render templates that are returned from helpers or functions. As far as I know, calling data context functions with arguments works fine - I did this extensively in an app I was working on recently where I made the data context a model object with many methods.

@mitar, can you confirm that this works on your end? Then we can rename the issue to something like "Template inclusion doesn't render templates returned from a helper or data context"

**Comment by mitar** [comment]
> As far as I know, calling data context functions with arguments works fine - I did this extensively in an app I was working on recently where I made the data context a model object with many methods.

Yes, `{{dataContextFunction 'foo' 'bar'}}` works perfectly. But you have to return a value. Not a template or a view.

I can do `{{> dataContextFunction}}` which should return a template object. Ideally, what I would like to do is `{{> dataContextFunction 'foo' 'bar' a='zzz'}}` and get the same call as with 
`{{dataContextFunction 'foo' 'bar' a='zzz'}}`, only that I can return a template (or view?) to be included. I would love that I could programmatically decide what is the data context of that template (or view?) included. So, do I could do something like `{{> dataContextFunction 'nameOfTemplate' 'language' dataContext=someOtherDataContextFunctionActingLikeHelper}}`.

**Comment by stubailo** [comment]
Ah, I see - so actually it is the case that:

1. You can call a data context function with arguments
2. You can render a template or view from a data context function

You just can't do (1) and (2) at the same time. Seems like a bug to me.

**Comment by mitar** [comment]
I can only render template from a data context function. Options of view would be something new/additional. Not completely sure if needed, but it could open additionally possibilities. (I am not sure how I can make a custom data context without being able to return a view.)

**Comment by stubailo** [comment]
So how does this tie into making a component system? I'm not sure I see the connection.

**Comment by mitar** [comment]
Component system would use a JavaScript (CoffeScript) classes and because data contexts would be instances of that classes, you could do inheritance between components easy. So you have a class with method `render` which returns a template and optionally configure the data context. If we look at Polymer-like component system, you could have two methods, `renderComponent` and `renderContent` (for content inside a component), all returning views/templates, and potentially you could pass arguments to `renderContent` to limit to only a subset of content.

**Comment by mitar** [comment]
So how I see it is that I can have a JavaScript-based classes which return "HTML" snippets to render. Similar to React. Only that I would be returning templates objects. (Ideally, if I would return views, I could even return htmljs.)

**Comment by stubailo** [comment]
I think you could achieve what you want by using the `Template` constructor directly - basically specify a render function that uses a function in the data context as part of itself.

**Comment by mitar** [comment]
Oho, I completely missed that `new Blaze.Template` is almost the same as `new Blaze.View`. OK, then I create templates programmatically, that is great! Then there are still two things missing:
* how I get arguments to the `{{> dataContextFunction 'foo' 'bar' a='zzz'}}`
* how I (optionally, determined by the logic in `dataContextFunction`) set another data context for the `new Blaze.Template` I am returning

**Comment by mitar** [comment]
Oh, I can return the following from a method to include `Tempalte.foobar` with the `newDataContext` data context.

```
return new Blaze.Template(function () {
  return Blaze._TemplateWith(newDataContext, Template.foobar);
})
```

OK, then the only thing is `{{> dataContextFunction 'foo' 'bar' a='zzz'}}`. Can then this be reclassified as a bug? @dgreensp?

**Comment by stubailo** [comment]
Agreed!

**Comment by mitar** [comment]
Reproduction: https://github.com/mitar/meteor-issue3913

See commented out blocks in the template.

**Comment by mitar** [comment]
Oh, I see that there are two different issues, one is:

```
{{> dataContextFunction a='zzz'}}
```

This gets changed into `{{#with a='zzz'}}{{> dataContextFunction}}{{/with}}` and then `dataContextFunction` does not exist in the current data context anymore, and this is why you get "No such template: dataContextTemplate" error.

The second issue:

```
{{> dataContextFunction 'foo' 'bar' a='zzz'}}
```

This does not even pass the template compilation phase.

All this seems then to make this as expected, but it really limits the usefulness. Could this be somehow made conditional? If `dataContextFunction` is a function, pass the rest as arguments, if it is a template, do the traditional thing?

**Comment by mitar** [comment]
I made a [workaround](https://github.com/mitar/meteor-issue3913/tree/workaround) which is OK, but not pretty:

```
{{> dataContextFunction args 'foo' 'bar' a='zzz'}}
```

So helper `args` wraps given arguments around original data context. But one also has to wrap all methods with an unwrapping code. See [here](https://github.com/mitar/meteor-issue3913/blob/workaround/template-method.coffee). I think pattern is really powerful, but it lacks nice support in Blaze.

**Comment by mitar** [comment]
After further experimentation, this method with `args` helper is really hacky. It introduces a new intermediary data context, and then another when restoring the original data context. And all this just to be able to pass arguments to a function. I would be OK with some special syntax, like using `args` keyword there, to make things backwards compatible, but I would need some help with how to make Meteor parse such include in a way that passes this directly to the function.

**Comment by mitar** [comment]
See the reason where I need this, in my Blaze Components implementation: https://github.com/peerlibrary/meteor-blaze-components

**Comment by brylie** [comment]
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment]
Use polymer as the default view layer using mwc:synthesis package 
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by hwillson** [comment]
Moved to meteor/blaze#218 - closing here. Thanks!
