### ISSUE TITLE
`add cordova plugins` test failure - FB plugin neither installs nor causes build to fail

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3914]
I'm getting this self-test failure consistently on `release-1.0.4`:

```
$ curmeteor self-test --slow 'add cordova plugins'
cordova-plugins: add cordova plugins ... 
  ... fail!
  => wrong-exit-code at tools/tests/cordova-plugins.js:198
  => Expected: 1; actual: 0
  => No output
```

The failure is in 
```js
  run = s.run("build", "../a", "--server", "localhost:3000");
  run.waitSecs(30);
  // This fails because the FB plugin does not compile without additional
  // configuration for android.
  run.expectExit(1);
```

It appears that the FB plugin is neither installing nor causing `build` to fail.

We tracked it down to this commit in cordova-lib: https://github.com/apache/cordova-lib/commit/242a8d760267379e963977de68d49aae96928562 which was done as part of this JIRA issue https://issues.apache.org/jira/browse/CB-7698

For whatever reason, this error case doesn't actually cause `plugin add` to fail with a non-zero exit code, but it does ignore the plugin.

**Comment by glasser** [comment]
Since it seems specific to this specific error message, added a hack to look at stdout for it!

**Comment by glasser** [comment]
(fixed on release branch)

**Comment by glasser** [comment]
They are also fixing the cordova bug, yay: https://github.com/apache/cordova-lib/pull/184

**Comment by Slava** [comment]
Thanks for fixing this!
