### ISSUE TITLE
Add links to source code for each function in the docs

### ISSUE THREAD

**Issue by PeppeL-G** [meteor/meteor#3916]
In [the documentation for Open Layers 3](http://openlayers.org/en/v3.2.1/apidoc/ol.Map.html), they link back to the source code where the functions are written. Could something similar be added to the documentation for Meteor? Curios as I am, I sometimes want to see how things work, but it's quite often hard to find where in the source code the functions has been written.

**Comment by stubailo** [comment]
This can be done easily, actually, since the docs are parsed out of source code anyway using jsdoc. Good idea!

**Comment by RobertLowe** [comment]
@stubailo Nice! :+1:
