### ISSUE TITLE
Meteor.loginWith<ExternalService> callback not called when using redirect login style

### ISSUE THREAD

**Issue by pauldowman** [meteor/meteor#3917]
When using `Meteor.loginWith<ExternalService>({loginStyle: "redirect"}, callback)` the optional callback is never called. The page is reloaded and no information about the callback is saved in sessionStorage.

### Reproduction

http://meteorpad.com/pad/Qq3G5CZ8u3q8X3xL3/oauth-redirect-callback-issue-repro

It's also deployed here because MeteorPad resets the data and wipes out the OAuth token:
http://oauth-redirect-callback-issue-repro.meteor.com/

### Details

Example with Facebook:

1. `loginWithFacebook` wraps the callback in a function returned by  `Accounts.oauth.credentialRequestCompleteHandler` [here](https://github.com/meteor/meteor/blob/556c0e28e94b9351cbf0b28e80a71a4e35f1362a/packages/accounts-facebook/facebook.js#L11)
2. Then calls `Facebook.requestCredential` with the wrapped callback function [here](https://github.com/meteor/meteor/blob/556c0e28e94b9351cbf0b28e80a71a4e35f1362a/packages/accounts-facebook/facebook.js#L12)
3. Which passes it to `OAuth.launchLogin` [here](https://github.com/meteor/meteor/blob/556c0e28e94b9351cbf0b28e80a71a4e35f1362a/packages/accounts-facebook/facebook.js#L12)
4. Which calls `OAuth.saveDataForRedirect(options.loginService, options.credentialToken)` [here](https://github.com/meteor/meteor/blob/ccfee68145720cd7761680215125f3f005d9ed30/packages/oauth/oauth_client.js#L121) and calls `OAuth.showPopup` with the callback [here](https://github.com/meteor/meteor/blob/611298fb50554b81a1889314ce8745b0b12b2f9d/packages/oauth/oauth_browser.js#L11)

I'm not sure how to go about fixing this because you can't really serialize functions, at least not with their bound variable values.

**Comment by pauldowman** [comment]
Sorry I had forgotten to make the Facebook app public so if you tried http://oauth-redirect-callback-issue-repro.meteor.com/ before now it wouldn't have worked. That's fixed.

**Comment by glasser** [comment]
Thanks. You're right that you can't serialize functions, which is why this doesn't work.  Let's update the docs to make this clear, and to suggest using client-side login hooks (added in 1.0.4) instead.
