### ISSUE TITLE
Template rendered order

### ISSUE THREAD

**Issue by tdmoneybanks** [meteor/meteor#3918]
I have a template that has multiple subtemplates.

```
<template name="x">
  {{> longLoadSubTemp}}
  {{> shortLoadSubTemp}}
  {{> otherTemp}}
</template>
```

I am trying to attach a jquery waypoint to a div within the shortLoadSubTemp. I placed the waypoint within the template.shortLoadSubTemp.rendered callback. The waypoint callabck is getting called twice when the page loads even though the shortLoadSubTemp should not be in the viewport. It seems that the problem is that the shortLoadSubTemp is loading quicker than the longLoadSubTemp above it and so, for a short moment when the page loads, the shortLoadSubTemp is within the viewport. Is there anyway to force the rendered order or should I just create a session variable that gets set to true in the longLoadSubTemp rendered callback? Thanks for the help.

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
