### ISSUE TITLE
`meteor shell` should support executing scripts

### ISSUE THREAD

**Issue by iameli** [meteor/meteor#3927]
**_1 Upvote**_ I'd like to be able to call files `meteor shell` so I can run arbitrary scripts within the context of a Meteor server. @meonkeys [provides a workaround here](http://stackoverflow.com/questions/28396923/can-i-run-a-one-liner-using-meteor-shell/29018889#29018889) but it would be nice to have something built into core.

Perhaps `meteor shell -f script.js` could be the syntax?

Our specific use case involves data generation in a test environment. We'd like to be able to tell our CI server "create this meteor server, run this data generator, expect these results", but the data generator calls code within the Meteor application.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by servel333** [comment]
I'd like to see this feature too. Maybe something where I can maybe create `.scripts/onlineUsers.js` and then run it in Meteor using something like `meteor shell --file .scripts/onlineUsers.js` or perhaps `meteor shell --run onlineUsers`.

**Comment by simap** [comment]
Similar situation here, I'd rather use `meteor shell` than expose an endpoint for destructive/dangerous test data staging.

**Comment by adnoh** [comment]
+1

**Comment by abernix** [comment]
With testing framework built-in to Meteor 1.3, which allows you to run things in the context of the Meteor server, is this even relevant anymore?

**Comment by meonkeys** [comment]
@abernix nice! This is news to me. Will you please provide a link to docs or examples with the relevant new functionality in Meteor 1.3?

Sounds great if it supports executing arbitrary JavaScript in the context of a running server, either by executing a .js file for you or allowing for shell one-liners.

**Comment by abernix** [comment]
Lots of information available in the new [Meteor Guide](http://guide.meteor.com/), particularly [this section on testing](http://guide.meteor.com/testing.html).

Plus view the [Full 1.3 Release Announcement](http://info.meteor.com/blog/announcing-meteor-1.3) on the blog.

**Comment by meonkeys** [comment]
@abernix I reviewed those before I asked. I don't see any straightforward examples. Little more help, please?

Maybe `meteor shell -f` is still a nice feature to have, or maybe the Meteor Guide just needs a section for how to do this with off-the-shelf Meteor 1.3. The Meteor Guide looks awesome, but between importing files and picking a test runner I'm rather lost on how to do something like the proposed `meteor shell -f`.

**Comment by abernix** [comment]
If you're looking for something straightforward, I highly recommend the [Meteor Todos](https://github.com/meteor/todos) app which comes with tests built-in that you can look at and see how they would fit in with your project.  A combination of that and the guide should be enough to get you started, but if you need more help check out [Meteor forums](https://forums.meteor.com) or StackOverflow.

http://guide.meteor.com/1.3-migration.html provides information on Migrating to 1.3 (which uses new JavaScript ES2015 module import/exports) and is probably worth a look if you're needing to wrap your mind around the importing, etc.  I know there is a lot of information to take in with the 1.3 release, but it's important stuff.

As for the feature request, it just seems as if the general need for this `meteor shell -f` feature is to perform tests within the context of the server and that is exactly what the testing framework provides.  Therefore, I don't immediately see much value to adding the feature.

**Comment by servel333** [comment]
I don't think `meteor test` fits this use case. Personally, I'm not looking to run tests specifically, but instead looking for a way to run maintenance or reporting scripts, usually with totally customized output. It's not very obvious how to even do that with the `meteor test` command from the documentation, and it seems weird to have to pick a test framework just to run a maintenance script that isn't for testing.

For me, the feature request for a `meteor shell -f` command still stands.

**Comment by abernix** [comment]
@servel333 Ok, so for maintenance scripts in your development environment?  Because the `meteor shell` is not available at all in production.

**Comment by simap** [comment]
@abernix Yes I think it is still useful. Why make users resort to weird expect scripts? There are more uses for this than in just testing, for example loading similar data for development. 

On another note, I think `meteor shell` functionality would be very valuable in production. Debugging production data is much easier in a meteor shell than in mongo, and potentially safer. You can also poke internal APIs when you didn't have the foresight to expose them as well protected APIs. As long as this is only listening locally, I don't see what the potential drawbacks are.

**Comment by abernix** [comment]
#4203 is already open for a production shell – different topic though.

@simap "weird expect scripts" are just industry-standard Mocha tests which are used by many/most NPM packages.  It's not some made up language.  They are the generally accepted way of doing tests.  I'm not suggesting using them for non-testing stuff, but the original requirement of this issue was:

>create this meteor server, run this data generator, expect these results

And if you're doing "totally customized output" reporting scripts on your development machine, or even just loading development data, why not use a `debugOnly ` package that provides the exact functionality you need via a method call?  Piping the output of a JS file into the meteor shell just seems like you'd be avoiding writing a package.

**Comment by simap** [comment]
@abernix you misunderstand my "weird expect scripts" statement. I'm talking about the original [expect](http://linux.die.net/man/1/expect) command line tool. Expect is the glue that you use to get otherwise unfriendly console applications to cooperate with automation. This has nothing to do with Mocha or expect-style assertions.

This is the expect-based [workaround](http://stackoverflow.com/questions/28396923/can-i-run-a-one-liner-using-meteor-shell/29018889#29018889) that the OP mentions. This is the kind of "weird expect script" that users have to write and maintain (this script no longer works for me on newer Meteor versions): 

```
#!/usr/bin/expect --
set timeout 3
spawn meteor shell
expect "> "
set firstArg [lindex $argv 0]
set secondArg [lindex $argv 1]
if { $firstArg == "-f" } {
  send [exec cat $secondArg]
  send "\n"
} elseif { $firstArg == "-e" } {
  send "$secondArg\n"
}
expect "true"
send "\x04"
expect "Shell exiting...\n"
```

> Piping the output of a JS file into the meteor shell just seems like you'd be avoiding writing a package.

Yes, exactly. Now you are starting to see the point. It isn't always possible or convenient to do everything in a meteor package. Leveraging the universe of shell scripting opens up a lot of possibilities.

**Comment by abernix** [comment]
Heh, okay, I'm aware of `expect` but I never saw the work-around link, thus the confusion with test-assertion-style `expect()`'s. 😁 

However, despite misunderstanding the "expect" you were talking about, I still don't see the point.  This `expect` script simply pipes JavaScript into the Meteor shell.  Why couldn't you put the same JavaScript that you're piping in, into a package, and run it with a method?  

The world of possibilities seems identical as you could just use any shell-script/language/tool to communicate with the Meteor method if you really wanted to (DDP, etc.).  It's not like you can just pipe in CSVs or something to the meteor shell – it still only takes JavaScript.

**Comment by abernix** [comment]
All that being said, it's probably not remarkably hard to implement in development since it uses `repl` on the back-end.  Probably somewhere near here: https://github.com/meteor/meteor/blob/devel/tools/shell-client.js#L116-L144.

**Comment by meonkeys** [comment]
Great points, all. #4203 sounds like exactly what would be useful for prod.

The `debugOnly` package sounds like a fine solution for dev, and armed with that idea I'm +1 for closing this ticket. I wrote that `/usr/bin/expect` workaround and I'd cheer on cremation of same.

**Comment by abernix** [comment]
Another thing I just realized: You can do `.load /path/to/file.js` within the `meteor shell` and it will execute that file (Just like Node) within the Meteor shell.

You should use full path though, as the current working directory within the shell is `<your-app>/.meteor/local/build/programs/server`.

So really this Issue really comes down to "Meteor Shell doesn't accept STDIN pipe".

**Comment by iameli** [comment]
@abernix Wow, that's... a really good point.

I don't work with Meteor too much day-to-day anymore, but that seems to conclude this ticket pretty well.

**Comment by mitar** [comment]
Yes, but I think that "Meteor Shell doesn't accept STDIN pipe" is an important aspect of it.

**Comment by simap** [comment]
What about `meteor shell -e ".load /path/to/file.js"`. Something like an `-e`=execute could be used for both.

**Comment by mitar** [comment]
If `meteor shell -e ".load -"`means load a script from stdin. :-)

**Comment by abernix** [comment]
I think since the `meteor shell` is 99.8% node `repl`, it should mimic it's functionality identically and take it from STDIN or using `.load` at the prompt.  No extra flags.

**Comment by abernix** [comment]
Meteor Shell does support input from a pipe now (and has for a while now), much in the exact same way as Node doe.  See #5055.  Thanks for this suggestion originally!

> `echo 1+1 | meteor shell`
