### ISSUE TITLE
Invoque Meteor.call("login",obj ) server side

### ISSUE THREAD

**Issue by eportico** [meteor/meteor#3928]
I have a HTTP Api for authentication. I call to Meteor.call("login",{user:{username:"xx"},password:"xxx"});

This call fail with error:  Cannot read property 'id' of null

What happend ? This code worked in the past

**Comment by stubailo** [comment]
When did this code work before? As far as I know, `Meteor.call("login", ...)` never worked from the server outside of another method call because it requires a DDP connection.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
