### ISSUE TITLE
Accounts.emailTemplates.from is not displayed as defined in mailbox

### ISSUE THREAD

**Issue by aj07mm** [meteor/meteor#3929]
Hi,

i defined this:
```
Accounts.emailTemplates.from = "Foobar";
```

but instead of "Foobar" as the sender in the mailbox is displayed the email defined in 

```
this.process.env.MAIL_URL = "foobar@gmail.com"
```

is there a way to show "Foobar"? Seems like something is wrong, it ends up being different from Mandrill that is another service which i use that shows "Foobar" as sender.

**Comment by Tarang** [comment]
You can use this format "Foobar <foobar@gmail.com>" to define the from address as with the RFC: https://tools.ietf.org/html/rfc2822

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

For example, the thing you are showing in `MAIL_URL` is not an URL, so either you're not showing the real reproduction, or that's the issue.

**Comment by aj07mm** [comment]
Thanks @Tarang, that worked perfectly!

**Comment by aj07mm** [comment]
You are right @glasser , i will improve my questions next time. Thnks for the advice
