### ISSUE TITLE
Underscore function _.find() undefined after second call on same template

### ISSUE THREAD

**Issue by mgbellaire** [meteor/meteor#3930]
I've created repo for this bug. Instructions and environment information is in the README, but here it is:

https://github.com/mgbellaire/underscore-find-bug

# \_.find() bug instructions
1. Start the app up: `meteor run`
2. Press the "Click Me" button once
3. Open the browser console to view the "Uncaught TypeError"

## Environment info
* **OS**: OSX Yosemite 10.10.2
* **Browser**: Google Chrome 41.0.2272.76 (64-bit)

**Comment by glasser** [comment]
We do. https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by mgbellaire** [comment]
@glasser, I've updated the info, created an app and added instructions. How does this look?

**Comment by PeppeL-G** [comment]
I've looked through your code (good minimal reproduction!), and you're calling [_.find](http://underscorejs.org/#find) wrong. The second argument to it must be a function (returning `true` or `false`), you can't simply use a string. So instead of doing this:

```javascript
_.find(testArray, 'test')
```

Do this:

```javascript
_.find(testArray, function(element){ return element == 'test'})
```

**Comment by glasser** [comment]
@PeppeL-G Thanks, I agree.  @mgbellaire You might be looking for `_.contains`.
