### ISSUE TITLE
DDP Subscription with multiple resultset

### ISSUE THREAD

**Issue by navinSing** [meteor/meteor#3931]
https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md

sub (client -> server):
   id: string (an arbitrary client-determined identifier for this subscription)

but the added, changed or removed are having just document id NOT the *sub id*

So if i have subscribed 2 resultset on same collection. i cannot figure out the exact changes in each subscription

**Comment by glasser** [comment]
Yes, that is how DDP is designed to work.  It is designed around the model where the main consumer of a DDP connection is using it to fill a local cache that is intended to (abstractly) be a subset of the server's database.

We recognize that this is a different model from other forms of pub/sub, and it's possible that a future version of DDP will have a different model.

**Comment by navinSing** [comment]
can we still keep this open ?

**Comment by glasser** [comment]
I'm not sure that "use a substantially different model for how data flows between the layers of the standard Meteor stack" is a really productive feature request to keep open.
