### ISSUE TITLE
Cordova download hangs when behind a proxy

### ISSUE THREAD

**Issue by dougmacklin** [meteor/meteor#3933]
When I'm behind a proxy and try to run `meteor run android` it hangs at 0% while trying to install the Cordova plugin.  With the `--verbose` flag applied, here is the (truncated) output:

```bash
% Installing a plugin org.apache.cordova.console 0.2.10                            
Using (built-in) Android SDK at /Users/username/.meteor/android_bundle/android-sdk 
% Running synchronously:  /Users/username/.meteor/packages/meteor-tool/.1.0.41.azxhr5++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'add', 'org.apache.cordova.console@0.2.10' ]
   Installing Cordova plugins                [                            ] 0% 0.0s
```

On a network without a proxy it works fine.

**Comment by Slava** [comment]
This part of Meteor uses `curl` under the hood, which looks at `http_proxy` environment variable. Please, make sure that it is set.

**Comment by dougmacklin** [comment]
Thanks @Slava. Apparently on Macs the http_proxy variable isn't set by default when you set a proxy in network settings: http://arstechnica.com/civis/viewtopic.php?f=19&t=147601

It'd be cool if meteor could have a timeout and set http_proxy based on networksetup's output. I'm not sure if that would overcomplicate things though.

**Comment by Slava** [comment]
Right now we don't go this far for the Meteor tool itself, I think.
