### ISSUE TITLE
When building for iOS - button presses are counted twice

### ISSUE THREAD

**Issue by kevinchiu** [meteor/meteor#3936]
How to repro:

1. Create a new meteor project. 
2. Go into the project folder
3. meteor install-sdk ios
4. meteor run ios
5. The iOS emulator should appear with the starter page loaded.
6. Press the button. The count now shows that the button has been pressed 2 times. It should show 1.

This problem does not occur if you load the localhost:3000 page through Safari.

**Comment by stubailo** [comment]
This reproduction doesn't happen for me. What version of Meteor are you running? can you package up the whole app directory and send it to me so I can try it?

**Comment by kevinchiu** [comment]
Meteor 1.0.3.2

I found the source of the problem. I added the mjn:famous library, which is causing the duplicate click registration.
