### ISSUE TITLE
Add 'stopped' attribute to observers handles

### ISSUE THREAD

**Issue by theosp** [meteor/meteor#3938]
I find the fact that a _stopped_ attribute is not available on the `observe`/`observeChanges` returned handle inconsistent with the Tracker api.

As both of the apis has a stop() method, and the Tracker is in use often I think it should work as a standard. Since I am used to the Tracker API I found it surprising that the above don't have the _stopped_ attribute (which I needed for testing).

If you agree, let me know, as I can also work on implementation.

Thanks,
-Daniel

**Comment by stubailo** [comment]
Can you provide some more details? For example, some sample code as it would look with this new API.

**Comment by theosp** [comment]
Hi @stubailo ,

Computations has the `stopped` attribute that indicates their status:

    comp = Tracker.autorun(runFunc)
    comp.stop()
    if (comp.stopped === true) {
        console.log("comp stopped");
    }

I think that for Meteor APIs to be coherent the following should be implemented too for `observe/observeChanges`:

    observer = cursor.observeChanges(callbacks)
    observer.stop()
    if (observer.stopped === true) { // this is the missing part
        console.log("observer stopped");
    }

As far as I know, not only this is somewhat in-consistent API, but also, there is no API to get observers status, which can be very valuable information.

Thanks,
-Daniel
[Meteor Developer](http://www.meteorspark.com/), MeteorSpark

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by theosp** [comment]
Thanks @glasser ,

I find APIs inconsistency/non-coherent design to be more of a bug than a feature.

-Daniel

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20'stopped'%20attribute%20to%20observers%20handles&body=Migrated%20from:%20meteor/meteor%233938) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
This is probably part of https://github.com/meteor/meteor-feature-requests/issues/64.
