### ISSUE TITLE
Publish Meteor's check function on NPM

### ISSUE THREAD

**Issue by meepeek** [meteor/meteor#3939]
Is there any npm for Meteor's check (validation) ?

Check function in Meteor is very convenient and I would like to use the same pattern in node webkit.

**Comment by stubailo** [comment]
You can get the files here: https://github.com/meteor/meteor/tree/devel/packages/check

Unfortunately we currently don't package any Meteor packages in NPM, but you should feel free to do so!

**Comment by meepeek** [comment]
Thanks a lot.
