### ISSUE TITLE
accounts-password email verification: missing date header field

### ISSUE THREAD

**Issue by SylvainBigonneau** [meteor/meteor#3940]
When `accounts-password` sends a verification email, my SMTP provider warns that the sending date is missing from the email header :

`X-Amavis-Alert BAD HEADER SECTION, Missing required header field: "Date"`

Is there a way to add the custom header fields of the emails sent by `accounts-password`? Or even better, add custom header variables to every email sent by the `email` package?

**Comment by glasser** [comment]
Yes, as of 1.0.4 you can set `Accounts.emailTemplates.headers`: http://docs.meteor.com/#/full/accounts_emailtemplates

There isn't a way to set global headers for all emails.

**Comment by mcorb** [comment]
@glasser - setting the Date header in the template isn't satisfactory, given that the date needs to reflect the date and time the email is sent.

I suggest integrating the simple https://github.com/jsdevel/node-email-date-header module and adding the header implicitly within Meteor's email implementation.

Failure to resolve this issue can get Meteor deployments flagged as email spammers.

**Comment by glasser** [comment]
Good point, reopening.

Maybe at some point the email sending API could be redesigned to not need 15 different ad hoc tweaks.

**Comment by mcorb** [comment]
Nodemailer by the same author apparently wraps smtp-connection (successor to simplesmtp) and handles details like this. Looks like a heavier dep, but maybe worth considering in future to avoid wasting time on SMTP minutiae.

https://github.com/andris9/Nodemailer

Ad-hoc fix would be great for now though.

**Comment by AlexanderS** [comment]
Any progress on this? Maybe it would be possible to simply update the mailcomposer package to a more recent version. The recent version use the [buildmail](https://github/nodemailer/buildmail) package that includes handling of the Date header.

**Comment by langfors** [comment]
yes please!
