### ISSUE TITLE
accounts-ui and accounts-google package do not let me add new users due to restrictCreationByEmailDomain validation error message

### ISSUE THREAD

**Issue by ashburnham** [meteor/meteor#3941]
I am using meteor 1.0.3.2 and the following accounts packages

accounts-google, version 1.0.3         
accounts-oauth, version 1.1.3 
accounts-ui, version 1.1.4    
accounts-ui-unstyled, version 1.1.6

The packages work fine for existing users, but when I try to add ANY valid new user it gives me the message for an invalid email by restrictCreationByEmailDomain.

I have tried various solutions including not stating any restrictCreationByEmailDomain, using strings, reg exp and even a function that returns true (see below).

        Accounts.config({
            restrictCreationByEmailDomain: function (email) {
                return true;
            }
        });

I have added and removed all the packages, reinstalled meteor, to no avail.

When I play with these functions 

Accounts.validateNewUser()
Accounts._options.restrictCreationByEmailDomain()

in the meteor shell, they work fine. By when I access these functions by actually using the accounts-ui, it doesn't work.

This app is in production and so it's kinda killing me at the moment... any ideas appreciated!

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

For example, you're not even showing us the error message that you say happened, let alone enough context to reproduce it.
