### ISSUE TITLE
[Cordova] iOS - Support for Asset Catalogs

### ISSUE THREAD

**Issue by emilecantin** [meteor/meteor#3948]
It would be nice to support Assets Catalogs for iOS app icons and splash screens. They are a standardized way to specify which image to use for each device, which would greatly reduce the burden of configuration in mobile-config.js.

**Comment by Slava** [comment]
I agree that the current flow of adding assets to the mobile apps is not great. There is a similar issue with some suggestions on how to improve it in #3767. I would like to hear more on "Asset Catalogs" and how one can make it work with Meteor's build process in that issue.
