### ISSUE TITLE
banners shouldn't be word wrapped

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3949]
either the banner printer should print them raw, or we shouldn't bother manually wrapping them

**Comment by applocalizations** [comment]
I agree David.

2015-03-17 13:34 GMT-07:00 David Glasser <notifications@github.com>:

**Comment by hwillson** [comment]
I haven't seen/heard many complaints about the current banner writing approach, so given the > 1.5 year age of this issue and the lack of +1's, I'll close this off. Happy to re-open if anyone feels this is still something that should be addressed. Thanks!
