### ISSUE TITLE
Feature request: allow server hooks on document insert, update, remove

### ISSUE THREAD

**Issue by guillermosan** [meteor/meteor#395]
Case use:

When a user in my app sends a new message i want to include in the doc the creation date of the item. I don't want to trust the client clock, it needs to be a server side generated value. 

I've been doing something like:
```javascript
myCollection.allow({
	insert: function (userId, doc) { 
        if (userId === doc.owner_id) {
			doc.creationDate = +(new Date);
			return true; 
		}
});
```
That works. Mongo insert includes the creationDate field and it's serverside generated. 

Then i tried this:
```javascript
Meteor.users.allow({
	insert: function (userId, doc) { 
			doc.someDefaultValue = true;
			return true; 
		}
});
```

This one fails. The insert function doesn't get called when users are inserted. I went at irc for some help and someone warned me this way of modifying the doc might not be intended, and that it is problably failing due to some default Meteor.users.allow call.

What would be the ad-hoc approach? For me this method works nicely.

**Comment by mizzao** [comment]
Would it be possible to re-open this issue (now that FRs are permitted) and consider the integration of https://github.com/matb33/meteor-collection-hooks into core? It's very widely used, yet requires a level of monkey patching and version dependence way beyond normal packages.

A set of proper hooks would allow for a much cleaner implementation of the https://atmospherejs.com/aldeed/collection2 package.

**Comment by glasser** [comment]
Sure, reopened based on our new [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by theduke** [comment]
+1 for this, I see it as quite essential functionality.

**Comment by rclai** [comment]
I am all for a non-monkey-patching solution to extending the Mongo.Collection API.

**Comment by almogdesign** [comment]
+1 this would be great, would also solve some issues for me in offline mode with groundDB

**Comment by jasonxeno** [comment]
+1 I use meteor-collection-hooks extensively in my pretty large app, it would be wonderful to unify it under Meteor core to increase stability. It's one of the most popular packages currently sitting at 3k on Atmosphere.

**Comment by rhyslbw** [comment]
+1 The number of end users interacting with this code would be huge

**Comment by FrancoAA** [comment]
+1

**Comment by nrafter** [comment]
+1

**Comment by scottsimock** [comment]
+1

**Comment by artwells** [comment]
+1

**Comment by rcsandell** [comment]
+1 has been very useful. 

Using to be able to modify a find selector before returning documents in publications to give the intersection of the documents a user is allowed to see, and the whatever other selector I used in the find for that publication.

**Comment by stocksp** [comment]
+1

**Comment by teknologist** [comment]
+1 indeed. Extensively using collections hooks package here too.

**Comment by webyak** [comment]
+1

**Comment by JackAdams** [comment]
+1 for a non-monkey-patching solution to extending the Mongo.Collection API.  Several super-useful and/or highly popular packages use this, but it's sometimes difficult to get them all working together due to the layers of wrapping of `Mongo.Collection` (with different functionality and APIs at each level of wrapping).

**Comment by risul** [comment]
+1

**Comment by Kestanous** [comment]
:+1:

**Comment by mizzao** [comment]
The number of issues getting reported for collection-hooks is reaching epic levels: https://github.com/matb33/meteor-collection-hooks/issues

Most are not about code quality, but use, design choices, and edge cases. I think this makes a strong argument for integrating into core, given how prominently it is used.

**Comment by rclai** [comment]
Yes, also, I just wanted to link [this issue](https://github.com/meteor/meteor/issues/3827) as well since it is related. Also, since Mongol was released, people have also been experiencing similar issues as well.

**Comment by mariorodriguespt** [comment]
+1

**Comment by Siyfion** [comment]
I'd love to see an official hooks implementation added to the API.

**Comment by dweldon** [comment]
:+1: Yes please.

**Comment by dandv** [comment]
Server-side auto-timestamping and auto-adding the user who inserted a document are such common use cases. Would love to see these made easy by the core.

**Comment by DeBraid** [comment]
+1.  Should have after insert hook for setting Session variables.

**Comment by gbachik** [comment]
+1

**Comment by jms301** [comment]
Yup auto-userId is my use case for this. The client should not need to know it's userId before submitting inserts.

**Comment by robfallows** [comment]
+1

**Comment by mcbain** [comment]
+1

**Comment by poojabansal** [comment]
+1

**Comment by terkalma** [comment]
+1

**Comment by dolgarev** [comment]
+1

**Comment by rudolfb** [comment]
+1

**Comment by bluepuma77** [comment]
+1

**Comment by Billybobbonnet** [comment]
+1

**Comment by jagi** [comment]
What about creating entire events system for many elements in Meteor, not only collection. I've used such approach in the [Astronomy](https://github.com/jagi/meteor-astronomy#events) package. It could look like follows:

```js
Posts.on('beforeInsert', function(e) {
  var doc = e.data.doc; // Getting document being inserted

  // Ability to stop propagation and to prevent default action
  e.stopPropagation();
  e.preventDefault();
});
```

Of course it could be something simple, more similar to the hooks that were already used in Meteor.

```js
Posts.onInsert = function(doc) {
  return doc;
};
```

However, such syntax allow only one hook. Of course, we could use different approach:

```js
Posts.onInsert(function(doc) {
  return doc;
});
// Another onInsert hook.
Posts.onInsert(function(doc) {
  return doc;
});
```

However, in my opinion events system is much more flexible and could be shared among entire Meteor API.

**Comment by joaopiopedreira** [comment]
\+ 1 for @jagi solution

**Comment by voidale** [comment]
+1

**Comment by nhduc296** [comment]
+1

**Comment by jayjo7** [comment]
I feel very strongly that adding this feature to core will benefit Meteor and meteor developer community. Please include in the code package.

**Comment by tcastelli** [comment]
+1

**Comment by prankymat** [comment]
+1

**Comment by sasikanth513** [comment]
+1

**Comment by stubailo** [comment]
The approach we recommend is now documented in the Meteor Guide: http://guide.meteor.com/collections.html#hooks

Looks like we won't be implementing this feature since there is a simple way to achieve the same thing with no feature at all.

**Comment by matb33** [comment]
It should be noted that the technique referenced in the guide will have the hook fire on a per-call basis whereas a package such as collection-hooks fires its hooks on a per-document basis.

**Comment by stubailo** [comment]
Correct!

**Comment by CandyOgre** [comment]
+1
