### ISSUE TITLE
Package that no longer has binary code is still required to have binary builds

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#3952]
I found this out when writing a workaround for `mizzao:sharejs@0.7.3` that doesn't require binary builds, which seem to be currently broken in #3951. After taking out the Mongo driver, which had the native code, I still got the following message:

```
Published mizzao:sharejs@0.7.3.               
                                              
This package contains binary code and must be built on multiple architectures.
                                              
You can access Meteor provided build machines, pre-configured to support older versions of MacOS and Linux, by running:
  meteor admin get-machine os.osx.x86_64      
  meteor admin get-machine os.linux.x86_64    
  meteor admin get-machine os.linux.x86_32    
                                              
On each machine, run:                         
                                              
  meteor publish-for-arch mizzao:sharejs@0.7.3
                                              
For more information on binary ABIs and consistent builds, see:
  https://github.com/meteor/meteor/wiki/Build-Machines
```

It seems like Meteor might be unable "unmark" a package as being no longer binary? I currently don't see any binary dependencies in the [ShareJS package.json](https://github.com/mizzao/ShareJS/blob/0.6/package.json), and it is the only dependency of the Meteor package.

**Comment by glasser** [comment]
The logic is pretty simple: it's just searching for a `*.node` file, and in fact there are two:

```
./npm/node_modules/share/node_modules/ws/node_modules/bufferutil/build/Release/bufferutil.node
./npm/node_modules/share/node_modules/ws/node_modules/utf-8-validate/build/Release/validation.node
```

**Comment by mizzao** [comment]
Thanks. Didn't know that's how it worked or to look that many levels deep. :)
