### ISSUE TITLE
Sensible namespace for helpers

### ISSUE THREAD

**Issue by jonjamz** [meteor/meteor#3953]
There are some great helpers [here](https://github.com/meteor/meteor/blob/50e6d3143db8fc6e1fc3fb74da74b40c8dc7f3a4/packages/meteor/helpers.js#L17) for working with objects. Unfortunately, they exist directly inside the `Meteor` namespace and have non-descriptive names.

Throughout Meteor's evolution, undocumented methods like these have proven useful in critical ways for those who knew where to find them. It would be great going forward if they existed in a more specific namespace--for example, `Meteor.utils`--and if their names were more descriptive. Docs could then disclose this namespace and suggest how to use/not use the methods inside it.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Sensible%20namespace%20for%20helpers&body=Migrated%20from:%20meteor/meteor%233953) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
