### ISSUE TITLE
Allow serving different bundles to different client platforms (other than browser vs cordova)

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3954]
I'm wondering if there are any plans / eta on adding runtime platforms?

It would be so nice to start using `web.browser.ie` and maybe `web.browser.ie>8`, `web.cordova>4` or `web.cordova.ios`

Eg.:
```js
Package.onUse(function(api) {
  api.addFiles('workaround.ie.js', 'web.browser.ie<9');
});
```

The reason for this is obviously to write better packages, this could be for polyfills/libraries etc. without including unused code. The current use case for me is `raix:push` where each platform got their own api implementations.

*I know it's not trivial eg. how should mobile browsers be defined etc. still stuff to be figured out*

Kind regards Morten

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

(I'm reasonably sure this is a duplicate, but I can't find another version of it.)

**Comment by RobertLowe** [comment]
:+1: I like this idea. 

How fine grade should the versioning semantics be (ex: `web.browser.ie>8.0.1`, `web.browser.ie<8.0.1`). What about targets that use different versioning semantics (ex: `web.browser.chrome=41.0.2272.104`).

Additionally I think some *very few* clients can only be detected at runtime...

Cheers
