### ISSUE TITLE
Add a "Forum" (or Discussion) link (pointing to the forum.meteor.com) in the Navbar, "Stats" section and Footer of the Meteor.com website.

### ISSUE THREAD

**Issue by dalerka** [meteor/meteor#3955]
Just to remind you guys (at MDG) to update the http://Meteor.com website, so people can easily get to the [forum](http://forum.meteor.com) and enjoy discussions in our community :)

*label:Project:www.meteor.com*

**Comment by glasser** [comment]
Good call. It's on https://www.meteor.com/contact but could be more prominent.

**Comment by glasser** [comment]
Fixed, thanks!
