### ISSUE TITLE
There should be a code sample for onCreated, onRendered, and onDestroyed

### ISSUE THREAD

**Issue by mariusdarila** [meteor/meteor#3956]
This http://docs.meteor.com/#/full/template_onCreated caused me a lot of problems because its not working, the right way to use it is Template.myTemplate.created.

**Comment by Slava** [comment]
@mariusdarila can you please give a concrete example where it is not working?

**Comment by Slava** [comment]
`Template.name.created = function () {}` was deprecated in favor of `Template.name.onCreated(function () {});` in 1.0.4.

**Comment by mariusdarila** [comment]
```
Template.name.onCreated = function(){ 
var instance = Template.instance();
instance.somevar = new ReactiveVar(10);
}

Template.name.helpers({
getVar: function(){
//this is throwing an error, somevar is not in template instance and does not have get() method
return Template.instance().somevar.get();
}
})
```
When i switched to ```Template.name.created``` everything worked like a charm

**Comment by Slava** [comment]
@mariusdarila did you see my example above? The way you use the `onCreated` function, you call it passing an event handler as an argument.

**Comment by mariusdarila** [comment]
Yeah, i see the problem now, thx for explanation. Some examples like this would help in documentation, i'm still a newbie in Meteor and this would help people like me because there are a lot of outdated examples of meteor on google and its frustrating to find the right way to use the api :).

**Comment by massimosgrelli** [comment]
I have the same problem. I switch to OnCreated and stopped working ─ I saw your example, but I have got a lot of errors. I migrated from:

```Templalte.channel.created = function() { ... }```
to
```Template.channel.OnCreated( function() {...});```

Running my application the browser console is full of errors like:

```Uncaught TypeError: undefined is not a function```

**Comment by Slava** [comment]
@massimosgrelli you have misspelled `onCreated`. The first letter is in lower case.

**Comment by massimosgrelli** [comment]
Whoops! Thanks
I checked the documentation searching the problem for the last couple of hours. You made my day.

**Comment by stubailo** [comment]
I think this documentation is unclear because there is no code sample to show how to call the function. It's especially bad because the manner in which it should be called is different from the previous API.

**Comment by massimosgrelli** [comment]
You can find a sample here http://docs.meteor.com/#/full/Blaze-TemplateInstance-subscribe but in general you are right. Very few samples in the API documentation.

**Comment by stubailo** [comment]
Yep. Hoping to add a system so that people can submit code samples of their own to the docs so that we don't have to do it all the time.

**Comment by bfodeke** [comment]
Is there a way to use an item in the URL as a parameter in a subscription that is placed in the onCreated section? I'm trying to subscribe to a single post _id.

So I'm looking to do something like this:
 Template.example.onCreated(function () {
  var self = this;
  self.subscribe({'posts', this.params._id});
 });

I had something similar to this working in iron-router but can't figure out how to accomplish with template level subscriptions.

**Comment by rclai** [comment]
If you use iron:router, you can do:

```js
Template.example.onCreated(function () {
  var self = this;
  self.autorun(function () {
    self.subscribe('post', Router.current().params._id);
  });
});
```

Also, double-check the way you are calling `this.subscribe`, you were passing in the arguments wrong.

**Comment by bfodeke** [comment]
Aaah, thank you much!

**Comment by stubailo** [comment]
This is done now: https://github.com/meteor/meteor/pull/3962
