### ISSUE TITLE
Spacebars package doesn't provide an escapeExpression method

### ISSUE THREAD

**Issue by iStefo** [meteor/meteor#3960]
**_1 Upvote**_ Learning Meteor after coming from Ember I was already used to Spacebars. Sometimes, I need to augment user-supplied values with little html tag, like `<br/>` between array items etc.. To display them, I wrap the string in `Spacebars.SafeString`, which works as expected.

However, sometimes I need to display user provided data. Using them without previous escape of course opens the application up for XSS attacks, which is why Handlebars comes with `Handlebars.Utils.escapeExpression`.

What I would like to do is:

``` js
var output = new Spacebars.SafeString(
    "<u>" + Spacebars.Utils.escapeExpression(user.email) + "</u>"
)
```

**Edit**: Yes, this could also be done by writing `<u>{{user.email}}</u>` in the template. Image more complex situations like joining lists with `<br/>` etc.

Why are the utils not included in Spacebars? Shouldn't it be as easy as possible for developers to create a secure application? Of course you can rip out the function from [the handlebars source code](https://github.com/wycats/handlebars.js/blob/ab96073c6bfde771dde1e8ff1aa7444192f7f6df/lib/handlebars/utils.js), but that seems unnecessarily complicated. Also, the [Spacebars documentation](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md) mentions the dangers from using `Spacebars.SafeString`, but offers no solution to that problem.

**Comment by iStefo** [comment]
For Meteor developers finding this issue in the future: this is the minimal working "port" of the original `escapeExpression` method: https://gist.github.com/iStefo/61b87ea78a978c90b599

**Comment by glasser** [comment]
I'm not positive (I'm not a blaze expert), but is the solution here to use HTMLJS?  `return HTML.U(user.email)`?

**Comment by iStefo** [comment]
@glasser you suggest manually creating the HTML element in code? I will try this and report if that solves my problem.

**Comment by glasser** [comment]
Hmm, actually I think I'm wrong and you can't return HTMLjs objects from helpers.  Not sure if that was intended or not. https://github.com/meteor/meteor/blob/devel/packages/spacebars/spacebars-runtime.js#L73-L79

**Comment by mattjorn** [comment]
You could use `Blaze._escape(text)` instead (https://github.com/meteor/meteor/blob/devel/packages/blaze/preamble.js at line 8)

**Comment by space-alien** [comment]
+1

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/3960#issuecomment-126464925, you can use `Blaze._escape` to do this. Since Blaze currently depends on underscore, you can also use underscore's [escape](http://underscorejs.org/#escape) function. Either way this issue is a duplicate of meteor/blaze#200, so I'll close this one off. Thanks!
