### ISSUE TITLE
Meteor Deploy Fails

### ISSUE THREAD

**Issue by justindra** [meteor/meteor#3964]
Hi,

I'm receiving this error when deploying to meteor.
````html
Error deploying application: <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
margin: 0;
text-align: center;
}
.meteor {
padding-top: 200px;
padding-bottom: 20px;
height: 142px;
}
.message {
padding-top: 50px;
font-size: 3em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.submessage {
padding-top: 20px;
font-size: 1.5em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.counter {
padding-top: 30px;
font-size: 1em;
color: #aaa;
letter-spacing: -1px;
}

</style>
</head>
<body>
<div class="meteor"><img
src="//warehouse.meteor.com/mother-assets/meteor-logo-final.png"/></div>
<div class="message">
This site is down.
</div>
<div class="submessage">
Try again later.
</div>
<div id="counter" class="counter">
</div>


<script type="text/javascript">
var refreshTime = 0 ;
if (refreshTime) {
var counterDiv = document.getElementById("counter");
var countdown = function () {
if (refreshTime < 1) {
counterDiv.innerHTML =
"Retrying...";
location.reload(true);
} else {
counterDiv.innerHTML =
"Retrying in " + refreshTime + " seconds...";
refreshTime = refreshTime - 1;
setTimeout(countdown, 1000);
}
}
countdown();
}
</script>

</body>
</html>
````
I've tried deploying multiple times with the same result. Not sure what to do here. Any ideas?

Cheers,

Justin

**Comment by jteebs713** [comment]
Hey, this literally just happened to me 10 minutes ago. I cleared up the problem by first running the meteor server in one tab of my terminal and then deploying the project in another tab.

Hope this helps,
Joey

**Comment by dcsan** [comment]
when i deploy i'm getting "this site crashed" on meteor.com

i tried the --patch and also downgrading to version 1.0.4 `METEOR@1.0.4`
oh... 5 mins later it seems to be running. odd backlog at meteor.com?
maybe downgrading helped?

**Comment by dcsan** [comment]
updated to 1.0.4.1 and the deploy crashes again

I also recently added android platforms to my project, wonder if that could be at all related?

**Comment by jteebs713** [comment]
I haven't put in the android part so I can't speak on that.

I now realize that running the meteor server while deploying my app and having it work was probably more of a coincidence than an actual fix.

Definitely bump this to another ticket, I like meteor a lot so I want to see this fully resolved

**Comment by dcsan** [comment]
ref #3974

**Comment by justindra** [comment]
I've recently tried again, after patching the new update and it's worked.

````meteor update --patch````

**Comment by glasser** [comment]
This looks correlated with a brief outage of the free meteor.com deploy servers.

**Comment by isdzulqor** [comment]
anyone have solved this problem? 
I got this problem, too just now...

**Comment by mrgnw** [comment]
For anyone who Googles this in the future, it may be related to Galaxy server issues.
You can check the status of Galaxy at status.meteor.com
