### ISSUE TITLE
adding `force-ssl` to a site with `appcache` breaks clients with a version already cached

### ISSUE THREAD

**Issue by n1mmy** [meteor/meteor#3965]
If you have an app using `appcache`, and a client goes to the site over HTTP, then you add `force-ssl`, and the client returns to the HTTP version of the site, they get stuck on the old version of the site.

This happens because the site tries to fetch http://.../app.manifest and gets a 302 to the https version, which it does not consider valid. Chrome says: "Application Cache Error event: Manifest fetch failed (4)".

Simply allowing `app.manifest` to be served over http is not sufficient, as browsers will still try to request the http version of assets and not follow redirects correctly. Not quite sure why.

It might be sufficient to simply serve a 400 error for app.manifest over http when both force-ssl and appcache are installed. This should cause the site to be un-cached for the http version, then hit /, get redirected to https, then cache the https version.

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers. 

Service Workers are supposed to be the replacement, which is being tracked in #5982.
