### ISSUE TITLE
Template helpers rerun when data context remains the same

### ISSUE THREAD

**Issue by hpx7** [meteor/meteor#3966]
Steps to reproduce:
1.  git clone https://github.com/hpx7/meteor-refiring-issue.git (or go to http://refiring-issue.meteor.com/)
2.  click the button
3.  helpers fired will be printed to the console

In the case of

``` handlebars
{{#with myObject}}
  {{> hello}}
{{/with}}
```

helpers inside the hello template shouldn't rerun if myObject is recomputed but the new value returned by the helper is the same as the old one.

Note that this works correctly (no re-firing) with `#if` instead of `#with`.

**Comment by stubailo** [comment]
It's hard to know if two JavaScript objects are truly equal: http://stackoverflow.com/questions/201183/how-to-determine-equality-for-two-javascript-objects

We could do better in the case of simple objects, however.

--------

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hpx7** [comment]
Are there cases where using `_.isEqual()` won't be sufficient?

**Comment by mitar** [comment]
I think there should be a way to configure which equality one would like. Reference equality, deep equality, etc. Various web frameworks are addressing various aspects here. In some way, one interesting idea is to try to simply do  reference equality, and then require that if there are any changes to the document, that should be propagated by triggering computation invalidation anyway.

**Comment by hwillson** [comment]
I've moved this over to meteor/blaze#169; closing this issue. Thanks!
