### ISSUE TITLE
EJSON issue in 1.4

### ISSUE THREAD

**Issue by navinSing** [meteor/meteor#3969]
livedata_server.js : 1534

RangeError: Maximum call stack size exceeded

due to returning a mongo cursor (inshort EJSON cannot clone a cursor)
this is causing EJSON conversion problem .. was not having this earlier in 1.3

Note : This was an internal method call with Meteor.call()

This is a breaking change and need urgent fix.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Your report doesn't provide enough context to tell what you're talking about.  What is returning a Mongo cursor?  A method?  Is the issue that you expect this to *work* or just that you expect it to *print a better error*?
