### ISSUE TITLE
Meteor run freezes/hangs

### ISSUE THREAD

**Issue by lukavent** [meteor/meteor#3970]
Since the latest meteor updates the app freezes on starting process:
"Building the application                  /"

My Setup
- I'm on Meteor 1.0.4.1 with cordova (android only).
- Ubuntu 14.04.1 LTS
- Vagrant Box with 32bit: Linux ionic-android 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:49:09 UTC 2014 i686 i686 i686 GNU/Linux

The / is even not spinning anymore.

I've tested / checked:
1. Deleting .meteor/local/ folder
2. Killing meteor with "kill -9 `ps ax | grep node | grep meteor | awk '{print $1}'`" stops meteor and it's restartable again without any error message. That means, it doesn't seem to be something with the system itself.
3. Updated NodeJS to v0.10.37
4. Tryed meteor --verbose --raw-logs 
5. Found nothing Logs: syslog
6. Removing all plugins and adding them again for reinstalling them.
7. Removing one plugin by another.
Result was, that it seems to be some kind of issue within build process combined with urigo:angular Plugin. But maybe the build process is simply stopped, because without that plugin errors are thrown, because meteor don't knows how to parse the angular template files.

I've no clue how to get some more detailed informations what and why it's breaking.
I couldn't find any error message.
Anyone any ideas what to check now?

**Comment by glasser** [comment]
That sounds like a bug in `urigo:angular`, or a Meteor bug triggered by it somehow.  You should report it at [its issue tracker](https://github.com/Urigo/angular-meteor); if it turns out to be a Meteor bug, Uri should be able to help you report it here in a way that better matches [our bug reporting guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor).

**Comment by lukavent** [comment]
Okay, we'll see. So far:
For anyone else who maybe also got that issue too. Here's a [link to the issue on urigo:angular plugin](https://github.com/Urigo/angular-meteor/issues/262)

**Comment by lukavent** [comment]
Just for a quick note - we found the reason:
"The issue seems to be with html-minifier, that just hangs when there are certain errors in the file it is proccessing. There are multiple issues on this topic at their repo, e.g [kangax/html-minifier#213](https://github.com/kangax/html-minifier/issues/213)."
