### ISSUE TITLE
[docs] Event maps second argument

### ISSUE THREAD

**Issue by rgoomar** [meteor/meteor#3971]
There is a [post](https://forums.meteor.com/t/hiding-not-removing-content-from-a-collection-the-meteor-way/1669/4?u=rgoomar) that says that the event maps documentation doesn't mention the second argument. After checking it out, it only shows `event` and not the `template` that can be accessed in the next argument.

**Comment by stubailo** [comment]
In general, Spacebars and templates are poorly documented, and a lot of the stuff is hidden in examples or READMEs.

**Comment by hwillson** [comment]
All Blaze related docs are now hosted at http://blazejs.org and have improved significantly since this issue was created. [Event map handler function `template` arguments](http://blazejs.org/api/templates.html#Event-Maps) are now mentioned in the docs, so closing this issue. Thanks!
