### ISSUE TITLE
Missing documentation for archMatching option to Plugin.registerSourceHandler

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#3972]
It isn't in the docs or the [source comments](https://github.com/meteor/meteor/blob/21bdac87347e0c80bbdf4fdbca132ff80033b3f3/tools/isopack.js#L521-L545) that `Plugin.registerSourceHandler` can take an `archMatching` option. The docs don't even reflect the possibility of an options argument at all. Lots of packages follow the lead of the core packages and use the `archMatching` option, it'd be nice to get it documented. Thanks!

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by hwillson** [comment]
Since `Plugin.registerSourceHandler` was deprecated in Meteor 1.2 (the [Build Plugins API](https://docs.meteor.com/api/packagejs.html#build-plugin-api) should now be used instead), I'll close this off. Thanks!
