### ISSUE TITLE
meteor.com sites crash with 1.0.4.1 patch release

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3974]
updated to 1.0.4.1 and deployed to meteor.com, I always get "This site is crashing"
edit `.meteor/release` down to `METEOR@1.0.4`  and can deploy, app runs no problem.
ver bump back up with `meteor update --patch` and get a crashing site again

deploy process runs fine.

I also recently added android (cordova) platform to my project, wonder if that could be at all related?

FWIW when the app is crashing I can't see any new hits with `meteor --logs` so the problem seems to be before whatever hits the app.

**Comment by glasser** [comment]
Your app works on 1.0.4 but not 1.0.4.1?  That's pretty surprising: the only change should be to the `publish-for-arch` command.

`meteor logs APPNAME` should show you the crash message. We'll need that in order to do any debugging.
