### ISSUE TITLE
Update less to version 1.7.5

### ISSUE THREAD

**Issue by vangorra** [meteor/meteor#3975]
Use the latest minor rev of the less library. It supports the /deep/ combinator which is very useful.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I suspect less will get upgraded when we work on [improving the plugin API](https://quip.com/YLcCAxtjuwsL)

**Comment by vangorra** [comment]
I've confirmed this package was updated to the latest version of less.
