### ISSUE TITLE
Feature Request: Allow extra template tag attributes and copy them to the template

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3980]
Template tag parser currently throws errors for any attributes other than `name`. If it allowed extra attributes besides `name` and attached them to the template object for use in code, then packages could support a syntax like:

`<template name="foo" inherits-helpers-from="bar">`
`<template name="foo" replaces="bar">`

That would yield, for example:

``` js
Template.myTemplate.atts.inheritsHelpersFrom = "bar"
```

Which would be a little nicer in some cases where it makes more sense to define such things in the markup versus javascript.

(Copied from discussion in #3706.)

cc @stubailo

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This is a great idea, but will require some thought to implement well, so it probably won't happen right this second.

**Comment by RobertLowe** [comment]
A bit OT, but this *could* allow for polymer style inheritance: 


    <polymer-element name="polymer-cool">
      <template>
        You are {{praise}} <content></content>!
      </template>
      <script>
        Polymer({
          praise: 'cool'
        });
      </script>
    </polymer-element>

    <polymer-element name="polymer-cooler" extends="polymer-cool">
      <template>
        
        <shadow></shadow> 
      </template>
      <script>
        Polymer();
      </script>
    </polymer-element>

`extends` is a nice keyword for example.

**Comment by mitar** [comment]
@stubailo that they would merge this feature in if pull request #4208 is updated to new codebase and pull request feedback comments are addressed. Any takers to create a new pull request?

**Comment by stubailo** [comment]
Important point: we should make the attributes get accessed via a function like `Template.x.getAttribute` and not as a static property, because functions are like 1000 times easier to work with in terms of backcompat.

**Comment by mitar** [comment]
What about maybe just `Template.x.attrs()`?

**Comment by stubailo** [comment]
hmm, that would encourage people to iterate over them. Is that a good thing?

**Comment by mitar** [comment]
I think so. If you do not provide that, then people tend to iterate over internal fields like `__helpers`. ;-)

**Comment by stubailo** [comment]
Sigh. I guess that is true. OK, I'll settle for `getAttributes`.

**Comment by mitar** [comment]
Hm, other method on template instance do not have `get` prefix? `instance`, `currentData`, `parentData`.

(In our internal code style we use `get` prefix when something is hard to compute. Here it is more or less just returning a static value.)

**Comment by stubailo** [comment]
Yeah, that's true. Maybe it's good to stick to the current style. I guess my Java is showing.

**Comment by mitar** [comment]
Yea, we had a long discussion about that when we did Blaze Components and [reactive-fields](https://github.com/peerlibrary/meteor-reactive-field). It is really hard to get away from Java.

**Comment by brylie** [comment]
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment]
Use polymer as the default view layer using mwc:synthesis package 
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#191 - closing here. Thanks!
