### ISSUE TITLE
ClientAddress is sometimes 127.0.0.1

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#3981]
I noticed about 10% of users have 127.0.0.1 instead of their correct IP address.  I added this to see why.

    Accounts.onLogin(function(info) {
        console.log(info.connection.clientAddress);
        console.log(info.connection.httpHeaders);
    })

It looks like x-forwarded-for sometimes has one IP and sometimes two.

    'x-forwarded-for': '50.46.121.xxx'
    'x-forwarded-for': '216.109.8.xxx,127.0.0.1'

When there is one clientAddress is correct.  When there are two clientAddress is 127.0.0.1.

Shouldn't clientAddress always be the correct one?

**Comment by glasser** [comment]
Have you set `$HTTP_FORWARDED_COUNT` to the number of proxies between end users and your app as [described in the docs](http://docs.meteor.com/#/full/meteor_onconnection)?

Meteor does not support calculating `clientAddress` in circumstances where the number of proxies between the user and the Meteor server is not constant.  If you have such a situation, you may need to parse x-forwarded-for yourself (and deal with the possible security implementations of trusting the header).

**Comment by meonkeys** [comment]
I'm seeing this in our production systems, exactly as @dan335 describes. Our Meteor apps sit behind an nginx reverse proxy. I am using `HTTP_FORWARDED_COUNT=1`, and `this.connection.clientAddress` from a Meteor method **usually** returns their IP. When it doesn't, the `x-forwarded-for` header (from `this.connection.httpHeaders['x-forwarded-for']`) contains their IP (matching what we see in the nginx access log), a comma, then `127.0.0.1`. Unfortunately, I can't get an isolated repro of this bug.

**Comment by meonkeys** [comment]
I'm seeing this in our production systems, exactly as @dan335 describes.

My Meteor apps sit behind an nginx reverse proxy. All run with `HTTP_FORWARDED_COUNT=1` set in their environment. All apps are deployed with [mup](https://github.com/arunoda/meteor-up).

`this.connection.clientAddress` from a Meteor method **usually** returns their IP. When it doesn't, the `x-forwarded-for` header (from `this.connection.httpHeaders['x-forwarded-for']`) contains their IP (matching what I see in the nginx access log), a comma, then `127.0.0.1`. Unfortunately, I can't get an isolated repro of this bug.
