### ISSUE TITLE
Briefly explain or link to Fibers in docs

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3982]
http://docs.meteor.com/#/full/ mentions "fiber" four times, but the concept isn't explain. Since Fibers are the mechanism behind an important design decision and a differentiator for Meteor vs. Node-based stacks, it would be helpful to explain the concept.

>  In Meteor, your server code runs in a single thread per request, not in the asynchronous callback style typical of Node. We find the linear execution model a better fit for the typical server code in a Meteor application.

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by hwillson** [comment]
This issue has been moved to meteor/docs#119. Closing here - thanks!
