### ISSUE TITLE
db.obtainWriteLock() fails

### ISSUE THREAD

**Issue by theduke** [meteor/meteor#3987]
I have come upon an issue related to direct database access introduced in #3640.

```javascript
var db = RandomCollection.rawDatabase();
db.obtainWriteLock();
```

This results in an exception: 

```
TypeError: Cannot read property '_isMongo26' of undefined
    at Db.Lock.obtainWriteLock (/home/theduke/.meteor/packages/vsivsi_file-collection/.0.3.3.4zlfxj++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/gridfs-locks/index.js:388:26)
    at repl:1:15
    at /home/theduke/Development/salesroom/salesroom/sr/app/.meteor/local/build/programs/server/shell-server.js:244:23
```

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

It sure looks like your issue depends on the particular version of the `gridfs-locks` package that you're using.  And it doesn't actually look like obtainWriteLock is defined on the database, but on a Lock object, so I don't think the snippet you showed is accurate.

This does not seem to be a Meteor issue to me, but if you can show a real reproduction, we can check again.

**Comment by theduke** [comment]
I will try to reproduce with a clean setup.

I had not considered this to be a contrib package issue, 
still new to diving into issues like this.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and also because the Mongo driver has been updated dramatically since this issue was first reported.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by theduke** [comment]
Not working on Meteor projects anymore.

Sorry for not getting you a more detailed report, though.
