### ISSUE TITLE
Meteor command "meteor mongo [site]" failing toconnect

### ISSUE THREAD

**Issue by jms301** [meteor/meteor#3988]
I'm trying to connect to the mongo database for a site with this command but it fails with: 

connecting to: production-db-d1.meteor.io:27017/audit-thingie_meteor_com
2015-03-21T14:22:37.626+0000 Error: couldn't connect to server production-db-d1.meteor.io:27017 (54.83.1.201), connection attempt failed at src/mongo/shell/mongo.js:148

Is there a problem with the meteor.com mongo severs authentication?

**Comment by jms301** [comment]
This was caused by a wifi blocking ports so PEBKC. Sorry!

**Comment by glasser** [comment]
Glad to hear you got it working!
