### ISSUE TITLE
Meteor Docs like WIkipedia

### ISSUE THREAD

**Issue by engenheiro** [meteor/meteor#3990]
**_1 Upvote**_ Hello, Im new in Meteor and I feel there are so much to know, but the docs is limited. Functions like: "Explain More" to asks to Community and Meteor team to give more Examples and Instructions about one question, and  a "FAQ" about one subject or function. A area with "Tutoriais" with scores and a smart categorization by the Community can be very useful. Linking the docs with the Community, giving reputation points to the users with best solutions can be a good idea. Giving a Tutorials walkthrough to start and advance on Meteor could be great.

**Comment by stubailo** [comment]
+1 there is some discussion here: https://forums.meteor.com/t/good-drop-in-comment-system-for-docs-meteor-com/840

**Comment by mitar** [comment]
Also see this community wiki: http://www.meteorpedia.com/read/Main_Page

**Comment by mitar** [comment]
Also StackOveflow has already "giving reputation points to the users with best solutions can be a good idea".

**Comment by nikhildaga** [comment]
Also, there must be a way to know if some part of documentation has changed. On http://docs.meteor.com/ , there is no way of knowing what documentation has been changed/updated.

**Comment by batjko** [comment]
Check out the Atom Editor's documentation:
http://blog.atom.io/2015/03/11/atom-docs.html

They just reworked it (calling it the Flight Manual now) and it's based on Asciidoc, gets auto-converted into ebook formats and is generally really nice.
It's backed by its own repository to which people contribute.

**Comment by mitar** [comment]
Changes to Meteor docs: https://github.com/meteor/meteor/commits/devel/docs

**Comment by stubailo** [comment]
@mitar nice! I didn't know you could do that on GitHub.

@engenheiro There's one problem with making Meteor Docs like Wikipedia, which is that it will be hard to keep things in sync with the latest version. Right now, we version the docs in the same git repo as the rest of Meteor, so you can go back to a previous version in Git. If we separate the editing of the docs from the code itself, how can we be sure that they are in sync?

**Comment by mitar** [comment]
I think Django really has the best docs around, including nice versioning and nice deprecation warnings.

https://docs.djangoproject.com/en/1.7/

See in the bottom right corner you can switch between versions. You can get also dev version, and stable versions. Really nice.

They keep docs in the main source tree: https://github.com/django/django/tree/master/docs

**Comment by stubailo** [comment]
Does Django have any form of user contribution beyond pull requests?

**Comment by mitar** [comment]
No. But I think good instructions how to edit with GitHub directly would be helpful. Or simply a simple in-Meteor developed app which would use GitHub API to give you an experience of wiki changes, but in fact it would be doing pull requests in the background.

**Comment by stubailo** [comment]
Ooh, that's a very interesting idea. Basically have each part of the docs aware of where it is in the repo, and open a new browser window with a pull request to that section.

**Comment by mitar** [comment]
Yes, or you could even have in-place editing/editor. See example of Grip which is using GitHub API for preview: https://github.com/joeyespo/grip GitHub API allows you to render markdown in a GitHub way.

So I think keeping the documentation together with the version is a very good practice. But you should offer reading old versions of documentation as well (similar to Django). And easy way for people to suggest changes. Maybe something like how Medium has comments on the side. Or Discover Meteor. So one is to change itself. But I think sometimes you are not sure enough to just propose a change. So some discussion about a section could be better. And then it would also be easier to notice which sections of documentation are less clear (because they have more comments/discussion).

**Comment by stubailo** [comment]
Yep, I am very excited to add a comment system to the docs, I think that would be awesome. These are awesome ideas, we should do them ASAP

**Comment by mitar** [comment]
@stubailo: I found this as an example: http://azure.microsoft.com/en-us/documentation/articles/machine-learning-what-is-ml-studio/

Microsoft has its docs on the GitHub. And in the docs they even show all the contributors. Nice touch.

**Comment by stubailo** [comment]
@mitar linking to the right section on GitHub shouldn't take too long, I think! I'll try that.

**Comment by dandv** [comment]
@stubailo: it's this icon:

![image](https://cloud.githubusercontent.com/assets/33569/9248582/bcf67948-4171-11e5-9510-e98ff303d4d9.png)

[Mongo's docs](https://docs.mongodb.org/manual/) have had this for a long while - an edit icon in the upper right that goes to the right file on GitHub.

Meteor's docs are a little more involved though; not sure how easy it will be to direct a user from a method's documentation to the right .md file *and* the source of `{{> autoApiBox`.

**Comment by abernix** [comment]
Docs have their own home now [in a new repo](http://github.com/meteor/docs/) where anyone can contribute changes relatively easily with the **edit on GitHub** link that jumps to that particular section.  I think the only issue left over from this thread is commenting, which the guide itself supports, just not docs.

Are there any other outstanding issues in this that I'm missing before we close this?  I will open a issue on docs about the commenting if that's it.

**Comment by dandv** [comment]
One issue would be the separation between documentation and JSDoc. For example, say I want to add something to [Meteor.wrapAsync](https://docs.meteor.com/api/core.html#Meteor-wrapAsync). Clicking on "Edit on GitHub" leads to [/docs/source/api/core.md](https://github.com/meteor/docs/blob/master/source/api/core.md), where all you can find it

    {% apibox "Meteor.wrapAsync" %}

[I do know how to get at the actual source of the doc, but I worry new contributors might not realize that the documentation comes from the JSDoc linked in the method header, ` (meteor/helpers.js, line 90)`.)

**Comment by abernix** [comment]
Without a clear action item on this anymore, I'm going to close this.  If someone runs into an issue with the confusion of where to make an edit for `apibox` code, they can open an issue on the `docs` repo now – something they couldn't do before.

If anyone has recommendations on how to make it more clear where the edit of JSDoc/`apibox` stuff needs to be done, I think an issue with `docs` would also be appropriate.
