### ISSUE TITLE
Make `this` be `share` in CoffeeScript files in packages

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3993]
**_1 Upvote**_ In packages, there is a `share` variable one can use to make package-level variables. This really makes code ugly, because all package-level variables have to have `share.` before. Often you have global symbols you use a lot in the code.

Why `share` is simply not set as a `this`? There is no reason why `this` would be global scope. This is discouraged anyway. It also makes strange inconsistencies. In browsers `@symbol` is available to the rest of the code because it sets the value on `window`, but on the server side it is not, because it is set inside `vm`. So `@` does not work the same on the client and server.

By making `@` same as `share` it would be easy to make package-level symbols. The issue question is only how to read it inside the nested code which uses `@`. So maybe `share` should simply be a global scope inside a package?

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This would unfortunately be a backwards-incompatible change, right?

Are you suggesting that `share` not exist at all, or just that `@` (at a relatively top-level scope) be a synonym for it?  I definitely think that would be awkward, since then you couldn't access `share` at the non-top level.

So the only advantage to this change would be that in a small subset of the places where you want to use a shared variable (the top-level places where `this` isn't reassigned), you can type 5 fewer characters to refer to them.  But the disadvantage would be now there are two different ways to refer to the same thing, one of which only works in a subset of places.  I'm not a CoffeeScript expert but to me this seems like adding extra confusion just to occasionally save a few characters.

**Comment by mitar** [comment]
> This would unfortunately be a backwards-incompatible change, right?

It could be made as another package?

**Comment by mitar** [comment]
> Are you suggesting that share not exist at all, or just that @ (at a relatively top-level scope) be a synonym for it? I definitely think that would be awkward, since then you couldn't access share at the non-top level.

I think it is OK if `share` continue to exist. So you could define new package-level symbol as:

```
@PackageLevel = 'foobar'
```

And then in another (or that) package use it as:

```
fooBar = ->
  console.log PackageLevel
```

Because it is a global symbol, you would not need to prefix it. It would just work.

In the case when you want to assign to the global symbol, you would have to use `share` though:

```
fooBar = ->
  share.PackageLevel = 'somethingelse'
```

The reason is because otherwise CoffeeScript creates a local variable scoped to the function.

**Comment by mitar** [comment]
So the main advantage is that everywhere where you want to read the global variable, you do not have to use the prefix. So in most cases you do not want to override the global variable anyway. So what I could then do in the package is:

```
@MySpecialUtils =
  awesomeFunction: ->
    console.log "Hello world"
```

And then around my package I can reference this everywhere with simply:

```
MySpecialUtils.awesomeFunction()
```

Instead of:

```
share.MySpecialUtils.awesomeFunction()
```

And this would work both in top-level or deeper scopes anywhere. Only if you would want to assign to `MySpecialUtils` itself you would have to use `share` somewhere in deeper scope. So:

```
share.MySpecialUtils = BetterUtils
```

But if you are not overriding the global variable itself, you can normally use:

```
MySpecialUtils.anotherFunction = ....
```

Everywhere. So in practice, in 99% of cases you will not have to write `share.` prefix anymore. Only if you want to override the global variable itself in deeper scope.

**Comment by glasser** [comment]
Hmm.  I guess I don't understand CoffeeScript as well as I thought I did: all unknown symbols are checked to see if they are fields on `this` when they're read?  I thought that was what `@` was for...

**Comment by mitar** [comment]
> all unknown symbols are checked to see if they are fields on this when they're read?

No, there is no magic like that. Maybe it is unclear, but with the above approach, you can define `@MySpecialUtils` to be a package-level symbol only on the top-level of the file. `@MySpecialUtils` somewhere deeper would assign it to the local `this`.

So `@MySpecialUtils` is the same as saying `this.MySpecialUtils`. There is no special semantic. The issue is that Meteor currently does not seem to handle `this` in any special way, so it is simply `window` in browsers. A global scope. Now, this works, but it is ugly, because you are leaking symbols out of the package.

So locally, in deeper context, writing `MySpecialUtils` would not be searching local `this` if it is not found, but it would simply try to find a globally defined variable. In normal CoffeeScript, because you assigned to `this` on the top-level, which is global scope, that search for `MySpecialUtils` will find it in global scope. Not `this`.

So `@MySpecialUtils` just uses the fact that on the top-level the global scope is same as `this`.

So the question of this ticket is: how we could make so that the global scope of the CoffeeScript code inside a package would be the package itself. No idea if that is really possible though. Now that I am thinking more. :-(

**Comment by Alino** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20%60this%60%20be%20%60share%60%20in%20CoffeeScript%20files%20in%20packages&body=Migrated%20from:%20meteor/meteor%233993) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
I think this is not needed anymore now that CoffeeScript supports exports and imports.
