### ISSUE TITLE
RangeError on deployed Meteor Cordova app

### ISSUE THREAD

**Issue by bastiRe** [meteor/meteor#3994]
I have a hybrid meteor app with Android and iOS clients. The first time after the installation of the app one of these clients connects my server it throws an error and restarts. This is the log that I get:
    
    [Sun Mar 22 2015 03:47:52 GMT+0000 (UTC)] WARNING
    throw(ex);
    ^
    [Sun Mar 22 2015 03:47:52 GMT+0000 (UTC)] WARNING
    /meteor/dev_bundles/0.4.16/lib/node_modules/fibers/future.js:245
    [Sun Mar 22 2015 03:47:52 GMT+0000 (UTC)] WARNING RangeError: Maximum call stack size   exceeded
    [Sun Mar 22 2015 03:47:52 GMT+0000 (UTC)] INFO STATUS running -> starting
    [Sun Mar 22 2015 03:47:52 GMT+0000 (UTC)] ERROR Application crashed with code: 8

After the server has restarted the responsible Cordova client connects fine. It's just the first connection that provokes the restart. It seems to happen before any of my serverside code get's executed.

**Comment by Slava** [comment]
What happened there? Did you resolve it?

**Comment by bastiRe** [comment]
Sorry, forgot to add a comment. The issue seems to be with the raix:push plugin not with Meteor in general.
