### ISSUE TITLE
Feature Request: Android Signing Automation 

### ISSUE THREAD

**Issue by andrewreedy** [meteor/meteor#3995]
Cordova has the ability to use an `ant.properties` file to point to the keystore and alias to use when building an Android app instead of having to go through the steps of signing the app after every build. The `ant.properties` file docs are [here](https://github.com/apache/cordova-android/blob/master/framework/ant.properties#L29-L33).  Also referenced [here](http://www.sencha.com/forum/showthread.php?279994-How-to-Cordova-build-of-an-Android-Release-APK).

The feature request is to include this in the `mobile-config.js` for easy access. 

```
App.buildProperties({
  "key.store": ~/Development/project/myapp.keystore,
  "key.store.password": "secret",
  "key.alias": "My App",
  "key.alias.password": "secret"
});
```

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Feature%20Request%3A%20Android%20Signing%20Automation%20&body=Migrated%20from:%20meteor/meteor%233995) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
