### ISSUE TITLE
Send email with html (file)

### ISSUE THREAD

**Issue by kiide** [meteor/meteor#3997]
Must be easy and cool send an email with html, but html in specific file.

**Comment by theduke** [comment]
Check out https://github.com/meteorhacks/meteor-ssr for rendering Templates on the server, for example for emails.

**Comment by kiide** [comment]
Yes, i am using it. But i think that this feature must be native in Meteor.

**Comment by ekatek** [comment]
This sounds like something that is best done by a community package. Meteor provides the building blocks for this -- custom templates, sending html emails, and the assets API. You can browse the Meteor package ecosystem here: https://atmospherejs.com/.

**Comment by kiide** [comment]
Yes, yes, I'm using one of the packages, it is very good :). It is something that I realized the meteor is that, it is really very simple and already gives you several things incredibly ready (multiple authentications, an email service - mailgun, deploy, among others ...) and other features coming being implemented, because standard and turned several apps use.

Also, do this:

![image](https://cloud.githubusercontent.com/assets/5432753/6840520/70ab35ba-d358-11e4-8010-8ac14f70ac8f.png)

É melhor e é muito mais elegante do que:

![image](https://cloud.githubusercontent.com/assets/5432753/6840528/a1dd4cf4-d358-11e4-885e-3f9681012b91.png)

or: 

![image](https://cloud.githubusercontent.com/assets/5432753/6840531/abfc8eca-d358-11e4-9dec-9413c3b86079.png)

Because having only <p> welcome </ p> and not 'welcome.html'?
