### ISSUE TITLE
"meteor mongo" command does not work with non-English folder path

### ISSUE THREAD

**Issue by hatsevich** [meteor/meteor#3999]
the same problem as https://github.com/meteor/windows-preview/issues/40#issue-55247356 but on Mac:

following the tutorial https://www.meteor.com/try/3 on step 3
opened a new terminal tab and typed "meteor mongo" in the project folder
got "mongo: Meteor isn't running a local MongoDB server."
although I have the Meteor sample app running in the other tab

I figured out that the problem was because the path to the app folder contained a folder named with Russian letters. After I moved the app to a folder with only-English-letters path, the error disappeared.

**Comment by glasser** [comment]
@hatsevich Thanks, that does seem like it could be a bug. Can you show an example of a path name that has this issue?  I bet we have an encoding error in our `findMongoPids` function.

**Comment by hatsevich** [comment]
@glasser 
Any Russian-lettered name, e.g. "метеор"

>~/d> cd метеор
>~/d/метеор> meteor
>[[[[[ ~/D/метеор ]]]]]                        
>
>=> Started proxy.                             
>=> Started MongoDB.                           
>=> Started your app.                          
>
>=> App running at: http://localhost:3000/

In another tab:
>~/d> cd метеор
>~/d/метеор> meteor mongo
>mongo: Meteor isn't running a local MongoDB server.

**Comment by hatsevich** [comment]
By the way: why is Preview feature absent when I edit a comment here? Is it a github bug?

**Comment by glasser** [comment]
Thanks, the problem seems to be that `ps` on some platforms corrupts characters such as т.

**Comment by glasser** [comment]
OK, this fix took me a little longer than I thought it would, and also unearthed some possible Windows issues.  Under review at https://rbcommons.com/s/meteor/r/32/
