### ISSUE TITLE
problems with App.launchScreens (mobile-config.js:undefined)

### ISSUE THREAD

**Issue by williamli** [meteor/meteor#4003]
according to the docs, the following are supported

// iphone
// iphone_2x
// iphone5
// iphone6
// iphone6p_portrait
// iphone6p_landscape
// ipad_portrait
// ipad_portrait_2x
// ipad_landscape
// ipad_landscape_2x
// android_ldpi_portrait
// android_ldpi_landscape
// android_mdpi_portrait
// android_mdpi_landscape
// android_hdpi_portrait
// android_hdpi_landscape
// android_xhdpi_portrait
// android_xhdpi_landscape

In my test, having
android_xhdpi_portrait
android_hdpi_portrait
android_mdpi_portrait
iphone6p_portrait

will result in a  'mobile-config.js:undefined' error

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by asadiqbal389** [comment]
i m facing same problem....Can anybody help

**Comment by stubailo** [comment]
It's hard to help without having all of the info. Please submit a reproduction in the form of an app. One possible issue is if your mobile-config.js is not at the root of the app.
