### ISSUE TITLE
Template instance setTimeout and setInterval

### ISSUE THREAD

**Issue by matb33** [meteor/meteor#4005]
To round out the inclusion of template instance reactive vars and template instance subscriptions, I think it would make sense to offer a `Template.instance().setTimeout` and `Template.instance().setInterval`, who are automatically cleared on template destroyed.

I've used `setTimeout` on `rendered` often enough, such as adding classes to elements in order to have them animate in a staggered fashion. It would be very handy for meteor to clear these timeouts if I happen to destroy the template before all timeouts have fired (possibly trying to add a class to a node that has already been removed from the DOM).

**Comment by rclai** [comment]
To account for any possible additional things to attach to template instances, it would be nice to have an official global template `Template.on<Event>(function () { });` like the one implemented [here](https://github.com/aldeed/meteor-template-extension/#templateoncreated--templateonrendered--templateondestroyed).

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

It would be good for people to be able to extend template instances easily to do new things.

**Comment by mitar** [comment]
Interesting idea.

**Comment by hwillson** [comment]
I've created meteor/blaze#162 to track this; this issue can be closed. Thanks!

**Comment by mitar** [comment]
Thanks!
