### ISSUE TITLE
Property named created will be ignored and handled incorrectly in 1.0.4.x

### ISSUE THREAD

**Issue by laddi** [meteor/meteor#4006]
After updating to Meteor 1.0.4.2 we noticed an error in the browser console stating that Template.xxx.created was deprecated and we also got an error in a template helper.  We managed to find out that this was caused by a property of a JSON object in Mongo that had the name 'created' and when we tried to traverse data with it, we always got this error.  Changing to this.created fixed the problem but we were surprised that the order of lookup in the template seems to be reversed since we encountered this inside an {{#each}}.

You should probably look into this as this is a definite regression since 1.0.3.x.  We suspect the same applies to properties named rendered and destroyed.

**Comment by Slava** [comment]
As a person who worked on `rendered` callbacks, I would like to look at this. To make sure, I understand the issue, do you have any simple example apps that can demonstrate the issue?

**Comment by laddi** [comment]
Sadly, no.  Our project is pretty big and not open source so I don't really have an example of this behavior.

**Comment by abernix** [comment]
Going to close this as the deprecation happened quite some time ago and this doesn't seem to have got much traction.  Happy to reopen with a reproduction that the problem still exists.
