### ISSUE TITLE
Public folder doesn't work properly.

### ISSUE THREAD

**Issue by nickanastasov** [meteor/meteor#4007]
Hello Meteor,
I am trying to save an image with CollectionFS into a public folder. So i used <code>process.env.PWD</code> to find the current working directory. But then in the JavaScript console i get an error " process is not defined ". So my idea is that i can't save an image to the public folder because it says that i don't have that permission tho. Can you help me please?

Nick

**Comment by ekatek** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

Additionally, collectionFS is not maintained by Meteor Development Group -- its repository here: https://github.com/CollectionFS/Meteor-CollectionFS.

Lastly, it sounds like you might be trying to use `process.env.PWD` on the client. I don't think that's going to work out -- `process` is part of the node server, and not accessible on the client. You might want to try something else.
