### ISSUE TITLE
Meteor packaged underscore should use Meteor.setTimeout instead of setTimeout

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4012]
Meteor packaged underscore should use `Meteor.setTimeout` instead of `setTimeout`. This could be implemented by doing `var setTimeout = Meteor.setTimeout` in `pre.js` in the package. (And similarly for other timer-related functions.)

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this does make sense, though I'm not positive what all the implications are.  (eg, I'm not sure that the `_.throttle` logic is correct when the function can yield; using setTimeout ensures that it isn't allowed to yield.)

**Comment by mitar** [comment]
But currently it is using `setTimeout` which does not assure any Meteor semantics. By replacing them with `Meteor.setTimeout` you would get those semantics.

**Comment by glasser** [comment]
`setTimeout` means that you can't run code that expects to be able to yield in it, which is a shame, but is better than running code that can yield but breaks the semantics of `_.throttle`.

**Comment by mitar** [comment]
So maybe then `setTimeout` should be replaced with version of `Meteor.setTimeout` with no yields allowed check.

**Comment by glasser** [comment]
I mean, isn't that basically the same as ... not jumping through all the hoops and overhead of creating a Fiber that you then immediately ban from yielding?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20packaged%20underscore%20should%20use%20Meteor.setTimeout%20instead%20of%20setTimeout&body=Migrated%20from:%20meteor/meteor%234012) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
