### ISSUE TITLE
scripts/generate-dev-bundle.sh stops building meteor@1.0.4.2

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4013]
Hi, as I am supporting the [meteor universal fork](https://github.com/4commerce-technologies-AG/meteor) for meteor on ARM architectures,  I run in same error as already mentioned in #3943. The bundler stops when trying to optimize the node_modules.

```bash
(code line 155:156)
pushd cordova/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify/node_modules
delete browserify-zlib/node_modules/pako/benchmark
delete browserify-zlib/node_modules/pako/test
```
The problem is, that the latest PAKO npm does not contain `benchmark` and `test` folder anymore.

I would suggest, that the `delete()` function should NOT `exit 1` if path to clean does not exist. So I prefer to modify it like:

```bash
# Used to delete bulky subtrees. It's not an error anymore but WARNING if they
# don't exist, because that might mean it moved somewhere else and we should
# update the delete line.
delete () {
    if [ ! -e "$1" ]; then
        echo "WARNING! Nothing to clean anymore. Missing or moved?: $1"
    else
        rm -rf "$1"
    fi
}
```

It is just "optimizing" unnecessary folders but should not break generator.

Cheers
Tom

**Comment by avital** [comment]
Thanks. We made this intentional, so we catch these changes. I just made this change on the avital-dev-bundle-fstream branch. I'll cherry-pick it to devel.

**Comment by avital** [comment]
(I don't think we'd notice if it were a warning since we build dev bundles on a build machine and we generally don't inspect the output unless it fails)

**Comment by TomFreudenberg** [comment]
Hi Avital, I would suggest to change `delete()` method in any case. In case of a stable meteor release it could (would?) happen that the npm module contents can change AFTER your stable release date. In that case the `generate-dev-bundle.sh` will break always after a few time.

So from my point of view, you should not `exit` only for optimization.

Cheers

**Comment by glasser** [comment]
You're right; we should be checking in shrinkwrap files.

That said, the whole point of having prebuilt dev bundles is to guarantee that everyone sees the same versions.  This is only really a problem for people using unsupported platforms, or if npm decides on different module versions for different platforms being built at the same time (actually quite possible...)

**Comment by TomFreudenberg** [comment]
I pushed this to my fork, maybe just a starting point for you to discuss

https://github.com/4commerce-technologies-AG/meteor/commit/339957dd3da81c1b124e3c96db3968c46bdd3523

**Comment by glasser** [comment]
No, as @avital says, we will never see those warnings.

The real improvement here would be to save npm-shrinkwrap files for consistency.

**Comment by TomFreudenberg** [comment]
Question is why you take so much attention on some of the cleanups?

Some cleanups you do by `delete method` and they may stop the script like e.g.

```bash
delete browserstack-webdriver/docs
delete browserstack-webdriver/lib/test
delete sqlite3/deps
delete wordwrap/test
delete moment/min
```

but others you just optimize by find and those will ignore missing files

```bash
# dedupe isn't good enough to eliminate 3 copies of esprima, sigh.
find . -path '*/esprima/test' | xargs rm -rf
```

What makes the difference if you have a fail while optimizing `sqlite3/deps` or `esprima/test`.

From my point of view you may ignore any of those _not longer existing files_ and just proceed with the script. Pay attention on a warning or not ... you may decide.
