### ISSUE TITLE
android crashes

### ISSUE THREAD

**Issue by chovy** [meteor/meteor#4018]
```
$ meteor run android
Starting android emulator
[[[[[ ~/projects/simple-todos ]]]]]

=> Started proxy.
=> Started MongoDB.
Unexpected exit code 1 from /Users/username/.meteor/android_bundle/android-sdk/tools/emulator [ '-avd', 'meteor' ]
stdout:
 emulator: Failed to sync vcpu reg

emulator: Failed to sync HAX vcpu context


stderr:
 HAX is working and emulator runs in fast virt mode
```

I had some issues before using cordova. I had installed android-sdk from brew, but I removed that and it just crashes for me when I run the meteor command.

**Comment by glasser** [comment]
Hmm.  http://stackoverflow.com/questions/17024538/how-do-i-fix-failed-to-sync-vcpu-reg-error suggests that you may have been running other VMs, like "genymotion", on your computer. Is that the case?

**Comment by JulianNorton** [comment]
Mine crashed as well. I don't have another VM or genymotion.

**Comment by steowens** [comment]
Same here

**Comment by martijnwalraven** [comment]
This seems like an issue with the Android emulator and not something we can fix from Meteor.
