### ISSUE TITLE
Incorrect Mime type in Android app

### ISSUE THREAD

**Issue by dkouvdis** [meteor/meteor#4020]
Hi.

I am not sure if this issue is related to compiling the app to Android or I should chase the package developer.

I am using the fontawesome package, it works fine on **web browser**. In the Android app, I noticed the css file from the CDN are returning 404 because of the mime type

See this issue
https://github.com/nate-strauser/meteor-font-awesome/issues/24#issuecomment-86007222

ps: Please ignore all other comments, focus on this comment I have referenced.

pss: Sorry if I wasted your time if its not related.

**Comment by glasser** [comment]
I don't think it's because of the MIME type; I think it's because of the fact that it's getting a 404 error.

As of Meteor 1.0.4, Cordova mobile apps need to declare which domains they fetch content from, for security reasons.  See https://docs.meteor.com/#/full/App-accessRule
