### ISSUE TITLE
I can't understand how can i reach to the public folder.

### ISSUE THREAD

**Issue by nickanastasov** [meteor/meteor#4022]
Hello, 
Please tell me how can i reach to the public folder of the project. This is something that meteor doesn't tell people. Because it's really annoying to log and search folder by folder to find where "Meteor" should have put it. So please help!

-Nick

**Comment by batjko** [comment]
Can you clarify what you're looking for and where?

By default, Meteor doesn't create the Public folder for you. You are expected to create your own folder structure (e.g. manually, or by using a [boilderplate](http://bit.ly/1NgeOAq)).

**Comment by ganySA** [comment]
just make one!

**Comment by nickanastasov** [comment]
I want to save an image which is sent by a client. Everything is done but I want my page to refresh because Meteor refreshes when something is changed in the public folder. So when I deploy my app in Meteor I can't find this specific public folder.

**Comment by batjko** [comment]
So you don't normally save a file sent by the client inside of your code
base. The public folder (if you create one for yourself as mentioned) is
not meant for that, but rather to hold assets thast you use to generate the
page(s).

Can you show the code you're using to upload your file?

**Comment by nickanastasov** [comment]
On the server: 

<code>
Meteor.methods({
		addEventStream: function (text, fileInfo, fileData) {

			// Make sure the user is logged in before inserting a task
			if (! Meteor.userId()) {
				throw new Meteor.Error("not-authorized");
			}

			return Streams.insert({
				text: text,
				imagePath: "",
				createdAt: new Date(),
				owner: Meteor.userId(),
				username: Meteor.user().username
			}, function (err, id) {

				if (!err) {
					if(fileInfo && fileData) {

						var imagePath = '/uploads/image-' + id + '-' + fileInfo.name;

						fs.writeFile(process.env.PWD + '/public' + imagePath, fileData, {encoding: 'binary'});

						Streams.update(id, {$set: {imagePath: imagePath}});
					}
					return id;
				}
			});

		}
	});
</code>

On the client:
<code>
var reader = new FileReader();

				reader.onload = function () {
					var dataUrl = 'data:image/jpeg;base64,'+btoa(reader.result);

					localStorage.setItem('tempImage', dataUrl);

					Meteor.call('addEventStream', text, file, reader.result, function(err,id){
						Session.set("selected_item", id);
					});

				};
				reader.readAsBinaryString(file);
</code>

Hope this help you to find where is my problem. 

--Nick

**Comment by batjko** [comment]
And the error you're getting if at all? Any console output?

**Comment by nickanastasov** [comment]
No there is no error. But when i try to go http://<my_app_name>.meteor.com/uploads/image-<id>-<filename>. It doesn't find it.

**Comment by batjko** [comment]
So you're trying to save it to `[process.env.pwd]/public/uploads/`...

I'm not an expert, but the first thing that jumps to mind on the server part is that `process.env.pwd` may not be what you think it is:
![image](https://cloud.githubusercontent.com/assets/7287076/6846685/fbe6174e-d3b7-11e4-8ac6-c7309747ae2c.png)

Others can probably comment on the rest, but if I were you, I'd look at what others have already done:
e.g.: http://inversekarma.in/technology/howto/uploading-files-in-nodejs-express-4-using-formidable/

**Comment by nickanastasov** [comment]
Thanks a lot. But I need to make it just as simple as mine without any other packages. So what command you think I should use? <code>process.env.home</code> is not working too. :(

**Comment by batjko** [comment]
Sorry, my Meteor-Fu is very basic.
But check out what this guy has done:
https://github.com/tomitrescak/meteor-uploads

On a basic level, his server-side looks like this:

```javascript
UploadServer.init({
    tmpDir: process.env.PWD + '/.uploads/tmp',
    uploadDir: process.env.PWD + '/.uploads/',
    checkCreateDirectories: true,
    getDirectory: function(fileInfo, formData) {
      if (formData && formData.directoryName != null) {
        return formData.directoryName;
      }
      return "";
    },
    getFileName: function(fileInfo, formData) {
      if (formData && formData.prefix != null) {
        return formData.prefix + '_' + fileInfo.name;
      }
      return fileInfo.name;
    },
    finished: function(fileInfo, formData) {
      if (formData && formData._id != null) {
        Items.update({_id: formData._id}, { $push: { uploads: fileInfo }});
      }
    }
  });
```

**Comment by nickanastasov** [comment]
It doesn't help me. I tried to make <code>/.uploads/</code> folder but it didn't give me because no access i guess. So I am really tired of Meteor. :(

**Comment by batjko** [comment]
So it seems your problem is [not uncommon](https://medium.com/@victorleungtw/how-to-upload-files-with-meteor-js-7b8e811510fa
).
    The file upload feature works fine on localhost, but it doesn’t work once it is deployed to the free meteor testing server. 


So it seems there is a cross-domain security issue you need to get around. And the author suggests a solution, using the `cfs:gridfs` package.

No idea if you can replicate that without using any third party package.


He's a solution

**Comment by nickanastasov** [comment]
Yeah this is very good. Thanks a lot! But I need to save on the server not into MongoDB because this will be tutorial hosted on Heroku(MongoDB - 500MB Max) and if each of 250 people uploads a 2MB image the database will be full. I hope you are not angry at me. I searched a lot too for about 3 days and I can't find what I need. I think my last and only option is to wait until Meteor fix this thing.

**Comment by awatson1978** [comment]
@nickanastasov - Hi!  Your question is probably a better fit for [forums.meteor.com](http://forums.meteor.com) than the github issues tracker, which is mostly focused on tracking bugs.  That being said, you may find this article on file-uploads to be helpful.  

https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook/file-uploads.md

**Comment by glasser** [comment]
I agree with @awatson1978: "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

(Typically, if you're trying to save uploads, the source tree isn't the right place to do it.  Honestly, in 2015, I think the best way to handle uploads doesn't involve writing to the local disk of whatever machine the server happens to be running on right now, because typically you'll want to run servers on lots of machines to scale!  I'd probably upload images to something like Amazon S3, or even easier, something like filepicker.com.)
