### ISSUE TITLE
error when updating meteor from dev-bundle (tools/watch.js)

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4023]
YOU MAY IGNORE THIS COMMENT AND START OVER WITH MY SECOND COMMENT.

---

Hi,

I am working on meteor universal fork to run meteor on yet unsupported architectures. At least all works fine but this when running meteor from a checkout and want to install a dev-bundle. It must be said, that the non-core packages should be linked to `packages` so that e.g. `npm-bcrypt` can be used:

```
  cd <your checkout path>
  ln -s packages/non-core/npm-bcrypt packages
```

Steps to reproduce error:

```
  cd <your checkout path>
  # clearing .meteor
  rm -rf .meteor
  # drop previous dev-bundle
  rm -rf dev_bundle
  # get meteor --version to install new dev_bundle and check environment
  meteor --version
```

After some time follwing error occurs:

<pre>
/usr/local/lib/meteor/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: ELOOP, stat '/usr/local/lib/meteor/packages/npm-bcrypt'
    at Object.Future.wait (/usr/local/lib/meteor/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as stat] (/usr/local/lib/meteor/tools/files.js:1330:24)
    at /usr/local/lib/meteor/tools/watch.js:265:25
    at Array.forEach (native)
    ...
</pre>

The problem is based inside `tools/watch.js` method `readDirectory()`.

**`var stats = files.stat(files.pathJoin(options.absPath, entry));`**

```javascript
var readDirectory = function (options) {
  // Read the directory.
  try {
    var contents = files.readdir(options.absPath);
  } catch (e) {
    // If the path is not a directory, return null; let other errors through.
    if (e && (e.code === 'ENOENT' || e.code === 'ENOTDIR'))
      return null;
    throw e;
  }

  // Add slashes to the end of directories.
  var contentsWithSlashes = [];
  _.each(contents, function (entry) {
    try {
      // We do stat instead of lstat here, so that we treat symlinks to
      // directories just like directories themselves.
      // XXX Does the treatment of symlinks make sense?
      var stats = files.stat(files.pathJoin(options.absPath, entry));
    } catch (e) {
      if (e && (e.code === 'ENOENT')) {
        // Disappeared after the readdir (or a dangling symlink)? Eh,
        // pretend it was never there in the first place.
        return;
      }
      throw e;
    }
    if (stats.isDirectory())
      entry += '/';
    contentsWithSlashes.push(entry);
  });
```

Funny thing: this is also documented in your own (MDG) comment

> // XXX Does the treatment of symlinks make sense?

From my point of view and in case of this error: NO, makes no sense ;-)

But coming back to be serious, this error would not be raised if using `files.lstat`.

Question: What conditions has to be that `files.stat` is the right call ?
 
Could you change it to `files.lstat()` ?

Thanks for feedback.

**Comment by TomFreudenberg** [comment]
Hi, sorry but changing to `files.lstat` is not the solution, it just moves the problem to somewhere else ;-)

The real problem are the both non-core jquery packages `jquery-history` and `jquery-layout`. When cleaning `dev_bundle` and `.meteor` folders and run `meteor update` for fresh dev_bundle installation following error occurs:

<pre>

=> Errors while scanning core packages:

While reading package from `/usr/local/lib/meteor/packages/jquery-history`:
error: packages in isopackets may not use versionsFrom

While reading package from `/usr/local/lib/meteor/packages/jquery-layout`:
error: packages in isopackets may not use versionsFrom


/usr/local/lib/meteor/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: isopacket scan failed?
    at newIsopacketBuildingCatalog (/usr/local/lib/meteor/tools/isopackets.js:227:11)
    at makeIsopacketBuildContext (/usr/local/lib/meteor/tools/isopackets.js:234:17)
    at /usr/local/lib/meteor/tools/isopackets.js:159:35
    at Function._.each._.forEach (/usr/local/lib/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /usr/local/lib/meteor/tools/isopackets.js:133:9
    at /usr/local/lib/meteor/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/usr/local/lib/meteor/tools/fiber-helpers.js:115:14)
    at /usr/local/lib/meteor/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/usr/local/lib/meteor/tools/fiber-helpers.js:115:14)
    at /usr/local/lib/meteor/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/usr/local/lib/meteor/tools/fiber-helpers.js:115:14)
    at /usr/local/lib/meteor/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/usr/local/lib/meteor/tools/fiber-helpers.js:115:14)
    at Object.capture (/usr/local/lib/meteor/tools/buildmessage.js:245:19)
    at /usr/local/lib/meteor/tools/isopackets.js:132:25
    at [object Object]._.extend.withProgressDisplayVisible (/usr/local/lib/meteor/tools/console.js:612:14)
    at Object.ensureIsopacketsLoadable (/usr/local/lib/meteor/tools/isopackets.js:131:26)
    at /usr/local/lib/meteor/tools/main.js:736:30
</pre>

Both packages contains an `api.versionsFrom` code line

```
packages/non-core/jquery-history/package.js:  api.versionsFrom('1.0');
packages/non-core/jquery-layout/package.js:  api.versionsFrom("1.0");
```

Is there something necessary to correct? I am not in knowledge currently if those key is important to that package or not.

Thanks for feedback.

**Comment by TomFreudenberg** [comment]
Hi, I checked via grep the complete meteor source tree and didn't found any suitable sense, why this info about `api.versionsFrom()` has to be in that two non-core packages. So I decided to comment them out out for my for fork.

I would really love to get a few words from you about that and if you can agree.

Thanks
Tom

**Comment by glasser** [comment]
I'm pretty confused about what you're reporting here.  But one thing that really confuses me is the path `/usr/local/lib/meteor/packages/jquery-history` in an error message.  How did jquery-history get directly under packages instead of under `non-core`?  You symlinked it there, I think?

I don't know why you felt that the non-core packages should be put under core, but, well, they were removed from core for a reason.  I'm not sure that "errors occur when you revert changes we made" is a Meteor bug.

**Comment by TomFreudenberg** [comment]
Hi David, sorry confusing you ;-) that was not intended.

You are right, I have symlinked the non-core packages to core to make them available to projects. As I asked already on forum https://forums.meteor.com/t/missing-non-core-packages-when-running-meteor-from-checkout/1140 I could not get information about the "right way" in using non-core packages.

What do you advise to do for getting run e.g. meteor examples todos when using dev_bundler? 

Thanks for some clarification and help.
Tom

**Comment by TomFreudenberg** [comment]
Hi David ( @glasser ), sorry confusing you ;-) that was not intended.

You are right, I have symlinked the non-core packages to core to make them available to projects. As I asked already on forum https://forums.meteor.com/t/missing-non-core-packages-when-running-meteor-from-checkout/1140 I could not get information about the "right way" in using non-core packages.

What do you advise to do for getting run e.g. meteor examples todos (npm-bcrypt) when using dev_bundler? 

Thanks for some clarification and help.
Tom

**Comment by glasser** [comment]
If you need to use them in apps, you can put them in your app's package directory, or put them in `$PACKAGE_DIRS`.  (The latter is maybe the easiest to do for your unofficial port.)  The git checkout's packages directory is treated specially and packages there have to obey some extra constraints.

**Comment by TomFreudenberg** [comment]
Hey David, thanks. Looking long time for an answer to that. I will update my documentation about that and follow your advise. 

Last question please: What do mean exacly with _"put them in your app's package directory"_ ?

Create a link to meteor checkout directory or create a copy of that directories? When creating copies you must take care on updates?

Tom

**Comment by glasser** [comment]
I mean, if I understand properly, your issue is: you have an unsupported port, and you'd like users to be able to use some Atmosphere packages which have binary dependencies which you don't have the ability to publish builds of.  And well, that means they need to be built from source within the user's apps.  For a system wide installation like yours, the app's `packages` directory isn't relevant.

(I hope at some point in the future, we change our approach to binary packages so that the pre-published build is an optimization that allows users without build tools installed to use binary packages, but that it can fall back to trying a local build if you're on a platform where the binary package hasn't been published.)

**Comment by TomFreudenberg** [comment]
When running from checkout you even can't run the latest official todos example because this needs the npm-bcrypt package.

But as I got it correct from your advise, I should set e.g. `export PACKAGE_DIRS=/usr/local/lib/meteor/packages/non-core` and then start my meteor app.

**Comment by TomFreudenberg** [comment]
Hi David ( @glasser )

setting the export var `$PACKAGE_DIRS` works as expected.

I really can't understand why you decide to move this 4 packages into `packages/non-core` when running from checkout but put them directly into `packages` folder when running your installer. Also I am wondering why there is the package `npm-node-aes-gcm` missing completly when using the installer.

Why do make that difference to the packages? There are no technical issue in using them also in the checkout environment.

Thanks in advance for some clarification
Tom

**Comment by glasser** [comment]
Tom, if you're referring to `~/.meteor/packages`, all packages end up there (core or downloaded from Atmosphere).

These few packages are just non-core packages like any other packages, which happen to be either formerly core packages, or dependencies of core packages.

**Comment by TomFreudenberg** [comment]
Hi David, I am referencing only to checkout packages from https://github.com/meteor/meteor/tree/devel/packages. What I do not understand is, why do you deliver especialy these 4 packages at https://github.com/meteor/meteor/tree/devel/packages/non-core? I mean if there are not important than anybody could install them from atmosphere later or if they are more important why not equal them to the others onboarded packages. I am sure I miss something but currently I can't get it.

Thanks for you patience and help
Tom

**Comment by glasser** [comment]
Mostly historical reasons.  Note that *all* packages can be installed from atmosphere once you have the tool; we include core packages in the bootstrap tarball to make it so the install process gets you most of what you need for your first app!

**Comment by TomFreudenberg** [comment]
Ok, it absolutly makes sense to deliver a number of packages within the meteor tarball but why include those 4 into the tarball but cannot use them without special action / settings? if you mentioned "historical", do you think that these packages will be rejected from the tarball in the next time?

**Comment by glasser** [comment]
Tom, you're wrong that you can't "use them" without special action/settings.
You can't *add them to the source tree* without special action/settings.

Nobody told you to add them to the source tree.  There's a difference between package source and a built unipackage.

Look, at the end of the day, we've made the decision to only support a fixed set of platforms.  Supporting new platforms is a lot of work — Windows (which we are releasing soon) took months of full-time work by multiple engineers.

I'm sorry to hear that your attempts to get our project to work on other platforms aren't going so well, but at the end of the day, this is why we make choices about what platforms are supported and what aren't.

**Comment by TomFreudenberg** [comment]
Ah .... that was my mistake ... not to differ between package source and already built unipackages! I thought in any case you will download the source of a package and build it on the destination, but they already pre-built. So now I understand why `meteor add npn-bcrypt` will com up with an error 

```
=> Errors while adding packages: 
While checking for npm-bcrypt@0.7.8_1:
error: No compatible build found
```

Thanks for that missing piece, David!

----

Btw. you don't have to be sorry, the meteor is performing and running absolutely well. No problems, no (more) bugs, everything is like on x86 machines as well. I worked with the universal fork on hacker boards of UDOO, Raspberry Pi B and 2, Beaglebone and pcDuino. They were all running a Debian based OS like Debian itself, Raspbian or mostly Ubuntu. I made Ubuntu core 14.04 LTS up on any board and meteorjs is doing like a charm. From my point of view those ARM environments are nearly 100% stable. The main pain ist to setup nodejs and mongodb well for your OS. If you are using an up-to-date OS like we do with Ubuntu core 14.04 it is really just `apt get install node mongodb` and then doing the installation for the universal fork like described. If you like, try it once yourself, you can use my pre-built archives for a very quick installation on Raspi or Udoo ;-)

So for now, thanks a lot for your patience and answers. I am fine with it.

Cheers David, have a nice weekend.
Tom
