### ISSUE TITLE
xcdatamodeld not copied from Cordova plugin

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [meteor/meteor#4024]
I have made a Cordova plugin to use a library that I have created for Android and iOS. I want to use it in my Meteor project, but the xcdatamodeld file for the iOS platform is missing when the plugin is installed... Here is what I have tried.

If I create a brand new Cordova project, add the ios platform, add my plugin to it from a url that downloads a tarball from bitbucket and then create the XCode project from it with `cordova prepare`, I will get a XCode project that has the xcdatamodeld file (because I added the `<source-file src="path/to/my.xcdatamodeld" />` in the plugin.xml file of my Cordova plugin).

But if I add my plugin the same way (from a tarball url) in my meteor project, the generated XCode project will be missing the xcdatamodeld file... I still don't know why, but I found that if I just copy the xcdatamodeld file from the project generated from Cordova to the project generated from Meteor, my plugin will work. But I need to do this every time I rebuild the XCode project from Meteor...

I am using Cordova version 4.3.0 and Meteor version 1.0.4.2

**Comment by glasser** [comment]
Hmm.  I'm not an expert on how Cordova plugins work.  Is this issue specific to "from a tarball URL" or does it also happen if you publish the plugin?  Can you create a reproduction so we can test this out, maybe with a stripped-down test plugin that just demonstrates the issue?  See https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by RaphaelRoyerRivard** [comment]
I also found that building the project with `meteor run ios-device` will not copy the xcdatamodeld file, but building with `meteor build <path> --server <remote_host> will copy the xcdatamodeld file exactly like a pure Cordova build would do.

I will create a a stripped-down test plugin if I find time to do so.
