### ISSUE TITLE
How to add prefix to main js and css in production

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4025]
I want to have my meteor application as the origin for Amazon CloudFront so a request goes to the CDN, if it doesn't have the asset then it requests it from my app and caches it at the CDN.

One question. How to change this in `<head>`:

```
/35cf1e1b9d95159941d0e60393b0da5534f8d0ba.js
/9043af6b130558cf9639bde8ff5504b62864f69e.css
```

...to something like:

```
//my.cdn.provider.com/35cf1e1b9d95159941d0e60393b0da5534f8d0ba.js
//my.cdn.provider.com/9043af6b130558cf9639bde8ff5504b62864f69e.css
```

?

**Comment by artpolikarpov** [comment]
Thanks to [meteorhacks:inject-initial](https://github.com/meteorhacks/meteor-inject-initial), it is possible with this lil script on the server:

```js
var assetsHost = _._property(Meteor, 'settings.public.assetsHost');

if (assetsHost) {
    console.log('assetsHost', assetsHost);
    Inject.rawModHtml('assetsHost', function(html) {
        return html.replace(/((src|href)=("|')?)\//g, '$1' + assetsHost + '/');
    });
}
```

Are there better ways around?

**Comment by Slava** [comment]
I think you can set an assets prefix calling a WebApp method: `WebAppInternals.setBundledJsCssPrefix(prefix)`

**Comment by artpolikarpov** [comment]
@Slava, wow!

**Comment by artpolikarpov** [comment]
Can confirm, that works:

```js
    WebAppInternals.setBundledJsCssPrefix('//my.cdn.provider.com');
```

Thank you.
