### ISSUE TITLE
1.0.5 Minifying Error

### ISSUE THREAD

**Issue by mccormjt** [meteor/meteor#4030]
Hello....just updated to 1.0.5 ---- I can successfully deploy my project, however I keep getting an error every time I try to access the main part of the application. The error is complaining about some function that was defined more once (which it calls "t"). If I deploy with the --debug option (i.e. not minified) then everything works fine. 

I am pretty sure the way its minifying things might be broken because I tried deploying a previous version of my app which did work fine in minified form (i.e. no debug option), yet I still get this same error, but only when its minified.

**Comment by Slava** [comment]
@mccormjt we would need to get a small reproduction to fix an issue like this. You can achieve it by cutting parts of your app and seeing if the issue persists.

**Comment by mccormjt** [comment]
Really weird problem. After many hours of trying to narrow down the conflicting lines of code there was one meteor method call that would cause it to blow up. But even if I commented out all the things the method did it didnt matter. Weird enough putting print statements around the method seemed to fix it. So my final solution (bandaid) was to simply wrap an anonymous function around that one method call. Really just a hack so it will compile normally for minifization. :/
Wondering if you had any other thoughts on trying to actually fix this problem.

**Comment by timhaines** [comment]
@mccormjt You haven't really provided enough info here (I'm curious about the problem you found too).  

Can you strip the rest of your app away and reproduce the problem just with this method?  With the method content commented out?  It sounds like that might make a nice reproduction for @Slava to work with.  

Possibly that just leaves an empty method declaration (and maybe some packages installed)?  What's the method name?

**Comment by mccormjt** [comment]
I can try to start stripping things away........but I think it might be very project specific.......it only happens for one of my app routes. I can go to the home page for example just fine. The meteor method being called is 'upsertUserIntoCloud' which just ensures the user data is inside the cloud he is trying to enter before entering it (its a beforeAction on iron router). But commenting out everything in the method doesnt fix it. Its actually calling the method thats the problem. Ill see what I can do. And I can call the method by itself just fine after Im in the cloud using the console. Its just that exact moment in the beforeAction where it complains about having a handler already named "t" and the stack trace isnt very helpful. I was able to track it back to that before action and calling that method haha.

**Comment by mquandalle** [comment]
Did meteor v1.0.4 also had this bug? If not, you can try to download the meteor git repository and git bisect from that basis to find out which commit introduced the bug.

```bash
$ git clone https://github.com/meteor/meteor.git && cd meteor
$ git bisect start release/METEOR@1.0.5 release/METEOR@1.0.4
# And then for every step
$ ./meteor run --production ~/path/to/your/project
```

**Comment by mccormjt** [comment]
ok cool I will give that a try

**Comment by mccormjt** [comment]
Hey guys.........just wanted to let you know Im still working on it. Ive gotten a 7000 line project down to about 400 lines and still able to reproduce the problem. I think I can narrow it down further. So Im going to keep working on it when I have time. Also meteor 1.1 update didn't fix the problem either. I am pretty sure this is an iron router problem though as its the most sensitive code to alter and still reproduce the bug in the whole project. Cheers

**Comment by Slava** [comment]
We appreciate your efforts! Let me know if I can help you (in case you can share the smaller version of your app)

**Comment by mccormjt** [comment]
That would be awesome if you guys could take a look! I worked all night on stripping the project apart. Its now down to about 70 "untouchable lines" meaning that deleting anymore causes the bug to go away. I made a repo with a readme in it to help you reproduce it. I Don't think I can narrow it down any more than those 70 lines (its really all iron router code).

https://github.com/mccormjt/meteor-bug

Cheers,
John

**Comment by glasser** [comment]
FYI you can test this by running `meteor --production`.

**Comment by glasser** [comment]
I'd consider this to be a bug in `iron:middleware-stack`.  See https://github.com/iron-meteor/iron-middleware-stack/blob/14f49297ea0943d8a26ed3123d63c836a4db8283/lib/middleware_stack.js#L27

This module, which is used by iron-router, cares about the internal name of a function you pass to it, which means that it will break when minification renames functions.  I'd file this as a bug at the iron-router or iron-middleware-stack repository.

**Comment by mccormjt** [comment]
Great thanks! Appreciate all your help!

**Comment by reason211** [comment]
I have the way to easy find the wrong place:
1. 
`vi ...//plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js`
2.  Add print here:
```
 271     function token(type, value, is_comment) {
 272 console.log('type: ' + type);
 273 console.log('value: ' + value);
 274 console.log('---');
 275 console.log('S:');
 276 console.log(S);
 277 console.log('---');
```
