### ISSUE TITLE
momentjs server side is broken since 1.0.4

### ISSUE THREAD

**Issue by jaskinn** [meteor/meteor#4031]
Slightly more info at - https://github.com/moment/moment/issues/2285

eg: 
```
var d = moment.duration(2, 'weeks');
```

results in 'TypeError: Cannot call method "duration" of undefined'.

However 
```
var now = moment();
```
is fine.

This is all on the server side.

**Comment by jaskinn** [comment]
hmmm I'm not so sure. I feel that I might be clobbering something.

**Comment by glasser** [comment]
As you wish!
