### ISSUE TITLE
Update doesn't work when collection is named "event"

### ISSUE THREAD

**Issue by fermuch** [meteor/meteor#4033]
```javascript
> Event = new Mongo.Collection("event")
> Event.findOne().party_managers
['1']
> Event.update({_id: _e}, { $push: { party_managers: "2" } })
MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}
```

But if I use any other name for a collection, nothing weird happens.

Example:
```javascript
> b = new Mongo.Collection("b")
>  b.insert({a: 'asd', b: ['1']})
'729becMYAhHEM8Y33'
> b.findOne()
{ _id: '729becMYAhHEM8Y33',
  a: 'asd',
  b: [ '1' ] }
> b.update({_id: 729becMYAhHEM8Y33}, { $push: { b: "2" } })
1
> b.findOne()
{ _id: '729becMYAhHEM8Y33',
  a: 'asd',
  b: [ '1', '2' ] }
```

This happens since 1.0.4. I'm testing now on 1.0.5 and it is still the same.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

I'm not able to replicate your issue.  Running something sort of like your example, but with the syntax errors (eg lack of quotes around 729becMYAhHEM8Y33) fixed and changing to "event" shows no issue.

**Comment by fermuch** [comment]
Hello!

After a little research I found this is a bug introduced in collection-hooks. It is caused by a collection hook not setting $set, not by the the collection itself.

Thanks anyway for your time and help.

**Comment by osv** [comment]
I think same story with simple-schema (aldeed:collection2) https://github.com/aldeed/meteor-collection2/issues/200

**Comment by osv** [comment]
aldeed fix simple-collection
