### ISSUE TITLE
Easy way to identify how an account was authenticated

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#4042]
**_1 Upvote**_ When a user signs in with Facebook/Twitter/etc, they should have 'signedInFrom' somewhere in their profile because the application may havefeatures for those networks (ie. a one click share button). Currently, you can identify this through services, but you may not want to publish that data (and its not published by default like profile)

**Comment by hpx7** [comment]
+1
See also #3669

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by jamgold** [comment]
I solved this particular need with this little snippet
```
Accounts._loginButtons.getLoginServices().forEach(function(ls){
	var s = ls.name[0].toUpperCase()+ls.name.substring(1);
	var lw = 'loginWith'+s;
	if(Meteor[lw] !== undefined)
	{
		var origMethod = Meteor[lw];
		// password is selector, password, callback
		if(ls.name == 'password')
		{
			Meteor[lw] = function(selector, password, callback) {
				Session.set('loggedinWith',ls.name);
				origMethod(selector, password, callback);
			}
		}
		else
		{
			Meteor[lw] = function(options,callback) {
				Session.set('loggedinWith',ls.name);
				// this is where I have to add the loginStyle?
				origMethod(options,callback);
			}
		}
	}
});
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Easy%20way%20to%20identify%20how%20an%20account%20was%20authenticated&body=Migrated%20from:%20meteor/meteor%234042) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
