### ISSUE TITLE
meteor command not found

### ISSUE THREAD

**Issue by rcidaleassumpo** [meteor/meteor#4043]
I know that this should be a easy problem to fix by putting the location where meteor was installed to PATH, but it's not working. The funny thing is that I have meteor working on my Surface normally from the command line, but on my desktop is giving me this problem. I installed through the msi installer and when I try to run through the cmd line it says that meteor command not found.
Any help? 
Thank you.

**Comment by avital** [comment]
On some versions of Windows a restart is required for PATH to be detected by new processes. Have you tried that?

(There seems to be some way to work around this but we haven't implemented it yet)

**Comment by rcidaleassumpo** [comment]
Yes, I tried that as well, I don't recall where someone said about restarting the pc after installing and it would work, but well :\ it didn't.

**Comment by stubailo** [comment]
@rcidaleassumpo do you have a lot of developer tools installed? There appears to be a maximum length for the PATH sometimes, and maybe we have hit that.

Have you tried going to the environment variable editor in Windows and manually adding `C:\Users\username\AppData\Local\.meteor`?

**Comment by rcidaleassumpo** [comment]
@stubailo Hi, yes I have tried :\. C:\Users\Renan\AppData\Local\.meteor . I also tried to take all the path that were there, uninstalled meteor and installed again, restart the computer, and nothing happened. I still get the "meteor command not found";

**Comment by stubailo** [comment]
@rcidaleassumpo are you running the CMD shell? We do not currently support git bash.

If you open CMD and type the full path of meteor.bat (`C:\Users\Renan\AppData\Local\\.meteor.bat`), it doesn't work?

**Comment by rcidaleassumpo** [comment]
Yes!, it works now. Thank you for your time my friend.

**Comment by upendram91** [comment]
Adding a path variable in Envrionment variables is another solution to use command from any directory. Path mentioned by @stubailo.
