### ISSUE TITLE
`private` directory not detected if not at the root of the project

### ISSUE THREAD

**Issue by gabriel-dehan** [meteor/meteor#4046]
Hello there,

I have been trying to get server assets throught `Assets.getText` with a file placed in `myapp/config/private/myfile.txt` but can't manage to make it work this way. I get an `Error: Unknown asset: myfile.txt`
The `private` directory and subdirectories seems not to be found when the `private` directory is not at the root of the project, meanwhile if I put my file in `myapp/private/myfile.txt` everything seems to work fine.

Is this supposed to work this way ? I think it would be better for it to work like the `lib` directory, being detected anywhere in the file tree.

**Comment by glasser** [comment]
This is working as intended; the docs say `All files inside a top-level directory called private` (see "top-level").

This makes sense to me: the argument to `Assets.getText()` is the path within `private`.  It's unclear what you would pass as the path to fetch a file from `myapp/config/private/myfile.txt`: `myfile.txt`? `config/myfile.txt`?  What if you have multiple `private` directories that contain `myfile.txt`?  Seems much more complicated than the current design.

**Comment by gabriel-dehan** [comment]
Makes sense, thanks.
