### ISSUE TITLE
Invalid "duplicate id" warnings in observe sequence

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4049]
I have a simple reproduction for a bug in Meteor. It seems observe sequence does not work correctly. It detects duplicate IDs where there are no duplicate IDs. Run the reproduction and observe the web console:

https://github.com/mitar/meteor-issue4049

cc @Slava

**Comment by Slava** [comment]
This was a fun bug! So it is a common mistake to check something for falsiness and while working with numbers. `!!0 === false`, this was the bug. A test and a fix coming soon.

**Comment by Slava** [comment]
On devel.

**Comment by mitar** [comment]
Thanks.
