### ISSUE TITLE
scope=['email'] gets overwritten in google_client.js

### ISSUE THREAD

**Issue by desm** [meteor/meteor#4050]
There seems to be a bug in the following lines of code:
https://github.com/meteor/meteor/blob/devel/packages/google/google_client.js#L28-L30

Pasting here for convenience:

```javascript
  var scope = ['email'];
  if (options.requestPermissions)
    scope = options.requestPermissions;
```

When the `if` condition passes, then `scope` gets overwritten.

The following fix works for me:

```javascript
  var scope = ['email'];
  if (options.requestPermissions){
    scope = _.union(options.requestPermissions, scope);
  }
```

**Comment by glasser** [comment]
I believe this is intentional; it allows you to choose to not request `email` if you don't want it.  (Perhaps you don't use the email address and don't want your users thinking that you do.)  The API you're proposing is strictly less powerful.
