### ISSUE TITLE
Screen corruption in Mac console when setting unmigrated

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#4054]
Obviously this isn't a particularly high priority, but I thought I'd note it.

When unmigrating a couple of packages, the text based screen updates end up causing 'corruption'.
It is also unclear what actually happened as the information is overwritten.
![image](https://cloud.githubusercontent.com/assets/3684334/6880978/456eab52-d542-11e4-93c8-3e7e6d884a07.png)

Note that this is on a Mac running Yosemite OS X 10.10.2 in the standard terminal app (set to 132x24).

I've also no idea why it ended up doing three things for the second command - I must have glanced away at the time. Possibly once per version?

**Comment by ekatek** [comment]
Yeah, that looks like an output-formatting thing. Probably, some stuff should be changed in this function to make it work more elegantly with the 'migrating' status bar. Thanks for catching this! I'll add it to the list of small things to take a look at.
