### ISSUE TITLE
delete-site command

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#4055]
I know that deploy has a --delete option, but it is far from obvious to newer users.
"deploy" infers deployment - the opposite of the delete operation, so the chances of someone using 'meteor help deploy' are minimal.
Deploy also requires you to be in a project where deletion doesn't.

For such a basic operation I think this should be top level command.

As an alternative (not my preference), I'd suggest changing the summary text of deploy from:
>    deploy              Deploy this project to Meteor.

to something like:

>    deploy              Deploy this project to Meteor (or use --delete to delete it).

While we're on the subject, there's a slight inconsistency in terminology.
It is just inferred from the summary text that deploy deploys a 'site', so maybe:
>    deploy              Deploy this project to **a** Meteor **site** (or use --delete to delete it).

**Comment by stubailo** [comment]
Good idea!

**Comment by laosb** [comment]
I thinks this is no longer needed as we don't have Meteor Free Hosting anymore, and Galaxy doesn't use this. Closing.
