### ISSUE TITLE
Mongo Text Indexing not working on *.meteor.com apps

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#4056]
Try searching here http://easy-search-leaderboard.meteor.com/
And try the same locally with following repo https://github.com/matteodem/easy-search-leaderboard.

Is there anyway I can see what my app on meteor logs on the server side? I can't debug what is failing right now.

**Comment by smowden** [comment]
The version of Mongo thats running on *.meteor.com is 2.4.12, text indexing is a new Mongo 3.0 feature

**Comment by matteodem** [comment]
Then I'd suppose to change it to 2.6 to have it synchronous to what is being used locally.

**Comment by smowden** [comment]
I've encountered this issue aswell today, FWIW you (or anyone who has this problem) can restrict easy search to @=1.4.13 until meteor hosting catches up

**Comment by glasser** [comment]
Text indexing was an experimental feature in 2.4 and is on by default in 2.6, but `meteor deploy` servers have not yet been upgraded to 2.6.  If you need this feature right now, you'll need to get your own Mongo server (or use a different deploy strategy altogether).

**Comment by smowden** [comment]
@glasser @matteodem  just checked it seems mongo has been upgraded

> connecting to: production-db-d1.meteor.io:27017/b
production-d:PRIMARY> version()
2.6.7

**Comment by glasser** [comment]
Note that `version()` tells you the version of the `mongo` shell client; `db.version()` tells you the server version.  Right now, some of the meteor deploy servers are at 2.6 and others are at 2.4.  We are having some difficulty with the upgrade (the meteor deploy servers scale in a different direction than mongo supports easily) and are evaluating various strategies now.

**Comment by matteodem** [comment]
Good that you are still considering upgrading :+1:

**Comment by gcacars** [comment]
What about minimongo $text selectors?

**Comment by glasser** [comment]
It's not implemented; you could open a feature request for that if you'd like.

**Comment by gcacars** [comment]
Thanks, it's what I will do!
