### ISSUE TITLE
Different App.info.id for Android and iOS

### ISSUE THREAD

**Issue by romangetman** [meteor/meteor#4057]
Is it possible to set the App.info.id in mobile-config.js per platform? There's nothing on this in the docs.

**Comment by glasser** [comment]
I don't believe that is possible in Meteor, and in fact I don't think it's possible in Cordova either: see https://cordova.apache.org/docs/en/4.0.0/config_ref_index.md.html which describes this file as "platform-agnostic".

What's your use case for this?
