### ISSUE TITLE
Feature request: preserve form inputs across hot code reload

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4058]
Filing here per @glasser in #1969.

Right now, when HCR occurs, form inputs are lost. This can have unwanted consequences especially when a textarea or element with contenteditable=true are re-rendered, and large amounts of user-entered text would be lost.

**Comment by Slava** [comment]
Ideally, we finish local template state (https://github.com/meteor/meteor/pull/3561) and the forms templates (like autoforms) will bind there values to there local state. And since the local state can be preserved (if configured so) in templates, this will just work fine.

**Comment by Slava** [comment]
Another solution for real use cases: postpone the hot code push until the user gets into a state, when there is no state like this to lose and user is inactive for X minutes.

**Comment by mitar** [comment]
cc @Retronator

**Comment by glasser** [comment]
@Slava And the hooks into hot code reload to do that already do exist (`Reload._onMigrate`) although not supported/doc'd.

**Comment by hwillson** [comment]
I've copied this feature request over to the Blaze repo at meteor/blaze#154. This issue can be closed.

**Comment by abernix** [comment]
Thanks, @hwillson!
