### ISSUE TITLE
Improve Atmosphere responsiveness

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4059]
Atmosphere is one of main official public Meteor apps. And it is so slow and unresponsive. UI is laggy. It just feels slow. How can I show to people how fast Meteor could be if even its own package repository is slow? I think Atmosphere is a good example of an Meteor app and you should invest some time to make it fast and sleek. If changes to Meteor are needed, this is the perfect use case.

**Comment by awatson1978** [comment]
Hi Mitar!

Have you seen http://fastosphere.meteor.com?  It's the fast package repository available.  :)

Different developers, different front-end UI.  Technically, Atmosphere isn't a MDG app (it's a Percolate Studios app, as I understand it).  Atmosphere is just a front-end to the 'meteor search' command, just like fastosphere is.

**Comment by mitar** [comment]
Atmosphere is linked from main Meteor app. My main issue is that when I pitch Meteor as a technology to use, people go, check the Meteor site, click on packages, and are welcomed with slowness and lagging, and whole browser starts behaving slow. It is very hard to convince anyone afterwards that Meteor is technology to use.

**Comment by awatson1978** [comment]
Hmmm....  yeah.  That's a problem then.  :(

I suspect once Galaxy is released, they'll reassign engineering resources to things like Atmosphere.  They've got a lot on their plate.  Until then, hang tight?

**Comment by mitar** [comment]
Are there example of performative, nice looking in-production, and large Meteor sites beyond those few listed on the landing page of Meteor page?

**Comment by ekatek** [comment]
Atmosphere is not maintained by MDG — comments on it should probably be directed to Percolate Studio (https://github.com/percolatestudio/atmosphere). It is nice to have a gorgeous front-end for package search, and I think that explaining that we have an awesome package system would be much harder (including for all the amazing package authors) if we *didn't* link to it from the docs. :)

The APIs used by Atmosphere have been publicly posted on the Github wiki pages here: https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API.
