### ISSUE TITLE
A site deployed to meteor.com does not work

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4060]
A very simple app ([see code here](https://github.com/mitar/meteor-issue4060)) deployed to meteor.com (see example here http://publish-on-deploy-bug.meteor.com/) does not work there. Locally it works great.

If you run app locally, you will see that there is all the time only one document on the client. If you open site on meteor.com you will see that every 3 seconds a new document is added and count goes up.

App simply runs upserts at regular intervals on the server, updating the same document.

When I do `Values.find().fetch()` in the console on deployed site I get an array of all documents (instead of only one), with:

```
_id: LocalCollection._ObjectID
  _str: "55173a20dd1241428cc7dca0"
  __proto__: LocalCollection._ObjectID
value: "by"
__proto__: Object
```

It seems there are some issues with EJSON deserialization?

**Comment by mitar** [comment]
cc @glasser

**Comment by mitar** [comment]
(As collection just grows and grows, probably you should reset the database on the deployed site before trying to open it, it will get really huge in time. Feel free to do so. This is just a deployment for this issue.)

**Comment by mitar** [comment]
Aha, the issue is that on the server:

```
Values.upsert('demo5', {
  value: dimsum.sentence(1).slice(0, -1).toLowerCase()
});
```

This tries to replace the whole document, but it is replacing without an ID, so a new ID is generated. This fixes the problem:

```
Values.upsert('demo5', {
_id: 'demo5',
value: dimsum.sentence(1).slice(0, -1).toLowerCase()
});
```

But the questions still is why it works locally when developing and not on Meteor deployment.

**Comment by glasser** [comment]
See a83008ebb44a8d53f8e36790e77811d2eb9d3c23

Mongo changed the behavior of upsert-by-ID between 2.4 and 2.6.  They regarded this as a bug fix, not a compatibility change (it wasn't even mentioned in their release notes, say).

Meteor deploy is still on 2.4, so you'll still see the 2.4 behavior when upsert's logic is being implemented by mongod there.

(And as of Meteor 1.0.4, minimongo's implementation matches the 2.6 behavior, as mentioned in History.md.)

**Comment by glasser** [comment]
Note that I believe (if it makes sense for your app) `Values.upsert('demo5', {$set: {value: 'xxx'}})` should do what you expect on both 2.4 and 2.6 (as mentioned in our History.md); it was just the "replace" version of update that had this bug in 2.4.

**Comment by mitar** [comment]
> Meteor deploy is still on 2.4, so you'll still see the 2.4 behavior when upsert's logic is being implemented by mongod there.

This is the reason then. :-)
