### ISSUE TITLE
package.js executed twice by meteor run, meteor test-packages

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4061]
Is this intended? To reproduce:

```
meteor create --package <yourusername>:twice
cd twice
echo "console.log('This should run only once perhaps')" >> package.js
meteor test-packages ./
```

The statement also executes twice when the package is used locally by a test app executed with `meteor run`.

Nice gain in startup speed on the horizon?

**Comment by glasser** [comment]
If and only if a package has tests, there's a second execution of package.js to generate the `local-test:foo` package.  While it would be possible to optimize this step, do you have reason to believe it's a particularly poorly-performing part of the code?  Typical package.js executions are purely "add some strings to some data structures".

**Comment by dandv** [comment]
I found a use case where `package.js` is executed repeatedly, which leads to a rate limit being exceeded on Windows. To reproduce,

```bat
git clone git@github.com:dandv/meteor-webix.git
git checkout a487d0c7c502189eb4b39d76d2ed37e0449ff39c
cd meteor-webix/examples/crud
git submodule update --init
REM create a syntax error
echo "0i" > client\crud.js
meteor run
```

The output shows that [`package.js`](https://github.com/dandv/meteor-webix/blob/master/package.js) is executed repeatedly:

```
=> Modified -- restarting.
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
Could not find webix/bower.json to read version number from; trying GitHub...
=> Errors prevented startup:

   While building the application:
   client/crud.js:1:16: Unexpected token ILLEGAL
```

(side note: there is no 16th column in client/crud.js; the file is only 3 bytes long)

On Linux, only two `Could not find webix/bower.json to read version number from; trying GitHub...` are output.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=package.js%20executed%20twice%20by%20meteor%20run%2C%20meteor%20test-packages&body=Migrated%20from:%20meteor/meteor%234061) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
