### ISSUE TITLE
Modular App Structuring

### ISSUE THREAD

**Issue by boustanihani** [meteor/meteor#4062]
After my Meteor project got more complex and I started grouping my code into modular (partially dependent) entities, I faced some issues **that made me ask myself if the current recommended way of structuring a Meteor app could be enhanced**.

In general, I like the principles of "**Convention over configuration**" as described in the docs: http://docs.meteor.com/#/full/structuringyourapp. But IMO, the current conventions and rules make it hard to organize a single Meteor app in a modular way (**without using packages**).

Suppose we have a folder named ```modules``` which includes several subfolders, **each representing a single module**. It is common, that modules are shared across projects and that each module has one or more ```lib``` folders that includes code which must be executed first, for the module to function.

Now suppose that some of the modules depend on another so we also need to make sure that certain ones are executed before others. **I know we could solve this by creating packages, dependencies and exports… but sometimes this is too much extra work** and we simply want to be able to place each module in its own folder and still make sure that some folders get executed before others.

All of our folder-modules have their own ```lib``` subfolders, so saying like put all core modules under ```lib``` and others outside ```lib``` is not an option. The only option we have left (other than switching to creating packages) is making sure that core-modules have a deeper path than others that depend on them. So I ended up creating several intermediate meaningless subdirectories, only to make sure that my core-modules get executed first. **I know this is an ugly solution, but for me this was much simpler than switching to creating packages**.

Now, the only reason for this post is to suggest the following enhancement:

Change the rule: "**Files with deeper paths are loaded first**" to "**Files with deeper paths are loaded first if and only if they lie on the same branch**". That means child nodes get executed only before their own parents.

Consider the following file structure:
```
../modules/module_a/file_a.js
../modules/module_b/sub/file_b.js
../modules/module_c/sub/sub/file_c.js
```
If  the above suggestion is taken into consideration, then ```file_a.js``` will get executed before ```file_b.js``` and ```file_b.js``` will get executed before ```file_c.js``` even though the others lie in a deeper path (relative to the project directory). So for files on different branches the "**alphabetical order**" is applied regardless of how deep the path is. This makes it possible to let ```module_a``` get loaded before  ```module_b``` and  ```module_b``` before  ```module_c``` regardless of how each module is internally structured… 

I hope all makes sense and I am excited for your feedback.

**Comment by queso** [comment]
What are you finding to be too much work about creating packages to manage this type of worry?

In my experience in several teams, packages have worked out great for this type of growth. On top of that we now have the new Mocha package testing w/ a hot UI on it.

**Comment by queso** [comment]
What are you finding to be too much work about creating packages to manage this type of worry?

In my experience in several teams, packages have worked out great for this type of growth. On top of that we now have the new Mocha package testing w/ a hot UI on it.

**Comment by boustanihani** [comment]
@queso I agree that when several teams work together, packages are necessary and also good practice, but IMO for a single developer and especially at early development stages, it won’t be clear what packages will emerge and which parts of your app will become reusable… with time when your project matures, you may then publish some of your modules as packages and make them available for others… but you still want to be able to organize your code into modules from the very beginning. Do you think my above suggested enhancement is okay for this purpose?

**Comment by awatson1978** [comment]
Refactor paths, sure.  I get what you're saying, @boustanihani.

I think the idea is pretty good, and would make for a better user experience, and is in keeping with the general trend towards web components and template inheritance.  It will take time for the MDG team to get around to rewriting the file parsing algorithm, and it could potentially break a bunch of people's apps.  And this code has been around since the beginning, and is baked fairly deep in.  So, it could be months before this kind of request happens.

My guess is that it's the kind of thing that would be thought about during work on the next Blaze rewrite.  Maybe suggest it on the [Blaze 2 Hackpad](https://meteor.hackpad.com/Proposal-for-Blaze-2-bRAxvfDzCVv) down at the bottom?  That might be the right place to contribute this kind of feedback.  Or at least add a link to this issue so people can cross-reference.

**Comment by boustanihani** [comment]
@awatson1978 I’m glad you got my point :) and I totally agree with what you are saying about potentially breaking a bunch of people's apps and so on… sure it could take month for such a request to happen… But I don’t think this is directly related to Blaze, it is more about enhancing the ability of writing modular code with Meteor, you may (for example) be using Meteor as server-only solution without Blaze or any other client-side components.

**Comment by Sanjo** [comment]
With the [control file idea](https://meteor.hackpad.com/New-control-file-brainstorming-ZDBMiEQ6DZl) you would be able to customize the load order in your project.

Personally I hope that the ES6 Module system is supported in the near future (for example via [SystemJS](https://github.com/systemjs/systemjs)), so that the load order depends on declared dependencies and not on the file location in the file system.

**Comment by boustanihani** [comment]
@Sanjo Interesting discussion, but the fine grained control is more related the packaging system, which is for sure a good option to have (when needed), on the other hand, when a user prefers simplicity (**Convention over configuration**) then we should provide him with smart conventions and wisely chosen rules he can work with... We are asking ourselves if the conventions & rules in the "**File Load Order**" section (under http://docs.meteor.com/#/full/structuringyourapp) could be furtherly optimized?

**Comment by aldeed** [comment]
I agree that this aspect of the rules has given me trouble a few times. Usually solvable by using packages, but sometimes that is overkill or doesn't make sense from the standpoint of keeping files organized logically.

I think a solution more likely to be merged soon would be a switchable algorithm, with the current being the default and some way to choose a different one (like your proposed alteration). Then its backwards compatible.

**Comment by benjamn** [comment]
Improving load order control is [an item on our roadmap](https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-apps-and-controlling-file-load-order), and we usually don't use GitHub for big discussions like that.

I tentatively agree with @Sanjo that [ES6 module syntax](https://github.com/meteor/meteor/issues/4062#issuecomment-87562504) could be a powerful technique for specifying dependencies, but there are still a number of issues to work out.

Thanks everyone for the interesting discussion, and please do have a look at the discussion on the roadmap link above if you're interested in contributing!

**Comment by trusktr** [comment]
Would a solution that uses webpack behind the scenes be legitimate?
