### ISSUE TITLE
Typos in the Cordova/Phonegap integration wiki page

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4063]
At https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration:

`The Android device will connect to the server at :.` - probably `<>` eaten up by Markdown

"push such updates to the clients if a Hot Code Push reload" -> with

"before loading the bundled application code shipped through App Store or Play Store, app tries to load from the internal storage copy. In case of files not being found on disk, app falls-back" -> the app

Hyperlink [CrossWalk](https://crosswalk-project.org/)?

**Comment by Slava** [comment]
Fixed all of these, thanks!
