### ISSUE TITLE
Windows Installer: Pressing Enter should initiate sign in

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4065]
Minor feature request. Right now, if I enter my user/pass and press Enter, nothing happens.

![image](https://cloud.githubusercontent.com/assets/33569/6891488/82e59c78-d670-11e4-956d-c752a568704e.png)

**Comment by stubailo** [comment]
Thanks for the report!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Windows%20Installer%3A%20Pressing%20Enter%20should%20initiate%20sign%20in&body=Migrated%20from:%20meteor/meteor%234065) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
