### ISSUE TITLE
Search does not clear filter

### ISSUE THREAD

**Issue by MHoeller** [meteor/meteor#4067]
I need to do a search on a text field. The Search criteria / filter on the collection can be any substring of the sting in the field. I save the filter (input) in a session variable. The filter seems to work the first time after the Sessionvariable is null. After the first search I get no result when I enter a new (extisting!) value. In case I clear the filter, hit enter and than reenter the filter I get the result. I assume that my code is suboptimal. Can someone please review and maybe make a suggestion?

-    why do I need to first "enter" as entry string to get a valid result
-    is this a good procedure? Doesn't hitting enter works against the reactive approach? I think after enter the complete page is resent ??
-    Would it be better to check "keyup" for ASCII 27 and 13?
-    it seems to me that the regex works, are there any concerns? I like to find any substring of the typed in filter, also when the filter has a whitespace.
 -   this is a full text search do I need to set something up on the mongodb side?
-    Open Question: are the already prebuild implementiations - I do not need to reinvent the wheel...

Here is what I have:

Session.setDefault('searchText', null);

    Template.questions.helpers({
         questions:function(){
        if ((Session.get('searchText') === null) || (Session.get('searchText') === '')) {
        Session.get('searchText',null);
        return Questions.find({archived:{$ne:true}});
    } else {
        var searchText = Session.get('searchText');
        Session.get('searchText',null);
        return Questions.find( { $and: [ { archived: { $ne: true } }, {note:{$regex: (".*"+searchText+".*") }  } ] } )
        }
        },
        searchText:function(){
            return Session.get('searchText');
        }
    })

    Template.questions.events({
    "change #nameSearchBar":function(event){;
            searchText = event.target.value;
            Session.set('searchText', searchText);
        }
    })

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
