### ISSUE TITLE
Implement SD card emulation to avoid "Insert an SD card before using the camera" error with the mdg:camera example in Android emulator

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4069]
When trying to take a picture in the [simple photo example](https://github.com/meteor/mobile-packages/tree/master/examples/simple-photo) on Ubuntu, the emulator displays an error message that an SD card should be inserted:

![image](https://cloud.githubusercontent.com/assets/33569/6905545/7924d9f2-d6dd-11e4-8d31-1b20f427d1a5.png)

Is this an easy option to enable somewhere, or should meteor [configure SD card emulation](http://developer.android.com/tools/devices/emulator.html#sdcard) for Android?

**Comment by glasser** [comment]
Replicated with Meteor 1.0.5 on OSX.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by yoh** [comment]
+1 :) (with Meteor 1.1.0.2 on OSX too)

**Comment by elfassy** [comment]
+1 also on OSX

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
