### ISSUE TITLE
Improve App.accessRule docs and Cordova error output

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4070]
**_1 Upvote**_ The correct format is 

```
App.accessRule("https://engine.kadira.io");
```

This was not clear to me after reading 

http://docs.meteor.com/#/full/App-accessRule

Just adding an example call would be great.

If my mobile-config.js has the incorrect line:

```
App.accessRule('<access origin="https://engine.kadira.io" />');
```

and I do `meteor run ios-device`, it goes from:

```
Building mobile project      |
```

to:

```
Error while running for mobile platforms: Error running /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
undefined
```

Which is not a descriptive error.

**Comment by Slava** [comment]
@lorensr you can submit a PR to docs! This would help us to improve things like this one.

**Comment by Alir3z4** [comment]
The [doc](http://docs.meteor.com/#/full/App-accessRule) `<access origin="*"/>` is really confusing, would be great if there were an example

**Comment by dandv** [comment]
:+1:

**Comment by hwillson** [comment]
I've moved this issue over to meteor/docs#118. Closing here - thanks!
