### ISSUE TITLE
Add reset-cordova command

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4072]
There have been at least a couple times when my cordova installation has been messed up (once might have been dropbox's fault, the other I don't know, maybe `meteor-up`), and no amount of add/removing platforms and packages can fix it. If memory serves, `meteor reset`ing didn't help either. I eventually resort to removing `.meteor` subdirectories until it starts working again 😄 It would be great if there was a 

`meteor reset-cordova`

command that does not reset the database but instead removes all `.meteor` subdirectory/ies that could possibly cause such a state.

**Comment by glasser** [comment]
Are you sure that `meteor reset` doesn't help?  While it's documented as deleting your mongo DB, it actually deletes all of `.meteor/local`, and that's where Cordova state is.

This bug does not have a reproduction, so I'm closing it. If anyone is able to come up a way to consistently reproduce it, we can reopen it.
