### ISSUE TITLE
Unnecessary re-rendering in Blaze because with's ReactiveVar uses default equals function

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4073]
***1 Upvote*** Blaze uses in its [Blaze.With](https://github.com/meteor/meteor/blob/devel/packages/blaze/builtins.js#L16) view `ReactiveVar` with default equality function:

> A function of two arguments, called on the old value and the new value whenever the ReactiveVar is set.  If it returns true, no set is performed.  If omitted, the default `equalsFunc` returns true if its arguments are `===` and are of type number, boolean, string, undefined, or null.

This means that for most data contexts which are objects re-rendering is triggered because equality function returns false. Even if new and old objects are referentially or content-wise completely equal.

The issue is that this triggers again and again `Template.currentData()` which might be in autoruns which do complex code.

So the questions are: why not provide some configurability here? Somehow one-size fits all approach is not good enough here. Some objects are equal when they are referentially equal. Some objects are equal when `EJSON.equals` returns true and it is cheaper for equality then recomputing the autorun reactive var is used in. For some you want fast failure like it is now.

Maybe a set of utilities around reactive dependencies would be beneficial which would help? https://github.com/peerlibrary/meteor-computed-field does not help with `Template.currentData()` because it does not use Blaze autorun.

In any case, the main issue is that internally all with data contexts are rerendered. And if this triggers then dynamic template inclusion to rerun, then you have things rebuilding and re-rendering all over the place.

**Comment by dgreensp** [comment]
It's true that being able to configure how `{{#with}} does comparisons might be a nice analogue of React's `shouldComponentUpdate`.  At the moment, combined with the fact that too many common patterns in Blaze take a dependency on the data context, some inefficiency results.

As a workaround for particular cases where you really don't want to re-render a template unnecessarily, you can use a `ReactiveVar` on the template instance and configure its `equalsFunc`.

**Comment by mitar** [comment]
My current workaround is:

```
@currentData = new ReactiveVar null, EJSON.equals
@autorun (computation) =>
  @currentData.set Template.getData()
```

Probably this is what you meant as well. :-)

**Comment by hpx7** [comment]
+1 (see also #3966)

**Comment by mitar** [comment]
This is especially problematic with `#each`.

**Comment by mitar** [comment]
Closing in favor of: https://github.com/meteor/blaze/issues/68
