### ISSUE TITLE
meteor reset on windows 8.1

### ISSUE THREAD

**Issue by MurWade** [meteor/meteor#4074]
`meteor reset`on windows does not work.

`This command does not work while Meteor is running your application. Exit
the running Meteor development server.`

Even though i have stopped the application. However it does work when i delete the `./meteor/local` folder.

**Comment by steph643** [comment]
Same for me on Windows 7 + WebStorm.

**Comment by ekatek** [comment]
This might be worth looking into before 1.1 -- @stubailo, @Slava ?

**Comment by steph643** [comment]
I am pretty sure this used to work correctly. What I did recently is adding service-configuration and accounts-facebook.

**Comment by jhuenges** [comment]
Doesnt work for me either (win 7)

**Comment by aadrian** [comment]
bug reproducible on win8.1, win8.1 Pro and win7 Enterprise.

**Comment by MurWade** [comment]
This works with the latest update meteor 1.1  for me

**Comment by glasser** [comment]
@aadrian @jhuenges @steph643 In what Meteor versions are you seeing this issue?  Does it work with 1.1 like it does for @MurWade?

**Comment by steph643** [comment]
It seems it works for me in 1.1

**Comment by jhuenges** [comment]
Works now (1.1)

**Comment by stubailo** [comment]
I think we fixed this in 1.1 and the original issue was posted before that. Closing this then.
