### ISSUE TITLE
Session.equals causing Tracker.autoruns to stop

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#4078]
I just spent 6 hours trying to debug why 2 Tracker.autorun functions were being mysteriously stopped. It came down to a line like this:

```js
if ( Session.equals("showHeader", true) ) {
  return ...
} else {
  ...
}
```

This line was for a header component, and the autoruns were in another component completely, the one that was rendered as the main section of that page.

The bug would only occur on a fresh load of a specific route — not if you arrived on that page through the application, and not from a live reload pushed from the server. This makes sense that Session was the cause of the bug then. 

My reactivity debugging looked like this
```js
var comp = Tracker.autorun( function(computation) {
  computation.onInvalidate( function() {
    console.log("computation is", computation.stopped ? 'stopped' : 'not stopped');
  }
}
```

Nowhere in my application was I calling `comp.stop()` but sure enough they were being stopped. And since I had subscriptions within the autoruns they were stopped as well. It was a huge, cryptic mess.

From my understanding of Tracker, [if there's an error in recomputing it will stop the computation](https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L199-L200). I have *no* idea how a faulty `Session.equal` not in any `Tracker.autorun` could cause that error to happen, but that seems to be what's happening. I hadn't gotten to the point of using a local version of Meteor and debugging from the Tracker package so I don't have any more than suspicion to back that up.

Unfortunately I can't share the repo as it's an in-progress commercial project, but let me what information I can give to be more helpful.

**Comment by stubailo** [comment]
@lourd the most useful reproduction would be a complete app that we can download and run to reproduce the issue. Unfortunately, I don't think we have enough information right now to identify the issue.

**Comment by glasser** [comment]
Agreed with @stubailo.  Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by lourd** [comment]
Understood. I'll work on paring it down to the minimal amount needed to show the bug and post it.

**Comment by shawnmclean** [comment]
@lourd did you ever get this sorted? I think I have that exact issue. My issue lies in wrapping some Routes in an auth component, haven't narrowed down the code yet but on a fresh page load, something is stopping my Tracker.autorun.
