### ISSUE TITLE
Is there any way to insert a callback before/after a templates context is updated? 

### ISSUE THREAD

**Issue by micahblu** [meteor/meteor#4079]
I'm aware of Template.onRendered, however I have the need to destroy and setup some plugins that act on the dom when the actual context is updated.

So saying I have `content` template, I'd need something similar to the following:

```js
Template.content.onBeforeChange(function () {
  $(".editor").editable("destroy");
});

Template.content.onAfterChange(function () {
  $(".editor").editable();
});
```
Is there any current way I can achieve this with the existing Template api?

**Comment by dcsan** [comment]
questions you might want to ask on stackoverflow? this is more for bug reports on the framework itself.

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by micahblu** [comment]
I agree my apologies
