### ISSUE TITLE
Will meteor run on old Windows Systems? If not .bat files can be changed to .cmd?

### ISSUE THREAD

**Issue by rodrigorodriguez-com** [meteor/meteor#4080]
or even PS to become more Microsoft Friendly!

"In addition, apparently 9x days and before there was only bat? And then with NT CMD was introduced, and running the same .bat file on 9x and NT definitely had different results, so having two different extensions made it less likely to accidently run a cmd written for NT on a 9x box if you were interoperating between the two. This sounds plausible, but I can't remember those sorts of details that far back."
http://commandwindows.com/batch.htm
http://waynes-world-it.blogspot.com.br/2008/08/difference-between-bat-and-cmd.html

**Comment by stubailo** [comment]
@rodrigorodriguez-com right now, we are only officially supporting Windows 7 and above, and Meteor runs great from inside PowerShell.

What system are you running on where `bat` files don't work?

**Comment by rodrigorodriguez-com** [comment]
@stubailo, everything works fine here.
I am running Windows 10, Build 10041. It's just a recommendation: To use .cmd files instead of .bat files. 
And in the future, migrate those .cmd files to PowerShell and create just a .cmd file which is a Powershell invoker.

**Comment by rodrigorodriguez-com** [comment]
And when everything is Powershell is more likely a 'Microsoft way' of doing this stuff on Windows, I believe.

**Comment by stubailo** [comment]
@rodrigorodriguez-com I think the thing we have works fine for people right now, when we see some tangible concerns that will be solved by switching to CMD or PowerShell then we will do it.

**Comment by rodrigorodriguez-com** [comment]
OK, just wondering if it will look old-fashioned to Windows users.

**Comment by stubailo** [comment]
Building better Windows-style tooling is definitely something we want to do. It will probably come in the form of Visual Studio integration, I think.
