### ISSUE TITLE
meteor stable release tag release/METEOR@1.1

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4082]
Hi, did you change your naming / tagging policy?

Normally you created a tag for each stable release but not yet for 1.1. Instead of a tag for this stable hash you have now a (moving) branch named release-1.1

Could you please mark the stable commit hash with a tag?

Thanks
Tom

**Comment by stubailo** [comment]
https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.1

Is this what you are looking for?

**Comment by TomFreudenberg** [comment]
Hi @stubailo 

exactly what I was looking for. When I `fetched all` hours ago it was not present at my local clone. Really spooky ... I did it again now and yet the tag is available. Maybe in case of the github attacks of the last days my fetch broke? or whatever...

Thanks for answer
Tom

**Comment by glasser** [comment]
It looks like the commit at which the release was built (the one @stubailo linked to) didn't actually end up being on the release branch or merged into HEAD.  By default `git fetch` only gives you tags that point into the branches you're fetching.  `git fetch -t` will give you all tags.

**Comment by TomFreudenberg** [comment]
Hi David, normally I update my local via `git fetch --all --tags` - so all new tags should be included. But maybe I missed something this time.

I already updated the universal fork to meteor 1.1 with the above commit from @stubailo.

Thanks for comments and help
Tom
