### ISSUE TITLE
It's was error when install android sdk 

### ISSUE THREAD

**Issue by ystyle** [meteor/meteor#4083]
$ meteor install-sdk android
✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
✓ Found Android Build Tools                   
✓ Found Android 19 API                        
✓ Found suitable Android x86 image            
Creating android virtual device (AVD): meteor 
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)

**Comment by glasser** [comment]
Did this happen every time you ran it, or just once?
What platform are you on?
What version of Meteor (`meteor --version`)

**Comment by ystyle** [comment]
every time,my pc is Archlinux x64
Meteor version is 1.05 bug now is 1.1

**Comment by ystyle** [comment]
![c7543e0d-4c0e-439f-a2bc-268eb0ede120](https://cloud.githubusercontent.com/assets/4478635/6955712/f79153e0-d914-11e4-8926-4996a5888084.png)

**Comment by ystyle** [comment]
I has solved this problem !!!
Method is:
```shell
cd ~/.meteor/android_bundle/.android # To avd save directory
rm -rf avd # Delete the created avd
cd ~/.meteor/android_bundle/tools/android #To the android SDK directory
tools/android # Run the android SDK manager then create a avd call meteor in the android SDK manager
ln -s /home/$USER/.android/avd /home/$USER/.meteor/android_bundle/.android # link the avd in your home directory to meteor's directory
meteor install-sdk android # Add back the android platform



````

**Comment by glasser** [comment]
Great to hear that this works.  But we don't expect it to be necessary.  If other users find this to be necessary let us know!

**Comment by zqalyc** [comment]
@glasser I have the same error. My version is Meteor 1.1.0.2

**Comment by ludbek** [comment]
I had the same issue. Here is the solution that worked for me,

    $ sudo meteor intall-sdk android

Add sudo to the command.

**Comment by nimaous** [comment]
I also add sudo but still have the problem

**Comment by SoftBrain001** [comment]
I have the same error, but in an earlier step : 
udo-admin@udo-project-002:~/repos/alerti-new$ sudo meteor install-sdk android
[sudo] password for udo-admin:
✓ Found Android bundle
✓ A JDK is installed
✓ Found Android Platform tools
Installing Android Build Tools

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)

I'm using: Ubuntu server 14.04 LTS x64

**Comment by jsteel** [comment]
Same for me on Ubuntu 14.04.2 LTS. Sudo didn't help.

**Comment by SoftBrain001** [comment]
I think that there is some issues on Ubuntu 14.04 Server.
I try it on Ubuntu 12.04 Desktop, it's work fine.
