### ISSUE TITLE
Meteor Build on 1.1

### ISSUE THREAD

**Issue by jhmacdon** [meteor/meteor#4084]
When trying to run Meteor, I get the error:
<code>Error: EACCES, rename '<directory>/.meteor/local/build'</code>
unless I run w/ sudo. This only happened after the update, any ideas?

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

What command are you running? What platform?  What's the full context (not just this one line)?

It sounds like it is trying to run an app in the root directory of your system, which is surprising.

**Comment by jhmacdon** [comment]
No, I just removed the rest of the directory that had some personal information. Will do though, thanks.

**Comment by glasser** [comment]
In general, it is much more helpful to provide the error message that is actually printed, not an edited version.
