### ISSUE TITLE
What happens when two packages Npm.depend on incompatible versions of a dependency?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4085]
FOr example, suppose one package depends on `foo@0.2.0`, and another package depends on `foo@1.2.0`. What happens?

**Comment by glasser** [comment]
What happened when you tried it? :)

Questions like this are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker.  If you think the behavior when you do this is wrong, that's a better fit for the bug tracker.  Good luck!
