### ISSUE TITLE
How to create a deployment account @Meteor

### ISSUE THREAD

**Issue by vioan** [meteor/meteor#4086]
There is mentioned in any tutorial how easy is to deploy your app to meteor.com but there is nothing about how and where the user should create his/her account and for beginners could be confusing. Could that be added to doc/tutorial?

**Comment by glasser** [comment]
It is fully documented in the tutorial... in that you don't have to create an account in order to deploy!  Just run `meteor deploy sitename` and it will prompt you for an email address, and let you later fully register your account with a password.
