### ISSUE TITLE
FR: Package api.addFiles accept wildcards / folders

### ISSUE THREAD

**Issue by raix** [meteor/meteor#4088]
Reference: https://github.com/MeteorCommunity/discussions/issues/7

-

Hugo Magalhaes: developing a application using the method suggested at http://www.matb33.me/2013/09/05/meteor-project-structure.html, so I have a package per feature and all the packages have the following structure:

```bash
-> client
    |-> sub_folder
    |   |-> file_1.js
    |   |->    ...
    |   |-> file_n.js
    |-> file_1.js
    |->    ...
    |-> file_n.js
-> lib
    |-> sub_folder
    |   |-> file_1.js
    |   |->    ...
    |   |-> file_n.js
    |-> file_1.js
    |->    ...
    |-> file_n.js
-> server
    |-> sub_folder
    |   |-> file_1.js
    |   |->    ...
    |   |-> file_n.js
    |-> file_1.js
    |->    ...
    |-> file_n.js
```

Trying to find a way to add all files from each folder (and sub-folder in the following way):
```js
api.add_files(["client/*","client");
api.add_files(["lib/*", ["client", "server"]);
api.add_files(["server/*","server");
```

**Comment by glasser** [comment]
Thanks for the suggestion. This is part of a major project that is being tracked on the [roadmap](https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-apps-and-controlling-file-load-order).

The eventual goal is to unify package configuration (which currently gives you detailed control over which files to load but no easy way to say "this whole subtree") and app configuration (which currently lets you just add files to a tree but doesn't give you detailed control).

**Comment by jlukic** [comment]
Just saw this and was like "Oh god meteor supports this now and I had no idea!"

This should make it into [Meteor doc's API explanation of `api.addFiles`](http://docs.meteor.com/#/full/pack_addFiles) and maybe @stubailo meteor guide.
