### ISSUE TITLE
'meteor' command not found in Windows 7

### ISSUE THREAD

**Issue by rteslaru** [meteor/meteor#4090]
Tried the official Windows installer today. It installs without any error messages, but I can't get it to run:

```
C:\Users\eraztes>meteor
'meteor' is not recognized as an internal or external command, operable program or batch file.
```

Tried restarting as well. No METEOR related environment variables are being set either, as far as I can tell. The account I used to install it is a local administrator.

**Comment by rteslaru** [comment]
I got it working by right-clicking on the executable and choosing "Run as an Administrator" -- that got it working, even though my account is already a member of Local Admins.

**Comment by anthonystorm** [comment]
There is a extra / after the folder name in the path C:\Users\user1\AppData\Local\.meteor\
remove it and everything works as expect.  C:\Users\user1\AppData\Local\.meteor

**Comment by glasser** [comment]
@anthonystorm Where is this extra backslash? In a file that we install?

**Comment by guokr321** [comment]
I did the same as @rteslaru ，but I did not work. And I manually  add the path of meteor. But I find the installer in window 8 add the path of meteor automatically

**Comment by siberianbear** [comment]
Same for me: I've installed Meteor 1.1 for Windows at Win 7 Ultimate x64 and by default it does not work at all. I've add Path manually and that's fixed the issue.

**Comment by aruljothiparthiban** [comment]
@anthonystorm I tried the same but it is not working.

**Comment by Xaverius** [comment]
Worked for me.
Check user variables, not system variables .

**Comment by jamc92** [comment]
Meteor is not recognized as an internal or external command, operable program or batch file on Windows 8.1

This is the output that is showing when I'm trying to use meteor on the command line: '"C:\Users\Javier\AppData\.meteor\\packages\meteor-tool\1.1.8t-os.windows.x86_32\meteor.bat"'

I don't know what to do and I don't know how to "play" with the path. Nothing.

**Comment by dddvvv** [comment]
My %PATH% got bigger than 2048 characters and it was truncated "C:\Users\Y\AppData\Local\.m". You can check if this is your problem by running "echo %PATH%". In this case you should delete redundant entries from %PATH%. WARNING: back up the entries in a text file before doing this because it could mess up your environment.

**Comment by jamc92** [comment]
This was the output
![captura de pantalla 2015-09-27 14 25 13](https://cloud.githubusercontent.com/assets/1733996/10124660/bd70d62c-6523-11e5-96ed-579752712b65.jpg)
What should I do? And if I delete redundant entries from Path, would be in User variables or System variables?
This is the output that throws CMD each time i run a Meteor command
![captura de pantalla 2015-09-27 14 19 28](https://cloud.githubusercontent.com/assets/1733996/10124665/ebee10c8-6523-11e5-9587-1897eb2b4220.jpg)

**Comment by dddvvv** [comment]
@jamc92 Yours is a different problem because your 1.1.8 meteor.bat is missing. You could try to reinstall your meteor.

Here is how meteor.bat shows on my setup:
![image](https://cloud.githubusercontent.com/assets/13160957/10127693/130d4404-65af-11e5-978c-5092c730f847.png)

**Comment by mizzao** [comment]
I'm having this issue too, but when opening command prompt as administrator, Meteor works. However, I don't recall running the Meteor install app as an administrator.

**Comment by mjhasbach** [comment]
Same problem on Windows 10:

> 'meteor' is not recognized as an internal or external command, operable program or batch file.

Fixed by removing the trailing slash as mentioned above. Is there another issue open tracking this Meteor installation issue?

**Comment by amanuel2** [comment]
Guys! Everybody, you guys have to have a seperate PATH On your enviorment variables. I accidently had mongoDB And Meteor on the same PATH Variable

**Comment by Lenzcrafter** [comment]
Many months later, still same issue... Really guys?  Can't just fix this?

**Comment by durairajaa** [comment]
I had the same issue,

I fixed the problem by adding the path(C:\Users\user_name\AppData\Local\.meteor) to the path variable under system variables.

after that it worked without running the command prompt in administrator mode.

**Comment by swederik** [comment]
@mizzao and @mjhasbach are right, removing the trailing backslash on a fresh install allowed me to run Meteor. This should be reopened!

**Comment by abernix** [comment]
@swederik, thanks for your input but please also see my comments here https://github.com/meteor/meteor/issues/7322#issuecomment-229258216.  It seems to work with or without the slash (btw, the slash isn't something that Meteor is putting there), but restarting is important, especially on Windows 7.

**Comment by swederik** [comment]
Fair enough, I didn't restart the PC. Maybe just the act of editing the environment variables applied the changes to the shell and the slash itself was inconsequential.

**Comment by abernix** [comment]
Yes, I believe using the GUI will make the changes take place immediately using Windows internals.  The Installer right now does say that you should restart, most likely to avoid this exact issue.  That being said, I've just found something that might resolve this in future installers.  I've opened #7431 if you're curious.
