### ISSUE TITLE
webcomponents.js (Polymer) breaks events in meteor

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#4091]
***1 Upvote*** When using webcomponents.js, Google Polymer's webcomponents polyfill, template events no longer work in Firefox. It doesn't matter if the event listens on a custom element or just a "normal" html tag.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by AndreasGalster** [comment]
https://github.com/AndreasGalster/meteor_polymer_firefox_debug

Sorry, my bad. I'm using Windows 8.1, latest version of Firefox.

**Comment by rchrd2** [comment]
:+1: I was experimenting with using Web components in MeteorJS and ran into this issue as well. In Chrome, things work great, but then in Safari and Firefox events stop working.

Here's an example repo:

https://github.com/rchrd2/MeteorWebComponentsExample/tree/a9479a4fb81230a4b82e2cf2194dae3c77f1db54

**Comment by rchrd2** [comment]
Somebody else made this great example which also shows how to work-around the problem by wrapping the template in a div.

https://github.com/pfafman/meteor-polymer-event-test

Eg.

### Before (does not work)

```
<body>
    {{> hello}}
</body>
```

### After (works)

```
<body>
  <div>
    {{> hello}}
  </div>
</body>
```

**Comment by brylie** [comment]
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment]
Use polymer as the default view layer using mwc:synthesis package 
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by AndreasGalster** [comment]
Closing this. Synthesis is a great package that integrates Polymer perfectly into Meteor as the main view layer. I believe this is well on it's way to become the official Meteor <-> Polymer integration as a replacement for Blaze.
