### ISSUE TITLE
Wrong dependencies?

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#4093]
1) I create a Meteor project and remove the files meteor has created
2) I create a package `setup`, with a `package.js` file:
```js

Package.describe({
  summary: 'App setup',
  version: '0.8.0'
});

Package.onUse(function (api) {
  
  api.versionsFrom('1.0');

  // Dependencies
  api.use([
    'iron:router',
    'alanning:roles'
  ]);
});

```
3) I run `meteor add setup` and then `meteor`
4) Meteor logs:
```
The package alanning:roles at 1.0.6 is incompatible with Meteor 0.9.0 or later. 
If a new, compatible version of this package exists, running 'meteor update' should
cause you to update.
```
5) I run `meteor update` and Meteor logs:
```
This project is already at Meteor 1.1, the latest release.
Your packages are at their latest compatible versions.
```

[On atmosphere I can see](https://atmospherejs.com/alanning/roles), that `alanning:roles` has a version `1.2.13` which should be compatible (but I get `1.0.6`). Same for `iron:router`, I get version `0.9.1`, but it's  actually > `1.0.0`. Why does Meteor give me old versions instead of the newest, possible combination?

**Comment by stubailo** [comment]
I think this is working as intended - when Meteor 1.0 was released, the 1.0 of iron router was not released yet. Try using `api.versionsFrom("1.0")` and let me know?

**Comment by zimt28** [comment]
That's already in my code (above). I tried with and without `fromVersion` set, same result.

**Comment by stubailo** [comment]
Uhhh, sorry I made a typo, I meant `api.versionsFrom("1.1")`.

**Comment by zimt28** [comment]
I changed it, ran `meteor update` but I still get
```
Your packages are at their latest compatible versions.
```

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by offthegrass** [comment]
has this been fixed?

**Comment by glasser** [comment]
It's hard to know if bugs have been fixed without an appropriate reproduction. Your guess is as good as mine!
