### ISSUE TITLE
Can't publish meteor-tool

### ISSUE THREAD

**Issue by jboulhous** [meteor/meteor#4094]
Hello,

I try to publish my meteor-tool but without success.
```
$ meteor publish

=> Errors while publishing:                   
                                              
While pre-publishing package jboulhous:meteor-tool:
error: Match failed
```
the first meteor publish --create did not succed even if i can see jboulhous:meteor-tool in atmosphere.

I wonder if you could help resolve this.
Kind regards.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by glasser** [comment]
You should also specify what platform you're on, for example.

**Comment by glasser** [comment]
I found the matching error in the server logs.  It's a bad value in `dependencies.meteor.references[3].arch` which is supposed to only be `web.browser`, `web.cordova`, `os`, or `plugin`.  Unfortunately there's not an easy way to see what it is.  If you can provide a full reproduction, we can test it and find out.

**Comment by jboulhous** [comment]
Hello @stubailo @glasser ,
I actually try to define an arch `web.nwjs` like `web.cordova` to bundle client code into an [nw.js](https://github.com/nwjs/nw.js/) application. so we can have `Meteor.isNwjs`, `api.addFiles('code.js','web.nwjs')` and a `meteor nw-run [options]`.
Will it be possible to publish such an `arch` ?

**Comment by glasser** [comment]
It is not possible to publish bespoke arches to the package server.

**Comment by jboulhous** [comment]
Thank you.

**Comment by glasser** [comment]
See #2459.  Atmosphere does not currently support deleting packages, except as an expensive manual operation.  If  you need that operation performed (because you published private data, for example) contact contact@meteor.com.

**Comment by vicnala** [comment]
Hi @jboulhous. I'm just trying to do the same thing (bundle client code into an nw.js application) in the same way (as an arch).
I think this is a good approach for "headless devices".

You did it? Can you give some guidelines to start with?

**Comment by jboulhous** [comment]
Hi @vicnala .
I remember, i tried to do the same as mdg did for cordova.
It's been a while, and i think meteor-tool code base has significantly changed for 1.2...
I remember trying another lead, creating a package that bundles nw.js code by using meteor shell > MyPack.bundle('/local/path').
I must confess that all i had tried is only for fun, nothing for a business project.
And i will be glad to contribute in a clean solution to this need ...
