### ISSUE TITLE
TWBS/Bootstrap Crashing

### ISSUE THREAD

**Issue by jmar42** [meteor/meteor#4095]
I can't load TWBS/Bootstrap on Windows 1.1 Meteor.  Is there a fix for this?

**Comment by stubailo** [comment]
Works for me on Windows 7:

![screenshot](http://i.imgur.com/ZJdABln.png)

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
