### ISSUE TITLE
Chrome Flagged Windows Installer as Dangerous

### ISSUE THREAD

**Issue by bkwhite** [meteor/meteor#4096]
Just saw the email saying the official windows version was released and when downloading chrome said the file could be dangerous.

**Comment by stubailo** [comment]
:[ we did everything we could - it's even signed with a code validation certificate. Hopefully it will go away with time.

**Comment by bkwhite** [comment]
I just installed on a different computer and no problems this time.  Possibly it is fixed.

**Comment by stubailo** [comment]
OK going to close this for now and wait for future reports.
