### ISSUE TITLE
Error after 1.1 upgrade - Exception from Tracker recompute function: TypeError: Cannot read property 'destroyMembers' of undefined

### ISSUE THREAD

**Issue by risul** [meteor/meteor#4097]
Hello,

After update to meteor 1.1 today, I'm seeing this error in browser console:

```
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot read property 'destroyMembers' of undefined
    at view.js:357
    at tracker.js:234
    at Object.Tracker.nonreactive (tracker.js:560)
    at Tracker.Computation.onInvalidate (tracker.js:233)
    at Object.Tracker.onInvalidate (tracker.js:577)
    at doRender (view.js:356)
    at view.js:191
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at view.js:190
    at Object.Blaze._withCurrentView (view.js:521)
```

As far as I can see this error happens first time I visit a route.. because when I go to another route (after this error) and revisit the first route that gave me error, my route is rendered and everthing seems to be fine.

Could this be a Meteor bug?

**Comment by devyg** [comment]
Having same issue here ! For me it's for my user profile but the error is similar and just came after 1.1 upgrade. Meteor or Iron Router, how's guilty ?

**Comment by glasser** [comment]
Are you able to provide a reproduction, as described at https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor ?

**Comment by glasser** [comment]
@dgreensp @Slava  I think this might be a bug in 28c760e05c834a811362c873f2bbd1dd471f9aef ?

**Comment by dgreensp** [comment]
Fixed on `devel`; thanks for the report.
