### ISSUE TITLE
WARNING BACKUP DATA BEFORE UPGRADING TO METEOR 1.1 (Failed update eats data)

### ISSUE THREAD

**Issue by wmodes** [meteor/meteor#4102]
When I attempted to upgrade to Meteor 1.1, it failed ungracefully and nuked my data.  I recommend waiting to upgrade until this problem is solved.

    wmodes$ meteor update

    Changes to your project's package version selections from updating the release:

    accounts-password   upgraded from 1.1.0 to 1.1.1
    autoupdate          upgraded from 1.2.0 to 1.2.1
    blaze               upgraded from 2.1.0 to 2.1.1
    less                upgraded from 1.0.13 to 1.0.14
    meteor              upgraded from 1.1.5 to 1.1.6
    minifiers           upgraded from 1.1.4 to 1.1.5
    minimongo           upgraded from 1.0.7 to 1.0.8
    npm-bcrypt          upgraded from 0.7.8_1 to 0.7.8_2
    observe-sequence    upgraded from 1.0.5 to 1.0.6
    spacebars-compiler  upgraded from 1.0.5 to 1.0.6
    templating          upgraded from 1.1.0 to 1.1.1
    tracker             upgraded from 1.0.6 to 1.0.7

    meteor: updated to Meteor 1.1.
    => Errors while upgrading packages:

    While checking for yong:meteor-videojs@1.0.5:
    error: No compatible binary build found for this package. Contact the package author
    and ask them to publish it for your platform.

The upgrade went forward despite failed dependencies (and thus my failed application):

    wmodes$ meteor --version
    Meteor 1.1

But my biggest surprise, was when my data vanished. This looks like a clean install with all my collections missing.

    wmodes$ meteor mongo
    MongoDB shell version: 2.6.7
    connecting to: 127.0.0.1:3001/meteor
    meteor:PRIMARY> show databases
    admin   (empty)
    local   0.063GB
    meteor  0.031GB
    meteor:PRIMARY> use meteor
    switched to db meteor
    meteor:PRIMARY> show collections
    meteor_accounts_loginServiceConfiguration
    roles
    system.indexes
    users

Before upgrade, meteor was 0.064GB. So I lost 33 MB of data.

WTF? Help?

Any thoughts about what happened to my data? Was it in the midst of some kind of database mod when the upgrade bailed?

**Comment by glasser** [comment]
What version were you upgrading from?

This is surprising and doesn't match any area where 1.1 is different from 1.0.4 or 1.0.5. 

Is data actually gone, though? Eg, isn't roles a collection from your app? Are you sure that size isn't measuring some internal mongo stat that could be explained by mongo doing some sort of internal garbage collection?

And you didn't run `meteor reset`, right?

**Comment by wmodes** [comment]
Okay, embarrassedly, I have to admit that I did accidentally run `meteor reset` much earlier, but didn't see any database effects to my relief. Until the update.  I'll close this and sleek away.

**Comment by glasser** [comment]
That's reassuring!
