### ISSUE TITLE
`meteor run` doesn't output logged lines until they are complete

### ISSUE THREAD

**Issue by samhatoum** [meteor/meteor#4103]
I have a test framework that incrementally reports progress using green dots or red F's. When running from within Meteor, this 'live' incremental update to the user doesn't happen, instead the line is only output at the end of the test runs, which can take minutes, and the user doesn't know if a single test has stalled, or if the suit is running normally.

Upon further investigating, I've found that using `process.stdout.write('hello')` is not actually output until a new line is written to the stdout at a later time. The repro below demonstrates this.

[Repro here](https://github.com/xolvio/std-write-test)

**Comment by glasser** [comment]
To be clear, this is something that happens with the `meteor run` development server, not Meteor app servers being run in another context, right?

**Comment by samhatoum** [comment]
Yep, just bundled the app to be doubly sure and indeed it's in `meteor run` mode only

**Comment by glasser** [comment]
Yeah, this is a result of how we use `eachline` to display log lines one line at a time with timestamps and colors.

**Comment by samhatoum** [comment]
on the subject of timestamps, I would welcome a directive to disable them. My use-case is that I sometimes want to give the user a code-snip for them to copy/paste from the console. 

Cucumber (the same test framework that shows dots and Fs) detects undefined phrases and gives the user code snips they can use to implement. They currently look like this:

```
I20150402-21:51:57.211(-7)? 
I20150402-21:51:57.211(-7)? 1 scenario (1 undefined)
I20150402-21:51:57.211(-7)? 4 steps (1 undefined, 1 skipped, 2 passed)
I20150402-21:51:57.211(-7)? 
I20150402-21:51:57.211(-7)? You can implement step definitions for undefined steps with these snippets:
I20150402-21:51:57.211(-7)? 
I20150402-21:51:57.211(-7)? this.When(/^I visit "([^"]*)"$/, function (arg1, callback) {
I20150402-21:51:57.211(-7)?   // Write code here that turns the phrase above into concrete actions
I20150402-21:51:57.212(-7)?   callback.pending();
I20150402-21:51:57.212(-7)? });
I20150402-21:51:57.212(-7)? 
```

And this is difficult to copy/paste, which is the intention. 

Sorry I know that this is not about the bug specifically, I'm hoping that just maybe it could be something worth considering! :)

**Comment by Slava** [comment]
@samhatoum `meteor run --raw-logs`

**Comment by samhatoum** [comment]
Thanks Slava, that really helped with the timestamps

**Comment by abernix** [comment]
For those that need to avoid buffered output:

    meteor run --raw-logs

**Comment by RevelsGit** [comment]
How can I bypass this? --raw-logs doesn't help. Simple reproduction:
```
let i = 1;
const interval = setInterval(() => {
  process.stdout.write('='.repeat(i));
  i++;
}, 1000);
```
Result: Nothing is shown in the console.
Windows 10

**Comment by smeijer** [comment]
I think this one should be re-opened, as it's still an issue. `process.stdout.write` is not outputting anything, even with the `--raw-logs` option.

I do need this though, for example, while running a migration with `percolate:migrations`.
