### ISSUE TITLE
Can't access direct url for image (Mobile Dev)

### ISSUE THREAD

**Issue by anggaranc** [meteor/meteor#4104]
I just created apps for mobile that need to access image via external direct url but the image not showing in mobile apps but in browser it showing. what should i do?? ..the problem in second picture. thanks 

in browser:
![screenshot from 2015-04-02 16 47 29](https://cloud.githubusercontent.com/assets/4870810/6961725/08ce21b8-d958-11e4-9020-d9028e1f4b84.png)

in mobile:
![screenshot_2015-04-02-16-46-56](https://cloud.githubusercontent.com/assets/4870810/6961737/1b7d91ea-d958-11e4-9659-7775be757865.png)

**Comment by glasser** [comment]
What is the URL in question?

**Comment by anggaranc** [comment]
my code :
```
<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
        //image no 1 in my folder
	<img src="/banana.gif">
        //image no 2 in external url
    <img src="http://mutiarakatadangambargambar.com/wp-content/uploads/2013/03/gambar-kartun-20-580x435.jpg">
</template>
```

**Comment by timbrandin** [comment]
You need to add an accessrule for that domain or all domains like this ```App.accessRule('*')```.
But I can't seem to find App.accessRule in the Meteor docs, I guess it's coming soon :)

**Comment by anggaranc** [comment]
@timbrandin thx about the explanation. but what about the cordova ? when i run meteor on mobile use this code 
```
meteor run android-device --mobile-server my_app_link:3000
```
 the image not showing.

**Comment by anggaranc** [comment]
up,, please help me

**Comment by wolasss** [comment]
Add `mobile-config.js` to your app and add: `App.accessRule("*:/*/*.(jpg|png)", {launchExternal: false});
` . That will allow any images to load from an origin

**Comment by byrne-yan** [comment]
Same issue, any progress?

**Comment by byrne-yan** [comment]
I20150917-11:40:45.812(8) (android:http://meteor.local/journals/list:0) Image from origin 'https://sharebj.s3-ap-southeast-1.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://meteor.local' is therefore not allowed access. The response had HTTP status code 404.

It works on chrome browser on android!

**Comment by byrne-yan** [comment]
S3 CORS configuration:

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

**Comment by byrne-yan** [comment]
The issue solve by BrowserPolicy package!
    BrowserPolicy.content.allowSameOriginForAll();
    BrowserPolicy.content.allowOriginForAll("http://meteor.local");
    BrowserPolicy.content.allowOriginForAll(process.env.ROOT_URL);
    BrowserPolicy.content.allowOriginForAll("https://*.amazonaws.com");
    BrowserPolicy.content.allowEval();

**Comment by timbrandin** [comment]
Wow, awesome!! :)

2015-09-18 3:33 GMT+02:00 byrne-yan <notifications@github.com>:

> The issue solve by BrowserPolicy package!
> BrowserPolicy.content.allowSameOriginForAll();
> BrowserPolicy.content.allowOriginForAll("http://meteor.local");
> BrowserPolicy.content.allowOriginForAll(process.env.ROOT_URL);
> BrowserPolicy.content.allowOriginForAll("https://*.amazonaws.com");
> BrowserPolicy.content.allowEval();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/4104#issuecomment-141301867>.
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com
