### ISSUE TITLE
accounts-twitter configure message update

### ISSUE THREAD

**Issue by ksepehri** [meteor/meteor#4108]
Twitter has updated it's process so it would be good to update the Configure Service screen. Below are the updated steps, things in **bold** are my comments

First, you'll need to register your app on Twitter. Follow these steps:

1. Visit https://dev.twitter.com/apps/new
2. Set Website to {{URL}}
3. Set Callback URL to: {{URL}}/_oauth/twitter
4. Select "Create your Twitter application".
5. On the Settings tab, enable "Allow this application to be used to Sign in with Twitter" and click "Update settings".  **This is now enabled by default. Should this step still be there?**
6. Switch to the "Keys and Access Tokens" tab.

**Comment by glasser** [comment]
Great, care to send a pull request?  The relevant code is in `packages/twitter`.
