### ISSUE TITLE
meteor shell shouldn't listen until after running app code

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#4109]
Once a `meteor shell` server listens, it "locks" the global `_` such that it can't be redefined.  Right now the server starts listening at startup, so that can be before the `underscore` package's global export gets written to global `_`!  There's a replication at https://github.com/meteor/meteor/issues/4010#issuecomment-88669681 (for me, you don't even need to run moment because there's a `_.each` in todos' bootstrap.js, though you need to meteor reset each time you test this).

Probably the shell server should do its listen in a Meteor.startup block.

**Comment by glasser** [comment]
(Alternatively, figuring out a way that we can get the right level of tab-completion/etc without making the repl context be global would be nice, or patching Node so that instead of receiving the last value via `self.context._ = ret;` there's a custom callback.)

**Comment by glasser** [comment]
Consistent reproduction:

```
shell1$ git clone https://github.com/glasser/issue-4109
shell1$ cd issue-4109
shell1$ meteor shell
# leave it running; then
shell2$ meteor
```

Should see this crash in shell2:

```
W20150402-12:11:45.484(-4)? (STDERR) TypeError: Cannot call method 'each' of undefined
W20150402-12:11:45.484(-4)? (STDERR)     at app/issue-4109.js:1:57
W20150402-12:11:45.484(-4)? (STDERR)     at app/issue-4109.js:3:3
W20150402-12:11:45.485(-4)? (STDERR)     at /private/tmp/issue-4109/.meteor/local/build/programs/server/boot.js:224:10
W20150402-12:11:45.485(-4)? (STDERR)     at Array.forEach (native)
W20150402-12:11:45.485(-4)? (STDERR)     at Function._.each._.forEach (/Users/glasser/Projects/Meteor/meteor/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150402-12:11:45.485(-4)? (STDERR)     at /private/tmp/issue-4109/.meteor/local/build/programs/server/boot.js:119:5
```

**Comment by iameli** [comment]
Thanks for looking into this. I agree -- running the REPL in the global context for the benefit of getting tab completion seems a bit heavy-handed.
