### ISSUE TITLE
Upgrade SockJS client

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#4114]
A fair amount of work has been done on the SockJS client lately. It hasn't been fully release as 1.0.0 yet, but it's probably worth investigating anyway.

If nothing else, it fixes some issues where SockJS client crashes when it reads invalid JSON (say, from  `/sockjs/info` when your app is crashing) which leads to long (eg 8 second) timeouts before retrying.

Note that there seem to be some compatibility changes in 1.0.0, like protocols_whitelist no longer working, and Meteor contains some local changes to the client as well (tagged with `<METEOR>`).

**Comment by abernix** [comment]
I spent some time on this today with successful results (i.e. it works).  In fact, it would seem that all the `<METEOR>` tagged changes are all linked to issues which have been resolved.  There's one of those hacks that I still need to evaluate the necessity of.

Unfortunately, the new version adds over 100KB to the _compressed_ size (170KB vs 70KB) of the `ddp-client.js` that is shipped to the client.  I think this is a fairly substantial and potentially unacceptable increase in size and I'm going investigate the feasibility of slimming it down.

**Comment by glasser** [comment]
Out of curiosity, what's been added in the new version that makes it so big?

**Comment by abernix** [comment]
I guess I should clarify that the size increase stated was in development mode, so less alarming as the production bundle would be minified.  Still a big jump.  I just did a quick test of the production size and it's only an increase of 10KB on the final JS resource bundle, so a lot less alarming.

I'll still look into it though as it's not really clear at first glance or from the Changelog.  The file size difference of the _uncompressed_ [distribution](https://github.com/sockjs/sockjs-client/tree/master/dist) in their repo is 282KB between 0.3.4 and 1.1.1 – a huge increase.  JSON2 was commented out of the old version on the Meteor side but that only affects the minified production version for the sake of this comparison.  The new version comes with JSON3.

Anyhow, more on this soon.

**Comment by hwillson** [comment]
Let's track this issue under FR https://github.com/meteor/meteor-feature-requests/issues/216. Closing here - thanks!
