### ISSUE TITLE
Upgrading older projects to 1.1 on Windows

### ISSUE THREAD

**Issue by tomutiger** [meteor/meteor#4116]
There are example projects built with older versions of Meteor (<1.1) which I have been having difficulty making work on windows. I cannot upgrade the project to Meteor 1.1 nor can I remove the problem package from the project. The problem stems from the use of various packages which do not have a windows distribution yet. 

To Reproduce the issue:
1. install Meteor 1.1 on Windows
2. get a copy of a project (https://github.com/themeteorchef/saas-stripe). This project used 1.0.3.1.
3. Update to latest Windows (meteor update --release METEOR@1.1.0.1)
- This fails because package particle4dev:sass does not have a windows distribution
  1. Remove the offending package(meteor remove particle4dev:sass)
  2. This fails because meteor is not supported on Windows for version less than 1.1
  3. No further progress can be made using Windows.

Workaround
1. I have found you can upgrade the project to Meteor 1.1 using an OS other than Windows (like Linux).
2. Move project to Windows
3. execute the meteor remove particle4dev:sass package 
4. then the project works.

Expected Behavior
1. have the meteor update command complete the upgrade with warnings or offer the option to complete the upgrade.  During the upgrade the problem package could be removed.

**Comment by stubailo** [comment]
Good idea! Btw the newest version of `fourseven:sass` works on Windows.

**Comment by avital** [comment]
You can also edit the package list directly in `APP_DIR\.meteor\packages`.

**Comment by hwillson** [comment]
Given that Meteor 1.1 was released 1.5 years ago, I think it's safe to assume people affected by this problem have found a workaround. Closing this off - thanks!
