### ISSUE TITLE
Major load-time difference on meteor servers

### ISSUE THREAD

**Issue by mikepaszkiewicz** [meteor/meteor#4117]
Identical deployments, but one takes around 20 seconds to respond and load the page. We are in beta testing on iOS and our app won't run because of this delay.

**Comment by stubailo** [comment]
Does it reproduce over multiple loads of the same app? Sometimes the first load after deploying is particularly slow.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by mikepaszkiewicz** [comment]
yep, seemed to be some kind of isolated situation that resolved itself - forgot i even made the issue. thanks!
