### ISSUE TITLE
Program has no main() function.

### ISSUE THREAD

**Issue by HedCET** [meteor/meteor#4123]
I am currently running Meteor in MAC Yosemite & Meteor 1.1.0.1, it shows error "Program has no main() function." & i tried it again after deleting .meteor/local folder get same error

https://github.com/HedCET/errorA

![screen shot 2015-04-04 at 8 43 41 pm](https://cloud.githubusercontent.com/assets/1794209/6993245/ea8a642c-db0b-11e4-8ad7-3bf89c3fe7ce.png)

**Comment by HedCET** [comment]
![Uploading Screen Shot 2015-04-04 at 9.04.30 pm.png . . .]()

**Comment by jhuenges** [comment]
http://docs.meteor.com/#/full/structuringyourapp

you might need a client folder and some files

**Comment by HedCET** [comment]
@jhuenges i don't think that's the reason becoz my another meteor 1.1.0.1 project run without client folder https://github.com/HedCET/useragents_updater

**Comment by thinklinux** [comment]
You packajes file is rather empty... https://github.com/HedCET/errorA/blob/master/.meteor/packages

You need some core packages to run meteor. You can try and add meteor-platform.

```
meteor add meteor-platform
```

I don't know why you don't have that package. Here what it is:
https://atmospherejs.com/meteor/meteor-platform

**Comment by jboulhous** [comment]
The way meteor is working now, is that server packages (app code is also "considered" a package) have to export only one main function.
the `webapp` package is the core package that exports `main` function, take a look at its code, meteor-platform uses webapp.
if you don't want to use webapp, you should export a main function in one of your packages or in app server code, and this `main function needs to return 'DEAMON'` and needs to start some sort of process that would not let the app shutdown, as an `http server` or `net server`.

**Comment by Slava** [comment]
As @jboulhous correctly pointed out, Meteor expects a function called `main` to be available. When you get rid of the `WebApp` package, the main function is gone with it. It is quite weird that this behavior is not documented anywhere, but it is also a subject to a change in the future.

The behavior described by the OP is not a bug.
