### ISSUE TITLE
Meteor 1.1.0.1 error with Object.prototype

### ISSUE THREAD

**Issue by wmodes** [meteor/meteor#4126]
When I upgraded to 1.1.0.1 I started getting an exception:

```
W20150404-23:10:20.595(-7)? (STDERR) /Users/wmodes/.meteor/packages/meteor-tool/.1.1.2.crfslw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150404-23:10:20.596(-7)? (STDERR)                            throw(ex);
W20150404-23:10:20.596(-7)? (STDERR)                                  ^
W20150404-23:10:20.648(-7)? (STDERR) Error: Update parameter cannot have both modifier and non-modifier fields.
W20150404-23:10:20.648(-7)? (STDERR)     at isModificationMod (packages/mongo/mongo_driver.js:560:1)
W20150404-23:10:20.648(-7)? (STDERR)     at [object Object].MongoConnection._update (packages/mongo/mongo_driver.js:484:1)
W20150404-23:10:20.648(-7)? (STDERR)     at [object Object].<anonymous> (packages/meteor/helpers.js:118:1)
W20150404-23:10:20.648(-7)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
W20150404-23:10:20.648(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/mongo/collection.js:575:1)
W20150404-23:10:20.648(-7)? (STDERR)     at Object._.extend._updateUserRoles (packages/alanning:roles/roles_common.js:680:1)
W20150404-23:10:20.648(-7)? (STDERR)     at Object._.extend.addUsersToRoles (packages/alanning:roles/roles_common.js:145:1)
W20150404-23:10:20.649(-7)? (STDERR)     at app/server/defineroles.js:27:13
W20150404-23:10:20.649(-7)? (STDERR)     at Array.forEach (native)
W20150404-23:10:20.649(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
=> Exited with code: 8
```

So I temporarily uninstalled alanning:roles and removed references to its methods, but I still seem to be getting a related error

```
W20150404-23:59:15.854(-7)? (STDERR) /Users/wmodes/.meteor/packages/meteor-tool/.1.1.2.crfslw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150404-23:59:15.854(-7)? (STDERR)                            throw(ex);
W20150404-23:59:15.854(-7)? (STDERR)                                  ^
W20150404-23:59:15.854(-7)? (STDERR) TypeError: Cannot call method 'documentMatches' of undefined
W20150404-23:59:15.855(-7)? (STDERR)     at [object Object].LocalCollection.insert (packages/minimongo/minimongo.js:566:1)
W20150404-23:59:15.855(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/mongo/collection.js:575:1)
W20150404-23:59:15.855(-7)? (STDERR)     at updateVersions (packages/autoupdate/autoupdate_server.js:97:1)
W20150404-23:59:15.855(-7)? (STDERR)     at packages/autoupdate/autoupdate_server.js:161:1
W20150404-23:59:15.855(-7)? (STDERR)     at /Users/wmodes/dev/secrethistory/meteor/.meteor/local/build/programs/server/boot.js:229:5
```

At this point, I'm out of my depth.  Any clue to my errors?

**Comment by wmodes** [comment]
I think this might have been caused by this code:

    Object.prototype.isin = function() {
        for(var i = arguments.length; i--;) {
            var a = arguments[i];
            if(a.constructor === Array) {
                for(var j = a.length; j--;)
                    if(a[j] == this) return true;
            }
            else if(a == this) return true;
        }
        return false;
    }

I think this might be related to this issue, though we thought it was resolved in January.  I've removed the code, and am now checking if I still have the problem with alanning:roles

**Comment by wmodes** [comment]
I solved my problem by removing the offending code, but I'll leave this open in case anyone wants to address the problem with meteor +  Object.prototype

**Comment by timhaines** [comment]
I'm not sure it's related, but after updating to 1.1.0.1 in dev, we're seeing issues in the client accessing LocalCollection._recomputeResults, which meteor sets on the prototype here:  https://github.com/meteor/meteor/blob/devel/packages/minimongo/minimongo.js#L920

Rolling back to 1.0.2, and there's no problem.

**Comment by glasser** [comment]
@timhaines Any chance of being more precise --- there were a lot of versions between 1.0.2 and 1.1.0.1 :)

**Comment by timhaines** [comment]
@glasser I certainly can be.  I'll report back.

**Comment by timhaines** [comment]
@glasser 1.0.3 is good, the problem arrives in 1.0.4

**Comment by timhaines** [comment]
This happened in the [changes](https://github.com/meteor/meteor/compare/release/METEOR@1.0.3...release/METEOR@1.0.4) between 1.0.3 and 1.0.4 (in minimongo.js):

![image](https://cloud.githubusercontent.com/assets/19700/7058253/d641c220-de13-11e4-96b1-25f67fdf9a47.png)

**Comment by glasser** [comment]
You mean you're calling that internal function in your code and it no longer exists?

BTW I'm not sure how this is related to the rest of this issue.

**Comment by timhaines** [comment]
@glasser The more I learn about it, the more I agree that it probably doesn't relate to this issue.  Without looking too deep, maybe it relates to #3478, maybe not.  

We are calling that internal function.  Why would it moving to the prototype mean it no longer exists?  BTW - this is perhaps getting too far off-topic.  Happy to move to email if you prefer.

**Comment by timhaines** [comment]
@glasser Juggling too much today over here.  Agree, unrelated.  Cleared the comments/noise.

**Comment by glasser** [comment]
Possibly related to #3478

**Comment by wmodes** [comment]
Definitely related. I wouldn't have guessed that was the problem, but I found that issue and that let to my solution/workaround.

**Comment by hwillson** [comment]
Closing here since this issue is being tracked in #3478. Thanks!
