### ISSUE TITLE
Unexpected mongo exit code 1. Restarting.

### ISSUE THREAD

**Issue by maxfinnsjo** [meteor/meteor#4129]
I have Ubuntu 14.04 running kde

"node -v" outputs "v0.10.38"
I go to meteor.com/install today (april 5th) and copy the command "curl https://install.meteor.com/ | sh" and run it, it installs meteor, it installs fine and I run "meteor create try-meteor" i cd to try-meteor and run "meteor" i get:

"[[[[[ ~/code/try-meteor ]]]]]                 

=> Started proxy.                             
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Can't start Mongo server."

I have tried uninstalling and reinstalling meteor a couple of times, with the above command, and with the git clone as described on the github page. I have tried all sort of stuff but nothing seems to work. Any ideas? I am not the most experienced linux user btw. Thanks for any ideas!!

**Comment by Sindis** [comment]
Check how much free space you have, I had this problem when I had less than 450 MB. Also, you can outsource your DB to mongolabs for example.

**Comment by glasser** [comment]
It's possible that this is the same bug as #4115 which we are in the process of fixing.  What does `ps ax | grep mongod` say?

**Comment by maxfinnsjo** [comment]
@glasser after running "ps ax | grep mongod" i get " 3045 pts/2    S+     0:00 grep --color=auto mongod"

@Sindis on linux I got different parts of the system on differennt mounts right, or some such. It seems all my partitions have more than 450 mb except on /boot/efi - and yes I am dualbooting with windows 8 on my machine. 

Thanks for your replys and time!

**Comment by maxfinnsjo** [comment]
just updated and get the same error.. =/

**Comment by maxfinnsjo** [comment]
I am SO sorry guys... I just logged in to standard ubuntu unity and, voila, meteor works again. So sorry to waste someones time, although not being able to run on kde seems to a problem also.. Anyways. CLOSE!!

**Comment by glasser** [comment]
Yeah, this doesn't sound like this was #4115.  Glad to hear this works for you now though!

**Comment by tech-no-crat** [comment]
Still running into this issue with node v0.10.30

**Comment by seeekr** [comment]
In case anyone else will be looking here: The problem can be about not properly configured / installed locale, e.g. fix in Ubtunu by doing `locale-gen de_DE.UTF-8`, using the locale that's appropriate for you. Mongo tools seem unable to handle missing locale.

**Comment by moneroexamples** [comment]
Had the same problem on Arch Linux.

Playing with locale settings and make fixed the issue

**Comment by bush** [comment]
I'm currently seeing this issue in a docker container created from a ubuntu:16.04 image. I resolved it like this in my Dockerfile:

FROM ubuntu:16.04
ENV OS_LOCALE="en_US.UTF-8"
RUN locale-gen ${OS_LOCALE}
ENV LANG=${OS_LOCALE} \
LANGUAGE=en_US:en \
LC_ALL=${OS_LOCALE}
RUN apt-get update && apt-get -y install curl locales && curl https://install.meteor.com/ | sh
