### ISSUE TITLE
Error output colors are hard to see in Windows PowerShell

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4133]
Copied screenshot from https://github.com/meteor/windows-preview/issues/142

![](https://cloud.githubusercontent.com/assets/86080/6861408/7756d7b4-d49a-11e4-8437-786cead8e049.png)

**Comment by hwillson** [comment]
Just a quick note - I've verified this is still an issue with Meteor 1.5.1.

**Comment by hwillson** [comment]
https://github.com/meteor/meteor/pull/9170 fixes this and has been merged. Closing - thanks!
