### ISSUE TITLE
Meteor.absoluteUrl.defaultOptions.rootUrl does not work

### ISSUE THREAD

**Issue by linhkurt** [meteor/meteor#4136]
I have the following code on client:
<pre><code>
Meteor.startup(function () {
	console.log('client startup');	
	Meteor.absoluteUrl.defaultOptions.rootUrl = "http://localhost:3000/app1";	
	console.log(Meteor.absoluteUrl()); //this line prints out http://localhost:3000/app1
});
</code></pre>

And then i run:
<pre><code>
meteor run ios
</code></pre>
However, on simulator, my app is still spinning, because it still points to localhost:3000 i think, while i only have router for '/app1'.

I also tried <code>ROOT_URL=http://localhost:3000/app1 meteor run ios</code>, but it also does not work.

My intention is to bundle different app with different rootURL (/app2, /app3, ..) but use the same server code base. How could I do that?

Thank you.

**Comment by MoeBadr** [comment]
Try: 

server side: 
`Meteor.startup(function () {`
 `process.env.MOBILE_DDP_URL = 'xx';`
 `process.env.MOBILE_ROOT_URL = 'xx';`
`});`

**Comment by linhkurt** [comment]
Thank you MoeBard but I want to set it on client side, so I can have multiple client app point to the same server. The <code>app1</code> in <code>http://localhost:3000/app1</code> is actually a parameter to let server know which client it is and serve the right content.

**Comment by MoeBadr** [comment]
sorry, I didn't understand the question. I'm currently using `meteor build --server xx --architecture os.linux.x86_64 build` to build meteor for production, have you tried doing multiple builds each pointing to different url using `--server` ? `--server` is the location where mobile builds connect to the Meteor server.

**Comment by glasser** [comment]
Have you tried using the `--mobile-server` argument to `meteor run`?

Note that `absoluteUrl.defaultOptions` is an internal undocumented API.

**Comment by linhkurt** [comment]
Thanks Glasser. I tried --mobile-server but the app is still empty. BTW, is there any way to give client app some intial parameter. Like, I want to have some initial settings for the app (Free and Paid versions, for example), which use the same server/db instance. And then based on that setting (free/paid), my templates will render different things.....?

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by linhkurt** [comment]
Sorry if I make you angry, already posted on Stackoverflow, I get stuck so I seek for help everywhere.
