### ISSUE TITLE
favicon.ico not found on hard reload

### ISSUE THREAD

**Issue by alitavector** [meteor/meteor#4139]
First time Hard Reload or Empty Cache and Hard Reload will log an error. On subsequently reload page, the error will not appear.
http://i61.tinypic.com/2edr1ja.png

Tested on Meteor 1.1.0.1 Windows 7 64-bit.

**Comment by Tarang** [comment]
Where is the favicon in your project? Is it in the root project directory, or in the `public` directory?

**Comment by alitavector** [comment]
Nope, I don't use favico and don't have such code in my html files, it was invoked for unknown reason.

**Comment by Tarang** [comment]
@alitavector The favicon is always requested by the browser.

If none is found nothing is displayed next to the URL in the browser as an icon. This is the expected behaviour unless I'm missing something?

**Comment by Slava** [comment]
This doesn't look like a bug. If your site doesn't have a favicon, I see nothing wrong in getting this error.

(Thanks @Tarang  for looking at this.)
