### ISSUE TITLE
(Windows) Meteor shell exits when server code changes

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#4146]
**_4 Upvotes**_ When **server** code is updated, the Meteor shell exits with the following error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
```

**Comment by thinklinux** [comment]
Can you give example code that is reproducing the problem? And on which Windows?

**Comment by rclai** [comment]
Windows 7 Pro. 

Is it so hard for you guys to create a server file, run meteor shell at the same time, edit the file and save?

**Comment by bluebay** [comment]
+1.

**Comment by 285858315** [comment]
+1

**Comment by glasser** [comment]
Hmm.  This does work on Mac, at least; the shell client is supposed to reconnect.  I wonder which object this is being thrown on...  The shell client does set an error handler on the socket!  (It removes it on the first error though.)

**Comment by bluebay** [comment]
> I wonder which object this is being thrown on... 
Is there anyway I could find out which object is being thrown?

**Comment by bhupesh** [comment]
+1

**Comment by Kaizeras** [comment]
+1

**Comment by neil-s** [comment]
This issue has been open for nearly a year now. MDG members, have you been able to replicate this issue or can I help with that?

Broadly, the steps are:
1) Run any Meteor project
2) Connect to the meteor shell
3) Edit your server code. If you save your code mid-edit, it will likely have syntax errors, causing the server to error out.
4) Shell will have disconnected

Meteor 1.2, Windows 10

**Comment by abernix** [comment]
This was a problem at one time, but should be fixed in the latest version of Meteor.  Thanks for reporting this!  Please report back if you're still having issues with it.
