### ISSUE TITLE
mongo uri title case username

### ISSUE THREAD

**Issue by J-Katzen** [meteor/meteor#4148]
When trying to use a MONGO_URL or MONGO_OPLOG_URL with a title case username as part of the authorization, receive this error when booting meteor:

starting meteor app on port:80 
```
/built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:246 
                ^ 
          throw message;       
  TypeError: Cannot read property 'done' of null 
      at /built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/auth/mongodb_scram.js:165:17 
      at Server.Base._callHandler (/built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41) 
      at /built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1903:9 
      at [object Object].emit (events.js:95:17) 
      at [object Object].<anonymous> (/built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20) 
      at /built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:487:18 
      at /built_app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1194:16 
      at [object Object].MongoReply.parseBody 
```

Once I created a new user with only lower case characters in it, worked fine

**Comment by Slava** [comment]
This looks like a bug in Node MongoDB native driver. You can report it here: https://github.com/mongodb/node-mongodb-native

Also, we require a reproduction with the bug reports.

**Comment by glasser** [comment]
Yeah, looks fixed recently in the driver:
https://github.com/mongodb/node-mongodb-native/commit/b53fc41e659756a3a8632e5f3e195b74cf6fb44c
https://jira.mongodb.org/browse/NODE-382

(It's an error handling issue, so something was wrong with your setup anyway I guess.)
