### ISSUE TITLE
[BUG]Phonegap: Filesystem dies after 990ish queries.

### ISSUE THREAD

**Issue by henryj** [meteor/meteor#4151]
How to reproduce:

<blockquotes>
meteor create fs
cd fs
meteor add-platform ios
meteor run ios-device -p 192.168.0.5:3000 --mobile-server 192.168.0.5:3000
</blockquotes>

Run the app from xcode. Then open safari console. Run:
<blockquotes>
var i=0;
setInterval(function(){  
    i++;
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function(){
        console.log(i)
    }, null);
}, 10);
</blockquotes>

Dies after 990ish. And any calls related to disk will not work after that.

Tested on a blank phonegap app, same thing works fine:
<blockquotes>
cordova create cfs
cd cfs
cordova platforms add ios
cordova plugin add https://github.com/apache/cordova-plugin-file#r1.3.3
cordova build
</blockquotes>

Open in xcode and run the same thing from safari console. Never dies.

It kinda affects everything about disk r/w. I found this when using the sqlite plugin and thought something wrong with that plugin but after cleaning up and testing, it turned out to be the filesystem itself.

**Comment by Slava** [comment]
We usually require a clonable reproduction demonstrating the issue with every bug report.

My understanding always was that `requestFileSystem` is unstable and breaks quite often in Cordova. It is possible that you are running a different version of cordova on your machine (as opposed to the version that Meteor uses), here is a very active ticket that occasionally gets new comments. https://issues.apache.org/jira/browse/CB-6667

**Comment by henryj** [comment]
You're probably right about the versions. I have the latest cordova while meteor is one small version behind as I remember. But it's not just <code>requestFileSystem</code>, <b>ANY</b> local disk operations will kill the disk after 990ish queries. 

And it happens to all Meteor - cordova projects for me.(at least ios ones. haven't tried others.) So basically I just open any or a blank meteor project with ios platform and do whatever disk queries. It happens when hits that mark. 

Unless it's something wrong with my setup and not happening to everyone, this is s a pretty serious issue as all the meteor apps now with disk operations cannot last. If my users use the app a lot without killing it, it dies after a while.

BTW, is there a way to change the cordova version that meteor uses? so I may test and work this around temporarily?

**Comment by Slava** [comment]
@henryj you can test if upgrading to the latest Cordova by going into your latest version of Meteor on disk, and running `npm install cordova` in the dev_bundle folder. For me it is:

```bash
cd ~/.meteor/packages/meteor-tool/.1.1.3.1hnp8oq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib
npm install cordova
```

Then recompile the app. (make sure that your app also uses the latest Meteor, the one that you just updated).

If this helps, it might make sense to make a release updating Cordova dependencies.

**Comment by henryj** [comment]
Yep. Just tested and it worked. Thanks.
