### ISSUE TITLE
Need loginWith<service>Mobile methods

### ISSUE THREAD

**Issue by sslotsky** [meteor/meteor#4152]
Now with Meteor supporting hybrid mobile apps, it's quite conceivable to have a single app that functions as both a web app and a native mobile app. The Oauth callback URL's will differ depending on the client though, so it seems that native mobile clients and web browsers need to login using a different clientID & secret.

I propose that for each external service supported, there should be an option to specify two configs - one for web, and one for mobile. Using Github as an example, we would create two service configurations - `github` and `github-mobile`. `loginWithGithub` would continue to use the `github` configuration and `loginWithGithubMobile` would use the `github-mobile` configuration.

I imagine this would be a simple refactoring to pull these off.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Need%20loginWith%3Cservice%3EMobile%20methods&body=Migrated%20from:%20meteor/meteor%234152) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
