### ISSUE TITLE
Support for package.coffee files

### ISSUE THREAD

**Issue by chmac** [meteor/meteor#4153]
**_1 Upvote**_ It would be awesome if meteor supported `package.coffee`, `package.coffee.md` and `package.litcoffee` files in packages.
# featureRequest

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Supporting arbitrary plugin-based package metadata files is architecturily infeasible.  It's possible we might support CoffeeScript specifically someday.  (We'll see how popular CS continues to be as ES6 support increases!)

**Comment by lalomartins** [comment]
Even with ES6, there are a few reasons why a developer might prefer package.coffee. For example: it's a lot more legible, and in JS if you want to add another file to the list you always have to be mindful of your commas. Compare:

```js
Package.describe({
    name: 'lalomartins:my-package',
    version: '0.0.1',
    summary: 'Do some stuff',
    git: 'https://github.com/lalomartins/notarealurl.git',
    documentation: 'README.md'
});

Package.onUse(function(api) {
    api.versionsFrom('1.1.0.2');
    api.use([
        'coffeescript'
    ]);
    api.addFiles([
        'rules.coffee',
        'cards.coffee'
    ]);
});
```

```coffeescript
Package.describe
    name: 'lalomartins:my-package'
    version: '0.0.1'
    summary: 'Do some stuff'
    git: 'https://github.com/lalomartins/notarealurl.git'
    documentation: 'README.md'

Package.onUse (api) ->
    api.versionsFrom '1.1.0.2'
    api.use [
        'coffeescript'
    ]
    api.addFiles [
        'rules.coffee'
        'cards.coffee'
    ]
    return
```

You don't even need to know CoffeeScript… just think of it as a cheap DSL ;-)

**Comment by biofractal** [comment]
:+1: 

I just assumed this would work and spent a while figuring out why I was getting the error:

```
 error: unknown package in top-level dependencies:
```

 Meteor spoils us with their coffeescript support so I suppose I shouldn't grumble, but is feels uncomfortable having to remember to put in all those extraneous commas, brackets etc again.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20for%20package.coffee%20files&body=Migrated%20from:%20meteor/meteor%234153) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
