### ISSUE TITLE
Minimongo $push does not implement $position modifier

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4158]
***1 Upvote*** ![image](https://cloud.githubusercontent.com/assets/251288/7060843/7813519e-de3d-11e4-8c14-3cda539dd643.png)

At first, 2 appears after 1, but when the client gets the update from the server, it switches to the correct order. It would be nice to have it in the correct order to start out, so you don't get that visual switch.

Reproduction:

https://github.com/lorensr/repro-minimongo-position

**Comment by BlooJeans** [comment]
+1

**Comment by glasser** [comment]
Yeah, `$position` didn't exist when we implemented the other `$push` modifiers in 3aca36aac4bfbf0d2f5a5ed34b777c79e2be691e.  Happy to take a PR (with tests!)

**Comment by glasser** [comment]
(And maybe it should be an error to use an unknown `$` option to `$push`!)

**Comment by dferber90** [comment]
I also extended the reproduction repo: https://github.com/dferber90/repro-minimongo-position.
It now delays the publication of changes so that the initial wrong order is visible longer.

**Comment by laosb** [comment]
As the pr was merged, closing.
