### ISSUE TITLE
MongoDb Query $where Operator Problem

### ISSUE THREAD

**Issue by engenheiro** [meteor/meteor#4159]
The javascript function dont works on MongoDb Query $where operator. 

I running Meteor on Windows 8.

http://docs.mongodb.org/manual/reference/operator/query/where/

My problem:

http://stackoverflow.com/questions/29530528/working-with-personalized-operators-on-mongodb-find-method/29530810?noredirect=1#comment47216360_29530810

**Comment by Slava** [comment]
We usually keep GitHub issues for bugs and feature request discussions. A good place for questions is Stackoverflow (and looks like you've got an answer) and the Meteor Forums.

Good luck.

**Comment by engenheiro** [comment]
Yep, i think its a bug. Meteor have problems to execute functions in $where.

**Comment by Slava** [comment]
@engenheiro you would need to provide a reproduction app demonstrating the issue. This would be a much better way to report a bug then a link to a stackoverflow comment.

**Comment by engenheiro** [comment]
Ok, I have a simple example for this, from: http://docs.mongodb.org/manual/reference/operator/query/where/#examples

//This works
db.myCollection.find( { $where: "this.credits == this.debits" } );
db.myCollection.find( { $where: "obj.credits == obj.debits" } );

//This dont works:
db.myCollection.find( { $where: function() { return (this.credits == this.debits) } } );
db.myCollection.find( { $where: function() { return obj.credits == obj.debits; } } );

The function in $where dont execute the command.

**Comment by Slava** [comment]
@engenheiro looks like the code you have posted is a snippet from Mongo Shell. If you claim this to be a bug in Meteor, please provide a reproduction (in a form of a clonable repo containing a Meteor app) that demonstrates the issue in Meteor.
