### ISSUE TITLE
During Meteor Installation, the installation terminates even if there is a network disconnection for 200 msec

### ISSUE THREAD

**Issue by meghadev** [meteor/meteor#4160]
installing Meteor using 
curl https://install.meteor.com | sh

I am unable to finish the installation. Even if there is a slightest disconnection, the complete installation process needs to be started all over again. There should be an option to resume the installation atleast.
Just not able to setup meteor on my system. Installation terminated multiple times at 2.5%, 5.7%, 16.2%, 45.3%, 53.4%, 85.1% ... and so on.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

The installer uses `curl` to download the Meteor distribution. There might be something that can be done here with the `-C` and `--retry` options.

**Comment by meghadev** [comment]
I need to use the -C or --retry options while using the curl command or You will add this to the install script? or you will update the install command, as specified on your website?

**Comment by glasser** [comment]
The installer script at install.meteor.com could be improved to use these options.

**Comment by abernix** [comment]
Thanks for reporting this issue originally!  This has been greatly improved thanks to #7348.  The installer now supports retrying and resuming interrupted downloads.
