### ISSUE TITLE
Strange order of life-cycle callbacks in Blaze

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4166]
When a template includes (`outer`) another template (`inner`), then `onDestroyed` callback of the `outer` template is called first before the `inner`. This is really strange for any cleanup one might want to do.

See this example: https://github.com/mitar/meteor-issue4166 Open the web console and type `Session.set('flag', true);`. The order of life-cycle callbacks will be:

```
onCreated outer
onCreated inner
onRendered inner
onRendered outer
onDestroyed outer
onDestroyed inner
```

But probably a more reasonable order would be:

```
onCreated outer
onCreated inner
onRendered inner
onRendered outer
onDestroyed inner
onDestroyed outer
```

I propose this to be switched around.

**Comment by Slava** [comment]
The order is indeed surprising. I would love to hear more about the ways people use `onDestroyed` callbacks to clean up. And what is the reasoning behind one order as opposed to another. I would also review a PR on this.

**Comment by jamgold** [comment]
I recently created this [Meteorpad](http://meteorpad.com/pad/iGPEhrNemEcfGvqz8/Meteor%20Template%20Event%20Sequence) to illustrate similar confusion with the order of template callbacks. In my case the outer template does a subscribe onCreated, but according to the logs gets called **after** onRendered.

**Comment by mitar** [comment]
Just a followup, this is fixed in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components).

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#177 - closing - thanks!
