### ISSUE TITLE
Meteor.bindEnvironment loses context

### ISSUE THREAD

**Issue by aramk** [meteor/meteor#4169]
If you use `Meteor.bindEnvironment()` as a callback and the code executing the returned function uses `.call()` or `.apply()`, the context `this` is lost to the given context `_this` which is typically undefined. I think there should be a line like `_this = _this || this;`.

Occurrences:
https://github.com/meteor/meteor/blob/556c0e28e94b9351cbf0b28e80a71a4e35f1362a/packages/meteor/dynamics_nodejs.js#L108
https://github.com/meteor/meteor/blob/devel/packages/meteor/dynamics_browser.js#L51

**Comment by glasser** [comment]
I don't think your fix works, since `this` inside runEnvironment isn't particularly well-defined either.

I'm not sure that adding yet another special case rule where you can count on `this` being preserved makes code easier to reason about than just saving `this` yourself.  Can you show an example of code that you wrote where you needed to care about the value of `this` in a callback?

**Comment by aramk** [comment]
I was using `Meteor.bindEnvironment()` in the [collection-hooks](https://github.com/matb33/meteor-collection-hooks) package on the server. Since it provides `this.previous()` the context must be set correctly in the callback.

**Comment by nelsonec87** [comment]
No solution yet? =(

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/4169#issuecomment-93070137, addressing this issue in the Meteor codebase might not be the best solution. Regardless, this issue has received very little interest in 1.5 years so I think it's safe to assume people have found acceptable workarounds. As part of the on-going old issue cleanup process, I'll close this off. If anyone thinks this issue should still be addressed, please post back and we'll consider re-opening (but please also provide a runnable reproduction showing exactly how this can be a problem). Thanks for posting this originally!

**Comment by diegonc** [comment]
My use case is using bound functions as the transform method of a Node stream, like in the snippet below:

```javascript
import klaw from 'klaw';
import through2 from 'through2';

klaw('/tmp')
  .pipe(through2.obj(Meteor.bindEnvironment(function keepFilesOnlyFilter(item, _, next) {
    if (item.stats.isFile())
      this.push(item);
    /* Do something that needs a bindEnvironment */
    if (item.stats.isSymbolicLink())
      LogCollection.insert({msg: `Found symbolic link: ${item.path}`});
    next();
  })))
  .on('data', function (item) {
    console.log(item.path);
  });
```

But as you said, there are workarounds. I coded this little alternative bind function that preserves `this` and I record here for the future me tripping over the same rock.

```javascript
import {Meteor} from 'meteor/meteor';
import {compose} from 'rambda';

export const bindEnvironmentWithContext = compose(
    thisAsFirstArg,
    Meteor.bindEnvironment,
    firstArgAsThis
);

function thisAsFirstArg(fn) {
    return function thisAsFirstArgWrapper(...args) {
        return fn(this, ...args);
    };
}

function firstArgAsThis(fn) {
    return function firstArgAsThisWrapper(_this, ...args) {
        return fn.apply(_this, args);
    };
}
```
