### ISSUE TITLE
Package scope variables in .js cannot be assigned to in .coffee

### ISSUE THREAD

**Issue by chmac** [meteor/meteor#4171]
There is a bug in the [coffeescript documentation](../blob/devel/packages/coffeescript/README.md). The docs say:

> If you want to use package-scope variables with CoffeeScript, one way is to make a short .js file that declares all of your package-scope variables. They can then be used and assigned to from .coffee files.

However, that's not true. If I create `scope.js` in my package, and I create a package level variable like `Foo = undefined;`, then I can access that variable inside my `.coffee` files, true. However, as soon as I try to **assign to it** (`Foo = 'bar'`) inside my `.coffee` file, at compile time, coffeescript adds a `var Foo;` to the top of the compiled file. Now `Foo` is a file scoped variable in that file.

This means the only way to actually share files across `.coffee` files within a package is via `share`.

It is possible to define an empty object in `scope.js` and then create properties on that object in `.coffee` files, but that's exactly the same as `share` with a different name.

### Example

This coffeescript:

```coffeescript
Foo = 'bar'
console.log Baz
```

Compiles into this javascript:

```javascript
var Foo;
Foo = 'bar';
console.log(Baz);
```

**Comment by glasser** [comment]
Yeah, hmm, I'm not sure what we meant by that.  Maybe just "read and mutated". I'll update the readme to say that.
