### ISSUE TITLE
windows: Meteor namespace isn't available for collections 

### ISSUE THREAD

**Issue by mrmowgli** [meteor/meteor#4172]
Running a project originally created on linux, which works, won't run on Windows 7 Ultimate. It is complaining that Meteor is not defined.  I suspect load order, but I'm not sure how Windows handles that.   The collections are defined in a top level folder called collections, in a file named collections.coffee:

    @CollectionA = new Meteor.Collection('collectionA')                 
    @CollectionB = new Meteor.Collection('collectionB')           
    @CollectionC = new Meteor.Collection('collectionC')     

and the actual error message:

    => Exited with code: 8
    => Your application is crashing. Waiting for file change.
    Terminate batch job (Y/N)?
    Terminate batch job (Y/N)? y

    D:\dev\coolApp>meteor reset
    Project reset.

    D:\dev\coolApp>meteor
    [[[[[ ~\D\dev\coolApp ]]]]]

    => Started proxy.
    => Started MongoDB.
    => Exited with code: 8
    W20150410-20:32:56.886(-7)? (STDERR)
    W20150410-20:32:56.888(-7)? (STDERR) C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
    W20150410-20:32:56.888(-7)? (STDERR) throw(ex);
    W20150410-20:32:56.888(-7)? (STDERR)       ^
    W20150410-20:32:56.888(-7)? (STDERR) ReferenceError: Meteor is not defined
    W20150410-20:32:56.889(-7)? (STDERR)     at collections/clientCollection.coffee:1:13
    W20150410-20:32:56.889(-7)? (STDERR)     at collections/clientCollection.coffee:1:1
    W20150410-20:32:56.889(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:222:10
    W20150410-20:32:56.889(-7)? (STDERR)     at Array.forEach (native)
    W20150410-20:32:56.889(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    W20150410-20:32:56.889(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:117:5
    W20150410-20:33:01.422(-7)? (STDERR)
    W20150410-20:33:01.422(-7)? (STDERR) C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
    W20150410-20:33:01.422(-7)? (STDERR) throw(ex);
    W20150410-20:33:01.422(-7)? (STDERR)       ^
    => Exited with code: 8
    W20150410-20:33:01.423(-7)? (STDERR) ReferenceError: Meteor is not defined
    W20150410-20:33:01.424(-7)? (STDERR)     at collections/clientCollection.coffee:1:13
    W20150410-20:33:01.424(-7)? (STDERR)     at collections/clientCollection.coffee:1:1
    W20150410-20:33:01.424(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:222:10
    W20150410-20:33:01.424(-7)? (STDERR)     at Array.forEach (native)
    W20150410-20:33:01.424(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    W20150410-20:33:01.425(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:117:5
    W20150410-20:33:06.816(-7)? (STDERR)
    W20150410-20:33:06.816(-7)? (STDERR) C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
    W20150410-20:33:06.816(-7)? (STDERR) throw(ex);
    W20150410-20:33:06.816(-7)? (STDERR)       ^
    W20150410-20:33:06.816(-7)? (STDERR) ReferenceError: Meteor is not defined
    W20150410-20:33:06.817(-7)? (STDERR)     at collections/clientCollection.coffee:1:13
    W20150410-20:33:06.817(-7)? (STDERR)     at collections/clientCollection.coffee:1:1
    W20150410-20:33:06.817(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:222:10
    => Exited with code: 8
    => Your application is crashing. Waiting for file change.
    W20150410-20:33:06.817(-7)? (STDERR)     at Array.forEach (native)
    W20150410-20:33:06.817(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\Mowgli\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    W20150410-20:33:06.817(-7)? (STDERR)     at D:\dev\coolApp\.meteor\local\build\programs\server\boot.js:117:5

**Comment by Multiply** [comment]
Try to use `Mongo.Collection` instead.

**Comment by Slava** [comment]
We require reproduction apps with every bug report.

Can you reproduce it using JavaScript and not Coffeescript? Does this happen on a brand new app that wasn't ported from Linux? What version of Meteor are you using.

**Comment by mrmowgli** [comment]
Hi Slava, this is in Windows ver of Meteor rev. 1.1.0.2, and the same error happens in either Javascript or coffeescript.  I also performed a meteor reset, just in case cruft had been committed.  Will try on a new project here shortly.

**Comment by mrmowgli** [comment]
Ok, the basic problem was after pulling the project down, then running `meteor update` the update process somehow commented out the following lines of the original `.meteor/packages` file:

    #standard-app-packages
    #less
    #email

**Comment by Slava** [comment]
Glad to hear you fixed the issue.

**Comment by avital** [comment]
Sounds very surprising that `meteor update` would comment out lines in `.meteor/packages`. Is this something that can be reproduced?

**Comment by mrmowgli** [comment]
I'll see about reproducing this but it's not my machine.  I have to do everything remotely with someone else.   It also seems that they had the unofficial windows build on there when they originally pulled down the project, tried an update but it failed to find the packages.  It is quite possible that the older version modified the file.  I'll double check it when I get a chance.

**Comment by mrmowgli** [comment]
Ok, we did it from scratch this time, with a fresh pull from github and everything worked correctly.  This looks like the unnoficial windows build from before was responsible.  No-one added or removed packages manually to to it between pulling it from github before and running the two versions of Meteor for windows.  Not worth trying to reproduce I would imagine.
