### ISSUE TITLE
Template.body not Explained in Tutorial

### ISSUE THREAD

**Issue by ssiano** [meteor/meteor#4176]
The tutorial is very helpful and well done.  I only found one part to be confusing.  In the Templates part of the tutorial (https://www.meteor.com/try/2), an explanation of `Template.body` in the **"HTML files in Meteor define templates"** section might be helpful.  Currently, the second and third paragraphs in this section are:

> Everything inside any `<head>` tags is added to the `head` section of the HTML sent to the client, and everything inside `<body>` tags is added to the `body` section, just like in a regular HTML file.

> Everything inside `<template>` tags is compiled into Meteor templates, which can be included inside HTML with `{{> templateName}}` or referenced in your JavaScript with `Template.templateName`.

I found it confusing that the code above the paragraph used `Template.body.helpers` instead of `Template.task.helpers` (since "task" is the `templateName`).  Maybe the second paragraph could be updated as follows:

> Everything inside any `<head>` tags is added to the `head` section of the HTML sent to the client, and 
everything inside `<body>` tags is added to the `body` section, just like in a regular HTML file.  Also, 
the `body` section can be referenced in your JavaScript with `Template.body`.

With an update to this effect, the third paragraph would no longer seem inconsistent with the code above the paragraph.  This would be helpful since Template.task is not used until https://www.meteor.com/try/5.

Of course, please write it however you'd like.  I just started using Meteor today and am unfamiliar with the terminology.

**Comment by stubailo** [comment]
Thank you, this is great feedback! We need more like this, because it's hard to put yourself in the shoes of a beginner when writing a tutorial.

**Comment by abernix** [comment]
@ssiano Thanks again for this great suggestion.  @samudranb was kind enough to submit a pull-request to the Tutorial repo (meteor/tutorials#28) with (basically) what you wrote in order to try to clear up the confusion about `Template.body`.

We hope this is more clear in the tutorial now!  Closing.
