### ISSUE TITLE
Meteor collection weird behavior.

### ISSUE THREAD

**Issue by pavanputhra** [meteor/meteor#4179]
I have collection "config" as follows.

    Config= new Mongo.Collection("config");

Config collection contains configuration data which will be loaded to DB from backend and never would be edited by Meteor.

Following is sample data in config:

	{
		_id: 0,
		name: "S"
	}
	
	{
		_id: 1,
		name: "M"
	}
	
	{
		_id: 2,
		name: "L"
	}

Note: _id is Integer.

Following code is run on server and results are inconstant.

```JavaScript
	Config.findOne(0); //result is undefined
	Config.findOne({_id: 0}); //result is undefined
	
	Config.findOne(1); //result is { _id: 1,Name:"M"}
	Config.findOne({_id: 1}); //result is { _id: 1,Name:"M"}
```

Following code is run in browser and results are again inconstant.

```JavaScript
	Config.findOne(0); //result is { _id: 0,Name:"S"}
	Config.findOne({_id: 0}); //result is undefined
	
	Config.findOne(1); //result is { _id: 1,Name:"M"}
	Config.findOne({_id: 1}); //result is { _id: 1,Name:"M"}
```

Why findOne is behaving differently when _id is 0

Note: Meteor version 1.1.0.2 on Windows 8.1

**Comment by glasser** [comment]
See #3527. Meteor doesn't currently fully support numeric `_id` (eg, you can't insert them).

This particular issue comes from https://github.com/meteor/meteor/blob/b704424a738cf963c81e9fa49a60b982d0f14b82/packages/mongo/collection.js#L322-L331 which I think is kind of weird; I'm not sure it makes sense to ban explicit `{_id: falsey}` (though I do understand banning falsey full selectors which are most likely programming error and shouldn't turn into "matches everything").
