### ISSUE TITLE
Documentation for UI.dynamic

### ISSUE THREAD

**Issue by tonyarash** [meteor/meteor#4181]
There is no documentation for rendering dynamic templates. This is a very useful feature and should be documented. Thanks.

**Comment by Slava** [comment]
http://docs.meteor.com/#/full/template_dynamic

**Comment by Slava** [comment]
I think documentation has exactly what you are looking for in this case ;)

**Comment by tonyarash** [comment]
Thanks. Sorry I somehow missed it.
