### ISSUE TITLE
Package API for modifying mobile-config.js

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4182]
Cross-platform packages that access HTTP APIs currently need to instruct the developer to add `App.accessRule(...)` calls in their `mobile-config.js` files - for example, @dburles' [Google Maps](https://github.com/dburles/meteor-google-maps#mobile-platforms).

A `Package` API allowing packages to insert access rules would simplify usage.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Package%20API%20for%20modifying%20mobile-config.js&body=Migrated%20from:%20meteor/meteor%234182) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
