### ISSUE TITLE
App breaking upon a hot push (Cordova)

### ISSUE THREAD

**Issue by MoeBadr** [meteor/meteor#4186]
I've had this issue for a while I've just recently managed to resolve it, a hot push would break the app (stuck on a plain background screen), solution: 

server side: 
`Meteor.startup(function () {`
 `process.env.MOBILE_DDP_URL = 'xx';`
 `process.env.MOBILE_ROOT_URL = 'xx';`
`});`

issue location: https://github.com/meteor/meteor/blob/40ec4760f049b3a312b6b228aa4bf08f91f241aa/packages/webapp/webapp_server.js#L542

This issue is only present in production, `ROOT_URL` is passed in as env var.

**Comment by glasser** [comment]
I'm sorry, I don't understand your report.  Is that code there the issue or the fix?  If that's not the issue, how do you reproduce the issue?  

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by MoeBadr** [comment]
Hi @glasser , 

Apologies about the later response. 

The issue is #2999, it also contains a reproduction. 

The above code I posted is a work around the issue.
