### ISSUE TITLE
force-ssl redirects LAN clients to https://localhost 

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4192]
When I'm in development, I test on a mobile browser on my phone, using the local IP of my dev machine, eg `http://192.168.1.100:3000`. However, when I add `force-ssl`, my mobile browser gets redirected to `https://localhost`, which doesn't work.

Considering this and #3382, it would be nice if `force-ssl` could be disabled during dev. Related: #3748

**Comment by glasser** [comment]
This is basically a duplicate of #1442, which includes the same suggestion.
