### ISSUE TITLE
"Meteor does not currently support objects other than ObjectID as ids" Only in Production

### ISSUE THREAD

**Issue by vazamb** [meteor/meteor#4193]
Hello everyone,

we are having trouble with a hard to track down error. After pushing a major update into production we get the following error:

````
Exception in queued task: Error: Meteor does not currently support objects other than ObjectID as ids
    at [object Object].LocalCollection._idStringify (packages/minimongo/minimongo.js:1072:1)
    at [object Object]._.extend.has (packages/id-map/id-map.js:31:1)
    at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:897:1)
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:919:1)
    at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:968:1)
    at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:144:1)
    at [object Object].proto._pollMongo (packages/meteorhacks:kadira/lib/hijack/wrap_observers.js:23:1)
    at Object.task (packages/mongo/polling_observe_driver.js:85:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:145:1)
    at packages/meteor/fiber_helpers.js:123:1
````

This causes the app to not perform any database operations anymore. After being unable to fix the issue we reverted back to the last stable version. The app is working now, however, the error still pops up in the server error logs. There are no issues when running Meteor on localhost or on the meteor.com server we are using as a staging server.

Our app is hosted on Modulus with a database on Compose. We have not updated the Meteor version (1.0.3.2) between updates. The only information I was able to find is from 2013 and points to a problem with having "length" properties in database objects interfere with underscore.js. I have scanned the entire database but was unable to find any issues. 

Is there anywhere I can start looking for the cause of this problem? Any known issues still?

**Comment by Tarang** [comment]
You likely have an entry in your database that this query would find. I'm not too certain what collection it would be in:

```
db.collection.find({_id: { $type: 3 } })
```

Meteor supports integers, strings and ObjectIDs as values for the `_id` field but nothing else. When integers are used falsey values also cause issues, such as `0`.

**Comment by vazamb** [comment]
Hey Tarang,

thank you for your answer! There actually was one entry where the _id field consisted of another json object. I will try re-deploying later and post if this solves the issue. I had actually looked at that object before but didn't spot the fact that it was nested inside the _id field.

**Comment by Tarang** [comment]
@vazamb  In that case you may be trying to reuse the ids to reference other documents. But when you inserted them you probably used `variableName` instead of `variableName._id`. If you fix that and remove the offending document this problem should go away.

**Comment by vazamb** [comment]
There is one instance where I did that, but the code has since been changed. It also dealt with a new collection created during the update, which the production database currently does not have yet. I will update once I got a chance to re-deploy to production.

**Comment by glasser** [comment]
Thanks @Tarang, I think your explanation was correct: Meteor doesn't support arbitrary objects as IDs and the app contained such an object.

**Comment by vhuerta** [comment]
I know that issue is old, but we are experimenting a similar problem, we have our app hosted in modulus, when we deploy a new release, arbitrarily they begin to generate documents in different collections with ids that can be json objects with one property or dates , which causes the application to start throwing the same error mentioned in the original comment. After researching about it and did not find any solution beginning to believe that the error may be caused when the javascript code of the application is updated while even local database is synchronizing with the server.

We have already checked we're not inserting these id values ​​intentionally in the application code.

Below I share some examples of bad generated records.

```javascript

{ 
    "_id" : {
        "_str" : "d5a3251635572f651a476dc6"
    }, 
    "title" : "DASHBOARD.ACTIVITIES.STATUS_CHANGE_TITLE", 
    "text" : {
        "message" : "DASHBOARD.ACTIVITIES.STATUS_CHANGE_TEXT", 
        "data" : {
            "one" : "160201061", 
            "two" : "Agendada"
        }
    }, 
    "unitId" : "C59E6eXd6nALvdQGm", 
    "createdAt" : ISODate("2016-02-09T12:06:25.253+0000"), 
    "createdDate" : {
        "year" : "2016", 
        "month" : "2", 
        "day" : "9"
    }, 
    "createdBy" : "HXiQEzNkvFEpwhNGT", 
    "collection" : "activities"
}

{ 
    "_id" : ISODate("2016-02-11T16:03:37.590+0000"), 
    "typesId" : "SALA", 
    "typesName" : ISODate("2016-02-11T16:01:51.157+0000"), 
    "userId" : "qoiG5kZW5GZomg8ow", 
    "appraisalId" : "HbgvZdNJRhiCTdEkN", 
    "createdAt" : ISODate("2016-02-11T16:08:21.256+0000"), 
    "createdBy" : "qoiG5kZW5GZomg8ow", 
    "progress" : "Amo9hEyJenxN24wzC", 
    "collection" : "appraisalSpaces"
}
```
Aditional bellow i share all the packages that we have instaled in our application to:

```
appcache
iron:router
accounts-password
accounts-base
tap:i18n
nimble:restivus
copleykj:mesosphere
alanning:roles
momentjs:moment
less
http
underscorestring:underscore.string
meteorhacks:ssr
fixtures
anti:fake
u2622:persistent-session
mrt:moment-timezone
matb33:collection-hooks
stevezhu:lodash
meteorhacks:npm
reactive-var
mrt:moment
risul:accounting
mdg:geolocation
lookback:emails
blackcore:google-maps
meteorhacks:aggregate
percolate:synced-cron
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
miro:json2html
ground:db
tap:i18n-bundler
mnmtanish:call
rafaelhdr:google-charts
kadira:debug
```

The actual version of meteor in our app is 1.2.1

Did you have any idea what is happening?


That can offer much appreciate your help , Regards

**Comment by ChrisCinelli** [comment]
@Tarang thank you: `db.collection.find({_id: { $type: 3 } })` found the problematic record and   `db.collection.remove({_id: { $type: 3 } })` fixed it. The record was test data and added by mistake.

**Comment by amit-tyagi** [comment]
I'm also seeing lot of these errors in my code. Could something like this can cause this error to pop up?

db.collection.find({_id: {$ne: '1234'}})

**Comment by Cherviakov** [comment]
Hello everyone. Want to share when I got error above in my app. I tried this: 

```template.myReactiveVar.set(myCollection.find(data).fetch())```

When data changes inside recompute this error appear. Seems make double reactive is bad practice, then it worth to add such error.
