### ISSUE TITLE
Package Not Upgrading with Meteor Update

### ISSUE THREAD

**Issue by doubletaketech** [meteor/meteor#4194]
In Meteor 1.1.0.2, I've seen an issue with packages not upgrading with meteor update.  It says they were upgraded, but they actually are not.  And if you run meteor list, it still shows the old version and says an upgrade is available.

Specific package I'm dealing with is jonblum:jquery-cropper .  It upgraded in past version of Meteor no problem, but now it does not.  The only way to get it to upgrade is to force the version jonblum:jquery-cropper@0.9.1 .

I can't really say if this applies in general, but I'm just letting you know.

Thanks,
Don

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
