### ISSUE TITLE
Meteor listens on all interfaces and does not detect that another process is listening on a more specific interface (eg rails)

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#4195]
if there's Rails app on localhost:3000, Meteor starts without error and show 'App running at: http://localhost:3000/'. When I go to http://localhost:3000/, I have Rails app.

Meteor should give an error if there's already app on 3000.

OSX Mavericks

**Comment by Slava** [comment]
Meteor has a specific logic for this exact error: https://github.com/meteor/meteor/blob/b704424a738cf963c81e9fa49a60b982d0f14b82/tools/run-proxy.js#L60-L84

I just checked on my computer, running a small server on the same port does print me this error. Can you demonstrate how to reproduce this?

**Comment by Firfi** [comment]
Hey Slava,

I reproduced it with fresh projects like this:

```

mkdir temp
cd temp
rails new blog
cd blog
rails server

=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-04-15 09:03:07] INFO  WEBrick 1.3.1
[2015-04-15 09:03:07] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
[2015-04-15 09:03:07] INFO  WEBrick::HTTPServer#start: pid=73252 port=3000

cd ..
meteor create blog2
cd blog2
meteor

[[[[[ ~/work/temp/blog2 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/

```

Also, I just tried to run `rails server` _after_ - same issue, _it_ has no error. Seems like problem is more global than just Meteor. (and super minor actually)

**Comment by glasser** [comment]
When I run rails, I get:

```
$ netstat -na | grep 3000
tcp6       0      0  ::1.3000               *.*                    LISTEN     
tcp4       0      0  127.0.0.1.3000         *.*                    LISTEN     
```

Which shows that rails listens on the `::1` and `127.0.0.1` interfaces by default.  By default, Meteor listens on any interface, which doesn't conflict with specific interfaces.  If you run `meteor -p 127.0.0.1:3000` you will see the conflict.

I can see why this isn't a great user experience.  I'm not sure what we can do to improve it, though; having the default listen interface be all interfaces has been better than just choosing one.

**Comment by Firfi** [comment]
Yeah, that makes perfect sense. I think there's nothing to do about it and it is actually not a big problem. Will close issue if you're ok.
