### ISSUE TITLE
Nested Match.Where checks fail even for values that should pass

### ISSUE THREAD

**Issue by serkandurusoy** [meteor/meteor#4196]
Given a barebones basic example that nests two `Match.Where` tests:

````
var test = 'test';
// first match test
check(test, Match.Where(function(test){
  // second match test nested within the first
  check(test,Match.Where(function(test){
    check(test,String);
  }))
}));
````

we get:

````
r {message: "Match error: Failed Match.Where validation", path: "", sanitizedError: r, errorType: "Match.Error", stack: (...)…}
````

It does not matter what we put within the function block of the inner test, as soon as we enter the inner test, we get back the `Match error` response.

**Comment by rclai** [comment]
A `Match.Where`'s callback function needs to return a `Boolean`.

**Comment by serkandurusoy** [comment]
I was trying to keep the example succint. The following fails as well.

````
var test = 'test';
// first match test
check(test, Match.Where(function(test){
  // second match test nested within the first
  check(test,Match.Where(function(test){
    check(test,String);
    return test === 'test';
  }))
}));
````

**Comment by serkandurusoy** [comment]
Oh, while reading it, now I get it. The problem is the outer Match not receiving true/false!

Right?

**Comment by rclai** [comment]
Yup.

**Comment by glasser** [comment]
Thanks @rclai, that's correct!
