### ISSUE TITLE
Why this works: Meteor-Blaze #with and data context?

### ISSUE THREAD

**Issue by Laslo89** [meteor/meteor#4198]
I wonder why the following thing outputs 'hello' instead of 'bye'???

Template:

<template name="example">
    {{#with dataContext}}
        {{say}}
    {{/with}}
</template>

Template Helper:

Template.example.helpers({
         dataContext: function() {
              return {
                   say: 'bye'
              };
          },
          say: function() {
             return 'hello';
          }
});
(Meteor 1.1.0.2)

**Comment by PeppeL-G** [comment]
> Template helpers take priority over properties of the data context.

https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#name-resolution

**Comment by Slava** [comment]
@Laslo89 We usually keep GitHub issues for bug reports and feature requests/discussions. The questions are better asked on Stackoverflow or forums.meteor.com.

As @PeppeL-G said, the lookup priority is described in the spec of spacebars.
