### ISSUE TITLE
32 bit library for installing android-sdk is non-existent

### ISSUE THREAD

**Issue by Slanman3755** [meteor/meteor#4199]
I am trying to use Meteor to build an Android application

I got stuck in the installation process because I cannot finish installing the android-sdk because I do not have the 32-bit libraries installed that the installation requires.  I was following the instructions in the wiki.

I tried running the following:
sudo yum install -y glibc.i686 zlib.i686 libstdc++.i686 ncurses-libs.i686

Everything appears to be already installed except for "libstdc++.i686" which cannot be found.

When I run:
meteor install-sdk android

everything looks OK except for "32-bit libraries not found"

**Comment by Slava** [comment]
What distro are you on? Looks like RHEL has "libstdc++.i686" in their repo: http://ipswitchft.force.com/kb/articles/FAQ/How-to-install-32-bit-version-of-libstdc-on-RHEL-6-64-bit

I would like to update the wiki page with the up to date instructions.

**Comment by Slanman3755** [comment]
I am using Fedora but I am on an Amazon EC2 instance.

**Comment by Slava** [comment]
Great to hear it worked out!
