### ISSUE TITLE
meteor shell on deployed instances

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4203]
**_13 Upvotes**_ It's possible to do

```
$ meteor mongo myapp.meteor.com
```

But it doesn't seem to be possible to do

```
$ meteor shell myapp.meteor.com
```

Filed here at @avital's [suggestion](https://groups.google.com/forum/#!topic/meteor-talk/MasJp-WyYlo).

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I suspect that it is unlikely we will implement this on the current line of deploy servers but hope to do so for Galaxy.

**Comment by psy21d** [comment]
Can I use shell for deployed meteor projects on my own server?

**Comment by fabyeah** [comment]
+1 

This is so important!

**Comment by jorgeer** [comment]
+1 super useful!

**Comment by giray123** [comment]
+1

**Comment by JulianKingman** [comment]
This would be extremely useful.

**Comment by shwaydogg** [comment]
+1

**Comment by joelpickup** [comment]
+1

**Comment by oliroy** [comment]
+1

**Comment by Menda** [comment]
+1 Really nice feature to have

**Comment by THPubs** [comment]
+1 A very useful feature!

**Comment by theodorDiaconu** [comment]
+1

**Comment by grissproject** [comment]
+1. Very useful!

**Comment by rhyslbw** [comment]
Is this on the roadmap for Galaxy?

**Comment by fabien-h** [comment]
we need this :)

**Comment by simap** [comment]
+1

**Comment by juliomac** [comment]
+1

**Comment by carlosbaraza** [comment]
👍

**Comment by ElicNg** [comment]
👍

**Comment by dnordberg** [comment]
+1

**Comment by patrickdevivo** [comment]
something I do as a workaround is set MONGO_URL to the DB of my galaxy deployed app, for a locally running instance (making sure I'm running the same code that's been deployed to galaxy!) and run meteor shell there. Not the best solution, but decent for issuing one-off method calls or inspecting method/collection results for a deployed app

**Comment by NitroBAY** [comment]
+1

**Comment by webmagnets** [comment]
+1

**Comment by skemb321** [comment]
+1

**Comment by kodie** [comment]
+1

**Comment by stubailo** [comment]
Please use the GitHub reactions feature rather than posting a comment with "+1"!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=meteor%20shell%20on%20deployed%20instances&body=Migrated%20from:%20meteor/meteor%234203) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
