### ISSUE TITLE
Hot Code Push only when approved

### ISSUE THREAD

**Issue by tehXor** [meteor/meteor#4205]
Hi there,

I'm writing a meteor app where security is somewhat important. Therefore uses of the mobile apps should not simply get new versions pushed via Hot Code Push but should see the old and the new checksum and be asked if they want to allow the Hot Code Push. So that they now can check on a trusted source if there really is a new version with the new checksum.

I'm aware that this probably will require a little bit (more) custom coding. My question just is, where in the project is the code I would have to extend, is there a different Hot Code Push logic for Android and iOS and do I have to prepare myself for other obstacles (like for example is something like that even possible with a meteor plugin?).

I know this is not exactly the right place to ask something like that however I'm not so sure if another place would have been better and it would be nice if someone still could give me some hints on this.
Thanks a lot.

**Comment by Tarang** [comment]
You could use SSL with a strict certificate if you want to make sure no one can hijack your app.

Alternatively you could fork the `autoupdate` package.

This file handles the download: https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_cordova.js

If you modify this bit https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_cordova.js#L203-L217 and add a bit of conditional logic you could probably get what you want.

**Comment by rclai** [comment]
You can also check [this](https://atmospherejs.com/arsnebula/appupdate) out.

**Comment by tehXor** [comment]
Awesome thanks a lot for both infos! With arsnebula:appupdate I could implement what I wanted easily and extend it by adding the version from __meteor_runtime_config__.autoupdateVersionCordova or __meteor_runtime_config__.autoupdateVersion. From what I understood in the autoupdate package the version should be a hash of all client files and therefore is a good indicator that people really get what they want. I haven't checked further how easy it could be to manipulate it however for the time being this is enough for me.

PS: The Meteor server already is behind an SSL-Proxy so the connection is secure. This measure should prevent easy and unnoticed code manipulation server-side by accident or on purpose.

**Comment by glasser** [comment]
Thanks @Tarang and @rclai for helping!
