### ISSUE TITLE
Misleading error for password String test

### ISSUE THREAD

**Issue by victorbstan** [meteor/meteor#4206]
I noticed that if I submit a password as number to `Accounts.createUser`, it pretends the password was not set, issuing the "Must set options.password" error. Which is not the case, as the password has been set, except it's not a `string`. I think perhaps the error message could be changed to better reflect the actual test going on, or the test should accept numbers as well. Either way, the two don't align well and something could be done to make it a bit more clear. I can make the changes and create a pull request, if you wish.

```
Accounts.createUser = function (options, callback) { 
//...
if (typeof options.password !== 'string')                                                                   // 111
    throw new Error("Must set options.password");
```

**Comment by glasser** [comment]
Thanks, fixed!
