### ISSUE TITLE
Email: set mailcomposer options

### ISSUE THREAD

**Issue by ryanbuiltthat** [meteor/meteor#4209]
Mailcomposer defaults to an encoding of `quoted-printable`. This seems to be causing some issues with html emails rendered on the server.  Can we add a hook into the mc instance options?

**Comment by glasser** [comment]
Thanks!  I've pushed a change to expose the `mailcomposer` module and allow you to pass a `MailComposer` object to `Email.send` so that power users can use its API directly.
