### ISSUE TITLE
meteor + phonegap code + iOS 8.3

### ISSUE THREAD

**Issue by ApostolisT** [meteor/meteor#4212]
Hello, I ve been fighting to make phonegap code to work on an iPhone 6 with iOS 8.3 with the *sample* code provided in the announcement of the PhoneGap merge and nothing happens.
I ve even tried with the mdg:camera package and the code that is contained here:
https://github.com/meteor/mobile-packages/blob/master/packages/mdg:camera/photo-cordova.js

but to no avail. 
It seems for some reason iphone refuses to listen. 
Could someone provide me with one working sample? (whole js and html file if possible please)

**Comment by Slava** [comment]
Questions like this are best asked on [Meteor Forums](https://forums.meteor.com/) or on Stackoverflow.

If you have a particular reproduction for a bug, I suggest you open it on the repo of the package.
