### ISSUE TITLE
Provide more info with "Email already exists." error

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4213]
When a client tries to `loginWith[Service]`, and they already have an account under a different login method, it would be useful to include in the error sent to the client the email address and `services` keys (eg `a@b.c` and `password` or `facebook`), so the app can tell the client which service(s) their account is under or autofill the login form (in the case of `password`).

**Comment by Tarang** [comment]
You can always create a custom rule to do this:

```
Accounts.validateNewUser(function(user) {
    var user_email = user.emails[0].address;
    var existing_user = Meteor.users.findOne({ 'services.facebook.email' : user_email});
    if(existing_user) throw new Meteor.Error(500, "A user already exists with facebook id " + existing_user.services.facebook.id);
});
```

I'm not certain this is the best idea for everyone though:

The reason is some users may have a log-in which is password only & another which is a facebook login. The 'primary-key' or identifier being the facebook-id (being unchangable) vs the email which can be edited.

**Comment by lorensr** [comment]
Great, thanks!

Sorry I didn't mention this – the only reason why you get an "Email already exists" error in the original situation is if you follow the common practice of copying from `services.facebook.email` to `emails.address` in `onCreateUser`, and `emails.address` is a unique key in Mongo.

I still think it would be nice for the error to have more info. It both saves devs from finding/copying your rule and a round trip to the db.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20more%20info%20with%20%22Email%20already%20exists.%22%20error&body=Migrated%20from:%20meteor/meteor%234213) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
