### ISSUE TITLE
IE7 : JSON is undefined

### ISSUE THREAD

**Issue by yim1990** [meteor/meteor#4214]
```
<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent
```

When I run meteor on IE7, I got a error "JSON is undefined".
I think this is because JSON isn`t defined on IE7.
So I want to know about the way to import JSON2 package on top of "__meteor_runtime_config__" code.

Thank you.

**Comment by darth10** [comment]
"IE7" :sob:

**Comment by avital** [comment]
Meteor supports IE 8 and above: http://meteorpedia.com/read/Supported_Browsers
