### ISSUE TITLE
Org names must be lower case

### ISSUE THREAD

**Issue by c316** [meteor/meteor#4217]
Organization names are proper nouns, they should be capitalized. 

![screen shot 2015-04-16 at 11 16 28 am](https://cloud.githubusercontent.com/assets/3142974/7185719/23f3ac1a-e42a-11e4-979a-163af7140452.png)

**Comment by ekatek** [comment]
Thanks for using Meteor accounts! However, in this context, organization names are more like usernames (ex: iron, or mdg) and, as such, contain only lower case letters. We are currently considering allowing more characters, such as '-' for separating words (my-org-name), but we are probably not going to allow capital letters for now.
