### ISSUE TITLE
Documentation: mention that terminal commands need to be run in a new tab

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#4219]
In the documentation's deploy instructions:

```
Run it locally:

$ cd myapp
$ meteor
# Meteor server running on: http://localhost:3000/
Unleash it on the world (on a free server we provide):

$ meteor deploy myapp.meteor.com
```

There should be a mention that `meteor deploy myapp.meteor.com` needs to be entered inside a new terminal tab, since if people try to type it inside their current tab (which is running their Meteor app) nothing will happen.

**Comment by glasser** [comment]
I guess?  I've always read that as something you type after you kill your local server (the implication being that `$` means shell prompt).  That said, you've got a lot more experience writing educational Meteor prose than I do, so feel free to send a PR!

**Comment by SachaG** [comment]
Done :)

https://github.com/meteor/meteor/pull/4248/files

**Comment by SachaG** [comment]
(By the way, lots of people don't know what "$" means… We got quite a few people reporting `-bash: $: command not found` errors in the book because they were typing out the "$" as well!)

**Comment by glasser** [comment]
Thanks!
