### ISSUE TITLE
template.$('#myElemId') and template.find('#myElemId') do not work in repeat instances of templates

### ISSUE THREAD

**Issue by jonlachlan** [meteor/meteor#4220]
I have confirmed this in a blank project on Meteor 1.1.0.2. 

This code:
```javascript
template.$('#myElemId')
```
returns the correct elements on the FIRST instance of a template, but on repeat instances of a template it returns nothing. However, if I use other identifiers, such as 
```javascript
template.$('.pretty')
```
or
```javascript
template.$('div')
```
it correctly returns the jQuery elements on the first template instance as well as subsequent instances.
This is reproducible in both Template.myTemplate.onRendered and Template.myTemplate.events.

The same problem when you use template.find('#myElemId').

Note that the DOM still has ```<div id="myElemId">```, but Blaze can't seem to find it.

Here is my code to reproduce this:
html:
```html
<body>
  {{> repeater}}
</body>
<template name="repeater">
  {{#each twoTimes}}
    {{> repeatTwice}}
  {{/each}}
</template>
<template name="repeatTwice">
  <div class="pretty" id="myDiv">this div will repeat</div>
  {{runThisCode}}
</template>
```
javascript:
```javascript
if (Meteor.isClient) {
  Template.repeater.helpers({
    twoTimes: [1,2]
  })
  Template.repeatTwice.onRendered(function() {
    console.log("running onRendered");
    console.log(this.$('#myDiv'));
    console.log(this.find('#myDiv'));
    console.log(this.$('.pretty'));
    console.log(this.$('div'));
  });

  Template.repeatTwice.events({
    'click div': function(event,template) {
      console.log("running event");
      console.log(template.$('#myDiv'));
      console.log(template.find('#myDiv'));
      console.log(template.$('.pretty'));
      console.log(template.$('div'));    }
  })
}
```
This seems like a bug. It seems that the hash lookup of Blaze breaks when there are multiple instances of a template.

**Comment by jonlachlan** [comment]
OK SO update on this... I thought to try to have the hash ID change from one element to the next, and when the ID's are unique Blaze has no problem. 

So, is this a bug or a feature? Does Blaze not support having multiple hash id's for html elements? Is that a web standard? I'm too new to know.

**Comment by jonlachlan** [comment]
Well, to finalize my noob rampage, a friend has informed me that id attributes must be unique and not start with a number. Oy.

**Comment by glasser** [comment]
In general on the web, you can only have one element with a given ID on an entire document.  If you try to make multiple DOM nodes with the same ID, strange things may occur.  This isn't a Meteor-specific issue.

(In the future, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.)
