### ISSUE TITLE
Unclear semantics of stub execution

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4221]
From documentation it is unclear if stub execution on the client is assured to happen in a blocking way or not. So if I do:

```
Meteor.call('foobar')
```

On the client, and `foobar` method has a stub. Can I expect that the stub will be always called before program flow gets after the `Meteor.call` call? Is this specified?

Alternatively, is there a difference on the client between:

```
Meteor.call('foobar')
```

And:

```
Meteor.defer(function () {
  Meteor.call('foobar')
});
```

Documentation just says that `Meteor.call` will always return `undefined` on the client.

(So I am talking out of the simulation context here.)

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

Yes, stubs always run synchronously before sending the RPC and before the `Meteor.call` returns.  I agree that the docs are confusing here, especially something where it claims they run in "parallel".

**Comment by mitar** [comment]
Also, is this the behavior which is guaranteed to hold in the future? Because to work around the #2315, #2691, #3025 set of issues, I have to use:

```coffee
originalMeteorCall = Meteor.call
Meteor.call = (args...) ->
  inSimulation = Package.ddp?.DDP._CurrentInvocation.get()?.isSimulation
  if inSimulation
    originalMeteorCall args...
  else
    Meteor.defer ->
      originalMeteorCall args...
```

But now I am seeing that I changed semantics. (I already remove the `isSimulation` when going through observe.)

**Comment by mitar** [comment]
Oh, stubs run before RPC? This explains a lot. But this really means that one should not have long stubs. And with observes being called synchronously on the client, does this mean that RPCs are not send to the server until everything unwinds back? Ugh.

**Comment by mitar** [comment]
After more investigation, I think that it is pretty problematic that stubs are run before the call to the server side is done. It makes it really hard to do things like the following [example shows](http://meteorpad.com/pad/a94nWpTu2g9ZY23it/Leaderboard). If you click on "burn" button, you will get the following message in the server console:

```
Where's the fire?
Setting a fire...
```

I would claim that this is a surprising behavior. A behavior I would expect is:

```
Setting a fire...
Where's the fire?
```

What the code does is calls a method which prints "Setting a fire..." and inserts a document. We then observe that collection which in the added callback calls a subscription which prints "Where's the fire?".

But because simulation is called first, before the server side method, client triggers observe callback and subscription before the server side method is even called.

So this really makes any system where you want first to call a method to prepare a server and then subscribe to that problematic. It makes it hard to decouple data changes from reactions to those data changes (using observe), because order is unexpected. Also, if simulations are long, it delays calling the server side at all (where one could assume that also server side would be long).

Could you move simulation calls to happen after a call to the server was made? I always thought that is the case. First you issue a network request (which has higher latency), then you start simulating, then you get reply back and can confirm if simulation was good. Why doing it in a different way? I would even go so far to call stubs which are not in the simulation already in a non-blocking way, method calls on the client anyway need a callback.

**Comment by glasser** [comment]
I mean, I think this is just #2315, where the observes shouldn't be running as a part of the simulation, but outside of it.

**Comment by ssmith15** [comment]
I'm not sure if this is related, but sometimes if I do a Meteor.call method on the client where the function is server side only, it fails to execute after the first time.

**Comment by hwillson** [comment]
This issue has been migrated to https://github.com/meteor/docs/issues/153. Closing here - thanks!
