### ISSUE TITLE
return additional package information with meteor search

### ISSUE THREAD

**Issue by benlavalley** [meteor/meteor#4223]
Meteor search is great, but with so many packages out there it can be difficult to figure out which one you should use.

When I need to add a package -- mandrill today, for example -- I run meteor search mandrill.

There are currently 6 packages for sending email via Mandrill.

I'll now hop on github or run 'meteor show' and pull them all up. The main parameter I use in determining which package to use is the last committed date. Perhaps there are more important considerations but as someone learning/building/trying to actually release a Meteor app, it's the one that has suited me well so far. 

It would be nice to have the ability to see the last updated date for each given package directly from meteor search to better assist in picking packages to install. 

Perhaps someone handy with bash (and more importantly, with the time) could put together a wrapper for meteor search to return recent version information for a given package by pulling data from meteor show. 

Not the most critical of features, but I felt it would be a worthy feature request contribution.

**Comment by ekatek** [comment]
Thanks for the feature request! One of the tradeoffs with running `meteor search` is screen real estate -- the more things we show for each pick, the more confusing, hard to read, and, potentially, less useful the output becomes. As such, we are very careful around adding more information, and it is unlikely that we would implement this feature request in the near future. (I'll leave it open, however, so we can look at it next time we look at `meteor search` output). 

For complicated searches, we recommend using a front end such as atmospherejs.com (or http://fastosphere.meteor.com/) !

**Comment by nibbl** [comment]
I somehow didn't know about Fastosphere -- thanks! Have to better balance my app coding time with general Meteor knowledge improvement. 

As for meteor search, an optional -details switch would probably suffice when you're able to evaluate this again in the future.

**Comment by hwillson** [comment]
Hi all - as part of the on-going old issue cleanup process, I'm going to close this issue for now. The current implementation of `meteor search` will likely remain as is (at least for now), especially since Meteor is headed towards a [full transition to npm](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm) for packages. Thanks for opening the original issue!
