### ISSUE TITLE
Clearly deprecate manual.meteor.com

### ISSUE THREAD

**Issue by skagedal** [meteor/meteor#4227]
In the [Meteor Manual](https://manual.meteor.com/) under the heading "Collection.find() versus Collection.cursor.fetch()", there is a FIXME that looks like regular text: "Just made up the term "property selector" to differentiate from "field selector" (or "field specifier" in the docs); open to suggestion" - confusing for the reader, I bet that it's not intended to be shown? 

I couldn't find a repository for this manual to submit a PR to.

**Comment by skagedal** [comment]
Ah wait, this is old? It should be removed and replaced with a link to the [Tracker Manual](https://github.com/meteor/meteor/wiki/Tracker-Manual).

**Comment by serixscorpio** [comment]
@skagedal I have been reading the meteor manual at https://manual.meteor.com/.  Thanks for posting this.  I'll read Tracker Manual from now on at https://github.com/meteor/meteor/wiki/Tracker-Manual

**Comment by Slava** [comment]
The manual is not maintained any more. Most of the content was migrated to https://github.com/meteor/meteor/wiki/Tracker-Manual. I deleted the comment from the wiki page.

**Comment by skagedal** [comment]
Ok! It would be good if there was a clear notification on http://manual.meteor.com that it's outdated and no longer maintained, with links to the proper places. It shows up on Google hits and "looks official".

**Comment by glasser** [comment]
Good point. Reopening to track this.

**Comment by abernix** [comment]
Closing because I think it's pretty clearly deprecated now!
<img width="491" alt="screen shot 2016-05-25 at 1 56 30 am" src="https://cloud.githubusercontent.com/assets/841294/15522543/ef166524-221b-11e6-9801-57b0df10da00.png">

In all seriousness though, check out the new and awesome [Meteor Guide](http://guide.meteor.com/)
:wink:
