### ISSUE TITLE
jQuery returns wrong data-* attributes the second time I click a remove button on a item part of a list.

### ISSUE THREAD

**Issue by brugnara** [meteor/meteor#4231]
**Short story**

Here you can see a demo of the problem (press some times ADD and then the first X many times.. Only the first one will delete the record. Then try with the second button for the very same issue): 
http://bug-event-template.meteor.com

Here the source code: https://github.com/brugnara/meteor-bug-event-template

**Long story**

I have a template that renders an array of objects stored in `Session`.

You can try by your self. You press the ADD button and you will see a list of items with a red sign that is supposed to remove the current item, and it works the first time you press it. The second time I get an error saying the id doesn't exist. With the inspector, I can see the `data-id=RAND` and it is right. The only wrong thing is the result of the `.data('id')` function the second time I press the button. I really can't understand what is happening. May this be a bug somewhere? (see the ****\* signed comment. The value obtained is wrong but anything else is rendered ok, ie the DEBUG `{{id}}` is showing correctly and the inspector shows the data-id setted correctly. In my opinion the `event` routine fails at some point, or simply I'm making some issue with the code :) )

Thank you for the attention. 

Manager:

``` js
var MESSAGE_QUERIES = 'messages:queries';
var MESSAGE_CURRENT = 'messages:current';

Template.messagesNew.helpers({
  queries: function() {
    return Session.get(MESSAGE_QUERIES);
  }
});

Template.messagesNew.events({
  'keyup #message-new-text': function(e) {
    var $len = $('#message-new-text-length');
    var $text = $(e.target);
    var len = $text.val().length;
    $len.html(len === 0 ? '' : len + (len === 1 ? ' char' : ' chars'));
  },

  'click .query-add': function(e) {
    e.preventDefault();
    var id = chance.word({ length:16 });
    var queries = Session.get(MESSAGE_QUERIES);
    if (!queries) {
      queries = [];
    }
    queries.push({
      id: id
    });
    Session.set(MESSAGE_QUERIES, queries);
  },

  'click .btn-remove': function(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    var $target = Template.instance().$(e.currentTarget);
    var id = $target.data('id'); // ************* This is wrong any click but first
    TARGET = $target; // for debug only
    var queries = Session.get(MESSAGE_QUERIES);
    var toRemove = -1;
    $target.blur();
    //
    queries.forEach(function(query, index) {
      if (query.id === id) {
        toRemove = index;
      }
    });
    if (toRemove === -1) {
      return console.warn('Nothing found with id:', id);
    }
    console.log('Removing query with id:', id, 'in position:', toRemove);
    queries.splice(toRemove, 1);
    Session.set(MESSAGE_QUERIES, queries);
  }
});
```

Template

``` hbs
<template name="messagesNew">

  <form>

    <div class="form-group">
      <label for="message-new-text">Text message</label>
      <small class="pull-right" id="message-new-text-length"></small>
      <textarea id="message-new-text" class="form-control" placeholder="Lorem ipsum"></textarea>
    </div>

    <div class="form-group">
      <label>Queries</label>
      <button class="btn btn-default query-add">
        <span class="glyphicon glyphicon-plus"></span>
        Add
      </button>
    </div>

    <div class="form-group">
      {{#each queries}}
        DEBUG: {{id}}
        <div class="panel panel-default">
          <div class="panel-title">
            <div>
              <span class="pull-right query-remove">
                <button class="btn btn-danger btn-xs btn-remove" id="query-remove-{{id}}" data-id="{{id}}">
                  <span class="glyphicon glyphicon-remove disabled" style="margin-top: 3px;"></span>
                </button>
              </span>
            </div>
          </div>
          <div class="panel-body">
            {{>query .}}
          </div>
        </div>
      {{/each}}
    </div>

  </form>

</template>
```

Thank you.

**Comment by brugnara** [comment]
Here you can see a demo of the problem (press some times ADD and then the first X many times.. Only the first one will delete the record. Then try with the second button for the very same issue): http://bug-event-template.meteor.com  

Here the source code: https://github.com/brugnara/meteor-bug-event-template

**Comment by glasser** [comment]
This is definitely strange!  I dug into it a tiny bit and it looks like this id comes from an internal jQuery-specific cache.  eg, after getting an error in the console, trying `jQuery.cache[TARGET[0][jQuery.expando]].data` shows the bad id.  Maybe Blaze is reusing DOM nodes somewhere without telling jQuery that it needs to clear its internal caches?  http://stackoverflow.com/questions/9304768/what-is-the-purpose-of-cache-in-jquery

**Comment by brugnara** [comment]
This post describes this problem as well: https://forum.jquery.com/topic/jquery-data-caching-of-data-attributes

Infact, `id = $target.attr('data-id')` returns always the correct id and this happens because attr is not taken from cache but from DOM.

**Comment by hwillson** [comment]
I've verified this issue is still happening and created a new issue to track this problem in the Blaze repo  (meteor/blaze#155). Since this issue is now being tracked elsewhere, it can be closed. Thanks!

**Comment by jint-daily** [comment]
https://sallow68.github.io/david/ Reflect on this explanation
