### ISSUE TITLE
Including a template should not fail when value is undefined

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4232]
Currently, only a template or a `null` can be included, but `undefined` not. This makes code really fragile because a lot of JavaScript code uses that interchangeably.

The error which is thrown is:

```
Expected template or null, found: undefined
```

Can this be lifted and made it less strict so that `undefined` can also be passed? And behaves the same as `null`?

**Comment by Maxhodges** [comment]
-1 I think it's a much better pattern for the dev to specifically say "don't render anything", rather wondering why something isn't working as expected.

**Comment by mitar** [comment]
The issue is that you cannot necessary control all the code paths. And yes, I think there should be a strict and non-strict mode. For example, why including a template fails with an exception, but doing `{{foobar}}` where `foobar` is `undefined` does not? Why the difference?

So, we could do that all missing symbols are throwing exceptions or printing out "missing" or something like that. And otherwise they are ignored. Not that things are mixed. Sometimes they are ignored, sometimes they throw an exception.

There are two stages this is used: in development, and during runtime. During runtime I do not want my templates to blow up because of one `undefined` vs. `null`.

Django has `TEMPLATE_STRING_IF_INVALID` for that, then you can do things like:

http://stackoverflow.com/questions/15312135/how-to-make-django-template-raise-an-error-if-a-variable-is-missing-in-context

**Comment by glasser** [comment]
This is working as intended, as per @Maxhodges 's explanation.
