### ISSUE TITLE
Updated App.configurePlugin Data Not Taking Effect

### ISSUE THREAD

**Issue by Koosmann** [meteor/meteor#4234]
**_1 Upvote**_ After a plugin has been installed once (e.g. com.phonegap.plugins.facebookconnect) with App.configurePlugin data, any subequent updates to the configuration in mobile-config aren't taking effect.

To reproduce, first install a basic app, add ios, and install a plugin:

```
meteor create test --example clock
meteor add-platform ios
meteor add cordova:com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/53fa226570c92ce25f79116b8c564d4d13ba2232
```

Then, create the mobile-config.js;

```
App.configurePlugin('com.phonegap.plugins.facebookconnect', {
    APP_NAME: 'Test',
    APP_ID: '012345678910'
});
```

Run the app for the first time:

```
meteor run ios
```

Update mobile-config.js with new values:

```
App.configurePlugin('com.phonegap.plugins.facebookconnect', {
    APP_NAME: 'Updated Test',
    APP_ID: '109876543210'
});
```

Finally, run the app once again - none of the cordova file storing the config data will be updated:

```
meteor run ios
```

The only way to get the new config data to take effect is to remove the .meteor/local/cordova-build folder before running again.

**Comment by Slava** [comment]
You are right, this is a bug.

The configuration is used when the plugin is installed. Due to the plugins caching, it is not removed and re-added as soon as the configuration is changed, instead, one needs to wipe out the build cache (either by removing the folder as you described, or running `meteor reset`) and then build the app over again.

**Comment by Alveoli** [comment]
+1, I've encountered the same bug. Not a big deal, but look forward to when it's fixed.

@Slava thanks for the good work on Meteor!  Keep it up!

**Comment by hwillson** [comment]
We're going to address this (for now) by documenting it. See https://github.com/meteor/docs/issues/176.
