### ISSUE TITLE
Cordova: Couldn't load from the manifest, falling back to the bundled assets.

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4239]
I see the following errors repeatedly in various apps when running on android device:

```
(android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.idnc85sng8wfs9w40ext/files/meteor/version
(android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
(android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
```

Reproduction steps:

```
git clone git@github.com:meteor/mobile-packages.git
cd mobile-packages/examples/simple-photo
meteor update
meteor run android-device
```

Every time I press the back button in the Photo booth app, the errors above appear in the terminal.

**Comment by glasser** [comment]
This isn't really an error; it's just saying that we haven't downloaded any autoupdates and are just using the original version.  But the messages are scarier than necessary.  Feel free to send a PR improving https://github.com/meteor/meteor/blob/5df2be6398ab5cbc6bf1a27bc8603324bf295d86/tools/client/meteor_cordova_loader.js#L95 and https://github.com/meteor/meteor/blob/5df2be6398ab5cbc6bf1a27bc8603324bf295d86/tools/client/meteor_cordova_loader.js#L76 to better express that there's no real error, just a recognition that the app hasn't been updated.
