### ISSUE TITLE
I got error when downloading package via add command

### ISSUE THREAD

**Issue by adals** [meteor/meteor#4241]
hello everyone

please help me how to solve it

when I use this "meteor add urigo:angular"

D:>meteor add urigo:angular
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

=> Errors while adding packages:

While downloading angularjs:angular@1.3.15...:
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

While downloading dburles:mongo-collection-instances@0.3.3...:
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

While downloading lai:collection-extensions@0.1.3...:
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

While downloading urigo:angular@0.8.2...:
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

Your package catalog may be out of date.
Please connect to the internet and try again.

my system is win8 and turn off firewall "eset" and dont use proxy and the same

so please help me

thanks

**Comment by Slava** [comment]
See https://github.com/meteor/windows-preview/issues/94. According to [this](http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature) Stackoverflow answer, it happens because your system has something unusual in your cert chain.
