### ISSUE TITLE
Meteor does not use resolutions from bower

### ISSUE THREAD

**Issue by nqbao** [meteor/meteor#4242]
Meteor seems to ignore `resolutions` in bower.json

```
{
  "name": "myapp",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "d3": "3.5.2",
    "vega": "1.4.3",
    "leaflet": "~0.7.3",
    "leaflet-d3": "~0.2.6"
  },
  "resolutions": {
    "d3": "3.5.2"
  }
}
```

This will run fine in bower, but meteor will say that it can't resolve the right version for d3 `Unable to find suitable version for d3`

However, if i remove the d3 in dependencies, it will be compiled nicely but then i got d3 is not defined in the app.

**Comment by ekatek** [comment]
Thanks for filing an issue. However, we can't resolve it without more information.
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Additionally, the Meteor tool does not actually use `bower.json`. It sounds like you might be using a third party package to translate from `bower.json` to something that Meteor understands.

**Comment by nqbao** [comment]
Thanks @ekatek! Sorry i don't know the policy and i will review and reopen the ticket if it is directly related to meteor tools.
