### ISSUE TITLE
Android background data

### ISSUE THREAD

**Issue by Tyga76** [meteor/meteor#4244]
Hi, I built an android app with meteoric. In the last month after doing some meteor updates i noticed that my background data usage is excessive. Some days its almost 200 MB. I am not sure whats changed. Is anyone else having this issue?

**Comment by Slava** [comment]
Meteor stores a cache on device with the latest code of your mobile app. Usually, it would store one version at most and there is some code that cleans up on every start:

https://github.com/meteor/meteor/blob/f7b887ac97a34893b112745c31091f23c0ebe501/packages/autoupdate/autoupdate_cordova.js#L227-L258

If you have a specific reproduction of this not working or a bug, we can review this.

**Comment by Tyga76** [comment]
Hi, thanks for the response. I don't think this is my issue. The updating of the app is not a problem. When I use the app it consumes couple megs of data. Which is typical. Soon as I put the app to the background, it consumes lots of data. In a few hours it can use up to 100 MB of data. Its like its doing massive updates in the background.

**Comment by Tyga76** [comment]
Quick Question.. I am using the debug apk on my phone. Could this be causing the excessive background data usage?
