### ISSUE TITLE
Google OAuth callback URL needs "?close" appended

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4246]
The default instructions for configuring Google OAuth lead to "Error: redirect_uri_mismatch". Turns out 

> The redirect URI in the request: http://{{Meteor.absoluteUrl}}/_oauth/google?close did not match a registered redirect URI.

The instructions advise setting only `http://{{Meteor.absoluteUrl}}/_oauth/google`.

**Comment by allandequeiroz** [comment]
No, there is not necessary, actually if you use this way, it's not gonna
work.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

`?close` was an old URL scheme we used; the current code does not suggest its use, but works either way.  The change was in 0.9.1, I believe.  I just tested this with a fresh app and it worked fine, so you'll need to provide a full reproduction.  Maybe this is something where you upgraded Meteor with an existing configuration and our backwards-compatibility code didn't work right?

**Comment by dandv** [comment]
Reproduction repo: https://github.com/dandv/meteor-issue-4224

Looks like the problem is caused by the interaction with `ian:accounts-ui-bootstrap-3`. Filed an [issue there](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/109), along with reproduction instructions.
