### ISSUE TITLE
Additional params when creating new user with Meteor.loginWith<Service>

### ISSUE THREAD

**Issue by v3rron** [meteor/meteor#4249]
It would be really nice if you could provide additional user params to save in Meteor.loginWith<Service> function.
Example: I have a signup page with some required input fields that user must provide before he can actually signup with Google OAuth. There's no way to pass those fields to the server upon user creation with external service.

Currently I'm using this hack:

```
// Submit Form and Register New User
  'submit form': function(e, tmpl) {
    e.preventDefault();
    var userData = { "profile.title": Session.get('title') };
    Meteor.loginWithGoogle({}, function(error){
      if(error){
        Notifications.error('Error', error.message);
      }else{
        // Current timestamp
        var today = moment();
        // CreatedAt timestamp
        var createdAt = moment(Meteor.user().created_at);
        // If user was created this minute and has no title field yet
        if (today.isSame(createdAt, 'minute') && _.isEmpty(Meteor.user().profile.title)) {
          Meteor.users.update({ _id: Meteor.userId() }, {$set: userData}, function(error, result){
            if(error){
              Notifications.error('Error', error.message);
            }else{
              Notifications.success('Success', 'New user have been created!');
            }
          });
        }
        Notifications.success('Success', 'You have been logged in successfully');
      }
    });
  }
```

But in this case if Meteor.users.update call will return an error, user have already been created and I have no option rolling it back.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

There's the `Accounts.onCreateUser` hook, but there's no way to plumb data through from `Meteor.loginWith*` to it. It would be nice if that was possible, though admittedly it does pass through a bunch of different places on the way to getting there.

**Comment by merlinpatt** [comment]
I would like to see this as well, so I can pass in expected user roles when people sign up

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Additional%20params%20when%20creating%20new%20user%20with%20Meteor.loginWith%3CService%3E&body=Migrated%20from:%20meteor/meteor%234249) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
