### ISSUE TITLE
App not accessible over local network

### ISSUE THREAD

**Issue by clxe** [meteor/meteor#4250]
I've got the app mentioned in the [Meteor tutorial](http://meteor.com/try) up and running on my own machine by running `meteor --port=0.0.0.0:3000` inside the app directory. This works fine on my own computer, but I can't access the app from other devices on the same network by visiting `192.168.1.100:3000` (which is what I can use to access it from the host machine). When I connect to `192.168.1.100:3000` from my other laptop I get "server stopped responding" messages and the app doesn't load.

This normally works fine when I'm using Node, so it probably isn't a firewall problem.

**Comment by glasser** [comment]
@Slava and I tried to reproduce this and couldn't.  He was able to access my laptop.

Are you sure you typed `0.0.0.0:3000` (or `3000` which should be fine)? Are you sure that the "normally works fine" behavior was actually working fine simultaneously?
