### ISSUE TITLE
Spinner barely visible on Cordova launch screen

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4251]
The spinner displayed on top of the splash screen is barely visible

![image](https://cloud.githubusercontent.com/assets/33569/7265976/642cfa62-e857-11e4-96c1-07c5d7567375.png)

To reproduce:

````
meteor create spinner
cd spinner
meteor add-platform ios
meteor run ios
```

On an iOS device, the spinner was practically invisible, due to the high gloss and DPI.

**Comment by rclai** [comment]
Lol, I didn't even know there was one.

**Comment by glasser** [comment]
Good point.  Pull requests welcome.

**Comment by RobertLowe** [comment]
I'm not sure what to do here. 

@dandv @glasser The indicator can be turned off via:

`App.setPreference('ShowSplashScreenSpinner', 'false');`

in your `mobile-config.js` for iOS:

https://github.com/apache/cordova-plugin-splashscreen/blob/559b300d29ba6eb2f951eb19b9bbf7ba9238a862/src/ios/CDVSplashScreen.m#L84-L98

It cannot however be easily styled/replaced without changes to `cordova-plugin-splashscreen`

---

Perhaps we should:

1. keep the indicator off by default
2. inform users of the design constraints of the indicator (it's very dark)
3. make necessary changes to `meteor` or `cordova-plugin-splashscreen` to allow for easier/better styling

**Comment by dandv** [comment]
How about changing the stars/meteor black background so it creates more contrast with the spinner?

**Comment by RobertLowe** [comment]
@dandv the splash screen image is configurable, so while we could change the default splash screen, any user that changes it may have the same issue reported here

**Comment by dandv** [comment]
Looks like the spinner should get a shadow/glow of some sort then.

**Comment by miri-am** [comment]
Any updates on this? Would be nice to be able to change the color and size of the spinner.

**Comment by Slava** [comment]
You can set a different image in the settings: http://docs.meteor.com/#/full/App-launchScreens

The stock image is just a place holder we put, you can replace it as you wish. For the spinner, I don't think there is a way to customize it in the cordova plugin.

**Comment by martijnwalraven** [comment]
In Meteor 1.3, the spinner has been disabled by default. A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
