### ISSUE TITLE
Accounts Oauth Facebook return URL 

### ISSUE THREAD

**Issue by ganySA** [meteor/meteor#4252]
Hi

I am trying to understand where meteor accounts package is setting the popup return URL for Oauth transactions specifically for facebook.

I have a scenario where i have a server configured in nginx http://www.example.com when i click on the facebook login it seems to open the return popup as http://example.com which then causes a cross origin request style problem.

I had the exact same problem when testing this on localhost when meteor was running on a different port. e.g http://localhost:3000 and the popup for facebook auth would redirect to http://localhost(no port) - i fixed this in my test environment by simply running "meteor --port 80"

In my production environment if i change nginx to serve pages from http://example.com then naturally the facebook oauth popup also works because there are no CORS style errors - but i dont like these types of workarounds...

I cannot find anywhere in the documentation or scouring through stackoverfly where meteor accounts is getting/setting the popup redirect - i thought it could be ROOT_URL env variable but that does not seem to be the case either....

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

(You do need to set `ROOT_URL` to the publicly accessible URL to your site for many parts of Meteor to work properly, including OAuth login.)
