### ISSUE TITLE
meta tag for charset utf-8 not on top of the html head

### ISSUE THREAD

**Issue by afriC84** [meteor/meteor#4254]
I use meteor on my windows machine. It seems to mess around with my head template and puts all the scripts on the very top after the opening `<head>` tag.

This is what I have in my template:

```html
<!DOCTYPE html>
<head>
<meta charset="utf-8">
```

This is what meteor generates:

```html
<!DOCTYPE html>
<head>
*** script 1 ***
*** script 2 ***
...
*** script n ***
<meta charset="utf-8">
```

This is why the charset-meta does not work.
Am I doing sth wrong? Is this on purpose? Is there a workaround?

On stackoverflow some guys modified a meteor file to force the charset-meta to the top. But that seems to be no solution to me. I **love** the whole project btw :-)

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

That said, I don't actually think you need a `<meta charset>` in Meteor: the HTTP server automatically serves the main page as `Content-Type: text/html; charset=utf-8`.  Is there something you were trying to do with utf-8 that wasn't working?

**Comment by afriC84** [comment]
Hi there! I have problems displaying letters like "ö", "ä" and so on. They are all replaced by a route with a questionmark. But I just build an app using the command `meteor create <name>` and not using [the boilerplate](https://github.com/Differential/meteor-boilerplate.git) and **it worked**! All the utf-8 letters were displayed correctly.

The interesting part: even when I replaced the new (working) `package`-file with the old one and copied over all the folders and files from the old project (with utf-8 not working) it worked as expected and displayed all the symbols correctly.

## how can that be?

But even if it works somehow with the `meteor create` command, the `<meta charset="utf-8">` should be the first meta tag after the opeining `<html>` tag, as [supposed by the W3C](http://www.w3.org/International/questions/qa-html-encoding-declarations) or the [Mozilla Developer Network](https://developer.mozilla.org/de/docs/Web/HTML/Element/meta#attr-charset).

Please let me know if you still need a git repo.

Finally I am still left with the question, how the charset-problem can be gone after copying files to a blank app created with `meteor create` and everytime I create it using [the boilerplate](https://github.com/Differential/meteor-boilerplate.git) via IntelliJ it fails... I'd be glad to hear any ideas. I already opened [an issue for that in that repo](https://github.com/Differential/meteor-boilerplate/issues/64).

**Comment by mahmunk** [comment]
Having same issue.

**Comment by Paku-** [comment]
same ...no international characters.
