### ISSUE TITLE
CSS change issues full application refresh and how to debug it

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#4255]
Currently in meteor application 1.1.0.2v I have some css files in client/ folder. When I change any css file, application issues full page refresh. I have several packages, but when I copy `packages` file content in newly created application (with `meteor create ...`) css refreshed without any issues. I thought it can be packages versions issue but `meteor update` doesn't fix the problem. I have scss preprocessor package but it doesn't seems to be problem either as it is installed through the `packages` on second testing app that I created from scratch to reproduce this issue and besides I change only `css` file. 

How can I debug this problem?

**Comment by Firfi** [comment]
I just found it was really a problem with package reactjs/meteor-react, but not with just a package. There's condition - you have to have syntax `class SongCircle extends React.Component {` inside your .jsx. I won't close this issue as still not sure if it can be some asset pipeline grepping on class keyword (?)

**Comment by Slava** [comment]
We require a small reproduction app to be able to reproduce the issue. The CSS-only inject works only when CSS is the only part that changed. If your change also changes some client-side js, the full refresh is always issued.

The build tool doesn't do any special grepping on the `class` keyword.

**Comment by Firfi** [comment]
To clarify, I do not change js, it is just a sole existence of line with this syntax in any js file, without changing this js or another js file, triggers full reload on changing any css file. Will take a time for small reproduction app later, maybe.
