### ISSUE TITLE
Setting strict package version in `packages` doesn't have effect

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#4256]
How to reproduce:

create new application, then there `meteor add dgellow:react-loader@0.0.3`. You'll have dgellow:react-loader@0.0.3 in `packages`. You'll have dgellow:react-loader@0.0.4 in `versions`.

**Comment by glasser** [comment]
This is working as intended.  That command means "a version compatible with 0.0.3".  If you want an exact pin, use `dgellow:react-loader@=0.0.3`.  This is documented at http://docs.meteor.com/#/full/meteoradd but maybe not in enough places.

**Comment by Firfi** [comment]
Thanks!
