### ISSUE TITLE
By default, preventDefault on form submits

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4257]
Reopening #1084, which was closed when FRs weren't accepted. I agree that there are reasons to keep `<form>`s rather than switch to solo `<button>`s.

When I've helped out at devshop, I saw a couple people struggle with what do to with forms. One was trying to handle the POST on the server, and another was calling a method in the submit event, but letting the POST happen, which caused a page reload. 

It is almost never the case in a Meteor app that you want a POST to happen, so I think the most developer-friendly solution would be to have the default be not POSTing, but provide some configuration parameter to allow it in the rare app that needs it. Or you could not have a config, and the rare app would just have to send the POST in JS.

**Comment by tonyarash** [comment]
I totally agree. I feel that it's almost always the case that you'll want to handle the submit event in client and then call your server method. So this behavior by default would be great.

**Comment by stubailo** [comment]
Yes, this is a case in Meteor where you have to have some previous experience working with JavaScript to know what to do inside an event handler. I agree that 99.999% of the time you probably want a form to not actually submit via HTTP.

What would the API look like for doing an actual submit then?

**Comment by lorensr** [comment]
If a config, then:

```
Template.foo.preventDefaultSubmit = false;

# or for all templates
Template.preventDefaultSubmit = false;
```

If not a config, then however you want, eg `$.post`

**Comment by mitar** [comment]
I think this should probably be build on top of Blaze, instead of making it a default? So this is something which 3rd package libraries can provide? Like autoform?

**Comment by stubailo** [comment]
Agreed. This is probably one of those places where a feature seems nice, but then ends up with a ton of edge cases and configuration options that need to be documented. The simpler thing to do would be to not have this feature, especially since it could be easily implemented in a package.

Also, we're working on a section about forms for the Meteor Guide which will be a great place for people to find out about form handling in Meteor.

Given all of the above, I'm going to close this. Let me know if that doesn't seem like a good idea.

**Comment by lorensr** [comment]
I think given the goal of app-building as fast/easy as possible, it makes
sense for the default to be the 99% case – making the 1% look up how to
enable form posts, rather than making those of the 99% that don't read the
Guide either a) look up how to disable form posts, or b) flounder for a
while trying to handle posts on the server, not knowing they should be
disabling posts.

Don't have a sense of how edge-casey it could get though :)

**Comment by mitar** [comment]
But probably those who wants to build forms as fast and easy as possible should use some package which generates them for them?

**Comment by lorensr** [comment]
It would be great if a form package was included by default, but until
then, many people won't find one to add.
