### ISSUE TITLE
Change `return false` in form tutorial 

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4258]
https://www.meteor.com/try/4

has

```
    // Prevent default form submit
    return false;
``` 

While `return false` is commonly conflated with `event.preventDefault`, it also stops propagation. In the tutorial, as the comment says, your only goal is to `preventDefault`, so you should set a good example and do `event.preventDefault`. When people get in the habit of returning false, they can't for example make a form component and then add a submit event to the template that includes the component, because the component event accidentally stopped event propagation.

**Comment by stubailo** [comment]
Yes, there's another problem which is that if you have an exception in the event handler the `return false` never happens, and the page refreshes.

This is 100% a correct change to make.

**Comment by lorensr** [comment]
This has been fixed
