### ISSUE TITLE
Improve spacebars string data context

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4259]
When you do `{{> foo uid}}`, where `uid` is `"FuFa6muAquumzfLMC"`, and you're inside a `foo` event, `this` is not a string, but rather an object representation of a string.

```
> console.log this, typeof this, Meteor.users.findOne this
String {0: "F", 1: "u", 2: "F", 3: "a", 4: "6", 5: "m", 6: "u", 7: "A", 8: "q", 9: "u", 10: "u", 11: "m", 12: "z", 13: "f", 14: "L", 15: "M", 16: "C", length: 17, [[PrimitiveValue]]: "FuFa6muAquumzfLMC"}
object
Uncaught TypeError: key.substr is not a function
```

1. It would be nice if `this` was a real string, but I don't think that's possible in JS.
2. If not 1, then it would be nice for Meteor functions that take strings, like `findOne`, to convert these spacebars object strings into real strings instead of throwing errors.

**Comment by Slava** [comment]
1. You are right, the context is always an object (and cannot be a primitive)
2. I don't think it is a good idea to let Minimongo make any assumptions about passed objects.

As unfortunate as it is, I think a good workaround is to not rely on the data context as much in the templates (pass values as arguments, etc).

**Comment by lorensr** [comment]
It wouldn't be making an assumption about passed objects, it would just support an additional type of string, both a string primitive and this Spacebars string object, which I assume you can differentiate (or modify to add a unique property that allows you to differentiate) from normal objects.

**Comment by mitar** [comment]
Yes, probably it would not hurt if Minimongo would check if something is of type `String` object and convert it to the primitive string.
