### ISSUE TITLE
Need onLogin onLogout onUserLoaded hooks/callbacks

### ISSUE THREAD

**Issue by drorm** [meteor/meteor#426]
Just as we have an onCreateUser callback, we need callbacks for login, logout, userLoaded and probably other account related actions.

**Comment by arturcarvalho** [comment]
@Overload119 Your comment helped! Thanks!

**Comment by glasser** [comment]
Yup, onLogin was implemented on the server in 0.7.2 and on the client in 1.0.4.

**Comment by jazeee** [comment]
I don't see Accounts.onLogout to match the onLogin on the client.
Can you add that too?

**Comment by ericmcgregor** [comment]
Yea, this seems like kind of an oversight.  for example, how is someone supposed to handle a re-direct after logout on the client side?  if i'm using accounts-ui and flowrouter, there isn't a hook to detect this is there?  it seems like Accounts.onLogout would be a standard hook.

**Comment by ericmcgregor** [comment]
ah, this solves it:  https://github.com/kadirahq/flow-router/issues/38

just seems kind of strange to be able to handle the login with accounts, but then use Tracker for log out:

Tracker.autorun(function(){
  if(!Accounts.userId()) {
    FlowRouter.go('/login')
  }
})

**Comment by tkiddle** [comment]
For succesful login cb (on the server) assign a new method to: 

Accounts._onLoginHook.callbacks

Works a treat.

**Comment by crapthings** [comment]
@tkiddle neat

**Comment by tmeasday** [comment]
Implemented in #7187
