### ISSUE TITLE
Method called once but executed twice when removing current user

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#4263]
Consider the following code:

```javascript
//---------------------------------

if (Meteor.isServer)
  Meteor.users.remove({});

//---------------------------------

Meteor.methods({

  // Create a user account
  createJohnAccount: function () {
    Accounts.createUser({
      username: 'john',
      email   : 'john@g.com',
      password: '123456'
    });
  },

  // Delete the current user then do something funny
  removeUser: function () {
    // Delete the current user
    console.log('BEGIN - deleteUser: about to remove user ' + this.userId);
    Meteor.users.remove(this.userId);
    console.log('END   - deleteUser: user has now been removed');

    // HERE DO ANYTHING INVOLVING THE Meteor.users COLLECTION, such as a
    // Meteor.users.update() or this one:
    this.setUserId(null);
  }
});

//---------------------------------

// On client...
if (Meteor.isClient) {
  Meteor.startup(function () {
    // create a user...
    Meteor.call('createJohnAccount', function (error, result) {
      // then log him in...
      Meteor.loginWithPassword('john', '123456', function (error) {
        // then remove him...
        console.log('Calling "removeUser"...');
        Meteor.call('removeUser');
      });
    });
  });
}

//---------------------------------
```
Client output, as expected:
```
Calling "removeUser"...
BEGIN - deleteUser: about to remove user RmyLdhJcYmPjEQCy9
END   - deleteUser: user has now been removed
```

Server output, with unexpected double call to `deleteUser':
```
I20150423-15:13:28.239(2)? BEGIN - deleteUser: about to remove user RmyLdhJcYmPjEQCy9
I20150423-15:13:28.241(2)? END   - deleteUser: user has now been removed
I20150423-15:13:28.320(2)? BEGIN - deleteUser: about to remove user null
I20150423-15:13:28.322(2)? END   - deleteUser: user has now been removed
```

The double call happens most of the time, but not always.

Here is the repo: https://github.com/steph643/meteor-issue-4263

**Comment by steph643** [comment]
Might relate to https://github.com/meteor/meteor/issues/4261 or https://github.com/meteor/meteor/issues/4262

**Comment by splendido** [comment]
Commenting `this.setUserId(null);` out fixes the double execution.

...once you have removed the current user object the user on the client will be logged out in any case, so there might be non need to explicitely set the user id to null.

This said, it might still be a bug to get a second execution of the method.

My 2 cents,
Luca

**Comment by splendido** [comment]
It also works with no problems if you move the `setUserId` to the top of the method:


```javascript
Meteor.methods({
  removeUser: function () {
    var userId = this.userId;

    // Log out the user
    this.setUserId(null);

    // Delete the old current user's object
    console.log('BEGIN - deleteUser: about to remove user ' + this.userId);
    Meteor.users.remove(userId);
    console.log('END   - deleteUser: user has now been removed');

    console.log('userId:' + this.userId);
  }
});
```

**Comment by steph643** [comment]
`this.setUserId(null)` is just an example. 

I originally discovered the issue by doing this instead:
```javascript
Meteor.users.update({}, { $pullAll: { favorites: favoriteIds } }, { multi: true });
```
Then I tried other operations on `Meteor.users`: some trigger the double call, some don't. 

The shorter operation I found that triggers the double call is `this.setUserId(null)`, that is why I put it in the code above.

**Comment by steph643** [comment]
I found a workaround. Any operation on `Meteor.users` you want to do after `Meteor.users.remove(this.userId)` should be placed in a `Meteor.defer()`.

For example:
```javascript
    var self = this;
    Meteor.defer(function() {
      self.setUserId(null);
    });
```

**Comment by alanning** [comment]
Thanks for the pointer on `Meteor.defer`.  I just ran into a similar situation with Meteor 0.7.1.2 where my enrollUser Meteor method was being executed twice because it called `setUserId` as part of my `Accounts.callLoginMethod({methodName: 'enrollUser', ...})` flow.

**Comment by mitar** [comment]
Oh, yea. This is probably reasonable. When you remove your server-side user document, that is pushed to the client. So maybe then that change loops back to the server, calling the method once more or something?

**Comment by glasser** [comment]
Thanks for the reproduction!

This is actually working as intended.  First, you remove the record from the database.  Then you make a call that yields (`setUserId` yields because it has to re-run all publishers with the new ID).  During the yield, the background observe thread notices that the user object is gone and disconnects the connection.  The client sees this and reconnects; because the `removeUser` method was in flight and never got a response, it runs it again.

The automatic disconnection of invalid connections is basically a security watchguard.  It's rare that you actually want to disconnect the current connection, so instead you should log the current connection out (transitioning it back to a no-user-id connection) before doing the remove, eg:

```js
    var id = this.userId;
    Meteor.call('logout');  // at this point, this.userId is null and the token has been removed
    console.log('BEGIN - deleteUser: about to remove user ' + this.userId);
    Meteor.users.remove(id);
    console.log('END   - deleteUser: user has now been removed');
```

This works the way you'd expect, and doesn't require a DDP-level reconnect!

**Comment by mitar** [comment]
Ah, so the solution is to call `Meteor.call('logout')` instead of manually use `setUserId`. Good to know.

**Comment by steph643** [comment]
@glasser, thanks a lot. Your explanation makes perfect sense.

Issues https://github.com/meteor/meteor/issues/4261, https://github.com/meteor/meteor/issues/4262 and https://github.com/meteor/meteor/issues/4263 make it overly complex to implement the "Delete My Account" feature. As this feature is (or should be) part of any application, I think updating the Meteor doc is required. I am about to issue a PR.
