### ISSUE TITLE
Dependency error android-support-v4.jar

### ISSUE THREAD

**Issue by stormbkk87** [meteor/meteor#4265]
I'm getting a dependency mismatch when compiling for Android. None of my other cordova plugins complain.

    Found 2 versions of android-support-v4.jar in the dependency list,
    [dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
    [dependency] All versions of the libraries must be the same at this time.
    [dependency] Versions found are:
    [dependency] Path: /local/cordova-build/platforms/android/com.phonegap.plugins.facebookconnect/mobile-FacebookLib/libs/android-support-v4.jar
    Length: 758727
    [dependency]    SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
    [dependency] Path: /local/cordova-build/platforms/android/libs/android-support-v4.jar
    [dependency]    Length: 987314
    [dependency]    SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

**Comment by stormbkk87** [comment]
When I create a blank project and add the com.phonegap.plugins.facebookconnect plugin all works fine. How do I resolve dependencies meteor uses? Both projects are meteor 1.1.0.2.

**Comment by stormbkk87** [comment]
I found the issue. The cordova:plugin.google.maps@1.2.4 was adding the improper dependency. Why it was in the main meteor lib folder I'm not sure. Hope this helps someone.

    Fix: remove cordova:plugin.google.maps@1.2.4 and add cordova:plugin.google.maps@1.2.5

**Comment by keyvanfatehi** [comment]
I am having this same error when trying to use this plugin https://github.com/Wizcorp/phonegap-facebook-plugin

Here's the error:

This issue should probably be reopened.

```
Running command: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/cordova/run --device
Buildfile: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/build.xml
-set-mode-check:
-set-debug-files:
-check-env:
 [checkenv] Android SDK Tools Revision 23.0.2
 [checkenv] Installed at /Users/keyvan/.meteor/android_bundle/android-sdk
-setup:
     [echo] Project Name: CordovaApp
  [gettype] Project Type: Application
-set-debug-mode:
-debug-obfuscation-check:
-pre-build:
-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
     [echo] Resolving Build Target for CordovaApp...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for CordovaApp...
[dependency] Library dependencies:
[dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[dependency]
[dependency] ------------------
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/com.phonegap.plugins.facebookconnect/testapp-FacebookLib/libs/android-support-v4.jar
[dependency]    Length: 758727
[dependency]    SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/libs/android-support-v4.jar
[dependency]    Length: 19036
[dependency]    SHA-1: bc202617b4cfed6673b1e10d87e52c78f7a6de38
Command finished with error code 8: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/cordova/run --device
ERROR running one or more of the platforms: Error: /Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project
BUILD FAILED
/Users/keyvan/.meteor/android_bundle/android-sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies
Total time: 1 second
/Users/keyvan/Projects/testapp/testapp-meteor/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
```

**Comment by Slava** [comment]
Cordova is known for leaving random build files of plugins even after the plugin was removed. A solution that users of Meteor Cordova can use: either run `meteor reset` or remove the Cordova build folder `rm -rf .meteor/local/cordova-build` and rebuild the project from scratch.

**Comment by keyvanfatehi** [comment]
@Slava the issue was that two cordova plugins (local notifications and facebook) were both loading in an android-support-v4.jar -- so i had to remove one. I removed local notifications and the bug went away. 

Definitely out of scope of meteor.

**Comment by edabdoub** [comment]
@keyvanfatehi  so there is not a way to use facebook plugin with local notifications?

**Comment by keyvanfatehi** [comment]
It appears that way. You probably have to make a version of that support file that has all the prototypes expected by both plugins and then only include one or something. I don't know enough android or Java to speculate even half-correctly here, sorry
