### ISSUE TITLE
Allow adding custom metadata to packages which would then be available through the API

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4267]
I would like to create [Blaze Components package explorer](https://github.com/peerlibrary/meteor-blaze-components/issues/31). I was thinking that it would be great if one could do:

```
Package.describe({
  name: 'namespace:button-component',
  version: '0.1.0',
  isBlazeComponent: true
});
```

And then somehow I could get through the [API](https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API) this extra metadata (and preferably even filter by it).

Or is that already possible?

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by ekatek** [comment]
Hm. That's not something that you can do yet, though more for product reasons (not sure how this would be used, not sure if a proliferation of custom labels would make things difficult to understand/hard to support later, not sure if this opens us up to something trolly, nobody has ever asked for it before, etc). That's not to say that we are opposed to it -- just that it probably won't happen super soon. We'll keep the issue open for future reference.

**Comment by mitar** [comment]
Could we maybe support only one extra field? Something like:

```
Package.describe({
  name: 'namespace:button-component',
  version: '0.1.0',
  custom: {}
});
```

And that dict is simply directly stored as part of metadata, no questions asked. You do not have to provide any special API to access it, just that it is available as part of `versions` collection.

I used Python [PyPi](https://wiki.python.org/moin/PyPIXmlRpc) in the similar way in the past. They offer two fields like this, `keywords`, which is completely arbitrary set of strings, and `classifiers`, which is moderated set of classifiers. When you have more than 10 packages or so (a relevant number of them), you can get your own classifier you can then use. Here is the [list of classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers).

So I think what I am suggesting is that at least something like that would be really great to have. At least keywords/tags.

**Comment by mitar** [comment]
Probably one reason why there is not much requests for this yet is because there are not many alternative package browsers yet made. So my experience making a new one (see it [here in action](http://components-explorer.meteor.com/)) is that API is mostly easy to use, just finding relevant packages inside all packages is hard. So something like proposed above would be really helpful.

I do not see much downside to do it. It would just allow subcommunities/subecosystems to emerge. Which I think is really useful/important. It would also allow for some experimentation about packages. Currently we have only versions and there is only one way to use versions. Such tags could also be used by wrapper scripts around `meteor add` and `meteor search` to guide you choosing a package.

**Comment by ekatek** [comment]
Yeah -- I think that is pretty close to how we would want to structure it (having a custom field, separating metadata-only user information from the stuff that's used by the tool).  Another way to do this is just to allow a list of keywords (which would also be used by `search` and/or package browsers).

That's an interesting idea -- how would you use such tags in `meteor add`?

'It would also allow for some experimentation about packages. Currently we have only versions and there is only one way to use versions. ' 

Can you elaborate on what you mean by this/how this relates to your proposal? I am a bit confused.

**Comment by mitar** [comment]
> That's an interesting idea -- how would you use such tags in meteor add?

Oh, this was mostly an idea for wrapping scripts, not for official `meteor add`. So if community would start using such tags for example to mark packages with the licenses they use, you could assure that `meteor add` adds only the packages which are compatible with the license of your code. Tags could tell which language pack is used in a particular package variation, so when doing `meteor add` it could automatically choose the right language.

> Can you elaborate on what you mean by this/how this relates to your proposal? I am a bit confused.

Oh, I thought that tags could be used to mark things like `preview`, `experimental`, `branch-name`. So you could have more metadata information than just the version string. I know that you can add stuff to the version string in semver, but explicit tags could be helpful here.

I am just saying that such custom tags/metadata could open some experimentation. Currently there is no extension point to do anything special with packages. Just whatever you officially support. So having at least something custom would help.

**Comment by ekatek** [comment]
Thanks lots! That explanation is useful, though I am not sure how much tags versus, for example, forking, would help there. We'll think about it, and whether this is going to happen in the short term.

**Comment by mitar** [comment]
@stubailo, this is also one of those packages which would really be helpful for the community to then build things for and around Meteor ecosystem. Just imagine an explorer of Blaze Components. Something [like this](http://blaze-material-ui.meteor.com/), but dynamically generated.

**Comment by mitar** [comment]
Please please. It is really so hard to allow custom `custom` tag in the package description which gets pushed into packages API? It is completely backwards compatible, and it can create great ways to build ecosystems on top of Meteor packages.

```
Package.describe({
  name: 'namespace:button-component',
  version: '0.1.0',
  custom: {}
});
```

**Comment by mitar** [comment]
I would really urge if this could be added. It would be really great and now there is some larger interest in creating a repository of Blaze Components. It would be great if it would be possible to define custom metadata of the package which one could then get out through Atmosphere API. This should really be very straightforward to add.

@zol, @benjamn

**Comment by zol** [comment]
@mitar, can you work around this by including a token within the description?

**Comment by mitar** [comment]
So some HTML tag inside markdown of the description, which is otherwise not rendered? A microformat-kind of a thing? :-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20adding%20custom%20metadata%20to%20packages%20which%20would%20then%20be%20available%20through%20the%20API&body=Migrated%20from:%20meteor/meteor%234267) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
