### ISSUE TITLE
Observe *changes* to a cursor

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4269]
Apparently when you run [`Cursor.observeChanges`](http://docs.meteor.com/#/full/observe_changes), all the documents in the cursor initially call `added`. This makes it difficult to determine if there is actually a new document being inserted or it was already there. Any ideas how I could skip the initial documents all calling added?

This is related to my question on the [Meteor forums](https://forums.meteor.com/t/modeling-and-publishing-likes-or-stars/3422)

**Comment by rclai** [comment]
I think this example from the docs might be relevant:

```js
ar initializing = true;

  // observeChanges only returns after the initial `added` callbacks
  // have run. Until then, we don't want to send a lot of
  // `self.changed()` messages - hence tracking the
  // `initializing` state.
  var handle = Messages.find({roomId: roomId}).observeChanges({
    added: function (id) {
      count++;
      if (!initializing)
        self.changed("counts", roomId, {count: count});
    },
    removed: function (id) {
      count--;
      self.changed("counts", roomId, {count: count});
    }
    // don't care about changed
  });

  // Instead, we'll send one `self.added()` message right after
  // observeChanges has returned, and mark the subscription as
  // ready.
  initializing = false;
```

**Comment by ccorcos** [comment]
Hmm. That seems rather procedural, doesn't it?

What would be awesome is if I could do something like this:

```coffee
Magic.autorun (__) ->
  count = Comments.find({postId:__}, {fields:{'_id':1}}).count()
  Posts.update(__, {$set:{nComments:count}})
```

**Comment by ccorcos** [comment]
@rclai, the only problem with this method is that on startup, there will still be N calls to `added`. At some point, that could be very inefficient...

**Comment by rclai** [comment]
Yeah, it is unfortunately. There would need to be some kind of pull request for a `find` option like `skipInitialDocs` or something like that.

**Comment by ccorcos** [comment]
hmm. well thats no good!

**Comment by rclai** [comment]
In regards to what you asked on the forum, why not use collection hooks (on the server) to increment or decrement a numeric field starsCount on the posts?

**Comment by ccorcos** [comment]
Collection hooks only works for client calls. If I do everything with Meteor.methods, the hooks don't work... :/

**Comment by ccorcos** [comment]
wait a sec. it appears they've updated package to handle server calls. That should work then!

That said, perhaps I should leave this ticket open as a feature request?

**Comment by stubailo** [comment]
You said you are already using methods to do everything, why not just add a line to the method that will increment the counter?

**Comment by ccorcos** [comment]
Thats just not very declarative or DRY. Suppose we have multiple different methods that add comments, then we'd have to be sure to include that update everywhere. With collection hooks at least, we can do the update in one place which is nice. But even that is procedural -- "update nComments when a comment is inserted". A more declarative way of doing it would be something like:

```coffee
Tracker.autorun ->
  Posts.update(postId, {$set: {nComments: Comments.find({postId:postId}).count()}})
``` 

However, it would be infeasible to have that many autoruns if we have a trillion posts. One thing that comes to mind is some sort of pattern-matching using wildcards:

```coffee
var postId = new Cursor.wildcard()
Tracker.autorun ->
  count = Comments.find({postId: postId}, {fields:{'_id':1}}).count()
  Posts.update(postId, {$set:{nComments:count}})
```

In this case, postId is a wildcard. Thus the autorun will depend on `Comments.find({}).count()` and whenever the cursor changes, postId will be assigned the postId property of the comment. The autorun will rerun, and the Posts.update will recognize that the wildcard has a value and update the appropriate post.

Just brainstorming here... I'm trying to think of how else wildcards would be used. Its an intriguing concept and it gets across the point about being declarative...

**Comment by ccorcos** [comment]
I suppose wildcards would be useful for two-way data binding.

Suppose you have something like:

```js

user = {
  username: 'joe'
  profile: {
    projects: ['github', 'facebook']
  }
}

project = {
  name: 'github'
  users: ['joe', 'charlie']
  //...
}
```

It would be great if we could keep these things in sync without having to manually update one when the other changes. If the cursor object to recognize and properly handle wildcards, you could do something like this:

```js
var USERNAME = new Cursor.wildcard()
var PROJECTS = new Cursor.wildcard()
Tracker.autorun(function() {
  Meteor.users.find({username: USERNAME, 'profile.projects':PROJECTS})
  PROJECTS.value.map(function(name) {
    Projects.update({name:name}, {$addToSet:{users:USERNAME.value}})
})
var USERS = new Cursor.wildcard()
var NAME = new Cursor.wildcard()
Tracker.autorun(function() {
  Projects.find({name:NAME, users:USERS})
  USERS.value.map(function(username) {
    Meteor.users.update({username:username}, {$addToSet: {projects: NAME.value}})
  })
})
```
There would have to be some checks in there to make sure wildcard.value isn't undefined, but this just an idea. Using `$addToSet` should prevent both the autoruns from circularly depending on each other.

Its also nice that we can add a user to a project or a project to a user and the other one should update accordingly. We also don't have to wait for the initial added documents to Cursor.observeChanges.

Anyways, just an idea. What do you think?

**Comment by Koleok** [comment]
This is very old obviously, but FWIW i was able to get around the issue doing

```js
const query = { someKey: true };
const existingIndexLimit = collection.find(query).count() - 1;

collection.find(query).observe({
  addedAt(doc, index) {
    if (index > existingIndexLimit) {
      console.log(doc)
    }
  },
});
```

Using `addedAt` turns out to be less than performant though, so I had better success with

```js
const query = { someKey: true };
const existingSet = collection.find(query, { fields: { _id: 1 } }).fetch();
const notInInitialSet = R.complement(R.contains(R.__, existingSet)); // using some ramda here

collection.find(query).observe({
  added(doc) {
    if (notInInitialSet(doc._id)) {
      console.log(doc);
    }
    // return processMessage(doc).fork(console.error, r => console.log('result', r));
  },
});
```

this one may be less performant with giant datasets, but i wouldn't think that'd be an easy obstacle to hit and you are only paying the cost once really.
