### ISSUE TITLE
Update Underscore version

### ISSUE THREAD

**Issue by gwendall** [meteor/meteor#4270]
The MDG package is based on Underscore 1.5.2 (https://github.com/meteor/meteor/blob/devel/packages/underscore/underscore.js - that was released in Sept 2013) whilst the library now reached 1.8.3 with some cool new functions like _.mapObject. Any plan to update your package soon?

**Comment by mitar** [comment]
Duplicate of #1009.

**Comment by stubailo** [comment]
Closed as duplicate, thanks mitar!
