### ISSUE TITLE
Switch from bcrypt to scrypt

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4272]
As recommended by Jeff Atwood: 

http://blog.codinghorror.com/your-password-is-too-damn-short/

Why scrypt is harder to crack:

> bcrypt and PBKDF2 aim to make calculation computationally expensive, which in turn makes them slow. However, both are incredibly parallel - with twice the hardware, you crack the passwords nearly twice as fast. scrypt tries to counter that through ‘memory hardness’.
> 
> It’s complicated and mathy, but the unique idea that scrypt brings to the table is that it tries to use as much memory as it can while completing its calculation within the same running time. This is the exact opposite of what most people want their code to do, but makes for a strong algorithm which requires a lot of storage, and resists parallelization making it much more resistant to hardware attacks whether from ASICs, FPGAs, or GPGPUs.

**Comment by laosb** [comment]
Sss....... I just found that most of my passwords are shorter than 12 characters. Modifying....

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
Migrated to https://github.com/meteor/meteor-feature-requests/issues/55.
