### ISSUE TITLE
Create user directly

### ISSUE THREAD

**Issue by psy21d** [meteor/meteor#4273]
I need to create users in meteor.
I have a coupe of problems with that process.

First, do not know how to activate creating accounts on default version. 
Which way to fix error "Signups forbidden [403]".

Next, when I build and deploy meteor, I need to create accounts directly to database.
Meteor console does not work on deployed program.
How I can create users now and how about rights? 

And third problem is login (default) buttons show so long. Why?
http://stopcredit.pro/secretpage

Thank you!

**Comment by M4v3R** [comment]
This is more a [Stackoverflow](http://stackoverflow.com/tags/meteor) question, than a bug.

I think you're using the old accounts UI package, which has a `forbidClientAccountCreation` set by default.

Try `accounts-ui` package to get a proper, working UI to login/register.

As for having users already created on production app, you can create a method in your server routines that does check if there are default users and creates them if not:

```
    if (Meteor.users.find().count() === 0) {
        // create users using Accounts.createUser method
    }
```

**Comment by psy21d** [comment]
accounts-ui without a version constraint has already been added.
It is not because accounts-ui, there is strange setting I do not know, where.

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
