### ISSUE TITLE
Cannot create "acme" organization

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4276]
I would like to create `acme` organization. Meteor tool is saying that it does not exist. But web interface is saying that it does exist. Is this a bug?

**Comment by ekatek** [comment]
In what context does the tool say that it doesn't exist?  Which command, specifically, are you running?
(You are right that the website says that it does)

**Comment by mitar** [comment]
```
meteor admin members acme --list
Error showing organization: Organization does not exist
```

```
meteor admin members mdg --list
Error showing organization: You are not a member of this organization.
```

**Comment by ekatek** [comment]
Ah, interesting. Thanks. It may be that acme is a user (or was a user?) and the error message on the webpage is misleading. Or there is some bug in how things are propagated. We'll take a look. Thanks!

**Comment by mitar** [comment]
Anyway, if it is possible somehow to register an organization with this name, please tell me. :-)

**Comment by mitar** [comment]
(I would like to start something similar to [Perl ACME](https://en.wikipedia.org/wiki/Perl#CPAN_Acme). See [examples](http://www.perlmonks.org/?node_id=558220).)

**Comment by abernix** [comment]
Fairly sure that the obstacle here is that an organization just cannot be the same as an existing username.

The message could be more clear (e.g. "This name is not available") but I'm not sure this can be fixed from meteor/meteor and I'm not sure it should stay here in the work queue.  Hope you don't mind if I close this (though I do love your intention for the acme idea even if you've probably forgotten about it entirely at this point :Smile:).

**Comment by mitar** [comment]
I have not forgotten it. I just gave up. :-(

But I think that Meteor should have some anti-squatting policy and also a way to resolve squatting. See examples:
* https://help.github.com/articles/name-squatting-policy/
* https://gitlab.com/gitlab-org/gitlab-ce/issues/14932

cc @theadactyl
