### ISSUE TITLE
Provide jQuery on the server side as well

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4279]
Some utility functions available in jQuery can work on the server side as well. I think you should simply export the symbol on the server side as well, instead of loading it only on the client.

**Comment by macrozone** [comment]
Some of jQuery's utility-functions that are not dom-specific are available in underscore as well. I personally prefer to use jQuery only for dom-specific functions and underscore for everything else.

**Comment by mitar** [comment]
I agree, but sometimes an exactly the same semantics is preferred.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by capensisma** [comment]
this is a MUST if one want to manipulate html documents instead of using complex regexp to search and find DOM element from and html string

A MUUUUUUUUST
I tried using this but it does load the jquery on the server 
`  api.use('jquery','server');
`

Why why ?
why is that ?

ALL the frameworks allow the dom manipulation : PHP,Python, Ruby ...

Dude hurry up
ovious thing should be already implemented !!!

**Comment by rclai** [comment]
Lol...

**Comment by robertpitt** [comment]
^ lol 

![jquery-0](http://bradsknutson.com/wp-content/uploads/2014/05/1bim.jpg)

**Comment by yaliceme** [comment]
Hi @rclai, @robertpitt, we would appreciate if you could keep your comments helpful and welcoming going forward

**Comment by rclai** [comment]
@capensisma you should be able to install it via `meteorhacks:npm` https://www.npmjs.com/package/jquery

**Comment by Ericzhiluo** [comment]
So true, jQuery is must in server side!!!!

**Comment by capensisma** [comment]
@Ericzhiluo YES I told them and they started **joking** about me!! they don't even know the plenty cases you need this!

Anyway I solved this by using (cheerio)[https://www.npmjs.com/package/cheerio] until they find a way so we can enable it on the server! like a custom Jquery Server!

**Comment by hwillson** [comment]
Now that Meteor directly supports npm, you can `npm install` jquery and access it server side. Quick example:

```
meteor create jquery-server-test
cd jquery-server-test
meteor npm install
meteor npm install --save jsdom
meteor npm install --save jquery
```

Replace the contents of `server/main.js` with the following:

```
import jsdom from 'jsdom';
jsdom.env('', (error, window) => {
  const $ = require('jquery')(window);
  console.log($.param({ someKey: 'Some Value!' }));
})
```

After running the app, you'll see the following in your server console:

```
I20170113-13:50:59.559(-5)? someKey=Some%20Value!
```

Given this, I'll close this off. Thanks for opening this originally!

**Comment by meteorplus** [comment]
@hwillson thank you :)
