### ISSUE TITLE
How can I specify --variable when adding cordova plugin

### ISSUE THREAD

**Issue by c316** [meteor/meteor#4280]
I'm trying to use https://github.com/EddyVerbruggen/Custom-URL-scheme with my Meteor app.

The normal way to add in Cordova is by running this at the CLI after chaning 'mycoolapp' out for your own app schema name.

```
$ cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp
```

I can run 
```
meteor add cordova:nl.x-services.plugins.launchmyapp@https://github.com/EddyVerbruggen/Custom-URL-scheme/tarball/3ce0b6df0eb7115114f11b448a99648825a8db13
```

without a problem, but when I launch the app I get this 

```
Error while running for mobile platforms: Failed to install plugin                 
nl.x-services.plugins.launchmyapp: Variable(s) missing (use: --variable URL_SCHEME=value).
``` 

If I try to run 
```
meteor add cordova:nl.x-services.plugins.launchmyapp@https://github.com/EddyVerbruggen/Custom-URL-scheme/tarball/3ce0b6df0eb7115114f11b448a99648825a8db13 --variable URL_SCHEME=appname
```

I get this error

```
--variable: unknown option.
Usage: meteor add <package> [package..]

Adds packages to your Meteor project. You can add multiple
packages with one command. To query for available packages, use
the meteor search command.

Options:
  --allow-incompatible-update   Allow packages in your project to be upgraded or
                   downgraded to versions that are potentially incompatible with
                   the current versions, if required to satisfy all package
                   version constraints.

```

Is there a way to add the variable to a cordova plugin?

**Comment by c316** [comment]
Nevermind, I found the answer in the docs. 

http://docs.meteor.com/#/full/mobileconfigjs

In the mobile-config.js file add

```
App.configurePlugin('nl.x-services.plugins.launchmyapp', {
    URL_SCHEME: 'appnamehere'
});
```

**Comment by alpjor** [comment]
@c316 Were you able to get the plugin to work with Meteor? I've been trying and having issues where it builds fine but simply doesn't make the url scheme changes in the native builds.

**Comment by c316** [comment]
It does work for me, but it isn't working well. It will launch the app, but I can't figure out how to get the path and query params to passthrough. I've been scratching my head about who to ask how I can make this connection. Is it an iron-router issue, an issue with ionic, is it a cordova issue, do I need to write some angular code. Part of the issue is that the launchmyapp plugin would usually setup a global variable to catch the launch and then you'd write your routing from there, but since this is a meteor app with its own routing I can figure out where I should be putting that function...

If you can't get it to make a URL_SCHEME change you might try adding the original URL_SCHEME back in, then run the app, then remove it. Then add the new URL_SCHEME back in. There is an issue on the github page for this plugin that talks about this. 

I haven't tried this on Android, just the iOS simulator, so I'm not sure if I'll run into a problem there. 

If you figure out how to route I'd really appreciate an update. I'll make sure I update you if I find out. 

Thanks

**Comment by glasser** [comment]
Glad to see you figured this out for yourself!

**Comment by keyvan-m-sadeghi** [comment]
@c316 I had a similar situation, resolved it by placing `handleOpenURL` at my main 'index.html' in a `script` tag:
```html    
    <body>    
    <script>
        oauth_code = "";
        function handleOpenURL(url) {
            var path = url.split("<SCHEMA_HERE>://")[1];
            var regex = new RegExp("[\\?&]" + '<VARIABLE_NAME_HERE>' + "=([^&#]*)"),
            results = regex.exec(url);
            variable = results[1];
            // Variable is now stored at 'variable'
        }
    </script>
    
    </body>
```

Hope this helps.

**Comment by c316** [comment]
@keyvan-m-sadeghi Thanks. Right now my browser policy doesn't permit inline scripts, so that wouldn't work, but thanks for posting your solution.

**Comment by AndyHan1001** [comment]
But If I move mobile-config.js into a package (because I need to do isolation like http://www.angular-meteor.com/tutorials/socially/angular1/mobile-support-and-packages-isolation), "App.configurePlugin" cannot work, since I still have the following error: 

While adding plugin                                                          
   https://github.com/boxfish/cordova-plugin-wechat.git#fcb8292d5a058eefc428aa1518fb8a0cf5df48f1
   to Cordova project:
   Cordova error: Variable(s) missing (use: --variable WECHATAPPID=value).      
   (If the error message contains suggestions for a fix, note that this may not 
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)

How to solve this issue?
