### ISSUE TITLE
observe/observeChanges are not reliable on the client

### ISSUE THREAD

**Issue by theosp** [meteor/meteor#4282]
On the client, operations on data that is watched by observe/observeChanges triggers the observers' callbacks before acknowledgment from the server received for the operation (in accordance with the latency compensation principal). In cases where the operations fails, the rollback operation is not reported to the observers, thus making it unreliable on the client.

I use observeChanges to synchronize a data structure that I am building from raw data stored in Mongo. When the user edits the data structure I only update the raw data (with Mongo operations). Thus I use this observeChanges to update the data structure for updates to the raw data that comes both from the server and the client itself. Since observers aren't called in cases where Mongo operations are rejected by the server and the local data (stored in minimongo) is being reverted, I can't have a clean implementation of the data structure synchronizer that is based on observeChanges but have to, for every mongo operation I do, look for the operation callback's err argument and perform required revert to the data structure by myself.

Thanks,
-Daniel

**Comment by Slava** [comment]
I think what you actually want here is a callback or an event whenever the DDP connection tells the collection to "retrieve originals" (i.e. "revert the simulated updates").

**Comment by Slava** [comment]
I tried to reproduce it and failed. For me, I get the `removed` event when the server rejects the change. https://github.com/Slava/meteor-issue-4282
