### ISSUE TITLE
Tinytest in-browser driver freezes browser with lots of assertions

### ISSUE THREAD

**Issue by kostko** [meteor/meteor#4283]
I have a server-side test case which results in more than a thousand passing assertions. The test case executes rather quickly on the server, but then the browser freezes, probably when trying to render the list of assertions. If I run the same test using the in-console driver, everything runs fine.

**Comment by mitar** [comment]
I think you should make a reproduction.

**Comment by Slava** [comment]
We expect a reproduction in a form of a clonable repository to be able to reproduce the issue.
