### ISSUE TITLE
Can't resume to log in remote ddp account server with token when refresh the page.

### ISSUE THREAD

**Issue by lzl** [meteor/meteor#4286]
I think this issue is related with `Project:Accounts:Password` and `Project:DDP`.

I set up a server `http://localhost:3000` and a client `http://localhost:4000`.

The client connect server via ddp. Code:

````js
var connection = DDP.connect("http://localhost:3000");
Accounts.connection = connection;
Meteor.users = new Mongo.Collection("users", {connection: connection});
````

Then add `accounts-password` and `accounts-ui` packages and set up `{{> loginButtons}}`.

I logged in at `http://localhost:4000` client successfully. At browser console, the result of `Meteor.userId` is the same at `http://localhost:3000` server.

Everything is fine. Except...

Except if I refresh the page. My account is logged out automatically. At browser console, it shows:

`Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`

How to resolve this problem?

Side note 1: When I refresh the page, the `Meteor.loginToken` and other two at Local Storage are removed.

Side note 2: Every about ten minutes, the terminal console of `http://localhost:4000` shows:

```
I20150428-10:59:29.387(8)? Exception in setInterval callback: Error: Not permitted. Untrusted code may only update documents by ID. [403]
I20150428-10:59:29.390(8)?     at throwIfSelectorIsNotId (packages/mongo/collection.js:380:1)
I20150428-10:59:29.390(8)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/mongo/collection.js:560:1)
I20150428-10:59:29.391(8)?     at Accounts._expireTokens (packages/accounts-base/accounts_server.js:858:1)
I20150428-10:59:29.391(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150428-10:59:29.391(8)?     at packages/meteor/timers.js:6:1
I20150428-10:59:29.391(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Because you did not provide a real reproduction, I have no idea if you actually mean you wrote `Meteor.users = new Mongo.Collection("users", {connection: connection});` in your code or not.  You don't need to do that; it should automatically use `Accounts.connection`.  I'm not sure what would happen if you redefine Meteor.users like this, but I can imagine it could cause strange problems.

**Comment by glasser** [comment]
Oh, also, the way to use `Accounts.connection` is undocumented, but it's to set `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` to an URL in top-level server code.  (#4233 by @benjamn may make this easier.)

**Comment by lzl** [comment]
Thank you @glasser !

Here is my reproduction: https://github.com/lzl/meteor-issue-4286

Its README.md has more information.

**Comment by mahiagit** [comment]
Yes i was also facing the same stuck in which the logged is user logged out as refresh the page. the scenario is same as expressed above . Any body have some clue..

**Comment by shactdeveloper** [comment]
Hi, I'm facing the same problem, when I refresh the page, the user is logged out

**Comment by FlawaCLV** [comment]
Same problem for me, anyone managed to solve it ?
