### ISSUE TITLE
"fieldNames is an array of the (top-level) fields in doc"

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#4288]
This is not really an issue, but more a small thing I was wondering about. In `allow/deny` callbacks, wouldn't it be more useful if `fieldNames` returned the names of *all* fields being operated on, and not just top-level ones?

**Comment by Slava** [comment]
This is partially due to the fact that DDP operates only on top-level fields (to map better to a wider variety of databases, such as SQL).

This is an architectural decision that doesn't look like a bug?

**Comment by SachaG** [comment]
Yeah sorry, I should've created a thread in the forum. Just one last thing, does that mean using only top-level fields is a little bit more "Meteor-y"?

**Comment by Slava** [comment]
I would say it is more DDP-y.

**Comment by rclai** [comment]
This is also one of the reasons I've stated in the Hackpad why we should deprecate the profile users field.

**Comment by SachaG** [comment]
The reason I'm asking is because I was thinking of creating a `user.telescope` object to hold all Telescope-related properties instead of putting them on the root of the object, to avoid any variable name conflicts in case someone wants to run other packages alongside Telescope. 

But dealing with nested objects seems to make a lot of things harder, so now I'm thinking maybe I'd be better off keeping those properties on the root of the object and just prefixing them with `telescope_` or something?
