### ISSUE TITLE
DDP adaptation for mobile devices

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#4290]
At the moment there is an issue with the DDP protocol's ability to resume state.

Consider a method 

```
var Fiber = Npm.require('fibers');

function sleep(ms) {
    var fiber = Fiber.current;
    setTimeout(function() {
        fiber.run();
    }, ms);
    Fiber.yield();
}

Meteor.methods({
   test: function() {
      var id = Random.id();
      console.log(id);
      sleep(10000);
      return id;
   }
});
```

If a mobile app calls `Meteor.call("test", function(err, result) { console.log(err, resut)});` and is backgrounded immediately after then loaded back after a short period\* (~10-30 seconds)

The mobile app will make a new request even though the old one has completed and has a result. This first result will be ignored and the call will begin afresh (even though the second `Meteor.call("test"..` has not actually been called.

This is a problem for more sensitive applications. For example: "Give 10 points to user Y". User Y would get 20 points (or even an uncertain number of points > 10 points), but never 10 points as the user intends.

Cordova didn't exist while the current version of the DDP protocol was availed (from pre 1 and up to 1) but this is a consideration that may need to be taken into account into future versions.

**Comment by stubailo** [comment]
Hi @Tarang! This is working as documented:

> If a client calls a method and is disconnected before it receives a response, it will re-call the method when it reconnects. This means that a client may call a method multiple times when it only means to call it once. If this behavior is problematic for your method, consider attaching a unique ID to each method call on the client, and checking on the server whether a call with this ID has already been made.

From http://docs.meteor.com/#/full/meteor_methods

We can keep this open as a feature request to possibly improve this in the future.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=DDP%20adaptation%20for%20mobile%20devices&body=Migrated%20from:%20meteor/meteor%234290) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
