### ISSUE TITLE
Email.send in windows

### ISSUE THREAD

**Issue by JimHough** [meteor/meteor#4291]
I have an app that is working fine in ubuntu in windows the Email.send function seems to queue the email for sending without the sending completing. 
When the meteor server is restarted the emails all arrive.
I have made a minimal meteor app with only the email package added and a single button to invoke a server method to send the email.
I have tried tracing what is going on in the simplesmtp package using node inspector.
I have also logged the network traffic using Microsoft network monitor.
I have tried different SMTP servers including the SMTP test server Neptune from Donovan Brown.
From the log it seems to send the EHLO, MAIL FROM and RCPT TO commands then a RSET command seems to be issued but I cant trace what is generating this command.

Any help or other experience with this matter would be greatly appreciated.

**Comment by stubailo** [comment]
Can you post the minimal app you made? I will run it on my computer and see if I can reproduce the issue.

**Comment by JimHough** [comment]
Here is the code for the minimal app:
TestEmail.html
```html
<head>
  <title>TestEmail</title>
</head>

<body>
  <h1>Testing Email.send()</h1>
  {{> test}}
</body>

<template name="test">
  <button>Send Email</button>
</template>
```
TestEmail.js
```javascript
if (Meteor.isClient) {
  Template.test.events({
    'click button': function () {
      Meteor.call(
        'sendEmail',
        'xxx@xxxx.com',  //to
        'xxx@xxx.com',   //from
        'Test email subject', //subject
        'Test email text\n'   //text
      );
    }
  });
}

if (Meteor.isServer){
  process.env.MAIL_URL = 'smtp://localhost:25/';
  Meteor.methods
  ({
    sendEmail: function (to, from, subject, text){
      console.log("*** sendEmail ***");
      try{
        Email.send({
          to: to,
          from: from,
          subject: subject,
          text: text
        });
      }
      catch(err){
        console.log("Error Sending Email");
        console.log(err);
      }
    }
  });
}
```

Thanks for looking into the problem. The emails seem to finally send when the meteor app is stopped in the console (Ctrl+C twice).

**Comment by JimHough** [comment]
I have also added a Git repo with the project if this helps: https://github.com/JimHough/MeteorProjects/tree/master/TestEmail

**Comment by abernix** [comment]
There haven't been other complaints of this in over a year though so this seems to be an isolated situation or strangeness in your setup and hasn't got much traction.  If you're seeing Meteor communicate with your mail server, it's very likely an authorization problem or a misconfiguration in the MTA.
