### ISSUE TITLE
Npm.depends() unable to parse .

### ISSUE THREAD

**Issue by mattpolicastro** [meteor/meteor#4293]
Tried adding the Chart.js library as a local package through its NPM module:
````javascript
Package.describe({
	name: "chartjs",
	summary: "Chart.js charting library",
	version: '0.1.0'
});

Npm.depends({chart.js: '1.0.2'});

Package.onUse(function(api){
	api.versionsFrom('1.0.2');
	api.addFiles('chart.js');
	api.export('Chart');
});
````
But running into the following error:
````shell
While reading package from `.../appName/packages/chartjs`:
package.js:7:19: Unexpected token .
````
Obviously the use of the `.` in the Chart.js npm package name is wonky. I tried passing it as a string, which caused `Error: Can't find npm module 'double-ended-queue'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?`; passing it without the `.` just meant it couldn't locate the package.

Should `Npm.depends({})` be able to handle this case?

**Comment by stubailo** [comment]
Have you tried `Npm.depends({'chart.js': '1.0.2'});`?

**Comment by mattpolicastro** [comment]
Yes, I attempted both single- and double-quotes, which both result in the `double-ended-queue' error.

**Comment by mattpolicastro** [comment]
@stubailo I did some more investigating last night, and it appears that some of my Meteor/npm modules were corrupted—when I run `Npm.depends({'chart.js': '1.0.2'});` it appears to be working now. Apologies for the false alarm.

**Comment by stubailo** [comment]
Interesting, thanks! Curious what the fix was - `meteor reset` or similar?

**Comment by mattpolicastro** [comment]
Just edited my comment, but I did a full removal/reinstall of Meteor, as well as transposing all my app files into a new project. My system's been having other issues, so it may have just been some trickle-down from that. Again, apologies for the false alarm.

**Comment by stubailo** [comment]
OK, let me know if you get more info.

**Comment by mattpolicastro** [comment]
I'll try to scrape together the logs when I have a moment.
