### ISSUE TITLE
feature request: avoid _debug output and allow to extend msg.msg by custom_msgs

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4297]
Hi, hopefully this is a valid request, I`d like to ask for:

When writing packages like [YuukanOO:Streamy](https://github.com/YuukanOO/streamy) which are using Meteors Connection object, it is nasty, that those custom messages appers as "unknown livedata messages" on the debug console. One option would be to override `Meteor._debug` but this not a preferred one in my point of view.

All is based at:

https://github.com/meteor/meteor/blob/c0aab1e8d3a5f01b4bedaa1c63dea3fc8f3db9b7/packages/ddp/livedata_connection.js#L259

where `Meteor._debug` is called when `msg.msg` does not match as a known msg. 

Wouldn't it be easy and possible, to extend the `options` argument with an additional list element of valid custom msg identifiers.

https://github.com/meteor/meteor/blob/c0aab1e8d3a5f01b4bedaa1c63dea3fc8f3db9b7/packages/ddp/livedata_connection.js#L27

So then instead just calling `Meteor._debug` add one `if clause` at the end like:

````
--- else
+++ else if (! _.include(options.custom_msgs, msg.msg))
      Meteor._debug("discarding unknown livedata message type", msg);
````

If this fits in your mind and does not break your concepts, I could start to work for a feature pull request.

Thanks for attention
Tom

**Comment by benjamn** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Often the best path to adding a new feature to Meteor is to try [implementing it as a package](http://docs.meteor.com/#/full/writingpackages). In this case, while you're right that overriding `Meteor._debug` feels strange in app code, that might be a fine way of implementing the feature in package code. If the package is useful to lots of people and would benefit from becoming part of the core, we may consider integrating it into the core.

**Comment by TomFreudenberg** [comment]
Hi Ben, thanks for feedback. 

Do you think, that it would be possible to append this feature as a package? I have no idea yet how to inject the additional `if clause` at the right place other than overriding the `.debug` or hacking core file.

Are you able to give me a short hint?

Thanks, Tom
