### ISSUE TITLE
Folder with partial name loaded AFTER folder with full name except when using a dash?

### ISSUE THREAD

**Issue by dalgard** [meteor/meteor#4300]
I seemed to be having some problems with load order, so I tested it by placing a file (`test.js`) in each folder containing only the line `console.log("<folder name>")` – here sorted by the OS:

- /modules/**myproj**/test.js
- /modules/**myproj-accounts**/test.js
- /modules/**myproj-app**/test.js
- /modules/**myproj-app-accounts**/test.js

To my great chagrin, this was the output in both server and browser console:

```
myproj-accounts
myproj-app-accounts
myproj-app
myproj
```

However, if I append a dash/hyphen to the two names that are moving place:

- /modules/**myproj-**/test.js
- /modules/**myproj-accounts**/test.js
- /modules/**myproj-app-**/test.js
- /modules/**myproj-app-accounts**/test.js

... it gives the expected result:

```
myproj
myproj-accounts
myproj-app
myproj-app-accounts
```

What gives???

I'm running OS X 10.9.5.

**Comment by benjamn** [comment]
I was able to reproduce this bug, and I hope to have a fix soon!

**Comment by dalgard** [comment]
Fantastic! I thought I was missing something.

**Comment by benjamn** [comment]
The root cause is that `-` comes before `/` alphabetically, so I think we should be splitting on `/` and comparing each pair of path components individually.

**Comment by dalgard** [comment]
Wouldn't it be enough to replace `/` with a character that is sure to come before all other legal file system characers, i.e. anything before 0x0a, roughly?
