### ISSUE TITLE
Reproduction for #4286

### ISSUE THREAD

**Issue by lzl** [meteor/meteor#4301]
#4286 is closed and can't be reopened by myself. I open this new one just for your attention. If it's not OK, please show me a better way.

Here is my reproduction: https://github.com/lzl/meteor-issue-4286

At `/meteor-issue-4286-server`, I run `meteor`. It's `localhost:3000` server at browser.

At `/meteor-issue-4286-client`, I run `meteor --port 4000`. It's `localhost:4000` client at browser.

I create an account with `accounts-ui` at server, then log in that account at client. What I want is that the `accounts-ui` show me it has got me logged in to the server's accounts from the client. But it shows nothing. At browser's console, both server and client's localstorages have `Meteor.loginToken`, `Meteor.loginTokenExpires` and the same `Meteor.userId`. But when I refresh the client page, all of them will be gone.

If I uncommented `Meteor.users = new Mongo.Collection("users", {connection: connection});` of the client. The `accounts-ui` will show me I have logged in, but has the same problem as I refresh the page.

I'm not sure it's a bug or not. I think I'm lack of the knowledge about `Accounts` and `DDP` of Meteor to resolve this problem. Please show me the way. Thank you.

**Comment by benjamn** [comment]
Reassigning `Accounts.connection` is probably not going to do what you want, since the original object continues to be used elsewhere in the various accounts packages.

You may be interested to know that we ware currently working on a way to support multiple instances of the `Accounts` object: https://github.com/meteor/meteor/pull/4233. Once those changes are released, I think you'll find it a lot easier to create multiple accounts-related DDP connections.

**Comment by lzl** [comment]
I see. Then before #4233 is merged, is there a way to set `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` by myself? @benjamn

**Comment by benjamn** [comment]
Yep, setting that property will work, just put it in `client/lib/accounts.js` so it loads before your other code.

**Comment by lzl** [comment]
I tried, but failed. The problem is `client/lib/accounts.js` still loads after `/packages/accounts-base.js`.

I forked `accounts-base` package then put it into my `packages` folder, changed `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` manually. It works perfect.

In production. I don't want to fork that core package. Is there a better way to resolve this issue?
