### ISSUE TITLE
rawCollection isn't present in the docs.

### ISSUE THREAD

**Issue by mariorodriguespt** [meteor/meteor#4304]

**Comment by benjamn** [comment]
@glasser Looking at https://github.com/meteor/meteor/issues/3640, I can't tell if `rawCollection` was intended to be a public API. Thoughts?

**Comment by rclai** [comment]
I've been using it a lot please don't make it inaccessible.

**Comment by mariorodriguespt** [comment]
Me too, keep it public.

**Comment by keyscores** [comment]
I think lots of people are using rawCollection as a work-around for mongo aggregation support. See here: https://github.com/meteor/meteor/issues/4947

**Comment by hwillson** [comment]
`rawCollection` is mentioned in the docs [here](https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection). Closing - thanks!
