### ISSUE TITLE
Is there a way to get fields of removed document in observeChanges?

### ISSUE THREAD

**Issue by vuhpham** [meteor/meteor#4306]
Hi all,

Is there a way to get fields of removed document in observeChanges?
I can get only id here:
http://docs.meteor.com/#/full/observe_changes

**Comment by ekatek** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker Good luck!

**Comment by Slava** [comment]
@vuhpham the answer is to use the `.observe` API instead of `.observeChanges`. It returns the whole deleted document.

**Comment by vuhpham** [comment]
@Slava @ekatek My bad, I coudn't figure out at that time :-) Thanks
