### ISSUE TITLE
SQL support

### ISSUE THREAD

**Issue by vchigne** [meteor/meteor#4309]
AFAICS, the most requested single feature for Meteor is native PGSQL or MYSQL support. There are some packages (numtel, meteorsteam) for this but they are not native, so they miss critical features and can be broken in next meteor versions, so my questions are: Will meteor support some SQL in the near future ie 6 months from now? Is somebody in the team working on it? If so, wich platform will be selected, MySql, PGSql, generic SQL?

**Comment by glasser** [comment]
Thanks for the suggestion. This is a major project that is being tracked on the [roadmap](https://trello.com/c/Gf6YxFp2/42-sql-support), not in the issue tracker.

We are planning to update our roadmap relatively soon.  I expect SQL to be on it as a high priority, but wait and see!

**Comment by peppeliquid** [comment]
I glasser,
Any news about MySQL support?
thanks for you feedback.
