### ISSUE TITLE
high cpu usage when running meteor from npm scripts block

### ISSUE THREAD

**Issue by dferber90** [meteor/meteor#4314]
**_9 Upvotes**_ ## Summary
When running Meteor from npm's scripts-block a node process eats >100% CPU.
## Details

There is a nice way of using npm's `package.json` file to save characters when starting Meteor with lots of options for development. Described in detail [here](http://blog.differential.com/use-package-json-in-your-meteor-app-for-fun-profit/),

Basically, Meteor can be started with `$ npm start` by including a file (called `package.json`) like the one below in the Meteor app.

``` json
{
  "name": "todos",
  "scripts": {
    "start": "meteor run"
  },
  "private": true
}
```

When running Meteor with `$ npm start` everything works as usual. But after letting it run for about 1,5minutes, the fans on my MacBook Pro go crazy. The cause of this is that a node process takes up more than 100% CPU and nearly 200M memory.
## Reproduction

The reproduction repository contains the plain todos example. I only added a `package.json` file.

```
$ git clone git@github.com:dferber90/meteor-npm-issue.git
$ cd meteor-npm-issue
$ npm start

# now, view %CPU and MEM of a node process in a new terminal tab
$ top
```

When running the same app with the plain old `$ meteor run` command instead of `$ npm start`, everything works fine. I am not sure what is causing this.

**Comment by ekatek** [comment]
This is kind of cool -- I have never running meteor through npm before. Thanks for reporting! Tool performance is an ongoing project for us, so while we might not concentrate on debugging this explicitly in the near future (because running with `meteor run` works fine), it is great to keep it in mind.

**Comment by TimFletcher** [comment]
I'm running into this issue too. My meteor app requires that I run a couple of other node processes at the same time so I just threw them all in as npm scripts so can just do `npm start` and run them all. Guess I'll have to find another way to run them all. Foreman, perhaps.

**Comment by ShockiTV** [comment]
+1 seems we have to maintain bash script for now

**Comment by Alino** [comment]
+1

simple ```meteor run``` is not enough for people who are doing more complicated projects where you need to start the whole environment with a single command

wee need to start meteor with a ton of other scripts and commands bundled into one ```npm start``` script

**Comment by ShockiTV** [comment]
As mentioned in that linked Webpack meteor React topic, you can create it this way

My start.js
```
#!/usr/bin/env node

var spawn = require('child_process').spawn;
//var appDir = process.cwd();
var execEnv = process.env;
var envDup = {};
var someVar;

//process.chdir(appDir + '/app');

for (someVar in execEnv) {
    envDup[someVar] = execEnv[someVar];
}
envDup["MONGO_URL"] = 'YOUR_MONGO_URL';

var options = {
    env: envDup
};

var m = spawn('meteor', ['--settings', 'YOUR_SETTINGS_JSON', '--port', '3000'], options);

m.on('exit', function() {
    console.log('exiting as child died');
    process.exit();
});

m.stdout.on('data', function (data) {
    console.log("m:"+data);
});

process.on( "SIGINT", function() {
    m.kill("SIGINT");
    console.log('killing child');
} );
```
And than run it as `npm run start`
package.json:
```
{
  "name": "myApp",
  "scripts": {
    "start": "node start.js",
  }
}
```

Problem seems to be with the stdio pipes.
As soon as I switch to `stdio: inherit` in options, it eats 170% of my 4core and never drops.
Also you can notice that this working (no additional CPU consumption) stream listening way there is missing quite noticeable part of standard meteor run output normally visible if u run it directly.
You can add displaying errors using this style too:
```
child.stderr.on('data',
    function (data) {
        console.log('err data: ' + data);
    }
);
```

So maybe if Meteor just outputs on console better way, it can stop ruining CPU during standard usage.
Have fun

**Comment by Alino** [comment]
This brings unnecessary complexity, we've got a start shell script where we got already everything and now we have to run another start javascript  which starts meteor.

**Comment by ShockiTV** [comment]
I think the old ( using by Meteor internally ) and new ( installed by devs locally ) Node streams cooperation is kinda borked.
Simple nvm-ing to 0.10.40 node version bring both on same level and fixed CPU issues.
Have fun and thanks for all the fishes.

**Comment by ShockiTV** [comment]
I think the old ( using by Meteor internally ) and new ( installed by devs locally ) Node streams cooperation is kinda borked.
Simple nvm-ing to 0.10.40 node version bring both on same level and fixed CPU issues.
Have fun and thanks for all the fishes.

**Comment by ShockiTV** [comment]
As we need to run also chimp and I would prefer still use current npm by default and not switch by hand so I prepared little wrapper for brew installed nvm on my OSX.

Roberts-MacBook-Pro:~ shock$ cat .bash_profile 
```
export NVM_DIR=~/.nvm
. /usr/local/opt/nvm/nvm.sh
alias npm="~/.npm_wrapper.sh"
```

Roberts-MacBook-Pro:~ shock$ cat .npm_wrapper.sh 
```
#!/bin/bash

readonly METEOR_NODE_VERSION="0.10.40"

# source nvm script installed by brew
. /usr/local/opt/nvm/nvm.sh

if [[ "$1" == "run" && ( "$2" == "start" || "$2" == "testEnv" ) ]]
then
  echo "Using npm for $METEOR_NODE_VERSION"
  nodePath=$(nvm which $METEOR_NODE_VERSION)
  npmPath=$(echo $nodePath | sed 's/node$/npm/')
  exec "$npmPath" $@
else
  # exec with current node
  nodePath=$(nvm which system)
  npmPath=$(echo $nodePath | sed 's/node$/npm/')
  exec "$npmPath" $@
fi

echo "Something went horribly wrong in npm_wrapper.sh"
```
Bye

**Comment by camstuart** [comment]
+1 Same issue here. My macbook fans go crazy when i run `npm start` I think having this as a standard way of launching meteor apps is ideal. No matter the project a developer should be able to clone, cd into the directory and run the app in a standard way. Then the projects `package.json` can control what happens next.

My only wish is that npm script accepted an array of commands like this:
```
"scripts": {
    "start": [
       "echo 'loading git packages'",
       "mgp"
       "echo 'launching application'",
       "meteor --settings settings-development.json"
   ]
  }
```
Instead of what I am currently doing:
```
"scripts": {
    "start": "echo 'loading git packages'; mgp; echo 'launching application'; meteor --settings settings-development.json"
  }
```

But otherwise, I'm all for this approach.

**Comment by svda** [comment]
+1

**Comment by zimt28** [comment]
+1. The current beta creates a `package.js` file with the start script, so it should be fixed before the `1.3` release.

**Comment by chmac** [comment]
We're seeing this on several of our team's and client's machines on OSX. Would be great to get a fix or a workaround...

**Comment by bitsuns** [comment]
+1

meteor: 1.3-beta.16
node: v4.4.0
npm: 2.14.20

**Comment by BlooJeans** [comment]
+1

**Comment by nadeemja** [comment]
+1

**Comment by st3phan** [comment]
+1

**Comment by krstffr** [comment]
This is still true post the 1.3 official release. 

Also true if you run your tests using `npm test` (and make it run the new `meteor test` command).

**Comment by Alino** [comment]
Guys, if you are on Meteor 1.3
**maybe you could try** `meteor npm start` or something like that.
I have read some news that you can use npm in meteor cli now.

I haven't migrated to meteor 1.3 yet, so I have no experience with this, but it might solve the issue, if npm runs from meteor process. Please could someone confirm this?

**Comment by camstuart** [comment]
After chatting to people on slack and in some meet up's, it seems the general opinion is that this is an issue with the very old node version that ships with Meteor. In the "What’s up next?" section of the 1.3 release announcement (http://hubs.ly/H02w6gg0), they mention node is getting updated next. So even though Meteor itself has been updated, node remains on the same version. So no improvement on this issue. I tried updating my node version only to realise that the node that underlies Meteor has nothing to with my own version of node... oops.

**Comment by krstffr** [comment]
@Alino even if that works it's still a workaround, and not the standard way of running things.

The point of using `npm start` is that everyone know how to do it, and it should not add a 170% increase in CPU load.

**Comment by Alino** [comment]
good to know that it works!
You are right that it is not standard thing to run things but yet It is acceptable and simple workaround in my opinion. At least something. :)

**Comment by Sanjo** [comment]
Using `meteor npm start` instead of `npm start` solves this issue for me.

I have the following versions installed:
* Meteor: 1.3
* Node.js: v4.4.1
* NPM: 2.14.20

**Comment by jbaxleyiii** [comment]
@benjamn do you have any idea why this is happening?

**Comment by hwillson** [comment]
This isn't happening when calling `meteor npm ...` (see https://github.com/meteor/meteor/issues/4314#issuecomment-211241868), which is the recommended way of using the npm CLI with Meteor. Given this, and the age of this issue, I'll close it off. Happy to re-open if anyone notices this happening with a current version of Meteor. Thanks for posting this originally!
