### ISSUE TITLE
ReactiveDict stores Boolean values as String

### ISSUE THREAD

**Issue by cneuro** [meteor/meteor#4315]
Is this intended? (Just wanna make sure before deploying a reproduction recipe).

Using meteor 1.1.02, reactive-dict 1.1.0, Chrome 42.0.2311.135 (64-bit), OS X 10.10.2

```javascript
var test = new ReactiveDict();
test.set('foo', true);
test.set('bar', false);
console.log(test);
```
Output:

![screen shot 2015-05-02 at 16 40 34](https://cloud.githubusercontent.com/assets/2691584/7441671/1cd0f240-f0ea-11e4-87bf-f078c2d2d2e9.png)

Thanks.

**Comment by Slava** [comment]
This is not a bug, but an implementation detail.

You inspected an internal data structure of a ReactiveDict instance. If you run `dict.get('bar')`, you will get a parsed boolean.
