### ISSUE TITLE
Windows compiler is 2 times slower than on Mac

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4317]
This includes building the app, server restarts and client refreshes.
Could be nothing of importance, but when you add a package which by itself increases total build time this really becomes a problem.
Like in this case https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/8

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
