### ISSUE TITLE
meteor 1.1.0.2 on Ubuntu gives: "Unexpected mongo exit code 1. Restarting."

### ISSUE THREAD

**Issue by etangreal** [meteor/meteor#4318]
Hi, I'm getting this "Unexpected mongo exit code 1. Restarting."

Runtime:
- Ubuntu 14.04 (running on my mac via vagrant & virtualbox) 
- meteor version 1.1.0.2

Instructions:
- vagrant init ubuntu/trusty64
- vagrant up
- vagrant ssh
- curl https://install.meteor.com/ | sh
- meteor create test
- cd test
- meteor update
- meteor --version (shows: 1.1.0.2)
- meteor

After which I get this "Unexpected mongo exit code 1. Restarting."

**Comment by liamreoch** [comment]
Can confirm this - am experiencing it on same system (Ubuntu 14.04) with same meteor version (1.1.0.2).

**Comment by liamreoch** [comment]
Installing node.js via apt-get seemed to fix this for me.

**Comment by etangreal** [comment]
Hi @liamreoch,

Are you sure it was after installing nodejs? I tried:
  - sudo apt-get update
  - sudo apt-get install -y nodejs
(before the step to install meteor)
and I still get "Unexpected mongo exit code 1. Restarting."

It seems unlikely that installing node.js will fix the mongodb issue ...

**Comment by ekatek** [comment]
Huh. I just followed your instructions exactly, and I can't reproduce the issue. (ie: meteor just runs fine for me, vagrant ubuntu on a mac). Maybe it is a vagrant issue with memory or somesuch? 
Leaving this open -- when @glasser gets back from vacation, he might understand this better than I do.

**Comment by etangreal** [comment]
Hi @ekatek 

Thanks for the reply. 
Yeah, then it must be something specific on my system :/ strange... 
I've have a look into your suggestion  - virtualbox memory or hardrive perhaps

**Comment by etangreal** [comment]
Hi @ekatek 

I just tried:
  - booting the VM normally with virtualbox 
  - logging in through the virtualbox console (the one it pops up when the VM boots)
  - logging in as user: vagrant | pass: vagrant
now when i run the meteor application - everything works!

So its a vagrant issue :/ ... (no idea why tho)
I'm closing this thread - since its not related meteor...

**Comment by etangreal** [comment]
I found the solution (no idea why this works tho), do the following:
  - export LC_ALL=C
  - meteor

must be something about vagrant that does not correctly initialise the environment?
