### ISSUE TITLE
Add HTTP/2 support to server [$100]

### ISSUE THREAD

**Issue by marxo** [meteor/meteor#4319]
**_2 Upvotes**_ HTTP/2 protocol is coming, and serving HTTP/2 with a Meteor app would be awesome.

There's a Node.js implementation for h-16 draft: https://github.com/molnarg/node-http2

Giving the user the ability to use HTTP/2 would immensely speed up applications, allow the requests to be reused better and lessen the need for sharding.

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=12972432)](https://www.bountysource.com/issues/12972432-add-http-2-support-to-server?utm_source=12972432&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by ekatek** [comment]
Good call, and thank you for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by marxo** [comment]
The Graduate has added a bounty of $100 to this issue.

**Comment by dandv** [comment]
One HTTP/1.x anti-pattern that HTTP/2 solves is concatenation (more in [this presentation](https://youtu.be/yURLTwZ3ehk?t=1498)). Meteor could consider a mechanism to skip concatenation and only minify resources.

The talk only mentions the problem of cache invalidation when only one byte in the whole concatenated app.js/css changes and triggers fetching the entire resource. Does HCP optimize this already?

**Comment by PEM--** [comment]
:+1: Strategic feature request.

**Comment by danlg** [comment]
I vote in favor of HTTP/2 in meteor

**Comment by ChrisCinelli** [comment]
HTTP/2 as been out for a while. Back in February, Firefox was getting more transactions though HTTP/2 than through SPDY. At the end of May [45% of the connections in Chrome were made through HTTP/2](https://docs.google.com/presentation/d/1r7QXGYOLCh4fcUq0jDdDwKJWNqWK1o4xMtYpKZCJYjM/present?slide=id.g518e3c87f_0_19). 

The current way to add HTTPS in general to Meteor is by adding a reverse proxy in front of Meteor. Since [nginx](http://wiki.nginx.org/Main)'s [support for HTTP/2 targets the end of 2015](https://www.nginx.com/blog/how-nginx-plans-to-support-http2/), you may want to use [nghttp2](https://nghttp2.org) or in case you are looking for the edge you may try [H2O](https://h2o.examp1e.net/).
The https://atmospherejs.com/meteor/force-ssl package will make the rest. 

However I do agree that it would be nice to have a "native" support for HTTP/2 or at least throught a package. 

The node-HTTP2 module mentioned above has some [performance issues](https://github.com/molnarg/node-http2/issues/98) but https://github.com/indutny/node-spdy is awesome and currently support HTTP/2.

I wonder how easy would be to expose a hook to use your own server module instead of just supporting the native node.js http.

**Comment by denim2x** [comment]
I could try porting [node-spdy](https://www.npmjs.com/package/spdy) to Meteor, given enough [motivation](https://www.bountysource.com/issues/12972432-add-http-2-support-to-server).

**Comment by thatjuan** [comment]
Does nginx allow proxying http/2 connections to http/1 targets? And, would doing that not defeat the purpose of http/2?

Also, this video is an excellent primer on http/2 https://www.youtube.com/watch?v=yURLTwZ3ehk

**Comment by dandv** [comment]
A year later, it would be really great to consider prioritizing native HTTP/2 + Server Push support.

This [Google I/O 2016 talk](https://youtu.be/J4i0xJnQUzU?t=1839) showcases some important advantages of using HTTP/2 with server push:

* Resource bundling no longer necessary.
* Resources can be named individually, which means the browser can cache them.
* Hot Code Push can be much faster - only the changed resources will be sent.
* On the first visit, only the required resources need to be sent to the client. This solves [Incremental loading](https://trello.com/c/24s6vyxo/55-incremental-loading), one of the top requested features in the Meteor roadmap.

Combined with [Service Worker support](https://github.com/meteor/meteor/issues/5982), this would enable the so-called [PRPL Pattern](https://youtu.be/J4i0xJnQUzU?t=2049) (push, render, pre-cache, lazy load) and modern Progressive Web Apps:

* *Push* components for the initial route ![image](https://cloud.githubusercontent.com/assets/33569/15661389/cee78f06-269b-11e6-924d-33ac73d91c17.png)
* *Render* the initial route ASAP 
![image](https://cloud.githubusercontent.com/assets/33569/15661424/1ff3687a-269c-11e6-9d71-dbd8718359c3.png)

* *Pre-cache* components for the remaining routes
* *Lazy-load* and create the next routes on-demand

-------

This *will* require some significant changes to the Meteor internals, but this is the direction the web is moving towards.

![image](https://cloud.githubusercontent.com/assets/33569/15661479/9880c67a-269c-11e6-9f05-8c1355afa199.png)

**Comment by NitroBAY** [comment]
+1 for http/2 ... I hope it's the main priority (with service workers) :+1:

**Comment by nick-gudumac** [comment]
+1

**Comment by aliogaili** [comment]
+1

**Comment by HintikkaKimmo** [comment]
+1

**Comment by Ajedi32** [comment]
Guys, please stop with the +1s. They're basically just noise and contribute nothing to the conversation.

If you want to show your support for this issue, click the thumbs up button on [the original post](https://github.com/meteor/meteor/issues/4319#issue-72861390) above, or [contibute to the bounty](https://www.bountysource.com/issues/12972432-add-http-2-support-to-server).

If you want to subscribe to this issue, there's a button for that over on the right.

**Comment by HintikkaKimmo** [comment]
Fair enough @Ajedi32 . Its just a feature I would like to see but have no idea how to implement in general level. 
I have managed to use CloudFlare to serve Meteor app with HTTP2. Why CloudFlare worked where other CDN's did not was you get few things. SLL for free, Websocket support (In Meteor Contects this is like superfast private TSL/SSL connection for DDR updates) . This did not however manage cache my full application for reasons I am not complety sure at this stage... 
With [Railgun](https://www.cloudflare.com/railgun/l) installation solution serves the whole app with HTTP2 maybe. I have not tried that as Railgun only comes with the 200$ month CloudFlare business package. Might do so in the future and in that case will definitely make a blog post how to set this up.

**Comment by mitar** [comment]
BTW, this is the second most upvoted issue for Meteor.

**Comment by alfredjkwak** [comment]
I am a bit interested on this one, checked last Sunday the spots in code that would need a change, and I think it might not be that hard like @ChrisCinelli mentioned.
> I wonder how easy would be to expose a hook to use your own server module instead of just supporting the native node.js http.

Would be nice to make contribution for Meteor, as I would now have some time to do it.

**Comment by mitar** [comment]
Maybe "a hook" could be socket support: #7392

**Comment by alfredjkwak** [comment]
@mitar yep, hmh, that's probably nicer issue to start understanding platform better for contributions. I take a look at "pull-requests-encouraged" labelled stuff :)

**Comment by krishaamer** [comment]
Wow @dandv, Meteor has always been on the bleeding edge of web tech. I hope DMG can keep up and make this a reality!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20HTTP%2F2%20support%20to%20server%20%5B%24100%5D&body=Migrated%20from:%20meteor/meteor%234319) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
