### ISSUE TITLE
Refresh and restart performance severely degraded if many .less files are present

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4320]
After adding https://atmospherejs.com/semantic/ui package which includes a couple of dozens ```less``` files I've found out that app refresh and restart processes are IMO 5-10 times longer than before.
Together with the package author we've concluded that perf degradation is due to ```less``` files being recompiled on each refresh\restart, even though the changes invoking the refresh are made to other files, ie index.html - https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/8
So, the question is: is it possible to recompile only the files that **need recompilation**, eg only the modified ```.less``` files in this case, and not all of them?

**Comment by Slava** [comment]
When you add a package from Atmosphere in the latest Meteor 1.1, the packages are not rebuilt on every run (unless they are local packages). So I don't see how it would affect the build time. We usually require a reproduction with clear steps demonstrating the issue. Provide a list of steps to observe the slowdown after adding the package (including what files needs to be edited), otherwise we wouldn't be able to debug the problem.

**Comment by avalanche1** [comment]
Ok, so here is a clean repo with lagging build process.https://github.com/avalanche1/less-test
Remove *less* package and you'll see that perf is back to normal.

**Comment by Slava** [comment]
In your demo you are not using the package, you copied files into your app. Why do you expect it not to take a lot of time on rebuilds?

**Comment by avalanche1** [comment]
Well, yes - I'm only using the files, without the package for the cleanliness of the experiment. To abstract away from any overhead the package might be causing.
And I expect them not to take lots of time, because .less files are not changed - so why recompile them to css?
I understand that it might be necessary in production deployment, when Meteor minifies everything into a single css file - but why recompile everything in devel?

**Comment by avalanche1** [comment]
So... shall we do smth about it?

**Comment by Slava** [comment]
We definitely should make it faster by caching more information! The work on this is in progress. There are other open issues where we are tracking this: https://github.com/meteor/meteor/labels/Project%3AIsobuild%3APerformance

**Comment by joryphillips** [comment]
I am happy to hear something might be done about this... I'm developing with Semantic UI as well and rebuilds are excruciatingly slow.

**Comment by glasser** [comment]
Allowing build outputs to be cached at a finer level is a major goal of the current work at https://quip.com/YLcCAxtjuwsL

**Comment by avalanche1** [comment]
@glasser nice! Waiting eagerly for the Implementation plan points 2&3)
