### ISSUE TITLE
Unable to run the example in the tutorial

### ISSUE THREAD

**Issue by johnsamuelwrites** [meteor/meteor#4321]
Reference: https://www.meteor.com/try/3
Unable to find a solution, getting the following error

$ meteor mongo
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start your application first. (This error will
also occur if you asked Meteor to use a different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with 'meteor deploy', specify your site's name with
this command.

**Comment by johnsamuelwrites** [comment]
After updating to the latest version,  it's no longer an issue (https://github.com/meteor/meteor/issues/4124)

**Comment by BrunoAndrade** [comment]
I'm running Mac OS X 10.10.4, installed Meteor 1.1.0.3 and I'm facing the same problem.

Wasn't it solved on Meteor 1.1.0.2?

**Comment by sjmcdowall** [comment]
I've tried this on my app with 10.10.4 with no issue 

What exactly are you seeing ? 

Is this due to deploy on meteor.com   Or local meteor ?

**Comment by BrunoAndrade** [comment]
I'm new to meteor, so I was giving a look a meteor tutorial and running it locally.
Basically, I simple follow the steps on the meteor tutorial.

Executed 'meteor', locally, and this was the output:
```
=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          
=> App running at: http://localhost:3000/
```

In another shell, I try to execute 'meteor mongo'. The output:
```
mongo: Meteor isn't running a local MongoDB server.
This command only works while Meteor is running your application locally. Start your application first. (This error will also occur if you asked Meteor to use a different
MongoDB server with $MONGO_URL when you ran your application.)
If you're trying to connect to the database of an app you deployed with 'meteor deploy', specify your site's name with this command.
```

**Comment by sjmcdowall** [comment]
I hate to ask an obvious question but -- are you sure you did a CD to your meteor project before doing the meteor mongo command? 

Also I assume you can access the app via a browser @ localhost:3000 ? 

What version meteor ?

**Comment by BrunoAndrade** [comment]
Yes, I was inside de app directory.
Yes, I can access the app via localhost:3000
Meteor 1.1.0.3

**Comment by BrunoAndrade** [comment]
I was able to use this workaround to continue the tutorial:
https://forums.meteor.com/t/cannot-run-meteor-mongo-2015-04-16/3091

But I still can't use 'meteor mongo' command.

2015-08-15 9:25 GMT+01:00 Bruno Andrade <bruno90@gmail.com>:

> Yes, I was inside de app directory.
> Yes, I can access the app via localhost:3000
> Meteor 1.1.0.3
> On 15 Aug 2015 02:16, "S McDowall" <notifications@github.com> wrote:
>
>> I hate to ask an obvious question but -- are you sure you did a CD to
>> your meteor project before doing the meteor mongo command?
>>
>> Also I assume you can access the app via a browser @ localhost:3000 ?
>>
>> What version meteor ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/meteor/meteor/issues/4321#issuecomment-131276049>.
>>
>


-- 
Bruno Andrade
Licenciado em Engenharia Informática (UMinho)
Estudante de Mestrado em Engenharia Informática (Uminho)

Contactos:
> Página pessoal <http://www.brunoandrade.pt>
> LinkedIn <http://pt.linkedin.com/in/brunompandrade>

**Comment by stubailo** [comment]
@BrunoAndrade does it still not work for you by default in the latest version of Meteor (1.1.0.3)?

**Comment by sjmcdowall** [comment]
How exactly did you install Meteor?  I just tried mine and it works just fine.  Where is your meteor binary?  I.e. when you do "which meteor" where is it and what does it look like?

**Comment by BrunoAndrade** [comment]
@stubailo I had the 1.1.0.3 version of Meteor, and don't work by default.

To install I follow exactly like is told on tutorial, executed 'curl https://install.meteor.com/ | sh'
'which meteor' outputs '/usr/local/bin/meteor', and /usr/local/bin is on PATH variable.

**Comment by dwhu** [comment]
Is there any update on this issue?  I am having the same problem as well.

**Comment by mohessaid** [comment]
I am having the same problem now, with version 1.2.1, I am in the app directory and I installed it using the commands from the documentation. "which meteor" shows /usr/local/bin/meteor
