### ISSUE TITLE
Email package should allow changing SMTP settings

### ISSUE THREAD

**Issue by blazarus** [meteor/meteor#4323]
In my application SMTP is configured by the user in the UI. As a result, they also need to be able to update the configuration from the UI, but today this is not possible. The email package creates a connection pool only once, regardless of whether the `MAIL_URL` environment variable is later changed. In email.js we have:
```
var getPool = _.once(function () {
  // We delay this check until the first call to Email.send, in case someone
  // set process.env.MAIL_URL in startup code.
  var url = process.env.MAIL_URL;
  if (! url)
    return null;
  return makePool(url);
});
```

It would be great if there were some way to update the SMTP configuration while the application is running, either by checking whether the environment variable has changed before sending an email (and creating a new pool if it has), or exposing some hook so the application can manually let the email package know the environment variable has changed.

**Comment by ekatek** [comment]
Thanks for the feature request! I agree that this would be useful. We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by sotarules** [comment]
I've run into the same issue, I have a case where I have a table of SMTP servers that must be used dynamically, but no way to change MAIL_URL after the first invocation.

**Comment by marceloschmidt** [comment]
We have that same problem in [Rocket.Chat](https://demo.rocket.chat), where the server admin may change the SMTP settings. Would you accept a PR for this one?
