### ISSUE TITLE
Command-line tool API for packages

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4324]
**_1 Upvote**_ Is there any way of extending the meteor CLI through a package? 

I've worked on a few projects now that present some common use cases. (1) Compiling icons, splash screens, and other static assets. (2) Starting and stopping databases (other than mongodb). (3) Starting and stopping multiple meteor micro services that work together.

Its a little in convenient to have to enter many shell commands to get your environment up and running, and I think allowing packages to handle this would be awesome.

I think something as simple as `CLI.onStart` and `CLI.onStop` would be a great start!

**Comment by ekatek** [comment]
Thanks for the feature request! This is something that has come up multiple times, and would be kind of cool (but is not currently supported). It sounds like maybe bash scripting might be able to help solve some of your issues (stopping and starting multiple services, databases, etc)  at least for now.

We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by rissem** [comment]
:+1:

**Comment by Slava** [comment]
Related: https://github.com/meteor/meteor/pull/2718

**Comment by rissem** [comment]
Also: https://github.com/MeteorCommunity/discussions/issues/9

**Comment by ccorcos** [comment]
Ah yes. Both of those places! Not sure where we should keep this then.

Also, I was thinking `CLI.onReset` would be nice too.

**Comment by ccorcos** [comment]
Hey, any thoughts on this? I just built a simple commandline tool which sets up a Neo4j database for a meteor project.

https://github.com/ccorcos/meteor-neo4j

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Command-line%20tool%20API%20for%20packages&body=Migrated%20from:%20meteor/meteor%234324) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
