### ISSUE TITLE
HTTP.call() auth password can't contain commas or full stops

### ISSUE THREAD

**Issue by moigagoo** [meteor/meteor#4325]
I have two identical endpoints running, both protected with basic auth. The password on the first one has both a comma and a full stop, i.e. "admin:password,.", the password on the second one doesn't have them, i.e. "admin:password".

When I make requests to the first one with HTTP.call or HTTP.get, the ECONNREFUSED error is raised. Requesting the second one works just fine.

**Comment by ekatek** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor . How are you making the HTTP.call/HTTP.get call? What does (a minimal version) of the failing app look like? Without a good way to replicate your problem, we can't debug and fix it.
