### ISSUE TITLE
Only the first callback registered with Accounts.onLogin is called on the client

### ISSUE THREAD

**Issue by ErikDakoda** [meteor/meteor#4331]
Please see reproduction of the bug in the following project:

git clone git@github.com:InfloErik/Accounts_onLogin_Bug.git

This is the todos sample application with the addition of a single file: client/Accounts_OnLogin_Bug.js
This file has three separate calls to Accounts.onLogin.

The onLogin callbacks should log to the console:
- Accounts.onLogin 1
- Accounts.onLogin 2
- Accounts.onLogin 3

Steps to reproduce:
1. Click Join and create a new account
2. Sign out and back in
3. Expected: all three console.log statements should be called when user logs in
4. Found: only the first console.log (therefore only the first callback) is called

onLoginHook in accounts-base does have all three callbacks
but "onLoginHooks.each" only executes the first one

**Comment by ekatek** [comment]
Hi, thanks for reporting an issue. We will take a look at your reproduction and try to figure out what is going on.

**Comment by InfloErik** [comment]
I just updated my reproduction project to test the server site as well. I added a second file: server/Accounts_OnLogin_bug.js

I confirmed that on the server side all 3 callback are being called correctly. This bug appears to only be on the client side.

**Comment by otroboe** [comment]
I notified this bug too. 
Multiple callbacks on Client side don't work :(

**Comment by otroboe** [comment]
Close this issue ?
Merged here: https://github.com/meteor/meteor/pull/4774

**Comment by brettle** [comment]
The [brettle:workaround-issue-4331](https://atmospherejs.com/brettle/workaround-issue-4331) package provides a workaround for this issue for anyone using a Meteor release where this isn't fixed.

**Comment by hwillson** [comment]
This functionality was added in https://github.com/meteor/meteor/pull/4774 - closing. Thanks!
