### ISSUE TITLE
Export Code as cordova project

### ISSUE THREAD

**Issue by AhmadEl-Banna** [meteor/meteor#4332]
Ok it may sound weird ,but I think it's gonna be cool ,can you add a cli command that export the code necessary for cordova cli to build for all platforms needed ,and without hot code push.
just export cordova project and let cordova CLI or phonegap build do it's thing 

Thank you

**Comment by Exilz** [comment]
I guess that would be quite useful, especially for adding Crosswalk since it's really hard to do it with Meteor currently.

**Comment by alpjor** [comment]
+1

**Comment by Slava** [comment]
I don't think this would be a useful feature. The Cordova project source is not a good artifact to work with. A better artifact is an ant project or an xcode project that we already export in a `meteor build` command.

If you really want to dig into the generated Cordova project, you can run your app on emulator and then go to the `.meteor/local/cordova-build` directory in your Meteor project.
