### ISSUE TITLE
Consistently Unable to Connect to os.osx.x86_64 Build Farm

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#4333]
Not sure where to log this issue, so feel free to close if it is not appropriate here. But I've been trying for 24 hours to publish my binary meteor package on all 4 supported architectures, and I have been unable to connect to an `os.osx.x86_64` machine every time I've tried (dozens of times). Every other machine works fine, including windows, but not this one. The following command `meteor admin get-machine os.osx.x86_64` always yields:

`Error from build farm: Sorry, no machines available now. Try again later. [try-again-later]`

I keep trying again later, with the same result. What's going on?

**Comment by Sanjo** [comment]
:+1: I have the same issue. Also one week ago and now.

**Comment by joncursi** [comment]
I still have this same problem for `os.osx.x86_64` build machines.

**Comment by glasser** [comment]
@ekatek is looking into this.

**Comment by ekatek** [comment]
Hi all! Thanks for letting us know -- the issue is fixed, and `meteor admin get-machine ox.osx.x86_64` should now work.

**Comment by joncursi** [comment]
:+1: works great now - thanks guys!
