### ISSUE TITLE
Wrapping a dom element (e.g. with Jquery) prevents events from being handled.

### ISSUE THREAD

**Issue by cwohlman** [meteor/meteor#4335]
If some non-meteor code wraps an element at the parent level of your template, events from that element are not handled by your template event handlers.

Reproduction: https://github.com/cwohlman/meteor-dom-range-containsElement-bug

Example:

``` html
<template name="hello">
  <button>Click Me</button>
</template>
```

``` javascript
Template.hello.onRendered(function () {
  $('button').wrap('<div>');
});
Template.hello.events({
  'click button': function () {
    // this handler is never called
  }
});
```

**Comment by cwohlman** [comment]
A workaround is to wrap your template internals in a containing element.

Example:
```html
<template name="hello">
  <div> <!-- this div not needed, but allows you to handle events from the button element
                  even if you later wrap it (the button element)-->
    <button>Click Me</button>
  </div>
</template>

**Comment by Slava** [comment]
This looks like a bug. A lot of jquery manipulations changing the structure (especially touching the top-level element of a template) don't have any specified behavior with Blaze. Note that Blaze attaches extra symbols to the top-level element of a template, so messing with its structure can lead to behaviors like this.

**Comment by cwohlman** [comment]
I actually looked into this a little deeper and it's actually a lot more nuanced than I expected. This is because blaze doesn't actually create any DOM for a template, so the child elements of two sibling inclusion tags share the same DOM parent.

To make things clearer, here's some code:

```html
<!-- Before -->
<div>
  <span>Other span</span>
  <!-- inner template -->
    <!-- 
      Blaze is attached to these two input elements using the $blaze_range
      property.
      -->
    <input name="firstName" type="text">
    <input name="lastName" type="text">
  <!-- /inner template -->
</div>

<!-- After -->
<div>
  <span>Other span</span>
  <!-- inner template ? -->
    <!--
      Blaze is not attached to this span element.

      The question is, how does blaze know whether this span belongs inside of
      inner template, or inside of the outer template (e.g. the template which
      contains the outer div)?
      -->
    <span class="jquery_wrap">
      <input name="firstName" type="text">
    </span>
  <!-- inner template ? -->
    <input name="lastName" type="text">
  <!-- /inner template b-->
</div>
```

I did a little work on this myself, but don't really like the solution of hacking jQuery: https://github.com/cwohlman/meteor/commits/bugfix/domRangeContainsElement

**Comment by mitar** [comment]
Yea, you probably shouldn't use jQuery to directly manipulate the DOM. :-)

If you want, then maybe also use jQuery to attach event handlers?

**Comment by hwillson** [comment]
There are 2 possible workarounds to this issue outlined in this thread (wrapping template internals in a containing element, or using jQuery events directly if using jQuery to manipulate the DOM). Given that there are workarounds, and that this issue is quite old without much traction (no recent work, comments, etc.), as part of the old issue cleanup process we might want to consider closing this issue. If necessary, this issue can always be re-opened in the new [Blaze repo](https://github.com/meteor/blaze). Thanks for originally reporting this issue and providing a reproduction!
