### ISSUE TITLE
Creating Mongo indexes

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4336]
It seems about time to officially support creating Mongo indexes. I've run across `Collection._ensureIndex` and it seems to work. Any reason this isn't in the documentation?

**Comment by glasser** [comment]
As of Meteor 1.0.4, there's direct access to the Mongo driver, so I'd encourage you to just use `c.rawCollection().ensureIndex(...)` instead!

**Comment by ccorcos** [comment]
Oh cool. Thanks! And where is this documented?

http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/

That looks like the mongo shell syntax, not necessarily the node.js driver syntax...

**Comment by rclai** [comment]
[This is what you're looking for](http://mongodb.github.io/node-mongodb-native/api-generated/collection.html)

**Comment by ccorcos** [comment]
There we go, thanks @rclai !
