### ISSUE TITLE
error: No compatible binary build found for this package

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4338]
When attempting to add `percolate:server-info`, which does not contain a binary component (https://github.com/percolatestudio/meteor-server-info/issues/5)

```
me$ meteor --version
Meteor 1.1.0.2
me$ meteor add percolate:server-info
 => Errors while adding packages:             
                                              
While checking for percolate:server-info@0.2.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by glasser** [comment]
`meteor publish` involves running multiple steps; it seems like one of the later steps (publishing a build) must have failed, or the tool crashed between the steps?  @zol You should be able to fix this with `meteor publish-for-arch percolate:server-info@0.2.3`.
