### ISSUE TITLE
[docs] Inconsistent recommendation on underscore usage

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#434]
The naming convention for additional properties seems to be conflicting for invalidation contexts vs. template instance objects:
### Meteor.deps

> Invalidation contexts have an attribute id which is a unique positive integer. You're free to add any other attributes you like to the invalidation context for your own convenience, **as long as they don't start with an underscore.**
### Template instances

> In addition to the properties and functions described below, you can assign additional properties of your choice to the object. Property names **starting with _** are guaranteed to be available for your use.

**Comment by mitar** [comment]
So what is the current recommended practice? Use underscore? Or don't use underscore for developer's properties?

**Comment by glasser** [comment]
The "Property names starting with `_` are guaranteed to be available for your use" text is now gone.  So I would say that's "assign things that don't begin with `_`" (or maybe "any name is fine", I'm not sure).
