### ISSUE TITLE
Unable to delete object inside embedded array with "update $pull"

### ISSUE THREAD

**Issue by v3rron** [meteor/meteor#4342]
Hi,
I'm using Collection2 combined with Simple Schema which looks like this:
````
Schemas.UserProfile = new SimpleSchema({
  links: {
    type: [Schemas.UserLinks],
    optional: true
  },
});

Schemas.UserLinks = new SimpleSchema({
  _id: {
    type: String,
    autoValue: function(){
      return Random.id();
    }
  },
  name: {
    type: String,
    regEx: /^[a-zA-Z -]{2,32}$/,
    optional: true
  },
  url: {
    type: String,
    regEx: SimpleSchema.RegEx.Url,
    index: true,
    unique: true
  }
});
Schemas.User = new SimpleSchema({
  profile: {
    type: Schemas.UserProfile
  },
});
````
(This is not the full Schema of course, I just pointed out the necessary fields).
As you can see, I'm storing embedded array of objects user.profile.links. In the database it looks like this:
````
"profile": {
   "links": [
      {
        "url": "http://facebook.com",
        "_id": "FH9w35pnRRLd2j8nc"
      },
      {
        "url": "http://google.com",
        "_id": "ost9yaWBn6Yr4GWeK"
      }
    ]
}
````
For some weird reason I cannot remove one link from profile.links array. I tried the following:
````
# Client
'click a.delete-link': function(e, tmpl){
    e.preventDefault();
    var _link = {};
    _link['_id'] = this._id;
    Meteor.users.update({_id: Meteor.userId()}, {$pull: {"profile.links": _link}});
}
````
I also tried to pass the whole document like this:
````
# 1st version
'click a.delete-link': function(e, tmpl){
    e.preventDefault();
    var _link = this;
    Meteor.users.update({_id: Meteor.userId()}, {$pull: {"profile.links": _link}});
}
# 2nd version
Meteor.users.update({_id: Meteor.userId()}, {$pull: {profile: {links: _link}}});
````
<b>I also tried all of those options on the server side with Meteor.call but nothing is happening. 
The call always returns success, but the object is not being removed from array.</b>
My guesses are one of these:
1. http://stackoverflow.com/questions/26144405/mongodb-update-pull-always-return-1
2. https://jira.mongodb.org/browse/SERVER-1014
3. <b>_id</b> field shouldn't be a type of <b>String</b> maybe? I tried changing it to <b>Mongo.Collection.ObjectID</b>, but then I can't insert any new links.
4. "unique: true" is not working for <b>url</b> field and now and I am able to insert duplicated urls. Opened an issue: https://github.com/aldeed/meteor-collection2/issues/221

PS: having a separate links collection is not an option, because the data is not redundant
Thanks in advance.

**Comment by v3rron** [comment]
Ok, it was weird but I managed to solve the problem by changing my Schema to:
````
Schemas.UserLinks = new SimpleSchema({
  _id: {
    //type: String,
    //autoValue: function(){
      //return Random.id();
    //}
    type: Mongo.Collection.ObjectID,
    optional: false
  },
  name: {
    type: String,
    regEx: /^[a-zA-Z -]{2,32}$/,
    optional: true
  },
  url: {
    type: String,
    regEx: SimpleSchema.RegEx.Url,
    index: true,
    unique: true
  }
});
````
And providing the ID manually on update:
````
Meteor.users.update(Meteor.userId(), {$push: {"profile.links": { _id: Mongo.Collection.ObjectID(), url: url }}});
````
Also tried to add autoValue like this:
````
_id: {
    type: Mongo.Collection.ObjectID,
    autoValue: function(){
      return new Mongo.Collection.ObjectID();
    }
},
````
but this didn't work by some reason. :/

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Ideally your reproduction would not involve Simple Schema; if it's impossible to reproduce without Simple Schema, then that may mean that it's a bug in that package.

**Comment by Philip-Nunoo** [comment]
I'm having this same issue @v3rron what was your solution

**Comment by v3rron** [comment]
@Philip-Nunoo the solution is in my second comment...

**Comment by cdolek** [comment]
I had the same issue, it was about SimpleSchema and autoValue fn. It returns the id value again even it's a $pull. Hopefully, there is a fix.

       Meteor.yourCollection.update({
            "_id": orderId,
            "activities._id": activityId,
        }, {
            "$pull": {
                activities: {
                    _id: activityId
                }
            }
        },
        // Here is the magic
        {
            getAutoValues: false
        });

**Comment by mdorn** [comment]
Just got bit by this issue too @cdolek -- given that there hasn't been a release of Simple Schema since December 2015, I wouldn't hold my breath for a fix. My solution was similar to that of v3rron, but I used `Random.id()` in my Meteor method instead.

**Comment by raphaelarias** [comment]
omg man, cdolek saved hours here. Very hard to find this very specific info! Thanks mate!

**Comment by juvyc** [comment]
Anyone solved this problem in a proper way? Like .remove method of mongo db? I know it can be fixed through looping and just ignore the match key but that's a weird solution.

**Comment by Louis30** [comment]
On Jan 29, 2017 3:28 PM, "juvyc" <notifications@github.com> wrote:

Anyone solved this problem in a proper way? Like .remove method of mongo
db? I know it can be fixed through looping and just ignore the match key
but that's a weird solution.

—
You are receiving this because you are unsubscribe to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/meteor/meteor/issues/4342#issuecomment-275955238>, or mute
the thread

**Comment by Louis30** [comment]
Unsubscribe
