### ISSUE TITLE
Blaze re-rendering doesn't keep up with keystrokes

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#4343]
Perhaps an addendum to https://github.com/meteor/meteor/issues/3596.

If you bind to a `keyup` event and resultingly re-render, Blaze doesn't keep up with very rapid typing.

Reproduction: https://github.com/tmeasday/blaze-textarea
1. Place the cursor before the X in one of the fields.
2. Type very rapidly.
3. Note that the cursor moves to the end of the field and text appears after the X.

I can attach a video if it's not clear what I mean.

Note that (for instance), React---where re-rendering is the _only_ way to have text appear in a textfield on user input---does not seem to have this problem.

Tested on a late 2014 iMac so I'm guessing that it'll only be easier to reproduce on less powerful computers.

**Comment by stubailo** [comment]
> React---where re-rendering is the only way to have text appear in a textfield on user input

I don't think this is the case? You just have to use `defaultValue` rather than `value` for the prop. In fact, I just wrote an app that does the thing you are describing in React and I'm pretty sure it doesn't always keep up properly unless you throttle the input.

**Comment by tmeasday** [comment]
No you are right about `defaultValue`, I'd forgotten that.

I tried it here on a very simple react app (can you post yours somewhere so I can try it?) and it worked fine. But then maybe my computer is too fast? I'll mess about on mobile.

**Comment by tmeasday** [comment]
Could reproduce in either React or Blaze on my iPhone 6.

**Comment by stubailo** [comment]
Yeah in my app it helped to just put a throttle on the event handler - but
maybe there is a good way to handle this by default.

**Comment by tmeasday** [comment]
@stubailo I see you replied to the email notification but I actually mistyped my comment initially -- I meant to say I *couldn't* reproduce on my mobile for either framework.

**Comment by tmeasday** [comment]
But you are right that throttling is a workaround for this problem--there are problems with that however (we used to do something like this). An example:

The user types their username/password, then quickly hits enter. Because we've throttled the keyup, the submit button is still disabled (it's disabled until you fill out both fields) when the browser gets the submit event and it's cancelled. The user is surprised that they can't submit the form with an enter press.

**Comment by RobertLowe** [comment]
@tmeasday I can confirmed this issue is happening, I had to press 6+ keys down at once for it to skip.

**Comment by murillo128** [comment]
Have you tried to manually doing a Tracker.Flush to force the reactive
changes to take place immediately? It has solved most of the glitches for me

**Comment by saturnaut** [comment]
Not sure how helpful this will be, but ... I had a similar issue happen in an application I am building with Meteor, where I needed input fields updated in real time as a user types into them. Problem is, there is almost a "ghosting" effect that can occur where it seems like the keyup event doesn't fire before the method finishes doing a collection update, resulting in cursor jumps and character loss during rapid typing. Either way, I got around this problem by only reactively changing the value of the input if the user is not focused on that particular field, essentially "locking" the field on focus and "unlocking" it on blur.

**Comment by RobertLowe** [comment]
@murillo128 Great thought, yes, I tested it with: `Tracker.flush` after the ReactiveVar/set and it does resolve the issue. At least we have a partial solution for now.

**Comment by tmeasday** [comment]
@murillo128 - yes, you are correct! A manual flush does do it. Great workaround. 

Of course this can lead to extra unnecessary renderings (e.g. if you have more than on event handler on the `keyup`), it would be better if Tracker somehow could not let the extra events slip through before doing it's own scheduled flush.

**Comment by rclai** [comment]
Are you not able to do `event.stopImmediatePropagation()` to stop the extra events from happening?

**Comment by tmeasday** [comment]
@rclai I think the issue is (somehow, I'm not totally sure how) two key events happening before the relevant flush has a chance to happen. So I'm not sure cancelling the event would solve the problem.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#157; this issue can be closed. Thanks!

**Comment by abernix** [comment]
Thanks, @hwillson :fire:

:smile:
