### ISSUE TITLE
Update Cordova packages on `meteor update`

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4344]
In the same vein as #3789, having better integration with Cordova plugin repository:
- `meteor list`: show which Cordova plugins have new versions available
- `meteor update`: update old Cordova plugins

**Comment by Slava** [comment]
`meteor update` works on the packages level. Cordova plugins on application level is more of a convenience hack, rather than a proper integration into the abstraction of Meteor pacakges.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Update%20Cordova%20packages%20on%20%60meteor%20update%60&body=Migrated%20from:%20meteor/meteor%234344) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
