### ISSUE TITLE
DDP Publication Bug

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4346]
To reproduce the bug, `git clone` [this repo](https://github.com/ccorcos/meteor-ddp-publication-bug), run the meteor app, and click the "run bug" button. Check out the README.md for an explanation.

I'm running on Mac OS X.

**Comment by ccorcos** [comment]
I just updated the readme. On the `diff` branch, I've meticulously diff'ed document ids when creating a new cursor to make sure that I dont add the same document more than once. This fixes the problem, but it seems that merge-box should be able to handle this scenario.

**Comment by glasser** [comment]
It's not legal for a subscription to say that the same document has been added twice. (In fact, I thought this would throw an error, but I was wrong.)

**Comment by ccorcos** [comment]
Hmm. Well I heard so much about merge-box handling diffs and sending the minimal amount of data -- I figured it could handle some duplicates added to the subscription. But that's fine. I figured out a work around...

**Comment by glasser** [comment]
Yeah, that handles merging between multiple subscriptions.

I am seriously confused that this isn't an error, though; I could have sworn that it was.  Maybe it is on the client side?

**Comment by ccorcos** [comment]
No errors client or server when I added a document twice to a publication on the server.

Seems pretty easy to fix. Although, I think it would be best to just drop the duplicate rather than throw an error...
