### ISSUE TITLE
Couldn't open a mongo connection: Service temporarily unavailable. Please try again later.

### ISSUE THREAD

**Issue by arturcarvalho** [meteor/meteor#4347]
I'm not able to reach my DB for the last 8 hours. The DB seems to be working correctly but I cannot connect. Any reason for the outage? It looks similar to this case: https://github.com/meteor/meteor/issues/3487

Thank you

**Comment by justinsb** [comment]
It is "working for me" on my site.  Can you let me know which site is giving you trouble?  I have a pretty easy to guess @meteor.com email if you'd rather let me know directly.

**Comment by ekatek** [comment]
Hi @arturcarvalho.

We have been doing some maintenance on our mongo clusters. It has resulted in temporary service disruptions for some apps, including in some cases, inability to run `meteor mongo`. 

I am sorry for the impact that this has had on you. I think that the ability to run `meteor mongo` has been restored. Thank you for your patience!

**Comment by arturcarvalho** [comment]
I can confirm it's working normally again, thank you for your help!
