### ISSUE TITLE
Unexpected mongo exit code 45. Restarting.

### ISSUE THREAD

**Issue by remtsoy** [meteor/meteor#4348]
Tried to run meteor app on Vagrant. Got this error right after running meteor.

**Comment by Slava** [comment]
After googling for "vagrant meteor mongo error 45", it looks like mongodb just doesn't work that well on shared folders. All the tutorials like [this one](https://gist.github.com/gabrielhpugliese/5855677) suggest you do it on a non-shared folder and then symlink it in.

To fix your immediate error, you can reset the database by running `meteor reset` (will delete all the local changes to the database), or you can search online on how to recover your db from this state (probably deleting a mongodb.lock file should suffice).
