### ISSUE TITLE
Expand `meteor add --help`

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4350]
It would be useful to have a section on specifying package versions, including eg the difference between `@0.6` and `@=0.6`.

```
$ meteor add xolvio:cucumber@0.6.6
Currently using xolvio:cucumber without any version constraint.
The version constraint will be changed to 0.6.6.
                                              
xolvio:cucumber: CucumberJS for Velocity      
$ meteor list | grep cucum
xolvio:cucumber                               0.7.4  CucumberJS for Velocity
$ meteor add xolvio:cucumber@=0.6.6
Currently using xolvio:cucumber with version constraint 0.6.6.
The version constraint will be changed to =0.6.6.
                                              
Changes to your project's package version selections:
                                              
xolvio:cucumber  downgraded from 0.7.4 to 0.6.6

                                              
xolvio:cucumber: CucumberJS for Velocity      
$ meteor list | grep cucumber              
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
```

**Comment by stubailo** [comment]
It's already explained here: http://docs.meteor.com/#/full/meteoradd

But it could be good to add more info to https://github.com/meteor/meteor/blob/devel/tools/help.txt#L164

**Comment by jozzas** [comment]
I had a go at creating a PR to expand on the description (my first meteor contribution!) but have probably mucked something up, so apologies in advance if I have.

**Comment by stubailo** [comment]
Great start! I would also add for completeness that you can see your version constraints in `.meteor/packages` and also that the constraints are resolved with the dependencies of any other packages you are using.

**Comment by stubailo** [comment]
Commented on the PR, thanks!

**Comment by lorensr** [comment]
This has been done
