### ISSUE TITLE
Un-rendering and re-rendering a large section of DOM can be expensive; add a way to keep the DOM around when it is not visible

### ISSUE THREAD

**Issue by ganySA** [meteor/meteor#4351]
Hi

I have posted a similar question on iron-router forums but i would keen to understand if anyone else is suffering from performance issues using meteor on mobile rendering large lists.

Scenario is Master List --> Details Page. When navigating between a master list and the details page and back to the master using a mechanism such as iron router to yield data - blaze is forced to re-render. On a mobile device this is very noticeable (not unusable) but simply starts loosing any sort of native appeal / feel - this is not experienced on a desktop.

The only way to get around this is to manually load the templates into the dom and then manually hide + show templates as needed (not re-render)

Is there a means in Blaze to keep a template as a singleton - that it is never disposed from view? Just hidden and shown as needed and does not have to re-fire "rendered" or other template events.

Or is this simply a issue with how iron-router works?

**Comment by stubailo** [comment]
Right now we use a similar strategy in the Meteor documentation app to avoid re-rendering large segments of the page by hiding them with CSS, currently there is no good solution.

It's a good idea to possibly add in the future, I'll mark this as a feature request.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#171 - closing. Thanks!
