### ISSUE TITLE
Latest update not working under Ubuntu 14.04

### ISSUE THREAD

**Issue by khronedev** [meteor/meteor#4356]
Latest meteor update (1.1.0.2) seems to not work under ubuntu 14.04 (tested on MacOSX and it's working fine). The MongoDB cannot start due to error:
````
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
````
It seems that this line:
````
export LC_ALL=C
````
fixes this problem, and let MongoDB to start.

**Comment by Slava** [comment]
Hi @khronedev! It is difficult for us to reproduce. Could you please tell us what was the value of your `LC_ALL` before you changed it?

Also related issues: https://github.com/meteor/meteor/issues/4318 https://github.com/meteor/meteor/issues/1064

**Comment by khronedev** [comment]
It seems like `LC_ALL` is not set:
````
printenv | grep LC_ALL
````
don't show anything. This error is occurring for example in DigitalOcean environment, new (raw) Ubuntu 14.04 installation.

**Comment by khronedev** [comment]
I have another observation: when i set `LC_ALL`, run the server and then logout from my ssh session the value of `LC_ALL` is, I don't know, abandoned? So when I log in once more, the `LC_ALL` is not set, the serwer is running -- but when i try, for example `meteor mongo` it says:
````
Failed global initialization: BadValue Invalid or no user locale set. Please ensure LANG and/or LC_* environment variables are set correctly.
````
So i suppose the `LC_ALL` var is needed only at startup of some component, not while it's running. However, I don't know if that may help you.

**Comment by abernix** [comment]
This works properly in the latest version of Meteor.
