### ISSUE TITLE
build trouble when I use Cordova + FacebookConnect plugin to generate apk

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [meteor/meteor#4357]
Hi,

I'm building a mobile app using Meteor 1.1.0.2 + Meteoric + Cordova Facebook Connect plugin.
My issue happens when I try to build the .apk.

I don't know why but when I install: 
`meteor add cordova:com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/0e61babb65bc1716b957b6294c7fdef3ce6ace79`

And run the build, the build stops and shows this error:

`Error: The APK file for the Android build was not found.`

And when I remove this plugin: 

`meteor remove cordova:com.phonegap.plugins.facebookconnect`

The build runs normally and generates the .apk. 

Does anybody can help me? Thanks!

**Comment by dcsan** [comment]
maybe you can output the whole build log here?

btw have you checked if that FB plugin will actually work with meteor's login system? I'm interested in the same thing, getting facebook OS native login performance. but worried the token won't "just work" with meteor, its quite a different process.

edit - i just tried this and see this:

Error while building for mobile platforms: Failed to install plugin com.phonegap.plugins.facebookconnect: Variable(s) missing
(use: --variable APP_ID=value --variable APP_NAME=value).

did you setup those vars? presumably in mobile-config.js but have to research.

**Comment by caio-ribeiro-pereira** [comment]
Hi @dcsan thanks for answer me....

Well, I'm using facebookconnect + https://atmospherejs.com/particle4dev/cordova-fb to make facebook app sigin in mobile env and fallbacks for accounts-facebook for web browser version.

As you can see, the facebook env vars are there (I just changed here to "SECRET") and this is my current `mobile-config.js`: 

``` javascript
App.info({
  id: "com.mobile.app99folks",
  name: "99folks",
  description: "Find people contact around you using geolocation search.",
  author: "99folks",
  version: "1.0.0",
  website: "http://99folks.com",
  email: "99folks@99folks.com"
});

App.icons({
  "iphone": "public/icons/iphone.png",
  "iphone_2x": "public/icons/iphone_2x.png",
  "ipad": "public/icons/ipad.png",
  "ipad_2x": "public/icons/ipad_2x.png",
  "android_ldpi": "public/icons/android_ldpi.png",
  "android_mdpi": "public/icons/android_mdpi.png",
  "android_hdpi": "public/icons/android_hdpi.png",
  "android_xhdpi": "public/icons/android_xhdpi.png"
});

App.launchScreens({
  "iphone": "public/splash/iphone.png",
  "iphone_2x": "public/splash/iphone_2x.png",
  "iphone5": "public/splash/iphone5.png",
  "ipad_portrait": "public/splash/ipad_portrait.png",
  "ipad_portrait_2x": "public/splash/ipad_portrait_2x.png",
  "ipad_landscape": "public/splash/ipad_landscape.png",
  "ipad_landscape_2x": "public/splash/ipad_landscape_2x.png",
  "android_ldpi_portrait": "public/splash/android_ldpi_portrait.png",
  "android_ldpi_landscape": "public/splash/android_ldpi_landscape.png",
  "android_mdpi_portrait": "public/splash/android_mdpi_portrait.png",
  "android_mdpi_landscape": "public/splash/android_mdpi_landscape.png",
  "android_hdpi_portrait": "public/splash/android_hdpi_portrait.png",
  "android_hdpi_landscape": "public/splash/android_hdpi_landscape.png",
  "android_xhdpi_portrait": "public/splash/android_xhdpi_portrait.png",
  "android_xhdpi_landscape": "public/splash/android_xhdpi_landscape.png"
});

App.configurePlugin("com.phonegap.plugins.facebookconnect", {
  APP_ID: "SECRET",
  APP_KEY: "SECRET",
  APP_NAME: "SECRET"
});

App.setPreference("StatusBarOverlaysWebView", false);
App.setPreference("StatusBarStyle", "default");
App.setPreference("StatusBarBackgroundColor", "#FFFFFF");

App.accessRule("*", {launchExternal: true});
```

This is the entire build log...

``` bash
% Running build for platforms: [ 'android' ]
% Building the cordova build project
% Bundling the web.cordova program of the app
% Ensuring the cordova build project
% Reading the mobile control file
% Running the mobile control file
% Copying resources for mobile apps
% Writing new config.xml
% Ensuring that platforms in cordova build project are in sync
% Running synchronously:  /Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: android 3.6.4
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios

% Ensuring plugins in the cordova build project are in sync { 'org.apache.cordova.console': '0.2.13',
  'org.apache.cordova.file': '1.3.3',
  'org.apache.cordova.file-transfer': '0.5.0',
  'com.ionic.keyboard': '1.0.4',
  'org.apache.cordova.inappbrowser': '0.6.0',
  'org.apache.cordova.geolocation': '0.3.10',
  'org.apache.cordova.device': '0.2.13',
  'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'org.apache.cordova.statusbar': '0.1.10',
  'org.apache.cordova.splashscreen': '1.0.0',
  'com.phonegap.plugins.facebookconnect': 'https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/0e61babb65bc1716b957b6294c7fdef3ce6ace79' }
% Getting installed plugins for project
% Running synchronously:  /Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: com.ionic.keyboard 1.0.4 "Keyboard"
com.meteor.cordova-update 0.0.1 "CordovaUpdate"
com.phonegap.plugins.facebookconnect 0.7.0 "Facebook Connect"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.geolocation 0.3.10 "Geolocation"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins lock: { 'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'com.phonegap.plugins.facebookconnect': 'https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/0e61babb65bc1716b957b6294c7fdef3ce6ace79' }
% Copying the JS/CSS files one level up
% Removing the www folder
% Writing www/application folder
% Writing index.html
% Writing meteor_cordova_loader
% Writing a default index.html for cordova app
% Running the build command
% Running synchronously:  /Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ '--verbose', 'build', 'android', '--release' ]
% Done building the cordova build project

/Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: The APK file for the Android build was not found.
    at findApkPath (/Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:970:11)
    at /Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at buildCommand (/Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29)
    at Command.main.registerCommand._.extend.name [as func] (/Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
    at /Users/caio/.meteor/packages/meteor-tool/.1.1.3.uhsqur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
```

This is my package list (I hope can be useful too): 

``` bash
meteor-platform
iron:router
fourseven:scss
meteoric:ionic-sass
meteoric:ionicons-sass
meteoric:ionic
mizzao:user-status
accounts-base
accounts-facebook
service-configuration
accounts-ui-unstyled
aldeed:autoform
aldeed:collection2
meteoric:autoform-ionic
accounts-google
fastclick
mdg:geolocation
audit-argument-checks
splendido:accounts-meld
sanjo:jasmine
velocity:html-reporter
velocity:core
juliancwirko:s-alert-slide
dburles:google-maps
particle4dev:cordova-fb
```

**Comment by dcsan** [comment]
it says done building.. so no `unaligned.apk` comes out?

i think you can open the android project folder and try building it with google's own tools, that may give you some more info.

**Comment by dcsan** [comment]
is this stuff

```
% The tarball plugins lock: { 'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'com.phonegap.plugins.facebookconnect': 'https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/0e61babb65bc1716b957b6294c7fdef3ce6ace79' }
% Copying the JS/CSS files one level up
% Removing the www folder
% Writing www/application folder
% Writing index.html
% Writing meteor_cordova_loader
% Writing a default index.html for cordova app
```

specific to the FB plugin or always there?
it could be that plugin specifically breaks the meteor build process, so maybe you can raise an issue on their repo and see what assumptions it makes? i doubt they will fix any meteor problems for you of course tho.

**Comment by caio-ribeiro-pereira** [comment]
@dcsan yeah, no `unaligned.apk` comes out, only `android` folder and `build.tar.gz` are generated for me.

**Comment by caio-ribeiro-pereira** [comment]
@dcsan so probably is an issue from facebookconnect plugin?

**Comment by caio-ribeiro-pereira** [comment]
Is there another tarball link to install the facebookconnect?

**Comment by dcsan** [comment]
hi - I'm just guessing what might be the issue. to see if it was just the wizcorp plugin, i installed it
and can confirm it breaks the build process.

however i removed and now I still cannot build. The fragile phonegap build process is broken and there's no real info on how to debug it. I previously built this app just a few hours ago, so its definitely related to installing and trying to uninstall this wizcorp plugin.

`meteor list` shows this as the only cordova plugin.
```
cordova:org.apache.cordova.plugin.ActivityIndicator  https://github.com/Initsogar/cordova-activityindicator/tarball/5496294bf2ba9e65a854...
```

so, sorry i don't have an answer to your issue, except that I also created a problem for myself simply trying to research your issue :cry:

**Comment by caio-ribeiro-pereira** [comment]
@dcsan do you know any other solution (or workaround) to force my meteor mobile app opens facebook app instead m.facebook.com when the user sign in?
Any way thanks a lot for your help! I'll create an issue into https://github.com/Wizcorp/phonegap-facebook-plugin hoping their helps.

**Comment by caio-ribeiro-pereira** [comment]
Hi again! 

@dcsan I solved this issue!

I just removed `.meteor/local` and I reinstalled all packages, and after that installed the facebookconnect plugin using the current version and not tarball url, like this:

`meteor add cordova:com.phonegap.plugins.facebookconnect@0.11.0`

I think is better update this link https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration using this command instead the old one.

**Comment by Slava** [comment]
It looks like you had a broken Cordova build. This happens pretty often when the Cordova project gets into a somewhat broken state after adding new plugins. Unfortunately, Meteor tool is not perfect at detecting issues like this.

**Comment by dcsan** [comment]
thanks for posting back @caio-ribeiro-pereira

**Comment by caio-ribeiro-pereira** [comment]
You're welcome @dcsan and it will be nice update all Meteor wiki with this new trick

**Comment by beetaa** [comment]
hi, @caio-ribeiro-pereira @dcsan and @Slava , as you're mention above, I've also met the same problem when I build the app for android,

@caio-ribeiro-pereira is solved that by updating packages, **but did not dig into the reason of this problem**. 

when I debug my code again and again, I finally found the reason causing this Error (also mentioned in #4544 ) is simple but not so obviously: **when I reference an image or other file and its name contains any unicode character**, this Error must happened when building for android (IOS is not have this issue). 

hope helps.

**Comment by beetaa** [comment]
when any filename contains any unicode (like Chinese, Korean, etc.) character in my codebase, the ghost "Error: The APK file for the Android build was not found." turn out whenever I build for android even I did not use the file in my code.

**Comment by RaphaelRoyerRivard** [comment]
This issue should not be closed. It is clearly a bug and the trick of referencing the plugin by its exact version instead of its tar ball is a workaround that does not work for private Cordova plugins.

**Comment by caio-ribeiro-pereira** [comment]
Reopening....

**Comment by caio-ribeiro-pereira** [comment]
Does anyone can help me with some workarounds?? Because I have an app in production and I need to build a new release and I can't because of this issue...

**Comment by RaphaelRoyerRivard** [comment]
When you build with `meteor run android-device --verbose`, does your build succeeds? If not, where does it fail?

**Comment by caio-ribeiro-pereira** [comment]
Hi @RaphaelRoyerRivard!! I can even run from `android-device`. And this is the error....

``` bash
[dependency] Library dependencies:
[dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[dependency]
[dependency] ------------------
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/com.phonegap.plugins.facebookconnect/app99folks-FacebookLib/libs/android-support-v4.jar
[dependency] 	Length: 758727
[dependency] 	SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/libs/android-support-v4.jar
[dependency] 	Length: 19036
[dependency] 	SHA-1: bc202617b4cfed6673b1e10d87e52c78f7a6de38
Command finished with error code 8: /Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/cordova/run --device
ERROR running one or more of the platforms: Error: /Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project
BUILD FAILED
/Users/caio/.meteor/android_bundle/android-sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies
Total time: 1 second
/Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/cordova-build/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
```

Can you help me?

**Comment by RaphaelRoyerRivard** [comment]
It seems like android-support-v4.jar is linked twice in your project. The facebook plugin includes it once, so there must be another place in your project that you include it. In my project, I have a plugin that I am developing and it needs android-support-v4, so I added the following line in the plugin.xml of my plugin :
 
        <dependency id="android.support.v4" url="https://github.com/MobileChromeApps/cordova-plugin-android-support-v4" commit="be140fb" />

Maybe you have something similar in one of your plugins!

**Comment by caio-ribeiro-pereira** [comment]
@RaphaelRoyerRivard  so propably I'm using another package with this jar....but I don't know which is...

**Comment by caio-ribeiro-pereira** [comment]
This is my package list:

``` bash

meteor-platform
iron:router
fourseven:scss
meteoric:ionic-sass
meteoric:ionicons-sass
meteoric:ionic
mizzao:user-status
accounts-base
service-configuration
aldeed:autoform
aldeed:collection2
meteoric:autoform-ionic
fastclick
mdg:geolocation
audit-argument-checks
sanjo:jasmine
velocity:html-reporter
velocity:core
particle4dev:cordova-fb
meteorhacks:kadira
mdg:reload-on-resume
email
cmather:handlebars-server
random
matb33:collection-hooks
momentjs:moment
accounts-password
datariot:ganalytics
ddp
accounts-twitter
bozhao:link-accounts
splendido:accounts-meld
bozhao:accounts-instagram
richsilv:cordova-notifications@0.1.6
ground:db@0.3.9
percolate:synced-cron
```

Do you know which one could possibly use the same jar?

**Comment by RaphaelRoyerRivard** [comment]
The package [richsilv:cordova-notifications](https://github.com/richsilv/meteor-cordova-notifications/blob/master/package.js) depends on [de.appplant.cordova.plugin.local-notification](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/plugin.xml) which has a dependency on andriod-support-v4. Maybe it will work if you remove the package `richsilv:cordova-notifications`?

I found this thread that talks about your problem : https://github.com/meteor/meteor/issues/4265

**Comment by caio-ribeiro-pereira** [comment]
Ok, I'll try another push notification solution.... @RaphaelRoyerRivard  thank you for help me to find a way to solve this issue!

**Comment by RaphaelRoyerRivard** [comment]
If you find another push notification package that does not depend on de.appplant.cordova.plugin.local-notification, good for you, otherwise you could maybe use the same but fork de.appplant.cordova.plugin.local-notification to create your own plugin and remove the dependency of android-support-v4 in the plugin.XML file. You could then fork richsilv:cordova-notifications to create your own package that would depend on your forked plugin instead of the original.

**Comment by caio-ribeiro-pereira** [comment]
I'll test this package: https://github.com/raix/push I hope to not have problems with this package. But anyway thank you a lot! I've been searching about this issue for 2 weeks without succeeds. Now I have at least a way to how to find a solution. Thanks!

**Comment by RaphaelRoyerRivard** [comment]
You are welcome!
By the way I used raix:push in one of my apps and it worked great ;)

**Comment by caio-ribeiro-pereira** [comment]
Nice!

**Comment by dcsan** [comment]
@caio-ribeiro-pereira  did that fix work?

so the issue is that if two plugins both have a same dependency but on different versions of another plugin, the build will fail?

> Found 2 versions of android-support-v4.jar in the dependency list,
> [dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
> [dependency] All versions of the libraries must be the same at this time.

**Comment by caio-ribeiro-pereira** [comment]
@dcsan the solution was replace cordova-notification to raix:push and everything come back to normal here.

**Comment by dcsan** [comment]
@caio-ribeiro-pereira that was the fix but i'm interested in what the reason was, in case of other similar conflicts with other plugins in future.

**Comment by caio-ribeiro-pereira** [comment]
@dcsan the reason for me was everything about what @RaphaelRoyerRivard told about duplicated `android-support-v4.jar` from `facebook-connect` + `cordova-notification` packages.

**Comment by RaphaelRoyerRivard** [comment]
The real problem is that Cordova Plugins must specify a version of `android-support-v4` they want to use, so when 2 of them do not include the same version, the problem occurs. There should be a way of whether always using the latest version or somehow obfuscating the `android-support-v4` classes for each Cordova Plugin so the compiler would not complain that the dependency are included multiple times with different version.
But this is a problem related to Cordova, not Meteor.

**Comment by dcsan** [comment]
> version of android-support-v4

so its the version of a dependency? 
there is no semver or equivalent used for cordova plugin versioning control?

**Comment by RaphaelRoyerRivard** [comment]
`android-support-v4` is the name of the library. Its version is not explicit. It will be determined by the included .jar file in the Cordova Plugin.
