### ISSUE TITLE
No way to reach the organization owner

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4360]
**_1 Upvote**_ Many organizations seems to be reserved, but nobody is using them. There is no way to reach people behind to see if they would be interested in giving access to those organizations.

Personally, I am interested in two organizations, `component` (for [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components)) and `acme` (like [Perl ACME](https://en.wikipedia.org/wiki/Perl#CPAN_Acme)).

**Comment by zimme** [comment]
:+1:

**Comment by stubailo** [comment]
I can imagine that some organizations might want to remain anonymous, but it might be good to have some sort of official process for requesting organization names; especially ones that are unused.

**Comment by mitar** [comment]
Communication could also be mitigated through Meteor. Like a Meteor-provided contact form or something.

**Comment by dandv** [comment]
+:100:  for this. This is the reason why I <strike>squatted</strike> registered 150+ orgs, because I'm happy to give them to those who can actually do something useful with them.

**Comment by laosb** [comment]
Contact form +1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=No%20way%20to%20reach%20the%20organization%20owner&body=Migrated%20from:%20meteor/meteor%234360) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
