### ISSUE TITLE
x64 version conflict on Windows for node-inspector

### ISSUE THREAD

**Issue by KrishnaPG** [meteor/meteor#4361]
On 64-bit windows, installing `node-inspector` with meteor npm is installing 64-bit version, which is causing errors such as 
![image](https://cloud.githubusercontent.com/assets/4610831/7568523/e8c13436-f820-11e4-894f-985bade7f723.png)
From the above screenshot *node-inspector* is looking for "node-v11-win32-ia32", (32-bit) where as the built one is 64-bit and I can see folder with name "node-v14-win32-x64"

Here is the path the installation has created - you can see the conflict easily
>meteor-tool\1.1.3\ `mt-os.windows.x86_32`\dev_bundle\bin\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.4\ `node-v14-win32-x64`

**Comment by stubailo** [comment]
Hi, what do you mean by "installing node-inspector with meteor npm"?
