### ISSUE TITLE
Spiderable not using the real hostname of request

### ISSUE THREAD

**Issue by maomorales** [meteor/meteor#4362]
Hi guys:

In spiderable, when a request goes to phantom; the hostname of that request is being replaced by one that Meteor understands the application is hosted on. However, if you have one same app that serves multiple top level domains; and behaves a bit different based on that, then there is a problem for the SEO, because basically all the SEO will be handled by the domain that phantom receives.

In example:
We have an app where the client router makes some decisions based on the hostname (window.location.hostname) – to redirect to a route or another. The app runs at lanzador.co - but we also have other domains pointing to the same application server (like medellin.chefaway.co) – however, though the request goes to the alternate domain (medellin.chefaway.co) we notice that the window.location.hostname will always be "lanzador.co" which is the one set in the environment when started running the bundle.

For completion: we're using meteor-up to deploy to our servers.

I see that here:
https://github.com/meteor/meteor/blob/devel/packages/spiderable/spiderable_server.js

var url = Spiderable._urlForPhantom(Meteor.absoluteUrl(), req.url);

The URL is being re-written, which is the cause of the error.

Would guys allow me to make the changes and pull request it? - or should you guys make the change?

Thanks. You guys rock.

**Comment by stubailo** [comment]
If you could make a pull request for this, that would be awesome. Also, is there an easy way to test that it works? Either an automated test or an app we could deploy to check that the URL is working properly.

**Comment by petermikitsh** [comment]
@stubailo Here is my change as mentioned in #5555: 

https://github.com/WyvrnCo/spiderable/commit/96b890b14dded92b6773e325abd2a7ab1eb50e93#diff-287eee98cb072b73178dff67d5ca5755L62.

The key line that must be changed is bookmarked. When passing the url into the phantomjs process, do not use `Meteor.absoluteUrl()` but rather the hostname supplied in the header of the request.

The fix is good in a local environment. Let me test it in prod, then I'd be happy to make a PR.

**Comment by chongwang87** [comment]
@stubailo @benjamn 
this issue has been encountered more then a year ago and pull request has been created also by @maomorales or @petermikitsh 
if this pull request doesn't merge to the master, more and more custom spiderable packages with this fix will born. 
eg raxraxraxraxrax:spiderable, jazeee:spiderable-longer-timeout, lufrai:spiderable2 and more...

**Comment by chongwang87** [comment]
i created a pull request #7865 using @maomorales code
hope this get merge asap.

**Comment by abernix** [comment]
@chongwang87 Sorry, but I closed your new pull request because it's the same which was previously rejected because it has [security implications](https://github.com/meteor/meteor/pull/4480#issuecomment-112579472) (#4480).  I realize this is important to you, but you'll need to make considerations regarding the comments in the original PR before proceeding – namely, something to whitelist a host which would be allowed to be used.

As it is, your PR would appear to make it possible to crawl any site (even private or internally) via this `phantomjs` process.  If other `spiderable` packages are doing this, I would probably advise not using them.

@maomorales You had a PR on this, did you make any progress on the changes suggested in #4480?

Please discuss further in this issue before opening another PR.

**Comment by chongwang87** [comment]
sorry im not a experienced programmer, for what i understand
the security issue mentioned in #4480, it's doesn't matter if other people fake their headers
because what this package do is just to render the html using phantomjs and return to the requester

**Comment by abernix** [comment]
PhantomJS is a web-browser and this code simply uses that "web-browser" (from your Meteor server) to "load" the Meteor page and output the results.

I'm fairly sure this concern is legitimate.  If the incoming request can set the `Host:` header (which it can), and an attacker changed it to `intranet.your-safe-company.com` and the requested URL was `/corporate-secrets`, it would run `phantomjs` on the internal network (where your Meteor server is), return that data to the public internet and expose potentially sensitive information which would normally only be available on the local network where Meteor is running.

**Comment by chongwang87** [comment]
Understood
then i think we need a new function like Meteor.safeRequesterUrl() to replace with the Meteor.absoluteUrl(). else this spiderable package is not capable for multi domain single app.

**Comment by chongwang87** [comment]
we need this fix urgently because we have about 20+ website SEO crashed, all serving from the same Meteor app.

**Comment by maomorales** [comment]
@abernix I didn't have time to work on this extra piece.

As it was proposed, I think a good solution is to have a whitelist/method that Spiderable checks to know whether the host in header is valid or not. We commented about it here:

https://github.com/meteor/meteor/pull/4480

If someone can make the change I can code review/share feedback.

Cheers,
Mauricio

**Comment by hwillson** [comment]
Hi all - deprecating the `spiderable` package is currently being considered. The reasons for this include:

- Google has deprecated the [AJAX crawling specification](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) that the `spiderable` package is based on;
- Search engine crawlers (like Google's) have gotten much better at dealing with javascript/AJAX based applications, without the need for any special handling;
- There are now several better options for SEO goodness, like pre-rendering services (e.g. [Prerender.io](https://prerender.io/) - recommended in the Guide's [Enabling SEO](https://guide.meteor.com/deployment.html#seo) section and [supported out of the box with Galaxy](http://galaxy-guide.meteor.com/seo.html)), server-side rendering techniques, etc.

As such, I'll close this issue off for now. If anyone feels like this is a bad decision and can justify why `spiderable` should not be deprecated, please post back with your reasons. Thanks for opening this issue originally!

P.S. --> Anyone who wants to keep using the `spiderable` package after it has been deprecated will still be able to, by version pinning to the last non-deprecated version of `spiderable`.
