### ISSUE TITLE
INCLUSION template tag is not allowed in an HTML attribute

### ISSUE THREAD

**Issue by daven009** [meteor/meteor#4364]
I'm working on with BS popover which content could be html

so there is an attribute data-content which can be html entities
what i want to achieve is something like data-content="{{> popover}}"

so i could create the popover template as data content, is it possible?

**Comment by stubailo** [comment]
Right now, we don't support having template inclusions inside attributes. However, there is a workaround that might do what you want.

Try defining a helper called `popover` and having that return a template rendered to a string using [Blaze.toHTMLWithData](http://docs.meteor.com/#/full/blaze_tohtmlwithdata).

```js
Template.myTemplate.helpers({
  popoverHTML: function () {
    return Blaze.toHTMLWithData(Template.popover, this);
  }
});
```

Then call it as a helper:

```html
<button data-content="{{popoverHTML}}" />
```

Let me know if that works for you!
