### ISSUE TITLE
When using "meteor build" node_modules is not included

### ISSUE THREAD

**Issue by booshtukka** [meteor/meteor#4366]
I deploy my app to a locked down server with no access to the Internet, ability to build or use package managers. As such, I am used to having to build fibres independently and copying this access. It would be great to be able to lose this step, especially now we can build for specific architectures.

However, the node_modules directory in my local copy is an alias to another directory on my machine. For some reason, when building the tarball this directory is omitted, which means I need to manually move that directory over - so the tarball is not a single portable item representing the app. Is this a bug, or am I doing something wrong?

**Comment by booshtukka** [comment]
I also have to recompile brcypt, remove the version from server/programs/npm/npm-bcrypt and add in my own to server/programs/node_modules/ - it would be great to be able to actually compile something that removes all these extra steps, or have a guide so I don't have to figure it out by trial and error!

**Comment by booshtukka** [comment]
I also don't seem to have control of the built .tar.gz filename? (Sorry, probably too many issues in one issue here…)

**Comment by Slava** [comment]
If you look at the output of `meteor help build` command, you will find most of the things you need:

```
  --architecture      Builds the server for a different architecture than your
                      developer machine's architecture. Valid architectures
                      include os.osx.x86_64, os.linux.x86_64, and
                      os.linux.x86_32.
```

and

```
  --directory         Output a directory (rather than a tarball) for the
                      application server bundle. If the output location exists,
                      it will be recursively deleted first.
```

Then when you build a bundle, you can find a README file that actually explains to run `npm install` for that bundle on a machine with the architecture of your choice. Good luck.

**Comment by booshtukka** [comment]
I'm sorry, you didn't answer my questions.

1) I am building for the correct architecture, using --architecture. However, this is completely excluding the node_modules directory, and I still have to manually build fibers and bcrypt and copy them over. Something isn't working right.

2) When I build to a file (not a directory) it names the file based upon the parent directory. I would like to be able to specify the name of the tarball file.

**Comment by Slava** [comment]
1) --architecture downloads the correct binary build for npm modules required by packages.

There is a separate part of npm modules required by the app server bundle (fibers in particular), the README files explains how to install it. There is no other way to install it other than following the instructions in the file

2) `meteor help build` explains that there is an argument "output path" where you can specify the name of the tarball.

**Comment by booshtukka** [comment]
1) This isn't working for me. Underscore was completely missing, for example. I had to manually copy the node_modules folder over. And npm-bcrypt didn't work, and I had to remove it from untarred folder structure and copy it in by hand. bcrypt and fibers are the only two that fail, the rest were safe to copy directly from OS X to RedHat. Perhaps I am misunderstanding?

2) Great, thank you - I'll investigate that.

**Comment by glasser** [comment]
It sounds like you're not using the right architecture flag here for your target (`os.linux.x86_64` or `os.linux.x86_32`).  Also note that `--architecture` only chooses the right version of *packages*; the direct dependencies of the top level server are expected to be installed via `npm install` from the included package.json.  If you don't have internet access on your target server (or on any server of the same architecture, eg some AWS VM) then that will not work.

**Comment by booshtukka** [comment]
Ah, I didn't understand that. That's a shame. Is there a plan to ever include them and make it entirely portable? Also, why not do the same thing for Fibers? I build it on a Ubuntu machine, and it copies across to a RedHat machine with no issues whatsoever.

**Comment by booshtukka** [comment]
To confirm I am 100% using the correct architecture flag - os.linux.x86_64.

Also:

"2) meteor help build explains that there is an argument "output path" where you can specify the name of the tarball."

This is not true. Output path just specifies the folder to put it in, I don't have control over the filename.

e.g. 

meteor build bundle/test.tar.gz  --architecture os.linux.x86_64

…results in the tarball living at:

bundle/test.tar.gz/test.tar.gz

…rather than:

bundle/test.tar.gz

**Comment by nzomedia** [comment]
Hi @booshtukka , this issue(s) is quiet old, but i'm actually facing one of them too: the name of the meteor build output file. I was searching to see if it had been posted already before creating an issue and i found yours. Did you finally found a solution to specify the name of the .tar.gz file manually ? I found that `meteor bundle` command doesn't have the naming problem, but it's limited and offcially deprecated.
My use case, is to give the bundled file the build number from Jenkins CI.
