### ISSUE TITLE
Add Template.registerHelpers(object)

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4367]
***1 Upvote*** There are two patterns I use a few places in my app that would be improved by this:
1. registering multiple helpers at once
2. registering helpers that are also called from app JS
Before:
```coffeescript
helpers = 
  foo: ->
    0
  bar: ->
    1
for name, fn of helpers
  Template.registerHelper name, fn
```
After:
```coffeescript
Template.registerHelpers
  foo: ->
    0
  bar: ->
    1
```
Before:
```coffeescript
foo = ->
  0
bar = ->
  1

Template.registerHelper 'foo', foo
Template.registerHelper 'bar', bar
```
After:
```coffeescript
foo = ->
  0
bar = ->
  1

Template.registerHelpers {foo, bar}
```

**Comment by zimme** [comment]
:+1:

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This looks like something that could be easily implemented in a package, in fact it would be a great feature for https://github.com/aldeed/meteor-template-extension! You should suggest it there.
