### ISSUE TITLE
Error reporting for existing email/user when creating new account is broken for WiredTiger

### ISSUE THREAD

**Issue by jasonparekh** [meteor/meteor#4368]
On the client, this translates to an error 500 instead of 403.

Meteor looks for "E11000 duplicate key error index: " [1], which is not the format the WiredTiger emits [2].  (As expected, it is the format that MMAP emits [3]).

[1] https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1022
[2] https://github.com/mongodb/mongo/blob/v3.0/src/mongo/db/storage/wiredtiger/wiredtiger_index.cpp#L111
[3] https://github.com/mongodb/mongo/blob/db59e0f31b12966f127bf39df5674e3239c57350/src/mongo/db/storage/mmap_v1/btree/btree_logic.cpp#L1047

**Comment by Slava** [comment]
You are right, Meteor's accounts server parses the errors to translate them to something accounts-related. Pull requests parsing both old and new type of errors are welcome.

**Comment by justinsb** [comment]
Is there any reason we're not just checking for startsWith("E11000 ") or just checking the error code directly (if it is split out into a non-string field).  Checking strings is always going to break in the end.

**Comment by Slava** [comment]
@justinsb I think this would work. It would be less descriptive, but we can as well put a comment.

**Comment by abernix** [comment]
I believe this works fine now as Meteor was updated to work with Mongo 3.2, but if not, please open a new issue with a reproduction!  Thanks for reporting this originally!
