### ISSUE TITLE
Charset meta tag

### ISSUE THREAD

**Issue by engenheiro** [meteor/meteor#4369]
The charset meta tag is not working for special characters like "ç" and "ã" when a word is provided by a helper or passed through a form with a post method.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by engenheiro** [comment]
Its very simple.

template.testTemplate.onRendered(function () {
    console.log("Ôõé not works");
});

Console result:
��� not works

**Comment by engenheiro** [comment]
Sorry. IDE problem.
