### ISSUE TITLE
[Documentation] EJSON.addType fix proposition

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#4371]
There is a little understatement in the description of the `EJSON.addType` [method](http://docs.meteor.com/#/full/ejson_add_type). You write:

```
factory Function
A function that deserializes a JSON-compatible value into an instance of your type.
This should match the serialization performed by your type's toJSONValue method.
```

The doesn't tell much about what this function has to do. It would be good to give some example like:

``` js
EJSON.addType('CustomType', function(json) {
  // Create "CustomType" instance and initialize it with values from "json" param.
  return new CustomType();
});
```

**Comment by stubailo** [comment]
Great idea! Submit this as a PR to the docs here: https://github.com/meteor/meteor/blob/devel/docs/client/full-api/api/ejson.md

**Comment by jagi** [comment]
https://github.com/meteor/meteor/pull/4380
Done :)

**Comment by hwillson** [comment]
Hi @jagi - just following up on this (admittedly old) issue. I see that you submitted a PR for this a while back, but that PR was accidentally closed via https://github.com/meteor/meteor/commit/05451d0e32ed666e1a7eb7211f469d2299506f6f. I think your suggestion is a good one, and that your PR makes a lot of sense. If you're still interested in submitting this change, could you open a new issue / PR in the [docs repo](https://github.com/meteor/docs)? We'll make sure it gets added in - thanks, and sorry about the mixup! Closing this issue.

**Comment by jagi** [comment]
Yes sure, PR added :)
