### ISSUE TITLE
How to use SSL?

### ISSUE THREAD

**Issue by coolaj86** [meteor/meteor#4375]
I have an OAuth2 application which enforces the same security requirements in development as in production.

I have to use a specific FQDN (which points to 127.0.0.1) and enable SSL (valid local certs are provided).

I can't figure out how to turn on SSL locally.

**Comment by keyvanfatehi** [comment]
check this https://stackoverflow.com/questions/27963749/setup-https-ssl-on-localhost-for-meteor-development

**Comment by Slava** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
