### ISSUE TITLE
Bug in Minimongo query which prevents correct autorun/observe

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4377]
If one is calling `collection.update(id, {a: array});` where array is kept and modified in place between calls to `collection.update(id, {a: array});`, Minimongo does not detect that anything changed because it keeps the `array` as a reference. So when a user modifies `array` to issue a new query, it also modifies internal Minomongo storage, so update does not do anything, thus not triggering autorun or observe on data change.

This is pretty tricky to debug. Because if you read data from Minimongo collection, latest data is there. Only observe and autoruns are not triggered.

But if you look closely you will see that latest data is there already before you call update. Very peculiar indeed.

[See the reproduction](https://github.com/mitar/meteor-issue4377). If you run it in the server console you should see something like:

```
added { '0': { a: [], _id: 'PE4PpPNNKpcKaYwDm' } }
changed { '0': { a: [ '0' ], _id: 'PE4PpPNNKpcKaYwDm' },
  '1': { a: [], _id: 'PE4PpPNNKpcKaYwDm' } }
```

Instead of:

```
added { '0': { a: [], _id: 'ugr4u6TqaifWvGueD' } }
changed { '0': { a: [ '0' ], _id: 'ugr4u6TqaifWvGueD' },
  '1': { a: [], _id: 'ugr4u6TqaifWvGueD' } }
changed { '0': { a: [ '0', '1' ], _id: 'ugr4u6TqaifWvGueD' },
  '1': { a: [ '0' ], _id: 'ugr4u6TqaifWvGueD' } }
changed { '0': { a: [ '0', '1', '2' ], _id: 'ugr4u6TqaifWvGueD' },
  '1': { a: [ '0', '1' ], _id: 'ugr4u6TqaifWvGueD' } }
changed { '0': { a: [ '0', '1', '2', '3' ], _id: 'ugr4u6TqaifWvGueD' },
  '1': { a: [ '0', '1', '2' ], _id: 'ugr4u6TqaifWvGueD' } }
changed { '0': { a: [ '0', '1', '2', '3', '4' ], _id: 'ugr4u6TqaifWvGueD' },
  '1': { a: [ '0', '1', '2', '3' ], _id: 'ugr4u6TqaifWvGueD' } }
```

**Comment by glasser** [comment]
Thanks, fixed!  Looks like this was mostly specific to replacement updates (not most $op updates).
