### ISSUE TITLE
Blaze puts old text in <font> tags instead of removing

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4378]
I don't have any `<font>` tags in my templates – they are weirdly getting added. In first example, there's `{{time_ago}}` that returns eg `'2m'` based on a Session var of the current time, which gets updated every minute. In the second example, the `$2` isn't even changing – whenever an ancestor is clicked, the text node's parent's siblings are toggling in and out of existence, and a class on an ancestor is getting toggled. Only occurs in subtemplates that are added after the route's main template is rendered. Any recommendations on how to debug this one?

![screen shot 2015-05-12 at 9 46 00 pm](https://cloud.githubusercontent.com/assets/251288/7604799/fe12679c-f8fc-11e4-9746-a81c0de30ef8.png)

![image](https://cloud.githubusercontent.com/assets/251288/7605351/50087248-f903-11e4-9b9b-676e01a9b642.png)

I can't reproduce it outside of my app. Didn't used to happen, probably started in past couple weeks.

**Comment by stubailo** [comment]
> I can't reproduce it outside of my app.

Yikes - I've never seen this problem. Any thoughts in what could be causing it?

**Comment by lorensr** [comment]
Nope! I can't imagine anything I'm doing to cause it, and doesn't seem like
any of my packages should cause it. Closest are raix:handlebar-helpers
and aldeed/meteor-template-extension.

**Comment by lorensr** [comment]
Still happens occasionally. Fixed by refresh. Don't know how it gets in that state though, could have to do with hot code reload.

![image](https://cloud.githubusercontent.com/assets/251288/8766637/b7baebba-2e0e-11e5-856a-9ca613086dd4.png)

**Comment by lorensr** [comment]
Closing for now. If someone else experiences this please leave a comment, thanks!
