### ISSUE TITLE
Meteor.logout() doesn't work with remote DDP connection with different user collection.

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#4379]
A server run as port 8000.

```
meteor -p 8000
```

It holds two different users collections.

```
@Users1 = new Mongo.Collection 'users1'
@Users2 = new Mongo.Collection 'users2'
```

App1 can use users1 collection as login

```
remoteUrl = DDP.connect 'http://localhost:8000'
Meteor.users = new Mongo.Collection 'users1', remoteUrl
```

App2 can use users2 collection as login

```
remoteUrl = DDP.connect 'http://localhost:8000'
Meteor.users = new Mongo.Collection 'users2', remoteUrl
```

Each app can createUser login  as well, but it just can't logout()
Meteor.logout() return undefined and  doesn't logout user at all.

**Comment by Tarang** [comment]
@crapthings It's not enough to change the user's database to a remote one. You have to change `Accounts.connection` too.

There's a bit more info here: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L108-L130

**Comment by glasser** [comment]
@benjamn has done some relevant work on `devel` recently and can give good advice here, I think.

**Comment by benjamn** [comment]
@crapthings @Tarang Yes, the next release of Meteor will allow you to create separate instances of the `Accounts` namespace. For example:
```js
var Accounts2 = new AccountsClient({
  ddpUrl: "http://localhost:8000"
});
Accounts2.connection.call("login", ...);
console.log(Accounts2.users.find().count());
Accounts2.logout();
```

**Comment by abernix** [comment]
Closing as this sounds like it's been resolved.  Happy to reopen if that's not the case!
