### ISSUE TITLE
auth flow for mobile web app (full screen)

### ISSUE THREAD

**Issue by boundsj** [meteor/meteor#438]
There are a few issues preventing auth from working on a full screen web app in Safari. A complete documentation of these issues (and a hacked solution) is on this post on meteor-core: https://groups.google.com/forum/#!topic/meteor-core/uXab_j6xWB0

The nutshell is that the "popup" that is supposed to be generated by openCenteredPopup() (using window.open) does not work as intended on a mobile web app and, in fact, this breaks the entire flow in such a way as to make it unusable.

As noted in the post on meteor-core, a badly hacked "workaround" for this issue is demonstrated here: https://github.com/boundsj/meteor-mobile-pudding (instructions for running the test are in the meteor-core post).

For completeness, it's probably worth nothing that localStorage also presents an issue for the meteor auth flow (at an even lower level than the "popup") and this issue is already described here: https://github.com/meteor/meteor/issues/367. The hacked solution mentioned just above does not suffer from this problem because it does not actually call the meteor auth code that employs local storage - it does not even use cookies, it just passes the "state" uuid (key) value in a url back to the client for processing.

Thanks!

**Comment by glasser** [comment]
I think we fixed this in 0.9.2 with 2fd00e58b:

```
* Better mobile support for OAuth login: you can now use a
  redirect-based flow inside UIWebViews, and the existing popup-based
  flow has been adapted to work in Cordova/PhoneGap apps.
```

Let me know if that's incorrect.
