### ISSUE TITLE
Document problem - signing apks for android

### ISSUE THREAD

**Issue by jms301** [meteor/meteor#4381]
On the github page here: https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store
jarsigner should be called with: 
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 unaligned.apk your-app-name

(The guide is missing -sigalg SHA1withRSA, I think this problem is due to a newer version of jarsigner)

**Comment by Slava** [comment]
I am going to edit the page with your suggestion, thank you.
