### ISSUE TITLE
[FR][Blaze] Pass param to object's method

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#4383]
I have an idea for some improvement in Blaze or rather Spacebars. Lets say that we've defined following template helper...

```js
Template.main.helpers({
  item: function() {
    return {
      title: 'Title',
      method: function(param) {
        return param.toUpperCase();
      }
    }
  }
});
```

... and we want to display this data in following way.

```hbs
<template name="main">
  <div>{{item.title}}</div>
  <div>{{item.method "some text to upper case"}}</div>
</template>
```

As you can see I try to pass param to object's method but I get error `Can't call non-function: undefined`. Global helpers can take params so it would be great to have such possibility with object's methods.

I'm creating my own package right now for ORM https://github.com/jagi/meteor-astronomy and I've defined some helpers for displaying validation errors and I use them in following way.

```hbs
{{getValidationError field="title" object="post"}}
```

Is it bad? No, but could be better. For example I would like to make helper name shorter `getError`. Unfortunately there is `getError` helper already defined. Why don't use methods?

```hbs
{{post.getError "title"}}
``` 

It would call `getError` method with the `"title"` string as a first argument.

**Comment by Slava** [comment]
I am not quite sure what is the issue here.

I tried the following and it worked:

```javascript
  Template.hello.helpers({
    xxx: {
      yyy: function (arg) {
        return "arg: " + arg;
      }
    }
  });
```

and template is `{{xxx.yyy "some value"}}`. The output is correctly `arg: some value`.

The same worked when I made the JS helper a function returning the same object:

```javascript
  Template.hello.helpers({
    xxx: function () {
      return {
        yyy: function (arg) {
          return "arg: " + arg;
        }
      }
    }
  });
```

So, it doesn't look like a bug. It is also not a Feature Request, because everything described in the examples works for me. Closing this, please provide a clearer (and shorter) description if you disagree.

**Comment by jagi** [comment]
Hmmm in deed it works. I had this problem like one month ago and now I've decided to post it on github. But when I've checked today it doesn't throw any error, so sorry for bothering you. Maybe it was my error.
