### ISSUE TITLE
Template.instance() does not work in data context functions and accross Spacebars.dot

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4386]
`Template.instance()` does not work in functions defined in the data context. Moreover, it does not work when accessing a field using a dot operator, so in `{{something.foobar}}`, `something` has access to `Template.instance()`, but `foobar` does not.

This makes any more complicated functions and libraries of functions not be able to access current template instance.

See the reproduction here: https://github.com/mitar/meteor-issue4386

The output is:

```
Found template instance: false.
Found template instance: false.
Found template instance: true.
Found template instance: false.
Found template instance: false.
```

But expected output is:

```
Found template instance: true.
Found template instance: true.
Found template instance: true.
Found template instance: true.
Found template instance: true.
```

**Comment by mitar** [comment]
Updated description with reproduction.

cc @dgreensp ;-)

**Comment by glasser** [comment]
Thanks, these should all work.  Pull requests encouraged!

**Comment by mitar** [comment]
I looked into this and is pretty tricky. So some guidance would be useful. From what I see it would require that current view is passed to `Spacebars.dot` so that it can wrap function calls correctly. Currently it is only:

```javascript
return Spacebars.mustache(Spacebars.dot(view.lookup("."), "dataTemplateInstance"));
```

`Spacebars.mustache` should probably get the same treatment.

Alternatively, one could wrap the whole view function with this? So instead of:

```javascript
HTML.P("Found template instance: ", Blaze.View("lookup:dataTemplateInstance", function() {
    return Spacebars.mustache(view.lookup("dataTemplateInstance"));
  }), ".")
```

It would be something like:

```javascript
HTML.P("Found template instance: ", Blaze.View("lookup:dataTemplateInstance", withView(view, function() {
    return Spacebars.mustache(view.lookup("dataTemplateInstance"));
  })), ".")
```

Or simply `Blaze.View` could accept a third argument which would be a parent view. :-)

**Comment by mitar** [comment]
Any progress on this? cc @stubailo

**Comment by hwillson** [comment]
Moved to meteor/blaze#202 - closing here. Thanks!
