### ISSUE TITLE
API for getting a given package's dependencies

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4387]
I see that packages in `~/.meteor/packages` have empty `package.js` files. 

I'm making a package that gives you a function that returns the dependencies for a given package, first checking the app's local `packages` folder, then `~/.meteor/packages`. For local packages, I'm just scanning the package.js file of a package for `api.use` calls using regexes. I thought I could re-use this logic for packages in `~/.meteor/packages` but then I realized that those are empty files, and so I'll have to make new logic to read all the `*.json` files in those package folders there. If the package isn't found locally or in ~/.meteor, then it returns null.

Is there some API for getting this info already?

The package I'm working on is [`rocket:module`](https://github.com/trusktr/rocket-module).

**Comment by rclai** [comment]
[Nope](https://github.com/meteor/meteor/issues/2853).

**Comment by trusktr** [comment]
@rclai Looks like my method will be useful, so I'll split it out into a separate package when done, perhaps `rocket:build-tools` or something.

**Comment by rclai** [comment]
Nice.

**Comment by glasser** [comment]
There is no API to (from within a Meteor app) learn about package dependencies.  We can track this as a feature request.  We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by trusktr** [comment]
@glasser I'm specifically needing the API for a [build plugin](https://github.com/trusktr/rocket-module) I'm making, but not at run time. I'm currently checking locally for package info in an app's local `packages/**/package.json` files, followed by `~/.meteor/packages/**/{isopack,unipackage,os,web.browser,web.cordova}.json` files when the package isn't found locally, and soon I'll update that to take into consideration `PACKAGE_DIRS` which I didn't know about until recently. I'm also considering getting info from Atmosphere, falling back to the local methods after that.

What I've made is a function called `getPackageInfo` that accepts the name of a package whose info should be gotten. After searching in those places/files I've mentioned, the function returns something like the following for `rocket:module` for example, which is installed locally in an app in this case:

```js
 { name: 'rocket:module',
  version: '0.0.1',
  summary: 'ES6 Modules for Meteor.',
  git: 'https://github.com/trusktr/rocket-module',
  documentation: 'README.md',
  path: '/Users/josephpea/src/trusktr+meteor-with-webpack/meteor/packages/module',
  dependencies: [ 'tinytest', 'rocket:module' ] }
```

Is looking in those places a valid way to get package info? I'm assuming I can get info from those `~/.meteor/packages/**/{isopack,unipackage,os,web.browser,web.cordova}.json` files, but I'm just making assumptions here. Is there a sure way? Are there docs on these `~/.meteor/packages` files et al?

**Comment by glasser** [comment]
Rather than parse js, for the local built-from-source packages you can find the built isopacks in `.meteor/local/isopacks` in your app. That's the same (not well documented) format that you're finding in the package store in your home directory.

**Comment by rclai** [comment]
Isn't it possible to use the same logic silver to output these dependencies? @dgreenspan

**Comment by trusktr** [comment]
If so, that'd be nice. I'm not familiar with all the internal APIs since they're not documented, so I figured I'd just read the info that's there in the filesystem. The thing is I want to do it in a way that is safe when Meteor versions change.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=API%20for%20getting%20a%20given%20package's%20dependencies&body=Migrated%20from:%20meteor/meteor%234387) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
