### ISSUE TITLE
Accounts.emailTemplates.from does not get overwritten

### ISSUE THREAD

**Issue by christieewen** [meteor/meteor#4389]
For email verifications, I'd like to overwrite the "from" to a no-reply email address but emails are getting sent from what is in the MAIL_URL settings.  

Accounts.emailTemplates.from = "Admin no-reply@example.com";

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by hwillson** [comment]
Setting from addresses via `Accounts.emailTemplates.from` should be working properly. If anyone notices any issues with this, please provide a reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Closing - thanks!
