### ISSUE TITLE
Docs - Timers

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4391]
I would append http://docs.meteor.com/#/full/timers with a notice that these functions -as well as their native counterparts- act asynchronously. For js newbies, etc

**Comment by stubailo** [comment]
You mean as opposed to something like `sleep`?

**Comment by avalanche1** [comment]
Yes, definitely) Meaning they do not halt execution. Because there's definitely some confusion for those not familiar with native js setTimeout and setInterval. Me, for once) Never used those before Meteor.

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by avalanche1** [comment]
It would be nice if you posted a link to docs repo here - https://github.com/meteor/meteor/wiki/Contributing-to-Meteor

**Comment by stubailo** [comment]
https://github.com/meteor/meteor/tree/devel/docs

It's in the same repo.

**Comment by abernix** [comment]
This is in meteor/docs now if you are still interested in submitting a PR!
