### ISSUE TITLE
running meteor on mobile: A JDK is not installed

### ISSUE THREAD

**Issue by arunkumarahuja** [meteor/meteor#4395]
When I run: meteor install-sdk android

I get this:

✓ Found Android bundle
✗ A JDK is not installed
✓ Android emulator acceleration is installed
Please follow the instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux#jdk

The link does not help either.

**Comment by nukeu666** [comment]
Try steps here - http://askubuntu.com/questions/117189/apt-get-install-openjdk-7-jdk-doesnt-install-javac-why

**Comment by stubailo** [comment]
@arunkumarahuja - what do you mean by "the link does not help" As in, you followed the directions and you still get the message saying there is no JDK?

**Comment by arunkumarahuja** [comment]
I mean i tried following the steps on that link, but that does not fix the problem.

I tried following advice from nukeu666, to create a linux link but that does not seem to work either.

I have been searching. This is what i found:

sudo update-alternatives --config javac
 returns: 
No alternatives available for javac

I think m not able to install javac, in the first place.

This does not work: sudo apt-get install openjdk-7-jdk
