### ISSUE TITLE
Meteor mobile build is not changing DDP_DEFAULT_CONNECTION_URL

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [meteor/meteor#4396]
Hi, I built a meteor app which uses a custom DDP server to work well with Cloudflare, basically I followed some rules from this post: https://meteorhacks.com/cloudflare-meets-meteor

The web version of my app works fine, but the mobile app is not working.

To build the mobile version, I running this command: 

``` bash
export DDP_DEFAULT_CONNECTION_URL="http://ddp.appserver.com"
export ROOT_URL="http://appserver.com"
meteor build .build --server http://appserver.com --mobile-settings settings.json --verbose
```

But when I check the `__meteor_runtime_config__` (using alert function in my android) the `DDP_DEFAULT_CONNECTION_URL` return the same value of `ROOT_URL`.

Is there another way to setup a custom DDP server for mobile builds? Or is this a meteor bug?

Today I'm using Meteor 1.1.0.2

**Comment by caio-ribeiro-pereira** [comment]
Problem solved!
I did a little code search and I found this code: https://github.com/meteor/meteor/blob/40ec4760f049b3a312b6b228aa4bf08f91f241aa/packages/webapp/webapp_server.js

In fact, to setup a custom DDP server, you must run this command:

`MOBILE_DDP_URL="http://ddp.server.com" MOBILE_ROOT_URL="http://server.com" meteor build .build --settings=settings.json # without --server flag`

I hope help anybody here.

**Comment by caio-ribeiro-pereira** [comment]
Sorry I reopening this issue because everything works fine when I run the command `MOBILE_DDP_URL="http://ddp.server.com" meteor run android-device`, but when I run `meteor build` the DDP url doesn't change.

**Comment by Futurama56** [comment]
+ 1

**Comment by Slava** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

You might be interested in this thread as well: https://github.com/meteor/meteor/issues/3852

**Comment by caio-ribeiro-pereira** [comment]
Ok, I'll do this now! thanks!
