### ISSUE TITLE
Typo in SpaceBars "let" example

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#4397]
https://github.com/meteor/meteor/blob/6983e8d8001f8315527ec9c70b290c034779bedf/packages/spacebars/README.md#let

**Comment by Slava** [comment]
What is the typo specifically?

**Comment by Slava** [comment]
https://github.com/meteor/meteor/commit/66f9b19b0df0c7a9e7f0512e745539a99ff05daf fixed
