### ISSUE TITLE
The load() method of jQuery does not work on Meteor Cordova.

### ISSUE THREAD

**Issue by claudiojulioferraz** [meteor/meteor#4398]
I played an alert in the template and it is responding normally. The problem must be with the cordova. He's not doing ajax calls. I'm using android.

HTML

    <head>   
      <title>x</title> 
    </head>

    <body>   
      <h1>Bem Vindo!</h1>
      {{> load}} 
    </body>

    <template name="load">   
      <div class="test">   
      </div> 
    </template> 

Javascript

    Template.load.onRendered(function(){
      $(".test").load("http://www.google.com");
    });

mobile-config.js

    App.accessRule("http://www.google.com/*");
The google site is not displayed. It is all in white. See the error that appears in the terminal:

    Command finished with error code 0: /home/cj/Desktop/x/.meteor/local/cordova-build/platforms/android/cordova/run --emulator

    I20150517-19:42:42.427(-3) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.id26h03sfle7yqvrubi2/files/meteor/version

    I20150517-19:42:42.429(-3) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.

    I20150517-19:42:42.567(-3) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local

**Comment by Slava** [comment]
The error message you posted is not an error message and is an expected debug log used during Meteor development.

As of your actual issue, I think the problem is in CORS headers (which is not the same as access rules). We are tracking this issue here: https://github.com/meteor/meteor/issues/4132
