### ISSUE TITLE
Dependency bug with debugOnly packages

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#4399]
If a package depends on a debugOnly package, Meteor will still build it into production even though the dependency won't be available. I think it should throw an error instead. 

I've had this happen when using Mongol when removing the debugOnly parameter. Mongol was bundled into the production code, even thought its debugOnly dependencies did not make it.

**Comment by glasser** [comment]
This is working as designed.  Your package can use `Package['foo']` to probe for the debugOnly package and use it if it is available, just like weak dependencies.  You need to be aware if your dependency is debugOnly or not; that's part of its API.
