### ISSUE TITLE
 CORS won't work on android 4.1.2

### ISSUE THREAD

**Issue by Lenin7** [meteor/meteor#4400]
It works perfectly on 4.4+, but I cannot get it to work on older versions of android.

Error:
XMLHttpRequest cannot load http://bucket.storage.aws.net/. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.

Replication:
This can be tested directly from the android browser by trying to upload a file to Google/AWS without the need of installing a Meteor Cordova application.

Does anyone know a fix for this problem or if there will be any?
Thanks

**Comment by Slava** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

> This can be tested directly from the android browser by trying to upload a file to Google/AWS without the need of installing a Meteor Cordova application.
I am not going to accept this as a reproduction. I don't know how to develop a file upload to Google/AWS off top of my head.

**Comment by Slava** [comment]
A dup of https://github.com/meteor/meteor/issues/4132
