### ISSUE TITLE
Order of execution issue with Template.subscriptionsReady?

### ISSUE THREAD

**Issue by CaptSaltyJack** [meteor/meteor#4401]
https://forums.meteor.com/t/possible-bug-in-meteor-with-template-subscriptionsready/4507

I have a feeling this may be a bug. I don't see any reason why the HTML content inside the `{{#if Template.subscriptionsReady}}` block doesn't exist once the subscriptions are ready.

Meteorpad demo: http://meteorpad.com/pad/X2psJgD4mtaChfzNP/subscriptionBug

**Comment by CaptSaltyJack** [comment]
Be sure to open the output in a separate window to view the console messages.

![meteorpad_-_subscriptionbug](https://cloud.githubusercontent.com/assets/440132/7693980/d540307e-fd8e-11e4-8421-05b48b736a3c.png)

**Comment by stubailo** [comment]
Hey, I looked at your forum post. I think the problem you are experiencing is that your callback is fired first, and then the UI rerenders later. This is because Tracker updates are batched and not necessarily run immediately. It's documented here under Tracker.flush: http://docs.meteor.com/#/full/tracker_flush

The solution is to use [`Tracker.afterFlush`](http://docs.meteor.com/#/full/tracker_afterflush) to make sure that your callback runs after the HTML has actually been rerendered.

Going to close this because it's not really a bug, but I agree that it could probably be more clear how rerendering works in Blaze with Tracker.

**Comment by CaptSaltyJack** [comment]
@stubailo Thanks! is there maybe a better way to accomplish what I'm after?

Basically, what I want: on template render -> subcribe -> when ready, AND template is fully rendered, do `template.$('#thing').addClass('highlight')`. Is using `Tracker.afterFlush` the best way, or is there a simpler way?

**Comment by CaptSaltyJack** [comment]
This seems to work:

```javascript
Template.listing.onRendered(function () {
  var template = this;

  template.subscribe('listOfThings', function () {
    Tracker.afterFlush(function() {
      template.$('#thing').addClass('highlight');
    });
  });
});
```

**Comment by avalanche1** [comment]
This should definitely be in the docs!

**Comment by CaptSaltyJack** [comment]
Agree 100%.

**Comment by stubailo** [comment]
I think there is another issue with this approach - why manually add the class if you can use Spacebars to set it instead?

**Comment by CaptSaltyJack** [comment]
It was just an example. Actually what I really need to do (instead of adding a class) is to make a jQuery call.

**Comment by stubailo** [comment]
Ah OK I missed the forest for the trees. I agree that we should have an example in the docs, but the example should use a JQuery call, or something like highlight.js.

**Comment by CaptSaltyJack** [comment]
How about:

```javascript
Template.listing.onRendered(function () {
  var template = this;

  template.subscribe('listOfThings', function () {
    Tracker.afterFlush(function() {
      template.$('#thing').modal('show');
    });
  });
});
```

**Comment by stubailo** [comment]
I'm gonna use: http://highlightjs.readthedocs.org/en/latest/api.html#highlightblock-block

**Comment by stubailo** [comment]
fcc83be5bdc03e620c14d90769f0a2b08726531f

**Comment by CaptSaltyJack** [comment]
:+1:

**Comment by avalanche1** [comment]
superb! I feel happy

**Comment by talha-asad** [comment]
Helped me alot. Thanks!
