### ISSUE TITLE
Meteor stops watching file changes after a while.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4403]
I'm developing a build plugin, and I've noticed that after a while changing the plugin file won't cause Meteor to refresh. I'm not sure how to reproduce it. After a random while, meteor just seems to stop restarting as if I've made no changes, although I have. I `^C` my way out and restart `meteor` to continue working. The package I'm working on is [`rocket:module`](https://github.com/trusktr/rocket-module), and I experience it when testing rocket:module as a local package inside of [this meteor app](https://github.com/trusktr/meteor-with-webpack).

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Specifically, I tried to run your reproduction and it didn't run:

```
glasser@glasser-lyrid 0 /tmp $ git clone https://github.com/trusktr/meteor-with-webpack
Cloning into 'meteor-with-webpack'...
remote: Counting objects: 131, done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 131 (delta 3), reused 2 (delta 2), pack-reused 125        
Receiving objects: 100% (131/131), 21.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
glasser@glasser-lyrid 0 /tmp $ cd meteor-with-webpack/
glasser@glasser-lyrid 0 /tmp/meteor-with-webpack master u= $ git submodule init
Submodule 'meteor/packages/module' (git@github.com:trusktr/rocket-module.git) registered for path 'meteor/packages/module'
glasser@glasser-lyrid 0 /tmp/meteor-with-webpack master u= $ git submodule update
Cloning into 'meteor/packages/module'...
remote: Counting objects: 30, done.        
remote: Total 30 (delta 0), reused 0 (delta 0), pack-reused 30        
Receiving objects: 100% (30/30), 14.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
Submodule path 'meteor/packages/module': checked out '5235f7eb00f71d4887525a8f0c5b7f47e9be4063'
glasser@glasser-lyrid 1 /tmp/meteor-with-webpack master u= $ cd meteor/
glasser@glasser-lyrid 0 /tmp/meteor-with-webpack/meteor master u= $ meteor
[[[[[ /private/tmp/meteor-with-webpack/meteor ]]]]]

=> Started proxy.
rocket:module: updating npm dependencies -- webpack, rndm, babel-loader,
css-loader, style-loader, lodash...
=> Started MongoDB.
trusktr:lib: updating npm dependencies -- upper-case...
 %%%%%%%%%%%%  null
trusktr:lib2: updating npm dependencies -- lower-case...
 %%%%%%%%%%%%  null
=> Errors prevented startup:
   
   While building package trusktr:lib:
   fs.js:742:18: EEXIST, file already exists
   '/private/tmp/meteor-with-webpack/meteor/packages/lib/.npm/package/node_modules'
   (compiling main.js)
   at Object.fs.symlinkSync (fs.js:742:18)
   at CompileManager.sourceHandler (<runJavaScript-36>:129:12)
   
   
   While building package trusktr:lib2:
   fs.js:742:18: EEXIST, file already exists
   '/private/tmp/meteor-with-webpack/meteor/packages/lib2/.npm/package/node_modules'
   (compiling main.js)
   at Object.fs.symlinkSync (fs.js:742:18)
   at CompileManager.sourceHandler (<runJavaScript-36>:129:12)
   
   
=> Your application has errors. Waiting for file change.
```

Can you try to simplify your reproduction? It looks like you're doing a lot of complex stuff that involves messing with how packages build, which means it might violate some assumptions of the build tool.

**Comment by trusktr** [comment]
@glasser 

> which means it might violate some assumptions of the build tool

I believe that's the case. I now need to move some of my build steps to the app-build-time to accomplish what I really want to accomplish. Is this possible?

**Comment by glasser** [comment]
I don't know, since I don't know what you're trying to do.

We are adding some more powerful build system APIs on the `batch-plugins` branch now, though I don't know if they will help your use case.  Do rest assured that we are all pretty excited about ES6 support (including modules) and hope to improve ES6 usability in Meteor in the future.

**Comment by trusktr** [comment]
@glasser I meant generally speaking. Is there a way of adding a build plugin that would be similar to using `Package.registerBuildPlugin`, except it runs during the app's build instead (instead of before being published to Atmosphere)?

**Comment by glasser** [comment]
Yes, that is the goal of the current project Slava and I are working on, in the batch-plugins branch.  https://quip.com/YLcCAxtjuwsL (details of the proposal are a little outdated but the concept is there)

**Comment by trusktr** [comment]
@glasser 

Wow. `Plugin.registerBatchHandler` looks to be *exactly* what I need.

**Comment by trusktr** [comment]
@glasser How long do you estimate until this new API is released?

**Comment by trusktr** [comment]
@glasser I was planning to write a hack to do similar to the proposed, but taking advantage only of Plugin.registerSourceHandler. The idea would be that during package build (the first stage) but when not in the context of a project (f.e. when publishing a package to Atmosphere) I will simply compile files handled by my source handler by commenting out every line, then during the compilation of the application (while the project is in context) the plugin provider script will look through the isopacks on the system to find the commented codes, then handle them all there at the same time like a batch plugin would.

This begs a question: can we modify isopack codes and Meteor won't know and Meteor will use the modified files naively?

If isopacks aren't found matching the versions listed in `.meteor/versions`, then the plugin doesn't handle any compilation, and will tell the user to restart Meteor. Maybe an asynchronous process scans the file system until Meteor's process has put all the isopacks in place, then kills Meteor right before telling the user to restart. The next time Meteor starts, the plugin provider scripts would see all the isopacks and be able to extract commented code from them to do what it needs to do.

The problem with this is: where do I put the output files? If I can put them back into place in the isopacks I got them from, then that would work fine for load order consistency. But if I write the output files to the project directory so that Meteor detects them, they will execute out of order, therefore breaking dependents that depend on the code.
