### ISSUE TITLE
HTTP param parsing

### ISSUE THREAD

**Issue by benjick** [meteor/meteor#4406]
I'm trying to send an object in params: with a HTTP POST. The code looks like this:

``` js
var options = {
    auth: Stripe.secretKey,
    params: {
        card: {
            number: '4242424242424242',
            exp_month: 12,
            exp_year: 2016,
            cvc: '123'
        }
    }
}

console.log(HTTP.call('POST', 'https://api.stripe.com/v1/tokens', options));
```

Meteor gives no error, but Stripe doesn't get correct data here, and if I check their logs I can see

```
{
    card: "[object Object]"
}
```

Talking with people in #stripe on freenode they recommended I try card[number] etc instead, resulting in the following code:

``` js
params: {
    card['number']: '4242424242424242',
    card['exp_month']: 12,
    card['exp_year']: 2016,
    card['cvc']: '123'
}
```

giving me the error

``` bash
=> Errors prevented startup:

   While building package benjick:stripe-native:
   server/methods/tokens.js:7:8: Unexpected token [

=> Your application has errors. Waiting for file change.
```

How would I send this data via HTTP POST?

**Comment by benjick** [comment]
Okay, so this works:

```js
params: {
	'card[number]': '4242424242424242',
	'card[exp_month]': 12,
	'card[exp_year]': 2016,
	'card[cvc]': '123'
}
```

Could this be a feature request to make this
```js
var options = {
	auth: Stripe.secretKey,
	params: {
		card: {
			number: '4242424242424242',
			exp_month: 12,
			exp_year: 2016,
			cvc: '123'
		}
	}
}

HTTP.call('POST', 'https://api.stripe.com/v1/tokens', options);
```
usable?

**Comment by stubailo** [comment]
Have you tried using the `data` option instead of `params`? I'm curious if that would work.

**Comment by benjick** [comment]
@stubailo That sort of worked, but it's missing `'Content-Type': 'application/x-www-form-urlencoded'` according to the logs. So I added that

```
	var options = {
		auth: Stripe.secretKey,
		data: {
	        card: {
	            number: '4242424242424242',
	            exp_month: 12,
	            exp_year: 2016,
	            cvc: '123'
	        }
	    },
	    headers: {
	    	'Content-Type': 'application/x-www-form-urlencoded'
	    }
	}
```

Now the request looks like this (in Stripe logs):

```
{
	{"card":{"number":"4242424242424242","exp_month":12,"exp_year":2016,"cvc":"123"}}: null
}
```

**Comment by robertpitt** [comment]
@benjick, I build a package called crest to help abstract the work around communication with restful resources, feel free to use or fork..

https://github.com/Centiq/centiq-crest

**Comment by hwillson** [comment]
Closing as using `data` and setting the appropriate `Content-Type` has fixed the original issue. Thanks!
