### ISSUE TITLE
How to use Meteor.logoutOtherClients()? 

### ISSUE THREAD

**Issue by yuomtheara** [meteor/meteor#4407]
I try
```js
Accounts.onLogin(function () {
    Meteor.logoutOtherClients(function(){
       console.log('this use is logined from other');
       Router.go('/');
   });
});
```
- first I login with PC1, it show console ...... (I think that should be don't show for the first )
- second I login with PC2, it show console .... and block PC1 but router don't work
Pl help me.

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
