### ISSUE TITLE
Grouping data from cursors reactively

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4408]
**_2 Upvotes**_ **Intro.** Let say we have `Messages` collection. And every doc in that collection looks like this:

```
{
  createdAt: 1432018583531,
  message: 'Hello',
  username: 'chuk',
  chatId: '82rWv8bv4YbxEiCky'
}
```

It’s easy to render plain list of messages:

```
<template name="messages">
  {{#each messages}}
    {{> singleMessage}}
  {{/each}}
</template>

---
Template.messages.helpers({
  messages: function () {
    return Messages.find(selector, options);
  }
});
```

Output may look like so:

> - @chuk [May 18, 10:00 AM]: Hello
> - @geck [May 18, 10:01 AM]: Hi
> - @geck [May 18, 10:01 AM]: How R U?
> - @chuk [May 18, 10:02 AM]: Fine :-)
> - @chuk [May 19, 09:02 PM]: Hey?

<br>**Question.** How to group messages by date and by author? How to transform output to something like this:

> May 18
> - @chuk, 10:00 AM<br>— Hello
> - @geck, 10:01 AM<br>— Hi<br>— How R U?
> - @chuk, 10:02 AM<br>— Fine :-)
> 
> <br>May 19
> - @chuk, 09:02 PM<br>— Hey?

<br>**Thoughts.** The first idea is to use `.fetch()` and group messages imperatively by iterating them all:

```
<template name="messages">
  {{#each dateBlock}}
    {{#each messageBlock}}
      {{#each}}
        {{> singleMessage}}
      {{/each}}
    {{/each}}
  {{/each}}
</template>

---
Template.messages.helpers({
  dateBlock: function () {
    return makeDateBlocks(Messages.find(selector, options).fetch());
  },
  messageBlock: function () {
    return makeMessageBlocks(this);
  }
});
```

But I believe that’s a bad way, because `.fetch()` will cause recomputing all the data on every change. The growing list will slow down depending on the number of elements.

What is the best way to do such grouping? Hey, meteors? May be we need to insert delimiters and give special classes to the elements via jQuery depending on data-attributes in `afterFlush` callback? Or?

**Comment by rclai** [comment]
You need to use underscore's _.groupBy, and then turn it into an array again.

**Comment by artpolikarpov** [comment]
I used to use .fetch(). And I wrote about it in initial message 👆. That’s pretty bad and slow when you have large lists. Because it’s recomputing the whole array again & again on every change.

**Comment by particle4dev** [comment]
@artpolikarpov I think your data struct should be like this:
```
{
  createdAt: 1432018583531,
 updatedAt: 1432018583531,
  messages: [
               'Hello',
               'How are you ?'
 ],
  username: 'chuk',
  chatId: '82rWv8bv4YbxEiCky'
}
```
So when you insert a new message, you need to check the user who insert the last message. If it is a same user, push message to messages array. If not, create new record. Just a idea, not sure how it work :)

@rclai `client-side aggregation` This is interesting, where can i find the package ?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by artpolikarpov** [comment]
@stubailo My hope was that the non-obviousness of doing such grouping with Meteor (without fetch, without changing the data) — is a design flaw. And we should think about it on a lower development level.

**Comment by stubailo** [comment]
OK, reopened as a feature request.

**Comment by artpolikarpov** [comment]
Great.

**Comment by JobJob** [comment]
+1

**Comment by c316** [comment]
+1

**Comment by leizard** [comment]
+1. I think this will be an important feature.

**Comment by marcelhadorn** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Grouping%20data%20from%20cursors%20reactively&body=Migrated%20from:%20meteor/meteor%234408) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
I think this will be resolved with https://github.com/meteor/meteor-feature-requests/issues/26.
