### ISSUE TITLE
[FR] Package license

### ISSUE THREAD

**Issue by raix** [meteor/meteor#4411]
It would be nice if we could add a `license` in the package describe and also be able to filter the search on atmosphere.

Eg.:
```js
Package.describe({
  license: 'MIT'
});
```

**Comment by mquandalle** [comment]
Wouldn't make more sense to provide a path to the license path to be consistent with the `documentation` option?

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this is a great idea - standardizing the way people specify licenses in their packages and making sure people use good licenses would be a great way to encourage adoption.
