### ISSUE TITLE
Can't build mobile app with different DDP server

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [meteor/meteor#4412]
**_1 Upvote**_ Hi, I'm using meteor 1.1.0.2, and I can't setup a different DDP domain server when I do mobile builds.

Today I'm using the command: 
`DDP_DEFAULT_CONNECTION_URL=http://ddp.myapp.com meteor build .build --server http://myapp.com`

But when I print the var `__meteor_runtime_config__`, it returns this kind of object:

``` json
{
"DDP_DEFAULT_CONNECTION_URL": "http://myapp.com",
"ROOT_URL": "http://myapp.com",
"ROOT_URL_PATH_PREFIX": "",
"appId": "XXXXXX",
"autoupdateVersion": "XXXXXX",
"autoupdateVersionCordova": "XXXXXX",
"autoupdateVersionRefreshable": "XXXXX",
"meteorRelease": "METEOR@1.1.0.2"
}
```

This issues only happens on `meteor build` commands, when I use `meteor run android` the DDP server is fine.

**Comment by glasser** [comment]
I don't think this is possible: https://github.com/meteor/meteor/blob/c978753bb8340545699161144c5a0b50080048a4/tools/commands-cordova.js#L321

Pull requests encouraged!  It seems a little weird to me that you'd configure the build-time behavior here by setting an env var that's usually read at run time, but it wouldn't be the worst interface.  (Or you could add a `--mobile-ddp-default-connection-url` option to `meteor build`; I think that would be cleaner.)

**Comment by caio-ribeiro-pereira** [comment]
I agree with you @glasser

**Comment by teknologist** [comment]
+1 for --mobile-ddp-default-connection-url

Using Cloudfare and WebSockets we need to split html/css/js from ddp. Hence the need for a different ddp server (cloudfare passthrough)

**Comment by VioletaCalvo** [comment]
Any news for this issue?

**Comment by martijnwalraven** [comment]
What specifically is the feature request here? To be able to specify a `DDP_DEFAULT_CONNECTION_URL` different from `ROOT_URL`? Or to differentiate between mobile builds and browser builds?

**Comment by caio-ribeiro-pereira** [comment]
@martijnwalraven to be able to specify a `DDP_DEFAULT_CONNECTION_URL` different from `ROOT_URL`.

**Comment by martijnwalraven** [comment]
@caio-ribeiro-pereira: Is your use case the ability to serve assets from a separate server or CDN?

**Comment by caio-ribeiro-pereira** [comment]
Yes!

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Can't%20build%20mobile%20app%20with%20different%20DDP%20server&body=Migrated%20from:%20meteor/meteor%234412) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
