### ISSUE TITLE
Error installing zmq npm on Windows

### ISSUE THREAD

**Issue by wstucco** [meteor/meteor#4416]
While trying to install a package that depends from zmq, I get this error

```
zmq: updating npm dependencies -- zmq...
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv
"C:\\Users\\user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
"C:\\Users\\user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.1.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node_modules\\npm\\bin\\npm-cli.js"
"install" "zmq@2.8.0"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the zmq@2.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.


 => Errors while adding packages:

While building package zmq:
error: couldn't install npm package
```

I already installed the the Visual C++ Redistributable Packages and Visual Studio 2013 , `msvs_version` is set to 2013, and installing the package directly from npm succeds

```
$ npm install zmq@2.8.0 

zmq@2.8.0 ..\..\..\..\node_modules\zmq
├── bindings@1.1.1
└── nan@1.3.0

$  meteor --version
Meteor 1.1.0.2
```

**Comment by glasser** [comment]
Are you definitely running that `npm install` with the same version of `npm` that Meteor uses?  eg, in a new directory, does `C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\node.exe install zmq@2.8.0` work?

Note btw that based on all the `..\` in your `npm install` output, it may have installed zmq at a surprisingly high-level/global place...

**Comment by wstucco** [comment]
The short answer is: I don't know.   
The computer is in the office right now, tomorrow I'll check and report back to you.   
I installed the zmq npm package with `npm install` in a totally different folder (but not globally), just to check if it was something related to my environment (it took me some time to install all the dependencies, that was my way to check that zmq could be at least compiled on the system I was working on).     
Is there a way to tell meteor not to install a package that is already installed globally, eventually?

**Comment by wstucco** [comment]
the two npm had different versions, the one coming with node was very ols, so I update the system npm to 2.10.1    
still the same result, trying to install zmq with 

```
C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd install zmq@2.8.0
```

gives me the same error as before, while the other succeeds.  
do you want me to attach the content of `npm-debug.log`?

**Comment by dbaikov** [comment]
Hey, did you find the solution for this problem? I am having the same issue.

**Comment by abernix** [comment]
This is definitely a problem of using a different version of node to install (and build) your module than the one that Meteor is running it with – the binary dependencies won't match up and you'll get this failure.

You can avoid this problem if you use Meteor 1.3.1 or higher and use the new `meteor npm install` command instead of just `npm install` when adding NPMs to your Meteor project.  If you're on an existing project, simply run `meteor npm rebuild` in the root of your project and it should rebuild anything that has binary dependencies and resolve this error.  Basically, this allows you direct access to the version of node that ships with Meteor and prevents you from having to maintain your own node version.
