### ISSUE TITLE
PlexRequest won't start as service

### ISSUE THREAD

**Issue by damiantje99** [meteor/meteor#4418]
Hi,

I have this problem with PlexRequest as a service. To add PlexRequest to services I use Nssm. PlexRequest uses Meteor to run. I created a .bat file, the .bat file itself is working correctly.
When i'm starting the service I get the error: Windows could not start the PlexRequest service on local computer. It doen't give any errors. Do you guys know what the problem is?

Kind Regards

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by damiantje99** [comment]
@stubailo 

Thanks for your response. I don't think the problem is directly an Meteor issue, im just curious if you people encountered this problem before.

**Comment by kaishichan** [comment]
I still havent figured out how to add plexrequest as a window service. adding vbs to task scheduler and start at startup doesnt run correctly either. any advice from either of you?

**Comment by kaishichan** [comment]
nevermind thanks, just needed to set the working directory too!

**Comment by stubailo** [comment]
OK going to say this isn't a Meteor issue.
