### ISSUE TITLE
Add `pending` or `skip` method to TestCaseResults in TinyTest

### ISSUE THREAD

**Issue by xpressivecode** [meteor/meteor#4421]
It would be nice to have the option to mark a test as pending. The driver currently defaults to a `succeeded` state in _testStatus within the else clause.

https://github.com/meteor/meteor/blob/devel/packages/test-in-browser/driver.js
method: _testStatus
line: 222

This prevents you from being able to run something like

``` js
test.onEvent({ type: 'pending' });
```

or ideally (if the api was extended)

``` js
test.pending(); 
```

Having that new status carry forward as the classname used by the test div in the reporter would make it easy to update the driver.css to include an additional look/feel.

**Comment by XpressiveCode** [comment]
Would it be possible to have TestCaseResults exported? Doing so would allow someone to extend it via another package.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
Tinytest is no longer recommended for use (outside of the Meteor codebase itself anyways). Meteor 1.3 introduced built-in unit/integration testing support, using test driver packages like [practicalmeteor:mocha](https://atmospherejs.com/practicalmeteor/mocha). The [Testing section of the Meteor Guide](https://guide.meteor.com/testing.html) outlines the modern approach for testing your packages/applications. For this reason, feature requests concerning Tinytest now have a very low chance of being worked on (bugs will be addressed but functionality changes are a very low priority). Thanks for originally opening this request!
