### ISSUE TITLE
will integrate with the new mixed-mode famous ?

### ISSUE THREAD

**Issue by ShawnOceanHu** [meteor/meteor#4428]
Hi guys,
Famous had just released their V1.0 version, the mixed-mode with WebGL, and as a first impression just got more powerful, and very likely a key factor for building high performance cross-platform apps, on the other hand, Meteor's got a powerful templating engine, clean/powerful APIs which I really like : )
So I'm wondering if you guys have any plans to integrate with famous ? That would awesome, truly ^_^

**Comment by glasser** [comment]
Closing because this isn't an issue; the [Meteor forums](https://forums.meteor.com/) are a better place for open-ended discussion, not our bug tracker.

That said, integration with Famous is not part of the core team's roadmap now, though perhaps it's a good fit for a third party package!
