### ISSUE TITLE
Why does my template not reactive?

### ISSUE THREAD

**Issue by sato-v** [meteor/meteor#4429]
In client startup I subscribe to something:

     Meteor.publish("Roles", function(){
       return Roles.find();
     });

     Meteor.startup(function() {
       if(Meteor.isClient) {
         Meteor.subscribe('Roles');
       }
     });

And roles template:

     Template.roles.helper({
       allRoles: function() {
         return Roles.find();
       }
     })

html

          <template name="roles">
          <div>
            {{#each allRoles}}
              <label>test role</label>
           {{/each}}
          </div>
        </template>

The problem is sometime `roles` template is rendered before the `Roles` is ready.
So these is no role labels displayed.

But according to Meteor document, helpers is a reactive computation, and Database queries on Collections is  reactive data source. So after `Roles` is ready, the `{{#with allRoles}}` is reactive and should be displayed.

Why does roles not be displayed?

And then I rewrite my code to:

     Meteor.startup(function() {
           if(Meteor.isClient) {
            roles_sub = Meteor.subscribe('Roles');
           }
         });
    
    Template.roles.helper( {
           allRoles: function() {
             console.log(2);
             return Roles.find();
           },
           isReady: function() {
             console.log(1);
             console.log(roles_sub.ready());
             return roles_sub.ready();
           }
         })

html

    <template name="roles">
      <div>
        {{#if isReady}}
        {{#each allRoles}}
          <label>test role</label>
        {{/each}}
        {{/if}}
      </div>
    </template>

And still role labels cannot be displayed.
And console gives me:

    1
    false
    1
    false
    1
    true
    2

Which means `isReady()` is reactive? but why my roles labels remains blank?

Can somebody explain this?

**Comment by KristerV** [comment]
instead of `.helpers(function(){})` try `.helpers({})`

But really, you should ask questions in stackoverflow. This place is for reporting actual issues concerning meteor itself.

**Comment by sato-v** [comment]
It is actually `.helpers({})` I misspelled it .

**Comment by ShashankaNataraj** [comment]
@sato-v Can you close this "issue" ?

**Comment by ekatek** [comment]
Glad you figured it out! 

In general, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Glad it worked out though!
