### ISSUE TITLE
$elemMatch documentation outdated

### ISSUE THREAD

**Issue by KristerV** [meteor/meteor#4430]
Does this still apply? $elemMatch seems to work find on my client.

> Field operators such as $ and $elemMatch are not available on the client side yet.

I'll remove this line with a PR if someone confirms it outdated.

**Comment by glasser** [comment]
Minimongo does not support these operators in *fields specifiers*: https://github.com/meteor/meteor/blob/046de405da50d89e4dc59084393f93a3d2561e2a/packages/minimongo/projection.js#L164-L165

It does support the similarly named operator in *queries*.

See eg http://docs.mongodb.org/manual/reference/operator/query/elemMatch/ vs http://docs.mongodb.org/manual/reference/operator/projection/elemMatch/

**Comment by KristerV** [comment]
ooh, right. thanks.
