### ISSUE TITLE
No return handle Meteor.setInterval ?

### ISSUE THREAD

**Issue by udiedrichsen** [meteor/meteor#4431]
I tried to use Meteor.setInterval 

The docs says:
Returns a handle that can be used by Meteor.clearInterval.

But I got only "undefined" as return value. The callback function is called, but I cant clear this
function without having a return handle.

I am using Meteor 1.1.0.2

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

It works for me and looks correct based on the source code.
