### ISSUE TITLE
OAuth over DDP with an accessToken (namely Facebook SDK on iOS)

### ISSUE THREAD

**Issue by smothers** [meteor/meteor#4441]
Much of the current OAuth flow seems to be [tied to the browser](https://github.com/meteor/meteor/blob/devel/packages/oauth/pending_credentials.js). 

It requires a mixture of [HTTP and parsing HTML](https://github.com/jasper-lu/android-ddp-client/blob/master/src/com/keysolutions/ddpclient/android/DDPStateSingleton.java#L376), [DDP](https://github.com/jasper-lu/android-ddp-client/blob/master/src/com/keysolutions/ddpclient/android/DDPStateSingleton.java#L391) and [modifications to the oauth packages](https://github.com/jasper-lu/accounts-facebook-ddp) to get them to work with the Facebook SDK on iOS.

---

**What if the DDP login method accepted the accessToken returned from the Facebook SDK and just worked?**

``` javascript
DDPClient.call("login", { oauth: { accessToken: "auth token returned by native sdk", service: "facebook" } })
```

---

Here's the current approach:
1. Start by changing accounts-facebook to accounts-facebook-ddp. This will [recognize valid accessTokens](https://github.com/jasper-lu/facebook-ddp/blob/master/facebook_server.js#L56) instead of just trying to request new ones.

``` javascript
// 1b. Login with Facebook SDK and get credentials for user
var credentials = WhatTheFacebookLoginMethodReturns

// 2. Prime meteor's pending_credentials collection with the access token and get a "credentialSecret" by pretending to be a popup
var expiresIn = (new Date(credentials.tokenExpirationDate)).getTime() - (new Date).getTime();
var state = that._generateState("popup", credentials.token)
var meteorFacebookOauthUrl = "http://localhost:3000/_oauth/facebook/?accessToken="+credentials.token+"&expiresIn="+expiresIn+"&state="+state;
fetch(meteorFacebookOauthUrl).then(function(response){

  // 3. Parse the response HTML for the credentialSecret
  var re = new RegExp("<div id=\"config\" style=\"display:none;\">(.*?)</div>")
  var found = re.exec(response._bodyText)
  var config = JSON.parse(found[1])

  // 4. Login over DDP
  var loginOptions = {
    oauth: {
      credentialToken: credentials.token,
      credentialSecret: config.credentialSecret
    }
  };
  ddpClient.call("login", [loginOptions], function(err, result) {
    console.log("err: ", err, " result: ", result);
  });
});

_generateState = function (loginStyle, credentialToken, redirectUrl) {
  return new Buffer(JSON.stringify({
    loginStyle: loginStyle,
    credentialToken: credentialToken,
    redirectUrl: redirectUrl})).toString('base64');
};
```

This is how the Android and Objective-C DDP packages handle native OAuth and it's what I've been using with React-Native.
#3515 addresses some of the problem, but the final solution involves decoupling OAuth from the browser.

**Comment by glasser** [comment]
This seems like a good idea, but do you have answers to my questions on #3515 like:

> Do you have documentation from Facebook that we can read that makes it clear that one can trust accessTokens received from untrusted clients?

**Comment by smothers** [comment]
Does this answers your question? https://developers.facebook.com/docs/facebook-login/access-tokens#architecture

Using `appsecret_proof` to secure a Graph API requests made from the meteor server with a token generated in a native client looks like exactly what we want. Use that to make the first request from meteor for the user's profile information.

**Comment by robertpitt** [comment]
Another means of validating the access token's origin is to get the client information from the debug endpoint, you can then validate that the access token was generated via a white listed set of client_id's

@see https://developers.facebook.com/docs/facebook-login/access-tokens#debug

My initial concern is that with the appsecret is It's far from standard when it comes to the Oauth RFC, and many providers will not provide a verification mechanism such as the appsecret_proof`.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=OAuth%20over%20DDP%20with%20an%20accessToken%20(namely%20Facebook%20SDK%20on%20iOS)&body=Migrated%20from:%20meteor/meteor%234441) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
