### ISSUE TITLE
Meteor.defer not covered in docs

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4442]
It would be great to see this documented. It's a powerful feature and not mentioned anywhere.

**Comment by rgoomar** [comment]
Oh wow, never noticed that. It also isn't documented in comments either (JSDoc style).
https://github.com/meteor/meteor/blob/master/packages/meteor/timers.js#L67

**Comment by ekatek** [comment]
Agreed. Thanks for catching this!

**Comment by mitjajez** [comment]
This is duplicate of #2176.

**Comment by stubailo** [comment]
Just added it! It will be deployed next time the docs are.

**Comment by ffxsam** [comment]
This issue is so old, I forgot what `Meteor.defer` does! 😆  I guess I'll wait and see when the docs are updated.
