### ISSUE TITLE
Docs says collection.allow/deny is Server side when in fact it is isomorphic

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#4443]
http://docs.meteor.com/#/full/allow
http://docs.meteor.com/#/full/deny

[`mongo package.js`](https://github.com/meteor/meteor/blob/master/packages/mongo/package.js#L71)

**Comment by glasser** [comment]
While you can call `c.allow` or `c.deny` on the client and it will not cause an error, it will also have no effect.  (If this is incorrect, please provide a reproduction proving that.)  The concept here was to allow you to put your allow/deny calls at the top level of files shared between client and server, although it's unclear if this was the best idea.  Certainly changing it now will be backwards incompatible for many apps.

**Comment by rclai** [comment]
Yes, I knew that it wouldn't do anything on the client, it's just that it's weird that I saw an app putting the `allow/deny` rules on shared code space when I knew in the back of my mind that the docs said it only works on the server. Shouldn't there be some verbiage on the docs and if backwards incompatibility is an issue, wouldn't it be a good idea to at least throw a `console.warn` when it's being called on the client?

**Comment by glasser** [comment]
If we make the design decision to deprecate client-side use, sure, but otherwise it's just causing warnings for no reason.

We're more likely to [de-emphasize/de-core allow/deny](https://meteor.hackpad.com/Proposal-to-replace-allowdeny-with-insertupdateremove-methods-1WCvv4P9e2h) when we next work on this part of the system anyway.

**Comment by rclai** [comment]
Oh okay that sounds cool.
