### ISSUE TITLE
Docs for code-prettify package

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#4445]
Please provide a little of docs (how to use, how it works) on [`code-prettify`](https://atmospherejs.com/meteor/code-prettify) package

**Comment by stubailo** [comment]
Hey, I think this package is no longer being maintained - we used to use it in the Meteor docs, but not anymore. Honestly I think we should just remove it and make it explicitly deprecated.

You can about code prettify here: https://code.google.com/p/google-code-prettify/
You can also try my package for the popular highlight.js library, which is a little more documented: https://atmospherejs.com/simple/highlight.js

**Comment by dr-dimitru** [comment]
Hi, 
Actually we found out how to use this package - and it works well.
Your package `simple:highlight.js` is good, but unfortunately it doesn't work within [`perak:markdown`](https://atmospherejs.com/perak/markdown), please see [#2](https://github.com/stubailo/meteor-highlight.js/issues/2)

**Comment by duvrai** [comment]
@dr-dimitru please share how you made it work.

**Comment by dr-dimitru** [comment]
@duvrai here you go:
```coffeescript
$('pre').addClass 'prettyprint'
prettyPrint()

# Also you can put this into `onRendered` event:
Template.yourTemplate.onRendered ->
   $('pre').addClass 'prettyprint'
   prettyPrint()
```

**Comment by duvrai** [comment]
Great, it works now! Thanks!

**Comment by stubailo** [comment]
With highlight.js, the code would be:

```js
this.$('pre').each(function(i, block) {
  hljs.highlightBlock(block);
});
```

Btw in your code sample you should use `this.$` instead of `$` if you want the highlighting to only apply to the current template and not the entire page.

**Comment by dr-dimitru** [comment]
@stubailo thanks, fixed.
Will try to move to your package.
BTW what the main deference, I mean why we should use your package instead of default one?

**Comment by stubailo** [comment]
I was going to say a difference is that mine is documented, but it looks like it wasn't documented well enough. So probably there isn't a big difference.

**Comment by hwillson** [comment]
Hi @stubailo - relating to your comment in https://github.com/meteor/meteor/issues/4445#issuecomment-105292250:

> Hey, I think this package is no longer being maintained - we used to use it in the Meteor docs, but not anymore. Honestly I think we should just remove it and make it explicitly deprecated.

What do you think the best way to deprecate this package would be, from a PR point of view? Remove the contents of `packages/code-prettify` but leave the `README` in place containing a message saying this package has been deprecated? If so would we then publish the updated/deprecated package to Atmosphere so the deprecated notice shows in the README, then proceed with fully removing the `packages/code-prettify` package from the repo?

I haven't seen many deprecated internal packages, so I'm just wondering what the best approach for moving this issue forward would be. Thanks!

**Comment by abernix** [comment]
@hwillson My thoughts would be:

* Update the `README`
* Update the `summary` attribute within `Package.describe` in `package.js` with a "(Deprecated)" prefix
* Remove the rest of the code and publish it to Atmosphere.
* A `deprecated.js` `server` package which spits an error out to the console similar to [the `preserve-inputs`](https://github.com/meteor/meteor/blob/devel/packages/preserve-inputs/deprecated.js#L1) package.  It could provide instructions that the last version should be pinned if the functionality is still desired and link to this issue.
* Major version bump

I think once it is published, it could be removed from the `meteor/meteor` repo.

I'd vote to go ahead and just drop a PR and see how it goes. :)

**Comment by hwillson** [comment]
Great ideas @abernix - I'll take a crack at it. Thanks!

**Comment by hwillson** [comment]
I've submitted PR #8265 to help with this - let me know if I'm missing anything - thanks!

**Comment by abernix** [comment]
PR has been merged.  Thanks for filing this originally, @dr-dimitru.  I know a deprecation isn't really an answer to your question, but I think that is the correct course of action here.

Thanks for the PR, @hwillson.  Closing.
