### ISSUE TITLE
Meteor should ignore node_modules directory in the root of the project

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4452]
Many development tools come as a NPM packages (like linting, testing, etc.) and they install dependencies into `node_modules` directory. It would be very useful if Meteor would not try to compile files inside it and would simply ignore the `node_modules` directory.

**Comment by ekatek** [comment]
Cool. As long as this is clear that the directory is, really, completely, entirely ignored, and there is documentation for this, it sounds pretty good to me. Pull requests encouraged -- should not be a very complex change. Thanks!

**Comment by mitar** [comment]
I was looking around, but didn't find the simplest way to do that. Where is code which ignores `tests` directory?

**Comment by mitar** [comment]
Done: https://github.com/meteor/meteor/pull/4457

**Comment by glasser** [comment]
Thanks, merged!
