### ISSUE TITLE
Add package to automatically generate cache manifest

### ISSUE THREAD

**Issue by ehallstr** [meteor/meteor#4454]
It seems that there is no easy way to automatically add a cache manifest to a project.

http://stackoverflow.com/questions/12028922/simple-way-to-add-a-cache-manifest-to-a-meteor-ap
http://stackoverflow.com/questions/10668687/how-can-i-add-a-cache-manifest-to-a-meteor-app

Shouldn't there be a package `meteor add appcache` to automatically genereate `manifest.appcache` and add it to the `html` tag?

**EDIT** Sorry I just found out there actually is a package, appcache https://atmospherejs.com/meteor/appcache wierd I couldn't find this.

You may close this issue, thanks.

**Comment by ekatek** [comment]
Thanks. Glad to see that you have figured it out!
