### ISSUE TITLE
Publish and subscribe from admin panel of my app.

### ISSUE THREAD

**Issue by tarzak** [meteor/meteor#4458]
I need to implement interface for publishing and subscribing without code editing of my app.

For example, I made some kind of admin panel, where "admin" can see all the collections present in app.
And he wants to create new collection, fill it and share with regular users. But he doesn't know anything about programming. Is it possible to make some kind of interface, where admin can enter new name of collection, and that interface will publish and subscribe users for the new collection?

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

I believe there are packages that let you add database editors to your admin panels.
