### ISSUE TITLE
TypeError: Object #<Compiler> has no method 'host'.

### ISSUE THREAD

**Issue by sidwalecha** [meteor/meteor#4459]
I added trial version of Kendo UI Professional in Meteor project. While building the application, I got this error. Requirement is to use Scheduler Control (which is present under Kendo UI Pro and not under Kendo-Ui-Core) into my meteor application. 

What i did is downloaded the trial version of Kendo UI Pro and copy the folder into my meteor project. But it's giving build error. Can you please help?

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

(The symbol `Compiler` does not exist in the Meteor source code, so this definitely has something specific to do with the code you've added!)
