### ISSUE TITLE
Document that npm-node-aes-gcm and dependents need OpenSSL to run on Windows

### ISSUE THREAD

**Issue by aaronjudd** [meteor/meteor#4461]
On Windows 8.1,  `meteor add oauth-encryption` causes meteor to crash (or rather the `npm-node-aes-gcm` dependency).

This issue was first reported here: http://stackoverflow.com/questions/30309970/meteor-build-error-on-windows-8-1 and I've reproduced with our build as well. (see: https://github.com/reactioncommerce/reaction/issues/363 ). Also in a [core google group thread] (https://groups.google.com/forum/#!msg/meteor-core/_Vo4Ei6uUOk/Ymah9_DfEokJ).

A repository should not be necessary to reproduce.  Just adding oauth-encryption to any application causes the crash. Removing the package allows the application to run again.

This occurs on a clean windows 8.1 + meteor installation, as well as one where OpenSSL + VB libraries have been installed as well. 

```
meteor create oauth-test
cd oauth-test
meteor
```
Success.

```
meteor add oauth-encryption
meteor
```

Failure:

```
 meteor add oauth-encryption

Changes to your project's package version selections:

npm-node-aes-gcm  added, version 0.1.3_6
oauth-encryption  added, version 1.0.5


oauth-encryption: Encrypt account secrets stored in the database
PS C:\Users\Aaron\Documents\Projects\packages\oauth-test> meteor
[[[[[ C:\Users\Aaron\Documents\Projects\packages\oauth-test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20150527-09:17:09.246(-7)? (STDERR)
W20150527-09:17:09.261(-7)? (STDERR) C:\Users\Aaron\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\futu
re.js:245
W20150527-09:17:09.261(-7)? (STDERR)                                            throw(ex);
W20150527-09:17:09.261(-7)? (STDERR)                                                  ^
W20150527-09:17:09.261(-7)? (STDERR) Error: The operating system cannot run %1.
W20150527-09:17:09.261(-7)? (STDERR)
W20150527-09:17:09.261(-7)? (STDERR) C:\Users\Aaron\AppData\Local\.meteor\packages\npm-node-aes-gcm\0.1.3_6\npm\node_modules\node-aes-gcm\build\Release\node_aes_gcm.nod
e
W20150527-09:17:09.261(-7)? (STDERR)     at Module.load (module.js:356:32)
W20150527-09:17:09.261(-7)? (STDERR)     at Function.Module._load (module.js:312:12)
W20150527-09:17:09.261(-7)? (STDERR)     at Module.require (module.js:364:17)
W20150527-09:17:09.261(-7)? (STDERR)     at require (module.js:380:17)
W20150527-09:17:09.261(-7)? (STDERR)     at Object.Npm.require (C:\Users\Aaron\Documents\Projects\packages\oauth-test\.meteor\local\build\programs\server\boot.js:142:18
)
W20150527-09:17:09.261(-7)? (STDERR)     at Package (packages/npm-node-aes-gcm/wrapper.js:2:1)
W20150527-09:17:09.261(-7)? (STDERR)     at C:\Users\Aaron\Documents\Projects\packages\oauth-test\.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:33:4
W20150527-09:17:09.261(-7)? (STDERR)     at C:\Users\Aaron\Documents\Projects\packages\oauth-test\.meteor\local\build\programs\server\packages\npm-node-aes-gcm.js:42:3
W20150527-09:17:09.261(-7)? (STDERR)     at C:\Users\Aaron\Documents\Projects\packages\oauth-test\.meteor\local\build\programs\server\boot.js:222:10
W20150527-09:17:09.261(-7)? (STDERR)     at Array.forEach (native)
```

**Comment by stubailo** [comment]
@aaronjudd hey, I've figured out why this happens - on Windows, node-aes-gcm has a runtime dependency on OpenSSL. Installing the first binary from this page should fix it: http://slproweb.com/products/Win32OpenSSL.html

Let me know if that works for you - if so, we should make it much more clear that this dependency exists and tell people to install it when they use the package.

**Comment by aaronjudd** [comment]
I'll check that out - I have done a bunch of cleanup in feature-roles-379 branch - there I have removed the node-aes-gcm requirement from core, and am building the app on windows - but still running into an error "event.js:72" where meteor has a fatal crash.

**Comment by aaronjudd** [comment]
@stubailo yes, that works for me on.  Also the Visual C++ libraries were required on my fresh install.

**Comment by stubailo** [comment]
Still need to document it :smile:

**Comment by aaronjudd** [comment]
I thought that was this: https://github.com/meteor/meteor/blob/devel/packages/non-core/npm-node-aes-gcm/README.md

Sorry! I've been having some cross-project posting fatigue. lol

**Comment by stubailo** [comment]
Haha, yeah I forgot we even had that. But we should probably try to warn at runtime if possible, or document it somewhere more visible.

**Comment by menefrega** [comment]
Is there any reason, why I do have to use the 32-bit version and can't use the 64-bit?

**Comment by abernix** [comment]
This should no longer be relevant once #7548 lands in an upcoming release as `npm-node-aes-gcm` will be provided natively by Node 4's `aes-128-gcm` implementation.
