### ISSUE TITLE
A later version of Meteor is already installed - Windows

### ISSUE THREAD

**Issue by timbarclay** [meteor/meteor#4464]
I've encountered an issue using the Meteor Windows installer.

I have successfully installed Meteor on one Windows machine on a network. Now if I try to install it on another machine as the same user, the installation fails.

I have a copy of InstallMeteor.exe downloaded on 29th April 2015 and when I run that I get this dialog:
![network resource](https://cloud.githubusercontent.com/assets/6851865/7858556/f034a848-0530-11e5-8786-95a45d921eb1.png)

The path it's pointing to is: C:\Users\tbarclay\AppData\Local\Package Cache\{30491D85-F385-4432-B176-E7F770DA4A83}v1.1\ which doesn't exist. However there is an equivalent folder at that same path, in this instance named {72D9B65D-2DC5-41EE-9872-83FDA70AA57D}v1.1.0.2, which contains SetupMeteor.msi. But if I paste that in, or navigate to it using Browse, I get this alert:
![not valid](https://cloud.githubusercontent.com/assets/6851865/7858617/83b7a674-0531-11e5-9b52-28097d75072f.png)

If I press cancel I get the message: "The older version of Meteor cannot be removed. Contact your technical support group."

I have tried re-downloading the installer today and if I run that, I just get the message: "A later version of Meteor is already installed. Setup will now exit."

Meteor doesn't show up as an installed program in Add or Remove Programs.

**Comment by avital** [comment]
If you still have the old installer, can you try running it with `InstallMeteor.exe /uninstall`? What happens then?

**Comment by timbarclay** [comment]
If i run /uninstall, it shows the message "Meteor has been uninstalled" but then trying to use either the new or old installer acts the same as in the original post. I've tried restarting after the uninstall but there's no difference.

**Comment by avital** [comment]
We wrote up instructions for how to manually install Meteor on Windows without the installer: https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation

Hope this helps!

**Comment by timbarclay** [comment]
That worked. Thanks very much!
