### ISSUE TITLE
Tinytest API documentation

### ISSUE THREAD

**Issue by brylie** [meteor/meteor#4465]
Where can we find documentation about the available methods for Tinytest? This question has been asked in several places, and documented piecemeal. It would be very useful to have official documentation for the Tinytest API, if it does not already exist.
## Examples

The following examples are community efforts to document the Tinytest API.
- Meteor Cookbook - [Writing unit tests](https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook/writing.unit.tests.md)
- Github Gist - [Tinytest API](https://gist.github.com/stbaer/8168063)
- Peter Ellis Jones - [Unit testing Meteor packages with Tinytest](http://www.peterellisjones.com/post/101970705880/unit-testing-meteor-packages-with-tinytest)

**Comment by glasser** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by brylie** [comment]
OK, great :-) I will try to find where the Meteor docs are located on Github.

**Comment by hwillson** [comment]
This was addressed in PR #5750. The TinyTest API is now documented in the [package README](https://github.com/meteor/meteor/blob/devel/packages/tinytest/README.md). Closing - thanks!
