### ISSUE TITLE
Allow configuration of force-ssl

### ISSUE THREAD

**Issue by egoldblum** [meteor/meteor#4467]
Currently force-ssl is one size fits all, redirecting _all_ non-SSL HTTP traffic to HTTPS.

My meteor deployment is on a shared environment that uses Server Name Indication to host multiple SSL sites behind one ip/port pair.

SNI is not supported on WinXP IE, causing certificate errors for users that attempt to connect.

I'd like to be able to configure force-ssl to not redirect to HTTPS for specific user agents, or, to be given a hook/callback to make that decision based on arbitrary values from the incoming request.

Additionally, I'd like the option of whether or not to trust the presence of the x-forwarded-proto header to indicate an earlier SSL termination.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
The `force-ssl` package was created to force all connections to be SSL based - it takes an all or nothing approach. That being said it's quite easy to replace the internal `force-ssl` package with a custom/overridden force SSL package, that adds in any extra functionality you're interested in using. Take a look on Atmosphere for a [few examples of this](https://atmospherejs.com/?q=force-ssl). Given this, and Meteor's documented preference of having features like the one you're requesting be [implemented as an Atmosphere/npm package](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) when possible, I'll close this issue. Thanks!
