### ISSUE TITLE
build hooks/events?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4468]
It'd be nice to be able to write code (perhaps in a build plugin or some other place that can be registered with `Package.registerSomething`) and in that code we can add event handlers that let us hook into various part of Meteor's build system.

For example, something like `onAppBuild` would be for when an application build is complete (built files have been written to disk), but before that code has been executed anywhere (server or client).

Would this go against Meteor's "reproducible build" mantra? I can imagine times when this might be so handy. What are your opinions a feature like this?

**Comment by robertpitt** [comment]
This is something I would like to see as well, being able to hook into to meteor build flow will allow us to do custom build operations.

Once of the things I need to do for our project is during build write the current git/branch/tag to a file and have that file picked up as an asset so we can use it during a build environment.

**Comment by trusktr** [comment]
@robertpitt, @glasser pointed me to [this proposal](https://quip.com/YLcCAxtjuwsL). `Plugin.registerBatchHandler` would be *super* helpful.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by Benco1** [comment]
Have there been any developments on this? Any (nice!) temporary workarounds?

**Comment by hwillson** [comment]
The [Build Plugin API](http://docs.meteor.com/api/packagejs.html#build-plugin-api) introduced in Meteor 1.2 should now help address this. Closing - thanks for the original suggestion!
