### ISSUE TITLE
Moment.js bug when starting meteor with meteor shell waiting to connect

### ISSUE THREAD

**Issue by xaxxon** [meteor/meteor#4469]
In meteor 1.1.0.2 with mrt:moment 2.8.1 if I start meteor while a meteor shell is waiting, I get

Exception in setInterval callback: TypeError: Property 'moment' of object [object Object] is not a function

with a 100% reproduction rate.  If there is no meteor shell waiting, I get 0% repro rate.

Here is a commit I'm able to reproduce this on:

https://github.com/xaxxon/mchat/commit/df98b2653d551b86d4a56eae54b3597932cead7b

I'm on latest patched os x and have not tried this on any other platform.

**Comment by glasser** [comment]
I could reproduce this with 1.1.0.2, but not with current devel, so I suspect 8a578e954b0a31a5e0418b42bfbb37399aae8395 fixed it.
