### ISSUE TITLE
Allow automatically logging in to Meteor in case you're logged in to facebook

### ISSUE THREAD

**Issue by avital** [meteor/meteor#447]
In case a Meteor app is configured _only_ with Facebook login, ideally Meteor would not be worse off that using the FB SDK directly, so that people are encouraged to use Meteor Accounts, and by this having a simpler upgrade plan to more than Facebook accounts.

At the moment, the FB SDK allows you to automatically log in, whereas with Meteor Accounts you still have to click on the 'login' button.

Also, from this work easily follows a change: If accounts-facebook and, say, accounts-google are configured, and you're logged in to Facebook, then when clicking on "Sign in with Facebook" there is no pop-up shown and you are immediately logged in.

**Comment by MickaelBZH** [comment]
Are there any more input on this? 
I'm looking for this way of automatic login for Facebook games with Canvas. Basically, Facebook send a post signed request to the app, getting the request you can decode something like this:

{
   "oauth_token": "{user-access-token}",
   "algorithm": "HMAC-SHA256",
   "expires": 1291840400,
   "issued_at": 1291836800,
   "user_id": "218471"
}

The question is how to link this with Account-Facebook? How to authenticate a user (or to create a new account) with a oauth_token and a user_id?

**Comment by ramezrafla** [comment]
I recommend we add a 'PR Welcome' and 'Workaround available' flags here or close.

**Comment by abernix** [comment]
@ramezrafla Closing this is pretty reasonable.  One permission is granted, the login is practically instantaneous right now.   Given that this is a feature request and hasn't gained any traction in the last 2 years, I'll close.   Thanks for pointing it out!
