### ISSUE TITLE
Repressing Meteor Connection Status Messages in Production

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor/meteor#4470]
Hello:

I'm preparing to launch my Meteor app on Modulus, but I can't figure out how to repress the Meteor yellow connection status messages, i.e. "Connecting..." or "Waiting for server connection...." They only show up briefly when the page loads but it happens every time. What's the best practice for either keeping Meteor absolutely running all the time or repressing these status messages?

I love this framework. Congrats on the Series B funding!

**Comment by stubailo** [comment]
Those messages aren't part of the framework itself - are you using some package that displays them for you?
