### ISSUE TITLE
packages/meteor/errors.js Error Throwing Firefox Errors

### ISSUE THREAD

**Issue by iDoMeteor** [meteor/meteor#4472]
```
// Firefox                                                       // 14  <-- LN comments == tragic
var e = new Error;                                        // 15  <-- Causes error w/o ST
e.__proto__ = errorClass.prototype;            // 16  <-- Causes mutation
```

Line 15 is actually line 553 in Meteor.js according to FF, yet another case to get rid of the LN comment appending.

Line 15 above causes an error to be thrown in Firefox with a full stack trace and no message, at least when attempting a collection.update w/a selector lacking an ID.  Something I accidentally did a second time yesterday, the first time it was nearly impossible to debug.. this time.. it was easier only because there was one little code block being worked on.

Also, I thought this was coming from a package in my other project..

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

.. and happens *every* load *every* project.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

That said,  I think this might be a part of #2232.
