### ISSUE TITLE
Missing info from Wiki for architecture builds.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4474]
The [Build Machines](https://github.com/meteor/meteor/wiki/Build-Machines) could be more helpful if it showed an example of how to build for a specific architecture. For example, to build for an arch you need to run

```sh
meteor publish-for-arch <package-name>@<version>
```

where `<package-name>` and `<version>` should be replaced with the name of your package and the specific version you want to build for. For example:

```sh
meteor publish-for-arch rocket:module@0.0.1
```

How can I get this info added to the Wiki?

**Comment by glasser** [comment]
I added a little more detail and a pointer to `meteor help publish-for-arch`. Thanks!
