### ISSUE TITLE
Meteor Style Guide Clarification Required Regarding Generating Error Messages

### ISSUE THREAD

**Issue by lb-** [meteor/meteor#4478]
How do we reconcile the way you generate an error in a server method; `new Meteor.Error(error, [reason], [details])` with what is prescribed in the Meteor style guide:

> Say you have a server method that can fail in one of three ways: "No such user", "Site doesn't exist", or "Access denied".
> 
> Right: In the event of failure, the server returns a symbolic error code, 'no-such-user', 'site-not-found', or 'access-denied'. The client then looks up that error code in a table to get an appropriate message and displays it to the user.
> 
> Wrong: The server returns an error string, such as "No such user", "Site doesn't exist", or "Access denied", which the client prints. This creates multiple problems. First, what if in the future the client wants to make a decision based on the error returned? (For example, a client might want to create the site if it doesn't exist, or try to log in as an administrator if access was denied.) Second, it complicates internationalization (the user's language code would have to be sent to the server so that it could return error messages in the appropriate language, requiring a protocol change, whereas constructing the error on the client does not block internationalization on a protocol change).
> 
> Wrong: The server returns a HTTP-style status code and message, such as "403 Access Denied" or "404 No Such User". HTTP just doesn't define enough status codes for them to be a viable alternative to string codes like "site-not-found". For example, if 404 is used to represent the 'no-such-user' condition, what's left to represent 'site-not-found'?

From https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#generate-error-messages-on-the-client-not-on-the-server
# Assumed Interpretation: Error is the 'symbolic error code'
1. `error` - are we to assume this is the symbolic error code defined in the 'right' way to to do things?
2. `reason` - this becomes useless, unless of course you wish to provide the third argument `details`

Example

``` js
if (Meteor.isServer) {
  //server
  Meteor.methods({
    'messages.delete': function (messageId) {
      check(messageId, String);

      if (!this.userId) {
        throw new Meteor.Error('user-must-sign-in');
      }

      if (!Messages.findOne(messageId)) {
        throw new Meteor.Error('message-not-found');
      }
    }
  });
} else {
  //client
  errorMessages = {
    'message-not-found': function () {
      return {
        title: 'Message Not Found',
        text: 'Message was not found!',
        type: 'error'
      };
    },
    'user-must-sign-in': function () {
      return {
        title: 'Not Signed In',
        text: 'Sorry, you must be signed in to to that!',
        type: 'error'
      };
    },
  }

  Meteor.call('messages.delete', someMessageId, function (error) {
    // identify the error
    if (error) {
      myAlertGeneratingFunctionWithI18N(error.error);
    }
  });

}

```

**Comment by stubailo** [comment]
@lb- I'm confused with the specific question here. I think the main point is that `error` and `details`, if they are used, should be for the developer only and not printed directly to the user. Otherwise, your error messages in the UI depend on the method implementation, and whoever wrote the method probably wasn't thinking too hard about error message wording.

Some of the confusion arises from the fact that the Error object was designed before we discovered the best practice encoded in the Style Guide. Maybe if we knew ahead of time it wouldn't have the `reason` or `details` fields exactly, and would have something else instead. But for now, you can use those to provide information to the developer calling your API so that they know how to debug their code.

**Comment by stubailo** [comment]
What do you think would be the best way to improve the situation?

**Comment by rclai** [comment]
We simply want to know which of the three parameters this statement is referring to:

> Right: In the event of failure, the server returns a symbolic error code, 'no-such-user', 'site-not-found', or 'access-denied'. The client then looks up that error code in a table to get an appropriate message and displays it to the user.

Lately we've been seeing a lot of people writing articles and writing code where they are returning an HTTP code as the first parameter and the second parameter as some error message of some kind, but that seems to be against the style guide.

**Comment by stubailo** [comment]
Ah yes. In this case, the assumed interpretation is correct. Honestly that field should be called `code` instead of `error`. Otherwise your code has a bunch of `error.error` incantations, which is pretty confusing.

**Comment by rclai** [comment]
Okay, is that something you guys are willing to change? Or perhaps document better to avoid confusion?

Also, what about RESTful error handling? Isn't it pretty standard to return a > 400 HTTP code? Would that be an exception to this rule?

**Comment by stubailo** [comment]
DDP error codes are not related to HTTP error codes, I think numerical error codes don't really give enough data to identify what went wrong, and you end up parsing the "reason" which people usually write to be human-readable. In the REST package I am currently working on, you can specify an HTTP error code independently.

**Comment by rclai** [comment]
Okay, that makes sense. So what of my former questions? Will you guys make a change code-wise or document-wise?

**Comment by stubailo** [comment]
I think there is a documentation change to make. Any changes to DDP itself should probably wait until we have some more stuff to go in a future version.

**Comment by lb-** [comment]
@stubailo @rclai thanks for that input. It seems that the main confusion is the legacy use of 'http status codes'. I have not found any set of useful guidelines for error codes, but at the end of this comment I have put some interesting info about gRPC (by Google).

So; after looking at the comments on meteor/errors.js there is this helpful comment:

>    // Optional: A short human-readable summary of the error. Not
    // intended to be shown to end users, just developers. ("Not Found",
    // "Internal Server Error")
    self.reason = reason;
From: https://github.com/meteor/meteor/blob/master/packages/meteor/errors.js#L88

I would like to suggest the following change:

From:
``` .js
 * @param {String} [reason] Optional.  A short human-readable summary of the
 * error, like 'Not Found'.
  // https://github.com/meteor/meteor/blob/master/packages/meteor/errors.js#L73
```

To:
``` .js
 * @param {String} [reason] Optional.  A short human-readable summary of the
 * error, like 'Not Found'. Intended to be shown to end users, just developers.
  // https://github.com/meteor/meteor/blob/master/packages/meteor/errors.js#L73
```


-----

Potential inspiration (for DDP) from gRPC.

## What is gRPC?
> In gRPC a client application can directly call methods on a server application on a different machine as if it was a local object, making it easier for you to create distributed applications and services. As in many RPC systems, gRPC is based around the idea of defining a service, specifying the methods that can be called remotely with their parameters and return types. On the server side, the server implements this interface and runs a gRPC server to handle client calls. On the client side, the client has a stub that provides exactly the same methods as the server.
> http://www.grpc.io/docs/

To me this appears to be similar to PART of the DDP protocols goals, and it will be interesting to see the progress of this project (launched officially by Google in Feb of 2015).

Specifically (regarding error conventions), they will hopefully fill out this page of the docs:
http://www.grpc.io/docs/guides/error.html

**Comment by lb-** [comment]
Just found this (related to above comment about gRPC) but the error codes appear to be very high level and may not suit the issue that we are trying to solve.

https://github.com/grpc/grpc-common/blob/1b1b826628661f13caa0af59171a874225634f4b/PROTOCOL-HTTP2.md#errors

**Comment by stubailo** [comment]
@lb- yeah, there is a fundamental difference between the general "error type" (not found, etc) and a specific unique error code. I wonder if there is actually a need for both, or a hierarchical approach, like this:

```js
// Create error with a hierarchy of error types
var userNotFoundError = new Meteor.Error("not-found.user");

// Match it:
userNotFoundError.match("not-found"); // true
userNotFoundError.match("not-found.user"); // true
```

Maybe that's overkill, though. In any case the suggestion you have about the documentation of `reason` is good, we should do that.

**Comment by lb-** [comment]
@stubailo I think a hierarchical approach does make sense & originally I interpreted the docs to mean something like;

error: generic, standard-ish (at least within your app), error code but not http status codes
reason: more specific (in the context of the above error code)

eg.
```js
  throw new Meteor.Error('not-found', 'user Id not found');
```

But I do like the idea of using `.` to namespace the error but all in one string leads to potential issues for parsing down the track IMO. Agree entirely with a two step approach to returning errors, first being the error type and second being a code that references the specific error that occurred and that all this should not be visible to the user but processed as needed for user alerts on the client.

Thanks re: the documentation change, that will help clear things up for now, would you like me to make the change & put through a PR?

**Comment by rclai** [comment]
@stubailo, I noticed that some of the [Meteor core uses `Meteor.Error`](https://github.com/meteor/meteor/search?l=javascript&q=%22meteor.error%22&utf8=%E2%9C%93) in ways that are not consistent with the suggested way.

**Comment by stubailo** [comment]
@rclai unfortunately, we can't really change those at this point. Maybe there will be some changes to this in a future Meteor 2.0, whenever that is.

**Comment by datacarl** [comment]
I think there are some improvements for this part:

> Wrong: The server returns an error string, such as "No such user", "Site doesn't exist", or "Access denied", which the client prints. This creates multiple problems. First, what if in the future the client wants to make a decision based on the error returned? (For example, a client might want to create the site if it doesn't exist, or try to log in as an administrator if access was denied.) Second, it complicates internationalization (the user's language code would have to be sent to the server so that it could return error messages in the appropriate language, requiring a protocol change, whereas constructing the error on the client does not block internationalization on a protocol change).

I think it could clarify that the error string should not be sent as the first param since that makes it harder for the client to make a decision based on the error type. It should still be fine to send it as the second param, the `reason`, though. In general having the server specify the `reason` for the client to display to the user makes sense in order to stay DRY and consistent. If you call the same method in multiple places or from multiple apps using the same backend you probably want to reuse the messages. If the client ever needs to override that message it can do so by looking at the first param to decide when to override.

I haven't had a look at i18n for Meteor so I'm not quite sure how that would work, but I do find it somewhat difficult to see a scenario where the server wouldn't know about the language preference of the user. If you want to do server side rendering for the first page the client visits the server needs to know the language choice. Maybe I'm missing something here but I don't think the argument is valid. I think having the server specifying the message to display to the user makes a lot of sense. Any debug info not intended for the user could then be sent as the third param.

**Comment by hwillson** [comment]
The Meteor Style Guide has been deprecated. Its content has been split up, re-written and included in the [Meteor Guide](https://guide.meteor.com) (the [Methods - Error handling](https://guide.meteor.com/methods.html#errors) section relates to this issue in particular). As part of the on-going old issue cleanup process, I'll close this issue. For proposed Meteor Guide suggestions/changes, please open a new issue within the [Meteor Guide repo](https://github.com/meteor/guide). Thanks for opening this issue originally!
