### ISSUE TITLE
Curl install command fails on Ubuntu VM

### ISSUE THREAD

**Issue by pheer** [meteor/meteor#4479]
On trusty64 virtualbox VM I get:

ubuntu-trusty-64:~$ /usr/bin/curl https://install.meteor.com | /bin/sh
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 6121 0 6121 0 0 951 0 --:--:-- 0:00:06 --:--:-- 1245
Downloading Meteor distribution
#################### 28.1%tar: Exiting with failure status due to previous errors

curl: (23) Failed writing body (1040 != 16384)
Installation failed.

Any ideas?

**Comment by glasser** [comment]
I'm unable to replicate this on vagrant `ubuntu/trusty64` on my Mac.  Did this happen repeatably?
