### ISSUE TITLE
docs - put Accounts.createUser into Accounts section

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4484]
Shouldn't http://docs.meteor.com/#/full/accounts_createuser should be in Accounts section of the docs? Seems natively logical - right beside Accounts.onCreateUser.

**Comment by PeppeL-G** [comment]
The function is defined in the `accounts-password` package, so putting it under the `accounts-base` package in the docs seems confusing.

**Comment by stubailo** [comment]
It's true - that function is only relevant for password-based accounts. Maybe the function should be called something like `createPasswordUser` instead. But I don't think that's an issue with the docs.
