### ISSUE TITLE
Cannot specify a cordova plugin tarball in package.js for a previously added plugin

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#4486]
Yet, I can do it using `meteor add cordova:...`

Getting a message of:

Error while running for mobile platforms: Version string must look like semver
(eg '1.2.3'), not
'https://github.com/practicalmeteor/com.meteor.cordova-update/tarball/a7e98f27a26b727288da81dcfd8047eccb5f6036'.

### Steps to reproduce:

```
git clone https://github.com/practicalmeteor/wkwebviewapp
# wkwebview package is a submodule
git submodule update --init
meteor run ios
```

To see it working with the same cordova plugin added using meteor add:

```
git checkout workaround
git submodule update
meteor run ios
```

**Comment by glasser** [comment]
I tried to reproduce this, but it worked for me.

**Comment by rbabayoff** [comment]
This is weird. Stopped happening to me too. Yet on Sunday, I verified it on multiple computers.
