### ISSUE TITLE
Cordova Update & integration with new cordova plugin system (npm)

### ISSUE THREAD

**Issue by gerwinbrunner** [meteor/meteor#4488]
Hi,

cordova 5.0.0 was released recently. Do you have plans on integrating it into meteor?
Is there a way to update it manually?

It also seems that cordova is using a new plugin system. Do you plan to integrate it?
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

Here is a related thread:
https://forums.meteor.com/t/timeline-for-cordova-update/3361

**Comment by Slava** [comment]
It was done in this PR: https://github.com/meteor/meteor/pull/4390

**Comment by gerwinbrunner** [comment]
Sorry, did miss it :( 
Thanks, for your quick answer.
