### ISSUE TITLE
Update Allow/Deny: simulate result

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#4489]
It would be nice if `allow`/ `deny` would simulate the transform on the current document.
As an example, if I have a status field and a user can only update it to be `7`, I don't care if the update query is `{ $set: { score: 7 }}` or `{ $inc: { score: 1 }}`.

So something like this (`modified`) would be a good feature:

```js

Collection.allow({
  update: function (userId, doc, fields, modifier, modified) {
    if (_.contains(fields, 'score') && modified.score === 7) {
      return true;
    }
  }
});
```

**Comment by Tarang** [comment]
This is quite computationally expensive. I suspect this is the reason the information given is so barren.

You could manually simulate the result using something like this:

```
   var temp = new Mongo.Collection()
   temp.insert(doc);
   temp.update(doc._id, modifier);
   var doc = temp.findOne()
```

**Comment by zimt28** [comment]
@Tarang Thanks, that's a great idea. I think I'll just write a `simulateTransform` function and use it if needed. But I'm still curious if someone at MDG sees a simple way to do this :)

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Personally, I think this is one reason that using allow/deny for update might not be a good idea. (For insert and remove, it works great) In a more theoretical sense, it would be easy to get into a race condition where the simulated result is outdated and doesn't actually match what you will get when the update hits the database.
