### ISSUE TITLE
Missing dependenies after meteor build

### ISSUE THREAD

**Issue by michalCapo** [meteor/meteor#4490]
On *Ubuntu 14.04* with *meteor 1.1.0.2* and these packages:
* meteor-platform
* insecure
* urigo:angular
* tonekk:angular-moment
* civilframe:angular-jade
* semantic:ui-css
* angularui:angular-ui-router
* aldeed:simple-schema
* emmerge:graviton
* aldeed:collection2
* mquandalle:jade
* momentjs:moment

after *meteor build* and completed the bundle/README list. I'got these errors:
* Error: Cannot find module 'websocket-driver'
* Error: Cannot find module './strategies/ping_strategy'.

There is a workaround on this by running:
```
cd programs/server
rm -fr npm/mongo
npm install websocket-driver
npm install mongodb@1.3.20
```
What do you think? It's meteor's problem or problem of package combination?

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
