### ISSUE TITLE
TemplateInstance#data is only updated when Template.instance() is called

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#4491]
The Template.data doesn't update unless view.templateInstance() is called.

This makes it useless to save a reference to the template and use it's data. Instead of that the user would have to call myTemplate = myTemplate.view.templateInstance() or save a reference to the view instead and call templateInstance from there.

This is very missleading and generates hard to track bugs. To find what was wrong with the update I had to create a special project to track down the issue, since the template.data was updated after a click event was fired in that template (because in the meteor source code when there is a handler attached to it the view.templateInstance() function is called automatically).

**Comment by stubailo** [comment]
You're right - `template.data` is not actually reactive and is updated imperatively when `Template.instance()` is called.

I think the best way to work around this would be to use [`Blaze.getData`](http://docs.meteor.com/#/full/blaze_getdata). Like so:

```js
var tpl = Template.instance();
// much later
Blaze.getData(tpl.view);
```

However, I 100% agree that this is weird and confusing. We need a better API for accessing the data context in different places, and there is abundance of issues on GitHub about it.

**Comment by santiagopuentep** [comment]
Blaze.getData(), good to know! Thanks.

I'm test using the manuel:viewmodel package. Its looking very good!

**Comment by mitar** [comment]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) fixed that by making `.data()` always a reactive data source. (Which you can use or not, so you can also limit the reactivity.)

**Comment by hwillson** [comment]
Migrated to meteor/blaze#179 - closing - thanks!
