### ISSUE TITLE
Provide a way to get child template instances in Blaze

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#4492]
There are no methods to find children templates. This makes it impossible to create hierarchical template apps, with templates inside templates accessible without extending the TemplateInstance prototype manually.

There are no methods to easily find the parent template either and this is very important to be able to do modifications to the template itself like putting it in focus or accessing it's view state.

I think this functionality is very basic and should be in the Blaze engine by default. It's already confusing with the views, data and template hierarchies.

**Comment by stubailo** [comment]
I completely agree. For now, the template-extension package provides some of these features: https://github.com/aldeed/meteor-template-extension

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) provide this feature.

**Comment by JoeyAndres** [comment]
I created [jandres:template-children](https://github.com/JoeyAndres/template-children) specifically for this problem. It is built on top of template-extension. The children()/getChildren() array _tries_ to maintain the underlying order of child templates. 

_tries_ means, if you only moved partially some of the elements under a template, the order is not kept track of, thus best to wrap your template stuff with some wrapper if you plan on switching their orders around.

**Comment by santiagopuentep** [comment]
Thanks joey for the solution. I´m using React now and I find that it is pretty amazing, extremely stable and tested and I haven´t had a single problem with it. It´s a shame that MDG is not developing Blaze any more, but we are in luck that the alternatives are really good.

Trying out Redux now, and it looks incredible too.

**Comment by mitar** [comment]
Closing in favor of: https://github.com/meteor/blaze/issues/115
