### ISSUE TITLE
Tracker.autorun inside template.autorun should make sure Template.instance() works

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4494]
Currently, if you run `Template.autorun` inside of a `template.autorun`, `Template.instance()` is not bound correctly inside that nested computation to the template instance. This makes it really hard to use reactivity as immediately when you have a bit more complicated code and you split it into multiple reactivity paths, things do not work anymore. The issue is even larger because you cannot nest `template.autorun` calls..

I would propose that if `Template.autorun` detects that it is running inside of `template.autorun`, it remembers the template context in which is running and runs its computation in that template context, when the computation is rerun, so that `Template.instance()` keeps working.

[Reproduction](https://github.com/mitar/meteor-issue4494). Just click the button and see the web console.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Is [this workaround](https://github.com/stubailo/meteor-issue4494/commit/cc6ad056061d80f888ce9dfcac0d15489856d709) not sufficient? It seems to me that passing the template instance in explicitly is probably better than associating it through a global dynamic function like `Template.instance()` anyway?

**Comment by mitar** [comment]
OK, this was just an example. The issue here is that then we get to the coding style where I have to pass a variable all around the codebase. The whole point of reactivity is that it nicely decouples things so that one does not have to pass around variables. Also, if you are reusing existing code which does not expect template as an argument, you have to do then make it accept. So if you have a function which can be called or from a template helper in a reactive way (and uses `Template.instance()`), or from autorun, now you have to make it accept an argument.

Also, it makes this pattern not working: https://github.com/awwx/meteor-isolate-value/issues/2

**Comment by Fathardie** [comment]
I agree with mitar. I was creating a function to retrieve a configuration which is associated with certain templates. Not being able to use Template.instance() indeed results in passing the template variables all around the script. In this case having a global function is exactly what I want. In that function I don't care which template it is, I want the current template.

In the short time I have been using meteor I found a lot of awesome stuff, but I also came across the nesting of autoruns that break stuff. Meteor is awesome but it could improve on consistency throughout its api. Template.instance() being only callable in certain situations(while in a template create/render/helper function) is one of those inconsistencies.

**Comment by stubailo** [comment]
I dunno, maybe a lot of people will disagree with this, but to me it seems like we should be moving in the direction of fewer global variables and hidden state, not the other way around. If your function depends on where it is called, then the best way to make that clear and obvious is to take that parameter as an argument.

Let's see what other people say about it.

**Comment by Fathardie** [comment]
I agree on lowering hidden state to a minimum! It is tough though to give an exact rule for what to remain hidden and what to move out into the open. My feeling about the Template.instance() is that it should be accessible anywhere as it is a function on a global variable/prototype which is why I find it inconsistent.

How would you feel about the exact opposite? Doing it functional style? As in, move every piece of config data (e.g. everything associated with Meteor and Template) to a single state object that is passed to every callback? Or move global state to a single global state object which is accessible anywhere? (Not sure if these suggestions are completely possible with Meteor, still a newb with the framework xD)

That might overdue it, but it is the cleanest solution there is.

**Comment by mitar** [comment]
I do agree that it is ugly to have a hidden state, but that is the approach Meteor took. And in some way it tries to add new semantics to JavaScript. Which made it easier to program some things. So while I see internal implementation as ugly, because it uses hidden state, it is good, because it exposes simpler API to the user. The question now is should this be reverted or should we just keep it, just making sure that it works on all cases. And it is not true that it does not work. It works in many many cases. I am reporting here only one extra side case, and if we fix it, then we will have it work well and with clean semantics to the outside, even if internally it is ugly.

**Comment by mitar** [comment]
@stubailo: This is an example of a simple fix which would keep Blaze cool.

**Comment by hwillson** [comment]
Migrated to meteor/blaze#178 - closing this one - thanks!
