### ISSUE TITLE
Error with meteor-developer oAuth

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#4497]
Hello,

I'm trying to create a private package server for Meteor (code here: https://github.com/sebakerckhof/stratosphere ).
Syncing packages works, but to publish packages meteor tool tries to login with a meteor developer account using oAuth.
I've set up oAuth using accounts-meteor-developer and I can log in using my meteor developer account and the accounts-ui. However, when meteor tool tries to log in I get:

"Error in OAuth Server: Failed to complete OAuth handshake with Meteor developer accounts. failed [400] {"error":"invalid_grant"}"

This is at the stage when my server tries to exchange the authorization code (which I receive correctly) for an access token.

I've looked at the request to "http://www.meteor.com/oauth2/token" and both the grant type, client id, client secret and redirect uri seem to be fine. The authorization code is the one send to me by meteor tool, so the error should lie there?

**Comment by stubailo** [comment]
Can you point me to the code that is making the request for an access token? I have some ideas about what might be going wrong, but it's hard to say exactly without knowing what you are doing.

**Comment by sebakerckhof** [comment]
Well, it's basically all Meteor code.
So I set the meteor_package_server_url environment var to my meteor project ( https://github.com/sebakerckhof/stratosphere ), this project uses the default accounts-meteor-developer, oauth, etc packages. I have it correctly configured, since I can login using my meteor developer account via the little front-end I have.

However, the oauth flow of meteor tool seems to fail.

So the steps are:
1) Meteor tool asks the meteor authentication servers for an authorization code:
https://github.com/meteor/meteor/blob/devel/tools/auth.js#L386-L390
This seems to work fine.

2) Meteor tool then returns this authorization token to my meteor project:
https://github.com/meteor/meteor/blob/devel/tools/auth.js#L396-L400
This seems to arrive and is handled by the meteor-developer oauth request handler, which then wants to exchange the auth code for an access token:
https://github.com/meteor/meteor/blob/devel/packages/meteor-developer/meteor_developer_server.js#L40-L59
My package server console then outputs:
Error in OAuth Server: Failed to complete OAuth handshake with Meteor developer accounts. failed [400] {"error":"invalid_grant"}

I also get some lines of:
```
Unable to parse state from OAuth query: ÃŸ~Â›Ã¡ÃžyÃ±Ã¾Â·Ã£n]Ã³fÃºÃ·ÂŽ}wÂ†ÂžÃ¥Â¦Âœ
But that seems to be correct behavior, since meteor tool only passes the credentialtoken as state parameter in http requests. So it's a little weird that it displays this as if it's an error.

3) The oAuth package seems to continue and it doesn't return an access denied, since we get to this line of code in meteor tool:
https://github.com/meteor/meteor/blob/devel/tools/auth.js#L411-L416

Which translates into this ddp request:
```
{"msg":"method","method":"login","params":[{"oauth":{"credentialToken":"336b4d558f63425d82b69459d4ae5aac","credentialSecret":"<!DOCTYPE html>\n<html>\n<head>\n<script type=\"text/javascript\">\n\nfunction storeAndClose() {\n\n  var config = JSON.parse(document.getElementById(\"config\").innerHTML);\n\n  if (config.setCredentialToken) {\n    var credentialToken = config.credentialToken;\n    var credentialSecret = config.credentialSecret;\n\n    if (config.isCordova) {\n      var credentialString = JSON.stringify({\n        credentialToken: credentialToken,\n        credentialSecret: credentialSecret\n      });\n\n      window.location.hash = credentialString;\n    }\n\n    if (window.opener && window.opener.Package &&\n          window.opener.Package.oauth) {\n      window.opener.Package.oauth.OAuth._handleCredentialSecret(\n        credentialToken, credentialSecret);\n
    } else {\n      try {\n        localStorage[config.storagePrefix + credentialToken] = credentialSecret;\n      } catch (err) {\n        // We can't do much else, but at least close the popup instead\n        // of having it hang around on a blank page.\n      }\n    }\n  }\n\n  if (! config.isCordova) {\n    document.getElementById(\"completedText\").style.display = \"block\";\n    window.close();\n  }\n}\n</script>\n</head>\n<body onload=\"storeAndClose()\">\n  <p id=\"completedText\" style=\"display:none;\">\n    Login completed. <a href=\"#\" onclick=\"window.close()\">\n      Click here</a> to close this window.\n  </p>\n\n  <div id=\"config\" style=\"display:none;\">{\"setCredentialToken\":false,\"storagePrefix\":\"Meteor.oauth.credentialSecret-\",\"isCordova\":false}</div>\n</body>\n</html>\n"}}],"id":"1"}
```
To my meteor server. So the credentialSecret (which is the response from the oauth package) is a bunch of html instead of a token.

4) finally the login request obviously fails at the server and we end up getting this message in meteor tool:
Error from package server: No matching login attempt found [145546287]

And that's where meteor tool stops.

**Comment by sebakerckhof** [comment]
This seems to be fixed in newer versions of meteor-tool (probably from Meteor 1.2 and up).

**Comment by stubailo** [comment]
Glad to hear it!
