### ISSUE TITLE
Log into Shell

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#4498]
It would be cool if `console.log`s would appear in the Meteor Shell. Alternatively something like `shell.log` would be really helpful.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This sounds like an awesome idea. There might be some difficulties though figuring out which logs came from the command that you typed in the shell, vs other parts of the running app.

**Comment by dandv** [comment]
Is there a way to log anything at the shell console? `console.*` calls print nothing. Nothing about this in `meteor help shell` or in the docs.

Right now I'm working around this by buffering stuff in a string:

```js
var output = ''; Meteor.users.find().forEach(function (user) { if (...) output += user.emails[0].address + '\n' }); output;
```

... which displays the `\n`s literally besides being awkward :)

**Comment by zimt28** [comment]
@dandv Couldn't find any, just `return`ing the information seems to work here.

**Comment by cheapRoc** [comment]
`repl.log = (line) => { repl.rli.output.write(line + '\n') }` should do the trick!

**Comment by cheapRoc** [comment]
Of course, that function doesn't provide nearly as friendly output as the normal Meteor `console.log` but it's something. :)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Log%20into%20Shell&body=Migrated%20from:%20meteor/meteor%234498) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
