### ISSUE TITLE
Remove references to document in Minimongo and DDP packages and sub-dependencies (better support for React Native)

### ISSUE THREAD

**Issue by hharnisc** [meteor/meteor#4501]
Minimongo and DDP are super useful and could theoretically be able to run on platforms that don't have a document (JavascriptCore runtime used by React Native for instance)

Digging in a little deeper it looks like most of the dependencies on the document are related to initialization. 

- document.readyState
- document.addEventListener
 -"DOMContentLoaded"
- document.attachEvent
  - "onreadystatechange"
- window.attachEvent <- might need some of the window functionality as well
 - "load"
- window.addEventListener
  - "load"

Because these types of environments don't have a document they can start running code right away.

I'm not exactly sure what the tooling would look like, but it would be nice to build a version of the client side JS for Minimongo and DDP (Tracker as well) that doesn't assume a document or window.

For reference I've opened an issue against React Native as well - https://github.com/facebook/react-native/issues/1495

They've suggested removing the document (if possible) and in the interim creating an NPM package that polyfills the document.

**Comment by Slava** [comment]
Minimongo and DDP client don't have such a strong dependency on any of these functions you listed. It looks like, these functions would be used just to understand when the page is loaded.

Minimongo and DDP client can be successfully used as a server-side dependency in a Meteor app, which proves for me that there is no good reason it wouldn't work today as is. Also you didn't give any links where it happens and I didn't find them myself.
