### ISSUE TITLE
Minimongo and mongo shell return different results for an $elemMatch query

### ISSUE THREAD

**Issue by juliomac** [meteor/meteor#4502]
Can't find a way to show a filtered collection by one of its embedded/nested document fields. I can filter by one field of the first level document but, when  I use find to filter by a outer field it keeps showing the entire collection.

I have put the test app on github adapted to run without auto-publish that is equivalent to the one shown on this text: https://github.com/juliomac/Test-of-Blaze-Meteor-with-cursors-fileter-by-embedded-nested-field

I want to show on Blaze Templace the same results I can get from from find() on Mongo Shell.

I have the following collection and want to to show on template only the results of key1=x1 of the Embedded document:

```
       SampleCol.insert({
        Name: "John Doe",
        Description: "Nice Guy",
        Embedded_1: [{
            key1: 'x1',
            key2: 'x2',
            qty: 1,
            Isittrue: true,
            TariffTypes: [{
                TariffCode: 'Promocional',
                TariffName: 'Promoção Especial',
                Price: 125,
                Refundable: true,
                MinStay: 0,
                Weekdays: ['Sun', 'Sat'],
                LastMinuteMinDays: -1                   
            },
            {
                TariffCode: 'LastMinute',
                TariffName: 'Promoção de Última Hora!',
                Price: 150,
                Refundable: true,
                MinStay: 0,
                Weekdays: ['Sun', 'Sat'],
                LastMinuteMinDays: 48      
            }], 
            },
            {
            key1: 'x3',
            key2: 'x4',
            qty: 2,
            Isittrue: false,
                                TariffTypes: [{
                    TariffCode: 'Promocional',
                    TariffName: 'Promoção Especial',
                    Price: 175,
                    Refundable: true,
                    MinStay: 0,
                    Weekdays: ['Sun', 'Sat'],
                    LastMinuteMinDays: -1                   
                },
                {
                    TariffCode: 'LastMinute',
                    TariffName: 'Promoção de Última Hora!',
                    Price: 200,
                    Refundable: true,
                    MinStay: 0,
                    Weekdays: ['Sun', 'Sat'],
                    LastMinuteMinDays: 48      
                }] 
            }]
        });
```

I can get all key1=x1 Documents on Mongo Shell with:
db.SampleCol.find({},{_id:0, Embedded_1: {$elemMatch: {key1:"x1"}}});

It returns this:

```
/* 1 */
{
    "Embedded_1" : [ 
        {
            "key1" : "x1",
            "key2" : "x2",
            "qty" : 1,
            "Isittrue" : true,
            "TariffTypes" : [ 
                {
                    "TariffCode" : "Promocional",
                    "TariffName" : "Promoção Especial",
                    "Price" : 125,
                    "Refundable" : true,
                    "MinStay" : 0,
                    "Weekdays" : [ 
                        "Sun", 
                        "Sat"
                    ],
                    "LastMinuteMinDays" : -1
                }, 
                {
                    "TariffCode" : "LastMinute",
                    "TariffName" : "Promoção de Última Hora!",
                    "Price" : 150,
                    "Refundable" : true,
                    "MinStay" : 0,
                    "Weekdays" : [ 
                        "Sun", 
                        "Sat"
                    ],
                    "LastMinuteMinDays" : 48
                }
            ]
        }
    ]
}
```

My helper is just:

```
  Template.test2.helpers({
    items: function () {
collection = SampleCol.find({},{_id:0, Embedded_1: {$elemMatch: {key1:"x1"}}});
      return collection;
    }
  });
```

My template is:

```
<template name="test2">
{{#each items}}
    {{#each Embedded_1}}
        {{this.key1}}
    {{/each}}
{{/each}}
</template>
```

The problem is that is showing the entire collection and not only the selected key=x1 parts. If I try to set Data context to Embedded_1 as in the examples below:
Example#1:

```
    {{#each Embedded_1}}
        {{this.key1}}
    {{/each}}
```

It shows nothing

Example#2:

```
{{#each Embedded_1 in items}}
        {{key1}}
{{/each}}
```

it shows nothing and give error message:
Error: No such function: Embedded_1

What should I do to solve it?

**Comment by zhenyasav** [comment]
Thanks for submitting an issue.

From a very brief investigation of your linked reproduction, It looks like the selector `{'Embedded_1': {$elemMatch: {key1:"x1"}}, Name:"John Doe"}` isn't matching because the subscription `Meteor.subscribe('samplecol', 'Jane Doe', 'x1');` only selects for `Jane Doe`. (file: `client/embeddedcol.js`)

If you could please submit a more basic reproduction that only has the _minimum_ necessary content to show what's not working, that would be very helpful.

**Comment by juliomac** [comment]
Hi Zhenyasav, thanks for your attention. the first part code was actually commented out. I took it out now to clean up the code now.

The meteor.publish gets its filtering option from the Meteor.subscribe('samplecol', 'Jane Doe', 'x1'). Therefore, it should have only published documents congaing both 'Jane Doe' and her subdocuments containing 'x1'.  The first part runs OK, only 'Jane Doe' shows up. However all her subdocuments, including key1='x3' are shown.

**Comment by altrome** [comment]
Hi, I've  exactly the same issue. Any news about it?

**Comment by mitar** [comment]
Can somebody make a reproduction for this?

**Comment by mitar** [comment]
cc @hwillson

**Comment by abernix** [comment]
@mitar Are you experiencing this issue, trying to close out old issues which can't be reproduced, or just checking if @hwillson has time to make a reproduction?

**Comment by mitar** [comment]
I stumbled about this old issue and because I never encountered anything like this, I asked original authors or people who are saying that they have the same issue for a reproduction. The linked above does not showcase the issue they are reporting.

There seems simply errors in code. For example, on the server the code is:

```
SampleCol.find({Name: namefilter}, {'Embedded_1': {$elemMatch: {key1: 'x1'}}});
```

This is not valid Meter MongoDB query code. It should be:

```
SampleCol.find({Name: namefilter}, {fields: {'Embedded_1': {$elemMatch: {key1: 'x1'}}}});
```

Also, it seems the issue here is not between Minimongo and Mongo shell, but between server-side Mongo queries and Mongo shell. The query above is not touching Minimongo.

So, I think I will just close this. Maybe some doc change to point out this difference in syntax between Meteor Mongo queries and MongoDB shell queries should be done.
