### ISSUE TITLE
Deploy successful but get there's no route on the client or the server

### ISSUE THREAD

**Issue by elmor34** [meteor/meteor#4505]
Local test works without problem.
Deploy is successful.

But get 

Oops, looks like there's no route on the client or the server for url: "http://zeytin.meteor.com/."

Tried several times...

regards
Gokhan

**Comment by Tarang** [comment]
Follow the quick start guide at: https://github.com/iron-meteor/iron-router

You've not created a route for the `/` path. This is why you see this.

**Comment by glasser** [comment]
Thanks @Tarang !  This error doesn't come from Meteor core so I think @Tarang is correct that you need to follow the Iron Router docs here.

**Comment by kimseak-dev** [comment]
I got sample problem do you have another solution?? please i stack 3 days ready
