### ISSUE TITLE
expose the meteor - mongo connection

### ISSUE THREAD

**Issue by zstew** [meteor/meteor#4509]
I'd like something like:

myRawMongoConnection = Meteor.getMongoConnection();

I'm also open to the idea that such a thing would be unwise, but I'd like to know why so I can plan to have this functionality or not.

**Comment by glasser** [comment]
This functionality has existed since Meteor 1.0.4 via the `myCollection.rawDatabase()` and `myCollection.rawCollection()` methods, which return references to the Node Mongo driver database and collection objects.  However, it's not documented other than in History.md.  Just added docs in 67e1330!
