### ISSUE TITLE
App takes forever (never suceed) to load on hot code pushes in Chrome regular mode

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#4511]
Hi everyone.
I have a similar problem than:
https://forums.meteor.com/t/solved-localhost-3000-takes-longtime-to-get-data-from-server-on-linux-mint/

Since a few days, when i'm doing a hot code push with my app in dev mode on localhost, Chrome is loading forever. The app is freezed and never succeed to load completely. 
I suspected an infinite loop somewhere in my code so i tried to profile it. What's very strange is than at soon as i launch the recording process for the Chrome profiler, the app finish loading.
Following infos in the other thread , i tried to launch the app in chrome "incognito" mode, and it doesn't have this problem. I don't know exactly what's the difference between Chrome Regular and "incognito" mode (i think it doesn't remember cookies, but the appcache seems to work correctly).
I'm on Chrome 43.0.2357.81 (64-bit) on Linux.
I don't have this problem with Firefox. I never had this problem in the past.
I tried to reproduce with an empty project but i don't know what to look for.

**Comment by ekatek** [comment]
Thank you for your report, but we can't investigate this without a reproduction. We understand that you tried, but we are not really sure what is causing this either. 

Incognito mode turns off Chrome Add-ons. Is it possible that one of your Chrome Add-ons is somehow involved in this issue?
