### ISSUE TITLE
Tracker.autorun handle should have flush() method

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4514]
***2 Upvotes*** So that you can force running the computation. Currently, the only way to force running it is to do something like:

```javascript
function autorunBody() {
  // ... do stuff ...
}

Tracker.autorun(autorunBody);

// Forcing run.
autorunBody();
```

But it would be much better if one could do:

```javascript
handle = Tracker.autorun(function () {
  // ... do stuff ...
});

// Forcing run.
handle.flush();
```

Because new dependencies would be registered/updated. And it might even be that `flush()` does nothing if dependencies were not really invalidated.

Because currently the only way to run this is to call `Tracker.flush()` but this flushes **all** computations. It would be great if you could flush only one, clearing dependency invalidations along the way.

**Comment by rclai** [comment]
:+1:

**Comment by kostko** [comment]
There is `handle._recompute()` which does something similar, but it is an internal function.

**Comment by rclai** [comment]
Ah interesting..

**Comment by stubailo** [comment]
Is `Computation#invalidate` not sufficient for your needs? http://docs.meteor.com/#/full/computation_invalidate

**Comment by mitar** [comment]
No, invalidate just marks the computation invalid and it will run with next flush cycle then. But with `run` proposed here (or it could be named `flush`) only that computation is run immediately.

`computation.invalidate()` + `Tracker.flush()` would be the same, but that would run all computations, not just this one.

**Comment by mitar** [comment]
I made a pull request, see #4715.

**Comment by mitar** [comment]
Oh, @chicagogrooves, I cannot believe you just implemented this as well. :-)

I would propose that the method is named `flush()` though. And you have to check if `_recomputing` is not already set for some reason.

Also, I think it is better that we do not invalidate the computation. So `flush` should only do something if computation is invalidated already.

**Comment by chicagogrooves** [comment]
Hmm, your method name `flush` is consistent with your code, @mitar, but can you say a little more about your use case? I took off in your direction, wanting a `run()` that does `invalidate` and a single `flush`.. I think we could do both `run` and `flush` off of my PR, and get test coverage, what do you think ?

**Comment by mitar** [comment]
I think my `flush` concept is just evolved from the `run` idea, after using it for some time. Namely, autorun computations should not really have side-effects which are not a consequence of reactivity. So if there was nothing inside an autorun which invalidated the autorun, then there is little reason why you would want to rerun it. If you do want to rerun it, despite no dependency change, then you are reruning it for some side-effect. And I think that changes the semantics of what computations are about.

On the other hand, flush just gives you a bit more control when you reruning to happen, if things were already invalidated. Maybe you just changed dependencies and you know that the computation is invalidated and you want to immediately (in blocking way) to use the result. But you do not want to rerun the whole flush cycle of all computations.

But yea, if you really want `run()`, then you can just do `computation.invalidate()`, `computation.flush()`. In some way `flush` is a primitive which is missing, while `run` can then be made using `invalidate()` and `flush()`.

**Comment by chicagogrooves** [comment]
Okay, I think I know how to work that into a test case- two autoruns exist, each with a common dep. Dep is changed, one is flushed, one is not, you can assert on side effects that flush only recomputes its receiver. I'll update my PR later today. Thanks for the idea..

**Comment by chicagogrooves** [comment]
This is ready in #4710

**Comment by mitar** [comment]
:+1:
