### ISSUE TITLE
Tinytest support for test coverage

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4518]
**_4 Upvotes**_ It would be great if tiny test could also calculate test coverage. So tests in a package would tell how much they are covering code in that package.

**Comment by ekatek** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. This sounds like it would be a potentially useful feature for tinytest to have, however we are unlikely to get to it in the near future. I'll leave this open for now.

**Comment by mhwheeler** [comment]
+1

**Comment by taromero** [comment]
+1. Meteor support for Node's coverage tools (`istanbul`, `blanket`, etc.) would be great.

I'm not sure why running `istanbul node main.js` on my bundled app doesn't work (I only get repors for 3 files: `mini-files.js`, `boot.js` and `boot-utils.js`.

Absence of code coverage tools is one of the things that makes Meteor not suitable for some large projects.

**Comment by craigbennett1981** [comment]
+1

**Comment by serut** [comment]
I'm the author of the package [meteor-coverage](https://github.com/serut/meteor-coverage), and i think this issue can be closed. It's not mandatory to implement coverage inside Meteor if you do not want to _instrument_ 100% of the server code.

> I'm not sure why running istanbul node main.js on my bundled app doesn't work (I only get repors for 3 files: mini-files.js, boot.js and boot-utils.js.

These 3 files are imported using the default _import_ that you normally use in a nodejs project. But Meteor loads all others dependencies (I mean server dependencies, the client code is another story) by using fs.readFile and [vm.runInThisContext(code[, options])](https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options). Istanbul can handle such import, but you need to provide the corresponding option: _--hook-run-in-context_.

**Comment by rws-github** [comment]
+1 for coverage on `meteor test ...`

**Comment by HugoHeneault** [comment]
Code coverage would be awesome...

**Comment by hwillson** [comment]
I think it's safe to assume there won't be much further development done on TinyTest (in terms of enhancements and/or functionality). While TinyTest is still used extensively within the Meteor codebase, [better meteor testing options](https://guide.meteor.com/testing.html) are now available. As far as code coverage with Meteor goes in general, as mentioned in https://github.com/meteor/meteor/issues/4518#issuecomment-218208431 external code coverage tools can be integrated with Meteor apps successfully (see [lmieulet:meteor-coverage](https://atmospherejs.com/lmieulet/meteor-coverage) for a working example).

Closing this issue as part of the on-going old issue cleanup process. Thanks for posting this originally!
