### ISSUE TITLE
meteor publish-for-arch isn't working correctly for os.windows.x86_32

### ISSUE THREAD

**Issue by vsivsi** [meteor/meteor#4521]
Hi, I'm the author of the [vsivsi:file-collection](https://atmospherejs.com/vsivsi/file-collection) Atmosphere package, and this package has a native code dependency through its use of the mongodb 2.0.x driver and the underlying performance critical bson(-ext) npm package.

Around the time of the release of Meteor 1.0.5 I received an issue (https://github.com/vsivsi/meteor-file-collection/issues/35) on my package's repo from members of the MDG asking me to "Please publish your package for Windows!"  

I promptly did as was requested and began publishing each new version using:

``` bash
meteor admin get-machine os.windows.x86_32
# Now on windows...
meteor publish-for-arch vsivsi:file-collection@<new_version>
```

The first time I did this on March 26th (vsivsi@file-collection@1.0.5) using what must have been METEOR@1.1-rc.0, the published package EJSON (from `meteor show vsivsi:file-collection --ejson`) includes:

``` json
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os.windows.x86_32"
      ]
```

However, each subsequent release of file-collection, published with METEOR@1.1.0.2, shows something different:

``` json
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os"
      ]
```

Notice that the `"os.windows.x86_32"` list entry has been replaced by simply `"os"`.

Note that there is no indication in the build on the Meteor build farm Windows box that anything has gone wrong with the build.  The tail of my most recent `publish-for-arch` on Windows from today is:

```
<snip>

tracker                 added, version 1.0.7
ui                      added, version 1.0.6
underscore              added, version 1.0.3
vsivsi:file-collection  added, version 1.1.2
webapp-hashing          added, version 1.0.3                                 
Please log in with your Meteor developer account. If you don't have one,
you can quickly create one at www.meteor.com.                           
Username: vsivsi                                                        
Password:                                                               
Published vsivsi:file-collection@1.1.2.                                                        
C:\Windows\system32>exit      
```

So something has changed in the `publish-for-arch` Win32 build environment since that first build I did on March 26th. And it seems to matter, because I'm getting issues on my project from Windows users who are getting warnings that the native BSON extensions aren't being loaded (e.g. https://github.com/vsivsi/meteor-file-collection/issues/57).

Anyway, I'm not a current Windows user or developer (haven't been since the XP days, over 10 years ago), so my ability and motivation to try to troubleshoot this for these users are both highly limited.

You should be able to clearly see this issue by running `meteor show vsivsi:file-collection --ejson` and inspecting the output for each version I've published since v1.0.5.

Any help in resolving this will be most appreciated.

**Comment by stubailo** [comment]
I looked in the package database, and the Windows build is simply not there.

That indeed looks like it could be a bug. We will investigate more deeply as soon as we can, hopefully this doesn't happen to other packages as well.

**Comment by stubailo** [comment]
OK, some more information from @glasser:

1. It's possible that the Windows binary version just failed to build, and a package was published that has no binary dependencies (that's why the architecture is simply `os` - it would work on any operating system).
2. You can access the BSON library through the newly exposed `MongoInternals` namespace on the `mongo` package, as mentioned here: https://github.com/meteor/meteor/blob/devel/History.md#other-bug-fixes-and-improvements-2

So it might not be a bug during publishing, but just some artifact of building that NPM module on Windows.

**Comment by stubailo** [comment]
More details: the place to access the BSON stuff is: `MongoInternals.NpmModules.mongo.module.BSONPure` and `MongoInternals.NpmModules.mongo.module.BSONNative`

**Comment by vsivsi** [comment]
Hi @stubailo, thanks for the updates.  

I can verify that the Win32 build worked successfully for version 1.0.5 of my package. See: https://github.com/vsivsi/meteor-file-collection/issues/57#issuecomment-109690118  It has only been subsequent builds that aren't working. At a minimum there is a bug in the process here in that there is no indication from the build on the Windows machine that anything is going wrong.

This package uses node streams2 style streams to get proper flow control when moving around data for large (potentially multi-GB) files, and only the mongodb 2.0.x node.js driver supports Streams2. Unfortunately the Meteor MongoInternals aren't any help for me because my package requires the newer mongodb driver (Meteor still uses mongodb 1.4.x) so I can't safely mix and match parts. My dependency on the new driver comes via the npm [gridfs-stream](https://www.npmjs.com/package/gridfs-stream) package. Anyway, the minute Meteor updates to the 2.0.x mongodb driver, I will no longer need `publish-for-arch` but in the meantime I'm stuck with it.

Also, it looks like Meteor itself currently disables the native bson-ext C++ extensions from its own mongodb driver, which would be a big performance penalty on a busy server:  https://github.com/meteor/meteor/blob/master/packages/mongo/package.js#L16

**Comment by glasser** [comment]
Yes, but bson-ext is an optional dependency of bson (https://github.com/mongodb/js-bson/blob/master/package.json#L18) which means that if there's any error at all building bson-ext (eg, maybe the Windows machine you're on doesn't have compilers configured correctly?) bson will still build anyway without it. Presumably this is what happened when you publish-for-arch'd on Windows?

**Comment by vsivsi** [comment]
@glasser  Correct. Except the Windows machine I'm on is Meteor's own build box accessed via `meteor admin get-machine os.windows.x86_32`. It used to work fine (my build 1.0.5 of vsivsi:file-colleciton) but now it doesn't. And it's not giving any indication that anything is wrong or what that might be. Using the fallback JS version of the bson lib is extremely suboptimal for a library that is routinely accessing 2-8MB mongo documents with binary blobs in them. I haven't benchmarked the difference, but even with the C++ extensions the bson processing is the largest processing component of streaming large files.

**Comment by vsivsi** [comment]
@stubailo Any progress on this? I continue to get new issues reported about this problem, and given that I can't realistically debug and/or fix Meteor's own Windows build servers, I'm at a loss on how to proceed. I really don't want the answer to be "my package can't fully support Windows, because Meteor..."

**Comment by hwillson** [comment]
Reading over this issue (and all related issues), it looks like the original problem has been resolved (details in https://github.com/vsivsi/meteor-file-collection/issues/57). The problem wasn't fixed by anything here though, so there could still be a bug lingering within Meteor's Windows build farm. That being said, given the age of this issue, I'll close it for now. If anyone runs into this problem again, please post back with the details, and I'll be happy to re-open it. Thanks!
