### ISSUE TITLE
Unable to Deploy or Update Meteor Application

### ISSUE THREAD

**Issue by ClaudeBotes** [meteor/meteor#4524]
Hi,

I'm pretty new to meteor and web development in general. Over the weekend I had some issues downloading packages. I knew the issue was due to my internet connection as in China not much is allowed...so I stumbled across this page (https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy) which covers how to use Meteor behind a proxy...

Not really understanding this article 100% or what it does, I ran the commands kind of blindly with some values, and now being back at the office, at on a connection where I was able to update packages and deploy without any issues, I am no longer able to do so.

Deploying or trying to update meteor, I get an error saying: Connection error (UNABLE_TO_VERIFY_LEAF_SIGNATURE)

So I think I might screwed up my HTTP and HTTPS variables...and because I don't know anything about environment variables, and what the article at (https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy) means, I am unable to revert to a state where I can continue to use meteor and deploy my application.

Can anyone please help me reset these variables to a state where I can continue with development please?

I work on a mac, so some guidance on terminal and setting variables would go a long way. 

Thanks to anyone who can help me out.

**Comment by coffee-mug** [comment]
Hi ! I am not an expert at Meteor, nor using it behind a proxy but here are two things you could look at : This SO post explaining several tricks to get solve your 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'  http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

Apparently it's just a certificates problem, so there may be something going wrong with your proxy over HTTPS (not downloading all the required certificates, ... ) 

Or, if you are on Linux/Mac you could type in a command line 'unset HTTP_PROXY' and 'unset HTTPS_PROXY', to revert back.

**Comment by ClaudeBotes** [comment]
You are a LEGEND!

Thanks.
Running 'unset HTTP_PROXY' and 'unset HTTPS_PROXY' fixe the issue.

Thanks a million!

**Comment by ekatek** [comment]
Sounds like you got it under control! Closing the issue.
