### ISSUE TITLE
Add ability to install a specific meteor version

### ISSUE THREAD

**Issue by caruccio** [meteor/meteor#4526]
Current installer doesn't allow to select an specific version of meteor.
It would be nice to have something like:

    curl https://install.meteor.com/?version=0.7.1.1 | sh

This is due to restrictions on environments regarding nodejs available version.

**Comment by mquandalle** [comment]
The script you install with  `curl ... | sh` isn't attached to any particular version. Meteor can download and run new version of core-packages and the build tool if the application you run needs them.

You can also use the `--release` option, eg `meteor create testapp --release 1.0.0`.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I have a question though - given that Meteor can run old versions by pinning your app to an old version or using `meteor --release 0.7.1.1`, why do you need this feature?

Also, you were talking about "This is due to restrictions on environments regarding nodejs available version." The Meteor command-line tool comes with its own internal version of Node. Which environment, or restriction on available version, are you referring to here?

**Comment by caruccio** [comment]
@stubailo @mquandalle My bad :( Didn't known that. Thanks for your feedback!

**Comment by RobertLowe** [comment]
@stubailo Can we reopen this? My buildpack on heroku started to fail to build and the only difference is a newer version of the build tool. It would be nice if we could lock/override the build tool down with a specific version, there's no way to override `RELEASE` 

Could we maybe do:

    # Default to latest release, or let user override by setting `RELEASE` before running script
    if [ -z "$RELEASE" ] ; then
      RELEASE="1.3.2.4"
    fi


😩

**Comment by abernix** [comment]
@RobertLowe See #6915.  Maybe post your specific problem there as well if you think it's relevant.  Sounds like potentially bigger issue.

**Comment by rregil** [comment]
@RobertLowe just use sed before sending your output to sh:

    curl https://install.meteor.com/ | sed 's/1.4/1.3.3.1/' | sh

This changes the current 1.4 to 1.3.3.1 release.

**Comment by RobertLowe** [comment]
@rregil totally legit, but you can also append `?release=x.x.x` now, see: https://github.com/meteor/meteor/issues/6915#issuecomment-235344516

Cheers

**Comment by Alino** [comment]
this does not work for me
```
root@9f3826972b9e:/# curl https://install.meteor.com/ | sed 's/1.4/1.2.1/' | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7592    0  7592    0     0   5845      0 --:--:--  0:00:01 --:--:--  5848
Downloading Meteor distribution

curl: (22) The requested URL returned error: 404 Not Found
Retrying download in 5 seconds...

```

**Comment by abernix** [comment]
@Alino just use the recommendation above your comment because the `sed` command regex from @rregil in your example is riddled with potential problems (both before and after your attempt to use it) ;)

**Comment by Alino** [comment]
@abernix still the same even if I am using this
```curl https://install.meteor.com/ | sed 's/1.4/1.3.3.1/' | sh```

I am trying it inside fresh docker container with latest ubuntu. Does not work.
I tried it also on OS X and same thing happens.

And no, it's not problem with connection because this works:
```curl https://install.meteor.com/ | sh```

**Comment by Alino** [comment]
I am really stuck now, I cannot build my docker image with my meteor app which is using release 1.2.1.

Does anyone have any workaround how can I force download older meteor version?
Installing newest version and then running ```meteor --release 1.2.1``` is not an option for me 😢

**Comment by abernix** [comment]
I'm sure it doesn't.  That's why I'm telling you to  add `?release=VERSION–YOU-WANT` after `install.meteor.com/` as the comment above states. 

That sed regex you're trying  to use would only work while the file was still only using "1.4" which it isn't.  Now it's replacing the 1.4 in "1.4.0.1" with 1.3.3.1 and ending up with "1.3.3.1.0.1".

**Comment by Alino** [comment]
ok now it works, thank you for explanation, you saved my day.

**Comment by zweicoder** [comment]
@abernix I'm doing `curl https://install.meteor.com/?release=1.2.0 ` but getting `curl: (22) The requested URL returned error: 403 Forbidden`. Anything I did wrong?

**Comment by mttstt** [comment]
How download old Windows version ? Thanks

**Comment by mttstt** [comment]
No way ?

**Comment by abernix** [comment]
@mttstt For Windows, it's recommended to use [the latest installer](https://install.meteor.com/windows).  Your project will always run with the version of Meteor it was built with.  This includes downloading the appropriate version of Meteor and installing it, if it's not available on your system already.

If you want to create a new project with an older version, you can use the `--release` flag.  For example, `meteor create --release 1.3.4.1 app-name`.  To see a full list of Meteor releases, try the `meteor show METEOR` command.

Hope this helps.
