### ISSUE TITLE
Error: write EPIPE when installing Android SDK

### ISSUE THREAD

**Issue by isbkch** [meteor/meteor#4530]
I'm on Meteor **1.1.0.2** Mac Yosemite, and I have this error when I try to install the android SDK for Meteor

$ meteor install-sdk android
Installing Android bundle
✓ A JDK is installed
Installing Android Platform tools

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)

From what I found on the web, it's an imagemagick related problem. But I don't see how this can help in my case since I'm not really using imagemagick.

Also I remove ~/.meteor and reinstalled Meteor but still got same issue

**The -- verbose command showed the following:**

Installing Android bundle
% Running script /Users/isbkch/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/ensure_android_bundle.sh

Running command USE_GLOBAL_ADK= METEOR_WAREHOUSE_DIR=/Users/isbkch/.meteor  bash
/Users/isbkch/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/ensure_android_bundle.sh

✓ A JDK is installed
Using (built-in) Android SDK at /Users/isbkch/.meteor/android_bundle/android-sdk
Installing Android Platform tools
Using (built-in) Android SDK at /Users/isbkch/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /Users/isbkch/.meteor/android_bundle/android-sdk

Running command
PATH=/usr/local/openssl/bin:/Applications/XAMPP/xamppfiles/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/DOSSIER/adt-bundle/sdk/platform-tools:/DOSSIER/adt-bundle/sdk/tools:/usr/share/ant/bin:/Users/isbkch/.meteor/android_bundle/android-sdk/tools:/Users/isbkch/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/Users/isbkch/.meteor/android_bundle  /Users/isbkch/.meteor/android_bundle/android-sdk/tools/android update sdk
-t platform-tools --all -u

**I started running the commands one by one and this one gave an error**

ANDROID_SDK_HOME=/Users/isbkch/.meteor/android_bundle  /Users/isbkch/.meteor/android_bundle/android-sdk/tools/android update sdk  -t platform-tools --all -u

-bash: /Users/isbkch/.meteor/android_bundle/android-sdk/tools/android: No such file or directory

**so I downloaded the android SDK and copied it it to the right folder** 
/Users/isbkch/.meteor/android_bundle/android-sdk/

But Meteor keeps deleting it everytime I run the install-sdk command

**Comment by ekatek** [comment]
Thank you for your report! We have tried to replicate this (and fixed another bug in the process), but are unable to do so. We will keep a lookout and try to get this fixed in the future.

**Comment by nspangler** [comment]
@isbkch I am having the same issue. Were you eventually able to come up with a solution?

**Comment by isbkch** [comment]
I couldn't really find a solution, I had to postpone any Android related tasks for now

**Comment by nspangler** [comment]
@isbkch I figured it out, at least what was causing my problem. I was behind a proxy, which for some reason didn't allow the `Installing Android Platform tools`  step to complete. Once I jumped on a different network, it worked.

**Comment by ChrisCinelli** [comment]
I keep having the same problem =(

    $ meteor install-sdk android
    Installing Android bundle
    ✓ A JDK is installed
    Installing Android Platform tools

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:905:11)
        at Object.afterWrite (net.js:721:19)
