### ISSUE TITLE
Windows build should not set read-only attribute

### ISSUE THREAD

**Issue by fongandrew** [meteor/meteor#4532]
On a fresh Meteor project on Windows, `meteor build` sets the read-only attribute on the resulting build directory and its subdirectories and its files. This can be annoying if you try to delete the directory from the command line or Powershell (oddly enough, explorer.exe seems to just ignore the flag). It also makes it more difficult to integrate Meteor into cross-platform NodeJS-based tools that aren't aware of Windows read-only attributes.

Reproduction steps, using Meteor 1.1.0.2 on Windows 8.1:
- `meteor create myapp`
- `cd myapp`
- `meteor build --directory ..\build`

As a work-around, manually unsetting the read-only flag is fairly simple: `attrib -r build/*.* /s`

**Comment by stubailo** [comment]
Interesting! We did this on Windows because that's the way `meteor build` works on Linux/Mac. However, it's possible that making files read-only creates a lot more hassle on Windows and isn't worth it. Can you elaborate more on this point:

> It also makes it more difficult to integrate Meteor into cross-platform NodeJS-based tools that aren't aware of Windows read-only attributes.

I'm curious what the symptoms are, and what tools you are referring to. That would be the most compelling reason for me to remove this behavior.

**Comment by fongandrew** [comment]
Well, in my case, I'm trying to use https://github.com/frozeman/meteor-build-client to generate a standalone Meteor client that I can run with Electron Shell. The process involves removing some of the server-specific files from the bundle the build command generates.

**Comment by avalanche1** [comment]
I agree. I work in Webstorm IDE and cannot add or rename files\folders in root dir via IDE means because IDE sees root dir as 'locked'

**Comment by hwillson** [comment]
Judging by the lack of activity and/or +1's on this issue in over 1.5 years, I think we can assume this is either no longer an issue, or developers have found suitable workarounds (I know people are still deploying on Windows! 🙂). Closing for now - happy to re-open if anyone feels differently!
