### ISSUE TITLE
Allow packages in subfolders

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#4534]
I'm structuring my app using packages only and it works great. It would be even nicer if Meteor allowed to create packages in subfolders.

At the moment, this is what I'm doing:
```
packages/
  app-base/
  app-base-ui/
  app-users/
  app-users-ui/
```

For structuring it would be much nicer to have this:
```
packages/
  platform/
    app-base/
    app-users/
  ui/
    app-base/
    app-users/
```

The downside is that even if Meteor just skipped the levels without a `package.js` file, there would now be two `app-base` packages; so support for something like `api.use('platform/app-base')` would be needed.

Let me know what you think, maybe it's just too much work for too little effect. I'm interested in hearing other opinions, especially from people who structure their apps this way, too. @SachaG? :wink:

**Comment by Slava** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).


A nested folder structure can be confusing for the reader the same way it can be helpful. I don't think this is a feature that would be super useful for more general case of storing a flat list of packages.

As a workaround you can go and structure your packages into nested folders and then use the `PACAKGES_DIR` env variable and set it to a comma separated list of paths.

**Comment by SachaG** [comment]
I haven't really felt the need for that, personally. The flat file structure works for me.

**Comment by zimt28** [comment]
I guess the workaround is enough here, so I'll close this. Thanks for your responses!
