### ISSUE TITLE
"Prototype mutation" warning in Firefox...

### ISSUE THREAD

**Issue by justinpeake** [meteor/meteor#4536]
I'm getting the following warning in Firefox 38.0.5.

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the       
    object with the correct initial [[Prototype]] value using Object.create

I've narrowed it down to something having to do with the snippet 
    ` return BlogPosts.find( { name : "Hello" }, { content : 1} ) `
in my .js file.

What could this mean exactly?  I'm not getting the warning in Chrome.

**Comment by Slava** [comment]
Looks like this comes from this line: https://github.com/meteor/meteor/blob/9adcfd32dc88abf9e9c70bda62aca655cf8b2631/packages/meteor/errors.js#L16

Notably, this is done in a piece of code specifically for Firefox, so I assume it is OK. The warning is valid though, modifying the `__proto__` property is known to be unrecommended for modifications: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto.
