### ISSUE TITLE
[bug] Running "meteor --help" in an app with an empty .meteor/release file should still show help.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4537]
Instead, running `meteor --help` results in

```
 ❯ meteor --help
Problem! This project has a .meteor/release file which is empty. The file should either contain the release of Meteor that you want to use, or the word 'none' if you will only use the project with unreleased checkouts of Meteor. Please edit the .meteor/release file in the project and change it to a valid Meteor release or 'none'.
```

**Comment by glasser** [comment]
The help that is printed depends on what release you're running, so this is working as intended.

**Comment by trusktr** [comment]
Well, that isn't very.... helpful. lol

**Comment by NDMTom** [comment]
Having this same issue, can't seem to find an answer anywhere.

$ cd simple-todos
$ meteor
Problem! This project has a .meteor/release file which is empty. The file
should either contain the release of Meteor that you want to use, or the word
'none' if you will only use the project with unreleased checkouts of Meteor.
Please edit the .meteor/release file in the project and change it to a valid
Meteor release or 'none'.

@trusktr did you ever find a solution?

**Comment by trusktr** [comment]
@NDMTom I don't quite remember, but I think I just added a release into the `.meteor/release` file. Have you tried that?
