### ISSUE TITLE
Android emulator acceleration is not installed ubuntu 14.04 x64

### ISSUE THREAD

**Issue by fleple** [meteor/meteor#4539]
On meteor install-sdk android, i get only.
I tried  the link bellow and it still doesn't work 

✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
✓ Found Android Build Tools                   
✓ Found Android 19 API                        
✓ Found suitable Android x86 image            
✓ 'meteor' android virtual device (AVD) found 
✗ Android emulator acceleration is not installed
  (The Android emulator will be very slow without acceleration)
Platform requirements not yet met             
Please follow the instructions here:          
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux#haxm

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.
