### ISSUE TITLE
Cordova build pointing to a server with a 302 redirect

### ISSUE THREAD

**Issue by joaopiopedreira** [meteor/meteor#4541]
Hi,

Have a meteor-cordova app in production for months now and it all works fine. When I build my cordova app, I use ... --server http://myIPAddress (myIPAddress is just a VW on AWS)

Recently, I changed my domain to another registrar and tried the following:

    meteor build ../../myAppPath --server http://myapp.mydomain.com

myapp.mydomain.com has a 302 redirect to myIPAddress.

When I do so, the app doesn't connect to the server and it keep "waiting..." (Meteor.status()).

Is there anyway to tell Meteor build to follow a redirect?

Many thanks.

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
