### ISSUE TITLE
package.js - add documentation for debugOnly

### ISSUE THREAD

**Issue by hontas** [meteor/meteor#4543]
I've seen packages that use debugOnly but theres nothing in the documentation.
Only referenced here: [History.md#tool-changes](https://github.com/meteor/meteor/blob/9bc20650a9c9d8c0cb5ee8870edfd1bf5bf9c17c/History.md#tool-changes)

**Comment by ekatek** [comment]
Thanks for the catch! Packages marked with debugOnly are not bundled with the app in production mode. (For example, this option is used by testing frameworks -- you might not want to deploy an app with a giant 'passing some tests' button in the corner).

**Comment by abernix** [comment]
This is [properly described in the new Meteor docs](http://docs.meteor.com/api/packagejs.html#Package-describe).  Thanks for reporting this! :smile:
