### ISSUE TITLE
Not able to authenticate user with github if user's email is private on github

### ISSUE THREAD

**Issue by frenchbread** [meteor/meteor#4545]
We are using accounts-github package for authenticating a user on a site. Everything works if user's email is public in github profile settings. But if the email is **not publicly** visible and even if permission for email requested, this error pops up:
```
 Exception while invoking method 'login' undefined
```
Also, there is an existing question about this issue on [stackoverflow](http://stackoverflow.com/questions/24689889/the-accounts-github-package-is-causing-my-meteor-user-to-have-a-null-email/24692465#24692465) which might be helpful to review.

**Comment by anubhav94** [comment]
Good point, we should probably be doing something similar to our Google/Facebook packages where we have a default scope of the 'user:emai' and then do a second round trip as seen here: https://developer.github.com/v3/users/emails/. Pull requests welcome!
