### ISSUE TITLE
Error deploying application: Connection error (read ECONNRESET)

### ISSUE THREAD

**Issue by kalaskar** [meteor/meteor#4554]
While deploying my app (using the command, meteor deploy my_app_name.meteor.com), I got "Error deploying application: Connection error (read ECONNRESET)". I reduced the Privacy settings to Low and then my app got deployed successfully. (windows 8)
1. Open Internet options
2. Privacy tab
3. Reduced the slider to Low

**Comment by ekatek** [comment]
ECONNRESET seems like we lost contact with the server. Sometimes that's intermittent due to flaky wireless or a server going down. Might be something else in your case, but it sounds like it got fixed for now?

**Comment by laosb** [comment]
Meteor Free Hosting was discontinued. Closing.
