### ISSUE TITLE
"Mongo.Collection.prototype._validatedInsert" should return id

### ISSUE THREAD

**Issue by raix** [meteor/meteor#4555]
`Mongo.Collection.prototype._validatedInsert` should return id?
https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L978

**Comment by glasser** [comment]
What problem does this cause?

**Comment by raix** [comment]
I stumbled across this while working on a package [dispatch:run-as-user](https://github.com/DispatchMe/Meteor-run-as-user)

We [work around](https://github.com/DispatchMe/Meteor-run-as-user/blob/master/lib/collection.overwrites.js#L41-L42) it - but it was unexpected that inserts wasn't returning when both update and remove does.

[In collection methods](https://github.com/meteor/meteor/blob/85ca501b7cf53df31e634fe70f5ce542c75298c7/packages/mongo/collection.js#L877) returns the value for inserts, those would always be undefined instead of returning the id.

I might cause an issue, when reading the [code](https://github.com/meteor/meteor/blob/85ca501b7cf53df31e634fe70f5ce542c75298c7/packages/mongo/collection.js#L517-L518) it will return `insertedId` if found otherwise the id from the call / `undefined`
