### ISSUE TITLE
[idea] GitBash (msysgit) for Windows build machines.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4556]
That'd be nice. https://msysgit.github.io/

**Comment by stubailo** [comment]
This is a great idea! First, we have to get Meteor to run inside Git Bash though: https://github.com/meteor/windows-preview/issues/96

**Comment by hwillson** [comment]
Just a quick FYI - the previously linked to "running Meteor in Git Bash" issue has been moved to meteor/meteor#4938.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bidea%5D%20GitBash%20(msysgit)%20for%20Windows%20build%20machines.&body=Migrated%20from:%20meteor/meteor%234556) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
