### ISSUE TITLE
App Transport Security support aka apps on iOS 9 don't work

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#4560]
iOS 9 (may) force developers to use App Transport Security exclusively. I overheard this somewhere randomly so I don't know whether this is true myself. But I suspect it and have come to this conclusion:

The app running on iOS 9 will (maybe) no longer connect to a Meteor server without SSL.

This means running `meteor run ios` or `meteor run ios-device` will (probably?) no longer work.

In the app's `info.plist`, `NSAppTransportSecurity` [`Dictionary`] needs to have a key `NSAllowsArbitraryLoads` [`Boolean`] to be set to `YES` or Meteor needs to use https for its localhost server soon. (From Page 26 http://devstreaming.apple.com/videos/wwdc/2015/711y6zlz0ll/711/711_networking_with_nsurlsession.pdf?dl=1)

This is what an error may look like. Of course this is at best, a guess:

```
The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

The best possible fix is to get Meteor to use a SSL server in dev mode.

Oh the hassle! Also again, I overheard this from a loud third party.

**Comment by Omeryl** [comment]
Haha, this just had me spinning in circles for the last hour. Great catch, thanks for the current work around.

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by krishaamer** [comment]
Had the same problem. Thank you.

**Comment by nanokanato** [comment]
I also this came communication fail. Thank you.

**Comment by rlech** [comment]
had the same issue. workaround fixed it for now. thx!

**Comment by krazyeom** [comment]
There was same issue on React Native. https://github.com/facebook/react-native/issues/1563 

They just added blew code to end of Info.plist

  <key>NSAppTransportSecurity</key>
  <dict>
    
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>

**Comment by rlech** [comment]
is there a way to do this with a deploy script? its super annoying to add this 2 entries every time after a meteor reset

**Comment by stubailo** [comment]
The workaround is now published as part of 1.2-rc.14. Try it out!

**Comment by girijeshkumar2007** [comment]
From iOS 9 We can not hit API directly. Apple had added Transport Security feature that improves the security of connections between an app and web services. This feature consists of default connection that conform to best practices for secure connections. 
Connections that do not follow the requirements will fail and give “The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.” error.

So, We have to add NSAppTransportSecurity dictionary in your .plist file and the NSAllowsArbitraryLoads key to YES under it to turn off transport security.

For more detail read Apple document https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html

**Comment by sebastianconcept** [comment]
Day saved! Thank you @Tarang !

**Comment by stevoPerisic** [comment]
This is still an issue. I am having to update the info.plist before running the app on the device. Here is a stackoverflow http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

**Comment by wilguevara** [comment]
what about this https://www.npmjs.com/package/cordova-plugin-transport-security?

**Comment by dairdr** [comment]
It works!

**Comment by tyagi15aug** [comment]
Thanks.. Your post helped me with my ionic and Node.js app.

**Comment by priyasaini** [comment]
What a relief. Thanks.. Saved my time.
