### ISSUE TITLE
Case-sensitive comparison of email addresses

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4561]
Now accounts-password allow to create two different accounts for _name@domain.com_ and _Name@domain.com_. That’s a bug. We have to take emails case-insensitively.

**Comment by artpolikarpov** [comment]
There should be no security issue. Because all sensitive methods like `sendResetPasswordEmail` looks for exact matching.

**Comment by anubhav94** [comment]
Closed as a duplicate of #550. Thanks!
