### ISSUE TITLE
Stuck at the Splash Screen after update if using AUTOUPDATE_VERSION

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4562]
If you set AUTOUPDATE_VERSION and the change it, your corodva app will be reloaded as expected. But if you’ll stop the app after that it will never run again. Because container with new assets will be deleted immediately.

It happens because `__meteor_runtime_config__.autoupdateVersionCordova` and `version` in `/__cordova/manifest.json` are different.

It can be fixed by replacing piece of [/packages/webapp/webapp_server.js](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L492):

```js
        var program = {
          manifest: manifest,
          version: WebAppHashing.calculateClientHash(manifest, null, _.pick(
            __meteor_runtime_config__, 'PUBLIC_SETTINGS')),
          PUBLIC_SETTINGS: __meteor_runtime_config__.PUBLIC_SETTINGS
        };
```

...with this:

```js
        var program = {
          manifest: manifest,
          version: process.env.AUTOUPDATE_VERSION || WebAppHashing.calculateClientHash(manifest, null, _.pick(
            __meteor_runtime_config__, 'PUBLIC_SETTINGS')),
          PUBLIC_SETTINGS: __meteor_runtime_config__.PUBLIC_SETTINGS
        };
```

I know `AUTOUPDATE_VERSION` variable is undocumented, but it can be very useful. For example, with this variable you can force apps to reload only when you need to. But now there is an inconsistency between _packages/webapp/webapp_server.js_ and _packages/autoupdate/autoupdate_server.js_ that prevents using `AUTOUPDATE_VERSION` in production.

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion
