### ISSUE TITLE
Allow fuzzy versions (~0.1.0 or ^0.1.0) in Npm.depends

### ISSUE THREAD

**Issue by zardak** [meteor/meteor#4563]
Currently when specifying a fuzzy version constraint
```js
Npm.depends({
  packagename: '^0.1.0'
});
```
meteor ceases to work.

Allowing fuzzy versions would ease the maintaining of packages, as I've seen many commits solely bumping a dependency version.

**Comment by anubhav94** [comment]
Duplicate of #4355. Thanks!
