### ISSUE TITLE
Template subscriptionReady()/rendered() timing

### ISSUE THREAD

**Issue by dcworldwide** [meteor/meteor#4564]
A common requirement I have is the need to register a jquery plug-in within the rendered callback. But as i use template level subs (with the subs ready template helper), it is often the case that rendered is called before my component is rendered to the dom. Therefore i can't call the jquery constructor logic within rendered. Could this be improved somehow? 

Perhaps a renderedWithSubsReady callback?

**Comment by glasser** [comment]
I think you can implement this yourself without core changes.

```js
var renderedWithSubsReady = function (tmpl, callback) {
  tmpl.onRendered(function () {
    var templateInstance = this;
    Tracker.autorun(function (computation) {
      if (templateInstance.subscriptionsReady()) {
        computation.stop();
        Tracker.nonreactive(function () {
          callback.call(templateInstance);
        });
      }
    });
  });
};

renderedWithSubsReady(Template.foo, function () { ... })
```

**Comment by dcworldwide** [comment]
Wow thanks so much :smiley:
