### ISSUE TITLE
Allow localhost project to continue running while rebuilding the application

### ISSUE THREAD

**Issue by ChrisNLott** [meteor/meteor#4567]
FEATURE REQUEST: 

This would be so helpful with larger apps that take longer to build.

It would work very similar to how hot-code deploys work to a server. 

Keep the app running until we have successfully built the new version.

Please let me know if this is currently already possible

**Comment by glasser** [comment]
OK, this is basically talking about moving the `appProcess.stop()` call in `tools/run-app.js` to come after the next `bundler.bundle` call.  I agree that this would be an improvement, though it definitely might make the already complex control flow even harder to understand.  (Of course, just making rebuilds faster would be helpful too.)

**Comment by jasonxeno** [comment]
There seems to be a package that is making progress towards making something similar happen:

https://github.com/nucleuside/meteor-live-update/

It seems to be part of an ambitious real time IDE project, but it would be great if any of the concepts in that package could be built into the meteor core to drastically cut down on project compiling time during development.

Excerpt:

*nucleuside:live-update is a helper package which allow you to hot-push the code into your meteor app. Yup, that means no refreshes for updating your js/html.

This package is a part of Nucleus(IDE). Nucleus is an in-browser editor for collaboratively developing meteor apps in power mode. It's awesome, but at pre alpha for now. Nucleus has direct access to all the app's code right within the browser, which allow it to just hot-push it (using live-update) into the app. But when using an external editor (e.g Sublime Text), we don't have that luxury of direct access to the app. So I am writing this package as a library for hot-loading js/html code for meteor apps, and am working on a generic adapter package which would use this package and act as a standalone hot-loading solution for meteor. I'll update this readme when I am done with that package. Till then, feel free to use nucleuside:live-update for building a plugin for your editor. Here's how you can do it:*

Demo Video:
https://www.youtube.com/watch?v=Q9M2YLiF-Q4

**Comment by hwillson** [comment]
Meteor [1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142) has introduced many build tool performance improvements. As mentioned in https://github.com/meteor/meteor/issues/4567#issuecomment-112573085, a better solution to this issue is to make rebuilds faster, which 1.4.2 has definitely done. Due to the low activity and age of this issue, I'll close it for now. If you're still having issues with the latest version of Meteor, please post back and let us know. Thanks for reporting this originally!
