### ISSUE TITLE
Exceeds allowable heap size in iOS

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4568]
(Isolating a single sub-issue of #3596.) 

My Meteor Cordova app gets killed by the OS due to large memory usage. (The site also crashes mobile Safari, but sooner – at a smaller heap size, after fewer actions are taken by user.) The app isn't doing anything crazy or weird, just normal template rendering, with complexity on the order of the Twitter app. For more details and memory graphs, see:

http://stackoverflow.com/questions/30813443/how-can-you-control-memory-usage-in-cordova

It would great to see:
- guidelines on controlling client memory usage in Meteor.
- Blaze using less memory, if possible.

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by gadicc** [comment]
@lorensr, considering the graphs in the SO post (on OSX Chrome), I'm not sure if this is necessarily Cordova related.  If memory usage is only going up, it seems more like a memory leak.  Although I'm at a bit of a loss how you manage to free so much memory from manually collecting garbage (I guess I need to read up on what exactly Chrome does there).

Any chance it's https://github.com/meteor/meteor/issues/4289 with the bug itself explained in https://github.com/meteor/meteor/commit/583d77e943949de003616a4b3e55545ede53bc7c?  Which I think would affect routers too, depending on how they're built.  Or in short, does the latest checkout from devel perform better?  (I'm pretty sure it will be in the next release)

If not, a cloneable repro would be great for when someone can look at this more in depth.

**Comment by lorensr** [comment]
I don't think it's Cordova related. It's just more of a problem on phones, where you get killed, versus desktop, where usually have more memory, and just slows w/ swap rather than killed.

I don't think it's a leak – don't think Chrome manual GC frees a different amount from what JS engines in general can free? In the case of that graph, I believe the browser just didn't decide to do so before the point at with I triggered it. And on iOS, I see that if I leave app idle for a while, it will eventually GC, but if I do a lot of rendering without breaks, it doesn't take a break for GC before the point at which it gets killed.

I'm sorry, it's a closed-source app, so I'd have to make a new complex app to reproduce.

**Comment by lorensr** [comment]
Note how in #4289 he hits GC button before end, but blue line stays at top.

**Comment by gadicc** [comment]
Yes, you're absolutely right, forgot he was also doing manual collection also -- the graphs do indeed show these are different issues.  I'm still wondering about the node count only growing though?

**Comment by lorensr** [comment]
Yeah, I don't know what's up with that. Here's a simple IR app w/ layoutTemplate – when I hit GC @ end, both heap and nodes/listeners go to baseline.

![image](https://cloud.githubusercontent.com/assets/251288/8625229/68000376-270b-11e5-8d0d-0c565ab42c3f.png)

In my app, the heap goes all the way down, but a lot of nodes and listeners stick around:

![image](https://cloud.githubusercontent.com/assets/251288/8625259/a2fbca28-270b-11e5-87f4-1929c88e5bf3.png)

I can't imagine what's special about my app that might cause that to happen. Any ideas on how to debug why it happens? :)

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
