### ISSUE TITLE
[bug] "let" not handled as expected, overrides variable in outer scope.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4571]
I'm [trying this](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=let%20guard%20%3D%20new%20WeakMap()%3B%0Alet%20singleton%20%3D%20null%0A%0Aclass%20Bar%20%7B%0A%20%20constructor%20(...args)%20%7B%0A%20%20%20%20var%20blah%20%3D%20%22asdfasdf%22%0A%20%20%20%20%0A%20%20%20%20if%20(!singleton)%20%7B%0A%20%20%20%20%20%20let%20blah%20%3D%20%22blah%22%0A%20%20%20%20%20%20singleton%20%3D%20this%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20let%20blah%20%3D%20%22blahblah%22%0A%20%20%20%20%20%20%2F%2F%20return%20singleton%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20console.log(%22blah%22%2C%20blah)%0A%20%20%20%20console.log(args)%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20private%20properties.%0A%20%20%20%20guard.set(this%2C%20%7Bfoo%3A%20'bar'%7D)%0A%20%20%7D%0A%7D%0A%0Aexport%20class%20Foo%20extends%20Bar%20%7B%0A%20%20constructor%20(...args)%20%7B%0A%20%20%20%20super(...args)%3B%0A%20%20%20%20guard.set(this%2C%20Object.assign(guard.get(this)%2C%20%7Blorem%3A%20'ipsum'%7D))%0A%20%20%7D%0A%20%20%0A%20%20someMethod()%20%7B%0A%20%20%20%20console.log(guard.get(this).lorem)%3B%0A%20%20%7D%0A%7D%0A%0Avar%20foo%20%3D%20new%20Foo(1%2C2%2C3)) in Babel's "Try it out". In the constructor of the `Bar` class, you see

```js
    var blah = "asdfasdf"
    
    if (!singleton) {
      let blah = "blah"
      singleton = this
    }
    else {
      let blah = "blahblah"
      // return singleton
    }
    
    console.log("blah", blah)
```

which results in

```js
  var blah = "asdfasdf";

  if (!singleton) {
    var blah = "blah";
    singleton = this;
  } else {
    var blah = "blahblah"
    // return singleton
    ;
  }

  console.log("blah", blah);
```

so the `blah` in the scope outside of the conditional is getting changed!

**Comment by kaiquewdev** [comment]
Variables was renewed just inside of vm, function or similar function types context.

**Comment by kaiquewdev** [comment]
var blah = "asdfasdf";

  function changeBlah() { var blah = "blah"; }

  if (!singleton) {
    changeBlah();
    singleton = this;
  } else {
    changeBlah();
    // return singleton
    ;
  }

  console.log("blah", blah);

**Comment by kaiquewdev** [comment]
`var` or `let` in this case not is relevant, because what's is more import to note is the execution
context who was the same, so the reference was changed with `var`, `let`, `const` or not.

**Comment by trusktr** [comment]
@kaiquewdev A `let` expression inside a block scope isn't supposed to modify the variable of the outerscope, right?

**Comment by kaiquewdev** [comment]
Yes because it's the conditional blocks not have garbage collection.
So the context is the same inside or outside in this case.

**Comment by glasser** [comment]
I'm not sure what this has to do with Meteor. Did you mean to file it at the Babel repository?

**Comment by trusktr** [comment]
@glasser Wow, haha. Yes, I meant this for Babel. I had little sleep and woke up early.
