### ISSUE TITLE
Meteor does not run on non-glibc Linuxes (Alpine, Void, etc)

### ISSUE THREAD

**Issue by prinzdezibel** [meteor/meteor#4573]
**_2 Upvotes**_ docker run -t -i gliderlabs/alpine sh -c ' apk-install bash curl && curl https://install.meteor.com/ | /bin/bash && meteor'

yields

```
/root/.meteor/meteor: line 133: /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: No such file or directory
```

**Comment by glasser** [comment]
OK, I'm not sure if this is intended to be a supported platform (eg, we ship binaries and I don't know if musl libc is ABI compatibile with other libcs) but we can track this here anyway.

**Comment by lukeadams** [comment]
I tried linking Node to the "apk add"-ed openssl and zlib libraries, but it still fails. I modified the build script by adding 
```--shared-openssl-includes=/usr/include/openssl --shared-openssl-libpath=/usr/lib --shared-zlib --shared-zlib-includes=/usr/include --shared-zlib-libpath=/usr/lib```
to line 20 of [scripts/build-node-for-dev-bundle.sh](https://github.com/meteor/meteor/blob/devel/scripts/build-node-for-dev-bundle.sh). It still failed (all Node or OpenSSL related). I tried using the system libuv too, but that didn't work.
Obviously you do have to install all dependencies for Node to compile. ```apk add gcc g++ make automake```... among others.

I would love to see this working.

**Comment by kop** [comment]
+1 to this issue.

Alpine is currently very popular in Docker world because of it's miniature size. Dockerized Meteor images built on Ubuntu base are resulting ~1Gb size... Having this reduced with the help of Alpine would be really nice.

**Comment by ellisonleao** [comment]
+1

**Comment by mrdomino** [comment]
FWIW statically linking meteor would solve this problem. You could even statically link it from a musl-based image for a smaller binary...

**Comment by abernix** [comment]
Currently Meteor simply uses the prebuilt `node` bundles from nodejs.org – it does not build them itself.  I'm not sure if they provide binaries linked against a musl libc.

But just to be clear, this should only affects the ability to run the `meteor` tool, not the ability to deploy a Meteor-built app to `musl`-based distros.  You could, for example, develop a Meteor app on a supported distro (currently Glibc Linux, OS X and Windows), bundle it on that system (with `meteor bundle`) then run the built bundle (which is just a `node` application) using a musl libc `node` binary.  The [mhart/alpine-node](https://hub.docker.com/r/mhart/alpine-node/) docker image would probably work to run it?

**Comment by ckeeney** [comment]
@abernix I agree it is possible to run meteor apps, but it would be nice if my CI environment could build the bundle in a docker container.

**Comment by abernix** [comment]
@ckeeney There is nothing stopping you from running `meteor build` in a Docker image – it would just need to be a `glibc`-capable distribution.  You could then ship the resulting `node` bundle to a small Alpine docker image like I suggested above.

Honestly, I find the `alpine` distro to be ideal for those wanting a very small, slim, production Docker image.  That's a fantastic quality, but once you bring the `meteor` tool itself into the picture, the image is going to become larger due to the power and footprint of the tool itself.  This is likely unavoidable.  To further complexity, most users run tests in the build environment which require additional large dependencies (such as PhantomJS, for example).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20does%20not%20run%20on%20non-glibc%20Linuxes%20(Alpine%2C%20Void%2C%20etc)&body=Migrated%20from:%20meteor/meteor%234573) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
