### ISSUE TITLE
The order of onRendered and onload depends on browsers.

### ISSUE THREAD

**Issue by y-ich** [meteor/meteor#4575]
On Chrome on OS X, onload event for window is triggered after onRendered events of templates of a page.
On IE11, the order is reversed.

This browser dependency causes side-effects, for example, carousels in Bootstrap do not start when the page is loaded on IE11.

**Comment by glasser** [comment]
Interesting.  So the bootstrap carousels are triggered by onload and thus they don't work?  Does bootstrap provide a way to start carousels for things added later?

That said, it would really be helpful if you provided a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.  Ideally, a simple reproduction just showing the different event order, and another one showing how it breaks carousels?

**Comment by y-ich** [comment]
I made reproduction code that also includes workaround.
https://github.com/y-ich/onload-onrendered-order

**Comment by hwillson** [comment]
I've tested the supplied reproduction, and can get the Bootstrap carousel to fire properly in both Chrome and IE 11, without using your supplied workaround. Yes `onload` and `onRendered` are fired in different orders by Chrome and IE 11, but in practice the impact of this should be fairly minimal. Blaze events shouldn't depend on `window` events, and vice versa.

Given the above and the age of this issue, I'll close this off. Thanks for reporting this!
