### ISSUE TITLE
When ES6 support is realeased, will it support import/export syntax?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4578]
If so, how will it work? How will packaging for Meteor change? I'm just curious so I can better know what to work on with [rocket:module](https://atmospherejs.com/rocket/module). I want to avoid creating something if MDG is already making the same thing, and that I might be able to contribute to instead.

**Comment by glasser** [comment]
Questions like this are best posed on the [Meteor forums](https://forums.meteor.com/), not our bug tracker.

We're currently working on getting the Meteor roadmap into a publishable form, which hopefully should answer some questions like these.
