### ISSUE TITLE
MOBILE_ROOT_URL and MOBILE_DDP_URL are ignored on meteor build

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4581]
When you create initial mobile builds `MOBILE_ROOT_URL` and `MOBILE_DDP_URL` are ignored. You won’t see your setting in _application/index.html_. But in runtime server gives correct html for mobile at _/__cordova/index.html_.

I believe we should have the same behaviour both on build and in runtime.

**Comment by artpolikarpov** [comment]
Here it goes:
https://github.com/meteor/meteor/blob/devel/tools/commands-cordova.js#L319

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.

**Comment by Richie765** [comment]
I've been doing some work on a similar issue #3815. I don't think those environment variables should be used by `meteor build`. Instead they should be set before running the bundle that was generated. To specify the URL's to be used by Cordova initially, there are command-line options, `--mobile-server- and `--server`. I think the variables that you mentioned are of little use.

Take a look at #2815 for more information. If that solves this, you can close this issue.

**Comment by abernix** [comment]
@Richie765, thanks for following up on this rather old issue.  It's nice to revisit some of these and clean them up.

I tend to agree with what you're saying here and this issue hasn't received much traction.  Those variables (`MOBILE_ROOT_URL` and `MOBILE_DDP_URL`) shouldn't ordinarily be necessary to set.

@artpolikarpov Thanks for reporting this issue originally, if you feel this being closed inappropriately, please do report back and we'll be happy to reopen.  We're trying to clean up older issues that don't seem to be ongoing issues.
