### ISSUE TITLE
mongo: upsert - order of $set and $setOnInsert in modifier matters

### ISSUE THREAD

**Issue by mcbain** [meteor/meteor#4582]
The following test does an upsert where the $set modifies a field on an object added by $setOnInsert. The $set overrides the value of `abc.hello` as expected. 

```javscript
Tinytest.add('upsert - order $setOnInsert before $set works', function (test) {
  var collection = new Mongo.Collection(test.id);

  collection.update(
    {name: 'Meteor'},
    {
      $setOnInsert: {
        abc: {
          hello: 1
        }
      },
      $set: {
        'abc.hello': 33
      }
    },
    {upsert: true}
  );

  var doc = collection.findOne();

  test.equal(doc.abc.hello, 33);
});
```

When changing the order of the two modifier fields the tests fails, because the value of `abc.hello` is still 1.  

 ```javscript
Tinytest.add('upsert - order $set before $setOnInsert works not', function (test) {
  var collection = new Mongo.Collection(test.id);

  collection.update(
    {name: 'Meteor'},
    {
      $set: {
        'abc.hello': 33
      },
      $setOnInsert: {
        abc: {
          hello: 1
        }
      }
    },
    {upsert: true}
  );

  var doc = collection.findOne();

  test.equal(doc.abc.hello, 33);
});
```

**Comment by mcbain** [comment]
According to https://jira.mongodb.org/browse/SERVER-10711 it should not work at all, strange that the first test works.

**Comment by mcbain** [comment]
Does meteor maybe remove some fields from the $setOnInsert object?

This statement fails to execute in the mongodb-shell
```
 collection.update({name: 'A'}, {$setOnInsert: {name: 'B'}, $set: {name: 'C'}}, {upsert: true});
```  
But in meteor there is no error and a document with `name=C` is inserted.

**Comment by Overheatedscott** [comment]
@mcbain https://microblinkvishal.github.io/ILYw9ENuHd5dHgruezlEGVy8MekHDSwaATjOMfQ0ZD7/
