### ISSUE TITLE
Improve the ReactiveDict API before the v.1.1.1

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4583]
Before releasing v.1.1.1 it would be great if `ReactiveDict` would get an overall overhaul so that we will not issues deprecating later on. Probably the best would be that `ReactiveDict` would match [ES6 Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

**Comment by jagi** [comment]
I've already made ReactiveMap package that more or less match ES6 Map spec https://atmospherejs.com/jagi/reactive-map. I don't think that ReactiveDict should do it too because it already has different API and few more functions, however lacks of a few others.

**Comment by glasser** [comment]
Is this in reference to https://meteor.hackpad.com/Proposal-Deprecate-Session-in-favor-of-ReactiveDict-0wbRKtE4GZ9 ?  As noted at the top, we're not currently not moving forward with that proposal.

Is there a reason in particular that this needs to be done before 1.1.1?  Are there pending changes on devel to ReactiveDict?

**Comment by mitar** [comment]
> Is there a reason in particular that this needs to be done before 1.1.1? Are there pending changes on devel to ReactiveDict?

Yes. From history.md:

> ReactiveDict now has two new methods, clear and all. clear resets the dictionary as if no items had been added, meaning all calls to get will return underfined. all converts the dictionary into a regular JavaScript object with a snapshot of the keys and values. Inside an autorun, all registers a dependency on any changes to the dictionary.
