### ISSUE TITLE
A named ReactiveDict should have an API to tear down the migrated data

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#4585]
**_1 Upvote**_ The objects in question are:

``` js
ReactiveDict._migratedDictData = {};
ReactiveDict._dictsToMigrate = {};
```

From [here](https://github.com/meteor/meteor/blob/devel/packages/reactive-dict/migration.js#L1-L2).

I created a named `ReactiveDict` to keep state in one of my templates like this and for the state to be persisted on hot code reloads:

``` js
Template.myTemplate.onCreated(function () {
  this.state = new ReactiveDict('myTemplate');
});
```

If my template is re-instantiated, it will [throw](https://github.com/meteor/meteor/blob/devel/packages/reactive-dict/migration.js#L13).

For that reason I needed to `delete` the key for the migrated data `onDestroyed` in order to fix this:

``` js
Template.myTemplate.onDestroyed(function () {
  delete ReactiveDict._dictsToMigrate['myTemplate'];
});
```

**Comment by rogchap** [comment]
+1

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Yes, this does seem like a useful feature to have to prevent memory leaks.

**Comment by Amanej** [comment]
This is should be included in the documentation. It caused me alot of problems, and it still makes my code sort of bloated.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=A%20named%20ReactiveDict%20should%20have%20an%20API%20to%20tear%20down%20the%20migrated%20data&body=Migrated%20from:%20meteor/meteor%234585) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
