### ISSUE TITLE
check fails when with circular object and null

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#4587]
`check` fails when checking an object with a circular reference against a null value.

```
var foo = {};
var bar = {};
foo.bar = bar;
bar.foo = foo;
check(foo, null);
>>> Uncaught RangeError: Maximum call stack size exceeded
```

**Comment by stubailo** [comment]
This would be a great improvement to `check`. If someone file a PR I'll take a look.

**Comment by quackware** [comment]
Seems to be related to #1446 since the failure occurs when `check` attempts to `EJSON.stringify` the provided object when returning the `Match.Error`.
