### ISSUE TITLE
website meteor.com not working with IE8

### ISSUE THREAD

**Issue by aj07mm** [meteor/meteor#4592]
Im doing a research to lecture on Meteor at a college tomorrow and i got
```
LOG: Exception Tracker recompute function
```
trying to use IE8 to open www.meteor.com

**Comment by stubailo** [comment]
Filed this in our internal repo. Thanks for reporting!

**Comment by abernix** [comment]
Microsoft Internet Explorer 8 has reached it's official End of Life.  I don't believe that any steps will be taken to resolve this at this point so I'm closing this.

( I can't even open microsoft.com properly in IE8 anymore ).

https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
