### ISSUE TITLE
Stylus (or sass) variables/mixins available between packages?

### ISSUE THREAD

**Issue by jgoley** [meteor/meteor#4593]
Trying to figure out a way to create a 'global' styles package that defines global variables/mixins and brings in other style related packages (i.e. bootstrap or stylus). This stuff would become available to other new packages by adding the styles package within the new package.

**Comment by glasser** [comment]
This is basically what we're working on on the `batch-plugins` branch.  See https://quip.com/YLcCAxtjuwsL for details (some aspects of the API have changed).  Right now we're implementing it for `less` but other preprocessors should be supportable too (though last I changed stylus will need some patches to support alternative implementations of `@import`).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Stylus%20(or%20sass)%20variables%2Fmixins%20available%20between%20packages%3F&body=Migrated%20from:%20meteor/meteor%234593) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
