### ISSUE TITLE
Meteor is showing confusing line of code

### ISSUE THREAD

**Issue by jakozaur** [meteor/meteor#4598]
When server crashes, because of bug in code. I always see the line:
```
.../server-lib/node_modules/fibers/future.js:245
                                                throw(ex);
```
Instead of line actually causing the problem.

Screenshot of current behavior:
![screen shot 2015-06-21 at 1 53 14 pm](https://cloud.githubusercontent.com/assets/972989/8271540/b01b1184-181d-11e5-94fa-23cc181bc84b.png)

Desired behavior:
![screen shot 2015-06-21 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/972989/8271542/c1f9aa46-181d-11e5-861b-b1553245207c.png)

It slows down my debugging. Moreover, it is unfriendly to beginners and confuse them a lot. It would be awesome if Meteor could pinpoint the problem. 

Happy to fix that.

**Comment by glasser** [comment]
Responded on the PR.  Thanks for working on this!

**Comment by abernix** [comment]
Closing this as Meteor now has better source map support.  Granted, it's not without bugs, they are covered in other more recent and more active issues like #6708 and #7076 (and others).  We're trying to get rid of duplicate issues whereever possible so please post your problems in another open issue if you are still suffering from this problem!  Thanks! :)
