### ISSUE TITLE
Meteor doesn't recover from MongoDB connection failure when using DB authentication, does without auth

### ISSUE THREAD

**Issue by graemian** [meteor/meteor#4600]
To replicate:

- Setup 2 MongoDBs, one with auth enabled and the other without
- Run the "To Do" example and point it at these Mongos using the MONGO_URL env var (for the auth'ed DB, use the mongodb://user:pass@... form)
- Restart the MongoDB while running on top of the non-auth'ed DB. Everything is still fine, you can add new todos after the restart.
  - If you stop the DB and add a todo, the add is buffered and successfully applied when the Mongo is started again
- Restart the MongoDB while running on top of the auth'ed DB, you can no longer add any new todos
  - If you stop the DB and add a todo, you get this error:

```
Exception while polling query {"collectionName":"lists","selector":{"userId":{"$exists":false}},"options":{"transform":null}}: Error: No replica set primary available for query with ReadPreference PRIMARY
I20150621-17:14:53.194(0)?     at Object.Future.wait (/tmp/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
I20150621-17:14:53.194(0)?     at [object Object]._.extend._nextObject (/packages/mongo/mongo_driver.js:948:1)
I20150621-17:14:53.195(0)?     at [object Object]._.extend.forEach (/packages/mongo/mongo_driver.js:982:1)
I20150621-17:14:53.196(0)?     at [object Object]._.extend.getRawObjects (/packages/mongo/mongo_driver.js:1031:1)
I20150621-17:14:53.196(0)?     at [object Object]._.extend._pollMongo (/packages/mongo/polling_observe_driver.js:147:1)
I20150621-17:14:53.197(0)?     at Object.task (/packages/mongo/polling_observe_driver.js:85:1)
I20150621-17:14:53.197(0)?     at [object Object]._.extend._run (/packages/meteor/fiber_helpers.js:147:1)
I20150621-17:14:53.197(0)?     at /packages/meteor/fiber_helpers.js:125:1
I20150621-17:14:53.198(0)?     - - - - -
I20150621-17:14:53.199(0)?     at [object Object].ReplSet.checkoutReader (/tmp/todos/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
I20150621-17:14:53.199(0)?     at Cursor.nextObject (/tmp/todos/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
I20150621-17:14:53.200(0)?     at [object Object].fn [as _synchronousNextObject] (/tmp/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:89:26)
I20150621-17:14:53.200(0)?     at [object Object]._.extend._nextObject (/packages/mongo/mongo_driver.js:948:1)
I20150621-17:14:53.201(0)?     at [object Object]._.extend.forEach (/packages/mongo/mongo_driver.js:982:1)
I20150621-17:14:53.201(0)?     at [object Object]._.extend.getRawObjects (/packages/mongo/mongo_driver.js:1031:1)
I20150621-17:14:53.202(0)?     at [object Object]._.extend._pollMongo (/packages/mongo/polling_observe_driver.js:147:1)
I20150621-17:14:53.202(0)?     at Object.task (/packages/mongo/polling_observe_driver.js:85:1)
I20150621-17:14:53.203(0)?     at [object Object]._.extend._run (/packages/meteor/fiber_helpers.js:147:1)
I20150621-17:14:53.205(0)?     at /packages/meteor/fiber_helpers.js:125:1
```

**Comment by glasser** [comment]
Can you give more detailed instructions on how you set up your mongod instances?  Ideally including specific commands to type.

This definitely seems like a problem.

**Comment by graemian** [comment]
I dug a little deeper, and the root cause is using a Mongo replica set member hostname ( rs.conf().members[n].host ) that isn't resolvable by the client. Meteor happily starts working on top of such a Mongo, but if the Mongo disappears, something in the recovery process is sensitive to that hostname, and the recovery fails.

This is a real pain since "rs.initiate()" just grabs a hostname that isn't resolvable by the client in a great many circumstances

This example is from a DigitalOcean Droplet called "mongo-test" that I created for testing. Obviously "mongo-test" isn't resolvable by the client:

```
{
	"_id" : "tp",
	"version" : 1,
	"members" : [
		{
			"_id" : 0,
			"host" : "mongo-test:27017"
		}
	]
}
```

Here's what happens under Docker. The hostname is the container name, also not resolvable:

```
{
	"_id" : "tp",
	"version" : 1,
	"members" : [
		{
			"_id" : 0,
			"host" : "b4a7d56382a6:27017"
		}
	]
}
```

I guess people need to learn to configure their Mongo's properly, but I suspect a great many people are going to get tripped-up by this.

Is that recovery code part of Meteor, or part of the Mongo driver from 10gen?

**Comment by graemian** [comment]
I suspect that most people that encounter this error will chalk it up to Meteor being unreliable since a Meteor restart fixes it.

**Comment by graemian** [comment]
From http://docs.mongodb.org/manual/tutorial/change-hostnames-in-a-replica-set:

```
NOTE
Always use resolvable hostnames for the value of the host field in the replica set configuration to avoid confusion and complexity.
```

Hehe

**Comment by lerayj** [comment]
I'm suprised you still don't have any feedback on this issue. 
It's a pretty important thing and we still don't have any way to patch this?
I'm kind of tired rebooting the app when the mongo host crash :/

**Comment by snajjar** [comment]
Happened to me last night, after loosing connectivity with the database service we use:

2016-07-29T08:13:58.06+0200 [App/1]      OUT Exception while invoking method 'login' Error: failed to connect to [/* HIDDEN */]
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at Object.Future.wait (/home/vcap/deploy/bundle/programs/server/node_modules/fibers/future.js:449:15)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:986:47)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1020:22)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1030:10)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1054:17)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:869:44)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at MongoConnection.findOne (packages/mongo/mongo_driver.js:776:56)
2016-07-29T08:13:58.06+0200 [App/1]      OUT     at [object Object].findOne (packages/mongo/collection.js:337:29)
...

After the connection loss, Meteor wasn't able to restore it.

2016-07-29T08:13:58.06+0200 [App/1]      OUT Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
2016-07-29T08:13:58.17+0200 [App/1]      OUT Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
2016-07-29T08:13:58.27+0200 [App/1]      OUT Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY

Restarting Meteor "fixed" the issue, but nobody can be satisfied with that.
It was Meteor 1.3.4, I'm upgrading to Meteor 1.4 (in hope that the driver issue has been fixed).

According to [this thread](https://github.com/meteor/meteor/issues/2092), MONGO_URL parameters seems to fix the issue (readPreference, socketTimeoutMS & connectTimeoutMS). Can somebody confirm this?

**Comment by realyze** [comment]
Same error here (with repl set on mLab).

**Comment by abernix** [comment]
I'm going to close this issue as the original issue was due to a misconfiguration in the Mongo replica set.  This recovery of a replica set was never handed by Meteor, but Mongo now makes explicitly clear that the hostname name must be resolvable for every host in the replica set, in addition to [other new configuration rules](https://docs.mongodb.com/manual/reference/replica-configuration/).  Running your own Mongo is a difficult task and its recommended to go with a provider who handles this for you.

As for reconnection from Meteor when connection is lost and doesn't recover, there are other issues open to track this: #5773
