### ISSUE TITLE
meteor deployed but some package uncaught

### ISSUE THREAD

**Issue by yozawiratama** [meteor/meteor#4602]
i have a meteor application, with this package :

    meteor-platform
    insecure
    iron:router
    aslagle:reactive-table
    accounts-base
    accounts-password
    natestrauser:font-awesome
    mizzao:bootboxjs
    aldeed:autoform
    aldeed:simple-schema
    aldeed:collection2
    matb33:collection-hooks
    twbs:bootstrap

when it still in development, it run well. but when i deploy by bundled, i have this error :

![Some packages uncaught error][1]

Why this happend? and how to solve it?

  [1]: http://i.stack.imgur.com/ttz5a.png

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
