### ISSUE TITLE
Cannot attach schema to a collection. Error using mongodb with Meteor in general

### ISSUE THREAD

**Issue by mangeshnanoti** [meteor/meteor#4604]
<strong> Hi, I am very new to Meteor. 

Here is my Code - </strong>

post = new Mongo.Collection("posts");

pos = new SimpleSchema({
		  maleCount:       {type: Number,    label: "Title",        max: 200 },
		  femaleCount:       {type: Number,    label: "Title",        max: 200 }

		  });
post.attachSchema(pos);

<strong>Here is the stacktrace - </strong>

W20150622-13:26:06.250(5.5)? (STDERR)         
W20150622-13:26:06.251(5.5)? (STDERR) /Users/mangeshnanoti/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150622-13:26:06.252(5.5)? (STDERR) 						throw(ex);
W20150622-13:26:06.252(5.5)? (STDERR) 						      ^
W20150622-13:26:06.252(5.5)? (STDERR) TypeError: Object [object Object] has no method 'attachSchema'
W20150622-13:26:06.252(5.5)? (STDERR)     at app/lib/common.js:8:6
W20150622-13:26:06.252(5.5)? (STDERR)     at app/lib/common.js:11:3
W20150622-13:26:06.252(5.5)? (STDERR)     at /Users/mangeshnanoti/Meteor Projects/newApp/.meteor/local/build/programs/server/boot.js:222:10
W20150622-13:26:06.252(5.5)? (STDERR)     at Array.forEach (native)
W20150622-13:26:06.252(5.5)? (STDERR)     at Function._.each._.forEach (/Users/mangeshnanoti/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150622-13:26:06.253(5.5)? (STDERR)     at /Users/mangeshnanoti/Meteor Projects/newApp/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8

**Comment by mangeshnanoti** [comment]
it appears that attachSchema is a function that no longer works.

**Comment by macrozone** [comment]
attachSchema is a function from the smart package aldeed:simple-schema, see https://github.com/aldeed/meteor-simple-schema

**Comment by mangeshnanoti** [comment]
But I do not not see any attachSchema() function. How do I attach my schema to the DB?

**Comment by zardak** [comment]
The function you're looking for is in [aldeed:collection2](https://atmospherejs.com/aldeed/collection2), this package depends on previously mentioned one.
And please, consider using google next time, this is the first link to pop up for `meteor attach schema`  query.

**Comment by glasser** [comment]
Thanks @macrozone and @zardak  for helping. "Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
