### ISSUE TITLE
Failed to write manifest.json on Android 5

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#4605]
I’ve got really strange behaviour of *packages/autoupdate/autoupdate_cordova.js* on Android 5.0.1 with android:targetSdkVersion="22" (devel branch). It successfully downloads new assets, but fails to write _manifest.json_ after all.

Here is the sample log:

```
METEOR CORDOVA DEBUG (autoupdate_cordova.js) start downloading /88bc067cd74cb6355be438afa573410c21d570ff.js
METEOR CORDOVA DEBUG (autoupdate_cordova.js) start downloading /d7afbc65ea945bc594a1283f032e2a5267983620.css
METEOR CORDOVA DEBUG (autoupdate_cordova.js) start downloading /index.html
METEOR CORDOVA DEBUG (autoupdate_cordova.js) done downloading /index.html
METEOR CORDOVA DEBUG (autoupdate_cordova.js) done downloading /d7afbc65ea945bc594a1283f032e2a5267983620.css
METEOR CORDOVA DEBUG (autoupdate_cordova.js) done downloading /88bc067cd74cb6355be438afa573410c21d570ff.js
METEOR CORDOVA DEBUG (autoupdate_cordova.js) Failed to write manifest.json: Error: Failed to write file: 
```

After some debug I can say that *version-hash/manifest.json* is created but `fileEntry.createWriter` fails with code 6 (NO_MODIFICATION_ALLOWED_ERR).

Android 4.2.2 is updating well. And when I downgrade `targetSdkVersion` back to `19`, all is fine again on Android 5.0.1.

**Comment by glasser** [comment]
Thanks for the report. The MDG core team is focused on some other areas of the platform right now, so we may not get to a fix for this soon. We’d welcome community help on this and other Cordova bugs in the form of PRs or other supporting information.
