### ISSUE TITLE
Rendering template,in need me place, when router takes get ?page=2

### ISSUE THREAD

**Issue by vortex14** [meteor/meteor#4609]
I have simple template:
template name="SearchResult"
{{#with SearchResult}}
...
{{/with}}
template

//Simple Helper for template:
Template.SearchResult.heplers({
SearchResult : function(){
Session.get('SearchResult').data
}
});

//Simple router controller:
Router.route('SearchResult', {
path: '/search',
controller: 'SearchController'
});

SearchController = AppController.extend({

onBeforeAction: function () {
    console.log('Method onBeforeAction');
    this.next();
},

before: function () {
    console.log('Method before');
    this.next();
},

action: function () {
    this.render('SearchResult');
},
});

Template.SearchResult.rendered = function(){
//callback rendered this template
}

When I start this app, callback "rendered" on the template, but when takes get parametr ?parametr=a&page=1 callback not call!

Test:
Router.go('/search?page=4')

What me do?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
