### ISSUE TITLE
Clarify output of incompatible package change

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4610]
**_1 Upvote**_ I currently get this output when trying to update a package with `meteor add`:

```
meteor add fourseven:scss@3.1.1
 => Errors while adding packages:             

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: meteoric:ionic-sass 0.1.3, was
0.1.9.
Constraints on package "meteoric:ionic-sass":

Potentially incompatible change required to top-level dependency: fourseven:scss 3.1.1, was 2.1.1.
Constraints on package "fourseven:scss":
* fourseven:scss@3.1.1 <- top level

To allow potentially incompatible changes to top-level dependencies, you must pass
--allow-incompatible-update on the command line.
```

It would be clearer to say:

```
You currently have Y version 2.1.1 and X version 0.1.3. 
X depends on Y version < 3, so X may be incompatible with Y version 3.1.1. 

To force update Y, do ...
```

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I agree that this is confusing and that we could have better wording here.

**Comment by chiester** [comment]
+1

**Comment by stallter4** [comment]
+1, well the question is, how do I force the update, I still can't find that information?

**Comment by stallter4** [comment]
nevermind, got that figured out, just need the meteor in front, but I do +1 the hieroglyphic message.

**Comment by stallter4** [comment]
It's definitely hieroglyphics, and how do I force the update, it gives some cryptic message that does nothing in the command line, then if you run that in the command line it does nothing.  Come on....

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Clarify%20output%20of%20incompatible%20package%20change&body=Migrated%20from:%20meteor/meteor%234610) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
