### ISSUE TITLE
accounts-ui: TypeError while configuring Twitter for the first time

### ISSUE THREAD

**Issue by sungwoncho** [meteor/meteor#4616]
I added `accounts-twitter` and `accounts-ui` to my application, and used `{{> loginButtons}}` in my template.

I was prompted to configure Twitter login, filled in API key and secret key.

When clicking `save configuration`, I get `Uncaught TypeError: $ is not a function`.

*Full error trace in browser console*

```
Uncaught TypeError: $ is not a function

Template._configureLoginServiceDialog.events.click #configure-login-service-dialog-save-configuration @ login_buttons_dialogs.js:200

(anonymous function) @ template.js:463

Template._withTemplateInstanceFunc @ template.js:437

(anonymous function) @ template.js:462

(anonymous function) @ view.js:869

Blaze._withCurrentView @ view.js:523

(anonymous function) @ view.js:868

(anonymous function) @ events.js:47

jQuery.event.dispatch @ jquery.js:4665

jQuery.event.add.elemData.handle @ jquery.js:4333
```

**Comment by glasser** [comment]
It worked for me.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by glasser** [comment]
That said, looks like there's a missing dependency that could cause problems in some cases.

**Comment by sungwoncho** [comment]
The issue was that a third party javascript code was messing with the jQuery by using `jQuery.noConflict(true)`. Sorry for not closing this sooner after I had discovered the fix.
