### ISSUE TITLE
Press mouse wheel on an old version of Firefox refresh the page

### ISSUE THREAD

**Issue by serut** [meteor/meteor#4617]
I was very surprised to discover that my app was refreshing almost every time I press the mouse wheel on Firefox 17, and not with Chrome. When I say almost every time, I mean that after some delay, this bug disappear. But if I open the page in a new tab, I still have this issue.
Anyone can reproduce this bug ? I just created an empty meteor project, run it, open Firefox and pressed the mouse wheel.

**Comment by stubailo** [comment]
@serut Just tested in my Firefox and it doesn't happen (and I can't think of any reasonable way this would be a result of Meteor code). Sometimes, things like this are the result of installed extensions - check on that.
