### ISSUE TITLE
Oauth._redirect_uri generates malformed query string

### ISSUE THREAD

**Issue by huned** [meteor/meteor#4618]
This issue just came up with an app that we're working on. We're oauth-ing with Dropbox via [gcampax:accounts-dropbox](https://atmospherejs.com/gcampax/accounts-dropbox), which uses meteor's oauth under the hood.

Per https://en.wikipedia.org/wiki/Query_string#Web_forms (sorry, I can't parse [RFC 3986](http://tools.ietf.org/html/rfc3986)) the query string is made up of multiple "key=value" pairs, which each item in the pair separated by "=". However, [Oauth._redirect_uri:L11](https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_common.js#L11) appends a "?close", which is malformed because it does not contain "=".

Dropbox in particular recently changed their redirect_uri validation to account for malformed query strings, breaking meteor's oauth. The code I'm using:

    Meteor.loginWithDropbox({
      loginStyle: 'popup'
    }, function(err) {
      if (err) {
        console.log(err);
      }
    });

Dropbox now responds with a 400 and the following message ([screen capture](https://www.evernote.com/shard/s57/sh/57f806e6-bb41-43d8-9768-3b11175be721/3041972cc45c8627)):

    Invalid redirect_uri: "http://localhost:3000/_oauth/dropbox?close": Invalid query string: Not valid "x-www-form-urlencoded" data: "close".

My proposal in fixing this while maintaining compatibility is to simply append "?close=" instead of "?close". (Dropbox support tells me that this would make things work.) Would that break legacy meteor clients?

**Comment by glasser** [comment]
Hmm, RFC 3986 does make it reasonably clear that anything is legal in a query, and https://tools.ietf.org/html/draft-hoehrmann-urlencoded-01 suggests that names without values are explicitly OK.  But it is a shame if Dropbox has this problem.

That said, I thought `?close` was old code and we don't use it by default any more.  It shouldn't show up if you specify a `config.loginStyle` (popup or redirect) to `OAuth._redirectUri`.  Maybe accounts-dropbox needs to be upgraded to pass this?

**Comment by huned** [comment]
Yes, you are correct @glasser ... per https://tools.ietf.org/html/draft-hoehrmann-urlencoded-01 the "=" is indeed optional. (I'll forward this on to dropbox's support team.)

In the mean time, I'll perhaps sleuth out how/why accounts-dropbox loses my `{ loginStyle: 'popup' }` configuration object by the time it gets to OAuth._loginStyle() here: https://github.com/gcampax/meteor-dropbox-oauth/blob/master/dropbox_client.js#L23

Thanks!

**Comment by cakoose** [comment]
The linked document is a [draft](https://en.wikipedia.org/wiki/Internet_Draft) and not an [RFC](https://en.wikipedia.org/wiki/Request_for_Comments) or an [IETF standard](https://en.wikipedia.org/wiki/Internet_Standard).

The authoritative definition for "x-www-form-urlencoded" URL query strings is hard to track down, but the OAuth 2.0 specification goes the extra mile to make it clear what it expects.

1. [Section 3.1.2](https://tools.ietf.org/html/rfc6749#section-3.1.2): "The endpoint URI MAY include an "application/x-www-form-urlencoded" formatted (per Appendix B) query component."
2. [Appendix B](https://tools.ietf.org/html/rfc6749#appendix-B) specifically references the W3C's HTML 4.01 spec.
3. [W3C HTML 4.01 spec, 17.13.4](https://www.w3.org/TR/1999/REC-html401-19991224/interact/forms.html#h-17.13.4): "The name is separated from the value by '=' and name/value pairs are separated from each other by '&'."
