### ISSUE TITLE
Remove all verification tokens for a specific email once that email is verified

### ISSUE THREAD

**Issue by zimme** [meteor/meteor#4626]
This will break links in the "other" verify email emails, but it will keep the user record cleaner

**Comment by zimme** [comment]
I'll try and put together a PR for this if you don't think this is a weird idea

**Comment by stubailo** [comment]
Yeah, I think this would be a good idea to do.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

If you add a PR for this I'll take a look.

**Comment by zimme** [comment]
I'll try and find sum time
