### ISSUE TITLE
Publish an array of cursors from one collection

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#4627]
For publishing an array of cursors there's a big, red comment on the docs:

> If you return multiple cursors in an array, they currently must all be from different collections. We hope to lift this restriction in a future release.

Is this going to be fixed? The only alternative I see here is using two publications, but having everything in one place would be much nicer.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

We don't have plans to fix this at the moment, but it would be a great improvement to have.

**Comment by zimt28** [comment]
I'm closing this, as there are simple ways to work around, it's bad to have too many issues open and Apollo is the future of Meteor's data stuff; not DDP.
