### ISSUE TITLE
JSON.parse issue on blaze re-render of each list

### ISSUE THREAD

**Issue by mattiLeBlanc** [meteor/meteor#4629]
Hi,

I noticed an issue where I have a list of items where each list has a button that opens a dialog, and forwards a data context.
This data context is put in a data-attribute, stringified in the helper.
When the button is clicked, the dialog opens for the data context and its context is available by accesing node.data('attributename'). Here it automatically gets parsed to a object.

This is where it goes wrong, if you remove elements from the list in the order: 
Remove item 2
Try remove item 3

When you try to remove item 3, it gets the parsed object of number 2, which doesnt exist anymore. When you look int the source you see the correct JSON for item 3. However, the parsed object is from number 2.

I can demonstrate this issue in the test I build:
https://github.com/mattiLeBlanc/parseJSONIssue

Anyone of the Blaze team who wants to take a look?

**Comment by glasser** [comment]
Are you able to reproduce this issue using Blaze directly without Jade?  If you are unable to reproduce this issue without Jade, you should report it as a Jade bug.  If you can reproduce it without Jade, you should show us a reproduction that doesn't use Jade.

**Comment by mattiLeBlanc** [comment]
Fine, I will un-Jade it. Should I also un-coffee it?

**Comment by glasser** [comment]
Can't hurt!

**Comment by mattiLeBlanc** [comment]
Okay, check new branch:
https://github.com/mattiLeBlanc/parseJSONIssue/tree/html-js

Issue still exists!

**Comment by avital** [comment]
This is actually the way jQuery's `data()` works -- after you call it the first time it caches the result and never reads the attribute again:

"The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery)."

(https://api.jquery.com/data/)

**Comment by mattiLeBlanc** [comment]
I worked around it by passing the plain JSON as text in the attribute and parsed it myself. That worked.
