### ISSUE TITLE
Issue when publishing new meteor-tool for osx.

### ISSUE THREAD

**Issue by jboulhous** [meteor/meteor#4630]
Hello MDG,
Thank you again for the whole meteor experience.
Regardings packages server, i have been trying for few hours to publish a `jboulhous:meteor-tool`, and a `jboulhous:IO` track, some of my tries ended with success and other failed.
>i finally understood that any thing published from a git checkout should be published to other platforms using the same git checkout.
>(please correct me)

`meteor show jboulhous:meteor-tool` and `meteor show jboulhous:IO` returns results, but i still can't use the track:
```
webapp imac$ meteor --release jboulhous:IO@1.1.1-rc2
Sorry, jboulhous:IO@1.1.1-rc2 is not installed and could not be downloaded. Please check to make sure that you are online.
webapp imac$
```
Internet connection is actually working.
Here what i did

1. `meteor-tool imac$ ../../meteor publish`
2. Follwing `ekate` [comment](https://github.com/meteor/meteor/issues/3173#issuecomment-65114285) I publishd `jboulhous:meteot-tool` to linux 64 and 32
  * `meteor admin get-machine os.linux.*`
  * `git clone -b devel https://github.com/jboulhous/meteor`
  * from meteor-platform `../../meteor publish --existing-version`
  * publishing for windows failed because of lake of 7z.exe. 
3. Trying to publish from an osx build machine failed with `Connection to 199.19.86.153 closed by remote host.`   
4. Trying to publish with `--existing-version` from my machine also failed after about 10 minutes with
```
meteor-tool imac$ ../../meteor publish --existing-version
=> Errors while publishing:                   
                                              
While uploading build:
error: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be
closed.</Message><RequestId>318A35A88744B127</RequestId><HostId>PQU+ShogJbY8wPP2iVbDcfgoDlpCqfsCbZgrYoLqonyoL1by9zMQkyhj3U+Aeqnf</HostId></Error>
```
I don't know if this is a bug or i just reach the maximum time for connecting to mdg servers.

I would like to thank you again for your support and for the whole meteor experience.

Regards Jamal.

**Comment by glasser** [comment]
Hmm.  `meteor admin get-machine os.osx.x86_64` works for me now. Does it work for you now?

That last error is coming from Amazon S3.  Maybe there is something up with your network connection?

**Comment by jboulhous** [comment]
Hello.
I tired for osx.x86_64 and got `Connection to 199.19.86.153 closed by remote host.`
i also tried published meteor-tool for linux 32&64 on a vm and got
`webapp imac$ meteor --release jboulhous:IO@1.1.1-rc2
Sorry, jboulhous:IO@1.1.1-rc2 is not installed and could not be downloaded. Please check to make sure that you are online.
`
i tried this in my home network, i will try again in another network.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem in a while and lots has changed with Meteor since it was opened.  Please try again using the latest version of Meteor to see if this problem still exists and if it does, we can reopen this.
