### ISSUE TITLE
Why don't Session variables support functions?

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4632]
I see no reason why Session variables shouldnt accept functions...
```js
a = function() {return 10}
Session.set('a', a)
Session.get(a)
// undefined
```

**Comment by robertpitt** [comment]
the `Session` object under the hood is just a `ReactiveDict`, ReactiveDict's support a feature called migration that serialises the data between reloads.

The storage mechanism for this is window.sessionStore, which only supports primitive types, with the odd exception such as Date Object that are serialised and de-serialised by `JSON.parse`

So it looks like support for storing functions is pretty much out the window, that being said, I think that switching to `EJSON` to serialise might be a cool idea.

**Comment by ccorcos** [comment]
Ah that totally makes sense. I suppose I could just use a reactive var instead since those don't get serialized...

**Comment by rclai** [comment]
Wait, does that mean that if you call the function in the `ReactiveVar`, you end up doing:

`myFunction.get()()`?

**Comment by robertpitt** [comment]
I don't see any use case for storing functions reactively, but @rclai, you're right, you will have to do the `()()` to call.

**Comment by ccorcos** [comment]
Well, I'm hacking around on something pretty non-trivial right now, so without giving too many details, I have a cursor that changes, and I when the cursor changes, I want Blaze to update:

```coffee
Session.set('messages', messagesCursor)
# {later}
Template.main.helpers
  messages: Session.get('messages')
```

`Session.set` keeps ripping off my `observe` function though...

**Comment by rclai** [comment]
Oh look at [this](https://github.com/meteor/meteor/pull/4120).

**Comment by ccorcos** [comment]
Nice @rclai. Thats what I was thinking...

**Comment by stubailo** [comment]
@robertpitt was right. Thanks for resolving this!
