### ISSUE TITLE
CSS files always minified, even in debug

### ISSUE THREAD

**Issue by tvld** [meteor/meteor#4633]
After "meteor run" , the browser shows only one  bundled & minified CSS, while I expect the various CSS there ready for debugging.

Server startup:  console.log(process.env);   shows that NODE_ENV: 'development',  so that seems ok.

Any thoughts?

**Comment by anubhav94** [comment]
Hey @tvld! Are you sure it's actually minified? I just tested it out and we merge all files into a single file as documented in the docs and replicated below.

> CSS files are still combined into a single file for consistency between production and development, because changing the CSS file's URL affects how URLs in it are processed.

If the CSS is actually minified, that seems to be a problem and we'd need a reproduction as described in: 
https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by tvld** [comment]
Maybe "minified"  is not the right word... 

But I tried to search for comment /*...*/   in the CSS, but it is not there. Bundle is ok, removing comments in development run is not I think? 

(I started with Meteor 2 weeks ago.. so maybe I am missing something )

**Comment by anubhav94** [comment]
You're right that we remove comments from our CSS, but we do provide source maps which you can enable in DevTools ([see here](https://developer.chrome.com/devtools/docs/css-preprocessors)) and then be able to cmd+click or ctrl+click to get to the appropriate line in a file when inspecting the css. 

Do you have a strong reason for wanting comments instead of just sourcemaps?

**Comment by tvld** [comment]
We use comments in CSS to remind us of strange quircks, especially in browser incompatibility issues, that we forget about existed even later. We fiddle a class & check the comments during that phase. 

Anyway, I dont see disadvantages of leaving comments in CSS during dev, but... it is no priority either as we manage ok for sure:))
Thanks for the links in DevTools... We have been focussed on Firebug so lost Chrome Devtools a bit out of sight.
