### ISSUE TITLE
Documentation doesn't mention PACKAGE_DIRS env var

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4634]
This is an important thing to mention in the documentation, I think.

**Comment by anubhav94** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by ffxsam** [comment]
PR added! https://github.com/meteor/meteor/pull/4661

**Comment by ffxsam** [comment]
Why was this removed from the documentation?

**Comment by skirunman** [comment]
This could be close as documented in [Meteor Guide ](http://guide.meteor.com/using-packages.html#atmosphere-overriding)

**Comment by hwillson** [comment]
Agreed @skirunman - closing this as it was documented in the [Overriding packages with a local version](https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages) section of the Guide. Thanks all!
