### ISSUE TITLE
Meteor.onConnection - onClose not working as documented

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4635]
I'm getting some strange behavior with `Meteor.onConnection` in general. Code below:

```javascript
Meteor.onConnection(function (conn) {
  conn.onClose = function () {
    console.log('user left');
  };
  console.log('New connection %s from %s', conn.id, conn.clientAddress);
});
```

When I load my page up, I see this in the server console:
> New connection NznKHxEwz6ymPdYKP from 127.0.0.1

But when I surf away from the page, I see:
> New connection 3rchcTmsMr9Nkwz7k from 127.0.0.1

So not only does the `onClose` not get called, but Meteor somehow thinks a new connection is being established. Something seems not right here.

**Comment by Tarang** [comment]
onClose takes a callback as its first parameter & is a function itself as specified in the docs:

   ```conn.conClose(function() ...});```

**Comment by iDoMeteor** [comment]
And DDP connections happen quite frequently.

**Comment by ffxsam** [comment]
Ah, thanks. I misunderstood the documentation and figured `onClose` was an object property, not an actual function.

**Comment by iDoMeteor** [comment]
I had to read it twice when I wanted to use it yesterday. :)

**Comment by glasser** [comment]
Thanks for helping, @Tarang!
