### ISSUE TITLE
Use SQL++ instead of Mongo query

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4636]
[SQL++](http://forward.ucsd.edu/sqlpp.html) is a query language which abstract differences between various other databases into a common JSON-based SQL-like query language. It allows queries which can join for example between MongoDB and Postgres. It is similar to SQL, but it operates on collections of JSON documents.

I think it would be a great way to provide a way in Meteor to make same queries both on the client and server side, which can then work both on MongoDB backends and SQL backends, without introducing caring if a publish function uses MongoDB or SQL internally.

JavaScript implementation is planned (they also want that the same query runs both on client and server).

They have already also support for incremental diffs (similar to how Meteor is doing with DDP).

**Comment by laosb** [comment]
I DO NOT really like the SQL-like query language. In fact, it's not very clear like the Mongo query.

**Comment by anubhav94** [comment]
Thanks for the suggestion @mitar ! This is a major project that is being tracked on the roadmap [here](https://trello.com/c/Gf6YxFp2/42-sql-support).
