### ISSUE TITLE
Can I have 2 different meteor deploy app connect to the same Mongo DB? 

### ISSUE THREAD

**Issue by zeskysee** [meteor/meteor#4642]
Hi, 

Example, I had 2 meteor project, the first project deploy to ```project1.meteor.com``` and the 2nd project deploy to ```project2.meteor.com```.

Can I have both of them connect to the same Mongo DB instead of each having one DB?

Thanks

**Comment by Tarang** [comment]
Yes, it can. There's already a previous answer up on stackoverflow: http://stackoverflow.com/questions/20535755/using-multiple-mongodb-databases-with-meteor-js

**Comment by zeskysee** [comment]
So to share mongodb for 2 different project, i must deploy my own database to achieve that?

**Comment by thinklinux** [comment]
If you can set an environmental variable MONGO_URL to your mongodb instance - then you can. I think that on meteor.com you can set it like that `process.env.MONGO_URL='blabla'` but you can ask google about that.

**Comment by stubailo** [comment]
@zeskysee this is not currently an option with the `meteor deploy` hosting service, but if you host Meteor yourself you can do it easily, as @thinklinux said.
