### ISSUE TITLE
Separating packages into client and server packages

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4643]
I'm reading [here](https://github.com/meteor/meteor/blob/devel/History.md#ddp) that

> The ddp package has been split into ddp-client and ddp-server packages; using ddp is equivalent to using both. This allows you to use the Node DDP client without adding the DDP server to your app. #4191 #3452

The reasoning for why makes sense to me -- we can use `ddp-client` with React Native possibly. 

But this seems like an anti pattern. We want to keep isomorphic javascript. So perhaps it may be better if we could compile packages into client and server packages. This way, we could add only client or server packages if we want and the community wouldn't have to separate all their isomorphic packages into two.

**Comment by glasser** [comment]
The `ddp-client` package it itself an isomorphic package: it contains a DDP client for Node and a DDP client for browsers.

The previous layout provided no way to say "I want a DDP client in Node, but I don't want a DDP server".

**Comment by ccorcos** [comment]
I see. thanks!
