### ISSUE TITLE
Allow Meteor to run without a Mongo database

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4645]
Is it possible to remove mongo and minimongo from a meteor project? It seems that live query and a bunch of other packages depend on them...

**Comment by stubailo** [comment]
Currently, the Meteor command line tool is hardcoded to run `mongo`. You might be able to specify a dummy `MONGO_URL` to avoid connecting to a database if you don't want to.

As for your question, it is not possible to have `livequery` without `mongo` because the realtime query functionality is Mongo-specific.

Making Meteor work with different databases, or without a database altogether, is a big project that we will definitely do in the future.

**Comment by ccorcos** [comment]
No doubt. And then building and API so you can use `accounts-*` with a different database.

Well whenever this happens, check out [any-db](https://github.com/ccorcos/meteor-any-db/)

**Comment by ccorcos** [comment]
Hey @stubailo, I'd really like to repoen this issue, or please point me somewhere else I can track progress.

I'm not sure what specifically "livequery" is. It looks like its absorbed by the DDP package. I'm using Meteor without Mongo and it seems ddp and merge-box ought to be separated out into their own package. Here's my implementation of publishing arbitrary data to the client over DDP.

```coffee
# publish a set of documents on the server
publish = (name, fetcher) ->
  Meteor.publish name, (query, options={}) ->
    pub = this
    pubId = serialize([name, query])
    subId = pub._subscriptionId

    docs = new IdMap()
    
    # returns an IdMap of documents
    fetch = -> 
      fetcher(query, options)
    
    refresh = ->
      newDocs = fetch()
      # MDG does all the hard work for me ;)
      DiffSequence.diffQueryChanges false, docs, newDocs,
        added: (id, fields) ->
          fields = R.pipe(
            R.assocPath([DB_KEY, subId], "true", fields) # set the subscription
            obj2Fields # flatten deep objects
          )(fields or {})
          pub.added(DB_KEY, id, fields)
        changed: (id, fields) ->
          pub.changed(DB_KEY, id, fields)
        removed: (id) ->
          pub.removed(DB_KEY, id)
      docs = newDocs

    registerSub(pubId, subId, refresh)
    refresh()
    pub.ready()

# client
Meteor.connection.registerStore DB_KEY,
    beginUpdate: (batchSize, reset) ->
      if reset then resetSubs()

    update: (msg) ->
      {id, fields, addToSubs, cleared} = parseDDPMsg(msg)

      if msg.msg is 'added'
        for subId, value of addToSubs
          sub = findSub(subId)
          sub.added(id, fields)

      if msg.msg is 'removed'
        eachSub (sub) ->
          sub.removed(id)
        return

      if msg.msg is 'changed'
        for subId, value of cleared
          sub = findSub(subId)
          sub.removed(id)
        for subId, value of addToSubs
          sub = findSub(subId)
          doc = findDoc(id)
          sub.added(id, R.omit([DOC_ID_KEY], doc))

        if Object.keys(fields).length > 0
          eachSub (sub) ->
            sub.changed(id, fields)
        return
        
      throw new Error("I don't know how to deal with this message");

```

I don't see any need for mongo / minimongo in all of this except for determining the logged in user. On this front, I think it would be great if Meteor's accounts-base could have a client / server API for saving cookies (could be on a native device or a browser), and for saving / retrieving user documents on the server for login, etc. This would give the developer the freedom to build their own schemas and publish exactly what they want. It would be a huge selling point for people with existing projects. Of course there will be other packages to adapt this base package to work with Mongo as it currently does.

Any thoughts?

**Comment by stubailo** [comment]
@ccorcos I still think this is a much bigger project than you are saying. A huge proportion of Meteor internals and community packages assume the Mongo API or the existence of a Mongo database. However, maybe we can still reopen the issue to be closed when we factor out Mongo support somehow.

**Comment by ccorcos** [comment]
> @ccorcos I still think this is a much bigger project than you are saying.

Its certainly not easy. I've looked in the code and gotten lost. But it seems there are certain things, like the snippet I showed you above, which demonstrate a fairly simple and separate functionality. It would be really cool if we could pull that all out into smaller packages. The `diff-sequence` package is a perfect example of what I like to see in upcoming Meteor releases -- more modular internals. This is the only way we're every going to boot mongo.

> A huge proportion of Meteor internals and community packages assume the Mongo API or the existence of a Mongo database. 

I think many packages have forgotten to add `meteor-platform` as a dependency of their package. But thats not a big deal because most people will already have `meteor-platform` added. If they want to use another database, they can use a different platform. `platform:mongo`, `platform:rethinkdb`. 

This is definitely no easy task, but I think its 100% necessary for the bright future of Meteor.

**Comment by ccorcos** [comment]
Look at all of the packages the `accounts-facebook` depends on. Holy crap!

```
~/C/m/events git:package ❯❯❯ meteor list                                                                                                                                                                  

accounts-facebook  1.0.4  Login service for Facebook accounts

~/C/m/events git:package ❯❯❯ meteor remove accounts-facebook                                                                                                                                            
                                              
Changes to your project's package version selections:
                                              
accounts-base          removed from your project
accounts-facebook      removed from your project
accounts-oauth         removed from your project
base64                 removed from your project
binary-heap            removed from your project
blaze                  removed from your project
blaze-tools            removed from your project
boilerplate-generator  removed from your project
callback-hook          removed from your project
check                  removed from your project
ddp                    removed from your project
deps                   removed from your project
ejson                  removed from your project
facebook               removed from your project
geojson-utils          removed from your project
html-tools             removed from your project
htmljs                 removed from your project
http                   removed from your project
id-map                 removed from your project
jquery                 removed from your project
json                   removed from your project
localstorage           removed from your project
logging                removed from your project
meteor                 removed from your project
minifiers              removed from your project
minimongo              removed from your project
mongo                  removed from your project
oauth                  removed from your project
oauth2                 removed from your project
observe-sequence       removed from your project
ordered-dict           removed from your project
random                 removed from your project
reactive-var           removed from your project
reload                 removed from your project
retry                  removed from your project
routepolicy            removed from your project
service-configuration  removed from your project
spacebars              removed from your project
spacebars-compiler     removed from your project
templating             removed from your project
tracker                removed from your project
ui                     removed from your project
underscore             removed from your project
url                    removed from your project
webapp                 removed from your project
webapp-hashing         removed from your project
```

**Comment by stubailo** [comment]
Yeah, I mean - if you have only accounts-facebook, and then remove it and have 0 packages, then that's what is going to happen.

I think one of the main benefits of Meteor is that there is a standard set of web app-related packages that everyone can use. I agree that mongo isn't one of them, but I think it's totally reasonable for `accounts-facebook` to depend on a lot of that stuff, since it's a package with _tons_ of cross-cutting concerns.

**Comment by ccorcos** [comment]
true. but it seems to me like those cross-cutting concerns should be more configurable with less of this exploding dependency effect.

Nothing html- or database-related should be a dependency of accounts-facebook (maybe you'd call it accounts-facebook-base). That should all be configurable to work with different databases, different storage methods on the client (for cookies) and different user interfaces.

**Comment by stubailo** [comment]
@ccorcos I think you're misrepresenting the problem here. I don't think it's bad if `accounts-facebook` depends on `accounts-base`, which assumes you are running a webapp? That's why we have the `facebook` package, which implements the facebook functionality without the accounts-related stuff.

IMO it's OK if Meteor is optimized for making an app with a client/server model rather than a generic JavaScript program.

**Comment by ccorcos** [comment]
Hmm. Well, here's my position:

I'm building an app with React, Facebook Login, and Neo4j. I'm using Mongo for accounts, but there's no reason I should need to. I'm using DDP with Neo4j all reactively with latency compensation. I don't need Mongo or Blaze. But I need Accounts and DDP. 

I've wedged myself in a challenging place, but I also think if Meteor is going to grow and become more powerful, this will eventually need to be addressed.

Getting Blaze out is a step in the right direction. I'm just curious when and *how* you guys are going to incorporate other databases.

**Comment by elitechance** [comment]
@ccorcos I'm working on something similar.  I was able to solve this issue by attaching this line in /lib

// if server
Meteor.users = YourPackage.Collection('users');

If you want to publish the current user

Meteor.publish("GetUser", function(){
    var userObject = {/* some value here */};
    var ID = /* The ID should match what you specified in Accounts.registerLoginHandler  */;
     this.added("users",ID,  userObject);
     this.ready();
});

**Comment by csillag** [comment]
Maybe it's time to revisit this. With Apollo, we can store the actual data in any DB we like. With a custom authentication handler (registered with `Accounts.registerLoginHandler()`), we can handle authentication any way we like.

As far as I can tell, the only remaining dependence on MongoDB is the accounts-base wants to store the active user sessions in MongoDB. I might be wrong here, but as far as I can tell, this part oesn't really use any fancy MongoDB-related feature, so here, MongoDB could be replaced with anything else.

How hard would it be the replace this with a different backed? (Redis, SQL, dummy in-memory storage, whatever.)

If I want to decouple MongoDB from here, where do I start? Would you consider accepting a PR for this, or I shouldn't even bother?

Thanks for the feedback.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20Meteor%20to%20run%20without%20a%20Mongo%20database&body=Migrated%20from:%20meteor/meteor%234645) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
