### ISSUE TITLE
Being able to hook into heartbeats

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4647]
I am currently using connection API to know when user connected and disconnected and I am storing this information into a MongoDB collection (so that it is available across instances). The issue is that if an instance crashes, the connection entry in the database stays because there was no disconnect code ran.

The traditional approach to address this is that each database entry should also have a timestamp and then I would regularly clear any stale entries. But the issue is that it is unclear how to be updating the timestamp. The best would be together with Meteor heartbeat. So while connection is open and active, I am updating the MongoDB timestamp. It the instance crashes, nothing keeps updating the timestamp.

**Comment by zhenyasav** [comment]
Thanks, @mitar - unfortunately we do not explicitly expose something to suit your ask, but this does sound like a solid feature request that we might take a look at in the near future.

**Comment by SanderMertens** [comment]
Since a DDP server knows when a client disconnects, it would be preferable to have an interface that notifies the server-app of this event, rather than using heartbeats.

The heartbeat approach is a potential scalability issue. You could end up with 100K clients that are all updating their timestamps regularly, causing lots of load on the database as well as bandwidth consumption for clients that are monitoring live users.

**Comment by mitar** [comment]
> Since a DDP server knows when a client disconnects, it would be preferable to have an interface that notifies the server-app of this event, rather than heartbeats.

It does not know, if DDP server hard crashes.

There is already disconnect callback for clean disconnects.

**Comment by SanderMertens** [comment]
@mitar Thanks, I did not know about the callback.

Do you have multiple servers connected to the same mongodb database? If not, you could just remove all entries from the connection collection upon server startup.

If you do have multiple servers connected, why not write a server-heartbeat, where each server updates its own timestamp every minute or so. If you annotate your connections with a generated random server id, this would be a more scalable solution than monitoring client-heartbeats.

It's also something you would be able to build with todays features.

**Comment by mitar** [comment]
> Do you have multiple servers connected to the same mongodb database? If not, you could just remove all entries from the 'connection collection' upon server startup.

Yes, I have multiple servers. Otherwise I could just use the local collection. But I have to use MongoDB collection to share information about connections between all instances.

> If you do have multiple servers connected, why not write a server-heartbeat, where each server updates its own timestamp every minute or so. If you annotate your connections with a generated random server id, and clear all connections of stale server instances, this would be a more scalable solution than monitoring client-heartbeats.

Hmmm. :-) That is not a bad idea. :-) Thanks.

**Comment by hwillson** [comment]
Closing this off as the solution proposed in https://github.com/meteor/meteor/issues/4647#issuecomment-121611309 sounds like it would work better (and be more scalable) then hooking into DDP's ping/pong. Thanks!
