### ISSUE TITLE
how to connect to a remote database!

### ISSUE THREAD

**Issue by train860** [meteor/meteor#4649]
I want to make all my meteor apps to share one database,maybe a remote database.

How to do this?

thanks

**Comment by thinklinux** [comment]
Look at http://docs.meteor.com/#/full/deploying below the `Running on your own infrastructure`

**Comment by train860** [comment]
thank you very much!!!

**Comment by stubailo** [comment]
Looks like this got resolved! In the future, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
