### ISSUE TITLE
Sources found in isopack build files are separate by 7 new lines. Can we rely on that?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4651]
For example, in an isopack build file, we have things like

```js
(function () {

///////////////////////////////////////////////////////////////////////
//                                                                   //
// packages/trusktr:lib2/module.js                                   //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
/*_____rocket_module_____:not-compiled*/ throw new Error('Rocket:module needs to be installed in your app for some code to work: meteor add rocket:module')
// Write your package code here!                                     // 2
var lowercase = require('lower-case')                                // 3
                                                                     // 4
console.log(' --- ', lowercase('HELLO WORLD!'))                      // 5
                                                                     // 6
                                                                     // 7
Lib = {                                                              // 8
    hello: function() {                                              // 9
        return 'Goodbye.'                                            // 10
    }                                                                // 11
} // ----------------------------------------------------------------------------------------------------------------------------------------------------
///////////////////////////////////////////////////////////////////////

}).call(this);






(function () {

///////////////////////////////////////////////////////////////////////
//                                                                   //
// packages/trusktr:lib2/blah.js                                     //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
                                                                     // 1
console.log('Blah!')                                                 // 2
                                                                     // 3
///////////////////////////////////////////////////////////////////////

}).call(this);






///////////////////////////////////////////////////////////////////////
//                                                                   //
// packages/trusktr:lib2/foo.js                                      //
// This file is in bare mode and is not in its own closure.          //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
                                                                     // 1
console.log('super duper heck yeah!!!!!')                            // 2
                                                                     // 3
// awesomeness.                                                      // 4
                                                                     // 5
```

Each source in there is separate by a (lucky?) 7 new lines. Can we rely on that to split the file into separate sources?

**Comment by trusktr** [comment]
P.S. When's `Plugin.registerCompiler` estimated to come out? It would help so much to have an estimate.

**Comment by stubailo** [comment]
No, you shouldn't rely on things that aren't officially part of the Meteor API; it would be impossible for us to make changes to Meteor if we had to maintain things like line spacing in built output. It seems like there should be a different way to do what you are trying to do; what are you trying to do?

Also, I don't think GitHub issues are the right place to ask questions - this would be good for a forum post.

**Comment by trusktr** [comment]
@stubailo Thanks for your reply here and at https://github.com/meteor/meteor/issues/4646#issuecomment-116838352!

I'm making [`rocket:module`](https://github.com/trusktr/rocket-module) (more info in [this forum thread](https://forums.meteor.com/t/new-package-rocket-module-to-provide-cjs-amd-es6-modules-for-meteor-packages-with-shared-npm-dependencies/4620) for now, until I update the README at v1.0.0). Rocket:module is depending on the 7-line split (it seems to be consistent across isopack build files).

What rocket:module is (will be) doing (when released) is compiling entry points using Webpack, during app build time, so rocket:module relies on source files from isopacks during app build. Rocket:module will be modifying the isopack build files during app-build so that the isopack files contain the newly compiled version of the source files that a package author originally added with `api.addFiles`. I know, I know, this is a completely unsupported use case. Over at [meteor.com/tool](https://www.meteor.com/tool) it says

> The Meteor Tool is not the only way to write Meteor apps. It's specifically a way to build apps from a command line in a terminal. There can be alternatives to the Tool that tie together all of the same software and services (Isobuild, Developer Accounts, Package Server, and so on) but are oriented around a graphical interface in a web browser or a native IDE.

Rocket:module will be one of those alternatives, although it'll run via the meteor tool itself since rocket:module is a Meteor package.

People who write packages that depend on rocket:module will be publishing to Atmosphere non-built sources (shipped in isopack builds), the rocket:module will handle those sources (using Webpack) during the app build.

The reason the sources need to be handled during app-build is because there will be code-splitting across packages of a given app (thanks to Webpack's code-splitting abilities). It's only possible to detect shared modules across package sources during an app-build, not during a publish build, because obviously during a publish build it's impossible to detect what packages are going to co-exist in any app.

In essence, I've made my own "batch handler" that runs during app build. This is why I'm curious to know when `Plugin.registerCompiler` will be coming out so that I can plan accordingly. I'll have to refactor rocket:module to use `Plugin.registerCompiler` for batch handling. I want to release rocket:module as soon as possible, so that's why I'm not writing it against the `batch-plugins` branch because I don't yet know how long it will take for those features to be released (besides, perhaps it will be nice to support versions of Meteor prior to that for people who haven't upgraded to the latest Meteor).

Lastly, I'm not entirely familiar with the private internal Meteor APIs. Maybe there's a better way to do what I want to do? Is there some way to hook into Meteor so I can get package sources without having to parse the built isopack files?

**Comment by stubailo** [comment]
@trusktr that's why I asked! :]

You can actually download the source code of packages with the package server API: https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API#versions

No parsing needed!

Does that fit your needs?

**Comment by trusktr** [comment]
Oh, also,

> it would be impossible for us to make changes to Meteor if we had to maintain things like line spacing in built output

true, I'll have to keep track of when these things change and have different code for each version. How would you recommend to normalize these things? Is it a matter of establishing the desired behavior, then documenting it in the docs?

**Comment by stubailo** [comment]
I think there might actually be appropriate hooks in Meteor to do the things you want to do without parsing undocumented file formats, as I mentioned above.

**Comment by trusktr** [comment]
@stubailo 

> You can actually download the source code of packages with the package server API

That's cool! I'll have to check that out.

> I think there might actually be appropriate hooks

Do you know where I might find those (or docs on them)?

**Comment by stubailo** [comment]
I think a good start would be asking about the actual things that you need - the problem here isn't "the files are separated by 7 lines" it's "I want the original source code of packages". If you ask the higher-level questions, I might be able to give you the answers you need.

**Comment by trusktr** [comment]
@stubailo Basically I need the source files/chunks of packages that are dependents of rocket:module (source code files/chunks ending with "module.js") so that I can process them app-side instead of publish-side. Then I need to make the app use that new code so I was going to put the code back into the isopacks (replacing the old code). I thought of splitting the isopack sources by the 7 lines, or parsing them somehow, in order to know where to replace source code. Then I would have to adjust the isopack `{os,web.browser,web.cordova}.json` meta files accordingly (file lengths need to be changed for example). I haven't quite gotten to that point yet, but I've tested it manually and the app uses those modified isopacks just fine, which is what I'm currently planning to take advantage of. During publish-build, rocket:module simply injects a comment into the dependent's source that flags the file in-need-for-handling. During app build, rocket:module detects if a file is flagged in order to handle it or not. The isopacks are then essentially a cache piggybacked by rocket:module's own package build process. The ultimate goal of this is to handle shared (npm) dependencies among the packages of a given app. I also hope this helps eliminate the wrapper package abomination from Atmosphere.

I think `Plugin.registerCompiler` is the solution to all this, when that's ready (since the batch handler will run during app-build making it easy to detect what packages co-exist in a given app). :smile: 

Any recommendations for alternative ways to accomplish that?

**Comment by stubailo** [comment]
I think the new batch plugin thing exists exactly for this reason.

Personally what I would do is see what packages are included by parsing the `packages` and `versions` files, use the package server API to get their dependencies, if they depend on `rocket:module` I would download their original source code and compile it with your special module compiler, and then put it into the app with `addJavaScript`. This uses only documented APIs and so is guaranteed to work in future versions of Meteor.

I don't think any solution that modifies built isopacks directly will be maintainable in the face of future updates to Meteor, and might not work well with build caching, deployment, etc. We assume that isopacks are immutable pretty much everywhere, since they are intended to be build artifacts not source files.

**Comment by trusktr** [comment]
@stubailo

> then put it into the app with addJavaScript.

I thought the same thing, but ran into a problem: The package sources need to be loaded in the same exact order as the sources in the isopacks would be, so that dependencies exist when expected (for example, package A depends on package B, both A and B depend on rocket:module, package C depends on package B but no on rocket:module, and now C will load before B due to rocket:module having used `addJavaScript` to add the files to the "app" package, so it breaks when C calls an undefined variable that was needed from B. Inserting the sources back into the isopacks would guarantee that they load in the proper order. `api.addFiles` is what establishes the important ordering of files and package authors need to be able to still use that, so that also causes those added files to go into a package's isopack, which seems to be the only way to guarantee order of execution.

Is there a way to use addJavaScript to add files to a certain package during app build? How exactly were you imagining using addJavaScript?

> I don't think any solution that modifies built isopacks directly will be maintainable in the face of future updates to Meteor

I might have to make sure that my package gets tested at every release of Meteor somehow, unless Plugin.registerCompiler is out soon enough.

**Comment by stubailo** [comment]
Unfortunately I don't have time to think about this too much right now, but you could do something like this: https://github.com/meteor/react-packages/tree/master/packages/react-runtime-dev

The package is compiled with Browserify, and all of the modules are available externally by calling `React.require` - so the modules are compiled at compile-time, but loaded at run-time so that dependencies are loaded in the right order.

**Comment by trusktr** [comment]
@stubailo That's interesting. That's exactly the use case that rocket:module is for, but (unlike with cosmos:browserify) rocket:module will share npm dependencies across packages. See, in that react-runtime package, react is compiled into that package. Now, if another package goes and does the same thing (get react from npm then use cosmos:browserify to compile it) then now that package will have react compiled into to it as well, so it is entirely possible that two packages in an app will contain duplicate libraries of the same exact version.

That's exactly the problem I'm solving with rocket:module, using Webpack (aided by npm dependency handling (I might switch to jspm.io in the future)) to share dependencies across packages by [code splitting them](http://webpack.github.io/docs/code-splitting.html).

**Comment by stubailo** [comment]
@trusktr so that is why I have created a new transform called `externalify`: http://react-in-meteor.readthedocs.org/en/latest/client-npm/#4-configure-browserify-and-transforms-in-appbrowserifyoptionsjson

You can actually then make a new browserify bundle expect to load modules from elsewhere :]

I did this to solve exactly the problem you are describing - it used to be that browserify would load a new React, but now it loads all of its "react/*" dependencies from the Meteor React package, if you use that transform.

With this strategy, it should be possible to bundle any number of NPM modules as Meteor packages, and then have Browserify load them.

**Comment by trusktr** [comment]
@stubailo Is that depending on globals? For example, I see

```js
var externalifyConfig = { external: { jquery: '$', three: 'THREE' } };
```

Are those specifying globals? If so, what about npm packages that don't create globals?

**Comment by stubailo** [comment]
@trusktr ooh awkward - I didn't update the README :]

Basically what it does is it lets you replace `require("x")` with `myRequire("x")`. So you can have a Meteor package export some function that follows the `require` API, and then have a module loaded from there.

So what I have done is have the `react` package export `React.require`, so you can call `React.require('react/lib/invariant')` and get the appropriate module. In the browserify transform, I patch all of the relevant `require` calls. So when `material-ui` does `require('react/lib/invariant')`, it gets replaced with `window.React.require('react/lib/invariant')` and Browserify doesn't bundle a duplicate of React.

Now, this is all somewhat React-specific, but you could do a generalized version - make a Webpack transform or something that uses a global `require` symbol to load modules from Meteor packages in much the same way.

Sorry about that README - I should fix it. These tests will be more useful: https://github.com/meteor/replace-require-functions/blob/master/test.js

**Comment by trusktr** [comment]
That's an interesting solution. Thanks for sharing.

I'm aiming for rocket:module to support AMD and ES6 modules too, plus have the ability for the entry points (the files added with `api.addFiles`) to require/define/import local dependencies--for that I will totally need that API link you shared in order to get sources.

I've never used the DDP api before. Where can I see some code sample of how to use that in Meteor?

**Comment by trusktr** [comment]
@stubailo Nevermind the nvm, I don't have it yet. :laughing: Here's what I'm trying: 

```
> var p = DDP.connect('https://packages.meteor.com')
> p.call('synNewData')
undefined
Error invoking Method 'synNewData': Method not found [404]
```

**Comment by stubailo** [comment]
I think the method is called "syncNewData"?

**Comment by trusktr** [comment]
@stubailo Yep, typo in my post, but using `syncNewData` results in the same error.

**Comment by robertpitt** [comment]
Try this:

```js
DDP.connect("packages.meteor.com", {
    onConnected: function() {
      Packages.connction.call("syncNewPackageData", {format: "1.1"}, function(err, data) {
        console.dir(data);
      })
    }
})```

**Comment by stubailo** [comment]
Let's take this discussion off of this dead issue? Maybe to the forums?

**Comment by trusktr** [comment]
@stubailo @robertpitt Sure, taken to the forums: https://forums.meteor.com/t/how-do-we-access-the-package-server-api-with-ddp/6275/4?u=joe
