### ISSUE TITLE
Support for burst / "token bucket" style rate limiting

### ISSUE THREAD

**Issue by anubhav94** [meteor/meteor#4653]
More details on this [hackpad](https://meteor.hackpad.com/Proposal-Rate-Limiting-in-Meteor-core-HJafA26QtIy)

**Comment by hwillson** [comment]
DDP rate limiting is now supported by Meteor via the [ddp-rate-limiter](https://github.com/meteor/meteor/tree/devel/packages/ddp-rate-limiter) package. Closing this off - thanks!
