### ISSUE TITLE
Allow subscriptions to send non-collection data to the client

### ISSUE THREAD

**Issue by Streemo** [meteor/meteor#4654]
## A minimally invasive way for publication functions to expose basic method behavior

```
//server:
Meteor.publish('pub',function(){
 var x = doSomething(arguments);
 return x;
 /*Meteor internals:
  If x is a cursor, proceed normally with publication.
  Else, call onstop with arguments {error:null, result:x}
 */
}

//client:
onStop = function(error,result){
  if (error)
   displayError(error)
  else
   doSomethingUseful(result)
}
```

This is desired because it results in higher symmetry between publications and the underlying method. If I want to fallback to using the underlying method's features, I should be able to. 

Sending data-on-end (i.e. a result passed as second arg to onStop) is a very useful pattern in method calls and can be similarly useful in "publication calls".
## Another possible syntax to be more unique to publications, and not interfere with returning Cursors:

```
//server:
Meteor.publish('pub',function(){
 var x = doSomething(arguments);
 this.stop(x);
 /*Meteor internals:
  calls onstop with arguments {error:null, result:x}
 */
}
```

Here, it simply allows us to pass an argument to on stop, which will be the result passed to the client. If no argument is passed, onStop behaves normally; result is undefined.
## A slightly more invasive version of the feature, along the lines of version 1:

Instead of having onStop, and onReady callbacks, there should be a single callback that takes arguments `[error, result, ready]` or something similar to avoid dealing with the ugly `callbacks = {onStop:myOnStopFunction, onReady:myOnReadyFunction}` structure.

If the pub is ready, the callback is called with `ready === true`. When the pub is stopped, the same exact callback is called with an error or a result.

**Comment by glasser** [comment]
I think the main issue here is that when we send data to the client, it's not actually tagged with its subscription. We will probably fix that at some point, and when we do so, we should probably allow other data to be sent in a subscription that doesn't fit the default DDP collection/ID/field schema.  This could be used for what you want to do here by sending data at stop time.

The other API design questions are interesting but we are not planning to redesign these JS APIs right now.

**Comment by Streemo** [comment]
Yes, tagging data with sub id would be very useful. I have to do this
manually, so I know which subs are contributing to which documents, etc.

And, it makes querying on the client easier if I can query by subscription.
My current solution is to include a subscription id map which is basically
_.extended onto the documents themselves in the publish functions.

The later design options I mention are for the sake of brevity. atm I'm
using a custom template function (on the instance directly, not a helper)
to generate the callbacks object from a string. I'm storing the callbacks
for the different subscriptions in a custom Template.callbackDictionary
object. not sure if that's the best solution, but it allows to not
reconstruct the functions on the fly.

**Comment by mitar** [comment]
Related, I asked for custom values to be able to be passed to `ready`: #1202

**Comment by mitar** [comment]
I think this package might help you: https://github.com/peerlibrary/meteor-subscription-data

**Comment by mitar** [comment]
And for tagging based on subscription ID: https://github.com/peerlibrary/meteor-subscription-scope

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20subscriptions%20to%20send%20non-collection%20data%20to%20the%20client&body=Migrated%20from:%20meteor/meteor%234654) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
