### ISSUE TITLE
Meteor.wrapAsync: callback is first function, not last function

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4655]
Suppose a function accept multiple functions and an async callback. It appears `Meteor.wrapAsync` will assume the first function is a callback, not the last function.

```js
a = function(b, callback) {
  console.log(b, callback)
}
f = Meteor.wrapAsync(a)
console.log(f(b))
// > [Function] undefined
```

**Comment by ccorcos** [comment]
More discussion here: https://forums.meteor.com/t/how-do-fibers-and-meteor-asyncwrap-work/6087/20

**Comment by glasser** [comment]
If the last function that you *actually pass* to a wrapped function is a callback, then that is treated as the callback. Otherwise it goes into sync mode.  `Meteor.wrapAsync` does not pretend that it knows how many arguments the wrapped function expects. This is working as intended.

**Comment by ccorcos** [comment]
Ahh. So what makes this challenging is that `Meteor.wrapAsync` will behave with a callback is you pass one... As opposed to always running sync like this:

```coffee
Future = Npm.require('fibers/future')

syncify = (f) ->
  (args...) ->
    fut = new Future()
    callback = Meteor.bindEnvironment (error, result) ->
      if error
        fut.throw(error)
      else
        fut.return(result)
    f.apply(this, R.append(callback, args))
    return fut.wait()
```
