### ISSUE TITLE
How to use the Meteor Package Server API

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4656]
I'm looking at this document but I can't figure out how to get information about a package off the server...

https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API

I connect with `DDP.connect`, but then what collections / subscriptions / methods do I use to look up a package?

**Comment by stubailo** [comment]
You have to use the "syncNewPackageData(syncToken)" method to sync all of the data at once. It wasn't designed for subscribing directly, but rather for having a local cache of all of the data if you were building a command line tool or package search website.

**Comment by ccorcos** [comment]
Ahh. now I get it. Thanks

**Comment by robertpitt** [comment]
```js
DDP.connect("packages.meteor.com", {
  onConnected: function() {
    Packages.connction.call("syncNewPackageData", {format: "1.1"}, function(err, data) {
      console.dir(data.collections);
    })
  }
})```

**Comment by ccorcos** [comment]
Thanks @robertpitt

**Comment by stubailo** [comment]
Here is a forum thread about this: https://forums.meteor.com/t/how-do-we-access-the-package-server-api-with-ddp/6275

**Comment by ccorcos** [comment]
thanks, we'll continue there
