### ISSUE TITLE
Array field exclusion not consistent with MongoDB - results in problems in pub/sub

### ISSUE THREAD

**Issue by tgoorden** [meteor/meteor#4657]
When excluding a field using field exclusion, e.g.:
```
   MyCollection.find({},{fields:{my_array:0}});
```
where `my_array` is in fact an array field and has content in it, Meteor will produce on both the client *and* the server side a document like this:
```
   {
      _id: ...,
      my_array: Array[0]
   }
```
Whereas the same query directly on the same collection MongoDB:
```
  db.my_collection.find({},{my_array:0})
```
will *not* include the `my_array` field at all.

This is highly problematic for pub-sub scenarios where you subscribe to the same collection twice, e.g. once with a more "detailed" view on a specific document and once with a "reduced" view on a lot more documents. For non-array fields, the subscriptions automatically merge the fields, but in this case, the `Array[0]` seems to sometimes "win" (I guess the subscriptions overwrite each other). In other words, the MongoDB approach (effectively excluding the field) seems like the correct one.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
