### ISSUE TITLE
Move GitHub wiki content to a place where people can contribute

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4658]
It's not editable. And the [Contributing to Meteor](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor) doesn't say how to contribute to the Wiki.

There's lot of missing info that I can add as I learn things. For example, the [Package Server API](https://github.com/meteor/meteor/wiki/Meteor-Package-Server-API) page doesn't say exactly how you use `syncNewPackageData(syncToken)`.

Actual code examples would be great to add, for example:

> Start with an empty syncToken object and make the call:
>
> ```js
> var syncToken = {};
> var chunk = p.call('syncNewPackageData', syncToken);
> ```
>
> You will now have a chunk object with a bunch of stuff, including:
> - chunk.syncToken - the next syncToken to use for the next chunk (pass this into the call).
> - chunk.collections - the package data as described below.

That would be very helpful.

The Wikis are just git repos. Can you host a public repo that we can make PRs into? Then someone awesome at MDG can simply merge the public repo into the wiki repo.

**Comment by stubailo** [comment]
This is a good point - there is no easy way to suggest updates to the GitHub wiki. It seems like it would be pretty hard to keep an external repo up to date without a lot of manual work, and I would hate to end up in a situation with two sources of data that are meant to be the same but are slightly out of sync.

Maybe the right solution to this is to avoid using GitHub wikis altogether; they have a lot of problems:

1. Impossible to redirect URLs
2. Impossible to file pull requests
3. Sidebar/index management is terrible
4. No automatic table of contents for pages

I recently went through and updated the sidebar, but it was only a small improvement. I think moving everything to `docs.meteor.com` and away from the Wiki would be great. What do you think?

**Comment by stubailo** [comment]
@zhenyasav @dominicnguyen something for you. You might also want to look at all of the `Project:Docs` issues.

**Comment by trusktr** [comment]
@stubailo Yeah, moving all to docs.meteor.com would be awesome.

**Comment by abernix** [comment]
This was a great suggestion.  Through a lot of work from a lot of people, the Wiki has all been moved to `.md` files on Git projects ([Contributing, for example](https://github.com/meteor/meteor/blob/devel/Contributing.md)) and [docs](http://docs.meteor.com/)<sub>([repo](https://github.com/meteor/docs/))</sub> and [guide](http://guide.meteor.com/)<sub>([repo](https://github.com/meteor/guide/))</sub> now accept pull requests (and their own issues!)

RIP https://github.com/meteor/meteor/wiki

Closing this. :)
