### ISSUE TITLE
Copy text from full docs to `meteor help` output

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4659]
Sometimes there is more information here:

http://docs.meteor.com/#/full/meteorhelp

than in the output of `meteor help X`. I think all or most of it should be included in the command line output because it's helpful/important things that people using the commands may need to know, and when they're using the command line help, they may not know that there is a more complete command line help in the online docs or think to look there. 

One example is if I want to update to a new major version of a package, `meteor help update` (and `meteor help add`, if I think to look there) doesn't tell me how, and I get stuck. I don't know that I have to read http://docs.meteor.com/#/full/meteoradd to learn about the `@version` add format.

**Comment by stubailo** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

In this case, it would be great to have some way by which the `meteor help` command and the `docs/` app could share this content.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Copy%20text%20from%20full%20docs%20to%20%60meteor%20help%60%20output&body=Migrated%20from:%20meteor/meteor%234659) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
