### ISSUE TITLE
Can't use 'created' name asi identifier in spacebars

### ISSUE THREAD

**Issue by Joe32** [meteor/meteor#4664]
Consider having helper

    Template.orders.helpers({
        "orders": function () {
            return [
                {"created": "1.1.1970"}
            ];
        }
    })

and in html 

```
{{#each orders}}
    {{ created}} 
{{/each}}
````
Does not work, when i change created to something else it works. Maybe some warning should be outputted to console?

**Comment by stubailo** [comment]
Hi @Joe32!

I put that code into a newly created Meteor app, and everything worked fine. I also scoured the Meteor codebase for instances of the word `create` and nothing came up.

Are you sure you don't have a helper called `create` somewhere which is overriding this field? It could also be defined in a package you are using. If you can provide a reproduction where this happens in a simple app, I can reopen the issue.
