### ISSUE TITLE
Add ability to check if a method was called from the client or server

### ISSUE THREAD

**Issue by dolgarev** [meteor/meteor#4665]
Hello guys!

I faced a problem, which I couldn't solve without some magic involvement. I needed to create a method to be avaluable for call only on server side. I googled this solution [https://github.com/themeteorchef/server-only-methods] but I quickly hacked it.

Here is an example of code (for server side):

``` js
Meteor.startup ->
  Meteor.methods
    'test1': -> console.log '@connection1', @connection
    'test2': ->
      console.log '@connection2', @connection
      Meteor.call 'test1'

  Meteor.call 'test2'
```

I see the result

``` js
@connection2 null
@connection1 null
```

Then I do a method call in the browser console

``` js
Meteor.call 'test2'
```

And I see the new result

``` js
@connection2 { id: '5XAZcKXtDvqKoyNuH', close: [Function], etc... } 
@connection1 { id: '5XAZcKXtDvqKoyNuH', close: [Function], etc... } 
```

We see that "method invocation object" was passed from the method test2 to the method test1. I don't think this is a bug, although method test1 was called in fact on server side, that is why we can expect that property connection is null.

I suggest to add new property to "method invocation object", and I propose to call it invocationContext, which would have value 'server' or 'client' depending on place in a code, where we try to call a Meteor's method.

**Comment by stubailo** [comment]
I'm curious what the use case is for this feature. What would you do in a server-only method that you can't do in a plain JavaScript function that exists only on the server?

Methods exist specifically for the use case of exposing code that can be called from a DDP client, so this doesn't seem to me like a good place to use a Meteor method. We should probably make the docs for methods more clear on this point.

In the meantime, I'll still leave this open for possible discussion as a feature request. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
Comment https://github.com/meteor/meteor/issues/4665#issuecomment-119343885 sums up why server side only Method's aren't needed, and the Meteor Guide [Methods](https://guide.meteor.com/methods.html) section (created after this issue was posted) does a good job at explaining this further (for example, by referring to Methods as Meteor’s remote procedure call (RPC) system). As part of the old issue cleanup process, I'll close this off. Thanks!
