### ISSUE TITLE
spiderable: phantomjs failed: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

### ISSUE THREAD

**Issue by meichenblatt** [meteor/meteor#4667]
Im getting a slightly different error than most when using spiderable and phantom:

spiderable: phantomjs failed: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

Any ideas?

**Comment by gchpaco** [comment]
Per the man page, ENOENT means:
> [ENOENT] The new process file does not exist.
Usually that means that you're trying to run a command that doesn't exist at that location in the filesystem.  Could you double check that the file exists and is readable by the process?

**Comment by meichenblatt** [comment]
I installed the smart package: gadicohen:phantomjs

**Comment by gchpaco** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by meichenblatt** [comment]
Ok I follow the guide lines on reporting a bug. Here is the repository:

https://github.com/meichenblatt/meteor-phantom-issue

**Comment by abernix** [comment]
Closing as the reproduction seems to work fine for me, and this issue is fairly old and hasn't got much attention from others with similar problems.  Please try a newer version of Meteor! :smile:

**Comment by kenshinman** [comment]
I have same issue, any fix yet?

**Comment by colasjun** [comment]
I close my terminal and then open agin and try it, that is ok.
