### ISSUE TITLE
Support CoffeeScript and React

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4668]
With Meteor 1.2 and React support, could you also support writing React in CoffeeScript?

**Comment by ccorcos** [comment]
I do it all the time! It works quite well too.

1) To be able to use a class as a function, you need to use React.createFactory. I use a function like this in all my projects: `createView = compose(React.createFactory, React.createClass)`.

2) Now with your components, including `React.DOM` components, the first argument is a props object and the rest of the arguments are children. I prefer to use a more Lisp-like syntax -- one of the perks of coffeescript is the flexibility of the syntax. Rather then so this: `div({}, child1, child2)`, I like to do it like this: `(div {}, child1, child2)`, and you don't need any commas between the children if you use a return. Also `do =>` comes in handy a lot as well:

```coffee
Item = createView
  displayName: 'item'
  render: ->
    {div} = React.DOM
    (div {className:'item'},
      @props.name
      do => if @props.unverified then "*"
    )
```

**Comment by stubailo** [comment]
Continue this discussion here: https://github.com/meteor/react-packages/issues/6

In the short term we are keeping discussion of the new React features on that repo.
