### ISSUE TITLE
Setting arch to "client" to added file produces web.browser build but not web.cordova build.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4669]
For example, in the package.js of a local package of my app I have

```js
Package.onUse(function(api) {
    api.versionsFrom('1.1.0.2')

    api.use([
        'rocket:module'
    ], 'client')

    api.addFiles(['module.js'], 'client')
    api.addFiles(['blah.js'], 'client')
    api.addFiles(['foo.js'], 'client', { bare: true })

    api.export('Lib', 'client')
})
```

The isopack (in `.meteor/local/isopacks`) contains only a build for `web.browser`.

Another package, this one not local, shipped on Atmosphere, has a package.js containing

```js
Package.onUse(function(api) {
    api.versionsFrom('1.1.0.2')

    api.use([
        'rocket:module@0.1.1_1'
    ], 'client')

    api.addFiles('client.module.js', 'client')
    api.addFiles('foo/bar.module.js', 'client')

    api.export('Lib', 'client')
})
```

The isopack for that one (in `~/.meteor/packages/`) contains a build for both `web.browser` and `web.cordova`.

In both packages, the architecture is specified as `'client'`, yet only one of the packages builds for `web.cordova`.

Why might this be? Is there be a bug? Do local packages only build for `web.browser`? (I'll push a repo if needed.)

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Please also include which files you are expecting to exist and where.

**Comment by glasser** [comment]
This is working as intended.  Local isopacks in your app's local isopack cache are built in the context of your app.  If your app is not being built for cordova platforms, we don't waste time building `web.cordova` unibuilds.  On the other hand, when publishing a package to Atmosphere, we always publish `web.cordova` unibuilds.

**Comment by trusktr** [comment]
@glasser Interesting. So when I run something like `meteor run android`, will it build the cordova unibuilds at that time?

**Comment by glasser** [comment]
Well, you have to `meteor add-platform android` first, and that (the contents of `.meteor/platforms`) determines if they are built.
