### ISSUE TITLE
can't configure network interface for second node process in meteor stack

### ISSUE THREAD

**Issue by divitoDBA** [meteor/meteor#4670]
I start meteor with the following command: meteor --port 192.168.0.107:8080

First node process binds to given server:port as expected, but the second node process (started once connection with Mongo is established OK) listens in all interfaces - exampe TCP *:26758 (LISTEN) instead of binding to 192.168.0.107 only.

Is this an expected behavior or is it a bug ?

LSOF evidence: 

lsof |grep meteor |grep LISTEN  |grep node
node      13128               meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
SignalSen 13128 13141         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13128 13143         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13128 13144         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13128 13145         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13128 13146         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13128 13206         meteor   13u     IPv4             244552       0t0        TCP oel70.node.com:webcache (LISTEN)
node      13205               meteor   11u     IPv4             244597       0t0        TCP localhost:36099 (LISTEN)
node      13205               meteor   25u     IPv4             244618       0t0        TCP *:26758 (LISTEN)
node      13205 13209         meteor   11u     IPv4             244597       0t0        TCP localhost:36099 (LISTEN)
node      13205 13209         meteor   25u     IPv4             244618       0t0        TCP *:26758 (LISTEN)
node      13205 13210         meteor   11u     IPv4             244597       0t0        TCP localhost:36099 (LISTEN)
node      13205 13210         meteor   25u     IPv4             244618       0t0        TCP *:26758 (LISTEN)
node      13205 13211         meteor   11u     IPv4             244597       0t0        TCP localhost:36099 (LISTEN)
node      13205 13211         meteor   25u     IPv4             244618       0t0        TCP *:26758 (LISTEN)
node      13205 13212         meteor   11u     IPv4             244597       0t0        TCP localhost:36099 (LISTEN)
node      13205 13212         meteor   25u     IPv4             244618       0t0        TCP *:26758 (LISTEN)

**Comment by glasser** [comment]
You can control the inner app port (including interface) with `--app-port`.
