### ISSUE TITLE
HAXM El Capitan 10.11 Support

### ISSUE THREAD

**Issue by romant** [meteor/meteor#4671]
##  Please note:
![screen shot 2015-07-02 at 14 19 55](https://cloud.githubusercontent.com/assets/49066/8469889/bd27170a-20c5-11e5-9df2-1eb3202940e8.png)
![screen shot 2015-07-02 at 14 20 10](https://cloud.githubusercontent.com/assets/49066/8469890/bd299106-20c5-11e5-9413-926cb606bad9.png)

**Comment by Tarang** [comment]
There's probably not much that can be done about this. Intel would need to update their package.

**Comment by romant** [comment]
Agreed @Tarang. Just mentioning it for anyone even attempting as an FYI.

**Comment by martijnwalraven** [comment]
Thanks for mentioning this, good to know. I don't think there is anything we can do except wait until Intel updates the HAXM kernel extension, but hopefully that will happen soon after OS X 10.11 is released.

**Comment by aramk** [comment]
Are you guys able to still build the android cordova project after updating to El Capitan? I'm able to run the simulator and it's slow as it promised, but the build is failing in weird ways. I'll try to reinstall the SDK.

**Comment by martijnwalraven** [comment]
Support for El Capitan has been available for a while now, so closing this issue:
https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager
