### ISSUE TITLE
No mechanism to validate or prevent Accounts.forgotPassword and Accounts.verifyEmail from sending email

### ISSUE THREAD

**Issue by burgaard** [meteor/meteor#4673]
I can't find a way to validate or control `Accounts.forgotPassword()` and `Accounts.verifyEmail()` requests from the client. I think that would be a concern to anyone using the `accounts-password` package.

Primary concern: Any meteor site using the `accounts-password` package and `MAIL_URL` configured to a valid SMTP service could be turned into both the source and victim of a simple DoS attack:
1. Open meteor website in browser
2. Obtain username or email address of user known to have account on the site
3. Open JavaScript console
4. Enter forever loop that calls Accounts.forgotPassword

Result:
- The client can send those requests much, much faster than the server can process them. As a minimum, database performance and other outgoing emails timeliness could be affected.
- A poor user is going to have her/his email inbox flooded.
- The website risks using up its SMTP quota, potentially at a lot of additional cost and/or blacklisting as a spam site.

As a minimum, I'd like fine grained control over all methods a la `Accounts.config.forbidClientCreation`, for example by adding:
- `Accounts.config.forbidClientForgotPasswordRequest`
- `Accounts.config.forbidClientVerifyEmailRequest`

And/or, provide server-side hooks where throwing an `Error` would stop the request:
- `Accounts.onSendResetPasswordEmail`
- `Accounts.onSendVerificationEmail`

**Comment by burgaard** [comment]
Actually, if the site allows client-side user creation, you don't even need to guess an existing user. Just try to call Accounts.createUser first and see if the call goes through...

**Comment by stubailo** [comment]
@anubhav94, does your rate-limiting project solve this?

**Comment by burgaard** [comment]
I'd like to submit a pull-request because I don't want to deploy any Meteor application without some measure in place to prevent clients from using the server to send emails. I've implemented a solution that introduces callback hooks from respectively `Accounts.sendResetPasswordEmail`, `Accounts.sendEnrollmentEmail`, and `Accounts.sendVerificationEmail`. I chose that approach because it doesn't change anything else either on the server or client.

However, at this moment, checking out meteor on the devel branch and running `meteor test-packages accounts-password` without making any changes results in 33 failed tests out of 35. Am I missing something?

**Comment by anubhav94** [comment]
Hi @burgaard! We've actually been working on a rate limiting addition to Meteor core that provides exactly the support you mention out of the box. There is even a default rule added to prevent password resets, create users and login attempts to a reasonable limit. You can check out our PR #4675  and provide feedback on our [post](https://forums.meteor.com/t/proposal-rate-limiting-in-meteor-core/6152) in the forums.

**Comment by burgaard** [comment]
Hi @anubhav94,

Maybe this is just terminology, but it sounds like your solution is concerned with throttling? That's certainly one way to address DoS concerns, but it still doesn't let me control when and how emails are generated.

I think your proposal is great and I will definitely use it, but it still doesn't change the fact that I'd like to be able to customize behavior regarding emails for password reset, enrollment and email verification. There are hooks for customizing account creation and validation, so it seems a bit strange actually that the current implementation doesn't allow any custom logic or workflow to be created around sending emails.

For example, what if I need to use a legacy interface for sending my emails?

Furthermore, unless the rate limiter stops the reset password flow altogether, the user's account state will have been modified even before the email is sent -- in this case by having the current password reset.

**Comment by stubailo** [comment]
> unless the rate limiter stops the reset password flow altogether

It does - it intercepts the server call at the DDP level.

It's true that right now the accounts-password package currently doesn't have much customization around how emails for these things are sent. With the rate limiter, one workaround would be to set the rate limit to 0 for these methods and implement your own email sending and password reset logic.

**Comment by burgaard** [comment]
Ok, that'll work short term, i.e. please don't close this issue with PR #4675.

What's the outlook for PR #4675 being made available in a general release?

**Comment by burgaard** [comment]
And again, I'd be happy to contribute code that implements server-side hooks and/or Accounts.config options. Just let me know...

**Comment by stubailo** [comment]
Yeah I think the next step would be to split out the Accounts email functionality from the accounts-password package itself, so that it can be easily overridden.

Then, you can either add the `accounts-password-email` package, or add your own that implements the same API to do whatever you want with emails. I would look at a PR that factors out this functionality.

**Comment by burgaard** [comment]
Great idea. I've posted a proposal to the Meteor forum: https://forums.meteor.com/t/proposal-refactor-email-handling-in-accounts-password-to-separate-package/6405

**Comment by greg-ashby** [comment]
Hi @burgaard, I'm writing my first Meteor app and just noticed the same issue when I realized Accounts.forgotPassword was a client side call. Was wondering what you ended up doing to address this since I didn't see any activity on the issue or proposal since last year?

The other concern I had was that Accounts.forgotPassword will include a "user does not exist" message if the email address isn't in the system. I'm surprised that's the default behavior as it makes it fairly easy to determine if an email address is a valid account. Is that a legitimate concern as well? Should it be in scope for this issue or posted as a separate one? Thanks!

**Comment by greg-ashby** [comment]
I didn't see anything in the docs indicating the requested hooks or possible package refactorings had happened, so in lieu of a better solution, I've done something a little (lot?) unorthodox for now.

Basically in my startup function, I grab the original forgotPassword function and wrap it with another function that allows me to sanitize the error if its due to the email not being an account:

```javascript
var originalFunction = Accounts._server.method_handlers.forgotPassword;
var newFunction = function (options) {
    try {
        return originalFunction(options);
    } catch (err) {
        if (err.reason === 'User not found') {
            // Fail silently - Don't confirm if the email exists or not, just tell the user to check their inbox.
            // This does fail really quickly though, so might still be open to a timing attack?
        } else {
            throw err;
        }
    }
};
Accounts._server.method_handlers.forgotPassword = newFunction;
```

I'm uber new to Meteor (and full stack javascript in general) so would appreciate any feedback on why that's a horrible thing to do ;)

Also relatively new to Github and the Meteor Forums, so if I should be posting this elsewhere to discuss, please do correct me - thanks!

**Comment by burgaard** [comment]
Hi Greg,

Sorry for the late reply. Shortly after posting about this, I realized I was budding heads with a number of areas in the Meteor framework and decided to go with a vanilla node.js + various npm packages instead. So, TLDR, I haven’t looked at this stuff since posting the comments you’re writing me about. Sorry!

Best of luck,
Kim

**Comment by greg-ashby** [comment]
No worries Kim, sorry to hear you had to abandon ship. That's the only thing I butted up against so far and that hack seems to work for now, so hopefully I won't come to the same fate. Good luck!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=No%20mechanism%20to%20validate%20or%20prevent%20Accounts.forgotPassword%20and%20Accounts.verifyEmail%20from%20sending%20email&body=Migrated%20from:%20meteor/meteor%234673) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
