### ISSUE TITLE
Batch DDP updates?

### ISSUE THREAD

**Issue by ryan-williams** [meteor/meteor#4674]
I documented lots of performance issues and characteristics of Blaze and React rendering simple 100-1000 row HTML tables in Chrome, Firefox, and Safari on [this Meteor forums thread](https://forums.meteor.com/t/rendering-an-html-table-with-up-to-2000-rows-very-slow-in-chrome/6356), and @debergalis suggested I post an issue about it to make sure the right people see it.

The main takeaway is that some things seem to render quite slowly today at data-sizes where they should be performant, and that batching DDP updates and/or Blaze↔︎DOM interactions may improve the situation considerably.

I'm hopeful is that React is faster enough in its DOM-interacting than Blaze that I will personally be unblocked here for the short term, but even in the faster React benchmarks I posted on the forums thread, some room for improvement is clearly apparent.

**Comment by gchpaco** [comment]
I would very much like to add batches to the DDP protocol, but that would require a DDP protocol revision.  Accordingly I do not think it will get done before 1.2.

**Comment by ryan-williams** [comment]
Thanks @gchpaco, that makes sense.

Thinking about this more, it seems like the thing that was really feeling "off" to me on the forum thread was that it seemed clear that the DOM re-render was blocking more DDP updates from being processed.

I would see a sequence of events like: 
* 30 items are sent to the client from the server, then the client DOM freezes while re-rendering.
* While the DOM is re-rendering, the server has sent, or attempted to send, the remaining 70 items.
* However, when the DOM finishes renderering the first 30 items, it pulls in a few more updates, then does a stop-the-world re-render with, say, 35 items.
* it goes on like this for seconds or minutes, performing stale, marginal re-renders, when the server has long since finished sending all of the data to the client.

Even given slow DOM re-renders, it "should" at least just render the freshest possible snapshot of the data each time it attempts to re-render the DOM.

I just wanted to try to articulate this since I wasn't sure "batching DDP" really describes how to fix this phenomenon: that applying DDP data updates should be un-blocked / not interrupted by DOM re-renders, if possible.

Not sure if that makes sense or is an accurate impression of the interplay between the components in the underlying infrastructure, but that's my take on one thing that felt "off" to me. Thanks!

**Comment by gchpaco** [comment]
It's really hard to do true parallelism in a single threaded cooperatively multitasked environment like the browser.  What you describe is very possible, and I'll have to engage some folks to establish if it is actually a problem.  The danger there is essentially starvation; if the DDP session sends updates fast enough, it's possible the client will never actually stop to update the UI.  I could well believe we might be at the wrong balance point, though.

**Comment by ryan-williams** [comment]
That makes sense, thanks again @gchpaco!

**Comment by abernix** [comment]
Completed (a while ago1) in #5680.   Thanks for filing this originally! :)
