### ISSUE TITLE
Cannot update a mongo document with an EJSON value if property was not inserted as an EJSON value first.

### ISSUE THREAD

**Issue by Jahdrien** [meteor/meteor#4676]
This bug seems to be related to MongoDB version since it only happens when deploying to meteor.com (mongodb 2.6.7). Localy with MongoDB 3.0 everything is fine.

On meteor.com, updating a document property to an EJSON value fails when initial value was not inserted as an EJSON value.

Exemple:
Collection.insert({date: moment()}) then Collection.update(ObjectId, {$set: {date: moment().add(1, 'hour')}}) is OK

But:
Collection.insert({}) then Collection.update(ObjectId, {$set: {date: moment()}}) fails with "Not ok for storage" server side and client side.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

(eg, I don't know if you're registering moment as an EJSON custom type.)
