### ISSUE TITLE
account-password pkg.maybe can little improve

### ISSUE THREAD

**Issue by backsapce** [meteor/meteor#4677]
password_server.js---line 203 function  Accounts.registerLoginHandler
i think it can be improve.this week i try to extend meteor account sys,we want to login with phone number. so we create a pkg and  registerLogin a Handler like this 
```js
Meteor.loginWithPhone = function(phone, password, callback) {
	Accounts.callLoginMethod({
		methodArguments: [{
			phone_login: true,
			phone: phone,
			password: Accounts._hashPassword(password),
		}],
		userCallback: callback
	});
};
```
i don't  set a user filed in methodArguments.
but in password_server.js  it check like this
```js
  check(options, {
    user: userQueryValidator,
    password: passwordValidator
  });
```
so in my project's packages file if the account-password'position is upper than my package.this means my handler regist later than password.when i call my login method.it will throw an MATCH ERROR.

i suggest set a flag to mark the login handler.
in  client
```js
Meteor.loginWithPhone = function(phone, password, callback) {
	Accounts.callLoginMethod({
		methodArguments: [{
			password_login: true,    //set a flag to verify
			user: selector,
                    password: Accounts._hashPassword(password)
		}],
		userCallback: callback
	});
};
``` 
and in server when enter in a handler,we check the flag first.
because of this issue.when i want to write a new login method that with args different from the account-password.i must put it name upper than "account-password". if i don't do it,it will throw Error and destroy the account system.
so can i set a pr to fix?  :)
forgive me my poor english.

**Comment by stubailo** [comment]
Right now, this is how the login handlers work - the easiest workaround would be to use a field called something other than `password` for your handler.

**Comment by abernix** [comment]
Closing as this hasn't really developed into a feature request.  If this is something you'd like to see included in a future version of Meteor, please read the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).  Thanks! :)
