### ISSUE TITLE
Deployment :The site has crashed

### ISSUE THREAD

**Issue by Shekharrajak** [meteor/meteor#4679]
Why many times I am not able to deploy my app in meteor.com

This site has crashed.
Site administrators can examine the logs with:
meteor logs appname.meteor.com

But the app is working fine in my localhost.

**Comment by Tarang** [comment]
You should run `meteor logs appname.meteor.com` to get a bit more info about why it's crashed.

The information you've provided alone isn't sufficiently helpful to know what the issue is.

**Comment by Shekharrajak** [comment]
Most of the time it is just :
This site is loading..

and then retrying again and again.without telling Site administrators can examine the logs with:
meteor logs appname.meteor.com

**Comment by Tarang** [comment]
@Shekharrajak The logs do not look like this. If you visit the app from your web browser it will do this.

On your computer you need to run `meteor logs appname.meteor.com` for further information, where appname.meteor.com is where your app is deployed to.

**Comment by glasser** [comment]
Thanks for helping, @Tarang !
