### ISSUE TITLE
Need change poll time period. Is possible ?

### ISSUE THREAD

**Issue by eportico** [meteor/meteor#4680]
I need change polling time period why I have many changes in data and It changes trigger many queries. I need "intregrate" this changes in a time period more long.

Thanks

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

I would recommend using the Oplog Observe Driver instead of polling for better scalability.
