### ISSUE TITLE
missing semi colon when new style rule is added

### ISSUE THREAD

**Issue by peernohell** [meteor/meteor#4681]
In a DOM element, if you have a rule with a value that are conditioned by a helper and this helper return an empty value, the rule is removed. But if the value reactively change the rule is append in the end of the style attribute. But if it didn't finish by a semi colon, Balze didn't add it and the style is brocken. 
 
  For an exemple you can see this meteorpad: http://meteorpad.com/pad/r4FyvBwHryBWkK9vm/Leaderboard

Some detail:
the template:
````
<div id="logo" style="background-color:{{bgColor}};padding: 10px">change my color</div>
```

The DOM after loading:
```
<div id="logo" style="padding: 10px">change my color</div>
```

The DOM after clicking a buton that change {{bgColor}} to red:
```
<div id="logo" style="padding: 10px background-color:red;">change my color</div>
````

**Comment by stubailo** [comment]
This is a real bug I think; it results from this code here, which simply concatenates the attributes with a space: https://github.com/meteor/meteor/blob/d634651232f66839b3467152cd046ec6887351b7/packages/blaze/attrs.js#L90

We probably want the attribute handlers to be able to define their own concatenation logic so that style can be semicolon-separated.

**Comment by glasser** [comment]
are extra semicolons a problem or can we just add like a zillion semicolons everywhere?

**Comment by stubailo** [comment]
@glasser Good question! It might be OK but needs to be tested in a variety of browsers. I wouldn't be surprised if some browsers complain about extra semicolons.

**Comment by glasser** [comment]
;;;;; good; point ;; ! ;

**Comment by stubailo** [comment]
Syntax error:1:1
- At <glasser commented 8 minutes ago>

**Comment by laosb** [comment]
Never have this problem since I always keep a semicolon after a rule :) However always putting a semicolon after a rule should be general knowledge.

**Comment by peernohell** [comment]
I know the workaround but it's valid CSS and hard to detect. It would be nice if Blaze support it.

**Comment by hwillson** [comment]
Moved this over to the Blaze repo as meteor/blaze#141 - this issue can be closed.

**Comment by stubailo** [comment]
Thanks!
