### ISSUE TITLE
Bug in how Meteor makes package dependency choices

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4684]
There's something wonky in how Meteor chooses which version of a package to install when installing a package that depends on an older version of a package that's already installed.

Simplest way to illustrate this:

```
$ meteor create test; cd $_
$ meteor add aldeed:autoform
$ meteor add orionjs:core
```

Note that Meteor chooses to install version 0.7.7 of Orion, even though 1.1.0 is out.

Full thread here:
https://forums.meteor.com/t/weird-package-dependency-problem-need-help/6446

**Comment by gchpaco** [comment]
This is actually the dependency resolver doing as it is supposed to when you try to install two packages that don't like one another, and preferring not to forcibly upgrade packages you have specified.  If I run your harness in the order you gave, it installs `autoform` 5.3.2 and `orionjs:core` 0.7.7, but if I switch them it installs `orionjs:core` 1.1.0, which depends on `autoform` 5.1.1 (although it installs 5.1.2).  The guilty file appears to be (https://github.com/orionjs/orion/blob/master/packages/attributes/package.js#L14)[part of the attributes package].  You should probably file a bug with the orion folks and ask them to correct that.
