### ISSUE TITLE
emails are not published to clients

### ISSUE THREAD

**Issue by Zane-XY** [meteor/meteor#4685]
From the documentation http://docs.meteor.com/#/full/meteor_users

> By default, the current user's username, emails and profile are published to the client. 

but when I run `Meteor.user()` in the client console, I didn't get the emails field:

```
Meteor.user()
Object { _id: "vK5ddWtypCewCwbSL", profile: Object }
```

I am using account-google, with autopublish removed.

**Comment by Tarang** [comment]
If the email is available with `accounts-google` it will be in the profile object above.

**Comment by Zane-XY** [comment]
@Tarang No, the profile only contains name.

```
Meteor.user().profile
Object { name: "XXX" }
```

I think it probably requires me to manually publish it from `users` collection, but this is an obvious error in the doc, or it's a bug in the account-google package. 

In this case, it didn't publish emails by default, it only publishes userId, profile object contains only a name.

**Comment by Tarang** [comment]
@Zane-XY The docs are correct in this regard. The `emails` array is only filled up if you add an email to the user manually, or you use `accounts-password` and sign up with an email.

The `emails` field isn't relevant to any other accounts-* package

**Comment by stubailo** [comment]
Yep, this is a combination of several problems:

1. The example user document doesn't say that some parts are only relevant to `accounts-password`
2. The example user document has _both_ facebook and password data, which is not an officially supported feature (you probably need a community package for this)
3. It's not clear from the documentation for external login services which fields they provide and which of those fields are public

I think there is a good case here for the documentation being improved, will tag it as such.

I will also look at a PR for this improvement if someone files one before me.

**Comment by hwillson** [comment]
I've moved this over to the docs repo: meteor/docs#114. Thanks for reporting this originally!
