### ISSUE TITLE
allow users to delete their packages from atmosphere

### ISSUE THREAD

**Issue by bevanhunt** [meteor/meteor#4687]
please allow users to delete their own packages from atmosphere.

**Comment by zardak** [comment]
https://atmospherejs.com/i/faq

> ### How do I delete a package?
> You can’t delete a package (what if someone else is using it?!), but you can mark it “unmigrated”. This will prevent it from appearing in Atmosphere’s search results:
> `meteor admin set-unmigrated [packagename]`

**Comment by glasser** [comment]
Duplicate of #2459.
