### ISSUE TITLE
Conditional compilation (utilising UglifyJS)

### ISSUE THREAD

**Issue by robertpitt** [meteor/meteor#4688]
So looking at some of the Meteor Internals it seems you are using UglifyJS to compile JavaScript, which is  great but I think there is one feature that we could all utilise and that's Conditional Compilation.

### Example
```javascript
if(Meteor.DEBUG) {
    console.log("Some debug info %o", Obj);
}
```

I was thinking that we could pass environment variables via the meteor command such as `JS_ARGS='-d Meteor.DEBUG=true' meteor run|build` allowing code to be removed/added in build time.

Are there any problems around implementing this feature?

Source: https://github.com/mishoo/UglifyJS2#conditional-compilation

**Comment by glasser** [comment]
We're currently making the minifier stage pluggable via modules instead of hardcoded into the tool, which should allow the community to implement this without core changes.

**Comment by hems** [comment]
@glasser / @robertpitt is there an updated solution for this issue ?

I would love to compile `javascript` code on my frontend with different configurations depending on which environment i'm building for..

For instance if it's 'production' i would like some stuff to be included, if it's not i would like to show extra features on the frontend that still being developed without adding that source to the production build

any  suggestions?
