### ISSUE TITLE
Website Docs / Tutorial / Simple Todos: missing helper in example code

### ISSUE THREAD

**Issue by sgates** [meteor/meteor#4689]
https://www.meteor.com/tutorials/blaze/publish-and-subscribe
isOwner is never defined as a helper, so the logic on the Public/Private button text toggle never happens (always says public). Recommend adding:

    isPrivate:function(){
      return this.private
    }

to Template.task.helpers in the example under "We need to modify our JavaScript code in three places:"

**Comment by stubailo** [comment]
Great catch - I'm actually working on a way to make it easier to maintain the tutorial(s) so I will go through and fix all of these hopefully. For now, will tag it.

**Comment by sgates** [comment]
Thanks, I would have submitted a pulled request, but I didn't see those docs in the main repo - maybe I was looking in the wrong place? Thanks!

**Comment by laosb** [comment]
Tutorial is in the Meteor website repo which `isPrivate` :)

**Comment by stubailo** [comment]
Yep, working on changing that too!

**Comment by malcolmhall** [comment]
I found another bug in the tutorial. Step 5 must have a mistake in the template because running this in the console does not uncheck the checkbox, however the strikeout does clear:

    Tasks.update('CJB3bEBhk2MDnBdFK',{$set : {checked:0}});

**Comment by abernix** [comment]
To me, this appears to be fixed so I'm going to close this.  If I'm incorrect, please let me know and I will reopen!  Also, there's a new repo for the tutorial at https://github.com/meteor/tutorial/ where you *can* actually report issues and open PRs! :)

<img width="396" alt="screen shot 2016-05-30 at 5 42 12 pm" src="https://cloud.githubusercontent.com/assets/841294/15652287/dc256afc-268d-11e6-91cd-6f82240dc507.png">
