### ISSUE TITLE
"meteor add-platform ios" always in a state of being installed

### ISSUE THREAD

**Issue by zfq** [meteor/meteor#4693]
I 've installed meteor according to  official tutorial，front steps were no problem, but after I typed "meteor add-platform ios",it's always in a state of " Adding platforms ", it take a long time and no any result. I have tried many times.

<img width="371" alt="2015-07-07 8 24 05" src="https://cloud.githubusercontent.com/assets/5937128/8546060/0475b34e-24e7-11e5-9114-455acb230e87.png">

**Comment by martijnwalraven** [comment]
Without more details about your situation, it is hard to know what could be going on. I'm currently working on improvements to the Cordova integration that I hope to get into the Meteor 1.2 release. Among other things, it will change the way Meteor interacts with the Cordova toolchain, and that could conceivably fix your problem.

**Comment by StephenWilson** [comment]
I have just started on the tutorials for my first time with meteor and experienced something very similar. It got stuck at adding platforms but after 15 minutes I canceled it and tried again, it said it's already added.

**Comment by zfq** [comment]
After I typed "meteor add-platform ios",it's took long time and has no response,so far I haven't found a solution，you can find some meteor demos which are based on Cordova,just search them on github
