### ISSUE TITLE
Meteor.absoluteUrl() always returns localhost in development mode, even when accessed at a different IP

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#4696]
When I'm developing, I usually have the Meteor server in a VM and test from other machines and/or operating systems. However, in development mode `Meteor.absoluteUrl("url")` always returns `http://localhost/url` even when I access the app from e.g. `http://192.168.56.101:3000/` (VirtualBox).

Would it be possible for `Meteor.absoluteUrl` to use `window.host` or something like that on the client, or would that cause other issues?

**Comment by mizzao** [comment]
Normally, in development we could just access URLs with `/url`. But for Cordova apps, `/url` does not translate to `http://meteor.local/url`, so it would be nice if `Meteor.absoluteUrl()` would take care of both that and the actual address that `/url` would automatically point to.

**Comment by glasser** [comment]
`Meteor.absoluteUrl` is always defined by the server, not by the client accessing it. Set `ROOT_URL` if you want to override it.  Is this a Cordova-specific issue maybe?

**Comment by mizzao** [comment]
I believe the Cordova part works fine.

I'm talking about using `Meteor.absoluteUrl` on the client in development mode, which is not very useful as it always gives `http://localhost` even if the app is being accessed at a different IP. This works as intended in Cordova, because the server is accessed at `http://meteor.local`.

**Comment by mizzao** [comment]
In the following file, `Meteor.absoluteUrl` would definitely not be working properly in the scenario I just described:

> https://github.com/meteor/meteor/blob/devel/docs/client/lib/navigate.js

This line defines the undocumented `Meteor._relativeToSiteRootUrl` function, which is what I seem to be asking for on the client. I guess I'm just wondering why that isn't used already.

> https://github.com/meteor/meteor/blob/devel/packages/ddp-client/livedata_tests.js#L742

**Comment by Taakn** [comment]
I am having the same problem, Meteor.absoluteUrl() always returns localhost in development mode even with 1.3

**Comment by samakar** [comment]
I have the same issue with 1.3 too

**Comment by vhmh2005** [comment]
Still relevant
