### ISSUE TITLE
Meteor.autosubscribe undocumented

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4697]
I just realized this exists. I'd do a PR and add it myself, but I have absolutely no idea what `Meteor.autosubscribe` does. :)

**Comment by stubailo** [comment]
@ffxsam some methods are intentionally not documented. If something is not in the docs, it's not part of the Meteor supported API and we reserve the right to change it in future versions of Meteor.

**Comment by glasser** [comment]
It's a deprecated old version of `Deps.autorun`, kept around only for backwards compatibility. We don't document deprecated APIs, but generally you can learn about deprecations from History.md:

```
## v0.5.5, 2013-Feb-13

* Deprecate `Meteor.autosubscribe`. `Meteor.subscribe` now works within
  `Meteor.autorun`.
```

(Then `Meteor.autorun` became `Deps.autorun` in v0.5.8, 2013-Mar-13.)
