### ISSUE TITLE
Packages in Full API don't contain packages available in Basic for Docs

### ISSUE THREAD

**Issue by anubhav94** [meteor/meteor#4698]
In Basic API, we see a package listed as mquandalle:jade but not in full

**Comment by stubailo** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by laosb** [comment]
Should a third-party package be introduced in official docs?

**Comment by laosb** [comment]
If true, should we add more popular third-party packages into the docs, like `meteorhacks:flow-router`?

**Comment by stubailo** [comment]
@laosb I think the `jade` package was in there for historical reasons (to demonstrate that you can use different templating languages)

However, I also totally agree with you that we should add popular community packages eventually. There is a project in progress to do major improvements to the docs, so hopefully we can do some of that.

**Comment by laosb** [comment]
@stubailo Can I join the project? And I may come up with a PR including a quick intro to some popular 3rd-party packages in docs.

**Comment by abernix** [comment]
Closing this as it's no longer relevant.  Popular community packages are documented in [the very helpful Meteor Guide](http://guide.meteor.com/) (including `mquandalle:jade`) and [the newly revamped Meteor Docs](http://docs.meteor.com) no longer have separate Basic/Full API sections.
