### ISSUE TITLE
please delete the MRT Meteor developer organization account

### ISSUE THREAD

**Issue by bevanhunt** [meteor/meteor#4700]
Two major problems:
  1. unmigrated packages from mrt show up in google (unmigrated Nov 10, 2014 and again a few days ago to try again). Search 'meteor leaflet' you get the picture.
  2. most if not all mrt packages are broken and have no maintainers - all my packages were broken on the 'upgrade' and I had about 10 - I got them back and unmigrated them all (BTW I had 10 packages when Atmosphere had about 40)

The MRT organization was only a temporary measure. It is time to delete it. Thanks.

**Comment by awatson1978** [comment]
No.  It's still in use.  Don't delete it.  Thanks.

**Comment by laosb** [comment]
Some packages, for example, `mrt:moment`, still has many users. In my opinion, we should set up a deadline for `mrt` packages.

**Comment by anubhav94** [comment]
Thanks for the issue @bevanhunt. As @awatson1978 and @laosb pointed out, there are packages that are still being used and thus we're not going to shut down the organization at the moment. We're definitely aware that the packages aren't being actively maintained.

**Comment by bevanhunt** [comment]
@anubhav94 - enjoy commercializing your ghost eco-system - best of luck.
