### ISSUE TITLE
Feature: save more states during boot.js procedure

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4701]
1) fileInfo

During boot.js the server codes are looped and loaded

https://github.com/meteor/meteor/blob/devel/tools/server/boot.js#L116-L117

While this, each code file is loaded and gets started with the addtional objects of Npm and Assets which where created during the loop

https://github.com/meteor/meteor/blob/devel/tools/server/boot.js#L205

https://github.com/meteor/meteor/blob/devel/tools/server/boot.js#L221-L222

I would suggest to also "enable" the associated `fileInfo` object to each process. With that it is much easier for some retrospactive debuggings than without.

2) __meteor_bootstrap__ object

https://github.com/meteor/meteor/blob/devel/tools/server/boot.js#L27-L32

Instead just accessing this not "api stable" object, I would suggest to append the properties `serverDir` and `configJson` to the global `Meteor` object when `isServer` is true.

This could be done at 

https://github.com/meteor/meteor/blob/devel/packages/meteor/server_environment.js

---

If you like one or both features, I could create a PR for you.

Thanks for feedback
Tom

**Comment by glasser** [comment]
I don't know what problem you're trying to solve with these suggestions. That said, the platform is more likely to move in the direction of ES2015-style modules and less in the current "eval a bunch of stuff" direction.

Adding fields to `Meteor` in boot.js is tricky because `Meteor` is defined in a package.

**Comment by TomFreudenberg** [comment]
Hi David ( @glasser )

thanks for Feedback.

At Point 1.) I do not wand to extend `Meteor` - I just want to append the `fileInfo` object to the Fiber process as you already do with the `Npm` and `Assets` var. So my suggestion is to provide a var `fileInfo` to each script runner.

The usecase for that is retrospective and debugging info for the running scripts and infos from built process.

At Point 2.) I want to extend `Meteor` only at the package site but with infos which were stored during boot.js inside `__meteor_bootstrap__`

The usecase is to prevent that annoying hopping until you reach the serverDir and get the absolute path directly from `Meteor`. A lot of stackoverflow questions are looking for the info to get the serverDir.
