### ISSUE TITLE
Error: Can't get default release version for track undefined (Windows)

### ISSUE THREAD

**Issue by batjko** [meteor/meteor#4702]
Hi,

I have installed Meteor on a Windows 2008R2 machine, and followed @Slava's [advice](https://github.com/meteor/windows-preview/issues/89#issuecomment-77947556) to move the `.meteor` folder to a new location, in order to make it user-independent.

Then I changed my PATH variable to point to the new location (`C:\Meteor`).

When I now run `meteor`, I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/7287076/8568173/5410e942-2563-11e5-98dd-9a7648230c31.png)

What shall I do? Is there anything inside Meteor that still points at the default location maybe?

**Comment by glasser** [comment]
I'm guessing this means it's failing to find the initial copy of the packages database that is distributed with a Meteor distribution inside `~/.meteor/package-metadata`.  It looks like if you set the `METEOR_WAREHOUSE_DIR` environment variable to the path to your `.meteor` folder, it should work.

That said, you're running in an unsupported configuration. Best of luck!

**Comment by batjko** [comment]
I'll try the env variable, thanks.
