### ISSUE TITLE
Unordered skip/limit queries not supported?

### ISSUE THREAD

**Issue by ryan-williams** [meteor/meteor#4703]
I don't see this documented explicitly anywhere, though it is alluded to in https://github.com/meteor/meteor/issues/1643 and [this years-old SO](http://stackoverflow.com/questions/10157454/meteor-cannot-observe-queries-with-skip-or-limit).

It seems that observing changes on queries that have a `skip` or `limit`, but not a `sort`, is not reactive? It takes several seconds for updates to propagate in [my test app](https://github.com/ryan-williams/meteor-test/tree/limit)

![](https://s3.amazonaws.com/f.cl.ly/items/0817183G1M0I4117193S/Screen%20Recording%202015-07-08%20at%2012.48%20PM.gif)
.

**Comment by glasser** [comment]
Yes, this is documented at https://github.com/meteor/meteor/wiki/Oplog-Observe-Driver, which says that the following types of queries don't use the optimized `OplogObserveDriver`:

 * Queries specifying the `skip` option
 * Queries specifying the `limit` option without a `sort` specifier or with a sort based on `$natural` order

They still should properly see changes, but when the changes occur from outside the current Meteor process it may take up to 10 seconds.

**Comment by ryan-williams** [comment]
Thanks @glasser, I googled around a fair amount without finding that info, which is somewhat buried even there; hopefully this issue can help people debugging similar behavior.

One question: that wiki page says "queries specifying the skip option" use polling observer, but isn't it only *unordered* queries specifying the skip option?

**Comment by glasser** [comment]
I think you're using the term "unordered" in a slightly different way than we do; we have unordered vs ordered observeChanges API, and there's also the concept of sorted vs unsorted.  All "ordered" observeChanges calls use the polling observer, but they aren't commonly used on the Meteor server to drive DDP subscriptions because DDP is an unordered protocol.

**Comment by ryan-williams** [comment]
Fair enough. Is it the case that unsorted skip queries use the polling observer, but sorted skip queries do not?

**Comment by glasser** [comment]
Please read the link I quoted above.  As I quoted:

> Queries specifying the skip option

That's all queries using the skip option.
