### ISSUE TITLE
Publish is out of control when logging in

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#4705]
**_1 Upvote**_ When you subscribe to a large data set, you usually want:
- to display a spinner,
- to turn off any Blaze reactive rendering on the data being loaded, as Blaze cannot handle large amount of progressive updates (see https://github.com/meteor/meteor/issues/3978).

Both requirements are achieved through the use of the subscription "ready" state:
1. Before subscribing, you turn off reactive display and show your spinner,
2. then you subscribe and wait for the "ready" signal,
3. then you display everything again (let alone issue https://github.com/meteor/meteor/issues/3194).

But there is a case where this scheme cannot be used: **when, instead of manually calling "subscribe", a user logs in**. When logging a user in, Meteor automatically reruns all `publish` functions. However, in that case, the client doesn't know:
- when they are triggered (because, even though it knows when users _tries_ to log in, it doesn't know if login will be _successful_),
- when they are ready (because it doesn't have access to the "ready" state).

Consequently, **when user logs-in, if Blaze is currently displaying a large reactive data set, your browser is frozen to death**. All you can do is to circumvent the problem with painful hacks (see below).

The repo is here: https://github.com/steph643/meteor-issue-4705/

When pressing the "Log-in As John" button, there is no way you can display a spinner correctly. Indeed:
- You don't know if login will be successful,
-  You don't know when subscription is ready

**Comment by steph643** [comment]
Now for the workaround:

 - Before calling `Meteor.loginWithPassword`, you have to consider that login might succeed, erase your page and display a spinner. This is painful: my repo shows a simple case where there is no data before login, and plenty of data after login. But suppose there is plenty of data before login, and plenty of *different* data after login. If login doesn't succeed, you have refreshed everything in vain (because nothing has changed on the page).

 - In order to get a useful "ready" state, you need to have an `autorun` that watches `Meteor.userId` and calls `subscribe` when user has successfully logged-in. It means your `publish` function will be called twice: the first time through the automatic Meteor behavior, the second time because of the explicit call to `subscribe`. I expect Meteor merge box to limit the incurred overhead, but this is not so cute.

**Comment by glasser** [comment]
Is `Meteor.loggingIn()`/`{{loggingIn}}` helpful at all here?

**Comment by steph643** [comment]
`Meteor.loggingIn()` doesn't help because it provides no way to know:
 - when publish functions have been called (publish functions are called only if login is successful, whereas `Meteor.loggingIn()` is called when a login *attempt* is made),
 - when they publish are ready.

**Comment by steph643** [comment]
I think what is required here is a way to disable the "auto publish" feature, which is based on the false assumption that publish functions can be called without the client to be aware of it.

If the above is not possible, a workaround would be to provide a `this.loggingIn()` function within publish, so that we can use the following code:
```javascript
  Meteor.publish('myCollection', function () {
    if (this.loggingIn())
      return;                   // I guess it is ok to never call this.ready()?
    return this.userId ? MyCollection.find() : this.ready();
  });
```

**Comment by serkandurusoy** [comment]
I use this pattern:

if (Meteor.Server) {
  Meteor.publish('pub',function(userId){
    check(userId, String);
    var cursor=[];
    if (!!userId && this.userId && this.userId === userId) {
      cursor = MyColl.find();
    }
    return cursor;
  })
}
if (Meteor.isClient) {
  Tracker.autorun(function(){
    Meteor.subscribe('pub', Meteor.userId() || '');
  })
}

**Comment by steph643** [comment]
@serkandurusoy, this is what I suggested in my post beginning with "Now for the workaround" (second bullet). But the real issue, explained in my first bullet, remains.

**Comment by serkandurusoy** [comment]
Yes that's correct. perhaps I've read your second post too quickly.

**Comment by mitar** [comment]
Is there a way to disable this behavior that publish functions are rerun again when user logs in? So in a way, to remove/disable `this.userId` property? The reason why I am asking that [we have implemented reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish) and maybe it would be easier to use it functionality to update published documents once user logged in instead of rerunning the publication.

**Comment by steph643** [comment]
Here are the two ways I have experimented to fix this issue:
 1. I have developed [steph643:ready2](https://github.com/steph643/ready2), an experimental package that changes the behavior of the ready() method so that it reactively fires when subscriptions are rerun.
 2. I have created a modified version of core package **ddp-server**, where subscription rerun has been disabled (still under test).

**Comment by mitar** [comment]
This is especially interesting now with the [subscription data](https://github.com/peerlibrary/meteor-subscription-data) package. `userId` could be just something inside the subscription's reactive data context. So if one wants to depend on `userId`, it registers reactivity, otherwise not.

**Comment by rhyslbw** [comment]
+1
It would be great to see if @mitar 's enhancements to pub/sub would be considered for rolling into core @glasser, as there's some solid APIs and improved the developer experience greatly.

**Comment by mitar** [comment]
I opened: https://github.com/meteor/meteor/issues/6441

**Comment by mitar** [comment]
@steph643: If you know how to disable subscriptions rerun, can you please create a pull request? (You are mentioning it above.) See #6441. @stubailo is [open towards the pull request](https://github.com/meteor/meteor/issues/6441#issuecomment-196454762) if it is simple.

**Comment by steph643** [comment]
@mitar:
I am not into Meteor these days, but here is what I have done, from initial work to final solution:

1.  I developed a package that changed the behavior of the `ready()` method so that it reactively fires when subscriptions were rerun.
 
2. I created a modified version of core package `ddp-server`, where subscription rerun was disabled. I lost the code, but it was about commenting part of the code in `livedata_server.js`, function `_setUserId`. 

3. I implemented a client-side hook that was called after login was detected but *before* subscriptions were rerun. This was achieved by monkey-patching function `AccountsClient.prototype.callLoginMethod`.

**Comment by hwillson** [comment]
Now that we have a [`DDP.onReconnect`](https://docs.meteor.com/api/connections.html#DDP-onReconnect) hook point, I think we can add "clear pending methods on reconnect" functionality to core fairly easily:

1) Add a new `clearOutstandingMethodsOnReconnect` property to [`Connection`](https://github.com/meteor/meteor/blob/4bbe849b35400f9e6d495b3e9f7105f6c09b50a2/packages/ddp-client/livedata_connection.js).

2) Adjust the [`Connection._callOnReconnectAndSendAppropriateOutstandingMethods`](https://github.com/meteor/meteor/blob/4bbe849b35400f9e6d495b3e9f7105f6c09b50a2/packages/ddp-client/livedata_connection.js#L1682) function to see if this property has been set after the `onReconnect` callbacks have been triggered; if so clear out the pending methods.

```js
_callOnReconnectAndSendAppropriateOutstandingMethods: function() {
  ...
  DDP._reconnectHook.each(function (callback) {
    callback(self);
    return true;
  });

  // If requested, clear all pending methods before reconnecting.
  if (self.clearOutstandingMethodsOnReconnect) {
    self._outstandingMethodBlocks = [];
    return;
  }
  ...
},
```

3) Then from our application, request that pending methods get cleared via a `DDP.onReconnect` callback:

```js
DDP.onReconnect(connection => {
  connection.clearOutstandingMethodsOnReconnect = true;
});
```

We could then also consider allowing `clearOutstandingMethodsOnReconnect` to be set via [`DDP.connect`](https://github.com/meteor/meteor/blob/4bbe849b35400f9e6d495b3e9f7105f6c09b50a2/packages/ddp-client/livedata_connection.js#L1758)'s undocumented `options` param and [`Connection`'s constructor](https://github.com/meteor/meteor/blob/4bbe849b35400f9e6d495b3e9f7105f6c09b50a2/packages/ddp-client/livedata_connection.js#L29) (to add even more flexibility).

Thoughts?

**Comment by mitar** [comment]
I think a slightly better API would be an explicit cal to "clear outstanding methods", and you can call it at any time, and calling it during reconnect just happens to do the right thing.

BTW, clearing should definitely throw an error to all callbacks waiting for methods to come back, but we should allow somehow those exceptions to be inspected and detected to know that maybe caller can just retry or handle it in some other way.

**Comment by hwillson** [comment]
This is an old issue that hasn't had very much traction, and is actually working as designed. Having a way to clear pending methods on reconnect would be a useful addition however.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Publish%20is%20out%20of%20control%20when%20logging%20in&body=Migrated%20from:%20meteor/meteor%234705) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
