### ISSUE TITLE
Sanitize input and remove <script> tags by default

### ISSUE THREAD

**Issue by petermikitsh** [meteor/meteor#4706]
For whatever reason, perhaps it wasn't clear in the documentation, but I missed the message on triple curly brackets for rendering HTML strings as actual HTML. I went on to write a lovely (and dangerous!) handlebars helper like this:

```
Handlebars.registerHelper('toHTML', function (text) {
    return new Handlebars.SafeString(text);
});
```

And used it in my templates.

Supposing my `text` value is ```<script>alert("bar")</script>```, which is totally valid user input on meteor insert's, etc., my app is now subject to possible XSS attacks. However, had we just sanitized input from the start and removed the `script` tags before I inserted my document, we'd be a little bit safer off.

Now it's likely the case I'm in the minority neglecting use of triple curly brackets. However, I am suggesting that Meteor be secure by default and remove script tags before they even make it to the database. Think of other use cases where perhaps my Meteor app is serving as an API to other applications on the internet. If they take my documents and insert them directly into the DOM, then their site too would have XSS attacks. Iffy corner cases such as this, that make me feel uncomfortable (from a security perspective) could all be mitigated by simply filtering data prior to insertion.

**Comment by glasser** [comment]
The [documentation for `Spacebars.SafeString`](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#safestring) says:

> If a double-braced tag at element level evalutes to an object created with
`Spacebars.SafeString("<span>Some HTML</span>")`, the HTML is inserted at the
current location.  The code that calls `SafeString` is asserting that this HTML
is safe to insert.

(`Handlebars.SafeString` is an old name for this.)  Ie, the word "safe" in this advanced feature means "I promise I have made sure that this is safe to insert".

The normal double-braces syntax is the easiest to use and is thus the most protective one.

I don't think that Meteor should assume that every string ever stored in any database can be arbitrarily munged by the framework.
