### ISSUE TITLE
Meteor.http.call - PATCH - data wrapped in quotes

### ISSUE THREAD

**Issue by romant** [meteor/meteor#4707]
Taking into account a definition

```
options = {
      headers:
      {
        'Content-Type': 'text/html'
      },
      data: foo
    };
```

A call to:

`Meteor.http.call('PATCH', 'http://localhost:8080/api/', options)`

Results in the data being received by the API endpoint as:

`"foo"`

instead of

`foo`

If `foo` is a variable, the entire string will still be sent across in quotes as well, as seen in the below Wireshark extract:

```

Hypertext Transfer Protocol
    PATCH /api/node HTTP/1.1
        [Expert Info (Chat/Sequence): PATCH /api/node HTTP/1.1]
            [PATCH /api/node HTTP/1.1]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: PATCH
        Request URI: /api/node
        Request Version: HTTP/1.1
    Content-Type: text/html
    host: localhost:8080
    content-length: 4
        [Content length: 4]
    Connection: keep-alive
    
    [Full request URI: http://localhost:8080/api/node]
    [HTTP request 1/1]
    [Response in frame: 2736]

Line-based text data: text/html
    "on"
```

**Comment by Tarang** [comment]
Consider using `content` instead of `data`:

```
options = {
      headers:
      {
        'Content-Type': 'text/html'
      },
      content: foo
    };
```

I suspect the quotes are an artefact of converting the variable's value to JSON.
More details here: http://docs.meteor.com/#/full/http_call

**Comment by romant** [comment]
Hi @Tarang,

You're correct. Was a late night :smile: - thank you very much!

**Comment by glasser** [comment]
Thanks @Tarang !
