### ISSUE TITLE
Console is not defined. 

### ISSUE THREAD

**Issue by Narven** [meteor/meteor#4709]
I'm getting this error on windows 7 with meteor 1.1.0.2, everytime I run meteor update or meteor list.

´´´
C:\Users\narven\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x
86_32\tools\files.js:643
      Console.debug(err);
      ^
ReferenceError: Console is not defined
´´´

I think it should be 'console.debug(err);' and not 'Console.debug(err);'

I changed manually on the files.js and it works now.

**Comment by robertpitt** [comment]
@Narven, I think the `Console` os defined in `tools/console.js`, just need's to be required in the head of `files.js`

@glasser, do you require a PR?

**Comment by Narven** [comment]
That's correct. I added the require at the top and it works

**Comment by stubailo** [comment]
Fixed, thanks for reporting! 6932f66140c6d65e374bca3b3e80717ef447de59

**Comment by brylie** [comment]
We are having this error with 1.1.0.2 as well. When will this fix be released?

**Comment by bajiat** [comment]
We applied the previous fix, and got the following error:
```
C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x8
6_32\tools\files.js:643
Console.debug(err);
^
TypeError: Object #<Object> has no method 'debug'
at Object._onImmediate (C:\Users\username\AppData\Local\.meteor\packages\meteor
-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643:15)
at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by Narven** [comment]
@bajiat i think you need to put this `var Console = require('./console.js');` on top of that `file.js`

At least for now.

**Comment by bajiat** [comment]
Do you mean files.js? If so, that's where we placed the following code:

´´´
var Console = require('./console.js');
´´´

**Comment by Narven** [comment]
Yes,

that file that is giving the error: `C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js`

Open it and on top there;s a bunch of require.. add:

`var Console = require('./console.js');`

**Comment by brylie** [comment]
We added the code to the top of the file, before any other of the require statements. The second error we got is regarding a missing method, indicating that the file inclusion was probably successful.

**Comment by Narven** [comment]
What is the second error that ur getting?

**Comment by brylie** [comment]
```
TypeError: Object #<Object> has no method 'debug'
at Object._onImmediate (C:\Users\username\AppData\Local\.meteor\packages\meteor
-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643:15)
at processImmediate [as _immediateCallback] (timers.js:354:15)
```
