### ISSUE TITLE
FR: Rate limit across servers

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4714]
Eg my website has a cluster of application servers, and IP X has many connections open, split among my servers. I'd like all of X's activity to count toward a single limit. This type of rate limiting is done by https://github.com/zeroasterisk/Meteor-Throttle with a Mongo collection. While that would be a good default, since it doesn't require any additional setup, it would be great to have an option to configure it to use Redis, which IMO is better suited to this type of task.

cc @anubhav94

**Comment by anubhav94** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests). I'll leave this open for more discussion and know it's on our radar about new features to add to the rate limiter!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=FR%3A%20Rate%20limit%20across%20servers&body=Migrated%20from:%20meteor/meteor%234714) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
