### ISSUE TITLE
Outdated filename in Meteor Wiki for Android on Mac

### ISSUE THREAD

**Issue by Aweary** [meteor/meteor#4717]
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Mac#installing-the-jdk

>  Agree to the license terms and select the Mac OS X image file (jdk-8u40-macos-x64.dmg)

That should say jdk-8u45-macosx-x64.dmg, as thats the latest version (and the version on the page it links to). It's such a minor thing, but hey, better to fix it than not I suppose.

The image is also out of date.

**Comment by martijnwalraven** [comment]
Thanks for the report, fixed the filename. Updating these instructions and taking recent screenshots is on my to do list.
