### ISSUE TITLE
Switch to having developers install the Android SDK separate from Meteor

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#4721]
Switch to having developers install the Android SDK separate from Meteor. Tying the two together has made it hard to keep the development toolchain up to date and has led to some difficult to diagnose failures. This would likely mean pointing users to instructions for installing an Android SDK if they haven't already done so. The most straightforward way is probably to install Android Studio, which offers a convenient configuration wizard on first launch.

**Comment by edwardvalentini** [comment]
further to this issue - is there a reason to force the use of HAXM?   Some people may prefer to use Genymotion or some other accelerator

**Comment by martijnwalraven** [comment]
With the changes mentioned in this issue, we won't require the use of HAXM anymore. By getting rid of the bundled Android SDK and tools, we're leaving it up to developers to set up their own environment. Although I haven't tested this, I believe that means you should also be able to use Genymotion or other accelerators.

**Comment by martijnwalraven** [comment]
We released the first Meteor 1.2 RC yesterday (`--release METEOR@1.2-rc.7`), which includes the changes described in this issue.
