### ISSUE TITLE
Update Cordova to 5.1.1 and update plugin dependencies

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#4723]
Update Cordova to the most recent version ([5.1.1](https://cordova.apache.org/news/2015/06/10/tools-release.html)) and update plugin dependencies to the [latest release] (https://cordova.apache.org/news/2015/06/22/plugins-release.html).

This should also make it easier for people to install the [Crosswalk plugin] (https://crosswalk-project.org/documentation/cordova/cordova_4.html), which offers a much improved web view, especially on older Android versions https://github.com/meteor/meteor/issues/3076.

**Comment by bgrayburn** [comment]
+1, trying to add a cordova plugin that uses a gradle hook so greatly looking forward to this update, think it'll be in 1.2?

**Comment by shishircc** [comment]
Great. This is one of the pain points we face at our startup.

**Comment by Wenape** [comment]
+1

**Comment by woniesong92** [comment]
+100! :sweat_smile:

**Comment by miri-am** [comment]
+1

**Comment by chriswessels** [comment]
+1

**Comment by martijnwalraven** [comment]
We released the first Meteor 1.2 RC yesterday (`--release METEOR@1.2-rc.7`), which includes a Cordova update to the latest version.

**Comment by DavideCan** [comment]
+1
