### ISSUE TITLE
Meteor app is not building in Samsung Galaxy S5

### ISSUE THREAD

**Issue by ksharifbd** [meteor/meteor#4727]
I am running  'meteor run android-device' but the app is not building in Samsung Galaxy S5. It builds and runs in my Samsung Galaxy Trend Sduos 2

**Comment by rclai** [comment]
You might need to change your USB mode and of course turn on debug mode.

**Comment by pmwisdom** [comment]
Try running 'adb devices' at the command line to make sure your phone is being recognized.

**Comment by anubhav94** [comment]
Hi @ksharifbd. Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it. I'm going to close this for now, however you might want to try the other suggestions and see if that fixes your problem.
