### ISSUE TITLE
curl https://install.meteor.com | /bin/sh failing

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4730]
Our tests are failing with:

```
curl https://install.meteor.com | /bin/sh returned exit code 2

/bin/sh: 2: Syntax error: newline unexpected Action failed: curl https://install.meteor.com | /bin/sh
```

**Comment by mitar** [comment]
Not anymore.

**Comment by anil-kumar-ma** [comment]
![screenshot from 2016-01-13 14 21 51](https://cloud.githubusercontent.com/assets/15100205/12305228/9e0868f8-ba01-11e5-94ca-f77d2893be83.png)
It's still the problem. I am using ubuntu 14.04 LTS/
