### ISSUE TITLE
Call tpl helpers from other helpers, events and onRendered

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4732]
It would be nice to be able to access tpl helpers from other helpers, events and tpl callbacks.
Now I have to hack it like this:
`Template.tplName.__helpers.get('helper').call()`
and
`Blaze._globalHelpers['helper']()`
not *too* shabby...

**Comment by rfox90** [comment]
This kind of breaks the abstraction/encapsulation that templates provide.

If its a common helper could it be a [collection based helper](https://github.com/dburles/meteor-collection-helpers/)?

**Comment by rclai** [comment]
If the state depends on a collection's data, it should be a collection helper, otherwise, you could use [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) to help with calling other "helpers".

**Comment by avalanche1** [comment]
@rfox90 , 1st off, if I want to access same tpl helpers from events or callbacks - this breaks nothing and feels quite natural, actually.
2ndly, I should be able to override abstraction layer, if I need to! this should be standard API procedure.

**Comment by Slava** [comment]
All template helpers are regular functions. You can declare a function in the shared closure, and then pass it to the `helpers` call. And use it later in your code as well. Example:

```javascript
var myFunction = function () {...};
Template.myTemplate.helpers({
     helper: myFunction
});

Template.myTemplate.events({
    'click .button': function (event) {
       ... myFunction(); ...
    }
});
```

I don't think there should be a way to call a helper of a template directly. For the most cases, just sharing a js variable works well.

**Comment by jonlachlan** [comment]
Meteor is great for code reuse, however this barrier to calling helpers goes against that patter. It would make more sense to make it convenient to call a template helper.

Experts may know how to get around this, but relative novices are going to be expecting this as an option.

**Comment by avalanche1** [comment]
At least @Slava 's recommendation should be mentioned in the docs.

**Comment by Slava** [comment]
@avalanche1 I disagree, my example above is just a regular JavaScript. There is nothing special about it. I don't think it should be in the docs.

**Comment by avalanche1** [comment]
Well, if you're ok with less experienced javascript devs bumping their heads with this issue like blind kittens - so be it.

**Comment by Ragsboss** [comment]
> 1st off, if I want to access same tpl helpers from events or callbacks - this breaks nothing and feels quite natural, actually.

I fully agree with this. Template - along with its helpers, events and html content - is one cohesive reusable unit of code. It does feel natural to be able to call my own template methods from that template's event handlers... 
Declaring a global function or a helper object with functions is odd because most of the time, the helper method is very specific to this template, which is why, it is in the template helper method, to begin with..

**Comment by avalanche1** [comment]
I've switched to using [viewmodel](https://forums.meteor.com/t/viewmodel-2-a-new-level-of-simplicity/), which solves all those problems (and much more!) and am  VERY happy about it!
btw, it allows to drop standard meteor helpers, events and callbacks completely (it still uses them, but in a much friendlier fashion)
