### ISSUE TITLE
Use immutable.js to implement Minimongo

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4733]
Instead of cloning all documents all the time inside Minimongo, maybe Minimongo should use [immutable objects](https://facebook.github.io/immutable-js/) to store data in it?

**Comment by stubailo** [comment]
Hi, I don't think we will accept pull requests of the form "X should be implemented in Y way" - the internal details of packages might change at any time, so we don't really consider that as part of Meteor's feature set. However, this is potentially a good idea and might be a good thing to investigate in the form of a forum discussion or experimental branch/PR.
