### ISSUE TITLE
Make external database a reactive source

### ISSUE THREAD

**Issue by weijian19391** [meteor/meteor#4737]
Hi 

Here's my use case:
I have an app that depends on an external database for information to be displayed on the app, the information is mainly sensor data collected by my BeagleBone Black, and is being uploaded to IBM Bluemix cloud services. I would like to display those data in the form of a chart inside my app, but the problem i'm facing is that when i use the following lines to connect to the external database: 
````
var database = new MongoInternals.RemoteCollectionDriver('mongodb://<user>:<pwd>@ds037812.mongolab.com:37812/IbmCloud_37tlksh0_9tum7eic');
console.log("number of things in temp collection is " + database.open('Battery_Temp').find().count());
````
when the database is updated, the log line is not being ran again, suggesting that the find() function is not detecting a change in database. 

Is there anyway to make an external database a reactive source in meteor? or is there a better workaround for my use case? 

Thank you.

**Comment by zimme** [comment]
How about using the `connection` option for the `new Mongo.Collection` constructor?

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

Tracker-style reactivity only exists on the client, not on the server.  I don't really understand what you're trying to do; is there a single database that sometimes changes, or one per user? Maybe you should be making this connection inside a publish function?
