### ISSUE TITLE
.meteor/release file that is empty; no action can be taken

### ISSUE THREAD

**Issue by jjadisch** [meteor/meteor#4738]
Hey!

I just installed Meteor and it wont allow me to take any action due to this error:

"Problem! This project has a .meteor/release file which is empty. The file
should either contain the release of Meteor that you want to use, or the word
'none' if you will only use the project with unreleased checkouts of Meteor.
Please edit the .meteor/release file in the project and change it to a valid
Meteor release or 'none'."

I have tried removing and reinstalling meteor and it didn't solve the issue. 

Any help is greatly appreciated, Sincerely,
jjadisch

**Comment by stubailo** [comment]
@jjadisch did you try editing that file as mentioned by the directions? What are the contents of the file?

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by NDMTom** [comment]
@stubailo Having the same issue here, no luck finding an answer so far...

How can I edit the contents of .meteor/release 

Just getting into coding the past few months, so I'm probably missing something obvious here

Problem! This project has a .meteor/release file which is empty.

$ cd simple-todos
$ meteor
Problem! This project has a .meteor/release file which is empty. The file
should either contain the release of Meteor that you want to use, or the word
'none' if you will only use the project with unreleased checkouts of Meteor.
Please edit the .meteor/release file in the project and change it to a valid
Meteor release or 'none'.

**Comment by sjmcdowall** [comment]
Interested in how in the world you got an empty .meteor/release project file.  However, if you know what release of Meteor the project was created in (or what release you current run) you can easily "edit" (use your favorite text editor of any sort) this file:
./meteor/release

And add this single line:
METEOR@1.1.0.3

If you have any *nix type shell available -- go to your project area and you can just do
echo "METEOR@1.1.0.3" > .meteor/release 

To also populate the file.  Of course, change 1.1.0.3 to the proper version you are on!

**Comment by NDMTom** [comment]
Same, must have been something I did without noticing.




I ended up deleting the project file and making it again, and it worked.




Thanks for the response

**Comment by tomachinz** [comment]
mine says:

METEOR@1.6.0.1

**Comment by tomachinz** [comment]
me and the OP are looking in the wrong folder. 

it's caused by renaming the project folder while the project is running.

somehow the /app/ folder will come back to live - it gets recreated half way see shot:

![image](https://user-images.githubusercontent.com/1026291/36290464-328cf2f4-132a-11e8-98b4-8eee703e926c.png)
