### ISSUE TITLE
Assets.getText() in packages cannot read server assets.

### ISSUE THREAD

**Issue by patmoore** [meteor/meteor#4739]
I have a package that needs to read configuration information from the private directory.

However, in boot.js ( getAsset function -line 185 - version 1.1.0.2 ), the check fails.
```
      if (!fileInfo.assets || !_.has(fileInfo.assets, assetPath)) { //  <<< Fails
        _callback(new Error("Unknown asset: " + assetPath));
      } else {
        var filePath = path.join(serverDir, fileInfo.assets[assetPath]);
        fs.readFile(files.convertToOSPath(filePath), encoding, _callback);
      }
```

This maybe intentional security. If so what is the suggested way to allow a package to read the application's private directory.

(Side note: this is a meteor core development issue)

**Comment by glasser** [comment]
This is working as intended. The `Assets` API provides access to assets in the current package/app.

With the current APIs, if you want to support this case you can have an API in your package that can be invoked by the app passing in its `Assets` object.

**Comment by patmoore** [comment]
O.k. If I modified the assets docs - would the pull request be accepted. ( not interested in wasting time )

**Comment by glasser** [comment]
Sure, I didn't realize the docs didn't describe how things worked in packages.
