### ISSUE TITLE
Meteor.loginWithFacebook not adding email address to user

### ISSUE THREAD

**Issue by KnutSv** [meteor/meteor#4743]
Code for reproducing the issue:
https://github.com/KnutSv/Meteor-facebook-login-email-bug

When the user registers via Facebook the email from Facebook is not added to the user account.

```javascript
Meteor.loginWithFacebook({requestPermissions: ['email']}, function(error){
  if (error) {
    console.log(error);
  }
});
```

Possible cause is changes to Facebook API v. 2.4 where fewer fields are returned from graph.
I get the email returned if I add `&fields=email` to the graph url:
https://graph.facebook.com/v2.4/{{userID}}?access_token={{accessToken}}&fields=name,email

**Comment by omeid** [comment]
I can confirm the same issue.

Meteor works with an older App that allows v2.0 of graph but for 2.4 it fails.

**Comment by tmeasday** [comment]
Thanks for the report @KnutSv, see also @glasser's comment on the PR.

We're considering whether on not to do a point release to deal with this.

**Comment by xpluscal** [comment]
Any news on a point release yet?

**Comment by dgreensp** [comment]
Working on it; probably Monday.

**Comment by dgreensp** [comment]
It's now out in 1.1.0.3.
