### ISSUE TITLE
Package Manager doesn't always rebuild correctly after a meteor add 

### ISSUE THREAD

**Issue by reduxdj** [meteor/meteor#4745]
Noticed that I had to hand change the package file to get the meteor add to actually add the file.

release/METEOR@1.1.0.2

**Comment by glasser** [comment]
I don't understand what the issue is. Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.

I suspect this is #3582 though.
