### ISSUE TITLE
Package manager doesn't reliably rebuild meteor if dependencies change

### ISSUE THREAD

**Issue by reduxdj** [meteor/meteor#4746]
Meteor admin wouldn't work with image upload and autoForm, I couldn't get the bug resolved until I removed all my packages and then it printed "removed from your project" XX times. After an error of it restarting, I replaced all the packages (ensuring a full build) and low and behold, tried my image upload and it worked! 

This would lead me to believe the point of the ticket.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by trusktr** [comment]
It's within the realm of possibilities. If a package has npm dependencies, then during rebuild `npm outdated` may need to be used to detect dependency changes in npm packages, and if changes are detected `npm update` will do the job that `npm install` won't do.
