### ISSUE TITLE
Meteor.call only executing once

### ISSUE THREAD

**Issue by ssmith15** [meteor/meteor#4748]
Inside of my Template.foo.events I have 

    'click .button' : function(e) {
        Meteor.call('bar', a, b, c)
        console.log("call is happening")

This code is meant to insert a database entry with a,b,c

Then inside of my file where I subscribe to this collection I have in Meteor.methods

    bar: function(A,B,C) {
        var inserted = collection.insert({a,b,c}, function() {
            console.log("insert is working!")
        })

When I go to the browser and click the button, I see a new item rendered and "insert is working". However if I click the button subsequently, nothing happens. If I refresh the page, I can repeat the process (only one db update). I've added the console.log messages to see where this behavior is coming from and it looks like the Meteor.method 'bar' isn't being called at all after the first time, but the .click function call is working fine.

What's going on here?

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
