### ISSUE TITLE
Updating Google Snippets

### ISSUE THREAD

**Issue by sweetticket** [meteor/meteor#4749]
How can I update the snippet that shows in google search results? I tried using the og:description meta tag in layout.html and the manuelschoebel:ms-seo package, but neither of them worked. I also tried "nosnippet" and "noarchive" for the google meta tags (<meta name="robots" content="nosnippet, noarchive" />, <meta name="googlebot" content="nosnippet, noarchive" />) and they failed as well.

Is there another way to do this?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
