### ISSUE TITLE
Accessing settings in mobile-config.js

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4751]
**_6 Upvotes**_ For example, I have a `TRUSTED_URLS` list in `app/server/browser_policy.js` [1] that I would like my `app/mobile-config.js` to be able to access for `App.accessRule` [2]

Related: #2860 

[1] https://atmospherejs.com/meteor/browser-policy
[2] https://docs.meteor.com/#/full/App-accessRule

**Comment by martijnwalraven** [comment]
Thanks for the feature request. I understand the need to share configuration information between mobile-config.js and browser-policy, but I'm not sure if code sharing would be the right approach for this. Rather, this may tie in with a general need for a configuration settings mechanism.

**Comment by max-nova** [comment]
+1 - I'd love to be able to display my version number from mobile-config.js in the UI without having to duplicate code.

**Comment by stubailo** [comment]
It would be cool if you could use stuff from `Meteor.settings` inside `mobile-config.js`!

**Comment by miri-am** [comment]
+1 for using Meteor.settings inside mobile-config.js: would enable settings ids for development versions of app etc.

**Comment by obiwarn** [comment]
+1 same problem as @max-nova

**Comment by msio777** [comment]
+1 to have this feature would be great

**Comment by jamielob** [comment]
Is this on the roadmap for 1.3 or out further?

**Comment by lance-anderson** [comment]
+1

**Comment by Slanman3755** [comment]
+1

**Comment by jackkav** [comment]
+1

**Comment by erikanthonywall** [comment]
I've been using environment variables with my build scripts to do this. Here's an example:

```
if (process.env.BUILD_FOR_PRODUCTION === 'true') {
	App.info({
		id: 'com.myapp.myapp',
		name: 'MyApp',
		version: '1.0.0',
		website: 'http://meteor.com'
	});
} else {
	App.info({
		id: 'com.myapp.myappstaging',
		name: 'MyApp',
		version: '1.0.0',
		website: 'http://meteor.com'
	});
}
```
Then, in my build scripts I set the environment variable according to my needs, using `set BUILD_FOR_PRODUCTION=false`. You can have different icons, splash screens, access rules, or anything else you can set in mobile-config.js.

**Comment by nunovieira** [comment]
+1 this is a must have feature to having a concise `mobile-config.js`.
It would be great to handle a single settings file per environment.

**Comment by anymos** [comment]
Hi guys, any idea if we just could use require or import it would be enought to hack around

**Comment by Testato** [comment]
+1

**Comment by AshHimself** [comment]
+1  Not being able to test both dev and prd on the same device is a little annoying. Currently using @ericterpstra workaround.

**Comment by tafelito** [comment]
I'm also using similar to what @ericterpstra is doing. I'm also trying to execute a process to get the last commit hash so I don't have to manually set the buildNumber every time I do a build. Couldn't figure it out how to do it yet, though

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Accessing%20settings%20in%20mobile-config.js&body=Migrated%20from:%20meteor/meteor%234751) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by nunovieira** [comment]
I don't understand this policy change. IMO, tracking feature requests on a separate repository just adds confusion.

**Comment by hwillson** [comment]
@nunovieira For an explanation of why we're doing this, please read this [forum post](https://forums.meteor.com/t/announcement-better-organization-of-feature-requests-for-meteor/37048). Thanks!
