### ISSUE TITLE
ReactiveDict should hold onto dictName?

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#4755]
https://github.com/meteor/meteor/blob/devel/packages/reactive-dict/reactive-dict.js#L19-L41

This can be closed, but it feels a bit odd that a reference to `dictName` is not kept, even as a private property, say: `_dictName`. 

Consider a case where you would want to reduce an array of dictionaries to find Session (`Session = new ReactiveDict('session')`). Without `dictName` dictionaries are indistinguishable from each other. Was this by design?

**Comment by stubailo** [comment]
I don't think it's by design. I'd probably accept a PR saving this property.
