### ISSUE TITLE
contentBlock inside of Template.dynamic

### ISSUE THREAD

**Issue by maxnowack** [meteor/meteor#4756]
It would be cool if `Template.contentBlock` can be used with `Template.dynamic`
Maybe some code can better explain what I mean:
````
{{#Template.dynamic template="Test"}}
  Dynamic
{{/Template.dynamic}}
````
````
<template name="Test">
  <div>
    Content from:
    {{> Template.contentBlock}}
  </div>
</template>
````

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by zimme** [comment]
Nice, with this iron:router's layout thing can be re-implemented with `Template.dynamic` instead if it's own dynamic template thing =)

**Comment by dotnetwise** [comment]
why not 
```js 
{{#dynamic name=xxx}}
abc
{{/dynamic}}
``` 
as opposite to longer uglier `Template.dynamic`
