### ISSUE TITLE
Can't override root cert list for Node DDP client (eg, package server)

### ISSUE THREAD

**Issue by TechplexEngineer** [meteor/meteor#4757]
At work we are behind an SSL inspection appliance which resigns all traffic with the companies root CA. Is there a way to add this to Meteor. 

When not suing meteor we can tell NPM where our CA cert lives:
`npm config set cafile /path/to/cert.pem`

Is there a way to do this for Meteor?

**Comment by TechplexEngineer** [comment]
Here is the error in full:
```
$ meteor add twbs:bootstrap
Unable to update package catalog (are you offline?)
                                              
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
                                              
 => Errors while adding packages:             
                                              
While downloading twbs:bootstrap@3.3.4...:
error: CERT_UNTRUSTED

Your package catalog may be out of date.      
Please connect to the internet and try again.
```

And just to show that I have the proxy properly configured
```
$ printenv | grep -i proxy
http_proxy=http://gatekeeper-w.<my company>.org:80/
https_proxy=http://gatekeeper-w.<my company>.org:80/
HTTP_PROXY=http://gatekeeper-w.<my company>.org:80/
HTTPS_PROXY=http://gatekeeper-w.<my company>.org:80/
```

**Comment by glasser** [comment]
It looks like we don't provide a way to override the CA used to connect to the package server. The library that we use (FayeWebsocket.Client) allows us to pass in a `ca` option but we don't provide a way for users to configure that, either in the `ddp-client` package or via the command-line tool.

This wouldn't be too hard to fix.  See how there is a `headers` field in `packages/ddp-client/stream_client_nodejs.js` passed to the `new FayeWebSocket.Client`?  It gets threaded through from `tools/auth-client.js` to `tools/service-connection.js` to `packages/ddp-client/livedata_connection.js` to that file.  I think we could add another option like `_fayeClientOptions` which is a hash of options to also send to `new FayeWebSocket.Client`, and then have an environment variable that lets you specifically pass in a ca file that eventually ends up in the `{tls: {ca}}` arg to `FayeWebSocket.Client` (its format is documented at https://nodejs.org/api/tls.html#tls_tls_connect_options_callback).

Pull requests encouraged!  Ideally with a description of how to verify that the PR works.

**Comment by TechplexEngineer** [comment]
Is there a Meteor CLI config file that this CA property could be read from?
