### ISSUE TITLE
Uncaught Error: Not permitted. Untrusted code may only remove documents by ID. [403]

### ISSUE THREAD

**Issue by joel-delong** [meteor/meteor#4758]
I've enabled Facebook and Twitter login through the accounts-ui package after completing the meteor-angular tutorial and this appeared to cause a problem. I'm using [meteor methods](https://www.meteor.com/tutorials/angular/security-with-methods) but am still getting the above error. The only queries that I'm performing on the client side are find operations.

**Comment by anubhav94** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it. I'm going to close this for now, if you provide a reproduction, we can try to debug the problem.
