### ISSUE TITLE
Define concatenated css files with html import?

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#4761]
http://stackoverflow.com/questions/31077273/how-can-an-external-stylesheet-be-used-to-style-polymer-1-0-elements

As asked in this stackoverflow, currently when using polymer you are able to style paper-elements (or custom elements in general cross browser in the future) with custom properties or whatever they're called sorry. However, you need to add is="custom-style" to your style tag.

Meteor takes all the css files and concatenates them automatically and uses the link tag to import them, so you don't even end up with a style tag. A solution for the problem is doing an html import and having the styles included in that file inline. But as mentioned in my comment on stackoverflow this means you need to add at least one additional http request. I know I'm super nitpicky here but developing for the Philippines (slowest internet speed in Asia, 3.6MBPS average) and Asia just means you want to optimize even the slighest detail for speed.

Would it theoretically be possible to concatenate everything into a html import instead of linking to a css file so you don't need to generate two seperate css files?

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think something like this could almost be done with the new user-pluggable minifier support targeted at Meteor 1.2, though it might not have all the hooks necessary to do that.

**Comment by brylie** [comment]
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by aruntk** [comment]
Use polymer as the default view layer using mwc:synthesis package 
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Define%20concatenated%20css%20files%20with%20html%20import%3F&body=Migrated%20from:%20meteor/meteor%234761) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
