### ISSUE TITLE
Ability to not pass `text` in Accounts.emailTemplates.*

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4768]
I'm trying to use Mandrill's feature of [automatically generating plain-text from HTML](https://mandrill.zendesk.com/hc/en-us/articles/205582117-Using-SMTP-Headers-to-customize-your-messages#automatically-generate-plain-text-from-html-content) if a certain SMTP header is specified. This is handy because Marketing wants to edit the email template via Mandrill's UI, and have the text part automatically generated. In my code, I call [Mandrill's template rendering API](https://mandrillapp.com/api/docs/templates.nodejs.html#method=render), then assign the result to `Accounts.emailTemplates.{enrollAccount|resetPassword|verifyEmail}.html`.

The problem is that `Accounts.emailTemplates.{enrollAccount|resetPassword|verifyEmail}.text` expects a function, and if one is missing, it adds a default text part to the email, e.g.

> Hello,

> To start using the service, simply click the link below.

> http://localhost:3000/#/enroll-account/<secret>

> Thanks.

I've tried assigning `null` and `''` but that didn't work. (`TypeError: Property 'text' of object #<Object> is not a function`).

**Comment by anubhav94** [comment]
Hey @dandv! The simple fix could've been to set `Accounts.emailTemplates.{enrollAccount|resetPassword|verifyEmail}.text` to be a function that returns an empty string. However, I just pushed out a fix that allows `text` to not be a function, which you can see in 567db56

**Comment by dandv** [comment]
Hi @anubhav94 ! Thanks for the fix, and welcome to MDG (I haven't followed development very closely lately, so you might have been there for a while :) I wanted to look at your contributions but it looks like your GitHub username isn't set up:

![image](https://cloud.githubusercontent.com/assets/33569/9018315/b968641e-3792-11e5-90b2-9f15029423f8.png)

Here are the settings that work for me:

```
    git config --global user.name "Dan Dascalescu"
    git config --global user.email "ddascalescu+github@gmail.com"
    git config --global github.user dandv
```
