### ISSUE TITLE
Request origin from mobile app

### ISSUE THREAD

**Issue by dhavalrajani92** [meteor/meteor#4770]
Hello,

I am new in meteor i have developed one application which is call third party api and its working fine in my website. i have made application from my OSX machine with live website url with following command 
meteor ~/androidapp build --server=https://mysite.com

and my app started successfully everything works fine except my third party api.

Please note my thrid party api also authenticating request origin. i am not able to figure out that what is the request origin of mobile app with above command i have set ROOT_URL as a env variable in my OSX machine which is same available at my EC2 server

Please try to figure out what is the problem

**Comment by dhavalrajani92** [comment]
any updates?

**Comment by martijnwalraven** [comment]
Have you defined an access rule (`App.accessRule`) for your API server in your [mobile-config.js](http://docs.meteor.com/#/full/mobileconfigjs)?

**Comment by dhavalrajani92** [comment]
Yes i defined access rule (App.accessRule('*');) in my mobile-config.js file.

**Comment by dhavalrajani92** [comment]
More information i am giving for this issue. I am putting third party iframe in my mobile app which is authenticating my request origin means from which url my iframe url has called. if that url was authenticated(Registered in my third party api account) then and then that iframe will display otherwise they will give me error that your credentials are wrong

**Comment by martijnwalraven** [comment]
The app will load all resources from the local filesystem, using the special http://meteor.local domain. There is no way to configure this. (Cordova normally uses file:// URLs here, which wouldn't help you either.)

Even if you could change meteor.local to a custom domain, that wouldn't make your approach any more secure. Anyone would be able to change their app to use the same name. A referer header is not a real security mechanism, as it is up to the HTTP client to set it.

**Comment by dhavalrajani92** [comment]
So as per your answer http://meteor.local is request origin for the mobile app and i need to register that url with my third party api system.

**Comment by martijnwalraven** [comment]
Yes.

**Comment by dhavalrajani92** [comment]
Ok thanks for this help. My code is working now with this http://meteor.local/ .
