### ISSUE TITLE
How do I change HTML in meteor app

### ISSUE THREAD

**Issue by krishnakc** [meteor/meteor#4773]
Hi Team,

I am excited with meteor features, I would like to change some of the html pages and customise them, I appreciate quick response

Thanks
-Krishna

**Comment by rfox90** [comment]
The issues section on github isn't for these sorts of questions.

you might want to redirect your question to: https://forums.meteor.com

However a little bit of info that might help:
Just edit the files. I have no idea of your project structure but their should be HTML files within it or you can create them. There's a tutorial here: https://www.meteor.com/tutorials/blaze/templates

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
