### ISSUE TITLE
The feature of Meteor.methods where methods automatically generate the same id on the client and server for inserts is not documented anywhere

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4780]
Except for this trello card: https://trello.com/c/moiiS2rP/57-pattern-for-creating-multiple-database-records-from-a-method

**Comment by justinsb** [comment]
Indeed, https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md says that it is deliberately undocumented 'pending stabilization'.  Perhaps we can now consider it stable and document it!

**Comment by stubailo** [comment]
Yep, we should make sure to document it nearby the Methods section on docs.meteor.com as well.

**Comment by abernix** [comment]
Moved to meteor/docs#19
