### ISSUE TITLE
Docs: Function declaration is not a "shorthand" for an assignment

### ISSUE THREAD

**Issue by dalgard** [meteor/meteor#4785]
In the section "Namespacing", it says:

> When declaring functions, keep in mind that function x () {} is just shorthand for var x = function x () {} in JavaScript.

This is not true and potentially misleading. Due to hoisting, a function that is declared is available within the whole scope, whereas a function expression that is assigned to a variable is only available from the point where it is assigned (only the variable name is hoisted).

**Comment by anubhav94** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by abernix** [comment]
Thanks for reporting this @dalgard.  This incorrect statement gone in the [newly revamped Meteor Docs](http://docs.meteor.com).  Closing. :smile:
