### ISSUE TITLE
Link to correct docs for Spacebars

### ISSUE THREAD

**Issue by peterchoo** [meteor/meteor#4786]
Currently the Spacebars documentation link goes to the development branch, which is misleading as to what is *actually* in the latest production build of Meteor.  I've seen numerous questions pop up (mostly relating to @index in the #each helpers) over the past few weeks.

Can we instead link to the [master branch](https://github.com/meteor/meteor/blob/master/packages/spacebars/README.md) version of the docs?

Thank you

**Comment by Slava** [comment]
This is already done on devel.

**Comment by peterchoo** [comment]
@Slava - not in all places  I opened PR #4787 to catch the three other places the docs were incorrectly linked.
