### ISSUE TITLE
Oplog tailing on sharded mongo

### ISSUE THREAD

**Issue by marcodejongh** [meteor/meteor#4788]
Currently working on a large scale application where we have to shard mongo.

If I remember correctly oplog tailing does not work on a mongo shard. Is this still the case? Is adding support for it something that the meteor team will take care of? If so what will be the timeline?

If sharding support has already been added then it definitely lacks documentation.

**Comment by Slava** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I agree that support for sharded MongoDB instances will help supporting larger instances.

**Comment by fjorgemota** [comment]
By the way some time ago MongoDB.com published in it's blog some tips to help in this issue:

- https://www.mongodb.com/blog/post/tailing-mongodb-oplog-sharded-clusters
- https://www.mongodb.com/blog/post/pitfalls-and-workarounds-for-tailing-the-oplog-on-a-mongodb-sharded-cluster

I think it is worth to keep this links to whoever will work on this issue (which should be an interesting challenge, I think)

**Comment by abernix** [comment]
Thanks for opening this originally!  This works with newer versions of Meteor which have the more recent Mongo driver (Meteor 1.4+).

The actual implementation/setup of the Mongo server is tricky though and best left to a MongoDB provider or to an exercise in the [MongoDB Docs](https://docs.mongodb.com/v3.2/).  Your `MONGO_URL` will need to list all of the appropriate hosts.
