### ISSUE TITLE
Integration with PostgreSQL JSONB

### ISSUE THREAD

**Issue by kokizzu** [meteor/meteor#4789]
It would be nice if meteor has integration with PostgreSQL 9.4+ JSONB data type.
http://www.postgresql.org/docs/9.4/static/datatype-json.html
JSONB data type is similar to MongoDB's document.

using JSONB we could use something like this:

```
CREATE TABLE users {
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data JSONB -- the data type
};
CREATE INDEX ON users USING GIN(data); -- fast search
INSERT INTO users(data) VALUES(  '{"name":"foo","age":29}' );
UPDATE users SET data=jsonb_merge(data, '{"name":"bar"}' ) WHERE id = 1;
SELECT * FROM users WHERE data->>'name' = 'bar';
SELECT * FROM users WHERE (data->>'age')::INT > 20;
```

the jsonb_merge function: http://dba.stackexchange.com/a/95768/15834

The advantage of using PostgreSQL instead of MongoDB is the ACID part.

**Comment by Slava** [comment]
Thanks for the feature request. We are tracking the project called "SQL Support" in the roadmap: https://trello.com/c/Gf6YxFp2/42-sql-support

I have been looking into JSONB recently and looks like a good support is possible. This is something that can be done in packages, too. It doesn't look like there is anything tied to Meteor Core. Also, see my notes on this here: https://github.com/Slava/jsonb-mongodb

**Comment by hwillson** [comment]
MDG's recommended solution for integrating SQL based databases with Meteor applications is to use [GraphQL](http://graphql.org). MDG has created a set of tools to help with this ([Apollo](http://www.apollodata.com)). As things stand currently, any upcoming database integration changes will revolve around better Meteor + GraphQL/Apollo integration (if/as necessary), so I'll close this issue. Thanks for the original feature request!

P.S. --> Some community members are currently using Meteor with PostgreSQL via GraphQL/Apollo; for more specific details try asking on the [Meteor Forums](https://forums.meteor.com).
