### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by meichenblatt** [meteor/meteor#4790]
Recaptcha is working but for some reason I'm getting an error: 

"Uncaught ReferenceError: grecaptcha is not defined"

Template.share.rendered = function() {

    $.getScript("https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit", function() {
        onloadCallback();
        console.log('reCaptcha Loaded');
    });

    onloadCallback = function () {

        grecaptcha.render('recaptcha1', {
            'sitekey' : 'SITE_KEY',
            'theme' : 'light'
        });

    };

};

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
