### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [meteor/meteor#4791]
Hey there Meteorites,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for Meteor in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?

**Comment by anubhav94** [comment]
Hey @csuwildcat,

Thanks for your message! As far as I know, Microsoft Edge hasn't been released yet and thus we haven't started testing on it yet. Once Edge is released, we'll start adding it to our tests. As of now, we support IE8 and higher. If you want to test on Edge and file bugs, we'd appreciate it and you're more than welcome to.

**Comment by trajano** [comment]
Can this be re-openned now that Windows 10 and Microsoft Edge has been released?

**Comment by abernix** [comment]
@trajano, Are there specific issues that you're experiencing with Edge?  Or are you simply asking for Microsoft Edge tests?
