### ISSUE TITLE
Add a way to avoid method blocking forever if Meteor.wrapAsync callback never fires

### ISSUE THREAD

**Issue by aunz** [meteor/meteor#4795]
Consider this code

``` javascript
Meteor.methods({
  'test': function(){
    return Meteor.wrapAsync(neverCallBack,null)();
  }
});

function neverCallBack(cb){
  Meteor.setTimeout(function(){
    //cb(null,"You will never see me");
  });
}

```

If a client calls

``` javascript
 Meteor.call("test",function(err,res){!err && res && console.log(res);});
```

The console will never log anything and the client won't be able to make other calls while waiting.

We can use `this.unblock` to allow more calls from the client, but how can we guard against this kind of situation when the cb is never called, for example, when using a third party function?

Does meteor has some built in functions to check if callback in wrapAsync will not be called after a certain period of time?

**Comment by stubailo** [comment]
Having a timeout in `wrapAsync` could be a good feature to add.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hems** [comment]
indeed a timeout would be a very good start!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20way%20to%20avoid%20method%20blocking%20forever%20if%20Meteor.wrapAsync%20callback%20never%20fires&body=Migrated%20from:%20meteor/meteor%234795) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
