### ISSUE TITLE
Problems with accounts-facebook and meteor build

### ISSUE THREAD

**Issue by Poliuk** [meteor/meteor#4796]
Hello,

First of all, I don't know if **accounts-facebook** issues must be placed in this repo, if not I will appreciate if someone can guide me to the right place.

I'm having an issue with my production App and the Accounts Facebook package, I've asked in the meteor forums but there was no answer: https://forums.meteor.com/t/facebook-login-how-to-configure-the-url/6649

While developing in localhost and meteor.com servers, this tutorial worked fine: http://bulenttastan.net/login-with-facebook-using-meteor-js/

My App is running in a linode server, and it is not running directly with meteor cause I've used **meteor build**. 

Is there any guide where I can understand how to configure Facebook in order to work with a production meteor App, with the ROOT_URL, the port? I'm completely lost, and I don't know if this is a problem of Meteor or Facebook.

**Comment by Slava** [comment]
Hi @Poliuk,

We usually keep GitHub issues for bug reports, pull-requests and feature requests. All questions on usage should go to Meteor Forums and StackOverflow.

If you are reporting an issue, we require a reproduction in a form of a public repository that demonstrates the problem. A lot of people use Facebook social login on their production Meteor sites and nobody has reported any issues yet.

ROOT_URL is used in a variety of places, usually it is set to the public-facing url of the site. It is also used in absoluteUrl method described here: http://docs.meteor.com/#/full/meteor_absoluteurl

**Comment by Poliuk** [comment]
Thanks @Slava, and sorry for the mistake opening this here.

In case some one finds this thread, the problem was not related with meteor but with Facebook. The production App was running in a port different from the 80 and Facebook was not able to recognize the App.

So the solution was simple, I moved the app to a subdomain http://app.myapp.com instead of http://myapp.com:5321

**Comment by Slava** [comment]
@poliuk glad you resolved your issue. Note that port is important to both Facebook configuration and the ROOT_URL.
