### ISSUE TITLE
Collection.remove() should throw an error when used with an empty array, instead of removing all items

### ISSUE THREAD

**Issue by AChusuei** [meteor/meteor#4804]
So, with javascript it is really easy to inadvertently pass an array object `Collection.remove(array)` as the selector, and if that array is the empty array, it deletes all documents in that collection! 

`Collection.remove()` should throw an error if passed an array (like it does in mongo!) or at the very least not delete the whole collection if an empty array gets passed as the selector. This seems like a very dangerous query loophole that could easily burn beginners of Meteor.

**Comment by osv** [comment]
But in doc we can find:
>Set selector to {} if you really want to remove all documents from your collection.

Also, I think beginners must know, that better use some **"remove" flag** instead of deleting record.

**Comment by jagi** [comment]
@osv empty array is not the same as empty object.
@AChusuei in deed, passing an array removes all the records when in Mongo it returns error.
In my opinion it should be fixed to match the way the Mongo database does it.

**Comment by AChusuei** [comment]
@jagi :+1: absolutely. Let's say this burned me just now ...

**Comment by AChusuei** [comment]
@osv, for a less seasoned js and mongo programmer, it feels idiomatic to pass an array of ids to a query, and it's really easy to do this if you are not that versed in the mongo selector query style.

**Comment by stubailo** [comment]
I'm not sure if it's idiomatic or not, but I agree that Mongo should probably throw an error instead of silently accepting the wrong type of argument, worse still if that results in deleting all items from the database.

**Comment by AChusuei** [comment]
Woo! Thanks @stubailo! =)

**Comment by AChusuei** [comment]
@stubailo, would it be possible at all to include me in the PR when you get around to doing this? Just curious to see how this would be implemented.

**Comment by AChusuei** [comment]
@stubailo, looks great thanks! ^_^
