### ISSUE TITLE
Node modules installed on the server side

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#4806]
Since Meteor 1.0, we can define node modules in `.meteor/package.json` like following

```
{
  "dependencies":{
    "jquery": "2.1.0",
    "jsdom": "3"
  }
}
```

after running `npm install` it works great on local environment. However, when I do `meteor deploy myapp.meteor.com` the app crashes. The error log is

```
WARNING Error: Cannot find module
'jquery'
```

I think this means `npm install` hasn't been run on the server side. Is this not supported by default when you deploy your app?

**Comment by stubailo** [comment]
@woniesong92 this is not a supported or tested way of using NPM packages with Meteor, so `meteor deploy` doesn't know that it needs to run NPM install. There are two options:

1. Use `Npm.depends` inside a package: http://docs.meteor.com/#/full/Npm-depends
2. Use `meteorhacks:npm`, which automatically generates a local package with `Npm.depends` for you: https://github.com/meteorhacks/npm

Hopefully, we will soon have a more official way to use NPM packages in an app directly, but putting a `package.json` file inside `.meteor` probably won't be it. Let me know if one of the methods above works for you.
