### ISSUE TITLE
MongoDB driver need upgrade for MongoDB 3.0

### ISSUE THREAD

**Issue by leonsim** [meteor/meteor#4808]
There is a bug for current used mongoDB driver: <https://jira.mongodb.org/browse/NODE-382>. upgrade it to version 1.4.34 the issue resolved.

**Comment by liangsun** [comment]
I rerun `mup setup`, and this is resolved.

**Comment by liangsun** [comment]
The current used npm mongo is in version: `1.4.32-plugins.0_1`. There is a bug in this version for MongoDB 3.0:

After upgrading a sharded cluster to mongodb 3.0.0 without upgrading to SCRAM-SHA1, we've been getting occasional exceptions in our web app every few minutes to an hour or so:

```
TypeError: Cannot read property 'done' of null,
         at node_modules/mongodb/lib/mongodb/auth/mongodb_scram.js:165:17,
         at node_modules/mongodb/lib/mongodb/db.js:1191:22,
         at null.<anonymous> (node_modules/mongodb/lib/mongodb/db.js:1903:9),
         at g (events.js:199:16),
         at emit (events.js:110:17),
         at Server.Base.__executeAllCallbacksWithError (node_modules/mongodb/lib/mongodb/connection/base.js:346:25),
         at null.<anonymous> (node_modules/mongodb/lib/mongodb/connection/server.js:528:14),
         at emit (events.js:107:17),
         at null.<anonymous> (node_modules/mongodb/lib/mongodb/connection/connection_pool.js:184:15),
         at emit (events.js:110:17)
```

According to <https://jira.mongodb.org/browse/NODE-382>, after upgrading to 1.4.34 the exception seems to have gone.

I think we can upgrade the native mongodb driver from `1.4.32-plugins.0_1` to `1.4.34`. I would like to submit a pull request to fix this issue, but I don't know where to get started.

**Comment by Slava** [comment]
Thanks for your issue, I think @dgreensp is looking into this as part of the release process for the next release of Meteor.

**Comment by liangsun** [comment]
Thanks @Slava 

@dgreensp 
I have already submit a pull request <https://github.com/meteor/node-mongodb-native/pull/1>
I believe after merging the upstream of node-mongodb-native driver, it only needs to modify the tarball address referenced in meteor repo.

**Comment by laosb** [comment]
#6957 So this is outdated. Closing.

**Comment by leonsim** [comment]
Thanks.
