### ISSUE TITLE
Heterogenous Attributes (Like HTML)

### ISSUE THREAD

**Issue by DerekTBrown** [meteor/meteor#4809]
In passing data to templates, the parser works one of two ways.  It either returns a string:

```
{{#foo bar}}
{{/foo}}
RESULT: this.data = "bar"
```

or it returns an object

```
{{#foo bar="baz" bat="bah"}}
{{/foo}}
RESULT: this.data = {bar: "baz", bat: "bah"}
```

However, it cannot parse multiple strings, or a combination of strings and objects. It would be nice to be able to parse both of these elements, to replicate HTML like features.  For example:
    {{#foo snap crackle="pop"}}
    {{/foo}}
    RESULT: this.data = {snap:"", crackle:"pop"}

**Comment by anubhav94** [comment]
Hey @DerekTBrown,

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
I've moved this over to meteor/blaze#174 - closing - thanks!
