### ISSUE TITLE
Deploy android application with own server

### ISSUE THREAD

**Issue by maxtor3569** [meteor/meteor#4811]
Hello Everyone, I'm stuck since several day.

I have my meteor hosted on https://myownserver.com. Use ngix and mongodb in my own server
I build the android application with meteor build --server=https://myownserver.com, and after I transfer to my device.

However, the app on my device seems not connected to the database of the server.
I have unbinded the mongo to listen to 127.0.0.1 and set up port to 27017.

I have some questions : 

1) Do I need to set up MONGO_URL or  ROOT_URL at the startup server of the app before build? How do I set up these?
2) MONGO_URL need to be set to mongodb://localhost:27017/mydatabse or mongodb://myownserver:27017/teamsport ?
3) I understand that option --server set up root url. Did this option also set up mongourl? How can I check on my android application that server option is correctly set?

Thanks for your support. It's not clear for me now

**Comment by Slava** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

Usually, you need to set up the MONGO_URL for the app server you build with the `meteor build` command.

Once you build a bundle, `cd` into bundle and read the README file that is placed there.
