### ISSUE TITLE
Add support for MongoDB SSL URIs

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4812]
URI: `domain.com:1234/db?ssl=true`
console: `mongo -ssl -sslCAFile example.pem example.dblayer.com:10373/admin -u user -p pass`

https://www.compose.io/articles/going-ssl-with-compose-mongodb-plus/

**Comment by Slava** [comment]
What is this feature request? Is it support for the mongo driver? For mongo shell? Is there a reproduction?

To my knowledge, we pass the MONGO_URL string to the node driver which already supports SSL urls.

**Comment by alax** [comment]
Just for future reference for anyone confused about how to add the PEM file or setting -sslVerify or anything like that (like I was), note that the node driver (which Meteor uses) doesn't require it:  http://mongodb.github.io/node-mongodb-native/2.0/tutorials/enterprise_features/

It won't do any certificate chain validation (which is less than ideal), but it will connect. All you need to do is specify `?ssl=true` on your connection string to connect to an SSL-enabled host.
