### ISSUE TITLE
Ubuntu node not found

### ISSUE THREAD

**Issue by kaaninel** [meteor/meteor#4813]
![image](https://cloud.githubusercontent.com/assets/3465923/8890461/75f5cd8e-330a-11e5-9d20-d4dcc09efa75.png)
![image](https://cloud.githubusercontent.com/assets/3465923/8890469/b0501fb6-330a-11e5-835f-d299310209ea.png)

**Comment by stubailo** [comment]
@kaaninel It is definitely not a good idea to run Meteor with `sudo`. The situation happening here is that Meteor is looking in your home folder for the installation, but it is being downloaded into the `root` home folder.

I think the best thing to do would be to just run `meteor` without `sudo`. Does that work for you?

**Comment by abernix** [comment]
Closing this due to lack of response.  You shouldn't need to run meteor with `sudo`, unless you are really trying to run it on a privileged port (e.g. <=1024).  Also, please try a more recent version of Meteor if you're still experiencing this problem.
