### ISSUE TITLE
How to print messages with the => like during Meteor startup?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4818]
Is there an official way to print messages that start with `=>` like we see during startup? f.e.

```
=> Started proxy.
=> Started MongoDB.
```

The loading animations is always after those messages. It'd be useful to output similar messages with a build plugin. I can do `console.log('=> blah blah')`, but it write over the loading animation sometimes.

**Comment by xgram** [comment]
I noticed this npm package had an animation throbber
https://www.npmjs.com/package/cli-color#throbber-write-interval-format
may give some ideas where to look.

**Comment by Slava** [comment]
The Meteor tool manages the output with the file called console.js. We don't expose this functionality to the build plugins (at least as of Meteor 1.2).

You shouldn't try to interfere with this output unless there is an official interface for this.

**Comment by trusktr** [comment]
@Slava Yeah, it'd be super cool if there was an official a way to add to those messages. The current way to do is is output a message like `=> foo                                                                      ` which has enough spaces at the end to go past the spinner animation, then the animation continues on the next line.
