### ISSUE TITLE
FR: Give Meteor apps access to package meta-data

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#4822]
In Telescope, we'd like to have an admin page that shows a list of all installed packages, along with their version, description, etc. 

That information is already included in each package's `package.js`, but it's [not accessible from within the app](https://forums.meteor.com/t/finding-out-the-version-of-a-package-from-within-your-app/4315/10) (at least, when deployed in production). 

So I would like to put in a request for that information to be made available to the app both in development and production modes.

**Comment by rfox90** [comment]
Have you see Reaction Commerce's way of dealing with this?

Each optional package runs some core code that registers it back to core. 

https://github.com/reactioncommerce/reaction-braintree/blob/development/server/register.coffee

Its not exactly what you are asking for but I liked their approach.

**Comment by stubailo** [comment]
@rfox90 I really like this approach - if there are telescope-specific packages, I would think that having custom telescope-specific metadata would be the way to go.

I'm going to do the same thing in my tutorial-tools packages that I'm working on - basically have a package that facilitates communication between the package and app in a mutually agreed upon way.

On the other hand, it could be a good idea to have metadata fields in `package.js` so that they could be shown on atmosphere. Then you could filter, for example, for packages designed to be used with Telescope.

**Comment by SachaG** [comment]
Yeah that's an approach we're considering. I was just thinking since some of that data is already there, maybe we could somehow send it over to the app?

You could even imagine something like:

```js
Package.describe({
  name: "telescope:api",
  summary: "Telescope API package",
  version: "0.22.2",
  git: "https://github.com/TelescopeJS/Telescope.git",
  options: {
    thumbnail: "my_image.jpg",
    homepage: "http://www.plugin.com",
    ...
  }
});
```

For custom properties?

**Comment by stubailo** [comment]
I think I would prefer custom properties, something like:

```
telescopePlugin: {
  thumbnail: "xxx",
  pluginType: "something"
}
```

Homepage is probably something we should have regardless.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=FR%3A%20Give%20Meteor%20apps%20access%20to%20package%20meta-data&body=Migrated%20from:%20meteor/meteor%234822) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
