### ISSUE TITLE
missing documentation for setting a prefix for bundle urls

### ISSUE THREAD

**Issue by SierraGolf** [meteor/meteor#4824]
I was looking for a way to prefix statics with a CDN URL and I basically found out about the `WebAppInternals.setBundledJsCssPrefix` by navigating from here: https://groups.google.com/forum/#!msg/meteor-core/XDWx5kscddY/lUby11FNGhEJ to the source code.

Is there a specific reason why I can not find any official documentation?

In case this is actually the official way to set a prefix to the bundled js and css files, I wonder if it wouldn't be more consistent to have an environment variable for that, e.g. `BUNDLE_URL`. At least to me the name `WebAppInternals` does not sound like a public API.

**Comment by Slava** [comment]
Thanks for pointing out an underdocumented aspect of Meteor!  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

Specifically, there is a reason why  it is placed on the symbol `WebAppInternals` and not `WebApps`. This is not a very pressing feature that the Core team had time to spend on.

**Comment by SierraGolf** [comment]
Currently there is generally not so much documentation about configuration, especially environment variables like ROOT_URL. Where would be the place to put the documentation?

Would it make sense to create a pull request introducing the BUNDLE_URL environment variable and adding proper documentation at the same time?

**Comment by hwillson** [comment]
Documentation suggestions/requests are now managed via the [meteor/docs](https://github.com/meteor/docs) repo. Since this issue hasn't been active in quite some time, I'll close it off. If you're still interested in working on this issue, please consider opening a new issue in the docs repo. Thanks for submitting this originally!
