### ISSUE TITLE
User gets stuck in limbo when login token expires

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [meteor/meteor#4825]
How to reproduce:
1. Open any Meteor app in a browser.
2. Sign in.
3. Either wait 3 months (hehehe), or open developer tools and set Meteor.loginTokenExpires in local storage to a date in the past.
4. Reload the page.
5. Observe nothingness.

There is no easy way for user to recover from this.

**Comment by Slava** [comment]
Fixed in 4c57fae881d2737a5e36f67abb7e5707585180d8
