### ISSUE TITLE
Spiderable should look for Slack's user agent string

### ISSUE THREAD

**Issue by johanbrook** [meteor/meteor#4830]
The [robots of Slack](https://api.slack.com/robots) are scraping a URL when it's posted in a chat channel, and a nice preview is shown. The problem is that the Slack robot isn't confirming to the `?_escaped_fragment_=` convention. Thus, we need to check for its user agent string when it hits the site.

It's simply done by adding the agent string

```
/^slackbot-linkexpanding/i
```
to the list of regexes in Spiderable.

I for one think this is important, since it's currently impossible for Slack to crawl Meteor apps. If this is something to be done, I'd be happy to file a PR. This works great in a local copy of Spiderable in our app.

**Comment by stubailo** [comment]
Fixed! Hopefully we can put this in Meteor 1.2

**Comment by johanbrook** [comment]
@stubailo Awesome! Thanks so much :sparkles:
