### ISSUE TITLE
Cordova EACCESS error when trying to run in iOS emulator

### ISSUE THREAD

**Issue by kylehagler** [meteor/meteor#4833]
all of a sudden getting the following error when trying meteor ios run

Error while running for mobile platforms: EACCES, unlink '/Users/me/dev/my-app/.meteor/local/cordova-build/resources/android_hdpi.icon.png'

**Comment by jonathanjot** [comment]
You have use 'sudo' in order to use meteor. You shouldn't do that.

perform a chown command on your .meteor folder in order to correct permission.

on Mac OS permission should be something like 
chown -R {your_user}:staff .meteor/

**Comment by Slava** [comment]
I think an easy fix is to reset your build and try again (`meteor reset`). Never run `meteor` from non-your user. Meteor relies on owning the temporary files it creates on the filesystem for the build.
