### ISSUE TITLE
TypeError: Object #<Object> has no method 'debug'

### ISSUE THREAD

**Issue by brylie** [meteor/meteor#4834]
We are trying to run Meteor 1.1.0.2 on Windows 7.

While troubleshooting issue #4709, we get an error regarding the Console.debug() method being missing:

```
.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x8
6_32\tools\files.js:643
Console.debug(err);
^
TypeError: Object #<Object> has no method 'debug'
at Object._onImmediate (C:\Users\username\AppData\Local\.meteor\packages\meteor
-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643:15)
at processImmediate [as _immediateCallback] (timers.js:354:15)
```

This is after we manually add the following code to `files.js`:
```
var Console = require('./console.js');
```

**Comment by Narven** [comment]
im not on windows now.
Can you try and open console.js file and check if the debug method is in there?

**Comment by Slava** [comment]
I believe this happens when Meteor fails to clean up a temporary directory.

The broken reference to `Console` is mysterious but we semi-fixed it in this commit: https://github.com/meteor/meteor/commit/4d6a5fe795bb0e2253d2f6d7f6a7b6affe8e112b

**Comment by leizard** [comment]
I'm having the exact issue
