### ISSUE TITLE
OAUTH very seriously error with fake base64 decode

### ISSUE THREAD

**Issue by psy21d** [meteor/meteor#4835]
meteor/packages/oauth/oauth_server.js

Google it: 
(oauth_server.js:78) Unable to parse state from OAuth query: FAKEFAKEKAKE

People get drubbing together with obtaining query.state on many oauth services, because oauth_server.js parse answer as base 64 without disassembling when it is not base 64 at all.

And, no information on internet about this problem. 
![oauthyarr](https://cloud.githubusercontent.com/assets/11248900/8955918/ac103796-35f9-11e5-8423-6e1e443120d3.jpg)

Please, fix it recently.

![oauth](https://cloud.githubusercontent.com/assets/11248900/8955484/cfb86ece-35f5-11e5-9aed-f1e39db5bafc.png)

**Comment by psy21d** [comment]
There is:
    string: "ÕI¨¯­ª¯spä"
    query: {
        close: "close"
        code: "711d643a3b6cb7b523"
        state: "HNWASaivraqvc3Dk4"
    }

Need: 
    string: "HNWASaivraqvc3Dk4"

**Comment by psy21d** [comment]
http://vk.com/dev/auth_sites

**Comment by sebakerckhof** [comment]
I've mentioned this earlier as part of this problem: https://github.com/meteor/meteor/issues/4497 (step 2 in the latest comment)

However, this seems to be the intended behavior for certain flows. E.g. the oauth flow from meteor tool, which only adds the credentialtoken to the query state. But then still, it is a bit weird that an error is displayed in the console.

**Comment by psy21d** [comment]
Need to check BASE64 string encoding, and if it is not, return clean string.

**Comment by sebakerckhof** [comment]
It actually does this, but further down the road.

So basically it tries to base64 decode and if this fails, the OAuth._stateFromQuery will throw, which is usually caught in the calling function (e.g. in OAuth._credentialTokenFromQuery), which then return the clean string (which is the credential token) instead.

So this seems to be correct behavior, but it's a bit weird that this is being done by throwing and logging errors.

**Comment by psy21d** [comment]
But there is not fails and fails later!!
Bad situation. Maybe need to create settings (options) way for OAUTH services?

**Comment by psy21d** [comment]
Not weird at all, because it is server console.

**Comment by psy21d** [comment]
Whats-a-problem to write properly code? Need to fix it, Please!

HNWASaivraqvc3Dk4 is-not-a Base64 string, so simply to check it.
Why you to write try-catch dummies when have a full specification
Your code SIMPLY NOT WORK as need!!

"HNWASaivraqvc3Dk4".length 
17

https://en.wikipedia.org/wiki/Base64
MUST to read.

Many people caught this error and you write "I was made nice code and thats work proper".

No, does it not work how need.
I am a beginner, I am no right to prove, but understand it is not operating properly, even to me it's obvious.

Instead, changes in the two lines code we are Arguing. What For?
https://en.wikipedia.org/wiki/Base64

Meteor is big and expensive project and need to be actual and yes, code need to be orderly and straight.

Thank you for understanding!

**Comment by psy21d** [comment]
Use ONLY specification and RFC!

**Comment by psy21d** [comment]
so, this code works good.
line 99: 

    OAuth._credentialTokenFromQuery = function (query) {
      var state;
      // For backwards-compatibility for older clients, catch any errors
      // that result from parsing the state parameter. If we can't parse it,
      // assume that the state parameter's value is the credential token, as
      // it used to be for older clients.
      try {
        state = OAuth._stateFromQuery(query);
      } catch (err) {
        return query.state;  // there is
      }
      return state.credentialToken;
    };

Problem closed.

**Comment by stubailo** [comment]
@psy21d if you would like to submit a Pull Request on GitHub so that we can review and consider merging, follow these directions: https://help.github.com/articles/using-pull-requests/

**Comment by adamgins** [comment]
related issue https://github.com/meteor/meteor/issues/8678
