### ISSUE TITLE
Adding callbacks to write fence after it has been armed in Oplog Driver

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#4839]
From https://forums.meteor.com/t/try-out-a-preview-of-batch-build-plugins-and-other-1-2-features/7374/16 (by @louisdescioli):

---

```
Exception in Mongo write: Error: fence has already activated -- too late to add a callback
I20150729-05:24:28.230(-4)?     at [object Object]._.extend.onBeforeFire (packages/ddp-server/writefence.js:69:1)
I20150729-05:24:28.230(-4)?     at Object.callback (packages/mongo/oplog_observe_driver.js:154:1)
I20150729-05:24:28.231(-4)?     at packages/ddp-server/crossbar.js:109:1
I20150729-05:24:28.231(-4)?     at Array.forEach (native)
I20150729-05:24:28.231(-4)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150729-05:24:28.231(-4)?     at [object Object]._.extend.fire (packages/ddp-server/crossbar.js:107:1)
I20150729-05:24:28.231(-4)?     at Object.Meteor.refresh (packages/ddp-server/server_convenience.js:9:1)
I20150729-05:24:28.232(-4)?     at packages/mongo/mongo_driver.js:374:1
I20150729-05:24:28.232(-4)?     at Array.forEach (native)
I20150729-05:24:28.233(-4)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
```

Here's a recreation: https://github.com/lourd/meteor-ecmascript-bug

The key file is foo-test.js

```
describe('Running some tests', () => {
  it('should run', (done) => {
    Meteor.call('dropThings', (err, res) => {
      expect(err).to.equal(undefined);
      expect(res).to.equal(2);
      console.log("test finished");
      done();
    });
  });
});
```

This will run fine on the client, not triggering any error. But running it on the server throws that Mongo error. Other observations:

- It only happens when using Meteor.call in an it, before, or beforeEach block -- not if it's just in a describe block.
- It doesn't happen in the application. Checkout sandbox.js to see that -- does the same thing, no problem
- Operation on the collection doesn't matter. I've tried removing and inserting, it still throws the same error
- The error comes after the test has finished. I'll see test finished in the console before I see the Mongo write fence error

---

Looks like this error could have originated from this change: https://github.com/meteor/meteor/pull/4694

**Comment by Slava** [comment]
@lourd, I ran the repo with both `curmeteor` and `curmeteor test-packages ./packages/foo`. Didn't get this stack trace.

**Comment by lourd** [comment]
From a fresh clone I'm seeing this

```sh
$ meteor --version
PLUGINS-PREVIEW@2
$ meteor test-packages ./packages/foo/
```

And then seeing the stack trace. 

I actually hadn't tried it with the default test reporter yesterday though, I was using Velocity and Respondly's test reporter. If you want to try that, jump into the directory and test. There's a `package.json` in `packages/foo` to simplify running it

```sh
$ cd packages/foo
$ npm test # run it in the terminal
$ npm run test-pretty # run it in the test reporter
```

Either way, I'm seeing it for all 3 variations

**Comment by Slava** [comment]
I could reproduce it with `npm test`. I guess this doesn't happen in a regular app for me, but only when the package is tested.

**Comment by Slava** [comment]
Tagging @glasser so he receives notifications for this issue.

**Comment by darkship** [comment]
I have it sometimes too with Kadira: 
```
Exception in Mongo write: Error: fence has already activated -- too late to add a callback
    at [object Object]._.extend.onBeforeFire (packages/ddp-server/writefence.js:69:1)
    at Object.callback (packages/mongo/oplog_observe_driver.js:154:1)
    at packages/ddp-server/crossbar.js:109:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object]._.extend.fire (packages/ddp-server/crossbar.js:107:1)
    at [object Object].kadira_Crossbar_fire [as fire] (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:3348:1)
    at Object.Meteor.refresh (packages/ddp-server/server_convenience.js:9:1)
    at packages/mongo/mongo_driver.js:377:1
    at Array.forEach (native)
```

And in my own app, a delayed insert caused the same but I'm unable to reproduce it.

**Comment by lourd** [comment]
This happens with an even simpler use case. This is a package with nothing but a single test file that runs on the server.

```js
describe('A generic server test', () => {
  it('should do something really easy', () => {
    expect(true).to.be.true;
  });

  it('should do another really easy thing', () => {
    expect(false).to.be.false;
  });

})
```

It looks like something with Velocity is broken for server-side tests.

**Comment by woniesong92** [comment]
+1 It happens with my app too, in a callback to create an account.

**Comment by glasser** [comment]
I'm pretty sure the issue is that onBeforeFire throws an error on a retired fence, unlike beginWrite.  (See dcd26415fe for background on what retired means.)  We should either drop that error or make OplogObserveDriver check to see if the fence is retired and do nothing in that case.

But first I should note that the reproduction is broken on devel: `curmeteor test-packages --driver-package respondly:test-reporter ./` has some issues due to jquery no longer being available.  Filed https://github.com/Respondly/meteor-util/issues/4

**Comment by lourd** [comment]
Just updated to 1.2-rc.3 and still seeing the simple reproudction fail in the terminal and on the test reporter

**Comment by glasser** [comment]
Fixed. Thanks for the reports!
