### ISSUE TITLE
Meteor Collection returns collection of wrong “limit” if “skip” parameter has floating point

### ISSUE THREAD

**Issue by iSuslov** [meteor/meteor#4844]
Meteor Collection returns collection of wrong “limit” if “skip” parameter has floating point 19.999999999999996

**Comment by Slava** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Does it happen on querying? Does it happen on server or client? Does it happen on LiveQuery?

**Comment by Slava** [comment]
I couldn't reproduce it neither on client, nor on server. Neither with querying, nor with observe APIs.
