### ISSUE TITLE
Ability to Create Meteor in an existing folder.

### ISSUE THREAD

**Issue by w1nterl0ng** [meteor/meteor#4845]
When you have a folder that does not currently have a meteor app in it, it would be nice to be able to create a new meteor app using the name of the folder.
`mkdir newApp`
`cd newApp`
`meteor create .`
When I do this I get `/path/to/file: Already exists`

@sircharleswatson

**Comment by w1nterl0ng** [comment]
not sure if it matters it here is the place in the code where this issue is located.
https://github.com/meteor/meteor/blob/cb681e595f709f569a0d23cc09268cd087ddc1bc/tools/cli/commands.js#L632

**Comment by sircharleswatson** [comment]
This would be helpful for example, if you create a project on Github with a README and then clone the app.

Then you can cd into the app and do `meteor create .` to make it a meteor app.

I was pretty sure that I've done this before but now I'm getting the error that @w1nterl0ng is getting. Not sure if that changed or I was just mistaken about being able to do it.

**Comment by Slava** [comment]
The conversation for this feature is happening here: https://github.com/meteor/meteor/pull/2276.
