### ISSUE TITLE
Send static html to the client without blaze

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4846]
I'm in the trenches building my "package-based" meteor app. I've removed `meteor-platform` and added back only the packages I need:

```
    'meteor',
    'webapp',
    'logging',
    'underscore', // https://github.com/meteor/meteor/issues/4843
    'random', // https://github.com/meteor/meteor/issues/4843
    'tracker',
    'ddp',
    'mongo',
    'check',
```

Now I have some static html thats not making it to the client:

```
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

I suppose I may need to add the `templating` package:

https://github.com/meteor/meteor/tree/devel/packages/templating

It appears that will add Blaze back to my project though :-1:

**Comment by stubailo** [comment]
Way ahead of you ;] https://github.com/meteor/meteor/pull/4829

Going to close this issue since that PR pretty much covers it.

**Comment by stubailo** [comment]
@ccorcos feel free to try running from that branch to see if that implementation works for you! If not, leave feedback there.

**Comment by ccorcos** [comment]
sweet :+1:

- is there any way for me to always keep meteor up to date with the devel branch?

**Comment by stubailo** [comment]
You can run it from a checkout. We're currently working on ways to make it easier to have cutting-edge Meteor without having to clone the whole repository with git.

Here are directions: https://github.com/meteor/meteor#slow-start-for-developers
