### ISSUE TITLE
want to deploy two meteor application with different mongo url on ubuntu server

### ISSUE THREAD

**Issue by dhavalrajani92** [meteor/meteor#4849]
Hello,

I have a two Meteor application which is working with different mongoDb i want to deploy both application on one server with different mongoDb url. And i want to deploy that application with making build of that application. So could you please tell me how can i do this? Because we are setting meteor application mongo url in env variable so i am little bit confuse that how my other application will work with different mongo url?

Thanks,
Dhaval

**Comment by osv** [comment]
change env for second app?

**Comment by dhavalrajani92** [comment]
yes

**Comment by osv** [comment]
It depend on how you start your apps, forexample I use `passenger` sometimes and `runit`. Maybe you want to deploy same app on 2 *.meteor.com? If so, meteor.com is not for production usage.

**Comment by dhavalrajani92** [comment]
I am deploying app on Amazon EC2  server. How can i deploy 2 application on same server

**Comment by osv** [comment]
And you use `meteor-up`, right :)? If so, you should better create topic on https://github.com/arunoda/meteor-up I don't know how use single meteor up config for this case

**Comment by dhavalrajani92** [comment]
i am not using MUP. My problem will solved using MUP? have you used MUP??

**Comment by osv** [comment]
Oh, no, no, you don't say details and I'm trying to guess how you deploy your app

**Comment by dhavalrajani92** [comment]
I deployed my app using build command of meteor.

**Comment by raix** [comment]
There might be a way, but it's not a public api:
```js
// Server-side only + depend on the mongo package
var options = {}; // supports oplogUrl
var fooDriver = new MongoInternals.RemoteCollectionDriver(myMongoUrl, options);

var fooBarCollection = new Mongo.Collection('bar', { _driver: fooDriver });
```
*completely untested (better answered on SO)*

**Comment by dhavalrajani92** [comment]
ok thanks @raix i will try it. But it will some extra work to edit my code i need to specify the driver in my all collection. Any other way to do this thing? i research about MUP(Meteor-up) can you suggest is it better way to handel multiple application on same server. Or can you  suggest other generic way to implement multiple application on same server

**Comment by osv** [comment]
can you show how you start apps?

**Comment by stubailo** [comment]
@dhavalrajani92 this depends on how you start your app. People here are having a hard time helping you because you aren't disclosing what command, tool, etc you are using to run your app. Are you just calling `node` from the command line? If so, you can set the MONGO_URL for that single invocation like so:

```
MONGO_URL=xxx node path/to/main.js
```

Anyway, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
