### ISSUE TITLE
Blaze: allow rendering to SVG as root document

### ISSUE THREAD

**Issue by ctzurcanu** [meteor/meteor#4850]
MIME type is different: image/svg+xml

And output should be of the form:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1260" height="555" id="8tKjNXB6TuxBSsf5c">
<script xmlns="http://www.w3.org/2000/svg" type="application/ecmascript" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/file/meteor_scripts.js"/>
...
<g>
<path d="M34,56..."
</g>
</svg>
```

The SVG page should retain reactivity and all other meteor goodness :)

**Comment by stubailo** [comment]
@ctzurcanu What would be the benefits of this? Like, what would you be able to accomplish with this approach that you can't do now? That will help people discuss and evaluate whether this is a good feature.

I'm also not sure what you mean by output - should the Meteor web server return this as the entire content of the page?

What browsers support this kind of SVG, etc?
