### ISSUE TITLE
less not working in html import

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#4852]
Currently less is not supported in html imports like below. This is the only way to conveniently style polymer element/webcomponents as of now when you want to link to a stylesheet rather than using inline-stylesheet directly on the page. (linking .css/.less files doesn't work, a is="custom-style" property is required for custom css properties.

By the way, I noticed less doesn't have a github link on atmosphere.

<link rel="import" href="/my-custom-style.html">

///// my-custom-style.html /////
<style is="custom-style">
@blue: #3896ed;
.blue {
	background: @blue;
}

paper-toolbar {
    --paper-toolbar-color: @blue;
}
</style>

**Comment by mariosant** [comment]
This is quite normal, as LESS compiler is not designed to run this way. If you need to compile LESS in your browser, you should then do the following:

1. Import the stylesheets like that: `<link rel="stylesheet/less" type="text/css" href="styles.less" />` Mind the `stylesheet/less` rel property.
2. **After importing your stylesheets** import the LESS compiler itself. `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.1/less.min.js"></script>`

Not sure if it can work for inline styling, though. IMHO it's bad practice and should be usually avoided.

**Comment by Slava** [comment]
@AndreasGalster what @mariosant is correct. This is not how the compilation works. Meteor templates don't process the embedded tags. The way the compilers work in Meteor, they only match files in the source tree with certain extensions (like LESS) and compile them to CSS or JS.

If Polymer is supposed to compile it for you, file an issue in the Polymer issue tracker. If you want to introduce this automatic behavior in templates, you can define your custom Compiler Plugin similar to the way Jade compiler works: https://github.com/mquandalle/meteor-jade
