### ISSUE TITLE
Mobile App Hot Code push problem

### ISSUE THREAD

**Issue by cachrisman** [meteor/meteor#4855]
I followed the simple todo app with angular tutorial to make an example meteor app.

I then deployed to server with `mupx deploy`

I can use web browser on computer or phone to visit and it works fine (although mobile doesn't look all that nice)

then to build and sign the android app, I do 
````
build ../mobile_build --server=http://[serverhostname.com]
cd ../mobile_build/android
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 unaligned.apk simple-todo
zipalign 4 unaligned.apk production.apk
adb install production.apk
````
and it installs the app on my phone.

the first time I open the app, it shows what I'm expecting(various tasks made my different test user accounts), but only for a second. Then the screen refreshes and I get a pretty blank screen with no tasks, no login buttons

here is the log from my server (I have an apache server running on my frontend reverse proxying requests to my meteor docker container deployed with mupx):
````
"GET /sockjs/info?cb=0409hew943 HTTP/1.1" 200 522 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"GET /sockjs/628/2p0d0pcp/websocket HTTP/1.1" 400 230 "-" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"POST /sockjs/628/e4p1bdhg/xhr HTTP/1.1" 200 492 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"POST /sockjs/628/e4p1bdhg/xhr_send HTTP/1.1" 204 424 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"POST /sockjs/628/e4p1bdhg/xhr HTTP/1.1" 200 899 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"POST /sockjs/628/e4p1bdhg/xhr_send HTTP/1.1" 204 424 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"POST /sockjs/628/e4p1bdhg/xhr HTTP/1.1" 200 895 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"GET /__cordova/manifest.json HTTP/1.1" 200 686 "http://meteor.local/" "Mozilla/5.0 (Linux; Android 5.0.1; HTC One Build/LRX22C.H3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
"GET /__cordova/index.html?tsiei9Dcps2x5ZGfr HTTP/1.1" 200 1244 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; HTC One Build/LRX22C.H3)"
"GET /__cordova/b3bb0b55799a5b6650416ee7f32cf5cdb9ba632b.css?nz5fJEMtRFy8hp49d HTTP/1.1" 200 3425 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; HTC One Build/LRX22C.H3)"
"GET /__cordova/0eb7d2741821fe74d36533aad240e2e61b8122b9.js?sb6L4wFZakusewhRP HTTP/1.1" 200 191234 "-" "Dalvik/2.1.0 (Linux; U; Android 5.0.1; HTC One Build/LRX22C.H3)"
````
I believe the last 4 GETs that begin with the path /__cordova/ are the meteor server updating the codebase(aka hot code push) on the app, but I built and deployed the server with the exact same codebase that I then built the app from...  I don't know why the referrer is `"http://meteor.local/"`

Here is a gif showing what happens: 

![gif of problem happening](http://i.imgur.com/EmIRELn.gif)

Running an iOS simulator of the meteor app I get a similar result.  I ran

`meteor run ios --mobile-server=http://[serverhostname.com]`

and I see these log entries from my server:
````
"GET /sockjs/info?cb=lok1u5vlon HTTP/1.1" 200 522 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"GET /sockjs/359/w81pe2ue/websocket HTTP/1.1" 400 230 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"POST /sockjs/359/psp2ikn6/xhr HTTP/1.1" 200 492 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"OPTIONS /sockjs/359/psp2ikn6/xhr_send HTTP/1.1" 204 532 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"POST /sockjs/359/psp2ikn6/xhr_send HTTP/1.1" 204 424 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"POST /sockjs/359/psp2ikn6/xhr HTTP/1.1" 200 868 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"POST /sockjs/359/psp2ikn6/xhr_send HTTP/1.1" 204 424 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"POST /sockjs/359/psp2ikn6/xhr HTTP/1.1" 200 973 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"GET /__cordova/manifest.json HTTP/1.1" 200 686 "http://meteor.local/" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"GET /__cordova/b3bb0b55799a5b6650416ee7f32cf5cdb9ba632b.css?JY2pqKYXqgJeKZQat HTTP/1.1" 200 3425 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"GET /__cordova/index.html?twCqYMZ53M6ers5hj HTTP/1.1" 200 1244 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
"GET /__cordova/0eb7d2741821fe74d36533aad240e2e61b8122b9.js?etYR55cRYyWEdfthZ HTTP/1.1" 200 191227 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2055055008)"
````
Unlike on my android phone, in the simulator I don't see any of the tasks I should see; I just see the meteor loading screen for a while (during which I see the hot code push happening) then I'm shown the app with no tasks.

I'm running 

meteor 1.1.0.2
mupx 1.5.1

how can I fix this?

**Comment by martijnwalraven** [comment]
It sounds the problem is the server has not been configured correctly.

A mobile client decides where to connect to based on settings in the generated `index.html`. Using `meteor build` with the` --server` option sets the `ROOT_URL` and `DDP_DEFAULT_CONNECTION_URL` to the passed in connection URL. The app working for a second suggests this initial configuration is correct in your case.

But because subsequent updates delivered through Hot Code Push replace the initially bundled `index.html` with a freshly generated one, the server should also be configured with the right connection URL. Otherwise, the client may not be able to connect, or perhaps connect to the wrong server, after a Hot Code Push. This is likely what is happening in the situation you describe.

Using meteor deploy takes care of setting these values automatically, so there is no need to specify anything in that case. But when deploying on your own server, you have to make sure to set at least the `ROOT_URL` environment variable (`DDP_DEFAULT_CONNECTION_URL` defaults to the same value). For Meteor Up, you can configure this in `mup.json`.

`meteor.local` is what we use to serve files cached on the device. We do this to work around issues with hashbang routing with file protocol URLs (which is what Cordova uses by default).

**Comment by cachrisman** [comment]
excellent!  that fixed the problem...  for the sake of other people who might run into the same problem, when using mup (or mupx), in your mup.json file, you need to set the `"env"` key with the hostname and port of your server **as clients will see it**.  I had set it as the server saw it (in a docker container behind an apache reverse proxy).  For example:
````
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://serverhostname.com"
  },
````

Thanks for the accurate and insightful help!

**Comment by salilsethi** [comment]
This is helpful. The one question, which I am struggling with is why does the server refresh the client if the code base is exactly the same. Is there a way to avoid that. I have an iOS app that flashes because the server pushes update on start even when the code is exactly the same. I am using mupx to deploy to server and building the xcodeproj using meteor build with --server flag. Any help would be appreciated.

**Comment by martijnwalraven** [comment]
The server should not refresh the client if there have been no changes to the code. I've heard more reports of this happening though, so it is something I plan to look into as part of the hot code push rewrite for Cordova that I'm currently working on.

**Comment by guilhermedecampo** [comment]
Hey @salilsethi and @martijnwalraven the hot code push happens because the app has been deployed to the server via mupx with the version `X` and the build process make it with the version `Y`. Right?

@martijnwalraven where can we see your progress in the rewrite? 
Really curious! :stuck_out_tongue_closed_eyes:

**Comment by sasikanth513** [comment]
hey @guilhermedecampo me and @salilsethi  working on same project,

we tried your use case too,we did deploy using same  build, still when we launch the app in iphone/ipod we still see hotcode push happening and we can see logs of downloading files in xcode

**Comment by guilhermedecampo** [comment]
Indeed @salilsethi @sasikanth513 @martijnwalraven.

I don't see any condition to test if the actual version of the app is the same as the server in the [meteor_cordova_loader.js](https://github.com/meteor/meteor/blob/devel/tools/cordova/client/meteor_cordova_loader.js)
