### ISSUE TITLE
Accounts.ui.config bug

### ISSUE THREAD

**Issue by SoilChang** [meteor/meteor#4856]
the four options in the configuration 

'USERNAME_AND_EMAIL', 'USERNAME_AND_OPTIONAL_EMAIL', 'USERNAME_ONLY', or 'EMAIL_ONLY' (default).

"USERNAME_AND_EMAIL" and "USERNAME_AND_OPTIONAL_EMAIL seem to be the same". 

I tried to use "USERNAME_AND_EMAIL" and I still can't get the users to sign in with BOTH username and email.

**Comment by stubailo** [comment]
I tried creating a new app, and everything seemed to work for me. Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by SoilChang** [comment]
i installed account-ui package "accounts-ui@1.1.5"
I use {{>loginButtons}} to call the template. 

in client folder(as instructed by documentation), i have 

Accounts.ui.config({
  requestPermissions: {
    facebook: ['user_likes']
  },
  passwordSignupFields: 'USERNAME_AND_OPTIONAL_EMAIL',
});

I tried 3 options after that:
1.USERNAME_AND_OPTIONAL_EMAIL

2.USERNAME_AND_EMAIL

3.USERNAME_ONLY

outcome:

1. the login button offers two fields: [___] username or email,  [____] password

2.the login button offers two fields: [___] username or email,  [____] password

3.the login button offers two fields: [___] username ,  [____] password

So the problem is, when I use USERNAME_AND_EMAIL, i don't get 3 fields like 
[___] username,  [____] email,  [____] password
is it supposed to be like this? if it is, what's the differences between USERNAME_AND_OPTIONAL_EMAIL and USERNAME_AND_EMAIL?

**Comment by stubailo** [comment]
@SoilChang I think you're mixing up "login" and "sign up". People only need to put in username and email when they make an account, not when they log in.

**Comment by SoilChang** [comment]
Ohhhhhh ya. really sorry. now i see it is working. thank you very much for the explanation.
