### ISSUE TITLE
Make Websocket messages 30% smaller by using UBJSON Instead of JSON

### ISSUE THREAD

**Issue by capensisma** [meteor/meteor#4859]
Hi
Can you make use of UBJSON isntead of JSON
because Universal Binary JSON specification carries these tenants of simplicity forward, it is able to take advantage of optimized binary data structures that are (on average) 30% smaller than compacted JSON and specified for ultimate read performance; bringing simplicity, size and performance all together into a single specification that is 100% compatible with JSON.

http://ubjson.org/#why

Thanks

**Comment by Tim-W** [comment]
+1

**Comment by stubailo** [comment]
Hey, @capensisma, do you happen to have any benchmarks of UBJSON vs. compressed websockets with standard JSON? It's hard to evaluate this decision in the absence of any concrete data of how UBJSON would improve Meteor specifically.

The page you linked to is a generic page about JSON, but it's possible that some or all of the advantages are not applicable for Meteor's communications. For example, I think we use gzipped websockets, but it's still easy to debug in Chrome's websocket inspector. So I'm not sure what's up with that part of their argument.

**Comment by capensisma** [comment]
Yes i agree but the same page they talked about your way of doing it JSON+Gzip
that's why i linked it. 

1) Raw JSON is slow to transfer compared to UBJSON
2) You have to uncompress it then work with which take more time+cpu


Here they are explaining it better than me :
```
Why not JSON+gzip?

On the surface simply gzipping your compacted JSON may seem like a valid (and smaller) alternative to using the Universal Binary JSON specification, but there are two significant costs associated with this approach that you should be aware of:

At least a 50% performance overhead for processing the data.
Lack of data clarity and inability to inspect it directly.
While gzipping your JSON will give you great compression, about 75% on average, the overhead required to read/write the data becomes significantly higher.

Additionally, because the binary data is now in a compressed format you can no longer open it directly in an editor and scan the human-readable portions of it easily; which can be important during debugging, testing or data verification and recovery.

Utilizing the Universal Binary JSON format will typically provide a 30% reduction in size and store your data in an optimized format offering you much higher performance while still allowing you to open the file directly and read through it.
```

You can try the NodeJS Library here : https://github.com/Sannis/node-ubjson

I know UBJSON from a Peer2Peer project i used to work on.
This is used in many languages where processing data is a priority.

http://ubjson.org/libraries/

I want this project to be the most faster than anything else on the market that's why I'm proposing this.

Thanks

**Comment by stubailo** [comment]
@capensisma I understand - I read the page that you linked.

But I don't see any evidence that the CPU load of decompressing JSON from the websocket connection is actually a bottleneck in Meteor compared to other things that we could be improving. I also personally have no trouble debugging gzipped websocket data in Chrome - maybe you have had a different experience? If so, I'd love to head about it.

Do you have any personal data or feedback that isn't from the page on the UBJSON website?

**Comment by capensisma** [comment]
May be it's not worth since it's slower than JSON parsing in browser according to 
Ycombinator Forum :
https://news.ycombinator.com/item?id=4981376

Better stick with JSON :)
Changed my mind, let's keep it like this.
Is there any Benchmark tests of Meteor Performance ?

**Comment by stubailo** [comment]
There currently aren't any benchmarks, but I'd love if somebody built some!

Going to close this issue then.

**Comment by capensisma** [comment]
Okay, Thanks i saw there is no benchmarks test only for the Meteor Cluster project
but thank you anyway
