### ISSUE TITLE
[bug] Build servers always close connection before successfully publishing my package.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4860]
The Meteor build servers consistently timeout when I try to publish `rocket:module`. It never works. The error is always

```
Connection closed by remote host
```

**Comment by trusktr** [comment]
Aha, seems I've gotten lucky one time, just now:

```
Please log in with your Meteor developer account. If you don't have one, you can quickly create one at www.meteor.com.
Username: trusktr
Password:
Published rocket:module@0.5.2. <------ LUCKY
Connection to 199.19.86.153 closed by remote host.
```

**Comment by trusktr** [comment]
Cool, just got lucky on the Linux build. I guess today is lucky.

**Comment by Slava** [comment]
Hope it is working for you now!

It looks like it was some outrage. I am not sure, but the AWS outrage happened around that time and a lot of software managing these VMs run on AWS. So it is not unlikely that these events are related.

Closing this issue as build farms are working right now.
