### ISSUE TITLE
 Meteor.userId() throws an error in validateLoginAttempt/onLogin/onLoginFailure callbacks

### ISSUE THREAD

**Issue by brettle** [meteor/meteor#4862]
`Meteor.userId()` is throwing an error when called within `Accounts.validateLoginAttempt`/`Accounts.onLogin`/`Accounts.onLoginFailure` callbacks. This is preventing me from determining which (if any) already logged in user made the login attempt.

Here's a reproduction recipe using [this github repo](https://github.com/brettle/Meteor.userId-throws-error-in-validateLoginAttempt-callback):

```sh
[brettle@localhost git]$ git clone git@github.com:brettle/Meteor.userId-throws-error-in-validateLoginAttempt-callback.git login-callback-bug
Cloning into 'login-callback-bug'...
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 0), reused 13 (delta 0), pack-reused 0
Receiving objects: 100% (13/13), done.
Checking connectivity... done.
[brettle@localhost git]$ cd login-callback-bug/
[brettle@localhost login-callback-bug]$ meteor
[[[[[ ~/git/login-callback-bug ]]]]]          

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

Visit http://localhost:3000/ and click the "Login with correct password" button. You'll get this on the server console:
```sh
I20150801-21:56:11.520(-7)? In validateLoginAttempt callback:
I20150801-21:56:11.521(-7)?   Meteor.userId() throws: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20150801-21:56:11.521(-7)?   this.userId: undefined
I20150801-21:56:11.522(-7)? In onLogin callback:
I20150801-21:56:11.522(-7)?   Meteor.userId() throws: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20150801-21:56:11.522(-7)?   this.userId: undefined
```
Click the "Login with incorrect password" button and you'll get this on the server console:

```sh
I20150801-21:56:15.091(-7)? In validateLoginAttempt callback:
I20150801-21:56:15.091(-7)?   Meteor.userId() throws: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20150801-21:56:15.091(-7)?   this.userId: undefined
I20150801-21:56:15.091(-7)? In onLoginFailure callback:
I20150801-21:56:15.091(-7)?   Meteor.userId() throws: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20150801-21:56:15.091(-7)?   this.userId: undefined
```
I suspect this is related to these API functions using [Hooks](https://github.com/meteor/meteor/blob/devel/packages/callback-hook/hook.js#L12) which binds the callbacks "with `Meteor.bindEnvironment`, so they will be called with the Meteor environment of the calling code that registered the callback."

**Comment by brettle** [comment]
It is, in fact, the Meteor.bindEnvironment() wrapping that is causing the problem. I've just created PR #4867 which fixes it. I don't see a good reason for using bindEnvironment here. Maybe @awwx just used because it was part of the Hook code that he extracted from livedata when he implemented login hooks 18 months ago?

**Comment by stubailo** [comment]
Thanks for the PR!

**Comment by brettle** [comment]
Thanks for the fast review and merge!

**Comment by brettle** [comment]
The [brettle:workaround-issue-4862](https://atmospherejs.com/brettle/workaround-issue-4862) package provides a workaround for Meteor releases where this is not fixed.
