### ISSUE TITLE
Error on Hot Code Push using iOS Simulator

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor/meteor#4864]
Hello:

I'm getting several errors like this in my terminal after any code change while running ```meteor run ios```:

```
E20150802-21:35:25.389(-4) (webapp.js:440) Error serving static file Error: Forbidden
```
It happens any time I make code changes and the app running in the simulator does not update. I'm running Meteor v1.1.0.2

**Comment by martijnwalraven** [comment]
Do you get those same errors when accessing the app though a web browser?

Any chance you've changed file permissions or are using symlinks?

**Comment by nicholasalanbrown** [comment]
I don't get the errors through the browser as long as Xcode isn't open.

I haven't made any recent changes to file permissions or symlinks, at least not intentionally.

**Comment by martijnwalraven** [comment]
Sorry, I have no real idea what else could cause this, but have you tried deleting `.meteor/local/cordova-build` to start with a clean slate?

**Comment by nicholasalanbrown** [comment]
Just tried that, it didn't work. Are there any log files I can look at to see what file(s) it might be having an issue with?

**Comment by martijnwalraven** [comment]
I don't believe so, the logging statement unfortunately does not print the path of the file.

Is there any way you can create a minimal project that allows me to reproduce this issue?

**Comment by nicholasalanbrown** [comment]
I think I'm going to just create a new project and pull in one piece at a time, starting with the packages and server-side code. It seems to work with an empty Meteor project. Thanks for your help.

**Comment by martijnwalraven** [comment]
No problem. Let me know if that fixes it, or if you find out what the issue is.

**Comment by nicholasalanbrown** [comment]
That seemed to work - I'm not sure what the original issue was but it's actually nice to have a clean project for creating the mobile version of this app...

**Comment by nicholasalanbrown** [comment]
I encountered the problem again and this time diagnosed it - it doesn't seem to deal well the mp3 files I have in a ```/public``` directory in my app. I haven't yet figured out where I should placing them, since I do use them in the app and they don't play/work at all in the app, though they do on the web. Any ideas?
