### ISSUE TITLE
Properly document how to use Meteor with git and other version control

### ISSUE THREAD

**Issue by joshterrill** [meteor/meteor#4866]
This is more of a suggestion but I was wondering if it would be possible/if anyone else thinks it would be useful, to create a meteor ```package.json```. It would hold all of the names of packages the app requires, settings, start scripts, etc. When you install a package you could do ```meteor add <package> --save```, similar to npm.

**Comment by martijnwalraven** [comment]
What use do you have in mind for this? Meteor already stores similar information in the `packages` and `versions` files in the `.meteor` directory of your project.

**Comment by joshuaterrill** [comment]
The ```.meteor``` directory really never gets committed on projects. This would be for use in other people's public and open source meteor projects. I could download your files and the ```package.json``` and then type in something like ```meteor install``` and it queries the file to download the dependencies and create the app.

**Comment by martijnwalraven** [comment]
Why wouldn't you commit `.meteor`? The recommendation is not to commit `.meteor/local` (which is what the default `.gitignore` contains), but the `packages` and `versions` files are needed for repeatable builds and should definitely be checked in. The behavior you describe is what `meteor` does by default: if there is no `.meteor/local` directory it will download and build the specified packages.

**Comment by stubailo** [comment]
Yeah... I'm not sure where we should put documentation for what you are supposed to commit. Maybe we should make the directory called something other than `.meteor` - that name makes it seem like those are hidden files that you shouldn't save/look at...

**Comment by zimme** [comment]
How about a "new" documentation section called "Meteor and version control" or something like that.

Where best practices around version control and Meteor are documented?

**Comment by stubailo** [comment]
Marking this as a docs feature request.

**Comment by abernix** [comment]
Closing this doc issue as it's due to be covered in the [Meteor Guide](http://guide.meteor.com) already in meteor/guide#312 which has "Using version control with Meteor" as it's number one bullet point.  Thanks for the suggestion @joshterrill!

**Comment by hangtwenty** [comment]
This remains confusing
