### ISSUE TITLE
Encountering a strange issue when adding a cordova plugin from a tarball url

### ISSUE THREAD

**Issue by idoivri** [meteor/meteor#4868]
Hola!

I've written a *very* simplistic app that should, in the future, do GPS location polling on android devices.
The app's code is available @ https://github.com/idoivri/demo-gps

To achieve GPS polling, I used a cordova plugin written by louisbl available [here](https://github.com/louisbl/cordova-plugin-locationservices)

I'm adding it to the project using its tarball - 
`meteor add cordova:cordova-plugin-locationservices@https://github.com/louisbl/cordova-plugin-locationservices/tarball/48d531af501b1706caed807b1646e3b239819a4d`

And then, when I run `meteor run android`, I get the following:

`
Error while running for mobile platforms: Error running
/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-locationservices':Error: Uh oh!
ENOENT, no such file or directory '/Users/idoivri/Sites/projects/demo-gps/.meteor/local/cordova-build/platforms/android/local.properties'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at Object.createEditor
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
at Object.module.exports.getProjectSdkDir
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
at module.exports.framework.install
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
at Object.ActionStack.process
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
ENOENT, no such file or directory '/Users/idoivri/Sites/projects/demo-gps/.meteor/local/cordova-build/platforms/android/local.properties'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at Object.createEditor
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
at Object.module.exports.getProjectSdkDir
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
at module.exports.framework.install
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
at Object.ActionStack.process
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/idoivri/.meteor/packages/meteor-tool/.1.1.3.sdjiur++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)

Installing "cordova-plugin-locationservices" for android
`

I've tried adding / removing the plugin in all sorts of ways, to no avail. Also tried removing the directory /Users/idoivri/Sites/projects/demo-gps/.meteor/local/cordova-build/platforms/android/ - didn't help...

Help me?

**Comment by idoivri** [comment]
@Urigo here's my issue. I also sent an e-mail. Cheers!

**Comment by martijnwalraven** [comment]
I'm not sure what could be going on here. Have you tried deleting the entire `cordova-build` directory?

I won't have time to look into this right now, as I'm working on some improvements to the Cordova integration that I'm hoping to get into Meteor 1.2. Among those is an update to the latest version of Cordova and some changes to our plugin handling, which may help solve your problem. Please try again when that version is released and let me know if the problem persists.

**Comment by idoivri** [comment]
Tried it; didn't work :( 
Any rough timeline estimations on Meteor 1.2?

**Comment by martijnwalraven** [comment]
Meteor 1.2 will ship later this Summer.

**Comment by idoivri** [comment]
Cheers, appreciate you letting me know so quickly.

**Comment by martijnwalraven** [comment]
Could you try this again with the Meteor 1.2 RC (--release METEOR@1.2-rc.7)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue. If not, let me know, and I'll look into it.

**Comment by idoivri** [comment]
Yes! I'll try later on today.

I should update meteor by running

meteor run --release METEOR@1.2-rc.7

right?

**Comment by martijnwalraven** [comment]
No, you should run `meteor update --release METEOR@1.2-rc.7`.

**Comment by idoivri** [comment]
1) Sorry for that, meant update.

2) YES! updated, and the app now builds correctly. Awesome stuff!

Many thanks, and even more thanks for not forgetting this...

**Comment by martijnwalraven** [comment]
Good to hear!

**Comment by Urigo** [comment]
:+1:
