### ISSUE TITLE
METEOR_SETTINGS env not interpreted during meteor run

### ISSUE THREAD

**Issue by ssmith15** [meteor/meteor#4869]
I actually wasn't running into this issue before but it started happening today. 

In the (near) past I have done

    export METEOR_SETTINGS=$(cat settings.json)
    //or
    METEOR_SETTINGS=`cat settings.json`

and then done

    meteor run --settings $METEOR_SETTINGS

The reason I'm testing this is because I'm going to be using these settings for a Docker build, in which you have to pass in the environment variables when the container is run. Currently, when I pass $METEOR_SETTINGS in a couple of things happen.

if I do meteor run --settings "$METEOR_SETTINGS"
    Error: ENAMETOOLONG

if I do meteor run --settings $METEOR_SETTINGS
    "Please add the "X":platform to your project first. 

if I do meteor run --settings settings.json
    everything is fine

This behavior wasn't actually happening before and I was able to run the application by using "$METEOR_SETTINGS" in quotes. How does this work exactly?

**Comment by Slava** [comment]
This is not how you would use the `METEOR_SETTINGS` env variable. See more in the docs: http://docs.meteor.com/#/full/meteor_settings

1. You can use the `--settings` option to give a **path** to the JSON **file** that will be parsed and given to the process, or ...
2. You can set the `METEOR_SETTINGS` env variable to the JSON **string** that will be parsed and given to the process.
