### ISSUE TITLE
Meteor.settings is not an empty object on the client

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4870]
If you run `meteor` without `--settings`, then `Meteor.settings` is undefined. This isnt what the docs say.

**Comment by Slava** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Couldn't reproduce with 1.1, here is what I put in my server code:

```
Meteor.startup(function () {
  console.log(Meteor.settings);
});
```

It outputed `{}`.

**Comment by ccorcos** [comment]
Try doing that without `Meteor.startup` and it wont be there.
