### ISSUE TITLE
Support drag and drop events

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#4874]
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop

This would be great. Currently we have to depend on [`raix:dropped-ui-event`](https://atmospherejs.com/raix/ui-dropped-event).

**Comment by rclai** [comment]
Nevermind, found [answer](http://stackoverflow.com/a/19223442/620010).

**Comment by rfox90** [comment]
There's always https://atmospherejs.com/ahref/dragula :)

**Comment by rclai** [comment]
My use case was in the context of file uploads, but thanks.

**Comment by Slava** [comment]
I think we can also mark it as a duplicate of https://github.com/meteor/meteor/issues/1200. Generally Blaze uses jQuery events system, so if plugins register jQuery events, they generally work.
