### ISSUE TITLE
[Cordova] add var for when a hot code push update is being downloaded

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4876]
**_2 Upvotes**_ It would also be great to have a `Meteor.isUpdateAvailable` or `Meteor.isDownloadingUpdate` so that when the app is opened on `Meteor.startup`, I can decide whether to hold the launch screen until the update finishes downloading and the page refreshes. Otherwise I get the bad user experience of the app page refreshing and the screen going blank a second or two after they open the app. 

Related to #4858 @martijnwalraven

**Comment by martijnwalraven** [comment]
Thanks for the feature request. I'm aware the current behavior isn't ideal for production apps, so I think it is reasonable to rethink this. Other UX options are to delay updating until the next time a user opens the app, or to tell users an update is available before refreshing. Ideally, we'd come up with both good defaults (which will likely differ between development and production) and a way for developers to customize the updating behavior.

**Comment by lorensr** [comment]
The example I mentioned was the case in which the update is delayed until the next time the user opens the app. (Which I'm using `mdg:reload-on-resume` to do. And while it does have a `Reload.isWaitingForResume()` var, it does not tell you when the new code is in the process of downloading.) Or the case in which it's the first open after installing app.

**Comment by martijnwalraven** [comment]
Now I see what you mean. Ideally, downloading a new version should be done in the background I think, and not force an immediate reload. That way, there is no further delay when you decide to reload or open the app after an update.

**Comment by lorensr** [comment]
Oh yeah, I forgot I submitted this:

https://github.com/meteor/mobile-packages/issues/42

- Don't know whether JS is stopped when the app is sent to background (in which case maybe the reload could be done in Objective C/Java? Don't know how native background runtime works.) 
- Need to make sure can recover from app being force-quit during an update download.
- Doesn't take care of the first run after installing the app.

I think best defaults are:

In development: reload as soon as updated code is downloaded.
In production: reload in background

Also think it's important to be able to have API for:

```
isDownloadingUpdate
isWaitingForResume (in which case you can location.reload() to update)
```

Ideally also an estimate on `downloadMsRemaining` based on size of files and connection speed, so that eg dev can make the decision in the original example – if Wifi/4g, I want to keep the launch screen up for a couple seconds until reload is done, but on 3g, I don't want to, because it could take a minute to download.

**Comment by martijnwalraven** [comment]
Oh, by downloading in the background I meant not blocking the main thread, but the app still being in the foreground. But it will require more to be done in native code.

**Comment by lorensr** [comment]
I see. Even if you're downloading in the background, completing the update still requires a visible refresh of the page. I think the refresh should happen when the app is not in the foreground by default in production.

**Comment by martijnwalraven** [comment]
Yes, that's still the idea. But by separating the download and the refresh, you should no longer experience a delay when you reopen the app. (That also takes away the need for something like `downloadRemaining` I think.)

**Comment by lorensr** [comment]
`isDownloadingUpdate` and `downloadMsRemaining` are still helpful for the first time opening the app after installation. The app store code version, at least in the case of Apple, is going to be at least one week old and often older. I often don't want to wait until the second time the app is opened for it to be updated, because eg I fixed an onboarding bug or changed how onboarding works. So on the first open, I want to be able to do:

```coffeescript
launchScreen.hold()

Meteor.startup ->
  if isDownloadingUpdate
    if downloadMsRemaining < 3000
      Tracker.autorun ->
        if isWaitingForResume()
          location.reload()
    else
      # either prompt them later to refresh or show a loading bar with seconds remaining
  else
    launchScreen.release()
```

**Comment by lorensr** [comment]
`downloadMsRemaining` might be difficult to implement, in which case `isDownloadingUpdate` is still great just by itself – I can then check device's connection (wifi, 4g, 3g) to get a general estimate on time myself.

**Comment by cdcv** [comment]
+1

**Comment by ppryde** [comment]
+1

**Comment by lorensr** [comment]
@martijnwalraven OMG THANK YOU! Saw the Meteor Night talk, very happy about non-blocking diff downloads and WKWebView 👌

Wanted to check whether my last two comments on this issue made sense?

**Comment by martijnwalraven** [comment]
Thanks! This is one of the issues I know is still open and I need to take a look at.

I think something like `WebAppCordova.onCheckedForUpdates()` probably makes the most sense, or maybe something more general like `WebAppCordova.onStatusChange()` or `WebAppCordova.status()` (reactive).

WebAppCordova.checkForUpdates()` is what actually initiates the check. It is invoked when receiving an autoupdate notification, but could also be invoked manually. That might speed up the first launch experience because there is no need to wait for the DDP connection to be established.

**Comment by lorensr** [comment]
I see, so if the four possible states were `'checking' | 'downloading-update' | 'waiting-for-resume' | 'up-to-date'`, then it would be this:

```coffeescript
WebAppCordova.checkForUpdates()
# now WebAppCordova.status() == 'checking'

unless localStorage.get 'hasRunBefore'
  launchScreen.hold()
  localStorage.set 'hasRunBefore', true

  Tracker.autorun (c) ->
    switch WebAppCordova.status()
      when 'downloading-update'
        if slowConnection
          Router.go 'appUpdating'
          launchScreen.release()
      when 'waiting-for-resume'
        location.reload()
      when 'up-to-date'
        launchScreen.release()
        c.stop()
```

**Comment by martijnwalraven** [comment]
Unfortunately, this hasn't made it into 1.3. Doing this right required more effort than I had expected, and I didn't want to expose a half baked public API at this point.

**Comment by lorensr** [comment]
No worries, very happy about the changes you've already finished – thank you! Excited to move all my static assets from the cdn to the app bundle, now that only changed files are pushed, and glad the downloading doesn't block main thread and continues in background!

Might be worth directly including the `window.location.reload() -> window.location.replace(window.location.href)` replacement recommendation in History.md, since I imagine it's commonly used, and some people won't click through to read the whole https://github.com/meteor/cordova-plugin-meteor-webapp readme.

**Comment by martijnwalraven** [comment]
Good to hear you're happy with the changes! 

The use of `windows.location.replace` is not really a recommendation, but something we actually changed in the reloading code: https://github.com/meteor/meteor/commit/5e9090c3ee86c21541a5bc8e4ec9bcde81251977. You're right though, it may make sense to include that in `History.md` so people are aware of it.

**Comment by lorensr** [comment]
https://github.com/meteor/mobile-packages/pull/112

**Comment by jamielob** [comment]
This API will be great for production apps.  +1

**Comment by lorensr** [comment]
Related: #5527 will make the download we're waiting for happen faster.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BCordova%5D%20add%20var%20for%20when%20a%20hot%20code%20push%20update%20is%20being%20downloaded&body=Migrated%20from:%20meteor/meteor%234876) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
