### ISSUE TITLE
Completely broken after Windows 10 upgrade

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#4877]
Sorry, not even sure how to break this one out into multiple issues.

Everything worked fine until Friday when I did a Windows 10 upgrade. My system more or less works except for Meteor. My app, which again worked fine on Friday, now demonstrates the following behaviors. These persist after uninstalling and reinstalling Meteor, and after a reboot:

## The system cannot find the path specified.

I get this with `meteor update`:

C:\Users\nolan\Projects\TurnNet>meteor update
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

I wish I knew which specified path it couldn't find.

## Couldn't run tasklist.exe: {"killed":false,"code":1,"signal":null}

=> Started proxy.

C:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x8
6_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: Couldn't run tasklist.exe: {"killed":false,"code":1,"signal":null}
    at Object.Future.wait (C:\Users\nolan\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398
:15)
    at findMongoPids (C:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\
1.1.3\mt-os.windows.x86_32\tools\run-mongo.js:120:16)
    at findMongoAndKillItDead (C:\Users\nolan\AppData\Local\.meteor\packages\met
eor-tool\1.1.3\mt-os.windows.x86_32\tools\run-mongo.js:236:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\nolan\AppData\Local\.m
eteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-mongo.js:360:7)
    at launchMongo (C:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.
1.3\mt-os.windows.x86_32\tools\run-mongo.js:612:7)
    at [object Object]._.extend._startOrRestart (C:\Users\nolan\AppData\Local\.m
eteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-mongo.js:712:19)

    at [object Object]._.extend.start (C:\Users\nolan\AppData\Local\.meteor\pack
ages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-mongo.js:670:10)
    at C:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\run-all.js:199:26
    - - - - -
    at C:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\run-mongo.js:73:24
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

The former issue goes away when I generate a new app, leading me to believe that perhaps it is a package issue. Still though, it would be nice to have more feedback as to what failed to run. The latter, unfortunately, persists. A brand new app crashes with the previous error.

I can run tasklist.exe from the console just fine, so I know that at least works.

Thanks.

**Comment by ndarilek** [comment]
The first issue looks like it is caused by having a project on a different Meteor version than the one that was installed, or some sort of version inconsistency. After `meteor update` successfully switched the project to 1.1.0.3, the "system could not find..." errors vanished at least. Might be worth investigating that and making those particular error cases a bit more bulletproof.

Sorry I don't have the exact circumstances of the bug, I just need to get these apps working locally so I can get back to work. :( I think that the app was on Meteor 1.1.0.2 whereas the installer downloaded 1.1.0.3, and I assume the command line tool tried to access 1.1.0.2 still.

**Comment by avital** [comment]
I just installed Meteor on a fresh Windows 10 machine and it seems to be working so this doesn't seem like a general problem with Meteor on Windows 10.

Meteor downloads releases that it has missing, so at the very least there are additional factors other than the fact that the installer installed 1.1.0.3 and your app was on 1.1.0.2.

We'd really need some more information to figure this out. If I clone your app maybe I can try running it on one of our Windows 10 machines?

**Comment by ndarilek** [comment]
I'm absolutely at a loss as to what's going on. My second issue at least
is a dupe of #4128, which I have a fix for in #4879. It all makes me
hate Windows that much more.

**Comment by avital** [comment]
If you apply your tasklist patch and just run `meteor` in your app directory, what do you get? (you shouldn't need to run `meteor update` to run your app -- it should download whatever release is missing)

**Comment by ndarilek** [comment]
Think I got it figured out. See my comments on #4128 and #4879 for the explanation. Putting this stuff everywhere to improve SEO for these issues in case anyone else hits this problem. :)

Closing this one since its subissues were resolved elsewhere. Thanks for the effort you put into attempting to duplicate, I unfortunately don't have hardware capacity for spare test installs. :)
