### ISSUE TITLE
Spiderable.userAgentRegExps always false due to start of string matching

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#4880]
Can someone confirm I'm not losing it?

https://github.com/meteor/meteor/blob/devel/packages/spiderable/spiderable_server.js#L15-L20
https://github.com/meteor/meteor/blob/devel/packages/spiderable/spiderable_server.js#L63-L65

We're attempting to match the user agent using: `^` (start of string)

```
Spiderable.userAgentRegExps = [
  /^facebookexternalhit/i,
  /^linkedinbot/i,
  /^twitterbot/i,
  /^slackbot-linkexpanding/i
];
```

should be:

```
Spiderable.userAgentRegExps = [
  /facebookexternalhit/i,
  /linkedinbot/i,
  /twitterbot/i,
  /slackbot-linkexpanding/i
];
```

we could even add a few more agents:

```
Spiderable.userAgentRegExps = [
  /facebookExternalHit/i,
  /linkedinBot/i,
  /twitterBot/i,
  /googleBot/i,
  /bingBot/i,
  /yandex/i,
  /google-structured-data-testing-tool/i,
  /yahoo/i,
  /MJ12Bot/i,
  /tweetmemeBot/i,
  /baiduSpider/i,
  /Mail\.RU_Bot/i,
  /ahrefsBot/i,
  /SiteLockSpider/i
];
```

For instance googlebots agent is: `'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'`

Cheers

**Comment by stubailo** [comment]
@RobertLowe we've been using those regexps for at least a year: https://github.com/meteor/meteor/commit/3ce808aae5003f6cf0e1f1c78765a090821807a3

I wonder if we test anywhere that it works.

**Comment by hwillson** [comment]
Hi all - deprecating the `spiderable` package is currently being considered. The reasons for this include:

- Google has deprecated the [AJAX crawling specification](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) that the `spiderable` package is based on;
- Search engine crawlers (like Google's) have gotten much better at dealing with javascript/AJAX based applications, without the need for any special handling;
- There are now several better options for SEO goodness, like pre-rendering services (e.g. [Prerender.io](https://prerender.io/) - recommended in the Guide's [Enabling SEO](https://guide.meteor.com/deployment.html#seo) section and [supported out of the box with Galaxy](http://galaxy-guide.meteor.com/seo.html)), server-side rendering techniques, etc.

As such, I'll close this issue off for now. If anyone feels like this is a bad decision and can justify why `spiderable` should not be deprecated, please post back with your reasons. Thanks for opening this issue originally!
