### ISSUE TITLE
Cannot run devel

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4882]
I wanted to make some improvements to docs.meteor.com, but I can't even run the app:

```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
   
   While selecting package versions:
   error: unknown package: isobuild:minifier-plugin
   Required by: standard-minifiers 0.0.1-plugins.0
   
=> Your application has errors. Waiting for file change.
```

The `.meteor/packages` file had `standard-minifier` twice which it didn't like (resulted in error), so I removed one of them. `packages` is now:

```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
standard-minifiers
jquery
underscore
showdown
spiderable
appcache
reload-safetybelt
simple:markdown-templating
simple:highlight.js
less
```

**Comment by stubailo** [comment]
@ffxsam we're introducing some new packages in Meteor 1.2. Does it run for you if you run Meteor from a checkout?

Alternatively, you can make your branch off of `master`, which will _definitely_ run with your installed Meteor.

**Comment by Slava** [comment]
I think @ffxsam just ran the wrong Meteor, as the devel version explicitly implements the package `isobuild:minifier-plugin`. I also just ran the tests for minifiers that pass. Unless there are repro steps, the issue should be closed.

**Comment by ffxsam** [comment]
If I want to contribute, what's the process? Which branch should I branch off of? How should I name my branch? Should I squash commits before I push?

**Comment by Slava** [comment]
@ffxsam to contribute docs change, you can checkout the `master` branch, make changes to the docs text, test it by running the `docs` app. Submit a PR.

**Comment by ffxsam** [comment]
Thanks!
