### ISSUE TITLE
Handlebars version update

### ISSUE THREAD

**Issue by sdossick** [meteor/meteor#489]
It's a drop hard to tell what version of Handlebars the current templating system is based on.  More recent versions of Handlebars support nice-to-have things like an @index context-dependent accessor so you can tag the index number of elements of an array you're {{each}}-ing through.

An update to the latest RC of handlebars would be great, as would some docs on how to Spark-ify our own versions of handlebars or other templating systems.

**Comment by MiroRadenovic** [comment]
still no @index support!
 +1

**Comment by mitar** [comment]
It is coming in #3560.

**Comment by MastaBaba** [comment]
+1

**Comment by J-Katzen** [comment]
+1

**Comment by laosb** [comment]
Could I say that you are mentioning the organization **index** on GitHub by mistake? Please use ``@index`` to prevent from mentioning an organization.

**Comment by davidmfry** [comment]
Is there an ETA when the @index might be supported?

**Comment by kkm** [comment]
harmless index for handlebars took for 3 years.
