### ISSUE TITLE
Tracker.forEach - run a function over an iterable, in separate flush cycles

### ISSUE THREAD

**Issue by deanius** [meteor/meteor#4891]
Use case: Cause a ReactiveVar to take on a series of values
Issue: calling `reactiveVar.set` must be done in separate flush cycles or dependent computations will be invalidated fewer times than we think
Proposal: `Tracker.forEach(iterable, fn)`, which runs `fn` in separate flush cycles
Naming: `Tracker.forEach(iterable, fn)` makes sense by analogy to `_.each`, but it ensures that 
- flush cycles occur between runs of `fn`
- any interleaved invalidations are also not clobbered

``` js
➢ rv = new ReactiveVar(1);
➢ Tracker.autorun( function(){ console.log(rv.get()); } )
➢ logAndSet = function(v){ console.log(v); rv.set(v); }

➢ Tracker.forEach = function(iterable, fn) {
   var iterator = iterable[Symbol.iterator]();
   var f = function () {
     var next = iterator.next();
     if (next.done) return;
     fn(next.value);
     Tracker.afterFlush(f);
   };
   Tracker.afterFlush(f);
}

➢ Tracker.forEach([1,2,3], logAndSet)
↩ undefined
1
2
3
➢ rv.set(1); Tracker.afterFlush(function(){ rv.set(1.1); }); Tracker.forEach([1,2,3], logAndSet);
↩ undefined
1
1.1
2
3
4
➢ rv.get();
↩ 4

```

**Comment by stubailo** [comment]
Hi, @deanius!

It looks like you are interpreting tracker as a stream of events, like an event emitter or similar. I believe the intended use for Tracker is solely for eventually-consistent data - so it should be reasonable to ignore some intermediate changes in a variable as long as things arrive at the correct state eventually.

I think that intention for what Tracker is supposed to accomplish is exactly at odds with the idea of ensuring that there is exactly one flush cycle per value, so I would personally be against a feature like this.

If anything, I think it would be better to have the opposite, something that wraps a Tracker dependency that changes often and throttles it to avoid causing too many reruns.

I'll keep this open as a feature request though in case someone else wants the same thing. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
As part of the on-going old issue cleanup process, since there has been very little support for this request in over 1.5 years, I'll close it off. Thanks for the original request!
