### ISSUE TITLE
Meteor tool error: "USER: unbound variable"

### ISSUE THREAD

**Issue by JamesMGreene** [meteor/meteor#4894]
I am getting an error from the Meteor tool (shell script) while trying to run Meteor on a session-less CI build server:

```
/usr/local/bin/meteor: line 78: USER: unbound variable
```

I would submit a Pull Request to fix this but I can't seem to find this tool/script in any of your public repos.  If I'm missing it somehow, please point me to it.

Anyway, here is the specific lines in question (line 78 is the first line):

```bash
  if [ -n "$USER" ]; then
    echo "$USER, this is your first time using Meteor!" 1>&2
  else
    echo "This is your first time using Meteor!" 1>&2
  fi
```

From an isolated view, this code looks fine.  However, it is volatile when combined with the fact that the script _also_ contains the following code on line 25 (which treats undeclared variable usage as errors):

```bash
set -u
```

While the `set -u` is valuable in general, your use of `$USER` is completely unnecessary in the first place, so it should definitely not be required (as your code already intends but misses the mark).

The fix is easy enough with [Bash parameter substitution](http://www.tldp.org/LDP/abs/html/parameter-substitution.html), just update line 78 (again, the first line below) to look like this:

```bash
  if [ -n "${USER-}" ]; then
    echo "$USER, this is your first time using Meteor!" 1>&2
  else
    echo "This is your first time using Meteor!" 1>&2
  fi
```

In the meanwhile, I'll be working around this bug by manually setting the `USER` environment variable on my side... either to an empty string, or to some pertinent real value.

**Comment by rfox90** [comment]
https://github.com/meteor/meteor/blob/devel/scripts/admin/launch-meteor is the file

**Comment by stubailo** [comment]
https://github.com/meteor/meteor/blob/c9eeec7469709288d9fe240319401f146dcded8d/scripts/admin/launch-meteor#L78-L82

**Comment by JamesMGreene** [comment]
Thanks, gents. I'll submit a little PR tonight.

**Comment by JamesMGreene** [comment]
Created PR #4901.

**Comment by glasser** [comment]
Thanks, merged!

**Comment by kod3000** [comment]
Using Pop!_OS 21.04, Meteor version 2.5. Got a similar meteor tool error "HOME: unbound variable". 

A quick fix to this was "export HOME=/your/home/directory" right on the command line and then running the meteor tool.
