### ISSUE TITLE
Add the Meteor tool shell script to a public repo

### ISSUE THREAD

**Issue by JamesMGreene** [meteor/meteor#4895]
Why is the Meteor tool shell script not available in any public repo [that I can locate]?  Is there some reason why it cannot be added to a public repo?  If not, please do so to enable the community to help out with issues like #4894.

**Comment by JamesMGreene** [comment]
P.S. The [Meteor Tool project page](https://www.meteor.com/tool) on meteor.com claims that its repo **is** [_this_ repo](https://github.com/meteor/meteor).

**Comment by rfox90** [comment]
https://github.com/meteor/meteor/tree/devel/tools/cli 

Appears to be everything you need.

**Comment by stubailo** [comment]
@JamesMGreene actually it's less complicated than the above. It's a file called `meteor` in the root of the repository: https://github.com/meteor/meteor/blob/devel/meteor

**Comment by JamesMGreene** [comment]
Thanks, gents. The file I was seeking in this instance was [scripts/admin/launch-meteor](https://github.com/meteor/meteor/blob/devel/scripts/admin/launch-meteor) (thanks for that, @rfox90!).

That said, given the 3 different viable paths mentioned here, it would be much appreciated if there was some high-level explanations of the layout in the "CONTRIBUTING.md" file (or elsewhere). :heart:
