### ISSUE TITLE
Cordova: Directly pointing to tarball not working / Documentation outdated?

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#4896]
Hi, I'm trying to get a Cordova plugin running inside my Meteor app, but nothing works so far. Maybe I'm dumb, but following the instructions from here

https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration

did not lead to a result.

The plugin I would like to use is
https://github.com/phonegap/phonegap-plugin-barcodescanner

First, I tried to add it using:
meteor add cordova:phonegap-plugin-barcodescanner@4.0.0
as this was the name recommended on the plugin page.

This was accepted, and when I ran meteor run ios-device, it also seemed to be downloaded. Yet, after the download, there was an Error 404 error: 

Error: 404 Not Found: phonegap-plugin-barcodescanner

So I used the package syntax instead:
meteor add cordova:com.phonegap.plugins.barcodescanner@4.0.0

Once again, the plugin seems to be downloaded, but then the following error is thrown:
Error: version not found: com.phonegap.plugins.barcodescanner@4.0.0

Ok, maybe Meteor is still pointing to the old plugin Cordova registry, and there's only an older version registered there. So I tried:

meteor add cordova:com.phonegap.plugins.barcodescanner@2.1.0

Well, this worked and the application started. But since I prefer to work with the latest version, I also tried the tarball syntax:

https://github.com/phonegap/phonegap-plugin-barcodescanner/tarball/v4.0.0

But this only throws an error message:
Must declare exact version of dependency:     
com.phonegap.plugins.barcodescanner@https://github.com/phonegap/phonegap-plugin-barcodescanner/tarball/v4.0.0

The same happens if I try:
https://github.com/phonegap/phonegap-plugin-barcodescanner/archive/master.tar.gz
or
https://github.com/phonegap/phonegap-plugin-barcodescanner/tarball/master

This is driving me nuts. If the Cordova integration has some caveats (e.g. because it is still using the old registry), this should at least be documented somewhere.

I'm still asking myself, how I could get the latest version of my plugin up and running?!

**Comment by derwaldgeist** [comment]
PS: Even the build succeeds for the 2.0.1 version, I am still not able to use the plugin using the navigator.barcodescanner syntax.

**Comment by martijnwalraven** [comment]
Installing plugins from a tarball is only supported with a SHA URL, not with branches or tags (this is documented on the Wiki page but it's easy to overlook):

In your case, I believe this URL should work:
`https://github.com/phonegap/phonegap-plugin-barcodescanner/tarball/b005d77852b22073c1b618ddec0d713453f5b69a`

Using the new plugin IDs to download from NPM seems to require a newer version of Cordova than we currently bundle. This should be fixed with Meteor 1.2.

**Comment by derwaldgeist** [comment]
Hi @martijnwalraven: Thanks for this explanation, I will give it a try!

**Comment by martijnwalraven** [comment]
We released the first public Meteor 1.2 RC yesterday (`--release METEOR@1.2-rc.7`), which supports downloading plugins from npm. So that should make this easier.
