### ISSUE TITLE
Make sockjs optional

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#4897]
More and more, people might not care about supporting older browsers. This could mean that they only support browsers that also support websockets, making sockjs of little value.
It would be great if the sockjs code would get pushed in a separate package so that people that don't need to support older browsers can do without its weight, just as with the new es5-shim package.

**Comment by stubailo** [comment]
I'm curious, do we know how much space sockjs takes up?

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by sebakerckhof** [comment]
In terms of filesize it's roughly:
84kB raw
32kB minified
10kB minified and gzipped
 
I just took sockjs-0.3.4.js & stream_client_sockjs.js and put them trough a closure minifier, I guess that makes a reasonable estimate.

**Comment by mitar** [comment]
I think we can keep sock.js on the server. And then on the client only connect directly to it using web sockets. I have done this in the past.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20sockjs%20optional&body=Migrated%20from:%20meteor/meteor%234897) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
