### ISSUE TITLE
Restart build immediately if a file changes while the app is building

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4899]
**_1 Upvote**_ When a client file changes, a rebuild happens, and eventually the client will be restarted.

But, if we change another client file while a build is in progress (the client is yet to be restarted) then that will trigger another build that queues up another client restart.

Idea: when a file changes during a build, cancel the following restart and only restart a single time once files have stopped changing; similar to how `_.debounce` works.

I find myself editing multiple files and saving them in succession, which causes multiple restarts. A single restart would be more efficient. The timeout of the "debounce" can just be the amount of time it takes for a rebuild to complete.

**Comment by trusktr** [comment]
This can apply to server restarts too.

**Comment by zimme** [comment]
:+1:

**Comment by stubailo** [comment]
This is a great idea! Happens to me all the time.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Restart%20build%20immediately%20if%20a%20file%20changes%20while%20the%20app%20is%20building&body=Migrated%20from:%20meteor/meteor%234899) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
