### ISSUE TITLE
Inject CSS-only changes into page without reload

### ISSUE THREAD

**Issue by cmalven** [meteor/meteor#490]
For most non-Meteor projects I use [LiveReload](http://livereload.com) to monitor my project folder for changes, pre-compile Sass & Coffeescript, and reload the browser windows as necessary.

Obviously, Meteor takes care of all of this for me. But LiveReload (and CodeKit, I believe) does one _really_ nice thing that saves me a ton of time: if it detects that the only changes to the project are CSS/Style, it instantly injects the updated styles into the current page _without_ requiring a full page reload.

This might not seem like a big deal, but at roughly 2-3 seconds per reload multiplied by hundreds (thousands?) of style changes and saves over the life of a project, that's some serious time and frustration savings.

I know this is not a high priority for the project, but this might be an easy win for developer happiness.

**Comment by wcj3** [comment]
any update on this for 2017?

**Comment by wcj3** [comment]
Although this issue has been dead for a few years, i'm dropping this to help future travelers:  https://atmospherejs.com/wcj3/sass-hot-loader
