### ISSUE TITLE
Android white screen after HCP

### ISSUE THREAD

**Issue by liangsun** [meteor/meteor#4902]
After hot code push, my Android app turns into white screen with no responses. This only happens when the server is behind a reverse proxy like nginx.

To reproduce this bug:

Meteor version 1.1.0.2

```
meteor create --example todos
cd todos
meteor add-platform android
```

Use `mup` to deploy to server.

mup.json file:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "todo.DOMAIN.com",
      "username": "ubuntu",
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "todos",

  // Location of app (local directory)
  "app": "/Users/liangsun/todos",

  // Configure environment
  "env": {
    "PORT": 3900,
    "ROOT_URL": "http://todo.DOMAIN.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

```
mup setup
mup deploy
```

On the server, configure nginx:

```
server {
        listen 80;
        server_name todo.DOMAIN.com;

        location / {
                proxy_pass http://localhost:3900;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade; # allow websockets
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP

                if ($uri != '/') {
                        expires 30d;
                }
        }
}
```

Build android apk file:

```
meteor build --server=http://todo.DOMAIN.com --directory ~/todo-builds  --debug
cd ~/todo-builds/android/
adb install unaligned.apk
```

Now open the app on the Android device, and it connects the server. Until now, everything works.

Change a template file of todos project, for example, in file `client/templates/lists-show.html`, change `{{incompleteCount}}` to `{{incompleteCount}}1111`. 

```
mup deploy
```

Open a browser, the page shows the change has been made. However when it comes to the app, it turns into white screen, and not responsible to users.

I look into the `adb logcat`, but find nothing abnormal.

This is 100% reproducible, please have a look at this, and contact me if any question.

**Comment by martijnwalraven** [comment]
My first thought is that there might be a problem with the `ROOT_URL` setting on the server, but from what you've posted it seems you've configured it correctly. Can you check whether `http://todo.DOMAIN.com/__cordova/index.html` contains the right `ROOT_URL`?

**Comment by martijnwalraven** [comment]
And you may also want to try using remote debugging to see if there are any errors on loading. You may have to do a `window.location.reload()` after you connect the debugger to trigger a reload.

**Comment by liangsun** [comment]
@martijnwalraven Thanks for your quick reply.

I checked `http://todo.DOMAIN.com/__cordova/index.html`, it seems the `ROOT_URL` value is right, but there are two errors in this page.

 I use `DOMAIN.com` just for reproducing consideration. Actually you may check my site here : `http://todo.feichanglaoshi.com`.

I will remote debug the app to see if there are any errors.

**Comment by liangsun** [comment]
@martijnwalraven Yes, I find an error when remote debugging. <https://www.dropbox.com/s/gnvklozwx8p4uj5/Screen%20Shot%202015-08-07%20at%2015.49.20.png?dl=0>

**Comment by martijnwalraven** [comment]
A `SyntaxError: Unexpected token '<'` usually means the client is receiving HTML content where it was expecting JavaScript. I expect you'll find the mentioned `.js` file is in fact loading `index.html`, which happens if the file cannot be found on the device.

If that same `.js` file can be loaded directly from the web server, that might mean something has gone wrong during a Hot Code Push update. Have you tried reinstalling the app? Or does it happen every time?

Any chance you're running a Meteor preview release with the batch plugins work?

**Comment by liangsun** [comment]
@martijnwalraven That same `.js` file in the server is also not correct (content is html format). I believe something has gone wrong during a Hot Code Push update as you said. After uninstall the app, and then reinstall it, it works, but when do another change to the code and `mup deploy`, it turns to white screen again. So this happens every time after an HCP. One thing I haven't figure out is this only happens with nginx. If I use `mup` to deploy to the `80` port directly, it works; while with nginx reverse proxy to another port, this bug happens.

I tried the most recent source code of Meteor (the `master` branch), this bug also exists.

**Comment by martijnwalraven** [comment]
I'm not sure, but it seems these lines from your nginx conf might be the culprit:
```
if ($uri != '/') {
    expires 30d;
}
```
I think this would lead to caching of an old version of `__cordova/index.html` and other files (those without a content hash for cache busting).

**Comment by liangsun** [comment]
@martijnwalraven You are right. That's the problem. I removed that lines and everything works. Thank you! :+1: :beers:
