### ISSUE TITLE
Session returning "null" as a string

### ISSUE THREAD

**Issue by sklink** [meteor/meteor#4903]
After updating to 1.1.0.3, `Session.get(/* some key here */);` is returning `"null"` as a String instead of the usual `null`.

Was this intended in the update? Could there be some plugin conflict? I've done some searching but haven't found anything related.

Here someone else has run into the same issue--at the same time I did. This was the question they posted: http://stackoverflow.com/questions/31848279/why-are-all-my-sessions-being-set-to-null-by-default-after-updating-to-1-1-0-3

**Comment by stubailo** [comment]
@sklink what version did you update from? Is there an app reproduction? I'm pretty sure we have tests for this.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by sklink** [comment]
Seems like it was a caching issue. One of the plugins must have stored `null` as a String and returned it instead. Something in the update or in the plugin removal (if it was one of the ones I removed) probably triggered it.

Either way, clearing cache and cookies worked. Will post back if it's a recurring issue.
