### ISSUE TITLE
[ecmascript] Meteor core in ES2015 and advice for packages developers

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#4904]
Hi, I have few questions regarding the `ecmascript` package coming with 1.2 release of Meteor.

1. **Are you planning to rewrite most of the Meteor core to use ES2015?**
2. What advice do you have for developers creating packages in terms of using ES2015. In my two packages [ReactiveMap](https://github.com/jagi/meteor-reactive-map) and [Astronomy](https://github.com/jagi/meteor-astronomy) I use some workarounds to support old browsers. In my situation, it's defining setters and getters using `Object.defineProperty` method. As far as I know there is no polyfill for that feature. In the `ReactiveMap` package I've decided to replace `size` property with the `size()` method to make it reactive. In the astronomy package I've introduced the `Astro.config.supportLegacyBrowsers` flag that changes the way Astronomy behaves. **Should I support older browsers?**
3. In many new libraries, developers don't care about old browsers. Let's take [PIXI.js 3.0](https://github.com/pixijs/pixi.js) as an example. The authors use the `Object.defineProperty` method extensively and thanks to that they force people to use newer browsers. **For how long are you planning to support old browsers?** As a company that may change a lot in the Web, you should promote the newest standards. But by supporting old technologies we won't move far away from where we are now.
4. **Do you have any feedback on how many developers want support for old browsers?**

**Comment by stubailo** [comment]
I think @benjamn would be the best to respond to this, although this discussion is probably best had as a forum thread since it's not a feature request or bug report.

**Comment by benjamn** [comment]
Yes, please repost this at https://forums.meteor.com/, and I'll respond there.

**Comment by jagi** [comment]
Ok done https://forums.meteor.com/t/ecmascript-meteor-core-in-es2015-and-advice-for-packages-developers/8312
