### ISSUE TITLE
Can't run an app on Windows if the "build" is done on Windows due to missing bin fibers module

### ISSUE THREAD

**Issue by sjmcdowall** [meteor/meteor#4906]
If you do a meteor build on Windows -- then go to the resulting directory and then do an 
npm install

You get a horrible error (see below) when it tries to install the appropriate fibers@1.0.5 module because the meteor-node-fibers tarbar for windows does NOT have the binaries loaded unlike the REAL node-fibers.  On Windows this is a horrible problem because then it tries to COMPILE said module and that fails because most machines (certainly not mine) don't have a developer environment (C++ / Python most notably). 

Fix -- place needed binaries in the bin directory for the tarbar like fibers@1.0.5 so it finds and uses those and doesn't try to compile them

ERROR FROM NPM 

```
C:\deploy\Galaxy\RTViewer\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/

fibers@1.0.5 install C:\deploy\Galaxy\RTViewer\programs\server\node_modules\
bers
node ./build.js
C:\deploy\Galaxy\RTViewer\programs\server\node_modules\fibers>node "C:\Program
iles\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin
ode-gyp.js" rebuild --release
Building the projects in this solution one at a time. To enable parallel build
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe"
To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visu
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere. [C:\deploy\Galaxy\RTViewer\programs\server\node_modul
s\fibers\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.e  failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_module
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack at ChildProcess.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:82
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_mo
les\node-gyp\bin\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\deploy\Galaxy\RTViewer\programs\server\node_modules\fibers
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
Build failed

npm ERR! fibers@1.0.5 install: node ./build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./build.js
npm ERR! You can get their info via:
npm ERR! npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\n
ejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\deploy\Galaxy\RTViewer\programs\server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by sjmcdowall** [comment]
Further update -- I did install Python and VS2015 Express (all I could find) -- and I still get a build error because it appears this logic was made for VS2005 (?!?!) and in VS2010 the command line tools changed (or that's what I am getting out of it) . 

Am I really the only person affected by this!?

**Comment by stubailo** [comment]
Interesting. We have a fork of Fibers so that things work a little differently. People are often affected by a different layout of thread locals than the default fibers implementation expects, sometimes because antivirus programs or similar are adding threads.

This is definitely something we should fix to make it easier to deploy Meteor on Windows servers.

**Comment by sjmcdowall** [comment]
Thanks -- sound be pretty simply to add the fibers.node compiled bit to the package under "bin/win32-blah-blah-blah" directory.  Don't remember exactly what path it is for Node 0.10.36 on windows .. but dumping the current fibers@1.0.5 should easily show the right name. :)

**Comment by morrismukiri** [comment]
I'm experiencing the same problem. I've tried installing the required npm packages globally first but can't install bcrypt

**Comment by sjmcdowall** [comment]
@morrismikiri -- until MDG updates their hacked fibers .. you may just have to bite the bullet and install the VS 2012 CE version of stuff to have the tools to build fibers on your machine .. then package up the whole kit into a shrink-wrap bundle to deploy.  I use demeteorizer to do the shrink wrap part -- works well for me -- but I did have to install VS2012 STUDIO Express .. <sigh> ..

**Comment by willrbc** [comment]
@sjmcdowall Any chance of a brief step by step on how to achieve this?  I'm not a windows dev at all, but really need to get a little meteor project running on a windows server.

**Comment by sjmcdowall** [comment]
If I can find the time I'll try to write something up over the next few days as this is a common issue - may not be pretty but ...

**Comment by mageddo** [comment]
Me too.. I have installed from source


	0 info it worked if it ends with ok
	1 verbose cli [ 'c:\\home\\programs\\node\\node.exe',
	1 verbose cli   'c:\\home\\programs\\npm-1.4\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'install' ]
	2 info using npm@1.4.9
	3 info using node@v0.12.7
	4 verbose readDependencies using package.json deps
	5 verbose install where, deps [ 'c:\\home\\codes\\mageddo-web-3\\mageddo-api\\node-fibers',
	5 verbose install   [] ]
	6 info preinstall fibers@1.0.1
	7 verbose readDependencies using package.json deps
	8 silly resolved []
	9 info build c:\home\codes\mageddo-web-3\mageddo-api\node-fibers
	10 verbose linkStuff [ false,
	10 verbose linkStuff   false,
	10 verbose linkStuff   false,
	10 verbose linkStuff   'c:\\home\\codes\\mageddo-web-3\\mageddo-api' ]
	11 info linkStuff fibers@1.0.1
	12 verbose linkBins fibers@1.0.1
	13 verbose linkMans fibers@1.0.1
	14 verbose rebuildBundles fibers@1.0.1
	15 info install fibers@1.0.1
	16 verbose unsafe-perm in lifecycle true
	17 info fibers@1.0.1 Failed to exec install script
	18 error fibers@1.0.1 install: `node ./build.js`
	18 error Exit status 1
	19 error Failed at the fibers@1.0.1 install script.
	19 error This is most likely a problem with the fibers package,
	19 error not with npm itself.
	19 error Tell the author that this fails on your system:
	19 error     node ./build.js
	19 error You can get their info via:
	19 error     npm owner ls fibers
	19 error There is likely additional logging output above.
	20 error System Windows_NT 6.1.7601
	21 error command "c:\\home\\programs\\node\\node.exe" "c:\\home\\programs\\npm-1.4\\node_modules\\npm\\bin\\npm-cli.js" "install"
	22 error cwd c:\home\codes\mageddo-web-3\mageddo-api\node-fibers
	23 error node -v v0.12.7
	24 error npm -v 1.4.9
	25 error code ELIFECYCLE
	26 verbose exit [ 1, true ]

**Comment by mageddo** [comment]
I have do `npm install` Is it your question?

**Comment by sjmcdowall** [comment]
@mageddo - my question was the set of commands you issued prior to getting the error, including the one causing the error.  I am trying to figure out your environment.  You may want to read my post on the Meteor forum https://forums.meteor.com/t/one-deployment-method-for-a-meteor-application-on-windows/13928 that could give you some ideas depending on what you are trying to do..

**Comment by hwillson** [comment]
Meteor has received many internal improvements since this issue was posted, and Windows developers are able to develop/deploy using the latest versions of Meteor successfully. Due to this issues age and lack of activity, I'll close it off. Please post back if you're still experiencing these issues using a recent version of Meteor. Thanks for reporting this originally!
