### ISSUE TITLE
Ability to default `settings.json` and pick via environment

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#4910]
It'd be great if `meteor run` picked up some kind of default settings file (`default-settings.json`?) so you didn't have to run with `--settings` all the time.

Additionally, it'd be pretty useful to be able to do `meteor run staging` and have it pick up `staging-settings.json`, etc. 

Probably this only works in dev mode (i.e. if you specific `--production` you need to be specific, no automagic).

See also #4887 for a similar request.

@timbotnik and I have discussed how to do this with a user-space package. We'll post here about it when we've had a chance to do so.

**Comment by radalin** [comment]
This really makes sense. I was about to make the same request after looking around for half an hour and finally looking to the source code.. Also the idea about "meteor run staging" etc looks good too.

**Comment by AlbinoGeek** [comment]
Why not load `settings.json` in production?  That's a pretty sane naming convention.
Thus, `staging-settings.json` and `dev-settings.json` for example, would be possible.
Even `test-settings.json` for test runners, if exists.

**Comment by hwillson** [comment]
Now that Meteor supports npm, I think we can close this issue off. Npm's [scripts](https://docs.npmjs.com/misc/scripts) functionality can be used to achieve the same thing: 

**package.json**

```json
...
  "scripts": {
    "start": "meteor --settings=config/settings.json",
    "start-staging": "meteor --settings=config/settings-staging.json"
  },
...
```

then `meteor npm start` to start prod, `meteor npm run-script start-staging` to start staging, etc.

Thanks for the original suggestion!
