### ISSUE TITLE
when i deploy it as an ios app,http package can't make an cross domain request

### ISSUE THREAD

**Issue by boxmate** [meteor/meteor#4911]
when i deploy it as an ios  app,http package can't make an cross domain request,so how can i solve this problem?

**Comment by martijnwalraven** [comment]
Have you defined [`App.accessRule`](http://docs.meteor.com/#/full/App-accessRule) for the domain you're trying to access to your [`mobile-config.js`](http://docs.meteor.com/#/full/mobileconfigjs)?

**Comment by boxmate** [comment]
yes , I had add

App.accessRule('*'); 

to the mobile-config.js

but i still can't use   HTTP.get   to request the url  such as  http://www.google.com

**Comment by martijnwalraven** [comment]
This is similar to what would happen in a stand-alone browser. Unlike regular Cordova apps, Meteor doesn't use `file://` URLs to access the bundled content, but serves files from `http://meteor.local`. This means XHR requests (which is what the HTTP package uses on the client) will have to respect [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) rules.

In addition to the client whitelisting the URLs it is allowed to access (which is what `App.accessRule` does), the server you're making the request to will need to set the right headers based on its own policy (`Access-Control-Allow-Origin: *` in the simplest case).

In your example, `http://www.google.com` does not allow loading from other origins and hence cannot be used directly from the client.

**Comment by boxmate** [comment]
Ya,  I know CORS,but  such ios and  android ,their native app never think about the CORS.
if i want to request an url(such as rss) and the server  not in my control,  also  the request depend the client's ip, how can i sovle this problem?

**Comment by martijnwalraven** [comment]
I agree this is a pain. A Cordova app runs in a web view and thus has to obey the rules it sets for it. The problem here is that, for other reasons, we're not serving the bundled content from a `file://` URL and so CORS requirements kick in.

What you could do to get around this is to use native mechanisms to download the content instead, by using [`cordova-plugin-file-transfer`](https://github.com/apache/cordova-plugin-file-transfer) or another plugin.

**Comment by boxmate** [comment]
Thanks  very very much for your reply, i'll try cordova-plugin-file-transfer ,but I think that so many people would have the same problem with me ，will you update meteor project in some day that the HTTP package without this problem? such as write some native code for the webview

**Comment by ChenLi0830** [comment]
+1
