### ISSUE TITLE
7z.exe missing from Windows build machine

### ISSUE THREAD

**Issue by pward123** [meteor/meteor#4913]
When attempting to publish-for-arch on the os.windows.x86_32 build machine, I receive the following error.

```
C:\Users\Public\Documents\meteor\packages\meteor-tool>..\..\meteor publish-for-arch pward123:meteor-tool@1.1.4_2
'7z.exe' is not recognized as an internal or external command, operable program or batch file.
"Please install 7z.exe (7-Zip) and put it into your PATH"
```

I am able to successfully publish on the linux machines, so I'm fairly certain that I'm doing things correctly.

I did notice that @jboulhous mentioned this in passing on #4630.  I dropped this into a separate issue since the Windows build error wasn't really the topic at hand on the other ticket.

**Comment by sjmcdowall** [comment]
One presumes you used the option to create a tarball on the build command line?  If so, this shouldn't come as a surprise really?  Just install 7z (it's free) and make sure it gets installed with the option to add it to the PATH environment.  ??  7Z must be the most popular packing utility on Windows.. like tar on Unix/Linux.

**Comment by pward123** [comment]
Do we have the ability to install applications on https://github.com/meteor/meteor/wiki/Build-Machines ?

**Comment by pward123** [comment]
I just tried what you suggested.  The only download from 7-zip.org is http-based which I have been unable to get downloaded using the build machine.  It doesn't look like wget was installed on the build machine, so I'm not sure how to go about downloading the file.

Even if I manage to get it downloaded, The downloads appear to be msi or installation executables which I doubt I'll have the ability to install.  I guess I could download it to my local, but I don't have access to a Windows machine, so that's not exactly going to help.

In any case, none of my coworkers are using WIndows machines, so it doesn't really matter to me.  I thought I'd report the issue since it seems strange that a build machine would be created for the purpose of running publish-for-arch without including one of the requirements.

**Comment by laosb** [comment]
You could download the zip version of 7z, which have 7z.exe in it without installing. 
You may try `start http://xxxxx/xxx.zip` which can trigger downloading.

**Comment by glasser** [comment]
Hmm, @Slava says that 7z is supposed to be in the image.

**Comment by Slava** [comment]
I have recently used a Windows build machine to publish a release from checkout (that requires 7z), and it worked fine. I don't remember the exact details, which part actually downloads 7zip, but the matter of fact, it works for me this week. If it doesn't work, you would need to prove it with a repro.

**Comment by pward123** [comment]
Not exactly sure how I create a repro for something this simple. I can go into any folder regardless of whether it is a meteor app or not and run the following:

```
pward> meteor admin get-machine os.windows.x86_32
Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>7z.exe
'7z.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pward123** [comment]
I also just tried running a (dir /s 7z.exe) from C:\ and file not found was returned

**Comment by Slava** [comment]
@pward123 I am sorry, you are totally right. I found the code in our scripts that downloads 7zip, and it doesn't happen to everyone.

https://github.com/meteor/meteor/blob/1f985eb2fdd9d4797759a094967d3406e0cd7ac9/scripts/admin/publish-meteor-tool.bat#L24-L29

**Comment by Slava** [comment]
I think this will be helpful to be able to run meteor from checkout on the build machines w/o installing 7zip all the time. Unfortunately, the process involved in updating the build machine image is pretty complicated and I am not going to do it right now. I hope the link to our script will help you to workaround your problem.

**Comment by pward123** [comment]
No worries. None of my coworkers are running Windows. This was my first attempt at creating a release of the meteor tools. So, I ran through all of the steps for completeness.  Feel free to put it on the back burner.

**Comment by Sanjo** [comment]
@pward123 Here are the easiest steps to publish the meteor-tool: https://velocity.readme.io/docs/publish-a-release#release-the-velocity-meteor-command-line-tool-fork

**Comment by hwillson** [comment]
There has been recent discussion about potentially shutting the Meteor build farm down. MDG is moving towards a different build process internally, and the existing build farm is used very little. More details on this plan will be coming shortly (likely as part of the work on https://github.com/meteor/meteor-feature-requests/issues/152). Given this new direction, I'll close this issue for now. Thanks!
