### ISSUE TITLE
Twitter retrieveCredential not working.

### ISSUE THREAD

**Issue by keslert** [meteor/meteor#4914]
Twitter.retrieveCredential now requires a credentialSecret to work, but at the time of calling, you only have access to the credentialToken. Passing nothing for the credential secret doesn't work.

https://github.com/meteor/meteor/blob/devel/packages/twitter/twitter_server.js

**Comment by anubhav94** [comment]
Hey @keslert! Sorry I don't understand what you're trying to do and what went wrong. Could you break it down a little bit more and explain which step of the OAuth handshake broke down and how far you were able to get with it working?

With more information, I hope to be able to solve your issue. Also, a full reproduction of how to face the same issue would be extremely helpful. Another place to check out might be #2118 which I think faces similar issues and let us know if that relates to what you're seeing.

**Comment by whitebeatle** [comment]
@keslert @anubhav94 hey guys i think i have a similar issue. My scenario is below

    Twitter.requestCredential({
       // no scopes here
    }, function(token) {
       // here once the popup is successful, the window does not close
       // when i inspected that window it says
       // Error: Permission denied to access property "Package"
       // and if i reload that url, the window closes and the token comes through.. But!!
       var secret = OAuth._retrieveCredentialSecret(token);
       // this secret is null
       // and because of this i cant get the value from the below line.
       // Twitter.retrieveCredential(token, secret)
    });

Any help would be great! Thanks!
@keslert have you solved the issue?

**Comment by whitebeatle** [comment]
i solved my issue! i was using ngrok and had the generated url as my ROOT_URL. By removing the env variable i got the secret value.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and this issue is rather old.  Would be happy to reopen it if you come up with some additional details (e.g. reproduction, steps, code) that are helpful in resolving it! :)

See [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more information on what would be necessary.
