### ISSUE TITLE
[tutorial] "Latency compensation" should be replaced by "Optimistic UI"

### ISSUE THREAD

**Issue by nomosyn** [meteor/meteor#4917]
In the tutorial [Security with methods](https://www.meteor.com/tutorials/blaze/security-with-methods)

we have:
> ... a bit later in the section titled *Latency compensation*.

but next section is:
> Optimistic UI

so should be:
> ... a bit later in the section titled *Optimistic UI*

**Comment by Tim-W** [comment]
+1

Create a pull request?

**Comment by anubhav94** [comment]
Thanks @nomosyn ! Fixed and we'll push it out soon!
