### ISSUE TITLE
Fields option not working on find or findOne to exclude the _id field

### ISSUE THREAD

**Issue by jeffkile** [meteor/meteor#492]
Collection1.findOne({_id:this._id}, {fields:{_id:0}});
The result of the above contains the _id even though im using the fields option to exclude it.

**Comment by llnathanll** [comment]
This issue is still valid.  Currently running Meteor 1.7.0.5, and `collection.findOne({}, { _id: 0 })` returns the entire document, including the _id field.  This is happening on server code.

**Comment by glasser** [comment]
@llnathanll Meteor's Mongo API has a second argument that is options, so you need a `fields:` in there.

**Comment by llnathanll** [comment]
Thanks for the quick reply @glasser, I stand corrected.  Unlike in the native mongo query, Meteor's api requires `collection.findOne({}, { fields: { _id: 0 } })`.  Closer reading of the docs, and indeed this thread, would have made that clear.
