### ISSUE TITLE
Custom fonts not working in Android app

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#4925]
I've built a Cordova app that uses custom web fonts, stored locally (so the fonts will show up correctly even if there is no internet connection). The fonts are stored in the /public/fonts folder.

This works well if I call the app on the desktop browser and on my iPad. However, if I display the app on my android device (HTC One with Android 5.0.2), the fonts are replaced by the standard system font (Roboto). In order to cross-check font display capabilities, I opened the web app directly in Android's Chrome browser. Here the fonts show up correctly.

Are there any limitations on loading fonts locally from the app's file storage on Android?

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by derwaldgeist** [comment]
I have to apologize, it was my fault. The font path conained two slashes in succession. iOS was so nice to ignore this, but Android didn't. I don't know exactly why it worked after a hot code reload, but this may be due to some sanitation the Meteor loader does while updating.

**Comment by stubailo** [comment]
Interesting. I've run into some similar things in different browsers. I thought the URL spec was to ignore a double slash, but maybe that's only for Unix file paths. Who knows these days.

**Comment by derwaldgeist** [comment]
Yup, obviously Android doesn't ignore this.
