### ISSUE TITLE
Facebook Avatar not Working on Android App

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor/meteor#4927]
Hello:

Per the wiki instructions, I'm testing my Android app via a deployed mobile server. I'm able to log in without any trouble via Facebook Connect, but the avatar image doesn't show, though it works on the mobile server itself. Any ideas what the issue might be?

Thanks!

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
