### ISSUE TITLE
Meteor installation failed on Windows 10

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4931]
Originally posted by @ViniciusAtaide on the windows-preview repo:

I've installed meteor as the image says under windows 10.
![Meteor Installer](http://i.stack.imgur.com/Ropyu.png)
The meteor command is still not recognized.
There's no .meteor folder in my \users\vinicius folder

**Comment by sebakerckhof** [comment]
I installed on win 10 successfully, it did require a restart before meteor command was available. Does win 8.1+ handle changes in path different than before?

@ViniciusAtaide
.meteor folder should be in the \AppData\Local\.meteor folder of your user, not in the home folder as it is on linux.

**Comment by Sanjo** [comment]
This behavior also exists prior to Windows 10 (I think at least since Windows 7). To refresh the path you need to terminate the cmd.exe process at least I think. Logging out and back in or restarting also works.

**Comment by abernix** [comment]
Windows 10 does work, but no matter what, existing `cmd.exe` windows need to be re-opened after installation.  But additionally, you need to do _one_ of the following:
* logout and log back in
* restart
* open the "System Environment Variables" control panel window and press "Ok" on it.

I tried fixing this in #7443 but the WiX installer used on the machine that the installer is built on is terribly old and lacking the API necessary to trigger the event so I've closed it until that can get revisited and the WiX build dependencies upgraded to more recent versions.

**Comment by hantsy** [comment]
I also got problem under Windows 10 .

The **InstallMeteor.exe** installation does not download any packages like before, and a flash to finish page. 

And when I run the meteor command in CMD, either restart or not, either administrator or not, and got:

```
E:\temp>meteor create simple-todos
This project uses Meteor 1.4.2.3, which isn't available on Windows. To
work with this app on all supported platforms, use
meteor update --release METEOR@1.4.2.3 to pin this app to the newest
Windows-compatible release.
```

After I run `meteor update --release METEOR@1.4.2.3` and still get the same info.

**Comment by abernix** [comment]
@hantsy Please try reinstalling Meteor using the following directions.  Do not run the Meteor Installer or the `meteor` command as Administrator.

* Uninstall Meteor from:
  * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
  * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by hantsy** [comment]
@abernix No lucky here. 
The problem I found the installer does not download files at all. The installation will go to login/signup view when I open the installer.

I did all of these steps, after that, I can not find `metoer` in path. And there is no folder named `.meteor` under my `%LOCALAPPDATA%` .

**Comment by abernix** [comment]
The situation you're describing definitely does happen if you run the reinstaller again without uninstalling, but if you uninstall and reinstall, it should download again.

If it doesn't download, it's entirely possible that you're encountering a firewall situation that's preventing the transfer of the bootstrap ZIP file

Please try the [Alternate Windows Installation Instructions](https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md) and report back if it works for you.

**Comment by hantsy** [comment]
@abernix This works for me , Thanks. I remember I installed Meteor before using the same approach. 

>If it doesn't download, it's entirely possible that you're encountering a firewall situation that's preventing the transfer of the bootstrap ZIP file

I am not sure about this, lots of websites are difficult to be accessed in China, but I hope Meteor can provide a official minimal runtime zip file for public download. 

Thanks for your help.

**Comment by rogerman789** [comment]
@abernix I did what you suggested but still no luck, also the alternate one.
I am using Windows 10 Pro
*meteor help show* command work fine, but not for *meteor --version*

**Comment by abernix** [comment]
@rogerman789 I suggested a couple things in this issue.  Can you be more clear about specifically what you did?  As an extreme step of caution: I would recommend uninstalling, restarting, reinstalling, restarting and then trying to run `meteor` from the command prompt.  Please don't run the installer, or the Command Prompt as "Administrator", as this could cause problems with permissions.

**Comment by rogerman789** [comment]
@abernix Here is what I did:
1. Uninstall, check %LOCALAPPDATA%
2. Restart
3. Download installer and install (it's downloading), skip logging
4. Restart
5. Command prompt: meteor --version
Unfortunately still no luck, but thanks for your suggestions. I'll try next time.

regards,

**Comment by hellbertos** [comment]
I'm having the same issue on a stable Win 10 machine. I cannot get meteor installed either by the MSI or manually extracting to %LocalAppData%.

If anyone figures this out, PLEASE POST!! Thx in advance...

**Comment by ericmaro** [comment]
this must me the oldest bug I ever saw.. :)

**Comment by hwillson** [comment]
Given that many people are using Meteor successfully on Windows 10, and there hasn't been any activity on this issue in quite some time, I'll close it for now. If you anyone is still encountering this problem, please post back with as many details as possible (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), and we'll re-open. Thanks!

**Comment by maka-io** [comment]
Old post, I know, but I was also having problems with installing Meteor on Windows 10.  So much so that I updated maka-cli (www.maka-cli.com) to provide an installer that works for Windows, Mac, and Linux.

``npm -g maka-cli``
``maka install meteor``
