### ISSUE TITLE
Error installing Meteor on Windows: 0x80070643. Fatal Error during installation.

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4932]
Originally posted by @chesteremia on the windows-preview repo:

I've been trying to install Meteorjs on windows but error occurs. I already tried downloading another installer and restarting my computer but it doesn't work. It always pops 'failed to contact install server. Please try again' then displays the message 'One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file.'

Under that it displays '0x80070643. Fatal Error during installation.'

*I also tried running it as an admin and turning off the firewall

**Comment by uno-de-piera** [comment]
Hi,

Which Windows operating system are you running?, I have this issue with windows 8.1, if this are your case, you can try changing the compatibility settings for Windows 7.

Regards.

**Comment by gotandon** [comment]
has this issue been resolved yet?

**Comment by stubailo** [comment]
No, sorry - if it is resolved we will close it here.

**Comment by nata-ax** [comment]
I try to run it with administrator and meteor successfully installed.

**Comment by BlazeSahlzen** [comment]
@nata-ax Using this StackOverflow [answer](http://stackoverflow.com/questions/32675541/meteor-js-windows-install-error-failed-to-contact-install-server/34013958#34013958) I successfully installed a lower version of Meteor..but now `meteor update` doesn't work. The response I get is:

> This project uses Meteor 1.2.1, which isn't available on Windows. To work with this app on all supported platforms, use meteor update --release METEOR@1.2.1 to pin this app to the newest Windows-compatible release.

Any workaround?

**Comment by Lukejkw** [comment]
On Windows 10 here. Also cannot install. 

Get the following error:
[2A20:15F8][2016-03-09T15:17:12]e000: Error 0x80070643: Failed to install MSI package.
[2A20:15F8][2016-03-09T15:17:12]e000: Error 0x80070643: Failed to configure per-user MSI package.


Attached log file
[Meteor_20160309151701.zip](https://github.com/meteor/meteor/files/165152/Meteor_20160309151701.zip)

**Comment by kastureranjit** [comment]
Hello Everyone, I am using windows 10  and I am also getting an error as 0x80070643 Fatal Error while installing meteor. Is there any solution?

**Comment by lyquocnam** [comment]
i installed in windows 10 x64 and without any problem. @kastureranjit  installed nodejs yet ?

**Comment by kastureranjit** [comment]
Yes i have installed node.js. while attempting for 10 th time, installation
stopped at 37%, I think problem is not internet speed. Because of slower
internet connection, its not installing.

**Comment by lyquocnam** [comment]
awesome, me too a few last day. and i tried at the midnight to upgrade meteor. and it work !
i don't know this proplem on meteor server or my internet connection.
try again in midnight like me :D

**Comment by kastureranjit** [comment]
I don't know that whether meteor is on the cloud server if it's hosted on
cloud server then problem will be resolved even if there is   internet
speed issue.and as per your suggestion I will try installing meteor at
mid-night may it installed at that time.

**Comment by kastureranjit** [comment]
Finally installed meteor on windows 10 64bit. Is it necessary to restart the system?

**Comment by lyquocnam** [comment]
you done ? i think we should make sure !

**Comment by kastureranjit** [comment]
Yes I have done.

**Comment by iAssureIT** [comment]
https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation try this

**Comment by hwillson** [comment]
Sounds like this issue has been resolved - closing. Thanks!
