### ISSUE TITLE
ENOTFOUND error when adding package on Windows

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4934]
Originally posted by @XieShangxu:

According to the "Todo" tutorial, run the following command:

```
meteor add accounts-ui accounts-password
```

Then I got this error: 

```
 => Errors while adding packages:

While downloading npm-bcrypt@0.7.8_2...:
error: getaddrinfo ENOTFOUND

Your package catalog may be out of date.
Please connect to the internet and try again.
```

My meteor version is 1.1.0.2

Thanks so much for your support!

**Comment by stubailo** [comment]
Originally posted by @johncarse:

+1

I'm behind a corporate firewall. I set the proxy and am able to curl http/https to http(s)://www.websocket.org/echo.html and curl https to packages.meteor.com successfully. However, when I run the meteor create, I get the ENOTFOUND error.

```
C:\Projects>meteor create --example localmarket
=> Errors while creating your project

While downloading iron:core@0.3.4...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading iron:dynamic-template@0.4.1...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading iron:layout@0.4.1...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading iron:router@0.9.4...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading mdg:camera@1.1.4...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading mdg:geolocation@1.0.2...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading percolate:velocityjs@1.2.1_1...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading percolate:wireframing@0.2.0...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

While downloading tmeasday:publish-counts@0.3.4...:
error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

```

**Comment by juanmarvin** [comment]
I got the same error here. 

While downloading npm-bcrypt@0.7.8_2...:
error: getaddrinfo ENOTFOUND

I am behind corporate firewall too. Is there any solution so far?

**Comment by amibappy** [comment]
i am having the same problem !!!
someone plz help !!!!!!!!!!!!!!!!!!!!!!!!!!!

Give a solution for this issue @meteor

**Comment by abernix** [comment]
Ultimately, the solution here is to ensure that the proxy supports web sockets.  I realize that's not possible in all cases but this is covered in (duplicate) #7151.  While this is older, I'm closing in favor of that as it's won the popularity contest.  Cheers!
