### ISSUE TITLE
MongoDB exit code 100 when running on Windows

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4936]
Closed a thread with 30 comments from meteor/windows-preview

@sdarnell mentioned a part of the MongoDB docs:

http://docs.mongodb.org/manual/administration/production-checklist/
"Windows: use the NTFS file system. Do not use any FAT file system (i.e. FAT 16/32/exFAT)."

It isn't clear whether that is for performance reasons or for functional reasons.

**Comment by hwillson** [comment]
This issue came out of testing the Windows preview release. Windows versions of Meteor have now been in use for quite some time, and more specific Windows + Mongo issues have been opened (a lot of which have been addressed). Given this, we should be okay to close this issue. Thanks!
