### ISSUE TITLE
Support Git Bash on Windows

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4938]
**_2 Upvotes**_ Continuation of a thread with 26 comments on meteor/windows-preview.

Originally posted by @jonagoldman:

The meteor path was added correctly to my system variables, but I can't run it when using the Git Bash.
When using the regular windows cmd it works correctly.
![image](https://cloud.githubusercontent.com/assets/1297559/6637792/54b1d8ee-c987-11e4-993d-33971aadeb0c.png)
And here is when using the cmd:
![image](https://cloud.githubusercontent.com/assets/1297559/6637804/777570d4-c987-11e4-9c6e-36f30b78740c.png)

**Comment by jacek-dargiel** [comment]
+1

**Comment by choidamdam** [comment]
+1

**Comment by adrianciurdarean** [comment]
+1

**Comment by wojtkowiak** [comment]
FYI Windows 10 64bit, minigw64 - `meteor.bat` spawns meteor correctly without any issues.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20Git%20Bash%20on%20Windows&body=Migrated%20from:%20meteor/meteor%234938) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
