### ISSUE TITLE
Meteor cordava error on fresh installation

### ISSUE THREAD

**Issue by cesarve77** [meteor/meteor#4941]
I got error running on android real device after fresh installation

I follow this steps in a mac terminal with cordova -v 5.1.1 :

```
meteor create app
cd app
meteor add-platform android
meteor run android-device 
WARNING: You are testing your app on a remote device.For the mobile app to be able to connect to the local server, make sure your device is on the
         same network, and that the network configuration allows clients to talk to each other (no client isolation).
[[[[[ ~/Documents/www/visitor2/borrar ]]]]]   

=> Started proxy.                             
=> Started app on Android Device.             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20150811-15:49:08.311(-4.5) (android:http://meteor.local/packages/meteor.js:811) Uncaught TypeError: queue.shift(...) is not a function

**Comment by avital** [comment]
So you can't run any apps on your Android device? It could be somehow related to the specific Android device you have -- which is it? (Though I'd still be surprised that some Android devices run JavaScript that doesn't have the `shift` method on arrays, which is what seems to be happening -- this probably comes from `packages/meteor/startup_client.js`)

@martijnwalraven, got any ideas what might be causing this?

**Comment by martijnwalraven** [comment]
It seems the error comes from `(queue.shift())()` in `packages/meteor/startup_client.js`. So the issue is not that `shift` is somehow not defined, but that it is expecting to find a function to call in the `queue` array. That would probably mean someone has passed a non-function argument to `Meteor.startup`?
