### ISSUE TITLE
Can't set buildNumber in App.info of mobile-config.js

### ISSUE THREAD

**Issue by rodrigok** [meteor/meteor#4944]
I'm trying to generate a new version of my app with same version but a different build number.

When I tried to set buildNumber in App.info I received this error:
```
Error while running for mobile platforms: Error reading mobile-config.js:Error: Unknown key in App.info configuration: buildNumber
```

Looking at code seems that should be possible to inform the buildNumber https://github.com/meteor/meteor/blob/devel/tools/cli/commands-cordova.js#L1493 and if I don't inform this code should generate a random build id but when I open the project in Xcode the build number is always equals to version.

Ideias?

**Comment by martijnwalraven** [comment]
I assume you're running the release version of Meteor (1.1.0.3 or lower), which doesn't have this feature yet. It was added in https://github.com/meteor/meteor/pull/4048 and will be a part of Meteor 1.2 (although as you can see in the discussion linked to above, the default `buildVersion` generation will probably be dropped).

**Comment by rodrigok** [comment]
Oh, so nice, thanks.

Can't wait for Meteor 1.2

Are there issues about more icon sizes in mobile-config.js?

**Comment by martijnwalraven** [comment]
I haven't looked into icon sizes yet, but you can always open an issue if you have suggestions :) Make sure to be specific about what is missing.

**Comment by rodrigok** [comment]
Ok, thanks :)
