### ISSUE TITLE
Spiderable package depends on 'templating'

### ISSUE THREAD

**Issue by cherbst** [meteor/meteor#4945]
Right now, the spiderable package depends on the templating package which in turn pulls in blaze. This makes it currently impossible to use spiderable without blaze even if my app uses a different view engine like react or angular. My understanding is that spiderable uses templating to inject the "fragment" meta tag into the head part of the app. The same functionality could be achieved with the new static-html package, but depending on this seems wrong for apps that use blaze as the view engine.

**Comment by stubailo** [comment]
@cherbst does this actually end up with Blaze being included on the client? If spiderable just depends on a server-side version of Blaze, then it seems like this is just an issue about an internal dependency.

**Comment by cherbst** [comment]
spiderable uses templating on the client so indeed blaze ends up being included on the client.

**Comment by cherbst** [comment]
I think the problem here is that `spiderable` needs a compiler for 'html' files to append it's `fragment` meta tag to the head of the document. Both, the `templating` and `static-html` packages provide this compiler, but there is currently no way (I know of) to specify to use only one of two alternative packages in a `package.js` file like in the example below:

```javascript
Package.onUse(function (api) {
  api.useAlternatives(['static-html', 'templating'], 'client');
});
```

**Comment by abernix** [comment]
Tagging as related to #6844

**Comment by hwillson** [comment]
[Google has deprecated the AJAX Crawling specification](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) that the `spiderable` package was based on, which means using the `spiderable` package is no longer really recommended. The Meteor Guide recommends using a service like Prerender.io instead (supported out of the box with Galaxy), in the [Enabling SEO](https://guide.meteor.com/deployment.html#seo) section. I'm wondering if the time has come to deprecate the `spiderable` package? I can't see many more changes being made to it now that better options exist (search engine crawlers have gotten better, pre-render services exist, server-side rendering options are becoming more mainstream, etc.).

**Comment by stubailo** [comment]
> I'm wondering if the time has come to deprecate the spiderable package?

Sure sounds like it!

**Comment by hwillson** [comment]
Hi all - deprecating the `spiderable` package is currently being considered. The reasons for this include (these reasons were alluded to https://github.com/meteor/meteor/issues/4945#issuecomment-278076681):

- Google has deprecated the [AJAX crawling specification](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) that the `spiderable` package is based on;
- Search engine crawlers (like Google's) have gotten much better at dealing with javascript/AJAX based applications, without the need for any special handling;
- There are now several better options for SEO goodness, like pre-rendering services (e.g. [Prerender.io](https://prerender.io/) - recommended in the Guide's [Enabling SEO](https://guide.meteor.com/deployment.html#seo) section and [supported out of the box with Galaxy](http://galaxy-guide.meteor.com/seo.html)), server-side rendering techniques, etc.

As such, I'll close this issue off for now. If anyone feels like this is a bad decision and can justify why `spiderable` should not be deprecated, please post back with your reasons. Thanks for opening this issue originally!
