### ISSUE TITLE
OplogObserveDriver doesn't handle renameCollection operations (used by aggregation with $out)

### ISSUE THREAD

**Issue by lpgeiger** [meteor/meteor#4947]
**_3 Upvotes**_ Mongo's aggregation pipeline is very useful, however using it correctly in Meteor fails silently.
See a reproduction here: http://meteor-aggregation-issue.meteor.com/

I'm posting here since the community has not succeeded in solving it.
http://stackoverflow.com/questions/31620268/why-is-mongo-aggregation-not-reactive-in-meteor
https://forums.meteor.com/t/why-is-mongo-aggregation-not-reactive-in-meteor/7462

SPEC:
Using  Collection.aggregate({ $out: "< output-collection >" }) will output the result of an aggregation pipeline to a mongo collection called < output-collection >. Changes to this < output-collection > should be observable by the meteor server, and UI.

PROBLEM:
Server is not observing the changes to  < output-collection >.  Using $out _DOES_ successfully create <output-collection> (which can be queried in the Mongo console). Also < output-collection > can be queried from the browser.

The < output-collection > is valid. All changes to those documents -- in mongo console for example-- will appear reactively in the UI. The data is not being observed on the server, in repo below see serverMain.js line 8 , observeChanges.

REPRODUCING:
See the github with an app that reproduces the error. Just run 'meteor' and go to http://localhost:3000 to see the walk-through to reproduce.
https://github.com/keyscores/meteor-aggregation-issue

DEPENDENCIES:
The app uses meteorhacks:aggregate, a thin wrapper on the Mongo.aggregate()
https://github.com/meteorhacks/meteor-aggregate/

REFERENCE:
Aggregate and  $out:
http://docs.mongodb.org/manual/reference/operator/aggregation/out/

**Comment by keyscores** [comment]
@Slava @glasser  Can I get your input here to confirm if this is a bug?

**Comment by keyscores** [comment]
From the Mongo Board: 
An aggregate command with an $out stage will create a temporary collection while the aggregation pipeline is running, and then, once the pipeline is done, it will rename the temporary collection to the name specified in the $out stage. e.g. if you ran

db.foo.aggregate([{$out: 'bar'}]);

It would create a temporary bar.tmp.agg_out collection, and insert all the results from the pipeline into that collection. When the pipeline completes, it will rename bar.tmp.agg_out to bar, keeping all indices and options of the existing bar collection (if any).
This should explain the behavior you are seeing. If I understand your code correctly, Meteor is providing a framework to let you listen to events, such as a document being inserted into a collection, and it is not calling the callback when you use an aggregate() command? As a temporary workaround, could you verify that listening to those events on the ".tmp.agg_out" collection would work?

**Comment by jdillworth** [comment]
+1

**Comment by glasser** [comment]
After clicking the second step of your button, I went into the mongo shell and looked at the oplog:

```
glasser@glasser-lyrid 0 ~/Projects/Meteor/meteor-aggregation-issue master u= $ meteor mongo
MongoDB shell version: 2.6.7
connecting to: 127.0.0.1:3001/meteor
meteor:PRIMARY> use local
switched to db local
meteor:PRIMARY> db['oplog.rs'].find()
{ "ts" : Timestamp(1441145240, 1), "h" : NumberLong(0), "v" : 2, "op" : "n", "ns" : "", "o" : { "msg" : "initiating set" } }
{ "ts" : Timestamp(1441145243, 1), "h" : NumberLong("-5456045755250769903"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "ehdfTJ4ZjCvq4yD7S", "name" : "a", "value" : 1 } }
{ "ts" : Timestamp(1441145243, 2), "h" : NumberLong("334401875879171077"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "j98sSwqRD3pkqyfHn", "name" : "b", "value" : 2 } }
{ "ts" : Timestamp(1441145243, 3), "h" : NumberLong("1387168879281153970"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "6t2d8inzY9KEZMmPi", "name" : "c", "value" : 3 } }
{ "ts" : Timestamp(1441145243, 4), "h" : NumberLong("3162788094384001466"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "xfMeB4JD7K4BuqqLw", "name" : "a", "value" : 1 } }
{ "ts" : Timestamp(1441145243, 5), "h" : NumberLong("-8583195719128222365"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "8NEz964GwpkBRcDK7", "name" : "b", "value" : 2 } }
{ "ts" : Timestamp(1441145243, 6), "h" : NumberLong("9040692183003049119"), "v" : 2, "op" : "i", "ns" : "meteor.events", "o" : { "_id" : "kgAFxAJkjs753NW9g", "name" : "c", "value" : 3 } }
{ "ts" : Timestamp(1441145531, 1), "h" : NumberLong("2767682403578686270"), "v" : 2, "op" : "i", "ns" : "meteor.notidealcollection", "o" : { "_id" : "QQHqPHG9zDwT2GnPC", "event" : "c", "aggregated" : 6 } }
{ "ts" : Timestamp(1441145531, 2), "h" : NumberLong("-3039832576346805124"), "v" : 2, "op" : "i", "ns" : "meteor.notidealcollection", "o" : { "_id" : "qgcrrvWfpnHRAyJtZ", "event" : "b", "aggregated" : 4 } }
{ "ts" : Timestamp(1441145531, 3), "h" : NumberLong("-5208097200020456729"), "v" : 2, "op" : "i", "ns" : "meteor.notidealcollection", "o" : { "_id" : "6pBMbB78jdBoBuF52", "event" : "a", "aggregated" : 2 } }
{ "ts" : Timestamp(1441145649, 1), "h" : NumberLong("-886458193635661930"), "v" : 2, "op" : "c", "ns" : "meteor.$cmd", "o" : { "create" : "tmp.agg_out.1", "temp" : true } }
{ "ts" : Timestamp(1441145649, 2), "h" : NumberLong("-5796797451083588092"), "v" : 2, "op" : "i", "ns" : "meteor.tmp.agg_out.1", "o" : { "_id" : "c", "aggregated" : 6 } }
{ "ts" : Timestamp(1441145649, 3), "h" : NumberLong("-2203088077851042561"), "v" : 2, "op" : "i", "ns" : "meteor.tmp.agg_out.1", "o" : { "_id" : "b", "aggregated" : 4 } }
{ "ts" : Timestamp(1441145649, 4), "h" : NumberLong("-4899241878917546351"), "v" : 2, "op" : "i", "ns" : "meteor.tmp.agg_out.1", "o" : { "_id" : "a", "aggregated" : 2 } }
{ "ts" : Timestamp(1441145649, 5), "h" : NumberLong("4404811175292340152"), "v" : 2, "op" : "c", "ns" : "admin.$cmd", "o" : { "renameCollection" : "meteor.tmp.agg_out.1", "to" : "meteor.idealcollection", "dropTarget" : true } }
```

It looks like Mongo processes aggregation with `$output` by putting the data in a temporary collection and then renaming it with a `renameCollection` operation. The oplog driver doesn't know about `renameCollection` operations so it doesn't process this.

We should improve the oplog driver to understand renameCollection, like it already does for `dropCollection`.  (I'll tag this as a feature request; pull requests encouraged).

As a workaround for now, you can disable use of the oplog driver for a query by adding the `_disableOplog: true` option to `find`.  eg, this worked for me (although it can take up to 10 seconds for the polling driver to actually notice the change):

```js
idealButBrokenCollection.find({}, {_disableOplog: true}).observeChanges({
  added: function (id, aggregated){
    console.log("hooray", aggregated);
  }
});
```

**Comment by keyscores** [comment]
Thanks @glasser that confirms what I though it was doing. Would be great to see this improvement to oplog. I'm guessing many people would like to use aggregating more effectively in Meteor.

**Comment by keyscores** [comment]
@glasser @stubailo  Can I get some input on how I could kickstart this? Skimming the code, I'm unsure where to begin.

**Comment by glasser** [comment]
If you search for dropCollection, that should show you some places where something like this is implemented.  (Sorry, I'm not actively working on this part of the project right now and am a bit rusty.)

**Comment by keyscores** [comment]
@glasser Any updates on this? Is it on a roadmap? I'd like to help I'm just not familiar enough with this part of the code. 
Thanks in advance

**Comment by serkandurusoy** [comment]
@glasser a search for `dropCollection` also reveals hits on the mongodb driver. What's the latest update status on the driver? Would a PR for `renameCollection` just be invalidated by a parallel work on the driver or would you guys be able to merge?

**Comment by AlexFrazer** [comment]
+1

**Comment by keyscores** [comment]
@serkandurusoy What are your thoughts on implementing the renameCollection?

**Comment by serkandurusoy** [comment]
@keyscores I think it would not be too hard to do that. My only concern is the *possible* changes on the driver level, which is supposed to get an update anyway, so I would not want to lose work.

**Comment by keyscores** [comment]
@serkandurusoy I can help set up some tests for this if that is helpful.  Let me know what you need to get a pull request proposed to MDG.

**Comment by keyscores** [comment]
@glasser Any updates on this? Any aggregations which are more that 16mb requires $out. So Meteor may not work for many data processing use cases.

**Comment by tastemeru** [comment]
+1

**Comment by keyscores** [comment]
@zol does removing 'backlog' tag mean it's in or out your task queue? :)

**Comment by abernix** [comment]
@keyscores Just reorganizing some labels around here.  This is still in `pull-requests-encouraged` status which means nobody at the core team is actively working on it.  However, I will point out that work is being done to upgrade the built-in Mongo driver to 3.2 (See #6957) and if there is any way to fit it into that project's work/schedule/scope it will be attempted (no promises here).

Could you please at least update your reproduction to the current version of Meteor (1.3.2.4)? :smile:

**Comment by Fabs** [comment]
So guys. I already made two PRs that make the new driver work with and without oplog. The changes are going towards `meteor/mongo-3.2`, you should check there, is a live think right now, but all tests pass for those two scenarios (pending one PR I believe it will be soon in). 

I looked into this issue, I have other things I need to get done first, but I will try to get to it. 

Meanwhile, the driver change does not introduces too many breaking changes. I haven't see it break anything on aggregation pipeline so far, but I haven't seen many tests on it either.  if @serkandurusoy or @keyscores have any patch, code or PR where it is already working or any progress it may help a lot. Tests would be great great, if you guys give me a suite with the desired behaviour of the $out, and etc. I think it would be much easier to me to make the changes.

I am not part of MDG, and I can make any promises on weather I can make it into meteor, but I will be more than glad to try to have it with the mongo-3.2 driver changes. Anyway, after the driver changes, I still have plans to continue working with mongo inside meteor...

**Comment by keyscores** [comment]
@Fabs 
Thanks for taking an interest in the problem. 
I just updated my reproduction repo to 1.3.2 and included a test: https://github.com/keyscores/meteor-aggregation-issue

The tests themselves have an issue with Meteor callbacks. Maybe you can look at them? Seems like meteor method calls are not conforming to the mocha async expectation, and does not finish when calling done(). Can you take a look at that?

**Comment by keyscores** [comment]
@Fabs, apologies, the repo was missing a test file. It's added now.

**Comment by Fabs** [comment]
Right, Thanks :). I am now working on fixing something related to mongod and the dev_build, but I will take a look sooner after it, probably on the weekend.

**Comment by Fabs** [comment]
Just some updates, there is still more work on the mongo-3.2 migration so I did not have that much time here. But there are good news, I started working on the $out, and I managed to get the renameCollection operation from the oplog.

Going further I have some questions.
1) For default behaviour, when I get the rename from oplog, what should I do? Should I just run find all the objects for the specific collection that just got replaced and then send messages that they where just "inserted", so sub.added would be called and everything would work seamlessly (maybe or most certainly, I could use the same query being observed so if you do not observe all there is not a ton of useless objects firing for you to ignore). Is that enough? Is there better ideas? I think there might be a way to build on the fact that the oplog already saw the objects, but on another collection, on the other hand maybe this is a way harder implementation.

2) Should I add something of the sort `sub.rename`? So if you want to use `observe`, `observeChanges` to have a more fine grained control of what happens once we get the rename operation form oplog?

**Comment by keyscores** [comment]
@Fabs that's great thanks for the effort.
1) For my use case, returning the full new collection is acceptable. Since in my aggregation workflow the whole collection gets cleared and replaced with new data.

2) I wouldn't necessarily use an observe changes specifically the 'rename' action. Assuming I could just observe that the documents have been added, I would just keep that pattern.

Thanks!

**Comment by Fabs** [comment]
I did not forget this one :/, but I am sorry I do not have it yet done. I was looking for a job and so lots of though interviews. Got one now, yay. So between now and moving I will have more time to take a look ta this issue. :)

**Comment by keyscores** [comment]
@Fabs  thanks. I've posted another workaround here: https://forums.meteor.com/t/why-is-mongo-aggregation-not-reactive-in-meteor/7462/33

Just documenting it here for posterity:

The solution: Use a $project stage in your pipeline, after the group stage, to rename AND DROP the _id property. Then you can safely output using $out.

So my pipeline looks like this:

    var pipeline = [
          {
            $project:  {
              productName: "$productName",
              price: "$price",
              units: "$units",
              customerTotal: {$multiply: ["$nits", "$price"]},
            }
          },
          {
            $group: {
              _id: {//_id is a fixed property for mongo aggregate, cannot be changed
                productName: "$productName",
              },
              customerTotal: {
                $sum:   "$customerTotal"
              },
              units: {
                $sum:   "$units"
              }
          },
          {
            $project:  {
              _id: 0, // DROP THE _id PROPERTY
              productName: "$_id.productName",
              units: "$units",
              customerTotal: "$customerTotal"
            }
          },
          {
            //outputs to collection. must be used for aggregations over 16MB. Meteor has a know
            $out : "aggregate"
          }
        ]

Run with:

    var aggregateQuery = Meteor.wrapAsync(Apple.rawCollection().aggregate, Apple.rawCollection());
    aggregateQuery(pipeline)

Now the _id is no longer a conflict with the Meteor ID conventions. The data should update reactively.

**Comment by anymos** [comment]
+1

**Comment by mitar** [comment]
I think comments above (to search for `dropCollection` implementation in oplog) are probably a good start for anyone wanting to implement this. Renaming should probably be pretty similar to `dropCollection` handling. Any takers?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=OplogObserveDriver%20doesn't%20handle%20renameCollection%20operations%20(used%20by%20aggregation%20with%20%24out)&body=Migrated%20from:%20meteor/meteor%234947) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
