### ISSUE TITLE
publish with $slice used may cause later subscribe failed

### ISSUE THREAD

**Issue by harlyluyar** [meteor/meteor#4948]
We are using Meteor to build app, and found one weird thing, which looks like a bug.
Just FYI.

We define one collection with scheme:
{
...
'pics.$.data': {
 type: string
}

...
}

Step 1: we open link A, which subscribe only the first element in pics array,
and it works; (server side use { pics {$slide: 1} } to realize this);
Step 2: we goto link B, which will subscribe a different publish, and this publish will publish all pics, rather than only 1st pic.
Now, it always show there is only 1 pic in the document. But after I refresh, it will show all pics.

So it looks the check on data syncing for new publish is only checking if the field already exists, but not checking the $slice case, or something like this.

Hope this helps.

**Comment by glasser** [comment]
Ideally, provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

That said, it sounds like this is what is described at https://github.com/meteor/meteor/issues/3764#issuecomment-75853901 as working as intended and documented, although perhaps in need of improvement.
