### ISSUE TITLE
How to clean things up from DOM before Template.onDestroyed?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4950]
Based on the docs, it seems that `template.onDestroyed` fires after the DOM element for that template has already be removed. How do we do something with that DOM element before it is removed?

Something like `template.onBeforeDestroyed` would be a convenient way to access elements in the template to, for example, run `React.unmountComponentAtNode(template.$('.element-in-the-template'))`.

Right now I'm doing

```js
Template.foo.onRendered(function() {
    React.render(
        <div>blah</div>,
        this.$('.element-in-the-template')[0]
    )
})
```

Now, when the blaze template `foo` gets destroyed, the DOM for the `foo` template is already gone when onDestroyed is called (I believe, based on the fact that we can't use template.$, etc), so how do I unmount my React component from the DOM of the Blaze template if the DOM is gone?

Will we have a memory leak now that React has a reference to the DOM that was previously in the Blaze template and there's no way to get that reference in order to unmount the React component?

**Comment by trusktr** [comment]
Made a suggestion: https://github.com/meteor/meteor/issues/4951

**Comment by trusktr** [comment]
As a workaround, perhaps I can just keep an external reference to an element in onRendered, then use that ref in onDestroyed.

**Comment by stubailo** [comment]
I'm going to keep the other issue about this, because it's more of a feature request and this is a how-to: https://github.com/meteor/meteor/issues/4951
