### ISSUE TITLE
Run meteor in GitHub' s Electron environment?

### ISSUE THREAD

**Issue by s-a** [meteor/meteor#4952]
I know there is no official support for this environment but I want to try it anyway. However I successfully started the Meteor "todo-list" example app in an Electron environment as described here : https://github.com/s-a/iron-node/blob/master/docs/METEOR.md

```
os win32 Windows_NT
node: "2.3.1", 
v8: "4.3.61.21"
```

Unfortunately ```http://localhost:3000/``` returns ```ERR_EMPTY_RESPONSE``` without any exception. 

Any Meteor expert out there willing to help make this work?

**Comment by sjmcdowall** [comment]
You may want to look at the github project 

Electronmeteor 

May help getting it working

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
