### ISSUE TITLE
Inner regions updating incorrectly on div click

### ISSUE THREAD

**Issue by krizka** [meteor/meteor#4956]
Try this tiny code example. Just click 'Some text' and then 'Another text', you will see it will be clonned
```js
Template.test.onCreated(function () {
  this.test = new ReactiveVar(false);
});

Template.test.helpers({
  isTest: function () {
    return Template.instance().test.get();
  }
});

Template.test.events({
  'click .test': function () {
    var test = Template.instance().test;
    test.set(!test.get());
  }
});
```
```html
<body>
  {{>test}}
</body>

<template name="test">
  <div class="test">
      Some text
      {{#if isTest}}
        Another text
      {{/if}}
  </div>
</template>
```

**Comment by stubailo** [comment]
This doesn't happen on my machine when I copy-paste your code. Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
