### ISSUE TITLE
cordova app icon: android_mdpi missing

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#4957]
mdpi icon is not copied to drawable folder.
On some devices Meteor app displays the default icon (not the desired custom one).

reproduce:
- install localmarket example app
- build
- go to .meter/cordova ... platforms/res
- the drawable-mdpi folder is empty

**Comment by martijnwalraven** [comment]
Could you try this again with the Meteor 1.2 RC (--release METEOR@1.2-rc.7)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue. If not, let me know, and I'll look into it.

**Comment by solo999** [comment]
I am on Meteor 1.2 and have the same issue

**Comment by martijnwalraven** [comment]
This should have been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
