### ISSUE TITLE
Custom file and folder ignore rules

### ISSUE THREAD

**Issue by servel333** [meteor/meteor#4958]
As a developer, I would like to have a way to include custom folders to be ignored by the Meteor file gobbler.

These could be

* unique files generated by my choice of editors
* files that are part of some tool I am using
* a `docs/` directory I put documentation in
* a `tmp/` directory I might put files that are not part of the codebase but are related to the project in
* personal notes files I put notes into (I sometimes put program extensions on them so I can put syntax highlighted code in my notes)
* etc.

### Possible solutions:

* Add an ignore file that works like `.gitignore` (List of regexes, `#` for comments, `!` to include files)
  * Possible file names: `.meteorignore`. `.meteor/ignore`
* Add a config file that lists files and folders to be ignore
  * Possible file names: `.meteor/config.json`, `.meteor/preload.js`

**Comment by servel333** [comment]
Implementation of this might allow for simplification of the [ignore rules built into Meteor](https://github.com/meteor/meteor/blob/devel/tools/isobuild/package-source.js#L1303) by removing editor-specific and platform-specific ignore rules to become part of the users project configuration.

**Comment by robertpitt** [comment]
Duplicate of #330

**Comment by servel333** [comment]
@robertpitt True. At least I have more details.

**Comment by anubhav94** [comment]
Thanks @robertpitt !
