### ISSUE TITLE
Don't rerun helpers when an #each cursor limit changes

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4960]
Earlier discussion: #1672

Simple modified leaderboard demo: http://stackoverflow.com/questions/31997304/how-can-you-prevent-cursor-item-helpers-from-being-rerun-when-the-limit-changes

@avital: "Here's why this is the behavior: When the argument to {{#each}} changes between different cursors, we treat the transition as if it is a change between two arrays. Since {{#each}} works with arbitrary arrays, we don't diff the items in the array. Instead, we inform all of the rendered items that their contents have changed (even though they likely haven't). This means many helpers will fire but their contents will stay the same."

In my app, I have a list with infinite scroll. Each list item has helpers that make minimongo queries that take time to run (from the flamegraph, it looks like the most expensive one is `.count()`). The time it takes to render item n + 1 is larger than the time it takes to render n, because it must rerun all helpers of the previous n items. For example on desktop Chrome, 130ms when changing the limit from 1 to 2, 334ms for 10 to 11, 539ms for 20 to 21. In production my app is run in UIWebView, with a JS runtime much slower than desktop, which means each time the user scrolls down, the app is frozen for seconds. 

@dgreensp in 2013 "It's beyond the scope of any current work to detect the case where a cursor reactively changes to a different query yet we can be sure some of the documents haven't changed."

It sounded like this is a feature MDG would like – would you accept a PR? If yes, what's a guess at the magnitude, and can you point me in the right direction for implementation? 🙏😃 cc @Slava

**Comment by lorensr** [comment]
Wherever in the Blaze code the `#each` notices a new cursor, can it compare it to the last cursor to see whether the query has changed or just the limit? And then if just the limit changed, don't invalidate the old items?

If it's not that simple, perhaps an easy first-version solution would be a way to manually tell Blaze, instead of Blaze figuring it out itself, like:

```coffeescript
  'scroll .list': (e, tmpl) ->
    tmpl.limit.set tmpl.limit.get() + 1
    tmpl.dontInvalidateOldDataInEachClosestTo e.currentTarget
```

**Comment by dgreensp** [comment]
As a practical solution, you could cache the count somewhere, like on the template instance.  This is what we've seen in React, that you start by recalculating everything all the time, which gives you guaranteed correctness and simple code, and then you deal with performance issues by caching or memoizing, either in the component state itself or in some object inside or outside the component.

The elegant solution in the framework would be to make minimongo smarter, giving it the intelligence to reuse materialized query results.  You could imagine a minimongo that internally keeps ReactiveArrays of some sort that are updated incrementally and sliced and projected as needed for the purposes of queries.

**Comment by lorensr** [comment]
Thanks! The `.count()`s aren't actually on the `Items` cursor, but on other associated collections, like up/down votes and comments. My first caching method below isn't pretty. The second is nicer, but is there any way to modify helpers or Tracker to inform the helper why it's being called? 

## General Caching Solution

### Autorun invalidation
The override isn't practical, just an example second type of reactive dependency.
```coffeescript
Template.item.cachedHelpers
  numComments: 
    helper: ->
      console.log 'side effects'
      Session.get('override-' + @_id) or Comments.find(item: @_id).count()

    invalidate: ->
      Session.get('override-' + @_id)
      Comments.find(item: @_id)
```
turns into:
```coffeescript
Template.item.onCreated ->
  @autorun =>
    @numComments = undefined
    Session.get('override-' + @data._id)
    Comments.find(item: @data._id)

Template.item.helpers 
  numComments: ->
    cachedValue = Template.instance().numComments
    if cachedValue? 
      return cachedValue

    console.log 'side effects'
    Template.instance().numComments = Session.get('override-' + @_id) or Comments.find(item: @_id).count()
```

### With tracker context
If something like `Tracker.invalidationSource` was a thing:
```coffeescript
Template.item.helpers
  numComments: ->
    # or if Tracker.invalidationSource in [Session, Comments]
    if Tracker.invalidationSource is Items and Template.instance().numComments?
      return Template.instance().numComments

    console.log 'side effects'
    Template.instance().numComments = Session.get('override-' + @_id) or Comments.find(item: @_id).count()
```
## Elegant Smart Minimongo Solution

This would nice, not only because no extra work needed by dev, but also because even when everything is cached and helpers return immediately, it still takes time for Blaze to call all the helpers and check the return values to make sure they haven't changed.

**Comment by dgreensp** [comment]
For a caching solution, I would store the count in a `ReactiveVar`.  That way, you don't need any side effects in the helper when you get the current count.

**Comment by lorensr** [comment]
Oh great thanks, that works better. The below is what you had in mind, right? Funny to be moving all my templates into autoruns :) Still doesn't have local data context, but that can be fixed by extracting everything inside an `#each` or `#with` into new templates.

```coffeescript
Template.item.onCreated ->
  @numComments = new ReactiveVar 0
  @autorun =>
    @numComments.set Comments.find(item: @data._id).count()

Template.item.helpers
  numComments: ->
    Template.instance().numComments.get()

**Comment by lorensr** [comment]
For anyone interested, this is the same technique used by Blaze Plus: https://kadira.io/blog/meteor/introducing-blaze-plus-the-next-generation-of-blaze

**Comment by mitar** [comment]
Yes, this is the pattern we use a lot in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) where one attach custom reactive variables on to the component instance. And because component instance is accessible from the template, this works exactly as expected.

Useful packages for this are then also:
* https://github.com/peerlibrary/meteor-reactive-field (to not have to write `.get` in the template)
* https://github.com/peerlibrary/meteor-computed-field (for memoization)

**Comment by lorensr** [comment]
Nice, thanks!

**Comment by mitar** [comment]
Also, related to your issue is probably #4073 as well. The issue is that Blaze by default uses a very conservative equality function for reactive vars, which is used for data contexts. And because all template helpers are by default bound to the data contexts it means that they are invalidated even if data contexts in some other semantics stayed equal. In Blaze Components though we do not bind template helpers to data context automatically, but only if you call `this.data()`. This allows you to wrap `this.data()` call into a memoization or some [other thing](https://github.com/peerlibrary/meteor-computed-field) which for example uses different equality function and thus less often invalidates surrounding computation.
