### ISSUE TITLE
Log out notice annoying during development

### ISSUE THREAD

**Issue by AnthonyAstige** [meteor/meteor#4962]
I clone my live db to local development very often, and every time this error is logged to console:

> Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]

I know this is 'my own fault' I'm seeing the error, but I wish there were a way to suppress it.

**Comment by AnthonyAstige** [comment]
Hacked suppression @ https://github.com/AnthonyAstige/meteor/commit/a96d120dad8efbecf85ca3f1b8d5b3091d1505d9

I don't know what I'm doing in this accounts-base package and likely could have broken something.  Just using this on my local so I don't see the error anymore.

**Comment by AnthonyAstige** [comment]
Hacked suppression to work with 1.1.0.3 @ https://github.com/AnthonyAstige/meteor/commit/9b6faf46d1db8564f9a545fea488ad864a750068

**Comment by stubailo** [comment]
@AnthonyAstige hey, I'm sorry that you find this log message annoying. But I think it can be informative for people looking at production server logs. Is there a particular feature you are looking for to suppress these kinds of log outputs? What would it look like to use this feature from the developer's point of view?

**Comment by AnthonyAstige** [comment]
@stubailo No worries, I can completely understand why the message could be helpful in debugging.

I think it would be helpful if there was a configuration option to turn these messages off or on.  Maybe grouped into a general 'debug mode' setting.  I'm not extremely familiar with the package so I can't say which config option to merge into / exactly how to fit in, or for certain if the default would be best left showing or not showing.  If it is left showing a note or link to a page explaining how to disable would be nice to include in the message.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Log%20out%20notice%20annoying%20during%20development&body=Migrated%20from:%20meteor/meteor%234962) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
