### ISSUE TITLE
Print more information about the HTTP call when there is an error

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4966]
It would be really nice if there was some way to determine the exact url being fetched especially when theres an error.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This would be a great candidate for a pull request to the [HTTP package](https://github.com/meteor/meteor/tree/devel/packages/http).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Print%20more%20information%20about%20the%20HTTP%20call%20when%20there%20is%20an%20error&body=Migrated%20from:%20meteor/meteor%234966) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
