### ISSUE TITLE
Meteor doesn't log module startup calls, or have a structured way for modules to call process.exit.  Print what modules are bootstrapping in `meteor --verbose`

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#4967]
Hi, I ran into this [bug](https://github.com/Wylio/meteor-winston-papertrail/issues/3).

This library was calling process.exit(1) w/o a log message to explain why.  It caused Meteor startup to repeatedly crash.  See [also](https://forums.meteor.com/t/debugging-exited-with-code-1/8464].

Is there a way to have a better crash report?  Thanks!

Mike

**Comment by stubailo** [comment]
This might require more Node.js hackery than it's worth, especially because it seems to me like primarily a bug in that package, but could certainly be fixable. Looks to me like a good candidate for a pull request.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by MichaelJCole** [comment]
Hey @stubailo, somewhere Meteor is bootstrapping in the module.  It would be nice if those bootstrappings were logged with --verbose.  That way there would be a module to blame :-)

Also, way better title for the bug  +1

Mike

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20doesn't%20log%20module%20startup%20calls%2C%20or%20have%20a%20structured%20way%20for%20modules%20to%20call%20process.exit.%20%20Print%20what%20modules%20are%20bootstrapping%20in%20%60meteor%20--verbose%60&body=Migrated%20from:%20meteor/meteor%234967) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
