### ISSUE TITLE
Update Meteor.user() when user has been logged out by the server

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4968]
1. Login to Browser A and login to Browser B, Tab 1
2. In Browser A, call `logoutOtherClients`
3. In Browser B, if you open Tab 2, you get the expected error: `Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`
4. However, in Browser B, Tab 1, `Meteor.user()` and `Meteor.userId()` have not changed.

**Comment by avital** [comment]
Yeah, you're right. The way Meteor manages users is that certain methods are called in a special way (`Accounts.callLoginMethod`) and expect to get a return value that includes the user id. Then the Meteor client updates its local record with the new userId. A new tab automatically tries to log in with the resume token so you get the error you describe and the user isn't logged in. But with the way login-over-DDP is designed at the moment, there's no way for an open tab to know that it's been force-logged out.

If this is very important for you, you could as a workaround try to "log in" once in a while by passing in the resume token you should have available in the accounts package. Or maybe you could expose a subscription to notify the client that its token is no longer valid.

**Comment by avital** [comment]
Oh sorry, I may have gotten this wrong. There's code in accounts_server.js that uses `observeChanges` to detect when a user's login token has changed and closes the DDP connection. The client is supposed to respond by reconnecting, then trying to log in with the same stored login token which would then fail.

So I'm now confused about this and we may have a bug.

**Comment by lorensr** [comment]
Not very impt, thanks – just a suggestion.

Should I make a simple repro, or did you already confirm?

**Comment by avital** [comment]
I have not yet confirmed.

**Comment by lorensr** [comment]
I apologize, I'm unable to replicate. No idea what in my app would be preventing my DDP connection from being closed.

**Comment by lorensr** [comment]
Also, when I call `this.setUserId` on server, `Meteor.user/Id()` changes correctly on server but not on client.

**Comment by avital** [comment]
@lorensr yes, that's the design. the user id updates on the client only when the client calls `Accounts.callLoginMethod`

**Comment by lorensr** [comment]
Oh, good to know, thank you!

**Comment by lorensr** [comment]
So others know, PR for adding to docs: #5078
