### ISSUE TITLE
/client/server should load on client

### ISSUE THREAD

**Issue by LordRalex** [meteor/meteor#4969]
If you define a /client/server path, then the files are not loaded during execution.

We use meteor to define a server management site, and so using a http://siteurl/server path + folder structure makes sense to use, however after working on it, we found that all of our files in the /client/server folder were not loading up.

We created an index.js with the following code to confirm:

``` code
if(Meteor.isClient) {
    console.log("client");
}
if(Meteor.isServer) {
    console.log("server");
}
```

When the folder path is /client/servers, "client" is correctly logged to the console, and "server" is not, which is the expected result.
However, when the path is /client/server, "client" does not get logged, nor does "server".

I am testing this using Meteor 1.1.0.3 on Windows 10.

**Comment by laosb** [comment]
That's must be a bug about the file path.

**Comment by LordRalex** [comment]
Well, after re-reading the docs, it appears this is actually intended:

http://docs.meteor.com/#/full/structuringyourapp
"Any directory named server is not loaded on the client."

This seems a bit.... cruel to be implementing, as now a folder name cannot be used ever. I do think that there needs to be some "freedom" in it. This server/client stuff should be top-level really, because you can very easily (and not realize it) create unreachable files.

**Comment by stubailo** [comment]
@LordRalex unfortunately, this is a downside of having magic directory names - it means that some directory names are not available to use freely.

A popular way to structure one's app involves using client/server directories not at the top level, like so:

```
apples/lib/               # code for apple-related features
apples/client/
apples/server/

oranges/lib/              # code for orange-related features
oranges/client/
oranges/server/
```

This means that until we offer a way to customize the directory loading rules, we won't be able to change what happens in this case.

However, it might be a good idea to actively try to identify this case and print a warning for it, would that help?

**Comment by LordRalex** [comment]
A warning would help greatly at least. It was not something I expected, and since it was in /client, I had expected siblings to get loaded as the client.

I do think that if a "scope" is defined, then it is applied to sub-folders, regardless of their name.

That should handle the case of the apples scenario like above being handled correctly, and the case where you have subfolders with the magic name being handled as expected.

So, in essence
```
apples/server/           # folder is server side, and all folders in it are loaded as such
apples/server/client   # because parent is server side, client is also server-side
```

That would be the ideal solution to me, because it resolves the issue of just 'plain' magic names, but still keeps the concept as designed.

**Comment by stubailo** [comment]
I think adding a warning about this would be a great first step.

**Comment by ffxsam** [comment]
I hit a bug (#7153) with this too. I was importing from `/imports/startup/client/routes.js` and getting errors, though only with `meteor test`. Just running my app via `meteor` worked perfectly, which is really strange. So this is definitely unexpected behavior.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%2Fclient%2Fserver%20should%20load%20on%20client&body=Migrated%20from:%20meteor/meteor%234969) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
