### ISSUE TITLE
User not logged in on reconnect after failing to login as another user

### ISSUE THREAD

**Issue by brettle** [meteor/meteor#4970]
If a logged in user fails in an attempt to login as a second user, then they will remain logged in as the first user (as expected), but if they ever reconnect, they will not be logged in again.

Reproduction:

```sh
[brettle@localhost tmp]$ git clone https://github.com/brettle/login-failure-breaks-reconnect
Cloning into 'login-failure-breaks-reconnect'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 16 (delta 3), reused 16 (delta 3), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
[brettle@localhost tmp]$ cd login-failure-breaks-reconnect/
[brettle@localhost login-failure-breaks-reconnect]$ meteor
[[[[[ ~/tmp/login-failure-breaks-reconnect ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

Visit http://localhost:3000/ and view the log that is displayed.

I believe the problem is [this line](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L140) in `accounts_client.js` where `connection.onReconnect` is being set to `null` when a login failure occurs. I believe it should be left untouched in that case and only set to `null` on logout. I'll work on a PR that does that.

**Comment by brettle** [comment]
In addition to the pull request that fixes this, I've created the [brettle:workaround-issue-4970](https://atmospherejs.com/brettle/workaround-issue-4970) package which provides a workaround for anyone using a Meteor release where this isn't fixed.

**Comment by glasser** [comment]
Thanks, merged!  It doesn't look like I thought very carefully about this error case when I wrote this code ages ago.
