### ISSUE TITLE
User is logged out by server when page is refreshed with accounts package and DDP.

### ISSUE THREAD

**Issue by fatihacet** [meteor/meteor#4972]
I have two meteor apps. First one is the backend and the second one is the web/ios app. I want my ios app to use the backend app's Mongo instead of its own. To make it work I created a DDP connection and set it as Accounts.connection. Now, register and login seems work fine but when I refresh the page Meteor server logs me out with the following error.

> Error logging in with token: Error: You've been logged out by the server. Please log in again.

I created a repo to demonstrate the issue I have. [Here](https://github.com/fatihacet/meteor-accounts-ddp) you can find the repo and check the code. 

Here is screencast of the issue.

![http://recordit.co/w01xUBzPoV](http://g.recordit.co/w01xUBzPoV.gif)

If I put a breakpoint into `accounts-base.js:158` and set `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` to my DDP url it works fine.

![http://f.acet.me/qbh6.png](http://f.acet.me/qbh6.png)

I am not sure this is a Meteor bug or I am missing something. Any comments ?

**Comment by sjmcdowall** [comment]
Just out of curiosity -- since the main object of Meteor is to allow a single "app" to have both server and client code in the same "project" -- why is your app split into 2 parts?  Why the separation of client code and server code.. just wondering what the use case is.

**Comment by fatihacet** [comment]
Actually the idea is separating mobile and web app. Web app will have it's own `client` and `server` directories and mobile app will connect to web app's `server` using DDP.

**Comment by stubailo** [comment]
@fatihacet I think what is happening is that your code to change the Accounts connection is actually running after the code that logs you in on startup is executing. So it's trying to log you in on the old connection, which isn't working.

You can fix this right now by putting:

```
__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = "the_url";
```

somewhere in your app's server-side code. This value is then propagated to the client.

In Meteor 1.2, there will be better APIs for managing Accounts connections, so hopefully you can switch to using those when they are available.

**Comment by fatihacet** [comment]
@stubailo thanks for your help. It seems it's working fine now.
