### ISSUE TITLE
"Uncaught Error: object missing from query" on connection: null connections

### ISSUE THREAD

**Issue by frozeman** [meteor/meteor#4976]
Once in a while i get the following error:
```
Uncaught Error: object missing from query             collection.js:582
```

I only use unmanaged collections using `connection: null`.

I assume a race condition, as i re-load data from local storage back into the collection when the app loads, e.g. here in my [persistent-minimongo](https://atmospherejs.com/frozeman/persistent-minimongo) package:
https://github.com/frozeman/meteor-persistent-minimongo/blob/master/persistent-minimongo.js#L133

Any idea what could cause the error?

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

It's hard to tell what is causing the problem without being able to run the code.

**Comment by frozeman** [comment]
I couldn't yet reproduce it in a plain repo, but maybe the following stack trace helps.
**Could somebody from MDG explain me in which case, this error could appear?**
```js
Uncaught Error: object missing from queryLocalCollection._findInOrderedResults @ minimongo.js:941LocalCollection._updateInResults @ minimongo.js:885LocalCollection._modifyAndNotify @ minimongo.js:822(anonymous function) @ minimongo.js:715LocalCollection._eachPossiblyMatchingDoc @ minimongo.js:602LocalCollection.update @ minimongo.js:710_.each.Mongo.Collection.(anonymous function) @ collection.js:586updateTransaction @ observeTransactions.js:99(anonymous function) @ observeTransactions.js:194(anonymous function) @ /Users/frozeman/Sites/_ethereum/mist/node_modules/web3/lib/web3/method.js:142(anonymous function) @ /Users/frozeman/Sites/_ethereum/mist/node_modules/web3/lib/web3/requestmanager.js:94(anonymous function) @ /Users/frozeman/Sites/_ethereum/mist/node_modules/web3/lib/web3/ipcprovider.js:77(anonymous function) @ /Users/frozeman/Sites/_ethereum/mist/node_modules/web3/lib/web3/ipcprovider.js:61emitOne @ events.js:77emit @ events.js:169
```

The part which throws that error is:
```js
LocalCollection._findInOrderedResults = function (query, doc) {
  if (!query.ordered)
    throw new Error("Can't call _findInOrderedResults on unordered query");
  for (var i = 0; i < query.results.length; i++)
    if (query.results[i] === doc)
      return i;
  throw Error("object missing from query");
};
```

**Comment by frozeman** [comment]
The error also appears on `Collection.remove` some times:
```js
Uncaught Error: object missing from query
    at Error (native)
    at Function.LocalCollection._findInOrderedResults (http://localhost:3050/packages/minimongo.js?cdf1a26cf7719fa9471a8017c3defd5aea812727:977:9)
    at Function.LocalCollection._removeFromResults (http://localhost:3050/packages/minimongo.js?cdf1a26cf7719fa9471a8017c3defd5aea812727:896:29)
    at http://localhost:3050/packages/minimongo.js?cdf1a26cf7719fa9471a8017c3defd5aea812727:701:23
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3050/packages/underscore.js?fa590de5090ceb4a42555b48562fd8f8e7035758:157:11)
    at LocalCollection.remove (http://localhost:3050/packages/minimongo.js?cdf1a26cf7719fa9471a8017c3defd5aea812727:697:5)
    at _.each.Mongo.Collection.(anonymous function) [as remove] (http://localhost:3050/packages/mongo.js?5dcfbae63393ea63b330ea0c46d7b41eb1b4c3ae:671:47)
    at http://localhost:3050/app/client/lib/ethereum/walletConnector.js?e7f554d1733a921a3cc1ce80c4f243a822b62462:100:22
    at Array.forEach (native)
```

**Comment by stubailo** [comment]
> iterate over all documents and call Collection.remove(_id)

It could be a matter of modifying a collection while iterating over it. Try doing the operations asynchronously? So first iterate and make an array of IDs, then iterate over the array and call remove?

**Comment by frozeman** [comment]
It happens on more complex stuff, while many things are updated, but it also happens when i call plainly this:
```js
    _.each(Transactions.find().fetch(), function(tx) {
        Transactions.remove(tx._id); 
    });
```

And here i'm for sure does nothing else. So its a weird error.
I believe that through some of the more heavy operations in the `Transactions` collection it breaks it internally or something..

**Comment by stubailo** [comment]
Sorry, I haven't encountered this myself so I can't really help you unless there is a way to reproduce the issue.

**Comment by frozeman** [comment]
But could you tell me at least in which case this error could be thrown? Like whats necessary that this happens?
