### ISSUE TITLE
Proposal for naming conventions regarding templates

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#4978]
One thing that confused me a lot is Meteor's naming convention regarding ```Template.name```.

I always thought that this construct describes a template instance, since the "name" is written in lower case letters. What contributes to this confusion, is the following statement in the docs:

"When you write a template as ```<template name="foo"> ... </template>``` in an HTML file in your app, Meteor generates a "template object" named Template.foo."

This might be true internally, but in fact Template.name seems to define a Template class, at least from a conceptional point of view. A first hint on that is this sentence:

"The same template may occur many times on a page, and these occurrences are called template instances."

So, according to Meteor's terminology, we're having a "Template object" that may occur many times on a page and thus has "instances". Huh?

It's getting more confusing when these instances come into play, as they have their own methods, like ```.findAll()```.

To make the conceptional differences clearer, I would like to recommend to call Template.name a "template class" rather than a "template object", and consequently use this notation: ```Template.Name```, according to JavaScript conventions.

Of course, I'm pretty aware that the "name" is just an identifier that can be deinfed in the ```<template name="">``` attribute, but it IMHO the API would be much clearer if class-like things would be called class in the documentation and object-like things would be called objects (or instances).

Alternatively, one could stick to the JavaScript terminology and use the concepts "Prototype" and "Object", but since ES6 is introducting "Classes" and Meteor wants to switch to this new standard, I would prefer the latter.

Switching to this naming convention would, for instance, also make much clearer why ```this``` inside a ```onCreated()``` refers to the template instance - if you think of ```onCreated()``` as being a class method, this becomes quite obvious.

PS: Please correct me if I got things wrong, but these terminology glitches confused me a lot. At least, I think so, I'm still not 100% sure if I understood everything right. :-)

**Comment by stubailo** [comment]
This makes a lot of sense, and it would be really great to be able to define templates as ES2015 classes. Like you said, the documentation mentions "instances" and the thing that creates that should be called a "class".

If we update the Blaze API soon, I think this would be a great change to make.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by derwaldgeist** [comment]
You're welcome, I'm glad if I can help making Meteor even better!

**Comment by mitar** [comment]
This is also the approach we took in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components). Components are recommended to start with an upper-case letter, while templates with lower.

**Comment by mitar** [comment]
I am closing this in favor of https://github.com/meteor/blaze/issues/98, which is trying to make templates a proper classes, and then we will hopefully have also more consistent naming.

**Comment by mitar** [comment]
Also, the idea is that we deprecate the use of global `Template.<name>` registry, but `<template name="Foo"> ... </template>` would simply define a class of name `Foo`, which would then be available for importing.
