### ISSUE TITLE
Tinytest silently ignores all tests on uncaught errors

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4979]
**_1 Upvote**_ 

```sh
git clone git@github.com:iDoRecall/email-normalize.git
git checkout 64b18f371d8d3f7d62d6821a46d4ef62b752472d
cd email-normalize
meteor test-packages ./
```

Notice that apparently everything went ok. At a closer examination, only `S`erver tests have been run, despite `pacakge.js` including the test on both client and server.

This is caused by the uncaught ReferenceError: `Npm is not defined` on the client, which halts the tests. Would it be possible to catch [this type of case](https://github.com/iDoRecall/email-normalize/issues/1#issuecomment-132132536)?

**Comment by anubhav94** [comment]
@dandv Thanks for catching this! This is a really good point and we'll definitely add it as a bug to track and fix in the future. Unfortunately, right now we're working on other projects and so as always, pull requests are welcome and encouraged!

**Comment by savvopoulos** [comment]
+1. This seems like a serious problem, given that the point of tests is too catch errors.
I've been bitten by this many times.

How can we fix this? Happy to send a PR if you give me some pointers.

**Comment by Maxim-Filimonov** [comment]
I did some preliminary investigation of the issue today. According to what I found error actually happens before tinytest kicks in.
Tinytest tests are injected a generated file "local-test_*package_name*" created by the test runner. The file has a bunch of imports at the top including the import of a package under test which is where the exception occurs. Those imports are not wrapped into any error handling logic which causes interpolation of the whole file to fail and leads to tests not being executed.
The simplest thing, I can think of is to change generator of the file to wrap imports into error handling logic and on failure product a single failure which displays the exception.
Thoughts ?

**Comment by Maxim-Filimonov** [comment]
Ok some after further investigation maybe someone from MDG can at least confirm the direction. Generation of the test file happens through standard linker and it doesn't look like there is an easy way to extend that generation without touching linker directly, which I would rather avoid. 
I have double checked that tinytest ignores tests only when error occurs in client tests. On error during server tests standard meteor error handler kicks in. Based on that I'm thinking to just use window.onerror to catch an exception while tests are running and then to create a failure with that exception which will fail the build.

**Comment by hwillson** [comment]
PR #9034 should help with this:

![screenshot 2017-08-22 09 24 27](https://user-images.githubusercontent.com/137740/29570969-01f6aa6c-8726-11e7-9448-551abd69751e.png)
