### ISSUE TITLE
_ensureIndex doesn't provide a contextual error

### ISSUE THREAD

**Issue by nathanhornby** [meteor/meteor#4982]
I'm currently struggling to provide an appropriate error message when a user provides a value already taken in a field that has an `_ensureIndex` applied to it, as seen in this question on SO: https://stackoverflow.com/questions/32070336/how-to-get-a-better-error-message-from-meteor-in-the-case-of-an-invalid-db-updat

```
Meteor.startup(function() {
  Meteor.users._ensureIndex('profile.uri', {unique: 1, sparse: 1});
});
```

As the error generated by Meteor is just a 500 error:

> M…r.m…e.errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}

Assuming there isn't a way to handle this - I'd suggest there should be - as currently I can't consistently provide a contextual error for the end user without assuming that all 500 errors are due to `_ensureIndex` matches.

**Comment by stubailo** [comment]
@nathanhornby are you referring to the error provided on the client? If you write a Method, you should be able to use try/catch to get an informative error:

```js
Meteor.methods({
  "updateProfileUri": function (newUri) {
    try {
      Meteor.users.update(Meteor.userId(), {
        $set: {
          "profile.uri": newUri
        }
      });
    } catch (e) {
      // e should be an informative error
    }
  }
});
```

If you are doing the update from the client directly, we decided it would be a security issue to ship informative errors about the database to the client by default. I would suggest writing a method.

**Comment by nathanhornby** [comment]
I am indeed using a method so this looks like the way to this kind of error - thanks for the help!

**Comment by Aralun** [comment]
@nathanhornby Do you have any more meaningful data that way than before?

**Comment by nathanhornby** [comment]
Kind of...

I have a client side check in place now which handles the friendly error using jquery validation, so what this returns isn't hugely important for me now.

But if I were to rely on it I'd have to do some string parsing I guess. But it's certainly better than a 500 error!
