### ISSUE TITLE
Microservice Infrastructure

### ISSUE THREAD

**Issue by mortaliorchard** [meteor/meteor#4984]
For all companies that are adopting the microservice infrastructure, all frontend components are gathering their data from multiple apis. The way Meteor is build closely couple the collections with one mongodb layer (for the benefits of being highly reactive).

The tutorials that are highlighting how to link an API always use a Mongo.Collection (so `this.added` behaves as expected). It seems like this method doesn't store (at least now) the objects created. However, is there a way to build our own Collection mechanism: so all create, read, update, and delete operations can be forwarded to a distant API?

**Comment by stubailo** [comment]
This is indeed very possible! You just need to specify the right publications and methods in your app server. I think this would be a great discussion to have on the Meteor forums: https://forums.meteor.com/
