### ISSUE TITLE
Support Npm.depends on scoped npm packages

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#4985]
**_3 Upvotes**_ This is a feature request for being able to `Npm.depend` on [scoped npm packages](https://docs.npmjs.com/getting-started/scoped-packages). Right now doing so throws a "404 Not found" when updating the npm dependencies for a Meteor app.

This is a request for supporting scoped packages that are publicly accessible. Private would be great too, but that can be a separate issue

**Comment by stubailo** [comment]
This sounds like something we should really support! Thanks for posting about it here.

If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by Sanjo** [comment]
To support this, you just need to upgrade npm to a newer version. I don't know which version the devel branch currently uses.

As a temporary workaround, you can currently install the newest version of npm with:

```sh
cd ~/.meteor/packages/meteor-tool/1.1.4/mt-*/dev_bundle/lib
../bin/npm install npm
```

This also works on the build machines.

**Comment by Sanjo** [comment]
I need to say that the support for this is quiet important. Currently npm packages that are scoped packages or have dependencies on scoped packages are not usable.
This results in a very bad experience for Meteor package developers or people who use those npm packages with Meteor in general.

**Comment by stubailo** [comment]
@Sanjo I understand, thanks for re-emphasizing.

**Comment by lourd** [comment]
Where is Meteor's npm version declared? I'm looking through the source but can't find it.

**Comment by lourd** [comment]
`scripts/dev-bundle-tool-package.js`. Trying this now, just bumped it to 2.13.5. Ran `generate-dev-bundle.sh` and got this:

```sh
Unexpected NPM version in lib/node_modules: 2.13.5
We will be replacing it with our own version because the bundled node
is built using PORTABLE=1, which makes npm look for node relative to
its own directory.
Update this check if you know what you're doing.
```

I've never been into the tool code, this is interesting.

It looks like we can use a standard npm version instead of Meteor's fork because [@glasser's PR](https://github.com/npm/npm/pull/5821) got into master on npm a while ago.

It says update this check if you know what you're doing... fake it till you make it, right? :stuck_out_tongue_winking_eye: Gonna keep hacking around

**Comment by lourd** [comment]
`scripts/generate-dev-bundle.sh` is an interesting read... I'm not sure what y'all are doing [here](https://github.com/meteor/meteor/blob/devel/scripts/generate-dev-bundle.sh#L70-L90) and [here](https://github.com/meteor/meteor/blob/devel/scripts/generate-dev-bundle.sh#L176-L190). Need more info on the npm version choices before a PR is possible

**Comment by lourd** [comment]
Would be *really* nice to get npm upgraded for 1.2. Happy to jump on this, just need some illumination on the spots in the code I mentioned a few weeks ago

**Comment by stubailo** [comment]
@benjamn I think you're on this, right?

I don't think we'll be able to do it for 1.2, but almost certainly for the next version. And I bet the next release will take less than 4 months to come out, my personal hope is that we can get it down to 1 month or so.

**Comment by sclausen** [comment]
Fixing this would be a requirement to use`angular@2.0.0-alpha.38`

**Comment by MilosStanic** [comment]
+1 for the reason of Angular2.alpha38

**Comment by dalcib** [comment]
+1 It is needed to install ```reactivex/rxjs```

**Comment by stubailo** [comment]
@Urigo what's your perception on this issue?

**Comment by MilosStanic** [comment]
Just want to ping @Urigo about this issue. He probably forgot, I see he's been overloaded a bit :)

**Comment by sclausen** [comment]
@MilosStanic: If you want Urigos perception, because of the Meteor-Angular2 issue, it's actually @barbatus who develops it.

**Comment by MilosStanic** [comment]
@sclausen I know, but @stubailo was asking @Urigo to comment.

**Comment by sclausen** [comment]
@MilosStanic sorry, I may be wrong, but it sounded like he wanted @Urigo s perception because of his experience of developing Meteor-Angular2. Urigo doesn't seem to be involved in the development of Meteor-Angular2. He is in fact the owner of the repository, but hasn't commited any code, nor commented any issues. Maybe he still is the wise silent spectator though. I just wanted to point out, that if @stubailo wanted his perception in a Meteor-Angular2 context, maybe @barbatus would be the right contact to ask. I could be totally wrong and stubailo wanted a general perception of the npm situation from him, and/or Urigo is actually in the know of Meteor-Angular2, though.

**Comment by Urigo** [comment]
Hi and sorry for the late response.
@stubailo we can work around that manually inside the package.
It will be hard and ugly, but probably doable.
My opinion is that we will probably going to see a growing number of those issues as more and more NPM package use that feature.
It's true that `Angular 2` and `rx` has the tendency to use very early features, it look like this feature is growing in popularity, specially since all Npm's private modules are scoped.
So I wouldn't look on this issue as a `Angular2.0` issue but from a larger perspective and for that I think @benjamn will know better how this feature relates to our current path.

**Comment by Urigo** [comment]
@sclausen @MilosStanic you can still contact me for anything, @barbatus work is a great help, but as an addition, not subtraction :)

**Comment by sclausen** [comment]
Hello Uri,

I really didn't want to deny your expertise. I'm really sorry, as a non 
native english speaker, it is a bit difficult for me to find the right 
words for what I really meant.

On 08.10.2015 17:45, Uri Goldshtein wrote:
>
> @sclausen <https://github.com/sclausen> @MilosStanic 
> <https://github.com/MilosStanic> you can still contact me for 
> anything, @barbatus <https://github.com/barbatus> work is a great 
> help, but as an addition, not subtraction :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/meteor/meteor/issues/4985#issuecomment-146583665>.
>
>
-- 
Mit freundlichen Grüßen
Sebastian Clausen

**Comment by aramk** [comment]
+1 In the meantime updating the npm version in meteor-tool as @Sanjo mentioned seems to work well.

**Comment by aramk** [comment]
I hear Meteor 1.3 had been released. Does it by any chance update npm to a version which supports scoped packages?

**Comment by aramk** [comment]
Meteor 1.3 uses npm 2.14.22 so scoped packages work fine. I think this issue can be closed 😀

**Comment by abernix** [comment]
As reported above, this was fixed when Meteor upgraded its version of NPM.  Thanks for reporting this originally! :smile:
