### ISSUE TITLE
Meteor 1.2 preview creates mystery parallel folders on Windows

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#4990]
For some reason, ES6 code did not work in my app when I tried it on Windows. I found the following very mysterious situation. My app is located in the following directory:

![image](https://cloud.githubusercontent.com/assets/2080084/9345680/630760e0-45e1-11e5-824b-8a510728704d.png)

However, after running the meteor tool, the following evil doppleganger directory appears:

![image](https://cloud.githubusercontent.com/assets/2080084/9345692/8badc93a-45e1-11e5-8fad-b94b6b6f2d0b.png)

Notice the strange path `C:\C\Users\...` instead of `C:\Users\...`. The only files in this evil twin directory are buried in this folder: 

![image](https://cloud.githubusercontent.com/assets/2080084/9345715/c1411520-45e1-11e5-9021-6bea9cb12c57.png)

On the other hand, the real `plugin-cache/ecmascript/0.1.3-plugins.1` directory is empty: 

![image](https://cloud.githubusercontent.com/assets/2080084/9345729/f88f86c4-45e1-11e5-81bb-4f2e69e1e7d9.png)

If I had to guess, I would imagine that the new plugin compiler is missing a colon somewhere. That would lead it to create and use the path `C/Users` as opposed to having `C:` refer to the disk and going into the proper path.

To reproduce this, just clone an app made with `PLUGINS-PREVIEW@2` and the `ecmascript` package, then run the meteor tool on Windows. The folder appears. **If I stop meteor, delete this folder, and run meteor again, it comes back.**

This does seem to cause mysterious problems in my app where it loads but some code is not working properly.

**Comment by stubailo** [comment]
@benjamn I think we didn't do a `files.convertToOSPath` when setting the cache dir for babel, or something.

Thanks for the report!
