### ISSUE TITLE
Client to client information exchange

### ISSUE THREAD

**Issue by Goatic** [meteor/meteor#4992]
HI guys - How would you suggest handling client to client exchange of information? - I'm currently integrating Opentok.js on server/client for my application, and I need some way for a client to pass string-based token to another client, for them to establish a 1-1 call. Security and privacy is kind of a big deal... :) thnx in advance

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by Goatic** [comment]
will do :)
