### ISSUE TITLE
Make dev cluster fully self-contained

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#4994]
I'd like to make it ultra trivial to spin up a dev cluster, do stuff to it, and kill it.  Partially so that we can do this for integration tests from CI; partially just because messing with Mongo passwords is annoying.

Notably this includes:
- Spin up a simple no-auth one-replica Mongo in ECS
- Allocate a bundle bucket in S3

This might also require running our own docker registry, eg with https://github.com/mbabineau/cloudformation-docker-registry

This doesn't have to affect staging/production, just dev clusters.

**Comment by stubailo** [comment]
@glasser wrong repository?
