### ISSUE TITLE
Allow changing the name of the users collection in Accounts

### ISSUE THREAD

**Issue by 466023746** [meteor/meteor#4995]
Meteor.users = new Mongo.Collection("users", {                                                                   // 141
  _preventAutopublish: true,                                                                                     // 142
  connection: Meteor.isClient ? Accounts.connection : Meteor.connection                                          // 143
});   

I want to change it to :

Meteor.users = new Mongo.Collection("wpadmin", {                                                                   // 141
  _preventAutopublish: true,                                                                                     // 142
  connection: Meteor.isClient ? Accounts.connection : Meteor.connection                                          // 143
}); 

because our mongodb has already a collection called users.

but when i use meteor,it becomes :

Meteor.users = new Mongo.Collection("users", {                                                                   // 141
  _preventAutopublish: true,                                                                                     // 142
  connection: Meteor.isClient ? Accounts.connection : Meteor.connection                                          // 143
});   

how can i change it?

**Comment by stubailo** [comment]
Unfortunately, this is currently not configurable. However, you can clone the source code of the accounts package locally into your app's `packages/` directory, and change the name of the collection yourself.

I'll track this here are a feature request.

**Comment by 466023746** [comment]
server/packages  web.brower/packages  web.cordova/packages which?

**Comment by okpatil4u** [comment]
Is there any progress on this one ??

**Comment by Levino** [comment]
Anything?

**Comment by stubailo** [comment]
No progress yet, but there will be some work coming up soon about decoupling the data backend of accounts, and this could probably be part of that. More info soon.

**Comment by raphaelarias** [comment]
I believe for now the workaround is this: https://forums.meteor.com/t/customizing-default-users-collection-name/15428

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20changing%20the%20name%20of%20the%20users%20collection%20in%20Accounts&body=Migrated%20from:%20meteor/meteor%234995) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by Levino** [comment]
Done. https://github.com/meteor/meteor-feature-requests/issues/61
