### ISSUE TITLE
"must use ordered observe" error message is incorrect when using observe in minimongo

### ISSUE THREAD

**Issue by timbotnik** [meteor/meteor#4996]
If you use `.observe()` on a ordered cursor with an `added` callback, you get the following message thanks to https://github.com/meteor/meteor/issues/2766#issuecomment-58974000

```
Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit
```

Although actually what you need to use is `addedAt` (as we are using `.observe()` not `.observeChanges()`). This is pretty confusing as if you switch your `added` to an `addedBefore` it continues to spit out the same error.

Let me know if a reproduction would be useful at all.

cc @tmeasday

**Comment by stubailo** [comment]
Yeah I'd love to see a repro so that we can copy it in the resulting unit test, just to make sure the right problem is tackled.

**Comment by timbotnik** [comment]
@stubailo: repro here https://github.com/timbotnik/meteor-issue-4996
Let us know if you need anything else.

**Comment by hwillson** [comment]
I've confirmed this is still an issue (tested with Meteor 1.5).
