### ISSUE TITLE
Add Github URL to Meteor Core packages

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#5000]
It would be nice if the core packages' `package.js` would link to the Github URL of the `master` (or `devel`?) branch sub-folder that way we can access it via Atmosphere. If you guys are down, let me know which branch you guys want to link to and I can PR it.

P.S - Woot, I claimed issue #5000!

**Comment by stubailo** [comment]
We would definitely want to link to `master`. Does atmosphere support links to subfolders on GitHub?

**Comment by rclai** [comment]
I'm assuming that it does. I remember a package that does link to a sub-folder. Perhaps you can confirm with someone from Percolate?

**Comment by stubailo** [comment]
OK, talked to @zol and links to a subdirectory are currently not supported.

I think the best option would be to add a link to the top of the README, then. Ideally, all of the packages would have the same format:

### accounts-password

Add password-based login to your Meteor app.

[Documentation](http://docs.meteor.com/#/full/accounts_passwords) | [Source code of released version](https://github.com/meteor/meteor/tree/master/packages/accounts-password) | [Source code of development version](https://github.com/meteor/meteor/tree/devel/packages/accounts-password)

---------

Rest of README here

**Comment by rclai** [comment]
Okay that works. Do you guys want PRs for this?

**Comment by stubailo** [comment]
If you have some time, a pr would be awesome!

**Comment by abernix** [comment]
Added `pull-requests-encouraged` label myself because it's already been stated above and I believe it still applies. :smile:

**Comment by hwillson** [comment]
This work was completed in PR #7622 - closing. Thanks!
