### ISSUE TITLE
Add CLI support for Electron/NW.js

### ISSUE THREAD

**Issue by Svenskunganka** [meteor/meteor#5001]
Feature request: Add CLI support for Electron/NW.js

Would be awesome to be able to build Desktop Applications with Meteor via Electron or NW.js. I haven't seen many discussions on this subject yet, so I figured I could start one here.

I've been doing some minor digging into this and there is already some work out there that has some basic support for Electron called ~~[Electrometeor](https://github.com/sircharleswatson/Electrometeor)~~ [meteor-desktop](https://github.com/wojtkowiak/meteor-desktop). Could potentially be integrated in the same way that iOS and Android is integrated with a CLI command to add OSX, Windows and Linux as platforms.

Resources:
https://forums.meteor.com/t/a-meteor-desktop-application/291
http://stackoverflow.com/questions/27787917/building-a-pure-offline-meteor-app/27794917#27794917

**Comment by sjmcdowall** [comment]
As Electrometeor evolves that could be a pretty interesting idea.. Like adding an "Electron" target platform .. which would build an ElectronMeteor app based on your current architecture (can't imagine a cross platform build working..)

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

If someone comes up with some specific changes or some CLI hook that can make Electron easier to use with Meteor, I'd be all for it. Maybe there is some low-hanging fruit that can make the experience much better with minimal changes to Meteor itself.

Adding it directly to the command line tool would make that part of the code much harder to maintain, so I think a full integration would be much further in the future.

**Comment by kachkaev** [comment]
Are there any plans on making this feature built into Meteor? There are a few packages available, but it would be still great to have something like:
```
$ meteor add-platform desktop

$ meteor list-platforms
browser
server
desktop <----- :–)
```

**Comment by jdnichollsc** [comment]
Excellent idea!

**Comment by Svenskunganka** [comment]
@jdnichollsc There is a project called [meteor-desktop](https://github.com/wojtkowiak/meteor-desktop) that seems to be doing this now.
