### ISSUE TITLE
Meteor - Error with Template implementation with ionic

### ISSUE THREAD

**Issue by Leramir1** [meteor/meteor#5004]
So I have been working with meteor and I am currently trying to implement a template inside an ionic-content, and I can't get a simple tutorial example to work. I keep getting an error regarding "Syntax Error: Token '>' not a primary expression" and I am not sure why. Please help or guide me, I would like to know what went wrong and learn from my mistake.
![issue5004](https://cloud.githubusercontent.com/assets/9030394/9398287/6114d7c0-475a-11e5-9cb9-11ef237b158e.png)

**Comment by dahngeek** [comment]
Just wondering, have you tried Meteoric? [Here's the link](http://meteoric.github.io/)

**Comment by stubailo** [comment]
I think you are trying to use angular-meteor? In that case, check out that tutorial: https://www.meteor.com/tutorials/angular/creating-an-app

Anyway, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
