### ISSUE TITLE
is it possible to test packages that use NPM modules?

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#5007]
I have a package that uses an external NPM module and starts with:

```
Meteor.startup(function() {
	var RiveScript = Meteor.npmRequire("rivescript");
})

error => 
? (STDERR) /Users/dc/.meteor/packages/meteor-tool/.1.1.4.uxrxxn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150820-22:19:39.502(-7)? (STDERR) 						throw(ex);
W20150820-22:19:39.502(-7)? (STDERR) 						      ^
W20150820-22:19:39.507(-7)? (STDERR) TypeError: Object #<Object> has no method 'npmRequire'
```

so next i tried  `Npm.require("rivescript");`

which gives:

    > Cannot find module 'rivescript'

also tried

    api.use(['npm-container'], 'server');

should i try the meteorhacks npm package? my understanding is that is only for using npm modules within the application, not within a package (and ideally i don't to wrap more layers of abstraction around this process)

i'm using tinytest, as that seems the only testing option that seems to even remotely work, but maybe it's only designed for self-contained packages?

FWIW I can get the app itself to run, but cowboy style it's impossible to test anything.

So is there any way to test meteor packages that use external modules?

**Comment by zimme** [comment]
`Npm.require` is only available for packages, and you need to specify the npm dependencies in the `package.js` file so that the npm packages are downloaded when using the package. This is done with `Npm.depends({'github': '0.2.4'});` if you were to use the `github` npm package within your Meteor package.

**Comment by sjmcdowall** [comment]
This seems more a "StackOver" question and not for a bug tracking list. 

However, did you try and installing the npmRequire package? 

meteorhacks:npm 

into your project?

**Comment by stubailo** [comment]
I think this is possible, and you can look at some of the core packages in meteor/meteor to see how they do this. However, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
