### ISSUE TITLE
Meteor public directory after build

### ISSUE THREAD

**Issue by Nits7029** [meteor/meteor#5008]
Hello,

I have build my meteor application, and now I want to upload some product's images through FTP. So anyone have idea in which folder I can upload all the images and then I can access it by something like that www.dummy.com/test.jpg

Any help would be appreciated.

Thanks.

**Comment by dhavalrajani92** [comment]
+1

**Comment by JamesMGreene** [comment]
Assuming you have them in your `public` folder....

It appears that the `public` directory ends up as the `{bundle}/programs/web.browser/app` directory once bundled.
 - So a root "favicon.ico" file would be at `{bundle}/programs/web.browser/app/favicon.ico`
 - If you have it in any sub-directories like `images`, then it would be `{bundle}/programs/web.browser/app/images/test.jpg`

**Comment by Nits7029** [comment]
Yes, you are absolutely right, it works if I have added images before meteor build.

But My question is if I add images after meteor build in web.browser/app/images then I am not able to access that image by referring www.dummy.com/images/test.jpg.

**Comment by glasser** [comment]
See previous responses in https://github.com/meteor/meteor/issues/1441#issuecomment-41106210 and https://github.com/meteor/meteor/issues/4022#issuecomment-86754378
