### ISSUE TITLE
Error: Can't find npm module 'bcrypt'.?

### ISSUE THREAD

**Issue by charliegn** [meteor/meteor#5009]
I'm running Meteor 1.1.0.3 locally and out of no where every branch of my project is throwing the same error when Meteor starts up which makes me think that there is something deeper going on that I waned to bring to your attention.  Another one of our production Meteor app is also getting this error?  Any ideas?

_I've cleansed the directory paths to just 'myApp' for security reasons_
```
W20150821-08:26:27.582(-5)? (STDERR)          
W20150821-08:26:27.583(-5)? (STDERR) /myApp/.meteor/packages/meteor-tool/.1.1.3.6mfum3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150821-08:26:27.752(-5)? (STDERR)            				throw(ex);
W20150821-08:26:27.752(-5)? (STDERR)            				      ^
W20150821-08:26:27.752(-5)? (STDERR) Error: Can't find npm module 'bcrypt'. Did you forget to call 'Npm.depends' in package.js within the 'npm-bcrypt' package?
W20150821-08:26:27.752(-5)? (STDERR)     at Object.Npm.require (/myApp/.meteor/local/build/programs/server/boot.js:155:17)
W20150821-08:26:27.752(-5)? (STDERR)     at Package (packages/npm-bcrypt/wrapper.js:1:1)
W20150821-08:26:27.752(-5)? (STDERR)     at /myApp/.meteor/local/build/programs/server/packages/npm-bcrypt.js:21:4
W20150821-08:26:27.753(-5)? (STDERR)     at /myApp/.meteor/local/build/programs/server/packages/npm-bcrypt.js:30:3
W20150821-08:26:27.753(-5)? (STDERR)     at /myApp/.meteor/local/build/programs/server/boot.js:222:10
W20150821-08:26:27.753(-5)? (STDERR)     at Array.forEach (native)
W20150821-08:26:27.753(-5)? (STDERR)     at Function._.each._.forEach (/myApp/.meteor/packages/meteor-tool/.1.1.3.6mfum3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150821-08:26:27.753(-5)? (STDERR)     at /myApp/.meteor/local/build/programs/server/boot.js:117:5
```

Thank you!

**Comment by charliegn** [comment]
FIXED the issue.  I'm curious as to why this ended up being necessary but from this article [accounts-password from meteor breaking because of bcrypt](http://stackoverflow.com//questions/30602244/accounts-password-from-meteor-breaking-because-of-bcrypt#answers-header) I was able to fix the error and the meteor app starting running just fine...

After looking in the `cd programs/server/npm/npm-bcrypt/node_modules/` directory there was **no** `bcrypt`directory present.  So I did the following:
```javascript
cd programs/server/npm/npm-bcrypt/node_modules/
rm -rf bcrypt  // I didn't need to do this step since 'bcrypt' was missing for me
npm install bcrypt
```

**Comment by t3db0t** [comment]
I just had this problem too—completely out of nowhere.  No idea what caused it, but I npm installed bcrypt just as above and it worked.

Kind of disturbing, anyone have any idea what would have caused this?

**Comment by stubailo** [comment]
Interesting - if anyone comes up with a way to reproduce this, I'll take another look.

**Comment by taky2** [comment]
@stubailo I am having the same issue on OSX 10.11.1 and looking into the project directory I can navigate to `.meteor/local/build/programs/server/npm/npm-bcrypt/` inside here I find a broken alias to `node_modules` which doesn't even display as a folder in finder. So I deleted it, created a folder called `node_modules' then found the global hidden .npm directory at `~/.npm/bcrypt` I copied this bcrypt folder and pasted it into the newly created node_modules folder.

**Comment by lfilho** [comment]
This also happened to me, Meteor 1.2.1, OSX, Node 5.0.0.

They I fixed `rm -rf ~/.meteor/packages/npm-bcrypt`.

Then after running `meteor` it downloaded bcrypt again and all was fine.

**Comment by metsak** [comment]
Just happened to me and no idea what triggered it. Running Meteor 1.2.1. Fixed it by restarting server.

**Comment by mmazloum** [comment]
Just got the same trouble, re-running meteor fixed the problem.

How if someone interested here is the error from my terminal : 
W20151126-16:59:37.696(1)? (STDERR)           
W20151126-16:59:37.696(1)? (STDERR) /Users/marwanmazloum/.meteor/packages/meteor-tool/.1.1.10.17jl6pu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151126-16:59:37.697(1)? (STDERR) 						throw(ex);
W20151126-16:59:37.697(1)? (STDERR) 						      ^
W20151126-16:59:37.700(1)? (STDERR) Error: Can't find npm module 'bcrypt'. Did you forget to call 'Npm.depends' in package.js within the 'npm-bcrypt' package?
W20151126-16:59:37.701(1)? (STDERR)     at Object.Npm.require (/Users/marwanmazloum/Desktop/Sites/startup-innovation/.meteor/local/build/programs/server/boot.js:175:17)
W20151126-16:59:37.701(1)? (STDERR)     at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:9:1)
W20151126-16:59:37.701(1)? (STDERR)     at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:13:1)
W20151126-16:59:37.701(1)? (STDERR)     at /Users/marwanmazloum/Desktop/Sites/startup-innovation/.meteor/local/build/programs/server/packages/npm-bcrypt.js:33:4
W20151126-16:59:37.701(1)? (STDERR)     at /Users/marwanmazloum/Desktop/Sites/startup-innovation/.meteor/local/build/programs/server/packages/npm-bcrypt.js:42:3
W20151126-16:59:37.701(1)? (STDERR)     at /Users/marwanmazloum/Desktop/Sites/startup-innovation/.meteor/local/build/programs/server/boot.js:242:10
W20151126-16:59:37.701(1)? (STDERR)     at Array.forEach (native)
W20151126-16:59:37.701(1)? (STDERR)     at Function._.each._.forEach (/Users/marwanmazloum/.meteor/packages/meteor-tool/.1.1.10.17jl6pu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151126-16:59:37.701(1)? (STDERR)     at /Users/marwanmazloum/Desktop/Sites/startup-innovation/.meteor/local/build/programs/server/boot.js:137:5

**Comment by Tzaphkiel** [comment]
I have the same issue anytime I build my meteor application on a linux platform.
I literally have to construct the bundle (meteor build...) than do : 
  * go to  programs/server: ```npm install```, 
  * stay in this folder: ```npm uninstall fibers && npm install fibers```
  * stay in the folder: ```rm -r ./npm/npm-bcrypt/node_modules/bcrypt && npm install bcrypt```

Only then can I go to the root folder of the app and use ```node main.js```  to launch it !

Furthermore, if I ever added kadira for example to the meteor packages, I get a module is un-defined for ```meteor-deque``` and npm ```module double-ended-queue```...

There seems to be a problem with the dependency management of NPM.

**Comment by DaveEveritt** [comment]
This happened after I set up Facebook login to work locally, then uploaded the app to meteor.com and tried to run locally again. I removed the Facebook login code, commented `accounts-facebook` out in .meteor/packages and rebuilt. Perhaps connected?

**Comment by Tzaphkiel** [comment]
No as far as I can see, the accounts-facebook was never installed in my application although I had some other accounts setup such as google, github, ...

**Comment by jonathanazulay** [comment]
I had the same problem, deleting` ~/.meteor/packages` solved it.

**Comment by mitar** [comment]
Happened to me as well.

**Comment by mitar** [comment]
It is trying to install bcrypt@0.7.7 though.
