### ISSUE TITLE
Add a way to block server restarts until some code finishes running

### ISSUE THREAD

**Issue by JamesMGreene** [meteor/meteor#5012]
So I stumbled upon the awesome `Reload._onMigrate`? callback registering method for the client-side but discovered, much to my chagrin, that it is a client-side only feature.

Is there any equivalent for the server-side?  I am getting annoyed by my DB migrations (using the [`percolate:migrations` package](https://atmospherejs.com/percolate/migrations) on my localhost getting interrupted by hot code reloads and then getting stuck in a weird locked state.  I'd love to have a server-side equivalent of `Reload._onMigrate` in order to specify when it is "safe" to reload.

**Comment by stubailo** [comment]
I think this could be a good feature to have, but I don't know if it's the best solution for migrations in particular. IMO the best way to solve migrations would be to have them run totally outside of the app code, for example inside a command line tool. Then, they wouldn't be affected by any other part of the app.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20way%20to%20block%20server%20restarts%20until%20some%20code%20finishes%20running&body=Migrated%20from:%20meteor/meteor%235012) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
