### ISSUE TITLE
Better, more consistent Match.Error messages for `check`

### ISSUE THREAD

**Issue by Aralun** [meteor/meteor#5013]
The error message of `check` changes in precision depending on the pattern used.

```
check('foo', Number);
```

> Match error: Expected number, got string

```
check('foo', [Number]); //Check against an array this time
```

> Match error: Expected array, got "foo"

The behaviour of `check` should stay consistent, or at least not depend on the pattern used...

**Comment by stubailo** [comment]
Yeah, I think `check` could use a lot of work in this department.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Better%2C%20more%20consistent%20Match.Error%20messages%20for%20%60check%60&body=Migrated%20from:%20meteor/meteor%235013) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
