### ISSUE TITLE
FR: user session binding

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5014]
To help mitigate the case in which a session token is stolen, you can bind the token to the user agent and/or IP (rejecting the token if it comes from a different UA/IP). A good UX default might be to bind to both on desktop, but to only use UA when the UA is a mobile agent, since mobile devices often change IP. 

Background: https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Binding_the_Session_ID_to_Other_User_Properties
https://en.wikipedia.org/wiki/Session_fixation#Verify_that_additional_information_is_consistent_throughout_session

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I don't know where this lies on the spectrum of priority of Accounts feature requests, but if there was a pull request I could take a look at it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=FR%3A%20user%20session%20binding&body=Migrated%20from:%20meteor/meteor%235014) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
