### ISSUE TITLE
Exited with code: 3

### ISSUE THREAD

**Issue by Skulmuk** [meteor/meteor#5018]
Anyone know what this code represents? A Google search only returns results for code 8, and I can't find anything in the repo that suggests what it might be. This isn't a consistently-occurring error; it only happens on occasion.

**Comment by glasser** [comment]
What is exiting with that code? Your app on the server in production?  Your app in the dev mode runner? The meteor tool?

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

I don't know of anything in Meteor core at causes an exit with code 3.

**Comment by CTimmerman** [comment]
I haven't found what calls run-app.js's onExit with code 3 yet, but i'm guessing it's an out of memory error caused by logging a large object.
