### ISSUE TITLE
Interactions with mongo collections fails on Cordova

### ISSUE THREAD

**Issue by allandequeiroz** [meteor/meteor#5021]
Hello guys, I'm trying to build an mobile app to read a qrcode and subtract a value in a collection. 
To read the qrcode I'm using Cordova's BarcodeScanner plugin, so.

**How I'm building the app:**

    meteor build ../redpass-builds --server=http://meteor-mobile.com:3000  --mobile-settings=settings.json

**How I reach the page:**

    FlowRouter.route('/operador/validacao/',{
        subscriptions: function(params, queryParams) {
            this.register('events', Meteor.subscribe('AllEventsIsTodayMoreOneDay'));
            this.register('transactions', Meteor.subscribe('AllTransactions'));
            this.register('lotes', Meteor.subscribe('AllLotes'));
        },
        action: function(params) {
            FlowLayout.render('Private', {main: "TicketValidation"});
        }
    });

**How my template looks like:**

    <template name="TicketValidation">
        <div style="text-align: center">
            {{#if isReady "events"}}
                {{#if isReady "transactions"}}
                    {{#if isReady "lotes"}}
                        <button type="button" class="scan btn btn-primary btn-lg"><i class="fa fa-qrcode fa-5x"></i></button>
                    {{/if}}
                {{/if}}
            {{/if}}
        </div>
    </template>

**How I read the qrcode:**

    Template.TicketValidation.events({
        'click .scan':function(){
            cordova.plugins.barcodeScanner.scan(
                function (result) {
                    var transactionId = result.text;
                    alert("transactionId:"+transactionId);
    
                    var transactions = Transactions.find({}).count();
                    alert("transactions:"+transactions);
    
                    var transaction = Transactions.findOne({_id:transactionId});
                    alert(transaction['card_holder_name']);
    
                    var quantity = parseInt(transaction.quantity);
                    if(quantity>0){
                        var remainder = quantity-1;
                        Transactions.update({_id:transactionId},{$set:{quantity:remainder}})
                        alert("Ingresso válido!")
                    }else{
                        alert("Esse ingresso já foi utilizado!")
                    }
                },
                function (error) {
                    alert("Não foi possível verificar o ingresso!");
                }
            );
        }
    });

Ok! Qrcode reading works fine! The alert with transactionId is fired nicely but, for some reason the next line that interacts with Transactions collection doesn't, I don't know why. Anyone has some idea?

Tks!

**Comment by gabrielalmeida** [comment]
Hi,

```var transactions = Transactions.find({}).fetch().count();```

Where it should be:

```var transactions = Transactions.find({}).count();```

Check docs about this [here](http://docs.meteor.com/#/full/fetch).

Both ```cursor.fetch()``` and ```cursor.count()``` must be called after a query that returns a ```cursor```. ```cursor.fetch()``` itself returns an ```Array``` and ```cursor.count()``` and ```Integer```, so you can't chain like that.

Boa sorte :smile:

**Comment by allandequeiroz** [comment]
Fala Gabriel :D,

Yes, I saw this error but, the problem is another and still without solution:
https://forums.meteor.com/t/meteor-status-status-connecting-forever/8838

The real reason for that problem is Meteor.status() that begins connected and suddenly down to waiting and goes to connecting and still connecting forever.

I tried to reconnect with this code but, without sucess

```javascript
var intervalId = null;
Meteor.startup(function() {
    Tracker.autorun( function () {
        if(Meteor.status().status === "waiting" && intervalId === null) {
            intervalId = Meteor.setInterval( function () {
                Meteor.reconnect()
            }, 1000);
        }
        if(Meteor.status().status === "connected" && intervalId != null) {
            Meteor.clearInterval(intervalId);
            intervalId = null;
        }
    })
});
```

**Comment by joaopiopedreira** [comment]
Hi  @allandequeiroz ,

For the connection issue, it's better to add 

```
--mobile-server=http://meteor-mobile.com:3000
```
 
to your build script.

If you really want to force a (re)connection with the server, use the undocumented

```
Meteor.reconnect({force:true})
```

this will reconnect even when Meteor.status() is "connected".

Hope it helps.

**Comment by allandequeiroz** [comment]
Hi @joaopiopedreira 

Unfortunately not. I just used {force:true} but still going to connecting limbo.

About the --mobile-server, I'm generating the .apk and installing on the phone, in this case it's necessary the --server parameter instead of --mobile-server.

```bash
meteor build ../redpass-builds --server=http://meteor-mobile.com:3000  --mobile-settings=settings.json
```

Thank you!

**Comment by avital** [comment]
@allandequeiroz Looks to me that you resolved this problem, so I'll close this ticket. Let me know if I misunderstood.

**Comment by allandequeiroz** [comment]
No @avital, still not working, in a first moment my app is connected and after an update from server, goes to waiting and connecting forever.

I don't know what to do anymore. 

If I use Meteor.call, it fails inside cordova context, if I use collection directly, when server sends an update to client, it disconnects. It's an impossible situation.

**Comment by avital** [comment]
Are you sure your app can even connect to begin with?

**Comment by gabrielalmeida** [comment]
>About the --mobile-server, I'm generating the .apk and installing on the phone, in this case, it's necessary the --server parameter instead of --mobile-server.

Assuming that perhaps the app can't even connect as stated above.
What is the value that you are inserting as ```--server``` flag?

Make sure to check that:

* You are using the complete address, it must include protocol and port.
* If you're using local IP, check if the phone is connected to the same network.
* Your network/router settings for the port you're running the server.
* Firewall settings.

**Comment by allandequeiroz** [comment]
@avital Yes, I don't know why it's disconnecting and still disconnected, even with Meteor.reconnect({force:true}).

@gabrielalmeida this is my --server flag:
--server=http://meteor-mobile.com:3000

**Comment by avital** [comment]
I'm still under the belief that it's most likely that your app isn't connecting at all. You shouldn't have to call `Meteor.reconnect` in your app.

**Comment by allandequeiroz** [comment]
When my app opens I can see that it's connected because of an alert:
alert(Meteor.status().status)

And I can read an qrcode and update server database but just once, after that client just disconnect from server

**Comment by avital** [comment]
@allandequeiroz Did you figure out your issue?

**Comment by allandequeiroz** [comment]
@avital I'm not sure, It was a combo.

I changed my app from an server to other, opened 3000,27017 ports for TCP/UDP, used Meteor.reconnect({force:true}) inside an Tracker and it just works.

**Comment by avital** [comment]
I'll just say this one more time -- you shouldn't need to call `Meteor.reconnect`.

**Comment by avital** [comment]
Happy you got your app running though!
