### ISSUE TITLE
Character encoding UTF-8 not working

### ISSUE THREAD

**Issue by mrtruko** [meteor/meteor#5026]
This is the code im using on windows 10 i tried inserting the meta on top of everything with meteorhacks:inject-initial but didn't work. I got the same problem using template instead of ui-view. here is an example grafica123.meteor.com
I Tried it on a mac and works fine here is an example http://graficaeje.meteor.com/ the problem is on windows
And only when i create the proyect on windows i can still create it on mac and use it on windows and works fine anyone knows why this happends?

```html
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport"  content="width=device-width, initial-scale=1">
  <base href="/">
</head>
<body>
  <div>Iníció</div> <-- This works
  <div ui-view></div> <-- Nothing inside here does
</body>
```

**Comment by gabrielalmeida** [comment]
Hello,

I guess the file is being saved as UTF-8 per default on Mac and not on Windows. Albeit if this was the case ```Inició``` should not be displayed correctly too. Anyway, try to do something like this on your text editor and let me know if it works:

![](http://blog.fraser-hart.co.uk/wp-content/uploads/2013/06/sublime.jpg)

**Comment by mrtruko** [comment]
Yes that did work thanks alot the problem was the encoding of index.html was in utf8 one being render in ui-view were in some other encoding.
Thanks for the help

**Comment by gabrielalmeida** [comment]
Got it, glad it helped!

**Comment by stubailo** [comment]
Glad this issue was resolved!
