### ISSUE TITLE
[BUG?] Sometimes publish requires architecture builds, sometimes not.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5028]
For example, I just tried this:

```
130 trusktr@starlancer ~/src/meteor-rocket+module (git)-[master] % meteor --release PLUGINS-PREVIEW@2 publish                                                                  :(
Please log in with your Meteor developer account. If you don't have one, you can quickly create one at www.meteor.com.
Username: trusktr
Password:
rocket:module: updating npm dependencies -- lodash, regexr, mkdirp, npm, shelljs...
Published rocket:module@0.8.0.
meteor --release PLUGINS-PREVIEW@2 publish  22.39s user 2.33s system 42% cpu 57.927 total
```

but Meteor didn't tell me to get any build machines to build for specific architectures, although I had to for the last version that I published, and I haven't changed the NPM dependencies except for adding more of them.

Why did it ask me to build things for each architecture before, but not now?

**Comment by trusktr** [comment]
By the way, I ran that last publish in Linux. Maybe it makes a difference if I run in OS X?

**Comment by avital** [comment]
Yeah, it could be the same as what was explained here: https://github.com/meteor/meteor/issues/4477#issuecomment-108110258

**Comment by trusktr** [comment]
@avital Does this mean that someone who is developing on one platform (without regular access to other platforms) won't be able to publish for the other platforms? If so, I'd consider this a bug because it means I'll have to switch to OS X (suppose I don't have OS X) just to trigger the platform-specific build. On top of that, I may never know that platform-specific builds are needed because I don't get any such message in my current platform. cc: @glasser

**Comment by avital** [comment]
No, it actually means the opposite -- that in some cases if you start with the "right" architecture you won't need to publish for other ones at all because the version you'll end up building won't use the binary package that's an optional dependency.

**Comment by trusktr** [comment]
@avital Hmmm, interesting. Could that be a bad thing? Maybe it's optional because it's only needed in OS X, so actually "required" in OS X, but "optional" in package.json?

**Comment by avital** [comment]
@trusktr If that's true I'd love to find that out. More likely it's an optimization that's only implemented for one architecture.

**Comment by trusktr** [comment]
Well, good thing I have OS X, so I'll switch over when I get a chance and see if the package works there.

**Comment by abernix** [comment]
Given the changes in the binary dependencies department of Meteor and movement toward a required compiler toolchain, I'm going to close this.
