### ISSUE TITLE
Make it so that returning `undefined` from Meteor.publish does something reasonable

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5029]
Right now, if you have a publication like below:

``` js
Meteor.publish(function () {
  if (this.userId) {
    return Widgets.find();
  }
});
```

The subscription will _never_ become ready, since Meteor assumes that a publication that doesn't return anything is trying to be an "advanced" subscription that will call `this.ready()` asynchronously.

We should fix this, because the above code snippet should be a reasonable thing to write in Meteor.

**Comment by mquandalle** [comment]
IIRC this code snippet has another side effect, which is that if a connected user `A` (who has subscribed to this publication and received the corresponding data) disconnect the data will not be removed from the minimongo cache. Thus non-connected users may access data from `A` directly in the UI. Even worst, if a second user `B` connects within the same session he will access both its data and also the data of user `A`.

This happened in LibreBoard, see https://github.com/libreboard/libreboard/issues/161

**Comment by stubailo** [comment]
@mquandalle is that side effect fixed if the empty subscription is marked as ready?

**Comment by mquandalle** [comment]
I need to test because I'm not exactly sure what `ready` does in this case (is it going to remove previously fetched data, or is the only way to call `stop`?)

BTW the case I described above will only happen with a named subscription that is subscribed on a particular route/template or at user connection. So it's not exactly the same case than your original snippet but still something to consider if we want to change the `undefined` semantic.

**Comment by mquandalle** [comment]
But as you can see in https://github.com/libreboard/libreboard/commit/82431349ff8c939326af3a986b1f543ab9878000 the fix was to return an empty array instead of `undefined`, I guess that may work with others values such as `false` as well.

**Comment by mquandalle** [comment]
I can't reproduce this in a simple example, that may be more tricky than I thought.

**Comment by stubailo** [comment]
@mquandalle note that returning `[]` from `Meteor.publish` marks it as ready, but returning `false` doesn't.

**Comment by sebakerckhof** [comment]
Quick question: What happens when the publication throws an error? A lot of publications use the check function to validate input parameters. Do we need to try-catch these and return [] on error?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20it%20so%20that%20returning%20%60undefined%60%20from%20Meteor.publish%20does%20something%20reasonable&body=Migrated%20from:%20meteor/meteor%235029) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
