### ISSUE TITLE
Don't pass an empty {hash:{}} as the last arg to a template helper

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5031]
Many people treat template helpers like normal JS functions and don't know that you can give keyword arguments `{{foo a="a" b="b"}}` or that the final arg passed is always a `Spacebars.kw` object of the form `{hash: ...}`. 

A common JS pattern is putting optional params in function definitions, and you expect those params to be `undefined` when you call the function with fewer params:

```coffeescript
foo = (bar, optional) ->
  if optional
    optional
  else
    bar

foo(5)
```
People expect `foo(5)` to return `5`, because that's what they're used to in JS. But in Blaze, `optional` is truthy, and they have a bug. Similarly, default param values won't work as expected: `foo = (bar, optional = 3) ->`

When you know about the `hash` arg, some people inelegantly guard against it, like so:

```coffeescript
Template.registerHelper 'foo', (bar, optionalOne, optionalTwo) ->
  unless typeof optionalOne is expectedType
  # or if expectedType is an object, then:
  # unless optionalOne?.hash?
    optionalOne = undefined

  unless typeof optionalTwo is expectedType  
    optionalTwo = undefined

  if optionalOne
    ...
```

Because it A) creates bugs, and B) creates lots of checking optional args, I think it would be preferable for Blaze to not pass `{hash:{}}` when no keyword arguments are passed.

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

You noted that people use the `typeof` method to check for the last argument. Does that mean that passing `undefined` will actually break that code then? Also, another way to check for optional arguments is to check the length of `arguments`, which will also break if we change the signature.

I'm not really sure how we can change this behavior at this point, unless it's part of a bigger set of breaking changes.

**Comment by lorensr** [comment]
If I'm understanding your question, `typeof(undefined)` is `"undefined"`, so it would not match `expectedType`, so it would not break that code.

Yes, if you're checking `arguments.length` and assuming there will be an extra last arg, then removing the last arg would be breaking.

**Comment by stubailo** [comment]
Right I'm saying someone could be checking that the type of the last argument is `"object"`, basically the opposite of your check. In which case it would fail.

**Comment by mitar** [comment]
Oh yes, this is a tricky one. I understand that keywords are wrapped into a custom object `Spacebars.kw`, but why then `hash` property inside? :-) (Handlebars legacy?)

BTW, this is documented here:

https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#helper-arguments
