### ISSUE TITLE
Make templates follow JS scoping rules between package and app code

### ISSUE THREAD

**Issue by JWo1F** [meteor/meteor#5032]
I'm making a large Meteor app and all my templates are now named "veryLongNameOfMyTemplate". I want to avoid having such long names.
I tried to create my templates in packages but I have a strange issue: while most package variables are file-scoped or package-scoped, templates are not: they are global by default.

How can I create package-scoped templates?

**Comment by mquandalle** [comment]
Related: https://trello.com/c/igqeUcwM/17-template-and-helper-namespacing

**Comment by JWo1F** [comment]
@mquandalle wow, thanks! I will wait this feature. You don't know when it will be done?

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this would be really great - if you could specify templates that should be exported and only those are available outside of the package.

**Comment by mitar** [comment]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components#namespaces) have namespaces.

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#182. Closing - thanks!
