### ISSUE TITLE
Build error with cordova when two plugins have the 2.9 dummy.java patch

### ISSUE THREAD

**Issue by petrometro** [meteor/meteor#5033]
Here is a repo
https://github.com/petrometro/meteor-cordova-dummy-java-error

a fix for an old cordova 2.9 issue meant that plugins had to create an empty /org/apache/cordova/api/Dummy.java file. There are many cordova plugins still using this for legacy users.

When I build a mobile meteor app and I have *more than one* such plugin, the build fails when loading the second plugin, complaining that 'Dummy.java' already exists (sample stack trace below). Since meteor's build tool uses cordova > 4.0 there would be no problem just ignoring that folder in the plugin.xml file.

My workaround for the moment has been to fork the plugin repositories and remove the lines by hand, which allows the build to go through 

```
        <!-- kludge for 2.9 -->
        <!--<source-file src="src/android/org/apache/cordova/api/Dummy.java"-->
        <!--    target-dir="src/org/apache/cordova/api"/>-->
```

Otherwise, you would have to do a better cleanup in between loading plugins I suppose.

pc8:distribution user$ meteor build --server=http://distribution.foo.org ../distribution-build
Error while building for mobile platforms: Error running                           
/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error during processing of action! Attempting to revert...
Failed to install 'com.chariotsolutions.nfc.plugin':Error: Uh oh!
"/Users/user/Desktop/kbg/distribution/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/api/Dummy.java"
already exists!
at Object.module.exports.common.copyNewFile
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:70:19)
at module.exports.source-file.install
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:65:20)
at Object.ActionStack.process
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at
/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:509:49
at flush
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
Error: Uh oh!
"/Users/user/Desktop/kbg/distribution/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/api/Dummy.java"
already exists!
at Object.module.exports.common.copyNewFile
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:70:19)
at module.exports.source-file.install
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:65:20)
at Object.ActionStack.process
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
at handleInstall
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
at
/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
at _fulfilled
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
at
/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:509:49
at flush
(/Users/user/.meteor/packages/meteor-tool/.1.1.4.gfpwd1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by martijnwalraven** [comment]
Could you try this again with the Meteor 1.2 RC (`--release METEOR@1.2-rc.7`)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue. If not, let me know, and I'll look into it.

**Comment by stubailo** [comment]
Does this still happen in Meteor 1.2.1?

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
