### ISSUE TITLE
FR: Bash completion

### ISSUE THREAD

**Issue by mquandalle** [meteor/meteor#5036]
A while back #1065 was rejected on the grounds of too high maintenance costs. Now that the framework has globally matured, in particular regarding the command line library and the various admin build tool around it, I feel it's time to re-open the feature request.

So the desired feature is pretty simple to understand:

```
$ meteor up [press Tab]
$ meteor update
```

I think we don't need to go further than command completion (ie not package names or others).

Hopefully we could make it work with ZSH as well, including a list to disambiguate between multiple matching commands:

```
$ meteor pu [press Tab]
publish           -- Publish a new version of a package to the package server.
publish-release   -- Publish a new meteor release to the package server.
publish-for-arch  -- Builds an already-published package for a new platform.
```

**Comment by stubailo** [comment]
I don't think this would add more maintenance burden if we parse it from `help.txt` or the command line tool, right? Really we just need someone to write the code once that generates a data file that works with some popular auto-complete library.

I don't think that pull request was the right way to go about it. At worst, we need a script that generates _that_ script from somewhere.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=FR%3A%20Bash%20completion&body=Migrated%20from:%20meteor/meteor%235036) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
