### ISSUE TITLE
Document App.icons() - which icons from config.xml

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#5042]
Hi, what are the right icon and splash properties to copy over from config.xml?

Maybe it's worth mentioning `ionic resources` to auto-build the images from initial files.

http://ionicframework.com/docs/cli/icon-splashscreen.html

I ended up with this, but the Apple stuff is probably wrong

```
App.icons({
  'iphone':       'resources/ios/icon/icon-60.png',
  'iphone_2x':    'resources/ios/icon/icon-60@2x.png',
  'iphone_3x':    'resources/ios/icon/icon-60@3x.png',
  'ipad':         'resources/ios/icon/icon-76.png',
  'ipad_2x':      'resources/ios/icon/icon-76@2x.png',
  'android_ldpi': 'resources/android/icon/drawable-ldpi-icon.png',
  'android_mdpi': 'resources/android/icon/drawable-mdpi-icon.png',
  'android_hdpi': 'resources/android/icon/drawable-hdpi-icon.png',
  'android_xhdpi':'resources/android/icon/drawable-xhdpi-icon.png',
});

App.launchScreens({
  'iphone':                 'resources/ios/splash/Default~iphone.png',
  'iphone_2x':              'resources/ios/splash/Default@2x~iphone.png',
  'iphone5':                'resources/ios/splash/Default-667h.png',
  'iphone6':                'resources/ios/splash/Default-667h.png',
  'iphone6p_portrait':      'resources/ios/splash/Default-736h.png',
  'iphone6p_landscape':     'resources/ios/splash/Default-Landscape-736h.png',
  'ipad_portrait':          'resources/ios/splash/Default-Portrait~ipad.png',
  'ipad_portrait_2x':       'resources/ios/splash/Default-Portrait@2x~ipad.png',
  'ipad_landscape':         'resources/ios/splash/Default-Landscape~ipad.png',
  'ipad_landscape_2x':      'resources/ios/splash/Default-Landscape@2x~ipad.png',
  'android_ldpi_portrait':  'resources/android/splash/drawable-port-ldpi-screen.png',
  'android_ldpi_landscape': 'resources/android/splash/drawable-land-ldpi-screen.png',
  'android_mdpi_portrait':  'resources/android/splash/drawable-port-mdpi-screen.png',
  'android_mdpi_landscape': 'resources/android/splash/drawable-land-mdpi-screen.png',
  'android_hdpi_portrait':  'resources/android/splash/drawable-port-hdpi-screen.png',
  'android_hdpi_landscape': 'resources/android/splash/drawable-land-hdpi-screen.png',
  'android_xhdpi_portrait': 'resources/android/splash/drawable-port-xhdpi-screen.png',
  'android_xhdpi_landscape':'resources/android/splash/drawable-land-xhdpi-screen.png',
});
```

**Comment by stubailo** [comment]
@martijnwalraven can you take a look at this?

**Comment by martijnwalraven** [comment]
I'm not sure I completely understand your question. What icon and splash properties are unclear to you?

If you've generated the images at the right sizes, the configuration seems alright to me. Why do you expect the Apple stuff to be wrong?

Note that the filenames will be automatically generated based on the keys, so there is no need to use the target platform naming convention for your source images.

**Comment by MichaelJCole** [comment]
Hi @martijnwalraven thanks for posting :-)

The icons and splashes were automatically generated with the `ionic resources` command.  It takes a single icon and splash, then generates all the images you see above (and more), along with a [config.xml](http://pastebin.com/5wim7GV8) file.  This file gets sent to Cordova for packaging.

My question is:  How do I match the keys in Meteor's App.icons() and App.launchScreens() to the files in the config.xml?

Or more importantly, what is the specs for the images used in Meteor's App.icons() and App.launchScreens() functions?

**Comment by wzoom** [comment]
I would say for iOS you need to look at [Official iOS Icon and Image Sizes](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW1).

Also Cordova docs shows to be a good resource: [Cordova Icons and Splash Screens](http://cordova.apache.org/docs/en/5.1.1/config_ref/images.html)
