### ISSUE TITLE
Meteor crashes when returning collection in publish function

### ISSUE THREAD

**Issue by connorblack** [meteor/meteor#5045]
Original here: http://stackoverflow.com/questions/32256779/meteor-crashes-when-returning-collection-in-publish-function

I'm having this weird bug happen in meteor, but it only expresses itself when I deploy to my staging environment.

I have a publish function for some data called `campaigns`:
```
    Meteor.publish('campaigns', () ->
    	campaigns = Campaigns.find({userId: @userId}, {$orderby: {created: -1}})
    	return campaigns
    )
```
This code works perfectly locally, but once I deploy through modulus (https://modulus.io/), the program crashes without any error and restarts. 

I've been debugging a little and the current state I'm at is I've commented out every reference to `Campaigns` client-side, and the only call to `subscribe()` is when I literally type this into the browser console:
```
    Meteor.subscribe('campaigns')
```
A few milliseconds later I get this:
```
    Object {subscriptionId: "SJzcL4SyWuiya3PHd"}
    f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32 GET https://staging.********.com/sockjs/info?cb=xy4b3xx4tj 500 (Internal Server Error)w._start @ f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32(anonymous function) @ f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32
    f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32 XHR finished loading: GET "https://staging.********.com/sockjs/info?cb=xy4b3xx4tj".w._start @ f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32(anonymous function) @ f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32
    f76aeae27f6c322792e7f2cc8ddb8d6abc211944.js:32 GET https://staging.********.com/sockjs/info?cb=qm6m8v5czn 500 (Internal Server Error)
```
and the server restarts.

At first, I thought it was the call to the DB that was causing the error, but when I comment out the `return` statement and log the `find` results, it logs what is expected. The only problem is that the data doesn't get returned, which is obviously necessary.

So it seems to me that the issue happens when the server tries to return the data in the publish function to the client. I'm not really sure why this has happened, and I've simplified the code enough to rule out a code logic error, and also it works perfectly locally. 

Also I thought maybe it was a node versioning issue, but I ran the code locally under the same node version the modulus server runs it (v0.10.36) and it works fine.

Has anyone else had issues with publishing collections like this? Any help would be appreciated.

**Comment by stubailo** [comment]
If you'd like to discuss with other people, the Meteor forums would be the best place: https://forums.meteor.com/

If we should treat this as a bug, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
