### ISSUE TITLE
Meteor release 1.2-rc.6 -> Meteor build android error

### ISSUE THREAD

**Issue by d62remi** [meteor/meteor#5046]
Hi,

I am French so excuse my english ... (google translation = D)
I have a problem to build the apk for android
Here is how to get the console on my intel mac (10.10.5) :

```
$ meteor create test12 --release 1.2-rc.6

$ cd test12

$ meteor add-platform android

$ meteor add crosswalk

$ meteor deploy testremi.meteor.com

$ meteor build ../build --server=testremi.meteor.com

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, lstat '/Users/XXX/Desktop/meteor/test12/.meteor/local/build_tar/bundle/README'
```

I followed the instructions here: 
```
https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac
```
Here's how I instantiated my environment variables : 
```
$ env
TERM_PROGRAM=Apple_Terminal
ANDROID_HOME=/Users/XXX/Library/Android/sdk
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/nh/r4m91p5n15l6jbkvg7y5kd0w0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.vQNqrRsywE/Render
TERM_PROGRAM_VERSION=343.7
OLDPWD=/Users/XXX
TERM_SESSION_ID=54C96D46-7077-4453-B792-AC8736344664
USER=XXX
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.2CFTwCGvtx/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1
PATH=/Users/XXX/Library/Android/sdk/platform-tools:/Users/XXX/Library/Android/sdk/tools:ANDROID_HOME/tools:ANDROID_HOME/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/XXX/Desktop/meteor/test12
LANG=fr_FR.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/XXX
DYLD_LIBRARY_PATH=/Users/XXX/java/qtjambi/lib:
LOGNAME=XXX
_=/usr/bin/env
```

an idea ?

Thank

From France <3

**Comment by sjmcdowall** [comment]
Salut Remi!  Comment ça va? 

Why are you using that version of Meteor?  1.2 is not released .. and "rc" is a bit of a misnomer.. it's not a "real" RC version.  Have you tried the "production" version of 1.1.0.3 ?  Newer is not always better. :) 

I do not want you to get frustrated trying an "in progress" version which for sure will have many "issues" until it's production ..

**Comment by d62remi** [comment]
Salut ça va bien merci =P

Why ? Because I follow the evolutions of mobile meteor and I wanted to test. 

I am an application in production (1.1.0.3) and a lot of Samsung devices not working -> white screen when app strating ! Bizarre ... 

From France =P

**Comment by sjmcdowall** [comment]
Oui c'est vrai ! Mobile apps are trickier ! Well they just release the real first RC 1.2 - rc7 :  maybe that will work better for you!

**Comment by d62remi** [comment]
after updated meteor to rc7, the error is always here ! 

I try to modify my path and android_home env : 

```
ANDROID_HOME=/Users/XXX/.meteor/android_bundle/android-sdk
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/XXX/.meteor/android_bundle/android-sdk/tools:/Users/XXX/.meteor/android_bundle/android-sdk/platform-tools
```

not working ...

**Comment by martijnwalraven** [comment]
It's an issue with building an app that uses Crosswalk. I just committed a fix for this (https://github.com/meteor/meteor/commit/b0c1464e7cb63e826372c8f9c97fb333c3a747af) that should be in the next RC.

**Comment by d62remi** [comment]
Why this error refered to '/Users/XXX/Desktop/meteor/test12/.meteor/local/build_tar/bundle/README' ? 

If I remove crosswalk, error is always here ! 

My path is it good ?

**Comment by martijnwalraven** [comment]
Hmmm, maybe your issue is not the same one I committed the fix for. I'm not sure why it would be unable to find README. 

Have you tried running with `--verbose`?

**Comment by martijnwalraven** [comment]
I just noticed you're trying to set your path to the `~/.meteor/android_bundle/android-sdk` directory. Note that Meteor 1.2 no longer bundles the Android tools and requires a system-wide install of the Android SDK. See [here](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac) for installation instructions.

**Comment by d62remi** [comment]
Thanks for the information ;-)

I'm going to try with the last RC this week. 

I will come back to you !

**Comment by d62remi** [comment]
Hi guys,

I deleted my test project and I created a new blank project with release 1.2-rc.12 : 

Now it's good !!!

I will test my project into production works with samsung mobile (which is not the case with the version 1.1.0.3)
