### ISSUE TITLE
Accounts.sendVerificationEmail

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#5048]
Is there no way to use `html` instead of `text` field for the template?

```
    Accounts.emailTemplates.verifyEmail.html = function (user, url) {
      "html version" + url;
    }

    Accounts.emailTemplates.verifyEmail.text = function (user, url) {
      "text version" + url;
    }
```

Only the latter works. I couldn't find anything about a html field in the document too but there must be a way to use an html template for verification emails, right?

**Comment by justin-umesh** [comment]
Hey u can use.. U need to have handlebars installed.

**Comment by avital** [comment]
There's no built in way in Meteor to use HTML template to send out emails. There are some community packages that try to address this, such as https://github.com/meteorhacks/meteor-ssr or https://github.com/lookback/meteor-emails. I've never tried it though so I can't guarantee their quality.

**Comment by avital** [comment]
Or maybe I understood? The Meteor accounts system definitely looks at `Accounts.emailTemplates.verifyEmail.html` if it has been set when it sends out email verification messages.

Is there a bug? Can you show a reproduction?

**Comment by woniesong92** [comment]
Reproduction should be as simple as setting the html field. Send a
verification email after you have set the html field, and see if the email
contains any of the html that you set.

**Comment by avital** [comment]
I made the following app and received an HTML email as expected:

```
if (Meteor.isServer) {
  Accounts.config({
    sendVerificationEmail: true
  });

  Accounts.emailTemplates.verifyEmail.html = function () {
    return "Yo!";
  };
}

<body>
  {{> loginButtons}}
</body>
```

**Comment by woniesong92** [comment]
@avital Aha, I had left out `return` keyword. Thank you!
