### ISSUE TITLE
publish-for-arch isn't working correctly

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#5050]
I'm trying to `publish-for-arch` for all platforms to create a build for this thin npm package. I'm remoting into each of the following:

    meteor admin get-machine os.osx.x86_64      
    meteor admin get-machine os.linux.x86_64    
    meteor admin get-machine os.linux.x86_32    
    meteor admin get-machine os.windows.x86_32

then running:

    meteor publish-for-arch markoshust:radium@0.0.2

It completed successfully on OS X, then the first os.linux machine I ran it on (ex. 32 bit). However, running it on a subsequent os.linux machine (ex. 64 bit) or on the windows machine I receive this message:

    While publishing package build for markoshust:radium:
    error: Cannot override existing build

When I show package details, only the OS X version exists:

    meteor show markoshust:radium --ejson

    "architecturesOS": [
      "os",
        "os.osx.x86_64"
    ]

This doesn't make much sense to me as I've received a successful build message for the first os.linux machine I ran it on. I also shouldn't be receiving the `error: Cannot override existing build` error when running this on the linux machine as it appears only the OS X build exists on atmosphere.

**Comment by markoshust** [comment]
This may help simplify the post... 

Only the OS X build exists on atmosphere:

    meteor show markoshust:radium --ejson

    "architecturesOS": [
      "os",
        "os.osx.x86_64"
    ]

However, when I try to build for `os.linux.x86_64`, it's erring out. This shouldn't happen because this build doesn't yet exist on atmosphere.

    Marks-MacBook-Air:meteor-radium markshust$ meteor admin get-machine os.linux.x86_64
    Linux ip-172-31-49-171 2.6.32-356-ec2 #69-Ubuntu SMP Mon Aug 26 15:32:17 UTC 2013 x86_64 GNU/Linux
    Ubuntu 10.04.4 LTS
    
    Welcome to Ubuntu!
    * Documentation:  https://help.ubuntu.com/
    
      System information as of Fri Aug 28 14:19:32 UTC 2015
    
    System load:  0.0               Processes:           61
    Usage of /:   16.3% of 9.84GB   Users logged in:     0
    Memory usage: 7%                IP address for eth0: 172.31.49.171
    Swap usage:   0%
    
    Graph this data and manage this system at:
      https://landscape.canonical.com/
    
        Get cloud support with Ubuntu Advantage Cloud Guest:
      http://www.ubuntu.com/business/services/cloud
        ---------------------------------------------------------------------
          At the moment, only the core of the system is installed. To tune the
    system to your needs, you can choose to install one or more
    predefined collections of software by running the following
    command:
    
      sudo tasksel --section server
    ---------------------------------------------------------------------
    
      0 packages can be updated.
    0 updates are security updates.
    
      New release 'precise' available.
      Run 'do-release-upgrade' to upgrade to it.
    
      A newer build of the Ubuntu lucid server image is available.
      It is named 'release' and has build serial '20150427'.
    *** System restart required ***
    
    The programs included with the Ubuntu system are free software;
    the exact distribution terms for each program are described in the
    individual files in /usr/share/doc/*/copyright.
    
     Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
     applicable law.
    
     meteor@ip-172-31-49-171:~$ meteor publish-for-arch markoshust:radium@0.0.2
     markoshust:radium: updating npm dependencies -- externalify, radium...
    
     Some package versions changed since this package was published!
    
     babel-compiler      added, version 5.6.15     
     coffeescript        added, version 1.0.6
     markoshust:radium   added, version 0.0.2
     react-runtime-dev   added, version 0.13.3_3
     react-runtime-prod  added, version 0.13.3_2
     tracker             added, version 1.0.7
     underscore          added, version 1.0.3
    
     Please log in with your Meteor developer account. If you don't have one, you can quickly create one at www.meteor.com.
     Username: markoshust
     Password:                                     
     => Errors while publishing build:             
    
     While publishing package build for markoshust:radium:
     error: Cannot override existing build
    
     meteor@ip-172-31-49-171:~$

**Comment by markoshust** [comment]
I now tried running this command through Ubuntu 12.04:
`meteor publish-for-arch markoshust:radium@0.0.2`

However, it is still saying: `error: Cannot override existing build`

Am I missing something here? Here is my entire `meteor show markoshust:radium --ejson` -- it is only showing an OS X build.

```
{                                             
  "versions": [
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.1",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "publishedBy": "markoshust",
      "publishedOn": {
        "$date": 1440729715133
      },
      "installed": true,
      "architecturesOS": [
        "os.osx.x86_64",
        "os"
      ]
    },
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.2",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "publishedBy": "markoshust",
      "publishedOn": {
        "$date": 1440731216139
      },
      "installed": true,
      "architecturesOS": [
        "os",
        "os.osx.x86_64"
      ]
    }
  ],
  "name": "markoshust:radium",
  "maintainers": [
    "markoshust"
  ],
  "totalVersions": 2
}
```

**Comment by markoshust** [comment]
So, I bumped the version to 0.0.3, and tried publishing the build first on ubuntu 64-bit. I'm still receiving this error:
```
While publishing package build for markoshust:radium:
error: Cannot override existing build
```

Here is the meteor show command output now:

```
{                                             
  "versions": [
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.1",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "publishedBy": "markoshust",
      "publishedOn": {
        "$date": 1440729715133
      },
      "installed": false,
      "architecturesOS": [
        "os.osx.x86_64",
        "os"
      ]
    },
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.2",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "publishedBy": "markoshust",
      "publishedOn": {
        "$date": 1440731216139
      },
      "installed": false,
      "architecturesOS": [
        "os",
        "os.osx.x86_64"
      ]
    },
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.3",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "publishedBy": "markoshust",
      "publishedOn": {
        "$date": 1441033729507
      },
      "installed": false,
      "architecturesOS": [
        "os"
      ]
    },
    {
      "exports": [
        {
          "name": "Radium",
          "architectures": [
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "markoshust:radium",
      "version": "0.0.3",
      "description": "    meteor add markoshust:radium\n\nUses official `react` package from Meteor.",
      "summary": "Add Radium to Meteor",
      "git": "https://github.com/markoshust/meteor-radium.git",
      "local": true,
      "directory": "/meteor-radium"
    }
  ],
  "name": "markoshust:radium",
  "maintainers": [
    "markoshust"
  ],
  "totalVersions": 4
}
```

**Comment by dgreensp** [comment]
Hi @markoshust, what version of `meteor` are you using?

This error may indicate that there isn't anything architecture specific to publish.  Does `radium` have a binary part to it?  If not, you do not need to `publish-for-arch`.  Try seeing if the package works on Linux as is.

**Comment by markoshust** [comment]
I'm just going to close this, as with 1.3 we can just use npm and no longer need these wrappers.
