### ISSUE TITLE
Unexpected mongo exit code 1

### ISSUE THREAD

**Issue by markusgattol** [meteor/meteor#5051]
See https://github.com/meteor/meteor/issues/4019 All worked fine before the upgrade to `meteor update --release METEOR@1.2-rc.7` i.e. I never saw the issue before the upgrade.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
