### ISSUE TITLE
Breaking up History.md

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#5052]
***1 Upvote*** That document is getting huge.

Would it be a good idea to create a root `history` folder where each version change is on its own file?

`next.md`
`v1.2.md`
`v1.1.0.3.md`
`v1.1.0.2.md`

**Comment by devonbarrett** [comment]
:+1:

**Comment by stubailo** [comment]
Ooh, this is a cool idea. Would make it easier to search for changes in a single release, as well. What do other big projects do about this?

**Comment by rclai** [comment]
Looks like [Bootstrap uses the releases for change-logs](https://github.com/twbs/bootstrap/blob/master/CHANGELOG.md).

**Comment by Tarang** [comment]
This is a cool idea. But it needs to be easily searchable. Often new features are added and they're mentioned in History.md and not the docs.

One purpose of the file is to see what's new. The other is its sort of a set of docs.

**Comment by lirbank** [comment]
I think I'd have to vote against breaking the history.md into several docs, one doc makes it easier to search. As a reference, Node.js [changelog](https://github.com/nodejs/node/blob/v5.10.1/CHANGELOG.md) is probably 2-3 times longer and it works well, for me at least. 

See #6730 for some related thoughts.

**Comment by stubailo** [comment]
Yeah I'm convinced this is not really super useful, and might actually make things worse because searching won't be as easy.

**Comment by rclai** [comment]
Unless Github decides to make it a feature!

**Comment by stubailo** [comment]
Yeah!
