### ISSUE TITLE
Support installation on NixOS.

### ISSUE THREAD

**Issue by aloiscochard** [meteor/meteor#5053]
Hi there,

I'm struggling to install Meteor on NixOS, the reason is that the `dev_bundle` is obviously statically linked with path which are not compatible with NixOS.

I could workaround the issue, by using the `node` installed by Nix, but I can not find any instruction about it? Can I do that? how?

It would be great to have a `dev_bundle` compatible with NixOS, or ever better a package for nix directly.

Thanks

**Comment by aloiscochard** [comment]
I'll try the "Slow start" (https://github.com/meteor/meteor#slow-start-for-developers) and see how it goes, I might be able to use the `node` built by Nix.

**Comment by sjmcdowall** [comment]
This question is more suitable for the Meteor Forums and not the bug tracking system. 

However, be that as it may .. 

Which flavor node (version) does Nix provides?  Meteor needs 10.0.36 (or so) for various reasons .. 

Making meteor work on a non-supported OS is quite an undertaking -- good luck!  At least it's a flavor of Linux ! :)

**Comment by aloiscochard** [comment]
I can install any version I want of `node`, so I could use the same one (Nix have a special design which allow different version to reside at the same time on a given system).

Anyway, I tried to build from source, and while trying to build `node` with the provided script I got the following error:

```
gyp: Undefined variable node_tag in /tmp/generate-dev-bundle-8BK3YCdZ/build/node/node.gyp
```

Any Idea?

**Comment by aloiscochard** [comment]
Never mind I fonud the issue, I'm moving forward... building dependencies.

*finger crossed*

**Comment by sjmcdowall** [comment]
If you get beyond Fibers -- you are almost home free. :)

**Comment by garbas** [comment]
@aloiscochard i would use ``generate-dev-bundle.sh`` as a hint how to create nix expression

**Comment by stubailo** [comment]
Hey, I think this is unlikely to become an officially supported platform for Meteor in the near future, unless there is a large segment of people who are interested. I think the forums would be a great place for further discussion to figure out workarounds and gauge interest.

**Comment by cstrahan** [comment]
FWIW, I'm working on packaging this for Nix right now, as I need it for work.

**Comment by sjmcdowall** [comment]
The hard part will be to get a binary fibers 1.0.5 (I think that is still used in Meteor 1.2) module integrated into the core meteor stuff.  However, it maybe useful for your own needs which is great.

**Comment by cstrahan** [comment]
What's the official build process? I mean, I see stuff like `#RemoveInProd`, but I'm not sure what command(s) I need to run to build from a source check out.

**Comment by sjmcdowall** [comment]
Not sure if you are talking fibers or not .. but for fibers .. once you try any sort of npm install that has a meteor project (including the initial stuff) you should see build-gyp get involved to try to build it from command line tools.  Look at the fibers git-hub page for a bit more information of compiling it .. you can actually I think try to this this in a separate little work project for just fibers to make sure it will compile ok when you use it for meteor .. just to be aware (and check for sure) -- but back in M 1.1 days it used a hacked version of fibers @ 1.0.5 .. you may want to pull that specifically from the meteor git repo if they haven't updated it .. just in case.  But I found if I got 1.0.6/7 to compile, the 1.0.5 hacked version compiled too .. just a matter making sure the C++ compiler was available and libs, etc.

**Comment by cstrahan** [comment]
Thanks for the info. Fibers is building fine, though I'm currently trying to use the binary distribution for the time being, which appears to be working well.

**Comment by aloiscochard** [comment]
@cstrahan Hi there, I'm really interested in your effort.

I have sadly gave up and I was going to install a linux in a qemu guest in order to get meteor running... *but*  I would much prefer a nix derivation.

Is there something I can look into? a fork/branch or something?

Thanks in advance.

**Comment by cstrahan** [comment]
Last remaining problem is this: the springboard (see `tools/cli/main.js`) tries to run `kexec` on the new meteor script, which then blows up on NixOS because the fetched package used `#!/bin/bash` as its shebang, and we only have `/bin/sh`.

To be more robust (and support NixOS), Meteor should use `/bin/sh` going forward, or, if any bashisms are too ingrained to work with `sh`, use `/usr/bin/env bash`.

For now, I'll see if I can patch the `kexec` lines to prefix the commands with `"bash "`.

**Comment by cstrahan** [comment]
Oops, I can't prefix with `"/bin/sh -- "` because that's an argument to exec, so it need to be a path (of course).

Well, damn. I'll need to patch the part of the code that fetches packages, so right after fetching/unpacking, the shebangs will be fixed up.

Where should I look in the source tree, if you don't mind giving me a hint?

**Comment by cstrahan** [comment]
As Meteor currently stands, a source distribution would be pointless, as specifying a specific Meteor version will result in Meteor fetching and extracting that version into somewhere under `$HOME/.meteor`, so binary distribution is unavoidable anyway.

@aloiscochard I have Meteor for NixOS packaged here: https://github.com/NixOS/nixpkgs/pull/10064

**Comment by aloiscochard** [comment]
Thanks a lot @cstrahan you are my hero :-)

I'll try this asap, thanks again.
