### ISSUE TITLE
`meteor update` fails looking for `isobuild:` packages

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#5054]
This is a bug in the code that makes a list of packages to update when you run `meteor update`.  It should ignore `isobuild:` pseudo-packages.

**Comment by AlexFrazer** [comment]
I think you have to do `meteor --release PLUGINS-PREVIEW@2 create --package {packagename}` for it to work... not sure why.

**Comment by dgreensp** [comment]
@AlexFrazer I don't understand the connection to this issue.  Are seeing an error when creating a package?

**Comment by dgreensp** [comment]
As a workaround, you can run `meteor update --packages-only`.  What's happening is that `meteor update` normally switches to the latest recommended release (1.1.0.3) and tries to update to that release, and even if it fails, it continues with that tool version.

I'm working on a fix.

For reference, here's what the repro looks like (create an app with 1.2-rc.7 and run `meteor update`):

```
Davids-MacBook-Pro:blah dgreenspan$ meteor update
This project is already at Meteor 1.2-rc.7, which is newer than the latest
release.
=> Errors while upgrading packages:

While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: meteor 1.1.7-rc.1
Required by: ecmascript 0.1.3-rc.1
Required by: templating 1.1.2-rc.3
Required by: ecmascript 0.1.3-rc.1

unknown package: isobuild:isopack-2
Required by: ecmascript 0.1.3-rc.1
Required by: ddp-server 1.2.1-rc.1
Required by: caching-compiler 1.0.0-rc.0
Required by: templating-tools 1.0.0-rc.0
Required by: caching-html-compiler 1.0.1-rc.0
Required by: templating 1.1.2-rc.3
Required by: ecmascript 0.1.3-rc.1

unknown package: isobuild:minifier-plugin
Required by: standard-minifiers 1.0.0-rc.1
```

**Comment by dgreensp** [comment]
Fixed on `release-1.2` branch (6130648c996a7e62e39d5c50ce023e530370e332).

**Comment by gcacars** [comment]
Isn't working yet!
I formated my PC, I deleted .meteor folder, create app again, and even so not working with Meteor 1.2 for Windows.

**Comment by gcacars** [comment]
Solved:
1) Uninstall Meteor
2) Delete .meteor from `%LocalAppData%`
3) Download `tar.gz` from https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation
4) Extract file to `%LocalAppData%`

After this, all my meteor messages changed, shows that I am in the 1.2.1 version, now have a lot of packages for new project (before was only meteor-platform).

So, I think that the installer of Meteor Windows is old, and not have updated code.
