### ISSUE TITLE
[registerCompiler API] Long pause on "linking" step with build plugin?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5061]
I'm seeing a long pause at the part where is says "linking". What might that mean?

**Comment by stubailo** [comment]
Can you give more details? I can't do anything at all about this report without a reproduction.

**Comment by trusktr** [comment]
@stubailo It might be related to #5067. We can reopen if not.

**Comment by stubailo** [comment]
OK let's revisit when we fix the other one.
