### ISSUE TITLE
Nested sub-expressions with parentheses fail

### ISSUE THREAD

**Issue by stephentcannon** [meteor/meteor#5066]
Per https://github.com/meteor/meteor/tree/devel/packages/spacebars#nested-sub-expressions

Per the documentation, "Sub-expressions can be used to calculate key-word arguments, too:"

````
{{> tmpl arg=(helper post)}}
````

My example below calls a helper registered as Template.registerHelper because it is used throughout the application.

````
{{> quickForm collection="Loans" id="insertLoan" type="insert" buttonClasses="btn btn-primary btn-lg btn-block" validation="submit" buttonContent=(i18nFormatContent 'Apply for Loan')}}
````

and errors because of the parentheses

````
client/views/dashboard/dashboard.html:6: Expected identifier, number, string, boolean, or null
...ubmit" buttonContent=(i18nFormatContent '...
````

Is the documentation wrong?

Please advise.

**Comment by Slava** [comment]
You are looking at the docs on devel branch where the feature is implemented. The latest release can be found on master - it doesn't have the subexpression implementation yet.

**Comment by stephentcannon** [comment]
Doh!

**Comment by PareshSolankiMI** [comment]
(_ 'post')
