### ISSUE TITLE
[BUG] [batch-plugins] Long wait time after my compiler handles sources and when Meteor continues.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5067]
The new `registerCompiler` API calls my compiler's (`rocket:module`'s) `processFilesForTarget` method. After `processFilesForTarget` returns, sometimes there's a period of time in the console with no output from Meteor, lasting about 1 minute.

I've got caching working in `rocket:module`, and `rocket:module` completes its tasks within seconds. The lag after `rocket:module`'s `processFilesForTarget` method returns is the only thing preventing quick refreshes for me right now.

Any ideas what might be happening? Is there any info I can provide?

cc: @glasser

**Comment by stubailo** [comment]
Do you have a version of the package I can clone to try it out? Then I can add some logging or something to the command line tool to see what it's doing during that time.

**Comment by trusktr** [comment]
@stubailo Yeah, I published `rocket:module` 0.8.2 on Atmosphere. It uses `api.versionsFrom('1.2-rc.7')`.

So, 

```
meteor create test
cd test
meteor update --release 1.2-rc.7
meteor add rocket:module
```

Then create an `npm.json` file and list some NPM dependencies in there (same format as package.json's `dependencies` field, for now):

```js
{
  "react": "^0.13.0",
  "foo": "^x.x.x",
  "bar": "^x.x.x",
  ... etc ...
}
```

Then create at least one entry point in the app. We'll create two: `client/entry.js` and `server/entry.js`.

In those files, begin importing the NPM dependencies like you would with CommonJS or ES6 module syntax. You can also import local files.

For example, `client/entry.js`:

```js
import React from 'react'
import foo from 'foo'
import bar from 'bar'

import something from './path/to/local/file'

Meteor.startup(x=>
  React.render(<div>Hello.</div>, document.body)
)
```

aliases for modules can be specified in `rocket-module.json`:

```js
{
  "aliases": {
    "elephant": "react"
  }
}
```

then you can do

```js
import React from 'elephant'
```

After you've started the app, the first build will always take longer, of course, and then everything should be cached. Make changes to the files, and rocket:module will rebuild in a matter of seconds.

You'll see output like this in the console:

```
[rocket:module] Compiling for platform "web.browser"...
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPEERINVALID jss-props-sort@0.1.0 requires a peer of jss@^1.0.0 but none was installed.
[rocket:module] Done. Elapsed time: 6181ms
```

give or take NPM messages in between the lines with `[rocket:module]`. After the line

```
[rocket:module] Done. Elapsed time: 6181ms
```

is when you'll notice Meteor is (sometimes) taking it's time to do something. I'm not sure what triggers it. You'd just have to start building and you'll notice it eventually. Perhaps add some local files, try stopping and restarting Meteor, stop and remove `.meteor/local` then restart, etc. I'm not sure what exactly causes it.

**Comment by trusktr** [comment]
@stubailo You can clone rocket:module locally from https://github.com/meteor-rocket/module.

**Comment by trusktr** [comment]
@stubailo Also note that files in any `modules` folder are never handed back to Meteor after rocket:module is done. File outside of `modules` folders are only handed back to Meteor if they are never imported into some other file.

**Comment by trusktr** [comment]
@stubailo I'm in the gitter room too if you wanna chat.

**Comment by stubailo** [comment]
@trusktr I don't think chatting will help at the moment - I'll investigate this repro in more detail and get back to you.

**Comment by trusktr** [comment]
I'll be updating https://github.com/meteor-rocket/module-example-app soon. Maybe I'll be able to have a repro in case you can repro on your end.

**Comment by trusktr** [comment]
@stubailo It seems to be happening only for the client (web.browser) builds in my current case. So, if I edit a file that outside of `server` or `client`, and that file is one that is imported into both `server/entry.js` and `client/entry.js`, then editing the file triggers a build for both sides, and only the client build is taking extra long after `rocket:module` is done in the project I'm currently working.

**Comment by trusktr** [comment]
@stubailo I noticed sometimes Meteor outputs something like `building for platform web.browser`, and sometimes it doesn't.

**Comment by trusktr** [comment]
@stubailo I may have an open source reproducible example for you soon, over at http://github.com/infamous/website.

**Comment by trusktr** [comment]
It's live at http://infamous.io

**Comment by trusktr** [comment]
Oops, wrong button.

**Comment by glasser** [comment]
@trusktr I'm starting to look into this, but can you provide a *full* reproduction? OK, I can clone infamous/website, but then what... run it, edit what file, ?

**Comment by glasser** [comment]
For example, I ran it, then edited `client/entry.js`, but there was no noticeable lag between `[rocket:module] Done. Elapsed time: 7701ms` and `=> Client modified -- refreshing`.

Are you running in `--production` mode, and what you're observing is the minifiers?

**Comment by trusktr** [comment]
That's all, your doing it right. I'll try building on the examples, adding
Meteor packages, and see if it happens in that repo. I've it happens I'll
post back.

/#!/JoePea

**Comment by trusktr** [comment]
@glasser @stubailo I'd really like to help you guys solve this. I'll email you guys access to a private repo where this is happening.

**Comment by trusktr** [comment]
Sent an email with the subject "private repo access".

**Comment by stubailo** [comment]
@trusktr I talked to @n1mmy and we can't look at private repos to reproduce issues. Let me know if there are any more hints so that we can reproduce it on our end.

**Comment by trusktr** [comment]
@stubailo How do I test using a locally cloned version of Meteor?

**Comment by stubailo** [comment]
There's a script in the root of the repository called `meteor` - just run that script instead of the global `meteor` command. So for example:

```
cd ~
git clone https://github.com/meteor/meteor.git
cd meteor; git checkout release-1.2; cd ..
~/meteor/meteor create app-from-checkout
cd app-from-checkout
~/meteor/meteor
```
