### ISSUE TITLE
BrowserPolicy - `default-src` and wildcard bugs

### ISSUE THREAD

**Issue by nathan-muir** [meteor/meteor#5068]
In `BrowserPolicy.content.setPolicy`, `default-src` is copied to every other directive passed. 

This creates some bad CSP's, especially where `'none'` and `*` are concerned.(`'none'` and `*` should preclude all other directives http://www.cspplayground.com/csp_validator).

Also, if you have a directive like `connect-src: *;`  adding sources like `allowConnectOrigin('http://foo.com')` should result in no change.

[Please see branch with added tests](https://github.com/nathan-muir/meteor/tree/browser-policy-bugs). `./meteor test-packages browser-policy`

**Comment by stubailo** [comment]
What would be the optimal solution? Special cases for `*` and `none` where they are not copied to the other directives?

**Comment by nathan-muir** [comment]
Well, I think `setPolicy` / `prepareForCspDirective` shouldn't do _any_ copying from `default-src`. However this would probably break the API for existing users.

At the very least, there should be some method, to add a directive / policy that doesn't inherit from `default-src`. And, special directives should always be excluded (eg `referrer` and `base-uri`).

Aside from copying from `default-src`, the current handling of `none` is -ok-, (it overwrites other directives), there just needs to be similar handling for `*`.

**Comment by hwillson** [comment]
While this issue still exists, I don't really see any reason why we should keep maintaining the `browser-policy-*` packages in core. All functionality provided by `BrowserPolicy` can now be directly replaced by leveraging a 3rd party npm package like [`helmet-csp`](https://www.npmjs.com/package/helmet-csp) (which is actively supported and continues to receive new bugs fixes and features). I think we should consider deprecating the `browser-policy-*` packages.

**Comment by hwillson** [comment]
This is an old issue that hasn't had very much traction in the past 3 years. Given that there are newer / more up to date browser policy related packages available via npm, I'll close this issue for now. If anyone is interested in working on a fix for this though, please let us know and we'll re-open.
