### ISSUE TITLE
Local NPM Packages Support

### ISSUE THREAD

**Issue by hitchcott** [meteor/meteor#5070]
I'm working with a script for the new `registerBuildPlugin` `sources` option in 1.2-rc7. But I do believe this can apply to all of Meteor (or at least the NPM upgrade i'm about to go into).

I was hoping to be able to include a local version of a NPM package I'm developing, but it appears that meteor currently doesn't support it #2876. The workaround was to tarball it somewhere over https, which is a bit of a monster workaround if you want to iterate quickly.

As of NPM v2 it's possible to use the `'module' : 'file:path/to/module'` format, which would be really useful and would solve that issue. 

Furthermore, devel looks like it's is already implemented for Cordova (https://github.com/meteor/meteor/blob/devel/tools/utils/utils.js#L455), but it throws an error for normal apps `npm ERR! notarget Valid install targets` -- it looks like this is because meteor uses it's own fork of NPM 1.x, so it might not be so straightforward.

Anyways, seems like it could be something that would help development of packages that rely on NPM modules.

**Comment by hitchcott** [comment]
Okay, looks like there is a better workaround:
Relative link in your filesystem within the Meteor package
`MyModule = Npm.require '../../../../../../sibling-project-named-MyModule/'`
Absolute doesn't seem to work, so you have to do a few steps of navigation

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this would be a really good feature to have.

**Comment by trusktr** [comment]
Have you tried `npm link`? Does that work?

**Comment by stubailo** [comment]
Added to Release 1.3 milestone, since I think this might be addressed there.

**Comment by abernix** [comment]
I believe you'll find that this works fine with Meteor 1.3 if you [`npm link` your local NPM module appropriately](https://docs.npmjs.com/cli/link).  Feel free to open a bug issue with reproduction if you encounter a problem with using it.
