### ISSUE TITLE
Meteor 1.2-rc.7: Arrow function in Template.helpres wrong this._id context

### ISSUE THREAD

**Issue by hkalic** [meteor/meteor#5071]
Can any one please check the issue I have (METEOR@1.2-rc.7) with ES6 arrow function context.
```javascript
Template.xxx.helpers({
        "selected": ()=>{
            console.log(this._id);
        }
    });
```
results in:
>
undefined

When i try the "old" way:
```javascript
Template.xxx.helpers({
        "selected": function(){
            console.log(this._id);
        }
    });
```
results in correct value.

Am I missing some ES6 knowledge or is this `ecmascript` package bug?

**Comment by rclai** [comment]
Don't use arrow functions in helpers because they will set the context of the helper to the global context.

**Comment by hkalic** [comment]
Ok thanks. Then it's me and my ES6 fu (or lack of)

**Comment by rclai** [comment]
Typically you want to use arrow functions when you're doing callbacks that way you don't have to create a `self` reference to `this`.

**Comment by stubailo** [comment]
The correct way to do this in ES2015 is:

```js
    Template.xxx.helpers({
        selected(){
            console.log(this._id);
        }
    });
```

**Comment by hkalic** [comment]
But isn't that ```selected()``` (from jQuery) for ```Template.xxx.events ``` ?
I meant ```"selected"``` inside helpers.

**Comment by stubailo** [comment]
That code is exactly the same as `selected: function () { ...`
