### ISSUE TITLE
Npm.require not available in meteor shell

### ISSUE THREAD

**Issue by funkyeah** [meteor/meteor#5076]
Maybe this is the intended behavior or maybe I'm making a feature request but Npm.require does not appear to be available within meteor shell.

**Comment by stubailo** [comment]
`Npm.require` is only available inside Meteor packages. Meteor shell runs in the scope of your app.

One option is to use `meteorhacks:npm`, which lets you use NPM packages from your app directly.

Unfortunately, this is not a feature that is possible to implement in Meteor's current packaging model. There are a couple different feature requests this could be: "Let me use NPM packages directly in my app", "Let me run `meteor shell` in the scope of a package", or something else.

What were you thinking?

**Comment by funkyeah** [comment]
I swear Npm.require works in server code outside of packages. Maybe that is unintended but it does seem to work for me. 

I don't want to make a formal feature request and add more work because meteorhacks:npm works just fine for my needs. My main goal was just to point out that it seems to work in server code and not the shell. If the shell is not meant to replicate everything you can do on the server then this is probably a moot point.

**Comment by rclai** [comment]
It _does_ work in regular server code.

**Comment by stubailo** [comment]
Whoa, OK I was actually unaware that it was accessible from there. My mistake!

**Comment by stubailo** [comment]
What happens when you call `Npm.require`? Could you post a screenshot?

**Comment by funkyeah** [comment]
I'm traveling so it might take a while before I can send a screenshot. It
is very straightforward though... just do meteor shell, and then see that
the Npm object is not in the global variable list so trying to use
Npm.require gives the standard error you would expect in that case.

Again, not saying it should be there, just saying it doesn't match the
server environment.

**Comment by stubailo** [comment]
OK, I think it should be there. Let's see what @benjamn thinks - he's out for the week, but he usually works on `meteor shell`.

**Comment by benjamn** [comment]
What is/should the `NODE_PATH` be for non-package server code?

**Comment by zimme** [comment]
Would be nice to have `Npm.require` in app server-side code too. Even though you might have to keep a `package.json` file updated manually with `npm` for it to work as expected.

Although wapping npm packages in meteor packages isn't that much of a hassle.

**Comment by abernix** [comment]
@funkyeah I'm not sure this is relevant anymore since as of Meteor 1.3, you can use NPM directly in your Meteor project using ES6 module syntax and as of 1.3.3 you can even `import "npm-package"` in the `meteor shell`.  Feel free to ping me to reopen if you'd like, but I'm closing this. ;)
