### ISSUE TITLE
[1.2 RC] Meteor doesn't reload after a compile error in JSX

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5080]
As noted in this comment: https://forums.meteor.com/t/first-public-release-candidate-of-meteor-1-2/8986/37

I have personally experienced this issue as well, we can use my app here to repro: https://github.com/stubailo/pr-tracker

Just clone the app, run it, edit App.jsx to cause a compile error, then fix it and it doesn't recompile.

**Comment by sikanhe** [comment]
this also happens for scss

**Comment by stubailo** [comment]
@sikanhe what other packages do you have in your app? In mine, the problem doesn't happen anymore if I remove semantic-ui, I wonder if you have something similar.
