### ISSUE TITLE
Meteor & Polymer Data Binding

### ISSUE THREAD

**Issue by lukicdarkoo** [meteor/meteor#5083]
I am trying to bind array fetched from Mongo to Polymer webcomponent
```javascript
  Polymer({
    is: 'project-collection',
    properties: {
      items: {
        type: Array,
        value: Projects.find({}).fetch(),
      }
    },
...
```
I also tried some variations, I made function objectCollectionSync() to listen changes in Mongo
```javascript
objectCollectionSync = function(mongoCollection, callback) {
  callback(mongoCollection.fetch());
  mongoCollection.observe({
      added: function() {
        callback(mongoCollection.fetch());
      },
      changed: function() {
        callback(mongoCollection.fetch());
      },
      removed: function() {
        callback(mongoCollection.fetch());
      },
      movedTo: function() {
        callback(mongoCollection.fetch());
      },
  });
}
```
and using of objectCollectionSync() in Polymer webcomponent
```javascript
ready: function() {
      objectCollectionSync(Projects.find({}), function(result) {
        this.items = result;
      });
    },
```

With ```<project-collection item="{{ stringify projects }}"></project-collection>``` it works fine, but it seems like a dirty solution. I want to build whole application with webcomponents with just a little bit of Blaze. Is there any non hacky solution?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by brylie** [comment]
Please add your support and comments regarding web component alignment in Blaze 2. See issue #6236.
