### ISSUE TITLE
How to clear out old code after editing and saving?

### ISSUE THREAD

**Issue by KnowledgeGarden** [meteor/meteor#5084]
Occasional recurring issue: edit a file, save, reboot, and see an error message with precisely the old code still being called out. Example, a template copied in from an angular app, and incorrectly modified to use {{#if ...}} but in the wrong place, e.g.

<li {{#if something}} <a ...
corrected to
{{#if something}}<li ..
and saved. Get this error message:

While building the application:
   client/templates/main.html:33: Reactive HTML attributes must either have a
   constant name or consist of a single {{helper}} providing a dictionary of
   names and values.  A template tag of type BLOCKOPEN is not allowed here.
   ...">               <li {{#if isNotAuthentic...

The line number called out is clearly from a much earlier version of the file.
The full code fragment I am trying to compile, from a bootstrap menu, is this

<ul class="dropdown-menu">
            {{#if isNotAuthenticated}}<li>  <a href="/admin/signup">Signup</a></li>{{/if}}
            {{#if isNotAuthenticated}}<li> <a href="/admin/login">Login</a></li>{{/if}}    
            {{#if isAuthenticated}}<li> <a href="/admin/logout">Logout</a></li>{{/if}}
            {{#if isAuthenticated}}<li> <a href="/admin/profile/{{userlocator}}">Profile</a></li>{{/if}}
 </ul>

Saving refuses to change whatever the compiler is working with. What am I missing?
Many thanks in advance for ideas

**Comment by KnowledgeGarden** [comment]
Just in case, this issue showed up on a RedHat 7.1 box and recurs on a Win7 box. It's not the first time I had to find a workaround. In another case, I completely removed a particular method block, and it kept showing up in compile errors, long after it was removed.

**Comment by KnowledgeGarden** [comment]
Final comment, one for which I have no clue. IDE is atom.io. I closed it on the RedHat box and the bug went away. That behaviour did not repeat on the Win7 box.

**Comment by stubailo** [comment]
I haven't encountered this issue before. Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
