### ISSUE TITLE
Hot push not working in some android phone

### ISSUE THREAD

**Issue by harlyluyar** [meteor/meteor#5085]
Hi,

I submitted my android app made from meteor to goole app store,
the weird thing is: in some android cell phone, after the hot push, the css will not work.
Before hot push it was fine.

I tried to resolve it, but no clue at all.
Would appreciate if anyone can help. This is blocking me... :'(

**Comment by martijnwalraven** [comment]
I will need something more to look into this. Preferably a reliable way to reproduce this behavior, but more details at a minimum.

What do you mean by 'the css will not work'? What changes did you make in the version that is being pushed to the phones? What makes you think it only occurs on certain phones and not others? What differentiates these phones from others (Android version, etc.)?

**Comment by harlyluyar** [comment]
Hi Mart,

Try this in your android:  https://play.google.com/store/apps/details?id=com.id1ibcv6d1wapie1ur85c7
See if the style will change.

The css style was working at the first few seconds, but after hot push from server, the css style turn to not work, not style at all, just plain html. The change I made is minor change in <p> content, do not think it will cause this.

I tried it on two exact same android phones, the same android version, one works, one failed.

I found this in other website
"When Meteor does a Hot Code Push, there is the possiblity of caching an unparseable JS or CSS file on the device. This will render the application completely broken and the only course of recovery is to uninstall the application."

To  me, it looks this should be the root cause: the css file pushed from hot push is not parseable, thus css not working.

Hope this can help.

**Comment by harlyluyar** [comment]
Mart, I found this:
"
 could it be that thing I read about where some mobile service providers are injecting some JS for analytics and tracking?? have you checked the developer tools by tethering your phone to your PC and debugging?

Articles mentioning TMobile and Vodafone doing it... (not recent though)

http://www.infoworld.com/article/2925839/net-neutrality/code-injection-new-low-isps.html2

security.stackexchange.com 5
Mobile Carrier Javascript Injection

asked by user102804 on 09:48PM - 01 Dec 11
javascript

stackoverflow.com 6
 Masud Rahman
Stop mobile network proxy from injecting JavaScript

asked by Masud Rahman on 01:25PM - 06 Nov 10
javascript, proxy
"

**Comment by harlyluyar** [comment]
Just tried, and do found it is caused by carrier injecting code.
It works fine if I use wifi, not in att

**Comment by martijnwalraven** [comment]
Good to hear you figured it out! Turns out there is actually a [thread](https://forums.meteor.com/t/no-css-after-hot-code-push/1229/7) about this on the forum.

**Comment by harlyluyar** [comment]
Just put this code into server side:



var connectHandler = WebApp.connectHandlers;
Meteor.startup(function () {
  connectHandler.use(function (req, res, next) {
    res.setHeader("Cache-Control", "no-transform");
    return next();
  })
})
