### ISSUE TITLE
How to use the subscribe that it has only one  item?

### ISSUE THREAD

**Issue by hojas** [meteor/meteor#5086]
```
Meteor.publish('postDetails', function(postId) {
    return Posts.find(postId);
    // In fact, I want to findOne
})
```

```
var postDetails = $meteor.collection(Posts).subscribe('postDetails', postId);
```

How to get the data I want from postDetails ?

**Comment by rclai** [comment]
That should already work. If not make the criteria `{ _id: postId }`.

**Comment by grsabreu** [comment]
You can

```js
$scope.$meteorSubscribe('postDetails', postId).then(function(){
  $scope.post = Posts.findOne();
});
```

**Comment by AlexFrazer** [comment]
If you subscribe by _id, it should only have one result. You can just use `findOne` on the client.

**Comment by stubailo** [comment]
Looks like people have posted good answers. For the future, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker.
