### ISSUE TITLE
Bug for Android Build

### ISSUE THREAD

**Issue by horochovec** [meteor/meteor#5089]
I don't understand what problem I have with this build...

horochovec:mediaglobe$ node --version
v0.12.6

horochovec:mediaglobe$ meteor --version
Meteor 1.1.0.3

horochovec:mediaglobe$ cat .meteor/packages 
meteor-platform
autopublish
insecure
iron:router
differential:vulcanize
accounts-password

horochovec:mediaglobe$ VULCANIZE=true meteor build --directory ../mobile-build --mobile-settings mobile-config.js --server http://xyz.meteor.com --verbose
% Running build for platforms: [ 'android' ]  
% Building the cordova build project          
% Bundling the web.cordova program of the app 
=> Vulcanize: Importing vulcanized file...   -
% Ensuring the cordova build project          
% Reading the mobile control file             
% Running the mobile control file             
% Copying resources for mobile apps           
% Writing new config.xml                      
% Ensuring that platforms in cordova build project are in sync
% Running synchronously:  /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: android 3.6.4
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios

% Ensuring plugins in the cordova build project are in sync { 'org.apache.cordova.console': '0.2.13',
  'org.apache.cordova.file': '1.3.3',
  'org.apache.cordova.file-transfer': '0.5.0',
  'org.apache.cordova.device': '0.2.13',
  'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'org.apache.cordova.statusbar': '0.1.10',
  'org.apache.cordova.splashscreen': '1.0.0' }
% Getting installed plugins for project       
% Running synchronously:  /Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: com.meteor.cordova-update 0.0.1 "CordovaUpdate"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins lock: { 'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2' }
% Copying the JS/CSS files one level up       
% Removing the www folder                     
% Writing www/application folder              
% Writing index.html                          
Error while building for mobile platforms: Unexpected token A

Thats it, the message finished at "Unexpected token A"

**Comment by horochovec** [comment]
I have the same problem build the localmarket example project.

**Comment by martijnwalraven** [comment]
I'm not sure what is going on, but could you try this again with the Meteor 1.2 RC (`meteor update --release METEOR@1.2-rc.10`)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue. If not, let me know, and I'll look into it.

**Comment by horochovec** [comment]
@martijnwalraven 

horochovec:mediaglobe$ meteor --version
Meteor 1.2-rc.10 

horochovec:mediaglobe$ VULCANIZE=true meteor build --directory ../mobile-build --mobile-settings mobile-config.js --server http://xyz.meteor.com --verbose
Local package version is up-to-date: accounts-base@1.2.1-rc.2
Local package version is up-to-date: accounts-password@1.1.2-rc.1
Local package version is up-to-date: autopublish@1.0.4-rc.0
Local package version is up-to-date: autoupdate@1.2.3-rc.1
Local package version is up-to-date: babel-compiler@5.8.22-rc.0
Local package version is up-to-date: babel-runtime@0.1.4-rc.0
Local package version is up-to-date: base64@1.0.4-rc.0
Local package version is up-to-date: binary-heap@1.0.4-rc.0
Local package version is up-to-date: blaze@2.1.3-rc.0
Local package version is up-to-date: blaze-html-templates@1.0.1-rc.0
Local package version is up-to-date: blaze-tools@1.0.4-rc.0
Local package version is up-to-date: boilerplate-generator@1.0.4-rc.0
Local package version is up-to-date: caching-compiler@1.0.0-rc.0
Local package version is up-to-date: caching-html-compiler@1.0.1-rc.0
Local package version is up-to-date: callback-hook@1.0.4-rc.0
Local package version is up-to-date: check@1.0.6-rc.0
Local package version is up-to-date: ddp@1.2.1-rc.0
Local package version is up-to-date: ddp-client@1.2.1-rc.1
Local package version is up-to-date: ddp-common@1.2.1-rc.0
Local package version is up-to-date: ddp-rate-limiter@1.0.0-rc.0
Local package version is up-to-date: ddp-server@1.2.1-rc.1
Local package version is up-to-date: deps@1.0.8-rc.0
Local package version is up-to-date: diff-sequence@1.0.1-rc.0
Local package version is up-to-date: differential:vulcanize@2.0.1
Local package version is up-to-date: ecmascript@0.1.3-rc.1
Local package version is up-to-date: ecmascript-collections@0.1.5-rc.1
Local package version is up-to-date: ejson@1.0.7-rc.0
Local package version is up-to-date: email@1.0.7-rc.0
Local package version is up-to-date: fastclick@1.0.7-rc.0
Local package version is up-to-date: geojson-utils@1.0.4-rc.0
Local package version is up-to-date: hot-code-push@1.0.0-rc.0
Local package version is up-to-date: html-tools@1.0.5-rc.0
Local package version is up-to-date: htmljs@1.0.5-rc.1
Local package version is up-to-date: http@1.1.1-rc.1
Local package version is up-to-date: id-map@1.0.4-rc.0
Local package version is up-to-date: insecure@1.0.4-rc.0
Local package version is up-to-date: iron:controller@1.0.8
Local package version is up-to-date: iron:core@1.0.8
Local package version is up-to-date: iron:dynamic-template@1.0.8
Local package version is up-to-date: iron:layout@1.0.8
Local package version is up-to-date: iron:location@1.0.9
Local package version is up-to-date: iron:middleware-stack@1.0.9
Local package version is up-to-date: iron:router@1.0.9
Local package version is up-to-date: iron:url@1.0.9
Local package version is up-to-date: jquery@1.11.4-rc.0
Local package version is up-to-date: launch-screen@1.0.3-rc.1
Local package version is up-to-date: livedata@1.0.14-rc.0
Local package version is up-to-date: localstorage@1.0.4-rc.0
Local package version is up-to-date: logging@1.0.8-rc.1
Local package version is up-to-date: meteor@1.1.7-rc.1
Local package version is up-to-date: meteor-base@1.0.1-rc.0
Local package version is up-to-date: minifiers@1.1.6-rc.1
Local package version is up-to-date: minimongo@1.0.9-rc.0
Local package version is up-to-date: mobile-experience@1.0.1-rc.0
Local package version is up-to-date: mobile-status-bar@1.0.5-rc.1
Local package version is up-to-date: mongo@1.1.1-rc.2
Local package version is up-to-date: mongo-id@1.0.1-rc.0
Local package version is up-to-date: npm-bcrypt@0.7.8_2
Local package version is up-to-date: npm-mongo@1.4.39-rc.0_1
Local package version is up-to-date: observe-sequence@1.0.7-rc.0
Local package version is up-to-date: ordered-dict@1.0.4-rc.0
Local package version is up-to-date: promise@0.4.8-rc.0
Local package version is up-to-date: random@1.0.4-rc.0
Local package version is up-to-date: rate-limit@1.0.0-rc.0
Local package version is up-to-date: reactive-dict@1.1.1-rc.0
Local package version is up-to-date: reactive-var@1.0.6-rc.0
Local package version is up-to-date: reload@1.1.4-rc.0
Local package version is up-to-date: retry@1.0.4-rc.0
Local package version is up-to-date: routepolicy@1.0.6-rc.0
Local package version is up-to-date: service-configuration@1.0.5-rc.0
Local package version is up-to-date: session@1.1.1-rc.0
Local package version is up-to-date: sha@1.0.4-rc.0
Local package version is up-to-date: spacebars@1.0.7-rc.0
Local package version is up-to-date: spacebars-compiler@1.0.7-rc.0
Local package version is up-to-date: srp@1.0.4-rc.0
Local package version is up-to-date: standard-minifiers@1.0.0-rc.1
Local package version is up-to-date: templating@1.1.2-rc.3
Local package version is up-to-date: templating-tools@1.0.0-rc.0
Local package version is up-to-date: tracker@1.0.8-rc.0
Local package version is up-to-date: ui@1.0.7-rc.0
Local package version is up-to-date: underscore@1.0.4-rc.0
Local package version is up-to-date: url@1.0.5-rc.0
Local package version is up-to-date: webapp@1.2.2-rc.2
Local package version is up-to-date: webapp-hashing@1.0.4-rc.0
                                              
Changes to your project's package version selections:
                                              
blaze-html-templates  added, version 1.0.1-rc.0
hot-code-push         added, version 1.0.0-rc.0
meteor-base           added, version 1.0.1-rc.0
meteor-platform       removed from your project
mobile-experience     added, version 1.0.1-rc.0
standard-minifiers    added, version 1.0.0-rc.1

=> Vulcanize: Importing vulcanized file...   -
Processing mobile-config.js                   
Writing new config.xml                        
Creating Cordova project                      
% Creating a new cordova project.             
Preparing Cordova project from app bundle     
Processing mobile-config.js                   
Copying resources for mobile apps             
Writing new config.xml                        
                                              
/Users/mediaglobe/.meteor/packages/meteor-tool/.1.1.7-rc.10.ij7pvy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
SyntaxError: Unexpected token A
    at Object.parse (native)
    at CordovaBuilder.generateBootstrapPage (/tools/cordova/builder.js:356:12)
    at CordovaBuilder.copyWWW (/tools/cordova/builder.js:336:32)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:124:13)
    at /tools/cli/commands.js:956:24
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/cli/commands.js:948:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at /tools/cli/commands.js:947:10
    at buildCommand (/tools/cli/commands.js:1002:8)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:786:12)
    at /tools/cli/main.js:1377:23

**Comment by martijnwalraven** [comment]
Ah, that helps! It is reporting a syntax error in reading the settings JSON file. It seems you are confusing the [settings file](http://docs.meteor.com/#/full/meteor_settings) with [`mobile-config.js`] (http://docs.meteor.com/#/full/mobileconfigjs). If you get rid of the `--mobile-settings mobile-config.js` option that should do it.

**Comment by horochovec** [comment]
Thanks @martijnwalraven 

Now I have this problem:

Unable to add '/Users/mediaglobe/Projects/xyz/.meteor/local/cordova-build/platforms/android/build/intermediates/assets/debug/www/application/app/bower_components/web-animations-js/web-animations.min.js.gz': file already in archive (try '-u'?)
ERROR: unable to process assets while packaging '/Users/mediaglobe/Projects/xyz/.meteor/local/cordova-build/platforms/android/build/intermediates/res/resources-debug.ap_'
ERROR: packaging of '/Users/mediaglobe/Projects/xyz/.meteor/local/cordova-build/platforms/android/build/intermediates/res/resources-debug.ap_' failed
:processDebugResources FAILED

FAILURE: Build failed with an exception.

**Comment by horochovec** [comment]
@martijnwalraven 

When I build the localmarket example everything works fine, I think this issue is related with Differential-Vulcanize.
