### ISSUE TITLE
Unexepected differences between iOS production & TestFlight on same version number

### ISSUE THREAD

**Issue by mikepaszkiewicz** [meteor/meteor#5090]
I submitted a TestFlight build last week and since, have not made a hot code push to my Modulus instance. On startup, the Test Flight routes as expected to the app's home page with no problem, however, when I load the same app (same version) downloaded from the App Store, I get a ReloadOnResume message.

Where, if at all, does Cordova snapshot the site pointed to in the config.xml? Even clearing/deleting/redownloading all app data results in the same thing.

**Comment by martijnwalraven** [comment]
I'm not sure I understand your issue. What exactly is the difference in behavior between TestFlight and the App Store you're seeing? Does this happen only the first time you open the app?

Cordova stores the data in the application sandbox under `/Library/NoCloud/meteor/<version>`.

**Comment by mikepaszkiewicz** [comment]
My bad, it's a bit difficult to explain...let me try to clarify. Last week, I made a final deployment to my Modulus instance, and submitted my update for iOS beta review, no problem. The update is available in the app store, but everyone who either does the iOS native update or newly downloads it gets a hot code push. To map it out:

**Test Flight Build**:
   - Build 3.4.5
   - Points to production server
   - On startup/redownload, no hot code push activitiy

**iOS production**
   - Build 3.4.5 (now approved)
   - Points to production server
   - Gets a hot code alert on update/fresh download

Only happens upon initial download or update, so just the first time...behavior as usual after that. To me, it doesn't make sense that 1. the same Cordova build is acting differently in App Store vs. TF and 2. the server hasn't been pushed to since before I made the build!

**Comment by martijnwalraven** [comment]
Hmmm, I don't think there should be a difference between the Test Flight and App Store situations. The fact that it only happens once seems to suggest it is getting an update, and it is is satisfied after applying it. Are you sure they are not running slightly different builds (even though they have the same build number)? Even a small change to any file would trigger a Hot Code Push.

**Comment by martijnwalraven** [comment]
This turned out to be a bug in our hot code push code and has been resolved as part of the plugin rewrite that I'm currently working on.
