### ISSUE TITLE
[1.2 RC] Error building Cordova app for platform Android: No match found

### ISSUE THREAD

**Issue by miri-am** [meteor/meteor#5092]
Meteor 1.2-rc.10 

```
public-docking-als-1311:myapp me$ meteor build .build --server https://myhomepage.ch --mobile-settings settings.json
                                              
WARNING: The output directory is under your source tree.
                                              
=> Errors executing Cordova commands:                                              
                                              
   While building Cordova app for platform Android:
   Error: /Users/me/00DEV/myapp/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit code 8 Error output:
   FAILURE: Build failed with an exception.
   
   * Where:
   Script '/Users/me/00DEV/myapp/.meteor/local/cordova-build/platforms/android/CordovaLib/cordova.gradle' line: 128
   
   * What went wrong:
   A problem occurred evaluating root project 'android'.
   > No match found
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   
   /Users/me/00DEV/myapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command: /Users/me/00DEV/myapp/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildRelease,-b,/Users/me/00DEV/myapp/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
   at ChildProcess.whenDone
   (/Users/me/.meteor/packages/meteor-tool/.1.1.7-rc.10.zyk6pl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Socket.<anonymous> (child_process.js:979:11)
   at Socket.emit (events.js:95:17)
   at Pipe.close (net.js:466:12)
```

**Comment by miri-am** [comment]
seems like the problem is caused by my App.info settings:
``
  version: '0.4.6',
  buildNumber: '0.4.6'
```
the exception is caused by the buildNumber including a dot notation. When I do the following, it works:
 ``
  version: '0.4.6',
  buildNumber: '100'
```

I dont know if this works as expected (because buildNumber should be an integer) or if this is an issue. Leaving it open for now in case somebody else encouters this.

**Comment by stubailo** [comment]
@martijnwalraven, can you take a look at this?

**Comment by martijnwalraven** [comment]
Good to see you figured this out! I agree the output is less than helpful, but you would get the same error if you modified `versionCode` in `config.xml` directly. Cordova error reporting could definitely use some work. Unless we want to perform our own validation, there isn't much that we can do to improve this in Meteor I'm afraid.

**Comment by gamedolphin** [comment]
Seems like buildNumber translates directly into android-versionCode ([here](https://cordova.apache.org/docs/en/5.1.1/config_ref_index.md.html#The%20config.xml%20File_core_configuration_elements)) which has to be a number as mentioned [here](https://developer.android.com/tools/publishing/versioning.html).

**Comment by java99** [comment]
I am getting the exact same error with meteor v1.2.0.2: Any ideas on what is causing this?

**Comment by martijnwalraven** [comment]
@java99 If you say you're getting the same error, the solution should also be the same: avoid dots in `buildNumber`. Or is there something more going on?

**Comment by java99** [comment]
Unfortunately not

I am using a mobile-config.js file which states and I tried many more
buildNumber settings

  version: '0.0.10',
  buildNumber: '1'

**Comment by martijnwalraven** [comment]
But are you sure you're getting the exact same error? What specifically have you tried, and what output do you get?

**Comment by java99** [comment]
Yes its the same.

In Meteor 1.1 I could create an apk and launch on android. Of course I added some packages in the meantime and developed it further but now I am stuck getting.

see here
https://forums.meteor.com/t/meteor-1-2-0-2-android-problem/11153

**Comment by martijnwalraven** [comment]
What you posted there is not the same error:
```
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
```
Not sure if this is the root cause, but note that building in the current directory is not a good idea (hence the `WARNING: The output directory is under your source tree`). Could you try this with `meteor build ../mobile-build --server mypage.meteor.com`?

**Comment by java99** [comment]
You are right for the zipException, but the underlying error has the same origin.. maybe that's not so important though. So feel free to redirect or open another issue.

Changing the output Dir to ../mobile-build did not change the error.

**Comment by java99** [comment]
As required in meteor 1.2 I had to specify ANDROID_HOME and ANDROID_SDK. Could this have brought up a conflict with my system's android-sdk? Which version would you recommand to run with meteor 1.2.02 (same for gradle?)

**Comment by martijnwalraven** [comment]
Looking at it some more, I actually think the issue might be that your Gradle installation is corrupt. Could you try `rm -rf ~/.gradle`?

**Comment by java99** [comment]
That was my first guess too, as I did install lots of different
gradle's in the past :)

rm -rf ~/.gradle

Now trying to rebuild... currently (during build) I see
gradle-2.2.1-all left.. Is this the one meteor 1.2 likes?

**Comment by martijnwalraven** [comment]
So has reinstalling Gradle fixed your problem?

As far as I know, the Gradle dependency is part of the Cordova Android platform, and it should be downloaded automatically during build. We don't have much control over that from the Meteor side.

**Comment by java99** [comment]
rm -rf ~/.gradle

solved it. Thanks heaps @martijnwalraven !

**Comment by jensenmobile** [comment]
Error: /Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/build.gradle' line: 253

* What went wrong:
A problem occurred evaluating root project 'android'.
> Project with path ':androidOpenCVExample' could not be found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
