### ISSUE TITLE
Enable adding entire folder as source in package

### ISSUE THREAD

**Issue by cleor41** [meteor/meteor#5093]
As of now the only way to add a file to a package's source is by using

```javascript

api.addFiles('email.js', 'server');

```

This is great if you need to have fine grained control but it's tedious to add this line for every file. There should be an option to use a more coarse approach. For example, maybe an option to add an entire folder and the load order is determined like how it is in a normal app.

**Comment by sebakerckhof** [comment]
Even better would be support for [glob](https://www.npmjs.com/package/glob) style file identifiers

**Comment by avital** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

In general we're not trying to add new features to the project specification format until we have a chance to do a broader rewrite as part of this project: https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order

**Comment by avital** [comment]
Closing the ticket, as this is being tracked in our roadmap.
