### ISSUE TITLE
Spacebars: Objects/ Array as arguments

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#5095]
At the moment Spacebars doesn't allow `Object`s and `Array`s as arguments in template helpers, only  `number, string, boolean, or null`. It would be a great addition allowing those two types as well.

**Comment by avital** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

To clarify, do you mean passing in object or array literals directly in your template's .html file? Like `{{foo [1, 2, 3]}}`? That's something we've talked about for a while, under the umbrella name "expressions in templates". We're still figuring out our exact roadmap for Blaze/Spacebars so we won't be implementing this in the near future.

Passing in arrays or objects via other helpers is definitely possible, though annoying: `{{foo bar}}` where `bar` is a helper that returns `[1, 2, 3]`

**Comment by mitar** [comment]
There was a bit of discussion of this in #4101. At least for object literals this could probably be quite easy to be done by extending current nested expressions.

So `{{foo (a=1 b=2)}}` would be one object passed as the first argument to `foo` helper.

As a workaround, there could be helpers for now:

```handlebars
{{foo (object a=1 b=2)}}
```

`object` would just pass through stuff (simply passes `.hash` value of the argument).

```handlebars
{{foo (array 1 2)}}
```

And this returns an array (simply passes `arguments` through?)`.

**Comment by mitar** [comment]
What symbols are allowed for helpers? Could it be something like {{foo (~ a=1 b=2)}}`?

**Comment by PandaWhisperer** [comment]
I just stumbled on this issue after googling whether it's possible to have inline objects in Blaze. 

I really liked @mitar's [idea](https://github.com/meteor/meteor/issues/5095#issuecomment-149053809), so I gave it a try, and low and behold, it actually works. I wrote two helpers as follows:

```javascript
// This allows us to write inline objects in Blaze templates
// like so: {{> template param=(object key="value") }}
// => The template's data context will look like this:
// { param: { key: "value" } }
Template.registerHelper('object', function({ hash }) {
  return hash;
});

// This allows us to write inline arrays in Blaze templates
// like so: {{> template param=(array 1 2 3) }}
// => The template's data context will look like this:
// { param: [1, 2, 3] }
Template.registerHelper('array', function() {
  return Array.from(arguments).slice(0, arguments.length-1);
});
```

Both helpers can be combined:

    {{> template param=(object foo="bar" things=(array 1 2 3)) }}

Will result in the template's data context looking like this: `{ param: { foo: "bar", things: [1, 2, 3] } }`.

**Comment by LeNiglo** [comment]
Hey @PandaWhisperer,

Your idea looks nice but on which version of Meteor does this work ?
I see you are using with for template but it should work the same for helpers, right ?
I use Meteor 1.4 and this is my code :

```html
<a class="navbar-brand {{ activeIfTemplateIs templates=(array 'index' 'home') }}" href="{{ pathFor 'home' }}">Home</a>
```

```js
Template.registerHelper('object', ({ hash }) => {
	return hash;
});

Template.registerHelper('array', () => {
	return Array.from(arguments).slice(0, arguments.length - 1);
});

Template.registerHelper('activeIfTemplateIs', (arg) => {
	var currentRoute = Router.current();
	console.log(arg);
	// Here I need to access my array ['index', 'home', ...]
	return '';
```

The output looks like :
https://puu.sh/qJ9Np.png
