### ISSUE TITLE
Only add collection methods if allow/deny is being used

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#5096]
**_1 Upvote**_ When creating a collection `new Mongo.Collection('posts')`, Meteor will create some methods automatically: `posts/insert`, `posts/update`, `posts/remove`, maybe some more. Please prefix these methods somehow, like `_meteor/posts/insert`; as creating a `posts/insert` method for a `posts` collection seems to be the right name (that's why you're using it), it shouldn't be blocked.

**Comment by stubailo** [comment]
Couldn't agree more!

As a workaround, I've been using `add` instead of `insert` for my own methods.

**Comment by stubailo** [comment]
@zimt28 in a very late response, would it work for you to simply not have these methods if you're not using allow/deny for that collection?

**Comment by mitar** [comment]
+1

**Comment by zimt28** [comment]
@stubailo This would work great for me!

**Comment by mquandalle** [comment]
I also support collection methods customization as @stubailo started to implement in #5559.

One use case I encountered in Wekan is that I wanted to define a set of *mutations* at the model level (instead of dispersing minimongo queries all over the code base) and at the same time benefit from re-usable security checks à la allow/deny. Currently I ended up defining my mutations like this:

https://github.com/wekan/wekan/blob/dd101543920148a48b74541ebbbaca97f6bc6d11/models/boards.js#L124-L213

Which I am pretty happy with. I have some ideas to improve this API (and the underlined DDP method calls) and the abstraction of `CollectionPrototype._defineMutationMethods` will be super helpful!

**Comment by mquandalle** [comment]
Well I read a little bit too quickly, `CollectionPrototype._defineMutationMethods` isn’t the kind of abstraction I hoped it was, but still the possibility to remove and replace allow/deny mechanism is great.

**Comment by stubailo** [comment]
Yeah I'm like 5% into implementing this stuff - the first step is taking exactly what exists now and refactoring a bit, the second step will be adding new APIs to decouple allow/deny and collections.

**Comment by stubailo** [comment]
> abstraction I hoped it was

What are you hoping for?

**Comment by mquandalle** [comment]
It’s just that from reading the name I thought it was a function to define methods to mutate the collection, something that would that would put a DDP method under a dedicated “namespace” and expose the collection object to this method, and then things like Mongo  `insert`, `update`, and `delete` or even things like `rename` or `changeColor` like my above example in Wekan could rely on this.

**Comment by stubailo** [comment]
You can do this easily in user-space, though, right?

```js
Meteor.methods({
  "/collection/something"(x) { ... }
});

MyCollection.something = function (x) { Meteor.call(x) };
```

There would be some extra boilerplate involved for validation and error handling, but it could be easily done in a package I would think.

**Comment by zimt28** [comment]
@zol Are you guys working on this? Otherwise I'd close this issue, as it doesn't seem to be a real issue for most people.

**Comment by zimt28** [comment]
@zol Let's do it the other way around, please re-open if you're fixing this.

**Comment by stubailo** [comment]
I got about halfway - I split allow deny into a separate package, but it's not yet removable. I'd like to get this done.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Only%20add%20collection%20methods%20if%20allow%2Fdeny%20is%20being%20used&body=Migrated%20from:%20meteor/meteor%235096) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
