### ISSUE TITLE
When adding packages, Meteor sometimes uses very old package versions

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5101]
Yesterday, I had a quite hard time getting the edgee:slingshot package to work, debugging it heavily because the code just did not behave as stated in the documentation.

Eventually, I found the root cause: Although I included it in my package like this:
```js
api.use('edgee:slingshot');
```
Meteor used a very, very old version of this package (0.0.3) instead of the latest one (0.7.1). To cross-test this behaviour, I also tried
```sh
meteor add edgee:slingshot
```
and saw the same behaviour. I did a
```sh
meteor list
```
immediately after that, and in fact it showed that slingshot was on version 0.0.3 and that there was a new version available. Only after running
```sh
meteor update
```
the package was updated to 0.7.1.

However, this did not help me for my package, so I had to use
```js
api.use('edgee:slingshot@0.7.1');
```
now, but that's not optimal.
I reported this issue to the maintainer of the slingshot package, but he told me that he also had noticed this behaviour with other packages. Hence, I would like to address it to the core Meteor team instead.

**Comment by zimt28** [comment]
Have a look at this issue: https://github.com/meteor/meteor/issues/4093

**Comment by derwaldgeist** [comment]
I don't think #4093 is related to this behaviour, since #4093 basically refers to the version of the main Meteor application.

**Comment by avital** [comment]
This is Meteor's behavior for indirect package dependencies (ie dependencies of a package that your app depends on). The reasoning is that you should get whatever version of the indirect dependency the package you're using was tested against when published.

You can find a lot more discussion about this on https://github.com/meteor/meteor/issues/4170 and https://meteor.hackpad.com/Packaging-UX-Gravity-Hurts-FoTnLTVUklt

Closing as a (mostly) dup of #4170

**Comment by derwaldgeist** [comment]
Thanks for this link. But this still doesn't explain why this also happens if you are adding a package as a top-level dependency, e.g. by using:
```
meteor add edgee:slingshot
```
