### ISSUE TITLE
[1.2 RC] Meteor.user() is undefined after Meteor.loginWithPassword() using remote DDP connection

### ISSUE THREAD

**Issue by scsirdx** [meteor/meteor#5103]
In meteor 1.1.0.3 i used following code to connect my mobile app to server and login to it:
```javascript
Meteor.loginWithPassword(email, password, function (e) {
        if (e) {
            console.log(e);
            Session.set('ddpErrors', e);
        }
        if (Meteor.user()) {
            console.log(Meteor.user());
        }
        return;
    });
```
and: 
```javascript
Meteor.startup(function() {
DDPConnection = DDP.connect('https://<server address>:443/');

Meteor.connection = DDPConnection;
Accounts.connection = Meteor.connection;
Meteor.users = new Meteor.Collection('users', {
    connection: DDPConnection
});
Meteor.connection.subscribe('users');

console.log(DDPConnection);
});
```
After installing 1.2rc (from 7 to 12) Meteor.user() is always undefined.
Am i doing it wrong way, or it is a bug?

Here is an example code to reproduce this:
https://github.com/scsirdx/ddp-meteor-1.2.git

**Comment by avital** [comment]
I'm not totally sure about this specifically, but modifying internals in Meteor (such as `Meteor.users`) is definitely likely to break with future versions of Meteor.

For your use-case specifically, there's a `--server` option to `meteor build` that should set the default connections to whatever server you choose. Does this solve your problem?

**Comment by scsirdx** [comment]
I'm running client using: meteor run --port 3001 --mobile-server https://<ip>:443
It does not solve problem in 1.2-rc

**Comment by martijnwalraven** [comment]
What is it you're trying to accomplish? In most cases, there should be no need to set up a DDP connection yourself and hook this up manually to the Accounts system.

As @avital mentions, modifying internals in this way is likely to break. Here, I believe the issue is that you are setting `Meteor.users` while Meteor 1.2 refers to the collection as `Accounts.users` (although it sets up `Meteor.users` as an alias).

**Comment by scsirdx** [comment]
I have one main app (server with web interface). And several client cordova apps. Client apps have totally different interface and libs, so i cant just use ```if isCordova``` and so on.
After several hours of reading docs, googling, reading meteor forum and experimenting i found that solution.
Thank you for telling about ```Account.users```, all working fine now.
It would be **really great** if you tell how to achieve remote ddp login without using this 'hack'.

Discussions on meteor forum:
https://forums.meteor.com/t/connecting-2-apps-over-ddp-how-to-login-across/977/29
https://forums.meteor.com/t/can-you-connect-to-a-separate-meteor-application-with-ddp/7595/4

**Comment by martijnwalraven** [comment]
You're right, there is currently no public API to make the Accounts system use a different DDP connection, although some work to prepare for this has been done internally. I'm glad your solution is working for you in the meantime.
