### ISSUE TITLE
Spacebars {{#let foo=bar}}{{/let}} interpreted as 'let' template

### ISSUE THREAD

**Issue by thomasvanlankveld** [meteor/meteor#5105]
"Let" is interpreted as a template.

```handlebars
{{#let bar=foo}}
  {{bar}}
{{/let}}
```

produces `Uncaught Error: No such template: let`

[Meteorpad](http://meteorpad.com/pad/QKvqyA3YtgbRHD35u/Leaderboard)

**Comment by Slava** [comment]
This feature is not released yet, it is going to be part of 1.2.
