### ISSUE TITLE
How do I use HTML entities on template?

### ISSUE THREAD

**Issue by joonas-yoon** [meteor/meteor#5111]
`&nbsp;` is able to write(or echod on browser) on template. but `&quote;` is not.

I have message with this problem.
```
Errors prevented startup:                  
   
   While building the application:
   client/templates/notifications/notifications.html:33: Character reference requires
   semicolon: &quot
   ...mmented on your post &quote;{{notificatio...
   ^
```

and html code(on template) is:
```
<p>commented on your post &quote;{{notificationPostTitle}}&quote;</p>
```

just do i use a character `'` instead of `&quote;`?

Thanks to read.

**Comment by hitchcott** [comment]
It's `&quot;` ;)

**Comment by joonas-yoon** [comment]
huh! Sorry for my stupid issue... thanks a lot :cry:

**Comment by avital** [comment]
Happy you figured it out!
