### ISSUE TITLE
[1.2 RC] Cannot update due to package constraints (from 1.1.0.3)

### ISSUE THREAD

**Issue by wallslide** [meteor/meteor#5112]
I have a meteor project running on version 1.1.0.3, and I get the following message when attempting ```meteor update --release METEOR@1.2-rc.12```:

```This project is at the latest release which is compatible with your current package constraints.```

Since our project has more than 60 packages, it is going to be very tedious to try to manually discover what is causing the conflict. Any advice on how to resolve this issue? 

Thanks

**Comment by hitchcott** [comment]
What happens if you manually edit your `.meteor/release` file?

**Comment by wallslide** [comment]
I ended up going through the packages in one of my projects, and figuring out that the culprit was ```enteye:spinner```.

**Comment by dgreensp** [comment]
This is a poor user experience, I agree.  We were just talking about this issue the other day, and I've opened a ticket for it: https://github.com/meteor/meteor/issues/5114

Glad you found the culprit!  Closing this issue.
