### ISSUE TITLE
Updating release doesn't explain package version conflicts

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#5114]
When you update your release with `meteor update` or `meteor update --release ...`, if there are package version constraints that make the new release not possible to select, you just get a message like: `This project is at the latest release which is compatible with your current package constraints.`  This is unhelpful for the user in the fairly common scenario where a package is blocking an update to the Meteor release.

The reason for the rather odd message is that `maybeUpdateRelease` in https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js has one code path for "updating" the release, which either tries a single release or a series of releases, depending on whether you asked for a specific one or just typed `meteor update`.  This function has no code to explain anything about version conflicts.

**Workaround:** Change the release version manually in `.meteor/release`, and then Meteor will print version conflicts.

**Comment by stubailo** [comment]
Fixed, will come out in the next RC.

**Comment by mjmasn** [comment]
@dgreensp Just to note that the workaround listed here didn't work, and the issue I had (which gave the same ambiguous error message) was actually with local packages that had something like:

```javascript
api.addFiles([
    'some/image.png',
    'some/styles.css',
    'another/image.jpg',
]);
```

In this case I needed to move the png and jpg to an `api.addAssets` call. @stubailo I haven't looked at the fix but could you confirm it would flag this kind of issue as well as package upgrade issues.

**Comment by stubailo** [comment]
I don't think it's possible that `addFiles` would cause a version solver error. The error you would get if it was related to `addFiles` would be a syntax error that `addFiles` isn't defined. Are you sure that was the problem?

Is it possible to create a minimum reproduction of an app that has these properties and can't be updated?

**Comment by dgreensp** [comment]
@mjmasn, when you say the workaround didn't work, what do you mean?  What happened when you changed `.meteor/release` and ran Meteor?

Did you run `meteor update` after that, and before changing your package.js, and find that it swallowed the actual error?  If so, does putting your package.js back the way it was and running `meteor update` reproduce swallowing the error?

**Comment by dgreensp** [comment]
This is actually the second case of a non-version-conflict error being swallowed; see https://github.com/meteor/meteor/issues/4943#issuecomment-140103662

In that case, the user ran `meteor update --release ...`, which should springboard to the new tool immediately, not in maybeUpdateRelease.  Not sure what's going on there.

**Comment by mjmasn** [comment]
@dgreensp I think I've confused myself, because having created a reproduction your workaround does seem to work. I wonder if I did something else to screw it up - had been trying to get 1.2 to work for a couple of hours by this point. Apologies for the false alarm.

The issue wasn't actually images but an `api.addFiles` call with the `{ isAssets: true }` parameter. https://github.com/mjmasn/meteor-5114-repro if it's of any use...
