### ISSUE TITLE
Login/logout race condition with multiple tabs

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#5115]
When you have multiple tabs open, logging out and logging back in quickly can sometimes cause you to be logged out.

Repro: https://github.com/meteor/issue5115

**Comment by zenweasel** [comment]
The behavior I noted is that as you increase the number of tabs, the number of times the tab on the far right gets logged out increases (i.e. with 20 tabs, the tab on the far right appears to get logged out 19 times). It sort of appears the logouts "cascade" to the right (in Chrome at least).

**Comment by aaronjudd** [comment]
I think that it may become more obvious when you have any other kind of processing happening in `Accounts.onCreateUser` - in our case, when a user logs out, we're creating a new anonymous user immediately, with some additional processing, and while I can't prove it, I feel like that makes matters worse. 
It is a pretty significant issue though, surprised it hasn't been reported more often.

**Comment by abernix** [comment]
I'm not sure I can reproduce in the latest version of Meteor with the reproduction provided.  While the other tabs do log out at a slightly different pace than the primary tab, it does seem to sort itself out and maintain the current state.

### Just two tabs, based on reproduction description
![screen recording 2016-11-01 at 04 28 pm](https://cloud.githubusercontent.com/assets/841294/19893060/7f3792b0-a050-11e6-94e6-59672586351b.gif)

*****

### 6 tabs and clicking really fast, to be a bit more dramatic.
![screen recording 2016-11-01 at 04 38 pm](https://cloud.githubusercontent.com/assets/841294/19893451/e37126b4-a051-11e6-8438-ec142f6971d6.gif)


Advice on how to confirm this as a bug still?  Or is it resolved?  (In other words, can be close this as we're going through old issues? :smile:)

**Comment by abernix** [comment]
Closing per my previous comments which lead me to believe this is no longer an issue.
