### ISSUE TITLE
[1.2 RC] `this.userId` not working as expected when fat-arrow functions used in `Meteor.publish()`

### ISSUE THREAD

**Issue by geekydatamonkey** [meteor/meteor#5116]
In meteor1.2-rc.12, `this.userId` in `Meteor.publish()` doesn't seem to work as expected when using ES2015 fat arrow functions `() => {...}`. 

For example,this code gives different results:

ES5 flavored:
```
Meteor.publish('tasks', function() {
  return Tasks.find({ owner: this.userId });
});
```

ES2015 flavored, with fat-arrow anonymous functions (and `this` binding):
```
Meteor.publish('tasks', () => {
  return Tasks.find({ owner: this.userId });
});
```

Here's a demo repo:
https://github.com/geekydatamonkey/meteor1.2-rc.12-fat-arrow-in-publish

Also, deployed here:
http://meteor-1.2-rc.12-fat-arrow-in-publish.meteor.com

**Comment by grsabreu** [comment]
Because the scope within fat-arrow functions are the outside scope that the function is being defined. 
So `this` keyword will be the Node's `global` var.

**Comment by gitawego** [comment]
yes,  I think it works as intended

**Comment by glasser** [comment]
As @grsabreu and @gitawego said, this is just how fat-arrow syntax works.  You'll have to avoid using fat arrow syntax at the top level of `Meteor.publish` for this reason.

We're pretty excited about using ES2015 in Meteor, including fat-arrow functions, so it's likely that future APIs will avoid the use of `this` in this way and perhaps provide an alternative for existing APIs.
