### ISSUE TITLE
Official support for webpack

### ISSUE THREAD

**Issue by harisvsulaiman** [meteor/meteor#5117]
If we can include webpack to build meteor app , using the upcoming plugin api, it would remove load order issues , partial code loading etc . I saw one implementation here. 
https://github.com/meteor-rocket/module

**Comment by avital** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Webpack is definitely something we're looking closely at as we make more concrete plans for the future of Meteor's build system, and the experimental meteor-rocket project is also very interesting. Let's see what happens out of it!

**Comment by AdamBrodzinski** [comment]
@avital if you haven't seen it already checking out https://github.com/jedwards1211/meteor-webpack-react might be interesting. I've even created a Blaze branch that uses a spacebars loader :smile: 

I've switched all most all of my apps over to using it and i've seen big productivity gains, especially with hot-code-patching. With cheap source maps i'm getting ~0.8 second reloads on a 2012 rMBP.

Having first class ES6 support is also really nice for one of my larger apps as they're *finally* not exposing tons of globals.

**Comment by vjau** [comment]
This would also make most of the work toward #4888.

**Comment by jedwards1211** [comment]
Rewrite the core Meteor packages as NPM packages...just sayin' :)

**Comment by jedwards1211** [comment]
@harisvsulaiman @avital the thing I don't like about `rocket:module` is, as far as I can tell, it doesn't seem intended to let users configure Webpack themselves, but rather just provide a run-of-the-mill ES6 environment.  People who want to use Sass, Typescript, etc. may be left out.

**Comment by avital** [comment]
@AdamBrodzinski that looks very cool! i think that's an approach we should learn more about.

**Comment by avital** [comment]
I updated my initial response to refer to meteor-webpack-react as well.

**Comment by AdamBrodzinski** [comment]
@avital @stubailo  You may also want to checkout [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform) which implements hot-patching via [react-transform-webpack-hmr](https://github.com/gaearon/react-transform-webpack-hmr).

It seems like Meteor could take advantage of the hot-patching (which is super fast) by using a babel transform. However I haven't tried this yet... it seems like it plugs into React-Native which doesn't use webpack either.

**Comment by AdamBrodzinski** [comment]
Update. You guys may want to checkout this webpack approach. It's a package that can be added to enable webpack and it feels like a built-in feature! 
https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264

Using webpack is the only thing that's keeping me using Meteor... globals and 15 second reloads are untenable when trying to iterate.

**Comment by harisvsulaiman** [comment]
15 secs feels like a lifetime. I think webpack is the way to go!
