### ISSUE TITLE
[1.2-rc12] Meteor.settings should be empty object but it's not.

### ISSUE THREAD

**Issue by phfrohring** [meteor/meteor#5118]
[Recipe](https://github.com/phfrohring/meteor-settings-bug)

# meteor-settings-bug

[Meteor doc](http://docs.meteor.com/#/full/meteor_settings)
> If you don't provide any settings, Meteor.settings will be an empty object.

```
$ cd app/
$ meteor
I20150908-15:34:42.365(2)? Meteor.settings: {"public":{}}
```

**Comment by dgreensp** [comment]
This change is due to a PR: https://github.com/meteor/meteor/pull/4704

I will ask about this there.

**Comment by dgreensp** [comment]
@phfrohring This change was intentional.  Thanks for pointing out the inconsistency with the docs.

Did this change cause a problem for your app, or are you just pointing out the discrepancy?

**Comment by dgreensp** [comment]
I think the original point the docs were making is that `Meteor.settings` always exists as an object, whether or not there is a settings file.  Now, additionally, `Meteor.settings.public` always exists as an object, whether or not there are any public settings.  So the proposed course of action is to change the docs to say this.

**Comment by dgreensp** [comment]
Fixed the docs.  Let me know know how this solution works for you.  Thanks!

**Comment by phfrohring** [comment]
@dgreensp It works. Thanks!

Here the use case, let's say that you want to do:
```
$ meteor --settings settings.json
```

and that you check the pattern of `settings.json` using `check`: then you get an error for unexpected `public` field showing up.

It suffice to change the `check` pattern to solve this: easy enough... 

I cannot see in anyway why changing the doc would not suffice.
