### ISSUE TITLE
[1.2RC] Public folder assets not accessible in mobile build

### ISSUE THREAD

**Issue by gamedolphin** [meteor/meteor#5119]
This is for meteor 1.2rc12.

The images stored inside the /public folder seem to inaccessible in the mobile debug build.  The project also had crosswalk plugin. After unpacking the debug apk, the public assets seem to be stored in a folder called 'app' and adding 'app' in front of the assets , as in, 'app/imgs/image.png' seemed to provide access.

**Comment by martijnwalraven** [comment]
As part of the build tool improvements for Meteor 1.2, application assets are now stored in a `app` directory, but they should still be accessible using the familiar URL (without the app prefix). This works for normal webapps, but is more difficult to get right for Cordova. I've made some temporary changes to our plugin that I hope will fix these issues for now.

**Comment by stubailo** [comment]
This should be fixed in the just released 1.2-rc.14. Try it out!

**Comment by gamedolphin** [comment]
It's fixed. Thank you!
