### ISSUE TITLE
Docs: Dangling link to Tracker chapter in Meteor Manual

### ISSUE THREAD

**Issue by aknuds1** [meteor/meteor#5120]
In the [Meteor docs](http://docs.meteor.com/#/full/tracker), there's a [dangling link](http://manual.meteor.com/#tracker) to a Tracker chapter in the Meteor Manual ("visit the Tracker chapter in the Meteor Manual"). As a matter of fact, I can't find a single reference to Tracker in the Meteor Manual.

**Comment by stubailo** [comment]
I removed the link: 423c424e1d384355fcf8b72bb7c4b4f48da10654

I think the Meteor manual isn't very helpful and it can be confusing for people who go there to learn more about Tracker. It also probably won't be kept up to date in the future, so I think it is best to remove the reference.

This change will get deployed when we publish Meteor 1.2 in the coming week or so.
