### ISSUE TITLE
Accounts package loginExpirationInDays option not working

### ISSUE THREAD

**Issue by bradvogel** [meteor/meteor#5121]
**_5 Upvotes**_ According to the docs at http://docs.meteor.com/#/full/accounts_config, the code:

```
Accounts.config({
    loginExpirationInDays: null
});
```

should disable login token expiration. However, I'm not sure this is working locally for me. After looking into the code briefly, it looks like line https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_common.js#L170 should include check for `null` explicitly like what is done on the server-side here: https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_server.js#L879

Is that a bug?

**Comment by bradvogel** [comment]
Additionally, it looks like the function https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_common.js#L170 is called synchronously when the app boots up, unsetting the login token (using the default loginExpirationInDays value of 90 days), before my Accounts.config() call has even been run. Shouldn't this be on a defer to wait for Accounts.config() to be called?

**Comment by bradvogel** [comment]
Also filed https://forums.meteor.com/t/anyone-using-the-loginexpirationindays-null-accounts-option-to-disable-auto-logout/9640

**Comment by benjamn** [comment]
This looks like a real bug that would be worth fixing. Thanks for the report!

**Comment by bradvogel** [comment]
Ping @benjamn @stubailo . Would be great to fix this :)

**Comment by psyfreak** [comment]
+1

**Comment by svda** [comment]
+1

**Comment by CTimmerman** [comment]
I managed to set the meteor_login_token cookie to end with the browser session, but next start it gets set again from localStorage. If i delete localStorage["Meteor.loginToken"] then the cookie disappears as well and the login is gone.

**Comment by khell** [comment]
It would be really appreciated if this could be fixed!

**Comment by Lenin7** [comment]
It's been 6 months. Any updates for this?

**Comment by bradvogel** [comment]
+1 This is a big issue for us (Mixmax)

**Comment by lorensr** [comment]
Haha you're keeping an upvote tally @top? Count me in 😊

**Comment by redreamality** [comment]
any updates？

**Comment by redreamality** [comment]
BTW will this plugin work?
https://atmospherejs.com/mbanting/cordova-accounts-resume

**Comment by bradvogel** [comment]
Bump on this. This is really bad.

**Comment by Kestanous** [comment]
+1

**Comment by leizard** [comment]
+1

**Comment by Kestanous** [comment]
+1

**Comment by mattiLeBlanc** [comment]
I know it is a slight variation, but it would be nice to configure the expiry in minutes too!
I want the session to expire (financial product) more aggressively and it is very hard to do this right now.

**Comment by ntoepker** [comment]
temporary bugfix: set services.resume.loginTokens.when in the user object to a future date to achieve that the login doesn't expire

**Comment by glasser** [comment]
I agree that there is a bug here.  One workaround would be to set loginExpirationInDays to a very large number like `365*30` (30 years) rather than null.

**Comment by SimonSimCity** [comment]
@mattiLeBlanc I was also looking for this feature and started off setting `loginExpirationInDays` to `(1 / 24 / 60) * 15` to have it at 15 minutes, but the lowest I could go was `0.05`, which equates to 1.2 hours ... But this might be another issue.

**Comment by SimonSimCity** [comment]
@mattiLeBlanc Please vote for https://github.com/meteor/meteor-feature-requests/issues/119
