### ISSUE TITLE
some things do not render on Android but render in iOS, browser

### ISSUE THREAD

**Issue by cmethod** [meteor/meteor#5122]
I'm trying to build a simple mobile website (crystalchen.meteor.com) which works fine in the browser and if viewed on iOS but will be missing various components when viewed on an Android device. I'm really lost here and I would greatly appreciate any pointers in the right direction to resolve this. Thanks!
![screen shot 2015-09-08 at 1 24 08 pm](https://cloud.githubusercontent.com/assets/14011720/9746464/ea10d3a4-562c-11e5-87f5-56e263286939.png)
![screen shot 2015-09-08 at 1 23 08 pm](https://cloud.githubusercontent.com/assets/14011720/9746465/ea128ece-562c-11e5-8962-129e8425f101.png)

**Comment by rjakobsson** [comment]
Without knowing your specific problem - I'm guessing that this is probably not an issue with Meteor, but with the rendering engine on your android device. Is your CSS using any properties that Android doesn't support? Check out http://caniuse.com .

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

If you are trying to report a bug in Meteor, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
