### ISSUE TITLE
Meteor deploy add upload progress

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#5126]
**_1 Upvote**_ This is super crucial. I'm deploying right now from the Philippines, my speed is quite slow right now. I'm deploying my app (probably with too many static resources being uploaded but still) and it's taking forever. Having a progress bar to see how much longer it'll take to deploy would be really nice.

The same should be done for Galaxy of course.

**Comment by dcworldwide** [comment]
Similiar for me. Could be useful. I find myself watching 'uploading.....' wondering when it will finish. Sometimes I get timeouts of late

**Comment by stubailo** [comment]
hanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I don't know when we will get to implementing this, but it might be possible for someone to submit it as a pull request.

Here's the code: https://github.com/meteor/meteor/blob/5a36f344e8fdc9f9703e549b3728bba540f095d4/tools/meteor-services/deploy.js#L432

You would just need to measure how much of the stream has finished somehow.

**Comment by edvinsalo35** [comment]
I am also getting similar problem. I am seeing "uploading" so long time, but still have to wait.

Is there any way to see the upload percentage at least so that I can notice how much should I wait?

**Comment by laosb** [comment]
+1 for this. Digging the code.

**Comment by dcworldwide** [comment]
This is still one of my biggest productivity killers..... 

Lately I've had a very quirky issue where a 3rd party api returns different data once my app is deployed. To debug, I had to use a process of elimination approach which required lots of console logs, code assertions etc. Each time I wanted to test a fix, I had to deploy the app again. As it takes ~10 minutes for me to deploy (even on galaxy), this has been a very time consuming process.  

I appreciate that community pull requests are welcome, I would love to dig into the code and try and fix this, but I really don't have the time. I would have thought this was very much a core product issue.

**Comment by jsantana90** [comment]
any update on this?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20deploy%20add%20upload%20progress&body=Migrated%20from:%20meteor/meteor%235126) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
