### ISSUE TITLE
Cannot deploy an app because of Network error: wss://packages.meteor.com/websocket: write EPIPE

### ISSUE THREAD

**Issue by iboxgithub** [meteor/meteor#5129]
Hi,

when I'm trying to do a "mup deploy" on my app I have a crash saying

Error connecting to package server: Network error: wss://packages.meteor.com/websocket: write EPIPE
Warning: could not connect to package server

I don't find this specific issue with EPIPE on internet, did anyone already run into that issue?

Thanks for your help

**Comment by stubailo** [comment]
Does this issue always happen, or is it only sometimes? It could just be a temporary issue with the package server.

**Comment by iboxgithub** [comment]
Hi, indeed, I reproduced it twice but never since then...whereas I had internet so I dont understand..whatever, I close the defect and will get back to it if I find a way to reproduce

**Comment by stubailo** [comment]
Yeah I'm saying it was an error on our end, but it was temporary. So it's good that it works now.
