### ISSUE TITLE
Env: node: No such file or directory

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#5134]
I'm testing meteor 1.2rc and receiving an error when attempting to run on android-device (everything works fine running on the browser).

Additional information:
1) I was on meteor 1.1.0.3 and everything was working fine on android-device

2) Upgraded to meteor 1.2rc-11 (then rc-12), created a new default project (meteor create ym)

3) Followed the steps reported here to install Android SDK on Mac: https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac

4) Executing meteor run android-device returns this error:

Getting error: Error: Command failed:  /dev/ym/ym/.meteor/local/cordova-build/platforms/android/cordova/version 
   env: node: No such file or directory

5) If I execute meteor reset and them launch meteor run android-device it takes few minutes (enough to get this error: WebSocket is closed before the connection is established) but I get the app on the device running.

6) Funny thing is that if I stop the process and re-launch meteor run android-device, then the error in 4) occurs again. 

So it seems to work properly, just once, right after executing meteor reset. Hopefully this can help to find the issue.

If I'm missing something, please let me know.

Thank you

**Comment by martijnwalraven** [comment]
Thanks for the report! I believe this should be fixed with b274e5390a8ae74aec8505c817568eda377e005f, which will be in the next RC.

The bug meant the `node` we ship was not added to the path, so unless a global `node` is available the version command will fail. It worked after a reset because that removes the platforms which contain the version command, so we won't try to execute it.

**Comment by davidecantini** [comment]
That explanation makes sense, thanks also for the quick analysis and for providing the fix already (I'll test the new rc (13) as soon as available to confirm).

**Comment by stubailo** [comment]
this should be fixed in RC 14, just released!

**Comment by davidecantini** [comment]
Confirming that RC 14 fixes the issue. Thank you guys!
