### ISSUE TITLE
Cannot run Meteor from source code without a `.git` directory

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5144]
Trying to do so fail with:

```
.../meteor/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOTDIR, open '.../meteor/.git/hooks/pre-commit'
    at Object.Future.wait (.../meteor/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as writeFile] (/tools/fs/files.js:1334:20)
    at /tools/tool-env/install-git-hooks.js:59:13
    at Array.map (native)
    at installGitHooks (/tools/tool-env/install-git-hooks.js:35:20)
    at /tools/cli/main.js:540:5
    - - - - -
```

The reason why `.git` directory is not there is because I have whole Meteor source tree as a git submodule.

**Comment by stubailo** [comment]
What branch are you on? devel?

**Comment by mitar** [comment]
Yes, and the command is `./meteor test-packages ../`. So clone [this repository](https://github.com/peerlibrary/meteor-server-autorun), go into `meteor` directory and run `./meteor test-packages ../`.

**Comment by stubailo** [comment]
Cool. I might not be able to get to this immediately since I'm working hard on shipping 1.2. But it should be easy to submit a PR to: https://github.com/meteor/meteor/blob/7eafc55eb2fcfb47d858f859c480c162f1d3b10b/tools/tool-env/install-git-hooks.js#L56-L67

To check if a `.git` directory exists, as a temporary solution.

**Comment by mitar** [comment]
Oho, ES6 code in Meteor core. :-)

**Comment by mitar** [comment]
BTW, I also have some other pull requests open. ;-)

**Comment by mitar** [comment]
Done. See #5160.

**Comment by timhaines** [comment]
@mitar's PR temporary resolved this problem.  A later commit ( https://github.com/meteor/meteor/commit/452c839d94a053749712cf14e4cdb8ddfb47f25e ) broke it again.   cc: @stubailo @yyx990803 

If you try and run Meteor as a submodule now: 
```
Error: ENOTDIR, stat '/path/meteor/.git/hooks'
    at Object.Future.wait (/path/meteor/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as stat] (/tools/fs/files.js:1334:20)
    at Object.files.statOrNull (/tools/fs/files.js:257:18)
    at Object.files.mkdir_p (/tools/fs/files.js:386:20)
    at installGitHooks (/tools/tool-env/install-git-hooks.js:36:9)
    at /tools/cli/main.js:541:5
```

**Comment by yyx990803** [comment]
Ah, I think they were addressing the same problem, but my commit assumed the `.git` folder existed and went in before the PR. I've reverted that part of my commit and moved mitar's check out of the map loop: 0f98ea2

@timhaines can you confirm this is working as intended for you?

**Comment by timhaines** [comment]
@yyx990803 Yes, that works.  Thanks!
