### ISSUE TITLE
Frequent error connect ETIMEDOUT

### ISSUE THREAD

**Issue by vishnuavenu** [meteor/meteor#5148]
I feeling meteor script should be more robust like npm and other i have moderate connection speed  but it still can't able to fetch the packages from atmosphere!

**Comment by itsgg** [comment]
I am having the same issue.

**Comment by vishnuavenu** [comment]
Hi ... Ganesh I just resolved that issue ... I hope by this way you can
save your time tooo

NOTE: Meteor runs a internal server for packages and trying to listen and
communicate to PORT 80 ..

I had two server trying to bind I do'nt know but Apache2 was first one that
hinders the communication of Meteor and when i uninstall it THERE IS
LIGHTTPD server which quickly occupied same PORT hence i was puzzled
initially, I felt i just removed all the server.. then manually unistalled
that too. Now its Working fine ...... I recommend u to start clean off
unnecessary  service running on yout system ..... HAPPY CODING!

**Comment by stubailo** [comment]
There was an issue with the package server being unreliable, maybe this is related to that. It should be OK now.
