### ISSUE TITLE
unable to add bootstrap or angular-ui-bootstrap. 

### ISSUE THREAD

**Issue by vishalmanchanda** [meteor/meteor#5149]
This can be specific to meteor(or some setting on my side )but adding here as I could not find any answers from my google search. I'm able to add angular, angular-ui-router, less and many other packages where as unable to add bootstrap or angular-ui-bootstrap. Tried with multiple package authors but getting timeout error -whereas connection doesn't time out for many other packages 

>meteor add nemo64:bootstrap
 => Errors while adding packages:

While downloading nemo64:bootstrap@3.3.5_2...:
error: connect ETIMEDOUT

While downloading nemo64:bootstrap-data@3.3.5...:
error: connect ETIMEDOUT

>meteor add angularui:angular-ui-bootstrap
 => Errors while adding packages:

While downloading angularui:angular-ui-bootstrap@0.13.0...:
error: connect ETIMEDOUT

**Comment by stubailo** [comment]
There were some issues with the package server recently, does this still happen? Keep in mind that packages you have used before are actually cached on your computer, so you should test this with packages you have never used before.

**Comment by stubailo** [comment]
Going to assume this was fixed and was a temporary server outage.
