### ISSUE TITLE
[BUG?] Sometimes `~/.meteor` gets into a state where apps fail with isopack-1 not found errors.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5151]
I think it has to do with the fact that I'm using PREVIEW-PLUGIN and/or 1.2-rc.7+ in local projects. Those project work fine. Then when I go into a project that uses the current default release of Meteor and run `meteor` I get error like this: http://trusktr.io:7777/huduxaqupu

I can fix the problem by deleting `~/.meteor` then trying `meteor` again, in a project that uses `1.1.0.2` for example. This leads me to believe there might be an isopack versioning issue.

I've no idea how to reproduce, but this isn't the first time it's happened before this report.

Reproduction strategy: If it happens again, I'll save a snapshot of `~/.meteor` then I'll delete it and start over, then it should be reproducible with one version of `~/.meteor` and not the other, and we can diff it.

**Comment by benjamn** [comment]
You could try deleting individual directories from `.meteor/isopackets/` to narrow down which packages are getting into a bad state.
