### ISSUE TITLE
Minimongo sort is inconsistent with mongodb sort, no numeric sort available.

### ISSUE THREAD

**Issue by cunneen** [meteor/meteor#5153]
Mongodb performs type conversion on numeric types prior to sorting, as specified [here](http://docs.mongodb.org/manual/reference/method/cursor.sort/#ascending-descending-sort):

> MongoDB treats some types as equivalent for comparison purposes. For instance, numeric types undergo conversion before comparison.

Meteor doesn't provide any option to do this. This causes havoc if there are mixed types.

For example, I have a PatientIDs collection. Here's what I get if I attempt to sort with meteor:

```js
var allPatientsIDs = JutoCollections.PatientIDs.find({},{"sort":{"patient_number":-1},"fields":{"patient_number":1}}).fetch()
var allPatientsIDsArray = allPatientsIDs.map(function(item) { return item.patient_number; });
console.log(allPatientsIDsArray)

["9", "8", "7", "6", "5", "4", "3", "28", "27", "26", "25", "24", "23", "22", "21", "20", "2", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "1", 91]
```

As you can see, this is clearly not sorted numerically.

If I sort the same collection with mongodb, it is sorted numerically:

```js
var allPatientsIDs = db.PatientIDs.find({},{"patient_number":1},{"$sort":{"patient_number":-1}})
allPatientsIDs
{ "_id" : "mKxyKqbxARa5ebYcH", "patient_number" : "1" }
{ "_id" : "Wcb9TmCrxM3b3qqxq", "patient_number" : "2" }
{ "_id" : "X7oBtn4x3j3wDFqiW", "patient_number" : "3" }
{ "_id" : "NtZwZqwZW9p3MD7SD", "patient_number" : "4" }
{ "_id" : "kHf2GRuujyxik5yHS", "patient_number" : "5" }
{ "_id" : "9YNdwKiCxBTjSaGDT", "patient_number" : "6" }
{ "_id" : "ro2h7G9qcAd2QAiDP", "patient_number" : "7" }
{ "_id" : "uimN63iyXSGdRvjgh", "patient_number" : "8" }
{ "_id" : "5sEFkzWegKmbrbcX3", "patient_number" : "9" }
{ "_id" : "vjcSi9S9bxzFarAcg", "patient_number" : "10" }
{ "_id" : "68TQNBQKcbuWEGF4E", "patient_number" : "11" }
{ "_id" : "tinKA6EN32zQHQYAv", "patient_number" : "12" }
{ "_id" : "zHq8AWmfAAinpjnm4", "patient_number" : "13" }
{ "_id" : "sryfPZ4z4Td4MoaNR", "patient_number" : "14" }
{ "_id" : "bYFdorSxPFa4bQ54r", "patient_number" : "15" }
{ "_id" : "5rYP8sDjLB8uDdZ42", "patient_number" : "16" }
{ "_id" : "Dx4tNRkLkK4dpquEF", "patient_number" : "17" }
{ "_id" : "yXtR7sD22cFweRcF2", "patient_number" : "18" }
{ "_id" : "hMA5tasK8aZHCiyzN", "patient_number" : "19" }
{ "_id" : "B5R4xEQ6gg267aRgk", "patient_number" : "20" }
{ "_id" : "Eyg7EReLEW7qGowLN", "patient_number" : "21" }
{ "_id" : "3eNpJgketSRrWyBYq", "patient_number" : "22" }
{ "_id" : "ot2SKXuYw2kReSawQ", "patient_number" : "23" }
{ "_id" : "yDGPFRjfBRezuz8sL", "patient_number" : "24" }
{ "_id" : "b2WFA5HLai9K74Z3C", "patient_number" : "25" }
{ "_id" : "AMA6ma4iwYeeFge7C", "patient_number" : "26" }
{ "_id" : "dzrKZoP4hEv2tYXgg", "patient_number" : "27" }
{ "_id" : "f6nNQ2NyKXqJmWMtM", "patient_number" : "28" }
{ "_id" : "n3bSLZWhdX3oRtSiD", "patient_number" : 91 }
```

As you can see, mongodb sorts it nicely.

**Comment by jagi** [comment]
What version of MongoDB do you have? I can't reproduce your problem.
I have version 2.6.7 and the result is:

```js
db.items.find({}, {number: 1}).sort({number: 1});

{ "_id" : "EmvnMFPAr62FbZ24B", "number" : "1" }
{ "_id" : "hbWdxPWW9kbEthiWQ", "number" : "15" }
{ "_id" : "5MC6aRxmpaFriRysG", "number" : "5" }
```

It's clearly non numerical order and in MiniMongo I have the same result.

```js
Items.find({}, {sort: {number: 1}, transform: null, fields: {number: 1}}).fetch();

{ "_id" : "EmvnMFPAr62FbZ24B", "number" : "1" }
{ "_id" : "hbWdxPWW9kbEthiWQ", "number" : "15" }
{ "_id" : "5MC6aRxmpaFriRysG", "number" : "5" }
```

And the you have an error, the `$sort` operator is reserved for `aggregate` method. You should use the `sort()` method on the cursor.

**Comment by cunneen** [comment]
I'm on 2.6.8 .

The lack of the ability to explicitly force a numeric sort is a problem either way.

Using the sort() option on the cursor I get the same result as you (non-numeric with no type conversion). But using $sort in mongodb I can get the results I need; in meteor I can't at all.

**Comment by jagi** [comment]
But there is no third argument in the `find` method http://docs.mongodb.org/v2.6/reference/method/db.collection.find/

You can always convert the `patient_number` value to the number before saving it into the collection.

**Comment by cunneen** [comment]
Ha. True. Interesting that it does anything at all, let alone giving the exact results I need. 

But this is an existing collection. So no, I can't do a conversion.

Meteor does not let me do a numeric sort. This is the problem.

I can work around it by fetching all of the documents and performing a sort (luckily I don't need any other fields so this shouldn't be a problem) but it is a big omission for meteor not to allow a numeric sort.

```js
  var allPatientIDObjs = JutoCollections.PatientIDs.find({},{"fields":{"patient_number":1}}).fetch();
  // sort them into descending numeric order
  var allPatientsIDsArray = allPatientIDObjs.sort(function (a, b) {return b.patient_number - a.patient_number;}); // numeric reverse sort

```

**Comment by jagi** [comment]
But it's not a problem with Meteor, it's a problem with MongoDB. It does not allow you to make numeric sort on string fields.

So, the solution would be, as you said, doing it manually.

**Comment by cunneen** [comment]
Everything meteor provides, it provides on top of what mongodb provides on its own. Consider this a feature request.

**Comment by jagi** [comment]
And MongoDB does not provide such feature :) so it's way Meteor doesn't do it too :)

**Comment by stubailo** [comment]
Yeah @jagi is correct. I don't think we will be able to implement additional query and sorting functionality on top of MongoDB without insane hacks, so it would make more sense to file this as a feature request for MongoDB. You can always fetch the documents and do the sort in code, or add a `transform` function that converts those strings into integers: http://docs.meteor.com/#/full/mongo_collection (see the transform option)

**Comment by cunneen** [comment]
transform is a great option, thanks!

**Comment by mitar** [comment]
Also related: #2730

**Comment by deveshrawat** [comment]
This can help You 
db.collectionName.find().sort({sortingParameter: 1}).collation({locale: "en_US", numericOrdering: true})
