### ISSUE TITLE
Not able to deploy using own domain name.

### ISSUE THREAD

**Issue by Shekharrajak** [meteor/meteor#5155]
I deployed my meteor app using deploy command ::
$ meteor deploy whitecastle.in

after uploading all the files it is saying 
Deploying to whitecastle.in.                  
Now serving at http://whitecastle.in  

but I can't  actually see it being deployed in http://www.whitecastle.in or http://whitecastle.in  
![screenshot from 2015-09-14 19 03 13](https://cloud.githubusercontent.com/assets/5774448/9851370/eec0059e-5b15-11e5-9f97-1d44704a0aef.png)

**Comment by afuggini** [comment]
Check out https://github.com/meteor/meteor/issues/2213

**Comment by stubailo** [comment]
What else have you done? Have you set the CNAME record as detailed here? http://docs.meteor.com/#/full/deploying

**Comment by Shekharrajak** [comment]
Thanks you @afuggini  and @stubailo 
It is working now. :+1:

**Comment by Shekharrajak** [comment]
Any idea how can I redirect http://whitecastle.in to http://www.whitecastle.in 
Right now it is serving on http://www.whitecastle.in/ 
but when I open http://whitecastle.in/  is not redirecting to http://www.whitecastle.in/
Any idea how to solve this problem . @afuggini @stubailo
