### ISSUE TITLE
[1.2-rc.14] Method stub isn't calledback

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5156]
While testing 1.2 on an existing app we got an issue where the callback in a `Meteor.call` is never called back.

The server method is run and returns expected value.

But `Meteor.connection._outstandingMethodBlocks` growing and the stream doesn't seem to return the method result to the client.

First outstanding method is id 1 and results are not on the websocket.

cc. @jperl

**Comment by raix** [comment]
sorry - Kadira bug - upgrade to `meteorhacks:kadira@2.23.2` fixes this

**Comment by jperl** [comment]
Glad you found the issue :)

**Comment by stubailo** [comment]
Cool!
