### ISSUE TITLE
[1.2-rc.14|babel] ...arguments in call fail

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5157]
It's an odd case:
```js
console.log.call(this, ...arguments);
```
Results in `TypeError: Cannot read property 'call' of undefined`

```js
var _console$log;
(_console$log = console.log).call.apply(_console$log, [this].concat(babelHelpers.slice.call(arguments)));
// babelHelpers.slice is undefined?
```

-

This works fine:
```js
console.log(...arguments);
```

**Comment by stubailo** [comment]
@benjamn can you take a look at this?

**Comment by benjamn** [comment]
I can fix the missing `babelHelpers.slice`, but I suspect you meant to do `console.log.call(console, ...arguments)`, since `console.log` weirdly has to be be called with `console` as the object.

**Comment by benjamn** [comment]
Fixed by fe69807f1872b4f64b143d0a555fe3d2775e5308, thanks!

**Comment by stubailo** [comment]
I'll release this in the next RC! Probably will be `1.2-rc.16`.

**Comment by raix** [comment]
Thanks - yeah the console example was just for replication, not the actual code :)

**Comment by stubailo** [comment]
It's out now!

**Comment by raix** [comment]
:+1: Thanks
