### ISSUE TITLE
32-bit libraries not found but installed

### ISSUE THREAD

**Issue by AntonLydike** [meteor/meteor#5158]
I've run through the [tutorial](https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux) for meteor developing on mobile, but I got to the point, where `meteor install-sdk android` prints:

    ✓ Found Android bundle
    ✓ A JDK is installed                          
    ✓ Found Android Platform tools                
    ✓ Found Android Build Tools                   
    ✗ 32-bit libraries not found                  
    ✓ Found Android 19 API                        
    ✓ Found suitable Android x86 image            
    ✓ 'meteor' android virtual device (AVD) found 
    ✓ Android emulator acceleration is installed  
    Platform requirements not yet met             
    Please follow the instructions here:          
    https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux#libs32

The referenced page says, I should run `sudo apt-get update; sudo apt-get install --yes lib32z1 lib32stdc++6` but that command prints:

    (...)
    openjdk-7-jdk ist schon die neueste Version.
    (...)

(openjdk-7-jdk is up do date)

**Comment by martijnwalraven** [comment]
Could you try this with the Meteor 1.2 RC (`meteor update --release METEOR@1.2-rc.15`)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue.

Note that you will have to install your own Android SDK, see [here](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux) for instructions.

**Comment by AntonLydike** [comment]
I did as you said and asumed, I schould now run `meteor add-platform android` but I got the following error printed out:

    /home/user/.meteor/packages/meteor-tool/.1.1.7-rc.14.1igfcku++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
    						throw(ex);
    						      ^
    TypeError: Cannot read property '0' of undefined
        at Object.exception (/tools/utils/buildmessage.js:490:22)
        at /tools/cordova/builder.js:179:24
        at /tools/utils/buildmessage.js:356:18
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at /tools/utils/buildmessage.js:349:34
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at /tools/utils/buildmessage.js:347:23
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at Object.enterJob (/tools/utils/buildmessage.js:321:26)
        at CordovaBuilder.processControlFile (/tools/cordova/builder.js:170:20)
        at /tools/cordova/project.js:117:15
        at CordovaProject.createIfNeeded (/tools/cordova/project.js:137:27)
        at new CordovaProject (/tools/cordova/project.js:58:10)
        at /tools/cli/commands-cordova.js:53:28
        at /tools/utils/buildmessage.js:268:13
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at /tools/utils/buildmessage.js:261:29
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at /tools/utils/buildmessage.js:259:18
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at /tools/utils/buildmessage.js:250:23
        at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
        at Object.capture (/tools/utils/buildmessage.js:249:19)
        at Object.main.captureAndExit (/tools/cli/main.js:268:29)
        at Command._mainJs2.default.registerCommand.name [as func] (/tools/cli/commands-cordova.js:42:8)
        at /tools/cli/main.js:1378:23

To mention is, that I ran the `umake android` command and specified my D: disk. (My Linux disk is verry small)

**Comment by martijnwalraven** [comment]
We should really improve the error message here, but from that stack trace it seems the issue is in your `mobile-config.js`. Any chance there's a `[0]` on a variable that is undefined?

**Comment by AntonLydike** [comment]
Okay. I just commented out the most part of my `mobile-config.js` (It was just an example) and ran the command again, and got this:

    android: added platform                       
                                                  
    Your system does not yet seem to fulfill all requirements to build apps for Android.
                                                  
    Please follow the installation instructions here:
    https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux
                                                  
    Specify the --verbose option to see more details about the status of individual requirements.

But when running `meteor add-platform android --verbose` I got:

    While adding platforms:
    error: android: platform is already added

And when I ran `meteor run android` I got this:

    Error: spawn EACCES
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by martijnwalraven** [comment]
Can you try running `meteor run android --verbose`?

**Comment by AntonLydike** [comment]
`meteor run android --verbose` prints the exact same:

    Error: spawn EACCES
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by martijnwalraven** [comment]
Hmmm, that's not very helpful output unfortunately. Can you try `meteor remove-platform android` followed by `meteor add-platform android --verbose`?

**Comment by AntonLydike** [comment]
`meteor remove-platform android` printed:

    android: removed platform                     
                                                  
    Error: spawn EACCES
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

and `meteor add-platform android --verbose` just printed:

    Error: spawn EACCES
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

I think that somewhere on the way there got something broken.

**Comment by martijnwalraven** [comment]
I would rather have liked to find out what is causing this, but as a last resort, can you try `rm -rf .meteor/local/cordova-build`?

**Comment by AntonLydike** [comment]
Okay. After that I ran `meteor add-platform android --verbose` which printed:

    Processing mobile-config.js                   
    Writing new config.xml                        
    Creating Cordova project                      
    % Creating a new cordova project.             
    Adding platform Android to Cordova project    
    % Adding android project...                   
    android: added platform                       
    Checking Cordova requirements for platform Android
                                                  
    Your system does not yet seem to fulfill all requirements to build apps for Android.
                                                  
    Please follow the installation instructions here:
    https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux
                                                  
    Status of the requirements:                   
    ✓ Java JDK                                    
    ✗ Android SDK: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
      Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
    ✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME
      environment variable.
    ✗ Gradle: Could not find gradle wrapper within Android SDK. Could not find Android SDK directory.
      Might need to install Android SDK or set up 'ANDROID_HOME' env variable.

The problem is I didn't download the SDK inside the Android studio. But when I try to open Android studio I get 

    Befehl konnte »"/media/user/DATEN/linux/programme/android-studio/bin/studio.sh" %f« nicht ausführt werden.
    Kindprozess »/media/user/DATEN/linux/programme/android-studio/bin/studio.sh« konnte nicht ausgeführt werden (Keine Berechtigung)

(Command "/media/user/DATEN/linux/programme/android-studio/bin/studio.sh" %f couldnt be executed)
(Child process "..." couldn't be executed (No permission))

I know this isn't related, but I didn't found that problem (nor an answer) on google. (might have to ask StackOverflow)
