### ISSUE TITLE
Error: Did not check() all arguments  during call to 'addNewProduct'

### ISSUE THREAD

**Issue by leomatthew** [meteor/meteor#5163]
Hi All,

I am using Orion to generate the model and publishing template. I created a collection called "Product" it has all the parameters. I crated a method to insert the data in Collection. It has all the required fields. But still I got the error. But it inserts the data in to the mongodb collection.

Anybody fixed this problem?

See the stack trace
------------------------
I20150915-11:22:30.578(5.5)? Exception while invoking method 'addNewProduct' Error: Did not check() all arguments during call to 'addNewProduct'
I20150915-11:22:30.578(5.5)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150915-11:22:30.578(5.5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150915-11:22:30.578(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150915-11:22:30.579(5.5)?     at packages/ddp/livedata_server.js:648:1
I20150915-11:22:30.579(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150915-11:22:30.579(5.5)?     at packages/ddp/livedata_server.js:647:1
I20150915-11:22:30.579(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150915-11:22:30.580(5.5)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150915-11:22:30.580(5.5)?     at packages/ddp/livedata_server.js:546:1
I20150915-11:22:32.752(5.5)? Exception while invoking method 'addNewProduct' Error: Did not check() all arguments during call to 'addNewProduct'
I20150915-11:22:32.753(5.5)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150915-11:22:32.753(5.5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150915-11:22:32.753(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150915-11:22:32.753(5.5)?     at packages/ddp/livedata_server.js:648:1
I20150915-11:22:32.754(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150915-11:22:32.754(5.5)?     at packages/ddp/livedata_server.js:647:1
I20150915-11:22:32.755(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150915-11:22:32.756(5.5)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)

But the data inserted correctly after emitting this error.

Thanks,
Leo Matthew.S

**Comment by stubailo** [comment]
I think this is a bug to file on Orion. But you probably need to use the `check` package to check your method's arguments. http://docs.meteor.com/#/full/check
