### ISSUE TITLE
new Mongo.Collection(null) and new LocalCollection() are not the same

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5164]
I always assumed that they are? But I get the error `Meteor requires document _id fields to be non-empty strings or ObjectIDs` when using numeric `_id`s with the former, but not the latter.

See #3527.

**Comment by stubailo** [comment]
What's the expected result? Also, do they need to be the same for some reason?

**Comment by mitar** [comment]
The expected result would be to behave the same. :-) I always though that using `null` for a name makes it a local collection. So the question which then opens is where the differences are documented and how can a programmer know when to use which?

**Comment by stubailo** [comment]
I guess I wonder why that would be the expected result, since `LocalCollection` is not documented anywhere at all. I would think that the official point of view is to always use `new Mongo.Collection(null)`, since `LocalCollection` is an internal implementation detail.

**Comment by mitar** [comment]
Hmm, you are right.
