### ISSUE TITLE
Minimongo difference: it allows $ prefixed keys

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5165]
If you try to use `$` prefixed key on the server, you will get an error. But Minimongo allows them. For example, for key `$each` you will get the following error:

```
$each is not valid for storage.
```

See reproduction (test `each-storage`) here: https://github.com/mitar/minimongo-diff/tree/split-tests

**Comment by benjamn** [comment]
Pull request welcome!

**Comment by mutdmour** [comment]
I will work on this.
