### ISSUE TITLE
Modification with $near and indexes does not work the same in Minimongo and server

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5166]
See reproduction (test `modify-with-near`) here: https://github.com/mitar/minimongo-diff/tree/split-tests

**Comment by stubailo** [comment]
Thanks for the report! Having Minimongo be more similar to real Mongo would be a great goal.

**Comment by hwillson** [comment]
This should have been addressed by https://github.com/meteor/meteor/pull/8642. Closing - thanks!
