### ISSUE TITLE
$push with $slice works on the server side but not in Minimongo

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5167]
See reproduction (test `positive-numbers-slice`) here: https://github.com/mitar/minimongo-diff/tree/split-tests

**Comment by stubailo** [comment]
Thanks for the report! Having Minimongo be more similar to real Mongo would be a great goal.

**Comment by mitar** [comment]
Just start running Minimongo tests against MongoDB. :-)

**Comment by mutdmour** [comment]
I will work on this.

**Comment by hwillson** [comment]
#8623 has been merged, so this issue will be fixed in an upcoming Meteor version. Thanks @mitar and @mutdmour!
