### ISSUE TITLE
todo sample app Meteor auto add <script> tag

### ISSUE THREAD

**Issue by nhduc296** [meteor/meteor#5169]
well, I don't know is this an meteor bug or it is a feature:

every time I switch between sign in and join page. A new '< script >' tag was added in the end of the html with the same content as below.

Step to reproduce:
- clone meteor todo app.
- start meteor app at localhost or deploy to xxx.meteor.com
- repeat click on join and sing in button.

```
<script>try{for(var lastpass_iter=0; lastpass_iter < document.forms.length; lastpass_iter++){ var lastpass_f = document.forms[lastpass_iter]; if(typeof(lastpass_f.lpsubmitorig2)=="undefined"){ lastpass_f.lpsubmitorig2 = lastpass_f.submit; if (typeof(lastpass_f.lpsubmitorig2)=='object'){ continue;}lastpass_f.submit = function(){ var form=this; var customEvent = document.createEvent("Event"); customEvent.initEvent("lpCustomEvent", true, true); var d = document.getElementById("hiddenlpsubmitdiv"); if (d) {for(var i = 0; i < document.forms.length; i++){ if(document.forms[i]==form){ if (typeof(d.innerText) != 'undefined') { d.innerText=i.toString(); } else { d.textContent=i.toString(); } } } d.dispatchEvent(customEvent); }form.lpsubmitorig2(); } } }}catch(e){}</script>
```

![todos - all your todos synced wherever you happen to be - google chrome_002](https://cloud.githubusercontent.com/assets/4246176/9878904/3538133e-5bef-11e5-8da7-9310991e25d9.png)

**Comment by Slava** [comment]
These scripts are added by your browser extensions. In your example, it is LastPass extension (read the code snippet you posted).

**Comment by nhduc296** [comment]
@Slava oh I see, thank you very much. Please close this PR.
