### ISSUE TITLE
[1.2-rc.15] Meteor reset ENOTEMPTY

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5170]
```js
$ meteor reset
                                              
/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOTEMPTY, rmdir '/Users/raix/dev/dispatch/meteor-app/.meteor/local/cordova-build'
    at Object.Future.wait (/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.14.1rpxx8z++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.rm_recursive (/tools/fs/files.js:270:9)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands.js:1206:9)
    at /tools/cli/main.js:1378:23
```

When I run `$ meteor reset` again it doesn't complain

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this. Has it happened again since?

Is there any chance two processes may have been trying to write to the same project directory?

**Comment by stubailo** [comment]
I think this isn't really an error we can "fix", unless it's somehow Meteor writing files while it's deleting which I don't think is the case. There are two options as far as I can see:

1. Retry `rm_recursive` if there is an `ENOTEMPTY` error, and just keep trying until everything is deleted.
2. Print a nicer error saying "We couldn't delete everything, try running the command again".
3. Do nothing.

@raix what do you think?

**Comment by raix** [comment]
The log actually said something about removing plugin. It did happen alot - making it hard to create the build. I'm going to see if it's still a problem tomorrow.

**Comment by stubailo** [comment]
Any updates on this? Going to close it to clean up the 1.2 milestone, I'll reopen if there is new info.
