### ISSUE TITLE
[1.2-RC.15] [ERROR:runtime_javascript_dialog_manager.cc(64)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::CancelActiveAndPendingDialogs(content::WebContents*)

### ISSUE THREAD

**Issue by miri-am** [meteor/meteor#5173]
Getting this error when running on Android:

```
[1.2-RC.15] E/chromium(26718): [ERROR:runtime_javascript_dialog_manager.cc(64)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::CancelActiveAndPendingDialogs(content::WebContents*)
```

Did not recognize any implications so far.

**Comment by martijnwalraven** [comment]
It seems [this Crosswalk issue](https://crosswalk-project.org/jira/browse/XWALK-3108) may be related. 

By no implications, do you mean it just prints the error but the app continues to work normally?

**Comment by miri-am** [comment]
yes. So far it seems to be working normally.
