### ISSUE TITLE
PACKAGE_DIRS env var not working in zsh

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#5176]
I use zsh, and just noticed today that if I have local packages in an external folder (as defined in `PACKAGE_DIRS`), `meteor` does not recognize that folder for some reason.

```
% echo $PACKAGE_DIRS
/Users/samh/Sites/local_packages
```

Yet when I run `meteor list`:

```
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: mine:testpackage
```

If I switch to bash and have the same exact `PACKAGE_DIRS` value, it works fine.

**Comment by benjamn** [comment]
Can you add a `console.log(process.env.PACKAGE_DIRS)` line to https://github.com/meteor/meteor/blob/devel/tools/index.js to make sure the variable is getting to Node?

I wasn't able to reproduce this in my version of `zsh` (5.0.6). Maybe you're using a different version that has some sort of bug?

**Comment by ffxsam** [comment]
I'm not totally clear on where to add that `console.log` statement. BTW, I'm using zsh 5.1.

**Comment by ffxsam** [comment]
@benjamn I get `undefined`.

**Comment by ffxsam** [comment]
Any updates on this?

**Comment by ffxsam** [comment]
I'm not sure what other details I could share that are helpful. I'm using zsh + oh-my-zsh. `PACKAGE_DIRS` is definitely defined (I `echo` it and I see the correct path where the packages are). Yet when I run `meteor list`, I get the error above.

I think when the meteor scripts are fired off with bash, the env var is lost. Should I be defining `PACKAGE_DIRS` somewhere specific? It's in both `~/.bashrc` and `~/.bash_profile`.

**Comment by ffxsam** [comment]
GOT IT. Environment variables in zsh have to be defined in `~/.zshenv` in order to carry over into bash scripts.

**Comment by benjamn** [comment]
Interesting. I wonder if there's anything we can do in the https://github.com/meteor/meteor/blob/devel/meteor Bash script to inherit variables from `zsh` shells…

**Comment by ffxsam** [comment]
It was totally my mistake. Stupid mistake :) I was just doing `VAR=val` instead of `export VAR=val`.
