### ISSUE TITLE
Sometimes cosmos:browserify freezes (loads forever?).

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5177]
I'm not sure if it's Meteor's or cosmos:browserify's fault, but here are the details:

https://github.com/elidoran/cosmos-browserify/issues/17

Posting in both places since I don't know on which side the issue lies.

**Comment by stubailo** [comment]
Is it possible to create a simple reproduction for this issue? I've never encountered something like this.

**Comment by stubailo** [comment]
@trusktr can you reproduce this issue consistently? If you can better describe what is happening and when, we might be able to isolate what's going on. You can also try running Meteor from a checkout of the `release-1.2` branch and adding some logging statements to try to track down what part of the code is malfunctioning.

**Comment by radalin** [comment]
This issue seems to be related on this: https://github.com/meteor/meteor/issues/5198

**Comment by thewolf** [comment]
I had a similar issue where webpack created a huge .js file

**Comment by radalin** [comment]
@stubailo I think you can close this issue, as this is definitely related to #5198. 

To avoid this, basically rename your huge js file hugefile.es5.js. This way browserify will no longer parse it for Ecmascript, thus your problem will be solved. Yet you won't get the benefit os Meteor's Ecmascript implementation. But obviously, this is a 3rd party file so it does not really support Meteor's Ecmascript.

**Comment by trusktr** [comment]
Ah, good to know!
