### ISSUE TITLE
[improvement] Better isopack error message.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5178]
I'm getting an error like this: http://trusktr.io:7777/pejerogizu

I've no idea what package is causing it. It'd be nice to know what's causing this.

**Comment by benjamn** [comment]
That link isn't loading for me, but perhaps https://github.com/meteor/meteor/commit/48797d6ceb05f186f6a84e2ca70d575660f47a93 will help?

**Comment by benjamn** [comment]
It seems like whatever package is depending on `jss-props-sort` should also be depending on `jss`, since that's an unmet [peer dependency](https://github.com/jsstyles/jss-props-sort/blob/ec6903417854b96bb9ffd9835a704ea07dd1764f/package.json#L34-L36).

**Comment by trusktr** [comment]
@benjamn Oops, I pasted the wrong output, I meant to paste this one: http://trusktr.io:7777/pejerogizu

**Comment by trusktr** [comment]
Here's the raw text, just in case: http://trusktr.io:7777/raw/pejerogizu

**Comment by trusktr** [comment]
This error causes Meteor to exit instead of waiting for file changes.

**Comment by stubailo** [comment]
@trusktr in the future, can you just paste the test into GitHub in a code fence:

```
like this
```

**Comment by trusktr** [comment]
@stubailo I normally do, but I have (hopefully temporary) problem where a tab in Chrome Linux freezes when I try to paste anything that's longer than about 1 screen.

**Comment by trusktr** [comment]
Okay, I don't know what I did that changed the error I'm getting, but now I get this: http://trusktr.io:7777/udogakimef (sorry, can't use code fence).

I deleted `~/.meteor` and my app's `.meteor/local` and get this error now. Not a clue yet why.

**Comment by trusktr** [comment]
Aha, so I compiled some stuff with Webpack to make bundles, and Meteor is tripping up on it. I'll close this and make a new issue.

**Comment by trusktr** [comment]
By the way, if anyone stumbles on this, the solution to that isopack error may be to delete `~/.meteor` and your apps' `.meteor/local` folder.

**Comment by trusktr** [comment]
@stubailo Acutally, I'd like to leave this open, as the following isn't a helpful message:

```
This isopack was likely built with a much newer version of Meteor.
```

It'd be nice if it stated which package "this isopack" was from.

**Comment by abernix** [comment]
This is relatively old and the self-hosted pastebin doesn't provide the error message anymore.  I'm not sure what error this was, but if it's still a problem, please ping back and we can consider it.

Thanks for opening this originally though.
