### ISSUE TITLE
settings.json cannot parse a file with BOM (Byte-Of-Mark) e.g. UTF-8

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#5180]
This sounds silly, but spent already 30 min trying to figure out what's wrong with my `settings.json` file

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Can you post an example settings.json file?

**Comment by dotnetwise** [comment]
even a blank settings.json file that contains `UTF-8 BOM` and curly braces is failing
```js
{
}
```

**Comment by abernix** [comment]
FYI: https://github.com/nodejs/node-v0.x-archive/issues/1918

**Comment by hwillson** [comment]
I've confirmed this is still an issue with Meteor 1.5.2. Quick macos repro steps for this:

```
meteor create --bare meteor-issue-5180
cd meteor-issue-5180
printf '\xEF\xBB\xBF{"key": "value"}' > settings.json
meteor --settings=settings.json
```

leads to:

```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While preparing to run:
   settings.json: parse error reading settings file
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```
