### ISSUE TITLE
[bug?] Meteor unable to compile certain files.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5184]
I've got some bundles I made with Webpack. They are libraries, compiled with Webpack so that I can use their globals in my app (instead of wrapping them in a Meteor package I placed them in a lib folder).

When the files are present in the app, Meteor has the following error that doesn't help much: http://trusktr.io:7777/udogakimef

(Sorry, I'm unable to paste code inline right now)

If I remove the files, no more error.

**Comment by trusktr** [comment]
Here are the files that cause the problem: 50.116.4.56/~/meteor-issue-5184-bad_files.zip

**Comment by trusktr** [comment]
@stubailo Sent you a repro.

**Comment by trusktr** [comment]
Hmmm, apparently the file that is causing the problem is the `famous.jsx`.

Aha! If I change the extension to `.js` to `.jsx`, then no more problem! Seems like the problem might be in the `jsx` package.

**Comment by stubailo** [comment]
@trusktr what versions of `jsx`, Meteor, and `meteor-tool` do you have in your app?

**Comment by stubailo** [comment]
I think this is the same as #5198, since some of the files are extremely large.
