### ISSUE TITLE
[bug?] Build taking a long time (longer than issue 5067, without rocket:module).

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5185]
So, in order to speed up development on a project, my team on that project decided to stop using rocket:module (for now, until issue #5067 can be sorted out) and go back to regular global files (we converted all ES6 module files to files that create global variables). Now that we've switched to global vars, building the app gets stuck for 10 minutes or more on the following step (note we're using the JSX package, and on Meteor `>1.2-rc.7`). I haven't actually been patient enough to let it finish, and don't know if it'll actually finish, so I just killed the process:

```
> meteor
[[[[[ ~/src/nowgoin+mobile_cordova/meteor-app ]]]]]

=> Started proxy.
=> Started MongoDB.

Changes to your project's package version selections:

blaze-html-templates  removed from your project
hot-code-push         removed from your project
meteor-base           removed from your project
meteor-platform       added, version 1.2.3-rc.0
mobile-experience     removed from your project

   Building for web.browser                  \
```

After downgrading from `1.2-rc.7` (or above, I think it upgrades automatically) to Meteor `1.1.0.3` building is back to normal duration.

**Comment by trusktr** [comment]
No luck with `1.2-rc.15`. I had to kill it after 20 min.

**Comment by stubailo** [comment]
@trusktr does this happen to everyone on your team?

What OS are you running on? What packages do you have in your app? Is it possible to create a reproduction that isolates the issue with a simple app?

**Comment by trusktr** [comment]
@stubailo 

> does this happen to everyone on your team?

Yep, identical behavior with another person. Everyone is on OS X except I'm in Linux.

I meant to send a repro. Let me do that soon. I'll make a simple repro if possible, but if I can figure out what makes it happen, I can only send the state of an app when/if it happens.

**Comment by stubailo** [comment]
Yeah, it's not that we don't want to fix this and other issues, it's just that we need a certain amount of information to be able to figure out what could be causing it.

**Comment by trusktr** [comment]
@stubailo For sure, I know. :+1: The work you guys are doing is awesome. :]
