### ISSUE TITLE
[bug?] Downgrading Meteor to pre-1.2 causes isopack errors like the ones in issue #5178.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5186]
I've downgraded an app from 1.2-rc.15 to 1.1.0.3, and when I try running it (even after deleting the app's `.meteor/local` folder), I get an isopack-1 not found error as detailed in #5178.

I can fix the problem by deleting `~/.meteor` and starting fresh (which takes a while unfortunately because it has to download packages all over again).

**Comment by stubailo** [comment]
> downgraded an app from 1.2-rc.15 to 1.1.0.3

What is the method you used to do this? If I create a blank app, it (correctly) doesn't let me downgrade:

```
Oleksandrs-MacBook-Pro:old sashko$ meteor update --release 1.1.0.3
This project is at the latest release which is compatible with your current package constraints.
Oleksandrs-MacBook-Pro:old sashko$ meteor --release 1.1.0.3
=> Using Meteor 1.1.0.3 as requested (overriding Meteor 1.2-rc.16)

[[[[[ ~/playpen/old ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package: isobuild:minifier-plugin
   Required by: standard-minifiers 1.0.0-rc.2

=> Your application has errors. Waiting for file change.
```

**Comment by robincwillis** [comment]
If you have a copy of `./meteor/packages` before upgrading you can revert that file and then 
`meteor update --release 1.1.0.3`
will work. If not then add/remove these packages from that file
````
> meteor-platform
< mquandalle:bower
< meteor-base
< mobile-experience
< mongo
< blaze-html-templates
< session
< jquery
< tracker
< logging
< reload
< random
< ejson
< spacebars
< check
````
