### ISSUE TITLE
Template helpers fired mutiple times in {{> inclusion data1 data2 data3}}

### ISSUE THREAD

**Issue by aunz** [meteor/meteor#5188]
Consider the following example
``` html
<body>
{{#each fruits}} blah {{/each}}
{{#each veges}} blah {{/each}}
{{#each flowers}} blah {{/each}}
</body>
```

```js
Template.body.helpers({
  fruits: function(){
    console.log('fruits helper was called')
    return Session.get('fruits')
  },
  veges: function(){
    console.log('veges helper was called')
    return Session.get('veges')
  },
  flowers: function(){
    console.log('flowers helper was called')
    return Session.get('flowers')
  }
})

```

If I run `Session.set('fruits',['apple','orange','banana'])`, as expected, only `fruits helper was called` will be logged in the console.
Similarly, if I run `Session.set('veges',['potato')`, only `veges helper` will be logged in the console

On the other hand

``` html
<body>
{{>garden fruits=fruits veges=veges flowers=flowers}}
</body>
<template name="garden">
{{#each fruits}} blah {{/each}}
{{#each veges}} blah {{/each}}
{{#each flowers}} blah {{/each}}
</template>
```

When `Session.set('fruits',['apple','orange','banana'])` is run, all the helpers were logged.

So in the case of template inclusion with multiple data `{{>garden fruits=fruits veges=veges flowers=flowers}}`, changing 1 helper will also invalidate or re run other helpers.
Is this behaviour a bug or expected?

**Comment by wh0** [comment]
There's only one computation that calls `fruits`, `veges`, and `flowers`. That single computation depends on all three helpers. So right now, changing one session variable invalidates the whole computation, which will call all three helpers when it recomputes.

**Comment by aunz** [comment]
Thanks for the clarification !

**Comment by yyx990803** [comment]
@wh0 thanks for explaining it :)
