### ISSUE TITLE
[FR:jshint] Allow comments in json (.jshintrc)

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5191]
It would be really nice if we could use the `jshint` package and still be able to have comments in the json... Maybe just use https://www.npmjs.com/package/strip-json-comments at https://github.com/meteor/meteor/blob/devel/packages/jshint/plugin/lint-jshint.js#L66

**Comment by stubailo** [comment]
Does JSHint outside of Meteor support this?

**Comment by raix** [comment]
yes, they use comments in their example too: https://github.com/jshint/jshint/blob/master/examples/.jshintrc
*It's not critical - we just stripped all comments*

-

btw. please help get meteor into jshint https://github.com/jshint/jshint pr: 2684 *(I've added only the bare minimum of globals - we use a tool to generate jshintrc based on dependencies, to use lint for warning about missing dependencies, so we just want the core globals in there)*
