### ISSUE TITLE
Unable to publish package, constraint not satisfied by really old version of package.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5192]
I'm trying to publish a package that depends on rocket:module 0.8.2, and I get an error like this:

```
> meteor publish
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint rocket:module@0.8.2 is not satisfied by rocket:module 0.0.2.
Constraints on package "rocket:module":
* rocket:module@0.8.2 <- infamous:motor 0.0.1
```

The package.js of the package looks like this:

```Package.describe({
  name: 'infamous:motor',
  version: '0.0.1',
  summary: 'A rendering engine for the web.',
  git: 'https://github.com/infamous/motor.git'
});

Package.onUse(function(api) {
  api.versionsFrom('METEOR@1.2-rc.7');

  // TODO
  api.use([
    'rocket:module@0.8.2'
  ], 'client');

  api.add_files([
    'entry.js',
    'npm.json',
  ], 'client');

  api.export('motor');
});
```

As you can see, the package depends on Meteor 1.2-rc.7 and rocket:module 0.8.2. 

The package code is here: https://github.com/infamous/motor/tree/joe/meteor-package

You'll see there a `testApp` in there to test that the package works (exports the symbol `motor`).

Why might I get this error when trying to publish the package?

**Comment by stubailo** [comment]
Do you have PACKAGE_DIRS set or something like that? This is pretty weird!

**Comment by stubailo** [comment]
I can't figure this out. Maybe there is something in your environment, or env vars, that Meteor is interpreting? Let me know if you figure something out.
