### ISSUE TITLE
Blaze: Make HelperMap reactive like ReactiveDict

### ISSUE THREAD

**Issue by dalgard** [meteor/meteor#5194]
I propose improving Blaze templates by making the internal `__helpers` HelperMap reactive.

With this feature, if I use a helper that doesn't exist yet, but add the helper later – e.g. after or during the materialization of the template – each place the non-existing helper was used would rerun with the newly added helper.

My use case has to do with `dalgard:viewmodel`. Here, helpers may get created on-the-fly by binding to some property using `{{bind ...}}`, but if I use these ad-hoc helpers *earlier* in the template than the `{{bind ...}}` statement, they never rerun.

**Comment by avital** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I've never used your viewmodel package, and it was a little much for me to wrap my head around right now, so I may be misunderstanding some things.

Why does the viewmodel package interact with Blaze helpers to begin with? It sounds like `{{bind}}` defines a new helper? Is that necessary? Can't `{{bind}}` just be a dispatcher that calls into whatever it needs to, while reading from some reactive variables inside viewmodel?

**Comment by avital** [comment]
cc @dackerman

**Comment by dalgard** [comment]
I think you've understood the situation correctly.

One of the things that makes my viewmodel solution especially lean is that every property on a template's viewmodel is automatically registered as a Blaze helper.

Another feature is that you don't have to actually declare the viewmodel properties explicitly. You can simply bind to a name and this property is created behind the scenes and registered as a Blaze helper.

A new property may be created when some `{{bind}}` statement is evaluated, but if this happens late in a template, any spot where the property name was used as a helper earlier is completely lifeless.

This can easily be fixed by making the `__helpers` HelperMap used by the `lookup` function reactive.

I've made it work by overwriting the methods on `Template.body.__helpers.constructor.prototype`, but since this class is not part of the API, it must be considered a hack.

I could send a pull request of a few lines, but I'm not so confident about writing tests and stuff like that.

I would consider the feature backwards compatible, though, since declaring helpers programmatically during or after the materialization of a template view hasn't really ever been described as having a particular behavior.

**Comment by avital** [comment]
I haven't yet understood why your desired feature requires changing Blaze.

Why doesn't `{{bind}}` do the "reactively call the right function" logic? Why does it need to happen inside of Blaze's helper map?

Adding new features to Meteor requires maintaining them, documenting them, testing them, committing to them going forward, etc; so we'll need a compelling use-case.

**Comment by dalgard** [comment]
I think I can explain better with an example.

```javascript
// No helpers or anything else is declared on this template
```

```html
<template name="example">
  <p>{{title}}</p>
  <input type="text" placeholder="Write a title" {{bind 'value: title'}}>
  <p>{{title}}</p>
</template>
```

What happens when this template is rendered?

1. Blaze tries to resolve the first helper – `{{title}}` – via the `lookup` function. It looks in the `Template.example.__helpers` HelperMap and doesn't find anything. If nothing is found further up in the chain, nothing is output.

2. Blaze runs the global `{{bind}}` helper with the bind expression `value: title`. The `value` binding demands the creation of a new property on the template's viewmodel – `title`.

3. When a new property is created on the viewmodel, this property is automatically registered as a Blaze helper:

```javascript
let key = "title";
this.view.template.helpers({
  [key](...args) {
    return Template.instance().viewmodel[key](...args);
  }
});
```

In other words, the new helper is added to the `__helpers` HelperMap on-the-fly, during the first materialization of the template.

4. Now Blaze reached the last line in the template and once again tries to resolve the `{{title}}` helper. This time it is successful, and this last use of `title` will update reactively to reflect the property in the viewmodel (which is reactive).

The problem is, that the first time `{{title}}` was used will never output anything, because no dependencies were registered when it ran – because the property didn't exist.

The way to resolve this is the same way ReactiveDict works.

1. When `lookup` asks the HelperMap whether this helper exists, a dependency should be created – what ReactiveDict calls `_ensureKey`.

2. When the helper is then actually created, it triggers a `changed` event for the dependency that was already there, and `lookup` will re-run, this time finding the new viewmodel Blaze helper.

It may seem like a lot to ask, but I really don't think it is – it is a few lines of code that will ensure that helpers that are used in a template will actually update if the helper is added to the template *after* it has already rendered.

I would say it's a pretty simple use of reactivity.

**Comment by avital** [comment]
I understand what you're saying, but let's try to keep this conversation
more focused:

Why would a user render a templates that uses a helper that isn't yet
defined? The .html template file and helper definitions should be seen as
one unit, even though they are in different files. (Compare to say, React,
where the entire component is defined in one file.)

Adding new helpers mid-way through an application execution should be seen
as an anti-pattern. Your suggestion would encourage that.

Happy to learn something new, if you can explain the rationale.

**Comment by dalgard** [comment]
Good question. The answer is that it allows using an implicit viewmodel – or let's just say, implicit helpers that are created on-the-fly.

Angular allows it – using a viewmodel that isn't declared in advance:

```javascript
// A controller will be created implicitly and the $scope object is the viewmodel
```

```html
<div ng-app="myApp">
  <p ng-bind="title"><!-- The value of $scope.title is output here --></p>
  <input type="text" placeholder="Write a title" ng-model="title">
</div>
```

In Blaze, this super-lean way of using an implicit viewmodel is not possible because of what I've described above.

**Comment by dalgard** [comment]
As can be seen by the lines in `dalgard:viewmodel` that I've referenced, it is possible to override HelperMap to add this behavior, but it's definitely supported in the official API.

**Comment by mitar** [comment]
I would suggest that you simply hook into [`Blaze._getTemplateHelper`](https://github.com/peerlibrary/meteor-blaze-components/blob/master/lib.coffee#L70) method and make template resolving any way you want. BTW, there is a current specification that this function should not create any reactive dependencies itself. Not sure why that is required, but it is there in the comment. So in the case that helper is not resolved, you should probably return a function which creates a dependency, instead of `null` or something and creating a dependency.

Having this in mind probably means that even if `__helpers` would be reactive, it would not help you, because `Blaze._getTemplateHelper` should not create a reactive dependency.

In your case you might want to hook into [`Blaze.View.prototype.lookup`](https://github.com/meteor/meteor/blob/devel/packages/blaze/lookup.js), because you probably want to run a default version and if it is returning `null`, then you instead return a function which waits for possible future `helper`.

**Comment by dalgard** [comment]
@mitar: Thanks for taking this up. I like your suggestion, but I would need to wrap `Template.example.helpers()` as well, if I want things to be reactive.

Do you know if there are other ways/methods used by Meteor or 3rd parties for adding helpers?

**Comment by mitar** [comment]
Look into [template-extension](https://github.com/aldeed/meteor-template-extension). That package allows copying helpers.

But yes, wrapping `helpers` should be easy.

**Comment by dalgard** [comment]
Good thinking. I'm using `template-extension` myself. Let's hope aldeed isn't writing directly to the `__helpers` collection. Although... I guess that would pretty much be his only option.

The reasons for making plumbing methods part of the public API become more and more apparent. I think the Blaze group would do well to sit down and make a decision on what methods to make public in the next version.

**Comment by dalgard** [comment]
Yes, `aldeed:template-extension` does copy directly from/to `__helpers`... This calls for a Blaze method for retrieving all helpers.

These methods could also alleviate the need for the crazy `" helperName"` trick by storing them on an *actual* private object.

I'd be happy to send a pull request with these changes.

**Comment by dalgard** [comment]
I've created a Blaze extension for getting and setting template helpers reactively, the way I've described above. It works by wrapping the two methods, `Template.prototype.helpers` and `Blaze._getTemplateHelper`.

The package hasn't been published yet, but can be found here: [`nordlys:get-helper-reactively`](https://github.com/nordlys-io/meteor-get-helper-reactively/)

I'm satisfied with this solution, for the time being.

**Comment by mitar** [comment]
Have you seen this comment: https://github.com/meteor/meteor/blob/devel/packages/blaze/lookup.js#L130

**Comment by dalgard** [comment]
Thanks – you pointed it out. I have to admit that I don't take too heavily to these kinds of comments; we create our software in an environment that lasts – at the most – a year or two, and if something like Blaze doesn't keep up with the times, well ... good riddance ;) In the meantime, a lot of value may be created from hooking into existing stuff.

**Comment by mitar** [comment]
Maybe you should write this policy into the README of your package. ;-) That this is breaking required semantics of Blaze.

**Comment by dalgard** [comment]
Seems fair – thanks for pointing it out. Would be nice to know the specific motivation for the code comment, though. @dgreensp
