### ISSUE TITLE
[typographical error?]

### ISSUE THREAD

**Issue by Lesp1ker** [meteor/meteor#5195]
https://github.com/meteor/meteor/blob/devel/tools/meteor-services/auth.js
0o600 mode?
file auth.js:
150. var fd = files.open(tempPath, 'wx', 0o600);

console:
... var fd = files.open(tempPath, 'wx', 0o600);
SyntaxError: Unexpected token ILLEGAL...

**Comment by stubailo** [comment]
This is an ES2015 feature, we transpile all of the files with Babel here: https://github.com/meteor/meteor/blob/devel/tools/tool-env/install-babel.js

Where are you trying to run this code?

**Comment by Lesp1ker** [comment]
I try to start auth.js on node.js
I want to use service of authorization of provider together with accounts-meteor-developer.
(я плохо понимаю английский, можно на русском?)
