### ISSUE TITLE
Getting Path too long issues on alternate windows installation

### ISSUE THREAD

**Issue by ccverak** [meteor/meteor#5196]
I have followed the instructions described here: https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation
While extracting the archive I'm getting path too long issues, even if I try to uninstall into C:\m.

I've tried with 7zip and WinRaR and I'm getting the same problem with both.

It fails with several is-property directories, is there any workaround to get this working?
BTW, using gitbash on windows and meteor (linux version) in combination will work?

**Comment by sliedig** [comment]
Not sure if this is related but I keep getting prompted for file replacements when extracting the tar file. 

![image](https://cloud.githubusercontent.com/assets/597073/10007533/a6ece2f8-60f8-11e5-8974-0873b144d1ea.png)

Figuring I should replace the file I get the following after the extraction completes

![image](https://cloud.githubusercontent.com/assets/597073/10007593/2f5bcab4-60f9-11e5-8b12-a21c6b6c8bba.png)

The files are never extracted.

**Comment by KamilaDanielo** [comment]
Try the Long path tool. It is really awesome tool.

**Comment by stubailo** [comment]
Interesting - other people have successfully used this method to install Meteor, I wonder what they are doing differently.

We use 7zip internally to do this, and it seems to work.

**Comment by gamicklisafisher** [comment]
I had this problem for a long time.
My friend recommended me Long Path Tool for fixing this.

**Comment by abernix** [comment]
Closing as I believe this problem is resolved in newer versions of 7zip and Meteor (which uses NPMv3 now).

Happy to reopen if the problem continues for you!  Thanks for opening this originally!
