### ISSUE TITLE
Meteor's Coffeescript implementation doesn't handle string interpolation in object literal keys.

### ISSUE THREAD

**Issue by groeneveld** [meteor/meteor#5197]
In the online Coffeescript.org interpreter I can run the following just fine:
```
key='blah'
a={"#{key}": 0}
```

When I run the same in Meteor it generates an 'unexpected string interpolation' error.

Perhaps this won't be a problem when Meteor 1.2 supports ES6 and we can use computed property names?

**Comment by msolters** [comment]
This is interesting.  I've never seen CS work that way.  I have traditionally done:
```
a = {}
a[key] = 0
```

But I can confirm it works in the interactive `coffee>` environment.

**Comment by groeneveld** [comment]
That's exactly what I'm doing now too. It's a bit more verbose, especially
when you dont need to assign the object to a variable.

On Friday, September 18, 2015, Mark Solters <notifications@github.com>
wrote:

> This is interesting. I've never seen CS work that way. I have
> traditionally done:
>
> a = {}
> a[key] = 0
>
> But I can confirm it works in the interactive coffee> environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/5197#issuecomment-141608656>.
>


-- 

--
Mark Groeneveld
616-594-0467

**Comment by zimme** [comment]
Is is possible that this is a feature of a newer version of coffeescript than meteor is using?

**Comment by groeneveld** [comment]
It looks like it was removed from Coffeescript in 0.9.6 but the functionality stuck around in the online coffeescript.org compiler.

https://github.com/jashkenas/coffeescript/issues/786

**Comment by yyx990803** [comment]
This feature was once removed from CoffeeScript and added back in 1.9.1. It's likely the `coffeescript` Meteor package you are using is using an older version of CoffeeScript. The latest `coffeescript` package uses 1.9.2 which should support the feature. I just tested in Meteor 1.2.0.1 and the code sample works fine.

**Comment by msolters** [comment]
![](https://mlpforums.com/uploads/monthly_12_2012/post-5946-0-76779800-1355630785_thumb.png)
