### ISSUE TITLE
[1.2] Meteor hanging at 100% cpu usage with ecmascript package and big JS file

### ISSUE THREAD

**Issue by jaimie-van-santen** [meteor/meteor#5198]
We are using Flat-UI in our apps. When adding the `ecmascript` package Meteor hangs and hits 100% CPU usage while starting. The problem is the provided `flat-ui.js` file which is ~500KB in file size. Removing it resolves the hanging but results in no FUI JS functionality.

Reproduction can be found here: https://github.com/jaimie-van-santen/ecmascript-hangs-issue

**Comment by benjamn** [comment]
Would it help in the meantime if you could just exclude that file from `ecmascript` compilation?

**Comment by jaimie-van-santen** [comment]
Yes, since im pretty sure none of the code in the library uses ES2015 functionality. How do i exclude files from being compiled?

**Comment by benjamn** [comment]
The workaround we settled on was to skip `ecmascript` compilation for files with the `.es5.js` file extension. Let us know if that doesn't serve your needs!

**Comment by jaimie-van-santen** [comment]
Yup! Renaming and checking out the latest devel dev bundle fixed the problem. Thanks!

**Comment by Batistleman** [comment]
Can someone add this to the upgrade guide? https://quip.com/RXFlAk9Rc2xI My app was hanging during the build without any warnings.

---

> To exclude files from the ecmascript compiler, use the extension .es5.js. (There is an issue with large js files: https://github.com/meteor/meteor/issues/5198)

**Comment by rgstephens** [comment]
@benjamn How do I know which file it's hanging on?  I'm running into this on Meteor 1.4.1.2

**Comment by evertonfraga** [comment]
For reference, here's a one liner to recursively find all .js files sorted by size (linux and mac)

```
find . -type f -exec du -h {} + | grep -E "\.js$" | sort -r -h | more
```
