### ISSUE TITLE
Array.prototype.find is not working

### ISSUE THREAD

**Issue by matfin** [meteor/meteor#5199]
I found a really odd bug when I was updating my app to Meteor 1.2 rc 15. It seems that Array.prototype.find cannot be found or run. I have created a simple project to demonstrate the problem which can be seen at <https://github.com/matfin/array_find>.

I am running OSX Yosemite with Node v4.1.0. Has anyone else seen this issue ?

**Comment by stubailo** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

Did it work for you in previous versions of Meteor, say 1.1?

**Comment by matfin** [comment]
It did. The app I was running it in uses the latest stable version of Meteor. You can see it being applied in one of my projects [here](https://github.com/matfin/annachristoffer/blob/master/server/publications.es6.js#L38).

This project uses the grigio:babel package which I have since removed as part of the upgrade process to 1.2.

**Comment by benjamn** [comment]
It looks like `Array.prototype.find` was provided by `grigio:babel` via `core-js`. I think it makes sense for Meteor 1.2 to provide it as part of the `ecmascript-collections` package (which is also based on `core-js`).
