### ISSUE TITLE
[1.2 RC16] Orientation locked to portrait mode on iPad

### ISSUE THREAD

**Issue by cedla** [meteor/meteor#5200]
Hi,

Every app I create with Meteor 1.2 RC16 is locked to portrait mode on iPad. I'm unable to rotate to landscape mode. And the iOS' orientation lock setting is disabled. No problem on Android. Everything is working fine with Meteor 1.1. 

Tested on:
- iOS 8.4 and 9, on both iPad emulators and devices
- Meteor 1.2 RC11 / RC15 / RC16
- no problem so far on Android (tested on Android 4.4 and 5.1, both emulators and devices)

I'm using Mac OS X El Capitan GM and Xcode 7 final. I haven't done any test on Xcode 6.4.

How to reproduce:

```bash
meteor create my-app
cd my-app
meteor update --release METEOR@1.2-rc.16
meteor add-platform ios
meteor run ios-device # and then choose an iPad emulator or device
```

I've tried the ```Orientation``` setting in the ```mobile-config.js``` file, with no effect:

```js
App.setPreference('Orientation', 'default'); // Locked to portrait mode
App.setPreference('Orientation', 'portrait'); // Locked to portrait mode
App.setPreference('Orientation', 'landscape'); // Locked to landscape mode
```

Any help will be greatly appreciated :)

**Comment by martijnwalraven** [comment]
This appears to be a known Cordova issue (see [CB-6026](https://issues.apache.org/jira/browse/CB-6026) and [CB-8783]( https://issues.apache.org/jira/browse/CB-8783) that has recently been solved (see the section on the `Orientation` setting in the [edge documentation](http://cordova.apache.org/docs/en/edge/config_ref_index.md.html#The%20config.xml%20File)).

When directly editing the `config.xml`, it seems you would now be able to add this to support all orientations:
```xml
<platform name="ios">
   <preference name="Orientation" value="all" />
</platform>
```

Unfortunately, our current `mobile-config.js` syntax doesn't allow specifying platform-specific values like this. Solving this will require some thinking and I won't be able to fix this for 1.2.

As a workaround, you can specify the supported orientations directly in the Xcode project (on the 'General' tab of the app target), but this is not a very convenient option as the settings will be removed at every build.
<img width="238" alt="screen shot 2015-09-18 at 09 26 20" src="https://cloud.githubusercontent.com/assets/54485/9954218/8934767c-5de7-11e5-9bfc-a20fa61bc485.png">

**Comment by cedla** [comment]
I have made a pull request that fixes that. I've added a third parameter to ```App.setParameter``` to specify the platform:
```js
App.setPreference('Orientation', 'default'); // optional
App.setPreference('Orientation', 'all', 'ios');
```

Hope this helps.

**Comment by martijnwalraven** [comment]
Thanks for your pull request! Just in time for 1.2 :)

**Comment by chmac** [comment]
For anyone else stumbling upon this issue, I tried the code above but couldn't get rotation to work on an iPhone SE with Meteor 1.3.2.4. However, if I removed the first `default` line, and added only the second line, it worked.

So I added this to `mobile-config.js`:

````javascript
    App.setPreference('Orientation', 'all', 'ios');
````

**Comment by dohomi** [comment]
I tried @chmac solution but then rotation is not working on `android` devices. Any thoughts on this issue?

**Comment by cunneen** [comment]
@dohomi have you tried this?

```js
App.setPreference("Orientation", "default", "android"); //for android
App.setPreference("Orientation", "all", "ios"); //for ios
```

**Disclaimer** I haven't tried it myself but I'd expect it to work.

**Comment by dohomi** [comment]
@cunneen yes this is what works for me. Would be great if the docs would be updated
