### ISSUE TITLE
jshint: enable multiple jshintrc files

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5201]
The jshint package only supports one jshintrc file, but consider that an app can contain packages in the packages folder - these could/should have their own jshint files. We use this jshint feature for maintaining dependencies/tracking missing deps down is a bit easier in jshint.

**Comment by stubailo** [comment]
I think it does support a jshintrc file per package, no?

**Comment by raix** [comment]
not if the packages are in the meteor app folder. I complains about multiple jshintrc files, wich it odd since jshint supports this + extending of eg. parent configs etc.

**Comment by stubailo** [comment]
I think the best option is to simply use an external linter for this. In Meteor 1.3 with standard modules, it will be easy to use ESLint directly without it complaining about undefined globals.

**Comment by raix** [comment]
yeah - we dont actually need meteor to handle this for us - plain eslint works fine in ide's/editors, pre commit hooks and CI
