### ISSUE TITLE
Transition appearing on initial mount using React

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor/meteor#5207]
I'm using the guide here to implement transitions when elements are added/removed from the DOM to implement infinite scroll:

https://facebook.github.io/react/docs/animation.html

However, though the transitions are working as expected, they're appearing even on initial page load, despite what the docs say:

```
ReactCSSTransitionGroup provides the optional prop transitionAppear, to add an extra transition phase at the initial mount of the component. There is generally no transition phase at the initial mount as the default value of transitionAppear is false. The following is an example which passes the prop transitionAppear with the value true.
```

Here's my component:
```
C.FeedList = React.createClass({
    render() {
        return (
            <div>
            <C.ReactCSSTransitionGroup transitionName="feed-transition">
        {
          this.props.posts.map(doc => {
            return <C.PostItem key={doc._id}
              { ...doc }
              destroyPost={ doc.destroy }/>;
          })
        }
            </C.ReactCSSTransitionGroup>
      </div>
        );
    }
});
```

Any ideas?

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

And if it is a bug, it's more likely to be a bug in React, so I would post there: https://github.com/facebook/react

**Comment by nicholasalanbrown** [comment]
This isn't a "how can I do this question." I'm saying that the behavior does not match what the official React docs show and the only difference between my code and their example is the Meteor mixin, so I felt like it was reasonable to assume that Meteor officially supporting React as a view layer would translate to help troubleshooting this issue, much as you would anything with the Meteor implementation of Blaze.

If I've misunderstood what "official support" means I apologize.

**Comment by stubailo** [comment]
I think when we say "official support" we mean support for the connector between Meteor and React. If you are submitting a bug to Meteor, it would be good to have some supporting information confirming that it is a bug that we can fix at all, and not something in the React library itself.

It might be easier to find out if you provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
