### ISSUE TITLE
Option to disable build tool spinner

### ISSUE THREAD

**Issue by zol** [meteor/meteor#5208]
It would be great if we allowed folks to disable the spinner in the build tool as it generates a heap of spurious logging inside automation tools such as Travis-CI.

**Comment by justinsb** [comment]
`METEOR_PRETTY_OUTPUT=0` is supposed to do this
https://github.com/meteor/meteor/blob/devel/tools/console/console.js#L76

**Comment by zol** [comment]
Thanks @justinsb - that did the trick.
