### ISSUE TITLE
es5-shim version conflict in create --release 1.2-rc.17

### ISSUE THREAD

**Issue by wh0** [meteor/meteor#5210]
```
$ meteor create --release 1.2-rc.17 ttttest
=> Errors while creating your project

While selecting package versions:
error: Conflict: Constraint es5-shim@0.1.0-rc.0 is not satisfied by es5-shim 4.1.13-rc.1.
Constraints on package "es5-shim":
* es5-shim@=4.1.13-rc.1 <- top level
* es5-shim@0.1.0-rc.0 <- meteor 1.1.7-rc.2 <- autopublish 1.0.4-rc.0
```

I'm not sure where all these constraints are from. `meteor` only depends on `es5-shim` weakly, and with no version constraint set. And I don't see `4.1.13` anywhere.

**Comment by BrettTrotter** [comment]
https://forums.meteor.com/t/public-release-candidate-of-meteor-1-2/8986/132
claims "It's due to simple:pg / simple:bookshelf"

**Comment by stubailo** [comment]
This is a real thing, we had some errors with version numbers and publishing - it won't affect the real release. Easiest fix is to use an earlier RC (for example 12) or remove autopublish for now.

**Comment by wh0** [comment]
1.2-rc.18 doesn't have this problem.

**Comment by stubailo** [comment]
Great, thanks for updating!
