### ISSUE TITLE
[1.2-rc.17] Meteor build not updating properly

### ISSUE THREAD

**Issue by sircharleswatson** [meteor/meteor#5213]
I'm running into an error where my builds are all of a sudden reverting to a previous version of my app.

I noticed this happening when I initially had a console log in one of my files then proceeded to delete it. Then a few hours later, it started showing again. When I look in `.meteor/local/build/programs/web.browser/packages/mypackage.js` it is indeed showing the old code that was there before, but in the original code, it is completely different.

If I go in to update that package and file specifically, after seeing the phantom `console.log()` the app will rebuild it. However, if I don't touch that package for a while, I have a feeling it will have more phantom code.

**Comment by sircharleswatson** [comment]
A little more information that might be helpful:

I did some more digging because now this out of sync issue is happening a lot and it's getting frustrating.

I found that the packages I created in my app are showing up correctly in `.meteor/local/isopacks` but that it's getting out of sync with `.meteor/local/build/programs/web.browser/packages`

The `web.browser/packages` are the ones that are showing old code (code that I changed at the beginning of my 12 hour programming session). Quite frustrating!.

A temporary solution is to shutdown the meteor app, then wipe the `web.browser/packages` directory and then restart the app.

**Comment by stubailo** [comment]
Can you reproduce this issue consistently? Is there some set of steps that always or almost always results in this out of sync issue happening?

**Comment by sircharleswatson** [comment]
Honestly, I'm not sure how to reproduce it.

Especially because it sometimes doesn't happen until after hours of working on the project. It then for some reason (I'm guessing) starts to grab the wrong files out of the `bundler-cache/linker` but I'm not sure. :disappointed:

**Comment by M4v3R** [comment]
I han into the same issue. I did a change in few files, ran `meteor bundle bundle.tar.gz` and than examined its contents and it turned out it had old files.

**Comment by jergason** [comment]
FWIW I thought I was running in to this same problem. The real issue turned out to be some copy-pasted code from a dependency. The copy-pasted code was updated, but the dependency was not, so it looked like the code changes didn't make it in to the build.
