### ISSUE TITLE
Twitter.requestCredential not returning in callback from Twitter handshake (iOS mobile Chrome only)

### ISSUE THREAD

**Issue by connorblack** [meteor/meteor#5214]
I'm currently dealing with a weird bug.

Our app uses `Twitter.requestCredential` to let users add multiple Twitter accounts to their application, and when testing across multiple devices and browsers, it appears that on mobile chrome (v 45.0.2454.89) on iOS (v 8.4.1), a call such as the one below does not illicit any callback. It pops open the api.twitter.com auth in a new tab, lets you successfully sign in with a Twitter account, but then nothing `alert`s: 

```
Twitter.requestCredential (resp) =>
	console.log resp
	alert(resp) 
    ...
```

What's extremely weird is that this works on mobile safari iOS (v 8.4.1), mobile chrome (v 45.0.2454.94) on Android (v 5.1.1) and on all major releases on desktop clients on OSX v 10.10.5 (14F27). 

Is anyone else running into this error? I would replicate it, but it's a little difficult without giving away my Twitter keys and hosting an application.

I'm currently seeing if this error happens on an iOS cordova build.

**Comment by stubailo** [comment]
@connorblack any more information about this?

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
