### ISSUE TITLE
CSS autoprefixer

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#5219]
***6 Upvotes*** I want to create a meteor compiler for CSS autoprefixer.

The problem is, if I add a compiler for 'css'-extensions, I get this error:
`error: conflict: two packages included in the app (meteor and seba:autoprefix) are both trying to handle *.css`.
Only workaround I can currently think of is registering the compiler for another prefix like 'autoprefix.css' files, but then I have to name all my files like this...

Furthermore, I also wrote a plugin to compile sass to css. But, after the SCSS file is compiled to CSS, it is not fed to the autoprefix compiler. So does this mean there is no compiler chaining?

Third problem: I guess files from external meteor packages can not be processed with compilers anymore? Because, in the case of autoprefixing, you might want to do this for all css files, even the ones coming from external packages. This is probably true for a lot of POSTCSS plugins.
Therefore it might make more sense to have these in the same build step like minification?
So maybe I should add the autoprefixer as a minifier instead of a compiler? But in that case, the naming is weird and I don't know if I can add an additional minifier (next to the one that actually minifies) for CSS files?

I created a repo with my SCSS and Autoprefix compilers that you can play around with: https://github.com/sebakerckhof/meteorcompiler

**Comment by stubailo** [comment]
I think these are some very legitimate points, but unfortunately I don't think we will be able to address any of them in 1.2. Hopefully soon after we can put more work into making our build system more flexible, but we've got to ship something first.

1. Yes, right now the `meteor` package includes the default `css` compiler, and this isn't removable.
2. I think a CSS post-processor would fall into some sort of `minifier` category, insofar as minifiers are defined as things that run after compilers and can operate on multiple files at once. Perhaps this isn't a great name.
3. Yes, a compiler is a package-internal dependency, meaning different packages can use different CSS compilers it they want. The minifier is the thing that brings it all together in the end.

I think you're basically right on all of your points, unfortunately we don't support these features at the moment. I'll reopen this as a feature request.

**Comment by Siyfion** [comment]
I too was only looking just now at how I'd go about integrating an "Autoprefixer" type package into the build chain, but after finding this, I may have to wait until there's a bit more structure in place to allow it.

**Comment by sebakerckhof** [comment]
Actually I think a css postprocessor could fall in 2 categories. Either a minifier or a compiler. A minifier (albeit badly named) because of what you've said in your comment above. Or a compiler if you want to make a package that has a piece of css ready to use with the browsers you want the package to support without an end-user having to do anything. Then it is similar to the ecmascript compiler, which essentially does for js what post processors do for css.

If you see what complex setups people build with gulp, they will probably also expect the same flexibility in Meteor. Chaining of build plugins seems like a good way to cover a lot of use cases. And I don't think it would be that hard for meteor to support.

**Comment by derwaldgeist** [comment]
+1

**Comment by lpender** [comment]
+1

**Comment by SavePointSam** [comment]
+1

**Comment by glasser** [comment]
@Slava was originally trying to add a CSS postprocessor step as part of 1.2 but we ended up cutting that for time.

**Comment by SavePointSam** [comment]
@glasser Any idea when that may be implemented? Or if we could just turn off the default `css` compiler? That would be perfect.

**Comment by glasser** [comment]
I'm not sure if that's planned any more.  We learned a lot in the difficult process of making these relatively small improvements to Isobuild, and my personal hope (though I'm focused on Galaxy these days myself) is that future effort gets put into moving away from Isobuild to something more standard rather than adding more features to Isobuild.

**Comment by aunz** [comment]
+1

**Comment by stubailo** [comment]
I've changed the title of the issue to be more specific. I think the current plan is to build autoprefixer into a minifier package. We ran into a small snag, discovered by @sebakerckhof, where it's not currently possible to pass a config file into a minifier: https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/isobuild/isopack.js#L817

Filed a new issue to improve minifiers: https://github.com/meteor/meteor/issues/5512

**Comment by stubailo** [comment]
Even though this is currently a feature request on Meteor, I don't think this should necessarily result in a "core" package for autoprefixer. Let's focus on addressing the things that are blocking the production of such a package, as @sebakerckhof was initially talking about. Then we can feature that package in the Meteor guide section about build plugins.

**Comment by stubailo** [comment]
This is a really great approach: https://github.com/juliancwirko/meteor-postcss

I'd like to validate that it works, but if it does it seems like an ideal solution for now.

**Comment by stubailo** [comment]
Yes, it also reads the config file from FS, which sucks but can't really be fixed until #5512

**Comment by carlosbaraza** [comment]
:+1:

**Comment by faceyspacey** [comment]
+1

**Comment by sebakerckhof** [comment]
I'll close this since we have both my plugin and the one from juliancwirko now.

**Comment by mitar** [comment]
See #7727 pull request for my work on this feature.
