### ISSUE TITLE
Accounts: option to activate users by (authorized) registered user

### ISSUE THREAD

**Issue by volontarian** [meteor/meteor#5222]
Guests are able to sign up but need to be activated by a (authorized) registered user before they can sign in.
Users who are able to activate users should get an e-mail on every sign up request.

Maybe someone also knows a workaround to override accounts package and achieve the feature until it's implemented.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Accounts%3A%20option%20to%20activate%20users%20by%20(authorized)%20registered%20user&body=Migrated%20from:%20meteor/meteor%235222) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
