### ISSUE TITLE
static-html / caching-html-compiler have a jQuery dependency

### ISSUE THREAD

**Issue by mxab** [meteor/meteor#5223]
Hi,
if I use the static-html package, don't have jQuery in my dependency and use attributes on the body tag, the application fails since the caching-html-compiler uses jQuery to attach attributes to the body element.

https://github.com/meteor/meteor/blob/devel/packages/caching-html-compiler/caching-html-compiler.js#L112

This is my custom platform package
https://github.com/planet-training/angular-meteor-platform/blob/1.2-with-rc-deps/package.js

and this its sample project
https://github.com/mxab/meteor-ng-app/tree/attr_on_body

One thing to fix this is to depend on jQuery in the static html package but having jQuery as dependency on the "static-html" package is a bit of a paradox :)

**Comment by stubailo** [comment]
Ooooooooh, that's a good point. I assume it's easy to change that code to not use JQuery, will do that now.

**Comment by stubailo** [comment]
Fixed, releasing in RC 19: https://github.com/meteor/meteor/commit/e6bc9413f3f7313225dc4ae87e2e25a85ca0c59a
