### ISSUE TITLE
Template events being lost when template is re-located in the dom...

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#5224]
Please see this forum post:

https://forums.meteor.com/t/template-event-attachments-being-lost-when-the-template-is-moved/9038/2

Plus, this also happens to any event that is defined in the Template.my.events block.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
