### ISSUE TITLE
Internal exception while processing message [reinstall to fix]

### ISSUE THREAD

**Issue by awsp** [meteor/meteor#5228]
After upgrading Meteor to 1.2 for my existing project, I keep getting this error.
So I went to create a fresh project, and it is still giving me this error. See below, 

```
Cannot read property '_CurrentInvocation' of undefined TypeError: Cannot read property '_CurrentInvocation' of undefined
```

Here is some error messages from the fresh untouched project. 
```
$ meteor --version
-> Meteor 1.2

=> App running at: http://localhost:3000/
I20150921-16:45:36.614(-10)? Internal exception while processing message { msg: 'connect',
I20150921-16:45:36.616(-10)?   version: '1',
I20150921-16:45:36.616(-10)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property '_CurrentInvocation' of undefined TypeError: Cannot read property '_CurrentInvocation' of undefined
I20150921-16:45:36.616(-10)?     at withoutInvocation (packages/meteor/packages/meteor.js:404:1)
I20150921-16:45:36.617(-10)?     at bindAndCatch (packages/meteor/packages/meteor.js:414:1)
I20150921-16:45:36.617(-10)?     at Object._.extend.setInterval (packages/meteor/packages/meteor.js:441:1)
I20150921-16:45:36.617(-10)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common/packages/ddp-common.js:71:1)
I20150921-16:45:36.618(-10)?     at [object Object]._.extend.start (packages/ddp-common/packages/ddp-common.js:66:1)
I20150921-16:45:36.618(-10)?     at new Session (livedata_server.js:312:20)
I20150921-16:45:36.618(-10)?     at [object Object]._.extend._handleConnect (livedata_server.js:1427:29)
I20150921-16:45:36.618(-10)?     at livedata_server.js:1356:18
```

Error received on client side
![screen shot 2015-09-21 at 4 53 39 pm](https://cloud.githubusercontent.com/assets/2015218/10010074/612c6aa8-6081-11e5-9469-8199d0853bf7.png)

#### System Information
- Mac OS X 10.10.5
- Latest XCode 7.0 and CLI Build tools
- Node version: v0.12.7

**Comment by Shutik** [comment]
+1 on Ubuntu Server 14
```
W20150922-05:46:35.285(3)? (STDERR)
W20150922-05:46:35.306(3)? (STDERR) /root/.meteor/packages/meteor-tool/.1.1.7.2gmdwd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150922-05:46:35.307(3)? (STDERR)                                             throw(ex);
W20150922-05:46:35.308(3)? (STDERR)                                                   ^
W20150922-05:46:35.378(3)? (STDERR) TypeError: Cannot read property '_CurrentInvocation' of undefined
W20150922-05:46:35.379(3)? (STDERR)     at withoutInvocation (packages/meteor/packages/meteor.js:404:1)
W20150922-05:46:35.379(3)? (STDERR)     at bindAndCatch (packages/meteor/packages/meteor.js:414:1)
W20150922-05:46:35.379(3)? (STDERR)     at Object._.extend.defer (packages/meteor/packages/meteor.js:469:1)
W20150922-05:46:35.379(3)? (STDERR)     at [object Object].MongoConnection.tail (packages/mongo/packages/mongo.js:1136:1)
W20150922-05:46:35.380(3)? (STDERR)     at [object Object]._.extend._startTailing (packages/mongo/packages/mongo.js:1602:1)
W20150922-05:46:35.380(3)? (STDERR)     at new OplogHandle (packages/mongo/packages/mongo.js:1441:1)
W20150922-05:46:35.380(3)? (STDERR)     at new MongoConnection (packages/mongo/packages/mongo.js:224:1)
W20150922-05:46:35.380(3)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)
W20150922-05:46:35.381(3)? (STDERR)     at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)
W20150922-05:46:35.381(3)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
=> Exited with code: 8
```

**Comment by pfafman** [comment]
Confirm on same system as @awsp but I don't think the local node version maters for it is running the version bundled with meteor.

It is not a complete crash for meteor still runs and thus I can check the internal node version

```
meteor shell
> process.version
'v0.10.40'
```

FYI: Local node version is v4.1.0

**Comment by nicolaslopezj** [comment]
I think this line has the error 

https://github.com/meteor/meteor/blob/832e6fe44f3635cae060415d6150c0105f2bf0f6/packages/meteor/timers.js#L3

**Comment by awsp** [comment]
@nicolaslopezj

Good catch!
I actually find `_CurrentInvocation` is located at `Package.ddp_client.DDP._CurrentInvocation` instead.

**Comment by AndyHan1001** [comment]
I have met the same issue on my Mac OS X 10.9.5 for meteor 1.2, and node version is 4.1.0

**Comment by martijnwalraven** [comment]
Could someone encountering this issue post their `.meteor/local/versions` file?

**Comment by stubailo** [comment]
Also, @awsp what do you get when you log `Package.ddp`?

**Comment by mplatts** [comment]
Freshly created app on mac 10.10.3:

```
autopublish@1.0.4
autoupdate@1.2.3
babel-compiler@5.8.24
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.1
callback-hook@1.0.4
check@1.0.6
ddp@1.2.1
ddp-client@1.2.1
ddp-common@1.2.1
ddp-server@1.2.1
deps@1.0.8
diff-sequence@1.0.1
ecmascript@0.1.3
ecmascript-collections@0.1.6
ejson@1.0.7
es5-shim@4.1.13
fastclick@1.0.7
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
insecure@1.0.4
jquery@1.11.4
launch-screen@1.0.3
livedata@1.0.14
logging@1.0.8
meteor@1.1.7
meteor-base@1.0.1
minifiers@1.1.6
minimongo@1.0.9
mobile-experience@1.0.1
mobile-status-bar@1.0.6
mongo@1.1.1
mongo-id@1.0.1
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
promise@0.4.8
random@1.0.4
reactive-dict@1.1.1
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
session@1.1.1
spacebars@1.0.7
spacebars-compiler@1.0.7
standard-minifiers@1.0.0
templating@1.1.2
templating-tools@1.0.0
tracker@1.0.8
ui@1.0.7
underscore@1.0.4
url@1.0.5
webapp@1.2.2
webapp-hashing@1.0.4
```

**Comment by stolinski** [comment]
Also having this issue. here is versions .

    accounts-base@1.2.1-rc.3
    accounts-ui@1.1.6-rc.0
    accounts-ui-unstyled@1.1.8-rc.1
    aldeed:template-extension@3.4.3
    amplify@1.0.0
    autoupdate@1.2.3-rc.1
    babel-compiler@5.8.22-rc.1
    babel-runtime@0.1.4-rc.1
    babrahams:editable-json@0.4.3
    base64@1.0.4-rc.0
    binary-heap@1.0.4-rc.0
    blaze@2.1.3-rc.1
    blaze-html-templates@1.0.1-rc.0
    blaze-tools@1.0.4-rc.0
    boilerplate-generator@1.0.4-rc.1
    caching-compiler@1.0.0-rc.0
    caching-html-compiler@1.0.1-rc.0
    callback-hook@1.0.4-rc.0
    check@1.0.6-rc.0
    chuangbo:cookie@1.1.0
    coffeescript@1.0.8-rc.5
    cosmos:browserify@0.5.1
    dburles:mongo-collection-instances@0.3.4
    ddp@1.2.1-rc.0
    ddp-client@1.2.1-rc.2
    ddp-common@1.2.1-rc.0
    ddp-rate-limiter@1.0.0-rc.1
    ddp-server@1.2.1-rc.2
    deps@1.0.8-rc.0
    diff-sequence@1.0.1-rc.0
    ecmascript@0.1.3-rc.3
    ecmascript-collections@0.1.5-rc.1
    ejson@1.0.7-rc.0
    email@1.0.7-rc.0
    erasaur:meteor-lodash@3.10.1_1
    fastclick@1.0.7-rc.0
    fortawesome:fontawesome@4.4.0
    geojson-utils@1.0.4-rc.0
    gwendall:session-json@0.1.7
    hot-code-push@1.0.0-rc.0
    html-tools@1.0.5-rc.0
    htmljs@1.0.5-rc.1
    http@1.1.1-rc.1
    id-map@1.0.4-rc.0
    jquery@1.11.4-rc.0
    jsx@0.2.1
    kadira:flow-router@2.6.1
    kadira:react-layout@1.3.0
    lai:collection-extensions@0.1.4
    launch-screen@1.0.3-rc.1
    less@2.5.0-rc.7_1
    livedata@1.0.14-rc.0
    localstorage@1.0.4-rc.0
    logging@1.0.8-rc.1
    markdown@1.0.5-rc.0
    meteor@1.1.7-rc.2
    meteor-base@1.0.1-rc.0
    meteorhacks:async@1.0.0
    meteorhacks:fast-render@2.10.0
    meteorhacks:inject-data@1.4.1
    meteorhacks:npm@1.5.0
    meteorhacks:picker@1.0.3
    meteortoys:allthings@1.2.3
    meteortoys:authenticate@0.4.1
    meteortoys:autopub@0.4.0
    meteortoys:hotreload@0.2.0
    meteortoys:listen@0.3.0
    meteortoys:method@0.4.1
    meteortoys:pro@0.6.2
    meteortoys:pub@0.3.1
    meteortoys:shell@0.4.1
    meteortoys:status@0.1.0
    meteortoys:sub@0.4.0
    meteortoys:toykit@0.8.7
    meteortoys:toypro@0.4.2
    minifiers@1.1.6-rc.1
    minimongo@1.0.9-rc.0
    mobile-experience@1.0.1-rc.0
    mobile-status-bar@1.0.6-rc.0
    mongo@1.1.1-rc.4
    mongo-id@1.0.1-rc.0
    mrgalaxy:stripe@2.1.0
    msavin:jetsetter@1.0.20
    msavin:mongol@1.1.5
    natestrauser:animate-css@3.2.6
    npm-container@1.2.0
    npm-mongo@1.4.39-rc.0_1
    observe-sequence@1.0.7-rc.0
    ordered-dict@1.0.4-rc.0
    promise@0.4.8-rc.0
    random@1.0.4-rc.0
    rate-limit@1.0.0-rc.1
    react@0.1.13
    react-meteor-data@0.1.9
    react-runtime@0.13.3_7
    react-runtime-dev@0.13.3_7
    react-runtime-prod@0.13.3_6
    reactive-dict@1.1.1-rc.0
    reactive-var@1.0.6-rc.0
    reload@1.1.4-rc.0
    retry@1.0.4-rc.0
    routepolicy@1.0.6-rc.0
    service-configuration@1.0.5-rc.0
    session@1.1.1-rc.0
    spacebars@1.0.7-rc.0
    spacebars-compiler@1.0.7-rc.2
    spiderable@1.0.9-rc.1
    standard-minifiers@1.0.0-rc.2
    stolinski:stylus-multi@1.3.4
    templating@1.1.2-rc.7
    templating-tools@1.0.0-rc.0
    tomi:upload-jquery@2.1.8
    tomi:upload-server@1.3.1
    tracker@1.0.8-rc.0
    u2622:persistent-session@0.4.1
    ui@1.0.7-rc.0
    underscore@1.0.4-rc.0
    url@1.0.5-rc.0
    webapp@1.2.2-rc.3
    webapp-hashing@1.0.4-rc.0

**Comment by mplatts** [comment]
@stubailo 

```js
if (Meteor.isClient) {
  Meteor.startup(function () {
    console.log(Package.ddp);
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    console.log(Package.ddp);
  });
}
```

Returns `{}` on both

**Comment by stubailo** [comment]
@mplatts here's what it logs for me:

```
I20150922-01:15:40.826(-4)? { DDP:
I20150922-01:15:40.827(-4)?       { [Function]
I20150922-01:15:40.827(-4)?    { ConnectionError:
I20150922-01:15:40.827(-4)?         captureStackTrace: [Function: captureStackTrace],
I20150922-01:15:40.827(-4)?         stackTraceLimit: 10,
I20150922-01:15:40.827(-4)?         prepareStackTrace: [Function: prepareStackTrace],
I20150922-01:15:40.827(-4)?         __super__: [Error] },
I20150922-01:15:40.828(-4)?      ForcedReconnectError:
I20150922-01:15:40.828(-4)?       { [Function]
I20150922-01:15:40.828(-4)?         captureStackTrace: [Function: captureStackTrace],
I20150922-01:15:40.828(-4)?         stackTraceLimit: 10,
I20150922-01:15:40.828(-4)?         prepareStackTrace: [Function: prepareStackTrace],
I20150922-01:15:40.828(-4)?         __super__: [Error] },
I20150922-01:15:40.828(-4)?      _CurrentInvocation: { slot: 1 },
I20150922-01:15:40.828(-4)?      randomStream: [Function],
I20150922-01:15:40.828(-4)?      connect: [Function],
I20150922-01:15:40.828(-4)?      _allSubscriptionsReady: [Function] },
I20150922-01:15:40.828(-4)?   DDPServer:
I20150922-01:15:40.829(-4)?    { _SessionCollectionView: [Function],
I20150922-01:15:40.829(-4)?      _calculateVersion: [Function],
I20150922-01:15:40.829(-4)?      _WriteFence: [Function],
I20150922-01:15:40.829(-4)?      _CurrentWriteFence: { slot: 2 },
I20150922-01:15:40.829(-4)?      _Crossbar: [Function],
I20150922-01:15:40.829(-4)?      _InvalidationCrossbar:
I20150922-01:15:40.829(-4)?       { nextId: 1,
I20150922-01:15:40.829(-4)?         listenersByCollection: {},
I20150922-01:15:40.829(-4)?         factPackage: 'livedata',
I20150922-01:15:40.829(-4)?         factName: 'invalidation-crossbar-listeners' } } }
```

**Comment by martijnwalraven** [comment]
@stolinski: It seems you are still running an RC. Have you updated to release 1.2?

**Comment by stubailo** [comment]
@mplatts can you post/send a zip file of your whole project directory, including `.meteor/local` with the built files? My email is sashko@meteor.com

**Comment by mplatts** [comment]
@stubailo sent

**Comment by locksalt** [comment]
same with me

I20150922-13:11:37.805(8)? Internal exception while processing message { msg: 'connect',
I20150922-13:11:37.805(8)?   version: '1',
I20150922-13:11:37.805(8)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property '_CurrentInvocation' of undefined TypeError: Cannot read property '_CurrentInvocation' of undefined
I20150922-13:11:37.805(8)?     at withoutInvocation (packages/meteor/packages/meteor.js:404:1)
I20150922-13:11:37.805(8)?     at bindAndCatch (packages/meteor/packages/meteor.js:414:1)
I20150922-13:11:37.805(8)?     at Object._.extend.setInterval (packages/meteor/packages/meteor.js:441:1)
I20150922-13:11:37.805(8)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common/packages/ddp-common.js:71:1)
I20150922-13:11:37.805(8)?     at [object Object]._.extend.start (packages/ddp-common/packages/ddp-common.js:66:1)
I20150922-13:11:37.805(8)?     at new Session (livedata_server.js:312:20)
I20150922-13:11:37.805(8)?     at [object Object]._.extend._handleConnect (livedata_server.js:1427:29)
I20150922-13:11:37.805(8)?     at livedata_server.js:1356:18

**Comment by locksalt** [comment]
on meteor version 1.1.0.3 no errors updating to 1.2 causing this errors...

**Comment by stubailo** [comment]
Well, running with `1.1.0.3` should work in the meantime while we work on this. It's weird that it only breaks for certain people.

@mplatts thanks for sending me the zip, I can see that the error is happening but can't yet establish how the app gets into that state. If you have fast internet, do you mind re-installing Meteor and checking if it still breaks in that way?

**Comment by stolinski** [comment]
You caught the log right before I deleted it :) I forgot that I had
reverted back to the rc that was last working for me.



SCOTT TOLINSKI
www.scotttolinski.com

On Mon, Sep 21, 2015 at 11:18 PM, Martijn Walraven <notifications@github.com

**Comment by stubailo** [comment]
@stolinski so it works fine for you with the RC, but not with the released version?

**Comment by stolinski** [comment]
@stubailo  That's correct. I've run several RCs with no issue. After updating to the released version, I'm getting the same error. "Cannot read property '_CurrentInvocation'"

**Comment by stubailo** [comment]
@stolinski can you send me a zip of your `~/.meteor/packages/ddp/` directory (this is the package cache)?

**Comment by stolinski** [comment]
@stubailo  Would you like the current running the rc, or the 1.2 release version?

**Comment by stubailo** [comment]
All of them if possible, or at least one RC and the final. I want to see how the different versions are represented on disk.

**Comment by stolinski** [comment]
@stubailo On its way.

**Comment by mikemurray** [comment]
I'm having a similar issue

```
W20150921-22:09:59.932(-7)? (STDERR) /Users/mikemurray/.meteor/packages/meteor-tool/.1.1.7.17kjaso++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150921-22:09:59.932(-7)? (STDERR) 						throw(ex);
W20150921-22:09:59.932(-7)? (STDERR) 						      ^
W20150921-22:09:59.978(-7)? (STDERR) TypeError: Cannot read property '_CurrentInvocation' of undefined
W20150921-22:09:59.979(-7)? (STDERR)     at withoutInvocation (packages/meteor/packages/meteor.js:404:1)
W20150921-22:09:59.979(-7)? (STDERR)     at bindAndCatch (packages/meteor/packages/meteor.js:414:1)
W20150921-22:09:59.979(-7)? (STDERR)     at Object._.extend.defer (packages/meteor/packages/meteor.js:469:1)
W20150921-22:09:59.979(-7)? (STDERR)     at [object Object].MongoConnection.tail (packages/mongo/packages/mongo.js:1136:1)
W20150921-22:09:59.979(-7)? (STDERR)     at [object Object]._.extend._startTailing (packages/mongo/packages/mongo.js:1602:1)
W20150921-22:09:59.979(-7)? (STDERR)     at new OplogHandle (packages/mongo/packages/mongo.js:1441:1)
W20150921-22:09:59.979(-7)? (STDERR)     at new MongoConnection (packages/mongo/packages/mongo.js:224:1)
W20150921-22:09:59.979(-7)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)
W20150921-22:09:59.980(-7)? (STDERR)     at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)
W20150921-22:09:59.980(-7)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
```


So I stripped out all packages from my app, and added them back one by one. As soon as I added `accounts-base` the app started crashing with this error.

Leaving `accounts-base` out, the app works fine.

When I have `Items = new Mongo.Collection("items");` the app crashes with the same error.

**Comment by dan335** [comment]
Re-installing meteor fixed it for me.

**Comment by mplatts** [comment]
@stubailo seems to work fine upon re-installing Meteor. Must be a bug in the update process

**Comment by mikemurray** [comment]
Just did the same. Removing the `~/.meteor` directory and reinstalling works.

**Comment by stolinski** [comment]
Re-installing worked for me as well.

**Comment by stubailo** [comment]
Yeah we figured it out, 1.2.0.1 incoming soon probably! glad that reinstalling works.

**Comment by AndyHan1001** [comment]
Me too! reinstalling will help

**Comment by stubailo** [comment]
Going to leave it open until the new release actually comes out. Running some tests now, should be like ~30 mins. Time to watch some TV shows I guess!

**Comment by locksalt** [comment]
yes fix by re-install but is this related to the issue

Exception in callback of async function: ReferenceError: EJSON is not defined
    at MiddlewareStack.concat (http://localhost:3000/packages/iron_middleware-stack.js?ff70621b6c5f6a406edc60600c4b76126dae21d6:303:25)
    at RouteController._runRoute (http://localhost:3000/packages/iron_router.js?dd5fa02859b6335661b94134bd9903be8eecf44d:542:17)
    at Function.Route.dispatch (http://localhost:3000/packages/iron_router.js?dd5fa02859b6335661b94134bd9903be8eecf44d:856:18)
    at route (http://localhost:3000/packages/iron_router.js?dd5fa02859b6335661b94134bd9903be8eecf44d:713:11)
    at boundNext (http://localhost:3000/packages/iron_middleware-stack.js?ff70621b6c5f6a406edc60600c4b76126dae21d6:425:31)
    at http://localhost:3000/packages/meteor.js?5deab0885176b44ccbbbf0b5101b065971c8f283:999:22
    at dispatch (http://localhost:3000/packages/iron_middleware-stack.js?ff70621b6c5f6a406edc60600c4b76126dae21d6:449:3)
    at http://localhost:3000/packages/iron_router.js?dd5fa02859b6335661b94134bd9903be8eecf44d:393:13
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?9309a5697855cef52b32921fbc9dcb1017c58b39:349:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?9309a5697855cef52b32921fbc9dcb1017c58b39:237:10)

**Comment by martijnwalraven** [comment]
@locksalt I don't believe so, this seems like an issue in Iron Router.

**Comment by SachaG** [comment]
> Going to leave it open until the new release actually comes out. Running some tests now, should be like ~30 mins. Time to watch some TV shows I guess!

Could you be a little more specific? Which TV shows should we watch while we wait for a patch to come out? Will any TV show do, or does it have to last exactly 30 minutes?

**Comment by devonbarrett** [comment]
Same error upon upgrade. Tested our app previously with RC-7 and had no issues.

**Comment by stubailo** [comment]
@locksalt your issue seems like a result of iron router not having a dependency on EJSON when it should have one declared. Perhaps file an issue there.

**Comment by stubailo** [comment]
I guess I was optimistic with 30 minutes! Still working through the process.

**Comment by devonbarrett** [comment]
Can confirm reinstalling fixed the issue for me.

**Comment by martijnwalraven** [comment]
@SachaG: I can recommend [Halt and Catch Fire](https://en.wikipedia.org/wiki/Halt_and_Catch_Fire_%28TV_series%29).

**Comment by Shutik** [comment]
reinstalling fixed the issue for me

**Comment by lukasvan3l** [comment]
`meteor update --release 1.2.0.1` works for me! thnx for the quick fix

**Comment by stubailo** [comment]
@lukasvan3l great! Glad that works, now we just need to update the installer etc.

**Comment by awsp** [comment]
Wow, that was fast, just went home. 

@stubailo 
So yea, as other has already mentioned, Package.ddp was an empty object. (When I looked at it in Chrome's debugger)

Thanks for the fix!

**Comment by stubailo** [comment]
OK 1.2.0.1 fixes this. Thanks everyone for reporting and sending us reproductions!

**Comment by AndyHan1001** [comment]
thumb up!

**Comment by rclai** [comment]
Wow, you guys stayed up pretty late lol.

**Comment by mofodox** [comment]
I'm experiencing the same problem here on Meteor 1.5 and I did meteor update even I reinstall MeteorJS but the issue still persists. What do you guys reckon?

**Comment by ichuanHung** [comment]
I have the same problem here on Meteor 1.5 , and meteor create tdb2 --release 1.4.3.1 is still have the problem:
I20170714-01:23:37.139(8)? Internal exception while processing message { msg: 'connect',
I20170714-01:23:37.191(8)?   version: '1',
I20170714-01:23:37.191(8)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
I20170714-01:23:37.191(8)?     at withoutInvocation (packages/meteor.js:443:33)
I20170714-01:23:37.191(8)?     at bindAndCatch (packages/meteor.js:452:33)
I20170714-01:23:37.192(8)?     at Object._.extend.setInterval (packages/meteor.js:479:24)
I20170714-01:23:37.192(8)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common.js:89:44)
I20170714-01:23:37.192(8)?     at [object Object]._.extend.start (packages/ddp-common.js:84:10)
I20170714-01:23:37.193(8)?     at new Session (packages/ddp-server/livedata_server.js:318:20)
I20170714-01:23:37.193(8)?     at [object Object]._.extend._handleConnect (packages/ddp-server/livedata_server.js:1463:29)
I20170714-01:23:37.193(8)?     at packages/ddp-server/livedata_server.js:1379:18

And I did : 
meteor update --all-packages
This project is already at Meteor 1.5, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest
version available:
 * mongo 1.1.18 (1.1.19 is available)         
                                              
Newer versions of the following indirect dependencies are available:
 * allow-deny 1.0.5 (1.0.6 is available)      
 * ddp 1.2.5 (1.3.0 is available)             
 * ddp-client 1.3.4 (2.0.0 is available)      
 * ddp-server 1.3.14 (2.0.0 is available)     
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.

Even I reinstall MeteorJS but the issue still persists. 

On my Mac is 
$ meteor node -v
v4.7.3

Any one can help me , TKS !

**Comment by denispasin** [comment]
Same here.

**Comment by Philip-Nunoo** [comment]
Looks like this issue happened a long time ago and it's back. @denispasin any progress.

**Comment by hwillson** [comment]
See https://github.com/meteor/meteor/issues/8908 - try running:

```
meteor update --release 1.5.1
```

**Comment by denispasin** [comment]
Yep. `meteor update --release 1.5.1` solved it. But since it's not the defaut latest meteor (it doesn't install with a raw `meteor update`) it might still be an issue.

**Comment by hwillson** [comment]
@denispasin It will be recommended (the default) very shortly.

**Comment by denispasin** [comment]
Perfect ! Sorry for the false alarm :)

**Comment by mattiaw** [comment]
Don't want to invest much time on shaky foundation.  Probably going to Angular or back to Backbone.

**Comment by ichuanHung** [comment]
meteor update --release 1.5.1 -- solved it. Thanks a lot.

**Comment by vurumadla** [comment]
can anyone suggest the soltion for this...

I20171005-07:19:15.685(0)?
W20171005-07:19:15.688(0)? (STDERR) The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.
W20171005-07:19:15.689(0)? (STDERR) /home/centos/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171005-07:19:15.689(0)? (STDERR)                                             throw(ex);
W20171005-07:19:15.690(0)? (STDERR)                                             ^
W20171005-07:19:15.690(0)? (STDERR)
W20171005-07:19:15.691(0)? (STDERR) TypeError: Cannot read property 'deny' of undefined
W20171005-07:19:15.691(0)? (STDERR)     at exports.default (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:91154:18)
W20171005-07:19:15.692(0)? (STDERR)     at Object.<anonymous> (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:71141:22)
W20171005-07:19:15.692(0)? (STDERR)     at __webpack_require__ (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62689:30)
W20171005-07:19:15.693(0)? (STDERR)     at Object.installedModules (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62721:19)
W20171005-07:19:15.693(0)? (STDERR)     at __webpack_require__ (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62689:30)
W20171005-07:19:15.694(0)? (STDERR)     at /home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62709:18
W20171005-07:19:15.695(0)? (STDERR)     at meteorInstall.meteor_core.server.server.bundle.min.js (/home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:62712:10)
W20171005-07:19:15.696(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171005-07:19:15.697(0)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171005-07:19:15.698(0)? (STDERR)     at /home/centos/Syndicated Lending/syndicated lending/syndicate_lending_new/.meteor/local/build/programs/server/app/app.js:93000:1
=> Exited with code: 1
