### ISSUE TITLE
Upgraded to 1.2, everything is undefined

### ISSUE THREAD

**Issue by mikeislearning** [meteor/meteor#5231]
Had no errors with 1.1.0.3, but after the upgrade, I see this:
<img width="1401" alt="screen shot 2015-09-22 at 6 21 46 pm" src="https://cloud.githubusercontent.com/assets/3151928/10017246/f40e2aa2-6156-11e5-984b-dafc36e1f618.png">
and this:
<img width="1415" alt="screen shot 2015-09-22 at 6 23 23 pm" src="https://cloud.githubusercontent.com/assets/3151928/10017256/096c2bd8-6157-11e5-9d66-313abfb50bf3.png">
and here is my list of packages:
<img width="620" alt="screen shot 2015-09-22 at 6 25 11 pm" src="https://cloud.githubusercontent.com/assets/3151928/10017387/088e1e82-6158-11e5-89a3-fdfce27a4d54.png">

**Comment by Exilz** [comment]
It's related to materialize, they broke Meteor it with their last version.
Just roll-back to 0.97.0 and you'll be fine !

**Comment by mikeislearning** [comment]
Awesome, thank you!
Before I close the issue, how did determine that?

**Comment by Exilz** [comment]
This drove me mad yesterday and I found out an issue on the Materialize's repo, saying that they declared the Materialize object in a way that broke Meteor. I didn't investigate more, they should fix it soon. :)

**Comment by mikeislearning** [comment]
Good to know, thanks again!

**Comment by yyx990803** [comment]
@Exilz thanks for the clarification :)
