### ISSUE TITLE
mdg:camera - preview not working in browsers after update to v1.2

### ISSUE THREAD

**Issue by miri-am** [meteor/meteor#5233]
When using camera from browsers (firefox, chrome) the preview just shows a black screen.

Reproduction here: https://github.com/miri-am/cameraTest

Getting this warnings in the console:

```
Warning: Blaze.render without a parent element is deprecated. You must specify where to insert the rendered content.
preamble.js:30 Warning: Blaze.insert has been deprecated.  Specify where to insert the rendered content in the call to Blaze.render.
photo-browser.js:132 'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.
```

**Comment by martijnwalraven** [comment]
I don't think these warning are the issue, although they should be fixed. Your project just seems to print the data URL to the console, it doesn't actually display it.

Have you looked at the [simple-photo example](https://github.com/meteor/mobile-packages/tree/master/examples/simple-photo)? This works for me on the most recent versions of both Chrome and Firefox (Safari is not supported).

**Comment by miri-am** [comment]
i know. The problem was the "live-display" from the webcam, which was not showing. However, it seems that this is an issue of my webcam ...  so sorry about this. Can be closed..

**Comment by achtan** [comment]
i got same warning on meteor 1.1
