### ISSUE TITLE
error: unknown package: isobuild:compiler-plugin

### ISSUE THREAD

**Issue by Pierre-Thibault** [meteor/meteor#5238]
Hello,

I still have these errors:

    => Started proxy.
    => Errors prevented startup:
    
    While selecting package versions:
    error: unknown package: isobuild:compiler-plugin
    Required by: meteor 1.1.7-rc.1
    Required by: ecmascript 0.1.3-rc.0
    Required by: ecmascript 0.1.3-rc.0
    
    unknown package: isobuild:minifier-plugin
    Required by: standard-minifiers 1.0.0-rc.1

These errors are appearing after I did `meteor update --release METEOR@1.2-rc.12`. Like @queso dgreensp was suggesting.

My packages versions:

        => Started proxy.
        => Errors prevented startup:
        
        While selecting package versions:
        error: unknown package: isobuild:compiler-plugin
        Required by: meteor 1.1.7-rc.1
        Required by: ecmascript 0.1.3-rc.0
        Required by: ecmascript 0.1.3-rc.0
        
        unknown package: isobuild:minifier-plugin
        Required by: standard-minifiers 1.0.0-rc.1
    Changes to your project's package version selections from updating the release:
                                                
    accounts-base            downgraded from 1.2.1 to 1.2.1-rc.2
    accounts-password        downgraded from 1.1.3 to 1.1.2-rc.1
    amplify                  removed from your project
    autoupdate               downgraded from 1.2.3 to 1.2.3-rc.1
    babel-compiler           downgraded from 5.8.24_1 to 5.8.22-rc.1
    babel-runtime            downgraded from 0.1.4 to 0.1.4-rc.0
    base64                   downgraded from 1.0.4 to 1.0.4-rc.0
    binary-heap              downgraded from 1.0.4 to 1.0.4-rc.0
    blaze                    downgraded from 2.1.3 to 2.1.3-rc.0
    blaze-html-templates     downgraded from 1.0.1 to 1.0.1-rc.0
    blaze-tools              downgraded from 1.0.4 to 1.0.4-rc.0
    boilerplate-generator    downgraded from 1.0.4 to 1.0.4-rc.1
    caching-compiler         downgraded from 1.0.0 to 1.0.0-rc.0
    caching-html-compiler    downgraded from 1.0.1 to 1.0.1-rc.0
    callback-hook            downgraded from 1.0.4 to 1.0.4-rc.0
    check                    downgraded from 1.0.6 to 1.0.6-rc.0
    coffeescript             downgraded from 1.0.9 to 1.0.8-rc.3
    ddp                      downgraded from 1.2.2 to 1.2.1-rc.0
    ddp-client               downgraded from 1.2.1 to 1.2.1-rc.1
    ddp-common               downgraded from 1.2.1 to 1.2.1-rc.0
    ddp-rate-limiter         downgraded from 1.0.0 to 1.0.0-rc.0
    ddp-server               downgraded from 1.2.1 to 1.2.1-rc.1
    deps                     downgraded from 1.0.9 to 1.0.8-rc.0
    diff-sequence            downgraded from 1.0.1 to 1.0.1-rc.0
    ecmascript               downgraded from 0.1.4 to 0.1.3-rc.2
    ecmascript-collections   downgraded from 0.1.6 to 0.1.5-rc.1
    ejson                    downgraded from 1.0.7 to 1.0.7-rc.0
    email                    downgraded from 1.0.7 to 1.0.7-rc.0
    fastclick                downgraded from 1.0.7 to 1.0.7-rc.0
    geojson-utils            downgraded from 1.0.4 to 1.0.4-rc.0
    hot-code-push            downgraded from 1.0.0 to 1.0.0-rc.0
    html-tools               downgraded from 1.0.5 to 1.0.5-rc.0
    htmljs                   downgraded from 1.0.5 to 1.0.5-rc.1
    http                     downgraded from 1.1.1 to 1.1.1-rc.1
    id-map                   downgraded from 1.0.4 to 1.0.4-rc.0
    jquery                   downgraded from 1.11.4 to 1.11.4-rc.0
    launch-screen            downgraded from 1.0.4 to 1.0.3-rc.1
    less                     removed from your project
    livedata                 downgraded from 1.0.15 to 1.0.14-rc.0
    localstorage             downgraded from 1.0.5 to 1.0.4-rc.0
    logging                  downgraded from 1.0.8 to 1.0.8-rc.1
    meteor                   downgraded from 1.1.7 to 1.1.7-rc.1
    meteor-base              downgraded from 1.0.1 to 1.0.1-rc.0
    minifiers                downgraded from 1.1.7 to 1.1.6-rc.1
    minimongo                downgraded from 1.0.9 to 1.0.9-rc.0
    mobile-experience        downgraded from 1.0.1 to 1.0.1-rc.0
    mobile-status-bar        downgraded from 1.0.6 to 1.0.5-rc.1
    mongo                    downgraded from 1.1.1 to 1.1.1-rc.3
    mongo-id                 downgraded from 1.0.1 to 1.0.1-rc.0
    mongo-livedata           downgraded from 1.0.9 to 1.0.9-rc.0
    npm-mongo                downgraded from 1.4.39_1 to 1.4.39-rc.0_1
    observe-sequence         downgraded from 1.0.7 to 1.0.7-rc.0
    ordered-dict             downgraded from 1.0.4 to 1.0.4-rc.0
    package-version-parser   downgraded from 3.0.4 to 3.0.4-rc.0
    promise                  downgraded from 0.4.8 to 0.4.8-rc.0
    random                   downgraded from 1.0.4 to 1.0.4-rc.0
    rate-limit               downgraded from 1.0.0 to 1.0.0-rc.0
    reactive-dict            downgraded from 1.1.1 to 1.1.1-rc.0
    reactive-var             downgraded from 1.0.6 to 1.0.6-rc.0
    reload                   downgraded from 1.1.4 to 1.1.4-rc.0
    respondly:css-common     added, version 1.0.1
    respondly:css-stylus     added, version 1.0.3
    respondly:ctrl           added, version 1.0.1
    respondly:util           added, version 1.0.2
    retry                    downgraded from 1.0.4 to 1.0.4-rc.0
    routepolicy              downgraded from 1.0.6 to 1.0.6-rc.0
    service-configuration    downgraded from 1.0.5 to 1.0.5-rc.0
    session                  downgraded from 1.1.1 to 1.1.1-rc.0
    sha                      downgraded from 1.0.4 to 1.0.4-rc.0
    spacebars                downgraded from 1.0.7 to 1.0.7-rc.0
    spacebars-compiler       downgraded from 1.0.7 to 1.0.7-rc.0
    srp                      downgraded from 1.0.4 to 1.0.4-rc.0
    standard-minifiers       downgraded from 1.0.0 to 1.0.0-rc.1
    templating               downgraded from 1.1.3 to 1.1.2-rc.4
    templating-tools         downgraded from 1.0.0 to 1.0.0-rc.0
    tracker                  downgraded from 1.0.8 to 1.0.8-rc.0
    ui                       downgraded from 1.0.8 to 1.0.7-rc.0
    underscore               downgraded from 1.0.4 to 1.0.4-rc.0
    url                      downgraded from 1.0.5 to 1.0.5-rc.0
    velocity:html-reporter+  downgraded from 0.9.0-rc.2 to 0.9.0-rc.1
    webapp                   downgraded from 1.2.2 to 1.2.2-rc.2
    webapp-hashing           downgraded from 1.0.5 to 1.0.4-rc.0

What should I do?

**Comment by stubailo** [comment]
Can you refer to the thread where people suggested downgrading to 1.2-rc.12? Does Meteor 1.2.0.1 work for you?

**Comment by Pierre-Thibault** [comment]
meteor --version
     Meteor 1.2.0.1

I did try:

    meteor update --release METEOR@1.2-rc.12

but it is not helping.

**Comment by Pierre-Thibault** [comment]
It seems that the problem is with xolvio:cucumber. Removing the package solve the problem but I would like to use cucumber!

**Comment by gabrielhpugliese** [comment]
I'm not using xolvio:cucumber and I have the same problem when trying to update my project from 1.0.3.2 to 1.2.0.2

**Comment by gabrielhpugliese** [comment]
By the way, any command I run ends up with the message:
```
=> Errors while initializing project:

While selecting package versions:
error: unknown package: isobuild:minifier-plugin
Required by: standard-minifiers 1.0.1
```

**Comment by abernix** [comment]
I'm going to close this issue now.  `xolvio:cucumber` has changed significantly since this was originally opened and has merged into `xolvio:chimp`.  I would recommend checking out that (new) project for your specific problems as it definitely worked with Meteor 1.2.x.  Additionally, check out the Meteor Guide has a section specifically on [using Chimp/Cucumber for Acceptance testing](http://guide.meteor.com/testing.html#acceptance-testing).
