### ISSUE TITLE
Meteor 1.2: `check`, `Tracker`, etc is no longer available on the client to packages that didn't explicitly api.use them.

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#5239]
It used to be that packages could use `check` on the client side without declaring it, since it was in `window`. This is no longer the case, possibly as a side effect of ES2015. This might cause old packages to break in Meteor 1.2 without the expected globals.

This also seems to be true for `Deps` or `Tracker`: iron-meteor/iron-layout#18.

It's possible this will also just force people to fix their packages, with much gnashing of teeth. But I imagine people will not update if packages are broken.

**Comment by glasser** [comment]
This is intended and is documented in the upgrade guide at https://quip.com/RXFlAk9Rc2xI

It is not an effect of ES2015: it is an effect of simplifying meteor-platform.

**Comment by glasser** [comment]
Though to be clear: while this is the case for new apps, it should not break apps on `meteor update` because `meteor update` should add the check package.  If it didn't for you, please show a full reproduction.

**Comment by mizzao** [comment]
@glasser I think what I'm seeing is that packages break during testing because `check` is not added for them as if they were part of an app.

That's probably less severe than the original problem I hypothesized, though.
