### ISSUE TITLE
[MOBILE] Cordova build failed after upgrade

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5241]
After upgrading to 1.2, I can't build my project anymore with Cordova:

    meteor run android-device -p 3000

FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':mergeDebugResources'.
   > Error: Failed to run command:
   /Users/dennis/Library/Android/sdk/build-tools/23.0.1/aapt s -i /Users/dennis/Desktop/Entwicklung/twyce/app/.meteor/local/cordova-build/platforms/android/res/drawable-port-hdpi/screen.png -o /Users/dennis/Desktop/Entwicklung/twyce/app/.meteor/local/cordova-build/platforms/android/build/intermediates/res/debug/drawable-port-hdpi-v4/screen.png
   Error Code:
   42
   Output:
   libpng error: Not a PNG file

//Edit: Okay, I found out, that I had ".jpg" files in my <code>mobile-config.js</code> for launch screen and icons. After removing them, I get a new error:

  /Users/dennis/Desktop/Entwicklung/twapp/app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR: Failed to launch application on device: ERROR: Failed to install apk
   to device:     pkg: /data/local/tmp/android-debug.apk
   Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1

**Comment by dnish** [comment]
Okay, it can be closed. Following steps I had to do after upgrading:

- Changing all JPG files for launch screen and icons to PNG files (fixes libpng error)
- Removing the app from my Android device & execute <code>meteor run android-device -p 3000</code> again (fixes certificates error)

**Comment by martijnwalraven** [comment]
Good to hear you got this working!

**Comment by xpluscal** [comment]
same error.

 While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/calvin/01_Projekte/0079_Jobmama/04_Meteor/jm/.meteor/local/cordova-build/platforms/android/cordova/run
   --device

   /Users/calvin/01_Projekte/0079_Jobmama/04_Meteor/jm/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR: Failed to launch application on device: ERROR: Failed to install apk to device:     pkg:
   /data/local/tmp/android-debug.apk
   Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

I did not find a fix so far...

**Comment by dnish** [comment]
@xpluscal Think it's not the same error. Do you use a real Android device for testing? <code>INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES</code> means, that you've installed another copy of the app on your device (f.e. the production version) and it is signed with another key.
