### ISSUE TITLE
1.2: Packages used by build plugins don't get implied versions properly

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#5244]
See https://github.com/mizzao/meteor-build-fetcher/blob/master/package.js, which is a very simple plugin.

When trying to publish the package, the following error is shown:

```
mizzao:build-fetcher$ meteor publish
=> Errors while publishing:                   

While publishing the package:
error: You must specify a version constraint for package isobuild:compiler-plugin
error: You must specify a version constraint for package ecmascript
error: You must specify a version constraint for package http
```

Shouldn't all these packages just get versions from `api.versionsFrom("1.2.0.1");`? Note that this includes both packages from `api.use`, and also `Package.registerBuildPlugin({use: [ ... ]})`.

**Comment by glasser** [comment]
Hmm, did this work before 1.2?

**Comment by glasser** [comment]
Looking at the code that handles versionsFrom in 1.1.0.3, it seems unlikely, though I did not test it:

```

    // If we have specified some release, then we should go through the
    // dependencies and fill in the unspecified constraints with the versions in
    // the releases (if possible).
    if (!_.isEmpty(api.releaseRecords)) {

      // Given a dependency object with keys package (the name of the package)
      // and constraint (the version constraint), if the constraint is null,
      // look in the packages field in the release record and fill in from
      // there.
      var setFromRel = function (dep) {
        if (dep.constraint) {
          return dep;
        }
        var newConstraint = [];
        _.each(api.releaseRecords, function (releaseRecord) {
          var packages = releaseRecord.packages;
          if(_.has(packages, dep.package)) {
            newConstraint.push(packages[dep.package]);
          }
        });
        if (_.isEmpty(newConstraint)) return dep;
        dep.constraint = _.reduce(newConstraint,
          function(x, y) {
            return x + " || " + y;
          });
        return dep;
      };

      // For all api.implies and api.uses, fill in the unspecified dependencies from the
      // release.
      _.each(compiler.ALL_ARCHES, function (label) {
        api.uses[label] = _.map(api.uses[label], setFromRel);
        api.implies[label] = _.map(api.implies[label], setFromRel);
      });
     };
```

This is iterating over arches and plugins are not arches.

Also, all documentation of `isobuild:*` feature packages should show examples with `@` strings.  If you see any documentation that suggests that versionsFrom works with isobuild:* feature packages and that you can write them without a version number, we can fix that.

**Comment by mizzao** [comment]
I can understand that `registerPlugin` might require versions. However, is this also true for the second line of the following?

```
  api.versionsFrom("1.2.0.1");
  api.use('isobuild:compiler-plugin');
```

I'm used to using `versionsFrom` and not specifying versions of core packages.

**Comment by mizzao** [comment]
Oh, and it did work in previous versions: https://github.com/mizzao/meteor-build-fetcher/blob/786444876c3158748af99c39d95c7cd1ad37cbd4/package.js

(no version specified for `http`).

**Comment by glasser** [comment]
`isobuild:*` is a special form. Every reference to it should tell you to include the version number. Did you find an error message or documentation telling you to write `api.use("isobuild:compiler-plugin")`?  I can fix that if you point me at it.

Not sure what's up with http working before; that is surprising, although I think it's fine to require people writing plugins (advanced users already) to be a little more explicit about their dependencies.

**Comment by mizzao** [comment]
Hey @glasser, where can I find the right version of `isobuild:compiler-plugin` to use? I can't even find it in the `.versions`.

**Comment by glasser** [comment]
https://github.com/meteor/meteor/wiki/Isobuild-Feature-Packages or the error message where you call `Plugin.registerCompiler` without using it.

**Comment by abernix** [comment]
Closing.  Thanks for opening this issue originally but you'll need to pass the version.  For what it's worth, except for `isobuild:cordova`, it will probably always be `1.0.0`, but the page listed in the previous comment will be kept up to date.
