### ISSUE TITLE
1.2: How to enable @decorators in ecmascript (Babel) package

### ISSUE THREAD

**Issue by pbastowski** [meteor/meteor#5246]
I have lots of ES2015 code in my projects that relies on Decorators, babel options `{ stage: 0 }`. However, Meteor 1.2 `ecmascript` package does not enable `{ stage: 0 }` by default and generates compile errors

    While processing files with ecmascript (for target web.browser):
    client/app/app.es6.js:30: client/app/app.es6.js: Unexpected token (30:0)

when it encounters code such as in the screen shot below from **app.es6.js**. (See the `@` at line 30 character 0)? That's a decorator.

![image](https://cloud.githubusercontent.com/assets/5649024/10034587/11be0208-6192-11e5-9114-80187da30d96.png)

The code above works with Meteor 1.1 and my existing package `pbastowski:angular-babel`, but not with Meteor 1.2 and package `ecmascript`.

Is there a setting or a configuration file, like babel.json, where I can configure my own Babel settings?

**Comment by BrianRosamilia** [comment]
The whitelist is hardcoded to the features MDG included in the release notes, it would seem.

You can whitelist it yourself here https://github.com/meteor/meteor/blob/devel/packages/ecmascript/ecmascript.js and see what happens

Push 'es7.decorators' into babelOptions.whitelist

I'm pretty shocked they didn't find a way to be permissive with es7 features, at least in the client.

Related :  even if you hack in async/await by changing the ecmascript package to whitelist it, it uses a custom compiler plugin that doesn't work properly right now.

**Comment by Sanjo** [comment]
You need to copy the ecmascript and babel-compiler packages to your app packages folder and add the option here:

* https://github.com/meteor/meteor/blob/release/METEOR%401.2.0.1/packages/ecmascript/ecmascript.js#L6
* https://github.com/meteor/meteor/blob/release/METEOR%401.2.0.1/packages/babel-compiler/babel-compiler.js#L51

I'm not sure if the `stage: 0` option works. `babelOptions.whitelist.push('<FEATURE_NAME>'` definitely works.

**Comment by pbastowski** [comment]
@BrianRosamilia, @Sanjo  Thanks guys. I saw that code yesterday also, but thought that perhaps "they" provided some way to set custom options. Alas, it would appear they didn't.

Ok, I found that it is babel-compiler.js, which needs to be modified. So, I pushed 'es7.decorators' and later 'es7.classProperties' to the whitelist, which fixes the Babel errors.

Then, I got the browser complaining about
````
Uncaught SyntaxError: Unexpected reserved word
````
when it tries to execute this
````javascript
import { SetModule, Component, State, View, Inject, bootstrap, Filter } from 'angular2now';
````

So, now `es6.modules` also needed to be added to support the transpilation of `import` and `from`.

The app starts now, but Chrome produces errors
    Uncaught TypeError: babelHelpers.interopRequireDefault is not a function

when it hits this code
````javascript
import defectModel from 'defectModel';
````

So, they broke Babel. 

I'll keep looking for a solution.

Thanks again for your help.

I thought it 
Any idea what

**Comment by BrianRosamilia** [comment]
I also don't think it provides much of an upgrade path as time goes on and features move to stable stages.  I can see why they disabled Async/await on the server but this is a regression from grigio:meteor-babel for me (and angular 2 users, it would seem).

Ideally, there would be a way to express your whitelist for both client and server, with things that actually aren't ready like async await on the server throwing exceptions when meteor builds.

Thoughts?

**Comment by pbastowski** [comment]
Yeah, I'm thinking pull-request with support for custom settings in babel.json in project root folder. Something like below in babel.js at the top:

````javascript
var meteorBabel = Npm.require('meteor-babel');
var fs = Npm.require('fs');
var path = Npm.require('path');

var appdir = process.env.PWD || process.cwd();
var babelOptionsFilePath = path.join(appdir, 'babel.json');
var babelUserConfig = {};

if (fs.existsSync(babelOptionsFilePath)) {
    babelUserConfig = JSON.parse(fs.readFileSync(babelOptionsFilePath, {encoding: 'utf8'}));
}
````

and then function getDefaultOptions becomes:

````javascript
function getDefaultOptions(extraFeatures) {
  validateExtraFeatures(extraFeatures);

  // See https://github.com/meteor/babel/blob/master/options.js for more
  // information about what the default options are.
  var options = meteorBabel.getDefaultOptions(extraFeatures);

  babelUserConfig.whitelist.forEach(function(opt) {
      if (options.whitelist.indexOf(opt) === -1)
        options.whitelist.push(opt);
  });

  // The sourceMap option should probably be removed from the default
  // options returned by meteorBabel.getDefaultOptions.
  delete options.sourceMap;

  return options;
}
````

Just a first cut.... and I took the read `babel.json` code from `grigio:babel`.

**Comment by pbastowski** [comment]
And here is the PR https://github.com/meteor/meteor/pull/5260

**Comment by pbastowski** [comment]
Could some of you good people help me verify my findings, below:

- As I mentioned in my PR (https://github.com/meteor/meteor/pull/5260), `.babelrc` allows us to whitelist extra Babel transformers
- Some transformers require specific helper functions to be added to the `babelHelpers` object
- I just discovered that the `babelHelpers` object is visible on `window`, so, we can add to it whatever functions we wish and desire.

So, create a file `client/lib/babel-helpers.js` in your project and add the following to it:
````javascript
// Provides support for es7.decorators
window.babelHelpers.defineDecoratedPropertyDescriptor = function (target, key, descriptors) {
    var _descriptor = descriptors[key];
    if (!_descriptor) return;
    var descriptor = {};

    for (var _key in _descriptor) descriptor[_key] = _descriptor[_key];

    descriptor.value = descriptor.initializer ? descriptor.initializer.call(target) : undefined;
    Object.defineProperty(target, key, descriptor);
};

// Provides support for es7.decorators
window.babelHelpers.createDecoratedClass = (function () {
    function defineProperties(target, descriptors, initializers) {
        for (var i = 0; i < descriptors.length; i++) {
            var descriptor = descriptors[i];
            var decorators = descriptor.decorators;
            var key = descriptor.key;
            delete descriptor.key;
            delete descriptor.decorators;
            descriptor.enumerable = descriptor.enumerable || false;
            descriptor.configurable = true;
            if ('value' in descriptor || descriptor.initializer) descriptor.writable = true;
            if (decorators) {
                for (var f = 0; f < decorators.length; f++) {
                    var decorator = decorators[f];
                    if (typeof decorator === 'function') { descriptor = decorator(target, key, descriptor) || descriptor; } else { throw new TypeError('The decorator for method ' + descriptor.key + ' is of the invalid type ' + typeof decorator); }
                }
                if (descriptor.initializer !== undefined) {
                    initializers[key] = descriptor;
                    continue;
                }
            }
            Object.defineProperty(target, key, descriptor);
        }
    }

    return function (Constructor, protoProps, staticProps, protoInitializers, staticInitializers) {
        if (protoProps) defineProperties(Constructor.prototype, protoProps, protoInitializers);
        if (staticProps) defineProperties(Constructor, staticProps, staticInitializers);
        return Constructor;
    };
})();

window.babelHelpers.interopRequireDefault = function (obj) {
    return obj && obj.__esModule ? obj : {
        "default": obj
    };
};
````

Now, create the file `.babelrc` in the root of your project and add the following to it:
```javascript
{
    "whitelist": [
        "es7.decorators",
        "es7.classProperties",
        "es7.exportExtensions",
        "es7.comprehensions",
        "es6.modules"
    ]
}
```

At this point, Meteor 1.2 with the `ecmascript` package and the above additions should be able to build your application without producing Babel compile errors. It will correctly transpile all your ES6 code, including any ES7 decorators and `import .... from` statements into ES5 code, as expected and previously accomplished with `grigio:babel` and/or my very own `pbastowski:angular-babel` packages.

Could someone please let me know if the above worked for them?

If it does then I will close my PR as it is no longer required, based on my findings.

Thanks.

**Comment by Sanjo** [comment]
@pbastowski Thanks for finding out this solution. This is much better than forking the packages.

**Comment by pbastowski** [comment]
@Sanjo You are welcome :) I agree.

**Comment by rclai** [comment]
@pbastowski is the above code that you wrote above something that can be put in a package?

**Comment by pbastowski** [comment]
Possibly. I will try it and see.

**Comment by pbastowski** [comment]
@rclai I have created this github repo: https://github.com/pbastowski/ecmascript-extras

It is an experiment, so, it may not work properly, although it seems to work for me. However, I am not entirely happy with how it is implemented. Feel free to make comments or submit a PR.

If you'd like to try it then clone it into your packages folder and then 

    meteor add pbastowski:ecmascript-extras

... and let me know if it works for you.

Paul

**Comment by rclai** [comment]
Cool, I'll try it out.

**Comment by benjamn** [comment]
Enabling decorators is probably straightforward and safe, depending on your risk tolerance, but things like modules will be more difficult, because Meteor is not based on a CommonJS `require`/`exports` module system, and Babel compiles `import` and `export` to `require` and `exports`. ES2015 modules are a good example of a feature you can't just turn on in a `.babelrc` file and expect them to work properly. Support for modules is planned for Meteor 1.3, but it's a good deal more complicated than just enabling a feature in Babel.

Though we don't want people to think they can just turn on arbitrary Babel features, you are more than welcome to fork the `ecmascript` and/or `babel-compiler` packages in order to tweak the set of available features. You'll be in uncharted territory, but it might work just fine.

For each feature that isn't supported in Meteor yet, there's a reason we chose not to enable it. In the case of modules, it's because you need `require` and `exports` for the Babel output to work at all. In the case of decorators, we're mostly just waiting for the proposal to advance beyond stage 1, since it's entirely possible that the syntax or semantics of decorators could still change. If you're willing to take that risk, more power to you, but I'm hope you can understand why the official `ecmascript` should not be inviting people to write code that could easily stop working in the future.
