### ISSUE TITLE
Add links to issues fixed in history.md

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#5247]
Now you only provide issue # which is inconvenient at best.

**Comment by stubailo** [comment]
I was going to respond saying it would be too much work and not worth it, but it turned out to be a simple regex. Here's the commit that fixes it: https://github.com/meteor/meteor/commit/f97efe4c351e26d4cb5bcfea5eb0642090db52c9

**Comment by avalanche1** [comment]
:+1: 
So how exactly did you do it?

**Comment by stubailo** [comment]
In Atom, I did a find/replace for: ` (#(\d+))` -> ` [$1](https://github.com/meteor/meteor/issues/$2)`
