### ISSUE TITLE
Google refresh token changes when user logs in.

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#5248]
Calling `Meteor.loginWithGoogle` to log in seems to change `services.google.refreshToken`. But Google only keeps the last 25 refresh tokens and (silently) revokes older ones which can lead to unexpected 401s.

Here's the `loginWithGoogle` call I'm using:
```
Meteor.loginWithGoogle({
  requestOfflineToken: true,
  loginStyle: 'popup',
  forceApprovalPrompt: true,
  requestPermissions: [
    'email',
    'https://www.googleapis.com/auth/plus.login',
    'https://www.googleapis.com/auth/calendar',
    'https://www.google.com/m8/feeds/']
}, callback);
```

**Comment by avital** [comment]
What would be more desirable behavior?

**Comment by avital** [comment]
(The option `requestOfflineToken` explicitly means: "request offline token")

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about improving this situation.  Would be happy to reopen it if you come up with some additional details for building out this feature.
