### ISSUE TITLE
crucial error in simple-todos-angular

### ISSUE THREAD

**Issue by sclausen** [meteor/meteor#5250]
adding ng-include to the body leads to a source simple-todos-angular.compiled.html.js which obviously is wrong:
```javascript
Meteor.startup(function() {
  document.body.setAttribute('ng-include', ''todos-list.ng.html'');
  document.body.setAttribute('ng-controller', 'TodosListCtrl');
});
```
I don't know where this code is generated, therefor I can only provide a hack around this problem:
change the attribute directive ng-include to an element directive.
``` html
<body ng-controller="TodosListCtrl">
  <ng-include src="'todos-list.ng.html'"></ng-include>
</body>
```

**Comment by sclausen** [comment]
Okay, even after this, my whole todos-app doesn't really work without an error.
![simple-todos-angular](https://cloud.githubusercontent.com/assets/916076/10038987/0cd45a62-61ce-11e5-96ac-8dda8de60cf8.png)

**Comment by gjr-qm** [comment]
I think this is the same bug as #5232 (single quote in body tag attribute value).

You could try escaping the quotes by putting a backslash in front of them:
`<body ng-include="\'todos-list.ng.html\'">`

**Comment by sclausen** [comment]
Yeah, this would be another good hack to fix the error. And afterall, the example app is still not useable. There must be somthing wrong on a more basic level for the quotation thing and the blank white page without errors, but as I said, I can't find the source code responsible for this… :(

**Comment by yyx990803** [comment]
Thanks for reporting the issue - @stubailo has pushed a fix, it will be out in the next patch release (soon!)

**Comment by jkalbfeld** [comment]
\m/  I thought I was a complete moron until I read this thread.  Just wrote some kickass stuff in the earlier version of Meteor, stole the code for a new app I scaffolded today and it was completely borked.

**Comment by stubailo** [comment]
#5232 is a duplicate, going to track there.
