### ISSUE TITLE
Provider/server side auth (Провайдерная часть авторизации с помощью сторонних сервисов)

### ISSUE THREAD

**Issue by Lesp1ker** [meteor/meteor#5256]
Hi all, need to realize provider part of authorization by means of third-party services, nobody found an initial code of provayderny part of authorization of meteor\vk\github\facebook e.t.c. (for an example)? (sorry for bad english)
Всем привет, требуется написать провайдерную часть авторизации с помощью сторонних сервисов, никто не находил исходный код провайдерной части авторизации meteor\vk\github\facebook и.т.д.(для примера)?

**Comment by jmlv** [comment]
Like this? https://github.com/mike1pol/meteor-accounts-mailru

**Comment by yyx990803** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

You can also check out the [Accounts API documentation](http://docs.meteor.com/#/full/accounts_api).

**Comment by Lesp1ker** [comment]
jmlv, these are the parties of the appendix, I need aside provider
