### ISSUE TITLE
isobuild - Control watched files - hot reload without page refresh

### ISSUE THREAD

**Issue by eXon** [meteor/meteor#5257]
I would like to develop a Webpack package with hot reload inside meteor. It would make the hot reload with React seriously 10x faster than what it is right now because it doesn't refresh the page and doesn't need meteor to do anything. 

However, it is impossible because as soon as my compiler use the jsx extension, modifying a file will make Meteor recompile.

Right now, the way I do it is by having my code outside of Meteor, having Webpack build it and drop it inside Meteor. While developing, it bypass Meteor and drop it in the browser directly.

AFAIK there is no way to do this right now. I think the plugins should be able to control this better. Isobuild is pretty complex, anyone know how this could be achieved?

**Comment by stubailo** [comment]
@eXon you can prevent page reloads with the API provided by the `reload` package. There's some sparse documentation here: https://github.com/meteor/meteor/blob/e3234ea99f04c304686cec545c4886e101f0ae64/packages/reload/reload.js#L102

Here's an example of a package that prevents reloads under certain conditions: https://github.com/meteor/mobile-packages/blob/master/packages/mdg:reload-on-resume/reload-on-resume.js

If there are some more specific features you need, please update the issue and comment - right now, this isn't really an actionable feature request or bug report. But to start, try out the approach above.

**Comment by eXon** [comment]
Awesome, thank you!

**Comment by eXon** [comment]
@stubailo It's working really great. However, one thing I can't get my head around. How do you know inside a compiler plugin if it is in development or production mode? (like the minifier). 

I can't use debugOnly or NODE_ENV. For my plugin, it is absolutely crucial. How can I know?
