### ISSUE TITLE
ReferenceError: check is not defined - Meteor 1.2.0.1 with latest angular package

### ISSUE THREAD

**Issue by morganpage** [meteor/meteor#5258]
Getting 'ReferenceError: check is not defined' when invoking the 'remove' method of the AngularMeteorCollection.

at Array.angularMeteorCollection.factory.AngularMeteorCollection.remove

The line in angular.js is:
check(keys, [Match.OneOf(String, Mongo.ObjectID)]);

The line of code causing the error is:

$scope.parties.remove(party);

From the tutorial:
http://angular-meteor.com/tutorials/angular1/bind-one-object

**Comment by charithperera** [comment]
Also having this exact same problem since upgrading to 1.2

**Comment by roaringskysoftware** [comment]
Same again. Since upgrade to 1.2.
```

I20150925-12:03:46.651(-7)? Exception while invoking method 'shiftRemove' ReferenceError: check is not defined
I20150925-12:03:46.652(-7)?     at [object Object].Meteor.methods.shiftRemove (lib/collections/shifts.js:15:9)
I20150925-12:03:46.652(-7)?     at packages/check/packages/check.js:117:1
I20150925-12:03:46.652(-7)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20150925-12:03:46.653(-7)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/packages/check.js:116:1)
I20150925-12:03:46.653(-7)?     at maybeAuditArgumentChecks (livedata_server.js:1689:18)
I20150925-12:03:46.653(-7)?     at livedata_server.js:708:19
I20150925-12:03:46.653(-7)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20150925-12:03:46.653(-7)?     at livedata_server.js:706:40
I20150925-12:03:46.653(-7)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20150925-12:03:46.653(-7)?     at livedata_server.js:704:46
```

**Comment by phoue** [comment]
Same problem since upgrading to 1.2, but fixed it by meteor add check .

**Comment by morganpage** [comment]
Fixed by:

meteor add check
meteor add ejson

Thanks to 'phoue' for fix.

**Comment by Urigo** [comment]
Fixed in the new `angular@1.0.0-rc.11` version

**Comment by avital** [comment]
Happy to see that this was resolved!

**Comment by siddhsuper** [comment]
Thanks this was not mentioned in the meteor book. [meteor add check
meteor add ejson]

**Comment by avital** [comment]
I'm curious @siddhsuper -- which book?

**Comment by borantula** [comment]
thanks @morganpage . 
I think Discover Meteor @avital . I also came here via "the book", discover meteor after the example failed

**Comment by phrazzld** [comment]
Just came from the book, thanks @morganpage for reporting it and @phoue for the solve!

**Comment by ulongx** [comment]
thanks @morganpage .@phoue

**Comment by quangv** [comment]
thanks @phoue & @morganpage ! :)

**Comment by divyeshdhokiya** [comment]
Thanks @phoue & @morganpage.

**Comment by h2jose** [comment]
thanks @morganpage , i am reading and writing code from "Discover Meteor" book, this detail is not mentioned in capitule 7.
Adds there and fixed.

**Comment by dwanderton** [comment]
Thanks all :)

**Comment by gregorwilson** [comment]
+1 thanks!

**Comment by bdains** [comment]
Thanks a ton for this it fixed my issues:
```
meteor add check
meteor add ejson
```
