### ISSUE TITLE
meteor crash after adding accounts-password package

### ISSUE THREAD

**Issue by attdona** [meteor/meteor#5259]
OS: ubuntu 14.04

$ meteor create fuzzy
$ cd fuzzy
$ meteor add accounts-password
                                              
Changes to your project's package version selections:
                                              
accounts-base          added, version 1.2.1   
accounts-password      added, version 1.1.3
ddp-rate-limiter       added, version 1.0.0
email                  added, version 1.0.7
localstorage           added, version 1.0.5
npm-bcrypt             added, version 0.7.8_2
rate-limit             added, version 1.0.0
service-configuration  added, version 1.0.5
sha                    added, version 1.0.4
srp                    added, version 1.0.4

                                              
accounts-password: Password support for accounts

$ meteor
[[[[[ ~/meteor/fuzzy ]]]]]                    

=> Started proxy.                             
W20150923-16:35:38.811(2)? (STDERR)           
W20150923-16:35:38.812(2)? (STDERR) /home/attilio/.meteor/packages/meteor-tool/.1.1.8.1uiokq7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150923-16:35:38.813(2)? (STDERR) 						throw(ex);
W20150923-16:35:38.813(2)? (STDERR) 						      ^
W20150923-16:35:38.813(2)? (STDERR) Error: failed to connect to [localhost:3001]
W20150923-16:35:38.813(2)? (STDERR)     at Object.Future.wait (/home/attilio/.meteor/packages/meteor-tool/.1.1.8.1uiokq7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150923-16:35:38.813(2)? (STDERR)     at new MongoConnection (packages/mongo/packages/mongo.js:221:1)
W20150923-16:35:38.813(2)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/packages/mongo.js:3353:1)
W20150923-16:35:38.813(2)? (STDERR)     at Object.<anonymous> (packages/mongo/packages/mongo.js:3387:1)
W20150923-16:35:38.814(2)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
W20150923-16:35:38.814(2)? (STDERR)     at new Mongo.Collection (packages/mongo/packages/mongo.js:3504:1)
W20150923-16:35:38.814(2)? (STDERR)     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
W20150923-16:35:38.814(2)? (STDERR)     at new AccountsServer (accounts_server.js:16:5)
W20150923-16:35:38.814(2)? (STDERR)     at Package (globals_server.js:5:12)
W20150923-16:35:38.814(2)? (STDERR)     at /home/attilio/meteor/fuzzy/.meteor/local/build/programs/server/packages/accounts-base.js:1813:4
W20150923-16:35:38.814(2)? (STDERR)     - - - - -
W20150923-16:35:38.815(2)? (STDERR)     at [object Object].<anonymous> (/home/attilio/.meteor/packages/npm-mongo/.1.4.39_1.1zkkoy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
W20150923-16:35:38.815(2)? (STDERR)     at [object Object].emit (events.js:106:17)
W20150923-16:35:38.815(2)? (STDERR)     at [object Object].<anonymous> (/home/attilio/.meteor/packages/npm-mongo/.1.4.39_1.1zkkoy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
W20150923-16:35:38.815(2)? (STDERR)     at [object Object].emit (events.js:98:17)
W20150923-16:35:38.815(2)? (STDERR)     at Socket.<anonymous> (/home/attilio/.meteor/packages/npm-mongo/.1.4.39_1.1zkkoy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
W20150923-16:35:38.815(2)? (STDERR)     at Socket.emit (events.js:95:17)
W20150923-16:35:38.815(2)? (STDERR)     at net.js:441:14
W20150923-16:35:38.816(2)? (STDERR)     at process._tickCallback (node.js:448:13)
=> Exited with code: 8
W20150923-16:35:44.071(2)? (STDERR)           
W20150923-16:35:44.072(2)? (STDERR) /home/attilio/.meteor/packages/meteor-tool/.1.1.8.1uiokq7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150923-16:35:44.072(2)? (STDERR) 						throw(ex);
W20150923-16:35:44.073(2)? (STDERR) 						      ^
=> Exited with code: 8

**Comment by cddin** [comment]
I have problem with accounts-password too. I cannot deploy app to meteor.com if I add this package.

**Comment by xcv58** [comment]
Similar problem here.
I just create a demo app and add `accounts-password` package.
```bash
meteor create temp
cd temp
meteor add accounts-password
meteor
``` 

Error message:
```
W20151008-12:11:16.954(-4)? (STDERR) /Users/xcv58/.meteor/packages/meteor-tool/.1.1.9.qm1xza++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151008-12:11:16.954(-4)? (STDERR) 						throw(ex);
W20151008-12:11:16.954(-4)? (STDERR) 						      ^
W20151008-12:11:16.954(-4)? (STDERR) Error: Can't find npm module 'bcrypt'. Did you forget to call 'Npm.depends' in package.js within the 'npm-bcrypt' package?
W20151008-12:11:16.954(-4)? (STDERR)     at Object.Npm.require (/Users/xcv58/temp/.meteor/local/build/programs/server/boot.js:175:17)
W20151008-12:11:16.954(-4)? (STDERR)     at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:9:1)
W20151008-12:11:16.954(-4)? (STDERR)     at Package (packages/npm-bcrypt/packages/npm-bcrypt.js:13:1)
W20151008-12:11:16.954(-4)? (STDERR)     at /Users/xcv58/temp/.meteor/local/build/programs/server/packages/npm-bcrypt.js:33:4
W20151008-12:11:16.955(-4)? (STDERR)     at /Users/xcv58/temp/.meteor/local/build/programs/server/packages/npm-bcrypt.js:42:3
W20151008-12:11:16.955(-4)? (STDERR)     at /Users/xcv58/temp/.meteor/local/build/programs/server/boot.js:242:10
W20151008-12:11:16.955(-4)? (STDERR)     at Array.forEach (native)
W20151008-12:11:16.955(-4)? (STDERR)     at Function._.each._.forEach (/Users/xcv58/.meteor/packages/meteor-tool/.1.1.9.qm1xza++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151008-12:11:16.955(-4)? (STDERR)     at /Users/xcv58/temp/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by xcv58** [comment]
By the way, it doesn't work on Mac OS 10.11
But works on Ubuntu 14.04

**Comment by xcv58** [comment]
I fix it by remove `~/.meteor`

**Comment by attdona** [comment]
I removed ~/.meteor but for me (ubuntu 14.04) doesn't work.

**Comment by attdona** [comment]
I get it working. It is not definitely a bug but my wrong env setting (MONGO_URL env var was set with a wrong value)

**Comment by timbotnik** [comment]
Sounds like you've figured it out!  Thanks.
