### ISSUE TITLE
Simple-todos-angular broken in meteor 1.2.0.1

### ISSUE THREAD

**Issue by daguangli** [meteor/meteor#5262]
My angular app was broken after upgrading meteor to 1.2.0.1. I thought there might be some setup issue in my environment, so I went ahead and installed the example app, I got the exact same error.
Symptom: blank home page.
Error in the developer tool: Missing )
Repro steps:
meteor create --example simple-todos-angular

**Comment by rgoomar** [comment]
I just ran it and found the same issue. Looking into it

**Comment by gjr-qm** [comment]
Duplicate of #5250. Solution (at least for the example app) provided there.

**Comment by stubailo** [comment]
OK going to close this as a duplicate.
