### ISSUE TITLE
Form sends GET request when using meteor deploy, but works fine of local computer

### ISSUE THREAD

**Issue by fayadh** [meteor/meteor#5264]
My application was working fine. I updated Meteor to 1.2, and when I deploy, all forms send GET requests instead of preventing default behaviour and inserting/update using mongo. 
Anyone facing similar issues?

**Comment by fayadh** [comment]
Problem resolved. Updating seems to have broken a dependency.

**Comment by stubailo** [comment]
Do you know which one? Glad you solved the issue, but would be good to know the cause.

**Comment by fayadh** [comment]
I must correct myself. It wasn't dependency problem. One of my templates
had a naming error ( 'Template.contact_us.events' instead of
'Template.ContactUs.events' ), and for some reason, even though the site
would load, the error would prevent all the forms from submitting properly.
This happened regardless of the fact that it worked perfectly well on my
local computer. Once corrected, everything went back to normal.

**Comment by stubailo** [comment]
Great. Weird that it worked in one place and not in the other!

**Comment by fayadh** [comment]
My feeling exactly :)
