### ISSUE TITLE
[Crosswalk] Disable gpu-rasterization

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5267]
When adding the <code>meteor add crosswalk</code> package, my whole app is full of pixel errors while changing the routes. I'm using Android 4.4. The issue is reported here:

https://crosswalk-project.org/jira/browse/XWALK-3123

How can we disable the GPU rasterization with the Meteor Cordova package?

**Comment by martijnwalraven** [comment]
The [Crosswalk Cordova plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) that our package wraps allows you to configure [Chromium command line options](http://peter.sh/experiments/chromium-command-line-switches/) with a preference setting. With Meteor, you can test this by adding the following line to `mobile-config.js`: `App.setPreference('xwalkCommandLine', '--show-fps-counter');`. This should show an FPS counter in the web view so you can easily see whether passing these options is working.

The option you're interested in seems to be `--disable-gpu-rasterization`. 

I noticed a new version of the plugin is available, so I upgraded it to 1.3.0, which uses Crosswalk 14 by default. This should come out in the next Meteor 1.2 point release. It is worth testing whether that happens to solve your problems even without disabling GPU rasterization.

**Comment by pmwisdom** [comment]
@martijnwalraven There is version 1.3.1 for Crosswalk that is out now on NPM that solves a really nasty native keyboard glitch on android that causes the screen to flicker up and down every time you open it. Might want to look into that version instead.

**Comment by martijnwalraven** [comment]
Ah, good to know. I updated the plugin to 1.3.1. Will be in Meteor 1.2.0.2.

**Comment by stubailo** [comment]
Meteor 1.2.0.2 is out!
