### ISSUE TITLE
Meteor rebuilds after change in /public/

### ISSUE THREAD

**Issue by reel** [meteor/meteor#5268]
Meteor rebuild after adding/renaming files in /public/

Reproduction: start meteor, add a file to your root /public directory, watch it spin.

I am using Meteor 1.2.0.1 on Windows 10 64bits

**Comment by Slava** [comment]
https://github.com/meteor/meteor/issues/1129 is highly relevant and even could be used to close this ticket as a duplicate.

**Comment by raquelhosein** [comment]
hey all if this issue is take care of please consider closing it!
