### ISSUE TITLE
Improve `meteor update` output when at latest compatible version

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5270]
**_5 Upvotes**_ 

```
$ meteor update
...
The following top-level dependencies were not updated to the very latest version available:
 * stevezhu:fbgraph 1.2.0 (2.0.0 is available)
...
To update one or more of these packages, pass their names to `meteor update`. 
$ meteor update stevezhu:fbgraph
The specified packages are at their latest compatible versions.
```

In this case, I don't think I have any other packages that depend on fbgraph < 2. I think it's just saying "latest compatible" because it's a major version number change. But in general, it would be helpful if both `meteor update` and `meteor update X` tell me:
1. X is latest compatible because of Y pkg (related: #4610) OR because different major version
2. In latter case, how can I update to new version

**Comment by stubailo** [comment]
@dgreensp could you help me link to the correct part of the code someone would need to improve to make this possible?

**Comment by dgreensp** [comment]
It's the `meteor update` command code: https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L1545

The `meteor update` command could definitely use some UX improvements.  Anywhere Meteor says something is at the "latest compatible version" it basically just means it isn't necessarily at the latest version!  Not a helpful message.

**Comment by DmitryEfimenko** [comment]
+1

**Comment by nooitaf** [comment]
+1

**Comment by john-osullivan** [comment]
+1 -- the best would be if the command actually said which other package is causing the incompatibility!  Trying to figure out why I can't update a certain package right now, and digging through all my others to check their dependencies is pretty painful.

**Comment by JWo1F** [comment]
+1

**Comment by nikunjchapadia** [comment]
+1

**Comment by KoenLav** [comment]
+1

jemoeder

**Comment by Deelux** [comment]
+1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Improve%20%60meteor%20update%60%20output%20when%20at%20latest%20compatible%20version&body=Migrated%20from:%20meteor/meteor%235270) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
