### ISSUE TITLE
How do I set meteor package for example  accounts-ui to internationalization (Chinese) ?

### ISSUE THREAD

**Issue by YYwork** [meteor/meteor#5272]

**Comment by YYwork** [comment]
update

**Comment by yyx990803** [comment]
The `accounts-ui` package does not come with internationalization mechanisms. However, this stackoverflow answer might be helpful: http://stackoverflow.com/questions/14546972/meteor-accounts-ui-localization

Also, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by YYwork** [comment]
@yyx990803 tks～
