### ISSUE TITLE
Meteor 1.2.0.1 - Email.send fails at an arbitrary message size

### ISSUE THREAD

**Issue by blackslate** [meteor/meteor#5273]
## Steps to reproduce
1. $ git clone https://github.com/blackslate/Email.send-silentFailure.git
2. Inside email.js, look for `// CHANGE THIS`. Use your own email address.
3. Look for `// CHANGE THE MAIL_URL`. Use your own SMTP data
4. $ meteor
## Result

In the Terminal window, you should see something like:

```
=> App running at: http://localhost:3000/
=> Meteor server restarted                    
I20150923-14:46:04.576(-4)? string 1386
```

No error is shown. 
Check your email. Did you receive the message? In my case, no message is delivered.
## Double-check
1. Open the file at `public/message.html`
2. Remove one character (any character)
3. Meteor should detect a change to the file system and refresh:
   
    => Client modified -- refreshing
    I20150923-14:46:32.515(-4)? string 1385
4. Check your email again. This time the message should have arrived.
# Notes

You can use either `text` or `html` in the `Email.send` object, to get the same effect.
Different texts break at different places. I have been able to send certain messages as big as 1800 characters.
Changing a single character can make the text break. I had one text which broke if I included a "!" character, but which worked if that character was replaced by "?"
I have not used meteor-email with versions of Meteor prior to 1.2.0.1, so I have no way of checking if this is an issue that has been injected by the upgrade.
There is always the possibility that the error is occurring on my email server, either for outgoing messages or for incoming ones, or that messages are being blocked by a spam filter.
## Expected

Any amount of text (within reason) should be sent successfully.
## Here's how I created the demo:
1. $ meteor create emailTest
2. $ cd emailTest
3. $ meteor add check
4. $meteor add email
5. At the root of the emailTest folder, delete the default files and add those that I have created.

**Comment by justinsb** [comment]
Can I suggest trying this after deploying with `meteor deploy`?  We automatically create and configure a mailgun account for apps deployed that way, so this would rule out the email server being the problem, although a spam filter could also still be a problem.

**Comment by hwillson** [comment]
I haven't been able to reproduce this with Meteor 1.5.1, so closing for now. I'm happy to re-open this issue if anyone is still seeing this happen. Thanks!
