### ISSUE TITLE
New way of adding attributes to body tag doesn't escape quotes etc

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5276]
```
Meteor.startup(function() {
  document.body.setAttribute('simple-todos', 'surfy');
  document.body.setAttribute('ng-include', ''todos-list.ng.html'');
  document.body.setAttribute('ng-controller', 'TodosListCtrl');
});
```

This code doesn't work if you pass something with single quotes. I need to escape the attribute values.

**Comment by YC00** [comment]
change the line:5 from ng-include="'todos-list.ng.html'" to ng-include='"todos-list.ng.html"'(single quote then double quote) in file simple-todos-angular.html will solve the problem
![screenshot 1](https://cloud.githubusercontent.com/assets/9416261/10079808/bf834154-631e-11e5-98ab-801e2be10496.png)

**Comment by stubailo** [comment]
Yes, but in reality either way of doing quotes should work, so this is actually a bug that should be fixed.

**Comment by stubailo** [comment]
Duplicate of https://github.com/meteor/meteor/issues/5232
