### ISSUE TITLE
ES2015 APIs are not available when including ecmascript package

### ISSUE THREAD

**Issue by Sanjo** [meteor/meteor#5277]
As a developer I expect that I can use all ES2015 APIs when I add the ecmascript package. As an example the [String.endsWith API](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) has been introduced with ES2015. It is not usable in a Meteor app out of the box ([Reproduce](https://github.com/Sanjo/meteor-string-ends-with-reproduce)).

I suggest that Meteor provides an easy way to use core.js that polyfills all those APIs in an app. grigio:babel did this with [this file](https://github.com/grigio/meteor-babel/blob/master/lib/core-js-no-number.js).

**Comment by dgreensp** [comment]
@benjamn What do you think?

**Comment by Sanjo** [comment]
I have just released a package for this. Feel free to move it into Meteor core. https://atmospherejs.com/xolvio/core-js

**Comment by benjamn** [comment]
@Sanjo cool! Is that code publicly available on GitHub somewhere?

**Comment by benjamn** [comment]
I'm leaving this open in case there are other polyfills that you need, but I've added most of what was missing to the `ecmascript-runtime` (formerly known as `ecmascript-collections`) package: https://github.com/meteor/meteor/commit/d3878f08bca5ed630a19751c3db0c1526c64adc3

**Comment by Sanjo** [comment]
Oops, I accidentally created a private repository for the package. It is now public: https://github.com/xolvio/meteor-core-js. In the README are the instructions for how I have created the build.

**Comment by lucendio** [comment]
wouldn't it make more sense to use babels plugin API for al the missing parts, since babel is the underlying core which drives the ES6 support in meteor (as mentioned in #5295)? Or am I missing something here?

**Comment by Sanjo** [comment]
@lucendio Transpiling ES2015 syntax features to ES5 and providing core API polyfills for functions that do not exist yet in the browser/node.js are two different things. If you would transpile all the core API calls into inlined code of the code API implementation, you would get a lot of duplicated code.

**Comment by stubailo** [comment]
Can you guys try running Meteor 1.2.1-rc.4 and let me know if this is fixed? We now include more polyfills for this kind of stuff.

#5478 has more details.

**Comment by stubailo** [comment]
Meteor 1.2.1 is out, and this should now work.
