### ISSUE TITLE
Meteor build hangs forever on windows due to locked files

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#5278]
In windows files are sometimes locked when meteor tries to remove them during builds.

This used to crash meteor, but is fixed since: https://github.com/meteor/meteor/issues/4933

However, it has been solved by attempting a retry if the file is locked, but this can sometimes hang the process for a VERY long time.
E.g. I got this file that is locked, and apparently never unlocks, which meteor tries to remove.
`Z:\\programdata\\github\\meteor-scss-test\\.meteor\\local\\isopacks\\fourseven_scss-garbage-1tkxi9r\\plugin.compileScssBatch.os.windows.x86_32\\npm\\compileScssBatch\\node_modules\\node-sass\\vendor\\win32-ia32-11\\binding.node"`

The problem is, that with a filepath this long (and with NPM, paths can get very long), the amount of retries grows exponentially. From a quick look at rimraf, this would be: `600 x 3^n` milliseconds, n being the depth of the path, or ~4000 seconds for a locked file that is 8 directories deep.

**Comment by stubailo** [comment]
> with a filepath this long (and with NPM, paths can get very long), the amount of retries grows exponentially. From a quick look at rimraf, this would be: 600 x 3^n milliseconds, n being the depth of the path, or ~4000 seconds for a locked file that is 8 directories deep.

Can you help me understand why it is exponential like that? This is something we should fix, maybe via a  pull request to rimraf.

**Comment by sebakerckhof** [comment]
Well, rimraf will try up to 3 times to delete a file or folder. It uses some kind of linear backoff strategy to decide when to try again, where with each try it grows by 100 ms. So you've got 100+200+300 = 600ms until it gives up on the file.

However, from what I remember rimraf probably does some kind of recursion where errors propagate down. So if you have a filepath like `/root/sub/file` and `file` is locked, then it will try to delete `file` 3^3 times in this case. It will walk through the files like this:
```
root/sub/file : locked, 1st try
root/sub/file : locked, 2nd try
root/sub/file : locked, 3rd try
root/sub : locked, 1st try
root/sub/file : locked, 1st try
root/sub/file : locked, 2nd try
root/sub/file : locked, 3rd try
root/sub : locked, 2nd try
root/sub/file : locked, 1st try
root/sub/file : locked, 2nd try
root/sub/file : locked, 3rd try
root/sub : locked, 3nd try
root/sub/file : locked, 1st try
root/sub/file : locked, 2nd try
root/sub/file : locked, 3rd try
root : locked, 1st try
root/sub/file : locked, 1st try
root/sub/file : locked, 2nd try
root/sub/file : locked, 3rd try
...
```

**Comment by sebakerckhof** [comment]
You could change this behavior in rimraf, but that doesn't really help since the file still needs to be deleted.

**Comment by sebakerckhof** [comment]
Btw, I only seem to get it with this binding file. So maybe it is limited to build plugins that have native bindings, that for some reason keep being locked.

**Comment by stubailo** [comment]
@sebakerckhof so if the file needs to be deleted but we can't delete it, what do we do?

**Comment by sebakerckhof** [comment]
Good question :). There's probably no way to avoid this file being locked by node without big changes to meteor-tool, which probably are not justifiable. The only easy way to unlock the file is actually throwing an error and killing the process. So maybe this behavior: https://github.com/meteor/meteor/issues/4933 , while not good, was better than what we have now (since there is no warning to the developer at all). However, the changes made by quetzalcoatl in rimraf are good for temporarily locked files. So I'd keep that but fail faster, e.g. after a fixed amount of total tries.

**Comment by sebakerckhof** [comment]
@stubailo Good question :). There's probably no way to avoid this file being locked by node without big changes to meteor-tool, which I guess is not justifiable. The only easy way to unlock the file is actually throwing an error and killing the process. So maybe this behavior: https://github.com/meteor/meteor/issues/4933 , while not good, was better than what we have now (since there is no warning to the developer at all). However, the changes made by quetzalcoatl in rimraf are good for temporarily locked files. So I'd keep that but fail faster, e.g. after a fixed amount of total tries.

**Comment by hwillson** [comment]
There hasn't been much activity on this issue in over a year, and the lack of +1's leads me to believe this issue affects a very low percentage of the Meteor developer base. I'll close it for now since we're trying to clean up older issues - happy to re-open if anyone disagrees. Thanks for originally reporting this!
