### ISSUE TITLE
Cursor warning in `getMeteorData()` should be disable-able and not appear on production.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5282]
In certain cases it make sense to e.g. pass a cursor in as a prop of a subcomponent (specifically if you want to observe it).

You should be able to suppress the error in this case.

Also it logs this error on production which is unusual for these kind of errors

**Comment by stubailo** [comment]
I'd suggest posting this on the react repo: https://github.com/meteor/react-packages
