### ISSUE TITLE
Android emulator with blue screen in version 1.2 meteor

### ISSUE THREAD

**Issue by allanalexandre** [meteor/meteor#5287]
I'm having a problem with the Android emulator on my application Meteor, this happened when I upgraded from 1.1 to 1.2, what you believe you can be?

![captura de tela 2015-09-25 as 09 09 00](https://cloud.githubusercontent.com/assets/3044907/10100637/79ec1f62-6369-11e5-91c9-9d68de05d208.png)

**Comment by martijnwalraven** [comment]
I'm not sure what this could be. Is it actually setting the background color of the body? Or is it not loading the web view at all?

What I do notice from your screen shot (not sure if this is related), is that you are using older versions of the core Cordova plugins. If you're not relying in specific versions, you may want to remove the directly added plugins so their versions will be taken from the packages that depend on them.
