### ISSUE TITLE
Killednloading on digitalocean deployment

### ISSUE THREAD

**Issue by DemidovVladimir** [meteor/meteor#5288]
Please answer my issue. Why am I getting error from some kind of meteor-tool?
What kind of tools it tryes to upload and do I need to create 10 dollar droplet, but what If my client want a droplet that have 5 dollar cost?
That sims to be weard problem!
My app weights about couple of mbs but I have to buy more expensive droplet only to deploy meteor, don't you think it is too dumb?

**Comment by DemidovVladimir** [comment]
By the way meteor is 1.2.0.1 version!

**Comment by FullStackMan** [comment]
I've deployed meteor on a $5 droplet before. The issue is RAM. You can create swap like sohttps://saturnapi.com/fullstack/swap

**Comment by FullStackMan** [comment]
I've deployed meteor on a $5 droplet before. The issue is RAM. You can create swap like so
https://saturnapi.com/fullstack/swap

**Comment by stubailo** [comment]
The cheapest option for hosting your Meteor app is free: `meteor deploy` just works.

When you deploy your app on digital ocean, you shouldn't need to use the Meteor tool. There are some directions here: http://docs.meteor.com/#/full/deploying

There are also some community tools that help with this. See the category on the forums: https://forums.meteor.com/c/deployment
