### ISSUE TITLE
how to uninstall meteor ?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#529]
uninstall all meteor, and reinstall it freshly.

how to do ?

**Comment by mj1930** [comment]
How to uninstall meteor from ubuntu?

**Comment by abernix** [comment]
@mj1930 The instruction above should be sufficient for Linux and OS X:

```
sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor
```

**Comment by augmen** [comment]
great it works
