### ISSUE TITLE
Cannot reinstall Meteor on windows 7

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#5293]
I needed a clean install of Meteor so I've uninstalled the old one and removed /user/appdata/local/.meteor folder (which uninstaller left behind weighing 350mb!).
Then I run the installer, but it doesn't download anything, just says that it's been installed
![image](https://cloud.githubusercontent.com/assets/10534563/10116063/b7e8ab7a-6434-11e5-9e5a-4499d9153bee.png)
But in reality nothing is installed and cmd doesn't recognize `meteor` command, nor `/user/appdata/local/.meteor` folder is created.
I guess there are some entries left in the registry which uninstaller didn't remove and so the installer thinks the app is already installed. Even so - it should have had a Repair option to restore all the default files.
So what do I do now - I cannot run my app.

**Comment by avalanche1** [comment]
Thankfully I've found [this topic](https://forums.meteor.com/t/windows-install-uninstall-hell/2375) and was able to download Meteor 1.1 from AWS and now everything works again.
Fix the installer for 1.2.

ps. you should provide links to previous versions on official site.

**Comment by avalanche1** [comment]
Also see https://forums.meteor.com/t/windows-install-uninstall-hell/2375

**Comment by stubailo** [comment]
That's very odd. Does updating to Meteor 1.2 through `meteor update` work for you? Also, I'm curious why you needed a clean install?

And the discussion about installing old versions is here: https://github.com/meteor/meteor/issues/4526

**Comment by avalanche1** [comment]
`Does updating to Meteor 1.2 through meteor update work for you?`
Yes.
`Also, I'm curious why you needed a clean install?`
https://github.com/meteor/meteor/issues/5269

**Comment by abernix** [comment]
I've tried again and again to reproduce this on Windows 7, but I cannot – and I reinstall it on a regular basis.  To reinstall, I simply uninstalled and reinstalled.  I do believe it may have been a bug at one point but it hasn't continued to be recurring issue.
