### ISSUE TITLE
Object.assign is undefined in meteor@1.2 // expose babel plugin API

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#5295]
Hi,

after updating from 1.1 to 1.2 and throwing out  ``grigio:babel`` in favour of the ``ecmascript`` package, ``Object.assign`` was broken. [Looks like its not part of the babel core](https://github.com/babel/babel/issues/377), but can be made accessable by plugin. In the latest meteor version is there any way set plugins for the ES6 compiler? Or are there any plans that MDG will integrate these plugins with basic ES6 features which are currently not part of bables core?

Note: I guess it worked in 1.1 because the ``grigio:babel`` has enabled that faeture.
Note 2: Yes I am aware of ``_.extend``, but if thats the answer, why are we doing these ES6 stuff anyway.

**Comment by bySabi** [comment]
Same here:

I my package Object.assign and rest operator(...) not work inside a method of a `class`
```
SimpleSchema = class extends _SimpleSchema {
  constructor(schemas, options) {
    super(simpleSchemaExtended(schemas), options)
  }

  extendField(field, obj) {
   Object.assign(this._schema[field], obj)
   // { ...this._schema[field], ...obj }
   //_.extend(this._schema[field], obj)
   return this
  }
}
```

fail when I call `extendField` method  from a test 
```
TypeError: Object function Object() { [native code] } has no method 'assign'
    at _class.extendField (lib/simple-schema-extended.js:179:11)
```

but is working as expected if called from them same test: 
```
Tinytest.add('SimpleSchema extended - extend Field - test#1', test => {
 
// This line fail !!!!
  const obj = (new SimpleSchema(schemaTest7)).extendField( ...extendField7 )

// This line work!!!
   console.log(Object({}, { theproof: true})

})
```

I use Object.assign and ...rest clone all over the place on my 1.2.0.2 projects.  Is the first time it fail me!

**Comment by dgreensp** [comment]
For the most part, we don't polyfill ES6 API methods at the moment, we just transpile syntax.  We can consider polyfilling more.

However, `...` should work everywhere!  I can't reproduce it failing.

**Comment by lucendio** [comment]
@dgreensp thanks for responding.
What do you think about some kind of API to control babel Plugins (as linked above)? Currently I solved the described issue by creating a local package for the ``Object.assign`` polyfill - and depend other local packages from it. I mean, okay we could take it a little further and create one for all polyfiles and not one for every polyfill but that doesnt feel right, especially when it comes to let other local packages depend on, or even worse publish packages with such dependency.

I mean we are talking about approved parts of ES2015 here, not just some more or less common native JS API.

**Comment by dgreensp** [comment]
I don't know.  I don't think it's so much about Babel plugins, in this case, as polyfills.  We should probably keep expanding our set of polyfills, taking into account browser compatibility and code size.  @benjamn Maybe this is what's next for the `ecmascript` package?

**Comment by bySabi** [comment]
Hi @dgreensp. You can reproduce with this:

```
class ClassA {}
ClassB = class extends ClassA {
  constructor() {
    super()
  }

  failMethod(obj) {
    Object.assign(this, obj)
    return this
  }
}


let test = Object.assign({}, {test: 'ok'})

let test1 = new ClassB()
test1.failMethod({test1: 'fail'})
```

This don´t compile cause `failMethod` of classB

**Comment by stubailo** [comment]
Can you guys try running Meteor 1.2.1-rc.4 and let me know if this is fixed? We now include more polyfills for this kind of stuff.

#5478 has more details.

**Comment by stubailo** [comment]
Meteor 1.2.1 is out, and this should now be supported.
