### ISSUE TITLE
ECMAScript2015 Class definitions are defaulted to file scope, not package scope

### ISSUE THREAD

**Issue by em0ney** [meteor/meteor#5296]
Hey there,

Inside of a package, I have a class being defined in A.js and it is being instantiated in B.js.  I have guaranteed that A.js is loaded before B.js.  By default, my class "A" is restricted to file scope, so is not available in B.js.

```javascript
// file: A.js
class A {
...
}

// file: B.js
a = new A();

// throws: [ReferenceError: A is not defined]
````

My workaround:
```javascript
// file: A.js
class _A {
...
}
A = _A;

// file: B.js
a = new A();
````

Without assigning the class definition to a package scoped variable, the class is unavailable in any other files in the package.

Thanks,
Elliott

**Comment by macrozone** [comment]
You can use class expression:

A = class { ... }

**Comment by stubailo** [comment]
The best thing to do right now is (I think):

```
A = class A {
  ...
}
```

This is an unfortunate side effect of Meteor's package scope system.

@benjamn is currently working on ES2015 module support, and in that world it will be a much nicer:

```
export class A {
  ...
}
```

Until then, the workaround is what you'll have to do.
