### ISSUE TITLE
Minor improvement for Cordova Android upgrade instructions

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5299]
In the instructions
> https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Mac

I found this sentence:
> Add ANDROID_HOME/tools, and ANDROID_HOME/platform-tools to your PATH.

I'd like to suggest to change this to:
> Add $ANDROID_HOME/tools, and $ANDROID_HOME/platform-tools to your PATH.

For people who are not that savvy in setting environment variables (like me), the current statement is a bit misleading.

**Comment by martijnwalraven** [comment]
Good point, change made!

**Comment by derwaldgeist** [comment]
Great, thanks!
