### ISSUE TITLE
Add an option to command line to measure build time

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#5302]
Like, when how long it takes to start an app, to build, to restart and to refresh. For testing purposes.

**Comment by Slava** [comment]
I have already commented on such flag in issue https://github.com/meteor/meteor/issues/5269.

The flag is `METEOR_PROFILE=50`

**Comment by Slava** [comment]
Also: https://github.com/meteor/meteor/tree/devel/tools#profiling

**Comment by avalanche1** [comment]
I guess these are different things we're talking about, no?

**Comment by Slava** [comment]
Have you tried it? I have no idea what you mean by "different things". If you believe they are different, please explain what do you expect to see and what do you see in the output instead.

**Comment by avalanche1** [comment]
Ah, I see. There is already a profiling tool. oops)
BUT - it should be in the docs!
