### ISSUE TITLE
meteor@1.2 don't runs 1.1.4 app

### ISSUE THREAD

**Issue by RamEduard** [meteor/meteor#5303]
I have the following error when meteor try run my app...

Downloading meteor-tool@1.1.4... 

And after:
![captura de pantalla de 2015-09-27 14 05 22](https://cloud.githubusercontent.com/assets/1749930/10124534/141cdc26-6521-11e5-9a52-6c378859666e.png)

**Comment by avital** [comment]
Looks like this is an issue where Meteor installed the new release but not the new version of the tool. That's a bug, but unfortunately it will be hard to investigate this without a repro.

In the meanwhile, can you try deleting `/home/serrano/.meteor` and running your app again? It should re-download the Meteor release, packages and tool version and your app should work.

**Comment by RamEduard** [comment]
Fine, i did that. It's runing again. Thanks

**Comment by avital** [comment]
Great! Sorry we weren't able to track down the root cause but happy I could help
