### ISSUE TITLE
Meteor 1.2.0.1 Error processing less @import

### ISSUE THREAD

**Issue by emmanuelbuah** [meteor/meteor#5304]
Here is a simple welcome to meteor repo - https://www.dropbox.com/s/yf8q6s7z96sn2zo/pointtwo.zip?dl=0 with the following error on execution i.e. meteor run

```
While processing files with less (for target web.browser):
   pointtwo.less:3: Unknown import: /public/base.import.less
```

The app has two less files. Pointtwo.less which imports base.import.less in the public folder.

**Comment by stubailo** [comment]
You can't import things from the `public` folder. `public` is not interpreted as "source code" for the app - it is solely for files that are going to be served statically to the client, and not compiled or imported.

This could be better documented, but in this case is working as expected.

**Comment by emmanuelbuah** [comment]
@stubailo  Got it. So import will only work under the client folder or in a packag (per importing from a package instruction for 1.2)

**Comment by stubailo** [comment]
Yes, any folder other than `public`, `private`, and folders that start with a dot. As noted here: http://docs.meteor.com/#/full/structuringyourapp

**Comment by cndreiter** [comment]
If I put my roughly 50 LESS files of [UIkit](https://github.com/uikit/uikit) into an arbitrarily named folder (not `private` or `public`, I get much more error messages because these LESS files are all interpreted directly.

How can I make it work with Meteor 1.2?

Renaming all the files is not an option.

**Comment by stubailo** [comment]
Unfortunately right now the only way to make it work is to rename all of the files; sorry.

**Comment by emmanuelbuah** [comment]
Or, place them in an "import" folder and import them in your mail CSS file.

**Comment by cndreiter** [comment]
@stubailo 

Well, for a Meteor beginner like me this is a showstopper because 3rd party LESS files are inevitable.

So far I had good experiences with Meteor, that is why I adopted it. I need to build a personal homepage within a week. Now I am not sure any more how I could achieve this with Meteor...

**Comment by stubailo** [comment]
Oh wait never mind - maybe Emmanuel is right - you might be able to put them in a directory named 'import'. I think I'm behind the times.

**Comment by cndreiter** [comment]
@emmanuelbuah @stubailo 

Just tried it, same result :-(

**Comment by emmanuelbuah** [comment]
You "import" folder will have to be under the client folder. So place your
UIKit folder in an import folder under the client folder. Then you can
import less files in your UIKit folder in your main .less file.

**Comment by cndreiter** [comment]
I moved the `import` folder into the `client` folder as you suggested, still getting masses of errors.

```
   ...
   client/import/bower_components/uikit/themes/gradient/thumbnail.less:10:48: variable @global-border is undefined
   client/import/bower_components/uikit/themes/gradient/tooltip.less:10:48: variable @global-z-index is undefined
   client/import/bower_components/uikit/themes/gradient/utility.less:10:48: variable @global-grid-gutter is undefined
   
=> Your application has errors. Waiting for file change.
```

**Comment by emmanuelbuah** [comment]
@cndreiter I can help you if we can do a quick video + share screen cast. I don't know where the issue is but it works for more. I'm using bootstrap (less) and I have it in an import folder under client. Meteor will treat skip over .less file under the import folder unless they are imported by another less file outside the import file.

**Comment by emmanuelbuah** [comment]
I haven't used UIKit before so I don't know how their less or sass files are structure but it should be pretty easy to make it work with meteor 1.2. I also don't like the changes MDG made in relation to less in 1.2 but its done.

**Comment by cndreiter** [comment]
I did a [screencast (please click to download)](http://46.182.19.246/meteor-less-errors.480p.mov). Resolution is not the best because my upload isn't as well.

**Comment by emmanuelbuah** [comment]
@cndreiter I found the issue. Sorry. The folder has to be named "imports", not "import".

**Comment by cndreiter** [comment]
Before I did the screencast, I tried it with `imports` as well.

Strange errors:

```
=> Started proxy.                             
=> Started MongoDB.                           
W20151005-01:07:05.274(2)? (STDERR)           
W20151005-01:07:05.418(2)? (STDERR) /Users/inet/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151005-01:07:05.418(2)? (STDERR)             				throw(ex);
W20151005-01:07:05.418(2)? (STDERR)             				      ^
W20151005-01:07:05.418(2)? (STDERR) ReferenceError: define is not defined
=> Exited with code: 8                        
W20151005-01:07:11.570(2)? (STDERR)           
W20151005-01:07:11.570(2)? (STDERR) /Users/inet/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151005-01:07:11.570(2)? (STDERR)             				throw(ex);
W20151005-01:07:11.570(2)? (STDERR)             				      ^
W20151005-01:07:11.572(2)? (STDERR) ReferenceError: define is not defined
=> Exited with code: 8                        
W20151005-01:07:18.107(2)? (STDERR)           
W20151005-01:07:18.107(2)? (STDERR) /Users/inet/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151005-01:07:18.108(2)? (STDERR) 						throw(ex);
W20151005-01:07:18.108(2)? (STDERR) 						      ^
W20151005-01:07:18.111(2)? (STDERR) ReferenceError: define is not defined
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by cndreiter** [comment]
Maybe it has something to do with the Javascripts of UIkit...

**Comment by emmanuelbuah** [comment]
Possibly but looking at the error, it looks like its not a .less issue. It might be the js file or another issue entirely.

**Comment by cndreiter** [comment]
**Thank you for your valuable input, Emmanuel.** Now I have a base to investigate further. I will do more debugging on this tomorrow.
