### ISSUE TITLE
Help needed: How to build a release image from dev_bundle

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#5307]
Hi Nick ( @n1mmy  ), David ( @glasser  ), David ( @dgreensp ), Sashko ( @stubailo  ), MDG

I hope that one of you is able and willing to give me a short helping note.

As you may remember, I am working on that unofficial fork for ARM devices. Since yesterday I also now have successfully rebuild the binaries for node, npm, mongo and mongod from your repros also for the ARM architecture.

I would like now to provide an installer archive like you do for x86 and osx.

**Question:** How do you build your release archives. Is there a script similar to `scripts/generate-dev-bundle.sh` ?

I have not find yet the right information how to create the structure you do as in latest release https://d3sqy0vbqsdhku.cloudfront.net/packages-bootstrap/1.2.0.1/meteor-bootstrap-os.linux.x86_32.tar.gz

Thanks for a short feedback
Tom

**Comment by stubailo** [comment]
It's a command `meteor admin make-bootstrap-tarballs`.

Check the source code for usage information!

**Comment by TomFreudenberg** [comment]
Hi Sashko ( @stubailo  ) thanks a lot for that quick response. That helped me already and I work out to generate an armv7l image of meteor.

May I ask you also to check just once my question on forum? https://forums.meteor.com/t/meteor-built-in-node-mongo-vs-os-depended-versions-to-use-for-production/10400/10?u=tomfreudenberg

Thanks 
Tom

**Comment by TomFreudenberg** [comment]
Hi Sashko ( @stubailo ) 

I have now completly full filled the changes to meteor 1.2.0.2 so that it can be build on armvXl architecture. I have also attached arm support to your mongo git and can compile the node for meteor.

So scripts:

* build-node
* build-mongo
* generate-dev-bundle

are running smoothly.

I tried now to build the bootstrap tarball and checked the remote-catalog values.

My next question on this process is:

Q: How do I generate the meteor-tool like the one you have generated at:

<pre>
{ buildArchitectures: 'os.linux.x86_32+web.browser+web.cordova',
    builtBy: { username: 'sashko', id: 'ABjjWdSKZqzKwoQcp' },
    build:
     { url: 'https://warehouse.meteor.com/builds/Pr7L8f6PqXyqNJJn4/1443478536376/YubJEnQm2w/meteor-tool-1.1.9-os.linux.x86_32+web.browser+web.cordova.tgz',
       tarballHash: 'Rlo0pbe4M2CmxVgu+QQIOzMJXvjoLbFk2CL+2XmWzBM=',
       treeHash: 'UrlFv7sjNCSLRx4DxvWF+nK8pE2x1Z3AbpnRmoxW1fA=' },
    versionId: 'Qanx9t7RkGNZrtNyC',
    lastUpdated: '2015-09-28T22:15:39.372Z',
    _id: 'f9FJuWTEnf8skJ7bA',
    buildPublished: '2015-09-28T22:15:39.372Z' },
</pre>

Thanks again for short pointing me to the right side.

Cheers
Tom

**Comment by stubailo** [comment]
@TomFreudenberg do you mean how to publish the `meteor-tool` package for a certain architecture?

**Comment by TomFreudenberg** [comment]
Not only to publish but also how to build that kind of tarball for a certain architecture.

Is there some script / command like `meteor admin make-bootstrap-tarballs` available or some kind of documentation how you build those?

Thanks for your help
Tom

**Comment by stubailo** [comment]
well we have our command `meteor publish-release --from-checkout` which actually creates the release, then we use `scripts/admin/publish-meteor-tool-on-all-platforms.sh`, which runs a custom command called `meteor publish --existing-version` on machines from the Meteor build farm (`meteor admin get-machine` I think?), which is like `publish-for-arch` but works for the Meteor tool.

**Comment by TomFreudenberg** [comment]
Thanks Sashko ( @stubailo ) - I will step thru the commands and sources and check if I may succeed with this steps ;-)
