### ISSUE TITLE
mdg:reload-on-resume - Not working with Crosswalk?

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5308]
Just tested it on my local dev machine. My app doesn't refresh anymore, even if I've modified some files. I've killed the app and started it again, but it works still with the old code. I'm using Meteor 1.2, tested with an Android 4.4 device.

**Comment by dnish** [comment]
@martijnwalraven I'm sorry, it can be closed. It was a coding error that didn't appear in the Cordova logs.

**Comment by martijnwalraven** [comment]
Ok, good to hear!
