### ISSUE TITLE
Blaze.rendered - Restrict $(selector) to template HTML

### ISSUE THREAD

**Issue by dcworldwide** [meteor/meteor#5316]
I often need to query the DOM from within my template logic. Mostly in rendered, sometimes in helpers. The issue I am having is that invariably, I only want to query the DOM managed by my template. The $ instance injected into Blaze templates doesn't do this, it instead allows us to select any element in the DOM regardless of whether it is managed by our template. This lack of encapsulation has a few side-affects.

1. When using #each loops to render the same Template multiple times, I need to make sure that I define Template HTML elements with unique Ids so that my $(selector) logic finds the correct element. 
2. Querying the entire DOM with $(selector) isn't efficient at all. 

One solution is to modify the $ signature with the following:

$(selector, constrainToTemplate:bool = false).

**Comment by macrozone** [comment]
this.$(".child-of-template") / template.$(".child-of-template") does not work for you? 

template.$ is restricted to the current template.

**Comment by dcworldwide** [comment]
Thanks @macrozone you are correct. I was using $ and not template.$.

**Comment by avital** [comment]
Yup, `template.$` is the way to go.
