### ISSUE TITLE
Meteor add ios / android fail

### ISSUE THREAD

**Issue by okpatil4u** [meteor/meteor#5317]
Having this issue on OS X. Using zsh, project is the meteor project directory.
Meteor 1.2.0.2
Cordova 5.3.3

➜  project  meteor list-platforms
browser
server

➜  project  meteor add-platform ios 
=> Errors executing Cordova commands:         
                                              
   While adding platform iOS to Cordova project:
   Cordova error: Platform ios already added. 
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)

➜  fitness  meteor add-platform android --verbose 
Adding platform Android to Cordova project    
=> Errors executing Cordova commands:         
                                              
   While adding platform Android to Cordova project:
   Cordova error: CordovaError: Platform android already added.
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js:130:35
   at _fulfilled
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)
➜  project  meteor add-platform ios --verbose
Adding platform iOS to Cordova project        
=> Errors executing Cordova commands:         
                                              
   While adding platform iOS to Cordova project:
   Cordova error: CordovaError: Platform ios already added.
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js:130:35
   at _fulfilled
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)

➜  project  meteor add-platform android
=> Errors executing Cordova commands:         
                                              
   While adding platform Android to Cordova project:
   Cordova error: Platform android already added.
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)
➜  project  meteor add-platform android --verbose 
Adding platform Android to Cordova project    
=> Errors executing Cordova commands:         
                                              
   While adding platform Android to Cordova project:
   Cordova error: CordovaError: Platform android already added.
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js:130:35
   at _fulfilled
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/Omkar/.meteor/packages/meteor-tool/.1.1.9.cvy08d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   (If the error message contains suggestions for a fix, note that this may not
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)

**Comment by martijnwalraven** [comment]
It seems the Meteor platforms and Cordova platforms may have gotten out of sync. Could you check if `rm -rf .meteor/local/cordova-build` fixes this?

Did you by any chance use the `cordova` command directly in the `cordova-build` directory?

**Comment by okpatil4u** [comment]
No, I didn't run cordova command in cordova-build directory. And rm -rf .meteor/local/cordova-build does not work as well.

I upgraded cordova and meteor to latest version. But it's still not working. My older meteor-cordova applications which worked well before have stopped working as well.

**Comment by martijnwalraven** [comment]
Did you run `-rf .meteor/local/cordova-build` from your project directory?

Upgrading Cordova won't make a difference, because Meteor bundles its own version and won't use a globally installed one.

**Comment by okpatil4u** [comment]
Yes. I tried it.

**Comment by martijnwalraven** [comment]
Is this with a newly created project? If not, could you try that to see if it also occurs there?

**Comment by okpatil4u** [comment]
This happens with both new and old projects.

**Comment by martijnwalraven** [comment]
Is there anything more you can tell me about your environment? I haven't been able to reproduce this, and I haven't seen other reports, so that makes it hard to figure out what is going on.

**Comment by okpatil4u** [comment]
Please tell me if there are any commands that I could use to generate these
reports.
Otherwise I could reinstall cordova and meteorjs to see if it works.

**Comment by okpatil4u** [comment]
Ok, so all the older cordova projects are running properly, so there is no problem with cordova. I reinstalled meteorjs, and it's still not working.

**Comment by martijnwalraven** [comment]
When you say older Cordova projects are working, do you mean projects created not by Meteor but by using the `cordova` command directly? Meteor uses its own bundled version of Cordova, so it is not affected by having a globally installed version available (it doesn't even require `cordova` to be installed).

Just to be clear, you've tried creating a new Meteor project using `meteor create` right?

**Comment by okpatil4u** [comment]
Yes and yes.

**Comment by martijnwalraven** [comment]
Is it possible to post a tar or zip of the project directory for a newly created project where you've tried adding platforms?

**Comment by okpatil4u** [comment]
Yes. It's a simple meteor project. 
https://www.dropbox.com/s/ig633sl5u8gg1lp/test_meteor.zip?dl=0

**Comment by martijnwalraven** [comment]
I don't see anything out of the ordinary here. The project has no platforms added in `.meteor/local/cordova-build/platforms`, but `meteor add-platform ios` works for me and adds the platform.

This issue is really a mystery to me! Just groping around in the dark here, but could you try `rm -rf ~/.cordova`?

**Comment by okpatil4u** [comment]
I tried moving the folder to another place. Still not working. I completely removed meteor installation including ~/.meteor directory. It's not working.

**Comment by okpatil4u** [comment]
Is it possible to use native cordova with meteor project ?? Can I compile the client side code and run it with cordova manually ?

**Comment by martijnwalraven** [comment]
There is currently no good way to create your own Cordova project with the compiled client side code. You could try copying the files from `.meteor/local/build`, but you would also have to manually add `index.html`, `config.xml`, etc. So I'd rather find out what is going on with your installation!

I don't know how comfortable you are with this, but do you see any chance to make a change to `~/.meteor/packages/meteor-tool/1.1.9/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js` to help track this down? It would be helpful if you could add this after line 124:
```
console.log('platformPath', platformPath);
```
Then run `meteor add-platform ios --verbose` and report back what the output is.

**Comment by okpatil4u** [comment]
console.log is not showing anything. But I used CordovaError to get some
output. Interesting thing is that it is showing

parent directory for projectRoot rather than parent/meteor_project
directory. Is it normal ?

**Comment by okpatil4u** [comment]
And also, it's not
 ~/.meteor/packages/meteor-tool/1.1.9/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js
file, that is showing me verbose error, but it's ~
/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js.

**Comment by okpatil4u** [comment]
Ok, this is interesting. I moved my project directory to another folder in root directory and it works now. 
It seems parent directory is a cordova project by itself, my goof up actually, and it was interfering with meteor project. 
Thanks for being patient with me and for your help.

**Comment by martijnwalraven** [comment]
Great to hear you figured it out!
