### ISSUE TITLE
static-html / caching-html-compiler have a jQuery dependency

### ISSUE THREAD

**Issue by mxab** [meteor/meteor#5320]
with 1.2.0.2 the jquery issue is back
see https://github.com/meteor/meteor/issues/5223

**Comment by mxab** [comment]
@stubailo was there any specific reason why you went back to use jQuery to set the body attributes?

**Comment by stubailo** [comment]
I introduced a bug when I removed it... it's more work than I thought!

Going to keep this open as a feature request.

**Comment by mxab** [comment]
Hmm ok, but if I'm not mistaken everyone who wants to use angular instead of blaze needs to depend on jQuery explicitly otherwise the application will break right?
Currently my application depends on jQuery anyway so I can live with it, but I'm also trying to setup a [angular-meteor-platform](https://github.com/planet-training/angular-meteor-platform) package which would now need the jQuery dependency.
I haven't done any React, but I guess also there jQuery is optional

**Comment by stubailo** [comment]
Yep, I know - hopefully we can fix it soon.

**Comment by stubailo** [comment]
I'd love to look at a pull request for this. Here's the relevant code:

https://github.com/meteor/meteor/blob/9c46763e3f62cbe813769b1f88f5554b00c6605e/packages/caching-html-compiler/caching-html-compiler.js#L112

Basically we need to change this code to not use jQuery to set attributes. But we need to make sure to escape the attribute keys/values properly.

**Comment by mxab** [comment]
Ok I see, I try to look into it

**Comment by mxab** [comment]
@stubailo could you provide some samples where the escaping is needed? or are there some tests for this already?

**Comment by stubailo** [comment]
No there are no tests yet. One example is if you do `<body x='"y"' ...` then a naive implementation without quote escaping will do some wrong things. This is what happened to me.

**Comment by mxab** [comment]
so the generated markup should contain ```<body x='\"y\"'``` right? But did you write ```<body x='"y"'``` yourself in the firstplace and wouldn't this be invalid already?

**Comment by ozsay** [comment]
@stubailo is this implementation good enough ?

```js
Meteor.startup(function() {
    var attrs = ${JSON.stringify(compileResult.bodyAttrs)};
    for (var prop in attrs) {
      document.body.setAttribute(prop, attrs[prop]);
    }
  });
```

What does this implementation lack?

**Comment by stubailo** [comment]
This could work I think - I ran into some problems with escaping quotes but it looks like this wouldn't have that problem. Submit a pr to remove the deep and I'll accept it.

**Comment by stubailo** [comment]
*dep

**Comment by faburem** [comment]
When I create a new project where I remove blaze and jQuery in favor of static-html, jQuery is still loaded. This happens with Meteor 1.2.1 and also with the latest 1.3-rc.5. Here is what I did and my test results:
```
meteor create static-html
meteor remove blaze-html-templates insecure autopublish jquery
meteor add static-html
```
When I run this regularly:
![screen shot 2016-03-22 at 09 48 00](https://cloud.githubusercontent.com/assets/11456790/13946591/d6affff0-f015-11e5-9705-52abfdf6d15c.png)
and the same with --production:
![screen shot 2016-03-22 at 09 54 05](https://cloud.githubusercontent.com/assets/11456790/13946611/eeb537fa-f015-11e5-9457-9c246af489d2.png)
![screen shot 2016-03-22 at 09 54 05](https://cloud.githubusercontent.com/assets/11456790/13946613/f2d64fe0-f015-11e5-8b1b-ff0046ff72a8.png)

Am I missing something or is there still a dependency on jQuery somewhere in Meteor Core?

**Comment by stubailo** [comment]
Seems like it - can you file a new issue for that?

**Comment by faburem** [comment]
#6563
