### ISSUE TITLE
Problem with todos example

### ISSUE THREAD

**Issue by alextaaa** [meteor/meteor#5321]
Error: EBADF, read
and
Error iron:router
http://i.imgur.com/Z2WFntf.jpg

**Comment by martijnwalraven** [comment]
This seems like the same issue as https://github.com/meteor/meteor/issues/5319.

**Comment by alextaaa** [comment]
maybe you have not noticed more bugs in the console? `Error: EBADF, read`
the picture is highlighted http://i.imgur.com/Z2WFntf.jpg

**Comment by martijnwalraven** [comment]
I suspect this is also a result of the version of the iron-router dependency you added. Please try again without updating dependencies to unsupported versions.
