### ISSUE TITLE
Missing `getIndexes` on collections

### ISSUE THREAD

**Issue by servel333** [meteor/meteor#5324]
In Meteor, there is currently no way to get a list of existing indexes. This is useful if you need to get the name of an index before dropping it, or want to see if there are any indexes that might interfere with a change.

MongoDB Collections offer a `getIndexes` function, but there also appears to be no way in Meteor to get to the underlying MongoDB Collection.

**Comment by jagi** [comment]
You can write your own method but remember it will only work on the server:

```js
if (Meteor.isServer) {
  var Future = Npm.require('fibers/future');
  Mongo.Collection.prototype.getIndexes = function() {
    var raw = this.rawCollection();
    var future = new Future();

    raw.indexes(function(err, indexes) {
      if (err) {
        future.throw(err);
      }

      future.return(indexes);
    });

    return future.wait();
  };

  Items = new Mongo.Collection();
  console.log(Items.getIndexes());
}
```

**Comment by servel333** [comment]
Thanks. Very helpful.

**Comment by servel333** [comment]
Thanks. I updated http://stackoverflow.com/a/32848389/761771 also.

**Comment by servel333** [comment]
I think this should be part of the core Meteor project, but if it ends up in a package (even by me if I have some time) then that would be acceptable.

**Comment by jagi** [comment]
Yes it definitely should be a part of the core. However it seems that the `Collection` is like a holder for documents not something that is one to one correlation between Mongo and MiniMongo. There may be a good reason for that especially if we are talking about ORM that abstracts interaction with database. I have some ideas for implementing a database abstraction that would not required you to think about what database do you have on the server. But it's a talk for another topic.

If you haven't seen my ORM package [Astronomy](https://atmospherejs.com/jagi/astronomy), then take a look :)

**Comment by servel333** [comment]
I don't think the Astronomy package fits my needs at the moment, but it looks very neat. I think that will be useful for another project of mine soon. Thanks for the link.

**Comment by jagi** [comment]
Good :-) just letting know :-)

**Comment by avital** [comment]
Yeah, this would be a good thing to add to Meteor's collection interface.

**Comment by jagi** [comment]
There isn't getIndexes method probably because it's meant to be the same set of api on both client and server especially if we talk about database access.

**Comment by avital** [comment]
@jagi Well there's the undocumented `_ensureIndex` that we use in some packages.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Missing%20%60getIndexes%60%20on%20collections&body=Migrated%20from:%20meteor/meteor%235324) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
