### ISSUE TITLE
Meteor 1.2.0.2 mobile build throws error while building:  ReferenceError: options is not defined 

### ISSUE THREAD

**Issue by oliroy** [meteor/meteor#5326]
Found that the hooksRunner.js file located in: 
'user/.meteor/packages/meteor-tool/1.1.9/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib has code which crashes:

```
    var execOpts = {
      cwd: opts.projectRoot,
      printCommand: !!options.verbose, // print command only if --verbose specified,
      stdio: options.silent ? 'pipe' : 'inherit', // hide script output in silent mode
    };
```

Variable options is never defined, when cross referencing against the cordova-lib 5.2.x github repo you can see the code is different (located at https://github.com/apache/cordova-lib/blob/5.2.x/cordova-lib/src/hooks/HooksRunner.js line 181)
```
    var execOpts = {cwd: opts.projectRoot, printCommand: true, stdio: 'inherit'};
```

Replacing the code that crashes with the above line fixes the issue.  By the way the cordova-lib is being downloaded by the meteor install process from http://com.meteor.static.s3.amazonaws.com/cordova-lib-d5ff7cf04757335762b6695f1664bca6c6cfc272.tar.gz.  The tar.gz contains the broken code.

Stack trace produced by running 'meteor build .mobile --debug  --server=http://10.34.15.34' is:

=> Errors executing Cordova commands:         
                                              
   While building Cordova app for platform Android:
   ReferenceError: options is not defined     
   at runScriptViaChildProcessSpawn
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:183:23)
   at runScript
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
   at
   /Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
   at _fulfilled
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/oli/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)

**Comment by martijnwalraven** [comment]
Thanks for the report and for tracking down the root cause! This makes it an easy fix, although that won't help you until the next point release.

Fortunately, this is not an issue with all builds, only for those where hooks are specified. The faulty code you mentioned is triggered when executing a hook script. I suspect this is the result of a plugin you use, that specifies a `<hook>` element in its `plugin.xml`. If that is the case, is there any way you can remove this plugin for now?

**Comment by raix** [comment]
+1

**Comment by oliroy** [comment]
Hey martijnwalraven,

Thanks for getting back to me.  Yes we do use hooks, not in a plugin but for our own customizations to the cordova build process for our mobile app.  Would you know a tentative date for the next point release?  For now our dev team will just modify the broken code in the .meteor folder in our local user directory to make building possible.

Cheers,

**Comment by martijnwalraven** [comment]
There is no set date for the next point release, but it shouldn't be too long. Glad to know you found a workaround.
