### ISSUE TITLE
Have a version of `meteor reset` that doesn't remove the database

### ISSUE THREAD

**Issue by rbaindourov** [meteor/meteor#5328]
Hi,

Yesterday I had some strange phenomenon occur, and it seems that I have stumbled onto a bug where the meteor system fails to rebuild all the of the code associated with a collection.

I have documented my experience on both [Stackoverflow](http://stackoverflow.com/questions/32834667/meteor-mongo-collection-payments-insert-is-already-defined/32848437) and [meteor forum](https://forums.meteor.com/t/meteor-clear-cache/10507/3).

Seems the community would benefit from a `meteor rebuild` command.
Not sure what is compiled or cached in NodeJS based platform, but I don't know how else to describe the issue.

Thank You!

**Comment by stubailo** [comment]
I think this is related to https://github.com/meteor/meteor/issues/5213.

The current workaround is you can delete everything except `db` from `.meteor/local`:

```
build
bundler-cache
isopacks
plugin-cache
shell
```

I'll keep this open as a feature request.

**Comment by glasser** [comment]
There's already `meteor rebuild`, which wipes `isopacks` and `plugin-cache`. It should probably be changed to wipe `bundler-cache` too... and I guess in 1.2 `build` can be reused too, so that too.

**Comment by stubailo** [comment]
@glasser doesn't that just rebuild local packages? What about the app?

Also, it should be documented somewhere that isn't just `meteor help`.

**Comment by glasser** [comment]
sure, i'm just saying we probably can stick to just two "reset local state" commands instead of adding a third :)

in my mind, "meteor reset" is "wipe away all local state" and "meteor rebuild" is (IN THEORY) a never-needed operation that's "there's a bug in meteor (or some plugin, now) so please wipe away all local *caches* and rebuild".  I definitely should have added `bunder-cache` to it when I added it, and added `build` when Slava did his optimization that reuses parts of `build` instead of always rewriting.

**Comment by rbaindourov** [comment]
Thank you Gentlemen for the discussion.

I've removed the need for Meteor's built in mongo instance by having a `run` shell script that sets the `MONGO_URL` and any other project specific settings for each meteor app during development.

So I suppose the `meteor rebuild` command would suit my needs just fine in rebuilding the app and not being able to touch my data if I were to come across this issue again.

As someone who is literally only three months into the whole ecosystem, and still spending lots of time in NodeJS, I do think that this issue should at least be documented or explained. 

I'm a big supporter of Competence vs Magic. I see lots of high level language developers just abandoning the science of computer programming, and "guessing" as to how a system works.  

That's why I prescribe to the theory that any insights as to how Meteor works under the hood are extremely valuable and should be made easily available, because it will breed true subject matter experts in the field. And these are the kind of people I want to work with.



Thank you!


-Robert Baindourov

**Comment by pozylon** [comment]
https://github.com/meteor/meteor/issues/7789

**Comment by hwillson** [comment]
Since #7789 is a more recent and active feature request that will address the same problem as this issue, I'll close this one off. Thanks for pointing this out @pozylon!
