### ISSUE TITLE
disable only minification in production

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#5329]
I'm the creator and the popular [meteor-webpack-react](https://github.com/jedwards1211/meteor-webpack-react) app skeleton, and I've been using it heavily in my own projects.

`meteor run --production` or `meteor build` on a large project is painfully slow because it takes Meteor a very long time to minify large Webpack bundles.  Using the UglifyJS plugin for Webpack seems to be faster, I'm guessing because it can operate on a single module at a time instead of the output bundle.

So ideally I want to prevent Meteor from minifying these bundles, and rely on Webpack for doing that.  However, other recommendations I've seen for disabling minification (e.g. `meteor build --debug`) sound like they alter a lot more than just minification.

I guess I can just make a minify plugin that doesn't actually do minification...is there really no simpler way to do this though?

**Comment by jedwards1211** [comment]
The old CompileStep API provided `fileOptions`.  If these had simply been preserved in the new build plugin API, then I could write a plugin that would nicely handle
```js
api.addFiles('client.bundle.js', 'client', {minify: false}).
```

**Comment by stubailo** [comment]
This is another potential solution: https://github.com/meteor/meteor/issues/5363

Also funny story, I think we still do have `fileOptions` but it's just not exposed through the `InputFile` class: https://github.com/meteor/meteor/blob/d5a9e40ad8ce019a5c90e5aee72b141c9302a39e/tools/isobuild/compiler-plugin.js#L152

I guess it wouldn't be too hard to make that a public property again, then modify `standard-minifiers` to skip minifying files with that option set.

**Comment by jedwards1211** [comment]
@stubailo yeah #5363 was what I settled on as a solution to this (I'm already doing it with a custom package, but that's awkward as it has to be a complete replacement for `standard-minifiers`.

Another interesting note about the build plugin changes...I tried making a plugin to process webpack.config.js files, running a webpack watch or webpack dev server.  I ran into two major issues:
* couldn't get absolute path to the input file (workaround: use deprecated `CompileStep` api)
* isobuild seems to skip re-processing source files that haven't changed, understandably, so when I would rerun the meteor command, it wouldn't start the webpack dev server until I changed the config file.  I thought about various hacks to solve this problem but gave up after awhile.

**Comment by Hongbo-Miao** [comment]
This will be helpful as a temporary way to help deploy angular2-meteor project too.
http://stackoverflow.com/questions/35810333/how-to-deploy-with-non-minified-codes-app-on-heroku

**Comment by hwillson** [comment]
With modern versions of Meteor this can now be handled by removing the `standard-minifier-js` package:

```
meteor remove standard-minifier-js
```

Closing - thanks for the feature request originally!

**Comment by Kwan12** [comment]
@hwillson, thanks for your info! It saved a lot of my time while trying to deal with the outdated code with minifier while doing it with mup.
