### ISSUE TITLE
VersionsFrom for registerBuildPlugin

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#5331]
`Package.onUse` allows to use `versionsFrom` for package version information.

This does not seem to apply to registerBuildPlugin, which can also specify packages it uses.

**Comment by stubailo** [comment]
This would certainly be a good thing to have!

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by stubailo** [comment]
This could be a good candidate for a PR since it's a super well-defined feature that totally makes sense to have.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=VersionsFrom%20for%20registerBuildPlugin&body=Migrated%20from:%20meteor/meteor%235331) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
