### ISSUE TITLE
Cannot remove nonexistent member of organization in Account settings

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#5333]
I'm trying to remove the `meteorpublish` user from organizations such as `nvd3`. When I click the remove link, I get this error in the console:

> Error invoking Method 'removeOrganizationMember': Specified user does not exist [400]

That's legit, but makes it impossible to remove obsolete users from organizations.

**Comment by stubailo** [comment]
So this is a user that was deleted called `meteorpublish`? I guess we probably need to do some manual database magic for this. @zol is this the kind of thing you would do?

**Comment by zol** [comment]
Database magic complete. It looks like the `meteorpublish` user was incorrectly converted to an org in that they weren't removed from orgs during the process (this should normally happen).
