### ISSUE TITLE
.eslintrc file

### ISSUE THREAD

**Issue by sys13** [meteor/meteor#5335]
I would add to the article about [How to set up Atom and WebStorm for Meteor ES6 and JSX](http://info.meteor.com/blog/how-to-set-up-atom-and-webstorm-for-meteor-es6-es2015-and-jsx) that you need to add a .eslintrc file to your project. 

Here's an example .eslintrc file that I'm using:

https://gist.github.com/dburles/a2f7ea77189b268b660d

**Comment by stubailo** [comment]
Hey, I think this would be better as a comment on the blog! @rdickert have you seen this?

Thanks for the feedback.

**Comment by rclai** [comment]
Given what was shared on that blog post, linting does not work out of the box. You need that `.eslintrc` file in your project.
