### ISSUE TITLE
Proper way to sign apps now?

### ISSUE THREAD

**Issue by vacarsu** [meteor/meteor#5338]
```~/.meteor/android_bundle/android-sdk/build-tools/20.0.0/zipalign 4 \
    unaligned.apk production.apk```

No longer works. I get ```No such file or directory```

I have the the sdk installed and everything. Is this page outdated now?
https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store

**Comment by martijnwalraven** [comment]
You're right, this should be updated, because we no longer bundle the Android SDK. Using `$ANDROID_HOME/build-tools/23.0.0/zipalign` should work (possibly replacing the version of the build-tools installed).

**Comment by vacarsu** [comment]
Yes, I suspected it hand to do with the removal of the android SDK will try using $ANDROID_HOME, I have added it to my path. So I will let you know if that works.

**Comment by vacarsu** [comment]
That didn't seem to work below is what my Library/android folder looks like. I noticed the version folder says 22.0.1 so I tried with that version number instead.
![screen shot 2015-09-30 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/11384972/10205999/6fc0edd8-6779-11e5-84f1-5a589481b514.png)

**Comment by martijnwalraven** [comment]
So did you try `~/Library/Android/sdk/build-tools/22.0.1/zipalign`?

**Comment by vacarsu** [comment]
Hah I'm so dumb... That worked thanks.
