### ISSUE TITLE
Error when trying to use ES2015 features in Meteor 1.2.0.2

### ISSUE THREAD

**Issue by pdelacruz86** [meteor/meteor#5339]
I have been trying to play with some features of ES2005 in a .js file : 

```javascript
MyList = {
        _list: [1, 2, 3],
        makeGenerator: function*() {
          let i = 0;
          while ( i < this._list.length ) {
            yield this._list[i++];
            console.log("after yield");
          }
        },
        [Symbol.iterator]() {
          return this.makeGenerator();
        }
      };
      for(let i of MyList) {
        console.log(i);
      }
```

found this error :  /Users/pdelacruz/Desktop/pdlacruzgit/OnGit/meteor_EcmaScript2005/ES2005/.meteor/local/build/programs/server/app/ES2005.es6.js:18
W20150930-14:08:31.976(-4)? (STDERR)       makeGenerator: function* () {                                    // 9
W20150930-14:08:31.976(-4)? (STDERR)                              ^
W20150930-14:08:31.976(-4)? (STDERR) SyntaxError: Unexpected token *
W20150930-14:08:31.976(-4)? (STDERR)     at /Users/pdelacruz/Desktop/pdlacruzgit/OnGit/meteor_EcmaScript2005/ES2005/.meteor/local/build/programs/server/boot.js:241:30
W20150930-14:08:31.976(-4)? (STDERR)     at Array.forEach (native)
W20150930-14:08:31.976(-4)? (STDERR)     at Function._.each._.forEach (/Users/pdelacruz/.meteor/packages/meteor-tool/.1.1.9.1fzs556++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-14:08:31.976(-4)? (STDERR)     at /Users/pdelacruz/Desktop/pdlacruzgit/OnGit/meteor_EcmaScript2005/ES2005/.meteor/local/build/programs/server/boot.js:137:5

To solve the issue I needed to install grigio/meteor-babel and add the .es6.js extension to the file.

For meteor 1.2.0.2 Your regular .js files will take ES2015 syntax by default if you do meteor add ecmascript  witch come by default when creating or updating your project.

Thanks,
Pedro de la Cruz
pedroabrahan@gmail.com

**Comment by benjamn** [comment]
We haven't enabled support for generator functions yet, but that's planned for Meteor 1.3.

By the way, I'm the author of [Regenerator](https://github.com/facebook/regenerator), which is what Babel uses to implement generator functions, so I'm pretty excited about turning them on ASAP.

**Comment by bySabi** [comment]
@benjamn how can test/enable regenerator ?
