### ISSUE TITLE
this.ready() is not defined in publish function

### ISSUE THREAD

**Issue by ayonix** [meteor/meteor#5340]
If I subscribe to this publication the server throws an error (`Exception from sub minimal id aFQY3LQPNayCKEJMy TypeError: Object [object global] has no method 'ready'`)

```
Meteor.publish('minimal', () => {
	this.ready();
});
```

According to the example on http://docs.meteor.com/#/full/meteor_publish these methods should be defined. It is connected to using ES6 which handles this differently?

**Comment by rclai** [comment]
Wrong use of arrow function.

**Comment by ayonix** [comment]
Thanks for this very helpful comment.
Babel transpiles
```
Meteor.publish('minimal', () => {
	this.ready();
});
```
to
```
Meteor.publish('minimal', function () {
	undefined.ready();
});
```
which would be the same as
```
Meteor.publish("counts-by-room", function (roomId) {
    var self = this;
    self.ready();
});
```
as in the example, if you add the argument.
So how is this a wrong use of the arrow function?

**Comment by ayonix** [comment]
Okay so `() => {}` is different from `function() => {}` alright, my fault.

**Comment by stubailo** [comment]
The arrow function _intentionally_ changes the behaviour of `this` so that it's the context outside of the call rather than inside. So this is a place in the Meteor API where you can't use an arrow function.

**Comment by casey-chow** [comment]
Given that this is the case, isn't it still troubling that the newer syntax completely disables the use of contexts in helpers? Is there any particular reason for not implementing some workaround, i.e., passing in the context to the helper as the last parameter, for example?
