### ISSUE TITLE
Update Browser Policy Readme.md

### ISSUE THREAD

**Issue by matthewforr** [meteor/meteor#5341]
Currently it says:

> Finally, you can configure a whitelist of allowed requests that various types of content can make. The following functions are defined for the content types script, object, image, media, font, frame, and connect.

But in reality it should say (emphasis added):

> Finally, you can configure a whitelist of allowed requests that various types of content can make. The following functions are defined for the content types script, object, image, media, font, frame, **style**, and connect.

I know this because Google Fonts wouldn't load.

Also, in the documentation you refer to `image` but in the source code it looks like the key is actually `img`.

**Comment by avital** [comment]
Sure, want to submit a pull request?

**Comment by stubailo** [comment]
Closed with 52c67dd020dcd74f0599b176094c3278243b4640
