### ISSUE TITLE
Weird characters in Meteor errors

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#5342]
I'm seeing unexpected characters in my Meteor errors. See below.

    at meteor://ðŸ’»app/packages/jagi_astronomy/lib/modules/fields/init_definition.js:131:1

This isn't specific to `jagi:astronomy` either. Anyone else getting these?

**Comment by stubailo** [comment]
What browser are you in? This is actually an emoji we use in source maps to have a cute icon in the chrome developer tools, like so:

<img width="356" alt="screenshot 2015-09-30 21 01 10" src="https://cloud.githubusercontent.com/assets/448783/10212600/681ad930-67b6-11e5-93b8-6d1899be29ca.png">

Where is the error being printed? Browser console?

**Comment by ffxsam** [comment]
I'm using the latest Chrome. Ah yes, I do see the computer icon in the dev tools. But the errors I got are when your app is crashing, and you try to load the page and it dumps the errors to the page.

**Comment by rclai** [comment]
I'm also getting this except mine is just a plain square instead of a computer.

**Comment by sebakerckhof** [comment]
Also have the square. Thought it was normal. Chrome on windows.

**Comment by abernix** [comment]
The icon works fine for me in "Sources" – however the emoji starts showing in Stack traces, much like @ffxsam, once `velocity:core` is installed, which uses (NPM Source Maps)[https://www.npmjs.com/package/source-map-support]. This just started with Meteor 1.2.  

@ffxsam Are you using Velocity (Jasmine, Cucumber, etc.) for tests?

**Comment by ffxsam** [comment]
Yes, I do have `velocity:html-reporter` and `sanjo:jasmine` installed.

**Comment by rriemann** [comment]
same issue! I cannot click on the stack trace to see the source. I have also `velocity:html-reporter` and `sanjo:jasmine` installed.

**Comment by rriemann** [comment]
Have you found a work-around for the time we are waiting for a fix ?

**Comment by abernix** [comment]
Closing this because Velocity is no longer supported in 1.3 and no longer maintained by it's author.  This problem no longer exists for me either.
