### ISSUE TITLE
CPU parallelism for meteor-tool compilation tasks

### ISSUE THREAD

**Issue by 4thlaurocruz** [meteor/meteor#5344]
i have an 8 cpu core,

when starting meteor it just uses 100 of one core.

its really beneficial to have 8 cores using 100 percent.

thanks

**Comment by leomatthew** [comment]
Use the package 

meteor add meteorhacks:cluster

It will give you multicore support to your project.

**Comment by MartinBucko** [comment]
@leomatthew thanks

**Comment by 4thlaurocruz** [comment]
i think meteorhacks:cluster uses all core when running. But it doesnt cluster when compiling including --production flag.

**Comment by benjamn** [comment]
Node generally runs in a single process, in a single thread, and Meteor has no built-in support for CPU parallelism. If `meteorhacks:cluster` works for you, that's great, but it's not something we're planning to support in the core any time soon.

That said, pull requests are welcome! I would recommend using something like https://www.npmjs.com/package/node-worker-pool to fork multiple processes to handle compilation in parallel.

**Comment by ramijarrar** [comment]
@benjamn Can we leave this issue open as a feature request?

**Comment by abernix** [comment]
@ramijarrar I believe that's fair, and I will re-open.

However, it's still not on the roadmap for the core team to work on.  A well-designed pull request would be considered for this.  However, as with all pull requests, please discuss your ideas here in this issue before submitting a PR.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=CPU%20parallelism%20for%20meteor-tool%20compilation%20tasks&body=Migrated%20from:%20meteor/meteor%235344) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
