### ISSUE TITLE
Meteor 1.2.0.2 `meteor publish` not backwards compatible - isobuild:isopack-2 error

### ISSUE THREAD

**Issue by peterchoo** [meteor/meteor#5347]
I have private project, using Meteor 1.0.5, and I have a public package [found here](https://github.com/Centiq/client-collection-filter).  The package has `api.versionsFrom('1.0.3.2');`.

I have made an update to the filtering package which I want to use in my project, and been testing it by symlinking it into my project.  Once I am happy with the changes to my package, and that I can use it, I have run `meteor publish` to release it.

When I remove the symlink and use the published version I get the following error: 

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: unknown package: isobuild:isopack-2
   
=> Your application has errors. Waiting for file change.
```

In my project `meteor --version` returns `1.0.5` and in my package returns `1.2.0.2`.  

I have now had to bump the version of my package so that I can run `meteor --release 1.0.5 publish` to  publish a version my project can use without generating the above error.

I believe the `meteor publish` command should take into account the version as specified by the `package.js` file, and that the documentation needs updating to reflect importance of the `--release` option for package developers.

**Comment by mitar** [comment]
Users are reporting the same for my package: https://github.com/peerlibrary/meteor-reactive-publish/issues/3

**Comment by mitar** [comment]
So yes, it seems like publishing with latest Meteor breaks backwards compatibility for those packages, even if they should otherwise continue working.

**Comment by glasser** [comment]
This is unfortunately working as intended for any package that is built with new-style 1.2 build plugins.  For example, @mitar, your package uses coffeescript.

The amount of backwards compatibility code in 1.2 already dwarfs the amount of code actually implementing the new functionality.  Allowing a package to be published simultaneously using the new-style "put the .coffee file in the built package" plugin and the old-style "first process coffee file, then put the JS in the built package" plugin would have essentially required a rewrite of the entire Meteor build system (to allow both the old plugin and new plugin, which are different versions, to coexist).

I encourage users to upgrade to Meteor 1.2, and I hope that future evolutions of the Meteor build system continue to move in the direction of "less processing done at publish time" so that these issues don't exist.

**Comment by mitar** [comment]
OK, so you are saying that in meantime all CoffeeScript packages should be published with older version of Meteor? Why was that not announced anywhere? (Or have I missed it?)

**Comment by mitar** [comment]
You could at least make a warning/deprecation message into `meteor publish`: "We are seeing that you are using `versionsFrom` with version smaller than < 1.2 and are publishing with Meteor version > 1.2. Be advised that package will not work for apps with Meteor < 1.2."

So please reopen this ticket and add at least such a warning.

I do understand that it is hard to keep backwards compatibility, but then warnings and deprecation messages are the way to go.

**Comment by mitar** [comment]
You cannot just hope that people will upgrade as soon as possible.

**Comment by glasser** [comment]
It's in bold in the [https://quip.com/RXFlAk9Rc2xI](upgrade guide)

> **Packages that use the new Build Plugins API, or that use plugins that use the new API, will only work with Meteor 1.2.**  However, we expect to see rapid adoption driven by performance improvements to the build tool, new ECMAScript 2015 support, and React integration, all of which require Meteor 1.2.  You can still publish 1.1-compatible packages from Meteor 1.2, as long as you use core package versions from a pre-1.2 release.

`coffeescript` falls into the category of "plugins that use the new API".

I'm not really sure what the final "as long as you use core package versions from a pre-1.2 release" is supposed to mean; I think it should probably say something more like "as long as they do not rely on any plugins that use the new API".

**Comment by mitar** [comment]
> You can still publish 1.1-compatible packages from Meteor 1.2, as long as you use core package versions from a pre-1.2 release.

I thought I am doing that by having in my `package.js`:

```
api.versionsFrom('METEOR@1.0.3.1');
```

**Comment by mitar** [comment]
Still, a warning message in the console would be great. Because I am less optimistic about adoption of 1.2.

**Comment by themeteorchef** [comment]
Agree with @mitar here re: additional information. What would be most helpful is a link to explain the change in the console. Something like:

```
* These packages have been updated to new versions that are not backwards compatible. For more information, read this: http://info.meteor.com/blah
```

At that URL, it would be nice to see a short doc on what developers need to do to ensure that their packages are compatible with both older and newer installs.

**Comment by mokolodi1** [comment]
This still wasn't working for me, but I've found a workaround:
```sh
METEOR_CLONE=~/meteor/clone/dir

git clone https://github.com/meteor/meteor METEOR_CLONE # clone Meteor
cd METEOR_CLONE # go to the Meteor directory
git checkout release/METEOR@1.1.0.3 # use specific Meteor release
cd ~/location/of/package
METEOR_CLONE/meteor publish --create
```
