### ISSUE TITLE
Documentation by version

### ISSUE THREAD

**Issue by servel333** [meteor/meteor#5348]
I know this is a duplicate of #2960, but please bear with me. I have good reasons for opening a duplicate and I think I have some new arguments to bring to the table for the Meteor team to think about.

This is a request for the official documentation to have a drop-down selector to show older versions of the documentation.

I've been working in meteor for only a month, and already enough of the documentation is out of date to cause problems for my team and I.

Asking others to host the documentation is not a light task. Since the Meteor documentation requires a server (if it was static, I would put it in S3 and host it myself, or host it on Github Pages) it means that hosting older versions of the documentation is not trivial, nor nearly free. It will require a server (either virtualized, Docker container or physical hardware) for each version of the Meteor documentation, and that cost adds up fast if you are not already hosting stuff.

This seems like an appropriate challenge for the official Meteor team to deal with, especially since the documentation can change so fast. I would really like to see the Meteor team consider solving this problem officially, rather than asking the community to help out.

I would also find it acceptable for the meteor team to convert the documentation to static HTML pages. In this way, it would become trivial and cheap to host. There's no good reason I can think of for the pages to require a server, since they show static content.

**Comment by stubailo** [comment]
Just a note: Meteor has free hosting - you can just clone the docs app any type `meteor deploy my-docs-app`.

**Comment by stubailo** [comment]
I also want to do a big project soon to migrate the docs to simpler static site generator. If you know any good options, I'd love to hear about them! All of the content is in markdown format already so it should be pretty simple to move it over.

**Comment by servel333** [comment]
I didn't consider the Meteor free hosting. That's a good idea. I may try to pull down various versions of the docs and see if I can load them up and put up an index somewhere. Thanks.

If it's already in markdown then it sounds like Github pages is a good bet. Hosted right along-side the source. I've been using [Jekyll](https://jekyllrb.com/) as well and can recommand it.

**Comment by stubailo** [comment]
Yep, that's what I have been thinking as well.

**Comment by guilhermedecampo** [comment]
@stubailo [harpjs](http://harpjs.com) is pretty awesome =)

**Comment by peterchoo** [comment]
As an additional note to this, there are developers using Meteor who cannot instantly upgrade version when you release it, and require access to previous versions of documentation.  It would be great to have a drop down to change the version, a la MongoDB Docs.

**Comment by stubailo** [comment]
Yeah I agree this would be good! I'm in the process of writing a plan someone could follow to make this happen.

**Comment by rjakobsson** [comment]
I believe this is solved, and that this could be closed.

**Comment by abernix** [comment]
@rjakobsson You're right, thanks for pointing this out! :smile:
