### ISSUE TITLE
No plugin known to handle *.import.less files

### ISSUE THREAD

**Issue by art-reddy** [meteor/meteor#5350]
Hi,

I use customized bootstrap package and get this exception trying to run app upgraded to Meteor 1.2.0.2:

> error: No plugin known to handle file 'custom/less/bootstrap.import.less'. If you want this file to be a static asset, use addAssets instead
> of addFiles; eg, api.addAssets('custom/less/bootstrap.import.less', 'client').

I include the file using:
api.addFiles('custom/less/bootstrap.import.less', 'client');

If I change it to api.addAssets('custom/less/variables.import.less', 'client'); my app throws this error:
> client/layouts/main_layout.less:1: Unknown import: ../../packages/bootstrap/custom/less/bootstrap.import.less 

So it just can't find this file.
I have dozens of *.import.less files in this and other packages and for all of them I get such error. It seems that meteor just doesn't recognize *.import.less files which in fact should be supported by less package. I use less@2.5.0_3 for application and all my packages.

Does anybody know what may cause this issue and how to solve it?

**Comment by stubailo** [comment]
Does the package containing the less file depend on the `less` package? I haven't encountered this issue before, it would be helpful to have a concrete code sample where this happens.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
