### ISSUE TITLE
Errors when running Meteor Cordova app in either iOS or Android

### ISSUE THREAD

**Issue by andykingking** [meteor/meteor#5353]
I have been experiencing issues when running my application on both iOS and Android. The console errors (either from Xcode or terminal/Chrome Inspect) appear as follows:

```
TypeError: undefined is not an object (evaluating 'Package['hb-tech:schema'].User'):8:http://meteor.local/packages/global-imports.js?38911c57779bebf17470697a86b0cb79c1e31635
ReferenceError: Can't find variable: Template:2:http://meteor.local/app/client/templates/application/includes/empty.tpl.jade.js?6b99c76f501cda74da48b7e4535cd19ad0fcbda2
...
```

These errors are numerous, and are followed by `METEOR CORDOVA DEBUG` messages referencing various assets being downloaded successfully. The application doesn't move past the splash screen on either platform simulator.

**Comment by martijnwalraven** [comment]
From the look of it, these seem more like errors in third-party packages or application code than an issue with Meteor, but I'm going to need at least some more information to understand and help you.

Does the app work when running in in a browser? What version of Meteor are you on? What packages do you use? When you say there are numerous errors, what are these about?

**Comment by andykingking** [comment]
This was due to errors in application code. An error being thrown during startup seemed to prevent Meteor from being loaded, but the rest of the files were still interpreted (and dude to no Meteor, all threw many errors).
