### ISSUE TITLE
old email attachment reference 

### ISSUE THREAD

**Issue by mike623** [meteor/meteor#5355]
mailcomposer has updated option of attachment and not work on meteor. I found the previous version of mailcomposer which is work 

https://github.com/andris9/mailcomposer/blob/b1345ed382bc50bdec5a7fa651d53426f51530dc/README.md

**Comment by stubailo** [comment]
I think this is the "most correct" URL: https://github.com/andris9/mailcomposer/blob/7c0422b2de2dc61a60ba27cfa3353472f662aeb5/README.md

It's the one from the version we use, `0.1.15`.

**Comment by stubailo** [comment]
Should be updated now: http://docs.meteor.com/#/full/email_send

Here's the commit: https://github.com/meteor/meteor/commit/99e8ddaa51aedebef1f950612e33936dfa44f14e
