### ISSUE TITLE
Deserialization of EJSON objects: Calling Meteor.user() leads to parse error

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5356]
I have a custom object that I made EJSON-serializable. Everything worked fine, the object was serialized correctly and had the correct data type when handed over to a method.

Until I placed a call to Meteor.user() in the object's constructor. This call causes the EJSON deserialization to fail. On the client console I can see the error message:

``` bash
Received error from server:  Parse error
```

but on the server console there is no error message. If I place a log statement right after the call to Meteor.user(), that log statement is also not printed to the console. Meteor.user() just fails silently and prevents the rest of the method from executing.

I am calling Meteor.user() because I want to copy some of the current user's profile data to property of the to-be-deserialized object.

EDIT: The same problem applies to Meteor.userId(). While log messages before the call are executed, log messages after the call are not. The functions are defined, but I cannot call them.

(Note: I'm still on Meteor 1.1.0.3)

**Comment by derwaldgeist** [comment]
I have now wrapped the code into a try-catch-handler.

This is what I get on the server console now:
```bash
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
```

**Comment by dgreensp** [comment]
EJSON deserialization is probably the wrong place to put this code.

`Meteor.user()` performs a database query, so on the server it internally yields the current fiber.  EJSON serialization and deserialization happens in the guts of Meteor, when putting things on the wire and taking them off the wire.  It's not necessarily safe or reasonable to yield or go to the database at those times.

Maybe a collection transform would help instead (http://docs.meteor.com/#/full/mongo_collection)?  What are you trying to do, more specifically?

**Comment by derwaldgeist** [comment]
Thanks for the fast reply and these explanations.

My use-case is quite simple: I have a ES 6 model class that I made EJSON-compliant. Although my use-case is a bit different, let's assume it's a class that stores posts in a social app. So it looks somewhat like this:

```js
class Post {
  constructor(obj) {
     ...
     this.author = obj.author || Meteor.userId()
     ...
  }
}
```
So the author of a post can either be passed through the initialization object ```obj``` or will be automatically set to the current user's _id.

EJSON-validation worked fine, until I placed this call to Meteor.userId() in the model class. Not sure if a database transform would help in this case, and it also would introduce two places where such a fallback would be implemented. At the moment, I am already having another place for this: In the SimpleSchema attached to the collection, I've also placed a default-Value handler that sets the author to the user Id, but I do this by calling ```(new Post()).author``` to avoid two implementations for the same fallback.

I managed to workaround the parse error by placing it in a try-catch-handler. But I think it should be documented that Meteor.user() and Meteor.userId() may not be called during EJSON-ification. At the moment, the docs just say: "Anywhere but publish functions".

**Comment by hwillson** [comment]
Thanks for reporting this. As mentioned in https://github.com/meteor/meteor/issues/5356#issuecomment-145168385, mixing EJSON serialization with `Meteor.user()` won't work very well. If you still think this should be added to the docs, please consider opening a new issue over at http://github.com/meteor/docs (or better yet consider submitting a docs PR! 🙂). Closing for now - thanks!
