### ISSUE TITLE
`Cursor.observeChanges` to array fields should show only the added fields.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5357]
I've created a small meteorpad showing the issue

http://meteorpad.com/pad/fyAepn2FYojHKhBjL/Leaderboard

(look at the console.logs).

I would expect to see only the newly added to the array to show up.

**Comment by jedwards1211** [comment]
i'm pretty sure the API is specified to mean the entire new values of top-level fields that changed.  With what you're proposing there would be no way to indicate that items had been removed or changed within an array field; it would take something more complex with much more specification.

**Comment by avital** [comment]
@jedwards1211 is right. The `observeChanges` API only shows changes to top-level elements.

If you really want to, you can use the `observe-sequence` package which lets you diff arrays. But make sure to read the comments in packages/observe-sequence/observe_sequence.js first!
