### ISSUE TITLE
Multiple languages in Accounts UI

### ISSUE THREAD

**Issue by antonkandersson** [meteor/meteor#5360]
Hi, I'm writing an app that's probably going to use Meteor and accounts-ui. Will need to localize the language to Swedish. Have been looking through the different packages for accounts but failed to find any such settings.

1. Do they exist?
2. Would you appreciate localization settings for accounts, if they do not?
3. Do you have a preferred way of how this would be implemented into accounts?

Cheers, Anton

**Comment by stubailo** [comment]
@antonkandersson I think your best bet would be to use this package: https://atmospherejs.com/useraccounts/core

It has many more features than the default `accounts-ui` package; IMO `accounts-ui` is only suitable for early prototyping.
