### ISSUE TITLE
Provide a block helper that adds to the data context

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5361]
I was surprised to find that `#let` doesn't add to the data context:

```handlebars
<body>
  {{#let foo="bar"}}
    {{helper}}
  {{/let}}
</body>
```

```coffeescript
Template.body.helpers
  helper: ->
    console.log @
    @foo
```

http://meteorpad.com/pad/GP54WkuYj9tdj7HrJ/Copy%20of%20Blank

I would expect to see `bar` on the page, but I get a blank page and an empty object logged to the console.

I see that this is by design:

"it doesn't change the data context"
https://github.com/meteor/meteor/tree/devel/packages/spacebars#let

I think it would be useful to have something that:

A. Doesn't overwrite the entire `this` like `#with` does
B. Does add fields to the context (or if there are already fields with the same name, overwrites only those fields)

Because:

1- Having access to the field in a helper is cleaner than always tacking it on to the arg list: 
```
{{helper}}
helper: ->
  @foo
```
vs
```
{{helper foo}}
helper: (foo) ->
  foo
```
2- I don't know how to access `foo` from an event.

**Comment by mitar** [comment]
This is a duplicate of #5280.

**Comment by lorensr** [comment]
Thanks!

**Comment by avital** [comment]
Yup, #5280 is the relevant place for this conversation.
