### ISSUE TITLE
Maybe standard-minifiers shouldn't re-minify .min.js files?

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#5363]
I'd be happy to make a PR, just want someone to acknowledge that this is a desired feature before I go to the effort

Those of us who are using Webpack are discovering that it takes a long time for Meteor to minify Webpack bundles.  Since we can minify more quickly with Webpack's UglifyJS plugin (since it operates on modules individually), it would be nice if we could just output bundles as `server.bundle.min.js` and Meteor wouldn't run them through UglifyJS again.

**Comment by stubailo** [comment]
Yeah, I think that could be very reasonable - I can't think of any reason someone would name their file with `.min.js` if it wasn't minified already. I'll accept the PR if it's a minimal change!

**Comment by jedwards1211** [comment]
Cool!  I'll make the PR soon

**Comment by jedwards1211** [comment]
Do you know of any good way I could add the option to disable bypassing `.min.js` files?  (Besides an environment variable), just in case someone needs it?  And should I print a message about "assuming yourfile.min.js is already minified" on the off chance it would be a surprise to some dev?

**Comment by laosb** [comment]
Fixed in #6986 !
