### ISSUE TITLE
Running on device take forever/not showing

### ISSUE THREAD

**Issue by cimenx** [meteor/meteor#5364]
Excuse me. I working on a project that using Angular Ionic.  I didn't set any icon and launchScreens in mobile-config.js because it make compilation error. After i executed using
$meteor run android-device --mobile-server http://my.laptop.ip.provided.by.usb.thetering:3000
i waited 6 hours and my app didn't show in my phone. Here is the log/shell :

Notebook-PC:~/Project/Meteor_Practice/mdk2015$ meteor run android-device --verbose --mobile-server http://192.168.42.128:3000
Getting installed version for platform android in Cordova project
Checking Cordova requirements for platform Android
[[[[[ ~/Project/Meteor_Practice/mdk2015 ]]]]]

=> Started proxy.                            
=> Started MongoDB.                          
Local package version is up-to-date: accounts-base@1.2.1
Local package version is up-to-date: accounts-password@1.1.3
Local package version is up-to-date: accounts-ui@1.1.6
Local package version is up-to-date: accounts-ui-unstyled@1.1.8
Local package version is up-to-date: angular@1.0.1
Local package version is up-to-date: angular:angular@1.4.7
Local package version is up-to-date: angular:angular-animate@1.4.7
Local package version is up-to-date: angular:angular-sanitize@1.4.7
Local package version is up-to-date: angularui:angular-ui-router@0.2.15
Local package version is up-to-date: autoupdate@1.2.3
Local package version is up-to-date: babel-compiler@5.8.24_1
Local package version is up-to-date: babel-runtime@0.1.4
Local package version is up-to-date: base64@1.0.4
Local package version is up-to-date: binary-heap@1.0.4
Local package version is up-to-date: blaze@2.1.3
Local package version is up-to-date: blaze-html-templates@1.0.1
Local package version is up-to-date: blaze-tools@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.4
Local package version is up-to-date: caching-compiler@1.0.0
Local package version is up-to-date: caching-html-compiler@1.0.2
Local package version is up-to-date: callback-hook@1.0.4
Local package version is up-to-date: check@1.0.6
Local package version is up-to-date: dburles:mongo-collection-instances@0.3.4
Local package version is up-to-date: ddp@1.2.2
Local package version is up-to-date: ddp-client@1.2.1
Local package version is up-to-date: ddp-common@1.2.1
Local package version is up-to-date: ddp-rate-limiter@1.0.0
Local package version is up-to-date: ddp-server@1.2.1
Local package version is up-to-date: deps@1.0.9
Local package version is up-to-date: diff-sequence@1.0.1
Local package version is up-to-date: dispatch:kernel@0.0.6
Local package version is up-to-date: dispatch:request-animation-frame@0.0.1
Local package version is up-to-date: driftyco:ionic@1.1.0_2
Local package version is up-to-date: ecmascript@0.1.5
Local package version is up-to-date: ecmascript-collections@0.1.6
Local package version is up-to-date: ejson@1.0.7
Local package version is up-to-date: email@1.0.7
Local package version is up-to-date: fastclick@1.0.7
Local package version is up-to-date: fxckdead:angular-elastic@2.5.0
Local package version is up-to-date: fxckdead:ng-cordova@0.1.20-alpha
Local package version is up-to-date: geojson-utils@1.0.4
Local package version is up-to-date: ground:db@0.3.14
Local package version is up-to-date: ground:dictionary@0.2.1
Local package version is up-to-date: ground:localstorage@0.1.9
Local package version is up-to-date: ground:minimax@1.1.3
Local package version is up-to-date: ground:servertime@0.0.3
Local package version is up-to-date: ground:store@0.1.2
Local package version is up-to-date: ground:util@0.1.17
Local package version is up-to-date: hot-code-push@1.0.0
Local package version is up-to-date: html-tools@1.0.5
Local package version is up-to-date: htmljs@1.0.5
Local package version is up-to-date: http@1.1.1
Local package version is up-to-date: id-map@1.0.4
Local package version is up-to-date: jquery@1.11.4
Local package version is up-to-date: lai:collection-extensions@0.1.4
Local package version is up-to-date: launch-screen@1.0.4
Local package version is up-to-date: less@2.5.0_3
Local package version is up-to-date: livedata@1.0.15
Local package version is up-to-date: localstorage@1.0.5
Local package version is up-to-date: logging@1.0.8
Local package version is up-to-date: meteor@1.1.9
Local package version is up-to-date: meteor-base@1.0.1
Local package version is up-to-date: minifiers@1.1.7
Local package version is up-to-date: minimongo@1.0.10
Local package version is up-to-date: mobile-experience@1.0.1
Local package version is up-to-date: mobile-status-bar@1.0.6
Local package version is up-to-date: mongo@1.1.2
Local package version is up-to-date: mongo-id@1.0.1
Local package version is up-to-date: npm-bcrypt@0.7.8_2
Local package version is up-to-date: npm-mongo@1.4.39_1
Local package version is up-to-date: observe-sequence@1.0.7
Local package version is up-to-date: ordered-dict@1.0.4
Local package version is up-to-date: promise@0.5.0
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: raix:onetimeout@1.0.4
Local package version is up-to-date: raix:stubfence@1.0.3
Local package version is up-to-date: random@1.0.4
Local package version is up-to-date: rate-limit@1.0.0
Local package version is up-to-date: reactive-dict@1.1.2
Local package version is up-to-date: reactive-var@1.0.6
Local package version is up-to-date: reload@1.1.4
Local package version is up-to-date: retry@1.0.4
Local package version is up-to-date: routepolicy@1.0.6
Local package version is up-to-date: service-configuration@1.0.5
Local package version is up-to-date: session@1.1.1
Local package version is up-to-date: sha@1.0.4
Local package version is up-to-date: spacebars@1.0.7
Local package version is up-to-date: spacebars-compiler@1.0.7
Local package version is up-to-date: srp@1.0.4
Local package version is up-to-date: standard-minifiers@1.0.1
Local package version is up-to-date: templating@1.1.4
Local package version is up-to-date: templating-tools@1.0.0
Local package version is up-to-date: tracker@1.0.9
Local package version is up-to-date: ui@1.0.8
Local package version is up-to-date: underscore@1.0.4
Local package version is up-to-date: urigo:angular-blaze-template@0.0.1
Local package version is up-to-date: urigo:cancel-fastclick@0.0.2
Local package version is up-to-date: url@1.0.5
Local package version is up-to-date: webapp@1.2.2
Local package version is up-to-date: webapp-hashing@1.0.5
Preparing Cordova project from app bundle    
Processing mobile-config.js                  
Copying resources for mobile apps            
Writing new config.xml                       
Preparing Cordova project for platform Android
                                             
WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the
         local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
Running Cordova app for platform Android with options --device
ANDROID_HOME=/home/wildan/Android/Sdk        \
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Running: /home/wildan/Project/Meteor_Practice/mdk2015/.meteor/local/cordova-build/platforms/android/gradlew cdvBuildDebug -b /home/wildan/Project/Meteor_Practice/mdk2015/.meteor/local/cordova-build/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true
Downloading http://services.gradle.org/distributions/gradle-2.2.1-all.zip
=> Started your app.                         
                                             
=> App running at: http://localhost:3000/    
    Starting app on android Device               /
{left it for 6 hours and nothing happened}

I forgot to mention i run it using meteor version 1.2 and http://localhost:3000 is working in my browser.
In mobile-config.js i added App.accessRule('http://192.168.42.128:3000/*'); but still no use.

Can anyone figure this out why and how to run it in correct way?

Regards.

**Comment by martijnwalraven** [comment]
Running on an Android device can be slow, but you shouldn't have had to wait 6 hours... Maybe you needed to accept the USB debugging key on the device? The Android tools can be a little flaky sometimes. Have you tried disconnecting and reconnecting the device and retrying?

You also mention you encounter compilation errors when configuring icons and launch screens. If that is still a problem, could you open an issue for that?

**Comment by justin-umesh** [comment]
create the AVD and launch the emulator manually, then run the 'meteor run android' it will launch the application very fast.

**Comment by crapthings** [comment]
@benjamn 

because download gradle is very slow.

Downloading http://services.gradle.org/distributions/gradle-2.2.1-all.zip

any possible to extract this manually ?

Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by crapthings** [comment]
works with starting a local http server 

export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=http://localhost/distributions/gradle-3.3-all.zip

https://stackoverflow.com/questions/37125496/cordova-build-changes-distributionurl-in-gradle-wrapper-properties-file
