### ISSUE TITLE
Can't install 3rd party Cordova packages.

### ISSUE THREAD

**Issue by codeHatcher** [meteor/meteor#5366]
With 1.2.0.2 I can't install 3rd party Cordova packages. Replicate as follows:
```bash
meteor add cordova:com.bunkerpalace.cordova.YoutubeVideoPlayer@https://github.com/Glitchbone/CordovaYoutubeVideoPlayer/tree/6019fa0f17138ee813dba609cd949e8f41db7854
```
```bash
meteor run ios
```
and you will get the following error, 
```
error: Meteor no longer supports installing Cordova plugins from arbitrary tarball URLs. You can either add a plugin from a Git URL
   with a SHA reference, or from a local path. (Attempting to install from
   https://github.com/Glitchbone/CordovaYoutubeVideoPlayer/tree/6019fa0f17138ee813dba609cd949e8f41db7854.)
```

**Comment by rfox90** [comment]
Try the git url version of the above: git@github.com:Glitchbone/CordovaYoutubeVideoPlayer.git

**Comment by martijnwalraven** [comment]
@rfox90 That won't work, because you'll need to specify a SHA reference.

Try `meteor add cordova:com.bunkerpalace.cordova.YoutubeVideoPlayer@https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git#6019fa0f17138ee813dba609cd949e8f41db7854`

**Comment by adriangordon1231** [comment]
This is a giant problem. I don't think I have ever completed a large cordova project without using at least one third party plugin.

**Comment by martijnwalraven** [comment]
@adriangordon1231 What is a problem? As far as I know, there are no issues with installing 3rd party plugins.

**Comment by codeHatcher** [comment]
@martijnwalraven that worked, thanks a bunch!
