### ISSUE TITLE
Package using ES6 "extends"

### ISSUE THREAD

**Issue by glyphing** [meteor/meteor#5367]
In a package I have the following three files (I'm using Meteor 1.2.0.2):

1) ```lib/wiki_common.js```:

```js
class WikiCommon {
  constructor(){
  }
  configure(conf) {

  }
}
```

2) ```lib/wiki_client.js```:

```js
class WikiClient extends WikiCommon {
  constructor(){
    super();
  }
}

let Wiki = new WikiClient();
```

3) ```lib/wiki_server.js```:

```js
class WikiServer extends WikiCommon {
  constructor(){
    super();
  }
}

let Wiki = new WikiServer();
```

But I get the following error:
```bash
W20151005-14:20:58.952(2)? (STDERR) TypeError: Super expression must either be null or a function, not undefined
W20151005-14:20:58.952(2)? (STDERR)     at Object.babelHelpers.inherits (packages/babel-runtime/packages/babel-runtime.js:80:1)
W20151005-14:20:58.953(2)? (STDERR)     at lib/wiki_server.js:1:17
W20151005-14:20:58.953(2)? (STDERR)     at Package (lib/wiki_server.js:1:17)
```

On the Babel web page [Try it out](https://babeljs.io/repl/) I get no warning / error.

What is wrong?

**Comment by glyphing** [comment]
I'm back with coffeescript and everything work fine.

**Comment by dcworldwide** [comment]
If defining classes in different files, i think you need to define each class as a global variable. I think this is a 1.2 limitation. Hoping the module work in 1.3 solves this

**Comment by timbotnik** [comment]
@dcworldwide is correct, the syntax (for the time being) looks like this:
```
WikiCommon = class WikiCommon {
```

**Comment by wraybowling** [comment]
I was having the same problem but thankfully I found notes I left for myself to copy from. There's a simple solution: You need to `export` your class for it to be extended. Also, this example is updated for the newer Meteor 1.3 which handles imports much more elegantly. But I think the same export rule applied in 1.2

1) /imports/wiki_common.js:
```javascript
export class WikiCommon {
  constructor(){
  }
  configure(conf) {
  }
}
```

2) /lib/wiki_client.js:
```javascript
import WikiCommon from '/imports/wiki_common.js';
class WikiClient extends WikiCommon {
  constructor(){
    super();
  }
}

let Wiki = new WikiClient();
```
