### ISSUE TITLE
Uncaught Error: Expected template or null, found: [object Object]

### ISSUE THREAD

**Issue by angjelo** [meteor/meteor#5368]
I installed bower and after polymer through bower .My html gets rendered twice and I do not know why...I took some screenshots that may help you to understand what is going on.
Thank you :)
![untitled](https://cloud.githubusercontent.com/assets/10425974/10291225/5a3ab55e-6b6e-11e5-89ff-ff38a4043a3e.png)

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

I can't understand things just through the screenshot like: what is the file structure, what packages are you using, etc.

**Comment by brylie** [comment]
Please add your support and comments regarding web component alignment in Blaze 2. See issue #6236.
