### ISSUE TITLE
Cordova file transfer issue

### ISSUE THREAD

**Issue by totorokk** [meteor/meteor#5371]
I've noticed that after the 1.2 update (may not be correlated though), file transfer for cordova app (both android and ios) has been problematic. Basically

1. Initial installation and launch: some public/ files are missing, sometimes even fontawsome package files. Also when e.g. an image `/assets/examples/f-avatar.jpg` is initially shown, changing a component state (using React) to toggle the image would result in `GET http://meteor.local/assets/examples/f-avatar.jpg net::ERR_NAME_NOT_RESOLVED` error, and the it's broken again on the page.
2. Kill and relaunch: app stuck at splash screen, no file is loaded (on android it seems to be endless loading/unloading plugins, so 'deviceready' is never fired). Only re-installation could bring it back.
3. When running on localhost, skip 2, modify some random code to trigger an HCP, all files are pushed to the phone successfully. There isn't a problem if re-launch. 

This issue is only seen on cordova app, both android and iOS. Pre-1.2-update this issue didn't exist for the same app. But I couldn't reproduce the issue using the 1.2 localmarket example, so not sure if there is a bug or just from misuse of some packages. I've researched on the previously known issues, like public assets with cordova and HCP, but they don't seem to be the same as this one. 

I've posted below some logs when the issue occurs on initial-launch. Basically they indicate that the files are not found, may not be very useful. Is there anything regarding cordova file transfer/load, e.g. file size, uri decode, etc, that we should pay attention to after the 1.2 update? 

```shell
# iOS XCode log when the file is not loaded
2015-10-04 10:55:16.685 MyApp[515:142123] METEOR CORDOVA DEBUG loading filepath: /var/mobile/Containers/Data/Application/A8CB210C-C64D-45FA-94E2-C5733ACB9342/Library/NoCloud/meteor/cbf43e25932646c39365e8b176ae2914c30e5ef4/ for path: %2Fassets%2Fexamples%2Ff-avatar.jpg

# Android device log
V/meteor.cordova.updater(11231): remapUri http://meteor.local/assets/examples/f-avatar.jpg
D/meteor.cordova.updater(11231): Unable to find http://meteor.local/assets/examples/f-avatar.jpg, will try http://meteor.local/index.html
```

**Comment by martijnwalraven** [comment]
Hmmm, I'm not sure what could be going on. 

One idea that comes to mind is that there might be a problem with `cordova-plugin-file-transfer`, which is used by the current version of Cordova hot code push. Have you also added the plugin directly to your app (`meteor add cordova:cordova-plugin-file-transfer@x.x`) by any chance? Because then an older version might have overwritten the one that is specified as a dependency of the `webapp` package, and that could somehow lead to trouble.

If this is not the case, is there any way you can send me your project (or preferably a minimal version of it that reproduces the issue), including the `.meteor/local` directory?

**Comment by totorokk** [comment]
@martijnwalraven Thanks for the tips. 

I didn't have another file transfer plugin. But anyway I hunted down the error and it was a wild one: somewhere in the lib/ folder, there is a line `if (!Meteor.settings.public.foo) Meteor.settings.public.foo = "foo"`. Removing that line would fix the file loading issue and everything is fine now. 

So I guess `Meteor.settings` and `Meteor.settings.public` are pre-defined ns by `__meteor_runtime_config__` and trying to forcibly set them in the app can cause unpredictable behaviors. If there is an official explanation from mgd, that'll be great.

**Comment by martijnwalraven** [comment]
Well, `Meteor.settings.public` is a predefined namespace, but you should be able to add properties to it. Not sure what specifically triggers your issue. Do you get any runtime errors with that line included?

**Comment by totorokk** [comment]
There was any other runtime error except the "ERR_NAME_NOT_RESOLVED" ones when files were not found. I also noticed that on an HCP, if the changes are client-only, the problem is gone, if they are client+server or server-only, the asset files are missing again. My guess is when server restarts, meteor and the app both try to reset the configs and maybe there is a race condition and some of the vars are messed up or even missing.

**Comment by martijnwalraven** [comment]
Have you tried putting the line in a `Meteor.startup` function?

**Comment by totorokk** [comment]
You are right, after moving that line into Meteor.startup, the issue is gone. 

Does this have anything to do with the cordova assets being moved out of the [`static-assets`](https://github.com/meteor/meteor/tree/devel/tools/static-assets) folder after rc19?

**Comment by martijnwalraven** [comment]
No, I think `Meteor.settings.public` has never been guaranteed to be defined before startup completes.

**Comment by totorokk** [comment]
Hmm.. Only when that line is put in `Meteor.isServer` block but not inside `startup`, there is an issue. If it's inside `startup` or just in `isClient/isCordova` (outside of `startup`), everything is fine. 

When the line is in server a code (`isServer` or `server/`) and outside of startup, it does get run before startup. But when it gets run, `Meteor.setting` is `{ public: {} } `. I've moved the isServer block to different files in `lib/` or `server/`, and `Meteor.settings.public` seems to be always defined before I try to set `Meteor.settings.public.foo = "foo"`. And when `isCordova` block is run, `public.foo` is set, but assets are missing on cordova (not on web).

Also, if I don't set `public` but rather none-public settings like `Meteor.settings.bar`, it's also fine no matter where I put it. 

The action plan is easy, just to use a settings.json file or only set it on the client or in the server `startup` callback (although it doesn't make much sense to set `public` on server). But I still don't quite get why it may cause assets missing and how...
