### ISSUE TITLE
meteor/stylus crashes (surprising path) when trying to import nib

### ISSUE THREAD

**Issue by swestgate** [meteor/meteor#5372]
**_3 Upvotes**_ I've run into an issue where including `@import 'nib'` in my main .styl file causes meteor to crash (detailed error below). I suspect this may be related to the fact that I'm running Windows with two drives, C: holds the OS and my profile, but D: holds most program files and is where I develop my meteor projects. It looks like the path to nib's support files isn't properly accounting for the drive letter.

Note: the error below chokes on reset.styl because I have `global-reset()` right after the import statement. Without it I get the same error, but with the vendor.styl file instead.

```
=> Errors prevented startup:

   While processing files with stylus (for target web.browser):

   C:\Users\myuser\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13:
   Surprising path:
   /Users/myuser/AppData/Local/.meteor/packages/stylus/2.511.0_2/plugin.compileStylusBatch.os/npm/compileStylusBatch/node_modules/nib/lib/nib/reset.styl
   at toDosPath
   (C:\Users\myuser\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:34:13)
   at Object.convertToOSPath
   (C:\Users\myuser\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:47:12)
   at Object.wrapper (C:\tools\fs\files.js:1310:25)
   at importer.readFile (plugin/compile-stylus.js:119:21)
   at Array.map (native)
   at processSourcemap (plugin/compile-stylus.js:139:52)
   at StylusCompiler.compileOneFile (plugin/compile-stylus.js:169:23)
   at multi-file-caching-compiler.js:115:45
   at multi-file-caching-compiler.js:144:68
   at
   C:\Users\myuser\AppData\Local\.meteor\packages\stylus\2.511.0_2\plugin.compileStylusBatch.os\npm\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\myuser\AppData\Local\.meteor\packages\stylus\2.511.0_2\plugin.compileStylusBatch.os\npm\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\myuser\AppData\Local\.meteor\packages\stylus\2.511.0_2\plugin.compileStylusBatch.os\npm\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\myuser\AppData\Local\.meteor\packages\stylus\2.511.0_2\plugin.compileStylusBatch.os\npm\caching-compiler\node_modules\async\lib\async.js:221:35)
   at StylusCompiler.processFilesForTarget (multi-file-caching-compiler.js:95:11)


=> Your application has errors. Waiting for file change.
```

**Comment by claudiutraistaru** [comment]
I encounter the same issue on a newly installed meteor 1.2.0.2 on windows. let us know  if you need further details.
Below is the list of packages used in my project :
accounts-base                     1.2.1  A user account system
accounts-facebook                 1.0.6  Login service for Facebook accounts
accounts-google                   1.0.6  Login service for Google accounts
accounts-password                 1.1.3  Password support for accounts
accounts-twitter                  1.0.6  Login service for Twitter accounts
accounts-ui                       1.1.6  Simple templates to add login widgets to an app
aldeed:autoform                   5.5.1* Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2                2.5.0  Automatic validation of insert and update operations on the client and server.
anti:i18n                         0.4.3  Internalization: simplest package
autopublish                       1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates              1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                             1.0.6  Check whether a value matches a pattern
dburles:collection-helpers        1.0.3  Transform your collections with helpers that you define
ejson                             1.0.7  Extended and Extensible JSON library
fortawesome:fontawesome           4.4.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
gildaspk:autoform-materialize     0.0.25  Materialize theme for Autoform
insecure                          1.0.4  (For prototyping only) Allow all database writes from the client
iron:router                       1.0.9  Routing specifically designed for Meteor
jquery                            1.11.4  Manipulate the DOM using CSS selectors
logging                           1.0.8  Logging facility.
materialize:materialize           0.97.0* Materialize (official): A modern responsive front-end framework based on Material Design
meteor-base                       1.0.1  Packages that every Meteor app needs
mobile-experience                 1.0.1  Packages for a great mobile user experience
momentjs:moment                   2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                             1.1.2  Adaptor for using MongoDB and Minimongo over DDP
mysport:lolliclock                0.2.1+ A material design timepicker based on clockpicker
mysport:useraccounts:materialize  1.12.3+ Accounts Templates styled for Materialize Css.
pfafman:materialize-modal         0.4.0  Display a modal via Materialize written in coffeescript
random                            1.0.4  Random number generator and utilities
react                             0.1.13  Everything you need to use React with Meteor.
reload                            1.1.4  Reload the page while preserving application state.
rzymek:moment-locales             2.9.0  Moment.js all locales. Companion package for momentjs:moment
sacha:spin                        2.3.1  Simple spinner package for Meteor
service-configuration             1.0.5  Manage the configuration for third-party services
session                           1.1.1  Session variable
softwarerero:accounts-t9n         1.1.4  Almost i18n, with standard translations for basic meteor packages.
spacebars                         1.0.7  Handlebars-like template language for Meteor
standard-minifiers                1.0.1  Standard minifiers used with Meteor apps by default.
tracker                           1.0.9  Dependency tracker to allow reactive callbacks
useraccounts:iron-routing         1.12.3  UserAccounts package providing routes configuration capability via iron:router.
yasaricli:slugify                 0.0.7  Remove special characters from a string

**Comment by claudiutraistaru** [comment]
Hi Guys,

The above I was getting when using meteor 1.2.0.2 on a Windows 10 x64 , I`ve installed it also on Windows 7 x64 and it works as expected, I will try to reinstall , maybe something went wrong on the installation.

**Comment by claudiutraistaru** [comment]
I have tried reinstalling on Windows 10 and also I have tested on another computer with Windows 10 , same error on the project . I will try to add packages one by one so I could see witch one has the problem , the todos example project works ok so there could be a package that is having issues.

**Comment by remindme74** [comment]
+1 Have the same issue at win8 x64

**Comment by redreamality** [comment]
+1 same issue, winserver 2012 x64

**Comment by claudiutraistaru** [comment]
I discovered that removing the @import 'nib' in the lolliclock     package did the trick , but this is not a long term solution  and it should be addressed.

**Comment by stubailo** [comment]
OK I think I know what the issue is, and I've opened a PR for the fix. Unfortunately I don't have a good way of testing this at the moment!

If someone could try running this from that branch on Windows and let me know if it works, that would be awesome!

**Comment by swestgate** [comment]
I've tested it, and I think we're closer. I've commented on your commit.

**Comment by claudiutraistaru** [comment]
Hi, If you could provide some steps on how to install that specific branch on windows I would test also.

**Comment by eraazana** [comment]
+1 Yeah, got the same issue.  win8.1 x64

**Comment by ForNeVeR** [comment]
I have the same problem. A temporary workaround is to deploy the project on `C:` drive. Thanks goes to @swestgate for helping me to figure that out.

**Comment by hwillson** [comment]
It looks like PR #5418 (the original solution to this issue) was never merged. That being said, there hasn't been any activity on this issue in a while, so as part of the on-going old issue cleanup process, I'll close it for now. If anyone still has this problem using the latest version of Meteor, please post back and I'll re-open this issue. Thanks for posting this originally!

**Comment by coagmano** [comment]
Came across this issue on a Windows machine with Meteor installed on C: and project folder on D:

Adding the patch in PR 5418 to a local copy fixed the issue immediately. Also added the fix to coagmano:stylus

Ended up moving the project to C: anyway because of other issues.

Just a FYI for future googlers

**Comment by rickywu** [comment]
@entrptaher  I have Meteor 1.6 still has this problem, have to move project to C:\

**Comment by sarlongda** [comment]
I tried to install wekan on windows 10 and I was getting above errors.
I followed install steps exactly.
My we can version is 1.6. 
When can this problem be solved?

**Comment by coagmano** [comment]
@sarlongda Well since `stylus` has been deprecated in favour of community packages, your best bet will be moving to one of them. The specific fix mentioned in this thread is implemented in `coagmano:stylus`
https://atmospherejs.com/coagmano/stylus

**Comment by Saniok88** [comment]
Had the same issue on windows 7.
To install wekan from scratch (in my case i had choco, git, nodejs already installed), just use that bat file (rebuild-wekan.bat) from the root of wekan folder. You need to prepare space on disk "C" (bat already specifies where to download (git clone) wekan, its in the "C:/repos"  (/wekan), then the compilation and running will not work, but at least the "meteor" will work. (sometime it reports errors with stylus, but then close cmd, open it in wekan directory and try "meteor" again, next time it may work.

**Comment by Saniok88** [comment]
Had the same issue on windows 7, but eventually it started succesfully.

To install wekan from scratch (in my case i had choco, git, nodejs already installed), just use that bat file (rebuild-wekan.bat) from the root of wekan folder. You need to prepare space on disk "C" (bat already specifies where to download (git clone) wekan, its in the "C:/repos" (/wekan), then the compilation and running will not work, but at least the "meteor" will work. (sometime it reports errors with stylus, but then close cmd, open it in wekan directory and try "meteor" again, next time it may work.

important notes:
1) disk C is necessary, it will not work from D (afaik)
2) bat file works well with the current version as of today.
