### ISSUE TITLE
Meteor build android fails after update to 1.2

### ISSUE THREAD

**Issue by tdamsma** [meteor/meteor#5373]
After upgrade to 1.2, I am running into issues building the android app. Since I have no experience building apps for android I don't really no what the errors mean. Before meteor 1.2 it just worked.

I set-up a fresh VM with ubuntu 14.04.03 desktop, installed meteor and myApp which runs fine. Then I followed the instructions [here](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux) to install Android SDK Platform API 22. 

It seems it is possible to pass options to the compiler to ignore lint errors, but where to put these? (I don't really care about the translations not being correct, my target audience is English only)

The only Cordova package used is phonegap-plugin-barcodescanner@4.0.2, though the following are defined in fetch.json due to package dependencies:

    cordova-plugin-console@1.0.1
    cordova-plugin-device@1.0.1
    cordova-plugin-legacy-whitelist@1.1.0
    cordova-plugin-statusbar@1.0.0
    cordova-plugin-splashscreen@2.1.0
    cordova-plugin-file@2.1.0
    cordova-plugin-file-transfer@1.2.0
    phonegap-plugin-barcodescanner@4.0.2

Anyways, I run meteor build andoird and this is the result

    v@v-VirtualBox:~/myapp$ meteor build android --server myserver
    Currently, it is only possible to build iOS apps on an OS X system.
                                                  
    WARNING: The output directory is under your source tree.
                                                  
    => Errors executing Cordova commands:         
                                                  
       While building Cordova app for platform Android:
       Error: /home/v/myapp/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit code 8 Error output:
       Note: Some input files use or override a deprecated API.
       Note: Recompile with -Xlint:deprecation for details.
       warning: string 'menu_settings' has no default translation.
       Note: Some input files use or override a deprecated API.
       Note: Recompile with -Xlint:deprecation for details.
       Note: Some input files use unchecked or unsafe operations.
       Note: Recompile with -Xlint:unchecked for details.
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values/arrays.xml:3: Error: "country_codes" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca"
       (Catalan), "cs" (Czech), "da" (Danish), "de" (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu"
       (Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish), "pt" (Portuguese), "ru" (Russian), "sk" (Slovak),
       "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
       <string-array name="country_codes">
       ~~~~~~~~~~~~~~~~~~~~
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values/strings.xml:3: Error: "app_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca"
       (Catalan), "cs" (Czech), "da" (Danish), "de" (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu"
       (Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish), "pt" (Portuguese), "ru" (Russian), "sk" (Slovak),
       "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
       <string name="app_name">myapp</string>
       ~~~~~~~~~~~~~~~
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values/strings.xml:4: Error: "launcher_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca"
       (Catalan), "cs" (Czech), "da" (Danish), "de" (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu"
       (Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish), "pt" (Portuguese), "ru" (Russian), "sk" (Slovak),
       "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
       <string name="launcher_name">@string/app_name</string>
       ~~~~~~~~~~~~~~~~~~~~
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values/strings.xml:5: Error: "activity_name" is not translated in "ar" (Arabic), "bg" (Bulgarian), "ca"
       (Catalan), "cs" (Czech), "da" (Danish), "de" (German), "el" (Greek), "es" (Spanish), "eu" (Basque), "fi" (Finnish), "fr" (French), "he" (Hebrew), "hi" (Hindi), "hu"
       (Hungarian), "id" (Indonesian), "it" (Italian), "iw" (Hebrew), "ja" (Japanese), "ko" (Korean), "nl" (Dutch), "pl" (Polish), "pt" (Portuguese), "ru" (Russian), "sk" (Slovak),
       "sl" (Slovene), "sv" (Swedish), "tr" (Turkish), "zh-rCN" (Chinese: China), "zh-rTW" (Chinese: Taiwan, Province of China) [MissingTranslation]
       <string name="activity_name">@string/launcher_name</string>
       ~~~~~~~~~~~~~~~~~~~~
       
       Explanation for issues of type "MissingTranslation":
       If an application has more than one locale, then all the strings declared
       in one language should also be translated in all other languages.
       
       If the string should not be translated, you can add the attribute
       translatable="false" on the <string> element, or you can define all your
       non-translatable strings in a resource file called donottranslate.xml. Or,
       you can ignore the issue with a tools:ignore="MissingTranslation"
       attribute.
       
       By default this detector allows regions of a language to just provide a
       subset of the strings and fall back to the standard language strings. You
       can require all regions to provide a full translation by setting the
       environment variable ANDROID_LINT_COMPLETE_REGIONS.
       
       You can tell lint (and other tools) which language is the default language
       in your res/values/ folder by specifying tools:locale="languageCode" for
       the root <resources> element in your resource file. (The tools prefix
       refers to the namespace declaration http://schemas.android.com/tools.)
       
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-ar/strings.xml:64: Error: "menu_settings" is translated here but not found in default locale
       [ExtraTranslation]
       <string name="menu_settings">إعدادات</string>
       ~~~~~~~~~~~~~~~~~~~~
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-bg/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-ca/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-cs/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-da/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-de/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-el/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-es/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-eu/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-fi/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-fr/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-he/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-hi/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-hu/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-id/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-it/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-iw/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-ja/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-ko/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-nl/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-pl/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-pt/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-ru/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-sk/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-sl/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-sv/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-tr/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-zh-rCN/strings.xml:64: Also translated here
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/res/values-zh-rTW/strings.xml:64: Also translated here
       
       Explanation for issues of type "ExtraTranslation":
       If a string appears in a specific language translation file, but there is
       no corresponding string in the default locale, then this string is probably
       unused. (It's technically possible that your application is only intended
       to run in a specific locale, but it's still a good idea to provide a
       fallback.).
       
       Note that these strings can lead to crashes if the string is looked up on
       any locale not providing a translation, so it's important to clean them
       up.
       
       5 errors, 0 warnings
       
       FAILURE: Build failed with an exception.
       
       * What went wrong:
       Execution failed for task ':lintVitalRelease'.
       > Lint found fatal errors while assembling a release target.
       
       To proceed, either fix the issues identified by lint, or modify your build script as follows:
       ...
       android {
       lintOptions {
       checkReleaseBuilds false
       // Or, if you prefer, you can continue to check for errors in release builds,
       // but continue the build even when errors are found:
       abortOnError false
       }
       }
       ...
       
       * Try:
       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
       
       /home/v/myapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
       throw e;
       ^
       Error code 1 for command: /home/v/myapp/.meteor/local/cordova-build/platforms/android/gradlew with args:
       cdvBuildRelease,-b,/home/v/myapp/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
       at ChildProcess.whenDone
       (/home/v/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
       at ChildProcess.emit (events.js:98:17)
       at maybeClose (child_process.js:766:16)
       at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by martijnwalraven** [comment]
It seems this is a [known issue](https://github.com/wildabeast/BarcodeScanner/issues/276) with the `phonegap-plugin-barcodescanner` (see also [here](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/80)).

As a workaround, you can disable linter errors by adding a `build-extras.gradle` file in `<projectdir>/cordova-build-override/platforms/android` with the following contents:
```
android {
  lintOptions {
      disable 'MissingTranslation'
      disable 'ExtraTranslation'
  }
}
```

**Comment by martijnwalraven** [comment]
(Also note that the argument to `meteor build` is not the platform to build, but the directory to put the build products in. So usually you'll want to specify something like `../build` instead of the `android` you currently have.)

**Comment by tdamsma** [comment]
Great, this works, thanks! I did run into another smaller issue:
First i successfully built the app after I added `<projectdir>/cordova-build-override/platforms/android`, but when I tried this in a fresh install, this fails due to 
```Cordova error: The provided path                                                
   "<projectdir>/.meteor/local/cordova-build/platforms/android" is not an Android project.```
So apparently first the contents of `cordova-build-override` is copied to 
`<projectdir>/.meteor/local/cordova-build`. Cordova then checks if this is a valid direcory which it is not yet. If the directory hadn't existed yet, then it would be generated without problems. So the question then is what defines a valid Android project, and must all these files be put in `<projectdir>/cordova-build-override/platforms/android`?

**Comment by martijnwalraven** [comment]
Did you run `meteor add-platform android` for the new project? Cordova should create the `platforms/android` directory when preparing for build.

**Comment by tdamsma** [comment]
No I didn't as android is already added to the platforms. I thought it was ok to delete the `/.meteor/local` folder to clear all cache but apparently not, as this worked until I added the `cordova-build-override` folder

**Comment by Exilz** [comment]
If you want to clear the cache, just use `meteor reset`.
By the way, could you tell me if the content of `cordova-build-override` is actually copied into the cordova build ?
It used to work for me before 1.2 but it just doesn't now.

**Comment by tdamsma** [comment]
For the `build-extras.gradle` file I can confirm that it is copied to `projectdir>/cordova-build-override/platforms/android`

**Comment by Exilz** [comment]
Ok nevermind, it's not that Meteor doesn't override, it's because of xcode. Once I meteor run ios-device, it puts the overriden files back to their original...
I don't know if I should open another issue, it might not be of your resort.

**Comment by kartikTT** [comment]
@tdamsma Were you able to resolve this issue? After adding the build-extras.gradle file I keep getting the same "The provided path [path] is not an Android project. 

Tried doing meteor run android-device before building so that the directory would be set up - but then meteor build does not result in any .apk file as expected in the build-path/android directory.
