### ISSUE TITLE
[Blaze] Possible error when printing an array with undefined values

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#5374]
**_1 Upvote**_ Hi, I don't know if it's expected behavior. Let's say we have a following array that we want to pass to the template.

``` js
Template.body.helpers({
  values: function() {
    var array = [];
    array[9] = 9;
    return array;
  }
});
```

and the template:

``` hbs
<body>
  {{#each values}}
    <div>{{@index}}: {{this}}</div>
  {{/each}}
</body>
```

As a result I will get the following HTML code:

``` html
<body>
  <div>0: 9</div>
</body>
```

I would expect to print 10 indexes from 0 to 9 and the 9 value under the index 9 not 0 like it's now.
Here is a reproduction repository: https://github.com/jagi/meteor-array-error

EDIT:
I've noticed that it may probably be caused by `underscore` being in version 1.5.2 instead of the newest 1.8.3. They differ in how the `_.each` method works. The newest one iterates over an array in the correct way, however 1.5.2 omits undefined values. And I assume that you are using the `_.each` method to iterate arrays.

**Comment by timbotnik** [comment]
Thanks for the reproduction, seems like this is probably not the right behavior.

**Comment by stubailo** [comment]
This is somewhat unfortunate, but it doesn't seem like a critical issue to me, especially if the fix is upgrading underscore I don't think this particular bug would make or break that switch.

**Comment by jagi** [comment]
Are you planning to upgrade underscore soon?

**Comment by stubailo** [comment]
No, there are currently no plans to do so. It's hard to say what the effects of that change could be, but I personally think it would be worth it.

**Comment by rpierreye** [comment]
I am running into the same issue... if the fix would be indeed upgrading underscore, I think it's worth doing.

**Comment by daltonrenaldo** [comment]
I am running into the same issue... if the fix would be indeed upgrading underscore, I think it's worth doing.

**Comment by chrisbutler** [comment]
+1

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#203 - closing here. Thanks!
