### ISSUE TITLE
Meteor.loginWithPassword give error Exception while invoking method 'login' Error: setUserId must be called on string or null, not object

### ISSUE THREAD

**Issue by bipin244** [meteor/meteor#5375]
I have add user using custom account ui and i have pass id as ObjectId so it give error like this Exception while invoking method 'login' Error: setUserId must be called on string or null, not object

Any idea how it solve.....

**Comment by stubailo** [comment]
DDP and Meteor Accounts only support string IDs. There's a very very lengthy discussion here: https://github.com/meteor/meteor/issues/1834
