### ISSUE TITLE
Upgrade to 1.2.0.2 from 1.1.x

### ISSUE THREAD

**Issue by suryaiiit** [meteor/meteor#5377]
I'm running into the below issues when I upgraded to 1.2.0.2

Uncaught ReferenceError: SimpleSchema is not defined
Uncaught ReferenceError: AccountsTemplates is not defined
Uncaught ReferenceError: Meteor is not defined
Uncaught ReferenceError: Template is not defined

I'm not sure how to fix this, please suggest.

Thanks.

The below is my packages files:
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library
logging
reload
random
ejson
check

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

underscore
iron:router
spacebars
less
materialize:materialize
useraccounts:materialize
useraccounts:core
aldeed:collection2
aldeed:autoform
gildaspk:autoform-materialize
accounts-password
alethes:pages
matb33:collection-hooks
alanning:roles
meteorhacks:aggregate
momentjs:moment
pcel:serialize
pcel:loading

aldeed:simple-schema
digilord:faker
meteorhacks:kadira

useraccounts:flow-routing
sacha:spin

**Comment by mitar** [comment]
Please provide a full reproduction: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor

**Comment by stubailo** [comment]
Yeah, I'd say try deleting all of the temporary files in your Meteor directory as described here: https://github.com/meteor/meteor/issues/5328#issuecomment-147850621
