### ISSUE TITLE
Using cordova contacts plugin with Meteor 1.2.0

### ISSUE THREAD

**Issue by shantanubhadoria** [meteor/meteor#5379]
I followed the instructions [here](https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration) and ran the following commands to get cordova contacts package which lets you get list of contacts from a phone.

    $ meteor add cordova:org.apache.cordova.contacts@1.1.0
    Added Cordova plugin cordova-plugin-contacts@1.1.0 (plugin has been renamed as
    part of moving to npm).

Then I put following in lib/startup.js

    Meteor.startup(function(){
      console.log(navigator.contacts);
    });

However I get this error when I run it all on a android emulator : 

    W20151007-13:36:08.149(8)? (STDERR)           
    W20151007-13:36:08.150(8)? (STDERR) /home/shantanu/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
    W20151007-13:36:08.150(8)? (STDERR) 						throw(ex);
    W20151007-13:36:08.150(8)? (STDERR) 						      ^
    W20151007-13:36:08.151(8)? (STDERR) ReferenceError: navigator is not defined
    W20151007-13:36:08.151(8)? (STDERR)     at setup.js:2:15
    W20151007-13:36:08.151(8)? (STDERR)     ~/meteor/.meteor/local/build/programs/server/boot.js:249:5

I would appreciate any help or guidance on what I might be doing wrong if this is not a case of something broken in meteor docs.
Thanks

**Comment by martijnwalraven** [comment]
I think the issue is that you are running the code in `lib/startup.js` on both client and server, and `navigator` is an object only available on the client. You'll want to put in `client' instead (or use `Meteor.isClient`).

**Comment by shantanubhadoria** [comment]
Thanks for that. I just put it in isClient and the error is gone but console.log(navigator.contacts) doesn't show anything anymore. Any ideas?

**Comment by shantanubhadoria** [comment]
Meteor.startup(function(){
  if(Meteor.isClient) {
    console.log('blah');
    console.log(navigator.contacts.find());
    conts = navigator.contacts.find();
  }
});

**Comment by martijnwalraven** [comment]
From the [plugin documentation](https://github.com/apache/cordova-plugin-contacts) it seems the `find()` call is asynchronous, so you'll have to pass it callbacks instead of expecting a function result.

**Comment by shantanubhadoria** [comment]
Just figured it out. Thanks for your help!
cheers!

**Comment by shantanubhadoria** [comment]
To help out anyone facing the same issue, I used the following code to get all the contacts:
    
    var options = new ContactFindOptions();
    options.filter = "";
    options.multiple = true;
    var fields = ["displayName", "name"];
    vm.contacts = navigator.contacts.find(fields, onSuccess, onError, options);

    function onSuccess(contacts) {
      console.log(contacts.length + 'contacts');
      for (var i = 0; i < contacts.length; i++) {
        console.log("Display Name = " + contacts[i].displayName);
      }
    }

    function onError(contactError) {
      console.log('onError!');
    }

**Comment by evanglerm** [comment]
Hi Can you share more details. I am trying to do same thing but I eep getting error 
"ContactFindOptions" not defined. 

Do we have restrictions as in 
1. It can run only on emulator or device. 
2. Is there any other settigs required other than adding cordova package.

**Comment by evanglerm** [comment]
Can you elaborate a little more. Where you have run this ( emulator/device/web). 
Did you use isCordova as well ? 
Not able to get it right. Not getting the Contacts still. { I am very new to Coding it self, but got many other things working. }
Not sure if 
1 . It does not work on emulator ( IOS) 
2. I missed anything in Setting. I just added cordova packges.

**Comment by evanglerm** [comment]
Hi shantanubhadoria , 
Can you tell me where did u see your log statement? 
Did u enclose it in "if(Meteor.isCordova) " to make sure that it runs on mobile phones only ? 

Thanks

**Comment by shantanubhadoria** [comment]
Sorry for the slow reply.
I ran it on a nexus 6(not emulator) it runs fine if the list of contacts is not long(i.e in a emulator usually).
I used isCordova.

**Comment by evanglerm** [comment]
One last thing where did u see your log prints ? 

Thanks for response.
