### ISSUE TITLE
Throw error if cursor is returned from a method

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#5382]
**_1 Upvote**_ repro here: https://github.com/peonmodel/adamant-waffle

basically is a server side meteor method is returning a cursor, the client side callback will not get called at all

```
    Meteor.methods({
            'test': function(obj){
                obj.fakefield += 1;
                delete obj._id;
                var id = TestCollection.insert(obj);
                var insert = TestCollection.find(id);  // <<< this line!
                return insert;
            }
        });
```

```
Meteor.call('test', previous, function(error, result){
                console.log('callback')  // will not get called
                if (error){
                    console.log(error)  // nor here
                } else {
                    console.log(result)  // nor here
                }
            })
```

it doesnt quite make sense to return a cursor from a method, but it is an easy mistake to make mistyping 'findOne' as 'find'
i would expect the error callback to get triggered instead of failing silently

**Comment by stubailo** [comment]
Is there any error on the server?

**Comment by peonmodel** [comment]
no, in the example i have posted, i didn't receive any error on the server,
i had just double checked, it fails silently on both client and server side

**Comment by juniobranco** [comment]
+1 Same here.. findOne() returns triggers the callback but returning a cursor ( using find() ) there is no callback triggered.

**Comment by peonmodel** [comment]
No, i did not, still awaiting a reply from the meteor team
I just take note to not return the cursor from a meteor method

**Comment by juniobranco** [comment]
@peonmodel right.. I went for the same approach, if I need to return a cursor, I will do it in the helper itself.

Hopefully this gets fixed soon. I tried to find the source code for the method call but so far haven't found it

**Comment by stubailo** [comment]
Yeah, returning a cursor from a method should throw an error, since cursors are not serializable.

**Comment by zol** [comment]
Can someone confirm that returning anything that is non-serializable results in a silent error?

**Comment by zol** [comment]
@peonmodel I can't access your repro

**Comment by peonmodel** [comment]
@zol i created a new repo: https://github.com/peonmodel/musical-journey

**Comment by zol** [comment]
Thanks!

**Comment by zbyte64** [comment]
Still an issue with meteor 1.4.2.1

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Throw%20error%20if%20cursor%20is%20returned%20from%20a%20method&body=Migrated%20from:%20meteor/meteor%235382) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
