### ISSUE TITLE
`meteor update` with a specific package fails silently outside of project directories

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#5384]
```shell
mkdir notmeteor
cd notmeteor
meteor update gridio:babel
```

Expected output: `update: You're not in a Meteor project directory.`

Actual output: none.

**Comment by stubailo** [comment]
Looks like a subtle issue. Shouldn't be too hard to fix, probably somewhere in https://github.com/meteor/meteor/blob/81c4a7ce665770160c1e69b4fb004d1119dd8ebc/tools/cli/commands-packages.js#L1221
