### ISSUE TITLE
Meteor install script shouldn't use --progress or redirect stdout.

### ISSUE THREAD

**Issue by luisatlive** [meteor/meteor#5385]
The install meteor script downloads a tarball with --progress enabled, which is overflowing our Travis-CI build logs when network is slow. Can we remove --progress from the script? Also unsure why it redirects all stdout to stderr...

Our command:
curl -s https://install.meteor.com

From Travis support:
What I'm seeing in the meteor installer script is that the tarball is being downloaded with `--progress`, which is likely resulting in a lot of control characters going to the log, which is resulting in log output overflow (https://gist.github.com/meatballhat/0ca2951be5901f95c805#file-meteor-installer-sh-L121).

**Comment by zol** [comment]
@glasser and I have spoken and agree that not all of `stdout` needs to be redirected to `stderr`. Currently it is because it turns out 90% of output is error related, and it's not possible to easily achieve the opposite (i.e output to `stderr` by default and only deliberately output to `stdout` sometimes).

We should:

1. Only log errors to `stderr` and info to `stdout`.
2. Add a `--quiet` command line flag that removes `stdout` output and the `--progress` flag to curl.

**Comment by skaag** [comment]
I can see this is labeled as 'planned' which is great, I just hope this happens soon. We automate Meteor installs on our VM's and it would be lovely to not have to see the billion line output of the progress bar trying to draw itself into stdout... ;-)

Thanks for a great job guys!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20install%20script%20shouldn't%20use%20--progress%20or%20redirect%20stdout.&body=Migrated%20from:%20meteor/meteor%235385) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
