### ISSUE TITLE
Need better error message for google accounts handshake invalid_client secret

### ISSUE THREAD

**Issue by jeremyjs** [meteor/meteor#5388]
I had the wrong client secret configured for google accounts, but got the following error server-side when I tried to connect:

```
W20151008-08:10:35.659(9) (oauth.js:406) Error in OAuth Server: Failed to complete OAuth handshake with Google. failed [401] {   "error" : "invalid_client" }
I20151008-08:10:36.534(9)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. failed [401] {   "error" : "invalid_client" }
I20151008-08:10:36.535(9)?     at getTokens (meteor://💻app/packages/google/google_server.js:59:1)
I20151008-08:10:36.535(9)?     at Object.ServiceConfiguration.configurations.findOne.service [as handleOauthRequest] (meteor://💻app/packages/google/google_server.js:10:1)
I20151008-08:10:36.535(9)?     at OAuth._requestHandlers.(anonymous function) (meteor://💻app/packages/oauth2/packages/oauth2.js:16:1)
I20151008-08:10:36.536(9)?     at middleware (meteor://💻app/packages/oauth/packages/oauth.js:181:1)
I20151008-08:10:36.536(9)?     at meteor://💻app/packages/oauth/packages/oauth.js:154:1
```

I ended up googling around for solutions for about an hour and a half before I discovered the real issue. It would be amazing if the accounts-google or service-configuration package could just tell me I've likely provided an incorrect clientId. Some low hanging fruit to make meteor accounts a bit more developer friendly.

**Comment by tmeasday** [comment]
This sounds reasonable (if it's easy to detect, although perhaps it possible google are ambigious here?). We'd accept a PR for this.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Need%20better%20error%20message%20for%20google%20accounts%20handshake%20invalid_client%20secret&body=Migrated%20from:%20meteor/meteor%235388) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
