### ISSUE TITLE
Android SDK Install on Debian Linux Server

### ISSUE THREAD

**Issue by JohnHanks** [meteor/meteor#5389]
I followed the tutorial but when I tell my meteor app to build it tells me the Android SDK is not installed.  How can I debug this? I have the 22 API instead of 23 from the SDK manager.  I have java (openjdk) installed and added to my path.  I wish the errors in meteor said a little more so I could troubleshoot this myself

:pray:

**Comment by martijnwalraven** [comment]
This might be the same issue as https://github.com/meteor/meteor/issues/5358 (which seems to have a fix).

Unfortunately, the error messages are generated by Cordova so there is not much we can do about them on the Meteor side. I'm planning on working with the Cordova project to improve the platform installation experience however.
