### ISSUE TITLE
register multiple compilers for same extension not allowed

### ISSUE THREAD

**Issue by faceyspacey** [meteor/meteor#5390]
I'm trying to use the ```ecmascript``` package and my own compiler (via ```Plugin.registerCompiler()```) to programmatically make edits to any ```.js``` file, but I'm getting this error:

````
error: conflict: two packages included in the app (ecmascript and my:package) are both trying to handle *.js
````

It seems my only option is to essentially fork the ecmascript package and make a version that does both what the ecmascript package originally does and what my compiler does. I'm doing very basic stuff--if there is no plan to support multiple compilers for the same extension, is there another recommended way to programmatically alter code?

**Comment by stubailo** [comment]
What alterations are you trying to make?

On the surface level, the answer is yes, there is no way to do this currently. There's already an open thread about a similar idea: https://github.com/meteor/meteor/issues/5219
