### ISSUE TITLE
Unexpected order of onInvalidate callbacks

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5396]
If an `onInvalidate` callback function calls `onInvalidate` by itself, the function is immediately called.

So for code something like this:

```javascript
var c = Tracker.autorun(function () {});
c.onInvalidate(function () {
  console.log("a");
  c.onInvalidate(function () {
    console.log("d");
  });
  console.log("b");
});
c.onInvalidate(function () {
  console.log("c");
});
c.invalidate();
```

Prints: adbc

When one would expect: abcd

The `onInvalidate` callbacks should be called in the order they were registered, no?

**Comment by zimme** [comment]
@mitar Here's a part of the `onInvalidate` docs
>, or runs it immediately if the computation is already invalidated.

Which leads me to expect the current behaviour.

**Comment by mitar** [comment]
Yes, this is probably OK when you call `onInvalidate` from outside, but if you are from `onInvalidate` it behaves unexpectedly.

**Comment by zimme** [comment]
I see your point, but it says it's gonna be called immediately if the computation is invalidated already, and when you are in side a `onInvalidate` function it's already invalidated and I would expect the new `onInvalidate` to run when registered as per the docs.

but I could see the use of having it run in the order it was registered too.

**Comment by zimme** [comment]
But I think I would expect that when registering a new `onInvalidate` from inside a `onInvalidate` it would run the next time the computation was invalidated.

**Comment by mitar** [comment]
Yes, I am not saying that it is against the docs. :-) Just that I think that this behavior is unexpected from inside `onInvalidated`. That there might have to be some special handling.

**Comment by tmeasday** [comment]
@mitar I'm not sure why this is unexpected. I think a lot of `onXs` work this way (if X has already happened, it runs immediately). Is this a Zalgo situation you are worried about (i.e. it should `setTimeout(0)` or something)?

Why would you want to do this though? I'm closing this as I can't see us changing it.

**Comment by mitar** [comment]
It is unexpected because it is not in the order of  how `onX` were/are called.

So if computation is stopped and you call `onStop` it is pretty clear that it should run immediately. But then the order is clear: probably all `onStop` callbacks were already called, so your call will call after them. So the order is the expected one.

The open question is what happens when you call `onStop` while in `onStop`. I would claim that in that case call should be put after all existing `onStop` callbacks.

**Comment by tmeasday** [comment]
@mitar I think you'll find that the same thing happens with `onStop`. Did you try it?

Again, why would you ever want to do this?

**Comment by mitar** [comment]
Yes, I know that it happens the same. But I was using stop example because it is clearer (stop happens only once, while with invalidation you have also the issue of invalidation happening in meantime).

The issue here is just to prevent strange bugs from occurring once this calls are nested in the middle of the rest of the framework. I was just looking in reasons why callbacks something happens in different order and was looking at the code and found a possible issue. I do not have a reproduction sadly. So this is for me just a general comment that it would be great if this would be more predictable.

**Comment by tmeasday** [comment]
Perhaps the key thing here is any computation is only invalidated once so it's not weird it happens in this order.

Basically I can't see why it's a good idea to call `onInvalidate` from inside a `onInvalidate`. It seems pointless.

**Comment by mitar** [comment]
> Basically I can't see why it's a good idea to call onInvalidate from inside a onInvalidate. It seems pointless.

Yes, but when you use complicated code it might be happening somewhere deeply nested.

**Comment by tmeasday** [comment]
Ok, but then you wouldn't be depending on any particular semantics.

**Comment by mitar** [comment]
Not necessary. If it goes for something which is a tree structure (Blaze templates) and you are walking a tree you might be calling `onInvalidate` in some particular order you would want to be kept.

Anyway, this is getting too abstract. I do not have a concrete example where this breaks. I found it when I was looking for sources of order inconsistencies (like #4410).
