### ISSUE TITLE
Facebook auth with multiple domains not working

### ISSUE THREAD

**Issue by lnmunhoz** [meteor/meteor#5397]
I'm having a problem on trying to authenticate with facebook with different domains. It works just with the domain specified in `ROOT_URL` variable. That means, my user only can use facebook login in domain with www (if the `ROOT_URL` is `http://www.mydomain.com` ) or without the www (if the `ROOT_URL` is `http://mydomain.com`)

I'm getting the following error message:
```
SecurityError: Blocked a frame with origin "http://www.mydomain.com.br" from accessing a frame with origin "http://mydomain.com.br". Protocols, domains, and ports must match.
```

All the possible callback urls are specified in advanced settings on facebook. This is an error maybe on meteor facebook package but I'm looking for some help here too.

**Comment by tmeasday** [comment]
I think you should probably redirect one to the other (probably the apex -- i.e. `mydomain.com` -- to the `www`).

Even if you could get facebook login to work I think you'd find that users wouldn't remained logged in if they switched from one to the other, and no doubt a variety of other problems.

**Comment by lnmunhoz** [comment]
I created a redirect to www from the apex and now everything is ok.
