### ISSUE TITLE
Template.dynamic doesn't have data context onCreated

### ISSUE THREAD

**Issue by SavePointSam** [meteor/meteor#5399]
When working with:
```
{{> Template.dynamic template=templateName data=context}}
```
```
Template.calledTemplateName.onCreated(function() {
  console.log(this.data);
});
```
`this.data` returns undefined

However, in a helper:

```
Template.calledTemplateName.helpers({
  helper: function() {
    console.log(this.data);
  }
});
```

`this.data` return the proper data context passed in.

**Comment by stubailo** [comment]
Interesting, can you tell me what `this.data` returns inside `onRendered`?

**Comment by SavePointSam** [comment]
Also getting `this.data` is undefined for onRendered

**Comment by stubailo** [comment]
That's not great! Let me try to create an app to reproduce - do you have one on hand by any chance?

**Comment by SavePointSam** [comment]
I don't I'm afraid. Our app is rather large and we are on crunch. Don't have time to make it D:

**Comment by lampe** [comment]
i have setup a repo for this issue:
https://github.com/lampe/TemplateDynamicWithDataContext

looks fine to me
![Image of console.log](http://i.imgur.com/GsrcGtf.png)

**Comment by zimme** [comment]
@SavePointSam is the `context` for the template `return someCollection.find();` and it's not waiting for the subscription to be ready and because of that returns `undefined`?

**Comment by arshs** [comment]
wondering why was this closed? Was there a solution? 
Having the same problem - and I have my this.data line inside a if(theSubscription.ready()) block.

**Comment by zimme** [comment]
I'm thinking this was closed due to Blaze is living in https://github.com/meteor/blaze and this issue should be over there if it's not already.
