### ISSUE TITLE
Prefix / namespace exposed Meteor.methods from packages

### ISSUE THREAD

**Issue by sdossick** [meteor/meteor#540]
Not sure this needs to be forced by the future packaging system, but at the very least should it be a best-practice to prefix/namespace Meteor.methods that are defined in packages?

For instance, the accounts-base exposes "login" and "logout", and accounts-password exposes "changePassword"...it would be great if these were "accounts-base-login" etc.

**Comment by msavin** [comment]
Was just about to submit an issue for this.. looking at the method_handlers I see a big flood of potentially conflicting names. It also becomes tougher to filter them if needed. Since package Sessions and Meteor collections are namespaced with Meteor., I think this should follow the pattern.

**Comment by glasser** [comment]
Note that the current roadmap URL for this is https://trello.com/c/igqeUcwM/17-template-and-helper-namespacing

**Comment by dandv** [comment]
Related feature request: #3675.
