### ISSUE TITLE
Default settings file location

### ISSUE THREAD

**Issue by sys13** [meteor/meteor#5400]
If there were a default settings location I wouldn't need to specify --settings every time I run locally. I have multiple meteor projects locally.

There might also be a convention for deploy as well, perhaps settings_prod.json if it exists, then settings.json if it doesn't. Of course, --settings and the env var would have precedence over this default file.

**Comment by tmeasday** [comment]
Hi @sys13 agreed - in fact there is already a ticket about this: https://github.com/meteor/meteor/issues/4910
