### ISSUE TITLE
App crashes in *.meteor.com using deploy --settings

### ISSUE THREAD

**Issue by mcchrish** [meteor/meteor#5402]
Running local `meteor --settings settings.json` works.
But when doing `meteor deploy xxxx.meteor.com --settings settings.json` the app crashes.
Using Meteor 1.2.

**Comment by justinsb** [comment]
Can you please share some more details about the error you're seeing, and the settings.json you're using (with any secrets/hostnames redacted?)

**Comment by mcchrish** [comment]
Hi,
Thanks for checking on this.
I have a set of facebook appId and secret in my settings.json.
But for some reason, `meteor deploy` with settings option works perfectly fine for me now. I was about to get some logs using `meteor logs` but they're gone now so I can't really give thorough details of the error. On top of my mind, I think the error says meteor can't detect `Meteor.settings` despite having the settings option in `meteor deploy`. 
If anything, I think the error is similar to this http://stackoverflow.com/questions/29300192/specify-settings-json-file-deploying-on-remote-meteor-free-service

**Comment by laosb** [comment]
Since Meteor Free Hosting has been shutdown, closing.
