### ISSUE TITLE
Hotpush not working for Cordova when modifying a file in client/lib

### ISSUE THREAD

**Issue by dragGH102** [meteor/meteor#5403]
As mentioned in the title,

Meteor doesn't hotpush to Cordova app (real device - Android 5.0) when I modify a .js file in **client/lib**. In fact no reload and the code doesn't change (not even with location.reload() ). Tested in chrome://inspect

I suspect this has to do with the way Meteor handles /lib folders.
In fact js files in other directories are hotpushed correctly (most times)

**Comment by grsabreu** [comment]
In which version of Meteor that issue occurs to you?

**Comment by dragGH102** [comment]
@grsabreu  latest, 1.2.0.2

**Comment by martijnwalraven** [comment]
Are you sure the issue is specific to `client/lib`? The current version of hot code push on Cordova can be a little flaky in general, which might be what is going on here. If it is specific, do you have a reproduction of the issue I could have a look at?

**Comment by dragGH102** [comment]
Actually, it worked lately.
However It's highly unreliable. Some times it just works, other times it
works after cleaning app data or. Location . reload () , other times it
stops working after few seconds followings  deploy (keeps giving sockjs
error).

**Comment by adrianolsk** [comment]
I was getting problem with hotpush on android when my chrome mobile was set
to use the "Data saving mode" to reduce data when browsing,
when I turned it off everything return to work just fine.

**Comment by dragGH102** [comment]
On Wed, Oct 21, 2015 at 12:22 AM, Adriano Skroch <notifications@github.com>
wrote:

> I was getting problem with hotpush on android when my chrome mobile was set
> to use the "Data saving mode" to reduce data when browsing
>

I had a look to it, but it's not set by default. it wasn't indeed

**Comment by dragGH102** [comment]
@martijnwalraven , why did you close it?  to me the issue is still there and Chrome is not in saving mode (no idea if this can have to do with crosswalk I'm using)

**Comment by martijnwalraven** [comment]
I closed this because the original issue mentions a specific problem with `client/lib`, and you mentioned that has actually worked for you, apart from the general flakiness of the hot code push. General problems with hot code push are known and tracked in issues like https://github.com/meteor/meteor/issues/4722, which is about the plugin rewrite I'm currently working on that hopefully solves this.
