### ISSUE TITLE
Cordova barcode scanner needs to work from a button press.

### ISSUE THREAD

**Issue by lornaz** [meteor/meteor#5404]
It looks like this is not supported from the documentation on https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration. My test code is in github https://github.com/lornaz/meteorProductCapture. I run it on an android tablet.

**Comment by stubailo** [comment]
Can you give me more information on what you are expecting to happen, and what happens instead? If this is a bug report, what is the bug?

**Comment by lornaz** [comment]
When the button is pressed the call to the barcode scanner does not return to call it's callback routines.  Barcode scanner can only work correctly if it is called from meteor.startup().  It is in the online documented that it can only be called from meteor.startup(), so this may not be considered a bug. I would like this as a feature. The end user needs to decide when to capture the barcode.

**Comment by stubailo** [comment]
It can only be called _after_ Meteor is done starting up. so if your code is executing after a button press you should be fine.

**Comment by lornaz** [comment]
Should be fine, but it doesn't work from the button. It only worked when called from the startup routine.

**Comment by martijnwalraven** [comment]
I suspect this is either a programming error or a bug in the plugin you are using. As long as the button press happens after `Meteor.startup`, there should be no issue calling into the plugin.
