### ISSUE TITLE
Error: Method 'global' must be a function... future.js

### ISSUE THREAD

**Issue by jasonnathan** [meteor/meteor#5405]
I have tried upgrading to Meteor 1.2 and got this error. I then removed `~/.meteor*` and removed meteor CLI
I then tried to reinstall Meteor, ran `meteor update` and tried running the server again. No luck, don't know where to start, error occurs here:

    (STDERR) ~/.meteor/packages/meteor-tool/.1.1.9.1u9tdq1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
    (STDERR) 						throw(ex);
    (STDERR) 						      ^
    (STDERR) Error: Method 'global' must be a function

This is a web only platform dev
Short of removing and adding each package again, I would sincerely appreciate some guidance.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details! :)
