### ISSUE TITLE
[Cordova] No second hotpush when using --mobile-server?

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5407]
When I run my app with <code>meteor run android-device --mobile-server http://app.myapp.com</code> I don't get a second hotpush when I modify one of my local files. The first edit works fine and my app get's updated with the current modification, but if I modify something other after that, hotpush stops.

I'm using Meteor 1.2 with Crosswalk plugin.

**Comment by martijnwalraven** [comment]
When you say you modify a local file, do you mean a file in the app deployed at `app.myapp.com`?

It sounds like the issue may be that the version that is hot code pushed after the first change does not connect to the same server. Did you set `ROOT_URL` on the server app?

**Comment by dnish** [comment]
@martijnwalraven I modify a file on my local development machine, and the first modification is loaded by a hot code push (I can see how my app reloads with the changed code). After that, there isn't any hot code push anymore, If I edit one of my local files.

<code>ROOT_URL</code> is set in my <code>mup.json</code>. Or is it the wrong usage for <code>--mobile-server</code> and the app shouldn't receive hot code pushes from the local version? I'm just wondering why it works the first time. The connection to the deployment version is running on first startup, because I can login with my login data and see all chats and messages.

**Comment by martijnwalraven** [comment]
If I get you correctly, the app seems to be receiving a hot code push from the local development server even though it is connected to the deployment server? That would be very surprising. Are you sure this is what is going on?

You would indeed set both `--mobile-server` (to the deployment server URL) and set `ROOT_URL` (in `mup.json` for the deployed app, to that same URL) to connect to the deployment server and also receive hot code pushes from there. Changes to your local development server shouldn't have any effect in this scenario.

**Comment by dnish** [comment]
Argh, sorry, seems like it was the same issue I've reported before https://github.com/meteor/meteor/issues/5297 - in this current case, the first hot push came not directly on the first start, but after reopening the app.

Can be closed.
