### ISSUE TITLE
jshint package does not support .jshintignore files

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#5412]
I have a .jshintignore file in my app's root folder to exclude some folders from jshint. After adding the jshint package, the ignored files get linted.

I can create a repo to reproduce this if you need one.

**Comment by timbotnik** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
Now that Meteor supports npm, the [recommended linting approach](https://guide.meteor.com/code-style.html#eslint) (outside of the Meteor codebase) is to use eslint via npm (which does properly support ignore files/approaches). The `jshint` package is used internally, but is not the best choice outside of core. Closing for now - thanks for the original issue!
