### ISSUE TITLE
Provide source maps for compiled templates

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5413]
So that when debugging a template you can step through the HTML template and not compiled template functions.

**Comment by stubailo** [comment]
Looks like a great idea!

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
I have no idea how to tackle this though. Any suggestions?

**Comment by hwillson** [comment]
Moved to meteor/blaze#204 - closing - thanks!
