### ISSUE TITLE
HTTP_PROXY fails http://localhost requests

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#5417]
When you set `HTTP_PROXY` all of your `http://localhost/....` requests will fail in a `Http.call` from a server method.

The same for `http://127.0.0.1/` requests

``` js
var result = Http.call('GET', 'http://localhost', {});
```

Throws cannot resolve address localhost, because it goes to the proxy to resolve it.

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

What did you set it to? Where? Why? What does "fail" mean?

**Comment by dotnetwise** [comment]
Much more clearer now?

**Comment by dotnetwise** [comment]
It should not be using `HTTP_PROXY` nor `HTTPS_PROXY` when making calls to `HTTP.call('http://localhost/*`

**Comment by dotnetwise** [comment]
Bummer, I bumped into this again! :(

**Comment by reel** [comment]
The problem sits here:

https://github.com/meteor/meteor/blob/f7b2735d2320eecafe478f3e4dd77ccaab848194/tools/utils/http-helpers.js#L238

Technically, HTTP_PROXY is used to answer request and set the specific headers on incoming requests. 

Depends on if MDG wants to test whether options.url is localhost or 127.0.0.1 and not set options.proxy in there. 

A workaround could be using froatsnook:request or straight npm request package.

**Comment by dotnetwise** [comment]
@stubailo and @martijnwalraven, any luck to fix this in meteor 1.3?

**Comment by abernix** [comment]
@dotnetwise Please make a basic reproduction and push it to github so someone can easily pull it up and run it.  This will make it much more likely that this can be resolved (and also, confirmed to be fixed)!

**Comment by dotnetwise** [comment]
See the initial description. Is one line of code.
Basically `Http.call` to `http://localhost` and `http://127.0.0.1` should bypass the `HTTP_PROXY` whatever value that is.

Currently it tries to navigate to `http://127.0.0.1` via the proxy, which obviously fails!!

**Comment by abernix** [comment]
I understand.  However, a reproduction repo is necessary to proceed with this, categorize it, and to be used in making regression tests. [See Reporting a Bug Here](https://github.com/meteor/meteor/blob/devel/Contributing.md)

**Comment by abernix** [comment]
In addition, this will be hard because of the lack of a proxy server to test on.  Are there RFC rules somewhere that show that 127.0.0.1 should NOT be run through the proxy?  Why doesn't the proxy itself take care of making that decision?

**Comment by dotnetwise** [comment]
It's just stuppid to run the request to the proxy - how can it handle the redirect back to the original `127.0.0.1` ?
That is just non-sense.

`192.168.0.1` issuing the request to `http://127.0.0.1` with proxy set to `http://192.168.0.2`
If the request is handled by proxy, then `127.0.0.1` would refer to `192.168.0.2` and not the original `192.168.0.1`


It's obvious that it should be treated at meteor level.

I don't have time to create a repo, especially because it requires a separate fake server.
However you could simply have an IIS / Apache site running on the port 80 locally, so without a test case is very easy to be reproduced.

Perhaps also from node should be able to spawn a server on whatever port number and then navigate to it e.g. `http://localhost:1234` with whatever fake proxy set in `HTTP_PROXY` env variable

**Comment by abernix** [comment]
What about when you have a proxy running on your local computer?  For example an SSH proxy server running locally, or something?  Wouldn't this break that functionality?

**Comment by dotnetwise** [comment]
perhaps add another flag `BYPASS_LOCAL_HTTP_PROXY=0` so your case would still work, if that's the intention (although, less likely real world scenarion)

**Comment by abernix** [comment]
I wouldn't argue that it's a less likely real-world scenario as having a HTTP_PROXY set *and* making `GET` requests to a local server seems pretty uncommon too.

Maybe the correct answer is not to use the `HTTP(S)_PROXY` if the requested URL is the same as the proxy address **AND** port – since it would be very unlikely that your proxy server is also the server you're requesting data from.

**Comment by dotnetwise** [comment]
That is not possible, as if your app is monitoring other apps on the same server, while you need a proxy to access the internet (e.g. by services such as `kadira` or others) .
So the proxy needs to apply only to non-localhost requests

Basically we need this flag:
![image](https://cloud.githubusercontent.com/assets/485535/15214678/b491534a-184e-11e6-9d77-ba85f47f153d.png)

**Comment by abernix** [comment]
Ok, the preference that you are pointing to applies to ALL local IP address ranges in RFC1918, not just localhost though.

> Maybe the correct answer is not to use the HTTP(S)_PROXY if the requested URL is the same as the proxy address AND port

On this statement, I should have clarified: "in addition to being a local address"

**Comment by dotnetwise** [comment]
Of course, but what others do you think of?
`::1`
`own IP(s)` 
others?

**Comment by abernix** [comment]
Yeah, tricky.  I think we've outlined the problem enough now though: there needs to be a way to bypass the proxy for specific addresses/ranges.  Unfortunately, this might be a relatively isolated situation and I'm not sure how likely a solution for everyone will be.  +1's to be considered, of course!

**Comment by abernix** [comment]
And you could actually work around this by using `require('request')` yourself [docs](https://www.npmjs.com/package/request) and setting proxy to undefined.

**Comment by dotnetwise** [comment]
but why not supporting it by design?

Or even as a parameter to `HTTP.call` ?

**Comment by abernix** [comment]
I'm not saying it won't ever be supported, but it'll be a matter of time before someone gets to this.  I've tagged this as a feature request.

Try this and see if it works for you as a work-around:

```
var result = HTTP.call('GET', 'http://localhost/', { npmRequestOptions: { proxy: undefined } });
```

**Comment by rayfoss** [comment]
I'll just drop a note here... DPP.connect ignores the `no_proxy` environment variable :/

it's quite a pain when doing server to server DPP

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=HTTP_PROXY%20fails%20http%3A%2F%2Flocalhost%20requests&body=Migrated%20from:%20meteor/meteor%235417) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
