### ISSUE TITLE
Update node-inspector (meteor-tools dependency) 0.7.4 < 0.12.0

### ISSUE THREAD

**Issue by bobslee** [meteor/meteor#5419]
The node-inspector, a meteor-tools dependency, is outdated (0.7.4 < 0.12.0).

There's an annoying bug, which is fixed in newer release(s):
One cannot expand any nodes in scope variables, watch expressions, or property nodes after typing an object reference into the console. 

See resolved issue: https://github.com/node-inspector/node-inspector/issues/478

**Comment by stubailo** [comment]
Hey, I think this could be a good idea, but I don't see it happening in the very near future. Ideally, it would be possible to use whatever version of node-inspector you like, and then we wouldn't have to update the versions ourselves.

I'll keep it open as a feature request.

**Comment by bobslee** [comment]
Thanx for the quick and clear answer.

However I could build my meteor-stack with Git checkout and a generate-dev-bundle?
After I switched the node-inspector (dep) version?

**Comment by dpacmittal** [comment]
The `meteor debug` is pretty much useless without being able to click on expanding lists. How do I update to the latest version of node-inspector in an existing app?

**Comment by Sanjo** [comment]
This issue causes an annoying bad debugging experience with Meteor. :+1: 

If you use Webstorm, you can use the Webstorm Debugger user interface instead as a workaround ;-)

**Comment by ericterpstra** [comment]
@stubailo Can I ask why you don't see this happening? It seems like an innocuous fix to upgrade node-inspector to the latest version (which will fix all the complaints in this thread).  Is there a blocker of some sort, or are you waiting for the more involved solution of allowing any version of node-inspector?

End-to-end debugging is incredibly useful and often goes overlooked by many developers. Getting this fixed will help emphasize the cohesiveness of Meteor for newcomers, as there aren't many frameworks that allow for full stack debugging in the same language and interface.

**Comment by rhyslbw** [comment]
This perplexes me. The pegged version is buggy so what are achieving by doing nothing?

**Comment by darko-mijic** [comment]
@stubailo I think this is not a feature request, it is a bug that needs to be resolved and it is a blocker for some of us.

I agree with rhyslbw. 

Is it possible to bump the version in the near future and leave this: 
> Ideally, it would be possible to use whatever version of node-inspector you like

as feature request.

**Comment by abernix** [comment]
This is done in bd1fdcf8bac227964f5cd99a97e58ccba6324323 and will be released with Meteor 1.4 which can be tracked in #7035.
