### ISSUE TITLE
The ability to dry run Mongo.Collection updates would make schema validation a lot more robust

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#5421]
Recently after becoming tired of SimpleSchema/Collection2 bugs, I realized that I simply don't feel confident in any auto-validation package for Meteor because, as far as I can tell, they have to use their own code to figure out what the update operators will do.

If the code that interprets the update operators can't be shared between Minimongo and the validator, I think there's a much greater proability that the validator has bugs.

Since Minimongo already has code to simulate updates on the client side, theoretically it shouldn't be too difficult to expose that code as dry-run methods that just return updated copies of the documents, without affecting anything in memory or the database.

This would be a huge boon to validation tools: they can simply dry-run the update and validate the resulting document before performing the actual update.  Such tools wouldn't support things like auto-generation and cleaning, but I know I would prefer to do that myself if it means the validation can be robust.  Has anyone else reached the same conclusion?

**Comment by chrisbutler** [comment]
+1

**Comment by sebakerckhof** [comment]
Interesting idea

**Comment by jedwards1211** [comment]
It's true, if the validator re-implements the Mongo operators itself it can run more efficiently.  But there's a fair bit of logic required to do that.  In any case, I was thinking, if only I could dry-run the updates, I could write a little `check`-based validator in an hour, and it would at least be useful for preventing mistakes during development, even if I turn it off completely in production.

**Comment by stubailo** [comment]
Sounds like this is just factoring out the part of Minimongo that runs updates into a separate package, right? I'd definitely look at a PR for that, sounds like a really good idea.

**Comment by sebakerckhof** [comment]
That would be this code I guess (LocalCollection._modify):
https://github.com/meteor/meteor/blob/devel/packages/minimongo/modify.js

Which should already be accessible, since the minimongo exports LocalCollection.

Is that sufficient?

**Comment by jedwards1211** [comment]
Oh, cool, thanks for pointing that out @sebakerckhof!  Well I should check if SimpleSchema is using LocalCollection._modify after all, because that would have been easy to miss.  In any case, @stubailo, I think we can close this

**Comment by stubailo** [comment]
Great!
