### ISSUE TITLE
Testing packages isn't working as expected since 1.2

### ISSUE THREAD

**Issue by zimme** [meteor/meteor#5422]
This is part of my `package.js` form my package `zimme:active-route` which I test with the following command:
```sh
meteor test-packages --velocity --driver-package velocity:console-logger ./
```
```js
Package.onUse(function(api) {
  api.versionsFrom(['1.0', '1.2']);

  api.use([
    'check',
    'coffeescript',
    'reactive-dict',
    'underscore'
  ]);

  api.use([
    'blaze',
    'kadira:flow-router@2.0.0',
    'meteorhacks:flow-router@1.8.0',
    'iron:router@1.0.0',
    'spacebars'
  ], ['client', 'server'], {weak: true});

  ...
});

Package.onTest(function(api) {
  api.versionsFrom(['1.0', '1.2']);

  api.use([
    'blaze',
    'check',
    'coffeescript',
    'mike:mocha-package@0.5.7',
    'practicalmeteor:chai@1.9.2_3',
    'reactive-dict',
    'spacebars',
    'underscore',
    'zimme:active-route'
  ]);

  ...
});
```
As you can see I have weak dependencies on `blaze` and `spacebars` `onUse` but have them as hard dependencies `onTest`.
Before `1.2` this worked well, but since `1.2` it seems as though when running `test-packages` it uses `onUse` instead of `onTest` as changes dependencies in `onUse` affects the `test-packages` command and `onTest` doesn't.

I've tried look into what's going on but haven't found the changes that affected this behaviour.

**Comment by stubailo** [comment]
I can't reproduce this - can you tell me what is wrong with my minimal repro?

https://github.com/stubailo/5422-repro-attempt

Run test with `meteor test-packages ./` and look in browser console to see that Blaze in fact exists.

**Comment by zimme** [comment]
Looking at the repo you provided, the issue wasn't within the package test files but within the package files when used by the test.

e.g. trying to access `Blaze` from `testtest.js` when running the test.

However this isn't a problem, or a bug. It turned out to be bad code which for some reason worked with previous versions of meteor, most likely due to more packages being brought in by implicit package usage. Which now have been made explicit. `meteor-platform` -> `meteor-base`.

**Comment by zimme** [comment]
When trying to reproduce this without my "bad" code I get the same result in both `1.1.0.3` and `1.2.0.2`.

`Blaze` isn't defined, but `Package.blaze.Blaze` is defined.
