### ISSUE TITLE
Login on server

### ISSUE THREAD

**Issue by dtruel** [meteor/meteor#5424]
Hello,

I'm creating a multi-tenant app.  I'm appending the tenant Id to the front of each user to keep names separate in the user database.  I need to discreetly append this after the user clicks submit.  It would be perfect if I could call a Meteor Method called "loginUser", and take the user's name, grab the company id, append them together, and login.

Currently a user chooses a company by subdomain.  I don't want to send out the id of the company associated with the subdomain to the client.  I want to keep that on the server until the person is logged in.  I can still do all this on the client, but it means having to send out that id to anybody - and I don't want to do that.

Any plans to make the login work on the server?

**Comment by stubailo** [comment]
Have you tried modifying the user document inside `Accounts.onCreateUser`? http://docs.meteor.com/#/full/accounts_oncreateuser

Either way, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by dtruel** [comment]
Good idea, thank you I used your solution and it works.
