### ISSUE TITLE
Meteor Behind a Proxy 

### ISSUE THREAD

**Issue by Angarsk8** [meteor/meteor#5425]
Today I ran into a problem performing some common tasks in meteor such as updating it, adding packages and deploying apps. The message I get in the console in all of those cases is:

```
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
```

That wiki page says that all I have to do is to set the HTTP_PROXY and HTTPS_PROXY environment variables, but I'm still so confused!! :disappointed:  The provided solution for OSX is: 

```
export HTTP_PROXY=http://user:password@1.2.3.4:5678
export HTTPS_PROXY=http://user:password@1.2.3.4:5678
meteor update
```

Can anybody briefly explain me what user and password do I have to put there, and what is that number at the end of those commands, where do I find it? 

Thanks for your help and sorry for my ignorance.

**Comment by k5e** [comment]
One hint that helps to find the proxy server's address may be in your browser's settings. You find the proxy settings in the network related area of your browser. Or ask your network administrator.

You need the following information:

- proxy server hostname or IP address
- proxy port
- your proxy user name
- your proxy user password

The latter two are only necessary if the proxy setup at your place requires authorization.

Then put all things together:
```
export HTTP_PROXY=http://<user>:<password>@<proxy server name or address>:<port>
export HTTPS_PROXY=http://<user>:<password>@<proxy server name or address>:<port>
```
or, if your proxy does not need authorization:
```
export HTTP_PROXY=http://<proxy server name or address>:<port>
export HTTPS_PROXY=http://<proxy server name or address>:<port>
```
I recommend that you put this into a shell script for easy access to these settings.

**Comment by martijnwalraven** [comment]
@k5e Thanks for explaining this so well! I'll go ahead and close the issue.
