### ISSUE TITLE
Multiple css files in build

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#5426]
I could be mistaken, but I thought Meteor 1.1 would minify all files in to 1 file on build.
I notice that in Meteor 1.2 there are multiple files (actually, 2 in all of my cases). I thought I might have done something wrong in my packages, but I notice this is also the case on www.meteor.com , where there are 2 css files.

If this isn't a bug then could you explain me what triggers the build system to split files and for what reason?

**Comment by stubailo** [comment]
I think it could be because Internet Explorer 9 has limits on the maximum number of selectors per stylesheet: http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx

This was a new feature added in Meteor 1.2 to enhance browser compatibility.

**Comment by sebakerckhof** [comment]
Oh, it's in the changelog, should have checked that first. ( https://github.com/meteor/meteor/issues/1876 )
