### ISSUE TITLE
Console output when trying to use `let` and `const` ES2015 features in Meteor 1.2.0.2

### ISSUE THREAD

**Issue by DevanB** [meteor/meteor#5428]
I'm seeing console logs reporting:

```
I20151014-12:41:46.869(-5)? /server/measure/measureService.js:
I20151014-12:41:46.870(-5)?   Unexpected token let
```

and

```
I20151013-16:02:24.569(-5)? /lib/routes.js:
I20151013-16:02:24.570(-5)?   Unexpected token const
```

Example usages causing the logs are pretty straight forward:
`let year = Meteor.settings.private.measurementYear;` and

```
const publicRedirect = () => {
  if (Meteor.userId()) {
    FlowRouter.go('index');
  }
};
```

This is happening between on two different applications that are at `1.2.0.2` and `ecmascript` is added. I've removed the `ecmascript` package and re-added it and removed and re-added at versions `0.1.5`, `0.1.4`, and `0.1.3`; all yielding the same console logs.

Should be noted that this doesn't seem to be causing any issues in the application, but is mucking up the console.

Thanks!

**Comment by mquandalle** [comment]
I think you should provide a clone-able reproduction.

**Comment by DevanB** [comment]
Sure, due to the nature of the projects I can't share the exact code, but I'll create a small reproduction. Thanks!

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by DevanB** [comment]
@stubailo Thanks for any help you can provide. It doesn't seem to be causing problems, it's just mucking up the console. Here are a few steps to replicate:

1. Clone this repo: `git clone https://github.com/DevanB/ordeal-planner.git`

2. Run with `meteor`

I'm using `let` in `/client/helpers/flow-router.js` and `const` in `/lib/routes.js`. Server-side console output I'm seeing is:

```
ordeal-planner master % meteor
[[[[[ ~/Documents/ordeal-planner ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
I20151021-13:14:41.286(-5)? /client/helpers/flow-router.js:
I20151021-13:14:41.288(-5)?   Unexpected token let
I20151021-13:14:41.288(-5)? /lib/routes.js:
I20151021-13:14:41.288(-5)?   Unexpected token const
```

**Comment by stubailo** [comment]
I think your repository is private: https://github.com/DevanB/ordeal-planner

**Comment by DevanB** [comment]
Sorry, it's public now.

Again, thanks for looking into this.

**Comment by stubailo** [comment]
Confirmed; the app runs but there is the weird output on the server. @benjamn any thoughts?

**Comment by hwillson** [comment]
I just ran the repro and didn't see any errors in the server console (using Meteor 1.4.2.3). Let's assume this is fixed - thanks for reporting this originally! Closing.
