### ISSUE TITLE
[Docs] 2x extra parenthesis in Cordova docs

### ISSUE THREAD

**Issue by mbrookes** [meteor/meteor#5437]
https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration

```js
Meteor.startup(function () {
    // The correct way
    navigator.geolocation.getCurrentPosition(success));
});

// Will not work
navigator.geolocation.getCurrentPosition(success));
```

```success))``` I'd edit, but it isn't a Wiki.

**Comment by stubailo** [comment]
Fixed! I'm trying to get that content off the wiki, so that people can submit PRs. That will probably end up related to the Meteor Guide project here: https://github.com/meteor/guide

**Comment by mbrookes** [comment]
Why not leave it where it is, and open it up for editing (i.e. actually make it a wiki)? I found a few more things like this, which I could have fixed on the spot.

**Comment by stubailo** [comment]
I don't think we would have the bandwidth to actively track the quality and correctness of all of the content if we made it entirely editable. I think pull requests are the best option.
