### ISSUE TITLE
Error: SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5438]
I get this randomly, I have no replication:

```bash
I20151015-16:24:31.588(2)? [cucumber.log] Error: SQLITE_BUSY: database is locked
I20151015-16:24:31.588(2)? [cucumber.log]     at Object.Future.wait (/Users/raix/.meteor/packages/velocity_meteor-tool/.1.1.9_1.19e60q3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
I20151015-16:24:31.588(2)? [cucumber.log]     at [object Object]._.extend._execute (/tools/packaging/catalog/catalog-remote.js:368:22)
I20151015-16:24:31.588(2)? [cucumber.log]     at [object Object]._.extend.begin (/tools/packaging/catalog/catalog-remote.js:98:13)
I20151015-16:24:31.588(2)? [cucumber.log]     at runOnce (/tools/packaging/catalog/catalog-remote.js:211:11)
I20151015-16:24:31.588(2)? [cucumber.log]     at [object Object]._.extend._serialize (/tools/packaging/catalog/catalog-remote.js:178:14)
I20151015-16:24:31.588(2)? [cucumber.log]     at [object Object]._.extend.runInTransaction (/tools/packaging/catalog/catalog-remote.js:244:21)
I20151015-16:24:31.588(2)? [cucumber.log]     at [object Object]._.extend._columnsQuery (/tools/packaging/catalog/catalog-remote.js:890:24)
I20151015-16:24:31.589(2)? [cucumber.log]     at [object Object]._.extend._contentQuery (/tools/packaging/catalog/catalog-remote.js:880:21)
I20151015-16:24:31.589(2)? [cucumber.log]     at [object Object]._.extend.getReleaseVersion (/tools/packaging/catalog/catalog-remote.js:665:23)
I20151015-16:24:31.589(2)? [cucumber.log]     at PackageAPI._.extend.versionsFrom (/tools/isobuild/package-api.js:483:44)
I20151015-16:24:31.589(2)? [cucumber.log]     at package.js:8:7
```

**Comment by sebakerckhof** [comment]
Is your home directory on a local hard disk? I've seen this happen on network drives.
Related: https://github.com/meteor/meteor/issues/4892

**Comment by raix** [comment]
locally

**Comment by martijnwalraven** [comment]
Is there anything more you can say about the circumstances under which this happens? From the output, it seems this may happen while running Cucumber tests?

**Comment by stubailo** [comment]
Yeah I have never seen this and don't know how to replicate it. Sorry, going to close since we can't do anything.

**Comment by TechyTimo** [comment]
I get this usually when im trying to run multiple meteor apps at the same time on my local machine.

**Comment by eminaz** [comment]
Had to restart my laptop to solve this.

**Comment by JulianNorton** [comment]
Confirming this issue. Restarting laptop didn't help. Investigating.

**Comment by devarashetty** [comment]
+1 happened when I tried to start two meteor apps at the same time

**Comment by raix** [comment]
Could it be a race condition locking the sql lite files?

**Comment by arnaud-zad** [comment]
Why this issue is closed ? I have reproduced the same error

**Comment by devonbarrett** [comment]
Just encountered this after a local instance died but did not clear up the running process on exit. (Stopped responding to TERM sigs)

```
~/.m/p/v2.0.1>  fuser packages.data.db
/home/dev/.meteor/package-metadata/v2.0.1/packages.data.db:  3492
```

sending a KILL signal to the hung instance removes the lock and lets the app start.

FWIW, we happily run multiple instances along side each other.

**Comment by fatbird** [comment]
This just happened to me when I was starting two meteor instances at the same time (one on a different port).  The first started, the second locked.  After the first was finished, I started the second again and it started normally.

**Comment by dpankros** [comment]
I've been getting this too as of late.  I can confirm that it's when multiple apps are started at roughly the same time.  I wonder if the package-checking process is the culprit here.  

If I stagger the start of my apps, it is more dependable.

**Comment by vyasbhavin** [comment]
I had the same issue, restarting the laptop fixed it. It looks like the previous shutdown wasn't graceful so there was likely a lingering lock state of the DB.

**Comment by rpong** [comment]
was there a fix for this? perhaps some sort of retry setting?

**Comment by leocavalcante** [comment]
Just got it, I solved by force quitting the process.  So things like restarting the computer should work as well...

**Comment by rpong** [comment]
In our case, this happened intermittently and affected our test builds which we are running in parallel with other instances per box.

What we did is we setup retries with random sleep:

```
meteor run --port $serverIP:$METEOR_PORT --settings $METEOR_CONFIG 
status=$?
if [ "${status}" -ne 0 ]; then
    export sleepRand=$(shuf -i 12-100 -n 1)
    echo "DB is busy, retrying in $sleepRand seconds"
    sleep $sleepRand
    meteor run --port $serverIP:$METEOR_PORT --settings $METEOR_CONFIG 
    status=$?
    if [ "${status}" -ne 0 ]; then
        exit $status
    fi
fi
```
