### ISSUE TITLE
Meteor Accounts: Using separate instances of client and server. Fails to login:

### ISSUE THREAD

**Issue by lucidprogrammer** [meteor/meteor#5439]
Code base to reproduce the problem is in the following repository.(different behavior in 1.1.0.3 and 1.2.02 - both in the repository)
https://github.com/lucidprogrammer/meteor-accounts-separate-server-issue

-------client.js
if (Meteor.isClient) {
  Meteor.startup(function(){
    var connection = DDP.connect("http://localhost:3040");
    Meteor.connection= connection;
    Accounts.connection= connection;
    Meteor.users = new Meteor.Collection('users', {
      connection: connection
    });

    connection.subscribe('users');

    Tracker.autorun(function () {
      console.log(Meteor.user());
    });

});

  Template.register.events({
    'submit #register-form' : function(e, t) {
      e.preventDefault();
      var email = t.find('#account-email').value
        , password = t.find('#account-password').value;

      Accounts.createUser({email:email,password:password}, function(err,result){
          if (err) {
            // Inform the user that account creation failed
            console.log(err);
          } else {
            // Success. Account has been created and the user
            // has logged in successfully.
            console.log("registered user");
            console.log('response is '+ result);
            console.log(Meteor.user());
            Meteor.connection.call('user',function(err,result){console.log(err);console.log(result);})
          }

        });

      return false;
    }

  });
  Template.login.events({

    'submit #login-form': function(e,t){
      e.preventDefault();
      var email = t.find('#login-email').value
      , password = t.find('#login-password').value;
        Meteor.loginWithPassword(email, password, function(err){
        if (err)
            console.log(err);
        else
           // The user has been logged in.
            console.log('logged in');
        });
        return false;
    }
  });

}

--------------server.js--------(remote)
if (Meteor.isClient) {
  Meteor.startup(function(){
    var connection = DDP.connect("http://localhost:3040");
    Meteor.connection= connection;
    Accounts.connection= connection;
    Meteor.users = new Meteor.Collection('users', {
      connection: connection
    });

    connection.subscribe('users');

    Tracker.autorun(function () {
      console.log(Meteor.user());
    });

});

  Template.register.events({
    'submit #register-form' : function(e, t) {
      e.preventDefault();
      var email = t.find('#account-email').value
        , password = t.find('#account-password').value;

      Accounts.createUser({email:email,password:password}, function(err,result){
          if (err) {
            // Inform the user that account creation failed
            console.log(err);
          } else {
            // Success. Account has been created and the user
            // has logged in successfully.
            console.log("registered user");
            console.log('response is '+ result);
            console.log(Meteor.user());
            Meteor.connection.call('user',function(err,result){console.log(err);console.log(result);})
          }

        });

      return false;
    }

  });
  Template.login.events({

    'submit #login-form': function(e,t){
      e.preventDefault();
      var email = t.find('#login-email').value
      , password = t.find('#login-password').value;
        Meteor.loginWithPassword(email, password, function(err){
        if (err)
            console.log(err);
        else
           // The user has been logged in.
            console.log('logged in');
        });
        return false;
    }
  });

}
----------
Issues:
1. Meteor.loginWithPassword fails in both versions
2. createUser succeeds in 1.1.0.3 and Meteor.user() shows correctly but {{currentUser}} fails
3. 2. createUser succeeds in 1.2.0.2 but Meteor.user() shows null @client

**Comment by smilansky** [comment]
Try this 
```
Meteor.loginWithPassword({"email": email}, password, callback});
```

**Comment by lucidprogrammer** [comment]
With version 1.2.0.2 the following code works perfectly for the scenario. However, code block 1 and code block 2 for making this scenario work should not be there ideally as the core should ideally cater to the use case in my opinion. Thanks

if (Meteor.isClient) {

  Meteor.startup(function(){
    //Seems that without this, on page refresh, it doesn't work.
    //COMMENT: Ideally this should not be needed if the core takes care of this use case of a different connection for Accounts
    //hack block 1***********
    var token = Accounts._storedLoginToken();
     if(token)  {
       Meteor.loginWithToken(token, function(err){
        // this is going to throw error if we logged out
        if(err)
          console.log(err);
        else
          console.log('loginWithToken');
      });//loginWithToken
     }
    //hack block 1***********
  });//startup function


  var connection = DDP.connect("http://localhost:3060");
  Accounts.connection= connection;
  //COMMENT: Ideally this should not be needed if the core takes care of this use case of a different connection for Accounts
  //hack block 2***********
  Accounts.users = new Meteor.Collection('users', {
      connection: connection
  });
  //hack block 2***********


  Tracker.autorun(function () {
    //No code which directly affects the functionality. Just for testing
    console.log(Meteor.user());
    Accounts.connection.call('user',function(err,result){
      if(err)
        console.log(err);
      if(result){
        console.log(result);
        if(result._id === Meteor.user()._id){
          console.log("Server and client shows that the same user has logged in");
        } else {console.log("Server and client shows different users");}
      }
    })
  });

  Template.register.events({
    'submit #register-form' : function(e, t) {
      e.preventDefault();
      var email = t.find('#account-email').value
        , password = t.find('#account-password').value;

      Accounts.createUser({email:email,password:password}, function(err,result){
          if (err) {
            // Inform the user that account creation failed
            console.log(err);
          } else {
            // Success. Account has been created and the user
            // has logged in successfully.
            console.log("registered user");
            console.log('response is '+ result);
            console.log(Meteor.user());
          }
        });//createUser
      return false;
    }
  });//register

  Template.login.events({
    'submit #login-form': function(e,t){
      e.preventDefault();
      var email = t.find('#login-email').value
      , password = t.find('#login-password').value;
        Meteor.loginWithPassword(email, password, function(err){
        if (err)
            console.log(err);
        else
           // The user has been logged in.
            console.log('logged in successfully');
        });
        return false;
    }
  });//login

  Template.statusloggedin.events({
    'click #logout': function(e,t){
      e.preventDefault();
      Meteor.logout();
      return false;
    }
  });//logout

}

**Comment by martijnwalraven** [comment]
I have some trouble following along with your code, so it might help if you could reduce it to a few essential lines. Is your point that you should not have to set both `Accounts.connection` and `Accounts.users`?

**Comment by lucidprogrammer** [comment]
Accounts.connection I believe is logical and mandatory. However additionally setting Accounts.users is unnecessary imho. But mainly the block 1 which is to manage Accounts._storedLoginToken() is really unnecessary and its tough to get the head around, I did take some time to get around to that. So making it easy can really help developers I think

**Comment by trialAndErrorxxx** [comment]
we have the same issue and we're trying to make multiple apps that use the same app users database for login. we tried to use AccountsClient but there's no clear documentation  of how to use it.

**Comment by evolross** [comment]
Wow, if I hadn't of stumbled upon this issue, I would have never found `Accounts._storedLoginToken();` which, at least in my case, was the key to getting `Meteor.loginWithToken()` to work.

I was trying to use `Meteor.user().services.resume.loginTokens[0].hashedToken` as the token with no luck and was banging my head.
