### ISSUE TITLE
Cordova plugin not working on meteor app

### ISSUE THREAD

**Issue by cmboros** [meteor/meteor#5443]
Hello,

Im using Meteor and Cordova and i try to use https://github.com/donaldp24/CanvasCameraPlugin but have some issue. 
The camera feed don't display in canvas but i can take picture switch the camera use the flash option but is not displaying the camera feed. 
I have setup also a standalone cordova app using the plugin and is working. 

I have attach the image one from meteor and one from cordova.

![img_0327](https://cloud.githubusercontent.com/assets/15148603/10527672/99758ade-7346-11e5-9841-66dc357298fb.jpg)
![img_0328](https://cloud.githubusercontent.com/assets/15148603/10527671/9973bf4c-7346-11e5-9400-f0fc89b3fff1.jpg)

Anyone have any idea why is working like this?

Thanks

**Comment by martijnwalraven** [comment]
I don't think I can help you with this specific plugin, but I'd like to know if there is some general issue with our Cordova integration. Did you happen to find out more about what could be causing this behavior?

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
