### ISSUE TITLE
Accounts sendEnrollmentEmail - retyping of password when initially setting up your account - 

### ISSUE THREAD

**Issue by sylido** [meteor/meteor#5444]
1. Send enrollment e-mail.
2. User clicks on link and is transported to main page, prompted to enter his password for the first time.
3. User has to enter the password twice for verification.
4. User doesn't enter the password in the second field, but password is still accepted and set correctly to the first one.

Not sure how much control over this Accounts has, maybe it's the account-ui-bootstrap-3 that is messing up ?

**Comment by zimme** [comment]
@sylido This is the responsibility of the ui, the ui should check this validation client-side before giving the password to `Accounts.resetPassword`.

**Comment by sylido** [comment]
Much thanks @zimme I've located the issue and will close this one.

**Comment by sylido** [comment]
For anyone with similar troubles, the issue for accounts-ui-bootstrap-3 is [here](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/172).

**Comment by stubailo** [comment]
Great, glad this got figured out!
