### ISSUE TITLE
Meteor Installation Script is broken

### ISSUE THREAD

**Issue by lampe** [meteor/meteor#5445]
When i try to install meteor i get this error:

![curl: (22) The requested URL returned error: 404 Not Found](http://i.imgur.com/GOyHhYd.png)

confirmed on: arch linux and osx el cap.

**Comment by lampe** [comment]
quick fix around it:
1. download the install script
2. change RELEASE="1.2.0.4-logging.0" to RELEASE="1.2.0.2"
3. chmod +x /path/to/file and run it

**Comment by cismous** [comment]
thank you

**Comment by tjmonsi** [comment]
I have put the edited install script and put it on my github. You can run the installation script using this:

"curl https://raw.githubusercontent.com/tjmonsi/stable-meteor-install/master/meteorInstall.sh | /bin/sh"

**Comment by Codebryo** [comment]
Thank you :) @tjmonsi just saved my day <3

**Comment by Oizor** [comment]
@tjmonsi Thx, but It's not working for my config in Codeship, as requiring sudo.

**Comment by swoobie** [comment]
Ran into this problem earlier tonight, glad to see someone's got a workound ^^

**Comment by huongtinhve** [comment]
Craete ! it work for me ! thanks

**Comment by rhyslbw** [comment]
+1

**Comment by jbwebesign** [comment]
+1. Thanks very much!

**Comment by dmitrijs-balcers** [comment]
Thank you

**Comment by mlocher** [comment]
See https://github.com/codeship/scripts/blob/master/packages/meteor.sh for a script that will definitely work on Codeship and that we will update if changes to the installation script are required.

**Comment by JoshuaSkootsky** [comment]
Just for fun, I ran diff on tjmonsi's edited script, which successfully installed meteor, with what's currently at https://install.meteor.com (which I titled "broken-meteor.sh")

Skootsky:meteor Skootsky$ diff broken-meteor.sh meteor-install.sh
25c25
< RELEASE="1.2.0.4-logging.0"
---
> RELEASE="1.2.0.2"
216a217
>

**Comment by sgtpepper43** [comment]
I can't comprehend that after eight hours, nobody has reverted the install script or put the correct file up.

**Comment by engelgabriel** [comment]
Is anyone from Meteor looking into this?

**Comment by jeremyccrane** [comment]
+1 for Meteor team.

**Comment by glasser** [comment]
This is fixed. We accidentally marked a pre-release as "recommended", but didn't do the other steps that would make it installable.

**Comment by glasser** [comment]
@sgtpepper43 Usually MDG is scattered across the world and sees issues like this over various time zones.  We're all in SF this week, so this caught us mostly asleep :)

Clearly better monitoring is needed for this situation though!  We have monitoring that install.meteor.com is serving but not for this edge case.

**Comment by sgtpepper43** [comment]
@glasser with the amount of issues you guys must go through daily I'm not surprised you wouldn't have somebody constantly watching them, it'd drive me crazy if I had to do that. If you added a team on the meteor organization people could use `@meteor/[teamName]` to flag you down on important issues, though I could see that getting taken away real quick when people start thinking all their issues are "important."

Also, sorry for being a bit short about the issue, it's the morning, and phantomJS had a very similar problem yesterday so I had a bit of an "OH NOT AGAIN" panic.

**Comment by glasser** [comment]
@sgtpepper43 Yeah, with the amount of issues we get, our main mechanism for getting through all of them is a big weekly meeting (I used to organize this, @stubailo does now).  Great for making sure everything gets seen, but not great for urgent problems!

**Comment by tjmonsi** [comment]
@glasser yey! Now going to revert back my .travis.yml files :) I'll keep the one in my repo as a safety just in case. Thanks for the fix :)

**Comment by glasser** [comment]
Also fun undocumented fact: you can install other versions with `curl https://packages.meteor.com/install.sh?release=foo | sh`.  (This doesn't work directly on install.meteor.com for silly reasons.)
