### ISSUE TITLE
Meteor Installer : The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by jbwebesign** [meteor/meteor#5446]
Hi there, trying to install Meteor on latest version of OS X. 

Running `curl https://install.meteor.com/ | sh` returns the following error:

`The requested URL returned error: 404 Not Found`

Have I missed something? Am I using the wrong URL? Or is the service down?

Cheers :)

**Comment by lampe** [comment]
https://github.com/meteor/meteor/issues/5445

**Comment by jbwebesign** [comment]
Cheers, sorry didn't see this when searching earlier, not sure how mind!

**Comment by lampe** [comment]
no problem :)
would be easier for the meteor folks if you could close that issue here :)

**Comment by stubailo** [comment]
Got fixed!
