### ISSUE TITLE
Method install not working with curl due to 1.1.0.3 release being last available in cloudfront's CDN

### ISSUE THREAD

**Issue by agustifernandez** [meteor/meteor#5447]
I solved it thanks to this StackOverflow answer: http://stackoverflow.com/questions/32706364/404-error-installing-meteor-on-mac-os-x-10-10-5

<quote> 
So, not sure if this is an official solution but I was able to get Meteor 1.2 by first installing Meteor 1.1.0.3, which was the latest version I saw on the https://d3sqy0vbqsdhku.cloudfront.net/ for Mac OS X (or any OS).

However, to get that version I first had to save the shell code from https://install.meteor.com to a local file, and then manually change

RELEASE="1.2" on line 25 to RELEASE="1.1.0.3"

After install Meteor using this version, then I ran a manual meteor update in the terminal

I don't really know why this is the case but if anyone else is seeing this problem then hope this helps
< /quote>

**Comment by lampe** [comment]
you can still install meteor 1.2 because there is now 1.2 there is only 1.2.0.2 and so on
so if you want 1.2 you have to change it to:  RELEASE="1.2.0.2"

**Comment by mcbain** [comment]
looking into the donwloaded sh shows weird version.
```
RELEASE="1.2.0.4-logging.0"
```

**Comment by mcbain** [comment]
Changing it to `1.2.0.2`allows direct install of 1.2

**Comment by stubailo** [comment]
This should be fixed now! More conversation here: https://github.com/meteor/meteor/issues/5446
