### ISSUE TITLE
package.js:14:7: must declare exact version of dependency: name@awesome-react

### ISSUE THREAD

**Issue by roberto68** [meteor/meteor#5449]
funniest thing is that there's no node package called awesome-react, wtf???
how can I define version when there's no package awesome-react??
so I remove react & react-bootstrap from packages.json but still the same.

**Comment by zimme** [comment]
What's at line 14 of `package.js`?

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by kachizukanne** [comment]
@roberto68 View packages.json (not package.json) on your app root. Exclude the reference to the dependency if not required, or provide exact version if
