### ISSUE TITLE
Application not starting on Android Simulator as well as Android Device on Ubuntu

### ISSUE THREAD

**Issue by ManrajGrover** [meteor/meteor#5451]
I have been trying to run application on Android Simulator as well as Android Device for a week now and failing to get it to work. I have followed the steps mentioned on [this](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux) page. The app is working on browser but when I run `meteor run android` or `meteor run android-device` the process gets stuck at this point:
![rsz_screenshot_from_2015-10-17_012625](https://cloud.githubusercontent.com/assets/5673050/10552468/9ce78bfa-7471-11e5-9501-63aef5d03ec0.png)

As it was mentioned that Android Simulator is bit slow, I tried it on an Android Device but again it got stuck at this point. I have waited for more than half an hour yet no progress was seen. I'm using Ubuntu 14.04 64 bit on VMWare. Please let me know if more information is required regarding this.

**Comment by martijnwalraven** [comment]
Can you try running with `--verbose` to generate more log output that might help diagnose the issue?

**Comment by ManrajGrover** [comment]
I tried to run `meteor run android --verbose` and got the following output which I stopped because emulator did not show up even after more than 20 minutes of wait. It kept showing "Starting app on Android Emulator"

```
manraj@manraj-virtual-machine:~$ cd meteor/myapp/
manraj@manraj-virtual-machine:~/meteor/myapp$ meteor run android --verbose
Getting installed version for platform android in Cordova project
Checking Cordova requirements for platform Android
[[[[[ ~/meteor/myapp ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
Local package version is up-to-date: autopublish@1.0.4
Local package version is up-to-date: autoupdate@1.2.3
Local package version is up-to-date: babel-compiler@5.8.24_1
Local package version is up-to-date: babel-runtime@0.1.4
Local package version is up-to-date: base64@1.0.4
Local package version is up-to-date: binary-heap@1.0.4
Local package version is up-to-date: blaze@2.1.3
Local package version is up-to-date: blaze-html-templates@1.0.1
Local package version is up-to-date: blaze-tools@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.4
Local package version is up-to-date: caching-compiler@1.0.0
Local package version is up-to-date: caching-html-compiler@1.0.2
Local package version is up-to-date: callback-hook@1.0.4
Local package version is up-to-date: check@1.0.6
Local package version is up-to-date: ddp@1.2.2
Local package version is up-to-date: ddp-client@1.2.1
Local package version is up-to-date: ddp-common@1.2.1
Local package version is up-to-date: ddp-server@1.2.1
Local package version is up-to-date: deps@1.0.9
Local package version is up-to-date: diff-sequence@1.0.1
Local package version is up-to-date: ecmascript@0.1.5
Local package version is up-to-date: ecmascript-collections@0.1.6
Local package version is up-to-date: ejson@1.0.7
Local package version is up-to-date: es5-shim@4.1.13
Local package version is up-to-date: fastclick@1.0.7
Local package version is up-to-date: geojson-utils@1.0.4
Local package version is up-to-date: hot-code-push@1.0.0
Local package version is up-to-date: html-tools@1.0.5
Local package version is up-to-date: htmljs@1.0.5
Local package version is up-to-date: http@1.1.1
Local package version is up-to-date: id-map@1.0.4
Local package version is up-to-date: insecure@1.0.4
Local package version is up-to-date: jquery@1.11.4
Local package version is up-to-date: launch-screen@1.0.4
Local package version is up-to-date: livedata@1.0.15
Local package version is up-to-date: logging@1.0.8
Local package version is up-to-date: meteor@1.1.9
Local package version is up-to-date: meteor-base@1.0.1
Local package version is up-to-date: minifiers@1.1.7
Local package version is up-to-date: minimongo@1.0.10
Local package version is up-to-date: mobile-experience@1.0.1
Local package version is up-to-date: mobile-status-bar@1.0.6
Local package version is up-to-date: mongo@1.1.2
Local package version is up-to-date: mongo-id@1.0.1
Local package version is up-to-date: npm-mongo@1.4.39_1
Local package version is up-to-date: observe-sequence@1.0.7
Local package version is up-to-date: ordered-dict@1.0.4
Local package version is up-to-date: promise@0.5.0
Local package version is up-to-date: random@1.0.4
Local package version is up-to-date: reactive-dict@1.1.2
Local package version is up-to-date: reactive-var@1.0.6
Local package version is up-to-date: reload@1.1.4
Local package version is up-to-date: retry@1.0.4
Local package version is up-to-date: routepolicy@1.0.6
Local package version is up-to-date: session@1.1.1
Local package version is up-to-date: spacebars@1.0.7
Local package version is up-to-date: spacebars-compiler@1.0.7
Local package version is up-to-date: standard-minifiers@1.0.1
Local package version is up-to-date: templating@1.1.4
Local package version is up-to-date: templating-tools@1.0.0
Local package version is up-to-date: tracker@1.0.9
Local package version is up-to-date: ui@1.0.8 
Local package version is up-to-date: underscore@1.0.4
Local package version is up-to-date: url@1.0.5
Local package version is up-to-date: webapp@1.2.2
Local package version is up-to-date: webapp-hashing@1.0.5
Preparing Cordova project from app bundle     
Copying resources for mobile apps             
Writing new config.xml                        
Preparing Cordova project for platform Android
Running Cordova app for platform Android with options --emulator
ANDROID_HOME=/home/manraj/Android/Sdk        |
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
WARNING : no emulator specified, defaulting to AVD_for_Nexus_4_by_Google
Waiting for emulator...
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM is not installed on this machine (/dev/kvm is missing).
^C                                              
manraj@manraj-virtual-machine:~/meteor/myapp$
```

However I got it working on my Android Device after a little long wait. I'm not sure how this happened but no fix from my side was made regarding this.

**Comment by martijnwalraven** [comment]
The fact that you got it working on a device is encouraging. I suspect it not working at first may have to do with flakiness of `adb` (Android Debug Bridge). Sometimes it helps just to unplug a device or restart adb.

As for the emulator, from the error message it seems you may not have KVM installed.

**Comment by ManrajGrover** [comment]
I'm sorry for taking so much time to reply back. I got involved in developing a Meteor app.
Currently I'm using Android Device for testing it. Simulator is still not responding. I haven't tried the above method as I'm not aware how to do that. I read [here](https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux) how to install KVM but I got a `0` as response on running that command, hence not possible to install KVM. 

Thank you so much for your support sir. Lets leave this issue closed for now.
I would love to contribute to Meteor. Please provide some pointers to good first bugs.

**Comment by adrianolsk** [comment]
Run "adb list" to see if your device is detected.
Maybe a bad USB cable or some missing driver.
Try to open the emulator manually as well to check if it's working without
meteor.
Run adb list to see if the emulator is listed.
Try to run the app with the emulator opened.
Em 24/10/2015 04:58, "Manraj Singh" <notifications@github.com> escreveu:

**Comment by ManrajGrover** [comment]
@adrianolsk,

I'll try and let you know. Thank you. :)

**Comment by jalik** [comment]
Hi, I faced the same problem, the solution is to :
- install the **Android Build Tools** (19 or newer) using the **Android SDK Manager**, it is required to build the APK for android
- install the **Android Support Repository** using the **Android SDK Manager**, it is required by the **crosswalk** meteor package (or you can remove this package)
- after executing `meteor run android --verbose`, wait a few minutes until the app has been compiled as an APK for Android, it will starts on your device/emulator

**Comment by b-long** [comment]
@jalik How does one tell if the app has been compiled as an APK?  I'm new to the ecosystem, but am fairly certain I've configured things correctly.  When I'm invoking `meteor run android --verbose` , I see a fair amount of successful looking output that ends with this : 

```
Running Cordova app for platform Android with options --emulator
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
ANDROID_HOME=/Users/me/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
No emulator specified, defaulting to my-avd  \
Waiting for emulator...
   Starting app on Android Emulator          /
```

Unfortunately, I never get past `Starting app on Android Emulator` .  Any advice?

**Comment by jalik** [comment]
@b-long You have to create an AVD (Android Virtual Device) in the AVD Manager in order to have a working emulator, if you already have the AVD, be sure that it is configured to use the Android API 23 (the one Meteor is configured to use). Note that is takes time to deploy on your phone, so wait at least 2/3 minutes the first time you deploy.
