### ISSUE TITLE
`meteor build` fails after 1.2.0.2 upgrade

### ISSUE THREAD

**Issue by betacar** [meteor/meteor#5452]
After upgrading to meteor 1.2.0.2, our staging meteor app fails in the build process. Basically (and this is my conclusion from the npm logs) is not able to compile fibers@1.0.5.

Here is the complete build output:
````shell
$ meteor build
bundle/
bundle/.node_version.txt
bundle/README
bundle/main.js
...
bundle/server/
bundle/server/.bundle_version.txt
bundle/star.json
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> fibers@1.0.5 install /home/mah-app/app/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/home/mah-app/app/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:132:54: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /home/ubuntu/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/ubuntu/.node-gyp/4.2.1/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/ubuntu/.node-gyp/4.2.1/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)’:
../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/home/mah-app/app/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/mah-app/app/programs/server/node_modules/fibers
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mah-app/app/programs/server/npm-debug.log
````

Now, there is an [open issue about this in the node-fibers project](https://github.com/laverdet/node-fibers/issues/248) in a node v4.X enviroment. But, we use node v0.10.40 is ours.

Any ideas?

**Comment by Sanjo** [comment]
You run Meteor with node v4.2.1. See `npm ERR! node v4.2.1`;-)

**Comment by martijnwalraven** [comment]
Glad you found out what the issue was.

**Comment by buhrmi** [comment]
How do we get Meteor build passing on node v4.2.1? We've updated jenkins to use node v4.2.1?

**Comment by martijnwalraven** [comment]
Meteor currently requires Node 0.10 (we use 0.10.40) and does not work on other versions.

**Comment by SirCmpwn** [comment]
What's the plan for moving to the latest node releases?

**Comment by serut** [comment]
OMYGAD. +1 to fix this issue.

**Comment by sjmcdowall** [comment]
To fix what issue precisely?  Meteor on Node 0.10.40 -- the supported version -- works fine?

**Comment by SirCmpwn** [comment]
The issue that Meteor only supports an outdated version of Node, obviously.

**Comment by ram-you** [comment]
Outdated supported Node version.

**Comment by SirCmpwn** [comment]
And still, outdated.

**Comment by sjmcdowall** [comment]
And that has no bearing on this issue -- which is closed because it was being built on a non-supported version.  I am sure there is some issue about upgrading support to the "latest" node -- there certainly is a lot of discussion in the forums that I suggest you check out and comment there.

**Comment by SirCmpwn** [comment]
I'm asking what the plan is to support new versions of node.js. There's no need to get shitty. I just want to know when Meteor is going to support the latest node, because I am not going to use it before then.

**Comment by sjmcdowall** [comment]
@SirCmpwn -- I wasn't in anyway trying to be "shitty". Yours is a very good and germane point that many people are wondering in fact.  All I was saying is that I think the best place to post (or add your question) maybe to the Meteor forums instead of this thread.  I don't think the MDG team is going to read this thread and answer here -- if they do answer anywhere it will be in the forums (I think).  Although to be honest, they've been rather mum on the whole plan of attack on node versions.  But there are some good discussions on the forums.

**Comment by suenot** [comment]
:+1: Have the same error in
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
fibers@1.0.5

**Comment by sjmcdowall** [comment]
@suenot - Meteor is NOT supported on ANY node version except 0.10.40.  So it's no surprise you have a problem.  There is no timeframe (that I know of) of when any other > 0.10.XX version will be supported.

**Comment by ram-you** [comment]
It is quite odd that Meteor provides solutions and support something in alpha (Angular 2) and can not support the LTS version of another thing (Node 4).

**Comment by csvan** [comment]
> It is quite odd that Meteor provides solutions and support something in alpha (Angular 2) and can not support the LTS version of another thing (Node 4).

Why is it odd, and how can you even thing that Angular2 vs Node4 support is even a valid comparison? Meteor is a very different framework, and has very different preconditions for its operating environment. If you don't like it, tough luck. It is not Meteors fault that more modern Node versions do not provide what it needs.

**Comment by suenot** [comment]
sjmcdowall, thanks

**Comment by ram-you** [comment]
@csvan  Thank you. 
I love Meteor. But at the same time I work a lot with other tools requiring at least NodeJS  4.x.
I was wondering if anyone has an idea on the future of Meteor. Are we going in the future to support recent versions of NodeJS or we will fork NodeJS 0.10.xx ?

**Comment by sjmcdowall** [comment]
@ram-you That is an excellent question -- maybe post it to the Meteor Forum or look to see if it's answered.  I can't believe that at SOME point -- at least Node LTS won't be supported.  I am pretty sure MDG understands that staying on Node 0.10.X isn't a viable solution long term if they want to keep developers using this platform.  But -- that's just my opinion FWIW. :)

**Comment by ram-you** [comment]
Hi @sjmcdowall 
I posted the question on the Forum : 
https://forums.meteor.com/t/nodejs-lts-support/14467

**Comment by AllanVieira** [comment]
Hello guys.
I use Fedora as the operating system in my development environment with Node 4.2.3, never had problems.
When I perform deploy on Ubuntu server I had a series of identical problems to those reported here.
I moved to Centos server and my problems over, follows the commands used to deploy Centos server for those who want to test:

yum -y update
yum -y groupinstall "Development Tools"
cd /usr/src
sudo wget http://nodejs.org/dist/latest-v4.x/node-v4.2.6-linux-x64.tar.gz
tar zxf node-v4.2.6-linux-x64.tar.gz
sudo mv node-v4.2.6-linux-x64 / opt
echo "export PATH = \ $ PATH: /opt/node-v4.2.6-linux-x64/bin" >> ~ / .bashrc
source ~ / .bashrc
node --version
sudo curl https://install.meteor.com/ | sh
meteor

**Comment by limonazzo** [comment]
deploy meteor v1.21 in node v4.2.2 :

    cd project 
    meteor build --directory ../build/
    cd ../build/bundle/programs/server/
    
edit:

    npm/promise/node_modules/meteor-promise/package.json
    npm/babel-compiler/node_modules/meteor-babel/package.json
    package.json

change 

    "fibers": "1.0.*",

to: (in all of it)

    "fibers": "1.0.10",


and delete:

    npm-shrinkwrap.json

run 

    npm install 
    cd ../..
    export x
    export etc.
    node main.js

¡y listo!, epsero sirva.

**Comment by sjmcdowall** [comment]
Meteor is only node 0.10.40
