### ISSUE TITLE
install meteor1.2.0.2 fail on Window 7 64bit

### ISSUE THREAD

**Issue by kingofhawks** [meteor/meteor#5453]
I try to install meteor as administrator on Windows 7 64bit, after installation finished, i can not find the folder under C:\Users\user\AppData\Local\.meteor.
When i run meteor on cmd console, it always prompt "Meteor not recognized as internal or external ..."
I have googled but nothing found about this issue. Also i have reinstalled latest Node and meteor, no help.

**Comment by kingofhawks** [comment]
After reinstalled meteor several times, it works like a charm now!

**Comment by dotnetwise** [comment]
If that doesn't work, add it manaually on `PATH` 
![image](https://cloud.githubusercontent.com/assets/485535/10615257/17257950-775f-11e5-91a7-586babfadfb7.png)

**Comment by martijnwalraven** [comment]
Great to hear you got it working. Did you ever figure out what the issue was?

**Comment by kingofhawks** [comment]
@dotnetwise , I have checked that ,after installation finished, there is no such folder \AppData\Local\.meteor created. This is very strange.

**Comment by kingofhawks** [comment]
@martijnwalraven  I resolved this issue by reinstall node.js and meteor several times.

**Comment by abernix** [comment]
Going to close this as resolved, but please let us know if you still have problems!
