### ISSUE TITLE
Prevent OAuth connections from immediately signing up / logging in users

### ISSUE THREAD

**Issue by calvinfroedge** [meteor/meteor#5456]
Hi,

I started digging into Meteor's guts a bit to exercise a bit more control over the OAuth methods in Meteor. I now have many more questions (and still don't yet know how to do what I want, but getting closer). Specifically, I want to be able to pass extra data to be populated in the profile for new accounts that is NOT associated with the account provider (and I want to send this info from my client, once that OAuth callback has been received).

I have found that by overriding `Accounts.callLoginMethod` I can see the data being used to login (the oauth credentials) before it actually happens. As there is a lot of other logic in this method, I would prefer not to overwrite it. Going a bit deeper, I found that things start getting really confusing after `self.connection.apply` is called in `Accounts.callLoginMethod`. Specifically, what happens after methodInvoker.sendMessage() is called? 

https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/ddp-client/livedata_connection.js#L904

I can see that this eventually calls `_send` on the SockJS connection. I'm kind of lost with what happens after that. Where are these calls received on the server side? How are requests dispatched, and how can I overwrite / intercept these handlers? I would really appreciate (and be willing to pay for), a few hours of time from someone who played a part in writing this piece.

Thank you!

**Comment by calvinfroedge** [comment]
As far as customizing the fields that get included in the user's profile, I've come up with a solution for this. First, let me say that this can easily be resolved for everyone with just a few changes to the API which I am happy to send a PR. My "monkey-patching" solution is as follows:

CLIENT SIDE
```
		Accounts.oauth.tryLoginAfterPopupClosed = function(credentialToken, callback) {
			var credentialSecret = OAuth._retrieveCredentialSecret(credentialToken) || null;
			Accounts.callLoginMethod({
				methodArguments: [{
					oauth_custom: {
						credentialToken: credentialToken,
						credentialSecret: credentialSecret,
						custom: {
							type: 'developer'
						}
					}
				}],
				userCallback: callback && function (err) {
					err ? callback(err) : callback();
				}});
		};


		var callback = function(){
			console.log('arguments', arguments);
			alert('login success!');
		}

		var waitForLoginServices = setInterval(function(){
			console.log('configured?', Accounts.loginServicesConfigured());

			if(Accounts.loginServicesConfigured()){
				clearInterval(waitForLoginServices);
				var credentialRequestCompleteCallback = Accounts.oauth.credentialRequestCompleteHandler(callback);
				Github.requestCredential({}, credentialRequestCompleteCallback);
			}
		}, 100);
```

SERVER SIDE
```
Accounts.registerLoginHandler(function (options) {
  if (!options.oauth_custom) //CHANGED oauth TO oauth_custom
    return undefined; // don't handle

  check(options.oauth_custom, { //CHANGED oauth to oauth_custom
    credentialToken: String,
    credentialSecret: Match.OneOf(null, String),
		custom: Object //Added custom
  });

	//ADDED check to ensure if custom is given, it is an object of string values
	_.each(options.oauth_custom.custom, function(value, key){
		var obj = {}
		obj[key] = String;

		check(options.oauth_custom.custom, obj);
	})

  var result = OAuth.retrieveCredential(options.oauth_custom.credentialToken,
                                        options.oauth_custom.credentialSecret);

  if (!result) {
    return { type: "oauth_custom",
             error: new Meteor.Error(
               Accounts.LoginCancelledError.numericError,
               "No matching login attempt found") };
  }

  if (result instanceof Error)
    throw result;
  else {
    if (!_.contains(Accounts.oauth.serviceNames(), result.serviceName)) {
      return { type: "oauth_custom",
               error: new Meteor.Error(
                 Accounts.LoginCancelledError.numericError,
                 "No registered oauth service found for: " + result.serviceName) };

  }

		//CUSTOMIZED
		result.options.profile = _.extend( (result.options.profile || {}), options.oauth_custom.custom);
		return Accounts.updateOrCreateUserFromExternalService(result.serviceName, result.serviceData, result.options);
  }
});
```

A permanent solution would be to simply change the `registerLoginHandler` for oauth to match what I've given, as well as ensure that 'loginWithService' can be given options to pass into the profile as well.

There were a couple other issues that were very similar, I think this approach should work for both of them as well: https://github.com/meteor/meteor/issues/3834 and https://github.com/meteor/meteor/issues/4249

**Comment by zol** [comment]
Hey @calvinfroedge . Could you be more specific about what changes to the API you require. I'm trying to understand this statement - ```Specifically, I want to be able to pass extra data to be populated in the profile for new accounts that is NOT associated with the account provider (and I want to send this info from my client, once that OAuth callback has been received)``` . Are you trying to pass extra parameters from the client when the OAuth login process is initiated that you would later use to cancel the login?

What specific API changes are you proposing (a before and after may help)? Also, what use case are you trying to address?

Thanks for your help!

**Comment by rsercano** [comment]
Is there any other workaround to pass extra parameters (such as extra profile info like we do on password signups) to OAuth login services ?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Prevent%20OAuth%20connections%20from%20immediately%20signing%20up%20%2F%20logging%20in%20users&body=Migrated%20from:%20meteor/meteor%235456) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
