### ISSUE TITLE
Meteor compatibility with third party mapping libs or things that have html setters?

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#546]
Hi.

How should I work with third party plugins that control a piece of the DOM, but inside that DOM I still want to render templates. Is this possible? How?

Backstory: So, I've spent a couple hours (too many) attempting to get Popup's from leaflet or infoWindow's from google maps to work friendly in meteor. Neither apparently do in this regard. I've gotten templates into the DOM and working outside of mapping libraries divs. But not inside, only rendered with no events.

I'm wondering if this has something to do with constant regions or just how template rendering works in general. I'm aware that events don't work inside constant regions. I couldn't get the rendered templates events to work with a map with no constant region either.

I'm doing something like this: 

```
  info = new google.maps.InfoWindow()
  google.maps.event.addListener marker, "click", ->
    info.setContent(Template.details(thing))
    info.open map, marker
```

I've based my code off of the parties example (because d3 & static images don't cut it).

Could someone maybe update the example with third party mapping or explain how to work with html setters in this context.

Thanks!

**Comment by amnevins** [comment]
Also, struggling with attaching events to my google maps markers with meteor.  Have tried several packages from leaflet to dburles, none of the examples they list in their readme's work...  I have tested with meteor 1.1 and 1.2,

 google.maps.event.addListener doesnt seem to work at all with meteor.  Has anyone figured this out?  Thanks!

**Comment by joaopiopedreira** [comment]
Hi,

My meteor app uses google maps extensively with no probs at all.

You must wait for the (async) google maps library to load before you can use it.

Try using a package from atmosphere (for instance this one - mrt:googlemaps) that makes sure that the library is loaded before you can start using it.

What is your exact problem?

Also, try posting this type of "how to use this or that" in the meteor forum (forum.meteor.com)

João Pio Pedreira
/// Sent from a mobile device ///
