### ISSUE TITLE
Meteor 1.1 app not working anymore since installation of another 1.2 app

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5463]
I tried out Meteor 1.2 in a separate app, in a separate directory. To this app I copied some of my main app, to try out what the upgrade from 1.1 would mean to it. I did not succeed and ended up in a strange error where Meteor said that the Fiber package could not be found.

So I deleted everything and returned to my main app, which was untouched. However, this app is now broken as well! If I try to start it, I only get the following error message:

```
W20151018-13:08:51.565(2)? (STDERR)           
W20151018-13:08:51.566(2)? (STDERR) /Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.23e2gg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151018-13:08:51.621(2)? (STDERR)             				throw(ex);
W20151018-13:08:51.621(2)? (STDERR)             				      ^
W20151018-13:08:51.621(2)? (STDERR) Error: Can't find npm module 'path-to-regexp'. Did you forget to call 'Npm.depends' in package.js within the 'meteorhacks_picker' package?
W20151018-13:08:51.621(2)? (STDERR)     at Object.Npm.require (/Users/waldgeist/Documents/Development/htdocs/concats/webapp/.meteor/local/build/programs/server/boot.js:155:17)
W20151018-13:08:51.621(2)? (STDERR)     at packages/meteorhacks:picker/lib/implementation.js:1:1
W20151018-13:08:51.622(2)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/concats/webapp/.meteor/local/build/programs/server/packages/meteorhacks_picker.js:135:4
W20151018-13:08:51.622(2)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/concats/webapp/.meteor/local/build/programs/server/packages/meteorhacks_picker.js:166:3
W20151018-13:08:51.622(2)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/concats/webapp/.meteor/local/build/programs/server/boot.js:222:10
W20151018-13:08:51.622(2)? (STDERR)     at Array.forEach (native)
W20151018-13:08:51.622(2)? (STDERR)     at Function._.each._.forEach (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.23e2gg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151018-13:08:51.622(2)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/concats/webapp/.meteor/local/build/programs/server/boot.js:117:5
```
This app was working as a charm before. I even tried to reset it to a state it was 1 week ago. No change, I'm still getting this error. Obviously, the Meteor tool itself is broken now. How can I fix this?! To be honest, I am completely through with trying Meteor 1.2. I always ended up with such a mess, it is very, very, disappointing.

EDIT: I got the app back to work by re-installing Meteor from scratch. Still, I cannot understand how this can even happen.

**Comment by derwaldgeist** [comment]
Update: Today, the same problem appeared again, with all my apps. I did not change anything in the meantime. After I restarted my Mac in the morning and tried to start-up one of my apps, I got the error message with the fibers module again. What can cause this issue? I'm now trying to re-install both Node and Meteor again, but I have no clue what's happening here.

**Comment by Sanjo** [comment]
Try `meteor reset`.

**Comment by derwaldgeist** [comment]
I tried this multiple times, but this did not help. The problem is also not related to a specific app. If it happens, *all* apps are affected at the same time. It seems as if Meteor's core tools have been corrupted somehow.

**Comment by avalanche1** [comment]
did you try running your old app with `meteor --release 1.1.0.3`?

**Comment by stubailo** [comment]
@derwaldgeist I don't know if you are still in this situation, but could you send me a Zip file of the contents of `~/.meteor/packages/meteorhacks_picker` please?

**Comment by derwaldgeist** [comment]
@stubailo: Thanks for coming back on this issue, highly appreciated.

I've downgraded all apps to 1.1 now and re-installed Meteor twice in the meantime, which was the only way to get things up and running again, so I unfortunately don't have the exact error configuration any more.

But as ```fourseven:scss``` recently added some functionality I was missing in 1.2 (and was preventing me to upgrade), I might try 1.2 out in the next days.

Anyways, I will send you the current contents of my meteorhacks_picker folder via mail, but as I said, I'm not sure if it resembles the state it was on 1.2.

**Comment by derwaldgeist** [comment]
I just found a stack-overflow question describing the very same phenomenon:
http://stackoverflow.com/questions/15851923/cant-install-update-or-run-meteor-after-update

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
