### ISSUE TITLE
Minimongo and filtered fields: update by finding index

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5464]
Say I have a meteor user that is structured like this:

```
{
  _id: '1234',
  emails: [{
    address: 'email@email.org',
    verified: true
  }],
  reviews: [{
    _id: '5678',
    title: 'What a dreadful movie',
  }, {
    _id: '7890',
    title: 'Great movie',
  }],
  roles: ['reviewer']
}
```

Now, on the server, I filter the fields for a route such as `/movies/5678/reviews` so that it can find all reviewers who have reviewed this movie.

```
Meteor.publishComposite('movie', function (movieId) {
  return {
    find: () => Movies.find(movieId),
    children: [{
      find: function (movie) {
        return Meteor.users.find({
          roles: 'reviewer',
          'reviews._id': movie._id
        }, {
          'fields': { 'reviews.$': 1 }
        });
      }
    }]
  }
});
```

I can't update it on the client via a slice appropriately.

```
Meteor.users.update({
  _id: Meteor.userId(),
  'reviews._id': Router.getParam('_id')
}, {
  $set: { 'reviews.$.title': form.title }
});
```

**Comment by stubailo** [comment]
Can you give me some more information?

> I can't update it on the client via a slice appropriately.

What do you mean? Is there an error? Does the update not show up? Does it end up in the database?

**Comment by AlexFrazer** [comment]
It says that it must be updated by `_id`.

**Comment by abernix** [comment]
Closing as we continue to go through and cleanup old issues.  Please provide a reproduction if this is still a problem per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines.  Thanks!
