### ISSUE TITLE
ES6 - No polyfills for Object and Symbol?

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#5468]
I noticed if I use `Symbol` in my Meteor app, it won't even run without errors. And `Object.assign` works in some browsers but not others (IE). Will the `ecmascript` package at some point have polyfills for these?

**Comment by stubailo** [comment]
@benjamn will have more info, but I believe Meteor 1.2.1, which I am hoping to release this week, will have these features. See more here: https://github.com/meteor/meteor/blob/devel/History.md#vnext
