### ISSUE TITLE
Stache - Docs and Snippets for Slack

### ISSUE THREAD

**Issue by harryward** [meteor/meteor#5470]
Hey all wanted to drop a note and ask you to checkout Stache - its a cool way to create, manage and collaborate on snippets and documentation dynamic to your slack team (and even share version of your documentation or snippet with someone outside of your slack team).

I'm sharing this because when you are referencing the problems you are having you can use a Stache link as a live example of what you propose or what your experiencing.

example: http://stached.io/standalone/HftLjxSfHmBbC9a7Z

Clicking on the feedback tab also shoots comments into whatever channels you have tied to the Stache.

http://stached.io

<a href="http://stached.io"><img src="https://s3.amazonaws.com/f.cl.ly/items/313x1j0T1E3V0k3U4132/Screen%20Shot%202015-10-19%20at%2011.00.11%20AM.png"></a>

<img src="http://api.harryward.biz/dZOB/Screen%20Shot%202015-10-19%20at%2010.40.54%20AM.png">

Let me know your thoughts!

**Comment by stubailo** [comment]
This isn't a bug or feature request for Meteor. We have https://www.meteor.com/contact for other stuff.
