### ISSUE TITLE
Support non-ObjectId ids

### ISSUE THREAD

**Issue by Quicksteve** [meteor/meteor#5471]
I was planning on using Meteor as a admin frontend to my MongoDB backend (used by another application, layout cannot be modified). This application uses UUIDs (BinData Variant 4) as  the `_id` value and as I just found out after pouring some time in my application Meteor does not support these.

Is there any chance that Meteor will add support for them? If not/not very soon where would be the right places to add support by hand?

**Comment by Quicksteve** [comment]
I've [hacked in UUID support](https://github.com/Quicksteve/meteor/commit/ae1706373c2c4dac5dbb488157224ee09fcaa617), but that solution probably isn't the way to go. I would really appreciate a 'real' fix to this issue.

**Comment by stubailo** [comment]
Currently there is not a plan to do this. Your hack looks like a pretty reasonable place to put that stuff, given that that is where we deal with ObjectIDs as well.

Is there an exhaustive list somewhere of the different kinds of Mongo IDs?

**Comment by Quicksteve** [comment]
According to the [documentation](https://docs.mongodb.org/manual/core/document/#the-id-field):

> The _id field may contain values of any BSON data type, other than an array.

So any BSON type may be used (including nested types).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20non-ObjectId%20ids&body=Migrated%20from:%20meteor/meteor%235471) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
