### ISSUE TITLE
Failing/Missing TCP Packet buffering for incoming WebSocket frames

### ISSUE THREAD

**Issue by jreinert** [meteor/meteor#5472]
I opened an issue for nodejs about this but I suspect this actually might be a bug in how meteor handles the websocket frame packets. See https://github.com/nodejs/node/issues/3445

**Comment by martijnwalraven** [comment]
Are you sure this is an issue that is specific to Meteor and not expected behavior for the WebSocket protocol? I've never come across this issue with any other WebSocket client.

**Comment by jreinert** [comment]
I can't believe this is expected behavior because the TCP maximum theoretical packet size is 64KiB which is _way_ less than the maximum size allowed for WebSocket.

**Comment by martijnwalraven** [comment]
I noticed you already opened [an issue](https://github.com/faye/faye-websocket-node/issues/48) for faye-websocket, which Meteor ultimately uses for its WebSocket support. I hope someone there is able to help you with your question.
