### ISSUE TITLE
onDestroyed isn't called if set on a helper

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/meteor#5476]
I'm adding an onDestroyed event on a helper (if it hasn't been added already). It doesn't fire when the first template is destroyed but it does when the second one is destroyed.

Here's the repo: https://github.com/ManuelDeLeon/onDestroyed-issue

Here's the code:

```html
<body>
  <button>Remove Head</button>
  {{#each children}}
    {{> child }}
  {{/each }}
</body>

<template name="child">
  {{addOnDestroyed}}
  {{name}}
</template>
```

```js
if (Meteor.isClient) {

  Template.registerHelper('addOnDestroyed', function () {
    var templateInstance = Template.instance();
    var template = templateInstance.view.template;
    if (!template.onDestroyedSet) {
      template.onDestroyedSet = true;
      template.onDestroyed(function () {
        console.log("onDestroyed from helper: " + Template.instance().data.name);
      })
    }
  });

  Children = new Mongo.Collection(null);
  Children.insert({name: "A"});
  Children.insert({name: "B"});

  Template.body.helpers({
    children: function () {
      return Children.find();
    }
  });

  Template.body.events({
    'click button': function () {
      var firstId = Children.findOne()._id;
      var firstName = Children.findOne().name;
      Children.remove(firstId);
      console.log("Removed: " + firstName);
    }
  });

  Template.child.onDestroyed(function () {
    console.log("onDestroyed regular: " + Template.instance().data.name);
  });

}
```

This is the initial state:

![image](https://cloud.githubusercontent.com/assets/4257750/10619063/d95cd074-7730-11e5-8c07-f678ffebb191.png)
![image](https://cloud.githubusercontent.com/assets/4257750/10619075/e56bbcae-7730-11e5-827a-0f10cdaf9464.png)

When you click the button, the head is removed but only the "regular" onDestroyed is called:

![image](https://cloud.githubusercontent.com/assets/4257750/10619107/10feda4a-7731-11e5-9742-9ff7813ba7b8.png)
![image](https://cloud.githubusercontent.com/assets/4257750/10619117/1c52f5ac-7731-11e5-9eb6-231b7938e56b.png)

If you click the button again, this time both onDestroyed will be called (the regular and the one added by the helper):

![image](https://cloud.githubusercontent.com/assets/4257750/10619128/38a9d7de-7731-11e5-951b-12ef0465c5f6.png)
![image](https://cloud.githubusercontent.com/assets/4257750/10619136/4363493a-7731-11e5-8f84-97e17580cf35.png)

I expected the onDestroyed from helper to be called when either template was destroyed, not just the second one.

**Comment by stubailo** [comment]
This is an intentional design decision: we go out of our way to copy the callbacks onto templates when they are created.

The appropriate pattern here would be to have some sort of JavaScript helper instead of a Spacebars one, and do something like:

```js
AddOnDestroyed(Template.child);
```

Before any of those templates are rendered. Inside the callback, you can inspect the template instance and data context to see if anything should be done.
