### ISSUE TITLE
this.request.body returning empty object

### ISSUE THREAD

**Issue by hyouuu** [meteor/meteor#5477]
Posted this issue originally on iron-router (https://github.com/iron-meteor/iron-router/issues/1449), but got no reply yet, so desperately posting here as well...

Quotes the original poster:
"Meteor 1.2

```
Router.route('/upload', {
  where: 'server',
  action: function(){
    console.log(this.request.body);
    this.response.end(JSON.stringify(this.request.body));
  }
});
```
I am using the lines mentioned in earlier issues.

```
if (Meteor.isServer) {
    Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({
        extended: false
    }));
}
```
Still the response is {}. Did this break with meteor 1.2?
"

**Comment by stubailo** [comment]
Hi, unfortunately I won't be able to help you with bugs in Iron Router, but if it is in fact some sort of bug in 1.2 that would be good to know.

Can you create a reproduction in the form of an app, where something does work in 1.1 but not in 1.2? If so, I will take a deeper look at it.

**Comment by hyouuu** [comment]
Thanks for the fast reply. How do I go back to meteor 1.1?
On a side, it seems Iron Router is de facto routing package for meteor, so it's surprising that MDG doesn't care at all for this basic functionality (or am I getting the impression wrong? Do you recommend using Flow Router or some other approaches?)

**Comment by stubailo** [comment]
@hyouuu downgrading isn't really a supported operation, the easiest thing is to start a new app with `meteor --release 1.1.0.3 create my-app` and then put your source code in there.

> On a side, it seems Iron Router is de facto routing package for meteor, so it's surprising that MDG doesn't care at all for this basic functionality

Currently, we don't have a recommended approach for server-side routing at all - there are many options out there like IR, Picker, Restivus, my package `simple:rest`, etc.

For the Meteor Guide which is being written now, we're recommending Flow Router, which seems to be more actively maintained and includes less functionality (which makes it easier to track down bugs).

**Comment by hyouuu** [comment]
Thanks for the elaboration @stubailo !

**Comment by hyouuu** [comment]
Actually one more question - since there's no recommended server-side routing, how should I handle server http POST requests?

**Comment by stubailo** [comment]
Here are a few options:

- https://atmospherejs.com/meteorhacks/picker
- https://atmospherejs.com/simple/json-routes
- https://atmospherejs.com/nimble/restivus (built on top of json-routes)
