### ISSUE TITLE
Document all supported ES2015 features in 1.2.1

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5479]
I think we added Symbol, some stuff for String, Object, etc. I'm not really sure what the whole list is.

The `ecmascript` README is probably the right place for this stuff right now: https://github.com/meteor/meteor/tree/devel/packages/ecmascript#polyfills

**Comment by benjamn** [comment]
Updated: https://github.com/meteor/meteor/commits/release-1.2.1
