### ISSUE TITLE
ConstraintSolver gets run on every file change

### ISSUE THREAD

**Issue by chrishowes** [meteor/meteor#5480]
I'm noticing that even in a brand new app, Meteor runs the constraint solver to get package versions on every code change. This is pre-hot loading. Though I'm not very familiar with Meteor internals, running Meteor with the DEBUG_SQL flag results in a lot of `Transaction took X` calls (it looks like they're not reported if t < 10, but removing that shows they are all `SELECT content FROM versions WHERE packageName=?`)

I'm wondering if this is necessary?

**Comment by avital** [comment]
Thanks for taking the time to dig into the internals of Meteor's build system.

We don't currently have plans to improve Meteor's build performance, but if you think you could untangle it and demonstrate an improvement to build times, we'll take a look at your pull request.

**Comment by dgreensp** [comment]
Fixed in betas of Meteor 1.3.

https://github.com/meteor/meteor/commit/0376b477a54f8b90f5ee7c35c8043ec238c6b8c6
