### ISSUE TITLE
Make it possible to opt-out of Method retries

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5481]
***1 Upvote*** Given the complexities on getting "run only once" working correctly in all cases (see https://github.com/meteor/meteor/issues/1285 and https://github.com/meteor/meteor/issues/2407), and the fact that developers want to use non-idempotent methods, it seems like a useful feature to be able to opt out of the method retries on a case-by-case basis, if a method is known to be non-idempotent and potentially harmful.

**Comment by stubailo** [comment]
+1! I've wanted this for a while. Also, it would be great to be able to set a timeout on a method - if it doesn't succeed after a certain amount of time, you can get an error callback.

**Comment by talsraviv** [comment]
Great to see this issue created. I have a method that takes a long time due to an API we use, and I'd like to tell Meteor to be patient on this and not call it multiple times.

**Comment by namirsab** [comment]
yes, that's happening to us also and its kind of ugly, because it's just a long method.

**Comment by namirsab** [comment]
Nothing new about this? @tmeasday @stubailo

**Comment by stubailo** [comment]
I'd look at a PR for this!

**Comment by namirsab** [comment]
@stubailo could you guide me a bit where to look? I would appreciate some help :smile:

**Comment by stubailo** [comment]
Oh wait, we already did this!

https://github.com/meteor/meteor/pull/6180

Heh, should have closed the issue.

Will be out in Meteor 1.3!
