### ISSUE TITLE
Cross Origin issues with iOS Cordova

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5482]
So I initially had an issue because `http://meteor.local` the wrong hostname for my Facebook api key. I got around this by skipping straight to the production build (deployed to http://findashindig.com). This got the Facebook API to work, but then the google maps api broke and I got this alert:

![img_7065](https://cloud.githubusercontent.com/assets/1794527/10628150/90ed9698-7776-11e5-8c78-1073226bece9.PNG)

Whats really suspicious here is that its from http://meteor.local. I thought I was building a production version of the app when I ran this command:

```
NODE_ENV=production meteor build ../build/v0.2 --server http://findashindig.com --mobile-settings settings.prod.json
```

When I run it in Xcode, I get Cordova debug messages. And in those messages, I see this one.

```
Finished load of: http://meteor.local/
```

Am I doing something wrong here? How can I build a production version of the app that doesn't involve meteor.local?

**Comment by adrianolsk** [comment]
Meteor create a server on the mobile serving files at http:/meteor.local,
probably because if it load from filesystem like phonegap do DDP calls
wound´t work.
so meteor.local will be there aways even in production.
You can try something in the mobile-config.js to load google maps

```js
App.accessRule('*.google.com/*');
App.accessRule('*.googleapis.com/*');
App.accessRule('*.gstatic.com/*');
````

**Comment by adrianolsk** [comment]
Meteor create a server on the mobile serving files at http:/meteor.local,
probably because if it load from filesystem like phonegap do DDP calls
would not work.
so meteor.local will be there aways even in production.
You can try something in the mobile-config.js to load google maps

```js
App.accessRule('*.google.com/*');
App.accessRule('*.googleapis.com/*');
App.accessRule('*.gstatic.com/*');
```

**Comment by martijnwalraven** [comment]
@adrianolsk is right: `meteor.local` is the address of the device local file serving and is used even in production. Basically, it is a replacement for using `file://` URLs.

So you may have to add `meteor.local` to the allowed origins for your Google Maps API key.

**Comment by ccorcos** [comment]
I see. that worked. Just added meteor.local to my allowed origins and also added the accessRule.
