### ISSUE TITLE
IE8 + default app fails?

### ISSUE THREAD

**Issue by louwers** [meteor/meteor#5484]
Meteor does not seem to work with IE8 – I tried the default app created with `meteor create testapp`. I tried the [virtual machine offered by Microsoft](https://dev.modern.ie/tools/vms/mac/).

![screen shot 2015-10-21 at 9 36 22](https://cloud.githubusercontent.com/assets/649392/10630558/a065af8c-77d7-11e5-8b11-341309f08a48.png)
![screen shot 2015-10-21 at 9 42 14](https://cloud.githubusercontent.com/assets/649392/10630608/099125fe-77d8-11e5-8e2d-2f2a334b7468.png)

Is this a bug or are there now certain packages required for IE8 support?

**Comment by stubailo** [comment]
@martijnwalraven were you able to reproduce this?

**Comment by martijnwalraven** [comment]
Yes, I did get some JavaScript errors running in IE8.

**Comment by stubailo** [comment]
Great, will be fixed in 1.2.1!

**Comment by tsgoak** [comment]
I tried the default app created with "meteor create test1" with Meteor 1.4. It has similar "Expected Identifier" error with IE8 in modules.js, line 249.
if (typeof Mp.import === "function" && // 7
typeof Mp.export === "function") {
