### ISSUE TITLE
Google's OAuth credentials page does not permit trailing slashes.

### ISSUE THREAD

**Issue by JonTheNiceGuy** [meteor/meteor#5486]
I submitted a PR which is, as far as I can tell, nearly right, however my lack of knowledge of Javascript prevents it from being tested. The PR is #5435.

**Comment by stubailo** [comment]
Sounds like a great idea to me, would be great if someone could fix up that PR.

**Comment by abernix** [comment]
This is fixed with PR #8331, thanks to @TechplexEngineer and should surface in Meteor 1.4.3.
