### ISSUE TITLE
Feature: Cordova Plugin Hot Code Push

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#5487]
It is a pain to manually update via all app stores every time we integrate a new cordova plugin.

This happens way more often than we expected.

E.g. see our current cordova-plugins:

cordova-plugin-screen-orientation@1.4.0
cordova-plugin-statusbar@0.1.10
fr._46cl.focus@https://github.com/46cl/cordova-android-focus-plugin.git#da668f4249217655a572a49e13496c1947573c39
imeiplugin@1.0.1
cordova-plugin-camera@1.2.0
mx.ferreyra.callnumber@https://github.com/Rohfosho/CordovaCallNumberPlugin.git#3dad50b5dfc292f0a20088b6d5a5dfa9b0b795ee
cordova-plugin-ble-central@1.0.1
cordova-plugin-geolocation@1.0.1
cordova-plugin-media@1.0.1
cordova-plugin-globalization@1.0.1
cordova-plugin-network-information@1.0.1
com.chariotsolutions.nfc.plugin@0.6.2

**Comment by adrianolsk** [comment]
I think hot code push Cordova is not possible because Cordova create native
code to each platform when you generate the app.

Hot code push, javascript, HTML and css is quite easy.

But if you add Cordova plugin there is no other way other than send the app
to the stores again
Em 21/10/2015 12:35, "obiwarn" <notifications@github.com> escreveu:

**Comment by martijnwalraven** [comment]
@adrianolsk is absolutely right. The reason for using a Cordova plugin is that it allows you to access features implemented in native code, and there is no way to push native code to existing apps.

What I do think would a useful feature is to keep track of these plugin dependencies, so we can be sure to not push incompatible versions to apps that have not yet been updated through the store.

**Comment by obiwarn** [comment]
I am not into this but couldn't Meteor integrate a Cordova plugin to watch
for updates?

E.g. like this one https://github.com/markmarijnissen/cordova-app-loader



Sebastian Obentheuer




+49 0176 569 88 564

sebastian@hoardspot.com


www.hoardspot.com


einFach GmbH, Alexanderstrasse 3, 10178 Berlin, Geschäftsführer: Anthony
Forsans

Registergericht: Amtsgericht Charlottenburg (Berlin), HRB 154297 B

2015-10-21 21:00 GMT+02:00 Martijn Walraven <notifications@github.com>:

**Comment by martijnwalraven** [comment]
@obiwarn: Meteor already does this, that is what we call Hot Code Push. The issue is not about pushing new versions of the JavaScript code, but about updating the native code part of Cordova plugins.

**Comment by obiwarn** [comment]
@martijnwalraven: I thought the above plugin does exactly that? 
It would be a lot of work since one must provide current builds for the platforms on the server. But I hope this is possible, since we need it for our infrastructure (which needs silent updates on a running app).

**Comment by martijnwalraven** [comment]
@obiwarn: No, the plugin you mentioned only updates JavaScript code (and other assets), which is true of all autoupdating solutions I know of. For most purposes, there is no way to push updates to native code without going through the app stores.

**Comment by obiwarn** [comment]
Dang. I hoped so much that an .apk on Android could update itself.

However, thank you very much @martijnwalraven.
