### ISSUE TITLE
observer with regex not working.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5488]
A document looks as follows in my collection:

```
{
  'name': 'messages',
  'connection': {
    'port': 23,
    'host': '192.168.1.3'
  },
  'messages': [{
    'message': 'Hello',
    'timestamp': ISODate()
  }],
  'tail': [{
    'message': 'Hello',
    'timestamp': ISODate()
  }]
}
```

```
const watch = function (match) {
  check(match, RegExp);
  let future = new Future();
  Connections.find({
    'name': 'messages',
    'tail.message': { $regex: match }
  }).observeChanges({ changed: future.return });
  return future.wait();
}
```

This method watches for the given messages being tailed. However, it never seems to work, but on `meteor.mongo` it does return results.

**Comment by rclai** [comment]
That is not the right way to use future return. You need to pass a function for the changed callback and inside of it use future return.

**Comment by AlexFrazer** [comment]
Doesn't work when I do it that way either. It simply never is accessed

**Comment by rclai** [comment]
In addition you should store the value that is being waited on so that you can stop the observer before returning otherwise you will have a memory leak.

**Comment by AlexFrazer** [comment]
Yep, I simplified it because no one wants to read tons of code. I resolve it in the `future.resolve(() => observer.stop())`

**Comment by stubailo** [comment]
I think all of the future logic is obfuscating the code that might actually be experiencing a bug; also, I'm not sure exactly what you mean by "never seems to work". It would be helpful if you could create a simple reproduction of this behavior that I could run on my machine, with a description of what you are expecting to happen and what actually happens, as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
