### ISSUE TITLE
Issue after "meteor publish" from Windows 10: No compatible binary build found for this package

### ISSUE THREAD

**Issue by michaelbromley** [meteor/meteor#5489]
I maintain a package which is used in the angular-meteor project, [`angularutils:pagination`](https://atmospherejs.com/angularutils/pagination). I used `meteor publish` on [this version](https://github.com/michaelbromley/angularUtils-pagination/tree/b5403041a5cced2098dddf2bcb6990c5b941a348) of the source files and it seemed to publish okay.

I then got the [following issue reported on my repo](https://github.com/michaelbromley/angularUtils/issues/247) (with several duplicates), and also got the error myself:

When running `meteor add angularutils:pagination` against the 0.9.1 meteor package, the console output:

```
Errors while adding packages:

While checking for angularutils:pagination@0.9.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

After speaking with Uri Goldshtein, we thought it may be to do with the fact I am publishing from Windows 10. 

He then published the same source files (the only change being the angular dependency, `1.2.24` -> `1.4.0`), as version 0.9.1_1. This then fixed the issue, i.e. I could now successfully `meteor add angularutils:pagination`.

So the issue itself is now fixed, but he recommended I file an issue with Meteor as something to look into - we don't know for sure whether the issue was caused by a bad dependency (angular), or the fact I published from a Windows 10 machine. Or something else.

My machine specs: Windows 10 Home, core i7-3735U.

**Comment by avital** [comment]
I can't see how this is due to different versions of Windows as Meteor just records the architecture of the package, which is one of:
  os.osx.x86_64
  os.linux.x86_64
  os.linux.x86_32
  os.windows.x86_32

But here's my real question: Why would you need a binary build for your package? That should only be necessary for packages that use NPM modules that have binary dependencies. It looks like your package doesn't depend on any NPM modules.

Could it be that you're using a version of Meteor checked out from Git rather than the officially installed Meteor? What do you get when you run `meteor --version`?

**Comment by michaelbromley** [comment]
I've no idea why it needs a binary build. I have very little Meteor knowledge - I just publish this single package because Uri uses it in his angular-meteor tutorial.

I installed Meteor using the windows installer from meteor.com. When I run `meteor --version` I get `Meteor 1.2.0.2`.

**Comment by abernix** [comment]
In an effort to clean up some older issues, I'm closing this as it hasn't got any traction in a while and publishing binary dependencies on Windows 10 has been known to work recently and was working well in Meteor 1.3.5.1.  Also, Meteor 1.4 has changed the necessity of this dramatically so I'd recommend moving toward 1.4 if you are still having problems.  Happy to reopen if you're still experiencing issues.
