### ISSUE TITLE
Template.parentData() in event handlers can't access the parent data context in the same template

### ISSUE THREAD

**Issue by lirbank** [meteor/meteor#5491]
**_2 Upvotes**_ Relates to https://github.com/meteor/meteor/issues/3249
and possibly https://github.com/meteor/meteor/issues/5280

Not sure if this is a bug but there is a confusing inconsistency between how parent (and current) data contexts can be accessed via {{../}} and via an event handler. 

From an event handler Template.parentData() can only access the data context of a _parent template_ (i.e. the element that fires the event have to be wrapped into a separate child template), not the parent data context in the _same template_. 

But {{../}} can access the parent data context, regardless if it's in the same template or in a parent template. 

I was for a while thinking that perhaps Meteor has both a concept of _data contexts_ (defined by by `{{#with}}` or `{{#each}}`) and another concept of _template data_ (defined by `<template>`), but it doesn't seem right. Looking at http://docs.meteor.com/#/full/template_parentdata it says Template.parentData() is used to "Accesses other data contexts that enclose the current data context." and "Template.parentData(2) is equivalent to {{../..}} in a template.", which would then not be true.
- Clone this repo https://github.com/lirbank/meteor-data-context-test.git (vanilla Meteor 1.2.0.2)
- Observe the browser console as you click the two buttons.
- Please note that both buttons share the same event handler function.

Hope this is helpful, happy to provide more details if needed.

**Comment by lirbank** [comment]
Just upgraded the repo to Meteor 1.2.1, same behavior.

**Comment by mitar** [comment]
Yes. It is pretty confusing. This is why in Blaze Components I introduced what you call "template data". So you have template-level data context and current data context.

**Comment by lirbank** [comment]
This? https://atmospherejs.com/peerlibrary/blaze-components

**Comment by mitar** [comment]
Yes.

**Comment by lirbank** [comment]
Awesome!

**Comment by timbotnik** [comment]
@lirbank Agreed this is confusing.  Luckily you have implemented a great workaround by creating a sub-template.

**Comment by lirbank** [comment]
If you want to avoid creating extra templates, another workaround is to pass data from the outer context to an html element in the inner context, in the same template.

```handlebars
{{#each companies}}
  {{#each employees}}
    <a href="" companyId="{{../id}}">Do something</div>
  {{/each}}
{{/each}}
```

Now the company ID can be accessed from the event handler with something like `$(event.currentTarget).attr('companyId')` and employee ID with `this._id`.

**Comment by oskareke** [comment]
+1 This is confusing, should be fixed or clarified in the docs if this is the expected behaviour.

**Comment by citylims** [comment]
+1 this is a glaring oversight

**Comment by hwillson** [comment]
Migrated to meteor/blaze#193 - closing here - thanks!
