### ISSUE TITLE
File change delay before recompilation

### ISSUE THREAD

**Issue by fusepilot** [meteor/meteor#5494]
**_1 Upvote**_ Editing a client side file in a clean install of the todo example with 1.2.0.2 takes about 5s until the browser reloads. And in the first 3s, nothing seems to be happening. The actual compilation seems to be quick once it finally starts.

Here's the output when running `env METEOR_PROFILE=50 meteor run` and editing the `lists-show.html` file. This doesnt appear until in the terminal until about 3s after the file change.

```
| Select Package Versions: 2350.5
|     Input#loadFromCatalog (sqlite): 2271.0
|     other Select Package Versions: 76.9
|
| Input#loadFromCatalog (sqlite): 2271.0
| other Select Package Versions: 76.9
| Total: 2347.9
|
| Rebuild App: 665.4
|     compiler.compile(the app): 90.6
|     bundler.bundle..makeClientTarget: 451.9
|         Target#make: 451.9
|             Target#_runCompilerPlugins: 64.5
|             Target#_emitResources: 192.8
|                 PackageSourceBatch#getResources: 187.3
|                     PackageSourceBatch#_linkJS: 184.8
|                         files.readFile: 67.6
|                         other PackageSourceBatch#_linkJS: 106.6
|             ClientTarget#minifyCss: 140.7
|     bundler..writeTargetToPath: 117.2
|         ClientTarget#write: 115.8
|             other ClientTarget#write: 90.5
|
| ClientTarget#minifyCss: 140.7
| other PackageSourceBatch#_linkJS: 106.6
| other ClientTarget#write: 90.5
| files.readFile: 83.7
| Total: 421.5
```

Is this large delay normal behavior?

OSX 10.11
MacPro 3 GHz 8-Core
500 GB APPLE SSD
64 GB 1866 MHz DDR3 ECC

**Comment by benjamn** [comment]
After instrumenting the file watcher code with `console.log`s, I believe file change notifications are indeed firing almost immediately, and most of the delay is attributable to [this `bundleApp()` call](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/runners/run-app.js#L785).

This deserves further profiling and investigation, since I'm afraid it doesn't look like a quickly fixable issue with file watching.

**Comment by activeperception** [comment]
+1

**Comment by hwillson** [comment]
Meteor 1.4.2 introduced many new build tool performance improvements. I'll close this for now, but if you notice similar issues with the latest version of Meteor, please post back and we'll re-open. Thanks for posting this originally!
