### ISSUE TITLE
Add a principled way to print warnings from the Meteor build tool

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5495]
I'm trying to convert the error I added in `1.2` about `api.addFiles` with the `isAsset` option into a warning, but there isn't a reasonable way to do it.

The issue about that is #5458 

`buildmessage` does support the idea of tagged messages, but the entire system seems to be built around the idea that a message is always an error. Here are some changes that could improve the situation:
1. Make `buildmessage.error` tag the added message as an `"error"`
2. Make a method `MessageSet#hasErrors` that checks this tag only (along with `Job#hasErrors`) and use this everywhere `hasMessages` is used now (since until now it always checked for errors
3. Add `buildmessage.warning` which tags as `"warning"`
4. Add `hasWarnings` like `hasErrors` above
5. Modify the places that print build message errors to also know how to print warnings
6. Add some build warnings around deprecated build plugin APIs, so that people update their code eventually

For now, I'm going to just remove the error and have the old API silently succeed, so that people don't need a ton of if statements in their `package.js` files.

**Comment by abernix** [comment]
Public Service Announcement: Even if not terribly in demand, this would be a good PR for someone looking to contribute to Meteor.  It's well outlined, and reasonable for a first-timer.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20principled%20way%20to%20print%20warnings%20from%20the%20Meteor%20build%20tool&body=Migrated%20from:%20meteor/meteor%235495) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
