### ISSUE TITLE
Meteor.loginWithFacebook callback not fired on Cordova when canceled

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5498]
cordova:

![](http://g.recordit.co/8CN82VqCwg.gif)

chrome:

![](http://g.recordit.co/vvpOYQgOPf.gif)

safari and ios safari use a redirect because they block popups. so they both work fine as well.

![](http://g.recordit.co/F1R3I4n66f.gif)

Seems to be an issue just with Cordova...

**Comment by martijnwalraven** [comment]
Would it be possible to post a reproduction for this? Preferably a minimal project that I can use to investigate the issue.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5498#issuecomment-150274142, if someone is able to post a reproduction demonstrating this, that will greatly help with troubleshooting. Closing until then - thanks!
