### ISSUE TITLE
Update the docs to say you need to add the `check` package manually starting in Meteor 1.2

### ISSUE THREAD

**Issue by willoughby** [meteor/meteor#5502]
It looks like **check** is no longer available client side, they say anywhere in the docs http://docs.meteor.com/#/full/check

**Comment by willoughby** [comment]
Just a follow up, this was okay in 1.1

**Comment by stubailo** [comment]
I just created an app with `meteor create`, added `check`, and it was definitely available in the browser console. Perhaps, you are running into the fact that it is no longer included by default in new apps; you need to add the `check` package.

We should document that.

**Comment by willoughby** [comment]
Yeah that sounds right. Thanks.

**Comment by abernix** [comment]
The need to add `check` manually is now documented in the [new docs](http://docs.meteor.com/api/check.html).  Thanks for bringing this to our attention!
