### ISSUE TITLE
Minor bug: private folder is not packaged when no server sources are available

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#5504]
I have made a simple test project and organized my files into

```
+ client/
    sample.js
    sample.html

+ public/
    logo.png

+ private/
    config/
      public.yaml
```

and used our [4commerce:env-settings](https://github.com/4commerce-technologies-AG/meteor-package-env-settings) package to define app settings to `Meteor.settings.public`

So I was wondering that the file `public.yaml` was not available in the build bundle.

When I created (without any content, joust `touch`) a file like

```
dummy.js
```

or

```
+ server/
    dummy.js
```

all was packaged and is working.

So this might not be a huge bug, but if you are designing just a client app and use packages, those might not work in case of this.

**Comment by martijnwalraven** [comment]
It seems this behavior does make sense if you look at the public API. Code in `private` is only accessible using the Assets API from server code, so if there is no server code there is no need to include the files. From the docs: 'Packages can only access their own assets'.

In your `4commerce:env-settings` package however, you're directly accessing the file system. I understand what you're trying to do, and it might work in most cases, but it's not actually supported. 

So you may want to look at alternatives. I mentioned this to @sashko, and he suggested that writing a build plugin might be more suitable for your use case.

**Comment by TomFreudenberg** [comment]
Well, I take your feedback and that's generally ok for me. I will write a note to the README at the package to inform the user about that case. At least it will be a relative seldom and unusual situation that someone does not create any (shared) server code.

The option to write a build plugin is an interesting idea, I will check that in case of effort and functionality.

You may close this issue or leave it as a state you like, I am fine with your answer.

Cheers
Tom
