### ISSUE TITLE
Allow comments in .Meteor/cordova-plugins

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#5506]
e.g. like this

cordova-plugin-screen-orientation@1.4.0
cordova-plugin-statusbar@0.1.10
fr._46cl.focus@https://github.com/46cl/cordova-android-focus-plugin.git#da668f4249217655a572a49e13496c1947573c39
imeiplugin@1.0.1
com.chariotsolutions.nfc.plugin@0.6.2
cordova-plugin-network-information@1.0.1
# below plugins are not needed, but for future use since hot code push cannot update plugins

mx.ferreyra.callnumber@https://github.com/Rohfosho/CordovaCallNumberPlugin.git#3dad50b5dfc292f0a20088b6d5a5dfa9b0b795ee
cordova-plugin-camera@1.2.0
cordova-plugin-geolocation@1.0.1
cordova-plugin-media@1.0.1
cordova-plugin-globalization@1.0.1
cordova-plugin-battery-status@1.1.0
cordova-plugin-vibration@1.2.0
cordova-plugin-bluetooth-serial@0.4.4
cordova-plugin-ble-central@1.0.1
# causes reload loops
# com.percolatestudio.cordova.safereload@https://github.com/percolatestudio/cordova-plugin-safe-reload.git#5f403974324314f5b779fe86f361aa5a6bc11643

**Comment by martijnwalraven** [comment]
I see how this could be useful, but especially since most people won't be viewing or editing `.meteor/cordova-plugins` directly, I'm going to treat it as a low priority feature request. If you feel this is something that is important to you, feel free to work on a pull request.

**Comment by stubailo** [comment]
I feel like we should standardize on a new configuration format for all of our config files that supports comments and is easily machine-parseable. (Shame JSON doesn't have comments, and YAML is too complex. any other options?)

**Comment by obiwarn** [comment]
@stubailo What about YAML? It has JSON as a subset + comments.
https://en.wikipedia.org/wiki/YAML

However, just a simple 
`# Comment`
would make debugging much easier.

**Comment by fabyeah** [comment]
+1

I have added several plugins for very specific uses. It would be nice to add comments, the same way as in the .meteor/packages file.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20comments%20in%20.Meteor%2Fcordova-plugins&body=Migrated%20from:%20meteor/meteor%235506) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
