### ISSUE TITLE
Fatal error in Meteor.setTimeout callback: userId doesn't seem to be available.

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#5507]
```
Exception in setTimeout callback: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
```

I'm in a setTimeout() created by a method and getting this error.  Meteor is telling me to use this.userId, even though it's not defined.

So, is there a technical reason we can't use Meteor.userId()?  There's this split for methods and publish, but what does that actually accomplish?  

Can we get rid of this split and have function that works everywhere?  This feels like an API bug.

What's the workaround?

Thanks for what you've already accomplished, it's incredibly useful.

Mike

```
Exception in setTimeout callback: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20151022-10:34:19.673(-5)?     at AccountsServer.userId (accounts_server.js:80:13)
I20151022-10:34:19.674(-5)?     at Object.Meteor.userId (accounts_common.js:222:19)
I20151022-10:34:19.674(-5)?     at Object.Schema.Opportunities.SimpleSchema.log.autoValue (lib/shared/collections/5_Opportunities.js:69:1)
I20151022-10:34:19.674(-5)?     at Object.runAV (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1181:1)
I20151022-10:34:19.674(-5)?     at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1282:1
I20151022-10:34:19.674(-5)?     at Array.forEach (native)
I20151022-10:34:19.674(-5)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
I20151022-10:34:19.674(-5)?     at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1281:1
I20151022-10:34:19.674(-5)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
I20151022-10:34:19.674(-5)?     at [object Object].getAutoValues (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1244:1)
```

The code was working with `autoValue` in SimpleSchema.  (I had the wrong code here, and refactored it away trying to fix it.)

**Comment by MichaelJCole** [comment]
Here's a SO discussion on this:  https://stackoverflow.com/questions/15329759/accessing-this-userid-not-working-when-calling-from-within-meteor-settimeout

**Comment by martijnwalraven** [comment]
Can you give a little more context on what you are trying to accomplish?

I'm not overly familiar with this bit of the code, but I found the following comment in `accounts_server.js` that explains why using `this.userId` is necessary:
```javascript
    // This function only works if called inside a method. In theory, it
    // could also be called from publish statements, since they also
    // have a userId associated with them. However, given that publish
    // functions aren't reactive, using any of the infomation from
    // Meteor.user() in a publish function will always use the value
    // from when the function first runs. This is likely not what the
    // user expects. The way to make this work in a publish is to do
    // Meteor.find(this.userId).observe and recompute when the user
    // record changes.
```

**Comment by MichaelJCole** [comment]
Ok, that's super interesting, thanks!

Here's what I'm trying to accomplish:

1) There is a collection of "Opportunities".  
2) A Meteor method createOpportunity() adds one to the collection.
3) createOpportunity sets a timer using Meteor.setTimeout()
4) People can claim the opportunity through another Meteor method.  That method uses Meteor.userId() for Access Control, and to log actions.
5) If the timer runs out, there's a change in status and a log entry.

The error came up in a previous implementation of 5).  log() was using Meteor.userId() "under the covers", instead of taking userId as a parameter.  For my application, logging the userId isn't that critical.  At that point these are "system" actions, so I can ignore it.

But for some applications, getting the userId may still be critical to determine access control.  I can't put that on the Opportunity, because multiple users are interacting with that object.

So the application would need to get userId inside the Meteor.setTimeout.  I think the workaround is to use a closure (set a variable outside the setTimeout() and reference it inside the setTimeout()).  

Why doesn't Meteor.setTimeout() create a closure to handle this?

Also, why doesn't Meteor.userId() return this.userId if that's the appropriate place to get the data?

It's just a tricky API to get this most basic piece of data, the user for the current method/request.

That said, what's already been implemented is great and I'm thankful :-)
