### ISSUE TITLE
Implementation of includeZero for {{#if}} statement is missing

### ISSUE THREAD

**Issue by cluxter** [meteor/meteor#5508]
Hi

When a helper returns a value equals to 0, the {{#if}} statement treats it as a false value. So when you want to conditionnaly display a value which might be equal to 0, you can't do it easily (you have to create another helper which is annoying and polutes the code).

For example:

```
{{#if anyvalue}}
{{anyvalue}}
{{else}}
<p>Loading value, please wait</p>
{{/if}}
```

will always display "Loading value, please wait" when anyvalue returns 0.

Handlebars added an option a couple of years ago to allow the developper to treat 0 as a true value, like this:

```
{{#if anyvalue includeZero=true}}
{{anyvalue}}
{{else}}
<p>Loading value, please wait</p>
{{/if}}
```

You can see the implementation here: https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/helpers/if.js#L10

It would be awesome to have this option in Spacebars too.

**Comment by cluxter** [comment]
I found an elegant solution, which is actually better than implementing this option.
In the helper, I convert the Number to a String when I return it, using the .toString() method. This way the {{#if}} statement sees the value as a "0" instead of a 0 and displays it properly.

**Comment by stubailo** [comment]
I think this package solves this problem nicely: https://github.com/raix/Meteor-handlebar-helpers

The code would look like this:

```html
{{#if $exists 0}}
  {{anyvalue}}
{{else}}
  <p>Loading value, please wait</p>
{{/if}}
```

I think the current behavior of `#if` in Spacebars is fine, since it's consistent with JavaScript.
