### ISSUE TITLE
Too many subscriptions on reconnect with GSM

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#5509]
My cordova app uses rather large DBs.

When I disable wifi and test my app on GSM my provider seems to reconnect the connection every 2-10 minutes. This causes a lot of traffic since all subscriptions are updated every time.

**Comment by martijnwalraven** [comment]
Especially on mobile connections, you'll have to be prepared for frequent reconnects. As you mentioned, that means all active subscriptions have to be reestablished. Try to limit the data you subscribe to so you only load what is needed at a specific point in the app.

**Comment by obiwarn** [comment]
Sadly I need a large DB. Is there a best practice for caching data?

**Comment by martijnwalraven** [comment]
Well, the best practice is to only subscribe to the data you need :) This is true on web as well, but even more important over mobile connections. When you say you need a large DB, what do you mean by that?

**Comment by obiwarn** [comment]
The device with my app is in a store.
A user comes in and scans a NFC tag and has to enter a code on the device.
The store has a very slow internet connection, so I need to cache all tags (5000) and codes (400) on the client for quick response times.
Codes change frequently. Some new tags get added every now and then.

**Comment by martijnwalraven** [comment]
Thanks for explaining your use case. Unfortunately, Meteor subscriptions are not really suitable for offline usage at this point. 

You may be able to use a community package like [GroundDB](https://github.com/GroundMeteor/db) to work around this. 

Depending on how often the data changes and how important realtime updates are, an alternative may be to store the data locally as CSV files and transfer them over regular HTTP.

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
