### ISSUE TITLE
Data Parameter not captured by Router

### ISSUE THREAD

**Issue by VikR0001** [meteor/meteor#5510]
Using the hash parameter works as expected.

In index.html:

> {{#ionItem path="lists" hash="categoryName" iconLeft=true iconRight=true}}

In router.js:

>this.route('lists', function() {
>    this.subscribe('database');
>    this.render('lists', {
>    data: {
>        data: this.params.hash
>    }
>    })
>});

In the template helper:

>aHelperFunction: function () {
>   var parameter = this.data;
>   return ;
>}

However, using the data parameter does not appear to work.

In index.html:

> {{#ionItem path="lists" data="categoryName" iconLeft=true iconRight=true}}

In router.js:

>this.route('lists', function() {
>    this.subscribe('database');
>    this.render('lists', {
>    data: {
>        data: this.params.data
>    }
>    })
>});

In the template helper:

>aHelperFunction: function () {
>   var parameter = this.data;
>   return ;
>}

**Comment by stubailo** [comment]
Hey, this doesn't look like a bug in the core Meteor framework represented by this repository. Which router are you referring to?

**Comment by VikR0001** [comment]
I'm a Meteor newbie. :) It's Iron Router.

**Comment by stubailo** [comment]
I think the best thing would be to ask about this on the forum: https://forums.meteor.com/c/help

**Comment by VikR0001** [comment]
Okay, thanks.
