### ISSUE TITLE
Anyway to play inline video in cordova?

### ISSUE THREAD

**Issue by vacarsu** [meteor/meteor#5511]
I'm trying to play video from collectionFS or cordova capture plugin however all I get is the following:

![screenshot_2015-10-22-10-28-50](https://cloud.githubusercontent.com/assets/11384972/10672979/4be6df18-78a8-11e5-895e-f6ed8adb2d2d.png)

Is this possible, I have tried every kind of browser policy/access rule I can think of.

**Comment by martijnwalraven** [comment]
You can play inline video from other servers, but unfortunately not from the local filesystem. This is a restriction of the Meteor file serving plugin that I'm currently fixing with a rewrite.

**Comment by adrianolsk** [comment]
Where are you video hosted? Is it on Amazon S3?
I had a problem some time ago trying to load content from S3 to manipulate
with a JQuery crop plugin, the problem was cross origin problems.
The solution was add CORS permissions to the S3 bucket I was using.

**Comment by vacarsu** [comment]
Videos are currently hosted from meteor hosting. @martijnwalraven  I get for local videos, but what about videos from CollectionFS (/cfs/files/...)

**Comment by martijnwalraven** [comment]
I believe this may have been fixed in Meteor 1.3. A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
