### ISSUE TITLE
Add files only if a package with weak dependency is used in the app

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#5513]
Sometimes, files are only needed if another package exists. For example, I might have a package that adds feature a, but if I have an admin panel installed, it also adds a page to the admin panel to manage the feature.

Or a package could only add the css files it needs depending on the framework the app uses.

An api might look like: 

``` js
Package.onUse(function(api) {
    api.use('packageName', {
        weak: true
    });
    if (api.packageAdded('packageName')) {
        api.addFiles(['optionalFile.css', 'optionalFile.js']);
    }
})
```

**Comment by stubailo** [comment]
This would require some significant changes to the way packages work, so it's not likely that it will be implemented in the near future. Perhaps some upcoming work on modules and dead code elimination could make it OK to export _all_ of the integrations, and then the ones that aren't used will automatically not be loaded on the client. See here: https://github.com/meteor/meteor/issues/4310

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20files%20only%20if%20a%20package%20with%20weak%20dependency%20is%20used%20in%20the%20app&body=Migrated%20from:%20meteor/meteor%235513) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
