### ISSUE TITLE
Streamline release process to avoid manual management of version numbers

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5515]
I've been doing release management for Meteors `0.9.4`, `1.1`, and `1.2`, and every single time we do a release we initially mess up some of the version number changes. I think this should be done automatically and should be easier to do correctly, with more checks in between. Some ideas:
1. Make sure a version number isn't decreased in a newer release (when you accidentally change `1.1.3` to `1.1.3-rc.0`, which should actually be `1.1.4-rc.0`)
2. Explicitly mark wrapper packages and make some sane strategy for them, since right now you can't combine wrapper versions and pre-release versions in the right way
3. Make the tool automatically increment numbers, with some way of indicating cases where a special version number change is necessary, for example for major version bumps

I have a useful tool already: `meteor admin check-package-versions` which checks if the current versions are the newest, possibly a solution for (1)

This would make it much easier to have a faster Meteor release cycle, which benefits everyone.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Streamline%20release%20process%20to%20avoid%20manual%20management%20of%20version%20numbers&body=Migrated%20from:%20meteor/meteor%235515) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
