### ISSUE TITLE
Error: launch-screen + accounts-facebook cause 5sec timeout in cordova

### ISSUE THREAD

**Issue by hlehmann** [meteor/meteor#5522]
I notice a 5 sec timeout making the app launch very slow on cordova.
After multiple tests I found it comes from launch-screen when it is with accounts-facebook but I can't figure out why exactly.

**Comment by martijnwalraven** [comment]
Without a way to reproduce your issue, there is no way for me (or anyone else) to investigate and solve it. So if you can, please try to create a minimal project that shows the behavior you are experiencing.

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
