### ISSUE TITLE
Submission to app store failing with apps built via Xcode 7

### ISSUE THREAD

**Issue by timbotnik** [meteor/meteor#5525]
Encountered this when submitting a new version to the App Store.  The submission fails with a message like `Invalid Bundle: iPad Multitasking...` as described in this thread:

https://forums.developer.apple.com/thread/17777

I think this is another Cordova-related issue keeping up with Xcode 7 / iOS9, and one quick fix is to add `UIRequiresFullScreen:YES` to the .plist file.

**Comment by martijnwalraven** [comment]
The issue seems to have been fixed on cordova-ios master: https://issues.apache.org/jira/browse/CB-9729. We should be able to update to Cordova iOS 4.0 for Meteor 1.3.

For now, adding `UIRequiresFullScreen` to the .plist file manually is probably the best workaround.
