### ISSUE TITLE
meteor add [package]@[version] fails immediately on finding a different version when using local packages

### ISSUE THREAD

**Issue by marcuscarr** [meteor/meteor#5526]
If I have multiple versions of packages in PACKAGE_DIRS, meteor throws an error immediately if it finds a package where the name matches but the version does not. [Miminal app](https://github.com/marcuscarr/package-version-bug-app) to reproduce the bug, run `meteor add my-package@=0.0.1`

I would expect meteor to look at all packages before throwing an error.

**Comment by stubailo** [comment]
Yes, I think this is a "convenience" aspect of `PACKAGE_DIRS` - it expects that you are developing a package locally, and therefore doesn't worry about looking for multiple copies of it. This combines with the version solver interpreting the exact version constraint and showing this error.

I think this shows the limits of the band-aid approach of PACKAGE_DIRS to local package development - it's not a great solution in all cases. Perhaps there is a simple solution that will make this work, but at the end of the day I think we need a better way to work with local packages.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=meteor%20add%20%5Bpackage%5D%40%5Bversion%5D%20fails%20immediately%20on%20finding%20a%20different%20version%20when%20using%20local%20packages&body=Migrated%20from:%20meteor/meteor%235526) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
