### ISSUE TITLE
Allow Cordova hot code push to use a CDN

### ISSUE THREAD

**Issue by motomux** [meteor/meteor#5527]
**_5 Upvotes**_ bundledJsCssPrefix is disabled for cordova, so code push after deploying new source code.

[meteor/packages/webapp/webapp_server.js:274](https://github.com/meteor/meteor/blob/412e502fa9ec9e794b05e7faf2d071cf818a48fc/packages/webapp/webapp_server.js#L274)

```
  var jsCssPrefix;
  if (arch === 'web.cordova') {
    // in cordova we serve assets up directly from disk so it doesn't make
    // sense to use the prefix (ordinarily something like a CDN) and go out
    // to the internet for those files.
    jsCssPrefix = '';
  } else {
    jsCssPrefix = bundledJsCssPrefix ||
      __meteor_runtime_config__.ROOT_URL_PATH_PREFIX || '';
  }
```

According to the comment, it doesn't need to use prefix for CDN and etc, but client needs to download bundled js and css after new source code is pushed.

Thanks!

**Comment by martijnwalraven** [comment]
The code you quote makes sense, because Cordova apps always load their assets from disk. So this should definitely not be changed. 

A separate issue is whether the Hot Code Push mechanism should be aware of `bundledJsCssPrefix` when it downloads new assets (which it stores to disk). Are you experiencing any difficulties when downloading assets from the origin server instead of from a CDN?

**Comment by motomux** [comment]
As you said, this would be the separate issue.

The reason why I want to deliver assets from CDN is that I'm showing a loading screen while hot code push for avoiding to let people see white screen, and I want to make it as short as possible.
We also provide our app to entire world so it's kind of slow to downloading assets for people in the foreign country.

**Comment by HQingYi** [comment]
we also need the hot code push to support the `bundledJsCssPrefix`.

**Comment by denisbabineau** [comment]
+1, my use case is for when we send out push notifications, which will cause a lot of users to open the app at the same time, potentially triggering a huge spike in HCP requests which would ordinarily be somewhat low.

**Comment by lorensr** [comment]
This would be great. While it's certainly less often a concern than websites, sometimes (eg with the [`reloader`](https://github.com/jamielob/reloader) package's `check` option) you leave the launch screen up and wait for an update to download – using the CDN would make the user wait less time.

Also if you get to the large scale, you don't want to burden the app server with file serving.

**Comment by lorensr** [comment]
In addition to the bundled JS and CSS, it would be nice to be able to use the CDN for things in `public/`, so having a way to tell the Cordova plugin to fetch `public/*` from `mycdn.com/*`. (Or could instead assume that with `bundledJsCssPrefix`, you want this done as well.)

**Comment by lorensr** [comment]
@martijnwalraven hoping this could make it onto your roadmap? :) If not, maybe point out which part of the code to change?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20Cordova%20hot%20code%20push%20to%20use%20a%20CDN&body=Migrated%20from:%20meteor/meteor%235527) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
