### ISSUE TITLE
Provide a way to force a connection's (or all connections' for a user) subscriptions to rerun

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5529]
When you call `setUserId()`, the subscriptions for the current connection re-run. This is a neat feature but  doesn't cover the totality of use cases where authorization logic changes. For instance a user's permissions may change once they validate their email.

Rather than build out a fully reactive publication mechanism[1], a simple solution would be to have a hook that server-side code could call to rerun all subs on a connection or for a user.

[1] like https://atmospherejs.com/lepozepo/reactive-publish

**Comment by mitar** [comment]
I think reactive approach is better. ;-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20a%20way%20to%20force%20a%20connection's%20(or%20all%20connections'%20for%20a%20user)%20subscriptions%20to%20rerun&body=Migrated%20from:%20meteor/meteor%235529) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
