### ISSUE TITLE
ctrl-c does not work on a Windows build farm machine during publish-for-arch

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5532]
Doing:

```
meteor admin get-machine os.windows.x86_32
meteor publish-for-arch <package name>
```

There is no way to cancel it with ctrl-c once the second command starts.

**Comment by stubailo** [comment]
SSH into a Windows machine is really hard to get working properly - I don't really know how to fix it. I'm open to any suggestions.

**Comment by hwillson** [comment]
Give the age of this issue, and it's low interest / activity, as part of the on-going old issue cleanup process, I'll close it off. The fact that ctrl-c doesn't work on a Windows build farm machine is a bit annoying, but the chances of this issue being addressed by anyone (MDG and/or the community) are quite low. Happy to re-open if anyone feels differently. Thanks for pointing this out originally!
