### ISSUE TITLE
Strange architecturesOS value for Windows

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5533]
Looking at:

```
meteor show --ejson commongarden:meshblu
```

```
      "architecturesOS": [
        "os",
        "os.linux.x86_32",
        "os.linux.x86_64",
        "os.osx.x86_64"
      ]
```

I assume `os` is Windows? But why such string?

**Comment by stubailo** [comment]
This is probably because the NPM package either:

1. Does not work on Windows, and so does not have any binary build, or
2. Uses an alternate code path on Windows that doesn't have binary dependencies

Basically I think the arch `os` is generated when one of the builds doesn't have a `.node` compiled file.

**Comment by stubailo** [comment]
Am I correct that this isn't really a bug or FR?

**Comment by mitar** [comment]
I think this is a bug. If there is no binary, then it should probably not be even available? So if a package requires a binary and you have to do `publish-for-arch`, how can then be an `os` only entry?

So I published a Windows version, and also if I try to do it again I get:

```
C:\Windows\system32>meteor --release 1.1.0.3 publish-for-arch commongarden:meshblu@1.30.1_2
```

And I get:

```
While publishing package build for commongarden:meshblu:
error: Cannot override existing build
```

So Windows build is there. But it is not on the list of `architecturesOS`. On the other hand, binary-less package:

```
meteor show --ejson peerlibrary:async
```

Has:

```
      "architecturesOS": [
        "os"
      ]
```

So where is Windows listed? How can I as an author of a package know if I have published a binary for Windows without having to just retry?

**Comment by c9s** [comment]
Same here.

**Comment by c9s** [comment]
I have a package https://github.com/c9s/meteor-sharp that wraps "sharp" package, and when I use:

    meteor publish-for-arch c9s:sharp@0.16.2_4

It reports:

```
babel-compiler   added, version 6.9.1_1
c9s:sharp        added, version 0.16.2_4
modules-runtime  added, version 0.7.6_1
underscore       added, version 1.0.9

=> Errors while publishing build:

While publishing package build for c9s:sharp:
error: Cannot override existing build
```

However, if I run `show` command:

```
{
  "exports": [],
  "implies": [],
  "dependencies": [
    {
      "name": "ecmascript",
      "constraint": "0.5.8_1",
      "weak": false
    },
    {
      "name": "isobuild:isopack-2",
      "constraint": "1.0.0",
      "weak": false
    }
  ],
  "name": "c9s:sharp",
  "version": "0.16.2_4",
  "description": "Lovell Fuller's [sharp](http://github.com/lovell/sharp) bindings to the libvips\nimage processing library, packaged for Meteor.\n\nFor full documentation, visit [sharp.dimens.io](http://sharp.dimens.io/).\n\nFor sample use, see the\n[meteor-sharp-demo](https://github.com/bdunnette/meteor-sharp-demo) repository.",
  "summary": "Adds bindings to the libvips image processing library",
  "git": "https://github.com/c9s/meteor-sharp.git",
  "publishedBy": "c9s",
  "publishedOn": {
    "$date": 1480756019375
  },
  "installed": false,
  "architecturesOS": [
    "os"
  ]
}
```

**Comment by c9s** [comment]
Anyway, it used to work. I think this is a bug, can't find any information about wrapping binary modules.

**Comment by hwillson** [comment]
Using `publish-for-arch` is no longer really necessary (as of Meteor 1.4.1). It can still be used, but its use should be quite minimal at this point. Because of this, and due to the age / low interest in this issue, we've decided to close this issue as is. If this becomes more of a problem in the future for some reason, we're happy to re-open. Thanks!
