### ISSUE TITLE
Deprecating packages does not work anymore

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#5534]
**_1 Upvote**_ ```bash
$ meteor admin set-unmigrated matteodem:easy-security
$ meteor search easy-security

Matching packages:
local-test:matteodem:easy-security  DEPRECATED: Protection against attacks by rate limiting remote calls + hooking functionality
matteodem:easy-security             DEPRECATED: Protection against attacks by rate limiting remote calls + hooking functionality

You can use 'meteor show' to get more information on a specific item.

```

Doesn't seem like `set-unmigrated` removes my package from search.
```

**Comment by zol** [comment]
Hey @matteodem, thanks for reporting this. The `set-unmigrated` command actually worked in your case. To test, you run `meteor show matteodem:easy-security` you'll notice that there are no versions shown, as opposed to when you run `meteor show --show-all matteodem:easy-security` and all previous versions are listed. Atmosphere also respects the `unMigrated` flag, so a search there will reveal that the `easy-security` package no longer appears in search results.

However, it is reasonable to expect the package to be hidden when doing a `meteor search` to match the behavior on atmosphere. We would be happy to take a pull request for this.

**Comment by maxkfranz** [comment]
+1

This doesn't seem to be working currently. `meteor admin set-unmigrated <package>` just spins forever

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5534#issuecomment-151640989, deprecating does work. Hiding the deprecated package when doing a `meteor search` is a new feature.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Deprecating%20packages%20does%20not%20work%20anymore&body=Migrated%20from:%20meteor/meteor%235534) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
