### ISSUE TITLE
Example https://www.meteor.com/tutorials/blaze/templates is white paging

### ISSUE THREAD

**Issue by tomtom87** [meteor/meteor#5536]
Just setup a new meteor project with the following 

html:

```
<head>
  <title>Todo List</title>
</head>
 
<body>
  <div class="container">
    <header>
      <h1>Todo List</h1>
    </header>
 
    <ul>
      {{#each tasks}}
        {{> task}}
      {{/each}}
    </ul>
  </div>
</body>
 
<template name="task">
  <li>{{text}}</li>
</template>
```

js

```js
if (Meteor.isClient) {
  // This code only runs on the client
  Template.body.helpers({
    tasks: [
      { text: "This is task 1" },
      { text: "This is task 2" },
      { text: "This is task 3" }
    ]
  });
}
```

I get a white page for output nothing is added to <body> tag, but the meteor js is included. What can I do to rectify this? Thanks in advance

**Comment by zol** [comment]
Hey @tomtom87 - I tried the code you posted above and it appears to work.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Thanks!

**Comment by tomtom87** [comment]
@zol  sorry mate it was a cock up with the IDE! Sorry!
