### ISSUE TITLE
Subclassing Meteor.Error via ES6 extends doesn't work in all browsers

### ISSUE THREAD

**Issue by timbotnik** [meteor/meteor#5538]
Here is the basic repro:

```
BadError = class extends Meteor.Error {
  constructor() {
    super('bad-error', 'badness');
  }
};

const badError = new BadError();
console.log(`here we have ${badError.reason || 'no reason'}`);
```

When using `ecmascript` this code prints `here we have badness` in Chrome and Node (on the server).  However in FFox & Safari, it prints `here we have no reason`.  Perhaps Meteor / Babel does not yet support this kind of subclassing?  If so, what is the preferred way to subclass Meteor.Error?

**Comment by abernix** [comment]
Closing as this works as you would expect in Meteor 1.4.2.3 and in modern browsers.  Thanks for reporting this originally! :smile:
