### ISSUE TITLE
Check reports "Expected string, got object" when null is passed instead of String.

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#5539]
`check(null, String)` throws `errorClass {message: "Match error: Expected string, got object", path: "", sanitizedError: errorClass, errorType: "Match.Error"}`.

It would be nicer (as in "correct" ;-) ) if it didn't say "got object" because, well, `null` is not an Object.

(Meteor 1.2)

**Comment by stubailo** [comment]
Fixed in this PR: https://github.com/meteor/meteor/pull/5545

**Comment by stubailo** [comment]
(The fix will actually be released in whatever the next release is after 1.2.1, maybe 1.2.2 or 1.3)

**Comment by realyze** [comment]
Sweet!

**Comment by realyze** [comment]
BTW I stand corrected, `null` _is_ actually an object. Oh, the wonders of JavaScript. :-)
