### ISSUE TITLE
[REQUEST] Debug on a specific android device from ```abd devices``` list

### ISSUE THREAD

**Issue by sun2rise** [meteor/meteor#5542]
Hi i need to debug while 2 android devices are connected to my mac so when i use `adb devices` on my terminal i have 2 devices...

Is there a way to decide where to debug the app when i do meteor run android-device?

**Comment by martijnwalraven** [comment]
There is no command line option for this right now, but there definitely should be! It's on my to do list, but I'm not sure when I'll get to it.

**Comment by sun2rise** [comment]
Thanks a lot @martijnwalraven !

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BREQUEST%5D%20Debug%20on%20a%20specific%20android%20device%20from%20%60%60%60abd%20devices%60%60%60%20list&body=Migrated%20from:%20meteor/meteor%235542) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
