### ISSUE TITLE
Problems querying collections by exact date

### ISSUE THREAD

**Issue by lscordilis** [meteor/meteor#5544]
I have a collection of things which have start and end dates, like so:

```
{ "_id" : "3DQAvx8zWcdM5Pr5o", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") }
```

In a method, I query a particular document by _id:

```
var thing = Things.findOne({ _id: id });
```

Then later on in the same method, without having changed anything about the returned data:

```
var startDate = thing.startDate;
Things.find({ startDate: startDate });  //returns nothing???
```

I checked to make sure there were no timezone or localization issues by printing the ISODate:

```
console.log(startDate.toISOString());   //returns "2015-10-23T04:00:00Z"
```

and pasting it directly into the mongo shell:

```
db.things.find({ "startDate" : ISODate("2015-10-23T04:00:00.000Z")})
```

And it get the correct output: 

```
{ "_id" : "W4GcQYyMukj3rEhXa", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") }
{ "_id" : "3DQAvx8zWcdM5Pr5o", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") }
{ "_id" : "dsvhbdx2JehqMRuYM", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") }
{ "_id" : "6qXPj8H4bZibSjF7f", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") }
```

So, at this point I'm really scratching my head. I'm wondering if there are any problems or gotchas with the date conversion to ISODate() by the Meteor mongo driver, but I couldn't find anything about it elsewhere besides things I could have done wrong in building my query (which I tested above).

I'm on `Meteor  1.2.0.2` and `aldeed:collection2  2.5.0`

**Comment by stubailo** [comment]
Meteor uses a package called `ejson` to convert JavaScript Date objects into a JSON object that looks something like `{ "$date": 1235 }`. It seems like this is conflicting with Mongo's native Date storage mechanism.

A possible workaround on the server would be to use the `rawCollection` attribute, which will let you access the Mongo driver directly. But then you won't get live queries. So you could do this:

```js
Things.rawCollection().find({ startDate: startDate });
```

We should figure out a way to make this work together with Meteor, perhaps by letting you wrap Date values so that Meteor knows they should be ISODate objects in the database.

**Comment by lscordilis** [comment]
Thanks for the workaround advice and quick response!

I don't need a live cursor for the functionality I'm trying to achieve in this case, so it's not the end of the world. I'll keep it in mind, moving forward.

**Comment by methodbox** [comment]
#5839 opened by me has a similar issue.

I've tried:
```
Trackers.rawCollection().find({callDate: new Date("Dec 16, 2015")})
```
And I get:
```
collection.js:663 Uncaught Error: Can only call rawCollection on server collections(…)
```

This work-around would be helpful, but it doesn't look like you can actually do this on the front-end, which means (I assume) I'll have to implement a Meteor.method to handle this.

**Comment by methodbox** [comment]
Nope, this doesn't work either.

It returns the results in the command line when I console.log it but it returns NOTHING on the front-end.

**Comment by mitar** [comment]
I checked this and I cannot reproduce with the current Meteor version. I did:

```
$ meteor mongo
> db.Things.insert({ "_id" : "3DQAvx8zWcdM5Pr5o", "startDate" : ISODate("2015-10-23T04:00:00Z"), "endDate" : ISODate("275760-09-12T04:00:00Z") })
> db.Things.find().pretty()
{
	"_id" : "3DQAvx8zWcdM5Pr5o",
	"startDate" : ISODate("2015-10-23T04:00:00Z"),
	"endDate" : ISODate("2761-12-09T00:00:00Z")
}
```

```
$ meteor shell
> var Things = new Mongo.Collection('Things');
> var thing = Things.findOne({ _id: '3DQAvx8zWcdM5Pr5o' });
> var startDate = thing.startDate;
> startDate
Thu Oct 22 2015 21:00:00 GMT-0700 (PDT)
> Things.find({ startDate: startDate }).fetch();
[ { _id: '3DQAvx8zWcdM5Pr5o',
    startDate: Thu Oct 22 2015 21:00:00 GMT-0700 (PDT),
    endDate: Fri Dec 08 2761 16:00:00 GMT-0800 (PST) } ]
```

**Comment by methodbox** [comment]
I'm sure it is resolved now - it's been a year.
