### ISSUE TITLE
Meteor methods returning data from dev DB in tests

### ISSUE THREAD

**Issue by NickBusey** [meteor/meteor#5546]
I am attempting to run a jasmine-server-integration test, I have a snippet which empties out the test DB.

I tested that this is working by doing:

		posts = Posts.find({}).fetch()
		console.log "Posts: ", posts
It returns: Posts: []

As expected. All good so far.

However when I call a method via Meteor.call which returns certain data from the database, it's returning Posts that exist in the dev database.

Why are Meteor methods not running off of the test db? Is there any way to fix this? Thanks

**Comment by stubailo** [comment]
I feel like this is an issue best filed on the jasmine server integration package. Which one are you using? Is it @Sanjo's?

**Comment by stubailo** [comment]
Also, to reproduce this issue completely we would need an app that exhibits this problem - the code snippets aren't quite enough to identify the issue.

**Comment by NickBusey** [comment]
It is indeed @Sanjo's and if this is better filed there, I'll happily open an issue there instead.

Either way I'll provide a stripped down example app as soon as I can. Thanks for getting back to me.

**Comment by NickBusey** [comment]
This was my mistake. Sorry about that.
