### ISSUE TITLE
Error when building the app in Xcode 7.1 (7B91b)

### ISSUE THREAD

**Issue by Perroquiet** [meteor/meteor#5549]
I just recently updated my xcode to 7.1. This internal error is shown when building and running on my iPhone 4 iOS v7.1.2 and iPhone 6 plus - iOS v9.1: 
![screen shot 2015-10-27 at 11 11 05 pm](https://cloud.githubusercontent.com/assets/704556/10762438/074c06be-7d01-11e5-858d-99b12223f4c1.png)

Anyone have any issue similar to this one?

I am using Meteor 1.2.1 and node v0.10.38

The following packages in my  `.meteor/packages` are:

insecure
aldeed:collection2
alanning:roles
meteorhacks:aggregate
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
mdg:reload-on-resume
crosswalk

**Comment by martijnwalraven** [comment]
I'm not sure what would cause this internal error to happen, but it sometimes helps to remove the Xcode cache directories in `~/Library/Developer/Xcode/DerivedData`. Let me know if this doesn't work.

**Comment by Perroquiet** [comment]
Thanks @martijnwalraven! It solved the error when I was trying to run on my devices. But when I Product -> Archive the project, the same error is shown back again. I then cleared the cached directory `~/Library/Developer/Xcode/DerivedData` again and it was fixed for some reason.

**Comment by martijnwalraven** [comment]
Going to close this as there hasn't been any activity in a while. Please reopen it if you feel this is still an issue.
