### ISSUE TITLE
A way to extend Spacebars compiler

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5552]
Currently it is not really possible to extend Spacbars compiler because the package loads before other packages on the server and you cannot really monkey-patch it or something. And once you get to your package, it seems all templates are already compiled? It would be great if there would be a way to inject yourself somehow there, or add stuff.

I am looking into this because of https://github.com/peerlibrary/meteor-blaze-components/issues/99. Because I would like to support such syntax:

```
<template name="ButtonComponent">
  <button class="red" onClick="onClick">Click me</button>
</template>
```

Where `onClick` attribute would not be rendered as attribute, but would be removed from HTMLJS and added to an event map for that DOM element once it is rendered.

(The above code would call `onClick` on the component instance for the `click` event.)

**Comment by stubailo** [comment]
Injecting code into build plugins is not currently possible from outside of the build plugin, and I don't think the architecture of build plugins really allows that at all. The correct thing to do here would be to create your own version of the `templating` plugin and ask people to switch to that one. In fact, the templating package is very nicely factored to allow you to easily do just that: https://github.com/meteor/meteor/blob/devel/packages/templating/plugin/compile-templates.js

However, as a personal preference, I would prefer to have an extra attribute in the DOM over having to switch build plugins.

**Comment by mitar** [comment]
If Blaze Components include my `templating` plugin and some other package includes official `templating` plugin, what happens? Which one will be able to process `.html` files?

**Comment by mitar** [comment]
Could package's `imply` help here?

**Comment by stubailo** [comment]
Build plugins are actually per-package. So different packages can easily use different HTML build plugins :]

You can't use both of them in the _same_ app or package though. (Think of an app like a big package that has automatic file loading, it's basically like that internally)

**Comment by mitar** [comment]
OK, so if I have package-based apps, things should work. Great.

**Comment by mitar** [comment]
This is not completely smooth because one has to copy most of the `templating` package around. I split it into two packages to make this easier: https://github.com/meteor/meteor/pull/5903

**Comment by mitar** [comment]
See also: https://github.com/meteor/meteor/issues/5911

**Comment by mitar** [comment]
See also: https://github.com/meteor/meteor/issues/5911
