### ISSUE TITLE
Upgrade to NPM 3 for installing package dependencies

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5553]
There are numerous issues that would be fixed by upgrading to NPM 3, and @benjamn suggests that switching might not be that hard. I'm opening this issue to track this task.

**Comment by stubailo** [comment]
PR here: https://github.com/meteor/meteor/pull/5567

**Comment by hwillson** [comment]
This was done (current Meteor version is 1.4.2.3 which uses npm version 3.10.9). Closing - thanks!
