### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by huttonr** [meteor/meteor#5554]
There is a typo in the documentation for [Package.registerBuildPlugin] (https://github.com/meteor/meteor/blob/88913ce687e1038a6fb9aada46920e23cdb053cd/tools/isobuild/package-source.js#L745).

The line reads: *"An object where the keys are NPM package names, and the keys are the version numbers of required NPM packages"*

Whereas it should read:

*"An object where the keys are NPM package names, and the __values__ are the version numbers of required NPM packages"*

**Comment by stubailo** [comment]
Thanks for the heads up! Please feel free to submit PRs for similar typos.
