### ISSUE TITLE
block on starting app on android device

### ISSUE THREAD

**Issue by larfadin** [meteor/meteor#5557]
I'm running ubuntu 15.10.

I have a meteor project I want to deploy on my android phone (nexus 4).
I've follow the doc for installing android sdk and everything works fine.

I want to install it on my phone.

    meteor run android-device --mobile-server my_project.meteor.com 

But this happened  and never stop:

    [[[[[ ~/Documents/dev/my_project ]]]]]            
    
    => Started proxy.                             
    => Started MongoDB.                           
                                                  
    WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to
             the local server, make sure your device is on the same network, and that the network
             configuration allows clients to talk to each other (no client isolation).
    => Started your app.                          
                                                  
    => App running at: http://localhost:3000/  --> why ??? it's on meteor.com not localhost
     Starting app on Android Device  ---> this never stop after 15min

I have wait 15 minutes and nothing happened. I don't know if something should happened on my phone but there is nothing (of course I have developer mode and debug on my phone).

I don't know if the problem is from here but I've also try to emulate it and there is an error :

    meteor run android

    => Started proxy.                             
    => Started MongoDB.                           
    => Errors executing Cordova commands:         
                                                  
       While running Cordova app for platform Android with options --emulator:
       Error: Command failed:                     
       /home/me/Documents/dev/my_project/.meteor/local/cordova-build/platforms/android/cordova/run
       --emulator
    
       /home/me/Documents/dev/my_project/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
       throw e;
       ^
       ERROR : No emulator images (avds) found.
       1. Download desired System Image by running: /home/me/Android/Sdk/tools/android sdk
       2. Create an AVD by running: /home/me/Android/Sdk/tools/android avd
       HINT: For a faster emulator, use an Intel System Image and install the HAXM device driver
       at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
       at ChildProcess.emit (events.js:98:17)
       at Process.ChildProcess._handle.onexit (child_process.js:820:12)

I think it's a cordova problem but maybe meteor is concerned too

**Comment by martijnwalraven** [comment]
Does anything happen on your device? Does it attempt to start the app, do you maybe get a white screen? Is the app visible using the remote debugger in Chrome?

(To answer your other comment, `meteor run` currently always runs the local server, even if you specify another server to connect to.)

**Comment by larfadin** [comment]
There is absolutely nothing on my smartphone. Just my homescreen

**Comment by martijnwalraven** [comment]
Are you able to run apps using the Android SDK tools? Or maybe plain Cordova if you have that installed?

**Comment by larfadin** [comment]
I have never made android app.

When I try to run `meteor run android` . It crash. (error in my issue)

**Comment by martijnwalraven** [comment]
I didn't mean `meteor run android` but stand-alone `cordova`, but you should be able to get the emulator working as well. From your error message it seems you do not have a suitable `avd` installed. Did you follow the instructions to create on using Android Studio?

**Comment by larfadin** [comment]
Yes I follow the doc and everything was working good, no error

**Comment by martijnwalraven** [comment]
But are you sure you also created a suitable avd (meaning one with SDK 22)?

**Comment by larfadin** [comment]
No, I just follow the doc. I don't know what it is and how to install it. (I've installed SDK 22)

**Comment by martijnwalraven** [comment]
I don't have Android Studio installed right now, but I think the change to SDK 23 might mean that a suitable avd is no longer installed by default. You can find more information about creating an avd [in the Android tools docs](http://developer.android.com/tools/devices/index.html).

**Comment by martijnwalraven** [comment]
Does that mean you managed to get your app running on your device?

**Comment by larfadin** [comment]
Yes I remove android studio and install all the 15go sdk and it works.
It's just android studio which is shit

**Comment by hafizali05** [comment]
hey @larfadin   whats that 15go sdk?  never heard and cant find any docs.
