### ISSUE TITLE
MongoError: '$set' is empty

### ISSUE THREAD

**Issue by epaminond** [meteor/meteor#5558]
Running code like `Contacts.update("t5JrgfdCFF7NvHegp", {$set: { prop: undefined }})` results into an error `update failed: MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}`.

Steps to reproduce:

1. `git clone git@github.com:epaminond/meteor-set-empty-bug.git && cd meteor-set-empty-bug && meteor`
2. In your browser open `localhost:3000`
3. In your browser console run `var id = Contacts.insert({prop: 'test'});`
4. In your browser console run `Contacts.update(id, {$set: {prop: undefined}});`

**Expected result**: update successful
**Actual result**: an error gets thrown: `update failed: MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}`

Running `db.getCollection('contacts').update({_id: 't5JrgfdCFF7NvHegp'}, { $set: { prop: undefined } })` in Robomongo doesn't throw any errors. However afterwards `Contacts.findOne("t5JrgfdCFF7NvHegp").prop` would result into `null` not `undefined`.

**Comment by AlbinoGeek** [comment]
**AFAIK** You are meant to use:

```js
Contacts.update("t5JrgfdCFF7NvHegp", {$unset: { prop: true }})
```

**Comment by stubailo** [comment]
Yes, the correct way is to use `unset` - as you mentioned, even RoboMongo doesn't do the right thing here since it ends up being set to `null` which is definitely not the same as `undefined`.

**Comment by epaminond** [comment]
> even RoboMongo doesn't do the right thing here since it ends up being set to null which is definitely not the same as undefined.

RoboMongo does the right thing and value is set to undefined for me. But after this `undefined` value travels through meteor to the Minimongo it becomes `null`. Is `undefined` valid Mongo value?

**Comment by epaminond** [comment]
@AlbinoGeek, there's a difference: `$unset` operation would result into deleting property key from object, whereas `{$set: {prop: undefined}}` is expected to set property value to `undefined`.

```
_.isEqual({}, {prop: undefined}); // => false
```
