### ISSUE TITLE
DDPRateLimiter is not defined

### ISSUE THREAD

**Issue by brianmingus** [meteor/meteor#5560]
On the client: Uncaught ReferenceError: DDPRateLimiter is not defined
On the server: ReferenceError: DDPRateLimiter is not defined

```coffeescript
addCommentRule =
  userId: (userId) ->
    type: 'method'
    name: 'getessay'

DDPRateLimiter.addRule addCommentRule, 1, 3000
DDPRateLimiter.setErrorMessage "Please wait three seconds"
```

**Comment by brianmingus** [comment]
I don't believe the official documentation mentions that in order to use the rate limiter you must install a special ddp-rate-limiter package.

**Comment by stubailo** [comment]
Yes, we don't do a good job listing in the docs when you need to add a certain package. For example, this is also the case with `ReactiveVar`.

**Comment by abernix** [comment]
Moving this over to the new `docs` repo at meteor/docs#14 now that the [new docs are up](http://docs.meteor.com/).  I will submit a PR for it over there!  Closing.
