### ISSUE TITLE
Error while adding platform Android to Cordova project

### ISSUE THREAD

**Issue by n370** [meteor/meteor#5563]
```
=> Errors executing Cordova commands:         
                                              
   While adding platform Android to Cordova project:
   Cordova error: CordovaError: Platform android already added.
   at
   /Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/platform.js:130:35
   at _fulfilled
   (/Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/n370/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   (If the error message contains suggestions for a fix, note that this may not apply
   to the Meteor integration. You can try running again with the --verbose option to
   help diagnose the issue.)
```

**Comment by martijnwalraven** [comment]
Is there anything more you can tell me about the circumstances under which this happened? Did you successfully add the android platform before? Is this a one time error or is it blocking future runs or builds?

**Comment by n370** [comment]
Hi @martijnwalraven . Thanks for replying so fast to this poorly described issue. Before opening it I searched through meteor/meteor open issues and found issue #5171 that seems to be related somehow to the one I'm facing.

My app is running on meteor version 1.2.1 and my system is a
![screen shot 2015-10-29 at 15 47 02](https://cloud.githubusercontent.com/assets/1547648/10828647/58dab0a8-7e54-11e5-8ac1-020b724b361c.png)

Minutes before it started throwing this error I was able to add the android platform without issues. I even ran the app on my device and in the android simulator. I think it broke when I ran meteor update. I can't make sense exactly when it happened because there was a lot of stuff going on in my local environment. I was debugging another issue related to the angular-meteor app I'm building so I was messing all around. As it is now I'm blocked and I just tried to run it in a newly created meteor app just to get the same error one more time.

**Comment by n370** [comment]
Hey @martijnwalraven I just figured it out. Same situation here as #5317 . I don't know how but there was an Ionic project initialized in the parent directory of my app and that was messing with everything. I cleaned up that files and everything backed to work perfectly again.

**Comment by jaydurga** [comment]
Hi,
    Currently, i am doing a project of creating mobile apps in Mac Os. For that, Apache cordova, node, apache ant and sdk tools,plugins and platforms for iOS and android were added. bash_profile file was updated with the path of sdk tools and apache ant. 
After the above, in order to complete an Android app and open it up, i opened the terminal and typed the following :             

~ bhargavijayaraman$ cd documents
:documents bhargavijayaraman$ cd apps
:apps bhargavijayaraman$ cd helloworld
:helloworld bhargavijayaraman$ cd appfiles
:appfiles bhargavijayaraman$ cordova platform add android
Error: Platform android already added.

I am new to this and am not sure what is causing this. Any help will be appreciated.

Thanks,
jay

**Comment by n370** [comment]
@FagnerNSZ @jaydurga double check if you really don't have any other Cordova app initialized in any sub directory or parent directory of the directory you're currently working on.
