### ISSUE TITLE
http_common - content may be undefined

### ISSUE THREAD

**Issue by ecwyne** [meteor/meteor#5565]
This line caused my application to crash. `content` was undefined and threw error because `.toString()` cannot be called on `undefined`

https://github.com/meteor/meteor/blob/devel/packages/http/httpcall_common.js#L8

To Fix:
```javascript
var contentToCheck = typeof content == "string" || typeof content == 'undefined' ? content : content.toString();
```

**Comment by stubailo** [comment]
Opened a PR with a fix, waiting for tests to run!
