### ISSUE TITLE
error on run android-device after adding crosswalk

### ISSUE THREAD

**Issue by vacarsu** [meteor/meteor#5568]
```
While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/alex/Desktop/cloudfit v1/cloudfit/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /Users/alex/Desktop/cloudfit v1/cloudfit/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR: Failed to launch application on device: ERROR: Failed to install apk to device:     pkg: /data/local/tmp/android-armv7-debug.apk
   Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```

**Comment by martijnwalraven** [comment]
This is a known Android issue unfortunately. You'll have to delete the app from the device and reinstall.

**Comment by vacarsu** [comment]
Unfortunately that hasn't fixed the error. I uninstalled the app, re-added Crosswalk, and tried running on android-device again. Got the same error.

**Comment by vacarsu** [comment]
Oh looks like I got the app running, the uninstall left some fragments I guess. I had to go into storage setting and "uninstall for all users." Now the app continuously crashes when I try to run it.

**Comment by Exilz** [comment]
The crash should not be related to the uninstall you just did.
Uninstalling for all users is mandatory for Android > 5.0, your crash must be something else.

**Comment by vacarsu** [comment]
Well the crash has to do with Crosswalk if I remove Crosswalk and reinstall the app. It works again.

**Comment by Exilz** [comment]
Do you have the nativepagetransitions plugin installed by any chance ?

**Comment by vacarsu** [comment]
No I do not have that plugin installed.

**Comment by aaronroberson** [comment]
I know this adds no value but I'm having the exact same problem. When I uninstall crosswalk the problem goes away. I'm on Meteor 1.2 and trying to run on my Galaxy Tab S with Android 5.0.2

**Comment by brightlylit** [comment]
Is there any update on this? I'm having the same problem

**Comment by yehuda54** [comment]
I am also having the same issue ... after installing crosswalk, my app no longer installs on my HTC One.  Without crosswalk, the app installs and runs just fine

**Comment by martijnwalraven** [comment]
@yehuda54: Have you tried removing the app from the device and reinstalling?

**Comment by yehuda54** [comment]
I just read a post on stackoverflow:

http://stackoverflow.com/questions/33587120/how-to-prevent-meteor-app-with-crosswalk-package-crashing-during-compilation-for

that mentions your suggestion and now everything is working like a charm ... thx

**Comment by ettiennelouw** [comment]
@martijnwalraven thanks your suggestion worked perfectly

**Comment by mattrosno** [comment]
Simply removing the app and reinstalling didn't do it for me. I had to remove Crosswalk so that I could install the app, "Clear Data" from settings, then uninstall the app. Following that I could add Crosswalk then install the app on device.

A device restart didn't free whatever resources were getting tied up. I had to "Clear Data" from the properly installed app then uninstall the app, add Crosswalk, install app.

**Comment by Kromahtique** [comment]
It seems like crosswalk is not compatible with the embeded android version of Cordova. What works for me is to uninstall the current android platform and replace it with version 5.0.0

`cordova platform remove android
cordova platform add android@5.0.0
...`

**Comment by martijnwalraven** [comment]
@Kromahtique: Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
