### ISSUE TITLE
Getting really bad performance on hot code pushes

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#5569]
I just timed my project, from the moment I hit save to the time the browser reloaded: 25 seconds! 35 seconds on another test run on a project that has almost no code in it. Hot code pushes used to take about 3-5 seconds for this project before Meteor 1.2.1.

I'm on an Early 2009 Mac Pro, using Meteor 1.2.1. My packages in this project:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

react
kadira:react-layout
twbs:bootstrap
fourseven:scss
jagi:astronomy
stevezhu:lodash
meteorflux:dispatcher
meteorflux:appstate
static-html
xolvio:cucumber
kadira:flow-router-ssr
meteorhacks:cluster
ffxsam:timestamp-log
http
```

And versions:

```
accounts-base@1.2.2
amplify@1.0.0
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
chuangbo:cookie@1.1.0
coffeescript@1.0.11
cosmos:browserify@0.8.1
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
es5-shim@4.1.14
fastclick@1.0.7
ffxsam:timestamp-log@1.0.1
fourseven:scss@3.4.1
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
jagi:astronomy@1.1.5
jquery@1.11.4
jsx@0.2.3
kadira:flow-router-ssr@3.5.0
kadira:react-layout@1.4.1
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
meteor@1.1.10
meteor-base@1.0.1
meteorflux:appstate@1.2.2
meteorflux:dispatcher@1.2.0
meteorflux:namespace@1.0.0
meteorflux:reactive-state@1.0.1
meteorhacks:cluster@1.6.9
meteorhacks:fast-render@2.10.0
meteorhacks:inject-data@1.4.1
meteorhacks:picker@1.0.3
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
mongo@1.1.3
mongo-id@1.0.1
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
package-version-parser@3.0.4
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
promise@0.5.1
random@1.0.5
rate-limit@1.0.0
react@0.14.1
react-meteor-data@0.2.2
react-runtime@0.14.1
react-runtime-dev@0.14.1
react-runtime-prod@0.14.1
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
sanjo:long-running-child-process@1.1.3
sanjo:meteor-files-helpers@1.1.0_7
sanjo:meteor-version@1.0.0
service-configuration@1.0.5
session@1.1.1
simple:json-routes@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
standard-minifiers@1.0.2
static-html@1.0.3
stevezhu:lodash@3.10.1
templating@1.1.5
templating-tools@1.0.0
tracker@1.0.9
twbs:bootstrap@3.3.5
ui@1.0.8
underscore@1.0.4
url@1.0.5
velocity:chokidar@1.2.0_1
velocity:core@0.10.7
velocity:html-reporter@0.9.1
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
webapp@1.2.3
webapp-hashing@1.0.5
xolvio:cucumber@0.19.4_1
```

**Comment by stubailo** [comment]
> before Meteor 1.2.1

Do you mean 1.2, or 1.1?

**Comment by ffxsam** [comment]
Nope, this started happening since the upgrade to 1.2.1 as far as I can tell.

**Comment by ffxsam** [comment]
Wow. Even SCSS files which used to refresh in a matter of a couple seconds (with no page reload) now actually do a page reload, and also takes many seconds to show up.

**Comment by stubailo** [comment]
Right, I'm asking what version you were on before 1.2.1. Did you go 1.1 -> 1.2? or 1.2 -> 1.2.1?

Also, that doesn't seem possible. Did you also upgrade some of your community package dependencies in the process? Can you send me a diff of your `.meteor/versions` file?

**Comment by ffxsam** [comment]
Oh, sorry. I was on 1.2.0.1 before, with about 8-9 second hot code pushes.

I'm going back in my git history to try to see where things started slowing down drastically.

**Comment by ffxsam** [comment]
How long is hot code push supposed to take, generally? 5-10 seconds?

**Comment by ffxsam** [comment]
Just for kicks, I renamed `/both` to `/client` and replaced `flow-router-ssr` with `flow-router`. Now hot code pushes are pretty fast once again (~4 secs).

**Comment by stubailo** [comment]
Interesting - so the server rebuild/restart is what is taking a long time!

**Comment by ffxsam** [comment]
Yes.. agonizingly long. :) You could probably replicate it by just copying my `.meteor/packages` file and running meteor, then making some code changes in `/both/whatever.js` for example.

**Comment by AlbinoGeek** [comment]
#5571 is the same issue on Windows, with really bad consequences.

**Comment by ffxsam** [comment]
@AlbinoGeek Is your project SSR or are client/server separated?

**Comment by AlbinoGeek** [comment]
@ffxsam I use iron-router and have `client/` `server/` separation, but `routes.js` is in the `/` so that both the client and server can share those definitions.  Everything is done via methods on the server.

I can reproduce my issue ( #5571 ) from a blank meteor project so..

**Comment by AlbinoGeek** [comment]
@ffxsam Can you take any system monitoring during this time?

I am not familiar with tools available on Mac OS .  On Linux you might use `sysstat` to output System Information / Metrics every X seconds (1 second) during this process, and then mark on the output when each push was started, when the browser refreshed, and when the refresh finished.

This would show us if it's a bottleneck somewhere on memory, if many processes were created, if the issue was network (package downloading), or file system (building / copying the server bundle); it could be anywhere frankly.

**Comment by ffxsam** [comment]
It's not really a resource issue. I don't see any CPU spikes or anything like that. It's just taking a long time when my project is using SSR.

**Comment by AlbinoGeek** [comment]
@ffxsam Is it as if the whole thing just sat on `sleep()` for the entire time?  i.e: is it doing literally nothing (waiting on some other resource to unblock, timers, etc.)

**Comment by timbrandin** [comment]
I'm also experiencing slow builds here, using one package (timbrandin:react-template) and have removed blaze-html-templates and ecmascript and using a sample meteor app (`meteor create example`). When changing the title the reload takes ~7 seconds, here's the profiling:

```
|  Selecting package versions                -
| files.readFile: 51.4
| Select Package Versions: 3275.0
|     Input#loadFromCatalog (sqlite): 3121.7
|     other Select Package Versions: 146.0
|
| Input#loadFromCatalog (sqlite): 3121.7
| other Select Package Versions: 146.0
| files.readFile: 51.4
| Total: 3319.2
|  Building the application                  -
| files.writeFile: 93.9
| Rebuild App: 790.1
|     bundler.bundle..makeClientTarget: 245.3
|         Target#make: 245.2
|             Target#_runCompilerPlugins: 75.2
|             Target#_emitResources: 139.2
|                 PackageSourceBatch#getResources: 135.6
|                     PackageSourceBatch#_linkJS: 133.4
|                         other PackageSourceBatch#_linkJS: 87.0
|     bundler.bundle..makeServerTarget: 146.2
|         Target#make: 145.9
|             Target#_runCompilerPlugins: 54.3
|             Target#_emitResources: 71.5
|                 PackageSourceBatch#getResources: 67.7
|                     PackageSourceBatch#_linkJS: 66.0
|     bundler..writeSiteArchive: 371.2
|         bundler..writeTargetToPath: 309.1
|             ClientTarget#write: 111.2
|             ServerTarget#write: 195.0
|                 JsImage#write: 182.1
|                     Builder#write: 118.7
|                     other JsImage#write: 56.8
|         Builder#complete: 54.7
|             files.rm_recursive: 54.4
|
| files.writeFile: 172.0
| other PackageSourceBatch#_linkJS: 125.5
| files.readFile: 61.1
| other JsImage#write: 56.8
| files.rm_recursive: 55.3
| Total: 470.7
```

I'm especially curious why I get so slow load from the catalog:
Input#loadFromCatalog (sqlite): 3121.7

Can I clear the sqlite catalog in some way maybe?

**Comment by ffxsam** [comment]
@timbrandin How are you getting that profile dump?

**Comment by timbrandin** [comment]
`env METEOR_PROFILE=50 meteor run`

**Comment by AlbinoGeek** [comment]
Thank you, I can use that to get more information for my issue on Windows.

**Comment by timbrandin** [comment]
You're welcome! // T

2015-10-31 23:46 GMT+01:00 Damon Blais <notifications@github.com>:

> Thank you, I can use that to get more information for my issue on Windows.
>
> On Sat, Oct 31, 2015 at 2:24 PM, Tim Brandin <notifications@github.com>
> wrote:
>
> > env METEOR_PROFILE=50 meteor run
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/meteor/meteor/issues/5569#issuecomment-152774259>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/5569#issuecomment-152778845>.
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by hwillson** [comment]
[Meteor 1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142) has introduced a significant number of build tool performance improvements, so I'll close this for now. Please post back if you're still having problems. Thanks for reporting this originally!
