### ISSUE TITLE
Catch all exceptions

### ISSUE THREAD

**Issue by bmustata** [meteor/meteor#5572]
Is there any way to catch all exceptions in the current version for meteor? (server side or client side)

**Comment by AlbinoGeek** [comment]
@bmustata Sure there is, Kadira does it; it even captures client-side errors and sends them to their server.  I would not normally answer with just a product, but it's open source too.  [You can find the sources here](https://github.com/meteorhacks/kadira)

https://github.com/meteorhacks/kadira

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

I imagine the way to do this in Meteor would be similar to how you would do it in Node.js, or in a web browser.
