### ISSUE TITLE
Meteor cordova ios background image black.

### ISSUE THREAD

**Issue by kishanj918** [meteor/meteor#5574]
I have image with black overlay. I am setting this image as background image of a page. It is working perfectly in android while in ios it's showing black background. I am attaching both images of android and ios. Please do help.
![screenshot_2015-10-30-15-46-42](https://cloud.githubusercontent.com/assets/3994657/10843261/07694228-7f1e-11e5-9c8d-d5cf74e05834.png)
![screen shot 2015-10-30 at 3 49 48 pm](https://cloud.githubusercontent.com/assets/3994657/10843271/146ef03a-7f1e-11e5-8e7e-f1585c7495ec.png)

**Comment by AlbinoGeek** [comment]
@kishanj918 The iOS has the image too... just much darker.  Lower your overlay's opacity on iOS.

**Comment by kishanj918** [comment]
@AlbinoGeek  Thanks :)

**Comment by martijnwalraven** [comment]
This seems to have been resolved!
