### ISSUE TITLE
Provide template helpers bound to template instance

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5576]
As [discussed here](https://github.com/meteor/guide/pull/75/files#r43528778), it would be really helpful to start offering template helpers bound to the template instance instead of data context. This would allow template helpers which use template instances for state, and also minimize unnecessary reactive reruns just because data context changed, but template helper might not even really use it.

API could be something like:

``` javascript
template.helpers({
   ...
}, {bindInstance: true});
```

Or:

``` javascript
template.boundHelpers({
  ...
});
```

The important thing is that helper should be bound to the instance of the template where it was defined, and not where it was invoked. `Template.instance()` can be used to retrieve the latter.

Should those bound template helpers be exposed also on the template instance as well? So that `template.boundHelpers({foo: function () {}})` means that there is also `instance.foo()` method available? This then allows good code reuse because a template helper can then call another template helper on the same instance.

**Comment by tmeasday** [comment]
Some thoughts about this:

1. I don't think it should be possible for one template to call another's helpers.

2. I think it makes a lot of sense for "helpers" to just be OO-methods on the template instance.

3. We also think that event handlers should be replaced with calls to "helpers"

    ```html
       <input onChange={{this.onChange}}/>
    ```

  (**ducks**)

4. The big issue is how to get the current data context in this case (as it may not be the same as `this.data()`. Given there are already problems with "template scope" vs "helper scope" (https://github.com/meteor/meteor/issues/5280), one suggestion is just to force people to pass it in.

  I think a lot of the objections in #5280 apply here though. I know @mitar will strongly disagree, he is thinking along the lines of https://github.com/meteor/meteor/issues/5577

**Comment by mitar** [comment]
> I don't think it should be possible for one template to call another's helpers (re: which instance it is bound to).

I do not understand what you mean here? You mean automatically in spacebars template? Or in general, that if I get an instance of another template I should not be able to call it? Can you explain a bit why you think this is bad? In fact I think this is a great way to provide explicit communication between instances.

So I think this is really useful to be able to do, but yea, this is open for debate.

> I think it makes a lot of sense for "helpers" to just be OO-methods on the template instance.

Yea, if we have a good way to define them? But yea, having `boundHelpers` is there just so that things are more familiar. We can also do it differently.

> The big issue is how to get the current data context in this case (as it may not be the same as this.data(). 

This is in fact the good side of it! You have not yet seen it, you should use Blaze Components more. So in Blaze Components we have `this.data()` which gives you the context of the component (template instance) and `this.currentData()` which gives you the current data context, if you are for example inside `#each`. This is a really cool feature and in fact is a feature why I do not feel a need for lexical scope at all. The important observation is that both `currentData` and `data` are both methods on template instance. So in the spacebars template you can then very easily be very explicit what you want to access. In Blaze Components you can then do inside `#each` things like `{{data.foo}}` to access foo of component data context. Or `{{currentData.foo}}` (or `{{this.foo}}`) to access current data context. In the case of template instances, this could be like `{{instance.lookup 'foo'}}` or `{{foo}}` respectively.

Pretty neat.

Yes, for me #5577 is a solution to the #5280.

I really think helper and template scope should be unified. Otherwise it is really hard for beginners to understand why is something resolving in a way it is in helper and differently in template. People should not have to understand that internally there are thing like lexical scope and data context.

> We also think that event handlers should be replaced with calls to "helpers"

I agree with this one, but I would propose a different API (https://github.com/peerlibrary/meteor-blaze-components/issues/99). Maybe the question is of terminology. I think we should introduce template instance methods, which then can be used as "template helpers" and "event handlers". This is also how it is in Blaze Components. So everything is just a method. With same `this` and so on, so you can call left and right as needed. And you can also extend them and inherit them and so on. So you can override event handler in a child class, if needed.

Syntax wise, I would thus not use template helper syntax, because I think it is problematic because maybe for us is clear what it is doing, but for beginners, you do not want to have the same symbols do something in one case and something else in another. So in one case template helper returns something, and in another it does not have to return an event handler, but it just binds somehow?

My plan with Blaze Components is to support this syntax:

```
<input onChange />
```

This means you want to call `onChange` method on the component, for event `change` (so the default name).

```
<input onChange="onInputChange" />
```

You want `change` event to call `onInputChange` on the template instance/component.

```
<input onChange=changeHandler />
```

`changeHandler` is a template helper which returns a event handler which should be called on `change` event.

But I do not have too strong feeling about this. Template helper syntax might allow more interesting stuff, like that I could pass `{{data.onChange}}` which would call `onChange` on the data context, for example (in cases where I use models for data context and models have instances and methods on them as well).

In any case, I think event handling is something for some other ticket. Here the question is how to attach some methods to template instances which have `this` a template instance and what API should be for that. I do not really care so much about the API and terminology (do we call them methods or bound helpers), but something like that should be available.

**Comment by tmeasday** [comment]
> > I don't think it should be possible for one template to call another's helpers (re: which instance it is bound to).

> I do not understand what you mean here? You mean automatically in spacebars template? Or in general, that if I get an instance of another template I should not be able to call it? Can you explain a bit why you think this is bad? In fact I think this is a great way to provide explicit communication between instances.

> So I think this is really useful to be able to do, but yea, this is open for debate.

Let's not debate it here, but I think the React-style philosophy of unidirectional data flow is pretty solid and a good rule of thumb to avoid spaghetti code.

> I really think helper and template scope should be unified

I think the tricky part is that it feels like in a proper component-based system (whether the component is the template instance or a separate construct ala BCs) `this` should be the component inside helpers and event handlers.

So then the question becomes how to get the "template scope" in a helper. The options seem to be:

1. Hanging it on the component `this.currentData()` (or `this.lookup()` which is a better version of the above) -- which feels wrong to me as it's not really a property of the component.

2. Hanging it off the global namespace in the same way (i..e making `Template.currentData()` work right, or adding `Template.lookup()`).

3. Not giving it to the user at all, and making them pass it into the helper.

Honestly I am leaning towards 2. but I think it's a complicated question.

**Comment by mitar** [comment]
> Let's not debate it here, but I think the React-style philosophy of unidirectional data flow is pretty solid and a good rule of thumb to avoid spaghetti code.

Like any simple model - yes, until you get to issues because something is hard to model in this way. :-)

> So then the question becomes how to get the "template scope" in a helper. 

I think 1. is the way to go. I do not think that in practice people would object to having such a method there. I think more people prefer local methods than some global-state-looking methods.

I think those are no-problems and you are complicating too much here. The idea here is to provide some basic and simple to implement improvement which would be backwards compatible, but make a lot of stuff easier. For people who like other ways, they can still use React. Here the idea is to just provide a small fix on Blaze as it is, without redesigning it as a whole and how it should be used.

**Comment by hwillson** [comment]
Moved over to meteor/blaze#232 - closing here. Thanks!
