### ISSUE TITLE
Template instances should have "lookup" method

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5577]
As discussed [here](https://github.com/meteor/guide/pull/75/files#r43528778), currently the issue is that it is hard to lookup symbols from code in the same way they are done in the templates. There are things like data context, lexical variables and so on.

Additionally, accessing data context registers dependency on the whole data context, even if you are accessing just a field.

We could implement this as a global template helper:

```javascript
Template.registerBoundHelper('lookup', function (name) {
  const view = Template.instance().view;
  var computedField = new ComputedField(function () {
    var value = view.lookup(name);
    if (_.isFunction(value)) {
      value = value();
    }
    return value;
  });
  return computedField();
});
```

Or template instance method:

```javascript
TemplateInstance.prototype.lookup = function (name) {
  const self = this;
  var computedField = new ComputedField(function () {
    var value = self.view.lookup(name);
    if (_.isFunction(value)) {
      value = value();
    }
    return value;
  });
  return computedField();
});
```

Question is what to do with symbol paths (`foo.bar`).

**Comment by stubailo** [comment]
> Question is what to do with symbol paths

I think the best possible implementation of this would return the exact same thing as `{{foo.bar}}` - basically, a way to evaluate a Spacebars lookup in JavaScript code.

**Comment by mitar** [comment]
Yes!

**Comment by mitar** [comment]
Closing in favor of https://github.com/meteor/blaze/issues/98.
