### ISSUE TITLE
Meteor Deploy Timeout Error

### ISSUE THREAD

**Issue by AkiraLaine** [meteor/meteor#5578]
I'm trying to deploy my app to musare.meteor.com and it's giving me this error:

```Error deploying application: Connection error (connect ETIMEDOUT)```

It seems to be the same for my friend who tried to deploy on his side.

**Comment by CloneXpert** [comment]
Having the same issue, it was also reported on [SO](http://stackoverflow.com/questions/33431196/meteor-connection-error-connect-etimedout)

**Comment by gazhayes** [comment]
I think everyone is having this issue at the moment. One thing I noticed is that if I do a deploy from my VPS (different IP/location) it works the first time but still produces this error for any updates to the same address. The issue doesn't seem to be very consistent so maybe it's some kind of resource issue on Meteor's server?

**Comment by andigehle** [comment]
+1

**Comment by trsh** [comment]
+1

**Comment by alexiri** [comment]
+1

**Comment by herinkc** [comment]
+1

**Comment by kishigo** [comment]
+1

**Comment by rogerkirkness** [comment]
+1

**Comment by dimascrocco** [comment]
+1

**Comment by mahmoudkm** [comment]
+1

**Comment by srb10** [comment]
+1

**Comment by bogoquiz** [comment]
+1

**Comment by chmann** [comment]
I've been unable to deploy for a few days now from Windows 10. There's [a thread on the forums](https://forums.meteor.com/t/error-deploying-application-connection-error-connect-etimedout/12739) as well. 

After seeing just a few people having the same issue It dawned on me to try running it from my MacBook which worked no problem. Seems like this is only affecting Windows -- I tried to deploy again after I was successful on OSX and it failed on Windows.

**Comment by kishigo** [comment]
I was having problems from linux but now it seems to work.  Looks like the
meteor wizards are at work!

**Comment by mathphreak** [comment]
I'm intermittently having this issue deploying from a Linux VM on a Windows host.

**Comment by srb10** [comment]
I did get my iMac to deploy after a few tries after not getting my Win10
machine to deploy for several days.My Win10 still gets the same error.

On Thu, Nov 5, 2015 at 7:45 PM, Matt Horn <notifications@github.com> wrote:

> I'm intermittently having this issue deploying from a Linux VM on a
> Windows host.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/5578#issuecomment-154248365>.
>



-- 
Thanks,
Shannon

**Comment by zachdixon** [comment]
I'm also having issues deploying, on OS X el capitan. I either get this error, or the "This site is down" HTML page in the console, or it actually deployed once but the site was still down. `meteor logs` gives me a "there's no site here" message, and `meteor mongo` works fine.

**Comment by mahmoudkm** [comment]
Works fine now - Mac

**Comment by timolehto** [comment]
+1

**Comment by ligne13** [comment]
+1 (Mac El Capitan)

**Comment by vladgolubev** [comment]
+1

**Comment by timbotnik** [comment]
Thanks everyone, we are currently investigating these issues.

**Comment by nhducit** [comment]
Deploying to webdict.meteor.com.              
                                              
Error deploying application: <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
margin: 0;
text-align: center;
}
.meteor {
padding-top: 200px;
padding-bottom: 20px;
height: 142px;
}
.message {
padding-top: 50px;
font-size: 3em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.submessage {
padding-top: 20px;
font-size: 1.5em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.counter {
padding-top: 30px;
font-size: 1em;
color: #aaa;
letter-spacing: -1px;
}

</style>
</head>
<body>
<div class="meteor"><img src="//warehouse.meteor.com/mother-assets/meteor-logo-final.png"/></div>
<div class="message">
This site is down.
</div>
<div class="submessage">
Try again later.
</div>
<div id="counter" class="counter">
</div>


<script type="text/javascript">
var refreshTime = 0 ;
if (refreshTime) {
var counterDiv = document.getElementById("counter");
var countdown = function () {
if (refreshTime < 1) {
counterDiv.innerHTML =
"Retrying...";
location.reload(true);
} else {
counterDiv.innerHTML =
"Retrying in " + refreshTime + " seconds...";
refreshTime = refreshTime - 1;
setTimeout(countdown, 1000);
}
}
countdown();
}
</script>

</body>
</html>

**Comment by evallgar** [comment]
Same here today. I already "undeployed" my sites and trying to deploy again. Same failure. `"This site is down. Try again later"` I understand there was an scheduled maintenance window today, but as far as I know, its completed at this time and [meteor status] (http://status.meteor.com) reports all systems operational.

damn ...

**Comment by trsh** [comment]
Yeah I think they got problems to maintain it, as the user count is increasing. For me most the time it works.

**Comment by stubailo** [comment]
I think this should be back up now, this was a relatively isolated outage. We're still working on improving the stability of the free service.

**Comment by iamtomhanks** [comment]
Has this issue been resolved? I am new to Meteor and getting this deploy error..

**Comment by Quasisun** [comment]
+1. The first time I tried to deploy, it asked for login info which was good. I had to exit because I had forgotten my password. When tried again, it just hung and gave the connection error.

**Comment by sdzafovic** [comment]
Still getting this issue. Tried the deploy command for a test app 11 times so far on Mac (OS 10.10.2)

**Comment by ethanwillis** [comment]
I am also getting this issue on Mac OS 10.10.5

**Comment by Quasisun** [comment]
The reason why the error occurs is that Meteor has discontinued its free hosting, so "meteor deploy" will return an error. You now have to go through their own Galaxy platform (or some other hosting service) in order to deploy your app.

**Comment by ethanwillis** [comment]
Thanks @Quasisun

**Comment by Tzikas** [comment]
+10

**Comment by dgraziotin** [comment]
@Quasisun what about existing websites?

**Comment by abernix** [comment]
@dgraziotin Yes, even existing websites.

#### [Forum Announcement Regarding Discontinuation of Meteor Free Hosting](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308/211)

**Comment by naysumyat** [comment]
+1

**Comment by julio177** [comment]
+1

**Comment by teddimagg** [comment]
+1

**Comment by dropfen** [comment]
+1

**Comment by hwillson** [comment]
Guys - just to be clear, adding +1's here isn't going to do anything. First of all this issue has been closed. Second of all MDG has shut down their free hosting service. Using `meteor deploy` will no longer work (unless used with MDG's paid service [Galaxy](https://meteor.com/hosting), hence the timeouts. For the full details please refer to the forum post @abernix [mentioned above](https://github.com/meteor/meteor/issues/5578#issuecomment-216875876).

**Comment by farhansumbul** [comment]
I am using the paid service of Galaxy. Trying to deploy my meteor app on Galaxy from Codeship. 

Here is the deployment code. 

echo $METEOR_TOKEN > deployment_token.json
echo $METEOR_SETTINGS > deployment_settings.json
DEPLOY_HOSTNAME=eu-west-1.galaxy.meteor.com METEOR_SESSION_FILE=deployment_token.json meteor deploy $METEOR_TARGET --settings deployment_settings.json


Every time I attempt deployment, there is Timeout error I am facing. Please suggest.
Error deploying application: Connection error (connect ETIMEDOUT)

Thanks in advance.

**Comment by abernix** [comment]
@farhansumbul As we discussed in #7308 this appears to be fixed for you now.

**Comment by abernix** [comment]
I'm locking this issue as the actual issue here has been very well explained and any further updates or +1's on this issue are probably missing the point or experiencing an entirely different issue.

Regardless, here's the...
#### [Forum Announcement Regarding Discontinuation of Meteor Free Hosting](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308/211)
... one more time.
