### ISSUE TITLE
Collection.distinct support

### ISSUE THREAD

**Issue by MeKarina** [meteor/meteor#5579]
Please support collection.distinct

This could be a handy feature for pooling such unique value like userId, email address, username, etc into an array. SO case: http://stackoverflow.com/questions/33424951/meteor-fail-to-send-email-to-multiple-users/33435199

thank You...

**Comment by stubailo** [comment]
Can you help me find more information about how `distinct` works in the Node.js MongoDB driver? I'm not having any success googling around for it.

**Comment by ecwyne** [comment]
[Mongo Docs](http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#distinct)

[Source Code](https://github.com/mongodb/node-mongodb-native/blob/c6d2a0268b1ad661ea20d4cdd4fd2c983eb2fabd/lib/collection.js#L1939)

**Comment by ecwyne** [comment]
Further digging looks like the Node.js driver just passes the command off to the [database](https://github.com/mongodb/node-mongodb-native/blob/c6d2a0268b1ad661ea20d4cdd4fd2c983eb2fabd/lib/db.js#L281) to where the actual work is done.

**Comment by b-e-r-t-o** [comment]
Yes! This is a must. Has any progress been made on 'distinct' support?

**Comment by ivansglazunov** [comment]
+1

**Comment by SimonSimCity** [comment]
What's the progress?

Just to give you an idea: On the server we could just pass it on to mongodb, whereby on the client, we could use underscore. I don't know how heavy this would be for a collection on the client-side ...

Server: https://github.com/zvictor/meteor-mongo-server
Client: http://stackoverflow.com/questions/23254699/meteor-how-to-search-for-only-distinct-field-values-aka-a-collection-distinct#answers

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Collection.distinct%20support&body=Migrated%20from:%20meteor/meteor%235579) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
