### ISSUE TITLE
Adding JWT Tokens to Meteor Methods

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteor/meteor#5581]
I'm running into a wall with trying to call methods on multiple apps from the clientside. Calling a method on another server's client yields null for `this.userId` in the Meteor method even though the user is logged in. (if you'd like more context I have a [post](https://forums.meteor.com/t/how-can-i-utilize-this-userid-from-a-meteor-method-call/12573) here on the forums)

From a lot of googling it seems like this is a common issue with calling methods from apps that are split up. 

Now that JWTs have matured, would it be a better developer experience to provide a JWT on login (on the user object perhaps) and then pass the JWT into the Meteor method as needed? This seems like an easy way to authenticate server to server and client to multiple servers. It would be nice if Meteor would automatically refresh the token for you, making the whole dev experience fairly nice.

Thoughts?

**Comment by stubailo** [comment]
Actually, there is already a token in the localstorage - that's how the app logs in automatically when you open a new tab. The right thing to do would be to call the `resume` login handler with this token on the other app.

I'm assuming this is for the case where the two servers are sharing the same database/users collection?

Basically, this isn't well documented but this token already exists. Let me know if I understand your use case, and I can elaborate more on how to get it to work.

**Comment by stubailo** [comment]
To conclude, I'm not sure how JWT will make this any better than it is now, since a token already exists. However if there is a good reason to switch entirely to JWT, then it would be good to discuss it here.

**Comment by AdamBrodzinski** [comment]
> Actually, there is already a token in the localstorage - that's how the app logs in automatically when you open a new tab. The right thing to do would be to call the resume login handler with this token on the other app.

Oh interesting, I didn't know you could do that. However if I understand this correctly I don't think this will work for this use case.

For example, say we have an Alpha and Bravo apps. Alpha app contains all the model methods and exposes those over meteor methods for authenticated callers. You can think of Alpha app as an admin dashboard for the clientside and Bravo app has very little server and mostly a UI for a certain role of user. Typically the Bravo users will never go the the Alpha app directly.

So when a user in Bravo app creates an account, this works but now they're logged in. Is there a way to now send the resume token to the Alphla app before calling the model update method? (this is the one that has a `this.userId` of null).

From what I understand the user would have to go back to the Alpha app and login with the resume token?

However... poking around the mongo shell, when foo@example.com is logged in and I look at the account, the server can see the `resume.loginTokens` and it seems like using that might work. What do you think about this approach to work around the null `this.userId`...:


- Client creates account on Bravo app
- Fetch `loginToken` from localstorage
- Client calls Model update method and passes `loginToken` as a param
- Alpha Meteor method queries for user by loginToken and fetches user
- User fetched user instead of `this.userId`

This seems to be fairly secure as the RPC caller has to log in the user to get a `loginToken` to make a successful update via the meteor method.

Thoughts?  and thanks!! Much appreciated!

Also instead of proposing JWTs, perhaps a better proposal is a way for core to derive the `this.userId` via the `loginToken` of the caller... or some kind of opt in/alternative way to authenticate that will work easily with micro-services.

**Comment by serkandurusoy** [comment]
@stubailo we've actually tried the bulitin `accountsClient.loginWithToken()` method but unfortunately that did not work out.

To recap, we have two separate apps sharing the same database. Is there a builtin method/way of letting a signed in user from the first app to login/resume on the second app?

If we are allowed to just pass in a token and query for a user, and that's a safe method to log in, then we can perhaps reason about the `loginWithToken` not working as a bug, perhaps?
