### ISSUE TITLE
Throw Meteor.Error('internal-error', 'Internal server error') instead of 500

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5582]
Numeric errors are deprecated. Meteor core should update accordingly and throw `'internal-error` or something instead of `500`.

**Comment by stubailo** [comment]
Yes, when we changed away from numeric errors, we thought about this. But it seems likely that people are relying on the current behavior. Is there any way to do this in a backwards compatible way?

**Comment by mitar** [comment]
I have a suggestion. Maybe there could be an extension point, something like `Meteor._errorStatus = 500` in Meteor core and then there could be a package `string-error` which would override it to `internal-error`. So developers who want to use it could add that package.

Or they could add a package to restore old behavior.

**Comment by stubailo** [comment]
> So developers who want to use it could add that package.

What about developers using packages that expect the old behavior?

**Comment by mitar** [comment]
They can then weakly depend on the package and if it is available, go with one behavior, otherwise with another. And they can slowly migrate.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Throw%20Meteor.Error('internal-error'%2C%20'Internal%20server%20error')%20instead%20of%20500&body=Migrated%20from:%20meteor/meteor%235582) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
