### ISSUE TITLE
Random Package not being used by default

### ISSUE THREAD

**Issue by rafaelcalpena** [meteor/meteor#5583]
I migrated some code from a project that had a previous version of Meteor to a newer project that had Meteor 1.2.1, and noticed that the global variable Random wasn't defined. After I looked for the package in the web, I found that it's a package included by default. (http://meteorcapture.com/random/). Then, I decided to use the package Random from AtmosphereJS (https://atmospherejs.com/meteor/random) and the project went back to normal.

**Comment by stubailo** [comment]
Yes, the Random package is no longer included in new apps as of 1.2. Unfortunately, we don't do a good job documenting which things are included and which aren't. For example, `ReactiveVar` is documented in the docs, but won't work unless you use the `reactive-var` package.

I think the solution is better documenting what is in which package, and which of those are included when you create a new app.
