### ISSUE TITLE
Support dots in names of templates

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#5584]
Create an empty meteor app (version 1.2.1) and paste in following html:

```html
<body>
  {{> myNamespace.testTemplate}}
</body>

<template name="myNamespace.testTemplate">
  Hello
</template>
```

Which does not work, whereas the same template without the `.` in its name works.

**Comment by stubailo** [comment]
Great idea, I think we should definitely make this work.

**Comment by matteodem** [comment]
This is not a feature. It clearly worked before as the easysearch docs show http://matteodem.github.io/meteor-easy-search/docs/components/. 

This is a bug to me that was created in the latest version.

**Comment by stubailo** [comment]
> created in the latest version

You could have dots in template names in 1.2?

**Comment by matteodem** [comment]
Yes, see the link to the docs that I attached, it worked previously. This problem occured to me in the latest version `1.2.1`.

**Comment by stubailo** [comment]
Weird, it doesn't seem consistent with the [changelog](https://github.com/meteor/meteor/blob/devel/History.md#v121-2015-oct-26). Going to try a test app now.

**Comment by stubailo** [comment]
I can't get `{{> hello.world}}` to work. In my code, it compiles to `return Spacebars.call(Spacebars.dot(view.lookup("hello"), "world"));`, which doesn't correctly render the template. Can you give me an example of a project that runs with Meteor 1.2.0.2 where there is a dot in the template name and it can be included using Spacebars?

**Comment by matteodem** [comment]
hm it might be that it works with EasySearch because of me using blaze components, but that doesn't sound like it would make a lot of sense. @mitar any ideas?

The easysearch leaderboard is a good example:https://github.com/matteodem/easy-search-leaderboard/blob/master/leaderboard.html#L17

**Comment by stubailo** [comment]
Actually, that's exactly it. @mitar does some hacks to make dotted template names work properly in Blaze components. But I think we should move those hacks into core to make it work everywhere.

**Comment by matteodem** [comment]
Yes, if mitar can give me some hints on how these hacks are implemented I might give it a shot.

**Comment by stubailo** [comment]
We also want this for the Meteor guide, since we want to suggest namespacing templates with dots: https://github.com/meteor/guide/issues/46

**Comment by mitar** [comment]
Yes, @matteodem, see discussion in https://github.com/meteor/guide/issues/46 for some direction where this stuff should be.

BTW, I think this should be exposed as `Template['myNamespace.testTemplate']` in JavaScript, in my opinion. So that you can have both `Template.base` and `Template.base.item` as templates.

**Comment by mitar** [comment]
Also, I think we should do this https://github.com/peerlibrary/meteor-blaze-components/issues/21.

**Comment by laosb** [comment]
Moved to meteor/blaze#38.
