### ISSUE TITLE
Strange behaviour of select element

### ISSUE THREAD

**Issue by npvn** [meteor/meteor#5588]
I have a simple template consisting of a `select` element. When there is no option selected, a placeholder item is shown at the top of the list. If any option is selected, the placeholder will be removed from the DOM.

The implementation for this is very simple and can be found in [this repo](https://bitbucket.org/npvn/meteor-select-element-issue).

There is a strange issue: When the first option is selected, the selection is "shifted" to the second option (see [screencast](http://quick.as/b87wHRQP9)). This only happens for the first selection, and only for the first option.

It looks like Blaze is confused about the placeholder element, and transforms it into the first option element instead of removing it from DOM.

A workaround that seems to fix this is adding a random `id` to each option element, like [this](https://bitbucket.org/npvn/meteor-select-element-issue/commits/a20a0a85c3e16445edd9d52957dc07a82fd769af?at=master).

**Comment by yyx990803** [comment]
It seems Blaze is not correctly handling the `selected` attribute in the re-rendered options. We will look into this further - for now a quick workaround is to reset the `selectedIndex` of the `<select>` element to `0` before setting the `selectedValue`.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#164; this issue can be closed. Thanks!
