### ISSUE TITLE
Issue with iOS builds and debugOnly

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#5589]
Somebody using Meteor Toys has informed me that when they build their iOS app, and when Meteor Toys are present, the application connects to localhost:3000 instead of the remote server. When Meteor Toys are removed, the issue stops.

I've noticed a similar issue here, which makes me think its something related to mobile builds and debugOnly:
https://github.com/meteor-velocity/velocity/issues/182

**Comment by pors** [comment]
I have this issue and the problem can be reproduced:

* I built a mobile iOS app following this recipe: https://github.com/Differential/meteor-mobile-cookbook/blob/master/iOS/Building.md
* the remote-server is set to an actual remote server on port 443
* I deploy the app via Apple testflight.
* when I open the app on my iPhone the screen stays blank
* inspecting the app via Safari dev tools shows that the app tries to connect to localhost:3000 

All the above with the meteortoys:allthings package included, which relies on debugOnly.

When I remove the meteortoys package all works as it should.

**Comment by timbotnik** [comment]
Is this something that happens only with `meteortoys` or is there a repro with debugOnly packages in general?

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Comment by pauldowman** [comment]
The issue still occurs with 1.3.2.4, and I think it's this: the first time you do `meteor run ios-device` after doing `meteor reset` then `debugOnly` packages aren't loaded.

Steps to reproduce:

1. `meteor reset`
1. `meteor run ios-device ...`
1. Observe that `debugOnly` packages aren't loaded
1. Kill the server
1.  `meteor run ios-device ...`
1. Observe that `debugOnly` packages *are* now loaded
