### ISSUE TITLE
get client public IP address at client side

### ISSUE THREAD

**Issue by Nits7029** [meteor/meteor#5591]
Hello,

How to get client IP address at server side. I have tried "this.connection.clientAddress" but it's not giving me proper public ip adress as from below snippet.

$.getJSON("http://jsonip.com?callback=?", function (data) {
        console.log("Your ip: " + data.ip);       
    });

**Comment by jhuenges** [comment]
"How to xyz" questions have a better place at the [Meteor forum](https://forums.meteor.com/).

The snippet you posted returns an ipv6 address and `this.connection.clientAddress` returns an ipv4 address. If I am not mistaken. Maybe you could post your question at the forum and explain what you understand under a "proper public ip address".

**Comment by Nits7029** [comment]
Sorry for that, I have posted message on meteor forum link as https://forums.meteor.com/t/how-to-get-client-public-ip-address-at-client-side/12702

**Comment by stubailo** [comment]
Great, if this turns out to be a bug, we can reopen this issue.
