### ISSUE TITLE
[suggestion] Don't use colon in ~/.meteor cache file names.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5595]
I tried copying my `/Users` folder on my MacBook from the main partition to an NTFS partition, and got lots of complaints from the `cp` command, like this:

```
cp: /Users/josephpea/.meteor/packages/raix_handlebar-helpers/.0.2.4.zd9kp7++os+web.browser+web.cordova/web.browser/packages/raix:handlebar-helpers.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/raix_handlebar-helpers/.0.2.4.zd9kp7++os+web.browser+web.cordova/web.cordova/packages/raix:handlebar-helpers.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/sewdn_collection-behaviours/.0.2.0.ku4fs3++os+web.browser+web.cordova/os/packages/sewdn:collection-behaviours.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/sewdn_collection-behaviours/.0.2.0.ku4fs3++os+web.browser+web.cordova/web.browser/packages/sewdn:collection-behaviours.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/sewdn_collection-behaviours/.0.2.0.ku4fs3++os+web.browser+web.cordova/web.cordova/packages/sewdn:collection-behaviours.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/stevezhu_lodash/.0.1.0.1skzlv9++os+web.browser+web.cordova/os/packages/stevezhu:lodash.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/stevezhu_lodash/.0.1.0.1skzlv9++os+web.browser+web.cordova/web.browser/packages/stevezhu:lodash.js: Invalid argument
cp: /Users/josephpea/.meteor/packages/stevezhu_lodash/.0.1.0.1skzlv9++os+web.browser+web.cordova/web.cordova/packages/stevezhu:lodash.js: Invalid argument
```

I believe it's because the file names all have a colon in them, f.e. the `stevezhu:lodash.js` in that last file.

Similar to isopacks, it might be better to name them with an underscore.

**Comment by yyx990803** [comment]
Thanks for the suggestion! This is a good idea but probably not a high priority item - that said, we will gladly accept a PR that implements the change.

**Comment by rozzzly** [comment]
I've noticed that if I look in Chrome DevTools for code from a package, say `rozzzly:whatever`, that it will be compiled into `[somepath]/pavkages/rozzzly_whatever.js`. Any PR for this (which would be **superawesome**.. _I'm looking at you developer who thinks, "oh my yeah I could do that", _should follow this `: ---> _` for consistency's sake. Just my 2¢.

**Comment by alfredjkwak** [comment]
This sounds like a good first contribution task. I would follow the pattern <code>: ---> _</code> as suggested.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bsuggestion%5D%20Don't%20use%20colon%20in%20~%2F.meteor%20cache%20file%20names.&body=Migrated%20from:%20meteor/meteor%235595) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
