### ISSUE TITLE
Not possible to add a test-only package asset

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5596]
Not possible to add a test-only package asset which can then be accessed inside a test.

**Comment by mitar** [comment]
The issue is that if my package code uses `Assets` to access asset files, I cannot really test if it works correctly from tinytest because if I add an asset in tests, that asset from tests is accessible only from tests' `Assets`.

**Comment by stubailo** [comment]
Can you elaborate more on the functionality you are trying to test?

**Comment by mitar** [comment]
So I have a package which processes assets provided by the package. So user can do something like `doSomethingWithAsset(assetName)`. The issue is that I would like to test some behavior of the `doSomethingWithAsset` on special crafted assets so that I can see if the package will work correctly also for edge cases and future assets added to the package. But those test assets should not be available in the package itself.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Not%20possible%20to%20add%20a%20test-only%20package%20asset&body=Migrated%20from:%20meteor/meteor%235596) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
