### ISSUE TITLE
Android Cordova missing icon sizes

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5599]
Taken from #3153:

`android_xxhdpi`
`android_xxxhdpi`

"This causes application published as not made for tablet"

**Comment by stubailo** [comment]
A PR would be great for this!

**Comment by Pushplaybang** [comment]
+1 we've just run into this one two.

**Comment by williamli** [comment]
+1 would love to add this. i will try to make a PR for this when i have time... if no one is doing this.

**Comment by williamli** [comment]
silly question... this will be my first commit to the meteor core...

I think I know what I have to change to make this addition, but how can I test it on my computer? do i need to remove the currently installed Meteor cli tools and some how map meteor to this? is there any other ways for me to test and build these Meteor changes without affecting my other meteor projects?

**Comment by stubailo** [comment]
Use these directions: https://github.com/meteor/meteor/tree/9c46763e3f62cbe813769b1f88f5554b00c6605e#slow-start-for-developers

You can just set a different alias (for example, I use `curmeteor` to point to the checkout version, and `meteor` points to the installed version as usual).

**Comment by subramaniashiva** [comment]
Is there any other work around till this issue gets fixed?

**Comment by williamli** [comment]
Yes.
Open project in Android studio to add in missing resources.

**Comment by subramaniashiva** [comment]
Thanks!

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3 beta (see https://github.com/meteor/meteor/issues/6050).
