### ISSUE TITLE
this context of template.autorun should be a template instance

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5603]
Currently it is `view`. One could get to the template instance with `view.templateInstance()`, but I think it is really cleaner if it would be a template instance to begin with.

**Comment by stubailo** [comment]
Sounds like a good idea, although I hope nobody is using the current behavior... in some sense this is a breaking change, right?

**Comment by mitar** [comment]
I would say that because this previous behavior was not documented is not a breaking change. :-)

**Comment by AlbinoGeek** [comment]
If anyone was intentionally using the previous behaviour, it would have been a bad on their end, not something we'd need to worry about (as it was undocumented.)  It would be much better for consistency sake if this (and therefore bare at), were the proper context at all times.

**Comment by deanius** [comment]
'Regular' autoruns have an undefined `this`, since `this` is confusing, eliminating it would be an option too. Failing that, however, the template instance is a more reasonable choice than the `view`.

**Comment by AlbinoGeek** [comment]
I never understood why an Autorun received null as "this", and it gave me
alot of problems.
I ended up editing Deps myself and binding (this) to be a proper context
anyways...

So I would be in favour of this change hitting back.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#166; this issue can be closed. Thanks!
