### ISSUE TITLE
Documentation is bad

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#5605]
Hey MDG,

I really like your work and everything you guys are working on. I have been following the meteor project when it just started and i have been very patient till version 1.2 to make sure it matures enough for everyday usage. However besides all the cool things that meteor does, I still think the documentation page and the format of documentation sucks. Let me clarify why i say this:

1. Haphazard explanation of things.
2. Alot of stuff is undocumented, which you find out from random gists and stackoverflow, which is also outdated for the most part.
3. Things like _wrapAsync should be properly documented, not everyone likes to go through the source to see such basic things.
4. Files like ```settings.json``` have to be explained properly.
5. I know you have sample applications, but i don't think most people have time to go through them when they have to get a project off the ground.

It could just be me, but i would really like to see better docs for such an awesome framework. I am not that good at writing docs otherwise this would have been a PR. Just to show what is good docs, head on over to astronomy docs. It's a meteor package but they do a good job at documenting stuff.

**Comment by stubailo** [comment]
Hey, we're working on this here: https://github.com/meteor/guide

Going to close this issue - please take a look at what we are working on for that project, and comment if we are missing anything! A good place to start is by looking at the issues labeled article: https://github.com/meteor/guide/labels/article

**Comment by osv** [comment]
https://github.com/awatson1978/meteor-cookbook was helpful at begin
