### ISSUE TITLE
Won't it be better to allow the developer to decide the user `selector` while logging in?

### ISSUE THREAD

**Issue by ahmedtabrez** [meteor/meteor#5606]
Instead of forcing the developer to use either of `_id`,`username` and `email`, will it not be better to make `Meteor.loginWithPassword(<selector>,<password>)` a little more generous so that the developer is not forced to use just the three of them and can use a little more innovated way of selecting the right user document ?

Just like in my question here:
http://stackoverflow.com/q/33520978/1184247

**Comment by AlbinoGeek** [comment]
@ahmedtabrez It's not just about finding the user, unless you've used `ensureIndex` you're going to find that everything slows down dramatically once you start finding documents by anything other than their `_id` or their first key.

**Comment by ahmedtabrez** [comment]
@AlbinoGeek, I did not mention that but of course I would definitely use `ensureIndex` keys involved in the `<selector>`.

**Comment by AlbinoGeek** [comment]
@ahmedtabrez Just making sure, :).

One implementation may be:

```coffee
# server.coffee
Meteor.methods
  loginByCustomerID: (customerID) ->
    user = Meteor.users.findOne customerID: customerID
    if user? then return user._id else return false
```

```coffee
# client.coffee
Template.login.helpers
  'submit form': (event, template) ->
    # I capture login form enter/submit like this.
    event.preventDefault() # Stop browser submitting GET/POST form.
    
    Meteor.call 'loginByCustomerID', event.target.customerID.value, (res, err) ->
      if err? then return alert err.message
      Meteor.loginWithPassword res, event.target.password.value, (res, err) ->
        # do whatever you want with the login callback here.
```

**Comment by ahmedtabrez** [comment]
@AlbinoGeek, exactly !!! I thought of the same thing. [Read my answer at StackOverflow](http://stackoverflow.com/a/33539383/1184247). As I mention in the answer, we leave a small window for the misbehaving users.

### How?

Anyone can retrieve an `_id` of another user simply by calling `Meteor.call( 'loginByCustomerID', <customerID>)` from the browser console. How they can misuse this information apparently depends on the application.

**Comment by AlbinoGeek** [comment]
@ahmedtabrez Fair, what about doing it entirely Server Side then?

### Create a server side method that accepts CustomerID and (somehow prehashed?) Password

### Login the user from the server-side, if user found AND pw match; else send general auth failure.

**Comment by zol** [comment]
Hey @ahmedtabrez - In the spirit of keeping Meteor's APIs simple and not introducing any security holes we're not going to add this feature. Thanks for the discussion!
