### ISSUE TITLE
Meteor deploy Mongo very slow

### ISSUE THREAD

**Issue by Joe312341** [meteor/meteor#5607]
Hello,

Since a couple of days ago now the Mongo DB of my app (deployed using meteor deploy) is extremely slow.

Commands like :
```
meteor mongo app.meteor.com -U
meteor mongo --url app.meteor.com
```

even timeout sometimes.

Is this something on the meteor team side? Anyone else have these problems?

**Comment by andigehle** [comment]
Maybe related with this issue: https://github.com/meteor/meteor/issues/5578

**Comment by Joe312341** [comment]
Problem do not occur anymore
