### ISSUE TITLE
Android Emulator Hangs

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5612]
```
=> App running at: http://localhost:3000/     
WARNING : no emulator specified, defaulting to Nexus6
Waiting for emulator...
emulator: The memory needed by this AVD exceeds the max specified in your HAXM configuration.
emulator: AVD      RAM size = 3072 MB
emulator: HAXM max RAM size = 2048 MB
emulator: You might want to adjust your AVD RAM size and/or HAXM configuration to run in fast virt mode.

HAXM is not working and emulator runs in emulation mode
emulator: UpdateChecker: skipped version check
   Starting app on Android Emulator          -
```

When I run with verbose, this is what I get. Not sure whats going on here or what to do about it. The android stuff is confusing to me.

**Comment by martijnwalraven** [comment]
The Android stuff is confusing to me too... Googling 'The memory needed by this AVD exceeds the max specified in your HAXM configuration' gives quite a few results, but I can see how that that might not help you much. I'm not sure how you created your AVD (through Android Studio or the regular AVD Manager), but what this seems to come down to is that you should decrease the RAM size of your AVD to 2048 MB.

**Comment by ccorcos** [comment]
OK. I'll have to check that out some more. I clicked so many buttons and installed so many things in android studio, lol.

**Comment by ccorcos** [comment]
Hmm. I figured it out. I had to run `~/Library/Android/sdk/tools/android avd` then edit the emulator to specify 2048MB RAM. Then run `brew cask install intel-haxm`.

Also, I think its worth mentioning in the docs somewhere how to install android stuff all through homebrew on mac. This gets you post of the way there:

brew cask install java
brew cask install android-studio
brew cask install intel-haxm

The rest is installing Android SDK and emulator through the android studo sdk manager

**Comment by ccorcos** [comment]
Still havent gotten the emulator up and running yet thouhg :/ lol

**Comment by ccorcos** [comment]
```
BUILD SUCCESSFUL

Total time: 2 mins 46.668 secs
Built the following apk(s):Emulator          |
    /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/build/outputs/apk/android-x86-debug.apk
Installing app on emulator...
Using apk: /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/build/outputs/apk/android-x86-debug.apk
A retried call failed. Retrying 2 more time(s).
A retried call failed. Retrying 1 more time(s).
   Starting app on Android Emulator          |
/Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Failed to launch app on emulator: Failed to install apk to emulator: Error executing "adb -s emulator-5554 install -r -d "/Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/build/outputs/apk/android-x86-debug.apk"": protocol failure
- waiting for device -

=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --emulator:
   Error: Command failed: /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/cordova/run --emulator
   
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
                                              
ExitWithCode:1
```

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
