### ISSUE TITLE
Meteor.com Website loading several jquery versions

### ISSUE THREAD

**Issue by ousamabenyounes** [meteor/meteor#5616]
I've just tested the meteor.com website on yellowLabTool open source project.
I get the following recommandations:
http://yellowlab.tools/result/e8tno909qd

I see two easy things that could improve the website webperf very quickly:

Image optimisation: http://yellowlab.tools/result/e8tno909qd/rule/imageOptimization
Stop loading 2 version of JQuery on the website: http://yellowlab.tools/result/e8tnq6vpbd/rule/jQueryVersionsLoaded

Hope this will help developers to improve this website.

**Comment by rozzzly** [comment]
I would not be surprised, and would reluctantly agree with MDG/mods if this got removed for "advertising"... But damn, I'm impressed. ![fukinsaved.jpg](http://i.imgur.com/YrX7hUt.jpg) that service will sure give _[pied piper](http://www.piedpiper.com/)_ a run for their _money_ lmfao

**Comment by stubailo** [comment]
I'll forward this to the appropriate person, but I'll close it here since it's not really a bug in Meteor. thanks!
