### ISSUE TITLE
Allow for multiple compilers of same file type.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5618]
Use case: I am using `ecmascript` plugin, but also want to create a documentation generator which will similarly process javascript files. Something like this would be cool:

```
PluginHandlers.ecmascript.extend({
  processForPackage(file, options) {
  }
});
```

**Comment by rozzzly** [comment]
I mean you could always fork `ecmascript` (and the actual compiler package it depends on, `babel-compiler`). Then modify the compiler's code that handles the per-file compilation to run your docgen before/after its babelified.

**Comment by rozzzly** [comment]
Although the compiler code is not something you typically would care about being documented given that es5 code is pretty ugly.

**Comment by stubailo** [comment]
Yeah, I think this is a legitimate feature we should have. I also am not sure if this is a great application of that feature, though, since I feel like you could achieve the documentation functionality with an external tool. Are you planning on somehow serving these docs as part of your app UI?

**Comment by egoldblum** [comment]
I too would like the ability to register additional build compilers for a single file type.  In my case, I would like to statically rewrite certain paths in `.html` files at build time; particularly in `head.html`.

As to the "achieving same functionality with an external tool": this feels a bit strange to me given the fact that linters & minifiers are first class citizens in the build process.  I can easily achieve the same functionality a linter plugin gives me using an external tool (in fact, I do), so it seems somewhat arbitrary to make that the deciding factor of the validity of this feature.

**Comment by stubailo** [comment]
> so it seems somewhat arbitrary to make that the deciding factor of the validity of this feature.

I'd argue this makes the linter feature of Meteor less useful than some other feature that would be hard to achieve using an external tool.

**Comment by sungwoncho** [comment]
I am writing a helper for flow router that can be used in React components. My solution was to register a compiler for `.jsx` extensions to look for the helper strings and evaluate them. But this cannot be done because no two packages can handle the same file extensions. I think this case is a good application of this proposed feature.

**Comment by stubailo** [comment]
> I am writing a helper for flow router that can be used in React components.

Why would a helper for flow router require parsing source code?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20for%20multiple%20compilers%20of%20same%20file%20type.&body=Migrated%20from:%20meteor/meteor%235618) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
