### ISSUE TITLE
Accounts.forgotPassword() is case sensitive for email-based requests to reset an account password

### ISSUE THREAD

**Issue by generalleger** [meteor/meteor#5621]
I am finding that `Accounts.forgotPassword` is case sensitive for email-based requests.

For example, when a user registered as **tester@tester.com** tries an Accounts.forgotPassword request with **Tester@tester.com**, the response from the server is `User not found`.

This seems odd to me because the login process is case *insensitive* when using email as the username, i.e. that user could login with **TeSTeR@tEstEr.Com** with no problem. But the `Accounts.forgotPassword()` seems to be applying different rules.

Is this the expected behavior?

Originally posted [here in the forum](https://forums.meteor.com/t/is-accounts-forgotpassword-case-sensitive-for-email-based-accounts/12926).

edit: Pretty sure this is related to [issue 550](https://github.com/meteor/meteor/issues/550)

**Comment by zol** [comment]
This is tracked in https://github.com/meteor/meteor/pull/5674 , thanks @zimme
