### ISSUE TITLE
Blaze: Nested function doesn't work

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#5623]
`reactComponent` is a template helper which returns - you guessed it - a React component.
```
This works
<div>{{> React component=reactComponent}}</div>

This doesn't 
<div>{{> React component=(reactComponent)}}</div>
```

Background:
I want to use the helper to get the react component dynamically by passing a name. This doesn't work either.

**Comment by mitar** [comment]
Yea, functions are called automatically for you. It is pretty tricky to be able to pass a function as an argument. What is wrong with the first line?

**Comment by stubailo** [comment]
It is weird that the two expressions work differently - I would expect them to do the same thing. Is anyone able to track down why this happens? If it had to do with calling functions automatically I'd assume that both wouldn't work.

**Comment by stubailo** [comment]
Also, it would be good to have a reproduction in the form of a complete app so that we can rule out side effects.

**Comment by mitar** [comment]
I am not sure what exactly it means "that it does not work". I think that it does not work in the sense that a function is called and not passed as value?
