### ISSUE TITLE
Repeated class names not rendered correctly

### ISSUE THREAD

**Issue by bitIO** [meteor/meteor#5632]
Using Semantic-UI sometimes you need to add the same class name twice, i.e.

```html
<div class="ui two column computer one column mobile grid container">
```

but this is translated into
```html
<div class="ui two column computer one mobile grid container">
```
breaking the interface.
This is because of [DiffingAttributeHandler](https://github.com/meteor/meteor/blob/devel/packages/blaze/attrs.js#L68) call `this.parseValue`which  reduces the repeated element into one since the element is the key in the array where values are stored
```javascipt
parseValue: function (attrString) {
    var tokens = {};

    _.each(attrString.split(' '), function(token) {
      if (token)
        tokens[token] = token;
    });
    return tokens;
  }
```

Here is the repo to reproduce the error with step by step guide: https://github.com/bitIO/repeated-class-issue

**Comment by talha-asad** [comment]
Over efficient are we here meteor :-1: ? +1

**Comment by avalanche1** [comment]
This shouldn't make sense as this is all the same from CSS standpoint.

**Comment by bitIO** [comment]
Well, when using a framework called semantic ui, words matter, an the order also does. Maybe from a pure CSS standpoint it makes no sense but the use case is there.

**Comment by avalanche1** [comment]
I use SUI extensively and never bumped into this. And you are wrong - word order and count doesn't matter, as SUI is just a bunch of css rules.

**Comment by AlbinoGeek** [comment]
@avalanche1 Actually yes, word-order does matter in Semantic UI.  There are some style rules that directly target a sequence of two classes being present on something, and have different behaviour based on the order.

Example:

```jade
  .ui.basic.segment

```

**Comment by talha-asad** [comment]
@stubailo Yes it was #3628. You can close that, i am going to try and submit a PR for this. Let continue the discussion here.

**Comment by talha-asad** [comment]
@stubailo It seems we need to change this:

```js
parseValue: function (attrString) {
    var tokens = {};

    _.each(attrString.split(' '), function(token) {
      if (token)
        tokens[token] = token;
    });
    return tokens;
  }
```

But i have no idea where it is being used, do you have any pointers on that?

**Comment by talha-asad** [comment]
I have created a mini file that is easy to use and work on, based on how its working in ```attrs.js```

The file contents are:

```js
var myElement = {className: 'ui middle aligned center aligned grid'};

function getCurrentValue(element) {
  return element.className;
}

function setValue(element, className) {
  element.className = className;
}
  
function parseValue(attrString) {
  var tokens = {};

  _.each(attrString.split(' '), function(token) {
    if (token) {
      if (tokens[token]) tokens[token] += ' ' + token;
      else tokens[token] = token;
    }
  });
  return tokens;
}
  
function DiffingAttributeHandler_update(element, oldValue, value) {

  var oldAttrsMap = oldValue ? parseValue(oldValue) : {};
  var newAttrsMap = value ? parseValue(value) : {};

  // the current attributes on the element, which we will mutate.

  var attrString = getCurrentValue(element);
  var attrsMap = attrString ? parseValue(attrString) : {};

  _.each(_.keys(oldAttrsMap), function (t) {
    if (! (t in newAttrsMap))
      delete attrsMap[t];
  });

  _.each(_.keys(newAttrsMap), function (t) {
    attrsMap[t] = newAttrsMap[t];
  });

  return _.values(attrsMap).join(' ');
}

DiffingAttributeHandler_update(myElement, myElement.className, 'ui middle aligned center aligned grid aligned yes');
```

This requires just underscore, you can either run this on the console of a meteor app or run it on NodeJS with an added ``` var _ = require('underscore'); ``` line added at the top. ```DiffingAttributeHandler_update``` should return ```ui middle aligned center aligned grid aligned yes```  when it will work properly.

Might need some help in preserving order.

**Comment by talha-asad** [comment]
I did it!

```js
var myElement = {className: 'ui middle aligned center aligned grid'};

function getCurrentValue(element) {
  return element.className;
}

function setValue(element, className) {
  element.className = className;
}
  
function parseValue(attrString) {
  var tokens = {};
  
  var similarTokens = 0;
  _.each(attrString.split(' '), function(token, i) {
    if (token) {
      if (tokens[token] && i > 0) {
        tokens[Object.keys(tokens)[(i-similarTokens++)-1]] += ' ' + token;
      } else tokens[token] = token;
    }
  });
  return tokens;
}
  
function DiffingAttributeHandler_update(element, oldValue, value) {

  var oldAttrsMap = oldValue ? parseValue(oldValue) : {};
  var newAttrsMap = value ? parseValue(value) : {};

  // the current attributes on the element, which we will mutate.

  var attrString = getCurrentValue(element);
  var attrsMap = attrString ? parseValue(attrString) : {};

  _.each(_.keys(oldAttrsMap), function (t) {
    if (! (t in newAttrsMap))
      delete attrsMap[t];
  });

  _.each(_.keys(newAttrsMap), function (t) {
    attrsMap[t] = newAttrsMap[t];
  });

  return _.values(attrsMap).join(' ');
}

DiffingAttributeHandler_update(myElement, myElement.className, 'ui middle aligned center aligned grid aligned yes');
```

**Comment by talha-asad** [comment]
PR submitted #5753

**Comment by talha-asad** [comment]
Seems to be working nicely for me, To test just put a blaze package in your local package dir.

**Comment by StanLindsey** [comment]
Moved to the meteor/blaze repo - https://github.com/meteor/blaze/issues/30

**Comment by laosb** [comment]
Moved to `meteor/blaze` by @StanLindsey - Closing.
