### ISSUE TITLE
Great slowdown because of the interaction between a Minimongo query and subscription

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5633]
***1 Upvote*** I want my Saturday back.

See reproduction [here](https://github.com/mitar/meteor-issue5633).

The issue is that I have one subscription which returns the latest document in a collection. And then I display that latest document. So I have a helper like:

```javascript
Template.hello.helpers({
  latest: function () {
    return Documents.findOne({}, {sort: {createdAt: -1}});
  }
});
```

And then I want to subscribe to the whole collection as well, so I open another subscription to a publish function which publishes all documents. That subscription takes (in the example app) for 500 documents **more than 10 seconds to get to the ready state**. The interesting thing is that if I comment out the content of the `latest` template helper, subscription finishes at normal speed (0.3 seconds, which still feels a bit large for localhost app, but OK).

It seems that the bottleneck is in the Minimongo query which is then slowing down everything else, including the reception and processing of DDP messages. So it seems that for every new document Minimongo is recomputing the query, and this grows super-linearly, it is slower and slower with number of documents in the collection.

I would guess this is potentially huge slowdown for many applications because. Especially cases like infinity scroll where you have an order specified in Minimongo and you are subscribing to a new larger publish of same documents.

**Comment by steph643** [comment]
Are you sure this is not due to the usual Blaze slowdown, as described [here](https://github.com/meteor/meteor/issues/3979)?

**Comment by mitar** [comment]
No. If I do:

```
Tracker.autorun(function () {
  // Comment this line out to make subscription fast.
  return Documents.findOne({}, {sort: {createdAt: -1}});
});
```

So not using Blaze, but just an autorun to open a query, things work as slow as before. But if I remove it, then they are fast.

So it is not Blaze related. It might be that it happens with Blaze more often (especially with template-level subscriptions) but it is happening because of open query with sorting.

**Comment by mitar** [comment]
One very interesting thing is also that if I change publish from:

```javascript
Meteor.publish('last-document', function () {
  return Documents.find({}, {sort: {createdAt: -1}, limit: 1});
});
```

To (so `-1` to `1`):

```javascript
Meteor.publish('last-document', function () {
  return Documents.find({}, {sort: {createdAt: 1}, limit: 1});
});
```

Then client side subscription is fast as well. But interesting, if I change then client side to match the order (so change `-1` to `1` in `sort`):

```javascript
Template.hello.helpers({
  latest: function () {
    return Documents.findOne({}, {sort: {createdAt: 1}});
  }
});
```

Then it is slow again.

**Comment by mitar** [comment]
Because this makes drastic differences for even small numbers of documents (like 100) and makes stuff feel stuck I think this might be the reason for many people observing that Meteor is slow sometimes to render stuff.

**Comment by mitar** [comment]
cc @wh0

**Comment by AlbinoGeek** [comment]
+1 , started reproducing this in our Applications once the "AuditLog" collection had more than 200 records to return for each user, regardless of using pagination and sane limits; the publish/subscribe itself takes a lot of time (as reported by Kadira.)

**Comment by mitar** [comment]
Not sure why this got closed. The issue is still there and it should be addressed.

**Comment by mitar** [comment]
Method is not reactive, the whole point of Meteor is that it is reactive.

Yes, the obvious thing would be that query is not reevaluated until subscription is ready. In general probably much better approach would be that documents are not visible to the client-side code until publication gets ready. That would also minimize DOM re-renderings for many cases.

**Comment by tmeasday** [comment]
I closed it because like I said above I don't see it getting addressed directly.

> Yes, the obvious thing would be that query is not reevaluated until subscription is ready

That is what you want in this case but there's just no way to make that happen automatically given the semantics of Tracker + Subscriptions.

**Comment by mitar** [comment]
I understand that it is unclear how to address it, but I think it is a very common problem many people hit not knowing it. Here is a clear and simple reproduction. I think MDG should sit down and think of how to fix this. Just leaving it out there and letting us use complicated workarounds is really a problem because you first have to know that you need one.

Maybe it is time for Minimongo to have indexes. Is there already a ticket for that?

**Comment by steph643** [comment]
> In the meantime, a work-around for this problem is to use a method rather than a publication for the dataset. Or a custom publication that combines all documents in to a single doc (if you want to ensure you reuse cursors).

The workaround I use is to disconnect any reactive data operation (especially Blaze rendering) while subscribing. This is required even for a few dozens of documents.
This is not so difficult to achieve. The only remaining problem was subscription rerunning in case of user login/logout (see https://github.com/meteor/meteor/issues/4705), but I think I have now solved it (new package coming).

**Comment by steph643** [comment]
I don't think the workaround I've described goes against template level subscription. What I am saying is that you should disable reactive behavior until your subscription is ready. This can be done within a template. It is basically about doing by hand what you've said above: "the obvious thing would be that query is not reevaluated until subscription is ready."
But I agree this is painful.

**Comment by tmeasday** [comment]
> Maybe it is time for Minimongo to have indexes. Is there already a ticket for that?

It doesn't look like it. I agree, but I suspect this is a "PRs encouraged" type of situation.

**Comment by mitar** [comment]
So then let's open this ticket and make it that. :-)

**Comment by tmeasday** [comment]
> I think MDG should sit down and think of how to fix this.

I think the solution to the problem involves batching/throttling `added` callbacks on the client so that if a bunch of documents arrive in quick succession, MM queries are only re-evaluated once, rather than once per document.

However, this is a pretty big change to the semantics of livedata, and as I hinted above, given that a larger overhaul of livedata is being considered to better support things like SQL, I suspect this change isn't going to happen to livedata in it's current form.

> Then there is really a need for subs manager like @arunoda is saying.

I'm not really seeing how subs manager helps with this problem?

**Comment by mitar** [comment]
Does MDG has a bounty program? I might find a person who could implement this. :-)

**Comment by mitar** [comment]
> This can be done within a template. It is basically about doing by hand what you've said above: "the obvious thing would be that query is not reevaluated until subscription is ready."

Hmm, this could then be simply:

```javascript
Template.hello.helpers({
  latest: function () {
    if (!Template.instance().subscriptionsReady()) return [];
    return Documents.findOne({}, {sort: {createdAt: -1}});
  }
});
```

**Comment by tmeasday** [comment]
So here's a MM ticket: https://github.com/meteor/meteor/issues/5678

I'm going to re-open this one just until I write the relevant section of the guide so others now how to avoid it.

**Comment by tmeasday** [comment]
> Does MDG has a bounty program? I might find a person who could implement this. :-)

If you mean to do the livedata changes, I don't think it's a matter of just implementing it but also getting buy-in from the relevant people to change the semantics in possibly breaking ways. And I highly suspect the answer would be "let's just wait until we make these other larger changes we are thinking of making"

**Comment by tmeasday** [comment]
Re: not getting documents until the sub is ready:

This is a good idea UX-wise in any case. But it doesn't totally solve the problem unfortunately. For instance you might have another cursor over the same collection which *is* ready, and that cursor will get re-evaluated also.

**Comment by mitar** [comment]
> I think the solution to the problem involves batching/throttling added callbacks on the client so that if a bunch of documents arrive in quick succession, MM queries are only re-evaluated once, rather than once per document.

That would in general be a good idea to support. So `added` callbacks which are batched together. And that possible overlapping changes are merged together. Also, backpressure is a related thing to batch processing. See #3740.

But I think is something not needed in this case. So if Minimongo would have indexes it should be pretty easy as well.

> However, this is a pretty big change to the semantics of livedata, and as I hinted above, given that a larger overhaul of livedata is being considered to better support things like SQL, I suspect this change isn't going to happen to livedata in it's current form.

BTW, I think there is already [API for this](https://github.com/meteor/meteor/blob/33eb9ee9744049490e0440eee36107e581c33ba6/packages/mongo/collection.js#L195). So I am not sure if your claim that this is some big breaking change is true. Maybe it is just a bug or edge case of current code? Or something where current code does not call into it?

> I'm not really seeing how subs manager helps with this problem?

Because you would not subscribe at every template, but would have documents already there, because often those subscriptions overlap between templates/pages.

**Comment by mitar** [comment]
> This is a good idea UX-wise in any case.

That is open for debate. I know there are some in Meteor community who prefer big loading signs and then rendering all at once. But from my experience doing some user testing people prefer things to load incrementally. Because big loading signs, if they are taking long, get people to loose patience and then they close the tab before it even loads. If things are loading incrementally people tend to stay around longer, because they see something is happening. Also, they are completely used to incremental loading on the web. Maybe it is different for mobile apps.

**Comment by tmeasday** [comment]
> Maybe it is just a bug or edge case of current code?

Well maybe you are right. Let me know if you figure any more out about it.

>  I know there are some in Meteor community who prefer big loading signs and then rendering all at once

I'm not really saying that. I'm saying if you have a cursor that depends on data that's not ready, it's probably bad UX (and certainly bad for performance) to render whatever component depends on that cursor with incomplete data. It doesn't mean you need to whack down a "big loading sign". You can for instance render the relevant part of the page in a loading state.

Otherwise you just don't have any control about what is rendered.

**Comment by mitar** [comment]
> Well maybe you are right. Let me know if you figure any more out about it.

Or maybe that can be a ticket for some from the core MDG to do. At the moment I do not have free cycles to get to now the internals of the livedata. Maybe @glasser can explain more why current suspend/resume does not work in this case?

> Otherwise you just don't have any control about what is rendered.

You do. Because you are getting one document by document.

**Comment by AlbinoGeek** [comment]
@mitar For most people using `iron-router` or `flow-router` for example, the entire UI for that page is locked up until all cursors return `ready` state.  This is what their intended `waitOn` programming flow is meant to help with.

**Comment by glasser** [comment]
I've thought for a while that we should batch up DDP messages that show up in the same time and, if there are more than one for a given collection, pass them as batches which trigger the normal minimongo batch update (pause/resume) behavior.  Unfortunately I haven't had time to focus on DDP for quite a while, but it would be a pretty easy PR, I think.

Ideally you would do it basically just batching things that arrive on TCP at the same time, but there are way too many layers of abstraction in the way to do that.  Throwing a tiny (1ms even) throttling to the low level processing of DDP messages in livedata_connection wouldn't be too hard and could be done as a minimally invasive PR. It's not too different from the current logic which batches messages until quiescence.

**Comment by mitar** [comment]
> For most people using iron-router or flow-router for example, the entire UI for that page is locked up until all cursors return ready state. This is what their intended waitOn programming flow is meant to help with. You cannot work with the records "as they arrive" because you're waiting for the ready state.

That is not true and is also the main point flow-router is bringing to the story. That this "waitOn" pattern is not a good one. They are even removing this feature altogether in the latest version of flow-router. Read [here more](https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management).

**Comment by mitar** [comment]
@glasser: Can you point me to concrete code lines where you think this could be hooked into? And where exactly is the current batching code invoked?

**Comment by glasser** [comment]
Take a look at `_livedata_data`.  When messages come in there is some logic to just add them to a buffer (for special cases around reconnect and user ID change) and then run them all later.

**Comment by mitar** [comment]
@glasser: I made #5680, but sadly it does not improve the performance of [the reproduction](https://github.com/mitar/meteor-issue5633). Now all messages are processed in one or two batches, but after the batch is processed, Meteor freezes for 10 seconds and then subscription is set to ready.

It seems there is something more causing the issue.

**Comment by tmeasday** [comment]
@mitar, I took a look at the profile, and added some logging, and although #5680 has moved the work into `processBatchedUpdates` (which is what we want), it's still running `Mongo.Collection.update` ~500 times via the registered store. So I don't think it's working as you intended?

**Comment by mitar** [comment]
I think it would be OK if it would call `Mongo.Collection.update` 500 times, the issue is why it is trying to sort anything while doing that? How I would assume it would behave is that it freezes the observe, it adds those documents (not really computing anything, just adding them to internal Minimongo storage), resumes the observe, observe would notice, o, there is one big change, let's invalidate all cursors. Cursors get invalidated. Next flush cycle happens. Cursor is queried, sorting happens, once.

**Comment by tmeasday** [comment]
Ok, so it turns out `LocalCollection.prototype.insert` ignores `self.paused` and recomputes queries no matter what. Is this as designed @glasser or is this a bug?

**Comment by tmeasday** [comment]
(Updated my comment above, it was `insert` not `update` that was being called 500 times)

**Comment by osv** [comment]
I think you should check for **ready** subscription in `latest` template

**Comment by glasser** [comment]
Ah @tmeasday you're right, I'd forgotten about how paused works.  Pausing prevents observe callbacks from being called (ie, doing lots of work in Blaze incrementally instead of in batches) but doesn't stop the queries from being updated internally.

You could do something like, if a query (observe) gets more than a certain number of changes while paused, we stop updating it and mark it as "dirty" and recompute it at resume time.

**Comment by AlbinoGeek** [comment]
You SHOULD pause during these 500 received exploders.  Then, if a certain
number (or passwd / user change ID / other special case) mark dirty and
unpause, otherwise only either unpause after receiving too many updates
(say batches of 100 or 500ms, whichever hits first?) ; otherwise a battered
realtime app would see delays.

**Comment by mitar** [comment]
> Pausing prevents observe callbacks from being called (ie, doing lots of work in Blaze incrementally instead of in batches) but doesn't stop the queries from being updated internally.

Why is this behavior at all? Why queries are not lazy by default? I always thought that they are. So updating only invalidates the reactive dependency, and when computation runs again, then the query is computed? Incremental updating would be useful only if there were indexes, so that you could incrementally be updating indexes with every change (but keeping query still as it is, until it is rerun inside a computation)?

Does this show a bigger design issue with how currently queries are eagerly modified?

**Comment by osv** [comment]
```diff
diff --git a/.meteor/packages b/.meteor/packages
index 3f49c2c..15c6455 100644
--- a/.meteor/packages
+++ b/.meteor/packages
@@ -18,3 +18,5 @@ ecmascript              # Enable ECMAScript2015+ syntax in app code
 
 random
 facts
+underscore
+reactive-var
diff --git a/slow-publish.js b/slow-publish.js
index ee6e33f..5932f5a 100644
--- a/slow-publish.js
+++ b/slow-publish.js
@@ -4,9 +4,12 @@ if (Meteor.isClient) {
   Meteor.startup(function () {
     Meteor.subscribe('last-document', {onStop: function (error) {console.log(error)}});
   });
+
+  var subscribeReady = new ReactiveVar(false);
   
   Template.hello.helpers({
     latest: function () {
+      if (!subscribeReady.get()) { return 'not ready';}
       // Comment this line out to make subscription fast.
       return Documents.findOne({}, {sort: {createdAt: -1}});
     }
@@ -22,8 +25,14 @@ if (Meteor.isClient) {
   Template.hello.events({
     'click button': function () {
       var start = new Date().valueOf();
+
+      subscribeReady.set(false);
+      
       Meteor.subscribe('documents', {
         onReady: function () {
+
+          subscribeReady.set(true);
+
           var stop = new Date().valueOf();
           console.log("Subscription took", ((stop - start) / 1000) + " seconds");
         },
```

**Comment by mitar** [comment]
@osv: This is just a reproduction. Imagine that instead you want to push 100 documents after the publish endpoint was already ready. Then you have the same problem.

**Comment by osv** [comment]
yeah.. But if you expect so many changes, better to use old way - REST or method call :)

**Comment by mitar** [comment]
But that is not reactive. Which is what Meteor promises to make it magically happen and work for you.

**Comment by AlbinoGeek** [comment]
Hence my suggestion about a middle ground with a timeout of either too many
queries hit, or too long a delay (100 oplog changes or 500ms, whichever
hits first.)

**Comment by mitar** [comment]
Yes, that is what #5680 is about. But we discovered that batching does not help because of current Minimongo implementation which still reevaluates the query every time inside a batch.

**Comment by AlbinoGeek** [comment]
Ahh I see; I'm sorry.  I have the project on watch but I missed the PR
showing up.  I see it's just not as easy as setting pause, waiting for
batch completion (triggered), then resuming; sadly.  I'm using
IndexedDB/WebSQL with the ApplicationCache package to provide a "Fully
Client-Side" application of sorts at the moment, where WebSQL does not have
this batch issue.  (The implementation allows me to feed the oplog directly
into WebSQL's write log, and update async.)

The Pro is that I have no delay on Publish, no delay on Subscribe, I can
hit the client as hard as I want to and as often as I want to.
A huge pro is that the client can save (15MB, requires user permission) a
copy of the application and database to their browser for fast reloads.
The Con is that I lose some data-sync, a client can read an old value (as
there's ~600ms delay on client updates the way I do worked around it.)

**Comment by lorensr** [comment]
I use subs-manager to sub to most of the data my app needs at page load. I noticed that my subs become ready sooner when I wait until they're ready before rendering templates. It sounds like this might be the reason.

**Comment by mitar** [comment]
#5680 has been merged, so for me this addresses this.
