### ISSUE TITLE
publishing packages for 1.1 version 

### ISSUE THREAD

**Issue by vijayanant** [meteor/meteor#5634]
Hi, 
We are on 1.1 version (moving to 1.2 shortly). We are unable to publish a package that is compatible to 1.1. 

meteor-tool seems to update automatically to 1.2.1 before publishing. 

and we get the below error  while adding the package 

While selecting package versions:
error: unknown package: isobuild:isopack-2

Works fine while adding the package on 1.2.1 version though

Thanks

**Comment by mitar** [comment]
Just use:

```
meteor --release 1.1.0.3 publish
```

That's what I am doing with all my packages. :-)

**Comment by vijayanant** [comment]
Thanks. That worked.

**Comment by stubailo** [comment]
Yep, that works, although there might be a bug if packages published with new versions of Meteor are not usable in 1.1.
