### ISSUE TITLE
Integrating Middle Gear with Meteor

### ISSUE THREAD

**Issue by behzadeshan** [meteor/meteor#5638]
Hi,
I am the creator of a new view engine named `Middle Gear`. You can check it here:
https://www.npmjs.com/package/middle-gear
I need documentation for integrating it with meteor.

**Comment by stubailo** [comment]
Hi, I think the best thing to do would be to post on the forums and ask for help: https://forums.meteor.com/

There are three parts of integrating this:

1. Make a build plugin to compile your template files
2. Make a Meteor package to include the runtime code
3. Integrate with Meteor's reactive data sources that use Tracker, through Tracker.autorun

If there are people who have experience building Meteor packages on the forums that are excited about Middle Gear, they'd be the best to work with.

**Comment by behzadeshan** [comment]
Ok thank you.
