### ISSUE TITLE
Make sure access rules are compatible with Cordova iOS 4.0

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#5642]
See https://github.com/shazron/cordova-discuss/blob/ios-remove-whitelist/proposals/ios-whitelist-removal.md

Do we need make changes to `App.accessRule`? How about compatibility with the `browser-policy` package and CSP?

**Comment by denisbabineau** [comment]
@martijnwalraven not sure if my question/concern should be aimed at browser-policy or cordova-plugin-meteor-webapp; this (and to yourself) seems like the best place to ask for guidance. Targeting android/ios 8+ using Meteor 1.3 currently using exclusively crosswalk/WKWebview respectively; it appears App.accessRule() defines whitelist (plugin) rules only and doesn't automatically add CSP equivalent on mobile so I was going to rely on App.accessRule()+browser-policy for CSP but it appears that package is only for webapp (versus cordova-plugin-meteor-webapp for mobile). Should I instead rely on App.accessRule()+<meta> tags in my HTML for CSP?

Do you foresee/would it make sense having cordova-plugin-meteor-webapp/browser-policy updated to support setting CSP headers from the embedded http server (should I open a feature request issue in cordova-plugin-meteor-webapp)?

Thanks!

**Comment by martijnwalraven** [comment]
You're right, `browser-policy` currently does not support setting CSP rules for mobile apps. Instead, we add a default set of rules to the boilerplate `index.html` that should allow basically everything:
`<meta http-equiv="Content-Security-Policy" content="default-src * data: blob: 'unsafe-inline' 'unsafe-eval';">`. Are you encountering any errors?

If we want to make this more configurable, using `browser-policy` to set the rules in the `meta http-equiv` tag would be the easiest I think. I don't think there is any benefit in setting the headers, and this way the local web server in the plugin would not need to be involved. 

We could also make `App.accessRule` add the appropriate rules automatically to `browser-policy`.

**Comment by denisbabineau** [comment]
I'm not encountering any errors, I'm actually looking at securing the app. Providing my own http-equiv with script-src, image-src, etc. does appear to override the default wildcard rule from the boilerplate in default-src properly which is what I want, so I'll stick with this approach.

I like your suggested approach, it would allow for a more consistent approach if targeting both mobile & browser.

Thanks for the feedback, you guys do awesome work!
