### ISSUE TITLE
Virus scanner slows/stalls Meteor on Windows

### ISSUE THREAD

**Issue by SCBuergel** [meteor/meteor#5644]
I tried to install Meteor from your website using Windows 7 (Service Pack 1). Using both normal account and admin account I do not get the installer to pass the point of "Installing Meteor... please wait. (This may take a minute or two.)" Even after 15 minutes I could not get past this point. I do not know where to locate any log files to give you more information. The only process that I can spot being busy is 7sa.exe (7-zip Standalone Console) every now and then reaching up to 5% CPU load. Any help would be greatly appreciated.

**Comment by SCBuergel** [comment]
Turned out that this was due to some anti virus scan. Maybe detect such interference and warn/suggest user to switch off such software.

**Comment by AlbinoGeek** [comment]
@SCBuergel It's out of scope for the Meteor project, they don't seem to even EkevatuibReqyured the installer last I checked on WIndows 10 (I had to specifically change UAC to run Meteor's installer as my users are configured with Family Safety.)

**Comment by avital** [comment]
It would be nice if the Meteor Windows Installer worked with antiviruses as well, but we don't currently have plans to change the installer. Let's keep this open in case we do.

**Comment by AlbinoGeek** [comment]
@avital 

#### Leaving these notes for whoever implements this.

You can check for an active AntiVirus with a WMI:// query to Windows Security Center.

This is explained in the [API DOCUMENTATION](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/bd97d9e6-75c1-4f58-9573-9009df5de19b/security-center-api)

Prior to Windows 7 SP1:
The WMI path for the SecurityCenter is `\\MACHINE-NAME\root\SecurityCenter`

for Windows 7 SP1 and newer:
The WMI path for the SecurityCenter is `\\MACHINE-NAME\root\SecurityCenter2`

Alternatively, check the registry at location:
`HKEY_LOCAL_MACHINE\SOFTWARE \Microsoft\Security Center`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Virus%20scanner%20slows%2Fstalls%20Meteor%20on%20Windows&body=Migrated%20from:%20meteor/meteor%235644) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
