### ISSUE TITLE
Meteor crashes when sending a really long email and MAIL_URL not configured

### ISSUE THREAD

**Issue by extremeandy** [meteor/meteor#5646]
Normally, if MAIL_URL is not configured, Meteor logs the email to the server console. However, if the email is really long (say 50KB of text), then Meteor crashes with a variety of errors while attempting to log the email to the console:
- Process exited
- Out of memory
- Some others...

**Comment by AlbinoGeek** [comment]
This is duplicate of (due to/caused by) other bugs dealing with "Out of memory" on large console.log .

Please see: #5543

**Comment by timbotnik** [comment]
@extremeandy - #5543 specifically refers to the issue being Windows-only.  Is this only on Windows as well?

**Comment by extremeandy** [comment]
@timbotnik I am running Windows for dev environment, yes, but have not tested in other environments

**Comment by abernix** [comment]
Closing in favor of #5543 to track this issue further.  Thanks for reporting this originally!
