### ISSUE TITLE
Should reactive dict clear values if loaded for second time?

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5647]
The use case is template state. If I do:

```
Template.X.onCreated(function() {
  this.state = new ReactiveDict('X');
});
```

Then the _second_ time I create an "X" (say I route to it, away, then back), I get an exception that there's already a dict called "X" defined.

For this use case, the correct behaviour is to _clear_ the reactive dict, and treat it like a brand new one.

I don't think thing there's any legitimate other use case where this would happen. The existing error could help avoid bugs though.

One option is to have a `{clearOnSecondRun}` option to reactive dict. It's just a bit awkward to have to do that all the time.

**Comment by stubailo** [comment]
> The existing error could help avoid bugs though.

Yeah, I'm worried that people will accidentally use the same name all over the place, and their code will collide in weird ways. But that's already possible with anything that has global strings involved.

**Comment by AlbinoGeek** [comment]
@stubailo Here I thought ReactiveDict (based on documentation) was meant to be scoped to the Template you use it in, keeping context; hence not a global. (?)

**Comment by AlbinoGeek** [comment]
I use ReactiveDict to hold an error state in my templates, and I manually bind (now that I know it's not necessarily intended functionality) my variables directly to my template data context (during .rendered I set them as properties to this.data , thus accessible directly in the template as {{variables}})

Since I am using ReactiveField 's alternative syntax, you can simply use this in your templates:

test.coffee
```coffee
Template.test.rendered = ->
  @data.error = ReactiveField('') # default value empty

Template.test.events =
  'submit form': (event) ->
    event.preventDefault()
    @error('There as an error!')
```

test.tpl.jade
```jade
if error
  .ui.top.attached.message
    error

form.ui.form
  input(type='text')
  button(type='submit') Submit
```

**Comment by martunta** [comment]
is there any workaround for this bug?
I seem to hit the error when accessing the same route with iron-router.

**Comment by tmeasday** [comment]
@martunta you could write a subclass for `ReactiveDict` that has the behaviour I wanted pretty easily.

**Comment by hwillson** [comment]
Given the lack of interest/activity on this issue, and the fact that as mentioned in https://github.com/meteor/meteor/issues/5647#issuecomment-203676449 `ReactiveDict` can be extended to handle this issue outside of the Meteor codebase, I'll close this issue for now. Thanks for reporting this originally!
