### ISSUE TITLE
Meteor add-platform ios fails ...

### ISSUE THREAD

**Issue by anshumanpurohit** [meteor/meteor#5648]
Having this issue on OS X. Using zsh, project is the meteor project directory.
Meteor 1.2.0.2

➜ project meteor list-platforms
browser
server

➜ project meteor add-platform ios 
=> Errors executing Cordova commands:

While adding platform iOS to Cordova project:
Cordova error: Platform ios already added. 
(If the error message contains suggestions for a fix, note that this may not
apply to the Meteor integration. You can try running again with the
--verbose option to help diagnose the issue.)

BTW, unlike Issue #5317 , I don't have a separate instance or Cordova installed and have removed .meteor/local/cordova_build several time.

**Comment by martijnwalraven** [comment]
This might just be a typo in your description, but did you try `rm -rf .meteor/local/cordova-build` (note the dash instead of the underscore)?

**Comment by anshumanpurohit** [comment]
Sorry about the typo, but I have tried that (with dash instead of the underscore) and it does not fix the issue. Thanks for the quick response!

**Comment by martijnwalraven** [comment]
Hmmm, are you sure there is no other parent Cordova build directory? Could you try moving the project directory to the root and see if you have the same problem?

**Comment by anshumanpurohit** [comment]
Yup, somehow meteor (add-platform?) had created a few folders in parent of my project. Removing a folder named www fixed the issue for me.
