### ISSUE TITLE
Is the Google oAuth 'profile' scope really required?

### ISSUE THREAD

**Issue by MasterAM** [meteor/meteor#5650]
Meteor's `google` package requests the 'profile' permission/scope with Google oAuth.

When reading the [Google documentation](https://developers.google.com/+/web/api/rest/oauth#profile), it may seem like this scope is indeed mandatory for getting the user's id. AFAIK, this is not really the case.

The `email` scope is sufficient for getting the required info.
To test this, I forked the `google` package, removed the `profile` scope, leaving only the `email` scope.
It worked very well. The only thing that was missing in the created user object was the `locale` field. 

I believe that this scope can (and should) be made optional,  since requesting unneeded permissions, especially in a very popular authentication mechanism, may deter some users from registering to our apps.

I will gladly submit this as a PR, if you find it worthy.

**Comment by rdickert** [comment]
Thanks for pointing this out! If you are confident it is not necessary, I'd be in favor of removing it. Thanks also for offering to do a PR - I'd say go for it.

**Comment by MasterAM** [comment]
Thanks for the response.

I created a PR for the issue.

I think that the `google` and `accounts-google` packages should be configurable via `Meteor.settings`, since there are some options that are not supported at the moment that I find important, in particular: adding default scopes and deciding whether or not to force the Google account selection popup to appear.

I believe that having that construct in place will make it easier to set options that override the defaults and can, in turn, be overridden by the options supplied to `Meteor.loginWithGoogle()`.

This may also make keeping backward-compatibility easier.

What do you think about this approach?

**Comment by laosb** [comment]
Close since the PR was merged and the functionality was released in 1.4.0.1.
