### ISSUE TITLE
$elemMatch with RegExp is not taken into account in calculating mongo observe key

### ISSUE THREAD

**Issue by lirbank** [meteor/meteor#5652]
**_UPDATE: Workaround available at the bottom of this thread**_

Given a publish function that takes a param which is used to query the DB using $elemMatch, the subscriber is not being updated after the initial data has been sent, despite the subscription being dynamically reloaded. It works as expected as long as $elemMatch is not being used.

Reproduction (vanilla Meteor 1.2.1, removed autopublish and insecure packages):
https://github.com/lirbank/meteor-elemmatch-regex-test
1. Start the app (or reload the browser) - all (five) persons are published.
2. Keep an eye on the server console.
3. In the "Search by job title" input, type "CEO" (all well - server says five persons found with job title "CEO" and five persons available in minimongo).
4. Now add any character after CEO eg "CEOX" so that the search match no persons/titles (error - server says zero persons are found with job title "CEOX" but minimongo says five).

This only happens when using [$elemMatch with RegExp](https://github.com/lirbank/meteor-elemmatch-regex-test/blob/master/server/server.js#L21-L25), not when [using RegExp directly](https://github.com/lirbank/meteor-elemmatch-regex-test/blob/master/server/server.js#L17) to query a subdocument in an array.

**Comment by lirbank** [comment]
Alternative test:

1. Start the app (or reload the browser) - all (five) persons are published.
2. Keep an eye on the server console.
3. In the "Search by job title" input, type "CoCEO" (all well - server says no persons found with job title "CoCEO" and no persons available in minimongo).
4. Now remove the first two character "Co" leaving only "CEO" in the input (error - on the server we see that there are now five matches but the client says there are zero).

**Comment by lirbank** [comment]
Update:

1. I've tried to with a low level publish function instead of simply returning the cursor, but the problem remains.

2. A cheezy workaround is to stop the subscription in the autorun function before re-running it, it works but forces a full re-load of all the subscribed data so it's slow and flickers as the template has to be re-rendered, etc. (not ideal):

```javascript
Template.Persons.onCreated(function () {
  Session.setDefault('searchStr', '');

  let self = this;
  let handle;

  this.autorun(function () {
    if (handle) handle.stop();
    handle = self.subscribe('persons', Session.get('searchStr'));
  });
});
```

**Comment by tmeasday** [comment]
Thanks for the repro @lirbank! That's very helpful.

The issue here is that the Mongo driver isn't taking the `$elemMatch` into account when calculating the observe key. So it's re-using the initial observer that's setup with `searchStr = ''` for each subsequent subscription.

Specifically, the `observeKey` on this line: https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L1153-L1154 is the same for this query, no matter what `searchStr` is put in.

I'll rename the issue to reflect this.

**Comment by deejross** [comment]
I noticed this today myself. In looking for an alternative for $elemMatch, I found that using something like this works for me (haven't tested reactivity yet), but I don't know what the downside is, if any:

```javascript
Collection.find({'theList.theKey': {$in: ['value1', 'value2']}})
```

In this case, it would search "theList" for an Object whose "theKey" property has a value equaling "value1" or "value2". Again, not sure if this is a good workaround or not.

**Comment by lirbank** [comment]
@deejross $elemMatch is necessary when matching on more than one (but not all) fields of the subsdocuments. 

I think your example works on my repro, because I don't match on multiple fields, to make the example simpler (I just wanted to show that $elemMatch doesn't work properly with RegExp) but in a real case where you want to match on multiple fields within the same subdoc you have to use $elemMatch (unless you can match all the fields).

Ex this will not work as expected (it will match all docs having a subdoc with theKey set to value1 or value 2, OR having a subdoc with theSecondKey set to value1):
```
Collection.find({
  'theList.theKey': {$in: ['value1', 'value2']},
  'theList.theSecondKey': {$in: ['value1', 'value2']},
});
```

And this will only match document having a subdoc where theKey and theSecondKey are either set to value1 or value2, but it not subdocuments having additional fields (ex. it won't match this document `{theList: [{theKey: value1, theSecondkey: value2, aThirdField: 'Yo!'}]}`.
```
Collection.find({
  theList: {
    theKey': {$in: ['value1', 'value2']},
    theSecondKey': {$in: ['value1', 'value2']}
  }
});
```

**Comment by lirbank** [comment]
Just found a workaround, using the `$regex` operator instead of a native JS RegExp object and the Mongo observer seems to work just fine.

```javascript
{
  '$elemMatch': {
    // Use this:
    title: {$regex: searchStr, $options: 'i'}

    // Instead of this:
    //title: new RegExp(searchStr, 'i')
  }
}

**Comment by vblagomir** [comment]
I have similar problem trying to send a RegExp over to a method (for dynamic publication with RegExp search). Can not receive RegExp on the server - it just gets an empty object.. :-(

And mongo $regex is not a workaround, as it does not work with $in query.. From MongoDB Docs:
> To include a regular expression in an $in query expression, you can only use JavaScript regular expression objects (i.e. /pattern/ ). For example:
> `{ name: { $in: [ /^acme/i, /^ack/ ] } }`
> You cannot use $regex operator expressions inside an $in.

**Comment by mitar** [comment]
I checked and this is still an issue.
