### ISSUE TITLE
why not start meteor server with another random port

### ISSUE THREAD

**Issue by dfang** [meteor/meteor#5653]
I mean start a new meteor app with a random port if you didn't specify a port option and port 3000 is used.

sometimes this is very handy when we're playing demos.

thanks !

**Comment by AlbinoGeek** [comment]
@dfang It would break support for everything that relies on Meteor using localhost:3000 at all times :).

**Comment by rozzzly** [comment]
It would needlessly complicate things for most developers. If your workflow could benefit from this, a simple bash script would work.

**Comment by AlbinoGeek** [comment]
@dfang 

```batch
SET /A METEOR_PORT=%RANDOM% * 100 / 32768 + 3000
```

Here you go, sets %METEOR_PORT% to be a random number around 3000-3200 .

```batch
REM Random port (REM is comment in Batch.)
SET /A METEOR_PORT=%RANDOM% * 100 / 32768 + 1024

REM Start meteor on the random port
start meteor run --port 0.0.0.0:%METEOR_PORT%

REM Start browser on the same port
start http://localhost:%METEOR_PORT%
```

**Comment by zol** [comment]
@dfang This isn't on our current roadmap of changes. Thanks @AlbinoGeek for pointing out a wrapper script for this.

**Comment by dfang** [comment]
thanks all
