### ISSUE TITLE
Using Assets within a package?

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5655]
I have a package that looks as follows
```
my-package
├── README.md
├── collections.js
├── fixtures
│   └── fake.json
├── package.js
├── permissions.js
├── publications.js
├── routes.js
└── seed.js
```

In my package, I use the following:

```
api.addAsset('fixtures/fake.json', 'server');
```

In my `seed` file, I want to do something like this:

```
Meteor.startup(function () {
  if (process.env.NODE_ENV === 'development') {
    EJSON.parse(Assets.getText(/** ??? */)).forEach(fake => {
      // ...
    });
  }
});
```

However, I cannot find a way to access this asset _within_ my package. I can use fs though:

```
const path = Npm.require('path');
const fs = Npm.require('fs');

let base = path.resolve('./assets/packages/my-package/fixtures');
fs.readFileSync(path.join(base, 'fake.json'));
```

Seems unadvisable. What's the appropriate way to do this?

**Comment by sebakerckhof** [comment]
I don't think there is a singular version of addassets.
It should be:
` api.addAssets(['fixtures/fake.json'],'server');`

and you can request it like:
`Assets.getText('fixtures/fake.json)`

**Comment by stubailo** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. I think @sebakerckhof's answer should be correct.
