### ISSUE TITLE
[idea] Allow asynchronous code in build plugins (registerCompiler) for better control of performance.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5656]
**_1 Upvote**_ To make this work, the `processFilesForTarget` of a compiler could be passed a promise that is to be resolved by the compiler when compiling is complete. The signature could become `processFilesForTarget(inputFiles, promise)`. Either that, or perhaps `processFilesForTarget` could just return a promise, and in that case Meteor can treat it asynchronously. If no promise is returned, then it is assumed synchronous.

This would be really convenient for new features arriving to JavaScript for asynchronous control flow like generator/yield and async/await functions.

**Comment by stubailo** [comment]
I think this will be implemented in a different way - you will simply be able to use `Promise.await` or the `await` keyword to return the result in a synchronous style while still being asynchronous. I think you can already use the Meteor `promise` package to do this, does that not work for you?

I guess I'm not really sure what is missing.

**Comment by trusktr** [comment]
@stubailo Is processFilesForTarget already expected to be async by Meteor (Meteor awaits my compiler's `processFilesForTarget` method when the method is called internally by Meteor)?

If I return a promise, will Meteor wait for that to be resolved (that's what `async`/`await` does)?

**Comment by dotansimha** [comment]
+1 !

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5656#issuecomment-157540976, based on what you're describing Meteor should already support this functionality. If you feel like something is still missing here, please open a new feature request over in https://github.com/meteor/meteor-feature-requests. Thanks!
