### ISSUE TITLE
Meteor.publish doesn't recognize methods of an object passed as an argument in subscribe call

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#5657]
Server (coffee)
```coffee
Meteor.publish 'posts', (args)->
 userId = @userId
 Posts.find(cityId:args.cityId(userId))
```
Client
```coffee
obj=
  cityId:(userId)->Users.findOne(userId).city
Meteor.subscribe 'posts', obj
```
Throws `Exception from sub posts id WcuyuY6eWNBxFw8yK TypeError: Object #<Object>
 has no method cityId` in server console.

**Comment by ShockiTV** [comment]
arguments must be E-JSON, function is not

**Comment by avalanche1** [comment]
This must be clearly stated in the docs. And the error should be explicit, not this '<Object> has no method'.

**Comment by stubailo** [comment]
This line should be changed from `Any` to `EJSONable`: https://github.com/meteor/meteor/blob/9740c232c1b0c4a6358651bc632a21e48769136d/packages/ddp-client/livedata_connection.js#L473
