### ISSUE TITLE
Meteor storing mongo documents with random create ts

### ISSUE THREAD

**Issue by jessonjoy** [meteor/meteor#5661]
I depend on mongo.collection.ObjectId().getTimestamp to get the created ts for that document. However when inserting via meteor, the document has some crazy future dates always.

`<addr>`
WOO = new Mongo.Collection("WOO", {idGeneration: 'MONGO'});
`<addr>`

Generates - ISODate("2038-04-10T01:10:46Z")

**Comment by avital** [comment]
Document IDs in Meteor are generated on the client, not on the server. So timestamps can't be made reliable anyways (clients' clocks can be out of sync). Meteor doesn't try.

If you want to know when documents were created, you should add a `createdAt` field that's added on the server before documents are inserted. The `collection-hooks` package lets you do that: https://www.discovermeteor.com/blog/a-look-at-meteor-collection-hooks/

Hope this helps!
