### ISSUE TITLE
Accounts.forgotPassword and Accounts.verifyEmail throw error instead of pass error in callback

### ISSUE THREAD

**Issue by mishavee** [meteor/meteor#5664]
Where the email address is blank, or the token is blank, the methods throw a new error, but the docs say they return errors in the callback.

The bad thing about this is undocumented behaviour, plus needing two forms of error handling.

Code in: meteor/packages/accounts-password/password_client.js

**Comment by stubailo** [comment]
I guess there is a bit of distinction of a runtime error that can't be predicted, vs. a programming error where the argument is of the wrong type. In an ideal world, these arguments could be statically checked.

However, I'd definitely accept a PR for returning these errors through the callback instead of throwing them.

**Comment by mishavee** [comment]
Thanks @stubailo, that sounds fun. Is there a guide to submitting a pull-request? Which branch do I clone from, and pull-request to? Can I link it to this issue? Is there automated tests to extend?
"Questions, questions, always questions" - I'm looking at other pull requests to see what to do.

**Comment by stubailo** [comment]
Unfortunately there isn't a great guide about it. But basically:

1. You branch off of `devel` and pull request to `devel`
2. Run the tests with `./meteor test-packages` in the root directory of the repo
3. The tests should be in the same package as the code you'll be changing, it is also probably a good idea to add more tests about the error handling in this case
3. Link to the issue by mentioning the issue in the PR description

**Comment by mishavee** [comment]
Thanks for the good directions :)  I found some similar info in [Contributing-to-Meteor](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor) but your steps are more useful.

**Comment by mishavee** [comment]
Hi @stubailo, I've had fun: cloned the repo, created a new local branch from devel, patched the file, created two tests that pass, and filled in the contributors form. I tried creating a pull request from github desktop, no permission to publish ... same if I try to push the new branch.

Do I need to fork into another github repo just to do a pull request?
Thanks for your time!

**Comment by stubailo** [comment]
Yes, you can only do a pull request on github from a fork, which is kind of
like a branch but on github.

**Comment by mishavee** [comment]
Okay I did a fork, added a branch with the changes, created a pull request to devel: #5681
Now it's waiting for the tests to run. Yay, thanks for your help @stubailo!

**Comment by laosb** [comment]
Fixed in #7117!
