### ISSUE TITLE
Improve Android documentation

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5670]
So my buddy told me all the Android emulators are crap so I bought an Android phone to test on, and...

```
=> Errors executing Cordova commands:         

   While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR: Failed to deploy to device, no devices found.
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```

Do I need to register the phone with meteor or something?

**Comment by ccorcos** [comment]
This is the answer:

http://stackoverflow.com/a/25698037/1191551

I think this information should be included in the meteor docs. Theres no way I would have known to do that.

**Comment by ccorcos** [comment]
Now I'm getting `Unfortunately APP_NAME has stopped` on the device...

**Comment by ccorcos** [comment]
I think this command should probably be in the docs somewhere too:

```
~/.meteor/android_bundle/android-sdk/platform-tools/adb logcat     
```

**Comment by ccorcos** [comment]
hmm. apparently the BackgroundColor preference doesnt work with crosswalk

```
App.setPreference('BackgroundColor', '0x000000ff', 'ios');
```

**Comment by martijnwalraven** [comment]
To start with the last one, the `BackgroundColor` issue is a known Crosswalk bug (see [this forum post](https://forums.meteor.com/t/crosswalk-1-3-1-is-broken/10571)).

I'm changing this issue to 'Improve Android documentation', because that seems what this is mostly about.

**Comment by ccorcos** [comment]
@martijnwalraven sounds good. It looks like most of these issues have been solved somewhere before. But it still took me hours to get through and track down all these issues. Perhaps a simple "Android Issues" markdown wiki would be great to compile all of these weird quirks and issues.

**Comment by AlbinoGeek** [comment]
Please create a documentation series regarding the platforms.

- Webapp could list known (how to SSL?) for example.
- Android needs to explain how to get developing on an android (see this issue)
- Cordova/ios needs to explain how to attach the device, etc.

**Comment by benstr** [comment]
I agree with @ccorcos. I spent unnecessary hours debugging my upgrade to crosswalk. Finding it frustrating navigating numerous issues and many of them contain *"this is a known bug..."*.

**Comment by hwillson** [comment]
Since this issue was created the Meteor Guide launched and includes a detailed [Mobile](https://guide.meteor.com/mobile.html) section. If you notice any issues with the content listed in this section, please open a new issue in the [Guide repo](https://github.com/meteor/guide). Closing this issue - thanks!
