### ISSUE TITLE
jarsigner: unable to open jar file: unaligned.apk

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5672]
I'm following the docs here.

https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store

And its unclear what I'm supposed to do here:

```sh
cd ~/build-output-directory/android/
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 unaligned.apk your-app-name
```

In this directory, there's a project folder and a readme. Thats it. When I cd to the project, I still dont see and unaligned.apk...

**Comment by ccorcos** [comment]
I thiknk I found what I was looking for by using `find . -name '*.apk'`

**Comment by ccorcos** [comment]
ok I tried this one `./build/outputs/apk/android-armv7-release-unsigned.apk` because apprently armv7 is more popular and the unaligned one says debug do that doesnt seem right.

And i got this weird warning:

```
Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-04-03) or after any future revocation date.
```

**Comment by martijnwalraven** [comment]
With Crosswalk added, there will actually be multiple apks for the different architectures, and you will have to submit all. The documentation needs to be updated to reflect this. See #5274.

**Comment by ccorcos** [comment]
ok. so I don't need to submit the debug ones. thanks!

**Comment by ayoubkhan558** [comment]
Just use absolute paths instead of relative paths
`jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore myApp.keystore E:\myApp\platforms\android\app\build\outputs\apk\release\app-release-unsigned.apk myApp`
