### ISSUE TITLE
meteor 1.2 支持react ，会不会考虑结合 ant design

### ISSUE THREAD

**Issue by pengqiuyuan** [meteor/meteor#5675]
https://github.com/ant-design/ant-design

**Comment by AlbinoGeek** [comment]
Is this advertising another project or?
I can't really tell how this is a bug.

**Comment by pengqiuyuan** [comment]
我想放在一起使用，应该很棒

**Comment by keithyau** [comment]
I think he is saying it will be great if meteor can support ant design

**Comment by AlbinoGeek** [comment]
@keithyau Ahh, I see now.  Sorry @pengqiuyuan .

**Comment by pengqiuyuan** [comment]
yes,Is what I mean,it will be great if meteor can support ant design. Thanks @keithyau  @AlbinoGeek

**Comment by tmeasday** [comment]
Hi, although we take feature requests on github, we probably need something more specific than this.

Is it not possible to use ant-design from our React integration? If so, what is missing?
