### ISSUE TITLE
Add indices to minimongo

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5678]
**_3 Upvotes**_ See https://github.com/meteor/meteor/issues/5633 for an example of the kind of problems we see because MM can be quite slow.

It would be great to support at least basic things like ordering.

**Comment by mitar** [comment]
Does MDG has a bounty program? I might find a person who could implement this. :-)

**Comment by AlbinoGeek** [comment]
Please, as indexing would literally fix all our problems...

**Comment by sebakerckhof** [comment]
I do think one should be able to specify different indexes for MM than the ones you put on your mongodb (e.g. using ensureIndex)

**Comment by mitar** [comment]
Yea, you would probably call `ensureIndex` and if you call it on client, you call on Minimongo, and on server on MongoDB. And you can decide that those calls are different.

**Comment by zodern** [comment]
There is [this package](https://forums.meteor.com/t/adding-indexing-to-minimongo/9130) by @helfer, but it doesn't support sorting.

**Comment by teknologist** [comment]
+1

**Comment by khaledkbadr** [comment]
+1

**Comment by laran** [comment]
+1

**Comment by vlasky** [comment]
+1

I think this should be added to the Meteor roadmap.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20indices%20to%20minimongo&body=Migrated%20from:%20meteor/meteor%235678) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
