### ISSUE TITLE
Windows 10: Error: EBADF, read

### ISSUE THREAD

**Issue by AlbinoGeek** [meteor/meteor#5679]
Hello!

`Meteor@1.2.1` for `Microsoft Windows 10.0.10586` (Windows 10 ... SP1 , the first major "Upgrade" rollout version, which actually pulls the Windows installer again, and forces a "Refresh" during the upgrade process.  Imagine a Win8 -> 8.1 upgrade process.)

Repeated console log (server):
```
   [timestamp]? (STDERR) Error: EBADF, read
   [timestamp]? (STDERR) Error: EBADF, read
   [timestamp]? (STDERR) Error: EBADF, read
```

I will see it happen during server idle.  I have a Chrome browser idled on the app, forcing it to keep heartbeat (1 connected client).  This issue DOES NOT occur on the staging or production servers (linux), so I know it is Windows specific.

Other times it will say it can't read a specific file, or had issues sending a file (js) to the browser.

The server is building from an NTFS filesystem.

**Comment by stubailo** [comment]
I think this is a duplicate of: https://github.com/meteor/meteor/issues/4201

**Comment by AlbinoGeek** [comment]
Yup, you were right on the dupe!   Sorry
