### ISSUE TITLE
Windows 10: EXFAT Filesystem

### ISSUE THREAD

**Issue by AlbinoGeek** [meteor/meteor#5683]
Since the new Meteor (1.0+) build system creates **millions** of files in the .meteor/local directory, it is not suited for some filesystems that place file information next to the file (such as EXFAT.)  I have also seen similar (but drastically worse) behaviour on NTFS, but I will open a different issue for that.

On EXFAT at least, the build time is increased significantly as the build folders are 10 levels deep, file names are ~200 characters each; and many tens of thousands (even millions on larger package imports) of files are created for every hot code reload.

Creating repro ...

---

On Windows 10.1 (1511, [Version 10.0.10586], Latest Stable Release) ; using an EXFAT file system on a secondary partition (my 2TB internal, but not OS/System SSD (mounted at O:)) I can see huge access times (20,000+ms) only during meteor builds.  The disk throughput also slows to a grinding halt (<100b/sec) as shown in Task Manager's Performance tab.

I have reproduced this on my development Desktop (2TB Samsung PRO 850) as well as both my spare laptop (120 GB generic SSHD) and my local test server (2x 1TB Samsung 840 PRO in "Volume Mirroring (Windows equiv. of RAID1)").  This exact behaviour is specific to filesystems similar to EXFAT.

**Comment by AlbinoGeek** [comment]
More FAT / FAT32 / EXFAT specific issues:

When using Meteor tools on Windows 10 with an EXFAT Filesystem I get (repeatedly) "The file name(s) would be too long for the destination folder.  You can shorten the file name and try again, or try a location that has a shorter path."  Also the "Path too long" long error code (0x80010135).

**Comment by AlbinoGeek** [comment]
Example paths:

`C:\Users\Damon-10\Documents\Git Projects\redacted\.meteor\local\.build673345.build\programs\.build496518.web.browser\packages\semantic_ui-css\themes\default\assets\images` (171 characters)

Or this directory (primary offender): `C:\Users\Damon-10\Documents\Git Projects\redacted\.meteor\local\bundler-cache\linker` Containing `*27,814*` of files named `0b5e377bf0c236805832d2a22efb85f230e5f478.cache` and similar. (150+ characters)

Some paths start getting VERY DEEP: `C:\Users\Damon-10\Documents\Git Projects\redacted\.meteor\local\isopacks\xiphy_jade-coffee\plugin.compileJade.os\npm\caching-compiler\node_modules\lru-cache\lib` (160 characters)

I'm lucky enough that my project is rooted in `C:\Users\Damon-10\Documents\Git Projects\redacted\` (50 characters), if it were any deeper; I wouldn't be able to delete cache files generated by the linker.

**Comment by stubailo** [comment]
Wow! Well, Meteor was developed initially to work on Linux and Mac, and then we did some porting work to make it run on Windows. We never really got to the stage of optimizing performance or rewriting the logic to work better with different file systems. I imagine it would take some serious rearchitecting to make the caches work differently.

I'll bring this to the attention of the platform team, maybe they will be able to do something about it in the near future. Thanks for the detailed information.

**Comment by phenix82** [comment]
Hi AlbinoGeek,
I notice you have "Path too long" long error code (0x80010135), and why not try the Long Path Tool, I have encountered the same issue, but with the help of this tool, it fixed.

**Comment by netomx** [comment]
Albino, we are waiting for you on LowEndTalk for some explanations

**Comment by hwillson** [comment]
There have been many Meteor performance improvements made since this issue was opened (and Meteor no longer creates an infinitely growing number of files in `.meteor/local`). Many of these performance improvements have targeted Windows specifically. If you're still encountering issues using a current version of Meteor on Windows, please consider opening a new issue. Thanks!
