### ISSUE TITLE
Running meteor in other iOS simulator device

### ISSUE THREAD

**Issue by mcchrish** [meteor/meteor#5684]
It seems to me that meteor 1.2.1 only runs on iphone 6 simulator. How can I target a specify device when running in the simulator?

**Comment by martijnwalraven** [comment]
There is no command line option for this, but if you use `meteor run ios-device`, which opens Xcode, you can select another simulator there.

**Comment by joaopiopedreira** [comment]
Can be tricky... You're better off building your project (meteor build ...) and then open it in Xcode. There you can easily change your device.

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by martijnwalraven** [comment]
Closing this as a duplicate of #3430.
