### ISSUE TITLE
Login with OAUTH services (Google,FB, etc.) does not work on Microsoft Edge on Windows 10

### ISSUE THREAD

**Issue by teknologist** [meteor/meteor#5686]
Hi,

It might just be easy to fix. Here is the info:

using

```javascript
return Meteor.loginWithGoogle({
  loginStyle: "popup",
        requestPermissions: ['email']
      }, function(error) {
        if (error) {
          return console.log(error.reason);
        }
      });
```

Popup opens and asks to be closed but nothing happens then.

Console shows this error:

```javascript
Error: Unable to get property 'focus' of undefined or null reference
TypeError: Unable to get property 'focus' of undefined or null reference
   at e (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:128:2877)
   at c.showPopup (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:128:2153)
   at c.launchLogin (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:128:1447)
   at p.requestCredential (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:136:3116)
   at e.loginWithGoogle (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:138:585)
   at click .btn-google (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_resource=true:517:276)
   at Anonymous function (https://xxxxxxxxxxxx.xxx/a82bed61c6725d852fb338a0abeaac80442c958c.js?meteor_js_
reporters.js (67,7)```


Many thanks

**Comment by stubailo** [comment]
It would be super helpful if you could run the app in development mode, to get the real stack trace of the non-minified code.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

**Comment by UziTech** [comment]
I am getting this error on IE11. In my case at least it seems to be an issue with https://github.com/meteor/meteor/blob/master/packages/oauth/oauth_browser.js#L67

```javascript
if (newwindow.focus)
```

`newwindow` is `null` for some reason so the error comes when looking for `.focus` on `null`

Changing it to

```javascript
if (newwindow && newwindow.focus)
```

stopped the error

**Comment by vsheyanov** [comment]
From Firefox 51.0.1 :
Looks like firefox is setting newWindow to null when popup was blocked (as mentioned by @UziTech )

stack:"openCenteredPopup@http://localhost:3000/packages/oauth.js?hash=a519c3410a532671028fac814c0ad30bbcd1a539:284:1
OAuth.showPopup@http://localhost:3000/packages/oauth.js?hash=a519c3410a532671028fac814c0ad30bbcd1a539:230:15
OAuth.launchLogin@http://localhost:3000/packages/oauth.js?hash=a519c3410a532671028fac814c0ad30bbcd1a539:150:5
Twitter.requestCredential@http://localhost:3000/packages/twitter.js?hash=68559687c729bf178a9f4b3d95dce00463b8eacd:177:3
Meteor.loginWithTwitter@http://localhost:3000/packages/accounts-twitter.js?hash=d1b035457a0b3b5e8dd766c47f3dd1412221d470:40:5
loginWithSocial/<@http://localhost:3000/app/app.js?hash=1c8c5de881bc65481368fc3020858f5e5fa6adf8:20630:13
loginWithSocial@http://localhost:3000/app/app.js?hash=1c8c5de881bc65481368fc3020858f5e5fa6adf8:20621:14
_loginWithSocial/<@http://localhost:3000/app/app.js?hash=1c8c5de881bc65481368fc3020858f5e5fa6adf8:19377:16
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:1105:17
"

**Comment by vsheyanov** [comment]
Can I submit PR for this?

**Comment by abernix** [comment]
@vsheyanov Can you explain the actual problem you're encountering?  Does the Window not actually close?  I'd be willing to accept a PR for the above change `(newwindow && newwindow.focus)`, but does that actually fix the problem?

I think the most important thing is to make sure you're launching `Meteor.loginWith<Service>` from trusted code which began as a user interaction (e.g. a click).

**Comment by vsheyanov** [comment]
@abernix sorry, I totally forgot about calling Popup opening from trusted code... It was called from within chain of Promises... Now it's fine
But anyway, is a fix still needed just to show proper error?
```
if (typeof newwindow === 'undefined' || newwindow === null) {
  // blocked by a popup blocker maybe?
```

**Comment by abernix** [comment]
@vsheyanov Maybe just a PR which adds a check for a truthy value there since it's coming through as `null`?  I'm not sure what the correct behavior is there (on the browser's part, returning `null` or `undefined`), but it seems that it should be "true" and that's the important part.

**Comment by vincentcarpentier** [comment]
Now in Chrome 99 the `newwindow` is `null` when popup is blocked...
The best way i think is to check `if (!newwindow || newwindow.closed) {`
Instead of <s>`if (typeof newwindow === 'undefined') {`</s>

Can I submit PR for this ?
