### ISSUE TITLE
Please add to the repository release JSON file used for each release

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5688]
In the `master` branch, together with `History.md`, it would be also great to keep a JSON file used to publish a release. That would make it easier then to create custom releases tracking the main Meteor release.

See [this discussion](https://forums.meteor.com/t/custom-meteor-release/13736/5) for more information.

**Comment by stubailo** [comment]
I'm pretty sure this command does exactly what you are looking for:

```sh
meteor show --ejson METEOR@1.2.1
```

Let me know if that doesn't work for you.

**Comment by mitar** [comment]
Thanks!

But why is that not in the repository?

**Comment by mitar** [comment]
Do you keep JSON files locally? I do not get what is your workflow here.

**Comment by stubailo** [comment]
There is never a json file in the source tree - it would just be duplicating the data from the package.js files in this repository. We use a custom script that generates it and passes it into publish release, and the official record of version numbers in git is the set of package.js files on a certain release tag.

**Comment by mitar** [comment]
Hm. Could that script be shared? ;-)

**Comment by stubailo** [comment]
Yes, it's the `meteor publish-release --from-checkout` option. See the code here: https://github.com/meteor/meteor/blob/2e69f7371abead3252053cf36fba8d3af7cae2de/tools/cli/commands-packages.js#L807-L819

**Comment by mitar** [comment]
Cool!
