### ISSUE TITLE
Wrong result from the collection operation on access denied

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#5689]
Let's say that we have a collection that have some allow/deny rules defined and the update operation is prevented from happening when called from the client.

```js
Items.allow({
  update: function() {
    return false;
  }
});
```

Now, let's say that we are trying to update a document.

```js
Items.update(id, {
  $set: {name: 'new name'}
});
```

The result of this operation is a message on the console `update failed: Access denied` which is ok but it's only for information. But what is wrong is the returned value from the `Items.update()` method. It returns `1` even if no document were modified. From what I know the same is true if it goes about `insert` and `remove` operations. Maybe it was intentional, but this way it's not possible to tell if a document was updated/removed etc. I think it's a bug. Do you know any way of getting to know (from the code) if an operation succeeded?

I've prepared reproduction repository showing a problem: https://github.com/jagi/meteor-access-denied-bug

**Comment by tmeasday** [comment]
Hi @jagi

The synchronous return value of a mutator on the client is the result of the simulation. If you want to operate based on whether the server's version worked, you should pass a callback to the mutator (i.e. `.update()` function)

**Comment by jagi** [comment]
Right, sorry for a stupid question and bothering you :) it was obvious
