### ISSUE TITLE
Adding Cordova plugin from Git URL should not accept @version

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#5692]
Although a Git URL requires a SHA reference, this is currently accepted and leads to errors during fetch:

```
meteor add cordova:https://github.com/devgeeks/Canvas2ImagePlugin@0.6.0
```

(See https://forums.meteor.com/t/how-to-use-cordova-plug-in-in-meteor/13808/2)

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in quite some time. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed. Thanks!
