### ISSUE TITLE
Windows: bad version number comparison 

### ISSUE THREAD

**Issue by k5e** [meteor/meteor#5695]
After some problems with an older project that I have left alone a couple of months I wantet to start it anew and wiped the meteor installation. After that I downloaded the latest windows installer and installed meteor. The version is reported as 1.1.10.
When I go to my project and do ```meteor update``` or simply ```meteor --version``` it starts downloading meteor-tool version 1.1.1-win.7. 
Apparently the version comparison does not get it right and considers "1.1.10" lower than "1.1.1-"
When I let it go it downgrades the app and returns:
```
C:\projects\mymeteorapp>meteor --version
WINDOWS-PREVIEW@0.3.0
```
A freshly created meteor app does not try to downgrade; it reports:
```
C:\projects>meteor create --example todos test-meteor
Created a new Meteor app in 'test-meteor' (from 'todos' template).

To run your new app:
  cd test-meteor
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn


C:\projects>cd test-meteor

C:\projects\test-meteor>meteor --version
Meteor 1.2.1
```
Am I right with my assumption, that the version comparison is broken?

**Comment by Slava** [comment]
@k5e it is hard to tell from your description, but I think the cause root is not in the versions comparison.

Your first project is pinned to the old release track that we used to release beta Windows versions. It will only see updates for that release track. To switch it to the official track, you would need to do `meteor update --version METEOR@1.2.1` manually.

For the new projects the official release track is chosen by default.

**Comment by k5e** [comment]
Thanks @Slava for the fast reply. 

I have tried several manipulations of ```.meteor\release``` before, including ```none```.

Well, this did the trick:
```
C:\projects\mymeteorapp>meteor update --release METEOR@1.2.1
[lots of stuff]
mymeteorapp: updated to Meteor 1.2.1.
[little more stuff]
```
... after I have removed package ```bootstrap-3``` and added ```mrt:bootstrap-3``` instead. Alas, it had to hint me with some error messages.

And ```meteor update``` seems to be content with it now and does not try to downgrade any more.

Thanks again for the help.
Christian
