### ISSUE TITLE
Make AccountsClient available on server

### ISSUE THREAD

**Issue by citizenkevin** [meteor/meteor#5696]
**_1 Upvote**_ ""Note that AccountsClient is currently available only on the client, due to its use of browser APIs such as window.localStorage. In principle, though, it might make sense to establish a client connection from one server to another remote accounts server. Please let us know if you find yourself needing this server-to-server functionality.""""

This sounds great to me. (Couldn't find a pre-existing feature request for it.) 
I'm in the process of developing an enterprise application with a service-oriented architecture -- where each service (hopefully) is a meteor app that could be hosted or installed on-site. And it would be valuable if I could use the same accounts interface for letting these services communicate with other servers.

**Comment by teknologist** [comment]
+1

**Comment by stubailo** [comment]
Thanks for the feature request! It would totally make sense to be able to log into a Meteor server from another server. Probably the best way to achieve this would be to factor out the part of accounts that stores the token in localstorage. I'd look at a pull request for this.

However, you could also implement a service architecture by sharing a secret API key, rather than by using a login system. So I don't know if this feature is a blocker for that type of thing.

**Comment by citizenkevin** [comment]
Thanks @stubailo. 
I don't claim to be in the know when it comes to this problem space and don't know the current practices that well yet, but it seems a secret api key wouldn't be enough to take actions on a remote server on behalf of a specific user (which is what I'm interested in). 
Here's what I'm currently thinking so someone can better clue me in/give me ideas:

Right now the method to authenticate a user on an additional/non-primary service (Server B)  seems to be:
1) pass the login token stored on Browser-Client A (and originating from Server A authentication) to Server B via a method
2) Server B then asks Server A for the userId associated with that token (by looking up the hashed version)
3) Once, and if, a userId is returned from Server A, this.setUserId is called on Server B so that subscriptions and methods on server B function as if the user is authenticated on that server as well

The shortcomings of this that I can see:
1) this is only relevant to an active browser connection, once the connection is gone, server B can no longer act on behalf of the user (which may be desirable) 
2) if I call Meteor.logout(), I'm still "logged in" on Server B until this.setUserId is called again, which with multiple services is something I'd rather have taken care of 

I think what I'd like to see is a consistent interface for:
1) for authenticating a user on any number of services (Meteor.login([connectionsArray]) perhaps?)
2) Meteor.logout() then logs out all those connections
3) an option for a persistent remote connection (presumably using the approach sashko recommended).

It seems this is all doable now without changes, but it feels like a workaround for a service-oriented architecture, which doesn't make sense to me given I think thats what meteor apps are really good for (having a web of DDP-powered services.)

Anyone got some feedback for me? Does this make sense? 

(this package seems to be doing something similar on the server, haven't delved into implementation details/limitations yet: https://atmospherejs.com/ongoworks/ddp-login)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20AccountsClient%20available%20on%20server&body=Migrated%20from:%20meteor/meteor%235696) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
