### ISSUE TITLE
future.js and tasklisk.exe problem when start meteor in windows 10

### ISSUE THREAD

**Issue by isdzulqor** [meteor/meteor#5700]
Hey Guys,
I have a problem when I want to start meteor to make server, you can see my error pic below, i've tried many ways from google, but nothing works. 
Please anyone can help me to figure it out,
Thank you
![capture](https://cloud.githubusercontent.com/assets/12388558/11355865/f96aed5e-928a-11e5-87c3-f48e7b620ca3.PNG)

**Comment by isdzulqor** [comment]
[SOLVED]
I add C:\Windows\System32 to my PATH of System variables in environment variable,
Thank you Meteor, You are amazing

**Comment by stubailo** [comment]
Great! Glad you got it solved.
