### ISSUE TITLE
[URGENT] net::ERR_CONNECTION_REFUSED in browser console

### ISSUE THREAD

**Issue by anshul-budhiraja** [meteor/meteor#5701]
I deployed my meteor production application. Its working randomly. In browser console, the error is http://myappurl/sockjs/info?cb=bz_q_zi_5q net::ERR_CONNECTION_REFUSED

Can anybody help me to understand what the root cause can be? What will be the solution for it.

**Comment by rozzzly** [comment]
`ERR_CONNECTION_REFUSED` means the dns is resolving to a valid host, but when try to connect it's like "nah". Usually means the server process is down. Although, there are 10,000 other things that could cause this to show up too _(I know. helpful right :stuck_out_tongue:)_ 

**First step restart node process.** Then dig around for error messages / stacktraces that the **server** give you internally (ie: not from my visiting your site.com from google and seeing the error msg in the console.

And I'm sure one of the offical contributers will post here soon telling you this is a question best posted on StackOverflow, Meteor Forums, the [gitter room](https://gitter.im/meteor/meteor), etc.

**Comment by stubailo** [comment]
Yeah, this could be any number of things, especially related to your hosting environment. We won't be able to do anything at all here without a reproduction.
