### ISSUE TITLE
Manifest contains invalid URLs for non-standard architectures

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5706]
If I have a non-standard architecture `web.foobar`, then its manifest is served under `/__foobar/manifest.json`, which is great, but the manifest itself has URLs which are not rooted under that path:

```
{
  path: "packages/meteor.js",
  where: "client",
  type: "js",
  cacheable: true,
  url: "/packages/meteor.js?2a844cb96311115f63cb890c87c79881233bdabc",
  sourceMap: "packages/meteor.js.map",
  sourceMapUrl: "/packages/2a844cb96311115f63cb890c87c79881233bdabc.map",
  size: 712,
  hash: "2a844cb96311115f63cb890c87c79881233bdabc"
},
```

See `url` and `sourceMapUrl`. They should be `/__foobar/packages/meteor.js?2a844cb96311115f63cb890c87c79881233bdabc` and `/__foobar/packages/2a844cb96311115f63cb890c87c79881233bdabc.map`, respectively.

**Comment by stubailo** [comment]
You're right - it seems like if we have this code, it should at least be consistent!

**Comment by hwillson** [comment]
PR #5714 was submitted to help address this issue, but it was closed and not merged for [this reason](https://github.com/meteor/meteor/pull/5714#issuecomment-218319547):

> it's not a trivial change we're not going to take this PR until there's clear demand for multiple architectures from others in the community. It's not on our roadmap to add more architectures at this stage.

For this reason, I'll close this issue. If someone wants to revisit new architecture support in the future, they'll be able to track down this history in the closed issues/PR's. Thanks for submitting this originally (and your work on the PR)!

**Comment by mitar** [comment]
I mean, there is quite heavy support for #6222 (16 upvotes), and this is a dependency for good support for #6222. So I think this should be left opened and fixed together with #6222, or both should be closed.

**Comment by hwillson** [comment]
Sounds good @mitar - since #6222 is so popular, I think you're right; let's keep this one open as well. Thanks for the feedback!

**Comment by mitar** [comment]
Also, #6201 was not merged only because I didn't have time to get back to it. But it is also a dependency for #6222. Could you maybe have time to do an updated pull request and get that merged in?

**Comment by hwillson** [comment]
Sure thing, I'll take a look at #6201.

**Comment by hwillson** [comment]
@mitar - I've resurrected your #6201 as #8293, so hopefully that helps!

**Comment by NitroBAY** [comment]
I'm glad that Meteor's team seems to be interested in #6222 which is very very important for me and a lot of other persons (for instance I have about 50 stars on my SW created for Meteor but I cannot make a package while you don't merge #6222 or implement another way to make  Meteor's tool compatible with SW in another way)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Manifest%20contains%20invalid%20URLs%20for%20non-standard%20architectures&body=Migrated%20from:%20meteor/meteor%235706) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
