### ISSUE TITLE
running meteor tutorial on clean install get spawn enomem error

### ISSUE THREAD

**Issue by dredgerman** [meteor/meteor#5718]
Hi,

Did clean install of centos 7 minimal, virtual min and only changes to configuration of server are editing iptables and setting up firewall wanted fresh start to install meteor, running 2 cores, 2gb ram, 2gb swap and 50gb hdd.

installed perfect and as sudo, who has root privileges,

created new myapp as per tutorial for beginners,

when I run myapp it crashes in local folder and produces enomem error not got first clue about what could be wrong followed instructions to letter and this is supposed to be simple to use!

thanks for any help given....path to myapp folder is /home/tomsudo/myapp

[tomsudo@server myapp]$ ls -alsh
 total 24K
 4.0K drwxr-xr-x 3 tomsudo tomsudo 4.0K Nov 25 09:10 .
 4.0K drwx------ 6 tomsudo tomsudo 4.0K Nov 25 09:10 ..
 4.0K drwxr-xr-x 3 tomsudo tomsudo 4.0K Nov 25 09:10 .meteor
 4.0K -rw-rw-r-- 1 tomsudo tomsudo 31 Nov 25 09:10 myapp.css
 4.0K -rw-rw-r-- 1 tomsudo tomsudo 218 Nov 25 09:10 myapp.html
 4.0K -rw-rw-r-- 1 tomsudo tomsudo 478 Nov 25 09:10 myapp.js
 [tomsudo@server myapp]$ meteor
 [[[[[ ~/myapp ]]]]]

=> Started proxy.
 => Started MongoDB.

/home/tomsudo/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
 throw(ex);
 ^
 Error: spawn ENOMEM
 at errnoException (child_process.js:1011:11)
 at ChildProcess.spawn (child_process.js:958:11)
 at Object.exports.spawn (child_process.js:746:9)
 at [object Object]..extend._spawn (/tools/runners/run-app.js:255:31)
 at [object Object]..extend.start (/tools/runners/run-app.js:85:22)
 at [object Object]..extend._runOnce (/tools/runners/run-app.js:716:16)
 at [object Object]..extend._fiber (/tools/runners/run-app.js:858:28)
 at /tools/runners/run-app.js:396:12
 [tomsudo@server myapp]$

No idea what is causing this?  This has been an issue in meteor since 2013 if you research web, so why hasn't this been fixed?  This is supposed to be easy way to get started I have a meteor course to do and can't even run a basic web app!!!  What are my next steps?

**Comment by tmeasday** [comment]
Hi @dredgerman,

It sounds like this is a problem with no swap space enabled on your machine: http://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn

PS "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
