### ISSUE TITLE
Must pass options.rootUrl or set ROOT_URL in the server environment

### ISSUE THREAD

**Issue by Silence-wzy** [meteor/meteor#5720]
![qq 20151127143858](https://cloud.githubusercontent.com/assets/11975123/11435354/adfb8842-9514-11e5-8025-5683253f708b.jpg)

Hello, I'm trying to deploy my app and i cannot seem to get it working, really not sure on where my error is!

Here are the logs

![image](https://cloud.githubusercontent.com/assets/11975123/11435433/880f35b0-9515-11e5-8ea6-1cb59e5ef7d1.png)

**Comment by joaopiopedreira** [comment]
Use mup (https://github.com/arunoda/meteor-up) my friend. All worries will be gone :)

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by Silence-wzy** [comment]
I've ever used mupx,but once application changed,i have to deploy my app again,and it will create a new docker container.(what i want to retain is not only the database)

so i have to deploy my app without mup or mupx

**Comment by martijnwalraven** [comment]
So have you tried setting the `ROOT_URL` environment variable on the server?

**Comment by stubailo** [comment]
Yeah I think this looks like a "how do I do this" question, which belongs on the forum in the "help" category: https://forums.meteor.com/
