### ISSUE TITLE
insert _id as number

### ISSUE THREAD

**Issue by bipin244** [meteor/meteor#5722]
I want add _id as a number in mongodb collection from my meteor application can it is possible?if yes than how?

Thanks in advance

**Comment by laosb** [comment]
I guess you can directly have `_id` in the object to insert. If you passed a `_id` to the object, Meteor will use it.

BTW, Issues Tracker is not a place for questions like this. http://forums.meteor.com is a better place for this.

**Comment by zol** [comment]
@bipin244 as @laosb said, please redirect your question to our forums.
