### ISSUE TITLE
DDPRateLimiter mistake in docs

### ISSUE THREAD

**Issue by minden** [meteor/meteor#5728]
The DDPRateLimiter example in the [Meteor docs](http://docs.meteor.com/#/full/ddpratelimiter)
```javascript
var loginRule = {
  userId: function (userId) {
    return Meteor.users.findOne(userId).type !== 'Admin';
  },
  type: 'method',
  method: 'login'
}
```

does not work for me. But if I change `method` to `name` it works. 

Is this a bug in the documentation?

**Comment by lieuwex** [comment]
Duplicate of #5505

**Comment by minden** [comment]
@lleuwex thanks :)

**Comment by lieuwex** [comment]
@minden you're welcome :)

**Comment by zol** [comment]
Thanks @lieuwex
