### ISSUE TITLE
Unexpected mongo exit code 100

### ISSUE THREAD

**Issue by Lexalexeev** [meteor/meteor#5731]
>Unexpected mongo exit code 100
MongoDB had an unspecified uncaught exception. 
This can be caused by MongoDB being unable to write to a local database. 
Check that you have permissions to write to .meteor/local. MongoDB does 
not support filesystems like NFS that do not allow file locking.

Windows 8.1
File System NTFS
Enough memory

I tried to delete mongo.lock, to 
>meteor reset

but it doesn't work.
Any advices?

**Comment by zol** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
