### ISSUE TITLE
`meteor deploy` should allow non-interactive login

### ISSUE THREAD

**Issue by andrewtamura** [meteor/meteor#5732]
**_1 Upvote**_ `meteor deploy` current prompts for email and password. It would be super friendly for CI servers to allow a non-interactive way to deploy. Maybe something like `meteor deploy -u USERNAME -p PASSWORD` or event accepting a `-t TOKEN` option. We're currently using the `.meteorsession` workaround provided by Codeship https://github.com/codeship/scripts/blob/master/deployments/meteor.sh, but it would be easier to maintain if would could pass authentication credentials into the command line.

**Comment by tmeasday** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

In the past, I've used something along the lines of `printf "$user\n$password\n" | meteor login` successfully.

**Comment by sathishc** [comment]
+1

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5732#issuecomment-161121504, `printf` will work for this purpose. Here's a quick CircleCI example:

```
...
deployment:
  production:
    branch: "master"
    commands:
      - printf "SomeUsername\nSomePassword\n" | meteor deploy somehost.com
...
```

That being said this is probably much less of an issue now that `*.meteor.com` hosting has been discontinued. Closing for now - thanks for posting this originally!
