### ISSUE TITLE
"Did you mean?" style messages when a meteor command is not found / typo'd

### ISSUE THREAD

**Issue by adnissen** [meteor/meteor#5733]
I don't know if there are statistics on whether or not "Did you mean?" style messages make for a good user experience, but I certainly don't think it can hurt. We can simply use the Levenshtein Distance between the input and each existing command to see if they reasonably typo'd. I'd be more than happy to implement this if people are interested.

**Comment by stubailo** [comment]
If there is a concise way to do this, preferably using a standard NPM package that does it for us, I'd be on board. But if it adds significant complexity to the code that we have to worry about then I'd say it's not worth it.

**Comment by sorenpeterson** [comment]
It looks like there is levenshtein package: https://www.npmjs.com/package/levenshtein. I would also be interested in implementing this, just for fun.

**Comment by hwillson** [comment]
Due to a lack of interest/support on this issue in over a year, I'll close it off. Thanks for the original suggestion!
