### ISSUE TITLE
Error in deploying Meteor App in Windows 

### ISSUE THREAD

**Issue by ajalacomfort** [meteor/meteor#5737]
![error](https://cloud.githubusercontent.com/assets/15694744/11517891/18539d58-988d-11e5-85d7-ea02abfeed9d.png)

I tried deploy but I got this error...How can I solve this?

**Comment by sorenpeterson** [comment]
It looks like the node package `pinkie-promise` is not installed. Try running `npm install -g pinkie-promise`. Also, this is not really the place to ask for help. You should post your question here: stackoverflow.com

**Comment by ajalacomfort** [comment]
Thank you!

**Comment by stubailo** [comment]
Great, let me know if it turns out to be a Meteor bug.
