### ISSUE TITLE
DDPRateLimiter for function calls

### ISSUE THREAD

**Issue by marceloschmidt** [meteor/meteor#5738]
Are there plans for supporting DDPRateLimiter on function calls too? 
The problem with running with methods only (or subscription) is that you usually do some validation on your method and if the validation fails, maybe you want your users to try again with different params. Say, for example, that I have a method that will do some heavy processing on the server. I don't think my users should be calling that method more than once every minute. If validation fails, the heavy processing will not happen, so it would be ok to call it again.

**Comment by stubailo** [comment]
You're in luck! DDPRateLimiter is just a conveniently named instance of `RateLimiter`, which is a separate package that isn't quite documented. See the package here: https://github.com/meteor/meteor/tree/devel/packages/rate-limit

You can see how DDPRateLimiter uses it here: https://github.com/meteor/meteor/blob/devel/packages/ddp-rate-limiter/ddp-rate-limiter.js

Basically, you can create your own RateLimiter instance and then rate limit any operation you want!

Let me know if this doesn't answer your question.

**Comment by marceloschmidt** [comment]
Yes, you rock! Thank you very much.
