### ISSUE TITLE
Android build not loads some .js files

### ISSUE THREAD

**Issue by dikmax** [meteor/meteor#5739]
Some requests to http://meteor.local/ return root index.html instead of requested file.
It appears as messages like this in inspector:

```
template.navigation_drawer.js?00aa014ed1ffcde96e5e2d694064cb37d59d4586:1 Uncaught SyntaxError: Unexpected token <
```

and therefore whole application fails to load.

I use Crosswalk WebView and Android 6 emulator.

Other builds (ios, browser) working as intended.

**Comment by sorenpeterson** [comment]
This is related to issue #4722. My best guess is that something is going wrong with build process and is causing files to be cached automatically.

**Comment by dikmax** [comment]
I found out that this related with Application Cache. It's getting too big, so some resources doesn't fit into it.

If I run application in production mode it works.

**Comment by martijnwalraven** [comment]
What do you mean by Application Cache in this case? Why do you think this is the cause of your issue?

Interested in figuring out what is going on, because I'm not aware of any explicit size limit for hot code push (except the amount of free storage on the device of course).

**Comment by dikmax** [comment]
It's just my assumption. But anyway it production mode application becomes smaller and problem disappears. This could be unrelated.

**Comment by dikmax** [comment]
Ok, Android build doesn't likes folders starting with underscores, don't know why. 
Renaming folder `_shared` to `shared` fixed everything.

I'm closing thins issue.
