### ISSUE TITLE
If facebook email not provided user can never login

### ISSUE THREAD

**Issue by greggman** [meteor/meteor#5740]
I'm probably doing something dumb but...

Using useraccounts:unstyled but assuming this is actually a core meteor issue. 

User chooses to create an account using facebook. They are asked for an email/password by facebook

![screen shot 2015-12-03 at 3 12 45 am](https://cloud.githubusercontent.com/assets/234804/11539785/558d1b7e-996c-11e5-82ef-d17b1da8417f.png)

They are then told what info will be shared

![screen shot 2015-12-03 at 3 12 50 am](https://cloud.githubusercontent.com/assets/234804/11539796/6335454e-996c-11e5-8472-9130fb56f95a.png)

They click "Edit the info you provide" and uncheck email

![screen shot 2015-12-03 at 3 12 56 am](https://cloud.githubusercontent.com/assets/234804/11539809/7aaf2b4a-996c-11e5-8134-8e17dfa3e697.png)

At this point accounts bombs out with "Email already exists".  I'm assuming (though I haven't checked, that it's checking for the empty string). 

There is no recovery after that AFAICT. Even if the user clears all cookies the next time they try to log in Facebook doesn't ask them what info they want to share. It's already saved their preferences so they just keep getting the same error, "Email already exists".

Note: I don't need their email for my app so I'm happy not to receive it and given that facebook allows people not to share their email this seems like an issue that needs to be solved one way or another, not requiring an email address.

Any ideas how to go about solving is issue?

**Comment by sorenpeterson** [comment]
Can you link the code you are working on?

**Comment by greggman** [comment]
Sorry, I tried the simple-todos tutorial and it works just fine without fb email. I'm using the useraccounts package in my own app so the issue is in there.

**Comment by stubailo** [comment]
@greggman great, let me know if it turns out to be something in Meteor core.
