### ISSUE TITLE
Update to wiki

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#5741]
This page needs to be updated:
https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store

`unaligned.apk` should be `release-unsigned.apk`. This appears twice on the page.
`$ANDROID_HOME/build-tools/23.0.0/zipalign` should be `$ANDROID_HOME/build-tools/23.0.1/zipalign`.

In case anyone else runs into similar issues with building an app for Android based off of the old wiki page.

**Comment by sorenpeterson** [comment]
Excuse my inability to assess the situation, but why does this change need to be made?

**Comment by elie222** [comment]
Because this is how you would upload to the play store today...

Just mentioning it because a friend was having trouble uploading and this
was the fix.

**Comment by abernix** [comment]
Thanks so much for pointing this out.  This is new covered thoroughly in [the Meteor Guide](http://guide.meteor.com/mobile.html#submitting-android), including the correct `.apk` filename. :smile:
