### ISSUE TITLE
Nodejs - download apk file as zip by IE

### ISSUE THREAD

**Issue by zxh930508** [meteor/meteor#5742]
hello guys, we have a website and can download apk file. it's working perfectly in Chrome, but it's converted to zip file by IE11. anybody can help? thanks.

**Comment by sorenpeterson** [comment]
Maybe I'm not understanding your question correctly, but it doesn't look this is actually an issue or bug with Meteor. Instead, it appears as if your issue is with IE. Try posting your question here: http://stackoverflow.com/

**Comment by stubailo** [comment]
Yes, I don't think this is a Meteor-related issue. Thanks @sorenpeterson.
