### ISSUE TITLE
setTargetPathFromRelPath does not match setUrlFromRelPath

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5744]
In `setTargetPathFromRelPath` path is prefixed with `app` if it is not from `packages` or `assets`, but in `setUrlFromRelPath` this does not happen. As a consequence, you get a mismatch between the relative path and URL:

```
{
path: "foobar/data.bin",
where: "client",
type: "asset",
cacheable: true,
url: "/__foobar/data.bin",
size: 294,
hash: "ed706bf0e2b97da5732dc265ebab5dc8cbe789b7"
}
```

I think that or `path` should be `data.bin`, or URL should be `/_foobar/app/data.bin`.

**Comment by timbotnik** [comment]
Is this a bug or enhancement request?  Would be great to have a specific reproduction here as well.  Thanks!!

**Comment by mitar** [comment]
This is a bug request, but it is hard to make a reproduction because it requires a custom target to discover that.
