### ISSUE TITLE
Cordova: Change --mobile-server needs reinstall of app

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#5746]
for my mobile app when after

    meteor run android-device

I call

    meteor run android-device --mobile-server http://staging.system

I need to uninstall the app on the device first for the change to take place.

**Comment by sorenpeterson** [comment]
It sounds like your issues might be related to these two: #4722 and #5297. You should check these out.

**Comment by martijnwalraven** [comment]
This is mostly likely a result of https://github.com/meteor/meteor/issues/5639 and will be fixed with the rewritten plugin coming in Meteor 1.3.

**Comment by martijnwalraven** [comment]
This should have been fixed in Meteor 1.3. A new beta is now available: https://github.com/meteor/meteor/issues/6266.

**Comment by abcd-ca** [comment]
@martijnwalraven Thanks, I love this fix (using release 1.3 version and working on Android, woo!)
