### ISSUE TITLE
CordovaBuilder - Allow nested properties

### ISSUE THREAD

**Issue by cunneen** [meteor/meteor#5756]
cordova's config.xml allows nested elements, such as those required for the [universal links](https://www.npmjs.com/package/cordova-universal-links-plugin) cordova plugin:

``` xml
<universal-links>
    <host name="example.com">
        <path url="/some/path/*" />
    </host>
</universal-links>
```

CordovaBuilder needs to allow a tree structure like this, rather than just simple key/value pairs. Otherwise some cordova features can't be used in a meteor app.

Can we have a "custom" key in mobile-config.js that takes a simple json object, so that the above could be specified like:

``` js
App.custom({
  universal-links: {
    host: {
      _attributes: {
        name: "example.com"
      },
      path: {
        _attributes: {
          url: "/some/path/*"
        }
      }
    }
  }
});
```

**Comment by adrianolsk** [comment]
Hello @cunneen, have you been able to use this plugin in your app?
I am trying to use it creating the file config.xml in the folder
```js 
cordova-build-override/config.xml
```
with the  universal link config, the override is working, but when I try to run on device I cant get the app to install,
the build fail when downloading the universal links plugin
```
Can't find module mkpath, running npm install[=========================  ] 92% 2.9s
Can't find module xml2js, running npm install[=========================  ] 92% 3.0s
=> Errors executing Cordova commands:                                              
                                                                                   
   While preparing Cordova project for platform Android:                           
   Error: Cannot find module 'xml2js'                                              
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at
   /home/adriano/Documentos/Projetos/beras/.meteor/local/cordova-build/plugins/cordova-universal-links-plugin/hooks/lib/configXmlParser.js:8:14
```

**Comment by cunneen** [comment]
For reference, I do have the plugin working with my meteor app but the solution is pretty awful.

1 -- I created the following hook script, in ```.meteor/local/cordova-build/hooks/before_prepare``` (you'll have to create the folder:

add_deep_link_config.js

```js
#!/usr/bin/env node

// this plugin appends deep_link_config.xml to our config.xml
//
console.log('appending deep_link_config.xml to config.xml');

var fs = require('fs');
var path = require('path');
var xml2js = require('xml2js');
var cordova_util = require('cordova-lib/src/cordova/util');
var projectRoot = cordova_util.isCordova(process.cwd());
var projectXml = cordova_util.projectConfig(projectRoot);
var projectPlatforms = cordova_util.listPlatforms(projectRoot);


var parser = new xml2js.Parser();
var builder = new xml2js.Builder();

// simple fn to reduce repeated boilerplate
function logAndRethrowError(err) {
  if (err) {
    console.log("ERROR:");
    console.error(err);
    throw err;
  }
}

if (projectRoot) {
  var ourconfigfile = path.join(projectRoot, "deep_link_config.xml");
  var deep_link_config_xml = fs.readFileSync(ourconfigfile, 'utf8');
  var deepLinkConfigObject; // we'll put the JS object in here

  // parse our deep link config xml file
  parser.parseString(deep_link_config_xml, function (err, result) {
    logAndRethrowError(err);
    deepLinkConfigObject = result;
    // OK so now result is a javascript object.
  });


  if (fs.existsSync(projectXml)) {
    fs.readFile(projectXml, 'utf8', function (err, configXMLString) {
      // now configXMLString is the contents of our config.xml file
      logAndRethrowError(err);
      parser.parseString(configXMLString, function (err, configXMLJSObj) {
        var xml; // we'll put the resulting config.xml in here.
        logAndRethrowError(err);
        // OK so now configXMLJSObj is a javascript object representing our config xml.
        // get rid of any old universal links
        delete configXMLJSObj.widget['universal-links'];
        // and now we add our "new" universal links back in.
        configXMLJSObj.widget['universal-links'] = deepLinkConfigObject['universal-links'];
        configXMLJSObj.widget['plugins'] = {};
        var builder = new xml2js.Builder();
        xml = builder.buildObject(configXMLJSObj);

        // now write it back again
        fs.writeFileSync(projectXml, xml);
        console.log("wrote " + projectXml);
      });
    });
  } else {
    console.log("missing: " + projectXml);
  }
}
```

2 -- In ```.meteor/local/cordova-build```, add a file called deep_link_config.xml containing the xml that you ultimately want added to your cordova config.xml

deep_link_config.xml:

```xml
<universal-links>
    <host name="app.example.com" scheme="https" >
        <path url="/Redeem/*" event="redeemLink" />
        <path url="/#/verify-email/*" event="verifyEmailLink" />
        <path url="/#/verify-sms/*" event="verifySMSLink" />
    </host>
</universal-links>
```

3 -- Exclude those files from your top-level .gitignore by editing .meteor/.gitignore and adding the following lines:

```
!local/
local/*
!local/cordova-build/
local/cordova-build/*
!local/cordova-build/hooks/
!local/cordova-build/ul_web_hooks/
```

4 -- Install xml2js, mkpath and cordova-lib (possibly the other dependencies below as well) using npm. E.g. in the folder above my (top-level) meteor project folder, I have the following package.json:

```json
{
  "name": "my-meteor-project",
  "version": "1.0.0",
  "description": "My App - Node dependencies",
  "main": "run_meteor.sh",
  "dependencies": {
    "read-package-json": "^2.0.2",
    "mkpath": "^1.0.0",
    "cordova-lib": "^5.4.1",
    "cordova-common": "^1.0.0",
    "rimraf": "^2.4.4",
    "xml2js": "^0.4.15"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://me@bitbucket.org/myteam/my-git-repository.git"
  },
  "author": "",
  "license": "ISC"
}
```

Then I can just go to that folder and do an "npm install". They are then available to all my hook scripts. Some of them are needed by the universal-links plugin.

/cc @adrianolsk

**Comment by adrianolsk** [comment]
Hey @cunneen.

Sorry I actually deleted my last comment because after reinstalled the plugin it worked using the override folder.

I tried to use the hook folder but the scripts in there are not being executed here. "Meteor 1.2.1".
I am using the simple solution of the cordova-build-override folder. Just copied the content that meteor generate from mobile-config.js in config.xml and add universal links config part.

But I was not able to get this part to work
```
document.addEventListener('ul_didLaunchAppFromLink', function(){}, false);
```
So I had to fork the plugin and add a hack to get the universal link parameters to work with my app.

But I agree with you Allow nested properties on mobile-config.js would be great or add a xml file that would be appended to config.xml and not override it

**Comment by cunneen** [comment]
What was your hack Adriano?

**Comment by adrianolsk** [comment]
I edited this file
```
https://github.com/adrianolsk/cordova-universal-links-plugin/blob/master/www/universal_links.js
```

I change the function bellow adding the "window.some_variable = msg;" so I can access this when meteor load without the need to listen to events. It return a object with, host, path, etc.

```
function nativeCallback(msg) {
 //Add the line below to be able to get data using Meteor JS
  window.ul_data = msg.data;
  var ulEvent = new CustomEvent(msg.event, {
    'detail': msg.data
  });

  document.dispatchEvent(ulEvent);
}
```

I add the plugin to my app direct on /.meteor/cordova-plugins this way
```
cordova-universal-links-plugin@https://github.com/adrianolsk/cordova-universal-links-plugin.git#e96ea016624d2a37b251a6b3c05e358dc5d75447
```


and I did some trick to style the white screen when opening the app using universal link as well, not sure if there is a better way, but I override the file under: ```cordova-build-override/www/index.html ``` with

```
<head>
    <style type="text/css">
        body {
            background-color: #272727 !important;
           /* 
            also add image as base64 do simulate a splash screen.
            background-image: url('data:image/png;base64,iVBORw0......
            background-size: 100px;
            background-repeat: no-repeat;
            background-position: center 225px;
        */
        }
    </style>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="meteor_cordova_loader.js"></script>
</head>
<body>
</body>
```
I added the same style to the myproject/index.html to avoid a blink of white

hope some of this help you @cunneen

**Comment by cunneen** [comment]
Thanks!

**Comment by grsabreu** [comment]
Yo guys, just did a PR for that feature
I also needed

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=CordovaBuilder%20-%20Allow%20nested%20properties&body=Migrated%20from:%20meteor/meteor%235756) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
