### ISSUE TITLE
Allow overriding packages

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5757]
Currently, if I create my version of the package, an extended version or fork, I cannot configure Meteor to use it in all cases (as a dependency) instead of the other package if the package is a dependency in packages I do not control.

The only solution is to add a dummy package to `packages`. For example `packages/kadira:flow-router/package.js`:

```
Package.describe({
  name: 'kadira:flow-router',
  version: '2.10.0'
});

Package.onUse(function(api) {
  api.imply('peerlibrary:flow-router@2.10.0_2');
});
```

**Comment by tmeasday** [comment]
That's a neat workaround though :)

I think an `api.replaces()` would be super helpful.

**Comment by rozzzly** [comment]
Nice idea @tmeasday! ....Devil's advocate here, _what about multiple packages that call `api.replaces()`_

**Comment by mitar** [comment]
They get processed in the order you have them listed in the `.meteor/packages` or in the package dependencies.

**Comment by rozzzly** [comment]
Orly now? I never knew the `.meteor/packages` bit!

**Comment by mitar** [comment]
Aaa, this would be so useful now. I just managed to create a new implementation of tracker package and it would be so great if I could say that my whole app should be using this custom package instead of core tracker package. I can add it as git submodule to `packages` inside my app, but this is not the best way to explain to other users how to install my package. It would be much better if they could do `meteor add mitar:tracker` and `mitar:tracker` package would say that it is replacing core `tracker`. Or, if users could do `meteor replace tracker mitar:tracker` or something.

**Comment by laosb** [comment]
I'm much more comfortable in the `package would say that it is replacing core tracker` way. It keeps meteor's magic way to do things, and it's easy to deal with if some package depends on an replacement package.

**Comment by Akryum** [comment]
We really need this to make take the Vue+Meteor story a giant leap forward! 😄

**Comment by laosb** [comment]
Several things to decide:

1. **Let users replace manually with `meteor replace`, or packages declare replacements.**
  IMO `meteor replace` way requires users to do it manually. For package authors who want to depend his packages on a specific replacement (like if some Vue integrations needs `mitar:tracker`), things will be harder as you need to remind users to do that replacement.
2. Can replacement packages be depended on?
  IMO we should forbid replacement depending, At least we should warn. Else we may run into "have two different implementation in an app" situation.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20overriding%20packages&body=Migrated%20from:%20meteor/meteor%235757) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
