### ISSUE TITLE
es5-shim breaks app when cookies are not allowed

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#5759]
platform: browser
until today reproduced in firefox (42.0), ff dev (44.0a2 (2015-12-04)) , chromium (48.0.2528.0)

to reproduce:
1) init default counter app
3) disable cookies in browser
4) open up the app in browser (with an open console)
2) remove ecmascript and es5-shim packages
5) again take a look into the console

chromium: ``Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.        es5-shim.js:856``

firefox dev: ``SecurityError: The operation is insecure.       es5-shim.js:956:0``

NOTE: please dont get confused about the different line number. Both point to the condition within the for loop in ``hasAutomationEqualityBug``

recommendation: after a quick research the ``es5-shim`` authors seems to had fixed this issue already, see https://github.com/es-shims/es5-shim/issues/327. So I think meteor just needs an update of the es5-shim package npm dependency

**Comment by benjamn** [comment]
Thanks for the thorough bug report and suggested fix. I'll upgrade `es5-shim` asap.

**Comment by Slava** [comment]
Interesting. Doesn't Safari throw on accessing LS in Incognito mode too? Curious if that was broken too.
