### ISSUE TITLE
Store expiresAt property for all OAuth providers, other than Google and Facebook

### ISSUE THREAD

**Issue by avital** [meteor/meteor#576]
This is supported for Google and Facebook:
- Google: 79405a495d4acaffc56042f8f7e15b5b34b6171f and 1e09d4ee8d29b2f2dc53a29c723bbc94dab3038b.
- Facebook: a404490ceb3d1a3db5f4dce7c8f1ae1d918cec95 and 06f1308b4be2fbceb3b776a44be186cb6fd5141f

**Comment by hwillson** [comment]
Since this issue was created, `expiresAt` has also been added to the `meteor-developer-oauth` and `weibo-oauth` packages. Since there hasn't been interest/activity on this issue in quite some time, I'll close it off. Thanks!
