### ISSUE TITLE
Package version installed mismatched with release tag of the package

### ISSUE THREAD

**Issue by ntkog** [meteor/meteor#5760]
Really weird behaviour. Steps to reproduce it : 

I'm using 
```
meteor --version
Meteor 1.2.1
```

```bash
meteor create testApp
cd testApp
meteor add tomi:upload-jquery
```

When I check the installed version of the package , it shows an **inexistent** version:

```
meteor list

autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript            0.1.6  Compiler plugin that supports ES2015+ in all .js files
es5-shim              4.1.14  Shims and polyfills to improve ECMAScript 5 support
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.3  Adaptor for using MongoDB and Minimongo over DDP
session               1.1.1  Session variable
standard-minifiers    1.0.2  Standard minifiers used with Meteor apps by default.
tomi:upload-jquery    2.2.1  Client template for uploads using "jquery-file-upload" from blueimp
tracker               1.0.9  Dependency tracker to allow reactive callbacks
```
**tomi:upload-jquery    2.2.1** --> Wrong Version!!

[tomi:upload-jquery repo](https://github.com/tomitrescak/meteor-tomi-upload-jquery)

Also if you try to get the badge from **icon.meteor.com**

[![Meteor Icon](http://icon.meteor.com/package/tomi:upload-jquery)]

Shows a wrong version.

If we check [package.js](https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/package.js) the version were properly set (**2.2.0** , matching with the tag of the release)

If we look for the [releases](https://github.com/tomitrescak/meteor-tomi-upload-jquery/releases) of the **tomi:upload-jquery** package , the latest version is **2.2.0**

Let's run this simple example , and in other terminal look for what is really building ( Just FYI )

```
cat .meteor/local/build/programs/web.browser/program.json
```
```js
...
    {
      "path": "packages/tomi_upload-jquery.js",
      "where": "client",
      "type": "js",
      "cacheable": true,
      "url": "/packages/tomi_upload-jquery.js?a711e4b531250b61efcb6f719ff58283a163ee06",
      "sourceMap": "packages/tomi_upload-jquery.js.map",
      "sourceMapUrl": "/packages/a711e4b531250b61efcb6f719ff58283a163ee06.map",
      "size": 396547,
      "hash": "a711e4b531250b61efcb6f719ff58283a163ee06"
    },
...
```

Could you give me some clue about what is happening?

**Comment by stubailo** [comment]
I think both of the data sources you quoted are actually wrong.

The badge from icon.meteor.com is incorrect, and it appears the package maintainer forgot to push a github tag for this release.

You can see that a version 2.2.1 exists by looking at the package page on atmosphere: https://atmospherejs.com/tomi/upload-jquery

You can also query the package server directly by typing `meteor show tomi:upload-jquery` in your terminal.

I'd suggest:

1. Reaching out to the package author to remind them to push a new release tag to GitHub
2. Reaching out to the maintainers of icon.meteor.com to notify them that the badge is not correct

I don't think there's anything we can do about either of these things on our end.
