### ISSUE TITLE
Tar problem when installing Meteor

### ISSUE THREAD

**Issue by MaxenceAdnot** [meteor/meteor#5762]
I tried to deploy a meteor app using a Docker container but it failed due to tar errors while installing Meteor:

```
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/transformers/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/transformers/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/transformers: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/defs/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/defs/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/defs: Directory renamed before its status could be extracted
tar: .meteor/packages/coffeescript/.1.0.11.148kw9n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/with: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/transformers: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/defs: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules/meteor-babel: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.5.8.24_1.127zxv6++os+web.browser+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
```

The error `Directory renamed before its status could be extracted` seems to be linked to a permission fault but I didn't found any way to fix this.

Thank you in advance for your support

**Comment by kaiquewdev** [comment]
To solve this, is needed more information about the contianer... you can publish the container Dockerfile?

**Comment by MaxenceAdnot** [comment]
I simply use the onbuild tagged image provided by https://github.com/meteorhacks/meteord on a Deis cluster using Docker Engine 1.7.1 (https://github.com/deis/deis). I also created an issue on meteorhacks' issue tracker.

The error is occurring while executing `curl -sL https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh`

**Comment by MaxenceAdnot** [comment]
The error is only occurring with Docker using overlayfs as storage driver which is now the default for CoreOS.

**Comment by stubailo** [comment]
I don't think installing Meteor inside Docker on CoreOS is an officially supported environment. Also, you shouldn't need to install Meteor anywhere when deploying your app. We're working on a deployment guide, but the important point is that you should run `meteor build` locally and then deploy a node.js app bundle. Read more here: http://docs.meteor.com/#/full/deploying

Am I misunderstanding something? Is there some reason you need to install Meteor inside your deployment container?

**Comment by MaxenceAdnot** [comment]
Thank you for your answer !

**Comment by olalonde** [comment]
Having same problem here (also installing meteor inside a docker container running on CoreOS). I'm actually trying to deploy a meteor app on Deis (http://deis.io/) and getting the tar errors when this buildpack runs: https://github.com/olalonde/heroku-buildpack-meteor

**Comment by jmlv** [comment]
Having same problem

```
FROM node:0.10

RUN apt-get update
RUN apt-get install -y curl git

ENV METEOR_DIR /opt/app

RUN mkdir -p $METEOR_DIR/src
RUN chown -R www-data:www-data $METEOR_DIR
COPY . $METEOR_DIR/src
WORKDIR $METEOR_DIR/src

RUN curl -s https://install.meteor.com | sh
```

**Comment by olalonde** [comment]
FWIW this is apparently a  bug in CoreOS: https://github.com/coreos/bugs/issues/1095

**Comment by mitar** [comment]
I am having the same issue building Docker image on Docker hub.

Moreover, isn't Galaxy using Docker containers? Why is then Docker not supported?

**Comment by erperejildo** [comment]
Still having this issue

**Comment by cunneen** [comment]
I encountered this issue today when using abernix/meteord:onbuild . I'm fairly new to docker, but at least I was able to get the image built:

- I'm using Docker for Mac OS , so I went to the docker icon -> preferences -> daemon -> advanced and changed the storage driver to aufs.
    ```json
    {
    "storage-driver": "aufs"
    }    
    ```
    - presumably you can edit /etc/docker/daemon.json on other systems in a similar way
- After restarting docker I was able to build the image without the tar errors.

    ![image](https://cloud.githubusercontent.com/assets/1751645/26142367/cae4475a-3b12-11e7-91da-e73a44ad3b7c.png)

**Comment by markoshust** [comment]
confirmed `aufs` filesystem fixes this. everyone should use this filesystem, overlayfs has lots of issues.

**Comment by pmcochrane** [comment]
I too had the same problem using the overlay driver on centos. I discovered that it was a problem with the gnu tar command not working properly with the driver. My workaraound was discovered after trawling about the internet for a bit and ending up using bsdtar instead of tar and meteor install without any issues with the overlay driver. I basically remove the default tar executable, symbolic link bsdtar to tar, install meteor then reinstall the original tar exe. You need to be root to do this.

The relevant section of my docker files is here:
```
# Switch tar to bsdtar as it fails to install Meteor
RUN    echo -n "tar version:"; tar --version \
	&& mv /usr/bin/tar /usr/bin/tar.gnu \
	&& ln -s /usr/bin/bsdtar /usr/bin/tar \
	&& echo -n "tar version:"; tar --version

# Create new user and swap to them
ARG USERNAME=retis-dev
RUN useradd -ms /bin/bash $USERNAME
USER $USERNAME
WORKDIR /home/$USERNAME

# Install Meteor
RUN curl --silent --location https://install.meteor.com/ | bash -
ENV PATH="~/.meteor:${PATH}"

# Put the original tar back
USER root
RUN mv /usr/bin/tar.gnu /usr/bin/tar
USER $USERNAME
```

**Comment by adamgins** [comment]
@cunneen thanks for this. This has helped me.. .but seems like it will be shortlived...
![screen shot 2018-08-16 at 9 40 16 am](https://user-images.githubusercontent.com/7233741/44179223-2160cd00-a139-11e8-8662-b0ff45df6c58.png)

any thoughts on how to resolve this moving forward

**Comment by cunneen** [comment]
@adamgins I'm glad it helped. Have you checked out @pmcochrane 's [solution above](https://github.com/meteor/meteor/issues/5762#issuecomment-327854093)?

**Comment by trsdln** [comment]
Turns out default tar app works randomly, so by running same build sequentially 3 times I got meteor installed:

First run:

```
tar: .meteor/packages/ddp-server/.2.2.0.1myjo2v.qrx6l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/ddp-server/.2.2.0.1myjo2v.qrx6l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/ddp-server/.2.2.0.1myjo2v.qrx6l++os+web.browser+web.browser.legacy+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/ddp-server/.2.2.0.1myjo2v.qrx6l++os+web.browser+web.browser.legacy+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/ddp-server: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/regjsparser/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/regjsparser/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/regjsparser: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
```

second run:

```
tar: .meteor/packages/babel-compiler/.7.1.1.1ltbie6.8w5d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
```

3rd run (success!):

```
Meteor 1.7.0.5 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
```

So if you're lazy enough just try to run `docker build` multiple times :)

**Comment by Rp70** [comment]
> As a note, when implementing @pmcochrane 's solution on other OSes, GNU tar can sometimes be located at `/bin/tar` instead of `/usr/bin/tar`, so you'd have to change the location of the tar files as so:
> 
> ```
> # Switch tar to bsdtar as it fails to install Meteor
> RUN    echo -n "tar version:"; tar --version \
> 	&& mv /bin/tar /bin/tar.gnu \
> 	&& ln -s /usr/bin/bsdtar /bin/tar \
> 	&& echo -n "tar version:"; tar --version
> ```
> 
> and then when putting it back:
> 
> ```
> # Put the original tar back
> USER root
> RUN mv /bin/tar.gnu /bin/tar
> USER $USERNAME
> ```

This works for me: node:8.16-stretch.
```
Meteor 1.8.1 has been installed in your home directory (~/.meteor).
```
Thanks a lot.

**Comment by andreverheij** [comment]
I could be wrong, but why would one need to hack tar to simply install meteor. I am trying to install it in AWS Codebuild, to then build my bundle, that I can then zip up and deploy to my machines. (Ec2, not running docker). 
I am less and less convinced of Docker..

**Comment by cunneen** [comment]
@andreverheij 

> why would one need to hack tar to simply install meteor

There are different versions of `tar` distributed with different OSes and distros, and they are not 100% compatible with each other. I don't think anyone is 'hacking tar', just ensuring the correct version is selected. Meteor itself is distributed as a tarball for each OS.
