### ISSUE TITLE
During dev build, package cache is always reloaded adding a 2.6sec delay

### ISSUE THREAD

**Issue by devgrok** [meteor/meteor#5764]
Creating a fresh issue to track this specific performance bottleneck.

My original comment made in https://github.com/meteor/meteor/issues/2950#issuecomment-161614404:
This testing was done on windows.

I've found that no matter what I change it always checks the local packages are 'up-to-date' (if they've been modified and their version constraints resolve).

The best logging information I got was by using:

```
set METEOR_DEBUG_BUILD=1
set METEOR_PROFILE=1
```

Both an empty project (created using the iron create) and my full project, spend roughly 2.6 seconds doing the "Input#loadFromCatalog" / "preparing project" --> "selecting package versions" step.

My best guess is that the dependency change check (that knows whether the project's or packages' metadata has changed) is always returning true.

Heres a snippet, full attached: [debug_build.txt](https://github.com/meteor/meteor/files/50760/debug_build.txt)

> START CAPTURE 0 undefined took NaN
>    START 1 preparing project
> ...
>      START CAPTURE 2 undefined took NaN
>        START 3 selecting package versions
> | 
> | Select Package Versions: 2496.8
> |     Input#loadFromCatalog (sqlite): 2421.7
> | 
> | Input#loadFromCatalog (sqlite): 2421.7
> | Total: 2421.7
>       DONE 3 selecting package versions took 2498
>     END CAPTURE 2 undefined took 2498
>     START CAPTURE 2 undefined took NaN
>       START 3 downloading missing packages
>         START 4 checking for autopublish@1.0.4
> ...
> END CAPTURE 0 undefined took 2565

The "Input#loadFromCatalog" time is inline with those posted in other issues like: https://github.com/meteor/meteor/issues/5691

Possibly related to: 
- https://github.com/meteor/meteor/issues/4284
- https://github.com/meteor/meteor/pull/5609
- https://github.com/meteor/meteor/issues/5683

**Comment by devgrok** [comment]
This is the result of the change in this pull request: https://github.com/meteor/meteor/pull/5747

Using meteor release 1.2.1
> 
> Select Package Versions: 2353.7
>     new CS.Input: 3.9
>     Input#loadFromCatalog (sqlite): 2279.2
>     other Select Package Versions: 70.6
> 
> Input#loadFromCatalog (sqlite): 2279.2
> other Select Package Versions: 70.6
> new CS.Input: 3.9
> Total: 2353.7

Using the patched version of isopack/contraint-solver (https://github.com/devgrok/meteor/releases/tag/constraint-solver%2Fv1.0.20_1)
> 
> Select Package Versions: 21.2
>     new CS.Input: 2.6
>     other Select Package Versions: 18.7
> 
> other Select Package Versions: 18.7
> new CS.Input: 2.6
> Total: 21.2

**Comment by avital** [comment]
Thanks @devgrok for finding the source of loading from the package catalog on rebuilds unnecessarily! I merged that change into the `devel` branch.

I also built a release of Meteor 1.2.1 with just that improvement to rebuild times.

To try it out, run `meteor update --release 1.2.2-faster-rebuilds.0`. It shouldn't change the speed of initial build but should significantly improve rebuilt times.

For everyone who's chimed in on this thread, please try it out and let me know how noticeable of an improvement this is on your apps.

If it's a big improvement we will release Meteor 1.2.2 with this change.

**Comment by rnosov** [comment]
@avital I've tried the *1.2.2-faster-rebuilds.0* release and my rebuild times are down from more than 9.5 seconds down to a 5.5 seconds (from hitting save button in the text editor to "Meteor server restarted" console message). Plus about 2-3 seconds to auto refresh the browser. Oftentimes, meteor 1.2.1 (seemingly random)  just sits there and flashes package names for good 15 seconds before even starting doing anything remotely useful which is incredibly frustrating. Faster-rebuilds is definitely a step in a right direction and I hope build times can be improved even further. I remember meteor being extremely fast few years ago but these days asp.net seems fast in comparison :(
**+100 for including this change into 1.2.2**

**Comment by jasongrishkoff** [comment]
Installed this. Hard to tell if it's improved. Seems my major issue is rendering once built -- takes ~35 seconds to download all the javascript files individually.

**Comment by ljack** [comment]
Reload speeds of 
http://pastebin.com/S2aXgX6P 1.2.2-faster-rebuilds.0 | Total: 4461.7
http://pastebin.com/jCYZEnBr 1.2.1  | Total: 7138.1
So 1.2.2-faster-rebuilds.0 seems faster. And I also noticed ~2 secs. Quite a variation between 2-4.5 secs?

**Comment by ThaumRystra** [comment]
It looks like a fix for this was merged in [a576bda](https://github.com/meteor/meteor/commit/a576bda03a584dda3ac5e6200bb207008cefd482), should this issue be closed?

**Comment by hwillson** [comment]
Yes it should - thanks for the reminder @ThaumRystra!
