### ISSUE TITLE
Sending binary data in binary form over the DDP websocket

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5766]
So websocket can transmit binary data, but currently binary values in DDP messages are encoded into EJSON and are converted to base64. So the underlying protocol supports binary data. Maybe we should simply use BJSON and transmit data in binary with it? Or proto buffers?

**Comment by stubailo** [comment]
We're using gzip compressed websockets, which might almost completely eliminate the size overhead of using base 64 encoding. The only issue left is the encoding time. Do you have an app where the base64 encoding/decoding is the performance bottleneck?

**Comment by mitar** [comment]
I think it is one of those things which slightly contributes to things but it is not a clear problem by itself. So both compression takes time, and also base64 conversion takes time. And memory. And then the same for decompression and then conversion back.

**Comment by stubailo** [comment]
I feel like trying to optimize something before it becomes a problem is rarely a good idea - probably the best starting point would be to demonstrate an app where this is a real problem, and then we can profile it and see what's going on.

**Comment by stubailo** [comment]
I'll reopen it if we have some more clear examples or evidence.

**Comment by trusktr** [comment]
First-person shooters, it's a problem.

**Comment by trusktr** [comment]
Intense multiplayer real-time games need the performance of sending pure binary.
