### ISSUE TITLE
Couldn't open a mongo connection: Service temporarily unavailable. Please try again later.

### ISSUE THREAD

**Issue by evallgar** [meteor/meteor#5767]
![screen shot 2015-12-09 at 1 15 44 am](https://cloud.githubusercontent.com/assets/10398339/11678976/6e18ad84-9e12-11e5-92b9-018dc5b52a67.png)
Right now is 7:13AM UTC. I know there is an scheduled maintenance today at 19 hours UTC.

Meteor.com system status says all services are operational.

**Comment by evallgar** [comment]
A few minutes ago, the service is back online ...

**Comment by sorenpeterson** [comment]
If your issue has been resolved, let's close this issue.

**Comment by evallgar** [comment]
It was still intermittently working  for a few hours later after my "back online" message ... now is working fine , now Im holding on the scheduled maintenance window.

**Comment by evallgar** [comment]
Well, still not working ... I alredy undeployed the apps, redeploy them and nothing ... `Couldn't open a mongo connection: Service temporarily unavailable. Please try
again later.`

**Comment by sorenpeterson** [comment]
Hey. How's it going lately? Is this issue still persisting?

**Comment by evallgar** [comment]
Unfortunately, yes ...

**Comment by sorenpeterson** [comment]
Can you try it with an example app and see if it works with something else?

**Comment by evallgar** [comment]
Sure, Thanks!. Will get back with the results...

**Comment by evallgar** [comment]
Its been working fine for the last two days ... maybe a few secs downtime in the middle but so far, so good ...
