### ISSUE TITLE
DateTime in android device

### ISSUE THREAD

**Issue by pokaxperia** [meteor/meteor#5768]
Hi, I don't know if is a issue or a mistake. I made an app in Metor and then build to android apk. I installed that apk (signed of course) in android device (tablet), I tested with internet connection and it works fine.
I tested too offline and works too, but the application does not respect the device time when the app are offline. Before I inserted many data, a few fields are "email, createdBy and date", in date field I use this code in Meteor and moment.js:
`var date1 = new Date();`
`ConteoCiclista.insert({createdBy: currentUserId, date: moment(date1).utcOffset(-6).format('L HH:mm:ss')});`

this code returns an inserted data like: `"date" : "12/09/2015 12:02:11"`

Today I used the app, starting at 9:00 am to 12:00pm (time in México City), but without internet connection. Then when I turn on the wifi on my device, to synchronize data with the server it works, but the time of all data is 12:30pm, the same time when I turned on the wifi in my device android.

Was a issue, bug or mistake in my code

**Comment by sorenpeterson** [comment]
Can you provide the code and steps to reproduce this problem? Thanks.

**Comment by pokaxperia** [comment]
This my unique js file:
```javascript
ConteoCiclista = new Mongo.Collection('ciclistas');

  Template.contador.helpers({
    'counter': function(){
      var currentUserId = Meteor.userId();
      var counter = ConteoCiclista.find({createdBy: currentUserId} ).count();
      return counter;
    }
  });
  // Events
  Template.leaderboard.events({
    'click .increment': function (e){
      e.preventDefault();
      $(e.target).addClass('increment');
      var itemId = $(e.target).data().id;
      var itemCat = $(e.target).data().cat;
      var variable = ConteoCiclista.find({},{sort: {date: -1}, limit: 1} ).fetch();
      variable = variable[0];

      Session.set('Id', variable);
      Session.set('selectedItem', itemId);
      Session.set('selectedCat', itemCat);

      var selectedItem = Session.get('selectedItem');
      var selectedCat = Session.get('selectedCat');
      
      var getId = Session.get('Id');
      getId = getId._id;


      $(e.target).removeClass('increment');
      $(e.target).addClass('disabled');

      Meteor.call('updateScore', selectedItem, selectedCat, getId);
    },
    'click .save': function (e, template){
      e.preventDefault();
      var currentUserId = Meteor.userId();
      var findDisabled = template.$('.disabled');
      findDisabled.removeClass('disabled');
      findDisabled.addClass('increment');

      var email = Meteor.user().emails[0].address;
      Meteor.call('newRow', email);
    }
  });

  Meteor.subscribe('conteoCiclista2015');
}

/* Server */
if(Meteor.isServer){
  Meteor.publish('conteoCiclista2015', function(){
    var currentUserId = this.userId;
    Meteor.call('statusDb', currentUserId);

    return ConteoCiclista.find({ createdBy: currentUserId });
  });

}
/* Methods */
Meteor.methods({
  'statusDb': function(currentId){
    var currentUserId = Meteor.userId();
    var existsDb = ConteoCiclista.find({ createdBy: currentId }).count();
    var date1 = new Date();
    
    var user = Meteor.user();
    var email = user && user.emails && user.emails[0].address;
    
    if(existsDb === 0 && currentUserId !== null){
      ConteoCiclista.insert({createdBy: currentUserId, email: email, date: moment(date1).utcOffset(-6).format('L HH:mm:ss')});
    }
  },
  'newRow': function(email){
    check(email, String);
    var currentUserId = Meteor.userId();
    var date1 = new Date();
    ConteoCiclista.insert({createdBy: currentUserId, email: email, date: moment(date1).utcOffset(-6).format('L HH:mm:ss')});
  },
  'updateScore': function(selectedItem, selectedCat, getId){
    check(selectedItem, String);
    check(selectedCat, String);
    check(getId, String);

    var currentUserId = Meteor.userId();
    var existsDb = ConteoCiclista.find({ createdBy: currentUserId }).fetch();
    var objeto = {};
    var key = 'createdBy';
    var value = currentUserId;
    var key1= selectedItem;
    var value1= selectedCat;
    
    objeto[key] = value;
    objeto[key1] = value1;

    if (currentUserId) {
      ConteoCiclista.update({_id: getId}, {$set:objeto});
    }
  },
});
````
Every click on those buttons, insert a "property: value":
![screen shot 2015-12-09 at 1 07 31 pm](https://cloud.githubusercontent.com/assets/1803166/11695643/f183c376-9e75-11e5-9a23-b00f53a1ed10.png)
![screen shot 2015-12-09 at 1 08 16 pm](https://cloud.githubusercontent.com/assets/1803166/11695647/f56c2b68-9e75-11e5-9ef5-c8bddf9cc26a.png)

Suppose I start at 9:00 am , and end at 10:00am (without internet connection). Each record it should be have X time, between 9 to 10 am, right?, but when I turned on the wifi in the android device to download all records synchronized with my url in aws, all records have the same time when I turned on the wifi of the android device (assuming that turned on the wifi at 11:00 am).

If you like, can provide of the apk, to test, and show the records, but first login or create an account with internet connection, create one or two records, and then turn off the wifi, and continue inserting records

**Comment by stubailo** [comment]
@pokaxperia this issue is because the time is generated on the server in your code. You probably want to explicitly generate the time on the client, and pass that as an argument into the method. This is a slightly confusing situation, but isn't ultimately a bug.
