### ISSUE TITLE
Android Marshmallow run-time permissions

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#5770]
:+1: for supporting [Android M run-time permissions](http://developer.android.com/training/permissions/requesting.html) released in API level [23](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux#installing-android-sdk-platform-api-22)), now that [Cordova support](http://cordova.apache.org/announcements/2015/11/09/cordova-android-5.0.0.html) has been released.

**Comment by sorenpeterson** [comment]
:+1:

**Comment by martijnwalraven** [comment]
I'm planning on upgrading to Cordova Android 5.0.0 for Meteor 1.3 (although this won't be in the first couple of betas yet).

**Comment by martijnwalraven** [comment]
I believe this has been fixed with in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
