### ISSUE TITLE
Use WebRTC data channel for DDP transport

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5772]
I think Meteor should make a paradigm shift and move to use WebRTC everywhere for DDP transport. This allows many interesting properties:
* connections can be based on SCTP
* have multi-path routing
* you can have data packets which are reliable or unreliable
* you can even have backpressure support (imagine that you could push back on Meteor publish because client cannot handle observes as quickly as server is pushing)

That would be a really modern web stack based on open technologies.

There is a great open source project already available which provides both client server support so the question is just to integrate it: https://github.com/feross/simple-peer

Community discussion about this is at: https://github.com/MeteorCommunity/discussions/issues/77

**Comment by maxenceC** [comment]
+1, Would love to use webRTC natively in meteor

**Comment by angusmcleod** [comment]
+1 this would be awesome.

We're trying to set up production-ready webRTC with a meteor app currently.

[This useful google doc](https://docs.google.com/document/d/1idl_NYQhllFEFqkGQOLv8KBK8M3EVzyvxnKkHl4SuM8/edit) collects a lot WebRTC resources if people are interested.

**Comment by stubailo** [comment]
Hi Mitar, I don't think we are going to track feature requests to switch underlying technologies without a very good reason. If there is a particular thing you are trying to accomplish which is not currently possible in Meteor, then we can track that as a feature request. This thread seems to be about speculating on what Meteor could be like if it was built on a different technology.

A good way to go about this would be to look at this decision from the point of view of a developer, or application user - what benefits do they get from, say, SCTP? Either way, I don't think GitHub issues are the right place to have this discussion.
