### ISSUE TITLE
Meteor development server: "website is loading" error

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#5774]
The "Website is loading" error occurs indefinitely after you deploy an app to `meteor.com` development server.

This happens when the deployed app has been dormant (no visitor for a while). It used to be that the server would revive successfully in 30 seconds but I observed that now the website just doesn't ever become active.

I am not sure if it's because you've decided to allocate less resources for the development server because of Galaxy, but this has been happening with multiple apps recently.

**Comment by sachaysl** [comment]
same problem

**Comment by wsjwong** [comment]
same

**Comment by tmeasday** [comment]
Hi, we were having some issues with the free hosting a few days ago. You can check the status here: https://status.meteor.com
