### ISSUE TITLE
Cordova: http://meteor.local breaks secure plugins (e.g. no payment on mobile) 

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#5779]
This is related to #5671

Building for mobile devices changes `window.location` from https://myapp.com to http:/meteor.local.

My payment plugin (Braintree) expects https:
It checks for `window.location.protocol` which changes to http: when I run with Cordova and so stops working.

**Comment by martijnwalraven** [comment]
I'm afraid there isn't much we can do about this. Cordova loads your app's assets from local storage, not over the network. In the current version of our plugin we use a custom `meteor.local` host for this, but it will change to `localhost` in 1.3. It doesn't make sense to use SSL on a local connection however (and even if we could it would slow things down unnecessarily). So I suggest you take this up with the Braintree plugin developers and ask them to whitelist `localhost`.

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3 beta (see https://github.com/meteor/meteor/issues/6050).
