### ISSUE TITLE
Understand performance implications of the new module system

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5783]
Time estimate: 1 day or less to understand. Good to ask our users on the forum to run `time meteor build ...` vs `time meteor --version 1.3-modules-beta.0 build ...`

In particular, now that package files are processed with compiler plugins much like files in applications, make sure the extra processing is not noticeable.

**Comment by avital** [comment]
I ran a local test by taking a real production app and running `time meteor build --debug --server localhost`.

On Meteor 1.2.1 it took 29 seconds; On 1.3-modules-beta.0 it took 33 seconds.

**Comment by avital** [comment]
It's worth pointing out that 312a344b8d01e0c54d5eab69205bbf5baef5eb1f will improve the time it takes to *rebuild* an app, but not for initial build.

**Comment by avital** [comment]
Asked users on the forum: https://forums.meteor.com/t/help-us-test-build-times-in-meteor-1-3/15031

**Comment by avital** [comment]
@dgreensp significantly improved build tool performance! Closing this.
