### ISSUE TITLE
Tool changes for Meteor 1.3

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5787]
Command line options to pick the org to which you’re deploying / display the org it belongs to when you deploy. (https://paper.dropbox.com/doc/Product-Design-Meteor-CLI-for-Galaxy-Deploy-and-Transfer-mCkFOLLcNEzI3vsCuAXel)

**Comment by avital** [comment]
See https://github.com/meteor/galaxy-server/issues/631

**Comment by timbotnik** [comment]
@benjamn let me know when this appears on the radar for you guys, happy to pair on it.  I actually think the first 3 "Deploys fail" tasks can be handled by the existing error message passing pipeline, but we should verify that.  The more pressing issue here is the option to specify a galaxy account name when deploying.  It's a big source of unnecessary complexity and user confusion in galaxy so the sooner we can rid ourselves of it the better.

**Comment by avital** [comment]
https://paper.dropbox.com/doc/Product-Design-Meteor-CLI-for-Galaxy-Deploy-and-Transfer-mCkFOLLcNEzI3vsCuAXel

**Comment by zol** [comment]
@tmeasday - Last week @avital indicated he would pair with you on this ticket hence I'm assigning it over to you.
