### ISSUE TITLE
Adding React completely breaks IE8

### ISSUE THREAD

**Issue by tomwasd** [meteor/meteor#5791]
Hi,

To reproduce:

`meteor create simple-todos-react`

`meteor add react`

`meteor run --production`

(as I believe the non-production version of the code isn't expected to run in IE8 anyway?)

IE8 then throws an error:

`Expected ':'`

It appears to relate to a line in the react code doing something like this:

`={get renderer(){return something}`

I would imagine IE8 expects anything within `{`'s to be an object and so for a colon to be present?

I'm not sure if this is a react issue or to do with how the react javascript is being minified/transpiled by Meteor.

Any help appreciated!

**Comment by tmeasday** [comment]
So this appears to come from the React source code: https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/src/shared/vendor/third_party/webcomponents.js#L770

**Comment by tmeasday** [comment]
It appears we are not following the same babel settings as React uses when we build the file: https://github.com/facebook/react/blob/401e6f10587b09d4e725763984957cf309dfdc30/gulpfile.js#L40

**Comment by tmeasday** [comment]
We should remove this line: https://github.com/meteor/react-packages/blob/devel/packages/react-runtime-dev/react.browserify.options.json#L159

**Comment by tmeasday** [comment]
I believe we fixed the issues in the react package. Closing this -- please reopen at  https://github.com/meteor/react-packages/issues if it's still not working,
