### ISSUE TITLE
New Meteor release@1.2 not loading the files in proper order -> root/client/lib loaded before root/lib

### ISSUE THREAD

**Issue by kaushik1979** [meteor/meteor#5797]
I was running 1.1 before and things were smooth. Had to upgrade to 1.2 for another issue and now my whole website is down.

This runs good in the localhost but when I deploy to production, I get the following kind error - 
`
Uncaught ReferenceError: QuickerQolls is not defined
`

When I hit the link and look at the build, <b>I can see that Routers are loaded before the lib/* files</b>. 

Structure of my project - 

client
---lib
--------routers
--------SomeJSFiles.js
---stylesheets
---views
lib
---collections
--------QuickerQolls.js
--------SomeMoreCollection.js
---locales
---SomeConstantKeeping.js
---SomeUtil.js
public
---images
server
---db
---lib
---publish

**Comment by kaushik1979** [comment]
Output of meteor list command - 


accounts-facebook                   1.0.6  Login service for Facebook accounts
accounts-google                     1.0.6  Login service for Google accounts
accounts-password                   1.1.4  Password support for accounts
aldeed:autoform                     5.8.0  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:autoform-bs-datetimepicker   1.0.6  Custom bootstrap-datetimepicker input type with timezone support for AutoForm
aldeed:collection2                  2.6.0  Automatic validation of insert and update operations on the client and server.
andruschka:bootstrap-image-gallery  0.0.5  Blueimp's bootstrap image gallery
blaze-html-templates                1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
cfs:filesystem                      0.1.2  Filesystem storage adapter for CollectionFS
cfs:graphicsmagick                  0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                          0.0.33  GridFS storage adapter for CollectionFS
cfs:standard-packages               0.5.9  Filesystem for Meteor, collectionFS
check                               1.1.0  Check whether a value matches a pattern
cordova:cordova-plugin-dialogs      0.3.0
cordova:cordova-plugin-statusbar    0.1.10
email                               1.0.8  Send email messages
hilios:jquery.countdown             2.0.4  The Final Countdown plugin for jQuery
houston:admin                       2.0.6  A zero-config Meteor Admin
ian:accounts-ui-bootstrap-3         1.2.84  Bootstrap-styled accounts-ui with multi-language support.
iron:router                         1.0.12  Routing specifically designed for Meteor
jparker:crypto-md5                  0.1.1  MD5 algorithm for CryptoJS, standard secure algorithms
jparker:gravatar                    0.4.1  Simple package to use gravatar images
jquery                              1.11.4  Manipulate the DOM using CSS selectors
logging                             1.0.8  Logging facility.
long:google-contacts                0.2.0  Google-Contacts package
maazalik:highcharts                 0.4.0  HighCharts for Meteor, with an easy to use helper to get you started!
manuelschoebel:wait-on-lib          0.3.0  Use Meteor Iron-Routers waitOn to load external javascript
meteor-base                         1.0.1  Packages that every Meteor app needs
meteorhacks:cluster                 1.6.9  Clustering solution for Meteor with load balancing and service discovery.
meteorhacks:fast-render             2.11.0  Render your app before the DDP connection even comes alive - magic?
meteorhacks:npm                     1.5.0  Use npm modules with your Meteor App
miguelalarcos:afwrap-xautocomplete  0.3.1  wrap over xautocomplete so it works ok with autoform
mikael:accounts-merge               0.0.11  Multiple login services for Meteor accounts
mizzao:jquery-ui                    1.11.4  Simple lightweight pull-in for jQuery UI in Meteor
mizzao:user-status                  0.6.6  User connection and idle state tracking for Meteor
mobile-experience                   1.0.1  Packages for a great mobile user experience
momentjs:moment                     2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                               1.1.3  Adaptor for using MongoDB and Minimongo over DDP
mrt:datatables                      0.1.3  DataTable - jQuery plugin for sortable, pagable data
mrt:mathjax                         0.6.3  Render math formulas with mathjax
mrt:require                         0.1.0  A very simple implementation of require/define for meteor
npm-container                       1.1.0+ Contains all your npm dependencies
oauth2                              1.1.5  Common code for OAuth2-based login services
perak:markdown                      1.0.5  GitHub flavored markdown parser for Meteor based on marked.js
pfafman:font-awesome-4              4.4.0_3  Font awesome packaged for meteor
random                              1.0.5  Random number generator and utilities
reactive-dict                       1.1.3  Reactive dictionary
reload                              1.1.4  Reload the page while preserving application state.
semantic:ui-icon                    1.12.3* Semantic UI - Icon: Single component release
session                             1.1.1  Session variable
simple:katex                        1.1.0  KaTeX 0.4.2 for Meteor
simple:reactive-method              1.0.2  Call methods synchronously inside Tracker.autorun
spacebars                           1.0.7  Handlebars-like template language for Meteor
splendido:accounts-meld             1.3.1  Meteor package to link/meld user accounts registered with the same (verified) email address.
standard-minifiers                  1.0.2  Standard minifiers used with Meteor apps by default.
tap:i18n                            1.7.0  A comprehensive internationalization solution for Meteor
tracker                             1.0.9  Dependency tracker to allow reactive callbacks
tsega:bootstrap3-datetimepicker     3.1.3_3* Bootstrap 3 DateTime picker from @Eonasdan, packaged for Meteor.js
twbs:bootstrap                      3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
wylio:mandrill                      0.3.0* Send email via Mandrill's send-template.json
yogiben:pretty-email                0.0.7  Send pretty emails
yong:meteor-videojs                 1.1.0  Video.js 4.12.5
zimme:active-route                  2.3.2  Active route helpers

                                              
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further, try typing
  `meteor add <package>@<newVersion>` to see more information.
                                              
+ These packages are built locally from source.

**Comment by stubailo** [comment]
Hi! I created an app with a folder structure like:

```
client
-- lib
---- a.js
lib
-- client
---- b.js
```

If the files `console.log` their own names, I get "a" then "b" in _both_ Meteor 1.1 and Meteor 1.2. So it doesn't look like the behavior changed, at least in my basic app.

Can you post a repository of an app where the load order is indeed different in the two versions of Meteor? Then I can run it locally and see if I can see the same issue.

**Comment by kaushik1979** [comment]
Hi Sashko,

I will create a repo soon and share that with you. 

Thanks.

**Comment by DrDanRyan** [comment]
I am having file load order issues in deployment as well. My app runs fine with no errors or warnings using the `meteor` command on my development machine, but when I use `meteor build` and deploy the app server, I get errors related to file load order.

One error is from the `files-collection` package:
`Uncaught Error: [The global definition of Mongo.Collection has changed since the file-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before file-collection.]`
Currently `files-collection` is at the bottom of my `.meteor/packages` list.

and the other is from Angular complaining that my main app module is not defined
`Uncaught Error: [$injector:modulerr] Failed to instantiate module marymahoneyApp due to:
Error: [$injector:nomod] Module 'marymahoneyApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`
The angular module is defined in `client/lib/app.js` and no other code that relies on the module is in a lib folder, so it should be loading before them... (which it does on my dev machine).

I never tried deploying with Meteor 1.1, so I can speak to whether this is a new issue or not.

**Comment by DrDanRyan** [comment]
Just discovered the `--production` flag for the meteor command. This breaks the app too; so, my case is not related to the build process; it is the minification/bundling process triggered by the `--production` flag.
