### ISSUE TITLE
More consistent Meteor.user object model - dispite login service

### ISSUE THREAD

**Issue by raix** [meteor/meteor#580]
Would be nice to have easy std. access to general user profile data, dispite oauth service.

The email part for password users seems odd, should be an email in the password service object eg. service.email - like the rest of the services?

Current user model when using password login:
user.username
user.emails[] {address, verified} //guess there is a reason for obtaining multiple emails?

should be like all other services?:
user.profile.name
user.service.password.email
user.service.password.verified

would be more consitent less error prone to use eg. 
Current publish:
  Meteor.publish("users", function () {
    return Meteor.users.find({}, {fields: {emails: true, username:true, profile: true, services: true}});
  });
Should be:
  Meteor.publish("users", function () {
    return Meteor.users.find({}, {fields: {profile: true, services: true}});
  });

maybe an extra field containing current login type?
eg. user.service.current = 'password'
or a getter
eg. user.service.current() -> return eg. the password, facebook object.

maybe a reserved/safe namespace for devs to place custom/app user info?
eg. user.custom.*

I guess on the long run it would be possible to connect multiple oauth services pr. user?

Wrote a general extractProfile function from the Meteor.users supporting mixed twitter,facebook,google and password services - should support more. - would be nicer with std. user model.

https://gist.github.com/4411818

**Comment by almogdesign** [comment]
+1
