### ISSUE TITLE
Localmarket example app: Geolocation not EJSON stringifiable

### ISSUE THREAD

**Issue by matthisk** [meteor/meteor#5800]
In the localmarket example app a Geolocation is send to a (server side) method in share-overlay.js line 53. However the Geolocation returned from `Geolocation.currentLocation` can not be serialized as EJSON, this results in a server side error when calling `createActivity` in activities.js.

**Comment by timbotnik** [comment]
Thanks for the bug report - we'll check into this.

**Comment by matthisk** [comment]
I also created a pull request that fixes this issue #5801, it is not perfect but it works. Didn't test it out yet on all platforms though.

**Comment by hwillson** [comment]
Closing as part of the old issue cleanup process. If needed, please consider re-opening this issue in the [Local Market](https://github.com/meteor/localmarket) repo. Thanks!
