### ISSUE TITLE
Meteor 1.2.1 does not work on Windows 10 x64

### ISSUE THREAD

**Issue by hantsy** [meteor/meteor#5803]
I tried to reinstall Meteor.

I removed `~/AppData/Local/.meteor` folder.

After installed, there is no exception in the installer GUI, and I restarted my system, but there is no `.meteor` in the `~/AppData/Local` and there is no `meteor` command in the path.

**Comment by stubailo** [comment]
Can you try this approach and see if it works? https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation

**Comment by Maxvien** [comment]
Thanks! I am using Windows 10 x64 too. Hope this works :smile:

**Comment by reel** [comment]
Been using the standard Meteor installer on Windows 10 x64 for a few months now and it works fine. Which terminal are you using? If you add the bin to your PATH, does it works?

**Comment by stubailo** [comment]
Yeah I think this is a bug in reinstalling, but things should work fine if you use the alternate install instructions.

**Comment by hantsy** [comment]
@stubailo  The alternative installation is ok for me. Thanks.
