### ISSUE TITLE
allow editing oauth package end_of_redirect_reponse.js externally?

### ISSUE THREAD

**Issue by voidale** [meteor/meteor#5804]
The only way to allow cross different domains social login is to edit `end_of_redirect_reponse.js` window.location.

for example:
my landing page is website.com
my app is at app.webiste.com

I change the end of redirect file to redirect to my app url + token `https://app.webiste.com/login?token="+config.credentialToken;` and I use the loginWithToken to login. 

There is no problem with this case on login method popup because you can use the callback to get the token and redirect manually. 

Also setting up the redirectUrl will not work because it's different domain/no access to token. Simple change but it allows cross domain login which is very useful!

**Comment by timbotnik** [comment]
Sounds like we'd need a slightly different mechanism for setting the redirect URL.  Perhaps you can suggest how this should work?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=allow%20editing%20oauth%20package%20end_of_redirect_reponse.js%20externally%3F&body=Migrated%20from:%20meteor/meteor%235804) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
