### ISSUE TITLE
Blaze reactive variable in input value is not updating

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#5806]
This is to reopen #1965

It looks like there was a regression.

I'm getting the same behavior, and it seems to be related to input focus.  

The value fields of input elements are not updated when: 
- subscriptions update the local data
- they have focus

**Comment by timbotnik** [comment]
Thanks for the report, we will check into this.  In the meantime, perhaps you can ensure that there is a reproduction described on the other thread or add one here.

**Comment by cashbit** [comment]
Any news on that ?

**Comment by abernix** [comment]
@cashbit Any chance of throwing together a bare-bones basic reproduction of this if you're experiencing the problem?  It will greatly increase the chances of someone being able to debug and fix it and if a bug is found, it will also give a good foundation for regression tests to be built around to make sure this doesn't resurface again.

Would be very much appreciated!

**Comment by MichaelJCole** [comment]
Hey, I don't have any context on this bug.  If you have a repro or more info, please re-open or refile.  Thanks!
