### ISSUE TITLE
Can't `require` JSON files

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5810]
Node.js supports `require('file.json')` and [some NPM packages](https://github.com/jshttp/statuses/blob/f2d79a72751edc66d975c855dca278d5d6a634b7/index.js#L2) depend on this feature.

The 1.3 beta does not currently support requiring JSON files in this way, so these packages can't be used.

**Comment by benjamn** [comment]
Specifically, although [we do consider `.json` file extensions](https://github.com/meteor/meteor/blob/77493f92c6a7fc04b53444e418377ccc3af549b8/tools/isobuild/import-scanner.js#L23), we need to generate a module whose `module.exports` is set to the parsed JSON.

**Comment by benjamn** [comment]
Time estimate: 1 hour (with tests).

**Comment by benjamn** [comment]
Fixed in 1.3b1: https://github.com/meteor/meteor/issues/5788#issuecomment-165935104
