### ISSUE TITLE
Implement removable autoimport package that preserves existing package api.export behavior

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5814]
Upgrading to Meteor 1.3 will automatically add this `autoimport` package, and new apps and packages will depend on `autoimport` by default. If `autoimport` is removed, no variables will be automatically imported from packages, so those variables will need to be explicitly imported. For example,

``` js
import {Meteor} from "meteor";
```

would probably have to appear at the top of many files. Is this a strict improvement over the existing behavior? We are not entirely sure, so it seems worth letting developers make this decision themselves.

cc @glasser @avital @martijnwalraven

**Comment by benjamn** [comment]
Time estimate: 1 day.

**Comment by benjamn** [comment]
The more I think about this, the less I think anyone would actually want to remove the `autoimport` package and be stuck with the burden of importing absolutely everything everywhere. You can still explicitly import anything you like. I just don't think there's much value in strictly enforcing that discipline. Let's revisit this after 1.3 if people are still interested.

**Comment by nathan-muir** [comment]
@benjamn I'd be absolutely removing the `autoimport` package as I refactor my current code base for 1.3.

1. It would encourage me to split code into smaller files, so they don't accumulate too many dependencies.
2. It would make obvious which code depends on each package, rather than having to know which globals that package exports and searching for them. This makes refactoring/repackaging code easier.
3. If the import blocks become too verbose, I can always create a `common-imports.js`, and import many symbols in one go.

**Comment by smeijer** [comment]
I'm surprised this one doesn't have more up votes. If the time estimate is really only one day; it would be awesome to have this choice as a developer. I see this one equal to the `insecure` package. Auto imports are awesome during quick prototyping, but it shouldn't be there in the final version of the software one is developing.

**Comment by abernix** [comment]
@smeijer This `autoimport` package actually never came to fruition in Meteor 1.3.

@benjamn Is this still something we should keep around as a feature request or was this superseded by [`api.mainModule`](https://guide.meteor.com/writing-atmosphere-packages.html#adding-javascript)?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Implement%20removable%20autoimport%20package%20that%20preserves%20existing%20package%20api.export%20behavior&body=Migrated%20from:%20meteor/meteor%235814) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
