### ISSUE TITLE
Use readAndWatchFile to read files from node_modules

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5815]
Changing files in `node_modules` doesn't cause the server to restart, because we are currently just using `files.readFile`.

Reported by @jeremyBYU [here](https://github.com/meteor/meteor/pull/5475#issuecomment-164837787).

**Comment by benjamn** [comment]
Time estimate: 2 hours (with tests).

**Comment by avital** [comment]
`1.3-modules-beta.3` was just released which should fix this issue.
