### ISSUE TITLE
https://manual.meteor.com/ seems to be down...

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#5817]
The page is saying: 

This site has been intentionally stopped
Please email whyismyappstopped@meteor.com for details

**Comment by MichaelJCole** [comment]
This was an old site.  I found it as the first hit on the google search "meteor template cleanup"

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=meteor+template+cleanup

Brewer contacted me by email.  Closing this as it seems like an SEO issue.

**Comment by riiiiizzzzzohmmmmm** [comment]
The docs still link to the manual, for example under this section: http://docs.meteor.com/#/full/tracker_dependency
