### ISSUE TITLE
[1.3 beta] issue on global space inside local package.

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5819]
I update a project from 1.2.1 to 1.3 beta0 and my local packages, more of then npm wrappers around jQuery plugins, can´t found jQuery or '$' global.
I create a minimal repo with a jQuery plugin on a local package for reproduction.
This example work fine on 1.2.1 even without add 'jquery' inside package. But is not the case with 1.3.
My impression it is a problem between global Meteor scope and IIFE that not find jQuery on `window ` global object. Maybe when IIFE is called Meteor environment is not yet set??

This  a test repo: https://github.com/bySabi/bug-on-1.3-beta0-with-jqueryplugin-package

**Comment by avital** [comment]
I ran your app on Meteor 1.3-modules-beta.0 and saw the following error in the console:
```
Uncaught TypeError: Cannot read property 'Gallery' of undefined
```

Then I ran it with Meteor 1.2.1 and got the same error.

Are you sure this repro demonstrates the problem you are hitting?

**Comment by bySabi** [comment]
You are right @avital. This repo not fail! .. Sorry for that.
I update an App from 1.2.1 to 1.3 beta0 and I have many problems on the client side. All errors are related to global. Ex: jquery, $, module,  my own global: 'App' are undefined.
I not isolate problem yet. Still looking

**Comment by avital** [comment]
@stubailo told me that he also hit something similar. Maybe he'll find a repro as well. But let's keep looking, if this is a real problem.

**Comment by benjamn** [comment]
Fixed in 1.3b1: https://github.com/meteor/meteor/issues/5788#issuecomment-165935104

**Comment by bySabi** [comment]
@benjamn is still problems with globals on Beta1. This time with  ...
```
sacha_spin.js:43      Uncaught ReferenceError: module is not defined
```

You can reproduce creating a blank project and add `sacha:spin@2.3.1`

**Comment by bySabi** [comment]
I make a workaround adding export in a local package ...
```
api.export('modules`);
```
and ensuring this package is loaded at top

**Comment by bySabi** [comment]
I create a package `globals` 

package.js
```
Package.describe({
  name: 'globals',
  version: '0.1.0',
});

Package.onUse(function(api) {
  api.addFiles('global.js');
  api.export('module');
});
```

global.js
```
var global = this;
global.module = global.module || {};
```

and this solve: `sacha_spin.js:43      Uncaught ReferenceError: module is not defined`

But now I have a new one:
```
ReferenceError: Spinner is not defined
```

**Comment by trusktr** [comment]
Possible duplicates: #5870 #5886
