### ISSUE TITLE
Allow middleware to set the HTTP status code

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#5820]
@stubailo requested someone create an issue on this repo back in April but I can't find one here. Apologies if this is a duplicate.

The problem is discussed at https://github.com/iron-meteor/iron-router/issues/1055 but basically boils down to changing https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L711 from:
```javascript
res.writeHead(200, headers);
res.write(boilerplate);
res.end();
return undefined;
```
to:
```javascript
var statusCode = res.statusCode ? res.statusCode : 200;
res.writeHead(statusCode, headers);
res.write(boilerplate);
res.end();
return undefined;
```

This would allow the router to return a 404 (or any non 200) status code (so Google etc. know not to index the url) but still render the boilerplate for the app so we can display the notFound template configured in IronRouter.

**Comment by tmeasday** [comment]
Agreed that this would be a sensible change. Would you like to send a PR?

**Comment by mjmasn** [comment]
@tmeasday done :+1:
