### ISSUE TITLE
Update example apps and tutorial for modules

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5822]
Rough time estimate: 3-4 days

**Comment by avital** [comment]
Also add `modules` to the skeleton app (`tools/static-assets/skel`)

**Comment by tmeasday** [comment]
- Todos example app is done (or mostly anyway)
- simple-todos/tutorial -- #6303 
- skeleton -- #6306 

I don't think we should change any other examples. Ideally we'd put them in separate repos and indicate in the README that they are current as of Meteor vWhatever.

**Comment by tmeasday** [comment]
@zol close this if you agree and we'll just track in the other tickets.

**Comment by zol** [comment]
Great, closing.
