### ISSUE TITLE
Update/write docs and Meteor Guide for Cordova, including improvements in Meteor 1.3

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#5823]
- [ ] Try out and update iOS and Android tools installation instructions
- [ ] Collaborate on the mobile section of the guide (https://github.com/meteor/guide/issues/40)

**Comment by noahsw** [comment]
Not sure if this is related, but I was just doing the tutorial and got this:
```
╰─± meteor install-sdk ios
Please follow the instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-iOS-on-Mac
```

The thing is I already had the Xcode command line tools installed and working. `meteor run ios` worked like a charm. But when I saw the message to "follow these instructions...", I thought my machine wasn't configured properly.

A better message would have been something like
```
╰─± meteor install-sdk ios
Your machine is ready to go! Simply run `meteor add-platform ios` and then `meteor run ios`.
```

**Comment by hwillson** [comment]
The [Mobile](https://guide.meteor.com/mobile.html) section of the Guide was completed, so closing this off. Thanks!
