### ISSUE TITLE
Rewrite "Using client-side modules…" React tutorial

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5825]
[This section](http://react-in-meteor.readthedocs.org/en/latest/client-npm/), specifically.

Once https://github.com/meteor/react-packages/pull/151 gets merged, the `meteorhacks:npm` and `cosmos:browserify` packages will no longer be necessary (when using Meteor 1.3).

**Comment by stubailo** [comment]
Actually we can get rid of like 70% of that content now:

- JSX transpilation should just be merged into whatever docs we have for ES2015
- Tutorials is now a tutorial on Meteor.com
- The NPM section will be outdated

We should eventually find a better home for this content that looks more "official". Perhaps some kind of "react" appendix to the docs or guide?

**Comment by benjamn** [comment]
Filed a task for this over at the `react-packages` repository: https://github.com/meteor/react-packages/issues/152
