### ISSUE TITLE
Improve audit-argument-checks to work for named arguments

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#5826]
We'd like:
1. To be able to check all properties of an object and have that object counted as checked (for `function({foo})` syntax).
2. To be able to mark something as checked without calling check on it (for eg. `SS.validate()`)

**Comment by zol** [comment]
@tmeasday - is this still relevant? Close or move to post-1.3 milestone if not.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Improve%20audit-argument-checks%20to%20work%20for%20named%20arguments&body=Migrated%20from:%20meteor/meteor%235826) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
