### ISSUE TITLE
import/export should work in `jsx` files

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5827]
Or should we deprecate the `jsx` package and unify it with `ecmascript`?

cc @benjamn @yyx990803

**Comment by benjamn** [comment]
Merged JSX functionality into the `ecmascript` package: https://github.com/meteor/meteor/commit/86b743f96346b66a7b79586823bbb92eeed8a83d

**Comment by avital** [comment]
Nice. So what happens to the `jsx` package we currently have? I guess we'll change it to imply `ecmascript` and print a warning that now your `.js` files are ES6 whether you want it or not?

**Comment by benjamn** [comment]
Filed an issue that includes deprecating `jsx`: https://github.com/meteor/react-packages/issues/152

The `jsx` package was already based on `BabelCompiler`, so making it imply `ecmascript` really shouldn't change anything anyone might care about.

**Comment by vjau** [comment]
With beta.1, meteor is complaining that
```
 While determining active plugins:
   error: conflict: two packages included in the app (jsx and ecmascript) are
   both trying to handle *.jsx
```
but jsx isn't in the package list.
