### ISSUE TITLE
Upgrading apps to Meteor 1.3 should be smooth

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5830]
For example, shouldn't require deleting `.meteor/local`

See https://github.com/meteor/meteor/issues/5788#issuecomment-165551779

Also https://github.com/meteor/meteor/issues/5884#issuecomment-169863891

**Comment by zol** [comment]
Anything that the modules test app isn't exercising could be an issue here. This is basically a QA ticket for testing various configurations of upgrading from 1.2 -> 1.3

**Comment by zol** [comment]
I successfully upgraded some of Percolate's large, production apps from 1.2 -> 1.3beta12 (atmosphere, credo, verso). Closing this out, I think we're in good shape.

**Comment by avital** [comment]
Great!
