### ISSUE TITLE
[1.3-beta1] import Blaze template not include helper, onRendered, onCreated.

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5831]
Hi @benjamn I was trying to include a Blaze template this way:
```
import './hello.html';
```
It work fine but helpers and onRendered, onCreated is not imported.

I create a repo: https://github.com/bySabi/Blaze_template_import__on_1.3-beta.1

**Comment by avital** [comment]
Yes, importing the `.html` file can't know where the `.js` file that defined helper is located. Am I missing something? How did you expect this to work?

**Comment by benjamn** [comment]
Package files that are not explicitly added with `api.addFiles` or imported by the main module (or one of its dependencies) will not be eagerly evaluated.

I believe in this case `client.js` should also explicitly import `hello.js`:
```js
import "./hello.html";
import "./hello.js";
```
Please reopen if that doesn't fix the problem.
