### ISSUE TITLE
Email case sensitive

### ISSUE THREAD

**Issue by cleor41** [meteor/meteor#5842]
Emails are case sensitive when logging into meteor.com. It looks like it uses the default accounts package. I have 2 accounts by accident and I can't delete one of them but they both have the same gmail address; one of them just has an uppercase first letter. Is this by design?

**Comment by timbotnik** [comment]
Hello @cleor41 - I believe this is [something that was fixed] (https://github.com/meteor/meteor/issues/550) in the accounts package in Meteor 1.2, however the actual accounts app may not have been updated ;-)  If you would like further help on removing accounts, please visit the [Meteor Contact Form] (https://www.meteor.com/contact) and choose `Meteor Accounts Support` for the subject.

**Comment by avital** [comment]
I deployed a new version of the Meteor accounts server that fixes this.

Sadly, "forgot password" still matches emails case sensitively. @martijnwalraven did we know this?

**Comment by avital** [comment]
I deployed a new version of the Meteor accounts server that fixes this.

Sadly, "forgot password" still matches emails case sensitively.
