### ISSUE TITLE
transform not working when publishing Cursor

### ISSUE THREAD

**Issue by SeanOceanHu** [meteor/meteor#5843]
Hi guys,
When publishing a collection, the 'transform' option doesn't seem to work:

```
Meteor.publish('postsOfAuthor', function(authorId) {
  return Posts.find(
    {author: authorId},
    {
        transform: function(doc) {
              doc.picture = doc.picture.replace('localhost', '172.24.230.166');
              return doc;
        },
    }
  );  
});
```
Then when client subscribes, the returned doc's picture url was not changed, still 'http://localhost/.....'.

However when passing transform option to Meteor.uesers.find(), it does work, which is strange : (

Can you guys help ? Thanks : )

**Comment by SeanOceanHu** [comment]
Hi guys, btw I'm using the meteor-related & meteor-publish-composite in my project 😉

**Comment by tmeasday** [comment]
Hi @SeanOceanHu, [transforms are not applied to published cursors](http://docs.meteor.com/#/full/mongo_collection). 

However you can apply the technique here to achieve what you want I think:
  http://stackoverflow.com/questions/18343534/how-to-publish-a-view-transform-of-a-collection-in-meteor

**Comment by SeanOceanHu** [comment]
Hi @tmeasday ,
Wow that is not mentioned in the docs~
anyway... thanks so much :smiley:
