### ISSUE TITLE
1.3 beta: redux-devtools errors on import

### ISSUE THREAD

**Issue by ciwolsey** [meteor/meteor#5844]
```
npm install redux-devtools
```
```
import { createDevTools } from 'redux-devtools';
```
Results in error:
```
Uncaught ReferenceError: global is not defined
```
Screenshot of console:
http://puu.sh/m2aD6/d7835b884c.png

**Comment by trusktr** [comment]
Possible duplicates: #5819 #5868 #5870

**Comment by benjamn** [comment]
This will be fixed by https://github.com/meteor/meteor/commit/b7907a2d171f62df25410500e56c31223c6c74cd in the next beta release.

**Comment by ciwolsey** [comment]
@benjamn Yep Just seen the commit. I'm gonna test it out now :)

**Comment by ciwolsey** [comment]
@benjamn Can confirm this fixed my issue. Cheers!

**Comment by benjamn** [comment]
:sparkles: awesome :sparkles:
