### ISSUE TITLE
[1.3] Can't import from HTML without JS file

### ISSUE THREAD

**Issue by stphdenis** [meteor/meteor#5848]
In an app, in the case of `aurelia`, we need to import an npm module as follow : 

```
<body>
  <script>
    System.import('aurelia-bootstrapper');
  </script>
</body>
```

but `aurelia-bootstrapper` doesn't exist in the source browser as we can't import it from a js file.

**Comment by hwillson** [comment]
With regards to the specific example given, Aurelia can be bootstrapped using an `aurelia-app` attribute, pointing to your main Aurelia config file. So something like:

**index.html:**

```html
<body>
  <div aurelia-app="client/main"></div>
  <script>
    System.import('aurelia-bootstrapper');
  </script>
</body>
```

Your `client/main.js` would then include something like:

```js
export function configure(aurelia) {
  aurelia.use.standardConfiguration();
  aurelia.start().then(a => a.setRoot('client/app'));
}
```

Given that there are workarounds to the originally reported issue, and there doesn't seem to be much interest (no +1's) in this relatively old issue, I'll close it off. Thanks for reporting this originally!
