### ISSUE TITLE
[1.3 modules beta1] jsx and ecmascript are both trying to handle *.jsx

### ISSUE THREAD

**Issue by laurentpayot** [meteor/meteor#5849]
With the new beta (1.3-modules-beta.1) I get:
```
=> Errors prevented startup:                  
   
   While determining active plugins:
   error: conflict: two packages included in the app (jsx and ecmascript) are both trying to handle *.jsx
```

jsx package is automatically added when removed, and removing ecmascript leads to build errors as expected...

@vjau has the same problem.

**Comment by mcbain** [comment]
+1

**Comment by nimerritt** [comment]
Try removing and then adding any packages which rely on jsx. Worked for me.

**Comment by nimerritt** [comment]
+1

**Comment by laurentpayot** [comment]
Thanks @nimerritt . Unfortunately it didn't work for me. I tried many combinations of packages removal then install. I'm simply trying to make the Simple-todos app work, can you tell me which packages to remove and reinstall in the list below?
```
$ meteor list
autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
coffeescript          1.0.12-modules.1  Javascript dialect with fewer braces and semicolons
ecmascript            0.2.1-modules.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim              4.3.2-modules.1  Shims and polyfills to improve ECMAScript 5 support
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
jquery                1.11.5-modules.1  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.4-modules.1  Adaptor for using MongoDB and Minimongo over DDP
react                 0.14.3  Everything you need to use React with Meteor.
session               1.1.2-modules.1  Session variable
standard-minifiers    1.0.3-modules.1  Standard minifiers used with Meteor apps by default.
tracker               1.0.10-modules.1  Dependency tracker to allow reactive callbacks
```

**Comment by aaronjudd** [comment]
I found that this happens when you have the `react` package installed.

**Comment by laurentpayot** [comment]
@aaronjudd yes because `react` forces `jsx` install. But I need `react` to use React ;)

**Comment by nimerritt** [comment]
I ended up just removing any packages which use react and including it via
node_modules. I can also confirm that having jsx installed gives the error.

**Comment by trusktr** [comment]
@laurentpayot @aaronjudd Well, with Meteor 1.3 we can now just import React from NPM.

**Comment by aaronjudd** [comment]
@trusktr yes sure.....  but backwards compatibility, informative error messages, etc.. would be good things to have.

**Comment by TimFletcher** [comment]
If you install React from NPM then you won't have access to the `ReactMeteorData` mixin. I installed it from atmosphere with `meteor add react-meteor-data` (to move onto the next error message!).

**Comment by laurentpayot** [comment]
This issue seems to be fixed for me after a `meteor update` now that  both react and ecmascript packages have been updated.

**Comment by avital** [comment]
Should be fixed in `1.3-modules-beta.2` (by essence of a new version of the `react` package in which `.jsx` files are handled by the `ecmascript` package). Run:
```
meteor update --release 1.3-modules-beta.2
meteor update # to update the react and jsx packages
```

**Comment by trusktr** [comment]
@TimFletcher You can use Meteor's react-meteor-data with React from NPM, it works fine.

**Comment by TimFletcher** [comment]
@trusktr If I understand you correctly, that's what I'm doing. I installed React via NPM and react-meteor-data via Atmosphere.

**Comment by trusktr** [comment]
@TimFletcher Yep, that's what I did, and it worked for me. Just be sure not to mix Meteor's `React` with the NPM React. For example, if you create a component with Meteor's instance of React, and then use that component in another component made with the NPM instance of React, then things will just break.
