### ISSUE TITLE
[FEATURE] Make Meteor APIs asynchronous, compatible with Promises.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5852]
*EDIT:* I think the reason I was having this problem is because I was deferring execution of Meteor APIs calls to later ticks than the one where the call was defined (for example, by using a `setTimeout` or `Promise.resolve()`). I think I have it working now because I am now running the APIs synchronously in the same tick (same Fiber).

---

I've got something like this on the server-side:

```js
import {makeStuff} from './makeStuff'
import Things from '../collections/Things'

let promise = null

export async function makeDefaultThings() {
    if (!promise) {
        promise = new Promise(async function(resolve) {
            let stuff = await makeStuff()

            let defaultThings = [ /* ... */ ]
            let things = []

            // make default things if they don't exist already
            console.log('Lets make things.')
            for (let defaultThing of defaultThings) {
                console.log('0', defaultThing)
                let thing = Things.findOne({stuff})  // <-- HERE
                console.log('1', thing)

                if (!thing) {
                    console.log('1.5')
                    let id = Meteor.call('Things.createDefault', defaultThing)
                    console.log('2', id)
                    thing = Things.findOne(id)
                    console.log('3', thing)
                }

                things.push(thing)
            }

            console.log('Done making default things.')
            resolve(things)
        })
    }

    return await promise
}
```

```js
import {makeDefaultThings} from './makeDefaultThings'

(async function() {
  await makeDefaultThings()
})()
```

the line `console.log('1', thing)` following the `findOne` call (marked `HERE`) never fires.

**Comment by trusktr** [comment]
I'm not yet sure if this is because of Regenerator or Meteor. Are there any implications with running certain Meteor APIs in separate ticks?

**Comment by trusktr** [comment]
cc: @benjamn Any thoughts?

**Comment by trusktr** [comment]
I've switched my code to use only Promises without async/await, but the problem is the same; the code pauses on the findOne line:

```js
import {makeStuff} from './makeStuff'
import Things from '../collections/Things'

let promise = null

export function makeDefaultThings() {
    if (!promise) {
        promise = makeStuff()
        .then(function(stuff) {

            let defaultThings = [ /* ... */ ]
            let things = []

            // make default things if they don't exist already
            console.log('Lets make things.')
            for (let defaultThing of defaultThings) {
                console.log('0', defaultThing)
                let thing = Things.findOne({stuff})  // <-- HERE
                console.log('1', thing)

                if (!thing) {
                    console.log('1.5')
                    let id = Meteor.call('Things.createDefault', defaultThing)
                    console.log('2', id)
                    thing = Things.findOne(id)
                    console.log('3', thing)
                }

                things.push(thing)
            }

            console.log('Done making default things.')
            Promise.resolve(things)
        })
    }

    return promise
}
```

So this doesn't seem to be a Regenerator problem. 

What could cause a `findOne` call to block?

**Comment by trusktr** [comment]
Maybe using Promises causes something to break from Meteor's fiber?

**Comment by trusktr** [comment]
Yep, changing all code to use Meteor's API entirely synchronously works. I guess the `findOne` call is in the same tick now.

```js
import {makeStuff} from './makeStuff'
import Things from '../collections/Things'

let promise = null

export function makeDefaultThings() {
    let stuff = makeStuff()

    let defaultThings = [ /* ... */ ]
    let things = []

    // make default things if they don't exist already
    console.log('Lets make things.')
    for (let defaultThing of defaultThings) {
        console.log('0', defaultThing)
        let thing = Things.findOne({stuff})  // <-- HERE
        console.log('1', thing)

        if (!thing) {
            console.log('1.5')
            let id = Meteor.call('Things.createDefault', defaultThing)
            console.log('2', id)
            thing = Things.findOne(id)
            console.log('3', thing)
        }

        things.push(thing)
    }

    console.log('Done making default things.')

    return things
}
```

**Comment by trusktr** [comment]
@benjamn [mentioned](https://forums.meteor.com/t/15177) that in the near future Meteor will have APIs for use asynchronously (with Promises, for example).

**Comment by tmeasday** [comment]
Hi @trusktr I'm quite following, but if you have some synchronous (fibers-based, "pure" Meteor) code that you want to turn into a promise, the best way I believe is:

```
Promise.resolve().then(syncFunc);
```

This will return a promise that will execute the sync func in the next tick and behave like a normal promise.

**Comment by trusktr** [comment]
@tmeasday True, but some Meteor APIs seem to fail when we defer them like that. I think they lose the context of the Fiber, which can be worked around with bindEnvironment, etc, but it's extra work for those of us who want control over all the async things in our app.

**Comment by tmeasday** [comment]
Do you have an example?

**Comment by trusktr** [comment]
@tmeasday The one I described above. I might be able to put a repo together. But, basically, when I stopped using any form of async control (no promises, no async/await or generator control flow) then all the APIs work just fine.
