### ISSUE TITLE
Observing collection skips inserts

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#5854]
Meteor 1.2.1
Win10 x64
Internal MongoDB

Prerequisites: other software is pushing data to mongo collection using 

`col.insert({time:Date.now(), value:123})` 

at different rates (1 mps ... 100 mps (messages per second)). Meteor instance is watching this collection using 

`col.find({},{sort:{'$natural':-1}, limit:1}).observe({added:(it)=>{console.log(it.value)}})`

Problem: meteor receive rate is ~0.3 mps no matter what rate of inserts is.
If I use `Meteor.setInerval()` to query with the same query I do receive all the data at any sensible rate. I do receive `col.find({}).observe({changed:(oldIt, newIt)=>{ console.log(newIt.value)}})` when items are updated in collection (not added) at the same rate they are being inserted either.

**Comment by ujin-v** [comment]
I've dig a little deeper into that question, so I've found that:
>As of Meteor 0.7.2, we use OplogObserveDriver for most queries. There are a few types of queries that still use PollingObserveDriver:

>    Selectors containing geospatial operators, the $where operator, or any operator not supported by Minimongo (such as $text)
>    Queries specifying the skip option
 >   Queries specifying the limit option without a sort specifier or with a sort based on $natural order
  >  Field specifiers and sort specifiers with $ operators such as $slice or $natural
   > Calls to observeChanges using "ordered" callbacks addedBefore and movedBefore. (The implicit call to observeChanges which occurs when you return a cursor from a publish function does not use the ordered callbacks.)

In my question it seem that oplog observer is not involved in any way.

What makes polling observer skip data?

**Comment by stubailo** [comment]
Could you create an app that reproduces this issue and post it to github so that we can clone and run it? Otherwise it is hard to reproduce the exact environment you have.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5854#issuecomment-169167070, without a reproduction this is a tricky issue to help troubleshoot. Closing for now - happy to re-open if anyone is able to demonstrate that this occurs with a recent version of Meteor. Thanks!
