### ISSUE TITLE
Arbitrary architecture argument for packages

### ISSUE THREAD

**Issue by cleor41** [meteor/meteor#5855]
api.use accepts an architecture as its second argument. Is it possible to let it accept arbitrary global constants that are defined somewhere on the server?

**Comment by timbotnik** [comment]
Thanks for the feature request!  Can you explain your use case for this a bit more?

**Comment by cleor41** [comment]
Thanks for the interest, I would love to hear you're thoughts! In the future I'll explain my use case with the feature request.

It seemed like a generalized version of what was already implemented but I didn't take a look at the internals so I don't know for sure. I wanted both my mobile app and the web app to exist under the same project. That isn't an issue if you separate the code base into packages and use the cordova architecture to conditionally load the mobile package. But then I wanted to develop the early stage mobile app in the browser like a normal meteor app bypassing the emulator. There is a conflict here since now the web and mobile app occupy the same environment.

I couldn't think of a way to accomplish this solely in Meteor but I happened to solve it with Angular. I solved the issue by loading both the mobile and web package on the client (regardless if it's cordova or not). Then I created an Angular app for mobile and web and conditionally loaded each app depending on this constant "Mobile = false || Meteor.Cordova". I flipped the hard coded boolean to true to force the mobile version of my code and left it as false in production. Now both applications benefit from the speed of browser development.

I don't know if anyone else had a similar issue with "api.use" or if this would benefit the project in other areas but it seemed pretty useful to have here.

**Comment by cleor41** [comment]
It just dawned on me that I could have given the web package an erroneous or scarcely used architecture to avoid the conflict but there's gotta be a better way to solve this problem.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Arbitrary%20architecture%20argument%20for%20packages&body=Migrated%20from:%20meteor/meteor%235855) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
