### ISSUE TITLE
Differential loading of Cordova plugins

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5858]
I am using a bunch of Cordova plugins I refer via Github tarball URLs. One of these is the OpenTok framework for video conferencing via WebRTC. This plugin is quite huge, and it takes sometimes 20 minutes to download it (maybe also due to my slow network).

My problem is that this download is triggered each and every time I add or remove a Cordova plugin. Instead of just loading or unloading the Cordova plugin I added/removed, Meteor seems to download every plugin again, including the OpenTok plugin.

Yesterday, I was able to watch the entire new video series on Blaze -> React migration while waiting for this. Well, that was a good investment, but I would definitely appreciate if you could implement a kind of "differential" loading for the Cordova plugins, i.e. remember which plugin has already been downloaded and skip this one on subsequent changes. Thanks.

**Comment by martijnwalraven** [comment]
Are you still on Meteor 1.1? With Meteor 1.2, we don't actually use tarballs anymore, but install directly from GitHub (we map the existing tarball URLs to GitHub URLs with a SHA reference). This makes Cordova responsible for downloading plugins. I would have to check, but I believe it caches the Git repositories it downloads from.

**Comment by derwaldgeist** [comment]
No, I am on 1.2 now (finally!).

But I am still using tarball references because I need the plugins in an older app (1.1), too. But I will try to use the cordova plugin syntax instead for plugins that are used in the 1.2 version only (OpenTok is one of them). Maybe this helps?

**Comment by derwaldgeist** [comment]
Can't use the normal syntax, unfortunately, since I am using a fork of this plugin that uses the same plugin name and is not registered in the plugin registry. What exactly do you mean by URLs with a SHA reference, can I optimize my code to point to this instead of the tarball?

**Comment by martijnwalraven** [comment]
No, that shouldn't matter, because we internally already convert tarball URLs to these Git URLs in Meteor 1.2.

You'll find more on these Git URLs with SHA references [here](https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration#meteor-packages-with-cordova-dependencies).

**Comment by derwaldgeist** [comment]
Thanks. Yes, I also found the Cordova git reference docs here now:
https://cordova.apache.org/docs/en/latest/guide/cli/index.html

But from these only the #<commit> version worked, as you documented in your link. I am trying this now.

**Comment by derwaldgeist** [comment]
Nope. This did not help. It's still downloading the plugin again, even after I just removed a plugin.

BTW: I also had a strange phenomenon. The plugin I removed was:

```
VitaliiBlagodir/cordova-plugin-datepicker
```

After I did this, I got the following message from Meteor:
``` % "cordova-plugin-file" is required by (cordova-plugin-file-transfer) and cannot be removed (hint: use -f or --force) and cannot be removed (hint: use -f or --force)
```
Is it normal that plugins remove other plugins if they depend on them? And does Cordova know which plugins Meteor acutally needs?

**Comment by martijnwalraven** [comment]
Unfortunately, Cordova's dependency management (and version resolution) is really weak. That is the reason we remove all plugins whenever any of the plugins change. This seems like an innocent warning, but I'm not sure why it would persist.

**Comment by derwaldgeist** [comment]
Fortunately, it only persisted once. The next time I started with run device, it disappeared.
