### ISSUE TITLE
[BUG] [1.3-modules-beta.1] SyntaxError with no clue where it's happening.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5862]
I've got an error like this: http://trusktr.io:7777/boleculico

The error doesn't say where the syntax error is happening. That's the only output that there is.

In my case, I had to rename .js files to .jsx files.

**Comment by trusktr** [comment]
Yep, apparently that was the problem: the `.js` files with JSX in them needed to be renamed to `.jsx` files. The error message could use some TLC. :}

**Comment by trusktr** [comment]
I just got another one, but this time I have no JSX anywhere. I might have an extra `<` somewhere, maybe, but the error doesn't appear to tell me where it is: http://trusktr.io:7777/dixegetaye

**Comment by avital** [comment]
Dup of #6009
