### ISSUE TITLE
[bug] [1.3-modules-beta.1] Cannot import JSX files.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5864]
I've got a file that does

```js
import blazeToReact from '../../../utilities/blazeToReact'
```

which results in 

```
Uncaught Error: Cannot find module '../../../utilities/blazeToReact'
```

in the browser.

The file being imported is indeed named `../../../utilities/blazeToReact.jsx`. If I remove the JSX content from that file and rename the extension to `.js`, then it works fine.

**Comment by casperan** [comment]
try

import blazeToReact from '../../../utilities/blazeToReact.jsx'

you have to specifiy .jsx when importing from .jsx files.

at least for now.

**Comment by casperan** [comment]
https://github.com/meteor/meteor/issues/5836

**Comment by trusktr** [comment]
@casperan 

I also tried

```js
import blazeToReact from '../../../utilities/blazeToReact.jsx'
```

which results in the same exact error message:

```
Uncaught Error: Cannot find module '../../../utilities/blazeToReact'
```

Note the error message doesn't show ".jsx" at the end of the filename.

**Comment by casperan** [comment]
try

import { blazeToReact } from '../../../utilities/blazeToReact.jsx'

**Comment by trusktr** [comment]
@casperan The blazeToReact file looks something like this:

```js
export default
function blazeToReact(name, options) { /* ... */ }
```

so the named import wouldn't (shouldn't) work.

**Comment by marines** [comment]
I experienced this issue as well (I think).

I'm including React components placed in */client* to router placed in */lib*. Importing fails then. But when I move the router to */client* then it imports components correctly (router itself doesn't register any routes itself so it doesn't work but it's expected).

**Comment by benjamn** [comment]
I believe this is fixed now. Please reopen if you're still having this problem!
