### ISSUE TITLE
[bug?] [1.3-modules-beta.1] Source maps might be off by one line.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5865]
I have a file that starts with

```js
import TWEEN from 'tween.js'
import Channel from 'async-csp'
import React from 'react'
import ReactDOM from 'react/lib/ReactDOM'
```

When importing `Channel` which is on line *2*, I get an error saying

```
Uncaught Error: Cannot find module 'babel-runtime/helpers/create-class'
```

In the stack trace, the line number is `1` instead of `2`, which shows the import or TWEEN. So, that led me to think the Source Map is 1 line off. Is this something that can normally happen with source maps sometimes?

**Comment by mjmasn** [comment]
Is the stack trace not referring the to line number where you're importing 'babel-runtime/helpers/create-class', somewhere in async-csp?

**Comment by trusktr** [comment]
Right. The error is in async-csp, but the line number points to the import of tween.js.

**Comment by trusktr** [comment]
Wish I saved a repoduction. I'll post back if I find one again.

**Comment by avital** [comment]
We'd love to look into this if someone comes up with a repro.

**Comment by trusktr** [comment]
I'll report back if I notice it again.
