### ISSUE TITLE
[bug] [1.3-modules-beta.1] Sub-dependency not found.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5866]
I'm using NPM v3.5.x to `npm install` deps into `node_modules`. Despite the fact that the `babel-runtime` dependency exists in async-csp's `node_modules` and/or my app's `node_modules`, I get an error when trying to import `Channel` from `async-csp`:

```js
import Channel from 'async-csp'
```

```
Uncaught Error: Cannot find module 'babel-runtime/helpers/create-class'
```

**Comment by trusktr** [comment]
Despite installing `babel-runtime` to my project directly with `npm install 'babel-runtime@^5.8.34' --save`, matching the version that async-csp depends on, I still get the error (even after `meteor reset`).

**Comment by trusktr** [comment]
I've stopped my app, `meteor reset` my project, deleted `node_modules`, and ran `npm install` again, after which node_modules looks like this (with irrelevant parts removed):

```
node_modules
├── async-csp
├── babel-runtime
│   ├── helpers
│   │   └── create-class.js
├── jss
├── jss-camel-case
├── jss-extend
├── jss-nested
├── jss-props-sort
├── jss-px
├── jss-vendor-prefixer
├── lowclass
├── react
├── react-dom
├── react-mixin
├── tinycolor2
└── tween.js
```

The error is the same.

**Comment by benjamn** [comment]
I think the problem here is that there is already a `babel-runtime` Meteor package. Of course, local `node_modules` should take precedence over Meteor packages. That bug should be fixed in the next beta: https://github.com/meteor/meteor/issues/5933

**Comment by trusktr** [comment]
@benjamn What if a dev wants to use NPM package `X` in the app and puts it in `package.json`, and a Meteor package in the app also depends on NPM package `X` but the dev is unaware?

Will the dev's version of NPM package `X` always take precedence, or will the Meteor package get it's own version of NPM package `X`?
