### ISSUE TITLE
Exposing service Configuration data at client side

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#5867]
I am using Service Configuration package to store auth0 configuration 

Current behaviour of service package is its publish all auth0 credentials at client side we want to restrict to access service configuration setting details to client side.

Please help on this.

Thanks

**Comment by stubailo** [comment]
What are you referring to in particular? The app ID/app secret of the OAuth server, or the individual user's credentials?

**Comment by mitiaptest** [comment]
@stubailo  Its exposing all my Auth0 credentials like domain name, clientId, clientSecret etc parameters which I have inserted into ServiceConfiguration.configurations.insert({}).

Thanks,
Mit

**Comment by stubailo** [comment]
Here's what I get in the client-side console:

```js
[
  {
    "_id": "ywfD8uNN6cLDaPS29",
    "service": "facebook",
    "appId": "809729075745606",
    "loginStyle": "popup"
  }
]
```

The client secret isn't in there, and I think the app ID isn't secret information.

**Comment by mitiaptest** [comment]
But with my APP, its expose secret as well.

**Comment by stubailo** [comment]
Can you create a reproduction where this happens? I can't reproduce it on my machine so it's hard to identify why this is happening.

**Comment by mitiaptest** [comment]
@stubailo Sure, will deploy sample App shortly.

**Comment by mitiaptest** [comment]
@stubailo  I have deployed code on http://serviceconfigurationcheck.meteor.com.If We check in my console with ServiceConfiguration.configurations.find().fetch() its showing all my auth0 details.

**Comment by mitiaptest** [comment]
@stubailo Any update?

**Comment by mitiaptest** [comment]
@stubailo Can you please let me know where change required for this?

**Comment by stubailo** [comment]
Hey for some reason I can't figure it out yet. Will have to ask someone.

**Comment by mitiaptest** [comment]
@stubailo ok thanks

**Comment by mitiaptest** [comment]
@stubailo Have you got any solution for this?

**Comment by stubailo** [comment]
So you have a field named `clientSecret` here: https://github.com/mitiaptest/login_demo/blob/0391d5f17eefd4f226fe64741c000e793d615f4a/server/server.js#L7

In Meteor, the publication publishes everything except a field named exactly `secret`: https://github.com/meteor/meteor/blob/7b53281af6f074aa18b11db4931f2c45d54b2d83/packages/accounts-base/accounts_server.js#L696

So I think your problem can be solved by renaming the `clientSecret` field to `secret`. Would that work for you?

**Comment by mitiaptest** [comment]
@stubailo Thanks.I have renamed it need to test it after that I will let you know.

**Comment by mitiaptest** [comment]
Thanks @stubailo for your help,Its working fine.

**Comment by stubailo** [comment]
Great, glad it worked out! Sorry for the delay.
