### ISSUE TITLE
[1.3-modules.beta.1] Global variables are undefined for some pre-1.3 packages.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5868]
After updating to 1.3-modules.beta.1 and using ES2015 modules for everything, the `jparker:gravatar` package (which depends on the `underscore` package) complains that `_` is undefined. I was able to work around it by simply putting

```js
window._ = _
```

in `client/main.js`.

**Comment by etmarch** [comment]
+1. This is happening to me after just updating my app from 1.2 to 1.3-modules.beta.2. 

I tried placing `window._ = _` in client/main.js, but to no avail.

**Comment by trusktr** [comment]
Unfortunately, the `window._ = _` hack won't work if a module needs it during module evaluation, or if a Meteor package needs it during evaluation of the package code. It will work only for things that are triggered at run time.

Another solution would be to make a local Meteor package in the `packages` folder, have that package do the `window._ = _` trick, and inside of `.meteor/local` list your custom package first so that it loads before other packages. (I read somewhere that the order of things in `.meteor/packages` determines the package load order, so you can take advantage of that).

**Comment by trusktr** [comment]
Possible duplicates: #5819 #5870

**Comment by avital** [comment]
Should be fixed by d542ffb1a96418b190d84999c5802a157dacea66

**Comment by avital** [comment]
`1.3-modules-beta.3` was just released.
