### ISSUE TITLE
[idea] [1.3-modules] Path aliases for modules.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5869]
I'm currently doing

``` js
import something from '/app/src/client/utilities/something'
```

it'd be nice to be able to configure path aliases so we can instead do

``` js
import something from 'client/utilities/something'
```

which would be useful for all client code, and similar to server code. We could make `both` alias to anywhere where modules for both ends are stored:

``` js
import Things from 'both/collections/Things'
```

The config might look like

```
{
  "aliases": {
    "client": "/app/src/client",
    "both": "/app/src/both",
    "client": "/app/src/server",
  }
}
```

**Comment by jamiter** [comment]
Hi @trusktr,

Where does the `/app` prefix come from and how did you know? I couldn't find documention about absolute paths. Can you point me to the right documentation if there is any? Thanks!

**Comment by trusktr** [comment]
@jamiter It's not documented per se, but @benjamn mentioned it [here](https://github.com/meteor/meteor/pull/5475#discussion_r46606764).

**Comment by jamiter** [comment]
Thanks @trusktr, very helpful!

More on topic: I like the alias idea. But this could lead to path conflicts, right? It would require some extra logic to determine the winner when a "normal" path is the same as an alias.

Looking at some existing npm packages:
https://www.npmjs.com/package/path-alias
https://www.npmjs.com/package/require-alias

These package prefix the alias path with a '@'. A nice way to prevent conflicts although you might want to use another sign (because '@' looks like its a username prefix).

**Comment by trusktr** [comment]
@jamiter I think the safe bet would be to assume that alias have highest priority. It would be up to the developer to not make an alias that overwrites something else.

@benjamn What do you think about this idea? I think this would be good, because some libraries, (f.e. [Famous 0.3 (my CommonJS fork, converted from AMD so that it works with Meteor 1.3)](https://github.com/trusktr/famous/tree/commonjs)) have all of their source files in`src` or `lib` (and ship that way). 

Here's a use case. Without aliases, importing anything from Famous always includes `/src` in the path:

```js
import RenderNode from 'famous/src/core/RenderNode'
```

But Famous intended for the `src` part to be omitted in their browserify workflow, like this:

```js
import RenderNode from 'famous/core/RenderNode'
```

Can you support aliases with Meteor 1.3? It'd be really convenient (for example, for bringing in a library into Meteor 1.3, a library that depends on Famous 0.3 and doesn't use `/src` in any paths).

For now, I'll have to actually convert all the import statements, as I can't wait, but it might be a good idea for other things (aliasing file paths relative to the app root, for example).

**Comment by trusktr** [comment]
@benjamn Could you provide some guidance as to where/how I might implement this for Meteor 1.3? I might like to make a PR for this one.

**Comment by smeijer** [comment]
This one would still be very nice to have.

**Comment by trusktr** [comment]
Haven't tried it yet, but I wonder if this Babel plugin would do the trick: https://www.npmjs.com/package/babel-plugin-module-alias

**Comment by smeijer** [comment]
I tried that one. But cannot get it to work. I guess it's because the plug-in resolves relative to the meteor node_modules directory instead of to the project root.

**Comment by smeijer** [comment]
Same thing for: https://github.com/tleunen/babel-plugin-module-resolver

**Comment by scottburch** [comment]
I had this working fine with this in my .babelrc and Meteor 1.4.  I am now playing with Meteor 1.5 beta and it no longer works.

{
  "plugins": [
    ["module-resolver", {
        "alias": {
          "images": "common-lib/lib/images",
          "src": "/client/imports",
          "components": "/client/imports/components",
          "services": "/client/imports/services",
          "styles": "/client/imports/styles",
          "test-helpers": "./tests/ua/helpers"
        }
    }]
  ]
}

**Comment by bouffa** [comment]
Thanks @scottburch , I tried your solution with meteor 1.4.3, it indeed works when I use `require('...')` but, it fails when I use `import '...'` . Do you have any clues how to fix this? Thanks.

**Comment by scottburch** [comment]
@bouffa I don't know.  It worked fine for me with import as well as with require.

**Comment by scottburch** [comment]
@bouffa Yep.  I upgraded meteor today and it broke.  Guess it does not work with the newer versions.

**Comment by iamkevingreen** [comment]
I'm on Meteor 1.4.3.2, and it works locally but fails with deployment:

```
e: /tmp/build_e850b87d68d87550d6f2395ab79e68d2/both/components/Pages/Admin/Locations/Single.js
remote: (os.linux.x86_64)
remote: 
remote: If you notice problems related to these missing modules, consider running:
remote: 
remote:   meteor npm install --save stores actions
```

my paths are getting pretty painfully long so something like this would have saved the day, but .babelrc doesn't seem to be playing nicely with the deployment process

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bidea%5D%20%5B1.3-modules%5D%20Path%20aliases%20for%20modules.&body=Migrated%20from:%20meteor/meteor%235869) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
