### ISSUE TITLE
Meteor Windows 7 Install Issue

### ISSUE THREAD

**Issue by arodr967** [meteor/meteor#5873]
It is taking a VERY long time to install. I restarted my computer and still stays stuck on the installing screen.
It stays stuck here:
![install meteor](https://cloud.githubusercontent.com/assets/11788477/11985654/0f29c32e-a995-11e5-8163-f9c8005253c8.PNG)

After a while, it will show up on my programs and when I try to do:
meteor create test 
it responds with "bash: meteor: command not found"

**Comment by avital** [comment]
Sorry for that.

In the meanwhile, you can follow the manual Windows installation instructions here: https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation

**Comment by arodr967** [comment]
Thank you @avital, it worked! Looking forward to using Meteor.

**Comment by deathmood** [comment]
Do not know anything about installation issues - I've installed it normally. But it really does not add `meteor` to windows PATH, that is why it is not available with bash shell. However, somehow (while not being in the PATH) it is available in plain windows cmd shell. And in powershell too.

**Comment by bdevalia** [comment]
I am having same issue. i wil give a manual windows installation a try

**Comment by twins16** [comment]
try ubuntu or mac it's very easy :(
