### ISSUE TITLE
[idea] Throw an error when subscribing to a non-existent publication.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5876]
I've changed some stuff on the server-side, and now I've gotta go hunt down parts of the client code that are subscribing to pubs that no longer exist. And error message would be nice for these cases, or in case of typos, etc, rather than silently failing.

**Comment by stubailo** [comment]
This would be solved by something like this: https://forums.meteor.com/t/package-idea-validated-publication/15516/1

Anyway, I think that `Meteor.subscribe("x", { onError(err) { console.error(err) } } );` would work. It sure is a lot of boilerplate though, which could be solved again by the above idea for a wrapper package.

**Comment by trusktr** [comment]
Yeah, as long as there's some way to error when subscribing to a non-existent pub, that'd be great!

**Comment by stubailo** [comment]
Yep, that's another great feature that a wrapper package would provide - trivial backcompat.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/5876#issuecomment-167851482, this could be (potentially better) solved using a wrapper package (like the [mdg:validated-method](https://atmospherejs.com/mdg/validated-method) approach). Given this and the lack of +1's on this issue (and as part of the on-going old issue cleanup process), I'll close this for now. Thanks for submitting the original suggestion!
