### ISSUE TITLE
Object ID including timestamps

### ISSUE THREAD

**Issue by dtruel** [meteor/meteor#5878]
Hello,

I have an idea for using objectIDs that are based on timestamps.  Why don't you send the current time on the server at application start.  Then start a timer from page load time on the cient.   Use that to calculate current time to generate a time-stamped id.

Could this worK?

**Comment by tmeasday** [comment]
I think that technique sounds like it has a lot of scope for things to go wrong. My understanding is the primary concern of the current random id generation technique is to ensure uniqueness of ids across different clients. I'm not sure how a timestamp based technique can do this.

**Comment by dtruel** [comment]
Hello tmeasday, thanks for the response!

My reason for posting this is because the current method of random id's is not optimal.  Yes, the chances of a collision are small, but they do exist.  I have investigated how mongodb id's are created, and think I have come up with a way to create ObjectIDs that are even less likely to be conflicting:


I believe Mongodb uses a timestamp based ID when generating internal IDs.  Here's how it works from the mongodb site:

```
Overview

ObjectId is a 12-byte BSON type, constructed using:

a 4-byte value representing the seconds since the Unix epoch,
a 3-byte machine identifier,
a 2-byte process id, and
a 3-byte counter, starting with a random value.
```
https://docs.mongodb.org/manual/reference/object-id/

The advantage to this would be that the probability of getting duplicates would hopefully be reduced.  If part of the _id contains the date-time, we know that values created now will certainly not conflict with ones created in the past.

To get more uniqueness, we could also bank on the fact that every meteor connection is keepalive.  There is probably some way to get the number of that keepalive connection.  Each one of those numbers will be unique.  So to ensure a unique id, we could do this:

4 - byte value since unix epoch
3 - byte connection id
3 - byte counter
3 - byte random

This way, if implemented, would probably help with objectID uniqueness.

The only possible flaw I see is that the client would get the time wrong.  But if every time instead of sending 'ping'-'pong' to keep the connection alive, you send the current server time, and then set a timer on that, you would be able to get the current time, with the max difference in time being (time between ping-pong + transfer time).  And that would almost never, ever get to that point, as to be that far off, the computers internal timer wouldn't be working, and if that's not working, the site will not work anyways.

**Comment by tmeasday** [comment]
Hi @dtruel,

I can see two obvious difficulties with this
1. As you've pointed out, trusting the client's time is problematic. There are solutions, as you've pointed out, but they involved some pretty serious changes in the DDP protocol and a lot of extra data transfer.

2. A unique connection id is actually a difficult thing to achieve when you have multiple backends. It's a classic distributed systems problem to guarantee uniqueness across different hosts.

But that aside, I disagree it's possible to "significantly reduce the chances of a duplicate id". Have you calculated on an absolute scale what the chances actually are? It's astronomically small.

**Comment by dtruel** [comment]
Ok, found somebody else's calculations:

```
The _ids in Meteor.users consists of 17 characters (a-Z + 0-9). That gives you 17^44 = 1.379598e+54 combinations. If you would have a billion (10^9) documents in the collection, the risk of generating an existing _id would be 0.0000000000000000000000000000000000000000001%.

I wouldn't care about that, but you might have an enormous amount of documents?
```

https://forums.meteor.com/users/Peppe_LG

So I would have to say you are right!
