### ISSUE TITLE
1.3-modules-beta.2 - modules package - Arguments to path.join must be strings

### ISSUE THREAD

**Issue by apptain** [meteor/meteor#5879]
I was looking to start working with import and export of modules using React jsx files in Meteor. I cloned the simple-todos-react repo, updated to 1.3-modules-beta.2, and add the modules package. Without changing the project code at all, I'm getting the below error from having installed the modules package. 

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.pathJoin (/Users/jdemilo/.meteor/packages/meteor-tool/.1.1.11-modules.3.12zjyk9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:86:16)

I saw the other issue that import and export keywords do not work in jsx files, and was hoping adding the modules package may help, but to no avail. 

https://github.com/meteor/meteor/issues/5795

Thanks, and Merry Christmas!

**Comment by benjamn** [comment]
Probably related: #5871

**Comment by avital** [comment]
Looks like this is happening specifically for packages with build plugins?

**Comment by benjamn** [comment]
Yes, and pre-1.2-style build plugins, specifically.

**Comment by avital** [comment]
Should be fixed by https://github.com/meteor/meteor/commit/221d8af44b62b91de50f93077c2b488db4a06dc4, and will be out with `1.3-modules-beta.3` later today.

**Comment by avital** [comment]
`1.3-modules-beta.3` was just released.
