### ISSUE TITLE
Meteor doesn't interpret the scope for Meteor.userId()

### ISSUE THREAD

**Issue by gcacars** [meteor/meteor#5881]
I have a wrapper for Mongo.find for example and a lot of various functions that works inside publish functions, methods, or as a normal function.
When I get the user id, meteor always show the error:
`Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.`
But the function has a validation for correct way of get the user id, like:
```
function findWrapper( select ){
    var userId = this.userId || Meteor.userId();
}
```

So, Meteor shouldn't show this error!

**Comment by tmeasday** [comment]
Hi @gcacars,

This is an issue with the way that `this` is propagated in JS. You'd need to pass the `userId` into the finder from your publication, there's no way to make `this` pass through easily (or in a sensible way). 

You'll also have problems with this code if you ever run it from a server context outside of a method or publication (where there legitimately isn't any user).
