### ISSUE TITLE
[BUG] [1.3-modules-beta.2] Unable to import files in "imports" folder, modules not working?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5885]
I was trying to get `modules` working over at https://github.com/trusktr/site/tree/8a151f953458ae8080902e879d6cf3df4dc7a5ee, but no luck. I've done `meteor add modules`, but Meteor seems to load files as if they are normal, non-module files.

**Comment by bySabi** [comment]
replace `modules` with `ecmascript` on .meteor/packages

**Comment by xamfoo** [comment]
I have a similar issue for beta.2. Neither the `imports` in the root folder, `client\imports` or `server\imports` are lazily loaded. Tried with:

- `ecmascript`
- `ecmascript`+`modules`

Using linux. Let me know if a repro is required.

**Comment by bySabi** [comment]
Following `modules` package docs, https://github.com/meteor/meteor/tree/release-1.3/packages/modules,  `ecmascript` is needed for  `import/export` ES2015 support and `modules` is related to CommonJS/Node `require/exports` support,  having say that.

Lazy evaluation is not work. Files on `imports` folder are evaluate `"eager"`, like usual.

**Comment by jamiter** [comment]
I confirm that files in `/imports` are loaded `eager`, just like all other files. @benjamn, a known issue?

**Comment by nchenbang** [comment]
I think they're already in the process of solving the bug. You can have a look at the commit here https://github.com/meteor/meteor/commit/fa27a67849ba97236d1f0aad90517deefef184c4

**Comment by jamiter** [comment]
@nchenbang, thanks, it looks like a fix indeed!

**Comment by avital** [comment]
Happy this helps! Will be out in `1.3-modules-beta.3` (not yet released)
