### ISSUE TITLE
[1.3modules-beta.*] on linux failure on build

### ISSUE THREAD

**Issue by Cherviakov** [meteor/meteor#5888]
Tried to use modules on Centos 7 developing on meteor. On all three available betas end up with error:
W20151226-19:55:12.839(2)? (STDERR)           
W20151226-19:55:12.841(2)? (STDERR) /home/yukinohito/.meteor/packages/meteor-tool/.1.1.11-modules.0.1nwvf97++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151226-19:55:12.841(2)? (STDERR)                                             throw(ex);
W20151226-19:55:12.842(2)? (STDERR)                                                   ^
W20151226-19:55:12.842(2)? (STDERR) ReferenceError: module is not defined
W20151226-19:55:12.842(2)? (STDERR)     at s (packages/systemjs_systemjs/packages/systemjs_systemjs.js:48:1)
W20151226-19:55:12.842(2)? (STDERR)     at packages/systemjs_systemjs/packages/systemjs_systemjs.js:48:1
W20151226-19:55:12.842(2)? (STDERR)     at Package (packages/systemjs_systemjs/packages/systemjs_systemjs.js:53:1)
W20151226-19:55:12.843(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/packages/systemjs_systemjs.js:115:4
W20151226-19:55:12.843(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/packages/systemjs_systemjs.js:127:3
W20151226-19:55:12.843(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/boot.js:242:10
W20151226-19:55:12.843(2)? (STDERR)     at Array.forEach (native)
W20151226-19:55:12.844(2)? (STDERR)     at Function.​_.each._​.forEach (/home/yukinohito/.meteor/packages/meteor-tool/.1.1.11-modules.0.1nwvf97++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151226-19:55:12.844(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/boot.js:137:5

Also tried to use universe:modules, universe:modules-entrypoint and rocket:module, all end up in various errors or problems. In the end have feeling that there is not way to use modules on meteor on linux at all.

**Comment by avital** [comment]
Is there a repro here? Is this fixed with `1.3-modules-beta.3`? We'll need more information to investigate this.

**Comment by avital** [comment]
Closing due to no repro. If you have one, please open a new ticket.
