### ISSUE TITLE
Poor error message in Accounts.Oauth

### ISSUE THREAD

**Issue by Custos** [meteor/meteor#5889]
Can we get some slightly more accurate error messages?  Just requires some extra logic in my alerting when a auth attempt cancels it reports an error doesn't make sense.

packages/accounts-oauth/oauth_server.js 

``` javascript
error: new Meteor.Error(
 Accounts.LoginCancelledError.numericError,
  "No matching login attempt found") };

error: new Meteor.Error(
Accounts.LoginCancelledError.numericError,
  "No registered oauth service found for: " + result.serviceName) }
```

**Comment by stubailo** [comment]
Are you saying we should just change the error message to something other than `"No matching login attempt found"`?

**Comment by abernix** [comment]
Closing because this is idle and the request is not clear.
