### ISSUE TITLE
[1.3-modules-beta.2] How do we transform files in node_modules?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5892]
My first thought was to make a build plugin that converts AMD to CommonJS, but then I realized that build plugins apply to Meteor packages and app code, not the libraries we install from NPM.

@benjamn Any suggestions? For example, I'd like to get some old stuff that I wrote with Famous 0.3.5 working, and the code is all AMD modules within the NPM package.

It seems that to accomplish this with a build plugin, I'd have to resort to making a wrapper package for Famous (which is what we're trying to avoid in Meteor 1.3 if we can just npm install a library) so that the build plugin can apply to the files. Also, the file names all end with `.js`, which would conflict with the `ecmascript` package. Renaming all the files to `.amd.js` or something would be funky.

Maybe there can be a new way to apply transforms to imported files? Or is there something already in place for that?

**Comment by benjamn** [comment]
So the AMD modules are published to npm? How does that work normally (outside of Meteor)?

**Comment by trusktr** [comment]
Famous 0.3.x lists the `deamdify` transform for Browserify usage in it's package.json, and it also has a bower.json for (likely) RequireJS users. Webpack users can benefit from Webpack's default support for AMD. Famous 0.3.x was designed purely for the browser. They switched to CommonJS at 0.5.

**Comment by stubailo** [comment]
Seems like this could be a great application of something like `cosmos:browserify`? Like if some packages have browserify-specific logic then maybe we should just use browserify, especially if it is older versions.

**Comment by trusktr** [comment]
The complication with is that if files are handled by `cosmos:browserify` (in the app), then the `cosmos:browserify` build plugin conflicts with `ecmascript`, which eliminates the ability to use Meteor 1.3 modules. This is `app` code in question, where I need to load AMD modules from `node_modules`. 

This is related to #5924.

**Comment by benjamn** [comment]
Is there a well-known `package.json` property that we should be paying attention to in order to determine how to transform files in `node_modules` directories?

**Comment by trusktr** [comment]
@benjamn The `browserify` property is the only one I can think of, specific to Browserify, and is package-developer-centric because package developers specify the needed transforms of a package (in package.json) instead of the app developer, as opposed to Webpack's app-developer-centric approach where the app dev must specify all transforms for everything in the app (including NPM modules, if any) in the app's Webpack config. JSPM reads the optional `format` property to determine the module format of a package (otherwise it tries to guess automatically).

Besides that, I don't think there's anything generic to NPM for that purpose (at least not that I've seen before).

**Comment by avital** [comment]
We're not going to support an in-core way to transform files inside of `node_modules`.

**Comment by avital** [comment]
I think this is outside of the scope of Meteor core. And so far looks like exactly one person cares about this. We can reconsider if this because a common request.
