### ISSUE TITLE
No build machines are available for Mac

### ISSUE THREAD

**Issue by Sanjo** [meteor/meteor#5896]
Currently I get the error "Error from build farm: Sorry, no machines available now. Try again later. [try-again-later]" since two days. @ekatek

**Comment by timbotnik** [comment]
Is this when deploying an app via `meteor deploy`?

**Comment by Sanjo** [comment]
No, it's when I do `meteor admin get-machine os.osx.x86_64`, because I need to release a package with architecture dependent dependencies.

**Comment by avital** [comment]
Yes, you're right. Our build machines are down. We'll investigate. Thanks for the report.

**Comment by gchpaco** [comment]
I have bounced the mac farm node and `meteor admin get-machine os.osx.x86_64` works for me now.  @Sanjo could you see if things are resolved for you?

**Comment by Sanjo** [comment]
Yes, works. Thanks.
