### ISSUE TITLE
Cannot override Oauth._endOfLoginResponse

### ISSUE THREAD

**Issue by jdmswong** [meteor/meteor#5899]
Hi, I'm trying to override that method for my own package.  When I paste the ```OAuth._endOfLoginResponse``` function redefinition to my package and run, I get the error:
```
W20151228-21:48:32.051(0) (oauth_server.js:204) Error generating end of login response
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)
    at ServerResponse.res._renderHeaders (/home/vagrant/.meteor/packages/webapp/.1.2.3.7d83sr++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:69:27)
    at ServerResponse.writeHead (http.js:1149:20)
    at ServerResponse.res.writeHead (/home/vagrant/.meteor/packages/webapp/.1.2.3.7d83sr++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:75:22)
    at Object.OAuth._endOfLoginResponse (packages/metart_man/man_server.js:92:1)
    at middleware (packages/oauth/oauth_server.js:198:1)
    at packages/oauth/oauth_server.js:146:1

```

if my override completely replaces the original, why doesn't it run?  Where is the first set of headers being sent?

Thanks!

OAuth._endOfLoginResponse: 
https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/oauth/oauth_server.js#L381

**Comment by timbotnik** [comment]
This seems like an unsupported extension of internal functionality, could you describe your use case for us in a feature request?

**Comment by jdmswong** [comment]
I was creating an Oauth server in Meteor in the style of accounts-facebook, accounts-github, etc; but it was failing and I couldn't tell why.  Since errors are handled and passed through the Oauth flow I had to track it down myself by overriding a variety of internal functions and following the flow.  The error ended up being that the secret used to create the state parameter **was not** the same as the secret I was passing to launchLogin.  I later discovered that the two were being compared to each other down the line, and derailed the process.

My feature request would be to make this necessity clear somewhere, or build it into the system somewhere.  Thanks!

**Comment by adamgins** [comment]
@jdmswong I have aa similar issue. My code works when using "popup" but failed with the same error when using "redirect". Wondering if you can share an code of how you fixed this, please?

I am calling an Oauth system that a) does not support `state` and b) uses a non standard `callback_uri` not `redirect_uri` I have tried to intercept the call coming back in and add in `state` myself, as Meteor does not handle with out it.
