### ISSUE TITLE
Public image path does not work in deploy for png?

### ISSUE THREAD

**Issue by DirkStevens** [meteor/meteor#590]
All my images are in a public/img folder.

This markup displays the image just fine:
<img src="img/iminds.png"></img>

When I look in the resources, the iminds.png is listed in the images.
When I check the network, the iminds.png is served as a text/html ?!
Another image that is used in the CSS and also is in the public/img folder is served properly:
![Image problem](https://f.cloud.github.com/assets/1837524/44012/bd55836a-56a6-11e2-9da1-c740e2fa3d13.png)

**Comment by Toro2018** [comment]
I just encountered the similar problem, all my jpg files are in the folder img and have the uppercase extension JPG. After I deployed all the files to the gh-pages, all the 'get' request get a 404 error and the img folder does not exist in the source.  I read your hint and modified the file extension cases, now everything works fine!
