### ISSUE TITLE
Issues using 1.3 beta2 and react-bootstrap

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#5904]
Attempting to use react-bootstrap 0.28.1, I encounter the following issues:

`import {Button} from "react-bootstrap"` fails, claiming it can't find the react-bootstrap module. I have to qualify it with `"react-bootstrap/lib"` to pick up lib/index.js. This is despite the apparent presence of a `main` field in package.json.

When I do import from the main module, I get the following error:

```
[39m
[34mW20151229-12:13:52.987(-6)? (STDERR) [39m[35m/home/nolan/.meteor/packages/meteor-tool/.1.1.11-modules.3.3ym4zh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245[39m
[34mW20151229-12:13:52.987(-6)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20151229-12:13:52.987(-6)? (STDERR) [39m[35m						      ^[39m
[34mW20151229-12:13:53.202(-6)? (STDERR) [39m[35mTypeError: Cannot read property 'bool' of undefined[39m
[34mW20151229-12:13:53.202(-6)? (STDERR) [39m[35m    at meteorInstall.app.node_modules.react-bootstrap.lib.PanelGroup.js (app/node_modules/react-bootstrap/lib/PanelGroup.js:31:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at meteorInstall.app.node_modules.react-bootstrap.lib.Accordion.js (app/node_modules/react-bootstrap/lib/Accordion.js:13:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)[39m
[34mW20151229-12:13:53.203(-6)? (STDERR) [39m[35m    at meteorInstall.app.node_modules.react-bootstrap.lib.index.js (app/node_modules/react-bootstrap/lib/index.js:25:1)[39m
[34mW20151229-12:13:53.204(-6)? (STDERR) [39m[35m    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)[39m
[34mW20151229-12:13:53.204(-6)? (STDERR) [39m[35m    at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)[39m
[34mW20151229-12:13:53.205(-6)? (STDERR) [39m[35m    at meteorInstall.app.lib.alexandria.jsx (/home/nolan/Projects/Alexandria/.meteor/local/build/programs/server/app/app.js:48:23)[39m
=> Exited with code: 8
```

I don't see this error when requiring react-bootstrap in different contexts.

Thanks.

**Comment by avital** [comment]
Apparently this happens because Meteor's new module system doesn't expose `global` as does Node, Browserify and Webpack.

**Comment by avital** [comment]
Sounds like a workaround could be just adding `global = {}` before the first `import` or `require` directive.

**Comment by avital** [comment]
(Though it seems like the stack trace reported here was due to a different problem, which is now fixed on the release-1.3 branch)

**Comment by ndarilek** [comment]
Has this fix been released yet? Where is a good place to watch for new 
betas? Are they documented at #5788 when available?

Thanks.

**Comment by avital** [comment]
This fix hasn't been released yet, but you can follow [these instructions](https://github.com/meteor/meteor/#slow-start-for-developers) to run from the release-1.3 branch directly.

We'll comment here and on #5788 when `1.3-modules-beta.3` is released.

**Comment by avital** [comment]
Should be fixed with https://github.com/meteor/meteor/commit/b7907a2d171f62df25410500e56c31223c6c74cd.

Will come out later today as part of `1.3-modules-beta.3`.

**Comment by avital** [comment]
`1.3-modules-beta.3` was just released.
