### ISSUE TITLE
[Question] Mongo.Collection._rewriteSelector setting id to random?

### ISSUE THREAD

**Issue by awei01** [meteor/meteor#5905]
Reference: https://github.com/meteor/meteor/blob/353e8e3a4a2cc96a10f360e26c0636166c3b163e/packages/mongo/collection.js#L359

I understand that when there is no selector passed or if the `_id` is falsey that we don't want to select any records. But why the implementation of setting the selector to `{ _id: Random.id() }`? Why not just set it to `{ _id: false }` or `{ $and: [{ _id: 1 }, { _id: 2 }] }` or some other selector where we can ensure that no records will be returned? Using `Random.id()` will create a new subscription and may cause inadvertent reactive behavior. Also, while the possibility of randomly selecting an existing id may be astronomically slim, it is still a possibility. 

Admittedly, my own use case is a very edge case, but I ran into an issue when I was checking `subscription.ready()` in a reactive function which then resubscribed to the subscription. This resulted in an endless loop as I'm essentially subscribing to a new random id every time.

**Comment by zol** [comment]
Hey @awei01 - our forums would be better suited for this type of question. Please ask over at http://forums.meteor.com

**Comment by awei01** [comment]
Ok, thx. For anyone else is curious, moved thread here: https://forums.meteor.com/t/question-mongo-collection--rewriteselector-setting-id-to-random/15889
