### ISSUE TITLE
[Mobile]: WebRTC/getUserMedia: Unsecure origin

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5907]
As Google announced about 1 year ago, the access to navigator.getUserMedia() will be locked for unsecure origins. In case of the Meteor Cordova integration, a warning will be shown if I try to access the camera when I use the Crosswalk plugin. The main problem is that Meteor runs the local server under "http://meteor.local", which is a unsecure origin. Are there any further fixes for that upcoming problem? Current Crosswalk version only prints a warning, but the latest Chrome version now blocks access from unsecured origins, so I think we will run into that problem on the next Crosswalk release.

    getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.”

**Comment by timbotnik** [comment]
Thanks for the issue report.  There are some other issues related to using `http://meteor.local` such as #5779, we should investigate further.

**Comment by dnish** [comment]
@timbotnik Ah okay, switiching over to "localhost" in 1.3 should fix that problem.

**Comment by martijnwalraven** [comment]
Indeed, `localhost` should be considered a secure origin even without HTTPS.

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3 beta (see https://github.com/meteor/meteor/issues/6050).
