### ISSUE TITLE
Improve error message for conflicting file handlers

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5911]
This error message:

> conflict: two packages included in the app (templating and peerlibrary:blaze-components) are both trying to handle *.html

Does not really help you a lot because many packages `imply` `templating`, so it is unclear which package exactly you have to remove. See [this list here](https://github.com/peerlibrary/meteor-blaze-components/issues/111#issuecomment-168109852). `templating` is not there, but it is still been complained about.

**Comment by mitar** [comment]
The issue is that some packages are implying other packages. See [here](https://github.com/orionjs/orion/pull/381).

It seems that this support for multiple handlers for the same `*html` file is probably problematic.

**Comment by stubailo** [comment]
Yikes. I'd say that for almost all packages, implying templating is a bug. I don't know how we could specify a better error message there, without rewriting a lot of constraint solver logic or something.

Perhaps we could have a way to determine which package is loading templating for you, by displaying some sort of tree visualization of dependencies.

**Comment by mitar** [comment]
> Yikes. I'd say that for almost all packages, implying templating is a bug.

I would not agree. Even Blaze Components were implying `templating` in the past. So that you could just add Blaze Components to your package and then use it and add HTML files to your package. Requiring one to add one extra sibling dependency is a bit strange. The idea should be that the package can define all dependencies you need to use it properly. Currently you have to imply `templating` if you want to make a package which uses HTML templates.

**Comment by stubailo** [comment]
What if the person using your package wants to use a different HTML handler? Like in this exact case? I'd say a package that uses React implying JSX would be an anti-pattern.

**Comment by mitar** [comment]
No, I would say that probably there should be three packages, a package which implies HTML handler, and another which does not, and the handler itself.

**Comment by mitar** [comment]
> What if the person using your package wants to use a different HTML handler?

In the case of Blaze Components that is not supported. Or that HTML handler would have to additionally extend Blaze Components HTML handler.

**Comment by stubailo** [comment]
I see, I guess in that case the only option would be to remove Orion or whatever is causing the conflict.

**Comment by mitar** [comment]
Of course, the main issue is that it is not really possible to extend `templating` package. In fact, the only thing I do, is add [an extra file](https://github.com/peerlibrary/meteor-blaze-components/blob/master/package.js#L20) (and make it run on the server side).

**Comment by chompomonim** [comment]
> I see, I guess in that case the only option would be to remove Orion or whatever is causing the conflict.

Are you serious? And what if in the app there are already a lot of places where orions stuff is used? And a lot places where BlazeComponents are used. Rewrite the app? Seriously? 
I think that's not right way if it's impossible to extend `templating` package.

**Comment by stubailo** [comment]
I mean, factually it is currently the only option. We could create other options by adding new features to the Meteor build tool. Right now, every build plugin identifies its files by the file extension, so it is literally impossible to have two build plugins compile files with the same extension.

**Comment by stubailo** [comment]
One option is to split your app into packages, because you could compile one package with `templating` and one with the Blaze Components thing. Another option would be to have packages not complete over the `.html` file extension, and have, for example, `.sb.html` for spacebars, or `.bc.html` for Blaze Components.

**Comment by mitar** [comment]
So probably most of the other packages imply `templating` so that users can use `Template` in the code without having to include and extra package. So in the case of Orion probably removing imply is an OK option.

But this is really not something which should really be done better. The whole point of a toolchain is around processing files. If you really want people to develop preprocessors, postprocessors and similar other stuff, then it is really important that it is possible to hook into that in a better way. Maybe #5552 should be reopened.

For starters, it would be really easy if a package could redefine an existing build plugin. So, instead of two packages fighting over `*.html` files, a package could define what to do if there is another package which is already handling them.

**Comment by mitar** [comment]
@stubailo, what about something like #5936? If we allow access to plugins, then I could do something like:

```javascript
var plugin = Plugin._getCompilerByExtension('html');
if (plugin) {
  delete plugin.archMatching;
  var originalFactoryFunction = plugin.factoryFunction;
  plugin.factoryFunction = function () {
    // Patch stuff.
    return originalFactoryFunction();
  }
}
else {
  Plugin.registerCompiler({
    extensions: ['html'],
    isTemplate: true
  }, () => new CachingHtmlCompiler(
    "blaze-components-templating",
    TemplatingTools.scanHtmlForTags,
    TemplatingTools.compileTagsWithSpacebars
  ));
}
```

The only issue is that I do not know if my [patching](https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js) of dependencies will really work because it seems plugins load modules separately. But maybe if I would call all that patching inside the `factoryFunction` it could work. I do not know.

**Comment by stubailo** [comment]
Oh, I see - you want to do this in the build plugin itself?

Is the idea that you want to override the plugin, but only for certain files? I'm not really sure what the code is trying to do.

**Comment by avital** [comment]
I don't think we should expose internals of plugin objects where the pattern you describe above becomes the best practice.

Also your described solution would have a different behavior based on the order in which build plugins are loaded.

I actually think this is a very minor problem. While I agree that it's hard to find which package implied templating to remove it, I think that's where the issue ends. In reality, packages shouldn't imply templating. If they do, then they are definitely incompatible with any other packages that define a build plugin on `.html` files. Once you write part of your app with `.html` files and it works, that part should not stop working because you added some other package that changes how `.html` files are compiled.

The solution is to get whatever package that implies templating to no longer imply templating. Or if they really want to, have two packages -- one just for the core, which only uses templating and another that implies templating.

**Comment by mitar** [comment]
> Is the idea that you want to override the plugin, but only for certain files? I'm not really sure what the code is trying to do.

In my particular case I just patch few methods because most of the `templating` plugin is exactly what I need in Blaze Components anyway. So I just [patch some methods](https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js). But in general this change allows a plugin to detect that some other plugin is trying to handle its extension and adapt the behavior. So before you blindly register a plugin, you can check if plugin already exists. Maybe then you do not register anything, maybe then you replace that plugin. Or patch it, or chain it, or whatever.

**Comment by hwillson** [comment]
Reading over this issue thread, it doesn't seem like there is much we can do to move this forward (the proposed solution hasn't received much buy-in). There are workarounds, so due to the lack of recent activity on this issue, I'll close it for now. Thanks!
