### ISSUE TITLE
HTML files with <head> tags shuld be added to the server side target

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5913]
It is a bit strange. Currently, HTML files with `<head>` tags are added for web target, but then they are rendered by the server and never really send to the client. This makes it tricky to create templates which can work both on the client and server side.

**Comment by stubailo** [comment]
So you want to send the `<head>`contents to the client? I'm not sure what the intended outcome is.

**Comment by mitar** [comment]
No, I am saying that currently file with `<head>` tags have to be added to the `client` target with `addFiles`, but they are not send to the client, but rendered on the server. This is a bit confusing. It is confusing even more if you do want to support `<head>` on the server side as well. So that server side renders `<head>` and then client side could dynamically change it.

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#167; this issue can be closed. Thanks!

**Comment by mitar** [comment]
Hm, this might require some changes to Meteor toolchain, I would guess.

**Comment by mitar** [comment]
Let's close it for now and we can then ask MDG to help in Meteor if needed.

**Comment by hwillson** [comment]
Sounds like a plan - thanks @mitar!
