### ISSUE TITLE
Ability to reset local cache used by Meteor during builds

### ISSUE THREAD

**Issue by austinkettner** [meteor/meteor#5918]
When using packages such as https://github.com/mquandalle/meteor-bower among others, there are many libraries being imported, downloaded, installed, and used per build. In some scenarios I have found removed packages are still served by Meteor despite the package (Bower as one example) distinctly removing it and verbosing showing this in the log. It seems wherever Meteor is storing the built app, it is too aggresively caching directories such as /app/packages and with no ability to force a reset of all local files, the only solution is to delete the entire folder and reclone/etc.

There is a `meteor reset` command, but to my knowledge only affects the local DB. Furthermore, being able to supply args would be fantastic. Example being: `meteor reset --database` or `meteor reset --filecache`.

**Comment by zol** [comment]
It's most likely the meteor-bower package itself contains a bug to do with removed packages. You can simply remove the `.meteor/local` folder to reset the file cache.

**Comment by avital** [comment]
Note: Delete `.meteor/local/bundler-cache`, not `.meteor/local` (which also contains your app's database)
