### ISSUE TITLE
install fails on OSX / el capitan / 'operation not permitted'

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#5919]
it seems El Capitan introduced some changes and I'm getting the error below on trying to do a fresh meteor install

relevant links:

https://developer.apple.com/library/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html

http://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled

```
curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6674    0  6674    0     0   5633      0 --:--:--  0:00:01 --:--:--  5636
Removing your existing Meteor installation.
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
Password:
cp: /usr/local/bin/meteor: No such file or directory

Couldn't write the launcher script. Please either:

  (1) Run the following as root:
        cp "/Users/dc/.meteor/packages/meteor-tool/1.1.10/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.

Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.

➜  app git:(master) sudo         cp "/Users/dc/.meteor/packages/meteor-tool/1.1.10/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
cp: /usr/bin/meteor: Operation not permitted

```

**Comment by dcsan** [comment]
from stackoverflow

----
Nvm. For anyone else having this problem you need to reboot your mac and press cmd+r when booting up. Then go into utilities > terminal and type the following commands:

csrutil disable
reboot 
and everything will work.

This is a result of System Integrity Protection. More info here.

**Comment by avital** [comment]
This is actually interesting. We may need to change Meteor's install script if this is the new default on Mac OS X...

**Comment by avital** [comment]
We could do something where if `sudo` fails with "Operation not permitted" we just move on instead of failing (and make sure we set the PATH to where Meteor was installed locally)

**Comment by siegesmund** [comment]
Getting the same error with a fresh install, also on El Capitan.

**Comment by abernix** [comment]
@avital I'm curious if a change wasn't made to fix this already, because even with with the new System Integrity Protection, `/usr/local/` is [supposed to be fair game according to these Apple SIP docs](https://support.apple.com/en-us/HT204899).

**Comment by o1lab** [comment]
a fine satday evening to learn meteor - and ended up struggling to install it..

**Comment by abernix** [comment]
@o1lab Can you provide details on what the problem was _specifically_ that you were encountering?  I haven't seen anyone complain about this particular issue in a long time and I was about to close this issue.

**Comment by photusenigma** [comment]
I've just run into this too.  On El Capitan OSX 10.11.6

```
>$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0  23469      0 --:--:-- --:--:-- --:--:-- 23516
Removing your existing Meteor installation.
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.4.2 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
Password:
cp: /usr/local/bin/meteor: No such file or directory

Couldn't write the launcher script. Please either:

  (1) Run the following as root:
        cp "/Users/dc9/.meteor/packages/meteor-tool/1.4.2/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.

Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
>$ sudo cp "/Users/dc9/.meteor/packages/meteor-tool/1.4.2/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
cp: /usr/bin/meteor: Operation not permitted
```

**Comment by abernix** [comment]
@photusenigma Thanks for reporting this.  Could you please run the following three commands and show their output:

```
ls -lad /usr/local/ /usr/local/bin
```

```
whoami
```

```
sudo cp "/Users/dc9/.meteor/packages/meteor-tool/1.4.2/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/local/bin/meteor
```

**Comment by photusenigma** [comment]
@abernix  sure!
```
MBP2:~ dc9$ ls -lad /usr/local/ /usr/local/bin
drwxr-xr-x   25 root  wheel   850 Oct 28 13:24 /usr/local/
drwxrwxr-x  196 root  admin  6664 Nov  3 13:38 /usr/local/bin
```

```
MBP2:~ dc9$ whoami
dc9
```

```
MBP2:~ dc9$ sudo cp "/Users/dc9/.meteor/packages/meteor-tool/1.4.2/mt-os.osx.x86_64/scripts/admin/launch-meteor" /usr/local/bin/meteor
cp: /usr/local/bin/meteor: No such file or directory
```

**Comment by photusenigma** [comment]
Side note:  Looks like there's an already an alias that wasn't removed during the recent install attempt yesterday.   Alias looks to be from 2+ months back.  Could that be our culprit?  Going to try clearing it out and try last command again.

```
MBP2:~ dc9$ ls -lha /usr/local/bin/meteor
lrwxr-xr-x  1 dc9  admin    47B Aug 16 19:17 /usr/local/bin/meteor -> ../lib/node_modules/meteor/app/meteor/meteor.js
```

**Comment by abernix** [comment]
Ah hah!  That very likely could be the problem!  Our of curiosity, how was that installation attempted?  Did you `npm install meteor -g` or something? (Which won't work, btw).

(Although, as a second problem, it does look like the "manual text" install instructions from the installer are incorrectly recommending that you try copying the launcher to `/usr/bin` which would no longer work on El Capital due to Apple's new [System Integration Protection](https://support.apple.com/en-us/HT204899), but you never really should have saw those instructions unless Meteor wasn't able to put the link at `/usr/local/bin/meteor`)

**Comment by photusenigma** [comment]
I think I may have, and it looks like that was our issue.

Was able to get through a full install by doing the following:
```
MBP2:~ dc9$ rm -Rf /usr/local/bin/meteor
MBP2:~ dc9$ rm -Rf ~/.meteor/
```

Re-ran the meteor curl install, and looks like I got a nice clean install.   Fingers crossed, but looks like success!
```
MBP2:~ dc9$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0  10610      0 --:--:-- --:--:-- --:--:-- 10619
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.4.2 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

MBP2:~ dc9$ 
```

**Comment by abernix** [comment]
Glad that worked for you.  I'll see about proposing a couple changes to the installer to make that more intelligent about dealing with issues like that in the future (or at least giving a more sensible error message).

Thanks for your help in debugging it!

**Comment by uuunk** [comment]
FWIW, had the same issue and @photusenigma cleanup commands worked for me as well:
```
rm -Rf /usr/local/bin/meteor
rm -Rf ~/.meteor/
```

**Comment by hwillson** [comment]
Since this cause of this issue has been tracked down, and there is an acceptable workaround (and anyone else having this issue will find this workaround by searching across the GH issues), I'll close this issue off. Thanks for reporting this originally!

**Comment by sgentile** [comment]
Would be nice to add this to the notes on installing meteor outside of needing to search through github issues...

**Comment by hwillson** [comment]
What would you recommend adding @sgentile? It looks like the issue was that the Meteor installation was attempted by calling `npm install meteor -g`, which isn't supported (and isn't mentioned anywhere in the installation instructions). I'm not sure if adding a message to the installation instructions to say "don't try installing with `npm install meteor -g`" would help much; there are a lot of other ways people shouldn't try to install Meteor, so the installation docs could become quite large with many "dont's". Regardless, let me know what you're thinking - doc changes are best requested in other repos ([docs](https://github.com/meteor/docs), [guide](https://github.com/meteor/guide), etc.) so I think this issue is still safe to keep closed. Thanks!

**Comment by sgentile** [comment]
Good point - npm is such a common way today to install cli tools that I
guess my first question is why isn't npm install supported ?

**Comment by hwillson** [comment]
> why isn't npm install supported ?

Hehe - that's [a topic for another day](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm). It will be maybe/definitely someday! 🙂

**Comment by navardan** [comment]
I had the same issue on Sierra 10.12.4 and @photusenigma cleanup commands worked. Thanks.

rm -Rf /usr/local/bin/meteor
rm -Rf ~/.meteor/

**Comment by surmistry** [comment]
> Hehe - that's a topic for another day. It will be maybe/definitely someday! 🙂

Or maybe reach out to npm to see who is currently utilizing `npm i meteor` and see if you can work something out for the people that tl;dr _really badly_ when it comes to npm packages :joy: @hwillson

**Comment by hwillson** [comment]
@surmistry Ha - I wish getting a specific package name on npm was the only thing holding Meteor up from being npm installable ... that would be a slightly easier issue to deal with than the hundreds / thousands of hours of design, development, testing, etc. that needs to be done to make this happen ... 🙂.

For what its worth, we have reached out to the current https://www.npmjs.com/package/meteor owner. They aren't interested in giving up the name, so MDG has procured the [`@meteorjs` namespace](https://www.npmjs.com/org/meteorjs/) instead (right now it just holds the `eslint-config-meteor` package).

**Comment by EranHr** [comment]
Had the same problem. Tried for hours brew uninstall / install. Tried "ln -s /usr/bin/nodejs /usr/bin/node" and chown. Nothing helped. 

Only installing node using it's GUI installation package: https://nodejs.org/en/download/
