### ISSUE TITLE
[1.3-modules] Support for AMD modules.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5924]
I'm wondering how this will be handled in Meteor 1.3. The advantage of Webpack is that things like AMD modules already work with Webpack (and hence with my package `rocket:module`).

I was thinking that perhaps a build plugin could convert AMD to CommonJS, but there's one problem with this: what if the library wants to use ES2015 language features, but the module system is AMD? Does the build plugin also have to handle ES2015 language features (for example with Babel) instead of the `ecmascript` package? This would be duplication of efforts.

I need to use some AMD libraries (maybe the devs will eventually update to ES6 modules, but for now their libraries are AMD), and I really want to keep Meteor 1.3, but I feel that the easiest solution for me might be to just go back to using `rocket:module` because it just works (although not as fast as `modules`, and I can simply

``` js
import something from 'an-AMD-library'`
```

and continue deving.

I think this is an important issue that Meteor 1.3 should address.

For now, I'll need to use `rocket:module` instead of `modules` on one project because I need to just get to deving, although I'd really love to use `modules`.

@benjamn Any thoughts on this?

**Comment by AddoSolutions** [comment]
I would add to that, I really need to be able to use AMD as well.

```
import SomeObject from '../lib/SomeObject'
```

It seems a bit odd to not support AMD at all, nor is there any way really to do so.

I suppose even a plugin for babel would work.

**Comment by trusktr** [comment]
I think perhaps Meteor needs a slight re-design of plugins so that a given file can be processed by more than one plugin (similar to Babel 6). Then, we'd add the plugins we need. For example, we might add `ecmascript` for syntax and `amd` for AMD module support. Both plugins would operate on the same file in some order. If `amd` went first, it would simply convert the AMD modules to CommonJS, leaving everything else intact. Then `ecmascript` would go and convert the ES2015 features to ES5. Similarly, if one wanted to write in CoffeeScript and use AMD modules, the `coffeescript` package would (somehow) process the file first, converting everything to JavaScript, then `amd` would go through and convert AMD modules to CommonJS so that meteorInstall could finally work with the files.

**Comment by avital** [comment]
What's an example of a library that supports AMD and not CommonJS?

**Comment by trusktr** [comment]
There's a [bunch on GitHub](https://github.com/search?l=javascript&q=define+function&ref=searchresults&type=Code&utf8=%E2%9C%93). There's probably more in the Bower registry. [Famous 0.3](https://github.com/Famous/famous) is written with AMD.

**Comment by trusktr** [comment]
cc @benjamn 

The following are the two types of AMD modules people commonly use. The first list dependencies in the first array argument a `define` call, and names the import in the following function argument:

```js
define(['jquery', 'lodash'], function($, _) {
  // use $ and _ here.
})
```

The second form is call to `define` with a single function argument, passing in require, in which case the inside of the function is like CommonJS:

```js
define(function(require) {
  const $ = require(`jquery`)
  const _= require('lodash')
})
```

I think it might be nice for Meteor to handle those two cases, and throw an error in other cases that use the runtime (non-staticly-analyzable parts) that are incompatible with ES2015 Modules.

**Comment by trusktr** [comment]
@benjamn Could you provide some guidance as to where/how I might implement this for Meteor 1.3? I might like to make a PR for this one.

Namely, how would we handle ES language features (normally handled by `ecmascript`) as well as converting AMD modules to CommonJS (not handled by `ecmascript`, but AMD modules may have language features that should be handled by `ecmascript`)

**Comment by ramijarrar** [comment]
Are there still any plans for this?

**Comment by abernix** [comment]
@trusktr I think this is no longer relevant too?  Please, if you have a second to go through some of your still-[open issues](https://github.com/meteor/meteor/issues/created_by/trusktr) and close anything that was only relevant at the time or is now resolved, it would be most appreciated!  Thanks!

**Comment by ramijarrar** [comment]
Not sure why it wouldn't be relevant? 

Meteor still doesn't support loading AMD modules in the latest release (e.g the [Microsoft Application Insights SDK](https://github.com/Microsoft/ApplicationInsights-JS) is incompatible with Meteor at the moment due to being AMD-only)

**Comment by abernix** [comment]
@ramijarrar I should have clarified.  I'm not sure I agree that the burden of supporting both AMD _and_ CommonJS should be on the build system.  It's generally up to a library to choose what environments it wants to support (configurable via various `package.js` settings, like `engines`) and most large libraries provide support for both CommonJS and AMD.

As you're involved in it, you'll know that there is [an issue open](https://github.com/Microsoft/ApplicationInsights-JS/issues/301) with Microsoft where they are considering CommonJS soon.  Given a push toward ES6 modules and what I've felt is a decline in the popularity of AMD, I'm suggesting that this may no longer be relevant for the future.  In other words, I don't know that this feature would get attention over other features in time for it to be relevant and a benefit to a majority of Meteor developers.

**Comment by hwillson** [comment]
For the reasons outlined in https://github.com/meteor/meteor/issues/5924#issuecomment-267955433 (push towards ES6 modules, industry-wide waning support for AMD, etc.), as well as a general lack of support (+1's) for this feature request, I'll close it for now. If for some reason adding AMD support becomes more important/critical, we can always re-open, but for now I think it's safe to assume this isn't something that is going to gain much traction or be worked on. Thanks for suggesting this idea originally!

**Comment by trusktr** [comment]
The solution might be to make a build plugin that converts define() calls
to the format that meteor understands.
