### ISSUE TITLE
Exclude force-ssl (https) on some urls?

### ISSUE THREAD

**Issue by digz6666** [meteor/meteor#5927]
**_1 Upvote**_ I use force-ssl with https://atmospherejs.com/cfs/http-methods package and I don't want to use SSL on these custom http methods. Is there any way to exclude some URLs to not use SSL?

**Comment by stubailo** [comment]
I think the easiest way to achieve this would be to create your own fork of force-ssl in your app, and have some sort of regex to filter URLs. Out of curiosity, why don't you want SSL on your API methods?

**Comment by digz6666** [comment]
@stubailo Thanks for the suggestion, I'm integrating with local telecom operator SMS gateway to receive SMS but 2 of 4 operators failed to send request to HTTPS, but HTTP works. Their tech support is so bad to resolve the issue, so I'm returning back to HTTP.

Where can I fork force-ssl from? There's no github link on https://atmospherejs.com/meteor/force-ssl

**Comment by digz6666** [comment]
@stubailo Ah nevermind, I found it here: https://github.com/meteor/meteor/tree/devel/packages/force-ssl

**Comment by stubailo** [comment]
Yep, that's the one! You can just put it in your app's `packages` directory. In the meantime I'll keep this open as a feature request.

**Comment by digz6666** [comment]
@stubailo Thanks for helping, it works fine. I added following line to quickly exclude some requests.
```javascript
  // dont' apply SSL to SMS API
  var isExcept = req.url.indexOf('/api/sms') == 0;

  if (!isLocal && !isSsl && !isExcept) {
    // connection is not cool. send a 302 redirect!

    var host = url.parse(Meteor.absoluteUrl()).hostname;

    // strip off the port number. If we went to a URL with a custom
    // port, we don't know what the custom SSL port is anyway.
    host = host.replace(/:\d+$/, '');

    res.writeHead(302, {
      'Location': 'https://' + host + req.url
    });
    res.end();
    return;
  }
```

By the way If someone make quick implementation and do a pull request, what's the best place to store configuration to exclude some URL paths?

**Comment by stubailo** [comment]
Hmm, I can think of three options:

1. Environment variable - I don't like this one, and it doesn't make sense that you would want different environments to ignore different URLs or something.
2. Meteor settings - this seems OK, but I can't think of other packages that expect settings to be passed?
3. Runtime configuration by exporting something like `ForceSSL.ignorePaths(...)`, this is more consistent with what other packages do, but might be overkill for something this simple.

What do you think?

**Comment by digz6666** [comment]
@stubailo I prefer settings.json, I saw that some packages use it.
For example following google analytics stores analytics key in settings.json:
https://atmospherejs.com/okgrow/analytics

**Comment by stubailo** [comment]
yeah, that looks fine, I would do it like this though:

```js
{
  "force-ssl": {
    "excludeUrls": {
      "/api/sms",
      "/api/news"
    }
  }
}
```

1. Seems more reasonable to namespace by the actual package name
2. Probably shouldn't be in `public` since the redirection is done on the server, except for the Meteor.absoluteUrl hook, but that doesn't seem worth it to expose the URL to the client?

**Comment by digz6666** [comment]
@stubalio I agree with you. Include namespace and store it in private.

**Comment by stubailo** [comment]
I think @avital would be the best to prioritize this and suggest whether a PR is appropriate.

**Comment by alpjor** [comment]
+1

**Comment by v3rron** [comment]
Actually I think environment variable would be the best fit for all. My use-case is that I use force-ssl on my production server. My whole app is served through https, I bought Positive SSL Certificate for this one. 
But I also setup a staging server with staging.myapp.com domain which doesn't support SSL since Wildcard Certicate is much more expensive. 
Currently I have to remove force-ssl package manually every time I upload the app to staging server.
It would be nice to just add some environment value to `settings.json`, something like:
````
{
  "force-ssl": {
    "only": {
      "www",
    },
    "except":{
      "staging",
    }
  }
}
````

**Comment by sferoze** [comment]
@v3rron I am having the same issue. I purchased a single domain SSL certificate, and have to manually remove force SSL each time I update the demo, or staging sites. 

Any update on an easy way to bypass force ssl via meteor settings or something

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Exclude%20force-ssl%20(https)%20on%20some%20urls%3F&body=Migrated%20from:%20meteor/meteor%235927) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
