### ISSUE TITLE
Ability to set different App.info.id for iOS vs Android

### ISSUE THREAD

**Issue by Alveoli** [meteor/meteor#5929]
Hi, a feature request here.  I guess a lot of people also have a iOS app Bundle ID not the same as their Android app's Package Name.  Can we have a way to configure this from `mobile-config.js` please?

Originally from here: https://forums.meteor.com/t/different-app-info-id-for-ios-vs-android/15228

Thanks.

**Comment by cunneen** [comment]
I've made a change that allows this, but my change seems to break the app id if you DONT specify the android-specific and ios-specific keys (in which case you end up with something like ```com.idifupyk7qhnh12puw9t```. I'm hitting a dead end in figuring out where the app id comes from in the normal case. 

My change is [literally only 4 lines. Take a look here.](https://github.com/meteor/meteor/compare/devel...cunneen:fix-5929?expand=1)

Perhaps you could take a look and see if anything jumps out at you, @martijnwalraven and/or @stubailo ?

Test:

```sh
# create meteor project
./meteor/meteor create test
cd test

# create a mobile-config.js file
echo "
// This section sets up some basic app metadata,
// the entire section is optional.
App.info({
  id: 'com.example.matt.uber',
  name: 'über',
  description: 'Get über power in one button click',
  author: 'Matt Development Group',
  email: 'contact@example.com',
  website: 'http://example.com',
        'android-packageName': 'com.example.matt.uber.android',
      'ios-CFBundleIdentifier': 'com.example.matt.uber.ios'
});

// Set up resources such as icons and launch screens.

// Set PhoneGap/Cordova preferences
App.setPreference('BackgroundColor', '0xff0000ff');
App.setPreference('HideKeyboardFormAccessoryBar', true);
App.setPreference('Orientation', 'default');
App.setPreference('Orientation', 'all', 'ios');

" > mobile-config.js

# add mobile platforms
../meteor/meteor add-platform ios android

# build cordova app
../meteor/meteor build ../build-output --server=https://example.com

```

results in:

```xml
    <key>CFBundleIdentifier</key>
    <string>com.example.matt.uber.ios</string>
```

in the iOS application's plist, and:

```xml
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.example.matt.uber.android" xmlns:android="http://schemas.android.com/apk/res/android">
```

In the android manifest.

Take out the two lines from mobile-config.js and run it again, you end up with :

```
    <key>CFBundleIdentifier</key>
    <string>com.idifupyk7qhnh12puw9t</string>

```

and

```xml
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.idifupyk7qhnh12puw9t" xmlns:android="http://schemas.android.com/apk/res/android">
```

**Comment by ElegantSudo** [comment]
@stubailo @martijnwalraven what happened to this?

**Comment by ElegantSudo** [comment]
@cunneen how can I implement that into my own app?

**Comment by abernix** [comment]
Currently both `android-versionCode` and `ios-CFBundleVersion` are set to `buildNumber` that is specified with `App.info` in `mobile-config.js`.  This was done per the reasoning in #4048.  The [Android versioning docs](https://developer.android.com/studio/publish/versioning.html) and the ones [for iOS](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364) seem to indicate that this is supposed to be an incrementing version number, not just the same (or similar) value as the App Id (e.g. `com.appname.ios`).  It doesn't seem to me that this field is meant to change the actual app ID.

Also, this (rather old) issue doesn't seem to be picking up much traction, so I'm not sure if the original claim in the forums that "Surely lots of other people have this problem." is proving to be true.  Without some solid information pointing to the contrary and a reason as to why you want/need different App Ids per platform, I believe this feature request is candidate for being closed.

**Comment by cunneen** [comment]
@abernix I don't think anyone is suggesting modifying the build number. 
Regarding "A reason as to why you want/need the different app IDs per platform", I think  @ElegantSudo and @Alveoli should be given the chance to respond. There are a lot of possible scenarios. Can you provide a solid reason why the app IDs and package names must always be identical across platforms?
In my case I had two existing apps that I wanted to replace with a meteor app. They had different app IDs.

**Comment by ElegantSudo** [comment]
@cunneen provides a good reason to want to have separate application ID's. Another is to be able to really easily identify and communicate to your team about the app that you're working with.

For example:
* `com.example.ios` and `com.example.android` are both much more clear than `com.example.app` for both iOS and Android.

This has become somewhat of a standard for lots of startups and companies who are using Cordova or other suites to develop apps for multiple operating systems.

**Comment by abernix** [comment]
Apologies, I completely misread `android-packageName` for `android-versionCode` and `ios-CFBundleIdentifier` for `ios-CFBundleVersion` when I was reading the [`config.xml` documentation](https://cordova.apache.org/docs/en/latest/config_ref/), so pardon my misstep there.

However that leads to the next question – while I think that @cunneen's reason above is perfectly valid, I find it strange that the documentation (again, see previous link) doesn't recommend this or even mention the configurability of those settings on a per-platform basis.

If someone can find some official perspective on the `config.xml` parameters (in order to ensure they aren't going to be deprecated, etc.), I'll find out if this can be a candidate for `pull-requests-encouraged`.

And if it does make it that far, it should of course only be an override and should default back to the `id` provided through `App.info({ ... }` in `mobile-config.js`.

**Comment by adrian-quince** [comment]
+1 for this feature. Until it comes out though, it is possible to use PlistBuddy on the Mac to write a separate bundle identifier for iOS.  Here's the syntax I used:

`/usr/libexec/PlistBuddy <path to project build>/project/<app name>/<app name>-Info.plist  -c 'set :CFBundleIdentifier <desired Bundle ID>'`

And here's an example, where the app name is MusiQuiz and the bundle ID is com.feedbaq.musiquiztest:

`/usr/libexec/PlistBuddy ~/Developer/CordovaBuilds/MusiQuizTest/ios/project/MusiQuiz/MusiQuiz-Info.plist  -c 'set :CFBundleIdentifier com.feedbaq.musiquiztest'`

**Comment by jdddog** [comment]
+1 for this feature

Thanks for the workaround Adrian!

**Comment by lcfm** [comment]
+1 for this feature

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Ability%20to%20set%20different%20App.info.id%20for%20iOS%20vs%20Android&body=Migrated%20from:%20meteor/meteor%235929) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by leemind** [comment]
I know its closed, but wanted to thank Adrian for that work-around!
