### ISSUE TITLE
Feature request for OAuth with accounts-password (at least)

### ISSUE THREAD

**Issue by Type1J** [meteor/meteor#5930]
***2 Upvotes*** First, here's some background: I'd like to quickly setup an OAuth server at several different (unrelated) companies. These servers would be to keep email/password combinations and are not accessible from outside of each of the companies' networks.

I'd like to make custom frontends for each in Meteor, and then have other Meteor apps (in different departments - read: places with different concerns, so not using the same data) all use that company's location's OAuth server for login credential validation.

This issue, then, is requesting a Meteor package that depends on accounts-password (at least, maybe other accounts-XXXX packages, but not required) that acts as an OAuth server that uses Meteor accounts to validate OAuth requests from other OAuth (possibly or possibly not Meteor) clients. A good name might be "accounts-oauth-server", or "accounts-password-server", but I have no preference.

This seems like a feature that would already exist for Meteor, but I couldn't find it in any packages. Please correct me, if I'm wrong.

**Comment by Type1J** [comment]
To be clear:

The Meteor clients to this server would NOT use accounts-password, but they would use accounts-oauth, or accounts package that depends on accounts-oauth.

**Comment by Type1J** [comment]
I did find this:
https://atmospherejs.com/rocketchat/oauth2-server
Please close, if it can't be made better.

**Comment by talha-asad** [comment]
+1

**Comment by kodamirmo** [comment]
+1

**Comment by vangorra** [comment]
I work for Prime8Consulting and we just finished writing an oauh2 client/server package for meteor. It lots of documentation and example applications that demonstrate how it works.

https://github.com/prime-8-consulting/meteor-oauth2

**Comment by Type1J** [comment]
@vangorra Thanks! I haven't tried it yet, but it looks like you've made the simplest to use package that I've seen so far. There's still a few raw HTTP requests in your examples, however. I think it could still be simpler (less boilerplate) by using settings to specify your resource server, for example.

An internal Meteor package would probably require only settings, and no other required boilerplate. That's what I'd be looking for here.

Again, I haven't tried it, yet, so I'm not sure if these are completely valid comments about the package, but I'm letting you know my first impression.

**Comment by Type1J** [comment]
@vangorra Ok, I've tried it out. Great job! I'll leave this open for @avital in case he had an idea for a MDG OAuth resource server/client, but if not, then this issue can be closed.

**Comment by avital** [comment]
Sounds like @vangorra built a great package. Closing this issue.
