### ISSUE TITLE
Feature request: 'hint' option for find() if using a Mongo cursor

### ISSUE THREAD

**Issue by bradvogel** [meteor/meteor#5932]
I'd like the ability to pass a 'hint' option to find when using a Mongo collection. See here: https://docs.mongodb.org/v3.0/reference/operator/meta/hint/

It's very common to use the `hint` optimization in large-scale Mongo apps.

**Comment by avital** [comment]
That'd be useful. We'd take a look at a pull request implementing this, but in the meanwhile you should be able to use [rawCollection](http://docs.meteor.com/#/full/Mongo-Collection-rawCollection) directly.

Unless this is something that's only available with newer version of the Mongo driver, in which you'd probably have to wait until we finish https://github.com/meteor/meteor/issues/5763

**Comment by wearhere** [comment]
Turns out that you can actually pass `$hint` to `Collection#find`, which is fine by me except for that you apparently then can't use `sort` in the `options`: http://stackoverflow.com/a/30916309/495611

**Comment by bradvogel** [comment]
Thanks! Would be great to have the above documented!

**Comment by arthurlataks** [comment]
Yet I still can't count results that match my query when using $hint. Maybe I'm doing something wrong...

`var totalCount = Meteor.users.find({ $query: searchQuery, $hint: indexType}).count();`

I end up receiving this exception:

`Exception while invoking method 'getSearchUserData' MongoError: exception: unknown top level operator: $query
I20160404-22:07:29.629(3)?     at Object.Future.wait (/Users/xxx/.meteor/packages/meteor-tool/.1.1.10.u899n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20160404-22:07:29.629(3)?     at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1059:1)
I20160404-22:07:29.629(3)?     at [object Object].Cursor.(anonymous function) [as count] (packages/mongo/mongo_driver.js:869:1)`

**Comment by faridblaster** [comment]
up

**Comment by nlhuykhang** [comment]
I don't think this is a Meteor issue. I tried below command in Mongo shell and I got error too:

```
db.users.find({
  $query: {
    _id: '...'
  },
  $hint: {
    _id: 1
  },
}).count()
```

**Comment by bpartridge** [comment]
If there's interest I can make this a package or pull request (both would require documentation), but for now we've found a way to monkey-patch Meteor's MongoInternals to allow you to pass a hint (and `maxTimeMS`, which goes hand-in-hand with hinting if your users are making queries that grind poor Mongo to a halt!) as a .find option, alongside sort/limit/fields. Should work with 1.2.1 thru 1.4.3.1, and it's currently being used in production.

Keep in mind that many Meteor packages make strong assumptions about what goes in `options`, so if you're using libraries that handle publications, you may need to patch those to pass the new options through. Hope this helps though!

```javascript
if (Meteor.isServer) {
  Meteor.startup(function() {
    var orig = MongoInternals.Connection.prototype._createSynchronousCursor;
    MongoInternals.Connection.prototype._createSynchronousCursor = function(cursorDescription, options) {
      var syncCursor = orig.call(this, cursorDescription, options);
      if (typeof cursorDescription.options.maxTimeMS !== 'undefined') {
        // modifies the _dbCursor itself...
        // so even though it is bound to other things in syncCursor, no need to re-bind
        syncCursor._dbCursor.maxTimeMS(cursorDescription.options.maxTimeMS);
      }
      if (typeof cursorDescription.options.hint !== 'undefined') {
        // same
        syncCursor._dbCursor.hint(cursorDescription.options.hint);
      }
      return syncCursor;
    }
```

**Comment by mitar** [comment]
I think allowing `hint` to be passed as an option should be a pretty straightforward change, as shown by a patch above. I think we should encourage a pull request for this. @hwillson, what do you think?

**Comment by hwillson** [comment]
Yes, I think so @mitar - sounds like a great addition! It looks like this was marked as `pull-requests-encouraged` a while back, so @bpartridge (if you're still interested) we'll definitely review a PR. Thanks!

**Comment by mitar** [comment]
Oh, I missed that. Great!

**Comment by bpartridge** [comment]
Definitely still interested in contributing this! Will aim for a PR by sometime next week.

**Comment by hwillson** [comment]
PR #8692 has been merged, so this functionality will be coming soon - thanks @bpartridge!
