### ISSUE TITLE
Local node_modules/underscore should take precedence over Meteor underscore package

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#5933]
As reported [here](https://forums.meteor.com/t/meteor-1-3-early-beta-now-available/14723/47?u=benjamn).

**Comment by nathan-muir** [comment]
Same issue as #5909 / #5915

**Comment by benjamn** [comment]
Related comment describing a follow-up change that will help with this issue: https://github.com/meteor/meteor/pull/5915#issuecomment-169501163

**Comment by avital** [comment]
To clarify, 	a6a5373 fixes this specific issue; but there still may be cases where you actually *want* Meteor's underscore package but instead get an accidental sub-dependency. @benjamn's comment above was about how to address that.

**Comment by avital** [comment]
Will be fixed in `1.3-modules-beta.3` (not yet released)
