### ISSUE TITLE
Syntax error in imported file causes stack trace and no indication of file name

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5934]
The syntax error is in this file: https://github.com/stubailo/repro-export-default-const/blob/master/imports/repro.js

Try running the app and you will see a scary stack trace.

**Comment by benjamn** [comment]
Probably related: #6009

**Comment by avital** [comment]
@stubailo You didn't include the stack trace here -- was it the same as described here: https://github.com/meteor/meteor/issues/6009?

**Comment by stubailo** [comment]
Yeah, basically the same.

**Comment by avital** [comment]
Great, closed as dup.
