### ISSUE TITLE
Meteor Docs missing important details

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#5935]
Most of the documentation lacks function signatures for callbacks which are sometimes shown in the example or someplace else but i think it would really make sense to kind of add it to the format that is being used.

HTTP functions have no explanation on the ```results``` object that is returned from the request. I found out about it by doing some logging, etc and this shouldn't be the case.

There should be a section on the ```results``` object. Like how the actual response is in ```results.content```

For function signatures this is what i propose:

**asyncCallback** *Function*

would become

**asyncCallback** *Function(error, results)*

**Comment by bySabi** [comment]
I don´t belong to MDG, say that. 

Meteor is a open source project make a PR proposal than a issue and the whole Meteor community will be grateful.

**Comment by stubailo** [comment]
Yeah, I think this would be a good idea. We generate those with JSDoc, perhaps we could use something like their callback? http://usejsdoc.org/tags-callback.html

Definitely open to concrete plans/suggestions.

**Comment by abernix** [comment]
The community is happy to review PRs for changes to these docs over in the meteor/docs repo (and on the main meteor/meteor repo, as necessary), but this general issue for improving docs isn't refined enough to keep open.
