### ISSUE TITLE
Meteor Build Problem

### ISSUE THREAD

**Issue by rorschach217** [meteor/meteor#5938]
I am building my app using meteor build /directory_path
it doses not give any error but when its process complete then the app.tar.gz does not have any public folder and does not have any forms/html pages which I have created in app.

my app directory is like this
client/templets/home/other directories
this directory have my html forms and js files

other directory such as /lib have js files that should accessed by client and server both
/public have images foder
/server have js code that should run on server

help me.
what should I do

**Comment by avital** [comment]
We can't look at this issue without a clear reproduction. Here are instructions for how to create a great repro: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by avital** [comment]
(Please open a new issue with a repro if you can produce one)

**Comment by rorschach217** [comment]
its ok I am shifting from meteor to node.js express

**Comment by avital** [comment]
Best of luck, thanks for trying Meteor!
