### ISSUE TITLE
Inserting field named 'length' not allowed

### ISSUE THREAD

**Issue by raix** [meteor/meteor#594]
Hi when trying a simple collection.insert({ owner: Meteor.userId(), length:3 }); in Meteor it's executed by client but revoked by server (or in process, same for collection.update) At the moment I renamed the field length to 'len' and voila it works... But now I'm not in compliance with the GridFS spec saying: 'fs.files.length' (the project: collectionfs.meteor.com)

**Comment by KyrosDigital** [comment]
Just ran in to this issue, April 26th, 2019. 

Our team spent quite some time trying to wrap out heads about it and then found this issue. 

We are on Meteor 1.8.0.1

I'm assuming this bug / issue has been floating around in the framework for a couple years now. 

What can we all do to fix this in the framework? We love meteor and I've been using for years. 
Would be great to see this fixed. We would be happy to help contribute.

**Comment by raix** [comment]
Wow 6years do fly, I had hoped underscore would have been swapped out by @jdalton’s lodash aldready 🧐
