### ISSUE TITLE
Kill meteor process started with node 

### ISSUE THREAD

**Issue by kristijanhusak** [meteor/meteor#5943]
Hi,

I'm trying to set up tests  for my project using [Chimp.js](https://github.com/xolvio/chimp) and their [best practices](https://github.com/xolvio/automated-testing-best-practices). They created a node script that starts the meteor application and runs chimp after that. It works pretty well, until the tests are finished. At that point, script is trying to kill all processes that it started. It successfully kills the Chimp, but meteor app hangs in the background, and needs to be killed manually. More info in this issue https://github.com/xolvio/automated-testing-best-practices/issues/4. Here are the steps to reproduce:

```
meteor create test-app
cd test-app
mkdir .scripts
wget https://gist.githubusercontent.com/kristijanhusak/cfe66e9e903ce9b1788d/raw/25ea4b20b6c003a7f090cb54fa997429c9dfae2f/run.js -O .scripts/run.js
node ./scripts/run.js
```

After 30 sec kill command is called on the process. It returns true, but application is still running. It probably kills the process that started meteor, but does not kill meteor process itself. Is there any proper way to handle this? Only solution that i found is to run kill command with `| grep meteor`, but that is not ideal solution. Thanks.

OS: Xubuntu 15.10 64bit
Gist used for script: https://gist.github.com/kristijanhusak/cfe66e9e903ce9b1788d

**Comment by rozzzly** [comment]
```
sudo pkill -ef meteor
```
Is what I use. Meteor spawns a ton of mongo processes which causes issues when you try to 
`meteor run` or `meteor reset` because mongo runs with elevated privileges compared to my shell session from which I try to rerun meteor. At least that was the issue with my setup. Now a days, I have a quick `./cln.qik.sh` in my approot that I'll run to clean out **everything** but the srccode. I'll share if you're interested.

**Comment by kristijanhusak** [comment]
Thanks. That works out for me too, but i'ts still not ideal.
You can share it if it has anything else except that command.

**Comment by timbotnik** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
