### ISSUE TITLE
Object stored in ReactiveVar can be changed without triggering Tracker

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#5944]
I noticed this after doing a `.get()` to a reactive variable, modifying the structure a bit and then sending it to a method. After doing the modification the stored variable under reactive var has been changed, as this demonstrates.

```
var obj = { foo: 'bar' };
var x = new Blaze.ReactiveVar(obj);
var y = x.get();
console.log(x.get());
y.bar = 'foo';
console.log(x.get());
obj.foo = 'changed original';
console.log(x.get());
```

**Comment by stubailo** [comment]
Yes, please use `set` when you are making changes to a `ReactiveVar`. In general, I would avoid mutating the objects you get out of it at all.

**Comment by davidworkman9** [comment]
I don't think it makes sense to close this, this is solvable by MGD.
If you do a ```findOne``` on a ```minimongo``` collection and modify the returned object it doesn't modify the underlying data structure. Same with ```Session```. I don't think it makes sense that the ```ReactiveVar``` would be different from the other two.

```
var obj = { foo: 'bar' };
Session.set('t', obj);
var y = Session.get('t');
console.log(Session.get('t'));
y.bar = 'foo';
console.log(Session.get('t'));
obj.foo = 'changed original';
console.log(Session.get('t'));
```

```
var c = new Meteor.Collection(null);
var obj = { foo: 'bar' }
c.insert(obj);
var y = c.findOne();
console.log(c.findOne());
y.bar = 'foo';
console.log(c.findOne());
obj.foo = 'changed original';
console.log(c.findOne());
```

**Comment by stubailo** [comment]
Oh, you're saying it should `clone` or `freeze` returned objects? I guess we could do that. But cloning all of the time is one of the things that makes Minimongo slow, so it would have to be worth it..

**Comment by davidworkman9** [comment]
Yes, that's how I ended up fixing this. I understand it's fairly expensive to clone each ```get``` call but I think consistency is the best. I figured because I can ```get``` Session and database objects, and mutate them without mutating the underlying data I could do the same with ReactiveVar which turned out to be incorrect.

**Comment by davidworkman9** [comment]
Shouldn't this be ```Project:Tracker```? ```ReactiveVar``` is an independent package from Blaze.

**Comment by stubailo** [comment]
You're right!

**Comment by mitar** [comment]
I remember that this has been discussed already at some point in the past.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Object%20stored%20in%20ReactiveVar%20can%20be%20changed%20without%20triggering%20Tracker&body=Migrated%20from:%20meteor/meteor%235944) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
