### ISSUE TITLE
_.mapObject not defined

### ISSUE THREAD

**Issue by jdmswong** [meteor/meteor#5946]
[_.mapObject](http://underscorejs.org/#mapObject) can't be used in the Meteor server.

This
```
console.log(_.mapObject({'a':1,'b':2},function(v,k){return {asdf:1234,val:v}}) );
```

returns the proper object on the Underscore website but throws
```
I20160106-19:29:11.120(0)? error [TypeError: Object function (obj) {                                                                                // 48
I20160106-19:29:11.120(0)?     if (obj instanceof _) return obj;                                                                    // 49
I20160106-19:29:11.120(0)?     if (!(this instanceof _)) return new _(obj);                                                         // 50
I20160106-19:29:11.120(0)?     this._wrapped = obj;                                                                                 // 51
I20160106-19:29:11.121(0)?   } has no method 'mapObject']
```
on Meteor.

**Comment by Slanman3755** [comment]
I think meteor uses an out of date version of underscore.  Try `meteor add stevezhu:lodash` and putting `_ = lodash` at the top of your js.  I find lodash to be a better library and is nearly completely backwards compatitble with underscore.

**Comment by kookoskar** [comment]
[`_.mapValues` was changed to `_.mapObject` in Underscore.js version 1.8.0](https://github.com/jashkenas/underscore/commit/48f005fa481c299a50439c542a3c88c70270f0fb). Meteor currently [uses version 1.5.2](https://github.com/meteor/meteor/blob/devel/packages/underscore/underscore.js). As a temporary solution, you might be able to use _.mapValues (not sure if it has the same functionality tbh).

**Comment by jdmswong** [comment]
All good solutions, I ended up implementing it myself.  However the root issue here is using an obsolete version of underscore, please fix!

**Comment by kookoskar** [comment]
Well, then it is a duplicate of #1009

**Comment by jdmswong** [comment]
yes it is, closing issue in favor of #1009
