### ISSUE TITLE
[1.3-modules-beta.2] Lazy-loaded files can not be imported with an absolute path

### ISSUE THREAD

**Issue by kookoskar** [meteor/meteor#5948]
An eager-loaded file can be imported with an absolute path

    import Something from '/app/lib/something.js'

but a lazy-loaded file cannot

    import Something from '/app/lib/imports/something.js'
    Error: Cannot find module '/app/lib/imports/something.js'

but it can be imported by a relative path

    import Something from '../lib/imports/something.js'

**Comment by benjamn** [comment]
This will be fixed by 0a6324013ada0f32f86b09465ccaa74c6081900c, though you'll want to remove the `/app/` prefix and simply `import ... '/lib/something.js'`.

**Comment by avital** [comment]
Should be fixed in `1.3-modules-beta.3`.
