### ISSUE TITLE
[feature-request] Auto-load index.html files from public/, like other web servers do.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5949]
Currently, if we have `public/foo/index.html`, visiting `/foo` won't load the `index.html` file. Would this be an acceptable change to Meteor? If so, mind pointing me to the spot in the code where public is handled?

**Comment by pcarrier** [comment]
@trusktr I cannot speak to this feature in particular, but the spot you are looking for is `WebAppInternals.staticFilesMiddleware` currently available at https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L324

**Comment by dgreensp** [comment]
Interesting; what is the motivation for this feature?

**Comment by trusktr** [comment]
We can write `/path/to/foo` instead of `/path/to/foo.html` or `/path/to/foo/index.html` for static pages. I guess we can implement it ourselves with a router, but it is a common default (apache and nginx do it).

**Comment by laosb** [comment]
I think static files should be treated separately, and static pages should not be bundled in a Meteor app bundle.

**Comment by trajano** [comment]
@trusktr how would you do it?  I am facing the same issue, I wanted to publish the dgeni docs on my public folder but I am able to access it properly because of the index.html issue

**Comment by trusktr** [comment]
@trajano Quickfix: Just make [picker](https://github.com/meteorhacks/picker) serve `/public/path/to/somewhere/index.html` whenever you visit `/path/to/somewhere`.

**Comment by trajano** [comment]
@trusktr I'll give it a try, though it seems I have to do it one directory at a time. :-1:

**Comment by trusktr** [comment]
@trajano I think another thing you could do is get more lower level, and use `WebApp.connectHandlers` to intercept requests, and send back the file you need:

```js
connectHandlers.use(function(req, res, next) {
    // use a globbing package or regexes to detect multiple URLs at once, get the HTML file, and send it.
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.end(fileContent);
});
```

**Comment by trajano** [comment]
@trusktr Thought I may have gotten it, but there seems to be a Windows issue that needs to be addressed https://github.com/nodejs/node-v0.x-archive/issues/3374 

Otherwise I think on Unix all one has to do 

    Meteor.startup(()=> {
      WebApp.rawConnectHandlers.use(serveStatic('public', {index: ['index.html', 'index.htm']}))
    })

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bfeature-request%5D%20Auto-load%20index.html%20files%20from%20public%2F%2C%20like%20other%20web%20servers%20do.&body=Migrated%20from:%20meteor/meteor%235949) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
