### ISSUE TITLE
Feature request: Client specifers for app directories and (more importantly) packages

### ISSUE THREAD

**Issue by Type1J** [meteor/meteor#5950]
Although the Meteor package system (Isobuild?) has direct support for web browser clients, it's very useful to use Meteor as the server in other native app client projects. These projects could have their own client side DDP implementation in a language other than JavaScript, but many Meteor client side features work well in native app scripts (Tracker, MiniMongo, Underscore, etc.). It would be useful if the

```
api.use('underscore', ['client', 'server']);
```

line could include something other than just `client` or `server` in the second argument. Perhaps a `all_clients` for "Pure JavaScript libraries that could run in any interpreter or environment" and a `blah_app` that is specific to a particular client, but not others. The `blah_app` string would have to be given somehow when the bundled JavaScript file is requested or a .js file list for that client is requested.

It also may be necessary to have a json file per directory with a list of the app type strings for which the directory is meant because one would probably want to make a directory that only served to `blah_app` in their Meteor app, but that, or another, directory might be meant to run on just `blah_app` or both `blah_app` and `server`, or just `all_clients`. We can already do this with the `client` and `server` directories, but this would allow any directory (except for `client`, `server`, `public`, `private`, and any other reserved directory name) to specify on what the .js files in them are meant to run.

This would enable native apps that have JavaScript JITs or interpreters to have Meteor packages and Meteor Apps that target them directly, and they could even participate in hot code push as the web browser does. With hot code push, even Node.JS processes in a large cluster could act as clients, and they could pull their specific tasks (JavaScript code) from a single Meteor instance.

I don't mind if this idea is twisted or mangled a bit to make it work better. Please let me know if I need to clarify anything, or if Meteor already has support for this sort of thing.

**Comment by rdickert** [comment]
Perhaps this might be better implemented as different entry points in the new module system for 1.3? @benjamn may have some ideas around this.

**Comment by Type1J** [comment]
Let me give the TL;DR version that might be more exciting than my long description above:
Hot code push for React Native separate from the webapp.

My particular case is not React Native, but an app using [DukTape](https://github.com/svaarala/duktape) by @svaarala.

**Comment by Type1J** [comment]
(I realize that hot code push would technically separate from this issue, but we can't _properly_ have hot code push for something other than a web browser until we have JavaScript packages and bundlers for something other than a web browser.)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Feature%20request%3A%20Client%20specifers%20for%20app%20directories%20and%20(more%20importantly)%20packages&body=Migrated%20from:%20meteor/meteor%235950) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
