### ISSUE TITLE
Atmosphere broken

### ISSUE THREAD

**Issue by philipmjohnson** [meteor/meteor#5952]
As noted on the forum by many users starting yesterday, Atmosphere is not allowing package creation or updates:

https://forums.meteor.com/t/cant-publish-new-package-error-socket-hang-up/15949

No one in a position of responsibility has indicated any awareness of this issue, so I am posting this issue in hopes it will break the radio silence. (I also posted an [Atmosphere issue](https://github.com/percolatestudio/atmosphere/issues/424)) but it did not generate any response. 

Please post something to the forum thread to at least indicate someone is aware of this issue and is working on it.

**Comment by ekatek** [comment]
Thanks for the report! This is the right place to post this -- it is a backend issue on our end. We are looking into it.

**Comment by pcarrier** [comment]
Thanks again! This should be fixed now, please let us know if you still run into issues.
