### ISSUE TITLE
[meteor-1.3] babel-runtime issue on the client

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#5953]
I'm trying to use a NPM module which comes with it's own babel-runtime. So, it will work on any environment. 

But it's having issues with Meteor 1.3. It works on the server, but not on the client. See following error:

<img width="941" alt="screen shot 2016-01-08 at 6 05 43 am" src="https://cloud.githubusercontent.com/assets/50838/12187052/597ea134-b5ce-11e5-97fa-4a431eb3efaa.png">

Here's a sample repo: https://github.com/arunoda/babel-runtime-client-issue-meteor-1-3

Is this a known issue?
Any suggestions?

**Comment by stubailo** [comment]
> NPM module which comes with it's own babel-runtime

Isn't this an anti-pattern? For example, you wouldn't ship an extra copy of `es5-shim`, or something. Regardless, I guess this should work anyway.

**Comment by arunoda** [comment]
No it's not. It only picks up the required features only.
It's a win win for some modules if you need to use it everywhere.

But anyway, this should be an issue right?

**Comment by benjamn** [comment]
This will be fixed in the next beta, thanks to #5933! The explanation is that the Meteor package called `babel-runtime` was wrongly taking precedence over any other top-level package called `babel-runtime`, which was a big mistake, in hindsight.

**Comment by arunoda** [comment]
Thanks ben. I'll pick it up then.
