### ISSUE TITLE
Unsure of how to contribute to the docs for docs.meteor.com

### ISSUE THREAD

**Issue by queso** [meteor/meteor#5954]
I spent 30 minutes or so looking through a bunch of stuff in this repo and can't figure how to add/contribute missing content to docs.meteor.com. Help. @stubailo?

**Comment by stubailo** [comment]
It's in the `docs` directory of the repository. Hopefully we can eventually move it to somewhere and give it some documentation of its own.

What were you trying to do?

**Comment by queso** [comment]
Need to add some docs around a method that has no docs atm, part of the WebApp package. I spent far too much time tracking this down and surely I can save someone else time down the road. Obviously I have a blog post ready to go up for it, but figure it should be in the docs too.

**Comment by stubailo** [comment]
OK - first off sorry it is so complex at the moment!

Anyway, you should add the relevant doc via JSDoc, following this document: https://meteor.hackpad.com/Automatically-Generating-API-Docs-using-JSDoc-EpPmd2iuFEH

Then, you should be able to, in the relevant part of the docs markdown (probably under the WebApp package), add `{{> autoApiBox "WebApp.nameOfMethod" }}`

Here's the relevant file about webapp: https://github.com/meteor/meteor/blob/devel/docs/client/full-api/packages/webapp.html

**Comment by stubailo** [comment]
I think the initial issue is resolved. If you want, you can file an issue for the specific piece of missing documentation you are referring to.
