### ISSUE TITLE
Could Not Deploy WebSocket to meteor.com 

### ISSUE THREAD

**Issue by isdzulqor** [meteor/meteor#5955]
I have deployed my Server to meteor.com and it's succeed. This is my site http://booklook-coba.meteor.com/. but when I try to connect it with websocket protocol it's failed. This is my protocol "ws://booklook-coba.meteor.com:443/websocket". The connection always lost. I cannot do CRUD into my database even though it's working in my localhost.
Could you tell me more about this? Thank you

**Comment by mjmasn** [comment]
Are you looking for a Mongo connection url? 

Try `meteor mongo --url booklook-coba.meteor.com` from the terminal.

**Comment by isdzulqor** [comment]
No, I mean I want to access this websocket with ddp. I made android native app with ddp because it's using socket and need real time data. It's work when I access it in my Localhost. But when I deployed it to meteor.com. I cannot access it. I use Genymotion for my android emulator device.

**Comment by mjmasn** [comment]
You might be missing an `s`. You're using port `443` (secure), but `ws://`(insecure). Try `wss://booklook-coba.meteor.com:443/websocket`

**Comment by stubailo** [comment]
We would need a reproduction to do anything about this issue - the source code of an app that doesn't work when it's deployed. Please ask questions about why things don't work on the forums, and post an issue when you know it's a problem with Meteor itself.
