### ISSUE TITLE
React Bug: Meteor.user() undefined in Firefox

### ISSUE THREAD

**Issue by SylarRuby** [meteor/meteor#5956]
`Meteor.user()`, when logged in, does not work in Firefox 43.0.4, only works in Chrome:

```
Foo = React.createClass({
 mixins: [ReactMeteorData],
 getMeteorData() {
    return {
      currentUser: Meteor.user(),
    };
  },
 getInitialState() {
  var u = Meteor.user();
  console.log(u); // undefined in Firefox but works in Chrome.
  
  return{name: ''}
 }
...
});
```

Server:

```
Meteor.publish(null, function () {
  if (this.userId) {
    return Meteor.users.find({_id: this.userId},
                             {fields: {'regtype': 1, 'profile': 1}});
  } else {
    this.ready();
  }
});
```

**Comment by patrickml** [comment]
@SylarRuby Im not having any issues with it as you can see here https://www.dropbox.com/s/gxotdefhexs2reh/Screenshot%202016-01-08%2009.30.17.png?dl=0

What the real issue may be is that your calling Meteor.user() within `getInitialState()` which is only called once, when the component is mounted. What you should do is use the `ReactMeteorMixin` and return the users. This will also keep your data reactive when the users information updates

**Comment by SylarRuby** [comment]
Thanks but the reason is, I need to state. So I could say `var u = Meteor.user().profile;` then in the return of `getInitialState()` : `{name: u.firstName}` Makes sense?

**Comment by reel** [comment]
Try not to use state. You can get your Meteor.user in a higher component and pass it as a prop to Foo.

```javascript
App = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
    return {
      currentUser: Meteor.user(),
    };
  },
  render() {
    return <Foo user={this.data.currentUser} />
  }
});

Foo = React.createClass({
  render() {
    if (this.props.currentUser) {
      // use it here...
    }
  }
});

```
