### ISSUE TITLE
[1.3-modules-beta.3] Setting a file named "lib.js" as a module entry-point in a package overwrites other entrypoints

### ISSUE THREAD

**Issue by kookoskar** [meteor/meteor#5962]
api.mainModule('client.js', 'client');
    api.mainModule('lib.js', 'server');

`lib.js` would be take precedence over `client.js`, even though `lib.js` is set as an entrypoint for the server. Renaming `lib.js` to anything else fixes the issue (the file will then only be set as the entrypoint for the server).

[Example repo.](https://github.com/kookoskar/meteor-bug-example) (Look at the console in the browser. Rename `lib.js` to something else in `package1`. The output changes).

**Comment by kookoskar** [comment]
Maybe there's other cases like this. [`1.3-modules-beta.2` had a similar problem with directories](https://github.com/meteor/meteor/issues/5957), but that got fixed with `1.3-modules-beta.3`. So I wouldn't be surprised if there were more problems with filenames.

**Comment by benjamn** [comment]
This is no longer reproducing for me. Not sure what might have been causing the bug. Feel free to reopen if it's still a problem for you.

**Comment by kookoskar** [comment]
This is still the case for me in `1.3-modules-beta.4`. I'll see, maybe I can do a pull request for you in your repo.

**Comment by kookoskar** [comment]
Well, I couldn't reproduce the bug when writing the test for it, so I did `meteor reset` in my original project and the bug was gone. My bad there.
