### ISSUE TITLE
Meteor.call with DOM element leads to too much recursion

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#5964]
I accidentally passed in a DOM reference to a Meteor method call using react like this:

``` JavaScript
// hangs/crashes/too much recursion
Meteor.call("updateOwnEmail", this.refs.email, (error) => { ... });
// works fine
Meteor.call("updateOwnEmail", this.refs.email.value, (error) => { ... });
```

It crashed the page in Chrome after a brief hang, and Firefox kicks out a "too much recursion" message. The rolled out error message shows a lot of EJSON lines (and ES5), so I would guess the serializer is choking on the DOM element, but that's just a guess.

A better outcome would be a console message saying that DOM elements can't be passed to the server.

**Comment by stubailo** [comment]
Yes I agree, it would be great for either EJSON or `Meteor.call` to throw a helpful error when values that can't be serialized are passed in. I'd be happy to look at a pull request to make this improvement.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor.call%20with%20DOM%20element%20leads%20to%20too%20much%20recursion&body=Migrated%20from:%20meteor/meteor%235964) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
