### ISSUE TITLE
getMeteorData() is very slow!

### ISSUE THREAD

**Issue by SylarRuby** [meteor/meteor#5966]
Has this been reported yet? `getMeteorData()` is very slow causing return value to be undefined. Any works around? Seems to be fast only in Chrome.

**Comment by sahanDissanayake** [comment]
are you using ```Meteor.publish()``` on the server ?

**Comment by SylarRuby** [comment]
@sahanDissanayake Yes I am.

**Comment by sahanDissanayake** [comment]
ok, I use ```Meteor.publishComposite``` and I get undefined values sometimes. lets see if a Core Dev has something to say :+1:

**Comment by stubailo** [comment]
This is best discussed on the forum in that thread that is already opened about it.

https://forums.meteor.com/t/getmeteordata-is-slow/16171

It will only make sense as a GitHub issue if there is a clear reproduction and an intended outcome.

**Comment by stubailo** [comment]
See the directions here: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
