### ISSUE TITLE
[1.3-modules-beta.4] Error when updating from an older version of Meteor: "TypeError: Cannot read property 'packages' of null"

### ISSUE THREAD

**Issue by cismous** [meteor/meteor#5967]
You are running Meteor from a checkout, so we cannot update the Meteor release. Checking to see if we can update
your packages.
Your top-level dependencies are at their latest compatible versions.
                                              
TypeError: Cannot read property 'packages' of null
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1705:39)
    at /tools/cli/main.js:1407:23

Note: this error seems to only occur when exec meteor update

**Comment by cismous** [comment]
I have exec ```meteor reset``` , but can't resolve this issue.

**Comment by avital** [comment]
Can someone come up with a set of commands I can run to see this error?

**Comment by benjamn** [comment]
Possibly related in spirit: #5830

**Comment by avital** [comment]
No repro for this one specifically, so I'm closing. If someone has a repro, please post!
