### ISSUE TITLE
Load gif in splash screen instead of static image

### ISSUE THREAD

**Issue by evivz** [meteor/meteor#5972]
I am trying to use gif in splash screen but its not working. Can I know what is the issue or how to use gif?

**Comment by talha-asad** [comment]
You mean splash screen of mobile app? Be a bit more specific.

**Comment by evivz** [comment]
Yes splash screen of mobile app (ios and android).

**Comment by talha-asad** [comment]
http://stackoverflow.com/questions/19967817/animated-splash-screen-using-gif

**Comment by stubailo** [comment]
It looks like the default Cordova splash screen plugin doesn't support animation. You would have to write a custom plugin to do this for you; perhaps the Meteor or Cordova forums could be helpful in finding out more.

There isn't much we can do about this in Meteor core, so I'm going to close this issue.

**Comment by sahanDissanayake** [comment]
@stubailo is there a way to remove the splashscreen from both IOS and Android ? People say that the app is slow to load ~10s from the icon click to working app.

Thanks.
