### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by rauleb** [meteor/meteor#5974]
[angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.2/auth

**Comment by rdickert** [comment]
@rauleb It sounds like this should probably be reported not on meteor, but on [angular-meteor](https://github.com/Urigo/angular-meteor). Please reopen here if I've misunderstood you.
