### ISSUE TITLE
Allow numbers for _id

### ISSUE THREAD

**Issue by dotnetwise** [meteor/meteor#5978]
This seems perfectly acceptable by `mongod` that comes with meteor `1.2.1`

This looks like an ancient restriction to me - but why do we still have it?

**Comment by stubailo** [comment]
Meteor's Optimistic UI system relies on being able to automatically generate unique random IDs on the client. It's impossible to do this with integers. So any Meteor support for numeric IDs in Mongo would be limited compared to current support.

I'm curious why it is important to you that the IDs need to be numbers?

**Comment by dotnetwise** [comment]
Because when you import data from other databases they might be numbers. 
Most of the SQL databases are either GUID or `integers`.

So if we convert them to strings we break other stuff.
Can you simply generate strings from client but also allow numbers if they are there?

Of course in mongo `1` is different than `"1"` which for ids is okay (no problem as we use the same evrywhere e.g. I think mongo is using `===` operator which is fine)

**Comment by stubailo** [comment]
Until such a time as we support numeric IDs (which might be possible in the future, independent of this request) I'd suggest using a different field to store the original ID from SQL.

**Comment by stubailo** [comment]
Closing this because it would be very hard to make DDP support integers.
