### ISSUE TITLE
ES6 spread operator for maps is broken

### ISSUE THREAD

**Issue by subhog** [meteor/meteor#5980]
Consider the following code:

    var m = new Map();
    m.set('asdf', 42);
    var x = [...m];
    console.log(x);

The value of `x` in ES6 is `[["asdf",42]]`. It currently works natively in FF43, doesn't work in Chrome43. However, in a Meteor app with `ecmascript` package turned on, the code is transpiled incorrectly and produces `x = [m]`.

The solution could be as simple as updating Babel version. `ecmascript` package is based on Babel 5.8.24. The snipped is transpiled correctly in never versions, see:

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20m%20%3D%20new%20Map%28%29%3B%0Am.set%28%27asdf%27%2C%2042%29%3B%0Avar%20x%20%3D%20[...m]%3B%0Aconsole.log%28x%29%3B%0A%0A%0A

As of writing this issue, the page above uses Babel 5.8.34 and produces the correct result.

**Comment by dgreensp** [comment]
I believe we're going to be upgrading Babel to v6 as part of Meteor 1.3, but either way, we should upgrade Babel to a version that fixes this bug.  cc @benjamn

**Comment by apendua** [comment]
@dgreensp @benjamn If you are thinking about upgrading to Babel 6, please keep an eye on the status of this ticket:

https://phabricator.babeljs.io/T6676

unless you want to run into another set of problems.

**Comment by benjamn** [comment]
I think this will be fixed by the Babel upgrade (though of course there may be other new bugs).

Leaving myself a note to add a regression test [here](https://github.com/meteor/meteor/blob/3eec30d469aede923e6a951f59985c2b1de3aef8/packages/ecmascript-runtime/runtime-tests.js#L1).

**Comment by apendua** [comment]
@benjamn Yes, there will be new bugs. I've just mentioned one of them above. I think it would be wise to add a regression test for that one as well.
