### ISSUE TITLE
Typo issue in documentation of Accounts

### ISSUE THREAD

**Issue by Garethderioth** [meteor/meteor#5983]
In this documentation: https://www.meteor.com/accounts

There is a typo issue, where says: Accounts.loginWithPassword, Accounts.loginWithFacebook is really Meteor.loginWithPassword and Meteor.loginWithFacebook.

Regards.

**Comment by wujunze** [comment]
hello

**Comment by avital** [comment]
Thanks. I'm deploying a fix.
