### ISSUE TITLE
Meteor build error.

### ISSUE THREAD

**Issue by Panda-Srujan** [meteor/meteor#5985]
Hi everyone,

I'm new to meteor. I've developed an application and tried to build the application to generate an .apk file. I've confronted with an error that says "This command is not yet available on windows".

Please suggest me if there is a process to generate an .apk file on windows platform. If not possible on windows, please suggest me the process to generate an .apk file on any other platform.

Thanks in advance.
![meteor build error 1](https://cloud.githubusercontent.com/assets/16679478/12286861/e834cb1a-b9ed-11e5-8955-385b030e15ab.png)

**Comment by martijnwalraven** [comment]
Building mobile apps is not yet supported on Windows. This is being tracked in #4155. You can build iOS and Android apps on Mac, and Android apps on Linux.

**Comment by Panda-Srujan** [comment]
Hi Martijnwalraven,

Thanks for providing me with the information.
