### ISSUE TITLE
meteor deploy --patch-settings env.json

### ISSUE THREAD

**Issue by dcworldwide** [meteor/meteor#5987]
A big annoyance for me is having to re-deploy my app just to patch it's configuration. IMO we need something like the following that will patch the configuration without re-deploying the app. I.e. 

```
meteor deploy --patch-settings env.json

or 

meteor deploy --settings env.json --patch-settings-only
```

I have the same issue for both free meteor.com and galaxy hosting. The absence of this feature is exacerbated by the fact that meteor deploy presently takes ~10 minutes for me at present.

**Comment by tmeasday** [comment]
Yes, I think we are tracking this feature request against Galaxy.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=meteor%20deploy%20--patch-settings%20env.json&body=Migrated%20from:%20meteor/meteor%235987) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
