### ISSUE TITLE
[meteor 1.2.1] When iterating some collections it returns function instead of object on chrome and safari on some mac

### ISSUE THREAD

**Issue by digz6666** [meteor/meteor#5990]
When iterating some collections it returns weird function instead of object on chrome and safari on some mac (macbook air), and throws following exception:
Error: {{#each}} doesn't support arrays with elements of type function

```javascript
relatedCars: function() {
    var carList = Car.find({ brand: 'Toyota' }, {}, limit: 10 }).fetch();
    for (var i in carList) {
        console.log(carList[i]);
        relatedCars.push(carList[i]);
    }
    carList = Car.find({ brand: 'Nissan' }, {}, limit: 10 }).fetch();
    for (var i in carList) {
        console.log(carList[i]);
        relatedCars.push(carList[i]);
    }
    return relatedCars;
```

So I've added typeof check and the issue is resolved at the moment.
```javascript
relatedCars: function() {
    var carList = Car.find({ brand: 'Toyota' }, {}, limit: 10 }).fetch();
    for (var i in carList) {
        if (typeof carList[i] === 'object') {
            relatedCars.push(carList[i]);
        }
    }
    return relatedCars;
```

console.log(carList[i]) sometimes prints just object:
```
Object {_id: "blabla", bodyType: "blabla"}
```

But sometimes it prints:
```
function() {try{var _0x5757=["\x6C\x65........................"]}
```

Here's the chrome console of the macbook air:
![123](https://cloud.githubusercontent.com/assets/1736110/12293446/96d2211e-ba2e-11e5-943e-8b36600d70df.png)

**Comment by stubailo** [comment]
You're missing an important part of iterating objects in JavaScript - the `hasOwnProperty` check. See the top answer to this SO question: http://stackoverflow.com/questions/684672/loop-through-javascript-object

Another way is to use `Array#forEach`, which does the right thing by default:

```js
    var carList = Car.find({ brand: 'Toyota' }, {}, limit: 10 }).fetch();
    carList.forEach(function (car) {
        console.log(car);
        relatedCars.push(car);
    });
```

Going to close, since it's an issue with JavaScript itself, and not Meteor.

**Comment by digz6666** [comment]
@stubailo Thank you for the explanation :)
