### ISSUE TITLE
App never reconnects to server (Safari, Mac OS X)

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#5996]
Our application (hosted on Heroku) never reconnect to server after going offline when running in Safari.  
`Meteor.status` reports `{status: "connecting", connected: false, retryCount: 1}`
I can see `[Error] WebSocket network error: The operation couldn’t be completed. Socket is not connected` in the console.

`Meteor.reconnect()` doesn't help.

Safari version 9.0, Mac OS X 10.11.

Chrome (47) reconnects without problems.

After page refresh the app connects normally.

**Comment by realyze** [comment]
By the way, after calling `Meteor.disconnect`, `Meteor.reconnect()` doesn't connect either.
```
> Meteor.disconnect()
< undefined
> Meteor.status()
< {status: "offline", connected: false, retryCount: 0} = $2
> Meteor.reconnect()
< undefined
> Meteor.status()
< {status: "connecting", connected: false, retryCount: 0} = $2
```

The status then stays the same.

**Comment by martijnwalraven** [comment]
This is not an issue I've encountered before, so it may have to do with your specific setup. To investigate, we will need a reproduction.

**Comment by realyze** [comment]
I have looked into that some more and it looks like it's related to [UserSnap's widget code](https://usersnap.com/) that we're including.

**Comment by realyze** [comment]
Should I close this one or do you want to keep it open?

**Comment by martijnwalraven** [comment]
No, let's close it.

**Comment by realyze** [comment]
OK, thanks. BTW sorry for not reporting back on this sooner, I got sidetracked.

**Comment by domramirez** [comment]
I'm having the same issue with FileStack's widget on iOS Chrome && iOS Safari. I didn't encounter the problem on FileStack's demo widget from their website. Is it possible that Meteor bumps other socket connections out on iOS?
