### ISSUE TITLE
regex selectors for case insensitivity on Accounts.createUser 

### ISSUE THREAD

**Issue by pahans** [meteor/meteor#5997]
the query generated from [`selectorForFastCaseInsensitiveLookup`](https://github.com/meteor/meteor/commit/dac019fda8a5e70b2dbec335b6605b04c0c034bc#diff-b4ff99fd7ae25449bebd21fc644cdea1R194)  looks like following.

```js
{
  "$and": [{
    "$or": [{
      "emails.address": {
        "$regex": "^user"
      }
    }, {
      "emails.address": {
        "$regex": "^useR"
      }
    }, {
      "emails.address": {
        "$regex": "^usEr"
      }
    }, {
      "emails.address": {
        "$regex": "^usER"
      }
    }, {
      "emails.address": {
        "$regex": "^uSer"
      }
    }, {
      "emails.address": {
        "$regex": "^uSeR"
      }
    }, {
      "emails.address": {
        "$regex": "^uSEr"
      }
    }, {
      "emails.address": {
        "$regex": "^uSER"
      }
    }, {
      "emails.address": {
        "$regex": "^User"
      }
    }, {
      "emails.address": {
        "$regex": "^UseR"
      }
    }, {
      "emails.address": {
        "$regex": "^UsEr"
      }
    }, {
      "emails.address": {
        "$regex": "^UsER"
      }
    }, {
      "emails.address": {
        "$regex": "^USer"
      }
    }, {
      "emails.address": {
        "$regex": "^USeR"
      }
    }, {
      "emails.address": {
        "$regex": "^USEr"
      }
    }, {
      "emails.address": {
        "$regex": "^USER"
      }
    }]
  }, {
    "emails.address": {
      "$regex": "^user131312233@foo\\.com$",
      "$options": "i"
    }
  }]
}
```
Why not something like following query is not used?
```js
{
  "$and": [{
      "emails.address": {
        "$regex": "^user",
        "$options": "i"
      },
      {
        "emails.address": {
          "$regex": "^user131312233@foo\\.com$",
          "$options": "i"
        }
      }]
  }
```

**Comment by pahans** [comment]
seems it is a performance improvement

>Generates a MongoDB selector that can be used to perform a fast case
>insensitive lookup for the given fieldName and string. Since MongoDB does
>not support case insensitive indexes, and case insensitive regex queries
>are slow, we construct a set of prefix selectors for all permutations of
>the first 4 characters ourselves. We first attempt to matching against
>these, and because 'prefix expression' regex queries do use indexes (see
>http://docs.mongodb.org/v2.6/reference/operator/query/regex/#index-use),
>this has been found to greatly improve performance (from 1200ms to 5ms in a
>test with 1.000.000 users).

https://github.com/meteor/meteor/blob/dac019fda8a5e70b2dbec335b6605b04c0c034bc/packages/accounts-password/password_server.js#L144

**Comment by deadjdona** [comment]
Any plans to use collation?
