### ISSUE TITLE
[1.3-modules-beta.4] addAssets on server compiling for web.browser

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#5998]
Just upgraded to 1.3-modules-beta.4 and get the following error when running the app:
```
While processing files with templating (for target web.browser):
   packages/mjmasn:emails/layouts/hoozyu.html:1: Expected one of: <body>, <head>, <template>
   ...all my other email templates...
```

I'm using SSR (meteorhacks:ssr) to render this template to send as an email so I don't want it to be compiled unless I manually do so with Assets.getText (see below):

```coffeescript
for template in templates
    SSR.compileTemplate template.name, Assets.getText template.path
```

package.js contains a call to `api.addAssets` like so:
```js
api.addAssets([
    'layouts/hoozyu.html',
    'templates/some-email-template.html',
    '...'
],'server');
```

I don't particularly like the temporary workaround I've found - which is to rename all the files to .email - because it breaks syntax highlighting. Yes I could fix that too, but it seems like Meteor isn't doing the right thing here.

**Comment by avital** [comment]
We probably don't need to compile all `.html` files in a package, just like we don't need to do for `.css` files. I think this is just a bug.

**Comment by benjamn** [comment]
Similar fix to https://github.com/meteor/meteor/commit/b04c83702703c7856848ddc84b9c06c9f3c22095.

**Comment by avital** [comment]
This bug also makes `meteor test-packages` fail now (because some packages have .html assets that aren't templates)

**Comment by avital** [comment]
Maybe we'll solve this pragmatically with a `.meteorignore` file in packages. #6002

**Comment by benjamn** [comment]
Another alternative: if a file is `.lazy` (i.e. not added explicitly to the package), then it may be safe to swallow compiler plugin exceptions.

**Comment by benjamn** [comment]
This should finally be fixed in `beta.11` (by [this commit](https://github.com/meteor/meteor/commit/ce4fda3783373d3a477496fe89655c64275118ae). Thanks for the report!
