### ISSUE TITLE
[1.3-modules-beta.4] all HTML and CSS assets in packages are compiled even if not specified in package.js

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#5999]
@benjamn this is a major breaking change from 1.2 - I have a number of packages, some of which may have submodule links or are otherwise linked to other github repos or external code.

Often these other repos have built in documentation which uses html and css. In 1.3 these are being compiled into the css that's sent to the browser, even though the files aren't specified in package.js.

As you can see we probably don't want other people's random css files being applied to our site...

**Meteor 1.2**
<img width="830" alt="screen shot 2016-01-14 at 14 18 55" src="https://cloud.githubusercontent.com/assets/2977095/12326612/cefc5fc8-bac9-11e5-9562-c0fc52a1d18c.png">

**Meteor 1.3-modules-beta.4**
<img width="686" alt="screen shot 2016-01-14 at 14 18 39" src="https://cloud.githubusercontent.com/assets/2977095/12326616/d3ba9b10-bac9-11e5-9756-7e012d37c392.png">

**Comment by barbatus** [comment]
+1
I have the similar issue but with .ts-extension.
There is a registered compiler for it and when I run
````
PACKAGE_DIRS=some_dir_with_lot_of_packages meteor run --release 1.3-modules-beta.4
````
It tries to compile every single .ts-file in packages directories even if it's not included in via api.AddFiles.
This is not how it worked previously.

**Comment by avital** [comment]
There are two separate things here, it seems.

One is a bug: We shouldn't be automatically applying all `.css` files in packages unless they were explicitly added via `addFiles`.

The second: We compile all `.js` files (and those that compile to `.js`) in every package. That is part of the new design. Can people be more specific about why this causes problems, eg @barbatus @Urigo? There are possible solutions but let's first understand the problem.

**Comment by Urigo** [comment]
So it means it's a breaking change right?
what if we have files we don't want to expose?  we have to write our code with `import` `export` then?

**Comment by avital** [comment]
I mean. It's a change. But I'd like to understand what it breaks.

**Comment by avital** [comment]
Even if you use `import`/`export` all the package files will be published.

**Comment by barbatus** [comment]
let's say I have a repo structure like this https://github.com/Urigo/angular2-meteor.
Files from examples and packages folders are now included in compilation as well if I run an example locally with `PACKAGE_DIRS` set, how can I exclude these folders now from compilation?

**Comment by avital** [comment]
Thanks for clarifying. One option would to say: "don't do that-- put your package in a subdirectory and docs and everything else in sibling directories, not a subdirectory of your Meteor package". Admittedly, that's not how people usually manage their Node modules...

Not sure really.

The reason we made this change to how we parse `.js` files in a package because it required less re-architecture of the build tool internals.

**Comment by avital** [comment]
Or maybe really the easiest is just a `.meteorignore` file

**Comment by mjmasn** [comment]
Yeah I guess my point about html/css documentation also applies to things like example code that are in a 3rd-party repo. Even without that, surely compiling ***all*** js in a package would also compile things like tests and half-written code that you don't want executed or sent to the client until you specifically add it to an `api.addFiles` call. How does it apply to client side code - if we're just compiling all js how does Meteor know what we're targeting? Or are packages moving towards the explicit `/lib` `/client` `/server` style folder structure?

In some of my recent packages I have jasmine unit tests that run completely separately from Meteor but with 1.3 it sounds like they are going to be compiled into the app. That's bizarre.

I think at the very least the current packages behaviour should be unchanged unless a package specifically uses depends on the 'modules' package. Supporting globs in package.js would be the ideal solution from my point of view maybe with include/exclude. So you could include all `.js` files in your package but exclude the `examples` directory for example.

**Comment by benjamn** [comment]
The CSS problem (which was a severe bug) will be fixed by https://github.com/meteor/meteor/commit/b04c83702703c7856848ddc84b9c06c9f3c22095 in the next beta release.

**Comment by avital** [comment]
We plan to address this issue for 1.3 via `.meteorignore`, as described above. We'll separately also look at #5998.

**Comment by dcworldwide** [comment]
This will affect me as well. I often git clone my forks of 3rd party libs into meteor wrapper packages and only expose the dist js files (typically excluding css) using add files. A ignore file will make this use case much less elegant but it is workable. I suppose this use case should move to an npm package at 1.3 instead?

**Comment by cunneen** [comment]
@avital it's not always reasonable to ask people to reorganize e.g. when using a local package to wrap a 3rd-party module that includes docs or grunt-built sources, such as:

[https://github.com/AppWorkshop/meteor-json-editor]()

The fact that this breaks should at least be added to the 1.3 migration guide. Moving the package to imports/ doesn't help.

**Comment by mjmasn** [comment]
@avital coming up against this issue again with 1.3 - Meteor is trying to process HTML test coverage reports from Istanbul which are in my imports directory so shouldn't be loaded. What's the solution here, was `.meteorignore` implemented in the end?

**Comment by Falieson** [comment]
https://github.com/meteor/meteor-feature-requests/issues/5
