### ISSUE TITLE
[1.3] Let `.js` files import `.html` files

### ISSUE THREAD

**Issue by avital** [meteor/meteor#6003]
***1 Upvote*** In order to let people use templates with modules, we should:
1. Let a `js` file import an `.html` file, getting back a map of template objects defined in that file.
2. If template files are in an `imports/` subdirectory they don't get automatically compiled and placed on the `Template` namespace.

This would for example allow to build packages that are built with a bunch of templates but only export one of them.

**Comment by stubailo** [comment]
After thinking about this a bit, I'm not sure that this will provide a lot of value - probably a lot of packages rely on being able to reference templates by name, and then being able to find them on `Template`. It would take a lot of restructuring, marketing, and upheaval of the package ecosystem to make everything work together nicely, and I'm not sure it's worth it just to make templates a bit more modular.

**Comment by raix** [comment]
+1 this would be nice

**Comment by stubailo** [comment]
@raix do you think it's worth it to add an extra file to each template for imports? Basically, for the following template, which previously didn't need any JS:

```html
{{! userBadge.html }}
<template name="userBadge">
  <div>
    {{> userAvatar}}
    {{> userSummary}}
  </div>
</template>
```

You'd need to add a JS file to import templates and declare helpers:

```js
// userBadge.js
import { userAvatar } from '../userAvatar.html';
import { userSummary } from '../userSummary.html';
import { userBadge ) from '../userBadge.html';

userBadge.helpers({
  userAvatar,
  userSummary,
  userBadge,
});
```

That's a lot of lines of boilerplate for a simple template. What would an improved version look like?

**Comment by raix** [comment]
@stubailo If the boilerplating concerns you we could have add a `global-templates` package for backwards compatibility.

This pattern will solve namespacing issues, and makes things a bit more componentized.

Examples of usage:

--

Work/think in components
```js
  // Use ui bootstrap components
  import UI from './ui.components'; // We can swap out components without much refactoring
  import styles from './ui.styles.v1.js';
  import { view } from 'foo.view.html';

  view.helpers({ UI, styles }); // Make UI.DateInputField available

  export view;
```

--

Extending/overwriting the template scope eg. for ab testing
```js
  // Use ui bootstrap components
  import UI from './ui.components';
  import AB from './ui.ab.test.components';
  import styles from './ui.styles.v1.js';
  import { view } from 'foo.view.html';

  const ABUI = Object.assign({}, UI, AB);
  view.helpers({ UI:ABUI, styles }); // Make ab components available for testing

  export view;  
```

--

Potentially we do even more in the longer run eg. extending views, decouple for testing etc.

eg.:
```js
  // Use ui bootstrap
  import UI from './ui.components';
  import styles from './ui.styles.v1.js';

  // Import view layer
  import { view } from 'foo.view.html';

  // Export viewController / component 
  export view.createComponent({
    // Add controller
    helpers: { UI, styles }
  });
```

**Comment by Goatic** [comment]
I have a question in this regard - I'm importing a "document.html" file on the client in a 1.3b8 project. I've removed Blaze, and added React from npm and static-html from atmosphere.

My "document.html" import isn't recognised as a module.

This technique works fine in a similar  project using Blaze...

Am I missing something obvious or should I submit an issue?

**Comment by cheapRoc** [comment]
@Goatic is your issue that you can't import an html file [like this](https://github.com/meteor/todos/blob/master/imports/ui/layouts/app-body.js#L1)? Because I can't import html files in the app I'm upgrading either (at least not yet anyway).

**Comment by cheapRoc** [comment]
In case anyone does the same thing... My template loading issue was due to incorrectly assuming I needed to load my templates for my Iron routes on the server. 

_Obviously_ you can't load templates on the server. :cactus:

**Comment by abernix** [comment]
I think this is done enough to close?

**Comment by stubailo** [comment]
Agreed!
