### ISSUE TITLE
Meteor webSocket error

### ISSUE THREAD

**Issue by nombx** [meteor/meteor#6007]
When i  build meteor on untubu 14.4, why server is not support websocket? 
WebSocket connection to 'ws://123.57.23.127:7788/sockjs/480/kpwqjw81/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

(http://123.57.23.127:7788/ )

**Comment by stubailo** [comment]
Hi, please submit a reproduction following the directions here: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

It's not clear what issue exactly you are experiencing, and how we could reproduce it. Thanks.

**Comment by adamgins** [comment]
@nombx wondering if you solved this?
