### ISSUE TITLE
[modules-1.3-beta.4] Lazy loading of package modules

### ISSUE THREAD

**Issue by barbatus** [meteor/meteor#6010]
I bumped into one potential issue.

Some of the package's modules I am developing need to be loaded lazily since I want to load NPMs only once at the app level, which uses this package.

I tried to put files into the `imports` folder, but it produced zero result in the package JS output: files were just ignored at all. 

Is any way to load package modules lazily now? Thanks

**Comment by barbatus** [comment]
Some elaboration based on the test modules app.

I’d like to avoid doubling of NPM packages' modules, that being imported on the client by the app itself and by some package, in the JS files produced by Meteor.

For example, this (https://github.com/barbatus/modules/blob/master/packages/modules-test-package/client.js#L6) import  is always executed at the app start whether I use this package here (https://github.com/barbatus/modules/blob/master/client/app.js#L7) or not.

In order to make the package work, I need to `NPM.depends` https://github.com/barbatus/modules/blob/master/packages/modules-test-package/package.js#L8 of these NPMs, which ultimately, as I understand, leads to appearance of the imported modules in the package’s final JS bundle.

Same happens on the app side too. Imports of NPM packages make Meteor bundle all modules that being imported to the `app.js` file.

How could I resolve the issue like above? Thanks
(I am possibly missing some trivial thing. Sorry for bothering you if it’s true)

**Comment by clayne11** [comment]
With Meteor 1.3 you shouldn't be using Npm.depends. Create a package.json file, npm install --save <package-name>, then import it wherever you need it.

I don't fully understand what your problem is though. Your explanation is not  very clear to me.

**Comment by barbatus** [comment]
@clayne11 Do you understand a word 'doubling'? I import Angular2 both in the app and in the package, and get two files (app and package) of 5MB size (Angular2 size). I didn't try `npm install ` for a package, but it doesn't matter.  It unlikely will help to avoid that issue.

**Comment by avital** [comment]
Meteor 1.3 doesn't attempt to address duplication of client-side Node modules.

A future version of Meteor should address this, probably through NPM3.

**Comment by avital** [comment]
Meteor 1.3 also doesn't attempt to solve the "build multiple client bundles". Your app still loads a single .js file at once. A future version of Meteor should also address that.

**Comment by laosb** [comment]
Duplicated #6967 Closing this.
