### ISSUE TITLE
Minimongo performance updating field in doc containing another large field 

### ISSUE THREAD

**Issue by activeperception** [meteor/meteor#6012]
Hi,

It seems that 'update' performance depends on the doc size...even if I update a small field of a large doc.
(fairly large document (~60Kb) with almost all data in one field and update ($pull) on another field).

Can you think of any workaround other than splitting the document in two?

**Comment by stubailo** [comment]
Yeah I think this might be related to the fact that Minimongo clones documents a lot before returning them. There are probably some tricks or workarounds that might help, but in general Minimongo is not optimized for dealing with large amounts of data. I'd probably suggest using something like `_publishCursor` on the server to publish the large fields to a separate collection that you access less frequently. Basically you can keep the data in the same collection on the server, but split it up when publishing to the client.
