### ISSUE TITLE
Inherent incompatibly between local NPM packages and Npm.require + proposition

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#6013]
I've been experimenting with Meteor 1.3 beta 4 on an existing project. Using modules has generally worked very well, however I'm struggling to reconcile the a number of problems that will now be introduced by the fact that we finally have easy access to NPM packages on the client.

If I include an NPM package in my project, and a meteor package `Npm.require`'s it too, then we have duplication. This also occurs if two packages include `Npm.require` the same NPM packages

This is obviously something that we wish to avoid at all costs, especially for huge libraries such as React. Let's look at our options:

### Create a wrapper package

This is the solution that we have today. We create a package that wraps the NPM module. If the app or other packages then need that NPM package then they install the Meteor wrapper package instead. The result is that there's just one copy of the NPM module shared by everyone.

That's fine, but it's certainly slightly more longwinded than just installing an NPM module. Creating some wrappers can be particularly awkward if the NPM package being wrapped depends on another NPM package that we already have (such as React), in which case we have to use browserify to rewrite the `require` statements to use our own versions.

Another major disadvantage is that many of the wrappers on Atmosphere use out of date version of the NPM modules that they're wrapping.

Nevertheless, from a technical standpoint, this does work for the moment (although I don't quite understand the comment made [here](https://github.com/meteor/meteor/issues/5795), are you dropping support for browserify?)

### Avoid wrapper packages

This is the approach that Arunoda has taken in his [article about using Meteor 1.3 and React](https://voice.kadira.io/getting-started-with-meteor-1-3-and-react-15e071e41cd1#.8jyr6kub2).

Rather than installing the MDG React package, he's installed it as a local NPM package in his project. At first glance this seems great because we can now install other NPM packages that depend on React without worrying about duplication. We don't need to create a wrapper and we don't need to use browserify.

However, not all is as rosy as it seems since we can **no longer import any Meteor package which depends on MDG's React package!**. If we do they we'll have replication. This is a terrible situation to be in  since we deprive ourselves of access to loads of great packages.
 
The example above is true of React, but it's also true of every other NPM module. If I install moment.js  using NPM then I'm in trouble if any of my other packages depend on the `moments:moment` wrapper (of which there are many). On the other hand, installing it locally makes if easy to add any of the NPM date picker packages without having to creating a wrapper using browserify.

### Package authors to the rescue? No.

So we clearly have a number short term issues to content with, but surely package authors can help in the long term?

Actually, no. It would seem that one option would be for package authors to stop using `Npm.require` and simple state in the documentation that NPM package XXX must be locally installed. However, this doesn't work. I tried to do this using beta 4:

```
import moment from 'moment';
```

However this fails since the Npm package isn't itself required by the meteor package that's trying to use it. It doesn't matter that the NPM package is installed by the app itself or by other meteor package.

As a package author there's there are just two workable options: either require the NPM package or depend on another Meteor package that wraps it. In either case we prevent the application author from being able to install the NPM app locally too.

## Proposition

It would be great if 1.3 could solve this problem properly.  What we really need is for a new version of `Npm.require` which simply requires that the given NPM package be installed locally. Ideally the Isobuild process would work out which version of the Npm package to install and then ensure that it's installed at the app's top level.

Similarly, rather than app authors just installing NPM packages locally, we could do this:

```
meteor add-npm ...
```

That way the build process would track the packages that are locally required too and ensure that everything works together.

**Comment by bySabi** [comment]
do you see this thread?: https://github.com/meteor/meteor/issues/5890#issuecomment-171871130

**Comment by timothyarmes** [comment]
I, I hadn't. I'll close this and discuss over there. Thx.
