### ISSUE TITLE
[1.3-modules-beta.4] Plugin Compiler .addJavaScript not working

### ISSUE THREAD

**Issue by huttonr** [meteor/meteor#6014]
##### *(Applies to Meteor v1.3-modules-beta.4)*

The isobuild:compiler-plugin's `addJavaScript` seems to have been broken (or partially broken) at least as it applies to the non-caching compiler.

The javascript added with `addJavaScript` does not ever get executed.

#### Example:

```javascript
const path = Plugin.path

Plugin.registerCompiler({
  extensions: [],
  filenames: ['testcompile.json']
}, () => new TestPackCompiler)

class TestPackCompiler {
  processFilesForTarget(filesFound) {
    let settingsFile = filesFound[0]

    // This shows up fine in the server console
    console.log('\ntestpack compiler is being executed...')

    // But the added javascript will never be executed
    settingsFile.addJavaScript({
      data: 'console.log("SUCCESS!"); alert("SUCCESS!");',
      path: path.join('client', 'successmessage.js')
    })
  }
}
```

#### Git bug reproduction:

https://github.com/huttonr/meteor-addjavascript-bug

**Comment by huttonr** [comment]
*The plot thickens...*  I have no idea why, but changing

```javascript
  settingsFile.addJavaScript({
    data: 'console.log("SUCCESS!"); alert("SUCCESS!");',
    path: path.join('client', 'successmessage.js')
  });
```

to

```javascript
  settingsFile.addJavaScript({
    data: 'console.log("SUCCESS!"); alert("SUCCESS!");',
    path: path.join('client', 'test.js')
  });
```

randomly causes it to work...

Yet no other filename + directory combo that I tried would work, but for some reason `client/test.js` works.

**Comment by benjamn** [comment]
Not to say this isn't a bug, but does `meteor reset` (or `rm -rf .meteor/local/build`) help at all with this problem? Warning: this will delete any local development data, as you probably know.

**Comment by timothyarmes** [comment]
Hi.  No, it doesn't.

**Comment by emgee3** [comment]
Agreed. `meteor reset` does not affect this.

**Comment by huttonr** [comment]
@benjamn 
I did try a meteor reset as well as pulling the data in fresh, cloned from the repo but still to no avail.  Others are having similar problems as well it seems though to problem isn't limited to the json extension as the reproduction shows.

See also:
https://github.com/meteor/meteor/issues/6014#issuecomment-172298132
https://github.com/meteor/meteor/issues/6031
https://github.com/meteor/meteor/issues/6017

**Comment by avital** [comment]
@huttonr Did you mean to close this issue?

**Comment by huttonr** [comment]
Yikes, thanks avital.  Did not mean to close it.

**Comment by huttonr** [comment]
Purely as a help in case anything had yet been pushed to try to fix it, this remains an issue in beta 7.

**Comment by benjamn** [comment]
@huttonr I think [this optimization](https://github.com/meteor/meteor/blob/143121d644d866f0e5f03dc2c731ac2c43cef6dc/tools/isobuild/compiler-plugin.js#L384-L388) may be the culprit. Before I blindly remove that clause, though, what side effects were you expecting to see from eagerly evaluating `.json` files?

A temporary workaround would be to `import "settings.json"` somewhere in your app code, just to make sure that file ends up in the bundle.

**Comment by huttonr** [comment]
@benjamn Thank you for the response.  That would make sense.  There are a couple of build plugin packages that eagerly evaluate json files and intentionally output js and css side effects.

My specific use case is https://github.com/huttonr/bootstrap3/

My only concern is that changing the file extension from `.json` to something else didn't cause it to work when I tested it last...

**Comment by huttonr** [comment]
I just tested a different file extension and this did work.

So the [optimization](https://github.com/meteor/meteor/blob/143121d644d866f0e5f03dc2c731ac2c43cef6dc/tools/isobuild/compiler-plugin.js#L384-L388) you referenced does seem to be the culprit.  Could this be reverted so as to not break plugins that rely on eagerly evaluated json having side effects.

**Comment by timothyarmes** [comment]
This breaks translation plugins such as universe:i18n too.

**Comment by benjamn** [comment]
This should be fixed in `beta.11`. Thanks for the report and the reproduction!
