### ISSUE TITLE
[1.3-modules-beta.4] addJavascript method from CompilerPlugin doesn't work from JSON source

### ISSUE THREAD

**Issue by emgee3** [meteor/meteor#6017]
`file.addJavaScript(...)` fails silently from JSON file source. The same plugin, from a different extension works. See reproduction https://github.com/emgee3/1.3-modules-beta.3-repro. This affects both OS X and Linux. Browser does not matter, as it affects the command line as well.

While this may be by design, it's a breaking change from 1.2, and breaks [huttonr:bootstrap3](https://github.com/huttonr/bootstrap3/) and [huttonr:bootstrap4](https://github.com/huttonr/bootstrap4/).

In the reproduction, uncommenting line 5 and commenting line 4 does work properly https://github.com/emgee3/1.3-modules-beta.3-repro/blob/master/packages/sj/plugin/sj-compiler.js#L4-L5

**Comment by emgee3** [comment]
Duplicate of https://github.com/meteor/meteor/issues/6014

**Comment by huttonr** [comment]
In this reproduction: https://github.com/huttonr/meteor-addjavascript-bug  it doesn't seem to matter what the file extension is.

**Comment by emgee3** [comment]
@huttonr, you wanna see something even weirder? Rename `successmessage.js` on https://github.com/huttonr/meteor-addjavascript-bug/blob/master/packages/testpack/plugin.js#L19 to `test.js` and it works.
