### ISSUE TITLE
13-second hot code reload times in 1.3 beta 4

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6020]
I'm getting pretty bad wait times for hot code reload to initiate. This is my list of Meteor packages:

```
accounts-facebook        1.0.6  Login service for Facebook accounts
accounts-twitter         1.0.6  Login service for Twitter accounts
ecmascript               0.3.1-modules.4  Compiler plugin that supports ES201...
es5-shim                 4.3.2-modules.4  Shims and polyfills to improve ECMA...
fortawesome:fontawesome  4.5.0  Font Awesome (official): 500+ scalable vector...
fourseven:scss           3.4.1  Style with attitude. Sass and SCSS support fo...
http                     1.1.2-modules.4  Make HTTP calls to remote servers
kadira:flow-router       2.10.0  Carefully Designed Client Side Router for Me...
meteor-base              1.0.1  Packages that every Meteor app needs
mobile-experience        1.0.1  Packages for a great mobile user experience
mongo                    1.1.4-modules.4  Adaptor for using MongoDB and Minim...
pauli:accounts-linkedin  1.2.0  Accounts service for LinkedIn accounts
service-configuration    1.0.6-modules.4  Manage the configuration for third-...
standard-minifiers       1.0.3-modules.4  Standard minifiers used with Meteor...
static-html              1.0.4-modules.4  Define static page content in .html...
tracker                  1.0.10-modules.4  Dependency tracker to allow reacti...
```

And my NPM packages:

```
  "dependencies": {
    "material-ui": "0.14.x",
    "materialize-css": "0.97.x",
    "react": "0.14.x",
    "react-dom": "0.14.x",
    "react-fontawesome": "0.x",
    "react-mounter": "1.x",
    "react-tap-event-plugin": "0.x"
  }
```

**Comment by saturnaut** [comment]
@ffxsam Does this happen after the Meteor instance has been running for some time? I've seen hot code reload times like this after I've had an app running for a few hours while developing (on both 1.2 and 1.3). Some sort of memory leak?

**Comment by ffxsam** [comment]
Never mind, I realized it's probably due to the fact that this is a Cordova project and so it has to do extra work besides the usual web-only build. So this is probably normal, yes?

**Comment by dgreensp** [comment]
What sort of wait times?  Are you talking about Cordova hot code push?

**Comment by ffxsam** [comment]
About 10-13 seconds before my browser (not mobile device) starts to reload.

**Comment by dgreensp** [comment]
I'm currently investigating build performance.  More to come: https://github.com/meteor/meteor/issues/6058

Thanks!

**Comment by ffxsam** [comment]
Thanks for the hard work!

**Comment by dgreensp** [comment]
I think it is "normal" but still begs for some improvement.  Keep trying the betas.  beta.7 has more performance improvements, and beta.8 will have more.   It might not crush the time down but it should help.
