### ISSUE TITLE
Mongo errors lead to unclear Meteor errors

### ISSUE THREAD

**Issue by talsraviv** [meteor/meteor#6021]
Hi! I wanted to report a case where a Mongo RangeError leads to a Meteor Error, but with no description.

In my code, I am inserting a document that causes a Mongo RangeError

```
MyCollection.insert(doc_that_causes_an_error);
```

and causes Meteor to print this error and stop execution with no stack trace or description:

```
Exception while invoking method 'my_method_name' undefined
```

I was able to solve this by adding an error callback to my insert statement:

```
MyCollection.insert(doc_that_causes_an_error, function(error, id){
    console.log('error? ', error); 
    console.log('id? ', id);
});
```

which instead printed the descriptive error:

```
error? [RangeError: Maximum call stack size exceeded]
```

I am guessing this is related to [this line](https://github.com/meteor/meteor/blob/5b4e1c6d39f846198ea3fc987bbca6c1a5293131/packages/ddp-server/livedata_server.js#L739), and not sure how to fix, but thought it would be useful to bring this up.

Thank you!

EDIT: It is clear to me that the Mongo error is reported asynchronously which is probably why Meteor can't easily report it.

**Comment by stubailo** [comment]
Do you have a reliable reproduction that we could run to cause a RangeError? Then it would be a lot easier to build a fix.

**Comment by talsraviv** [comment]
Yes! I was causing it with circular reference inside a javascript object, then trying to save that object to Mongo.

You should be able to reproduce it by creating any circular object that can't be serialized:

```
var a = {}
a.b = a;
MyCollection.insert(a);
```

**Comment by hwillson** [comment]
I've just verified that running

```js
const widget = { name: 'Some Widget' };
widget.meAgain = widget;
widgetsCollection.insert(widget);
```

with Meteor 1.4.3.1 throws the proper `RangeError` with description:

**Client:**

```
ejson.js?hash=0f17ced…:492 Uncaught RangeError: Maximum call stack size exceeded
    at Object.EJSON.clone (ejson.js?hash=0f17ced…:492)
    at ejson.js?hash=0f17ced…:531
    at Function._.each._.forEach (underscore.js?hash=cde485f…:157)
    at Object.EJSON.clone (ejson.js?hash=0f17ced…:530)
    at ejson.js?hash=0f17ced…:531
    at Function._.each._.forEach (underscore.js?hash=cde485f…:157)
    at Object.EJSON.clone (ejson.js?hash=0f17ced…:530)
    at ejson.js?hash=0f17ced…:531
    at Function._.each._.forEach (underscore.js?hash=cde485f…:157)
    at Object.EJSON.clone (ejson.js?hash=0f17ced…:530)
```

**Server:**

```
RangeError: Maximum call stack size exceeded
    at packages/mongo/mongo_driver.js:112:20
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at replaceTypes (packages/mongo/mongo_driver.js:112:5)
    at packages/mongo/mongo_driver.js:113:23
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at replaceTypes (packages/mongo/mongo_driver.js:112:5)
    at packages/mongo/mongo_driver.js:113:23
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at replaceTypes (packages/mongo/mongo_driver.js:112:5)
    at packages/mongo/mongo_driver.js:113:23
```

As such, we should be good here. Closing - thanks for reporting this originally!

**Comment by Floriferous** [comment]
If it can help anyone, I just stumbled on this again.

For my part, I was returning an entire class from one of my methods:

```js
Meteor.methods({
  doStuff() {
     // This class method actually returned `this`, which led to the crash
    return SomeClass.doStuff();
  }
})
```

So be careful with what you send back to the client, it could also lead to a security issue!
