### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by peernohell** [meteor/meteor#6022]
package like pkginfo didn't work due to __dirname not defined.

to reproduce:

```
git clone https://github.com/peernohell/test-winston
cd test-winston
meteor --release 1.3-modules-beta.4
```

build error:

```
W20160117-14:36:33.711(1)? (STDERR)
W20160117-14:36:33.711(1)? (STDERR) /Users/peernohell/.meteor/packages/meteor-tool/.1.1.11-modules.5.y3ac7i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160117-14:36:33.711(1)? (STDERR) 						throw(ex);
W20160117-14:36:33.712(1)? (STDERR) 						      ^
W20160117-14:36:33.752(1)? (STDERR) ReferenceError: __dirname is not defined
W20160117-14:36:33.752(1)? (STDERR)     at meteorInstall.node_modules.pkginfo.lib.pkginfo.js (node_modules/pkginfo/lib/pkginfo.js:133:1)
W20160117-14:36:33.752(1)? (STDERR)     at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
W20160117-14:36:33.752(1)? (STDERR)     at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
W20160117-14:36:33.753(1)? (STDERR)     at meteorInstall.node_modules.winston.lib.winston.js (node_modules/winston/lib/winston.js:14:1)
W20160117-14:36:33.753(1)? (STDERR)     at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
W20160117-14:36:33.753(1)? (STDERR)     at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
W20160117-14:36:33.753(1)? (STDERR)     at meteorInstall.server.main.js (/Users/peernohell/projects/test-winston/.meteor/local/build/programs/server/app/app.js:42:16)
W20160117-14:36:33.753(1)? (STDERR)     at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
W20160117-14:36:33.753(1)? (STDERR)     at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
W20160117-14:36:33.753(1)? (STDERR)     at /Users/peernohell/projects/test-winston/.meteor/local/build/programs/server/app/app.js:4472:1
=> Exited with code: 8
```

**Comment by acemtp** [comment]
I have the same issue :/

**Comment by mkumas** [comment]
Same problem here. The module local variable __filename is also causing the same problem. One important thing to note is: when importing the npm module from within meteor, instead of using the 1.3beta's commonjs require or ES6 import syntax; installing Meteorhacks:npm and using Meteorhacks' Meteor.npmRequire method gives no error.

in https://github.com/peernohell/test-winston/blob/master/server/main.js

import winston from 'winston'; //ReferenceError: __dirname is not defined

var winston = Meteor.npmRequire('winston'); //WORKS

It seems that if one uses 1.3beta's import or require, any imported module and its dependencies doesn't have access to __dirname and __filename variables.

**Comment by benjamn** [comment]
Closing in favor of this umbrella issue: https://github.com/meteor/meteor/issues/6055

**Comment by shallwefootball** [comment]
i use var winston = Npm.require('winston'). so done

**Comment by afang** [comment]
Same issue with https://github.com/mikaelbr/node-notifier/issues/102#issuecomment-187661084

**Comment by benjamn** [comment]
Try using just `require` instead of `Npm.require`. The `__filename` and `__dirname` variables should be defined as of `beta.11`.

**Comment by slaphead** [comment]
Hi there,
I am trying to use lob.com's api and the require is still getting this:
ReferenceError: __dirname is not defined

With other APi's it seems ok, but lob specifically has this issue. Is it still ok to use Npm.require in this instance or what can I check for?

**Comment by garrisons** [comment]
I'm having the same issue as @slaphead... Trying to implement lob.com's api and no luck... 

I've tried using Npm.require and a whole host of other items, but nothing was successful.
