### ISSUE TITLE
Error in docs for Template.dynamic

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#6024]
Problem with Template.dynamic section of the docs as shown here:

> Template.dynamic allows you to include a template by name, where the name may be calculated by a helper and may change reactively. The data argument is optional, and if it is omitted, the current data context is used. It's also possible, to use Template.dynamic as a block helper (
  
    
    
>  )

> For example, if there is a template named "foo", {{> Template.dynamic
template="foo"}} is equivalent to {{> foo}} and {{#Template.dynamic template="foo"}} ... {{/Template.dynamic}} is equivalent to {{#foo}} ... {{/foo}}.

http://docs.meteor.com/#/full/template_dynamic

**Comment by stubailo** [comment]
What's the error? You quoted the text, but I'm not sure which part you are referring to.

**Comment by elie222** [comment]
as a block helper (

)

empty lines and parenthesis

**Comment by stubailo** [comment]
Ah, thanks.

**Comment by stubailo** [comment]
Fixed: http://docs.meteor.com/#/full/template_dynamic

Thanks!
