### ISSUE TITLE
Removing a cappedCollection in Meteor

### ISSUE THREAD

**Issue by thinkholic** [meteor/meteor#6025]
Is there any way to delete/dropped cappedCollection created by using `_createCappedCollection` method? I tried `collection.remove({}}` and it's obviously not working and checked in the repo and couldn't found any method related.

**Comment by stubailo** [comment]
According to the MongoDB docs, you can't remove documents from a capped collection, you can only drop the collection: https://docs.mongodb.org/manual/core/capped-collections/#document-deletion

Have you tried `collection._dropCollection()`?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it doesn't seem to be a Meteor issue.

Though, to my knowledge, capped collections are managed/truncated entirely on the server, you would need to drop/recreate the collection to remove it's documents.
