### ISSUE TITLE
accounts.sendverificationemail not work after set root_url

### ISSUE THREAD

**Issue by meepeek** [meteor/meteor#6026]
First I run a server and then tested with these syntax on meteor shell:
```
Email.send({to: "[[EMAIL]]", from: "[[EMAIL2]]", subject: "subject test", text: "this is a test email from meteor"})
```
```
Accounts.sendVerificationEmail([[UID]])
```
Both of them trigger my mail server and sending email as expected.

Then I added this line to my script and run the server again:
```
export ROOT_URL=[[IP_ADDRESS]]
```
Running the first syntax still sending me the email but the second one (Accounts.sendVerificationEmail) did nothing at all. I checked my mail server log and there was no trace of meteor mailing attempt.

Tested on both 1.2.1 and 1.3-modules-beta.4

**Comment by avital** [comment]
I am extremely surprised that you see this. `Accounts.sendVerificationEmail` literally calls `Email.send`: https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_server.js#L781

Are you sure this is what you're seeing? If so, we'll need a reproduction to investigate this.

**Comment by meepeek** [comment]
I cannot reproduce the issue as I started my dev server today with the same script on both versions. I will let you know if I could reproduce. It could be a false alarm, I am very sorry.
