### ISSUE TITLE
1.3-beta4: How to modify ecmascript and babel config?

### ISSUE THREAD

**Issue by dotansimha** [meteor/meteor#6028]
**_1 Upvote**_ Hi,
I am trying to use 1.3-beta4 and modify babel options to enable some es7 features I need. 
I followed the instructions in https://github.com/meteor/meteor/issues/5246 , but it does not work in 1.3-beta4... I create the `.babelrc` file, but it looks like it does not in use - the ES7 features I try to turn on are not available.

Any ideas?

**Update:**
I managed to modify it by editing some code in `babel-runtime` and `babel-compile`, but there is any ideas about how to perform it without modifying the packages?

Thanks.

**Comment by barbatus** [comment]
It looks like `.babelrc` is not supported. At least I looked into the code and didn't find it, see
https://github.com/meteor/meteor/tree/release-1.3/packages/babel-compiler

I suppose we need a wrapper with manually added whitelist options as it was before since it's still considered "added at your own risk" (see https://github.com/meteor/meteor/issues/5246#issuecomment-146025676). We also need to set a bunch of Babel plugins to transpile some of Angular2's syntax right (see https://github.com/shuhei/babel-angular2-app). Hopefully Meteor 1.3 with `Npm.depends` has made  possible configuring Babel with plugins.

**Comment by dotansimha** [comment]
Thanks @barbatus 
It actually needed for Angular2-Meteor, we need to enable es7.decorators in order to use Angular2 with Meteor 1.3 without external compiler. 
I thought about some ideas, and I think that enabling `.babelrc` is one solution that might work (we also need to modify `babel-runtime` and add some more `babelHelpers` to support decorators), but I think that Meteor should provide the ability to use a package and configure it when declaring it's usage, for example:
```js
// package.js
// ...
api.use('ecmascript', ['client', 'server'], {
  // custom config that will be passed into the ecmascript package
}

api.use('babel-compiler', ['client', 'server'], {
  // custom config that will be passed into the babel-compiler' package
  extraWhitelist: [
       // ...
  ]
}
// ...
```

What do you think?

**Comment by barbatus** [comment]
@dotansimha Yes, this looks like what we actually need instead of `. babelrc `.

**Comment by luisherranz** [comment]
+1 here :+1:

**Comment by benjamn** [comment]
Opened a task to enable decorators: https://github.com/meteor/meteor/issues/6057

Making Babel more configurable is still a risky proposition (see [my comment](https://github.com/meteor/meteor/issues/5246#issuecomment-146025676) mentioned above), but definitely something we can consider after upgrading to Babel 6 (which is happening in the 1.3 release).

**Comment by luisherranz** [comment]
Thanks @benjamn

**Comment by dotansimha** [comment]
Thanks @benjamn !

**Comment by rclai** [comment]
@benjamn, does using a custom `.babelrc` not work yet since upgrading to Babel 6?

**Comment by abernix** [comment]
@dotansimha Can this be closed?  Meteor does support `.babelrc` now.

**Comment by dotansimha** [comment]
@abernix yeah sure, thanks!
