### ISSUE TITLE
Meteor destroys npm package

### ISSUE THREAD

**Issue by benjamin79** [meteor/meteor#6029]
Strage thing happened. I just added a html dropdown. On rebuild i got: Can't find npm module 'gm'.
But i never removed it. Then removing and adding it back again to package.json solved the error.

I know, not much info i can give. And i can´t reproduce it. But without any change that should´t happen.

What might be the reason for this?

thanks

**Comment by rdickert** [comment]
I agree, that's really strange. Without a way to reproduce this, unfortunately, it's unlikely that we'll be able to verify and then fix the problem. Could anything be happening with your local file system that's unrelated to Meteor or Node? Also, are you using `meteorhacks:npm` to include the node package? If so, you'd need to check [over there](https://github.com/meteorhacks/npm/).

If it has only happened once and you aren't experiencing ongoing problems, I think we should just close it and assume there was some outside cause. Let me know what you think.

**Comment by benjamin79** [comment]
Yes, i use meteorhacks:npm. It happend some months ago also. I thought i post it here so if other might experience the same we can make out a possible cause.

thanks
