### ISSUE TITLE
Problem: Error in http://docs.meteor.com/#/full/

### ISSUE THREAD

**Issue by phfrohring** [meteor/meteor#6030]
Recipe: 
  - Chrome Version 47.0.2526.111 (64-bit)
  - got to: http://docs.meteor.com/#/full/quickstart

Result:
![screen shot 2016-01-18 at 17 02 07](https://cloud.githubusercontent.com/assets/10885649/12396070/b659818c-be05-11e5-9703-3b925e0cf9f8.png)

**Comment by stubailo** [comment]
I don't get this error when I go to the page, and I have the same Chrome. Can you check again if it is happening? And is it consistent, or only sometimes?

**Comment by phfrohring** [comment]
Hi! I just tried it again and... it's gone! No idea why... This issue may be closed I guess.

**Comment by stubailo** [comment]
Ok, glad it solved itself!
