### ISSUE TITLE
Build Plugins broken under 1.3 beta 4 when using ecmascript

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#6031]
Hi,

After converting my project to 1.3 beta 4 there was one package that wasn't working for me (universe:i18n). I eventually tracked this down to a build plugin/ecmascript issue, and I've created a [tiny project to demonstrate the bug](https://github.com/meteor/meteor/files/94961/buildPluginTest.zip).

The project contains 2 packages. The `compile` package takes a .json file as an input and outputs it to the console when the application starts up.

The `test` package contains a .json file for the `compile` package to compile.

When you `meteor run` the server terminal (and the browser console) will display this:

```
{ hello: 'Hello World' }
```

Now, edit the test/package.js and add a dependency for `ecmascript` (uncomment the line concerned). Running the app will no longer display the text because the code generated by the compile plugin isn't included in the project.

I have checked that `addCompileResult` is still being run. The problem is that the result from this isn't being added to the final source code.

**Comment by cristo-rabani** [comment]
It seems like ecmascript steals all json files, because *.i18n.json isn't attached to bundle of meteor (of course after compilation to js). For *.i18n.yml all locales are attached to bundle.

**Comment by timothyarmes** [comment]
I see that this is already reported in #6014. I'm closing this one.
