### ISSUE TITLE
[1.3-modules-beta.4] cannot find core modules

### ISSUE THREAD

**Issue by sup** [meteor/meteor#6032]
recently i wanted to try out the modules beta, so i went ahead and did `npm i -S gravatar-url`. i then put `import gravatar from 'gravatar-url'` somewhere in my `lib` folder. now, though, chrome throws me this nice error:

<img width="392" alt="screen shot 2016-01-18 at 21 59 51" src="https://cloud.githubusercontent.com/assets/6078550/12402685/d66205d4-be2e-11e5-92a7-99931d009714.png">

this also blocks the entire load

am i missing something really obvious, or is this a legit bug?

**Comment by nathan-muir** [comment]
It appears that your import statement is running on both the client & the server.

At the moment, the modules beta doesn't provide client versions of core modules [like webpack does](https://github.com/webpack/webpack/blob/72e8dd01475841b5123607efd8b3c7b892c1a32a/lib/node/NodeSourcePlugin.js).

So for now, this will only work if you import it on the server. (eg, put code under `server/lib`)

**Comment by sup** [comment]
@nathan-muir thanks for clearing that up. but is the module only available on the server then?

**Comment by avital** [comment]
We're tracking these suggestions here: https://github.com/meteor/meteor/issues/6056
