### ISSUE TITLE
[1.3-modules-beta.4] Load TS modules without extension.

### ISSUE THREAD

**Issue by barbatus** [meteor/meteor#6034]
In order to load a module compiled from TypeScript file I need to specify extension explicitly, i.e.:
 `import ./foo.ts` to load exports located in `foo.ts` file.
I seems to be because of this
https://github.com/meteor/meteor/blob/b63d9b7d3d39b774ab3915ffc38cfaffa20a8bfa/tools/isobuild/import-scanner.js#L18; there are only two extension supported: `js`, `json`.

Do you plan to add other extension there or come with any other general way to load files w/o specifying extension?

**Comment by benjamn** [comment]
My goal was to support the same extensions as Node, so I'm not planning to try `.ts` when no extension is specified. Is this just a question of convenience, or does it prevent you from using TypeScript at all?

**Comment by barbatus** [comment]
@benjamn Yes this prevents me to use TypeScript in a Meteor package with added `modules` package.
Modules package's Atmosphere page clearly states that modules are going to be supported for the packages as well (via import `meter/package_name`).
But it is turning out old style packages are not in priority now, and everything is preferred to be a NPM.
Another one issue I bumped into on this side (except current one) is this [one](https://github.com/meteor/meteor/issues/6010). Can you please look into?
It’s turned out same NPMs can’t be shared between an app and a Meteor package, since result JS bundles (of the app and package) has own versions of imported NPMs.

**Comment by avital** [comment]
Hi @barbatus, I am confused trying to follow your explanation. Other than your other ticket, what is the specific issue if you need to write `import [...] from ./foo.ts`?

**Comment by barbatus** [comment]
@avital Thanks that looked into. The specific issue is that unusable in IDEs. Every IDE's TypeScript will curse on imports like that.

**Comment by avital** [comment]
@stubailo persuaded me that this is important to allow jsx example code to work out-of-the-box in Meteor.

**Comment by Urigo** [comment]
thank god for @stubailo ! ;)

**Comment by benjamn** [comment]
We're convinced this is important for 1.3, but let's consolidate further discussion over at #6151.

**Comment by benjamn** [comment]
With [this commit](https://github.com/meteor/meteor/commit/22d423e5a5a1944b81870f4a2da7022a2fd45eed), the list of optional import extensions will be determined automatically by the compiler plugins that are enabled. So if you have a compiler plugin that handles the `ts` extension, you can import `.ts` files without an explicit extension. Note, however, that the `.js` and `.json` extensions will always be tried first.
