### ISSUE TITLE
[1.3] Style files in local packages

### ISSUE THREAD

**Issue by juliancwirko** [meteor/meteor#6036]
It seems that Meteor 1.3 (beta 4) includes all style files from local packages. Even when they are not added by addFiles. Why is that?

Example: 
I have package which have some .styl files in addFiles and some are just not used. They are in main package folder in for example /packages/my-package Now in 1.2 they are ignored and only those from addFiles are bundled and in 1.3 they are also bundled which is in my opinion wrong, but maybe I don't have a broader view of something.

**Comment by avital** [comment]
Fixed by b04c837. Should be out with the next beta release very soon!

**Comment by ljack** [comment]
Running beta 8 and have errors with html files (pure html not blaze template) being included without it being the intention:
https://forums.meteor.com/t/meteor-1-3-modules-beta-8-auto-including-all-html-files
