### ISSUE TITLE
Error message is not helpful: inconsistent dependency constraint across unibuilds?

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#6039]
I really need some help. Since this morning my meteor project gives me this error whenever I try to run it:

```
Error: inconsistent dependency constraint across unibuilds?
    at [object Object]._.extend.getDependencyMetadata (/tools/isobuild/package-source.js:1452:15)
    at /tools/packaging/catalog/catalog-local.js:316:41
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    ....
```

I've tried absolutely everything I can think of to get this sorted:
- I've gone back to previous versions of the code base that were working perfectly before
- I've run `meteor reset`
- I've deleted my entire ~/.meteor folder, thus forcing a reinstallation of meteor + packages
- I've run `meteor update`
- I've rebooted my machine!

I have other projects that work, but this one now refuses. What on Earth could be going on?

**Comment by dgreensp** [comment]
Hi @timothyarmes,

I don't know how that could happen, but the code that throws that error is reading a local package from disk and finding its dependencies (as specified by `api.use`) somehow invalid.  Some rare packages create local packages (like `meteorhacks:npm`).  Beyond that, I don't know.

**Comment by timothyarmes** [comment]
I'd be happy with that explanation if it wasn't for the fact the the problem persists when I check out previous versions of the code....

**Comment by timothyarmes** [comment]
Hi,

24 hours later, I've finally found the issue. Thank you @dgreensp for putting me on the right track. I did indeed have a local package with corrupted dependencies. In my own project I had a symbolic link to the corrupted package, so checking out previous versions of my code made no difference to the symbolic link!!

I'm not closing the issue since the lack of a useful error message cost me an entire day. It should have at least stated in which package the error was occurring.

Tim

**Comment by timbotnik** [comment]
Updated the title to reflect that the issue is related to the error message.

**Comment by trusktr-goin** [comment]
The cause for me was listing a package twice inside of package.js, for exampe:

```js
Package.onUse(function(api) {
  // ...
  api.use('matb33:collection-hooks@0.8.0')
  // ...
  api.use(["matb33:collection-hooks@0.8.1"], "server");
  // ...
})
```

**Comment by awatson1978** [comment]
The cause for me was updating the versions in ``use()``, and forgetting to update the associated ``imply()``.

````js
  api.use([
      "aldeed:collection2@2.5.0",
    ]);

  api.imply([
      "aldeed:collection2@2.9.0",
    ]);
````

**Comment by hwillson** [comment]
This is functioning as designed, but that error message could definitely be made a little more user friendly.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Error%20message%20is%20not%20helpful%3A%20inconsistent%20dependency%20constraint%20across%20unibuilds%3F&body=Migrated%20from:%20meteor/meteor%236039) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by AlberErre** [comment]
Same problem as **awatson1978**, check versions for both:
`api.use` and `api.imply`

**Comment by micktaiwan** [comment]
Same pb as ghost: the cause of this error for me, was listing a package twice inside of package.js.
The error message is still misleading.
