### ISSUE TITLE
Use pinned Cordova plugin versions to avoid installing incompatible core plugins

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#6040]
Adding Cordova plugins, either as package dependencies or directly through `meteor add`, always requires specifying an exact version. We don't have any version resolution mechanism however, so there is no way of telling which version of a plugin will be installed when multiple packages specify a dependency on different versions.

One place where this leads to a lot of trouble is when a newer version of Meteor upgrades its Cordova platforms. The upgrade to Cordova iOS 4.0 in Meteor 1.3 for instance, will mean that many existing projects that use plugins will fail with a non-obvious compiler error.

You will have to manually go through all your direct and indirect dependencies and make sure their plugin dependencies specify the latest supported version of all plugins. 

Besides the manual updating, another issue here is that there is no easy way of finding out what the latest supported version of a plugin actually is. To find out that `cordova-plugin-camera` now has to be updated to `2.0.0` you will have to check for the latest version on NPM yourself and hope that is the version required. If version `3.0.0` is released later and doesn't work with the platform versions your Meteor installation bundles, it will also fail at compile time and you will have to try an earlier version until you find something that works.

Cordova itself has recently introduced the notion of pinned plugin versions for core plugins (https://github.com/apache/cordova-lib/commit/b704e7870a8a3af413fbf2db3e6f9d83d1677abd). This specifies the versions of plugins that a Cordova release has been tested with. (Also see https://github.com/riknoll/cordova-discuss/blob/plugin-versioning/proposals/plugin-verion-fetching.md for some possible future directions.)

We could use this information to either warn users about incompatibilities (so they are not faced with non-obvious compiler errors) or even to automatically solve the problem by overwriting the user specified plugin versions with the pinned versions (maybe as a minimum requirement). The latter could be confusing because we'd basically ignore the package and user version dependencies. But then, we don't have a real version resolution mechanism anyway, so any other package could have also overwritten any plugin dependencies.

Especially for core plugins, it seems there is almost never a good reason to have to rely on specific versions. If you want to use `cordova-plugin-camera`, you want to use the latest version that works with your current Cordova platform versions. So if we decide to somehow use the pinned plugin versions, we may want to support `meteor add cordova:cordova-plugin-camera` without a version specification as well.

**Comment by avital** [comment]
What is the lowest effort solution that is acceptable (not ideal)?

**Comment by martijnwalraven** [comment]
The lowest effort solution is putting a warning in the documentation, but I'm afraid that would still lead to issues and forum posts from people who encounter these errors.

**Comment by avital** [comment]
And above that, can we just detect that people are old versions. If so, print a link to a single Wiki page with instructions?

**Comment by martijnwalraven** [comment]
If we are detecting that people are using an old version, we also know the minimum version (because that is what we will be testing against). So at that point we could just as well tell them what version they should upgrade to, or even bump the version ourselves.

**Comment by avital** [comment]
Why would we do that work? What if we get the logic wrong, then we'd have to fix the code, etc, build a new release. Modifying wiki pages is easy. We can add more "features" going forward whenever we want

**Comment by martijnwalraven** [comment]
The logic isn't too complicated, and I think helping users in cases like this is one of the strengths of the platform.
