### ISSUE TITLE
Decide what to do about mdg mobile-packages

### ISSUE THREAD

**Issue by martijnwalraven** [meteor/meteor#6041]
We should decide whether there is any value in maintaining `mdg:camera`, `mdg:geolocation` and `mdg:reload-on-resume` in https://github.com/meteor/mobile-packages, or whether it would make more sense to deprecate them.

**Comment by avital** [comment]
Why are we tying this to 1.3?

**Comment by martijnwalraven** [comment]
It's not necessarily tied to the 1.3 release, but I've had to update the underlying Cordova plugins that it uses and that might uncover new issues (besides the many that are already open). So we should decide whether we are committed to actually making these packages work or whether we should tell people to use the plugins directly with 1.3.

**Comment by avital** [comment]
Sounds like @stubailo said in a previous conversation that we should deprecate them?

**Comment by stubailo** [comment]
Yes, we currently don't maintain them and it would be better to make that clear.

**Comment by martijnwalraven** [comment]
Yeah, we should at least change the README to make that clear.

But I don't think we can simply remove them or make them stop working with Meteor 1.3. Local Market also uses them, and that is still our primary mobile example app.

Is there any way to mark a package as deprecated, or show a warning when it is installed?

**Comment by stubailo** [comment]
I mean we also shouldn't have one of our main example apps have deprecation warnings.

**Comment by lorensr** [comment]
> We should decide whether there is any value in maintaining

I would guess that the majority of production Meteor Cordova apps use at least one (mine uses all 3), it seems like there would be a good amount of value in maintaining. Or barring that, finding an organization to maintain a branch to deprecate in favor of. 

> Is there any way to mark a package as deprecated

Don't think that's a feature of atmosphere, so it would be adding "Deprecated" to pkg description and head of readme.

**Comment by hwillson** [comment]
I've moved this over to https://github.com/meteor/mobile-packages/issues/134. Closing here - thanks!
