### ISSUE TITLE
meteor mongo --url "website.meteor.com" returns service unavailable

### ISSUE THREAD

**Issue by cleor41** [meteor/meteor#6045]
I've been trying to run this command for a day now and it's still unavailable. Is there something wrong with the servers? It's weird because the website runs fine in the browser. Meteor version 1.1.0.3

**Comment by yogiben** [comment]
This is not currently possible with the free Mongo instance that meteor provides.

If this is something you need, consider setting up your own mongo instance (e.g. with compose.io).

**Comment by cleor41** [comment]
I'm trying to back the data up so I can move to a paid service. Is there a service that when switched too it takes all of the data with it?

**Comment by cleor41** [comment]
All of the tools and websites require the mongo url including compose

**Comment by cleor41** [comment]
I'm not sure what's going on with the meteor mongo --url tool but I was able to get this information by console.logging process.env.MONGO_URL and then by checking the remote logs. I noticed the password isn't changing and I also noticed the mongodump command stalls without doing anything. Is this the intended behavior for the free service and is there a place I can go to learn more?

**Comment by cleor41** [comment]
I found a workaround, happy to post it here if anyone wants it.

**Comment by appinteractive** [comment]
sure, let us know :)

**Comment by cleor41** [comment]
You can console.log Meteor.process.env.mongoURL on the server and then access it using meteor logs. Be careful though, it doesn't look like the password is changing anymore. Once you have the URL you can mongodump it to your local hard drive and then mongorestore it Galaxy or Modulus etc

**Comment by cleor41** [comment]
I was trying to figure out what the developers intentions were with that functionality before I posted it because I didn''t know if meteor mongo --url is down on purpose or whatever.
