### ISSUE TITLE
Provide more Node globals like process, __dirname, etc.

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6055]
This is an umbrella issue for providing simple shims for Node global variables. This issue does not include reimplementing built-in modules like `fs` or `http`.

- [x] `process`
  - [x] `platform` (#6046)
  - [x] `nextTick` (#6167, #6198)
  - [x] `env`
    - [x] `process.env.NODE_ENV`
- [x] `global`
- [x] `__dirname` (#6022)
- [x] `__filename`

**Comment by rclai** [comment]
@benjamn, are you able to release a new beta in order to get `__dirname` and `__filename` to work?

**Comment by Sikwan** [comment]
Same problem here:

```shell
W20160216-10:54:27.943(1)? (STDERR) /Users/vandefr/.meteor/packages/meteor-tool/.1.1.13-modules.8.9fhm2j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160216-10:54:27.943(1)? (STDERR) 						throw(ex);
W20160216-10:54:27.943(1)? (STDERR) 						      ^
W20160216-10:54:27.945(1)? (STDERR) ReferenceError: __filename is not defined
```

I assume it is because I use fibers/future in my code but not entirely sure.

**Comment by ffxsam** [comment]
Yes! Following this issue, since some pretty major npm packages (stripe, aws-sdk) do not work.

**Comment by benjamn** [comment]
Everything mentioned in the issue summary is implemented in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).
