### ISSUE TITLE
Provide shims for built-in Node libraries on the client, when possible.

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6056]
Built-in libraries are modules like `fs` and `http`, which have the property that `require.resolve(id) === id`.

Browserify and Webpack make an effort to provide stub implementations of some of these modules, and a number of npm libraries assume the availability of those stubs.

This should be a straightforward matter of mimicking the behavior of Browserify and/or Webpack, but I think it will have to wait until 1.3.1, since it is possible to provide your own stubs currently (it just won't be as automatic as it could be).

cc @stubailo who was asking about this a few days ago

**Comment by stubailo** [comment]
Can we document how to provide stubs in 1.3?

**Comment by stubailo** [comment]
> since it is possible to provide your own stubs currently (it just won't be as automatic as it could be).

I tried doing something like `npm install util` but couldn't get `util` to properly load on the client. Could we pair on this for a second? It's quite important for my current data work.

**Comment by benjamn** [comment]
Hmm, while it might be possible to provide your own stubs on the client as well as the server, I'm realizing it may be very difficult to provide a different version of the stub (or no stub at all) on the server, if your only tool is `npm install`.

For npm packages, a relatively common convention is to have a ["browser" field](https://github.com/substack/node-browserify#browser-field) in the `package.json` file, but there's currently no `package.json` file in the root of a Meteor app, so I'm not sure how to generalize that approach for apps as well as their dependencies.

@stubailo are you mostly trying to get npm packages to work, or do you want your app/packages to be able to use different versions of npm packages on the client and server?

**Comment by stubailo** [comment]
@benjamn I want to use `util` on client and server, which is a core Node package that has a Browserify shim.

**Comment by avital** [comment]
Need to also make sure that `process.nextTick` is defined (see #6198)

**Comment by benjamn** [comment]
While we are not yet providing automatic stubs for builtin Node modules, it is now possible to install most stubs yourself, thanks to the following commits:
https://github.com/meteor/meteor/commit/3ecc3e43a9b5a51f3416a25bd3fcfd8d056210b7
https://github.com/meteor/meteor/commit/90541281ed12fb09c2221ff5c80414c1fd05a98e
https://github.com/meteor/meteor/commit/e4544b5428cc28f52706139a9c00173919102f2e
https://github.com/meteor/meteor/commit/3897fa8634f5f33c6de87cd26a038c76bf5813b8

**Comment by zol** [comment]
Since it's easy, we could make empty stubs the way webpack does for popular imports like `fs`.

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).

**Comment by kachkaev** [comment]
I just got this error after installing [`react-sanfona`](https://github.com/daviferreira/react-sanfona) in Meteor 1.3.2.4. That npm module depends on `uuid` which in turn depends on `crypto`. Even if I `npm install` and then import `crypto` directly, the error in the browser persists.

What could go wrong?

**Comment by benjamn** [comment]
You want `npm install --save meteor-node-stubs` instead of installing `crypto` by itself.
