### ISSUE TITLE
meteor build filenames

### ISSUE THREAD

**Issue by brettg2** [meteor/meteor#6061]
I am using git to track the output of `meteor build` but the scripts and styles are changing file names each time the process runs. This means git thinks the prior version of the scripts are being deleted and the new files are being created / added. 

Example:
```
02fa888b4b14f641de5add8c54923fefdb85c36f.js
737d4405b6d5123d24bbc1339055c0800a7406b4.css
index.html
```
... changing to:
```
05e746150274630cb5732dc013fbd08c7d262996.js
5cd04d43a893cab1c2c43355b3265eca8b063f94.css
index.html
```

(Git sees this as deleting the first files and adding the new, which means redundant data is being stored in the git repository)

Is there a way to use a common file name each time the build process is run instead of using a generated hash string? 

Thank you.

**Comment by rdickert** [comment]
Unfortunately, there is not a way to do this as this is the intended behavior. The general intention is that you should ignore build files (this is how the .gitignore file is set up by default) and instead track just the source files. Meteor should reliably give you reproducible builds for any given version of the source files, so tracking compiled files is redundant.
