### ISSUE TITLE
Builtin HTTP Package #Patch

### ISSUE THREAD

**Issue by emars** [meteor/meteor#6064]
Is there a reason why there is not a convenience method for HTTP#Patch?

**Comment by zol** [comment]
Hey @emars, no I can't think of a good reason beyond not many people use it. Feel free to create a PR to add a convenience method for it if you like.

**Comment by stubailo** [comment]
Fixed! 06d64bfcd4a7677c83140324e77c608d804bad77 Thanks @emars
