### ISSUE TITLE
'click' event does not work on iPad Chrome or Safari

### ISSUE THREAD

**Issue by watsokel** [meteor/meteor#6065]
When I run my web app on iPad or iPhone's Chrome or Safari browsers, there is no response to the  'click' event. For instance, in my app, the following does not result in a route: 
```
Template.myTemplate.events({
    'click #my_template': function(){
      Router.go('/somewhere');
    }
}
```
The click event works just fine on localhost or when deployed. I've tried touchstart, but this results in a double fire of the event.

**Comment by zol** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
