### ISSUE TITLE
Parse error building APK

### ISSUE THREAD

**Issue by watsokel** [meteor/meteor#6066]
I followed the instructions on creating the production apk (https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store) but when I email myself the apk and try to install it on my Android phone, I get "Parse error: there was a problem parsing the package."

**Comment by yourcontainer** [comment]
have a some problem, how u fix it?

**Comment by watsokel** [comment]
@yourcontainer, I believe I just misunderstood some of the instructions. In the command below, I think it should be changed from:

```
cd ~/build-output-directory/android/
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 unaligned.apk your-app-name
```
to
```
cd ~/build-output-directory/android/
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 release-unaligned.apk your-app-name
```
or to whatever the name of your unsigned APK is.

Also, I believe I had a different version of the API so I had to change this command from:
 
```
$ANDROID_HOME/build-tools/23.0.0/zipalign 4 \
    unaligned.apk production.apk
```
to
```
$ANDROID_HOME/build-tools/23.0.0/zipalign 4 \
    release-unaligned.apk production.apk
```
