### ISSUE TITLE
MiniMongo: sorting on dates doesn't work

### ISSUE THREAD

**Issue by tifroz** [meteor/meteor#607]
with...

```
mycollection = new Meteor.Collection("mycollection")
mycollection.insert({created: new Date("1/1/2010")})
mycollection.insert({created: new Date("1/1/2011")})
mycollection.insert({created: new Date("1/1/2012")})
```

when fetching, `mycollection.find({}, {sort: {created: -1}})` and `mycollection.find({}, {sort: {created: 1}})` the order of the returned results shouldn't be the same

**Comment by nsinfoPRO** [comment]
Is **miniMongo** date sort now working?

**Comment by afrokick** [comment]
@nsinfoPRO yes, it works
