### ISSUE TITLE
1.3-modules-beta.5:error: Can't load npm module 'babel-runtime/helpers/slicedToArray' from packages/modules-runtime.js. Check your Npm.depends().

### ISSUE THREAD

**Issue by TeemoWan** [meteor/meteor#6076]
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading plugin `compileStylusBatch` from package `stylus`:
   error: Can't load npm module 'babel-runtime/helpers/slicedToArray' from packages/modules-runtime.js. Check your Npm.depends().
   
=> Your application has errors. Waiting for file change.

meteor list
....
stylus                    2.511.2-modules.5  Expressive, dynamic, robust CSS
....

**Comment by jamiter** [comment]
Adding `babel-runtime` with `npm install babel-runtime --save` fixes this. But this should not be required of course...

**Comment by simon-engledew** [comment]
This appears to occur if you use the array destructuring functionality in babel, e.g:

```
_.each(_.pairs(a), function ([key, value]) {
  console.log(key, value);
});
```

Meteor ships with a built-in babel runtime package:

https://github.com/meteor/meteor/tree/devel/packages/babel-runtime

and my guess is that the slicedToArray and slicedToArrayLoose helpers in babel-runtime proper:

https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js

need to be implemented.

**Comment by immuzov** [comment]
@jamiter It's doesn't work. Same error.

**Comment by benjamn** [comment]
@immuzov can you provide a short reproduction repo, or steps to reproduce?

**Comment by kctang** [comment]
I tried both with and without specific version, still getting the same error. Any other options to resolve this now?
    
    ± |master ✗| → npm install babel-runtime@5.8.34 --save
    npm WARN package.json xxx@1.0.0 No description
    npm WARN package.json xxx@1.0.0 No repository field.
    npm WARN package.json xxx@1.0.0 No README data
    babel-runtime@5.8.34 node_modules/babel-runtime
    └── core-js@1.2.6
    
    ± |master ✗| → meteor
    [[[[[ ~/xxx ]]]]]
    
    => Started proxy.
    => Started MongoDB.
    => Errors prevented startup:
    
    While loading plugin `compileStylusBatch` from package `stylus`:
    error: Can't load npm module 'babel-runtime/helpers/slicedToArray' from
    packages/modules-runtime.js. Check your Npm.depends().
    
    => Your application has errors. Waiting for file change.

**Comment by benjamn** [comment]
This particular problem should be fixed in the next beta, thanks to this commit: https://github.com/meteor/meteor/commit/3f3aac4fd1859d4c13ad432b5ad0b4ff0059d0ad
