### ISSUE TITLE
Collections: Collection names limit Multi-DB usefullness

### ISSUE THREAD

**Issue by thomasf1** [meteor/meteor#6077]
This is less of a bug, more of a limitation that probably will come up as new DB drivers get added:

First: Connecting to a 2nd Mongo DB works great.

```coffeescript
xxx = new (Mongo.Collection)("users", _driver: secondDB)
```

If the table names on both DBs are the same though (2x "users" for example), the collection names have to be 2x users which throws an error (which makes sense).

Proposed change: Ability to set the mongo table name and collection name separately (for example an "tablename" attribute falling back to the collection name).

Something like in mongo/collection.js
```javascript
self._collection = options._driver.open(name, self._connection);
```
to

```javascript
self._collection = options._driver.open(options.tablename || name, self._connection);
```

Which would allow something like that:

```coffeescript
xxx = new (Mongo.Collection)("users-db2", {_driver: secondDB, tablename: "users"})
```

Obviously this is just a suggestion up for discussion, maybe there is a better way.

**Comment by zol** [comment]
Thanks for the suggestion. Our [forums](https://forums.meteor.com/) are a better place to create a post discussing feature requests. In this case, check out our blog [post](http://info.meteor.com/blog/reactive-graphql) regarding the reactive GraphQL library we're working on. One of the design goals is going to be to support multiple data sources (including databases). It's unlikely we're going to add this feature to livedata.
