### ISSUE TITLE
$elemMatch projection

### ISSUE THREAD

**Issue by mcchrish** [meteor/meteor#6084]
In meteor mongo shell, this filters out the array elements according to `$elemMatch`:
```
db.campSubscriptions.find({}, {quotes: {$elemMatch: {style: 'moss'}}}).pretty()
```

But in meteor shell, this returns all of the arrays instead:
```
Schema.campSubscriptions.find({},{quotes: {$elemMatch: {style: 'moss'}}}).fetch()
```

**Comment by rdickert** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by KamChanLiu** [comment]
Reproduction here: [https://github.com/KamChanLiu/meteor-issue-6084](https://github.com/KamChanLiu/meteor-issue-6084)

Running the app and opening the client (to trigger a subscribe) you will see in the server log the _$elemMatch_ query returns **all** children of an array:
`[ { name: 'john', school: 102, age: 10 }, { name: 'jeff', school: 108, age: 15 } ]`

Running the same query in meteor mongo will only return a **single** matched element:
Query: `db.school.find({}, { students: { $elemMatch: { school: 102 } } })`
Result: `{ "_id" : "qS56LKh9L4n53kkuT", "students" : [ { "name" : "john", "school" : 102, "age" : 10 } ] }`

Appreciate any further investigation.

**Comment by abernix** [comment]
Thank you for the reproduction @KamChanLiu!

While the results are not what you might expect, both you and the original issue reporter are using `.find()` incorrectly.  The `selector` (criteria) is supposed to be the **1st** element to the `.find()` operator.  The second parameter is meant for `options`.  You currently have your `selector` as an empty object (`{}`).

You will get the same results on both server, client, and shell if you use:

```javascript
.find({ students: { $elemMatch: { school: 102 } } })
```

See the docs for `Meteor.find()` here:
* http://docs.meteor.com/#/full/find

And the docs for Mongo `.find()` here:
* https://docs.mongodb.com/v2.6/reference/method/db.collection.find/

Closing this but please @mention me if you feel like it needs to be reopened!

**Comment by mitar** [comment]
You should do `find({}, { fields: { students: { $elemMatch: { school: 102 } } } })` in Meteor.

**Comment by KamChanLiu** [comment]
@abernix Thanks for the prompt reply.
Moving the $elemMatch to the first .find() parameter did not seem to work as it yields the same results, i.e. it still shows both records.

According to the MongoDB docs, $elemMatch can be used in both [query](https://docs.mongodb.com/v3.0/reference/operator/query/elemMatch/) and [projection](https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/) operators.
Although I'm not sure if this differs in the Meteor implementation.

Using @mitar's query with the fields seemed to work.

I have updated the reproduction repo with all three queries.
[https://github.com/KamChanLiu/meteor-issue-6084](https://github.com/KamChanLiu/meteor-issue-6084)

**Comment by abernix** [comment]
@KamChanLiu Sorry, I misinterpreted your original intention.  Yes, `$elemMatch` works in both query and projectional senses – if you want to use it in the projectional sense (in the second parameter to `.find`), then @mitar's example is what you want (it must be inside a `fields` attribute on the second parameter).  Meteor and MiniMongo just use that slightly different format.

Thanks @mitar for catching the difference there. 😄

**Comment by KamChanLiu** [comment]
Ah that makes sense.
Thanks @abernix and @mitar!!

**Comment by mitar** [comment]
See more here: https://themeteorchef.com/snippets/mongodb-queries-and-projections/
