### ISSUE TITLE
Source Path Too Long ==> 1.3-modules-beta.4

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor/meteor#6088]
Developing in a Windows 8 environment using Meteor and Webpack. After a first build I can't copy the .meteor folder. I get the following message:

```
Source Path Too Long

The source file name(s) are larger than is supported by the file system. Try moving to a [....etc.]
```

NB. I get this error using Meteor 1.3-modules-beta.4. When I tried it at Meteor 1.2 there was no problem.

NB-2. I posted this issue also at the webpack/webpack repository: [issue 1937](https://github.com/webpack/webpack/issues/1937)

**Comment by rozzzly** [comment]
Traditionally, windows/winapi file path has a max length of 256. Sounds like webpack is making a nested dir structure that's too deep. Where's you apps root folder? Moving it to `C:\` might make it short enough. Hacky and not all that helpful, lol. But dont see an easy way to fix this without ripping open the compiler. Id check to see if they have the same restriction for Unicode paths vs cstrings? Or maybe forking deps, giving them shorter names? Haha

**Comment by benjamn** [comment]
Can you provide a simplified reproduction? If so, then we can decide whether this is something we can fix once and for all, or something that may need to be mitigated in some clever way.

**Comment by AnnotatedJS** [comment]
I tried in several ways but could not reproduce the error. Suggest to close this issue.

**Comment by Dominik321321** [comment]
Hello AnnotatedJS, you can try "Long Path Tool" its really awesome, i succeed with it

**Comment by OxanaAngel** [comment]
Long Path Tool worked great for me.
