### ISSUE TITLE
meteor remove-platform browser not supported?

### ISSUE THREAD

**Issue by austinrivas** [meteor/meteor#6091]
running the meteor cli command on Meteor@1.2.1

`meteor remove-platform browser`

results in the console message

```
While removing platforms:
error: browser: cannot remove platform in this version of Meteor
```

Is it truly not possible to remove the browser platform from Meteor at this point in time, or am I missing something?

My use case is a standalone headless Meteor application for monitoring a MongoDB collection for changes and triggering aws lambda functions as a result.

**Comment by stubailo** [comment]
It is truly not possible. It might be possible in a future version. But I don't think you lose much from having a basically empty client-side app, so it's totally fine to make a headless application whose client build is never used.

As this was framed as a question and I think I answered it, I'm going to close the issue. Let me know if you need anything else.

**Comment by austinrivas** [comment]
@stubailo thanks for answering the question

**Comment by Urigo** [comment]
there might be a value in that where you don't need to build the client and it can shorten the build process if you are using your server just as an API (pretty common use case).
Maybe we should label it as a feature request?

**Comment by ramirez530** [comment]
Request

ramirez$14$

there might be a value in that where you don't need to build the client and
it can shorten the build process if you are using your server just as an
API (pretty common use case).
Maybe we should label it as a feature request?

—
Reply to this email directly or view it on GitHub
<https://github.com/meteor/meteor/issues/6091#issuecomment-187185211>.

**Comment by stubailo** [comment]
> there might be a value

I'd rather make sure there is a real value first.

**Comment by M4v3R** [comment]
@stubailo There is real value in this, when you're developing a Cordova app. My client directory is quite complex and the `browser` platform takes a while to build, but I don't need it because it won't work properly in the browser anyway, the only thing I need is `android` and `ios` platforms to build (in my case I don't even need `server`, because I'm using an external DDP server).

**Comment by IamCarbonMan** [comment]
I'd like to request that this issue be reopened. The `browser` platform as a default makes sense for most of Meteor's use cases, but there are use cases that have no reason to include it, for example when building only for `android` or `ios` or when using an alternative DDP client such as those listed [here](http://meteorpedia.com/read/DDP_Clients). Furthermore, there are almost endless possibilities such as @austinrivas example of a headless server application. Meteor's own architecture is built to allow easy integration of the server with different types of clients, and while the browser is most common there is no reason to limit projects not intended for browser use to it.

**Comment by deadjdona** [comment]
+1

**Comment by faisalhasnain** [comment]
👍 its really valuable use case. highly requested. For building services, we don't need browser platform

**Comment by brettg2** [comment]
+1 For us we need a client-side only application therefore we'd prefer to remove the server platform, but as mentioned this is not possible right now. Preferably we'd like the DDP, auto-reload functionality during debugging only, and when the app is built/deployed, the DDP, auto-reload, hot-code-push packages are removed from the production build output. @stubailo I understand you see little value in this request, but there are many different use cases and potential variations to the Meteor framework, not just the server/browser paradigm. Please consider this again! Thank you

**Comment by samoilis** [comment]
++1

**Comment by kwunyeung** [comment]
+++1

**Comment by aproskurin** [comment]
++++1

**Comment by yanickrochon** [comment]
+++++1

**Comment by Oyshoboy** [comment]
++++++1
