### ISSUE TITLE
accounts-github needs to be able to connect to an internal github enterprise

### ISSUE THREAD

**Issue by rgauny** [meteor/meteor#6092]

**Comment by rdickert** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=accounts-github%20needs%20to%20be%20able%20to%20connect%20to%20an%20internal%20github%20enterprise&body=Migrated%20from:%20meteor/meteor%236092) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
