### ISSUE TITLE
1.3-modules-beta.5 - Missing class properties transform.

### ISSUE THREAD

**Issue by haiodo** [meteor/meteor#6096]
Hi,

After update from 1.3-modules-beta.4 to beta.5 following errors become occur on classes with types defined.

example.js
```
/* @flow */
class MyClass {
   myField: string;
}
```
Any plans to return support of flowtype.org back in beta.6?

Best regards,
Andrey.

**Comment by benjamn** [comment]
Class properties are only at stage 1 of standardization, which means the syntax and semantics could still change drastically: https://github.com/tc39/ecma262#current-proposals, https://github.com/jeffmo/es-class-fields-and-static-properties

If you really want to use this feature now, you should fork the `ecmascript` and `babel-compiler` packages.

**Comment by ChrisCinelli** [comment]
How difficult is to add options to enable or add babel modules? For example I would definitely add `stage-0` to my environment. I would also like to add: "transform-decorators-legacy" and "jsx-control-statements".

**Comment by joncursi** [comment]
Agreed. All of my other projects are using early versions of ES7 but due to lack of control over babel we have to write code differently than we would prefer within Meteor.

**Comment by joncursi** [comment]
Hmm, looks like this was actually addressed in 1.3.x? It looks like `.babelrc` support is now a thing!

**Comment by abernix** [comment]
@joncursi `.babelrc` support did come in 1.3.3!  See more in the Meteor forums and Meteor blog!

**Comment by stubailo** [comment]
Coming back on this issue - the syntax _did_ change dramatically! Boy, I'm glad I didn't write a lot of code with the old syntax.

It's in stage 2 now, and I got here by talking to someone who was trying to follow learnapollo.com in Meteor: https://forums.meteor.com/t/learnapollo-meteor-or-how-to-deal-with-the-es7-and-es6-issues/32558

It seems like a lot of React tutorials are now assuming this transform is on, so perhaps it's a good time to switch it on by default? It does depend on how likely it is for the syntax to change.

**Comment by abernix** [comment]
If it were [Stage 3](https://tc39.github.io/process-document/), I'd be more in favor of turning it on right now; it's hard to say how much it will change from Stage 2.

Timing-wise, I might suggest that we review all transforms at closer to 2017-02-01 as this might give ES2017 time to surface (TC39 meeting is sometime in January).  Also, UglifyJS is rumored to get harmony support around then.  I link these two things together only because there might be some similar considerations.

**Comment by mattblackdev** [comment]
Im having this issue with mobx & Meteor 1.4.4.x
example-store.js:
```
import { observable } from 'mobx'

class ExampleStore {
  @observable foo = 'bar'
}

const exampleStore = new ExampleStore()
export default exampleStore
```
component.js:
```
import React from 'react'
import { observer } from 'mobx-react'
import exampleStore from './exampleStore'

export default observer(() => <div>{exampleStore.foo}</div>)
```
exampleStore.js: Missing class properties transform.
