### ISSUE TITLE
Error with Meteor.loginWith< ExternalService > on Cordova: "Error: No hash fragment in OAuth popup?"

### ISSUE THREAD

**Issue by VioletaCalvo** [meteor/meteor#6097]
Hi!

I'm triying to login with services (Google, Twitter & Facebook) on Cordova clients but getting errors. No problems on web browsers.

According to [meteor wiki](https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients) I'm ussing `Meteor.loginWith<ExternalService>({ loginStyle: "redirect" })` in Cordova.

This is my code to login with Google (_I think it is supposed to work_):
``` coffeescript
  'click #loginGoogle': (e,tlp) ->
    options = {}
    if Meteor.isCordova
      options.loginStyle = "redirect"
      # I also tried with the line below
      options.redirectUrl = Meteor.absoluteUrl('_oauth/google?close')
    Meteor.loginWithGoogle options, (error, res)->
      if error
        console.error "loginWithGoogle Error"
        if error.errorType is 'Meteor.Error'
          Notifications.error error.reason
        else
          console.error error
      else
        FlowRouter.go 'home'
```
With iOS simulator, after touching the "login with google" button a blank window is displayed and these are console logs:
```
Error in Success callbackId: InAppBrowser1420976554 : Error: No hash fragment in OAuth popup?
Uncaught Error: Error: No hash fragment in OAuth popup?:314:http://meteor.local/cordova.js
Error: No hash fragment in OAuth popup?
```

The code is supposed to work? I'm doing something wrong or is there a bug?
Thank you!

**Comment by VioletaCalvo** [comment]
Any suggestion to solve this? Thank you in advance!

**Comment by VioletaCalvo** [comment]
Hi !

I found the reason. It's a problem with `MOBILE_ROOT_URL` and `MOBILE_DDP_URL`.
Code works fine if 'ROOT_URL` and `--mobile-server` are the same.
Same issue as #4581

**Comment by ikostic** [comment]
Hi,

I am in the same situation now.

Facebook Login on Web is working nice.

On Android i get same error as you are. 

On Server i set ROOT_URL with my domain, but i can't understand or find some resource about MOBILE_ROOT_URL, MOBILE_DDP_URL and --mobile-server configuration.

Can you help me on this?

Regards,

Igor

**Comment by VioletaCalvo** [comment]
Of course!

When you run in mobile you have to set `--mobile-server`. With that you are setting `MOBILE_ROOT_URL` and `MOBILE_DDP_URL`
https://www.meteor.com/tutorials/blaze/running-on-mobile
https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration

To run on android:
```
meteor run android-device --mobile-server https://myapp.com
```
Local build for all your platforms:
```
meteor build your-build-output-directory --server https://myapp.com --mobile-settings your-mobile-settings.json
```

This works for me. Let me know if this have helped or you have more questions.

**Comment by ikostic** [comment]
Hi,

this is how i have done this.

Login with facebook part:

    options = {};
    if (Meteor.isCordova) {
        options.loginStyle = "redirect";
        options.redirectUrl = Meteor.absoluteUrl('_oauth/facebook?close');
    }
    Meteor.loginWithFacebook(options,
        function(err){
            if (err){
                throw new Meteor.Error('Facebook login failed: ' + err);
            } else {
                console.log('Facebook login ok');
            }
        }
    );

I am building app with this command:

    meteor build ../builds/build_0.0.x --server https://server.domain.com --mobile-settings production.json

Bundle is deployed on server i run like this:

    export MONGO_URL='mongodb://user:pass@domain.mongolab.com:56688/db'
    export ROOT_URL='https://server.domain.com/'
    export PORT=3000
    export METEOR_SETTINGS=$(cat production.json)

    node main.js

Error i am receiving through chrome inspector while using android debug release:

    cordova.js:310 Error in Success callbackId: InAppBrowser141363425 : SyntaxError: Unexpected token _
    cordova.js:312 Uncaught SyntaxError: Unexpected token _pageLoaded @ oauth.js?1dd3663131860c7d9bafb68435b8a19749aca3ee:251Channel.fire @ cordova.js:820InAppBrowser._eventHandler @ inappbrowser.js:39cb @ inappbrowser.js:96cordova.callbackFromNative @ cordova.js:291processMessage @ cordova.js:1079processMessages @ cordova.js:1102pollOnce @ cordova.js:971pollOnceFromOnlineEvent @ cordova.js:958

Maybe it's good to mention that during the android app loading i am receiving lot of debug info like this:

    METEOR CORDOVA DEBUG (autoupdate_cordova.js) Download error, will retry (#5): https://server.domain.com/__cordova/uploads/snaps/20e204da-bab8-8c65-24c4-8ad8c2edb608.jpg?yYwjt93C5q9v7ZoYp
    autoupdate.js:37 METEOR CORDOVA DEBUG (autoupdate_cordova.js) Download failed: {"code":3,"source":"https://server.domain.com/__cordova/js/ios-websocket-hack.js?xmdHcFhJw9MoX9BRp","target":"file:///data/user/0/com.domain.server/files/meteor/878c3fd700168ed1bb20550198d83de29b5a11d9/js/ios-websocket-hack.js","http_status":null,"body":null,"exception":"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."}, source=https://server.domain.com/__cordova/js/ios-websocket-hack.js?xmdHcFhJw9MoX9BRp, target=file:///data/user/0/com.domain.server/files/meteor/878c3fd700168ed1bb20550198d83de29b5a11d9/js/ios-websocket-hack.js

**Comment by VioletaCalvo** [comment]
Hi!

I think you shouldn't configure `export PORT=3000` otherwise, your app is running in `https://server.domain.com:3000`.

If this doesn't works, did you try to run your app with this?
```
meteor run android-device --mobile-server https://server.domain.com --mobile-settings production.json
```

Note that your error is not the same error I had. You have a `SyntaxError: Unexpected token _` and I had `Error: No hash fragment in OAuth popup?`

Hope this helps...

**Comment by ikostic** [comment]
This thing made me completely crazy whole last week.

I fixed the problem. My server is working on https and i had problem with intermediary SSL certificate. I fixed that problem, now everything is working ok.

Thanks for the help :)

**Comment by KudMath** [comment]
Hello guys,

I have a similar/weird problem my ios app can login with facebook fine but the android one can't (blank redirect screen) any idea what might cause that?

**Comment by justingrayston** [comment]
Thanks @ikostic for posting, I was debugging this issue, and your comment led me to check the Cert details, and sure enough Intermediate was missing.
