### ISSUE TITLE
1.3-modules-beta.5: How to use HTML / CSS assets files from node_modules?

### ISSUE THREAD

**Issue by dotansimha** [meteor/meteor#6098]
**_6 Upvotes**_ Hi,

I am helping in Angular2-Meteor, and I try to figure out how to use templates that comes from node_modules directory. 

This is my app structure:

```
app
      - node_modules
          - my_module 
               - file.js
               - file.html
```

`file.js` loaded using `import ...`, but the `file.html` which is a template that required by `file.js` not loaded. 

I saw that the new version (beta5) now provides the ability to add CSS styles files, but I think that its not enough, because I was to specify a file from the node_modules instead of providing the actual style.

I think a good option to provide the same logic as `addAssets` is to provide the ability to `import` CSS and HTML inside the modules:

```
import './a.css';
import './a.html';
```

And then add these files to the compilers to handle, just like `addFiles / addAssets` done.

Another option is to add a custom property to the `package.json`, like `assets: [ ... ]`...

Thanks!

**Comment by dotansimha** [comment]
For the moment, I used webpack to bundle my component. 
Meteor 1.3 automatically imports the JS files you `import ...`, but it does not handle `.css` or `.html` files (or any other assets, like images or fonts) that the packages provide. 

In order to provide a workaround for the moment, I used Webpack to bundle all my source code into single `.js` file. 

So I used some webpack loaders:
- html-loader (to load HTML template files into the js file)
- less-loader (which provides the ability to compile LESS files into CSS files)
- css-loader (loads CSS into the bundle)
- style-loader (which loads the `.css` file I create into the `<head>` tag when the JS file is loaded).
- ts-loader (which compiles TypeScript into ES5 file)

Because Meteor 1.3 works with CommonJS, we need to declare that the output module of Webpack is `commonjs`, like in here:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/webpack.config.js#L4

The next step is to declare all of our external or meteor `import`s, we declare it with it's name, without change, in order to tell Webpack just to leave the `import` and not try to load the actual `.js` file and bundle it:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/webpack.config.js#L11-L17

We also need to specify the extensions which is relevant to the bundle:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/webpack.config.js#L9

And specify the main (entry point) of the module:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/webpack.config.js#L2

And now you can implement you module as you with, and do not forget to `require(...)` the files you need, where you need.

So in order to bundle HTML file, just do as follow:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/modules/login-buttons.ts#L18

And to load `.less` file, do the same anywhere in your source file:
https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/modules/login-buttons.ts#L6

So now when you bundle your module - you will provide a single `.js` file that meteor can handle ! 

I still think that Meteor should think about a way to provide an alternative to `api.addAssets`, because some packages does not bundle `.css` file and provides the ability to decide wether to load it or not.

**Comment by dagatsoin** [comment]
This will be usefull for React when using Modular CSS/SCSS.
For example today, the great and easy-to-use React Toolbox UI is unusable because this issue (same here: https://github.com/nathantreid/meteor-css-modules/issues/1#issuecomment-180076417)
I really hope for a new way of building in Meteor 1.3

**Comment by adrianmc** [comment]
Is there currently no way of requiring static assets from node modules? What if an NPM package I am using requires an image file or a vendor JS file with no exports? I'd have to install Webpack? That completely makes a lot of NPM packages useless.

I'm currently trying to use this NPM package: https://www.npmjs.com/package/react-medium-editor

Unfortunately, it requires me to use the CSS files inside a node module. How do I do this?

**Comment by enaros** [comment]
same question here as @adrianmc , any plans to implement such a feature?

**Comment by Secretmapper** [comment]
+1

**Comment by enricofoschi** [comment]
+1

**Comment by lukasvan3l** [comment]
+1 for https://www.npmjs.com/package/toastr

**Comment by omeid** [comment]
+1

And as mentioned, it is not Angular specific.

**Comment by Hongbo-Miao** [comment]
+1

**Comment by omeid** [comment]
Related #6037.

**Comment by serkandurusoy** [comment]
+1

**Comment by leoetlino** [comment]
To the +1 commenters: use the new vote feature instead of commenting with useless +1 comments. That feature wasn't added for no reason… :-1:

---

Also, yes, while 1.3 allows importing JS from npm dependencies, CSS is not possible at all… Webpack is an alternative but meteor-webpack does not work with everything, not with native modules that are supported on the server for [example](https://github.com/thereactivestack/meteor-webpack/issues/143).

**Comment by AndreasGalster** [comment]
@benjamn I believe you worked on the previous .css/.scss support. Are there any news regarding supporting importing html? This is a show stopper for Polymer integration as well.

**Comment by Urigo** [comment]
we needed something like that for `angular-meteor` so we've create something for static HTML (not related directly to Angular).
@AndreasGalster try it out and let me know if it solves your problem: https://github.com/Urigo/meteor-static-templates

@benjamn would love to hear your thoughts about the package and the implementation, I haven't checked how it affects build times yet....  https://github.com/Urigo/meteor-static-html-compiler

**Comment by hwillson** [comment]
Styles can be imported from npm packages using newer versions of Meteor (see the [Importing styles from npm](https://guide.meteor.com/using-npm-packages.html#npm-styles) section of the Guide for more info). Importing other static files like `.html` is not directly supported, but  using a 3rd party package like [urigo:static-html-compiler](https://atmospherejs.com/urigo/static-html-compiler) can help.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=1.3-modules-beta.5%3A%20How%20to%20use%20HTML%20%2F%20CSS%20assets%20files%20from%20node_modules%3F&body=Migrated%20from:%20meteor/meteor%236098) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
