### ISSUE TITLE
Cross target package dependencies

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6099]
I stumbled across what I think is currently a limitation of the package system (1.2). The issue is that I would like to create a package, which when you add it on `web.browser` target would add files both to `web.browser` and `web.cordova` targets, if the latter is enabled for the whole app. It seems this is not possible. Currently, I have to list both `web.browser` and `web.cordova` when doing `api.use`. This is problematic because the fact about `web.cordova` file is something which is internal to the package implementation. The exposed API and symbols are reasonable only for the `web.browser`. (`web.cordova` only gets some assets and some other tweaks which then make it work with the `web.browser`.)

(The target names here are just example, I in practice have some custom targets.)

**Comment by avital** [comment]
It the example above with `client` and `web.cordova` actually true? I am pretty sure passing in `"client"` into `api.use` makes that package available on both browser and Cordova apps.

**Comment by mitar** [comment]
I will update the description to make it clearer how I would like this to behave.

**Comment by mitar** [comment]
So, to be more concrete, I have a package, which does:

```
api.addFiles('browser.js', 'web.browser');
api.addFiles('cordova.js', 'web.cordova');
```

And I would like to do in another package:

```
api.use('my-package', 'web.browser');
```

But that should add also `cordova.js` to `web.cordova` if it is enabled, but not that user has to list it when doing `api.use`, because it should be internal to the implementation of my package.

One example for this is code for web workers. Imagine that we have `web.worker` target. I would like to create a package `my-super-rendered-in-web-worker` which has `api.js` for `web.browser` and `worker.js` for `web.worker` targets. Users should not know that the package is using web workers internally. You would want only to load the package on the `web.browser` because this is where the public API for the package is. And then my package could check and load `worker.js` from `web.worker` target internally.

**Comment by mitar** [comment]
Hm, I am looking into this and I have issues implementing it. So it is not easy to get metadata in, but the issue is that each target is build separately, it seems. So when a target `web.browser` is being build, there is no way to tell the target `web.worker` that when it will be build, it should include the X extra package (because a package from `web.browser` depends on it).

**Comment by mitar** [comment]
I made #6238 pull request.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Cross%20target%20package%20dependencies&body=Migrated%20from:%20meteor/meteor%236099) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
