### ISSUE TITLE
Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by nitinkumarmedia** [meteor/meteor#6100]
Hi,

During deployment of meteor application to remote server in Meteor-MySQL stack, I was using command "mup deploy" which failed due to some unknown reasons.

> Failed to connect to localhost port 80: Connection refused
> Latest deployment failed! Reverted back to the previous version.
> 

When I check the mup logs with command "mup logs -f", I am getting continuous error:

> TypeError: Cannot read property 'host' of undefined
>     at new ConnectionConfig (/opt/meteor/app/programs/server/npm/numtel_mysql/node_modules/mysql/lib/ConnectionConfig.js:12:36)
>     at Object.createConnection (/opt/meteor/app/programs/server/npm/numtel_mysql/node_modules/mysql/index.js:12:34)
>     at new LiveMysql (/opt/meteor/app/programs/server/npm/numtel_mysql/node_modules/mysql-live-select/lib/LiveMysql.js:14:18)
>     at server/lib/main.server.app.js:2:17
>     at /opt/meteor/app/programs/server/app/server/lib/main.server.app.js:13:4
>     at /opt/meteor/app/programs/server/boot.js:242:10
>     at Array.forEach (native)
>     at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
>     at /opt/meteor/app/programs/server/boot.js:137:5
> [IP_ADDRESS] error: Forever detected script exited with code: 1
> [IP_ADDRESS] error: Script restart attempt #907
> [IP_ADDRESS] /opt/meteor/app/programs/server/node_modules/fibers/future.js:245
> 						throw(ex);

What could be the reason for this? I have restarted the node server as well as ec2 instance to see if that was causing the problem. But no luck. Please suggest.

**Comment by zol** [comment]
This looks like an issue with mup, please open an issue within their issue tracker.
