### ISSUE TITLE
Windows meteor.bat script does not extract automatically the bundle

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6102]
In this way it is not the same as Linux script, which automatically extracts the dev bundle tgz file if it finds it locally (instead of downloading it from the server). This makes it complicated to script/write documentation for. It would be great if behavior of both Meteor run scripts would be the same.

**Comment by stubailo** [comment]
It works for me when developing locally. Do you have 7zip on your machine? Perhaps the script can't find it?

Here's the line in the download script which is supposed to unpack it: https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/scripts/windows/download-dev-bundle.ps1#L37

**Comment by mitar** [comment]
I think [this is missing](https://github.com/meteor/meteor/blob/devel/meteor#L77) for Windows.

**Comment by stubailo** [comment]
Oh, I misread your issue! Yes, you're right, there isn't logic to extract an existing tarball if one exists. I can't fix this right now, but this seems like a great candidate for a PR (going to go look at your other one now)

**Comment by abernix** [comment]
This should work the same as the non-Windows version now thanks to #8010.  Make sure you set `SAVE_DEV_BUNDLE_TARBALL` in your environment to save downloads, otherwise the bundle will still get removed after being extracted.   Let me know if you have problems with it.
