### ISSUE TITLE
Custom EJSON types and Promise-based values

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6103]
While trying to add web crypto `CryptoKey` to EJSON I realized that this is not possible. Despite web crypto having a nice JSON export format (JWK) which could be easily embedded into EJSON, it is not possible to use it inside EJSON because the web crypto API uses promises. And EJSON supports only synchronous transformation.

It would be great to extend EJSON in a way to support Promises when generating the serialized or deserialized content.

**Comment by tmeasday** [comment]
Hey @mitar, can you not simply wait for the promise to finish executing synchronously? I think the `promise`'s package `.await()` function will do this for you. Something like

```js
new Promise(fnThatReturnsAPromise).await();
```

**Comment by mitar** [comment]
And how would this work on the client side? So I call a method on the client side, it tries to use EJSON, it cannot?

BTW, there is no reason why it could not be async. Maybe we should just extend EJSON to allow it to return promises, and if it is a promise, then consumer of EJSON should try handle that. So maybe the solution is that we augment core calls to EJSON functions with checking for promise.

**Comment by tmeasday** [comment]
Why does it need to be async though? I don't really get it. How can doing crypto processing be async?

**Comment by mitar** [comment]
Because it is [the standard](http://www.w3.org/TR/WebCryptoAPI/).

**Comment by tmeasday** [comment]
Ok, fair enough, although I don't really understand it still. Is it a webworkers thing?

I think it's probably not something that we want to add to EJSON right now, I'd say however.

Can you tell me a little more about the use-case?

**Comment by mitar** [comment]
> Ok, fair enough, although I don't really understand it still. Is it a webworkers thing?

No, it is a normal web crypto, not linked to web workers (you can use it in web workers, but you do not have to). I heard the reason why it is with promises is that it can work on hardware which allows only one crypto operation at a time. So that you can queue others.

> Can you tell me a little more about the use-case?

Yes, my use case is that I want to send generated keys over the Meteod methods. So only EJSON-able values can be send. So I tried to implement this but it is not possible. I have to manually do it before and convert it to UInt8Array. So it is just ugly.

Another use case is if you wan to encrypt fields before storing them into the database. I could create `EncryptedString` and use that on documents and it would be automatically encrypted every time it is serialized, but it is also not possible.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Custom%20EJSON%20types%20and%20Promise-based%20values&body=Migrated%20from:%20meteor/meteor%236103) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
