### ISSUE TITLE
Replace EJSON with JSON-LD and/or JSON Schema

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6104]
Instead of using custom format like EJSON, Meteor could use standard JSON-LD and/or JSON Schema to link JSON to a schema. In this way it would still be possible to serialize and deserialize data, but instead of adding type information about serialized data directly next to the value, that type information would be stored in the schema for the whole document.

**Comment by tmeasday** [comment]
This seems like a interesting idea but not the sort of change that we are going to make to the 1.0 data system. I guess a [GraphQL based system](http://info.meteor.com/blog/reactive-graphql) probably includes this idea of separating the schema from the data types? I'm not really sure.
