### ISSUE TITLE
meteor unknown-command execution time about 2 seconds?

### ISSUE THREAD

**Issue by ljack** [meteor/meteor#6106]
Just wondering, what's really going on why it takes so long for Meteor to determine what commands are available?

Maybe add yours on comments to see if there's something at all going on? ;)

Maybe create a shell script to run some of the meteor's (supposedly "fast" ) commands automatically and log execution time?

```
ljack1:~/ $ time meteor unknown-command
'unknown-command' is not a Meteor command. See 'meteor --help'.

real    0m2.107s
user    0m1.580s
sys     0m0.460s
```

```
ljack1:~/$ time meteor list
real    0m31.637s
user    0m15.196s
sys     0m2.132s
```

**Comment by zol** [comment]
Closing as this would be a better discussion topic for the [Meteor forums](https://forums.meteor.com/).
