### ISSUE TITLE
Joi (npm) in the browser, using Meteor 1.3 beta 5

### ISSUE THREAD

**Issue by czbaker** [meteor/meteor#6107]
I wasn't entirely sure if this is a problem with Joi or Meteor itself, but I have a current situation when trying to use Joi to handle form verification for Redux-Form.

The project works fine without using Joi, but when I incorporate it into a React component, I get the following error in browser console:

`Uncaught Error: Cannot find module 'crypto'`

Any help would be appreciated.  Again, I'm not sure if this is a problem with Meteor or Joi, or a possibility that I'm just doing something wrong, but this error happens either way, so I thought I'd report it.

**Comment by prashantgaikwad** [comment]
I am having the same issue.

**Comment by benjamn** [comment]
This issue is subsumed by https://github.com/meteor/meteor/issues/6056. In the meantime, can you let us know if running `npm install crypto` in your app solves your problem?

**Comment by prashantgaikwad** [comment]
The 'crypto' package on npm is a different one and not being maintained. The one which 'joi' expecting comes as a core package in node.

**Comment by benjamn** [comment]
This is fixed in beta.16, thanks to #6056.
