### ISSUE TITLE
spacebars documentation for double-braced tags in attribute values

### ISSUE THREAD

**Issue by nicocrm** [meteor/meteor#6109]
The spacebars documentation (packages/spacebars/README.md) has a minor issue with respect to expansion of double-braced tags in attribute values.

Although the documentation states:

```handlebars
<input type="checkbox" class="checky {{moreClasses}}" checked={{isChecked}}>
```

The correct syntax is actually:

```handlebars
<input type="checkbox" class="checky {{moreClasses}}" checked="{{isChecked}}">
```

**Comment by aramix** [comment]
It works both ways though

**Comment by nicocrm** [comment]
It didn't in my experience but I would be happy to be proved wrong... if you look at https://forums.meteor.com/t/my-checkbox-is-always-checked/17191/9 I posted a basic example, the only way I got it to work was using the quotes.

**Comment by stubailo** [comment]
It is supposed to work both ways. If it doesn't please file an issue with a reproduction we can run.
