### ISSUE TITLE
[Blaze 1.2.1 and 1.3 BETA5] Bug when rendering child templates

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [meteor/meteor#6111]
This bug is in both 1.2.1 and 1.3 BETA5.
Please clone my app from here: https://github.com/Laurentiu-Andronache/filterbet.win

Start it and write something in the first textbox.
It will copy what you wrote to the second textbox. Also, the focus will be lost. Both of these are unintended consequences of the bug.

Now refresh the page and write something in the second textbox.
The focus will be lost because of the bug.

The issue disappears if I remove line 17 of app/client/templates/shared/input_odds/input_odds.js:
`ChecksCollection.update({}, {$set: objectForSet});`
Removing it makes it possible to write into the textboxes and for example the helper isValidOddsFormat from the same file works correctly. I need that line though. I can't delete it.

Can this be fixed?

Unrelated: please use the upper menu and change between the two options. Can the slide effect be done only in a horizontal manner? (at the moment the divs also jump from below to the correct position). If not, can you please recommend an animation library that actually works with bootstrap? percolate:momentum and jquery-ui have failed me.

Thank you for reading this!

**Comment by Laurentiu-Andronache** [comment]
Note: I managed to solve the issue for my app by creating an array of objects instead of an array of values. Blaze works well for something like that:
global.emptyOdds = {asString: '', asPercentage: '', asDecimal: '', asFractional: '', asMoneyline: ''};
global.startNewCheck = () => ChecksCollection.insert({
  localInsertDate: new Date(),
  oddsChecked: [emptyOdds, emptyOdds],
[...]

The bug in Blaze rendering still remains though. Just clone the app and see for yourself. I won't update it until you see the issue. Hopefully you will be able to solve it because it's quite a big one.

**Comment by avital** [comment]
I'm happy you found a workaround!

The app you linked to is too big for us to look into as part of how we investigate bugs. If you can supply a minimal reproduction then we can take a look.

Though, from what you're describing this sounds a lot like this: https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#reactivity-model-for-each

**Comment by avital** [comment]
No repro for 22 days; closing
