### ISSUE TITLE
reactive:false not working here

### ISSUE THREAD

**Issue by ChenLi0830** [meteor/meteor#6112]
Hi there, I am new to Meteor and currently I am trying to use it with react. 

Here is what I am trying to do: The server has a collection 'Apps', and the client needs to get the 'Apps' based on what app-category the user chose. The first time the Apps are fetched, they should be sorted based on 'subscribeCount'. After that, the page should only re-render itself if the user choose another category and it should not re-render for 'subscribeCount' changes.

I tried to use reactive: false. However, I can't seem to stop the change of 'subscribeCount' from re-rendering the page.
Here is my code: 
```
        const chosenApps = Apps.find({
                categoryNames: {
                    $in: [this.state.chosenCategory]
                }
            },
            {sort: {subscribeCount: -1}, reactive: false}
        ).fetch();
```

**Comment by nathan-muir** [comment]
Hey @ChenLi0830, it's worth reading ["Reporting a bug in Meteor"](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor) before opening an issue; As we probably can't figure out exactly what's happening in your app from the snippet you've posted.

Either way, this might work better as a question on the [meteor forums](https://forums.meteor.com), or [stackoverflow](http://stackoverflow.com/questions/tagged/meteor).

**Comment by ChenLi0830** [comment]
Hi @nathan-muir, thanks for your reply. You can close this issue I will ask it somewhere else. If I still couldn't figure it out, I'll probably come back and ask again and I will follow the "Reporting a bug in Meteor" :)
