### ISSUE TITLE
WebSocket 503 with release-1.3

### ISSUE THREAD

**Issue by kalebheitzman** [meteor/meteor#6116]
Mac OS X 10.11.2
Node 0.12.9
Homebrew 0.9.5

Git Version of meteor and branch release-1.3

I cd'd into the docs and ran ../meteor and this is the result in the console. Documentation will not load. I've tried creating a fresh app and I get the same results. I'm assuming it's my mac environment but I don't know where to even begin looking. I downgraded to Node 0.10.xx and tried as well with no luck.

```
WebSocket connection to 'ws://localhost:3000/sockjs/103/z5lj1xqg/websocket' failed: WebSocket is closed before the connection is established.
sockjs-0.3.4.js:854 POST http://localhost:3000/sockjs/103/f1_zl52o/xhr_send 503 (Service Unavailable)
```

**Comment by avital** [comment]
Does this also happen on the `master` branch of Meteor? Or with an installed (not via Git) version of Meteor?

(BTW, Meteor comes with its own version of Node; changing your globally installed version doesn't have an affect on your Meteor apps)

**Comment by avital** [comment]
That is -- I'd be extremely surprised if this is something about Meteor 1.3.

**Comment by avital** [comment]
Closing due to no comment in 16 days.
