### ISSUE TITLE
meteor build/deploy should fail if node_modules/**/*.node

### ISSUE THREAD

**Issue by pcarrier** [meteor/meteor#6118]
If a `node_modules/**/*.node` file exists, meteor build/deploy should fail with message explaining that binary node packages need to be wrapped with a traditional meteor package.

**Comment by zol** [comment]
Add a warning when we detect this case.

**Comment by benjamn** [comment]
This is *not* fixed with the recent changes related to #6398. The only place we were warning about binary npm dependencies was when publishing packages, but we also need to warn when building or deploying an app.

**Comment by abernix** [comment]
Pretty sure this can be closed with recent versions of Meteor being smart enough to handle this?

**Comment by hwillson** [comment]
Yes, it looks like this has been fixed. The `*.node` check is handled by the [`meteorNpm.dependenciesArePortable`](https://github.com/meteor/meteor/blob/355cde306a57ec30a13dd5ede24c9936f93ae76b/tools/isobuild/meteor-npm.js#L506) function, which is called [in the bundler](https://github.com/meteor/meteor/blob/355cde306a57ec30a13dd5ede24c9936f93ae76b/tools/isobuild/bundler.js#L1996) (through `isPortable`), when writing the image to disk. Found non-portable npm packages are then [rebuilt](https://github.com/meteor/meteor/blob/355cde306a57ec30a13dd5ede24c9936f93ae76b/tools/isobuild/bundler.js#L2040-L2045). Closing this off - thanks!
