### ISSUE TITLE
Implement RFC 7239 for force-ssl

### ISSUE THREAD

**Issue by winniehell** [meteor/meteor#6120]
[RFC 7239](http://tools.ietf.org/html/rfc7239) replaces the `X-Forwarded-Proto` header by `Forwarded`. How about using the `Forwarded` header in the `force-ssl` package with a fallback to `X-Forwarded-Proto`?

**Comment by winniehell** [comment]
See also Wikipedia on [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For).

**Comment by timbotnik** [comment]
Thanks for noting this @winniehell.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Implement%20RFC%207239%20for%20force-ssl&body=Migrated%20from:%20meteor/meteor%236120) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
