### ISSUE TITLE
[meteor1.3-beta5] named export cannot be imported

### ISSUE THREAD

**Issue by sungwoncho** [meteor/meteor#6121]
Named exports, when imported, is `undefined`.

*foo.js*

```
export default {
  hello: 'world'
};
```

*bar.js*
```
import {hello} from './foo'
// => hello is undefined
```

Here is the repo for reproduction: https://github.com/sungwoncho/meteor-1.3-import-bug

Using
* meteor1.3-beta5
* OSX El Capitan 10.11.2

**Comment by nchenbang** [comment]
The export defined in your _foo.js_ is actually a default export and the correct way of importing it should be 
```

**Comment by sungwoncho** [comment]
Maybe the term 'named exports' is not what I am looking for.

I can confirm what I have here works in beta.4, but not in beta.5. Just pushed a new branch [1.3-beta.4](https://github.com/sungwoncho/meteor-1.3-import-bug/tree/1.3-beta.4) to the reproduction repo.

**Comment by nchenbang** [comment]
I've already look through the new branch you mentioned. It seems like there's a bug in beta.4. The import/export syntax is totally wrong and it shouldn't have worked. I'm really glad that this bug has been solved in beta.5.

**Comment by sungwoncho** [comment]
@nchenbang I have used the correct syntax for named exports by following your suggestion, but it did not work in either beta4 or beta5.

I have pushed another branch [1.3-beta.4-2](https://github.com/sungwoncho/meteor-1.3-import-bug/tree/1.3-beta.4-2). Can you have a look?

**Comment by nchenbang** [comment]
That's no how you import a named export. It should be like this
```javascript
import { Post } from './collections';
```

**Comment by benjamn** [comment]
Here's the Babel issue where they debated removing support for this export pattern: https://phabricator.babeljs.io/T2212
