### ISSUE TITLE
Uglify: Eliminate code based on `Meteor.isServer`, etc.

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#6123]
It looks like Meteor is already using Uglify, so why aren't we using it's features to remove dead code? Wouldn't it be possible to make using `Meteor.isServer` etc. safe this way? Maybe this could be added to `1.3`.

**Comment by stubailo** [comment]
This would be a great feature to have in the future, alongside elimination for production/development/test code. It's definitely not going to be in the 1.3 release.

**Comment by laosb** [comment]
That's a good feature. Many beginners think that the code in `Meteor.isServer` block was not sent to the client, which is totally not true.

**Comment by raix** [comment]
https://github.com/meteor/meteor/issues/802
https://github.com/mishoo/UglifyJS2/issues/132

**Comment by stubailo** [comment]
> Many beginners think that the code in Meteor.isServer block was not sent to the client, which is totally not true.

We can also solve this with documentation and tutorial updates, by making the new tutorial simply not use `Meteor.isServer`. Probably a good idea anyway.

**Comment by laosb** [comment]
Good idea. Also make a note when we talk about `Meteor.isServer`.

> On Feb 12 2016, at 1:50 am, Sashko Stubailo &lt;notifications@github.com&gt;
wrote:  

>

>> Many beginners think that the code in Meteor.isServer block was not sent to
the client, which is totally not true.

>

> We can also solve this with documentation and tutorial updates, by making
the new tutorial simply not use Meteor.isServer. Probably a good idea anyway.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/meteor/
meteor/issues/6123#issuecomment-182977114).![](https://github.com/notification
s/beacon/ACbWbdFD7RVlrce47OUeHlE9xQD3J5qAks5pjMFDgaJpZM4HQAn3.gif)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Uglify%3A%20Eliminate%20code%20based%20on%20%60Meteor.isServer%60%2C%20etc.&body=Migrated%20from:%20meteor/meteor%236123) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
