### ISSUE TITLE
press or type?!

### ISSUE THREAD

**Issue by dotku** [meteor/meteor#6126]
` Type Control-C twice to stop.`

I'm not sure if someone will misunderstand this...
I just not really conformatable to use "type" over here...

**Comment by Slava** [comment]
What would be a better wording? Is there anything consistent with other software on Windows?

**Comment by stubailo** [comment]
> I'm not sure if someone will misunderstand this...

I think changing this speculatively would be a mistake - maybe we should wait for a bug report from someone that actually couldn't stop the server?

**Comment by dotku** [comment]
@Slava I mean, using 'press' would be beter
@stubailo no problem, just report something overe here; it is just little thing, not concidered as 'bug' however.

**Comment by stubailo** [comment]
Yeah, I'll reopen this later if we get a report from a confused user. Thanks for the heads up!
