### ISSUE TITLE
Triple-braced-tags deprecated?

### ISSUE THREAD

**Issue by simsketch** [meteor/meteor#6128]
https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#triple-braced-tags

I remember reading that the triple-braced tag has been deprecated?

**Comment by jhuenges** [comment]
Where and why?

**Comment by stubailo** [comment]
They are not deprecated. We do warn against using them if you don't know what you're doing, because it can open you to security issues with raw HTML.
