### ISSUE TITLE
[wiki] Link in Meteor Style Guide (console.js)

### ISSUE THREAD

**Issue by mitjajez** [meteor/meteor#6129]
Where should point **Console** link in [Meteor Style Guide #line-length](https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#line-length)?

404 [console.js](https://github.com/meteor/meteor/blob/devel/tools/console.js

**Comment by tmeasday** [comment]
Good question! I think it's this: https://github.com/meteor/meteor/blob/devel/tools/console/console.js

Send a PR?

**Comment by mitjajez** [comment]
Ok, find how to do it http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github#11481887

**Comment by tmeasday** [comment]
Oh, sorry I didn't realise this was a request against the wiki. I'll update it.
