### ISSUE TITLE
Cordova: Building with meteor build --server <server> ignoring <server> and using default localhost:3000

### ISSUE THREAD

**Issue by khronedev** [meteor/meteor#6130]
Hi,

I propably found a bug where building with
````
meteor build <dir> --server test.com:5000
````
get's ignored and my mobile app is trying to connect to default ``localhost:3000``. I'm using both iOS and Andorid platforms. Why am I thinking that?

1) When i run my app on localhost by ``meteor run ios`` and so on - everything seems to work fine.
2) When i build my app using ``meteor build <dir> --server <server>`` and DO run local server on port 3000 I get's connected to my localhost database instead of remote ``<server>`` DB.
3) When i build my app using ``meteor build <dir> --server <server>`` and DO NOT run local server on port 3000 i got an errors in my iOS simulator:
````
ERROR whitelist rejection:
````
with url pointing to default localhost:3000 AND no subscriptions are left "ready" - they seems to be loaded (i found it by ``Template.subscriptionReady`` in my handlebars).
4) When i try to run app from my phone the app get's freezed by the first time i load data from server (and i cannot debug on my device).

Maybe I am doing something wrong? Please, help.

**Comment by khronedev** [comment]
I just want to notice, that after updateing project to ``1.3-cordova-beta.3`` the problems get's resolved.

**Comment by martijnwalraven** [comment]
This is likely to be related to not setting `ROOT_URL` on the server, see https://github.com/meteor/meteor/issues/5973. `1.3-cordova-beta.3` protects against this, but that means it won't accept any hot code pushes until the server has been configured correctly.
