### ISSUE TITLE
1.3: ecmascript package required for coffeescript?

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#6131]
I'm using CoffeeScript. With 1.3 I must also install the `ecmascript` package, or it won't work. Why is required, when I just want to use CoffeeScript? It would be nice if we could drop the `ecmascript` package and just use `coffeescript` instead.

**Comment by benjamn** [comment]
This behavior is not intended. What is the error that you see that makes it seem like `ecmascript` is required?
