### ISSUE TITLE
Make api.mainModule support options.lazy

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6132]
[Motivation](https://forums.meteor.com/t/will-meteor-1-3-output-commonjs-modules/17328/7?u=benjamn).

**Comment by benjamn** [comment]
Note to future self: you probably won't be able to use `api.export` if your `api.mainModule` is lazy.

**Comment by mitar** [comment]
Is it also possible to import only a subset of files from a package lazily? So that you have a strict base file (main module) but then some extra files are available to other packages so that the can include them as necessary?

**Comment by benjamn** [comment]
@mitar That's exactly how it works now! In fact, I've been meaning to draw your attention to this, since you objected to compiling implicit package files in the past: the reason implicit package files have to be compiled is precisely so that other packages and application code can import them at application build time, e.g. `import ... from "meteor/some:package/implicit.js"`. If the package doesn't compile `implicit.js` before publishing, then every user of the package will have to compile that file if they want to import it.

**Comment by mitar** [comment]
Yes, but I would prefer that a package could say that no files should be automatically compiled, and then do `api.addFiles([...], {lazy: true})` and those files would then be available for lazy importing elsewhere. To me this is a clean design: only allowed files can be imported outside, it makes a clean API, and it has much better performance.

I agree that current thing is probably a good default, but maybe something like that if `api.addFiles([...], {lazy: true})` is called (even with empty `[]`), then automatic compilation is disabled and only explicitly added lazy files are available, or none.

So this is really for power users who want to create a clean local packages structure and precisely control what is compiled and what is not (#7598), what is added to targets and what is not (#7573), and what is available as lazy and what is not (#7867).

What do you think?

**Comment by benjamn** [comment]
I see where you're coming from, but just in case you're tempted to submit a pull request, you should know that this will involve a significant change to the compiler plugin API. Specifically, we would need to compile files lazily, during [`ImportScanner#scanImports`](https://github.com/meteor/meteor/blob/f4abbccf4570179f14d37a8747ceb391e25f1cb5/tools/isobuild/import-scanner.js#L341), rather than compiling all matching files before scanning imports. Right now the `processFilesForTarget` method of a compiler plugin can expect to receive a list of all the files that need to be compiled, but we'd have to relax that contract if we compiled files lazily. In other words, `processFilesForTarget` would probably get called multiple times with different subsets of package files.

This is not to discourage you from exploring this functionality; I just want you to be aware what's involved. I have to admit I probably won't have much time to work on it myself, at least for the time being, though I would be happy to review a pull request.

**Comment by mitar** [comment]
> Specifically, we would need to compile files lazily

No, you compile only files which were `api.addFiles`-ed. So if there is `api.addFiles([...], {lazy: true})` then only files added are compiled, and only those files can be imported from other files.

**Comment by benjamn** [comment]
Well, files that are imported by files that are explicitly added are also considered lazy. And you definitely don't want to have to call `api.addFiles(path, arch, {lazy:true})` for every file that might be imported by your package. But you don't know which files are imported until you scan imports.

We can talk about how things should work, but please don't argue with me about how they currently work, since that's an area where my opinion happens to be fairly authoritative.

**Comment by mitar** [comment]
> And you definitely don't want to have to call api.addFiles(path, arch, {lazy:true}) for every file that might be imported by your package.

Why not? This is exactly what I am arguing. This has been until now for packages before imports. You had to add all files to be available in the package. So I like that level of control.

> We can talk about how things should work, but please don't argue with me about how they currently work, since that's an area where my opinion happens to be fairly authoritative.

I am only arguing how `api.addFiles(path, arch, {lazy:true})` should work, which we do not yet have.

**Comment by mitar** [comment]
Or maybe it could be `api.addFiles(path, arch, {importable:true})`?

**Comment by benjamn** [comment]
I'm not willing to turn `package.js` into a laundry list of every module in your package, sorry. I thought you were talking about an explicit way to allow other packages to import specific (lazy) files from your package.

**Comment by mitar** [comment]
> I'm not willing to turn package.js into a laundry list of every module in your package, sorry. 

Hm, but that was how it was before imports? And this can be fixed by allowing wildcards and directories inside `addFiles`, as described here: #4088

> I thought you were talking about an explicit way to allow other packages to import specific (lazy) files from your package.

I would like both. :-) I would like control.

**Comment by theosp** [comment]
Hi,

[Not only that is how it was pre v1.2](https://github.com/meteor/meteor/issues/7842) (see screenshots there), it was (and is) a breaking change that caused community packages that relied on it to break as a result.

That **"laundary list"** is the whole point of package.js.

A serious body of code and practices were developed prior es6 based on the prior addFiles concept. I don't think that it is fair to expect the entire body of code that relied on a specific, and very logical, way in which Meteor had been working to be rewritten.

@mitar 's, argument: "the reason implicit package files have to be compiled is precisely so that other packages and application code can import them at application build time"

Is simply unfair to the hard work and investment that me and many other put on Meteor pre-es6. Yeah, I understand many believe es6 is the future, but as long as you don't advance the major (Meteor 2.0) you shouldn't impose breaking changes (without even documenting them) - and this is a breaking change.

I really think this should be fixed - it isn't a feature it is a bug.

-Daniel

**Comment by mitar** [comment]
I could not agree more with @theosp. Meteor was an opinionated framework. Now all core developers changed to another set of core developers, and those opinions changed a lot. I can understand that. But I do not see why we could not have it both ways. Why those who came to Meteor before modules cannot keep it the way they liked it, because this is why they came to Meteor in the first place.

**Comment by mitar** [comment]
And that change about traversal of files happened even for packages which do not depend on `modules` package at all (#6823).

**Comment by shaiamir** [comment]
I agree with both @mitar and @theosp. This new behavior breaks old code and should be optional.

**Comment by zimme** [comment]
So I'm working on a re-write of my active-route package and was trying out the `lazy` option on `mainModule` and it seems to be working, but when it's turned on it's kinda hard debugging a package.
