### ISSUE TITLE
How to use nonlogical operator in a #if

### ISSUE THREAD

**Issue by TyrionGraphiste** [meteor/meteor#6133]
Hi everyone,

I'm starting Meteor since today and encounter an easy error. I would like reverse the equality of the condition by placing a nonlogical operator just like this :

``
{{#if !hide}}
    {{title}}
{{/if}}
``

But I'm getting **Your application has errors. Waiting for file change.**
I know I could easily reverse the assignation of the **hide** variable because it's a boolean, but I would like to know how to do in this particular case. So how could I manage to make it work ?

Thanks :)

**Comment by jameswang14** [comment]
Use {{#unless}} instead of {{#if}} to invert the condition. 

See [spacebars doc](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#ifunless)

**Comment by TyrionGraphiste** [comment]
Thanks !
I didn't thought that it could be in the doc for a smallest issue.

Good evening :)
