### ISSUE TITLE
MinGW can't regonize meteor?!

### ISSUE THREAD

**Issue by dotku** [meteor/meteor#6134]
I report the issue over there [https://github.com/shoebappa/vagrant-meteor-windows/issues/34], but it seems nobody respond, so I report here as well.

The issue is, after I fresh installed meteor on my windows machine with version 1.2.1.
It works well on CMD, but MinGW32 can't regonize meteor. I have already check the path setting for MinGW, and it has meteor path setting:

> /c/Users/lwj/AppData/Local/.meteor/

I'm just confused :(

**Comment by dotku** [comment]
I found the answer, since it is .bat file, mingw simple can't run it~ 
hopefully, there would be sh version soon~

**Comment by stubailo** [comment]
Duplicate: #4938
