### ISSUE TITLE
Improve error output when using client packages on server

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6135]
When you forget to wrap a `Tracker.autorun` in an `if Meteor.isClient`, it would be nice to get an error saying, "You are using Tracker on the server. Tracker is client-only." 

Current behavior:

```
Tracker.autorun ->
  Meteor.users.findOne()
```

results in `Error: Can't call yield in a noYieldsAllowed block!`

![image](https://cloud.githubusercontent.com/assets/251288/12730922/2fc6e946-c8fc-11e5-9643-d6545ddbd7fe.png)

related: #1868

**Comment by tmeasday** [comment]
Hey @lorensr, this is kind of an unfortunate one. Tracker is only documented to be defined on the client, but it does sort-of-work on the server (in a limited way) -- so I imagine people do rely on the current behavior. I can't really see a way to improve this error without breaking things for those people.

If you can see a better way, I think a PR would be a good idea but for now it is what it is I guess.
