### ISSUE TITLE
Error: loadLocalPlugins called twice with different search paths.Support for     this is not implemented.

### ISSUE THREAD

**Issue by Doris1994** [meteor/meteor#6136]
While adding local plugin com.raananw.imageResizer,Errors executing Cordova commands:
Error: loadLocalPlugins called twice with different search paths.Support for 
   this is not implemented.
   at loadLocalPlugins
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:199:19)
   at findLocalPlugin
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:227:5)
   at Q.when.then.then.options.plugin_src_dir
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:118:25)
   at _fulfilled
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
   at flush
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.11-cordova.3.11tzofq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.
