### ISSUE TITLE
Why does sqlite spend 10 seconds each build reading from a 176 mb packages.data.db file?

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#6137]
Hi, I've moved my project out of the tutorial/toy phase, and I'm having some pretty long build/refresh times.

About 30-50 seconds.  I'm using a SSD w/ 500mb/s

I noticed this in my .meteor directory:

```
michael@mc-laptop ~/.meteor/package-metadata/v2.0.1.old
☀  ls -la
total 177344
drwxr-xr-x 2 michael michael      4096 Jan 11 14:42 .
drwxr-xr-x 5 michael michael      4096 Feb  1 20:48 ..
-rw-r--r-- 1 michael michael 176649216 Feb  1 09:35 packages.data.db
-rw-r--r-- 1 michael michael     32768 Feb  1 20:36 packages.data.db-shm
-rw-r--r-- 1 michael michael   4902576 Feb  1 19:20 packages.data.db-wal
```

Which seems kind of excessive.  If I rename this directory, meteor rebuilds it very slowly, and not obviously via the network.  It grows again to roughly the same size

```
 michael@mc-laptop ~/.meteor/package-metadata/v2.0.1
☀  ls -la
total 176804
drwxr-xr-x 2 michael michael      4096 Feb  1 20:48 .
drwxr-xr-x 5 michael michael      4096 Feb  1 20:48 ..
-rw-r--r-- 1 michael michael 176746496 Feb  1 20:58 packages.data.db
-rw-r--r-- 1 michael michael     32768 Feb  1 20:57 packages.data.db-shm
-rw-r--r-- 1 michael michael   4248624 Feb  1 20:58 packages.data.db-wal
```

Browsing this database, it has about 120k rows, mostly with json dumped into a "content" field, including a copy of the atmosphere readme for each package and version.

99% of those records and information are completely unnecessary for managing packages in my project.

**Comment by sebakerckhof** [comment]
Meteor caches the metadata of the entire atmosphere package catalog on your computer. That way it can look up new versions, do constraint resolution etc. without having to request info online. 

It actually works pretty well that way, but it's not the most future proof (imagine if Atmosphere had the same amount of packages as NPM...). But I doubt MDG will change this now the focus has shifted towards NPM anyway.

**Comment by MichaelJCole** [comment]
Hey, thanks for the comment.  

I'm used to 1-3 second builds with gulp.js.  So when Meteor takes 10 seconds crawling through a 176mb db, filled with junk data (old README's that will never be used on my computer), I'd say it "barely works in spite of it's design and implementation".

Package management (dependencies) and build management, are two very different tasks.  Gulp and npm split the work really well.

Things change, and I'm excited to see 1.3.

**Comment by zol** [comment]
Thanks for taking the time to report this @MichaelJCole . We're currently working on build tool performance and I've labelled this issue accordingly.

**Comment by MichaelJCole** [comment]
Thanks for the update.  

If you keep the client-side db, please consider trimming unnecessary fields in the "content" field of the versions table.  Or at least investigate it.  I didn't look into the usage pattern.

**Comment by dgreensp** [comment]
@MichaelJCole, 30-50 seconds is way too long!  I'm currently working on improving tool build times.

`packages.data.db` is a SQLite database of the package catalog, and that file size is normal.  There's nothing inherently slow about accessing a large SQLite database; SQLite is smart about its reads and the queries we are doing should be hitting indexes.  I've never seen the tool spend more than a few seconds reading the data it needs from SQLite (which is already a suspiciously high amount of time; I think some of that time, as it shows up in the profiler, is actually going to processing we do in JavaScript).

You can run Meteor's performance profiler by prepending `METEOR_PROFILE=1` to your `meteor` command.

What data is showing you that the time is going to reading SQLite?

Also, I would love a repro if there's a small app without any sensitive code you could point me to that takes ~30 seconds to rebuild.  I'm looking for more examples of that.

Thanks.

**Comment by sebakerckhof** [comment]
@dgreensp You mean 30-50 seconds is way too long for the time spend interacting with the database or in total? Because we're also seeing similar times (total rebuild time) on high-end machines, in which case I'll look into the profiler. It's a pretty big app, so a small repro isn't easy.

Also @MichaelJCole note that the package synchronisation protocol does not allow to remove packages. In the (unlikely) event a package or package version gets removed, the entire database gets trashed and re-synchronized. So from time to time the database stuff might take a long time.

**Comment by MichaelJCole** [comment]
Hi @dgreensp, thanks for looking into it.  Here's what I'm doing:

```
METEOR_PROFILE=1 meteor run --port 3010 --settings settings.json
```

Which [shows this](http://pastebin.com/qBHcy8Pc): 
```
|  Selecting package versions                -
| Select Package Versions: 16538.7
|     new CS.Input: 31.7
|     Input#loadFromCatalog (sqlite): 11007.6
|     check for previous versions in catalog: 1.4
|     new CS.Solver: 173.0
|         Solver#analyze: 172.5
|             analyze allowed versions: 21.4
|             analyze root dependencies: 1.1
|             analyze reachability: 24.6
|             analyze constraints: 120.5
|             analyze pre-releases: 3.5
|             other Solver#analyze: 1.4
|     Solver#getAnswer: 5323.3
|         new Logic.Solver (MiniSat start-up): 242.3
|         require root dependencies: 4.7
|         generate package variables: 352.2
```
Which I'm assuming means 11s in sqlite queries and 5s in thinking about it.

I moved my SSD's trim from weekly to hourly, and that's sped up the build to 25s.

I'm sorry, I don't have a small repo, because I'm a ways into development.  I built my app based on "micro-services", symlinking shared code into 4 different meteor apps.  This is the output for starting a single app by itself.

Here's a [package list](http://pastebin.com/LJ9np4iY) if that helps.

**Comment by MichaelJCole** [comment]
One other comment.  While looking through the .db file, entries with README files appeared to be spread out over multiple pages/blocks in the file.  So visiting the `content` field in a SQL query would have to load multiple pages.

Keeping each record on one page/block may speed up your work.  I don't know enough about sqlite's architecture to make a better suggestion, but know a fragmented file when looking at one.

This would be especially problematic if you had to visit a record, to look up other records to visit.

**Comment by dgreensp** [comment]
Ah, wow.  From my investigations so far, I think that 11s does include some other stuff -- like sorting lists of package version numbers and inefficiently re-parsing them in the comparison function -- but I'm not sure how much.

Can you post `.meteor/packages`?  (Is an empty app with the same `.meteor/packages` also slow?)

As for storing data larger than a block in SQLite, it does seem like fragmentation could be an issue, though I've been led to believe by this document about the efficiency of storing blobs in SQLite vs. files that, on average, the block size does not have a huge impact on the efficiency of storing large blobs: https://www.sqlite.org/intern-v-extern-blob.html

I'm sure there is plenty to optimize here; don't get me wrong.  We could check the validity of `.meteor/versions` without reading all the data about all versions of all dependencies and running the constraint solver, for example.  Batching queries to SQLite also might help.

**Comment by ljack** [comment]
@MichaelJCole I've pretty similar problem. Here's [one](http://pastebin.com/VCK33e0q) of my build logs which shows similar numbers as yours.  I ran some "select counts" in the packages db with [this](http://pastebin.com/hBhVfHZ3) simple bash script.

```
table count
bannersShown : 0
metadata : 1
releaseTracks : 47
syncToken : 1
builds : 57424
packages : 11000
releaseVersions : 466
versions : 56056
```

**Comment by dgreensp** [comment]
@sebakerckhof I know people are seeing times like this for builds (especially initial build, and 30 seconds for sure for some rebuilds), but it is a lot longer than I would like.

**Comment by ljack** [comment]
@dgreensp I can provide you a semi-private access to Cloud9 IDE where I'm seeing this problem. Would that help?

**Comment by MichaelJCole** [comment]
Hmmm...  On ext4, the default page size is 4k.  So maybe SQLite offers larger page sizes for blobs so that it grabs them all in one request.  It would be better, but still lead to unnecessary IO.  

If the blob was bigger than the SQLite page, it would require an IO read, some thinking to find the next SQLite page, then another read.  That could be a huge drag, but I couldn't say more than that.

Attached is a list from the packages dir.   [packages.txt](https://github.com/meteor/meteor/files/114892/packages.txt)

Ooof.  I just did `meteor create test` and it took about 2 minutes.  Here's a [pastebin on first run](http://pastebin.com/tMeAFbBJ) and [a 2nd run that took 15s](http://pastebin.com/bcezkZY2).  This is without any custom code.

```
☔  meteor --version
Meteor 1.2.1
```

**Comment by ljack** [comment]
Had an idea to run ```meteor create test``` with METEOR_PROFILE=1 which turned pretty interesting results.

```
ljack1:~ $ meteor create test
|  Selecting package versions                |
| Select Package Versions: 9009.2
|     new CS.Input: 12.1
|     Input#loadFromCatalog (sqlite): 8222.9
|     new CS.Solver: 81.2
|         Solver#analyze: 80.8
|             analyze allowed versions: 9.9
|             analyze reachability: 2.4
|             analyze constraints: 66.2
|             analyze pre-releases: 1.1
|     Solver#getAnswer: 692.2
|         new Logic.Solver (MiniSat start-up): 18.5
|         require root dependencies: 1.3
|         generate package variables: 12.3
|         generate dependency requirements: 20.3
|         generate constraints: 31.6
|         pre-solve: 202.4
|         minimize unknown_packages: 1.8
|         minimize conflicts: 16.3
|         calculate new_root version costs: 1.1
|         lock down important versions: 2.4
|         calculate new_indirect version costs: 2.1
|         minimize total_packages: 375.1
|         generate version map: 1.4
|         other Solver#getAnswer: 4.4
| 
| Input#loadFromCatalog (sqlite): 8222.9
| minimize total_packages: 375.1
| pre-solve: 202.4
| analyze constraints: 66.2
| generate constraints: 31.6
| generate dependency requirements: 20.3
| new Logic.Solver (MiniSat start-up): 18.5
| minimize conflicts: 16.3
| generate package variables: 12.3
| new CS.Input: 12.1
| analyze allowed versions: 9.9
| other Solver#getAnswer: 4.4
| lock down important versions: 2.4
| analyze reachability: 2.4
| calculate new_indirect version costs: 2.1
| minimize unknown_packages: 1.8
| generate version map: 1.4
| require root dependencies: 1.3
| calculate new_root version costs: 1.1
| analyze pre-releases: 1.1
| Total: 9005.9
Created a new Meteor app in 'test'.           

To run your new app:                          
  cd test                                     
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn  
```

**Comment by dgreensp** [comment]
@MichaelJCole Thanks for the info.  For the packages list, what I actually need to repro is a copy of the `.meteor/packages` file from your app directory.  You're right that there's no inherent reason we need to re-run the constraint solver each time; the code just needs some factoring to make it possible to check the constraints accurately (which requires loading some information from sqlite and applying some of the same logic) without doing a full run.

@ljack, my times are less than half that for some reason: 4 seconds to Select Package Versions and 9 seconds of wall-clock time total to run `meteor create`.  It's the same in version `1.2.1` and `1.3-modules-beta.6` (the latest).  I wonder why.  My machine is a 2013 13" MacBook Pro, 2.4 GHz i5 with SSD.

**Comment by MichaelJCole** [comment]
@dgreensp Ok, awesome, happy to help: https://www.dropbox.com/sh/aew3ecswgsmra2k/AABT1MzAHQteqTTgaztUagjRa?dl=0

If there's anything else I can do, just ask :-)

**Comment by dgreensp** [comment]
I'm actually looking for the `.meteor/packages` file inside your *app* that lists the direct package dependencies of the app.

**Comment by MichaelJCole** [comment]
Aha!  My mistake.  
[meteor.zip](https://github.com/meteor/meteor/files/119286/meteor.zip)

**Comment by dgreensp** [comment]
This change I made today (coming in the next 1.3 beta) should help things quite a bit: d6e9921bbbf33943ce3c1f64ec4224d751eaf163  Now, in the usual case where `.meteor/versions` contains a fully valid set of versions from a previous run of the tool, the tool will try constraint solving without even loading any metadata about other versions.

**Comment by dgreensp** [comment]
linked here: https://github.com/meteor/meteor/blob/release-1.3/tools/PERFORMANCE.md#constraint-solving

**Comment by MichaelJCole** [comment]
@dgreensp @sebakerckhof That's awesome, thanks!  I really appreciate it.  I'm looking forward to 1.3 :-)

**Comment by sebakerckhof** [comment]
Well, I didn't actually do anything :P

**Comment by hwillson** [comment]
Meteor [1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142) has brought many build tool performance improvements to the table. I'll close this issue off since it's related to performance issues with an older Meteor version, but if you still think there is an issue please re-test with the latest Meteor version, and post your findings. Thanks for reporting this originally!

**Comment by MichaelJCole** [comment]
Thanks for improving it!  It's made the DX much better.
