### ISSUE TITLE
[1.3] Babel bug causes "Duplicate declaration"

### ISSUE THREAD

**Issue by PEM--** [meteor/meteor#6138]
Sample JS:

``` js
class Test {
  myVal() {
    let myVal = '';
  }
}
```

This fails to compile telling `myVal` is read-only and duplicated:

``` txt
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   evenements-snvel.js:4:10: /evenements-snvel.js: Duplicate declaration "myVal"

   While processing files with ecmascript (for target os.osx.x86_64):
   evenements-snvel.js:4:10: /evenements-snvel.js: Duplicate declaration "myVal"
```

See: https://github.com/kadirahq/flow-router/issues/505

**Comment by avital** [comment]
Yes, this is a bug in Babel 6. We're not going to fix it right now. In the meanwhile you'll have to rename your variables.

**Comment by benjamn** [comment]
Relevant Babel issue: https://phabricator.babeljs.io/T2684

**Comment by PEM--** [comment]
Indeed. I was using Babel 5.8.25 for my comparison. Thanks for your feedback.

**Comment by abernix** [comment]
This should be fixed in more recent versions of Meteor+Babel.  Thanks for reporting it.  Happy to reopen if you're still experiencing the problem on current versions!
