### ISSUE TITLE
Weird behavior using check and objects with prototypes

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#6140]
Check seems to only check for an object's own properties, e.g. this will run fine, without affecting the `child` object:
```js
var parent = {foo:"bar"};
var child = Object.assign(Object.create(parent),{bar:"foo"}); 
check(child, {bar: String,});
```

Let's say you have an object `child` as above and you run this code:
```js
check(child, {bar: String});
myCollection.insert(child);
```
This will insert a document with properties `foo` and `bar` in myCollection.

I know that in 99% of the cases `check` will be used on values coming from JSON (through DDP), but I'd like to argue that the package shouldn't make this assumption and a developer could reasonably assume/expect object `child` to only contain property `bar` after running through `check`. Therefore the current behavior, as described above, is weird and error-prone.

**Comment by tmeasday** [comment]
I'd probably argue the real issue here is that minimongo is pickup up prototypical properties and inserting them into the DB. This seems the wrong behavior to me. I think it's a duplicate of https://github.com/meteor/meteor/issues/4260 really.

**Comment by sebakerckhof** [comment]
I don't agree, because even if you leave out the minimongo part, the behavior of `check` is still weird to me:
```js
var parent = {foo:"bar"};
var child = Object.assign(Object.create(parent),{bar:"foo"}); 
check(child, {bar: String});
if(child.foo){ 
  console.log("this is not what I'd expect"); 
}
```

Since `check` is its own package and actually quite useful for a lot of stuff (I believe @stubailo mentioned it could be a good stand-alone NPM package for the larger JS community), I think it makes sense to make it work with objects that have prototypes.

+ It's a really small change, I can provide a PR, but I want to verify if there's a specific reason not to do it that way.

**Comment by tmeasday** [comment]
@sebakerckhof We are really recommending people use simple-schema to do schema checks these days and if anything looking to deprecate check. Perhaps that was the package @stubailo was referring to?

I'd be hesitant to change the semantics of `check()` given it's such a security critical feature and we'd have to think through the implications. It does sound like what you are proposing would be an in improvement though. @stubailo what do you think?

**Comment by stubailo** [comment]
@tmeasday I did suggest that if we plan on keeping around check, we should make it an npm package and encourage all kinds of people to use it. It looks like considering non-own properties would only make check _more_ restrictive, not less, so it doesn't look like it would be a security issue.

Only thing that I'm worried about is that people might end up with check calls that used to succeed, but now will fail. Is that something we are OK with?

**Comment by tmeasday** [comment]
I think probably yes because it seems like such an unusual use case, that it's not likely to bite too many people. If they are relying on the current behaviour they might be confused about what's going on anyway. Shall I mark it PR-encouraged?

**Comment by stubailo** [comment]
Sure, sounds good!

**Comment by sebakerckhof** [comment]
@tmeasday Actually it's looking into this behavior of simple schema: https://github.com/aldeed/meteor-simple-schema/issues/545 that brought me here. But the behavior of simple-schema is much worse, since as soon as an object has a prototype, it isn't being checked at all and everything you put into it passes.

I added a note to history.md in my PR about the change, maybe it should be marked as a possibly breaking change. But like you said, it's not likely to affect many people (if any).

**Comment by sebakerckhof** [comment]
Closing per https://github.com/meteor/meteor/pull/6148

**Comment by mitar** [comment]
@stubailo: If you are thinking of replacing `check`, I would suggest you just go and start using JSON schema. I used [this package in the past](https://geraintluff.github.io/tv4/) and it is really nice.

And then you can be compatible with the rest of the world/ecosystem. So nor `check` and nor simple schema are really embracing the JavaScript ecosystem.

**Comment by mitar** [comment]
I commented in the [pull request](https://github.com/meteor/meteor/pull/6148#issuecomment-189600727) why I think this should be reverted. It goes directly against explicitly stated semantics in the documentation. It is not something which was overlooked.

**Comment by mitar** [comment]
But I agree that based on the documentation, `check` should fail if object is not a plain object but has prototype. Now I see that it is not really failing, but I was always assuming it will.

**Comment by mitar** [comment]
This should be reopened. My plan is to:
* make `Match.ObjectIncluding` throw an error if object is not plain
* add `Match.FullObjectIncluding` which traverses prototypes

**Comment by mitar** [comment]
I will simply use jQuery.isPlainObject and port it to the server-side as well.

**Comment by mitar** [comment]
@stubailo: I have made #6392.

I have not made `Match.FullObjectIncluding`, no time. @sebakerckhof, I would propose that if you would like to have the behavior you want, you implement `Match.FullObjectIncluding` with documentation and tests and make a pull request.
