### ISSUE TITLE
Allow return statements at module top level

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6144]
This may already be fixed by https://github.com/meteor/babel/commit/4c329c46f1a1c9aa3df5ce465e25556aa9754aee.

**Comment by trusktr** [comment]
@benjamn Hello Ben, what does this let us do?

**Comment by benjamn** [comment]
@trusktr conditionally returning at the top of a module is a good way to avoid having to wrap the entire module in an `if` statement

**Comment by trusktr** [comment]
@benjamn For sure. It's the same as with Node modules I suppose. While we're at it, can we make the module wrapper function an `async` function? :smile:

```js
// some-file.js
await promiseReturningFunc()
// ...
```
