### ISSUE TITLE
Is jsx extension on files really needed for jsx to work?

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#6151]
This is in response to [this issue](https://github.com/meteor/meteor/issues/6150) I had.

Typically what I've seen in the React community is that people use the `react` Babel preset to make `jsx` work out of the box with regular `.js` files. Are you guys going to follow in this manner or do we need to keep naming our files `.jsx` if we use `jsx`?

**Comment by stubailo** [comment]
@benjamn I think we should try to enable this, IMO this is pretty simple to do? Most React boilerplates I've seen don't use the `jsx` extension anymore, and they also don't include the file extension in the import statement. This would include #6152

**Comment by avital** [comment]
Yeah @stubailo persuaded me that this is important to allow jsx example code to work out-of-the-box in Meteor.

**Comment by tomitrescak** [comment]
Please resolve also ".ts" and ".tsx" extensions in order for typescript to work. Thanks.

**Comment by benjamn** [comment]
JSX will be enabled in `.js` files in the next beta release.

**Comment by tomitrescak** [comment]
Does this mean that you will not be resolving .jsx files? That is sad to hear. All major dev tools recognise jsx code only in jsx files and will throw errors in js files. I think that it is much cleaner just to resolve jsx. What do you. Think? It also does not solve problem with Tyoescript, where react code has to be in TSX files.

**Comment by benjamn** [comment]
@tomitrescak I think you'll be happy to see what we're doing re: optional import extensions: https://github.com/meteor/meteor/issues/6152#issuecomment-189449753

We won't be throwing errors for JSX in `.js` files, but we will automatically append `.jsx` to imported module identifiers, if you're using a compiler plugin that handles that file extension, such as the official Meteor `ecmascript` package.

**Comment by benjamn** [comment]
[Here](https://github.com/meteor/meteor/blob/ae8705a74e88472f5b4b677270ef1cbc881cf89e/packages/ecmascript/plugin.js#L2)'s where the `ecmascript` plugin lays claim to `.js` and `.jsx` files. Anything in the `extensions: [...]` list of a compiler plugin becomes an optional import extension for code that uses the plugin.

**Comment by tomitrescak** [comment]
@benjamn great news indeed;) thanks. Great work!

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).
