### ISSUE TITLE
Allow configuration of optional file extensions, like .jsx and .ts (in addition to .js and .json)

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#6152]
For a given `Todos.jsx` file:

This doesn't work,
`import Todos from './Todos';`

But this works,
`import Todos from './Todos.jsx';`

**Comment by rclai** [comment]
Will this get a 1.3 milestone tag?

**Comment by avital** [comment]
Yeah @stubailo persuaded me that this is important to allow jsx example code to work out-of-the-box in Meteor.

**Comment by rclai** [comment]
:+1:

**Comment by benjamn** [comment]
Let's consolidate this discussion over at #6151. Definitely want to fix this for 1.3.

**Comment by zol** [comment]
#6151 will enable this for 1.3, we'll work on this particular feature post 1.3

**Comment by benjamn** [comment]
Specifically, #6151 enables JSX syntax in `.js` files, so if you stick to `.js` for your React code, you won't have to use an explicit file extension when you import.

**Comment by Urigo** [comment]
@benjamn you closed #6034 in favor of this one, but it looks like it is solved only for `jsx`.
Does it mean we need to re-open #6034 ?

**Comment by benjamn** [comment]
With [this commit](https://github.com/meteor/meteor/commit/22d423e5a5a1944b81870f4a2da7022a2fd45eed), the list of optional import extensions will be determined automatically by the compiler plugins that are enabled. So if you have a compiler plugin that handles the `ts` extension, you can import `.ts` files without an explicit extension. Note, however, that the `.js` and `.json` extensions will always be tried first.

**Comment by Urigo** [comment]
@benjamn very cool!

**Comment by rclai** [comment]
Thanks for this!

**Comment by D1no** [comment]
@benjamn sorry, I did not want to open a new ticket as I think its related:
Does omitting the file extension only work on relative paths?

When I do this in a `/client/main.js` file:
```js
// finds routes.jsx
import { renderRoutes } from '../imports/routes';
```
```js
// finds routes.jsx
import { renderRoutes } from '/imports/routes.jsx';
```
```js
// does NOT find routes.jsx
import { renderRoutes } from '/imports/routes'; //no file extension & absolute path
```

Files are often transpiled (i.e. from typescript). So requiring a file without stating its file-extension is a good way to ensure that in typescript the require leads to `routes.tsx` and in the transpiled format to `routes.js(x)`. Same with jscss etc.

Only working with relative paths can be quite confusing.

**Comment by Urigo** [comment]
@D1no I think it's better to separate the issues and open a different one and reference this one

**Comment by D1no** [comment]
kk
