### ISSUE TITLE
Application not starting on Android Simulator as well as Android Device on Mint 17.2

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#6153]
Hi,
I have same issue with [this](https://github.com/meteor/meteor/issues/5451) but my issue not fixed.
I have been trying to run application on Android Simulator as well as Android Device for a week now and failing to get it to work. I have followed the steps mentioned on [this](https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-Android-on-Linux) page. The app is working on browser but when I run ```meteor run android``` or ```meteor run android-device``` the process gets stuck at this point (***this is my terminal output for ```meteor run android-device --verbose``` after 15 minutes***):
![meteor android error](https://cloud.githubusercontent.com/assets/8266479/12806179/d6d38d98-cb18-11e5-8f98-0db039c854db.png)

and also this is my ```adb devices``` output:
```
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 
TGSSEQGQ95GEJVAI	device
```
What is the issue??
What are this points (.) in terminal output?
How to fix it?
It's going me crazy :cry:

**Comment by martijnwalraven** [comment]
Have you been able to get this to work yet? From your description, I have no idea what could be wrong. It seems you're already running with `--verbose`, so I would expect errors to show up.

**Comment by cyclops24** [comment]
Hi, Thanks for your attention.
I wait for **near 1 hour** and finally it run on my device after many dot (.) :cry: 
I don't know why but first time running of mobile application is sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo slow.
I don't know why but development speed really bad on my device.
(I have a HP 4530 notebook with 4 core i7 CPU and 8 gig RAM)
