### ISSUE TITLE
[1.3 beta 6] ReferenceError: regeneratorRuntime is not defined after updating from beta.3 to beta.6

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6154]
After updating to beta.6 from beta.3, I get the error

```
Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at Scene._mount (http://localhost:3000/packages/modules.js?hash=88e0e9e7d9a1d0f618e712143042d2b1beba448a:15990:20)
    at new Scene (http://localhost:3000/packages/modules.js?hash=88e0e9e7d9a1d0f618e712143042d2b1beba448a:15983:34)
    at beFamous$ (http://localhost:3000/app.js?hash=c196677f6bcd8113027dd7fc90a151e4e57374d9:132:37)
    at tryCatch (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:549:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:825:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:582:21)
    at tryCatch (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:549:40)
    at invoke (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:625:20)
    at http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:670:11
    at callInvokeWithMethodAndArg (http://localhost:3000/packages/babel-runtime.js?hash=2dd8b17813cb93e36f7dbca3715e2aa9892c0622:669:16)
```

Reproduction:

```sh
git clone git@github.com:trusktr/site.git
cd site
git checkout meteor-issue-6154
npm install
meteor
# visit localhost:3000, it works (red spinning square)
meteor update --release 1.3-modules-beta.6
meteor
# visit localhost:3000 and now you'll see the error.
```

**Comment by trusktr** [comment]
It happens when updating to beta.5 too, but no problem when updating to beta.4 (from beta.3). Maybe this problem was introudced in beta.5.

**Comment by trusktr** [comment]
It probably has to do with the update from Babel 5 to 6.

**Comment by trusktr** [comment]
After looking in my app, I see I have the file `node_modules/babel-runtime/regenerator/runtime.js`, while it seems Meteor is [looking for](https://github.com/meteor/meteor/blob/release/METEOR%401.3-modules-beta.6/packages/babel-runtime/babel-runtime.js#L395-L398) `node_modules/babel-runtime/regenerator.js`, which doesn't exist.

@avital Could this be an example of [the conversation](https://github.com/meteor/meteor/issues/5890#issuecomment-171232235) we were having on users needing to micro-manage NPM dependencies? I.e. Have I installed the wrong version of babel-runtime somehow?

**Comment by trusktr** [comment]
Oh, wait, that `meteorInstall` call is setting up that path for use by the app, it's not necessarily an existing path in the filesystem, so I'm not sure what the problem is.

**Comment by trusktr** [comment]
Hmm, well, I `npm install`ed `regenerator` in the app, and that didn't work, so maybe this isn't a case of needing to manage NPM deps @avital.

**Comment by trusktr** [comment]
Alright, so after importing `regenerator` manually in my only main.js, I got past the error, which then got me to another error about not finding the `assert` module, so I installed that, then that got me to the next error about something else missing.

It seems lots of things are missing, and I could eventually fix the problem by installing everything, error by error, which would take a long time.

**Comment by avital** [comment]
Can you supply a minimal repro?

**Comment by trusktr** [comment]
@avital that's pretty minimal already, look in main.js, which imports home/index.js, and that uses async/await. Unfortunately I don't have time to make a new repro right now; that one just happened by chance. I'll be on beta.4 for now in order to get some work done (gotta make rent money!).

**Comment by benjamn** [comment]
Since `beta.6`, which was the release where we upgraded Babel to version 6, `regeneratorRuntime` is no longer globally defined. Instead, Babel 6 generates code that imports it when necessary. So this could be a caching issue, where code previously compiled with an earlier beta version is still cached somewhere? If that's the case, then a `meteor reset` might do the trick, but this is definitely an upgrade bug that we would want to fix.

**Comment by benjamn** [comment]
It looks like `node_modules/infamous/motor/Scene.js` was compiled and published to npm assuming a Babel 5-like runtime environment.

We can make `regeneratorRuntime` global again, but that would cause the runtime to be evaluated on every page load, instead of getting evalated lazily when Babel 6-compiled code needs it.

As a workaround, perhaps you can make it global yourself:
```js
global.regeneratorRuntime = require("babel-runtime/regenerator");
```
before importing anything from `node_modules` that might need it?

**Comment by benjamn** [comment]
I can confirm that putting
```js
regeneratorRuntime = require("babel-runtime/regenerator");
```
in a file called `lib/regenerator.js` appears to make the app work again.

**Comment by trusktr** [comment]
@benjamn Thanks! That indeed works. 

For "single page apps" (which I think everyone using Meteor is aiming for) I think it'd be fine to load regeneratorRuntime by default so async/await would work out-of-the-box.

Maybe Babel has a way to automatically expose `regeneratorRuntime`  to built code if generators or async functions were used in the original source?

**Comment by trusktr** [comment]
@benjamn In my NPM module (infamous) I put this at the top of all the files that use async functions so that users don't have to do it manually:

```js
import regeneratorRuntime from 'babel-runtime/regenerator'
if (!Object.keys(window).includes('regeneratorRuntime'))
    window.regeneratorRuntime = regeneratorRuntime
```

But it seems like a hack. Is that the only way? Any ideas?

**Comment by trusktr** [comment]
Hmmm, it seems I can just do

```js
import 'babel-polyfill'
```

in my NPM module, which isn't as verbose (but might apply polyfills in a way not as Meteor designed).
