### ISSUE TITLE
dfischer:faker package doesn't work on the client

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6155]
Repro: https://github.com/tmeasday/faker-1.3-problem

I'm not totally sure, but I suspect the issue is that this package adds a JS file on the client (which ordinarily would have attached itself to `window`), but doesn't `api.export()` anything.

Note there is _no_ way to use this package on the client now. In this case, you probably may as well just install `faker` from npm anyway, but I suspect there may be other cases that aren't so easy to work around. Or at the least it's a difficult migration path for people.

**Comment by trusktr** [comment]
Do we expect to be able to import things (using CommonJS or ES6) from Meteor packages that were `api.export`ed? In other words, if `some:package` `api.export`s `Foo`, then the app code should be able to `import Foo from 'some:package'`?

**Comment by benjamn** [comment]
@trusktr yes, but it will be a named export, and there will be a `meteor/...` prefix in the module identifier: ```js
import {Foo} from "meteor/some:package";
```

**Comment by avital** [comment]
@tmeasday Looks like the package only exports on the server? https://github.com/dfischer/meteor-faker/blob/master/package.js#L17

Sounds to me that this is the correct behavior? What do you think?

**Comment by avital** [comment]
Oh. I see now. There is a different file added on the client by the package which tries to attach itself either using `module.exports`, AMD, or `window` if it doesn't find the others.

And before 1.3 neither `module` nor `exports` were defined so this worked.

**Comment by avital** [comment]
Hmm. I thought 1.3 knew how to notice new properties on `exports` and make it have the same behavior as calling `api.export`.

I don't care so much about this particular package (since it's better to install via NPM directly) but it's worth understanding what's going on for a little bit more.

**Comment by tmeasday** [comment]
Yeah, I suspect there are a fair few wrapper packages out there that on the client side have just copied the distributed JS file from the source, which will similarly check for `modules.exports`. Chances are most of them can be replaced in a similar way, but it makes for a unpleasant upgrade experience to have to figure this out.

**Comment by zol** [comment]
@benjamn should we bump this to post 1.3?

**Comment by hwillson** [comment]
I just ran the repro with the latest version of Meteor (1.4.2.3) and it worked properly. Looks like this has been fixed - closing - thanks!
