### ISSUE TITLE
[mobile] existing config.xml should merge with mobile-config.js not overwrite its content

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#6159]
Since the the `App.` API doesnt fully support every configuration that is possible to define in cordovars `cordova-build-override/config.xml`, its rather common to have both. But in this case every config defined with JS and its resulting `config.xml` will be ignored and replaced by the `config.xml` from the override folder. I know thats on purpose ([wiki: ovewriting existing files with `cp -R`](https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration#advanced-build-customization)), but then the great `App.` API, which helps to write less xml, is totally obsolete.

I am a bit new to the using-meteor-for-mobile thing. So I might be wrong on that. Then, please correct me, if I am 'holding it wrong'.

**Comment by lpender** [comment]
I'm feeling the pain of this too--not sure what the best practice is here.

**Comment by timbotnik** [comment]
Agreed this would make a lot of sense - @martijnwalraven can you confirm this is an issue?

**Comment by martijnwalraven** [comment]
I agree this could be an issue, but I don't think this is the solution. I don't want our integration to be responsible for parsing both `config.xml`s and merging the result.

The alternative is to expose better ways of modifying `config.xml` through our own `mobile-config.js` mechanisms.

What settings specifically are you missing?

**Comment by lucendio** [comment]
@martijnwalraven asks for elaboration on the steps I described in https://github.com/meteor/meteor/issues/6205:

Step 6 is to have only on single place to maintain these information. I just want to have the ``config.xml`` OR ``mobile-config.js`` - currently thats not possible because ``mobile-config.js`` lags on possibilities a/o flexibility. In my case, disabling ``App.info`` in the ``mobile-config.js`` breaks the mobile build because its not defined and the cordova builder defaults to project folder name. Again, In my case thats ``app`` (in our projects - for other deployment reasons). So the builder (or somewhere deeper) performs some string search and replace, as mentioned in https://github.com/meteor/meteor/issues/6205.

Does this clear things up?

**Comment by martijnwalraven** [comment]
@lucendo: Thanks for elaborating. The underlying question is why you need to modify `config.xml` manually at all. What settings or features are missing from `mobile-config.js` for you?

I agree we should have a single place to maintain this information, but I'd rather have that be `mobile.config.js`.

**Comment by lucendio** [comment]
Absolutly, js/json syntax makes way more sense ;)
In our case we have to define some platform related hooks. to be more specific: 
´´´
<platform name="ios">
    <hook type="before_build" ... />
</platform>

<platform name="android">
    <hook type="after_prepare" ... />
</platform>
´´´

**Comment by Abhimanyu008** [comment]
my app is crashing as it is not able to connect with localhost:12592 , the content src was defined as locahost:12592 in the config.xml of cordova as well as allow navigation is also defined to localhost. How could i overwrite these value in config.xml using mobile-config.js.

**Comment by martijnwalraven** [comment]
@Abhimanyu008: You shouldn't override these values, as the app is served from the device and meant to connect to `localhost:<port>`.

What do you mean when you say your app is crashing? What errors do you get in `logcat`/Xcode logs and using Safari/Chrome remote debugging?

**Comment by Abhimanyu008** [comment]
I am running the app in android emulator and it is saying it is not able to
connect with localhost:12592.

Here is the log

I20160503-11:48:00.664(5.5)? 05-03 11:46:42.396  2727  2727 I MeteorWebApp:
Serving asset bundle with version: bdf47d8b746ff3c788ed4f54803f2ec1bfbc4b16
I20160503-11:48:00.879(5.5)? 05-03 11:46:49.435  2727  2727 I chromium:
[INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source:
http://localhost:12592/cordova.js (1185)
I20160503-11:48:00.880(5.5)? 05-03 11:46:49.614  2727  2727 I chromium:
[INFO:CONSOLE(1178)] "Channel not fired: onDOMContentLoaded", source:
http://localhost:12592/cordova.js (1178)
I20160503-11:48:00.915(5.5)? 05-03 11:47:02.475  2727  3261 W MeteorWebApp:
App startup timed out, reverting to last known good version
I20160503-11:48:02.595(5.5)? 05-03 11:47:31.978  3302  3302 I chromium:
[INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0,
default verbosity = 0
I20160503-11:48:02.608(5.5)? 05-03 11:47:32.922  3302  3302 W chromium:
[WARNING:resource_bundle.cc(285)] locale_file_path.empty()
I20160503-11:48:02.610(5.5)? 05-03 11:47:35.161  3302  3349 W chromium:
[WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
I20160503-11:48:02.610(5.5)? 05-03 11:47:36.583  3302  3302 I MeteorWebApp:
Serving asset bundle with version: bdf47d8b746ff3c788ed4f54803f2ec1bfbc4b16
I20160503-11:48:03.512(5.5)? 05-03 11:47:44.717  3302  3302 I chromium:
[INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source:
http://localhost:12592/cordova.js (1185)
I20160503-11:48:03.513(5.5)? 05-03 11:47:44.718  3302  3302 I chromium:
[INFO:CONSOLE(1178)] "Channel not fired: onDOMContentLoaded", source:
http://localhost:12592/cordova.js (1178)

I have attached the screent shot also


[image: Oodles Technologies Pvt Ltd] <http://www.oodlestechnologies.com/>

*Abhimanyu* Technical Architect, Oodles Technologies Pvt Ltd
Phone:   +91 124 4368 395
Mobile:   +91 9643171464
Email:     abhimanyu.singh@oodlestechnologies.com
Website:  http://www.oodlestechnologies.com/
Skype:     abhimanyu.oodles
Address: Unit No 951-955 , Tower B1, Spaze I-Tech Park , Sector 49 , Sohna
Road , Gurgaon , India , 122001
[image: Twitter] <https://twitter.com/oodlestech> [image: Facebook]
<https://www.facebook.com/OodlesTech> [image: Google +]
<https://plus.google.com/+Oodlestechnologies/posts> [image: LinkedIn]
<https://www.linkedin.com/company/oodles-technologies-pvt-ltd>
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Oodles
Technologies is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company.

**Comment by martijnwalraven** [comment]
I don't see it saying it can't connect to `localhost`, but app startup is timing out. This usually means there is a JavaScript error in your app. Have you used remote debugging to see what is going on? See [here](http://guide.meteor.com/mobile.html#logging-and-remote-debugging) for more information.

**Comment by Abhimanyu008** [comment]
I have used the apk created to install in my mobile and it doesn't crash
whereas in emulator it is crashing

[image: Oodles Technologies Pvt Ltd] <http://www.oodlestechnologies.com/>

*Abhimanyu* Technical Architect, Oodles Technologies Pvt Ltd
Phone:   +91 124 4368 395
Mobile:   +91 9643171464
Email:     abhimanyu.singh@oodlestechnologies.com
Website:  http://www.oodlestechnologies.com/
Skype:     abhimanyu.oodles
Address: Unit No 951-955 , Tower B1, Spaze I-Tech Park , Sector 49 , Sohna
Road , Gurgaon , India , 122001
[image: Twitter] <https://twitter.com/oodlestech> [image: Facebook]
<https://www.facebook.com/OodlesTech> [image: Google +]
<https://plus.google.com/+Oodlestechnologies/posts> [image: LinkedIn]
<https://www.linkedin.com/company/oodles-technologies-pvt-ltd>
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Oodles
Technologies is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company.

**Comment by martijnwalraven** [comment]
Have you used remote debugging to see what is going on?

**Comment by hwillson** [comment]
This is currently functioning as designed - instead of modifying Cordova's `config.xml` file directly, Meteor uses the `mobile-config.js` file to configure the project. That makes this a feature request.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bmobile%5D%20existing%20config.xml%20should%20merge%20with%20mobile-config.js%20not%20overwrite%20its%20content&body=Migrated%20from:%20meteor/meteor%236159) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
