### ISSUE TITLE
Can't call super inside a class definition

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6162]
Repro: https://github.com/tmeasday/super-beta.6-bug

The following code

```js
class Foo extends Mongo.Collection {
  insert() {
    return super();
  }
};
```

Leads to the following:

```
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
   super-test.js:3:11: super() outside of class constructor (3:11)
   
   While processing files with ecmascript (for target os.osx.x86_64):
   super-test.js:3:11: super() outside of class constructor (3:11)
```

Introduced sometime between `1.3-modules-beta.2` and `1.3-modules-beta.5`

**Comment by nchenbang** [comment]
I don't think that's a valid code. `super()` refers to the parent class constructor and you can only call it inside your class constructor. If what you want is calling the insert method on your parent class, it should be something like this

```javascript
class Foo extends Mongo.Collection {
  insert() {
    return super.insert();
  }
};
```

**Comment by tmeasday** [comment]
Wow, you are totally right. And yet this worked in 1.2 somehow. So weird .. @stubailo
