### ISSUE TITLE
Babel.parse should not enforce strict mode

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6166]
This causes a variety of errors, for example
```
While computing assigned variables:
   /packages/cfs_power-queue/packages/cfs_power-queue.js: Deleting local
   variable in strict mode (541:4)
   
=> Your application has errors. Waiting for file change.
```

**Comment by benjamn** [comment]
The fix is simple! https://github.com/meteor/babel/commit/823ac5721e5af4097f7f52ee7d5e4806536b5fc5

**Comment by Lenin7** [comment]
Is there a way to manually fix this since it's so simple? When will this patch be released? Thanks

**Comment by Sanjo** [comment]
@Lenin7 This is already in the latest release. Just update with `meteor update --release METEOR@1.3-modules-beta.8`.
