### ISSUE TITLE
Correction to meteor react documentation

### ISSUE THREAD

**Issue by vkhazin** [meteor/meteor#6168]
https://www.meteor.com/tutorials/react/components

Instead of:
    React.render(<App />, document.getElementById("render-target"));

Use:
    ReactDOM.render(React.createElement(App), document.getElementById("render-target"));

React.render - deprecated
`<App />` results in error when running 'meteor' from terminal:

> ../.meteor/local/build/programs/server/app/MeteorUi.js:15
> React.render(<App />, document.getElementById("render-target"));   // 7
> SyntaxError: Unexpected token <

**Comment by stubailo** [comment]
@yyx990803, we should try to update the React tutorial soon. I can help if necessary.

**Comment by yyx990803** [comment]
@stubailo should we do it with 1.3?

**Comment by stubailo** [comment]
It doesn't have to be aligned with the release, but we should probably do it at the same time that we ship the new data container, if we want to use that in the tutorial.

**Comment by hwillson** [comment]
Closing as the tutorial has since been updated - thanks for pointing this out originally!
