### ISSUE TITLE
Cookie/Cache made Meteor Apps inaccessible. 

### ISSUE THREAD

**Issue by elmarti** [meteor/meteor#6169]
I'm not sure what has caused this, but I have been working on 3 completely separate Meteor apps and they all became unusable at the same time. Yhe console logged that all of the Meteor object's fields didn't exist and it was the same for each site. After resetting my browser data, all sites reverted to the original functionality. This lasted for 2 days.

**Comment by stubailo** [comment]
Hey, I don't think we will be able to do anything about this without a reproduction, and it looks like the issue resolved itself. If a situation arises again like this, I'd also try clearing your `.meteor/local/build` directory.
