### ISSUE TITLE
Add ☄, :stars: or :rocket: to the GitHub repo's description

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#6172]
Makes the repo stand out in GitHub tops. See for example https://github.com/search?p=1&q=stars%3A%3E1&s=stars&type=Repositories:

![image](https://cloud.githubusercontent.com/assets/33569/12861316/5c45fce6-cc17-11e5-956f-f580a6b9fe64.png)

**Comment by stubailo** [comment]
Hey, I don't think the shooting star emoji is that good, and the other ones aren't aligned enough with the project. Do you think people look through the top project lists a lot to look for repositories? I would also be worried that this would make us look less serious for enterprise decision makers.

**Comment by dandv** [comment]
Just a thought, no problem. An emoji might convey an increased coolness factor to developers, but I can see how this may not be the tone MDG wants to convey to enterprise customers.

**Comment by stubailo** [comment]
Cool, thanks for the suggestion thought!
