### ISSUE TITLE
[meteor1.3-beta8] an npm module fails to resolve its module path

### ISSUE THREAD

**Issue by sungwoncho** [meteor/meteor#6173]
***1 Upvote*** I am unable to use [node-github](https://github.com/mikedeboer/node-github) npm module with 1.3 beta 8 because it fails to load its own file. This is related to https://github.com/meteor/meteor/issues/6114 which is already fixed.

When I instantiate a new `github` object by passing version number, the module requires an appropriate file according to the version number given on runtime.

e.g.
```
import GithubAPI from 'github';

let github = new GithubAPI({version: '3.0.0'});
```

Then the github module requires the appropriate file with [this code](https://github.com/mikedeboer/node-github/blob/master/index.js#L183).

But on 1.3 beta 8, the module fails to load its own file.

    Error: Cannot find module './api/v3.0.0'

Please see my reproduction repo: https://github.com/sungwoncho/meteor-1.3-bug

Using
* METEOR@1.3-modules-beta.8
* OSX El Capitan 10.11.2

-----------

**Update**

I think this issue happens when modules require files on runtime.

To use the module, I had to modify github module's source code to require files from the get-go, rather than on runtime. Namely the culprits were 

* [here](https://github.com/mikedeboer/node-github/blob/master/index.js#L183)
* [here](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/index.js#L22)  (it complained that `__dirname` was undefined, and putting the relative path did not work. So I had to copy&paste the whole json file rather than requiring it)
* [here](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/index.js#L36-L38).

**Comment by coolmenu** [comment]
yes when i use qiniu sdk, and have errors which same with you.

**Comment by leijing7** [comment]
+1

**Comment by benjamn** [comment]
@sungwoncho The next beta will provide `__dirname`, but it's unlikely we're going to be able to support `require` calls with dynamic expressions. You might have to `require` those modules using static string literals in your application code, or in a wrapper package.

**Comment by benjamn** [comment]
Looking at this again, I can understand why you would expect this to work on the server, as in Node, because Node has access to the entire file system, not just the modules that were bundled together during the build process.

Meteor 1.3 is a little different from Node, because it uses the same module bundling system on the server as it does on the client. In other words, your workaround of requiring files up front, so that they can be required dynamically at a later point, is necessary on the server as well as on the client.

Another strategy might be to create a wrapper npm package that depends on `github` and requires the necessary modules using string literals, so that the dependency scanner could find those modules at build time. That's basically the same as your workaround, just encapsulated in an npm package.

If that workaround is really annoying, it's possible that we could make this work by bundling all possible files when Meteor builds your server code. I would like to avoid that if possible, but I'm open to your input!

**Comment by sungwoncho** [comment]
@benjamn Now I understand that this issue happens because Meteor does not have access to file system, but rather bundles up modules during build process. Thanks for the explanation.

Granted, no one likes a workaround, but I'd like to demonstrate why the suggested workaround is such a pain:

---

* [Step 1](https://github.com/sungwoncho/meteor-1.3-bug/blob/05e43e32ee3c9f990a5ca8f1729173bd08ae2001/server/main.js), I get

    Error: Cannot find module './api/v3.0.0'

* [Step 2](https://github.com/sungwoncho/meteor-1.3-bug/blob/263c036e5cad12c9f602b75edf6bde1cda16594b/server/main.js)

    Error: Cannot find module './gists'

But the path `./gists` is relative to the file requiring it. So I need to jump into the module's directory structure to find out its path.

...

* [Step n](https://github.com/sungwoncho/meteor-1.3-bug/blob/2ebc6a63d399c31a46124b7f3781591c279447de/server/main.js)


I end up with this after a while (not a full solution because `__dirname` is not available in the version I am using).

---

I do not like this workaround because:

1. It is tedious. I would like to use any modules without having to use a hack.
2. If the module's file structure changes, I have to possibly go through the above steps over again.
3. If the number of files required on runtime grows, people will end up with a giant block of meaningless `import` at the top of a file.
4. I am sure there are a number of npm modules that requires files on runtime. Any time someone tries to use them in their Meteor app, they will face this issue and have to search for a solution.

Also I am *strongly* against wrapper packages. I think it is a step backward. I don't want to see explosion of "Meteor [insert npm module name] wrapper package" on npm all over again, just as we have seen in the past on Atmosphere. They are seldom maintained, and make the ecosystem overly complex. They are not the way to solve this problem.

How inefficient would the build process be, if Meteor bundles all possible files? Unless there is a huge trade-off, I think it makes sense to support `require` calls with dynamic expressions. After all, Meteor should bring the best of JavaScript and without this feature, I think module support is rather incomplete.

**Comment by benjamn** [comment]
Those are good arguments. Is it ok if we only include all possible files on the server? On the client, it's definitely more important to keep the bundle size as small as possible.

**Comment by sungwoncho** [comment]
I think that is reasonable. If someone wants to use dynamic `require` on the client, would she have to use the workaround, or will there be other solutions?

**Comment by benjamn** [comment]
The other option for dynamic imports on the client is some sort of asynchronous `require`, like Webpack's `require.ensure` or `System.import`.

**Comment by benjamn** [comment]
One more option: it might be pretty easy to detect if a package contains any dynamic `require` calls, and only include all the files in that case (when building the server bundle).

**Comment by zol** [comment]
Lets try the easy solution first and bundle all js files.

**Comment by benjamn** [comment]
For Meteor 1.3, server-side npm packages that rely on Node-specific behavior will need to be installed the old way, using `Npm.depends` in a Meteor package, and imported with `Npm.require`. I would very much like to make `Npm.require` completely unnecessary, but I don't want to delay 1.3 for that, given that there's a tolerable workaround (emphasis on tolerable).

**Comment by benjamn** [comment]
This is fixed in `beta.16`!
