### ISSUE TITLE
[1.3-modules-beta.8] isobuild:compiler-plugin addStylesheet and addJavaScript not working

### ISSUE THREAD

**Issue by huttonr** [meteor/meteor#6174]
I had previously submitted https://github.com/meteor/meteor/issues/6014

This previously only affected `addJavaScript` however it now affects `addStylesheet` as well.

The former has not been working since beta 1.  The latter since 6 or 7 and is as well not working in 8.

Note, I don't believe this applies to `caching-compiler` as the `less` and `ecmascript` packages both seem to still be working.  It appears specific to `isobuild:compiler-plugin`.  I have not tested this though.

I've updated the repro: https://github.com/huttonr/meteor-addjavascript-bug

**EDIT:** It does apply to CachingCompiler too it seems: https://github.com/huttonr/meteor-addjavascript-bug/tree/caching-compiler

**Comment by dotansimha** [comment]
Not sure if it the same, but since beta8, my compiler does not works anymore. 
It tries to add HTML file, and get this error:
```
=> Errors prevented startup:

   While processing files with angular2-compilers (for target os.osx.x86_64):
   /tools/isobuild/compiler-plugin.js:502:13: Document sections can only be
   emitted to web targets: client/index.html
   at ResourceSlot.addHtml (/tools/isobuild/compiler-plugin.js:502:13)
   at InputFile.addHtml (/tools/isobuild/compiler-plugin.js:310:24)
   at NgHtmlCompiler.addCompileResult
   (packages/angular2-html-templates/compilers/html_compiler.js:70:10)
   at packages/caching-compiler/caching-compiler.js:305:14

```

The last version I used was beta6 and it worked great...

**Comment by avital** [comment]
Thanks. We'll look into this.

**Comment by benjamn** [comment]
I believe this problem has the same cause as #6014, namely [this bad optimization](https://github.com/meteor/meteor/blob/143121d644d866f0e5f03dc2c731ac2c43cef6dc/tools/isobuild/compiler-plugin.js#L384-L388).

**Comment by huttonr** [comment]
See https://github.com/meteor/meteor/issues/6014#issuecomment-182766125

**Comment by benjamn** [comment]
Fixed in `beta.11`.
