### ISSUE TITLE
[1.3-modules-beta.8] Change in client code causes server reload

### ISSUE THREAD

**Issue by gadicc** [meteor/meteor#6182]
@dgreensp, the new load times are awesome!

I noticed that from `beta.7` to `beta.8`, a change in client code causes a server reload, as evident by `=> Meteor server restarted` vs `=> Client modified -- refreshing` and server initialization code being run again.

Don't think it's needed but a made a a tiny [repro](https://github.com/gadicc/meteor-client-refresh) in case, the README shows the output of a few different situations.

**Comment by dgreensp** [comment]
Seems client-only refresh stops happening in 35a02864aff85c829cb509f2bcbb8dfe67a64848 @benjamn

**Comment by avital** [comment]
Thanks. We'll fix this.

**Comment by JoaoFOliveira** [comment]
I was searching for this. In fact everything that goes in "client" folder or in "if (Meteor.isClient) {" triggers a server reload, unnecessarily.

**Comment by benjamn** [comment]
This is fixed in `beta.11`, but re: @JoaoFOliveira, changes in files that run on both the server and the client will trigger a server restart, even if the changes only affect code that never runs on the server, since we are not attempting any fancy reachability analysis.

**Comment by gadicc** [comment]
Thanks, everyone!

**Comment by reel** [comment]
Is it possible that a change in `imports` triggers a reload on client & server?

Seems like every time I change client related stuff in `imports`, it shows `Server restarted`...

**Comment by benjamn** [comment]
@reel try having separate `client/imports/` and `server/imports/` directories?

**Comment by reel** [comment]
Ok... I have the following structure (as per the guide): 

> /client/main.js
> /server/main.js
> /imports/ui/components (react components)
> /imports/ui/semantic (semantic ui react components)
> /imports/ui/api (collections, methods & al)

Moving components and semantic to `/client/imports/` should fix it?

Would be great to updated the guide :)
