### ISSUE TITLE
Allow manual setting of Meteor.loginToken, etc

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#6183]
I've noticed when you manually try to set the Meteor.loginToken, Meteor.loginTokenExpires, and Meteor.userId to localStorage, Meteor automatically removes it after a couple of seconds. I think it's being a bit over-protective here, and we should be able to set any token we would like. If, for whatever reason, the token is not valid, we should have some kind callback to handle it on the client.

**Comment by stubailo** [comment]
> Meteor automatically removes it after a couple of seconds.

Actually what is happening, is, Meteor stores the _real_ token in local storage in the browser. This is necessary for several reasons:

1. You need to share login state across browser tabs - it would be weird if you had to log in separately in every tab
2. You need to keep login state when you close the window and open it again

For these reasons, changing a variable in JS will never be enough. But I'm sure if we look we can dig up the correct API to actually update the token in local storage...

I think this is what you want: https://github.com/meteor/meteor/blob/0c332825bbe0360277b6abf9d4986d3044da1c2d/packages/accounts-base/accounts_client.js#L324

And nicely named, to boot! Let me know if calling that function works for you.

**Comment by msavin** [comment]
That function is nice, just what I've been looking for! Thanks man.
