### ISSUE TITLE
[1.3] How to manage architectures and exports when using external compiler and mainModule?

### ISSUE THREAD

**Issue by dotansimha** [meteor/meteor#6185]
@barbatus 

Hi,
I encountered a weird behavior with an app I try to create. 

I try to create a simple app with a login page, but I want to use a different import for each architecture: `web.browser` and `web.cordova`.

My stack is:
- Meteor 1.3 beta8
- Angular 2.0 (does not make any difference, mention it for the record)
- TypeScript using ts-compilers package: https://github.com/barbatus/ts-compilers/
- Custom HTML compiler

This is my structure:
````
client/
     app.ts
     app.html
     index.html
packages/
     login-for-browser/
          package.js
          browser-main.ts
          browser-login.html
          browser-login.ts
     login-for-mobile/
          package.js
          mobile-main.ts
          mobile-login.html
          mobile-login.ts
````

Each one of the packages has it's own `package.js`, which looks like that:
````js
Package.describe({
  name: 'login-for-browser',
  version: '0.0.1'
});

Package.onUse(function(api) {
  api.versionsFrom('1.3-modules-beta.8');
  api.use('ecmascript');
  api.use('angular2-compilers'); // The TS compilers & HTML compiler
  api.mainModule('browser-main.ts', 'web.browser');
});
````

**This mobile package is the same, just with `web.cordova` platform**

So the problem is:
In 1.3, the `addFiles` method is deprecated so I need to use a main file (in my case, `mobile-main.ts` and `browser-main.ts`) and to use `mainModule` to perform my imports.
So all of the `.ts` files are being compiled using my compiler, which returns regular CommonJS code, for **all** architecture, because I do not use the `addFiles` no more. 

The problem is that something wrong with `mainModule`:
- When specify `web.browser` - the main module loaded in both `web.browser` and `web.cordova` - looks like that actual value becomes `client`. 
- When specify `web.cordova` - the main file ignored entirely and does not loaded in any architecture.

Also, when changing my files to be `.js` files instead of `.ts`, it looks like the architecture works... so something wrong with the custom compiler...

Any idea?

**Comment by avital** [comment]
> Also, when changing my files to be .js files instead of .ts, it looks like the architecture works... so something wrong with the custom compiler...

`api.mainModule` should understand `"web.cordova"` and `"web.browser"`. And you say you've seen this to work with `.js` files.

So... This is a bug with the `.ts` compiler package you're using? This bug report should be filed against that package.
