### ISSUE TITLE
meteor list suggests running meteor update, meteor update ignores it

### ISSUE THREAD

**Issue by vladimir3000** [meteor/meteor#6187]
meteor list at current point (today) shows:

```
accounts-password     1.1.4  Password support for accounts
autopublish           1.0.4  (For prototyping only) Publish the entire d...
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI wit...
ecmascript            0.1.6* Compiler plugin that supports ES2015+ in al...
es5-shim              4.1.14  Shims and polyfills to improve ECMAScript ...
insecure              1.0.4  (For prototyping only) Allow all database w...
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.3  Adaptor for using MongoDB and Minimongo ove...
ovcharik:alertify     0.3.11  JavaScript Alert/Notification System for M...
session               1.1.1  Session variable
standard-minifiers    1.0.2  Standard minifiers used with Meteor apps by...
tracker               1.0.9  Dependency tracker to allow reactive callbacks


* New versions of these packages are available! Run 'meteor update' to try
  to update those packages to their latest versions. If your packages
  cannot be updated further, try typing
  `meteor add <package>@<newVersion>` to see more information.

```

Suggestion is caused by ecmascript as I understand by asterisk. But meteor update ignores suggestion about new packages:

```
>meteor update

This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions. 

```

> meteor update ecmascript

`The specified packages are at their latest compatible versions.
`
The error is either in latest version check or compatibility check or update procedure.

**Comment by vladimir3000** [comment]
More information: https://atmospherejs.com/meteor/ecmascript - is 0.3.0 that's why asterisk is put correctly. But the update mechanism is not triggered.

Also, the situation is on Windows platform.

**Comment by stubailo** [comment]
@benjamn, did we end up publishing a new version of `ecmascript` that isn't part of a new Meteor release?

**Comment by abernix** [comment]
@vladimir3000 Are you still experiencing this problem?

**Comment by ipa1981** [comment]
There is the same problem. I have plenty of packages sticked to old versions.

**Comment by hwillson** [comment]
A lot has changed with regards to package constraints since this issue was posted (if you're interested in a brief overview of the changes, see https://github.com/meteor/meteor/pull/8960#issuecomment-322511317). Please try again with a current version of Meteor (1.5.1 as of today). Thanks!
