### ISSUE TITLE
A way to get current Meteor package name

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6188]
In 1.2, I am not sure if there is a difference with 1.3, but it would be very useful to be able to get current Meteor package name. This would allow one to construct asset URLs without hard-coding stuff. I am doing some stuff with automatically resolving dependencies and loading them through the manifest file, so that would be also useful there.

**Comment by mitar** [comment]
Made pull request #6192.

**Comment by mquandalle** [comment]
I also encountered this issue.

**Comment by nathan-muir** [comment]
We definitely need some way of getting the URL; but, wouldn't something like `Assets.getUrl('myfile.txt')` be better, as it's the same API in app's and packages?

**Comment by mitar** [comment]
Oh, this would can then be used inside `Assets.getUrl` as well. This is just the primitive which is useful for both assets and other stuff.

**Comment by stubailo** [comment]
I think the idea is great, and we should have it. Looking at the PR, let's discuss the implementation there.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=A%20way%20to%20get%20current%20Meteor%20package%20name&body=Migrated%20from:%20meteor/meteor%236188) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
