### ISSUE TITLE
Server-side observe() impact on RAM?

### ISSUE THREAD

**Issue by mhagmajer** [meteor/meteor#6194]
Let's say I have two related collections: articles and authors. For performance reasons, on every author's document I'd like to keep the count of articles written by them. To achieve this I'll be using [`observe()`](http://docs.meteor.com/#/full/observe).

My application is going to store tens of thousands of such documents. How much does this increase RAM requirements for the server of my application?

**Comment by tmeasday** [comment]
Hey @mhagmajer, I think it depends on exactly how you plan to do it. If you use a approach like the https://atmospherejs.com/tmeasday/publish-counts and simply observe the `_id`s of the relevant author's articles on demand, then the observe driver will simply cache in memory a list of those relevant ids.

This can make sense if the # of articles per-author isn't too high and each user isn't looking at too many authors. If this isn't the case, then you might be better off using an alternate approach that basically just does a `.count()` and polls every now and then.

Does that answer the question?

**Comment by mhagmajer** [comment]
Thanks, Tom!

I'm only using observe on the server side. No data is published to clients
for this.

I am precisely interested in learning what is the memory usage of the
observer. Seems like you're saying that the current results of a cursor are
being cached in memory on the server side. Is that right?

**Comment by tmeasday** [comment]
That's my understanding, yes: https://github.com/meteor/meteor/blob/devel/packages/mongo/oplog_observe_driver.js#L73
