### ISSUE TITLE
[1.3b8]: "yup" npm not working on client (plus reproduction repo)

### ISSUE THREAD

**Issue by ciwolsey** [meteor/meteor#6198]
Trying to use this npm: https://www.npmjs.com/package/yup

Works on the server, doesn't work on the client. Here is a minimal reproduction:
https://github.com/ciwolsey/yup-minimal-reproduction/tree/master

There's a main.js on the server and the client which are identical, however I receive the error: "Uncaught TypeError: process.nextTick is not a function" on the client while the server version works as expected.

**Comment by huttonr** [comment]
Dup of https://github.com/meteor/meteor/issues/6167

**Comment by avital** [comment]
Will be resolved by #6056.

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).
