### ISSUE TITLE
[1.3-modules-beta.8] Implied package exports cannot be imported

### ISSUE THREAD

**Issue by reohjs** [meteor/meteor#6199]
E.g. https://github.com/meteor/meteor/blob/devel/packages/browser-policy/package.js#L8
```js
// server
import {BrowserPolicy} from 'meteor/browser-policy';

console.log('BrowserPolicy is: ', typeof BrowserPolicy); // BrowserPolicy is: undefined
```
Repro:

```bash
git clone git@github.com:reohjs/meteor-issue-6199.git
cd meteor-issue-6199
meteor
```
OS: Windows 7
Also tested local package with same implied export format.

**Comment by avital** [comment]
This is correct behavior. Imply means "have the app behave as if it added that other package". Use this import line instead if you want access to `BrowserPolicy`:

```
import {BrowserPolicy} from 'meteor/browser-policy-common';
```
