### ISSUE TITLE
[1.3-beta-8]Load order is not always correct

### ISSUE THREAD

**Issue by newsiberian** [meteor/meteor#6202]
Hello, in [reaction](https://github.com/reactioncommerce/reaction), we have a heavy global variable `ReactionCore`. It is created [here](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/common/global.js#L3) inside one of the packages and then is exported from [here](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/package.js#L381) to other packages.

I'm making a package for UI with `react` and `redux` and it is on 1.3-beta-8. In many places I do like so:
```js
import { ReactionCore } from "meteor/reactioncommerce:core";
```
and it works fine for a most cases, but I faced with situation in `package-name/modules/dashboard/reducers/index.js` where `ReactionCore` is not defined in time when I call it.

If it is needed I can prepare a repro repos.

**Comment by huttonr** [comment]
This doesn't look to me like a load order problem.  Possibly related to: https://github.com/meteor/meteor/issues/6165

**Comment by avital** [comment]
Please create a _minimal_ repro repository. (And not to be mean, but yes, any bug report should come with a minimal repro)

**Comment by newsiberian** [comment]
Oh. wait, while creating repro I've noticed that this imported object isn't showed in debugger but it  exists. It could be a problem related with [this](https://github.com/meteor/meteor/issues/5788#issuecomment-181422874). I think I close this issue for a while. Let wait till `sourceMap` will be fixed and then If this will back again I will ask about reopening the issue.
