### ISSUE TITLE
Crash when '#! /usr/bin/env node' contained in imported module

### ISSUE THREAD

**Issue by tjmonsi** [meteor/meteor#6204]
Hi everyone,

I just found a "sort of" bug. I was including `gcloud` in my project. Once I typed this:

```
import gcloud from 'gcloud';
```

It crashes and sends this:

```
~/project/.meteor/local/build/programs/server/packages/modules.js
#! /usr/bin/env node
^         
SyntaxError: Unexpected token ILLEGAL
  at ~/project/.meteor/local/build/programs/server/boot.js
  at Array.forEach (native)
  at Function._.each._.forEach (~/.meteor/packages/meteor-tool/.1.1.13-modules.8.1ix0lc8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js)
  at ~/project/.meteor/local/build/programs/server/boot.js
```

Apparently, the `gcloud` module requires `JSONStream` module. Looking around I found that a part of its source code is this...

```
#! /usr/bin/env node

'use strict'

var Parser = require('jsonparse')
  , through = require('through')
```

I tried just doing making a node js file and running using `node` and apparently, doing `require('JSONStream');` or `require('gcloud');` works... 

Is it the problem of babel's transpiler? I really need `gcloud` in my project but this is one big bummer if it doesn't work

**Comment by avital** [comment]
Thanks for the report. We should fix this.

**Comment by benjamn** [comment]
This will be fixed in the next beta.

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).
