### ISSUE TITLE
[mobile ios] xcode error: no such product type for the 'iphonesimulator' platform

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#6205]
within the error message one will find a similar string like: ``'com.MYAPPNAMEle.product-type.MYAPPNAMElication'``, where ``MYAPPNAME`` is the ``name`` in ``config.xml``

steps to reproduce:
0. ``$   meteor create app``
1. create a ``mobile-config.js`` w/ basic ``App.info`` (such as ``name`` and stuff)
2. create a ``cordova-build-override/config.xml`` w/ similar infos (at least ``name``)
3. ``$   meteor run ios-device``
4. build and simulate in xcode --> everything works
5. ``$   meteor reset``
6. DISABLE the ``App.info`` code in ``mobile-config.js``
7. ``$   meteor run ios-device`` again
8. the error occurs
(9. after that an additional reset and run/build wont make any change)

The ``cordova/builder.js`` defaults name to ``files.pathBasename(this.projectContext.projectDir)`` (line 73) which is in im my case ``app`` (because of step 0.). The wrong string mentioned at the beginning is located in  ``app/.meteor/local/cordova-build/platforms/ios/Pflegekurs.xcodeproj/project.pbxproj``. My guess is, that when ``App.info`` is not set, at first the builder creates a ``config.xml`` with these default values. Meanwhile cordova generates ``project.pbxproj``. Then generated ``config.xml`` will be merged/overwritten some how with the content in ``cordova-build-override/config.xml``, which I think, is also done by ``cordova/builder.js``, but I couldnt figure out where, sorry. And then, again cordova trys to update ``project.pbxproj`` with a simple regex replace old name with new name, and thats where everything breaks apart, because it searches for the first (default, in my case ``app``) name: ``'com.apple.product-type.application'`` gets changed to ``'com.MYAPPNAMEle.product-type.MYAPPNAMElication'``

Note: I am not sure about all of that. Based on my research, thats how I think it might work. So I dont know if this is a meteor or cordova bug. 

following issues might be related:
https://github.com/meteor/meteor/issues/5521
https://github.com/meteor/meteor/issues/6159
https://stackoverflow.com/questions/31465852/target-specifies-product-type-com-apple-product-type-bundle-ui-testing-but-th
https://forums.meteor.com/t/build-fail-on-ios/12665

**Comment by timbotnik** [comment]
It sounds like the iOS project is getting confused based on those steps.  

I would use the same instructions given by martijn on #5521: 

> The error message is fairly generic, but could be caused by the Xcode project getting into an inconsistent state. Could you try rm -rf .meteor/local/cordova-build to rebuild the project on the next run?

**Comment by lucendio** [comment]
the ``$   rm -rf ...``is done with ``$   meteor reset``. as I described, its reproducable and I think the issue lies somehow deeper, because there is an obvious pattern.

**Comment by timbotnik** [comment]
Right - but you didn't say that there was a reset between here:
> 6. DISABLE the App.info code in mobile-config.js
and here
>7. $ meteor run ios-device again

**Comment by lucendio** [comment]
you are right, this might be confusing. I made an addition to the steps

**Comment by timbotnik** [comment]
Great, that clarifies the issue for us!

**Comment by martijnwalraven** [comment]
Could you elaborate on what you're trying to do here? Why do you need to remove `App.info` from `mobile-config.js` (step 6 above)?

I don't think this is a scenario we can support. The `cordova-build-override` mechanism is fairly primitive and simply overwrites files. I don't think it is ever a good idea to completely overwrite `config.xml`, so if we are missing settings we should find another solution for that.

Closing this issue in favor of the conversation going on in https://github.com/meteor/meteor/issues/6159.

**Comment by qfaison** [comment]
my app is crashing and because of conetent src is defined localhost:12592 and allow-navigation is defined to localhost too. how could i overwrite these property of cordova using mobile-config.js
