### ISSUE TITLE
There doesn't appear to be a way to enforce password length server side (only client side).

### ISSUE THREAD

**Issue by mjgallag** [meteor/meteor#6206]

**Comment by stubailo** [comment]
This is because we hash the password on the client before we send it. Is it important to you to enforce this on the server? Which users of your app will be affected by this?

**Comment by mjgallag** [comment]
@stubailo to be perfectly honest i don't know off the top of my head if it matters from a security perspective ... if it doesn't then feel free to close this, thanks for the quick reply!

**Comment by stubailo** [comment]
It doesn't! I think if the user has to go through so much effort to shoot themselves in the foot with password length, it's their fault.
