### ISSUE TITLE
Meteor 1.3 beta 8 problem with NPM 3 Flat Dependency Folder system

### ISSUE THREAD

**Issue by tjmonsi** [meteor/meteor#6207]
Hi guys,

I found a bug in Meteor 1.3 when using NPM 3's flat dependency folder system... I replicated the system here:

https://github.com/tjmonsi/meteor-utils-inherit

It happens when you have this:

```bash
npm -v
3.x.x
```

Then when you type this, it works

```bash
rm -Ir -f node_modules
npm install
node server/main.js
```

but it doesn't work when you try this:

```bash
rm -Ir -f node_modules
npm install
meteor
```

It works again though when you do this...

```bash
rm -Ir -f node_modules
npm install --legacy-bundling
meteor
```

**tl;dr;**
It seems `sinon` installs `util`, and `eslint` installs `inherits`, when you use `multiparty`, it tries to use `util.inherits` which tries to get code from `inherits` but `inherits` tries to export `util.inherits`. Hence, circular dependency, making `util.inherits` null.

Explanation at the git repo.

**Comment by avital** [comment]
Thanks. @stubailo also hit this when trying to use Relay in Meteor with NPM3. We'll take a look.

**Comment by tjmonsi** [comment]
@avital Would it be because Meteor uses an older version of Node? I am already using Node 5 so the apparent circular dependency on a flat dependency structure is taken cared of. 

If a newer version of Node will be a solution, would it also cascade to us having to use a newer version of a mongo driver? I think it would be inevitable

**Comment by tjmonsi** [comment]
Nevermind, I just tried going to node version 0.10 but the pseudo-flat dependency I got still works (installing util and inherits inside the node_modules). I'll try doing a node version 0.10 and an npm version 3. See if it breaks...

**Comment by benjamn** [comment]
This might be fixed by implementing support for the "browser" field of `package.json` files: https://github.com/isaacs/inherits/blob/3af5a10c6b51f9e99d9f90394645d7ea630d5eaa/package.json#L16

**Comment by benjamn** [comment]
I believe this is fixed in `beta.11`. Thanks for the report and the reproduction!
