### ISSUE TITLE
64-bit support for Windows

### ISSUE THREAD

**Issue by aayushkapoor206** [meteor/meteor#6208]
The app goes out of memory very early on Windows. Is there be 64-bit support for Windows planned?

**Comment by stubailo** [comment]
Currently there isn't anything planned. We haven't gotten many reports of this issue though, is there something special about your app that causes it to use more memory?

**Comment by voegtlel** [comment]
Another argument for 64bit support on windows: E.g. the "sharp" image library only comes with 64bit binaries for windows, thus you can't use it on windows as proposed in https://angular-meteor.com/tutorials/whatsapp2/meteor/file-upload

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=64-bit%20support%20for%20Windows&body=Migrated%20from:%20meteor/meteor%236208) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
