### ISSUE TITLE
Consider a better pre-release mode

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#6209]
## Why

We even don't know which pre-release is the latest. Also, this makes the issues list in a mess. 
![image](https://cloud.githubusercontent.com/assets/2545261/12940830/e1989a90-d007-11e5-8b69-dc2780be04be.png)

So many different ways to decribe `1.3-modules-beta.8` !

## How

A separated pre-release page and a auto-labeling bot might be helpful. On the page, we have the latest pre-releases version numbers and the command to update, including a CHANGELOG. We can have a `I have problem` button for each pre-release linked to GitHub New Issue page with a special title preset by adding `&title=` after the URL of it.
The bot adds `pre-release` label and the version label to the issue, and remove the version number from title.

**Comment by zol** [comment]
Thanks for your feedback. We'll be overhauling our release process in the near future.
