### ISSUE TITLE
Not resolving "jsx" files in 1.3 

### ISSUE THREAD

**Issue by tomitrescak** [meteor/meteor#6212]
Hi, when importing jsx containers in 1.3 they have to be imported in a following manner:

`import Navigations from './navigations.jsx';`

This makes it difficult to use e.g. Typescript, which uses `.tsx` file extension. And does not allow to specify import as such.

In webpack, the situation is solved by specifying the list of resolved extensions ['.ts', '.js', '.tsx', '.jsx']. With this import can be written as following:

`import Navigations from './navigations';`

Would you consider something similar in order to be able to use Typescript in Meteor. Thanks.

**Comment by avital** [comment]
Dup of #6152 and #6034. Feel free to add the list of extensions you think we need to support.

**Comment by tomitrescak** [comment]
Good news! Sorry about the duplicate. Was searching for it. Thanks.
