### ISSUE TITLE
meteor mongo: Service temporarily unavailable.

### ISSUE THREAD

**Issue by emmarion** [meteor/meteor#6213]
My meteor website has been up and down sporadically for at least several days now, and I think the issue is mongo-related.

    eric ~/Documents/zeromailer/sociallist $ meteor --release 0.6.4.1 mongo www.zeromailer.com
    Password: 
    Service temporarily unavailable. Please try again later.`

Or:

    eric ~/Documents/zeromailer/sociallist $ meteor --release 0.6.4.1 mongo www.zeromailer.com
    Password: 
    <!DOCTYPE html>
    <html>
    <head>
      <title>Error</title>
      <style type="text/css">
      ....
      <div class="message">
        This site is down.
      </div>
      <div class="submessage">
        Try again later.
      </div>
    ....

This seems similar to, for instance: https://github.com/meteor/meteor/issues/3487

Any reason for the outage?

**Comment by zol** [comment]
Hey @emmarion. This was most likely caused by instability on our free application tier. We're currently working on moving the free tier across to the Galaxy backend (our new hosting service). You can monitor the status of our infrastructure at http://status.meteor.com .
