### ISSUE TITLE
Tool caching doesn't respect `package.js` changes

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6214]
This is hard to repro via a repository so instead try following the following steps.

```bash
meteor create test-app
cd test-app
meteor create --package exporter
meteor add exporter
# we do this *after creating the package* to make it like a 1.2 package being upgraded
meteor update --release 1.3-modules-beta.8
echo "export const foo = 42;" > packages/exporter/exporter.js
echo "import {foo} from 'meteor/exporter'; console.log(foo);" > test-app.js

# we don't expect this to work, but it caches things
meteor 

# now edit packages/exporter/package.js and change the `api.addFiles('exporter.js')` to `api.mainModule('exporter.js')`

# this time it should log 42 but it doesn't
meteor 

echo "// random stuff" >> packages/exporter/exporter.js


# this time it does
meteor 
```

You can even remove the random stuff comment and see it fail again! Good times.

**Comment by benjamn** [comment]
The linker has its own cache, and the cache key mostly depends on the set of files included in the bundle, and their hashes, but not (say) their file options. So I think when you change `api.addFiles` to `api.mainModule`, even though the `fileOptions.main` property of that file changes, the set of files is not changed, so the linker cache gives the same result as last time.

**Comment by benjamn** [comment]
This will be fixed in the next beta!

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).
