### ISSUE TITLE
HTTP.get throws error 

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6215]
This issue was closed but is not fixed yet (#2519)

An async call via HTTP.get() on the client returns an error in the callback, but also throws an error (on error code 400/500...). Regarding to the doc the error should only be thrown on a  sync call (on the server).

This can throw errors on a client (but should not):

```
HTTP.get("https://freegeoip.net/json/", (error, result) ->

)
```

**Comment by stubailo** [comment]
I'd accept a PR to change this.

**Comment by lassombra** [comment]
This isn't a Meteor bug, it is standard browser behavior.

Contrary to appearances, it's not actually throwing a catchable error.  Try turning on break on errors in your inspector and it won't trigger.  The Meteor code is handling the error correctly, and is the only in-code way of knowing about the error.  No javascript can hide that from the console.

You can however [Turn it off](http://stackoverflow.com/a/34856429) in chrome.  YMMV with other browsers.  @stubailo I recommend closing this ticket as there is not an actual bug in this case.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/6215#issuecomment-183588424, this is standard browser behaviour. Closing - thanks @lassombra!
