### ISSUE TITLE
Windows 7: Sorry, this OS is not supported.

### ISSUE THREAD

**Issue by DavidAPowers** [meteor/meteor#6221]
Steps to replicate
1. Install Meteor from https://www.meteor.com/install
2. Add meteor.bat to PATH (C:\Users\<USER>\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32)
`> meteor`
`Sorry, this OS is not supported.`

**Comment by stubailo** [comment]
What shell are you using? CMD?

**Comment by DavidAPowers** [comment]
Windows 7 Ultimate, running ConEmu with GitBash giving me some (but not all) of the standard Linux Bash commands.

**Comment by stubailo** [comment]
The issue is that Meteor on Windows doesn't run in Git Bash: #4938 

Works on Windows in PowerShell and CMD just fine!

Closing as a duplicate.
