### ISSUE TITLE
[MiniMongo] $slice in $push must be zero or negative

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#6223]
I've noticed that there is an error in the MiniMongo package in the `LocalCollection._modify` method. It does not allow positive numbers in the `$slice` operator when used with the `$push` operator. https://github.com/meteor/meteor/blob/master/packages/minimongo/modify.js#L256

And if you read MongoDB documentation for this operator, you will see that it's valid value https://docs.mongodb.org/v3.0/reference/operator/update/slice/

- `0` - erase array
- `> 0` - leaves only N first elements
- `< 0` - leaves only N last elements

**Comment by jagi** [comment]
Oh I've noticed that is duplicate of #5167

**Comment by helfer** [comment]
Yeah, seems to be a duplicate, so I'll close it. Thanks for the reminder!
