### ISSUE TITLE
Is it possible to enable property transform in babel

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [meteor/meteor#6224]
**_1 Upvote**_ A lot of react examples are using property transforms which basically saves some coding when writing huge forms. Is it possible to enable the property transform by default.

**Comment by stubailo** [comment]
:+1: Encountered the same with React code samples.

**Comment by suhail-ansari-apconic** [comment]
Yeah that is becoming common place in react as we don't have to bind the callbacks when using es6.  Should this be on roadmap for 1.3.

**Comment by stubailo** [comment]
Leaving it up to @benjamn to decide what we do about this and when.

**Comment by jamiter** [comment]
At the moment this is the **only** thing blocked me from using [Flow](http://flowtype.org/) with Meteor. Flow demands that you define your class property types, but if you do, Meteor crashes. Flow doesn't have the option yet to disable this specific rule, so if Meteor would simply allow it, that would be awesome. 100% Flow support!

**Comment by hwillson** [comment]
Additional Babel transforms support was added in [Meteor 1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133), so this feature can now be enabled like:

**.babelrc**
```json
{
  "plugins": [
    "transform-class-properties"
  ]
}
```

Thanks for posting this feature request - closing.
