### ISSUE TITLE
[1.3-modules-beta.8] Meteor command line messages are invisible on Windows.

### ISSUE THREAD

**Issue by gbersani** [meteor/meteor#6226]
OS: Windows 10 x64

As of beta 8, many of the messages Meteor would output for updates (Client refreshing, Server restarting, etc) are no longer showing on the command line. The invisible messages still occupy the same amount of lines they would if they were there.

Using console.log and other logging tools still seem to work fine, so I'm ending up with things like this in my console:

```
=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.







I20160212-10:30:39.511(-5)? Hello?
```

**Comment by gbersani** [comment]
An update: What gets hidden or shown appears to be different every time the app first starts.

My console as of now:
```
=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.




















=> Client modified -- refreshing (x6)


=> Client modified -- refreshing
```

**Comment by ljack** [comment]
Noticing the same happening here. Thought it was something with my environment, but guess not.

**Comment by zol** [comment]
Is this still an issue with beta 11? Do we know whether every version of Windows is affected?

**Comment by gbersani** [comment]
I am no longer seeing the problem as of beta-11.
Gonna keep an eye on it and re-open the issue if the problem returns. :)
