### ISSUE TITLE
Unable to install meteor globally via npm

### ISSUE THREAD

**Issue by mimiflynn** [meteor/meteor#6228]
When attempting to run `npm install -g meteor'

Mac OS 10.10.5

Did a search for meteor installation issues with fibers but couldn't find anything. I was able to install on a different machine a week ago; could this be a new issue?

See below and attached log file.

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "meteor"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! fibers@0.6.9 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@0.6.9 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mimi.flynn/npm-debug.log
npm ERR! code 1
```

[npm-debug.log.txt](https://github.com/meteor/meteor/files/128729/npm-debug.log.txt)

**Comment by DevotionGeo** [comment]
I think its better to install using curl as suggested on the Meteor's official website.

**Comment by stubailo** [comment]
@mimiflynn we actually don't maintain that NPM package, that's someone else who probably repackaged it for NPM. Please install using the official installation instructions here: https://www.meteor.com/install

**Comment by amitesh786** [comment]
@DevotionGeo - you're absolutely right, but when you're using curl there was another issue 
"Only 64-bit Intel processors are supported at this time."

Then I prefer this - "export PATH=/usr/sbin:$PATH && curl https://install.meteor.com/ | sh"
It's works, but when you switch the terminal, then it doesn't, 

So I need to install global, I don't like to work-around ;(
If I use to add inside bash/profile then every time when you open terminal then it will do something like - "Removing your existing Meteor installation.
Downloading Meteor distribution "

So, if there is any solution feel free to share :)
