### ISSUE TITLE
Tail of array in a Collection is always being considered new item even if prepending

### ISSUE THREAD

**Issue by fegemo** [meteor/meteor#6230]
Suppose a `Mongo.Collection` called `Tutorials` that has a `comments` field, which is an array of objects (e.g., `author`, `content`, `date`), like so:
```json
[{
  "_id": "xjkjlxjlkjlxj",
  "comments": [{
    "author": "Flavio",
    "content": "http://....",
    "date": "2016-02-12T22:12:50.852Z"
  }]
},
{
  "_id": "kejwlkewlemlwkj",
  "comments": [{
    "author": "Elder",
    "content": "http://....",
    "date": "2016-02-12T11:12:50.852Z"
  }]
}]
```

I want to display the comments sorted by `-date`, so that more recent comments show up on top. Instead of calling `Tutorials.findOne` to get the comments array and `.reverse`ing it, my approach is to insert new comments by **prepending the `comments` array**. For that, I am using `$push` with the `$each` and `$position` modifiers:

```js
Tutorials.update(activeTutorial._id, {
  $push: {
    comments: {
      $each: [newComment],
      $position: 0
    }
  }
});
```

Insertion in the database is working as expected and the view is being properly updated as well.

However, I started using the [webtempest/meteor-animate ](https://github.com/webtempest/meteor-animate) package to provide transitions for inserted elements (it basically use Blaze's `ui-hooks`) so that new comments would fade-in when inserted.

It turned out that **although the new comment was added at the top (head)**, it was **the array item at the bottom (tail)** that was being transitioned in. At first I thought it was an issue with [webtempest/meteor-animate ](https://github.com/webtempest/meteor-animate), but I noticed that it was the `DiffSequence` package that was providing the meteor-animate package with the wrong array item.

It is the first time I'm looking into Meteor's source, but I believe that the issue might lie around `diff-sequence/diff.js:DiffSequence.diffQueryOrderedChanges` function and it might be happening only in this particular case of "changes in arrays inside Mongo.Collections" and not happening on "Mongo.Collections".

I'll try to put up a simple project to reproduce it.

Thanks for the great platform!!

**Comment by fegemo** [comment]
Please, consider this project to illustrate the scenario: [live](https://diff-sequence-issue.meteor.com/) and [source code](https://github.com/fegemo/meteor-diff-sequence-issue).

**Comment by stubailo** [comment]
@fegemo I think this is what you're looking for:

https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#reactivity-model-for-each

Blaze identifies which items are added and removed via an `_id` key. So if you just put a random ID on each comment, it should work properly.

**Comment by fegemo** [comment]
Genius ;) That fixed it indeed.
Thanks for the pointers and the instant response
