### ISSUE TITLE
Accounts.validateNewUser() should allow more than user.profile

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6231]
`Accounts.validateNewUser()` should allow more than `user.profile`.
If I pass an object like this to `Accounts.createUser()`
```
userData = {
  account: {
    type: 'free'
  },
  profile: {
    name: 'Artem',
  },
  username: 'aaa@gmail.com',
  password: '123'
};
```
`account.type` is not present in user object available to `Accounts.validateNewUser()`

**Comment by stubailo** [comment]
The default `onCreateUser` hook strips all of the fields except the ones it knows about, for security reasons so that your users can't store arbitrary data.

You should override the default hook by using this function: http://docs.meteor.com/#/full/accounts_oncreateuser

**Comment by avalanche1** [comment]
Yes, I tried to use it but then it has no means to abort new user creation if some user property doesn't pass validation.

**Comment by stubailo** [comment]
Yeah I think you need to use both.

**Comment by avalanche1** [comment]
That's a bummer. 
I use custom method which validates user object, then calls Accounts.createUser(), then adds non-standard properties to new user doc via Users.update().
