### ISSUE TITLE
Meteor reset necessary when using cordova facebook plugin

### ISSUE THREAD

**Issue by mscherer82** [meteor/meteor#6232]
When using the facebook plugin I got this message 
`AAPT: No resource found that matches the given name (at 'value' with value '@string/fb_app_id').`

I don't think this is related to the plugin because after `meteor reset` I'm able to run the app.

When I try to run it a second time I got the message

`.meteor\local\cordova-build\platforms\android\res\values\facebookconnect.xml" already exists!`

I deleted the file and got the first error message again. After `meteor reset` it worked again.

**Reproduce:**
install `heysailor:accounts-facebook-cordova`
add `App.setPreference('android-minSdkVersion' , 15); ` to your mobile-config.
launch `meteor run android-device ..

**Comment by martijnwalraven** [comment]
This seems like an issue either with `heysailor:accounts-facebook-cordova` or (more likely) the underlying `cordova-plugin-facebook4` it uses. So I don't think this is something we can fix in Meteor.

**Comment by rubenlpz** [comment]
@mscherer82 Did you find any solution for this, besides the workaround?
