### ISSUE TITLE
Align Blaze 2 with Web Components APIs

### ISSUE THREAD

**Issue by brylie** [meteor/meteor#6236]
It would be widely beneficial if Blaze 2 were to align with Web Components. This would, in effect, mean that components written in Blaze 2 could readily be included in other projects.

Please consider designing Blaze 2 APIs to correspond with the emerging Web Components standard.

**Comment by mitar** [comment]
There will be no Blaze 2.

But feel free to explain a bit more how would you align Blaze more with Web Components? What exactly do you have in mind? See also [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) which is a community project for Blaze 2.

**Comment by brylie** [comment]
Basically, we want to use, as closely as possible, the emerging [WebComponents standards](http://webcomponents.org/) while building new apps.

How closely does Blaze Components align with the WebComponents specs?

**Comment by stubailo** [comment]
> It would be widely beneficial if Blaze 2 were to align with Web Components.

Can you provide more information about why this would be widely beneficial right now? I don't see any evidence that Web Components are widely used compared to any other way of defining components in JavaScript, for example Angular 2, React, Ember, Vue.js, etc.

**Comment by brylie** [comment]
@stubailo part of the problem is that all of the mentioned platforms are developing their own component models, and community factions, rather than contributing to a common standard. The opportunity is to align with WebComponents standards, while fostering the development, so that standardized web components become more widespread. 

If Blaze 2 components were simply WebComponents, then they could might be used in projects despite any other framework concerns.

**Comment by stubailo** [comment]
I don't know if it's our place to try to encourage people to use web components. Perhaps we can revisit in the future once web components are a more widely adopted standard outside of specific implementations like Polymer.

**Comment by mitar** [comment]
Are there any issues with using web components with Meteor? I think those should be addressed, so that people who would like to use web components can use them. So maybe give input on tickets which are preventing one from using web components.

**Comment by stubailo** [comment]
Yes I agree that would be a good idea. But that is _definitely_ not relevant to this issue, which asks for adopting the Web Components API for a future release of Blaze.

**Comment by mitar** [comment]
Hm, not sure what you are saying here. I was agreeing with you and saying to @brylie that he should probably for now make sure Meteor supports using web components at all, and give feedback on relevant tickets.

**Comment by brylie** [comment]
There are several open issues where people are having difficulties using WebComponents with Meteor, referenced at the top of this thread.

Blaze/WebComponent API alignment would, at the least, make it easy for people to build re-usable, cross-framework components.

Thanks for your perspective @mitar and @stubailo.

**Comment by aruntk** [comment]
@brylie Use polymer as the default view layer using mwc:synthesis package.
https://forums.meteor.com/t/polymer-meteor-with-meteor-webcomponents-packages/20536

**Comment by brylie** [comment]
Thanks @aruntk :smiley:
