### ISSUE TITLE
[bug/outdated docs] collection.insert callback called with wrong parameters

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#6237]
collection.insert calls the callback with wrong parameters when insertion failed
issue occurs on both client and server side
issue doesn't not occur on local collection though

according to the meteor docs @ http://docs.meteor.com/#/full/insert

> On the server, if you don't provide a callback, then insert blocks until the database acknowledges the write, or throws an exception if something went wrong. If you do provide a callback, insert still returns the ID immediately. Once the insert completes (or fails), the callback is called with error and result arguments. ***In an error case, result is undefined***. If the insert is successful, error is undefined and result is the new document ID.

> On the client, insert never blocks. If you do not provide a callback and the insert fails on the server, then Meteor will log a warning to the console. If you provide a callback, Meteor will call that function with error and result arguments. ***In an error case, result is undefined***. If the insert is successful, error is undefined and result is the new document ID.

On a fresh meteor project
```
TTT = new Mongo.Collection('TEST');

TTT.insert({_id: 'TTT'}, (err, res)=>{
	console.log('111', err, res)  // insert once
})

let SSS = TTT.insert({_id: 'TTT'}, (err, res)=>{
	console.log('222', err, res)  
        // err is complaining about duplicate id, res is ***false*** instead of undefined
        // also SSS is 'TTT' instead of null
})

if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
```

problem doesn't occur for local collection
```
PPP = new Mongo.Collection(null);  // local collection

PPP.insert({_id: 'TTT'}, (err, res)=>{
	console.log('111', err, res)  // insert once
})

let UUU = PPP.insert({_id: 'TTT'}, (err, res)=>{
	console.log('222', err, res)  
        // res is undefined as expected
        // UUU is null
})
```

**Comment by helfer** [comment]
Thanks for pointing it out, that is indeed inconsistent. I don't consider it a major issue though, so we won't prioritize fixing it. Pull requests encouraged!

For anyone interested in submitting a pull request, I think the best way to go about this would be to figure out what response the node-mongodb-native fork we use returns. If it's false, then it should be false on the client as well. If it's undefined, then just pipe that through.
