### ISSUE TITLE
force-ssl generates error: "too many redirects"?

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6239]
When I add the **force-ssl package** to my Meteor project and analyze my page (www.hoardspot.com) with Google PageSpeed Insights I get an error message:

**"Fetching the page exceeded the maximum of 10 redirects."**

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.hoardspot.com%2F&hl=en

**Comment by zol** [comment]
This is most likely due to a conflict between `force-ssl` and your load balancer or proxy tier and not a bug.
