### ISSUE TITLE
Meteor exit with - Abort trap: 6

### ISSUE THREAD

**Issue by HedCET** [meteor/meteor#6241]
<img width="376" alt="untitled copy" src="https://cloud.githubusercontent.com/assets/1794209/13047099/cc6eda54-d402-11e5-8f0f-f7ad956132d3.png">

Using OS X El Capitan, Meteor-1.2.1

How i solve this ?

**Comment by helfer** [comment]
How frequently does this happen? Are you able to reliably trigger the bug? Also, can you tell us what packages you are using?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by NazarYablonskiy** [comment]
The same happened with me. The app is 'Mantra' with a WebPack. I had doing some things with a 'SimpleSchema' on the client. Yeah, that happened while reloading.

**Comment by thomasf1** [comment]
That regularly happens to me, particularly when the local server has been running for a while without load (maybe related to mac sleep?)

**Comment by derekclair** [comment]
I've had the `Abort trap: 6` a few times, and this time I went to see if it was documented, as I restarted the App I was returned the following: ```

=> Client modified -- refreshing
I20161115-10:02:26.535(-7)? Kadira: completed instrumenting the app
=> Meteor server restarted
I20161115-10:02:26.815(-7)? Kadira: Successfully connected
Abort trap: 6
Dereks-MacBook-Pro:roipgm-platform DerekClair$ meteor --settings settings.json
[[[[[ ~/Development/GitHub/roipgm-platform ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
/Users/DerekClair/.meteor/packages/coffeescript/.1.11.1_2.gv04sw++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/DerekClair/Development/GitHub/roipgm-platform/node_modules/npm/node_modules/mkdirp/test'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/DerekClair/.meteor/packages/meteor-tool/.1.4.2_1.49umjh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
Dereks-MacBook-Pro:roipgm-platform DerekClair$  meteor --settings settings.json
[[[[[ ~/Development/GitHub/roipgm-platform ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
/Users/DerekClair/.meteor/packages/coffeescript/.1.11.1_2.gv04sw++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/DerekClair/Development/GitHub/roipgm-platform/node_modules/npm/node_modules/readdir-scoped-modules/test/fixtures/@scope/y'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/DerekClair/.meteor/packages/meteor-tool/.1.4.2_1.49umjh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
Dereks-MacBook-Pro:roipgm-platform DerekClair$  meteor --settings settings.json
[[[[[ ~/Development/GitHub/roipgm-platform ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
/Users/DerekClair/.meteor/packages/coffeescript/.1.11.1_2.gv04sw++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/DerekClair/Development/GitHub/roipgm-platform/node_modules/npm/node_modules/readdir-scoped-modules/test/fixtures/a'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/DerekClair/.meteor/packages/meteor-tool/.1.4.2_1.49umjh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
Dereks-MacBook-Pro:roipgm-platform DerekClair$ 
```
I haven't been able to re-start yet, but I think it's worth mentioning, particularly because of the  inconsistency of the thrown error. (Though that might very well be my ignorance as well...) I'll try to follow-up.

Regarding the earlier discussion points, I've seen it mostly when my macOS 10.12.1 sleeps, but not every time. And, it's never had an issue re-starting like this instance.

**Comment by derekclair** [comment]
Here's the error with the `--verbose` flag:
```
Dereks-MacBook-Pro:roipgm-platform DerekClair$ meteor --settings settings.json --verbose
[[[[[ ~/Development/GitHub/roipgm-platform ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
Local package version is up-to-date: accounts-base@1.2.14
Local package version is up-to-date: accounts-password@1.3.2
Local package version is up-to-date: alanning:roles@1.2.15
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.0
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: apollo@0.1.2
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.13.0
Local package version is up-to-date: babel-runtime@0.1.12
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.1.9
Local package version is up-to-date: blaze-html-templates@1.0.5
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.0.11
Local package version is up-to-date: caching-compiler@1.1.8
Local package version is up-to-date: caching-html-compiler@1.0.7
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.4
Local package version is up-to-date: coffeescript@1.11.1_2
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.3.2
Local package version is up-to-date: ddp-common@1.2.7
Local package version is up-to-date: ddp-rate-limiter@1.0.6
Local package version is up-to-date: ddp-server@1.3.11
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: ecmascript@0.5.9
Local package version is up-to-date: ecmascript-runtime@0.3.15
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: email@1.1.18
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: force-ssl@1.0.13
Local package version is up-to-date: fourseven:scss@3.10.0
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.10
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.1.0
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.0.12
Local package version is up-to-date: logging@1.1.16
Local package version is up-to-date: mdg:geolocation@1.3.0
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.6.0
Local package version is up-to-date: meteor-base@1.0.4
Local package version is up-to-date: meteorhacks:kadira@2.30.2
Local package version is up-to-date: meteorhacks:meteorx@1.4.1
Local package version is up-to-date: minifier-css@1.2.15
Local package version is up-to-date: minifier-js@1.2.15
Local package version is up-to-date: minimongo@1.0.18
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.13
Local package version is up-to-date: modules@0.7.7
Local package version is up-to-date: modules-runtime@0.7.7
Local package version is up-to-date: mongo@1.1.14
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: mongo-livedata@1.0.12
Local package version is up-to-date: npm-bcrypt@0.9.2
Local package version is up-to-date: npm-mongo@2.2.11_2
Local package version is up-to-date: observe-sequence@1.0.14
Local package version is up-to-date: okgrow:analytics@2.0.0
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: promise@0.8.8
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.6
Local package version is up-to-date: react-meteor-data@0.2.9
Local package version is up-to-date: reactive-dict@1.1.8
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: seba:minifiers-autoprefixer@1.0.1
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.2.1
Local package version is up-to-date: softwarerero:accounts-t9n@1.3.5
Local package version is up-to-date: spacebars@1.0.13
Local package version is up-to-date: spacebars-compiler@1.0.13
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-js@1.2.1
Local package version is up-to-date: std:accounts-basic@1.1.12
Local package version is up-to-date: std:accounts-ui@1.2.6
Local package version is up-to-date: templating@1.2.15
Local package version is up-to-date: templating-compiler@1.2.15
Local package version is up-to-date: templating-runtime@1.2.15
Local package version is up-to-date: templating-tools@1.0.5
Local package version is up-to-date: tmeasday:check-npm-versions@0.3.1
Local package version is up-to-date: tracker@1.1.1
Local package version is up-to-date: ui@1.0.12
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.0.11
Local package version is up-to-date: webapp@1.3.12
Local package version is up-to-date: webapp-hashing@1.0.9
/Users/DerekClair/.meteor/packages/coffeescript/.1.11.1_2.gv04sw++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/DerekClair/Development/GitHub/roipgm-platform/node_modules/npm/node_modules/readdir-scoped-modules/test/fixtures/a/x'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/DerekClair/.meteor/packages/meteor-tool/.1.4.2_1.49umjh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by abernix** [comment]
@derekclair Thanks for the additional information.  Please see #8057 for a possible solution to your problem!

**Comment by t3db0t** [comment]
I just got this error for the first time—is it definitely caused by the `maxfiles` limit?

**Comment by abernix** [comment]
@t3db0t Not necessarily.  Please see #8002 to see if it sounds similar to your problem.  If it doesn't, please open a new issue with a reproduction as this issue is closed.

**Comment by rijk** [comment]
I frequently experience this error. Basically every time my Mac goes to sleep.

**Comment by abernix** [comment]
@rijk What version of Meteor? / Are you still experiencing this after updating applications to Meteor 1.5.2.2?

**Comment by rijk** [comment]
@abernix Yes I'm on the latest (1.5.2.2). I experience this issue in two different projects.

**Comment by rijk** [comment]
I still get this issue fairly frequently. Even in the latest Dr. Mongo — so it's not my code or anything.

Some details to try and reproduce: I am running [Dr. Mongo](https://github.com/DrMongo/DrMongo) on a Mac, OSX 10.13.1. The app is running in Chrome, 62.0.3202.75 (but I don't think that matters). The issue seems to only occur when the macbook goes to sleep (not closing the lid but letting it inactive for a while).

Let me know if there is anything I can do to help debug the issue!

**Comment by Firfi** [comment]
I get the same issue frequently. It's good it's not important, we can just restart our servers. We have time for that.
