### ISSUE TITLE
database is not accessible in android device?

### ISSUE THREAD

**Issue by vithanidarpan** [meteor/meteor#6248]
Currently my meteor application is working absolutely fine in browser and also in android emulator.

But my problem is that when I install that apk in android device then database related operations are not working. For example registration and login is not working in android device and Also other features of my project which requires database related operations.

Also if someone can explain use of root_url in meteor application then it would be very helpful.what will be root url to run android application in android device?

**Comment by martijnwalraven** [comment]
Is your app able to connect to the server? The `ROOT_URL` specifies the address of the server, which is used both for data loading and hot code push.

**Comment by ramirez530** [comment]
Root url

ramirez$14$

**Comment by martijnwalraven** [comment]
I think something may have gone wrong with your response.

**Comment by vithanidarpan** [comment]
I have some issue connecting android device in android.
So here are steps what I have done to run application in device.
1. run application on my ip address using command : meteor --port 192.168.1.107:3000 --verbose
2. then I build android application in new terminal using this command :  meteor build ~/home/abc --server http://192.168.1.107:3000
3. copied apk from output directory in mobile and installed in mobile.
4. run application and watched log in chrome console but not found any error in console. I am attaching screenshot of console output.

![screenshot from 2016-02-17 10 21 45](https://cloud.githubusercontent.com/assets/16571528/13100296/9e00a0c0-d561-11e5-81d5-d45d67cd36aa.png)

so please help me what to do now.

**Comment by vithanidarpan** [comment]
thank you guys for your response.
I've connected android device and after running android application using meteor run android-device --port 192.168.1.1:3000 it ran successfully on device.
Now its working fine.
But I don't know still why it was not working when I was installing app after building application.
Anyway issue is resolved now.
