### ISSUE TITLE
Cannot update package on Atmosphere

### ISSUE THREAD

**Issue by Hongbo-Miao** [meteor/meteor#6250]
I have a [package](https://atmospherejs.com/hongbomiao/ng2-bootstrap) on Atmosphere, but now I cannot update it.

If I use `meteor publish --update`, it says

> You can't call `meteor publish --update` on version XX of package 'hongbomiao:ng2-bootstrap' without publishing it first.

However, if I use `meteor publish --create`, then it shows:

> Package already exists. To create a new version of an existing package, do not use the --create flag!

Please help me delete it, so I can create again. Thanks!

![screenshot](https://cloud.githubusercontent.com/assets/3375461/13081084/6cef5d3c-d499-11e5-9ff3-8dbaa4e21805.png)

**Comment by helfer** [comment]
It looks like you're trying to publish a new version of your package, is that right? In that case you should just use `meteor publish` without the `--update`. `--update` is for changing the readme or description of the package, not to publish a new version.
