### ISSUE TITLE
[1.3-modules-beta.8] No version of autoupdate satisfies all constraints: @=1.2.4, @=1.2.5-modules.8

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#6252]
`meteor update --release 1.3-modules-beta.8 `

I was trying to see if Rocket.Chat would run under 1.3 and got the following error. 
not sure if this is expected at this point ...

```
➜  Rocket.Chat git:(develop) ✗ meteor
[[[[[ ~/dev/rnd/Rocket.Chat ]]]]]             

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of autoupdate satisfies all constraints: @=1.2.4, @=1.2.5-modules.8
   Constraints on package "autoupdate":
   * autoupdate@=1.2.4 <- top level
   * autoupdate@=1.2.5-modules.8 <- top level
   * autoupdate@1.2.5-modules.8 <- hot-code-push 1.0.1-modules.8 <- meteor-base 1.0.1
   
=> Your application has errors. Waiting for file change.
```

**Comment by abernix** [comment]
This is a pretty simple version constraint issue (various packages having incompatible versions).  I'm sure the Rocket.Chat team will address this in their upgrade to 1.3.  The simple answer is: Rocket.Chat currently only supports 1.2.1.  Closing this as it's an issue with Rocket.Chat, not Meteor.

**Comment by vikas0121** [comment]
Facing same issue..is there any solution?

=> Errors while initializing project:         
                                              
While selecting package versions:
error: No version of autoupdate satisfies all constraints: @=1.2.11, @1.3.12
Constraints on package "autoupdate":
* autoupdate@=1.2.11 <- top level
* autoupdate@1.3.12 <- top level
* autoupdate@1.2.8 <- hot-code-push 1.0.4 <- meteor-base 1.0.4
