### ISSUE TITLE
MongoDB Issue with Compose.io MongoDB+

### ISSUE THREAD

**Issue by guns2410** [meteor/meteor#6258]
When recently upgraded by MongoDB+ (MongoDB version 3.2) with Compose.io after having MongoDB Classic deployment (MongoDB version 3.0), i noticed that they did not offer ReplicaSet for the new deployment.

There is no replica set for the deployment and it is a sharded deployment that's fronted by a `mongos` router.

Every deployment had 2 mongos router. With meteor we can only use one mongos router since meteor will treat a MONGO_URL putting two mongos router seperated by a comma as a replicaSet and we get an error which says MongoError: not master.

So we only put one router in MONGO_URL.

now the Problem:

I hosted my applications on Galaxy Developer's edition.
If one mongos router failed, the application stops and does not process Observers again.

So, we need to create some simple testing logic within the application to see if the host is up and if not move to the next ingress point which i think currently is not supported by Meteor.

Please correct me if I am wrong. What could be a workaround.

**Comment by benjamn** [comment]
@pcarrier feel free to triage this to someone else if you're not the best person to look at it

**Comment by guns2410** [comment]
Found the route cause of the issue. 

The cause is when using MongoDB 3.2 with compose, they do not give replica set but gives a mongos router configuration which has two mongos routers. Since with meteor we can only have one mongos router in MONGO_URL, the application could not handle the failing of the router.

Additionally, we should have an option putting failover MONGO_URL or implement a smarter way to detect if the URL provided is a replica set or mongos router url.

I will dig into the MONGO library of Meteor and see if I can add anything there.

Thanks!

**Comment by benjamn** [comment]
Here's a forum post about a similar use case (deliberately changing the database, not necessarily due to failure): https://forums.meteor.com/t/switch-database-while-meteor-is-running/4361

To the best of my knowledge, this feature is not currently supported. While it might be possible to trigger a server restart that picks up a new `MONGO_URL`, I definitely agree that supporting failover would be a useful feature for the framework to support.

**Comment by Latnok** [comment]
may be same problem? #5773

**Comment by abernix** [comment]
Closing as Meteor 1.4, which uses the updated version of the Node Mongo driver, supports this if the app is using a correct `MONGO_URL` and their Mongo server is properly configured.  See #7450, #7492 and other related issues for more information.
