### ISSUE TITLE
Pull Request & Issue Templates

### ISSUE THREAD

**Issue by rgoomar** [meteor/meteor#6259]
GitHub just added new features for templates. I think this would help with clutter on issues and make sure pull requests have the proper information for you guys to review. It can help give new contributors an idea of what information you want to easily review the PR and/or issue. 

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by stubailo** [comment]
Yes we are all very excited about this! Hopefully we can write up some templates asap. Got any ideas for what should go in there?

**Comment by ecwyne** [comment]
https://github.com/devspace/awesome-github-templates

**Comment by martijnwalraven** [comment]
I added a first version of the issue and pull request templates: https://github.com/meteor/meteor/commit/7ad51b7418661a7fd7c8e08ce7b585e42c1b50e1

Let's discuss here whether we think this is a good idea and what we may want to change about them. One downside of the way these templates are used is that what you actually see is the Markdown source, not the formatted version. So this makes it hard to see structure and follow links.

**Comment by rgoomar** [comment]
@martijnwalraven I would say that you could change this line to mention creating a repository for the reproduction like such:
```
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code related to issue that anyone can clone down and see the behavior)
```

Just some way to make it more clear how they can represent that reproduction. That way, it isn't people putting large amounts of code into an issue.

**Comment by rgoomar** [comment]
Besides that, I really like the templates put in place. It is a bummer that it doesn't render the markdown.

**Comment by zol** [comment]
Thanks for the suggestion @rgoomar - I've updated the template accordingly.
