### ISSUE TITLE
Auto publish or link packages from github

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6261]
Many packages on atmosphere are months behind their GitHub version. Most of the times this is not by intention but the devs simply forget to publish to Atmosphere.
For the most important updates I remind them with a GitHub issue but it is a real pain.

Are there any ideas to remind devs / auto publish / link directly to GitHub?

**Comment by laosb** [comment]
Aha sounds we can have a webhook for package authors, and automatically publish their package updates.

**Comment by sakulstra** [comment]
Actually you can do this pretty simple, by using some ci(like circle-ci) to publish the package.
sth like this: 
```sh
deployment:
  production:
    branch: "master"
    commands:
      - printf "${name}\n${password}\n" | meteor login --email
      - meteor publish
```
should do the trick.

**Comment by tmeasday** [comment]
Hey @sakulstra - thanks for this! We'll mention this in the "publishing packages" guide article (which is just an outline at the moment: https://github.com/meteor/guide/blob/master/outlines/publish-packages.md).

**Comment by sakulstra** [comment]
np, actually I think it would be better to have this bundled inside the guide instead of a link... so feel free to simply copy paste my text, or ping me and I'll do a pr
