### ISSUE TITLE
Additional helpers for compiler plugins

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#6262]
In https://github.com/Urigo/angular2-meteor/issues/96#issuecomment-180320663 the issue was raised if the utils from this file https://github.com/Urigo/angular2-meteor/blob/952a01591a4e8fb13d068345dde03a7cf21745ed/atmosphere-packages/angular2-html-templates/utils/file_mixin.js would make sense to have in Meteor core.

Having made a couple of compiler plugins I think this would be a quick and useful addition.
If people from MDG agree, I can make a PR for this.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Additional%20helpers%20for%20compiler%20plugins&body=Migrated%20from:%20meteor/meteor%236262) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
