### ISSUE TITLE
`meteor update` and `meteor remove` saying conflicting things

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#6264]
Hi, I'm trying to update packages in my app.  Meteor update and meteor remove are telling me conflicting information:

```
☀  meteor update                                                                
This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
Newer versions of the following indirect dependencies are available:
 * kevohagan:sweetalert 0.5.0 (1.0.0 is available)
 * mdg:validation-error 0.2.0 (0.4.0 is available)
 * momentjs:moment 2.10.6 (2.11.2 is available)
 * softwarerero:accounts-t9n 1.1.7 (1.2.2 is available)
To update one or more of these packages, pass their names to `meteor update`.

☀  meteor remove kevohagan:sweetalert                                           
kevohagan:sweetalert is not in this project.  
```
`meteor list | grep sweet` returns no lines.

**Comment by kamilkisiela** [comment]
@MichaelJCole `kevohagan:sweetalert` is in your app but as a dependency of the top-level package.

> Newer versions of the following **indirect** dependencies are available:

So you cannot remove it from your app directly.

**Comment by MichaelJCole** [comment]
That would make this output a lie:

> kevohagan:sweetalert is not in this project.

**Comment by kamilkisiela** [comment]
Depends how you look on it.

It's true that you cannot remove it, but yes, the message is not so accurate.

**Comment by laosb** [comment]
True, we may say:

> kevohagan:sweetalert is not a direct dependency of this project.

Better we can show the package who used it at the same time.
