### ISSUE TITLE
Unexpected spaces between characters in Email with Chinese characters.

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#6267]
## Reproduction
1. create a new app;
2. add `accounts-base` ,`accounts-password`, `accounts-ui`, and put `{{> loginButtons}}` somewhere;
3. configure SMTP and add code below to server side:

```
Accounts.emailTemplates.from = 'xxx';
Accounts.emailTemplates.siteName = '中国科学出版社平台';
```
1. run the app, register and login, try `Accounts.sendVerificationEmail(my_id);` on `meteor shell`
2. The email subject looks like this, with extra spaces circled red.
   ![image](https://cloud.githubusercontent.com/assets/2545261/13170550/c86a8e80-d727-11e5-8e36-fc10ffd46e61.png)
## Notice
1. It's not a problem with a special Chinese string or characters, many members in Meteor China have suffered this with all sorts of Chinese string.
2. Haven't tested if Japanese or so also have this problem.
3. Not the bug of mail clients.

**Comment by benjamn** [comment]
This definitely sounds like a bug, and we'll look into it as soon as we can. In the meantime, please do let us know if you discover any additional information that might explain the spaces.

**Comment by QuoniamYIF** [comment]
my code is:
```
Accounts.emailTemplates.resetPassword.from = function () {
			// Overrides value set in Accounts.emailTemplates.from when resetting passwords
			return "密码重置 <no-reply@example.com>";
		};
		Accounts.emailTemplates.resetPassword.subject = function () {
			// Overrides value set in Accounts.emailTemplates.from when resetting passwords
			return "来自SendCloud的第一封邮件！";
		};
		Accounts.emailTemplates.resetPassword.text = function () {
			// Overrides value set in Accounts.emailTemplates.from when resetting passwords
			return "你太棒了！你已成功的从SendCloud发送了一封测试邮件，接下来快登录前台去完善账户信息吧！";
		};
```
but why result is:
```
I20160620-11:10:54.572(8)? Subject: =?UTF-8?Q?=E6=9D=A5=E8=87=AASendCloud=E7=9A=84?=
I20160620-11:10:54.572(8)?         =?UTF-8?Q?=E7=AC=AC=E4=B8=80=E5=B0=81=E9=82=AE?=
I20160620-11:10:54.572(8)?         =?UTF-8?Q?=E4=BB=B6=EF=BC=81?=
I20160620-11:10:54.572(8)? Content-Type: text/plain; charset=utf-8
I20160620-11:10:54.572(8)? Content-Transfer-Encoding: quoted-printable
I20160620-11:10:54.573(8)? 
I20160620-11:10:54.580(8)? =E4=BD=A0=E5=A4=AA=E6=A3=92=E4=BA=86=EF=BC=81=E4=BD=A0=E5=B7=B2=E6=88=90=E5=8A=9F=E7=9A=84=E4=BB=8ESendCloud=E5=8F=91=E9=80=81=E4=BA=86=E4=B8=80=E5=B0=81=E6=B5=8B=E8=AF=95=E9=82=AE=E4=BB=B6=EF=BC=8C=E6=8E=A5=E4=B8=8B=E6=9D=A5=E5=BF=AB=E7=99=BB=E5=BD=95=E5=89=8D=E5=8F=B0=E5=8E=BB=E5=AE=8C=E5=96=84=E8=B4=A6=E6=88=B7=E4=BF=A1=E6=81=AF=E5=90=A7=EF=BC=81
```

**Comment by laosb** [comment]
Strange, this haven't happened in my app since 1.4 and there's no further similar reports in MeteorChina. Closing this but if anyone hit this, please reply below and I'll reopen.
