### ISSUE TITLE
Incremental Hot Code Push

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6269]
Reduce traffic by only transmitting the code diff.

**Comment by martijnwalraven** [comment]
If you're talking about only downloading changed files on mobile hot code push, that has actually been implemented in Meteor 1.3. A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

**Comment by obiwarn** [comment]
Great. Wouldn't that make sense for all HCP (not only mobile)?

**Comment by martijnwalraven** [comment]
On normal browsers, a hot code push is just a page reload, so normal HTTP caching is used. We did make some improvements to this in Meteor 1.3 that may make things faster there as well.
