### ISSUE TITLE
Facebook login on android with not working with new 1.3 beta release

### ISSUE THREAD

**Issue by itaibs** [meteor/meteor#6272]
I can't sign in using facebook login (only on android, on chrome it works). I'm getting stuck on the facebook login page after entering username and password with a js exception:
Uncaught SyntaxError: Unexpected token _

Exactly same code as before the update. The update to the new beta version is the only difference.

**Comment by itaibs** [comment]
OK. Sorry about this but this is happening to me now also on the stable version. I'm guessing it's another change or update I made which is unrelated to this. Investigating further.

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this, so I'm hoping you can provide a little more detail.

How are you signing in to Facebook? Is this using `accounts-facebook`? How has the service been configured? Any more error messages or more detail (stack trace, etc.)?

**Comment by itaibs** [comment]
Sorry for the wait, was on vacation and didn't get to work.

It might have been just my mistake. I'm guessing that if this was an actual issue someone else would have also reported this by now...

**Comment by hwillson** [comment]
Closing as this issue couldn't be reproduced. Thanks!
