### ISSUE TITLE
Can't install new atmosphere package

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#6274]
Hi,
I'm using Meteor 1.2.1. I can't add [atmosphere](https://atmospherejs.com) package from two days ago until now.
I can add package that later add in other project for example I used simple-schema before and now I can add this successfully without any issue.
I test from two different internet connection and two different laptop but I got this error on console: (for example for [tabular package](https://atmospherejs.com/aldeed/tabular))
```
 => Errors while adding packages:             
                                              
While downloading aldeed:tabular@1.6.0...:
error: socket hang up
```

I also test using proxy, based on [this page guide](https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy) but nothing different.

Is it a bug or atmosphere issue or other things?
I test many things in this two days. :cry:

**Comment by zol** [comment]
I can't reproduce this. Works for me:

```
$ meteor create test
Created a new Meteor app in 'test'.           

To run your new app:                          
  cd test                                     
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
Zoltans-MacBook-Pro:tmp zol$ cd test
Zoltans-MacBook-Pro:test zol$ meteor add aldeed:tabular
                                                                                   
Changes to your project's package version selections:
                                              
aldeed:tabular  added, version 1.6.0          

                                              
aldeed:tabular: Datatables for large or small datasets in Meteor
Zoltans-MacBook-Pro:test zol$                 
```

**Comment by cyclops24** [comment]
@zol so I guess maybe it's ISP issue for example for SSL. Is it possible to strict-ssl false for meteor like npm??
