### ISSUE TITLE
Message: This project uses Meteor 1.3-beta.11, which isn't available on Windows

### ISSUE THREAD

**Issue by CoveTechnologyAus** [meteor/meteor#6275]
Hi

I have just tried to update a project to 1.3-beta.11 on windows and have received the following message:

```
This project uses Meteor 1.3-beta.11, which isn't available on Windows. To work with this app on all supported platforms, use meteor update --release METEOR@1.2.1 to pin this app to the newest Windows-compatible release.
```

I had successfully updated to 1.3-modules-beta.8 previously and have been working in that fine on Windows.
Are there issues with the windows version of beta.11 or are you not supporting Windows in this round?

Thanks guys.

**Comment by benjamn** [comment]
@martijnwalraven any ideas?

**Comment by d62remi** [comment]
Same issue !

**Comment by lyquocnam** [comment]
`meteor update --release 1.3-beta.11`
it work for me on Windows 10

**Comment by martijnwalraven** [comment]
Just tried it on Windows 7, and that also worked.

@benjamn: Could this have anything to do with the package server issues?

**Comment by Rhywden** [comment]
It definitely has something to do with the server issues. My desktop was updated fine yesterday afternoon (successfully) and in the night I tried to update my (new) laptop.

That updating process dragged out endlessly without error messages.

I then created a new project and tried to update that one to see if it was my existing project. I then almost immediately got "isn't available on Windows". When I then tried to update my existing project again, I **also** got this message where previously the updating process at least began.

**Comment by Rhywden** [comment]
Okay, the problem has just become more serious. Remember how I said that after getting the "not available" message for **one** project I then also got it for the **other**?

Well, I just deleted the folders to start again from scratch and cloned the existing beta.8 project from Github.

Now I'm getting this:

```
c:\Users\abc\Documents\Github\projectname> meteor
This project uses Meteor 1.3-modules-beta. which isn't available on Windows.
```

**Comment by Rhywden** [comment]
Aaaand of course, uninstalling and then reinstalling Meteor also does not work because the installer will now hang. Another victim of the package server issues, it seems.

**Comment by JasonWeise** [comment]
Update.. I was able to update to beta.11 today on windows and was working with the project fine all day, now two hours later when going back to the project and running ``` meteor ``` in my project directory to run my project I am receiving the original error again.

How is this possible when I already upgraded to beta.11 and it was working? I must say I am very confused.

**Comment by Rhywden** [comment]
It's nice to know that, in case of such server issues, we get **no** infos about server issues whatsoever.

**Comment by JasonWeise** [comment]
More than anything I am confused why it would be having a server issue if the project had already been updated. When we execute ``` meteor ``` does it do a check on the server every time?

If it does I can see real problems, if the remote server is down we cannot work. I could be completely missing the mark but it is both bothering me and confusing me.

**Comment by Rhywden** [comment]
I'm also bothered by the 2nd issue - that getting the "not available on Windows" message for one beta-version also destroys the already existing and working earlier beta-version.

**Comment by martijnwalraven** [comment]
@Rhywden @JasonWeise: I'm just as confused as you are. The package server itself is running fine, but there seems to be an issue with syncing that somehow only affects Windows users, and only intermittently. We fixed some other issues last week, and I suspect that may have something to do with it.

**Comment by Rhywden** [comment]
Is there some kind of logging tool we could activate?

**Comment by martijnwalraven** [comment]
@Rhywden: You can activate debug logging by setting the `METEOR_LOG` environment variable to `debug`. Not sure how to do that on Windows, but in a Bash shell you would do:
`METEOR_LOG=debug meteor run`

**Comment by Rhywden** [comment]
You can do that by using Powershell:

```
$env:METEOR_LOG = "debug"
meteor run
```

**Comment by sebakerckhof** [comment]
@Rhywden , if you rename `%appdata%\Local\.meteor\package-metadata\v2.0.1\packages.data.db` and remove `packages.data.db-shm` and `packages.data.db-wal`) to something else and then create a new meteor project using `meteor create`, it should resync the entire database. Does that solve the problem?

**Comment by Rhywden** [comment]
Had to reset my installation of Windows in the mean time (the Insider preview will do that to you from time to time), so the issue has been solved through that means.

Thus I can't really follow those instructions anymore.

**Comment by sebakerckhof** [comment]
Okay, well, then it's also pretty safe to say resetting the package database would solve this. This actually happens anyway every now and then when a package gets removed.

**Comment by abernix** [comment]
Closing as I think this is isolated.  The instructions above should help but that re-sync might be _really, really_ slow after deleting the entire `package.data.db`.  It may be better/faster to just reinstall using the installer.
