### ISSUE TITLE
"Error: Method not found [404]" isn't helpful.

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#6277]
***1 Upvote*** I'm getting an error like

```
W20160219-23:25:16.646(-8)? (STDERR) Error: Method not found [404]
W20160219-23:25:16.646(-8)? (STDERR)     at [object Object]._.extend.apply (livedata_server.js:1583:19)
W20160219-23:25:16.646(-8)? (STDERR)     at [object Object]._.extend.call (livedata_server.js:1553:17)
W20160219-23:25:16.647(-8)? (STDERR)     at server/initialize/initialize.locations.js:15:1
W20160219-23:25:16.647(-8)? (STDERR)     at /home/nowgoin/src/nowgoin/webapp/.meteor/local/build/programs/server/boot.js:249:5
```

presumably because I'm using `Meteor.call` to call a methods that doesn't exist (or wasn't defined yet). It'd be helpful if the error would show actual line numbers pointing to the actual source code (not the build files) and if the error would tell us the name of the method we are trying to call. That'd make it easier to find the problem.

**Comment by trusktr-goin** [comment]
I spoke too soon, it does show the line of the actual source: `server/initialize/initialize.locations.js:15:1`. It'd still be nice to show the method name in the error output.

For example, `Error: Method not found ("someMethod")` instead of `Error: Method not found [404]`.

**Comment by tmeasday** [comment]
I think we'd take a PR that does this.

**Comment by trusktr-goin** [comment]
@tmeasday https://github.com/meteor/meteor/pull/6320

**Comment by lnmunhoz** [comment]
+1

**Comment by laosb** [comment]
Why still open? Closing as the pr was merged.

**Comment by abernix** [comment]
Feel free to test this in first 1.3.3 beta – `meteor --release 1.3.3-beta.0 ` and report back if it doesn't work for you!
