### ISSUE TITLE
Blaze renders self-closing tags with attributes with / at the wrong place

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6278]
If there is in Blaze template such string:

```
<input foo={{foo}}/>
```

This is rendered as:

```
<input foo="/">
```

Instead of:

```
<input foo="">
```

Or:

```
<input>
```

I [see in the code some special handling](https://github.com/meteor/meteor/blob/devel/packages/html-tools/parse.js#L156) for non-self-closing tags of this situation. But for self-closing tags there is no special handling.

Inserting space solves the problem:

```
<input foo={{foo}} />
```

**Comment by zol** [comment]
Hey @mitar . In the last day or two we've gone ahead and moved Blaze out into it's own repository. It's still early days as we haven't quite figured out our updated build process and how you can release independent package versions. Can I ask that you please re-open this issue in the new Blaze repository located at https://github.com/meteor/blaze . Thanks!
