### ISSUE TITLE
Add support for new iOS security declarations in mobile-config.js / App.accessRule

### ISSUE THREAD

**Issue by jmanos3** [meteor/meteor#6280]
For mobile configuration, the App.accessRule functionality needs to enhanced to support the new whitelisting directions for iOS.

According to Cordova whitelisting guide:

> iOS Whitelisting
> The allow-intent and allow-navigation tags are new for cordova-ios 4.x and greater, see the cordova-plugin-whitelist documentation for details. cordova-ios version 4.0 and greater does not require the cordova-plugin-whitelist plugin to be installed.
> 

It is my understanding that App.accessRule in mobile-config.js transforms into <access origin> in the config.xml.  One possible option would be to add both <access origin> and <allow-navigation> declarations for a single App.accessRule statement.

I have a Meteor app that utilizes the Braintree drop-in UI plugin for payment processing. The drop-in UI uses an iFrame.

In Meteor 1.2.1, all works fine for.  However, I just tested the app with Meteor 1.3 beta 11 and found that without adding the allow-navigation directive manually to the config.xml of the cordova project, the Braintree drop-in UI would not function properly on iOS. It does work properly on Android.

**Comment by skirunman** [comment]
Hi @martijnwalraven. We can not get the right syntax to work in mobile-config.js. We have a mobile app that uses a custom oauth we wrote for salesforce.com that was working great on our Cordova mobile app with Meteor 1.1.x and 1.2.x. With 1.3-x we can not access the salesforce oauth servers. I tried a bunch combinations. We need a wildcard for all salesforce.com subdomains. I thought this syntax should work as per Cordova whitelist documentation:
```
App.accessRule('https://*.salesforce.com', {
  'minimum-tls-version': 'TLSv1.0',
  'requires-forward-secrecy': false,
});
```
but also tried `https://*.salesforce.com/*`, `*.salesforce.com`, and `*.salesforce.*`, but in all cases getting errors `CFNetwork SSLHandshake failed (-9824)` and `NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)`.

This happens on both IOS simulator and IOS device with either local server or running on a remote staging server. In all cases we are building for development purposes. 

I also know there was another change to make force_ssl only be included in production. Our oauth requires SSL for authentication even in development so hoping this is not a contributing issue. 

Can you point me to the docs on the exact syntax for this?

Thanks!

**Comment by martijnwalraven** [comment]
@skirunman: Are you on `1.3-rc.6` or higher? Support for those attributes was only added in https://github.com/meteor/meteor/issues/6554.

**Comment by skirunman** [comment]
1.3-rc.9

**Comment by martijnwalraven** [comment]
Could you try running `nscurl --ats-diagnostics --verbose https://<subdomain>.salesforce.com` with the subdomain you are trying to connect to? I tried this with `login.salesforce.com` and that succeeded with the forward secrecy requirement disabled.

**Comment by skirunman** [comment]
I was able to get this to "work" after much testing. A combination of things probably made this hard including Xcode caching, app token caching, and wonky behavior of Salesforce. I did need to add another domain, but this syntax seems to be correct. Still need to do further testing.
```
// Allow access to Salesforce OAuth servers
App.accessRule('https://*.salesforce.com', {
  'minimum-tls-version': 'TLSv1.0',
  'requires-forward-secrecy': false,
});
App.accessRule('https://*.force.com', {
  'minimum-tls-version': 'TLSv1.0',
  'requires-forward-secrecy': false,
});
```
