### ISSUE TITLE
Large file count in public folder stops meteor from serving/refreshing the app

### ISSUE THREAD

**Issue by ohmycode** [meteor/meteor#6282]
Hello devs@meteor!

First of all: great Job! I got so excited about meteor that I started coding again during my self proclaimed time-out :)

I was fiddeling around and I ran into an issue with the meteor CLI while having a large asset collection in the public folder (around 500Mb and > 10000 files). When I start the app in the terminal with the `meteor` command, the build succeeds but the processing indicator keeps spinning forever (or at least more than 5 minutes).

![screen shot 2016-02-21 at 13 04 59](https://cloud.githubusercontent.com/assets/765267/13202715/485296ae-d89c-11e5-9071-e9a46c6f9202.png)

Sometimes I'm still able to open the app in the browser, sometimes I get a lot of 503 errors. The filewatching stops working completely.

I don't know how the public folder is behaving in meteor, but coming from an apache world I would expect some kind of symlinking the files inside, in a way that it makes no difference how many or how big they are so that the filesystem enforces those limits or responsiveness. Does that make sense? 
If that's not possible, at least in the [docs](http://docs.meteor.com/#/full/structuringyourapp) should be given some kind of hint.

Also it would have been nice to see what meteor is actually doing while spinning. It took me quite a while to figure out what was happening as neihter `meteor --verbose` nor `meteor debug`  were giving me any insights.

Thank you for this great project! :metal:

P.D.:
Meteor v1.2.1
node v0.10.41

**Comment by martijnwalraven** [comment]
I suspect the issue here is that Meteor computes the MD5 hash for every file, including the ones in `public/`. So with large asset collection that might take a while or even overload the file watching implementation. In general, I think the recommendation is to only use `public/` for assets that are used as part of your app, not for content. You should probably move these to S3 or another external service.

**Comment by benjamn** [comment]
Would #6002 help in this case?

**Comment by stomybexy** [comment]
[This](https://atmospherejs.com/jonatan/static-folder) package may help. It allows to serve static files from a folder outside your meteor project folder during dev.

**Comment by abernix** [comment]
@benjamn This seems to be happening with users with large NPM dependency trees too – see #6952 (and several related within).  I guess #6002 would fix some of their problems (`public/` stuff), but this seems like the same problem and I think this can be closed in favor of #6952.

**Comment by ohmycode** [comment]
Thank you for the suggestions. In my case #6002 would work, but as @abernix said, let's follow this on #6952.

**Comment by abernix** [comment]
@ohmycode, sounds good.  Do you also get file descriptor errors if you Ctrl-C?

**Comment by ohmycode** [comment]
Hey @abernix. It's been a while and this happened while playing around with some test code, I deleted that project so I can't reproduce it anymore and I don't remember the error output after sending a SIGINT, I'm sorry.
