### ISSUE TITLE
Check whether non-supported platforms are indeed skipped during build

### ISSUE THREAD

**Issue by pronan** [meteor/meteor#6283]
ubuntu 14.04 LTS

commands:

`meteor create --exmaple todos`
`cd todos`
`meteor build /root/deploy --server http://wdksw.com:3000`

error message:
`Currently, it is only possible to build iOS apps on an OS X system.`
`Killed`

sometimes even different messages with exactly same build:
`Currently, it is only possible to build iOS apps on an OS X system.`
`Killedking`

**Comment by pronan** [comment]
sometimes error message is:
`Currently, it is only possible to build iOS apps on an OS X system.`
`Killedlding for web.cordova  `

**Comment by martijnwalraven** [comment]
The important message here is `Currently, it is only possible to build iOS apps on an OS X system.` Since you are running on Ubuntu, that is the problem. So you'll have to do `meteor remove-platform ios` before building.

The differences in output you're seeing have to do with how messages are written to the console.

**Comment by martijnwalraven** [comment]
I've reopened this issue to remind me we should consider changing this behavior.

**Comment by martijnwalraven** [comment]
As far as I can see, `Currently, it is only possible to build iOS apps on an OS X system.` is a warning message and the build should still complete successfully without building for iOS.

Are you sure the build is in fact aborted and the server tarball is not created either?

**Comment by martijnwalraven** [comment]
I have not been able to reproduce this behavior. Please reopen this issue if you feel this needs further discussion.
