### ISSUE TITLE
[1.3 Beta.11] Android icon not working and warning messages

### ISSUE THREAD

**Issue by adam-hanna** [meteor/meteor#6284]
I recently upgraded to the 1.3 Beta and am getting the following warning when I "meteor build":
```
$ WARNING: android_ldpi: unknown key in App.icons configuration. The key may be deprecated.
$ WARNING: iphone: unknown key in App.launchScreens configuration. The key may be deprecated.
$ WARNING: android_ldpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
$ WARNING: android_ldpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
```

On my Android phone, the icon for my app is now the default meteor icon and not my icon.

Here's my mobile-config.js:
```
App.icons({
	// iOS
	'iphone_2x': 	'resources/icons/apple_icon_120x120px.png',
	'iphone_3x': 	'resources/icons/apple_icon_180x180px.png',
	'ipad': 		'resources/icons/apple_icon_76x76px.png',
	'ipad_2x': 		'resources/icons/apple_icon_152x152px.png',

	// Android
	'android_ldpi': 	'resources/icons/icon_36x36px.png',
	'android_mdpi': 	'resources/icons/icon_48x48px.png',
	'android_hdpi': 	'resources/icons/icon_72x72px.png',
	'android_xhdpi': 	'resources/icons/icon_96x96px.png'
});
```

This was working fine before the upgrade to 1.3

**Comment by martijnwalraven** [comment]
The deprecation messages have to do with app icon and launch image sizes for low resolution devices that are no longer supported. So there is no need to include these.

We now support some even higher resolution images, and if you do not provide these yourself a default icon will be used. So I suspect that is what is happening here.

```
  'android_xxhdpi': '144x144',
  'android_xxxhdpi': '192x192'
```

Could you let me know if this solves your problem?

There is an existing issue for improving the documentation around this:
https://github.com/meteor/meteor/issues/5497

**Comment by adam-hanna** [comment]
I'll give this a try. I may have just made a dumb error and not read the documentation fully. My mistake.... :(

**Comment by braadworst** [comment]
@adam-hanna Did you get the icons to work on your android phone? I added the new versions and removed the low res ones but i am still not able to load an icon on my phone...

**Comment by adam-hanna** [comment]
@braadworst no unfortunately I wasn't. The app was crashing in iOS so I just gave up and went back to meteor 1.1.x :(
