### ISSUE TITLE
loadLocalPlugins called twice with different search paths.Support for     this is not implemented.

### ISSUE THREAD

**Issue by Doris1994** [meteor/meteor#6289]
Error: loadLocalPlugins called twice with different search paths.Support for 
   this is not implemented.
   at loadLocalPlugins
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:199:19)
   at findLocalPlugin
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:227:5)
   at Q.when.then.then.options.plugin_src_dir
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:118:25)
   at _fulfilled
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
   at flush
   (/Users/aei/.meteor/packages/meteor-tool/.1.1.13-beta.11.1xvnigz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)

**Comment by martijnwalraven** [comment]
When I asked you to try this on Meteor 1.3 and reopen if you felt this needed further discussion on https://github.com/meteor/meteor/issues/6136, I meant reopening the existing issue.

I'm not sure if you've read the issue guidelines, but just posting error output is not a valid issue. At the minimum, you should describe the environment you tried this on and the steps you've taken before this happened.

From [this Cordova issue](https://issues.apache.org/jira/browse/CB-7808) it seems this error message may have to do with a local plugin depending on another local plugin. Are you using any plugins added from the local file system?
