### ISSUE TITLE
[1.3-beta.11] ECMAScript syntax error not seen on Babel REPL

### ISSUE THREAD

**Issue by dj-foxxy** [meteor/meteor#6292]
Create a clean Meteor 1.3-beta.11 application (on Linux) and place the following in shared code:

```JavaScript
class Foo {
  foo () {
    let foo;
  }
}
```

Gives the build-time error message:

```
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
   bug.js:5:8: /bug.js: Duplicate declaration "foo"
   
   While processing files with ecmascript (for target os.linux.x86_64):
   bug.js:5:8: /bug.js: Duplicate declaration "foo"
```

This is not the case on the [Babel REPL](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=class%20Foo%20{%0A%20%20foo%20%28%29%20{%0A%20%20%20%20let%20foo%3B%0A%20%20}%0A}).

Also, happens with:

```JavaScript
const foo = /* any value */;
```

But not:

```JavaScript
foo (foo) { /* function body */ }
```

**Comment by benjamn** [comment]
The Babel REPL is still using Babel 5.x, though the latest version of Babel is ~6.5.0, which might explain the discrepancy.

Is this causing you problems you can't work around? I realize it's annoying, but it's definitely an upstream Babel thing.

**Comment by benjamn** [comment]
Also reported in #6276. Your summary is better, but that issue came first, so I'm (somewhat arbitrarily) closing this issue. Thanks for reporting it!

**Comment by dj-foxxy** [comment]
Hi @benjamn, Thanks for getting back to me. It's not causing me any issues at all. If anything it's making me pick proper method and variable names.
