### ISSUE TITLE
[1.3 beta-11] Cordova: Hot Code Push fails due to trailing slash in runtimeConfig.rootURL

### ISSUE THREAD

**Issue by henrikhortemo** [meteor/meteor#6293]
I get the error "ROOT_URL in downloaded asset bundle does not match current ROOT_URL. Make sure ROOT_URL has been configured correctly on the server.".

This seems due to a trailing slash in runtimeConfig.rootURL, which is not present in configuration.rootURL (AssetBundleDownloader.swift).

My app is hosted with Galaxy, and I do not use a trailing slash in ROOT_URL in settings.json nor for --mobile-server during meteor build.

**Comment by teknologist** [comment]
Same here see #6296

**Comment by martijnwalraven** [comment]
Thanks for the report. I've been able to reproduce this and I'm looking into a fix for the next beta.
