### ISSUE TITLE
Meteor down?

### ISSUE THREAD

**Issue by watsokel** [meteor/meteor#6294]
When I navigate to my app at `[appname].meteor.com`, I get  "This site is loading..." which stays there forever, and my app never loads.  When I tried to deploying my application a couple of times today, I got two different error messages:
`Error deploying application: Connection error (socket hang up)`
```
Error deploying application: <!DOCTYPE HTML>
<html>
<body>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
margin: 0;
text-align: center;
}
.meteor {
padding-top: 200px;
padding-bottom: 20px;
height: 142px;
}
.message {
padding-top: 50px;
font-size: 3em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.submessage {
padding-top: 20px;
font-size: 1.5em;
color: #777;
letter-spacing: -1px;
font-weight: bold;
}

.counter {
padding-top: 30px;
font-size: 1em;
color: #aaa;
letter-spacing: -1px;
}

</style>
</head>
<body>
<div class="meteor"><img src="//warehouse.meteor.com/mother-assets/meteor-logo-final.png"/></div>
<div class="message">
This site is down.
</div>
<div class="submessage">
Try again later.
</div>
<div id="counter" class="counter">
</div>


<script type="text/javascript">
var refreshTime = 0 ;
if (refreshTime) {
var counterDiv = document.getElementById("counter");
var countdown = function () {
if (refreshTime < 1) {
counterDiv.innerHTML =
"Retrying...";
location.reload(true);
} else {
counterDiv.innerHTML =
"Retrying in " + refreshTime + " seconds...";
refreshTime = refreshTime - 1;
setTimeout(countdown, 1000);
}
}
countdown();
}
</script>
</body>
</html>
```

Even when deployment is successful, I still get the "This site is loading..." message on the browser.

Is anyone else having this issue?

**Comment by watsokel** [comment]
I think this is resolved, my site loads now. I guess it was just temporarily down?

**Comment by Bezronczek** [comment]
I've got the same issue with my app.

**Comment by watsokel** [comment]
This issue isn't showing up on status.meteor.com but I've posted this in the Meteor forums and others are having this problem as well. https://forums.meteor.com/t/error-deploying-application-connection-error-socket-hang-up/18330

**Comment by Hongbo-Miao** [comment]
+1
Error deploying application: Service temporarily unavailable. Please try again later.

**Comment by watsokel** [comment]
Yeah I think it is still down. My Meteor site still doesn't load.

**Comment by zol** [comment]
Hi all, It looks like the free tier has been in a degraded state over the last day or so. Unfortunately, our alerts didn't pick it up and it wasn't a system wide outage so the issue wasn't reflected on the status page.

**Comment by Hongbo-Miao** [comment]
@zol I tried again, it is still shows `Error deploying application: Service temporarily unavailable. Please try again later.`

**Comment by watsokel** [comment]
@zol, I see that you've closed this, but could you tell us what the status is? Also, is there a way to report this in the future?

**Comment by zol** [comment]
We're retiring the free tier in the next few weeks as we move it over to the Galaxy infrastructure. This will be more reliable and include better downtime notification.
