### ISSUE TITLE
Update 'publish-release' command for split repos

### ISSUE THREAD

**Issue by zol** [meteor/meteor#6297]
Change the `publish-release` command to allow you to specify package versions that are not part of the checkout to facilitate the Blaze package split off.

**Comment by ramirez530** [comment]
Ramirez044yahoo.com

ramirez$14$

**Comment by zol** [comment]
We also need to think about how contributors publish new releases of the 'Independent Core Packages' (as we're now calling them) and how others are able to consume them.

**Comment by martijnwalraven** [comment]
We should be able to adapt [the `publish-packages` script from `react-packages` (https://github.com/meteor/react-packages/tree/devel/scripts/publish-packages)]. As far as I can see, only `publishOrder` contains hard coded references to specific packages.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Update%20'publish-release'%20command%20for%20split%20repos&body=Migrated%20from:%20meteor/meteor%236297) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
