### ISSUE TITLE
Update tutorials and simple-todos app to follow 1.3

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6303]
- [ ] Modules
- [ ] Add a test step
- [ ] ?

**Comment by stubailo** [comment]
For the Blaze version:
- Don't use session, instead probably a variable in the template
- Do template subscriptions
- Use `each in`

**Comment by stubailo** [comment]
For React:
- Update to new React syntax, get React from NPM

For Angular:
- Update to new Angular API, get Angular from NPM, @Urigo probably has more comments here

**Comment by tmeasday** [comment]
Deployed here: http://1.3-tutorial.meteorapp.com/

**Comment by stubailo** [comment]
My notes here:

https://paper.dropbox.com/doc/Tutorial-Docs-notes-Fw9HOdVKkPFSON2OtyBzZ

**Comment by tmeasday** [comment]
@Urigo I'm done for now with the Blaze and React versions of this, handing over to you for Angular. Please let me know how I can help

**Comment by Urigo** [comment]
I'm done as well.
Modules, tests, all the best practices for a good Angular app
