### ISSUE TITLE
Update docs to use ES2015 syntax

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6305]
Note this isn't the modules stuff (see #6304), but instead ES2015 stuff.

Note we didn't do it for 1.2

**Comment by laosb** [comment]
Mark. Do you have standards of ES6 styling?

**Comment by tmeasday** [comment]
https://github.com/meteor/guide/blob/structure-content/content/code-style.md#javascript-style-guide

**Comment by laosb** [comment]
Ha, I didn't notice the update on it.

**Comment by abernix** [comment]
Moved.

**Comment by abernix** [comment]
Moved to meteor/docs#17
