### ISSUE TITLE
Docs / Guide cleanup for 1.3

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6308]
- [x] Remove introduction from docs and point existing links at the guide articles
- [x] Add quickstart section to guide
- [x] Move prominent package readmes into docs
- [x] Remove simple docs
- [x] Move package docs to `.md` files to save CPU
- [x] Fix up formatting of spacebars table

**Comment by tmeasday** [comment]
Available at 1.3-docs.meteorapp.com

**Comment by zhe1ka** [comment]
"Available at http://1.3-docs.meteorapp.com"

What is the difference with
http://docs.meteor.com/#/full/
?

**Comment by tmeasday** [comment]
You can read the list of changes above. It's just a temporary hosting of the new docs for 1.3
