### ISSUE TITLE
Unexpected mongo exit code 100

### ISSUE THREAD

**Issue by QuoniamYIF** [meteor/meteor#6310]
I start meteor and this is what I get.

```
=> Started proxy.                             
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Can't start Mongo server.                     

Looks like you are out of free disk space under .meteor/local.
```

I am using 1.1.2

I do as the method in this issue[https://github.com/meteor/meteor/issues/2772], but that didn't work.

**Comment by tmeasday** [comment]
Hi @QuoniamYIF -- it sounds like your development machine is out of disk space? Have you checked that?

**Comment by QuoniamYIF** [comment]
thank you,it's just like what you say
