### ISSUE TITLE
Ensure angular-meteor is up to date with Meteor 1.3

### ISSUE THREAD

**Issue by zol** [meteor/meteor#6315]
The angular-meteor should work as soon as we release 1.3.

**Comment by Urigo** [comment]
Angular1-Meteor can be tracked [here](https://github.com/Urigo/angular-meteor/milestones/1.3.7-beta.1).
Angular2-Meteor can be tracked [here](https://github.com/Urigo/angular2-meteor/milestones/0.5.0-beta.1).

**Comment by dohomi** [comment]
I think this task can get closed. I'm using Meteor 1.3 with meteor-angular 1.3.10 without any trouble

**Comment by Urigo** [comment]
true that.
