### ISSUE TITLE
Changes to testing file matching patterns

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6321]
Moving from https://github.com/meteor/meteor/issues/5784#issuecomment-187518773

#### Unit tests:

- matching *.tests.* but not *.integration.tests.*
- or test*

#### Integration tests:

matching *.tests.* but not *.unit.tests.*
- or test*

#### Acceptance tests (ignored by all modes of meteor)

- inside top level `acceptance-tests/` directory.

**Comment by avital** [comment]
I thought we'd do `tests/integration/`. Sounds a little weird to special case acceptance and not integration. And it would be surprising that simply by being in `tests/` as opposed to a file named `test_foo.js` is an integration test instead of a unit test. What do you think?

**Comment by tmeasday** [comment]
So other stuff inside `tests/` are unit tests?

**Comment by avital** [comment]
Maybe the existence of files in `tests/` throws an error? But this might not really matter.

**Comment by tmeasday** [comment]
Ok, changed the requirements above
