### ISSUE TITLE
Check that dependencies from `package.json` are installed when running/bundling

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6322]
So I created this simple Atmosphere package (not yet released) that allows you to check a set of npm packages are installed in your app `https://github.com/tmeasday/check-npm-versions/blob/master/check-npm-versions.js`

https://github.com/tmeasday/check-npm-versions

I think this task would be as follows:
- [ ] Move the core logic of the package to an npm package
- [ ] Make the npm package return some kind of error object so we can log differently in different contexts
- [ ] Use the npm package at an appropriate spot of the tool, passing in `dependencies` or `dependencies  + devDependencies` depending on whether we are running `meteor run|test-X|etc` or `meteor build|bundle`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Check%20that%20dependencies%20from%20%60package.json%60%20are%20installed%20when%20running%2Fbundling&body=Migrated%20from:%20meteor/meteor%236322) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
