### ISSUE TITLE
Move React/Todos example into the main Todos repository

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6323]
It's here: https://github.com/meteor/module-todos-react

@zol perhaps you can make the call as to whether this is 1.3 or post?

**Comment by zol** [comment]
Sorry for the late response on this one. What is required for this? I don't understand what work is implied.

**Comment by tmeasday** [comment]
There's a second repo with essentially a branch of our todos up designed to work with modules/1.3.

However Todos keeps moving forward and has changed a little. Probably the best thing to do is to move this code into the meteor/todos repo and merge master into it / deal with resulting problems. 

It may make sense to do this anyway, given I'm in charge of the react article now

**Comment by zol** [comment]
Ahh, got it. I think you're right and it makes sense to merge it.
