### ISSUE TITLE
[Meteor 1.3 beta.11] Cannot find module 'fs'

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6324]
i tried
`import fs from 'fs';`
and this message from client:
`Cannot find module 'fs'`

i try to use js-yaml and this package has dependencies "fs" package.
any missing?

**Comment by aldeed** [comment]
"fs" is a NodeJS module so it wouldn't be available in client code

**Comment by aldeed** [comment]
Actually it looks like you can `npm install --save meteor-node-stubs` to get client-side stubs now

**Comment by lyquocnam** [comment]
thanks aldeed, i will try

**Comment by aldeed** [comment]
I don't know how to use it either, but it sounds like you just need to add it and everything will start working.

**Comment by benjamn** [comment]
This is fixed in beta.16, thanks to #6056, though note that the `fs` module is just an empty stub on the client.
