### ISSUE TITLE
[1.3-beta.11] Meteor.methods userId

### ISSUE THREAD

**Issue by vitalyrotari** [meteor/meteor#6326]
`this.userId` in methods always return `null`. 

```javascript
Meteor.methods({
  '/check/roles'() {
    const userId = this.userId;
   // ...
 }
});

Meteor.startup(function() {
  Meteor.call('/check/roles');
});
```

Also trying `$ meteor shell`

```
> Meteor.user()

Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
    at AccountsServer.user (packages/accounts-base/accounts_common.js:53:23)
    at Object.Meteor.user (packages/accounts-base/accounts_common.js:230:19)
    at [object Object]:1:-54
    at Script.(anonymous function) [as runInThisContext] (vm.js:41:22)
    at /Users/CKY/Projects/meteor/minefield/.meteor/local/build/programs/server/shell-server.js:363:27
    at /Users/CKY/.meteor/packages/meteor-tool/.1.1.13-beta.11.q3use8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40
```

```
> console.log(this.userId)

undefined
```

**Comment by avital** [comment]
Well, the shell doesn't demonstrate anything -- `this` is the global object, not a method invocation.

Are you sure you're logged in when you call the method? Can you supply a small repro repository that demonstrates this issue? (Something we can clone and run to see this behavior?)

**Comment by vitalyrotari** [comment]
Actually I solve the problem... But I think it's little tricky.
The base case is to check something for logged-in users when Meteor is startup

```javascript
Meteor.methods({
  '/users/verify'() {
     const userId = this.userId;
     // some logic here
  }
});
```

### First method

> in this case `this.userId` is always `null`

```javascript
Meteor.startup(function() {
  Meteor.call('/users/verify');
})
```

### Second method

> this case works fine

```javascript
Accounts.onLogin(function() {
  Meteor.call('/users/verify');
})
```

I think `userId` must be available for first method, because we call method when Meteor is started.

**Comment by avital** [comment]
This is how Meteor log in works. When the app is loaded the user isn't yet logged in -- there's a server round-trip required to verify that the stored token is valid.
