### ISSUE TITLE
METEOR@1.3-beta.11 accounts-ui and/or accounts-password not correctly working with Firefox and IE11

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor/meteor#6330]
Meteor 1.3  beta 11 developed and tested on Windows 8

The accounts-ui and/or accounts-password not correctly working with Firefox and IE11.
It does work in Chrome.

See http://meteor-react-start-app.meteor.com

**Comment by zol** [comment]
Do you see the same issue with 1.2? Can you provide a reproduction?

**Comment by AnnotatedJS** [comment]
You can find the source on [GitHub](https://github.com/AnnotatedJS/meteor-react-start-app). No, I can't reproduce it in 1.2 The whole app is geared towards 1.3.

**Comment by AnnotatedJS** [comment]
i have checked it on my local server (Windows 8) and it gives the same problem.

**Comment by zol** [comment]
Thanks for the link @AnnotatedJS. It would help us if you could provide a stripped down reproduction containing code that just demonstrates the specific issue.

**Comment by AnnotatedJS** [comment]
Stripping down was a good suggestion. After removing <button> ... </button> around
<AccountsUIWrapper /> the signin works with all three browsers. See [my commit](https://github.com/AnnotatedJS/meteor-react-start-app/commit/0f5ce130436a8d67822544d7f3b42b302c327fdf)
If you still want a stripped down reproduction of code reproducing this issue, let me know and I will place it on GitHub.

**Comment by zol** [comment]
Great, I'll close this out.
