### ISSUE TITLE
[Meteor@1.3-beta.11] Problem with Tap:i18n package

### ISSUE THREAD

**Issue by okland** [meteor/meteor#6332]
Only package being used is tap:i18n.
When running meteor with version Meteor@1.3-beta.11, I get the following :

```
=> Started proxy.
=> Started MongoDB.
toEnd: wrong arguments-i18n-compiler` fr...  \

to: wrong arguments

=> Started your app.

=> App running at: http://localhost:4000/
```

All you need to do in order to reproduce the problem is to run the following commands:
`meteor create 1.3-tap-test`
`meteor update --release 1.3-beta.11`
`meteor add tap:i18n`
`meteor`

There are also issues under [the package itself](https://github.com/TAPevents/tap-i18n/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+1.3+), just thought it might be issues that also relevant to the meteor version.

**Comment by zol** [comment]
I was able to reproduce this and noted that I didn't see this behavior with Meteor 1.2

**Comment by benjamn** [comment]
This seems to be a duplicate of #5107, and may be related to the use of the `shelljs` package by Cordova. Closing in favor of that issue.
