### ISSUE TITLE
[1.3-beta.11] ES modules in package and support for Meteor 1.2

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#6334]
Hi, as in the subject, will it be possible to use package using ES modules in Meteor 1.2? Meteor 1.2 does not see the `api.mainModule` method. Someone in the forums advised me to build package into one file and use that to support Meteor 1.2. As Meteor in the build process creates one single file for each package I'm curious if such file could be used for that. However, I'm not sure. Do you have any plans to allow Meteor 1.3 package be used with Meteor 1.2?

**Comment by zol** [comment]
It will not be possible to use npm packages in 1.2 the same way that you can in 1.3 . You can still use  write a wrapping Meteor package and use `Npm.depends` as you always have.

**Comment by jagi** [comment]
I'm not talking about npm packages. I'm talking about Meteor packages with EcmaScript modules.

**Comment by zol** [comment]
Ahh, I see. It will not be possible to write packages that use the new module syntax in a backward compatible way.

**Comment by jagi** [comment]
Are you 100% sure that there is not workaround? I was thinking about it and let me explain how I see it and I would like to hear if my thinking is correct.

Meteor build system builds each package into one .js file. If a package is using ES6 modules it's still transpiled into version that is compatible with ES5. It uses `requirejs` on both server and client, right? So what's the problem with just using the newest version of the `ecmascript` package that would be used only for packages using ES6 modules?

Maybe I'm missing something and there is some compatibility breaking change.

**Comment by zol** [comment]
Yeah, unfortunately it won't work. The modules stuff relies on a bunch of tool changes.

**Comment by jagi** [comment]
Ok that's bad. I will have to force users to switch to Meteor 1.3. Thanks for help
