### ISSUE TITLE
[Meteor@1.3-beta.11] page title changes to "Mocha" when using avital:mocha

### ISSUE THREAD

**Issue by helfer** [meteor/meteor#6336]
With the package `avital:mocha` is added, `meteor run` causes the server side unit tests to run and the page title (head title attribute of the page) is changed to "Mocha". See it in action with this [fork of the todos app](https://github.com/apollostack/module-todos-react-graphql).

**Comment by tmeasday** [comment]
@avital - is it possible that `avital:mocha@2.1.0_5` isn't `testOnly` after all?

I forgot to put it in my github repo version, if you ever published from there.

**Comment by avital** [comment]
I wasn't able to reproduce this issue. I ran the app with `meteor`. The title was "module-simple-todos-react". I also verified in the console, by looking at the `Package` object that `avital:mocha` wasn't being loaded. (Though, surprisingly `practicalmeteor:chai` and `practicalmeteor:sinon` were)

Then I ran `meteor test-app` and did see the title being "Mocha" and that `avital:mocha` was present in the `Package` object.

**Comment by tmeasday** [comment]
That is odd. Were you running `meteor` or `curmeteor`?

**Comment by tmeasday** [comment]
(All I did was clone the repo, `npm install`, `npm add lodash`, `meteor`)

**Comment by avital** [comment]
I tried both `meteor` and `curmeteor`. The app loaded correctly on both. (Are you saying that you did reproduce the problem?)

**Comment by tmeasday** [comment]
Yes, I did reproduce the problem. I saw 2 things
 1. the title "Mocha"
 2. an error in the console that came out of the `avital:mocha` package

**Comment by avital** [comment]
Apparently the way the "testOnly" change in the tool works is that it reads the metadata it gets from packages.meteor.com and then selectively writes certain properties to the metadata file on disk. (This is true for all of the metadata, not just testing).

See this change: https://github.com/meteor/meteor/commit/6682972c3a718140a35cab3e4841667d92a472c5#diff-740d015e502f4c1c0d97061a8c158589R1182
 
So, basically: If you ran `avital:mocha` with a non-1.3 version of Meteor ever, and then ran it with 1.3, you'd not have `testOnly` in the local metadata for the package

(I guess this happened when we introduced `debugOnly` and `prodOnly` as well)

Anyhow, I think the best thing to do now is "nothing". And if someone complains about this just tell them to delete `~./.meteor/packages/avital_mocha` and run their app again. (Or later `~/.meteor/packages/practicalmeteor_mocha`)
