### ISSUE TITLE
Confusing README of Meteor Stylus Repo

### ISSUE THREAD

**Issue by ldong** [meteor/meteor#6337]
Hi Meteor Devs,

I don't usually reach out to people like this, especially on other repo [meteor/stylus](https://github.com/meteor/stylus/). It seems to be the best way to file an issue here, since issue list of [meteor/stylus](https://github.com/meteor/stylus/) is closed.

Please, please do NOT write confusing words in the [README](https://atmospherejs.com/meteor/stylus) in [atomspherejs](http://atomspherejs.com), see the following screenshot.

<img width="1219" alt="screen shot 2016-02-24 at 8 04 38 pm" src="https://cloud.githubusercontent.com/assets/5491695/13309867/4edfcd52-db35-11e5-9143-3451b42c9fa9.png">

With the stylus package installed, **.main.styl** files in your application are
automatically compiled to CSS and the results are included in the client CSS
bundle.

Creating `.main.styl` simply does not work. So, instead of saying misleading words like that, one could say, any file ending with `.styl` will be automatically merged and bundled into one css. It was confusing to me, and I don't understand why this [file change](https://github.com/meteor/meteor/commit/d6e816e3fd84b58185e01f3f6307c0dd2d5e578d?diff=split) is not reflected in the current stylus README. Please help, and make sure you update both github [repo](https://github.com/meteor/stylus) and [atomspherejs](http://atomspherejs.com).

BTW, can meteor developers explain why you guys closed issues on [meteor/stylus](https://github.com/meteor/stylus/) repo?

Thank you,
Lin

**Comment by Menda** [comment]
Makes sense to me

**Comment by Slava** [comment]
The meteor/stylus repo you linked to is a fork of an npm module. We did it to submit PRs. The actual package is in this repo.

**Comment by ldong** [comment]
@Slava Thank you for clarifying, I got that. I just wonder why the README was not being updated on the [atmospherejs](https://atmospherejs.com/meteor/stylus) website. i.e.
```
With the `stylus` package installed, `.main.styl` files in your application are
automatically compiled to CSS and the results are included in the client CSS
bundle.
```

And that is confusing. Can you please update that?

**Comment by lorensr** [comment]
`foo.styl` works for me. I've never tried `.main.styl` or `foo.main.styl`.

**Comment by abernix** [comment]
@ldong Thanks for reporting this and sorry it took so long to get around to it.  It will be updated on Atmosphere when the next release is published.  PRs are definitely welcomed for this stuff to make them land quicker.
