### ISSUE TITLE
[beta.11] Error: Must throw non-empty error

### ISSUE THREAD

**Issue by trusktr-goin** [meteor/meteor#6340]
Beta.8 is working fine, but with beta.11 (and using mupx) to deploy, the deployment says:

**Comment by trusktr-goin** [comment]
![error](https://cloud.githubusercontent.com/assets/16913311/13313358/2276e1b6-db52-11e5-8847-01771cb51999.jpg)

**Comment by zol** [comment]
Hey. Are you able to provide a reproduction that causes the problem without mup?
