### ISSUE TITLE
Bundled code isnt 'ugly' ~~enough~~ at all!

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6342]
In my opinion code generated for production app is too easy to reverse engineer. Actually, the only things obfuscated are variable names and... that's it.
Is it intentional? Is some kind of debugging assumed on a production app?

I propose that everything is completely obfuscated besides raw values and strings:

- `Meteor` namespace
- Collections
- Method names
- Subscription names
- Object props and methods
- Global variables
- Anything else?

**Comment by ciclopes** [comment]
+1

**Comment by osv** [comment]
Ha! almost all code is easy to reverse, especial angular :)

I think you should learn more how js minificators work, google closure compiler can minify properies, but you should do a lot of work to make it right. https://github.com/google/closure-compiler/wiki/FAQ

**Comment by avalanche1** [comment]
@zol why you close it?

**Comment by zol** [comment]
@avalanche1 closed it because beyond an opinion this issue doesn't represent something constructive  e.g a reproducible bug report. Our forums are a better place for general, discussion - this would be a better place for this issue.
