### ISSUE TITLE
(Meteor 1.3-beta.11) Error: Cannot find module 'meteor/mongo' while running mocha - Server Side

### ISSUE THREAD

**Issue by lucidprogrammer** [meteor/meteor#6343]
Need to create a server module. All works except that mocha is not able to resolve 'meteor/mongo'. Details as follows. Any help is appreciated
**server/tester/package.json**
`
  "name": "tester",

  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "testonly": "mocha ./tests/*.js --compilers js:babel-core/register",
    "test": "npm run testonly"
  },
  "author": "",
  "license": "",
   "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "chai": "3.x.x",
    "mocha": "2.x.x"
  }
}
`

**server/tester/collection.js**

`import {Mongo} from 'meteor/mongo';

export const Taste = new Mongo.Collection('taste');
`
npm test gives the following error

`> mocha ./tests/*.js --compilers js:babel-core/register

module.js:340
    throw err;
    ^
Error: Cannot find module 'meteor/mongo'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)`

From the meteor shell, all works, where I can insert to the collection etc. I guess it boils down to properly resolving 'meteor/mongo'

Any suggestions on what I am doing wrong or how to get it right.

**Comment by lucidprogrammer** [comment]
Ok possibly my misunderstanding. Support for ES6 module support does not mean meteor itself is available!!! Possibly some day where meteor itself is npm installable?

**Comment by Menda** [comment]
Hi, I have in my code:

    import {Mongo} from 'meteor/mongo';
    export const Districts = new Mongo.Collection('districts');

Which runs perfectly using Meteor 1.3-beta 11.

What do you need `mocha` for exactly?

**Comment by gsabran** [comment]
Same here, this works fine in the Meteor server, but not in in `mocha` tests. Well I need mocha for testing...

**Comment by mfpinheiro** [comment]
I have the same issue here. I need this for using mocha fot tests. Any help will be nice.

**Comment by luckyyang** [comment]
Same failure with release `METEOR@1.4.0.1`, any update about this or anybody solved this problem?
