### ISSUE TITLE
weak dependency not working

### ISSUE THREAD

**Issue by arunhedcet** [meteor/meteor#6344]
I've tried to add a weak dependency to my package. But it doesnt seem to be working. Here is the repo https://github.com/arunhedcet/meteor-weak-dependency-test

[package.js][1]

    Package.describe({
      summary: "Test of Meteor's weak dependency resolution"
    })
    
    Package.on_use(function (api) {
      api.use('iron:router', ['client', 'server'], {weak: true})
    
      api.add_files('weak-test.js', 'server')
    })

[weak-test.js][2]

    var router = Package['iron_router'];
    
    console.log("[weak-test] iron-router package found?", !!router);
    console.log(router);

  [1]: https://raw.githubusercontent.com/arunhedcet/meteor-weak-dependency-test/master/packages/weak-test/package.js
  [2]: https://raw.githubusercontent.com/arunhedcet/meteor-weak-dependency-test/master/packages/weak-test/weak-test.js

**Comment by tmeasday** [comment]
Hi,

It should be 

```js
var router = Package['iron:router'];
```

Cheers.

**Comment by arunhedcet** [comment]
@tmeasday 

Interestingly

**Comment by tmeasday** [comment]
What's the difference between the two? `on_use` vs `onUse`? I really don't think that'll make any difference.
