### ISSUE TITLE
Custom Cordova plugin: wrong relative path on Windows (Meteor 1.3 beta 11)

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#6345]
I guess this is for @martijnwalraven:

I add my custom plugin to the "cordova-plugins" file:

`com.obi.volumeTracker@file://.cordova-plugins/volumeTracker`

OSX compiles fine, in Windows I get an error message:

```
While installing Cordova plugins:
   error: Couldn't find local directory 'C:\C\Users\sebas\Documents\storeapp\.cordova-plugins\volumeTracker' (while attempting to install plugin com.obi.volumeTracker).
```

**Comment by martijnwalraven** [comment]
This should be fixed in Meteor 1.3 beta 12.
