### ISSUE TITLE
meteor run ios-device, bugged when running on localhost but ok on mobile-server (1.3 beta 11)

### ISSUE THREAD

**Issue by lukastheiler** [meteor/meteor#6347]
I reproduced this strange behaviour with a very simple app, which just lists the elements of a collection on 1.3 beta 11. 

__OK__: ```meteor run ios ```works fine both in the browser and in the ios simulator

__NOT OK__: ```meteor run ios-device ``` browser ok, but no collection item shows up on the physical ios device. 

__OK__: ```meteor run ios-device --mobile-server lukas13b11.meteor.com``` works both on the browser and the physical device. 

Does anyone know a workaround?

**Comment by martijnwalraven** [comment]
In the `meteor run ios-device` case, are you sure your device is able to connect to the local server? They have to be on the same WiFi network, there might be router settings preventing them from connecting to each other, or the computer could be blocking ports.

**Comment by lukastheiler** [comment]
WIFI wasn't the issue, ```meteor run android-device```worked fine. 
However: i just did a ```rm -rf .meteor/local/build```and ran  ```meteor run ios-device``` - and now it works like charm. Very strange. I'll keep an eye on it and do more rm's. 
So i'm guessing we can close the issue for now. 
Thanks! Lukas
