### ISSUE TITLE
[Request] Support for Mobile SDK (IOS/ANDROID) 

### ISSUE THREAD

**Issue by davidbilly** [meteor/meteor#6350]
@stubailo , Have any chance meteor will be support Android/IOS native SDK? 

Planning write an app with native code without using Webview. 

Thanks :D

**Comment by ChrisOHu** [comment]
Hi,
fyi, you can use the community implementations android-ddp[https://github.com/delight-im/Android-DDP] & meteor-ios[https://github.com/martijnwalraven/meteor-ios]

**Comment by stubailo** [comment]
Yeah I think for now the community DDP clients are the answer.

**Comment by luiseduardobrito** [comment]
Guys, community packages are not suitable for commercial usage of Meteor, is there any plans of officially supported SDKs?
