### ISSUE TITLE
[beta.11] Error during importing npm packages with es2015 syntax

### ISSUE THREAD

**Issue by mhhf** [meteor/meteor#6353]
I have installed an npm package by including it as a dependency in `package.json` file and installing the dependencies with `npm install` with npm 3.3.5. 
when I require/importing it from my server side code 
`var pkg = require('pkg');`
I get the following error:
```
[...].meteor/local/build/programs/server/packages/modules.js:1388
     for (let entry of result.logs) {
          ^^^
 SyntaxError: Unexpected strict mode reserved word
     at [...].meteor/local/build/programs/server/boot.js:244:30
     at Array.forEach (native)
     at Function._.each._.forEach (/Users/mhhf/.meteor/packages/meteor-tool/.1.1.13-beta.11.m1bb0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /Users/mhhf/work/99_extern/nexus/dapphub/.meteor/local/build/programs/server/boot.js:140:5
=> Exited with code: 8
```

However, the breaking code from the package(`for (let entry of result.logs) {`) just works fine if i include it in my server side code.

I'm working on `METEOR@1.3-beta.11` with `ecmascript 0.4.0-beta.11`
My node version is `0.10.41`

**Comment by benjamn** [comment]
We don't do any further compilation of files installed by `npm`, so this behavior is expected. Packages published to npm need to be precompiled to run by Node without modification.

Out of curiosity, though, which package were you hoping to use?

**Comment by mhhf** [comment]
Thanks for the fast replay. I'm the co-author of [dapple](https://www.npmjs.com/package/dapple) and was hoping to access their features on the server-side.
We will think about introducing an intermediate compilation-step here to make it compatible.

**Comment by benjamn** [comment]
Ah, I see `dapple` only promises to support [Node v5.x](https://github.com/nexusdev/dapple/blob/ef7a9fad7a2a06564d580a5b2daa7a1d5a81adb8/package.json#L84) and above. I like how forward-thinking you are!

[Upgrading the version of Node that Meteor uses](https://github.com/meteor/meteor/issues/5124) is a major priority after 1.3. Once we switch over to Node 4 (or more likely 5 at this point), this package will have a much better chance of working without compilation.

**Comment by abernix** [comment]
Closing as Meteor 1.4 is out now and comes with Node 4.4.7.  This issue will be greatly improved (and hopefully your package will work now) but the bottom line is that node modules need to be transpiled to run in the environments they wish to run o n.  More details in my comment here: https://github.com/meteor/meteor/issues/7420#issuecomment-233935516
