### ISSUE TITLE
React error

### ISSUE THREAD

**Issue by civako227** [meteor/meteor#6354]
Use Meteor 1.2.1 (same problem with 1.3 beta 11) on Windows 8

Add package `react` and type `meteor` after that I see this

![default](https://cloud.githubusercontent.com/assets/16919130/13364356/76061c3c-dcdf-11e5-8c48-81f6183e3c4d.PNG)

**Comment by tmeasday** [comment]
Hey,

I can't really see what's happening here but I'm not sure the old (current) `react` package works with 1.3 out of the box. We plan on updating it to basically just enforce the NPM-installing of react that we recommend here: https://github.com/meteor/react-packages/issues/169

**Comment by tmeasday** [comment]
Please let me know if you can't get it working following those instructions.
