### ISSUE TITLE
"No metadata files found for isopack" when update to 1.3 beta 11

### ISSUE THREAD

**Issue by civako227** [meteor/meteor#6358]
When I try to update Meteor 1.2.1 (Windows 8) project to 1.3-beta.11 I see this error

![default](https://cloud.githubusercontent.com/assets/16919130/13372566/44753750-dd59-11e5-895b-f0a944ad6868.PNG)

**Comment by derekmartinla2** [comment]
What was the resolution here? I also have this issue and after several reinstalls of Meteor, it still persists.

**Comment by almawhoob** [comment]
I am getting the same issue!

**Comment by abernix** [comment]
The recommendation is to run `meteor reset` (this will remove your dev database as well) and then perform a fresh installation of Meteor using the instructions here: https://github.com/meteor/meteor/issues/5719#issuecomment-229102966

Please write back if you still have issues after performing both of these tasks.
