### ISSUE TITLE
[Meteor 1.3] Add --ci option for test-app

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#6359]
cc @avital @tmeasday 

I managed to get headless `test-app` working for Meteor 1.3. I did it by creating an npm package that is similar to spacejam but much less code and aimed at the `test-app` command rather than `test-packages`. Given that it's only a minimal amount of code and one npm dependency, can we discuss adding this directly into the meteor tool as a `--ci` or `--headless` option for `test-app`? It's such a common need that it seems like it should be baked in if Meteor 1.3 is really supposed to address everyone's complaints about ease of testing.

https://github.com/DispatchMe/node-spaceghost

It needs my fork of the avital:mocha package temporarily only because there isn't a beta release that supports `--driver-package` yet, so I changed to the console package as default directly in my fork.

My fork also includes this, which should be added to `avital:mocha`: https://github.com/aldeed/meteor-mocha-for-1.3/commit/a4504bdd6fa5a0ef464667298a34e57213e89437 In my opinion, the Meteor tool should print the "App running at:" line both in normal mode and in --once mode since that's useful information and required to know when to load the page. I can create a separate issue for that if you agree.

**Comment by Menda** [comment]
This is a really *MUST* to have. I was using Python for a long time and I couldn't believe when I started with Meteor that you needed to open a browser pointing to localhost:3000 in order to run unit tests. Big +1 to feature this.

**Comment by tmeasday** [comment]
Hey @aldeed - this is cool! It worked for me against Todos also.

I'm not sure there's much benefit in baking this into meteor core however. I think at this point we are trying to minimize the scope of the tool, and make sure that things can be accomplished without needing to change it. This seems like a great example of where a simple npm module can achieve the functionality we want without needing any explicit support from the tool.

I think if the section on testing in the guide basically has your instructions for adding it to `package.json` and running `npm run test`, I'll be really happy (whether it's this package or spacejam).

> My fork also includes this, which should be added to avital:mocha: aldeed/meteor-mocha-for-1.3@a4504bd In my opinion, the Meteor tool should print the "App running at:" line both in normal mode and in --once mode since that's useful information and required to know when to load the page. I can create a separate issue for that if you agree.

I'm sort of confused here. Isn't it the console reporter package that needs to log that line?

**Comment by tmeasday** [comment]
@rbabayoff I would be interested in your thoughts about the differences between this and spacejam..

**Comment by aldeed** [comment]
@tmeasday, forgetting about testing needs for a moment, it is still a bit strange that you see "App running at:" line in normal mode, but you add `--once` flag and then you never get any indication that the app started. The console reporter needs some indication of when it's OK to load the page with phantomjs, so I replicated printing that line, which is a solution I actually borrowed from here: https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/test-in-console/reporter.js#L30-L35

So if every console reporter pkg needs to do it, and if it would be helpful for a human to see that line anyway to know that startup was successfully in `--once` mode, then why not just figure out a way for the core tool to print that line?

I would agree that the tool I made is essentially the same as spacejam, so it would be better to bake into spacejam. Spacejam has a lot of code that did not seem necessary to me, so I just wanted to make the simplest possible thing for now. If @rbabayoff thinks it makes sense, we can work to merge the two tools.

**Comment by tmeasday** [comment]
@aldeed perhaps we should open a separate issue for the logging in `--once` mode thing. I think your analysis is correct there, I'm not sure why the tool doesn't print it in that mode?

**Comment by tmeasday** [comment]
@aldeed we aren't sure why `meteor run --once` is quiet (historical reasons perhaps) so I've turned it off (https://github.com/meteor/meteor/commit/7f4d9706b8b32c3919ccbb674ba0a520d9172129). We'll see if anyone complains about it in the next beta release ;)

**Comment by rbabayoff** [comment]
@aldeed and @tmeasday , I do plan to support test-app, if time permits, and more importantly, I think that either tool should support cross browser unit testing from the console and in ci envs using selenium / sauce / browserstack, not only headless testing using phantomjs. Both I and others have run into quite a few compatibility bugs between phantomjs and browsers and between different browsers, when testing our packages. Supporting this will result in more stable packages and easily finding compatibility bugs during development, not in production.

Regarding not integrating it into meteor, my opinion is that it should, we should encourage and make it really easy for even the most novice developers to start with unit tests and ci from the get go, as meteor does for writing apps, and having it part of meteor would provide such encouragement. With using something like --console-test-driver, the developer can then decide in what browser and env he wants to run it's unit tests, and the community can write test drivers, such as the phantomjs execution code in spacejam or running selenium locally or on sauce. Once the test driver exits, meteor exists with it's status code.

**Comment by tmeasday** [comment]
I'm closing this issue as I'm pretty sure we are not going to add this to the tool, for the reasons outlined above. But feel free to continue the discussion here or elsewhere.

**Comment by aldeed** [comment]
I think the point about supporting other headless options is good. The main thing here is that MDG needs to officially document exactly how to do it. @tmeasday do you need a ticket in meteor/guide for this, or do you already have it covered?

Thanks for the `silent` fix, too. That will help. There are probably a couple other tiny adjustments that could be made to at least make support for headless driver packages more overt without going as far as a `--ci` option. To reduce unnecessary boilerplate shared among them, etc. We can keep that in mind, but for now it's fine.

**Comment by tmeasday** [comment]
> @tmeasday do you need a ticket in meteor/guide for this, or do you already have it covered?

Yup, check 8 here: https://github.com/meteor/guide/blob/master/outlines/testing-outline.md
