### ISSUE TITLE
Meteor.userId not available in REST api calls for collection hooks

### ISSUE THREAD

**Issue by dtruel** [meteor/meteor#6360]
Hello,

First I want to say thank you for making a great, great product!

I'm using collection-hooks to manage access to my databases.  It relies on Meteor.userId().

Now I'm also building an api that needs to use these collection hooks to manage authentication.  Unfortunately, it has been made absolutely impossible (as far as i can tell) to set a meteor userId from any server side method.  The rest api is never going to use DDP or client side methods, so my whole authentication scenario breaks!  If I try to sneakily first call a Meteor.method and set it in there using `this.setUserId`, I am stopped by an error that says I can't set userId in serverSide calls.

There needs to be some way that I can fake Meteor.userId() for the sake of making the collection-hooks run in my API.  This is a major need, and it should not be so hard to do.

Thank you for your help.

**Comment by zol** [comment]
Thanks for the kind words. However, "How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!
