### ISSUE TITLE
Error occuring when build for android with cordova

### ISSUE THREAD

**Issue by SherlockStoneed** [meteor/meteor#6362]
# ISSUE SOLVED :+1: 
## [**Click here to go to the solution !**](https://github.com/meteor/meteor/issues/6362#issuecomment-189852511)

When I try to launch "meteor run android" or "meteor build android --server ***" I win this beautiful error ...
Someone to help me ? :cry: :smile: 

```
=> Errors executing Cordova commands:         
                                              
   While building Cordova app for platform Android:
   Error: /home/sherlock/workspace/simple-todos-mobile/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit
   code 8 Error output:
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   A problem occurred configuring root project 'android'.
   > Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:1.0.0+.
   Required by:
   :android:unspecified
   > Failed to list versions for com.android.tools.build:gradle.
   > Unable to load Maven meta-data from https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml.
   > Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml'.
   > peer not authenticated
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   

   /home/sherlock/workspace/simple-todos-mobile/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command: /home/sherlock/workspace/simple-todos-mobile/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildRelease,-b,/home/sherlock/workspace/simple-todos-mobile/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
   at ChildProcess.whenDone
   (/home/sherlock/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
   at ChildProcess.emit (events.js:98:17)
   at maybeClose (child_process.js:766:16)
   at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by SherlockStoneed** [comment]
My project include AngularJS if it's important ^^

**Comment by SherlockStoneed** [comment]
On the web it said it's a proxy problem ... but I just have my internet nob and nothing other ...
I try this : 

```
$ export HTTP_PROXY=192.168.1.1:80
$ export HTTPS_PROXY=192.168.1.1:443
$ meteor update

Unable to update package catalog (are you offline?)
                                              
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

```

**Comment by martijnwalraven** [comment]
I'm not sure what is going on here, but it seems it somehow fails to connect to the Maven repository to download Gradle and other dependencies. Could indeed be a network issue, or maybe the repo itself is having trouble.

What version of Meteor are you using?

**Comment by SherlockStoneed** [comment]
Meteor 1.2.1 ...

I think it isn't a repo error because the url ttps://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml is accessible trough the navigator it's a https connection error.

**Comment by SherlockStoneed** [comment]
Thanks for helping me ^^

**Comment by martijnwalraven** [comment]
Ah, that makes sense. Maybe a missing certificate or strict security setting? What OS are you on?

**Comment by SherlockStoneed** [comment]
I'm on Ubuntu 15.10

**Comment by SherlockStoneed** [comment]
Yes it's maybe a missing certificate or strict security setting you're right (I think) but how to configure that ?

**Comment by SherlockStoneed** [comment]
I'm trying to configure the gradle-wrapper.properties (in $PROJECT_PATH/.meteor/local/cordova-build/platforms/android/gradle/wrapper) for it load the xml I downloaded on my docs ... but I think this file is regenerated in compilation, and replace my file version ...

**Comment by SherlockStoneed** [comment]
I comment this line on build.gradle the file gradle-wrapper.properties will not be generated on each build (in theorie)

```
task wrapper(type: Wrapper) {
    gradleVersion = '2.2.1'
}
```

**Comment by SherlockStoneed** [comment]
I found this on Stackoverflow :

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

// Running 'gradle wrapper' will generate gradlew - Getting gradle wrapper working and using it will save you a lot of pain.
task wrapper(type: Wrapper) {
    gradleVersion = '2.2' 
}

// Look Google doesn't use Maven Central, they use jcenter now.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by SherlockStoneed** [comment]
Result with this method :

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:0.14.0+.
     Required by:
         :android:unspecified
      > Could not resolve com.android.tools.build:gradle:0.14.0+.
         > Failed to list versions for com.android.tools.build:gradle.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
               > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
Seems to be certificate like you say : 
`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by SherlockStoneed** [comment]
There is a resolve idea : [Unable to Connect to SSL Services due to PKIX Path Building Failed](https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html)

**Comment by SherlockStoneed** [comment]
@martijnwalraven plz close the issue :)

**Comment by SherlockStoneed** [comment]
If you have an error like this : 

```
/PROJECT_DIR/platforms/android/cordova/node_modules/q/q.js:126
throw e;
^
Error code 1 for command: /PROJECT_DIR/platforms/android/gradlew with args: cdvBuildRelease,-b,/PROJECT_DIR/platforms/android/build.gradle,-Dorg.gradle.daemon=true
```

Try to remove the line 126 `throw e;` from the file /PROJECT_DIR/platforms/android/cordova/node_modules/q/q.js

**Comment by jensenmobile** [comment]
I got this error when run cordova project on terminal

Error: /Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

Where:
Build file '/Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/build.gradle' line: 253

What went wrong:
A problem occurred evaluating root project 'android'.

Project with path ':androidOpenCVExample' could not be found in root project 'android'.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

How can I resolve this?

**Comment by SherlockStd** [comment]
Sorry @jensenmobile , I don't think this error is related with this issue.
Please open another issue to resolve it.

**Comment by fish-ball** [comment]
I've work out that the maven https ceritficate is ok, while the `jcenter.bintray.com` certificate is not correct.

```
Error: /home/alfred/app/bomeiyi-cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.2.0.
     Required by:
         :android:unspecified
      > Could not resolve com.android.tools.build:gradle:2.2.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

So how to work for this site?

**Comment by SherlockStd** [comment]
I check your error in less than one hour and Côme back to you :)



Le 24 nov. 2016 04:56, à 04:56, Alfred Huang <notifications@github.com> a écrit:

**Comment by SherlockStd** [comment]
@fish-ball sorry for late, if you look at [this comment](https://github.com/meteor/meteor/issues/6362#issuecomment-189852076) on this issue, you'll see the exactly same issue than the one you get.

Have you tried to follow [my solution](https://github.com/meteor/meteor/issues/6362#issuecomment-189852511) but this time on the jcenter.bintray.com certificate ?
