### ISSUE TITLE
DDP Invalid State Error (INVALID_STATE_ERR)

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#6365]
Not 100% sure what's going on here or how to go about resolving it but over the last few weeks we've had a couple of times where **all our servers have been taken out (inadvertently) by a single user**.

What happens is:
* CPU usage rises on one or more of our load-balanced servers
* Our logs show hundreds of consecutive 'Successful login for X' messages where X is the same user
* Kadira error logging shows hundreds of `INVALID_STATE_ERR` client-side errors that correspond with the time
* After ~20/30 minutes all our monitoring goes crazy because we're now at 100% cpu on all the servers.

From Kadira we can see that it always seems to be a Windows 7 + IE9 combo so I assume this is an IE9 compatibility issue with SockJS or at least the way SockJS is connecting to our setup. I wish organisations would just upgrade their software but that's a whole 'nother issue :weary:  

Some things to note:
* The hundreds of 'Successful login for X' messages are the just the successful ones, many more are being blocked by the DDPRateLimiter (default settings).
* The servers never recover even after the user leaves the site. Currently 2 of our 3 app servers have been at 100% CPU for 2.5 hours. The only solution is to restart the app in PM2, which I will do shortly, I wanted to see if the servers would recover but they haven't.

Obviously there are solutions like just blocking/redirecting IE9 at the load balancer (haproxy) level or with nginx which sits in front of each app server but that seems a tad heavy handed.

Any similar experience or advice would be much appreciated. The relevant code in Meteor is https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/ddp-client/sockjs-0.3.4.js where there's three place that `INVALID_STATE_ERR` can be thrown...

**Comment by zol** [comment]
Hey, thanks for reporting this. I'm going to close this out as we're not going to be able to action this but at least others will be able to see your observations.

**Comment by mjmasn** [comment]
Just to follow up, it turned out to be a mixture of issues including a reactive feedback loop where we had used `reactivePublish` that was depending indirectly on the User object, and were also updating that User object each time the user logged in. With IE9 and other polling clients or clients with bad connections that was causing lots of publications to be triggered, and then further reactive updates to those publications on every reconnect. We were also using cookie based sticky sessions with HAProxy but it seemed the cookie wasn't being sent with every request from IE9, I think due to the way SockJS handles the lack of websocket support. This was causing the xhr url to return a 404 two-thirds of the time (we have 3 load balanced servers) and yet more reconnects to happen (like thousands of reconnects). We've switched to source IP based sticky sessions, and now only update the user if it hasn't been updated in the past 60 seconds.

Leaving this here in case anyone has similar problems. I was expecting using `reactivePublish` would burn us at some point but was lulled into a false sense of security by a number of months with no issues!

**Comment by ratiofu** [comment]
FWIW, I am seeing the behavior on our app when Googlebot hits the site. Still figuring out what to do about it.

**Comment by elie222** [comment]
Any updates here? Also seeing this behaviour

**Comment by dr-dimitru** [comment]
We're experiencing the same issue, looks like happens on Chrome at Windows and Android (*error log for last 30 days*):
```
Uncaught Error: INVALID_STATE_ERR. | Chrome Mobile 41.0 | Nexus 5X 0.0 | Android 6.0
Uncaught Error: INVALID_STATE_ERR. | Chrome 41.0 | Linux 0.0
Uncaught Error: INVALID_STATE_ERR. | Chrome Mobile 61.0 | Nexus 5 0.0 | Android 6.0
Uncaught Error: INVALID_STATE_ERR. | Chrome 61.0 | Windows 7 0.0
Uncaught Error: INVALID_STATE_ERR. | Chrome Mobile 61.0 | Nexus 5 0.0 | Android 6.0
Uncaught Error: INVALID_STATE_ERR. | Chrome Mobile 41.0 | Nexus 5X 0.0 | Android 6.0
Uncaught Error: INVALID_STATE_ERR. | Chrome 41.0 | Linux 0.0
```

**Comment by elm2178** [comment]
I am also experiencing this same issue. It seems like it is safe to ignore but it would be great to get some more information on what is causing this and any potential workarounds for it.

**Comment by dr-dimitru** [comment]
@elm2178 agree.
Hopefully, @benjamn or @abernix could tell us their opinion.

**Comment by Floriferous** [comment]
Might have to reopen this one, I keep seeing this error in our production logs. Here's one from a minified error stack:

```sh
Error: INVALID_STATE_ERR
   at T.prototype._didClose (https://www.e-potek.ch/bd2798b37a7f14a406bce526308844561c29075b.js?meteor_js_resource=true:59:15175)
   at Anonymous function (https://www.e-potek.ch/bd2798b37a7f14a406bce526308844561c29075b.js?meteor_js_resource=true:59:18963)
   at onfinish (https://www.e-potek.ch/bd2798b37a7f14a406bce526308844561c29075b.js?meteor_js_resource=true:59:20192)
   at a.prototype.emit (https://www.e-potek.ch/bd2798b37a7f14a406bce526308844561c29075b.js?meteor_js_resource=true:59:1791)
```

**Comment by ZackLeonardo** [comment]
+1

**Comment by po-jo** [comment]
+1

**Comment by idanwe** [comment]
@Floriferous did you find a solution ?

**Comment by Floriferous** [comment]
No, we had to write a custom line to ignore this error in all our error logs, very annoying!

**Comment by idanwe** [comment]
I notice users that have this error and then a few seconds after log out of the system.
What did happen in your case?

**Comment by TheKidCoder** [comment]
We're still seeing this issue, it is not at all related to IE9.

**Comment by paulincai** [comment]
I am also seeing plenty of these. One other thing I noticed. I push a new bundle to the server (AWS) and my scores in Google Speed test is 98% for mobile and 100% for desktop. Couple of days later, same bundle (in dev, no users) 16-30% mobile, and 60% desktop. Other speed test resources still show 98-100% optimization. It seems to be something particularly related to Google indexing (at least in my case).

![Screen Shot 2019-07-31 at 23 12 08](https://user-images.githubusercontent.com/26188915/62240735-aabfec80-b3e8-11e9-9aa2-f243913df597.png)

**Comment by paulincai** [comment]
> @elm2178 agree.
> Hopefully, @benjamn or @abernix could tell us their opinion.
@benjamn or @abernix might have replied on this somewhere...
