### ISSUE TITLE
Docs site crashes iOS browsers

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6367]
When loading http://docs.meteor.com/#/full

### Chrome

1. page loads fine
2. tap hamburger
3. crash [1]

### Safari

1. after the blue loading bar completes and before page content is displayed, you get the crash notification on the top of the screen [2], and the page reloads (this process loops)

[1] ![2016-02-29 12 23 55](https://cloud.githubusercontent.com/assets/251288/13402915/80d674b0-dee0-11e5-80a4-15be663f275e.png)

[2] ![2016-02-29 12 24 57](https://cloud.githubusercontent.com/assets/251288/13402914/80d589a6-dee0-11e5-929c-869f5be1e72a.png)

Old related: #2263

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this on an iPhone 6S running iOS 9.2.1. What device/version are you experiencing these crashes on?

**Comment by lorensr** [comment]
If it's a memory issue, then perhaps that's because 6S has 2 GB RAM and my 6+ (9.2.1) has 1 GB? It's one of the largest-memory tabs on Mac Chrome – 260 MB.

**Comment by lorensr** [comment]
Also crashes Moto X Android v5.1 (2 GB) Chrome, iPhone 4S v8.4 (512 MB).

![screenshot_2016-03-01-10-00-15](https://cloud.githubusercontent.com/assets/251288/13430927/3c5008c8-df95-11e5-9130-63c78196cbd4.png)

(I selected "wait", and after a minute, the alert reappeared)

**Comment by martijnwalraven** [comment]
I suspect app cache limits may have something to do with it. It is over 5mb, which generates a warning but hasn't let to any trouble so far, or at least I thought.

**Comment by lorensr** [comment]
Fixed, thank you @tmeasday
