### ISSUE TITLE
Provide Meteor.getConnection on server

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6369]
I've worked on a couple of packages that needed connection-level data on the server. I stored the data on the `connectionHandle`, but in order to access it, I had to require the package users to keep track of the original Method's `this` so they could pass it to my package functions. In one case, there were 5 levels of function calls between the app's Method and where it called my package function, which is a lot of extra `methodContext` parameters scattered around. Here is the single-level case:

```coffeescript
Meteor.methods
  foo: ->
    SomePackage.bar this

SomePackage.bar = (methodContext) ->
  connection = methodContext.connection
  connection.myData = 1
```

If feasible, it would be nice to be able to access the current DDP connection without passing it around:

```coffeescript
Meteor.methods
  foo: ->
    SomePackage.bar()

SomePackage.bar = ->
  connection = Meteor.getConnection()
  connection.myData = 1
```

Currently, I can see `Meteor.server.sessions.*.connectionHandle` on the server, but I don't know which is mine.

`connectionHandle` def: https://github.com/meteor/meteor/blob/b13bed66c37ddd203e63fd4416a40e10333f2940/packages/ddp-server/livedata_server.js#L279

**Comment by lorensr** [comment]
Looks like it's available at `DDP._CurrentInvocation.get().connection`. Perhaps it's worth adding to the public API / full docs? It might prevent people from using roundabout solutions like the one I used, or heavyweight solutions like this: https://github.com/erasaur/server-session/blob/master/lib/server-session.js#L67-L78

**Comment by zol** [comment]
Hey there. Thanks for your suggestion. We're actually moving away from magic gloabls in favor of imports/exports and explicit argument passing.

**Comment by lorensr** [comment]
@zol Could it be reopened under the new title? The main issue isn't how it's accessed, but documenting it, whether it's `DDP._CurrentInvocation.get().connection` or `connection = import 'foo'`.

**Comment by zol** [comment]
I'd rather not document this case specifically as we don't recommend it.
