### ISSUE TITLE
[meteor 1.3-beta11] improve hot code push trigger/usability on mobile

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6371]
When a hot code push is triggered, by default the page is just refreshed. This is representative of a screen 'blink' followed by the display of the new code.

This method is slightly invasive and doesn't provide a good user experience on a native mobile app. It feels more like a web experience rather than a native mobile experience.

Couple options:
- When a hot code push update is received, the trigger would show the splash screen until all of contents are downloaded. This is the most common update method I've seen in native app updates. Then the resulting page is shown.
- Be able to specify a loader route or component. So the user would be sent to this route just during content downloading/refreshing. Specify enter/leave routes. This would allow us to fade in/out whatever we wish when contents are being downloaded and then subsequently reloaded.
- If a user downloads the app, and since the mobile build has been in the app store there are one or two hot code pushes, the app will load then follow with a 'blink'. This is a very bad experience for a new user who just downloaded the app. The splash screen should not go away until it is confirmed that all hot code pushes since the mobile build have been downloaded & applied. The same thing should happen on app resumes when the splash screen is shown. 

re: https://github.com/meteor/meteor/issues/6266

**Comment by martijnwalraven** [comment]
Downloading of hot code pushed updates always happens in the background. So a splash screen or loader route wouldn't add much (you can just continue using the app while it is downloading). The page reload itself is unavoidable is you want to update a running app. Alternatively, you can use [mdg:reload-on-resume](https://github.com/meteor/mobile-packages/tree/master/packages/mdg:reload-on-resume) to only reload while the app is in the background, so you avoid a visible 'blink'.

**Comment by markoshust** [comment]
Thanks @martijnwalraven, I wasn't aware that module still worked with 1.3.
