### ISSUE TITLE
1.3 beta 11 - Build process hangs using cordova-sqlite-storage

### ISSUE THREAD

**Issue by oliverlloyd** [meteor/meteor#6374]
`1.3 beta 11` Builds hang when using the `cordova-sqlite-storage` package.

```
$ meteor create sqlite-test
$ cd sqlite-test
$ meteor add cordova:cordova-sqlite-storage@0.7.10
$ meteor add-platform ios
$ meteor update --release 1.3-beta.11
$ meteor build /tmp/build --server localhost
   Building for web.browser                  \
```

The meteor process is then stuck at 100% cpu and has to be killed. Same thing happens when using `cordova-sqlite-storage@0.8.2`. Works using `Meteor 1.2.1`.

So, sure, it's likely this plugin doesn't support the latest Cordova version but I'm surprised the meteor process hangs like this.

It's worth mentioning that if I include this plugin via the `raix:localstorage` package it doesn't hang and I get this error:

```
The following build commands failed:
  CompileC build/MyProject.build/Release-iphonesimulator/MyProject.build/Objects-normal/i386/SQLitePlugin.o MyProject/Plugins/io.litehelpers.cordova.sqlite/SQLitePlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
=> Errors executing Cordova commands:

   While building Cordova app for platform iOS:
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/oliver/Code/myproject/.meteor/local/cordova-build/platforms/ios/cordova/build-release.xcconfig,-project,MyProject.xcodeproj,ARCHS=i386,-target,MyProject,-configuration,Release,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/oliver/Code/myproject/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/oliver/Code/myproject/.meteor/local/cordova-build/platforms/ios/build/sharedpch
```

**Comment by martijnwalraven** [comment]
Could you try this with `--verbose` to see where exactly this happens and whether there are any errors? 

Also, I vaguely seem to remember there being an issue with building in `/tmp` at one point. Are you sure this only occurs when you add the plugin? Could you try building in a different location?

**Comment by oliverlloyd** [comment]
Okay, so I just tried again (with verbose) using beta 12 and it now happily throws an error. The same `Error code 65` one I give above that I saw using `raix:localforage`. Oddly, I then tried downgrading to beta 11 thinking this was the cause but this also works now (throws an error properly).

I take it this error means this plugin doesn't support the latest versions of Cordova?

**Comment by martijnwalraven** [comment]
Using 'meteor run ios-device' and building in Xcode, `cordova-sqlite-storage@0.7.10` generates an error that is indeed a result of changes to Cordova iOS. But I am able to successfully build with `cordova-sqlite-storage@0.8.2`, also with `meteor build`. Could you give that another try?

**Comment by oliverlloyd** [comment]
Hey, you're right. It works with 0.8.2! No idea why it was hanging before. Sorry, I only wanted to check newer versions of the package against the one used by raix:localforage to help update that package but I guess something got corrupted and confused things. Hot fur dammer.
