### ISSUE TITLE
mdg:validated-method no longer works with check()

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6378]
I'm using 1.3 beta 11. Not sure when this issue cropped up, but it used to work.

```
export const deleteUser = new ValidatedMethod({
  name: 'deleteUser',

  validate(userId) {
    console.info('checking userid validity');
    check(userId, String);
  },

  run(userId) {
    console.info('Deleting user ID:', userId);
  }
});
```

If I pass an object instead of a string, nothing happens; no error is thrown.

**Comment by stubailo** [comment]
> If I pass an object instead of a string, nothing happens; no error is thrown.

Can you give some specific examples of things you passed in where the error didn't work?

Seems like this could be related to https://github.com/meteor/meteor/pull/6148

If so, we should fix this before 1.3. But it would be good to have a clearer reproduction.

**Comment by ffxsam** [comment]
I can't reproduce it in a fresh Meteor project, it works as expected. But in this project I'm working on, I have the following:

```
export const editUser = new ValidatedMethod({
  name: 'editUser',

  validate(user) {
    console.log('validating user:', user);
    check(user, {
      username: Number,
    });
  },

  run(user) {}
});
```
I get the console.log statement, so I know it's getting there. And I'm definitely passing a user object with username as a string, but the check doesn't throw an error.

**Comment by tmeasday** [comment]
Hey @ffxsam have you tried stepping through with a debugger?

If the line is logging I suspect the problem isn't really in validated-method; perhaps it's in check. Have you overridden it in your project somehow?

I've tried reproducing without success.

**Comment by ffxsam** [comment]
Well, this is odd! It suddenly started working. I have no idea what changed or what happened.

Consider this mysteriously resolved. ;)
