### ISSUE TITLE
Move example apps into their own repo and update the tool to tell you to clone it

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6379]
***1 Upvote*** We should just hardcode the tool so that we get

```
$ meteor create --example todos
Please clone the repository from https://github.com/meteor/todos
```

**Comment by stubailo** [comment]
:+1: love it! One more option - create a git org called `meteor-examples` and then just `git clone github.com/meteor-examples/${stuff}`

**Comment by stubailo** [comment]
But I don't know if the proliferation of GitHub orgs would be a good thing. Maybe `github.com/meteor/example-${name}`.

**Comment by tmeasday** [comment]
Yeah I prefer the second. I think I'll rename the todos repository.

Re: the three simple todos examples (and similarly the (now two) full todos examples). Are we best having a single repo for these w/ branches? Or 3 separate repos?

**Comment by stubailo** [comment]
Hmm, I guess the question is do we want to unify the issues for the repos?

**Comment by tmeasday** [comment]
The nice part we get for free out of this is we can now create a meteor/example-boilerplate repository.

**Comment by tmeasday** [comment]
Unifying issues and being able to cherry pick non-UI specific commits I think are great benefits.

Downsides are making harder to clone and perhaps more confusing.
