### ISSUE TITLE
[1.3-beta.12] [modules] CommonJS require statements return undefined for circular references

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor/meteor#6381]
I’ve been working with @avital to figure out how to work with Meteor 1.3’s modules in CoffeeScript (and by extension, with any other language that compiles to ES5 JavaScript). In that effort, I’ve ported @tmeasday’s [todos](https://github.com/meteor/todos) example app (from commit ca3ab0b8c6aa1a66fcf1c551862ccb07bbd42f3a, which was the latest when I forked) into CoffeeScript. The idea was to demonstrate how to work with modules in CoffeeScript in a non-trivial app. My port is [here](https://github.com/GeoffreyBooth/todos-coffeescript).

It turns out that CommonJS works very, very well as a replacement for ES2015 `import`/`export`. Code like this:
```js
import { AccountsTemplates } from 'meteor/useraccounts:core';
import '../imports/startup/client/routes.js';
```

can be written in CoffeeScript like this:
```coffee
{ AccountsTemplates } = require 'meteor/useraccounts:core'
require '../imports/startup/client/routes.coffee'
```

which looks great to me, and I’ve been helping @avital write documentation to explain it. There’s just one issue though: circular references work in ES2015, but fail in CommonJS. And such a thing actually happens in the `todos` app, in [lists.js](https://github.com/meteor/todos/blob/master/imports/api/lists/lists.js) and [todos.js](https://github.com/meteor/todos/blob/master/imports/api/todos/todos.js). If you look at the top of [`lists.coffee`](https://github.com/GeoffreyBooth/todos-coffeescript/blob/master/imports/api/lists/lists.coffee), it imports [`todos.coffee`](https://github.com/GeoffreyBooth/todos-coffeescript/blob/master/imports/api/todos/todos.coffee):
```coffee
{ SimpleSchema } = require 'meteor/aldeed:simple-schema'
{ Factory } = require 'meteor/factory'
{ Todos } = require '../todos/todos.coffee'
```

And the top of `todos.coffee` imports `lists.coffee`:
```coffee
incompleteCountDenormalizer = require './incompleteCountDenormalizer.coffee'
{ SimpleSchema } = require 'meteor/aldeed:simple-schema'
{ Factory } = require 'meteor/factory'
{ faker } = require 'meteor/dfischer:faker'
{ Lists } = require '../lists/lists.coffee'
```

So [`lists.coffee`](https://github.com/GeoffreyBooth/todos-coffeescript/blob/master/imports/api/lists/lists.coffee) requires [`todos.coffee`](https://github.com/GeoffreyBooth/todos-coffeescript/blob/master/imports/api/todos/todos.coffee), which requires *`lists.coffee`!* Somehow this works in the original, ES2015 version, but fails in the CoffeeScript CommonJS version. Within `todos.coffee`, `Lists` is undefined. But in other files that import `lists.coffee`, `Lists` is an object of class `ListsCollection` like you would expect it to be. I’ve added some `console.log` statements to demonstrate this (clone the [repo](https://github.com/GeoffreyBooth/todos-coffeescript), run `meteor`, and look in the console in your browser when you go to http://localhost:3000). You can prove that the circular reference is causing the problem by commenting out `lists.coffee` line 3 (where it imports `todos.coffee`): suddenly `require '../lists/lists.coffee'` returns an object again in `todos.coffee`, as it should.

This is compounded by the fact that the `coffeescript` build plugin doesn’t pass its output to the `ecmascript` plugin, so using true ES2015 `import`/`export` statements within backticks is not an option. But that’s a [separate issue](https://github.com/meteor/meteor/issues/6000).

**Comment by ndarilek** [comment]
I wonder if this is at all related to #6364? The failing behaviors sound somewhat similar. It uses ES2015, but I too get `undefined` when importing an ES2015 export. The reproduction uses mantra-core which I can't remove and preserve the bug, but maybe module use works fine on the surface but breaks down somewhere deeper in the stack (I.e. mantra-core in my case, coffeescript in this one.)

**Comment by benjamn** [comment]
You're running into one of the drawbacks of CommonJS `require`—or, to put it more positively, one of the advantages of ES2015 `import` and `export`.

An `import` statement like
```js
import { SimpleSchema } from 'meteor/aldeed:simple-schema';

function later() {
  let schema = new SimpleSchema();
  ...
}
```
is not identical to a `require` declaration like
```js
let { SimpleSchema } = require('meteor/aldeed:simple-schema');

function later() {
  let schema = new SimpleSchema();
  ...
}
```
What the `import` version is actually doing is something more like
```js
var _aldeedSimpleSchema = require('meteor/aldeed:simple-schema');

function later() {
  let schema = new _aldeedSimpleSchema.SimpleSchema();
  ...
}
```
Referring to `_aldeedSimpleSchema.SimpleSchema` allows the source module time to resolve any circular dependency cycles, whereas saving a reference to the `SimpleSchema` symbol immediately after calling `require` means your code will use that (possibly not yet initialized) value forever.

Here's a [talk](http://benjamn.github.io/empirenode-2015/#/12) I gave last year that touches on these problems and their solutions. **tl;dr** If you're stuck using CommonJS `require`, you can approximate the benefits of ES2015 `import` by following [this discipline](http://benjamn.github.io/empirenode-2015/#/31).

Here's an [example](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=import%20%7B%20SimpleSchema%20%7D%20from%20'meteor%2Faldeed%3Asimple-schema'%3B%0Alet%20%7B%20Factory%20%7D%20%3D%20require('meteor%2Ffactory')%3B%0A%0Afunction%20callLater()%20%7B%0A%20%20let%20schema%20%3D%20new%20SimpleSchema()%3B%0A%20%20let%20factory%20%3D%20new%20Factory()%3B%0A%7D) you can play with in the Babel REPL.

**Comment by GeoffreyBooth** [comment]
@benjamn thanks for your detailed response and links. I found [this slide](http://benjamn.github.io/empirenode-2015/#/31) particularly helpful. For future visitors to this page, here’s how I managed to solve this problem:

So instead of `lists.coffee` referencing `todos.coffee` like this (and `todos.coffee` doing the inverse, which creates the circular reference):

```coffee
{ Todos } = require '../todos/todos.coffee'

class ListsCollection extends Mongo.Collection
  remove: (selector, callback) ->
    Todos.remove {listId: selector}
```

I instead referenced the root _object,_ i.e. the object exported by `module.exports`, not its property `module.exports.Todos`:

```coffee
TodosModule = require '../todos/todos.coffee'

class ListsCollection extends Mongo.Collection
  remove: (selector, callback) ->
    TodosModule.Todos.remove {listId: selector}
```

When the code is initially parsed by the browser or Node runtime, the object defined by `module.exports` exists but the property `module.exports.Todos` is undefined. But that property _is_ defined by the time we run that `remove` function, since that doesn’t get called until after all code has been parsed; and by saving the reference to the parent object that does exist (`TodosModule`) and looking for its property only later, rather than saving a reference that resolves to `undefined` at parse time and never gets updated (`{ Todos }`), we workaround the circular-reference limitation of CommonJS. This solution is a little more verbose than would be ideal, but it solves the problem; and this is only necessary for modules that create circular references. All of my other `require`s look just like their ES2015 counterparts. [Full code](https://github.com/GeoffreyBooth/todos-coffeescript/blob/63985e652f448f921faf3159b045be0e49ea9353/imports/api/lists/lists.coffee).

**Comment by mrmowgli** [comment]
This issue is still kicking around in the 1.3.4+ versions of Meteor.  The todos coffeescript branch breaks again after updating to the new version when inserting a new todo.

In the file: `incompleteCountDenormalizer.coffee` both `ListsModule` and `TodosModule` requires return empty objects.  This DOES work in the original version of the branch, so something has changed to break this in later versions of Meteor.

**Comment by benjamn** [comment]
@mrmowgli I [commented](https://github.com/meteor/meteor/issues/7459#issuecomment-234725177) on the issue you opened, but for anyone else who comes across this issue, the official recommendation is to use `import` and `export` instead of `require` and `exports` in your `.coffee` files, which has been possible since Meteor 1.3.3 thanks to @GeoffreyBooth's work in #6691.

**Comment by GeoffreyBooth** [comment]
Hi @benjamn, shouldn't we still get to the bottom of this issue? Clearly if it worked in 1.3.3 and broke in 1.3.4 it's a bug, and there should be a test to catch it. Who knows what else might be affected until we investigate.
