### ISSUE TITLE
[1.3-beta.12] Long Build Times with package using ecmascript and big js files (not api.use()'d) in the package

### ISSUE THREAD

**Issue by DanielDornhardt** [meteor/meteor#6384]
Hi! :)

I'm running on the latest Beta on Mac.

I was trying to create a package for wrapping a big vendor library, namely OpenLayers.

When trying to add the files as assets to a new local package, I noticed build times going through the roof. Actually it looks like it's stuck and only a `killall -9 node` seems to be able to stop the process.

This is _before_ adding the files via either addFiles nor addAssets.

Trying to whittle down the issue further, I can see that it starts producing the error when using the ecmascript package inside the same package ( eg. `api.use(["ecmascript"], 'client');`).

I would have expected the ecmascript package to leave alone any files not explicitely added to the package?

Reproduction Repo: https://github.com/DanielDornhardt/meteorIssueEcmascriptInPackagesExample

To make it start / build again, remove the line `api.use(["ecmascript"], "client");` from the file packages/testpackage/package.js .

The same thing happened with 1.3-beta.11 by the way.

Also, I removed the .css - File from the vendor folder, and that doesn't change a thing. Also renaming the folder containing the file to something without dots, dashes and other things didn't help either.

Using `api.addAssets(["vendor/openlayers/ol.js"], "server");` didn't help either either.

Using api.use() would of course be nice too to have only a single file being delivered by meteor :) But the build times would have to be snappy of course! :D

Thanks and best wishes

Daniel :)

**Comment by benjamn** [comment]
I'm hoping https://github.com/meteor/meteor/commit/ad3f56a0bf0de4f28a2476a83f5b695e3ab1d1a0 helps somewhat with this (available in `1.3-rc.1`).

**Comment by hwillson** [comment]
Meteor 1.4.2 introduced many new build tool performance improvements. Please try your app with the latest version of Meteor and post back if you're still having issues. Closing for now - thanks for reporting this originally!
