### ISSUE TITLE
lib sass not found - node-sass

### ISSUE THREAD

**Issue by hoscb** [meteor/meteor#6385]
I'm using the new meteor 1.3 beta 12 release and I'm doing an npm import for node-sass.

`import nodesass from 'node-sass'`

When I run meteor, I receive this error:

> W20160302-14:34:54.547(0)? (STDERR) /home/vagrant/.meteor/packages/meteor-tool/.1.1.13-beta.12.xtqt6a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
> W20160302-14:34:54.547(0)? (STDERR)             				throw(ex);
> W20160302-14:34:54.547(0)? (STDERR)             				      ^
> W20160302-14:34:54.550(0)? (STDERR) Error: The `libsass` binding was not found in /node_modules/node-sass/vendor/linux-x64-11/binding.node
> W20160302-14:34:54.550(0)? (STDERR) This usually happens because your node version has changed.
> W20160302-14:34:54.551(0)? (STDERR) Run `npm rebuild node-sass` to build the binding for your current node version.

I have been trying to solve this problem for the past few days but with no avail.

I ran `npm rebuild node-sass` and its shows me this:

> node-sass@3.4.2 install /vagrant/node_modules/node-sass
> node scripts/install.js
> node-sass@3.4.2 postinstall /vagrant/node_modules/node-sass
> node scripts/build.js
` /vagrant/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 /vagrant/node_modules/node-sass

A little info of my platform:
- Mac OS running with vagrant
- Node v5.6.0
- Npm v3.6.0
- n v2.1.0
- nodejs v0.12.10
- node-sass v3.4.2

I have both node-sass install locally and globally. I would appreciate you guys point me to the right direction. Thanks!

**Comment by stubailo** [comment]
I don't think Meteor 1.3 supports NPM packages with binary dependencies... @benjamn?

If you want to compile SASS files in your Meteor app, we suggest using one of the packages from Atmosphere, since that's the only way to integrate with the Meteor build system.

See here: http://guide.meteor.com/build-tool.html#sass

**Comment by benjamn** [comment]
This is fixed in `beta.16`, thanks to #6398, though you may have to `npm install node-sass` with the same version of `npm` (and `node`) that Meteor uses (1.4.29 and 0.10.41). Let me know if you have trouble figuring out how to do that.
