### ISSUE TITLE
How to downgrade from 1.3 correctly? I tried to reinstall whole meteor.

### ISSUE THREAD

**Issue by Hongbo-Miao** [meteor/meteor#6387]
I updated to meteor 1.3 by using:
```
meteor update --release 1.3-modules-beta.8
```
But I decided to downgrade. So I deleted all files by using:
```
rm -rf ~/.meteor/
sudo rm /usr/local/bin/meteor
```
And install again by
```
curl https://install.meteor.com/ | sh
```

But now it still shows:
> Uncaught TypeError: Cannot read property 'System' of undefined

![qq20160302-0](https://cloud.githubusercontent.com/assets/3375461/13477812/218b7ee8-e09c-11e5-8bbe-d1f75a7a3ab6.png)

**Comment by Hongbo-Miao** [comment]
After I restarting my system, Meteor 1.2.1 is back to work! Ha

**Comment by Hongbo-Miao** [comment]
After I restarting my system, Meteor 1.2.1 is back to work! :P

So what I wrote down in the first way is a way to downgrade the version.
Hope this can help others who meet similar problems.

**Comment by edvinsalo35** [comment]
I also need to downgrade meteor from 1.3 to 1.2.1.
But now, the 1.3 is became normal version, so I cannot think your way is now working. 
How can I handle this problem?

**Comment by Hongbo-Miao** [comment]
@edvinsalo35  I would recommend you create a new issue and ask.
