### ISSUE TITLE
"peer" npm dependencies are not bundled to the client if the app does not require them.

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6390]
Reference case: the `react-runtime-dev` package I'm working on here: https://github.com/meteor/react-packages/pull/171.

This package now basically does `React = require('react')`, and checks that the user has installed react with http://atmospherejs.com/tmeasday/check-npm-versions. 

The problem is that React is not bundled client-side from `node_modules` because no app code `import` it. You can resolve the issue by adding `import 'react'` at some random place in your app client side code.

I guess we could require the users of such packages to do that, but will seem awfully weird I imagine.

**Comment by benjamn** [comment]
We do collect missing imports from packages and make sure the app includes the appropriate modules (even if nothing in the app imports those modules), but perhaps that code is ignoring `debugOnly` packages? [This](https://github.com/meteor/meteor/blob/081c5b64461a283f6abafe8beeeaa06ca7ac91a0/tools/isobuild/compiler-plugin.js#L602) would be the offending line, if so.

**Comment by tmeasday** [comment]
Ok, it turns out the reason this was happening was that I had installed a `node_modules` directory *inside* the package (in an attempt to try and figure out if it was possible to do `test-packages` for such an app, basically trying to solve #6391).

So this one is NOTABUG. But I'll continue to investigate for #6391
