### ISSUE TITLE
Meteor 1.3 beta-12, npm installing Aurelia does not work

### ISSUE THREAD

**Issue by Markusxmr** [meteor/meteor#6394]
Greetings,
Steps taken:
- Initiated a clean Meteor 1.3 project with a package.json file on Mint 17.3,
- npm installed aurelia-bootstrapper and aurelia-framework and saved it to package.json,
- in the client folder in the main.js file imported aurelia-bootstrapper, to kickstart the framework,
then after starting meteor app, console logs: 
``
Uncaught (in promise) TypeError: id.charAt is not a function(…)   modules-runtime.js:327 
``
![err](https://cloud.githubusercontent.com/assets/10939097/13488422/5ce9c730-e121-11e5-8425-1ff66b328a73.jpg)

Can't locate where the issue is specifically...

**Comment by benjamn** [comment]
My guess is that it's coming from [this line](https://github.com/aurelia/bootstrapper/blob/7185af3779d6c1bc472ff5187c742a3c96a5d909/dist/commonjs/aurelia-bootstrapper.js#L66-L68). That's the AMD asynchronous `require` style, which we don't currently have any plans to support. You might be able to get it to work by using another library to define `window.require`, though I'm not sure what to recommend.

**Comment by Markusxmr** [comment]
Ok. Thank you for checking into it.

**Comment by abernix** [comment]
Closing because of the above reasons!

**Comment by foobarbecue** [comment]
I'm running into this with [Cesium](http://cesiumjs.org). I guess a significant proportion of the npm ecosystem is unusuable due to this issue.
