### ISSUE TITLE
[1.3-beta.12] Build stuck at "Building for os.osx.x86_64" when NPM depending on "soap"

### ISSUE THREAD

**Issue by quintstoffers** [meteor/meteor#6395]
Sample repository here:
https://github.com/quintstoffers/meteor-soap-build

When building an app using a package that depends on the NPM library "soap" it'll succeed the first time, but hang with the following output the second time the app is built:
```
Quints-MBP:meteor-soap-build quint$ meteor
[[[[[ ~/development/meteor-soap-build ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
   Building for os.osx.x86_64                -
```
Removing the package's `.npm` directory that is created after the first build allows for another build. Needless to say removing the directory each build is a bit cumbersome.

**Comment by zol** [comment]
Thanks for the repro!

**Comment by zol** [comment]
This should be fixed in rc4.
