### ISSUE TITLE
Meteor 1.3 overrides process.env.NODE_ENV on server

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#6399]
In the current beta (1.3-beta.12) the `process` package unconditionally overrides `process.env.NODE_ENV` on the server to `development` or `production` even if you explicitly set `NODE_ENV` to something when you run the server.  @benjamn suggests that it should not override explicitly set values.

There's then a second question of whether, if you set `NODE_ENV` to a custom value, if that should also fill in the new client-side `process.env.NODE_ENV` polyfill, or if it should stay as always `development`/`production`.  (Via `__meteor_runtime_config__` or something.)

**Comment by benjamn** [comment]
This is fixed in `beta.16` (and we're even propagating the server's value to the client!).

**Comment by sajhu** [comment]
hello, 

Im deploying to galaxy in this moment and Im getting the same problem. my staging environment says I'm in production both in Meteor.isProduction and process.env.NODE_ENV
