### ISSUE TITLE
Figure out a way to run package tests for packages with peer dependencies

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6401]
Due to the way that `meteor test-packages` works (makes a clean app and points the local package dir to the current app), app-level `node_modules/` do not come over to the `test-packages` context. This means packages with "peer" dependencies (like packages that use React) will fail to run in package test mode.

Some solutions: 
 - Encourage such package authors to stub out npm dependencies (not necessarily that helpful).
 - Figure out a way to copy over `node_modules` to the test app.
 - Figure out a way to set the `projectContext` of the test app to have a non-standard `node_modules` lookup (not sure if that makes any sense @benjamn).
 - Something else?

@zol I feel like we need to figure out if we are going to do anything about this one.

**Comment by tmeasday** [comment]
Oh, I figured out a pretty good workaround -- write a scaffolding app, who's tests can be used to test the package. CF https://github.com/meteor/react-packages/commit/54debd94a60ed6429af5ff29cd0fa8f9dd4d9aba

We should probably document this somewhere. I'm beginning to think we need that 'writing packages' guide article.

**Comment by zol** [comment]
Yes, I think a guide article on Packages would be very useful and worth tackling soon.

**Comment by tmeasday** [comment]
Closing this as the plan is simply to document how to do the app-test workaround in the "Writing Packages" guide article.
