### ISSUE TITLE
Winston, Joi are not working in beta 12

### ISSUE THREAD

**Issue by suhail-ansari-apconic** [meteor/meteor#6408]
Winston, Joi not working in beta 12
Version beta 12

Winston gives the following error
W20160304-13:24:39.214(5.5)? (STDERR)         
W20160304-13:24:39.378(5.5)? (STDERR) /home/sansari/.meteor/packages/meteor-tool/.1.1.13-beta.12.jdmeew++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160304-13:24:39.379(5.5)? (STDERR)           				throw(ex);
W20160304-13:24:39.379(5.5)? (STDERR)           				      ^
W20160304-13:24:39.704(5.5)? (STDERR) Error: ENOENT, no such file or directory '/node_modules/pkginfo/lib'
W20160304-13:24:39.704(5.5)? (STDERR)     at Object.fs.readdirSync (fs.js:666:18)
W20160304-13:24:39.704(5.5)? (STDERR)     at Function.pkginfo.find (node_modules/pkginfo/lib/pkginfo.js:95:1)
W20160304-13:24:39.704(5.5)? (STDERR)     at Function.pkginfo.read (node_modules/pkginfo/lib/pkginfo.js:119:1)
W20160304-13:24:39.705(5.5)? (STDERR)     at module.exports (node_modules/pkginfo/lib/pkginfo.js:69:1)
W20160304-13:24:39.705(5.5)? (STDERR)     at meteorInstall.node_modules.pkginfo.lib.pkginfo.js (node_modules/pkginfo/lib/pkginfo.js:132:1)
W20160304-13:24:39.705(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:176:1)
W20160304-13:24:39.706(5.5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160304-13:24:39.707(5.5)? (STDERR)     at meteorInstall.node_modules.winston.lib.winston.js (node_modules/winston/lib/winston.js:14:1)
W20160304-13:24:39.707(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:176:1)
W20160304-13:24:39.707(5.5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)

Joi still cannot find crypto.

Thanks

**Comment by benjamn** [comment]
The issue with `crypto` is fixed in `beta.16` if you `npm install meteor-node-stubs`, but now there's another problem, which is that the `joi` package is only meant to work with [Node >= 4.0](https://github.com/hapijs/joi/blob/93ca39f65e05de1e9dd0043bbf970aebb6e347c6/package.json#L13), so ES2015 syntax like [these `const` declarations](https://github.com/hapijs/joi/blob/93ca39f65e05de1e9dd0043bbf970aebb6e347c6/lib/binary.js#L5-L6) is not legal in Meteor's version of Node (0.10).

Upgrading to Node 4 (or even 5, at this rate) is a high priority after 1.3 is released: https://github.com/meteor/meteor/issues/5124

**Comment by benjamn** [comment]
Forgot to mention: `winston` seems to [work](https://github.com/meteor/meteor/blob/bcad71e95b687aac5dc4b463ef16dfa3fa5811f6/tools/tests/apps/modules/server/only.js#L6) in `beta.16`.

**Comment by suhail-ansari-apconic** [comment]
Well there are two version of Joi that are being maintained. The version 6.x.x can be used for Node < 4.0 while the version 7.x.x should be used for Node >=4.0.

**Comment by suhail-ansari-apconic** [comment]
Thanks for winston though.
