### ISSUE TITLE
High cpu consumption due to images in public

### ISSUE THREAD

**Issue by billaras** [meteor/meteor#6412]
Hello
i am using meteor 1.1.0.1 on windows
i have a problem that causes the meteorjs to take too much cpu consumption always even without any users connected. From the task manager i see the node.exe process that creates the application of meteorjs has a steady around 18-20% cpu consuption at all times even without any users. After reading other issues i have come to realize that the problem is that i have 2 folders with about 1k images inside the public folder. When i remove these 2 folders the consumption drops to 5-6% which is acceptable to me. But when i put the images back it goes to 20% and stays there.

i understand that meteorjs has the file monitor thing that watches files and if something is changed it pushes it to the client. I like this feature and it is extremelly helpful. It is very helpful for the images too. But to take 20% of the cpu is a real problem from my production environment.

I would kinly like to ask what is the solution or possible workarounds in order to keep the meteorjs file watch but has a normal small cpu consumption.
thanks

**Comment by Menda** [comment]
Did you try if upgrading to the last version solves it? Be careful and make a copy of the old version just for testing.

**Comment by billaras** [comment]
i tried upgrading and it says the laterst version of meteor 1.1.0.1 is already installed on this computer... i also did inside the project and it said that it is the latest version. i know that in the meteor page it says that the version is 1.2.1 but is this for all platforms?my platform is windows. has the problem been resolved?

**Comment by stubailo** [comment]
> But to take 20% of the cpu is a real problem from my production environment.

When running a Meteor app in production, you should not use the Meteor tool to launch it. Because clearly when running a production app you don't need stuff like file watching.

Read more about how to run Meteor in production here: http://guide.meteor.com/deployment.html#deployment-options

I'm not sure why upgrading beyond Meteor 1.1.0.1 is not working - 1.2 is in fact much faster. Please open a separate issue about that, with more information about the console output of `meteor update`.

**Comment by billaras** [comment]
Hi thank you for your replies. The link to the deployment options are referring to 
-galaxy (which i do not want to since i want to host it to my own server) 
-meteor up which says (This version is no longer maintaining) and plus it only runs on "Debian/Ubuntu flavours and Open Solaris at the moments" i want for windows 
-Meteor Up X (Development Version) so not for production
-the last option is the custom deployment, are you referring to this option?
i am a bit confused could you please provide some more information?

**Comment by stubailo** [comment]
Yeah, custom deployment. The point is, you should use `meteor build` and run the app with `node` rather than using the Meteor command line tool in production.

**Comment by billaras** [comment]
o i see i didnt do it because it seemed rather complicated. i will have a look at it. i would like to note that i did upgrade to 1.2.1 (there was a conenctivity issue after all) but the cpu consumption is still unchanged

**Comment by billaras** [comment]
i am not familias with the built command but as i understand i must have a nodejs server running and then put the output of the built command into it?thanks

**Comment by stubailo** [comment]
No there isn't an official guide of deployment for dummies, but there might be some blog posts. If you need additional help I would suggest asking on the forums.
