### ISSUE TITLE
Triggered restarts doesn't reset the database when testing

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/meteor#6418]
Running Meteor test --driver--package practicalmeteor:mocha resets the testing database as expected. Hereafter modifying files will trigger the test to restart, but the database won't reset. To reset the database I have to do ctrl + c and then rerun the test.

Originally posted [here](https://github.com/meteor/guide/issues/257#issuecomment-192566476)

**Comment by zol** [comment]
Hey. Thanks for reporting this. We discussed it more internally and the database resetting between runs is a side effect of starting a new app whenever Meteor is run in test mode. Test authors should not rely on this behavior and if they're relying on the database for a test/suite should clear it themselves.
