### ISSUE TITLE
[1.3-beta.12] Workaround for babel configuration stage-x

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#6420]
I am a bit lost on how to configure babel right now as https://github.com/meteor/meteor/issues/6351 states that .babelrc is ignored until post 3.1.

For example how to enable decorator and class properties? (stage-1)

**Comment by mikemurray** [comment]
@dagatsoin unfortunately I think your only option will be to fork both the `ecmascript` and `babel-compiler` packages. I just copied the correct versions for my release into my packages directory.

See this gist for an example: https://gist.github.com/mikemurray/1a98f6ffc75c99c6a65d

This may or may not work for you, as I've only tested class properties and not decorators using the stage-0 preset.

**Comment by dagatsoin** [comment]
Thx @mikemurray but I am a totally noob on Meteor package system. How do you "fork" a package?

**Comment by mikemurray** [comment]
I literally just downloaded the release ( https://github.com/meteor/meteor/releases ), and copied the two folders (ecmascript and babel-compiler) into my packages directory.

**Comment by dagatsoin** [comment]
Ho ok thx you! I am going to try this.

**Comment by dagatsoin** [comment]
do you `meteor remove ecmascript babel-compiler` or it automatic use the ones in the folder package?

**Comment by dagatsoin** [comment]
Ok il automatic uses the one in package folder.
Class properties passes the build but not the decorator. I will try with stage1.

**Comment by mikemurray** [comment]
fingers crossed :smile:

**Comment by dagatsoin** [comment]
```
error: Can't load npm module 'babel-preset-stage-1' from packages/babel-compiler.js. Check your Npm.depends().
```
I just changed `Npm.require("babel-preset-stage-0")` to `Npm.require("babel-preset-stage-1")`

But I don't know what to add in Npm.depends()

**Comment by mikemurray** [comment]
you need to update the Npm.depends in the package.js

**Comment by dagatsoin** [comment]
ho sorry! I forgot this line.

**Comment by dagatsoin** [comment]
No decorator does not pass. Weird.

`lib/classes/player/Player.js:4:7: /lib/classes/player/Player.js: Decorators are not supported yet in 6.x pending proposal update.`

**Comment by dagatsoin** [comment]
do you know if we can use babel plugin with this workarounds? I would like to give a try directly with `babel-plugin-syntax-decorators`

**Comment by mikemurray** [comment]
Can you live without decorators?

**Comment by dagatsoin** [comment]
I use http://mobxjs.github.io/ that use decorators extensively. There is also classic API call without decorators but it is fare more versbose and less elegant.

Next attempt is to use `webpack:webpack` with a more flexible babel config. Hoping that babel config will be a native feature soon in Meteor.

**Comment by mikemurray** [comment]
Hopefully this exercise will help you decide whether its worth while to use the features that are standard, or spend the time and energy to figure out how to enable them.

The only reason I'm using stage-0 at the moment is because I came from webpack app and wanted to quickly convert to meteor. I actually removed all the decorators I had because it wasn't worth the time to hack it in. I'm only using class properties, and intend to remove them if they become a problem.

**Comment by dagatsoin** [comment]
Indeed it was instructive. But I bet on more babel problems to come until Meteor 1.3.1 will be released. So I use `webpack:webpack` and it seems to work well. And it works :)
So workaround for babel stuff until Meteor 1.3.1 ==> https://github.com/thereactivestack/kickstart-meteor-react.
