### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by maartenbusstra** [meteor/meteor#6421]
I really like how you're attaching "-beta" to the minor version (1.3-beta.x). But, TIL it's not allowed by the spec.

[http://semver.org/#spec-item-9](http://semver.org/#spec-item-9)

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately **following the patch version**.

**Comment by stubailo** [comment]
Meteor releases don't follow SemVer, but the individual packages do. Note that we have had releases with numbers like `1.2` and `1.1.0.3` in the past, which are clearly not valid SemVer.
