### ISSUE TITLE
1.3 beta.12 bug - isobuild:compiler-plugin

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#6422]
I'm not able to add more than one js files with `inputFile.addJavaScript`. Seems like the last one is the only one visible in the app.js.
I.e.: 
```JavaScript
inputFile.addJavaScript(js1);
inputFile.addJavaScript(js2);
inputFile.addJavaScript(js3); // Only this file shows up in app.js
```

**Comment by Zodiase** [comment]
To reproduce, simply do:
```JavaScript
inputFile.addJavaScript({
  data: 'console.log("test1");',
  path: 'test1.js'
});
inputFile.addJavaScript({
  data: 'console.log("test2");',
  path: 'test2.js'
});
inputFile.addJavaScript({
  data: 'console.log("test3");',
  path: 'test3.js'
});
```
and then run the app with the package. Only "test3" will show up in console and `app.js` contains only `test3.js`.

**Comment by benjamn** [comment]
This is fixed in `beta.16`. Thanks for noticing this and reporting it!
