### ISSUE TITLE
High CPU usage, using "npm start" script

### ISSUE THREAD

**Issue by maartenbusstra** [meteor/meteor#6425]
Release: 1.3-beta.12
node: v5.4.1
npm: 3.3.12

I've noticed running Meteor from an NPM script uses 175% CPU for me. I like to include command line arguments in the script, but this kind of gets in the way.

Just include this in package.json:
```
"scripts": {
  "start": "meteor",
}
```
...and run `npm start`.

**Comment by maartenbusstra** [comment]
Whoops. Duplicate of #4314. Couldn't find it before I posted this.

**Comment by zol** [comment]
Closing dupe.
