### ISSUE TITLE
Output with npm colors

### ISSUE THREAD

**Issue by kkm** [meteor/meteor#6426]
It does not work anymore. But I am not sure newer version is disabled output colors?

`var colors = Npm.require("colors");
console.log(colors.blue("See blue?"));`

**Comment by stubailo** [comment]
@kkm, thanks for the issue report but it's very hard to tell what you are trying to achieve, and what you mean by it doesn't work anymore. What version of Meteor/`colors` are you using, and which version were you using before? Do you have an example app I can test out to see the result you are experiencing?

I'll reopen if there is a reproduction. Please see the issue template for directions: https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md
