### ISSUE TITLE
Can't use sinon from npm

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6427]
Have run into this yet?

Sinon has the following:

`lib/sinon.js` requires `./sinon/utils/core`, which should include`lib/sinon/utils/core/index.js`. For whatever reason this is failing on both client and server. On the client it appears that nothing apart from `lib/sinon.js` is getting bundled.

I can create a reproduction if you like, it's pretty straightforward (`npm install sinon`; `import 'sinon'`).

**Comment by benjamn** [comment]
This seems like another unintended consequence of https://github.com/meteor/meteor/commit/99cb96fcf76cb08cc389d354ec8ed42ef74e8ae9, like https://github.com/meteor/meteor/issues/6430#issuecomment-193512981.

cc @tmeasday @zol

**Comment by tmeasday** [comment]
Seems fixed. Closing.
