### ISSUE TITLE
Weird case-sensitivity problem in module compilation

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6428]
In the following situation (notice the case mismatch on `b.js`):

```js
import './B.js';
```
[`a.js`]

```js
export const foo = 5;
```
[`b.js`]

The compiled `app.js` includes an uncompiled version of `b.js` (as `"B.js"`), and no version as `"b.js"`, leading to `Unexpected reserved word` exceptions (for the `export`) when running.

Repro: https://github.com/tmeasday/case-sensitivity-repro

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.5`](https://github.com/meteor/meteor/issues/6266#issuecomment-199632139).
