### ISSUE TITLE
Xmllint validateXML() causes Meteor to restart

### ISSUE THREAD

**Issue by CTimmerman** [meteor/meteor#6429]
Meteor 1.2.1 (and/or Meteor 1.0) on Windows 10.

Details and test case here: https://github.com/kripken/xml.js/issues/11#issuecomment-191158626

**Comment by zol** [comment]
Please provide a minimal reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  . Often the act of pairing down your code reveals a different bug or cause for the behavior behind your original report. Being able to clone, run and understand a simple git repository makes it more likely that contributors will take a look at your report.

**Comment by CTimmerman** [comment]
That's okay. I have a workaround.

**Comment by CTimmerman** [comment]
But here's a repo: https://github.com/CTimmerman/meteor-xmllint-bug

**Comment by CTimmerman** [comment]
Should i open a new issue for this?

**Comment by CTimmerman** [comment]
Open issues get the looks. Should be fixed now according to https://github.com/meteor/meteor/issues/6574#issuecomment-201059477

**Comment by Beat-YT** [comment]
I made a fork that fix this problem:

https://github.com/Beat-YT/xml.js
