### ISSUE TITLE
Warn and prevent downgrading

### ISSUE THREAD

**Issue by zol** [meteor/meteor#6431]
Rather than ensure Meteor can downgrade from the current version (tricky in some cases - see #6366) we should: 
1. Prevent the tool from trying to downgrade.
2. Ask for confirmation when running `--update` . Suggested copy is something like: `Warning: You cannot downgrade updated projects. Ensure your source code is backed up before updating. Do you want to continue? Y/N`

**Comment by mjmasn** [comment]
@zol Would it be worth adding a --force option to at least attempt the downgrade? Obviously some kind of version control is the best option but if someone doesn't have a backup and it *is* possible to downgrade it would be silly to prevent them from downgrading entirely.

**Comment by zol** [comment]
Yes, I think that would be reasonable.

**Comment by laosb** [comment]
So, should we disable all downgrades, or only those need to downgrade across a record in `.finished-upgraders`?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Warn%20and%20prevent%20downgrading&body=Migrated%20from:%20meteor/meteor%236431) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
