### ISSUE TITLE
[Request] Please add support for native client(Android/iOS/NodeJs) side meteor sdk

### ISSUE THREAD

**Issue by ChrisOHu** [meteor/meteor#6437]
Hi,

As we develop our app, we found that it's really quite pain to develop in a way client/server highly coupled, especially if each one's responsible for a specific endpoint(server, Android, iOS, browser, .etc).

So I think it would be really great if meteor could officially support native client side SDKs. Also on a strategic level I think it would be really helpful for the meteor community.

Truly & Best Regards,
Chris

**Comment by martijnwalraven** [comment]
To many people, one of the benefits of a full-stack platform like Meteor is actually that you might not need separate responsibilities or teams. This is also why people are so excited about React Native: the same team can now be responsible for developing both iOS and Android version of the app (while sharing a substantial percentage of the code).

Having said that, there are definitely situations where it makes sense to write native apps and have these connect to a Meteor server. You may want to have a look at [this list of DDP clients](http://meteorpedia.com/read/DDP_Clients) developed by the community.

**Comment by ChrisOHu** [comment]
Hi guys~~~ closing this~~

**Comment by martijnwalraven** [comment]
@ChrisOHu: Any particular reason you reopened this?

**Comment by ChrisOHu** [comment]
@martijnwalraven just thought meteor might officially support them, anyway, I'll close this : )

**Comment by luiseduardobrito** [comment]
Is there any native SDKs in the Roadmap?
