### ISSUE TITLE
Allow disabling userId inside the publish function

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6441]
Based on discussion in #4705, I have a concrete proposal: it would be great if there would be a way to disable management of `this.userId` for a publish endpoint, and as a consequence restarting of publish function when `userId` changes.

The reason for this is that for some publish endpoints you know that you are not using `userId` at all inside, so you could mark it as such and publish endpoints would not be restarted.

Moreover, there is now also [server-side reactive publish](https://github.com/peerlibrary/meteor-reactive-publish) so `userId` could simply be done by calling `Meteor.userId()` inside autorun on the server-side:

``` javascript
Meteor.publish(function () {
  this.autorun(function () {
    return Posts.find({authorId: Meteor.userId()});
  });
});
```

(`Meteor.userId` works inside publish function [using this package](https://github.com/peerlibrary/meteor-user-extra).)

Because reactive publish sends only changes it is much more efficient (from the client's perspective) than blindly restarting the whole publish endpoint.

I am not sure about the API, but maybe the second argument could be used for options?

``` javascript
Meteor.publish(function () {

}, {
  noUserId: true
});
```

I know that data level is being moved to GraphQL, but I still think this would be a beneficial change because it would allow one space of experimentation for those who will probably some time be stuck with existing data world.

Edit:

In fact, I am realizing there are two levels of disabling `userId` here.

One is to simply prevent restarting a subscription when `userId` changes. This is what is described above and can help optimize publish function when used with reactive publish (autorun). So in some way, `userId` could be made a reactive variable, and when accessing it, if it changes later on, `autorun` is rerun, but not the whole subscription.

Another case is when you have publish functions which publish the same set of documents for all users (depend only on arguments to the publish function). Then restarting such publish function might not be needed when userId changes. On the other hand, there is an intermediary situation, where userId is used only to check permissions inside publish function, but then published documents are the same for all users.

What I am thinking here is mostly to address the first case. Maybe `userId` could be simply made into a getter which creates a reactive dependency. And if it creates a reactive dependency, then main publish function is not restarted when it changes. And if it did not create a reactive dependency, but was used, then the whole publish function restarts.

**Comment by mitar** [comment]
cc @stubailo: Would this be a pull request/change you would entertain?

**Comment by stubailo** [comment]
`simple:rest` already uses the second argument for options: https://github.com/stubailo/meteor-rest/blob/master/packages/rest/README.md#publications

So that seems like a fine place to put them.

I think whether we would accept a PR for this depends on how complicated the implementation is. Do you have a sense for that?

**Comment by mitar** [comment]
I will edit the description above with some more ideas I got in meantime.

> I think whether we would accept a PR for this depends on how complicated the implementation is. Do you have a sense for that?

I think it is pretty straightforward. We would not pass `userId` in the context, and we would mark it as a publish function which should not be restarted on `setUserId`.

**Comment by mitar** [comment]
My current proposal:

> Maybe userId could be simply made into a getter which creates a reactive dependency. And if it creates a reactive dependency, then main publish function is not restarted when it changes. And if it did not create a reactive dependency, but was used, then the whole publish function restarts.

**Comment by mitar** [comment]
After more thought. I think this is premature optimization. I think sharing subscriptions between logged in and not logged in users is not as common. And publish functions should anyway be very lightweight, mostly just doing ACL and copying data from one source to output. So rerunning should not be very costly, probably as costly as running ACLs again anyway.
