### ISSUE TITLE
Which is the official router for Meteor ?

### ISSUE THREAD

**Issue by hojas** [meteor/meteor#6445]
Which is the official router for Meteor ? iron-router ?

**Comment by helb** [comment]
Well, none. There is no router included with Meteor by default. All of them are third-party packages, with `iron:router` and `kadira:flow-router` being the most [widely used](https://atmospherejs.com/?q=router).
____
Also, this is not an issue. [Meteor forums](https://forums.meteor.com/) would be a better place to ask.

**Comment by martijnwalraven** [comment]
There is no official router, but the [Meteor Guide article on routing](http://guide.meteor.com/routing.html) recommends using Flow Router.

Closing this because it is indeed not an issue.
