### ISSUE TITLE
Provide more granular configuration of resume token expiration

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6451]
**_2 Upvotes**_ Currently you can only configure resume token expiration globally with `loginExpirationInDays`:

https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_common.js#L89

It would be nice to allow configuration at the handler and login level.
## Per handler

An example use case is a one-time password auto-login link: https://github.com/meteor/meteor/issues/6386#issuecomment-194029596

If you consider such links to be less secure than a password, then you could set a lower expiration for them:

``` javascript
Accounts.registerLoginHandler( function(loginRequest) {
  ...
  return {userId};
}, {expirationInMinutes: 10});
```
## Per login

If you want admin accounts to expire weekly, versus accounts with fewer permissions that expire every 90 days:

``` javascript
Accounts.registerLoginHandler( function(loginRequest) {
  ...
  if (user.isAdmin)
    return {userId, expiresInMinutes: 7 * 24 * 60};
  else
    return {userId};
});
```

**Comment by mitar** [comment]
+1

**Comment by alanning** [comment]
+1   Yes please

**Comment by stubailo** [comment]
Couldn't you simply write your own cron job (or package) that expires the tokens on whatever schedule you need? It can have custom logic to look at the user in question and do whatever you need to do with roles, types of tokens, etc. Does this need to be part of the API? I think the database contains enough information to do this.

**Comment by lorensr** [comment]
`resume.loginTokens` is an array of `{hashedToken, when}`, and I don't know of a way to get Accounts to add a field to that object, whether it's `{createdFromHandler: 'password'}` or `{expirationInSeconds: 10 * 60}`. If there were, then a package could remove tokens on a schedule.

**Comment by stubailo** [comment]
Well the "per login" case is solved by my above strategy right? So now are talking about per-handler/per-login-session.

So perhaps the PR here is to add a special field from the client into the login token array. So you could say `return {userId, tokenMetadata}` and have that inserted with the hashed token and login time.

**Comment by lorensr** [comment]
> Well the "per login" case is solved by my above strategy right?

Oh, sorry – you mean when it's checking `user.isAdmin`? Yes, it is. I wasn't thinking about that situation specifically, but rather being able to decide based on arbitrary logic at time of login.

> `return {userId, tokenMetadata}`

👍

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20more%20granular%20configuration%20of%20resume%20token%20expiration&body=Migrated%20from:%20meteor/meteor%236451) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
