### ISSUE TITLE
[1.3-beta.16]  error while deploying to production

### ISSUE THREAD

**Issue by cj** [meteor/meteor#6452]
Here's a back-trace of the error:  https://gist.github.com/cj/d40ee2421fbc36abb709

I tried with and without the `cosmos:browserify` package.

Here's the buildpack I tried it with on heroku https://github.com/cj/meteor-buildpack-horse

**Comment by jamiter** [comment]
This buildpack worked for me for beta.12: https://github.com/robinnewhouse/meteor-buildpack-horse

**Comment by benjamn** [comment]
Possible dupe of #6449.

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.4`](https://github.com/meteor/meteor/issues/6266#issuecomment-198997482).
