### ISSUE TITLE
`import-scanner:_resolveNodeModule()` runs into infinite loop for `avital:mocha`

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6453]
I'm not sure exactly what's changed, but I traced it to https://github.com/meteor/meteor/blob/release-1.3/tools/isobuild/import-scanner.js#L616-L619

It breaks because 

```js
dir = '/Users/tom/Meteor/meteor/.meteor/packages/avital_mocha/.2.1.0_10.18v8uuc++os+web.browser+web.cordova/npm/npm/node_modules/mocha'
this.sourceRoot = '/Users/tom/Meteor/meteor/.meteor/packages/avital_mocha/.2.1.0_10.18v8uuc++os+web.browser+web.cordova/web.browser'
```

That is, `dir` is not a subdirectory of `sourceRoot` (which is assumed by that code).

We may need to do another release to fix this, as it's not currently possible to run mocha tests.

**Comment by benjamn** [comment]
Fixed in `1.3-rc.1`, thanks to https://github.com/meteor/meteor/commit/1189c217beb962f0dd6e70680043f8489f6545d7.
