### ISSUE TITLE
[1.3-beta.16]Error: TypeError: Object function createServer() has no method 'compress'

### ISSUE THREAD

**Issue by aniketdd** [meteor/meteor#6463]
TypeError: Object function createServer() {
function app(req, res, next){ app.handle(req, res, next); }
merge(app, proto);
merge(app, EventEmitter.prototype);
 app.route = '/';
 app.stack = [];
return app;
 } has no method 'compress'
     at runWebAppServer (packages/webapp/webapp_server.js:593:19)
    at meteorInstall.node_modules.meteor.webapp.webapp_server.js (packages/webapp/webapp_server.js:811:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:180:1)
   at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)

I am receiving above error on updating to beta.16. Initially i had errors for not finding npm modules 'meteor-deque', mongodb etc. i manually installed these modules using npm install until i faced with above error.
Anyone knows how to solve it/ which package is missing?

**Comment by zol** [comment]
Can you provide a reproduction please.

**Comment by eliezedeck** [comment]
@aniketdd How did you resolve this? I'm getting this same exact problem on Windows.

### How to reproduce?
- Be on Windows (Win 10 64-bit)
- meteor build ...
- cd programs\servers
- npm install
- npm install meteor-deque mongodb meteor-babel connect parseurl useragent send (because Meteor complains about those)
- cd ..\..
- node main.js

I get this:

```
C:\Project\deployment-win64\app\bundle\programs\server\node_modu
les\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Object function createServer() {
  function app(req, res, next){ app.handle(req, res, next); }
  merge(app, proto);
  merge(app, EventEmitter.prototype);
  app.route = '/';
  app.stack = [];
  return app;
} has no method 'compress'
    at runWebAppServer (packages/webapp/webapp_server.js:589:19)
    at meteorInstall.node_modules.meteor.webapp.webapp_server.js (packages/webapp/webapp_server.js:807:1)
    at fileEvaluate (packages\modules-runtime.js:158:9)
    at require (packages\modules-runtime.js:92:16)
    at C:\Project\deployment-win64\app\bundle\programs\server\packages\webapp.js:843:1
    at C:\Project\deployment-win64\app\bundle\programs\server\packages\webapp.js:856:3
    at C:\Project\deployment-win64\app\bundle\programs\server\boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Project\deployment-win64\ap
p\bundle\programs\server\node_modules\underscore\underscore.js:79:11)
    at C:\Project\deployment-win64\app\bundle\programs\server\boot.js:133:5
```

**Comment by aniketdd** [comment]
This issue was resolved in rc builds of meteor 1.3.
Please update your project with 'meteor update' command.

**Comment by eliezedeck** [comment]
@aniketdd well, I am using 1.3.1 already, and I got that error.

**Comment by aniketdd** [comment]
try deleting node_modules folder and then run 'npm install' command.
Also run 'meteor reset' before running app.

**Comment by nabiltntn** [comment]
@eliezedeck , so i was doing the same thing to workaround by installing manually NPM packages.
The problem you have is due to connect package, you need to precise a previous version of connect package , the connect@2.30.2 .
So now i am having new erros about missing packages like sockjs ,etc. i dont have the final list for the moment , keep tuned 😄

**Comment by nabiltntn** [comment]
@eliezedeck so you have to install also these two packages : `sockjs` and `permessage-deflate`

**Comment by eliezedeck** [comment]
Thanks @nabiltntn ... Seems to me there is a weird lack of support on Windows that the MDG is no having anyone on. So, I'm going to deploy to a Linux machine, which everything works well right out of the box.

**Comment by nabiltntn** [comment]
I created a repo with a guide and cartidge to deploy meteor app on openshift. It determines and installs automatically all npm modules required by your application. It's working with Meteor 1.2, not yet tested with 1.3 .

https://github.com/nabiltntn/deploy-meteor-on-openshift
