### ISSUE TITLE
Deprecate Npm.require in favor of import/require

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6464]
Meteor packages can now use `import` and/or `require` to import npm packages installed by `Npm.depends`, and #6398 removes any advantage of using `Npm.require`.

Concretely, this means
- [ ] making `Npm.require` print a warning in development mode in Meteor 1.3,
- [ ] eliminating all uses of `Npm.require` in core modules, and
- [ ] removing it entirely in ~1.3.1.

**Comment by zol** [comment]
I think doing the first item in 1.3 and items 2+3 post 1.3 would make sense here but this is a good idea.

**Comment by tmeasday** [comment]
We don't have a deprecation mechanism yet (printing a warning in development mode), although it wouldn't be too hard to create one.

The only thing is I'm not sure it's fair to say "6398 removes any advantage of using Npm.require" -- there are still quite a couple of disadvantages of having "peer" dependencies:

 1. You have to instruct users to install the package or use `tmeasday:check-npm-versions` to output a (potentially not that obvious) error message.
 2. You can't write tests in a natural way, instead you have to use an app scaffold: https://github.com/meteor/meteor/issues/6401

**Comment by tmeasday** [comment]
I would propose that we think about solving 1 + 2 in 1.3.1 (in some way?) and deprecating it then.

**Comment by tmeasday** [comment]
Or have I mis-read this, and are you proposing still using `Npm.depends()`? If so disregard my comments above.

**Comment by benjamn** [comment]
Yes I think `Npm.depends` still has a role to play for the time being, and will only be replaced as Meteor packages migrate to npm packages.

**Comment by hwillson** [comment]
Let's move this over to the FR repo.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Deprecate%20Npm.require%20in%20favor%20of%20import%2Frequire&body=Migrated%20from:%20meteor/meteor%236464) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
