### ISSUE TITLE
Error deploying: Host domain already in use on Galaxy?

### ISSUE THREAD

**Issue by mikepaszkiewicz** [meteor/meteor#6466]
I'm on 1.2.1,  I can deploy fine to meteorapp.com but this error gets thrown when I try to deploy to my subdomain / hostname. I've followed the guide closely but not sure what to make of this...there is no way my url is already in use, as this is my first Galaxy setup and the domain name isn't public.

```
//CLI
DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy xxxx.xxxxx.com --settings MIKE_settings.json

Error deploying application: This host domain is already in use on Galaxy. [xxxx.xxxx.com]
```
```
//MIKE_settings.json
{
    "galaxy.meteor.com": {
      "env": {
        "ROOT_URL": "https://xxxx.xxxxx.com",
```

**Comment by Primigenus** [comment]
You should probably get in touch with the Galaxy support team via the Help link inside Galaxy rather than posting an issue here.
