### ISSUE TITLE
[1.3-branch] meteor test command does not see driver package

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#6473]
@tmeasday, with the latest release-1.3 commit, `meteor test` does not seem to be working anymore. It is not loading the driver package and `process.env.TEST_METADATA` is not set yet in `test_environment.js` (it seems to be loaded before the code that sets it?). Initially the symptom was that I was getting “describe” reference error because the driver package code was not running to define it. I discovered that there was actually faulty logic for the error related to that, which I fixed in PR https://github.com/meteor/meteor/pull/6472. Once you merge that, though, you get the `No --driver-package specified for meteor test` error all the time because `process.env.TEST_METADATA` is not set in that file.

**Comment by aldeed** [comment]
Possibly the preamble stuff you removed in https://github.com/meteor/meteor/commit/3a98d04b710e1286f13138823c29b90a24a3dec4 is actually necessary because of the load order

**Comment by tmeasday** [comment]
The issue is a regression where `buildMode` can no longer be "test" and so `testOnly` packages are never loaded.

**Comment by tmeasday** [comment]
Give it a try now @aldeed

**Comment by aldeed** [comment]
Works now, thanks
