### ISSUE TITLE
[1.3-beta.16] [Windows] Did you forget to call 'Npm.depends'

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor/meteor#6474]
Trying out beta.16 on a Windows machine,  I got the following error messages:
=============================================================

D:\tryout\v13b16>meteor
[[[[[ ~\D\tryout\v13b16 ]]]]]

=> Started proxy.

Changes to your project's package version selections:

standard-minifiers  removed from your project

=> Started MongoDB.
=> Exited with code: 8
W20160313-11:27:24.699(1)? (STDERR)
W20160313-11:27:24.704(1)? (STDERR)     at D:\tryout\v13b16\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160313-11:27:24.704(1)? (STDERR)     at Array.forEach (native)
W20160313-11:27:24.704(1)? (STDERR)     at Function._.each._.forEach (C:\Users\René\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160313-11:27:24.699(1)? (STDERR) D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:313
W20160313-11:27:24.704(1)? (STDERR)    ^
W20160313-11:27:24.704(1)? (STDERR)     at D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:272:10
W20160313-11:27:24.704(1)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160313-11:27:24.704(1)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160313-11:27:24.704(1)? (STDERR)     at Object.Npm.require (D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:193:17)
W20160313-11:27:24.704(1)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160313-11:27:24.704(1)? (STDERR)     at D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:133:5
W20160313-11:27:24.704(1)? (STDERR) }).run();
W20160313-11:27:27.284(1)? (STDERR)
W20160313-11:27:27.284(1)? (STDERR) D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:313
W20160313-11:27:27.284(1)? (STDERR) }).run();
W20160313-11:27:27.284(1)? (STDERR)    ^
W20160313-11:27:27.284(1)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160313-11:27:27.284(1)? (STDERR)     at Object.Npm.require (D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:193:17)
W20160313-11:27:27.284(1)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160313-11:27:27.284(1)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160313-11:27:27.284(1)? (STDERR)     at D:\tryout\v13b16\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160313-11:27:27.284(1)? (STDERR)     at D:\tryout\v13b16\.meteor\local\build\programs\server\boot.js:272:10
W20160313-11:27:27.284(1)? (STDERR)     at Array.forEach (native)
W20160313-11:27:27.284(1)? (STDERR)     at Function._.each._.forEach (C:\Users\René\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)

**Comment by Rhywden** [comment]
Duplicate of https://github.com/meteor/meteor/issues/6448

**Comment by AnnotatedJS** [comment]
Closed because of Duplicate of #6448
