### ISSUE TITLE
[1.3-beta.12] meteor test does not work with angular2 apps

### ISSUE THREAD

**Issue by ahmedhagii** [meteor/meteor#6477]
I can't seem to get meteor test to run while using angular2 instead of blaze and I keep getting the following error:

```
W20160313-22:12:04.705(2)? (STDERR)
W20160313-22:12:04.706(2)? (STDERR) /private/var/folders/zg/3nxlrbcs3ss41bjfwg5yw0mh0000gn/T/meteor-test-run1eal9lp/.meteor/local/build/programs/server/app/try.test.js:1
W20160313-22:12:04.706(2)? (STDERR) (function(Npm, Assets){(function(){import { mocha } from 'meteor/avital:mocha'
W20160313-22:12:04.706(2)? (STDERR)                                    ^^^^^^
W20160313-22:12:04.715(2)? (STDERR) SyntaxError: Unexpected reserved word
W20160313-22:12:04.716(2)? (STDERR)     at /private/var/folders/zg/3nxlrbcs3ss41bjfwg5yw0mh0000gn/T/meteor-test-run1eal9lp/.meteor/local/build/programs/server/boot.js:244:30
W20160313-22:12:04.716(2)? (STDERR)     at Array.forEach (native)
W20160313-22:12:04.716(2)? (STDERR)     at Function._.each._.forEach (/Users/ahmedhagii/.meteor/packages/meteor-tool/.1.1.13-beta.12.1ocs6z4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160313-22:12:04.716(2)? (STDERR)     at /private/var/folders/zg/3nxlrbcs3ss41bjfwg5yw0mh0000gn/T/meteor-test-run1eal9lp/.meteor/local/build/programs/server/boot.js:140:5
```

To reproduce:
1. create a new project with 1.3.12 release
2. `meteor add urigo:angular2-meteor`
3. `meteor remove ecmascript`
4. `meteor add avital:mocha; meteor add practicalmeteor:chai`
5. create a method.test.js file with:
```
import { mocha } from 'meteor/avital:mocha';
import { chai, assert } from 'meteor/practicalmeteor:chai';

describe('Test', () => {
    it('should just run', () => {
        assert.equal(5, 5);
    });
});
```
6. run `meteor test --driver-package avital:mocha`

I guess the problem is that typescript is not compiling the test file cuz it doesn't end in .ts and and therefore complaining about import, but If I tried to change the extension to .ts it runs fine but nothing show in the tests result just 0 passed and 0 fails as if it didn't consider the file.

**Comment by grundyoso** [comment]
I encountered this similar error doing something totally different and it's basically that the "import" syntax requires backwards compatibility with ES2015 and below... so to resolve I left the ecmascript package to my meteor build:

`meteor add ecmascript`

**Comment by kamilkisiela** [comment]
It's working for me.
https://github.com/kamilkisiela/meteor-typescript-testing

I'm using `practicalmeteor:mocha` because avital's was just a temporary thing.

@grundyoso @ahmedhagii Do you still have any issue with testing?

**Comment by grundyoso** [comment]
I was able to overcome my issue by adding ecmascript package... I haven't tested without... I'll post here once I do and it's successful

**Comment by kamilkisiela** [comment]
To sum it up.

`.ts` extension is needed also on every test file. I think that's okay since there is a `typescript` compiler in use and not `ecmascript`.

In my opinion it suppose to work this way.

As I mentioned two comment above, `practicalmeteor:mocha` works really well with `barbatus:typescript` and all tests are being loaded and run correctly.

---

So I think we can close it, @Urigo

**Comment by Urigo** [comment]
thanks @kamilkisiela

**Comment by mariohmol** [comment]
Hi there.. trying to make it work with `practicalmeteor` but having trouble to make it find the typings.. i'm basing this app on the whatsup clone.. is there a example of testing using this repo? anyway. here is the issue about it https://github.com/practicalmeteor/meteor-chai/issues/9
