### ISSUE TITLE
meteor 1.3 - a driver-package for meteor test-packages is not found if it's testOnly

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#6478]
@tmeasday that's what prevents your practicalmeteor:mocha 1.3 [pr](https://github.com/practicalmeteor/meteor-mocha/pull/14) to work with meteor test-packages. I'd recommend allowing testOnly packages to be test-packages driver-packages

**Comment by tmeasday** [comment]
Hi @rbabayoff -- which version are you trying this against? If you are running against checked out Meteor, you may be running into #6473

**Comment by tmeasday** [comment]
Oh, actually I think it was this you were running into: https://github.com/meteor/meteor/pull/6479

**Comment by jsep** [comment]
@tmeasday you we right it working with the merge of #6479
