### ISSUE TITLE
Avoid rebuilding the app three times on error

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#6481]
Since Meteor tries to restart your app three times when there a server runtime error, it can take a long time to discover that this is happening. I've written a package that detects server errors and displays them on the client, but it would be much better if Meteor only tried once:

https://github.com/stubailo/meteor-dev-error-overlay

I have never encountered a situation where the automatic restart fixed the problem. Maybe it's time to get rid of it.

**Comment by zol** [comment]
@benjamn if this is easy it would be great to fix post 1.3 . Ideally we only restart once and if the app crashes with the same runtime error we wait for file changes like we do now.

**Comment by DominikGuzei** [comment]
Yes, pleeeease throw it out – it's one of the most frustrating "features" of Meteor :wink:

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Avoid%20rebuilding%20the%20app%20three%20times%20on%20error&body=Migrated%20from:%20meteor/meteor%236481) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
