### ISSUE TITLE
Meteor Reactivity problem on Safari 9.0.3

### ISSUE THREAD

**Issue by mroftalp** [meteor/meteor#6482]
I haven't fully check on other macs but can someone please check on this, to whoever has an upgraded OS Mac (El Capitan) which has a Safari version 9. There seem to be a problem on the reactivity of meteor. I tested on different browser (Chrome, FireFox, Safari v8) and its only this Safari version 9 that has a reactivity problem. Regarding the reactivity problem, I have a helper function that reads the chat in which is dependent whether the user is idle.. (https://github.com/mizzao/meteor-user-status) If I'm the only one with the reactivity problem then I have to change my logic but it works fine on Chrome, FireFox, and Safari v8. So that weirds me out.

**Comment by JulianLaNeve** [comment]
Can you make a repository with your project? I've been using Safari 9.0.3, and everything seems to be fine for me.

**Comment by Primigenus** [comment]
Seems like you should report this to @mizzao on his user-status repository rather than Meteor. Right?

**Comment by mroftalp** [comment]
@Primigenus Ahhh yeah you're probably right.

**Comment by mizzao** [comment]
It's not clear to me that this is a problem with user-status rather than user error.
