### ISSUE TITLE
[1.3-beta.16] Jquery and thrid party jquery libraries stopped working

### ISSUE THREAD

**Issue by THPubs** [meteor/meteor#6483]
After upgrading to beta 16, it started to say `Jquery is not defined` and most of my jquery libraries stopped working!

For example, I linked to `justifiedGallery` through `index.html` like this :

    <script src="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.6.1/js/jquery.justifiedGallery.min.js"></script>

But when I try to run it :

    $("#mygallery").justifiedGallery();

It says `justifiedGallery` is not a function.
All the other libraries are breaking like this. When downgraded to beat 11, it started to work!

**Comment by lampe** [comment]
with the newest beta of 1.3 meteor puts all script at the end of the <body> tag not the <head> tag

so your probebly loading the justifiedGallery before jquery is loaded

**Comment by THPubs** [comment]
@lampe Great!  I just created a body tag in the index.html and moved the scripts from the head to that body tag. That solved the issue!
