### ISSUE TITLE
Package published with Meteor 1.3 tool doesn't respect client/server divide in Meteor 1.2 app

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#6484]
Using `METEOR@1.3-beta.12` I published this code: https://github.com/stubailo/meteor-dev-error-overlay

Then, I could use it successfully in an app on the same beta. But when you added it to an app on 1.2.1 or below, you would get the following error: https://github.com/stubailo/meteor-dev-error-overlay/issues/1

```js
ReferenceError: localStorage is not defined
     at loadConfig (dev-error-overlay.js:159:16)
     at Package (dev-error-overlay.js:6:22)
```

(This is because a client-only file was loaded on the server)

Perhaps, when publishing, the 1.3-beta.12 tool didn't include some metadata required by older versions of Meteor.

Note that I reproduced this with beta 12; if it is likely that this issue has already been fixed I can try to reproduce with 16 or newer as well, but it takes a while to publish and install a package so I haven't done that yet.

**Comment by benjamn** [comment]
This should be fixed if you do `meteor update --release 1.3.1-rc.3`, soon to become 1.3.1.
