### ISSUE TITLE
Update to 1.3-rc.0 doesn't work on Windows

### ISSUE THREAD

**Issue by seifip** [meteor/meteor#6487]
***2 Upvotes*** ```
PS C:\Users\Philip\Documents\GitHub\ll-app> meteor update --release 1.3-rc.0
This project uses Meteor 1.3-rc.0, which isn't available on Windows. To work with this app on all supported
platforms, use meteor update --release METEOR@1.2.1 to pin this app to the newest Windows-compatible release.
```

Using PowerShell on Windows 10 x64

**Comment by lyquocnam** [comment]
the same with windows 10 x64.

**Comment by seifip** [comment]
rc.1 exhibits the same problem

**Comment by lyquocnam** [comment]
rc1 not working for windows 10 x64 too. :3

**Comment by bosung90** [comment]
+ 1 please make rc work on windows too

**Comment by redwards1966** [comment]
+1 yes, I really need to update this. running on windows 10 x64

**Comment by Laurentiu-Andronache** [comment]
solve it you monsters!

**Comment by kaleoh** [comment]
They announced rc.1 wasnt ready for windows, only osx and linux. Unless
something has changed?

**Comment by zol** [comment]
That's correct. We had some issues with releasing a Windows RC. We've now resolved these and are planning to release an RC2 that will work with Windows shortly.
