### ISSUE TITLE
[1.3-rc.1] Can't find test driver package with version constraints

### ISSUE THREAD

**Issue by jsep** [meteor/meteor#6493]
Hello,

If you specify a version of the package driver meteor can't find the package with both `test` and `test-packages` commands.

```
Error: Can't find test driver package: practicalmeteor:mocha-console-runner@0.2.0-meteor-1.3-rc.1
W20160315-13:51:57.570(-4)? (STDERR)     at nextSlot (/tmp/meteor-test-runfja9to/.meteor/local/build/programs/server/packages/meteor.js:1004:13)
W20160315-13:51:57.570(-4)? (STDERR)     at /tmp/meteor-test-runfja9to/.meteor/local/build/programs/server/boot.js:288:5
```
Steps to reproduce:
```
meteor --release 1.3-rc.1 create  test-app
cd test-app
meteor --release 1.3-rc.1 test --driver-package practicalmeteor:mocha@2.1.0-meteor-1.3-rc.1

```

**Comment by rbabayoff** [comment]
@tmeasday we need this fixed to check the console runner and spacejam with meteor 1.3. Tks!

**Comment by aldeed** [comment]
@jsep @rbabayoff You have to `meteor add` the package first, so I would think you'd specify the version when doing that and then you don't need it with `--driver-package`

**Comment by tmeasday** [comment]
Does @aldeed's solution work for you @jsep @rbabayoff ?

**Comment by tmeasday** [comment]
(Closing will reopen if not)
