### ISSUE TITLE
[1.3-rc.1] Meteor no longer defined on client following upgrade

### ISSUE THREAD

**Issue by JeremySaks** [meteor/meteor#6497]
Hi guys. After an upgrade directly from `1.3-beta.12` to `1.3-rc.1` server code is running smoothly but `Meteor` is not defined on the client. All the Meteor core packages come in from a single local package where I `api.imply` `meteor-base` and others. This strategy has worked fine up through `1.2` as well as on `1.3-beta.12`. Not sure where to begin with this one, my console's awash in red. I'm on Mac OSX. Are there package changes I need to be making to move from `beta.12` to now?

![screen shot 2016-03-15 at 4 41 11 pm](https://cloud.githubusercontent.com/assets/1514690/13793521/998cba84-eacd-11e5-9421-e9eeaee69df3.png)

**Comment by JeremySaks** [comment]
One update here that may be helpful, the first error that lands in the console is:

`Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined` at `meteor.js:59`

So it looks like `meteorEnv` in `packages/meteor/client_environment.js` is undefined.

**Comment by zol** [comment]
Please post minimal repro to help us track this down.

**Comment by JeremySaks** [comment]
Ok, after some more digging I believe my issue is a duplicate of a known error / incompatibility right now with `FlowRouter` + `1.3-beta.16` / `1.3-rc.1`. See #6448, #6449,  #6495, kadirahq/flow-router#552.

For those coming across this, I think the errors from the screenshot above came in as they did because I added `cosmos:browserify` as an explicit package dependency and was bringing that and `flow-router` in from a local package. But the problem is actually arising from the combination of `Meteor@1.3-rc.1/flow-router/browserify`.

Pretty confident this can be marked as a duplicate.

**Comment by zol** [comment]
Thanks @jJeremySaks, marking this as dupe.
