### ISSUE TITLE
[1.3-beta.12] [windows] fail to import file in current directory

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#6498]
Noob here...

Maybe I am wrong but I assumed that `import "file.js";` would import a file from the current directory of the file that included this statement.  Alternatively, I was thinking it might import a file at the root of my project.  It does not seem to do any of those things in my windows development environment.

### environment:
* Windows 10 x64
* meteor 1.3-beta.12 installed on C: drive, project on E: drive.
* node 5.8.0 x64

### repro:

1. go to e: drive root.
2. `meteor create test`
3. `cd test`
4. add one liner file `FileToImport.js` that contains: `console.log("In FileToImport");`
5. in `test.js` add one line: `import "FileToImport.js";`
6. run `meteor`, I get the following error:  
`W20160315-15:10:02.204(-7)? (STDERR) C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.12\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245`
`W20160315-15:10:02.204(-7)? (STDERR)                                            throw(ex);`
`W20160315-15:10:02.204(-7)? (STDERR)                                                  ^`
`W20160315-15:10:02.205(-7)? (STDERR) Error: Can't find npm module 'FileToImport.js'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?``

### work around:
1. in `test.js` change one liner to: `import "./FileToImport.js";`

explicitly specifying current directory: "**./**" works.

**Comment by benjamn** [comment]
This is tempting, but the behavior you're seeing is the way that CommonJS (Node) works, and the Meteor module system tries to stick to Node/npm's rules as closely as possible. Specifically, all relative identifiers must start with `./` or `../`, absolute identifiers (like the `module.id` for each module) start with `/`, and all other paths refer to something in a `node_modules` directory. [Here](https://nodejs.org/api/modules.html#modules_all_together) are the official rules.

When you include the `.js` at the end of the file, it might seem obvious that you wanted to refer to a relative path, but the `.js` extension is optional, so the real ambiguity comes with something like `import "FileToImport"`. Is that a relative path, or a package in a `node_modules` directory? The only safe answer is to stick with what works in Node.

**Comment by brucejo75** [comment]
Thanks benjamn!

Sorry for being a noob on it.  I could not find the spec for the expectations for import.  I was looking mostly at the language specification I did not think to check node.  I agree that meteor should follow node.
