### ISSUE TITLE
WebAppLocalServer is not defined

### ISSUE THREAD

**Issue by Fen747** [meteor/meteor#6503]
Hi !

I'm deploying my app on an aws EC2 instance, it works great until I want to run it as an android app on my physical device.

I deployed my app on AWS with Arunoda's MUP.
- node version : 0.10.40
- meteor version : 1.2.1

I run it with `meteor run --settings settings-development.json android-device --mobile-server http://my.ip.is.here`

Then, I get the unfortunately famous errors concerning CORS on meteor.local. Therefore, I use `App.accessRule("*")` to avoid it.

But when I do that, I know get only one log : "Uncaught ReferenceError :WebAppLocalServer is not defined". That's the only log I can deal with now. And not a single post seems to exists here or on SO or anywhere else about it.

When I try to upgrade the app to the meteor 1.3 beta, I get CORS error again (on http://my.ip/_timesync), though I still use `App.accessRule("*")`.

There is, according to my searches, absolutely nothing, no related doc, about the WebAppLocalServer error I get. Therefore I report it here.

Here are the `--verbose` logs :

```
I20160316-17:34:57.617(1) (android:file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
    I20160316-17:34:57.702(1) (android:http://meteor.local/753cf1d0f224d17b3e38ba586d04c9dc3aee4c15.js:103) Uncaught ReferenceError: WebAppLocalServer is not defined
    I20160316-17:34:57.703(1)? I/chromium(27295): [INFO:library_loader_hooks.cc(130)] Chromium logging enabled: level = 0, default verbosity = 0
    I20160316-17:34:57.703(1) (android:file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js:173) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
    I20160316-17:35:00.690(1) (android:http://meteor.local/753cf1d0f224d17b3e38ba586d04c9dc3aee4c15.js:103) Uncaught ReferenceError: WebAppLocalServer is not defined
```

What should I do ? I'm blocking on this problem for a week now, and I found nothing helpfull :S

Thank you.

**Comment by martijnwalraven** [comment]
`WebAppLocalServer is not defined` is a result of hot code pushing an update from a server running Meteor 1.3 to a device running an app built using Meteor 1.2.

I've actually committed [a workaround for this](https://github.com/meteor/meteor/commit/ea6951122efa9719dc41ff69910f2bb9e14ac2af) just a few hours ago, which blocks hot code pushes to Meteor 1.2.

Your other errors are most likely unrelated. Note that `App.accessRule("*")` doesn't have anything to do with CORS. In order to avoid CORS errors, you will have to make sure the server is sending the right headers.

**Comment by Fen747** [comment]
I finally find it out a few minutes ago, but thanks for your help :)

I had to uninstall / reinstall completely the app. I didn't knew that restarting the local server for mobile app was just a hot code push and not a total rewritting of the app on the phone.
