### ISSUE TITLE
Meteor silently loses connection

### ISSUE THREAD

**Issue by JacobPariseau** [meteor/meteor#6504]
I am using the latest official master build of Meteor, deployed to Galaxy (Developer) and using Compose MongoDB.

To be fair, I am not on an exemplary internet connection -- quite frequently apps on my phone will report that there is no internet access, but it always comes back a second or two later.

Lately I have noticed that on occasion while my app is running on Galaxy it will disconnect from the server. I initially thought I just had a huge latency problem, as I could make a few posts and several minutes later they would appear (sometimes up to 10 minutes). I installed Kadira Debug and at the same time the app starts to show latency issues, Kadira stopped receiving logs. I checked Meteor.status() which reported that my connection was good, but the only way to restore the connection was to either wait for it to happen automatically or call Meteor.disconnect() followed by Meteor.reconnect();

Very shortly after this manual reconnect Kadira Debug started receiving a mass of logs from the timespan that I was disconnected and the posts I had tried to make (that were sitting on the client) pushed to the server.

I can't expect Meteor to take care of the dropped connections seamlessly; that would be a job for me to handle. But I have no way of reading when the connection cuts out. If Meteor.status() reported that I was disconnected, I could alert the user that there was no connection and offer them the chance to reconnect, but at the moment I'm unsure if that is possible.

There is a definite possibility I am misreading the issue, but I'm no expert on Meteor and don't know how to debug further. I'll provide any information you may need to figure out what is actually going on.

Exhaustive list of packages:
`accounts-base
accounts-password
iron:router
dbernhard:jquery-ui-draggable
dsyko:jquery-ui-touch-punch
fastclick
momentjs:moment
gfk:notifications
ficshelf:media-query
infinitedg:gsap
lepozepo:s3
alanning:roles
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
meteorhacks:fast-render
percolate:synced-cron
mizzao:bootboxjs
jacobpariseau:animated-each
reactive-var
sacha:spin
reywood:publish-composite
velocityjs:velocityjs`

**Comment by benjamn** [comment]
More discussion of reconnecting to Compose.io: #6258

**Comment by abernix** [comment]
This actually doesn't sound like a Mongo issue that you were referring to originally, but more a Meteor connection error with the DDP connection.  This issue is rather old now, but is this something you can still reliably reproduce on a recent version of Meteor (e.g. 1.4.1.1)?  If so, can you provide some basic reproduction steps on a fresh Meteor app?  (Or even better, a Meteor app Git repo?)

**Comment by abernix** [comment]
Thanks for opening this originally.  I'm going to close this because we haven't heard anything back from you but would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
