### ISSUE TITLE
Mongo Collection is not searching by function in server

### ISSUE THREAD

**Issue by brunovcosta** [meteor/meteor#6509]
Mongo make it possible to [query itens with functions](https://docs.mongodb.org/manual/reference/operator/query/where/).

It works well in Client, but in server it aways return true.
Is easy to reproduce the error by trying any of the following codes in `meteor shell`

```
YourCollection.find({$where: function(){return false}})
YourCollection.find(function(){return false})
YourCollection.findOne({$where: function(){return false}})
YourCollection.findOne(function(){return false})
```

My current version: 1.2.1
My packages (wich may not make any difference):

```
accounts-facebook        
accounts-google          
accounts-password        
accounts-twitter         
benjick:webcam           
blaze-html-templates     
bozhao:link-accounts     
cfs:filesystem           
cfs:graphicsmagick       
cfs:standard-packages    
cfs:ui                   
check                    
chrismbeckett:toastr     
classcraft:imagemagick   
dbarrett:dropzonejs      
ejson                    
email                    
fortawesome:fontawesome  
http                     
iron:router              
jquery                   
less                     
logging                  
meteor-base              
mikael:accounts-merge    
mobile-experience        
momentjs:moment          
mongo                    
mrt:moment-timezone      
natestrauser:animate-css 
okgrow:router-autoscroll 
raix:push                
random                   
reload                   
sanjo:jasmine            
service-configuration    
session                  
sewdn:masked-input       
spacebars                
standard-minifiers       
tracker                  
twbs:bootstrap           
velocity:html-reporter   
zimme:iron-router-active 
```

**Comment by helfer** [comment]
Can you try the same on `YourCollection.rawCollection()`? If it works there, this is an issue we can fix, if not then it's an issue with the Node Mongo driver.

Info about rawCollection():  http://docs.meteor.com/#/full/Mongo-Collection-rawCollection

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this as we haven't heard back from you, but I've done some additional research...

It doesn't appear that the Mongo Node driver [supports](https://mongodb.github.io/node-mongodb-native/markdown-docs/queries.html) the shorthand notation of using a function in place of the query `Object`, however using the (slightly longer) syntax which includes the `$where` object does work:

```js
YourCollection.find({ $where: function () { return "this.fun === true" })
```

It's not entirely clear to me what you were expecting by having the function `return false` as that wouldn't be a valid query anyway.  I think it should be pointed out that using this method of querying foregoes all indexes and therefore could be quite slow.  It should generally be avoided for performance reasons.

**Comment by mitar** [comment]
Also useful: https://stackoverflow.com/questions/15612947/mongodb-where-query-always-true-with-nodejs
