### ISSUE TITLE
meteor 1.3 - don't require driver packages to be added to the app

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#6510]
@tmeasday this is a big one, here's why:

I'm adding practicalmeteor:mocha to my app so I can run my tests in the browser during development.

Then, I want to either use practicalmeteor:mocha-console-runner (with spacejam) or dispatch:mocha-phantomjs in ci, and I will have have to add it explicitly to the app in ci, before running my tests.

Even worse, if I want to run my tests and report results to the console during dev, I will have to add one of the packages above to the app, and this will overwrite the browser reporter until I remove them again.

I suggest bundling the driver-package specified on the command line with the app, when building the app for meteor test or meteor test-packages, so I can use one driver in devel and another one in ci or whenever I want to run my tests with another driver. This was the behavior before for test-packages with test-in-browser and test-in-console, so I suggest restoring it.

**Comment by rbabayoff** [comment]
This implies also being able to specify version constraints for driver packages on the command line, as before.

**Comment by tmeasday** [comment]
Why can you not add both drivers to the app?

The reason we have `runTests()` exported is so that the driver can co-exist with other drivers peacefully and not take any action unless they have been specified on the commandline.

**Comment by rbabayoff** [comment]
Let us check if there are no other conflicts, but yes, this should work. Will get back to you tomorrow. Now I understand why you removed the startup code from Meteor.startup

**Comment by rbabayoff** [comment]
Working perfectly.
