### ISSUE TITLE
Add support for Meteor.isTestPackages and Meteor.isTestFullApp

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#6511]
Sometimes, even though not really a good practice testing wise, you may want to know in what context your code runs in.

I'd recommend keeping Meteor.isTest to always be true and then setting one of the others, if needed.

**Comment by tmeasday** [comment]
It's perhaps more confusing than it needs to be, but there's:

 - package test mode: nothing set
 - normal test mode: `Meteor.isTest === true`
 - full app test mode `Meteor.isFullAppTest === true`

**Comment by rbabayoff** [comment]
@tmeasday can we add something for package test mode? I already run into a few cases I needed that.

**Comment by tmeasday** [comment]
We're in feature freeze now.

Maybe let's move this to a Feature Request issue and we can discuss it there?

**Comment by rbabayoff** [comment]
@tmeasday this seems to be straightforward, you already set flags for when running meteor test and meteor test --fulll-app. There is no reason that meteor test-packages should be inferior, runtime context awareness wise, to meteor test, especially taking into account that app code usually moves to package code, once you start to use it between apps.

I'm already doing this [here](https://github.com/practicalmeteor/spacejam/blob/master/bin/mtp#L30), in my meteor test-packages wrapper script.

You guys asked for my help to get all my test tools up to date for meteor 1,3 in time and provide feedback, I'm doing this, so I'd appreciate if my feedback will be heard, especially taking into account my vast hands-on experience with testing and meteor.

I don't see it as a feature, I see it as an oversight that should be fixed as part of testing for meteor 1.3. and it really seems like a couple of lines of code that doesn't affect anything and is definitely backwards compatible.
