### ISSUE TITLE
Meteor 1.3 RC 1 doesn't seems to like the spread operator

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#6514]
This is with the Meteor 1.3 RC-1. It seems like it doesn't like the spread operator and hence create some weird issue.

We had a few with FlowRouter. So, we had to remove some places where we use the spread operator. This work with 1.3 betas (up to beta 12)

Here are some places we got this:

* https://github.com/kadirahq/flow-router/pull/564
* https://github.com/kadirahq/flow-router/commit/534ef5474db3b18f72c78a0b3c32dd2bf2b5f59e

**Comment by marbemac** [comment]
I think it might specifically be the spread operator when used on/as function arguments. We use spread operators in function bodies w no problems so far.

**Comment by ChrisCinelli** [comment]
That syntax is not ES6.  I think it is currently a stage-0 syntax ( https://github.com/babel/babelify/issues/32 ). The react community that use the ES6 tents to enable stage-0 in Babel. That is why it would be nice if #6351 could be solved sooner than later.

**Comment by arunoda** [comment]
@ChrisCinelli oh no. This is ES6.
We just spread method arguments.

**Comment by ChrisCinelli** [comment]
You are right. I was confused with spread rest properties is actually a stage-2 feature: https://babeljs.io/docs/plugins/preset-stage-2/
https://github.com/sebmarkbage/ecmascript-rest-spread

**Comment by benjamn** [comment]
Fixed in `1.3-rc.3`.

**Comment by arunoda** [comment]
Thanks.
