### ISSUE TITLE
Template.data is reactive source for the helpers how come it is non-reactive in Template.onRendered autorun block

### ISSUE THREAD

**Issue by hadijaveed** [meteor/meteor#6516]
**Helper**

```
Template._testTemplate.helpers({
  testingVal() {
    return Template.instance().data.check;
  }
});
```

**onRendered CallBack**

```
Template._testTemplate.onRendered(function() {
  let self = this;
  Tracker.autorun(function() {
    console.log('check reactive sasata ', self.data.check);
  });
});
```

**Template**

```
<template name="_testTemplate">
  <p>Test Patial Template</p>
  <p>{{testingVal}}</p>
</template>
```

I am calling this partial form another Template while sending a reactive data through session.
`{{>  _testTemplate check=testingVal}}`

How come helpers update data reactively while autorun block doesn't rerun even if the data is changed. Is this some sort of bug that autorun block is not rerun even if the reactive data is changed.

**Comment by M4v3R** [comment]
`Template.instance().data` is not an reactive source. Your parent template basically re-initializes your partial template when any data passed as parameter to it changes and re-runs all its helpers. You can verify that by replacing:

```
Template._testTemplate.helpers({
  testingVal() {
    return Template.instance().data.check;
  }
});
```

With:

```
Template._testTemplate.helpers({
  testingVal() {
    console.log("Hello from testingVal helper");
    return "test";
  }
});
```

You will see that it will log to console every time you change the Session value.

**Comment by hadijaveed** [comment]
`Template.currentData()` is the reactive source and it works re actively in the on Rendered callback autorun block.

**Comment by stubailo** [comment]
@hadijaveed `Template.instance().data` will work. Note that the `instance()` call needs to be inside the autorun. This is because JavaScript values can't be reactive - only functions can. So like this:

```
Template._testTemplate.onRendered(function() {
  Tracker.autorun(function() {
    console.log('check reactive sasata ', Template.isntance().data.check);
  });
});
```

**Comment by hadijaveed** [comment]
@stubailo it does not work in autorun. I have tried it many times but Template.currentData() works. Since in meteor offical documentation they claim Template.currentData() as a reactive source but Template.instance().data is not a reactive source.

**Comment by hadijaveed** [comment]
How come `Template.instance().data` works in an autorun block if it is a non-reactive source ?

**Comment by M4v3R** [comment]
Sorry @stubailo but I believe you're wrong. `Template.instance().data` is not a reactive source in a way that it won't fire methods that depend on it. I've just checked the code you've pasted and the autorun code does not run when `Template.instance().data.check` gets changed. On the other hand all helper functions from child template are ran, but not because they depend on Template.instance().

Here's a test repo that illustrates that: https://github.com/M4v3R/meteor-reactivity-test

Note that `"check reactive"` line gets executed only once, even though its inside an autorun block. Also note that all helpers get executed (logging `1` and `2` to console) even though they don't contain any calls to template data.

**Comment by stubailo** [comment]
Yep I believe you, which is why I reopened the issue.

**Comment by M4v3R** [comment]
@stubailo But as @hadijaveed pointed out, this is a non-issue, because we already have `Template.currentData()` method which is reactive and does its job perfectly :).

**Comment by mitar** [comment]
Shouldn't one use `this.autorun` and not `Tracker.autorun`, because the former makes sure current template instance is correctly bound inside the computation, while the former does not?

**Comment by stubailo** [comment]
Yeah, you're right.

**Comment by mitar** [comment]
(BTW, there is no reason why `Template.autorun` could not detect that it is run inside the template instance context. This would probably solve #4494 as well.)

**Comment by hwillson** [comment]
It looks like the only remaining actionable item in this issue thread has already been created in the Blaze repo as meteor/blaze#178. Closing here - thanks for reporting this originally!
