### ISSUE TITLE
`meteor remove` should explain why it can't remove a dependent

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#6517]
I just spent a while trying to figure out why my app depends on cosmos:browserify, which a) can't be upgraded to the latest version for some reason and b) has been downgraded even further after I removed my .meteor/versions file. My first thought for figuring this out was looking up the package on Atmosphere, but as a blind screen reader user, Atmosphere has had accessibility issues for a while and is less than usable. Without Atmosphere usability, the command line becomes invaluable.

Given that, it would be nice if `meteor remove cosmos:browserify` reported the constraints that prevent it from being removed, rather than simply claiming it is not a direct dependency. If I want a certain dependency gone for whatever reason, this would help me refactor out its direct dependencies so I can remove it.

Thanks.

**Comment by abernix** [comment]
This is a great suggestion.  It's conceptually dependent on the same logic necessary to implement #4387, and I'll tag this as `pull-requests-encouraged` the same as that one.  Ultimately, both of these implementations should share the same method which determines the dependencies.

Anyone interested in tackling this should refer to #4387 and its linked issues.  Let us know if you can help implement this!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20remove%60%20should%20explain%20why%20it%20can't%20remove%20a%20dependent&body=Migrated%20from:%20meteor/meteor%236517) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
