### ISSUE TITLE
NPM Modules that are for browser only fail in 1.3

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#6518]
I'm using ```1.3-rc.2```.

I'm trying to use filesaver.js from NPM, the main file in the package has a line in it that tries to detect the window object, but gets "undefined" instead during build time. If I add a ```if (!window) return;``` Meteor passes the build section without errors, and the code works on the client.

```
typeof self !== "undefined" && self
	|| typeof window !== "undefined" && window
	|| this.content
```

**Comment by davidworkman9** [comment]
Is this something that might get fixed for 1.3? I'm seeing a bunch of talk about today being 1.3 release day!

**Comment by zol** [comment]
We're not going to 'fix' this in 1.3 . You should be able to work around it by importing the module only on the client. For 1.3+ we may include something in the framework to make this more automated.

**Comment by davidworkman9** [comment]
> importing the module only on the client

You're right. Man is that not clear. I thought I was only loading on the client, but now I realize my routes are defined on both the client and server, a bunch of imports down the line, I import something that should only be imported on the client.

Is there a way to import something only on the client or server once you've imported a higher level file on both?

both of these don't work:
```
if (Meteor.isClient) {
   import x from 'x';
}
```
or
```
const package = Meteor.isClient ? 'pkg' : 'serverstubs/pkg';
import filesaver from package;
```

**Comment by zol** [comment]
Hey @davidworkman9 - In this case you'll need to use the `require` syntax, `require("filesaver.js/FileSaver.js");`

**Comment by davidworkman9** [comment]
Nested imports now work.
