### ISSUE TITLE
Failure building fibers on DragonFly BSD

### ISSUE THREAD

**Issue by fupjack** [meteor/meteor#6519]
I had a failure building the fibers package, as part of installing wekan on DragonFly BSD 4.4.  I'm new to node.js and npm in general, so this may be a simple error on my part.  The error message it produced said to tell the listed author of the fibers package.  That's Marcel Laverdet, and he said to forward to the Meteor team.

It failed doing this: node ./build.js.  I've added the log: 
[npm-debug-log.txt](https://github.com/meteor/meteor/files/178207/npm-debug-log.txt)

**Comment by Deilv** [comment]
You are using node 5.7.0, but meteor requires node 0.10.x at the moment. Support for newer versions of node is coming in a future update.
