### ISSUE TITLE
Postpone open the DDP connection

### ISSUE THREAD

**Issue by knigal** [meteor/meteor#6520]
**_1 Upvote**_ I maintain a meteor app which serves thousands of concurrent sessions. 99% of the clients interact with the app in read-only mode, meaning they fetch the app, then some data, then client/server comm is done. For performance and cost-saving reasons (also environmental  :P) the clients are served by CDN. If/when the user logins, changing data becomes possible via newly-created subscriptions.

My understanding is that in Meteor a DDP connection is established immediately after the initial load. In my app this connection is not actually required until the user logs in. Problem is, the idle websockets for DDP require load-balancer and instance resources, which forces horizontal scaling.  I my use case, having the bulk clients hold an idle websocket is just inefficient & expensive architecture.

It seems there's no method to prevent Meteor clients from attempting to open a websocket when starting. There is a workaround using `DDP_DEFAULT_CONNECTION_URL` which can be set to an invalid value, causing the client connection to fail (console shows error).

Adding an environment variable such as `DDP_ESTABLISH_ON_START=off` can solve it.

Is this the appropriate venue to request such an enhancement?

**Comment by priezz** [comment]
👍 +1 (sorry, but nothing else to add :) )

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Postpone%20open%20the%20DDP%20connection&body=Migrated%20from:%20meteor/meteor%236520) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
