### ISSUE TITLE
Email address handling is wildly inconsistent for users

### ISSUE THREAD

**Issue by queso** [meteor/meteor#6523]
Currently, the data structures around a users email is wildly inconsistent depending on the source of signup. I believe we should standardize a way to access email addresses for a user, in a consistent manner. Part of the problem is trying to figure out where the user's email might be (I am sure twitter made this even harder up until now with their policies) because you might not be sure what service a user came in on and will require a big nest of if statements to figure out using code. Beyond that, none of the `services` portion of a user record is published. I really feel like publishing user records are already a source of overpublication in most applications, so I don't want to recommend sending down fields from services.

On top of that, accounts-password seems to push to a completely separate `emails` object, which is indeed published down to a client by default. This is great, but it turns out emails is an array of objects tracking if an email is verified or not. So you have to use something like `emails[0].address` to access what you want.

Here are all the standard sources, which doesn't include any third-party oAuth packages...

* "services.facebook.email"
* "services.github.email"
* "services.google.email"
* "services.twitter.email"
* "emails"

My proposal is that we move or copy the oAuth service email address on account creation so there is a more consistent source of truth for this type of information that people need to access in their apps.

**Comment by martijnwalraven** [comment]
@queso: I don't think this has been discussed, but you could be the first person to open an issue on the new [`meteor/accounts` repository](https://github.com/meteor/accounts/issues) :)

**Comment by engelgabriel** [comment]
Hi there, this is a nice opportunity to fix some of this inconsistencies.
Did you open the issue there? It would be good to put a reference here.

**Comment by stubailo** [comment]
Going to close this here, please reopen there: https://github.com/meteor/accounts/issues
