### ISSUE TITLE
Meteor 1.3 and npm modules with binary dependencies

### ISSUE THREAD

**Issue by lucidprogrammer** [meteor/meteor#6524]
Meteor Version: METEOR@1.3-beta.12
(Issue tested in both Windows and Mac )
npm install node-sass@3.4.2
(Installation successful in both windows and mac)
```
--windows---
 C:\Users\projects\myttnc\src\webapp\node_modules\node-sass\vendor\win32-x64-47\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
---mac ----
> node-sass@3.4.2 install /Users/username/Sites/project-path/node_modules/node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall /Users/username/Sites/project-path/node_modules/node-sass
> node scripts/build.js

` /Users/username/Sites/project-path/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
```
However, when meteor is run, it fails with the following error
```
--windows error
ERROR in The `libsass` binding was not found in C:\Users\projects\myttnc\src\webapp\node_modules\node-sass\vendor\win32-ia32-11\binding.node

--mac error--
ERROR in The `libsass` binding was not found in /Users/username/Sites/project-path/node_modules/node-sass/vendor/darwin-x64-11/binding.node
```

Tried downloading the said binary(meteor exception) from https://github.com/sass/node-sass-binaries
But fails in both windows and mac
```
Windows ----
ERROR in %1 is not a valid Win32 application.
C:\Users\projects\myttnc\src\webapp\node_modules\node-sass\vendor\win32-ia32-11\binding.node
mac ---
yld: lazy symbol binding failed: Symbol not found: _node_module_register
Referenced from: /Users/wmena/Sites/ttnc/myttnc/src/webapp/node_modules/node-sass/vendor/darwin-x64-11/binding.node
Expected in: flat namespace

dyld: Symbol not found: _node_module_register

```

fourseven:scss also was tried, it also exits with errors... 

Is it to do with the fact that meteor is using 10.x and these were made for newer versions? Is there a way for meteor to look for the right binary which gets installed in these scenarios?

**Comment by benjamn** [comment]
You may have to use the version of `npm.cmd` that's installed with Meteor, so that it picks up the version of `node.exe` that Meteor uses. If I had better knowledge of Windows BAT scripting, I would port [this commit](https://github.com/meteor/meteor/commit/ac6a2a961fb5dd54c106d585303cf72605c6469e) to `meteor.bat`, which would make things easier.

**Comment by lucidprogrammer** [comment]
Thanks Ben. Yes I figured it out that in the meantime.
Following is what I did, to avoid again another version of Node. (Chimp is also used in my project which needs node 5.2 so, I need to separate out the npm install scripts to cater to both these demands though)

SET WHICH_METEOR=1.1.13-beta.12
SET WHICH_DEV_BUNDLE=%LOCALAPPDATA%\.meteor\packages\meteor-tool\%WHICH_METEOR%\mt-os.windows.x86_32\dev_bundle
SET NODE_PATH=%WHICH_DEV_BUNDLE%\server-lib\node-modules;%WHICH_DEV_BUNDLE%\lib\node_modules;%WHICH_DEV_BUNDLE%\bin\node_modules;
SET WHICH_NODE_EXE_LOCATION=%WHICH_DEV_BUNDLE%\bin
SET PATH=%PATH%;%WHICH_NODE_EXE_LOCATION%

**Comment by lucidprogrammer** [comment]
it all works now for this version, but in another thread as I mentioned, it all bombs out with the current head version where it cries for deque.
