### ISSUE TITLE
[1.3 rc.3] isn't available on Windows.

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6526]
try to update:

`meteor update --release 1.3-rc.3`
and this message:
```
This project uses Meteor 1.3-rc.3, which isn't available on Windows. To work with this app on all supported platforms, use
meteor update --release METEOR@1.2.1 to pin this app to the newest Windows-compatible release
```

still not support on windows 10 x64 ?

**Comment by jakobrosenberg** [comment]
``meteor update --release 1.3-rc.3`` is working for me so far (installing...). Will be interesting to see if it finally works on Windows or if I'll go back to beta12.

**Comment by benjamn** [comment]
Try now?

**Comment by lyquocnam** [comment]
this still can not install windows 10 x64 mr @benjamn

**Comment by lyquocnam** [comment]
anyone have same problem ?

**Comment by bosung90** [comment]
It works fine for me on Windows 10 x64

**Comment by lyquocnam** [comment]
yeah, this work fine for now ! thanks
