### ISSUE TITLE
Feature request: Configurable root for ES6 modules

### ISSUE THREAD

**Issue by zimt28** [meteor/meteor#6528]
When writing Meteor apps, my structure currently looks like this:

```
├── client/
├── lib/
├── node_modules/
├── packages/
├── server/
├── CHANGELOG.md
├── Dockerfile
├── LICENSE
├── README.md
├── package.json
└── wercker.yml
```

Only `client`, `lib` and `server` folders contain actual application code. Because of this I'd like to move these into an `app` or a `src` folder. However, when using absolute module paths, I'd have to prefix all of them with `app` or `src`. Because of this, it would be nice if there was a way to set the project's root folder, maybe in a `.meteor/config` file or so. What do you think?

**Comment by zimt28** [comment]
@eXon, is this possible using `meteor-webpack`?

**Comment by eXon** [comment]
Yes, it is how every [kickstart projects](https://github.com/thereactivestack/kickstart) are setup.

All you need to do is set the `root` in webpack.json

**Comment by zimt28** [comment]
@benjamn Feedback?

**Comment by benjamn** [comment]
Would this affect anything other than the interpretation of absolute module identifiers?

**Comment by zimt28** [comment]
@benjamn I don't think so. It's just convenient not having to to add the obvious `app/` or so to the includes then the app lives in a subfolder.

**Comment by zimt28** [comment]
@benjamn Could this be done by allowing `.babelrc` files (https://github.com/meteor/meteor/issues/6351) and something like [babel-root-slash-import](https://github.com/mantrajs/babel-root-slash-import)?

**Comment by hwillson** [comment]
Meteor now supports `.babelrc` files (as of [1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133)), so you can leverage one of the popular root import packages to address this issue (like [babel-root-import](https://www.npmjs.com/package/babel-root-import), [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver), etc.). As such, I'll close this issue off. Thanks for suggesting this initially!

**Comment by trusktr** [comment]
Note, `babel-root-import` only handles files that Babel handles (namely JS and TS files). There's a need to do this for any type of file, so I made a new idea for it here: https://github.com/meteor/meteor/issues/10661
