### ISSUE TITLE
Make `meteor npm` work on Windows

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6531]
[This code](https://github.com/meteor/meteor/blob/0486b473e8066b2e483cec745ec16c5011c6fd52/meteor#L133-L141), introduce by [this commit](https://github.com/meteor/meteor/commit/ac6a2a961fb5dd54c106d585303cf72605c6469e), clearly won't work for Windows, and may not even work for other released versions of Meteor, without changes to the installer script.

The right way to solve both of these problems is to move this logic (or something similar) into [`tools/index.js`](https://github.com/meteor/meteor/blob/release-1.3/tools/index.js).

**Comment by lucidprogrammer** [comment]
@benjamn 

npm install in a meteor project directory.

Example directory structure.
.scripts/ (this has a package.json related chimp and end to end testing stuff. this requires node/npm latest & not the meteor version, so using system installed version)
/src/ (.meteor and the meteor application directory)

package.json (root level package file)
("install": "cd .scripts && npm install && cd ../src/webapp && npm install")

This kind of scenario fails as inside the meteor project directory - it should use the meteor's version of npm !!

Following is a npm.cmd in the meteor project directory which helps with this

:: When running npm commands in a meteor application directory, the version of node and npm should be the same as the one used by meteor
 @ECHO OFF
 :: We will be changing the NODE_PATH environment while this is running, lets don't clobber the global environment
 SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
 SET command=%1
 SET thisfolder=%~dp1
 echo %command%
 IF EXIST ".meteor" (
  IF "%command%"=="install" (
    for /f %%i in ('meteor --long-version') do set release=%%i
    echo meteor tool used for this release is !release!
    :: removing meteor-tool@ from the release variable
    SET tool=!release:~12!
    ECHO !tool!
    SET WHICH_DEV_BUNDLE=%LOCALAPPDATA%\.meteor\packages\meteor-tool\!tool!\mt-os.windows.x86_32\dev_bundle
    SET NODE_PATH=!WHICH_DEV_BUNDLE!\server-lib\node-modules;!WHICH_DEV_BUNDLE!\lib\node_modules;!WHICH_DEV_BUNDLE!\bin\node_modules;
    SET WHICH_NODE_EXE_LOCATION=!WHICH_DEV_BUNDLE!\bin
    SET PATH=!WHICH_NODE_EXE_LOCATION!
    echo !WHICH_NODE_EXE_LOCATION!
    !WHICH_NODE_EXE_LOCATION!\npm --version
    GOTO:EOF
  ) ELSE ( IF "%command%"=="start" (meteor)   )
) ELSE (
    ECHO You are not in a meteor project directory, your original npm is not getting called instead this script is getting called, not desirable!!
    GOTO:EOF
)

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.4`](https://github.com/meteor/meteor/issues/6266#issuecomment-198997482).
