### ISSUE TITLE
[1.3-rc.3] Galaxy deploy: Meteor requires Node v0.10.43 or later.

### ISSUE THREAD

**Issue by kations** [meteor/meteor#6533]
Got the following error on Galaxy with rc3, went back to rc1 and everything works finde again.

Meteor requires Node v0.10.43 or later.
Application exited with code: 1 signal: null
Application process closed with code: 1 signal: null
The container has crashed. A new container will be started to replace it.

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.4`](https://github.com/meteor/meteor/issues/6266#issuecomment-198997482).
