### ISSUE TITLE
[Feature request] Allow using our own test suits with Mocha

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6538]
I'm just now getting into Enzyme:
http://airbnb.io/enzyme/docs/guides/mocha.html

Of course, for now I'm going the "plain old" npm route for testing, which just dumps output in a terminal window. Will there (eventually) be a way to plug in our own test suite and have it display test results in the browser window, a la Velocity?

Enzyme just provides some functions to be used in conjunction with Mocha, so I imagine it shouldn't be that difficult. Though I had to do some setup to get Enzyme working, which included editing `.babelrc` to the following:

```json
{
  "presets": ["airbnb"]
}
```

And installing some extra npm packages, namely `chai`, `jsdom`, `babel-register`, and `babel-preset-airbnb`. The mocha command I'm using is:

```json
  "scripts": {
    "test": "mocha tests/.setup.js tests/**/*-test.js"
  },
```

#### .setup.js
```javascript
require('babel-register')();

var jsdom = require('jsdom').jsdom;

var exposedProperties = ['window', 'navigator', 'document'];

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    exposedProperties.push(property);
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

documentRef = document;
```

I imagine within Meteor, much of this setup wouldn't be necessary.

**Comment by tmeasday** [comment]
@ffxsam I think this should be eminently possible, either by writing a new test driver based on `practicalmeteor:mocha`, or even perhaps just by writing a `testOnly` package.

I would have to investigate a bit more how Enzyme is supposed to work in this mode, but maybe I'd suggest we move this to a forum post to discuss further? It seems more discoverable / more likely to have useful contributions?

**Comment by stubailo** [comment]
I agree with @tmeasday that building a new test runner that extends practicalmeteor:mocha, or maybe adding enzyme support to that package, would be the way to go. Going to close this in favor of a forum thread about how to make this package happen.

**Comment by ffxsam** [comment]
Tag me in it when you post. Thanks!

**Comment by stubailo** [comment]
I was hoping you could do it :P

**Comment by ffxsam** [comment]
What, you too busy or something? ;) (kidding, I know you are). Of course! I misunderstood your post & thought you were going to open one. We have a thread already actually, where Sam Hatoum recommended NOT integrating React unit testing into Meteor. I'll bump the thread & tag you in a few.
