### ISSUE TITLE
1.3 imported variables not available in console/debugging 

### ISSUE THREAD

**Issue by proehlen** [meteor/meteor#6542]
Per the below screenshot of the Chrome console, I'm importing a variable called ```terms``` (a reference to a Mongo.Collection) which is successfully used in the code before the ```debugger``` breakpoint.  However, at the breakpoint, in the console when I try to reference this variable it says ```Uncaught ReferenceError: terms is not defined(…)```.

![screen shot 2016-03-20 at 4 28 52 pm](https://cloud.githubusercontent.com/assets/8384068/13903719/9e0494c0-eeb9-11e5-871a-193cbe96c347.png)

What's especially weird though is that when I type the variable name in the console it comes up as a suggestion as if it is known:
![screen shot 2016-03-20 at 4 29 39 pm](https://cloud.githubusercontent.com/assets/8384068/13903721/d2331c30-eeb9-11e5-9ce3-52ea3b3961e9.png)

**Comment by benjamn** [comment]
Source maps are usually helpful, but in this case they're hiding the way this code is really transpiled. Similar explanation [here](https://github.com/meteor/meteor/issues/6381#issuecomment-193938592).

It would be great if source maps captured the concept of one identifier mapping to some other expression, but until then you may find it easier to disable source maps, or add some code that assigns `terms` to a normal variable.

**Comment by proehlen** [comment]
Ok thanks for the explanation and advice.
