### ISSUE TITLE
[1.3-rc3] Import: Omitting file extension only works with relative paths

### ISSUE THREAD

**Issue by D1no** [meteor/meteor#6543]
As mentioned here #6525 

Does omitting the file extension only work on relative paths?

When I do this in a `/client/main.js` file:
```js
// finds /imports/routes.jsx
import { renderRoutes } from '../imports/routes';
```
```js
// finds /imports/routes.jsx
import { renderRoutes } from '/imports/routes.jsx';
```
```js
// does NOT find /imports/routes.jsx
import { renderRoutes } from '/imports/routes'; //no file extension & absolute path
```

Files are often transpiled (i.e. from typescript). So requiring a file without stating its file-extension is a good way to ensure that in typescript the require leads to `routes.tsx` and in the transpiled format to `routes.js(x)`. Same with jscss etc.

Only working with relative paths can be quite confusing in large code bases.

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.4`](https://github.com/meteor/meteor/issues/6266#issuecomment-198997482).
