### ISSUE TITLE
release/METEOR@1.3-rc.4 meteor node

### ISSUE THREAD

**Issue by lucidprogrammer** [meteor/meteor#6544]
meteor node and meteor npm, works like a charm, no more custom scripts to get the meteor version of node/npm running. Great work @benjamn. (Tested on windows 10 and works well)

It can be great if you can solve the NODE_PATH to remove the additional scripts needed. For example, to use any testing framework, (say wallaby or standard mocha), one may pass meteor node as the runner. However, it will fail with errors like 'underscore./fibers etc not found.

Following is what I do now to solve this issue. Can we avoid the necessity for that, say somehow for the specific process (local) change the NODE_PATH?
In node:
`nodePaths.push(path.join(devBundle,'server-lib','node_modules'));
  nodePaths.push(path.join(devBundle,'lib','node_modules'));
  nodePaths.push(path.join(devBundle, 'bin','node_modules','npm','node_modules'));
  
`
In script
`
SET NODE_PATH=%thisfolder%node_modules;!WHICH_DEV_BUNDLE!\server-lib\node-modules;!WHICH_DEV_BUNDLE!\lib\node_modules;!WHICH_DEV_BUNDLE!\bin\node_modules;
    SET WHICH_NODE_EXE_LOCATION=!WHICH_DEV_BUNDLE!\bin
  
    start !WHICH_NODE_EXE_LOCATION!\node %command%
`

**Comment by benjamn** [comment]
If you don't mind putting together a pull request, we will happily merge this for 1.3.1! Have a look at [this file](https://github.com/meteor/meteor/blob/release-1.3/tools/cli/dev-bundle-bin-commands.js).

**Comment by lucidprogrammer** [comment]
Tks, will do.
