### ISSUE TITLE
[METEOR@1.3-rc.4] Build time is very high

### ISSUE THREAD

**Issue by aniketdd** [meteor/meteor#6547]
On updating meteor to rc.4 on my windows machine, it is taking atleast 15-20 minutes to start the application. Even on updating the code it takes same amount of time to restart/refresh.
All the modules are added as npm dependencies (even for joi and winston), not using browserify.

**Comment by benjamn** [comment]
Should be fixed in [`1.3-rc.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-201058454). Please reopen if the problem persists.
