### ISSUE TITLE
`Assets.absoluteFilePath()` is undocumented and doesn't work in build plugins

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6552]
CF: https://github.com/meteor/meteor/commit/134707be68d255d04a6d8b588f666c255f22b518#commitcomment-16742686

In the above commit, `Assets.absoluteFilePath` was implemented in `tools/static-assets/server/boot.js`. However the documentation for the other `Assets` APIs is in `tools/isobuild/bundler.js`, where the `Assets` APIs are *duplicated*.

This was confusing. It turns out the reason for this is when you are using the asset API from a build plugin. The only way you can do this is:

1. You have a build plugin `X`, that depends on package `Y`.
2. `X` calls `Y.foo()`
3. `Y.foo()` calls `Assets.Z()` -- this version of `Assets.Z()` is the `bundler.js` version.

Note that if `Y.foo()` is called from application code (possibly via some other package), it will use the version in `boot.js`.

The issue is that in `bundler.js`, we have the contents of the asset but not the on-disk path. This makes implementing `Assets.absoluteFilePath` difficult there.

Options from here:

1. Leave `Assets.absoluteFilePath()` undocumented.
2. Document `Assets.absoluteFilePath()` in `boot.js` and explain the limitation there (it's probably unlikely anyone will ever even *try* to use in the above way.
3. Try and figure out a way to implement `Assets.absoluteFilePath()` in the `bundler.js` context (if this is even possible.

**Comment by aldeed** [comment]
I like option 2, at least until someone complains it doesn't work in the build plugin.

**Comment by tmeasday** [comment]
Ok, finally did this.
