### ISSUE TITLE
[meteor 1.3.rc.5] Update release 1.3 rc5 promise_server.js error

### ISSUE THREAD

**Issue by RWizard** [meteor/meteor#6555]
***3 Upvotes*** Update from rc4 to rc5  error with /meteor-promise/promise_server.js:116
system: OS X 10.11.3
![2016-03-22 9 54 40](https://cloud.githubusercontent.com/assets/190453/13944200/4b5ef2fe-f014-11e5-9889-6170490a5fc6.JPG)

**Comment by danlg** [comment]
same issue

**Comment by jorisroling** [comment]
same here

**Comment by alamont** [comment]
Same on Windows 10

**Comment by cismous** [comment]
+1

**Comment by M4v3R** [comment]
Same issue here while updating from 1.2.2-faster-rebuilds, on OSX 10.11.3.

**Comment by miri-am** [comment]
+1

**Comment by DanielDornhardt** [comment]
+1 - Here too

**Comment by M4v3R** [comment]
Do you guys have `angular:angular` package added to your project? It seems that the issue is somewhere in angular dependencies, specifically while parsing `plugin.compileNGTemplate.os`.

**Comment by M4v3R** [comment]
I've nailed down this issue to a parsing problem in `bundler.js`. I fixed it by adding additional parsing rule, as you can see in this pull request #6559.

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.6`](https://github.com/meteor/meteor/issues/6266#issuecomment-199903292), thanks to #6559 and @M4v3R!
