### ISSUE TITLE
Build time jumps from 6 seconds to 40 seconds when switching from beta 12 to rc3/6

### ISSUE THREAD

**Issue by tomRedox** [meteor/meteor#6561]
I'm seeing really slow rebuild times since rc3 that are still present in rc6, is anyone else experiencing this?  

In beta 12 My project takes 5-6 seconds from hitting save to the browser finishing refreshing.  That then jumps to 35-40 seconds when I move to rc3 or rc6.

This is on Windows 8.1 64 bit and I'm testing against our Simple CRM example: https://github.com/tomRedox/simpleCRM.  

(I've done a meteor reset but that hasn't made any difference)

**Comment by benjamn** [comment]
Can you reproduce this running meteor from a [checkout](https://github.com/meteor/meteor#slow-start-for-developers)? If so, I would like to know what effect [this commit](https://github.com/meteor/meteor/commit/b56f4d58fd28c44db7ff53ce234aef9684967f18) has (you can revert it with `git revert b56f4d58fd28c44db7ff53ce234aef9684967f18`).

**Comment by benjamn** [comment]
I think this will be fixed in [`1.3-rc.8`](https://github.com/meteor/meteor/issues/6266#issuecomment-200069991).

**Comment by tomRedox** [comment]
@benjamn it's telling me that rc-8 isn't available on Windows, do I need to wait for files to propogate?

**Comment by benjamn** [comment]
I can confirm `meteor update --release 1.3-rc.8` works in the Windows command prompt for me, but I suppose there might be a time delay, or a caching issue if it failed when you tried earlier. Try again?

**Comment by tomRedox** [comment]
Just tried again, still getting this:

```
C:\websites\loler>meteor update --release 1.3-rc.8
This project uses Meteor 1.3-rc.8, which isn't available on Windows. To work with this app on all supported platforms, use meteor update --release METEOR@1.2.1 to pin
this app to the newest Windows-compatible release.
```

**Comment by tomRedox** [comment]
The download just started working for me. I'll report back once it's finished downloading and I've tested it.

**Comment by tomRedox** [comment]
Blocked by: https://github.com/meteor/meteor/issues/6568

**Comment by tomRedox** [comment]
Fixed by rc.9 - thank you :)
