### ISSUE TITLE
Better server-side error message

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6562]
I can't count the number of hours I've spent tracking down the infamous `Exited with code: 1` error.

This typically happens because a variables that does not exist in the current scope was referenced. Meteor should know what file it was in when the error occurred - is it possible to get a better error message? At least something that points to the file in question that was being run when the error occurred.

**Comment by clayne11** [comment]
Here's a great example. Using `cosmos:browserify` in Meteor 1.2 I get the following error message if I've missed an import:

```
   packages/casalova:browserify-deps/client.browserify.js: Cannot find module 'leaflet-draw' from
   '/Users/clayne/workspace/r3ntr_meteor/packages/casalova-browserify-deps/.npm/package'
```

With Meteor 1.3 and `import`, I get absolutely no message when I have a typo on an import and the app will just crash. That's a pretty terrible experience as a developer.

**Comment by benjamn** [comment]
Are you set up to run `meteor` from a checkout? I just pushed df273f3cb4ffde81d10858d77717b69100295768 and 11cbd89e1ba8c2a41bbb2925d400d1b46fddbd24 to the `release-1.3` branch, and I'm hoping they help with this issue.

**Comment by benjamn** [comment]
Ok, I ended up pushing a series of commits to help with missing module problems: https://github.com/meteor/meteor/compare/7650bb0a0118e223187d6d37357aa422f4be0f40...58a7082aa30fd97475c436bcdae8c41177cf7294

This will be going out in `1.3-rc.10` as soon as possible.

**Comment by benjamn** [comment]
Implemented partially (hopefully adequately?) in [`1.3-rc.10`](https://github.com/meteor/meteor/issues/6266#issuecomment-200906878).

**Comment by benjamn** [comment]
I accidentally disabled the warnings in `1.3-rc.11`, so this won't really be ready to try until `1.3-rc.12`. Sorry about that.

**Comment by clayne11** [comment]
Is that going to be out today?

**Comment by benjamn** [comment]
Yes! [`1.3-rc.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-201058454) should be out now.

**Comment by clayne11** [comment]
So this fixes the issue for Npm modules but I can still have the issue with Meteor packages. I was hoping to get a fix where I would know when a Meteor package import comes up undefined, either because the package is undefined or the variable is undefined.

For Npm dependencies I was already able to solve this using `estlint-plugin-import` which is actually better since it's static analysis and thus much faster. It's a much larger issue for Meteor package imports.
