### ISSUE TITLE
[1.3-rc.3] Builds take extreme amount of disk space.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6565]
We've got a server that has 2.1 free GB of space, and it fills up when the app is being built. It might be related to [this issue](https://forums.meteor.com/t/massive-linker-directory-26gb/19396) reported in the forums.

**Comment by trusktr** [comment]
On second thought, I'm not sure what the problem is. Will report back if I find more details.

**Comment by tmeasday** [comment]
Ok, I'll close this for now, let us know.

**Comment by ffxsam** [comment]
I wouldn't mind if this issue re-opened. There seems to be an issue here:

https://forums.meteor.com/t/should-meteor-get-this-big-14-gigs/19904

Maybe Meteor could auto cleanup once in a while?

**Comment by tmeasday** [comment]
@ffxsam sounds like a slightly different issue (this was an issue with build size, yours is with `~/.meteor`). Maybe open a new issue?

**Comment by ffxsam** [comment]
Ah, I missed that detail. Will do, thanks!
