### ISSUE TITLE
[1.3-rc] Build fails unless I have chimp in my node_modules folder

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6566]
I can only build my project if I have `chimp` installed in my `node_modules` folder. I have no idea why, I'm just getting the dreaded `Exited with code: 1`.

I can't create a reproduction since I have no idea what's causing the issue.

If I remove `chimp` my app fails to start but if I add it, everything runs fine.

This is an issue for two reasons:

1) I only use `chimp` for tests - it shouldn't affect running the app.
2) I cannot deploy with `chimp` in my `node_modules` folder due to #6537 so I am effectively stuck.

I noticed that `chimp` has a dependency on `fibers` and I tried installing `fibers` on it's own but that doesn't fix the issue either so I'm pretty much out of ideas.

Any ideas on what might be causing this issue?

**Comment by clayne11** [comment]
Figured it out through process of elimination of installing all of `chimp`s dependencies.

I was `import request` but I forgot to `npm install --save request` and so it wasn't in my `node_modules` folder.

The build errors I get in Meteor are **unbelivably** frustrating.

This leads back to #6562. PLEASE give us better error messages. When I'm missing an Npm dependency I need to know with an error message, not a random failure.

**Comment by benjamn** [comment]
I agree with you! I'll see if I can add a helpful warning to the `ImportScanner` in a low-risk way (so that it can be included in 1.3).

**Comment by clayne11** [comment]
This would literally save me **hours** of debugging.
