### ISSUE TITLE
[1.3-rc.7] Meteor OS X build servers not working

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#6567]
I'm attempting to build my package, nathantreid:css-modules, on the Meteor build servers. I've published for Linux and Windows, but on Mac I've been unable to complete the build process for the last hour or two.

I'm using the command `sudo meteor admin get-machine os.osx.x86_64` as directed by Meteor publish.

A couple times, I've received the message `Error from build farm: Sorry, no machines available now. Try again later. [try-again-later]`

At one point, I was assigned build machine that gave the error: `-bash: meteor: command not found`

Most of the time, I see this:
``` bash
build:~ meteor$ meteor publish-for-arch nathantreid:css-modules@1.0.0-beta.9
   Downloading meteor-tool@1.2.5-rc.7...     |                                     
Connection to 199.19.86.153 closed by remote host.
```

**Comment by benjamn** [comment]
Thanks for the report. This does happen sometimes, but I would hope you've been able to get a machine in the meantime?

**Comment by nathantreid** [comment]
Unfortunately, no. I've created a reproduction repo: https://github.com/nathantreid/sass-test-package

It's just a simple build 1.3 build plugin with node-sass added via npm so that I will need to use Meteor build servers.
I built it using Meteor 1.3.1.
When I attempt to publish-for-arch, I get the same error: 
`Connection to 199.19.86.153 closed by remote host.`

**Comment by nathantreid** [comment]
Well, i guess I just got unlucky all those other times, because I finally managed to publish for OS X!
