### ISSUE TITLE
ReferenceError: is not defined with Meteor postgres

### ISSUE THREAD

**Issue by norbertoru** [meteor/meteor#6569]
I have this error when run scrip.sh :

=> Started proxy.
=> Exited with code: 8
W20160318-23:51:48.129(-3)? (STDERR) W20160318-23:51:48.132(-3)? (STDERR) ReferenceError: globals is not defined W20160318-23:51:48.132(-3)? (STDERR) at meteorInstall.simple-todos.js (simple-todos.js:2:1) W20160318-23:51:48.132(-3)? (STDERR) at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1) W20160318-23:51:48.132(-3)? (STDERR) at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1) W20160318-23:51:48.133(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/app/app.js:134:1 W20160318-23:51:48.133(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:242:10 W20160318-23:51:48.131(-3)? (STDERR) /home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267 W20160318-23:51:48.133(-3)? (STDERR) at Array.forEach (native) W20160318-23:51:48.133(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:137:5 W20160318-23:51:48.131(-3)? (STDERR) throw(ex); W20160318-23:51:48.133(-3)? (STDERR) at Function..each..forEach (/home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11) W20160318-23:51:48.131(-3)? (STDERR) ^ W20160318-23:51:50.050(-3)? (STDERR)
W20160318-23:51:50.050(-3)? (STDERR) /home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267 W20160318-23:51:50.050(-3)? (STDERR) throw(ex); W20160318-23:51:50.051(-3)? (STDERR) ^ W20160318-23:51:50.070(-3)? (STDERR) ReferenceError: globals is not defined W20160318-23:51:50.070(-3)? (STDERR) at meteorInstall.simple-todos.js (simple-todos.js:2:1) W20160318-23:51:50.071(-3)? (STDERR) at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1) W20160318-23:51:50.071(-3)? (STDERR) at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1) W20160318-23:51:50.071(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/app/app.js:134:1 W20160318-23:51:50.071(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:242:10 W20160318-23:51:50.071(-3)? (STDERR) at Array.forEach (native) W20160318-23:51:50.072(-3)? (STDERR) at Function..each..forEach (/home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11) W20160318-23:51:50.072(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:137:5 => Exited with code: 8 W20160318-23:51:51.519(-3)? (STDERR)
W20160318-23:51:51.520(-3)? (STDERR) /home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267 W20160318-23:51:51.520(-3)? (STDERR) throw(ex); W20160318-23:51:51.520(-3)? (STDERR) ^ W20160318-23:51:51.539(-3)? (STDERR) ReferenceError: globals is not defined W20160318-23:51:51.540(-3)? (STDERR) at meteorInstall.simple-todos.js (simple-todos.js:2:1) W20160318-23:51:51.540(-3)? (STDERR) at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1) W20160318-23:51:51.540(-3)? (STDERR) at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1) W20160318-23:51:51.540(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/app/app.js:134:1 W20160318-23:51:51.540(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:242:10 W20160318-23:51:51.541(-3)? (STDERR) at Array.forEach (native) W20160318-23:51:51.541(-3)? (STDERR) at Function..each..forEach (/home/norberto/.meteor/packages/meteor-tool/.1.1.13-modules.8.1y5c8sp++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11) W20160318-23:51:51.541(-3)? (STDERR) at /home/norberto/Proyectos/facol/.meteor/local/build/programs/server/boot.js:137:5 => Exited with code: 8 => Your application is crashing. Waiting for file change.

- norberto@norberto:~/Proyectos/facol> meteor --version
Meteor 1.3-modules-beta.8 

norberto@norberto:~> meteor --version
Meteor 1.2.1

repository. Packages that have been split from core and their repositories are:

- Blaze: https://github.com/meteor/blaze

**Comment by abernix** [comment]
The problem you're referring to is too vague to accurately provide help, however you were on a beta of Meteor at the time you reported this.  Meteor is now stable in 1.3.2.4 and your problem is most likely explained in the [Meteor Guide about Migrating to 1.3](guide.meteor.com/1.3-migration.html).  Also, try asking for help on either the [Meteor Forums](https://forums.meteor.com) or StackOverflow.

After all this, if you are still having problems, please submit a complete reproduction for this issue.  That snippet by itself is not enough to isolate the problem, or even to determine if the problem is in Meteor itself: [More information on reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)
