### ISSUE TITLE
Feature request: EventEmitter that emits same events on client and server.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#6575]
The use case for this is if you have some execution without persistent data (eg, non-mongo backed) that occurs on both client and server. Something like this could be in common code.
```
import {EventEmitter} from 'events';

export class Download extends EventEmitter {
  constructor() {
    super(...arguments);
  }
}
```

It would be nice if it could emit events on both client and server and respond to them. Eg, if you had a meteor method:

```
Meteor.methods({
  'connect': async function (download) {
    this.emit('started');
    await download.run();
  }
});
```

Then the client could respond to the "started" event because it receives it as well

**Comment by clayne11** [comment]
I use [raix:eventemitter](https://atmospherejs.com/raix/eventemitter) for exactly this purpose.

**Comment by benjamn** [comment]
`raix:eventemitter` looks awesome for this!
