### ISSUE TITLE
Server restarts on client file changes in imports/ directory

### ISSUE THREAD

**Issue by D1no** [meteor/meteor#6576]
# The server seems to eagerly watch all files in the `imports/` directory, except for the ones under a `/client/` sub-folder.
- [ ] Prevent server restarts on file changes belonging to the client AST. This should work when changing a client file inside the `imports/` folder, but outside of a `client/`subfolder (`imports/client/`).
- [ ] Please have the server ignore files inside the `imports/` folder, except they are
  - imported to a server file (server AST)

The `imports/` is finally here to **avoid eager loading** and separate client and server files by purpose instead of environment. But right now, the watcher isn't: Files that are outside of `imports/client` still trigger a restart on the server. Or are at least tracked by the server.

The official todos example uses `api/` , `startup/` and `ui/` folders inside the `imports` folder. Touching any client-related files also leads to some checks by the server. That also affects the official [meteor todo app when changed to a flatter file hirarchy](https://github.com/D1no/todos):  

``` text
.
├── client/
│   ├── main.html
│   ├── main.js      #import "./imports/client.entry";
│   └── main.less    #@import "{}/imports/style.entry.less";
...
│ +---------------------- Main Dev Folder -----------------+
│
├── imports/
│   ├── #components/ # UI Components & Extensions
│   ├── _screens/    # Compositions of UI Components
│   ├── api/         # Collections, Methods and Pub/Sub
│   ├── lib/         # Helpers & former Meteor Packages
│   ├── server/      # Strict security related files
│   ├── stylesheets/ # Global styles (if used)
│   ├── client.entry.jsx +--->
│   ├── server.entry.js  |--->  Loader agnostic / entries
│   └── style.entry.less +--->
│
│ +--------------------------------------------------------+
...
├── server/
│   └── main.js       #import "./imports/server.entry";
```

This is not very noticeable in small apps.

But in large apps, and more importantly, in sophisticated build plugins like `webpack:webpack` ([Github Issue](https://github.com/thereactivestack/meteor-webpack/issues/119#issuecomment-200323870)) `gadicc:ecmascript-hot` ([Forum Issue](https://forums.meteor.com/t/react-hotloading-in-native-meteor-is-ready-i-e-no-webpack/17523/79?u=dinos) / [Github Repo](https://github.com/gadicc/meteor-react-hotloader)):

You constantly get a 

```
=> Meteor server restarted
```

even though working on client only files inside the `imports/` folder.

If even, the server should only watch `/server/` sub folders inside the `imports` folder.

**Comment by eXon** [comment]
I think it would be great to have a better control over the client / server restart within a compiler plugin.

As an example, webpack knows when a client file or a server file has been changed. We have a hook for that. It would be great if we could disable the entire system and trigger them manually.

**Comment by gbisheimer** [comment]
@D1no, I also have the same issue. I've also noticed that if you create a file inside imports folder that is not referenced from any other file, and include a typo in that file, that will throw an error and prevent the server from starting.

I've tried with a file error.js with just a ? inside and got

```
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   imports/error.js:1: Unexpected token (1:0)

   While processing files with ecmascript (for target os.linux.x86_64):
   imports/error.js:1: Unexpected token (1:0)

=> Your application has errors. Waiting for file change.
```

But that file shouldn't be evaluated as isn't imported from any other file. I also tested with a valid instruction like a `console.log('Testing errors');`  and the server start correctly but nothing is printed on the console (as expected).

It seems that those files are watched and also parsed for errors, but not executed.

**Comment by Akryum** [comment]
Doesn't seem to be resolved in in Meteor 1.3.2.2, despite the changelog.

**Comment by oswaldoacauan** [comment]
Any news? We are facing the same issue... :/

**Comment by kachkaev** [comment]
@benjamn how about adding this to 1.5 milestone together with some sort of `.meteorignore` (https://github.com/meteor/meteor/issues/6002, https://github.com/meteor/meteor/issues/330, https://github.com/meteor/meteor/issues/1534, https://github.com/meteor/meteor/issues/1806, etc.)? This can significantly improve the dev experience as the build times will decrease in a variety of circumstances.

**Comment by Pruxis** [comment]
Has this been adressed yet, as I have the same issue as stated above but cannot find anything in the documentation to fix this.

**Comment by mcissel** [comment]
@D1no thanks! I had't thought of adding another 'client' folder _INSIDE_ the 'imports' folder. Now I'm back to quick, client-only, build times. I was just about to dive into webpack. Phew! Thanks boss.

I'll also probably start using start using [Kadira's Story Book](https://voice.kadira.io/introducing-react-storybook-ec27f28de1e2) soon.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Server%20restarts%20on%20client%20file%20changes%20in%20imports%2F%20directory&body=Migrated%20from:%20meteor/meteor%236576) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by benjamn** [comment]
Both `client/imports` and `imports/client` should work. However, if you find that not to be the case, please do click the link in @hwillson's comment to migrate the issue to the new feature request repo!

**Comment by avalanche1** [comment]
Isn't that bug, not a new feature?
