### ISSUE TITLE
[Meteor 1.3-rc.9] not support windows ?

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6579]
try to update...
`meteor update --release 1.3-rc.9`
or
`meteor create rc9 --release 1.3-rc.9`
```
This project uses Meteor 1.3-rc.9, which isn't available on Windows. To work with this app on all supported
platforms, use meteor update --release METEOR@1.2.1 to pin this app to the newest Windows-compatible release.
```

**Comment by tomRedox** [comment]
rc9 download *is* working for me on Windows, but I had this same issue yesterday with rc.8.  I kept retrying and about 8 hours after release it started working, not sure why.  I'm guessing it's taking a while to propagate out to the download servers.

**Comment by lyquocnam** [comment]
i dont know why, but still not working for me on windows 10 x64.
`which isn't available on Windows`
