### ISSUE TITLE
Add a way to validate Accounts.changePassword?

### ISSUE THREAD

**Issue by minfawang** [meteor/meteor#6583]
The source code of changePassword method is defined [here](https://github.com/meteor/meteor/blob/5931bcdae362e1026ceb8a08e5a4b053ce5340b7/packages/accounts-password/password_server.js#L413-L458). 

It appears to be no way to stop user from calling Accounts.changePassword from the client, and there is no way to stop the user changing the password to anything as long as the user got the old password right. 

I feel it makes sense to allow to add an optional custom validation logic here. We have `Accounts.validateNewUser`, why not have something like `Accounts.validatePassword`?

**Comment by helfer** [comment]
Can you explain the use case for adding this functionality? Maybe there's another way to achieve this.

**Comment by arthurlataks** [comment]
@helfer I assume that @minfawang was meaning that if for instance he wants his users to have password of at least 6 characters and contain only letters, then he has no way how to ensure it, because anyone can run `Accounts.changePassword('oldValidOne', 'newInvalidPassword')`

**Comment by premasagar** [comment]
I agree. I would be very helpful to be able to set a minimum password length.

Related, `accounts-ui` has a hard-coded 6 character limit in its [`validatePassword`](https://github.com/meteor/meteor/blob/master/packages/accounts-ui-unstyled/login_buttons.js#L97) method. That feels too low in this day and age.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20way%20to%20validate%20Accounts.changePassword%3F&body=Migrated%20from:%20meteor/meteor%236583) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
