### ISSUE TITLE
[1.3-rc.10] isn't available on windows

### ISSUE THREAD

**Issue by bosung90** [meteor/meteor#6584]
***1 Upvote*** `meteor update --release 1.3-rc.10`

```
This project uses Meteor 1.3-rc.10, which isn't available on Windows. To
work with this app on all supported platforms, use
meteor update --release METEOR@1.2.1 to pin this app to the newest
Windows-compatible release.
```

I am on Windows 10 x64

**Comment by lyquocnam** [comment]
+1 me too Windows 10 x64

**Comment by lyquocnam** [comment]
i think we have to wait for server change, 
1.3-rc.9 now can available download with windows. this must take about 10 hours for available....

**Comment by lyquocnam** [comment]
this work for me now  - 1.3-rc.10 for windows 10 x64.

**Comment by bosung90** [comment]
Weird, I tried again but I get same error messages. Maybe it is cached somewhere?

**Comment by Rebolon** [comment]
IT works for me :

>  meteor update --release 1.3-rc.10                            
                                                                
Changes to your project's package version selections from updati
                                                                
allow-deny             upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
autopublish            upgraded from 1.0.5-rc.8 to 1.0.5-rc.10  
autoupdate             upgraded from 1.2.6-rc.8 to 1.2.6-rc.10  
babel-compiler         upgraded from 6.5.2-rc.8 to 6.5.2-rc.10  
babel-runtime          upgraded from 0.1.6-rc.8 to 0.1.6-rc.10  
base64                 upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
binary-heap            upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
blaze                  upgraded from 2.1.5-rc.8 to 2.1.5-rc.10  
blaze-html-templates   upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
blaze-tools            upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
boilerplate-generator  upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
caching-compiler       upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
caching-html-compiler  upgraded from 1.0.4-rc.8 to 1.0.4-rc.10  
callback-hook          upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
check                  upgraded from 1.1.2-rc.8 to 1.1.2-rc.10  
ddp                    upgraded from 1.2.3-rc.8 to 1.2.3-rc.10  
ddp-client             upgraded from 1.2.3-rc.8 to 1.2.3-rc.10  
ddp-common             upgraded from 1.2.3-rc.8 to 1.2.3-rc.10  
ddp-server             upgraded from 1.2.4-rc.8 to 1.2.4-rc.10  
deps                   upgraded from 1.0.10-rc.8 to 1.0.10-rc.10
diff-sequence          upgraded from 1.0.3-rc.8 to 1.0.3-rc.10  
ecmascript             upgraded from 0.4.1-rc.8 to 0.4.1-rc.10  
ecmascript-runtime     upgraded from 0.2.8-rc.8 to 0.2.8-rc.10  
ejson                  upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
es5-shim               upgraded from 4.5.8-rc.8 to 4.5.8-rc.10  
fastclick              upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
geojson-utils          upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
hot-code-push          upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
html-tools             upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
htmljs                 upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
http                   upgraded from 1.1.3-rc.8 to 1.1.3-rc.10  
id-map                 upgraded from 1.0.5-rc.8 to 1.0.5-rc.10  
insecure               upgraded from 1.0.5-rc.8 to 1.0.5-rc.10  
jquery                 upgraded from 1.11.6-rc.8 to 1.11.6-rc.10
launch-screen          upgraded from 1.0.8-rc.8 to 1.0.8-rc.10  
livedata               upgraded from 1.0.16-rc.8 to 1.0.16-rc.10
logging                upgraded from 1.0.10-rc.8 to 1.0.10-rc.10
meteor                 upgraded from 1.1.12-rc.8 to 1.1.12-rc.10
meteor-base            upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
minifier-css           upgraded from 1.1.9-rc.8 to 1.1.9-rc.10  
minifier-js            upgraded from 1.1.9-rc.8 to 1.1.9-rc.10  
minimongo              upgraded from 1.0.12-rc.8 to 1.0.12-rc.10
mobile-experience      upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
mobile-status-bar      upgraded from 1.0.10-rc.8 to 1.0.10-rc.10
modules                upgraded from 0.5.1-rc.8 to 0.5.1-rc.10  
modules-runtime        upgraded from 0.6.1-rc.8 to 0.6.1-rc.10  
mongo                  upgraded from 1.1.5-rc.8 to 1.1.5-rc.10  
mongo-id               upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
npm-mongo              upgraded from 1.4.41-rc.8 to 1.4.41-rc.10
observe-sequence       upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
ordered-dict           upgraded from 1.0.5-rc.8 to 1.0.5-rc.10  
promise                upgraded from 0.6.4-rc.8 to 0.6.5-rc.10  
random                 upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
reactive-dict          upgraded from 1.1.5-rc.8 to 1.1.5-rc.10  
reactive-var           upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
reload                 upgraded from 1.1.6-rc.8 to 1.1.6-rc.10  
retry                  upgraded from 1.0.5-rc.8 to 1.0.5-rc.10  
routepolicy            upgraded from 1.0.8-rc.8 to 1.0.8-rc.10  
session                upgraded from 1.1.3-rc.8 to 1.1.3-rc.10  
spacebars              upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
spacebars-compiler     upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
standard-minifier-css  upgraded from 1.0.4-rc.8 to 1.0.4-rc.10  
standard-minifier-js   upgraded from 1.0.4-rc.8 to 1.0.4-rc.10  
templating             upgraded from 1.1.7-rc.8 to 1.1.7-rc.10  
templating-tools       upgraded from 1.0.2-rc.8 to 1.0.2-rc.10  
tracker                upgraded from 1.0.11-rc.8 to 1.0.11-rc.10
ui                     upgraded from 1.0.9-rc.8 to 1.0.9-rc.10  
underscore             upgraded from 1.0.6-rc.8 to 1.0.6-rc.10  
url                    upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
webapp                 upgraded from 1.2.6-rc.8 to 1.2.6-rc.10  
webapp-hashing         upgraded from 1.0.7-rc.8 to 1.0.7-rc.10  
                                                                
meteor-install-1.3: updated to Meteor 1.3-rc.10.

**Comment by smooJitter** [comment]
Ok so here we go again. (same message w/ rc.9-13)  I see the issue closing when just one person finds that it works but I don't understand why it keeps closing with out a resolution.

> meteor update --release 1.3-rc.13
This project uses Meteor 1.3-rc.13, which isn't available on Windows. To work with this app on all
supported platforms, use meteor update --release METEOR@1.2.1 to pin this app to the newest
Windows-compatible release.

**Comment by zol** [comment]
I think for some sort of caching reason new RCs take longer to propagate for Windows users.

**Comment by smooJitter** [comment]
I actually got it work by first starting a fresh 1.2.1 installation (meteor install 1.3-rc.13) then upgrad to 1.3-rc.13.  I must have misunderstood the error message.  Given the message read, "update --releaseMETEOR@1.2.1 to pin this app to the newest...", I thought I'd start from 1.2.1 then run meteor update instead.
