### ISSUE TITLE
[1.3-rc.10] Load script file twice

### ISSUE THREAD

**Issue by TeemoWan** [meteor/meteor#6587]
![143abcdb-8267-41b1-ae34-23ea097c43d0](https://cloud.githubusercontent.com/assets/950957/14018884/fc458018-f20a-11e5-9d3f-9441cc38b05f.png)

And in production, didn't load styles file

**Comment by vadimrostok** [comment]
I've had a similar problem, but it disappeared after update to 1.3.

**Comment by abernix** [comment]
There isn't enough here to reproduce this problem, debug this problem or say if it's fixed.  Please open a new issue with the appropriate information for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) if you're still experiencing this issue.  Thanks!
