### ISSUE TITLE
[1.3-rc.10] Not importing css from SweetAlert NPM

### ISSUE THREAD

**Issue by servermeta** [meteor/meteor#6588]
Hi guys, 

when I install SweetAlert NPM module it doesn't import its CSS files. 

```
meteor create test --release 1.3-rc.10
cd test
npm init -f
npm install -S sweetalert
```

then add:

`import { swal } from 'sweetalert';`

when I launch from console swal('hello') the warning is loaded correctly, but it has no CSS so it looks ugly. 

I have to manually add the CSS files to the client folder. If I install sweetalert from atmosphere it works correctly.

**Comment by zol** [comment]
CSS is not automatically loaded from npm modules. We'll be looking closer at asset loading in a future release.

**Comment by servermeta** [comment]
Is there any workaround for now?

**Comment by zol** [comment]
Yes, copy the assets into `/public`

**Comment by serkandurusoy** [comment]
So @zol is it in your opinion

* a valid solution to manually drill down assets from npm libraries, copy them over to another folder, make sure you have not missed any new/changed assets after each update?
* Does this solution really allow *closing* this issue?
* Does this not contradict with the advertisement "meteor now supports complete npm integration"?

Sad...

**Comment by zol** [comment]
Closed because there are other issues tracking this like #6098 #6037 . The implementation is quite involved hence it was bumped from 1.3

**Comment by serkandurusoy** [comment]
Great! Thank you for the references. I had already discovered only one of those.

**Comment by dnish** [comment]
@zol Are you serious? Why should we still use any packages, when your recommend way is to copy assets into the public folder? Why shouldn't we copy all JS files also into the public folder? Forget about npm, let's go the old copy & paste way.

**Comment by nosizejosh** [comment]
@zol is this feature (import css from node modules) implemented n any release of meteor?
