### ISSUE TITLE
[1.3-rc.12] Meteor can't find one of my Npm dependencies

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6589]
I just updated to `1.3-rc.12` from `1.3-rc.8`.

Under `1.3-rc.8` my build worked complete fine. Under `1.3-rc.12` the app builds fine on the server but when it hits the browser it's complaining:

```
Uncaught Error: Cannot find module 'react-komposer'
    require @ modules-runtime.js?hash=939c79d…:95
    meteorInstall.node_modules.meteor.casalova:map-search.both.map-search-listing-hoc.js @ map-search-listing-hoc.js:4
    fileEvaluate @ modules-runtime.js?hash=939c79d…:158
    require @ modules-runtime.js?hash=939c79d…:92
    (anonymous function) @ casalova_map-search.js?hash=4fca0e9…:1005
    (anonymous function) @ casalova_map-search.js?hash=4fca0e9…:1018
    casalova_reducers.js?hash=027b0a7…:17
    Uncaught TypeError: Cannot read property 'MapSearch' of undefined
    (anonymous function) @ casalova_reducers.js?hash=027b0a7…:17
    (anonymous function) @ casalova_reducers.js?hash=027b0a7…:83
```

**Comment by clayne11** [comment]
It looks like `react-komposer-fork` doesn't have a `main` attribute in `package.json`. Without a `main` I think we should default to `index.js`. I'm assuming that's what was happening in `1.3-rc.8`.

**Comment by benjamn** [comment]
[This commit](https://github.com/meteor/meteor/commit/dc0345b0ff4dc7809c3742145bf6d49eb47ffa27) is probably to blame.

**Comment by benjamn** [comment]
Are you installing/using `react-komposer-fork` or `react-komposer`? It looks like you might be importing `react-komposer` when `react-komposer-fork` is what's installed? Or maybe `react-komposer-fork` is accidentally importing `react-komposer` (because it's a fork of the original)?

**Comment by clayne11** [comment]
I’m using `react-komposer-fork` - my fork isn't fully up to date though so I tried `react-komposer` to see if my fork was the issue and it didn't work either.

**Comment by benjamn** [comment]
I can install and import both packages, so I'm not sure what's going on…

**Comment by clayne11** [comment]
With `react-komposer-fork@1.3.5` I'm having this issue. i updated my fork to `react-komposer-fork@1.4.3` and included a `main` attribute and the issue is resolved.

**Comment by themeteorchef** [comment]
@clayne11 bumped into this same error with `react-komposer`. I did an uninstall and reinstall and then the app booted fine:

```
npm uninstall react-komposer
npm install react-komposer
```

Modified the `react-komposer` version in `package.json` manually.

**Comment by clayne11** [comment]
Interesting.

As I noted above I was able to reproduce the issue after uninstalling and reinstalling `react-komposer-fork@1.3.5`.

I still think the issue is related to the package not have a `main` attribute.

**Comment by tmeasday** [comment]
Sounds like it was a problem with `react-komposer` which is now fixed.
