### ISSUE TITLE
Possible issue with ES6 imports

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6592]
I just ran into this problem, and thought it was rather odd. I figured I'd report as a bug, just in case it is, before 1.3 is out. Though I just might be doing something wrong.

Meteor 1.3 beta 12. (trying to stay as stable as possible - if one of the newer RCs is just as stable, let me know)

In a file `/client/components/AppHeader.js`, I have this:

```
import React, { PropTypes } from 'react';
import { FlowRouter } from 'meteor/kadira:flow-router';
import L11Logo from './L11Logo';
import * as routes from '../routes';
import {
  Avatar,
  IconMenu,
  MenuItem,
} from 'material-ui/lib';

const navLinks = [
  { label: 'Dashboard', route: routes.ROUTE_DASHBOARD },
  { label: 'Insights', route: routes.ROUTE_INSIGHTS },
  { label: 'Tests', route: routes.ROUTE_TESTS },
  { label: 'Rules', route: routes.ROUTE_RULES },
];
```

And in `/client/routes.js`:

```
export const ROUTE_HOME = 'home';
export const ROUTE_LOGIN = 'login';
export const ROUTE_DASHBOARD = 'dashboard';
export const ROUTE_INSIGHTS = 'insights';
export const ROUTE_TESTS = 'tests';
export const ROUTE_RULES = 'rules';
```

The `navLinks.route` property is `undefined` for some reason. But if I move `navLinks` inside the `render` method, it works fine:

```
export default AppHeader = (props) => {
  const navLinks = [
    { label: 'Dashboard', route: routes.ROUTE_DASHBOARD },
    { label: 'Insights', route: routes.ROUTE_INSIGHTS },
    { label: 'Tests', route: routes.ROUTE_TESTS },
    { label: 'Rules', route: routes.ROUTE_RULES },
  ];
```

The thing is, I want to get the object literals _out_ of `render`, as they can be problematic and cause unnecessary re-renders. What's going on here?

**Comment by Deilv** [comment]
First of all, you really should check this using the latest rc in case it has already been solved.
Having said that, you only provide part of your code and expect a solution for the missing elements. How do you check the contents of navLinks? In which file are you trying to access it?

**Comment by ffxsam** [comment]
Still have the problem in RC12. And I can't exactly dump all the code here, otherwise I'd be breaking NDA. The relevant parts are above.

The bottom line is, I'm importing something and it's coming up undefined. But I can't replicate it in a totally new project.

**Comment by ffxsam** [comment]
Here's a bigger picture of what's going on. Note the two `console.log` statements.

```
import React, { PropTypes } from 'react';
import { FlowRouter } from 'meteor/kadira:flow-router';
import L11Logo from './L11Logo';
import * as routes from '../routes';
import {
  Avatar,
  Dialog,
  IconMenu,
  MenuItem,
} from 'material-ui/lib';

import { profileMenuItems } from '../layouts/MainLayout';
import OrgSwitcher from './OrgSwitcher';

console.log(`dashboard route at ${performance.now()}:`, routes.ROUTE_DASHBOARD);

const anchorOrigin = {
  horizontal: 'right',
  vertical: 'top',
};
const targetOrigin = {
  horizontal: 'right',
  vertical: 'top',
};

function navigateTo(event, link) {
  FlowRouter.go(link.route);
}

export default AppHeader = (props) => {
  console.log(`dashboard route at ${performance.now()}:`, routes.ROUTE_DASHBOARD);
  // ...
```

And in the browser console, I see:

>dashboard route at 2367.4950000000003: undefined
>dashboard route at 3340.8250000000003: dashboard

So outside the stateless function, at 2367ms, the thing I just imported is undefined. And then one second later, when the component gets around to rendering, it's fine. But in a totally clean project, this glitch doesn't occur. I wonder if it has something to do with the build system?

**Comment by benjamn** [comment]
Symbols imported using `import` are not really variables but [mutable bindings](https://github.com/meteor/meteor/issues/6381#issuecomment-193938592), and may be redefined (usually from `undefined` to something else) as the exporting module gets around to defining them. This behavior is usually only noticeable in cases of circular dependencies, and helps resolving those cycles when possible. Further explanation [here](https://github.com/meteor/meteor/issues/6364#issuecomment-193942790).

Try turning off source maps and adding `debugger` statements before the relevant `export` statements and symbol usage sites to get a better sense for when the exports are defined vs. when they are used.

As you've discovered, observing the value of an imported symbol later (after all the modules participating in a dependency cycle have loaded) gives the symbol a better chance of being defined by then. Avoiding circular dependencies also prevents the issue, though I wouldn't leap to the conclusion that they are the "root" of the problem.

**Comment by Deilv** [comment]
You can also read more about it [here](http://exploringjs.com/es6/ch_modules.html).

**Comment by ffxsam** [comment]
Ah. So in short, make sure I keep my references to imported variables inside React components and functions. Thanks!
