### ISSUE TITLE
[1.3-rc.12] script tag not end of body tag

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6594]
i don't know this missing, should we put scripts end of body ?
currently, they are top of body tag
![script-not-end-of-body-tag](https://cloud.githubusercontent.com/assets/8347826/14058412/ae45f1de-f351-11e5-87fd-1cb6dc8473d5.PNG)

**Comment by benjamn** [comment]
Looks like the `<div>` is getting appended to the `<body>` after the scripts have run? Is this causing you problems, or just confusing?

**Comment by lyquocnam** [comment]
i remember i saw someone say meteor will put them to end of body (it will after #react-root tag)
currenlty, all be fine! i just confuse about this!

**Comment by laosb** [comment]
For a no-server-rendered app like a typical Meteor app, the position of `<script>` tags shouldn't make too much sense.
