### ISSUE TITLE
[1.3-rc.2] Incredible amounts of disk I/O, system completely unresponsive.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6595]
I'm in openSUSE, and when I save a file and a rebuild happens, the system becomes unresponsive with incredible amounts of I/O. It also happens with some other actions besides saving a file, but not sure what yet. Here's `iotop` output:

![default](https://cloud.githubusercontent.com/assets/297678/14062419/3a2e4026-f35b-11e5-84e4-0bd2aa6890a2.jpg)

You can see some of the i/o is from Google Chrome, and some is Meteor. The system  becomes 100% unresponsive until it finishes doing whatever it is doing. (Pressing alt-tab to switch windows is blocked until it all clears up, etc, everything completely unresponsive).

Don't know if it matters, but my filesystem is `btrfs` (default for openSUSE).

**Comment by trusktr** [comment]
Apparently this isn't happening if I use Firefox. I wonder if this is a problem with Meteor relating to Chrome, or a problem with Chrome itself. I'll try updating to the latest RC and see what happens. I'll also try reverting to a commit that was on Meteor 1.2.

**Comment by trusktr** [comment]
Well, the same thing finally started happening while using Firefox too, so I don't think it's a browser problem. I was getting lucky with Firefox for a while. Still investigating...

**Comment by anywhichway** [comment]
I am using v1.3 production version on Windows 10 64. I get similar behavior. Within 30 seconds of starting Meteor disk utilization goes to 97% and drops back to about 50% in about another 60 seconds. Then, as soon as I access a Meteor page using Chrome (just the intro app plus the login ui in this case) disk utilization goes up to 99% and then varys between 55% and 99% even if I close the web page. Killing the Meteor server immediately fixes the problem. The Task Manager shows that Evented I/O for V8 JavaScript (32 bit) is the issue.
I am using v1.3 production version on Windows 10 64. I get similar behavior. Within 30 seconds of starting Meteor disk utilization goes to 97% and drops back to about 35% in about another 30 seconds. Then, as soon as I access a Meteor page (just the intro app plus the login ui in this case) disk utilization goes up to 99% and then varys between 55% and 99% even if I close the web page. Killing the Meteor server immediately fixes the problem. The Task Manager shows that Evented I/O for V8 JavaScript (32 bit) is the issue.

I I access the same page using Firefox utilization hovers around 40%, tolerable, although still not great.

**Comment by abernix** [comment]
Closing as I believe this was meant to be closed a while ago (per above comment) and there have been countless performance improvements since this was opened.
