### ISSUE TITLE
[1.3-rc.13] TypeError: _regeneratorRuntime is undefined

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6597]
I'm getting that error. The error happens with the file `node_modules/async-csp/dist/channel.js` of the [async-csp](https://www.npmjs.com/package/async-csp) NPM package.

Why might this happen? I thought regenerator was included by `ecmascript` (or so)? The compiled code has

```js
var _regeneratorRuntime = require('babel-runtime/regenerator')['default'];
```

Do we need to `npm install babel-runtime`, or should `ecmascript` handle that?

**Comment by trusktr** [comment]
Oh, I forgot I posted this one: https://github.com/meteor/meteor/issues/6154.

So, I checked the async-csp package, and it has `"babel-runtime": "^6.3.19"` as a dependency, and uses regenerator like this: https://github.com/dvlsg/async-csp/blob/45202945996b1d3111e41ba00405717a9fe6b290/dist/channel.js#L114-L117. It seems like it should just work since that compiled `dist` code is importing it directly from `babel-runtime`.

Based on #6154, I tried the following:

```js
import _regeneratorRuntime from 'babel-runtime/regenerator'
if (!Object.keys(window).includes('_regeneratorRuntime'))
    window._regeneratorRuntime = _regeneratorRuntime
```

After adding that, I still get the error `TypeError: _regeneratorRuntime is undefined`! I can manually confirm in the console that `_regeneratorRuntime` exists on `window`, so I'm not sure why the error still happens.

**Comment by benjamn** [comment]
The line
```js
var _regeneratorRuntime = require('babel-runtime/regenerator')['default'];
```
assumes that `babel-runtime/regenerator` is an ES2015 module with a `default` export. If I'm right, the following line should work:
```js
var _regeneratorRuntime = require('babel-runtime/regenerator');
```
If you really need to get this code to work without changing it, you can maybe do
```js
require("babel-runtime/regenerator").default = require("babel-runtime/regenerator");
```
somewhere earlier in your code.

**Comment by trusktr** [comment]
Aha, so it appears that the version of async-csp on NPM was compiled with Babel 5. The top of the dist/channel.js file looks like this:

https://github.com/dvlsg/async-csp/blob/a37a39d3197284249be9ff2a22e0381838dca69c/dist/channel.js#L3-L19

THe latest on GitHub (not yet published to NPM) is compiled with Babel 6 and looks like this (the same pattern as with files built with Meteor and hence Babel 6):

https://github.com/dvlsg/async-csp/blob/45202945996b1d3111e41ba00405717a9fe6b290/dist/channel.js#L11-L51

Using the version `dvlsg/async-csp#master` instead of `^0.3.0` in package.json solves the problem for now, and I'll change back to an NPM version when it gets published.

**Comment by trusktr** [comment]
This brings up a larger concern in general, perhaps relating to Babel in general so posted there: https://phabricator.babeljs.io/T7245

**Comment by benjamn** [comment]
For better and worse, Babel is a fast-moving project that doesn't attempt to keep its runtime completely backwards-compatible with older versions of the compiler platform. Those libraries should be recompiled with Babel 6. I'm not an official spokesperson for Babel, but I imagine that's what they'll say on the Phabricator issue you opened.

**Comment by trusktr** [comment]
For sure. I guess for backwards support a package author can publish a new package `<package-name>-babel-5` that has the same version numbers as the main `<package-name>` package.
