### ISSUE TITLE
Add ddos protection layer to Galaxy

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6598]
Add ddos protection layer to Galaxy. Yep, we need it.
https://forums.meteor.com/t/does-galaxy-provide-ddos-protection/14584/

**Comment by stubailo** [comment]
This is not the place for feature requests for Galaxy. And in that thread, I suggested that a lot of the things involved are best solved either via a Meteor package, change to Meteor core, or a CDN service. I'd be happy to accept a PR to improve the default rate limiter rules to avoid situations where sending lots of subscriptions can crash the server.
