### ISSUE TITLE
[1.3-rc.13] Changing NPM dependencies requires meteor reset.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6600]
I often find that after modifying dependencies in package.json (changing version numbers, adding/removing packages), the app requires `meteor reset` or else the client will get `module not found` errors.

**Comment by tmeasday** [comment]
Have you tried simply restarting the server?

**Comment by trusktr** [comment]
@tmeasday Yep, it failed. It should require a server restart IMO though. `npm install something` and the app should update. That'd make it nice and easy.

**Comment by tmeasday** [comment]
@trusktr agreed (see #6627)
