### ISSUE TITLE
Update 1.3-rc.12 in Window supper slow

### ISSUE THREAD

**Issue by tamltn93** [meteor/meteor#6602]
Hi all,

I have try to update to version 1.3-rc.12 or 1.3-rc.13. But it download very slow on my Win 7 64bit.

Who have same issue like me ?

**Comment by tcastelli** [comment]
My update got stuck in downloading templating package (well it actually downloads it but after that it just stays with the text Downloading templating@1XXXX..... and never ends no matter how much I wait. If i try to stop the execution, then I see continuous fails messages of temp folder mt-XXXXX not being empty

**Comment by tamltn93** [comment]
@tcastelli Yes, I have uninstall meteor and reinstall meteor it again. And it's work. Thank you

**Comment by joetidee** [comment]
I have the same issues, stuck on "Downloading templating@1.1.7...". Don't want to uninstall Meteor, or,  if I do is there any way for Meteor to know what packages it needs for the application?

**Comment by tamltn93** [comment]
@joetidee  Currently, Meteor version 1.3 is available at Meteor website. Try install it, it work with me.

**Comment by atul-mourya** [comment]
Uninstalling and reinstall a new meteor didn't work for me. The problem is still the same. Stuck at "Downloading limemakers:three@0.75.0...  /". The download was actually finished as indicated by the progress bar, but was stuck just after it. 
Does anyone one know what the problem is?
