### ISSUE TITLE
[1.3] createContainer not defined

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6603]
Just wanted to quickly report that `createContainer` still does not work out of the box in 1.3.

Carry on! :)

**Comment by stubailo** [comment]
If you update to the newest version of `react-meteor-data`, it should work now!

Let me know if it doesn't. Thanks for reporting!

**Comment by joetidee** [comment]
Also import the react-meteor-data module:

import { createContainer } from 'meteor/react-meteor-data';

**Comment by gurjit03** [comment]
uncaught typeError : createContainer is not a function
