### ISSUE TITLE
Meteor 1.3 + Cordova + Crosswalk : _timesync error

### ISSUE THREAD

**Issue by hlehmann** [meteor/meteor#6605]
```
XMLHttpRequest cannot load http://192.168.43.84:3000/_timesync. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12032' is therefore not allowed access.
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
Error syncing to server time:  Error: network(…)
Max number of time sync attempts reached. Giving up.
```

The app is working but I always get those errors, is it normal ?

**Comment by martijnwalraven** [comment]
It seems you are using `mizzao:timesync`, and because the CORS header it sets hasn't been changed for Meteor 1.3, syncing server time won't work. That shouldn't affect the rest of your app though. I've opened [an issue](https://github.com/mizzao/meteor-timesync/issues/41) for this.
