### ISSUE TITLE
[1.3] Wrong "meteor update" command message

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#6610]
Hi,

Yesterday I saw 1.3 release immediately after release and rapidly update my project with this command ```meteor update --release METEOR@1.3``` today I saw official blog post about this release and run ```meteor update``` for one of my package update but this message shown on command line:

```
Not updating the release, because this app is at a newer release (METEOR@1.3)
than the latest recommended release (METEOR@1.3).
```
But it's wrong because METEOR@1.3 release not newer than METEOR@1.3.

**Comment by laosb** [comment]
Should it be fixed in the PR I submitted?

**Comment by benjamn** [comment]
This will be fixed in the next release by @laosb's pull request.
