### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by jalik** [meteor/meteor#6612]
After upgrading to Meteor 1.3, I have this message :
`SyntaxError: expected expression, got '<'`

The error is thrown because I load some libs in `<head>`, if I don't load them, there's no errors, but it's the official libs.
```
    <script src="lib/d3.js"></script>
    <script src="lib/c3.js"></script>
```

**Comment by stubailo** [comment]
You don't need to manually load these files with Meteor. Meteor runs a build process that loads the files for you and concatenates and minifies them for you in production, so you don't need to put any script tags in your HTML at all.

If you want these files to be loaded outside of the normal Meteor build process, put them into your app's `/public/lib` directory, then you can load them as in your code example.

**Comment by jalik** [comment]
Hi @stubailo I know all the automatic stuffs Meteor does for me, but I did it this way because in my case, **C3.js needs to be loaded after D3.js** and I did not wanted to wrap them in a package just to do that.

These libs are (like you suggested) located in the `/public/lib` directory, if I did open the issue it's because this error came with Meteor 1.3.

**Comment by jalik** [comment]
What is your recommandation when you want to load external libs respecting an order and these libs have no wrapper package ?

Please don't tell me to create a package. :(

**Comment by stubailo** [comment]
@jalik in Meteor 1.3, we have imports specifically for this case!

So at the top of `c3.js`, put `import './d3.js'`, and the command line tool will respect the dependency!

**Comment by jalik** [comment]
@stubailo Okay thank you and sorry if I made you repeat things.. 
Your work and help is much appreciated. :+1:
