### ISSUE TITLE
Dead code elemination for production

### ISSUE THREAD

**Issue by aunz** [meteor/meteor#6614]
In this [line](https://github.com/meteor/meteor/blob/master/packages/standard-minifier-js/plugin/minify-js.js#L30), dead_code is false.
Would it be better to enable it such as below?
```js
    compress: {
      dead_code: process.env.NODE_ENV  === 'production'  : true ? false
    }
```
At the moment, a lot of codes specific to 'development' insides React package are still retained even running `meteor run --production`.
Or am I a bit ignorant, unaware that there are other reasons why `dead_code` is set to `false`?

**Comment by laosb** [comment]
Should `unuse` also be true?

**Comment by skirunman** [comment]
Your request looks to be a duplication of what is being tracked in #6402 and #6123. You may want to close this out and add your comments in those issues.

**Comment by aunz** [comment]
Sorry, didn't see #6402 when I searched for the phrase "dead code elimination", will close this.
