### ISSUE TITLE
[1.3] meteor publish : client-side code on the server-side

### ISSUE THREAD

**Issue by kamilkisiela** [meteor/meteor#6618]
### What's the issue?

1.  I published `mys:mys11` package using `Meteor@1.2.1` publish tool (it's the [`1.2.1`][package-1.2.1] version).
2. Then I released the new version with no changes but I switched to use `Meteor@1.3.0` publish tool (it's the [`1.3.0`][package-1.3.0] version).
3. Client-side code is also available on the server-side (as you can [see here][bundle-diff])

It's causing problems in `Meteor@1.2.1` apps (link to the reproduction below).

### Links:

- [`mys:mys11`][atm] - example atmospherejs package
- [repository of `mys:mys11` package][package-repo]
- [repository of in-app reproduction][app-repo]

[bundle-diff]: https://github.com/kamilkisiela/mys11-app/compare/6dd9e2f...211c13d
[atm]: https://atmospherejs.com/mys/mys11
[package-repo]: https://github.com/kamilkisiela/mys11-package
[app-repo]: https://github.com/kamilkisiela/mys11-app
[package-1.2.1]: https://github.com/kamilkisiela/mys11-package/commit/ede53bf7f3b7cb02a065a9db00a8fae576fcda02
[package-1.3.0]: https://github.com/kamilkisiela/mys11-package/commit/a09535e8e4e4bb55de5321de0a9d724627b78c56

**Comment by benjamn** [comment]
You should update [this line](https://github.com/kamilkisiela/mys11-package/blob/a09535e8e4e4bb55de5321de0a9d724627b78c56/package.js#L9) to say `api.versionsFrom("1.3")`. Packages published with the 1.3 tool have this problem when running under older versions of Meteor.

Same problem as #6484, I think. We should warn when you publish a package using Meteor 1.3 but don't specify `api.versionsFrom("1.3")`.

**Comment by benjamn** [comment]
Or perhaps we can just revert to the old behavior when the package isn't depending on `modules`…

**Comment by kamilkisiela** [comment]
@benjamn 
> Or perhaps we can just revert to the old behavior when the package isn't depending on modules…

It would be nice :+1:

**Comment by kamilkisiela** [comment]
Otherwise it will be hard to maintain backwards compatible packages. I'm sure there are many different packages that will be maintained that way, like `angular-meteor` for example.

**Comment by trajano** [comment]
Oh that would explain why my packaging was going wonky in https://github.com/trajano/angular-bootstrap-validator/

**Comment by benjamn** [comment]
Working on this now!

**Comment by mitar** [comment]
> Or perhaps we can just revert to the old behavior when the package isn't depending on modules…

That would be really great! I am getting reports that people cannot use [meteor-util](https://github.com/peerlibrary/meteor-util) package anymore with Meteor 1.3, but thins should really stay backwards compatible.

**Comment by benjamn** [comment]
If you want to test this on `devel`, that would be great! Trying to put out a `1.3.1` release today or Monday.

**Comment by kamilkisiela** [comment]
Thanks, it's working!

[diff](https://github.com/kamilkisiela/mys11-app/commit/ba23f9f6a6dfe2120664598a6ebc0332f3a67721)

**Comment by benjamn** [comment]
This should be fixed if you do `meteor update --release 1.3.1-rc.3`, soon to become 1.3.1.
