### ISSUE TITLE
CSS concatenation (on deploy) breaks @import statements

### ISSUE THREAD

**Issue by pzich** [meteor/meteor#662]
I noticed that my web font wasn't working on deploy. After some investigation, I discovered that my custom CSS (with "@import …" in the first line) is getting concatenated right against the closing curly bracket, breaking it. In addition I believe @import statements are supposed to appear at the beginning of the file.

![Screen Shot 2013-02-04 at 3 15 28 PM](https://f.cloud.github.com/assets/706138/125316/b05fac9e-6f10-11e2-8e11-b15eeba8c3e6.png)

**Comment by wmodes** [comment]
I'm getting a broken @import on Meteor 1.1.0.2.  Works locally, import not working after deploy. I have this near the top of my css file:

     @import url(http://fonts.googleapis.com/css?family=Architects+Daughter);

**Comment by rriemann** [comment]
I created my project with yeoman angular-meteor and put an @import statement into by app.scss to load a google font.

Meteor reports:
> Client modified -- refreshing (x9)app/client/app.scss.css: warn: there are some @import rules those are not taking effect as they are required to be in the beginning of the file

It's not working. I am with Meteor 1.2.1.

**Comment by jjhesk** [comment]
the problem happens again on version 1.10.2
