### ISSUE TITLE
[1.3] Fresh install of meteor 1.3 will not allow me to run any meteor commands when not in a meteor directory.

### ISSUE THREAD

**Issue by Andrew1431** [meteor/meteor#6620]
![image](https://cloud.githubusercontent.com/assets/9736372/14118795/17ba803a-f5b9-11e5-88b2-29460d969e23.png)

On a fresh install of meteor 1.3 I am unable to create a meteor application. (I can still run my old apps, but can't create any new ones)

**Comment by benjamn** [comment]
Do you accidentally have a `.meteor/` directory in your `code` directory? Is that intentional?

**Comment by Andrew1431** [comment]
You clever son of a bitch! For some reason I do, and I have no idea why there would be. Thanks man :)

**Comment by benjamn** [comment]
Whew :relieved:

**Comment by Andrew1431** [comment]
Haha probably gave you a good scare. 100% brokeness on official release. Seriously though nice work team. meteor 1.3 is the cleanest stack I've ever used.
