### ISSUE TITLE
[1.3] Client side debugging unable to set breakpoints on valid lines, sourcemap issue?

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#6623]
Server side debugging has no issues.
Client side debugging is unable to set breakpoints on valid lines of code.

I suspect a source map problem.

### Environment
Windows: 10 Pro x64 (10240)
Chrome: 49.0.2623.110 m
Meteor: 1.3

### Repro

1. `meteor create test`
2. `cd test`
3. `meteor`
4. bring up a chrome client with URL `http://localhost:3000`
5. enable chrome debugger (e.g. F12)
6. try to set a breakpoint on `main.js:8` or `main.js:20`.  unable to set breakpoints there.

Expected to be able to set breakpoints on all valid code lines.

**Comment by tomRedox** [comment]
I have endless issues with this too, although I hadn't pinpointed Meteor as being the cause.  Interesting to see reproducible steps.

**Comment by zol** [comment]
I've seen this problem randomly before with/without Meteor on different browsers/platforms. If there is a consistent reproduction someone could take a look.

**Comment by brucejo75** [comment]
@zol, are you unable to reproduce using the example meteor app that I showed above?

**Comment by foobarbecue** [comment]
I just tried this on Ubuntu 14.04, Chrome 51 and the breakpoints can be set and work fine. Note chrome dev tools has been upgraded a lot lately... on mine, all the files are under "app" with an icon of a cloud and a computer. I don't remember how it was in older chrome dev tools but I think it was arranged differently.

**Comment by brucejo75** [comment]
Thanks @foobarbecue so Ubuntu looks OK, I suspect mac looks OK maybe this is only a Windows issue?
@tomRedox have you been able to repro with my steps above?

also, I am something of a newbie.  I assume that I cannot mess with labels unless I am on a special list for the meteor team?  What is the protocol for contacting @zol to verify the repro did not work for him?  I assume this is his issue because he assigned it to himself?

**Comment by tomRedox** [comment]
@brucejo75 I just tried and I get exactly the same behaviour as you, I can't set breakpoints on lines 8 or 12 (or 20 either for that matter).

Windows: 8.1 Pro
Chrome: 49.0.2623.87 m
Meteor: 1.3

**Comment by JesperWe** [comment]
This is a very frustrating bug.  I find myself having to change the code and reload just to be able to set a breakpoint in certain places. I'm on Win10, Chrome 50.0.2661.94 m (64-bit)

**Comment by JesperWe** [comment]
Since this got labelled :has-workaround, I'd be curious to know what the workaround is, since I haven't seen one mentioned?

**Comment by zol** [comment]
It has a 'workaround' in that it doesn't block you from doing development or impact production apps. Granted it's an annoyance.

**Comment by Nullpo** [comment]
I have the same problem randomly in Ubuntu 14.04. I will post here when I found a way to reproduce it.

**Comment by brucejo75** [comment]
This has improved significantly with version 1.4.  Now I cannot reproduce any of the problems.

Closing.

**Comment by abernix** [comment]
For record keeping and posterity's sake, this may have been fixed by aacfbbf5d27631d1eb18eb210e6868f105e467a8.
