### ISSUE TITLE
Reverting back to 1.2 from a forced 1.3 update

### ISSUE THREAD

**Issue by maresk** [meteor/meteor#6625]
Everything was working fine till today when I noticed a "Downloading 8 packages" message after every `meteor run` started appearing. It not only slowed down the build but took my node server size which usually hovered around 500 MB to 1.6 GB.  I checked this issue  #2950 out. I had a hunch that there must be a new release and updating could stop it from trying to download updates every time I run the app. So I checked and saw Meteor 1.3 released yesterday. I updated to 1.3 from 1.2.1 The "Downloading 8 packages" messages went away, the node server size was back to normal but the update broke my app. I had a leaflet draw control that was working and now the controls don't even show up on the map.

Not wanting to hunt down this issue as this draw control is central to the app I wanted to revert back to 1.2.1 where everything was working. But trying to `meteor update --release 1.2.1` got these messages instead 

`$ meteor update --release 1.2.1
Update to release METEOR@1.2.1 is impossible: 
While selecting package versions:             
error: Conflict: Constraint meteor@1.1.12 is not satisfied by meteor 1.1.10.
Constraints on package "meteor":
`
`meteor@1.1.12 <- standard-minifier-css 1.0.4
meteor@1.1.12 <- minifier-css 1.1.9 <- standard-minifier-css 1.0.4
meteor@1.1.12 <- standard-minifier-js 1.0.4
 meteor@1.1.12 <- minifier-js 1.1.9 <- standard-minifier-js 1.0.4
`

I checked this issue #6366. My `.gitignore` repo has a line to not track the `.meteor` folder so I cannot revert back using git. I do have the `packages versions releases` files on my deployed app server as it only ignores `.meteor/local` but I am not sure  I should be copy pasting these from older versions or  replacing `standard-minifier-js` and `standard-minifier-css` with `standard-minifiers` in packages and  removing `1.3.0-split-minifiers-package` from `.finished-upgraders` as mentioned #6366.
. How can I resolve these messages using `meteor update ` ?

**Comment by mroftalp** [comment]
I can't revert back too!

**Comment by mroftalp** [comment]
@maresk I'm using Web storm and there's a history log, reverting back the changes in the packages, release and versions in the .meteor folder I was able to revert back to Meteor 1.2

**Comment by Jerret321** [comment]
I think Meteor official should give the way to revert back low level version. When we upgrade Meteor from 1.2.1 to 1.3, there will be some problems in latest version application. We have to revert it

**Comment by ericmcgregor** [comment]
The blog post announcing 1.3 was really wonderful!  however it neglected to mention that upgrading would literally break everything in my project and there was no way to revert.  This should be the first thing you mention, because I am completely hosed now.  What a horrible oversight.

**Comment by mroftalp** [comment]
It broke some in my project too that's why I reverted back.

**Comment by abernix** [comment]
In order to facilitate easy roll-backs, you should **not** have entire `.meteor` directory Git-ignored.  `.meteor` has it's own `.gitignore` to ignore `.meteor/local`.  The other files should be tracked (especially `.meteor/versions`, `.meteor/release` and `.meteor/packages`).  I can still run Meteor 1.1.0.3 using the Meteor 1.3 toolset without problems by rolling my project back to that state.

Without those files in version control, it might be hard to roll-back, but try setting the content of your `.meteor/release` file to `METEOR@1.2.1`, and perhaps remove your `versions` file and let it rebuild from your `packages`.

**Comment by maresk** [comment]
I managed to revert back manually using the directions I mentioned before, it worked ok locally but deployment was still failing. Turns out the new version is hardcoded in the install script that the official buildpack calls. Got that working as well but it took a major chunk of time to get it straightened out. If any one still needs instructions I can put them down here.

**Comment by mhdHussein** [comment]
@maresk I updated meteor and now I cannot (mup deploy) my project , to add extra features 

can you please post the instructions

thank you

**Comment by abernix** [comment]
@mhdHussein Running `meteor update` without `--packages-only` will change the pinned release, but assuming you had the correct files in your version control, you can simply roll back your version control (Git, Svn, etc.) and be back on 1.2.1 (or whatever version you want).  The 1.3.x Meteor tool (which is the `meteor` command itself) is capable of running previous versions of Meteor just fine as it will download and install the appropriate bootstrapping bundle for you.

You probably want to switch to using [`mupx`](https://github.com/arunoda/meteor-up/tree/mupx) now, which if your project works in development, is probably the issue you're encountering as the original mup has not been actively maintained in a very long time.

Further conversation belongs in a [forum post](http://forums.meteor.com/) where you will probably find a lot more help.

**Comment by maresk** [comment]
I did it manually which sounds bad but is actually simple, 
In your packages remove lines  `standard-minifier-js` and `standard-minifier-css` and add  `standard-minifiers` The minifies were apparently split up in the latest version.

You may also have to remove  `1.3.0-split-minifiers-package` from `.finished-upgraders`

If you delete the versions file in `.meteor/` you will get a clean versions file which will fix the problems you mentioned above. 

Then do a  `meteor update`.

If you are deploying an app, you will have to make sure you add `?release=YOUR_METEOR_VERSION` to the install script curl URL, else it tends to get the latest and may result in some silent feature breaking. Thats what happened to me.

**Comment by abernix** [comment]
Closing this because you can always revert your project back if you have your project (including the `.meteor` directory) in GIT version control (as you should).

The meteor tool will always run your project with the version of Meteor it was last run with.  Before you run `meteor update` you should have the last version of your project committed to Git so if you encounter incompatibilities with upgrades, you can easily roll back.
