### ISSUE TITLE
Deprecate core jQuery package

### ISSUE THREAD

**Issue by ramijarrar** [meteor/meteor#6626]
Now that we have full support for NPM packages, having a duplicate version of jQuery in Meteor Core leads to integration issues with packages that depend on the official NPM version. Would it be possible to get rid of this package altogether or take a similar approach to the react package?

**Comment by ramijarrar** [comment]
Also, in the meantime can you suggest any way to point NPM packages to the version provided by Meteor core (like we could do with Browserify transforms)?

**Comment by benjamn** [comment]
I agree! One way to approach this might be to release a new version of the `jquery` Meteor package that imports `jquery` from the app's `node_modules` directory, throwing a helpful exception if it's not installed.

**Comment by ramijarrar** [comment]
@benjamn Sounds great. What's the timeline for something like this (i.e 1.3.1, 1.4, etc.)? In the past we were using [exposify](https://www.npmjs.com/package/exposify) to mitigate this issue, can we do something similar in 1.3?

**Comment by skirunman** [comment]
Related to #3456 and also slightly related to cleaning up some unneeded and unwanted Meteor core jquery dependencies. See #6563.

**Comment by Siyfion** [comment]
Yeah this is actually causing me a huuuuge headache as I've got a duplicated version of jQuery, one has the bootstrap modal library, one doesn't. Other NPM packages are trying to call bootstrap jQuery functions on the version without them... It's all getting rather messy!

**Comment by ramijarrar** [comment]
@benjamn Is this ready for testing in 1.3.2-rc.0?

**Comment by benjamn** [comment]
Once Meteor 1.3.2 is released today or tomorrow, it will be possible to avoid including jQuery in your project at all, or to use your own version throughout the project by `npm install`ing it yourself. You can test it out by doing `meteor update --release 1.3.2-rc.5` now. Thanks for your feedback, everyone!

**Comment by skirunman** [comment]
@benjamn Just wanted to make sure you saw this comment as @mitar mentioned there may be an issue with using the jquery.isPlainObject code he created running on the client. https://github.com/meteor/meteor/commit/fbf7617111d0d4b7ee7ee7e63a6861f2dfc0fd16#comments
Great work on getting this fixed.

**Comment by lorensr** [comment]
I'm on `1.3.2-rc.5`, I've got a lot of atmo packages that depend on atmo `jquery`, so I can't remove it. 

When I `npm remove --save jquery`, I get browser console error on pageload `cannot find module 'jquery'`, probably because I have npm packages that depend on jquery. 

When I have both of them installed, I have this problem:
- I log `$.fn` from inside an npm package jquery plugin, and the logged object has my plugin listed
- After everything has finished loading, I look at `$.fn` in JS console, and it no longer has my plugin. 

I'm guessing that the atmosphere jquery is being loaded after the npm jquery & other npm packages, and overwriting `$`? Anything I should do to further diagnose?

**Comment by dohomi** [comment]
Hi @benjamn 
I removed `jQuery` from my `packages` folder and tried to include it with `npm` with the newest 2.x version but I receive following error with `Meteor 1.3.2.1`:
``` 
While selecting package versions:
   error: No version of jquery satisfies all constraints: @=0.0.0, @=1.11.8
   Constraints on package "jquery":
   * jquery@=0.0.0 <- top level
   * jquery@=1.11.8 <- top level
   * jquery@1.11.8 <- blaze 2.1.7 <- accounts-base 1.2.7
```
Is it possible that there are some dependencies left in the `Meteor` core packages?
Thanks
Dominic

**Comment by derwaldgeist** [comment]
Why has this been closed if there are still remaining issues?
