### ISSUE TITLE
[1.3] Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6630]
i try to use [json-file-plus](https://github.com/ljharb/json-file-plus) for write json file.
this package require module 'fs'.
error:
`Cannot resolve module 'fs'`

how to import this module form meteor ?
any missing ?

**Comment by Deilv** [comment]
fs is not a dependency of json-file-plus, so it's not automatically installed.
Did you try **meteor npm install fs** inside your project?

**Comment by lyquocnam** [comment]
yah, i tried and..:
`Uncaught TypeError: fs.readFile is not a function`

**Comment by Deilv** [comment]
We'll need a bit more info than that. How do you import 'fs' and how do you initialize it?

**Comment by lyquocnam** [comment]
ya, i use meteor 1.3 and webpack
`import settings from  'settings.json';`
so i want write settings back to json, that i use package file-json-plus.
and try like example:

```
var jsonFile = require('json-file-plus');
var path = require('path'); // in node-core 
var filename = path.join(process.cwd(), 'package.json');
var callback = function (err, result) { /* your code here */ };
 
/* Note: jsonFile also returns a Promise, if you prefer that to a Node-style callback ("errorback"). */
jsonFile(filename, function (err, file) {
	if (err) { return doSomethingWithError(err); }
 
	file.data; // Direct access to the data from the file 
	file.format; // extracted formatting data. change at will. 
 
	file.get('version'); // get top-level keys. returns a Promise 
	file.get('version', callback); // get top-level keys. calls the errorback 
	file.get(); // get entire data. returns a Promise 
	file.get(callback); // get entire data. calls the errorback 
 
	/* pass any plain object into "set" to merge in a deep copy */
	/* please note: references will be broken. */
	/* if a non-plain object is passed, will throw a TypeError. */
	file.set({
		foo: 'bar',
		bar: {
			baz: true
		}
	});
	
	file.remove('description'); // remove a specific key-value pair. returns a Promise 
    	file.remove('description', callback); // remove a specific key-value pair. calls the errorback 
 
	/* change the filename if desired */
	file.filename = path.join(process.cwd(), 'new-package.json');
 
	/* Save the file, preserving formatting. */
	/* Errorback will be passed to fs.writeFile */
	/* Returns a Promise. */
	file.save(callback).then(function () {
		console.log('success!');
	}).catch(function (err) {
		console.log('error!', err);
	});
});
```

**Comment by suhail-ansari-apconic** [comment]
You need to do **npm install meteor-node-stubs** for all the default node modules to show up in your applications.

**Comment by lyquocnam** [comment]
i maked sure installed meteor-node-stubs @@!

```
var readJSON = function readJSON(filename) {
	var callback;
	if (arguments.length > 1) {
		callback = arguments[1];
		if (!is.fn(callback)) {
			throw new TypeError('callback must be a function if provided');
		}
	}
	var deferred = promiseback(callback);
	fs.readFile(filename, { encoding: 'utf8' }, function (err, raw) {
		var file;

		if (err) {
			deferred.reject(err);
		} else {
			try {
				file = new JSONFile(filename, raw);
				deferred.resolve(file);
			} catch (e) {
				deferred.reject(e);
			}
		}
	});
	return deferred.promise;
};

```
error at this line:
`fs.readFile(filename, { encoding: 'utf8' }, function (err, raw) {`
`Uncaught TypeError: fs.readFile is not a function`

**Comment by Deilv** [comment]
Afaik you still need to import the fs module, which you don't, and .readFile is not a function of undefined.
So, how about you add **var fs = require('fs');** at some point in the second file?

**Comment by abernix** [comment]
As @Deilv said, as with any module/package you want to use, you still need to require/import `fs` if you want to use it:

`import fs from 'fs';`

This should be discussed further on the [Meteor Forums](https://forums.meteor.com) or StackOverflow as it is not a bug with Meteor.
