### ISSUE TITLE
Accounts.forgotPassword() is still case sensitive for email to reset password

### ISSUE THREAD

**Issue by Hongbo-Miao** [meteor/meteor#6632]
I am using Meteor 1.2.1 (I haven't tested Meteor 1.3).

I read these two issues, and actually these two didn't fix this one at the end. https://github.com/meteor/meteor/issues/5621, https://github.com/meteor/meteor/pull/5674
(Does it mean we should get rid of `Accounts.forgotPassword()`, instead, using `Accounts.findUserByEmail(email)` first and then `Accounts.sendResetPasswordEmail(userId, [email])` to reset the password in the server side?)

Now Accounts.forgotPassword() is still case sensitive for email to reset password. So when my codes looks like these:

```
   let options = { email: email };
    Accounts.forgotPassword(options, err => {
      if (err) console.log(err);
      // ...
    });
```

When a user use My@email.com to register but reset by my@email.com, it still shows

> User not found

**Comment by laosb** [comment]
According to the `History.md`, that has been solved in 1.3.

**Comment by Hongbo-Miao** [comment]
@laosb Thanks, just leave a link here [History.md](https://github.com/meteor/meteor/blob/bb5bb4d07d9ce2dcfa253f14ab2545245e72a311/History.md#accounts). I will try again once I updated to Meteor 1.3

**Comment by nazarposhta** [comment]
Is that function even work? Because I receive  `User not found` all the time.
