### ISSUE TITLE
Try to simplify example app creation

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6638]
![image](https://cloud.githubusercontent.com/assets/10534563/14140251/93e5dd7c-f680-11e5-86af-c76e816a4bf5.png)

**Comment by avalanche1** [comment]
I guess, if it's a todo's example - it should install seamlessly, without me doing any voodoo on packages and stuff.

**Comment by Deilv** [comment]
Did you even read the [instructions](https://github.com/meteor/todos) of the todos project?

> Running the app
> **npm install**
> meteor

It works seamlessly for me (and probably many others).

**Comment by avalanche1** [comment]
No I didn't. And I shouldn't. I've used `meteor create --example todos`. from https://www.meteor.com/todos. That was always enough. But not with 1.3

**Comment by pwnball** [comment]
Versions of meteor before 1.3 were not integrating full npm support. Meteor 1.3 is. I am aware that your point is still a valid one.

**Comment by Deilv** [comment]
If you wish to see this fixed, you should change your issue subject to point out that documentation has to be updated:
```
https://www.meteor.com/todos
https://www.meteor.com/localmarket
```
Besides that everyone participating in this community should put at least some minimum effort to help the project, like I spent 15 minutes trying to replicate your error and give you a solution.

**Comment by abernix** [comment]
When Meteor turned 1.3 (and in the future, 1.4), NPM becomes more and more critical.  If you're saying you can't and won't run `npm install` as directed, then hopefully Feature Request #6848 ("Meteor should install npm packages automatically") is as close as it comes to resolving your issue.  As it stands right now, you are saying you won't follow the instructions in the `README`, which is your own choice, but the Meteor tool then goes on to give you the commands to fix it as well.  Overall, pretty helpful.

@Deilv makes a point here that might be valid though, perhaps until #6848 lands, the meteor.com site should be changed to tell you to clone the repo from git and run `npm install`.

Also, maybe it would be nice if the `meteor create` could `git clone` the repo automatically, but that might just be confusing functionality when you move to your own app.

**Comment by avalanche1** [comment]
You guys fail to see why I opened that issue.

**Comment by abernix** [comment]
@avalanche1 I think I've covered everything that you've brought up so far.  Can you further explain what your concern is?

**Comment by avalanche1** [comment]
Before 1.3 I was able to create an example app with simple `meteor create --example todos` from https://www.meteor.com/articles/todos-example-app.
Now I have to do some voodoo magic. And still cant get it running - see the initial screenshot.
If you're positive with that outcome - fine, close this issue.

**Comment by abernix** [comment]
I understand.  And this process can definitely be improved.  But I already said:

>Feature Request #6848 ("Meteor should install npm packages automatically") *(this would take care of you having to run `npm install` manually)*

And as a temporary solution until that feature request can be done:

> perhaps until #6848 lands, the meteor.com site should be changed to tell you to clone the repo from git and run npm install *(this refers to updating the article that you just posted)*

What did we fail to see?  There's not going to be a way to avoid doing an NPM install, but hopefully meteor-tool can do it for you.

**Comment by Primigenus** [comment]
@avalanche1 Why do you feel `npm install` is voodoo magic? Are you familiar with npm or is it a new command that you don't understand?

Perhaps we're overlooking an assumption that as we open up to the node.js community, people installing Meteor 1.3 will therefore be people from the node.js community. Maybe explaining things like `npm install` will help.

What if running `meteor` with the `--example` flag automatically also runs `npm install`?

**Comment by avalanche1** [comment]
> Before 1.3 I was able to create an example app with simple meteor create --example todos exactly like https://www.meteor.com/articles/todos-example-app describes it.
I guess you shoud simply fix the page that it doesnt say that you only need `meteor create --example todos` because that's not true anymore.
