### ISSUE TITLE
No source files on a generic app on 1.3 and windows.

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6639]
***1 Upvote*** https://forums.meteor.com/t/how-to-prevent-merging-files-in-1-3-when-running-in-dev/20312

**Comment by serkandurusoy** [comment]
+1

This is not just a windows issue. I'm experiencing this on ubuntu and there's another report I've spotted over at the forum

https://forums.meteor.com/t/debugging-on-chrome-with-meteor-1-3-modules-and-angular/20433

**Comment by benjamn** [comment]
Do you have JavaScript source maps enabled?

**Comment by serkandurusoy** [comment]
Mine are enabled.

This happened right after the update from 1.2 where no such problem existed.

**Comment by serkandurusoy** [comment]
Hmm, @benjamn I just realized that meteor now appends scripts into the beginning of body and not head. Is this intended, can that be related to our problem?

I'm on 1.3.1

**Comment by benjamn** [comment]
Let's continue discussion at #6708, which is closer to describing the underlying problem.
