### ISSUE TITLE
[1.3|Blaze] Setting a string primitive as the current data coerces the string to an Object

### ISSUE THREAD

**Issue by dj-foxxy** [meteor/meteor#6642]
Release: METEOR@1.3
Platforms: Linux, Web
Packages: Default packages

Example: https://github.com/dj-foxxy/meteor-string-data-bug

**Expected behaviour**
When a string primitive is set as the current data (_e.g._, `{{> myTemplate myString}}`) it remains a string primitive.

**Actual behaviour**
This string primitive is coerced to a String object. This plays havoc with minimongo selectors: in the selector `{ key: this }`, `this` is treated as a sub-selector, rather than a value to match against.

<hr>
```Handlebars
Test code (also in example repository):
<body>
  body: {{stringType}}<br>

  {{#each strings}}
    each: {{thisType}}<br>
  {{/each}}

  {{#with string}}
    with: {{thisType}}<br>
  {{/with}}

  {{> stringData string}}
  {{> objectData string=string}}
</body>

<template name="stringData">
  String Data: {{thisType}}<br>
</template>

<template name="objectData">
  Object Data: {{stringType}}<br>
</template>
```

```JavaScript
import { Template } from 'meteor/templating';

const string = 'string';
console.log(typeof string);

Template.body.helpers({
  string,

  strings: [string],

  stringType: typeof string,

  thisType() {
    return typeof this;
  },
});

Template.stringData.onCreated(function onCreated() {
  console.log('stringData', typeof this.data);
});

Template.stringData.helpers({
  thisType() {
    return typeof this;
  },
})

Template.objectData.onCreated(function onCreated() {
  console.log('objectData', typeof this.data.string);
});

Template.objectData.helpers({
  stringType() {
    return typeof this.string;
  },
});
```

**Comment by helfer** [comment]
Thanks for reporting this. Unfortunately this is impossible to fix, because `this` in Javascript can never refer to a primitive type. Instead, we recommend you pass in an object that contains the string. See the Meteor guide here: http://guide.meteor.com/blaze.html#name-data-contexts
