### ISSUE TITLE
Please add an option for specifying a DDP server

### ISSUE THREAD

**Issue by ChrisOHu** [meteor/meteor#6645]
Hi guys,

Really love meteor, but I found that it's really hacky to specify a DDP server, currently I followed the instructions from https://github.com/frozeman/meteor-build-client.

Just consider, web frontends are usually delivered through a CDN, which will basically includes all the html/css/js. The frontend only needs to fetch the true 'data' from the true backend.

Also consider, as an app evolves, server/client decoupling will become necessary.

As a result, I think Meteor should be able to let the developers to specify a different DDP server.
And also the ability to bundle the client side only codes. 🙀

Best wishes : )

**Comment by DavidReinberger** [comment]
`DDP.connect()` is too hacky? Meteor accounts also "freshly" (since 1.2.1?) supports different server with `new AccountsClient(connection)`, the ONLY hacky solution is with HCP, where you have to manually edit the HCP package.

**Comment by ChrisOHu** [comment]
Oh thanks so much @DavidReinberger , did not know Accounts can specify a ddp connection 😅
