### ISSUE TITLE
Basic TODOS stops while downloading templating (Windows7 x64)

### ISSUE THREAD

**Issue by andus** [meteor/meteor#6647]
=> Started proxy.
=> Started MongoDB.
   Downloading templating@1.1.7...

.. earlier templating is downloaded and after that it get stuck.

**Comment by pdliu** [comment]
my Meteor under windows10 x64 also gets stuck at this step,, want to know how to solve this problem.

**Comment by andus** [comment]
I had previous installation of separate products like mongodb, node.js and meteor. Just uninstalled all of them, and run only fresh Meteor install. This solved this issue. Also, try to clean the system and temp files.
Hope this helps.

**Comment by pdliu** [comment]
Thanks for your reply. Luckily, I waited, and the installation went on and meteor launched successfully. 
When it got stuck, I watched the modified time of the folders in the directory C:\Users\xxxx\AppData\Local\.meteor\packages, turned out it was actually updating/installing some other packages.
