### ISSUE TITLE
Allow `Meteor.publish` to take an object

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6649]
This would avoid needing to pass in `function()` syntax:

``` js
Meteor.publish({
  something() {
    // this.userId is correct now
  }
});
```

cc @stubailo

**Comment by stubailo** [comment]
Alternatively, couldn't we just pass the publication context as the first argument?

```js
Meteor.publish((context, arg1, arg2) => {
  context.userId;
});
```

**Comment by tmeasday** [comment]
I mean that'd change the API

**Comment by stubailo** [comment]
Oh, true. And I guess the object thing would bring it more inline with methods. Although I feel like we should move in the opposite direction personally, with something like `Meteor.method(...)`.

**Comment by tmeasday** [comment]
This just seems like a very simple change that makes sense in isolation and will improve our examples / guide etc.

**Comment by stubailo** [comment]
Although it's not zero-cost, for example it will require changes to `simple:rest`. But I'm happy to make those changes.

**Comment by mitar** [comment]
If you go this direction, I would also like to see a second argument with options object passed and then available somewhere inside publish handler. :-)

https://github.com/meteor/meteor/issues/6441

**Comment by grsabreu** [comment]
Seems a interesting feature

**Comment by StanLindsey** [comment]
I like this - it keeps a lot of the Meteor code syntactically similar - like methods helpers etc.

**Comment by theodorDiaconu** [comment]
@tmeasday @stubailo close this issue, since the PR has been merged thx.

**Comment by abernix** [comment]
Thanks for pointing this out, @theodorDiaconu.

**Comment by mitar** [comment]
Interesting, that was never documented in `HISTORY.md`.

cc @zimme
