### ISSUE TITLE
Declaring a collection with name Template will mess with Template object methods like "onRendeder" "OnCreated" etc

### ISSUE THREAD

**Issue by ramonmata** [meteor/meteor#6652]
***1 Upvote*** Just by declaring a variable named **Template** 

`Template = new Mongo.Collection('template');`

Will cause the following errors in web brower console:

`Uncaught TypeError: Cannot read property 'onRendered' of undefined`

or 
`Uncaught TypeError: Cannot read property 'onCreated' of undefined` 

etc

The compilation script should be able to detect this and perhaps let us know that the name is reserved

**Comment by avalanche1** [comment]
+1

**Comment by fvpDev** [comment]
Indeed this seems to be a problem any time a variable is defined twice in any programming language. The `Template` object is already defined by the `templating` package in meteor so You should probably avoid trying to define `Template` again.

http://docs.meteor.com/#/full/templates_api

**Comment by helfer** [comment]
Template is a global variable that Blaze relies on, so you cannot redeclare it. You'll have to use a different name.
