### ISSUE TITLE
unable to unit test newly created package for 1.3

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#6653]
in Meteor 1.3, the dummy default package code itself does not compile when running test-packages command

running
```
meteor create packbug
cd packbug
meteor create --package test:pack-c
meteor add test:pack-c
meteor test-packages test:pack-c
```

it does not compile and give this
```
Error: Can't find npm module 'meteor/pack-c'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```

i am trying to understand how the new package modules worked in the new Meteor 1.3, turns out the problem i had lies with the default generated code itself, it is confusing

**Comment by abernix** [comment]
Thanks for pointing this out.  This is definitely a problem with the skeleton that is used to generate the package.   It is importing the module as if it was outside the package, not relative to itself.

Until this gets fixed, if you change `/packages/pack-c/pack-c-tests.js` line 5 from `meteor/pack-c` to `./pack-c.js` (or even just `./pack-c`), it works properly:

    import { name as packageName } from "./pack-c.js";

**Comment by benjamn** [comment]
@abernix as I [commented](https://github.com/meteor/meteor/pull/7147#issuecomment-223055128) on the PR, I think we should change the skeleton test code to
```js
import { name as packageName } from "meteor/test:pack-c";
```

**Comment by abernix** [comment]
@benjamn Makes perfect sense.  PR has been fixed.
