### ISSUE TITLE
App.accessRule with type: 'navigation' doesn't work on 1.3

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#6654]
Reproduction:

```
meteor create test
cd test
meteor add-platform ios
```

add this `mobile-config.js` in

```
App.accessRule('*', {
  type: 'navigation'
});
```

Build the project (test with `meteor run ios-device --mobile-server="http://127.0.0.1:3000"`) and check the `config.xml` file.

The expected behaviour is the `config.xml` file should contain an entry that looks like
```
<allow-navigation href="*"/>
```

But it doesn't. The default `<allow-navigation href="http://localhost"/>` is visible, though.

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this. If I follow these steps, the generated `config.xml` contains `<allow-navigation href="*" />` as expected.

**Comment by Tarang** [comment]
I'll try on a different machine, i've tried this again exactly as above and get the same behaviour

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
