### ISSUE TITLE
How to downgrade to last 1.2 version

### ISSUE THREAD

**Issue by scheung38** [meteor/meteor#6655]
***1 Upvote*** Currently

$ meteor --version
Meteor 1.3

Running:

$ meteor
C:\Users\SEC11\AppData\Local\.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\me
teor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^

so tried downgrade to 1.2 as there seems to be a lot of problems with 1.3 as above:
$ meteor update --release 1.2.1

Update to release METEOR@1.2.1 is impossible:
While selecting package versions:
error: Conflict: Constraint meteor@1.1.12 is not satisfied by meteor 1.1.10.

So I cannot downgrade back and all I can do is for someone to fix it? I am surprised anything manages to get push to release when even starting a new project crashes...and this is getting US$30 million funding?????

**Comment by avalanche1** [comment]
You cannot downgrade, but you can run a specific app in with a different meteor version:
`meteor --release 1.1.0.3`

**Comment by scheung38** [comment]
That's what I did, but still saying 1.3

**Comment by guilhermedecampo** [comment]
use git to the previous commit?

**Comment by avalanche1** [comment]
No, you should start your app with `$ meteor --release 1.2.1`

**Comment by misteio** [comment]
+1 guilhermedecampo, I have downgraded yesterday 1.3 --> 1.2. It works. You have to get previous versions of 2 files: versions and release in your meteor app ( /.meteor/versions and /.meteor/release)
When did, you have just to run meteor as usual, and the downgrade begins. It can be a little long.

**Comment by stubailo** [comment]
The best way to downgrade Meteor is to use version control, and revert back to a version of your code that was running with Meteor 1.2. The `.meteor/packages`, `.meteor/versions`, and `.meteor/release` files are the ones that record the relevant information about what release an app is pinned to, so these should always be tracked in something like Git along with your app's source code. Future upgrades of Meteor might need to perform one-way operations on metadata files that are hard to undo, so committing to having a working downgrade command isn't feasible.

**Comment by azamatsmith** [comment]
Just happened to me with version 1.4  Followed @stubalio instructions and I was back to where I left off and can redeploy again. Thanks!

**Comment by Endtry** [comment]
I just had some issues updating to version 1.4 and @stubailo solution works. I copy the contents from .meteor/packages .meteor/versions and .meteor/release file a recent branch from github and run meteor again. Also, I did a meteor reset to get the project back to where it was before. Hope this help others. Special thanks to @azamatsmith, who was also on the same boat.

**Comment by brucejo75** [comment]
Here is a way that works:

`meteor create --release x.y.z....`
copy all your source code (not .meteor files) into the new project.  update the projects file, possibly by hand.  Maybe remove references to versions.

`meteor npm install`
`meteor`

good to go.
