### ISSUE TITLE
Cannot access meteor.com

### ISSUE THREAD

**Issue by hpb0412** [meteor/meteor#6656]
I tried to access meteor.com but the page is not appeared. What I found on console was like this:

> Refused to load the stylesheet 'https://hello.myfonts.net/count/2c4b9d' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' https://d14xs1qewsqjcd.cloudfront.net http://platform.twitter.com https://platform.twitter.com http://syndication.twitter.com https://syndication.twitter.com http://meteor-frontpage-assets.s3.amazonaws.com https://meteor-frontpage-assets.s3.amazonaws.com http://app-ab16.marketo.com https://app-ab16.marketo.com".

I used Chrome, Firefox, Edge (Windows 10 64b & Windows 8.1 64b) but there was no hope.

It'd happened for 2 days.

Please help!
Thanks very much

**Comment by poltak** [comment]
Are you referring to an app deployed and hosted on meteor.com?

If so, please be aware that, as of last week, [free hosting on meteor.com has ceased](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308).

If not, I cannot help as meteor.com is accessible for me from here in Thailand.

**Comment by hpb0412** [comment]
@poltak 
I prefer to meteor.com site itself. 2 days ago, i've not access this site anymore. Both from company computer and home computer. Everything I received is a blank page and console showed as above.

I was searching for solution but most of them related to policy setting at source code, not one relates to browser setting.

Before 1.3 release, I still accessed page normally.

**Comment by nickpolet** [comment]
Please close this as it has nothing to do with the framework. Meteor.com is perfectly accessible and has not been down this week.

**Comment by helfer** [comment]
This is definitely not related to the 1.3 release, and it seems nobody else can reproduce the issue, so I'm closing it for now.
