### ISSUE TITLE
1.3 regression: Symlink cycle detected

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6665]
***1 Upvote*** It seems that with Meteor 1.3 there is a regression in symlink cycle detection. For Blaze Components I have a demo app in the same repository as the rest of the package is, with a symlink to the package: https://github.com/peerlibrary/meteor-blaze-components/tree/master/demo/packages

Now, even if package does not call `addFiles` on that `demo` directory, symlink check detection is still triggered. I think this is an error and prevents packages do contain other stuff they do not really use. Like this demo app.

**Comment by mitar** [comment]
cc @benjamn

**Comment by rgould** [comment]
:+1:

**Comment by benjamn** [comment]
This is happening because Meteor 1.3 traverses files in package directories that were not explicitly added with `api.addFiles`. We should probably just deal with symlink cycles instead of throwing.

**Comment by Zodiase** [comment]
👍

**Comment by dr-dimitru** [comment]
Add flag `--ingnore-symlink-loops`

**Comment by benjamn** [comment]
This issue will be officially fixed when Meteor 1.3.2 is released today or tomorrow, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.

**Comment by pferrel** [comment]
I am getting a similar problem trying to symlink some images into public/images/posts from posts/images

Meteor refuses to start with the symlink, is this the same issue and therefore will be fixed with an upgrade?
