### ISSUE TITLE
[bug] [1.3] importing Template from meteor/templating causes undefined errors.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6670]
I have an app that I'm migrating from 1.2 without `modules` to 1.3 with `modules`. I have a small file like this:

```js
Template.foo.helpers({
  show_cancel_btn: function() {
    return this.show_cancel || true;
  },
});

Template.bar.onRendered(function() {
  console.log('rendered')
});
```

It works fine in Meteor 1.3. Then, if add the recommended import statement to the top of the file, as in

```js
import Template from 'meteor/templating'

Template.foo.helpers({
  show_cancel_btn: function() {
    return this.show_cancel || true;
  },
});

Template.bar.onRendered(function() {
  console.log('rendered')
});
```

the app will start having this error:

```
Uncaught TypeError: Cannot read property 'helpers' of undefined
```

Seems like after adding the import statement that `modules` starts loading this code before the JavaScript compiled from the corresponding `.html` file by `templating`.

**Comment by dj-foxxy** [comment]
You need `{ }` around `Template`, _e.g._ `import { Template } from 'meteor/templating;`

**Comment by benjamn** [comment]
Yep, `Template` is a named export rather than a default export. For new apps, we tried to make this clear by providing an [example](https://github.com/meteor/meteor/blob/8248d86fb2aeb27aac30d0ca0682e0ab8008320c/tools/static-assets/skel/client/main.js#L1) in `client/main.js`. Sorry for the confusion.

**Comment by benjamn** [comment]
I guess I should let you close this if your issue is fixed.

If you're right about the reordering, you might try forcing the `.html` file to load first:
```js
import {Template} from 'meteor/templating';

// If app.html defines templates "foo" and "bar", this import will guarantee that
// Template.foo and Template.bar are defined below.
import "./app.html";

Template.foo.helpers({
  show_cancel_btn: function() {
    return this.show_cancel || true;
  },
});

Template.bar.onRendered(function() {
  console.log('rendered')
});
```

**Comment by trusktr** [comment]
Oops, that was it!

Maybe default exports might be nice to add? It would be intuitive that the default export of `meteor/ddp` would be `DDP`, etc.
