### ISSUE TITLE
[1.3][benjamn/install] Misleading error message when trying to import modules with errors.

### ISSUE THREAD

**Issue by jorgeer** [meteor/meteor#6671]
Given a react component  that has an error, like having propTypes inside a component using es6 class syntax, you will receive this error when trying to import it:

`Error: Cannot find module './imports/component.jsx'`

This lead me to spend a lot of time examining my import paths, spelling in the import statement etc, when I should have been spending my time debugging the component itself.

It would be helpful if these kinds of erros had descriptive messages, or at least wording that indicated that the problem could lie in the module. I image this can cause a headache for a lot of people.

**Comment by tarun-batra** [comment]
#6670

**Comment by jorgeer** [comment]
No @tarun-batra , I don't see how these issues are related.

**Comment by tarun-batra** [comment]
@jorgeer my bad, wrong issue. lost the right one.

**Comment by benjamn** [comment]
Can you give some more details, or provide a small reproduction? And if this turns out to be a problem with github.com/benjamn/install, maybe open an issue over there?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
