### ISSUE TITLE
[1.3] webapp appears to force-serve manifest.json

### ISSUE THREAD

**Issue by Primigenus** [meteor/meteor#6674]
Since 1.3 it seems like apps are serving a `/manifest.json` file which appears to contain a long list of whether to cache specific resources. I imagine this might be used by something like mobile support to manage whether it needs to update things during hot code reload?

The line causing this behaviour appears to originate here: [2ccb746#L514](https://github.com/meteor/meteor/blob/2ccb7467c9bb5889a3c36739d2d8b59a0656961c/packages/webapp/webapp_server.js#L514)

Steps to repro:
1. create a new Meteor app using 1.3 and navigate to `http://localhost:3000/manifest.json`.

This breaks existing apps that were relying on their own `manifest.json` hosted in eg. `/public` being available, for instance in the case of wanting to provide a [web app manifest according to the W3C Working Draft](https://w3c.github.io/manifest/) using `<link rel="manifest" href="/manifest.json">`.

**Comment by mitar** [comment]
Huh, yes, but that was fix of the omission in the past. The code was meant to server it, but it was not serving it.

There is a TODO to rename it to `program.json`. Maybe this could be a fix? To rename Meteor manifest to `program.json`?

**Comment by Primigenus** [comment]
Yes, or consider naming internal Meteor files like this something that will less likely conflict with the app's files. Maybe serve from a /__meteor__/ folder or something?

**Comment by martijnwalraven** [comment]
I wasn't aware this behavior was new in Meteor 1.3. Mobile support only needs `/__cordova/manifest.json`, but I always assumed it would also serve this for the main architecture (although it isn't used anywhere as far as I know).

Not sure how https://github.com/meteor/meteor/commit/53205bfcd14dfd064ab4d6f7ebc7fee789c54a2f and https://github.com/meteor/meteor/pull/6101/files change this.

**Comment by mitar** [comment]
No, this was the fix: https://github.com/meteor/meteor/pull/5713

**Comment by AndreasGalster** [comment]
Will this be fixed or is there another way how we can serve our manifest.json in the meantime?

**Comment by geremora** [comment]
I need serve my own manifest.json, but in meteor 1.3.4.1 still appears to contain a long list of whether to cache specific resources.

**Comment by abernix** [comment]
The `TODO` (well, `XXX`) is still there in the code to rename this to `program.json`, but even that could lead to people asking the same question as above for `program.json` (e.g. _"How do I serve a `program.json` since Meteor already serves one?!"_).  I guess `manifest.json` might be a more commonly clashing name though.

@AndreasGalster @geremora What kind of manifest is this that you are trying to serve? Is it not configurable to something else?

**Comment by abernix** [comment]
Also, I don't think this is "mobile" related as far as Meteor is concerned at this point so removing that label as it's happening in the webapp code.

**Comment by AndreasGalster** [comment]
I'm trying to define a manifest.json with a gcm_sender_id for push messaging, which currently is not possible.

**Comment by mitar** [comment]
There is a standard to use `.well-known` path for such things: https://tools.ietf.org/html/rfc5785

I would suggest manifest is moved to `.well-known/meteor/manifest.json`.

Meteor should also register it: https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

**Comment by abernix** [comment]
@AndreasGalster You don't have to have the file named `manifest.json` – you can [specify whatever you want according to Google's developer docs](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-05?hl=en):

```
<link rel="manifest" href="some_other_manifest.json">
```

**Comment by lvnr** [comment]
@abernix is correct @AndreasGalster, you can name it whatever you want, but you need to make sure that it's the first manifest included in the page if there are others.

**Comment by fmilani** [comment]
@abernix I've renamed my `manifest.json` but I still can't make it work on chrome mobile (it doesn't appear as a standalone app), and I'm failing to find anyone with the same problem on the web. 

Has anyone ever succeeded in creating their own manifest with meteor? I'm trying to make a progressive web app, with a splashscreen and no url bar...

I appreciate any help, thanks.

**Comment by mitar** [comment]
I do this: https://github.com/peer/mind/blob/master/client/head.html

**Comment by fmilani** [comment]
@mitar That did changed the status bar color of my phone (I guess because of the meta tag `theme-color`). But still it is not in standalone mode and still no splashscreen shown, do you get these in your web app?

**Comment by mitar** [comment]
I haven't tested that. :-)

**Comment by fmilani** [comment]
If someone else could tell if they got it working... I really don't know what I'm doing wrong. =(

**Comment by Primigenus** [comment]
@fmilani You have to add it to your homescreen in order to trigger the splash screen and fullscreen options.

**Comment by fmilani** [comment]
@Primigenus I did add it to my homescreen.

**Comment by hwillson** [comment]
Marking this as `pull-requests-encouraged` - if anyone is interested in jumping on this, please use the following (Meteor team approved) format:

```
/__meteor__/webapp/manifest.json
```

**Comment by mitar** [comment]
So we do not want to use standard `.well-known`?

**Comment by hwillson** [comment]
The idea was discussed, but there is precedent for using a pattern like the one suggested within the Meteor codebase (e.g. the [`bundle-visualizer` is using something similar](https://github.com/meteor/meteor/blob/c8c88300a6ef3497f2bbafcdd12a12f62ef7d2c5/packages/non-core/bundle-visualizer/common.js#L3)). The plan is to eventually standardize around the `__meteor__/package-name` pattern. Going through the process of being properly registered for a `.well-known` address isn't currently something that the team wants to spend time looking into (that may change in the future though!). Thanks!

**Comment by abernix** [comment]
I took some more time to look into this this morning.  I'm not sure that `manifest.json` is consumed by anything but Cordova, specifically in [this portion](https://github.com/meteor/cordova-plugin-meteor-webapp/blob/a63a91294c806626a1246aa513becc25a31fe2e5/src/ios/WebAppLocalServer.swift#L234-L247) of the `cordova-plugin-meteor-webapp` plugin (which Meteor Cordova apps use), and specifically at `__cordova/manifest.json`.  Some of the tests of that plugin [further elude to that theory](https://github.com/meteor/cordova-plugin-meteor-webapp/search?utf8=%E2%9C%93&q=__cordova&type=), and I can't find any such code in the non-Cordova code.

I'm not sure if anyone can spot instances where we actually access `manifest.json` at the top level, but if we can hone in on whether or not that's necessary, the more preferable option here might be to just disable it.  I'm not really keen on the idea of changing `cordova-plugin-meteor-webapp` to support this new URL.

**Comment by abernix** [comment]
Regarding `.well-known`, I'm not sure even sure we meet the requirements for it.  The RFC states, in [section 1](https://tools.ietf.org/html/rfc5785#section-1):

```
1.  Introduction

   It is increasingly common for Web-based protocols to require the
   discovery of policy or other information about a host ("site-wide
   metadata") before making a request.
```

And further clarifies in [1.1](https://tools.ietf.org/html/rfc5785#section-1.1):

```
                                ...they are designed to facilitate
   discovery of information on a site when it isn't practical to use
   other mechanisms; for example, when discovering policy that needs to
   be evaluated before a resource is accessed, or when using multiple
   round-trips is judged detrimental to performance.
```

I don't believe we're accessing `manifest.json` before the request is made, but rather as subsequent requests when there are other practical mechanisms.

**Comment by hwillson** [comment]
> I'm not sure that manifest.json is consumed by anything but Cordova

Interesting find @abernix - commit https://github.com/meteor/meteor/commit/05b2765d61f0ba9f4d9a8069840ee25b960628ed definitely points towards that being the case. It looks like the `manifest.json` was always (and only) served up via `/cordova/manifest.json` until that commit. I can't find any reason why it needs to be available at `/manifest.json` - it just looks like that commit was refactoring things a bit and decided to make the manifest serving code a little less architecture specific. So we can probably drop it? I'll give it a shot. Thanks!

**Comment by mitar** [comment]
So we used `manifest.json` for multi-target Meteor fork. For web workers and service workers, then we made targets for them and then they had their own manifest a worker loaded to know which things it can import. We also fetch manifest first, before everything else, because there you do not have index.html to load, but you load resources directly. One good use of manifest for us was also that after we loaded manifest, service worker was able to check manifest against a signature, and then any resource it loaded, it checked against the manifest (and hash there). So we were able to detect compromised servers where server might start serving malicious code.

So I would say the question is if Meteor is planing to ever support multiple targets. I think allowing custom targets would be great, and would allow things beyond just Cordova and workers, but maybe even Electron and so on. So the question is: is Cordova the only one using it because it is the first use of it, or it is t he last one?

And so that commit changed manifest with anticipation of going with more targets. I made other additional pull requests which at the time looked like they will go in.

**Comment by abernix** [comment]
@mitar Even with that explanation/use case, I see no reason that any such `manifest.json` file would need to be served top level. 
 Correct?

**Comment by Primigenus** [comment]
Just a quick note that these days, the recommended file to serve is `manifest.webmanifest`, with a mimetype of `application/manifest+json`. So perhaps we can avoid the collision completely by referring people trying to serve `manifest.json` to the documentation: https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by hwillson** [comment]
Thanks @Primigenus - the name is still optional though, and many people (like Google) are still recommending ([by example](https://developers.google.com/web/fundamentals/web-app-manifest/)) `manifest.json`. I think at the very least we should still consider getting Meteor's `manifest.json` out of the top level.
