### ISSUE TITLE
Fastclick package breaks app on Firefox MacOS

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#6677]
This is very strange.

My Meteor 1.2.1 app stopped working in Firefox all of a sudden, without any changes to the source code. Only Firefox (45.0.1 on MacOS) is affected, if I run it in Chrome everything works as expected.

I first suspected a corrupt build or Meteor installation, so I did a ```meteor reset``` and even re-installed Meteor including a ```rm -r``` of the ```~/.meteor``` folder. But the problem was still there.

Based on the log (below), I was able to track this down to a problem with the ```fastclick``` package. If I remove this package, the app is working again. But as soon as I re-add the package, Firefox throws these errors.

I then suspected a recent Firefox update, so I re-installed older versions of FF (first 45.0, then 44.0), but the problem was still there.

The app ran perfectly before, with the very same source code. I even did a revert of my svn working directory to an older "last known good" version which is currently running on my production AWS instance, just to be sure. But the problem also occurs in that revision.

Here's the full console log:

```
http://localhost:3000/packages/kadira_flow-router.js?3bf0822dc2875cf55697c72e8fde8f4d3c0eebd9 is being assigned a //# sourceMappingURL, but already has one kadira_flow-router.js:2726:4
guzz: Running in webbrowser concats_app-main.js:168:5
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create matb33_collection-hooks.js:263:5
unreachable code after return statement meteortoys_sub.js:170:3813
unreachable code after return statement meteortoys_email.js:236:964
TypeError: Package.fastclick is undefined
 global-imports.js:9:1
ReferenceError: Template is not defined
 template.modal-dialog.js:2:1
ReferenceError: Template is not defined
 template.simple-message.js:2:1
ReferenceError: Template is not defined
 template.avatar.js:2:1
ReferenceError: Template is not defined
 template.image-slider.js:2:1
ReferenceError: Template is not defined
 template.pagination-bar.js:2:1
ReferenceError: Template is not defined
 template.rating-display.js:2:1
ReferenceError: Template is not defined
 template.app-menu.js:2:1
ReferenceError: Template is not defined
 template.footer.js:2:1
ReferenceError: Template is not defined
 template.header-brand.js:2:1
ReferenceError: Template is not defined
 template.header.js:2:1
ReferenceError: Template is not defined
 template.preloader.js:2:1
ReferenceError: Template is not defined
 template.spinner.js:2:1
ReferenceError: Template is not defined
 template.webapp-main.js:2:1
ReferenceError: Template is not defined
 template.error.js:2:1
ReferenceError: Template is not defined
 template.not-authorized.js:2:1
ReferenceError: Template is not defined
 template.not-found.js:2:1
ReferenceError: Template is not defined
 template.body.js:2:1
ReferenceError: Meteor is not defined
 at-config.js:12:5
ReferenceError: FlowRouter is not defined
 not-found.js:21:1
ReferenceError: Meteor is not defined
 startup.js:9:1
ReferenceError: ReactiveVar is not defined
 modal-dialog.js:15:3
ReferenceError: Template is not defined
 image-slider.js:9:1
ReferenceError: Template is not defined
 pagination-bar.js:25:1
ReferenceError: Template is not defined
 rating-display.js:15:1
ReferenceError: Template is not defined
 app-menu.js:11:1
ReferenceError: Template is not defined
 header-brand.js:9:1
ReferenceError: Template is not defined
 preloader.js:14:1
ReferenceError: Template is not defined
 webapp-main.js:9:1
ReferenceError: Template is not defined
 error.js:9:1
ReferenceError: Meteor is not defined
 startup.js:14:1
ReferenceError: Meteor is not defined
 head.scripts.js:10:1
ReferenceError: Meteor is not defined
 helpers.js:13:5
ReferenceError: BlazeLayout is not defined
 layout.js:9:1
ReferenceError: Meteor is not defined
 push.config.web.browser.js:1:1
ReferenceError: Tracker is not defined
 tomwasd_flow-router-autoscroll.js:60:3
TypeError: $ is not a function
 concats_app-main.js:430:5
```

Please also note the first line of the log which is reporting an source map error related to FlowRouter that I've never seen before. This error is even still there if I remove the fastclick package and the app is working again. So it might not be related to this issue, but it's also new to me.

**Comment by derwaldgeist** [comment]
Update: I downgraded Firefox to 45.0 and 44.0, but the problem is still there (including the sourceMappingURL error message). So I can just guess the problem is caused by some silent upgrade of Meteor's build tools?

**Comment by gauravraj** [comment]
I'm also getting the same issue. I'm using Iron-Router. Whenever I try to open any page, it gives me this same error. I got this issue in chrome but site was opening properly in firefox. After a while, same thing started in firefox. Though if I try to access the server from another system using my ip, everything works perfectly fine. Now I'm getting the same issue with my previous meteor projects as well. How do I resolve this.

**Comment by derwaldgeist** [comment]
Update: I created a repo for reproduction:
https://github.com/concats/meteor-issue-6677

If you remove the fastclick package from this repo, the app works. But if you leave the fastclick package in, I get the following logs errors:

```
Die Verbindung zu ws://localhost:3000/sockjs/789/1sp0lorr/websocket wurde unterbrochen, während die Seite geladen wurde. ddp-client.js:1361:14
TypeError: Package.fastclick is undefined
 global-imports.js:6:1
ReferenceError: Template is not defined
```

**Comment by lucfranken** [comment]
If I run your repo on:

OSX Captain 
Chrome: 48.0.2564.116 (64-bit)
FF: 42.0
FF: 45.0.1

```bash
$ meteor
[[[[[ ~/xxxxxx/Software/meteor-issue-6677 ]]]]]

=> Started proxy.                             
=> Meteor 1.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

And no console logs whatsoever in any of those browsers. 

So I assume it's related to your local configuration. If I am right you had some issue with the configuration before but you state you re-installed so that's strange.

**Comment by derwaldgeist** [comment]
Nope, I did not have any configuration problems before. I just re-installed everything to make sure it's not a configuration problem. And the apps worked fine until yesterday morning (CEST). Since yesterday afternoon (i.e. morning in the US), they're broken.

**Comment by gauravraj** [comment]
Even I did the same thing. I re-installed everything and still the problem persisted. But I tried the same thing in a different PC and its working perfectly. This is the most weird part. If I run the server with fastclick and try to access it from a different PC using the local IP, its working fine.  After removing fastclick, the project is working perfectly fine.

**Comment by derwaldgeist** [comment]
I tracked this problem down a bit further and noticed that FF does not even load the package file, although it is included in the HTML and also located on disk. If I open the URL directly in the browser, I can see it.

If I replace the fastclick.js under the web.browser build by just a console.log printout, this will not show up in the console, whereas for all other packages, this works.

So I had an even closer look and found the program.json file inside that folder which contains a dictionary of all package files. fastclick.js is referenced there as well, but I noticed that the file size entry for this package is about twice as high as the actual file size on disk. For other packages (which I checked at random), the file size was correct.

I can just guess that Meteor has an internal mechanism that checks files for sanity based on their size and hash and refuses to load them if the values are not correct. But that wouldn't explain why I can easily modify the other files (add a console.log) and they still work. It's only the fastclick.js file that won't be loaded for whatever reason.

**Comment by derwaldgeist** [comment]
@gauravraj Interesting. Are you running Meteor on MacOS as well? BTW: The app works fine for me, if I start meteor with the --production flag. Seems as if the problem is somehow build-related.

**Comment by gauravraj** [comment]
No, I'm running it on Ubuntu 14.04

**Comment by derwaldgeist** [comment]
Thanks, good to know that it is not MacOS-related.

**Comment by Evan-Goode** [comment]
Your test repository works fine for me on FF 45.0.1 (OS X El Capitan). However, it does throw some errors around in Safari 9.1: [Screenshot](http://i.imgur.com/DS6sGdj.png)

I am having the same issue (only in Safari) with one of my projects; removing the fastclick package fixed the problem. Just an hour ago, my code worked fine.

**Comment by derwaldgeist** [comment]
@Evan-Goode That's quite funny. Seems as if different browsers are affected depending on whatever reason. For me, Safari and Chrome both work fine, but FF throws these errors. And @gauravraj reported that for him Chrome isn't working either. I have no clue what's going wrong here.

**Comment by lucfranken** [comment]
Comparing packages files:
`
# Your version:
accounts-password
audit-argument-checks
blaze-html-templates
check
ecmascript
fastclick
ejson
jquery
logging
meteor-base
mobile-experience
mongo
random
reactive-var
reload
service-configuration
session
spacebars
tracker
underscore

# Meteor 1.3 version
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
`

I see a lot of differences. I don't see anything mentioned in the Meteor guide (http://guide.meteor.com/1.3-migration.html) about requiring you to add any core packages.

Still I have the feeling there is a dependency on one of those new or updated packages. I would for sure try to move the meteor-base package to the top.

Also I would remove fast click from the core packages file and use only meteor-experience since that already applies fast click in the intended way.

**Comment by derwaldgeist** [comment]
The reasons that the minifiers are missing is my fault, because I had to remove them in order to use the versions by fourseven:scss. Otherwise, auto-prefixing would not have been possible. But the fact that they're missing should not matter in this case, since AFAIK the minifiers are only used for production deployments.

**Comment by derwaldgeist** [comment]
It's getting even weirder: Today the problem is gone! The only thing I did was to re-add the minifiers to my test repo, just to be sure they're not responsible. After I did that, the app was working. Then, I removed them again - and the app was still working! I now stopped the issue repo app and started my real app with fastclick. And even this worked, without adding and removing the minifiers. I have absolutely no clue why. But now my app is working as expected. Magic?!

**Comment by clayne11** [comment]
The issue is related to AdBlock.

I had the same thing happen to me a couple of days ago. It turns out an update to one of the AdBlock repositories was blocking the fastclick package.

I noticed the issue and checked AdBlock and one of the repos had been updated 18 minutes previously.

When I disabled AdBlock the issue went away.

The AdBlock extension automatically updates it's repos in the background so this happened silently and suddenly while I was working.

**Comment by lucfranken** [comment]
https://github.com/ftlabs/fastclick/issues/464
There it is, great find @clayne11 !

**Comment by derwaldgeist** [comment]
This explains everything, thanks a million @clayne11 and @lucfranken for pointing this out!

**Comment by guilhermedecampo** [comment]
@clayne11 awesome!

Thanks for replying the only extension I didn't remove to test chrome problems :eyes: 

:+1:
