### ISSUE TITLE
[1.3] npm install fails on Windows when username has a space

### ISSUE THREAD

**Issue by s-devaney** [meteor/meteor#6679]
When trying to run `meteor npm install` on Windows the command will fail if the username has a space in it.

`C:\Users\User Name\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\bin\\node.exe C:\Users\User Name\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\bin\\..\lib\node_modules\npm\bin\npm-cli.js install --save react react-dom
'C:\Users\User' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by mologie** [comment]
An explanation and fix for this issue was submitted under #6664. As workaround, open `%localappdata%\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\bin` and copy the changes from the pull request to `npm.cmd`.
