### ISSUE TITLE
1.3 regression: package peerlibrary:util does not work anymore

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6680]
With Meteor 1.3, and old package [`peerlibrary:util`](https://github.com/peerlibrary/meteor-util) does not work anymore. When adding it to the Meteor 1.3 project, the following warning is printed:

```
Unable to resolve some modules:

  "internal/util" in                          
.../.meteor/packages/peerlibrary_util/.0.3.0.mld599++os+web.browser+web.cordova/web.browser/node.js/lib/util.js
(web.browser)
                                              
Consider running: meteor npm install --save internal
```

And then in browser's console:

```
modules-runtime.js:417 Uncaught Error: Cannot find module 'buffer'
global-imports.js:9 Uncaught TypeError: Cannot read property 'util' of undefined
app.js:1 Uncaught ReferenceError: meteorInstall is not defined
```

Reproduction: https://github.com/mitar/meteor-issue6680

**Comment by mitar** [comment]
cc @benjamn

**Comment by serut** [comment]
I fixed an issue that was similar by adding 

api.use("modules");

to my package.js file 
The error was :

> => App running at: http://localhost:4096/
> spacejam: meteor is ready
> spacejam: spawning phantomjs
> phantomjs: Running tests at http://localhost:4096/local using test-in-console
> I20160414-07:38:51.119(0)? test-in-console listening
> phantomjs: ReferenceError: Can't find variable: meteorInstall
>     http://localhost:4096/packages/lmieulet_meteor-coverage.js?hash=49019b54cc7dd40dc24714c663db3df6008672b3: 55
>     http://localhost:4096/packages/lmieulet_meteor-coverage.js?hash=49019b54cc7dd40dc24714c663db3df6008672b3: 62

**Comment by Batistleman** [comment]
I'm having a similar issue here: https://github.com/meteor/meteor/issues/6537#issuecomment-209609947

Where did you find out about api.use("modules") ? I'll try this as soon as possible.

**Comment by mitar** [comment]
But this breaks backwards compatibility? If I add `api.use("modules")` then this package cannot be used anymore with Meteor 1.2?

**Comment by Batistleman** [comment]
Yes, I tested it and adding api.use('modules') fixes my error.

I should also note I only have this problem with 1.3.2-rc.5, not with 1.3.0.

**Comment by benjamn** [comment]
Right—adding `api.use("modules")` is unfortunately not an option for packages that want to be backwards compatible with pre-1.3 versions of Meteor.

To fix the `Cannot import module 'buffer'` problem, you just need to run `meteor npm install` in the app, since the `buffer` package comes with the `meteor-node-stubs` npm package.

Fixing the `internal/util` problem is going to require some changes on the `peerlibrary:util` side, because the [trick](https://github.com/peerlibrary/meteor-util/blob/98efd2e823c1ba90688f3eb5e4183ea54f01c7a8/before.js#L65) of defining a stub version of the `require` function is now broken for any app or package that uses `modules`.

If `peerlibrary:util` needs to use Node's `util` package, I recommend relying on `meteor-node-stubs` rather than trying to import the file from Node's own source tree and hoping for the best. 🙊

**Comment by mitar** [comment]
> Fixing the internal/util problem is going to require some changes on the peerlibrary:util side, because the trick of defining a stub version of the require function is now broken for any app or package that uses modules.

But this should be local to the package? This should not leak out, no?

**Comment by mitar** [comment]
Anyway, this seems to not be possible anymore. So much about keeping backwards compatibility:
* I cannot have `git submodule` of the node.js tree in my package anymore, in the repository, because Meteor now dies out of memory because it tries to traverse the whole node.js tree, even when I add only few files
* just `require`-ing `utill does not work, Meteor does not know what to do on the client (because `util` is node.js module, not package)

**Comment by mitar** [comment]
I see what happened, `ecmascript` dependency got `modules` as an implied package, and this is breaking stuff now with my mock `require`.

Moreover, even if I remove `ecmascript` (and thud `modules`) dependency, Meteor still tries to go through the whole node.js repository, with expected output: crash because of the memory.

**Comment by Batistleman** [comment]
Would it be possible to do a version check in your package? Something like:

    if(Meteor.release >= 1.3) api.use("modules");

**Comment by mitar** [comment]
`Meteor.release` exists in `package.js`?

**Comment by mitar** [comment]
Also, this is really problematic that `ecmascript` now implies `modules`. So I cannot just use `ecmascript` to compile ES6 into ES5. And `ecmascript` is not just some thin package, but compilation itself is in the `ecmascript`. Could `ecmascript` be split into `ecmascript-plugin` which `ecmascript` implies? Then I could just use `ecmascript-plugin` here.

**Comment by mitar** [comment]
I made a pull request with package split: #6824

Now I can continue compiling ES6 files without using Meteor's `require`. This allows me to use my mock `require` to load `node.js` file.

Of course, `node.js` subrepository seems too big for Meteor, but this is another issue.

**Comment by benjamn** [comment]
Submitted a pull request to fix `peerlibrary:util`: https://github.com/peerlibrary/meteor-util/pull/3. Happy to discuss details over there.

I know #6824 seems like it fixed your problems, but removing modules support from the `ecmascript` package is not an acceptable solution here.
