### ISSUE TITLE
App.accessRule type data for navigation

### ISSUE THREAD

**Issue by lucfranken** [meteor/meteor#6683]
**Environment**
1.3 with Cordova on iOS
Might relate to #6654.

**Problem**
If you try to load a PDF or other data url in an iframe.src you get errors in the console. It is not allowed the data URI, following error is received in Xcode:

> ERROR Internal navigation rejected - <allow-navigation> not set for url='data:application/pdf;base64

The error text does not relate to accessRule which makes it quite hard to find. 

**Solution**
In this case the solution is:

`
App.accessRule('data:*', {type: 'navigation'});
`

**Solutions**

2 fixes I think are possible:

Allow data attributes by default if secure. If not secure that should be added to the doc maybe.

OR

A better error and a more explicit list here: https://docs.meteor.com/#/full/App-accessRule which tells you which kind of URI's are not allowed.

**Security and docs**
The security issue: http://cordova.apache.org/announcements/2014/08/04/android-351.html and the http://cordova.apache.org/docs/en/6.x/guide/appdev/whitelist/index.html are both not specific on the data tag.

**Comment by martijnwalraven** [comment]
I don't think we should whitelist `data:` URLs by default, but we could add this to the docs. We have no control over the error messages unfortunately, because these are part of Cordova.

**Comment by lucfranken** [comment]
Sounds like the right thing to do, that will help users in the future!

**Comment by martijnwalraven** [comment]
Closing this, because it was added to the mobile guide.

**Comment by rashmimhatre100** [comment]
I am using [react-html-table-to-excel](https://www.npmjs.com/package/react-html-table-to-excel) for exporting table to xls format. At the beginning I was getting ERROR Internal navigation rejected - not set for url='data:application/pdf;base64, then I added access rules and now xls is opening and no error is there. But expected output would be file to be download in the format of the .xls and not opening it. Once the xls is open it is not possible to go back to ios-app, one need to kill it.
