### ISSUE TITLE
windows installer text is obsolete and misleading - "our free service"

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#6684]
![image](https://cloud.githubusercontent.com/assets/485535/14225318/642bd886-f8c7-11e5-9332-93d106692e5f.png)

Unfortunately, the free service was hunted down and now only payed galaxy service is available!

Does anyone still reads these texts? :)

**Comment by helfer** [comment]
Thanks for pointing it out, we have  a pull request that fixes it: https://github.com/meteor/meteor/pull/6685

It will be included once we get around to recompiling the windows installer.

**Comment by stubailo** [comment]
(To clarify, recompiling the installer is an arduous process that involves physical certificate signing keys, very specific visual studio builds, etc, so sorry that it takes a bit longer than it should)

**Comment by hwillson** [comment]
This was completed - thanks for posting this originally!

**Comment by hwillson** [comment]
Ooops - turns out this wasn't fully completed. The submitted changes are still pending a re-compile (https://github.com/meteor/meteor/pull/6685#issuecomment-205147754). Re-opening!

**Comment by hwillson** [comment]
I believe a re-compile has happened since https://github.com/meteor/meteor/issues/6684#issuecomment-276139992, so I'll close this off (again 🙂). Thanks!

**Comment by abernix** [comment]
Actually, this still hasn't happened. 😞

**Comment by hwillson** [comment]
The old Windows installer has been replaced by [`choco install meteor`](https://www.meteor.com/install) in Meteor 1.6. Closing this off (for good this time! 🙂).
