### ISSUE TITLE
[1.3] Cannot build server-only meteor bundles

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6689]
Error when trying to run the following command:

```
meteor remove-platform browser

While removing platforms:
error: browser: cannot remove platform in this version of Meteor
```

I'd like to build a server-only Meteor app that has no need to run from the browser (server worker).

**Comment by lucfranken** [comment]
Might be related: https://forums.meteor.com/t/build-server-only-for-mobile/20675/2 http://guide.meteor.com/mobile.html#building-for-production

**Comment by martijnwalraven** [comment]
The `--server-only` option doesn't build the mobile apps, but it still builds all the client bundles, including the browser one. There is currently no way to skip building client bundles completely.

**Comment by alfredjkwak** [comment]
Interested to get this one supported, would make sense also for pure Restivus server, see tools for REST APIs for Meteor, https://github.com/meteor-rest

**Comment by alfredjkwak** [comment]
@markoshust @martijnwalraven 
Made changes to allow removal of browser & building of 'web.browser', https://github.com/alfredjkwak/meteor/pull/1

I could make PR here also, if those changes make any sense.
In application startup, I set WebApp.defaultArch = 'server'; to tell webapp skip client boilerplate.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5B1.3%5D%20Cannot%20build%20server-only%20meteor%20bundles&body=Migrated%20from:%20meteor/meteor%236689) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
