### ISSUE TITLE
[1.3] Client refresh bug - Builder slowly notice file modifications

### ISSUE THREAD

**Issue by valentinvichnal** [meteor/meteor#6690]
***1 Upvote*** I updated a project from 1.3-beta6 to 1.3.
The beta6 release worked well, it rebuilt the client files on the first client file modification.
Since the update the server rebuild became a lot slower, but the real issue is the client refresh.
I need to modify a client only file up to 10 times, until finally the file watcher notified by this change, and rebuild the client files and refresh the browser.

There was no other modification to that repo, no other npm or Meteor packages was added, so I guess it is not my fault.

**Comment by jebarjonet** [comment]
+1

I have the same issue, build is slooow, checking every single package everytime I update a client file.

Probably a link with #6662

**Comment by valentinvichnal** [comment]
Probably related to #6750
