### ISSUE TITLE
[1.3] Waiting for a 30 seconds

### ISSUE THREAD

**Issue by yimankaing** [meteor/meteor#6695]
Hello Meteor! I encounter a small issue which occurs after i run my project. I have to  **wait for a 30 seconds** then Meteor is searching my packages. I am sure that it is not my computer problem!

**Comment by pisethtieb** [comment]
RAM?

**Comment by yimankaing** [comment]
Hey man! I told you that it is not my computer problem!

**Comment by sanderdatema** [comment]
@yimankaing No need to shout. If you need help, help others to help you: give as much details as you can. Including what system you run this on. Just saying it doesn't work makes it difficult to help you out.

**Comment by stubailo** [comment]
Can you give us more information about your machine? What operating system are you running? Can you show what the output of the tool is while you are waiting?

**Comment by yimankaing** [comment]
@sanderdatema 
@stubailo 
I have solved this problem. I don't know why it happened. Everyday it seems normal but on that day i encountered that one. Thanks for dropping down comments. I am sorry for not giving enough information to you. This is my first issue.  Thanks so much!!

**Comment by abernix** [comment]
Glad you got it resolved. :smile:
