### ISSUE TITLE
Load local video file on Android in not working

### ISSUE THREAD

**Issue by jamalx31** [meteor/meteor#6697]
I'm trying to view a video located in
/data/data/com.app/files/../file.mp4

I build the url:
http://localhost:12472/local-filesystem/data/data/com.app/files/../file.mp4

but I can't play the video, when I try to access an image from the same location it works well

**Comment by martijnwalraven** [comment]
Unfortunately, the URL interception mechanism Meteor uses to serve local files does not support video playback. 

You may be able to use a plugin to play the video instead. I haven't tried it myself, but [this plugin](https://github.com/moust/cordova-plugin-videoplayer) looks promising.

**Comment by jamalx31** [comment]
@martijnwalraven Thanks,
Is there a reason not to support video playback ? or planing to add this feature in the future ?

**Comment by martijnwalraven** [comment]
It is a technical limitation of the URL interception mechanism Cordova implements on Android.

**Comment by jamalx31** [comment]
@martijnwalraven The plugin you suggested works but the video preview doesn't work very will 
Using this plugin was much better and can use it with the ```<video>``` tag
https://github.com/floatinghotpot/cordova-httpd

**Comment by martijnwalraven** [comment]
Closing this, because this isn't something we can fix ourselves and there are workarounds available.
