### ISSUE TITLE
Can't use npm modules whose `main` is not .js/.json

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#6699]
Got a report: Can't use bwip-js directly from a Meteor app.

The error (only when deployed) is:

```
Can't find npm module 'bwip-js'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```

@benjamn this is the issue we took a look at and you decided it was because bwip-js's main file doesn't have an extension.  Either fix this to work, or at least improve the error message. There's also a workaround you mentioned.

**Comment by benjamn** [comment]
Submitted a PR to `bwip-js`, though I plan to address the problem on the Meteor side as well.

**Comment by benjamn** [comment]
As a temporary workaround, you should be able to get it to work (on the server) by adding this code snippet anywhere before where `bwip-js` is imported:
```js
meteorInstall({  
  node_modules: {
    "bwip-js": {
      "node-bwipjs": function () {}
    }
  }
});
```

**Comment by benjamn** [comment]
This issue will be officially fixed (without needing any workarounds) when Meteor 1.3.2 is released today or tomorrow, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.
