### ISSUE TITLE
mongodb reconnection

### ISSUE THREAD

**Issue by Latnok** [meteor/meteor#6700]
no aswers on issue #5773. new post

My configuration is app deployed with meteorUp on cloud hosting with ip 190.#.#.# behind nginx, and my database on my own server with ip 91.#.#.# replicaSet with 3 nodes behind proxy (port forwarding).
After 3-4 users connections to my app it don`t answer, in logs after 60-90 sec added
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27017]
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27018]
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27019]

and app isn`t restarted! app users view only white screen.

mongo connection settings:
"MONGO_URL": "mongodb://usr:pwd@91.#.#.#:27017,91.#.#.#:27018,91.#.#.#:27019/myapp?replicaSet=myRepl&authSource=admin"
"MONGO_OPLOG_URL": "mongodb://usr:pwd@91.#.#.#:27017,91.#.#.#:27018,91.#.#.#:27019/local?replicaSet=myRepl&authSource=admin"

mongo nodes is up. 
connection from 190.#.#.# mongo --host=91.#.#.#:27017 is ok
connection from 190.#.#.# mongo --host=91.#.#.#:27018 is ok
connection from 190.#.#.# mongo --host=91.#.#.#:27019 is ok

but then my app deployed on my own server 91.#.#.# with meteorUp behind nginx (same connection settings), it works fine.

meteor --version = 1.3
mongodb --version = 3.2.3

please fix this problem, app in production now and I can`t scaling it!

**Comment by benjamn** [comment]
Let's consolidate this discussion at #5773, which you correctly identified as a duplicate.
