### ISSUE TITLE
Scroll not working in IOS meteor 1.3 

### ISSUE THREAD

**Issue by dhavaldigicorp** [meteor/meteor#6702]
Hello

I have update this meteor version and now image upload is completely working fine but i am not able to scroll my long page in IOS(Scroll working in Android). Please help to out from this problem. I am facing this kind of issues in my meteor app please help me ASAP. Because i need to deliver my app today your help make my day.

Thanks in advance

**Comment by joaopiopedreira** [comment]
You might want to give some more details about that scrolling issue (template code, css)

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by dhavaldigicorp** [comment]
Sorry for the less detail. Now my issue is solved i have install ionic keyboard 1.0.8 plugin this version plugin is not compatible with meteor 1.3 thats why scroll is not working in iOS application. Now i have removed that plugin and its working fine

but thanks for the reply. :)
