### ISSUE TITLE
How to return value on Meteor.call() in client?

### ISSUE THREAD

**Issue by rorschach217** [meteor/meteor#6703]
i want to return true if data was found from the mongodb from server. but i cannot.
here is my code

this is js file for template in client section.
`Template.createUser.events({`
    `'submit' : function (event, template) {`
        `event.preventDefault();`
        `var username = document.getElementById("username").value;`
        `var password = document.getElementById("password").value;`
        `if(isUserExist(username)) {`
            `sAlert.error("This username already exist !");`
            `return;`
        `}else{`
        `}`
    `}`
`});`

and i put this code in lib directory in methods.js

`if(Meteor.isClient){`
    `isUserExist = function (username) {`
        `return Meteor.call("isUserExist", username);`
    `};`
`}`

`if(Meteor.isServer){`
    `Meteor.methods({`
        `isUserExist : function(username){`
            `var user = Meteor.users.findOne({username : username});`
            `return (user) ? true : false;`
        `}`
    `});`
`}`

please suggest me something.

**Comment by skirunman** [comment]
The issue tracker is not for getting help. You should close this and ask your question on https://forums.meteor.com/ or http://stackoverflow.com/questions/tagged/meteor as you will likely get someone to help you.

**Comment by lyquocnam** [comment]
Meteor.call() have callback method men ! see in the docs.
```
Meteor.call('someMethod', (error, result) => {
      if (error) ...
     else
         return result;
});
```

**Comment by stubailo** [comment]
Using a callback is the right way to get a method return value on the client.
