### ISSUE TITLE
'Client modified -- refreshing' hangs

### ISSUE THREAD

**Issue by mkalygin** [meteor/meteor#6705]
Possible duplicate of #5074.

Hi! I really enjoy using Meteor, thanks for such a good framework. The problem appeared after I've installed the following packages:

```
less
coffeescript
fortawesome:fontawesome
mquandalle:jade
```

This bug makes my development experience very slow since I need to reload Meteor application every time I make any changes and want to check them in a browser.

### What I've tried

1. `$ meteor update` to v1.3 didn't help.
2. Cleaning `.meteor/local` directory didn't help.

### Repro steps

1. Start the Meteor application: `$ meteor`.
2. Edit any `.jade` or `.coffee` file and save.
3. `Client modified -- refreshing` message appears in the terminal.
4. Open `http://localhost:3000/` in a browser.

**Expected**: the client is refreshed without any problems and I can see the changes I've made in `.jade` and `.coffee` files.

**Observed**: a browser refreshes the page many-many times unless I kill the Meteor process and start the Meteor again. After starting the Meteor again I can see all the changes I've made in `.jade` and `.coffee` files.

### Debug output

`$ METEOR_PROFILE_REQUIRE=1 METEOR_PROFILE=1 METEOR_LOG=debug VELOCITY_DEBUG=true meteor --verbose`

[OUTPUT](https://gist.github.com/mkalygin/991a5285de1d2cafe0d19b6f35cd6eb2)

### Environment

Node.js v5.7.1
NPM v3.6.0
Meteor v1.2.1
OS X El Capitan v10.11.3 (15D21)
MacBook Pro (13-inch, Mid 2009)
**Processor** 2,53 GHz Intel Core 2 Duo
**Memory** 8 GB 1333 MHz DDR3
**Graphics** NVIDIA GeForce 9400M 256 MB
**Storage** Samsung EVO 850 120 GB SSD

### Packages

`$ cat .meteor/versions`

[OUTPUT](https://gist.github.com/mkalygin/61a6dfe89c8cda6a5a361aba6368b590)

**Comment by benjamn** [comment]
I tried reproducing with those steps, but unfortunately couldn't get this to happen in my environment. Can you start with your app that isn't working, and then remove packages and files until you can't remove anything else without making the problem go away?

**Comment by mkalygin** [comment]
Hi @benjamn, thanks for the response.

I've followed your advice and have found that the `meteorhacks:cluster` package causes this issue. If I remove it everything works as expected. I will post this issue to the issue tracker of the package's repo.

Thanks for the help!

**Comment by benjamn** [comment]
Thanks, I'll check out `meteorhacks:cluster` to make sure we're not doing something weird with it.

**Comment by abernix** [comment]
@mkalygin Doesn't seem that this has been a popular error among others so far – and `meteorhacks:cluster` is a relatively popular package.  Are you able to reproduce this in a more current version of Meteor?  Also, to facilitate debugging and reproducing it, can you please create a barebones, minimal reproduction in a new Meteor project that highlights this problem and upload the project to Github?

Would be much appreciated in helping to track this problem down!

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
