### ISSUE TITLE
NPM packages and source maps.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6715]
Some NPM packages are compiled with Babel, then the compiled files placed in a `dist` folder with the `main`field pointing to the entry point for example. Those files often contain bable syntax and use babel helpers. 

When those packages throw errors, etc, what would be the best practice so that Meteor can (or could in the future) use source maps for those files?

If Meteor has no source map feature at all for NPM packages currently, could there perhaps be a convention for Meteor to look along side a file for it's source map? For example, `dist/main.js` would have `dist/main.js.map`. Does Meteor look at inline sourcemaps that are left as comments inside the files?

It'd be nice to have some sort of convention (if it doesn't already exist) for source mapping NPM packages in Meteor (or in NPM in general), as currently if there's an error from an NPM package's transpiled code, we see that ugly code in the console while investigating the error.

**Comment by benjamn** [comment]
This is a good idea, though source map concatenation ends up being one of the most expensive parts of the build process, so we'd have to keep performance in mind. I suppose publishing source maps to npm is rare today, though, so maybe this concern is premature.

I think the current convention is having a `//# sourceMappingURL=...` comment in the generated file. That's what `node-inspector` looks for when debugging server-side code, at least.

**Comment by trusktr** [comment]
@benjamn The downside of the inline source maps is it is included in the file size that gets passed through the network, but if the source map comment supplies a comment, then that source map will only be fetched when devtools is opened, so normal users won't experience any lag from the download.

Maybe source maps can be served independently from the application bundle, served only when the devtools are opened?

**Comment by benjamn** [comment]
Though inline source maps are appealing in many cases, the `//# sourceMappingURL=...` doesn't have to be an inline `data:` URL. It can be the relative path of a file on the file system somewhere nearby, which I think would satisfy your concerns?

**Comment by trusktr** [comment]
> It can be the relative path of a file on the file system somewhere nearby, which I think would satisfy your concerns?

Does Meteor grab and use that specified file? On the client that doesn't do anything currently, or does it? That'd be a nice feature for Meteor. :]

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=NPM%20packages%20and%20source%20maps.&body=Migrated%20from:%20meteor/meteor%236715) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
