### ISSUE TITLE
[Meteor 1.3] [bug] ES6 language features missing.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6716]
I'm in Safari 8 and getting an error that `undefined is not a function` for some code like `array.includes(...)`.

Is `ecmascript` not handling this language feature? I didn't notice the problem in Chrome because Chrome has Array.prototype.includes already.

I see babel-polyfill/core-js does feature detection: https://github.com/zloirock/core-js/blob/master/modules/_export.js#L19-L31. Can that be used? Would adding babel-polyfill to an app cause any problems with Meteor's polyfills/shims?

**Comment by trusktr** [comment]
I suppose this is a feature request for missing ES6 language features. :D

**Comment by trusktr** [comment]
I guess the problem is fixed by importing babel polyfill, but that seems [heavy weight](https://github.com/zloirock/core-js/blob/master/shim.js). Is that the reason for not including babel-polyfill by default in Meteor?

**Comment by trusktr** [comment]
Workaround for the meantime: search and replace all `.include(foo)` with `.indexOf(foo) >= 0`.

**Comment by trusktr** [comment]
For a second I thought that maybe Meteor was simply ignoring node_modules (which makes sense, a library should transpile on prepublish), but, Meteor isn't handling `.includes` in app code either.

**Comment by aldeed** [comment]
Array#includes is actually an ES7+ proposal, but if it were to be added, I think the correct core-js dependency would just need to be added to the [ecmascript-runtime](https://github.com/meteor/ecmascript-runtime) package

https://github.com/zloirock/core-js#ecmascript-7-proposals

**Comment by trusktr** [comment]
@aldeed Ah, gotcha. I thought it was es6 for some reason.

**Comment by abernix** [comment]
Meteor supports anything ES6 that Babel supports.  When Meteor switches to ES7, this will work – but that's not ready now. :smile:
