### ISSUE TITLE
SockJS in ddp-client should be exported

### ISSUE THREAD

**Issue by Type1J** [meteor/meteor#6719]
I need to add a transport to SockJS for DDP. This is completely possible if I add SockJS as an export to ddp-client.

There are 3 possible solutions:
1. Add SockJS as an export to ddp-client.
2. Make SockJS a separate package that only exposes SockJS if it is explicitly added to a project.
3. Assign SockJS to DDP.SockJS, where DDP is already exposed.

I don't have a preference on which solution is used, but I would like 1 of these 3 solutions to be in the Meteor code itself, so that I don't have to tediously work around it anymore.

I have the load order problem worked out by disconnecting, then reconnecting after adding the new transport to SockJS. This issue is only for enabling the SockJS object to be exposed somehow.

**Comment by sebakerckhof** [comment]
I have a preference for option 2, where SockJS becomes an optional import for DDP. 
Related issue: https://github.com/meteor/meteor/issues/4897

This would solve your problem and allow to reduce the JS payload for people who only target websocket-enabled browsers.

**Comment by wojtkowiak** [comment]
@Type1J I have recently published https://github.com/wojtkowiak/meteor-custom-protocol which you may find useful. I am using this already in production for more than a year for implementing WebRTC signaling and better sub/pub performance.

**Comment by Type1J** [comment]
@wojtkowiak Your 2 projects (meteor-custom-protocol and meteor-direct-stream) are impressive. I might use them in a future project.

I'm not sure if they sovlve this issue, though. This issue is here because I'm using Meteor client code in an environment that is not a web browser, and the WebSocket API is slightly different in that environment.

**Comment by wojtkowiak** [comment]
@Type1J thanks :smile:
Oh now I get it. I just briefly read the issue and got the impression you want to send something custom on the socket while you meant SockJS transport. In this case I agree that my packages will not help you with this specific issue.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=SockJS%20in%20ddp-client%20should%20be%20exported&body=Migrated%20from:%20meteor/meteor%236719) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
