### ISSUE TITLE
[1.3 & 1.3.1] Problem using fibers

### ISSUE THREAD

**Issue by AnthonyAstige** [meteor/meteor#6720]
It appears Meteor 1.3 is forcing fibers 1.0.8 install when I try to use fibers in my project, which causes a npm install failure on a built project.  If I manually install fibers 1.0.7 everything seems to work, but this is a workaround and feels wrong.

Detailed reproduction & platform notes @ https://github.com/AnthonyAstige/too-high-fiber

**Comment by benjamn** [comment]
The npm `fibers` package is at 1.0.10 now—does installing that version help at all?

**Comment by AnthonyAstige** [comment]
Is changing fibers to 1.0.10 a very recent change / in a beta version of Meteor? The tests were just set up from scratch about an hour before your message. If it's a beta version to try, can you point me in the right direction to try it (I've only used stable Meteor versions so far)?

**Related notes** (perhaps you're already aware of)
The [reproduction's package.json](https://github.com/AnthonyAstige/too-high-fiber/blob/master/package.json) has fibers 1.0.10 set in it. However [the install looked like it was trying to to install fibers 1.0.8](https://raw.githubusercontent.com/AnthonyAstige/too-high-fiber/master/fiber-fail.png)

**Comment by AnthonyAstige** [comment]
I just tried this again and same problem on Meteor 1.3.1

**Steps taken**

1. Ran `meteor update` locally on repository >> committed >> pushed up to github
1. Followed my reproduction instructions in [README](https://github.com/AnthonyAstige/too-high-fiber/blob/master/README.md)
 1. Got the same problem
 1. Sanity check new meteor pulled `cat ./.meteor/release` >> `METEOR@1.3.1`

**Comment by AnthonyAstige** [comment]
I just started a new Meteor 1.3.1 project, this time without manually adding fibers.  I got the same problem.  And the same workaround works.

This may have more to do with npm / node versions.

**Comment by AnthonyAstige** [comment]
[Related meteor forum post from miriam7](https://forums.meteor.com/t/npm-warn-saveerror-missing-fibers-1-0-8-required-by-meteor-dev-bundle-0-0-0/23457)

**Comment by AnthonyAstige** [comment]
I (think I) ran into this this issue again when starting a new production server on Ubuntu 16.04 (migrating from an old server running 14.04).  It appears there was a requirement for Python 2.X. Maybe up to 3.0, but 3.5 didn't work. I figured this out reading the error messages more closely.  

Here's what I've done on my Ubuntu 16.04 production server

```
sudo apt-get install -y python2.7-minimal
cd /usr/bin && ln -s python2.7 python
```

At least initially it appears no more work-around is needed.

I'm wondering if this will all self-resolve when Meteor moves part Node v0.10.4X onto Node v4 which may kick fibers up to a new version, which may in it's self know how to use the latest python as it comes packages with Ubuntu.

In any case this feels more like an environment issue than a direct Meteor issue, so I'm closing it.
