### ISSUE TITLE
[1.3.1] Update results in Error: Can't find npm module 'babel-runtime/helpers/typeof'.

### ISSUE THREAD

**Issue by pors** [meteor/meteor#6723]
Updating from 1.3 to 1.3.1 broke something for me. All was running fine with 1.3, now I get:

```
$ meteor run
[[[[[ ~/dev/reactionic-kitchensink/app ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160406-20:06:32.096(3)? (STDERR)
W20160406-20:06:32.097(3)? (STDERR) /Users/mark/dev/reactionic-kitchensink/app/.meteor/local/build/programs/server/boot.js:324
W20160406-20:06:32.097(3)? (STDERR) }).run();
W20160406-20:06:32.097(3)? (STDERR)    ^
W20160406-20:06:32.213(3)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160406-20:06:32.213(3)? (STDERR)     at Object.Npm.require (/Users/mark/dev/reactionic-kitchensink/app/.meteor/local/build/programs/server/boot.js:195:17)
```

etc.

**Comment by eldog** [comment]
I had to delete my local meteor installation, i.e.,  run `rm -rf ~/.meteor`, to fix the error.

**Comment by pors** [comment]
@eldog that does it for me as well, thanks!

I now get these warnings, but at least it works again

```
W20160409-11:45:31.527(3)? (STDERR)  - react@0.14.7 installed, react@15.x needed
W20160409-11:45:31.527(3)? (STDERR)  - react-addons-pure-render-mixin@0.14.1 installed, react-addons-pure-render-mixin@15.x needed
```

**Comment by vittaljk** [comment]
Thank you it helped me!!!!!

**Comment by meyian** [comment]
I'm having this error, and deleting the .meteor folder means you can no longer run your application. Need help with this issue, is it possible to have this thread reopened?

**Comment by meetmagdalene** [comment]
+1 for this issue to be reopened. 

I receive this error after updating to meteor 1.3.2.4.

**Comment by timmygee** [comment]
I've re-opened a similar issue here https://github.com/meteor/meteor/issues/6918

**Comment by namelivia** [comment]
I'm also having the same issue, I tried doing `rm -rf ~/.meteor` but then after doing `meteor update && meteor` for reinstalling and launching the application again I am getting the error again.

**Comment by meyian** [comment]
Hi everyone, I think I have a solution. Basically, you have to delete your meteor installation, and then reinstall it. 

These are the steps:

1.
`sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor`

(If you're like me, you'll find that you can't just rm -rf ~/.meteor - the system hangs. So you have to go in, and delete folder by folder. I did it by going into the ~/.meteor folder doing something like rm -rf ./a* to get rid of all the directories starting with "a", and then moving on through the rest of the alphabet.)

2.
Then, reinstall meteor

`curl https://install.meteor.com/ | sh`

That should get things working for you.

**Comment by meetmagdalene** [comment]
Thanks for the suggestion @meyian! That fixed it for me. I am now running my project on Meteor 1.3.2.4 without issue.

**Comment by timmygee** [comment]
I can confirm that this error is resolved by removing the `.meteor` directory in your home directory with

```
rm -r ~/.meteor
```

(This takes a long time if you have a lot of packages)

Then re-install meteor with 

```
curl https://install.meteor.com/ | sh
```

**Comment by abbood** [comment]
damn man.. i'm just going through the tutorials/installation of meteor and this is the second major bug i'm finding.. why so broken guys? comon!

**Comment by abbood** [comment]
```
$ rm -rf ~/.meteor
$ meteor 
abdullahbakhach, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
##############################                                            42.0%
curl: (18) transfer closed with 96327924 bytes remaining to read
.meteor/packages/logic-solver/.2.0.5.1lakk47++os+web.browser+web.cordova/os/logic.js: (Empty error message)
tar: Error exit delayed from previous errors.
```

**Comment by abernix** [comment]
Just as a pointer to anyone who might be experiencing this issue, you may be able to avoid reinstalling Meteor completely by simply removing the `<PROJECT_DIR>/.meteor/local/bundler-cache/` directory and relaunching your app. Should be a lot quicker than a full-reinstall.

**Comment by n1mmy** [comment]
@abbood I think your issue may be different from the original one in this report. We've been getting reports of issues with meteor installer downloads in different geographic areas and we're trying to track down the problems. It would be very helpful if you could send me your IP address and the output of `traceroute static-meteor.netdna-ssl.com`. If you're not comfortable posting your IP publicly, feel free to email me privately at nick at meteor dot com. Thanks!

**Comment by array-addu** [comment]
removing .meteor and then re-installing meteor doesn't help me. It doesn't taking the meteor command as .meteor folder is deleted, any solution for this?

**Comment by liambrownweb** [comment]
I've uninstalled and reinstalled meteor, deleted all the ~/.meteor directories, deleted [app]/.meteor/local, tried running as different users, reinstalled and re-reinstalled multiple versions of the babel-runtime library both locally and generally, with and without --save-dev, and nothing is working. Still seeing that error.

**Comment by abernix** [comment]
@liambrownweb Please see #8032 for the solution!
