### ISSUE TITLE
[1.3.1] import preloading

### ISSUE THREAD

**Issue by brettg2** [meteor/meteor#6727]
The new ES6 module support for 1.3 was supposed to include "lazy-loading" support of code stored in the /imports directory, however all imported code is still bundled into an app.js file and sent to the client. Where is the benefit of a non-eager loading system when all the code is pushed to the client on initial load anyways?

Is there a way to dynamically load modules? What if I have hundreds or thousands of components to load depending on the user's interaction? What if the user is on a mobile phone using our web app that requires them to download megabytes of template code to their phone's memory? What if a user never visits certain sections of the app? Why would I give them the code for those sections? Why must we use the module import programming style when the benefit is exactly the same without?

If I'm mistaken, please let me know. Thank you!

**Comment by skirunman** [comment]
You are confusing what Meter has been calling"lazy-loading" (I prefer to call it "lazy evaluation") with [code splitting](https://webpack.github.io/docs/code-splitting.html). There are [benefits of lazy evaluation](https://en.wikipedia.org/wiki/Lazy_evaluation) such as controlling load order and scope.

Meteor does not have support (yet) for code splitting or dynamically loading code chunks. Webpack supports this and I suspect at some future date Meteor will support it.

Today you can use this [Webpack solution](https://github.com/thereactivestack/meteor-webpack/tree/master/packages/webpack/).

**Comment by laosb** [comment]
Related to #6967 , Closing this one.
