### ISSUE TITLE
Meteor 1.3 is not backward compatible with iron:router 

### ISSUE THREAD

**Issue by Noveltysa** [meteor/meteor#6734]
ver 1..3 is not backward compatible with the latest version of iron:router,
the localmarket example(1.3) does not work with the latest iron:router, the localmarket example only works with iron:router@0.9.4

**Comment by alexandesigner** [comment]
I did a simple test here, I got the same problem ... However, I managed to update 'removing' and then 'adding' the package iron:router

**Comment by benjamn** [comment]
Opened an issue over at the new localmarket repo: https://github.com/meteor/localmarket/issues/3

The new version of `iron:router` (1.0.12) indicates there were major breaking changes, so it's no surprise that some work will be needed to upgrade.
