### ISSUE TITLE
[1.3] `check`'s Match.Optional now allows "null" (contrary to plan)

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#6735]
As found during research for the problem in  #6712, `Match.Optional` now matches `null` when it had not before 1.3.  The (ultimate) decision in Issue #3876 was to keep `Match.Optional` the same (allow `undefined`) and introduce a new `Match.Maybe` which would match `null` and `undefined` in order to **NOT** do this:

> silently change the (`Match.Optional`) behavior because it could introduce undiscoverable security holes into people's apps

Unfortunately, the way that that #6220 was done, it literally did exactly that, and there was no Match test in place to make sure that `null` did not pass `Match.Optional`.

I have an incoming PR to fix this.  This Issue is just for the record.

**Comment by stubailo** [comment]
I appreciate filing the issue before opening the PR!

**Comment by abernix** [comment]
No problem! :neckbeard:  Speaking of – do you all *prefer* to have a single issue with the pull-request attached to it?  (as you can do with the `hub` command)... Or separate issue/pull-requests/numbers?

**Comment by stubailo** [comment]
Hmm, I don't really know that we have a strict preference at the moment.

**Comment by tmeasday** [comment]
@abernix let's stick with separate issues/PRs otherwise it may get confusing in categorization.
