### ISSUE TITLE
Meteor.loginWith<Service> fails when served under a directory.

### ISSUE THREAD

**Issue by vinvinod** [meteor/meteor#6737]
I have problems adding support for third party authentication to my meteor app.

Meteor Version: 1.3.1
Platform: Ubuntu 14.04 x86_64
Packages used: accounts-google + accounts-ui

The meteor server is started with `ROOT_URL=http://localhost:3000/app`

After authentication from google, the pop window is redirected to http://localhost:3000/app/_oauth/google?state=someLongStateString&code=someCodeString#

At this time, there is a console error 
`GET http://localhost:3000/packages/oauth/end_of_popup_response.js 404 (Not Found)`

However the actual path should have been `http://localhost:3000/app/packages/oauth/end_of_popup_response.js`

The sample project to reproduce the problem is at [https://github.com/vinvinod/meteor-google-test](https://github.com/vinvinod/meteor-google-test)

**Comment by vinvinod** [comment]
Can anyone confirm whether this issue is reproducible?

**Comment by laosb** [comment]
Could you share an Client ID and secret so we can do a quick repro?

**Comment by vinvinod** [comment]
Hey, Sorry, I was on a break from Meteor!

I have included the clientId and secret inside `Meteor.startup()` now. Just pull in new code.
Also note that authorized redirect URL is `http://localhost:3000/app/_oauth/google`
Let me know if u need any more help.

**Comment by laosb** [comment]
OK, will review this weekend.

**Comment by vinvinod** [comment]
@laosb : Did you get a chance to look into this issue?

**Comment by laosb** [comment]
Oh my fault! This weekend, I promise this time!

**Comment by laosb** [comment]
OK, tested, but the redirect uri wasn't right.
My procedures:
```
$ ROOT_URL=http://localhost:3000/app meteor
[[[[[ ~/tests/meteor-google-test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started your app.

=> App running at: http://localhost:3000/app
```
Then clicked `Sign in with Google`. It shows this:

![image](https://cloud.githubusercontent.com/assets/2545261/15631171/02a39b6e-258e-11e6-9820-a1722e1b9d06.png)

**Comment by vinvinod** [comment]
I had made some changes in google dev console. But had forgotten to revert back!
Please test now!

**Comment by laosb** [comment]
Will see this weekend. I believe that it should exist as you said, and I've started digging the code. 

Or, @abernix , do you have time to take a look? I've only a old computer with Windows XP in school.

**Comment by abernix** [comment]
I can confirm this is broken.  Unfortunately, I don't have time to investigate why right away!

**Comment by hwillson** [comment]
The repro works properly if updated to Meteor 1.4.3.2, so please consider updating your Meteor version. Closing - thanks!
