### ISSUE TITLE
feature - Add beginPoll and endPoll optional callbacks to mongo cursor observe/observeChanges.

### ISSUE THREAD

**Issue by okland** [meteor/meteor#6740]
The problem this feature request try to solve is responding to all the notifications (added, changed, removed operation) that has been received due to one polling operation over the db in a batch. 
So subscriptions that want to send updates to their client in batch can do this efficiently.
For example subscription of 300 docs that change each second instead of sending 300 messages a sec we can send one message with all the updates.

To read more about the use case -
https://medium.com/@omriklinger/should-we-allow-custom-ddp-messages-a5fff26673e2
https://medium.com/@omriklinger/how-to-send-1000-updates-sec-per-client-using-meteor-and-stay-alive-88eba7588c36

It is a part of easily allowing meteor developers to allow batch publication together with ddp custom messages PR - https://github.com/meteor/meteor/pull/6117

**Comment by abernix** [comment]
There were nice improvements to the DDP handling in Meteor 1.3.2.4 (thanks to #5680) which should have greatly improved this handling.  Unfortunately, as it stands, this feature request isn't really built out enough to meet the requirements for a feature request and hasn't picked up enough traction to remain open. See: https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests for more information.
