### ISSUE TITLE
[1.3] [bug?] Insufficient resources in Chromium

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6747]
My Meteor app is outputting these messages at a rate of about 60hz. Could be I have a rogue animation loop in the app (I'm experimenting with graphics), but I'm not using any Meteor API (let alone network APIs) at all. There's not even a single collection, and server-side code is completely non-existent at the moment.

![screen shot 2016-04-07 at 4 56 12 pm](https://cloud.githubusercontent.com/assets/297678/14370329/19597038-fce2-11e5-9735-55b892afebe9.png)

(I forgot to open the dropdown to show the trace, will do when it happens again)

**Comment by trusktr** [comment]
Before this happens (it happens after some time, not right away), I do get some DDP-related errors right from the beginning. Again, note, I'm not doing any network stuff or using any Meteor APIs at this point (well, except for `require` to load some graphical code).

![screen shot 2016-04-07 at 6 50 58 pm](https://cloud.githubusercontent.com/assets/297678/14372035/f23ffcaa-fcf1-11e5-863d-4969fa8e2538.png)

**Comment by abernix** [comment]
I think `ERR_INSUFFICIENT_RESOURCES` is when a process requests too many resources at once.  Does this happen to you in Chrome or only Chromium?  Canary?  What versions?

**Comment by trusktr** [comment]
I haven't hadthis again yet. I'll re-open if it happens again.
