### ISSUE TITLE
[1.3.1] Cannot find module c3

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#6748]
Ran `meteor npm install --save c3` and then tried importing the module like `import { c3 } from 'c3';` and saw `Cannot find module c3`.

Doing a `require('c3')` in the browser console throws the same error.

Additionally the following NPM packages don't work with a simple import either.

1) Dropzone (says not a constructor)
2) form-serializer (doesn't attach to jquery and gives an object with FormSerializer as a key)

Is this on the NPM package side?
Can anyone explain why this is happening? @benjamn

**Comment by benjamn** [comment]
The `c3` is working fine for me (on the client), though you probably want to be doing `import c3 from "c3"`.

**Comment by abernix** [comment]
Closing due to lack of additional information.
