### ISSUE TITLE
Parsing erroneous server responses in synchronous HTTP call

### ISSUE THREAD

**Issue by bomb-on** [meteor/meteor#6752]
Sorry for cross-posting [original SO post](http://stackoverflow.com/questions/36475296/parsing-erroneous-server-responses-in-meteor), but maybe I'll get the answer here much faster...

**Reproduction steps:**

1) Create a new Meteor project (reproduced with v1.2 and v1.3): `meteor create err; cd err`
2) Add HTTP package: `meteor add http`
3) Replace the content of `err.js` with this code:

```
if (Meteor.isServer) {
  Meteor.startup(function () {
    let url = 'https://api.github.com/';
    var headers = {"User-Agent": "whatevs"};

    let payload = {headers};
    try {
      var result = HTTP.get(url, payload);
      console.log(result);
    } catch (exc) {
      console.log(exc);
      return exc;
    }

    return result;
  });
}
```

4) Run the app: `meteor`

**Results:**

- In case of status code 200 OK, the `result` variable will be a proper JSON object.
- In case of 4xx/5xx errors (e.g. replace `HTTP.get(url, payload)` with `HTTP.post(url, payload)`), the `exc` variable is wrapped in Meteor's exception and results in `string` type, therefore cannot be parsed in the same way like `result`:
```
{ [Error: failed [404] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}] stack: [Getter] }
```

What is the correct way to parse errors like these? Does Meteor have some helpers or should we use regex magic or whatever else?

**Comment by abernix** [comment]
This is documented on http://docs.meteor.com/ and works as described there.

The correct place to ask for help is SO and the [Meteor Forums](http://forums.meteor.com/).
