### ISSUE TITLE
Avoid meteor restart for import/*.js files if imported from client only

### ISSUE THREAD

**Issue by aruntk** [meteor/meteor#6754]
### Expected Behavior.
When a file inside imports folder is changed meteor should restart only if the file is imported from the server. If its imported from a client side file then do a simple hot code reload just like what meteor does in the case of files inside client folder. 
### Actual Behavior.
Meteor gets restarted on file change regardless of whether its imported from client or server
### Steps to reproduce the behavior.
Add files client/main.js and imports/ui/test.js . import test.js from main.js.

**Comment by gbisheimer** [comment]
This issue is also related to #6576.

**Comment by Akryum** [comment]
I get this behavior in Meteor 1.3.2.4, despite the changelog showing the opposite.

**Comment by abernix** [comment]
Duplicate of #6576.
