### ISSUE TITLE
Pass a callback to test driver package `start` function - support "watch" mode

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#6755]
I added a watch mode to [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha) but it requires setting an environment variable.

This is because the packages itself exits the process if necessary after the tests run. https://github.com/DispatchMe/meteor-mocha/blob/master/server.js#L13-L19

I was going to propose that the Meteor tool should set an env variable based on whether `--once` was used, so packages can know. That might be a good idea anyway, but I think the best solution to the root issue here is for the Meteor tool to pass a callback to `start` function (or use a Promise).

So in Meteor it would be something like:

``` js
driverPackage.start(passed => {
    if (/* --once was used */) {
      // exit with non-zero status if there were failures
      process.exit(passed ? 0 : 2);
    }
});
```

And then in the driver packages, it would be:

``` js
function start(callback) {
  mainMocha.run((failureCount) => {
    callback(!failureCount);
  });
}
```

So driver package would not have to worry about once vs. watch mode and let Meteor handle it.

cc @tmeasday for thoughts

**Comment by tmeasday** [comment]
This makes sense to me -- although what should happen if the package doesn't define `start`? Do we just not exist the process in that case?

**Comment by aldeed** [comment]
Hmm, probably just whatever happens now I guess. In theory I guess this same approach could be applied to the client runTests function, where the callback would send the `success` value to the server, which would then run the `process.exit`. Not sure how necessary that is.

**Comment by aldeed** [comment]
Since there is no callback now, this would all be opt-in and backward compatible for the driver packages.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Pass%20a%20callback%20to%20test%20driver%20package%20%60start%60%20function%20-%20support%20%22watch%22%20mode&body=Migrated%20from:%20meteor/meteor%236755) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
