### ISSUE TITLE
No APK's Automatically Generated via Meteor Build ( 1.3.1 & 1.3.2 )

### ISSUE THREAD

**Issue by pmwisdom** [meteor/meteor#6756]
I've noticed that Meteor Build is behaving quite odd since 1.3.1, for instance, if you do a meteor reset (delete .meteor/local) right before you build, the build will succeed but it won't generate any APK's. If you run meteor, and then build, it will generate APK's.

I also noticed something else that was strange. Lets say I'm on my master branch and I run meteor, and then I switch over to my staging branch and immediately build, it will actually build the last run from my master branch, not the staging branch i'm trying to build. It seems to be building whatever was last run, not the current state of the app at that point and time.

**Comment by pmwisdom** [comment]
I'm not 100% of why this is happening still but a work around if anyone else sees this is to run build from inside the android/project/cordova/ folder of your meteor build. That will generate your APK's.

**Comment by davidwoody** [comment]
@pmwisdom We are seeing the same thing on our project... basically our build script does:

```
rm -rf .meteor/local; rm -rf ../output-build;

meteor build ../output-build --server=$SERVER --mobile-settings $SETTINGS;
```

Meteor 1.3 outputs the`android/project/build` directory, but Meteor 1.3.1 or 1.3.2 does _not_ output the `android/project/build` directory (with the APK's we're after).

**Comment by conrad-vanl** [comment]
Same here. Running the `build` script within `android/project/cordova` does generate APKs, but with filenames that don't match what we're used to seeing (things like 'debug' in the filename)

**Comment by pmwisdom** [comment]
@conrad-vanl you need to run build with the --release flag.

**Comment by oliverthomasklein** [comment]
@pmwisdom I'm also getting this issue. Right now there appears to be no build folder. I'm updated to the latest 1.3.4.4. When you say add the --release flag what release are you using that helped you work around this?

**Comment by pmwisdom** [comment]
@oliverthomasklein I was referring to the --release flag of **cordova** build, not to the **meteor** release. Meaning if you want to generate apks for app store distribution you need to provide the --release flag to the build executable in /cordova-build/platforms/android/cordova/build. If you do not, you will generate debug apks.

**Comment by ffflorian** [comment]
Same problem here, running Meteor 1.4.0.1.

**Comment by jimmy1993k** [comment]
Same problem on 1.3.5.1, you can get the APK's when you run the cordova build command yourself as in when you have build to some build folder: 
`<build-folder>/android/project/cordova/build --release`

**Comment by oliverthomasklein** [comment]
Hello, I got around this issue by adding a line in my build script that manually copies over the build directory from `cordova-build`. There is a bug where Meteor isn't copying it over but you can also do it yourself.

`cp -a .meteor/local/cordova-build/platforms/android/build "$OUTPUT_PATH/android/project"`

Running the `cordova build` command would also do it.

I assumed this would have been fixed in later releases but if you are still having this issue give that a go.

**Comment by openqubit** [comment]
For newer version of meteor  > 1.4.x this is the 
apk path `~/finalapp/.meteor/local/cordova-build/platforms/android/build/outputs/apk$`

I run this command 

`meteor build ~/apk --server=finalapp.herokuapp.com`

the apk is the folder i had created to store the output apks. Didn't happen and the apk generated is to be found at the root of the meteor app.The app is called finalapp.
