### ISSUE TITLE
[1.3] Should warn/fail on using `import` in `meteor shell`

### ISSUE THREAD

**Issue by gadicc** [meteor/meteor#6764]
This seems to be coming up almost every day on the forums... maybe one day people will search first, but OTOH, it is a little counter-intuitive that the statement "works" (without error) but "doesn't work" (in result).  We should assume that most users won't understand the different between a full app compile vs REPL.

@benjamn

e.g.

* https://github.com/meteor/guide/issues/312#issuecomment-207054402 (your comment)
* https://forums.meteor.com/t/silly-noob-import-export-question/21040 (2016-04-09)
* https://forums.meteor.com/t/1-3-1-strange-import-behavior/20940/5 (2016-04-07)
* https://forums.meteor.com/t/how-to-import-npm-in-meteor-1-3/17901 (2016-04-07)
* Probably others I missed and from earlier.

I could do a PR towards end of next week, don't think I'll have a chance before then.

**Comment by benjamn** [comment]
Warning is a great idea!

**Comment by gadicc** [comment]
Solved with [reify](https://github.com/benjamn/reify) in Meteor 1.3.3; no warning necessary :D
