### ISSUE TITLE
Explain universal publication in docs

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6768]
## common questions

1. Why is `Meteor.user()` undefined? (see for example https://github.com/meteor/meteor/issues/6745#issuecomment-207064712)
2. How do I publish different data about a user?

## current docs

![image](https://cloud.githubusercontent.com/assets/251288/14406286/9eae0f24-fe71-11e5-9762-9813742842c5.png)

![image](https://cloud.githubusercontent.com/assets/251288/14406267/0a5e4eec-fe71-11e5-92b8-5a5414fe2c33.png)

## suggested additions

- Say what the universal/null publication contains by default (otherwise someone could overwrite it with non-user data and wonder why `Meteor.user()` stays undefined)
- Give an example on how to redefine it (and could subsume the `userData` publish example in 
http://docs.meteor.com/#/full/meteor_user ? or recommend people don't redefine it)

`Meteor.user()`
> Get the current user record, or null if no user is logged in. A reactive data source.

- Add "or `undefined` if the universal publication[linked to description] isn't ready". 
- Since there's no way to check whether the universal publication is ready, add "do `Tracker.autorun -> Meteor.user()`" to react to the user data being published. 
- Say "use `Meteor.userId()` instead if you want to determine whether a user is logged in". (And perhaps put `Meteor.userId()` before `Meteor.user()` in docs)

**Comment by abernix** [comment]
Issue moved to [meteor/docs #62](https://github.com/meteor/docs/issues/62) via [**ZenHub**](https://www.zenhub.com/)
