### ISSUE TITLE
Case sensitivity when importing, weird behaviour

### ISSUE THREAD

**Issue by dufia** [meteor/meteor#6770]
So, when I import

````
//server side
import classNames  from 'classNames' //camelcase works fine
import classNames  from 'classnames' //lowercase works fine

//client side
import classNames  from 'classNames' //camelcase works fine
import classNames  from 'classnames' //lowercase Cannot find module 'classnames'

````

I found out about it when I tried to upgrade from 1.3-rc.4. 

I managed to discover that it breaks my app since 1.3-rc.6 or 1.3-rc.5 (It doesnt install for me). One of my dependencies used lowercase `var cs = require('classnames');`

**Comment by dufia** [comment]
ant comments?

**Comment by abernix** [comment]
@dufia Could you provide a more complete example?  What is `classNames`/`classnames`? A file? [The `classnames` npm package](https://www.npmjs.com/package/classnames)?  A custom module?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
