### ISSUE TITLE
Meteor 1.3+ Cordova: Ability to Import 'App' variable into mobile-config.js

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#6774]
`mobile-config.js`, per the [Meteor Docs](http://docs.meteor.com/#/full/mobileconfigjs), uses an `App` variable to configure Cordova.

`App` should be importable at the top of this file to

1) match the new javascript import/export syntax
2) pass `ESLint` code style checks, which is another Meteor Guide recommended standard

Where is `App` imported from?

**Comment by joncursi** [comment]
Bump.

**Comment by martijnwalraven** [comment]
`mobile-config.js` is executed in a special way (see [here](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L207-L210)), which doesn't work with ES2015 modules. So being able to import `App` would require some fundamental changes to how this works and frankly doesn't seem worth it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%201.3%2B%20Cordova%3A%20Ability%20to%20Import%20'App'%20variable%20into%20mobile-config.js&body=Migrated%20from:%20meteor/meteor%236774) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
