### ISSUE TITLE
Meteor.user() behavior on server

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6775]
http://docs.meteor.com/#/full/meteor_user

People are used to `Meteor.userId()` returning immediately on client and server and `Meteor.user()` returning immediately on client. It may not occur to them that on the server, `Meteor.user()` waits on a round-trip to the DB. 

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L52

Currently, if you want to reduce method latency, you save and re-use the user doc, passing it around:

```javascript
const user = Meteor.user()
if (user.bool)
  foo()

...

if (Roles.userIsInRole(user, 'admin'))
  bar(user)
```

I propose doing one of the following:

1. Change `Meteor.user()` to return a cached value if repeatedly called from a method, with an optional arg `{ignoreCache: true}`. Perhaps the cached doc can even get autoupdated from the oplog. 
2. Note the DB round-trip in the docs, and tell people to save the value if they don't need it to be precisely up-to-date.

The first has the benefit that the developer doesn't need to worry about storing and passing around the user doc, which can be a pain, especially when the functions that need the user doc are many levels deep, or inside packages.

**Comment by helfer** [comment]
I'm leaning towards option 2, because it's a much easier change to make, and it gives those developers who care the knowledge necessary to optimize their code, while everyone who doesn't care can just keep calling `Meteor.user()` as always.

@lorensr Would you be willing to make a PR to the docs for this? If you do, you can mention me and I'll make sure it gets merged.

**Comment by mitar** [comment]
I also think that 2 is better.

Also, I think that it would be much better if in all examples and guide both on the client and server code we would use `Meteor.userId()` when testing only if user is logged in.

Moreover, I think those extensions should go into the core: https://github.com/peerlibrary/meteor-user-extra

Especially that you can limit fields in which you are interested in (reactivity!).

**Comment by lorensr** [comment]
I agree, moved to #7002 😊

**Comment by lorensr** [comment]
Fixed by https://github.com/meteor/docs/commit/db1a565763548ba6084553d8098ea088448f35fd
