### ISSUE TITLE
Accounts.logoutOtherClients() logs out all clients

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#6777]
Meteor 1.3.1

The following code doesn't work as expected:
```
if (Meteor.isClient) {
  Accounts.onLogin(function() {
    console.log(Meteor.loggingIn()); // false.  See https://github.com/meteor/meteor/issues/1616
    Accounts.logoutOtherClients();
  });
}
```

Here's the test case:

FF 1 tab.  Chrome 2 tabs.
1) Login to 1 chrome tab.
ERROR: it logs in the 2nd chrome tab as well
2) Login to Firefox
OK: Logs out Chrome
3) Login to 1 chrome tab
ERROR: logs into other Chrome tab.  Logs out Firefox.  Then logs out both Chrome tabs.

What's the use case for this function, if not for keeping only one tab logged in?  Thanks!

See also: https://forums.meteor.com/t/make-sure-user-is-logged-into-only-one-tab/21156

**Comment by abernix** [comment]
This is working as intended.

HTTP is a stateless protocol and requires some way to keep track of users from server to client.  This is generally resolved with Cookies (which are sent to the server on each request) or by storing the session ID in the browser URL.  A "client" (as in `logoutOtherClients`) is an implementation which has only one Cookies/LocalStorage per domain, per profile.

You will find this behaviour with most all websites – if you log in on one tab, all your tabs will become that same user.  You can't log into Facebook on one tab and not be logged into on another (unless it's a completely new profile – like incognito/private browsing).

A use case for `logoutOtherClients` is when you may have inadvertently left yourself logged in on other computers and need to log yourself out (as found in Gmail, Facebook, etc.).

If you want to work around it, you will need to build your own login implementation that uses `sessionStorage` which is not persisted outside of the current DOM.  You could probably also find a way to use the `connectionId` on the client (available as `Meteor.connection._lastSessionId`) to inactivate the non-active interface with a warning.

**Comment by pawansingh-snapwiz** [comment]
User logs into Tab1 and automatically gets logged into Tab2, which is OK, but then suddenly he gets logged out of both tabs.
Isn't this still a BUG?

Sample Code --

`        // Tracker.autorun(function () {
        //   if (Meteor.loggingIn()){
        //     return;
        //   } 
        //   Meteor.logoutOtherClients(function (err) {
        //     if (err) {
        //       console.log(" Error :: ", err);
        //       return;
        //     }
        //   });
        // })`

**Comment by afrokick** [comment]
@pawansingh-snapwiz it is ok, because there is 'shared' `Meteor_token` variable in LocalStorage. So, if you logged out, it just cleared.

**Comment by pawansingh-snapwiz** [comment]
@afrokick Any suggestions how can I solve it? What I want to achieve is 

1. Across Multiple browsers there can be only one Session at a time, which seems to be working with above code.
2. Within a browser user should be able to open multiple tabs, which is not working with above code (As soon as user opens an another tab he will be logged out from both the tabs).
 
**Browser Fingerprinting** is one technique that I can use, any other suggestions.

Thanks in advance.
