### ISSUE TITLE
registry.npmjs.org contacted by meteor build when specifying NPM_CONFIG_REGISTRY

### ISSUE THREAD

**Issue by tmds** [meteor/meteor#6779]
For my project, I want to use a local npm repository.
For standard npm, this can be done by setting NPM_CONFIG_REGISTRY to specify a local server.
When meteor restores npm packages it still tries to use registry.npmjs.org (see meteor-npm.js). When I disable access to registry.npmjs.org, I get an error message:
`"error: Can't install npm dependencies. Are you connected to the internet?"`

**Comment by sebakerckhof** [comment]
@stubailo I also have this issue, where we want our builds to be able to build without any dependency on a third-party service. For this we run our own NPM and Atmosphere (Stratosphere) server which caches all the depending packages in case any of these services would be offline.

Could we just use `NPM_CONFIG_REGISTRY` envar here: https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/tools/isobuild/meteor-npm.js#L670 and here: https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/tools/isobuild/meteor-npm.js#L698 ?

**Comment by laosb** [comment]
That's also important for China developers, most of which use a npm registry mirror.

**Comment by laosb** [comment]
I think modifying the first one is enough for this change?
