### ISSUE TITLE
Meteor.publish does not set "this" when using es6 function shorthand

### ISSUE THREAD

**Issue by cellog** [meteor/meteor#6780]
Meteor.publish('moreConcerts', function(limit) {
  if (this.userId && authorizedUser(this.userId)) {
...
}

works, if a user is logged in.  this.userId is properly set.

Meteor.publish('moreConcerts',(limit) => {
  if (this.userId && authorizedUser(this.userId)) {

does not work.  "this" is not set to the correct value (it is set to the global object)

**Comment by laosb** [comment]
Yes, it doesn't work. To use `this`, you can't use arrow functions. I remember that someone from MDG  said they're going to have an API suits ES6.

**Comment by cellog** [comment]
so is this a documentation problem then?

On Mon, Apr 11, 2016 at 4:46 AM, Wexpo Lyu <notifications@github.com> wrote:
Yes, it doesn't work. To use this , you can't use arrow functions. I remember that someone from MDG said they're going to have an API suits ES6.

**Comment by ephemer** [comment]
@cellog This is a 'limitation', or rather expected behaviour of ES6/ES2015. Within an arrow function, `this` (and `arguments`, from memory) will always be that of the containing scope. In this case, the outer scope is the global scope, which is what you're seeing.

As far as I could see the docs use standard functions, not arrow functions, which is correct for this use-case.

**Comment by cellog** [comment]
OK. The docs strongly recommend using eslint, which raises an error for any function that doesn’t use shorthand. This breaks every single meteor method, publish function, and so on. So either the docs are broken or Meteor is, yes?

On Mon, Apr 11, 2016 at 9:36 AM, Geordie <notifications@github.com> wrote:
@cellog [https://github.com/cellog] This is a 'limitation', or rather expected behaviour of ES6/ES2015. Within an arrow function, this (and arguments , from memory) will always be that of the containing scope. In this case, the outer scope is the global scope, which is what you're seeing.

As far as I could see the docs use standard functions, not arrow functions, which is correct for this use-case.

**Comment by Zodiase** [comment]
You know you can configure ESLint so it doesn't act silly on its own, right?

Maintaining current context (while not creating its own) is one of the features of arrow function in ES6. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this

To compensate this feature, `.publish` functions **can't** be arrow functions if you want to use `this`.

I don't think either the docs or Meteor is broken.

**Comment by cellog** [comment]
If you follow the recommendations of the docs, it has you use an eslint setting that converts all functions to arrow notation.

Say what you like, but meteor 1.0 was significantly easier to start because the docs did not recommend settings that would break things.

All that is needed is a note and link to the docs you just linked to. It is similar to the jsx gotchas section of react docs. They are not too proud to say things that seem obvious, and it makes the platform more popular.

/end rant


On Mon, Apr 11, 2016 at 12:04 PM, Xingchen Hong < notifications@github.com [notifications@github.com] > wrote:
You know you can configure ESLint so it doesn't act silly on its own, right?

Maintaining current context (while not creating its own) is one of the features of arrow function in ES6. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this]

To compensate this feature, .publish functions can't be arrow functions if you want to use this .

I don't think either the docs or Meteor is broken.

**Comment by Zodiase** [comment]
@cellog I just found this: http://guide.meteor.com/data-loading.html#publications
So they did mention this sort of things in the guide. Where do you think is missing this info?

**Comment by cellog** [comment]
Hi,
In the docs.meteor.com for Meteor.method and Meteor.publish, it needs to be mentioned there. Also, in Migrating to 1.3 in the Meteor guide, this gotcha could be mentioned there as well, since es2015 is the new kid on the block.
In general, the switch to modules is quite time consuming, but I love it. It’s just a matter of time before my code works faster and better than it did with the app I am porting from Meteor/Blaze 1.0 (http://csq.events, if you’re bored and want to see what I am working with)
Thank you!

On Mon, Apr 11, 2016 at 3:01 PM, Xingchen Hong <notifications@github.com> wrote:
@cellog [https://github.com/cellog] I just found this: http://guide.meteor.com/data-loading.html#publications [http://guide.meteor.com/data-loading.html#publications]
So they did mention this sort of things in the guide. Where do you think is missing this info?

**Comment by jimmiebtlr** [comment]
Is there a mdg recommended eslint file?  That would probably avoid issues like this, and help converge on a style for the community.  As far as I know the airbnb preset is the only recommendation at the moment.

**Comment by stubailo** [comment]
You'll just need to ignore the linter for publications for now. Hopefully soon we'll improve the publication API: #6649 

I'd be happy to accept a PR for any part of the guide or docs which would make the current situation clearer.
