### ISSUE TITLE
`Assets` is not importable

### ISSUE THREAD

**Issue by cellog** [meteor/meteor#6784]
I need to use the Assets class in an app, but the docs do not say from whence to import it, and importing from meteor/meteor does not work.

**Comment by abernix** [comment]
`Assets` (and actually `Npm`, too) cannot be imported from anywhere right now – it is simply in the global namespace so you can just use it.

**Comment by cellog** [comment]
So... Perhaps this could be documented.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.28&pv=5.1.1&source=email_footer_2] On Mon, May 23, 2016 at 1:46 AM, Jesse Rosenberger < notifications@github.com [notifications@github.com] > wrote:
Assets (and actually Npm , too) cannot be imported from anywhere right now – it is simply in the global namespace so you can just use it.

**Comment by abernix** [comment]
I opened the issue in the docs repo already.  (Shown above in the issue, but looks like you're on your e-mail so you probably didn't see.)

**Comment by abernix** [comment]
@cellog Docs have been updated with meteor/docs#28 with a note about this: http://docs.meteor.com/api/assets.html

Leaving this issue open until it's properly exported from the API through.  Thanks again for submitting an issue for this.

**Comment by abernix** [comment]
Semi-Related to #3343

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60Assets%60%20is%20not%20importable&body=Migrated%20from:%20meteor/meteor%236784) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
