### ISSUE TITLE
Hot Code Push not working for ios app running 1.3.1

### ISSUE THREAD

**Issue by chip** [meteor/meteor#6789]
I'm not seeing Hot Code Push/Reload working on my apps running on Digital Ocean with Ubuntu 14.04.3 LTS. The apps run under 2 different domains, 1 for production and another for staging and are deployed using `mupx`, which uses a Docker container, so I'm not sure if that matters.

**.meteor/release**:
```
METEOR@1.3.1
```

**.meteor/platforms**:
```
browser
ios
server
```

**.meteor/versions**:
```
accounts-base@1.2.5
accounts-password@1.1.7
alanning:roles@1.2.15
aldeed:collection2@2.9.1
aldeed:collection2-core@1.1.1
aldeed:geocoder@0.3.8
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.3
audit-argument-checks@1.0.6
autoupdate@1.2.7
babel-compiler@6.6.1
babel-runtime@0.1.7
base64@1.0.7
binary-heap@1.0.7
blaze@2.1.6
blaze-tools@1.0.7
boilerplate-generator@1.0.7
browser-policy@1.0.8
browser-policy-common@1.0.8
browser-policy-content@1.0.9
browser-policy-framing@1.0.9
caching-compiler@1.0.3
caching-html-compiler@1.0.5
callback-hook@1.0.7
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:graphicsmagick@0.0.18
cfs:gridfs@0.0.33
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:ui@0.1.3
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.1.3
chuangbo:cookie@1.1.0
coffeescript@1.0.16
cosmos:browserify@0.10.0
dburles:google-maps@1.1.5
ddp@1.2.4
ddp-client@1.2.4
ddp-common@1.2.4
ddp-rate-limiter@1.0.3
ddp-server@1.2.5
deps@1.0.11
diff-sequence@1.0.4
digilord:faker@1.0.7
ecmascript@0.4.2
ecmascript-runtime@0.2.9
ejson@1.0.10
email@1.0.11
fastclick@1.0.10
fortawesome:fontawesome@4.5.0
fourseven:scss@3.4.1
geojson-utils@1.0.7
harrison:papa-parse@1.1.1
hot-code-push@1.0.3
html-tools@1.0.8
htmljs@1.0.8
http@1.1.4
id-map@1.0.6
jquery@1.11.7
jsx@0.2.4
kadira:blaze-layout@2.3.0
kadira:debug@3.2.2
kadira:flow-router@2.11.0
kadira:react-layout@1.5.3
kadira:runtime-dev@0.0.1
less@2.5.7
livedata@1.0.17
localstorage@1.0.8
logging@1.0.11
mdg:camera@1.4.1
mdg:geolocation@1.3.0
mdg:reload-on-resume@1.0.4
mdg:validation-error@0.5.1
meteor@1.1.13
meteor-base@1.0.3
meteorhacks:fast-render@2.13.0
meteorhacks:inject-data@2.0.0
meteorhacks:kadira@2.23.6
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
meteorhacks:ssr@2.2.0
mikowals:batch-insert@1.1.13
minifier-css@1.1.10
minifier-js@1.1.10
minimongo@1.0.13
mobile-status-bar@1.0.11
modules@0.5.2
modules-runtime@0.6.2
momentjs:moment@2.12.0
mongo@1.1.6
mongo-id@1.0.3
mongo-livedata@1.0.11
npm-bcrypt@0.7.8_2
npm-container@1.2.0
npm-mongo@1.4.42
observe-sequence@1.0.10
ordered-dict@1.0.6
pcjpcj2:ratchet@2.0.2
pfafman:filesaver@0.2.3
promise@0.6.6
raix:eventemitter@0.1.3
random@1.0.8
rate-limit@1.0.3
react@0.14.3
react-meteor-data@0.2.8
react-runtime@0.14.3
react-runtime-dev@0.14.3
react-runtime-prod@0.14.3
reactive-dict@1.1.6
reactive-var@1.0.8
reload@1.1.7
retry@1.0.6
routepolicy@1.0.9
service-configuration@1.0.8
session@1.1.4
sha@1.0.6
spacebars@1.0.10
spacebars-compiler@1.0.10
srp@1.0.7
standard-minifier-css@1.0.5
standard-minifier-js@1.0.5
stevezhu:lodash@4.6.1
templating@1.1.8
templating-tools@1.0.3
themeteorchef:bert@2.1.0
themeteorchef:jquery-validation@1.14.0
tmeasday:check-npm-versions@0.2.0
tracker@1.0.12
twbs:bootstrap@3.3.6
ui@1.0.10
underscore@1.0.7
url@1.0.8
webapp@1.2.7
webapp-hashing@1.0.8
```

Using `reload-on-resume` did work on a previous version, among which were the following:
```
METEOR@1.3
METEOR@1.3-rc.12
METEOR@1.3-cordova-beta.5
METEOR@1.2.1
```

**Unfortunately, I cannot remember at which point this started failing.**

**reload-on-resume**
Additionally, I do see that refreshing the app on the device appears to trigger an app reload, but it doesn't show the most recent version of code. I also no longer see the `reload-on-resume` message that I had displaying in previous versions.

**appId**
I have logged into my server on Digital Ocean and noticed that the apps deployed for both staging and production have the same **appId** from `current/bundle/programs/server/config.json`.

**build commands**
To build the production app for Xcode, I do the following (real domain is replaced with example.org):
```
rm -rf .meteor/local/cordova-build
meteor build ../example.org --directory --mobile-settings .environments/production/settings.json --server http://example.org
```

For staging, I do something similar, but the domain name is different and settings.json is in a separate location.

**Making small revisions**
When I need to make a small change, I am not creating new builds each time, as I was hoping that deploying with `mupx` would allow me to take advantage of Hot Code Push. I am bumping the version in `mobile-settings.json` and `package.json` upon each revision, although I'm not sure if that matters.

Please let me know how to better troubleshoot this issue. 

Thanks so much on your recent Meteor updates. Your hard work is greatly appreciated!

**Comment by chip** [comment]
As a side note, I have seen this behavior in both AppStore apps and TestFlight apps.

**Comment by chip** [comment]
Per https://github.com/meteor/meteor/blob/devel/packages/autoupdate/autoupdate_cordova.js#L4, I see there is a collection created that saves `version-cordova`. However, I do not see this collection when using `mongo` on Digital Ocean. I wouldn't think that I should need to create this collection manually, but thought it was worth noting here.

**Comment by martijnwalraven** [comment]
Can you check if `http://example.org/__cordova/manifest.json` actually serves the manifest? I suspect the server may not be serving the Cordova bundle that is needed for hot code push.

Are you removing the mobile platforms before deploying by any chance? Because that would also remove the Cordova bundle from the server bundle.

**Comment by chip** [comment]
Thanks @martijnwalraven for your suggestions.

I did a `find . -name manifest.json` from `/opt` on the server as well as within my local project directory and received no results, so that could be the culprit. I also did the same from within the ios build directories locally without finding that file.

How do I produce this file and verify that it is being served?

Also, I'm not removing the `ios` platform before deploying.

**Comment by chip** [comment]
Also, I did not find a `__cordova` directory on the server, either.

**Comment by martijnwalraven** [comment]
Could you use a browser to check if `http://example.org/__cordova/manifest.json` is served? It should serve a JSON file, and not the index file.

There is not supposed to be a  `__cordova` directory, but the contents of the Cordova bundle (`web.cordova`) are served under `__cordova`. `manifest.json` is not stored as is either, but is based on `program.json` from the same bundle.

**Comment by chip** [comment]
Thanks for further details. I checked and both domains serve a `manifest.json`. Here's a small snapshot, but let me know if you need further details.
![manifest](https://cloud.githubusercontent.com/assets/31725/14465040/026f40ba-0097-11e6-97dd-b899dbc4ac7a.png)

**Comment by chip** [comment]
As an update, if I launch the app locally using `meteor run ios-device --mobile-server=http://example.org --settings .environments/production/settings.json --verbose`, the `reload-on-resume` message does appear upon initial load. However, I have not seen it show up after that when making updates locally.

The AppStore version also shows a white screen occasionally. I recently added a react button component and deployed that committed change to the production server, at which point it briefly showed up, only to disappear later.

I am using the Safari debugger to troubleshoot it locally on the device, but cannot reproduce it on that version, only the AppStore version.

**Comment by chip** [comment]
When running the `ios-device` command locally, Xcode launches with my original version and build number, not the ones that are listed in `mobile-config.js` or `package.json`. Is there a way to get it to fetch the current version?

**Comment by chip** [comment]
I just launched the directory containing the bundle I uploaded to the AppStore and see this in the log regarding the `manifest.json` (see last 3 lines):

```
2016-04-12 14:05:48.733 Bin Tracker[1182:337359] Apache Cordova native platform version 4.1.0 is starting.
2016-04-12 14:05:48.735 Bin Tracker[1182:337359] Multi-tasking -> Device: YES, App: YES
2016-04-12 14:05:48.878 Bin Tracker[1182:337359] Using WKWebView
2016-04-12 14:05:48.880 Bin Tracker[1182:337359] [CDVTimer][handleopenurl] 0.290036ms
2016-04-12 14:05:48.886 Bin Tracker[1182:337359] [CDVTimer][intentandnavigationfilter] 4.741013ms
2016-04-12 14:05:48.887 Bin Tracker[1182:337359] [CDVTimer][gesturehandler] 0.167012ms
2016-04-12 14:05:48.916 Bin Tracker[1182:337359] [CDVTimer][statusbar] 27.043998ms
2016-04-12 14:05:48.990 Bin Tracker[1182:337359] Serving asset bundle version: 9f1cc0e8ab861222f43d0aa33a18c1b8bee29e6d
[INFO] GCDWebServer started on port 12000 and reachable at http://localhost:12000/
2016-04-12 14:05:48.994 Bin Tracker[1182:337359] [CDVTimer][webapplocalserver] 76.729000ms
2016-04-12 14:05:48.995 Bin Tracker[1182:337359] [CDVTimer][localstorage] 0.953019ms
2016-04-12 14:05:48.995 Bin Tracker[1182:337359] [CDVTimer][TotalPluginStartup] 115.157008ms
2016-04-12 14:05:50.822 Bin Tracker[1182:337359] Start downloading asset manifest from: manifest.json -- http://tracker-app.impactinnovates.com/__cordova/
2016-04-12 14:05:50.966 Bin Tracker[1182:337455] Downloaded asset manifest for version: feaaa9215bc5ab233525eb8fb841dd899f38b12c
2016-04-12 14:05:50.967 Bin Tracker[1182:337455] Download failure: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible
```

**Comment by martijnwalraven** [comment]
Ah, that explains it! Have you indeed made changes to your set of Cordova plugins? That requires a new version of the app to be submitted to the store before hot code push will be able to work again.

**Comment by chip** [comment]
According to my repo history, I haven't updated `.meteor/cordova-plugins` in 21 days, which was well before I submitted my first app. I now have a second app that I have submitted, but it has not yet been reviewed. Here's what I have in that file:

```
cordova-plugin-statusbar@2.1.2
phonegap-plugin-barcodescanner@4.1.0
```

Is there somewhere else I should check perhaps or any other possible causes?

**Comment by martijnwalraven** [comment]
There have been some updates to built-in Cordova plugins for Meteor 1.3.1, so that is probably the cause.

**Comment by chip** [comment]
I hope so. I'll leave this open until Apple reviews that most recent app so I can verify it's working again. Thanks for your help @martijnwalraven! You're doing a fantastic job with Meteor.

**Comment by wojtkowiak** [comment]
I have similar issue with 1.3.1.

Steps to reproduce:
```
meteor create test
cd test
meteor add-platform android
meteor run
````
on `127.0.0.1:3000/__cordova/manifest.json` I just get normal app as I would get getting `127.0.0.1:3000`, no json being served.
`meteor run --mobile-server=127.0.0.1:3000` does not help.
After building android app I get `Error: Error parsing manifest`
Tried on: Xubuntu 14.04 64bit, Windows 10 64bit, OSX El Capitan.

**Comment by martijnwalraven** [comment]
@wojtkowiak: `meteor run` will not serve the Cordova bundle unless you add a mobile target (e.g. `meteor run android-device`). See https://github.com/meteor/meteor/issues/6417 for the reasoning behind this change in Meteor 1.3.

**Comment by wojtkowiak** [comment]
Ok, it seems I have missed some changes.
So sorry if this has already been answered but I need to make it clear for myself - so `meteor run --mobile-server=192.168.1.1:3000` also does not serves manifests for cordova?
If yes than how actually I can run a meteor server that will HCP new versions for android & ios without issuing `run android/ios`?
Currently my dev server was just running `meteor run --production --mobile-server=192.168.1.1:3000`. Should I run from a build instead to have manifest available?

**Comment by martijnwalraven** [comment]
Yes, `meteor run` without `android`/`ios` will not serve the Cordova bundle. So you'll have to run from a build to serve it.

**Comment by wojtkowiak** [comment]
Ok, thanks for clarifying :smile: 
I would however argue a little bit and say that it should build web.cordova when run with `--mobile-server` which clearly indicates I want to use this as server for mobile builds :wink: 
At least a notification saying that HCP won't work would be helpful.

**Comment by wojtkowiak** [comment]
Hmm I am trying to restore my development flow for few hours now and my experience is not as good as it was before.
Normally I had windows with a virtual Xubuntu on which I have run meteor. On that machine I did not even have android sdk. It was just running `meteor run --mobile-server=...`. 
My IDE was just sending changes to that virtual machine, meteor was noticing file change and rebuilding. My iOS and Android builds were just updated through HCP from that virtual Xubuntu runing meteor.
If I understand it properly if I want to retain this setup I would have to build the project on that virtual machine every time I want to update my mobile clients.
I am kinda feeling that I've lost the flexibility.
Maybe we should add a switch like --enable-hcp or at least build web.cordova when `--mobile-server` is provided. I can do a PR if you agree on one of the options.

**Comment by skirunman** [comment]
Agreed, it would be better if we build web.cordova when --mobile-server is provided, unless this creates some other unknown side effect. 

Also, I'd suggested to @martijnwalraven that we try not to update plugins bundled with Meteor by default between minor versions as this creates a "breaking change" for any deployed mobile apps. See [discussion](https://forums.meteor.com/t/cordova-app-android-not-reloading-after-hot-code-push-with-deployed-app/16336/23).

**Comment by chip** [comment]
After getting my app approved in the AppStore, this issue still persists. Possibly related to #6847.

**Comment by chip** [comment]
I submitted an app yesterday which was surprisingly accepted this morning and have confirmed that HCP now works!  I think my recent findings from #6847 did the trick.

@martijnwalraven - THANK YOU SO MUCH for your guidance throughout this process! 👍

**Comment by wojtkowiak** [comment]
@martijnwalraven Can I open another issue about the `--mobile-server` related changes?

**Comment by martijnwalraven** [comment]
@wojtkowiak: Sure! Separate issues make it easier to keep track.

**Comment by iwoj** [comment]
See #7760
