### ISSUE TITLE
Scan node_modules for packages that can be treated as local Meteor packages

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6791]
Publishing Meteor packages to npm seems fairly straightforward if we treat `node_modules` directories as similar to `packages` directories, and consider any package with a `package.js` file to be a Meteor package.

This would mean Meteor packages could be hosted by npm, and could also be installed with `npm install` or `meteor npm install`.

The main complexity I can see is that, when importing from such packages, we could use either the npm package name or the `meteor/name` currently used to refer to Meteor packages. It might be possible to support both styles, though!

**Comment by jiku** [comment]
Great idea. If NPM doesn't suddenly begin collecting module 'stack variants' (npm-module, react-npm-module, angular-npm-module, meteor-npm-module to npm-module with variant specified in packages.json metadata or on import) and most modules having Meteor-specific functionality are published as `meteor-npm-module` it makes sense to drop the `meteor/` prefix I think. But might be good to have the option.

Would you want to keep ´package.js´ or transition to something like ´meteor.js´?

**Comment by benjamn** [comment]
I'm thinking the `package.json` file could have a `meteor` section that (among other uses) optionally specifies the name of the control file, e.g.
```js
{
  "name": "user:name",
  "main": "server.js",
  "browser": "client.js",
  "meteor": {
    "control-file": "package.js",
    ...
  }
}
```

**Comment by jiku** [comment]
Yeah that would be even better.

**Comment by laosb** [comment]
Looks good. But what if there comes a normal npm package with a `package.js` in it? And, what if a non-Meteor user use this package by mistake?

**Comment by jiku** [comment]
@laosb hopefully that won't happen. Enforcing use of `meteor.control-file` in `packages.json`, people have to point to a specific file. Even then, or if someone points to the wrong file in `packages.json`, Meteor would still execute it structurally. Not just eager-load the whole file, self-executing functions and all.

**Comment by talha-asad** [comment]
@benjamn I like the idea of putting in a `meteor` section in package.json, instead of using package.js file.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Scan%20node_modules%20for%20packages%20that%20can%20be%20treated%20as%20local%20Meteor%20packages&body=Migrated%20from:%20meteor/meteor%236791) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
