### ISSUE TITLE
Erratic Behavior Under Load Balancer & SSL

### ISSUE THREAD

**Issue by nishikawa7863** [meteor/meteor#6792]
We're having issues with Meteor running behind a Load Balancer with SSL (301 Redirect Enabled). 
Behavior is very strange essentially it won't send Method Calls to the server and when it does it send corrupt data. For example when sending an integer on client, server will receive a random string.
Subscriptions sometimes never reach client. No errors anywhere, so very hard to track.

My First guess was the load balancer was directing request randomly but after setting up persistent sessions the issue continues.

Disabling SSL solves the issue.

Any idea why this might be happening? Everything is running on Rackspace if it helps.

Is there any specific requirements for running SSL & Load Balancing? 
I don't have this issues with any other app. Node, PHP & Ruby Apps have worked under this setup before.

**Comment by abernix** [comment]
This setup works fine.  You will find help by asking your question on http://forums.meteor.com.
