### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by delicacy1** [meteor/meteor#6801]
Auto close tab is unfunctional in firefox & my "pale moon"

it'd be nice to update the addon & add this:

Auto Close tabs based on a list of (html content) keywords for specific domains,

**Comment by stubailo** [comment]
I think this might be the wrong repo!

**Comment by delicacy1** [comment]
your addon auto-close is outdated & you dont have a github page for it nor
give a crap to respond, so yes, it's the wrong place to report anything,
even if u were in front of me.
as i dont have time for vanity & trollism.

**Comment by stubailo** [comment]
what's auto-close?

**Comment by delicacy1** [comment]
https://addons.mozilla.org/en-US/firefox/addon/auto-close-tab/
by Misha Verplack.

https://github.com/mishavee

i thought meteor belonged to him, but apparently not, he just contributed
in meteor.

this topic can be closed.
