### ISSUE TITLE
Improve notice: "Unable to resolve some modules"

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6802]
```
Unable to resolve some modules:

  "jquery" in /Users/me/parlay/node_modules/magnific-popup/dist/jquery.magnific-popup.js (web.browser)
  "dist/index.js" in /Users/me/parlay/node_modules/waves/package.json (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save jquery dist  
```

I npm-added `magnific-popup` and `waves`. I don't recognize `dist/index.js`. 

My questions, some of which can be avoided by changing / adding to the printout:
- What is "resolve"? Conflicting version requirements? Cannot find in `node_modules`? Are they dependencies? Why aren't dependencies automatically installed?
- Module could also mean something I exported from another one of my own files. In this case, we're talking about npm packages, so perhaps "Unable to resolve some _npm packages_" would be clearer?
- I can guess from the filename that `dist` is required by `waves`, but that may not occur to everyone. Perhaps change to: `"dist" package is required[/used] by "waves" in /Users/...`
- I ran `meteor npm install --save dist`, but it's still listed in the `Unable to resolve` notice
- My `.meteor/packages` has `jquery`. But when I load the client, I get an error about missing jquery, so I guess it's not loaded in time for npm packages to use? Perhaps print a recommendation telling people to use npm instead of atmosphere for jquery?
- If running with unresolved modules is a valid state (as "consider running" implies), how do I suppress this notice, so that I don't see it every time I start meteor?

```
    "magnific-popup": {
      "version": "1.1.0",
      "from": "magnific-popup@>=1.0.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/magnific-popup/-/magnific-popup-1.1.0.tgz"
    },
    "waves": {
      "version": "0.1.1",
      "from": "waves@<1.0.0",
      "resolved": "https://registry.npmjs.org/waves/-/waves-0.1.1.tgz"
    }
```

**Comment by scharf** [comment]
I see the same problem with fibres:

```
  "fibers/future" in /Users/scharf/.../server/UsingFibers.js (os.osx.x86_64)
If you notice problems related to these missing modules, consider running:

  meteor npm install --save fibers
```

It seems that this module is resolved correctly by meteor. Wouldn't installing another version using npm potentially causing problems? 

When I use `Npm.require('fibers/future')` the problem goes away, but I thought this is deprecated. It would be nice to have an official way to import those meteor related modules.

**Comment by lorensr** [comment]
Also, when you clone a new repository and forget to `npm install`, it gives a similar error. It would be nice if it realized that it's in your `package.json` and tell you to run `npm install`. Related: #6848

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Improve%20notice%3A%20%22Unable%20to%20resolve%20some%20modules%22&body=Migrated%20from:%20meteor/meteor%236802) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
