### ISSUE TITLE
Chrome blackboxing broken

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6803]
I use a logging helper function (in `helpers.coffee`), and use chrome blackboxing to show the file that calls the helper instead of every line showing `helpers.coffee`. After moving to 1.3, this no longer works in Chrome latest, but does still work in Canary.

## Chrome Regular and Canary, Meteor 1.2.1

without blackbox:

![image](https://cloud.githubusercontent.com/assets/251288/14481267/47d710e8-00ff-11e6-912a-e7725bfb1819.png)

with blackbox:

![image](https://cloud.githubusercontent.com/assets/251288/14481278/605e50d6-00ff-11e6-93bd-49216900d33f.png)

## Chrome Regular, Meteor 1.3.2-rc.4

with and without blackbox:

![image](https://cloud.githubusercontent.com/assets/251288/14481354/33c89652-0100-11e6-9604-7188ecb32045.png)

Canary works.

**Comment by abernix** [comment]
@lorensr Do you have any more recent experience with this?  I've used blackboxing fairly recently and it worked properly.  Also, presumably the Canary version you were using which was working would have been released by now. :smile:

**Comment by lorensr** [comment]
Works for me rn :)
