### ISSUE TITLE
Notify when major Cordova packages are changed

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6804]
When someone updates Meteor or a package, for cases in which a cordova package changed, I think it would be very helpful if prominently printed in the console output were a notice telling you that you need to resubmit to the app store. 

Related: https://github.com/meteor/meteor/issues/6789#issuecomment-209063701

**Comment by coderefractor** [comment]
Seconded

**Comment by chip** [comment]
Yes, please!

**Comment by lucfranken** [comment]
The Cordova hash which is generated by Meteor for Hot code push might be written in a file, like the Meteor version gets put into: .meteor/release so you can track it down in Git to see where an update is due.

**Comment by abernix** [comment]
As reported by @ianpogi5 in #8012, something similar would also be helpful for when major Cordova package changes might break a hot-reload: such as when going from Cordova 6.0 to 6.2 in Meteor 1.4.2.

I've changed the title of this issue to be a bit more generic, but I think still covers the original request.

**Comment by lorensr** [comment]
I might even consider Cordova changes to be breaking—since they break updates, a function that meteor users rely on in production—and increment the major (second) meteor version number.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Notify%20when%20major%20Cordova%20packages%20are%20changed&body=Migrated%20from:%20meteor/meteor%236804) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
