### ISSUE TITLE
Importing soap package crashes the application in Meteor 1.3.1.

### ISSUE THREAD

**Issue by kjami** [meteor/meteor#6805]
Hi, 

My meteor application is crashing, when I import [soap](https://www.npmjs.com/package/soap) npm module into my application. I have tried using `import`, `Npm.require` and `require` in the following ways,

<pre>
import * as Soap from 'soap';
// import * as soap from 'soap';
// import { soap } from 'soap';
// var soap = Npm.require('soap');
// var soap = require('soap');
</pre>

None of them prevented the application from crashing. When I used any of the above mentioned lines in my application, it is crashing with 

> TypeError: Object  has no method 'split'

So I have created a simple application to reproduce the bug. But when I use one of the above statements, it is still crashing but with a different error

> dyld: lazy symbol binding failed: Symbol not found: _node_module_register

To stop the app from crashing, comment `import * as Soap from 'soap';` line in `server/main.js`

My main application is upgraded from Meteor 1.2.1 to Meteor 1.3.1. I have added `ecmascript`, `modules`, `meteor-node-stubs` packages.  I have also installed `soap` (and dependant `compress`) package using `meteor npm install --save soap compress` before `import`ing the `soap` variable in a file.

The sample application repo specified below is created using `meteor create`.

Meteor Version: 1.3.1

Here is repo with a minimal code to reproduce this issue: https://github.com/kjami/soap-meteor-crash

Previously, this Npm.require('soap') statement use to be in a package, which worked well. So to show that, I have included a sample test package in the above repo as well. `require`ing in package works without any problem.

**Comment by kjami** [comment]
The problem looks like loading the dependency modules. In package, it is loading all dependency modules where as in application it is not loading all dependency modules. See the attached screenshots. Thank you.

 ![Image of soap dependency modules in main application](https://github.com/kjami/images/blob/master/meteor/node-modules-in-application.png)

 ![Image of soap dependency modules in package](https://github.com/kjami/images/blob/master/meteor/node-modules-in-package.png)

**Comment by abernix** [comment]
This is related to using the wrong version of `node` to install `soap`.  To avoid this, please make sure that you use `meteor npm install` and not just `npm install`.  I ran your repo and it works fine for me when installed with `meteor npm install`. :smile:
