### ISSUE TITLE
React Native integration

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6807]
Feature request:

`meteor add-platform react-native-ios/android`

I get the sense that everyone starting a new mobile app these days is using React Native 😄 Might be a big win for Meteor if it was the full-stack solution for building React Native apps. There are a few things that RN integration could look like. Here are some ideas:
- `meteor run/build` wrapper around eg `react-native run-android` that supports using the same code project directory for server, web client, and RN, sharing some of the code between all three, and perhaps some advanced sharing between RN and React web.
- data layer: currently you can use `minimongo-cache`, but looking ahead, the apollo client and cache will work in the React Native JS environment
- other modifications required to get the relevant Meteor APIs to work in RN environment, for instance using native storage instead of LocalStorage for Accounts resume token.

**Comment by martijnwalraven** [comment]
Creating full-stack apps with React Native is definitely a great option, but I'm not convinced tighter integration with Meteor is the way to go. 

React Native is a moving target, with its own ecosystem, and trying to wrap that will likely lead to suboptimal solutions. For example, there is a lot of innovation around tooling, both with React Native's own packager and with Webpack-based solutions, and forcing the use of the Meteor build system would mean you wouldn't be able to use certain features (like the debugger or hot module replacement) unless we are prepared to replicate the effort (which we are probably not, and which would always lag behind).

So I actually think decoupling Meteor and making it more open to integrating with the larger JavaScript ecosystem is the way to go. The move to npm is an important part of that, and we also want to make Meteor less dependent on using its own build system. That should make it easier to use parts of Meteor (like `minimongo`) in a React Native project.

With Apollo, that is the approach we are taking from the start. The Apollo client and cache should work in all JavaScript environments, including React Native. And if that requires the use of environment-specific APIs (like native storage), we will probably either try to find an existing abstraction or build one ourselves.

**Comment by lorensr** [comment]
Hey Martijn, thanks for the well-thought-out reply 😊

I see how wrapping `react-native` might not make sense. However, maybe there's a way to get the benefits of official integration without wrapping.

## Benefits of official integration

- Marketing – Bringing people from React Native to Meteor
- Ease of use – Keep the best, up-to-date way of using them together. Saves dev time, and makes it more likely devs will use them together (eg a RN dev deciding to use Meteor, or a Meteor dev deciding to use RN over Cordova).

Before Cordova integration, everyone knew you could put a web app inside a mobile app with Cordova, but not many people did it with Meteor. The pre-Cordova branding of Meteor was "best way to build a web app", and post, it was "best way to build web and hybrid apps". The idea that Meteor is for building  hybrid apps makes people who want to build hybrid apps consider using it. Before then, I would have had to think of the possibility myself, and also be willing to take the time/energy to figure out how based on 3rd party guides and packages and figure out solutions to the problems that I'd likely run into using those packages. Similarly, before official Angular support, if I'm an Angular developer, I might hear about how you could use Angular instead of the view library you're supposed to use with Meteor, but I'm much less likely to try it than if I see on Meteor.com that Angular is one of their 3 view layers.

## Integration

```
> meteor create --react-native myapp
[installs react-native, creates below dir structure]
myapp/
  react_native/   # RN app. where you run  `react-native` command
    package.json  # generated with minimongo/apollo client, accounts, etc    
  meteor/         # meteor app, optionally with a web client. where you run `meteor`.
    server/
    client/ 
    [etc]
  lib/
    local_npm_package1/ # code shared between meteor app and RN app
    local_npm_package2/  
```

- meteor.com says "Meteor is the best way to build web, hybrid, and native apps"
- RN is one of the 4 view tutorials
- Guide article on RN

### Meteor vs Apollo

Perhaps there also should be `apollo create --react-native myapp`? Is there going to be an apollo command line tool, or just a server module you import? What is Meteor besides data and view? Apollo will subsume pub/sub, methods, DDP, and collections. Will Apollo have `Accounts`? The only non-view things left in Meteor are Tracker/Session and build tool/Atmosphere.

**Comment by mikeifomin** [comment]
@lorensr really highly impressionable arguments!
But RN does not work out of the box (with single command). 
And RN integration entails more fragmentation for Meteor Platform. It will be harder to maintain with current level of quality as it is now in Meteor.

But as the react/angular packages starts like a separate project we (you, me and other interested contributors) can create package for ReactNative.

### Here is major steps:
1. Create guide from all of articles, packages are available for now. 
2. Create missing thin package (Account, Tracker, Minimongo, etc) **<- important**
3. Create single package  (to understand what we need to change in meteor core - build hooks)
4. Some experiments with fork of meteor 
5. Finally we could possibly create some stable pull for main meteor repo 

MDG now working on **Node 4+**, Npm, Apollo and Galaxy. Let them complete necessarily task.

- - -

@lorensr I'm interested to find new contributors and give a try.

**Comment by bradcrispin** [comment]
@martijnwalraven @lorensr . RN integration would be dreamy. But if the tooling is a moving target I would add an iOS perspective - regardless of what you use to build a front end (native, RN, hybrid), I think the major pain point in iOS land is the server, especially with Parse devolving from a service to OS. I suspect a lot of iOS devs would be interested in hearing about how to use Meteor as a reactive backend for mobile instead of thinking of it as a monolithic web framework. Why shouldn't Meteor become the go to choice for mobile back end? That would add a few Galaxy subs!

**Comment by thatgibbyguy** [comment]
> Why shouldn't Meteor become the go to choice for mobile back end?

Exactly. If we're honest, that's the strength of meteor anyway. Cordova is nice, and using Ace with cordova is pretty nice as well, but the webview train is leaving. 

For meteor to have a chance at being the go to for mobile backend, RN needs official support even if it's only in the form of a guide for how to use it. Of course, replacing cordova with RN would be the holy grail.

**Comment by martijnwalraven** [comment]
Well, we'll be recording a Transmission podcast today about exactly this topic!

**Comment by ChrisOHu** [comment]
Hi guys I think native client side meteor sdks would be the best way to go : )

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=React%20Native%20integration&body=Migrated%20from:%20meteor/meteor%236807) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
