### ISSUE TITLE
Javascript Rendering Problem

### ISSUE THREAD

**Issue by coderefractor** [meteor/meteor#6808]
Javascript is not normally loaded if it is included in the template like general HTML files. This makes it difficult to integrate themes into Meteor.

**Comment by mikeifomin** [comment]
@coderefractor The best way to include third party  Javascript is to use `Template.fancyTheme.onRendered` handler.



```javascript

Template.fancyTheme.onRendered(function () {
  // Use the this.find() like document.getElementById or document.querySelectorAll
  fancyTheme.init(this.find('.container'))
 
});

``` 


```handlebars
<template name="fancyTheme">
  <div class="container">
   {{> contentBlock}}
  </div>
</template>

<body>
  {{#fancyTheme}}
    <!-- you HTML code -->
  {{/fancyTheme}}
</body>
```

see [Docs](http://docs.meteor.com/#/full/template_onRendered)


O

**Comment by laosb** [comment]
I think @mikeifomin 's solution had done this case. Closing.
