### ISSUE TITLE
Click events on SVG elements fail in IOS

### ISSUE THREAD

**Issue by rdickert** [meteor/meteor#681]
I love the parties demo and wanted to play around with the d3 + SVG functionality. This is a pretty compelling use of Meteor, but when I tested on an iPad, the interactivity wasn't there. It appears that click/mousedown type of events are not registering. 

You can replicate this problem by opening the parties demo on an iPad. The display and reactivity work (you can see parties created elsewhere), but it is impossible to tap on a party to select it.

At first I thought IOS must not support events on SVG objects, but `<rect class="btn" x="0" y="0" width="100" height="70" onclick="alert('click!')"/>` is a clickable object on IOS. 

Edit: Since writing the above I discovered an odd behavior that may provide a clue. I added the above `<rect>` to the parties app in the existing `<svg>` element. Prior to clicking it, the map is unresponsive to taps, but if I tap the `<rect>` once and trigger the `alert`, the party circles become selectable, albeit with an odd flash and slight delay. If I refresh the browser, it ceases to respond to taps until I again click on the `<rect>`. Now that I found that, it turns out that the `<rect>` element is not even necessary - you can enable svg events simply by clicking the "Sign in" link. Could it be something as simple as binding events before the DOM is ready? 

Double clicks never work, but I take that as a design issue, not a technical one (while we're at it, I'll mention that the app doesn't format correctly on the iPad screen either - not sure if that's worth adding a separate issue).

**Comment by chrismcmath** [comment]
Just had the same issue with nav elements above an SVG- using 'touchstart' fixed it.

**Comment by watsokel** [comment]
I'm having the same issue still. Click does not work on both iOS aChrome and Safari. Please reopen this issue, Using touchstart is not an option for me because it results in a double event fire.

**Comment by kylecarlson** [comment]
Okay, crazy workaround here. In CSS for the element(s) you're trying to click, add cursor: pointer;

I had a class on each of the SVG elements on the page, and rather than adding 50 blank onclick events and reuploading SVGs, this one line fixed it all. Let me know if this works for anyone.

**Comment by sivakumarcse12** [comment]
> Please reopen this issue. Click does not work on both iOS Chrome and Safari. Using touchstart is not an option for me because it results in a double event fire.

if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
		   $(document).on("touchstart","#svgclick",function(){ 
			// code here
		   })
		}
		else{
			$(document).on("click","#svgclick",function(){ 
			  // code here		
		     })
		}
