### ISSUE TITLE
Please add opposite option of --server-only in 'meteor build'

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#6811]
Feature request in **meteor build**.

Could you please add the opposite option of **--server-only**? 
For example **--app-only**, or **--ios-only** or **--android-only**.

It would realy help in the (in my case) wasted time of server building.

Cheers,
Joris

**Comment by crapthings** [comment]
i think they should build at same time?

will hot code push replace ios bundle with server one that if you don't build server

**Comment by martijnwalraven** [comment]
I'm not sure this would help much, because in order to build the app, we would still need to build the `web.cordova` bundle.

**Comment by jorisroling** [comment]
Ah yes, I see. 
It's just that I never use the created **App.tar.gz**. I deploy to my server in an separate step (using mup).

**Comment by martijnwalraven** [comment]
Yeah, not generating the server bundle would same some time, but not much I think, because you still need to invoke the Meteor build system for the `web.cordova` bundle.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Please%20add%20opposite%20option%20of%20--server-only%20in%20'meteor%20build'&body=Migrated%20from:%20meteor/meteor%236811) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
