### ISSUE TITLE
Cordova iOS framework embedding doesn't work

### ISSUE THREAD

**Issue by ephemer** [meteor/meteor#6813]
Hi guys, especially @martijnwalraven. I'm using Meteor version 1.3 – great work to the whole team for this, it feels like a major upgrade, especially with the mobile stuff.

We're trying to get back to a meteor-based deterministic build for our iOS project and are having trouble adding our custom framework. We'd expect to be able to add this to our plugin's `plugin.xml`:

```
<platform name="ios">
    <framework src="build/MyCustomFramework.framework" custom="true" link="true" />
</platform>
```

..and have the framework appear in Xcode as a symlink, and added to Xcode's embed binaries build phase. This commit should have dealt with the issue of adding iOS frameworks to the embed phase: https://github.com/apache/cordova-lib/commit/737f2df4e5c8de205c90cc29614483ebcd71f605. But it's not working- it just adds the framework normally (and doesn't link it either, which is slightly less important at this stage)

I went into to `~/.meteor/packages/meteor-tool/.1.3.1.101c02o++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/ios.js` (which _does_ contain the code from the above commit that's supposed to fix this issue) and put a bunch of console.logs in the to try to see what was happening – it seems like nothing in this file gets called at all. Does meteor bypass `cordova-lib`'s plugman somehow?

What's the best way to get this embedding (and hopefully linking) working?
I'll put a small example project on GitHub shortly

**Comment by ephemer** [comment]
https://github.com/ephemer/meteor-cordova-add-framework-issue-example
just clone that repo, run `meteor run ios-device` and look at the resulting xcode project.

Click on the project in the file navigator tree, and note that `MyFramework.framework` is listed under `Linked Frameworks and Libraries` but not under `Embedded Binaries`.

Attempting to run the project on an actual device causes a crash on startup, because iOS expects to find the Framework in the app bundle, which only happens when it is present in `Embedded Binaries`.

**Comment by btafel** [comment]
I was able to workaround this by running this script, configured as a hook at plugin.xml [](https://github.com/btafel/cordova-plugin-braintree/blob/master/hooks/after_plugin_install.js )

It works just fine when running the app with `meteor run ios-device` but it won't work when build production release with `meteor build <output-dir>.....`. 

Both `meteor run` and `meteor build` generate an xcodeproject in ./meteor/local/corodva-build which is just fine, including the result of running the hook, BUT `meteor build` will also create an xcodeproject at the output-dir, which does not includes the right references to Embedded Binaries, which makes the project to fail.

I tried to understand why the build process won't take the /cordova-build folder as the same content for the output-dir compilation, but yet no luck. For now, I'm just overwriting the resulting output-dir/xcodeproject with the one from /cordova-build. Ugly.

**Comment by ephemer** [comment]
Thanks for the script link, I may well use an adaptation of it as well. As for `meteor build`: we can't use it anyway because we have local Cordova plugins that meteor now symlinks by default since 1.3 via relative paths. The relative paths are always broken for `meteor build`, so instead we just do a `meteor run ios-device --production` and use the Cordova project created in `./meteor/local/cordova-build` that then contains the production (minified) web.cordova bundle

**Comment by syrakozz** [comment]
any one able to solve it ?

**Comment by cusspvz** [comment]
Still waiting for `embed` attr to come under `cordova-lib`...
https://issues.apache.org/jira/browse/CB-10034

**Comment by hwillson** [comment]
This issue hasn't had any activity in the past 1.5 years. Is this still a problem for anyone? As part of the on-going old issue cleanup process, I'll close this for now. If anyone is still encountering this issue (with a modern version of Meteor) and feels like it should be addressed, please post back and let us know. Thanks!
