### ISSUE TITLE
minifyCss what does it do and why is it needed in dev mode?

### ISSUE THREAD

**Issue by gajuro** [meteor/meteor#6814]
We have a meteor 1.2 + React 0.14 app containing 60 React components. 

This week we had a big refactoring of all components applying the BEM styling convention resulting into 160 scss files and meteor rebuild taking ~35 seconds (**ClientTarget#minifyCss: 35736.7**).

I am not sure what minifyCss does in development since the css loaded in the browser simply looks like the concatenation of all the stylesheets resulting after scss processing.

Is there a way to skip this stage of the build? 
If not, can the css be cached somehow based on the unchanged sources?
If not, can the resulted css be hot pushed into the browser later, so we can view the js changes faster?

Thanks a lot for this great framework and for any answer.

**Comment by elisei-timofte** [comment]
Same here. Need help!!

**Comment by clayne11** [comment]
There's already an [issue](https://github.com/meteor/meteor/pull/5875) open tracking this.

**Comment by gajuro** [comment]
Thanks for your reply @clayne11 

I’ve just found a sort of an workaround for this: I’ve temporarily removed "seba:minifiers-autoprefixer” from .meteor/packages. Now I get a few warnings in the console, but at least I’m able to code again.

**Comment by gajuro** [comment]
I've upgraded to Meteor 1.3 and nothing changed.

We've decided to compromise the BEM approach and and use explicit bootstrap classes in the jsx files along the BEM classes. This way we avoind using scss @export, resulting in a way fewer css selectors.

**Comment by stubailo** [comment]
Yeah I think the issue linked above basically covers it - further discussion should go there.
