### ISSUE TITLE
Meteor.wrapAsync handles undefined parameters strangely (and wrong?)

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#6816]
Here's a simple test case:
```
var emptyObj = {}
var testFun = function(p1, p2, cb) { Meteor.defer(function() { console.log(cb) }) };
```

When I run `Meteor.wrapAsync(testFun)(1, 2)`, `console.log` prints `[Function]`.

When I run `Meteor.wrapAsync(testFun)(1, emptyObj.attr);` or `Meteor.wrapAsync(testFun)(1, undefined);`, `console.log` prints `undefined`.

Why should the callback be `undefined`? I'm passing two parameters in (even though the 2nd is `undefined`).

**Comment by clayne11** [comment]
Your function isn't defined properly. The final parameter, `cb` in this case, is supposed to be called with `(error, result)`. Your function simply logs the callback which doesn't make sense.

`Meteor.wrapAsync` will not work if you're not wrapping a node JS style callback.

**Comment by realyze** [comment]
Well that's a good point focusing on a bad part though. :-) What I'm saying is that if I pass arguments to the wrapped function, I would expect it gets called with the same arguments (plus a callback which is a node resolver created by `Meteor.wrapAsync`). But it doesn't actually get called with the same arguments, all `undefined` params are stripped (backwards starting from the last one). I don't think that should happen.

**Comment by abernix** [comment]
I don't believe this can be considered a bug and any changes might have significant impact.  You are welcome to bind whatever parameters you would like to your function before passing it to wrapAsync using a wrapper function.  If you believe this warrants a change to Meteor core, please open a feature request following the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).

Closing.

**Comment by mjovkovic** [comment]
I agree with @realyze. This behaviour is not expected. Here's the easy to reproduce example:

```
let myAsyncFn = Meteor.wrapAsync(function (arg1, arg2, callback) {
  Meteor.setTimeout(function() {
    console.log('Calling callback, got args:', arg1, arg2);
    callback(null, 'result');
  }, 5000);
});
```

So, we expect `myAsyncFn` to be called with 2 arguments. If we do
```
myAsyncFn('test1', 'test2')
```
it returns 'result' after 5 seconds, with server logging the message `Calling callback, got args: test1 test2`

Calling 
```
myAsyncFn(undefined, 'test2')
```
returns 'result' after 5 seconds as well, logging the message `Calling callback, got args: undefined test2`.

But, calling 
```
myAsyncFn('test1', undefined)
```
never returns. And the log on the server side is 
```
Calling callback, got param: test1 function (/* arguments */) {
    var args = _.toArray(arguments);

    var runWithEnvironment = function () {
      var savedValues = Fiber.current._meteor_dynamics;
      try {
        // Need to clone boundValues in case two fibers invoke this
        // function at the same time
        Fiber.current._meteor_dynamics = _.clone(boundValues);
        var ret = func.apply(_this, args);
      } catch (e) {
        // note: callback-hook currently relies on the fact that if onException
        // throws and you were originally calling the wrapped callback from
        // within a Fiber, the wrapped call throws.
        onException(e);
      } finally {
        Fiber.current._meteor_dynamics = savedValues;
      }
      return ret;
    };

    if (Fiber.current)
      return runWithEnvironment();
    Fiber(runWithEnvironment).run();
  }
```
Following an exception
```
Exception in setTimeout callback: TypeError: callback is not a function
    at repl:4:5
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1176:24)
```

So Meteor stripped the last argument, which was passed as `undefined`, therefore changing the expected function arguments `function (arg1, arg2, callback) {` where the actual callback was passed as second argument, while the `callback` parameter remained undefined, causing the callback never to be called and, lastly, async function call never to return.
