### ISSUE TITLE
[1.3.2-rc.6] feature request: import static resources

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6818]
`release/METEOR@1.3.2-rc.6` work well when import less, sass file from js.
if we can import some static resources  like: fonts, images, json.... that will be great !
that we can import pure npm package like bootstrap, summernote, sweetalert... ( all they have fonts...)
thanks mr @benjamn !

![font](https://cloud.githubusercontent.com/assets/8347826/14516289/aca357e8-022b-11e6-9478-663209366717.PNG)

**Comment by laosb** [comment]
For me, I'm using `han-css`, which includes a webfont to get things right. I'm able to import css now, but it doesn't import fonts correctly.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5B1.3.2-rc.6%5D%20feature%20request%3A%20import%20static%20resources&body=Migrated%20from:%20meteor/meteor%236818) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
