### ISSUE TITLE
[1.3.2] Date input field has stopped working

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6821]
I use a date input field that is configured with [pickadate](https://github.com/amsul/pickadate.js).

In `1.3.1` it works fine, but in `1.3.2-rc.6` clicking on it no longer does anything. The date picker used to pop up but now it simply doesn't respond to clicks.

**Comment by clayne11** [comment]
I worked around this issue by add an event listener on the picker's input field and manually opening the picker when it's clicked.

The ONLY change I made between when it worked by default and when I had to add this hack is updating from Meteor `1.3.1` -> `1.3.2`.

I'm not sure what caused this but I would be much more comfortable I understand what happened rather than just adding a hacky workaround.

**Comment by Siyfion** [comment]
Would you care to create a small code example of the issue?

**Comment by clayne11** [comment]
Closing because I'm not going to make a repro.
