### ISSUE TITLE
Don't traverse package repositories when package does not depend on modules

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6823]
Even when a package does not depend on `modules`, package directory is still traversed. This is problematic because sometimes it includes a lot of other code (like [whole node.js](https://github.com/peerlibrary/meteor-util)) which makes it then long to compile, or even throw a memory limit error. Or it goes into a symlink loop: #6665

**Comment by mitar** [comment]
Related: #6680

**Comment by mitar** [comment]
Related: 7598

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Don't%20traverse%20package%20repositories%20when%20package%20does%20not%20depend%20on%20modules&body=Migrated%20from:%20meteor/meteor%236823) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
