### ISSUE TITLE
Missleading error message

### ISSUE THREAD

**Issue by li-po** [meteor/meteor#6826]
Situation
- write a first local package (folder packages):  company:package1
- write a second local package (folder packages):  company:package2
- in the second package write:
  import { Something } from 'meteor/comsdfasdfpany:package1'
  instead of
  import { Something } from 'meteor/company:package1'

And you get the error:
Error: Can't find npm module 'meteor/comsdfasdfpany:package1'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

This happens (I guess) in 
https://github.com/meteor/meteor/blob/devel/tools/static-assets/server/boot.js
line 195

The message should be something like "The Atmosphere package 'comsdfasdfpany:package1' does not exist."
Due to the prefix 'meteor/' the system should be able to guess that we are looking for an Atmosphere package and not an npm package.

**Comment by laosb** [comment]
#6763

**Comment by abernix** [comment]
This was fixed with #6763.  Thanks for reporting this originally!
