### ISSUE TITLE
[1.3.1] Error running meteor test - Arguments to path.join must be strings

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#6828]
I'm trying run a simple test without nothing important or different.

I created this post in forum without solution so far (https://forums.meteor.com/t/error-running-meteor-test-arguments-to-path-join-must-be-strings/20974) then I think it is an issue because others have the same issue.

/usr/local/bin/meteor test --driver-package practicalmeteor:mocha --port 3100 --settings env/dev/settings.json
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3100
I20160407-22:27:17.793(-3)? Exception in defer callback: TypeError: Arguments to path.join must be strings
I20160407-22:27:17.794(-3)? at path.js:360:15
I20160407-22:27:17.794(-3)? at Array.filter (native)
I20160407-22:27:17.794(-3)? at Object.exports.join (path.js:358:36)
I20160407-22:27:17.794(-3)? at Object.pathJoin (packages/velocity_meteor-internals.js:681:16)
I20160407-22:27:17.795(-3)? at Object.getTestsPath (/private/var/folders/lt/xtllnx7d6619n_4rf9pm8pf80000gn/T/meteor-test-run1hb4acl/.meteor/local/build/programs/server/packages/velocity_core.js:1425:44)
I20160407-22:27:17.795(-3)? at initFileWatcher (/private/var/folders/lt/xtllnx7d6619n4rf9pm8pf80000gn/T/meteor-test-run1hb4acl/.meteor/local/build/programs/server/packages/velocity_core.js:1604:23)
I20160407-22:27:17.795(-3)? at initializeVelocity (/private/var/folders/lt/xtllnx7d6619n_4rf9pm8pf80000gn/T/meteor-test-run1hb4acl/.meteor/local/build/programs/server/packages/velocity_core.js:1364:11)
I20160407-22:27:17.795(-3)? at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
I20160407-22:27:17.795(-3)? at packages/meteor.js:445:45
I20160407-22:27:17.796(-3)? at runWithEnvironment (packages/meteor.js:1154:24)

If you need more information than I put in the forum, please let me know

**Comment by lorensr** [comment]
I had this problem too! Try:

```
grep velocity: .meteor/versions
```

Any matches? If yes, remove all velocity packages, like `mike:mocha`, `xolvio:cucumber`, and `sanjo:jasmine`. Then run `meteor` so it can recompute dependencies. Once `velocity:core` is gone from `.meteor/versions`, try running the test command again. Lmk if you have any issues 😊

**Comment by filipenevola** [comment]
Hi @lorensr , thank you man.

Jasmine was the problem.
