### ISSUE TITLE
When importing CSS from npm module, import assets too

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#6829]
**_1 Upvote**_ I'm using `han-css` from npm to improve the layout and readability of Chinese in my app. From 1.3.2, I could import its css and js using:

```
import 'han-css/dist/han.css';
import Han from 'han-css';
```

But the problem is, in the `han.css`, it loads webfonts like this:

```
@font-face {
  font-family: "Biaodian Sans";
  src: url("./font/han.woff?v3.3.0") format("woff"), url("./font/han.otf?v3.3.0") format("opentype"), local("Hiragino Sans GB"), local("Hiragino Kaku Gothic ProN"), local("Hiragino Kaku Gothic Pro"), local("Microsoft Yahei"), local(SimSun);
  unicode-range: U+2014;
}
```

That doesn't work. Browser complains like that:
![image](https://cloud.githubusercontent.com/assets/2545261/14578458/58fd437e-03bb-11e6-84ac-10e02e43d194.png)

It looks like that Meteor didn't ever handle it.
So the possible solution is, parse that css file and serve assets  in some folder, and then change the path in the css file, finally we merge it to the merged css.

**Comment by laosb** [comment]
Related #6818

**Comment by zhaoyao91** [comment]
what's worse, it even change the asset path if you go into your app from not-root url
![image](https://cloud.githubusercontent.com/assets/3808838/14585061/38d202c8-0498-11e6-8824-1775fa8dc6fa.png)

**Comment by ramirez530** [comment]
Ramirez044@yaho.com

**Comment by tcastelli** [comment]
+1 My solution for now is to load the scss with the fourseven package and change paths, but that implies that I can't import packages that only produce a css and to do the same trick :(

**Comment by NitroBAY** [comment]
Sorry but what's your plan ?
One year after we still cannot correctly import `.css` from npm (one hack is to `import` in a `.js` file but then the css is **NOT** minified..., **not minified !**). May you explain what am I supposed to do to import and minify a css file from a npm package (except using webpack).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=When%20importing%20CSS%20from%20npm%20module%2C%20import%20assets%20too&body=Migrated%20from:%20meteor/meteor%236829) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mizzao** [comment]
Have any of you found a solution for this? I've also import some `npm` packages and their CSS, but the `background-image(...)` parts are not showing up.
