### ISSUE TITLE
Meteor 1.3.2(.1) - tests are not executed

### ISSUE THREAD

**Issue by Ben305** [meteor/meteor#6831]
***1 Upvote*** After updating to Meteor 1.3.2 (or 1.3.2.1), the test are not executed any longer. The test runner starts, but it seems that no files are found.

It's easy to reproduce: Clone todo-app. Start tests using _npm run test-watch_. When using Meteor 1.3, client tests (5) and server tests (18) are executed.

Now update to Meteor 1.3.2 or 1.3.2.1. The test runner can be started successfully, not neither on the server nor on the client any test is run (the tests aren't shown either).

**Comment by benjamn** [comment]
Reverting eb18d59faa1986d912a59bd57a4ecc03ba4b3572 seems to fix this. I'll look into why.

**Comment by jasonnathan** [comment]
+1

**Comment by Sanjo** [comment]
I wonder if this could be released as a hotfix (e.g. 1.3.2.5), because this blocks people who test to upgrade to 1.3.2.x and in general the whole testing feature is broken in the latest recommended Meteor release, which is a bad impression.

**Comment by thebarty** [comment]
plus one!

**Comment by tiagolr** [comment]
+1 Happening with Meteor 1.4.0.1
