### ISSUE TITLE
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#6834]
I am working on a cordova app in 1.3.1.
When I write ` style="display:block;height:80%;"` as a div attribute that throws an exception. `Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`
The console asks me to disable minifier for React to retrieve the full message error.

How is this doable in Meteor?

Note I use **ecmascript hot** package (cc @gadicc).

**Comment by gadicc** [comment]
Hi @dagatsoin, you should switch back to the original `ecmascript` package to confirm if this is a bug in Meteor or my package.

(As an aside, if the package is working for you in Cordova, it would be great for you to mention it in https://github.com/gadicc/meteor-react-hotloader/issues/33).

I've never come across this error before but in case you're running with "--production", try running without that.

**Comment by stubailo** [comment]
Yeah, I don't think this is a bug in Meteor itself, most likely. If there is a reproduction of this issue without the hot reload package, we can reopen.
