### ISSUE TITLE
devDependencies are loaded into the application

### ISSUE THREAD

**Issue by trajano** [meteor/meteor#6836]
I noticed an issue when I was developing a package that worked on 1.2 and had issues on 1.3 https://forums.meteor.com/t/npm-devdependencies-get-added-on-package-builds/20265.  However, I was testing out a change on my main application and I also noticed that `devDependencies` are also being loaded.

To test this, do `meteor npm install gulp --save-dev`

Then look at modules.js from the web browser you would see gulp.js and other things that are supposed to be only for development being loaded.

This is affecting 1.3.1

For those who are using CoffeeScript, https://github.com/jashkenas/coffeescript/issues/1078 crops up only on the client side from what I can tell though.

### When reporting a bug, please be sure to include the following:
- [X] A descriptive title
- [X] What version of Meteor you're using, and the platform(s) you're running it on
- [X] What packages or other dependencies you're using
- [X] The behavior you expect to see, and the actual behavior
- [X] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for more detail on what is expected of a bug report.

**Comment by priezz** [comment]
I have the same issue with 1.3.2.1 - all dev deps are in the production bundle (ex., `eslint`)

**Comment by trajano** [comment]
One thing to note, even if it does get loaded it does not get executed.  I had a bug in my `gulpfile.js` that caused it to execute.

Regardless though it should not be part of `modules.js`

**Comment by arunoda** [comment]
I'm also seeing this in Meteor 1.3.2 and take forever build the app. Looking forward for a solution.

**Comment by eXon** [comment]
Webpack is having a lot of devDependencies we DON'T want in the final bundle. In a really small app, my bundle is 64 MB and there is around 50 MB of devDependencies, which is a huge problem for everyone using Webpack with Meteor. 

Bundling is REALLY slow.

Meteor should go through package.json files and only keep dependencies and ignore devDependencies. Here is how we were doing it with Webpack: https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/WebpackCompiler.js#L634-L684

Hope it helps.

**Comment by trajano** [comment]
I found a way around it at least with gulp by aliasing requires to something else.  In addition, you can make it require something in a `.` folder.  I'm using it in my [meteor boilerplate][2]

I had documented in [how to use gulp with meteor][1]

Though that is only runtime rather than bundle.

[1]: http://www.trajano.net/2016/04/using-gulp-with-meteor/
[2]: http://github.com/trajano/meteor-boilerplate

**Comment by benjamn** [comment]
Closing in favor of https://github.com/meteor/meteor/issues/6750.
