### ISSUE TITLE
Windows installer cannot properly reinstall

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6837]
1) If I delete `AppData/Local/.meteor` folder and try to reinstall meteor with the official installer - it doesn't download anything, but says that meteor has been installed:
![image](https://cloud.githubusercontent.com/assets/10534563/14598845/e67d133a-055c-11e6-8c48-78381cad8e57.png)
Then I have to manually go through the registry and remove every line containing string 'meteor' in order for the installer to actually download meteor files.
Can you make that the installer actually re-downloads all the files every time it's being run - no matter what is in the registry?
2) After all this voodoo, there is no uninstall record for meteor in windows remove\uninstall programs list. That needs to be fixed

**Comment by benjamn** [comment]
Thanks for letting us know about this problem!

@stubailo may have some ideas about how to proceed here

**Comment by benjamn** [comment]
Just ran into this myself. Although this isn't fixed in the current beta of 1.3.3 (`meteor update --release 1.3.3-beta.0`), it will be fixed before the official 1.3.3 release.
