### ISSUE TITLE
Windows installer installs 1.3.1 instead of 1.3.2.1

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6839]
***1 Upvote*** https://forums.meteor.com/t/meteor-1-3-2-isnt-available-on-windows/21474/6

**Comment by trajano** [comment]
This is what I get on Windows 7
<pre>
> meteor update
Not updating the release, because this app is at a newer release
(METEOR@1.3.2.1) than the latest recommended release (METEOR@1.3.1).
</pre>
I think Windows 10 worked, but hard to tell because the screen is garbled up.

**Comment by tcastelli** [comment]
+1 had to do a manual update

**Comment by benjamn** [comment]
This is expected. Neither 1.3.2 nor 1.3.2.1 are recommended releases. The next recommended release will be 1.3.2.2 (which you can manually update to now if you like).
