### ISSUE TITLE
1.3.2.1 doesn't work with coffeescript

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6841]
Whenever I do `meteor add coffeescript` I get 
![image](https://cloud.githubusercontent.com/assets/10534563/14602447/a1f692c2-0570-11e6-9d3b-aa6fce1e8eef.png)

**Comment by benjamn** [comment]
Is `startUp.coffee` your file? What does it look like?

**Comment by avalanche1** [comment]
Yes, it is. And it's blank.

**Comment by talha-asad** [comment]
This is the only issue that makes me happy :)

**Comment by avalanche1** [comment]
So, what can I do to narrow this down? I cannot be the only person having this, can I?

**Comment by abernix** [comment]
This issue does not appear to be a recurring issue and seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen if you can provide a GitHub link to a reproduction repo project.
