### ISSUE TITLE
[1.3.2.x] minimongo observe changed cursor broken in Meteor 1.3.2.x and minimongo 1.0.15

### ISSUE THREAD

**Issue by rogerkirkness** [meteor/meteor#6849]
***1 Upvote*** I believe that upgrading to 1.3.2.2 broke the observe changed cursor functionality in minimongo. I have not isolated why yet, but I believe I was able to reproduce it here:
https://github.com/rogerkirkness/meteor-changed-cursor-bug

I am using Meteor 1.3.2.2 on Windows 10 64x in Firefox browser. The cursor is not updating my local collection when I write this (also demonstrated in the above reproduction):
```
Collection.find({}).observe({
  changed: function(new) {
    if (new._id == "id") {
      indicatorVar.set("id", new.data);
    }
  }
});
```

I am using the latest versions of minimongo, reactive-dict and mongo. The behavior before was the function updated reactive-dict I had initialized earlier with information from a local collection when it changed. Now it wont run and the reactive dict is undefined, where it ran before upgrading. I believe this can be reproduced in the repo I link to above but I am new to this process...

**Comment by rogerkirkness** [comment]
Update: I got this working by adding an "added" cursor which works when I add the record, but it does not notice the changed item like it used to. So it adds it the first time using all the same infrastructure (local collection, reactive dict, client helpers, publish ont he server) but the changed does not notice changes. This, I believe, suggests the behavior of changed is different version to version. It could be I used it wrong initially and it is now more strict, or something broke in the new version.

**Comment by rogerkirkness** [comment]
Final update: minimongo 1.0.14 and Meteor <=1.3.2 works, where 1.0.15 and Meteor 1.3.2.x do not. The version bump from minimongo 1.0.14 to 1.0.15 broke the functionality after the upgrade.

**Comment by tcastelli** [comment]
+1

**Comment by abernix** [comment]
I'm guessing this is because of #5680 which snuck into 1.3.2.1 and 1.3.2.2.  It will be backed out of 1.3.2.3 (soon-ish – I would expect this today or tomorrow), maybe re-worked a bit, and then reintroduced (probably) in 1.3.3.

**Comment by tmeasday** [comment]
Hi @rogerkirkness, thanks for the repro, I can see the issue you are referring to[1].

This changed behavior is not actually surprising though. @abernix is right that it's #5680 which causes DDP message callbacks (such as observe callbacks) to be batched. So if you send a DDP `added` followed immediately by a `changed`, they'll be batched into a single `added` callback. You can see the old behavior is still there if you add a `Meteor._sleepForMs(1000)` between your two messages in the publication. Typically this would be more like behavior you'd see in the wild.

Is there a reason you were relying on only the `changed` callback? Is there some library affected by this?

I'll close this issue for now but we can re-open if there are flow-on effects of this.

[1] Although I needed to change your code to make the client-side collection be called `"b"` as that's where you were publishing. Perhaps you could change the repro to avoid confusion in the future?

**Comment by rogerkirkness** [comment]
I wanted to confirm this is working again in 1.3.2_4. Thank you for your help.

**Comment by mitar** [comment]
> I wanted to confirm this is working again in 1.3.2_4. Thank you for your help. 

Just to warn you that this will "break" again for you in 1.3.3. So you should still answer why you need this old behavior.

**Comment by rogerkirkness** [comment]
What id the new behavior? observeChanges?

**Comment by mitar** [comment]
That  changes are batched together so you might not get callbacks for both `added` and `changed`, but maybe only `added`.
