### ISSUE TITLE
Meteor 1.3.2.2 - errors no more detailed than before

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6850]
I'm still seeing errors without sourcemaps, and without proper file names, e.g:

```
TypeError: Cannot read property 'tracks' of undefined
    at ReelDraft.componentWillMount (app.js:719)
```

And when I click the link to app.js, I get transpiled code:

```
  ReelDraft.prototype.componentWillMount = function () {                                                               // 61
    function componentWillMount() {                                                                                    //
      this.setState({   ...
```

**Comment by ffxsam** [comment]
Hmm.. doing `rm -rf .meteor/local/bundler-cache` seems to have fixed this. Is that expected?

```
TypeError: Cannot read property 'tracks' of undefined
    at ReelDraft.componentWillMount (ReelDraft.js:74)
```

```
  componentWillMount() {
    this.setState({  ...
```

**Comment by abernix** [comment]
If you don't mind, I'll close this for now.  We have other source map issues open, such as the popular #7076, which will progress to hopefully address nuances such as this (not working, but working after rebuild).

Additionally, there are known problems with particular packages https://github.com/meteor/meteor/issues/7206#issuecomment-230332826

Also potentially related, #6851
