### ISSUE TITLE
Unable to import momentjs in meteor 1.3.2.2 (OS X)

### ISSUE THREAD

**Issue by sbarnabas** [meteor/meteor#6854]
meteor add momentjs:moment fails in 1.3.2.2, it worked previously in 1.3.1.

```
daybreak:mobile sbarnabas$ meteor create blank
Created a new Meteor app in 'blank'.

To run your new app:
  cd blank
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

daybreak:mobile sbarnabas$ cd blank
daybreak:blank sbarnabas$ meteor add momentjs:moment
 => Errors while adding packages:

While checking for momentjs:moment@2.13.0:
error: No compatible binary build found for this package. Contact the package author and ask them to
publish it for your platform.

daybreak:blank sbarnabas$ meteor --version
Meteor 1.3.2.2
daybreak:blank sbarnabas$ uname -a
Darwin daybreak.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```
Since momentjs hasn't changed, I'm assuming this is due to a build change in meteor.

**Comment by santiq** [comment]
Why not use the npm package instead?

**Comment by rogerkirkness** [comment]
This is discussed here:
https://forums.meteor.com/t/announcing-meteor-1-3-2-2/21637/18

In the short term, you can replace the meteor package with the npm package by:
`meteor remove momentjs:moment && npm install --save moment`

It wont solve the problem for packages that depend on moment but that is on the package author.

**Comment by sbarnabas** [comment]
@rogerkirkness Thanks for the work around.
Do you happen to know the underlying change that caused this? I'd love to be able to tell which other packages are affected.

**Comment by mlecoq** [comment]
@sbarnabas  This issue is fixed now : a moment version 2.13.1 has been published

**Comment by abernix** [comment]
Can this be closed @sbarnabas?

**Comment by sbarnabas** [comment]
Yes, this is resolved.  Thanks!

On Wed, May 4, 2016, 11:44 AM Jesse Rosenberger <notifications@github.com>
wrote:

> Can this be closed @sbarnabas <https://github.com/sbarnabas>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/6854#issuecomment-216906682>
>
-- 
Sandy Barnabas
Lead Architect, Boom Fantasy
