### ISSUE TITLE
Unpublish specific version of a package

### ISSUE THREAD

**Issue by ichernev** [meteor/meteor#6855]
I'm the maintainer of moment.js https://atmospherejs.com/momentjs/moment
I tried pushing out version 2.13.0 but somehow it got corrupted to a state where users can't download it and I can't push it:

```
error: Version already exists
```

Also there was no clear indication on how to remove versions (only whole packages).

I managed to push 2.13.1, but I want to remove 2.13.0 so nobody gets errors: https://github.com/moment/moment/issues/3130

I'm submitting the package from a linux box -- all versions up to 2.13.0. 2.13.1 was from OS X (but OS X still failed with version exists for 2.13.0). It had worked so far, so I guess its not the issue.

**Comment by stubailo** [comment]
It's not possible to remove a version of a package in general; nobody should accidentally get `2.13.1` though if no packages are specifically depending on that version, and they don't intentionally download that specific version. Hopefully that is OK.
