### ISSUE TITLE
possible bug in Template.body.events arguments + blaze tutorial affected

### ISSUE THREAD

**Issue by lyricalpolymath** [meteor/meteor#6856]
Hi,
following the tutorial for Meteor 1.3.1 in the "[Storing temporary UI state in a Reactive Dictionary](https://www.meteor.com/tutorials/blaze/temporary-ui-state)"

I think there is either a bug in Template.body eventMaps or
there is an error in the step for imports/ui/body.js 
```
'change .hide-completed input' (event, instance) {
    instance.state.set('hideCompleted', event.target.checked);
  },
```
when I click it I get a warning
>body.js:57 Uncaught TypeError: Cannot read property 'state' of null

this is because, oddly enough, instance = null

digging I found an **inconsistent behaviour** between the arguments that Template.body.events provide and those that any other template (ie Template.task.events) provide

## THE PROBLEM
apparently there are **3 arguments in the Template.body events while there are 2 in other Templates events**

test it yourself :

### Template.body.events
**in imports/ui/body.js **
```
Template.body.events({
    //TWO PARAMETERS BUT IT EXPECTS THREE
    'change .hide-completed input'(event, instance) {
          console.log("change filter event - arguments: ", arguments);  //shows 3 arguments - the 2nd = null
    }
});
```
yields to console

```
change filter event - arguments:  
    0: jQuery.Event
    1: null
    2: Blaze.TemplateInstance
    ...
```
**the problem is that NULL argument**

### Template.task.events (or any other template)
**in imports/ui/task.js **
```
Template.task.events({
    'click .delete'(event) {
          console.log("delete event - arguments: ", arguments); // shows 2 arguments
    }
});
```
yields to console

```
delte event - arguments:  
    0: jQuery.Event
    1: Blaze.TemplateInstance
```

## SIMPLE SOLUTION (without solving the bug) > CHANGE THE TUTORIAL

the tutorial page should change this
` 'change .hide-completed input'(event, instance) {`
to this
` 'change .hide-completed input'(event, NULL, instance) {`
possibly adding an explanation of why there should be that 'NULL' argument
(beware, you can't use "null" in lowercase as it will yield an error)

**or am I doing something wrong?**
thanks!

**Comment by stubailo** [comment]
That's so odd - `Template.body` is in basically all ways a normal template.

**Comment by lyricalpolymath** [comment]
did you manage to reproduce the error? 
or is it something I only get?

**Comment by klaussner** [comment]
I always get the expected two arguments in `body` templates. Do you have a repo with an example?

**Comment by lyricalpolymath** [comment]
Hi
here's the repo
https://gitlab.com/lyricalpolymath/simple-todos-tutorial-blaze-bugged
(I had a problem with credentials trying to upload it to github :(  )

I initially thought it could be a problem of Meteor version but it isn´t
and the problem does not appear to be present in the official meteor repository for the tutorial.
https://github.com/meteor/simple-todos

I'm starting to think that maybe there is a package that I've installed (constellation?) that has changed the behavior of the Template.body??

Let me know if you too see the bug in my repo (I'm using the latest Meteor version 1.3.2.4 now)
thanks

**Comment by klaussner** [comment]
It's not a bug. The issue is caused by [gwendall:body-events](https://atmospherejs.com/gwendall/body-events), which is an indirect dependency of Constellation. This package changes the signature of body event handlers such that they receive the data context as second argument.

**Comment by lyricalpolymath** [comment]
gotcha! thanks! 
I had a sense it might have been constellation. @klaussner how did you track down exactly that it was that?
is that a normal behaviour or should I warn gwendall to solve the issue in his package?

**Comment by klaussner** [comment]
I just called `console.trace()` in the event handler. If Constellation is added to the project, you can see that gwendall:body-events calls the `body` handlers. It looks like overriding the default behavior is the whole purpose of this package.

**Comment by lyricalpolymath** [comment]
nice trick. I was unaware of console.trace. thanks!

**Comment by andreavaghi** [comment]
I'm having the same problem, following the tutorial with v.1.3.3
the project has only the default packages and the reactive-dict from step 7

the stack trace is:
```
Error
    at HTMLInputElement.changeHideCompletedInput (body.js:45)
    at HTMLInputElement.<anonymous> (inspector.js:1)
    at HTMLDocument.dispatch (jquery.js:4665)
    at HTMLDocument.elemData.handle (jquery.js:4333)
```
i've managed to solved it including the solution suggested by @lyricalpolymath adding a NULL parameter in the handler function. Maybe it has to be fixed like this also in the tutorial?

**Comment by kraegpoeth** [comment]
Hi guys,

Just going through the tutorial with METEOR@1.4.2.3 and I want to point out that if you have meteor-toys:allthings installed it will also insert a second `NULL` argument on the `Template.body` resulting meteor expecting three arguments instead of two thus producing the same error as @lyricalpolymath mentions.

The problem is transversed by adding a NULL argument to the eventhandler as mentioned or by removing meteor-toys as @klaussner suggests. Thanks to you both!

Dunno who (or if relevant) to ping for a fix - the meteor tutorial team? Meteor-toys team? - just wanted to mention it here for future reference.
