### ISSUE TITLE
[1.3.2.2] Server doesn't display errors on startup when importing an invalid package 

### ISSUE THREAD

**Issue by billyvg** [meteor/meteor#6858]
I have a server file that is not in the `imports` directory. it had an invalid `import` statement, i.e.

`import { Mongo } from 'meteor/Mongo';

When starting up the dev server, no errors are thrown before the server fully starts, and it just seems like it's hanging.

**Comment by abernix** [comment]
The latest version of Meteor would provide the following error in such a case:

    Error: Can't find npm module 'meteor/Mongo'

Please consider upgrading to the latest version of Meteor 1.3.4.4:

    meteor update --release 1.3.4.4
