### ISSUE TITLE
Build freezes at building for web.browser when there are large number of js files in the imports directory in meteor 1.3

### ISSUE THREAD

**Issue by aruntk** [meteor/meteor#6859]
I've created a repo to demonstrate the issue https://github.com/aruntk/js-load-test
As stated in the title while building meteor gets frozen when I put a large number of js files inside imports directory even if I'm not importing them from the client/server. No error is shown in terminal.
I suspect this is because the ecmascript package going through all js files inside imports irrespective of whether I'm importing them or not. 
I think this should change to - go through the files which the user is importing.
Another possible solution(although I prefer the first one) maybe implementing a babelrc file and add files in the ignore field.

**Comment by aruntk** [comment]
@tmeasday I'm stuck at this issue. Could you please help?

**Comment by chip** [comment]
Not sure if I could help here, but I was curious to know the best approach for debugging this issue.

Here's what I did, with some help from the [Meteor Tool README](https://github.com/meteor/meteor/blob/abd574f38008b45f5e2a6bc322b10bcdde44763a/tools/README.md):

1. Cloned meteor: `cd ~/code && hub clone meteor/meteor`
2. Cloned js-load-test: `hub clone aruntk/js-load-test`
3. From both tmux panes I was using, I ran `export TOOL_NODE_FLAGS=--debug-brk`
4. Run inspector.js: `cd ~/code/meteor/dev_bundle/lib/node_modules/node-inspector/bin; ./inspector.js`
5. Launched browser: http://127.0.0.1:8080/debug?port=5858
6. Ran the js-load-test against the cloned meteor repo: `cd ~/code/js-load-test; ../meteor/meteor`

I see the app run until the point of `Building the application`, but nothing after that.

From the browser (step 5) I don't see a way to open any files to set a breakpoint, so I think I'm missing a step or possibly doing this all wrong.

Maybe someone has suggestions on how I can debug this better? Thanks.

**Comment by tmeasday** [comment]
Hi @chip,

Thanks for taking a look at this.

When I do this, I see the following:

On immediately loading node inspector:
![screen shot 2016-04-22 at 10 57 59 am](https://cloud.githubusercontent.com/assets/132554/14750328/17d35b96-0879-11e6-9bc3-0507510b7b0a.png)

Not all the tool sources, but a couple of them. I put a break point in `project-context.js`:
![screen shot 2016-04-22 at 10 58 28 am](https://cloud.githubusercontent.com/assets/132554/14750343/2a321e80-0879-11e6-9b65-046666cb4174.png)

After hitting "continue", I now see the list of files populate on the LHS, and the tool stops at that line:
![screen shot 2016-04-22 at 10 59 10 am](https://cloud.githubusercontent.com/assets/132554/14750355/40d0b9c6-0879-11e6-923a-e23b97102419.png)

I can now set breakpoints wherever.

I'm not sure why it does that weird thing but that might help.

**Comment by chip** [comment]
@tmeasday - Thanks for following up. The problem for me is that the sources aren't listed.

![build-freezes](https://cloud.githubusercontent.com/assets/31725/14762448/f881ec54-093f-11e6-8571-a99ce13616ff.png)

Would you please describe the steps that you followed to get them load? Thanks.

**Comment by tmeasday** [comment]
@chip I'm really not sure what's different. I took the first screenshot above immediately on loading the node-inspector in the browser.

**Comment by chip** [comment]
Ok, I'm not sure what happened, but I reloaded the browser and was able to open files. I set a number of  breakpoints, eventually getting to `tools/isobuild/bundler.js`, but I haven't yet narrowed it down completely yet. It hangs at `Building for web.browser`.

**Comment by chip** [comment]
Actually, I just noticed it says `Error 0ding for web.browser`, which looks strange. I'll keep looking.

**Comment by chip** [comment]
With **Pause on all exceptions** set within Chrome Dev Tools, I'm seeing `SyntaxError: Unexpected end of input` inside `module.js` several times as I step through:
![module](https://cloud.githubusercontent.com/assets/31725/14827406/ce134d68-0ba7-11e6-90e5-0b9b92dcf2b4.png)

Additionally, I'm seeing `Syntax error: Unexpected token` many times within `babylon/index.js`:
![unexpexpected-token](https://cloud.githubusercontent.com/assets/31725/14827464/1c7a375a-0ba8-11e6-9c7f-4f2fcfb94822.png)

The last file that I currently see running is `babel-traverse/lib/path/context.js`, yet I'm not sure exactly where to pinpoint. It doesn't help that I keep losing my breakpoints, so that might be all that I can do unless anyone has further suggestions.

**Comment by wangyueming** [comment]
I have the same issue on version 1.3.2.4. 

Please take a look at the picture. If I put the lib folder into web, the building freezes at building for web.browser, it can reproduce. If I put the lib folder as a sibling of web folder. It is okay.
![2016-06-05 11 17 48](https://cloud.githubusercontent.com/assets/10303419/15803421/2b7f80bc-2b0f-11e6-98f5-180ea0a99af5.png)

It seems flat directory structure is better than deep directory structure.

**Comment by danlg** [comment]
got this issue as well using 1.3.4. sometimes it hangs sometimes the build takes ages, so it's difficult to say if it is systematic. 
```
NODE_ENV=production meteor run ios-device --production --settings settings.json --mobile-server=https://example.com -p 5000
```
Build tools chain are expected to work. I have an app now which takes 15-20 min to build...when it works..This compares poorly with this is not even a strongly type language such as C++ are very agressive optimization compiler. I experienced much more complex and system and the build was not so long, complicated and convoluted. I seriously consider leaving Meteor as it kills the productivity and makes me wonder if this is a reliable framework I can rely on.

**Comment by pooya-eghbali** [comment]
same issue using 1.3.4. didn't have this problem before, did a meteor update from 1.3.3.1 to 1.3.4 and now i have this issue, did a meteor update --release 1.3.3.1 but didn't solve the issue. i removed all of the packages from my meteor project and adding them one by one to find the source of the issue; problem was with .js files in public folder of one of custom packages, changing extension for all of the .js files in public folder to .es5.js solves the issue, but it breaks things in the project (dependencies/loading resources) and it's seriously a stupid way of solving this problem.

**Comment by aruntk** [comment]
@tmeasday Any updates on this issue?

**Comment by tmeasday** [comment]
@benjamn any thoughts on how the ecmascript cache could have gotten corrupted?

**Comment by abernix** [comment]
Is anyone still experiencing this problem?  If this was the case, it's likely a failed download which has been improved by various updates to the downloader.  I'll close this if there are no objections.
