### ISSUE TITLE
EEXIST fs error involving wrong filename case

### ISSUE THREAD

**Issue by dmarkrollins** [meteor/meteor#6863]
Mac OS 10.10.5
Current Meteor Version: 1.2.1

The app is organized as a collection of packages.

Here is the error I am getting:

/Users/DMR/.meteor/packages/templating/.1.1.8.q861ph++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: EEXIST, mkdir '/Users/DMR/Code/meteor/tournitup/.meteor/local/isopacks/.build55672.tiu-app/os/Schema'

**Comment by chip** [comment]
Would you be able to provide a repo and steps to reproduce this issue?

**Comment by dmarkrollins** [comment]
I put a sample project out here that should throw this error when you attempt to update it.

https://github.com/dmarkrollins/tournitup3

**Comment by chip** [comment]
@tmeasday - With help from the [Meteor Tool README](https://github.com/meteor/meteor/tree/devel/tools), from the **Debugging** paragraph, I did the following to attempt to troubleshoot this issue:

### Terminal shell for Meteor repo
1. Cloned meteor from `~/code`: `hub clone meteor/meteor`
2. Changed into the repo directory: `cd ~/code/meteor`
3. Setup the **dev_bundle**: `./meteor --get-ready`
4. Set debugging variable: `export TOOL_NODE_FLAGS=--debug-brk`
5. Change into inspector directory: `cd ~/code/meteor/dev_bundle/lib/node_modules/node-inspector/bin`

### Terminal shell for this repo
1. Cloned repo from `~/code`: `hub clone dmarkrollins/tournitup3`
2. Changed into repo directory: `cd tournitup3`
3. Set debugging variable: `export TOOL_NODE_FLAGS=--debug-brk`
4. Run the app against the downloaded meteor repo: `../meteor/meteor update --release 1.3`

### Go back to the Terminal shell for Meteor repo
6. Run the inspector: `./inspector.js`

Load the node-inspector per the url it responds with:
http://127.0.0.1:8080/debug?port=5858

I stepped through the code for quite awhile, but eventually the console reported from the Terminal shell for **tournitup3**: `Can't specify a release when running Meteor from a checkout.`.

I'm definitely doing something wrong. Do you have any suggestions? Thanks.

**Comment by tmeasday** [comment]
Thanks for the repro @dmarkrollins. The issue is case sensitivity -- your package has a folder "Schema" but you `api.addFiles('schema/..')`. We should throw a better error I guess @benjamn?

**Comment by tmeasday** [comment]
@chip I'm not totally sure how to debug the tool like this, I see similar problems. I'll try and find out more.

**Comment by hwillson** [comment]
The cause of this issue has been explained in https://github.com/meteor/meteor/issues/6863#issuecomment-215236609 (case sensitivity issue in the repro). This doesn't seem to be a common problem (there has been very little interest in this issue), so wiring up a better error message in this case is very low on the priority list. As part of the on-going old issue cleanup process, I'll close this off. Thanks for reporting this originally!
