### ISSUE TITLE
1.3.2.2 contains two jquery versions

### ISSUE THREAD

**Issue by mxab** [meteor/meteor#6864]
Hi,

I created a fresh project and added jquery via npm and use it via `import jQuery from 'jquery'`.

The application has still the packages/jquery.js (1.11.2) but also in the modules.js the npm jquery version

See this basic project sample
https://github.com/mxab/meteor-jquery-issue

![screen shot 2016-04-20 at 12 03 36](https://cloud.githubusercontent.com/assets/1607547/14671304/616dbc94-06f1-11e6-8dbd-bac9b718d980.png)

![screen shot 2016-04-20 at 12 03 11](https://cloud.githubusercontent.com/assets/1607547/14671307/63734b76-06f1-11e6-9125-4438fa81df57.png)

**Comment by Ben305** [comment]
You have to remote the meteor package for `jquery`. This is still included in your sample.

**Comment by mxab** [comment]
@Ben305 I thought the idea of the 1.3.2 release was that it would then take the jQuery provided by the node modules. Also removing jquery from `packages` does not show any effect, I assume to some transitive dependency in in some other meteor package.

**Comment by abernix** [comment]
At the moment `blaze-html-templates` requires `jquery` itself.  Thus if you continue to use `blaze-html-templates` (or any other private/public package that uses `jquery` using the Atmosphere system) this will continue.

With your example, if you remove `jquery` and `blaze-html-templates` with `meteor remove`, you should see the second version go away.

I know there are efforts under way to fix this in Blaze, but don't remember where the ticket is right now (If you want to peek around, Blaze progress is happening over in https://github.com/meteor/blaze now)

**Comment by mxab** [comment]
@abernix have you seen this issue https://github.com/meteor/meteor/issues/6626 ? As far as I get it the meteor jquery package should detect jquery in the node modules and does not load the built in version, shouldn't it?

**Comment by bySabi** [comment]
You can make the trick creating a local 'jquery' that import already installed jquery module. For example: https://github.com/bySabi/neal-sample-meteor/tree/master/packages/meteor-jquery--module

Remember update version on meteor release updates.

**Comment by abernix** [comment]
If you install your own version of jQuery with NPM, it should be used.  If you don't find this to be the case, please reproduce in the latest version of Meteor and upload a reproduction repo to Github and provide the link.

Thanks!

#7202 (related)

**Comment by coagmano** [comment]
Is there a way to stop `meteor/jquery` from bundling version `1.11.2` to the browser when an npm version exists?

Can dynamic imports help here?
