### ISSUE TITLE
[1.3.2.3] Error trying to update

### ISSUE THREAD

**Issue by tcastelli** [meteor/meteor#6867]
***1 Upvote*** I was just trying to update to fix the observechanges #6849  problem and I get this message. I'm on a windows 10 x64 machine

```
meteor update --release=METEOR@1.3.2.3

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by rogerkirkness** [comment]
+1

**Comment by TimStorck** [comment]
I'm also experiencing this and also on 64bit Windows 10

+1

**Comment by ddeklerk** [comment]
@rogerkirkness Just an FYI, you don't need to reply with '+1' anymore, you can 'vote' by using the 'Add your reaction' button at the top right of a comment.

**Comment by tcastelli** [comment]
If you still have 1.3.2.2 installed, I have followed the proposed workaround https://forums.meteor.com/t/meteor-1-3-2-3-partial-install-on-windows/21788/10 and then updated to 1.3.2.4. It seems to be working ok under windows (the update takes a long time as always)
