### ISSUE TITLE
"mt-os.windows.x86_32\meteor.bat" is not recognized

### ISSUE THREAD

**Issue by GrushinEgor** [meteor/meteor#6869]
***1 Upvote*** Since 1.3.2.3 I'm getting this error
![image](https://cloud.githubusercontent.com/assets/6255315/14685900/2fe7435e-073f-11e6-8c0c-02d460350612.png)

The PATH variable has no backslash at the end of meteor path

There meteor.bat file
![image](https://cloud.githubusercontent.com/assets/6255315/14685880/1c0ae11a-073f-11e6-8b00-3c2bcd7dc0f7.png)

Even trying to edit meteor.bat with removing backslash before 'packages' path.

**Comment by nizulzaim** [comment]
Same here :+1:

**Comment by briarfox** [comment]
Same issue as well.

**Comment by nathantreid** [comment]
Same here - you submitted yours while I was busy typing mine up: #6870

**Comment by rogerkirkness** [comment]
+1

**Comment by GrushinEgor** [comment]
Trying to reinstall to 1.3.2.4

**Comment by GrushinEgor** [comment]
Reinstall meteor has solved the problem

**Comment by nizulzaim** [comment]
how can i reinstall? delete meteor and install again?

**Comment by GrushinEgor** [comment]
@nizulzaim  Yep, through Control Panel

**Comment by GrushinEgor** [comment]
Now  I'm getting this error
![image](https://cloud.githubusercontent.com/assets/6255315/14687204/ee3f5468-0744-11e6-911b-22daab989eff.png)

**Comment by rogerkirkness** [comment]
+1 to same error when I try to run Meteor project. Sitting duck...

**Comment by tcastelli** [comment]
meteor show METEOR lists 1.3.1 as the latest recommended so I guess there were still problems with 1.3.2.4

**Comment by GrushinEgor** [comment]
Nothing helped me

**Comment by GrushinEgor** [comment]
Solution that helped me:
1. Remove pbastowski:angular-babel from \AppData\Local\.meteor
2. Run meteor update --release METEOR@1.3.1
3. Run meteor in project folder

**Comment by timbarclay** [comment]
I'm still having this issue. Meteor doesn't show up in control panel so I'm not sure the best way to delete it and reinstall it.

If I try and run any `meteor` command I get the message:

    H:\Documents\Other stuff\project>meteor --release 1.3.1
    '"C:\Users\tbarclay\AppData\Local\.meteor\.meteor\\packages\meteor-tool\1.3.2_3\mt-os.windows.x86_32\meteor.bat"' 
    is not recognized as an internal or external command, operable program or batch file.

**Comment by nickgermaine** [comment]
Updating meteor for me isn't an option right now as I'm using react, and updating meteor while using these packages is a nightmare.

So I was going to try uninstalling/reinstalling meteor, however, the meteor uninstaller has been stuck at about 25% for a while now...

**Comment by csergiu** [comment]
same thing as @nickgermaine after uninstalling and installing again the installation gets stuck at about 25%... Windows 10 x64

**Comment by nickgermaine** [comment]
I managed to get it reinstalled, it's downloading meteor tool, just waiting to see if I can get it up and running again.

**Comment by rogerkirkness** [comment]
I wanted to confirm that I had this issue, and uninstall/reinstall followed by running `meteor update --release=METEOR@1.3.2.4` now works with the updated functionality and no bugs so far.

**Comment by nickgermaine** [comment]
Confirmed: Uninstalling/reinstalling restores functionality to meteor.
