### ISSUE TITLE
[1.3.2.3] meteor.bat is not recognized as an internal or external command, operable program or batch file. (Windows)

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#6870]
I'm running Windows 10 x64, and just trying about go about my normal day working on some 1.2.1, 1.3.1 and 1.3.2.2 projects, but the Meteor 1.3.2.3 tool keeps downloading and breaking my Meteor installation.

Once the tool downloads, any attempt to launch Meteor results in the message `'"C:\Users\nathantreid\AppData\Local\.meteor\\packages\meteor-tool\1.3.2_3\mt-os.windows.x86_32\meteor.bat"' is not recognized as an internal or external command,
operable program or batch file.`
The only contents of the `mt-os.windows.x86_32` directory are the following:

- dev_bundle/
- isopackets/
- .git_version.txt

Deleting the directory (which requires some run-around since the paths are too long for Windows to delete normally) and setting the `AppData\Local\.meteor\meteor.bat` file to use 1.3.2.2 allows me to run Meteor again, but then 1.3.2.3 re-downloads and I have to go through the whole process again.

**Comment by tcastelli** [comment]
IF you still have 1.3.2.2 installed you can try this workaround and then update to 1.3.2.4
https://forums.meteor.com/t/meteor-1-3-2-3-partial-install-on-windows/21788/12

**Comment by nathantreid** [comment]
Yep, that fixes it for me!
