### ISSUE TITLE
Is Meteor 1.3.x stable yet?

### ISSUE THREAD

**Issue by aayushkapoor206** [meteor/meteor#6873]
I have been using meteor to build a very simple app and the updates have been flowing! I see many issues with each version number, even the latest. I was wondering when version 1.3.x will go stable?

**Comment by abernix** [comment]
@aayushkapoor206 1.3 is stable. If you have specific issues, please [discuss them on the forums](//forums.meteor.com) and if they turn out to be issues, open detailed issue tickets here.

**Comment by talha-asad** [comment]
I think meteor just needs a little more tests to make sure everything is working properly with some of the edge cases.

**Comment by stubailo** [comment]
Please feel free to contribute new tests!
