### ISSUE TITLE
Feature request: contains() method in a publication

### ISSUE THREAD

**Issue by bradvogel** [meteor/meteor#6876]
We use the "low level" publications APIs `this.added`, `this.removed`, and `this.changed` to manage documents on the client in response to redis notifications (we use Redis instead of the Mongo oplog for performance).

In determining which publication CRUD method to call, we need to know if the document has already been received - something the publication already tracks through its private `_documents` object. It would be nice if this were exposed publicly, perhaps in the form of a `this.contains(docId)` method on the publication.

Right now it can be polyfilled with the following code.

``` js
Meteor.publish('mypub', function() {

  // Polyfill for https://github.com/meteor/meteor/issues/6876
  this.contains = id => {
    id = this._idFilter.idStringify(id);
    return Boolean(this._documents.mycollection && this._documents.mycollection[id]);
  };

  onRedisInvalidationNotification(doc => {
    if (!this.contains(doc._id)){
      this.added('mycollection', doc._id, doc);
    } else {
      this.changed('mycollection', doc._id, doc);
    }
  })
});
```

Are you open to me filing a PR to add this?

**Comment by mitar** [comment]
I think it would be simply better if Meteor would be less strict about calling `added` and would simply convert it to `changed` automatically. I am not sure if API to expose internal state of mergebox is a good idea. But on the other hand, maybe it is. Maybe a better approach to access and manipulate its state could be helpful.

I am doing something similar to what you are describing here: https://github.com/peerlibrary/meteor-reactive-publish/blob/master/server.coffee#L135

But I wonder if this has to be something Meteor provides. This could also be a package, especially because it is a two-liner.

**Comment by bradvogel** [comment]
> I think it would be simply better if Meteor would be less strict about calling added and would simply convert it to changed automatically.
Yes, that would work too. Or perhaps a new `upsert` method.

> But I wonder if this has to be something Meteor provides. This could also be a package, especially because it is a two-liner.
If it were a package, it'd be just as brittle because it's reading private properties in Meteor. So I'd like Meteor to expose an API for it.

**Comment by mitar** [comment]
> If it were a package, it'd be just as brittle because it's reading private properties in Meteor. So I'd like Meteor to expose an API for it.

Not necessary. Because then only that package has to be updated and all others who depend on it continue to works.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Feature%20request%3A%20contains()%20method%20in%20a%20publication&body=Migrated%20from:%20meteor/meteor%236876) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
