### ISSUE TITLE
[1.3] Docs should clearly mention "server-side" for Promise.await().

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6878]
The docs here:

http://guide.meteor.com/using-packages.html#promises

show an example of `Promise.await()`. People won't get the expected results when they try this on the client side.

My first suggestion would be to make sure it clearly states that this is for the server-side.

A better suggestion would be to change the example to `async`/`await`, as that will work on both sides.

```js
async function sendTextMessage() {
  const promise = client.sendMessage({
    to:'+16515556677',
    from: '+14506667788',
    body: 'Hello world!'
  });

  // Wait for and return the result
  return await promise;
}
```

**Comment by benjamn** [comment]
@tmeasday I would strongly prefer that we change the example so that it doesn't rely on `Promise.await`, since that's never going to work on the client, as @trusktr points out.

**Comment by tmeasday** [comment]
@benjamn can you sanity check https://github.com/meteor/guide/commit/6a02b84cdc9db69580a192e7c6146e3a3078023e

**Comment by tmeasday** [comment]
Thanks @trusktr, this was a good point.
