### ISSUE TITLE
[1.3] Errors via promises/await statements show irrelevant stack trace.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6879]
I've got some code like this:

``` js
function doSomethingAsync(userId) {
  let resolve = null
  let reject = null
  const promise = new Promise((r,e) => {resolve = r; reject = e})

  Meteor.call('error-throwing-method', function(err, resule) {
    if (err) reject(err)
  })

  return promise
}

async function someFunction() {
  await doSomethingAsync()
}

someFunction()
```

When the promise is rejected, I see an error in the Chrome console that shows the error's message, but the stack trace is completely irrelevant to my code:

![screen shot 2016-04-21 at 6 55 10 pm](https://cloud.githubusercontent.com/assets/297678/14729431/9fed2a66-07f2-11e6-9a7a-4c7bb1d4c3ad.png)

The Meteor.method error in my example comes from the backend (the method does not exist on the client).

**Comment by trusktr** [comment]
Hang on, double checking the cause

**Comment by trusktr** [comment]
Yep, the problem is as described.

So, ifmodify `someFunction` like this:

```js
async function someFunction() {
  console.log('foo')
  await doSomethingAsync()
}
```

then if the `console.log('foo')` statement shows as line `foo.js:2`, then I'd expect the stack trace for the error on the next `await doSomethingAsync()` to show `foo.js:3`.

**Comment by trusktr** [comment]
I can confirm that if I wrap the `await` statement with try/catch and re-throw the error myself, then the stack trace becomes much more relevant:

```js
async function someFunction() {   // 1
  try {                           // 2
    console.log('foo')            // 3
    await doSomethingAsync()      // 4
  }                               // 5
  catch(e) {                      // 6
    throw new Meteor.Error(e)     // 7
  }                               // 8
}                                 // 9
```

and in this case, the error shows `foo.js:7`, something like

![screen shot 2016-04-21 at 7 21 31 pm](https://cloud.githubusercontent.com/assets/297678/14729905/c1d22e48-07f6-11e6-9d5f-70a6c715f96c.png)

I replaced the actual file in the image with `foo.js:7` to show the effect. The other lines in the stack trace are still irrelevant to my code, but at least the line in question is in the stack trace which makes debugging easier. it'd be nice if it was at least like this without the try/catch.

**Comment by trusktr** [comment]
Noting that https://github.com/meteor/meteor/issues/7076 is probably paired with this one.

**Comment by abernix** [comment]
@trusktr Is this resolved?

**Comment by abernix** [comment]
Closing as likely-resolved, but also for inactivity.  Happy to reopen if this is still a problem!
