### ISSUE TITLE
https://guide.meteor.com/v1.2/ is broken

### ISSUE THREAD

**Issue by zzaacchh** [meteor/meteor#6884]
Selected 1.2 from the dropdown version menu on https://guide.meteor.com/ .  Produces this error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F7BE935559DA9F95</RequestId>
<HostId>
lopPM9nMDF7Nv/eroOGImYO+R+59/wm2kzVLvr+gy9e873wvk8ti8Susvm0+WWWfr6Vwv+ES7k4=
</HostId>
</Error>

**Comment by lorensr** [comment]
Indeed it is 😊 Please resubmit to the Guide repo: https://github.com/meteor/guide/issues

**Comment by helfer** [comment]
Thanks for reporting this @zzaacchh , it's now fixed thanks to @tmeasday.
