### ISSUE TITLE
When I use import in client in lib folder, the program cannot find imported module

### ISSUE THREAD

**Issue by Jerret321** [meteor/meteor#6885]
Meteor Version: 1.3.2
NodeJS Version: 0.10.41

When I use import module in lib folder on the client, some error occur:

```bash
Error: Cannot find module '/imports/client/pages/authority'
W20160424-00:14:11.143(8)? (STDERR)     at require (packages/modules-runtime.js:95:19)
W20160424-00:14:11.143(8)? (STDERR)     at meteorInstall.lib.common.js (lib/common.js:1:1)
W20160424-00:14:11.143(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160424-00:14:11.143(8)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160424-00:14:11.143(8)? (STDERR)     at /Users/huangjiangtao/Places/Code/Hex/hexpm/.meteor/local/build/programs/server/app/app.js:12547:1
W20160424-00:14:11.143(8)? (STDERR)     at /Users/huangjiangtao/Places/Code/Hex/hexpm/.meteor/local/build/programs/server/boot.js:283:10
W20160424-00:14:11.143(8)? (STDERR)     at Array.forEach (native)
```

how can I avoid lib folder load twice or how can I only import module on the client ??

**Comment by benjamn** [comment]
Can you provide a few more details?
* What is the full path (within the app) of the file that imports the module?
* What is the full path of the `authority` package?
* What is the `import` statement you're using?

Without that information, I would guess that you might need to use a relative path.

**Comment by Jerret321** [comment]
the module `authority` is `authority.js` without other file extension. When the module is placed in `lib` folder and under `client` folder,  I think it is running in the server and errors occur. So I had to change the module location to `lib/common/authority.js` and everything is ok. I will close the issue. 

I think `Meteor` can support like this: 

```javascript
if(Meteor.isClient){
    import '/imports/client/pages/authority.js'
}
```
