### ISSUE TITLE
Clarify Cordova package add options

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6886]
> Meteor requires either an exact version (e.g. phonegap-facebook-plugin@1.0.0), a Git URL with a SHA reference, or a local path.

Maybe I'm formatting the "Git URL with a SHA reference" incorrectly? Printing an example would help. Also, it looks like a fourth option is tarballs?

```
> meteor add cordova:com.phonegap.plugins.facebookconnect@git+https://github.com/Wizcorp/phonegap-facebook-plugin.git#544cc06b0968b32dae4a8f97c1b01a3d5c74a1b6
com.phonegap.plugins.facebookconnect: Meteor requires either an exact version (e.g. com.phonegap.plugins.facebookconnect@1.0.0), a Git URL with a SHA reference, or a local path.

> meteor add cordova:com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/544cc06b0968b32dae4a8f97c1b01a3d5c74a1b6
Added Cordova plugin com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/544cc06b0968b32dae4a8f97c1b01a3d5c74a1b6.
```

Related: https://github.com/meteor/meteor/pull/5562#issuecomment-152918630

Background: I'm upgrading to Meteor 1.3, and my `com.*` packages can no longer be found:

```
cordova:com.phonegap.plugins.facebookconnect  0.11.0
cordova:com.verso.cordova.clipboard           0.1.0
```

```
> meteor run ios
...
=> Errors executing Cordova commands:                                              

   While adding plugin com.verso.cordova.clipboard@0.1.0 to Cordova project:       
   Cordova error: Failed to fetch plugin com.verso.cordova.clipboard@0.1.0 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: Registry returned 404 for GET on https://registry.npmjs.org/com.verso.cordova.clipboard
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Clarify%20Cordova%20package%20add%20options&body=Migrated%20from:%20meteor/meteor%236886) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
