### ISSUE TITLE
[bug] Can't update meteor behind a proxy on Linux!

### ISSUE THREAD

**Issue by aadrian** [meteor/meteor#689]
Was trying to update meteor from 0.5.4 with:

> meteor update

behind a proxy, but it seems to give all the time:

> "Failed to download manifest."

This is quite unexpected since the system is setup correctly, wget and curl work too, and "npm", "bower" and all other dependency managers work without problems too behind the proxy.

Thanks in advance.

**Comment by daxpablo** [comment]
That's what worked for me:

export HTTP_PROXY="http://user:password@1.2.3.4:5678" && curl https://install.meteor.com/ | sh

**Comment by kenorb** [comment]
Same here.

```
$ meteor update
Failed to download manifest.
$ curl https://install.meteor.com
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
```
