### ISSUE TITLE
[idea] Using <script async defer> instead of placing scripts in the body.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6892]
It seems like code would be cleaner if we left scripts in the head, and use async and deferattributes to achieve essentially the same effect. So instead of

```html
<html>
    <head>
    </head>
    <body>
        <script src="..."></script>
        <script src="..."></script>
        <script src="..."></script>
    </body>
</html>
```

it'd be

```html
<html>
    <head>
        <script src="..." async defer></script>
        <script src="..." async defer></script>
        <script src="..." async defer></script>
    </head>
    <body>
    </body>
</html>
```

The only thing is that IE <10 doesn't support the attributes. But, maybe there's a solution for this. Meteor's initial payload can look like this, with only a single script tag (even in development):

```html
<html>
    <head>
        <script src="meteor-bootstrap.js" async defer></script>
    </head>
    <body>
    </body>
</html>
```

This script will do some quick detection to detect if the browser is likely to support `async` and `defer`. Then, there are two cases:

**Case 1, browser doesn't support the attributes:**

In this case the bootstrap (running synchronously) waits for the document to be ready, and then appends the script tags into the head.

**Case 2, browsers support the attributes:**

In this case, the bootstrap code loads asynchronously and is deferred until parsing of the document is finished, at which point it does what the bootstrap in the first case did, except this time it didn't need to explicitly wait for the document to be ready.

---

The end result of either case would be DOM that looks like

```html
<html>
    <head>
        <script src="meteor-bootstrap.js" async defer></script>
        <script src="..." async defer></script>
        <script src="..." async defer></script>
        <script src="..." async defer></script>
    </head>
    <body>
    </body>
</html>
```

and not cluttering the `<body>`.

But, in the end, is this effort worth it just for the benefit of not cluttering the `<body>`?

**Comment by laosb** [comment]
I'd suggest discussing this in https://forums.meteor.com . This can be a feature, but I don't think it's worth to do it. Closing and feel free to reopen if we got more +1s from forums.
