### ISSUE TITLE
How to redefind urls with accounts-password@1.1.8

### ISSUE THREAD

**Issue by Silence-wzy** [meteor/meteor#6893]
How to redefind urls with accounts-password@1.1.8

when i use accounts-password@1.1.4,I just overwrite AccountsServer.prototype.url to defind my urls

but with 1.1.8,it told me that AccountsServer is not defind.

I have no idea with it.

**Comment by StorytellerCZ** [comment]
According to the [guide](https://guide.meteor.com/accounts.html#email-flows) you are looking on something like this:
```javascript
Accounts.urls.resetPassword = (token) => {
  return Meteor.absoluteUrl(`reset-password/${token}`);
};
```

**Comment by Silence-wzy** [comment]
@StorytellerCZ
 
Thank you.

It works.
