### ISSUE TITLE
Can't connect to hidden secondary to pull reporting data?

### ISSUE THREAD

**Issue by Broham** [meteor/meteor#6896]
I have setup a hidden secondary MongoDB instance that I would like to read from for reporting purposes.  The problem that I have run into is that when I try to connect to the hidden secondary I get the error:

> Error: No primary found in set

Can I connect to this type of database instance using `RemoteCollectionDriver` as I am trying below?

The code I am using to connect now is:

    flirtDb = new MongoInternals.RemoteCollectionDriver("mongodb://1.1.1.1/myDB");

Output of `rs.status()`:

    {
    	"set" : "flirtReplica",
    	"date" : ISODate("2016-04-21T16:37:24.637Z"),
    	"myState" : 2,
    	"term" : NumberLong(1),
    	"syncingTo" : "10.0.0.175:27017",
    	"heartbeatIntervalMillis" : NumberLong(2000),
    	"members" : [
    		{
    			"_id" : 0,
    			"name" : "10.0.0.175:27017",
    			"health" : 1,
    			"state" : 1,
    			"stateStr" : "PRIMARY",
    			"uptime" : 2484535,
    			"optime" : {
    				"ts" : Timestamp(1461183860, 11),
    				"t" : NumberLong(1)
    			},
    			"optimeDate" : ISODate("2016-04-20T20:24:20Z"),
    			"lastHeartbeat" : ISODate("2016-04-21T16:37:24.389Z"),
    			"lastHeartbeatRecv" : ISODate("2016-04-21T16:37:24.389Z"),
    			"pingMs" : NumberLong(0),
    			"electionTime" : Timestamp(0, 0),
    			"electionDate" : ISODate("1970-01-01T00:00:00Z"),
    			"configVersion" : 3
    		},
    		{
    			"_id" : 1,
    			"name" : "10.0.0.134:27017",
    			"health" : 1,
    			"state" : 2,
    			"stateStr" : "SECONDARY",
    			"uptime" : 2485582,
    			"optime" : {
    				"ts" : Timestamp(1461183860, 11),
    				"t" : NumberLong(1)
    			},
    			"optimeDate" : ISODate("2016-04-20T20:24:20Z"),
    			"syncingTo" : "10.0.0.175:27017",
    			"configVersion" : 3,
    			"self" : true
    		}
    	],
    	"ok" : 1
    }

**Comment by abernix** [comment]
This seems basically the same as the other issue you opened a few days after it: #6934 

And again, looks to be solved if #6958 works out, correct?

**Comment by Broham** [comment]
@abernix yeah I added the second one when I knew what the problem was to determine if we should add support.  This can be closed out
