### ISSUE TITLE
What is Minimongo official repository to contribute??

### ISSUE THREAD

**Issue by stefanocudini** [meteor/meteor#6897]
I would like to implement the mongodb operator $within that now is not supported in Meteor client side queries... I think it's more useful and important!

Here I have not found the references to where are the official sources:
https://atmospherejs.com/meteor/minimongo

I must fork the main repository of meteor? which branch?

tnk
Stefano

**Comment by hakima** [comment]
I just know this sources: 
https://github.com/meteor/meteor/tree/devel/packages/minimongo

**Comment by laosb** [comment]
except Blaze for now, all core packages are under this repo.

**Comment by nickpolet** [comment]
Minimongo looks to be integrated fairly deeply at the moment, so cloning the whole repo will be the way to go with this.

https://github.com/meteor/meteor/tree/devel/packages/minimongo

Can this be closed as it's just locating sources?
