### ISSUE TITLE
Conflicting error messages when adding cordova plugin from git URL

### ISSUE THREAD

**Issue by ephemer** [meteor/meteor#6898]
Hi guys, just came across a strange and frustrating (but in the scheme of things minor) error:

Running the following command 'works', as in meteor lets you add the plugin:

`meteor add cordova:cordova-plugin-inappbrowser@https://github.com/ephemer/cordova-plugin-inappbrowser#04091fde737519c149e7ad6316971cb6b490c5b3`

but when you go to run meteor, it tells you that meteor doesn't support the old-style URLs, please use a normal Git URL with a SHA hash. Huh?? That's what I did.

After some playing around I saw you have to include `.git` at the end of the GitHub path (before the SHA hash). This seems arbitrary to me, because both URLs point to the same place. Also the error message is wrong and confusing. Either I shouldn't be able to add the plugin at all with the the first URL, or it shouldn't fail when running `meteor`.

Thanks

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Conflicting%20error%20messages%20when%20adding%20cordova%20plugin%20from%20git%20URL&body=Migrated%20from:%20meteor/meteor%236898) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
