### ISSUE TITLE
Full app test files inside /import directory not being eagerly loaded in full app testing mode

### ISSUE THREAD

**Issue by jfly** [meteor/meteor#6901]
***1 Upvote*** Files of the form `/import/*.app-test[s].*` used to be eagerly loaded by Meteor (and therefore, when running `meteor test --full-app --driver-package practicalmeteor:mocha`, my full app tests would run). This behavior was changed in https://github.com/meteor/meteor/commit/eb18d59faa1986d912a59bd57a4ecc03ba4b3572, which only eagerly loads test files when `global.testCommandMetadata.isTest` is true, but when running `meteor test --full-app --driver-package practicalmeteor:mocha`, `global.testCommandMetadata` is:

```
{ driverPackage: 'practicalmeteor:mocha',
  isAppTest: true,
  isTest: false }
```

It looks like https://github.com/meteor/meteor/commit/eb18d59faa1986d912a59bd57a4ecc03ba4b3572 made it into Meteor 1.3.2. When testing by hand, I see that my full app tests do run under Meteor 1.3.1, but not under Meteor 1.3.2.1 (I couldn't test Meteor 1.3.2 directly due to some bug in Meteor 1.3.2)

Am I correct in placing my full app tests under the `/imports` directory? The Meteor Guide says that tests should live in the imports directory alongside the relevant code, but it doesn't specifically mention full app tests. I looked to meteor/todos, and it *does* place its `*.app-test[s].*` files in the `imports/` directory. See [/imports/startup/client/routes.app-test.js](https://github.com/meteor/todos/blob/master/imports/startup/client/routes.app-test.js).

Once fix seems fairly straightforward, just change the `isTest` computation [here](https://github.com/meteor/meteor/blob/310d6df4ac2b411425c626094ed3d378206fee18/tools/isobuild/package-source.js#L1330-L1331) to account for `global.testCommandMetadata.isAppTest` as well as `global.testCommandMetadata.isTest`. I'll submit a PR with that change.

**Comment by jfly** [comment]
Oh! I forgot to mention: if you update meteor/todos from [Meteor 1.3](https://github.com/meteor/todos/blob/master/.meteor/release) to Meteor 1.3.2.1, then its full app tests won't run when you run `meteor test --full-app --driver-package practicalmeteor:mocha`.

**Comment by krstffr** [comment]
👍

**Comment by tmeasday** [comment]
This seems like an important bug @benjamn.

One thing though: The original guard in that file was correct I think -- it was making *all* files load lazily if `Meteor.isTest === true` (which isn't something you want to do if `Meteor.isAppTest === true`).

So there are two things that should happen that I suspect may have been conflated:

1. If `Meteor.isTest`:  all files that would ordinarily be eagerly loaded should not.
2. If `Meteor.isTest || Meteor.isAppTest`: A set of test files (`*.test.*` or `*.app-test.*) should be eagerly loaded (these files would ordinarily not be).

This is sort of confusing so we should be careful that we fix it properly.

**Comment by ramijarrar** [comment]
Can we get a patch release for this?

**Comment by tmeasday** [comment]
`1.3.3-beta.0` is out if you'd like to try that. I don't think we'd do a patch against 1.3.2 -- you could just downgrade to `1.3.1` if you don't want the beta.

**Comment by ramijarrar** [comment]
@tmeasday Yep, on the 1.3.3 beta at the moment. 

I don't think downgrading from 1.3.2 to 1.3.1 is really an option for most people considering some of the major additions such as support for importing style files in node_modules & the changes made to accomodate the official NPM jQuery package.

**Comment by tmeasday** [comment]
Sure; but we'll be doing the 1.3.3 pretty soon I think so hopefully there's a solution for everyone.

**Comment by bhaibel** [comment]
I'm experiencing this issue on 1.3.4.1.

The original reporter said that he was able to run the tests "by hand," but as I'm new to Meteor I have no idea what that means. Could someone point me to an appropriate documentation link?

**Comment by ChristopherLivett** [comment]
I've had similar issues, I've just scrapped working on full-app tests for now until things are made clearer and easier.  After this patch it seems like my application is eagerly loaded but I cannot see the results of any tests.

**Comment by tmeasday** [comment]
@bhaibel / @ChristopherLivett  I think maybe you are experience something different? I believe this issue was solved. Can we get a new issue with a reproduction of what you are seeing?

**Comment by bhaibel** [comment]
This issue describes what I was experiencing fairly exactly, with a different meteor version (again, 1.3.4.1). I have tests with filenames `[thing].app-test[s].js`. When I run `meteor test --full-app --driver-package practicalmeteor:mocha`, zero tests run.

**Comment by tmeasday** [comment]
@bhaibel are those files inside a directory named `tests/` ? Can you create a simple reproduction?
