### ISSUE TITLE
Update Meteor Guide with Font Best Practices

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#6903]
There are many unanswered questions surrounding the recommended font usage within a Meteor app.

* Where should fonts be placed in the project structure?
* How should they be imported / loaded in a Meteor 1.3+ app?

[According to the Meteor Guide](http://guide.meteor.com/mobile.html):

> An important benefit of packaging up your web app as a Cordova app is that all your assets are bundled with the app. This ensures your app will load faster than a web app running on a remote server could, which can make a huge difference for users on slow mobile connections.

Does this mean that fonts will be bundled as well, if they are not loaded from a CDN?

Hoping for some suggestions / answers, and to ultimately see this information make it to the Meteor Guide.

**Comment by rolivav** [comment]
I remember trying to import fonts with 1.2 bundling unsuccessfully. I ended up adding a CDN to the head and it worked pretty well like that. 
Now in 1.3 I import them with sass, which is ideal so you can control when they are loaded.

**Comment by skirunman** [comment]
You may want to close this issue here and open it on https://github.com/meteor/guide

**Comment by stubailo** [comment]
Yes, please open this issue on the guide repo!
