### ISSUE TITLE
Meteor crashes on 'Building the application'

### ISSUE THREAD

**Issue by selten** [meteor/meteor#6904]
Meteor versions: 1.2 and 1.3(.2.4), issue has been persistent for a few months now.
Platform: Windows 10
Packages:
- meteor-base             # Packages every Meteor app needs to have
- mobile-experience
- mongo
- blaze-html-templates
- session
- tracker
- es5-shim
- ecmascript
- accounts-password
- dburles:google-maps
- kadira:flow-router
- kadira:blaze-layout
- jeremy:geocomplete
- reactive-var
- http
- zimme:active-route
- okgrow:analytics
- sacha:spin
- check
- aldeed:collection2
- coffeescript
- msavin:mongol
- twbs:bootstrap
- jquery
- accounts-facebook
- service-configuration
- underscore
- jazeee:spiderable-longer-timeout
- bojicas:bootstrap-alerts
- email
- wylio:mandrill
- maveller:meteor-accounts-ui-bootstrap-3
- meteorhacks:aggregate
- tomwasd:flow-router-seo
- gadicohen:phantomjs
- random
- oleh:foursquare
- chfritz:easycron
- momentjs:moment
- herrhelms:meteor-leaflet-markercluster
- bevanhunt:leaflet
- meteorhacks:kadira
- nimble:restivus
- simple:json-routes
- standard-minifier-css
- standard-minifier-js
- themeteorchef:jquery-validation
- mdg:validated-method
- simple:rest

I expect Meteor to compile and build the application correctly and if that's not possible to tell me what is wrong.

> => Started proxy.
> => Started MongoDB.
>    Building the application                  \

Meteor instead crashes without any information (also not in debug).

**Comment by nickpolet** [comment]
Do you have the option to build the project on a linux or osx platform?

One of my colleagues had a similar issue while trying to build on windows, but his issues were resolved by switching to Ubuntu.

Have you tried deleting the .meteor/.local folder and rebuilding?

**Comment by selten** [comment]
We work in a team, it works for everyone else. It also works on Linux. I'm contemplating on switching to Ubuntu anyhow.

I'll try your suggestion.

**Comment by selten** [comment]
Jus tested removing .meteor/.local, doesn't fix the issue.

**Comment by chip** [comment]
Possibly related to #6859 and #5275.

**Comment by selten** [comment]
Unrelated to both those issues.
#6859: not a lot of imported files present, merely some packages and a bit of code.
#5275: doesn't hang on building, it actually crashes on building.

**Comment by laosb** [comment]
Can you come up with a minimal repro?

**Comment by selten** [comment]
Could you be more specific on what you are asking me to do?

**Comment by nickpolet** [comment]
Create a simple project that encounters the same errors you are having in your application. Or come up with a way to reproduce the error consistently. Either post a simple application on github (make sure there is no sensitive information in it) or create a list of steps to follow to get the same issues you are having.

**Comment by Sewdn** [comment]
I have the same issue.
Try to remove your leaflet dependencies (bevanhunt:leaflet).
It's a missing css file in that package I suppose
