### ISSUE TITLE
Eliminate phantomjs from dev bundle

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6905]
The `phantomjs` package is one of the largest npm packages in the dev bundle, at 45MB. It is currently only used in [Velocity tests](https://github.com/meteor/meteor/blob/d6288aceed339e01c120cc19e69308d0a3d8d80e/tools/runners/run-velocity.js#L4) and [self-tests](https://github.com/meteor/meteor/blob/d6288aceed339e01c120cc19e69308d0a3d8d80e/tools/tool-testing/selftest.js#L6), neither of which are commonly run by most Meteor developers. We should consider eliminating this dependency for the 1.3.3 release.

**Comment by laosb** [comment]
Good to see that.

**Comment by gadicc** [comment]
And spiderable... although if we expect users to install spiderable themselves on their deploy target, I think it's ok to ask them to do the same in devel (possible doc update somewhere...).  `meteor deploy` used to do this automatically, but Galaxy relies on prerender.io now anyways.

**Comment by laosb** [comment]
@gadicc Dev bundle shoudn't affect production deployment, I think?

**Comment by gadicc** [comment]
@laosb, correct :)  just saying that there are number of people who use `spiderable` without really understand the connection with `phantomjs`, which has been invisible until now (because it existed locally and if they deployed via `meteor deploy` or `mup` it would be there too).  but yeah in any case this only affects people who are testing spiderably locally; i'm just suggesting just half a sentence in the upgrade notice for their benefit :>

**Comment by laosb** [comment]
@gadicc So, should we just output a console message saying `PhantomJS not found. spiderable depends on phantomjs to run.`

**Comment by gadicc** [comment]
Yeah that would do it :)  And a mention in History.md, maybe:

```
* PhantomJS is no longer included in the Meteor dev bundle.  If you previously relied on this for local testing of spiderable, velocity tests or testing Meteor from a checkout, you should now install your own local copy.  See if your distribution has it's own 'phantomjs' package or download it from phantomjs.org.  (#6905)
```

**Comment by laosb** [comment]
@gadicc Mentioning the whole url instead of just issue number is better in console logs.

**Comment by trajano** [comment]
Actually if we had an easy and consistent way of using it for testing I wouldn't mind it.  So far if I follow the guide I have to make a choice of either `practicalmeteor:mocha` or `dispatch:phantom-mocha` if I had both packages in my app.  https://github.com/DispatchMe/meteor-mocha-phantomjs/issues/10

**Comment by Sanjo** [comment]
You can remove the whole run-velocity.js file. Velocity doesn't work with Meteor 1.3.x. We had a Meteor fork for Velocity and I stopped releasing with Meteor 1.3.

**Comment by aldeed** [comment]
What about run-selenium.js and the `selenium-webdriver` dep? I've never seen that documented and the one time I tried to figure out getting it to work, it didn't. Pretty sure that could be done as a separate test driver package now, like our mocha-phantomjs pkg, if it's needed.

**Comment by benjamn** [comment]
This is done in the version of the dev bundle that ships with `1.3.3-beta.0`.

If you still need PhantomJS, all you have to do is `meteor npm install -g phantomjs-prebuilt`.
