### ISSUE TITLE
Tiny Test fails - livedata stub - reconnect non-idempotent method

### ISSUE THREAD

**Issue by pmoons** [meteor/meteor#6906]
When checking out a commit as recent as [7012957a](https://github.com/meteor/meteor/commit/7012957a0d1f48c5b141e3e2a34fd450457a7d56), running tests will fail with the `livedata stub - reconnect non-idempotent method` message.

Meteor 1.3.2.4
No extra dependencies.
**Expected behavior**: I expected the tests to pass, but one fails.
**Steps to reproduce**: Check out that commit and run `meteor test-packages ./`

I believe this [line](https://github.com/meteor/meteor/blob/devel/packages/ddp-client/livedata_connection_tests.js#L780) is the culprit.  There is never any error received from the method call when the connection is reset.

**Comment by abernix** [comment]
I'll look at this.

**Comment by abernix** [comment]
This is fixed in `1.3.3-beta.0` and will be fixed in 1.3.3.  Try now with `meteor --release 1.3.3-beta.0`!
