### ISSUE TITLE
Proper import chain for Meteor packages

### ISSUE THREAD

**Issue by gadicc** [meteor/meteor#6907]
In [modules/install-packages.js](https://github.com/meteor/meteor/blob/83c2f7a790dbf13f45a153ed5320f4692e706b41/packages/modules/install-packages.js) we have:

```js
  meteorDir[name + ".js"] = function (r, e, module) {
    module.exports = Package[name];
  };
```

Would it be possible to get something like this instead:
```js
  meteorDir[name + ".js"] = [mainModule, function(require, e, module) {
    module.exports = require(mainModule);
  }];
```

This is important for hotloading for updates to flow down correctly, and required for the new version of the original react-hot-loader package (although there is a [workaround](https://github.com/gaearon/react-hot-loader/issues/259) that can be used to catch the update in each individual package too).  And I guess affects possible bundle analysis in the future.

cc: @benjamn as usual :)

I'd say if you tell me that the name of the `mainModule` is already available in `computeJsOutputFilesMap` somewhere I'll submit a PR for this, except I already owe you a much simpler PR from like two weeks ago :(

**Comment by gadicc** [comment]
I think we can just track this via the PR.

**Comment by abernix** [comment]
Let's actually leave it open until resolved, per policy for FRs. :wink:
