### ISSUE TITLE
How can I get all my child template had rendred in the parent template?

### ISSUE THREAD

**Issue by Micjoyce** [meteor/meteor#6909]
//parent
<template name="parent">
  {{#each lists}}
    {{> child}}
  {{/each>
</template>

//child
<template name="child">
 {{name}}
</template>

How can I get all of child template has renderd at parent template onRendered function.

Hope some one can help me!

**Comment by talha-asad** [comment]
You should post this on the forums

**Comment by laosb** [comment]
Yah, as @talha-asad , forums.meteor.com is a better plaze for this. Closing.
