### ISSUE TITLE
Cannot call import for amqplib in meteor 

### ISSUE THREAD

**Issue by ramzauchenna** [meteor/meteor#6910]
I am trying to import the amqp package with 

> import { amqp } from 'amqplib'

i get the following error message 

```
   While building for os.linux.x86_64:
   node_modules/amqplib/lib/connection.js:164:9: Unexpected token (164:9)
   node_modules/amqplib/lib/channel_model.js:322:11: Unexpected token (322:11)
   
   While computing assigned variables:
   node_modules/amqplib/lib/connection.js: Unexpected token (164:9)
   node_modules/amqplib/lib/channel_model.js: Unexpected token (322:11)
```
This currently works with Npm.require but not with import

**Comment by aiserg** [comment]
@ramzauchenna I've just renamed `await` in files and it started work
https://github.com/squaremo/amqp.node/issues/251

**Comment by dimofte** [comment]
I had the same problem with meteor, made a _temporary_ fork - see [this comment](https://github.com/squaremo/amqp.node/issues/251#issuecomment-222632582)

**Comment by abernix** [comment]
I believe this is fixed in the latest version of `amqplib`.  Either way, this appears to be a bug in that library and it would need to be fixed there.  Closing.
