### ISSUE TITLE
Meteor should not hide errors that have `expected` set

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#6912]
livedata allows tests to set `expected` on an error so that it isn't displayed:

https://github.com/meteor/meteor/blob/4e81417281a371ad93f9191dfc3bfaf7f6cb7124/packages/ddp-server/livedata_server.js#L1671

However, in production, ordinary errors can have the `expected` field set.  For example, the standard Node `assert` module sets the `expected` field on assertion errors.  This makes it hard to track down bugs when the error is silently suppressed.

Meteor should use a different field for tests, such as for example `_expected_by_test`.

**Comment by laosb** [comment]
Totally should be.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20should%20not%20hide%20errors%20that%20have%20%60expected%60%20set&body=Migrated%20from:%20meteor/meteor%236912) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by awwx** [comment]
> This feature request will be closed here

This is a bug.

Where does it go as a bug?

**Comment by hwillson** [comment]
@awwx - it can stay right here. Re-opening (and removing the previously added `feature` label). Thanks for pointing this out!

**Comment by laosb** [comment]
My fault for having the wrong label. Sorry!
