### ISSUE TITLE
[Crosswalk] Cordova Apps getting destroyed quickly by app, thus restarting on next access

### ISSUE THREAD

**Issue by DanielDornhardt** [meteor/meteor#6913]
Hello everybody,

while playing with different reload-on-resume and the new Reloader - Package, I now finally found out why none of those would fix our issue: They weren't the ones causing the reloads on every task-switch - it was the Android OS, quickly ending (destroying?) ([Android lifecycle docs](http://developer.android.com/training/basics/activity-lifecycle/index.html)) the app almost immediately after switching away from it to another slightly memory intensive app (eg. "Gmail" or something similar, or another Meteor Crosswalk App), thus forcing a restart when returning to our app.

Now the thing is, I understand the need for the OS to free the memory and everything. The thing is though: We'd like to allow the user to switch away for a few seconds, eg. to copy a password from an Email or something like this, and when coming back, not having the user to fill in his username again / navigate to the right place again because the app restarted immediately.

And also we'd prefer not to do a lot of lifecycle management ourselves inside of our app, as that seems to be a whole new can of worms we wouldn't like to get into if it's not necessary :D

Is there anything we can do? Some mobile-config.js - setting we could provide perhaps, or some Cordova-API we could use for this?

Actually that's kind of a real problem for meteor apps I start thinking now, because the reload always takes some time with Meteor Apps anyway, and if we add another few seconds for something like Reloader - it quickly could become rather painful to build something the user would like to go back and forth to for some reason or another.

Sorry that this is a more open question which might not be 100% apt for this bugtracker, we thought that this might be of enough of a general interest item to have an eye on for the meteor cordova components overall. Or maybe even something for the guide?

The device used for testing was mainly an LG G2 (32 GB / 2 GB Ram).

Thank you for your Feedback.

PS: [I cross-posted this to the forums too](https://forums.meteor.com/t/crosswalk-cordova-apps-getting-destroyed-quickly-by-app-thus-restarting-on-next-access/22126) to cast a wider net for possible ideas and potential feedback.

**Comment by pmwisdom** [comment]
@DanielDornhardt Meteor-wise there isn't all that much you can do config-wise to force your application to stay alive. You can try to lower your memory consumption while in the background, or you can try this plugin that I have used in the past. https://github.com/katzer/cordova-plugin-background-mode. That should get you about 10 minutes of "background time".

**Comment by influxa** [comment]
Hi Daniel, did you ever get this issue resolved? I find myself encountering this problem on a project I am working on, specifically for Android. Would like to hear your thoughts on how you went about this.

**Comment by DanielDornhardt** [comment]
Hi @influxa, there are some / different workarounds possible. In [the forum discussion [link]](https://forums.meteor.com/t/crosswalk-cordova-apps-getting-destroyed-quickly-by-app-thus-restarting-on-next-access/22126/7) linked above there's some ideas, mainly to stop any background activity on the cordova pause / backgrounding events, I don't know exactly which are the best, but there's more about it in the cordova docs. One thing you could try is doing a meteor.disconnect() to make meteor stop any background activity if new data arrives in the background.

The other option to try may be the [cordova-plugin-background-mode](https://www.npmjs.com/package/cordova-plugin-background-mode), which keeps the app open for longer in the background. Maybe also these two approaches combined? This seemed to work well with android, not so well with iOS for me (the app didn't really run in the background on iOS I think), but I am not sure whether this would be an issue for the google play store maybe. If it would be for the apple store you may actually be able to build two separate versions, one with the plugin and one without...? I never tried that actually.

A third option I use for a timer-style app (which is actually a slightly different issue where I want my app to alert the user after some amount of time) is to use the local notification package to post a notification at a specific time if the user would have left the app, if he's still in the app he won't receive the notification. But this is, as I said, a slightly different use case: [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).

Finally it seems that this issue was a problem on my own phone mostly. I don't know if it was because it is a bit older now (LG G2), or a thing with my specific android version or anything else, but it turned out that others didn't have as big an issue as I had myself on my phone. Maybe try it on some other phones as well? :D

LAST BUT NOT LEAST if it's the mdg:camera package you have trouble with maybe see if you can patch it / fix it / find a fixed fork which works for you to not use the very memory - intense communication method MDG was forced to use when they originally implemented the camera package but instead uses a local file to store the image and access it from there, which should be possible since the great Cordova rewrite which came with Meteor 1.3.

That's all I know... I hope something in there will help you out a bit. Sorry, no clear-cut solution yet. I will keep you posted if I ever find out more. And please do report back if you find out anything new! :)

**Comment by hwillson** [comment]
Since this discussion is open-ended and can't really be pegged as either a bug or a feature request, I'll close this issue. Continuing the discussion via the [Meteor Forums](https://forums.meteor.com/t/crosswalk-cordova-apps-getting-destroyed-quickly-by-app-thus-restarting-on-next-access/22126/7) make sense. That being said, thanks for originally opening this and the interesting discussion!
