### ISSUE TITLE
Date.now() returns incorrect value on server

### ISSUE THREAD

**Issue by RayVR** [meteor/meteor#6920]
Meteor 1.3.2.4: Date.now() output 29100768797
 jsfiddle output 1461775629314

Meteor 1.2 returned correct values.

**Comment by abernix** [comment]
```
$ meteor shell
> Meteor.release
'METEOR@1.3.2.4'
> Date.now()
1461776315064
> 
```
@RayVR I believe this is isolated to something that your project or it's packages must be doing.  Definitely not affecting my projects and would have certainly caused a lot of problems by now. If you still think it's a reproducible problem, you should make a test meteor repo and submit it with your issue.

**Comment by RayVR** [comment]
I'm not able to post any code to github. I just ran
meteor create test-project
meteor npm install
meteor

then started meteor shell. The same issue exists. This is the output of meteor list:
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.4.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.5.10  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
jquery                 1.11.8  Manipulate the DOM using CSS selectors
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.7  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.9  Reactive variable
standard-minifier-css  1.0.6  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.0.6  Standard javascript minifiers used with Meteor apps by default.
tracker                1.0.13  Dependency tracker to allow reactive callbacks

**Comment by RayVR** [comment]
> Meteor.release
'METEOR@1.3.2.4'
> Date.now()
383663171

**Comment by abernix** [comment]
@RayVR, and what if you type `date` on your command line?  What OS are you on?

**Unix**
```
$ date
Thu Apr 28 08:44:17 EEST 2016
$ date +%s
1461822258
```

**Comment by RayVR** [comment]
`
$ date +%s
1461850488
$ date
Thu Apr 28 09:40:04 EDT 2016
`
`
$ python -c "import time; print time.time()"
1461850558.27
`
`
$ node
> Date.now()
29176515065
`
`
$ meteor shell

> Meteor.release
'METEOR@1.3.2.4'
> Date.now()
29176669493
`

**Comment by abernix** [comment]
Wow.  Ok.  Well, at least that points in the direction of `node` and not `meteor`.  The time is advancing at the correct rate (21 hours, 2 minutes and 27 seconds between the timestamps in your posts), but it's offset significantly (i.e. it's in 1970).  I don't have any more ideas, myself.

**Comment by RayVR** [comment]
Thank you for the information. 
Do you have any idea how the Date object calculates/retrieves the time? Perhaps it's a problem with node and my OS (CenOS 6.5)
I tried the same test with a different version of node (0.12.7) and the result is the same.

**Comment by RayVR** [comment]
```
> Date(2014, 3, 3, 12, 20, 10, 100)
'Fri Dec 04 1970 13:03:43 GMT-0500 (EST)'
```

**Comment by abernix** [comment]
Heh, yea, that's just wrong.  10 years ago I might have told you to check your CMOS battery. 😸

I'm not sure about the node Date internals.  It uses the V8 engine which must be incorrectly integrating with your (rather old) kernel – CentOS 6.5 is a bit dated.  I would at least upgrade it to the latest point release and you might see this resolve itself.

**Comment by abernix** [comment]
Just out of curiosity, what node version were those first timestamps from? `node -v`?

**Comment by abernix** [comment]
It's probably not much consolation but I fired up my 32-bit CentOS 6.5 LiveCD with no updates in a VirtualBox and it worked fine. 😞  (`uname -r` = `2.6.32-431.el6.i686`)  I do feel like this is isolated to something with your local environment though so not sure there is anything Meteor can do.

**Comment by RayVR** [comment]
node versions are 0.10.40 and 0.12.7

Appreciate the help. I agree this must be an issue with the system I'm on. The node binary is accessible from multiple machines (stored on NFS) and the output varies per machine. Building node from source now to see if it's a problem with a shared library.

**Comment by abernix** [comment]
I'd venture to guess it's outside of the node binary and something with the machine's kernel.  Meteor bundles its own version of `node` (which in 1.3 you can invoke with `meteor node`), I'm almost certain you'll find the same result there.

Also, friendly reminder, Meteor 1.3 is with node `0.10.43` whereas 1.2 was `0.10.40`.

**Comment by RayVR** [comment]
@abernix thanks for the help. I'll close this issue but continue to update.

**Comment by RayVR** [comment]
Could you post the version of GCC you're using on the centOS live cd?

**Comment by abernix** [comment]
I didn't compile it or have any dev essentials installed.  Just used the
rpm from nodesource rpm archives.

https://rpm.nodesource.com/pub/el/6/

**Comment by RayVR** [comment]
so the values for Date.now() vary from machine to machine. It turns out the values are exactly the uptime on each server. 

We have a time synchronization system running which seems to be breaking the Date.now() call.

**Comment by abernix** [comment]
Sounds the same as [this CentOS forums issue](https://www.centos.org/forums/viewtopic.php?f=14&t=48822).  Good luck!
