### ISSUE TITLE
Issues not being closed

### ISSUE THREAD

**Issue by westlakem** [meteor/meteor#6924]
My issue is that issues are not being closed in the issue tracker.  This makes it look at a glance that Meteor is a high risk project due to 1,100 issues.  Please close out issues that are no longer valid so sites that use githubs interface for "code health" doesn't give the project a critical rating

**Comment by abernix** [comment]
😢 This is being discussed on the forums and is a pinned-topic this week.

https://forums.meteor.com/t/community-help-with-issue-triage/21805/7

Self-closing your issue and discussing there would be a great way to help the project.

**Comment by stubailo** [comment]
Yes, please discuss on that thread!
