### ISSUE TITLE
Providing already built assets and bundle js to meteor

### ISSUE THREAD

**Issue by lucidprogrammer** [meteor/meteor#6928]
For various reasons and use cases for a current project, I used an approach where the server is in meteor and the client is in webpack. 

Everything works fine in development. The server is running in meteor and the client developers can develop without hassle with webpack bundling. 
Webpack creates the bundle js file and assets(css and fonts etc).
Is there an easy way to create the program.json ("format": "web-program-pre1" etc) where I just supply the already built js file and assets.
(for deploying as a node application)

**Comment by rogeriojlle** [comment]
WebAppInternals.staticFiles['/__browser/manifest.json'].content
