### ISSUE TITLE
Github Milestone Cleanup

### ISSUE THREAD

**Issue by StanLindsey** [meteor/meteor#6929]
I noticed that there are a couple of old releases in the Github Milestones that could be closed for brevities sake; 'Release 1.2.1' and 'Release 1.2.0.2' have 100% complete issues.

Also theres some older issues in Release 1.2 which I'm not sure are relevant anymore?

**Comment by laosb** [comment]
@meteor

**Comment by abernix** [comment]
This was mostly taken care of by someone and work is continuing on issue triage – some issues remain, but everything you mentioned is gone.

So closing this issue so work can continue on that streak. :)

<img width="313" alt="screen shot 2016-05-09 at 6 43 10 pm" src="https://cloud.githubusercontent.com/assets/841294/15118672/f2fc53ae-1615-11e6-9c17-fb3f99b52119.png">
