### ISSUE TITLE
Meteor build system slow in 1.3

### ISSUE THREAD

**Issue by cjh9** [meteor/meteor#6930]
What has happened with the build system in version 1.3? It was originally very slow, but after the last update it has increased to almost 10 seconds for a dummy simple app with only a few react views. The feedback loop is too slow, also the whole site is refreshed after an update.

I really love meteor, but I can't use it because of this. I will opt for Webpack solution, with hot-code-reload instead. It only takes 0.6 seconds to rebuild the same app, and the state in the browser is preserved.

When using Webpack it also says how long the rebuild took in seconds, i can't see that information when using meteor.

Hope this will be fixed soon, I really hope meteor will succeed.

**Comment by clayne11** [comment]
Meteor has a community hot-reloading solution you can try: https://github.com/gadicc/meteor-hmr

**Comment by dcworldwide** [comment]
Same scenario for me. I've worked on a startup for 12 months with this issue, when I think of all the lost productivity waiting for builds and deploys to complete I'm depressed :( I've had to move to Web pack.

**Comment by laosb** [comment]
Will take a look if I can reproduce. You didn't mention the details. We've received many issues reporting this, and I think MDG has done something to improve. 

As there is no detailed info, I'm closing this and please report if you see something we could change clearly to improve the speed.

**Comment by Hedgepig** [comment]
Builds can take up to 10 mins. Here is my profilling

https://gist.github.com/Hedgepig/a33fea315e9bc6e05e8f90bdc66b8707

Here is the package.json
```
{
  "name": "app",
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "install-redux": "npm i --save react-redux redux redux-logger redux-thunk && mv imports/.redux imports/redux",
    "lint": "eslint .",
    "storybook": "start-storybook -p 9001",
    "test": "jest"
  },
  "jest": {
    "automock": false
  },
  "author": "Matthew Laws",
  "private": true,
  "dependencies": {
    "apollo-client": "^0.4.19",
    "apollo-server": "^0.3.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "bcrypt": "^0.8.7",
    "body-parser": "^1.15.2",
    "datamaps": "^0.5.7",
    "express": "^4.14.0",
    "faker": "^3.1.0",
    "fbjs": "^0.8.3",
    "figlet": "^1.2.0",
    "graphql": "^0.7.1",
    "graphql-tag": "^0.1.14",
    "graphql-tools": "^0.7.2",
    "highland": "^3.0.0-beta.3",
    "http-proxy-middleware": "^0.17.2",
    "immutable": "^3.8.1",
    "jquery": "2.2.4",
    "keymirror": "^0.1.1",
    "less": "^2.7.1",
    "meteor-node-stubs": "^0.2.3",
    "moment": "^2.14.1",
    "mysql": "^2.11.1",
    "object-assign": "^4.1.0",
    "radium": "^0.18.1",
    "rc-slider": "^5.1.1",
    "react": "^15.3.0",
    "react-addons-perf": "^15.2.1",
    "react-addons-pure-render-mixin": "^15.3.0",
    "react-addons-test-utils": "^15.2.1",
    "react-apollo": "^0.5.7",
    "react-autosuggest": "^6.0.4",
    "react-bootstrap": "^0.30.3",
    "react-bootstrap-typeahead": "^0.9.2",
    "react-datepicker": "^0.29.0",
    "react-dom": "^15.2.1",
    "react-dual-rangeslider": "^1.2.15",
    "react-komposer": "^1.13.1",
    "react-month-picker": "^1.0.12",
    "react-mounter": "^1.2.0",
    "react-router": "^2.8.1",
    "react-tag": "^2.2.7",
    "react-typeahead": "^2.0.0-alpha.5",
    "react-wysiwyg": "^2.2.1",
    "underscore": "^1.8.3",
    "validate": "^3.0.1",
    "validate.js": "^0.10.0",
    "xml2json": "^0.10.0"
  },
  "devDependencies": {
    "css-loader": "^0.23.1",
    "eslint": "^3.1.1",
    "eslint-plugin-class-property": "^1.0.0",
    "eslint-plugin-react": "^5.2.2",
    "jest-cli": "^14.0.0",
    "raw-loader": "^0.5.1",
    "react-addons-perf": "^15.2.1",
    "style-loader": "^0.13.1"
  }
}
```
