### ISSUE TITLE
[Docs] It's not clear in the docs that "session" and "check" must be added

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#6932]
As forums user **gris** [brought up here](https://forums.meteor.com/t/session-package/22276/2), it's not clear that `session` must be added in order to use it.  Other packages make a very clear distinction.  This probably wasn't updated when the packages were no longer default starting in (I think) 1.2.

The same omission seems to be on `check`.

PR coming.

**Comment by abernix** [comment]
Not the first time I've heard this complaint.  Didn't realize the other packages made it so clear that they had to be installed and these didn't.

**Comment by stubailo** [comment]
Looks like the PR was merged, so let's close this!
