### ISSUE TITLE
Path routes exhaust the application cache

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#6936]
I submitted a PR (https://github.com/meteor/meteor/pull/2926) for this a while ago but realized I hadn't opened an associated issue for people to find, so here you go.

The appcache attempts to support path routes with a application cache manifest fallback entry of "/ /", which causes paths which didn't otherwise match to fall back to the root URL "/", and so load the application HTML.

However Chrome at least adds each and every such encountered path to the manifest as a "master" entry. This slows code update reload times (Chrome will re-download each master entry), and has the danger of eventually running out of space in the application cache.

Running out of space in the application cache is particularly nasty because that would cause code updates to fail, leaving users running the old version of the code, with no way for the developer to push an update.

Switching to using hash fragment routes when using the application cache is uglier, but is supported by browsers, and can be applied automatically by routing packages (such as iron:router) when the appcache package is used.

**Comment by tmeasday** [comment]
I'm not sure if this is quite a bug or a feature, but I'll classify it as a feature because I think it requires an analysis of the trade-off in a feature-like way.

I'd be very interested to hear what users of the `appcache` package think about this; it surprising to me that a lot of people are using it but we don't hear about this issue more often.

**Comment by awwx** [comment]
The app html for a typical Meteor app is quite small (~ 2K), and modern browsers often give a lot of space to the app cache (100MB or more), so you can go for quite a long time before exhausting the available space.

Some browsers like Chrome vary the amount of space given to apps based on criteria such as the amount of free disk space available.  So it's possible that most users are doing just fine (so far, maybe they'll exhaust their app cache eventually), and maybe only some very small percentage of users are actually running into trouble at this point (those which their browser is giving less than the usual amount of app cache space to).

However the lack of bug reports might not be indicative.  There's no way for the developer to know that a user is stuck on an old version of the app unless the user tells the developer that something isn't working.  (And the user might just abandon the broken app rather than telling the developer).  And if the developer does get a report "the app isn't working", they have no reason to know that it's the appcache that's causing the problem as opposed to something else strange in that particular user's environment.  After all, it all works fine when the developer tests it, and it's working for most users.  So it's true that lack of bug reports might mean that no one is actually running into trouble in practice yet... or, some people might be running into trouble, but we're not hearing about it because it's hard to diagnose.

This is definitely a bug.  Having the appcache support path routes is a feature.   Having app code updates stop working for some users because of the appcache is a bug.  You might decide not to *fix* the bug if you make the trade-off that path routes are more important than having apps break for some small percentage of users, but the appcache breaking Meteor's code updates is a bug, even if it only happens in rare circumstances.

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers. 

Service Workers are supposed to be the replacement, which is being tracked in #5982.
