### ISSUE TITLE
npm init command in Angular 2.0 tutorial

### ISSUE THREAD

**Issue by Sauermann** [meteor/meteor#6939]
On the tutorial site
http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping
Between steps 0.1 and 0.3 it is mentioned that one should initialize a project with the command

    $ npm init

However this does not work for me.
I am on Windows 8.1, where Meteor was previously not installed. This installed version of Meteor is 1.3.2.4 and get as response, that npm can not be found.

As a workaround I used

    $ meteor npm init

I would like to suggest to add a note to the tutorial of how to use npm on windows 8.1.

**Comment by abernix** [comment]
Great point!  That is actually a third-party tutorial though.  Could you close this issue and open it [over there](https://github.com/Urigo/angular-meteor-docs) on @Urigo's project?

**Comment by Sauermann** [comment]
Right. Sorry ... will do that.
