### ISSUE TITLE
Couldn't find layout template after build command.

### ISSUE THREAD

**Issue by krestt** [meteor/meteor#6942]
Please help. The app is working fine in all browsers, without errors, loading all templates. But after i build it to android .apk and install it to device or emulator it says "Couldn't find layout template. Are you sure you defined it?" 
It asks for the template that i defined in router.configure > layoutTemplate. I know that because when i change there the value it asks for the new one that i set.

The template exists.

Even when i build the auto generated todo app, it shows the same error.

Commands i use:
`meteor run --mobile-server localhost:3000`
`meteor build ../bundle --debug --server localhost:3000`

Meteor Version : 1.3.2.4

Thank you in advance!

**Comment by laosb** [comment]
Sounds strange.

**Comment by krestt** [comment]
Okay i fixed it after all. For some reason when in the layout template i used {{> header}} and {{> yield}} it was throwing this error. So it allows only {{> yield}}. To fix it i copy pasted the header's html in to this layout template.

**Comment by laosb** [comment]
Which router are you using? 

It doesn't sounds like a Meteor bug. Closing.

**Comment by krestt** [comment]
iron router

**Comment by laosb** [comment]
@krestt Iron Router is not recommended. You may post this to https://forums.meteor.com, it's a better place for discussing.

**Comment by krestt** [comment]
Okay. Thank you!
