### ISSUE TITLE
A lot of problems after version 1.3

### ISSUE THREAD

**Issue by georgetour** [meteor/meteor#6943]
After having new version, me and a lot other people that we are doing the University of London Course had a lot of issues.Some older projects that were made in previous versions if we choose to meteor update then the projects were blank.So the solution for us was not to update since even after a lot of code changed they didn't work.Also if you have meteor 1.3 or above and you try to run previous versions with meteor --release we get also blank pages or errors like isobuild:minifier-plugin package is unknown and many other errors that don t start your application.Thank you.

**Comment by abernix** [comment]
The problem you're referring to is too vague to accurately provide help.  You should at least be seeing errors in the browser or server console.  Meteor 1.3 is generally backward compatible with Meteor 1.2.

**Comment by georgetour** [comment]
There are so many errors I will try to gather them all when I find a little time and post them in here.

**Comment by abernix** [comment]
Please close this issue and possibly consult with the forums (extremely helpful) or stackoverflow with your particular errors.

**Comment by georgetour** [comment]
I did that but no one of us could find solutions since they were too many but I ll close it. I have tried meteor forums which were really helpful but for issues like that there are not much things we can do.Trying so many hours to find unresolvable compatibility issues was a pain .Thank you for your time though and I hope future releases will fix stuff like that.
