### ISSUE TITLE
Failed to parse SourceMap error when importing bootstrap from NPM.

### ISSUE THREAD

**Issue by sergiotapia** [meteor/meteor#6947]
This is happening on Meteor 1.3.2.4.

>Failed to parse SourceMap: http://localhost:3000/5900bf1a492856b07ec0a28815a97a76e290cf7c.map

I have this import in my `main.scss`:

```
@import "{}/node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
```

When I remove this import, the error goes away. Here's what the map has when there's the error:

> {"version":3,"sources":["meteor://ðŸ’»app/node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss","meteor://ðŸ’»app/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_normalize.scss","meteor://ðŸ’»app/packages/meteortoys_toykit/style/toykit. \*snip\*

Could that weird symbol be causing the issue? `"meteor://ðŸ`

**Comment by lorensr** [comment]
Hi @sergiotapia thanks for reporting. I can't reproduce the error – could you please edit this repo until the error appears?

git@github.com:lorensr/6947.git

![image](https://cloud.githubusercontent.com/assets/251288/15165825/044a5242-16e7-11e6-9e87-c4eb29e37b75.png)

**Comment by ffxsam** [comment]
I've been having the same issue, but I can't reproduce it on a clean repo, and I can't hand over the repo it's happening in since it's closed source.

**Comment by abernix** [comment]
@sergiotapia I'm going to close this because we haven't heard anything back from you about this problem.  Would be happy to reopen it if you can provide a repo that reproduces it! :)

**Comment by kachkaev** [comment]
I also have this issue in a current project, but I can't figure out the cause. Can this simply happen when the sourcemap becomes too big for Chrome? Mine is 3300KB.

BTW: It does not seem that strange symbols in `meteor://ðŸ’»app/node_modules/...` are the reason for the problem – they are just `meteor://💻app/node_modules/...` in UTF-8.

**Comment by kachkaev** [comment]
Another (more active discussion) is here: https://github.com/meteor/meteor/issues/7206
