### ISSUE TITLE
Hot code push only worked after uninstalling and reinstalling iOS app

### ISSUE THREAD

**Issue by mikeislearning** [meteor/meteor#6949]
I'm not sure if this is a bug, or if it is expected behaviour.
I went through the Meteor Guide on hot code push, but it doesn't indicate clear requirements on expectations on how it will run. Nor does the guide indicated suggestions packages.
Here are mine:
`accounts-facebook            1.0.9  Login service for Facebook accounts`
`accounts-ui                  1.1.9  Simple templates to add login widgets to ...`
`alanning:roles               1.2.15  Authorization package for Meteor`
`aldeed:collection2           2.9.1  Automatic validation of insert and update...`
`aldeed:simple-schema         1.5.3  A simple schema validation object with re...`
`blaze-html-templates         1.0.4  Compile HTML templates into reactive UI w...`
`check                        1.2.1  Check whether a value matches a pattern`
`dburles:collection-helpers   1.0.4  Transform your collections with helpers t...`
`ddp                          1.2.5  Meteor's latency-compensated distributed ...`
`ddp-rate-limiter             1.0.4  The DDPRateLimiter allows users to add ra...`
`ecmascript                   0.4.3  Compiler plugin that supports ES2015+ in ...`
`ejson                        1.0.11  Extended and Extensible JSON library`
`fastclick                    1.0.11  Faster touch events on mobile`
`fourseven:scss               2.1.1* Style with attitude. Sass and SCSS suppor...`
`houston:admin                2.0.7  A zero-config Meteor Admin`
`http                         1.1.5  Make HTTP calls to remote servers`
`iron:layout                  1.0.12  Dynamic layouts which enable rendering d...`
`iron:router                  1.0.12  Routing specifically designed for Meteor`
`jquery                       1.11.8  Manipulate the DOM using CSS selectors`
`kadira:debug                 2.2.4* Full Stack Debugging Solution for Meteor`
`localstorage                 1.0.9  Simulates local storage on IE 6,7 using u...`
`logging                      1.0.12  Logging facility.`
`manuel:reactivearray         1.0.5  Reactive Array for Meteor`
`matb33:collection-hooks      0.8.1  Extends Mongo.Collection with before/afte...`
`meteor-base                  1.0.4  Packages that every Meteor app needs`
`meteorhacks:kadira           2.28.5  Performance Monitoring for Meteor`
`meteorhacks:kadira-profiler  1.2.1  CPU Profiler for Meteor (used with Kadira)`
`meteoric:ionic               0.2.0  Ionic components for Meteor. No Angular!`
`meteoric:ionic-sass          0.1.9* Ionic's CSS Framework in SASS and bundled...`
`meteoric:ionicons-sass       0.1.6* Ionic's Ionicons library in SASS and bund...`
`mobile-experience            1.0.4  Packages for a great mobile user experience`
`momentjs:moment              2.13.1  Moment.js (official): parse, validate, m...`
`mongo                        1.1.7  Adaptor for using MongoDB and Minimongo o...`
`npm-bcrypt                   0.8.5  Wrapper around the bcrypt npm package`
`percolate:momentum           0.7.2  Reactive animations`
`random                       1.0.9  Random number generator and utilities`
`rate-limit                   1.0.4  An algorithm for rate limiting anything`
`reactive-var                 1.0.9  Reactive variable`
`reload                       1.1.8  Reload the page while preserving applicat...`
`reywood:publish-composite    1.4.2  Publish a set of related documents from m...`
`service-configuration        1.0.9  Manage the configuration for third-party ...`
`session                      1.1.5  Session variable`
`sha                          1.0.7  SHA256 implementation`
`spacebars                    1.0.11  Handlebars-like template language for Me...`
`srp                          1.0.8  Library for Secure Remote Password (SRP) ...`
`standard-minifier-css        1.0.6  Standard css minifier used with Meteor ap...`
`standard-minifier-js         1.0.6  Standard javascript minifiers used with M...`
`tracker                      1.0.13  Dependency tracker to allow reactive cal...`
`underscore                   1.0.8  Collection of small helpers: _.map, _.eac...`

Any assistance is appreciated!

**Comment by martijnwalraven** [comment]
Could you describe in more detail what steps you took, what you expected to happen, and what actually happened?

**Comment by mikeislearning** [comment]
I'll try - what steps do you mean though?
For the submission to the app store, I did meteor build, and listed the domain name as the --mobile-server option.
Yesterday, I used MUP to upload the latest build to my server.
Upon opening and closing the app numerous times on my phone, I did not see the reflected change.
Once I uninstalled and reinstalled the app, the change was there.

So hot code push is working...sort of. I'm just wondering if there is a plugin I am missing, or if I should be waiting longer or something to see the change reflected in the app.

**Comment by martijnwalraven** [comment]
When you say you uninstalled and reinstalled the app, do you mean you did a new build? Or did you reinstall the same version from the App Store?

Possible reasons for updates not working  that come to mind:
- You need to make sure you set `ROOT_URL` correctly when deploying with MUP
- Did you make any changes to the set of Cordova plugins? Since hot code push can only update JavaScript code, any change to native code will block updates.
- Is the new version you uploaded built using the same version of Meteor? There have been some changes to core plugins between 1.3 and 1.3.1, so this would also block updates.

**Comment by mikeislearning** [comment]
I didn't do a new build, just reinstalled the same version from the App Store.

- ROOT_URL is correctly set with MUP
- I haven't made any changes with the plugins.
- the version might be different across what I submitted vs what I'm currently using, but I noticed that the code push was successful automatically in Android.

I guess I'm just a little unclear on expectations with Hot Code Push based on the Meteor Guide.

**Comment by martijnwalraven** [comment]
What part of the [description of hot code push in the guide](http://guide.meteor.com/mobile.html#hot-code-push) isn't clear to you?

**Comment by mikeislearning** [comment]
Expectations.
Assuming the correct configuration is implemented, will these changes occur immediately on all devices where the app is downloaded? Does the app need to be restarted/reinstalled? Are there plugins that can make the experience better for the user? How often does the app check the server for client side changes, or what event on the client triggers it? 

Is there a way to test if everything is configured correctly?

**Comment by martijnwalraven** [comment]
I'm not sure what caused your app to only update after a reinstall of the same version, but that shouldn't be needed. The server notifies the app of new versions over DDP, so the update should occur almost immediately. By default, the app will reload with the new version directly after completing the download, but you can use [reload-on-resume](https://atmospherejs.com/mdg/reload-on-resume) to wait until the app goes into the background.

Testing hot code push is hard on a production build, but you could run the app in development while connecting to the production server (`run ios-device --mobile-server`) and watch for logs in the Xcode console and using Safari remote debugging.

**Comment by mikeislearning** [comment]
Alright. I appreciate your time on this matter! Just wanted to make sure there wasn't a bug. Cheers!

**Comment by mikeislearning** [comment]
Ya - so this is definitely an issue.
Just tested it again. I'm using a Nexus 5 and an iPhone 6s.
The version of the app on the Play Store is actually older than the one on the App Store.

Once I push my changes to the server, and open the app on each device, the Nexus 5 triggers a refresh to show the correct changes. The iPhone 6s does not (but it will if I uninstall & reinstall the app).

Thoughts?

**Comment by martijnwalraven** [comment]
Could you try connecting a development build to the production server (`meteor run ios-device --mobile server <host>`)? And then see if hot code push works, or whether anything shows up in the Xcode console or using Safari remote debugging?

**Comment by jean1987** [comment]
I am facing the same issue, and I tried what you suggested: Running a development build on the device connected to Xcode, then updating the development server.
Once the server is restarted, the Xcode console shows:

`2016-07-09 13:59:58.982 project[388:144573] Start downloading asset manifest from: manifest.json -- https://dev.project.com/__cordova/`
`2016-07-09 13:59:58.994 project[388:147604] Downloaded asset manifest for version: 199b3c41f38894293265bb28b28ac480d4749ee6`
`2016-07-09 13:59:59.080 project[388:144573] true`

The screen flashes as usual during hot push updates, but after the reload the old page shows.
Oddly, uninstalling and reinstalling the app does work...

**Comment by iwoj** [comment]
Same for me. Doesn't seem like hot code push works on iOS. I'm running in dev mode with:

`meteor run ios-device --mobile-server https://productionsite`

Auto reloading works fine in the mobile browser.

**Comment by iwoj** [comment]
See #7760

**Comment by hwillson** [comment]
There hasn't been any activity on this issue in a while, and using the `--mobile-server` option is reported to address this issue. I'll close this issue for now, but if anyone is still encountering this issue with a modern version of Meteor, please post back and I'll re-open. Thanks!
