### ISSUE TITLE
install.meteor.com should provide an update check

### ISSUE THREAD

**Issue by trajano** [meteor/meteor#6953]
Meteor 1.3.2.4.  To speed up travis builds we can do caching to reduce the downloads if possible.  This optimization can be done on `node_modules` already.  http://install.meteor.com/ script is written in such a way that it will always do a clean install which is generally a good idea and I'd like to keep it as the default.  However, I would also like an option to check if there is a new version compared to the installed copy and if so to do a clean install with the newer version otherwise leave the current installation alone.

**Comment by laosb** [comment]
Didn't see the case of doing so. In pre-0.8 days, when `meteor` fails I always try that to get a clean install.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=install.meteor.com%20should%20provide%20an%20update%20check&body=Migrated%20from:%20meteor/meteor%236953) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
