### ISSUE TITLE
Allow passing options in the MongoDB driver

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6958]
For example, to enable SSL validation (after #6957) - https://github.com/meteor/meteor/issues/5809#issuecomment-190841203

This could look something like 

`Mongo.setConnectionOptions({...});` to be called by the user before they initialize any collections, setting some internal state that is read at the various points we call `new MongoConnection`.

**Comment by dburles** [comment]
@tmeasday just opened a PR, maybe you can take a look

**Comment by tmeasday** [comment]
https://github.com/meteor/meteor/pull/7277

**Comment by tmeasday** [comment]
This issue is fixed but I'm not sure it works in practice if you are using accounts. Have you tested that @dburles?

**Comment by dburles** [comment]
I haven't

**Comment by abernix** [comment]
I'm fairly sure that this doesn't work unless implemented as a package and loaded before (i.e. in `.meteor/packages`) any other package which initiates a collection (such as `accounts-base`).  #7455 and the [related forum post](https://forums.meteor.com/t/meteor-with-the-new-mongodb-3-2-1-compose-io/17763/11) seem to hint at that.  It does seem to work though!

Is it possible that `Meteor.settings` would be a more appropriate way to implement this?  But then, as mentioned in aforementioned links, there's the SSL CA file needing to be loaded from a filesystem path.

**Comment by tmeasday** [comment]
Possibly accounts could do its init in a startup block but that could cause flow on problems..

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20passing%20options%20in%20the%20MongoDB%20driver&body=Migrated%20from:%20meteor/meteor%236958) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
