### ISSUE TITLE
Bug in check behavior

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6959]
Meteor 1.3.2.4.

The following unexpected behavior is occurring:

```
args = { thing: undefined };

check(args.thing, Match.Optional(String)); //passes
check(args, {
  thing: Match.Optional(String)
}); // fails
```

I tried `Match.Maybe` and that also fails. So I have to comment out my entire `check` statement because if I'm passing something in and it's not checked, the check fails.

**Comment by abernix** [comment]
This is confusing, but it's nothing new – it's always been this way.  `Object`s do not get checked in the same way.  There's even an [explicit test that makes sure that this happens](https://github.com/meteor/meteor/blob/devel/packages/check/match_test.js#L140), so we can't really call it a bug.

I can speculate about why it's this way, but I can't find any discussion about it.  Perhaps it's time to consider an existing NPM package that provides similar functionality?  [validator](https://www.npmjs.com/package/validator) is the only thing that comes to mind for me, but I'm sure there are others.

That being said, `check` is a great package, and perhaps it just needs some love.

**Comment by abernix** [comment]
@ffxsam This is a good discussion to be had, but you can work-around this by using:

##### For `Match.Optional`-like functionality
```
check(args, {
  thing: Match.OneOf(undefined, String)
});
```
##### For `Match.Maybe`-like functionality
```
check(args, {
  thing: Match.OneOf(null, undefined, String)
});
```

**Comment by abernix** [comment]
Ok, some more confusion happened in #6938 about `check`.  Let's turn this into a discussion about how to maybe fix `check`.  There was some initial discussion in #3876 when `Match.Maybe` came into existence.

### Current Functionality

#### Non-Objects
* `Match.Optional(String)` will allow `String` or `undefined`.  That's it.
* `Match.Maybe` will allow `String`, `undefined` **OR `null`**.

#### Objects
First, let's remember that in an object you can have something set to `undefined`/`null` or it can *not be set at all* (absent).

* `Match.Optional(String)` will allow `String` or *not set*
* `Match.Maybe(String)` will allow `String` or *not set* (Same as `Match.Optional`)

### Tests
📛 = Does Not Match *(throws error when used with `check`)*

✅ = Matches! *(does **not** throw error when used with `check`)*
#### Non-Object

##### `null`
`Match.test(null, Match.Optional(String));`
>`false` 📛

`Match.test(null, Match.Maybe(String));`
>`true` ✅

`Match.test(null, Match.OneOf(undefined, String))`
>`false` 📛

`Match.test(null, Match.OneOf(null, String))`
>`true` ✅

##### `undefined`
`Match.test(undefined, Match.Optional(String));`
>`true` ✅

`Match.test(undefined, Match.Maybe(String));`
>`true` ✅

`Match.test(undefined, Match.OneOf(undefined, String))`
>`true` ✅

`Match.test(undefined, Match.OneOf(null, String))`
>`false` 📛

#### Objects
🌀 = different behaviour than when not an object

##### `null`
`Match.test({ keyName: null }, { keyName: Match.Optional(String) })`
>`false` 📛

`Match.test({ keyName: null }, { keyName: Match.Maybe(String) })`
>`false` 📛 🌀

`Match.test({ keyName: null }, { keyName: Match.OneOf(undefined, String) })`
>`false` 📛

`Match.test({ keyName: null }, { keyName: Match.OneOf(null, String) });`
>`true` ✅

##### `undefined`
`Match.test({ keyName: undefined }, { keyName: Match.Optional(String) });`
>`false` 📛 🌀

`Match.test({ keyName: undefined }, { keyName: Match.Maybe(String) });`
>`false` 📛 🌀

`Match.test({ keyName: undefined }, { keyName: Match.OneOf(undefined, String) });`
>`true` ✅

`Match.test({ keyName: undefined }, { keyName: Match.OneOf(null, String) });`
>`false` 📛

##### *not set*
`Match.test({ /* not set */ }, { keyName: Match.Optional(String) });`
>`true` ✅

`Match.test({ /* not set */ }, { keyName: Match.Maybe(String) });`
>`true` ✅

`Match.test({ /* not set */ }, { keyName: Match.OneOf(undefined, String) });`
>`false` 📛

`Match.test({ /* not set */ }, { keyName: Match.OneOf(null, String) });`
>`false` 📛

#### Problem. e.g. "What if I want to optionally check for a `String` in an object?""
>With the current implementation, I think the answer is this:

>*`Match.Maybe(Match.OneOf(undefined, null, String))`*

##### Example
`Match.test({ keyName: null }, { keyName: Match.Maybe(Match.OneOf(undefined, null, String)) });`
>`true`

`Match.test({ keyName: undefined }, { keyName: Match.Maybe(Match.OneOf(undefined, null, String)) });`
>`true`

`Match.test({ /* not set */ }, { keyName: Match.Maybe(Match.OneOf(undefined, null, String)) });`
>`true`

`Match.test({ keyName: "Actual String" }, { keyName: Match.Maybe(Match.OneOf(undefined, null, String)) });`
>`true`

#### The Fix?

The examples that are marked with 🌀 above are just confusing results.

`Match.Optional` has always worked differently on objects, even before `Match.Maybe` was introduced.  Also, `Match.Optional` has never allowed `null`, even though it seems reasonable.  `Match.Maybe` (which allowed `null` or `undefined` in addition to the specified type) was an *okay* solution for this, however when it was introduced, it should have also fixed the quirky object behaviour.

On Objects, it seems that `Match.Optional` and `Match.Maybe` should allow "missing" (i.e. `"key" in object === false`), in addition to what they usually permit (`undefined` and in `Maybe`'s case also `null`).

Non-Objects should work the same as they do right now.

All that being said, `Match.Optional` is probably due for deprecation (as mentioned in #3876), but that's a different issue.

So the ultimate question is, for checking objects, can `Match.Optional` and `Match.Maybe` be changed to treat `undefined` and `null` the same as not-existing, without breaking things?  Or is everything fine the way it is? :smile:

**Comment by mitar** [comment]
We have been using [this package](https://github.com/peerlibrary/meteor-check-extension) to address some of those inconsistencies.

One interesting thing is also how `undefined` becomes `null` when it goes through `Meteor.call`. So then if you have a `check` inside a simulation, it can fail on the `undefined`, while it can succeed on `null` on the server side. :-)

Not sure if this is helpful for this discussion, but this one was for me personally the most confusing.

**Comment by abernix** [comment]
Just jotting down notes: npm check-types: https://www.npmjs.com/package/check-types

**Comment by ffxsam** [comment]
I've got a workaround now, it's a bit clunky though:

```
    check(args, {
      _id: Match.Optional(Match.OneOf(String, undefined)),
      title: String,
      description: String,
      orgId: String,
      related: Match.Optional(Match.Any),
      tagIds: Match.Optional(Match.Any),
    });
```

I'm guessing MDG is not putting much time into `check` now that they recommend SimpleSchema for validation in methods. The thing is, I'm using Astronomy and don't want to have to use SimpleSchema just to validate method args.

**Comment by stubailo** [comment]
At some point I was hoping that Astronomy and SimpleSchema could use a similar or identical schema format, and that would replace check. But it seems that hasn't happened.

**Comment by ffxsam** [comment]
Well, let me ask this: in the Meteor validated method, how is the `validate` method structured? That is, what is it expected to return exactly, in order to provide either a success or failure? Just a `throw new Meteor.Error(...)`?

**Comment by stubailo** [comment]
Any error at all works. It's exactly the same as throwing from the body of a regular Method. So:

1. `check` works
2. `Meteor.Error` works
3. `ValidationError` is the thing SimpleSchema throws, which is a nice convention to follow: https://github.com/meteor/validation-error

So nothing SimpleSchema-specific there at all!

**Comment by ffxsam** [comment]
Ok, good to know! I'll see what Astronomy can do as far as validation. They probably updated how it works in v2. http://jagi.github.io/meteor-astronomy/#validation

**Comment by stubailo** [comment]
I'd love to add some docs to validated method about how to use it with astronomy or something else that isn't simple schema!

**Comment by lucendio** [comment]
I think, instead of having a big `SimpleSchemaà dependency, a core-near package like `check` is really great. I think there are 2 questions regarding what might be the nest steps:
1. give check the love it deserves or replacing it with a npm solution?
2. Fixing the behavior of `Maybe` and `Optional` or introducing new functions like the mentioned extension does?

**Comment by mitar** [comment]
Maybe a better approach would be to allow `audit-argument-checks` package to have an API so various check packages could tell which arguments have been checked. So then `SimpleSchema` package could provide `check`-like functionality, and mark arguments as checked. Or any other alternative. In this way it would be easy for community to experiment and move away from `check`.

**Comment by ffxsam** [comment]
Just a brief follow-up on this issue:

I'm having a great deal of trouble getting this to work predictably. In this particular scenario, I have the following:

```js
  validate(args) {
    console.log(args);
    check(args, {
      userIds: [String],
      message: String,
      url: Match.OneOf(Match.Maybe(String), undefined),
    });
  },
```

`url` is optional, but the problem is that on the server side, if I leave off `url`, it's missing from the object. But on the client side, it's there as `undefined`. I've tried every combination I can think of using `Match.OneOf`, `Match.Maybe`, and nothing seems to cover all scenarios. Even `Match.Any` doesn't work:

```
I20160725-11:34:53.849(-7)? Exception while invoking method 'sendNotification' Error: Match error: Missing key 'url'
I20160725-11:34:53.849(-7)?     at exports.check (packages/check/match.js:34:1)
```

And one last desperate attempt, `Match.Optional(Match.Any)` doesn't work either. On the server side, there's no problem, but the client complains that `url` is required... even though I said it was optional.

So, clearly the problem is that there's a difference in an object between `undefined` and "missing key." @abernix, I tried your suggestion:

```js
      url: Match.Maybe(Match.OneOf(undefined, null, String)),
```

And it passes on the server, but the client complains about `url` being required.

**Comment by ffxsam** [comment]
My last ditch resort was to always pass a string no matter what:

```js
    _sendNotification.call({
      userIds,
      message,
      url: url || '',
    });
```

And that, sadly, has failed. I can see on the server side, `url` is a blank string. On the client side, I get:

```
Object {userIds: Array[1], message: "This will soon be clickable.", url: ""}
Error invoking Method 'sendNotification': "url" is required [validation-error]
```

It can't even tell the difference between a blank string and a missing parameter. 😞

**Comment by hwillson** [comment]
Hi all - as discussed (https://github.com/meteor/meteor/issues/6959#issuecomment-216448319), the original issue in this thread isn't a bug - `check` has always worked this way. That being said, there is definitely work that can be done to make `check` better (as outlined in https://github.com/meteor/meteor/issues/6959#issuecomment-216769130). At this point however, that work falls under the feature request category.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Bug%20in%20check%20behavior&body=Migrated%20from:%20meteor/meteor%236959) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
