### ISSUE TITLE
[bug] [1.3.2.4] Hidden files in public folder are watched by Meteor.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6966]
I have `public/.src/node_modules` in my app, and as you can see it's inside a hidden folder. Despite being hidden, `meteor` still watches those files, and since there are thousands and thousands of files in `node_modules`, I get the error

```
Error: EMFILE, too many open files '...'
```

Shouldn't Meteor ignore hidden files?

A workaround in my case is to `npm install` within `public/.src`, build what I need, `rm -rf node_modules`, then finally start `meteor`. As you can imagine, this can get bothersome towards development. Would be great if Meteor ignored hidden files!

Another workaround could be to move these files in `.src` one level up from the Meteor app, and build them into the app.

**Comment by abernix** [comment]
Related to #6952

**Comment by laosb** [comment]
I remembered that somewhere in the docs mentioned hidden folders won't be watched by Meteor. But now it wasn't there. If it even hadn't been there, this should be considered as a `feature` instead of a `bug`.

**Comment by merlinpatt** [comment]
What's the purpose of having `node_modules` inside the `public` directory?

**Comment by abernix** [comment]
I'm sure this is the same issue that is happening in #6952.  There's more conversation over there and multiple reproductions, so closing this as a duplicate.

**Comment by trusktr** [comment]
@merlinpatt 

> What's the purpose of having node_modules inside the public directory?

I use `webpack` to build some static demos in `public`, then I serve them in iframes using routes (f.e. with flow-router or iron-router). The reason is because I don't want to spend time migrating the demos into the Meteor app, and plus that involves lots of trickery as Meteor's build system doesn't handle loader chaining (build plugin chaining) or other modules formats like AMD which some libraries in the demos use. The easiest solution in my case is to keep the demos as they are with their possibly-outdated dependencies separate from the Meteor app's `node_modules`, and to compile them statically to static assets.

As a workaround for the EMFILE error, I moved `node_modules` and demo sources completely outside of the Meteor app, then I just tell Webpack to build into the Meteor app's `public` folder. Now the only things in `public` are the final built files.
