### ISSUE TITLE
jQuery is not defined - Meteor 1.3

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#6968]
https://github.com/aldeed/meteor-autoform-select2/issues/65

and more others jquery plugins, example:
```jade
head
  script(src="https://cdnjs.cloudflare.com/ajax/libs/jquery-countdown/2.0.2/jquery.countdown.js")
```

workaround:
```coffee
  Template.hello.onRendered: ->
    $.getScript '/countdown.js', ->
      $('.countdown').countdown date: new Date 2016, 5, 15
```

**Comment by comerc** [comment]
Solution. Copy jQuery-plugin to /hello/lib/client/ and create package.json in root of project:
```json
{
  "name": "hello",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
  }
}
```
run meteor:
```bash
Unable to resolve some modules:

  "jquery" in /hello/lib/client/selectize.js/_selectize.js (web.browser)
  "sifter" in /hello/lib/client/selectize.js/_selectize.js (web.browser)
  "microplugin" in /hello/lib/client/selectize.js/_selectize.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save jquery sifter microplugin

```
ok, run: 
```bash
  meteor npm install --save jquery sifter microplugin
```
I see changes in package.json
```json
{
  "name": "hello",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "jquery": "^2.2.3",
    "meteor-node-stubs": "~0.2.0",
    "microplugin": "0.0.3",
    "sifter": "^0.4.5"
  }
}
```
Now Meteor works fine!

**Comment by LewisW** [comment]
If you're using `$.getScript()`, you probably want to disable [jQuery's cache busting](https://api.jquery.com/jquery.getscript/#caching-requests):
```
$.ajaxSetup({
  cache: true
});
```

Also if you're calling getScript inside a template that could be re-rendered when switching different routes, that you only call getScript once.

Also I haven't checked, but your 2nd workaround could possibly be downloading a separate jQuery version to the one that Meteor bundles. It'll probably work fine, but it's not ideal.

**Comment by laosb** [comment]
Your first example won't work because we now have the JS bundle at the ending of `<body>`, including the jQuery required by Meteor. Putting it to client is reasonable and should works fine.

Seems not a problem of Meteor itself. You can discuss it on [Meteor Forums](https://forums.meteor.com).
