### ISSUE TITLE
Meteor Deploy Timeout Error

### ISSUE THREAD

**Issue by dgraziotin** [meteor/meteor#6969]
I used to have an app hosted at sematacc.meteor.com, which was developed with meteor v1.0. Likely because of the changes brought by the subsequent releases, the website went down. Now I have took care of porting the app to meteor 1.3.0. However, when trying to deploy the app, this is what I get:

```
$ meteor deploy sematacc.meteor.com -p
Error deploying application: Connection error (connect ETIMEDOUT)
```

This is using OS X. No matter how many times I try.

**Comment by abernix** [comment]
@dgraziotin As you saw in the other issue, #5578, MDG discontinued Meteor "free" hosting – including existing apps.  This command will no longer work for `.meteor.com` sites, but will work for the [Galaxy Paid hosting service](http://meteor.com/galaxy).  See the [Announcement from MDG on the Meteor Forums](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308/211) for more information.

**Comment by laosb** [comment]
Meteor.com Free Hosting was shutdown by MDG. Existing apps was removed too.
