### ISSUE TITLE
[1.3] [accounts-password]: e-mails and i18n

### ISSUE THREAD

**Issue by Sabst** [meteor/meteor#6970]
This is about the accounts-password package and the texts of the associated e-mails (enrollment, verification, password reset): the texts can be customized but there is no way to know in the customization what the client locale is.
Two user sessions can use different locales and the e-mails sent (from the server-side) need to know about each of those client locales.

**Comment by abernix** [comment]
Are you suggesting that one user with two different user sessions would need to get e-mails in different locales depending on which session they are currently using?

**Comment by Sabst** [comment]
Yep if the two sessions have a different locale: this is what the user asked for, no?

The main point in my opinion is that two different users with two different locales will get e-mails in their respective locales. In a way, the e-mails are an extension of the web experience and must be consistent from a locale standpoint.

Maybe I missed something you see as an issue?

**Comment by abernix** [comment]
I was just clarifying for the sake of the issue/feature-request. 😄

Personally, I would find it different than the experience I'm used to.  Generally, my account has a 'default language' and that is the language I receive my administrative e-mails from Google in and the language my account switches to when I log in (regardless of my browser setting).  I can change my Google Maps/Search/etc. interface into another language temporarily, but that doesn't change the e-mails.

Honestly, I'm not even sure if there is a way to send the `accounts-ui` e-mails in different locales at all – but I've never used that feature.

**Comment by Sabst** [comment]
I'm fine as long as the framework enables the different possibilities and allows applications to answer their specific customer reqs.
For example, send the mails using:
- a locale defined in the user profile
- the browser locale (preferences)
- the locale defined in the web page (if all supported locales are listed in the page)

I'm not using `accounts-ui` and my concern is about the API available when the application needs something specific.

That being said, if the locale is part of the user profile and stored in the DB, your approach will work as the user (and hence the locale) is available when the e-mail text customization is defined.
I will probably use this workaround for now until more flexibility is available, thanks :-)

**Comment by hwillson** [comment]
As long as the client locale can be passed to the server somehow (like by storing it / reading it from Mongo for example), then it can be accessed wherever you call [`Accounts.emailTemplates`](https://docs.meteor.com/api/passwords.html#Accounts-emailTemplates). Since this can be handled without making changes to the Meteor codebase, I'll close this off. Thanks for posting this originally!
