### ISSUE TITLE
Cordova: no CORS header on /sockjs/info

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6971]
After upgrading from 1.2 to 1.3.2.4, I get this periodic error during `run android`:

`XMLHttpRequest cannot load http://192.168.2.11:3000/sockjs/info?cb=juitcbbvao. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12280' is therefore not allowed access.`

and `Meteor.status().status` is stuck at `"waiting"`

At first I thought it was that `force-ssl` thing (#3382), but it remained after removing `force-ssl`. 

- `mobile-config.js` has `App.accessRule('*')`
- I also added `BrowserPolicy.content.allowOriginForAll("192.168.2.11:3000");` and `BrowserPolicy.content.allowOriginForAll("localhost:12280");`

`run ios` works fine.

@martijnwalraven any ideas?

Related: #4132

**Comment by martijnwalraven** [comment]
SockJS responses should contain an `Access-Control-Allow-Origin` header, so I don't think that is the issue. Could it be that the server returns some kind of error response?

Could you try Chrome remote debugging to see what the actual response looks like?

(`App.accessRule` misconfiguration would have generated another error message, and `BrowserPolicy` has no effect on Cordova. See [here](http://guide.meteor.com/mobile.html#accessing-local-files-and-remote-resources) for some more documentation on these confusing options.)

**Comment by lorensr** [comment]
Thanks Martijn! 

`meteor run android --mobile-server http://192.168.2.11:3000`

I have two clients open. One is the app in the android emulator, which gets a 301:

![image](https://cloud.githubusercontent.com/assets/251288/15048419/73c41a10-12b7-11e6-9ab3-e8da5d251feb.png)

And one is a `localhost:3000` chrome tab, which gets a 101 and works fine:

![image](https://cloud.githubusercontent.com/assets/251288/15048493/d2ddea76-12b7-11e6-823b-9c803b6b5269.png)

**Comment by lorensr** [comment]
So only the `http://192.168.2.11:3000` one gets a 301, and the redirect works in wget and iOS, but not in Android:

```sh
> wget http://192.168.2.11:3000/sockjs/info?cb=3mgtkfzau5
--2016-05-05 11:55:55--  http://192.168.2.11:3000/sockjs/info?cb=3mgtkfzau5
Connecting to 192.168.2.11:3000... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://localhost:3000//sockjs/info?cb=3mgtkfzau5 [following]
--2016-05-05 11:55:55--  http://localhost:3000//sockjs/info?cb=3mgtkfzau5
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:3000... failed: Connection refused.
Connecting to localhost|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'info?cb=3mgtkfzau5'

info?cb=3mgtkfzau5                        [ <=>                                                                       ]      79  --.-KB/s   in 0s     

2016-05-05 11:55:55 (6.85 MB/s) - 'info?cb=3mgtkfzau5' saved [79]

> cat info\?cb\=3mgtkfzau5 
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":3944947841}macbook:vet2pet me$  git:(upstream ⚡ detached@dffb470) 2M 2A 

> wget http://localhost:3000/sockjs/info?cb=lcawemwgsg
--2016-05-05 11:56:29--  http://localhost:3000/sockjs/info?cb=lcawemwgsg
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:3000... failed: Connection refused.
Connecting to localhost|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'info?cb=lcawemwgsg'

info?cb=lcawemwgsg                        [ <=>                                                                       ]      79  --.-KB/s   in 0s     

2016-05-05 11:56:29 (6.85 MB/s) - 'info?cb=lcawemwgsg' saved [79]

> cat info\?cb\=lcawemwgsg 
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":2698190686}
```

**Comment by lorensr** [comment]
One weird thing is the double `//` in the redirect, maybe android doesn't like that:

`http://localhost:3000//sockjs/info?cb=3mgtkfzau5`

**Comment by lorensr** [comment]
Nevermind, not working on iOS either:

![image](https://cloud.githubusercontent.com/assets/251288/15049309/b03e8cba-12bb-11e6-82de-494c6d71402b.png)

Originally it was working on iOS, will try to get back to that.

**Comment by lorensr** [comment]
Went back to commits when I remember iOS connecting, but it doesn't anymore. I'm stumped 😝

**Comment by lorensr** [comment]
It was the fault of `wizonesolutions:canonical`. Thanks for your help!

**Comment by guillim** [comment]
I spent hours digging until I Found your post @lorensr! tks, I had the exact same wizonesolutions:canonical package. You may have saved a couple more hours of my life :)

Thank you very much

**Comment by guillim** [comment]
How did you deal with the package then @lorensr  ? did you remove it or, did you adapt your code ? I would love to keep this package for the website part, but it is a problem for the apps. If I could avoid splitting my project into web | apps that would save some time

**Comment by lorensr** [comment]
Sorry, I just removed it 😊

**Comment by guillim** [comment]
ok. tks for your answer
