### ISSUE TITLE
//@ sourceURL' and '//@ sourceMappingURL' are deprecated

### ISSUE THREAD

**Issue by tdsfugal** [meteor/meteor#6973]
Am getting the following warning in Chrome Version 50.0.2661.86 on OS X 10.10.5

'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.'  at codeschool_devtools.js:1

I get the warning even on a fresh release 1.3.2.4 "meteor create" with no modifications.

**Comment by abernix** [comment]
This is not coming from Meteor.  It's coming from your [CodeSchool Discover DevTools Companion Chrome Extension](https://chrome.google.com/webstore/detail/discover-devtools-compani/angkfkebojeancgemegoedelbnjgcgme?hl=en) which you have installed in your local web browser.  It will go away if you disable that Chrome extension.

**Comment by tdsfugal** [comment]
Thanks.  Didn't know it was installed.  My bad.
