### ISSUE TITLE
Invalid documentation for Meteor.apply

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6984]
It seems there is some bug in how `Meteor.apply` documentation renders: http://docs.meteor.com/#/full/meteor_apply

The signature is:

```
Meteor.apply(name, args, [options], (Boolean), [asyncCallback])
```

But this boolean is part of options in fact. Also `noRetry` is described not as part of options.

I think this was introduced with `noRetry` flag.

**Comment by stubailo** [comment]
Already fixed: https://github.com/meteor/meteor/commit/70209d91abe1703986a4b47d86648ecbab24048f

I think @tmeasday is waiting on the new docs refactor to land before redeploying the docs?

**Comment by tmeasday** [comment]
Correct, yeah, sorry new docs launch is days away
