### ISSUE TITLE
version 1.2.1 on ubuntu 14.04 server 64 bit, mongos does not support setName result in MONGO_OPLOG_URL failure

### ISSUE THREAD

**Issue by fuyinhai** [meteor/meteor#6985]
1> I'm using mongos as mongo server
2> I started meteor through command
     MONGO_URL="mongodb://mongoserver:27017/demo"  
     MONGO_OPLOG_URL="mongodb://mongorepl:27017/local"
3> When I start meteor app would report
    $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set

**Comment by laosb** [comment]
Didn't see the relationship between your title and your content. Would you please make it clear?

**Comment by fuyinhai** [comment]
the root cause:
    oplog_tailing.js checked isMasterDoc.documents[0].setName, but my mongos environment don't have the setName api

**Comment by fuyinhai** [comment]
thanks @lorensr

**Comment by lorensr** [comment]
Is this a problem with your mongos or with Meteor? If Meteor, does the problem still happen if you try doing the same steps with an empty repository (created with `meteor create`)?

Thanks!

**Comment by fuyinhai** [comment]
it's a problem of meteor due to the code:
    ~/.meteor/packages/mongo/1.1.3/os/oplog_tailing.js  isMasterDoc.documents[0].setName, there actually no setName method exists, when I just remove the code block isMasterDoc.documents[0].setName it works well

`    // Now, make sure that there actually is a repl set here. If not, oplog
    // tailing won't ever find anything!
    var f = new Future;
    self._oplogLastEntryConnection.db.admin().command(
      { ismaster: 1 }, f.resolver());
    var isMasterDoc = f.wait();
    if (!(isMasterDoc && isMasterDoc.documents && isMasterDoc.documents[0] &&
          isMasterDoc.documents[0].setName)) {
      throw Error("$MONGO_OPLOG_URL must be set to the 'local' database of " +
                  "a Mongo replica set");
    }
`

**Comment by laosb** [comment]
That code block must be there for some reasons. The code block you mentioned lives in https://github.com/meteor/meteor/blob/devel/packages/mongo/oplog_tailing.js#L208 in this repo, and some core developers should try to figure out a solution.

**Comment by abernix** [comment]
This happens when oplog tailing is not setup properly.   Oplog tailing is not super easy to setup correctly and I don't necessarily recommend doing it yourself.  Polling is generally fine in development, but it's best if you let the `meteor-tool` do it for you by not setting `MONGO_URL`, in which case it will start it's own server with oplog enabled.

This is coincidentally a duplicate of an issue I just responded to: #6015.  See there for the full explanation.
