### ISSUE TITLE
ReactiveDict.setDefault does not allow Object argument like ReactiveDict.set

### ISSUE THREAD

**Issue by DrDanRyan** [meteor/meteor#6992]
Currently using `reactive-dict` 1.1.7.  After some painful troubleshooting I realized that the `setDefault` method does not handle the case where the argument is an object like the `set` method does. The documentation for `Session` in the API docs says that:

> Set a variable in the session if it hasn't been set before. Otherwise works exactly the same as Session.set.

For this to be true, it should check whether the argument is an object and if it is, iterate over the keys calling `setDefault` on each one.

**Comment by stubailo** [comment]
This is correct, based on a cursory inspection of the code: https://github.com/meteor/meteor/blob/97578f2fcad30bc84a9c6d41b65fe71f39ff946f/packages/reactive-dict/reactive-dict.js#L82

Should be pretty easy to fix, by adopting the same strategy as `set` and `_setObject` here: https://github.com/meteor/meteor/blob/97578f2fcad30bc84a9c6d41b65fe71f39ff946f/packages/reactive-dict/reactive-dict.js#L193

Looking forward to the pull request!
