### ISSUE TITLE
Install button on meteor.com not working

### ISSUE THREAD

**Issue by Dev1an** [meteor/meteor#6994]
The "install" and "tutorial" button on Meteor's home page are not working in Safari.

Reproduction:
- Open Safari.app
- Go to https://www.meteor.com
- Click on the red button 'INSTALL NOW'

Current behavior: Nothing happens
Expected behavior: Goto meteor.com/install

Running Mac OS 10.11.4
Safari 9.1

**Comment by alexandesigner** [comment]
The solution is simple, how can I do it? Is only a small change in style

![captura de tela 2016-05-07 as 01 21 53](https://cloud.githubusercontent.com/assets/3044907/15090161/266dbc3a-13f2-11e6-873c-78e574fd669e.png)

**Comment by laosb** [comment]
@alexandesigner www.meteor.com is an private repo which we don't have access to.

**Comment by alexandesigner** [comment]
It was the imagine. So, with that little change (pic) solve the problem of the buttons ...

**Comment by danahmadi** [comment]
Thank you to @Dev1an for submitting this issue and to @alexandesigner for the suggested fix. This issue is now resolved.
