### ISSUE TITLE
Cyclic dependencies are possible across platforms

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6996]
Meteor supports multiple platforms (client, server). In my large graph of dependencies it happens that `package1` depends on `package2` on the client, but `package2` depends on `package1` on the server. (In reality, is much more complicated why something like that happens, but this is the result.) Such dependencies could be resolved without problems when loading each code on each platform, but Meteor still complains that there is a cycle between packages. This is too restrictive.

**Comment by mitar** [comment]
Reproduction: https://github.com/mitar/meteor-issue6996

**Comment by tmeasday** [comment]
Can we consider a workaround?

I never understood what using on the client was supposed to mean. 

A fix for this would be highly involved and not inline with moving to npm which does not have this concept.

**Comment by mitar** [comment]
What? Why closing this ticket? This is a bug report, things do not work as advertised. It might be hard to do it, I can understand that it would be low priority (probably impacts not many people), but it simply does not work as it is.

And what is a workaround?

**Comment by tmeasday** [comment]
I'm closing it because I can say with confidence it won't be fixed. That's
the idea here.

I'm not sure about a workaround, I'm offering to help figure one out, but
I'll need more information to help do that.

**Comment by mitar** [comment]
> I'm closing it because I can say with confidence it won't be fixed.

Even if community provides a pull request?
