### ISSUE TITLE
Different mongo query statement in meteor and mongo shell

### ISSUE THREAD

**Issue by codelegant** [meteor/meteor#6998]
At the last of this tutorial [blaze/forms-and-events](https://www.meteor.com/tutorials/blaze/forms-and-events), use `Tasks.find({}, { sort: { createdAt: -1 } });`  to show newest tasks at the top.
But when I use statement  `db.tasks.find({},{sort:{createdAt:-1}})`  in my mongo shell, it  _cause error_:
```
error: {
        "$err" : "Can't canonicalize query: BadValue Unsupported projection option: sort: { createdAt: -1.0 }",
        "code" : 17287
}
```
Which query can work on my mongo shell is `db.tasks.find().sort({createdAt:-1})`, but it _not worked in Meteor_.
I‘m very confused, is anybody can help me? Thanks for you.
PS:My Mongodb version is 3.2.6-64bit

**Comment by laosb** [comment]
Mongo shell uses really different syntax and just sometimes looks like the way you use in Meteor. That's not an actual problem. If you want to operate the DB in a Meteor way, try `meteor shell`.

**Comment by codelegant** [comment]
@laosb In the issue, I was use  `meteor mongo` to start the _shell_, is this make difference with `meteor shell`?

**Comment by laosb** [comment]
@codelegant `meteor mongo` starts an Mongo Shell, which uses its own syntax; `meteor shell` actually starts an Meteor server REPL, allowing you execute JavaScript on server. See: http://docs.meteor.com/#/full/meteorshell

**Comment by codelegant** [comment]
@laosb Thanks for your answer.
