### ISSUE TITLE
devDependencies should not be bundled in production

### ISSUE THREAD

**Issue by eXon** [meteor/meteor#7001]
When bundling an application to send it in production, the NPM modules are bundled. The problem I'm having is the dependencies are there, but also the devDependencies. This is a major problem if you're having a lot of devDependencies (and all Webpack users are having a lot :P).

Instead of having a 11 MB bundle, it is 64 MB which is aweful.

It would be important for Meteor to look at what are the project dependencies, bundle them and ignore devDependencies. I would expect it to do so.

Meteor version I'm running is 1.3.2.4 on Mac. This issue might be related to #6836

**Comment by eXon** [comment]
FYI `webpack:webpack` was already bundling only dependencies and ignoring devDependencies before Meteor was supporting NPM. Here is the code I was using: https://github.com/thereactivestack/meteor-webpack/blob/15954e9c9c6da6bdbbff69963c193adc5865121f/packages/webpack/plugin/WebpackCompiler.js#L634-L684

**Comment by tcastelli** [comment]
I think this was already stated here https://github.com/meteor/meteor/issues/6836

**Comment by tmeasday** [comment]
Can we get a simple reproduction? My understanding is only want you import is bundled but I might have that wrong

**Comment by eXon** [comment]
@tmeasday 

```sh
meteor create test-dev-dependencies
cd test-dev-dependencies
npm init
npm install --save-dev webpack
meteor bundle test
tar -xzvf test.tar.gz
cd bundle/programs/server/npm/node_modules
ls
```

And you'll see your entire node_modules content has been copied there (and webpack has A LOT).

**Comment by feit** [comment]
I think the big bundle size also make boot time increase

**Comment by benjamn** [comment]
Here's a better workaround: run [`npm prune --production`](https://github.com/npm/npm/issues/2854) before building/deploying.

**Comment by benjamn** [comment]
With the flattening that npm v3 does, indirect dependencies of production dependencies are often installed outside the directory tree of the package you're depending on, so any solution to this problem must know better than to remove such packages.

The `npm ls --production` command can also be helpful for figuring out which packages are actually needed in production, though it displays the logical dependency tree rather than displaying packages as they are installed on disk.

**Comment by benjamn** [comment]
Closing in favor of https://github.com/meteor/meteor/issues/6750.

**Comment by eXon** [comment]
@benjamn A workaround is not a fine solution IMHO. Especially when it is just an implementation detail that can be done seamlessly. A workaround should be the last solution for something that cannot be fixed without human interaction.

The script I pointed out is working with every NPM version including those with flattening. It finds them the same way Node.js does.
