### ISSUE TITLE
Meteor exits too soon on unhandled error

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7005]
Now, that we are moving to use Promises, it seems that Meteor immediate exit at an error can potentially hide unhandled promise rejections. I had a situation where there was an error in one of promises, and I was relaying on it being unhandled to get some error message about that to the console. But because there was an error in the promise, some other part of the code throw an exception, bringing down the whole Meteor app. The result is I have never seen that unhandled promise rejection because the console output happens at next tick, but runtime never got to the next tick.

Maybe Meteor could handle unhandled exceptions by delaying them with `setImmediate` as well. To allow the whole event cycle to finish.

**Comment by tmeasday** [comment]
I'm sort of confused. The exception that crashed the process didn't help you figure out what the problem was?

Can you provide some kind of reproduction?

**Comment by mitar** [comment]
No, because crash happens because of the failed promise. But promise "unhandled rejection" happens on nextTick, which is before the crash.

I will try to come up with something.

**Comment by mitar** [comment]
Hm, I think I will just close this bug. The issue is simply that in large applications it is hard to correctly depend on all promises you should be depending. So an exception is thrown because program gets into a unexpected state and information about why is that state is in a unhandled rejected promise somewhere else. Because Meteor exits immediately, it is not really possible to see that error in that unhandled promise.

**Comment by mitar** [comment]
This might even be node.js bug: https://github.com/nodejs/node/issues/6456

**Comment by mitar** [comment]
It seems on Windows there is already a workaround in Meteor: https://github.com/meteor/meteor/blob/devel/packages/meteor/flush-buffers-on-exit-in-windows.js
