### ISSUE TITLE
Meteor.isDevelopment not present in docs

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#7006]
if I type 'isdev' - it shows me that there is such a heading, but redirects me to http://docs.meteor.com/#/full/meteorguide.
ctrl+f doesnt find 'isdev' string as well.

**Comment by laosb** [comment]
It was mentioned in `History.md`:
> process.env.NODE_ENV is now defined on both client and server as either development or production, which also determines the boolean flags Meteor.isDevelopment and Meteor.isProduction.

I didn't realize it too:)

**Comment by gregorynicholas** [comment]
that's fun .   this is like a treasure-hunt .   the name of my next book, "hunting for meteor treasures around the entire source.. fun times and me"  call me ladies.

**Comment by abernix** [comment]
New docs will be up soon and will be much better and even easier to update.

**Comment by abernix** [comment]
It is in [the newly revamped Meteor Docs](http://docs.meteor.com) right over [here](https://docs.meteor.com/api/core.html#Meteor-isDevelopment).  Closing this – thanks for reporting it initially!
