### ISSUE TITLE
wrapAsync does not handle case where last non-callback argument is a function

### ISSUE THREAD

**Issue by DrDanRyan** [meteor/meteor#7010]
I discovered this after trying to wrap some of the functions from the very popular npm package `async`: if the last non-callback argument to the original (unwrapped) function is a function, then the wrapped function will always behave as if a callback was passed and will not behave in the fiber 'sync' style on the server. This happens because the wrapped function looks at the last argument and if it is a function, then it will assume that it is the callback.

For example, `async.map` has a signature:   `(collection, iteratee, callback)`, where `iteratee` is a function and required parameter.  So, you cannot use the result of `Meteor.wrapAsync(async.map)` on the server in a way that makes it wait for the result. If you omit the callback, then Meteor uses `iteratee` as a callback and you end up with garbage results and no sync style wait for the results.

However, this can be hacked by wrapping it in a function that changes the function arguments, like:

``` javascript
const mapFiber = Meteor.wrapAsync(myMap);

function myMap(iteratee, collection, cb) {
    async.map(collection, iteratee, cb);
}


// Later when you want to use it, you have to use the modified argument order
const result = mapFiber(iteratee, collection);
```

This is an easy enough workaround, but I wonder if there could be some option for `Meteor.wrapAsync` that would allow direct wrapping without changing argument order.  Maybe allowing the caller to specify the number of required non-callback function arguments?  Then, `wrapAsync` would know how far back in the argument list to go looking for the callback before deciding that there was none provided on the function call.  In the `map` case above, I could say there are 2 non-callback arguments and then `wrapAsync` would never consider the first two arguments fair game for being chosen as the callback.

**Comment by DrDanRyan** [comment]
I ended up writing my own function that just assumes that the wrapped function is always called without the callback (server only):

```javascript
function fiberize(fn, context) {
  return function() {
    const self = context || this;
    const fut = new Future();
    const cb = Meteor.bindEnvironment(fut.resolver());
    const newArgs = [..._.toArray(arguments), cb];
    fn.apply(self, newArgs);
    return fut.wait();
  };
}
```
This works great for wrapping npm server-side libraries.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=wrapAsync%20does%20not%20handle%20case%20where%20last%20non-callback%20argument%20is%20a%20function&body=Migrated%20from:%20meteor/meteor%237010) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
