### ISSUE TITLE
Avoid alert for meteor-node-stubs multiple times.

### ISSUE THREAD

**Issue by hlehmann** [meteor/meteor#7020]
One of my dependencies (Reflect-metadata) has:

```
let nodeCrypto = isNode && require('crypto');
```

so I always get this alert

```
Unable to resolve some modules:

  "crypto" in .../node_modules/reflect-metadata/Reflect.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-node-stubs 
```

Is there a way to avoid this alert other that installing meteor-node-stubs. On production I got:
- 536Ko with meteor-node-stubs
- 359Ko without meteor-node-stubs

**Comment by benjamn** [comment]
For what it's worth, that difference in size is due entirely to the `crypto` stub package. We only bundle the stubs that you use, and your code is "using" the `crypto` package as far as Meteor (or Webpack or Browerify or any other client-side bundling tool) can tell.

I'd be happy to consider a pull request that warns only once, but these warnings are too helpful to silence by default.

**Comment by ffxsam** [comment]
I'm using Sentry's node module (raven), and I get constant warnings about not having `pg` installed, even though it's a conditional import. I _really_ wish there was a way to silence this.

It's interesting to note that, at one point, doing this would silence warnings:

```js
const r = require;
const Raven = r('raven');
```

But that stopped working (unsure of exactly when or why). Not to mention, it's a bit of a hacky solution and wound up bombing in production for some reason, so I had to do that conditionally:

```js
  const r = require; // using r shortcut suppresses Raven dependency warnings
  Raven = process.env.NODE_ENV === 'development'
    ? r('raven')
    : require('raven');
```

Just my two cents.

**Comment by hwillson** [comment]
Hi @ffxsam - quick side note regarding conditional imports; the Meteor build tool still needs libraries requested by conditional `require`'s to be available at build time, so this warning really is accurate. In this specific case `raven` is requiring `pg` to see if it's available, which will be problematic for the Meteor build tool and other bundler's like webpack. They know this though, and are working on it via getsentry/raven-node#254 (as you've already noticed since you're the last commenter there 🙂).

**Comment by ffxsam** [comment]
So you're saying Meteor's build tool needs those packages, even if they're conditionally used?

https://github.com/getsentry/raven-node/blob/483b70ea486ffd0741c9eae6701e96c688bfcaa6/lib/breadcrumbs.js#L118-L120

But I'm ignoring the warning and using this app in production, without any issues.

**Comment by hwillson** [comment]
The Meteor build tool doesn't need the package; it's just giving you a heads up saying "hey, wait a sec - when I was bundling your code, I found a `require('pg')`, but you don't actually have that package installed - is this right?" The `raven` package dev's are using that `require('pg')` call to see if the `pg` package is available; if it isn't available, then they don't use it. The Meteor build tool (and webpack) can't differentiate between using `require` to check if a package is available, or using `require` to actually use a package. The safer assumption is that any `require` used really does mean that the package is needed, hence the warning. In `raven`'s case though, you can ignore the message and continue to use it without the `pg` package. When they address getsentry/raven-node#254, the warning will disappear.

**Comment by ffxsam** [comment]
That's what I thought. Just wanted to make sure! 😁

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Avoid%20alert%20for%20meteor-node-stubs%20multiple%20times.&body=Migrated%20from:%20meteor/meteor%237020) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
