### ISSUE TITLE
how can I to push .html to client without pageck blaze-html-templates

### ISSUE THREAD

**Issue by liiil825** [meteor/meteor#7025]
I use react and meteor, I want to write a html file to push client but I don't want to use blaze

Can I don't use pageck blaze-html-templates

**Comment by laosb** [comment]
By saying "write a html file to push client", do you mean an static html for further client AJAX? If so, you can simply place it in `/public`.

**Comment by laosb** [comment]
BTW, https://forums.meteor.com is a better place for discussions like that. Closing.

**Comment by liiil825** [comment]
thanks
