### ISSUE TITLE
"meteor test ... --once" does not terminate after tests have been run.

### ISSUE THREAD

**Issue by hg-stolle** [meteor/meteor#7027]
Hi!

I am trying to run test for a Meteor application on a CI server. At the moment I'm using Meteor 1.3.2.4. The test framework is Jasmine. I've added the packages

    sanjo:jasmine
    velocity:html-reporter
    velocity:console-reporter

for testing. Tests are started with this command:
`meteor test --port 3333 --driver-package sanjo:jasmine --full-app --once`
As far as I understand the parameter `--once`should take care that the applications terminates as soon as all tests have been run. However, the application starts and keeps running forever. All I can do is point my browser at http://<hostname>:3333/ to see the test results. However, I would rather like `meteor test` to run the tests and then terminate with exit code 0, if all tests have been successful, or a non-zero exit code, if any of the tests have failed. This way the CI server could easily check, whether any test have failed.
Is there a way to do this with Meteor 1.3.2.4 and Jasmine?

Thanks in advance for your help and suggestions.

**Comment by abernix** [comment]
You are right that the `--once` flag *should* provide that functionality, but the implementation is currently not in place by the `sanjo:jasmine` package, [as noted here in that package's History](https://github.com/xolvio/meteor-jasmine/blob/master/History.md#100).   The package itself has xolvio/meteor-jasmine#335 open to track this and #6755 (via #6809) is open on the Meteor side to provide the `--once` functionality that `sanjo:jasmine` needs.

Closing this in favor of the other issues.  Please "+1" those other issues if they are important to you! :smile:
