### ISSUE TITLE
Import chain not clear in the app structure guide

### ISSUE THREAD

**Issue by talkoren** [meteor/meteor#7028]
The [app structure guide](http://guide.meteor.com/structure.html) does not elaborate the (non-trivial) import chain that it requires. Had to reach [this thread](https://forums.meteor.com/t/import-best-practices/20818/26) to figure it out. Opened this issue per @stubailo's request.

**Comment by abernix** [comment]
Just FYI, the Guide Repo is [over here now](//github.com/meteor/guide).  Moving this there and closing here.

**Comment by talkoren** [comment]
Thanks.
