### ISSUE TITLE
[1.2.1] Cordova build fails on second run due to deleted cordova-plugin-compat plugin

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#7029]
Since about one month, I am experiencing the following behaviour:

If I run `meteor run xxx-device` for the first time, the build works as before. But as soon as I do a second run, the build always fails, with this error message:

```
% "cordova-plugin-file" is required by (cordova-plugin-file-transfer) and cannot be removed (hint: use -f or --force) and cannot be removed (hint: use -f or --force)
=> Errors executing Cordova commands:         

   While removing plugins                     
   com.concats.cordova-plist-patches,com.meteor.cordova-update,com.percolatestudio.cordova.safereload,cordova-plugin-compat,cordova-plugin-console,cordova-plugin-crosswalk-webview,cordova-plugin-device,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-globalization,cordova-plugin-iosrtc,cordova-plugin-legacy-whitelist,cordova-plugin-splashscreen,cordova-plugin-statusbar,io.guzz.cordova-xcode-config-guzz,io.guzz.cordova.webrtc.permissions,cordova-plugin-insomnia,cordova-plugin-camera,phonegap-plugin-push
   from Cordova project:
   Cordova error: Cannot find plugin.xml for plugin 'cordova-plugin-compat'. Please try adding it again.
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You
   can try running again with the --verbose option to help diagnose the issue.)

ExitWithCode:1
```

I believe I could track this down to its root cause. About a month ago, the Cordova team introduced this new plugin: https://github.com/apache/cordova-plugin-compat. It seems as if the latest Cordova CLI tools automatically add this plugin to the project. If I do the first Cordova build, the plugin shows up in the cordova-build folder and everything works as expected.

But as soon as I execute `meteor run xxx-device` for the second time, Meteor seems to uninstall all plugins first (due to whatever reason) before the cordova build is initiated again. If I watch this folder, I can see the plugins disappear one after another, and as soon as the plugin folder for `cordova-plugin-compat` is removed, the uninstall process breaks with this error message. It seems as if this plugin is required somehow during the uninstall process.

If I remove the whole cordova-build folder before running `meteor run xxx-device`, everything works again. But this also causes Meteor to download all plugins again, which takes about 20 minutes for me, due to a slow connection to Github and a large plugin.

BTW: If I run `cordova build` in the cordova-build folder manually, the CLI tells me that its usage is deprecated for the Cordova Android and Cordova iOS version Meteor uses. So I am asking myself which CLI version I should install for Meteor 1.2 instead to avoid incompatibilities?

**Comment by derwaldgeist** [comment]
There's kind of a workaround: If you add ```cordova-plugin-compat@1.0.0``` to the cordova-plugins file, the error won't show up again until you change something in your plugins configuration. I can only guess that the "missing" ```cordova-plugin-compat``` plugin is also the reason why Meteor tries to re-install all plugins on the second run. If I add ```cordova-plugin-compat@1.0.0``` to the cordova plugins, it won't do this anymore. But unfortunately a change to the plugins configuration (adding or removing another plugin) will cause the build to fail again. So it's not a permanent workaround.

**Comment by abernix** [comment]
Please provide very precise reproduction steps.  Is this something we can reproduce on a brand new project by simply running it twice?  If not, could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction or at least very easy to reproduce steps, it's very difficult to help.

**Comment by derwaldgeist** [comment]
Ok, I'll try to provide a reproduction repo.

**Comment by abernix** [comment]
Any updates on this @derwaldgeist?  I've seen a couple other issues regarding nuances with first run vs second run Cordova issues (though the only I can find at the moment is #6978) but haven't been able to put a finger on what the problem is.  Admittedly, Cordova is not my specialty and I don't use it on a regular basis.

**Comment by derwaldgeist** [comment]
Hi @abernix It's very hard to produce this error in a clean-room repo. For the past monts, I lived with my work-around adding the cordova-compat-plugin manually. This worked fine until I added the PayPal mobile cordova plugin just recently. From this time on, each second build will fail again, despite of my adding the compat plugin manually. Obviously, this is related to a specific combination of Cordova plugins or plugin versions. Still have no clue what actually causes this weird build problem. BTW: Each time this happens, the Meteor process gets stuck and I have to kill -9 it.

**Comment by derwaldgeist** [comment]
Some more infos on this. If I run meteor in verbose mode, I am getting this:

```
Preparing Cordova project from app bundle     
Processing mobile-config.js                   
Copying resources for mobile apps             
Writing new config.xml                        
Removing plugins                              
com.concats.cordova-plist-patches,cordova-plugin-console,cordova-plugin-crosswalk-webview,cordova-plugin-customurlscheme,cordova-plugin-device,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-globalization,cordova-plugin-inappbrowser,cordova-plugin-iosrtc,cordova-plugin-legacy-whitelist,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-x-socialsharing,io.guzz.cordova-ios10-patches,io.guzz.cordova-xcode-config-guzz,io.guzz.cordova.webrtc.permissions,cordova-plugin-insomnia,cordova-plugin-camera,phonegap-plugin-push
from Cordova project
% Plugin "cordova-plugin-insomnia" is not present in the project. Converting value to "nl.x-services.plugins.insomnia" and trying again.
% Plugin "cordova-plugin-camera" is not present in the project. Converting value to "org.apache.cordova.camera" and trying again.
% Uninstalling cordova-plugin-legacy-whitelist from android
% Uninstalling cordova-plugin-inappbrowser from android
% Uninstalling cordova-plugin-globalization from android
% Uninstalling cordova-plugin-file-transfer from android
% Uninstalling cordova-plugin-file from android
% Uninstalling cordova-plugin-device from android
% Uninstalling cordova-plugin-customurlscheme from android
% Uninstalling cordova-plugin-crosswalk-webview from android
% Error during processing of action! Attempting to revert...
% Uninstalling cordova-plugin-console from android
% Uninstalling com.concats.cordova-plist-patches from android
% Uninstalling phonegap-plugin-push from android
=> Errors executing Cordova commands:         
                                              
   While removing plugins                     
   com.concats.cordova-plist-patches,cordova-plugin-console,cordova-plugin-crosswalk-webview,cordova-plugin-customurlscheme,cordova-plugin-device,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-globalization,cordova-plugin-inappbrowser,cordova-plugin-iosrtc,cordova-plugin-legacy-whitelist,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-x-socialsharing,io.guzz.cordova-ios10-patches,io.guzz.cordova-xcode-config-guzz,io.guzz.cordova.webrtc.permissions,cordova-plugin-insomnia,cordova-plugin-camera,phonegap-plugin-push
   from Cordova project:
   Cordova error: CordovaError: Cannot find plugin.xml for plugin 'cordova-plugin-compat'. Please try adding it
   again.
   at new PluginInfo
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/PluginInfo.js:329:15)
   at PluginInfoProvider.get
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/PluginInfoProvider.js:35:32)
   at
   /Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/prepare.js:80:45
   at Array.forEach (native)
   at Object.handlePrepare
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/prepare.js:78:24)
   at
   /Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:341:28
   at _fulfilled
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
   at flush
   (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.10.81akj5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You
   can try running again with the --verbose option to help diagnose the issue.)
                                              
ExitWithCode:1
```
This shows that Meteor removes all Cordova plugins once it has written the new config.xml file. There must be a reason why Meteor does this, and obviously it should not delete the cordova-plugin-compat plugin before all other plugins have been deleted.

**Comment by derwaldgeist** [comment]
Also found the code that is deciding whether it is necessary to delete all plugins, it starts here:
https://github.com/meteor/meteor/blob/693fce59be5240801e762a7288283a96ab154af4/tools/cordova/project.js#L571
According to the code, this should only happen if one plugin has changed its version or if plugins have been added/removed. Why this is being triggered on every run xxx-device is mysterious.

**Comment by derwaldgeist** [comment]
I was now able to reproduce the problem and created a new issue including a reproduction repo here: #8196 

Closing this one to cut this thread.
