### ISSUE TITLE
Extensive Use of Try...Catch Causes V8 Deoptimization

### ISSUE THREAD

**Issue by jlukic** [meteor/meteor#7034]
I've noticed many functions in Meteor, including [Tracker](https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L322) and [Blaze](https://github.com/meteor/blaze/blob/master/packages/blaze/view.js#L534) wrap essential function calls like `compute` in `try..catch` syntax.

In current versions of V8 shipping with Chrome, using `try/catch` causes V8 to "bail out" of some compiler optimizations.

It appears in [some examples](http://ryanmorr.com/reinventing-the-try-catch-block/) performance inside try/catch [may suffer](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) up to 90% over similar code. 

Since a lot of reactivity in Meteor stems from tracker, this seems like it could be a big win for Meteor performance in Chrome, which for a lot of people who use Meteor with Electron or similar situations might be the _only_ targetable browser.

This will probably be solved whenever chrome gets around to launching ["TurboFan"](https://groups.google.com/forum/#!msg/v8-dev/ab8V5Z58_70/5-05DvysCt8J) their new compiler replaces Crankshaft in stable, but unfortunately we can't predict how long that will be.

Here's a screenshot to show, dev tools will also make very clear that you are using a `deopt`
![foo](https://dl.dropboxusercontent.com/u/2657007/not-optimized.jpg)

**Comment by zol** [comment]
Hey @jlukic. Have you identified places in the code where try...catch clauses could be refactored with the original semantics maintained? I'm going to leave this issue open for now but don't suspect much will happen on it without a clear path forward with obvious benefits.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Extensive%20Use%20of%20Try...Catch%20Causes%20V8%20Deoptimization&body=Migrated%20from:%20meteor/meteor%237034) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
