### ISSUE TITLE
[ddp-rate-limiter] Collection Subscriptions not Limiting

### ISSUE THREAD

**Issue by thiagof** [meteor/meteor#7053]
My use-case is to rate the number of updates a certain Collection gives.

    Meteor.publish('orderbooks', function(pair)
    {
        return OrderBooks.find({ pair: pair });
    });

The OrderBooks collection updates once per 500 miliseconds.
But I want to update the interface only once per 1000 miliseconds.

So I got:

    DDPRateLimiter.addRule({
        name: 'orderbooks',
        type: 'subscription',
        connectionId() { console.log(arguments); return true; },
    }, 1, 1000);

But no, the UI still receives every update, once per 500 miliseconds

**Comment by laosb** [comment]
In my view the DDP rate limiter only limits the subscriptions, not the updates in this subscriptions. But, yeah, if we have this function (having a limit on DDP messaging rate) that will be good. Closing but feel free to reopen if I'm wrong.

**Comment by thiagof** [comment]
Yes, youre right.

But seems to be possible to limit the update interval with `pollingIntervalMs` and `pollingThrottleMs` params to the find method

http://docs.meteor.com/#/full/find
