### ISSUE TITLE
Meteor default re-exports don't work

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7056]
With ES6 modules, you should be able to re-export the default export of another file. In Meteor, this doesn't work.

Example:
```javascript
// default-test/test.js
export default 'test';

// default-test/index.js
export default from './test';
export test from './test';

// main.js
import testDefault, {test} from './default-test';

console.log(testDefault) // undefined
console.log(test) // undefined
```

[Reproduction](https://github.com/clayne11/meteor-reexport-bug)

**Comment by laosb** [comment]
Ah, get it.

**Comment by mjmasn** [comment]
Works for me with:

```javascript
export { default as default } from './test';
```

**Comment by abernix** [comment]
The exact syntax used in your reproduction is [actually not in the ES6 specification](http://www.ecma-international.org/ecma-262/6.0/#sec-exports).  [See discussion here](https://esdiscuss.org/topic/re-export-default) (where it's admittedly an oversight), but also see [the pending tc39 proposals here](https://github.com/tc39/proposals) which should fix that.

Specifically the two championed by Lee Byron:
* [`export v from "mod";` statements](https://github.com/leebyron/ecmascript-export-default-from)
* [`export * as ns from "mod";` statements](https://github.com/leebyron/ecmascript-export-ns-from)

Unfortunately, they also didn't make it into ES7 but whenever it lands it will become supported as soon as possible.

Regardless, you can still achieve what you want with ES6.  Remember, `default` is (just) a named export so in this case you can:

* Replace `export default from './test';` with `export { default } from './test';`
* Replace `export namedTest from './named-test';` with `export { default as namedTest } from './named-test';`
