### ISSUE TITLE
`meteor mongo` only works with built-in mongo

### ISSUE THREAD

**Issue by nicodmf** [meteor/meteor#7064]
Versions:
Meteor: 1.3.2.4
Configuration in development mode : 
- one docker container for meteor
- one docker container for mongodb (3.0)

The `meteor mongo` command doesn't work even with a right $MONGO_URL variable in the environenment. After reading the code : 

https://github.com/meteor/meteor/blob/abd574f38008b45f5e2a6bc322b10bcdde44763a/tools/cli/commands.js#L1134

It's seems that meteor mongo could take an argument, but even with an argument, this doesn't work for dark reasons (Sorry, Meteor does not yet support specific path URLs,).

But with meteor shell, i can use the database and insert document.

As docker is even a development system that a production system, and anyway that to have a mongodb in different server is a usually process, i think the meteor mongo should be upgraded tio work with a distant database.

At less the message should be changed.

Best Regards

**Comment by nicodmf** [comment]
The more angriest with this command is that if i change code and indicate my server this works...

**Comment by abernix** [comment]
You can also just use `mongo mongodb://..` but I suppose it *might* make sense for the `meteor-tool` to be able to connect as well.

I wonder if it wouldn't be best to use the same functionality as `meteor npm` though and simply proxy the request to the built-in `mongo` so you could do `meteor mongo mongodb://...`.  If it can discover the local server's `MONGO_URL` or it's set in the ENV, then it could set it for you.

But then there's the question of what to do with the rest of the mongo commands: `mongodump`, `mongoexport`, `mongoimport`, `mongorestore`, `mongotop`, etc., etc., etc. ?

**Comment by abernix** [comment]
The expectation right now is that if you're running your own Mongo server and setting it with `MONGO_URL`, you know how to use the built-in `mongo` tools directly.

**Comment by laosb** [comment]
The argument is used by Meteor Free Hosting, and I'm not sure if it still works on Galaxy. Back to that time it's pretty useful to do `meteor mongo xxx.meteor.com`.

**Comment by abernix** [comment]
@laosb That hasn't changed though, right?  I don't see why that would have stopped working.  This is basically asking to make it possible to connect `meteor mongo` to non-Galaxy, non-Free-Hosting, non-built-in Mongo.

**Comment by nicodmf** [comment]
As i say on #7068 : I'm not sure that is just a feature, for me at least at beginning this was more a bug or a correction. The process is not clear :

- you can connect distant db on deployment
- but not near db in dev

This is at least a strange effect.

**Comment by nicodmf** [comment]
I tested the mongo address mongodb:// as argument, it didn't work for me.

**Comment by nicodmf** [comment]
Sory, i see the point on the entire process, for the moment, i prefer let you arguee on all other commands independently, as i tought that there are not meteor core commands.

**Comment by laosb** [comment]
@abernix Yeah, I'm clarifying what the argument used for. In my PR I just add few lines to detect if `MONGO_URL` exists.

**Comment by laosb** [comment]
#7077 is my PR which would read `MONGO_URL` when in a app but doesn't have a builtin mongo.

**Comment by abernix** [comment]
@laosb You basically re-submitted the same exact PR that @nicodmf already opened and was already closed by Tom.  We need to confirm features **before** they are turned into PRs, including discussing various options, what (if any) tests need to be written, and potentially breaking changes, oversights, etc.

I think it's a good idea to support using different `mongodb://`'s.

To [quote compose.io about using Meteor with Compose.io](https://www.compose.io/articles/meteor-and-compose-a-beginners-guide-to-using-them-together/):

> you'll have to deviate from the tutorial slightly. This is because the tutorial suggests you use the `meteor mongo` command to connect to your MongoDB. The problem is that that command only works with local or Meteor-deployed instances of MongoDB. **It's a bit of an oversight**, and it means you'll have to install the Mongo shell on your system to connect up and to do that, you'll need to usually need the rest of MongoDB with it.

They basically say it's an oversight of the Meteor tool to _not_ support using a remote DB.

But I'll ask again:
>I wonder if it wouldn't be best to use the same functionality as `meteor npm` though and simply proxy the request to the built-in mongo so you could do meteor mongo mongodb://.... If it can discover the local server's MONGO_URL or it's set in the ENV, then it could set it for you.

I'm not even sure if `MONGO_URL` should be the primary way of using this.  It's very nice that Meteor bundles `node` and `npm` for ease-of-use to the end-user – you can run `meteor npm [whatever]` the same as `npm [whatever]`.  It might be nice if `meteor mongo` copied this as much as possible, allowing `meteor mongo [options] [db address] [file names (ending in .js)]` (see `mongo --help`).  If nothing was passed, then it would automatically work the same as before.  For size reasons, the dev bundle does not come bundled with the other mongo tools like `mongodump` (8.8Mb), but they could be easily added in the future.

**Comment by nicodmf** [comment]
I'm agree with you meteor mongo [options] [db address] [file names (ending in .js)] should be a very good feature, but actually the deployment option take all arguments place. 

So the change is BC that can cause problem for person using the deployement option.

**Comment by abernix** [comment]
Meteor Free hosting doesn't exist anymore and I don't think (highly doubt) this works with Galaxy in any way since it doesn't provide Mongo but instead suggests using a Mongo provider.

So I don't think there is a "deployment option".  Thus, this might be even easier as there is no need to account for not breaking deployments.

**Comment by nicodmf** [comment]
In this case this could simplify the work and the code will be more a shorcut to mongo command this the advantage to take env and other variable from meteor.

And surely more clear too as this part wasn't the better code written, i think.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20mongo%60%20only%20works%20with%20built-in%20mongo&body=Migrated%20from:%20meteor/meteor%237064) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
