### ISSUE TITLE
'meteor/meteor' is not found when required in a NPM used on the server side

### ISSUE THREAD

**Issue by barbatus** [meteor/meteor#7065]
Current behavior:
Please check out a simple app https://github.com/barbatus/app along with a NPM package that requires `meteor/meteor`. If you run the app, there will be an `Cannot find module 'meteor/meteor` exception thrown. Seems to happen only if that NPM is required on the server side.

Expected behavior:
No exception is raised when `meteor/meteor` is required in a NPM that is used on the server side.

Meteor version: 1.3.2.4

Seems related to the order NPMs are defined and loaded.

**Comment by stubailo** [comment]
I think in current releases of Meteor, NPM packages can't depend or load Meteor packages. See the Meteor guide for more information about when to use an NPM package, and when to use a Meteor/Atmosphere package: http://guide.meteor.com/atmosphere-vs-npm.html#when-atmosphere

**Comment by barbatus** [comment]
@stubailo how come then it works on the client? As you know, Meteor creates `modules.js` file where all NPMs used across the code are bundled together as well as NPM stubs like `meteor/meteor` etc are installed. One might expect the same behavior in the server side's `modules.js` as well.

**Comment by barbatus** [comment]
Also in the link above in the section 'When to use atmosphere package', it says for example `Get direct access to Meteor’s package namespacing and package global exports without having to explicitly use ES2015 import`. Does that mean that  I can use explicit ES2015 imports in NPMs for Meteor namespaces?

**Comment by stubailo** [comment]
Not that I know of, I think this is referring to the fact that you don't need to use modules at all. @benjamn did I correctly answer this?

**Comment by benjamn** [comment]
Sashko is right: on the server, we use Node itself to import modules in `node_modules`, so there is no difference between Meteor and Node, but one of the drawbacks of that choice is that there is no package called `meteor` visible to Node, which means `meteor/<package>` module identifiers are no longer available to server-side `node_modules`. On the client, of course we can't use Node, and that means it's easier to define stubs for Meteor packages under the `meteor/...` namespace.

**Comment by benjamn** [comment]
Concretely, I think the best solution to this problem is to expose an API method from your server-side npm package that accepts the `Meteor` namespace object as an argument, rather than calling `require("meteor/meteor")` from within the npm package.
