### ISSUE TITLE
Webtorrent in Meteor fails when loaded via NPM. Not via CDN

### ISSUE THREAD

**Issue by FinnFrotscher** [meteor/meteor#7067]
When I import the `webtorrent` package via `import  WebTorrent  from 'webtorrent'` and try to set up the package with `var client = new WebTorrent()` I get 
 
    tcp-pool.js:22 Uncaught TypeError: net.createServer is not a function
But when I use `$.ajax()` to load the `CDN` hosted version it works. 

This is both `clientside` running `1.3`.

**Comment by abernix** [comment]
As the author of `webtorrent` wrote on #6890, this is because that package uses the object form of the `browser` field in `package.json`.  Going to track this in the existing issue, #6890 and close this one.

Thanks for bringing it to our attention!
