### ISSUE TITLE
Minor issue on the AngularJS task list tutorial

### ISSUE THREAD

**Issue by Lance61** [meteor/meteor#7071]
I'm using the latest version of Meteor on a Windows 10 OS.  I have installed the Meteor-Angular extension and I'm following the "simple-todos" tutorial.

The example at 7.3 did not work:
```
            createdAt: -1
          }
        });
      },
      incompleteCount() {
        return Tasks.find({
          checked: {
            $ne: true
          }
        }).count();
      }
    })
  }
```

I placed parenthesis around the entire return statement and it worked:
```
        return (Tasks.find({
          checked: {
            $ne: true
          }
        }).count());
```

This was not a serious attempt at debugging, but just an informed guess by someone new to the platform.

Hope this helps.

**Comment by Lance61** [comment]
That quick fudge causes other issues, while this appears to fix it:
```
        return Tasks.find({}, {
          checked: {
            $ne: true
          }
        }).count();
```

**Comment by stubailo** [comment]
Neither of the code snippets you posted as a solution should have fixed it, I suspect there is some other issue in your code that isn't shown in these snippets. Can you please post a request for help on the forums, preferably with a link to download your code?

You can always use the GitHub links from the tutorial to compare all of your app's code.

**Comment by Lance61** [comment]
You were right - there was a second "<body>" tag in the html. Apologies.
