### ISSUE TITLE
Can't require app's npm packages from build plugins

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7073]
Reproduction: https://github.com/tmeasday/build-plugin-require

See https://github.com/juliancwirko/meteor-postcss/issues/15

@benjamn can you mark the issue confirmed if my repro makes sense to you

**Comment by tmeasday** [comment]
(Marking `impact:some` because of the related postcss issue. Not sure if this is fair or not

**Comment by benjamn** [comment]
The new way to do this in `1.3.3-beta.0` is to call `inputFile.require(id)`.
