### ISSUE TITLE
Better error insight into Meteor validated methods

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7074]
I'm on Meteor 1.3.2.4, and I'm having a tough time debugging validated methods. Here's an example of what I'm seeing:

So, I get an error such as the following:

![title_here](https://cloud.githubusercontent.com/assets/12532733/15341610/8cb85c8e-1c44-11e6-8749-837bede04dae.png)

If I click on the `coments.js:8` reference, I see this:

![title_here](https://cloud.githubusercontent.com/assets/12532733/15341623/ab62776e-1c44-11e6-84b7-b9e8e2f7c8a4.png)

Great, but the next error is in `validated-method.js:71` which is this:

![title_here](https://cloud.githubusercontent.com/assets/12532733/15341642/c61d3710-1c44-11e6-864d-18473666d26e.png)

So this doesn't really help me pinpoint the problem. And there's no mention of `length` in my method code, actually.

**Comment by abernix** [comment]
Absolutely.  This is a matter of the need for (better) source-mapping in-general. Combining with #7076 which also came in this morning.
