### ISSUE TITLE
Improve Source Mapping

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7076]
If package `foo:bar` has file `path/to/file.js`, I would expect errors from that file to be something like

```
W20160517-22:34:04.667(-7)? (STDERR)     at Package (packages/foo:bar/path/to/file.js:123:45)
```

or

```
W20160517-22:34:04.667(-7)? (STDERR)     at Package (foo:bar/path/to/file.js:123:45)
```

but instead, Meteor shows something like

```
W20160517-22:34:04.667(-7)? (STDERR)     at Package (packages/foo_bar.js:567:89)
```

The second form is referring to the built file.
Would be super nice to see the errors relative to the original source files!

**Comment by abernix** [comment]
@trusktr I'm wondering if combining this with #6715 is fair and if this isn't more of an "in-general" source-mapping feature that needs attention.

**Comment by abernix** [comment]
@ffxsam & @trusktr you both opened issues this morning that are basically asking for better source mapping.   Could you both provide git repos (that can be tested against when this feature is worked on) that demonstrate the problem and expected result?

They don't have to be complicated, but these features are much more likely to be picked up by both the core-team and the community-at-large when there is something very easy to work against!

**Comment by ffxsam** [comment]
The problem is, it's sporadic. Sometimes I get source maps and errors with file/line numbers that make sense. Other times, I get no source maps, and I can't really pinpoint/reproduce it.

**Comment by trusktr** [comment]
As @ffxsam mentioned, I think recall seeing both the correct and incorrect files/line numbers. I'll report back if I have a reproduction in my public projects (so far happened on a private project), in which case I can simplify the code too probably.

**Comment by ffxsam** [comment]
It's cropping up again (Meteor 1.3.2.4).. driving me crazy! :) I'll do whatever I can to help pinpoint & troubleshoot this. Just let me know how I can help.

![title_here_](https://cloud.githubusercontent.com/assets/12532733/15560566/ab1658b2-22a1-11e6-9cd5-ad3b42040d81.png)

![title_here_](https://cloud.githubusercontent.com/assets/12532733/15560575/bbfda112-22a1-11e6-9e48-e9ab4510cfcf.png)

**Comment by ffxsam** [comment]
@abernix oh, to answer your Q: unfortunately I can't provide this particular repo, it's a closed source project.

**Comment by ffxsam** [comment]
Hey, here's a thought: if I run meteor in debug mode (if I recall correctly, `DEBUG=* meteor`), will it dump out anything useful?

**Comment by abernix** [comment]
@ffxsam It's unlikely it will provide you with what you want – more than anything it will provide with you a bunch of noise (`DEBUG=*` will enable all node core module debugging, not Meteor.  You're probably thinking of `METEOR_LOG=debug`, which still won't help in this case).

The most helpful would be to see if you get this on a fresh project.  As I said in your #6708 (and as another user just posted a few days ago there) some third-party packages are causing this to happen (most recently `pbastowski:angular-babel).  Assuming that a fresh project works for you, the best bet would be to systematically remove packages you are using until source maps are working again.

**Comment by ffxsam** [comment]
Gotcha. Most of the time, fresh projects behave perfectly :) But I'll let you know!

**Comment by ffxsam** [comment]
Now these little gems are showing up:

![reelcrafter](https://cloud.githubusercontent.com/assets/12532733/15592915/6da3bb44-235c-11e6-8459-4507b3e5472f.png)

Can't repro in a fresh project. I'll have to duplicate my project and start tearing things out until I figure out what's causing this.

**Comment by lyquocnam** [comment]
this happen on `meteor 1.3.3` official too.

![image](https://cloud.githubusercontent.com/assets/8347826/15982244/f8f77b48-2fac-11e6-8a44-3de4a92cea64.png)

**Comment by trusktr** [comment]
@lyquocnam You should post that as a new separate issue so it can be tracked.

**Comment by lyquocnam** [comment]
this is my project: https://github.com/lyquocnam/meteor-1.3-test

**Comment by abernix** [comment]
I believe this is resolved.  Please ping me to reopen if this is not the case (though do update your Meteor to the latest version first)
