### ISSUE TITLE
[1.3.2.4] Meteor builds no APK's

### ISSUE THREAD

**Issue by raix** [meteor/meteor#7079]
When running
```bash
$ meteor build ~/dev/builds/foo --architecture os.linux.x86_64 --server=https://foo.bar
```

The app builds etc. but theres no "builds" folder in the android project. I have to copy this from `.meteor/local/cordova-build/platforms/android`

Note that we are using croswalk

It feels like [this code](https://github.com/meteor/meteor/blob/4225f3c8ec01758cb01ce4d5aa17ef48e8292b96/tools/cli/commands.js#L974) is being run to early?

*([This code](https://github.com/meteor/meteor/blob/4225f3c8ec01758cb01ce4d5aa17ef48e8292b96/tools/cli/commands.js#L990) should copy all related `*.apk` files eg. to support croswalk - might be good to update?)*

**Comment by abernix** [comment]
Can you check if #6756 sounds similar to your problem?  Also, is your problem reproducible on the `localmarket` example application?

**Comment by raix** [comment]
@abernix I'm not sure about #6756 - it's unclear what `but...` implies *(if the previous apk's are copied or none)*

I'll see if I can replicate - for now I just copy manually

**Comment by abernix** [comment]
Without a reproduction repo or explicit instructions on reproducing, I'm closing this.

**Comment by crazybaud** [comment]
Same for us, here a quite similar issue with reproduction : https://github.com/meteor/meteor/issues/7291
