### ISSUE TITLE
Fix/remove flaky tests

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7087]
## Failing Unit tests
 - [x] `tinytest - mongo-livedata - oplog - drop collection/db`
 - [x] accounts reconnection test? (this one is yet to fail on CI but a few people have reported it)

## Speeding up self test

 - [x] Don't run unit tests on circleCI
 - [x] Mark `wipe-all-packages` test slow
 - [x] Create a `warehouse` category
 - [x] Rebalance tests so `warehouse` tests run on one or two containers (to avoid once-off warehouse costs) and remaining tests are spread equally.

## Failing Self tests
 - [x] `selftest.js:646` - up the timeout from 20 -> 120
 - [x] autoupdate test (<- I'm not sure this is fair any more)
 - [x] `static-html: static-html - add static content to head and body` (Bumped timeout)
```
  ... fail!
                                              
                                             /
                                              
  => mongo-not-running at ../../../tools/tests/static-html.js:17
```

  Looks like due to this loop timing out: https://github.com/meteor/meteor/blob/relax-release-constraints/tools/tool-testing/selftest.js#L1456-L1457

 - [x] `run and SIGKILL parent process` (Bumped timeout)

   ```
  ... fail!
  => match-timeout at ../../../tools/tests/run.js:389
  => Pattern: must be a valid process ID
  => Last 100 lines:
  1| [[[[[ /tmp/mt-1c0r2wm/home/myapp ]]]]]
  1| 
  1| => Started proxy.
```

 - [x] `hot-code-push: css hot code push` : https://circleci.com/gh/meteor/meteor/1619 (container 2)

- Looks like a match ordering problem again -- lines 87 + 87 appeared out of order

**Comment by abernix** [comment]
Very nice, @tmeasday.  Most impressive test improvements.   I can haz close this original issue?  Ok! 😜
