### ISSUE TITLE
meteor list is taking forever

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7090]
Sometimes, `meteor list` inside my [Dockerfile takes forever](https://github.com/tozd/docker-meteor/blob/master/Dockerfile#L18). It seems like it is in a loop.

See attached log for an example. This has been going for more than 12 hours now (for this particular build).

[Terminal Saved Output.txt.gz](https://github.com/meteor/meteor/files/275502/Terminal.Saved.Output.txt.gz)

**Comment by abernix** [comment]
Can you attach `gdb` to it and see where it's stuck?  If it's only in a `Dockerfile` maybe you reproduce in some other TTY-less situation?  screen/ssh or something? 💭 

My computer had a lot of fun with that 1.2Gb text file.

**Comment by mitar** [comment]
It is not stuck. It is working all the time, but it is not progressing.

I was also thinking that it might be TTY thingy. Maybe `meteor list | cat` should be a good way to test it.

**Comment by abernix** [comment]
My only other thought would be that it's stuck on the sqlitedb (locked?) for some reason.

**Comment by mitar** [comment]
OK, if it was not clear. The output is going and going. The log I send is not the end of the output. But it continue for hours in the same way. Working, 100% CPU, but not really progressing.

**Comment by abernix** [comment]
Yeah I got that from the log. My computer was at 200% cpu just opening it.  Haha.

**Comment by mitar** [comment]
Crazy thing is that on Docker Hub it works and image with the same Dockerfile compiles well. Only when trying to compile the image locally.

And this is something new. It has not been a problem in the past.

**Comment by mitar** [comment]
Interesting. It seems to get stuck trying to download core packages. From Docker Hub where it works, I have for example such lines in my log (indentation not preserved):

```
 Task [Downloading 120 packages child] 3719829/?
   Task [Downloading babel-compiler@5.8.24_1...] 3719829/?
 Task [Downloading 120 packages child] 223294/?
   Task [Downloading blaze@2.1.3...] 223294/?
 Task [Downloading 120 packages child] 4483553/?
   Task [Downloading coffeescript@1.0.11...] 4483553/?
 Task [Downloading 120 packages child] 9627494/?
   Task [Downloading cosmos:browserify@0.9.3...] 9627494/?
 Task [Downloading 120 packages child] 333998/?
   Task [Downloading ddp-client@1.2.1...] 333998/?
 Task [Downloading 120 packages child] 111257/?
   Task [Downloading ddp-server@1.2.2...] 111257/?
```

While on failing build:

```
            Task [Downloading 120 packages child] 0/?
              Task [Downloading blaze@2.1.3...] 0/?
                Task [Downloading blaze@2.1.3...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading blaze-tools@1.0.4...] 0/?
                Task [Downloading blaze-tools@1.0.4...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading caching-compiler@1.0.0...] 0/?
                Task [Downloading caching-compiler@1.0.0...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading callback-hook@1.0.4...] 0/?
                Task [Downloading callback-hook@1.0.4...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading coffeescript@1.0.11...] 0/?
                Task [Downloading coffeescript@1.0.11...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading ddp-client@1.2.1...] 0/?
                Task [Downloading ddp-client@1.2.1...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading ddp-rate-limiter@1.0.0...] 0/?
                Task [Downloading ddp-rate-limiter@1.0.0...] 0/?
            Task [Downloading 120 packages child] 0/?
              Task [Downloading deps@1.0.9...] 0/?
                Task [Downloading deps@1.0.9...] 0/?
```

Why have those packages number `0` there? What does it mean at all?

**Comment by mitar** [comment]
I think that maybe the issues are with a CDN. And that when there are issues with a CDN, Meteor does not throw any error and just waits. See #6960 and #6944.

**Comment by mitar** [comment]
I think this is a duplicate of the CDN. With latest automatic retries it seems this improved. Closing.
