### ISSUE TITLE
`babel-preset-meteor@6.8.1` breaks new `dev_bundle`s

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7092]
When I built a new `dev_bundle` on the `mongo-3.2-new-binary` branch, it installed `babel-preset-meteor@6.8.1`. This lead to the [following error](https://travis-ci.org/meteor/meteor/builds/131830015) on `meteor` startup:

```
/home/travis/build/meteor/meteor/tools/tool-env/source-map-retriever-stack.js:1
(function (exports, require, module, __filename, __dirname) { import sourceMap
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.require.extensions..js (/home/travis/build/meteor/meteor/dev_bundle/lib/node_modules/meteor-babel/register.js:35:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/meteor/meteor/tools/tool-env/install-babel.js:49:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Manually changing the version in the bundle back to `babel-preset-meteor@6.6.8` (as in the current `devel` `dev_bundle`) solved the problem.

I'm not sure what to do next as this comes from a sub-dependency in both cases from `meteor-babel@0.9.2` and npm doesn't give me any way to control its deps ( ;) ).

**Comment by benjamn** [comment]
I think you need to rebase the `mongo-3.2-new-binary` branch against `release-1.3.3`. The line numbers in this stack trace refer to code that has changed in `release-1.3.3`, with [this commit](https://github.com/meteor/meteor/commit/6aec3603c872f93b88532d7d571e0426d8461339) among others.

That said, I'm not sure how you were able to get `babel-preset-meteor@6.8.1` when your dev bundle was using [`meteor-babel@0.9.2`](https://github.com/meteor/meteor/blob/4cdbe6a9e2589a83b0cdaee810f8e9c450087317/scripts/dev-bundle-tool-package.js#L27).

Actually, I misunderstood the `^6.6.7` version syntax [here](https://github.com/meteor/babel/blob/cd970ff232896a3e03981df2a9033fb760784f7a/package.json#L33). Unbelievably, that matches `6.8.1`, so you get `babel-preset-meteor@6.8.1` when you install `meteor-babel@0.9.2`. Gross.

I'll republish another 0.9.x version of `meteor-babel` with no `^` versions.

**Comment by benjamn** [comment]
Ok you should be able to use `meteor-babel@0.9.4` in the dev bundle to fix this.

**Comment by tmeasday** [comment]
> Actually, I misunderstood the ^6.6.7 version syntax here. Unbelievably, that matches 6.8.1, so you get babel-preset-meteor@6.8.1 when you install meteor-babel@0.9.2. Gross.

I think that works the same as `@6.6.7` does in Meteor. The theory is, only major releases should have breaking changes. You can specify `6.6.*` if you want "only take patches".

[It works differently for `^0.a.b` (and differently again for `^0.0.a`, which is I think a frequent source of confusion about all this].

**Comment by tmeasday** [comment]
(Meteor's constraint solver prefers to take patches and minimize minor version changes, which can lead to perceived different behavior also. npm is very aggressive OTOH).

**Comment by tmeasday** [comment]
Thanks @benjamn
