### ISSUE TITLE
[1.3.3-beta.0] .babelrc with babel-preset-es2015 fails

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7096]
i tried add .babelrc file:
{
```
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    ["transform-runtime", {
     "polyfill": true,
     "regenerator": true
   }],
    "jsx-control-statements"
  ]
}
```
and install dependencies packages:
```
{
  "name": "test",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0"
  },
  "devDependencies": {
    "babel-plugin-transform-regenerator": "^6.9.0",
    "babel-polyfill": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "babel-preset-stage-3": "^6.5.0",
    "babel-runtime": "^6.9.0",
    "jsx-control-statements": "^3.1.2"
  }
}

```

this error:

```
 While processing files with ecmascript (for target web.browser):
   module.js:338:15: Cannot find module 'babel-preset-es2015'
   at Function.Module._resolveFilename (module.js:338:15)
   at InputFile.resolve (C:\tools\isobuild\compiler-plugin.js:347:14)
   at InputFile.<anonymous> (C:\tools\isobuild\compiler-plugin.js:351:25)
   at InputFile.require
   (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.3-beta.0\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:353:23)
   at req (packages/babel-compiler/babel-compiler.js:209:1)
   at packages/babel-compiler/babel-compiler.js:214:1
   at Array.forEach (native)
   at infer (packages/babel-compiler/babel-compiler.js:212:1)
   at BabelCompiler.BCp._inferHelper (packages/babel-compiler/babel-compiler.js:231:1)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler/babel-compiler.js:163:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:150:1)
   at packages/babel-compiler/babel-compiler.js:92:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:40:1)

```

**Comment by abernix** [comment]
Did you run `meteor npm install` after you set those as your `devDependencies`?

**Comment by lyquocnam** [comment]
yes i did @abernix , but still error

**Comment by abernix** [comment]
Ok, while I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by lyquocnam** [comment]
this my test project, i hope this help !
https://github.com/lyquocnam/meteor-1.3-test

**Comment by abernix** [comment]
Thank you for that!

Ok, so I was NOT able to reproduce your problem or your exact error, but I was actually able to get your project working just fine by simply:
* Running `meteor npm install`
* Running `meteor npm install --save-dev babel-plugin-transform-runtime` (you did not have that plugin in your `package.json`.
* Removing `jsx-control-statements` from the `.babelrc` (Sorry, I missed it in your original post – only `plugins` and `presets` are supported at this time as stated in https://github.com/meteor/meteor/pull/7033/commits/7c63a8e704e73405eaa32042c997da957891e8b2 – one thing at a time :smile:)

**Comment by lyquocnam** [comment]
thanks mr @abernix i hope` jsx-control-statements ` will be supported soon, it realy need with react project :)

**Comment by abernix** [comment]
No problem.  Glad it works!  It's still a work in progress so additional support will come over time. :smile:
