### ISSUE TITLE
Browsers won't autorefresh when user logged in. 

### ISSUE THREAD

**Issue by polkhovsky** [meteor/meteor#7097]
Meteor 1.3.2.4
First Chrome, then Safari stopped auto-refreshing when I update client files. Meteor registers the change and says `=> Client modified -- refreshing` in the console but the browsers don't react. I loaded my site in an incognito window and it would auto-refresh just fine until I log into the site. Same behavior in standard browser windows -- site auto-refreshes when I'm not logged in. As soon as I log in auto-refresh stops working. 

I also posted in [StackOverflow](http://stackoverflow.com/questions/37352536/meteor-stopped-auto-refreshing-the-browser).

**Comment by abernix** [comment]
Could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction repository, it's very difficult to get to investigate.

**Comment by polkhovsky** [comment]
I'm going to close this. I still don't know why it's not working but I was trying to include some outside scripts by inserting script tags in the main html file and autorefresh started working. It stopped again after I removed the new tags. So must me something with my code then. Sorry to bother.
