### ISSUE TITLE
[1.3.3-beta.0] .babelrc plugins fails

### ISSUE THREAD

**Issue by rickmed** [meteor/meteor#7098]
error:
```
While processing files with ecmascript (for target web.browser):
   module.js:338:15: Cannot find module 'babel-plugin-babel-plugin-react-html-attrs'
```

.babelrc
```
{
  "plugins": [
    "babel-plugin-react-html-attrs"
  ]
}
```

package.json
```
{
...
  "devDependencies": {
    "babel-plugin-react-html-attrs": "^2.0.0"
  }
}
```

I tried with "babel-plugin-react-html-attrs" and "react-html-attrs" on babelrc
Also, tried running meteor npm install, meteor npm install --save-dev  "babel-plugin-react-html-attrs" 
I see the package installed in my node_modules

I'm on windows 10.

**Comment by benjamn** [comment]
There is probably still a bug here, but just to clarify, your `.babelrc` file should definitely say
```js
{
  "plugins": [
    "react-html-attrs"
  ]
}
```
rather than `babel-plugin-react-html-attrs`.

**Comment by myknbani** [comment]
I don't know if this is related, but it also fails when I use the "transform-decorators-legacy" plugin.

#### .babelrc
```js
{
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

I have `"babel-plugin-transform-decorators-legacy": "^1.3.4"` in my package.json

Here's the stacktrace.
[bug.txt](https://github.com/meteor/meteor/files/276717/bug.txt)

**Comment by jamiter** [comment]
To get mine to work I used the `package.json` and had to add a relative url to get it working:

```json
{  
  "babel": {
    "plugins": [
      "./node_modules/babel-plugin-transform-class-properties"
    ]
  }
}
```
If I use just use `transform-class-properties`, it says it can't find the `babel-plugin-transform-class-properties` module.

Or is this another issue?

**Comment by benjamn** [comment]
Does this still happen after `meteor update --release 1.3.3-beta.1`?

**Comment by jamiter** [comment]
It now works for me with a `.babelrc`. I no longer need to define the relative path. Thanks!

**Comment by benjamn** [comment]
Glad to hear it. Please reopen if the problem still occurs.
