### ISSUE TITLE
Meteor API-doc as single page

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#7099]
***1 Upvote*** I need Meteor API-doc as single page for search any entry. It is very strange, but [new design](http://docs.meteor.com/) made me lose this functionality!

**Comment by devonbarrett** [comment]
:+1: if the search functionality is going to be removed from the site, at least having a way to ctrl+f effectively is needed.

**Comment by abernix** [comment]
Thanks for reporting this, however there is a separate repository for docs.  These issues are already open, so please +1 them over there!  meteor/docs#8 (single page) and meteor/docs#5 (search).  Closing.
