### ISSUE TITLE
error installing meteor via curl on osx

### ISSUE THREAD

**Issue by chappydboz** [meteor/meteor#7106]
installing meteor from the console in osx yosemite using curl
`curl https://install.meteor.com/ | sh`
  
i get this response: 

```
dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_next_proto_select_cb
  Referenced from: /opt/local/lib/libcurl.4.dylib
  Expected in: /opt/local/lib/libssl.1.0.0.dylib

dyld: Symbol not found: _SSL_CTX_set_next_proto_select_cb
  Referenced from: /opt/local/lib/libcurl.4.dylib
  Expected in: /opt/local/lib/libssl.1.0.0.dylib
```

**Comment by laosb** [comment]
Would you like to try `curl`ing other urls? It looks like a curl problem.

**Comment by abernix** [comment]
This is definitely a problem with your machine and will probably happen with some if not all SSL hosts (not just Meteor).  It appears you're using MacPorts and it appears that your OpenSSL isn't linking properly, so I would probably recommend `sudo port upgrade openssl`.  Maybe `sudo port upgrade curl` too.

Closing as unrelated to Meteor, but please feel free to request that it get reopened if you identify that it's specifically a problem with Meteor.

**Comment by chappydboz** [comment]
yeah.. the macports upgrades worked.. 
thx
