### ISSUE TITLE
Support for --production in 'meteor test'

### ISSUE THREAD

**Issue by ramijarrar** [meteor/meteor#7107]
Limiting test runs to development mode can mask errors specific to production builds. Adding support for this flag will improve the reliability of test results (particularly with the acceptance test driver).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20for%20--production%20in%20'meteor%20test'&body=Migrated%20from:%20meteor/meteor%237107) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
