### ISSUE TITLE
[1.3.2.4] Error: `D:\projekty\chimp_test\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node` is missing. Try reinstalling `node-fibers`?

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#7109]
Hey,

seems that when you have fibers in your node_modules, meteor tries to use it instead of the bundled version. As far as I could test this happens only on windows (tested on 7,8,10 all of them 64bit).

```
Error: 'D:\projekty\chimp_test\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node' is missing. Try reinstalling 'node-fibers'?

at Object.<anonymous> (D:\projekty\chimp\node_modules\fibers\fibers.js:16:8)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (D:\projekty\chimp_test\.meteor\local\build\programs\server\boot.js:1:75)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
```

Repro:
```
meteor create test
cd test
npm install fibers --save
meteor
```

It also happens when you install `chimp` as it has `fibers` in its deps.

There is also a similar problem with cordova, when you add `npm install shelljs --save-dev` consecutive building of cordova apps will fail, as it apparently also uses the version from local node_modules if present. I had to downgrade to `0.5.3` in `packages.json` to make it work.
Pity that I've found this https://github.com/meteor/todos/issues/107#issuecomment-212905737 after whole day of digging.

**Comment by laosb** [comment]
Will try to reproduce this weekend.

**Comment by benjamn** [comment]
This will work if you use the same version of Node/V8 that Meteor uses. The easiest way to do that is to run
```sh
meteor npm install fibers --save
```
instead of
```sh
npm install fibers --save
```
To see what versions of Node-related dependencies are in use, try running
```sh
meteor npm version
```
and compare the output to that of
```sh
npm version
```

**Comment by laosb** [comment]
Did reproduce. According to @benjamn , this is a problem of different node versions. So we should add a tip to docs/guides suggesting use `meteor npm` instead in a Meteor app!

**Comment by wojtkowiak** [comment]
Sorry for late answer. @benjamn using `meteor npm install` indeed solves these problems, thanks :smile:
However for me when most of the team is working on Windows this is more like a workaround since only `npm3` (since it doesn't nest the deps) allows us to develop without growing hundreds of megabytes in node_modules and prevents us from running into problems with `path too long`.
Since it is our choice to work on Windows I won't bother you more and close this :wink:
I guess we will have to wait for Node 5 support.
When it comes to packages from node_modules leaking and being used by cordova it is really disturbing and guess it would be nice to warn somewhere in the docs about it (I am not sure if @martijnwalraven can do anything with it).

**Comment by abernix** [comment]
@wojtkowiak Will try to make this more clear in the docs.  Thanks for the update.

**Comment by stephen-mi11er** [comment]
I'm having the same or similar issue when trying to run acceptance testing on my product using chimp. 

When I run `meteor npm run chimp-watch` on my Windows 10 machine I get the following error:

```
## There is an issue with `node-fibers` ##
`C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers\bin\win32-x64-57\fibers.node` is missing.

Try running this to fix the issue: C:\Users\Steve\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin\node.exe C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers/build
C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers\fibers.js:20
        throw new Error('Missing binary. See message above.');
        ^
Error: Missing binary. See message above.
    at Object.<anonymous> (C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\node_modules\fibers\fibers.js:20:8)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Steve\AppData\Roaming\npm\node_modules\chimp\dist\lib\utils\fiberize.js:14:15)
```

I tried running the suggested fix from the error but I end up going down a rabbit hole of trying to compile fibers on my machine.

I tried everything from `meteor reset` to eventually removing and reinstalling node, npm and meteor to no avail.

I also tried the command suggested by @benjamn above.

**Comment by stephen-mi11er** [comment]
@abernix should I reopen a new issue?

**Comment by stephen-mi11er** [comment]
I actually just fixed this by re-running `meteor npm install chimp`
