### ISSUE TITLE
[1.3.3-beta.0] `export { default } ...` wrapped (Regression)

### ISSUE THREAD

**Issue by AnthonyAstige** [meteor/meteor#7111]
I think there's a regression in handling syntax like `export { default } from '/imports/foo/foo.js'`

I've reproduced in my codebase, and summarized as follows (though the code below is untested)

## Files

/server/main.js

```
import foo from /imports/foo/';
console.log(foo)
```

/imports/foo/index.js
```
export { default } from './foo.js';
```

/imports/foo/foo.js
```
function foo() { }
export default foo;
```

## Output

1.3.2.4 (Correct)

> { [Function: foo] }

1.3.3-beta.0 (Incorrect)

> { default: [Function: foo] }

## Workaround

**/server/main.js**

```
import foo from /imports/foo/foo.js';
console.log(foo)
```

1.3.2.4 & 1.3.3-beta.0 (Correct)

> { [Function: foo] }

## References

https://esdiscuss.org/topic/re-export-default (See Caridy's first comment)

**Comment by abernix** [comment]
You'll have to make a reproduction repo because I got the "correct" response on `1.3.3-beta.0` based on what you wrote :
```
[Function: foo]
```
(Yes, I added the missing quote in `/server/main.js`)

**Comment by abernix** [comment]
@AnthonyAstige Any updates on this?

**Comment by AnthonyAstige** [comment]
@abernix Sorry for the delay, just got the time today to throw this together quickly.

**Reproduction repo**
https://github.com/AnthonyAstige/meteor-export-default-regression

**Reproduction screenshots**
Confirmation from 1.3.2.4 to `meteor update --release 1.3.3-beta.1`

![screenshot from 2016-05-28 17-44-23](https://cloud.githubusercontent.com/assets/236039/15630339/7f2a8392-24fc-11e6-85ca-601ce1411f76.png)

`meteor update --release 1.3.3-beta.1` is the same

![screenshot from 2016-05-28 17-52-49](https://cloud.githubusercontent.com/assets/236039/15630346/018f1ec4-24fd-11e6-8150-d46297e64aa6.png)

**Comment by abernix** [comment]
Thanks for the repo.  When I tested this, I threw your code into an existing project that (I didn't notice) had a `.babelrc` with the `es2015` preset.  Apparently, it works fine with that preset in place!  As soon as I removed that preset from the `.babelrc`, I see the same behaviour in my repo as yours.

(#7033)

**Comment by abernix** [comment]
#7159 had this same issue. 

Workaround for this for now is to just import as:

    export default from './foo';

**Comment by abernix** [comment]
*export

Can't edit on phone.

**Comment by abernix** [comment]
@benjamn – wasn't sure how to interpret from the spec how this should work versus what babel-was-doing/reify-is-doing.  This is the only reify difference I've seen so far.
