### ISSUE TITLE
How to get userId in the Mongo.Cursor#observeChanges

### ISSUE THREAD

**Issue by amou1012** [meteor/meteor#7113]
I wrote Mongo.Cursor#observeChanges at the **server side**, and I want to get the current userId in the changed(id, fields) function by using **this.userId** , but I always get undefined.... please help me~~

 Collection.find().observeChanges({
  added: function (id, fields) {
   .....
  },
  changed : function(id, fields) {
    console.log(this.userId); //undefined
  }
});

**Comment by laosb** [comment]
You may try `Meteor.userId()`.

PS: Discussions like this should be posted to [forums](https://forums.meteor.com), closing.
