### ISSUE TITLE
docs.meteor.com should not forbid rescaling viewport

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#7121]
> &lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, **user-scalable=no"**&gt;

Please, please, please: do not turn off user-scalable.

Not all of us have eyes that can read tiny fonts.

**Comment by abernix** [comment]
Issue moved to [meteor/docs #34](https://github.com/meteor/docs/issues/34) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by abernix** [comment]
Closing because moved.  Please use [the Meteor Docs repo](http://github.com/meteor/docs/) for future docs issues as they as now kept separately (and also user contributions are greatly appreciated via PR!)

**Comment by awwx** [comment]
Thank you @abernix !
