### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE when using proxy

### ISSUE THREAD

**Issue by liuxihua** [meteor/meteor#7122]
i use the meteor behind the proxy, and I already set the proxy as "https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy" said.

I use meteor in windows 7. 

when i input "meteor update" command, it update quite good:

```
`C:\Studio\microscope>meteor update
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

This project is already at Meteor 1.3.2.4, the latest release.
Your top-level dependencies are at their latest compatible versions.
```
`

when i input the "meteor add twbs:bootstrap" command, I got a error like below:
```
`C:\Studio\microscope>meteor add twbs:bootstrap
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

 => Errors while adding packages:

While downloading twbs:bootstrap@3.3.6...:
**error: UNABLE_TO_VERIFY_LEAF_SIGNATURE**

Your package catalog may be out of date.
Please connect to the internet and try again.`
```

when i worked in npm, i set the proxy and set the "strict-ssl = false" in the npm config. it works fine.

so could you pls tell me where to set the "strict-ssl = false" or what should i do , thanks

**Comment by abernix** [comment]
This is would appear to be  happening due to incorrect intermediary certificate authority certs being in place.  Perhaps the proxy itself or your machine hasn't received recent updates?

Please try running this before your command (on Windows) to see if it resolves it for you:

    SET NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by liuxihua** [comment]
great , it works , thanks
