### ISSUE TITLE
Unable to set cordova preference KeyboardDisplayRequiresUserAction

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#7126]
According to the [Cordova documentation](https://cordova.apache.org/docs/en/latest/config_ref/index.html), and lots of posts around the web, the most standard way to programmatically open iOS's keyboard on web-based projects is two-fold:
1. Set the `KeyboardDisplayRequiresUserAction` preference to `false`:
   
   mobile-config.js:
   
   ```
   App.setPreference('KeyboardDisplayRequiresUserAction', false, 'ios');
   ```
2. Then call `.focus()` in your event handler:
   
   event handler:
   
   ```
   $('input').focus();
   ```

However, settings the preference in step 1 does not seem to apply for me. When I rebuild the app (delete `.meteor/local`, rebuild, execute app code that calls `.focus()`, the iOS keyboard still does not launch within the iOS Cordova app.

When I do a search for `KeyboardDisplayRequiresUserAction` within `.meteor/local`, I see some interesting things:

![screen shot 2016-05-26 at 8 25 15 pm](https://cloud.githubusercontent.com/assets/4974609/15594058/06211b96-2380-11e6-9b1e-a1d3407d26fd.png)

In `.meteor/local/cordova-build/platforms/ios/AppName/config.xml`, the property gets set twice. First as `true`, then as `false`. True appears to be the default, but rather than replacing it, Cordova tries to override it through code load order, which I'm not sure actually works.

In `.meteor/local/cordova-build/platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewEngine.m`, iOS tries to choose the proper setting, but my guess is it can't find the preference I set, so it defaults to `true`.

**Comment by laosb** [comment]
Doesn't know what happening there and I can only label this. Any one any ideas?

**Comment by mrlowe** [comment]
@joncursi are you sure you're using UIWebView for rendering? Meteor 1.3 uses WkWebView by default, which doesn't support anything like keyboardDisplayRequiresUserAction. You might double-check to see if your xcode console output doesn't say something like: ```Using WKWebView```.

I encountered a similar problem trying to get inputs to focus. Now to try to hack WkWebView ... =P

**Comment by mrlowe** [comment]
No luck, so I told Meteor 1.3 to go back to using the old UIWebView:
```
App.setPreference('CordovaWebViewEngine', 'CDVUIWebViewEngine');
```
And as expected, KeyboardDisplayRequiresUserAction works. Should this issue be closed?

**Comment by joncursi** [comment]
Oh interesting, I did not know this was a limitation of the new WKWebView. I'll look more closely at WKWebView and see if I can find any workarounds. Thanks for your feedback!

**Comment by joncursi** [comment]
Looks like there is an issue filed on the Cordova issue tracker for this:

https://issues.apache.org/jira/plugins/servlet/mobile#issue/CB-10376

**Comment by macrozone** [comment]
I observed the same with WKwebview which prevents autoplay (for example).

See https://github.com/meteor/meteor/issues/7173

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/7126#issuecomment-223841332, an [issue](https://issues.apache.org/jira/browse/CB-10376) for this has been filed with Cordova. There isn't much that can be done here until that issue is resolved, so for now the workaround is to use the `UIWebView` (as outlined in https://github.com/meteor/meteor/issues/7126#issuecomment-223756100). After Cordova fixes this problem it will be included in a future Meteor release (since the Cordova libs are updated fairly regularly), so I'll close this issue for now. Thanks for reporting this originally!

**Comment by steodor** [comment]
I had the same issue in a Cordova app and i found this plugin https://www.npmjs.com/package/cordova-plugin-wkwebview-inputfocusfix , it works like a charm. Maybe it can serve as inspiration for a Meteor fix so you can use WKWebView. Good luck!
