### ISSUE TITLE
`meteor login` is broken under mintty (Windows 10)

### ISSUE THREAD

**Issue by pcarrier** [meteor/meteor#7130]
```
$ meteor.bat login

C:\ProgramData\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: EINVAL, invalid argument
    at new Socket (net.js:157:18)
    at process.stdin (node.js:703:19)
    at Console.readLine (C:\tools\console\console.js:1289:12)
    at Object.<anonymous> (C:\tools\meteor-services\auth.js:572:39)
    at Object.loginCommand (C:\tools\meteor-services\auth.js:36:22)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands.js:1822:15)
    at C:\tools\cli\main.js:1402:23
```

**Comment by pcarrier** [comment]
Workaround:

```
$ winpty meteor.bat login
```

**Comment by hwillson** [comment]
This hasn't been a popular issue, and there is a workaround (https://github.com/meteor/meteor/issues/7130#issuecomment-222267468). As part of the on-going old issue cleanup process, I'll close this off. Thanks!

**Comment by pcarrier** [comment]
I am still affected.

**Comment by hwillson** [comment]
Thanks @pcarrier - sorry for closing prematurely. We're trying to be a little more aggressive about closing out some of the older issues, that haven't been upvoted by many developers. This issue fell into that category. I agree, the workaround isn't great. I'm happy to leave this open longer (and would be even happier if anyone reading this is interested in digging into this a bit, and potentially submitting a PR).

**Comment by abernix** [comment]
Possibly related: https://github.com/keybase/keybase-issues/issues/723?

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Comment by hwillson** [comment]
Just to add @pcarrier - we've made [recent policy changes with regards to Meteor bugs](https://github.com/meteor/meteor/blob/devel/ISSUE_TRIAGE.md#bug-issue-lifespan). If anyone steps forward to work on this, great! We'll re-open it as needed.
