### ISSUE TITLE
[bug] Once in a while a file handle collides.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7133]
I'm on Meteor 1.3.2.4. Every once in a while I get an error like this:

```
=> Client modified -- refreshing (x69)The handle(652) returned by watching /Users/trusktr/src/MightyDevs+website/meteor-app/node_modules/react/lib/ReactDOMTextComponent.js is the same with an already watched path(/Users/trusktr/src/MightyDevs+website/meteor-app/client/app/App.js)
=> Client modified -- refreshing (x84)^C
```

Unfortunately I have no way to reproduce it, it's seemingly random, and I've no idea how to trigger it.

**Comment by abernix** [comment]
This is the same as another issue you already have open, #5923.  As stated in that issue, it's likely due to not resolving symlinks before watching them and will hopefully be fixed in a future release.  The warning message can be safely ignored.

Closing as duplicate.

**Comment by trusktr** [comment]
My goodness, I'm on a duplicate spree. Sorry about that. Searching my own issues next time.
