### ISSUE TITLE
Source maps with node_modules?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7134]
Some libraries on NPM have source maps, because the library may have been transpiled on `prepublish`. Is there a (perhaps planned) way to take advantage of these in Meteor?

For example, package A's `main` file might be `dist/index.js`, and the corresponding source map might be `dist/index.js.map`.

Does Meteor look at those? If not, maybe there can be a simple convention: for each `path/to/file.js` have Meteor simply look for `path/to/file.js.map`.

**Comment by abernix** [comment]
This is also another duplicate of an issue you already have open, #6715 (and not all that different than #7076 either).  Please understand that these issues will all get addressed much quicker if they are consolidated and organized.  Please search existing issues before opening new ones.
