### ISSUE TITLE
Can't use index.jsx as the default entry point when importing a directory

### ISSUE THREAD

**Issue by ModrichBadr** [meteor/meteor#7138]
I have components which export their sub-components via Index.jsx

What works: 

`import Conversations  from './conversations/index.jsx'`

What does not work: 

`import Conversations  from './conversations'`

Seems to be an issue with JSX extension, any thoughts on how to configure for JSX extension ? So I'm able to import using `./conversations`

**Comment by laosb** [comment]
Not sure if it's a bug or feature. But should be able to automatically use `index.jsx`, or even `index.ts` `index.tsx` in the future.

**Comment by hwillson** [comment]
Using the `.jsx` extension has fallen out of favour these days (when in doubt, refer to [Create React App](https://github.com/facebookincubator/create-react-app)). If you rename your `index.jsx` to `index.js`, then 

```js
import Conversations from './conversations'
```

will work. Given this, I think we're okay to close this issue. Happy to re-open if anyone disagrees. Thanks!

**Comment by gaurav-** [comment]
@hwillson, I disagree :) 

We use the `.jsx` extension if the file contains, well, `jsx` syntax. I'd imagine there would be many who'd prefer the same. So it would be good to keep this option open. 

We're currently building the frontend with Webpack 1, and plan to migrate the build to Meteor 1.5 when it's released. But this would be an annoying step for us to rename our `index.jsx` files 😨 

Moreover, even the [Airbnb JSX Style Guide recommends](https://github.com/airbnb/javascript/tree/master/react#naming) using `index.jsx` for root components of the directory. This style guide is very popular and even [recommended by the official Meteor Guide](https://guide.meteor.com/code-style.html#style-guide).

**Comment by hwillson** [comment]
Ha - disagreements welcome! 🙂 

Airbnb's style guide recommends it, but the fact that it does is [quite controversial](https://github.com/airbnb/javascript/pull/985). Actually, the `react/jsx-filename-extension` is listed as being one of the most disabled/overridden rules in Airbnb's styleguide. The final nail in the `.jsx` extension coffin though seems to be the fact that React Native doesn't support it.

All of that being said, it sounds like there is still some interest in seeing this happen. I'll re-open and mark this as `pull-requests-encouraged`; happy to review a PR for this if anyone is interested in contributing.  Thanks!

**Comment by stubailo** [comment]
Plus, `create-react-app` doesn't use `.jsx` either.

**Comment by gaurav-** [comment]
Ohh i was unaware of all the discussion on this topic; thanks for sharing! 

As I understand and agree now, there's indeed a good rationale for dumping `.jsx` altogether. 

We should perhaps nudge people to gradually transition to `.js` for react components too, like `create-react-app` folks seem to have done: https://github.com/facebookincubator/create-react-app/issues/87#issuecomment-244563409

But as long as `.jsx` is supported, it would be counter intuitive to make an exception of `index.jsx`. This inconsistency is more undesirable than the newly discovered fallacy of using `.jsx`, imo. So I'd still vote for supporting this, even though I wouldn't use `.jsx` in a greenfield project from now on.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Can't%20use%20index.jsx%20as%20the%20default%20entry%20point%20when%20importing%20a%20directory&body=Migrated%20from:%20meteor/meteor%237138) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
