### ISSUE TITLE
Windows 10 meteor-tool@1.1.4 taking not downloading

### ISSUE THREAD

**Issue by mcole1976** [meteor/meteor#7139]
I have recently put 1.3 on a windows 10 pc, and  I am getting stuck at this point for a while

![meteor issue](https://cloud.githubusercontent.com/assets/11861970/15656174/2d64a1a4-266a-11e6-85da-0002705c08ac.JPG)

**Comment by abernix** [comment]
How fast is your Internet connection?  `meteor-tool` is probably a 150MB download.

**Comment by mcole1976** [comment]
thank you

**Comment by mcole1976** [comment]
it downloads it just freezes after the download

**Comment by abernix** [comment]
How do you know it downloads?  What happens if you just run `meteor update` in that directory instead of just `meteor`?

**Comment by mcole1976** [comment]
ty, I just re installed meteor and it is fine with the new Apps.Thanks for the help and advice!
