### ISSUE TITLE
FireFox Developer Tools CSS Source Map Missing

### ISSUE THREAD

**Issue by j2l** [meteor/meteor#7140]
By default (locally run), Meteor now merges all stylesheets and you can't debug anymore.
Should have been fixed but still present, see https://forums.meteor.com/t/how-to-prevent-merging-files-in-1-3-when-running-in-dev/20312 for discussion and announce of being fixed.

**Comment by abernix** [comment]
The _actual_ stylesheet that is served will be merged to make sure that it's replicating the production environment, but the source maps are still in place to map things to their original files.

There are two sections of the **Sources** tab in DevTools.  The first is the compiled code (indicated by `localhost:3000`, or similar) will show the files as-compiled.  The source files are available in the "💻 app" catalog further down the list (see below for screenshots).

For example, I just created a brand new Meteor project and made two separate CSS files with overlapping `body` styles (`main.css` and `main2.css`) and had no problem debugging.  If I inspect my `body` tag, the files that the styles are declared in are clearly noted with proper inheritance shown.

![screen shot 2016-05-31 at 2 36 23 pm](https://cloud.githubusercontent.com/assets/841294/15673084/1348bd04-273d-11e6-86a9-3a25f551b90c.png)

If I click on the filename and line number (`main2.css:2` in my case), it takes me to the source-mapped portion of the **Sources** tab in DevTools (indicated with "💻 app") which shows me the file _exactly_ as it is on my system.

![screen shot 2016-05-31 at 2 37 19 pm](https://cloud.githubusercontent.com/assets/841294/15673118/33028fbc-273d-11e6-8e70-d5d2a66f71f9.png)

Can you clarify further what you're trying to debug or unable to debug?

**Comment by j2l** [comment]
Thanks Abernix for your quick reply and the screenshot of your test.
Like many I guess, I tweak my CSS on the fly. Actually I do it with Firefox and only get the merged stylesheet:
Inspector:
![ff](https://cloud.githubusercontent.com/assets/65325/15675926/84cbe9d6-2744-11e6-8eda-88d1f1b9e6f0.png)
Style Editor shows most of the rules are merged:
![screen shot 2016-05-31 at 3 14 34 pm](https://cloud.githubusercontent.com/assets/65325/15675934/8f0d4728-2744-11e6-9e58-8a54862e79c2.png)

Following your message I tried with Chrome and I have a different behavior with mixed results:
Element tab:
![screen shot 2016-05-31 at 3 11 04 pm](https://cloud.githubusercontent.com/assets/65325/15675941/9460cc7c-2744-11e6-87a6-65a6d95408dc.png)

Network tab:
![screen shot 2016-05-31 at 3 13 27 pm](https://cloud.githubusercontent.com/assets/65325/15675951/9934d108-2744-11e6-998a-211f19b253eb.png)

Hope it helps. I guess problem is with Firefox. Still, having merging as an option for Chrome would help find which css is slow/bloated via the network tab.

**Comment by j2l** [comment]
FF is 45.0.1 on Mac OS 10.11.3

**Comment by abernix** [comment]
Well, it is an option in Chrome – you can view either one you want and you can always enable/disable source-maps.

Your screenshot from Chrome doesn't really show me anything not working.  The `merged-stylesheets.css` will certainly still be served to you by the server.  This is to ensure an identical production/development process – the `X-Sourcemap` header is just not served on your production app.  What happens if you click on `bootstrap.css:1084`?  What file does it take you to?

Not sure what's going on with Firefox, but I see the same issue – FireFox isn't detecting or using the `X-Sourcemap` header that is being sent with the CSS file.   According to a developer who works on FireFox Developer Tools, [support was just recently added in v46](http://jlongster.com/On-the-Road-to-Better-Sourcemaps-in-the-Firefox-Developer-Tools) but isn't fully used?

I'm not certain if using the `/* # sourceMapURL=` in-line file syntax would get it picked up or not.

**Comment by abernix** [comment]
It's working in Safari too – but I tried FireFox Developer Edition with no luck.

![screen shot 2016-05-31 at 5 39 16 pm](https://cloud.githubusercontent.com/assets/841294/15678344/b01169b0-2756-11e6-98e0-5790ec8499a4.png)

**Comment by j2l** [comment]
Thank you very much Abernix.
I was speaking about the network tab in Chrome where only the merged file is visible, so it's harder to tell which local CSS file is heavy (slow/bloated) on your dev. It happens when you install themes or packages from here and then :)
Hope it makes more sense. 
But you replied to the main question perfectly, thanks again.

**Comment by abernix** [comment]
You're very welcome.  Glad that answered it for you!

I think I'll actually leave this open for a bit to see if FireFox can be addressed, but feel free to unsubscribe. :wink:

**Comment by abernix** [comment]
Closing this is in favor of (duplicate and older) #3304.  Thanks for reporting this again, @j2l.  Feel free to follow the other issue for more updates.
