### ISSUE TITLE
[1.3.*] Default app crashes in IE8

### ISSUE THREAD

**Issue by mperkh** [meteor/meteor#7141]
Meteor 1.3 does not seem to work with IE8 – I tried the default app created with ```meteor create 13testapp```. Tested using the [virtual machine offered by Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/).

Iit seems, the page crashes, because ```es5-shim``` is loaded after the Meteor bundles, eg. ```modules-runtime.js```.

![m13ie8](https://cloud.githubusercontent.com/assets/1648040/15671034/dff4e0a4-2728-11e6-9aec-0e22d16c44b9.png)

Also created default app, using ```meteor -release 1.2.1 create 12testapp``` and ```es5-shim``` is correctly loaded before all other scripts, so the 1.2 app does not crash in IE8.

Opened a [forum post 1Mo ago](https://forums.meteor.com/t/meteor-1-3-ie8-support/21672?u=mperkh), where the issue couldn't be resolved.

Is this a bug or are there now certain packages required for IE8 support?

**Comment by abernix** [comment]
I'll leave this to get an official opinion about this, but seeing as Microsoft officially announced that it will no longer support IE8 (End of Life) in January and it has <6% marketshare and dropping, I would find it unlikely that this gets much attention.  _Most_ websites, including Microsoft.com, don't work very well with IE8 anymore.

**Comment by mperkh** [comment]
Thanks for the reply, of course we will all be more than happy, if we can depreciate IE8. But I have a medical project and most clients in this hospital are still on old Windows versions with IE8. I know this is a horrible situation, but I don't make the rules there. The web-app I developed, works perfectly using Meteor 1.2 and if the only reason it does not work with 1.3 ist, that es5-shim is loaded to late, it should be possible to fix that and support IE8 for some more time.

Does [this](https://github.com/meteor/meteor/blob/devel/tools/static-assets/skel/.meteor/packages#L17) imply, Meteor supports IE8?

**Comment by abernix** [comment]
`es5-shim` is an attempt to maintain support with older browsers (and servers!), and at one point IE8 was (generally) covered by that.  However, it's possible that as the Meteor project progresses additional shims will be necessary to keep IE8 working as more native functions are used.  

You may want to experiment with the [es5-shims](https://github.com/es-shims/es5-shim) project and see what you find regarding the additional shims (and shams!) they have.

If you can figure out what exact properties are erroring out (starting with that first `Object` warning), it might lead to which shim is necessary.

**Comment by mjmasn** [comment]
@mperkh As a temporary workaround can you not just remove es5-shim from the project and load it from your site or a CDN in the `<head>` so that it loads first? 

As an aside - if you're supporting IE8/9 watch out for issues with constant reconnection + 100% CPU usage if your app is load balanced. With our apps we had to switch from least connections (+sticky cookie) to the less-than-ideal source ip based routing because IE wasn't always sending the cookie when polling, leading it to connect and log in to a new server every few seconds, and eventually hanging every server at 100% CPU.

**Comment by mperkh** [comment]
@mjmasn Thanks for the suggestion. This fixes the ```modules-runtime.js``` error described above. Now first error is ```Object expected``` at ```ecmascript-runtime.js```. Seems ```core-js```, which is used by the 'ecmascript' package, [has problems with IE8](https://github.com/zloirock/core-js/issues/32).

Giving up. For my future projects Meteor 1.3 does not support IE8.

**Comment by mperkh** [comment]
Similar situation with Meteor 1.4
![14ie8test](https://cloud.githubusercontent.com/assets/1648040/17131522/29bbcc4a-531e-11e6-9a04-3545e3d0f996.png)

**Comment by abernix** [comment]
@mperkh There is likely some ES6 code in one of your NPM packages which is getting used on the client which IE8 cannot parse.   Clicking on the links to the blue links to the source on the lines with the problems (starting with the first) would provide the most meaningful information about what exact line is causing this and step through your problem.

**Comment by tsgoak** [comment]
Seems like in modules.js, line 249, shown below, causes IE 8 error :"Expected Identifier."
  if (typeof Mp.import === "function" &&                                                                     // 7
      typeof Mp.export === "function") { 

Modules.js run before es5.shim.js, so it will cause es5-shim.js error :"Package.modules.meteorInstall" is null...

**Comment by abernix** [comment]
Closing with same comments as #7761:

> Per the [official deprecation notice by Microsoft](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), Internet Explorer 8 has reached it's official end-of-life.  While I recognize this might cause problems and chagrin for some, especially those in certain industries, I find it unlikely any steps will be taken by Meteor Core to resolve this.

> If there are particular and specific issues with clear and simple resolutions that can be made to maintain compatibility, feel free to open issues and PRs as appropriate, but "not compatible" issues for deprecated software aren't going to do much good sitting here.  Closing.
