### ISSUE TITLE
[1.3.2.4] Match.Optional not working properly in Match.ObjectIncluding

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#7150]
```JavaScript
check(undefined, Match.Optional(Object)) // Pass.
check({ a: undefined }, Match.ObjectIncluding({ a: Match.Optional(Object) })) // Error.
check({ }, Match.ObjectIncluding({ a: Match.Optional(Object) })) // Pass.
```

I expect the second line to pass as well. You can try running these two lines directly in the browser console.

Real implication: I might have an object:
```JavaScript
{
  foo: collection.findOne(selector)
}
```
and `#findOne` can return undefined.

Now I have to use `Match.Optional(Match.OneOf(Object, undefined))` in place of `Match.Optional(Object)`, which is silly.

**Comment by laosb** [comment]
Reproduced. Good catch, as I've seen many bugs in `check`.

**Comment by abernix** [comment]
This is actually the [documented behavior](http://docs.meteor.com/api/check.html#matchpatterns).  It also doesn't matter if it's `ObjectIncluding` or not.  Also a duplicate of #6959.
