### ISSUE TITLE
Mobile orientation in Xcode project after 'meteor build' is incorrect 

### ISSUE THREAD

**Issue by teodizzo** [meteor/meteor#7152]
Meteor 1.3.2.4
OS X El Capitan 10.11.5

When setting the mobile device orientation using Meteor's App.setPreference method, Xcode checks both "Portrait" and "Upside Down" to active instead of just "Portrait." This does not happen inside of the output directory for the android project, only the ios project. 

**Steps to recreate**:
- Define the orientation within the mobile-config.js file 

`App.setPreference("orientation", "portrait");`
- Building the project with the following command:

`meteor build <build-path> --server <server-url>`
- Open the project output in Xcode
- Observe: General > Deployment Info

![image](https://cloud.githubusercontent.com/assets/7098634/15724680/cc7bfe82-280d-11e6-955e-aa4a6874b96f.png)

**Expected Behavior**: Portrait should be checked
**Actual Behavior**: Portrait AND Upside Down are checked

**Comment by laosb** [comment]
Would try to repro today.

**Comment by dvolland** [comment]
For me all orientations in xcode are unchecked when I do the following:

```
App.setPreference("Orientation", "default"); //for android
App.setPreference("Orientation", "all", "ios"); //for ios
```
I would expect to have all checked in xcode.

**Comment by hwillson** [comment]
Meteor has received several Cordova updates since this issue was created. Due to the age of this issue, I'll close it for now. If anyone is still encountering this problem please post back and let us know. Thanks!
