### ISSUE TITLE
import bug with unit testing

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7153]
I'm on Meteor 1.3.2.4. I just implemented some basic unit testing per the instructions in the Meteor Guide, and I'm getting a couple errors:

One is with regards to the npm aws-sdk package:
```
W20160601-19:44:16.088(-7)? (STDERR) TypeError: Cannot read property 'Stream' of undefined
W20160601-19:44:16.088(-7)? (STDERR)     at Object.<anonymous> (/Volumes/SuperData/Sites/harris/L11/node_modules/aws-sdk/lib/http/node.js:2:44)
W20160601-19:44:16.088(-7)? (STDERR)     at Module._compile (module.js:456:26)
W20160601-19:44:16.089(-7)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160601-19:44:16.089(-7)? (STDERR)     at Module.load (module.js:356:32)
W20160601-19:44:16.089(-7)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160601-19:44:16.089(-7)? (STDERR)     at Module.require (module.js:364:17)
W20160601-19:44:16.089(-7)? (STDERR)     at require (module.js:380:17)
W20160601-19:44:16.089(-7)? (STDERR)     at Object.<anonymous> (/Volumes/SuperData/Sites/harris/L11/node_modules/aws-sdk/lib/aws.js:11:1)
W20160601-19:44:16.090(-7)? (STDERR)     at Module._compile (module.js:456:26)
W20160601-19:44:16.090(-7)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
```

The other has to do with an import statement:
```
W20160601-19:46:03.200(-7)? (STDERR) Error: Cannot find module '/imports/startup/client/routes'
W20160601-19:46:03.200(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
W20160601-19:46:03.200(-7)? (STDERR)     at meteorInstall.imports.redux.actions.insights.js (imports/redux/actions/insights.js:11:1)
W20160601-19:46:03.200(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160601-19:46:03.200(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160601-19:46:03.201(-7)? (STDERR)     at meteorInstall.imports.features.Insights.components.InsightDetail.js (imports/features/Insights/components/InsightDetail.js:22:1)
W20160601-19:46:03.201(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160601-19:46:03.201(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160601-19:46:03.201(-7)? (STDERR)     at meteorInstall.imports.features.Insights.components.InsightDetail.tests.js (imports/features/Insights/components/InsightDetail.tests.js:6:1)
W20160601-19:46:03.201(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160601-19:46:03.201(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1
```

I can't replicate either of these in a fresh project, unfortunately (and maddeningly). I thought maybe it was bombing out due to importing from an absolute path, but that's not the case.

This is one of the few frustrating things (about coding in general) that makes me want to burn it all and walk: everything works great in the repro project, but in the actual closed-source project with 4000+ lines of code.. nope. 😡

**Comment by ffxsam** [comment]
With the import error, I can get to a state where the test for my component works fine. Then once I uncomment this line in `InsightDetail.js`, the error above occurs:

    import * as routes from '/imports/startup/client/routes';

But in my test repro, this syntax works perfectly.

**Comment by abernix** [comment]
This really should be worked into a reproduction with help from those on the forums before being opened into an issue, but I'll do my best.

I understand if you can't provide your whole closed-source project.  But can you provide:

* The command that you're using to start your test mode? What reporter are you using?
* The contents of your `/imports/startup/client/routes.js` or `/imports/startup/client/routes/index.js` (whichever it is) file
* Where in your test file you're loading `aws-sdk` and how?  Even more so, perhaps why you're loading `aws-sdk` in unit tests?

Anything would help.  As of right now, there isn't much to work with here.

**Comment by ffxsam** [comment]
I know, it's tough. I'd literally have to hand you the entire project for you to experience what's going on, but I can't. _Maybe_ I could convince the project manager, if you were MDG staff and you were to sign an NDA. :) 

Anyway, I'll circle back here later today and try to post as many details as I can.

**Comment by abernix** [comment]
Even a mocked example!  Pseudo code!  A Bone? ;)  Is `routes` a file or a directory?

**Comment by ffxsam** [comment]
Ok. I'll dump out here what I can, without getting myself into trouble.

Let's start with the actual test causing the problem:

### InsightDetail.tests.js
```javascript
// FIXME: broken for now
// https://github.com/meteor/meteor/issues/7153

import React from 'react';
import { expect } from 'chai';
import { shallow } from 'enzyme';
import sinon from 'sinon';

import InsightDetail from './InsightDetail';

describe('<InsightDetail />', function () {
  if (Meteor.isServer) return;

  it('test not working :(', function () {

  });
});
```

So, it imports from `./InsightDetail` which has the following problematic import: (I know this is the problem because if I comment it out, things are OK - except the AWS SDK bug, which I'll cover later)

### InsightDetail.js
```javascript
// ...
import {
  setInsightCover,
  userRequestedEditInsight,
  userRequestedDeleteInsight,
  userRequestedSaveInsight,
  userRequestedSetRating,
  userSaveInsightField,
  userSaveInsightAttachment,
} from '/imports/redux/actions/insights';
// ...
```

And then..

### /imports/redux/actions/insights.js
```javascript
import { actions } from 'react-redux-form';
import { FlowRouter } from 'meteor/kadira:flow-router';

import {
  saveInsight,
  deleteInsight,
  setRating,
  saveInsightField,
  saveInsightAttachment,
} from '/imports/features/Insights/methods';
import * as routes from '/imports/startup/client/routes'; // problematic import
// ...
```

So I cut _all_ code from `/imports/startup/client/routes.js` to see what would happen. And lo and behold:

```
W20160602-16:36:22.392(-7)? (STDERR)
W20160602-16:36:22.393(-7)? (STDERR) /Users/samh/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160602-16:36:22.394(-7)? (STDERR)            				throw(ex);
W20160602-16:36:22.394(-7)? (STDERR)            				      ^
W20160602-16:36:22.660(-7)? (STDERR) Error: Cannot find module '/imports/startup/client/routes'
W20160602-16:36:22.661(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
W20160602-16:36:22.661(-7)? (STDERR)     at meteorInstall.imports.redux.actions.insights.js (imports/redux/actions/insights.js:11:1)
W20160602-16:36:22.661(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-16:36:22.661(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-16:36:22.661(-7)? (STDERR)     at meteorInstall.imports.features.Insights.components.InsightDetail.js (imports/features/Insights/components/InsightDetail.js:22:1)
W20160602-16:36:22.661(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-16:36:22.661(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-16:36:22.662(-7)? (STDERR)     at meteorInstall.imports.features.Insights.components.InsightDetail.tests.js (imports/features/Insights/components/InsightDetail.tests.js:9:1)
W20160602-16:36:22.662(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-16:36:22.662(-7)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
=> Exited with code: 8
```

**Comment by ffxsam** [comment]
SWEET. Got a repro repo!

https://github.com/ffxsam/meteor-test-breakage

**Comment by abernix** [comment]
I'm about to depart on holiday, so someone else will have to look at the repo (I'm on my phone), but based on your snippets above in this issue: why you think this import style  _would_ actually work?

From your `.tests.js`, you're trying to access the default export of `InsightDetail.js` (referring to it with `InsightDetail`) but `InsightDetail.js` exports nothing (and definitely not a default).  Therefore, importing `InsightDetail` *will* fail as there is nothing to import.

Additionally, basically same-same for your `insights.js` import of routes.  If you're having a failure with a clear `routes.js` it's because by clearing it (and not exporting anything), it is actually *not* a module and therefore: `Cannot find module`.

Again, just going off the code in this issue, but it sounds like you've misunderstood how ES modules work.

**Comment by ffxsam** [comment]
I went ahead and updated the repo so it actually exports stuff. The error still stands.

**Comment by ffxsam** [comment]
@tmeasday Can I get your opinion on this? Something seems broken here..

**Comment by abernix** [comment]
Hmm, Try renaming the `client` folder in `imports/startup/client/routes.js` to `giggle`.  (or anything besides `client`). :wink:

**Comment by abernix** [comment]
Its probably that importing anything in a `client` folder on the server just _won't_ work, even if explicitly stated.  The opposite (preventing `server` folders from _ever_ being imported on the client) could be perceived as a security safety net.

Probably related: #4969.

**Comment by tmeasday** [comment]
I think @abernix is right. Either make the test file in a `client` folder, move the routes file out of the `client` folder, or change the import to:

```js
if (Meteor.isClient) {
  const routes = require(...);
}
```

**Comment by ffxsam** [comment]
Wow, renaming the folder from `import/startup/client` to `import/startup/foobar` works. What.. the.. heck??

I was under the impression that the client/lib/server folder names didn't matter underneath `import`, that nothing is lazy loaded??

**Comment by ffxsam** [comment]
But why does my Meteor app have no problems whatsoever? It was just testing that was failing.

**Comment by tmeasday** [comment]
Well it's pretty simple. Because the test is *not* in a `client/` folder, it runs on both client and server. Then eventually it tries to require a client-only file.

In your app's normal operation, I would assume that none of the files that reference that client-only file are ever loaded on the server.

**Comment by ffxsam** [comment]
Ahh I see what you're saying. Yes, in the app, the `InsightDetail.js` is only imported by client-side code. And tests are client _and_ server.

So what is the ideal way to address this? Maybe just move the server check higher up? E.g.:

```javascript
if (Meteor.isServer) return;

import React from 'react';
import { expect } from 'chai';
import { shallow } from 'enzyme';
import sinon from 'sinon';

import InsightDetail from './InsightDetail';

describe('<InsightDetail />', function () {
  it('test not working :(', function () {

  });
});
```

**Comment by ffxsam** [comment]
Or I have to go back to using `client` and `server` folders within `/imports`.

**Comment by tmeasday** [comment]
There's no ideal solution. You can wrap your code in an `if (Meteor.isClient)` and use `require()` (for now! nested imports coming in 1.3.3!), or put it in a `client` folder.

**Comment by ffxsam** [comment]
Got it. Thanks again for pointing me in the right direction! I'm used to React unit tests being all client-side, and I totally forgot about the server-side aspect.
