### ISSUE TITLE
IPv6 addresses weren't properly parsed

### ISSUE THREAD

**Issue by chemicstry** [meteor/meteor#7155]
I'm trying to run meteor on IPv6, but opening app in browser gives 404 "Unknown path".

Using default app that is created with "meteor create xx". It works with IPv4, but it doesn't with IPv6.

Meteor version: 1.3.2.4
Platform: Debian GNU/Linux 8 amd64

By default meteor does not bind to IPv6 address so I tried starting with:
meteor run --port [::]:3000
meteor run --port [xxxx:........:xxxx]:3000

And then opening http://[xxxx:........:xxxx]:3000/ gives 404 "Unknown path"

By searching through source code I suspect that webapp package gives this error but I was unable to dig any further.

**Comment by chemicstry** [comment]
With a bit of digging I got it to work when I set ROOT_URL to my public IPv6:
export ROOT_URL="http://[xxxx:.........:xxxx]:3000/"
And then:
meteor run --port [::]:3000

But there is clearly something wrong when ROOT_URL is not set. Variable ROOT_URL_PATH_PREFIX gets initialized to "::" and then webapp_server.js throws that 404 error.

**Comment by chemicstry** [comment]
So here is the problem:

Command line "--port" option is seperated into ip and port here:
https://github.com/meteor/meteor/blob/a62d89519dbfb9e3ca7a1f0854cfd14edca09c6d/tools/cli/commands.js#L289

This is done in utils parseUrl which uses npm url library and removes [ ] brackets from IPv6:
https://github.com/meteor/meteor/blob/a62d89519dbfb9e3ca7a1f0854cfd14edca09c6d/tools/utils/utils.js#L22

ip and port get concatenated back to url at:
https://github.com/meteor/meteor/blob/a62d89519dbfb9e3ca7a1f0854cfd14edca09c6d/tools/runners/run-all.js#L56

However [ ] brackets are not added to IPv6 url and in case of localhost [::] url turn into http://:::3000/ instead of http://[::]:3000/

I don't know at which stage these brackets should be fixed so it's up to meteor developers to fix.

**Comment by laosb** [comment]
You're right and meteor didn't consider IPv6. Seems that meteor have similar problems in dealing IPv6 address in other parts.

**Comment by tmeasday** [comment]
I'm not sure this should be marked `Severity:production`. By the sounds of it and the look of the PR to fix it is is mainly a problem with the tool.
