### ISSUE TITLE
Options in .connect isn't documented.

### ISSUE THREAD

**Issue by ilacyero** [meteor/meteor#7156]
I had a problem to detect the connected state of DDP client connection.
I find in the documentation how to add this callback. I must debug the initialize to see the options and its onConnected options. Please try to add in documentation. 
```
    const connection = DDP.connect(config, {
      onConnected() {
        console.log('connected');
      }
    });
```

**Comment by laosb** [comment]
Thank you! But this should be in `meteor/docs` as MDg has moved docs to the separated repo. Closing this and I will repost this to docs!
