### ISSUE TITLE
Importing LESS/CSS during 'meteor test' fails

### ISSUE THREAD

**Issue by hellogerard** [meteor/meteor#7157]
I am importing a LESS file for a particular component as described in the [guide](http://guide.meteor.com/build-tool.html#css-importing). It looks like this:

```js
// bug.js
import './bug.less';

// code for component

export default Bug;
```

It works exactly as expected when running the app. Now, I am trying to test this component. The test looks like this:

```js
// bug.tests.js
import { chai } from 'meteor/practicalmeteor:chai';
import Bug from './bug.js';

// code for tests
```

When I run `meteor test`, I am getting an error: 

```
W20160602-11:20:47.722(-4)? (STDERR) Error: Cannot find module './bug.less'
W20160602-11:20:47.722(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
W20160602-11:20:47.722(-4)? (STDERR)     at meteorInstall.imports.bug.js (imports/bug.js:1:1)
W20160602-11:20:47.722(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-11:20:47.722(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-11:20:47.722(-4)? (STDERR)     at meteorInstall.imports.bug.tests.js (imports/bug.tests.js:2:1)
W20160602-11:20:47.723(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-11:20:47.723(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-11:20:47.723(-4)? (STDERR)     at /private/var/folders/st/_8fwkbw97zn2q9vh8ycdn0w40000gn/T/meteor-test-run1i4gcsc/.meteor/local/build/programs/server/app/app.js:44:1
W20160602-11:20:47.723(-4)? (STDERR)     at /private/var/folders/st/_8fwkbw97zn2q9vh8ycdn0w40000gn/T/meteor-test-run1i4gcsc/.meteor/local/build/programs/server/boot.js:283:10
W20160602-11:20:47.723(-4)? (STDERR)     at Array.forEach (native)
```

FYI, if I change the LESS file to CSS, I get a different error:

```
W20160602-11:22:37.640(-4)? (STDERR) TypeError: Object [object Object] has no method 'addStyles'
W20160602-11:22:37.640(-4)? (STDERR)     at meteorInstall.imports.bug.css (imports/bug.css:1:1)
W20160602-11:22:37.640(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-11:22:37.640(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-11:22:37.640(-4)? (STDERR)     at meteorInstall.imports.bug.js (imports/bug.js:1:1)
W20160602-11:22:37.640(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-11:22:37.641(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-11:22:37.641(-4)? (STDERR)     at meteorInstall.imports.bug.tests.js (imports/bug.tests.js:2:1)
W20160602-11:22:37.641(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160602-11:22:37.641(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160602-11:22:37.641(-4)? (STDERR)     at imports/bug.css:3:1
```

This should work, right? Or am I mistaken?  I could of course apply styles a different way, but I like this feature, but this error is preventing me from testing my components. I am on Mac OS El Capitan / Meteor 1.3.2.4.  It might be related to work performed for #6798, where the original feature was implemented. I have a reproduction [here](https://github.com/hellogerard/meteor-import-less-bug.git). To reproduce this bug:

```bash
$ git clone https://github.com/hellogerard/meteor-import-less-bug.git
$ cd meteor-import-less-bug
$ npm test # see errors in console
```

**Comment by abernix** [comment]
Essentially, `.css` (or `.scss`, `.less`, `.styl`, etc.) cannot _currently_ be imported on the server (see #6852).  When running `meteor test`, your `*.tests.*` files are being eagerly loaded ([per the way `test` modes work](https://guide.meteor.com/testing.html#test-modes)) and the import is being attempted on the server, which will currently fail.

If you:

0. Upgrade to Meteor 1.3.3 or higher (but preferably 1.3.4.1, current as of writing this) – which supports nested `import` statements.
0. Move your `import` in `bug.tests.js` into the `if (Meteor.isClient)` conditional statement.

...everything should work.

Ultimately, this is related to #6852, so closing in favour of that.

Hope this helps!  :smile:

**Comment by teebszet** [comment]
@abernix Thanks for the workaround!

Is there any potential to provide a solution within the meteor test mode, to ignore .css files? maybe similar in the way that I could do with plain mocha and [ignore-styles](https://www.npmjs.com/package/ignore-styles).

```
mocha --compilers js:babel-register imports/ui/directory-splash.test.js --require ignore-styles
```

Thanks
