### ISSUE TITLE
spontaneous logouts

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#7158]
In a deployed production app we're having users getting logged out spontaneously by the system.  It seems to be related to intermitten network connection failures.  Are there any circumstances under which Meteor would spontaneously log a user out?  I can't find a lot of documentation about what happens when the connection fails.

**Comment by jedwards1211** [comment]
See https://github.com/meteor/accounts/issues/6

**Comment by laosb** [comment]
Did the DDP connection break when the user is logged out?

**Comment by jedwards1211** [comment]
@laosb I haven't been able to verify that yet, but I just found out that what was actually happening was the kiosk browser applet on the tablet being used in production automatically reloads the start page when it detects that the network connection comes back, so there may be no issue with Meteor.

**Comment by laosb** [comment]
That might be related. As we failed to repro, I'm closing this, but feel free to reopen if it happens again!
