### ISSUE TITLE
Missing crosswalk-library

### ISSUE THREAD

**Issue by fschaeffler** [meteor/meteor#7161]
Since yesterday, we have some strange behavior on our build-server. Builds kept failing so we started to re-build from git-commits, which already succeeded previously.

When building, we get the following exception.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches org.xwalk:xwalk_core_library_beta:13+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library_beta/maven-metadata.xml
         https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library_beta/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library_beta/maven-metadata.xml
         file:/usr/local/bin/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library_beta/maven-metadata.xml
         file:/usr/local/bin/android-sdk-linux/extras/android/m2repository/org/xwalk/xwalk_core_library_beta/
         file:/usr/local/bin/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library_beta/maven-metadata.xml
         file:/usr/local/bin/android-sdk-linux/extras/google/m2repository/org/xwalk/xwalk_core_library_beta/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

It seems from the mentioned link at https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library_beta/ that there had been an update of crosswalk.

Is this a meteor or a pure crosswalk-issue?

**Comment by pmwisdom** [comment]
It is a pure crosswalk issue, I'm assuming your using crosswalk v1.7.0? 

Try removing that and using meteors version which is version 1.6.3?. I believe they moved around some libraries on https://download.01.org which is causing the resolver to fail because it can't find  org.xwalk:xwalk_core_library_beta:13+.

**Comment by fschaeffler** [comment]
It seems it was a very old reference in `.meteor/cordova-plugins`. There you need to set a tagged version yourself and we had the entry `cordova-plugin-crosswalk-webview@1.2.0`, which we now manually needed to update to `cordova-plugin-crosswalk-webview@1.6.0`.

**Comment by 88plug** [comment]
+1 Definitely a bug - can't use 1.6.0 - 1.7.2

Instead try changing your config.xml found in .meteor/local/cordova-build/

<preference name="xwalkVersion" value="xwalk_core_library_beta:18+" />
change it to:

<preference name="xwalkVersion" value="xwalk_core_library:18+" />
