### ISSUE TITLE
[1.3.3-rc.0] Meteor running out of memory when app is tested

### ISSUE THREAD

**Issue by Ben305** [meteor/meteor#7168]
Since Meteor 1.3.3-rc.0, it is not possible to start tests for our app:

<pre>
meteor test --verbose --settings settings-development.json --driver-package dispatch:mocha-phantomjs --port 3010 --once

[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1y86e5m.10t3sji/os/lib/browser-polyfill.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1y86e5m.10t3sji/web.browser/lib/browser-polyfill.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1y86e5m.10t3sji/web.cordova/lib/browser-polyfill.js" as it exceeds the max of "100KB".
{ [SyntaxError: /meteor-wastebin-1nniv9l/mt-12tpvx6.1h48z7d/npm/node_modules1/glob/test/00-setup.js: 'return' outside of function (81:2)]
  pos: 1772,
  loc: { line: 81, column: 2 },
  _babel: true,
  codeFrame: 'if (process.platform === "win32" || !process.env.TEST_REGEN) {\n  console.error("Windows, or TEST_REGEN unset.  Using cached fixtures.")\n  return\n}\n\nvar spawn = require("child_process").spawn;' }
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-p3mars.hqj1iz/web.browser/bower_components/fullcalendar/dist/fullcalendar.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-p3mars.hqj1iz/web.cordova/bower_components/fullcalendar/dist/fullcalendar.js" as it exceeds the max of "100KB".
{ [SyntaxError: /meteor-wastebin-1nniv9l/mt-12tpvx6.1h48z7d/npm/node_modules1/supports-color/cli.js: 'return' outside of function (21:1)]
  pos: 361,
  loc: { line: 21, column: 1 },
  _babel: true,
  codeFrame: 'if (argv.indexOf(\'--help\') !== -1) {\n\thelp();\n\treturn;\n}\n\nif (argv.indexOf(\'--version\') !== -1) {' }
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-129gr7y.18n4fnk/os-legacy/packages/jquery.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-129gr7y.18n4fnk/web.browser-legacy/packages/jquery.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-129gr7y.18n4fnk/web.cordova-legacy/packages/jquery.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-12d15g9.17l56s7/plugin.compileTemplatesBatch.os/packages/ecmascript-runtime.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-12d15g9.17l56s7/plugin.compileTemplatesBatch.os/packages/html-tools.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-148rfwe.trz4wh/web.browser-legacy/packages/fastclick.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-148rfwe.trz4wh/web.cordova-legacy/packages/fastclick.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1g6mdz3.rea76x/plugin.compileNGTemplate.os/packages/html-tools.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1g6mdz3.rea76x/plugin.compileNGTemplate.os/packages/meteor.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1g6mdz3.rea76x/plugin.compileNGTemplate.os/packages/spacebars-compiler.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1g6mdz3.rea76x/plugin.compileNGTemplate.os/packages/underscore.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1h34eky.7365r0/os-legacy/packages/netanelgilad_polyfill-angular-server.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1kehbet.1xanvuj/os-legacy/packages/minimongo.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1kehbet.1xanvuj/web.browser-legacy/packages/minimongo.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1kehbet.1xanvuj/web.cordova-legacy/packages/minimongo.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1l6oif6.1kcl31n/os-legacy/packages/srp.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1l6oif6.1kcl31n/web.browser-legacy/packages/srp.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1l6oif6.1kcl31n/web.cordova-legacy/packages/srp.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1ou30wi.14vohre/os-legacy/packages/meteor.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1ou30wi.14vohre/web.browser-legacy/packages/meteor.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1ou30wi.14vohre/web.cordova-legacy/packages/meteor.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1qfolhv.1pef2kv/os/packages/practicalmeteor_chai.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1qfolhv.1pef2kv/web.browser/packages/practicalmeteor_chai.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1qfolhv.1pef2kv/web.cordova/packages/practicalmeteor_chai.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1s5wrw9.1ez1dc1/web.browser/packages/mquandalle_perfect-scrollbar.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1s5wrw9.1ez1dc1/web.cordova/packages/mquandalle_perfect-scrollbar.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1stn4ah.pmssf7/os-legacy/packages/spacebars-compiler.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1stn4ah.pmssf7/web.browser-legacy/packages/spacebars-compiler.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-1stn4ah.pmssf7/web.cordova-legacy/packages/spacebars-compiler.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-39m7ja.yu9wv9/plugin.compileCoffeescript.os/packages/compileCoffeescript_plugin.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-39m7ja.yu9wv9/plugin.compileCoffeescript.os/packages/ecmascript-runtime.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-6vjyug.4qerjc/web.browser-legacy/packages/alanning_roles.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-6vjyug.4qerjc/web.cordova-legacy/packages/alanning_roles.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-bvhyh6.ymvf76/plugin.compileScssBatch.os.linux.x86_64/packages/ecmascript-runtime.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-czdjv8.1uwg0ub/os-legacy/packages/check.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-czdjv8.1uwg0ub/web.browser-legacy/packages/check.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-czdjv8.1uwg0ub/web.cordova-legacy/packages/check.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-fqfh5o.xiupb2/os/min/locales.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-fqfh5o.xiupb2/os/min/locales.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-fqfh5o.xiupb2/os/min/moment-with-locales.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/meteor-wastebin-1nniv9l/mt-fqfh5o.xiupb2/os/min/moment-with-locales.min.js" as it exceeds the max of "100KB".
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Aborted (core dumped)
</pre>

This does not happen when using 1.3.3-beta.2. I guess this is related to 73685f6?

cc @benjamn

**Comment by laosb** [comment]
I'm not helpful on testing. Hope someone can look at this soon.

**Comment by benjamn** [comment]
I've reverted that commit, though I have to admit I have no idea why Babel would be running on files that have been moved to temp directories. This should be fixed in `1.3.3-rc.1`, out soon.

**Comment by Ben305** [comment]
Fixed in rc1, thanks!
