### ISSUE TITLE
[1.3.3-rc.0] Mocha test server promise functions

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7171]
I'm trying to test server functions that use promises (async / await) in my app and it's complaining: 
```
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
```

I've tried using `chai-as-promised`, simply writing my own promise assertions, and then using `Promise.await` in hopes that would make it happy.

As it stands I seem to be completely unable to test server methods that return promises (rather than using Fibers).

I'm trying to get off of Fibers since they are basically deprecated in favor of promises as far as I can tell. I thought Meteor was now fully able to support promises on the server side at this point?

**Comment by benjamn** [comment]
Using promises should allow you to avoid using fibers directly, though for legacy reasons we do run `Promise` callbacks in fibers, which means `Meteor.bindEnvironment` should never be necessary.

What does your `Meteor.methods(...)` call look like on the server? What's the stack trace for that error?

It's possible that your test harness is using raw `setTimeout` or something of that sort, which might cause code that uses fibers to run outside the context of a `Promise` callback.

**Comment by clayne11** [comment]
It's not actually a Meteor method. I generally abstract out my method body into a service so that I can call it directly on the server (passing in a `userId` and bypassing permission validation) or from a method where I perform permission validation and use `this.userId`.

I don't have any `setTimeout` anywhere in the code. It's all `async` / `await`.

If you don't have any other ideas I'll try to create a reproduction.

**Comment by clayne11** [comment]
Looks like this was a problem with the `practicalchai:mocha` package. It's been fixed in the newest release.
