### ISSUE TITLE
Android not connecting to server on 1.3.2.4

### ISSUE THREAD

**Issue by jbrozena22** [meteor/meteor#7172]
***2 Upvotes*** Android is unable to connect to the Meteor server on 1.3.2.4, even with a basic stock app run locally. 
 
Steps to reproduce:
(open an Android simulator or plug in an Android device)
```
meteor create testmobile
cd testmobile
meteor add-platform android
meteor run android-device
```
The client app opens fine on the simulator/device. However, if on chrome you go to chrome://inspect/#devices and select inspect on your app, in the Javascript console you will see:
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE

Trying Meteor.connection.status() shows you are not connected. Obviously this means any code that requires the server doesn't work (method calls, collections, etc). 
This has completely broken our Android app - kind of shocked no one else is seeing this behavior.

Meteor Version: 1.3.2.4
Platform: Android 4.4 (tested both on physical device and simulator)
Packages: Nothing other than what comes with meteor create

**Comment by laosb** [comment]
Interesting. Will try after I install the Android SDK (just got a reinstall of OS X, still reinstalling many apps, sorry!)

**Comment by wanchopeblanco** [comment]
Im having a similar issue where my iOS app works just fine but my android app wont connect to the server, even if i run it at localhost. I get this error on the console

Failed to load resource: net::ERR_CACHE_MISS

**Comment by cunneen** [comment]
+1 I have this issue on android too.

meteor run android-device

My android device can't connect with ```net::ERR_ADDRESS_UNREACHABLE```, on the same wifi network. The issue doesn't occur on android. I'm suspecting a missing cordova plugin.

Meteor 1.3.2.4

**Comment by jimmy1993k** [comment]
+1 Having this issue as well, iOS works fine but Android just gives Failed to load resource: net::ERR_ADDRESS_UNREACHABLE. This is at Meteor 1.3.3.1.

**Comment by markoshust** [comment]
I can confirm this is also happening to me, trying to setup a fully working iOS app in Android. Might be worth it pulling @martijnwalraven into this as I know he's the mobile expert. Meteor 1.3.2.4 here.

**Comment by markoshust** [comment]
For what it's worth, here are the opening lines after meteor run ios-device:


    => App running at: http://localhost:3000/     
      => Started app on Android Device.
      I20160621-10:52:33.326(-4)? I/chromium( 1299): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
    I20160621-10:52:33.512(-4)? W/chromium( 1299): [WARNING:dns_config_service_posix.cc(298)] Failed to read DnsConfig.
      I20160621-10:52:33.512(-4)? E/chromium( 1299): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
      I20160621-10:52:33.513(-4)? E/chromium( 1299): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
    I20160621-10:52:33.516(-4)? E/chromium( 1299): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
    I20160621-10:52:33.518(-4)? I/chromium( 1299): [INFO:xwalk_extension_renderer_controller.cc(43)] EXTENSION PROCESS DISABLED.
      I20160621-10:52:33.518(-4)? I/MeteorWebApp( 1299): Serving asset bundle with version: 6ea619deeb8dc1c431cb83035c940432d10cd631
    I20160621-10:52:33.518(-4)? E/chromium( 1299): [ERROR:layer_tree_host_impl.cc(2121)] Forcing zero-copy tile initialization as worker context is missing
    I20160621-10:52:35.938(-4) (android:http://localhost:12296/packages/modules.js:14691) Download the React DevTools for a better development experience: https://fb.me/react-devtools
      I20160621-10:52:37.021(-4)? I/chromium( 1299): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
    I20160621-10:52:37.022(-4)? I/chromium( 1299):
    I20160621-10:52:37.022(-4)? I/chromium( 1299): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
    I20160621-10:52:37.023(-4)? I/chromium( 1299):
    I20160621-10:52:42.623(-4)? E/chromium( 1299): [ERROR:xwalk_autofill_client.cc(172)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()

**Comment by markoshust** [comment]
Note, I also tried setting a remote mobile-server, but I'm still getting `et::ERR_NAME_NOT_RESOLVED` error. 

Tried adding the following to mobile-config.js:
App.accessRule('*');
App.accessRule('http://*');
App.accessRule('https://*');

None of these helped. This is a very critical blocker (surprised more aren't having this?) as it completely prevents dev/deploy for Android.

**Comment by martijnwalraven** [comment]
@markohust: I'm not sure what is going on here, but it doesn't seem Meteor related. I suspect here is a network/DNS error that results in the server name not being resolved (maybe `Failed to read DnsConfig` is related?)

**Comment by markoshust** [comment]
@martijnwalraven thank you, it was indeed a misconfigured wifi connection on my mobile device. fixed the wifi connection, all working now! i'm guessing everyone else in this ticket has a similar issue if you are receiving the `DnsConfig` error...

**Comment by abernix** [comment]
I'm going to close this because there has been a lack of activity for a while and it seems to be a generally isolated situation or strangeness in setup (as Mark had found).
