### ISSUE TITLE
meteor windows installer stuck at v1.0 

### ISSUE THREAD

**Issue by Metrophobe** [meteor/meteor#7174]
It seems like the windows installer is stuck at V1.0 on the website when it clearly says that meteor arrived at V1.3.

**Comment by laosb** [comment]
Actually it downloads the latest version. Where did you see "v1.0"?

**Comment by Metrophobe** [comment]
The installer said V1.0 under add/remove programs in windows.

**Comment by stubailo** [comment]
Yeah the way to get the current meteor version installed is to type "meteor --version" in the console. Meteor does its own updating so you don't need to use the installer after the initial download at all.
