### ISSUE TITLE
meteor windows installation location 

### ISSUE THREAD

**Issue by Metrophobe** [meteor/meteor#7175]
The installation location cannot be changed and is located on the C drive. Allow users to install this to any drive / folder.

**Comment by laosb** [comment]
Actually you can follow the alternative installing to do that.

**Comment by Metrophobe** [comment]
Well, in the windows environment there is nothing wrong with using an installer packaging tool which offers a folder selection prior to installation.  Make it easier for people to adapt and use meteor.

**Comment by laosb** [comment]
I think there was a similar FR long ago, and I'm sure that is not a common usage. In fact, macOS / Linux users don't have the ability to choose, too. Would close this.
