### ISSUE TITLE
[1.3.3-rc.1] App won't build - exited with code 1

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7185]
I upgraded from `rc.0` to `rc.1` and now I'm getting the dreaded `Exited with code: 1`.

I can't provide any more information really since this error has stack trace.

On a side node, this error REALLY needs to be handled more gracefully. Issues that, when run on the client, post a clear stack trace are simply `Exited with code: 1` on the server which is next to impossible to debug.

**Comment by benjamn** [comment]
This does seem super annoying!

The logging statement responsible for that unhelpful error is [here](https://github.com/meteor/meteor/blob/5ae53de46b3f2cc8331de54c7b254f40059a85b5/tools/runners/run-app.js#L935).

You're on Windows, right? If you edit `AppData\Local\.meteor\packages\meteor-tool\1.3.3-rc.1\mt-os.windows.x86_32\tools\runners\run-app.js` to add a `console.log(runResult)` before that line, perhaps there's some more information in the `runResult` that could be useful here…

If so, then we should definitely definitely improve the error logging.

**Comment by clayne11** [comment]
I'm not on Windows. OS X 10.11.5.

**Comment by benjamn** [comment]
Ok, then it's `~/.meteor/packages/meteor-tool/1.3.3-rc.1/mt-os.osx.x86_64/tools/runners/run-app.js` instead.

**Comment by clayne11** [comment]
Whatever it was is fixed in `1.3.3-rc.4`.

**Comment by laosb** [comment]
Good to see this was fixed in rc4. Closing.

**Comment by renanduart3** [comment]
meteor npm install --save babel-runtime

**Comment by Bl0uf** [comment]
@renanduart3 Thanks a lot !

**Comment by marlontamo** [comment]
@renanduart3  thanks legit!!!

**Comment by itrevex** [comment]
Had similar issue. Issue popped up after install react-meteor-data;
Restarting my machine and reinstalling the package seems to have worked.
