### ISSUE TITLE
[1.3.3-rc.4] Can't add "account-password"

### ISSUE THREAD

**Issue by derencel20** [meteor/meteor#7188]
**Error:**
![image](https://cloud.githubusercontent.com/assets/17394978/15891811/e9092bb0-2da8-11e6-802e-093623419966.png)

**Packages:** 
![image](https://cloud.githubusercontent.com/assets/17394978/15891835/14c4c1d8-2da9-11e6-83cf-c67e76c21d67.png)

**Dependencies:**
![image](https://cloud.githubusercontent.com/assets/17394978/15891847/235003c0-2da9-11e6-8dd0-e13a2fe02dce.png)

**.babelrc:**
![image](https://cloud.githubusercontent.com/assets/17394978/15891859/38932dfc-2da9-11e6-914c-32ba6b97569c.png)

**Comment by derencel20** [comment]
Also in 1.3.3-beta.1

**Comment by benjamn** [comment]
Are you able to run `meteor npm install bcrypt` in your application directory?

**Comment by derencel20** [comment]
@benjamn 
Here's the error:
![image](https://cloud.githubusercontent.com/assets/17394978/15903326/c88c6a9c-2dde-11e6-961f-611cf2553270.png)

I'm on windows 10 btw,

**Comment by derencel20** [comment]
I've also observed that  running `meteor npm install bcrypt`, even with the most stable version of meteor which is 1.3.2.4, yields an error.

**Comment by benjamn** [comment]
Ok, how about
```sh
meteor npm config set python 'C:\Users\Tensai\AppData\Local\.meteor\packages\meteor-tool\1.3.3-rc.4\mt-os.windows.x86_32\dev_bundle\python\python.exe'
meteor npm install bcrypt
```
If `C:\Users\Tensai\AppData\Local\.meteor\packages\meteor-tool\1.3.3-rc.4` doesn't exist, then you need to do `meteor update --release 1.3.3-rc.4`.

**Comment by benjamn** [comment]
Some background: in 1.3.3, we actually ship a minimal Python binary with the Windows dev bundle, but I'd definitely like to know if that's not working, because if it's not reliable then we should just let users know they may have to install Python 2.7.

**Comment by derencel20** [comment]
![image](https://cloud.githubusercontent.com/assets/17394978/15904021/f46049f6-2de1-11e6-8be1-911a9e28cae9.png)
Error again

**Comment by derencel20** [comment]
This is my npm-debug file. I converted it to text so that it can be uploaded.
[debug.txt](https://github.com/meteor/meteor/files/305358/debug.txt)

**Comment by benjamn** [comment]
Does that `...\python.exe` program work if you try to run it? Thanks for your patience with all the questions.

**Comment by derencel20** [comment]
I'll try.

**Comment by derencel20** [comment]
like this? 
![image](https://cloud.githubusercontent.com/assets/17394978/15904612/3e0236c6-2de4-11e6-8f1d-55f53b328a25.png)

**Comment by derencel20** [comment]
tried installing python 2.7 manually, and another error
![image](https://cloud.githubusercontent.com/assets/17394978/15919984/010737b6-2e49-11e6-9d81-bedc15f7d390.png)

**Comment by derencel20** [comment]
@laosb I think this is only a bug in windows tho, my teacher uses linux and he didn't have any problems adding accounts-password.

**Comment by laosb** [comment]
I see. Added `Project:Windows` too.

**Comment by benjamn** [comment]
The full solution is likely to follow the Windows installation instructions for `node-gyp`: https://github.com/nodejs/node-gyp#installation. Note that there's a standalone version of the Visual Studio command-line tools, so you don't necessarily have to install the full VS IDE.

**Comment by mueller-andre** [comment]
Had the same problem on Mac OS X 10.11.5
`meteor add npm-bcrypt` fixed it for me.
Surprisingly it's also the most trending package at the moment.

**Comment by benjamn** [comment]
@mueller-andre did you do that, within the past couple of minutes? I literally just published `npm-bcrypt@0.8.6_1`, in hopes of fixing this problem, so you may have gotten that version!

**Comment by mueller-andre** [comment]
@benjamn yeah literally 10 min ago. :P
Had the same problem that I couldn't add "accounts-password" and it always came up with the following error message:
`meteor add accounts-password
 => Errors while adding packages:             
                                              
While checking for npm-bcrypt@0.8.6_1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.`

Your suggestion of trying `meteor npm install bcrypt` executed and terminated without any errors but didn't fix the "accounts-password" problem. After I tried `meteor add npm-bcrypt` it all worked fine after that.

**Comment by derencel20** [comment]
thanks @benjamn. Fixed it!
Should i close the thread?

**Comment by benjamn** [comment]
Glad to hear it! Please reopen if this happens again.

**Comment by storedev99** [comment]
Hello benjamn,

When i follow the guide here https://github.com/nodejs/node-gyp#installation.. i get the following error http://pastie.org/10923820

Inside my project directory, when i do a 

node -v => v6.3.1
npm -v => 3.10.5

Will be great if you can help us understand what the issue is and how do i solve this ?

**Comment by abernix** [comment]
@storedev99 Your Pastie is gone.  Please repost somewhere it can be analyzed if you need help.

**Comment by storedev99** [comment]
Thanks for the time and Sorry for the paste expiration,
Also it striked to me that, I am running Meteor version 1.4 and commented here by mistake.
So have routed the query to [here](https://github.com/meteor/meteor/issues/7543#issuecomment-237149420)
