### ISSUE TITLE
Meteor.http.post doesn't post data correctly

### ISSUE THREAD

**Issue by VasilySizov** [meteor/meteor#719]
Hi, guys!

I'm implementing a module for interaction with PayPal's ExpressCheckout (https://www.x.com/developers/paypal/documentation-tools/express-checkout/integration-guide/ECGettingStarted#id0832BA0605Z)
and stuck with a simple POST request.

Assume we have HTML such as given below:

```
<form method="post" action="https://api-3t.sandbox.paypal.com/nvp">
    <input type="hidden" name="USER" value="sdk-three_api1.sdk.com">
    <input type="hidden" name="PWD" value="QFZCWN5HZM8VBG7Q">
    <input type="hidden" name="SIGNATURE" value="A-IzJhZZjhg29XQ2qnhapuwxIDzyAZQ92FRP5dqBzVesOkzbdUONzmOU">
    <input type="hidden" name="VERSION" value="64.0">
    <input type="hidden" name="PAYMENTREQUEST_0_PAYMENTACTION" value="Sale">
    <input type="hidden" name="PAYMENTREQUEST_0_AMT" value="19.95">
    <input type="hidden" name="RETURNURL" value="https://www.YourReturnURL.com">
    <input type="hidden" name="CANCELURL" value="https://www.YourCancelURL.com">
    <input type="hidden" name="METHOD" value="SetExpressCheckout">
    <input type="submit">
</form>
```

Quite simple. If you click the Submit button you get a response from PayPal:
    TOKEN=EC%2d5E833286G60906214&TIMESTAMP=2013%2d02%2d21T11%3a47%3a03Z&CORRELATIONID=e6dab80787a99&ACK=Success&VERSION=64%2e0&BUILD=5294323

So, ACK=Success.

If we write it with Meteor on the server side we get something like this:

```
Meteor.http.post(
    "https://api-3t.sandbox.paypal.com/nvp"
    data:
        "USER": "sdk-three_api1.sdk.com"
        "PWD": "QFZCWN5HZM8VBG7Q"
        "SIGNATURE": "A-IzJhZZjhg29XQ2qnhapuwxIDzyAZQ92FRP5dqBzVesOkzbdUONzmOU"
        "VERSION": "64.0"
        "PAYMENTREQUEST_0_PAYMENTACTION": "Sale"
        "PAYMENTREQUEST_0_AMT": "19.95"
        "RETURNURL": "https://www.YourReturnURL.com"
        "CANCELURL": "https://www.YourCancelURL.com"
        "METHOD": "SetExpressCheckout"
    (error, result) -> console.log(result)
)
```

But the request results with:

```
{ statusCode: 200,
    content: 'ACK=Failure&L_ERRORCODE0=81002&L_SHORTMESSAGE0=Unspecified%20Method&L_LONGMESSAGE0=Method%20Specified%20is%20not%20Supported&L_SEVERITYCODE0=Error',
    headers: 
        { date: 'Thu, 21 Feb 2013 11:57:19 GMT',
        server: 'Apache',
        'content-length': '146',
        connection: 'close',
        'content-type': 'text/plain; charset=utf-8' },
    data: null,
    error: null }
```

I tried to post the data to my http webserver to check the request, and it looks good.

Also I coulnd't find a solution for a problem with Meteor.http and PayPal's Instant Payment Notification verification (when you post back the data sent by PayPal).  PayPal couldn't recognize the request also. I plugged in node.js module instead and it worked great (https://github.com/andzdroid/paypal-ipn).

Looks like the problem is somwhere in https.

Look forward to your suggestions!

Thanks!

**Comment by aadamsx** [comment]
It's been a long time, but a question for you @VasilySizov?

I'm trying to do the same thing as you did and I'm having issues.

```
Router.route('/paypal-callback', function (req, res) {
  var querystring = Npm.require('querystring');
  console.log('Received POST /');

  // STEP 1: read POST data
  req.body = req.body || {};
  req.statusCode = 200;
  res.end('OK');

  // read the IPN message sent from PayPal and prepend 'cmd=_notify-validate'
  var postreq = 'cmd=_notify-validate';
  for (var key in req.body) {
    if (req.body.hasOwnProperty(key)) {
      var value = querystring.escape(req.body[key]);
      postreq = postreq + "&" + key + "=" + value;
    }
  }

  // Step 2: POST IPN data back to PayPal to validate
  console.log('Posting back to paypal');
  HTTP.post('https://www.sandbox.paypal.com/cgi-bin/webscr', { 
    params: postreq 
  }, function (error, result) {
    console.log('Error: ' + error);
    return console.log('Result: ', + result.content);
  });
  return [204, 'No Content'];
}, {where: 'server'});
```
I get the initial IPN, but after my attempt to POST back, nothing.

I don't get any errors and and I don't get a result either.  I'm using the IPN simulator and targeting my my  SSL enabled staging site on AWS.

Server logs:
[staging.my_domain.com] Received POST /
[staging.my_domain.com] Posting back to paypal
[staging.my_domain.com] Error: null
[staging.my_domain.com] Result:  0

**Comment by VasilySizov** [comment]
Hi, @aadamsx 

Unfortunately, I don't remember how I solved the problem. Nowadays I just use https://github.com/andzdroid/paypal-ipn to verify IPNs. It works fine.

**Comment by aadamsx** [comment]
Thanks @VasilySizov .... but this is a node.js package, I don't know how to add this to my Meteor project.

**Comment by aadamsx** [comment]
I got it working.  But do you have an example you can share using paypal-ipn?

**Comment by aadamsx** [comment]
Wow, https://github.com/andzdroid/paypal-ipn to verify IPNs works!  Thank you so much @VasilySizov!
