### ISSUE TITLE
Add `build` key to `App.info` object

### ISSUE THREAD

**Issue by tyvdh** [meteor/meteor#7191]
Cordova allows us to use `android-versionCode="x.x.x"` and `ios-CFBundleVersion="x.x.x"` to denote build numbers of our app versions. Would love to have the ability to just set a build number inside the `App.info` object so I don't have to manually do it in Xcode.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20%60build%60%20key%20to%20%60App.info%60%20object&body=Migrated%20from:%20meteor/meteor%237191) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
