### ISSUE TITLE
Add android_xxxhdpi_[portrait, landscape] support

### ISSUE THREAD

**Issue by tyvdh** [meteor/meteor#7192]
Need to be able to insert these triple x splash screen values. Might want to consider a better, more customizable solution to better future proof new screen sizes/resolutions. This system relies way to much on you adding support for keys regularly. Probably not the best idea.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20android_xxxhdpi_%5Bportrait%2C%20landscape%5D%20support&body=Migrated%20from:%20meteor/meteor%237192) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
