### ISSUE TITLE
Doesn't run babel on NPM dependencies

### ISSUE THREAD

**Issue by mhagmajer** [meteor/meteor#7193]
I have a private Node package that I use as dependency in a few projects. This package has async code, so I need Meteor to handle transpiling and produce different code for client (based on regenerator) and server (fibers). Unfortunately, when I run meteor I am getting these errors:

```
me$ meteor
[[[[[ ~/MyProject ]]]]]                

=> Started proxy.                             
=> Started MongoDB.                           
W20160609-03:06:52.455(2)? (STDERR)           
W20160609-03:06:52.595(2)? (STDERR) /Users/me/MyProject/.meteor/local/build/programs/server/packages/modules.js:3562
W20160609-03:06:52.595(2)? (STDERR) import _ from 'lodash';
W20160609-03:06:52.596(2)? (STDERR) ^^^^^^    
W20160609-03:06:52.596(2)? (STDERR) SyntaxError: Unexpected reserved word
W20160609-03:06:52.597(2)? (STDERR)     at /Users/me/MyProject/.meteor/local/build/programs/server/boot.js:286:30
W20160609-03:06:52.597(2)? (STDERR)     at Array.forEach (native)
W20160609-03:06:52.598(2)? (STDERR)     at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.3.3-beta.1.3pq8cx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160609-03:06:52.598(2)? (STDERR)     at /Users/me/MyProject/.meteor/local/build/programs/server/boot.js:133:5
```

How can I properly depend on my package?

**Comment by mhagmajer** [comment]
CC @benjamn who was recently working on Babel integration.

**Comment by laosb** [comment]
It's intended not dealing with compiling node packages for now. You may try to make it an Meteor package and then `api.use('ecmascript');` will do.

**Comment by mhagmajer** [comment]
Ok, so the workaround here would be to include the dependency as git submodule in a Meteor package, isn't it?

**Comment by seeekr** [comment]
Usually transpilation is done *before* publishing a package to npm, no? So then anyone depending on the package doesn't need to worry about it any more. Are you sure that you have good reasons for why you're making your package behave differently?

**Comment by mhagmajer** [comment]
This is a great point @seeekr. However, in this particular case I'd like my
package to be used both on client and server for which Meteor uses slightly
different Babel configuration. That's why I can't just do transpilation
myself and let Meteor depend on transpiled sources.

**Comment by clayne11** [comment]
You could have two different entry points, one for the browser and one for the server that are compiled differently. You're able to do this with a normal npm package.

**Comment by laosb** [comment]
It's better to discuss on Forums for this problem, and by now, the trend is transpile before publish, so this feature won't be considered.
