### ISSUE TITLE
Meteor on windows creating folders in temp which cannot be cleaned because of long file names

### ISSUE THREAD

**Issue by meghadev** [meteor/meteor#7194]
We are using Meteor on windows. Each time we start meteor application, it is dumping some files in the %temp% location. It is not possible to delete these folders without using an external tool as windows prompts that the file name is too long. The memory consumption is so huge, that size of temp has reached almost 35 gbs on one of our systems. I cleaned up Temp on my system using Total Commander 2 weeks back. Today cleaned it again and got rid of almost 4 gb. 
This has an impact on the overall system performance and really slows it down. 

Just because we are using meteor, should mean that we have to compromise on the overall system performance AND require external tools at frequent intervals to get rid of the files and folders which are of no use.

We are using the following packages, incase this information is required for fixing this issue:
meteor-platform
nimble:restivus
meteorhacks:npm
npm-container
iron:router
angularui:angular-ui-bootstrap
linto:jquery-ui
urigo:angular
angular:angular-material
http
autopublish
insecure
arunoda:streams
jchristman:context-menu
jparker:crypto-md5
typ:ldapjs
jparker:crypto-core
jparker:crypto-base64
s2corp:angular-ui-grid
kidovate:bootstrap-slider
meteorhacks:aggregate
chuangbo:cookie
infinitedg:winston
brentjanderson:winston-client
retry
angular:angular-sanitize
browser-policy

**Comment by benjamn** [comment]
What version of Meteor are you using?

**Comment by meghadev** [comment]
We are using 1.1.0.2.

Following is the content of version file of various packages:
 1.1.0.2

**Comment by tcastelli** [comment]
Maybe this is not the ideal solution, but I found a way of deleting this folders by installing a npm package called rimraf.
`npm install -g rimraf`

and then you can directly delete folders from the command line with `rimraf foldername`

**Comment by abernix** [comment]
The latest version of Meteor has a lot of fixes for Windows.  I realize Meteor 1.4.1.1 is a big jump coming from 1.1.0.2, however the number of changes, including for max-path situations like this, is impressive.  While I can't say the Windows experience is flawless, Meteor 1.1 is not actively maintained anymore so I would begin working in that direction to experience the benefits.

1.4.1.1 is the current Meteor version and I'd encourage you to start exploring it.  Change-wise, the 1.3 version jump is probably the most difficult and you'll begin seeing significant Windows changes around 1.3.4.1.

In regard to cleaning up those stubborn long paths, as recommended above, the `rimraf` NPM command is very helpful, but also the [7-zip](http://www.7-zip.org/) (free download) File Explorer.

**Comment by steph643** [comment]
I believe this error still occurs. I've just had to use `rimraf` to remove 1,6 GB of Meteor temp files (see https://github.com/meteor/meteor/issues/8677)
