### ISSUE TITLE
CSS properties baked in DOM

### ISSUE THREAD

**Issue by anvlkv** [meteor/meteor#7195]
When I set CSS property `transform:scale(1.25)` let's say I set it for `.scale-me`  it causes meteor to add attribute style to my element `<button class="scale-me" style="transform: matrix(1.25, 0, 0, 1.25, 0, 0);">Click Me</button>"`. Style is not removed when I remove the class.

This behavior noticed in Chrome 50.0.2661.102 (64-bit) on OS X 10.11.5

**Comment by anvlkv** [comment]
![screen shot 2016-06-09 at 11 08 37](https://cloud.githubusercontent.com/assets/2813794/15924513/b55f3932-2e32-11e6-8d48-92fbd00a1758.png)

**Comment by devonbarrett** [comment]
@anvlkv can you show how you are setting the class, and how/where your CSS declaration is?

**Comment by anvlkv** [comment]
I just created the new project with `meteor create`.
My styles are in `client/main.css`:
`/* CSS declarations go here */
.scale-me{
	transform: scale(1.25);
}`

I also added toggle class to click event in `client/main.js` to check if transformation is removed when I remove the class:
`Template.hello.events({
  'click button'(event, instance) {
    // increment the counter when button is clicked
    instance.counter.set(instance.counter.get() + 1);
    $(event.target).toggleClass('scale-me');
  },
});`

**Comment by abernix** [comment]
Are you only noticing this in Chrome or in other browsers as well?

Also, I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Will you please make a basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here?

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by anvlkv** [comment]
Ooops, while trying to reproduce I figured out it is SEE chrome extensions causing this.
https://chrome.google.com/webstore/detail/see/dkihcccbkkakkbpikjmpnbamkgbjfdcn
Sorry for bothering.
