### ISSUE TITLE
Why 1.3.3.rc4 breaks after update from 1.3.2.4?

### ISSUE THREAD

**Issue by scheung38** [meteor/meteor#7196]
Has anyone seen same issue? How to resolve a previously perfecting working app.

**Comment by benjamn** [comment]
If you want help with whatever is happening, please follow the GitHub issue template provided when you create a new issue. With so little information, there's nothing we can do to help you.

**Comment by scheung38** [comment]
Hi benjamn,

In OSX I had a perfectly working app in 1.3.2.4, then after the meteor update --release 1.3.3-rc4, errors and breakages.. :

Unable to resolve some modules:

"/Users/seb/node_modules/react-datetime/css/react-datetime.css" in
/Users/seb/client/components/MomentInputDemo.jsx (web.browser)

"/Users/seb/node_modules/react-bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"
in /Users/seb/client/components/ParentComponent.jsx (web.browser)

W20160609-14:56:51.926(1)? (STDERR)

W20160609-14:56:51.927(1)? (STDERR) /Users/seb/.meteor/packages/meteor-tool/.1.3.3-rc.4.123jw7s++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160609-14:56:51.928(1)? (STDERR) throw(ex);
W20160609-14:56:51.928(1)? (STDERR) ^
W20160609-14:56:52.008(1)? (STDERR) ReferenceError: FutureTasks is not defined
W20160609-14:56:52.009(1)? (STDERR) at meteorInstall.lib.collections.js (lib/collections.js:57:1)
W20160609-14:56:52.010(1)? (STDERR) at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160609-14:56:52.010(1)? (STDERR) at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160609-14:56:52.011(1)? (STDERR) at /Users/seb/.meteor/local/build/programs/server/app/app.js:918:1
W20160609-14:56:52.011(1)? (STDERR) at /Users/seb/.meteor/local/build/programs/server/boot.js:291:10
W20160609-14:56:52.011(1)? (STDERR) at Array.forEach (native)
W20160609-14:56:52.015(1)? (STDERR) at Function..each..forEach (/Users/seb/.meteor/packages/meteor-tool/.1.3.3-rc.4.123jw7s++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160609-14:56:52.015(1)? (STDERR) at /Users/seb/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8

Tried meteor reset

But still error as above

**Comment by macrozone** [comment]
@scheung38 do you use absolute paths in imports ? like "import from /...." ? 

Maybe related to https://github.com/meteor/meteor/issues/7225
