### ISSUE TITLE
Installing Cordova Plugins timeouts at 0%

### ISSUE THREAD

**Issue by auterium** [meteor/meteor#7200]
Hello,

I'm trying to run my app with the Android emulator but it won't start at all. I found a similar issue here #3459 but it was just closed and never reopened as asked by @glasser. Aparently the original issue was that http://plugins.cordova.io/ was down, but this is not the case when I try to run it for the first time. It just gets stuck like this:

`Installing Cordova plugins                [                            ] 0% 0.0s`

And after a while it just times out and throws the following:

`$ meteor run android
Error while running for mobile platforms: Error running                            
/home/auterium/.meteor/packages/meteor-tool/.1.1.4.pjtsy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh
Error: connect ETIMEDOUT
at errnoException (net.js:905:11)
at Object.afterConnect [as oncomplete] (net.js:896:19)

Fetching plugin "org.apache.cordova.console@0.2.13" via plugin registry`
`

Any help will be much appreciated.

**Comment by karsiyakalilar** [comment]
same problem here, can it be some type of maintenance issue?

**Comment by karsiyakalilar** [comment]
seems like it's a versioning issue, updating meteor to its latest release fixes the issue

**Comment by auterium** [comment]
Although upgrading the project's Meteor version does remove the error, it introduced a world of errors, as my legacy app runs on Meteor 1.1.0.3, so basically this is a no-go for me, at least not for the moment.

**Comment by laosb** [comment]
Since this is fixed in the latest version, closing.

@auterium I'm sorry, but basically the only way to solve this is upgrading, I think.
