### ISSUE TITLE
meteor update --release 1.3.3-rc.5 not available on windows

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7201]
I cannot upgrade any of my projects to version 1.3.3-rc.5 including the sample app.

### Repro
```
meteor create sample
cd sample
meteor update --release 1.3.3-rc.5
```
fails

### Console Output
```
This project uses Meteor 1.3.3-rc.5, which isn't available on Windows. To work with this app
on all supported platforms, use meteor update --release METEOR@1.3.2.4 to pin this app to
the newest Windows-compatible release.
```

**Comment by benjamn** [comment]
Sorry this took a while. The `1.3.3-rc.5` release should work with Windows now. We were having some problems with the build farm. In general, I won't post about a release until it's ready to be downloaded on all platforms.

**Comment by brucejo75** [comment]
still busted on my end.  I will try again in later this afternoon.

**Comment by benjamn** [comment]
Sometimes the installation is left in a bad state if you try to update before `meteor-tool` has been published. Try removing `.\AppData\Local\.meteor\packages\meteor-tool/1.3.3-rc.5` before running the update command?

**Comment by brucejo75** [comment]
I checked that directory does not exist under meteor-tool.
I also tried a `meteor reset` in the sample directory.

I am still getting the error.

**Comment by benjamn** [comment]
I don't know if `1.3.3-rc.5` will end up working on your machine, but you can now do `meteor update --release 1.3.3`. Rest assured I have finished publishing `meteor-tool@1.3.3` on Windows this time!

**Comment by brucejo75** [comment]
Installing 1.3.3 now.  Looks normal.  Interesting side effect of installing prior to version out there.
