### ISSUE TITLE
jQuery Package Out of Date

### ISSUE THREAD

**Issue by jlukic** [meteor/meteor#7202]
I was unable to find a separate GitHub repo for MDG's jQuery package so I thought it would be appropriate to post here. Forgive me if this is the wrong location.

jQuery 3.0 was released today however MDG's [jQuery atmosphere package](https://atmospherejs.com/meteor/jquery#jquery) still reflects the `1.x.x` release cycle

**Comment by reel** [comment]
Actually, as per [this stub](https://github.com/meteor/meteor/blob/devel/packages/jquery/main.js#L4), meteor jquery package will try to import the npm version first and fallback to 1.11.2

**Comment by laosb** [comment]
If you `meteor npm install`ed your own version of jQuery, it should use the npm one automatically. This is not a real issue and MDG is planning to remove the dependency on jQuery on client. Closing.

**Comment by msj121** [comment]
Sadly I think there is a lack of documentation on this from Meteor, not to mention people having conflicting Jquery issues... Would be nice if they just updated jquery...

**Comment by abernix** [comment]
@msj121 Agree.

Meteor will prefer the `npm` version ` jquery` that you have installed, IF you have it installed, which you can do by running the following in the project root:

    meteor npm install jquery --save

Assuming that there are some obstacles to updating the [`jquery` atmosphere package](https://atmospherejs.com/meteor/jquery) (I'm not sure what they are) and focusing just on the documentation – where do you think the best place to document this would be?   The first things that come to mind for me are the previously linked page and [this (similar) page](https://docs.meteor.com/packages/jquery.html).

Is there anywhere else you think it should be?

**Comment by msj121** [comment]
@abernix That is a good question, I think that the page you had chosen would have been great. I definitely hit it on google when trying to solve the update issue.

I will try your fix when my build is a little more stable, sadly I had found a lot of talk about jquery node-stubs that I didn't quite understand.
