### ISSUE TITLE
Use meteor client libs without the full meteor build process

### ISSUE THREAD

**Issue by ShayMatasaro** [meteor/meteor#7204]
Hi,

I would like to use the meteor client packages(ddp,accounts,etc..) from within my existing JS project , without incorporating the full meteor build process.

Apollo project  is already moving towards  a standalone project that can run in any JS app , it would be great if the existing client will also provide this feature.

An official NPM package with the core client feature set would be great, or instructions on how to generate such a package.

Cheers,
Shay

**Comment by laosb** [comment]
Hi,

It's true that MDG is trying to make every part of Meteor useful for general JS apps, but it's a long-term plan which can't be carried out in few days. 

For now, you can try some 3rd-party tools to get the client bundle, e.g. [this one](https://www.npmjs.com/package/meteor-build-client). Also I found something looks exactly you wanted on npm: [this one](https://www.npmjs.com/package/meteor-client-side-official). But it's UNOFFICIAL and you may use it at your own risk.

Another possible solution is use the [Asteroid](https://www.npmjs.com/package/asteroid), which is commonly used in your case. But again, unofficial.

**Comment by ShayMatasaro** [comment]
@laosb thanks!
Yes this is not an easy task , which is why its more an RFE then a bug
One thing that would be a great help is to have even a set of manual  steps that I can perform for each new version, since of of the above options are behind the latest meteor GA

**Comment by laosb** [comment]
That's not something I'm familiar with, and I suggest your posting this to Meteor Forums. This is not a specific issue so I'll just close this.

**Comment by ShayMatasaro** [comment]
RFE = Feature request
Please dont close this issue

**Comment by laosb** [comment]
This is something on agenda, and as this is not very specific, so I closed this. If you have something detailed abou how can we do this, please do an another issue.
