### ISSUE TITLE
Email.send causes crash on ECONNRESET

### ISSUE THREAD

**Issue by llama** [meteor/meteor#7209]
Docs for email package state: "Throws an Error on failure to contact mail server or if mail server returns an error."

I believe this should include ECONNRESET. Instead, ECONNRESET causes the app to crash with a traceback like this:

```
events.js:72 
        throw er; // Unhandled 'error' event 
              ^ 
Error: write ECONNRESET 
    at errnoException (net.js:905:11) 
    at Object.afterWrite (net.js:721:19) 
```

This asynch error should be caught within the email package and thrown from the call to `Email.send`.

https://stackoverflow.com/questions/4088222/how-to-handle-econnreset-connection-reset-by-peer

**Comment by llama** [comment]
Related: https://github.com/nodemailer/nodemailer/issues/203

**Comment by abernix** [comment]
Is this something you can reliably reproduce or is this  just something you have observed happening occasionally?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by jbo023** [comment]
we do have the same problem, 
this happens if we want to send an Email with Email.send to an Exchange server, with incorrect Autorisation. 
The try/catch around the Email.send catches the "Not authorized error" but the server crashes afterwards. 

This only happens under windows with meteor 1.4.1.1
