### ISSUE TITLE
Clarify that OS X 10.9.4 is required for iOS development

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7210]
I just went down the rabbit hole of purchasing a 10.7 compatible mac (I got a good price) and building it up for meteor based on the info on the [meteor.com](https://www.meteor.com/install) page:

> Meteor supports OS X, Windows, and Linux, and is simple to install. The command line installer supports **Mac OS X 10.7 (Lion)** and above...

I found out that if you want to target the IOS platform, Meteor's minimum OSX version is 10.9.4 because of a dependency on [Xcode 6](https://developer.apple.com/library/tvos/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_6_0.html) or later.  Xcode 6 requires at least 10.9.4:

> Xcode 6 requires a Mac running OS X version 10.9.4 or later or 10.10. It includes SDKs for OS X version 10.9 and 10.10, and iOS 8.

Recommend that you change the minimum OSX version to be 10.9.4.  You could add verbiage that says only ios platforms have this constraint, but your overall supported version should be able to target all platforms.

Hopefully, it could save someone a week or 2 of time...

**Comment by laosb** [comment]
Yeah. As Meteor have a lot of dependencies, it's hard to say which version is compatible. We should make it clear that some functions work on Lion but not all.

Node.js is dropping legacy versions of OS X (macOS) too, so it should be updated as Meteor 1.4 will ship with Node 4 and 1.5 with 6.

**Comment by abernix** [comment]
OS X 10.7 _probably_ works fine with Meteor for just web app development (though I have no access to such a system to test anymore), however if you're trying to do iOS mobile development then yes, you would be subjected to Apple's own requirements.  I don't think this means that meteor.com is wrong though.

Assuming that webapp (and possibly Android too) still works on 10.7, then that statement is still accurate and I'm not sure updating this is relevant.

An additional disclaimer could be added indicating requirements for iOS development though!

**Comment by abernix** [comment]
In reference to Node though: Best I can tell, Node is still supporting 10.7 in v6 (as of right now) per this commit https://github.com/nodejs/node/commit/204f3a8a0b4625f2b13a2104c2f2430329dee7fa and this issue https://github.com/nodejs/node/issues/5731.  Did you find something contrary @laosb?

**Comment by brucejo75** [comment]
FYI: I have been using the 10.7 system to host my server and it seems to work fine.

Yes, a disclaimer about IOS development would have been very helpful to me.  In my case, I ended up purchasing an iMac that was only 10.7 capable thinking it was enough.  Then had to purchase a macbook that is capable of running El Capitan. I could have skipped the first purchase.

Thanks!

**Comment by skirunman** [comment]
@abernix Can this be closed as this issue is most likely handled in Meteor Guide anyway https://guide.meteor.com/mobile.html#installing-prerequisites-ios

**Comment by brucejo75** [comment]
Hey guys the reference is still there in the home page
>The command line installer supports Mac OS X 10.7 (Lion) and above

This may be true of the command installer.  But for building IOS apps you need at least 10.9.4.

The guide is ambiguous.  Just trying to save someone else the pain.

I recommend the minimum version of  Mac should be linked to your minimum version of Xcode support for Cordova.

For Meteor v1.5 you have under Cordova:
>iOS apps now require iOS 8 or higher, and building for iOS requires Xcode 7.2 to be installed.

Which implies [this](https://developer.apple.com/library/content/documentation/Xcode/Conceptual/RN-Xcode-Archive/Chapters/xc7_release_notes.html):
>Xcode 7.3.1 requires a Mac running OS X 10.11 or later

Seriously, give up on 10.7.

**Comment by abernix** [comment]
> Hey guys the reference is still there in the home page

It also says on the homepage, at the end of that sentence: iOS development requires the latest Xcode.

That's pretty straightforward, and I believe I actually made that change as a result of your original opening of this issue (Meteor.com stuff is tracked elsewhere).

> Seriously, give up on 10.7.

While 10.7 is certainly less relevant than it once was, please don't use Cordova, a framework which is less and less relevant than it once was, as your driving motivation behind pushing this agenda.  Even the just released Node.js 8 is still supporting Mac OS X 10.7 [on it's active branch](https://github.com/nodejs/node/blob/v8.x/common.gypi#L368 and therefore Meteor 1.6 will also likely support it.  Our Meteor Mac build farm still has 10.7 machines to test releases!
