### ISSUE TITLE
Meteor website: navigation is not rendering properly in FireFox

### ISSUE THREAD

**Issue by GreatDanton** [meteor/meteor#7212]
Navigation on meteor website (www.meteor.com) is not rendering properly in FireFox 47 (see picture):

![meteorwebsite](https://cloud.githubusercontent.com/assets/11252004/16045629/90fe1232-3249-11e6-8e99-d8712b214291.png)

As you can see navigation menus are not visible, without hovering over

Chromium renders correctly:

![meteorchromium](https://cloud.githubusercontent.com/assets/11252004/16045682/d4f819e2-3249-11e6-8311-213536e10cf6.png)

**Comment by laosb** [comment]
Same as #7197. Thank you!
