### ISSUE TITLE
Add a onUpdateUser hook to the accounts-base package

### ISSUE THREAD

**Issue by FGM** [meteor/meteor#7213]
## Problem to solve

Since commit 00eda434206aba34e91ccde25019c2b035b3c746 (OAuth login to an existing account now _does_ update the services.PROVIDER), `accounts-server.js` contains mention of a `onUpdateUser` hook remaining to be implemented, in function `updateOrCreateUserFromExternalService()`. Still present in the `release-1.5` branch
## Why this is a problem

It turns out this hook is missing in an accounts package for transparent Drupal authentication I've been developing (https://github.com/FGM/accounts-drupal) : due to this missing hook, when Meteor is notified about a change in the user exported information, the info is properly merged to the database under the `services` key for the user, but the `profile` field cannot be updated.

This appears to have been the reason for the mention about that hook in the first place: 

>  XXX provide an onUpdateUser hook which would let apps update the profile too
## Current workaround

The current workaround is to delete the user and relog them, which causes the profile to be regenerated as it should, but means any work in progress by the user is lost while they are logged out, and all login information for other accounts providers is deleted too.
## Suggested solution

Implement such a hook. If MDG is willing, I could probably submit a PR to do so.

Note: one similar hook was added recently on logout in #6889, so adding its equivalent for updates seems just a consistency measure.

**Comment by FGM** [comment]
Still an issue on release-1.5 HEAD.

**Comment by abernix** [comment]
Thanks for this feature request.  I think this is a reasonable request and this could be a candidate for `pull-requests-encouraged`, however I'll cite the [feature request guidelines](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) for the sake of completeness and because there are a lot of other feature requests:

> You'll have the best chance of getting a change into core if you can build consensus in the community for it. Start by creating a well specified feature request as a Github issue.

> Help drive discussion and advocate for your feature on the Github ticket (and perhaps the forums). The higher the demand for the feature and the greater the clarity of it's specification will determine the likelihood of a core contributor prioritizing your feature by flagging it with the pull-requests-encouraged label.

Do you mind writing out a bit of a proposal here for exactly what you had in mind or how you planned to implement it?  I don't think this sounds terribly complicated, so if it sounds good you'll be encouraged to make a PR for it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20a%20onUpdateUser%20hook%20to%20the%20accounts-base%20package&body=Migrated%20from:%20meteor/meteor%237213) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
