### ISSUE TITLE
curl: (56) SSLRead() return error -9806

### ISSUE THREAD

**Issue by trung1008** [meteor/meteor#7219]
macos 10.10 yosemite install meteor  error  **curl: (56) SSLRead() return error -9806** can anyone help me :(

**Comment by hwillson** [comment]
See the following [forum post](https://forums.meteor.com/t/curl-56-sslread-return-error-9806-need-help-please/21913?u=hwillson) (TL;DR - look into installing a version of `curl` with SSL support).

**Comment by trung1008** [comment]
oh thanks you for reply. i just have updated my curl and OMZsh. and i fixed it successfully. :)

**Comment by laosb** [comment]
As was fixed by issue reporter and not a meteor issue, closing.
