### ISSUE TITLE
[1.3.3] slow rebuilds when 1.3.3 is downloading in the background

### ISSUE THREAD

**Issue by s-devaney** [meteor/meteor#7223]
Since the `This release is being downloaded in the background. Update your app to
Meteor 1.3.3 by running 'meteor update'.` message has started appearing when running `meteor` my rebuilds have gone from taking 20-30 seconds to over 2 minutes on Windows 10.

Combined with #7222 this is causing me a lot of problems

**Comment by laosb** [comment]
Not sure if there is exact a such problem. Waiting for other similar reports or someone use Windows to test it out.

**Comment by s-devaney** [comment]
I restarted my machine and I've been able to upgrade to 1.3.3, and the problem has gone.
