### ISSUE TITLE
[1.3.3] After reload a page Meteor.user() is undefined

### ISSUE THREAD

**Issue by zhe1ka** [meteor/meteor#7224]
After update Meteor to 1.3.3 I detected that after reload a page Meteor.user() gives undefined

**Comment by zhe1ka** [comment]
setTimeout(() => {
        console.log(Meteor.user());
    }, 1000);

I receive an object of user. 
but if I set the time 100 I receive undefined

**Comment by laosb** [comment]
This is intended, I think. Meteor needs to establish the connection to server and then fetch data from server. It takes time. You can also reproduce this on earlier version of Meteor.

Feel free to correct me and reopen this if I didn't get the point. Closing.

**Comment by zhe1ka** [comment]
I reproduce this on 1.3.2.4 version of Meteor and it works correct. On 1.3.3 it breaks.

I do check before loading the page on the user's authorization and always get undefined

**Comment by laosb** [comment]
Can you provide a repro app according to Contributing.md?

**Comment by zhe1ka** [comment]
Problem was with some packages.
Thanks!)

Close.

**Comment by laosb** [comment]
Glad to hear that!
