### ISSUE TITLE
[android] Provide instructions if no devices are available

### ISSUE THREAD

**Issue by billh93** [meteor/meteor#7228]
So, I have correctly ran the following commands 'meteor install-sdk android', 'meteor add-platform android' and lastly I ran 'meteor run android' but my terminal is currently stuck on the phase of 'Starting app on Android Emulator'. I have everything correctly installed as I didn't get any warning or error messages. What do I need to do to run the android emulator cause it's been like over 10 minutes waiting for it to start.

**Comment by laosb** [comment]
Can you just try `meteor run` as this looks like #7229 ?

**Comment by billh93** [comment]
`meteor run` works fine. I just can't get the android emulator to pop up on my computer. I currently don't have a usb cable to connect my phone to my computer so I can't try it on my device.

**Comment by patrickbolle** [comment]
Same problem here...

**Comment by laosb** [comment]
Could you provide an repro, or say every Meteor project with Android platform added on your Meteor installation can't start?

**Comment by patrickbolle** [comment]
Okay, so i figured it out on my own somehow - 
I ran "android avd" to create my virtual device first (meteor1 in my case).
Then I ran `emulator -avd meteor1` in one terminal, waited for the emulator to start up...
then ran `meteor run android` and my app popped up and worked for me.

Hope it helps someone.

**Comment by abernix** [comment]
As mentioned in the [the Meteor Guide – Android Prereqs](https://guide.meteor.com/mobile.html#installing-prerequisites-android), it is necessary to create a virtual device if you'd like to develop on a virtual device instead of a real device.  Unfortunately, the Android virtual devices are not very fast so it's usually preferable to test on a real device.

Meteor leaves the decision to the developer to decide which device they use/create.

It would be nice if Meteor could detect this automatically and provide a message, so I'll turn this into a feature request. :smile:

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bandroid%5D%20Provide%20instructions%20if%20no%20devices%20are%20available&body=Migrated%20from:%20meteor/meteor%237228) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
