### ISSUE TITLE
refresh issue when using Microsoft Edge

### ISSUE THREAD

**Issue by AndyHan1001** [meteor/meteor#7231]
Every time I open my website (built by meteor framework) by Microsoft Edge and jump between two different pages, then I can notice an obvious refresh after loading the page.

**Comment by laosb** [comment]
Didn't reproduce that on Edge. Can you provide us with detailed information like which version of meteor and router you're using, and how you navigate between pages? But of course, a reproduce repo is prefered for reporting an issue.

**Comment by AndyHan1001** [comment]
meteor version: 1.2.1
router: angular ui-router
navigate method: regular way

**Comment by laosb** [comment]
Can you provide a minimal reproduction?

**Comment by AndyHan1001** [comment]
you can use edge to visit this website: https://www.meteor.com/tutorials/angular/creating-an-app and navigate between different pages. Hopefully you can see the refresh issue.

**Comment by laosb** [comment]
Unable to reproduce. @zhaoyao91 also tried to reproduce but failed. Is that a problem between two specific pages? Please post the two pages there so we can try it.

**Comment by AndyHan1001** [comment]
I do not why, but today this issue has gone.
