### ISSUE TITLE
meteor-tool  Arguments to path.join must be strings

### ISSUE THREAD

**Issue by dusted** [meteor/meteor#7234]
when running meteor command i get the following error, im using meteor 1.3.1

/Users/riccardo/.meteor/packages/meteor-tool/.1.3.1.1y8y6ny++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160616-11:56:40.188(1)? (STDERR)             				throw(ex);
W20160616-11:56:40.188(1)? (STDERR)             				      ^
W20160616-11:56:40.294(1)? (STDERR) TypeError: Arguments to path.join must be strings
W20160616-11:56:40.294(1)? (STDERR)     at path.js:360:15
W20160616-11:56:40.294(1)? (STDERR)     at Array.filter (/Users/riccardo/.meteor/packages/es5-shim/.4.5.9.tx54dl++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:499:48)
W20160616-11:56:40.294(1)? (STDERR)     at Object.exports.join (path.js:358:36)
W20160616-11:56:40.294(1)? (STDERR)     at meteorInstall.builds.ios.project.cordova.lib.copy-www-build-step.js (/Users/riccardo/code/reportPro/mobile/.meteor/local/build/programs/server/app/app.js:1193:19)
W20160616-11:56:40.294(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160616-11:56:40.294(1)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160616-11:56:40.294(1)? (STDERR)     at collections/jobs.ts:14:4
W20160616-11:56:40.294(1)? (STDERR)     at /Users/riccardo/code/reportPro/mobile/.meteor/local/build/programs/server/boot.js:283:10
W20160616-11:56:40.295(1)? (STDERR)     at Array.forEach (native)
W20160616-11:56:40.295(1)? (STDERR)     at Function._.each._.forEach (/Users/riccardo/.meteor/packages/meteor-tool/.1.3.1.1y8y6ny++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)

**Comment by benjamn** [comment]
I'm curious what's on line 1193 of the file `/Users/riccardo/code/reportPro/mobile/.meteor/local/build/programs/server/app/app.js`…

**Comment by abernix** [comment]
@dusted Can you provide the information requested?  Otherwise we will have to close this issue as it lacks the proper information to assist.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
