### ISSUE TITLE
angular 2.0 tutorial impossible on windows 10

### ISSUE THREAD

**Issue by pwnball** [meteor/meteor#7236]
I just started a new project and wanted to give angular2 a swing with meteor. Unfortunately my enthusiasm was swiftly met with disappointment when I learned that even the first angular 2 step in the tutorial stopped me in my tracks.
https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

The command : 
`meteor npm install --save angular2-meteor @angular/platform-browser-dynamic`
gives back this result:

> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Users\\Daan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\Daan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\n
> pm\\bin\\npm-cli.js" "install" "--save" "angular2-meteor" "@angular/platform-browser-dynamic"
> npm ERR! node v0.10.45
> npm ERR! npm  v2.15.1
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package @angular/core@2.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.2 wants @angular/core@2.0.0-rc.2
> 

I am using windows 10 with meteor 1.3.2.4. I would use 1.3.3 but that version does not seem to work with windows 7 and 10 in its current state.

Thanks! :)

**Comment by benjamn** [comment]
That sounds like an issue best filed over here: https://github.com/Urigo/angular-meteor/issues/new

**Comment by pwnball** [comment]
Thanks for pointing that out Benjamn, I've create the issue there :)

**Comment by laosb** [comment]
Close this as was crossposted on angular-meteor.
