### ISSUE TITLE
feature request after user created hook for Accounts package

### ISSUE THREAD

**Issue by dohomi** [meteor/meteor#7238]
This is a feature request for the `Accounts` package. As you have the `Accounts.onLogin` hook after successful logging in process of a user, it would be great if you could publish a hook after successful created user:

```
// runs on server only:
Accounts.afterCreateUser(function(data){
console.log(data) // -> {type:facebook, allowed:true,user:{ (...)}}
})
```

This would be helpful for many use cases. Thanks!

**Comment by hwillson** [comment]
Duplicate of #7741, which is a bit more recent and has more discussion, so I'll close this one. Thanks!
