### ISSUE TITLE
[1.3.x] [cordova/android] revert to last good known version always reverts to initial bundle

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#7241]
There should be `else` I guess:
https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/android/WebAppLocalServer.java#L324

`iOS` version to compare:
https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/ios/WebAppLocalServer.swift#L297

Also it seems that no test case covers this, however I was not able to run the tests at all, some quick note about how to run them would be useful https://github.com/meteor/cordova-plugin-meteor-webapp/issues/8

If you need repro, let me know.

**Comment by laosb** [comment]
Ah, this is an inconsistent between docs and code (or between platforms). So the best fix might be fixing that `.java`, not fixing both `.swift` and `.md` then. Hope someone can look into it.

**Comment by wojtkowiak** [comment]
Well there should be just `else` imho. There is nothing afaik that could prevent us on android from falling to last known good version.
I can make a fix for that and add some test cases but I need some help on how to run the tests in the cordova plugin.

**Comment by wilau2** [comment]
Is there any updates on this issue ? @wojtkowiak

**Comment by wojtkowiak** [comment]
@wilau2 I would be happy to fix but I do not have time to struggle (https://github.com/meteor/cordova-plugin-meteor-webapp/issues/8) with running the tests. If somebody - maybe @martijnwalraven could give me hints on how to run them - then I can do a PR.

**Comment by wilau2** [comment]
@wojtkowiak We made the change locally in our project and push a new version of our app on the  playstore hot code push now seems to work on android on the newest version of the app.

This is an important issue that should not be taken lightly for application in production. 
Hot code push is a larde advantage with meteor and you are loosing it if the code keeps reverting to the first version of the code pushed on the app/play store.

**Comment by jackkav** [comment]
Also made the change locally can also confirm, appears to fix the revert to initial on android.

**Comment by jackkav** [comment]
Submitted a PR with the change, seems like something which is easy to reason about considering the comments and the logic in the swift code. Should be a really easy merge decision. https://github.com/meteor/cordova-plugin-meteor-webapp/pull/14

**Comment by wojtkowiak** [comment]
Closing, since this was fixed here https://github.com/meteor/cordova-plugin-meteor-webapp/pull/14

**Comment by kakadais** [comment]
This happnes on my METEOR@1.10.2 App. 
Do I miss something ?

**Comment by filipenevola** [comment]
Please open a new issue if that is the case.
