### ISSUE TITLE
Error code 1 on build after adding crosswalk

### ISSUE THREAD

**Issue by lelolenda** [meteor/meteor#7242]
Error: Error code 1 for command

![capturar](https://cloud.githubusercontent.com/assets/7979063/16150931/11bab598-3492-11e6-8fb7-ae0a44a00308.PNG)

**Comment by abernix** [comment]
There should be no need to use the `cordova` command directly if you're using Meteor, but aside from that there is nothing to work with in this issue and the problem you're referring to is too vague to accurately provide help – I can't even tell if you're actually using Meteor.

Are you using Meteor?  If so, what version of Meteor are you experiencing this on?  Can you create a basic reproduction repo and upload it to GitHub?  Why are you using `cordova build android` directly?

Closing as too vague but will reopen if you can provide information per the [guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).
