### ISSUE TITLE
[1.3.3.1 Windows] Error: UNKNOWN, unknown error

### ISSUE THREAD

**Issue by zayaisshawn** [meteor/meteor#7243]
Sorry If this issue is redundant but I can't find solution/workaround on other threads. And the error looks different. On meteor command I get following error. Meteor version 1.3.3. I can't update to 1.3.3.1 rc too.

> C:\Users\me\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
>       throw error;
>             ^
> Error: UNKNOWN, unknown error 'C:\Users\me\AppData\Local\.meteor\packages\ecmascript-runtime\0.2.11\isopack.json'
>     at Object.fs.statSync (fs.js:696:18)
>     at Object.wrapper [as stat] (C:\tools\fs\files.js:1373:35)
>     at Object.files.statOrNull (C:\tools\fs\files.js:263:18)
>     at Object.files.exists.files.existsSync (C:\tools\fs\files.js:1438:19)
>     at Function.readMetadataFromDirectory (C:\tools\isobuild\isopack.js:285:13)
>     at [object Object]._alreadyDownloaded (C:\tools\packaging\tropohouse.js:341:19)
>     at [object Object]._makeDownloader (C:\tools\packaging\tropohouse.js:412:33)
>     at C:\tools\packaging\tropohouse.js:560:29
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\packaging\tropohouse.js:557:20
>     at C:\tools\packaging\package-map.js:57:7
>     at Function._.each._.forEach (C:\Users\zayai\AppData\Local\.meteor\packages\meteor-tool\1.3.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
>     at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
>     at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:553:16)
>     at C:\tools\project-context.js:738:25
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\project-context.js:737:20
>     at C:\tools\packaging\catalog\catalog.js:100:5
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
>     at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:736:13)
>     at C:\tools\project-context.js:281:9
>     at C:\tools\utils\buildmessage.js:359:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at ProjectContext._completeStagesThrough (C:\tools\project-context.js:271:18)
>     at C:\tools\project-context.js:263:12
>     at Function.run (C:\tools\tool-env\profile.js:489:12)
>     at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:262:13)
>     at C:\tools\cli\commands-packages.js:1695:22
>     at C:\tools\utils\buildmessage.js:271:13
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.main.captureAndExit (C:\tools\cli\main.js:271:29)
>     at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packages.js:1676:8)
>     at C:\tools\cli\main.js:1402:23

I can't even downgrade to 1.3.2 as it's downloading meteor tools 1.3.2 forever. So I can't use meteor at all. Any workaround guys?

**Comment by vicktor3** [comment]
I am experiencing the exact same build fail on Windows 10. Is this possibly related to the space in my user name?

**Comment by laosb** [comment]
@vicktor3 : @zayaisshawn 's path shows he doesn't have a space in username, so this should be not related. 

Try to upgrade using [this solution](https://github.com/meteor/meteor/issues/7221#issuecomment-226883843) may fix the upgrading process.

**Comment by zayaisshawn** [comment]
@laosb sorry followed that workaround still getting errors.

**Comment by benjamn** [comment]
@zayaisshawn does it help if you remove the `C:\Users\me\AppData\Local\.meteor\packages\ecmascript-runtime\` directory and re-run meteor? That should force meteor to re-download the `ecmascript-runtime` package from Atmosphere…

**Comment by zayaisshawn** [comment]
Thanks @benjamn for suggestion, but doesn't work. I remove ecmascript-runtime package and then ren-run meteor, gives me error. I also remove ecmascript package which still gives me error. After that I uninstalled meteor and installed it again. Now starting meteor project stuck at Downloading meteor-tool@1.3.2_4...  for more than 3 hours. Is it possible something wrong with server/cdn?

**Comment by benjamn** [comment]
Does the `C:\Users\me\AppData\Local\.meteor\packages\ecmascript-runtime\0.2.11\isopack.json` file exist? If so, what do its contents look like?

**Comment by zayaisshawn** [comment]
Sorry about late reply. With new install of meteor I can run/ update apps to 1.3.4-rc.0. The isopack.json looks like this:
```
{
  "isopack-2": {
    "name": "ecmascript-runtime",
    "summary": "Polyfills for new ECMAScript 2015 APIs like Map and Set",
    "version": "0.2.11",
    "isTest": false,
    "builds": [
      {
        "kind": "main",
        "arch": "os",
        "path": "os.json"
      },
      {
        "kind": "main",
        "arch": "web.browser",
        "path": "web.browser.json"
      },
      {
        "kind": "main",
        "arch": "web.cordova",
        "path": "web.cordova.json"
      }
    ],
    "plugins": []
  },
  "isopack-1": {
    "name": "ecmascript-runtime",
    "summary": "Polyfills for new ECMAScript 2015 APIs like Map and Set",
    "version": "0.2.11",
    "isTest": false,
    "builds": [
      {
        "kind": "main",
        "arch": "os",
        "path": "os-legacy.json"
      },
      {
        "kind": "main",
        "arch": "web.browser",
        "path": "web.browser-legacy.json"
      },
      {
        "kind": "main",
        "arch": "web.cordova",
        "path": "web.cordova-legacy.json"
      }
    ],
    "plugins": []
  }
}
```
Thank you.

**Comment by benjamn** [comment]
I also added [this commit](https://github.com/meteor/meteor/commit/7ea260dac2cf688193efd540d643472a0cd74d5a) to the 1.3.4 release. I'm not entirely sure it's a good idea to ignore errors like these, but I believe would have prevented your problem.

**Comment by benjamn** [comment]
Closing now, but please reopen if this happens again.

**Comment by DrkCoater** [comment]
Hi, I recently upgrade meteor to 1.3.4, my mac works fine, on my windows 10, I have this error:

C:\Users\Jeremy Lu\AppData\Local\.meteor\packages\meteor-tool\1.3.4_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: UNKNOWN, lstat 'C:\Workspace\bc\messenger\.meteor\dev_bundle'

I'm running everything latest.

**Comment by benjamn** [comment]
@DrkCoater try deleting `.meteor/dev_bundle`, if it exists?

**Comment by DrkCoater** [comment]
Thanks for your very fast response! @benjamn your solution worked indeed, I guess it's an upgrade issue then..

**Comment by joaobarcia** [comment]
Was also receiving this error. Not sure why it started hapenning, since I havent upgraded in quite a while. @benjamn 's workaround worked, but it should still be fixed as a bug
