### ISSUE TITLE
Embed app breaks on Safari

### ISSUE THREAD

**Issue by sahanDissanayake** [meteor/meteor#7246]
Hi Guys,

I'm running the latest Meteor version. This is my scenario. I have an Meteor App. think of Disqus, So I embed a link 'http://local.dev:3000' to a webpage in 'http://localhost:8000'

The emebed works and function as expected on every other browser. But On safari I get this error. I'm sure it's a Meteor Issue because when I try to embed any other website from the internet it works alright on Safari. The website shows up ( if not blocked from the website provider ) without any error messages

I'm happy to provide any information you may need

<img width="738" alt="screen shot 2016-06-18 at 11 50 51 am" src="https://cloud.githubusercontent.com/assets/5580680/16167618/6aff1aa4-354b-11e6-8b13-4f0f8d7f8308.png">

Tracking this here
http://stackoverflow.com/questions/37892500/only-safari-iframe-content-load-error

**Comment by sahanDissanayake** [comment]
So I was checking out this r jsfiddle.net/e9exn2pd/3 ( Safari ONLY ) 

This app is Meteor V 1.2 and the login works great and the login tokens are saved on the local storage. 

But with my app on V1.3.3.1 when I try to login it does not persist the login tokens to the localstorage of the parent window.

So crazy times.. I hope someone from MDG will assess this.

**Comment by sahanDissanayake** [comment]
So it seems http://stackoverflow.com/questions/31351937/safari-localstorage-not-persisted-between-sessions

Safari does not let iframes play well with the browser. 😢

**Comment by laosb** [comment]
Hi, thanks for your pointing out the different browser behavior in Safari!

However, this should be on Forums instead of issues, as this is not a specific feature or bug we can do something for. Closing and thank you for your efforts again!
