### ISSUE TITLE
how to set a var to ReactiveVar in Meteor.call

### ISSUE THREAD

**Issue by YY030913** [meteor/meteor#7248]
i set a var after meteor.call to a reactiveval , but the client brow get :
`Exception in delivering result of invoking 'getVar': TypeError: Cannot read property 'var' of null`
my meteor.call in onRendered to init the data
```
Meteor.call("getVar", FlowRouter.current().params.slug, (error, result)->
			Template.instance().var.set(result);
	);
```

**Comment by YY030913** [comment]
I use self get the reactive var but i don't konw why ?
anyone can help me?

Template.debate.onRendered ->
	self = this
	Meteor.subscribe("debate", FlowRouter.current().params.slug);
	Template.instance().debate.set({result: true});
	Meteor.call("getDebate", FlowRouter.current().params.slug, (error, result)->
		if error?
			toastr.error t(error.message)
		else 
			console.log result
			self.debate.set(result);
	);

**Comment by laosb** [comment]
Posting this to Forums for discussion is a better way than posting to issues. Thank you!
