### ISSUE TITLE
Cordova build failure on Windows leaving port used.

### ISSUE THREAD

**Issue by fangjj** [meteor/meteor#7249]
On Windows, `meteor run android -p 3001`，but cordova build failed，making the port 3001 not closed! so, i just ran android -p 3002, the same problem, i can't use the port 3002.

**Version:** meteor 1.3.3.1 on windows 7 x64

 `meteor add wuyuedefeng:sen-camera-album`

others told me that i should kill `node`, but i don't know what cmd can killall node on Windows

![port](https://cloud.githubusercontent.com/assets/15318800/16170761/69ca12ac-3590-11e6-989c-8161299cd243.png)

the pic above show the port on Windows, i can't find the PID for 3001,3003, so i can't kill by PID..
wish someone can help me. 

I'm a Chinese, not so good at English, sorry!

**Comment by laosb** [comment]
So the actual meteor problem is that Cordova build failure leads to a dead port usage. I'm not quite familiar with Windows so I don't know how to kill all node processes on Windows either. You may just kill all nodes one by one in the TaskMgr, it should works.

Again, the actual problem happening there is why Meteor left some process running after an exit.

**Comment by fangjj** [comment]
yeah, thank you make me got the reason. but i can't get the process PID, so can't kill it.

**Comment by laosb** [comment]
Could you provide some info about the cordova failure? @fangjj

**Comment by fangjj** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\jim>cd meteor

C:\Users\jim\meteor>cd mypic

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3001 -p 3001
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Started your app.

=> App running at: http://localhost:3001/
   Type Control-C twice to stop.

=> Errors executing Cordova commands:

   While running Cordova app for platform Android with options --device:
   Error: Command failed: C:\Users\jim\meteor\mypic\.meteor\local\cordova-build\platforms\android\cordova\run --device --device
   FAILURE: Build failed with an exception.

   * What went wrong:
   Received invalid response from the daemon: 'Build{id=17f4683c-8a21-4efc-a342-c9931e715dc5.1, currentDir=C:\Users\jim\meteor\mypic\.meteor\local\cordova-build}' is a result of a type we don't
   have a strategy to handle.Earlier, 'Build{id=17f4683c-8a21-4efc-a342-c9931e715dc5.1, currentDir=C:\Users\jim\meteor\mypic\.meteor\local\cordova-build}' request was sent to the daemon.

   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   at ChildProcess.exitCallback (C:\tools\utils\processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

C:\Users\jim\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\isopackets\cordova-support\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
ExitWithCode:1
##hit error, but not show every time
- so, run again on the port 3001

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3001 -p 3001
Can't listen on port 3001. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3001, you can
specify an alternative port with --port <port>.

##the port 3001 in use, so i have run agin on the port 3002, and work well.

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3002 -p 3002
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Started your app.

=> App running at: http://localhost:3002/
   Type Control-C twice to stop.

=> Started app on Android Device.
I20160619-07:42:59.554(8)?                   -
I20160619-07:42:59.944(8)?                   \
I20160619-07:42:59.944(8)? I/chromium( 3577): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
I20160619-07:42:59.944(8)?
I20160619-07:42:59.944(8)? E/chromium( 3577): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
I20160619-07:42:59.944(8)?
I20160619-07:42:59.944(8)? E/chromium( 3577): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersisten
tNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I20160619-07:42:59.944(8)?
I20160619-07:42:59.944(8)? E/chromium( 3577): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
I20160619-07:42:59.944(8)?
I20160619-07:42:59.944(8)? I/chromium( 3577): [INFO:xwalk_extension_renderer_controller.cc(43)] EXTENSION PROCESS DISABLED.
I20160619-07:42:59.944(8)?
I20160619-07:42:59.944(8)? I/MeteorWebApp( 3577): Serving asset bundle with version: 5333dd63e7a5c13f40e65654566d2d054638868c
I20160619-07:42:59.944(8)?
I20160619-07:43:05.217(8) (android:http://localhost:12608/cordova.js:1185) deviceready has not fired after 5 seconds.
I20160619-07:43:05.217(8)?
I20160619-07:43:05.217(8) (android:http://localhost:12608/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20160619-07:43:05.232(8)?
终止批处理操作吗(Y/N)?
^C
##i type control-c twice to stop, and run agin on the port 3002, but the port 3002 is in use

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3002 -p 3002
Can't listen on port 3002. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3002, you can
specify an alternative port with --port <port>.

C:\Users\jim\meteor\mypic>netstat -ano |findstr 3001
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING       2104
  TCP    192.168.199.225:3001   192.168.199.118:48548  CLOSE_WAIT      2104
  TCP    192.168.199.225:3001   192.168.199.118:48549  CLOSE_WAIT      2104
  TCP    192.168.199.225:3001   192.168.199.118:48552  CLOSE_WAIT      2104
  TCP    192.168.199.225:3001   192.168.199.118:48553  CLOSE_WAIT      2104

C:\Users\jim\meteor\mypic>netstat -ano |findstr 3002
  TCP    0.0.0.0:3002           0.0.0.0:0              LISTENING       4804
  TCP    192.168.199.225:3002   192.168.199.118:43974  CLOSE_WAIT      4804
  TCP    192.168.199.225:3002   192.168.199.118:43976  CLOSE_WAIT      4804
  TCP    192.168.199.225:3002   192.168.199.118:43977  CLOSE_WAIT      4804
  TCP    192.168.199.225:3002   192.168.199.118:43978  CLOSE_WAIT      4804
  TCP    192.168.199.225:3002   192.168.199.118:43979  CLOSE_WAIT      4804
  TCP    192.168.199.225:3002   192.168.199.118:43980  CLOSE_WAIT      4804

C:\Users\jim\meteor\mypic>tasklist |findstr 2104

C:\Users\jim\meteor\mypic>tasklist |findstr 4804

C:\Users\jim\meteor\mypic>
##i can find the port 3001 and 3002, but can't find the PID belongs the port.
##so, i run again on the port 3003, work well, an so on....

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3003 -p 3003
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Started your app.

=> App running at: http://localhost:3003/
   Type Control-C twice to stop.

=> Started app on Android Device.
I20160619-07:48:56.636(8)?                   -
I20160619-07:48:56.799(8)?                   \
I20160619-07:48:56.800(8)? I/chromium( 4033): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
I20160619-07:48:56.801(8)?
I20160619-07:48:56.802(8)? E/chromium( 4033): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
I20160619-07:48:56.804(8)?
I20160619-07:48:56.805(8)? E/chromium( 4033): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersisten
tNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I20160619-07:48:56.806(8)?
I20160619-07:48:56.808(8)? E/chromium( 4033): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
I20160619-07:48:56.810(8)?
I20160619-07:48:56.811(8)? I/chromium( 4033): [INFO:xwalk_extension_renderer_controller.cc(43)] EXTENSION PROCESS DISABLED.
I20160619-07:48:56.813(8)?
I20160619-07:48:56.814(8)? I/MeteorWebApp( 4033): Serving asset bundle with version: 5333dd63e7a5c13f40e65654566d2d054638868c
I20160619-07:48:56.815(8)?
I20160619-07:49:02.176(8) (android:http://localhost:12608/cordova.js:1185) deviceready has not fired after 5 seconds.
I20160619-07:49:02.177(8)?
I20160619-07:49:02.179(8) (android:http://localhost:12608/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20160619-07:49:02.180(8)?
I20160619-07:49:04.308(8) (android:http://localhost:12608/packages/modules.js:781) Download the React DevTools for a better development experience: https://fb.me/react-devtools
I20160619-07:49:04.308(8)?
I20160619-07:49:04.358(8)? I/chromium( 4033): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
I20160619-07:49:04.360(8)?
I20160619-07:49:04.364(8)? I/chromium( 4033):
I20160619-07:49:04.366(8)?
I20160619-07:49:04.369(8)? I/chromium( 4033): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
I20160619-07:49:04.371(8)?
I20160619-07:49:04.373(8)? I/chromium( 4033):
I20160619-07:49:04.376(8)?
终止批处理操作吗(Y/N)?
^C

##i type control-c twice to stop, and run agin on the port 3003, work well and so on...
C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3003 -p 3003
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Started your app.

=> App running at: http://localhost:3003/
   Type Control-C twice to stop.

=> Started app on Android Device.
I20160619-07:51:11.538(8)?                   /
I20160619-07:51:11.658(8)?
I20160619-07:51:11.698(8)? I/chromium( 4321): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
I20160619-07:51:11.698(8)?
I20160619-07:51:11.698(8)? E/chromium( 4321): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
I20160619-07:51:11.698(8)?
I20160619-07:51:11.708(8)? E/chromium( 4321): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersisten
tNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I20160619-07:51:11.708(8)?
I20160619-07:51:11.708(8)? E/chromium( 4321): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
I20160619-07:51:11.708(8)?
I20160619-07:51:11.708(8)? I/chromium( 4321): [INFO:xwalk_extension_renderer_controller.cc(43)] EXTENSION PROCESS DISABLED.
I20160619-07:51:11.708(8)?
I20160619-07:51:11.938(8)? I/MeteorWebApp( 4321): Serving asset bundle with version: 5333dd63e7a5c13f40e65654566d2d054638868c
I20160619-07:51:11.938(8)?
I20160619-07:51:17.552(8) (android:http://localhost:12608/cordova.js:1185) deviceready has not fired after 5 seconds.
I20160619-07:51:17.553(8)?
I20160619-07:51:17.556(8) (android:http://localhost:12608/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20160619-07:51:17.558(8)?
I20160619-07:51:20.960(8) (android:http://localhost:12608/packages/modules.js:781) Download the React DevTools for a better development experience: https://fb.me/react-devtools
I20160619-07:51:20.966(8)?
I20160619-07:51:21.034(8)? I/chromium( 4321): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
I20160619-07:51:21.035(8)?
I20160619-07:51:21.035(8)? I/chromium( 4321):
I20160619-07:51:21.037(8)?
I20160619-07:51:21.050(8)? I/chromium( 4321): [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
I20160619-07:51:21.051(8)?
I20160619-07:51:21.051(8)? I/chromium( 4321):
I20160619-07:51:21.053(8)?
终止批处理操作吗(Y/N)?
^C
C:\Users\jim\meteor\mypic>

C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3003 -p 3003
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Started your app.

=> App running at: http://localhost:3003/
   Type Control-C twice to stop.

=> Started app on Android Device.
I20160619-07:54:08.830(8)?                   -
I20160619-07:54:08.937(8)?
I20160619-07:54:08.972(8)? I/chromium( 4871): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
I20160619-07:54:08.974(8)?
I20160619-07:54:08.974(8)? E/chromium( 4871): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
I20160619-07:54:08.976(8)?
I20160619-07:54:08.977(8)? E/chromium( 4871): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersisten
tNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
I20160619-07:54:08.978(8)?
I20160619-07:54:08.980(8)? E/chromium( 4871): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
I20160619-07:54:08.983(8)?
I20160619-07:54:08.984(8)? I/chromium( 4871): [INFO:xwalk_extension_renderer_controller.cc(43)] EXTENSION PROCESS DISABLED.
I20160619-07:54:08.985(8)?
I20160619-07:54:08.986(8)? I/MeteorWebApp( 4871): Serving asset bundle with version: 5333dd63e7a5c13f40e65654566d2d054638868c
I20160619-07:54:08.988(8)?
I20160619-07:54:13.384(8) (android:http://localhost:12608/cordova.js:1185) deviceready has not fired after 5 seconds.
I20160619-07:54:13.385(8)?
I20160619-07:54:13.392(8) (android:http://localhost:12608/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20160619-07:54:13.393(8)?
终止批处理操作吗(Y/N)?
^C
C:\Users\jim\meteor\mypic>

C:\Users\jim\meteor\mypic>

**Comment by fangjj** [comment]
even i don't hit the error, run on the port 3000 and work well, when i type contorl - c twice to stop and run again on the port 3000. just find the port 3000 is in use. i chage it to 3001, work well, and so on...
![Uploading 3000.png…]()
![Uploading 3001.png…]()

**Comment by laosb** [comment]
Well well, this sounds like a bug of Crosswalk integration.

**Comment by fangjj** [comment]
well, if i remove the crooswalk package, it will be ok?

**Comment by laosb** [comment]
You can try but I can't promise.

**Comment by fangjj** [comment]
ok. thank you! but i think crooswalk webview is more powerful than webview.

**Comment by laosb** [comment]
Yes, it's really something we need to fix.

**Comment by laosb** [comment]
It looks like #7242.

**Comment by fangjj** [comment]
C:\Users\jim\meteor\mypic>meteor run android-device --mobile-server 192.168.199.225:3006 -p 3006
[[[[[ C:\Users\jim\meteor\mypic ]]]]]

=> Started proxy.
=> Started MongoDB.
WARNING: Attempting to install plugin cordova-plugin-camera@0.3.2, but it should have a minimum version of 2.1.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network
         configuration allows clients to talk to each other (no client isolation).
=> Errors executing Cordova commands:

   While running Cordova app for platform Android with options --device:
   Error: Command failed: C:\Users\jim\meteor\mypic\.meteor\local\cordova-build\platforms\android\cordova\run --device --device
   { [Error: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe: Command failed with exit code 1 Error output:
   error: cannot parse version string: kg01] code: 1 } 'Error: C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe: Command failed with exit code 1 Error output:\nerror:
   cannot parse version string: kg01\n    at ChildProcess.whenDone
   (C:\\Users\\jim\\meteor\\mypic\\.meteor\\local\\cordova-build\\platforms\\android\\cordova\\node_modules\\cordova-common\\src\\superspawn.js:169:23)\n    at ChildProcess.emit
   (events.js:98:17)\n    at maybeClose (child_process.js:766:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:833:5)'
   at ChildProcess.exitCallback (C:\tools\utils\processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

C:\Users\jim\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\isopackets\cordova-support\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
ExitWithCode:1

**Comment by fangjj** [comment]
i use promise in my project, why build error.

**Comment by laosb** [comment]
@fangjj did you mean that the wrong usage of Promise leads to this error?

**Comment by fangjj** [comment]
i don't think so, because run in browser is ok. just run on android hit the errors sometime.

**Comment by hwillson** [comment]
The recently released Meteor 1.6 introduces many new Windows changes. Please try things out with 1.6 and post back if you're still encountering this issue. Thanks!

**Comment by fangjj** [comment]
@hwillson , Thank you for your reply. But I'm having another problem.[8399](https://github.com/meteor/meteor/issues/8399), No one answered me, can you help me.
