### ISSUE TITLE
Meteor(1.3.3.1) version application crashed while running on windows 10 (32 bit)

### ISSUE THREAD

**Issue by anomepani** [meteor/meteor#7254]
I am using Meteor 1.3.3.1 version in windows 10(32-Bit) architecture. When I am trying to create my first hello world application I am getting error as per below image.

![windows10-meteor issue](https://cloud.githubusercontent.com/assets/2988295/16177423/6a06fc16-364a-11e6-852d-a2053d234096.png)

Let me know how to fix this issue.

**Comment by laosb** [comment]
Hi, this is exactly #7247. Closing this.
