### ISSUE TITLE
1.3.3.1 - Facebook auth type checking error in facebook package 1.2.7

### ISSUE THREAD

**Issue by workflow** [meteor/meteor#7255]
Trying to login using `facebook@1.2.7` (newest version) in Meteor 1.3.3.1 yields the following type check error:

```
facebook_client.js:40 Uncaught TypeError: Cannot read property 'authType' of null
```

Please do let me know if you need more info to reproduce.
I'm attaching a one-line PR that fixes this.

**Comment by workflow** [comment]
#7256

**Comment by zol** [comment]
This looks like a regression caused by 3d3c7edc6d30de8004fa41f135ba9153aa421e95
