### ISSUE TITLE
1.3.3.1 upgrade fails babel syntax ?

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#7259]
***1 Upvote*** => Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
   native: Unexpected token }
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromPackageJson (packages/babel-compiler/babel-compiler.js:181:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:155:1)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:97:1)
   at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:21:1)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:20:1)

**Comment by interfaith** [comment]
to avoid the problem a new project is created and the files copied over.

**Comment by tomasz-nolberczak** [comment]
+1

**Comment by interfaith** [comment]
It is not the 1st time this has happened, a "test upgrade" feature would help avoid this
upgrade "trap".

**Comment by benjamn** [comment]
I'm guessing you have a syntax error in a `.babelrc` or `package.json` file, given that stack trace. When you created the new project, you probably avoided copying the file with the syntax error, and so the error disappeared.

**Comment by interfaith** [comment]
just a meteor npm init for package.json

{
  "name": "audeo",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

On Mon, Jun 20, 2016 at 7:29 AM, Ben Newman <notifications@github.com>
wrote:

> I'm guessing you have a syntax error in a .babelrc or package.json file,
> given that stack trace. When you created the new project, you probably
> avoided copying the file with the syntax error, and so the error
> disappeared.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/meteor/meteor/issues/7259#issuecomment-227158590>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAs5z3Mj1L1x-Jdjo3ByE55f9P6QjuCxks5qNqPhgaJpZM4I5N2R>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by benjamn** [comment]
If you can provide a small reproduction repository, I will take a look at this.

**Comment by interfaith** [comment]
it all works now, thx.. maybe updating all meteor components helped.

**Comment by benjamn** [comment]
@interfaith thanks for letting us know, and please do reopen this issue if you can reproduce the problem reliably
