### ISSUE TITLE
Meteor 1.3.3.x hang on startup

### ISSUE THREAD

**Issue by jwall149** [meteor/meteor#7265]
After upgrade from Meteor 1.3.2.4 to 1.3.3.1, my application fails to startup, it stops on processing ecmascripts and hang at: `Processing files with ecmascript `:

Local package version is up-to-date: underscore@1.0.9
Local package version is up-to-date: url@1.0.10
Local package version is up-to-date: webapp@1.2.9
Local package version is up-to-date: webapp-hashing@1.0.9
Local package version is up-to-date: zodiase:check@0.0.4
Local package version is up-to-date: zodiase:material-design-icons-fonts@2.2.2
Local package version is up-to-date: zodiase:mdl@1.1.3_1
Local package version is up-to-date: zodiase:mdl-assets@1.1.3
Doing HTTP request:  POST                     
https://www.meteor.com/oauth2/authorize?state=012938kjsadhf912j3h12sdjfhsd&response_type=code&client_id=1lkasdf019231doifu&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
   Processing files with ecmascript (for...  /

**Comment by laosb** [comment]
Would you like to try remove `ecmascript` from your `.meteor`, and run again? (This should download `ecmascript` again)

**Comment by jwall149** [comment]
I've just tried, but it doesn't help, still hanging forever.

**Comment by laosb** [comment]
OK, though I'm not sure whether this can address it, would you like to try 1.3.4-rc0?

Anyway, this doesn't look like a npm problem. So would you like to provide a minimal repro?

**Comment by jwall149** [comment]
I tried `1.3.4-rc0` and it's the same. I tried delete addition packages, features out of my application. At some point it works but very slow, and consume large amount of CPU and Memory. 

If I tried to remove everything an only keep 10, 20 files, it works like expected. When the number come up to 100, 150 files, everything is slowing down a lot, it takes 5, 7 minutes to build, and some time it hangs.

I'm not sure that helps,  but I can not find a minimal reproduction.

**Comment by benjamn** [comment]
What operating system are you using?

What's in your app's `.meteor/packages` and `.meteor/versions` files?

**Comment by jwall149** [comment]
I'm using `MacOS X El Capital`, here is the build command that hang:

**Comment by santisiri** [comment]
Facing the same issue here with Mac OS X El Capitan.. 
 `=> Errors prevented startup:  While processing files with ecmascript (for target web.browser):`

**Comment by Mattze96** [comment]
Hi,

i had the same problem with emcascript. There was an additional folder called `android` in my workspace i had to remove.

**Comment by abernix** [comment]
@jwall149 Can you work out a simple reproduction app that you could upload to GitHub and share with us that demonstrates this problem?  Perhaps a copy of your app which has the same packages but most other code removed?  Also, limiting the packages to the bare minimum that cause the problem?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back.
