### ISSUE TITLE
Add retrying to installer

### ISSUE THREAD

**Issue by zol** [meteor/meteor#7266]
Currently, the Meteor install script doesn't retry+resume downloads. Therefore, downloading the Meteor distribution can fail part-way leading to an aborted installation. On a bad network connection where the download continually fails, it's impossible to install Meteor.

We should add the ability for the script to retry and resume downloads. This will partially address the CDN issues reported in #6960

## Suggested implementation
- Refactor curl to save the download to a temporary file created by the `mktemp` command rather than executing `stdout`.
- Using the method outlined [here](https://ilovesymposia.com/2013/04/11/automatically-resume-interrupted-downloads-in-osx-with-curl/), refactor the curl command to resume the download if it fails. You may need to check for multiple exit codes as the post suggests. Alternatively, you could check for a non-0 exit and retry a fixed number of times.

**Comment by tmeasday** [comment]
Done. Have commented on #6960. Closing this, will reopen if it's not successful.

**Comment by tmeasday** [comment]
I should change this file too https://github.com/meteor/meteor/blob/devel/scripts/admin/launch-meteor#L1
