### ISSUE TITLE
1.3.3.1 upgrade resulting in "Uncaught SyntaxError: Unexpected token import"

### ISSUE THREAD

**Issue by Batistleman** [meteor/meteor#7268]
Hi,

I just upgraded to 1.3.3.1 (on mac) an got the following error client side:

    "app.js?hash=5ba5726…:59324 Uncaught SyntaxError: Unexpected token import "

pointing to  /client/compatibility/modules/fullscreen.js: 

    import screenfull from 'screenfull';   

Before 1.3.3.1 I did not have any errors. (unfortunately I don't have a minimal app to reproduce yet)
I've tested 1.3.4-rc.0, but it does not seem to solve the issue.

**Comment by laosb** [comment]
I wonder if you have `ecmascript` installed?

**Comment by Batistleman** [comment]
Yes, I have... from the update logs: 

    ecmascript              upgraded from 0.4.3 to 0.4.5
    ecmascript-runtime      upgraded from 0.2.10 to 0.2.11

Could it have something to do with the 'compatibility' folder?

**Comment by laosb** [comment]
I'm not sure. This might be a different issue. Can you provide a minimal repro?

**Comment by laosb** [comment]
Oh, my fault. After reading your issue carefully, it's a intended behavior. In `compatibility`, these js files won't be compiled, so imports won't work there. You may consider a different folder for files with imports.

**Comment by Batistleman** [comment]
Yes, that was it, thanks!
