### ISSUE TITLE
Slow and frustrating experience when developing with cordova

### ISSUE THREAD

**Issue by nerdmed** [meteor/meteor#7271]
Dear MDG, @martijnwalraven @zol 

since the 1.3 release it's become a real pain to develop for cordova. We really appreciate all the hard work and the great updates on the underlying technique, but when developing it's really not what it used to be.

I will try to explain the journey:

There are many use cases where you want to work on some custom native components for your hybrid web app via Xcode or Android Studio. Ok its now possible to do that by just opening the underlying projects with the tools, which is what happens automatically after running `meteor run ios-device`. Great.

BUT

then there comes the moment you're working on something and the meteor server crashes for whatever reason: wrong file in package, strange import typo etc. Sometimes it just crashes, or maybe i wanted to restart the server manually because of some unknown error 🐹 . Now lets go and start the server again. `meteor run --settings ....` - BUMMER my app is not hot code reloading on iOS anymore. But we know to add the mobile-server flag: `meteor run --settings ... --mobile-server ...` - SECOND BUMMER meteor starts to download all the cordova plugins and build the app from the ground up. Logically it should be fast because nothing at all has changed. Wrong again- it takes at least 3-4 minutes to complete on a high-end Macbook Pro 15". Let's go grab some coffee and wait.

Oh great finished - BUMMER app fails to finish the build because of some strange cordova bug that causes the whole project to mess up on second build (this happens every time on both platforms by the way). And then theres's no way to start the server without having the tool to create the whole cordova project anyway. Repeat frustrating process 10 times a day and by the end of the week you are just about ready to smash up your mac.

Guys this was not a problem before the 1.3 release. We could just build for the web and get hot code reloads on native devices. I am not sure how this fits into your schedule but i assume this to be a very quick fix for someone familiar to the build stack.

**Comment by ephemer** [comment]
Part of this frustration has to do with this well-intentioned commit which unfortunately caused more harm than good:
https://github.com/meteor/meteor/commit/49c9d07be833561a789f57581416638bca4d249d

**Comment by Exilz** [comment]
I can confirm that these changes are making our mobile workflow much slower than before.

I guess another issue has already been opened for this, but an option to serve the hot code push without having to compile the app again when starting meteor would be a nice thing to add.

**Comment by nerdmed** [comment]
@Exilz - any links for the issue?

**Comment by laosb** [comment]
Did a search but not found.

**Comment by Exilz** [comment]
I'm pretty sure I've read this in an issue. Maybe the issue wasn't dedicated to adding this option.
It might be good to open one, or better, to make a PR adding this.

I wonder what @martijnwalraven thinks about this.

**Comment by nerdmed** [comment]
@martijnwalraven thanks 👍

**Comment by martijnwalraven** [comment]
I'm sorry I missed the last comment on https://github.com/meteor/meteor/commit/49c9d07be833561a789f57581416638bca4d249d#commitcomment-17439041. I was under the impression that commit had solved the issue, but it indeed builds the complete Cordova project. The change above should fix this.
