### ISSUE TITLE
External mongo 3.7.2 leads to `driver is incompatible with this server version`

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#7274]
MongoError: driver is incompatible with this server version

MONGO_URL=mongodb://localhost:27017/audeo meteor (3.2.7)

meteor  // is ok

using installed mongod fails ? downgrade mongod ? 1.3.2 was ok 1.3.3.1 fails
simple meteor create is ok

here is the package list
was ok until upgrading to 1.3.3.1

/newaudeo/audeo$ meteor list
accounts-password      1.1.11  Password support for accounts
accounts-ui            1.1.9  Simple templates to add login widgets to an app
blaze-html-templates   1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
bootstrap              1.0.1  Front-end framework from Twitter
check                  1.2.3  Check whether a value matches a pattern
ejson                  1.0.12  Extended and Extensible JSON library
email                  1.0.14  Send email messages
iron:router            1.0.13  Routing specifically designed for Meteor
jquery                 1.11.9  Manipulate the DOM using CSS selectors
logging                1.0.13  Logging facility.
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.9  Adaptor for using MongoDB and Minimongo over DDP
new3rs:twitter         0.0.9  a synchronous wrapper of NPM twitter
random                 1.0.10  Random number generator and utilities
reload                 1.1.9  Reload the page while preserving application state.
session                1.1.6  Session variable
spacebars              1.0.12  Handlebars-like template language for Meteor
standard-minifier-css  1.0.7  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.0.7  Standard javascript minifiers used with Meteor apps by default.
tracker                1.0.14  Dependency tracker to allow reactive callbacks

**Comment by abernix** [comment]
Changes are being made to Meteor to make it support Mongo 3.2.  It's possible something changed in Meteor 1.3.3 to prepare for this, though I'm  not aware of anything.  Prior to Meteor 1.4, Mongo versions over 2.8 are not officially supported.

What happens if you try using the new beta release of Meteor 1.4 which uses Mongo 3.2?:

```
meteor update --release 1.4-beta.2
```

**Comment by interfaith** [comment]
yes that works well.

**Comment by abernix** [comment]
Ok, glad to hear it!  I'm going to close this since everything should work great in Meteor 1.4 and Mongo 3 isn't supported in older Meteor versions.

p.s. `1.4-beta.6` is out now. 😉
