### ISSUE TITLE
meteor build for android

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#7275]
Simple projects produce the android build environment.
However more complex projects do not.

accounts-password      1.1.11  Password support for accounts
accounts-ui            1.1.9  Simple templates to add login widgets to an app
blaze-html-templates   1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
bootstrap              1.0.1  Front-end framework from Twitter
check                  1.2.3  Check whether a value matches a pattern
ejson                  1.0.12  Extended and Extensible JSON library
email                  1.0.14  Send email messages
iron:router            1.0.13  Routing specifically designed for Meteor
jquery                 1.11.9  Manipulate the DOM using CSS selectors
logging                1.0.13  Logging facility.
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.9  Adaptor for using MongoDB and Minimongo over DDP
new3rs:twitter         0.0.9  a synchronous wrapper of NPM twitter
random                 1.0.10  Random number generator and utilities
reload                 1.1.9* Reload the page while preserving application state.
session                1.1.6  Session variable
spacebars              1.0.12  Handlebars-like template language for Meteor
standard-minifier-css  1.0.7  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.0.7  Standard javascript minifiers used with Meteor apps by default.
tracker                1.0.14  Dependency tracker to allow reactive callbacks

**Comment by interfaith** [comment]
build errors maybe a different nodjs/npm needed

Errors prevented bundling:                    
While minifying app code:                     

/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token: operator (>)
at new JS_Parse_Error
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18)
at js_error
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:204:11)
at croak
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:675:9)
at token_error
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:683:9)
at unexpected
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:689:9)
at expr_atom
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1196:9)
at maybe_unary
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1358:19)
at expr_ops
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1393:24)
at maybe_conditional
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1398:20)
at maybe_assign
(/home/mark/.meteor/packages/standard-minifier-js/.1.0.7.1e2bme5++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1422:20)

**Comment by interfaith** [comment]
meteor add ecmascript fixed it.. yet no docs hint it is needed ?

**Comment by nerdmed** [comment]
@interfaith  it should be added by default for a new project.
Did you use any es6 code in your app code?

**Comment by interfaith** [comment]
not knowingly. also  ./gradlew assembleDebug will avoid android studio to deliver a useful debug apk.

**Comment by interfaith** [comment]
so all old projects should be copied over a skeleton new project

**Comment by nerdmed** [comment]
or just add the ecmascript package 👍
as this isn't a real issue with meteor i would suggest to discuss this via the forums on the https://guide.meteor.com/1.3-migration.html part of the guide. It could be mentioned there!

**Comment by interfaith** [comment]
ok.. here using crosswalk the app sets up a window saying the crosswalk service project must be updated for the correct architecture.
