### ISSUE TITLE
After login this.connection inside publish is missing keys, for example this.connection.host is undefined

### ISSUE THREAD

**Issue by claudiutraistaru** [meteor/meteor#7287]
In Meteor 1.3 , even in latest release , when a user is not logged in  with the below code :
```
  Meteor.publish("collection", function () {
        console.log("Publishing Sites " + EJSON.stringify(this.connection));
         ....code to publish
}
```
when the user is not logged in the below object is returned by this.connection:
```
{"id":"P4CxJyz6Lpexcretx","clientAddress":"127.0.0.1","httpHeaders":{"x-forwarded-for":"127.0.0.1","host":"localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36","accept-language":"ro-RO,ro;q=0.8,en-US;q=0.6,en;q=0.4"},"headers":{"x-forwarded-proto":"http","x-forwarded-port":"3000","x-forwarded-for":"127.0.0.1","cookie":"cluster-endpoint::web=c941ad20dc843d199a8832622748bcf0b460ca68","accept-language":"ro-RO,ro;q=0.8,en-US;q=0.6,en;q=0.4","accept-encoding":"gzip, deflate, sdch","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36","upgrade-insecure-requests":"1","cache-control":"max-age=0","connection":"keep-alive","host":"www.myvirtualdomain.com","x-ip-chain":"127.0.0.1,127.0.0.1"},"headerDep":{"_dependentsById":{}}}
```
where in particular interest is : host":"www.myvirtualdomain.com" because the requested url is www.myvirtualdomain.com/url

after a user is logged in , this.connection has less keys:
` {"id":"miBFW92uWE6s8tsB2","clientAddress":"127.0.0.1","httpHeaders":{"x-forwarded-for":"127.0.0.1","x-forwarded-proto":"ws","host":"localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36","accept-language":"ro-RO,ro;q=0.8,en-US;q=0.6,en;q=0.4"}}`
the same request is made on www.myvirtualdomain.com/url , but the only host provided is localhost:3000 which is not the key I need.

In meteor 1.2 the issue was not present , the keys were returned even after the user login, as such , I think this is a bug as the object is too different.

I am using also meteorhacks:cluster , if this is of help.

**Comment by claudiutraistaru** [comment]
Hi, after further testing it seems that the issue dissapears when removing the cluster settings lines :  ```
Cluster.connect("mongodb://localhost/service-discovery");
Cluster.register("web"); 
```
Removing the lines makes the header available as usual.

**Comment by laosb** [comment]
How about cross-posting this to `meteorhacks:cluster`?

**Comment by claudiutraistaru** [comment]
Hi @laosb . Posted it now to meteorhacks:cluster also https://github.com/meteorhacks/cluster/issues/128

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue.
