### ISSUE TITLE
Shared NPM dependencies in apps and packages

### ISSUE THREAD

**Issue by Gywem** [meteor/meteor#7290]
**Using:** Meteor 1.3+

I report you an unexpected behavior or something that you may consider to tackle in the future working. The issue is about what happens on include the same _NPM modules_ in both _Meteor_ applications and packages. Modules are being instantiated several times and some of them require to be singleton instances to work properly. Concretely, that is what happens when using _React_. 

With the inclusion of _React_ and _NPM modules_ in _Meteor_, it expands our possibilities to flesh out our applications requirements. With the possibility to create _Meteor_ packages, we promote the modularity and reusability of our units of logic.
That is what we do in our applications, we take the advantage of _React_ rendering and _NPM modules_ to setup our infrastructure, such us `redux`, `react-redux`, `react-router`, etc; but at the same time we rely on reusability across other _Meteor_ apps we implement by creating our shared _React_ components in a separate Meteor package.

The infrastructure:

```
Meteor App #1
   NPM Package react
   Meteor Package A
      NPM Package react
   Meteor Package B
      NPM Package react
Meteor App #2
   NPM Package react
   Meteor Package A
      NPM Package react
```

When we set up an infrastructure like this, we have several options, either we expose the react dependency from the package level by using `Npm.depends([modules])` or `npm install --save [module]` in both apps and packages. Both options seems that are keeping several instances of _React_, which produces errors, for instance when using _React_ references through the component hierarchy defined from the root app to the package level.

`Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's 'render' method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

What it would be expected is to have a way by which the same _NPM modules_, that are defined in both apps and packages, are shared and ensure no several instances are created when launching the app environment. Wouldn't be?

For understanding better the issue, somebody reported a similar problem, but this time using angular deps. You can check it out [here](http://stackoverflow.com/questions/36910579/using-multiple-packages-in-meteor-1-3-that-include-the-same-npm-package).

**Comment by ramijarrar** [comment]
You can achieve this with the ```tmeasday:check-npm-versions``` package as documented in the Meteor guide [here](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies).

**Comment by Gywem** [comment]
Thanks for the answer.

That is what I tried first. But as I understood, this only ensures that we will use a concrete version of a NPM module in our app level.

To avoid multiple React instances, we would require to not include the react NPM dependency in the package, and only doing it at the app level. I tried on this, but this implies the test server for the package would not include the react dependency and therefore tests would not work.

**Comment by Ben305** [comment]
[@Gywem Have you tried to include react in `api.onTest` ?

**Comment by Gywem** [comment]
Sorry, do you mean to include React separately (not as a npm module) and use `api.addFiles`?

As I know there is not other way to attain this, because `api.use` only accepts other meteor packages.

**Comment by Ben305** [comment]
You could try to use react as package in onTest. But I don't get it: Since 1.3.3 test-packages allows to use npm packages from the app.

**Comment by Gywem** [comment]
The reason why I don't include react as an NPM dependency on the package level is because is the only way to ensure that only one instance is created when launching the app.

I have tested the next command from the app:
`meteor test-packages --driver-package dispatch:mocha-browser MY_PACKAGE --port 4000`
, but it doesn't test the package from the app context loaded. So, as react is not included as an npm dependency in the package, it warns me about the react module is not found.

Is the command supposed to be shaped in another way?

I don't include react as a meteor package because I use other react dependencies that are only made as a NPM modules, therefore they require to set up react as a NPM module as well.

**Comment by ramijarrar** [comment]
@Gywem This is a known limitation, the Meteor guide suggests a [work-around](https://guide.meteor.com/writing-atmosphere-packages.html#testing-with-peer-dependencies):

> If your package makes use of peer npm dependencies, you cannot currently use test-packages to write package tests (as the dependencies will not be included in the special test app).

> To work around this, you can create a “scaffolding” test application, which is a simple app which simply includes the package and uses standard tests to run tests against the package. You can see examples of these kind of scaffold test apps in the [React packages repository](https://github.com/meteor/react-packages/tree/devel/tests).

**Comment by lawrentiy** [comment]
Two month I develop application and have missed docs about peerDependencies. I caught some issues, but someways fixed it. Now I try to add google-maps npm-package. And have investigated, that it`s impossible cause of meteor npm limitations.
That my investigation:
https://github.com/lawrentiy/meteor-react-issues

All in all, I am very disappointed in myself, that I miss that point in docs.
And in meteor, that it isn`t possible, to solve such dependencies right.

Will there any possibilities, to implement meteor packages with npm dependencies like react?
Or I have to create my own npm package (local or not) to wrap react and others packages and insert directly into my project?

**Comment by abernix** [comment]
The known limitation noted above is no longer the case, as I found with debugging #7500.  The section was removed from the Guide.

Also, peer NPM dependencies are known to work properly in Meteor 1.4.x and also [documented in the Guide](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies).

If you feel this is still not working properly, please ping me back and I'm happy to reopen this.

Thanks for opening this originally! :smile:

**Comment by macsj200** [comment]
I'm not sure if I have exactly the same problem or not, but I am really struggling to get phantomjs working with `dispatch:mocha` when using `test-packages`. I'm at my wit's end and would really appreciate some help.
