### ISSUE TITLE
Inconsistent Android build with Crosswalk

### ISSUE THREAD

**Issue by Exilz** [meteor/meteor#7291]
**_1 Upvote**_ @martijnwalraven Since Meteor 1.3 (I'm currently using Meteor 1.3.3.1), I noticed a strange bug when building Android applications.

The problem is, when I build the project like so `meteor build ../BUILDS/TEST-BUILD-ADNROID/1.0.0 --server localhost:3000` (purely for example), I noticed that the output directory isn't the same everytime.

On my first attempt, the directory `android/project/build` doesn't exist at all.
Then, I deleted it, and typed the previous command again.

Aaand hurray ! here is my `android/project/build/outputs/apk` folder with `android-x86-release-unsigned.apk` & `android-armv7-release-unsigned.apk` as expected.

This gets even stranger when, sometimes, the apk folder is there, but it's not filled with `release` apks, only debug ones. I couldn't reproduce this 100% of the time, but this happens.
I noticed it when I tried to sign them, since jarsigner told me "dafuq dude, it's already been signed".

The only way around this is to `meteor reset` before the first build, fail the first one, delete the destination folder, and succeed on the second try.
Since building is taking a _really long_ time on my projects (25 cordova plugins...), having to build twice really is time consuming for us.

I could reproduce this in an empty project :

```
meteor create testmobile
cd testmobile
meteor add-platform android
meteor add crosswalk
npm install
meteor build ../BUILDS/TEST-BUILD-ADNROID/1.0.0 --server localhost:3000
```

-> No `build` directory.

I don't know if this is related to meteor is itself or crosswalk. I didn't notice this on my Cordova projects not related to meteor, though.

**Comment by chrisknu** [comment]
+1 for a fix. Noticed the same issue, just kindof dealt with it by re-running after doing a meteor reset a few times

**Comment by pmwisdom** [comment]
I think this is the same issue I saw before. The workaround is to run the build script yourself. to generate the APK's. 

See https://github.com/meteor/meteor/issues/6756 for more info.

**Comment by AnthonyAstige** [comment]
I've also noticed inconsistencies in build names / directories, if it's there or not, etc.  Once other piece of perhaps interesting and maybe related information: Sometimes the app says it's build, but it appears to have an old version.

Steps to (sometimes) reproduce

1. Build the app as normal
1. Update your version number in `mobile-config.js`
1. Run `aapt dump badging /tmp/wingr-build/unaligned.apk | grep ver` (aapt can be found via something like `find ~/Android/Sdk aapt`)
1. See if your app version updated

Sometimes my version updates, sometimes it doesn't. I build again if I notice an old version, and it seems to update on the second run. I'm not confident on this pattern nor descended any patterns relating to when the version isn't updated in the first place.

**Enviornment**
* `METEOR@1.3.4.1`
* `crosswalk` plugin installed
* Ubuntu 16.04 LTS
* OpenJDK
* Android Studio graphical installation

**Comment by crapthings** [comment]
i've got this after meteor build ../android --server domain.com --verbose

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':processArmv7ReleaseResources'.
        > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/24.0.0/aapt'' finished with non-zero exit value 1

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

        BUILD FAILED

        Total time: 15.648 secs
        % ERROR building one of the platforms: Error code 1 for command: /Users/monsterstep/dev/nexushubs/cube/.meteor/local/cordova-build/platforms/android/gradlew with args: cdvBuildRelease,-b,/Users/monsterstep/dev/nexushubs/cube/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
        You may not have the required environment or OS to build this project
        => Errors executing Cordova commands:

           While building Cordova app for platform Android:
           Error code 1 for command: /Users/monsterstep/dev/nexushubs/cube/.meteor/local/cordova-build/platforms/android/gradlew with args:
           cdvBuildRelease,-b,/Users/monsterstep/dev/nexushubs/cube/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

same here

METEOR@1.3.4.1
crosswalk plugin installed
Ubuntu 16.04 LTS
OpenJDK
Android Studio graphical installation

**Comment by d62remi** [comment]
I had the same issue but I managed to fix it with that :

In package.json 
```js
"Script":{
   "build" : "meteor build ../output --server=http://url-server"
}
```

And after run :
```
meteor npm run build
```

Apks are in this folder 
android/project/build/outputs/apk ;-)

I hope it can fix your problem !

**Comment by Exilz** [comment]
@d62remi thanks for the suggestion but I don't see how using an npm script would fix the problem since the command is the same as you would type by hand.

**Comment by d62remi** [comment]
Neither do I. But it worked for me

**Comment by Exilz** [comment]
@d62remi be careful if you're not doing a meteor reset before building because sometimes the application built is not the latest version. 
Better not find this out in production 😅

**Comment by d62remi** [comment]
thank you for the info

**Comment by varunwyest** [comment]
Something that worked for me..
do a meteor reset and then a build and then go into the android\project folder and create the folder build and run the build again. It creates the apk.

**Comment by Exilz** [comment]
In the meantime, there is a way to save a lot of time instead of just rebuilding again.
You can use :

```
$ buildDest/android/project/cordova/build [--release]
```

Which will generate the APKs properly.
