### ISSUE TITLE
npm install inside bundle - sh: node-pre-gyp: command not found

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#7293]
I'm not 100% sure when this appeared but I think probably with 1.3.3.1. When deploying from a bundle on Ubuntu 16.04 / Node 0.10.45 / NPM 2.15 I was getting errors. Unfortunately I didn't save the error message but it was:

```
sh: node-pre-gyp: command not found
```
Followed by a load of stuff about fsevents. (Which I thought was a OSX only package so slightly confused, wondering if that's because I build the bundles for Linux on OSX)

It was fixed with `npm i -g node-pre-gyp` but obviously shouldn't have been a problem in the first place. Wonder if anyone else has come across this?

**Comment by benjamn** [comment]
I know this may sound a bit odd, but if you can install `meteor` on your production machine, `meteor npm install` will take care of providing tools like `node-gyp` and `node-pre-gyp` for you. Just don't use `meteor run`, of course (though `meteor node main.js` would be fine).

**Comment by mjmasn** [comment]
@benjamn So is requiring node-gyp/pre-gyp a recent thing? I have always just used npm install. We do (for now) have Meteor installed on all production machines because initially we were just sending a bunch of commit SHAs via SaltStack to all the servers for the apps and shared packages repo and each server was building its own copy of the app. That got too slow eventually and was crashing a couple of VPSs with each deploy 👎  but I haven't got around to removing it from Salt.

I've added a Salt state that does a global install of pre-gyp now anyway but good to know meteor npm install is a solution if the problem crops up elsewhere 👍 Thanks!
