### ISSUE TITLE
stuck to download meteor-tool@1.3.4

### ISSUE THREAD

**Issue by Nits7029** [meteor/meteor#7294]
Hello,

I have trying to run meteor project from last two days, and i am stuck to download meteor-tool@1.3.4 as it's not downloading.

What is a particular an issue?

Note: Internet availability/speed is not an issue and I am located in India.

I really need helps, PLEASE.

Thanks

**Comment by supermyth** [comment]
Hi, 
I'm not sure you meant 'meteor-toot'. Isn't its name 'meteor-tool' instead?

**Comment by Nits7029** [comment]
Sorry, yes it's meteor-tool

**Comment by supermyth** [comment]
In my case, It works. update and newly-install both.
Can you attach logs?

**Comment by Nits7029** [comment]
there is no log, in command prompt 

Downloading meteor-tool@1.3.4...          [=                        ] 4% 3616.5s

**Comment by lvitali** [comment]
A friend of mine have troubles like this, and the problem is the ram available, can you check how many ram you have when you run the command?

**Comment by laosb** [comment]
Actually Asia users are still suffering CDN problems. Please refer to #6960 for further information.
