### ISSUE TITLE
Chrome Failed to load resource: net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by carsonperrotti** [meteor/meteor#7295]
Having an issue running any meteor application in the latest version of Chrome. It works fine in Safari and Firefox.

Meteor 1.3.4.1
Chrome 51.0.2704.106
Mac OS 10.11.5

Here is the console log
<img width="1150" alt="screen shot 2016-06-24 at 1 13 19 pm" src="https://cloud.githubusercontent.com/assets/2063102/16344974/711f8b82-3a0d-11e6-9995-c11d0f4ee867.png">

Steps to reporoduce:
1. `meteor create example`
2. meteor run
3. open localhost:3000 in Chrome

**Comment by laosb** [comment]
Runs well with Chrome 50.

**Comment by carsonperrotti** [comment]
Chrome 51 is the latest production build on their website. I will have users on that version. To tell them to revert a chrome version is not a viable option.

**Comment by abernix** [comment]
@carsonperrotti Executing these exact same steps works fine for me under the exact same settings as you:

> Meteor 1.3.4.1
> Chrome 51.0.2704.106
> Mac OS 10.11.5

Also works fine on Chrome 51.0.2704.**103** as well as Canary 53.0.2781.0.  Please try using Incognito to test with or try disabling all your browser extensions and see if the problem goes away.  These errors are indicative of your browser expecting GZip'd content (and trying to decompress it) when the content isn't actually GZip'd.  It's possible that a proxy, or third party extension is mangling the content or is decompressing the content before it arrives.

And please report back what you find!

**Comment by carsonperrotti** [comment]
I only had one extension enabled. Reddit enhancement suite. Removing it from Chrome fixed the issue. Closing this issue. 

![](http://i.giphy.com/3o7qE4DT4NMhia1XLq.gif)

**Comment by abernix** [comment]
Hmm, that's truly bizarre.  I have RES installed on my work computer 😁 and had it enabled when I tested your repro – worked just fine.  Maybe you had some weird configuration within it?  I couldn't even begin to guess what could cause that though.

..or perhaps it's a blessing in disguise and you can finally get some work done now! :wink:
