### ISSUE TITLE
Don't do Method call to server if client stub fails

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#7300]
For now, when call a method, Meteor get a stub running and then immediately fire up an RPC call to server. I think if the client stub failed, we don't need to call the server method and it's clear that even called, the RPC call would fail too. What we need to do is just move the invoke process to [/packages/ddp-client/livedata_connection.js#L878](https://github.com/meteor/meteor/blob/master/packages/ddp-client/livedata_connection.js#L878), and don't fire the RPC call if we received an `exception`.

As this would change the DDP behavior, I think we can just have an option to turn it off. Reasons of making it as default:
- **Reduce server pressure** as server do not need to process those waste calls;
- **Do the first one without touching `ValidatedMethod`** as someone use Meteor in production even didn't heard of it, or simply don't want to change their code;
- **Rarely** do people make a Method fails on client but can succeed on server.
- **Don't affect user experience** as most stubs run very quickly, so it's almost no difference between waiting for the stub or do RPC calls right away. Even if it comsumes a lot of time, developers can simply turn this off. Again, rare cases.

TODO:
- [ ] Modify the code
- [ ] Update docs
- [ ] Update Meteor Guide
- [ ] Take down in `History.md`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Don't%20do%20Method%20call%20to%20server%20if%20client%20stub%20fails&body=Migrated%20from:%20meteor/meteor%237300) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
