### ISSUE TITLE
[1.4] Import gcloud throws error

### ISSUE THREAD

**Issue by valentinvichnal** [meteor/meteor#7301]
Hey, when I use gcloud in a plain nodejs app it works fine, but with Meteor.js I can't make it to work.

The plain node app installs and runs gcloud and the grpc dep without error on this environment:

```
windows 8
node -v: 4.4.5
npm -v: 3.9.6
```

The Meteor.js app can install gcloud too but it gives the following warnings on the same environment:

```
Meteor 1.4-beta.1
windows 8
node -v: 4.4.5
npm -v: 3.9.6
```

``` bash
  "fast-crc32c" in
/D/projects/demo-app-meteor/node_modules/hash-stream-validation/index.js
(os.windows.x86_32)
  "memcpy" in
/D/projects/demo-app-meteor/node_modules/bytebuffer/dist/ByteBufferNB.js
(os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

meteor npm install --save fast-crc32c memcpy
```

When I require gcloud and start the meteor app:

``` javascript
var gcloud = require('gcloud');
// or: import gcloud from 'gcloud';
// gcloud version: 0.36.0
```

Meteor throws this error:

``` javascript
C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
throw(ex);
Error: %1 is not a valid Win32 application
\\?\D:\projects\demo-app-meteor\node_modules\grpc\src\node\extension_binary\grpc_node.node
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Module.Mp.load (C:\Users\user\AppData\Local\.meteor\packages\babel-compiler\6.8.4-beta.1\npm\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (D:\projects\demo-app-meteor\node_modules\grpc\src\node\src\grpc_extension.js:38:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```

I can install fast-crc32c.
memcpy gives a lot of error on Windows 8 and can't install it.
grcp has a dependency of bytebuffer which should work without memcpy because it is only optional to make it faster.

grcp requires node >12, now that meteor use node 4.4.5 it should work, but still isn't.

The gcloud package repo: [https://github.com/GoogleCloudPlatform/gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node)

Any help would be appreciated.

**Comment by benjamn** [comment]
It looks like `memcpy` needs to upgrade the version of `nan` it uses, in order to work at all on Node 0.12 and later: https://github.com/dcodeIO/node-memcpy/issues/7

**Comment by Tetraib** [comment]
Hi, same problem for me. I don't really understand why it works fine on a standard Node 4.4 but not on the same Node 4.4 under the meteor environnement ?

**Comment by andreuka** [comment]
+1

**Comment by valentinvichnal** [comment]
@Tetraib @benjamn Yes, This is an official Google package and this cannot be memcpy's fault because it works on plain 4.4.5 nodejs but not with meteorjs 1.4 (4.4.5 node). 
There is probably something in the meteor environment that doesn't work with grpc_node.

**Comment by micahalcorn** [comment]
I am having similar problems using `gcloud`. However, I seem to be able to use it just fine on my local (OS X) machine despite the `memcpy` warning. My problem is when I try to deploy to my production Ubuntu instance using Meteor Up. Please see [this stack trace](http://pastie.org/private/wapafgb52x08gbjzeisnrg) and let me know if you have any insights.

**Comment by sethmurphy18** [comment]
Ok, so I have managed to get `memcpy` working on versions of node > 0.12...however, it now no longer works on node versions <= 0.12. Anyhow, it's failing a test and I cannot figure out why.

**Comment by ramezrafla** [comment]
Looks like it's really NPM and platform specific (unrelated to Meteor). Is everyone OK if we close this?
