### ISSUE TITLE
Why meteor get stuck on updating version 1.3.4. When its uninstalled and deleted, it reinstalled properly version 1.3.4.1. But as soon as I try run any meteor command it automatically starts updating meteor tool 1.3.2_4. And it again got stuck.

### ISSUE THREAD

**Issue by devin6391** [meteor/meteor#7303]
You guys have some serious problems with update. I whad meteor 1.3.2 earlier. Whenever I ran any meteor command it started downloading meteor tool 1.3.4. So after trying very hard for 2 days and meteor team's reply that it is a CDN problem, I uninstalled meteor and deleted all the files. Then I reinstalled meteor. The version that successfully got installed is 1.3.4.1. Now in my project folder I again ran meteor, ant this time I get 'downloading meteor tool 1.3.4.2'. Please guys do something, its really annoying. And I don't know if its really a CDN issue as installing is always ok. And from now on try not to automatically start updating meteor for any meteor command.

**Comment by tberghuis** [comment]
I got it to download by adding 54.192.225.217 warehouse.meteor.com to /etc/hosts https://github.com/meteor/meteor/issues/6960

**Comment by devin6391** [comment]
Not solved by this too. My update is now working correctly as per this solution. But whenever I want to run meteor from my project, downloading of meteor-tool@1.3.2_4 starts downloading. The download gets to 100% within 2 minutes but then it gets stuck and the download never actually completes. Please help me here. I am living in India and my meteor version right now is 1.3.4.1.

**Comment by tberghuis** [comment]
How long did you wait after it got to 100% ? I think I had to wait an extra three minutes.

**Comment by wuworkshop** [comment]
@tberghuis Thank you! That /etc/hosts solution fixed the problem for me.

**Comment by laosb** [comment]
Hi, we're really sorry for the annoying problems. It downloads 1.3.2.4 because your Meteor project wasn't updated to 1.3.4.1, so the old version of Meteor is needed to update the app. The CDN issue is really annoying and most Asia users are suffering, including myself in China. Please be patient as MDG tried and is trying hard to solve this. #6960 is the issue for CDN problems and please provide more information there so MDG can get more information to solve this. 

Closing this.

**Comment by raffibag** [comment]
@tberghuis very odd... I had 54.192.225.217 warehouse.meteor.com already in my hosts file and had the same issue. It was when I _removed_ it that it worked fine.
