### ISSUE TITLE
Timeout error in Galaxy paid service deployment. 

### ISSUE THREAD

**Issue by farhansumbul** [meteor/meteor#7308]
I am using the paid service of Galaxy. Trying to deploy my meteor app on Galaxy from Codeship.

Here is the deployment code.

echo $METEOR_TOKEN > deployment_token.json
echo $METEOR_SETTINGS > deployment_settings.json
DEPLOY_HOSTNAME=eu-west-1.galaxy.meteor.com METEOR_SESSION_FILE=deployment_token.json meteor deploy $METEOR_TARGET --settings deployment_settings.json

Every time I attempt deployment, there is Timeout error I am facing. Please suggest.
Error deploying application: Connection error (connect ETIMEDOUT)

Thanks in advance.

**Comment by laosb** [comment]
What's the version of Meteor you're using? This should have been fixed in 1.3.4.

**Comment by farhansumbul** [comment]
HI, My application is built on 1.3.3_1. Do you suggest that it should be updated to 1.3.4 ?

**Comment by abernix** [comment]
In general, I would recommend upgrading to 1.3.4.1.   However, I don't believe the problem that @laosb is referring to existed in 1.3.3.1 and I'm not sure upgrading will solve your problem – but it's possible that the increased control over the timeout could help your situation – especially if the latency between your CodeShip instance and the EU datacenter is abnormally high.  Maybe worth a try!

Please provide additional information to help diagnose the issue.

* Has this worked before and just stopped working?  Or has this never worked for you?
* Does the same problem occur if you try deploying to the North American datacenter?
* Does this same problem occur if you try deploying directly from your local box instead of through CodeShip?

**Comment by farhansumbul** [comment]
Hi Abernix,

- This is first time I am trying Galaxy using Codeship.

- I have tried on us-east-1.galaxy-deploy.meteor.com and this also failed with same error message. Is this the North American Data centre you are mentioning? As Galaxy provides only two data centre options eu-west-1.galaxy.meteor.com and us-east-1.galaxy-deploy.meteor.com. Correct me if I am wrong here.

- Deployment from local box works perfectly without having upgraded to 1.3.4

**Comment by abernix** [comment]
Yes, `us-east-1.galaxy-deploy.meteor.com` was the North American data center I was referring to.

I don't think it _currently_ matters, but I will point out though that the `DEPLOY_HOSTNAME` should be `eu-west-1.galaxy-deploy.meteor.com` (and not just `eu-west-1.galaxy.meteor.com` as you have in your example above).  A small, but potentially important discrepancy.

Also, make sure that you have your `METEOR_TOKEN` setup properly in your CodeShip environment variables.  Based on what you're showing, it should be the full contents of the `deployment_token.json` file that you've created on your local machine with `METEOR_SESSION_FILE=deployment_token.json meteor login`.

Debugging via SSH on CodeShip might be the most helpful as you can check the contents of the files, do traceroutes, try the whole process manually, etc.

**Comment by farhansumbul** [comment]
Thanks for the quick responses. 

Just to clarify, Galaxy mentions just ` eu-west-1.galaxy.meteor.com` in their websites. Anyways I am trying all suggested options. 

Just to know more on this. Is there any way that we can increase the timeout at CodeShip? And any idea that what is the available timeout they give internally. There are certain packages in my application like foursevescss which takes lot of time to download even in my local box. 

Thanks in advance.

**Comment by farhansumbul** [comment]
Thanks @laosb and @abernix . I upgraded the Meteor to 1.3.4 and it worked. 

Thanks a lot.

**Comment by abernix** [comment]
Bizarre that it fixed it for you because the neither the timeout changes nor any HTTP changes were included in 1.3.3 in any way (added here in 853e218a8983ef475a1ffdab5edd23ddd87287c3), but glad it's working now!  Perhaps it was another sporadic issue of some sort.  Closing! :smile:

**Comment by mcoenca** [comment]
I have exactly the same issue on Meteor 1.3.4, without CodeShip, just plain command line deployment

`sudo DEPLOY_HOSTNAME=eu-west-1.galaxy-deploy.meteor.com meteor deploy cyd.meteorapp.com --settings ../config/production/settings.json
Talking to Galaxy servers at https://eu-west-1.galaxy-deploy.meteor.com
Deploying your app...

Error deploying application: Connection error (ETIMEDOUT)`

Any news on this one :( ? It works from time to time but having to try 10 times a deployment where the build time is 3 minutes is a bit of a hassle.

Thanks.

**Comment by mcoenca** [comment]
Ok I found where this bug was mentioned, and the fix, in case anyone stops by:

![image](https://cloud.githubusercontent.com/assets/6507140/17678894/59e97644-6339-11e6-9003-58ddd645b2d7.png)


https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460
