### ISSUE TITLE
Invalid proxy operation may break Meteor

### ISSUE THREAD

**Issue by shiyao00** [meteor/meteor#7309]
I used 360 browser to access my Meteor app. The recent fix throws an error.

=> App running at: http://localhost:8765/

/home/xxxxxx/.meteor/packages/meteor-tool/.1.3.4_1.mwbgj9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-proxy.js:168
        resOrSocket.writeHead(400, {
                    ^
TypeError: Object [object Object] has no method 'writeHead'
    at attempt (/tools/runners/run-proxy.js:177:21)
    at Proxy._tryHandleConnections (/tools/runners/run-proxy.js:205:7)
    at Server.<anonymous> (/tools/runners/run-proxy.js:56:12)
    at Server.emit (events.js:106:17)
    at Socket.socket.ondata (http.js:2042:14)
    at TCP.onread (net.js:528:27)

**Comment by laosb** [comment]
Hi, server failures have no relationship with your browser, I think? Noticing that you're Chinese, would you like to join MeteorChina's QQ Group, so we can talk in Chinese to have a deep look at this issue? I'll post the details in English there if we get confirmed of this issue.

Or you may just want to talk here. I think you need a reproduction which produce this error with minimal efforts.

The QQ Group No. is 438397259. Any one interested in Meteor could join in, of course.

**Comment by abernix** [comment]
Looks to be a potentially legitimate issue: https://github.com/meteor/meteor/commit/b83e4d3061204d773104fd836bbbc7319c74d7b9#commitcomment-18019076

**Comment by benjamn** [comment]
This will be fixed by https://github.com/meteor/meteor/pull/7218/commits/81986f18945fe5816bd77a5c697768656b678bcc.

**Comment by benjamn** [comment]
I'm planning a [Meteor 1.3.4.2 bug fix release](https://github.com/meteor/meteor/pull/7340), with this fix included. Please run `meteor update --release 1.3.4.2-beta.0` if you would like to upgrade your apps immediately.

**Comment by abernix** [comment]
This was fixed in Meteor 1.3.4.2 with 94f9ebbdd83d10fb13b91809b09b411e61fc2a23.  Closing
