### ISSUE TITLE
Can't access OSX build server

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7314]
I can't seem to access OSX build servers using:
`meteor admin get-machine os.osx.x86_64`

It seems to freeze for a minute or so, and then it exits (I never actually get on the machine).
All other platforms work fine.

**Comment by benjamn** [comment]
I'll try restarting it.

**Comment by sebakerckhof** [comment]
Now I just get this error:
`Error from build farm: Sorry, no machines available now. Try again later. [try-again-later]`

**Comment by benjamn** [comment]
Not just busy… there's a problem with our mac mini build machine, and I'm still trying to figure out how to get it to launch instances again. I'll post updates here, so you don't have to keep trying. Sorry for the inconvenience!

**Comment by benjamn** [comment]
@sebakerckhof try now?

**Comment by sebakerckhof** [comment]
Seems to work now. Thanks.
