### ISSUE TITLE
Extra slash in PATH entry for meteor

### ISSUE THREAD

**Issue by roblourens** [meteor/meteor#7322]
Windows 10, Meteor 1.3.4.1

Just installed, and the command prompt couldn't find the `meteor` command. Checked the PATH and noticed that meteor added `C:\Users\roblou\AppData\Local\.meteor\` which shouldn't have a slash at the end. I don't know why Windows doesn't like that slash, but none of the other entries end in a slash. Removed it and now `meteor` can be found.

**Comment by abernix** [comment]
Are you _sure_ you restarted your command prompt (and maybe even restarted Windows too) after installing Meteor?  My `meteor` command works fine even with the trailing slash and if I remove it & restart it: still works, put it back & restart again: still works.   Also on Windows 10 & Meteor 1.3.4.1.

And further information: the trailing slash isn't something that Meteor is adding – it's done by the WiX installer.  You can [see the configuration setting which handles it here](https://github.com/meteor/meteor/blob/release-1.3.4.1/scripts/windows/installer/WiXInstaller/Meteor_Product.wxs#L69-L72).  It appears to be common to have it both ways as I have several non-Meteor items in my PATH that _DO_ have a trailing slash (even from Microsoft products).

**Comment by roblourens** [comment]
I'm sure I restarted the prompt. But, I just put the slash back, and it's still working. And it doesn't seem like it should be a problem anyway... Just a glitch I guess, thanks.
