### ISSUE TITLE
Meteor collection not being created automatically on start and autoform doesn't post to mongo db

### ISSUE THREAD

**Issue by devin6391** [meteor/meteor#7327]
Hi I am stuck on this issue. Please follow stackoverflow for description. Waiting for answer there but no response till now. Could be a bug with meteor@1.3.4.1
http://stackoverflow.com/questions/38083925/meteor-collection-not-being-created-automatically-on-start-and-autoform-doesnt

**Comment by abernix** [comment]
> Remember, an issue is not the place to ask questions.

I don't believe there is a bug here.  Please consult the forums, [the newly revamped Meteor Docs](http://docs.meteor.com) and [the very helpful Meteor Guide](http://guide.meteor.com/) for more help – in addition to checking the [example projects](https://www.meteor.com/articles).

If after you've exhausted those resources, you can work this into a reproduction repo proving that there is a bug with Meteor, please provide a repo link in a detailed issue write-up.  Closing.

**Comment by devin6391** [comment]
Its not new enough. It shows doc for v1.3.3. I have v1.3.4.1. On v1.3.2 everything worked fine. Its this version where things are not working. I will check all the versions for my current project and hope it gets solved.

**Comment by aboire** [comment]
why you already re-import meteor/meteor in /server/main.js?

I do like that export :

```
    ...
    export const RecipesCollection = new Mongo.Collection('recipes');
    ...
```

and Then put the name of the collection

```
    ...
    {{> quickForm collection="RecipesCollection" id="insertRecipeForm" type="insert" class="new-recipe-form" }}
    ...
```

**Comment by devin6391** [comment]
@aboire - -Tried it. Although you are right about multiple meteor/meteor imports. I fixed that. RecipesCollection collection cannot be put directly into quickform as its not in the window scope. My project is in public scope, can you fork it and fix it please?
https://github.com/devin6391/meteorLearn1/tree/master/recipebook

**Comment by devin6391** [comment]
Solved for now, there was a version issue with accounts-ui package, because of cdn issue, couldn't get the latest one. But still collections do not get created automatically when server starts

**Comment by aboire** [comment]
Look at the documentation "autoform" you will see that is exactly what he has marked it, I always did like this and it works very well
https://github.com/aldeed/meteor-autoform#a-basic-insert-form
