### ISSUE TITLE
useraccounts:iron-routing causes signup forbidden 

### ISSUE THREAD

**Issue by yigubigu** [meteor/meteor#7329]
- [ ] signup forbidden is displayed when user register after adding useraccounts:iron-routing 
- [ ] ubuntu 14.04, meteor:13.4.1  
- [ ]useraccounts:iron-routing
- [ ] after adding this package, user cannot register

**Comment by abernix** [comment]
This is the issue repository for Meteor Core.  You should open the issue with the package maintainer or [consult their documentation](https://github.com/meteor-useraccounts/iron-routing).  You most likely have a misconfiguration in your useraccounts setup.

Closing as this is the wrong place for this issue.
