### ISSUE TITLE
meteor update --release 1.2.1 cann't work

### ISSUE THREAD

**Issue by YY030913** [meteor/meteor#7330]
os : window server 2008 x64
meteor : 1.3.4.1(cann't download other version)
command: meteor update --release 1.2.1
error: can not download the meteor-tool@1.1.10
console: Sorry, Meteor 1.2.1 is not installed and could not be downloaded. Please check to make sure that you are online.

os: linux 64
command: curl https://install.meteor.com/ | sh
error: CInstallation failed.

**Comment by abernix** [comment]
When you run `meteor update --release 1.2.1`  how long does it take before you receive this error message?

**Comment by YY030913** [comment]
@abernix sometime it block, sometime it will take a few mins, can i download the meteror 1.2.1 installer???

**Comment by abernix** [comment]
What happens if you try creating a new project instead of trying to update an existing one?

```
meteor create new-meteor-1.2.1-project --release 1.2.1
```

**Comment by crapthings** [comment]
@YY030913

you need a vpn or proxy

**Comment by YY030913** [comment]
@crapthings  yes , the internet is terrible，if there has the prev meteor installer is perfect.

**Comment by YY030913** [comment]
@crapthings  is there any vpn or proxy you can recommend

**Comment by abernix** [comment]
@YY030913 Which OS do you want help fixing this on?  Windows or Linux?

**Comment by crapthings** [comment]
@YY030913 vpnso 价格不错 线路很多

**Comment by YY030913** [comment]
@abernix i fix it, it the internet problem,thanks very much

**Comment by laosb** [comment]
@YY030913 @crapthings In China, you can use `curl http://install-cn.ourmeteor.com/ | sh` to install the 1.3.4 version of Meteor, or append version number after the final slash in the URL to download a previous version. (But, only few versions were supported.)

Anyway, closing this and if someone find this again, please refer to #6960 .

**Comment by usukhbayar** [comment]
@abernix same problem here, cant update or create project, downloading meteor-tool does not finish after 100% download
![untitled](https://cloud.githubusercontent.com/assets/7240741/16509036/9d99ef1e-3f6b-11e6-8c49-237e11aaefb3.png)

**Comment by abernix** [comment]
@usukhbayar Sorry to hear about the problems.  If the download is reaching 100% this would appear to be a different issue.  So two options:

0. If you don't mind spending a bit of time to help debug this (please do if you can! would love to get this fixed), [open a new issue](https://github.com/meteor/meteor/issues/new) and include:
 * Details about your OS (_exactly_ what Windows version are you on)
 * What the last version of Meteor you were successfully running (e.g. `meteor --version` outside of a project directory)
 * How long you left this `Downloading meteor-tool` prompt waiting before you gave up (it can take a while to extract the installer package!)
 * A ZIP file of your `C:\Users\YourUsername\AppData\Local\.meteor` directory, uploaded to Dropbox as it might be large.  There shouldn't be any personal details in that folder, but if you'd like you can private message me the link on the [Meteor Forums](http://forums.meteor.com/).  Same username.
 * As many additional details as possible! :smile:
0. Alternatively, if you don't have time to spare, do a fresh re-install on Windows [using my instructions here](https://github.com/meteor/meteor/issues/6218#issuecomment-229352878).

I'm almost certain the second option will fix it for you however I'd like to put your `.meteor` folder onto my own box and see if I can reproduce the problem and find a better (automated) solution.
