### ISSUE TITLE
Function.prototype.bind changed in v1.3.3.1 (and persists in v1.3.4) from v1.3.2.4 

### ISSUE THREAD

**Issue by GeorgeCalvert** [meteor/meteor#7334]
Run the following in v1.3.2.4 and v1.3.3.1 or 1.3.4.1:
```
var fn = function (arg) {
    return 'this=' + typeof this + ' arg=' + typeof arg;
  };
var x = fn.bind('scalar_string');
console.log(x('abc'));
```
v1.3.2.4 produces `this=string arg=string`.
v1.3.3.1 produces `this=object arg=string`.
And you see similar results when binding to a scalar number.

This true on multiple platforms (e.g. Ubuntu, OSX and CentOS) and in multiple browsers (e.g. the latest Chrome and Firefox, which of course support `bind`).  I see Babel's runtime package creates its own bind unless `Function.prototype.bind` exists.

I do see that running the above in the console produces `this=object arg=string` no matter which version of Meteor is running.  Arguably then, the change brings Meteor's implementation more in line with the browsers' interpretation of the spec.  If a change was made specifically to that end, please note that when closing the issue.

Thanks.

**Comment by abernix** [comment]
Are you experiencing a problem in particular?  Or is this just a general question?

**Comment by GeorgeCalvert** [comment]
I have some listeners that are bound to scalar strings and this change caused a bug in code that predates introducing Meteor.  1.3.2.4 was preserving pre-existing browser behavior; 1.3.3.1 changed that but hell if I can find where.  I can work around the change -- but it'd be a big help to know whether the change was on purpose.

Apologies if this issue is better suited to StackOverflow.  It feels more like an issue/feature to me, particularly given how it surfaced.

**Comment by benjamn** [comment]
Historically, pre-ES5 JS coerced `this` to an object no matter what, even to the point of using the global object if you did `.call(null)`. With the advent of "strict" mode in ES5 (the version of JS before ES2015), code running in a `"use strict"` context (including all modules) no longer coerces `this` to an object.

In other words, I'm guessing your 1.3.3.1 code is now running in strict mode.

**Comment by GeorgeCalvert** [comment]
OK, that explains the difference between the console and the app code.

We were in strict mode pre Meteor and pre 1.3 with a `'use strict'` atop every file.  We still have `'use strict'` atop the files, though modules is itself enforcing strict mode in the app code.  The binding takes place in a package file that starts with a `'use strict'` but is not using `import` or `export`.

The surprise for us is that 1.3.3.1 *is* coercing.  I see this for both Underscore bind (which is the original code) and (as a test) Function.prototype bind.  It's not clear to me whether the bind in Babel runtime is running in strict mode -or- even whether that bind is somehow superceding the Function.prototype that Underscore uses.  Can we rule that out?

**Comment by abernix** [comment]
@GeorgeCalvert Just going through and trying to close some idle issues.  Are you still experiencing unexpected behavior on Meteor 1.4.1.1?

**Comment by GeorgeCalvert** [comment]
@abernix We're good in 1.4.1.  Thanks :-)
