### ISSUE TITLE
Adding Cordova plugin from private registry fails

### ISSUE THREAD

**Issue by jackkav** [meteor/meteor#7336]
```
meteor add @myscope/cordova-plugin-whatever@1.0.0

meteor add cordova:@myscope/cordova-plugin-whatever@1.0.0

=> Errors while initializing project:         

While reading project metadata:
.../.meteor/cordova-plugins: Cordova plugin must specify version:
@myscope/cordova-plugin-whatever@1.0.0
```

This issue appears to be due to line 1911 of meteor/tools/cli/commands-packages.js

`let [id, version] = target.split('@');`

I would expect this to remove the first element in the array and append @ to the first if three exist.

Meteor 1.3.3

Can be reproduced using the above meteor add.

**Comment by hwillson** [comment]
Just to re-cap where this issue stands: @jackkav has gratefully started PR #7350 to address this issue, but it was closed due to inactivity. If anyone encounters this issue and would like to help contribute to Meteor, please consider taking a look at (and ideally finishing off) PR #7350. Thanks!
