### ISSUE TITLE
Verify password before some operations

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#7337]
Currently, it's not easy to verify one's password before some danger operations, for example, dealing with security configurations and enter admin panels.

Suggestions:
- An API to verify the user's password:
  - Available on client, like `Accounts.verifyPassword(password)`.
  - When fired, verify user password with server and get a token from server and store on client, which is valid in 15min or so. This token will be used in checking the verify status in next steps.
- Have a API available in methods to ask for verifying, like `Accounts.requiresPasswordVerify()`: 
  - When fired, This throws an special error if no valid token found on client, or do nothing means password verified.
  - Developers can make the client call `Accounts.verifyPassword(password)` and rerun the method when the special error occurs.

**Comment by laosb** [comment]
Cross posted to forums: https://forums.meteor.com/t/feature-request-verify-password-before-some-methods/25803

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Verify%20password%20before%20some%20operations&body=Migrated%20from:%20meteor/meteor%237337) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
