### ISSUE TITLE
[1.4] Error deploying bundled Meteor app - module did not self-register

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#7339]
I'm receiving the following error when trying to run a bundled Meteor app:

```
root@fffea4fb1146:/opt/app# node main.js 
/opt/app/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/opt/app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
```

Appears to be related to the `accounts-password` package, as that is the one that bcrypt is being pulled in for.

**Comment by zvictor** [comment]
I had the same problem because of #7331.

First, run `meteor reset` and then follow @benjamn's instructions at https://github.com/meteor/meteor/issues/7331#issuecomment-229702518

**Comment by Petermo** [comment]
Running into the same problem. 
Going into
`.meteor/local/build/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt`
and running
`node-gyp rebuild`
solved it for me.

**Comment by rhettlivingston** [comment]
Similarly, I ran into this, but I had to ~/.meteor/packages/npm-bcrypt/ and .meteor/local. Then, when I reran meteor, it rebuilt bcrypt and everything worked. 

I had just updated from 1.4-beta.1 to 1.4-beta.7 and wiped out my node-modules and .meteor/local when the problem started. I'm wondering if some of these cached package builds need to be rebuilt across meteor versions???

**Comment by markoshust** [comment]
After clearing `~/.meteor/packages/npm-bcrypt/`, I'm able to build just fine. However, after running a `meteor build`, and deploying that bundle, I still receiving this error when trying to run the bundled assets;

```
/opt/app/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/opt/app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
```

**Comment by markoshust** [comment]
Hmm. What is the recommended node and npm versions for Meteor 1.4?

I'm using the official nodejs docker image for node 4.4.7. But I just realized it comes with npm 2.15.8.

**Comment by markoshust** [comment]
Receiving this error when trying to rebuild `node-gyp` on deploy machine:

```
root@05d01aa03b8c:/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin# node node-gyp.js rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.7 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.4.7/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.4.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.15-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by markoshust** [comment]
Just a quick update on this: I'm able to create a brand new 1.4-beta.10 project, build, and deploy successfully. I'm wondering if something is staling out in .meteor/versions or something. I'll do some additional tests and report back.

**Comment by priezz** [comment]
I have exactly the same problem. Have tried both with node `4.4.7` and `0.10.46`. 
4.4.7 throws:
```
/opt/app/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^
...
```
and 0.10.46 throws:
```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/usr/src/app/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/usr/src/app/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/app/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
```

It runs fine with `meteor run`.

**Comment by priezz** [comment]
Ok, I see, why it does not work with 0.10.46 - it should not as it refers to Node v4 functions. So we have to understand, what is wrong with fibers...

**Comment by markoshust** [comment]
Correct, this version is only node 4+. My error is happening on Node 4.

I found the problem; it is related to `accounts-password`. It's definitely a bug.

First issue: accounts-password was not auto-updated when upgrading meteor to 1.4-beta. It still uses the version for meteor 1.3.

Second issue: After upgrading to `accounts-password@1.2.12-beta.14`, it still doesn't work. This may be using outdated npm depends code for the package.js file? https://github.com/meteor/meteor/blob/release-1.4/packages/accounts-password/package.js

Can someone please help? I can't figure out a fix. I tried changing the package to `Npm.depends` per the manual at https://guide.meteor.com/writing-atmosphere-packages.html#npm-dependencies, and updating the `password-server.js` file to `var bcrypt = require('bcrypt');`, however I am receiving this error and am stuck:

```
/opt/app/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /opt/app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/opt/app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
```

**Comment by benjamn** [comment]
After you've deployed your bundle, you should be running `npm install` in the `bundle/programs/server` directory, which runs `node bundle/programs/server/npm-rebuild.js`, which should take care of rebuilding binary `npm` packages, including `bcrypt`. Though this is similar to the `node node-gyp.js rebuild` command you ran, it probably isn't rebuilding the `bcrypt` package in the same way.

**Comment by priezz** [comment]
Ben, I do `npm install` there...

**Comment by priezz** [comment]
I have noticed that for node v4 nothing is being rebuild, while for 0.10 it is.

**Comment by benjamn** [comment]
@priezz Sorry, but I don't think you're having the same problem. The
```
/opt/app/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
```
header often appears at the top Meteor stack traces, and is not a good sign of similarity.

**Comment by priezz** [comment]
I will try to run `npm-rebuild.js` manually and will report here.

**Comment by priezz** [comment]
The output is exactly the same as for @markoshust, I just decided not to repeat it completely here.

**Comment by markoshust** [comment]
I'm indeed running npm install from programs/server. Perhaps this is related to the `--architecture` flag.

This can be easily replicated. On mac, run:

```
meteor create meteor14 --release 1.4-beta.14
cd meteor14
meteor add accounts-password@1.2.12-beta.14
rm -rf ../meteor14-build/ && meteor build --architecture=os.linux.x86_64 --directory ../meteor14-build/
```

Then, transfer the bundled files to a linux environment, and run it:
```
ROOT_URL=http://localhost:4000 PORT=4000 NODE_ENV=production MONGO_URL=mongodb://localhost:27017 node main.js
```

You'll receive this error:
```
markshust@linux/:~/bundle$ ROOT_URL=http://localhost:4000 PORT=4000 NODE_ENV=production MONGO_URL=mongodb://localhost:27017 node main.js
/home/markshust/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/markshust/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
```

If I then try to rebuild for linux:
```
cd programs/server && npm i
```
I receive this error:

```
markshust@linux:~/bundle/programs/server$ npm i
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> meteor-dev-bundle@0.0.0 install /home/markshust/bundle/programs/server
> node npm-rebuild.js


> bcrypt@0.8.7 install /home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:15:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:70:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:91:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markshust/bundle/programs/server/npm/node_modules/meteor/accounts-password/npm-debug.log

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markshust/bundle/programs/server/npm-debug.log
```

**Comment by priezz** [comment]
@markoshust it seems, you have no devtools installed within the docker image. What image do you use? If it is `node:4.4.7-slim` it lacks them, use `node:4.4.7` instead.

**Comment by benjamn** [comment]
In order to deploy to a different architecture, the target environment needs to have the basic set of build tools: `make`, `gcc`, etc. You're missing `make`, at least, and maybe others. Note that many `npm` packages will require that you have at least `gcc`/`g++` 4.8. On Ubuntu or Debian, you'd need to do `apt-get install build-essential`. Other distributions will have their own package manager commands, but the tools are the same.

**Comment by benjamn** [comment]
Once you have a basic compiler toolchain installed, you might try running `meteor build` without the `--architecture=os.linux.x86_64` flag. I'm not sure that it hurts, but everything should work without it (since [Meteor 1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133), that is).

**Comment by priezz** [comment]
I have finally solved the issue.

```
meteor reset
cd .meteor
rm -f dev_bundle
ln -s ~/.meteor/packages/meteor-tool/.1.4.0-beta.14.m7p4qn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle ./
cd ~/.meteor
rm -rf package-metadata meteor
ln -s packages/meteor-tool/1.4.0-beta.14/mt-os.osx.x86_64/meteor ./
cd <PROJECT_DIR>
meteor update
```
After that it takes a long time to collect packages metadata.

A have added `node npm-rebuild.js` into the prelaunch script as well. I think this was exactly that helped, thanks to @benjamn.

**Comment by benjamn** [comment]
Cool! Just note that in the next release of 1.4 (`1.4-rc.0`), the `dev_bundle` link is moving to `.meteor/local/dev_bundle`, in case you have to create it manually again (hopefully not).

**Comment by priezz** [comment]
@benjamn thanks, good to know. I have recreated the link as it pointed to `1.3.4.4` in my case, don't know why.

**Comment by markoshust** [comment]
@priezz thanks for the tip -- I was actually using `node:4.4.7`, however this also doesn't include the build files. switched to `node:4.4.7-wheezy` now and all good 👍  I didn't have to do this with meteor 1.3, but it seems 1.4 requires build-tools for deploy. thanks so much. i think staring at this issue all morning i went blind and didn't see the `make` message 😋 

The `accounts-password@1.2.12-beta.14` package actually does work as it stands.

I do think that when doing `meteor update --release 1.4-beta.14`, it should update the `accounts-password` package to this new version -- no?

**Comment by priezz** [comment]
I currently have `accounts-password@1.2.12-beta.14` and I believe it was updated properly while upgrading to the next beta.  Maybe that was an issue with 1.4-beta6. But I always run `meteor update` after `meteor update --release...` - just to be sure :)

**Comment by benjamn** [comment]
The next release of Meteor 1.4 will have a version of `accounts-password` that uses `npm-bcrypt@=0.8.7`. I'm hoping the `=` will force the version more reliably than just `npm-bcrypt@0.8.7` did. https://github.com/meteor/meteor/pull/7218/commits/00c05facde53300d4adcf2524691ed681b37313d#r71216686

**Comment by priezz** [comment]
Here is my `docker-compose.yml`, maybe you will find it helpful:
```
regula-pro:
  image: 'node:argon'
  environment:
    - 'BUNDLE_URL=https://secure.host.com/path/to/bundle.zip'
    - 'BUNDLE_DIR=/usr/src/app'
    - "METEOR_SETTINGS={}"
    - 'MONGO_URL=mongodb://meteor_user:password@mongo.host.com:12345/db'
    - 'ROOT_URL=http://app.host.com'
    - 'TZ=Europe/Riga'
    - 'PORT=8080'
  restart: on-failure
  expose:
    - "8080"
  command:
    - bash
    - -c
    - 'date; APP_DIR="$$BUNDLE_DIR/programs/server"; if [ ! -f "$$BUNDLE_DIR/installed" ]; then apt-get -q update; apt-get -qy install unzip; npm install -g --depth 0 npm@3; mkdir -p "$$BUNDLE_DIR"; cd "$$BUNDLE_DIR"; npm install -g --depth 0 node-gyp; wget -q -N -O bundle.zip "$$BUNDLE_URL"; unzip -q bundle.zip; cd "$$APP_DIR"; npm install --depth 0; node npm-rebuild.js; touch "$$BUNDLE_DIR/installed"; fi; cd "$$APP_DIR"; npm start;'
```

I use `zip/unzip` here instead of `tar` as I often experience problems with tar under Docker.

**Comment by markoshust** [comment]
Ok -- found the root issue. Seems that it was really caused with docker & npm perms.

For those of you using Docker, this info might help. I went back to the `node:4.4.7` base image -- this actually works fine. What I really needed was an `--unsafe-perm` flag on npm i. For some reason, npm install was bombing out on docker because this flag wasn't included. Here is the Dockerfile for those interested, all working with 1.4 https://github.com/markoshust/docker-meteor/blob/master/Dockerfile

**Comment by WayneUong** [comment]
@markoshust #7475 seems to be related to this issue, do you have a similar solution for mupx? Thank you.

**Comment by markoshust** [comment]
See last comment -- the `--unsafe-perm` flag fixed it for me :)

**Comment by peterkuiper** [comment]
@markoshust this fixes it in my case too, thanks!

**Comment by awatson1978** [comment]
For people experiencing this issue on Modulus, see onmodulus/docker-build-meteor#25.

**Comment by aurelben** [comment]
--unsafe-perm on npm rebuild works for me

**Comment by Kosmin** [comment]
@markoshust sorry if I'm missing something, but where do you specify `--unsafe-perm` in the configuration? In `package.json` ? `mup.js` ? I couldn't find explicit documentation on setting this build option in `mup.js`

**Comment by markoshust** [comment]
When installing the npm modules

**Comment by abernix** [comment]
@Kosmin For Mup v2 (i.e. kadirahq/meteor-up), see my comment here: https://github.com/meteor/meteor/issues/7475#issuecomment-235229269  You'll see I made a custom Mup docker image that incorporates Mark's suggestion above (that addition was inspired by his findings with `--unsafe-perm` originally).

**Comment by Kosmin** [comment]
Thanks so much @abernix, this worked!
