### ISSUE TITLE
Artifacts on Android browsers

### ISSUE THREAD

**Issue by guaka** [meteor/meteor#734]
Minimum example at http://artifacts.meteor.com/ - code at https://github.com/guaka/meteor-artifacts

Stuff becomes blue, so it looks like stuff gets selected.

This can become much worse when dealing with maps and more extended interfaces, such as maps (with tiles turning blue and stuff like that).

**Comment by jamesharrington** [comment]
I had to be more specific ```a.btn{ -webkit-tap-highlight-color: rgba( 0, 0, 0, 0 ); }``` worked for me
