### ISSUE TITLE
stuck @ downloading meteor-tool@1.3.4_1...

### ISSUE THREAD

**Issue by ahhmarr** [meteor/meteor#7345]
it starts downloading every time i  ```meteor my-project``` and gets stuck between 50%-80% 
I'm using meteir 1.3 on ubuntu 16.04 and it is installed globally 

I think its a CDN issue (India).
here are my traceroute details:

> traceroute to static-meteor.netdna-ssl.com (146.88.128.4), 30 hops max, 60 byte packets
>  1  192.168.87.1 (192.168.87.1)  2.088 ms  2.303 ms  3.544 ms
>  2  172.50.60.1 (172.50.60.1)  19.784 ms  19.806 ms  20.628 ms
>  3  103.237.173.61 (103.237.173.61)  21.605 ms  21.613 ms  21.608 ms
>  4  ec2-23-23-23-1.compute-1.amazonaws.com (23.23.23.1)  22.512 ms  24.287 ms  24.298 ms
>  5  202.89.73.181 (202.89.73.181)  40.562 ms  42.896 ms  42.899 ms
>  6  125.18.243.73 (125.18.243.73)  43.613 ms  26.699 ms  32.786 ms
>  7  203.101.95.133 (203.101.95.133)  69.554 ms 182.79.247.33 (182.79.247.33)  69.100 ms 182.79.203.209 (182.79.203.209)  73.021 ms
>  8  * 125.16.2.122 (125.16.2.122)  73.005 ms  82.372 ms
>  9  ae1.bbr02.eq01.sng02.networklayer.com (50.97.19.249)  118.115 ms  111.553 ms  118.107 ms
> 10  ae0.bbr02.pn01.hkg01.networklayer.com (50.97.18.173)  147.673 ms  142.103 ms  147.657 ms
> 11  ae6.dar02.hkg02.networklayer.com (50.97.19.35)  288.089 ms ae6.dar01.hkg02.networklayer.com (50.97.19.33)  302.420 ms ae6.dar02.hkg02.networklayer.com (50.97.19.35)  283.715 ms
> 12  * * po2.fcr01.hkg02.networklayer.com (119.81.138.133)  318.130 ms
> 13  146.88.128.4 (146.88.128.4)  296.012 ms  297.243 ms *

**Comment by ahhmarr** [comment]
adding ```54.192.225.217 warehouse.meteor.com``` to my host file fixed the issue

**Comment by kenshinman** [comment]
@ahhmarr where can I find this host file on my windows 10? Thanks. (Nigeria)
Thanks

**Comment by abernix** [comment]
@kenshinman In Windows, this file is at `C:\Windows\System32\Drivers\etc\hosts`, however, Meteor 1.3.5.1 just came out and I would strongly recommend you try a fresh install of this new version since it contains some potentially helpful solutions for this exact problem:

    curl https://install.meteor.com/ | sh

**Comment by troygolden** [comment]
I get to 100% then it just gets stuck.

**Comment by ahhmarr** [comment]
@kenshinman you need to append at the end of the file C:\Windows\System32\Drivers\etc\hosts

1.open notepad as administrator 
  notepad >> right click >> run as administrator 
2.open the file (ctrl+o) 
   the location is C:\Windows\System32\Drivers\etc\hosts
3. append ```54.192.225.217 warehouse.meteor.com```
3. save

**Comment by troygolden** [comment]
Ok. Will try. Thanks.

Troy

Please excuse my typing.  I am out of the office and sending from my mobile device.

**Comment by babin93** [comment]
What is the cause of this problem ? Updating local host file seems like a bad hack that could cause me troubles in the future that will be hard to troubleshoot (I won't remember that I changed it).
