### ISSUE TITLE
[1.4] `simplesmtp` NPM crashes when sending e-mail

### ISSUE THREAD

**Issue by victorlambert** [meteor/meteor#7347]
Using Meteor@1.4-beta.7, simplesmtp crash the app on user account creation, when verification mail is sent I guess.

Here is the stack trace from galaxy logs : 

```
2016-07-03 22:11:47+02:00TypeError: Cannot assign to read only property 'reconnectCount' of false
2016-07-03 22:11:47+02:00 at SMTPClient._actionAUTHComplete (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:823:34)
2016-07-03 22:11:47+02:00 at SMTPClient._onData (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js:329:29)
2016-07-03 22:11:47+02:00 at emitOne (events.js:77:13)
2016-07-03 22:11:47+02:00 at TLSSocket.emit (events.js:169:7)
2016-07-03 22:11:47+02:00 at readableAddChunk (_stream_readable.js:153:18)
2016-07-03 22:11:47+02:00 at TLSSocket.Readable.push (_stream_readable.js:111:10)
2016-07-03 22:11:47+02:00 at TLSWrap.onread (net.js:531:20)
```

Probably related to #6529 .

**Comment by abernix** [comment]
Do you mind building a simple reproduction project of this issue using the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) guidelines?

It will allow easy confirmation when this bug is fixed and can also be used for building tests to ensure it doesn't happen again.

Thanks!

**Comment by victorlambert** [comment]
@abernix  I'll try to do that, but basically creating a user with MAIL_URL set should reproduce it.

**Comment by guns2410** [comment]
Same Error here...

MAIL_URL is smtp://username:password@smtp.mailgun.org:587

and while sending email gives the error

```
W20160711-19:18:16.384(5.5)? (STDERR) TypeError: Cannot assign to read only property 'reconnectCount' of false
W20160711-19:18:16.384(5.5)? (STDERR)     at SMTPClient._actionAUTHComplete (/Users/gunjansoni/.meteor/packages/email/.1.1.15-beta.9.1fjjsm9++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:823:34)
W20160711-19:18:16.385(5.5)? (STDERR)     at SMTPClient._onData (/Users/gunjansoni/.meteor/packages/email/.1.1.15-beta.9.1fjjsm9++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:329:29)
W20160711-19:18:16.385(5.5)? (STDERR)     at emitOne (events.js:77:13)
W20160711-19:18:16.386(5.5)? (STDERR)     at TLSSocket.emit (events.js:169:7)
W20160711-19:18:16.386(5.5)? (STDERR)     at readableAddChunk (_stream_readable.js:153:18)
W20160711-19:18:16.386(5.5)? (STDERR)     at TLSSocket.Readable.push (_stream_readable.js:111:10)
W20160711-19:18:16.387(5.5)? (STDERR)     at TLSWrap.onread (net.js:536:20)
```

using release 1.4-beta.9 and the email package is at 1.1.15-beta.9

**Comment by abernix** [comment]
I can confirm this is happening with `1.4-beta.9`.  Thanks for reporting this.  It's a bug in the `simplesmtp` NPM module involving illegally changing a `const` and it surfaced with the change to Node 4.  Meteor will need to update it's version of `simplesmtp`.

@benjamn I can confirm this is resolved by upgrading [`simplesmtp` in `email`](https://github.com/meteor/meteor/blob/release-1.4/packages/email/package.js#L10) to the latest version: [0.3.34](https://github.com/andris9/simplesmtp/blob/master/CHANGELOG.md).  I submitted PR #7387 with this change, entirely for the sake of running the tests.

**Comment by abernix** [comment]
This is confirmed fixed in the latest beta if you want to update to 1.4-beta.14:

    meteor update --release 1.4-beta.14

**Comment by guns2410** [comment]
Yes @abernix. Confirmed fixed. Thanks for the update.
