### ISSUE TITLE
meteor lost response after the first connection

### ISSUE THREAD

**Issue by DevinXian** [meteor/meteor#7364]
Ubuntu 14.04, node 6.2.2, npm 3.9.5, meteor 1.3.2.4

In dev mode,  works fine.

In production mode, `meteor build` is fine (need reinstall bcrypt module for npm-bcrypt);  
Startup  by command `{some env...} node bundleName/main.js` is fine,  meteor startup functions executed, seems everything is absolutely OK...

When I visited it via Chrome/FF... **first time**, meteor created session and fetched the `index.html`. However, meteor lost response then and can't be connected any more, **even via localhost `curl`**. Meteor seems serve **only once**. I can't find out what's wrong, any help please?
 I guess may be hangup for sth, but cpu/memory is not increasing.

Here is the chrome websocket log: 
![websocket_lost](https://cloud.githubusercontent.com/assets/5300023/16654449/73ff636a-4488-11e6-9c53-528238387aa3.png)
`wget localhost:{port}` result like: 
> $ wget localhost:7009
--2016-07-07 21:29:09--  http://localhost:7009/
Resolving localhost (localhost)... 127.0.0.1, 127.0.1.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:7009... connected.
HTTP request sent, awaiting response...

**Comment by abernix** [comment]
Could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Nothing really appears wrong here, but there's not much to look at here and without more information or a reproduction, we'll have to close the issue.

However, seeing as there appears to be a bit of a language barrier here, I'll leave this quote from @laosb here:

> Noticing that you're Chinese, would you like to join MeteorChina's QQ Group, so we can talk in Chinese to have a deep look at this issue? I'll post the details in English here if we get confirmed of this issue.

> Or you may just want to talk here. I think you need a reproduction which produce this error with minimal efforts.

> The QQ Group No. is 438397259. Any one interested in Meteor could join in, of course.

:smile:

**Comment by DevinXian** [comment]
Thank you for answering. Error can't be reproduced in a new project, so I closed the issue. I will write here if I solve the problem. Thank you again!

**Comment by laosb** [comment]
I'll try to help with any issue report in Chinese in that QQ group if I'm free. Drop me a private message on QQ if I wasn't there.
