### ISSUE TITLE
cursor.observe() should perhaps pass `ts` to callbacks for tailable cursors

### ISSUE THREAD

**Issue by sprohaska** [meteor/meteor#7368]
When using a tailable cursor, the current implementation deletes `ts`. See details below.  I think it would better pass it to the callbacks. `ts` might be useful to keep track of which docs have been processed and restart tailing at the tracked location, for example after application restart.

The relevant line is
<https://github.com/meteor/meteor/blob/b3a033bc725074c65debd8aaf0dd08955145e16c/packages/mongo/mongo_driver.js#L1324>.

With the following startup code:

```js
const db = new MongoInternals.RemoteCollectionDriver(oplogurl);
const oplog = db.open('oplog.rs');
const cursor = oplog.find(
  { ts: { $gt: MongoTimestamp.ZERO } },
  {
    // Meteor automatically sets `awaitdata` and related; see
    // <https://github.com/meteor/meteor/blob/b3a033bc725074c65debd8aaf0dd08955145e16c/packages/mongo/mongo_driver.js#L929>.
    tailable: true,
  },
);
```

The official API removes `ts`:

```js
cursor.observe({ added(doc) { /* ts missing. */ } });
```

The following workaround can be used to get the full docs:

```js
cursor._mongo.tail(cursor._cursorDescription, (doc) => { /* ts is there. */ });
```

**Comment by abernix** [comment]
Can you provide some insight about what you're _trying_ to do by tailing the oplog directly?  Perhaps there's a cleaner work-around that can be provided for you because I just don't see this being particularly useful to a vast majority of users.

**Comment by sprohaska** [comment]
I'm evaluating how to implement streaming db replication to migrate to MongoDB in another region; for example, migrate from Compose + Galaxy us-east-1 to Compose + Galaxy eu-west-1.

I'm exploring an approach that does not simply replicate the entire db, but only essential collections. Derived collections can be recomputed later. It seems convenient to use Meteor to implement this instead of writing a completely separate node app, since I have access to some application-specific data structures that are useful.

The sync starts with a full copy and then transitions to oplog tailing. I'd like to restart tailing after a restart of the sync app.

I find it confusing that everything works as expected except for the missing `ts`. When I run a query in the Mongo shell, `ts` is there. When I run essentially the same query in Meteor, `ts` is missing.

**Comment by abernix** [comment]
Again, `ts` is an implementation detail I'd venture to say that except in very rare cases like what you're doing, users will not need access to this.  Unfortunately, I don't have an easy answer.  I don't imagine this feature request will pick up much traction so you might consider [running Meteor from a checkout](https://github.com/meteor/meteor/#slow-start-for-developers) and making the change yourself temporarily to see if you can solve your problem then write up a more in-depth feature proposal that might allow this as a configurable option.

You can also probably find a more direct way to access the database if you dig through `MongoInternals` a bit more.

**Comment by abernix** [comment]
Appreciate the idea on this, but closing as it hasn't got traction and is an extreme edge case probably better served by a process outside Meteor.
