### ISSUE TITLE
meteor-tool error in promise_server.js after upgrade to 1.3.4_3 (Windows 10)

### ISSUE THREAD

**Issue by gjr-qm** [meteor/meteor#7374]
An hour ago meteor-tool was automatically updated on my machine (Windows 10). After that my existing application resulted in an error when starting (meteor).

Creating a new project with 'meteor create test-app' doesn't work either. The error i get is:

...\AppData\Local\.meteor\packages\meteor-tool\1.3.4_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: EPERM, symlink '...\AppData\Local\.meteor\packages\meteor-tool\1.3.4_3\mt-os.windows.x86_32\dev_bundle'

I tried stepping back to version 1.3.4_1 (which worked), but then meteor-tool is automatically updated again to version 1.3.4_3.

Anyone else having this problem? And is there a workaround (previous version worked just fine)?

**Comment by prolax** [comment]
Same here, windows 8.1

Can't do anything..

Can't run any apps, update meteor, or even check what version I'm on - just get the same error you are.

**Comment by dongzhi-yang** [comment]
Same here, I am on windows10
C:\Users\claud_000\AppData\Local\.meteor\packages\meteor-tool\1.3.4_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: EPERM, symlink 'C:\Users\claud_000\AppData\Local\.meteor\packages\meteor-tool\1.3.4_3\mt-os.windows.x86_32\dev_bundle'

**Comment by Jogibaer1963** [comment]
Same here on Windows 10.

**Comment by Rahman-S-M** [comment]
I got it for windows 7

**Comment by Rahman-S-M** [comment]
any workarounds would help.. completely blocked..not able to do any thing.

**Comment by Jogibaer1963** [comment]
How can I downgrade the meteor-tool and stop the automatic update ?

**Comment by NitroBAY** [comment]
Same here I tried uninstalling, reinstalling but the bug is still here on windows 10. Whenever I try to create a new project with an old release meteor --release 1.3.2, I can't run with `meteor` as it says `You're not in a Meteor project directory` and when I retry to create a project it says You're not in a Meteor project directory. I need in emergency a solution, I'd already a lot of retard with my current project, now I'm in a critical situation... If anyone can furnish a solution I really need it !!!!

**Comment by Rahman-S-M** [comment]
I found a way to downgrade to old version.

there is a meteor.bat file @ C:\users\XYZ\AppData\Local\.meteor
change the version from 1.3.4_3 to 1.3.4 and its working..


@echo off
SETLOCAL
SET METEOR_INSTALLATION=%~dp0%
"%~dp0\packages\meteor-tool\# **1.3.4**\mt-os.windows.x86_32\meteor.bat" %*
ENDLOCAL
EXIT /b %ERRORLEVEL%

**Comment by NKumarPraveen** [comment]
I too facing same issue windows 7

**Comment by NitroBAY** [comment]
In any way I hope such a problem will not happen again, and meteor will test its releases, a full framework who's front and back-end make code unusable without the framework. Without garanties for the future, I'll definitively stop counting on the framework as a reliable solution...

**Comment by D-Nice** [comment]
Same issue here... I will try Rahman's fix, in mean time this needs to be resolved.

**Comment by Kootain** [comment]
same issue here. but there will no problem when i create app in c:/users/username. So i try to run as administrator and it works.

**Comment by gjr-qm** [comment]
Running the commandprompt as administrator works for me too.

Before that i used Rahman's approach, in addition to which i made the meteor.bat file read-only, because it was overwritten each time i started meteor.

**Comment by benjamn** [comment]
I will unrecommend 1.3.4.3, which should prevent `meteor.bat` from getting updated to that version.

Can anyone provide a longer stack trace than what's already been provided?

**Comment by gjr-qm** [comment]
Is there a switch that i can use for a longer stack trace? I'd be glad to help out, but a clue would be welcome.

**Comment by benjamn** [comment]
Running the shell (`cmd.exe` or PowerShell) as an Administrator should be a workaround for this problem. Alternatively, [here's how](http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7) you can grant a non-Administrator user the ability to create symbolic links (though it takes an Administrator to grant the privilege).

I will note that [`fs.symlink(target, link, "junction")`](https://github.com/meteor/meteor/blob/126b9172c742015baccebb27aa83b24079b4d739/tools/cli/dev-bundle.js#L51) is supposed to be possible without Administrator privileges, so I'm not sure why it wouldn't work.

Are your application directories also on the `C:\` drive?

**Comment by gjr-qm** [comment]
My applications are on another drive (not C:\)

**Comment by benjamn** [comment]
@gjr-qm can you try creating an app on `C:`? Note: at this point you'll have to do `meteor create --release 1.3.4.3 app-name`, since `1.3.4.3` is no longer "recommended."

**Comment by gjr-qm** [comment]
@benjamn your command produces the same error when i run it as a regular user.

**Comment by abernix** [comment]
@benjamn These stack traces appear to be missing a slash in the path between `Local` and `.meteor`, no?

    AppData\Local.meteor\

**Comment by benjamn** [comment]
@abernix I think that's just from copy-pasting the `\.`

**Comment by gjr-qm** [comment]
Check! The \\ is there in the stack traces

**Comment by benjamn** [comment]
My hunch is that the `fs.symlink` is failing because the target is on a different disk (`C:\`) from the app, though I haven't ruled out the administrator privilege issue.

**Comment by gjr-qm** [comment]
I think it is not the drive, because it doesn't matter on which drive i try to run or create the app, it always results in the error when i do it as a regular user.

But when i run the command prompt/Powershell as administrator, then it simply works on all drives.

**Comment by gjr-qm** [comment]
Great work, thanx @benjamn!

**Comment by benjamn** [comment]
This should be fixed if you `meteor update --release 1.3.4.4-rc.0`.

**Comment by avenchen** [comment]
in windows 10, I open dos command with administrator, then run meteor. It works.

**Comment by Almaju** [comment]
Doing `meteor reset` worked for me. (Meteor 1.4)
