### ISSUE TITLE
Custom Meteor deployment results in MongoError: auth failed

### ISSUE THREAD

**Issue by Nakroma** [meteor/meteor#7378]
Hey, im probably doing something wrong but the meteor docs aren't that descriptive so im posting it here, since I can't get an answer on google too.  
I did everything described in the deployment docs, I built my meteor app, put the tarball on my server and extracted it. I installed node_modules. The database credentials work, and I actually created the 'meteor' database just to be 100% sure.  
Im using this line to start the app:  
`MONGO_URL=mongodb://myusername:mypassword@localhost:20536/meteor ROOT_URL=http://myurl.org node main.js`  

This is the error that results:

```
/var/www/virtual/nakroma/html/bundle/programs/server/node_modules/fibers/future.js:313  
                                                throw(ex);  
                                                     ^  
MongoError: auth failed  
    at Object.Future.wait (/var/www/virtual/nakroma/html/bundle/programs/server/node_modules/fibers/future.js:449:15)   
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)  
    at new MongoInternals.RemoteCollectionDriver (packages/mongo  /remote_collection_driver.js:4:16)  
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at Object.toError (/var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/var/www/virtual/nakroma/html/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
```

[Heres a screen for more readability:](http://puu.sh/pWPfH/b8de7f1d66.png)

**Comment by laosb** [comment]
Can you provide a simple reproduce?

**Comment by Nakroma** [comment]
I don't know since my server hoster has quite a bit of specific stuff going on.  
Install node/meteor/mongo etc  
pack project with "meteor build"  
put tarball on server, extract it  
run npm install inside /bundle/programs/server (cant remember the exact path, but the one with the package.json  
go into meteor db, use meteor and insert some random data to make it exist (dunno if thats actually neccessary, it didnt change the error message one bit)  
start meteor with the mongo_url and root_url provided above

**Comment by abernix** [comment]
@Nakroma What happens when you run the following command (adjust the username and password as necessary, of course!):

    mongo mongodb://myusername:mypassword@localhost:20536/meteor

**Comment by mjmasn** [comment]
Assuming the Mongo details _are_ correct, try quoting the string:

```
MONGO_URL="mongodb://myusername:mypassword@localhost:20536/meteor"
```

Should stop any special characters in the password from breaking things.

**Comment by Nakroma** [comment]
@abernix gives an assertion failed error, altough google says that is expected because you can't feed mongo shell a mongo url. I can log on no problem with `mongo meteor --port 20536 -u xyz -p abc` and `mongo localhost:20536/meteor` also works.  

@mjmasn Doesn't have any special characters, the quotes change nothing.

**Comment by Nakroma** [comment]
Yeah no problem :) Im running v.2.6.12  
Im on linux, but I don't have any mongo related environment variables set. No changes with using 127.0.0.1 either.

**Comment by abernix** [comment]
>`mongo localhost:20536/meteor` also works.  

If that works, doesn't that indicate that there is no username and password?

**Comment by Nakroma** [comment]
When I try without one I get a 'not authorized for query' error, which suggests I have to use a user which doesn't work either.

**Comment by abernix** [comment]
When you try it _where_?  Are you referring to using `MONGO_URL` when starting your app?  Or using `mongo` shell?  I really think you  have your Mongo server misconfigured as Meteor definitely supports using different usernames and passwords to connect to Mongo.  It's an extremely common configuration.

#### More Questions
##### First
What happens when you run?:

    mongo localhost:20536/meteor -u YOUR_USERNAME -p YOUR_PASSWORD

... and then try actually selecting information out of your database directly?

    db.yourcollection.find()

##### Second

What is the output of?:

    db._adminCommand( {getCmdLineOpts: 1})

##### Third

What's the output of the following?:

    use meteor
    show users

##### Fourth

What's the output of the following?:

    use admin
    show users

**Comment by Nakroma** [comment]
Yeah it probably is, the problem is I can't figure out where. 
When I try to start it with this line (as in the op): `MONGO_URL=mongodb://myusername:mypassword@localhost:20536/meteor ROOT_URL=http://myurl.org node main.js`  

**First**  
I get an auth error when connecting with admin credentials and it connects perfectly fine with my meteor db user. Im getting the information just fine:
 
    MongoDB shell version: 2.6.12
    connecting to: localhost:20536/meteor
    2016-07-13T13:32:32.827+0200 Error: 18 { ok: 0.0, errmsg: "auth failed", code: 18 } at src/mongo/shell/db.js:1292
    exception: login failed

**Second**  
Probably because the user isnt an admin

    {
         "ok" : 0,
        "errmsg" : "not authorized on admin to execute command { getCmdLineOpts: 1.0 }",
        "code" : 13
    }

**Third**  
This is pretty weird since the user has readWrite permissions and with .find() it shows the collections just fine.

`2016-07-13T13:50:38.295+0200 Error: not authorized on meteor to execute command { usersInfo: 1.0 } at src/mongo/shell/db.js:1363`

**Fourth**  
Same as above. Note, when I get into mongo with my master account I get this for meteor users:  

    {
        "_id" : "meteor.meteor",
        "user" : "meteor",
        "db" : "meteor",
        "roles" : [
                {
                        "role" : "readWrite",
                        "db" : "meteor"
                }
        ]
    }

And this for the admin collection (nakroma_mongoadmin is my predefined master account):  

{
        "_id" : "admin.nakroma_mongoadmin",
        "user" : "nakroma_mongoadmin",
        "db" : "admin",
        "roles" : [
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
}
    {
        "_id" : "admin.superuser",
        "user" : "superuser",
        "db" : "admin",
        "roles" : [
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
    }

Also note that I get the auth error when I log in with an admin account and literally nothing happens (as in, the command line doesnt output anything and just kinda hangs in nothingness) when I use the meteor user.

**Comment by abernix** [comment]
The Mongo driver has been updated to the latest stable version as of Meteor 1.4.0.1.  Your last update proves that there are some configuration concerns with your Mongo deployment.   If you can prove this is a bug with Meteor, I'm happy to reopen, but as of now I have to direct you to Mongo documentation or recommend using a Mongo SaaS like mLab or Compose.io.

**Comment by lukastheiler** [comment]
I actually have the same Issue, and think this is an issue with mongodb versions. I created the mongo docker container + user: 
````
docker run --name mongodb -p 27017:27017 -d mongo --auth  
docker exec -it mongodb mongo admin
db.createUser({ user: 'admin', pwd: 'straightscarletviolably', roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] });
```

Then, when starting the meteor container I get the error: 

````
=> Starting meteor app on port:80
/tmp/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);					^
MongoError: Authentication failed.
```

When I connected with mongo 3.2, directly, I did get the Authentication Error as well - after upgrading to 3.2.9, the error is gone. 

So i guess it's a Meteor issue, they probably use the 3.2 driver.

**Comment by Gradlon** [comment]
I Had the same issue and i Solved it.
It was rather a stupid mistake which lead to the error.
Example:
MONGO_URL=mongodb://USER:PASS@mongodb/DB

You need to add the user with which you want to authenticat to the according DB.
In this exampple.

1. Login to your Mongo admin Shell
2. Set Your DB in this example: >use DB
3. Add the user: db.createUser({ user: 'USER', pwd: 'PASS', roles: [ { role: "dbOwner", db: "DB" } ] });

This solved the problem for me.

**Comment by nickgrealy** [comment]
Yeh, this was a really obtuse stacktrace - as previously mentioned - pay attention to the `MongoError: auth failed` error message (it speaks the truth). We couldn't authenticate with the database, because of the `MONGO_URL` we'd configured. 

Leaving this message here for "future" Nick.

**Comment by devanghire** [comment]
you have to use command like:- meteor npm install

**Comment by aditzend** [comment]
@Gradlon you saved my day. Your solution solved my problem too!!
