### ISSUE TITLE
gitignore rule for dev_bundle

### ISSUE THREAD

**Issue by ramijarrar** [meteor/meteor#7379]
Now that our local meteor directory contains a symlink to "dev_bundle", I think it makes sense to cover this with a gitignore rule (in the same spirit as ".meteor/local")

**Comment by ramijarrar** [comment]
Just saw the changes in 1.3.4.3 and it looks like this already been addressed.

**Comment by abernix** [comment]
For the record, this has been moved in Meteor 1.3.5.1 to be inside the `local` folder so this should no longer be necessary.  After you upgrade your projects to 1.3.5.1, you can remove the `.meteor/dev_bundle` symlink if it isn't cleaned up for you automatically.
