### ISSUE TITLE
CSP prevents loading fonts on meteor.com, website unusable

### ISSUE THREAD

**Issue by tuxtina** [meteor/meteor#7382]
The Content Security Policy on meteor.com seems to prevent fonts from loading, causing an endless stream of messages on the console, resulting in high CPU usage and the website being mostly unusable:

> [Error] Refused to load the font 'data:application/font-woff;charset=utf-8;base64, (...)' because it violates the following Content Security Policy directive: "default-src 'self' https://d14xs1qewsqjcd.cloudfront.net http://platform.twitter.com https://platform.twitter.com http://syndication.twitter.com https://syndication.twitter.com http://*.olark.com https://*.olark.com http://meteor-frontpage-assets.s3.amazonaws.com https://meteor-frontpage-assets.s3.amazonaws.com http://*.marketo.com https://*.marketo.com http://*.marketo.net https://*.marketo.net http://*.cloudfront.net https://*.cloudfront.net http://maxcdn.bootstrapcdn.com https://maxcdn.bootstrapcdn.com". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Errors happen with both Safari and Chrome on OS X. Problem did not occur for me before to the weekend.

**Comment by abernix** [comment]
Thanks for reporting this!

Hmm, @dominicnguyen, is this your realm?

**Comment by kachkaev** [comment]
I can confirm this on Ubuntu & Windows Chrome. Ubuntu FF OK.

**Comment by laosb** [comment]
Looks like fixed. Closing.

**Comment by jgmurillo10** [comment]
Hi @laosb , How did you fixed the problem? I am having the same in a personal project.
