### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by kachkaev** [meteor/meteor#7384]
​I'm trying to use `meteor npm install `[`react-map-gl`](https://github.com/uber/react-map-gl) and end up with this fatal error in a browser:
```txt
svg.react.js:61 Uncaught TypeError: fs.readFileSync is not a function
```

![capture](https://cloud.githubusercontent.com/assets/608862/16728158/b0a9801c-475c-11e6-8a3b-3629b00c6b57.PNG)

My guess is that the issue is somehow related to the way meteor mocks nodes's `fs` methods. I've added [`meteor-node-stubs`](https://github.com/meteor/node-stubs) to my local `node_modules`, but this did not help.

I understand that using `fs.readFileSync` on a client is odd, but assume that there is a reason for referencing this method. It does not seem to cause problems in apps that are built not with meteor, so I guess we should not move the issue upstream.

Trying everything on Meteor 1.4-beta.9. Any ideas on a temporal workaround?

**Comment by kachkaev** [comment]
It appears that the issue I'm facing is sourcing from this file:  [mapbox-gl-shaders/index.js](https://github.com/mapbox/mapbox-gl-shaders/blob/57576d602b2239fa4854f69f2edc72b1267c3e1a/index.js). It is expected to be processed by webpack and turned into a single file where occurances of `fs.readFileSync` are replaced with the actual content of the files.

Meteor does not seem to be able to process such a thing. Any ways to overcome the problem with the current build system?

I could have tried to just use a dist version of `mapbox-gl-js`, but only if there was no react wrapper. Uber's `react-map-gl` sets `mapbox-gl-js`as a dependency and imports various sub-dependencies in its code using `import`/`require`.

**Comment by kachkaev** [comment]
Another interesting thing is seeing `svg.react.js` in the exception log. The error does not belong there at all. Something must be wrong with how meteor makes source maps in `1.4-beta.9`

**Comment by Nexus7** [comment]
I think we are also seeing this similar error with fs using another npm package... on the browser console we see function not defined errors. I think the meteor-node-stubs just gives you an empty object for 'fs' so I think that is why it happens. Previously we used meteorhacks:npm to install the package and cosmos:browserify to use the package on the client side. 

However as we are currently trying to migrate to Meteor 1.3/1.4 we were hoping to ditch both these packages and just use the native npm... From the Meteor guide it seems that we should just be able to do an import on both client and server without problems but obviously in our previous method some more magic was being conducted which has now dropped out of our build process...

**Comment by super-iterator** [comment]
@kachkaev any luck to get fs.readFileSync on the client side? facing the same thing here!

**Comment by kachkaev** [comment]
I ended up switching to webpack where I was able to configure a transform when loading mapbox js files. fs.readFileSync is now executed during build so the browser gets the result of this function, not the function call itself.

Maybe this thread of a few neighbouring ones can help you: https://github.com/mapbox/mapbox-gl-js/issues/1649

**Comment by abernix** [comment]
`fs.readFileSync` will never truly work on the client as it's Node functionality and the browser is not Node. 

Closing for a similar reason as #7567, but mostly because the discussion in #6890 is the closest thing to a more generic, actual solution for this (rather than having individual issues about NPM modules that don't work).

And from #7567:
> `meteor-node-stubs` is available to try to solve this, however you can install whatever functions you'd like to mock Node functions and have them behave as you wish.  Additional conversation can be found in these issues:

> * https://github.com/meteor/meteor/issues/6578#issuecomment-200895733
> * https://github.com/meteor/meteor/issues/6890#issuecomment-214032062 (open, and ultimately a solution)
