### ISSUE TITLE
[feature-request] Provide arguments to onLogin / onLoginFailure on client

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#7385]
There's some discussion of this at #3572 but that issue is closed and not specific to this issue.

It would be good to have at least the type and error passed to `onLogin`/`onLoginFailure` callbacks on the client. I can sort of understand the argument for not providing the method arguments e.g. email/username & password (although the point is moot, you either trust the client side code you're bundling or it shouldn't be in there) but the other non-sensitive-information arguments that are available on the server should be supplied. These are `type`, `allowed`, `error`, `user`, `connection`, and `methodName` [but not `methodArguments`].

The use case is checking for a specific error on login, which is fine if using a login form that calls `Meteor.loginWithPassword` with a callback but not fine on a session resume / page refresh etc. If a specific error appears I need to redirect the user to a different website along with a login token for that website. I want to provide these details in the error object from the server because I don't see another way of returning anything from a login attempt to the user.

**Comment by mjmasn** [comment]
About to go on holiday so not going to do a full PR but minimal fix to get the error in the callback is a 1 line change. See https://github.com/meteor/meteor/compare/devel...mjmasn:7385-provide-error-to-onloginfailure-callback

Not sure about providing the other arguments, that may be more involved.

**Comment by s-ol** [comment]
+1, currently it seems to be impossible to obtain ANY error information from implicit login attempts using a cached session token (when re-opening a page). It is also impossible to differentiate between such implicit login attempts and user-initiated login attempts / explicit method calls.
