### ISSUE TITLE
Strangely adding events to parent template

### ISSUE THREAD

**Issue by arashnewday** [meteor/meteor#7386]
I just find out Meteor adds events to parent template instead to specified elements 

Best way to describe this issue is by giving example:
e.g. I have **todosList** and **todo** templates:

```
<template name="todosList">
    <div class="content-scrollable" id="content-scrollable">
            {{#each todo}}
                {{> todo}}
            {{/each}}
    </div>
</template>
```

```
<template name="todo">
    <div class="todo-item">{{text}}</div>
</template>
```

and:

```
Template.todo.events ({
    'click .todo-item: function () {
             // do something
    }
});
```

Here is the issue, **click event** will be added to `<div class="content-scrollable" id="content-scrollable">`  which is a parent template element **multiple times**, as many times as i have todo items in this session. this is not normal behavior of JavaScript and it may cause problems and overhead event triggering specially for events like mousemove and scroll

<img width="1019" alt="screen shot 2016-07-11 at 5 56 17 pm" src="https://cloud.githubusercontent.com/assets/14264142/16732263/9168c1c4-4791-11e6-9251-6ae671892a30.png">

**By the way why it using jQuery for handling event?!?**

Meteor 1.3.4.1 , Chrome 51.0.2704.106 , Firefox 47.0 , OSX El Capitan 10.11.5

**Comment by abernix** [comment]
I'm not immediately sure why the events are on the parent element versus the element directly.  The events work properly though.  Are you actually experiencing this problem:

> problems and overhead event triggering specially for events like mousemove and scroll

**Comment by abernix** [comment]
_(Sorry, accidentally "updated" before I was done)_

I could postulate that it has something to do with storing it on the element which _contains_ the template rather than the template itself so that on template redraws the existing events are preserved, but I'm not really sure.

Perhaps someone else can provide some insight.

**Comment by abernix** [comment]
(Labeling as `bug`, though I'm not really sure it is.)

**Comment by hwillson** [comment]
I've moved this over to the Blaze repo: meteor/blaze#233. Thanks!
