### ISSUE TITLE
Meteor tools download taking longer than 1 hour

### ISSUE THREAD

**Issue by brettg2** [meteor/meteor#7388]
Trying to run meteor on windows 10 (64 bit) and the meteor command is downloading the latest version of meteor tools (meteor-tool@1.3.4_1) which has been going for over an hour. We've had this happen on other machines and thought it would be resolved. Now it's happening again. The first time it happened was over a month ago. Has anyone else experienced this? Is there a solution being created or a work-around developed? Thank you.

**Comment by rafialikhan** [comment]
Faced the same issue (on Windows 7, im sure Window 10 will also have the same) here and after several repeat attempts, meteor finally seems all setup and ready to go.... but after running meteor - it gets stuck at Starting your app ...

**Comment by laosb** [comment]
Sounds like the CDN issue, which might be the most widely-affected issue, #6960. I would close this and please track or get workarounds in #6960.
