### ISSUE TITLE
Accounts.createUser doesn't run when testing

### ISSUE THREAD

**Issue by AbhinavMadahar** [meteor/meteor#7395]
When running `meteor test --driver-package dispatch:mocha-phantomjs` the Accounts.createUser function does not run. Current Meteor version is 1.3.4.1. Installed packages with versions:
```
accounts-base@1.2.8
accounts-password@1.1.11
aldeed:collection2@2.9.1
aldeed:collection2-core@1.1.1
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.5
autoupdate@1.2.10
babel-compiler@6.8.3
babel-runtime@0.1.9_1
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.8
blaze-tools@1.0.9
boilerplate-generator@1.0.9
caching-compiler@1.0.5_1
callback-hook@1.0.9
check@1.2.3
coffeescript@1.1.2_1
dburles:factory@1.0.0
ddp@1.2.5
ddp-client@1.2.8_1
ddp-common@1.2.6
ddp-rate-limiter@1.0.5
ddp-server@1.2.8_1
deps@1.0.12
diff-sequence@1.0.6
dispatch:mocha-phantomjs@0.1.7
dispatch:phantomjs-tests@0.0.5
ecmascript@0.4.6_1
ecmascript-runtime@0.2.11_1
ejson@1.0.12
email@1.0.14_1
es5-shim@4.5.12_1
fastclick@1.0.12
fourseven:scss@3.4.3
geojson-utils@1.0.9
hot-code-push@1.0.4
html-tools@1.0.10
htmljs@1.0.10
http@1.1.7
hwillson:stub-collections@1.0.1
id-map@1.0.8
jquery@1.11.9
kadira:flow-router@2.12.1
launch-screen@1.0.12
livedata@1.0.18
localstorage@1.0.11
logging@1.0.13_1
mdg:validation-error@0.2.0
meteor@1.1.15_1
meteor-base@1.0.4
minifier-css@1.1.12_1
minifier-js@1.1.12_1
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.6.4
modules-runtime@0.6.4_1
mongo@1.1.9_1
mongo-id@1.0.5
npm-bcrypt@0.8.6_1
npm-mongo@1.4.44_1
observe-sequence@1.0.12
ordered-dict@1.0.8
practicalmeteor:chai@2.1.0_1
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.7.2_1
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.5
react-meteor-data@0.2.9
reactive-dict@1.1.8
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
routepolicy@1.0.11
seba:minifiers-autoprefixer@1.0.1
service-configuration@1.0.10
sha@1.0.8
spacebars@1.0.12
spacebars-compiler@1.0.12
srp@1.0.9
standard-minifier-js@1.0.7_1
tmeasday:check-npm-versions@0.3.1
tracker@1.0.14
ui@1.0.11
underscore@1.0.9
url@1.0.10
webapp@1.2.9_1
webapp-hashing@1.0.9
xolvio:cleaner@0.3.1
```

And package.json dependencies:
```json
  "dependencies": {
    "babel-eslint": "^6.1.0",
    "babel-plugin-transform-class-properties": "^6.10.2",
    "enzyme": "^2.3.0",
    "eslint": "^2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.10.0",
    "eslint-plugin-jsx-a11y": "^1.5.3",
    "eslint-plugin-react": "^5.2.2",
    "faker": "^3.1.0",
    "logarithmic": "^1.1.0",
    "meteor-node-stubs": "^0.2.3",
    "mocha": "^2.5.3",
    "node-random-name": "^1.0.1",
    "notie": "^3.2.0",
    "peerjs": "^0.3.14",
    "precommit-hook-eslint": "^3.0.0",
    "react": "^15.2.1",
    "react-addons-pure-render-mixin": "^15.0.2",
    "react-addons-test-utils": "^15.2.1",
    "react-bootstrap-switch": "^3.4.5",
    "react-dom": "^15.0.2",
    "react-materialize": "^0.14.3",
    "react-mounter": "^1.2.0",
    "simple-peer": "^6.0.4",
    "sinon": "^1.17.4",
    "sweetalert": "^1.1.3"
  },
  "devDependencies": {
    "react-addons-test-utils": "^15.2.1",
    "react-dom": "^15.2.1"
  }
```

Name a file RegForm.jsx

```javascript
import React from 'react';
import { Accounts } from 'meteor/accounts-base';
import { Meteor } from 'meteor/meteor';

export default class RegForm extends React.Component {
  onSubmit = (event) => {
    event.preventDefault();

    Accounts.createUser({
      email: `example${Meteor.user()}@gmail.com`,
      password: 'Password123',
    }, (error) => {
      console.log('After creating:', error || Meteor.user()); // LINE X
    });
  }

  render() {
    return (
      <div>
        <form onSubmit={this.onSubmit}>
          <button type="submit">Submit</button>
        </form>
      </div>
    );
  }
}
```

Then another named RegForm.test.jsx

```javascript
import React from 'react';
import { shallow } from 'enzyme';

import RegForm from './RegForm';

describe('RegForm', () => {
  it('creates a new user', () => {
    Meteor.logout();
    const form = shallow(<RegForm />);
    form.find('button[type="submit"]').simulate('click');
    console.log('User:', Meteor.user());
  });
});
```

Running `meteor test --driver-package dispatch:mocha-phantomjs` does not cause `LINE X` to be run, even though it should.

**Comment by abernix** [comment]
Not confirming as a bug yet, but do you mind just putting all that into a new Meteor project and uploading it to Github so it's easier to reproduce?  I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.

Much appreciated, if you could.

**Comment by AbhinavMadahar** [comment]
This reproduces the issue

https://github.com/AbhinavMadahar/meteor-bug-repo

To reproduce:
1. Clone the repo
2. Run `npm install && meteor` and then quit after meteor installs all the packages
3. Run `meteor test --driver-package dispatch:mocha-phantomjs`
4. See that LINE X is not run, reproducing the bug

**Comment by abernix** [comment]
Thanks for making the reproduction.  Unfortunately, I don't think I was able to reproduce things properly.  Someone with React experience might be of more help here.  I apologize for my unfamiliarity.

When I follow the reproduction steps above, I get the following:
```
Unable to resolve some modules:

  "react/addons" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
  "react/lib/ReactContext" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
  "react/lib/ExecutionEnvironment" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
```

I do receive notification that the client tests have run:

```
I20160714-19:31:07.321(3)? --------------------------------
I20160714-19:31:07.322(3)? ----- RUNNING CLIENT TESTS -----
I20160714-19:31:07.322(3)? --------------------------------
I20160714-19:31:07.322(3)?
=> Meteor server restarted
I20160714-19:31:08.766(3)?
I20160714-19:31:08.767(3)?
I20160714-19:31:08.769(3)?   RegForm
I20160714-19:31:08.779(3)? User: null

I20160714-19:31:08.781(3)?     ✓ creates a new user
I20160714-19:31:08.781(3)?
I20160714-19:31:08.781(3)?
I20160714-19:31:08.782(3)?   1 passing (16ms)
I20160714-19:31:08.782(3)?
I20160714-19:31:08.783(3)? stdout:
I20160714-19:31:09.885(3)? All client and server tests finished!
```

But, they keep repeating themselves because the app keeps crashing.

Not only do I not see the `LINE X` getting ran, I also don't see **anything** inside the `onSubmit` being called, so that indicates to me that there is a larger problem here.

Any guidance in reproducing this would be appreciated!

**Comment by AbhinavMadahar** [comment]
Thank you for checking. I will look into my own code and try to find the
problem.

On Thu, Jul 14, 2016 at 12:37 PM Jesse Rosenberger <notifications@github.com>
wrote:

> Thanks for making the reproduction. Unfortunately, I don't think I was
> able to reproduce things properly. Someone with React experience might be
> of more help here. I apologize for my unfamiliarity.
>
> When I follow the reproduction steps above, I get the following:
>
> Unable to resolve some modules:
>
>   "react/addons" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
>   "react/lib/ReactContext" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
>   "react/lib/ExecutionEnvironment" in /Users/jesse/Dev/Misc/meteor-tests/meteor-issue-7395/node_modules/enzyme/build/react-compat.js (web.browser)
>
> I do receive notification that the client tests have run:
>
> I20160714-19:31:07.321(3)? --------------------------------
> I20160714-19:31:07.322(3)? ----- RUNNING CLIENT TESTS -----
> I20160714-19:31:07.322(3)? --------------------------------
> I20160714-19:31:07.322(3)?
> => Meteor server restarted
> I20160714-19:31:08.766(3)?
> I20160714-19:31:08.767(3)?
> I20160714-19:31:08.769(3)?   RegForm
> I20160714-19:31:08.779(3)? User: null
>
> I20160714-19:31:08.781(3)?     ✓ creates a new user
> I20160714-19:31:08.781(3)?
> I20160714-19:31:08.781(3)?
> I20160714-19:31:08.782(3)?   1 passing (16ms)
> I20160714-19:31:08.782(3)?
> I20160714-19:31:08.783(3)? stdout:
> I20160714-19:31:09.885(3)? All client and server tests finished!
>
> But, they keep repeating themselves because the app keeps crashing.
>
> Not only do I not see the LINE X getting ran, I also don't see *anything*
> inside the onSubmit being called, so that indicates to me that there is a
> larger problem here.
>
> Any guidance in reproducing this would be appreciated!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/meteor/meteor/issues/7395#issuecomment-232720336>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AH7WELFhA2u_T-pH--1Ojk5R3O4O1IvEks5qVmXkgaJpZM4JKlGD>
> .
>
-- 

Signed,

Abhinav Madahar

**Comment by alonisser** [comment]
Happens to me too.. on server sides tests
