### ISSUE TITLE
meteor test --raw-logs

### ISSUE THREAD

**Issue by skeggse** [meteor/meteor#7396]
When we run our tests, we get a bunch of output like `I20160712-10:42:10.275(-7)? stdout:`. This clutters the output and makes it harder to read the test results. It'd be nice to disable this, and it seems like `--raw-logs` would work if it were supported by `meteor test`, but it looks like that option is only supported by `meteor run`. Could we add the option to the `test` command?

See also: https://github.com/meteor/meteor/issues/1551, https://forums.meteor.com/t/meteor-test-raw-logs/26361

**Comment by abernix** [comment]
This seems reasonable to me just as a matter of consistency between `meteor run` and `meteor test`.

Thanks for submitting the issue before the pull request too!  Someone from core will review it as soon as possible.
