### ISSUE TITLE
Provide a way to have async Meteor.method return values

### ISSUE THREAD

**Issue by dsummersl** [meteor/meteor#74]
Currently only straight thru method definitions are possible. Perhaps support a results callback or 'future' or 'pending' function as a return value from Meteor.method definitions. I had to roll my own using the fibers-promise package...it worked, but it'd be nice if the API already supported it.

**Comment by Xample** [comment]
Meteor call supporting callback http://docs.meteor.com/#/full/meteor_call
Making use of a promise would just do it…
something like
```js
function doStuff()
{
var promise = new Promise()
{
Meteor.call("methodName", function(error, result)
{
if (error) promise.reject(error);
else promise.resolve(result);
})
}
return promise;
}
```

Usage:
```js
doStuff().then(function(result){ /* Use the result */ })
```
PS: code not tested
My favorite package for promises is : https://github.com/meteor/promise
