### ISSUE TITLE
Not able to run "meteor mongo" in 1.3.4_4 version of meteor

### ISSUE THREAD

**Issue by DrkCoater** [meteor/meteor#7402]
I'm running Windows 7 Enterprise version

This is the error:

\AppData\Local\.meteor\packages\meteor-tool\1.3.4_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: EINVAL, invalid argument
    at new Socket (net.js:157:18)
    at process.stdin (node.js:703:19)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands.js:1153:5)
    at C:\tools\cli\main.js:1402:23

Also, meteor reset doesn't seem to clear out the database for me.

**Comment by benjamn** [comment]
What terminal program are you using? Some of them have this problem when running the Node REPL: https://github.com/nodejs/node-v0.x-archive/issues/6459

**Comment by DrkCoater** [comment]
Just the plain old cmd prompt

**Comment by DrkCoater** [comment]
Ah, right, I was using [babun](http://babun.github.io/) which is cygwin based...

**Comment by abernix** [comment]
Due to various incompatibilities with cygwin, you will need to a shell supported by Meteor: PowerShell or Windows Command Prompt.  I can confirm that `meteor mongo` does work properly on Windows with Meteor 1.3.4.4 using one of these shells.
