### ISSUE TITLE
[Package system] publish for arch can't find package.json

### ISSUE THREAD

**Issue by ichernev** [meteor/meteor#7403]
I'm trying to publish momentjs:moment@2.14.1. I did already create the package, but when I try to use the vm to publish-for-arch I get this issue:

```
% meteor admin get-machine os.linux.x86_64
...
$ meteor publish-for-arch momentjs:moment@2.14.1
=> Errors while initializing project:                                              
                                              
While reading package from `/tmp/package-sourceoj7gx/momentjs_moment`:
fs.js:439:18: ENOENT, no such file or directory 'package.json'
at Object.fs.openSync (fs.js:439:18)
at Object.fs.readFileSync (fs.js:290:15)
at package.js:6:48

error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "_".
```

My build used to work before you changed the whole process.

How do I find out which architectures are already published and which source files are published without architecture?

**Comment by benjamn** [comment]
What's on line 6 of your `package.js` file?

**Comment by abernix** [comment]
Presumably, this is the line: https://github.com/moment/moment/blob/develop/meteor/package.js#L6

**Comment by ichernev** [comment]
@benjamn that is how it was written before. Isn't package.json and the rest of the package downloaded when I say publish-for-arch? 

@abernix thanks!

**Comment by benjamn** [comment]
@ichernev does it help if you include `package.json` in your `api.addFiles` call?

**Comment by ichernev** [comment]
When I put it in `api.addFiles` in the `onUse` section, i get

```
% meteor publish         
=> Errors while initializing project:                                              
                                              
While building package momentjs:moment:
error: No plugin known to handle file 'package.json'. If you want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('package.json', 'client').
```

I guess I can try `addAssets`, but I don't want to add a client asset, because it will upset people who want to keep size down. On this page's documentation: https://guide.meteor.com/writing-atmosphere-packages.html#adding-assets, there is a link to the `addAssets`, which doesn't seem to work: http://docs.meteor.com/#/full/PackageAPI-addAssets

So I guess there is `api.addAssets(..., 'server')` which is not documented?

**Comment by ichernev** [comment]
Correction : I tried both
```
  api.addAssets('package.json', 'client');
```
 and
```
  api.addAssets('package.json', 'server');
```

And both result in the same error `ENOENT`.

NOTE: I had to bump the version 2 times because I can try only one package.js for each.

**Comment by ichernev** [comment]
OK, I put some fixed version number, removed the package.json dependency. I `meteor publish`-ed the initial version `2.14.4` from my x64 linux box, then I went on to do the other publish-for-arch commands, but only the mac one succeeded. Everything else (x64, x32 linux and windows) gave me 
```
While publishing package build for momentjs:moment:
error: Cannot override existing build
```

So it it ok now? Can I verify somehow?

**Comment by benjamn** [comment]
Yes, `error: Cannot override existing build` is usually a good sign!

After trying it just now, I can also confirm that `momentjs:moment@2.14.4` works on both of the Linux platforms, and Windows.

**Comment by abernix** [comment]
From what I understand, this issue is resolved so I'll close this.  Happy to reopen if this is not the case though!
