### ISSUE TITLE
Allow Importing CSS from NPM into Atmosphere package

### ISSUE THREAD

**Issue by tiagoporto** [meteor/meteor#7406]
I open this [issue](http://stackoverflow.com/questions/38273675/import-css-from-npm-from-atmosphere-package), but no response.

I created a meteor package, and in my package I import a NPM package, in my package I want use the CSS from this NPM Package.

```
Package.describe({
  name: "my:package",
  summary: "My User Interface package",
  version: "0.1.0"
});

Npm.depends({
  "bootstrap": "4.0.0-alpha.2"
});

Package.onUse(function(api) {
  api.versionsFrom("METEOR@1.3");
  var packages = [
    "fourseven:scss"
  ];
  api.use(packages);
   api.addFiles("main.scss", "client");
});
```

In main.scss I use
`@import "{}/node_modules/bootstrap/scss/bootstrap.scss";`
But doesn't work.

**Comment by activeperception** [comment]
Same exact issue. I've created a local package so I can only import ionic styles when platform is cordova. My package.js is very similar to yours.

**Comment by tiagoporto** [comment]
Someone?

**Comment by abernix** [comment]
Is it providing either of you any errors or just doing nothing?   Please provide errors if possible.  Have you tried both the recommended options from [this Meteor Guide section on Importing NPM styles from Packages](https://guide.meteor.com/using-npm-packages.html#npm-styles)?

And I realize it may seem simple, but building reproductions from descriptions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by tiagoporto** [comment]
Hello @abernix, thanks your attention

This is the [repository](https://github.com/tiagoporto/package-meteor-ui)

**Comment by abernix** [comment]
Sorry for the long delay in getting to this!  (I was gone for all of August and have no excuse for September).

I can confirm that the issue you're demonstrating in this repo does exist.  I _believe_ that documentation is referring to importing from `npm` packages, but not the process of importing styles from `npm`s which are inside Atmosphere packages, which I'm not sure are available in this way.

Unfortunately, further investigation is still required.

**Comment by abernix** [comment]
I've confirmed that this is not intended to work right now (not built), so I'll convert this to a feature request issue.  Normal [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) apply!

I've also opened a PR with a slight revision to the text on the Guide to make this more clear: meteor/guide#571

Thanks for filing the issue about this, originally.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20Importing%20CSS%20from%20NPM%20into%20Atmosphere%20package&body=Migrated%20from:%20meteor/meteor%237406) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by aspirinchaos** [comment]
create a **symlink** to file in the .npm folder, helps to work properly the @import
