### ISSUE TITLE
Stuck on "updating package catalog"

### ISSUE THREAD

**Issue by paralin** [meteor/meteor#7410]
With meteor 1.3.4.4 on Gentoo linux "Updating package catalog" seems to show forever. It worked fine until earlier today. How can I debug this?

**Comment by clayne11** [comment]
I'm having this as well on Mac OS X.

**Comment by benjamn** [comment]
Me too! There's honestly no way you could have debugged it, other than reporting it here (thanks!).

As of a few minutes ago, I believe the package server is back in business, after I stopped and restarted all of its containers.

**Comment by benjamn** [comment]
Try `meteor refresh` to verify it's working for you.

**Comment by paralin** [comment]
It's back up now, but it'd be nice to clarify the output a bit if it's having trouble connecting.

**Comment by citylims** [comment]
As of Meteor 1.3.4.4 I've been experiencing a lot hiccups with my builds. This being one of them. Anyone have a actual solution or resolution for this?

**Comment by pmwisdom** [comment]
+1 still happening intermittently for me.

**Comment by corphiloscience** [comment]
Experiencing the same thing. Looks like the servers down?

**Comment by stevematdavies** [comment]
Same on installations on two macs

**Comment by matinabdullah** [comment]
Same on mac
