### ISSUE TITLE
Cannot test due to HTML files in node_modules

### ISSUE THREAD

**Issue by nicocrm** [meteor/meteor#7412]
`meteor test` is giving an error when certain NPM packages are included, that have HTML files that are not parsed correctly by meteor.  One such package is [jsforce](https://github.com/jsforce/jsforce) - an HTML file in the test directory has a `DOCTYPE`.

To reproduce it on meteor (1.3.4.4):
1. meteor create jsforce-test
2. cd jsforce-test
3. meteor npm install --save jsforce
4. meteor test --driver-package practicalmeteor:mocha --port 3100

The error given is:

   While processing files with templating (for target web.browser):
   node_modules/jsforce/test/browser/client.test.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

Removing the offending file allows tests to run.

Is it possible to ignore HTML files inside of node_modules?

**Comment by abernix** [comment]
Thanks for the easy reproduction steps.  I can confirm this happens to me as well.  I've packaged this into this reproduction:

https://github.com/abernix/meteor-issue-7412

**Comment by joncursi** [comment]
Same issue here when using `nyc` and `istanbul` to generate HTML files into a `coverage/` folder. Meteor tries to load this HTML and I don't think I have the tools to be able to block that.

**Comment by hwillson** [comment]
This is no longer an issue with Meteor 1.4.2.3 (the supplied repro doesn't throw the error after updating to 1.4.2.3). Closing - thanks for reporting this originally!
