### ISSUE TITLE
Minimongo fetch very poor performance (client side)

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#7421]
Meteor 1.3.4.1 (but it most probably doesn't matter which version you use).

This is an example of a document stored in my `contacts` collection.

```
{
  "links": {},
  "givenName": "Olivia",
  "familyName": "Example",
  "emailAddresses": [
    "olivia@example.com"
  ],
  "type": "contact",
  "isTentative": true,
  "_meta": {
    // various meta data, example `createdAt`
    "createdAt": new Date("2016-07-16T05:40:36.080Z")
  },
  "_id": "7144112da7def6ae0c1dadb5"
}
```

The collection has roughly 2000 contacts. Now for some numbers:

```
console.time('fetch');
contactsColl.find({}).fetch();
console.timeEnd('fetch');
> 18ms
```

```
console.time('fetchRaw');
_.values(contactsColl._collection._docs._map);
console.timeEnd('fetchRaw')
> 0.79ms
```

Which means minimongo's fetch is **20x slower**. Which is *very* noticeable when I e.g. query the contacts to show a list of matches while user is typing.

Now, I understand `fetchRaw` doesn't actually run any query and is not reactive. But 20 times? Really?

**Comment by realyze** [comment]
Just to add some motivation behind me filing this issue: I actually had to give up on minimongo querying and use underscore to filter the list "manually". It's still much faster (cca 3-4 times) than minimongo's `fetch`.

**Comment by laosb** [comment]
You shouldn't deal with so much data on client. 2000 records on a client collection is a really rare case, but it does make sense to improve client performance.

**Comment by realyze** [comment]
Hm, what's so rare about having 2000 clients on a client? I mean, 10000 maybe but I wouldn't say 2000 is extra huge. Let's say you're doing a offline-capable Cordova app; it's pretty common to import your phone contact list. And that could easily be 1000+ people.

**Comment by abernix** [comment]
There are quite a few [MiniMongo performance issues open already](https://github.com/meteor/meteor/labels/Project:Minimongo).  I think #5678 and related cover the problem(s) already.  Closing as duplicate.

**Comment by realyze** [comment]
Fair enough, thanks. (But FTR - this one is not about indexing, more like slow transformations of data when fetch does its thing.)
