### ISSUE TITLE
[1.3.4.4] Meteor shell command does not work

### ISSUE THREAD

**Issue by s-devaney** [meteor/meteor#7423]
Since upgrading to 1.3.4.4 the `meteor shell` command fails with the following error:
`Server unavailable (waiting to reconnect)`

I'm using Windows 10

**Comment by walliski** [comment]
Do you have a meteor instance running in another window? Works well for me on Windows 8.1.

**Comment by abernix** [comment]
It also works fine for me on Windows 10 enterprise using 1.3.4.4.  Make sure you:

* Use a supported shell: Windows Command Prompt or Windows PowerShell
* Have your Meteor project actually running in the first window.
* Are running `meteor shell` from the **same project directory** in another Window.
