### ISSUE TITLE
JSON parse error when HTML tags are not self-enclosed

### ISSUE THREAD

**Issue by sunlee-newyork** [meteor/meteor#7426]
Issue #3230 was reporting a JSON parse error for Cordoba, but I was able to reproduce it on a browser.

Error message:
> Uncaught Error: SyntaxError: JSON Parse error: Unrecognized token '<':2083:http://meteor.local/packages/ddp.js?1f971b2ac9f4bdab7372cb5098ed1e26ff98dfb2

I had the same issue with a skeleton architecture (barely started) and the error went away when I added the forward slash to close off my meta tags in my main.html:

```html
<head>
	<meta charset="utf-8">
	<title>Shop Chop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<body></body>
```
turned into 
```html
<head>
	<meta charset="utf-8" />
	<title>Shop Chop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
</head>

<body></body>
```

**Comment by laosb** [comment]
Could you please simply refresh the web to see what has happened? I guess it just because this triggered a build error when compiling the template.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
