### ISSUE TITLE
[1.4] Downloading templating@1.1.14... stuck for over 3 hours

### ISSUE THREAD

**Issue by Dielz98** [meteor/meteor#7430]
Tried `meteor create --release 1.4-beta.14 myapp`

And `Downloading templating@1.1.14...` stuck for over 3 hours.

I have retried 3 times.
I don't have issue with meteor-tools. It's already dowloaded quite fast.

OS: OSX 10.11

**Comment by abernix** [comment]
You can Ctrl-C it and stop it.

I'd like to capture the state of your `$HOME/.meteor` project directory and take a look at it on my own development machine to try (hopefully!) debugging and see where it's stuck.  If you can provide it by running this command:

    tar cvf - $HOME/.meteor | gzip -9c > ~/meteor_backup.tar.gz

It should create a (possibly very large) tarball in your home directory called `meteor_backup.tar.gz`.  If you could provide me with a (Dropbox, maybe?) link, it'd be much appreciated.  It should not contain any sensitive information, but feel free to private message me the link in [Meteor Forums](http://forums.meteor.com) messaging if you don't feel comfortable posting it here. (I'm also @abernix on there)

**Comment by Dielz98** [comment]
I don't mind share it. But uploading such giga file, I'm sorry. Maybe other way I could help you?

**Comment by abernix** [comment]
The entire directory provides the best opportunity to find the problem.  If uploading a file of that size is a problem, I could try with something smaller, like:

    tar cvf - -C $HOME .meteor/package-metadata .meteor/packages/templating | gzip -9c > ~/meteor_backup.tar.gz

**Comment by Dielz98** [comment]
100 mb https://www.dropbox.com/s/gpvb4vl7qcsiaqg/meteor_backup.tar.gz?dl=0

**Comment by abernix** [comment]
Thanks.  I'll take a look and hopefully that'll be enough.  If you run `meteor --version` outside of a project directory, what version does it give you?  I'll need this to test accurately.

**Comment by Dielz98** [comment]
You mean ~/ directory?

**Comment by Dielz98** [comment]
It give me `Downloading meteor-tool@1.3.4_4...`

**Comment by abernix** [comment]
Can you give me the output of the following two commands?

* `ls -l ~/.meteor/meteor`
* `ls -l ~/.meteor/packages/meteor-tool`

**Comment by Dielz98** [comment]
```
users-MacBook-Pro:~ user$ ls -l ~/.meteor/meteor
lrwxr-xr-x  1 user  staff  50 Jul 12 11:10 /Users/user/.meteor/meteor -> packages/meteor-tool/1.3.3/mt-os.osx.x86_64/meteor

users-MacBook-Pro:~ user$ ls -l ~/.meteor/packages/meteor-tool
total 88
lrwxr-xr-x  1 user  staff  53 Sep 25  2015 1.0.38 -> .1.0.38.3jsjn3++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  53 Sep  4  2015 1.0.40 -> .1.0.40.lwj4yd++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  53 Oct 29  2015 1.1.10 -> .1.1.10.7odh2t++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  69 Feb 27 06:59 1.1.11-faster-rebuild.0 -> .1.1.11-faster-rebuild.0.zz82r++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  52 Sep 15  2015 1.1.3 -> .1.1.3.dzw9kd++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  52 Aug  4  2015 1.1.4 -> .1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  52 Sep 22  2015 1.1.8 -> .1.1.8.18mqmp++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  53 Sep 29  2015 1.1.9 -> .1.1.9.1f0n2l1++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  52 Apr 20 09:58 1.3.1 -> .1.3.1.c1j3a6++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  52 Jul 11 05:36 1.3.3 -> .1.3.3.v3alnf++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x  1 user  staff  60 Jul 18 11:03 1.4.0-beta.14 -> .1.4.0-beta.14.phy08j++os.osx.x86_64+web.browser+web.cordova
```

**Comment by abernix** [comment]
Will you try running these two commands:

0. `mv ~/.meteor/package-metadata/v2.0.1/packages.data.db ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu`
0. `sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu ".dump" | sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db`

Then try running `meteor --version` and see what happens.  If it runs successfully, try creating a project with `meteor create --release 1.4-beta.14 myapp` again.

**Comment by maxnowack** [comment]
I don't know if this has a similar origin, but today my 1.4 app stuck at `Starting your app`.
It works after I've downgraded to 1.3

**Comment by abernix** [comment]
@maxnowack Not likely related.  If you can make a reproduction, please open a new issue.

**Comment by Dielz98** [comment]
@abernix 
Same. It give me Downloading meteor-tool@1.3.4_4...

**Comment by abernix** [comment]
Is it actually downloading, or is it just stuck?

**Comment by Dielz98** [comment]
Stuck without progress

**Comment by Dielz98** [comment]
Oh sorry it's downloading now

**Comment by Dielz98** [comment]
Should I wait until it finished?

**Comment by abernix** [comment]
Yes, please allow it to download and finish and let's see what happens.

**Comment by Dielz98** [comment]
Anyway, what did you do with this:
```
mv ~/.meteor/package-metadata/v2.0.1/packages.data.db ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu
sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu ".dump" | sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db
```

**Comment by Dielz98** [comment]
Now it's stuck at 34%

**Comment by Dielz98** [comment]
This could be network error

Can I revert this:

```
mv ~/.meteor/package-metadata/v2.0.1/packages.data.db ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu
sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db.bu ".dump" | sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db
```

**Comment by abernix** [comment]
If it's stuck _during_ the download then it's likely due to a network failure and something that #7267 should fix but won't be released until 1.3.5.  If it's stuck for you right now, Ctrl-C and retry again.  Let's try to get that past 100%!

The `mv` and `sqlite3` command I gave you is to rebuild what I found to be a corrupt SQLlite database in the tarball that you sent me.  Let's leave that alone for now.

**Comment by Dielz98** [comment]
@abernix 
Can we download from github? This should faster

Meteor-tool located on `.meteor/packages/meteor-tool`

Can we just download from github and put it on that folder?

**Comment by abernix** [comment]
Will you try the instructions [in this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-226641013) about updating your `hosts` file to use a different CDN server?

**Comment by abernix** [comment]
Meteor 1.3.5.1 is now recommended and it does contain some fixes for various downloading issues and is highly recommended if you're attempting to test out Meteor 1.4.  I might recommend a fresh install of Meteor by simply running:

    curl https://install.meteor.com | sh

Please report back how it works for you!
