### ISSUE TITLE
[windows] Wix installer should call WixBroadcastEnvironmentChange

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#7431]
This looks like a potential solution for requiring Windows users to restart after installing Meteor and confusion over the `meteor` command not working after installation as in #7322 & #4090.

See [Wix documentation here](http://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html) which says specifically:

> Windows Installer itself sends the WM_SETTINGCHANGE message for settings it changes while processing an MSI package but cannot do so for changes a package makes via custom action. Also, Windows Installer does not send WM_SETTINGCHANGE for environment variable changes when a reboot is pending.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bwindows%5D%20Wix%20installer%20should%20call%20WixBroadcastEnvironmentChange&body=Migrated%20from:%20meteor/meteor%237431) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
