### ISSUE TITLE
[1.3.5.1 Windows] `Cannot call method 'join' of undefined` on run

### ISSUE THREAD

**Issue by adam-m-denny** [meteor/meteor#7439]
After meteor tool updated to 1.3.5_1 in Windows, meteor won't start at all. I've tried uninstalling and reinstalling Meteor with the installer. The error even prevents me from rolling back meteor to a previous version via cmd, running any project, or running meteor create to start any new project. Here's the output: 

```
C:\Users\Adam\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
TypeError: Cannot call method 'join' of undefined
    at Table._generateQuestionMarks (C:\tools\packaging\catalog\catalog-remote.js:435:57)
    at Table._buildStatements (C:\tools\packaging\catalog\catalog-remote.js:425:28)
    at new Table (C:\tools\packaging\catalog\catalog-remote.js:418:8)
    at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:696:26)
    at C:\tools\cli\main.js:763:20
```

Any ideas? I can't seem to get around this one.

Edit: I copied in 1.3.3_1 and modified meteor.bat to run this version instead because the meteor command wasn't working for anything, and I'm getting the same issue, and I haven't added any packages since the update.

**Comment by benjamn** [comment]
It looks like somehow the Underscore method `_.times` is returning undefined. Maybe `underscore` is corrupted? Try removing `C:\Users\Adam\AppData\Local\.meteor\packages\underscore` and running meteor again?

**Comment by adam-m-denny** [comment]
Removed underscore and underscore-tests and there was no change, same exact error msg.

**Comment by adam-m-denny** [comment]
Replaced the _generateQuestionMarks function with this: 

```
  _generateQuestionMarks: function _generateQuestionMarks(n) {
    // return "(" + _.times(n, function () {
    //   return "?";
    // }).join(",") + ")";
    var q = [];
    for(var i = 0; i < n; ++i){
      q.push("?");
    }
    return "(" + q.toString() + ")";
  },
```

and it stops throwing the original error and proceeds.

**Comment by cheqitout-dev** [comment]
Okay so an npm package has included an old version of underscore.js that is missing those calls and meteor is using the old package I've included somewhere rather than the version Meteor uses to build and Meteor is using the old version. Once I dig out wherever I've installed the bad version I think it should clear up.

**Comment by adam-m-denny** [comment]
It's pulling an old version of underscore from an npm package dependency somewhere and using that to start meteor instead of the one that's packaged with meteor. I'll see if I can't figure out what version of underscore it's using and remove it.

**Comment by marcianosr** [comment]
Any progress on this? I'm getting the same error...

**Comment by abernix** [comment]
Closing this as if the old version situation gets resolved this should work properly.

@marcianosr Perhaps you can elaborate on how you specifically found the problem to help others.

**Comment by marcianosr** [comment]
I fixed this problem by deleting the underscore package in my global node_modules folder. It seems that Meteor is using the package of underscore out of the node_modules folder which is not working with meteor.
