### ISSUE TITLE
[1.3.4.2] --mobile-server works differently

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#7452]
Seems that from 1.3.4.2 `--mobile-server` which functioning was restored here https://github.com/meteor/meteor/issues/6862 works differently.

I might have missed some issue changing it, but I do not see that mentioned in history.

After running `meter --mobile-server=http://127.0.0.1:3000` I can see that `.meteor/local/cordova-build` is created but the `.meteor/local/cordova-build/www` is empty.

One of my projects totally depends on how it was working - I am taking the contents of cordova-build/www for further modifications.

**Comment by wojtkowiak** [comment]
Oh I have found it: https://github.com/meteor/meteor/commit/238623ca74873a4882d332d9bbafb9d539a64754
So it seems that `build/programs/web.cordova` is built but it is not copied to `cordova-build/www`.
Also it lacks index.html which I actually need the most.

**Comment by wojtkowiak** [comment]
This can be closed. I have changed my https://github.com/wojtkowiak/meteor-desktop to download the missing files from running projects - I guess I can live with that :wink:

**Comment by abernix** [comment]
@wojtkowiak Thanks for following up on this.  Our of curiosity, did you find this behavior to be any different with Meteor 1.4.2 (which updates Cordova to 6.2)?

I'd love to have been able to help figure out the problem here, but strangely, it didn't seem to be breaking anything and I'm not familiar with the Cordova side of this. 😕

**Comment by wojtkowiak** [comment]
Generally I was depending on behavior others were complaining about 😉 

For quite some time `--mobile-server` did not work at all and was restored here https://github.com/meteor/meteor/issues/6862 - but with building `web.cordova` it was also building cordova project in `local/cordova-build`.
I was benefiting from that fact, because `cordova-build/www` has the full app with the index.html generated from the boilerplate and `program.json` has `version` property computed. And that is exactly what I need for further processing in `meteor-desktop`.

`--mobile-server` - should generally enable HCP, and for that there is no need to even make a cordova project, install plugins etc - and that is what people were complaining so Martin have changed the behavior here https://github.com/meteor/meteor/commit/238623ca74873a4882d332d9bbafb9d539a64754 making my life miserable :wink:

In general I did not want to generate the `index.html` myself (even if others do so, for instance https://github.com/frozeman/meteor-build-client/blob/master/meteor.js#L96)

I have managed to work it out, by just querying a running project for the files I've missed in the `web.cordova`. (you can just query the cordova HCP endpoint like http://127.0.0.1/__cordova/index.html, http://127.0.0.1/__cordova/manifest.json to get what is not present in `web.cordova`).
