### ISSUE TITLE
Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7453]
My app is at 1.2, and then I run `meteor` from the git checkout, which is 1.3.5.1, I always got this:

(It's a little bit weird that I can use the official bundled meteor 1.3)

```
   npm ERR! Darwin 15.5.0
   npm ERR! argv "node" "/Users/c9s/src/work/kaneoh/meteor/meteor/dev_bundle/bin/npm" "rebuild" "--no-bin-links"
   "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
   npm ERR! Exit status 8
```

It shows the log file here:

```
/Users/c9s/src/work/kaneoh/meteor/meteor/.meteor/packages/fourseven_scss/.3.4.1.vccdt3++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/compileScssBatch/node_modules/.temp-skuo29/npm-debug.log
```

but when I cat this file, it's already removed.

**Comment by c9s** [comment]
I know it probably related to the local installed node or npm. I tried this:

     PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin" ~/work/kaneoh/meteor/meteor/meteor run ...

And here is the related information:

    /opt/local/bin/node
    /opt/local/bin/node-gyp
    /opt/local/bin/node-pre-gyp

**Comment by c9s** [comment]
I also chowned the ~/.node-gyp but it doesn't work.

I guess it's because the bundler/installer uses node v0.10.46?

**Comment by abernix** [comment]
I would suggest reading https://github.com/meteor/meteor#slow-start-for-developers and ensuring that you have the [proper requirements for `node-gyp` on your operating system](https://github.com/nodejs/node-gyp#installation) (on Mac this mean XCode + Command Line Tools and Python 2.7, but not 3.0!).

**Comment by c9s** [comment]
Does the first line related to this issue?

```
=> Running Meteor from a checkout -- overrides project version (Meteor 1.2.1)
```

**Comment by abernix** [comment]
You might also want to try a more stable branch: `release-1.3.5`, for example.

The message about running from a checkout is just how running from a checkout works.  It's unreleased code so if you want to run and work on a particular branch, you would need to check out that particular branch and you need a dev_bundle to match (downloaded automatically if you don't have it already).

To run your own app with it, you would just run the following from inside your app:

```sh
your-app-directory $ /Users/youruser/Path/To/Checkout/meteor/meteor run
```

**Comment by c9s** [comment]
Yes, I checked out:

```
git checkout release/METEOR@1.3.5.1
```

And I ran the meteor inside my app:

```
~/work/kaneoh/meteor/meteor/meteor run
```

Is it related to the .meteor/versions ? for example, fourseven_scss was locked at some specific release?

**Comment by c9s** [comment]
Same result as I checkout the `git checkout -t origin/release-1.3.5` branch.

**Comment by abernix** [comment]
Is that the whole error message?  Perhaps you could try generating a dev bundle and see what happens?

```sh
meteor $ # (from within the `meteor` checkout)
meteor $ ./scripts/generate-dev-bundle.sh
```

Also, I might just suggest deleting the entire contents of your `~/.node-gyp` directory as I have ran into problems with that in the past.

**Comment by c9s** [comment]
a new try:

I updated .meteor/version fourseven:scss@3.4.1 to fourseven:scss@3.4.3,

And I've also delete the whole `~/.node-gyp`.

still the same result.

I am trying to run `./scripts/generate-dev-bundle.sh`

**Comment by c9s** [comment]
Here is the whole message:

```
=> Running Meteor from a checkout -- overrides project version (Meteor 1.2.1)
[[[[[ ~/src/work/kaneoh/shaka/app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package fourseven:scss@3.4.1:
   error: Command failed:
   module.js:340
   throw err;
   ^
   Error: Cannot find module '../'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/c9s/src/work/kaneoh/meteor/meteor/.meteor/packages/fourseven_scss/.3.4.1.vccdt3++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/compileScssBatch/node_modules/.temp-1mrh299/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)

   npm ERR! Darwin 15.5.0
   npm ERR! argv "node" "/Users/c9s/src/work/kaneoh/meteor/meteor/dev_bundle/bin/npm" "rebuild" "--no-bin-links"
   "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
   npm ERR! Exit status 8
   npm ERR!
   npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the thread-sleep package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-pre-gyp install --fallback-to-build
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs thread-sleep
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls thread-sleep
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/c9s/src/work/kaneoh/meteor/meteor/.meteor/packages/fourseven_scss/.3.4.1.vccdt3++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/compileScssBatch/node_modules/.temp-1mrh299/npm-debug.log
```

**Comment by c9s** [comment]
@abernix I ran generate-dev-bundle successfully without any error message.

**Comment by c9s** [comment]
If I simply run npm install node-sass, it installs node-sass without any error.

`npm install -g node-sass`

**Comment by c9s** [comment]
do you use npm3 in your local? or just npm2? is that related?

**Comment by abernix** [comment]
There are bugs in fourseven:scss@3.4.1 that prevent it running on Meteor 1.3.5 or higher.  Please search recent issues.

> It's a little bit weird that I can use the official bundled meteor 1.3

If you mean that you can run your project by just running `meteor`, you actually are NOT running your project with Meteor 1.3 – you are running your project with Meteor 1.2.  You should upgrade your own project by running `meteor update --release 1.3.5.1` (the bundled `meteor`, NOT the checkout) and _then_ try running it with the checked out `meteor` tool.

**Comment by abernix** [comment]
Additionally, you should make sure your project **runs** with the bundled Meteor after running `meteor update` before trying to make changes to the `meteor` tool. :smile:

**Comment by c9s** [comment]
@abernix Thank you for the patience. I will try that tomorrow. Thanks!

**Comment by c9s** [comment]
It's 1AM here, I have to sleep. Have a nice day!

**Comment by c9s** [comment]
Upgraded scss to 3.8 and it works thanks!
