### ISSUE TITLE
Meteor app stuck at installing cordova plugin from plugin registry

### ISSUE THREAD

**Issue by array-addu** [meteor/meteor#7454]
I have upgraded my application to 1.2.1, when running meteor run iOS app sucks at downloading 
com.ionic.keyboard@1.0.4 every time. I haven't added this plugin though and i tried to remove it but i can't and also i tried to upgrade it to latest version but still cordova fetches this specific version and haults the app.
 > Adding plugin com.ionic.keyboard@1.0.4 to Cordova project
% Fetching plugin "com.ionic.keyboard@1.0.4" via npm                              
% Fetching plugin "com.ionic.keyboard@1.0.4" via cordova plugins registry         
=> Errors executing Cordova commands:                                             
                                                                                  
   While adding plugin com.ionic.keyboard@1.0.4 to Cordova project:               
   Cordova error: CordovaError: Failed to fetch plugin com.ionic.keyboard@1.0.4   
   via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: connect ETIMEDOUT
   at registry.fetch.fail.then.pinfo

**Comment by abernix** [comment]
I was able to add this plugin to a project of my own with no issue:

```sh
$ meteor add cordova:ionic-plugin-keyboard@1.0.4
Added Cordova plugin ionic-plugin-keyboard@1.0.4
$
```

Therefore, this sounds like a connectivity problem or a (temporary or geographical) issue with the NPM registry.  Please check your Internet connection and maybe try:

```
meteor update cordova:ionic-plugin-keyboard
```

Alternatively, please reproduce this problem in a fresh Meteor project and include a link to a GitHub repro where someone can run it and experience the same problem.

Closing as I believe this to be a temporary problem but happy to reopen if you can provide additional information, a GitHub repo showing the problem or repro steps on a new project.

**Comment by array-addu** [comment]
Hello abernix,
There is no problem with the internet connection. the problem arises when i updated the meteor to version 1.2.1, previously all was working fine. i think the problem is with cordova update with meteor 1.2.1 as with some research i found out that  plugin `com.ionic.keyboard` was on cordova plugin registery and now the plugin is moved to npm with different name `ionic-plugin-keyboard` which and meteor is fetching this plugin from npm which is not there hence giving the error. So it treats `ionic-plugin-keyboard` as a different plugin, hence updating this plugin doesn't solve the problem. I don't know how to override the the previous plugin name with the latest one or how to fetch the plugin from cordova plugin registry.
and the output of `meteor npm config get registry` is `https://registry.npmjs.org/`.

**Comment by abernix** [comment]
`ionic-plugin-keyboard` is on NPM and works properly.  If Meteor is trying to install `com.ionic.keyboard` then there is must be a dependency in your project on this still.  Have you confirmed that all other plugins you are using have been updated to use the new name?

But again, can you please provide a basic reproduction?  If you can't provide a reproduction, this issue will need to be closed.  You should copy your current project and remove major portions until you can't remove anything else and you still experience this issue.

Also, Meteor 1.2.1 is using Cordova 5.  Have you considered upgrading to Meteor 1.3.5.1 which uses Cordova 6?

**Comment by array-addu** [comment]
> ionic-plugin-keyboard is on NPM and works properly. If Meteor is trying to install com.ionic.keyboard then there is must be a dependency in your project on this still. Have you confirmed that all other plugins you are using have been updated to use the new name?

I've checked there is no dependency on this plugin and i haven't used any plugin so there is no dependency on any other plugin.

> But again, can you please provide a basic reproduction? If you can't provide a reproduction, this issue will remain closed. You should copy your current project and remove major portions until you can't remove anything else and you still experience this issue.

[Here](https://github.com/array-addu/ionicKeyboard) is a link to basic reproduction of the project. You can replicate the issue by running 

> meteor run ios --verbose  command.

> Also, Meteor 1.2.1 is using Cordova 5. Have you considered upgrading to Meteor 1.3.5.1 which uses Cordova 6?

I've upgraded this project to 1.3.2.4 and the problem still persists and updated cordova version to 6.

**Comment by array-addu** [comment]
Hello abernix, did you find any success in replicating the issue?

**Comment by abernix** [comment]
Thanks very much for the repro repo.  Maybe someone else can take a look?  If not, I'm real busy at the moment but hopefully on Monday!  Not forgotten! ;)

**Comment by abernix** [comment]
>> ionic-plugin-keyboard is on NPM and works properly. If Meteor is trying to install com.ionic.keyboard then there is must be a dependency in your project on this still. Have you confirmed that all other plugins you are using have been updated to use the new name?

> I've checked there is no dependency on this plugin and i haven't used any plugin so there is no dependency on any other plugin.

What about `meteoric:ionic` – a package that you are using directly in your app?  It has a direct dependency on `com.ionic.keyboard`.  In fact, you can see in this commit that they have fixed the issue in a newer version: https://github.com/meteoric/meteor-ionic/commit/d187d66f111b3d57521906bfb9e86832dd20869d

I ran this and _that_ problem went away:

    meteor update meteoric:ionic meteoric:ionic-sass meteoric:ionicons-sass

However, I will not that almost every package you are using has updates pending:

```
$ meteor list
accounts-password              1.1.8* Password support for accounts
aldeed:autoform                4.2.2* Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2             2.3.3* Automatic validation of insert and update operations on the client and server.
amdingo:lettering-js           1.0.3   /* Lettering.js for Meteor */
blaze-html-templates           1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
check                          1.2.1* Check whether a value matches a pattern
cordova:ionic-plugin-keyboard  2.2.1
d0minikk:materialize-meteor    1.95.1  A modern responsive front-end framework based on Material Design
dandv:jquery-rateit            1.0.22_2  RateIt - a modern, mobile-friendly, jQuery (star) rating plugin
ecwyne:mathjs                  2.4.0* Mathjs, An extensive math library for JavaScript, packaged for Meteor. See http://mathjs.org.
ejson                          1.0.11* Extended and Extensible JSON library
fortawesome:fontawesome        4.4.0* Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
gildaspk:autoform-materialize  0.0.6* Materialize theme for Autoform
grigio:materialize-sass        0.0.4  Materialize scss theme
gwendall:body-events           0.1.6  Get Template.body.events() working
iron:router                    1.0.7* Routing specifically designed for Meteor
jquery                         1.11.8* Manipulate the DOM using CSS selectors
keryi:meteor-dcaccordion       1.0.3  Design Chemical's jQuery vertical accordion
launch-screen                  1.0.11* Default and customizable launch screen on mobile.
logging                        1.0.12* Logging facility.
maazalik:highcharts            0.4.0  HighCharts for Meteor, with an easy to use helper to get you started!
maazalik:highcharts-gauge      0.4.0  HighCharts gauge for Meteor
manuelschoebel:wait-on-lib     0.3.0  Use Meteor Iron-Routers waitOn to load external javascript
materialize:materialize        0.96.1* Materialize (official): A modern responsive front-end framework based on Material Design
mdg:camera                     1.1.5* Photos with one function call on desktop and mobile.
mdg:reload-on-resume           1.0.4  On Cordova, only allow the app to reload when the app is resumed.
meteor-base                    1.0.4  Packages that every Meteor app needs
meteoric:autoform-ionic        0.1.5* Ionic theme for Autoform
meteoric:ionic                 0.1.17* Ionic components for Meteor. No Angular!
meteoric:ionic-sass            0.1.9* Ionic's CSS Framework in SASS and bundled for Meteor.
meteoric:ionicons-sass         0.1.6* Ionic's Ionicons library in SASS and bundled for Meteor.
mfpierre:chartist-js           1.6.0* Simple responsive charts
mobile-experience              1.0.4  Packages for a great mobile user experience
momentjs:moment                2.8.4* Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                          1.1.7* Adaptor for using MongoDB and Minimongo over DDP
pascoual:pdfjs                 1.1.114  PDF rendering for your Meteor application (client only)
raix:push                      2.6.12* Isomorphic Push notifications for APN and GCM
random                         1.0.9* Random number generator and utilities
reload                         1.1.8* Reload the page while preserving application state.
reywood:iron-router-ga         0.6.1* Google analytics (universal edition) with some Iron Router sugar for tracking page views.
richsilv:owl-carousel          0.1.0  Touch enabled jQuery plugin that lets you create a beautiful responsive carousel slider.
session                        1.1.5* Session variable
shake:shake                    0.2.0  Detect shake events in mobile browsers or Cordova apps
spacebars                      1.0.11* Handlebars-like template language for Meteor
standard-minifier-css          1.0.6* Standard css minifier used with Meteor apps by default.
standard-minifier-js           1.0.6* Standard javascript minifiers used with Meteor apps by default.
tracker                        1.0.13* Dependency tracker to allow reactive callbacks
useraccounts:materialize       1.12.0* Accounts Templates styled for Materialize Css.
```

I'm getting another error now on `cordova-plugin-shake`  – but the idea is the same.  That dependency is being provided by the `shake:shake` package which has not changed [it's own dependency](https://github.com/dandv/meteor-shake/blob/master/package.js#L10).  The Cordova plugin IDs have changed (this is NOT Meteor's fault in any way – Cordova changed the way they did things) and your project will need to be updated.

This is not a Meteor bug.

**Comment by array-addu** [comment]
Thanks @abernix  for pointing out the exact cause of the problem. After updating the packages the issue is resolved.
