### ISSUE TITLE
build tool optimization: _.each is bailing out in v8 optimization

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7465]
This is related to  #6058
## Why is the linker so slow?

To process the files and linking, I saw the linker reads the files and split the lines, use js analyze to analyze the global variable assignments.

However, the source files could be thousands, and each file might contains 100+ lines or more, 1000+ symbols ... and so on.

And so, the big O of processing the symbols, as you can imagine, could be something similar to `O( files * lines * symbols )`.
## One of the reasons

The underscore functions are actually not optimized by V8, if you run `--trace_opt --trace_deopt` on the underscore:

```
node --trace_opt --trace_deopt --allow-natives-syntax underscore.js
```

you will find almost all `_.{anonymous function}` are not optimized into native code via v8's JIT compiler.

see the gist here https://gist.github.com/c9s/f8dc64cd713fc9123bcd870b9b6dac5b
## Suggestion

I understand the `_.each` provides polymorphism and readability, however it's causing the whole function calling `_.each` not being optimized. (V8 optimizes the functions as it's unit)

Hence the `_.each` used in the critical section like linker.js, bundler.js, package-source.js should be rewritten to a native javascript for loop (`forEach` is also slower than a normal `for` loop).

However this is just the first step to optimize the code, we need to remove all polymorphic functions (or rewrite) with monomorphic functions.     (most of polymorphic functions can't be optimized by V8)
#7449 is what I've done, you can see the actual result there, I will break the changes into separate PRs later.

**Comment by laosb** [comment]
Is it worthwhile to do so as we lose much readability, maintainability and  furthermore?

**Comment by laosb** [comment]
@c9s I think you should provide detailed data about how this change would benefit developers in speed.

**Comment by c9s** [comment]
you can check the benchmark result here

https://github.com/meteor/meteor/pull/7449

**Comment by laosb** [comment]
@c9s I mean only **this** change. The result you provided in #7449 sounds like the effect of all your changes.

**Comment by vlasky** [comment]
@c9s - does [lodash's implementation](https://github.com/lodash/lodash) also suffer from this optimization problem?

**Comment by benjamn** [comment]
@c9s This is exactly the kind of issue I was hoping for. Thanks for taking the time to write it up :)

I wonder if there's any way to get V8 to optmize the `underscore` (or possibly `lodash`) API, so that we can keep the readability…

**Comment by c9s** [comment]
@vlasky There are many functions used in lodash being optmized. lodash is even better than underscore.

@benjamn  I think we can still keep the readability, we just need to write some monomorphic functions like `each`, `map`. because `_.each` accepts both Object and Array, it's hard to be optimized by V8.

**Comment by vlasky** [comment]
Thanks @c9s.

I strongly support the MDG replacing underscore in Meteor's core with lodash, or at least providing a mechanism to allow the user to do it easily.

I'm not the only one who wants this:

[Investigate swapping Underscore w/ Lo-Dash or upgrading Underscore #1009](https://github.com/meteor/meteor/issues/1009)

**Comment by c9s** [comment]
I am actually fine with this. but before that, we can use jsperf.com to see what's the difference. (however jsperf.com is down for now... *sad*)

**Comment by abernix** [comment]
Now that Meteor 1.4 is out with Node 4, it might be feasible to start profiling these things more effectively.  In regard to `jsperf`, I'm currently running it locally: https://github.com/jsperf/jsperf.com#how-to-run-a-local-copy-of-jsperf-for-testingdebugging and it works well.

My problem with micro optimizations like this (like replacing underscore's `_.each` is that they sacrifice readability/portability for a short period of time until the various engines (e.g. SpiderMonkey, v8) catch up.  It's generally a game of one method hopping over the other.  In May, I heard that lodash `_.map` was the fastest iteration implementation, but who knows how long this will last?

As @laosb already asked, I'm still curious to see benchmarks for just this single change.  Based on your other benchmark, the increase in speed was only around 5% which I'd argue isn't enough to sacrifice readability (or even the risk in making all the changes).

> I strongly support the MDG replacing underscore in Meteor's core with lodash, or at least providing a mechanism to allow the user to do it easily.

Really this should have zero affect on the user and there is no reason to allow the user a mechanism to do it.  Despite the similarities, the two libraries are not interchangeable.  Users are, of course, free to use whatever package they like in their own project, especially with 1.3 module support.

That said, I do think the gradual transition to lodash is a good idea – though ES6 does offer some native functions that should be explored (read: benchmarked) first.  It would be best to use native functions as they will benefit the most as v8/node evolves. Specifically, I think that slowly starting to plug in various lodash modules (not the entire library) would be a good way to start down this road.  Not only might there be some compilation optimizations (like this issue), but Meteor might even end up with a smaller overall footprint by only picking the functions it needs.

**Comment by vlasky** [comment]
@abernix I'll level with you. We are using meteor for real-time GPS tracking. Our goal is to be able to handle as many connections/sessions as possible on a single node instance.

The main part of the meteor code which I would want to run faster is the communications layer, e..g ddp-server. I see it has lots of loops that use various underscore loop functions e.g. _.each(), _.find(), _.contains(), _.all()

I'd like you to humor us by doing whatever benchmarks you plan using lodash's equivalents for these: _.each(), _.find(), _.contains() and _.every(). If that's too much, then just benchmark with _.each(). 

This may seem like a micro optimization, but when performed repetitively, it quickly adds up and becomes a macro optimization. Yes, the V8 optimizer will eventually improve, but why should we endure an indefinite period of sub-optimal performance when we may have a candidate solution on hand - lodash?

**Comment by abernix** [comment]
@vlasky Well, _I'm_ not currently planning on doing any benchmarks.  I'd love to, but I just don't have time.  (I have job and doing Meteor issue triage is taking up any spare time I have).

That being said, my last paragraph says pretty clearly that I think `lodash` might be worth a go.  There is a happy middle-ground between "absolute fastest" and "maintainable" code, but benchmarking is the only way to decide what to replace at what cost.  Someone in a position to benchmark it should test this and I was asking @c9s to provide that as he was directly working on it/had interest in getting performance increases.  If this is something you need, perhaps you should indulge as well.

**Comment by vlasky** [comment]
@abernix ok I will indulge :-)

**Comment by c9s** [comment]
FYI: https://top.fse.guru/nodejs-a-quick-optimization-advice-7353b820c92e#.6ynqk2z5a

**Comment by c9s** [comment]
@abernix to me, it's just a small step to improve the performance. Optimize `each` is the precondition to let V8 optimize the whole function, it's not just for `each` and `map`.

The builder is now really slow because the functions used inside the builder are too dynamic, too big to optimize, thus the whole parent function is not optmized.

**Comment by zeroasterisk** [comment]
can we `import` lodash into just these few builder files, and re-profile?

**Comment by laosb** [comment]
Sounds like a good way to try.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=build%20tool%20optimization%3A%20_.each%20is%20bailing%20out%20in%20v8%20optimization&body=Migrated%20from:%20meteor/meteor%237465) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
