### ISSUE TITLE
build tool optimization: reducing source map files

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7466]
This is related to  #6058

the source map processing is really slow, because it requires the bundler to process each line of the code and split the symbol into symbol trees.

my question is, do we really need source map files for all server side code?

If you use `find APP/.meteor -type f -iname "*.map`, you will find there are so many backend side files with .map files. (like 300+ files)

and some files are especially really large (I can see 228065+ words in one file), for example:

```
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/babel-compiler.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/babel-runtime.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/blaze-tools.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/caching-compiler.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/caching-html-compiler.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/compileTemplatesBatch_plugin.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/ecmascript-runtime.js.map
.meteor/local/isopacks/templating/plugin.compileTemplatesBatch.os/packages/ecmascript.js.map
```

I think we need some option or environment variable to turn the server side source map off,
what do you think?

**Comment by laosb** [comment]
Can have an option, but it wasn't worthy, as you may need to analyze the stack trace.

**Comment by laosb** [comment]
Anyway, not all of them are useful for normal development.

**Comment by c9s** [comment]
As now I can see babel related packages have large source maps, and I think we can just ignore them.

**Comment by laosb** [comment]
I guess generating these files was done before building your app. They were generated when the package was built?

**Comment by c9s** [comment]
It depends, for now, I can see the startup time is also too long...

I think it will be usefull if we can ignore building sourcemap for some
packages.


Wexpo Lyu <notifications@github.com> 於 2016年7月24日 星期日寫道：

**Comment by laosb** [comment]
Well, these source maps was built in the process before publishing the package I think, so it may not affect startup time in the way you mentioned.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=build%20tool%20optimization%3A%20reducing%20source%20map%20files&body=Migrated%20from:%20meteor/meteor%237466) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
