### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by IvanPortfolio** [meteor/meteor#7467]
As for me it would be really nice to add official support for typescript. There are several packages for this, but some of them are obsolete and some are not much relieble.

It is really hard to develop a big and bugless application without static types.

**Comment by birkskyum** [comment]
I have looked for official TS support too, but it's actually quite easy to get up and running in a reliable way already. I wrote a small guide in the forum a few weeks ago, and it's still up to date:

https://forums.meteor.com/t/feature-request-support-typescript-out-of-the-box/25244/28

I would have added the the 'feature' label, but I'm not set up for issue triaging yet.

**Comment by abernix** [comment]
This actually doesn't meet the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) as it _can_ be implemented entirely as a third-party package.  (Unless I'm missing something?).

I think a first step for better integration would be getting some recommendations in the Meteor Guide (an issue over there might be a good place to start a discussion).  And then eventually, perhaps adding an example TypeScript app similar to the Angular example in #7363.

**Comment by birkskyum** [comment]
I think @IvanPortfolio initially suggested a 'typescript' atmosphere package, instead of having to choose between various 'username:typescript' packages. 

Mdg has to make an opinionated choice to make that happen, so I don't think it can be implemented entirely by yet another typescript third-party package.

**Comment by abernix** [comment]
Yes, that's the way I understood it as well.  But why can't it be implemented by a third-party package?  Why can't there be a community of typescript-focused developers who ensure its well-being and pay it the attention it deserves.  I'm not suggesting that MDG wouldn't consider it but the official stance for Feature Requests is:

> we strongly encourage features to be implemented as Atmosphere or npm packages rather than changes to core

and specifically not to accept features that...
> can clearly be built as a package

Essentially, there is already a lot going on in Meteor without adding additional functionality that can be provided by outside packages.  Is the only issue that the third-party packages have abandoned them?

**Comment by birkskyum** [comment]
Following those guidelines are there probably not an issue here at all. I think too that an up-to-date addition to the Meteor Guide would be a good solution.

**Comment by abernix** [comment]
@IvanPortfolio @birkskyum Would either of you be interested in taking that issue up with the `meteor/guide` repo?  I'm sure an issue with some discussion about its benefits and an (eventual) PR would be very appreciated.  I'm probably not familiar enough with TypeScript to make that happen.

**Comment by birkskyum** [comment]
@abernix I can handle that.

**Comment by abernix** [comment]
@birkskyum Thanks!  Definitely would a be great to have!  (I'll definitely learn something).

Closing as I think that's the best option for now.
