### ISSUE TITLE
Meteor DB API needs a mapreduce or projection feature to display of collections w/ subarrays that match userId

### ISSUE THREAD

**Issue by kenyee** [meteor/meteor#747]
I can't see a clean way to do this w/o something like MongoDB's mapreduce or projection features which is not in Meteor's collection API.

E.g., you easily can't take the Parties Meteor example and properly show "all parties I'm invited to and my rsvp status for each" on a single page like this:
  party1   myrsvp is yes
  party2   myrsvp is no
  party 3  myrsvp is maybe

You can get a collection of parties that you're invited to, but the document collection includes all the rsvps that have been put in, so you can't do a Handlebars #each that shows the party name, and your rsvp status w/o hacking around this in one of two ways:
a) write a Handlebars helper that iterates through the rsvp array to look for one that matches your user ID (but you'll be wasting network bandwidth sending all the rsvps down and if the rsvps are supposed to be private, this is a security issue)
b) write a custom published collection on the server that recreates and array of documents that reduces down the rsvp field w/ the rsvp that matches your user ID (basically hacking a mapreduce function in each time you do this) but at least this cuts down network bandwidth

I think (b) is the only viable option for now but it'd be nice if something like mongo's mapreduce or projections were added instead so you don't have to write custom collection handlers each time you need something like this...

**Comment by AlexFrazer** [comment]
the fields thing could be a bit better documented :\ had some trouble with that one until I found that issue, as it seemed to work in `meteor mongo` but not meteor itself

**Comment by dheerajbhaskar** [comment]
:disappointed_relieved:  AlexFrazer +1

@glasser I hope what you said here was actually put in the Meteor docs, would've saved me a lot of time. I was going around in circles about SO and meteor docs since the past two days. 

> On the server, anything you pass to the fields option to find is passed directly to Mongo as a projection operator, so you can use (eg) the $elemMatch projection operator. So, for example: ...

> We haven't implemented the $elemMatch projection operator in minimongo, so it doesn't work on the client, just on the server (where queries are mostly just processed by MongoDB).

PS: Anyway, I like you guys and what you're doing with meteor :)

**Comment by dheerajbhaskar** [comment]
@glasser Also, projection operator elemMatch works very differently to the way mongodb uses it. I'm using it in a publish function like shown below and the entire query turns up empty when there's no array element with the given `currentUserId`. MongoDB however just removes the particular field `active_bets` if the element was not found. Is there a way I can modify the query to get an empty `active_bets` if the element was not found?

    Games_collection.find(
      {
        table_id             : currentTableId,
        "active_bets.user_id": currentUserId
      },
      {
        fields: {
          limit      : 1,
          table_id   : 1,
          message    : 1,
          timer_value: 1,
          joker      : 1,
          andar_cards: 1,
          bahar_cards: 1,
          active_bets: {$elemMatch: {user_id: currentUserId}},
          game_result: 1,
          createdAt  : 1,
          updatedAt  : 1
        },
        sort  : {createdAt: -1}
      });

**Comment by dheerajbhaskar** [comment]
@glasser Nevermind, silly me. :relieved: I'd left the `"active_bets.user_id": currentUserId` in the query portion. It is as to be expected.
