### ISSUE TITLE
[1.3.5.1] Meteor app has stopped running

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7470]
Anyone else have this issue where Meteor gets stuck here?

```
=> Started proxy.
=> Started MongoDB.
```

It just hangs at that point. My app was working just fine a few minutes ago! Is there some way I can get a glimpse into the build process to see where it's getting stuck? I thought adding `DEBUG=*` to the environment was how, but it doesn't seem to show anything extra.

**Comment by ffxsam** [comment]
Upgraded to 1.4, did a `meteor reset`. This issue is no longer relevant. :)

**Comment by meonkeys** [comment]
I'm glad you shared this! I have a Meteor 1.3.2.4 app that wouldn't build after my installed Meteor upgraded itself to 1.4 (I have not upgraded the app yet). `meteor reset` fixed the build.
