### ISSUE TITLE
1.4 release update: downloading forever.

### ISSUE THREAD

**Issue by ababba15** [meteor/meteor#7473]
![image](https://cloud.githubusercontent.com/assets/13153161/17125640/ec16f1e6-52fd-11e6-87e7-fed77d7deb42.png)

Is there any way to log what is going on? What can cause this behavior?

**Comment by abernix** [comment]
Potential duplicate of many issues: #7430 #7345 #7101 #7124 #7388 #6960.  Please search before opening new issues!

Also, you didn't specify how long 'forever' is so I don't know what advice to give you.  Have you left it for 10 minutes or 10 hours?  On a slow Internet connection, this could take hours, on a slow computer, extracting the 160MB tar could take some time too.  If you don't have sufficient RAM or disk space, the extraction of the download could have failed completely, or is struggling.

Generally speaking, this will eventually finish.  But on an average computer, I wouldn't expect it to take more than 20 minutes.  How long has it been sitting?  Is the cursor spinning?  Did the progress bar go by to 100% already?  Do you have sufficient resources?

**Comment by ThomsCass** [comment]
what's your node version ? Are you on windows ?

**Comment by abernix** [comment]
@ababba15 It's also safe to Ctrl-C and try again.  I'm also curious what happens if you Ctrl-C and run the following:

    sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db vacuum

I'd like to know if it had any output (it might return nothing).

**Comment by ababba15** [comment]
I should give more details, sorry guys.

I am working on MacBook early 2008 with 10.7.5 OS (Lion).
There is about **9Gb** of free space on my hard disk, hope it is enough for new release.
When last night I relaunched my project on which I am working, the new **meteor-tool@1.4** started to download automatically *(past releases I got only notifications that I can update).*

So it downloaded and app started. But from now **meteor-tool@1.4** is downloading every time I restart my app, so I decided to stop the app and make `meteor update`.
After that command **meteor-tool@1.4** has been downloaded again to 100% and then keeps state like on my *screenshot*. 
This all repeats every time I repeat my actions.

Yes, cursor is spinning. I have waited for about 1 hour and nothing changed.

```
node -v
v6.3.0

npm -v
2.15.9
```

`sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db vacuum` gives **no** any output.

I was just wandering — is there any `debug mode` for `update` command to see what is going on under the hood?

**Comment by ababba15** [comment]
Seems like there is similar issue #7476

**Comment by abernix** [comment]
There are so many similar issues (see above) and many are for different reasons entirely.  Your particular issue sounds like an issue with the `tar` NPM module being generally inefficient or just failing silently (see #7457 for a hopeful solution coming soon).

I would honestly recommend doing a fresh install which should rebuild everything:

    curl https://install.meteor.com/ | sh

Please report back how it goes.

**Comment by ababba15** [comment]
I have successfully reinstalled **meteor**, and now outside the project I have 1.4 version.

But inside a project it tries to download **1.3.5_1** version on any command, that starts with `meteor`, even `meteor update` or `meteor --version`.

Should I re-create the project and reinstall all packages?

**Comment by abernix** [comment]
@ababba15 If you run just `meteor` it will try to use (and download) the 1.3.5.1 version (or whatever version your project was using).  Try running `meteor update --release 1.4` instead of just `meteor update`.  If that doesn't work, try just changing the contents of your `.meteor/release` file to `RELEASE@1.4` then running `meteor` as usual.

**Comment by ababba15** [comment]
**After running** `meteor update --release 1.4` all packages were re-downloaded 

```
>> onflight meteor update --release 1.4
                                                                                   
Changes to your project's package version selections from updating the release:
                                              
accounts-base          upgraded from 1.2.8 to 1.2.9
accounts-password      upgraded from 1.1.13 to 1.2.12
babel-compiler         upgraded from 6.8.5 to 6.9.0
babel-runtime          upgraded from 0.1.9_1 to 0.1.10
caching-compiler       upgraded from 1.0.6 to 1.1.6
ecmascript             upgraded from 0.4.8 to 0.5.7
ecmascript-runtime     upgraded from 0.2.12 to 0.3.12
email                  upgraded from 1.0.16 to 1.1.16
es5-shim               upgraded from 4.5.13 to 4.6.13
logging                upgraded from 1.0.14 to 1.1.14
meteor                 upgraded from 1.1.16 to 1.2.16
minifier-css           upgraded from 1.1.13 to 1.2.13
minifier-js            upgraded from 1.1.13 to 1.2.13
modules                upgraded from 0.6.5 to 0.7.5
modules-runtime        upgraded from 0.6.5 to 0.7.5
mongo                  upgraded from 1.1.9_1 to 1.1.10
npm-bcrypt             upgraded from 0.8.6_3 to 0.8.7
npm-mongo              upgraded from 1.4.45 to 1.5.45
promise                upgraded from 0.7.3 to 0.8.3
standard-minifier-css  upgraded from 1.0.8 to 1.1.8
standard-minifier-js   upgraded from 1.0.8 to 1.1.8
stylus                 upgraded from 2.512.5 to 2.513.4
tracker                upgraded from 1.0.15 to 1.1.0
webapp                 upgraded from 1.2.11 to 1.3.10

onflight: updated to Meteor 1.4.
```

```
>> onflight meteor --version
Meteor 1.4
```
**After launching:**
```
>> onflight meteor
[[[[[ ~/Desktop/onflight ]]]]]                

=> Started proxy.                             
                                              
Your development database is using mmapv1, the old, pre-MongoDB 3.0 database engine. You should consider upgrading to Wired
Tiger, the new engine. The easiest way to do so in development is to run meteor reset. If you'd like to migrate your database,
please consult https://docs.mongodb.org/v3.0/release-notes/3.0-upgrade/
                                              
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

**After following instructions** about database:
```
>> onflight meteor reset
Project reset.                                
>> onflight meteor
[[[[[ ~/Desktop/onflight ]]]]]                

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

# Hewston, all going fine!

Thanks for this release and for fast reply.

Closing.

**Comment by toledoroy** [comment]
Turn off Windows Defender

**Comment by JWPapi** [comment]
Turning off Win Defender worked perfect! Did not even had to restart!
