### ISSUE TITLE
Proposal to use -s as short form of --settings flag in the Meteor CLI tool

### ISSUE THREAD

**Issue by yogiben** [meteor/meteor#7478]
`--settings` is probably the most used flag for the cli tool.

We make developers' lives easier by allowing them to use `-p` in addition to `--port` when setting a port.

The same would be true if we allowed `-s` in addition to `--settings`.

e.g. `meteor -s settings.json`

**Comment by yogiben** [comment]
I'd be happy to submit a PR for this.

**Comment by alphanso** [comment]
@abernix  @platform I have created a PR. Please check.

**Comment by abernix** [comment]
Fixed with PR #7819.  Nice work, @alphanso!  This should work its way into an upcoming version.
