### ISSUE TITLE
Module did not self-register on dev-stage after upgrading to Meteor@1.4

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#7480]
I expecting this issue on old app (started on early versions of Meteor, before v1.0). But I update this app to every Meteor release. This issue appeared right after update from v1.3.5.1 to v1.4.

This app has NPM packages installed locally via `npm install ...`, because `meteor npm intall ...` is new feature.

Console error:
```
Error: Module did not self-register.
   at Error (native)
   at Object.Module._extensions..node (module.js:434:18)
   at Module.load (module.js:343:32)
   at Module.Mp.load (/Users/dmitriygolev/.meteor/packages/babel-compiler/.6.9.0.1ks9dms++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at bindings (/sites/meteor-app/node_modules/mhash/node_modules/bindings/bindings.js:76:44)
   at Object.<anonymous> (/sites/meteor-app/node_modules/mhash/index.js:1:37)
   at Module._compile (module.js:409:26)
```

This issue was fixed via (see [this comment](https://github.com/meteor/meteor/issues/7475#issuecomment-235258111)):
```shell
nvm install v4.4.7
npm rebuild
npm update
meteor reset
meteor update
meteor run
```

I guess more proper way - is to remove NPM packages and install them via `meteor npm install ...`, see [this comment](https://github.com/meteor/meteor/issues/7475#issuecomment-235259484)

Anyways, I'm waiting for community response on this, maybe someone has a better solution.

**Comment by abernix** [comment]
The solution is either:

```sh
cd your-app-dir
meteor npm rebuild
```

or the more extreme:

```sh
cd your-app-dir
rm -rf node_modules
meteor npm install
```

Could you reproduce the problem and try by rolling back with Git and trying again?

**Comment by dr-dimitru** [comment]
> Could you reproduce the problem by rolling back with Git and trying again?

No, no chance to reproduce the problem again as `node_modules` is ignored and isn't committed to Git.

The only way is install and build npm packages for node v0.10.6

> do a lot of silly things including installing a Node binary that Meteor will not use itself and wiping your database.

Is there any other way to remove local dev-build files without dropping DB?

**Comment by abernix** [comment]
> Is there any other way to remove local dev-build files without dropping DB?

You can remove the contents of the `.meteor/local/` directory manually but skip the `db` folder.

**Comment by dr-dimitru** [comment]
> You can remove the contents of the .meteor/local/ directory manually but skip the db folder.

It's obvious, I meant command (*may be there is a new one, or undocumented*). 

Anyways, thank you. As it solved fell free to close this issue, or keep it open for a while, for folks with same issue on local build.

**Comment by abernix** [comment]
Ah, no, there's no command to do specifically that!

Anyhow, thanks for reporting it!  I will leave it open for a couple days, but folks can always find closed issues thanks to Google and Issue Search. 😄

**Comment by FinalDes** [comment]
when build to linux server I happen the same error

**Comment by abernix** [comment]
Did you try either of [my solutions above](https://github.com/meteor/meteor/issues/7480#issuecomment-235263987)?

**Comment by FinalDes** [comment]
no one works @abernix

**Comment by abernix** [comment]
Are you referring to a problem in development or with a bundle you made with `meteor build`?

**Comment by FinalDes** [comment]
my problem happen when I make the bundle @abernix

**Comment by abernix** [comment]
@FinalDes This issue is about the development environment only.  Read on...

If you're coming to this issue with production issues (e.g. using `node index.js`, `mup`, Docker, etc.), please read my remarks in the `mup` production problem thread, as your issues are most likely related:  https://github.com/meteor/meteor/issues/7475#issuecomment-235229269.  Open a new issue if you don't find your answer with that or read the [Meteor guide section on custom deployment](http://guide.meteor.com/deployment.html#custom-deployment).

If your problem is with development environment (i.e. running with the `meteor` tool), consider my suggestions in https://github.com/meteor/meteor/issues/7480#issuecomment-235263987 and leave your problems below.

I'm closing this issue as it hasn't got much traction in the mess of 1.4 so I don't think it's super relevant, but happy to reopen if others experience this problem **in development** as well.

**Comment by zeroasterisk** [comment]
Here's my recreation of this problem.

https://github.com/zeroasterisk/meteor-issue-7512

TL;DT: running `meteor add accounts-password` breaks the production build and deploy... worked before
