### ISSUE TITLE
source map header bug?

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7484]
Please take a look
https://github.com/meteor/meteor/blob/devel/tools/isobuild/linker.js#L1063

the option `includeSourceMapInstructions` is an option which maybe true, the `header` variable is defined and initialized outside of the map closure.

The line 1063 concats `header` and re-assigns the result to `header` variable again. if the closure is executed more than 1 time, we will have repeated `SOURCE_MAP_INSTRUCTIONS_COMMENT` and the repeated header and the header will be getting longer. Is it a bug?

I think the concat suppose to be outside of the closure instead of inside the map closure?

I suspect this is the cause of the source map parsing error.

**Comment by abernix** [comment]
I'm not confirming as a bug, but just marking for the time being. 😁

What you're saying sounds reasonable to me, but someone more familiar with that part of the process would need to comment.

**Comment by abernix** [comment]
Closing as this was fixed in Meteor 1.4.1.1 via aacfbbf5d27631d1eb18eb210e6868f105e467a8.  Great find and thanks for reporting this.  Hopefully this will resolve some of the more weird source map problems that have been occurring!
