### ISSUE TITLE
Release script should bump dependent package versions

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7495]
When you update a vanilla app to 1.4 from 1.3.5.1, you'll see

```
Newer versions of the following indirect dependencies are available:
 * autoupdate 1.2.11 (1.3.11 is available)
 * caching-compiler 1.0.6 (1.1.6 is available)
 * ddp-client 1.2.9 (1.3.0 is available)
 * ddp-server 1.2.10 (1.3.9 is available)
 * http 1.1.8 (1.2.8 is available)
 * templating 1.1.14 (1.2.13 is available)
To update one or more of these packages, pass their names to `meteor update`.
```

The reason for this is that although new versions of the above packages have been published, the direct dependencies of the skel that depend on them have not. For example:

 - `ddp-client@1.3.0` was published as part of 1.4
 - `ddp` [which depends on `ddp-client`] has not had a new version published
 - `meteor-base` [which depends on `ddp`] has not had a new version published

The skel depended on `meteor-base@1.0.4` (published April 16th), before, and after the update.

(A) solution to this problem would be to publish dependent package versions when releasing. This was the solution chosen by the `react-packages` to solve the same problem, and we could likely repurpose the [`publish-packages` script](https://github.com/meteor/react-packages/tree/devel/scripts/publish-packages).

Another alternative would be to make `meteor update` more aggressive about taking changes to indirect dependencies (at the moment it prefers to only take patches, not even minor versions).

**Comment by laosb** [comment]
For those who want to get a copy&paste solution, here you're: 

```
meteor update autoupdate caching-compiler ddp-client ddp-server http templating
```

**Comment by tmeasday** [comment]
## Notes about the way the constraint solver updates dependencies

Terminology:
 - root packages -- packages in `.meteor/packages`
 - indirect packages -- packages used by the project that are not root packages
 - previous solution -- the current contents of `.meteor/versions`

Use cases:
  - `meteor update` -- updating the tools version and all packages
  - `meteor update X` -- updating a single package(s)
  - `meteor add X` -- adding a package, basically similar to `meteor update X`

There is an argument `--allow-incompatible-update` -- without this the tool will
never bump a version across major boundaries (or downgrade a version).

Packages are split into categories:

1. Packages to update (`toUpdate`)
   - either all root packages (for `meteor update`) or the packages named that were in the previous solution

2. Previous root
  - packages that were root packages in the previous solution (and aren't being updated)

3. Previous indirect
  - packages that were indirect packages in the previous solution

4. New root packages

5. New indirect packages

The solver works by a series of optimizations; i.e it will optimize each step and never relax that when optimizing further steps.

1. First minimize "bad" things like using unknown packages, conflicting with constraints, and unanticipated preleases. Generally if these things end up > 0, we'll throw an error.

2. If we aren't allowing incompatible updates, minimize incompatible updates to *all* previous packages (including the ones we are updating). If this is > 0, we'll error.

3. Maximize package versions of packages to update
  - this means if we've not allowed incompatible updates, we'll end up maximizing up to minor versions.

4. If we are allowing incompatible updates, *now* minimize incompatible updates.

5. Now minimize changes to all previous root packages.

6. Now minimize changes to all previous indirect packages (taking patches though when running `meteor update`).

7. Now maximize package versions of new root packages.

8. Now take the lowest possible version of all new indirect packages (taking patches).

9. Now minimize the total number of packages.

## The problem

Previously, a lot of this behavior was fairly invisible because release pinning meant that for all core dependencies we only ever had one version allowed and third party packages didn't tend to lead to all that many indirect dependencies.

However, with release unpinning, a significant fraction of core packages are indirect dependencies of any given project. Given the behavior tends to freeze indirect dependencies (particularly steps 6. and 8. above), this means `meteor update` doesn't tend to upgrade a lot of core packages to their latest versions!

## Potential solutions

1. One solution is when running `meteor update`, rather than passing in all root dependencies as the "packages to update", pass in *all* current dependencies. However this won't help with step 8. if we happen to add new packages to core. (It's very simple to implement however)

2. Update the "with patches" caveat above to mean "with patches and minor versions". However this will mean we never take updates to major versions of indirect dependencies.

3. Switching all indirect dependency resolution to preference updates rather than preference no changes. However this would lead to indirect deps being updated when you `meteor update X`, which is probably not ideal.

4. Switch the `upgradeIndirectDepPatchVersions` set by `meteor update` to `upgradeIndirectDepsVersions` to lead to solution 3. when `meteor update`-ing but leaving the behavior unchanged when updating a single package.

  To do this we'd need to move step 4 to be after steps 6. and 8. (at least in that case).

I'm leaning towards doing solution 4. but also tempted to just do solution 1.

**Comment by benjamn** [comment]
I'm not in favor of releasing new versions of unchanged dependent packages just to trigger updates of their dependencies. That seems like a recipe for lots and lots of pointless patch versions.

I'm also not a fan of pushing new minor versions of packages on our developers, so I don't think I can support changing the behavior of `meteor update` to take minor updates. That may be the "npm way," with the default `^x.y.z` notation accepting the most recent `.y.z` as long as `x > 0`, but it feels hostile to developers who want their packages to keep working the way they used to, which is absolutely their prerogative. Semantic versioning has its shortcomings, but it's a useful tool when respected, and it's not our place to cheapen it by ignoring the semantic difference between patch and minor versions.

What about a simpler solution? Instead of printing just this verbal instruction:

```
To update one or more of these packages, pass their names to `meteor update`.
```

we could also print out an easily copy/pasted command that updates indirect dependencies, like the one @laosb provided above:

```
To update one or more of these packages, pass their names to `meteor update`:

  meteor update autoupdate caching-compiler ddp-client ddp-server http templating
```

As a shorthand for this command, we could easily support a flag like `meteor update --all-packages`.

**Comment by glasser** [comment]
I'm not sure that I understand what the "however" from 3 is.  The code that makes `meteor update X` work already manages to differentiate between "I want to update X" and "I don't want to update other root dependencies".  Why would changing the update algorithm to basically treat root and indirect dependencies the same way (which is what 3 is suggesting, right?) break the ability to differentiate between mentioned and non-mentioned packages?

So yeah, I'd lean towards 3, unless I'm missing something: basically just entirely rip out the differentiate between root and indirect packages, but still keep in the difference between mentioned and non-mentioned packages.

**Comment by tmeasday** [comment]
@glasser: I don't think I was suggesting treating root and indirect "unmentioned" deps the same; it's pretty clear that we shouldn't update root unmentioned deps in any of the cases, but what we are discussing in this issue is what to do with indirect unmentioned deps (specifically that we should maybe update them in some circumstances).

Unless you are assuming we are doing solution 1. also ("mentioning all indirect deps"), which would make doing solution 3. redundant as steps 5+ only affect *unmentioned* dependencies (I'll update my original comment to make this clearer).

**Comment by glasser** [comment]
My suggestion is just to treat root and indirect dependencies identically. Sounds like Ben disagrees though, so I'll defer to his more timely experience.

**Comment by tmeasday** [comment]
@benjamn 

> As a shorthand for this command, we could easily support a flag like `meteor update --all-packages`.

My point would be that what does `meteor update` mean if not `meteor update --all-packages`?

I guess I agree with @glasser, I don't really see a reason to treat root and indirect dependencies differently. If I call `meteor update` with no arguments, I'm saying "update everything" not "update the packages in my `.meteor/packages`" -- especially given the existence of `meteor-base`, which then depends on and implies a set of key core packages, it just seems a bit weird to me to just update the few packages that happen to be in `.meteor/packages`.

Obviously it used to mean "update everything core", and we are defining what it means now in the post unpinning world, but that's my intuition anyway. Certainly we could have both modes (if we prefer the reverse it could be `meteor update --only-direct-dependencies` or something).

---

However, @stubailo raised an interesting secondary point about all this: in the current implementation and everything we've proposed so far, we've lost the ability to update core packages to anything other than the latest version of Meteor. 

This is because when you `meteor update --release X` we update the constraints in `.meteor/packages` to at a minimum the versions in release `X`, but then the resolver runs with "packages to update" set to all your those packages; which will push it to take the latest version of them (which will, sans breaking changes and the tool, take you to the latest release).

Assuming we are concerned about this, I think we should *not* pass any packages to update into the constraint solver when running `meteor update`.

To implement `meteor update --all-packages`, we would also need to pass in minimum versions of all core packages as governed by the release. I think we can do that however.

**Comment by tmeasday** [comment]
As an aside, I just looked again and realised that when you run `meteor update --release X.Z.Y` we do not attempt to update packages outside of the constraints of the new release.

This will mean we put a floor on your direct dependencies (as governed by your updated `~/.meteor/packages`) but do not pass any "packages to update" to the constraint solver. This will tend to keep versions as low as possible given those new constraints. This is probably what we want, although we may want to think a little bit about indirect core dependencies here also.

**Comment by tmeasday** [comment]
See https://github.com/meteor/meteor/pull/7653

**Comment by laosb** [comment]
@tmeasday How about notice developers when higher major versions of packages are available? It sounds like most package authors won't support older versions once new major is released, and developers won't know about it without referring to its docs or Atmosphere page.

*Not so related to this problem, but can be improved.*

**Comment by benjamn** [comment]
Should this issue remain open now that Meteor 1.4.1 supports `meteor update --all-packages`?

**Comment by tmeasday** [comment]
Happy to close this, would like to consider https://github.com/meteor/meteor/issues/7671 before moving on however.
