### ISSUE TITLE
meteor shell unresponsive after reload

### ISSUE THREAD

**Issue by gooor** [meteor/meteor#7498]
I have specific issue on meteor 1.3.5.1 on OSX El Captain:
when I'm in meteor shell, change something in the code to trigger live reload, shell will reload by saying `Server unavailable (waiting to reconnect)`. But while reloading I press arrow keys (up or down) it is unresponsive (nothing can be written, or cannot be stopped with Ctrl+C). I can only close tab and open new - that can be annoying ;)

Edit:
Also on 1.3.4.1. That's happening on every meteor (5x) project with different libs
On empty 1.4 it works ok

**Comment by abernix** [comment]
It works on 1.4 because it was fixed in 946e505d5fa7f067baffba339f21c91d87291e1f in duplicate issue #7312. 😬

You'll need to either hold off on pressing the keys until the server restarts, or update your project to 1.4 to get this bug fix as it likely will _not_ get back-ported anytime soon.
