### ISSUE TITLE
'meteor update' on Ubuntu 16.04 results in weird 404-error

### ISSUE THREAD

**Issue by peterwilli** [meteor/meteor#7501]
Hi guys,

I am currently running a project with Meteor 1.3 and I am trying to update to 1.4.
I am getting this error (never seen it before), I hope someone has the same and maybe figured it out!

    error: Command failed: /home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
    Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node": HTTP error 404 Not Found
    gyp ERR! configure error 
    gyp ERR! stack Error: 404 status code downloading tarball
    gyp ERR! stack     at Request.<anonymous>
    (/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
    gyp ERR! stack     at emitOne (events.js:82:20)
    gyp ERR! stack     at Request.emit (events.js:169:7)
    gyp ERR! stack     at Request.onRequestResponse
    (/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:320:20)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! System Linux 4.4.0-31-generic
    gyp ERR! command "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
    "/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
    "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd
    /home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass
    gyp ERR! node -v v4.4.7
    gyp ERR! pangyp -v v2.2.1
    gyp ERR! not ok 
    Build failed

    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
    "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
    npm ERR! node v4.4.7
    npm ERR! npm  v3.10.5
    npm ERR! code ELIFECYCLE
    npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs node-sass
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!
    /home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/npm-debug.log
    Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node": HTTP error 404 Not Found
    gyp ERR! configure error 
    gyp ERR! stack Error: 404 status code downloading tarball
    gyp ERR! stack     at Request.<anonymous>
    (/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
    gyp ERR! stack     at emitOne (events.js:82:20)
    gyp ERR! stack     at Request.emit (events.js:169:7)
    gyp ERR! stack     at Request.onRequestResponse
    (/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:430:21)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:320:20)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! System Linux 4.4.0-31-generic
    gyp ERR! command "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
    "/home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
    "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
    gyp ERR! cwd
    /home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/node_modules/node-sass
    gyp ERR! node -v v4.4.7
    gyp ERR! pangyp -v v2.2.1
    gyp ERR! not ok 
    Build failed

    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
    "/home/peter/.meteor/packages/meteor-tool/.1.4.0.aqkgqc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
    npm ERR! node v4.4.7
    npm ERR! npm  v3.10.5
    npm ERR! code ELIFECYCLE
    npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the node-sass package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/build.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs node-sass
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls node-sass
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!
    /home/peter/.meteor/packages/fourseven_scss/.3.2.0.137cqr2++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1g4dxgc/npm-debug.log

**Comment by Ben305** [comment]
You should update fourseven:scss to `3.8.0_1` first

**Comment by abernix** [comment]
The reason you're getting this 404 is because the `fourseven:scss` 3.2.0 package (released in July 2015) has a equal dependency on [`node-sass` 3.2.0](https://github.com/sass/node-sass/releases/tag/v3.2.0) but since Ubuntu 16.04 didn't exist for almost another full year, there is no binary package for it.  As @Ben305 suggested, updating will fix your problem.

Please remember that updating your Meteor project requires updating not only Meteor but the dependencies you use in your own project.

Running `meteor list` would show that this package was out of date and should be updated.  Please use that command and take a moment to check for updates to other packages you may be using as well.

Closing.

**Comment by peterwilli** [comment]
Hi @Ben305  and @abernix, I didn't know that, thanks! You made my day!

**Comment by abernix** [comment]
Good to hear!   A project created a few days ago using `meteor add fourseven:scss` would have had a much more recent version.  Perhaps another package you added has a very outdated dependency on `fourseven:scss` (likely).

**Comment by peterwilli** [comment]
@abernix I never installed the scss package on purpose, at least. I ran meteor list to see if it was there but it wasn't, I also had to explicitly add @3.8.0_1 to the package name to actually override the old version.

It must be some kind of external dependency or something

**Comment by abernix** [comment]
It's definitely not a core dependency so just out of curiosity, do you know which other packages you started the project with?  If you can figure it out, it'd be nice to poke package maintainers for this update to avoid problems like this in the future!

**Comment by peterwilli** [comment]
@abernix Out of the official packages, I did use coffeescript, stylus, dalgard:jade, kadira:flow-router, kadira:blaze-layout, meteorhacks:picker, momentjs:moment
