### ISSUE TITLE
Mupx deploy always failed ...

### ISSUE THREAD

**Issue by wwlweihai** [meteor/meteor#7515]
I have trying many version of meteor, many version of node, npm . no one can deploy success! The problems are two main type ——

One is the fibers is missing. like this
>         /bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
>                 throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
>                       ^
>         Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?

Other one is the npm need update. like this

> npm WARN deprecated such as scoped packages, offered by the primary npm
> npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
> npm WARN deprecated latest stable version. To upgrade to npm@2, run:
> npm WARN deprecated
> npm WARN deprecated npm -g install npm@latest-2
> npm WARN deprecated
> npm WARN deprecated To upgrade to the latest stable version, run:
> npm WARN deprecated
> npm WARN deprecated npm -g install npm@latest
> npm WARN deprecated
> npm WARN deprecated (Depending on how Node.js was installed on your system, you
> npm WARN deprecated may need to prefix the preceding commands with sudo, or if
> npm WARN deprecated on Windows, run them from an Administrator prompt.)
> npm WARN deprecated
> npm WARN deprecated If you're running the version of npm bundled with
> npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
> npm WARN deprecated will be bundled with a version of npm@2, which has some small
> npm WARN deprecated backwards-incompatible changes made to npm run-script and
> npm WARN deprecated semver behavior.
> npm WARN package.json meteor-dev-bundle@0.0.0 No description
> npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
> npm WARN package.json meteor-dev-bundle@0.0.0 No README data

By the way set `deployCheckWaitTime` is useless, because i set this 600 , and error is still.

Is here anybody can tell how to deploy meteor project to my server. I want to know the version of meteor,nodejs,npm on my local pc ,and on the server!

Thanks !

**Comment by abernix** [comment]
Please **search** before opening issues.  See > #7475 < and the [Meteor Guide section on deployment](http://guide.meteor.com/deployment.html#custom-deployment)

Closing as duplicate.
