### ISSUE TITLE
Validated method's `validate` not throwing errors when passed incorrect types

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7518]
Meteor 1.4.

Steps to reproduce:
1) Clone https://github.com/ffxsam/ffx-meteor-react-boilerplate
2) `npm install && npm run scaffold`
3) Edit `/imports/features/SomeFeature/components/Thing/Thing.js`, line 6, and change `'Unknown'` to a numeric value.
4) Run `meteor`
5) Click the "Call Meteor method" button and observe the client and server consoles.

There are no errors thrown.

**Comment by laosb** [comment]
I guess this should go to meteor/validated-method ?
