### ISSUE TITLE
[IDEA] Coordinate data synchronization and reactivity with `requestAnimationFrame`.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7519]
My [graphical library](https://github.com/infamous/infamous) is getting close to a point where I will start making some apps with it (on top of Meteor).

But, in the meanwhile building my library, I've also been thinking about [graphical performance in Meteor](https://forums.meteor.com/t/jank-free-animation-in-meteor/26217).

When many clients are connected via a single Meteor server, reactive updates can be very random, and can happen during any of the clients' animations.

I don't know what the solution is yet, but I simply know that it is easy to cause "jank" (in general, not just in a Meteor app) when there are lots of random data-wise things happening. In the case of Meteor, it is reactive updates from the server.

It'd be nice if there was some way of throttling reactivity behind `requestAnimationFrame`.
## high-level idea:

A high-level idea would be for Meteor to provide it's own hook for hooking into `requestAnimationFrame`, whereby all Meteor app developers would use the hook to run graphical calculations.

There would be two stages in Meteor's built-in rAF mechanism. First, Meteor would run the users request animation procedures. Then, if there is any time left in the animation frame, Meteor would run reactive updates (guaranteeing at least 3 ms of time if there happens to be no time left). Then, view updates would be batched into the next frame.
## as it currently stands

View updates are random, and are not associated with `requestAnimationFrame` at all, leading to easy opportunities for jank.

---

That's just some high-level thinking, but not necessarily an actual solution. Other libraries (like mine) make their own animation loop, so another idea could be for Meteor to expose a reactive update API that a graphical layer can call, and the graphical layer can specify how much time is available for reactive computations. When the threshold is reached, Meteor simply defers any calculations that haven't been processed yet to the next frame (which requires again that the graphical engine make a new request on the next frame along with an allotted time).

---

I hope this can stir some thinking, so that Meteor might adopt some form of strategy. I'll keep thinking about it as I go along with my graphical stuff, and will post back if I have any more specific ideas.

**Comment by abernix** [comment]
Thanks for submitting this feature request.  Please read the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) and make sure you help champion this feature (discuss on forums, etc.) if you want it to have the best chance of becoming part of core.  Remember, the bare minimum approach is best where Meteor provides basic hooks and third-party packages provide the additional functionality.

Tagging as feature and +1's/discussion are welcome.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BIDEA%5D%20Coordinate%20data%20synchronization%20and%20reactivity%20with%20%60requestAnimationFrame%60.&body=Migrated%20from:%20meteor/meteor%237519) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
