### ISSUE TITLE
client tests and server tests run simultaneously and interfere with eachother

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/meteor#7527]
Meteor v1.4 and prior

I have various tests scattered around my application and I just learned that they don't run consequently, but in parallel. This is causing inconsistencies in my testing. For instance logging in and out in the client tests hides the server tests from my application.

meteor test --driver-package practicalmeteor:mocha
```
describe('my tests', function(){
  if(Meteor.isClient){
    //client tests
  }
  if(Meteor.isServer){
    //server tests
  }
})
```

**Comment by quintstoffers** [comment]
There's the (undocumented?) environment variable `MOCHA_RUN_ORDER` that one can set to `serial` to run the server tests before the client tests.

`MOCHA_RUN_ORDER=serial meteor test --driver-package practicalmeteor:mocha`

**Comment by jakobrosenberg** [comment]
Thanks @quintstoffers 

Closing issue
