### ISSUE TITLE
install.meteor.com/?release=<VERSION> fails for some older versions

### ISSUE THREAD

**Issue by yourcelf** [meteor/meteor#7528]
When installing some older releases of Meteor while specifying the release version (e.g. using `https://install.meteor.com/?release=<VERSION>`), the installation hangs while attempting to download files for the Meteor distribution.  Characteristic output is:

```
Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
```

Two example versions that cause this problem right now are:
- 1.4-beta.7
- 1.2.2-faster-rebuilds.0

To reproduce, install meteor, specifying a HOME directory that is different from your usual so that Meteor creates a new installation:

```
mkdir /tmp/meteor-install/
curl -sS https://install.meteor.com/?release=1.2.2-faster-rebuilds.0 | HOME=/tmp/meteor-install /bin/sh
```

The install script itself is correctly downloaded, but it then attempts to fetch https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.2.2-faster-rebuilds.0/meteor-bootstrap-os.linux.x86_64.tar.gz which is 404.

We ran into this with meteor-buildpack-horse, a Heroku buildpack for meteor apps (AdmitHub/meteor-buildpack-horse#132).  The buildpack fetches specific releases of meteor to make installation on heroku faster and more consistent.  We'd prefer not to have to fetch the meteor platform twice (once for the current release to avoid CDN issues, and again when meteor installs the older platform for the target app), as this painfully slows code deploys.

**Comment by laosb** [comment]
Maybe MDG cleared these beta releases? I can still see them from `meteor show --show-all METEOR`:

```
$ meteor show --show-all METEOR | grep 1.2.2-faster-rebuilds.0
  1.2.2-faster-rebuilds.0                         December 18th, 2015
```

But truly can't download:

```
$ mkdir /tmp/meteor-install/
$ curl -sS https://install.meteor.com/\?release\=1.2.2-faster-rebuilds.0 | HOME=/tmp/meteor-install /bin/sh
Downloading Meteor distribution

curl: (22) The requested URL returned error: 404 Not Found
Retrying download in 5 seconds...
^C
```

**Comment by abernix** [comment]
I realize this might be working for you and I understand the helpfulness of this in your particular circumstance, but I'm not sure about the likeliness of this to get resolved given the other issues needing to be attended to.

The truth of the matter is that neither of those are official releases and using `?release=` syntax is not officially encouraged.

**Comment by laosb** [comment]
Yes. Developers shouldn't really use them.

**Comment by jsantana90** [comment]
I worked with the release `1.2.2-faster-rebuilds.0` and the rebuild time for development is really time saver.

**Comment by abernix** [comment]
I'm aware, but the change in that release (f93115bae50773cca05b76dd1f22b2d78213a36e) was experimental in regards to the dependency cache and worked its way into future officially recommended releases.

**Comment by hwillson** [comment]
Closing this off - https://github.com/meteor/meteor/issues/7528#issuecomment-236902139 sums up why:

> The truth of the matter is that neither of those are official releases and using ?release= syntax is not officially encouraged.

Thanks for reporting this originally!
