### ISSUE TITLE
1.4.0.1 upgrade is a patch, meteor update does not work without --patch flag

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7535]
Yesterday morning my projects started having an issue, when I ran the meteor command I would get a notification that `meteor-tool@1.4.0-1` would download and then I would get seemingly random errors showing in my app.

The app worked minutes before!  I made no changes!

I flailed along and came across some steps that would resolve it.

### Steps to resolve
1. `meteor create test`
2. `meteor --version` shows version 1.4
3. `meteor` the build completes after downloading `meteor-tool@1.4.0-1` for a while.
4. I got a message on the command line that a patch is available.  To install run `meteor update --patch`.  That is a new one!
5. `meteor update --patch` on my test app
6. go to all of my other v1.4 projects and execute `meteor update --patch`

As a general rule, if I have an update issue I always try to update with a test project created by `meteor create`:
- This reduces the possibilities of packages failing because there are fewer packages used in the test app.
- I suspect the meteor team at least verifies that a test app can be updated.
- Once it is updated then all the dev_bundle packages are on your system and it will not try to download again.

### What I think happened?
- v1.4 builds stopped working because it would start downloading `meteor-tool@1.4.0-1` and fail.
- I believe that v1.4.0.1 was marked as an official release but it was also marked as a patch?  Likely by design.  Maybe the behavior of a patch is to automatically download the patch even if a user does not `meteor update`?  Maybe 4th level updates are automatically patches?
- running `meteor` would download `meteor-tool@1.4.0-1` for a while and then barf in some random place.
- `meteor update` would download `meteor-tool@1.4.0-1` for a while and then barf in a new random place.
- `meteor update --patch` would not work in my project directories, so I tried with a new simple project created by `meteor create`.  whew it worked.

### Recommendation
- Did this really need to be a patch release?  Was v1.4 flawed badly enough that updates needed to be forced?
-  If true.  Then add a note in the release notes that this is a patch?  Or maybe we should assume all 4th level updates are patches?

**Comment by benjamn** [comment]
@tmeasday I understand why it seemed like a reasonable thing to do, but I would have advised against marking 1.4.0.1 a patch release.

Given the headaches it has caused, I'm going to disable the background downloading of releases, and remove the code responsible for that feature.

**Comment by tmeasday** [comment]
You guys are right of course, apologies for marking it a patch release. I just wanted to ensure it would get downloaded ASAP for as many users as possible, but I'm not sure the "patch" status even affects this. Can we un-mark it a patch release?

I agree there doesn't seem be a great benefit in auto downloading releases that the user isn't using, although I'm not sure it would have helped in @brucejo75's case (he's on 1.4, patch release forces him to go to 1.4.0.1, so it's not really background downloading in this case).

Of course the original #7491 would have had a much smaller impact if we didn't background download.

In this particular case, it's the CDN / resuming / unpacking / something that is rearing it's head again. I'm going to dig into this today.

**Comment by tmeasday** [comment]
I recall you are a Windows user @brucejo75, so you're probably happily unaware of #7491. If you follow that issue, you can probably see why we wanted to update to come down the wire ASAP.

**Comment by tmeasday** [comment]
Hmm, I tried and failed to reproduce this by getting a system with only 1.4 on it, creating a 1.4 app, and then killing the network mid-way through starting the app (so the background request for `meteor-tool@1.4.0-1` fails), but I did not see the problem. The request for the tool happens in the background (and eventually fails) and the app continues to run normally

**Comment by tmeasday** [comment]
@benjamn thinking about this more, I think it *was* correct to make it a patch release, given it fixed a critical issue for linux/32bit users.

I'm not sure about the original issue reported here, I have been unable to replicate it.

**Comment by brucejo75** [comment]
@tmeasday Thanks for looking into this.

Yes, I am a windows user.

I do not think that the request for `meteor-tool@1.4.0-1` failed.  What happened was that it generated very strange bugs in my larger project and failed to build my project which failed to complete the full install of the `dev_bundle` bits.

When I moved to a simple project the update worked fine and told me that I needed to use the `--patch` flag.  And that is when I was able to resolve it for my larger projects.

My intent with the bug was to make folks aware of a way to get it to work if their project was failing on it.  Also, if it is necessary to do a patch, which it sounds like it may be in this case.  Then maybe worthwhile to document the install steps in the release notes  (e.g. use `--patch` flag), because the feedback that is a patch happens after the full download of the `dev_bundle` succeeds.

My experience has been that typically >50% of updates fail on my full project; patch or otherwise.  I have learned to drop back to a simple project, get the `dev_bundle` set up and then things usually work fine.  As a general rule, I think I am going to do a `meteor update` in a non-meteor project or always update it on the app created by `meteor create` .  I usually find once the `dev_bundle` is downloaded my projects can handle it.  For some reason complex projects can foul up the `dev_bundle` download.  I included my package list below, in case that could possibly help with a repro.  (do you have a larger project that you run through the paces prior to a release?)

### Package List
```
accounts-password@1.2.12
accounts-base@1.2.9
jquery@1.11.9
check@1.2.3
audit-argument-checks@1.0.7
themeteorchef:jquery-validation
twbs:bootstrap
browser-policy@1.0.9
# meteorhacks:npm
mdg:validated-method


themeteorchef:bert


# npm-container
ecmascript@0.5.7
es5-shim@4.6.13
kadira:flow-router
kadira:blaze-layout
meteorhacks:fast-render
meteor-base@1.0.4
session@1.1.6
templating@1.2.13
fourseven:scss
reactive-var@1.0.10
reactive-dict@1.1.8
aldeed:collection2
tracker@1.1.0
email@1.1.16
force-ssl@1.0.12
underscore@1.0.9
meris:base
meris:signin
meris:helpers
meris:utils
meris:col-sort


# spacebars-compiler

# required for file uploading
benjaminrh:jquery-cookie
numeral:numeral

# utils
liberation:reactive-var-inc-and-dec

# debug tools
meteortoys:allthings
# datariot:ganalytics
# standard-minifier-css
# standard-minifier-js
# kadira:debug


# testing
practicalmeteor:mocha
# velocity:meteor-stubs

# Android web surface for backwards compat
crosswalk@1.6.2

#must be last
vsivsi:file-collection
```

**Comment by tmeasday** [comment]
@brucejo75 I'm not convinced this issue is anything particuarly to do with the fact that the release was a patch release.

If you have problems updating your app, it could be useful to post the specific problem. I think most people are able to update their larger apps without seeing the kind of issue you describe.

**Comment by brucejo75** [comment]
Fair enough @tmeasday .  I will dutifully document each issue :-).

Although, I do not think I have had an issue that I have not seen in the forums or documented in the bugs.  So it may be possible that these issues may be affecting many users.

**Comment by reggieboyYEAH** [comment]
I am also encountering this in my windows 10 64bit machine. meteor update --patch does not work 
Its just stuck on downloading the meteor-tool@1.4.0.1. :(

**Comment by s-devaney** [comment]
Same here. Had to completely uninstall and re-install Meteor to get it to work. Come on guys, there seems to be issues with downloads getting stuck all the time nowadays.

**Comment by brucejo75** [comment]
Did you try doing the work around?  create a simple project and then patch it?  then move on to update your main project?  That seems to be a good fall back for me.
