### ISSUE TITLE
[1.4] `pkginfo` package issue in a package created using `meteor npm link` 

### ISSUE THREAD

**Issue by miraten** [meteor/meteor#7536]
I made a winston-js wrapper package.
And I inserted into my Meteor app using `meteor npm link`.

When I build it, I met the fail message.
And the message is the same that of [https://github.com/meteor/meteor/issues/6313](https://github.com/meteor/meteor/issues/6313)

If I embed the package into the node_module directory in my app, it works well.
But if it is linked using 'meteor npm link' command, I fails.

**Comment by benjamn** [comment]
What version of `winston-js`? What version of `pkginfo`?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this.
