### ISSUE TITLE
A way to force package to not be compatible with a Meteor release

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7537]
Currently it seems there is no way that you could make a package not be compatible with a Meteor release. For example, Meteor 1.4 ships with new MongoDB version. But it is unclear if my PeerDB package is compatible with new MongoDB. So I would like to make sure nobody upgrades to new MongoDB and looses data if they are using my package. But it seems there is no way to prevent that. Automatic upgrade process would simply upgrade everything.

**Comment by tmeasday** [comment]
@mitar can you not set a maximum version of the `mongo` package?

**Comment by mitar** [comment]
The `mongo` package version was changed from `1.1.9` (Meteor 1.3) to `1.1.10` (Meteor 1.4). MDG seems to not follow really semver. `mongo` package could for example track Meteor versions, like `3.2.0_1` for this release.

**Comment by mitar** [comment]
I think maybe because you have to bump all packages for every release, package versions are not updated critically, but automatically. Just to satisfy the administration.

**Comment by tmeasday** [comment]
In this case the API of the `mongo` package has not changed, so I'm unsure about whether that's strictly a mistake.

The `npm-mongo` package bumped a minor version at least (`1.4.45` -> `1.5.45`).

> I think maybe because you have to bump all packages for every release, package versions are not updated critically, but automatically. Just to satisfy the administration.

This is generally speaking true. We need to improve this process.

**Comment by mitar** [comment]
Good point. API didn't really change. But underlying things did. Maybe there should be some other way to specify this core Meteor features and depend on them.

**Comment by tmeasday** [comment]
I think it would probably make sense for the `npm-mongo` version to "encode" the version of the mongo driver it wraps. Realistically the version number should be like `2.2.4-1` or something. This is our bad.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=A%20way%20to%20force%20package%20to%20not%20be%20compatible%20with%20a%20Meteor%20release&body=Migrated%20from:%20meteor/meteor%237537) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
