### ISSUE TITLE
update to 1.4 causing duplicate application tag

### ISSUE THREAD

**Issue by mjwheatley** [meteor/meteor#7542]
I am attempting to update my [Meteor-Ionic2 starter ](https://github.com/mjwheatley/Ionic2-Meteor1.3-Starter.git) repository to the latest Meteor 1.4 release.

After updating to Meteor 1.4, I start the app using my `npm start` script.  The app starts with no errors, but the UI does not appear.  When I inspect the app in Chrome I see a duplication in the elements.  Inside my ion-app is another html, head, body, ion-app.

I have seen this in the past when the path to an html template was wrong, but I have double checked all of the paths and they are correct.  Plus, it was all working prior to the update.

I would appreciate any insight or assistance in resolving this issue.

**Comment by Metrophobe** [comment]
Can you replicate the code here which is causing the issue?

**Comment by mjwheatley** [comment]
No, I am unable to do so as I do not know what is causing the issue and I am receiving no error messages.  Perhaps it is a change in the compilers.  I noticed that the update also started trying to compile my scss files, which it had previously not done, so I had to move those files around.  

Or perhaps it may be something with the bootstrapping of the application, which is occurring in the app/client/lib/_meteor-ionic-app.ts file.  

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import {provide, Type, Provider, IterableDiffers, Component, PLATFORM_DIRECTIVES, enableProdMode} from '@angular/core';
import {METEOR_PROVIDERS} from 'angular2-meteor';
import {IONIC_DIRECTIVES, ionicProviders, ionicBootstrap} from 'ionic-angular';
declare var Reflect;

export function MeteorIonicApp(args:any) {
    return function(cls) {
        // get annotations
        let annotations = Reflect.getMetadata('annotations', cls) || [];
        // set selector if undefined
        args.selector = args.selector || 'ion-app';
        // if no template was provided, default so it has a root <ion-nav>
        if (!args.templateUrl && !args.template) {
            args.template = '<ion-nav></ion-nav>';
        }
        // create @Component
        annotations.push(new Component(args));
        // redefine with added annotations
        Reflect.defineMetadata('annotations', annotations, cls);
        // wait for meteor platform
        Meteor.startup(function() {
            // define array of bootstrap providers
            var providers = ionicProviders(args.providers).concat(args.providers || [], METEOR_PROVIDERS);
            // auto add Ionic directives
            let directives = args.directives ? args.directives.concat(IONIC_DIRECTIVES) : IONIC_DIRECTIVES;
            // automatically provide all of Ionic's directives to every component
            providers.push(provide(PLATFORM_DIRECTIVES, { useValue: [directives], multi: true }));
            if (args.prodMode) {
                enableProdMode();
            }
            ionicBootstrap(cls, providers, args.config);
            return cls;
        });

        return cls;
    }
}
```

**Comment by abernix** [comment]
Please provide a very simple reproduction repo link (bare minimum please, per [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)) and steps here in this issue so whoever looks at this doesn't need to go digging around in another project.  Thanks!

**Comment by mjwheatley** [comment]
The referred project is a simple reproduction link.  It is a starter repo to help people start using Meteor and Ionic2 together.

Steps to reproduce the issue:
Verify the application runs before the upgrade by following the "Getting Started" section of the README.

Perform the update to Meteor 1.4:
```
meteor update

// update indirect dependencies
meteor update autoupdate barbatus:typescript caching-compiler ddp-client ddp-server

// update MongoDB
meteor reset

npm start
```

**Comment by mjwheatley** [comment]
This issue was resolved by downgrading the angular2-compilers package from v0.6.0 to v0.5.7
