### ISSUE TITLE
meteor 1.4.0.1 error trying to add "accounts-password"

### ISSUE THREAD

**Issue by spiral2k** [meteor/meteor#7543]
i have installed "windows-build-tools", i have reinstall meteor and node and im keep getting this error with "accounts-password".

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While downloading npm-bcrypt@0.8.7...:
   error: Command failed:
   C:\Users\Meni\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.window
s.x86_32\dev_bundle\bin\npm.cmd
   rebuild --no-bin-links --update-binary
   gyp ERR! build error
   gyp ERR! stack Error: `C:\Program Files
   (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
   gyp ERR! stack     at ChildProcess.onExit
   (C:\Users\Meni\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windo
ws.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:276
:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 6.1.7601
   gyp ERR! command
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js"
   "rebuild"
   gyp ERR! cwd
   C:\Users\Meni\AppData\Local\Temp\mt-19eefq1\npm\node_modules\.temp-jdjkfa\nod
e_modules\bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 6.1.7601
   npm ERR! argv
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!
   C:\Users\Meni\AppData\Local\Temp\mt-19eefq1\npm\node_modules\.temp-jdjkfa\npm
-debug.log
   gyp ERR! build error
   gyp ERR! stack Error: `C:\Program Files
   (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
   gyp ERR! stack     at ChildProcess.onExit
   (C:\Users\Meni\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windo
ws.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:276
:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 6.1.7601
   gyp ERR! command
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js"
   "rebuild"
   gyp ERR! cwd
   C:\Users\Meni\AppData\Local\Temp\mt-19eefq1\npm\node_modules\.temp-jdjkfa\nod
e_modules\bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 6.1.7601
   npm ERR! argv
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Meni\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt
-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!
   C:\Users\Meni\AppData\Local\Temp\mt-19eefq1\npm\node_modules\.temp-jdjkfa\npm
-debug.log

**Comment by Metrophobe** [comment]
this is a known issue apparently. I would suggest that you add "bcrypt" in your packages.js (located in the .meteor folder) and it should load for you. However make sure you put it before the dependency (bcrypt) is being requested.

**Comment by benjamn** [comment]
@spiral2k A couple of diagnostic questions:
1. What does `meteor node -p process.env.GYP_MSVS_VERSION` print for you?
2. Are you able to run `meteor npm install bcrypt` successfully in your application directory?

**Comment by Joe312341** [comment]
I have the same exact error on win 10 and win 7, everything worked fine on OSX

To answer your question
1. 2010
2. Yes I can run the command

**Comment by Joe312341** [comment]
@Metrophobe 
If I put npm-bcrypt anywhere in the package.js and run `meteor` I get the exact same error too

**Comment by Metrophobe** [comment]
@Joe312341  it is packages.js inside the .meteor folder and not package.js I am assuming you added it in with the other packages correct?

**Comment by Joe312341** [comment]
`meteor add npm-bcrypt` does not work, it throws the same error as posted above.

`meteor npm install bcrypt` works just fine though

My node-gyp version is up-to-date (v3.4) when typing `node-gyp -v` into the project folder

**Comment by benjamn** [comment]
@Joe312341 and @Metrophobe I'm glad you're trying to help, but your advice is off-base. There is no file called `packages.js` in the `.meteor` directory, for example, and @spiral2k has already installed `npm-bcrypt@0.8.7` via the `accounts-password` package. This issue is pretty clearly about getting a compiler toolchain to work on Windows, not installing `npm-bcrypt`. Please don't offer any more advice until @spiral2k has had a chance to respond, and you're sure you're talking about the same problems. Thanks!

**Comment by Joe312341** [comment]
@benjamn I have exactly the same problem as spiral2k and have not offered any advice. To the contrary I was trying to answer the question you put to spiral2k. Just like him I also installed "windows-build-tools" I am in the exact same situation.

**Comment by Metrophobe** [comment]
@benjamn thanks for pointing out that I had a misprint it should have read packages.json not packages.js.  And just for the record, I provided the possible solution because in my situation the method described _always_ resolved the issue; tried and tested.

**Comment by benjamn** [comment]
@Joe312341 My mistake, you're right. For what it's worth, I do not expect that adding `npm-bcrypt` to your `.meteor/packages` file will help with your problem.

While `windows-build-tools` is exciting, we haven't had a chance to verify that it works for everyone. If you have the ability to install the [2015 build tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159), that's the official recommendation.

@Metrophobe Still not sure what you're referring to. There is a file called `.meteor/packages`, but you should not edit it directly. Instead, `meteor add npm-bcrypt` will update that file for you.

**Comment by Joe312341** [comment]
@benjamn I actually did install those tools, after windows-build-tools did not work.

The guide says the following

> To test that your compiler toolchain is installed and working properly, try installing any binary npm package in your application using meteor npm. For example, run meteor npm install bcrypt then meteor node, then try calling require("bcrypt") from the Node shell.

I did that and it all worked fine. But running anything above Meteor 1.4 does not work. I tried creating a clean new project and just adding `accounts-password` but it resulted in the same error as posted above

**Comment by benjamn** [comment]
@Joe312341 Is there a file in `C:\Users\YourName\` called `AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\bcrypt\.meteor-last-rebuild-version.json`? What does it say?

If you go to `AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\` can you run `meteor npm rebuild bcrypt`?

**Comment by Joe312341** [comment]
I have the following output

`{
  "http_parser": "1.2",
  "node": "0.10.45",
  "v8": "3.14.5.9",
  "ares": "1.9.0-DEV",
  "uv": "0.10.36",
  "zlib": "1.2.8",
  "modules": "11",
  "openssl": "1.0.1t"
}
`
I can rebuild and the output wont change..

One line has a warning, but im guessing thats standard?

`..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data`

**Comment by Metrophobe** [comment]
@benjamn yes ok

**Comment by benjamn** [comment]
@Joe312341 Ok great, that indicates that `npm-bcrypt@0.8.7` was somehow actually built with Node 0.10.45, which would explain why it needs to be rebuilt. Not why the rebuild is failing, unfortunately, but at least it's a start. Thanks for your patience.

**Comment by benjamn** [comment]
Hmm, ok, so, it looks like when you're using Node 4, compiling `npm-bcrypt` requires a C++11 compiler, which means you have to have at least Visual C++ 2012. This seems odd to me because the 2010 version worked with Node 0.10.46, but I guess the version of V8 that Node 4 uses just isn't compatible with older compilers.

Do you have the option of installing [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)? If so, that's definitely your best option.

**Comment by Joe312341** [comment]
Got it working on Win7, not on Win10 yet unfortunately (but that is not a priority for now). I installed Microsoft Build Tools 2015, but no change and I have Visual C++ (2012, 2013,2015)

In any case you have been very helpful, thanks for taking the time!

**Comment by spiral2k** [comment]
@benjamn 
1) 2015

2) npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by storedev99** [comment]
@benjamn Your suggestion to install "Microsoft Build tool 2015" worked perfectly to install the accounts-ui package. whereas when i continue to install the accounts-password package i still get the same error

```
D:\pros\mob\Meteor\resolutions>meteor add accounts-ui

Changes to your project's package version selections:

accounts-base          added, version 1.2.9
accounts-ui            added, version 1.1.9
accounts-ui-unstyled   added, version 1.1.12
ddp-rate-limiter       added, version 1.0.5
less                   added, version 2.6.5
localstorage           added, version 1.0.11
rate-limit             added, version 1.0.5
service-configuration  added, version 1.0.10


accounts-ui: Simple templates to add login widgets to an app

D:\pros\mob\Meteor\resolutions>meteor add accounts-password
 => Errors while adding packages:

While loading package npm-bcrypt@0.8.7:
error: Command failed: C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild
--no-bin-links --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.
js"
"rebuild"
gyp ERR! cwd C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1624gg\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1624gg\npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.
js"
"rebuild"
gyp ERR! cwd C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1624gg\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1624gg\npm-debug.log
```
The contents of .meteor-last-rebuild-version.json is

```
{
  "http_parser": "1.2",
  "node": "0.10.45",
  "v8": "3.14.5.9",
  "ares": "1.9.0-DEV",
  "uv": "0.10.36",
  "zlib": "1.2.8",
  "modules": "11",
  "openssl": "1.0.1t"
}
```

**Comment by AlokJoshi** [comment]
I had the same issue and I installed windows-build-tools using the following
npm install --global --production windows-build-tools
and everything worked again.

**Comment by entagy** [comment]
Had same issue on Windows 7

- removed NodeJS (was very old version)
- Run as administrator using CMD <code> npm install --global --production windows-build-tools</code>
- The run <code>meteor add accounts-password</code> - and all works!

**Comment by fvpDev** [comment]
Also, don't forget about this: https://guide.meteor.com/1.4-migration.html

**Comment by storedev99** [comment]
@fvpDev  @AlokJoshi  @entagy  did the same. Is there any pre-requisite on your windows installation apart from this ? did you have a GCC compiler separately ?

```
##D:\Self_pros\mobility\Meteor\resolutions>npm install --global --production windows-build-tools

> windows-build-tools@0.4.1 postinstall C:\Users\some_user\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.11.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.11.msi. Saved to C:\Users\some_user\.windows-build-tools\python-2.7.11.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |Successfully installed Python 2.7
Waiting for installers... -Successfully installed Visual Studio Build Tools.
C:\Users\some_user\AppData\Roaming\npm
`-- windows-build-tools@0.4.1

------------------------------------------------------------------------------------------------------------

D:\Self_pros\mobility\Meteor\resolutions>meteor add accounts-password
 => Errors while adding packages:

While loading package npm-bcrypt@0.8.7:
error: Command failed: C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
rebuild --no-bin-links --update-binary
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable
"\C\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the
PYTHON env variable.
gyp ERR! stack     at failNoPython
(C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib
\configure.js:449:14)
gyp ERR! stack     at
C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\
configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_module
s\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1idt3vs\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cl
i.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1idt3vs\npm-debug.log
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable
"\C\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the
PYTHON env variable.
gyp ERR! stack     at failNoPython
(C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib
\configure.js:449:14)
gyp ERR! stack     at
C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.13\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\
configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\node_module
s\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1idt3vs\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\some_user\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.13\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cl
i.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\some_user\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1idt3vs\npm-debug.log


------------------------------------------------------------------------------------------------------------


## D:\Self_pros\mobility\Meteor\resolutions>node --version
v4.4.7
```

**Comment by fvpDev** [comment]
@storedev99, I have no knowledge whatsoever about GCC... what do you get for `echo %PATH%` in cmd? Maybe this has something to do with administrative rights or the ability to use python on a different drive other than the one on which it was installed? (this is completely over my head lol)

**Comment by benjamn** [comment]
This should be fixed with `npm-bcrypt@0.8.7_1`, which is used by `accounts-password@1.2.13` (just published). To update, you'll need to be running Meteor 1.4 (which [relaxes core package constraints](http://info.meteor.com/blog/announcing-meteor-1.4)) and execute `meteor update` in your application directory. If the version solver refuses to update `npm-bcrypt`, it may help to `meteor remove accounts-password` and `meteor remove npm-bcrypt` first, before adding them back.

Note that this version of `npm-bcrypt` comes with a prebuilt version of the `bcrypt` npm package, which is how we've traditionally provided the `bcrypt` functionality. The next minor version of `npm-bcrypt` will use a pure-JavaScript implementation, with the option to `meteor npm install bcrypt` in your application if you need to use the native implementation. See [this pull request](https://github.com/meteor/meteor/pull/7595) for more details.

**Comment by storedev99** [comment]
@benjamn that solved all issues man.. thanks a ton..
posting the log below

```

D:\Self_pros\mobility\Meteor\resolutions>meteor --version
Meteor 1.4-beta.13

D:\Self_pros\mobility\Meteor\resolutions>meteor update
resolutions: updated to Meteor 1.4.0.1.

Changes to your project's package version selections from updating package versions:

ecmascript-runtime  upgraded from 0.3.12 to 0.3.13


Newer versions of the following indirect dependencies are available:
 * autoupdate 1.2.11 (1.3.11 is available)
 * caching-compiler 1.0.6 (1.1.6 is available)
 * ddp-client 1.2.9 (1.3.0 is available)
 * ddp-server 1.2.10 (1.3.9 is available)
 * http 1.1.8 (1.2.8 is available)
 * less 2.6.5 (2.7.4 is available)
 * templating 1.1.14 (1.2.13 is available)
To update one or more of these packages, pass their names to `meteor update`.

D:\Self_pros\mobility\Meteor\resolutions>meteor remove accounts-password
accounts-password is not a direct dependency in this project.

D:\Self_pros\mobility\Meteor\resolutions>meteor remove npm-bcrypt
npm-bcrypt is not a direct dependency in this project.

D:\Self_pros\mobility\Meteor\resolutions>meteor add accounts-password@1.2.13

Changes to your project's package version selections:

accounts-password  added, version 1.2.13
email              added, version 1.1.16
npm-bcrypt         added, version 0.8.7_1
sha                added, version 1.0.8
srp                added, version 1.0.9


accounts-password: Password support for accounts 
```

And when you say it will be a pure javascript implementation do you mean bcryptjs ?
If yes, can you please let us know the reasons for it ? 
Last time when i was checking the bcrypt related issues for this error, there were several discussions about performance hit and security seeding or something when native library is compared with the js one..

**Comment by davidpintos** [comment]
so i did the same for my project and now it's working ok, but what is the last version of accounts-password package ?

**Comment by davidpintos** [comment]
it works ok with the version 1.2.14, thanks

**Comment by Amritpd** [comment]
@benjamn Is it better to use the pure-Javascript implementation of bcrypt or use the native implementation, because when I try to run ` meteor npm install --save bcrypt` I get the same error log as @spiral2k . Thanks

**Comment by noelkoutlis** [comment]
most answers in meteor forum say "meteor npm install --global --production windows-build-tools" in PowerShell solved the problem. imo bycryptjs is a drop-in replacement, api is the same
npm uninstall --save bcrypt
npm install --save bcryptjs

**Comment by spiral2k** [comment]
you can close this issue, meteor fixed that. thanks all for the support.
