### ISSUE TITLE
Piping to Meteor Shell Broken

### ISSUE THREAD

**Issue by veered** [meteor/meteor#7547]
In Meteor 1.3 `echo "console.log('hello');" | meteor shell` would cause 'hello' to be printed to the Meteor server's stdout. In Meteor 1.4 it fails and prints:

```
console.log('hello');
Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

> Shell exiting.
```

The ability to pipe to the meteor shell was added here https://github.com/meteor/meteor/pull/5575.

Edit:
I went back to a Meteor 1.3.4 project, and piping to the meteor shell still doesn't work. Could this be because I've upgraded my global Meteor version to `1.4.0.1`?

**Comment by abernix** [comment]
I think this is the same root issue as #7504 so I'm going to close it as a duplicate and note the problem there as it's likely the same scope of work to fix it.  Thanks for reporting this!
