### ISSUE TITLE
Meteor won't generate utf-8 valid Javascript

### ISSUE THREAD

**Issue by JohnRodney** [meteor/meteor#7551]
Meteor 1.3.5.1 - OS X El Capitan 10.11.4 (15E65)

In order to build a chrome extension with an inject script the JavaScript file must be utf-8 compatible.  The regex's generated in a client build include unsupported utf-8 characters.  When installing your built meteor client to a chrome extension with the javascript file listed as a "content script" the error will appear explaining that the javascript file is not in utf-8 format.

CLI tools such as iconv will not convert the file directly to utf-8 due to errors in recognizing the generated file format.  

Hacky Workaround: 
You can drag and drop the hash named javascript file into a browser which is able to convert the file to utf-8 then copy paste the result back into your editor.  Then the file will install in a extension successfully.  This does not allow a good workflow for testing and editing the meteor app.  Does meteor have any supported utf-8 builds or is this a solution that we will have to work into a build by adding a post proccess to the build?

**Comment by abernix** [comment]
I'll start by saying I'm fairly confused by what you're talking about.

> The regex's generated in a client build include unsupported utf-8 characters.

What do you mean by this?  Can you provide some example of a file (Gist/PasteBin, please) that was generated by Meteor that has "unsupported utf-8 characters"?

> You can drag and drop the hash named javascript file into a browser which is able to convert the file to utf-8 then copy paste the result back into your editor. Then the file will install in a extension successfull

Can you provide a before-and-after sample of what you're referring to?

**Comment by JohnRodney** [comment]
@abernix my apologies on the poor explanation.  I am building a chrome extension and bundling my client of the meteor build process to run inside the extension and then connecting to my meteor server once the client has been injected to my target webpage.  

Here is an example of before file:
[48001838c9e0962b1579b8a9a4c8facaa71c899e.js.zip](https://github.com/meteor/meteor/files/397787/48001838c9e0962b1579b8a9a4c8facaa71c899e.js.zip)
And the after conversion file: 
[meteor.js.zip](https://github.com/meteor/meteor/files/397788/meteor.js.zip)

Here are some diff screenshots of the utf and non utf character comparison side by side.
<img width="1116" alt="screen shot 2016-08-02 at 1 01 11 pm" src="https://cloud.githubusercontent.com/assets/11075982/17339389/4d84670c-58b1-11e6-9750-88fc64a43e3e.png">
<img width="1126" alt="screen shot 2016-08-02 at 1 00 50 pm" src="https://cloud.githubusercontent.com/assets/11075982/17339393/50d6d84a-58b1-11e6-8a49-34f3443a32e9.png">



Note: Github doesn't allow the js file to upload so I had to zip

I understand if this is expected behavior you can close I was just trying to find out if this was a bug or a expected situation before working on a post processing solution.  Thank you for your time.

**Comment by abernix** [comment]
Interesting!  Thanks for the additional information – much more clear now.  I can't say for sure this is intended behavior, but I'm also not sure if its a bug. :grin:

To narrow down the problem, I'm curious if this problem goes away if you remove the `standard-minifiers-js` package from your project and rebuild?

**Comment by abernix** [comment]
Any updates on this, @JohnRodney?

**Comment by hwillson** [comment]
We haven't heard anything back about this in a while, so as part of the old issue cleanup process, I'll close it for now. If you're still having problems using a recent version of Meteor, please post back and let us know. Thanks for posting this originally!
