### ISSUE TITLE
Meteor 1.4.0.1 - error on 'add accounts-password' (Mac)

### ISSUE THREAD

**Issue by jamesarmenta** [meteor/meteor#7553]
Getting a very extensive error after 'meteor add accounts-password'. Toward the end of the error terminal outputs this:
```
node v4.4.7
npm  v3.10.5
code ELIFECYCLE
bcrypt@0.7.7 install: `node-gyp rebuild`
Exit status 1

Failed at the bcrypt@0.7.7 install script 'node-gyp rebuild'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the bcrypt package,
not with npm itself.
Tell the author that this fails on your system:
    node-gyp rebuild
You can get information on how to open an issue for this project with:
    npm bugs bcrypt
```
I've seen a similar topic on the forums, but triggered only for Windows users, while I am on a Mac. Is this an issue with Meteor or with bcrypt?

**Comment by laosb** [comment]
Did you install the build toolchain? https://guide.meteor.com/1.4-migration.html#binary-packages-require-build-toolchain

**Comment by jamesarmenta** [comment]
@laosb Ah, perfect. It took a rebuild to get it working. Thanks so much!

**Comment by jamesarmenta** [comment]
Oddly enough, I believe `meteor add npm-bcrypt` solved it.
