### ISSUE TITLE
[1.4] assertion error on modulus ("undefined" === "function")

### ISSUE THREAD

**Issue by djwatt5** [meteor/meteor#7554]
When deploying to modulus, the app does not start and users will only see `Unable to connect to any application instances.`

The app does not have any errors or warnings in localhost, and all dependencies were updated. This seems to be an error related to how modulus builds the webapp. The error log is the following:
```
> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> node ../../main


assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/mnt/app/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

npm ERR! Linux 3.13.0-88-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.41/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/bundle/programs/server/npm-debug.log
Now using node v0.10.41 (npm v3.9.6)
Found package.json: ./bundle/programs/server/package.json
Running command: npm start
```

The error was reproduced by somebody else: (http://www.initcode.info/issues_deploying_meteor_app_to_modulus)

**Comment by abernix** [comment]
You are using the wrong version of Node in production for Meteor 1.4 which requires Node 4.4.7.  Please see #7475, specifically my comment here: https://github.com/meteor/meteor/issues/7475#issuecomment-235229269

Closing as duplicate.

**Comment by gschleic** [comment]
I am having this same issue.  meteor node -v show  4.4.7,  node -v :node -v
v5.10.1...
Where is it getting this old 0.10.x version from and how do I get the "modulus deploy" command to pick up the right version?

**Comment by abernix** [comment]
You should contact Modulus or their docs.  That Node version is being provided by their server (and as it is is a old version of 0.10).

**Comment by gschleic** [comment]
Thanks Jesse. I will do that. They have a new Meteor “runtime” setting, whereas before Meteor was wrapped in Node. I think this is something to so with that change, along with Meteor 1.4 officially moving up to Node 4.4…

Glenn

**Comment by deanius** [comment]
@gschleic - Did you get a resolution?

**Comment by secondspace** [comment]
Any luck, guys?

I'd like to deploy my app using meteor 1.4 to Modulus.

**Comment by gschleic** [comment]
No, not yet…getting frustrated. 

Following the thread / suggestions here:

https://github.com/onmodulus/docker-build-meteor/issues/25 <https://github.com/onmodulus/docker-build-meteor/issues/25>

**Comment by gschleic** [comment]
Same!

**Comment by secondspace** [comment]
I spoke with Modulus on Friday (8/5) and they told me it should be compatible with 1.4 by this Friday (8/12).

Crossing my fingers.

**Comment by gschleic** [comment]
Thanks for the info…
