### ISSUE TITLE
CSS animation keyframes not supported by standard-minifiers

### ISSUE THREAD

**Issue by Slanman3755** [meteor/meteor#7555]
Meteor 1.4.0.1
Standard Minifiers 1.0.6
minifier-css  1.2.13
standard-minifier-css  1.1.8

App crashes when trying to use CSS keyframes for animation.  The app should not crash because the CSS is correct.

Error:

Errors prevented startup:

While minifying app stylesheet:
app/client/css/main.css:67:10: property missing ':'

Your application has errors. Waiting for file change.

Replication:
Make a new meteor project
Add this code to a css file:
`@keyframes rainbow {
0% {color: #ff0000;}
10% {color: #ff8000;}
20% {color: #ffff00;}
30% {color: #80ff00;}
40% {color: #00ff00;}
50% {color: #00ff80;}
60% {color: #00ffff;}
70% {color: #0080ff;}
80% {color: #0000ff;}
90% {color: #8000ff;}
100% {color: #ff0080;}
}
`
Run the meteor project

**Comment by laosb** [comment]
It does work for me.

![image](https://cloud.githubusercontent.com/assets/2545261/17352875/255e52bc-596d-11e6-8619-3e669ab21aea.png)

![image](https://cloud.githubusercontent.com/assets/2545261/17352884/3b220d6e-596d-11e6-9f08-aa352acf1ebd.png)

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to work.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
