### ISSUE TITLE
meteor fails in modules-runtime with cannot find module 'assert/'

### ISSUE THREAD

**Issue by rajpa** [meteor/meteor#7557]
![image](https://cloud.githubusercontent.com/assets/6967216/17353935/d52c128a-5961-11e6-8658-7b119f5243e6.png)

Hi

Due to this error, I am unable to run the app in production. Pls help to resolve this.

Meteor version 1.4.0.1

Regards

**Comment by laosb** [comment]
Please provide a full reproduction.

**Comment by rajpa** [comment]
Thanks @laosb 

I changed all the bootstrap code to materialize (except for select2) and suddenly the app wont deploy in production. While it runs in dev mode, it fails in production.

Here is my package list:

accounts-password                                      1.2.12  Password ...
accounts-ui                                            1.1.9  Simple tem...
alanning:roles                                         1.2.15  Authoriza...
aldeed:autoform                                        5.8.1  Easily cre...
aldeed:autoform-bs-datetimepicker                      1.0.6  Custom boo...
aldeed:autoform-select2                                2.0.2  Custom sel...
aldeed:collection2                                     2.9.1  Automatic ...
aldeed:schema-index                                    1.0.1  Control so...
aslagle:reactive-table                                 0.8.34  A reactiv...
blaze-html-templates                                   1.0.4  Compile HT...
chart:chart                                            1.0.1-beta.4  Cha...
cordova:cordova-plugin-inappbrowser                    0.5.4
cordova:de.appplant.cordova.plugin.local-notification  0.8.4
dburles:collection-helpers                             1.0.4  Transform ...
dispatch:deep-link                                     4.0.4  Handle dee...
ecmascript                                             0.5.7  Compiler p...
edgee:slingshot                                        0.7.1  Directly p...
es5-shim                                               4.6.13  Shims and...
fastclick                                              1.0.12  Faster to...
fortawesome:fontawesome                                4.5.0  Font Aweso...
fourseven:scss                                         3.8.0_1  Style wi...
iron:router                                            1.0.13  Routing s...
jquery                                                 1.11.9  Manipulat...
juliancwirko:postcss                                   1.1.1  Minifier f...
materialize:materialize                                0.97.7  Materiali...
meteor                                                 1.2.16  Core Mete...
meteor-base                                            1.0.4  Packages t...
meteorhacks:kadira                                     2.30.0  Performan...
mizzao:autocomplete                                    0.5.1  Client/ser...
mobile-experience                                      1.0.4  Packages f...
momentjs:moment                                        2.14.4  Moment.js...
mongo                                                  1.1.10  Adaptor f...
mpowaga:autoform-autocomplete                          0.0.2  Autocomple...
mrt:moment-timezone                                    0.2.1  Timezone s...
natestrauser:select2                                   4.0.2  Select2 is...
raix:handlebar-helpers                                 0.2.5  Handlebar ...
raix:push                                              3.0.2  Isomorphic...
random                                                 1.0.10  Random nu...
reactive-var                                           1.0.10  Reactive ...
reywood:publish-composite                              1.4.2  Publish a ...
sacha:spin                                             2.3.1  Simple spi...
service-configuration                                  1.0.10  Manage th...
session                                                1.1.6  Session va...
standard-minifier-js                                   1.1.8  Standard j...
timbrandin:autoform-slingshot                          1.1.2  File uploa...
tracker                                                1.1.0  Dependency...
tsega:bootstrap3-datetimepicker                        4.17.37_1  Bootst...
twbs:bootstrap                                         3.3.6  The most p...
udondan:slick                                          1.3.11_1  the las...
underscore                                             1.0.9  Collection...
utilities:state-transitions                            0.1.3  A simplifi...
yogiben:admin                                          1.2.4* A complete...
zimme:select2-bootstrap3-css                           0.1.1* CSS to mak...

Thanks again!

**Comment by abernix** [comment]
Again, please provide a reproduction.  A list of your packages is not enough for a developer to recreate the problem themselves as that snippet by itself is not enough to isolate the problem, or even to determine if the problem is in Meteor itself: [More information on reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)

A reproduction should be a minimal Meteor project showing this problem; remove large portions of your project and packages until this problem goes away, then try to reproduce it with as little as possible.

Without this, nobody will be able to assist you.

**Comment by rajpa** [comment]
Thanks @abernix.

I did the following:

1.  meteor create testoba

copy .meteor\packages containing all the packages above.

2. meteor

I got the errors below:

<img width="543" alt="metererror4" src="https://cloud.githubusercontent.com/assets/6967216/17355002/040fb21a-596b-11e6-9809-b52eb190a1f6.png">

This is the browser window:

<img width="897" alt="metererror5" src="https://cloud.githubusercontent.com/assets/6967216/17355019/2a187a14-596b-11e6-9463-4bdc48c8dc2c.png">

Can you pls see if you can reproduce.

Thanks rajpa

**Comment by rajpa** [comment]
All the packages that meteor complains about are there in the meteor-node-stubs/node_modules directory.. I tried meteor npm rebuild and meteor npm install again and still the same exceptions are being thrown.

**Comment by abernix** [comment]
What are the contents of your `package.json`?

Also, what happens if you run the following in the root of your project?:

    meteor npm install --save meteor-node-stubs@~0.2.0

**Comment by rajpa** [comment]
meteor is unable to find the following modules which are all there in the meteor-node-stubs\node_modules directory..

Directory of c:\Users\rajpa\Desktop\meteor\medio\testoba\node_modules\meteor-node-stubs\node_modules

03-Aug-16  12:03 PM    <DIR>          .
03-Aug-16  12:03 PM    <DIR>          ..
03-Aug-16  12:03 PM    <DIR>          assert
03-Aug-16  12:03 PM    <DIR>          browserify-zlib
03-Aug-16  12:03 PM    <DIR>          buffer
03-Aug-16  12:03 PM    <DIR>          console-browserify
03-Aug-16  12:03 PM    <DIR>          constants-browserify
03-Aug-16  12:03 PM    <DIR>          crypto-browserify
03-Aug-16  12:03 PM    <DIR>          domain-browser
03-Aug-16  12:03 PM    <DIR>          events
03-Aug-16  12:03 PM    <DIR>          http-browserify
03-Aug-16  12:03 PM    <DIR>          https-browserify
03-Aug-16  12:03 PM    <DIR>          os-browserify
03-Aug-16  12:03 PM    <DIR>          path-browserify
03-Aug-16  12:03 PM    <DIR>          process
03-Aug-16  12:03 PM    <DIR>          punycode
03-Aug-16  12:03 PM    <DIR>          querystring-es3
03-Aug-16  12:03 PM    <DIR>          readable-stream
03-Aug-16  12:03 PM    <DIR>          stream-browserify
03-Aug-16  12:03 PM    <DIR>          string_decoder
03-Aug-16  12:03 PM    <DIR>          timers-browserify
03-Aug-16  12:03 PM    <DIR>          tty-browserify
03-Aug-16  12:03 PM    <DIR>          url
03-Aug-16  12:03 PM    <DIR>          util
03-Aug-16  12:03 PM    <DIR>          vm-browserify

**Comment by rajpa** [comment]
Here is what I have in package.json

{
  "name": "testoba",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "^0.2.3"
  }
}

after running 
.. meteor npm install --save meteor-node-stubs@~0.2.0

there was no change - same exceptions for same modules..

**Comment by abernix** [comment]
Please make this `testoba` project into a Git repo and upload it to GitHub and then share the link.  Also provide:

* The exact version of Windows that you are using.
* What browser version that is (Edge?)?
* The output of `meteor --version` when run outside a project directory (i.e. before `meteor create`)

I will try to recreate this afternoon in a Window's environment.

**Comment by abernix** [comment]
I don't have IE 11 on my VirtualBox to test this, but this works fine for me on Windows 10 with Edge and also in Chrome.

Please try running:

    meteor reset

...in your project and see if the problem resolves itself.  Also, if you still have problems, try deleting your `node_modules` directory and running `meteor npm install` again.

Also, you have a lot of packages in this reproduction.  I'm sure you can remove some of the packages, and keep removing them until the problem disappears.  I don't think you will experience this problem on a completely empty project.  It's possible you're using a package that hasn't been updated for 1.4 (or is no longer supported).

**Comment by rajpa** [comment]
Hi @abernix

Please try to run meteor --production to see the errors.

Thanks a bunch!

**Comment by rajpa** [comment]
hi @abernix 

fixed this by moving fourseven:scss and materialize:materialize to the top of the package list (just after the core packages) in the packages file!!! the packaging order matters for production i guess....

thanks

**Comment by abernix** [comment]
Glad you got it figured out!  That is likely because `materialize:materialize` is depending on an old 3.2.0 version of `fourseven:scss` which is broken – they really should update that.

**Comment by rajpa** [comment]
😀 it happens with the latest version as well.

Thanks a bunch.

Cheers
Rajpa
