### ISSUE TITLE
Explore an option for `meteor config` similar to `npm config`

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#7559]
It would be nice if there was a way to provide configuration options for **non-sensitive** information to the `meteor-tool`, such as `--port`, the proposal for `--skip-release-check` in #7445, and other development items which are frequently only configurable via increasingly-clunky `ENV` variables.  Ideally this would be done using a tool similar to [`npm config`](https://docs.npmjs.com/cli/config) and its [`npmrc`](https://docs.npmjs.com/files/npmrc) derivitive so it could also have "global" preferences where options could be set for all your Meteor projects, including the ability to have a version controlled file in a project that would work across multiple developers, CI builds, etc.

I believe this is only relevant for the development environment specifically for using the `meteor` command line tool, **not for production**, which I believe is fine the way it is using `Meteor.settings` + `settings.json` or the `METEOR_SETTINGS` environment variable.  

The [`config` NPM package](https://www.npmjs.com/package/config) is the first thing that comes to mind, but I'd love to see other proposals.

**Comment by aaroncalderon** [comment]
If meteor where to respect the `~\.*rc` convention other tools have implemented (e.g. git, npm, bower, tsd) and use said configurations we would not have to re-invent the wheel.

My point being, lets honor `~\.npmrc` and the issues we all face with runing `meteor npm install` behind a proxy. And we could also have meteor implement a similar approach, we would be able to do without those environment variables.

**Comment by abernix** [comment]
@aaroncalderon This feature request was not meant to have anything to do with changing NPM settings in relation to Meteor.  It's simply saying that Meteor has certain parameters (of its own), which would be nice to configure with a tool roughly similar to `npm config`.  Meteor currently has no global "tool" config and this is what that was aiming to be.

Briefly though: If you are using `npm config` (without the `--global` flag) in the root of the Meteor project, you will not get the results you are looking for since Meteor's functional root as far as NPM is concerned is not the same – as you have found.  That being said (I haven't tested this), it's plausible that if you use `npm config set proxy <proxy> --global` Meteor would pick it up without you having to go to this effort.  Additionally, I'm fairly sure that the `HTTP_PROXY` (and similar/related) environment variables work properly with Meteor.  Either way, this is a discussion for another issue/the forums as this is about something else entirely.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Explore%20an%20option%20for%20%60meteor%20config%60%20similar%20to%20%60npm%20config%60&body=Migrated%20from:%20meteor/meteor%237559) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
