### ISSUE TITLE
add a page with all API docs and make it print-friendly

### ISSUE THREAD

**Issue by sorcamarian** [meteor/meteor#7565]
A single page with all the API Docs would be much simple to print.
Also, the page should be print-friendly. 

The sidebar doesn't look nice in the current pages. 
![image](https://cloud.githubusercontent.com/assets/12509753/17375148/7ec6b240-59b8-11e6-860a-a0ff96ecbf22.png)

For example Node.js has: https://nodejs.org/api/all.html

**Comment by abernix** [comment]
Thanks for this submission.   Currently, there is already meteor/docs#8 regarding this so I will close this here – docs are kept in their own repository.
