### ISSUE TITLE
make the API Docs print-friendly

### ISSUE THREAD

**Issue by sorcamarian** [meteor/meteor#7566]
The API Docs are not print-friendly. 

The sidebar isn't designed for such use cases. 
![image](https://cloud.githubusercontent.com/assets/12509753/17375237/c8e48690-59b8-11e6-9712-4d500ab0c3f4.png)

**Comment by abernix** [comment]
You already opened this issue and I closed it.  See my notes on #7565.

**Comment by sorcamarian** [comment]
That's about a page with all docs.
This one is about the current pages.

**Comment by sorcamarian** [comment]
Add at the end of: https://docs.meteor.com/style/style.css :
```
@media print {
  .sidebar,
  .nav { 
    display: none; 
  }
  .content {
    margin: 0;
  }
}
```

**Comment by abernix** [comment]
This is a great suggestion, but please open it in [the Meteor Docs repository](https://github.com/meteor/docs), or even better, in the repository for [the Meteor theme](https://github.com/meteor/hexo-theme-meteor) so it will fix both the Guide and the Docs!  A pull request there would be greatly appreciated and likely accepted.

**Comment by sorcamarian** [comment]
Done: https://github.com/meteor/hexo-theme-meteor/issues/24

But no answer, after 6 days.
