### ISSUE TITLE
[sockjs] Obtain REMOTE_USER from connection object

### ISSUE THREAD

**Issue by srbdev** [meteor/meteor#7570]
I am using Meteor 1.3.5.1 and have the following setup: Apache acts as a proxy and authenticates a user. Once the user is authenticated, the connection is forwarded to the Meteor app with the REMOTE_USER HTTP header. I have the following piece of code in my `server/main.js` file:

```javascript
Meteor.onConnection((connection) => {
  console.log(connection);
});
```

I see some information but I cannot see the REMOTE_USER value. I read in the documentation that the HTTP headers are whitelisted but it doesn't specify how one would go about editing the whitelist.

**Comment by mitar** [comment]
There is no way to edit the whitelist, see this pull request: https://github.com/sockjs/sockjs-node/pull/202

**Comment by srbdev** [comment]
@mitar Thank you for letting me know. Do you know of any workaround to expose the desired HTTP headers?

**Comment by mitar** [comment]
Yes, you make an Ajax request to the Meteor endpoint on the server and then expose this to the rest of the code. This is also safe and secure from the perspective of the cross-origin requests. [This packages does exactly this](https://github.com/sandstorm-io/meteor-accounts-sandstorm). It might be interesting to extract this logic into a 3rd party package which then you and others could just use.

**Comment by abernix** [comment]
If this ever surfaces in SockJS then Meteor can attempt to implement it.  Until then this is a SockJS issue.
