### ISSUE TITLE
Offer `Accounts.sendVerificationEmail`(client) api

### ISSUE THREAD

**Issue by zhaoyao91** [meteor/meteor#7582]
The use case is: new user is not verified thus not being allowed to login. although we send a verification email on signup, but he may not verify it this time and return to the app later, only to find that the email is already used without be verified, no way to verify it again.

yes we can implement this api by ourself, but I think it'd be better to be here to match other apis in the same abstract level, such as `Accounts.forgotPassword`(client), and I found to implement rate-limit for it is not so simple a work.

**Comment by abernix** [comment]
Thanks for submitting this feature request.  The guidelines for feature requests [can be found here](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests), but here are some key points to keep in mind!:

> You'll have the best chance of getting a change into core if you can build consensus in the community for it. Start by creating a well specified feature request as a Github issue.
>
> Help drive discussion and advocate for your feature on the Github ticket (and perhaps the forums). The higher the demand for the feature and the greater the clarity of it's specification will determine the likelihood of a core contributor prioritizing your feature by flagging it with the pull-requests-encouraged label.
>
> Finally, you can show your support for features you would like by commenting with a +1 or up-voting the issue.

The most needed features will of course receive the most attention from those in the community.  I'll label this as a feature request – +1s accepted!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Offer%20%60Accounts.sendVerificationEmail%60(client)%20api&body=Migrated%20from:%20meteor/meteor%237582) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
