### ISSUE TITLE
Support "Bash on Windows"

### ISSUE THREAD

**Issue by NitroBAY** [meteor/meteor#7583]
Hello, I updated W10 to anniversary edition and so I downloaded meteor 1.4.0.1 via linux command of your website (curl | sh), check that I've python, gcc as the C compiler (+ sudo apt upgrade/update) but either on old project or newly created projects with the brand new ubuntu shell I got with sudo meteor :
`Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.`
if I ommit sudo I have an 
`=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
Error: EACCES: permission denied, mkdir '/home/NitroBAY/.meteor/packages/npm-bcrypt/.0.8.7.1yuta2i++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-pwr33q'
    at Error (native)`

**Comment by abernix** [comment]
I don't believe this has been tested at all yet and I'm not even remotely surprised that it doesn't work out of the box.

I would recommend using the traditional Windows installer for now if you are eager to use Meteor on Windows.  But by all means, please do try to help figure out what's wrong and submit a proposal for making it work.  I'm sure many Windows users would appreciate it, but I don't know if this is going to get a lot of attention right away.

My first question would be if you can setup your own Mongo server on that machine and then get Meteor to use it by specifying the environment variable `MONGO_URL=mongodb://localhost:27017/meteor`.  It's possible that the Mongo binary Meteor has bundled just isn't compatible with Windows 10 and won't start.

But again, this is only speculation and there is probably a lot more that could be wrong / needs to be looked into.

**Comment by NitroBAY** [comment]
Okay, I'm glad that you're interested by this problem. But the problem is that some actually make linux on windows shell working with meteor : http://tomgrek.com/post/meteor-on-windows-bash/ (and he told about his article here https://forums.meteor.com/t/linuxs-meteor-install-now-works-natively-on-windows/21954) and @heberallred said he make it works on #5091

**Comment by NitroBAY** [comment]
Also I tried to change permissions of .meteor recursively both via linux and via windows explorer but that didn't change my problem, so as you said I could reinstalling windows installer (especially that I'm already late on a project) but that's really tough and sad

**Comment by NitroBAY** [comment]
Didn't succeed to install mongo. I'm under ubuntu 14.04, I followed that https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ and `sudo service mongod start` give me `mongod: unrecognized service`

**Comment by laosb** [comment]
@NitroBAY You can try to start your MongoDB instance on Windows using Win binaries, and then specify the MONGO_URL to the instance on Windows.

**Comment by NitroBAY** [comment]
Unfortunately I'll very probably not have time for programming next weeks so I cannot help :( I hope that it'll be fixed by then.

**Comment by dtruel** [comment]
perhaps try installing it to a different location.  I put my projects in a folder on the C drive which in WSL is /mnt/c/projects instead of the home directory

**Comment by NitroBAY** [comment]
Finally mongodb is working but I can't get working 1.4 + subsystem exactly like https://forums.meteor.com/t/1-4-app-successfully-building-in-windows-10-bash/27552

**Comment by NitroBAY** [comment]
Thanks to fourseven:scss 3.9.0 and meteor 1.4.0 all is working now.
By the way : YAY the compilation seems faster. That plus the 1.4.2 which should (finally) focus on compilation time, Meteor could be really usable on a daily basis :D :+1:

**Comment by NitroBAY** [comment]
I don't know why but the bug is back. Either I try to launch my project on my windows drive (/mnt/c) but Unexpected mongo exit code 100. Restarting. (even with sudo, even with admin right to the bash). Either I create a project into linux but then when I change something windows side on (AppData\Local\lxss) the changes ARE NOT DETECTED by linux. ALL was working great but since days the bug I described above is back AND I waste days into that without solving anything....

**Comment by musosoft** [comment]
I started to have the same issue recently. if I run `meteor` it throws error: Unexpected mongo exit code 14. Restarting. With sudo it has exit code 100

**Comment by NitroBAY** [comment]
If I put my project in home of windows bash changes aren't detected so I can't edit my code.
If I try to launch my project under /mnt/c (windows partition) Meteor will not run because linux can't rewrite what meteor Windows has written.
So the workaround could be to delete .meteor/local of a /mnt/c project and to run meteor on bash, but mongo isn't working nor shell etc. And I don't think I can update, so yeah we wait for a response of MDG because I'll not use linux on Windows if I can't use Meteor (obviously) but I wait for that moment since too long and that would really increase productivity so I hope 1.4.2 will take care of it as it's in the logic of performance optimization.

**Comment by NitroBAY** [comment]
Please if you can do test on W10.

**Comment by NitroBAY** [comment]
Please if you can do test on W10, we would be so glad to use linux on Windows !

**Comment by musosoft** [comment]
The older 1.3 meteor branch works under WSL, just downgrade until MDL will fix the new mongo version in 1.4 branch.

`meteor create PROJECT_NAME --release 1.3.5.1`

**Comment by NitroBAY** [comment]
I don't think any version of Meteor works at any time with WSL for me.

**Comment by NitroBAY** [comment]
As I think it's interesting enough, here's what @abernix said on another report about bash on windows 

> Thanks for filing an issue. There is no reason for this very basic, non-cross-device operation to fail.
> 
> The very likely reason that this is happening is that you are using "Bash on Windows" which is still incomplete and has an official warning that you should expect "some things to work and for many things to fail".
> 
> I attempted for several hours to get Meteor working with BashOnWindows over the weekend and ran into numerous problems with seemingly basic tasks. For example node-gyp install, a very basic command which simply downloads and extracts the node headers into a directory fails because of a bizarre data flow error.
> 
> I was able to work around many things by doing things that I shouldn't have to had done (copying files manually, etc.), but the bottom line is: Bash on Windows is not ready.
> 
> There are a lot of known problems, and several which were only fixed by switching to the "Insider" builds which are not automatically released. Many filesystem issues are fixed only in internal Microsoft builds.
> 
> You may have better luck if you run Bash as administrator but you shouldn't have to if everything is working properly. Unless you are able to reproduce this problem with bash on a stable version of actual Ubuntu, you'll probably need to open this issue with Microsoft. For what it's worth, they do seem really eager to get it all working and are closing issues on a regular basis.
> 
> I think the only reasonable option here is to wait until Microsoft stabilizes the release and I think #7583 is a sufficient issue to wait for that to happen.

**Comment by dtruel** [comment]
It may be that 1.4 requires inotify support, which will be added at some point to release builds of windows 10
https://blogs.msdn.microsoft.com/commandline/2016/10/07/wsl-adds-inotify-filesystem-change-notification-support/

**Comment by abernix** [comment]
Thanks for cross-posting that, @NitroBAY, I had meant to do that but forgot.

I hope I was clear: I do think this can all get worked out eventually and there might be some changes that Meteor needs to make in order to finally work, but as of right now I had to throw my hands up especially since I don't actively work on Windows and BashOnWindows isn't open-source so it could be further debugged by the community.

**Comment by mizzao** [comment]
@musosoft can you clarify what you mean by '1.3 works under WSL'?

For example, do you put your project under `/home` or `/mnt/c`? What do you edit the files with? This confounds me, because
- if you put the files in the WSL filesystem, apps running in Windows will not be able to edit the files directly (e.g. https://github.com/Microsoft/BashOnWindows/issues/402#issuecomment-220585695)
- on the other hand, if you put the files under `/mnt/c`, Meteor's file watcher will expect a Linux FS but since it will actually be Windows, and won't work properly.

Has anyone actually tried running meteor on WSL while editing the files from a normal Windows app? If so, what works?

**Comment by mizzao** [comment]
Just wanted to follow-up on my last comment. Under some basic testing, Meteor 1.3.5.1 seems to work fine with the project under `/mnt/c` being edited by Visual Studio Code, with `meteor` itself running under WSL bash. Basic file changes work on both client and server, and rebuild times aren't horrible.

Haven't tested 1.4.x yet, but would be interested in the build optimizations in 1.4.2 if those improve performance further. Will report back with any additional findings.

**Comment by NitroBAY** [comment]
Oh yeah so I wasn't crazy, Meteor used to work and to detect changes under /mnt/c.

**Comment by NitroBAY** [comment]
So ... as Windows added inotify support on Insiders builds Meteor on windows on bash is working now on Insiders build ?
Because next month the update "creators update" is going to be deployed. And if we could run Meteor from the bash then it would be pretty amazing.

**Comment by NitroBAY** [comment]
Still `Unexpected mongo exit code 14. Restarting.`.

**Comment by NitroBAY** [comment]
Well I still have mongo error (14/100) even after the creator update.

**Comment by lobosan** [comment]
Same here. Is there any way to fix it?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20%22Bash%20on%20Windows%22&body=Migrated%20from:%20meteor/meteor%237583) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mizzao** [comment]
Following up on my earlier post, Meteor 1.5 does *not* work using WSL for a project under `/mnt/c`. It shows the following error, possibly due to the inotify support above.

```
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Can't start Mongo server.                     
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
```

**Comment by mizzao** [comment]
I'd recommend everyone who is following this thread to post their latest experiences over at https://github.com/meteor/meteor-feature-requests/issues/154 to see if we can get Meteor working on WSL again.
