### ISSUE TITLE
Feature: Build bundle without tar.gz

### ISSUE THREAD

**Issue by lope** [meteor/meteor#7587]
It would be nice to have an option to build the bundle without tar.gz

Use cases:
1. Some people build on the server
2. I prefer to **build** into a ramdisk, then rsync it with my server.

The tar.gz is a waste time and resources in these cases. It should be possible to disable the .tar.gz step and just get the bundled files.

Suggested new option:
--notar

**Comment by laosb** [comment]
In fact you can use `--directory` to get a directory of all bundled files.

**Comment by abernix** [comment]
This was already explained the output of `meteor build --help`, however I submitted meteor/docs#74 to clarify the online docs.

**Comment by lope** [comment]
@laosb @abernix Thanks guys. I did not check meteor build --help. I didn't know that type of help was available thanks :) I did check the online docs. Awesome that you've updated it :)
