### ISSUE TITLE
Remove Templating Dependency from Google Package

### ISSUE THREAD

**Issue by DerekTBrown** [meteor/meteor#7589]
For people using React / Angular, it doesn't make sense to have to import clientside Blaze and JQuery in order to be able to use Google Accounts.  Which currently is required because of the following dependency chain:

accounts-google -> google -> templating -> blaze (client)

It currently seems like the only reason this is required is in order to launch a dialog if the Google Client OAuth Key has not been properly configured:

https://github.com/meteor/meteor/blob/devel/packages/google/google_configure.js

This can easily be done using either server-side Blaze, or even by just removing this functionality entirely and instead redirecting to a static html page in the documentation.

**Comment by mitar** [comment]
Or this could be a lazy import.

**Comment by DerekTBrown** [comment]
@mitar yeah, weak dependency

**Comment by abernix** [comment]
I think this is (essentially) the same issue as #6844 (where you've had some conversation before) and the newer #7715 (which has had a lot more conversation about the issue).  Let's keep the conversation in those places for now as they've had more activity and, if necessary, branch off from the solution to that ticket.
