### ISSUE TITLE
CoffeeScript documentation is outdated

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7592]
In the documentation, it is written:

> Note that ES2015 code in backticks, for example an import statement in backticks, do not work; your .coffee files will be transpiled into JavaScript, but not then handed off to the ecmascript package for further transpiling. Any JavaScript you type in backticks will be passed through unmodified all the way to the browser or Node.js runtime.

To my understanding, this is not true anymore. Probably this should be updated with an example how to use it with backticks.

**Comment by tmeasday** [comment]
We should probably move this here: https://github.com/meteor/docs/issues. But I'm wondering where you see that?

**Comment by mitar** [comment]
Oh, that was fixed 11 days ago: https://github.com/meteor/docs/commit/b4212bc87052b56e6fffbfe4f54d3c3a93f1e735
