### ISSUE TITLE
Prevent Meteor searching the whole package directory

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7598]
I have some packages which contain git submodules with many many files. New Meteor versions search the whole package directory for files, even if I do not use `modules` or any imports/exports. This effectively makes it not possible to work with those packages. For example, I cannot publish it. (I do a workaround by manually removing all files I do not care anyway for publishing, and then restoring them back.)

Example: https://github.com/peerlibrary/meteor-util

**Comment by theosp** [comment]
Related to #7842 , the issue is wider than meteor searching the entire packages directories.
Many packages broke in v1.3.5.1 as a result of a change made then.

**Comment by shaiamir** [comment]
I have the same problem when trying to move to Meteor 1.4 from 1.2.1.
Prefer to have the old behavior back or allow more control over what files are scanned.

**Comment by mitar** [comment]
See [my proposal here](https://github.com/meteor/meteor/issues/6132#issuecomment-261378905).

**Comment by shaiamir** [comment]
Your proposal sounds great.
Any idea when / if it will be implemented?

**Comment by mitar** [comment]
I do not think MDG likes it. I do not know why though. Because it would be backwards compatible and it would provide more control (and speed) to those who need it.

**Comment by theosp** [comment]
Commented there as well: https://github.com/meteor/meteor/issues/6132#issuecomment-261722247

**Comment by mitar** [comment]
So #7867 has been closed because one can already lazily import files from other packages by doing:

```
import ... from "meteor/some:package/implicit.js"
```

And to support this, Meteor currently scans the whole `some:package`. This issue is then that I think it would be great if one could configure it with an explicit list of files. So in some way, the old Meteor behavior. Where you listed explicitly which files to add to the package, and now which files to add for others to be able to import.

From my [proposal here](https://github.com/meteor/meteor/issues/6132#issuecomment-261378905):

I would prefer that a package could say that no files should be automatically compiled, and then do `api.addFiles([...], {lazy: true})` and those files would then be available for lazy importing elsewhere. To me this is a clean design: only allowed files can be imported outside, it makes a clean API, and it has much better performance.

I agree that current thing is probably a good default, but maybe something like that if `api.addFiles([...], {lazy: true})` is called (even with empty `[]`), then automatic compilation is disabled and only explicitly added lazy files are available, or none.

So this is really for power users who want to create a clean local packages structure and precisely control what is compiled and what is not, what is added to targets and what is not (#7573).

**Comment by theosp** [comment]
@mitar I think that a more explicit api that turns the full package scan off is better than implicit approach like the one you propose above.

```
api.strictFilesListing() # or any other wording that convey better the behavior
```

Since that might be very confusing for developers that aren't aware of the radical effect of {lazy: true} on their package load.

I think that an approach like the one you are proposing is great and will allow to fix the backward compatibility issues for packages that were written before v1.3.5.1 by simply updating the package.js file of the packages that relied on the previous behavior.

Hope to see something like this coming in future versions!

-Daniel

**Comment by mitar** [comment]
I agree.

Also, maybe we could just repurpose `isImport` flag, instead of having new `lazy` flag?

**Comment by mitar** [comment]
I cannot run tests anymore with newer Meteor for this package because it dies scanning the whole git submodule: https://github.com/peerlibrary/meteor-server-autorun

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Prevent%20Meteor%20searching%20the%20whole%20package%20directory&body=Migrated%20from:%20meteor/meteor%237598) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
