### ISSUE TITLE
Can't publish on build servers

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7599]
I'm trying to build a package on the build servers.
However, it always tries to download `meteor-tool@1.3.4_4`.

On the mac servers the connection gets closed during the download:
```
build:~ meteor$ meteor publish-for-arch fourseven:scss@3.8.1
   Downloading meteor-tool@1.3.4_4...        [===========               ] 43% 39.4s                                                                Connection to 199.19.86.153 closed by remote host.
```

On both linux build servers after the download has completed (but the spinner is running), I get:
```
Broadcast message from root@ip-172-31-28-30
        (unknown) at 10:30 ...

The system is going down for power off NOW!
Connection to 54.164.113.44 closed by remote host.
```

On windows it seems to take ages and then the connection is also closed.

I've tried 3 times on each architecture by now...

**Comment by cdcv** [comment]
+1

**Comment by YannDanthu** [comment]
+1

**Comment by benjamn** [comment]
For what it's worth, you can pass a `--minutes n` flag to `meteor admin get-machine` to reserve the machine for longer.

**Comment by sebakerckhof** [comment]
Problem is that 15 minutes is the maximum, but it's not enough...

**Comment by sebakerckhof** [comment]
Btw, I think it would be a good idea if the meteor package constraint solver only takes packages into account which have a binary build (if necessary) available for the chosen architecture.

**Comment by benjamn** [comment]
Coincidentally (or not?) I've been working on a PR to make `meteor publish-for-arch` unnecessary after Meteor 1.4.1, and I would love to hear any feedback you have: https://github.com/meteor/meteor/pull/7608

**Comment by sebakerckhof** [comment]
Okay, I've been able to publish on mac and windows with the --minutes option set to 15.
On linux I think it installs the correct meteor-tool successfully, but then reboots because of this install. The next time I reconnect, I get a new machine assigned. At least that's what I think since the IP address of the machine has changed. Could it be there are just a large amount of linux build servers compared to mac/windows servers and I need to be lucky to catch one where the installation has already happened?

**Comment by benjamn** [comment]
Just bumped the max reservation time from 15 minutes to 45 minutes. It's not the ideal solution, but I hope it helps!

**Comment by fourseven** [comment]
I've just tried running the same publish as @sebakerckhof - the mac machines still timeout after ~15 minutes and the linux boxes are now spinning on:

```
meteor@ip-172-31-35-120:~$  meteor publish-for-arch fourseven:scss@3.8.1
   Downloading meteor-tool@1.3.4_4...        |
```

For over 20 minutes (I'm not sure it's doing anything at this point, the download progress bar completed and disappeared).

**Comment by sebakerckhof** [comment]
Yeah, I also tried with 45 minutes. Thing seems stuck on:
`Downloading meteor-tool@1.3.4_4...        |` and then the machine shuts down. Not just a disconnect, it tells me:
`Connection to 54.164.113.44 closed by remote host.`

It's even less of a perfect solution, but if someone could install meteor-tool@1.3.4_4, so it doesn't need to do that, then at least I can help these people: https://github.com/fourseven/meteor-scss/issues/201

And the following release probably won't need publish-for-arch anyway...

**Comment by awatson1978** [comment]
+1  

Did `METEOR@1.4.1` get pushed to the build servers?  Crossing my fingers that this might work now...

**Comment by mitar** [comment]
Meteor 1.4.1 does not help. See: https://github.com/meteor/meteor/issues/7675

@sebakerckhof, @fourseven: At least for Linux it is relatively easy to create your own local VirtualBox Linux machine and publish from there for that arch. You do not really need build machines for that. I can try publishing it if you give me permissions.

**Comment by mitar** [comment]
For downloading issues, I think it is also a problem of new CDN. It is really slow. :-(

**Comment by abernix** [comment]
I was just able to successfully publish two binary packages from all the different `arch`s using `--release 1.3.4.4` which would indicate to me that the `Downloading` process in Meteor 1.4.1.1 (which is on all the build servers) is at least helping to some degree with this problem (and the messages are at least a lot more clear and make debugging a lot easier).

Going to close for now but if anyone above is still experiencing this issue on the build servers, let's reopen this and I'd be happy to help.
