### ISSUE TITLE
Comment support in 'meteor/cordova-plugins'

### ISSUE THREAD

**Issue by zhtuguowei** [meteor/meteor#7604]
When i add a commont in cordova-plugins file, an error occured.

This is the cordova-plugins file:

```
#hello
cordova-plugin-badge@0.7.2
cordova-plugin-camera@2.2.0
```

This is the console output:

```
=> Errors prevented startup:                  
   While reading project metadata:
   /Users/guowei/Code/js/app/.meteor/cordova-plugins: Cordova plugin must specify version: #hello
=> Your application has errors. Waiting for file change.
```

**Comment by laosb** [comment]
Is it a must to have comments in it?

**Comment by laosb** [comment]
To achieve comments in `cordova-plugins`, simply use [the code stripping comments in `packages`](https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/tools/project-context.js#L856) when [parsing `cordova-plugins`](https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/tools/project-context.js#L1227).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Comment%20support%20in%20'meteor%2Fcordova-plugins'&body=Migrated%20from:%20meteor/meteor%237604) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
