### ISSUE TITLE
Surprising path error when using an npm module with long relative path

### ISSUE THREAD

**Issue by Kurounin** [meteor/meteor#7605]
**Meteor version:** 1.4.0.1
**OS:** Windows 10 64bit
**Bug repository & steps to reproduce:** https://github.com/Kurounin/meteor-absolute-path-bug
**Description of bug:** If you use an npm module in the project with a long relative path (e.g.: _../../../build/Release/kerberos_) and you place the project in the drive root, when building the project meteor will join the current absolute file path and the required relative path and the resulting path will be _/build/Release/kerberos_ which will cause it to crash with a fatal error.

**Comment by abernix** [comment]
I was able to successfully reproduce this problem on Windows 10 64-bit with Meteor 1.4.0.1 and 1.4.1.3, but after upgrading to Meteor 1.4.2 this problem went away – without the pull-request.

A lot has changed in 1.4.2 with the isobuilder so I would attribute the change to that.  If you find that this is not fixed for you when you update to 1.4.2, please ping me and we can reopen, but I'm fairly confident that this is resolved. :smile:
