### ISSUE TITLE
Meteor 1.3.3 DDP Batching bug with Fast-Render

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#7618]
A lot of people have reported that Fast-Render stopped working properly after the 1.3.3 update (I assume due to the new DDP batching features):

https://github.com/kadirahq/fast-render/issues/176

What this means in practice is that `Meteor.user()` first shows up at `undefined` when you log it out, even though fast-render is supposed to send its data along with the initial payload:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2y2d23413B3S1c2J170L/Screen%20Shot%202016-08-10%20at%201.12.57%20PM.png?v=26af7af9](https://d3vv6lp55qjaqc.cloudfront.net/items/2y2d23413B3S1c2J170L/Screen%20Shot%202016-08-10%20at%201.12.57%20PM.png?v=26af7af9)

Here's a reproduction with the React To-Dos app:

https://github.com/SachaG/simple-react-todos-bug

You can see the files I changed here:

https://github.com/SachaG/simple-react-todos-bug/commit/eb4d921571f04d738c10a01b9238c562e4c26c7a

(just ignore `mup.js`).

**Comment by tmeasday** [comment]
Definitely a bug w/ fast-render: https://github.com/kadirahq/fast-render/issues/176#issuecomment-238773813
