### ISSUE TITLE
Support one-time login

### ISSUE THREAD

**Issue by zhaoyao91** [meteor/meteor#7625]
With `accounts-*` packages, the login will be maintained for default 90 days. the token will be cached to localstorage and the next time user open the browser, it will login automatically again.

But for some app, this is not right and secure. For example, for an admin app, user need to perform a one-time login, and keep the token in memory to make it safe for it will be removed on closing of browser.

**Comment by zhaoyao91** [comment]
[@reoh's solution](https://forums.meteor.com/t/how-to-implement-one-time-login/27834/3) workaround this problem. It really should be made a config options of `Accounts`.

**Comment by laosb** [comment]
Should it be global for all accounts, or users can choose to do so? I mean you don't really want to type your user and pw everytime on a trusted machine.

**Comment by laosb** [comment]
Maybe a config option of Accounts like:

```
Accounts.config({ noKeepLoggedIn: true });
```

So globally one-time login. When this was `false` (default), we can still pass it to login functions as a option, meaning one-time login for this session:

```
Meteor.loginWithPassword({ /* Login data */, noKeepLoggedIn: true });
```

Just my thoughts :thought_balloon:

**Comment by laosb** [comment]
Maybe a config option of Accounts like:

```
Accounts.config({ noKeepLoggedIn: true });
```

So globally one-time login. When this was `false` (default), we can still pass it to login functions as a option, meaning one-time login for this session:

```
Meteor.loginWithPassword({ /* Login data */, noKeepLoggedIn: true });
```

Just my thoughts :thought_balloon:

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20one-time%20login&body=Migrated%20from:%20meteor/meteor%237625) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
