### ISSUE TITLE
Meteor should check if is running as root and prevent it on Unix

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7631]
Meteor should have a similar check node.js has and prevent running as root on Unix. That if you do `sudo meteor` it says that it will not run and you have to do `sudo meteor --ireallyknowwhatiamdoing` (see what is the flag node.js use) to allow it. Because I think this is so common issue and there is so little reasons why to run meteor with sudo that it would be very useful.

[From discussion here](https://github.com/meteor/meteor/issues/7469#issuecomment-239073439).

**Comment by mitar** [comment]
We should maybe also document a fix if you do run with `sudo`, that you should chown your `.meteor` directory back to yourself: `chown -Rh <username> ~/.meteor`

**Comment by mhidou** [comment]
Should we check only on `meteor run` or in all commands?

**Comment by abernix** [comment]
I don't see a reason not to do it on all commands.  It seems that the only time root would _actually_ be necessary would be if you were using the `meteor` development tool and wanted to bind to a port <= 1024.  In the case that you needed to do that (still arguably necessary in a world of containers and port forwarding), you could pass the flag to allow it.

But, speaking of flag, I can't seem to find a reference to what that `--ireallyknowwhatiamdoing` Node flag is you're referring to, @mitar. 🔎🔍

**Comment by mitar** [comment]
In npm it is called [unsafe-perm](https://docs.npmjs.com/misc/config#unsafe-perm). So I would do `meteor --unsafe-perm run` to be similar.

I run inside Docker building bundles and on Travis CI test-packages as root. :-) So this might be backwards incompatible change if we do it for all commands, but I would still do it. But we probably have to do it for all, because almost all commands could access packaging information and potentially change permissions of files, no?

Alternatively, we could be just output a warning if you run as root and without this flag.

**Comment by abernix** [comment]
Ah, yes.  I just had to use that on the `abernix:meteord` `mup` image recently.  I'm glad I've forgotten already. :wink:

But yea, this would be a breaking change if it was anything more than a warning.  I think it's pretty important to prevent this sort of behavior though.  I'm kinda in favor.

**Comment by mitar** [comment]
In favor of preventing or of warning?

**Comment by abernix** [comment]
In favor of preventing entirely unless the flag is passed.

**Comment by mitar** [comment]
I agree.

**Comment by mitar** [comment]
This has been resolved.

**Comment by mitar** [comment]
This has been resolved.
