### ISSUE TITLE
Circular cross-package imports

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7635]
Since Meteor 1.3, we can use ES6 import syntax. One of the benefits is this allow circular dependencies.
Since we agree this can be useful, I think we can also agree it would make sense to have circular cross-package imports.
However, if 2 packages use each other Meteor will throw an error like:
`error: circular dependency between packages bar and foo`.

But Meteor also provides the `{unordered:true}` option, like: `api.use([...], {unordered:true})`. Now it won't complain anymore about circular dependencies. However, whether it works now depends on how meteor will order the packages (alphabetically?). 
Take this example repo: https://github.com/sebakerckhof/circulartest
This will throw an error like:
`Error: Can't find npm module 'meteor/foo/sayHello'. Did you forget to call 'Npm.depends' in package.js ...`

If you look at the `otherwayaround` branch, which just swaps the packages `foo` and `bar`, all of the sudden everything works.

I get that having circular package dependencies would mean that the lazily loaded files and the code in the main modules of those packages should be able to run in any order. But for imports I think there are scenarios where it makes sense if you could have them circular, cross-package.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Circular%20cross-package%20imports&body=Migrated%20from:%20meteor/meteor%237635) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
