### ISSUE TITLE
improve initial page loading speed

### ISSUE THREAD

**Issue by bmcmahen** [meteor/meteor#764]
I'm working on some basic cms systems for a number of clients that allow them to enter an 'admin' section, and alter display information including site name, links, etc., which is then stored in the database. The problem with this right now, is that I need to wait until the subscription has finished loading before I can draw the user configured appearance options. Basically, you (1) load the site, which (2) fetches the subscription, which (3) allows me to update the site with the user configured data. This is pretty slow, and necessitates a loading indicator for key site components, including text (which should be the first to load...)

It might be nice if, at least on initial page loads, the html was rendered server-side and then supplied to the client.

**Comment by dandv** [comment]
Now that GitHub is used to track feature requests, could we re-open this?

**Comment by glasser** [comment]
Our current policy is that very large feature requests that are whole projects that we haven't started yet and are already in the Future column of  https://roadmap.meteor.com/ get tracked on the roadmap rather than GitHub.   This is https://trello.com/c/69Jndpqf/47-page-load-time-optimization
