### ISSUE TITLE
Meteor opening node window with prompt in windows7 after update to 1.4.0-1

### ISSUE THREAD

**Issue by Rahman-S-M** [meteor/meteor#7642]
Meteor working fine before and after its update to 1.4.0-1, meteor command is opening node window with prompt but not starting meteor. Any known issues?

**Comment by Rahman-S-M** [comment]
I could able to create a new project but old projects are not working. 'meteor' or 'meteor update' opening a new command window of node . How to fix this issue?

**Comment by laosb** [comment]
Could you provide a *full reproduction* as was explained in Contributing.md? It's hard for us to reproduce your issue without a reproduction.

* For your reference:*

> A Meteor app has many moving parts, and it's often difficult to
> reproduce a bug based on just a few lines of code.  So your report
> should include a reproduction recipe.  By making it as easy as possible
> for others to reproduce your bug, you make it easier for your bug to be
> fixed. **It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.**
> 
> **A single code snippet is _not_ a reproduction recipe and neither is an entire application.**
> 
> A reproduction recipe works like this:
> 
>  * Create a new Meteor app that displays the bug with as little code as
>    possible. Try to delete any code that is unrelated to the precise bug
>    you're reporting, including extraneous Atmosphere packages.  Ideally, try to use
>    as few source files as possible so that it's easy to see the whole reproduction
>    on one screen, rather than making a large number of small files, even if that's
>    not how you'd choose to structure an app.
> 
>  * Create a new GitHub repository with a name like
>    `meteor-reactivity-bug` (or if you're adding a new reproduction
>    recipe to an existing issue, `meteor-issue-321`) and push your code
>    to it. (Make sure to include the `.meteor/packages` and `.meteor/release` files!)
> 
>  * Reproduce the bug from scratch, starting with a `git clone`
>    command. Copy and paste the entire command-line input and output,
>    starting with the `git clone` command, into the issue description of
>    a new GitHub issue. Also describe any web browser interaction you
>    need to do.
> 
>  * If you reproduced the issue using a checkout of Meteor instead of using
>    a released version that was pinned with a `.meteor/release` file,
>    specify what commit in the Meteor repository was checked out.
> 
>  * Mention what operating system you're using and what browser (if any).
>

**Comment by Rahman-S-M** [comment]
OS : Windows 7
Meteor updated to : 1.4.0-1

on starting 'meteor' , it is opening another node window with prompt. 
nothing working with meteor ie., meteor --help or meteor --port ...
all are opening a new window with node prompt

**Comment by laosb** [comment]
Anyone using Windows 7 can reproduce?

**Comment by abernix** [comment]
Unfortunately, I am not able to reproduce this on Windows 7 at all.  Which Command Prompt are you using with Windows?  Regular Command Prompt (i.e. `cmd`), PowerShell, etc.?

What is the value of your `PATH` environment variable?  You can find this by typing `SET PATH` in a `cmd` window (not PowerShell).

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  :)
