### ISSUE TITLE
this.userId is undefined with ES6 arrow function in Meteor.publish

### ISSUE THREAD

**Issue by CODEheures** [meteor/meteor#7644]
The "this.userId" seem to be undefined in Meteor.publish when I use ES6 arrow function.
![meteor](https://cloud.githubusercontent.com/assets/12785273/17650435/219deea0-624e-11e6-8899-6411826b4698.jpg)

**Comment by DavidReinberger** [comment]
ES6 fat arrow functions are inheriting the parent scope, that's why. Use an anon or named function in publications.

**Comment by laosb** [comment]
This is intended just like what @DavidReinberger said. Closing.
