### ISSUE TITLE
Getting stuck on Processing files with ecmascript (for...

### ISSUE THREAD

**Issue by polkhovsky** [meteor/meteor#7648]
Trying to run Meteor project, the process gets stuck forever on `Processing files with ecmascript (for...` step forever. Ctrl+C doesn't kill it. The only way to kill the process is with the `kill ` command. Latest Meteor 1.4.0.1 running on Mac. Attached are screenshots of the process profile on my Mac. Hope it helps.

![screen shot 2016-08-14 at 8 47 19 pm](https://cloud.githubusercontent.com/assets/4451400/17653255/62861f02-6260-11e6-9a2b-cd8119476836.png)
![screen shot 2016-08-14 at 8 47 27 pm](https://cloud.githubusercontent.com/assets/4451400/17653254/6281ccc2-6260-11e6-84d1-efd241e98641.png)

**Comment by laosb** [comment]
Could you provide a *full reproduction* as was explained in Contributing.md? It's hard for us to reproduce your issue without a reproduction.

* For your reference:*

> A Meteor app has many moving parts, and it's often difficult to
> reproduce a bug based on just a few lines of code.  So your report
> should include a reproduction recipe.  By making it as easy as possible
> for others to reproduce your bug, you make it easier for your bug to be
> fixed. **It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.**
> 
> **A single code snippet is _not_ a reproduction recipe and neither is an entire application.**
> 
> A reproduction recipe works like this:
> 
>  * Create a new Meteor app that displays the bug with as little code as
>    possible. Try to delete any code that is unrelated to the precise bug
>    you're reporting, including extraneous Atmosphere packages.  Ideally, try to use
>    as few source files as possible so that it's easy to see the whole reproduction
>    on one screen, rather than making a large number of small files, even if that's
>    not how you'd choose to structure an app.
> 
>  * Create a new GitHub repository with a name like
>    `meteor-reactivity-bug` (or if you're adding a new reproduction
>    recipe to an existing issue, `meteor-issue-321`) and push your code
>    to it. (Make sure to include the `.meteor/packages` and `.meteor/release` files!)
> 
>  * Reproduce the bug from scratch, starting with a `git clone`
>    command. Copy and paste the entire command-line input and output,
>    starting with the `git clone` command, into the issue description of
>    a new GitHub issue. Also describe any web browser interaction you
>    need to do.
> 
>  * If you reproduced the issue using a checkout of Meteor instead of using
>    a released version that was pinned with a `.meteor/release` file,
>    specify what commit in the Meteor repository was checked out.
> 
>  * Mention what operating system you're using and what browser (if any).
>

**Comment by polkhovsky** [comment]
All my fault. I saved a .js file in my client/js/lib folder, and then I accidentally saved my  meteor application's home page in the same folder! Guess I was too tired. Found the folder and then saw the html and a subfolder with meteor-generated scripts by process of elimination. Removed them and everything clicked. Sorry to bother.
