### ISSUE TITLE
More control on modules package to not wrap few npm package on request

### ISSUE THREAD

**Issue by veeramarni** [meteor/meteor#7651]
I'm using latest Meteor (1.14.0.1) and i have been facing react duplication when using webpack:webpack pacakge. Basically, meteor bundle include react package and as well the webpack budles the react package. 

I would like to use react package that will bundled through webpack only, is there a way to prevent react getting bundle. If any package has reference to react, module.js has that package otherwise it wouldn't. But if we have an option to ignore a package for example here react package that would solve lot of these duplication issue. 

I have created repo [here](https://github.com/veeramarni/kickstart-meteor-react-router) to replicate the issue.

**Comment by abernix** [comment]
Your bug report/feature request is really more of a question.  Additionally, your question involves using webpack (another project) and your repo doesn't clearly present an issue without digging into it extensively and trying to figure out what it is you're referring to.

You should consider posting your question to the Meteor forums and not here in Issues.  Closing.
