### ISSUE TITLE
Attempt to reconnect to mongo if initial connection fails.

### ISSUE THREAD

**Issue by rws-github** [meteor/meteor#7655]
If I `export MONGO_URL=mongo://localhost/database` and start meteor, it fails to connect to the database, never retries and exits.

```
MongoError: failed to connect to server [xxx:xxx] on first connect
    at Object.Future.wait (xxx/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
```

Using Mongo 1.4

**Comment by tmeasday** [comment]
Why do you think the initial connection fails? Do you know why in your case? This doesn't seem like something you should have to do.

If we think this feature is a good idea, we should probably backoff, and throw an exception after a certain number of retries. I know from experience that seeing errors when the `MONGO_URL` is mis-configured is super useful, I wouldn't want to lose that.

**Comment by rws-github** [comment]
I'm not exactly sure why it initially fails and it only happens some of the time. I would like to implement fixed retries and an interval so that it can work as it did originally by default but in my case I can control the behavior (and the existing tests will pass). Would these be settings set in the settings.json file?

**Comment by wojtkowiak** [comment]
I would be also interested in this feature. In my case, when I am starting docker containers I sometimes have an issue where the db is not yet ready and meteor fails to start. Of course for now I am just delaying things to fix it (there are also some docker specific workarounds to wait for some resources to be available in a bash script) but I would rather expect meteor to at least retry a few times.

**Comment by tmeasday** [comment]
Honestly, I think if the infrastructure is unreliable, there's no big problem in just restarting the Meteor process. `forever` exists, and does the job, so why not just use it?

**Comment by ramezrafla** [comment]
No updates on this thread? Frankly, I agree with @tmeasday, we shouldn't expect Meteor to support all possible retries for all APIs. If something is not there, something else is wrong.
