### ISSUE TITLE
Meteor could consider add "onStart" callback in Meteor.subscribe 

### ISSUE THREAD

**Issue by reason211** [meteor/meteor#7658]
I have the code:
```
this.autorun(()=>{
                let _filter = this.filter.get(); 
		loading.set(true);

		this.subscribe('user.list', _filter , limit, {
			onReady(){
				loading.set(false);
			}
		});
})
```
But
> Meteor is smart enough to skip a wasteful unsubscribe/resubscribe

So it cannot work as expected when param is not change. 
This means maybe need double compare param ( manual compare param and meteor Internal inspection )

Hope Meteor can consider add "onStart" callback in Meteor.subscribe , just like this:

```


		this.subscribe('user.list', filter , limit, {
                        onStart(){
 		                loading.set(true);
                        },
			onReady(){
				loading.set(false);
			}
		});
```

**Comment by mitar** [comment]
On my server-side implementation of [Tracker](https://github.com/peerlibrary/meteor-server-autorun) I have [beforeRun and afterRun](https://github.com/peerlibrary/meteor-server-autorun/issues/11) callbacks which help a lot with exactly such situations. We might want to introduce them to client-side Tracker as well.

**Comment by mitar** [comment]
(But I must say that I do not understand what exactly you are asking in your issue above.)

**Comment by laosb** [comment]
I don't understand, too. When I did a search in MeteorChina QQ Group, I found a similar request. If it's you @reason211, would you like explain this to me in Chinese in that group (or private messages)? I'll post it in English there.

**Comment by abernix** [comment]
Any updates on this @reason211 (or @laosb?)?

**Comment by laosb** [comment]
Ah, @reason211 did talked with me a month ago and he hadn't realize that it can be done using `subscriptionsReady`. I think we can close this.
