### ISSUE TITLE
meteor 1.4 start error

### ISSUE THREAD

**Issue by YY030913** [meteor/meteor#7660]
meteor 1.4.0-1
window 2000 server

=> Started MongoDB.
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.
windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:873:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at C:\tools\cli\dev-bundle-bin-helpers.js:72:42
    at addWindowsVariables (C:\tools\cli\dev-bundle-bin-helpers.js:67:10)
    at C:\tools\cli\dev-bundle-bin-helpers.js:35:14
    at C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1
\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:3
2:39

**Comment by benjamn** [comment]
What does `meteor node -p process.env.PYTHON` print?

**Comment by laosb** [comment]
>window 2000 server

I don't think Meteor will run on such old Windows version?

**Comment by YY030913** [comment]
@benjamn  when i put "meteor node -p process.env.PYTHON", i got the same error above

**Comment by YY030913** [comment]
@laosb when i use meteor .1.3.2 on this server it is ok, but my code has update to 1.4 need the new version support, so i don't think meteor is not support on 2000server

**Comment by YY030913** [comment]
@benjamn [](url)

**Comment by YY030913** [comment]
i am mistake close the problem ,but i stil not slove it

**Comment by YY030913** [comment]
i reinstall the meteor and follow #7469 ,now it's ok
