### ISSUE TITLE
MongoDB exited because its port was closed, or was already taken by a previous instance of MongoDB

### ISSUE THREAD

**Issue by twins16** [meteor/meteor#7663]
MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB
 i see this port is taken by metasploit in port 3001 
![screenshot from 2016-08-17 23 31 52](https://cloud.githubusercontent.com/assets/17352572/17755616/cd877e58-64d2-11e6-888c-fced1f54ee35.png)

and i see this euror 
![screenshot from 2016-08-17 23 32 18](https://cloud.githubusercontent.com/assets/17352572/17755626/db0931e8-64d2-11e6-8c9e-a335f9567cb8.png)

**Comment by twins16** [comment]
Sloved meteor -p 3006
![screenshot from 2016-08-18 00 01 30](https://cloud.githubusercontent.com/assets/17352572/17756300/ed55545e-64d6-11e6-8848-714534d7f000.png)

**Comment by laosb** [comment]
Please don't use root to run Meteor! That might be related your root usage.

**Comment by abernix** [comment]
In addition to what @laosb said, yes, MetaSploit uses port 3001.  Meteor uses its `--port` (default: 3000) and `port+1) – so by default, 3000 and 3001.  You'll have to us a different port, as you have done. :smile:

Closing as the error message actually stated the problem.
