### ISSUE TITLE
[1.4] Rebuilds times are too long

### ISSUE THREAD

**Issue by nicolaslopezj** [meteor/meteor#7665]
In these times where things like hot code push makes apps reload instantaneously, Meteor apps are reloaded in 15-40 seconds (or more in some cases) each time we hit the save button.

We are seeing in the roadmap things like node 4 and apollo, and that's great but we **need** faster rebuild times!

This should be a **critical issue**, meaning that everything else drops until this is resolved.

**Comment by trinicoder** [comment]
not to mention the annoying "Downloading tooling 1.3.1...."

**Comment by queso** [comment]
Honestly, I feel like this should be a community effort. @benjamn do you guys have any scripts or tools made for tracking overall build times on saving/reloading?

**Comment by nicolaslopezj** [comment]
I have and idea for a fast partial fix that could come with 1.4.1:

Expose a option to not watch for changes on files on server or client. With the new file structure, where all files are in a common folder every time I change a client file all the server restarts taking more than 40 seconds. 

With this option, we could prevents rebuilds when changing files in the ui folder for the server and the api folder for client.

And since most of the files changes are for the client (in my case), most rebuild times will be improved in 30 seconds or more.

**Comment by benjamn** [comment]
Meteor 1.4.2 will focus on rebuild performance.

There are multiple issues addressing more specific parts of this problem already (e.g. https://github.com/meteor/meteor/issues/7493). We don't need another one. We do, however, need community members who are willing to help diagnose and fix the problem.

[Here](https://github.com/meteor/meteor/blob/devel/tools/PERFORMANCE.md)'s a document all about Meteor performance to get you started.
