### ISSUE TITLE
Constrain core packages to be "underpinned" by the release

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7671]
A follow up to https://github.com/meteor/meteor/issues/7495 and https://github.com/meteor/meteor/pull/7653

Post 1.4, there is no effective way to update to anything but the latest release of Meteor, if by updating to a release we mean "ensuring you have at a minimum the versions specified in the release"[1]

For example, supposing that the latest release was 1.5, and you ran `meteor update --release 1.4.1` in a 1.4 app, the following would happen:
1. Your tool version would update to the 1.4.1 tool
2. Your `.meteor/packages` would be updated to "underpin"[2] all your **direct** dependencies to the versions specified in 1.4.1.
3. The constraint solver would run, choosing a new set of packages to respect 2.

However, as the constraint solver is conservative with indirect dependencies, chances are all your core indirect dependencies would remain at the 1.4 versions.

You could run `meteor update --all-packages`, however this would try and get the latest versions of all packages, which would (bar the tool) put you on 1.5.

There is no real way you could actually get those indirect dependencies up to the 1.4.1 versions[3]

---

This issue is a proposal that we re-introduce the `_addReleaseConstraints` code to `ProjectContext`, loosening [this line](https://github.com/meteor/meteor/blob/release/METEOR%401.3/tools/project-context.js#L662) to remove the `=` (i.e. "underpinning" rather than "pinning"). Potentially we could only do this during updates.

Note that this would also resolve https://github.com/meteor/meteor/issues/7495 (I think we are OK with https://github.com/meteor/meteor/pull/7653 as a solution to that though).

We discussed doing this originally in the release unpinning work, but decided not too because it wasn't something that made sense for npm. I'm not sure that reasoning is still as relevant.

[1] Maybe that's not what we mean by "updating to a release"?
[2] i.e. set minimum versions
[3] Bar _maybe_ futzing with your `.meteor/versions`, although that might not work.

**Comment by tmeasday** [comment]
@zol, @benjamn thoughts on this? I'm not sure it matters that much, but this could bit us later, especially if we ever want to release on an older track.

**Comment by laosb** [comment]
Not very sure with the constraint resolver, but why not specify all updated core package versions in a release, and set minium version for all those packages when update, no matter direct/indirect?

**Comment by tmeasday** [comment]
A secondary problem: right now if you `meteor create --release X.Y.Z` you get the latest compatible versions of all packages (or maybe just root packages?). This is surprising (maybe not, I guess it's due to step 7 in https://github.com/meteor/meteor/issues/7495#issuecomment-238792229).

If we are concerned about this we may want to reconsider the logic of step 7

**Comment by hwillson** [comment]
Great news - this has been addressed in Meteor 1.4.3; see:

- https://github.com/meteor/meteor/pull/8123/commits/868a52829fd26433baf3bde72edbd944cf02e61b
- https://github.com/meteor/meteor/pull/8123/commits/ff4b00c774ef4cbef9ddefea514b426d6694cf90

Re-capping from the [1.4.3 release notes](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13):

> Versions of Meteor core packages are once again constrained by the current Meteor release.

> Before Meteor 1.4, the current release dictated the exact version of every installed core package, which meant newer core packages could not be installed without publishing a new Meteor release. In order to support incremental development of core packages, Meteor 1.4 removed all release-based constraints on core package versions (#7084). Now, in Meteor 1.4.3, core package versions must remain patch-compatible with the versions they had when the Meteor release was published. This middle ground restores meaning to Meteor releases, yet still permits patch updates to core packages.

So, we should be all set here. Closing - thanks!
