### ISSUE TITLE
[1.4.1] hang on meteor starting app...

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7672]
dear author, i try run meteor:  `meteor -p 4000`
it hang at 
```
[[[[[ ~/meteor/test ]]]]]                     

=> Started proxy.                             
   Starting your app  
```

i'm using ubuntu 14.0.5
node 4.5

**Comment by benjamn** [comment]
If you continue having hard-to-diagnose-or-reproduce problems with your Meteor installation, you might consider reinstalling it with `curl https://install.meteor.com/ | sh`. This will remove your existing installation and install a fresh copy of 1.4.1.

**Comment by lyquocnam** [comment]
thanks for reply @benjamn this work !
