### ISSUE TITLE
[1.4.1] - Custom meteor build deployment error (invalid ELF header)

### ISSUE THREAD

**Issue by bakeruk** [meteor/meteor#7674]
I have built my Meteor project using the instruction guide on Meteor.com ([https://guide.meteor.com/deployment.html#custom-deployment](https://guide.meteor.com/deployment.html#custom-deployment)), once deployed I get the following error:

```
/srv/www/presenter_app/releases/20160819083707/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /srv/www/presenter_app/releases/20160819083707/bundle/programs/server/npm/node_modules/contextify/build/Release/contextify.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/srv/www/presenter_app/releases/20160819083707/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/srv/www/presenter_app/releases/20160819083707/bundle/programs/server/npm/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/srv/www/presenter_app/releases/20160819083707/bundle/programs/server/npm/node_modules/contextify/lib/contextify.js:1:34)
    at Module._compile (module.js:409:26)
```

I get the same error using multiple servers and OS:

- Ubuntu 14.04 LTS
- Red Hat 7
- AWS Linux 2016.03 (Centos)

I ran the following build command on my dev machine which used Mac OS X (El Capitan) stating the desired architecture that the project will be ran on.
```
meteor build ../ --directory --architecture=os.linux.x86_64
```
Once built I have moved the `bundle/` directory to the server via GIT. 

On the server I run the following commands as the `root` user,
```
cd bundle/programs/server/ && npm install
```
And finally,
```
cd ../../ # <--- 'bundle/'
node main.js
```

### Summary

This issue is an odd one as the error (`invalid ELF header`) implies that the desired architecture flag in the `meteor build` command is not doing it's job.

I have another project that run on meteor version 1.3 and that deploys absolutely fine using the same deployment process.

Please help!

**Comment by benjamn** [comment]
> On the server I run the following commands as the `root` user,

This may actually prevent newer versions of `npm` from modifying files not owned by `root`, which can cause problems when rebuilding. Try not running as `root`?

**Comment by bakeruk** [comment]
Cheers for the suggestion Ben.

I have spun up a new server (using the same AWS AMI - server OS and Chef recipes) to make it a fair/equal test and the same issue persists using OS's default user.

```
[deploy@meteor-test-2 bundle]$ node main.js 
/srv/www/presenter_app/releases/20160822091354/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: /srv/www/presenter_app/releases/20160822091354/bundle/programs/server/npm/node_modules/contextify/build/Release/contextify.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at Module.Mp.load (/srv/www/presenter_app/releases/20160822091354/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/srv/www/presenter_app/releases/20160822091354/bundle/programs/server/npm/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/srv/www/presenter_app/releases/20160822091354/bundle/programs/server/npm/node_modules/contextify/lib/contextify.js:1:34)
[deploy@meteor-test-2 bundle]$ ls -la
total 32
drwxr-xr-x 4 deploy apache 4096 Aug 22 09:14 .
drwxr-xr-x 8 deploy apache 4096 Aug 22 09:14 ..
-rw-r--r-- 1 deploy apache  485 Aug 22 09:14 main.js
-rw-r--r-- 1 deploy apache    7 Aug 22 09:14 .node_version.txt
drwxr-xr-x 4 deploy apache 4096 Aug 22 09:14 programs
-rw-r--r-- 1 deploy apache  541 Aug 22 09:14 README
drwxr-xr-x 2 deploy apache 4096 Aug 22 09:14 server
-rw-r--r-- 1 deploy apache  361 Aug 22 09:14 star.json

[deploy@meteor-test-2 bundle]$ cd programs/server/
[deploy@meteor-test-2 server]$ ls -la

total 120
drwxr-xr-x  7 deploy apache  4096 Aug 22 09:14 .
drwxr-xr-x  4 deploy apache  4096 Aug 22 09:14 ..
drwxr-xr-x  2 deploy apache  4096 Aug 22 09:14 app
drwxr-xr-x  3 deploy apache  4096 Aug 22 09:14 assets
-rw-r--r--  1 deploy apache 11300 Aug 22 09:14 boot.js
-rw-r--r--  1 deploy apache   192 Aug 22 09:14 boot-utils.js
-rw-r--r--  1 deploy apache   147 Aug 22 09:14 config.json
-rw-r--r--  1 deploy apache  3681 Aug 22 09:14 mini-files.js
drwxr-xr-x 21 deploy apache  4096 Aug 22 09:14 node_modules
drwxr-xr-x  3 deploy apache  4096 Aug 22 09:14 npm
-rw-r--r--  1 deploy apache   900 Aug 22 09:14 npm-rebuild-args.js
-rw-r--r--  1 deploy apache  1384 Aug 22 09:14 npm-rebuild.js
-rw-r--r--  1 deploy apache    52 Aug 22 09:14 npm-rebuilds.json
-rw-r--r--  1 deploy apache  5353 Aug 22 09:14 npm-require.js
-rw-r--r--  1 deploy apache  2956 Aug 22 09:14 npm-shrinkwrap.json
-rw-r--r--  1 deploy apache   551 Aug 22 09:14 package.json
drwxr-xr-x  2 deploy apache 12288 Aug 22 09:14 packages
-rw-r--r--  1 deploy apache 11228 Aug 22 09:14 program.json
-rw-r--r--  1 deploy apache   174 Aug 22 09:14 server-json.js
-rw-r--r--  1 deploy apache 12329 Aug 22 09:14 shell-server.js

[deploy@meteor-test-2 server]$ groups deploy
deploy : apache
```

If I run the bundle using `node` (the same way as I'm attempting above but on my dev machine) it runs with no hicups.

I'm guessing as it's the same architecture it works as intended. However I would have thought this should not work as I had specified '`os.linux.x86_64`' as the desired architecture and not '`os.osx.x86_64`'.

Which makes me think, is the `--architecture` flag working when I build the project using `meteor build ../ --directory --architecture=os.linux.x86_64`?

**Comment by benjamn** [comment]
The `--architecture` flag affects only Meteor packages that were published with `meteor publish-for-arch`, and it's supposed to select which precompiled versions of any binary npm dependencies will be used. It has no effect on other npm packages.

Since version 1.3.3, Meteor has had the ability to recompile binary npm dependencies even if you don't provide the `--architecture` flag, so it's becoming less and less useful. Our eventual plan is to [get rid of `meteor publish-for-arch` entirely](https://forums.meteor.com/t/whats-happening-to-meteor-publish-for-arch-in-meteor-1-4-1/28209).

**Comment by bakeruk** [comment]
Ah ok, then I'm a little bit stuck.

According to articles found via Google regarding the node `invalid ELF header` error.

> This happens when you build on one architecture and then attempt to use the same built addon on a different architecture.

Is this classed as a bug with Meteor as this does not happen with my other projects running version 1.3.x or is this package related?

Can you suggest a method to test and debug?

**Comment by bakeruk** [comment]
I found a way to fix the issue - It seems to be a package problem within the `bundle/programs/server/npm` files.

In the `bundle/programs/server/` directory on the production server, I had run the `node npm-rebuild` command to call the `npm-rebuild.js` file.

The rebuild appears to have downloaded packages intended for the architecture of the server. 

As the `bundle/programs/server/npm/` directory is controlled by the Meteor build process, it seems like a step is missing during build and deployment process, otherwise this issue wouldn't of arose.

Is there a step missing?

Happy to help if there is an issue =)

**Comment by abernix** [comment]
@bakeruk The `npm-rebuild.js` "fix" should actually be getting run automatically when you ran:

    cd bundle/programs/server/ && npm install

... as you said you had (and per the README in the bundle and the custom deployment steps).

With that being said, I don't believe you would experience this problem on a completely fresh Meteor project, so I suspect this has to do with some dependency of your project.  I'd be happy to take a look at this if you could make a simple reproduction of this problem using only the components that cause it to happen but as of now can't reproduce this or suggest a permanent solution.

Could you make a pass at that doing that?

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
