### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7677]
My CircleCI tests are failing with the following error:

```
=> Errors while initializing project:         
                                              
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

```
uname -a
Linux box617.localdomain 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

From `meteor show --ejson 'fourseven:scss@3.8.1'` it seems only the following architectures have been published:

```
  "architecturesOS": [
    "os.windows.x86_32",
    "os.osx.x86_64"
  ]
```

But isn't with new Meteor version `meteor publish-for-arch` command is not necessary anymore and that the package will be build locally? So why it does not work? Is this a bug?

**Comment by mitar** [comment]
A possible workaround:

```
git submodule add https://github.com/fourseven/meteor-scss.git packages/fourseven:scss
```

Does not work because of the #7675.

**Comment by Akryum** [comment]
Did you try removing and adding back the package?

**Comment by mitar** [comment]
This has been resolved by fourseven:scss releasing a new version without any binaries, requiring the package to be compiled locally.
