### ISSUE TITLE
Windows 10 rebuild time

### ISSUE THREAD

**Issue by valentinvichnal** [meteor/meteor#7680]
I had to use Windows 10 for a few days, it was a clean installation and the only thing I used was Meteor 1.4.
The initial build time felt a little slower than in win 8.1 but not considerably.
What was strange is that the whole system slowed down 5-10 minutes after a meteor app has started.

There was no high CPU, disk or network usage (0-2%), yet starting a software could take half minute what was before seconds, moving their window felt really slow and the loading time of any website in a browser increased drastically.

When I stopped the Meteor process all these problems gone, maybe it is related to the rebuild process, I didn't make any profiling because I switched back to windows 8.1.

I found these problems only in Windows 10, everything works in Windows 8.1.

**Comment by laosb** [comment]
That sounds strange. If anyone experienced this too, please report!

**Comment by benjamn** [comment]
Are you running a virus scanner? Perhaps it got swamped with new files to scan?

**Comment by valentinvichnal** [comment]
Yes it had a virus scanner but the same antivirus is on the 8.1 too where there is no such error.
If I get a win 10 pc again I will try meteor with a disabled antivirus.

**Comment by abernix** [comment]
I'm going to close this for the time-being as virus-scanners+Windows+Meteor is known (and understandably) slow due to the extremely large number of files being changed and scanned with each bundle that's generated.  Happy to reopen with additional details though!
