### ISSUE TITLE
[bug] [1.4.0.1] Deferred imports (reify) not always working ("syntax error").

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7683]
Reopening #7646.

Reproduction:

```sh
git clone git@github.com:trusktr/meteor.git --branch issue-7646 --single-branch
cd meteor
./run-dev.sh
```

The error happens for me every time.

**Comment by abernix** [comment]
Let's continue with the existing issue (which I have reopened) since it has more+the same information.
