### ISSUE TITLE
[Upgrading from Meteor 1.3 to 1.4.1] URIError: URI malformed -- Application Crashing

### ISSUE THREAD

**Issue by tmpg** [meteor/meteor#7685]
I tried to solve this issue before when updating to from 1.3 to 1.4 but was unable to. Has anyone seen this before? Let me know if I can help further...Details below:

**What version of Meteor you're using, and the platform(s) you're running it on**
Meteor v1.4.1 -- Ubuntu 16.04
**What packages or other dependencies you're using**
# **_Meteor:_** 
- meteor-base@1.0.4             # Packages every Meteor app needs to have
- mobile-experience@1.0.4       # Packages for a great mobile UX
- mongo@1.1.11                   # The database Meteor supports right now
- blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
- session@1.1.6                 # Client-side reactive dictionary for your app
- jquery@1.11.9                  # Helpful client-side library
- tracker@1.1.0                 # Meteor's client-side reactive programming library
- es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.
- ecmascript@0.5.8              # Enable ECMAScript2015+ syntax in app code
- reactive-dict@1.1.8
- audit-argument-checks@1.0.7
- check@1.2.3
- random@1.0.10
- standard-minifier-css@1.2.0
- standard-minifier-js@1.2.0
- fortawesome:fontawesome
- less@2.7.5
- huttonr:bootstrap3
- custom:lock
- alanning:roles
- settinghead:auto-nprogress
- mrt:jquery-ui
- edgee:slingshot
- react-meteor-data
- momentjs:moment
- aldeed:collection2
- underscore@1.0.9
- reywood:publish-composite
- utilities:avatar
- jagi:astronomy@=1.2.11
- jagi:astronomy-validators
- jagi:astronomy-timestamp-behavior
- jagi:astronomy-slug-behavior
- meteorhacks:kadira
- kadira:debug
- kadira:flow-router-ssr
- meteorhacks:cluster
- meteorhacks:fast-render
- meteorhacks:inject-initial
- webdeb:app-loader
- xyz:loading
- okgrow:router-autoscroll
- froala:editor-reactive
- froala:editor
- gadicc:blaze-react-component
- shell-server

# **_NPM:_**
>   "devDependencies": {
>     "@kadira/storybook": "^1.22.1",
>     "babel-core": "6.x.x",
>     "babel-plugin-react-require": "2.x.x",
>     "babel-plugin-react-transform": "2.x.x",
>     "babel-plugin-transform-class-properties": "^6.9.0",
>     "babel-polyfill": "6.x.x",
>     "babel-preset-es2015": "6.x.x",
>     "babel-preset-react": "6.x.x",
>     "babel-preset-stage-0": "^6.5.0",
>     "babel-preset-stage-2": "6.x.x",
>     "babel-root-slash-import": "1.x.x",
>     "chai": "3.x.x",
>     "enzyme": "^2.2.0",
>     "eslint": "1.10.x",
>     "eslint-plugin-react": "3.15.x",
>     "jsdom": "^8.0.4",
>     "material-ui": "0.15.2",
>     "mocha": "2.x.x",
>     "raw-loader": "^0.5.1"
>   },
>   "dependencies": {
>     "autosuggest-highlight": "2.1.1",
>     "domready": "^1.0.8",
>     "draft-js": "0.7.0",
>     "draft-wysiwyg": "0.2.4",
>     "flow-bin": "0.26.0",
>     "lodash": "^4.12.0",
>     "mantra-core": "^1.5.0",
>     "meteor-node-stubs": "^0.2.3",
>     "mobile-detect": "^1.3.3",
>     "moment": "2.13.0",
>     "rc-animate": "^2.3.1",
>     "react": "15.2.1",
>     "react-addons-css-transition-group": "^15.3.0",
>     "react-addons-pure-render-mixin": "15.1.0",
>     "react-addons-test-utils": "^15.0.2",
>     "react-autosuggest": "3.7.4",
>     "react-avatar": "1.2.2",
>     "react-bootstrap": "0.30.0",
>     "react-color": "2.2.0",
>     "react-dom": "^15.2.1",
>     "react-drive-in": "^1.7.3",
>     "react-gmaps": "^1.5.0",
>     "react-google-maps": "4.11.0",
>     "react-helmet": "^3.1.0",
>     "react-infinite-scroll-meteor": "^0.1.2",
>     "react-inline-style": "^0.1.0",
>     "react-komposer": "^1.13.1",
>     "react-mixin": "3.0.5",
>     "react-mounter": "^1.2.0",
>     "react-no-ssr": "^1.0.1",
>     "react-responsive": "1.1.4",
>     "react-scroll": "1.0.16",
>     "react-slick": "0.12.2",
>     "react-tag-input": "3.0.6",
>     "react-tap-event-plugin": "^1.0.0",
>     "react-typewriter": "^0.4.1",
>     "react-typist": "^0.3.0",
>     "react-visibility-sensor": "^3.3.0",
>     "scrollto-with-animation": "^4.2.0",
>     "sinon": "1.17.x",
>     "style-loader": "^0.13.1"
>   },

**Stack Trace**

> (STDERR) /home/linuxbox/.meteor/packages/meteor-tool/.1.4.1.45m808++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
> (STDERR)                                            throw(ex);
> (STDERR)                                            ^
> (STDERR)
> (STDERR) URIError: URI malformed
> (STDERR)     at decodeURIComponent (native)
> (STDERR)     at module.exports (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/url_parser.js:144:15)
> (STDERR)     at connect (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:266:16)
> (STDERR)     at Function.MongoClient.connect (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:113:3)
> (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:174:11)
> (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
> (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
> (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
> (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:103:40)
> (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)

I will try to upload an example when I get a chance.

**Comment by laosb** [comment]
Given the impression that you have many packages, please keep your repro minimal.

**Comment by tmpg** [comment]
Repo is as minimal as possible at the moment. Supports 200k users with less then 1MB download. Please give usable advice.

**Comment by laosb** [comment]
I mean *reproduction* by saying *repro*, which is required for contributors & maintainers to reproduce your situation. You can refer to Contributing.md about making a reproduction.

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue or comment below.

**Comment by tmpg** [comment]
This issue was caused by the inability of meteor to properly parse the MONGO_URL ENVIRONMENTAL VARIABLE. 

Example:
This worked fine in Meteor 1.3:
`export MONGO_URL=mongodb://admin:fakepassword#$%@fake.mlab.com:99999/dev meteor --port 5005 --settings settings.json;`

When upgrading to meteor 1.4 this no longer worked due to the symbols (#$%) causing meteor to think that this URI was malformed. When those symbols were not part of the password Meteor 1.4 worked fine.

Please fix.

**Comment by abernix** [comment]
Related to #7768
