### ISSUE TITLE
Picking up bad version of tar.

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7689]
### Update
This was caused by using a bad version of tar that I had on my path.

### Problem symptoms

Usually, I can work through the issues and get it figured out.  This time I am completely **FUBAR**.  I have a lot of detail below.  But the primary problem is that none of the meteor commands work.  Every one of them (except `meteor --version`) executes for a while but eventually results in:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)
```

Please help I am dead in the water.  At this point I only have the 1.4.1 dev_bundle installed and I am trying to figure out how to get rid of it and go back to 1.4.  This ate up a day.

### Environment
- Meteor: v1.4.1 (node: v4.5.0, npm: 3.10.6)
- Windows 10 Version 1511 (OS Build 10586.545)
- Node: v4.5.0

### How I got here
1. I went to my test directory and created a 1.4.0.1 project via `meteor create test`.
2. I went into the `test` project and did a `meteor update`
3. This updated for quite a while but eventually failed with the error above.
4. From here on out my default version was set to 1.4.1 and none of the commands worked without emitting the error above.
5. I noticed that `meteor node --version` reported `v4.4.7` and `meteor npm --version` reported `3.10.5` which was odd because I knew from the notes that the versions have been updated to `v4.5.0` and `3.10.6` respectively.
6. I updated my installed version of node to `v4.5.0`, but this output an error that stated "A later version of Node.js is already installed. Setup will now exit."  However, when I checked my node version and the meteor version they were all reporting `v4.4.7`.
7. I found this forum [issue](https://forums.meteor.com/t/meteor-update-error/28243/1).  And decided I should wipe my slate clean and reinstall Meteor.
8.  I uninstalled meteor and also cleaned out `C:\Users\username\AppData\Local\.meteor`
9. I installed node `v4.5.0`.
10. I installed meteor from meteor.com.

### Result
Nothing works always results in:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EOF
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)
```

**Comment by brucejo75** [comment]
Minutes after I submitted this issue I attempted another tack...

Reading through the notes, I see that you will use my installed version of tar.  On windows, I typically do not use tar and I have other tools.  But it turned out that I had a very old version of `tar.exe` in my bin directory.  And the meteor install was finding and using it.

I also have `7z.exe` which is reasonably new. So I removed my version of `tar.exe` and now Meteor is finding `7z.exe` I believe.

Error gone!

PS: I am hoping the new ubuntu bash shell in windows will be able to work with meteor and I can use updated versions of linux tools soon.

**Comment by brucejo75** [comment]
Recommend that Meteor have a mode of running that will flag each of the native tools it depends on?

**Comment by laosb** [comment]
Maybe we should just check the version of `tar.exe` or `7z.exe`.

**Comment by benjamn** [comment]
On Windows, Meteor comes with a standalone version of `7z.exe` (i.e., `dev_bundle\bin\7z.exe`), so we should probably just prefer that over `tar` on Windows.

**Comment by jalalat** [comment]
Hi @benjamn by path you mean Path in Env Variables, right? I do not have tar.exe in my path but i am still seeing this error.

**Comment by zipzit** [comment]
@jalalat  that file could be anywhere.  On my computer I had one copy of tar.exe at location  C:/MinGW/msys/1.0/bin  and another copy at C:/TexasInstruments/xdc_tools_3_20_08_88/bin   You are just going to have to search.  I used Windows Explorer which is painfully slow.

**Comment by brucejo75** [comment]
you can use `where` to find it.  e.g.
```
where tar
```
will find all versions of tar on your path.

**Comment by AliMor** [comment]
I still have the issue. My question is why it stopped working all of the sudden?

**Comment by brucejo75** [comment]
Look at [release notes](https://github.com/meteor/meteor/blob/devel/History.md) for v1.4.1:

> * After Meteor packages are downloaded from Atmosphere, they will now be extracted using native tar or 7z.exe on Windows, instead of the https://www.npmjs.com/package/tar library, for a significant performance improvement. #7457
>
> * The npm tar package has been upgraded to 2.2.1, though it is now only used as a fallback after native tar and/or 7z.exe.

**Comment by AliMor** [comment]
@brucejo75 thanks for your help. I went almost through all step before jumping online and search if anyone else has the same issue. now extracting takes a long time to finish; I had couple of tar files in my path though. Removed all. I am probably going to update my node as well.

**Comment by benjamn** [comment]
> I am probably going to update my node as well.

Meteor comes with its own version of Node, by the way, and you can use it by running `meteor node ...`. Installing Node on your system outside of Meteor is neither necessary nor especially helpful.

**Comment by smeijer** [comment]
I had this issue when trying to update to a specific release.

Updating tar.exe to a new version helped indeed. Thanks!

**Comment by michaeldewal** [comment]
This does not solve the problem for me, I renamed the tar.exe in my git folder.
My update or run is still stuck on "extracting templating@1.1.19" it will never finish.
Windows 10 here.

**Comment by brucejo75** [comment]
did you try getting a new version of `tar.exe`?  Or use a version of `7z.exe`?  And then put those on your path?

**Comment by fafournier** [comment]
After 5 days searching, finally found that thread. I didn't have tar.exe in the path apparently but using `where tar.exe`, I found it came with git: C:\Program Files (x86)\Git\bin\tar.exe !
