### ISSUE TITLE
Add visual cue to accounts-ui package when user is logging out

### ISSUE THREAD

**Issue by EvNaverniouk** [meteor/meteor#769]
See this thread: https://groups.google.com/forum/?fromgroups=#!topic/meteor-talk/Obg62KR1Lq8

There should be a visual cue (ie loading animation) when the Sign Out button is pressed. Because sometimes the sign out process takes a while and it looks like nothing is happening.

**Comment by glasser** [comment]
We have a new feature request policy so I'll reopen this: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests

**Comment by raix** [comment]
sounds cool @glasser :+1:

**Comment by hwillson** [comment]
I'll work on getting a PR in for this (since it will address both this issue and #1331).

**Comment by abernix** [comment]
This does seem like it would be a nice little addition!

**Comment by hwillson** [comment]
I created PR #8271 to help address this issue (very much based on @raix's original code - thanks!).

**Comment by hwillson** [comment]
PR #8271 has been merged, so this functionality will be coming soon! Thanks everyone!

**Comment by abernix** [comment]
This should be fixed in Meteor 1.4.3.2.  You can try the latest 1.4.3.2 beta and help confirm by running:

    meteor update --release 1.4.3.2-beta.0

Please report back if you encounter any problems, and thanks for taking reporting this!
