### ISSUE TITLE
Allow testing non-local packages

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7691]
Currently it is possible to test only ~~non-~~local packages. It would be great if it would be possible to any package an app is using as well. The reason is that we just had a bug our Circle CI has not cough because it is in one of dependencies which was not compatible anymore with Meteor 1.4. If we would run its tests we would discover this even sooner.

Edit by @abernix to remove "non-" which was the opposite of the request. :smile:

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20testing%20non-local%20packages&body=Migrated%20from:%20meteor/meteor%237691) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
