### ISSUE TITLE
Cordova 6.0.0 Gradle 2.2.1 app can't handle Multidex (64K DEX error)

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#7693]
**Meteor version: 1.4.1
Plateform: Android**

When you add plugins, the limit o the [64K methods](https://developer.android.com/studio/build/multidex.html#about) included in the APK could be easily reachable.
There is two ways to avoid this. Use Proguard to shrink the dead code or use Multidex to overpass the limit of 64K.
But you need to tweak the Android project for that and breaks the way of Meteor abstract native code project.
Fortunately there is a plugin called cordova-multidex which can enable Multidex for you. But there is no way to make it work with the current Gradle version used by Cordova 6.0.0.
### Repro steps:
1. Create an empty app
2. add Android platform
3. past this in the _.meteor/cordova-plugins_

```
cordova-plugin-crosswalk-webview@2.0.0
cordova-plugin-mapbox@https://github.com/dagatsoin/Mapbox.git#79713dd8d91af26994aaa5fe0b49dd741b7869da
cordova-plugin-mauron85-background-geolocation@https://github.com/mauron85/cordova-plugin-background-geolocation.git#8acb476e58ec9d6874a2857aeb6a36dd66a6374c
cordova-sqlite-storage@https://github.com/litehelpers/Cordova-sqlite-storage.git#0381d9fa7e30d1be90773b0eaafd606d07b09413
me.tonny.cordova.plugins.multidex@https://github.com/jwall149/cordova-multidex.git#be54d0ed263911e4b0bf8f21e52df1dba4ca94ea
```
### Excepted behavior

APK methods number would grow up to 64+ but app should be run by enabling `multiDexEnabled true`thanks to [Multidex plugin](https://github.com/jwall149/cordova-multidex.git)
### Actual behavior

App crash with error:

```
W/dalvikvm: Link of class 'Lorg/xwalk/core/internal/XWalkPresentationHost;' failed
W/System.err: java.lang.NoClassDefFoundError: org/xwalk/core/internal/XWalkPresentationHost
W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:368)
W/System.err:     at java.lang.System.loadLibrary(System.java:535)
W/System.err:     at org.xwalk.core.internal.XWalkViewDelegate.loadXWalkLibrary(XWalkViewDelegate.java:134)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err:     at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61)
W/System.err:     at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:360)
W/System.err:     at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:258)
W/System.err:     at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:172)
W/System.err:     at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:337)
W/System.err:     at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/System.err:     at java.lang.Thread.run(Thread.java:856)
W/System.err: Caused by: java.lang.ClassNotFoundException: org.xwalk.core.internal.XWalkPresentationHost
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err:   ... 19 more
```
### Workarounds
- Open the built cordova project in Android Studio and configure gradle.build (Module: Android) according to [the manual](https://developer.android.com/studio/build/multidex.html#mdex-gradle)
- I recreated another Cordova project with the same plugins (except meteor-wepapp) and bump Gradle version to 2.14.1 and the cordova-plugin-multidex did the job.
- use a fork of the cordova-plugin-multidex https://github.com/dagatsoin/cordova-multidex

**Comment by dagatsoin** [comment]
If some one could try reproducing this... to see if it is really due to cordova version ?
I managed to use a fork of [cordova-plugin-mulidex](https://github.com/dagatsoin/cordova-multidex) by swapping the lifecycle from `before_compile` to `after_plugin_install`
If someone could confirm this, maybe it will be useful to add it in the doc, because it is an issue that people who use plugins will surely have.

**Comment by crazybaud** [comment]
With Meteor 1.3.4.1 + Ionic 1.2.4

We have this issue `com.android.dex.DexIndexOverflowException: Cannot merge new index 67365 into a non-jumbo instruction!` after Intercom update.

We used `meteor add cordova:cordova-plugin-mulidex@https://github.com/dagatsoin/cordova-multidex/tarball/b445f835b261eb6edb41a1285debcdf0a65d91ef`, perfect, thanks :)

`meteor add cordova:cordova-plugin-multidex@https://github.com/jwall149/cordova-multidex.git#be54d0ed263911e4b0bf8f21e52df1dba4ca94ea` is also working for our version, but we kept your version.

**Comment by hwillson** [comment]
Given that there have been many new Meteor releases since this issue was created, along with numerous changes to Meteor's mobile dependencies, I recommend trying things out with Meteor 1.6 to see if this problem is still happening. If so, please post back and let us know. Closing for now - thanks!
