### ISSUE TITLE
Please add findAndModify support

### ISSUE THREAD

**Issue by valentinvichnal** [meteor/meteor#7694]
My meteor app has a simple credit system,
I am not sure how secure is to use a Find to get an ID then right after make this item
"passive" with an Update so any Find after this not going to return that item.

With a few user only maybe this would work fine but after a certain troughput there is going to be an unwanted state where two Find will select the same item before the first Update can happen.

findAndModify solve this problem and many other security problem similar to this, there is currently one community created package which tries to add this support but it does not work after 1.4.
https://github.com/fongandrew/meteor-find-and-modify

This shouldn't be a community created feature because we don't know what you change with the MongoDB driver internally, a package like this is only easy to maintain for a MDG member.

Could you please add this feature, I think it is a basic functionality and would make make many meteor applications more secure.

**Comment by valentinvichnal** [comment]
#1070

**Comment by mitar** [comment]
Duplicate.

**Comment by mitar** [comment]
But if it is unclear that this exist, then open an issue to better document it.
