### ISSUE TITLE
meteor npm shrinkwrap error

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7696]
Running into this issue which seems to be resolved in npm v3.10.7
https://github.com/npm/npm/issues/13327

Is there a planned version bump for Meteor Npm?

**Comment by serkandurusoy** [comment]
I've hit the same problem so work around it by using my global npm installation instead of meteor's.

**Comment by abernix** [comment]
Thanks for pointing this out!  NPM has been bumped to 3.10.7 via https://github.com/meteor/meteor/pull/7668/commits/d411113e7f876b7266d8a45343f3541e10ab8234 and will be included with Meteor 1.4.2 when it is ultimately released.  Follow #7668 for updates on that!

**Comment by benjamn** [comment]
You can also force-upgrade the version of `npm` used by the `meteor npm` command by running `meteor npm install -g npm@3.10.7`. You can check that it worked by running `meteor npm version`.

Note that this new version of `npm` will be installed only for the specific version of Meteor displayed by `meteor --version`, which is sensitive to the `.meteor/release` file in the current app, so you may need to run `meteor npm install -g npm@3.10.7` more than once, if you have different apps that are pinned to different versions of Meteor.
