### ISSUE TITLE
Meteor install scripts: error 403 (tarball unavailable?)

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7697]
The Meteor install shell script fails with a 403 error.

It tries to request this file: https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.4.1.1/meteor-bootstrap-os.linux.x86_64.tar.gz

Which indeed (at this moment) gives this error:
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>901EBFD6DFCFB0B3</RequestId>
<HostId>
GEu0Gz3mu1kD7jobnPYr8ymFn/DJGUcKtr2KP3gkRbNDeCSG/w1bNONVnMsyyCIXhUWDegFT3Xw=
</HostId>
</Error>
```

However, I also see no release notes for `1.4.1.1` in `history.md`, so could it be the install script wrongly has this version set?

**Comment by sebakerckhof** [comment]
For people experiencing this issue, the temporary workaround is to change `1.4.1.1` to `1.4.1` in the install script.

**Comment by 3nki** [comment]
where is the install script you refer to? i'm on os x. i tried the curl command provided (curl https://install.meteor.com/ | sh) which just gives a 403 Forbidden response.

**Comment by sebakerckhof** [comment]
this script: https://install.meteor.com/ The 403 is from the tarball the install scripts tries to download.

**Comment by sebakerckhof** [comment]
So, instead, just use this: https://gist.github.com/sebakerckhof/c057ce899e5dc8e4239262429350e9f2

**Comment by Carl-Hee** [comment]
....looks like tomcat config error

**Comment by THPubs** [comment]
Same issue here! Have the issue in both my server and local machine. Looks like its a global issue :-)

**Comment by area** [comment]
Doing `curl https://install.meteor.com/?release=1.4.1` will work and install the previous version until this gets sorted.

**Comment by skemb321** [comment]
@area thanks for sharing the release option! Cheers

**Comment by benjamn** [comment]
This should be fixed now. The 1.4.1.1 was accidentally not published before the release was recommended. Sorry for the inconvenience!

**Comment by Thorsten1987** [comment]
I faced the same problem today while installing meteor with curl https://install.meteor.com/ | sh. I am getting:
curl: (22) The requested URL returned error: 403 Forbidden

Does anyone can help me out on that?
