### ISSUE TITLE
Let users pick which server to connect after app builded on cordova

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#7698]
We have tried change root url or ddp url on client and it works, but after a page refresh or app restart then we lost login state that because ddp url was reset by this line of code/

    https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate_web.cordova.html#L14

it would be nice to have capability to load ddp url from localStorage.

    __meteor_runtime_config__.ROOT_URL = localStorage.get('cordova_root_url') || __meteor_runtime_config.ROOT_URL

or

    {{#each css}}  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="{{url}}">{{/each}}

      <script type='text/javascript'>
        __meteor_runtime_config__ = JSON.parse(decodeURIComponent({{meteorRuntimeConfig}}));

        if (/Android/i.test(navigator.userAgent)) {
          // When Android app is emulated, it cannot connect to localhost,
          // instead it should connect to 10.0.2.2
          // (unless we're using an http proxy; then it works!)
          if (!__meteor_runtime_config__.httpProxyPort) {
            __meteor_runtime_config__.ROOT_URL = (__meteor_runtime_config__.ROOT_URL || '').replace(/localhost/i, '10.0.2.2');
            __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = (__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL || '').replace(/localhost/i, '10.0.2.2');
          }
        }
      </script>

    {{#each beforeEverythingLoadJs}}
    
      {{#if ../inlineScriptsAllowed}}
        <script type='text/javascript'>
          {{contents}}
        </script>
      {{else}}
        <script type='text/javascript'
                src='{{rootUrlPathPrefix}}{{pathname}}'></script>
      {{/if}}
    {{/each}}

**Comment by laosb** [comment]
That sounds same as #7617, we should track this there.
