### ISSUE TITLE
Cannot install latest meteor on windows 7

### ISSUE THREAD

**Issue by tlambeir** [meteor/meteor#7700]
I'm trying to use the windows installer on windows 7 downloaded from here https://www.meteor.com/install. 

It imediatly installs in less than a second, which already seems suspicious to me, then it shows the account step which I'm skipping. 

When I look at my installed programs in windows, meteor is listed but when I go to the C:\Users\[MyUser]\AppData\Local\ folder there is no .meteor folder.

I've tried uninstalling  and reinstalling also removing all instances of meteor I can find in the registry via regedit and rebooting the pc multiple times. But the .meteor folder just does not get created in the Local AppData folder.

I have a feeling my installer cannot reach your server but I'm not sure how to confirm this.

**Comment by TekVanDo** [comment]
+1

**Comment by DerekChia** [comment]
I'm also getting the following error...

`ubuntu, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
Downloading Meteor distribution

curl: (22) The requested URL returned error: 403 Forbidden
Retrying download in 5 seconds...`

**Comment by carlevans719** [comment]
It looks like it's the 1.4.1.1 release. 

You can use `curl https://install.meteor.com | sed 's/RELEASE="1.4.1.1"/RELEASE="1.4.1"/g' | sh` as a workaround while waiting for a fix

**Comment by tlambeir** [comment]
That workaround does not work on windows which is why I made this issue.

**Comment by benjamn** [comment]
This should be fixed now. The 1.4.1.1 was accidentally not published before the release was recommended. Sorry for the inconvenience!
