### ISSUE TITLE
[1.4.1.1] Unable to update to 1.4.1.1 in ubuntu x86_64 - Access Denied

### ISSUE THREAD

**Issue by merunga** [meteor/meteor#7701]
> curl https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.4.1.1/meteor-bootstrap-os.linux.x86_64.tar.gz #filename extracted from installation script

<?xml version="1.0" encoding="UTF-8"?>
\<Error\>
  \<Code\>AccessDenied\</Code\>
  \<Message\>Access Denied\</Message\>
  \<RequestId>4686F85256FF7097\</RequestId\>
  \<HostId\>
     8jqz+RE60jbGLQTIlsJzHlck8IchQq+6iEDBe8FckQQHwP83sKaE542JJrSK/BeRnCAnjYJeiVQ=
  \</HostId\>
\</Error\>

**Comment by benjamn** [comment]
This should be fixed now. That URL didn't exist before, but does now. Sorry for the inconvenience!
