### ISSUE TITLE
meteor cnpm 

### ISSUE THREAD

**Issue by Jerret321** [meteor/meteor#7707]
In China, meteor developers have to use meteor with proxy.  
The package `cnpm` is developed by Alibaba and visited with  the China mirror.
Developers can install package more quickly without any proxy. 
Meteor can support `meteor cnpm` when someone install the global package `cnpm`.

**Comment by crapthings** [comment]
为什么不直接 cnpm i 一下就行了？

为啥非得加个 meteor cnpm ??

**Comment by Jerret321** [comment]
多谢提醒 试了下 可以的

**Comment by nabilfreeman** [comment]
For anybody coming from Google I found a good solution...

Run this in Terminal:
`npm config set registry https://registry.npm.taobao.org`

Now, NPM = CNPM!

**Comment by nabilfreeman** [comment]
For anybody coming from Google I found a good solution...

Run this in Terminal:
`npm config set registry https://registry.npm.taobao.org`

Now, NPM = CNPM!
