### ISSUE TITLE
Meteor publish also "-tests" file

### ISSUE THREAD

**Issue by osv** [meteor/meteor#7709]
I publish to atmosphere small package https://github.com/osv/meteor-mongo-counter which have 2 files: counter.coffee, counter-tests.coffee

When I use this package I have error - meteor trying use tinytest which is used in test file and fail. So I check folder of meteor cache and found my **counter-tests.coffee.js**:

```
  /home/olexandr/.meteor/packages/osv_mongo-counter/.0.3.3.dcg0vg++os+web.browser+web.cordova/os/packages/osv_mongo-counter:
  total used in directory 16K available 198676416
  drwxr-xr-x 2 olexandr 4,0K 2016-08-25 12:56 ./
  drwxr-xr-x 3 olexandr 4,0K 2016-08-25 12:56 ../
  -r--r--r-- 1 olexandr 2,0K 2016-08-25 12:56 counter.coffee.js
  -r--r--r-- 1 olexandr 1,3K 2016-08-25 12:56 counter-tests.coffee.js
```

Here is my package.js:
```js
Package.describe({
  summary: "Atomic counters stored in MongoDB",
  version: "0.3.3",
  git: "https://github.com/osv/meteor-mongo-counter.git",
  name: "osv:mongo-counter"
});

Package.onUse(function (api) {
  api.versionsFrom("METEOR@1.0.4");
  api.use(['coffeescript', 'mongo-livedata','underscore'], 'server');
  api.addFiles('counter.coffee', 'server');
  if (api.export) {
    api.export('incrementCounter', 'server');
    api.export('decrementCounter', 'server');
    api.export('setCounter', 'server');
    api.export('deleteCounters', 'server', {testOnly: true});
  }
});

Package.onTest(function(api) {
  api.use('coffeescript');
  api.use('tinytest');
  api.use('osv:mongo-counter');
  api.addFiles('counter-tests.coffee', 'server');
});
```

- I tried to update meteor before publish (`curl https://install.meteor.com/ | sh`) but it not help.
- I don't `git push` updated my repo before publish (as I know publishing not depend on git repo)

To reproduce error.
```
meteor create test
cd test
meteor add osv:mongo-counter
meteor
```

**Comment by osv** [comment]
I comment 
```js
Package.onTest(function(api) {
  api.use('coffeescript');
  api.use('tinytest');
  api.use('osv:mongo-counter');
  api.addFiles('counter-tests.coffee', 'server');
});
```
block, but when I publish the file `counter-tests.coffee` is published too, so I temporary remove -test file, comment onTest and publish. I think problem is in coffescript module.

**Comment by abernix** [comment]
Your steps to reproduce the error do not cause an error for me.  Can you please be more clear about what you're trying to accomplish?  Why don't you want to publish your package tests with your package?  Frequently users will want to run your package tests themselves to make sure they work.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and have not been able to reproduce it with what you provided.  I would be happy to reopen it if this is still a problem for you and you can come up with some additional details that are helpful in resolving it! :)
