### ISSUE TITLE
After upgrade to Meteor 1.4.1.1 & MongoDB 3.2.9 MongoDB passwords containing % fail to authenticate

### ISSUE THREAD

**Issue by mjgallag** [meteor/meteor#7713]
I had a `%` in my old `MONGO_OPLOG_URL` password, `^Co387mA%10^`, (that I'm no longer using anywhere) and it worked just fine until I upgraded to `Meteor 1.4.1.1` & `MongoDB 3.2.9` at which point passwords containing `%` stopped working.

It would be great to see if someone else can reproduce this issue. If so, even if we don't get so far as to root cause it, we can at least add something to the docs so others can avoid my pain.

```
{
  "galaxy.meteor.com": {
    "env": {
      "MONGO_URL": "mongodb://username:password@ds017448-a0.mlab.com:17448,ds017448-a1.mlab.com:17448/qeople?replicaSet=rs-ds017448",
      "MONGO_OPLOG_URL": "mongodb://username:password@ds017448-a0.mlab.com:17448,ds017448-a1.mlab.com:17448/local?authSource=admin&replicaSet=rs-ds017448"
  }
}
```

Thanks!

**Comment by mjgallag** [comment]
See my proposed change to MongoDB's Connection String Spec mongodb/specifications#105 requiring `%` to be URL encoded since it's already required for `@` and `:` thus not requiring for `%` leads to ambiguity.

**Comment by abernix** [comment]
@mjgallag Did you explicitly find an explanation for the change in behaviour with the Mongo Connection String in Meteor 1.4 and why?  See related #7768 and my comments there.

**Comment by mjgallag** [comment]
@abernix No I didn't go so far as to root cause it.
