### ISSUE TITLE
File referencing without path

### ISSUE THREAD

**Issue by jesperordrup** [meteor/meteor#7714]
In the good old meteor days it was so amazing that you didnt have to reference files. Everything was so easy to reorganize over and over. And we do that. A lot. Of course the problem was that we couldn't control what was loaded and in which order. 

So it was solved and now we have:

import what from '../what.js';
import { stuff } from './../../stuff.js';

Kind of ugly. And really not easy to move stuff around. Not flexible at all and reorgs are not easy.

Consider this:

import what from '~/what.js';
import { stuff } from '~/stuff.js';
import '~/memememe.css';

Think of it as the "find first file with this name" operator. And you could still do a specific reference when needed:

import { stuff } from '../../lib/stuff.js';
import { what } from '~/what.js';

Best
jesper

**Comment by laosb** [comment]
I guess you can just use `import` to import from `imports/` where you need to control the load order, and use the old *magic* way like before out of `imports/`. Closing since it can be properly addressed by yourself. If anyone think it's good to have, +1 and I'll reopen this.

**Comment by LDubya** [comment]
@laosb from what I've read, the 'old magic way' is going away right? If so, how is this properly addressed by Meteor? Unless the 'old magic way' is here to stay and I missed that update.

**Comment by laosb** [comment]
@LDubya The old magic way is still available outside of `/imports`. Meteor just use the magic way, but don't process files in `/imports` in the magic way since it's intended for `import`s.
