### ISSUE TITLE
httpProxy.createProxyServer is not a function

### ISSUE THREAD

**Issue by QbyteFennek** [meteor/meteor#7717]
I installed meteor and restarted pc. Meteor appears to be working.

>git clone https://github.com/bsliran/angular2-meteor-base.git
>meteor npm install
>meteor

At this point I get the following error:

```
C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

TypeError: httpProxy.createProxyServer is not a function
    at Proxy.start (C:\tools\runners\run-proxy.js:40:28)
    at Runner.start (C:\tools\runners\run-all.js:117:16)
    at Object.exports.run (C:\tools\runners\run-all.js:320:10)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:359:17)
    at C:\tools\cli\main.js:1402:23
```

also doesn't work after:
>meteor update

What do?

**Comment by tmeasday** [comment]
@Urigo sounds like this may need updating?

**Comment by QbyteFennek** [comment]
@tmeasday is  there anything I can do in the meanwhile?

**Comment by tmeasday** [comment]
@QbyteFennek actually looking at this again, this looks like just a (really weird) problem with your meteor installation. Can you run a simple app?

```
cd <somewhere>
meteor create app
cd app
meteor
```

?

**Comment by QbyteFennek** [comment]
@tmeasday Same error. I have already tried uninstalling and reinstalling a couple of times.

**Comment by seedgabo** [comment]
same issue here

**Comment by tmeasday** [comment]
I'm not seeing this. @QbyteFennek there seems to be some odd paths in that stack trace above. Why is there something in `C:\tools`? (I'm no expert on the windows installation, but that doesn't seem right).

**Comment by tmeasday** [comment]
(It could be something weird in error reporting on windows I guess).

What do you see the file:

```
C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\package.json
```

Specifically the `"version"` field?

**Comment by QbyteFennek** [comment]
@tmeasday I only have this error at work and I'm not going today or tomorrow. I will post an update when I go there.

**Comment by QbyteFennek** [comment]
@tmeasday There is no such file in that location. node_modules only has a bunch of modules, no json files.

**Comment by QbyteFennek** [comment]
@tmeasday On a sidenote, there is nothing in C:\tools . There is no such folder. I don't know why meteor is trying to access it

**Comment by tmeasday** [comment]
I suspect the error message is just misreporting the paths for the stacktrace.

Apologies, I meant:

```
C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\http-proxy\package.json
```

**Comment by QbyteFennek** [comment]
@tmeasday "version": "1.11.1"

**Comment by QbyteFennek** [comment]
[package.zip](https://github.com/meteor/meteor/files/461033/package.zip)

**Comment by tmeasday** [comment]
@QbyteFennek and I supposed the file `.../http-proxy/lib/http-proxy.js` contains a function `createProxyServer` too?

Is it possible your node include path is weird? Do you have `NODE_PATH` set?

**Comment by QbyteFennek** [comment]
@tmeasday 

```
module.exports.createProxy = function createProxyServer(options) {
return new httpProxy.Server(options);
};
module.exports.createProxy = function createProxyServer(options) {
return new httpProxy.Server(options);
};
```

Where do I set the `NODE_PATH` ? If you mean a system variable then no, I can't find anything like that.

**Comment by tmeasday** [comment]
It looks like you have the right thing in your dev bundle (which is probably not surprising really). When `run-proxy.js` does `require('http-proxy')` it is clearly not getting the file out of the dev bundle.

I can [see](https://github.com/meteor/meteor/blob/devel/meteor.bat#L38-L41) that the `meteor.bat` script is setting `NODE_PATH` to within the dev bundle anyway (sorry, I'm not completely up to speed with how the windows version works).

Does it also fail if you run that script directly? (It should be at `C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\meteor.bat`)

**Comment by QbyteFennek** [comment]
@tmeasday When I run the bat file directly, it opens and then does some things, no messages pop up and then it closes. So I suppose it doesn't fail. Althought I could be wrong since I don't know what it's supposed to do.

**Comment by tmeasday** [comment]
I mean when you run `meteor` on the command line it just runs that bat file? Are you running it on the commandline also?

**Comment by QbyteFennek** [comment]
```
C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:19
  if (p[0] === "\\" && (! partialPath)) {
       ^

TypeError: Cannot read property '0' of undefined
    at toPosixPath (C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:19:8)
    at Object.convertToStandardPath (C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:56:12)
    at Object.files.getHomeDir (C:\tools\fs\files.js:1294:13)
    at defaultWarehouseDir (C:\tools\packaging\tropohouse.js:31:43)
    at Object.<anonymous> (C:\tools\packaging\tropohouse.js:40:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\jente\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
```

**Comment by QbyteFennek** [comment]
Maybe I'm misunderstanding you. The above is what happens when I run the bat file from the commandline.

When I just run meteor  outside an app folder I just get an error that I'm not in a meteor app folder. Inside an app folder I get the error from the title

**Comment by tmeasday** [comment]
No, sorry, I just don't have a windows machine in front of me. It looks like the top level executable (the one that `meteor` runs) sets the `METEOR_INSTALLATION` environment variable. If you set it to `C:\Users\jente\AppData\Local\.meteor` before running the script what happens?

**Comment by QbyteFennek** [comment]
@tmeasday No worries,

Same error though I'm afraid

**Comment by QbyteFennek** [comment]
@tmeasday Update here: It does seem to be path related. It didn't work before because I was trying in an app that was created before I changed the path. I created a whole new meteor app now and now it works.

**Comment by QbyteFennek** [comment]
@tmeasday Thank you

**Comment by seandlg** [comment]
hi folks
