### ISSUE TITLE
Support for equality in Arrays, including unordered arrays

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#7724]
Discussion for PR #7723 , @laosb

 - __Description__: Support for equality in Arrays, including unordered arrays. EJSON package
 - __Why__: We use this equality on our end. Reduce template re-rendering, and in Server -> Client reactive data updates, if reactive data sources is unordered arrays
 - __Solution__: 
    * Copy comparable Arrays
    * Walk through elements until first match, then remove matched elements from array, walk again through smaller array
    * If matching elements not found in a single loop walk - stop loop, return `false`
 - __Testing__: 
    * All tests is passed
    * Additional tests for new behaviour is added

Old behaviour:

```js
EJSON.equals({a: ['a', 'b', 'c']}, {a: ['c', 'a', 'b']}); // false
EJSON.equals(['a', 'b', 'c'], ['c', 'a', 'b']); // false
```

New behaviour:
```js
EJSON.equals({a: ['a', 'b', 'c']}, {a: ['c', 'a', 'b']}); // true
EJSON.equals(['a', 'b', 'c'], ['c', 'a', 'b']); // true
```

Can be used with `keyOrderSensitive` option: 
```js
EJSON.equals(['a', 'b', 'c'], ['a', 'c', 'b'], {keyOrderSensitive: true}); //false
EJSON.equals(['a', 'b', 'c'], ['a', 'b', 'c'], {keyOrderSensitive: true}); //true
```

**Comment by laosb** [comment]
That sounds like you changed the old behavior. In my opinion you should leave the old behavior there and use options to enable the new behavior so we can make sure all old code run.

Btw, we may want to update the docs accordingly.

**Comment by dr-dimitru** [comment]
Hi @laosb ,

 1. This changes may (*or may not*) "*Reduce template re-rendering, and in Server -> Client reactive data updates, if reactive data sources is unordered arrays*". I didn't saw any changes, but I'd like to do tests if someone can point me to the right direction.
 2. `In my opinion you should leave the old behavior there and use options to enable the new behavior`. Yes, I can implement this via option (*3rd arguments*). And I'll update docs then

Waiting for response on first statement. If MDG believes there is not benefit in speed and optimisation - I'll implement this as option.

**Comment by mitar** [comment]
I think you can get speed and optimization by using custom equality functions in templates, instead of trying to change defaults. You probably cannot change defaults because you will break compatibility.

With arrays, in general there are multiple different ways you might want to compare them. [Sometimes even simply by reference of elements](https://github.com/peerlibrary/meteor-base-component/blob/master/lib.coffee#L1). So no one-size-fits-all can really be made here.

**Comment by mitar** [comment]
BTW, I do not think that `keyOrderSensitive` is a good name for order of array elements to be respected.

**Comment by dr-dimitru** [comment]
@mitar you want to call it `indexOrderSensetive`?
What if we have something like this?:
```js
EJSON.equals({a: ['a', 'c', {b: ['e', 'f', 'd']}]}, {a: ['c', 'a', {b: ['d', 'e', 'f']}]}, {keyOrderSensitive: true}); //false
```

**Comment by dr-dimitru** [comment]
@mitar 

> You probably cannot change defaults because you will break compatibility.

I see no difference currently in running code, but I'm ready to do tests. I just have no idea how properly test it.

> I think you can get speed and optimization by using custom equality functions in templates

EJSON deeply integrated in `ReactiveDict`/`ReactiveVar` and other functionality responsible for reactive re-rendering.

> With arrays, in general there are multiple different ways you might want to compare them.

Yes, if arrays has certain values type like `[String]` or `[Number]` we can make function very optimised, but in our case it might be any JS Object.

**Comment by mitar** [comment]
Yes, but then I think there should be a way to configure equality function. See #4073.

**Comment by dr-dimitru** [comment]
@mitar great performance issue ticket, btw...

> should be a way to configure equality function

`RectiveVar` constructor already has second argument, or you mean `EJSON.equals` should be default? If so, my PR is great chance to reduce re-rendering

**Comment by mitar** [comment]
I think there should be some way to configure what Blaze uses as a default, so you could swap default `ReactiveVar` with some other with uses a different equality function. For example one, which for arrays do what you are proposing above.

**Comment by dr-dimitru** [comment]
Hey @laosb and @mitar ,

 - On what we've stopped?
 - Do I need to change something in PR?
 - What next steps?

**Comment by mitar** [comment]
You have to propose a backwards compatible change.

**Comment by dr-dimitru** [comment]
@mitar if this is non-breaking change?

**Comment by mitar** [comment]
What do you mean? Your proposed new behavior is a breaking change.

```
EJSON.equals(['a', 'b', 'c'], ['c', 'a', 'b']); // true
```

This is different than it was until now.

**Comment by dr-dimitru** [comment]
Okay,

I meant - it isn't breaking other packages behaviour
Anyways I wouldn't argue on this.
 - What should be default behaviour new or old?
 - I can take a look on Blaze package to implement option to set default comparison function, according to #4073 , is this needed or it is already in progress?

**Comment by mitar** [comment]
> it isn't breaking other packages behaviour

What do you mean? You mean tests are passing for other packages? Yes, but other developers might used this function to check equality of arrays with order. We cannot just change it.

> What should be default behaviour new or old?

Old.

> I can take a look on Blaze package to implement option to set default comparison function, according to #4073 , is this needed or it is already in progress?

I think this would be the best way. You want this change to improve Blaze. Not to change EJSON as it is (EJSON can be used also outside Blaze).

I do not think anybody is working on #4073. Also, I migrated that to new Blaze repository: https://github.com/meteor/blaze/issues/68

I also explained there how I would address this issue. Feel free to take it over and make a pull request (with tests). I think it should address your use case.

**Comment by mitar** [comment]
> Server -> Client reactive data updates

Where is this coming from? What is an use case here? You could just use Minimongo to store this data on the server instead of an array with EJSON comparison?

Do we need some other place to change default equality function?
