### ISSUE TITLE
Meteor Shell (Server Unavailable) After Upgrading to 1.4.1

### ISSUE THREAD

**Issue by smilansky** [meteor/meteor#7729]
Our team cannot access `Meteor Shell` after upgrading to 1.4.1. We see `Server Unavailable (waiting to reconnect)` in the console. 

What we have tried to fix this:

- Reinstalling Meteor
- `Meteor Reset`

Has anyone else experienced this?

**Comment by mikepaszkiewicz** [comment]
broken for me as well in 1.4+, downgrading to 1.3.4.1 fixes it. meteor debug is also acting like it can't connect to the server in node inspector - possibly related?

**Comment by tmeasday** [comment]
Did the upgrader run successfully? Do you have `shell-server` in `.meteor/packages`?

**Comment by MalcolmGC** [comment]
Thanks. The shell-server was not in my .meteor/packages.
> meteor add shell-server
 fixed the problem of getting the message "Server unavailable (waiting to reconnect)".

**Comment by tmeasday** [comment]
@smilansky @mikepaszkiewicz does this fix the problem for you?

**Comment by smilansky** [comment]
@tmeasday yes it did, thanks!

**Comment by mikepaszkiewicz** [comment]
@tmeasday all good, thx tom!

**Comment by tmeasday** [comment]
Awesome!

**Comment by yogiben** [comment]
@tmeasday it would be good to get a descriptive error message when `meteor shell` is run without this package.

It appears to have affected a large number of developers.

**Comment by benjamn** [comment]
@yogiben I would take a pull request for that, though it could be tricky because I wouldn't want to expose information about installed packages over the shell socket connection. Maybe the shell client could read `.meteor/packages` to see if `meteor-shell` is installed?

**Comment by philipbed** [comment]
I have shell-server installed but still get the server unavailable message

![image](https://cloud.githubusercontent.com/assets/9041893/20360717/cea1a68e-ac02-11e6-98dc-72e130b96961.png)

![image](https://cloud.githubusercontent.com/assets/9041893/20360763/fd568d96-ac02-11e6-8878-231fa0257389.png)

**Comment by abernix** [comment]
@philipbed The `meteor shell` command depends on `meteor` running already in another terminal.  Are you running both?

**Comment by philipbed** [comment]
I realized meteor wasn't starting properly because of an error in my server.js file. Once I corrected it everything worked fine. 

Thanks!
