### ISSUE TITLE
static files are cached, preventing altering images without renaming them

### ISSUE THREAD

**Issue by n1mmy** [meteor/meteor#773]
**_1 Upvote**_ In #631 we turned off cache headers for static assets. This let users modify images and other assets without requiring a rename or query parameter to cache-bust.

However, doing this seems to cause image flickering during Spark re-render on multiple browsers. So in 105cb9e67f3083047b408e30f04f0de22ebeb2ca we turned caching back on. It seems to be the lesser of two evils. Flicker is annoying and hard to work around, and comes up for many people.

In order to both serve assets with a caching header and prevent flicker, we may need to rewrite all image URLs with query parameter. Ideally this parameter would be based on the hash of the file, so the cache would only be invalidated when the file changed. These cache busting URLs would need to be substituted both in HTML and CSS to cover common patterns.

The ability to rewrite asset URLs could also be really handy for offloading static assets to a CDN. This could drastically speed page load.

**Comment by leonli** [comment]
no progress or plan on this issue?

**Comment by glasser** [comment]
Correct.

**Comment by jonmbrown** [comment]
You can trick meteor into reloading a new image (that has the same filename as a previous one) just by adding ?xxxx eg myimage.gif?changed. I usually use a date/time stamp if the image changes a lot. eg <img src="image.gif?25MAR2015-2328">

**Comment by hwillson** [comment]
This was addressed by PR #5951. Closing - thanks!
