### ISSUE TITLE
Deployment fail with Meteor 1.4.1

### ISSUE THREAD

**Issue by marcoschwartz** [meteor/meteor#7731]
Hello, I have an app using several NPM modules including Mosca, and since Meteor 1.4 it fails when I try to deploy my app (with Meteor Up and/or Meteor Up Classic). Here is the error:

-----------------------------------STDERR-----------------------------------
	bash: line 5: cd: ./*: No such file or directory
	-----------------------------------STDOUT-----------------------------------
	----------------------------------------------------------------------------

Does anybody knows how to fix this error ? Thanks!

**Comment by indesignlatam** [comment]
Are you using a custom image?

Try adding this line to your kadira:meteor-up config file

````
dockerImage: 'abernix/meteord:base'
````

**Comment by tmeasday** [comment]
This sounds like a mup issue. Please re-open if there's a specific issue w/ Meteor we can look at.
