### ISSUE TITLE
Babel plugin listed in babelrc not used when compiling package

### ISSUE THREAD

**Issue by immertreu** [meteor/meteor#7733]
I'm attempting to use the babel transform-class-properties plugin and am running into an issue. My app consists of a very simple wrapper app that loads its React components from packages. 98% of my code lives in those packages. While I am able to use es7 class properties in that wrapper app, I get an error when I use them in one of my packages.

The contents of babelrc

```
{
  "plugins": ["transform-class-properties"]
}
```

The error:
```
 While building for web.browser:
   packages/digi:urma-tlr/vpn/components/ipsec-new.jsx:53:4: /packages/digi:urma-tlr/vpn/components/ipsec-new.jsx: Missing class properties transform.
```
I'm using version 6.11.5 of babel-plugin-transform-class-properties and Meteor version 1.4.0.1.

**Comment by laosb** [comment]
Can't reproduce that. Could you provide a reproduction?

If this still exists and you have a reproduction, please reopen.
