### ISSUE TITLE
[bug] WebReflection Custom Elements v1 polyfill from NPM breaks app.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7736]
I'm not sure where this bug report belongs, but basically, I have only the following single line of code in my app,

```js
import 'document-register-element'
```

which causes this error:

![screen shot 2016-08-30 at 1 43 29 am](https://cloud.githubusercontent.com/assets/297678/18082411/a825c518-6e53-11e6-9eeb-a16e79e953b5.png)

**Comment by trusktr** [comment]
Reproduction:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7736 --single-branch
cd meteor
./run-dev.sh
```

**Comment by trusktr** [comment]
I also reported it at document-register-element: https://github.com/WebReflection/document-register-element/issues/72

**Comment by WebReflection** [comment]
can anyone tell me if Meteor does some overwrite for native HTML constructors ? I don't understand what even is `HTML.Raw` but for sure it doesn't come from my repository.

If there is some constructor that needs to be better verified or ported to DRE overwrites please let me know and I'll fix it. I just would like to be sure that's the case.

**Comment by trusktr** [comment]
@mitar Opened a new issue at https://github.com/meteor/blaze/issues/95

**Comment by trusktr** [comment]
@mitar Opened a new issue at https://github.com/meteor/blaze/issues/95 because it seems the error is related to Blaze/templating which is in a separate repo (although shipped by default as part of Meteor).
