### ISSUE TITLE
[bug] Importing the WebComponents.js Custom Elements v1 polyfill from NPM breaks app?

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7738]
The only lines in the app are

```js
import 'webcomponents.js/src/CustomElements/v1/native-shim'
import 'webcomponents.js/src/CustomElements/v1/CustomElements'
```

which results in a [familiar yet unhelpful error](https://github.com/meteor/meteor/issues/5551):

```js
   While computing assigned variables:
   node_modules/webcomponents.js/src/CustomElements/v1/native-shim.js: Unexpected token (30:17)
```

Reproduction:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7738 --single-branch
cd meteor
./run-dev.sh
```

Note, I'm getting the webcomponents.js package from GitHub (see package.json).

**Comment by trusktr** [comment]
Reproduction:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7738 --single-branch
cd meteor
./run-dev.sh
```

**Comment by trusktr** [comment]
Opened reciprocal issue in webcomponents: https://github.com/webcomponents/webcomponentsjs/issues/608

**Comment by WebReflection** [comment]
Why is my polyfill mentioned when the example imports `webcomponents.js` which is **not** my polyfill?

Has this bug anything to do at all with my polyfill?

**Comment by WebReflection** [comment]
@trusktr can you please change ASAP this title which blames for no reason my library? thank you

**Comment by WebReflection** [comment]
can anyone please update this ticket, changing the title to start with?

**Comment by trusktr** [comment]
@WebReflection Hi Andrea, I fixed the title. My mistake.

**Comment by trusktr** [comment]
The [error](https://github.com/webcomponents/custom-elements/issues/5) was fixed, and the polyfill has been moved to a new repo, so the following lines now work:

```js
import '@webcomponents/custom-elements/src/native-shim'
import '@webcomponents/custom-elements/src/custom-elements'
```
