### ISSUE TITLE
Meteor error on windows 8.1 

### ISSUE THREAD

**Issue by marcianosr** [meteor/meteor#7740]
Hi,

I'm having issues running meteor on windows. Firstly I got the the following error: 
`C:\Users\Adam\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
throw error;
^
TypeError: Cannot call method 'join' of undefined
at Table._generateQuestionMarks (C:\tools\packaging\catalog\catalog-remote.js:435:57)
at Table._buildStatements (C:\tools\packaging\catalog\catalog-remote.js:425:28)
at new Table (C:\tools\packaging\catalog\catalog-remote.js:418:8)
at RemoteCatalog.initialize (C:\tools\packaging\catalog\catalog-remote.js:696:26)
at C:\tools\cli\main.js:763:20
`

I fixed that by looking at this issue on github: https://github.com/meteor/meteor/issues/7439#issuecomment-238327569

However i'm now getting the next error while building...

```
C:\Users\MarcianoS\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

TypeError: _.findWhere is not a function
    at Object.recordPackages (C:\tools\meteor-services\stats.js:43:9)
    at bundleApp (C:\tools\runners\run-app.js:566:15)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:625:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:884:28)
    at C:\tools\runners\run-app.js:402:12
```

I cant run any meteor project or work on any of them now. I reinstalled meteor a couple of times. Rebooted my computer a couple of times. What is the best thing to do? Maybe downgrade? Has anyone got this error yet?

I'm using meteor 1.4.1 on windows 8.1.

**Comment by Isarstyle** [comment]
#1

**Comment by marcianosr** [comment]
You mean the global node_modules folder (User > node_modules)?  Local folders you mean the 'packages' folder, am I right?
Thanks.

**Comment by marcianosr** [comment]
Ok, removed Meteor entirely, deleting everything inside of the .meteor folder, doesn't seem to work either. Im running meteor 1.4.1.1...

**Comment by marcianosr** [comment]
Allright! Fixed it! Deleted the underscore folder in node_modules and got it working after that!

**Comment by seedgabo** [comment]
can you provide better instructions for this issue, please

**Comment by marcianosr** [comment]
@seedgabo What do you mean, I wrote down the issue in the first post. It is all I know

**Comment by seedgabo** [comment]
nevermind, my antivirus was blocking the installer, and some packages may have corrupted, turn off the antivirus and reinstall works for me.

**Comment by abernix** [comment]
Closing as it seems resolved.  Thanks for the update.
