### ISSUE TITLE
Allow configuring which user fields are published automatically

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7743]
Currently, `username`, `emails`, and `profile` are published automatically. This can be surprising and in my case `profile` is a chunk of HTML so it is quite large and now I discovered that it is always published. Despite me not using it in the old-school Meteor way. I think we should slowly deprecate profile field altogether, and one way to do that is to allow one to configure which fields to be published and make it so that it is not published.

I just need some simple hook to do that. I can then add this to [my package](https://github.com/peerlibrary/meteor-user-extra). Would it be OK to create a simple internal function like `Ap._publicationFields` which returns a list of fields to publish. And then I can override it?

(Preventing writing can be done through deny/allow rules, see #3618.)

**Comment by mitar** [comment]
I made #7744.

**Comment by stubailo** [comment]
Question: why do we even publish any fields automatically? I remember there is some weird stuff with OAuth keys, because of nested fields, but that doesn't seem relevant to this.

Perhaps this should just be an option to disable any automatic publishing when you don't have `autopublish` installed?

Maybe it's a backcompat package called `autopublish-current-user`, which is automatically added on upgrade, and then we just remove that publication entirely?

**Comment by mitar** [comment]
> Maybe it's a backcompat package called autopublish-current-user, which is automatically added on upgrade, and then we just remove that publication entirely?

I like this one the best!

I also do not know why this is published automatically. The issue is that also there is no `ready` on `null` publications, so it is hard to wait on this in templates.

**Comment by stubailo** [comment]
Ok just want to check in with @benjamn and let's get it in the next release.

**Comment by mitar** [comment]
Should I mark this as pull requests encouraged?

**Comment by glasser** [comment]
I believe the historical answer was roughly "we wanted to publish name and email address because we wanted to show that in the UI and figured that was very common; we wanted to publish profile because we thought it would be a useful feature to have a freely-editable-by-the-user field on the user doc and overestimated how self-documenting the name `profile` would be".  In general I think the Meteor design principles in 2012 were much more focused on automatically silently doing potentially useful things than they are now.

**Comment by stubailo** [comment]
@mitar yes please!

**Comment by stubailo** [comment]
I think that package approach is good, let's just do it.

**Comment by stubailo** [comment]
I guess while we are there, we can just call that package something like "legacy-users-defaults" or something and also include https://github.com/meteor/meteor/issues/3618

**Comment by mitar** [comment]
Maybe we can move #7745 into the package as well. :-)

**Comment by glasser** [comment]
I do expect that accounts-ui depends on this, so you may want to add a dependency from it.  (Or at least say that this is a breaking change where accounts-ui really wants you to add this package to your app or do something weirder.)

**Comment by mitar** [comment]
I am not sure anymore if there is a hard dependency. I think the only dependency is now from the extracted Blaze-based configuration tool package (like `facebook-config-ui`). So we might just have to wait for all packages to extract this configuration out, and then depend from them to this new package.

**Comment by glasser** [comment]
I may be far out of date, but my point is that accounts-ui expected to be able to show the current username or email address when you're logged in.

**Comment by mitar** [comment]
Oh, I thought that you are replying to my comment about #7745. Sorry.

You are right about username or email and this package for this issue.

**Comment by benjamn** [comment]
What about whitelisting/filtering the `profile` object to contain just name and email? Wouldn't that reduce the amount of data sent, and also address any security concerns? Still not sure how best to let people opt into that behavior.

**Comment by mitar** [comment]
I think a package would be the best way. A package which publishes those, and you can remove it if you do not want it.

Or, a hook to configure which fields to automatically publish.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20configuring%20which%20user%20fields%20are%20published%20automatically&body=Migrated%20from:%20meteor/meteor%237743) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
