### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7746]
I'm having an issue with a flash of unstyled content (FOUC).

I'm using React, and each component that I develop has a corresponding `styles.scss` file that's imported directly into each file for CSS modules.

When I run my app with `meteor` everything works fine, however if I use `meteor --production` or run a built app in production I'm getting a FOUC which apart from being ugly is actually causing issues on my map page because the style isn't loaded when the map is initialized which gets the client into a broken state.

Any ideas on why this is happening or how I can stop it?

I think it would be a good idea to gather CSS from components and bundle it into a CSS file (or several chunks once code-splitting is in). What were the reasons behind appending each individual stylesheet to head instead of bundling CSS like `Webpack`?

FOUC
![screen shot 2016-09-01 at 12 45 57 pm](https://cloud.githubusercontent.com/assets/2831444/18176076/12a88a52-7042-11e6-8a60-c017d642b9db.png)

Fully-styled
![screen shot 2016-09-01 at 12 44 17 pm](https://cloud.githubusercontent.com/assets/2831444/18176082/1c8ddf68-7042-11e6-9196-f9302bfc7790.png)

**Comment by tmeasday** [comment]
We do bundle the CSS into one file, perhaps it is just not loading in time, and you need to e.g. wait for the `window`'s `load` event to be sure the CSS has loaded if your JS is contingent on it being ready.

**Comment by clayne11** [comment]
I don't think that's true. I import the style directly into my React components which means it doesn't get bundled.

The module code for [`addStyles`](https://github.com/meteor/meteor/blob/devel/packages/modules/css.js) adds the styleshseet for each component separately into the DOM. This is pretty inefficient because:

1) You cannot load the CSS in parallel to the JS.
2) Adding 200-300 stylesheets to the DOM (the number of components that I have) is pretty slow.

I think the behavior in production should be to strip out all the CSS that's imported at the top of files (outside of function scope) and bundle them into a single CSS file.

Additioanlly, I DO wait for the `window` `load` function (using `Meteor.startup()`) before I render my root component so that's not the issue either.

**Comment by tmeasday** [comment]
Apologies, you are right. I guess the `load` event isn't working because the CSS is added dynamically via JS.

I'm not sure what's involved in trying to do static analysis of CSS requirements and adding them to the CSS bundle but it sounds non-trivial.

**Comment by clayne11** [comment]
Webpack handles CSS like that in production.

In development it's kept separate and added to the head as done by Meteor. This enables hot reloading. In production, however, it's much more efficient to bundle it at compile time.

[This](https://github.com/webpack/extract-text-webpack-plugin) is the Webpack plugin that extracts CSS into a bundle.

**Comment by ramezrafla** [comment]
Just an idea, have things hidden and show after a load event or timeout.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Flash%20of%20unstyled%20content&body=Migrated%20from:%20meteor/meteor%237746) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
