### ISSUE TITLE
Install script doesn't check $HOME to see if it exists

### ISSUE THREAD

**Issue by martinb3** [meteor/meteor#7749]
Hello! It seems that the Meteor [install script](https://install.meteor.com/) (release 1.4.1.1) doesn't actually check to be sure `$HOME` exists. When using the install script with tools like [cloud-init](https://cloudinit.readthedocs.io/en/latest/) -- or really with any headless / non-interactive installation, it errors out with:

```
mv: cannot move '/.meteor-install-tmp/.meteor' to '': No such file or directory
```

I think the install script should check for the $HOME variable being defined before using it. This problem was seen on an Ubuntu 14.04 installation on AWS:

```
$ uname -a
Linux ip-172-18-37-171 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by abernix** [comment]
The `$HOME` directory needs to exist for the Meteor tool to work.  If Meteor checks to see if it exists and it doesn't, the best it can do is exit (or create it, but creating a home directory is potentially controversial in and of itself for a variety of reasons).  While I realize this may be the way that your particular `cloud-init` is setting things up, it's simply not true that any headless/non-interactive installation would be missing `$HOME` (it's quite common via non-interactive `ssh`, etc.) but its up to the users shell to decide how to set that.

You'll need to have a directory that exists for Meteor to be installed in and you'll need to have `$HOME` set to that directory.

**Comment by martinb3** [comment]
For what it's worth, it's a very painful install experience when the installer doesn't at least check it's assumptions. I understand your point about `$HOME`, but it would be much more user-friendly and defensive programming to print out an appropriate error message than trying to do file operations with files that don't exist.

**Comment by abernix** [comment]
I don't disagree.  Unfortunately the `install.meteor.com` script isn't in version control for various reasons so shipping a fix for this edge-case is just slightly complicated.  But let's give it a shot...

I would propose something like this:

```sh
if [ -z $HOME1 ] || [ ! -d $HOME1 ]; then
  echo "Installation and use of Meteor requires that the \$HOME environment variable be set to a directory where its files can be installed."
  exit 1
fi
```

...be added right before line 122 (`trap "echo Installation failed." EXIT`) of the http://install.meteor.com script.

Thoughts?

**Comment by martinb3** [comment]
That seems reasonable to me. Thank you!

**Comment by aysark** [comment]
Just ran into this, i was installing meteor on a docker container and docker will have an empty HOME var if you don't specify a user (which most people don't).  Having a correct error message would be a plus.

**Comment by b-long** [comment]
+1 for the comment by @aysark . Definitely want to see first-class Docker support! Thanks MDG!

**Comment by tmeasday** [comment]
Thanks @abernix, I just deployed this change to the package server.
