### ISSUE TITLE
Downloading templating@1.1.14... stuck - again -- my solution

### ISSUE THREAD

**Issue by MalcolmGC** [meteor/meteor#7750]
The issue of Downloading templating@1.1.14... stuck was raised recently and the trail of dialog went on and on. 
This is what worked for me: > meteor add templating
I got this from:  https://atmospherejs.com/meteor/templating.
Hope this helps others. 
PS -  the meteor-tools issue is different and I have posted that resolution at: 
https://github.com/meteor/meteor/issues/6960
 https: //github.com/meteor/meteor/issues/6960

**Comment by stubailo** [comment]
Thanks for the suggestion - I think it would be best to post this on the issue thread where people were experiencing that issue.
