### ISSUE TITLE
Meteor app in android reloads first screen when launching

### ISSUE THREAD

**Issue by rubenlpz** [meteor/meteor#7752]
When launching meteor app on android device, the first screen is shown succesfully but after 4 seconds it is reloaded.   According to @martijnwalraven it happen when the ROOT_URL is not properly set in remote server hosting, but I'm sure I have set this variable in my server (Heroku).   It seems meteor still looking for localhost until server version refresh the first page.

**Comment by laosb** [comment]
Could you provide a *full reproduction* as was explained in Contributing.md? It's hard for us to reproduce your issue without a reproduction.

* For your reference:*

> A Meteor app has many moving parts, and it's often difficult to
> reproduce a bug based on just a few lines of code.  So your report
> should include a reproduction recipe.  By making it as easy as possible
> for others to reproduce your bug, you make it easier for your bug to be
> fixed. **It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.**
> 
> **A single code snippet is _not_ a reproduction recipe and neither is an entire application.**
> 
> A reproduction recipe works like this:
> 
>  * Create a new Meteor app that displays the bug with as little code as
>    possible. Try to delete any code that is unrelated to the precise bug
>    you're reporting, including extraneous Atmosphere packages.  Ideally, try to use
>    as few source files as possible so that it's easy to see the whole reproduction
>    on one screen, rather than making a large number of small files, even if that's
>    not how you'd choose to structure an app.
> 
>  * Create a new GitHub repository with a name like
>    `meteor-reactivity-bug` (or if you're adding a new reproduction
>    recipe to an existing issue, `meteor-issue-321`) and push your code
>    to it. (Make sure to include the `.meteor/packages` and `.meteor/release` files!)
> 
>  * Reproduce the bug from scratch, starting with a `git clone`
>    command. Copy and paste the entire command-line input and output,
>    starting with the `git clone` command, into the issue description of
>    a new GitHub issue. Also describe any web browser interaction you
>    need to do.
> 
>  * If you reproduced the issue using a checkout of Meteor instead of using
>    a released version that was pinned with a `.meteor/release` file,
>    specify what commit in the Meteor repository was checked out.
> 
>  * Mention what operating system you're using and what browser (if any).
>

**Comment by abernix** [comment]
Unfortunately, as stated above, you haven't provided enough information to help reproduce this problem.  Please report back if you continue to have this issue and help us help you by providing the information requested above.  Closing due to lack of response.
