### ISSUE TITLE
Can't start app : Missing file "/tmp/mt-d7ms31/web.browser.json"

### ISSUE THREAD

**Issue by craissQ** [meteor/meteor#7755]
Hi everyone,

I'm new in meteor, intern in a startup. I apologize in advance for my English which is not perfect.
This morning, i cloned the app (version 1.4.0.1) .
To migrate to 1.4.1.1, I followed this advice: "If meteor update takes a very long time for you (more than ten minutes), your best option may be to reinstall Meteor from scratch, so that you can avoid having to run meteor update."
I found it on this link: http://info.meteor.com/blog/announcing-meteor-1.4.1
Then, i wanted to launch the app and this error occurred :

```
--------
[[[[[ ~/my_app ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
/home/quentin/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-d7ms31/web.browser.json'
    at Error (native)
--------
```

I tried all the following solutions without success:

-uninstall meteor (usr & su)
  sudo rm /usr/local/bin/meteor
  rm -rf ~/.meteor

-install meteor with su / whitout su

-my teammate upgraded the app to 1.4.1.1

For each step, I deleted the local app and cloned again. The file is always missing.
When I create a brand new meteor app, everything works perfectly on 1.4.1.1, but the same bug appears in 1.4.0.1.
During this manipulations, I also had problems with EACCES but I solved it by starting all over again with only non-root user actions, after I did that :
- Remove the ~/.meteor and /root/.meteor folders
- Remove the project/.meteor/local folder and the symlink at project/.meteor/dev_bundle (where project is your project directory)
- Make sure that the ownership of everything in the project/ folder is to the current user (chown -R ./ <username>)
- Run Meteo

Is anyone aware of that bug ? What does it means ?
Thanks you.

**Comment by stubailo** [comment]
What does it say in the apps `.meteor/release` file?

**Comment by Taberu** [comment]
I have the same issue and I have lost a week searching for a solution to this!
Even I tried to only use 1.4.1 but the same issue appear, reseting the project, cloning into a fresh one but it doesn't allow me to add new packages.
My version release is METEOR@1.4.1.1.
I need this solve asap. Sorry for being straight forward!

**Comment by stubailo** [comment]
Do you have a `PACKAGE_DIRS` defined or anything like that?

**Comment by Taberu** [comment]
I tried "meteor run" but it always thrown error. Then I found out that adding a new package using "meteor add" it thrown error again, it happens when a package with dependencies is installed first, it crashed. Then I added the dependencies first and it worked.

For new packages, meteor run is not working properly, this issue can be bypassed using meteor add... Now my project is working.

**Comment by laosb** [comment]
I had this issue when use `meteor --release 1.3`, after it downloads and extracts the 1.3.

**Comment by thiagoribeir015** [comment]
My meteor project was developed based on meteor@1.4.0. After rebuilding my workspace I  installed Meteor repos latest version (1.4.1).

So, when I executed 'meteor run', the same error described by **craissQ** happened.

When Meteor tried to build the project it was looking for the 1.4.0 version, and even reverting my local Meteor version to 1.4.0 solved the problem.

So, after all, I've simply changed the project version ($projectFolder/.meteor/release) to the latest version (METEOR@1.4.1.1) and now is working like a charm \o/

**Comment by abernix** [comment]
Thanks for reporting this.  I'm closing as I'm almost positive this is the same as #7806 and was due to an incomplete package being downloaded from a failing CDN server.  If you're still experiencing this, please update to Meteor 1.4.1.3 or higher as the downloading process has been improved (and the CDN server, resolved).

Happy to reopen if you're still experiencing the problem though!
