### ISSUE TITLE
Support for Facebook AccountKit Login 

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#7757]
In addition to the traditional signup/login options available in Accounts, it would be great to have  the new Facebook phone number based login: https://developers.facebook.com/docs/accountkit

Unfortunately, as stated in the FAQ (https://developers.facebook.com/docs/accountkit/faq):
 "The JavaScript SDK doesn't support WebView login, so you can't login people from a WebView with Account Kit."

So, is there any possibility to enable Meteor apps (running on iOS/Android, i.e. in the webview, because when running on the browser there's no problem) to use this new login option?

Thank you in advance to anyone who could provide useful insights/solutions.

**Comment by abernix** [comment]
I would encourage those who are interested in this feature to do some research about its feasibility and determine if its possible to implement it as a third-party package.  My intuition is telling me that it could be and therefore it would not be a candidate for Meteor Core.

I'll leave this open for the time-being, but please read the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).  If it's determined that this can be made a package (or more specifically, if it's not proven that some Meteor core API is necessary to make this happen), this issue will be closed.

**Comment by shyjal** [comment]
@davidecantini Did you tried implementing account kit for meteor web app. I am currently facing few issues with accountkit js sdk on meteor client side.

**Comment by davidecantini** [comment]
@shyjal Yes, I gave it a quick try and, unfortunately, the result seems to confirm what's stated in their FAQ ("The JavaScript SDK doesn't support WebView login, so you can't login people from a WebView with Account Kit.")

**Comment by shyjal** [comment]
@davidecantini That's about usage inside a webview rite. Im taking about an web app that works in desktop.

**Comment by davidecantini** [comment]
@shyjal From the browser it is supposed to work, but I can't confirm that because in my case I was  testing for mobile apps.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20for%20Facebook%20AccountKit%20Login%20&body=Migrated%20from:%20meteor/meteor%237757) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
