### ISSUE TITLE
Meteor is auto-publishing all the subscriptions without autopublish

### ISSUE THREAD

**Issue by THPubs** [meteor/meteor#7759]
Guys, I just realized that my app is publishing all the publications to the client even without a subscription and the autopublish package. Any idea why this is happening?

**Comment by robfallows** [comment]
You'll need to provide a minimal reproduction.

**Comment by THPubs** [comment]
@robfallows Just cloned the app in another machine and tried. In there it didn't publish all my collections. I was unable to re-produce it. I just reset my project and the auto publishing stopped. After that I re-stored the old database (which I backed up before resetting). Now again it's publishing everything.

**Comment by robfallows** [comment]
This sounds like an issue with database versions/driver versions.

There was an issue in 1.4.1 (but not to do with publish IIRC). 1.4.1.1 fixes that and may be worth trying if you're not already at that version.

**Comment by THPubs** [comment]
@robfallows Actually the app is already on `1.4.1.1` :smile:

**Comment by lucfranken** [comment]
Can you show your publish calls?

**Comment by robfallows** [comment]
@THPubs : I'm trying to reproduce with an old database (pre 3.2) running with the new driver, but I need to know what the DB version was before you updated to Meteor 1.4. The original Meteor version you were using would be useful.

**Comment by THPubs** [comment]
@robfallows It was `1.4.1` :-)

**Comment by laosb** [comment]
Could you provide a *full reproduction* as was explained in Contributing.md? It's hard for us to reproduce your issue without a reproduction.

*For your reference:*

> A Meteor app has many moving parts, and it's often difficult to
> reproduce a bug based on just a few lines of code.  So your report
> should include a reproduction recipe.  By making it as easy as possible
> for others to reproduce your bug, you make it easier for your bug to be
> fixed. **It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.**
> 
> **A single code snippet is _not_ a reproduction recipe and neither is an entire application.**
> 
> A reproduction recipe works like this:
> 
>  * Create a new Meteor app that displays the bug with as little code as
>    possible. Try to delete any code that is unrelated to the precise bug
>    you're reporting, including extraneous Atmosphere packages.  Ideally, try to use
>    as few source files as possible so that it's easy to see the whole reproduction
>    on one screen, rather than making a large number of small files, even if that's
>    not how you'd choose to structure an app.
> 
>  * Create a new GitHub repository with a name like
>    `meteor-reactivity-bug` (or if you're adding a new reproduction
>    recipe to an existing issue, `meteor-issue-321`) and push your code
>    to it. (Make sure to include the `.meteor/packages` and `.meteor/release` files!)
> 
>  * Reproduce the bug from scratch, starting with a `git clone`
>    command. Copy and paste the entire command-line input and output,
>    starting with the `git clone` command, into the issue description of
>    a new GitHub issue. Also describe any web browser interaction you
>    need to do.
> 
>  * If you reproduced the issue using a checkout of Meteor instead of using
>    a released version that was pinned with a `.meteor/release` file,
>    specify what commit in the Meteor repository was checked out.
> 
>  * Mention what operating system you're using and what browser (if any).
>

**Comment by THPubs** [comment]
Looks like i was unable to reproduce it. After resetting the app it worked. So I'm going to close the issue :smile:

**Comment by szimmers** [comment]
this just happened to me. same symptoms, same behavior w/ dumping and restoring the database.

this is terrifying. what if this were to happen in production? the entire users table is being auto-published to the client even when i'm not logged in.

what we need is to understand WTF is going on, so if it happens in production, we can flip some bit in the database and fix it immediately. obviously, a 'meteor reset' is not a viable production fix.

**Comment by szimmers** [comment]
ok i figured it out.

it has to do with this Chrome plugin:

https://github.com/thebakeryio/meteor-ddp-monitor

it has a tab called Security. Under there is Collections. For each collection, you can hit a button called "Audit collection".

if you do that for the collection "MeteorToys.AutoPub", it adds a collection of that same name to your db. suddenly, autopublish is enabled.

to confirm, i successfully restored my old db, deleted the MeteorToys.AutoPub collection, and everything is back to normal. crisis averted.

**Comment by stefanve** [comment]
I have this problem as well. Still trying to debug it, but it is a concern. I have not added any monitor manually anyway

**Comment by stefanve** [comment]
Meteor reset cured the problem, but what caused it? I imported the same database as the one I had while experienced the error

**Comment by derwaldgeist** [comment]
This issue is making me nervous...

@szimmers Thanks for pointing me to the DDP monitor, I did not know this cool thing.

**Comment by abernix** [comment]
@derwaldgeist You shouldn't be nervous unless you have a reproduction of this problem. Do you use MeteorToys?  @szimmers Seems to be saying that a combination of this DDP monitor and MeteorToys could be responsible for causing this problem, though I'm inclined to believe it might be achievable with MeteorToys and its own configuration options as well since Meteor Toys does possess the ability to forcibly turn on auto-publish as well (without the `autopublish` package).

I guess it should be pointed out that since MeteorToys is a `devOnly` package, this would never affect a production application.

**Comment by stefanve** [comment]
I do not have MeteorToys and I have the problem in production, deployed with mupx. I disappeared for me locally after meteor reset but came back when I restored the old database. I tried to remove all but the official packages, one by one, but problem persisted

**Comment by abernix** [comment]
@stefanve If it came back after you restored your old database, please do figure out what it is in your database that's causing this to happen!  Obviously without this, it's difficult to say.  I can assure you that this is not typical (though I would also recommend you update your Meteor to a new version!)

**Comment by stefanve** [comment]
This happened when I updated Meteor to the latest version. I had to throw away that project but if I get time one day I might look at it again. The db was just two collections, nothing fancy
