### ISSUE TITLE
IE8 default app fails with meteor version 1.4?

### ISSUE THREAD

**Issue by tsgoak** [meteor/meteor#7761]
I tried the default app created with "meteor create test1" with Meteor 1.4.  It has similar "Expected Identifier" error as #5484 with IE8 in modules.js, line 249.
if (typeof Mp.import === "function" && // 7
typeof Mp.export === "function") {

**Comment by abernix** [comment]
Per the [official deprecation notice by Microsoft](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), Internet Explorer 8 has reached it's official end-of-life.  While I recognize this might cause problems and chagrin for some, especially those in certain industries, I find it unlikely any steps will be taken by Meteor Core to resolve this.

If there are particular and specific issues with clear and simple resolutions that can be made to maintain compatibility, feel free to open issues and PRs as appropriate, but "not compatible" issues for deprecated software aren't going to do much good sitting here.  Closing.
