### ISSUE TITLE
Error while running meteor update

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#7764]
Just ran sudo meteor update and am getintg this error (?)

/home/tidee/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
undefined

**Comment by tmeasday** [comment]
Is that the whole error?

**Comment by joetidee** [comment]
At one point it was saying the disk was full (when it wasn't) and other times it was saying undefined. Anyhow, I have blatted Meteor and am starting again.
