### ISSUE TITLE
Allow default CSS compiler to be overridden or removed

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#7765]
Currently Meteor has a hard-coded CSS compiler, which prevents developers from creating their own compiler plugins to handle `.css` files. My initial proposal is to handle `.css` files like Meteor handles `.js` files - if there is no user-installed compiler, use the default (all it does is pass through the CSS file contents unchanged).
I'd be happy to implement this so I can do away with the hack I'm currently using to make my CSS Modules plugin work.

**Comment by laosb** [comment]
Sounds a good idea, but further discussions are required before the code.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20default%20CSS%20compiler%20to%20be%20overridden%20or%20removed&body=Migrated%20from:%20meteor/meteor%237765) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
