### ISSUE TITLE
Bootstrap error being thrown after upgrading to Meteor 1.4

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#7767]
Just upgraded to Meteor 1.4. My application uses Bootstrap 3.3.6. Now the browser console is throwing the error:

> bootstrap.js:16 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

So, I traced this back to the bootstrap.js file (line 16) and the code that detects the version of jQuery:

```
+function ($) {
  'use strict';
  var version = $.fn.jquery.split(' ')[0].split('.');
  console.log(version);
  if ((version[0] < 2 && version[1] < 9) || (version[0] == 1 && version[1] == 9 && version[2] < 1) || (version[0] > 2)) {
    throw new Error('Bootstrap\'s JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3')
  }
}(jQuery);
```

When printing out `version`, it says 3.1.0 - which makes sense as to why the error is being thrown. HOWEVER, when I view the page source the jQuery that is being loaded by Meteor is 1.11.2 !
IF I THEN run `meteor list` in the OS console it tells me that 1.11.9 is included !

What's going on? :)

**Comment by laosb** [comment]
Just install your own jquery by npm. Meteor should pick your installed version of jquery. Anyway, the version of `jquery` package is not corresponding to the version of jquery it actually used.

**Comment by laosb** [comment]
I think it's better to discuss this on [forums](https://forums.meteor.com).

**Comment by idl-asad** [comment]
@joetidee  reset the jquery version in package.json file in root directory of your meteor 1.4 project, it solved my same issue.
