### ISSUE TITLE
[Upgrading from Meteor 1.3 to 1.4.1] URIError: URI malformed caused by improper MONGO_URL parse

### ISSUE THREAD

**Issue by tmpg** [meteor/meteor#7768]
**Stack Trace**

```
(STDERR) /home/linuxbox/.meteor/packages/meteor-tool/.1.4.1.45m808++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
(STDERR) throw(ex);
(STDERR) ^
(STDERR)
(STDERR) URIError: URI malformed
(STDERR) at decodeURIComponent (native)
(STDERR) at module.exports (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/url_parser.js:144:15)
(STDERR) at connect (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:266:16)
(STDERR) at Function.MongoClient.connect (/home/linuxbox/.meteor/packages/npm-mongo/.1.5.46.1lr66o8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongo_client.js:113:3)
(STDERR) at new MongoConnection (packages/mongo/mongo_driver.js:174:11)
(STDERR) at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
(STDERR) at Object. (packages/mongo/remote_collection_driver.js:38:10)
(STDERR) at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
(STDERR) at new Mongo.Collection (packages/mongo/collection.js:103:40)
(STDERR) at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
```

This issue was caused by the inability of meteor to properly parse (possibly due to escapes) the MONGO_URL ENVIRONMENTAL VARIABLE.

Example:
This worked fine in Meteor 1.3:
MONGO_URL=mongodb://admin:fakepassword#$%@fake.mlab.com:99999/dev meteor --port 5005 --settings settings.json

When upgrading to meteor 1.4 this no longer worked due to the symbols (#$%) causing the meteor app to think that this URI was malformed. When those symbols were not part of the password Meteor 1.4 worked fine.

**Comment by laosb** [comment]
I don't think this is a Meteor bug, since this error was thrown by `mongodb`, the official mongo driver.

**Comment by SNY7** [comment]
mongodb driver uses decodeURIComponent function, tested in javascript, it's throw that error.

decodeURIComponent('mongodb://admin:fakepassword#$%@fake.mlab.com:99999/dev')
> Uncaught URIError: URI malformed

**Comment by laosb** [comment]
Did a little research, found [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). You may need to do a `encodeURIComponent()` to ensure that your URI is in a correct form.

**Comment by tmpg** [comment]
The URI was and is in correct form as it held a valid password for mongo while following the proper specification (as this password worked without the following characters #$%, respectably). The whole reason that is this an issue is that the user should not have to modify their password with escapes or use `encodeURIComponent()`  in order for the URI to be valid. That should be done for the user.

**Comment by laosb** [comment]
I mean, special characters was not in their correct forms. It should follow the specification while we do like to simplify something. In fact, AFAIK most people use a randomly-generated user/pass pair for their production mongo provided by their PaaS/CaaS.

Maybe we just need to update the docs with a notice that `MONGO_URL` is required to be escaped. I guess most people would do escape since this specification is applied not only to `MONGO_URL`s, but also other kind of service URLs that may have special characters in the URL.

**Comment by tmpg** [comment]
Please do not make sweeping assumptions.

**Comment by laosb** [comment]
It's really a breaking change for someone, and we should give them some hints about doing escaping. But I don't think we should do escaping for them since we're actually doing what the specification specified.

**Comment by laosb** [comment]
IMO we should just note down this breaking change(but still minor change, even not by Meteor itself) somewhere.

**Comment by laosb** [comment]
So I'm leaving this open -- if someone hit this too, we may consider it again.

**Comment by abernix** [comment]
See related Meteor issue #7713.  Looking back through the MongoDB API versions it doesn't appear their API, nor the connection string specification has changed in any way that would have broke this – though the error is coming from Mongo's URL parser.

It appears to be a shortcoming of [the connection string specification](https://github.com/mongodb/specifications/blob/dac7d816ec7f2a6f8ba8fba2c1b10ac8d110c4c2/source/connection-string/connection-string-spec.rst#userinfo-optional) though, as it's not really clear (see @mjgallag's proposed change in open PR mongodb/specifications#1050).

Also, based on [this code](https://github.com/mongodb/node-mongodb-native/blob/64d53ee38389f903d0d418ad5a307807b41387fb/lib/mongo_client.js#L290) in the Mongo Node Driver, I'm not entirely sure why it would have ever worked as the [`uri_decode_auth` option from the docs](https://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html) doesn't seem to [get used](https://github.com/mongodb/node-mongodb-native/search?utf8=%E2%9C%93&q=uri_decode_auth) or be [obeyed in the parser](https://github.com/mongodb/node-mongodb-native/blob/64d53ee38389f903d0d418ad5a307807b41387fb/lib/url_parser.js#L141-L145).

Haven't had a chance to trace this through Meteor, but something fishy does seem to be occurring.

**Comment by laosb** [comment]
Yes, yesterday I found that it seems `uri_decode_auth` wasn't even used and actually it's true (if we need to say) by default.

**Comment by Pushplaybang** [comment]
just running into this now (I think).  Do I just need to use a password without special chars?

**Comment by tmpg** [comment]
Yes, when this happened it threw me off for a bit. Just change the password to not include special characters and you'll be golden.

**Comment by hwillson** [comment]
We're going to document special character handling with `MONGO_*_URL` - see https://github.com/meteor/docs/issues/177. Closing here - thanks!
