### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by tkiddle** [meteor/meteor#7770]
N/A

**Comment by abernix** [comment]
I recall speaking specifically to someone about this issue on IRC around the exact same time that this was opened – not sure if it was you or not.  Regardless, you seem to have removed your issue at this point.  Next time, or if you still have concerns with this matter, please consider submitting your findings per the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).  Happy to discuss via the forums as well where you can find me under the same username.
