### ISSUE TITLE
Roadmap doesn't show progress

### ISSUE THREAD

**Issue by phest** [meteor/meteor#7777]
The roadmap [1] [2] doesn't show what's already been released (eg MongoDB updates and Support for Node 4 added a while ago in 1.4).

As a suggestion, including a list with checkboxes (as used in the [VS Code roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap), although in the Docker/Meteor roadmap style it would probably be a higher level list) would make it easy to update and see the progress.

[1] [roadmap devel version](https://github.com/meteor/meteor/blob/devel/Roadmap.md)
[2] [roadmap version as of this writing](https://github.com/meteor/meteor/blob/67100f7207a38d6ec66cbadc761bd158055009c6/Roadmap.md)

**Comment by laosb** [comment]
I think so. And it wasn't updated frequently.

PS: You've claimed issue #7777!

**Comment by laosb** [comment]
Note that the newly-released "Projects" view on GitHub might be a good choice for Roadmap.

**Comment by phest** [comment]
Gentle bump. As someone wanting to keep an eye on Meteor for upcoming projects, it would be useful to have a high level document of the current state and future of Meteor.

**Comment by abernix** [comment]
This hasn't been forgotten! ;)

**Comment by abernix** [comment]
Updated via #8153 thanks to @stubailo and company!

**Comment by stubailo** [comment]
Check the relevant forum post: https://forums.meteor.com/t/meteor-roadmap-update-12-13-16/32261

Important bit is that we're going to try to update regularly.
