### ISSUE TITLE
Accounts-base: need to be able to set MIN_TOKEN_LIFETIME_CAP_SECS

### ISSUE THREAD

**Issue by mattiLeBlanc** [meteor/meteor#7779]
Hi,

We are using Auth0 for our user management and have implemented this using `Accounts.registerLoginHandler`.
The problem I am looking at is that we want strict session rules. When a person closes his browser we want to log them out. Unfortunately Meteor set its expiryToken to 90 days default and min value is 1 day. I figured out I can manually override the localeStorage `Meteor.loginTokenExpires` to set it to a shorter value.

However, anything shorter then 1 hour of expiry is causing a direct logout.
This is because of constant `MIN_TOKEN_LIFETIME_CAP_SECS` (accounts_common.js) which is set to 3600 seconds (1 hour).

What I want to achieve is practically a session cookie effect. For that to work, I have to be able to set the MIN_TOKEN_LIFETIME_CAP_SECS to for example 10 seconds. 

We have an inactivity service which will count down and log out after 15 minutes. On any user input the timer will reset it self.
At that time I will set the `Meteor.loginTokenExpires` to 10 seconds in the future which will allow someone to do a hard refresh of the page without being logged out. And when someone moves the mouse the tokenExpire is updated again.
The result of this will be that when the close the browser they are automatically logged out, which is what I want to achieve.

For this to work, I need be to be able to set the MIN_TOKEN_LIFETIME_CAP_SECS to a desired number.
I am happy to fork and make a pull request so that it is configurable.
Any thoughts?

**Comment by abernix** [comment]
Sorry for the delay in getting to this!  I was hoping someone else with more `accounts-*` experience might have input on this as I'm not sure I understand the implications of accepting a pull request which would raise (or allow raising) this minimum value.  I agree that a full hour definitely seems long for a minimum.

As a work around, could you simply modify the `AccountsCommon` constructor to provide your own `_tokenExpiresSoon` method?  Something along the lines of:

```js
AccountsServer.prototype._tokenExpiresSoon = function (when) { // your logic }
```

**Comment by mattiLeBlanc** [comment]
Well what I actually did was ad 10 seconds to the hour. Since Meteor logs out when the token expiry reaches 1 hour, changing it to 1 hour and 10 seconds has the same effect as setting it to 10 seconds when expiry minimum would be 0.

Feels a bit like a creative hack but it does the job.

**Comment by darkyen** [comment]
That does seem like a hack. I'm curious though why did you take the Accounts.registerLoginHandler over using Auth0 as OAuth2.0 server?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Accounts-base%3A%20need%20to%20be%20able%20to%20set%20MIN_TOKEN_LIFETIME_CAP_SECS&body=Migrated%20from:%20meteor/meteor%237779) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
