### ISSUE TITLE
1.4.1.1 Upgrade, App crashes if no internet connection, otherwise builds

### ISSUE THREAD

**Issue by roh0987** [meteor/meteor#7782]
I recently upgrading app to 1.4.1.1. The app works fine if connected to internet. But if disconnected the app crashes with following errors. Tried updating all packages, no use...

> c:\myApp>meteor
> [[[[[ c:\myApp ]]]]]
> 
> => Started proxy.
> 
> W20160917-08:41:47.185(5.5)? (STDERR)
> W20160917-08:41:47.245(5.5)? (STDERR) c:\myApp\node_modules\fibers\future.js:313
> 
> W20160917-08:41:47.246(5.5)? (STDERR)
> throw(ex);
> W20160917-08:41:47.247(5.5)? (STDERR)
> ^
> W20160917-08:41:47.249(5.5)? (STDERR) MongoError: failed to connect to server [l
> ocalhost:27017] on first connect
> W20160917-08:41:47.250(5.5)? (STDERR) at Object.Future.wait (c:\myApp\node_m
> odules\fibers\future.js:449:15)
> W20160917-08:41:47.251(5.5)? (STDERR) at new MongoConnection (packages/mongo
> /mongo_driver.js:216:27)
> W20160917-08:41:47.253(5.5)? (STDERR) at new MongoInternals.RemoteCollection
> Driver (packages/mongo/remote_collection_driver.js:4:16)
> W20160917-08:41:47.255(5.5)? (STDERR) at Object. (packages/mongo/
> remote_collection_driver.js:38:10)
> W20160917-08:41:47.256(5.5)? (STDERR) at Object.defaultRemoteCollectionDrive
> r (packages/underscore/underscore.js:750:1)
> W20160917-08:41:47.258(5.5)? (STDERR) at new Mongo.Collection (packages/mong
> o/collection.js:103:40)
> W20160917-08:41:47.259(5.5)? (STDERR) at meteorInstall.imports.api.sessions-
> api.js (imports/api/sessions-api.js:4:14)
> W20160917-08:41:47.261(5.5)? (STDERR) at fileEvaluate (packages/modules-runt
> ime/.npm/package/node_modules/install/install.js:153:1)
> W20160917-08:41:47.263(5.5)? (STDERR) at Module.require (packages/modules-ru
> ntime/.npm/package/node_modules/install/install.js:82:1)
> W20160917-08:41:47.264(5.5)? (STDERR) at Module.Mp.import (AppData\Local.meteor\packages\modules\0.7.6\npm\node_modules\reify\lib\runtime.js
> :70:16)
> W20160917-08:41:47.265(5.5)? (STDERR) - - - - -
> W20160917-08:41:47.267(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\topologies\server.js:313:35)
> W20160917-08:41:47.268(5.5)? (STDERR) at emitOne (events.js:77:13)
> W20160917-08:41:47.270(5.5)? (STDERR) at [object Object].emit (events.js:169
> :7)
> W20160917-08:41:47.272(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\connection\pool.js:260:12)
> W20160917-08:41:47.273(5.5)? (STDERR) at [object Object].g (events.js:260:16
> )
> W20160917-08:41:47.275(5.5)? (STDERR) at emitTwo (events.js:87:13)
> W20160917-08:41:47.276(5.5)? (STDERR) at [object Object].emit (events.js:172
> :7)
> W20160917-08:41:47.277(5.5)? (STDERR) at Socket. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongodb-core\li
> b\connection\connection.js:162:49)
> W20160917-08:41:47.279(5.5)? (STDERR) at Socket.g (events.js:260:16)
> W20160917-08:41:47.280(5.5)? (STDERR) at emitOne (events.js:77:13)
> => Exited with code: 1
> W20160917-08:41:57.238(5.5)? (STDERR)
> W20160917-08:41:57.239(5.5)? (STDERR) c:\myApp\node_modules\fibers\future.js:313
> 
> W20160917-08:41:57.240(5.5)? (STDERR)
> throw(ex);
> W20160917-08:41:57.241(5.5)? (STDERR)
> ^
> W20160917-08:41:57.242(5.5)? (STDERR) MongoError: failed to connect to server [l
> ocalhost:27017] on first connect
> W20160917-08:41:57.244(5.5)? (STDERR) at Object.Future.wait (c:\myApp\node_m
> odules\fibers\future.js:449:15)
> W20160917-08:41:57.247(5.5)? (STDERR) at new MongoConnection (packages/mongo
> /mongo_driver.js:216:27)
> W20160917-08:41:57.249(5.5)? (STDERR) at new MongoInternals.RemoteCollection
> Driver (packages/mongo/remote_collection_driver.js:4:16)
> W20160917-08:41:57.251(5.5)? (STDERR) at Object. (packages/mongo/
> remote_collection_driver.js:38:10)
> W20160917-08:41:57.253(5.5)? (STDERR) at Object.defaultRemoteCollectionDrive
> r (packages/underscore/underscore.js:750:1)
> W20160917-08:41:57.254(5.5)? (STDERR) at new Mongo.Collection (packages/mong
> o/collection.js:103:40)
> W20160917-08:41:57.256(5.5)? (STDERR) at meteorInstall.imports.api.sessions-
> api.js (imports/api/sessions-api.js:4:14)
> W20160917-08:41:57.257(5.5)? (STDERR) at fileEvaluate (packages/modules-runt
> ime/.npm/package/node_modules/install/install.js:153:1)
> W20160917-08:41:57.258(5.5)? (STDERR) at Module.require (packages/modules-ru
> ntime/.npm/package/node_modules/install/install.js:82:1)
> W20160917-08:41:57.260(5.5)? (STDERR) at Module.Mp.import (AppData\Local.meteor\packages\modules\0.7.6\npm\node_modules\reify\lib\runtime.js
> :70:16)
> W20160917-08:41:57.262(5.5)? (STDERR) - - - - -
> W20160917-08:41:57.263(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\topologies\server.js:313:35)
> W20160917-08:41:57.264(5.5)? (STDERR) at emitOne (events.js:77:13)
> W20160917-08:41:57.265(5.5)? (STDERR) at [object Object].emit (events.js:169
> :7)
> W20160917-08:41:57.266(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\connection\pool.js:260:12)
> W20160917-08:41:57.267(5.5)? (STDERR) at [object Object].g (events.js:260:16
> )
> W20160917-08:41:57.268(5.5)? (STDERR) at emitTwo (events.js:87:13)
> W20160917-08:41:57.269(5.5)? (STDERR) at [object Object].emit (events.js:172
> :7)
> W20160917-08:41:57.270(5.5)? (STDERR) at Socket. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongodb-core\li
> b\connection\connection.js:162:49)
> W20160917-08:41:57.271(5.5)? (STDERR) at Socket.g (events.js:260:16)
> W20160917-08:41:57.271(5.5)? (STDERR) at emitOne (events.js:77:13)
> => Exited with code: 1
> W20160917-08:42:06.257(5.5)? (STDERR)
> W20160917-08:42:06.258(5.5)? (STDERR) c:\myApp\node_modules\fibers\future.js:313
> 
> W20160917-08:42:06.260(5.5)? (STDERR)
> throw(ex);
> W20160917-08:42:06.261(5.5)? (STDERR)
> ^
> W20160917-08:42:06.262(5.5)? (STDERR) MongoError: failed to connect to server [l
> ocalhost:27017] on first connect
> W20160917-08:42:06.263(5.5)? (STDERR) at Object.Future.wait (c:\myApp\node_m
> odules\fibers\future.js:449:15)
> W20160917-08:42:06.264(5.5)? (STDERR) at new MongoConnection (packages/mongo
> /mongo_driver.js:216:27)
> W20160917-08:42:06.266(5.5)? (STDERR) at new MongoInternals.RemoteCollection
> Driver (packages/mongo/remote_collection_driver.js:4:16)
> W20160917-08:42:06.267(5.5)? (STDERR) at Object. (packages/mongo/
> remote_collection_driver.js:38:10)
> W20160917-08:42:06.269(5.5)? (STDERR) at Object.defaultRemoteCollectionDrive
> r (packages/underscore/underscore.js:750:1)
> W20160917-08:42:06.270(5.5)? (STDERR) at new Mongo.Collection (packages/mong
> o/collection.js:103:40)
> W20160917-08:42:06.273(5.5)? (STDERR) at meteorInstall.imports.api.sessions-
> api.js (imports/api/sessions-api.js:4:14)
> W20160917-08:42:06.274(5.5)? (STDERR) at fileEvaluate (packages/modules-runt
> ime/.npm/package/node_modules/install/install.js:153:1)
> W20160917-08:42:06.277(5.5)? (STDERR) at Module.require (packages/modules-ru
> ntime/.npm/package/node_modules/install/install.js:82:1)
> W20160917-08:42:06.279(5.5)? (STDERR) at Module.Mp.import (C:\Users\Gagan\Ap
> pData\Local.meteor\packages\modules\0.7.6\npm\node_modules\reify\lib\runtime.js
> :70:16)
> W20160917-08:42:06.281(5.5)? (STDERR) - - - - -
> W20160917-08:42:06.282(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\topologies\server.js:313:35)
> W20160917-08:42:06.283(5.5)? (STDERR) at emitOne (events.js:77:13)
> W20160917-08:42:06.284(5.5)? (STDERR) at [object Object].emit (events.js:169
> :7)
> W20160917-08:42:06.284(5.5)? (STDERR) at [object Object]. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongod
> b-core\lib\connection\pool.js:260:12)
> W20160917-08:42:06.285(5.5)? (STDERR) at [object Object].g (events.js:260:16
> )
> W20160917-08:42:06.286(5.5)? (STDERR) at emitTwo (events.js:87:13)
> W20160917-08:42:06.287(5.5)? (STDERR) at [object Object].emit (events.js:172
> :7)
> W20160917-08:42:06.288(5.5)? (STDERR) at Socket. (AppData\Local.meteor\packages\npm-mongo\1.5.49\npm\node_modules\mongodb-core\li
> b\connection\connection.js:162:49)
> W20160917-08:42:06.289(5.5)? (STDERR) at Socket.g (events.js:260:16)
> W20160917-08:42:06.290(5.5)? (STDERR) at emitOne (events.js:77:13)
> => Exited with code: 1
> => Your application is crashing. Waiting for file change.

**Comment by abernix** [comment]
The error you're getting is because Meteor cannot connect to your own Mongo server:

```
MongoError: failed to connect to server [localhost:27017]
```

I'm not sure why your own Mongo deployment would not be available when your Internet is down, but that is an issue that lies outside of Meteor.  Meteor provides its own Mongo server which should work fine regardless of your Internet connectivity.

You should try unsetting your `MONGO_URL` by running:
```
set MONGO_URL=
```

If you still have problems when using the built-in Mongo, please report back and we can try to figure out what that is.
