### ISSUE TITLE
[iPhone] Double clicking home button displays meteor icon not my icon

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7784]
I set all my iPhone icons as described in the mobile configuration documentation [here](http://docs.meteor.com/api/mobile-config.html#App-icons).

Icons display fine in home screen.  But when I double tap the home button and get my list of running applications the meteor icon displays for my app.

Is it possible that this may use the 60x60 size that was deprecated in v1.3?  See [issue #6069](https://github.com/meteor/meteor/issues/6069).

**Comment by brucejo75** [comment]
@martijnwalraven, do you know what size icon is used when double clicking the home button?

**Comment by lucfranken** [comment]
@brucejo75 i cannot test it in full at this moment but we have the 60x60 iPhone icon and with that icon we see it also on double click on the home button. We added it because Xcode also seems to use it. I don't see a risk in adding it so I would just do that when possible.

**Comment by brucejo75** [comment]
OK, I found the full list of icons [here](https://github.com/meteor/meteor/blob/424d8e216709571285de852ee7b1640b11aba828/tools/cordova/builder.js#L16).

60x60 is not on the list, it was deprecated.

But, I loaded all the `ios_` icons and I am now getting the icon when I double click.  I had only used the `iphone` icons.  All good.
