### ISSUE TITLE
tools/static-assets/skel/.gitignore should end with a new line(\n)

### ISSUE THREAD

**Issue by oyyq99999** [meteor/meteor#7786]
As the title says.

**Comment by abernix** [comment]
Opened #7801.  From a sysadmin standpoint, I understand the reasoning behind this.  Per my comments in the commit:

> Even though I think the fight is a bit futile, it is considered best practice to have newlines at the end of all files.  At the request of meteor/meteor#7786, this commit adds newlines to the end of the new app skeleton `.gitignore` file.  These skel files are used when generating new meteor apps so this avoids perpetuation of this problem into futrue generations. ;)

I changed a few other `.gitignore` files that were missing it too.  This will be closed when the PR is merged.  Thanks for pointing it out!
