### ISSUE TITLE
[1.4.1.1] Can't find npm module 'babel-runtime/helpers/defineProperty'

### ISSUE THREAD

**Issue by nmaro** [meteor/meteor#7788]
When starting meteor.

Error: Can't find npm module 'babel-runtime/helpers/defineProperty'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

It's just like issue https://github.com/meteor/meteor/issues/6918
but I'm using version 1.4.1.1 on ubuntu

Removing ~/.meteor and reinstalling didn't help.

` meteor npm install --save-dev babel-runtime
`
solved the issue, yet it seems that this is just a workaround.

**Comment by abernix** [comment]
This is not sufficient for opening an issue as it lacks reproduction steps for recreating your problem from scratch or a reproduction repo.  You also didn't include the version of Ubuntu you were attempting to use.

Please read the information for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Happy to reopen if you provide reproduction steps or a reproduction repo and other relevant details necessary to help debug.

**Comment by nmaro** [comment]
Okay, sorry, thanks for the info. I'll post if it occurs again.
