### ISSUE TITLE
Meteor 1.4.2-beta.4 updating failed on MAC  

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#7792]
Hello All

While updating Meteor form 1.4.1.1 to 1.4.2-beta.4. I am getting following error

`/Users/user/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/3l/lhghyg651ml3dbnzdshjky5h0000gn/T/mt-1law5vc/os.json'
    at Error (native)`

To resolve this issue I try to uninstall meteor and re-install again still it giving this error while updating 

Can you please help me out from this 

Thanks

**Comment by olafleur** [comment]
I got this error to on Windows. I've installed version 1.4.1.1

**Comment by mitiaptest** [comment]
@olafleur I am also able to update to 1.4.1.1 but to solve iOS 10 issues need to update to 1.4.2-beta.4.

but not sure what is going wrong here.

**Comment by olafleur** [comment]
Sorry, I meant that I've installed 1.4.1.1 on Windows and have this problem. Will try to install 1.4.2-beta.4

**Comment by mitiaptest** [comment]
@olafleur I have resolved this issue by removing meteor and adding it again.
