### ISSUE TITLE
Cordova: Content-Security-Policy should include gap: protocol

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#7797]
The current Content-Security-Policy defined here:

https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate_web.cordova.html#L7

is missing the gap: protocol. This protocol is required to enable communication between Native and JavaScript code. If it is missing and such communication is done, Safari runs into an end-less looping printing out an error message on the console every millisecond. And of course the communication fails. I faced this problem when using a Twitter Digits plugin.

I could work-around this problem with these settings:

```
 <meta http-equiv="Content-Security-Policy" content="default-src * data: blob: gap: 'unsafe-inline' 'unsafe-eval' ws: wss:;">
```

Alternatively, `gap:ready` should also work (and be more precise), since the console prints the error for this path, but I haven't tried this out.

I'd recommend to add gap: in the standard. I'm still on Meteor 1.2, so I don't know if that's still an issue in newer Cordova versions, but if they still use gap:, this should be the case.

It would also be very nice if the CSP settings could be set programmatically somehow, in order to restrict them to app-specific values. Patching the boilerplate-generator is possible, but not nice. And it did not work for me. Although I placed my own boilerplate-generator package in my app and checked that it is being executed, the resulting boilerplate was still the standard one.

**Comment by jcesarmobile** [comment]
It has gap: now, this can be closed

**Comment by abernix** [comment]
Confirmed, this was added with https://github.com/meteor/meteor/commit/eef23a30b4eda0b17467fd3b4eb7a1e9106aa43e (in PR https://github.com/meteor/meteor/pull/7934) thanks to @ramezrafla.

Thanks for pointing this out, @jcesarmobile!
