### ISSUE TITLE
Expose a way to set the user ID from the server for testing methods

### ISSUE THREAD

**Issue by thurn** [meteor/meteor#781]
If I try to do e.g. this.setUserId(2345) in a method call initiated from the server, it fails with this error "Can't call setUserId on a server initiated method call".

I would personally like to be able to call setUserId in my unit tests, because otherwise it's kind of tricky to test anything involving an authenticated user. More generally, I'm not really clear on why this isn't allowed... presumably calling it from a server is MORE safe than letting it be called from the client.

**Comment by talbenbasat** [comment]
Did anything change in the past years in this matter?
How can I test methods in meteor?

**Comment by davidworkman9** [comment]
Now that we have a much better solution for testing with 1.3 it'd be really nice to have a way to set the userId for the duration of a test. Having fibers for async requests and not having to worry about separating client and server behaviour would be nice for simple authentication security tests.
