### ISSUE TITLE
how to return HTML on ?_escaped_fragment_= ?

### ISSUE THREAD

**Issue by Nits7029** [meteor/meteor#7813]
Hello,

I built website in Meteor frmaeowrk.

So, how i can return rendered HTML like https://www.meteor.com/?_escaped_fragment_=

Please guide me to follow some necessary steps.

Please do, I stuck on this.

Thanks
Nitesh

**Comment by laosb** [comment]
I think it's better to discuss this on [forums](https://forums.meteor.com).

`spiderable` package can fit you need, but not the best. You can do some search with terms like "meteor server-side rendering".
