### ISSUE TITLE
run meteor 1.4.1.1 error with windows, but it's ok with linux 

### ISSUE THREAD

**Issue by sunshineying** [meteor/meteor#7816]
![image](https://cloud.githubusercontent.com/assets/18010449/18807307/f4a0b39a-8275-11e6-96b6-4a063f6744ff.png)

**Comment by mckb** [comment]
I think 1.4.1.1 has just been patched.

**Comment by mckb** [comment]
Yup, confirmed. The patch has now solved this issue for me. I did do a full reinstall of meteor before updating as well.

**Comment by sunshineying** [comment]
thanks. It's ok now.
