### ISSUE TITLE
Contributing.md has a broken link

### ISSUE THREAD

**Issue by lucfranken** [meteor/meteor#7827]
https://github.com/meteor/meteor/blame/devel/Contributing.md#L64

The link to many subproject (https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) is broken. I believe there was a page on that on the older websites but currently it's gone. The only overview of the projects seems to be the labels but that's also not a real list of projects.

Not sure what's the best way to fix this link as I cannot find a real list of the subprojects.

**Comment by abernix** [comment]
Nice catch!  For now, I'd propose either: 

* Pointing the link to the second-half of the link (the part that `subproject` links to): [The github labels](https://github.com/meteor/meteor/labels); or
* (perhaps better) to the directory listing of the `packages` directory: https://github.com/meteor/meteor/tree/devel/packages

What do you think?

**Comment by lucfranken** [comment]
I found later today this post: https://forums.meteor.com/t/community-involvement-setup/29538/2 which made me think that maybe those things should be in sync so there will be a clear list of projects within the Meteor community.

That being said: For now I would propose the packages directory. Because: It groups nicely, all accounts stuff is together for example. Also I think many people have no idea how many moving parts Meteor actually has which will give a better understanding of the internals.

**Comment by abernix** [comment]
Sounds good to me.  A PR for that link would be welcomed!

**Comment by lucfranken** [comment]
@abernix Clean PR here: https://github.com/meteor/meteor/pull/7834
