### ISSUE TITLE
Provide global configuration for build plugins

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7829]
So while one can configure build plugins by passing options to `api.addFiles`, there is no such mechanism for app-level files. For example, #7727 would need that.

A proposed idea was to use and parse `package.json` for that.

**Comment by mitar** [comment]
cc @tcastelli, would you be interested in working on a pull request for this?

**Comment by tcastelli** [comment]
I have never tried to do that from package.json, but I could check how postcss and get involved into the pull request, (especially if that could help Blaze getting those nice configs :) )

To be clear, If I understand correctly the idea is to create a way to define custom options for packages that could have special build options. If so, I have some questions
- Would these options available for any kind of package(npm/atmosphere)?
- Is there any reference design/conventions that we must follow for this PR (or we can structure it as we want)?
- Limitations?

**Comment by mitar** [comment]
I do not yet have answers to those questions. :-) I think you will have to investigate it.

Probably anything in Meteor could access those options, but the primary use for me is to access them from build plugins. For example, see https://github.com/meteor/meteor/pull/7727 how I configure build plugin to use `api.addFiles`.

We probably want in `package.json` section for all options, and then for each of packages their own key, which would then have custom values plugin or whoever could access. Something like:

```json
{
  "packageOptions": {
    "stylus": {
      "autoprefixer": {
        "browsers": ["last 3 Chrome versions", "Firefox >= 7", "Explorer >= 8", "last 2 versions", "> 1%", "Firefox ESR", "Safari >= 4"]
      }
    }
  }
}
```

**Comment by sebakerckhof** [comment]
I remember @stubailo opening a related issue when we were discussing autoprefixing: https://github.com/meteor/meteor/issues/5512 .

**Comment by sebakerckhof** [comment]
Ow, I see you already found that one. Anyway, it might have some relevant discussion on how to read the config file.

**Comment by mitar** [comment]
Yes, that was only for minimizers. I am thinking that those options could be used by any package, including build plugins.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20global%20configuration%20for%20build%20plugins&body=Migrated%20from:%20meteor/meteor%237829) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
