### ISSUE TITLE
Missing link to WebApp project in readme of autoupdate package

### ISSUE THREAD

**Issue by lucfranken** [meteor/meteor#7843]
In followup on #7827 here is a link to "WebApp project" which does not exist:

https://github.com/meteor/meteor/tree/8cdab91bc415433aa693e045534996e5a3ba4f05/packages/autoupdate

https://github.com/meteor/meteor/blame/devel/packages/autoupdate/README.md#L12

It seems there is no real list of "projects" anymore. Which is also referred to by Thea in: https://forums.meteor.com/t/community-involvement-setup/29538/2 as "parts of Meteor" or "components".

Is there such a list available which describes the main projects under which the packages are grouped? So we can link to those and there a developer can get an overview of the specific projects of Meteor? 

It seems to me that it's much easier to get a grasp of parts of Meteor, for developers who want to contribute, when you have an idea of how the packages relate to each other. Now I do that just by hand following which packages include each other.

Search on all occurrences of this specific link:
https://github.com/meteor/meteor/search?utf8=✓&q=%22meteor.com%2Fwebapp%22&type=Code

_Found this while researching: https://github.com/meteor/meteor/issues/7760_

**Comment by abernix** [comment]
The meteor.com/webapp link was probably lost during the Meteor.com redesign which happened a long time ago.  You can still find `webapp` in the `packages` directory that we looked at (and linked to) in #7827.

> Search on all occurrences of this specific link:
> https://github.com/meteor/meteor/search?utf8=✓&q=%22meteor.com%2Fwebapp%22&type=Code

As you can see, those are README files from the other packages within the Meteor project.  I think it's reasonable to update all those links (in that search) to be: `[Webapp](https://github.com/meteor/meteor/tree/devel/packages/webapp)`?

It's possible that those (including the one already accepted in #7827) should be relative links (i.e. `[Webapp](../webapp)`), but I don't have a particular feeling either way.  Relative might be easier to update, but less helpful if viewing the `README` in a normal text editor (e.g. `vi`, `emacs`, Atom, Sublime Text, etc.).

Maybe a `README` for this `packages` directory might be a good "table of contents" for the various projects.?

Thoughts?

**Comment by lucfranken** [comment]
@abernix to be clear I am waiting for @theadactyl as it seems she is working on something https://forums.meteor.com/t/community-involvement-setup/29538/59 which might relate to the organization of this. 

I agree with your approach, we should improve this on Github with readme files. But it needs some agreement internally it seems to organise this so let's wait for that?

**Comment by abernix** [comment]
I could be entirely wrong, but I don't think @theadactyl is going to provide anything which addresses the action item of this issue which is fixing the webapp links.

I think the question here is whether that link should point to:

* https://atmospherejs.com/meteor/webapp, or
* https://github.com/meteor/meteor/tree/devel/packages/webapp, or
* Same as previous link, but the `master` branch

These are all essentially the same readme for the `webapp` project.  The more I think about this, the more I lean toward the first,  but it's up for discussion: they are technically Meteor packages, and thus have Atmosphere pages (and I think that's where meteor.com/webapp once re-directed to).

A `README`  table of contents for the `packages` directory is for another issue, but just something I was mentioning in passing.

**Comment by theadactyl** [comment]
@abernix @lucfranken agreed that what I'm working on isn't so fine-grained yet to block this discussion, as I'm focusing for now on the project maintenance structure vs component documentation. That being said, if the convention for packages is to link to Atmosphere README's, I agree we should follow it until we want to change that across the board. Not an expert here.

> A README table of contents for the packages directory is for another issue, but just something I was mentioning in passing.

I think this is what you're asking for @lucfranken, yes? As contributor-oriented documentation, this should probably live on GitHub. Any ideas where it would be most helpful?

**Comment by abernix** [comment]
@lucfranken Do you want to submit a pull request to take care of this above, mentioned [in this comment above](https://github.com/meteor/meteor/issues/7843#issuecomment-251321474):

> I think it's reasonable to update all those links (in that search) to be: [Webapp](https://github.com/meteor/meteor/tree/devel/packages/webapp)?

I think that's the only actionable item in this issue and it would be nice to get it closed. :smile:

**Comment by hwillson** [comment]
Hi @abernix - hopefully PR #8172 helps complete this. Let me know if you need anything else - thanks!

**Comment by abernix** [comment]
Thanks, @hwillson.  #8172 was merged and this appears to be done now. 👍 

Also, thanks @lucfranken for originally reporting this!
