### ISSUE TITLE
Updates needed for Xcode 8

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#7847]
General > Identity
- Display Name not automatically set from mobile-config.js App.info.name

General > Signing
- Automatically manage signing is now checked by default

Build Settings > Signing
- Needs update for automatic signing, so:
- Debug & Release should now both be set to iOS Developer

**Comment by abernix** [comment]
Just to make it clear: You're referring to [this forum post](https://forums.meteor.com/t/ios-10-compatibility/26065/17) and your findings you reported there.

I think it might be better to open this issue with the [`meteor/cordova-plugin-meteor-webapp` repo](https://github.com/meteor/cordova-plugin-meteor-webapp)

@aldeed Can you advise what might be the best course of action here?

**Comment by markoshust** [comment]
Yes, the app name isn't carrying over from mobile-config.js. Also, the build settings for signing apps has changed with Xcode 8.

**Comment by abernix** [comment]
Is this still a problem with Meteor 1.4.2.1?  I know you had some discussion about signing problems in the #7668 issue and there was mention of a [Cordova bug](https://issues.apache.org/jira/browse/CB-11845) but any idea if it was the problem?  That Cordova issue is now marked as resolved.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and (based on my previous comments) I believe this may be fixed with Cordova updates that were made in 1.4.2.x.

Happy to reopen if it's still a problem though.
