### ISSUE TITLE
[IOS 10 / jquery] ScrollTop broken

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/meteor#7848]
If you are using jquery ScrollTop in you app it no longer works. Something got changed on IOS 10 as once I updated it stopped working everywhere I was using this.

**Comment by abernix** [comment]
If this is the case (you haven't provided a reproduction, or any version information about the jQuery/Meteor/etc. you are using), this wouldn't be an issue with Meteor so you should file an issue with jQuery.  If jQuery updates this, you can use any version of jQuery you'd like in your project using the `jquery` NPM package:

In your project directory:

    meteor npm install jquery --save

Meteor will prefer the NPM-installed version of `jquery` over its own [per this code](https://github.com/meteor/meteor/blob/c829bf580eae759f17ef005f7b6ccdf108ae7ed5/packages/jquery/main.js#L4).
