### ISSUE TITLE
[sockjs] Handle offline with sockjs

### ISSUE THREAD

**Issue by NitroBAY** [meteor/meteor#7853]
Hello,
I'm building a service worker for Meteor (by the way I don't know if I can turn it into a package, that means if I can put a file in the /public programmatically), and I'm not sure how handle sockjs request when I'm offline without it to add a lot of console errors, if I don't return request sockjs complains, if I do return a proper 503 I have the precedent error and a new one 

```
GET http://localhost:3000/sockjs/info?cb=1ff5tlzdy1 net::ERR_INTERNET_DISCONNECTED
sockjs-0.3.4.js:854 GET http://localhost:3000/sockjs/info?cb=1ff5tlzdy1 503 (No connection to the server)
```

How to just answer to sockjs when it ask for an url _**/sockjs/_\* "the client is currently offline, do not worry the application and I know it and handle it"

**Comment by NitroBAY** [comment]
Do someone will help me ?

**Comment by abernix** [comment]
Really, you will probably have better luck getting assistance on this in the existing threads you've been participating on about service workers (e.g. #5982 & #6222), but I'll give you whatever I can.  It's not really clear to me what you need from Meteor but I'm not familiar with this at all.

It seems like something might be necessary upstream from `sockjs` to make this work?

Have you looked into how the previous [Meteor-implementation of `appcache`](/meteor/meteor/blob/master/packages/appcache) handled things?  Meteor also provides the reactive [`Meteor.status()`](https://docs.meteor.com/api/connections.html#Meteor-status) function to detect changes in connectivity to the server.

If you're simply trying to avoid `ERR_INTERNET_DISCONNECTED` messages in the console, I'm not even entirely sure that's possible.  I see that error all the time from a variety of web-apps when I'm offline going online and offline.

It's entirely likely that something major would have to change for Meteor to work with this sort of setup.  Happy to try to figure this out with you, but I'm completely in the dark as to what's necessary.  Again, the existing issues will probably be more help as the participants have more familiarity with the issue.  I suggest you start there.

**Comment by NitroBAY** [comment]
Okay so if you think it's normal to have error on the console when one is disconnected I can close this issue 👍

**Comment by guanzo** [comment]
@NitroBAY did you ever figure this out? I'm testing an offline page and the sockjs errors are really annoying, they fill up the console with errors and it's just distracting.
