### ISSUE TITLE
[1.4.2-beta.7] Can't update from 1.4.1.1 on Linux

### ISSUE THREAD

**Issue by chompomonim** [meteor/meteor#7854]
```
$ meteor update --release 1.4.2-beta.7
/home/private/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-or7tma/os.json'
    at Error (native
```

Running on Ubuntu Linux 16.04
On MacOSX update worked fine.

BTW, I tried it on brand new meteor project as well:
- meteor create test
- cd test
- meteor npm install
- meteor
- [ctrl+c]
- meteor update --release 1.4.2-beta.7
- Boom! .... Error: ENOENT: ...

**Comment by abernix** [comment]
Please search existing/recent issues before opening new/duplicate issues.

#7806
