### ISSUE TITLE
Adding support for absolute imports without the leading slash

### ISSUE THREAD

**Issue by fabiospampinato** [meteor/meteor#7855]
I'm porting an existing Meteor project to TypeScript using [this](https://github.com/barbatus/typescript) package, which as far as I understood may get included into Meteor itself at some point in the future.

There's basically an incompatibility problem between the way absolute imports are written in Meteor and in TypeScript:

```js
import Something from '/imports/module'; // Meteor
import Something from 'imports/module'; // TypeScript
```

If I write my imports using Meteor's style I won't get almost any of the advantages that got me switching to TypeScript in the first place, since being unable to locate the referred package effectively trashes away all the types added to it.

If I write them using TypeScript's style then a `run` will fail since Meteor isn't able to locate the modules.

My request is: can Meteor support absolute imports without the need to write the leading forward slash?

**Comment by abernix** [comment]
I'm really not familiar with TypeScript, but "Meteor's style" (of imports) is not just some made-up idea.  As with file paths, URLs, and many other things, omitting the leading slash changes the meaning entirely and I would assume that the same is true of TypeScript.

Surely something else must be wrong or there must be a different way to fix this.  I would recommend discussing this with the package author if you're having an issue with this or maybe reach out to the [Meteor forums](http://forums.meteor.com/) for input.

**Comment by javoire** [comment]
So this is more than TypeScript. For editors (vscode, vim) relying on language servers (eg [this one](https://github.com/sourcegraph/javascript-typescript-langserver) for js/ts) the import paths with a leading slash don't work (i.e go to definition). Probably because they assume it's an OS absolute path.

Here's how I read it:
```js
import Something from '/imports/module'; // absolute file system path
import Something from 'imports/module'; // path relative to project root
import Something from './module': // path relative to current file
```

If meteor were able to resolve imports without leading slash it would both support language servers and be more aligned with how other JS tooling resolves import paths.

Cheers.

**Comment by javoire** [comment]
When you google a problem and find your own reply to it :P 

For VSCode you can get Meteors "absolute import paths" to work using https://forums.meteor.com/t/vscode-absolute-imports/40278/16

Still have no solution for Vim.

**Comment by hexsprite** [comment]
It sounds like a bug in the client if they don't support the official TypeScript solution to support leading slash absolute paths. Personally I think having a leading slash that means the root of the filesystem, as opposed to the root of my source tree, is pretty useless. There's almost no situation I could think of where I would want to embed an absolute filesystem path into a project.

**Comment by javoire** [comment]
Ok it's all sorted now. [This setup](https://github.com/autozimu/LanguageClient-neovim/wiki/javascript-and-typescript-language-servers#method-2---typescript-language-server) of the language server handles leading slashes, given the appropriate `tsconfig.json` setup mentioned above. 

@hexsprite you are right that it's the clients responsibility/fault to handle this.

Cheers
