### ISSUE TITLE
Support for new field update operators ($min, $max, $currentDate and $mul)

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7857]
Since mongo 2.6+ there are some new field operators: $min, $max, $currentDate and $mul.

Minimongo currently does not yet support these modifiers. @stubailo [encouraged](https://forums.meteor.com/t/meteor-1-4-1-1-does-not-support-mongo-3-2-operators-min-max/29900/8?u=seba) to make a PR for this, which I plan to do. So I mainly create this issue to link the PR to an issue.

**Comment by stubailo** [comment]
I'd suggest doing it in several smaller PRs, if possible - that way we can merge each individual one faster.

**Comment by stubailo** [comment]
Oh never mind, I see that you have opened a PR already.

**Comment by sebakerckhof** [comment]
Yeah, I could still split them up if you think it's better, but even with them combined it's a pretty small PR.

**Comment by stubailo** [comment]
Yep, no problem.

**Comment by tmeasday** [comment]
#7858 is merged!
