### ISSUE TITLE
Error: Attempting to combine different files

### ISSUE THREAD

**Issue by dmarkrollins** [meteor/meteor#7859]
The file in error is attached and is part of a local package for my app. My understanding is that local packages are still supported - although I know modules is the preferred implementation moving forward.

Error: Attempting to combine different files:
{ type: 'js',
  data: <Buffer 0a 54 65 6d 70 6c 61 74 65 2e 5f 5f 63 68 65 63 6b 4e 61 6d 65 28 22 61 75 74 68 52 65 63 6f 76 65 72 50 61 73 73 77 6f 72 64 22 29 3b 0a 54 65 6d 70 6c ...>,
  sourcePath: 'client/views/template.auth-recoverpassword.js',
  targetPath: 'client/views/template.auth-recoverpassword.js',
  servePath: '/packages/tiu-app/client/views/template.auth-recoverpassword.js',
  hash: 'fe63d92ee0e00cc8e20aaad25197eb1fbddc6c18',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  installPath: 'node_modules/meteor/tiu-app/client/views/template.auth-recoverpassword.js',
  imported: true }
{ type: 'js',
  data: <Buffer 0a 54 65 6d 70 6c 61 74 65 2e 5f 5f 63 68 65 63 6b 4e 61 6d 65 28 22 61 75 74 68 52 65 63 6f 76 65 72 50 61 73 73 77 6f 72 64 22 29 3b 0a 54 65 6d 70 6c ...>,
  sourcePath: 'client/views/template.auth-recoverPassword.js',
  targetPath: 'client/views/template.auth-recoverPassword.js',
  servePath: '/packages/tiu-app/client/views/template.auth-recoverPassword.js',
  hash: 'fe63d92ee0e00cc8e20aaad25197eb1fbddc6c18',
  sourceMap: undefined,
  lazy: true,
  bare: false,
  mainModule: false,
  installPath: 'node_modules/meteor/tiu-app/client/views/template.auth-recoverPassword.js',
  imported: false }

```
at checkProperty (/tools/isobuild/import-scanner.js:293:15)
at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:303:5)
at /tools/isobuild/import-scanner.js:206:14
at Array.forEach (native)
at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:177:11)
at /tools/isobuild/compiler-plugin.js:1011:15
at Array.forEach (native)
at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:982:19)
at ClientTarget._emitResources (/tools/isobuild/bundler.js:926:8)
at /tools/isobuild/bundler.js:697:12
at /tools/utils/buildmessage.js:359:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at ClientTarget.make (/tools/isobuild/bundler.js:688:18)
at /tools/isobuild/bundler.js:2544:14
at /tools/isobuild/bundler.js:2633:20
at Array.forEach (native)
at Function._.each._.forEach (/Users/DMR/.meteor/packages/meteor-tool/.1.3.5_1.mzs98g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at /tools/isobuild/bundler.js:2632:7
at /tools/utils/buildmessage.js:271:13
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:264:29
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:262:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:253:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.capture (/tools/utils/buildmessage.js:252:19)
at bundle (/tools/isobuild/bundler.js:2525:31)
at /tools/isobuild/bundler.js:2472:32
at Object.withCache (/tools/fs/files.js:1445:12)
at Object.exports.bundle (/tools/isobuild/bundler.js:2472:16)
at /tools/runners/run-app.js:591:36
at Function.run (/tools/tool-env/profile.js:489:12)
at bundleApp (/tools/runners/run-app.js:581:34)
at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
at AppRunner._fiber (/tools/runners/run-app.js:887:28)
at /tools/runners/run-app.js:411:12
```

[auth-recoverPassword.js.zip](https://github.com/meteor/meteor/files/505097/auth-recoverPassword.js.zip)

**Comment by dmarkrollins** [comment]
OK so I figured it out -  the file name specified in my package.js did not match the the name of the  same file on disk. It is case sensitive. V1.2 is apparently case insensitive.

Once I renamed auth-recoverpassword.js to auth-recoverPassword.js to match the file's actual name on the file system it solved my problem. 

In this scenario I suggest either changing the "attempting to combine different files" error thrown to something like "File {0} not found - please check file name case sensitivity" --- or simply make file names case insensitive.

Thanks

**Comment by abernix** [comment]
Glad to hear that you resolved the situation.  Some operating systems behave differently in regard to case so I think it's generally good advice to ensure that case is matched correctly when referencing files on disk.  This behavior (as implemented now) would actually prevent this from happening in the future and should provide better portability.

Closing, but thank you for reporting this issue!

**Comment by dmarkrollins** [comment]
@abernix - does it make sense to update the error message related to this occurrence to something like what I suggested to reduce developer churn? 

The more delightful the experience the better in my opinion. 

I mean you do a thing that causes an error and the tool tells you about the thing you are not supposed to do and ideally how to fix it.

My 2 cents anyways.

**Comment by abernix** [comment]
I'm not sure there would be an

**Comment by abernix** [comment]
~~I'm not sure there would be an~~

👆👆👆 Always nice to help with unintended mistakes whenever possible! 😬

I wasn't sure if there would be a reasonable way of detecting this, but actually, it might be straightforward.  Perhaps as easy as [changing these lines](https://github.com/meteor/meteor/blob/devel/tools/isobuild/import-scanner.js#L290-L297) to be something like:

```js
      if (oldFile[name] !== newFile[name]) {
        const fuzzyCase = oldFile.sourcePathtoLowerCase() ===
          newFile.sourcePath.toLowerCase();

        throw new Error(
          "Attempting to combine different files" +
            ( fuzzyCase ? " (is the filename case slightly different?)" : "") +
            ":\n" +
            inspect(omit(oldFile, "dataString")) + "\n" +
            inspect(omit(newFile, "dataString")) + "\n"
        );
      }
```

Actual message up for discussion, of course.

/cc @benjamn Does that sound reasonable to submit a PR for?

**Comment by abernix** [comment]
The PR has been merged and this will be fixed in an upcoming release of Meteor.  Thanks very much for making this suggestion and helping improve developer experience, @dmarkrollins.  If you have more suggestions, please keep them coming (and if they're simple like this, pull-requests are absolutely the best!)
