### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/private/tmp/mt-1j8e0c0/os.json'

### ISSUE THREAD

**Issue by jsantana90** [meteor/meteor#7861]
I just bought a macbook 2016 and installed meteor via the command `curl https://install.meteor.com/ | sh`

When I try to run a meteor 1.4 app it works perfectly but when I go to a meteor app 1.2 or 1.3 it starts downloading the meteor tools and after it finishes I get this error message:

<img width="1275" alt="screen shot 2016-10-02 at 3 32 22 pm" src="https://cloud.githubusercontent.com/assets/9933887/19023172/7938e286-88b5-11e6-8f3e-e625d01deda4.png">

I was able to fix the version 1.2 by installing nvm and using node version 0.10.40 (I think this was the fix) but after trying the same method in a meteor 1.3 app (using node 4.5.0) it didn't work and now I can't run any app which is version 1.3.

Not sure what to do :(

**Comment by jsantana90** [comment]
Well, don't know what it was but got it working by doing the following:

I was able to get it running by doing `https://install.meteor.com/?release=1.3.2.4 | sh` and now everything seems to work even the 1.2 and 1.3, haven't tested 1.4 yet but hopefully it works.

**Comment by abernix** [comment]
Seems to be a duplicate of #7806 (still pending).  Thanks for reporting it and your solution though!
