### ISSUE TITLE
CR line-endings when springboarded

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#7863]
As of Meteor 1.4.1.1 on OSX.

Try this in the terminal:

``` Bash
meteor create helloworld --release 1.4.1
cd helloworld
RAW_RELEASE=$(meteor --version)
printf 'xx%soo' "$RAW_RELEASE" # Expecting "xx1.4.1oo" but get "oo". Which means $RAW_RELEASE contains a line break.

FOO=$(echo "$RAW_RELEASE" | tr -d '\n')
printf 'xx%soo' "$FOO" # Expecting "xx1.4.1oo" but get "oo". Which means $RAW_RELEASE contains a line break that is NOT newline.

BAR=$(echo "$RAW_RELEASE" | tr -d '\r')
printf 'xx%soo' "$BAR" # Expecting "xx1.4.1oo" and get "xx1.4.1oo". Which means $RAW_RELEASE contains a carriage return.
```

The thing is, if you use `meteor --version` outside of an app, the result doesn't contain any line breaks.

Just please be consistent.

**Comment by abernix** [comment]
This isn't a new bug, but rather a side effect of the spring-boarding process – meaning this will only happen when your system Meteor doesn't exactly match the app that you're running it in.  It actually adds the CRs to all output, not just the output from the `--version`

I'll use `perl` to show this more clearly.   In this output, it should also be noted that when a cmd doesn't explicitly print `\n` my `zsh` shell prints `%` and adds its own.

```zsh
~/tests $ # Make an alias for perl
~/tests $ alias show-line-endings="perl -pe 's/\n/[NL]/;s/\r/[CR]/'"
~/tests $ meteor --version | show-line-endings # Check system Meteor version (it's 1.4.1.1)
Meteor 1.4.1.1[NL]%
~/tests $ cd 1.4.1-proj # No \r!  Go into a 1.4.1 project
~/tests/1.4.1-proj $ cat .meteor/release # Prove it. ;)
METEOR@1.4.1
~/tests/1.4.1-proj $ # Run meteor which will springboard to 1.4.1
~/tests/1.4.1-proj $ meteor --version | show-line-endings
Meteor 1.4.1[CR][NL]%
~/tests/1.4.1-proj $ # \r is there!  Now, cheat around the springboard
~/tests/1.4.1-proj $ ~/.meteor/packages/meteor-tool/1.4.1/mt-os.osx.x86_64/meteor --version | show-line-endings
Meteor 1.4.1[NL]%
~/tests/1.4.1-proj $ # \r is gone again! Try "--help"...
~/tests/1.4.1-proj $ meteor --help | show-line-endings
Usage: meteor [--release <release>] [--help] <command> [args][CR][NL]       meteor help <command>[CR][NL]
...snipped for brevity...
See 'meteor help <command>' for details on a command.[CR][NL][CR][NL]%
~/tests/1.4.1-proj $ # \r is everywhere a \n is.  Now go back to system Meteor
~/tests $ meteor --help | show-line-endings
Usage: meteor [--release <release>] [--help] <command> [args][NL]       meteor help <command>[NL]
...snipped...
See 'meteor help <command>' for details on a command.[NL][NL]%
~/tests $ # \r is gone.
```

I think this could be a side effect of using `kexec` or maybe related to the progress bar rendering, perhaps somewhere [in this file](https://github.com/meteor/meteor/blob/devel/tools/console/console.js) (maybe in the`depaint` function?).  It's possible that `enableProgressDisplay` is getting set on these basic commands when it shouldn't be.

I think a PR would be considered for this.  As a work around, I would suggest you either always clean `meteor --version` with `| tr -d '\r'` simply use the value from the` .meteor/release` file in your app project (e.g. `cat .meteor/release`).

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in quite some time. If anyone comes across this issue and is interested in working on it, please let us know (it is pull-requests-encouraged). Until then however, this issue will be closed. Thanks!
