### ISSUE TITLE
Package-level lazy imports

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7867]
It seems there is no way to have package-level lazy imports?

**Comment by benjamn** [comment]
Related? https://github.com/meteor/meteor/issues/6132

**Comment by mitar** [comment]
Hm, maybe. Not sure how would this be best implemented/exposed. I love the fact that I can expose some symbols from a package and that I do not have to again and again import those modules. But then how would that work lazily is a question.

**Comment by hwillson** [comment]
This issue appears to have been addressed by #6132, so I'll close it off (I realize there has been a lot of  discussion in #6132 about how things are currently implemented, and not everyone agrees with them, but the changes implemented for #6132 should still address this issue). Thanks for reporting this originally!

**Comment by mitar** [comment]
No, this has not been addressed at all. [See comment here](https://github.com/meteor/meteor/issues/6132#issuecomment-261378905).

**Comment by mitar** [comment]
Or, you are right. The issue opened here is resolved by being able to do:

```
import ... from "meteor/some:package/implicit.js"
```

I think we can track how one defines which files one can import or not in #7598.

**Comment by mitar** [comment]
I summarized the proposal [here](https://github.com/meteor/meteor/issues/7598#issuecomment-279021281).
