### ISSUE TITLE
Error deploying to Galaxy on EU west server  - Connection error 

### ISSUE THREAD

**Issue by tiberiucorbu** [meteor/meteor#7875]
The command  suggested into the docs (http://galaxy-guide.meteor.com/deploy-quickstart.html) fails.
When I run :
`$ DEPLOY_HOSTNAME=eu-west-1.galaxy-ingress.meteor.com meteor deploy samples.tiberiucorbu.ro --settings ./galaxy-settings.json`
After login and build sequence it puts out at the end : 
`Error deploying application: Connection error (140227627919168:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:757:`

I have no problem with the internet (as far as I know), but the `ping` to the `eu-west-1.galaxy-ingress.meteor.com` and to `galaxy-ingress.meteor.com` fail.

```
$ ping eu-west-1.galaxy-ingress.meteor.com
PING eu-west-1.galaxy-ingress.meteor.com (52.210.144.103) 56(84) bytes of data.
^C
--- eu-west-1.galaxy-ingress.meteor.com ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10029ms

$ ping galaxy-ingress.meteor.com
PING galaxy-ingress.meteor.com (52.72.167.154) 56(84) bytes of data.
^C
--- galaxy-ingress.meteor.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5033ms
```
When I ping meteor.com it works
```
$ ping meteor.com
PING meteor.com (52.85.173.85) 56(84) bytes of data.
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=1 ttl=245 time=16.2 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=2 ttl=245 time=34.7 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=3 ttl=245 time=16.3 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=4 ttl=245 time=32.0 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=5 ttl=245 time=21.3 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=6 ttl=245 time=29.3 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=7 ttl=245 time=16.7 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=8 ttl=245 time=26.1 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=9 ttl=245 time=22.7 ms
64 bytes from server-52-85-173-85.fra6.r.cloudfront.net (52.85.173.85): icmp_seq=10 ttl=245 time=17.0 ms
^C
--- meteor.com ping statistics ---
11 packets transmitted, 10 received, 9% packet loss, time 10035ms
rtt min/avg/max/mdev = 16.249/23.286/34.797/6.618 ms
tiberiu@curioux:~$ 
```

**Comment by abernix** [comment]
Hey, just as a reminder, this is not the best place for Galaxy Support as it's not intended for those purposes, but I will point out that the command you're using differs slightly from the guide which you referenced and is the cause of the problem.

You said you were doing:

```
DEPLOY_HOSTNAME=eu-west-1.galaxy-ingress.meteor.com meteor deploy samples.tiberiucorbu.ro --settings ./galaxy-settings.json
                                ^^^^^^^^
```

But the guide recommends using

```
DEPLOY_HOSTNAME=eu-west-1.galaxy.meteor.com meteor deploy [hostname] --settings path-to-settings.json
                                ` without -ingress
```

You'll note a slight difference that the host is `eu-west-1.galaxy.meteor.com` and **not** `eu-west-1.galaxy-ingress.meteor.com`.

If you make that change, you should be fine!  If you have any additional problems, open a support ticket in Galaxy by clicking "Support" from the menu on your Galaxy Dashboard.
