### ISSUE TITLE
is the version wrong in History.md?

### ISSUE THREAD

**Issue by danutc** [meteor/meteor#7881]
According with History.md file v1.4.2 was released. I believe that is wrong. If that is the case please update file.

https://github.com/meteor/meteor/blob/devel/History.md

**Comment by abernix** [comment]
1.4.2 is the current **beta** release and the default branch on GitHub is `devel`.  Change the branch to `master` and you'll see the stable release change log.

https://github.com/meteor/meteor/blob/master/History.md
