### ISSUE TITLE
Ver 1.4.1.2 do not update css minifier

### ISSUE THREAD

**Issue by Testato** [meteor/meteor#7893]
I installed the last Meteor version on local linux (xubuntu 16.04-32bit)
Created a new app
update the new app by meteor update

But the css minifier do not update to the last version

```
This project is already at Meteor 1.4.1.2, the latest release.
Your top-level dependencies are at their latest compatible versions.
The following top-level dependencies were not updated to the very latest version available:
 * standard-minifier-css 1.2.1 (1.3.1 is available)
```

Also if i manually "meteor remove" and "meteor add" it, the version remains 1.2.1 and is not possible update to 1.3.1

**Comment by TechplexEngineer** [comment]
I found that I can `meteor add standard-minifier-css@1.3.1` but then I get a notice that experimental versions of packages were needed to resolve the constraints.

```
Currently using standard-minifier-css with version constraint 1.2.0_1.             
The version constraint will be changed to 1.3.1.
                                              
Changes to your project's package version selections:
                                              
meteor+                upgraded from 1.2.17_1 to 1.2.18-beta.9
standard-minifier-css  upgraded from 1.2.1 to 1.3.1
underscore+            upgraded from 1.0.9 to 1.0.10-beta.9

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
                                              
standard-minifier-css: Standard css minifier used with Meteor apps by default.
```

**Comment by laosb** [comment]
I guess it's because 1.4.2 betas are using `standard-minifier-css` at 1.3.1, so it depends on a beta version.

**Comment by Testato** [comment]
Here we use 1.4.1 like specified in subjct title

**Comment by abernix** [comment]
Can you try again now that Meteor 1.4.2 is released and see if this is still a problem for you?  This should be resolved since the new release also releases new dependencies and those will no longer be experimental versions.

**Comment by abernix** [comment]
@Testato Any update on this?

**Comment by TechplexEngineer** [comment]
Once you update to 1.4.2 the issue goes away. I just updated my project to 1.4.2 and the css minifier is at 1.3.2. Perfect!

**Comment by abernix** [comment]
Thanks.  As @laosb suggested, that was expected to be the case once 1.4.2 came out.

Sometimes, there may be newer packages published which you are not able to receive for various reasons.  You can generally see the reason for this by trying to directly add the package at that version:

    meteor add PACKAGE-NAME@VERSION

Closing as resolved!

**Comment by Testato** [comment]
Yes, it' solved
Thanks
