### ISSUE TITLE
ES7 async/await statements won't compile in Meteor anymore

### ISSUE THREAD

**Issue by damonmaria** [meteor/meteor#7897]
As per [tiny example Meteor Github project](https://github.com/damonmaria/meteor-await-bug-example). It is simply `meteor create`, installing Babel npm packages, and then using `async`/`await` in `server/main.js`.

I did have `async`/`await` working in Meteor previously but I suspect a recent Babel upgrade has broken some way in that Meteor's ecmascript package compiles using Babel. I've tried downgrading Babel but it doesn't appear to be related to a package I directly depend on. 

Meteor: `METEOR@1.4.1.2`
OS: Mac OS X

As per the example project linked to above. No Meteor packages added, just 2 Babel packages (which are their current versions):
````js
  "devDependencies": {
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-stage-2": "^6.17.0"
  }
````

Meteor log on start:
````
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
   
   While processing files with ecmascript (for target os.osx.x86_64):
   /Users/damon/.meteor/packages/ecmascript/.0.5.8_1.1mmdbod++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-traverse/lib/visitors.js:232:13:
   /server/main.js: You gave us a visitor for the node type "ForAwaitStatement"
   but it's not a valid type
   at verify
   (/Users/damon/.meteor/packages/ecmascript/.0.5.8_1.1mmdbod++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-traverse/lib/visitors.js:232:13)
...
````

**Comment by benjamn** [comment]
Please try this without `.babelrc` file (or the Babel presets). Not all configurations of Babel plugins are guaranteed to work well together, and Meteor supports `async`/`await` without any additional plugins.

**Comment by damonmaria** [comment]
Correct. It works for `async`/`await` if I remove the `.babelrc`. 

But our project uses Mobx and, as per it's recommendation, `@decorators`. Plus, class properties don't seem to be supported by default in Meteor either:
````
   While processing files with ecmascript (for target os.osx.x86_64):
   server/main.js:18:14: /server/main.js: Missing class properties transform.
   
   While processing files with ecmascript (for target os.osx.x86_64):
   server/main.js:18:14: /server/main.js: Method has decorators, put the
   decorator plugin before the classes one.
````

I would hate to work in React without either of these. 

From the error in the original post above it appears that Meteor is calling Babel in some incompatible way. Or maybe more specifically that the version of Babel Meteor's `ecmascript` package bundles is incompatible with the latest Babel release?

**Comment by benjamn** [comment]
Don't get me wrong, I fully expect that these transforms can work together, I just wanted to check that the problem is coming from the extra transforms. Thanks for reporting this!

**Comment by damonmaria** [comment]
Awesome. Thanks @benjamn.

**Comment by abernix** [comment]
Probably-Related Forum Thread: https://forums.meteor.com/t/the-keyword-await-is-reserved/29871

**Comment by benjamn** [comment]
As part of the [1.4.2 release](#7668) I [upgraded](https://github.com/meteor/meteor/commit/6bb4bd739b973e8dd496f105385ce8c4c004f8d4) the Babel [packages](https://github.com/meteor/babel-preset-meteor/commit/e044172bda7c556f68e0e64226032c092564a005) used by [`meteor-babel`](https://github.com/meteor/babel), which appears to have resolved the problem in your reproduction app.

Please verify this by running `meteor update --release 1.4.2-rc.0` and restarting reproduction app.

If you get an error about missing `../core-js/promise`, just `meteor npm install --save babel-runtime`.

If it's still failing for you, feel free to reopen this issue.

**Comment by damonmaria** [comment]
I can confirm the reproduction app now works with rc.0. 

FYI I did have to install `babel-runtime`. 

Thanks @benjamn
