### ISSUE TITLE
Meteor 1.4.1.2 - Data not loading after some time

### ISSUE THREAD

**Issue by tnedich** [meteor/meteor#7899]
After some time data is not loding, but no errors are shown neither on server or browser side (in my case). Project is still working but without data. Operating system: Windows 7, 64-bit

**Comment by lednhatkhanh** [comment]
+1 This happens for me too.

**Comment by jerradpatch** [comment]
I also get this, the data shows up when the server is first booted, but after a browser reload or just waiting the subscriptions are not called (ie server prints nothing to the console) or compiling on save. There are no errors on either browser or server, and I can not put a log statement to get a hint as to the issue. It calls subscription, then calls find, then nothing is sent from the server.....

I am using the new recommended method of rxjs subscriptions and observable collections.

Any suggestions?

**Comment by StGeass** [comment]
+1 Same for me, sometimes (idk why, and when, but usually after reload page) data not loading, with MongoDB all is well. All subscriptions on client exists, but never ready.

**Comment by jerradpatch** [comment]
so, I believe I fixed my issue. Long story short, I believe updating a package that was incompatible with other packages was the issue. The bottom of this thread solved my issue. 

https://forums.meteor.com/t/meteor-app-crash-randomly-throwing-a-mongoerror-server-instance-pool-was-destroyed-error/29610/27

the answer by babrahams

recapping, I updated my mongo instance to 1.1.12_5, and npm-mongo to  2.2.10_1

**Comment by StGeass** [comment]
@jerradpatch also works for me, thank you

**Comment by tnedich** [comment]
Helped me also. It is working now.

**Comment by abernix** [comment]
Closing as the solution seems to have been fixed by updating Mongo packages to the latest version:

    meteor update npm-mongo mongo

Or simply:

    meteor update --all-packages
