### ISSUE TITLE
ENOENT: no such file or directory ... program.json

### ISSUE THREAD

**Issue by xubuhang** [meteor/meteor#7904]
#### If this does not match your error, please search for another, more appropriate issue, or open a new issue as described in [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)

*****

<img width="570" alt="qq20161011-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/19258140/1035bb0c-8fa8-11e6-8fd3-474b19e8b5f3.png">
<img width="586" alt="qq20161011-1 2x" src="https://cloud.githubusercontent.com/assets/4189632/19258219/b8623210-8fa8-11e6-8201-a730642e4cfa.png">

<img width="802" alt="qq20161011-2 2x" src="https://cloud.githubusercontent.com/assets/4189632/19258147/264b6da6-8fa8-11e6-9ec2-c24ffbef6fdb.png">

**Comment by wwwjason1994** [comment]
i got it too on window

**Comment by kaiyes** [comment]
whats the status of this error ? My team mate has the same error in ubuntu while I don't have this in mac

**Comment by xubuhang** [comment]
I changed the command line like this.
<img width="573" alt="qq20161011-4 2x" src="https://cloud.githubusercontent.com/assets/4189632/19260928/4b82c21e-8fc0-11e6-94ec-f4df9c356046.png">

**Comment by abernix** [comment]
@kaiyes This issue was only opened 5 hours ago and there is not a status update, however, you posted in issue #7806 that your team mate was getting a _different_ issue than this.  What is the full, exact error that your teammate is getting?

**Comment by adrianciurdarean** [comment]
Hi,

I'm getting similar issues on **Windows 7**.

I got this one first when trying to install a particular package (meteorhacks:aggregate), then after a cleaning up meteor, I'm getting it for **mrt:later** used by the ecmascript compiler plugin.

Seems to be related to colons in file/directory names:

```
D:\.meteor\packages\ecmascript\0.5.8\plugin.compile-ecmascript.os\npm\node_modul
es\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'D:\.meteor\packages\mrt_later\1.
6.1\os\packages\mrt:later.js'
    at Error (native)
```

When the package is decompressed the colon gets replaced with an underscore, thus I have the following file on my machine:

`D:\.meteor\packages\mrt_later\1.6.1\os\packages\mrt_later.js`

but that one does not get picked up for some reason.

Thanks,
Adi

**Comment by kaiyes** [comment]
@abernix solved it by downgrading it to 1.4.1.1 but you are right. My error is different than this one. 

>  throw error;
      ^

> Error: ENOENT: no such file or directory, open '/tmp/mt-1ezmo9a/os.json'
    at Error (native)

**Comment by abernix** [comment]
For those experiencing this issue, it's seeming that this is happening because of a failing CDN provider, which is terminating connections before the downloads are done, and Meteor attempting to use those incomplete tar-balls.  You'll find a solution in https://github.com/meteor/meteor/issues/7806#issuecomment-253903512 (which is essentially the same issue) involving changing your `hosts` file.

Leaving this issue open until that is resolved.

**Comment by abernix** [comment]
Thanks for reporting this issue originally.  I'm going to close this as I'm confident that this is related to #7806.  I also believe the CDN issue may be resolved, but it not, please use the workaround here: https://github.com/meteor/meteor/issues/7806#issuecomment-254125662 and report back if it doesn't work (or if it fixes it for you!) :smile:
