### ISSUE TITLE
Beta.9 {Error: ENOENT: no such file or directory, open '/tmp/mt-194vpuv/os.json'}

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#7910]
meteor update --release 1.4.2-beta.9
/home/jk/.meteor/packages/meteor-tool/.1.4.1_2.g5mcbf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-194vpuv/os.json'
    at Error (native)

**Comment by abernix** [comment]
Duplicate of #7806.
