### ISSUE TITLE
Meteor/React rendering blank pages after accounts-base and mongo updates

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7912]
I'm running Meteor 1.4.1.2 with the following packages:

```
accounts-base@1.2.11
accounts-password@1.3.0
alanning:roles@1.2.15
aldeed:template-extension@4.0.0
allow-deny@1.0.5
amplify@1.0.0
autoupdate@1.2.11
babel-compiler@6.9.1_1
babel-runtime@0.1.11_1
babrahams:constellation@0.4.6
babrahams:editable-json@0.6.4
babrahams:temple@0.4.2
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.9
blaze-tools@1.0.10
boilerplate-generator@1.0.10
c9s:scss@3.8.1
caching-compiler@1.1.7_1
caching-html-compiler@1.0.7
callback-hook@1.0.9
check@1.2.3
coffeescript@1.1.4
constellation:autopublish@0.4.1
constellation:console@1.4.1
constellation:plugins@0.4.3
constellation:position@0.4.1
constellation:session@0.4.2
constellation:subscriptions@0.4.2
constellation:tiny@0.4.1
dburles:factory@1.1.0
dburles:mongo-collection-instances@0.3.5
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.6
ddp-rate-limiter@1.0.5
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.6
ecmascript@0.5.8_1
ecmascript-runtime@0.3.14_1
edgee:slingshot@0.7.1
ejson@1.0.12
email@1.1.17_1
es5-shim@4.6.14_1
fastclick@1.0.12
force-ssl@1.0.12
geojson-utils@1.0.9
gwendall:body-events@0.1.6
gwendall:session-json@0.1.7
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.9_1
hwillson:stub-collections@1.0.2
id-map@1.0.8
jagi:astronomy@2.1.4
jagi:astronomy-softremove-behavior@2.0.4
jagi:astronomy-timestamp-behavior@2.0.0
jquery@1.11.9
kadira:flow-router@2.12.1
lai:collection-extensions@0.2.1_1
lai:ddp-inspector@1.1.9
launch-screen@1.0.12
livedata@1.0.18
localstorage@1.0.11
logging@1.1.15_1
mdg:validated-method@1.1.0
mdg:validation-error@0.5.1
meteor@1.2.17_1
meteor-base@1.0.4
meteorhacks:picker@1.0.3
mikowals:batch-insert@1.1.13
minifier-css@1.2.14_1
minifier-js@1.2.14_1
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.7.6_1
modules-runtime@0.7.6_1
mongo@1.1.12_1
mongo-id@1.0.5
mousetrap:mousetrap@1.4.6_1
npm-bcrypt@0.9.1_1
npm-mongo@1.5.50
observe-sequence@1.0.12
ordered-dict@1.0.8
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.8.7
random@1.0.10
rate-limit@1.0.5
react-meteor-data@0.2.9
reactive-dict@1.1.8
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
reywood:publish-composite@1.4.2
routepolicy@1.0.11
service-configuration@1.0.10
session@1.1.6
sha@1.0.8
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.9
standard-minifier-css@1.2.1
standard-minifier-js@1.2.0_1
static-html@1.1.13
templating@1.1.14
templating-tools@1.0.5
tmeasday:check-npm-versions@0.2.0
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.0
u2622:persistent-session@0.4.4
ui@1.0.12
underscore@1.0.9
universe:i18n@1.9.0
universe:utilities@2.3.3
url@1.0.10
webapp@1.3.11_1
webapp-hashing@1.0.9
```

Of note are `accounts-base` and `mongo`. At their current versions above, everything is fine, but when I update them to 1.2.12_1 and 1.1.12_3 respectively, my app breaks and the page renders as blank (with the exception of Constellation). In the React DevTools, I can see my layout component (rendered by Flow Router) but it contains null.

I haven't had a chance to reproduce this yet, but things consistently break whenever I update, and are 100% fixed when I revert to the previous versions.

**Comment by ffxsam** [comment]
Same issue on a second project of mine. I did see some error about Mongo pool being destroyed.. or something. I can't get it now, every time I run my app and load it, I get a blank page just like on my other project. The new `mongo` update is totally broken. @benjamn

**Comment by robfallows** [comment]
Have you tried `meteor update --all-packages`?

**Comment by abernix** [comment]
My 1.4.1.2 is running fine with the latest versions of the packages.  The versions you mentioned are not the latest versions of those packages for the `meteor` that you are using;  `mongo@1.1.12_5` and `npm-mongo@2.2.10_1` are both out, newer, and compatible with your release.

Consider that those new packages have been out for 5+ days now a "totally broken" deployment would have likely been noticed already.  Please provide a reproduction when opening issues and don't just directly mention people when opening issues unless it's something they are particularly involved in already.  The person you're urgently mentioning is likely asleep right now, and not the only person who monitors these issues.  Every issue opened is emailed out to almost 2000 watchers who also might have input on the issue.

**Comment by ffxsam** [comment]
I apologize if I jumped the gun. Though something is definitely up since two unrelated projects are both completely failing. I noticed someone else +1'd my report so it's not just me.

I can try to put together a repro, but when the project in question is a 16,000 line application, I have a feeling that a test app that's a fraction in size and complexity won't reproduce the issue.

I'll get something put together when I get some spare time. At the moment I'm crunching on getting a major SaaS launched.

**Comment by abernix** [comment]
@ffxsam No worries.  I understand, and issues are always important (thank you for reporting serious problems, always).  There's still some value to this as other users can +1, as you said.  Just understand that there isn't much to do without a reproduction or any error message – simply rolling back the driver update could cause problems for other users who might have benefited from bug fixes.

Do make sure you're using the latest version (as @robfallows said, `meteor update --all-packages` or `meteor update mongo`) because as it is, `mongo@1.1.12_3` uses `npm-mongo@1.5.48_1` uses `mongodb@2.2.9` (NPM).  The newer `mongo@1.1.12_5` resolves to `mongodb@2.2.10` which [has quite a few bug fixes](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2210-2016-09-15)!

**Comment by ffxsam** [comment]
I also should've been clearer when I said "totally broken" :) I mean, it did strike me as odd that no one else had reported this. But the fact that it totally breaks both my apps is weird. I'm sure there are some package commonalities between the two though.

I totally understand the value of a reproduction. I figured I'd report it anyway just in case someone else had run into the problem, or maybe one of the contributors was aware of the issue.

I didn't even know about `--all-packages` until Rob mentioned it since `meteor help update` doesn't list it. I'll give that a shot now, and report back ASAP.

**Comment by ffxsam** [comment]
This is odd behavior. It didn't update to the version of `mongo` that you mentioned for some reason. And at the end, it recommended that I run `meteor update --all-packages` which I just ran.

```
$ meteor update --all-packages
This project is already at Meteor 1.4.1.2, the latest release.

Changes to your project's package version selections from updating package
versions:

accounts-base                upgraded from 1.2.11 to 1.2.12_1
autoupdate                   upgraded from 1.2.11 to 1.3.11
coffeescript                 upgraded from 1.1.4 to 1.2.4_2
ddp-client                   upgraded from 1.2.9 to 1.3.1_1
ddp-server                   upgraded from 1.2.10 to 1.3.10_1
http                         upgraded from 1.1.8 to 1.2.9_1
meteorhacks:kadira           upgraded from 2.30.0 to 2.30.2
mongo                        upgraded from 1.1.12_1 to 1.1.12_3
observe-sequence             upgraded from 1.0.12 to 1.0.13
templating                   upgraded from 1.1.14 to 1.2.15
templating-compiler          added, version 1.2.15
templating-runtime           added, version 1.2.15
tmeasday:check-npm-versions  upgraded from 0.2.0 to 0.3.1


The following top-level dependencies were not updated to the very latest
version available:
 * mongo 1.1.12_3 (1.1.12_5 is available)
 * standard-minifier-css 1.2.1 (1.3.1 is available)

Newer versions of the following indirect dependencies are available:
 * coffeescript 1.2.4_2 (1.11.1_1 is available)
 * npm-mongo 1.5.50 (2.2.10_1 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```

**Comment by abernix** [comment]
Try:

    meteor add mongo@1.1.12_5

And see what it tells you.

A bit strange though because I'm almost positive both `npm-mongo@2.2.10_1` and `mongo@1.1.12_5` were constrained to `meteor@1.2.17_1`, which is what you have in your `.meteor/versions` you pasted above.

**Comment by ffxsam** [comment]
Aha!

```
While selecting package versions:
error: Potentially incompatible change required to top-level dependency:
mikowals:batch-insert 1.1.9, was 1.1.13.
Constraints on package "mikowals:batch-insert":
```

It looks like `batch-insert` hasn't been updated since last September. 😖  I'll take it out and whip up my own solution. Let me try another update, and see if this fixes my app from bombing.

**Comment by ffxsam** [comment]
And this time I managed to see the server errors I missed last time:

```
I20161012-09:57:40.401(-7)? Exception in setInterval callback: MongoError: server instance pool was destroyed
I20161012-09:57:40.402(-7)?     at Object.Future.wait (/Users/samh/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:446:16)
I20161012-09:57:40.402(-7)?     at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
I20161012-09:57:40.403(-7)?     at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:771:49)
I20161012-09:57:40.403(-7)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20161012-09:57:40.403(-7)?     at AccountsServer.Ap._expireTokens (packages/accounts-base/accounts_server.js:1100:14)
I20161012-09:57:40.403(-7)?     at packages/accounts-base/accounts_server.js:1173:14
I20161012-09:57:40.403(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161012-09:57:40.404(-7)?     at packages/meteor/timers.js:6:1
I20161012-09:57:40.404(-7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20161012-09:57:40.404(-7)?     - - - - -
I20161012-09:57:40.404(-7)?     at Function.MongoError.create (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:29:11)
I20161012-09:57:40.405(-7)?     at basicWriteValidations (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:434:51)
I20161012-09:57:40.405(-7)?     at [object Object].Server.update (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:547:16)
I20161012-09:57:40.405(-7)?     at [object Object].Server.update (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/server.js:386:17)
I20161012-09:57:40.405(-7)?     at updateDocuments (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1041:19)
I20161012-09:57:40.405(-7)?     at [object Object].Collection.update (/Users/samh/.meteor/packages/npm-mongo/.1.5.50.1cgdd2e++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1080:44)
I20161012-09:57:40.405(-7)?     at MongoConnection._update (packages/mongo/mongo_driver.js:560:18)
I20161012-09:57:40.406(-7)?     at MongoConnection.kadira_MongoConnection_update [as _update] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:23:1)
I20161012-09:57:40.406(-7)?     at MongoConnection.<anonymous> (packages/meteor/helpers.js:118:1)
I20161012-09:57:40.406(-7)?     at MongoConnection.(anonymous function) (packages/mongo/mongo_driver.js:771:49)
I20161012-09:57:40.406(-7)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20161012-09:57:40.407(-7)?     at AccountsServer.Ap._expireTokens (packages/accounts-base/accounts_server.js:1100:14)
I20161012-09:57:40.407(-7)?     at packages/accounts-base/accounts_server.js:1173:14
I20161012-09:57:40.407(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161012-09:57:40.407(-7)?     at packages/meteor/timers.js:6:1
I20161012-09:57:40.408(-7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by ffxsam** [comment]
```
This project is already at Meteor 1.4.1.2, the latest release.

Changes to your project's package version selections from updating package
versions:

mongo       upgraded from 1.1.12_3 to 1.1.12_5
npm-mongo*  upgraded from 1.5.50 to 2.2.10_1
```

This seems to have fixed it!! @robfallows @abernix A thousand thank-yous.

@benan789 Heads up, in case you're still watching this.

**Comment by abernix** [comment]
> Aha!

Yeah, there's still some gotchas in the messaging.  There's an existing issue, I'm almost sure.  (Not in a place to search right now)

> And at the end, it recommended that I run meteor update --all-packages which I just ran.

Yeah, again, there is some confusing messaging here.

****
#7822 was the "pool instance destroyed" issue – fixed by the driver update, I believe.

Anyway, cheers!  Glad you've got it fixed! :smile:
