### ISSUE TITLE
Webapp not working in subdir behind reverse proxy

### ISSUE THREAD

**Issue by Huljo** [meteor/meteor#7916]
The webapp is not working in a subfolder behind nginx in my case.

I'm trying to install Rocket.chat in a subfolder but the webapp rejected the URL (ROOT_URL=http://www.domain.com/chat/) and throw "Unknown path" if I run nginx in front.

[The Rocket.chat issue](https://github.com/RocketChat/Rocket.Chat/issues/4546)

My nginx config (rocket.chat is running at localhost:3000) : 

````
    location /chat/ {
       proxy_pass          http://127.0.0.1:3000/;
    }
````

**Comment by abernix** [comment]
Have you tried passing `ROOT_URL` without the trailing slash?

    ROOT_URL=http://example.com/chat meteor

Realistically though, your Nginx configuration is a bit basic to truly work correctly and you're not accounting for a number of factors (websockets, missing `Host`, `X-Forwarded` headers, etc.).

I recommend taking a look additional parameters which are important in [this `nginx.conf`] (https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/nginx.conf) (a configuration used in the popular `mup` project) and also setting `HTTP_FORWARDED_COUNT=1` so Meteor is aware that it's in front of a Proxy.

**Comment by abernix** [comment]
Also, what is the output if you browse directly to your Meteor server, without the proxy, and run the following in the browser console?:

    JSON.stringify(__meteor_runtime_config__)

**Comment by Huljo** [comment]
Hi @abernix,
I removed the  trailing slash and updated my nginx conf : 
````
    location /chat/ {
     proxy_pass          http://127.0.0.1:3000/chat/; 

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
````

That solved the "Unknown path" but assets still all absolute URLed to '/'.
After a quick look at the webapp, its seems that the subdir is not passed to **WebAppInternals.setBundledJsCssPrefix** : 
_server/packages/webapp.js_
```
WebAppInternals.setBundledJsCssPrefix = function (prefix) {                                                         
  var self = this;                                                                                                  
  self.setBundledJsCssUrlRewriteHook(function (url) {                                                                
    console.log('Meteor config path:', __meteor_runtime_config__.ROOT_URL_PATH_PREFIX); // Meteor config path: /chat
    console.log('Passed path:', prefix); // Passed path: 
    return prefix + url;    // no prefix ...                                                                                         
  });                                                                                                               
};    
```
I need to manually add the prefix to get assets.

_console.log( JSON.stringify(__meteor_runtime_config__) )_ : 
```
{ meteorRelease: 'METEOR@1.4.1.2',
  meteorEnv: { NODE_ENV: 'production', TEST_METADATA: '{}' },
  PUBLIC_SETTINGS: {},
  ROOT_URL: 'http://localhost',
  ROOT_URL_PATH_PREFIX: '/chat',
  appId: '1d10m9yd7fq1hsv663c',
  accountsConfigCalled: true }
```

**Comment by abernix** [comment]
Glad that fixed it for you!  I would be curious to know if it was specifically the trailing slash though as that seems like something that doesn't (shouldn't) matter and should be fixed.

You don't need to call `WebAppInternals.setBundledJsCssPrefix` in order to deploy Meteor to a sub-directory.  In fact, you should NOT call it.  The [default implementation](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L39-L43) handles it for you.

Why did you think you needed to call that function?  It's meant to be used when you have all of your assets on a CDN, in which case you call it with the FULL URL (e.g. `https://mycdn.com/url/to/asset/dir`)

**Comment by Huljo** [comment]
It was good for nginx when I just added `/chat/` to the local adress (at the end of the `proxy_pass` value). Without this `__meteor_runtime_config__.ROOT_URL_PATH_PREFIX` was empty and the webapp throwing "Unknown path".

Concerning assets prefix, I used `WebAppInternals.setBundledJsCssPrefix` because that was the only way for me to add the prefix after tried a lot of possibilities. `bundledJsCssUrlRewriteHook` is not called in my case :
```
var bundledJsCssUrlRewriteHook = function bundledJsCssUrlRewriteHook(url) {
  console.log("I was called!"); // never displayed
  var bundledPrefix = __meteor_runtime_config__.ROOT_URL_PATH_PREFIX || '';                                          
  return bundledPrefix + url;
};    
```

**Comment by abernix** [comment]
I really don't think it's necessary for you to call `WebAppInternals.setBundledJsCssPrefix` at all in your case.  Try _not_ calling it at all.

**Comment by Huljo** [comment]
I am not calling it anymore.

**Comment by abernix** [comment]
Can you explain what asset prefix you're talking about?  CSS?  Images?  Links?  `script` tags?

**Comment by Huljo** [comment]
App css and js.
![assets](https://cloud.githubusercontent.com/assets/12231164/19350442/0fb32096-9158-11e6-86cf-21f4004849b9.jpg)

**Comment by abernix** [comment]
Something still doesn't seem to be right.  The port of the Meteor server is missing on that URL which means that the Nginx server must be cutting it off.  The proxy server must be re-writing the URL.  I don't think you should have `proxy_redirect` set to `off` in your `nginx.conf`; I would remove the `proxy_redirect` line.

Next would be to figure out what the `<script>` and `<link>` tags are _on the Meteor server itself_.  If you browse _directly_ to your Meteor server (on port `:3000`) and view the source, what do you see for those tags?

I see no reason why the default implementation couldn't be getting called: The [boilerplate template](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate_web.browser.html#L3) calls `bundledJsCssUrlRewriteHook` in the helper for the `<link>` and `<script>` tags.  It's [instantiated here](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L292-L320) and thus would call [this `bundledJsCssUrlRewriteHook` function](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L39-L44) which does use the `ROOT_URL_PATH_PREFIX` which as you pasted above is set in your `__meteor_runtime_config__`.

😕

**Comment by Huljo** [comment]
I removed the `proxy_redirect` line, nothing seems to change.

Thank you for explaining how boilerplate template implementation was made. :)

_view-source:http://localhost:3000/chat/_
```
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/a9678fe09ea06c808777bcd0ec9cf59aac340b6b.css?meteor_css_resource=true">  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/theme.css?12f173799a5d4cf4a7ccafbd0558b29e03332119">
[...]
<script type="text/javascript" src="/e5d4bffb9d9ac9fa2be0b3fa6a385473fe40b44b.js?meteor_js_resource=true"></script>
```

**Comment by abernix** [comment]
I just reproduced this on a new project and did not have this problem:

```sh
$ mkdir 7916
$ cd 7916/
$ meteor create --release 1.4.1.2 app
$ cd app/
$ meteor npm install
$ meteor
# works... ^C
$ meteor build --directory ../build
$ cd ../build/bundle/programs/server
$ npm install
$ cd ../..
$ PORT=3000 MONGO_URL=mongodb://localhost:27017/funfun ROOT_URL=http://localhost:3000/haaaha node main.js
```

![image](https://cloud.githubusercontent.com/assets/841294/19353042/cad4b51c-916a-11e6-839c-2f808cf05b1b.png)

```
> [__meteor_runtime_config__.ROOT_URL, __meteor_runtime_config__.ROOT_URL_PATH_PREFIX]
< ["http://localhost:3000/haaaha", "/haaaha"]
```

**Comment by Huljo** [comment]
![testm](https://cloud.githubusercontent.com/assets/12231164/19353911/309576f8-9165-11e6-9346-2f236328c05b.jpg)

It works fine for me. So I guess the problem is coming from Rocket.chat itself... 
Like I said, `bundledJsCssUrlRewriteHook` is not even called, but `setBundledJsCssPrefix` is... Without any changes on Rocket.chat build. What can be the reason that the webapp is isn't calling `bundledJsCssUrlRewriteHook` ?

**Comment by abernix** [comment]
Ah, so it's with Rocket.Chat!

The only reason that the default `bundledJsCssUrlRewriteHook` wouldn't be getting called is if something else is calling `setBundledJsCssPrefix`.  If you're not personally calling `setBundledJsCssPrefix` then they must be...

Their source seems to have this:

https://github.com/RocketChat/Rocket.Chat/blob/744d25a6264c0daf3c3c357fc65754010c4fa476/packages/rocketchat-lib/server/startup/settingsOnLoadCdnPrefix.coffee

Maybe you're setting `CDN_PREFIX` in your settings?  Or maybe that code just doesn't work as expected.

I would probably open an issue with Rocket.Chat or use that as a starting point to solve it yourself.  Everything on the Meteor side of things appears to be working okay.

**Comment by Huljo** [comment]
I see now, thank you very much for your help @abernix, I think you found the problem with `CDN_PREFIX`.
I'll update the Rocket.Chat issue and continue to try to solve it here.
