### ISSUE TITLE
Blaze: helpers do not work for <body>

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#7917]
I have `<body class="{{bodyClasses}}">...</body>` in code, and it shows exactly `<body class="{{bodyClasses}}">...</body>` in the browser without replacing `bodyClasses`.

I have tried `bodyClasses` as both a global helper and a `Template.body` helper, same result.

**Comment by laosb** [comment]
Blaze issues should be in meteor/blaze. Would you like move this to meteor/blaze and close this?

**Comment by WayneUong** [comment]
just did, thank you.
