### ISSUE TITLE
Win10 error when running any Meteor commands - CMD: "Node.js: Server-side Javascript has stopped working", Git Bash: "Segmentation Fault"

### ISSUE THREAD

**Issue by bov188** [meteor/meteor#7922]
Hi, I am trying to install Meteor on Windows 10 (64-bit, Version 1607, OS Build: 14393.321).

However, whenever I try to use any meteor command in CMD, Powershell, or Git Bash I receive the following errors:

CMD and PowerShell (Elevated and normal user):

![capture](https://cloud.githubusercontent.com/assets/18218561/19358601/779eea3c-9144-11e6-9ecb-054fab037b18.PNG)

I also tried using Git Bash using the meteor.bat command (Elevated and normal user):
```
DESKTOP-VPQMC35~
$ meteor.bat
Segmentation fault

DESKTOP-VPQMC35~
$ meteor.bat --version
Segmentation fault

DESKTOP-VPQMC35~
$ meteor.bat create myapp
Segmentation fault
```
I then added meteor to the Git Bash path following the directions [here](https://forums.meteor.com/t/how-to-config-meteor-command-in-git-bash-on-window-7/9703), and I receive the following errors

Git Bash (Elevated and normal user):
``````
DESKTOP-VPQMC35~
$ meteor --version
/c/Users/Ab/AppData/Local/.meteor/meteor: line 2:  3712 Segmentation fault      cmd //c "$0.bat" "$@"

DESKTOP-VPQMC35~
$ meteor --version
/c/Users/Ab/AppData/Local/.meteor/meteor: line 2:   428 Segmentation fault      cmd //c "$0.bat" "$@"
DESKTOP-VPQMC35~
$ meteor --version
/c/Users/Ab/AppData/Local/.meteor/meteor: line 2:  6552 Segmentation fault      cmd //c "$0.bat" "$@"

DESKTOP-VPQMC35~
$ meteor
/c/Users/Ab/AppData/Local/.meteor/meteor: line 2:  7424 Segmentation fault      cmd //c "$0.bat" "$@"
``````

So after going through some of the issues I found this suggestion made by @abernix (Thank you!)

> Uninstall Meteor from:
- Win10: Settings > System > Apps & features > Meteor > Uninstall
- Win7: Control Panel > Programs > Programs and Features > Meteor > Uninstall
- Using Windows Explorer, delete the .meteor folder from %LOCALAPPDATA% completely. If you are unable to delete it due to long file-path errors, please try using the 7-zip File Explorer application to do it instead.
- Install fresh 1.4.1.2 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
- Restart (This is very important)
- Open Command Prompt and type meteor --version to confirm it's working.

After repeating those steps twice I am still getting the aforementioned errors.

Any help or suggestions would be greatly appreciated!

```
DESKTOP-VPQMC35~
$ git --version
git version 2.10.1.windows.1

DESKTOP-VPQMC35~
$ node -v
v4.6.0

DESKTOP-VPQMC35~
$ npm -v
3.10.8
```
I should note that during my first 2 attempts at install / reinstalling, I was using Node 6.8.  I uninstalled and downgraded to 4.6 to see if that fixed the issues, but no luck

**Comment by matthewshirley** [comment]
Just to double check, are you using InstallMeteor.exe or compiling from the devel source?

**Comment by bov188** [comment]
@matthewshirley Yes I used the InstallMeteor.exe from the Meteor website.

However, today when I tried to install heroku-cli I was getting the same exact errors (for Git Bash and CMD).  

So I think it is safe to say that this is an issue with my machine.

Closing this issue.
