### ISSUE TITLE
Build tool optimization for server only packages

### ISSUE THREAD

**Issue by AirBorne04** [meteor/meteor#7927]
I noticed that server only packages are still represented on the client side build with a file which is basically empty, it is also still present in the production build and therefore adds up in data transfer to the client and to the browser cpu load.

E.g. the shell-server package produces this

```
//////////////////////////////////////////////////////////////////////////
//                                                                      //
// This is a generated file. You can view the original                  //
// source in your browser if your browser supports source maps.         //
// Source maps are supported by all recent versions of Chrome, Safari,  //
// and Firefox, and by Internet Explorer 11.                            //
//                                                                      //
//////////////////////////////////////////////////////////////////////////


(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;



/* Exports */
if (typeof Package === 'undefined') Package = {};
Package['shell-server'] = {};

})();
```

where of the function part is still present in production. Shouldn't the production build get rid of this parts, i know it is a relatively low amount of data, but it is adding up the larger the project gets, furthermore the dev-build is also including those which is adding load on builder and again on the browser in dev too.

**Comment by benjamn** [comment]
I would take a pull request for this! Check out tools/isobuild/linker.js for the relevant code. You'll also want to run meteor from a checkout to test any changes (see the "Slow Start" section of https://github.com/meteor/meteor/blob/devel/README.md).

**Comment by AirBorne04** [comment]
Hi, i can sure work on this and make a proposal. Thank you for the hints on where to get started. I had a look at the linker and i think that the proper place for the edits would be the very last function in the linker js.
I am thinking along the lines of
```
if (files.source.length == 0 && declaredExports.length == 0) {
  return {
    source: '',
    sourcePath: file.sourcePath,
    servePath: file.servePath
  }
}
```

I was not sure if there is a way of removing the file altogether from the build (returning empty content makes an empty file as expected). Would that be a better place in the full link or in the pre link?

I will do a bit more testing and create a pr.
