### ISSUE TITLE
Meteor-tool 1.3.2.4 unreachable

### ISSUE THREAD

**Issue by Mymetique** [meteor/meteor#7938]
Hello,

I'm trying to install a brand new meteor v.1.3.2.4 application using metor  install with https://install.meteor.com/ | sh. It seems I can't download Meteor-tool 1.3.2.4 anymore. 

Thanks.

**Comment by macrozone** [comment]
I have a similar problem with an older app. I reinstalled meteor, but now it tries to download packages for two days now in the older app...

**Comment by matthewshirley** [comment]
@Mymetique can you clarify what you mean in regards to "I can't download Meteor-tool 1.3.2.4 anymore"? 

I changed the RELEASE variable in the install script to 1.3.2.4 and had no issues downloading on both x64 and x86 platforms. You can also install another version of Meteor by using:

`meteor --release VERSION`

You can also download the [1.3.2.4 source](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.3.2.4).

**Comment by Mymetique** [comment]
Well, I have a script which installs meteor into a docker instance. Meteor is downloaded and installed into docker with https://install.meteor.com/ | sh. Since I can't chose the version from there, it's the latest version downloaded first. Then I run meteor with a copy of my working project which contains the meteor version, meteor starts to download the right version which is 1.3.2.4. I had no issue with this until today. Now it is slowly loading (expected time 300s approx) but it fails during the process saying some file doesn't exist in /tmp. Is there any chance that a previous interrupted download can be the cause ? or maybe there was a temporary issue with the metepr server ? I can't test it right now, will do it tomorrow.
Thanks for your time

**Comment by abernix** [comment]
See #7806 for the work around to the problem.

As another workaround, you actually *can* select the release from the `curl` install command:

    https://install.meteor.com/?release=1.3.2.4 | sh

This should be significantly quicker in your `docker` case and avoid the #7806 problem too.
