### ISSUE TITLE
"You are attempting to run Meteor as the 'root' user"

### ISSUE THREAD

**Issue by mwarren2** [meteor/meteor#7939]
Just updated to Meteor version 1.4.2-rc.0, on Mac Sierra.

I have a very simple meteor app, and the server part (which is giving me the message) runs in docker. The client is a cordova app.

As far as I can see, nothing, apart from updating Meteor, has changed.

I've checked permissions of my `.meteor` folder, and just for total safety ran `chown` to make double sure that all folders in my app were in my normal user name. I haven't changed anything recently in my code. It's been running fine for several weeks.

And yet I'm being told I'm trying to run it as root, which is not the case, and my server exits.

The strange part is that the first time I ran it after updating meteor I got the dreaded #7806 :

> [1.4.x] ENOENT No such file or directory, open ... tmp ... /os.json #7806

So in response to this I did the workaround and then got  "You are attempting to run Meteor as the 'root' user", which is now the case even if I remove the workaround for #7806

Not only these two happenings, it's also giving 13 errors when I try to build for IOS in XCode.
Let's just say it hasn't been a nice day.

Any help or ideas would be greatly appreciated for the running as root problem. Thankyou.

**Comment by mwarren2** [comment]
Wait a minute, it's running in docker. 
- Therefore it may be running as root .., which shouldn't actually matter, it's in its own container by itself. 

However I will close this while I look into how I'm running this in docker, and how I can solve this.

**Comment by abernix** [comment]
(Ignoring the "No such file or directory" error, which is in-fact related to the issue you referenced)

That is a new feature put in place in Meteor 1.4.2 to prevent you from running the `meteor` tool as root because it regularly causes problems with permissions.  See #7821 and related issues.

The rest of the message goes on to explain why and states to run it with `--unsafe-perm` if this is what you're intending to do.  Do you think the message could be more clear?

Semi-related: You should not use the `meteor` tool to run your app in production.  It will be _dramatically_ slower, at the very least.  `meteor build` is what you want to use for production as it will build a `node` project which you can deploy.

**Comment by mwarren2** [comment]
Ah, it's the fact that I run `meteor` in development as root that's giving the message.
No, I don't use it in production.

I have a setup in docker in development that is as similar as possible to the one in production, for the usual reasons - so as not to run into "Oh, but it worked fine in development" scenarios.

So I use meteor in docker in development - and I get hot code reload while I'm developing - and node in production.

With hindsight and your explanation I can see better what the message is saying, and it's not easy to improve. Perhaps the word Meteor would be better in lower-case and in inverted commas as we're talking about the meteor command and not the Meteor framework.

As in: **You are attempting to run 'meteor' as the "root" user.**

I see that Docker has added the possibility of not running as root, and I will work on that basis.
Thankyou for the explanation.

**Comment by abernix** [comment]
Thanks for the suggestion!  Will consider changing the wording in the coming days as more people react to it. :)

**Comment by leetschau** [comment]
I built a meteor app with `meteor build` in a docker container, and met "You have run Meteor as root ..." error. Then the whole build process failed.
IMHO for `meteor build` a warning is enough, making whole build failed is unnecessary and annoying.

**Comment by cluxter** [comment]
I guess you are using a deprecated Docker image.
Use this one instead:

https://github.com/jshimko/meteor-launchpad

**Comment by vmatekole** [comment]
Hi! this issue is blocking development and deployment on our side as we use Docker in dev and production. What is the work around? as running --unsafe-perm also halts our CI process, as it asks for .meteor to be chown'ed.

**Comment by abernix** [comment]
@vmatekole See #7959 for the work-arounds.

I would point out though that the message about asking for `.meteor` to be change-ownered is just a message, and not an error – it shouldn't be blocking anything.

**Comment by vmatekole** [comment]
@abernix unfortunately, it halts the build process in Docker. Has anyone in the Meteor core team actually tested these breaking changes with Docker. We have a very simple Dockerfile:

```
FROM node:4.5
ENV METEOR_NO_RELEASE_CHECK=true
RUN curl https://install.meteor.com/ | sh
COPY . /app/seedbloom/src
WORKDIR /app/seedbloom/src
RUN meteor npm install
RUN meteor build /app/seedbloom/build --directory --architecture os.linux.x86_64
WORKDIR /app/seedbloom/build/bundle/programs/server
RUN npm install
CMD METEOR_SETTINGS=$(cat /app/seedbloom/src/settings.json) node /app/seedbloom/build/bundle/main.js
EXPOSE 3000
```

**Comment by abernix** [comment]
@vmatekole You're running into #7959.  Again, take a look at that issue as there is a known error and multiple work-arounds.  The best work-around is to not run Meteor as root, even if you're inside a Docker container.

**Comment by lang100** [comment]
@mwarren2,
did u solve the problem?
can you share the solution?
having the same problem and can't seem to solve it...

**Comment by vmatekole** [comment]
@mwarren2 

Example working Docker image — use it across multiple projects. So far it has been suffice for my needs. Some room for improvement in terms of clean-up of superfluous files after build.

FROM node:4.5
RUN useradd meteoruser
RUN mkdir /home/meteoruser
RUN chown meteoruser /home/meteoruser
USER root
COPY . /app/src
WORKDIR /app/src
RUN chown -R meteoruser /app/*
RUN npm install --global node-pre-gyp
USER meteoruser
RUN curl https://install.meteor.com | sh
RUN npm install --production
RUN /home/meteoruser/.meteor/meteor build /app/build --directory  --architecture os.linux.x86_64
WORKDIR /app/build/bundle
RUN cd programs/server && npm install
CMD METEOR_SETTINGS=$(cat /app/src/settings.json) node /app/build/bundle/main.js
EXPOSE 3000
