### ISSUE TITLE
Unable to execute meteor command

### ISSUE THREAD

**Issue by gauravbhusare** [meteor/meteor#7948]
Meteor Version 1.4.1.2
Packages used are 

	"babel-plugin-transform-class-properties": "^6.16.0",
	"bcrypt": "^0.8.7",
	"bluebird": "^3.4.6",
	"bootstrap": "^3.3.7",
	"classnames": "^2.2.5",
	"immutable": "^3.8.1",
	"jquery": "^3.1.1",
	"md5": "^2.1.0",
	"meteor-node-stubs": "^0.2.3",
	"node-uuid": "^1.4.7",
	"react": "^15.3.2",
	"react-addons-css-transition-group": "^15.3.2",
	"react-addons-pure-render-mixin": "^15.2.0",
	"react-bootstrap": "^0.30.5",
	"react-dom": "^15.3.2",
	"react-komposer": "^1.13.1",
	"react-redux": "^4.4.5",
	"react-router": "^2.8.1",
	"react-router-redux": "^4.0.6",
	"redux": "^3.6.0",
	"redux-devtools": "^3.3.1",
	"redux-devtools-dock-monitor": "^1.1.1",
	"redux-devtools-log-monitor": "^1.0.11",
	"redux-form": "^6.1.0",
	"redux-logger": "^2.7.0",
	"redux-promise": "^0.5.3",
	"redux-thunk": "^2.1.0",
	"shortid": "^2.2.6",
	"underscore": "^1.8.3",
	"uuid": "^2.0.3",
	"victory": "^0.13.0"

dev dependencies

	"chai": "^3.5.0",
	"enzyme": "^2.4.1",
	"react-addons-test-utils": "^15.3.0",
	"redux-devtools": "^3.3.1",
	"redux-devtools-dock-monitor": "^1.1.1",
	"redux-devtools-log-monitor": "^1.0.11",
	"redux-mock-store": "^1.2.0"

Whenever I try to execute meteor command it show following error

`C:\Users\ADMIN\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.
js:165
     throw error;`
 
I don,t  know how to reproduce this issue

I tried to completely remove and reinstall meteor, but still no effect. Please help me solving this issue.

**Comment by bedorn** [comment]
try meteor reset, worked for me

**Comment by abernix** [comment]
Is there any more to the error message after the `throw error`?  Try a `meteor reset` as recommended above.   At the very least, please provide a minimal reproduction repo to help debug the issue.  See [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for what is expected.

**Comment by gauravbhusare** [comment]
It started working itself after few tries of completely uninstalling and installing meteor again.
