### ISSUE TITLE
Remove or separate emailing from Accounts-package

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#7949]
Currently there is no (sensible) way to use the  `Accounts`-packages without also using the built-in emailing features. This is the case for example with `Accounts.sendVerificationEmail`, `Accounts.sendResetPasswordEmail` and `Accounts.sendEnrollmentEmail`.

I already tried discussing this in Meteor Forums, with a handful of replies describing the different hacks people have come up with to fix the issue.
### What's wrong with the emailing?
1. SMTP endpoint has to be used
2. The email contents have to be generated, customized or stored in-app
3. No mechanism provided to personalize the email headers ([we only have](https://docs.meteor.com/api/passwords.html#Accounts-emailTemplates) `from`, `subject`, `text`, `html`)
4. Apparently security isn't really straightforward
5. We don't really know if the email has succesfully been sent
### Why is this bad?

**Point 1** is bad because there's many benefits to using a REST API instead of plain-old SMTP.

**Point 2** is bad because it's a lot easier to handle the templates else where by people who do not need to understand Meteor or Javascript

**Point 3** is bad because, for example, attaching a `to`\- header field with personalized data like _Awesome User a.user@gmail.com_ to the mail increases deliverability and reduces chance of being caught by spam filters.

**Point 4** is just bad. Apparently the DDP rate limiter fixes some of the issues, but I have not investigated this myself: it has been discussed here: #4673

**Point 5** is obvious - we don't get any confirmation of the mail being accepted for delivery, do we?
### How to improve things

I suggest that there would be a way to use the token creation and handling from `Accounts`-packages and handle the emailing part manually. All we need are the tokens, right?

If somebody wants to use the Meteor's Email-feature, fine, but if somebody doesn't why force them?

It probably took me longer to write this issue than implement my own token creation function, but I still thought this would be a welcome change to the `Accounts`-packages and probably really easy to implement?

**Comment by abernix** [comment]
Thanks for opening this feature request!  I don't have much experience with this side of the `accounts` packages but this sounds like a good idea.  Out of curiosity, where was the post on the forums about this?  Also, is this something you'd be willing to tackle?  I'm not intimately familiar with what this would entail, but if some sort of backwards compatible (this is super important for accounts) proposal could be put together I think this would be a welcome addition.  Maybe get some of the participants from the forum post engaged in speccing this out?

**Comment by mitar** [comment]
I think #8065 and #8038 should address some of your concerns?

**Comment by arggh** [comment]
> I think #8065 and #8038 should address some of your concerns?

Seems though, there is still no way to skip `Email.send` and intercept the flow at that point?

**Comment by mitar** [comment]
The proposed way will be to split e-mail preparation from sending e-mails. So what you can do then is prepare e-mail, but use REST API for example to send it instead.

**Comment by abernix** [comment]
@arggh The proposal in #8065 would provide exactly what you're asking.  Essentially, you would use your own send method:

```js
function sendVerifyEmail(userId, emailAddress) {
  // Generate the token (and URL using the token) necessary.
  const { user, token, url } = Accounts.generateVerification({userId, emailAddress});
  // A function that generates an email from a template.  Would need to return `text`, `html`, `subject`, `to`, etc.
  const options = generateEmailOptions({ user, emailAddress, url }); 
  // Send through your own way!
  YourMailProviderApi.send(options); // Or send through eFax! :)
}
```

**Comment by arggh** [comment]
@abernix Then this would be a most welcome change. I just wrote a custom flow to handle these emails and moved on, which is why this issue has completely dropped of my radar.

I'll follow up on #8065 and close this when it's merged.

**Comment by hwillson** [comment]
I believe PR https://github.com/meteor/meteor/pull/8207 will address this (and is very close to being merged). Closing for now - thanks!
