### ISSUE TITLE
[1.4.1.x] Assets are not updated after build on the client side

### ISSUE THREAD

**Issue by pletinsky** [meteor/meteor#7950]
Meteor version: 1.4.1.2
Platform: Windows 10
### Preconditions:
- I use custom build plugin based on the "babel-compiler".
- It worked fine using some times ago (initial 1.4 versions).
- I have code to add static asset:

`inputFile.addAsset({
                path: adaptPath(outPath),
                data: fs.readFileSync(sourcePath)
            });
`

_inputFile - it's some base file for adding asset
sourcePath - it's a path of source js asset
outPath - it's a destination path of my js asset_
### Steps:
- I change the javascript file (it's an asset file added by the code from precondition)
### Expected result:
- The browser is refreshed after build
- New version of js file is working through the web browser
- Actual version of the asset has been added to the both out locations:
  _.meteor/local/build/programs/server/assets/packages/[my package]/[file path]_
  _.meteor/local/build/programs/web.browser/packages/[my package]/[file path]_
### Actual result:
- The browser is not refreshed after build
- New version of code does not work in the web browser (only the initial old version of the code)
- The file _.meteor/.../server/..._ is updated correctly, but the browser version _.meteor/.../web.browser/..._ was not updated.

This problem is reproducible. So you can perform  a lot of changes and the behavior is the same.
It's still first version of the asset file in the browser.

The problem is fixed after change my build plugin (the file that is registered as _Package.registerBuildPlugin_). And expected behavior is ok after next builds.

So I have a horrible workaround: update the build plugin after running IDE.

It looks like a problem with caching of output build files for the client side of meteor (cause the server asset file is fine).

I am ready to write any additional information about the problem.

**Comment by abernix** [comment]
It may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  Then provide a simple instruction of how to use it, like: "Change the contents of client/file.js to something else", then "check the browser console for this".

Also, please find exactly which version of Meteor this last worked in.   You can use `meteor --release <version_number>` to use a specific previous version and you can find the list of versions in the [`History.md` for this project](https://github.com/meteor/meteor/blob/devel/History.md).

Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by hwillson** [comment]
Closing this off as we haven't heard back about a reproduction showing this issue. Thanks for posting this originally!
