### ISSUE TITLE
Cant`t update to 1.4.1.3

### ISSUE THREAD

**Issue by RWizard** [meteor/meteor#7952]
osx Sierra
==========================
.meteor/packages/meteor-tool/.1.4.1_2.1mw6om++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/_t/h_m8nmq17hn10s6jmd2rqn480000gn/T/mt-1lq7an/os.json'
    at Error (native)

**Comment by Deadly0** [comment]
@RWizard look at this comment https://github.com/meteor/meteor/issues/7806#issuecomment-254125662

**Comment by RWizard** [comment]
Thx!
