### ISSUE TITLE
Logo license

### ISSUE THREAD

**Issue by mgibas** [meteor/meteor#7957]
Can you clarify on logo license ?

**Comment by abernix** [comment]
@theadactyl Would you have any insight on this? 🙏

**Comment by theadactyl** [comment]
@mgibas can you further describe how you intend to use this?

**Comment by abernix** [comment]
@mgibas Please clarify if you have some time.  It would be nice to know where you'd be interested in using it.

But that being said, something along the lines of publishing a license or usage guidelines might be handy for some, @theadactyl.

Some examples:
* Dropbox: https://www.dropbox.com/branding
* Redux: https://github.com/reactjs/redux/blob/master/LICENSE-logo.md
* https://opensource.org/logo-usage-guidelines

This would allow easy things like "Powered by Meteor" without concern about logo licensing (when used appropriately, obviously).

In the case above, it appears that this was intended to be a part of a "dev stickers" project, but I could see it including options like [Font Awesome Brands](http://fontawesome.io/icons/#brand) too.

**Comment by mgibas** [comment]
I would like to use it in iMessage stickers pack:
https://appsto.re/us/NPjFfb.i

**Comment by ramezrafla** [comment]
Sorry to resurrect this, have we reached conclusion?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Logo%20license&body=Migrated%20from:%20meteor/meteor%237957) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
Not sure if this is feature request, really. @hwillson?

**Comment by hwillson** [comment]
I wasn't sure if it was either @mitar, but I dropped the migration message here anyways (since it was already marked as a `feature`). This is likely better tracked internally at MDG. I guess it could be a feature if the logo license ends up getting added to the repo somewhere though.

**Comment by mitar** [comment]
Let me then move it to the repo. But I think the best way to resolve this is to really do it internally in MDG. Outside contributors cannot really do anything here.
