### ISSUE TITLE
Database may flap on client if server is starting

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#796]
Here's an app that inserts into a collection on client startup and displays the count:

https://github.com/dgreensp/public/tree/master/players

Sometimes the count goes 0, 1, 0, N -- that is, the insert is reflected locally, and then the database flaps.  This only seems to happen when the server is starting, e.g. on hot reload, and then only sometimes, with multiple tabs seemingly making it more likely to happen.  It is very easy to reproduce using hot reload, especially with two tabs.

It would be interesting to know what's going on here.

See: [(meteor-talk) Are Collections wiped briefly once the server returns the subscription?](https://groups.google.com/d/msg/meteor-talk/xr2kUuVYgKw/DOBfZ9yQQ3IJ)

**Comment by hwillson** [comment]
Almost 4 years have passed since this issue was created, and a lot of the Meteor codebase has changed since. Given the lack of interest/activity on this issue in quite some time, I'll close it off. Thanks!
