### ISSUE TITLE
can't update to 1.4.2 (Mac)

### ISSUE THREAD

**Issue by zhe1ka** [meteor/meteor#7966]
Hello!
When I tried to update the meteor to version 1.4.2 I had got a problem

<img width="638" alt="2016-10-26 12 16 18" src="https://cloud.githubusercontent.com/assets/6460571/19720252/0f037d9e-9b76-11e6-84b4-14c86a676b4e.png">

at first I updated all packages which are in requirement

<img width="634" alt="2016-10-26 12 18 54" src="https://cloud.githubusercontent.com/assets/6460571/19720338/65e06488-9b76-11e6-970a-dbb2f7bb0a17.png">

what do I do incorrect?

**Comment by aboire** [comment]
look here  https://github.com/meteor/meteor/issues/7806
(export METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net)

**Comment by zhe1ka** [comment]
@aboire thanks) it helped me)
