### ISSUE TITLE
[1.4.2] Meteor mobile app rejected by Apple for not supporting IPv6

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#7969]
Just received this bug on my most recent App Store submisison:

```
Thank you for your response and response. Upon further review, we discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.1 on Wi-Fi connected to an IPv6 network.

Specifically, we were unable to login to your app due to the “No Internet Connection” error message. We've attached screenshot(s) for your reference.

Next Steps

Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue(s). For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue(s).

Resources

For information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and About Networking
```

I've uninstalled plugins, tested, tried to diagnose... no luck. It seems this is a fairly new requirement by Apple from June, however this is the first submission I've had which was actually flagged/rejected on this basis. It also happens with Meteor 1.4.1.

This is easily reproducible by following the instructions at http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/

An easy thing to test would be for `Meteor.status().status`, should equal `connected`, but instead equals `waiting`.

**Comment by abernix** [comment]
I wonder if this is related to:

https://stackoverflow.com/questions/37605742/about-ios-ipv6-network-with-ionic-framework/37896631#37896631

which recommends:

> https://github.com/wymsee/cordova-HTTP

Additionally, Meteor 1.4.2 has some significant Cordova updates that might help here?:

From the `History.md`:
> The cordova-lib npm package has been updated to 6.3.1, along with cordova-android (5.2.2) and cordova-ios (4.2.1), and various plugins.

Also possibly helpful, and related to your previous question about IPv6,  maybe check out [this article](http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/).

**Comment by markoshust** [comment]
@abernix thank you. If the cordovaHTTP plugin would work that would be great, but how would I go about implementing it into Meteor (or is that a backend meteor update that is needed?).

@martijnwalraven have you run into any of these issues since you are the Meteor mobile guru? Apple refuses to pass my app through the app store until it works on IPv6 :(

**Comment by abernix** [comment]
@markoshust Per [these instructions in the Meteor Guide](https://guide.meteor.com/mobile.html#installing-plugins), you could try installing that package with:

    meteor add cordova:cordova-plugin-http@1.2.0

I can't say if it would fix your problem, but those steps in that article on testing IPv6 might come in handy and maybe you can verify if the package helps fix it.  There might be other underlying issues though, which I'm not currently aware of.

**Comment by markoshust** [comment]
@abernix just installing that plugin doesn't seem to do anything. It appears that plugin just makes a `cordovaHTTP` global available, but then you need to do something with it. The problem is that I'm not making any http requests -- I'm using all of Meteor's built-in call and subscribe methods.

I can test under IPv6 using the link above (http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/), however I have no clue how to fix this. At first I thought this was possibly related to my production hosting environment, but things don't work in a localhost environment either.

**Comment by markoshust** [comment]
is there a content security policy needed for IPv6? i noticed that when i remove `127.0.0.1:*` from my content security policy sources, i get a similar result on IPv4, in which it doesn't connect to the server.

**Comment by markoshust** [comment]
So, I believe I found the issue. This was a weird/obscure one.

In mobile-config.js, I had these lines:
```
-App.accessRule('https://192.168.1.66:*');
-App.accessRule('wss://192.168.1.66:*');
-App.accessRule('ws://192.168.1.66:*');
```

and meta tag for CSP read:
```
   <meta
     http-equiv="Content-Security-Policy"
    content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: 127.0.0.1:* http://192.168.1.66:* wss://192.168.1.66:* ws://192.168.1.66:* https://*.mydomain.com wss://*.mydomain.com:* ws://*.mydomain.com:*;"
   >
```

Once I removed all of the entries/references to `192.168.1.66`, everything starts to work on IPv6. Apparently the CSP tags referencing an IPv4 address make a connection of IPv6 to fail.

👊

**Comment by vaidyaanand** [comment]
I have the same problem. I have put my app for the review on test flight but it is rejected due to ipv6 problem. Does anyone have the solution ???

**Comment by abernix** [comment]
@vaidyaanand Are you currently making references to IPv4 addresses (like 192.168.0.1, 10.0.0.1, 216.55.1.1, etc.) or API endpoints in your application which do not support IPv6?  To my knowledge this is still not an issue of Meteor or Cordova but rather the way you make HTTP requests (or configure HTTP requests) within your application.
