### ISSUE TITLE
1.4.2 regression: files under programs/server/npm/node_modules/meteor in bundles are read-only

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#7974]
This leads to some problems, eg with phantomjs-prebuilt which overwrites one of its files (lib/location.js) at rebuild time.

**Comment by benjamn** [comment]
I'm pretty sure [this commit](https://github.com/meteor/meteor/commit/8e57ecb7318ee98dbc00d3228cb2a2fcddc18703) is the culprit, since [this line](https://github.com/meteor/meteor/blob/e462cf7133f731bc929ce5f16d8676b371996077/tools/fs/files.js#L601) is no longer involved.

**Comment by glasser** [comment]
Good catch! That's definitely it.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.4.2.1-beta.0` in your app directory.

**Comment by benjamn** [comment]
Closing now because this seems to be fixed in my tests, but of course feel free to reopen if you discover otherwise!

**Comment by harveysanders** [comment]
I just ran into this problem too. I upgraded to 1.4.2.1-beta.1 and now I'm getting this error from meteor on my local machine and the deployment server
```
/project/.meteor/local/build/programs/server/boot.js:348
 }).run();
    ^
 
 Error: Cannot find module '../core-js/symbol/iterator'
     at require (packages/modules-runtime.js:109:19)
     at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (packages/modules.js:351:17)
     at fileEvaluate (packages/modules-runtime.js:181:9)
     at Module.require (packages/modules-runtime.js:106:16)
     at Module.Mp.import (/global/.meteor/packages/modules/.0.7.7.jvu3qu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/project/.meteor/local/build/programs/server/packages/webapp.js:33:26)
at fileEvaluate (packages/modules-runtime.js:181:9)
at require (packages/modules-runtime.js:106:16)
at /project/.meteor/local/build/programs/server/packages/webapp.js:842:1
at /project/.meteor/local/build/programs/server/packages/webapp.js:855:3
```

**Comment by abernix** [comment]
@harveysanders This is a different error which *did* exist but the version you're using (beta.1) is no longer the most recent.  Meteor 1.4.2.1-rc.1 is out now, so please try that instead:

    meteor update --release 1.4.2.1-rc.1
    meteor npm install babel-runtime --save

I believe that will fix your problem.

**Comment by snamoah** [comment]
Had the same error on meteor 1.4.2.3. Got mine working by installing babel-runtime without version constraint
```
meteor npm install babel-runtime --save
```
