### ISSUE TITLE
[1.4.x] Weird ReactiveVar/Tracker delay occurring

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#7976]
I've had this issue since 1.4.1.2 at least.

https://forums.meteor.com/t/strange-behavior-with-a-long-delay-before-container-recognizes-reactive-data-change/30270

I'm pretty desperate to fix this, so I'm posting here in the hopes that someone who knows the Meteor code well can help me pinpoint why this delay is occurring. The reproduction project worked perfectly. I've ruled out some stuff:
- It's definitely not data/DDP related, as all server data is pre-published to the client
- Chrome's timeline shows no heavy JS activity during the delay, it's as if it's just sitting there

There's something really strange going on between the time I use `.set()` on my `ReactiveVar` and the time the Meteor container recognizes the update and reruns. Any help would be greatly appreciated, I'm extremely close to launching a SaaS and would like to get this annoying bug squashed! :bug: :hammer:

**Comment by abernix** [comment]
Nothing shown in the forum post leads me to believe there is a bug with `Tracker` or `ReactiveVar` – aside from the fact that the code hasn't changed.  It would be quite possible to create any number of bottlenecks with large enough datasets, or even small inefficient queries.   Even with everything "published", if you are resubscribing to that data, you could be causing large data changes which need to be re-merged/synced with local collections.

Briefly: If you're seeing the delay after changing the `ReactiveVar`, you could be triggering a multitude of invalidations and causing a large amount of code to re-execute.  Maybe monitor the frames coming over the DDP wire by monitoring the `/websocket` endpoint on your Network panel?  I believe there are tools available to help clarify this data-stream, like [this Chrome extension](https://chrome.google.com/webstore/detail/meteor-devtools/ippapidnnboiophakmmhkdlchoccbgje), the [`babrahams:constellation`](https://atmospherejs.com/babrahams/constellation) tools, Meteor Toys, and I'm sure some Kadira tools do this too.  You should determine how much data is moving around.

Unfortunately, without more to work with, there isn't much else to say: this usually boils down to something running more often than you've anticipated or moving too much data around.  Given the CPU activity, I'd say that it's crunching on something!

**Comment by ffxsam** [comment]
Very strange. It's not a major issue of course, but just an annoyance, and kind of a puzzle at this point. :) You mention CPU, but I don't recall any additional CPU consumption—in fact, the Chrome JS profiler shows it mostly idling which is odd.

It's been a while, so I don't remember if I checked DDP.. but all data has already been sent over the wire. All this `ReactiveVar` is doing is changing the `limit` on the client side only. That's why it's so puzzling to me. My last remaining hypothesis is that maybe it's render-related, though I'm doubtful because on first page load, this weird lag doesn't present, but after navigating away and coming back, it does. It's sporadic.

Unfortunately my repro worked just fine. It might be an interaction with another package, for all I know. I'll come back here if I manage to come up with any new ideas or think I might've stumbled upon the cause. Thanks Jesse!

**Comment by abernix** [comment]
I misread the profiler output on the CPU – you're right.  But, as an additional point, it should be pointed out that MiniMongo does not have indexes.  If you have a lot of data, that could be costly and you may have better performance if you instead relied on the server to do some of that work and kept less in-memory on the client.  See #5678 about adding indexes to MiniMongo.
