### ISSUE TITLE
[1.4.2] Meteor tmp folder in root

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7981]
when upgrade new package from meteor 1.4.2, i see these tmp folder stay in root project folder.
may be this missing ? i think they should be place in .meteor folder.

![image](https://cloud.githubusercontent.com/assets/8347826/19793407/a4ffa26a-9cf6-11e6-898b-53290cfaaf8f.png)

**Comment by abernix** [comment]
They shouldn't be there, or in the `.meteor` folder, they should be using whatever your  operating system defines as the location for temporary files.  What are the values of your `TEMP`, `TMP` and `TEMPDIR` environment variables (any of which might be undefined)?

**Comment by abernix** [comment]
Any updates on this @lyquocnam?  I do not see this behavior in Windows myself.

**Comment by lyquocnam** [comment]
this may be fix @abernix
