### ISSUE TITLE
Meteor build is failing on the server installation with node boron slim

### ISSUE THREAD

**Issue by ankibalyan** [meteor/meteor#7983]
Meteor app generated build is getting failer on ther server only with node's new LTS version.
I'm using docker image boron-slim

```
    npm WARN meteor-dev-bundle@0.0.0 No description
    npm WARN meteor-dev-bundle@0.0.0 No repository field.
    npm WARN meteor-dev-bundle@0.0.0 No license field.
    npm ERR! Linux 3.13.0-96-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! fibers@1.0.13 install: 'node build.js || nodejs build.js'
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node build.js || nodejs build.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs fibers
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /app/bundle/programs/server/npm-debug.log
```

**Comment by abernix** [comment]
Please try using the 4.6.1 LTS and see if it works for you.  Meteor is not meant to run with Node 6 (yet) – the latest Meteor 1.4.2 ships with Node 4.6.1 and I'd recommend trying that version.

**Comment by ankibalyan** [comment]
yes with it does work with `4.6.1 LTS`. When it can be expected to be compatible with `node 6.9.1 LTS`

**Comment by abernix** [comment]
There's no clear answer on this right now and I'll have to leave that for comment from the core team (which I am not, nor do I work for MDG), but right now it's not intended to work so this isn't a bug.

I would review some of the information in #6923 (a past, now-closed, issue about Node 6 which was opened at the same time as the Node 4 transition to address some of the major issues), keep your eye on it, stay tuned to (and follow the) [Meteor Forums](https://forums.meteor.com/) for more information about Meteor 1.5.

It may happen in Meteor 1.5 but I wouldn't bet on it as I believe focus will be put on some more pressing matters.  Node 4 does work, is very stable and is actively in LTS for a very long time to come.  I personally wouldn't sweat the difference too much, though I'm aware that there are benefits to Node 6.

**Comment by benjamn** [comment]
We're definitely keeping an eye on Node 6 compatibility.

It's hard to quantify incompatibility, but in my experience Node 6 seems not nearly as stable as Node 4 at this time. A few npm packages used by Meteor (e.g. `sqlite3`) are still not working at all with Node 6, which suggests that the npm ecosystem beyond Meteor still needs time to adjust to the new version of Node. Your error stems specifically from the `npm install` command for the `fibers` package, which is potentially worth debugging in isolation, not likely a problem with Meteor per se.

Long-term support (LTS) status is just what it sounds like: a commitment to ongoing improvement, not really a stamp of immediate compatibility or stability.

If you have the time and inclination to help in this process, you can try bumping the Node version [here](https://github.com/meteor/meteor/blob/e462cf7133f731bc929ce5f16d8676b371996077/scripts/build-dev-bundle-common.sh#L9) and then run Meteor [from a checkout](https://github.com/meteor/meteor/tree/e462cf7133f731bc929ce5f16d8676b371996077#slow-start-for-developers). Note that running `scripts/generate-dev-bundle.sh` is essential (not optional) if you're changing the Node version.

You might also try focusing just on debugging the problem with `npm install fibers@1.0.13` on your system, though there may be other problems after that.

If you don't feel like digging into this yourself, that's fine; you'll just have to wait that much longer!
