### ISSUE TITLE
[1.4.2] Collection broken after subclassing Mongo.Collection

### ISSUE THREAD

**Issue by romeroadrian** [meteor/meteor#7987]
I'm having an issue after updating Meteor to 1.4.2 (was working fine with 1.4.1.3).

I'm subclassing a particular Mongo collection to provide special hooks in the insert method, just as advised in the Meteor guides. The relevant code is something like this:

```
class MyModelCollection extends Mongo.Collection {
  insert(doc, callback) {
    // do some stuff
    return super(doc, callback)
  }
}

const MyModel = new MyModelCollection('foo');
```

After running that, the collection seems to be broken. Things like `MyModel.find` will return undefined, and almost all related to the collection crashes when the app is opened (this seems to be unrelated to calling the insert method).

If I just define the Mongo.Collection without subclassing everything returns to normal:

```
const MyModel = new Mongo.Collection('foo');
```

**Comment by benjamn** [comment]
Possibly related: https://github.com/meteor/meteor/issues/7956

**Comment by abernix** [comment]
@romeroadrian Please test the release-candidate for Meteor 1.4.2.1 and see if this is fixed.  `1.4.2.1-rc.0` contains some noteworthy changes to the way `babel-runtime` works and might fix this...

You can try it out by:
```sh
cd path/to/your/app
meteor update --release 1.4.2.1-rc.0
meteor update --all-packages
meteor npm install --save babel-runtime
# etc. etc.
```

(Note the need to install your own `babel-runtime`!)

**Comment by abernix** [comment]
@romeroadrian Meteor 1.4.2.1 is now officially released so I've updated the above instructions.  I expect this will fix your problem, but happy to reopen this if you're still having problems.

Thanks for reporting this originally!
