### ISSUE TITLE
[1.4.2] Cannot call a class as a function / Babel setup?

### ISSUE THREAD

**Issue by 123batman** [meteor/meteor#7989]
Hi,
I am not exactly sure what is causing the problem. It was working before upgrading from 1.4.1.1 to 1.4.2 When using mobx:

```
import {observer} from "mobx-react";

class EventListPage extends React.Component {
  constructor(props) {
    super(props);
  }
...
}
EventListPage = observer(EventListPage)
```

This should work according to [the ES6 syntax example](https://github.com/mobxjs/mobx-react#observercomponentclass) but Babel gives me:
`Cannot call a class as a function at classCallCheck`

The only thing I could find is:  https://github.com/babel/babel/issues/700

It stopped working after upgrading to 1.4.2
Did anything change in the babel setup? I couldn't find anything about it in the [changelog](http://docs.meteor.com/changelog.html#v142)

**Comment by tcastelli** [comment]
Possibly related to #7956 , you can try meteor 1.4.2.1 beta and check if that is solved

**Comment by abernix** [comment]
Thanks for reporting this issue, @123batman.  As @tcastelli said, please try this in the latest release candidate for 1.4.2.1 – I'm fairly confident this would be resolved for you.

Simply `meteor update --release 1.4.2.1-rc.1` and `meteor npm install --save babel-runtime`.

Happy to reopen if this problem still exists for you.

Thanks, @tcastelli for making the connection. :)
