### ISSUE TITLE
todo app keep loading on android 2.3 default browser (2g network)

### ISSUE THREAD

**Issue by wighawag** [meteor/meteor#799]
When browsing to http://plausibly-featureful-todos-example.meteor.com/ with my android mobile default browser (2,3) 
"loading..." keeps appearing  and I do not see any todo coming up

When using my laptop browser (chrome) using teh same 2g network I can see the todos but it takes quite a while (10 seconds) before I can see any todos

**Comment by jumami** [comment]
Has this problem solved?

**Comment by jsmillie** [comment]
Not for me. I have just published the to do app to alpha testing in Google Play and this issue arises. The screen just says loading and it doesn't actually load.

It was working fine up until building the project and uploading the apk to Google

**Comment by jumami** [comment]
Does java way also has this problem?
