### ISSUE TITLE
[1.4.2] While debugging server, node-inspector debug console is unusable

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7991]
This is new with 1.4.2: I am seeing this error when loading a server debug session

```
Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open 'E:\mroot\meris\.meteor\local\build\programs\server\profile.js.map'
```

I do not know if it is related, but any commands in the console get lost in space (I assume the debugger may be parsing the entire symbol tree looking for things?).  The console is unusable.

This may be related to #7977 
#### Environment

Windows 10: 1511 (OS Build 10586.633)
Meteor: 1.4.2
Chrome: 54.0.2840.71

**Comment by akodate** [comment]
I am also getting this exact same error after the 1.4.2 update.

**Comment by aaroncalderon** [comment]
I am experiencing the same issue.

# Environment

Windows 7
Meteor: 1.4.2
Chrome: 54.0.2840.71

**Comment by benjamn** [comment]
What "debug console" are you talking about? Do you mean `meteor shell` or `meteor debug` or something else? I'm confused about why you'd be using Chrome to debug server code.

**Comment by aaroncalderon** [comment]
@benjamn I believe he is refering to using `meteor debug` and then opening the `http://localhost:8080/debug?port=5656`. Then once chrome loads the page the above mentioned error happens and the console is unusable. 

That is what happens to me.

**Comment by brucejo75** [comment]
Sorry.  I am using node-inspector which pops up a chrome window.

This error shows up in the console window of Node-inspector:
```
Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open 'E:\mroot\meris\.meteor\local\build\programs\server\profile.js.map'
```

And the console is unusable.  If I type in a variable to inspect it simply does not work.  This is impacting debugging fairly significantly.

**Comment by brucejo75** [comment]
@benjaminn: Does `profile.js` need to be in [this](https://github.com/meteor/meteor/blob/8a6ff5637e6de20f54dd00cb249bf981d3d71303/tools/isobuild/bundler.js#L2240) list?

**Comment by benjamn** [comment]
@brucejo75 it gets written just above that list (`builder.write("profile.js", ...)`)

**Comment by benjamn** [comment]
For what it's worth, we are [using](https://github.com/meteor/meteor/blob/release-1.4.2.1/scripts/dev-bundle-tool-package.js#L36) the latest version of https://www.npmjs.com/package/node-inspector (0.12.8).

**Comment by brucejo75** [comment]
Yeah, I upgraded everything.  But the console is still dead.

Any idea why Node-inspector is looking for the map of `profile.js`?  Does not seem to need or complain about lack of maps for any other `.js` files in that directory: `.meteor\local\build\programs\server`

**Comment by brucejo75** [comment]
I just installed 1.4.2.1 and verified the issue is still there in that version.

### Repro
1. `meteor create test`
2. `cd test; meteor`
3. Bring up node-inspector

### Result
node-inspector console is not responsive to commands

**Comment by brucejo75** [comment]
OK, I found this: https://github.com/node-inspector/node-inspector/issues/903

Seems that node-inspector is having a sync problem with Chrome and this bug cropped up with new versions of Chrome.  Not related to Meteor...

Closing, sorry for the distraction.

**Comment by benjamn** [comment]
All good! Obviously `node-inspector` is a large and complicated piece of software (mimicking Chrome DevTools with pure HTML is no easy feat!), and so the surface area for bugs is pretty big. On top of that, the Chrome team isn't responsible for `node-inspector` continuing to work with their updates, so there are bound to be bugs like this one from time to time. Thanks for digging into it some more.

**Comment by AronVanAmmers** [comment]
Note that this issue describes three phenomena:

1. `node-inspector` for a meteor app doesn't show the source tree
1. An error message about `profile.js.map` is shown in the error console of the Chrome tab that `node-inspector` is loaded in
1. The console of `node-inspector` doesn't work due to a change in handling keyboard inputs in Chrome

Point 3 is indeed a generic issue between `node-inspector` and Chrome. Getting your hands on a Chrome version 51 or earlier is a workaround for this point.

Point 1 and 2 are connected and actually _do_ only occur after Meteor 1.4.2. I've tested Meteor 1.4.1.3 and there the source tree loads fine and there is no error message about `profile.js.map`. So there does seem to besomething wrong on the Meteor side as well.

**Comment by abernix** [comment]
@AronVanAmmers First, please try resetting your dev environment with `meteor reset` (will clear your database too!).  If you continue to experience this, please open a new issue (this is closed) with steps on how to reproduce the exact problem you're encountering (most preferably with a Git reproduction repository which can be cloned!).  From my own perspective on this issue, in the course of triaging GitHub issues for Meteor, I routinely use `meteor debug` and `node-inspector` in various capacities on many different apps and have not encountered problems that you're referring to.

**Comment by AronVanAmmers** [comment]
@abernix that's encouraging, thanks 😄. Will clean up and report back.

**Comment by brucejo75** [comment]
BTW: I do not think node-inspector will ever get fixed anymore.

As of Node v6.3.0+, node applications can  be debugged with the chrome debug tools directly:

See "[Debugging Node.js with Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.sam9dduaz)"



YAY!  Looking forward to the next version of Meteor with support for Node v6.  I think it is coming soon.

**Comment by AronVanAmmers** [comment]
@brucejo75 thanks, that's very helpful to know! Looking forward to v6.

As it turns out, I was wrong on point 1 above. Indeed loading the source tree works fine in 1.4.2.3, as does the rest of the debugging functionality. The error message about `profile.js.map` _is_ shown using the repro steps above, however it doesn't seem to cause any harm.

**Comment by AronVanAmmers** [comment]
Here's a one-liner to apply the workaround from https://github.com/node-inspector/node-inspector/issues/951 and fix the behaviour of the enter key in Chrome >= 53. This adapts the file of `node-inspector` within the meteor path. This needs to be run after every new Meteor version update.

```
find ~/.meteor -name DOMExtension.js -exec sed -i 's/return event.keyCode !== 229 \&\& event.keyIdentifier === "Enter"\;/return (event.keyCode !== 229 \&\& event.keyIdentifier === "Enter") || event.keyCode
```

Note that there appears to be an issue with the cursor keys as well, and node-inspector has more issues. But with this fix basic debugging is possible.

**Comment by mikepaszkiewicz** [comment]
@AronVanAmmers - tried running from terminal and it acted like I was missing a quote or something, so i modified the file directly:

1. ```find ~/.meteor -name DOMExtension.js```
2. open file and find isEnterKey
3. replace function with one given here node-inspector/node-inspector#951 
```function isEnterKey(event) {
//suit for event.keyIdentifier
return (event.keyCode !== 229 && event.keyIdentifier === "Enter") || event.keyCode === 13;
}```

**Comment by brucejo75** [comment]
Thanks for the pointer, but that fix does not work for me.  I did these steps:
1. Made the change in the file
2. Did a rebuild.
3. Opened up node inspector by going to: http://127.0.0.1:8080/?port=5858 in my browser
4. Hit a breakpoint

Went to a console line I still have the enter problem?

**Comment by mikepaszkiewicz** [comment]
Hm..by rebuild do you mean letting the project auto-rebuild after a change or completely stopping the app and running ```meteor``` again? 

Also double check that your project is running on the same meteor release as the subdirectory of the file you changed. I have two meteor version directories for different projects - 1.3.3 & 1.4.2.1 - and had to make the change in both.

**Comment by brucejo75** [comment]
@mikepaszkiewicz, thanks for the reply.  I am seeing a problem, maybe with my build?
1. I stopped the app and reran meteor.
2. I only have one `DOMExtension.js` file under my `.meteor` directory and it was found here:
`.meteor\local\dev_bundle\lib\node_modules\node-inspector\front-end\platform`.
3. I am running meteor v1.4.2.3

And here is the code in the file I changed:

```
/**
 * @return {boolean}
 */
function isEnterKey(event) {
    // Check if in IME.
    return (event.keyCode !== 229 && event.keyIdentifier === "Enter") || event.keyCode === 13;
}
```

While running node-inspector, I hit `F12` and took at look at `platform/DOMExtension.js` and it does not have the change in it that I added above.  I would have thought a rebuild would have pulled this in?  Maybe with the smarter build it is skipping the dev_bundle rebuild?

Also, how do you fire up a debug session?  Just navigate to http://127.0.0.1:8080/?port=5858?
Thanks

**Comment by AronVanAmmers** [comment]
@brucejo75 @mikepaszkiewicz there was a typo in my initial message about the one-liner. Corrected, sorry about that.

I can confirm that breakpoints work for me. Indeed start by navigating to http://localhost:8080/?port=5858.

**Comment by ajitgoel** [comment]
@AronVanAmmers : I made the changes as suggested by @brucejo75 on Dec 13, 2016 and I am still getting the same issue. Any ideas on what I might be doing wrong?

**Comment by brucejo75** [comment]
@ajitgoel  I figured out my issue.  I had installed node-inspector globally, not in my meteor project.

So I made the requisite changes in the global repository for node-inspector.  In my case that is on windows and my installation is here: C:\Users\Bruce\AppData\Roaming\npm\node_modules\node-inspector.

Maybe others got tripped up by this too?

**Comment by ajitgoel** [comment]
Hi @brucejo75,
I am a meteor newbie.
The project that I am working on is located in C:\Projects\simple-todos folder. 
I made the changes suggested in your comments in the C:\Users\u6041471\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-inspector\front-end\platform\DOMExtension.js
file whereas the node-inspector folder is present in C:\Users\u6041471\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\. 
This however did not solve the problem. Can you please help?

**Comment by brucejo75** [comment]
What  happens when you type `where node-debug` and `where node-inspector` to the command line of a cmd window?

**Comment by ajitgoel** [comment]
I get the following when I run the **where node-debug** and **where node-inspector** commands respectively. 
**C:\Users\u6041471\AppData\Roaming\npm\node-debug
C:\Users\u6041471\AppData\Roaming\npm\node-debug.cmd**

**C:\Users\u6041471\AppData\Roaming\npm\node-inspector
C:\Users\u6041471\AppData\Roaming\npm\node-inspector.cmd**

When I run the **npm install -g node-inspector** command, I see the following error:

23885 verbose stack Error: v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
23885 verbose stack Exit status 1
23885 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
23885 verbose stack     at emitTwo (events.js:106:13)
23885 verbose stack     at EventEmitter.emit (events.js:191:7)
23885 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
23885 verbose stack     at emitTwo (events.js:106:13)
23885 verbose stack     at ChildProcess.emit (events.js:191:7)
23885 verbose stack     at maybeClose (internal/child_process.js:885:16)
23885 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
23886 verbose pkgid v8-debug@0.7.7
23887 verbose cwd c:\Projects\simple-todos
23888 error Windows_NT 6.1.7601
23889 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
23890 error node v7.4.0
23891 error npm  v4.0.5
23892 error code ELIFECYCLE
23893 error v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
23893 error Exit status 1
23894 error Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
23894 error Make sure you have the latest version of node.js and npm installed.
23894 error If you do, this is most likely a problem with the v8-debug package,
23894 error not with npm itself.
23894 error Tell the author that this fails on your system:
23894 error     node-pre-gyp install --fallback-to-build
23894 error You can get information on how to open an issue for this project with:
23894 error     npm bugs v8-debug
23894 error Or if that isn't available, you can get their info via:
23894 error     npm owner ls v8-debug
23894 error There is likely additional logging output above.
23895 verbose exit [ 1, true ]

**Comment by brucejo75** [comment]
OK, good information.  Couple of things:

1. I am running the same version of Node as the version inside of Meteor.  I am running meteor v1.4.2.3, which is running node v4.6.2.  I recommend that you do the same.  You can find this out by running these commands:
```
meteor --version
meteor node -v
```

2. You need to figure out what is going on with the node-inspector install.  It looks like there is an open [bug](https://github.com/node-inspector/node-inspector/issues/868) on it and an answer [here](https://github.com/node-inspector/v8-debug/issues/7#issuecomment-154450807).  From reading this, I think it may be node version 5+ related.  So if you go back to node v4.6.2 I think it may install without issue.

3. Also there is another gotcha.  I initially installed 64 bit versions of `node` and `node-inspector`.  But meteor only supports 32 bit.  So it all must be installed 32 bit to properly mate with the meteor app.

#### After all that...

Now you can make the patch to `node-inspector` here: `C:\Users\u6041471\AppData\Roaming\npm\node_modules\node-inspector\front-end\platform\DOMExtension.js`

Hope this helps.

**Comment by codeHatcher** [comment]
I'm glad this thread is here but this is nuts that it has been an issue almost for 5 months. I guess either no one is debugging their apps or maybe many people aren't using Meteor? Is there an alternative debugging method that everyone is using other than `meteor shell` ?

**Comment by abernix** [comment]
@codeHatcher This issue is closed.  Meteor apps can be debugged by running `meteor debug` and I do this on a regular basis.  If you encounter problems with using those debug tools, please open a new issue with a reproduction.

**Comment by codeHatcher** [comment]
@Abernix what was the solution that closes this issue that I also see. The highly reacted ones are the "hacks" vs official fix

**Comment by abernix** [comment]
@codeHatcher I guess the resolution was that there is a bug in `node-inspector`'s console (the bug is still open).  But that doesn't mean that people aren't debugging their apps or not using Meteor, it just means that developers aren't using the console in `node-inspector`.

[The reproduction above](https://github.com/meteor/meteor/issues/7991#issuecomment-259488934) still appears a bit incorrect as it doesn't show any attaching of Meteor to the debug interface – or more correctly, using `meteor debug` at all – which doesn't require you use `node-inspector` directly at all.

But again, if you're encountering this problem, can you please open a new issue with a clear reproduction? :smile:

**Comment by brucejo75** [comment]
repro using `meteor debug` is [here](https://github.com/meteor/meteor/issues/7991#issuecomment-258919721).

Regardless there is no bug in Meteor.  Node-inspector had a bug and a published workaround [here.](https://github.com/node-inspector/node-inspector/issues/951).

After closing the bug, this thread published instructions on how to patch your version of meteor's node-inspector.  Those instructions did not work for me.  Then I [realized](https://github.com/meteor/meteor/issues/7991#issuecomment-277484110) that my debug environment uses my installed version of node-inspector and I do not use the version that comes with Meteor so I published instructions on how to find the file to patch for that circumstance.

@abernix is right, I am confusing things by not using `meteor debug` which is the documented way to debug.  I hadn't realized it was confusing because I never figured out how to debug meteor any way other than what I happened to cobble together.

hmm. thinking about it... would it be reasonable for Meteor to apply the patch as part of building the dev bundle?

**Comment by codeHatcher** [comment]
I'll open up a new issue, I am having the same issue as the person that posted in November but it seems that's buried in the comments

**Comment by abernix** [comment]
The bug reported [in bullet-point 3 in December](https://github.com/meteor/meteor/issues/7991#issuecomment-266139691) is actually the same as the original issue and the subject of this issue.

This is absolutely a bug with `node-inspector` and I can reproduce it myself now too.  We'll follow the `node-inspector` fix for this in your new issue, but it is essentially a duplicate and the same problem is experienced in `node-inspector` outside Meteor and will (eventually?) be fixed if/when `node-inspector` lands https://github.com/node-inspector/node-inspector/pull/955 and is reported in https://github.com/node-inspector/node-inspector/issues/903.
