### ISSUE TITLE
Meteor._localStorage to npm?

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7996]
Do you think I could help publish the localstorage package to NPM? I'd like to use it outside of Meteor and was wondering if this was something that was planned already?

**Comment by abhiaiyer91** [comment]
https://github.com/Workpop/localstorage

I've ported it here. What are next steps for me

**Comment by stubailo** [comment]
I think @benjamn is working on a way to have Meteor core packages on NPM, possibly with one in the next release. So we could follow that pattern, let's circle back in a few days.

**Comment by smeijer** [comment]
That sounds really awesome @stubailo. I've been waiting for this moment a long time. 

Does that also mean that our `package.json` needs an update on that release? This will be a huge win for testability.

**Comment by hwillson** [comment]
As mentioned in the Meteor Roadmap, a [full transition to npm](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm) is planned, and will happen at some point in the future. Until that happens however, internal Meteor core packages like `localstorage` will only be available via Atmosphere (using Meteor's custom package API). Once the process for moving Meteor to npm has been fully investigated, tested and put into place, an npm approach for `localstorage` (along with all other Meteor core packages) will be put in place as well. Given this, there isn't much that can be done with this issue right now. `localstorage` functionality can always be extracted and made into your own npm package (like you've already done), as a temporary stop-gap measure.

Given the above, I'll close this issue for now. Thanks for submitting this feature request originally!
