### ISSUE TITLE
[1.4.2] NPM dependencies onTest are not found

### ISSUE THREAD

**Issue by namirsab** [meteor/meteor#7999]
## Meteor Version
1.4.2
## Packages
* `practicalmeteor:mocha`
* NPM `cheerio` inside the package to illustrate the problem

## Observed Behaviour
Running `meteor test-packages --driver-package=practicalmeteor:mocha packages/npm-failing-test` throws the following error:
```
W20161101-19:15:49.248(1)? (STDERR) /home/namirsab/.meteor/packages/meteor-tool/.1.4.2.okzouw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161101-19:15:49.248(1)? (STDERR) 						throw(ex);
W20161101-19:15:49.248(1)? (STDERR) 						^
W20161101-19:15:49.249(1)? (STDERR) 
W20161101-19:15:49.249(1)? (STDERR) Error: Cannot find module './lib/cheerio'
W20161101-19:15:49.250(1)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161101-19:15:49.250(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:npm-failing-test.node_modules.cheerio.index.js (/tmp/meteor-test-run10cj9p7/.meteor/local/build/programs/server/packages/local-test_npm-failing-test.js:62:28)
W20161101-19:15:49.250(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-19:15:49.250(1)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161101-19:15:49.250(1)? (STDERR)     at Module.Mp.import (/home/namirsab/.meteor/packages/modules/.0.7.7.1fxu2so++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161101-19:15:49.250(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:npm-failing-test.npm-failing-test.spec.js (packages/local-test:npm-failing-test/npm-failing-test.spec.js:1:21)
W20161101-19:15:49.250(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-19:15:49.251(1)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161101-19:15:49.251(1)? (STDERR)     at /tmp/meteor-test-run10cj9p7/.meteor/local/build/programs/server/packages/local-test_npm-failing-test.js:73:1
W20161101-19:15:49.251(1)? (STDERR)     at /tmp/meteor-test-run10cj9p7/.meteor/local/build/programs/server/packages/local-test_npm-failing-test.js:79:3

```

## Expected Behaviour
Running `meteor test-packages --driver-package=practicalmeteor:mocha packages/npm-failing-test` run the test.

## Repository
https://github.com/namirsab/meteor-1.4.2-npm-test-bug

## More info
Look how the import works in the app but not in the test run.

**Comment by namirsab** [comment]
@abernix here you are!

**Comment by JeremySaks** [comment]
i'm getting this as well, new in 1.4.2.

`meteor test-packages ./ --driver-package practicalmeteor:mocha` and then `import {assert} from chai` inside my test directory leads to:

```
W20161101-14:53:30.779(-4)? (STDERR) Error: Cannot find module './lib/chai'
W20161101-14:53:30.779(-4)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161101-14:53:30.779(-4)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:ato.cards.node_modules.chai.index.js (/private/var/folders/b3/9w8g0scx6_51h9531ly_djgw0000gn/T/meteor-test-run1xycy4i/.meteor/local/build/programs/server/packages/local-test_ato.cards.js:2357:18)
W20161101-14:53:30.779(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-14:53:30.779(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161101-14:53:30.780(-4)? (STDERR)     at Module.Mp.import (/Users/jeremysaks/.meteor/packages/modules/.0.7.7.jvu3qu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161101-14:53:30.780(-4)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:ato.cards.test.test.js (packages/local-test:ato.cards/test/test.js:1:22)
W20161101-14:53:30.780(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-14:53:30.780(-4)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161101-14:53:30.780(-4)? (STDERR)     at /private/var/folders/b3/9w8g0scx6_51h9531ly_djgw0000gn/T/meteor-test-run1xycy4i/.meteor/local/build/programs/server/packages/local-test_ato.cards.js:2535:15
W20161101-14:53:30.781(-4)? (STDERR)     at /private/var/folders/b3/9w8g0scx6_51h9531ly_djgw0000gn/T/meteor-test-run1xycy4i/.meteor/local/build/programs/server/packages/local-test_ato.cards.js:2541:3
```

the reference to './lib/chai' is a subfolder (which is present) inside the `node_modules/chai` directory.

**Comment by lampe** [comment]
I have created a small repo where you can see the bug:

[lampe/meteorIssue7999](https://github.com/lampe/meteorIssue7999/tree/master)

**Comment by lampe** [comment]
I'am still getting the same error as @namirsab on the 1.4.2.1-beta.1 Release

**Comment by namirsab** [comment]
@abernix any news about that? Any plans to fix it?

**Comment by abernix** [comment]
Thanks for opening this issue.  I can confirm that the reproduction you've provided does indeed cause the error which did not happen in 1.4.1.3.  While it does work with another package I tried (say `sprintf-fs`), I see no reason why `cheerio` would exhibit this behavior.  I believe this is an unintended regression in Meteor 1.4.2.

I'll mark this as a confirmed bug.  Thanks for reporting it!

**Comment by namirsab** [comment]
@abernix i'm willing to try to fix the issue with some guidance. We need this to get solved, the meteor testing solutions should be stable and i don't know why, every time i try to stabilsh a proper testing workflow with my team, the testing solution breaks or just get replaced (velocity case)

**Comment by abernix** [comment]
@namirsab Thanks for being willing to take a look at it!  I'm a bit distant from this particular logic, but if I had to point you in a direction, I'd first say make sure you're setup to [run Meteor from a checkout](https://github.com/meteor/meteor/#slow-start-for-developers).

Honestly, I think this is probably coming from https://github.com/meteor/meteor/commit/03c5346873849151cecc3e00606c6e5aa13b3bbc.  It serves a good purpose though, so it's not as easy as just removing it.

Also, if you need to use `node-inspector`, I think this should do it for you:
 0. Run `node-inspector` (install if necessary with `npm i -g node-inspector`
 0. Start your checked-out meteor with `TOOL_NODE_FLAGS='--debug-brk' /path/to/checked-out/meteor <usual flags>`
 0. Open the link given by `node-inspector` in step 1.

Alternatively, hopefully someone can look at this sometime this next week.

**Comment by hwillson** [comment]
@namirsab I haven't looked into the cause of your issue, but I can suggest a workaround. Using `Npm.depends` in packages is quite rigid, and for that reason is not really recommended (for more details see the Guide's [Peer npm dependencies](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) section). If you remove the `Npm.depends` code from `packages/npm-failing-test/package.js` in your repro, and instead run a `meteor npm install --save-dev cheerio` in your project, your `meteor test-packages` call will no longer throw an error. Again this doesn't explain the error you're seeing, but it will work (and my brain can't go much further on Friday afternoon!).

**Comment by theodorDiaconu** [comment]
Can these be related ? https://github.com/meteor/meteor/issues/8028
