### ISSUE TITLE
Separate fronte end and backend dependencies & document how to use a separate react front end

### ISSUE THREAD

**Issue by birish2** [meteor/meteor#8000]
I would really like to see this project implement more modular ways to integrate with other existing front end frameworks. My ideal case would be to see a basic example of how to integrate Meteor's TODO App tutorial, with the front end being started by the https://github.com/facebookincubator/create-react-app
In this case, meteor would only handle backend services, accounts, live updates, etc. while keeping the react app in a completely separate build project/bundle with minimal imports required to connect to the meteor backend.

**Comment by laosb** [comment]
I think it's better to discuss this on [forums](https://forums.meteor.com). Closing.

PS: You've claimed issue #8000!
