### ISSUE TITLE
[1.4.2] Cannot find module 'double-ended-queue'

### ISSUE THREAD

**Issue by mhlmhl** [meteor/meteor#8004]
I upgraded to Meteor 1.4.2 on my Windows 8.1 64-bit machine, and everything was ok until I rebooted, when I got the error described at https://stackoverflow.com/questions/40362806/meteor-1-4-2-typeerror-cannot-set-property-node-modules-react-router-package-j.  I tried a bunch of things to get around this problem, including:
   * specifying --release 1.4.1 on "meteor run"
   * recreating my app in another folder

Whatever I do, I get the error shown below.  So I created a did "meteor create test" to create a brand new meteor app in a new folder, and tried to run it.  And I still get this error.  Now I'm dead in the water and really hurting.

> C:\Users\mhl\Downloads\test>meteor run --release 1.4.2
> [[[[[ C:\Users\mhl\Downloads\test ]]]]]
> 
> => Started proxy.
> => Started MongoDB.
> W20161102-09:05:09.116(-4)? (STDERR) C:\Users\mhl\Downloads\test\.meteor\local\build\programs\server\boot.js:348
> W20161102-09:05:09.215(-4)? (STDERR) }).run();
> W20161102-09:05:09.216(-4)? (STDERR)    ^
> W20161102-09:05:09.216(-4)? (STDERR)
> W20161102-09:05:09.217(-4)? (STDERR) Error: Cannot find module 'double-ended-queue'
> W20161102-09:05:09.218(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
> W20161102-09:05:09.219(-4)? (STDERR)     at Function.Module._load (module.js:276:25)
> W20161102-09:05:09.219(-4)? (STDERR)     at Module.require (module.js:353:17)
> W20161102-09:05:09.220(-4)? (STDERR)     at require (internal/module.js:12:17)
> W20161102-09:05:09.221(-4)? (STDERR)     at Object.<anonymous> (C:\Users\mhl\AppData\Local\.meteor\packages\meteor\1.6.0\npm\node_modules\meteor-deque\index.js:1:18)
> W20161102-09:05:09.221(-4)? (STDERR)     at Module._compile (module.js:409:26)
> W20161102-09:05:09.222(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
> W20161102-09:05:09.223(-4)? (STDERR)     at Module.load (module.js:343:32)
> W20161102-09:05:09.223(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
> W20161102-09:05:09.224(-4)? (STDERR)     at Module.require (module.js:353:17)
> => Exited with code: 1

**Comment by mhlmhl** [comment]
On a guess, I tried "meteor npm install --save double-ended-queue" but the error has not gone away.

**Comment by mhlmhl** [comment]
Further evidence: I see a folder named "double-ended-queue" at "C:\Users\mhl\AppData\Local\.meteor\packages\meteor\1.6.0\npm\node_modules\meteor-deque\node_modules\double-ended-queue". That folder contains a js folder which is completely empty.  So I think the problem is that the double-ended-queue npm package is not properly installed.

**Comment by mhlmhl** [comment]
Another clue: the package.json file in C:\Users\mhl\AppData\Local.meteor\packages\meteor\1.6.0\npm\node_modules\meteor-deque\node_modules\double-ended-queue contains the line "  "_from": "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz".  So I manually downloaded and looked in that .tgz file.  I found the js folder, which contains "deque.js" that exports the module called "Dequeue".  So I copied this file into the js folder of C:\Users\mhl\AppData\Local.meteor\packages\meteor\1.6.0\npm\node_modules\meteor-deque\node_modules\double-ended-queue.

Result: the error "Cannot find module 'double-ended-queue'" has gone away, only to be replaced by "Error: Cannot find module 'bson'".  Looking thru the stack trace, I see that it references "C:\Users\mhl\AppData\Local\.meteor\packages\npm-mongo\2.2.11_2\npm\
node_modules\mongodb-core\lib\connection\commands.js:4:12".  I discovered that I have multiple versions of the npm-mongo package.  Comparing the 2.2.11_1 version to the 2.2.11_2 version, I see that numerous .js files that exist in the 2.2.11_1 version of npm\node-modules\bson are missing from the 2.2.11_2 version.  For example, the lib folder has these files in the 2.2.11_1 version that are missing from the 2.2.11_2 version: {code, decimal128, double, float_parser, ...}.js.

So it appears that some .js (and maybe other?) files are not being installed.

**Comment by mhlmhl** [comment]
Not getting any response to this issue, and desperate for a solution, I deleted and reinstalled meteor 1.4.2.  The regular Windows install program didn't work - the "meteor" command did not work even after rebooting because the meteor.bat file was not installed in ...\AppData\Local\.meteor.  So I installed according to this article: https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md.

This got meteor to the point where "meteor create" followed by "meteor" runs fine.  BUT my own existing app has a major problem: jsx imports are not getting resolved.  I use the Chrome debugger to breakpoint in my code immediately after these import statements:

> import { Meteor } from 'meteor/meteor';
> import React from 'react';
> import { render } from 'react-dom';
> import { Router, Route, IndexRoute, browserHistory } from 'react-router';
> 
> import { BasicLayout } from '/imports/client/layouts/BasicLayout.jsx';
> import { Home } from '/imports/client/pages/Home/Home.jsx';
> import TestView from '/imports/client/pages/vocabulary/test/TestView.jsx';

When I hover my mouse over each of these imports, I see that:

- Meteor, React, render, Home, and TestView all show up as objects.
- Router, Route, IndexRoute, browserHistory, and BasicLayout are undefined.  The common aspect of these is that they are all .jsx files.

I have verified (via "meteor npm list") that react-router is installed and that BasicLayout is at location specified in the import statement.  I also verified (via meteor list) that I have ecmascript 0.5.9.  So now I'm looking for a solution to that problem.

**Comment by dan335** [comment]
I'm getting this also.  1.4.2.1

```
[danp-1]2016-11-10T06:18:12.108496297Z Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
[danp-1]2016-11-10T06:18:12.108517696Z     at Object.require (/opt/app/bundle/programs/server/boot.js:200:17)
[danp-1]2016-11-10T06:18:12.108533006Z     at packages/meteor.js:677:32
[danp-1]2016-11-10T06:18:12.108547876Z     at packages/meteor.js:846:4
[danp-1]2016-11-10T06:18:12.108562445Z     at packages/meteor.js:1380:3
[danp-1]2016-11-10T06:18:12.108580925Z     at /opt/app/bundle/programs/server/boot.js:295:34
[danp-1]2016-11-10T06:18:12.108596124Z     at Array.forEach (native)
[danp-1]2016-11-10T06:18:12.108611084Z     at Function._.each._.forEach (/opt/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
[danp-1]2016-11-10T06:18:12.108626374Z     at /opt/app/bundle/programs/server/boot.js:128:5
[danp-1]2016-11-10T06:18:12.108641073Z     at /opt/app/bundle/programs/server/boot.js:344:5
[danp-1]2016-11-10T06:18:12.108655743Z     at Function.run (/opt/app/bundle/programs/server/profile.js:480:12)
[danp-1]2016-11-10T06:18:25.583763322Z /opt/app/bundle/programs/server/boot.js:348
[danp-1]2016-11-10T06:18:25.583828950Z }).run();
[danp-1]2016-11-10T06:18:25.583846340Z    ^
```

**Comment by dan335** [comment]
Fixed my problem.  In .gitignore I had this.

    node_modules/

and meteor-deque is at

    /app/bundle/programs/server/npm/node_modules/meteor/meteor/node_modules/meteor-deque

so it wasn't being checked in.

**Comment by abernix** [comment]
If you are experiencing this problem, please upgrade to Meteor 1.4.2.1 and install the `babel-runtime` NPM (as Meteor 1.4.2.1 no longer provides its own babel functions):

```sh
$ cd /your/app/directory
$ meteor update --release 1.4.2.1
$ meteor npm install babel-runtime --save
$ # If you still have problems, try a Meteor reset:
$ # Note, this will erase your development database!
$ meteor reset
$ # If you _still_ have problems, please reinstall Meteor:
$ curl https://install.meteor.com/ | sh
$ meteor # start it again
```

Please report back if this does or does not fix the problem for you.

**Comment by mhlmhl** [comment]
My problem is fixed, but I'm not sure what fixed it.  I had a hardware problem that required complete re-installation of my system.  I noticed these instructions along the way, and followed them. (It was a horrible week!)

**Comment by abernix** [comment]
Glad to hear it's fixed for you.  Thanks for reporting the problem originally!  I'm not saying there wasn't a bug that existed here, there may have been and hopefully it's fixed.  (And hopefully the solution for others won't be "reinstall your whole computer". :wink:)
