### ISSUE TITLE
Can't publish package

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8011]
When I try to publish a package `meteor publish` I keep getting:
`Error from package server: No matching login attempt found [145546287]`

I tried deleting my `.meteorprofile` file, had to log in again, but got same error.

**Comment by abernix** [comment]
I just tried with no problem.  Can you log in at https://packages.meteor.com/? (or if already logged in, log out and log in again).

Also, be sure to take caution if you're copying and pasting the password – it always fails for me on Windows.

**Comment by sebakerckhof** [comment]
Logging in to https://packages.meteor.com/ works.
The actual password login also works in meteor tool (otherwise I get: 'Login failed').
And the `.meteorsession` file is filled with:
```
{
  "sessions": {
    "www.meteor.com": {
      "session": "PyARbo34fqJrWD2sx",
      "type": "meteor-account",
      "username": "seba",
      "userId": "BDYbaRDoNYXCb2ygo",
      "token": "SECRET",
      "tokenId": "SECRET"
    }
  }
}
```

**Comment by abernix** [comment]
Someone else will have to look at this.

I just deleted my `~/.meteorsession` file, did `meteor login`, and did `meteor publish --release 1.4.2 abernix:test-test` to publish these [two versions of `abernix:test-test`](https://atmospherejs.com/abernix/test-test).  What `--release` are you using or what version of the tool are you using?  Perhaps it's something isolated to your account and I wouldn't experience it.

**Comment by abernix** [comment]
What package are you trying to publish?  Is it a new package or an existing package, and if it's an existing package, what is it?

It seems like some bizarre oAuth handshake issue coming [from here](https://github.com/meteor/meteor/blob/release-1.4.2.1/packages/accounts-oauth/oauth_server.js#L19-L38).

This is hacky as, but what if you login at https://packages.meteor.com, pop open your browser console, and put the result of `localStorage.getItem('Meteor.loginToken')` as the `token` in your `.meteorsession` file, like this:

#### ~/.meteorsession
```
{
  "sessions": {
    "packages.meteor.com": {
      "type": "package-server",
      "pendingRevoke": [],
      "token": "TOKEN_HERE"
    },
    "www.meteor.com": {
      "type": "meteor-account",
      "username": "YOUR_USERNAME",
      "userId": "USER_ID_SAME_AS_BEFORE"
    }
  }
}
```

I've tried several times to break my process

**Comment by sebakerckhof** [comment]
I was trying to publish a build from `fourseven:scss` where I'm the maintainer. Anyway, it worked from another PC. Let's assume it was something with my meteor installation. 
Thanks for your support anyway.
