### ISSUE TITLE
[1.4.2.1-rc.0] meteor todos client tests fail with select: Invalid argument

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#8016]
Noticed this in my project and was able to reproduce using the `meteor-todos` project.

Just upgrade to rc.0 and you'll see that when running `npm test` the client tests fail. In fact, it seems the process exits unceremoniously somehow since the output is cut off.

```
I20161104-09:06:23.738(-7)? --------------------------------
I20161104-09:06:23.738(-7)? ----- RUNNING CLIENT TESTS -----
I20161104-09:06:23.738(-7)? --------------------------------
I20161104-09:06:23.738(-7)? 
I20161104-09:06:23.738(-7)? select: Invalid argument
....  80 repeated snipped ....
I20161104-09:06:23.738(-7)? select: Invalid argu
➜  todos git:(master) ✗ echo $?
0
```

**Comment by misteral** [comment]
Get the same issue

**Comment by hexsprite** [comment]
seems more likely to be a phantomjs issue here. But I am curious why this would suddenly show up in this particular meteor release since the node version was not changed.

**Comment by hexsprite** [comment]
doesn't appear when running the tests in CircleCI so this also may be OSX specific

**Comment by toongijbels** [comment]
I noticed this problem in my project as well.  
OSX 10.11.2. 
Meteor 1.4.2.1.
NPM 3.10.9

**Comment by hwillson** [comment]
Thanks for reporting this - I've moved this over to issue meteor/todos#198; I'll track progress there (and close this issue).

**Comment by weilitao** [comment]
The bug is still exists. Todo app and my app all have the same issue when running `npm test`, `npm test-watch` is ok.

OSX 10.12.1
Meteor 1.4.2.3
phantomjs 2.1.1

**Comment by hwillson** [comment]
@weilitao Can you please add your comments to meteor/todos#198? The discussion have moved over there. Thanks!
