### ISSUE TITLE
Windows 10 Installer

### ISSUE THREAD

**Issue by DZuz14** [meteor/meteor#8017]
Just frozen. This is after 20 minutes. My internet is working fine, as I am typing here while the installer is frozen.
![1](https://cloud.githubusercontent.com/assets/19492185/20015787/380a15b2-a293-11e6-96d8-2859c3163180.jpg)

**Comment by DZuz14** [comment]
**RIGHT CLICK AND SELECT RUN AS ADMINISTRATOR** fixes it.

**Comment by abernix** [comment]
Hmm, I run it on Windows 10 all the time and don't have to run as administrator.  Is this your first time installing Meteor or is this a re-install?

**Comment by DZuz14** [comment]
first time

**Comment by DZuz14** [comment]
Going to be 100% honest, installing was pretty nightmarish. It took me almost 2 hours to get it going. Numerous uninstalls, installer freezing, etc. I was about to give up until it worked.

**Comment by abernix** [comment]
While I hope that your suggestion to run as administrator will help some, that isn't the intended way to have to install it, nor is it necessary for me.  I do a fresh install on a new Windows VirtualBox every couple weeks and it does go through.  The installer doesa fairly dramatic download (150 megs or so) of the bootstrapping tarball during the installation which could have been the bottleneck that you experienced.

I'm very glad you got it installed, and hope that won't be an ongoing issue for you, but unfortunately without a particular action item here, I'm going to close this and try to identify specific problems with it.

Thank you for reporting this problem.
