### ISSUE TITLE
Can't find variable: Modules

### ISSUE THREAD

**Issue by theeli0tt** [meteor/meteor#8018]
- Meteor version: 1.4.2
- Modules package
- macOS 10.13 staff alpha

Hi, I recently created a Meteor app by doing 
`meteor create app`
Then I wanted to create modules. So i did the following command
`meteor add modules`
`meteor add ecmascript`

Then in the client folder, I created a "modules" folder, and in this folder I created a file "_modules.js":
`/client
--- /modules
------ _modules.js`
In this file I wrote the following code:
`Modules.client = {};`

Then I launched the server:
`meteor`

And finally I opened `http://localhost:3000`
When I typed `console.log(Modules)` in the console I got the error: 

> Can't find variable: Modules

It should return me an object

**Comment by benjamn** [comment]
In JavaScript, `Modules.client = {}` does not define the `Modules` variable for you. You probably wanted to say something like
```js
Modules = {
  client: {}
};
```
instead.
