### ISSUE TITLE
Downloading babel-runtime@0.1.13... not downloading - timedout

### ISSUE THREAD

**Issue by albsa** [meteor/meteor#8019]
Hi, 

when downloading/creating new meteor app it gets stuck on:
Downloading babel-runtime@0.1.13...

I get a timed out NPM error after some mins, can you please check this issue?

**Comment by abernix** [comment]
What version of Meteor are you trying to create your app with and what platform are you running on?  The `babel-runtime` is a relatively large package too so make sure you're on a reliable Internet connection when you're installing it.

**Comment by abernix** [comment]
Also, if you're interested in trying another option, Meteor 1.4.2.1 has changed the way that `babel-runtime` works:

```
* Installing the `babel-runtime` npm package in your application
  `node_modules` directory is now required for most Babel-transformed code
  to work, as the Meteor `babel-runtime` package no longer attempts to
  provide custom implementations of Babel helper functions.
```
Consider trying it out by using the latest release candidate (not officially released yet):

    meteor update --release 1.4.2.1-rc.1

And then:

    meteor npm install --save babel-runtime

**Comment by bmustata** [comment]
I will do some more tests after meteor 1.4.2.1 is up and running. 

https://github.com/meteor/meteor/releases

**Comment by albsa** [comment]
hi @abernix it's working now. Maybe it was CDN issue. I was just creating the stable version, using meteor create sample
