### ISSUE TITLE
Mongo $pop always removes last item in array

### ISSUE THREAD

**Issue by indesignlatam** [meteor/meteor#8022]
Im trying to use $pop operator but no matter if I use -1 or 1 it always removes the last item in the array. Still if i run the same modifier directly from mongochef it works correctly as it removes the first item in the array not the last one.

Meteor.users.update({_id: this.userId}, {$pop: {'analytics.lastRoutes': -1}});

-----
Meteor 1.4.2
OSX Sierra

**Comment by abernix** [comment]
Is this something you've only seen more recently and not before?

While I realize it may seem simple, but building reproductions takes a significant amount of core developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Any chance you could make a basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here?  Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by indesignlatam** [comment]
Sure, ill make the repro and post it later. Thanks

**Comment by indesignlatam** [comment]
I will close the issue since I was not able to reproduce the issue on a fresh meteor project.

**Comment by abernix** [comment]
Happy to reopen this issue if you're able to reproduce it, and thanks for reporting it anyhow. :smile:
