### ISSUE TITLE
Cannot run app on Android 4.4

### ISSUE THREAD

**Issue by yanickrochon** [meteor/meteor#8027]
On a tablet running Android 4.4.1, I have created a small WebView container app that I run, which connects to a server URL. This app works because I can use it to access another Web apps just fine, and I have been using it for over two years, now.

However, I just completed a new app with Meteor, and managed to deploy it this weekend... and it works because I can access it just fine with Google Chrome on any PC.

But when I take the Android WebView container app and redirect it to the same URL, I get a JavaScript error 

```
11-07 16:09:39.267 12695-12695/com.vitex.okapi I/chromium: [INFO:CONSOLE(81)] "Uncaught Error: Match error: Expected e", source: http://192.168.2.51/79f86307fc3df874d7ef03cfab0d40821ab26846.js?meteor_js_resource=true (81)
11-07 16:09:39.277 12695-12695/com.vitex.okapi I/chromium: [INFO:CONSOLE(134)] "Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined", source: http://192.168.2.51/79f86307fc3df874d7ef03cfab0d40821ab26846.js?meteor_js_resource=true (134)
```

I'm guessing something's wrong with ol' WebView, so I try the "meteor way" and build my meteor APK package, then sign it, then zipalign it, then push it to the device. Nothing but a white space.

I try `meteor run android-device`, and I get 

```
I20161107-16:13:02.551(-5)? I/chromium(14993): [INFO:library_loader_hooks.cc(112)] Chromium logging enabled: level = 0, default verbosity = 0
I20161107-16:13:02.797(-5)? W/chromium(14993): [WARNING:proxy_service.cc(888)] PAC support disabled because there is no system implementation
I20161107-16:13:02.798(-5)? I/MeteorWebApp(14993): Serving asset bundle with version: 7b29e6fd04c2924ac9914dabefdd93503bd3879f
I20161107-16:13:02.798(-5)? I/chromium(14993): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
I20161107-16:13:02.798(-5)? I/chromium(14993): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
I20161107-16:13:05.840(-5)? I/chromium(14993): [INFO:simple_index_file.cc(397)] Simple Cache Index is being restored from disk.
I20161107-16:13:06.742(-5) (android:http://localhost:12032/cordova.js:1185) deviceready has not fired after 5 seconds.
I20161107-16:13:06.747(-5) (android:http://localhost:12032/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20161107-16:13:12.203(-5) (android:http://localhost:12032/packages/check.js:72) Uncaught Error: Match error: Expected Number
I20161107-16:13:12.475(-5) (android:http://localhost:12032/packages/kadira_flow-router.js:519) There is no route for the path:
```

Again, everything is fine with Google Chrome on all PC, as well as Google Chrome on Android. Android 4.4 is only three years old and still widely used

![android_historical_version_distribution_-_vector svg](https://cloud.githubusercontent.com/assets/78461/20076514/afa978d6-a506-11e6-9509-f1a62ff71a85.png)

How can I debug this and make things work?

**Comment by yanickrochon** [comment]
I gave it another shot, this morning, and enabled `debug` on the build options. The WebView container returns this output :

```
11-08 09:40:06.290 17640-17640/com.vitex.okapi I/chromium: [INFO:CONSOLE(72)] "Uncaught Error: Match error: Expected Number", source: http://192.168.2.51/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057 (72)
11-08 09:40:06.400 17640-17640/com.vitex.okapi I/chromium: [INFO:CONSOLE(519)] "There is no route for the path:", source: http://192.168.2.51/packages/kadira_flow-router.js?hash=fe29e5a71d60015441870884ac391b8d7ea99254 (519)
```

## check.js:72 (packages/check/match.js)
```js
var check = exports.check = function (value, pattern) {                    // 20
  // Record that check got called, if somebody cared.                      // 21
  //                                                                       // 22
  // We use getOrNullIfOutsideFiber so that it's OK to call check()        // 23
  // from non-Fiber server contexts; the downside is that if you forget to // 24
  // bindEnvironment on some random callback in your method/publisher,     // 25
  // it might not find the argumentChecker and you'll get an error about   // 26
  // not checking an argument that it looks like you're checking (instead  // 27
  // of just getting a "Node code must run in a Fiber" error).             // 28
  var argChecker = currentArgumentChecker.getOrNullIfOutsideFiber();       // 29
  if (argChecker)                                                          // 30
    argChecker.checking(value);                                            // 31
  var result = testSubtree(value, pattern);                                // 32
  if (result) {                                                            // 33
    var err = new Match.Error(result.message);                             // 34
    if (result.path) {                                                     // 35
      err.message += " in field " + result.path;                           // 36
      err.path = result.path;                                              // 37
    }                                                                      // 38
    throw err; /// <--- this is where the error is thrown                  // 39
  }                                                                        // 40
};                           
```

I have no stack trace to show, but something is wrong on Android's WebView, because I do not get this error on PC

**Comment by yanickrochon** [comment]
Well, it works with [Crosswalk](https://crosswalk-project.org/documentation/android.html). The [remote debugging](https://crosswalk-project.org/documentation/android/android_remote_debugging.html) is also quite awesome, too!

**Comment by abernix** [comment]
I could not explain why it works in one and not the other.  Unfortunately, there isn't much to work with here and without a reproduction I can only speculate.

Do you have a very large app?  It's possible that the device doesn't have enough memory (or is very slow) and takes a long time to load.  Thus, due to the extensive load time some methods could be timing out?  Maybe the Crosswalk WebView is faster/more-efficient?

Maybe you could try setting a higher app startup time (the default is 10 seconds) using the following [in your `mobile-config.js`](https://guide.meteor.com/mobile.html#configuring-your-app):

    App.setPreference("WebAppStartupTimeout", "20000");

**Comment by yanickrochon** [comment]
This meteor app is an upgrade to another Node.js app that runs just fine in a small WebView container, written in plain Java and deployed on the tablets. Since this app is in-house, on intranet, it will not have automatic updates, therefore using crosswalk is better than build the meteor app for Android and deploying it manually on every client for every updates; with crosswalk, I can just point to the server URL and simply deploy to the server without bothering with the clients.

The app is, indeed, quite large, with many modules and component. The loading time is greater than 10 seconds, for sure. I guess at some point Meteor will implement compartmentalized / lazy loading, which will make things faster, instead of loading one single big JS file over the wireless network?

Or perhaps use Crosswalk as container, since it seems to be updated more often and seems to be faster than plain WebView?

**Comment by abernix** [comment]
Without a reproduction it won't be possible to analyze this and find a solution.  Happy to reopen if you can share a reproduction project repository, but I suspect something edge case is happening here as the Android 4.4 platform (`android-19`) should work fine still.
