### ISSUE TITLE
Mobile manifest asset urls to be different path than root

### ISSUE THREAD

**Issue by javascriptlove** [meteor/meteor#8029]
Meteor version: METEOR@1.4.1.1

I'm not sure which kind of issue is this. We are trying to deploy the application to a separate folder on a domain, say /subfolder/, while the root is for another application (and there's some nginx rewrites involved). And we are also building a mobile app for this. Now, the problem is the urls in the mobile manifest.json

So, i thought providing `--server` with a `http://url.example/subfolder/` will work, but the manifest.json still has the urls inside like this:

> {"path":"app/fonts/my-icons.eot","where":"client","type":"asset","cacheable":false,"url":"/fonts/my-icons.eot","size":15024,"hash":"d1d5d9cff63720ffe631336b2ac816cf2b1d9294"}

So the mobile application tries to load /fonts/my-icons.eot instead of /subfolder/fonts/my-icons.eot and of course fails. I also tried setting the prefix with `WebAppInternals.setBundledJsCssPrefix` but the manifest still has absolute urls pointing to root... Any way to make urls in manifest to look like `/subfolder/fonts/my-icons.eot`?

**Comment by abernix** [comment]
What are you providing `--server` to?  Are you using `meteor run` or are you talking about production ("deployed") using `node main.js`?  If you're talking about a deployed app, are you [setting your `ROOT_URL` with the subfolder properly](https://guide.meteor.com/deployment.html#custom-deployment)?

**Comment by javascriptlove** [comment]
We decided to not use this way as the infrastructure setup becomes very complicated, too much issues arise here and there with the subfolder, ignore this issue..
