### ISSUE TITLE
Improvement to error message

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#8034]
While investigating a problem that appears to be in the angular2 meteor compilers, there is an exception thrown from the core: /tools/isobuild/compiler-plugin.js:698
But this error gives no indication of the file which caused the problem - I would have wasted a lot less time if the filename had been given.

See https://github.com/Urigo/angular2-meteor/issues/427 and https://github.com/Urigo/angular-meteor/issues/1466

These issues themselves may not be in the meteor core, but it will save others time when investigating similar issues in this area in the future.

One option would be to change the throw itself in ResourceSlot.addAsset():

    throw new Error("'data' option to addAsset must be a Buffer or String. Path " + options.path);

Interestingly the similar ResourceSlot.addHtml() already outputs the file path in its errors.

Issue noticed in meteor 1.4.2.

**Comment by abernix** [comment]
I agree that the fix might be just that easy, but is there a simple reproduction you could provide that could be used to verify that the fix works properly?

**Comment by sdarnell** [comment]
The simplest reproduction is to use the angular2-boilerplate (https://github.com/bsliran/angular2-meteor-base). Then running `meteor --production`.

As the issue is now fixed in the angular2 compilers, it would be necessary to use an *older* version of these meteor packages:
```
 angular2-compilers 0.6.5
 barbatus:css-compiler 0.3.5
```

I made the single change I mentioned by hacking the .js files on an installed setup, and modified the single case that I needed, i.e.:
```
throw new Error("'data' option to addAsset must be a Buffer or String. Path " + options.path);
```
But there are a couple of similar messages in the same routine.

Given the simplicity of the change it probably will be a lot quicker if someone who is already setup to prepare the change, but if not I can probably find the time to do it.

**Comment by abernix** [comment]
Thanks for this and the reproduction steps.  I've submitted #8104 to hopefully fix this. :smile:

***

Just to further simplify the reproduction, encountering this is as easy as:

```sh
$ git clone https://github.com/bsliran/angular2-meteor-base 8034
$ cd 8034
$ git checkout f3eded9
$ meteor
```

#### Before PR
```
=> Errors prevented startup:

   While processing files with angular2-compilers (for target web.browser):
   /tools/isobuild/compiler-plugin.js:729:15: 'data' option to addAsset must be a Buffer or String:
   node_modules/meteor-rxjs/examples/angular2/client/imports/app/app.component.scss
   at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:729:15)
   at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:494:24)
```

#### After PR
```
=> Errors prevented startup:

   While processing files with angular2-compilers (for target web.browser):
   /tools/isobuild/compiler-plugin.js:729:15: 'data' option to addAsset must be a Buffer or String
   at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:729:15)
   at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:494:24)
```

**Comment by sdarnell** [comment]
Brilliant, thanks!
