### ISSUE TITLE
[1.4.2.1] Input fields are losing their read-only attribute since the new patch

### ISSUE THREAD

**Issue by programthis** [meteor/meteor#8046]
As the title states, input fields no longer have their read-only attribute when the app is initially loaded. I've found that this seems to only affect inputs within templates that are initially hidden and then made visible via an instance variable. 

I downgraded back to 1.4.2 just to be sure and this does seem to resolve the issue.

**More details**:
- using Blaze 
- other attributes still seem to work fine, such as "disabled"

**Packages**:
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.14                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.1                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.2   # CSS minifier run for production mode
standard-minifier-js@1.2.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.9              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.1            # Server-side component of the `meteor shell` command

fourseven:scss
tmeasday:presence
accounts-password@1.3.2
aldeed:simple-schema
aldeed:collection2
check@1.2.4
zimme:active-route
reactive-dict@1.1.8
kadira:flow-router
kadira:blaze-layout
arillo:flow-router-helpers
rcy:nouislider
ostrio:files

**Versions**:
 accounts-base@1.2.14
 -accounts-password@1.3.1
 +accounts-password@1.3.2
  aldeed:collection2@2.10.0
  aldeed:collection2-core@1.2.0
  aldeed:schema-deny@1.1.0
 -aldeed:schema-index@1.1.0
 +aldeed:schema-index@1.1.1
  aldeed:simple-schema@1.5.3
  allow-deny@1.0.5
  arillo:flow-router-helpers@0.5.2
  autoupdate@1.3.12
  babel-compiler@6.13.0
 -babel-runtime@0.1.12
 +babel-runtime@1.0.0
  base64@1.0.10
  binary-heap@1.0.10
 -blaze@2.1.9
 +blaze@2.2.0
  blaze-html-templates@1.0.5
  blaze-tools@1.0.10
  boilerplate-generator@1.0.11
 -caching-compiler@1.1.8
 +caching-compiler@1.1.9
  caching-html-compiler@1.0.7
  callback-hook@1.0.10
  check@1.2.4
  chuangbo:cookie@1.1.0
 -coffeescript@1.11.1_2
 +coffeescript@1.11.1_3
  ddp@1.2.5
  ddp-client@1.3.2
 -ddp-common@1.2.7
 +ddp-common@1.2.8
  ddp-rate-limiter@1.0.6
 -ddp-server@1.3.11
 +ddp-server@1.3.12
  deps@1.0.12
  diff-sequence@1.0.7
 -ecmascript@0.5.9
 +ecmascript@0.6.0
  ecmascript-runtime@0.3.15
  ejson@1.0.13
  email@1.1.18
  es5-shim@4.6.15
  fastclick@1.0.13
 -fourseven:scss@3.10.0
 +fourseven:scss@3.10.1
  geojson-utils@1.0.10
  hot-code-push@1.0.4
  html-tools@1.0.11
htmljs@1.0.11
http@1.2.10
id-map@1.0.9
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.0
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
mdg:validation-error@0.5.1
meteor@1.6.0
meteor-base@1.0.4
meteorhacks:fast-render@2.16.0
meteorhacks:inject-data@2.0.0
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
minifier-css@1.2.15
minifier-js@1.2.15
minimongo@1.0.18
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.7
mongo@1.1.14
mongo-id@1.0.6
npm-bcrypt@0.9.2
npm-mongo@2.2.11_2
observe-sequence@1.0.14
ordered-dict@1.0.9
ostrio:cookies@2.0.5
ostrio:files@1.7.5
promise@0.8.8
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.6
rcy:nouislider@7.0.7_2
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
sha@1.0.9
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.10
standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.0.5
tmeasday:presence@1.0.6
tracker@1.1.1
ui@1.0.12
underscore@1.0.10
url@1.0.11
webapp@1.3.12
webapp-hashing@1.0.9
zimme:active-route@2.3.2

Edit: added further details

**Comment by abernix** [comment]
Thanks for filing a bug report for what you believe to be a bug with Meteor.  Unfortunately, I'm not sure how you expect anyone to help with this based on what you've provided.  Please provide the information requested in the body of the issue text before you replaced it when opening a new issue (as also stated in the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) instructions).  Namely:

- [ ] What packages or other dependencies you're using
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

You haven't even specified if you are using Blaze, Angular or React (which are _actually_ responsible for rendering the HTML) which could be breaking on their own.  Did any other packages update when you updated to 1.4.2.1?  (You can compare your `.meteor/versions` file).

**Comment by programthis** [comment]
@abernix Thank you, I've updated my comment with further details. I am working off a private repo but will work to create a public demo to try to replicate the issue.

**Comment by pmysinski** [comment]
I got this bug also. 
It appear after update blaze@2.1.9 to blaze@2.2.0

repo with bug reporoduce (just fresh project with new version of blaze and 2 imputs with readonly):
https://github.com/pmysinski/meteor-issue-8046-reproduce

**Comment by abernix** [comment]
Issue moved to [meteor/blaze #163](https://github.com/meteor/blaze/issues/163) via [**ZenHub**](https://www.zenhub.com/)

**Comment by abernix** [comment]
Thanks to you both for the update!  I can confirm this behavior by using the repo provided by @pmysinski:

On initial load, the second `number` field remains `readonly` when using `blaze@2.1.9`.  However, after updating to `blaze@2.2.0` it no longer starts as `readonly`.  Likely related to meteor/blaze#52.

However!  I will move this over to [meteor/blaze #163](https://github.com/meteor/blaze/issues/163) as [Blaze 🔥](https://blazejs.org) now has its own repository (just FYI, as you'll probably get a quicker response over there)

😄
