### ISSUE TITLE
[1.4.2.1] Oplog flooding (100% CPU)

### ISSUE THREAD

**Issue by Maxpain177** [meteor/meteor#8047]
With a large count CRUD operations per second in a collection, which NOT using in my meteor app, CPU load sometimes stucks to 100% 

Maybe you make it possible specify which collections needs listening oplog mongodb operations?

**Comment by choyweston** [comment]
This is already doable, see : http://info.meteor.com/blog/tuning-meteor-mongo-livedata-for-scalability

**Comment by Maxpain177** [comment]
@choyweston Yes, i readed this article. But i can't move high velocity to another logical database, because it used in another meteor applications, connected to this database.

Maybe make ability to **specify needs collection oplog or not**?
Example with [```mongo-oplog``` package via npm](https://www.npmjs.com/package/mongo-oplog):
```javascript
var oplog = MongoOplog('mongodb://127.0.0.1:27017/local', { ns: 'test.posts' }).tail();
There are we subscribe ONLY to the posts collection of test database, NOT ALL collections
```

**Comment by choyweston** [comment]
I'm not sure I follow. What you want is exactly what's in the article, no? We have successfully used the info in that article to turn on/off oplog tailing on a per collection basis in production.

**Comment by Maxpain177** [comment]
@choyweston No, in article oplog disabled with passing ```disableOplog: true``` to query, but it's not prevent mongo sending oplog events to this collection. Meteor reads ALL oplog messages, but we need only certain collections.

**Comment by choyweston** [comment]
I believe tailing the log doesn't cost memory, it's updating the server's local collection cache. It only does this for collections that have oplog turned on.

**Comment by ignl** [comment]
Try this new solution with redis: https://forums.meteor.com/t/meteor-scaling-redis-oplog-status-1-0-4/30855/120

**Comment by Maxpain177** [comment]
@ignl wow, nice. thx 👍

**Comment by ramezrafla** [comment]
We use redis-oplog in production and it works great, and I frankly believe it's the solution going forward for scalability. Can we we close this issue?

**Comment by ramezrafla** [comment]
@Maxpain177, can we close?

**Comment by Maxpain177** [comment]
@ramezrafla Yes
