### ISSUE TITLE
medium-editor-tables peer dependencies not honored. 

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#8054]
I have `medium-editor-tables@0.6.1` installed which has  `peerDepenency` of `"medium-editor": "^5.5.1"`. Which I have installed.

When I run my meteor app I get an error that `MediumEditor` is not defined inside of medium-editor-tables. Outside of that npm module `MeteorEditor` is defined. The packages were installed using 

meteor npm install medium-editor-tables --save 
meteor npm install medium-editor@5.5.1 --save

it is worth noting that I got a warning on `npm WARN saveError extraneous: medium-editor@5.5.1 /path/to/module/` initially, but I fixed this by adding the dependency to my projects package.json

The packages are imported into my app as follows:
import MediumEditor from 'medium-editor';
import MediumEditorTable from 'medium-editor-tables';

I am running Meteor 1.4.2 on Ubuntu

**Comment by abernix** [comment]
While I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by abernix** [comment]
(To be fair, I suspect there could actually be an issue here, but please submit a reproduction for the sake of simplicity and clearly showing your problem).

Also, it's probably worth noting since Meteor uses NPM v3:

> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. The behavior in npms 1 & 2 was frequently confusing and could easily put you into dependency hell, a situation that npm is designed to avoid as much as possible.

**Comment by abernix** [comment]
@znewsham Can you please provide a reproduction?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
