### ISSUE TITLE
I install meteor 1.4.2.1 today in windows server 2016 ,but is dosnot work . 

### ISSUE THREAD

**Issue by yanghai100** [meteor/meteor#8060]
I install the meteor 1.4.2.1 from the www.meteor.com  sucess.  when I run  meteor create myapp.It is ok.   
C:\Users\Administrator\app1>meteor
[[[[[ C:\Users\Administrator\app1 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

But when I use IE  http://localhost:3000/,   I get nothing.

**Comment by hwillson** [comment]
A couple of questions:

1. Have you verified that Windows Firewall isn't restricting [http://localhost:3000]() access? You can always try shutting the firewall off completely just to verify.
2. Your console dump shows the `Control-C` cancel message; I'm assuming this was just added as you copied from your console after stopping `meteor`, but just want to make sure - you are leaving `meteor` running when you test your app, correct?

**Comment by yanghai100** [comment]
1:I only use one computer.and I had shutdown firewall.
2:I keep meteor running when I test my app,and in IE can get the source of the web page, But dos not show anything in the normal model.    
3:4 weeks ago I install meteor (maybe 1.4.2 )  in another pc (the same os ),it work well.

**Comment by hwillson** [comment]
Would you be able to link to a small reproduction app that shows this problem, so we can try it out?

**Comment by benjamn** [comment]
Any JavaScript errors in the Developer Tools console?

**Comment by yanghai100** [comment]
I just begin with meteor in a new pc. and just us the meteor create myapp .  dan cd to myapp run meteor..
This is the source code of http://localhost:3000.   
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=ab162e5272bdf82a965260a90b059f552052eab9">
<title>myapp</title>

</head>
<body>



<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.4.2.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22development%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%2210i1905gbxqeq15tkbi6%22%2C%22autoupdateVersion%22%3A%2226274a38a523b86ea7fcedfe2ea66a7c1fcf4346%22%2C%22autoupdateVersionRefreshable%22%3A%22755c0dbaa5052417a882cd6d91c643db4113373f%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>

  <script type="text/javascript" src="/packages/underscore.js?hash=8993f1a8af5a53c8887a593804b7594ee040ef91"></script>
  <script type="text/javascript" src="/packages/meteor.js?hash=f9ccb2ff6079255e5772603b7fc6c401e5161ae6"></script>
  <script type="text/javascript" src="/packages/meteor-base.js?hash=93d647d4f37895a036c061cc57cf6eba719db451"></script>
  <script type="text/javascript" src="/packages/mobile-experience.js?hash=8932e82d8a85c8f775a6518d83363d240724658b"></script>
  <script type="text/javascript" src="/packages/modules-runtime.js?hash=5b5615c907a5b9a4d19081582f04748e2ad64275"></script>
  <script type="text/javascript" src="/packages/modules.js?hash=8bd208e22f101a05f9b945e4089cb46d6548ee6c"></script>
  <script type="text/javascript" src="/packages/es5-shim.js?hash=fabfa8e9e2d0f4157a9d1c29bbabdcf24e2d2e78"></script>
  <script type="text/javascript" src="/packages/promise.js?hash=3ab617c320606d918992f9f7b81c030b2152c359"></script>
  <script type="text/javascript" src="/packages/ecmascript-runtime.js?hash=2c3308cfd5d8e27923a4d9caab1d73abddf96ad8"></script>
  <script type="text/javascript" src="/packages/babel-compiler.js?hash=b00c58b51946517d0662ab00589293b2aa55d8cb"></script>
  <script type="text/javascript" src="/packages/ecmascript.js?hash=32ba8df5a5f394369ec54dd7fbb58279aed7afc1"></script>
  <script type="text/javascript" src="/packages/base64.js?hash=436cac2bc143a581f5edb93822b412ee15a641ab"></script>
  <script type="text/javascript" src="/packages/ejson.js?hash=0ac1c5b2e1a7164cf90e47298f5411133f6590b1"></script>
  <script type="text/javascript" src="/packages/id-map.js?hash=073be1ff6bd3a1dceeda0094b4761e7545568926"></script>
  <script type="text/javascript" src="/packages/ordered-dict.js?hash=4c13482516a43fc43f1708a2b854c547ae6c0322"></script>
  <script type="text/javascript" src="/packages/tracker.js?hash=e52e5febdef644d89e21db20456ef53daa80b912"></script>
  <script type="text/javascript" src="/packages/babel-runtime.js?hash=319717090c2ac435c1269c6623746eec03f17a48"></script>
  <script type="text/javascript" src="/packages/random.js?hash=f640404ff5ee70d6d48ddfb3846f43033005cfd6"></script>
  <script type="text/javascript" src="/packages/mongo-id.js?hash=cc69777cbac99617738749584c6868b4949d52e1"></script>
  <script type="text/javascript" src="/packages/diff-sequence.js?hash=6d33d619a37b4bbd3db717ee6c2a25c5d880b9bd"></script>
  <script type="text/javascript" src="/packages/geojson-utils.js?hash=49d3a92226e81d44af8ae4c2896ef2dda465b906"></script>
  <script type="text/javascript" src="/packages/minimongo.js?hash=8aad8cfd5810181a65321d853cab302b956e5322"></script>
  <script type="text/javascript" src="/packages/check.js?hash=d4de24f57efd5d716b6ce9a7a90bf6a91b307bf4"></script>
  <script type="text/javascript" src="/packages/retry.js?hash=5179d91da075444c09bc870af3e6fcbd8be695b6"></script>
  <script type="text/javascript" src="/packages/ddp-common.js?hash=7e3f0c9d877af74b7eb5219d6bfbe02794a818ca"></script>
  <script type="text/javascript" src="/packages/reload.js?hash=b2d1086fd7bbc28deb93350f437ce0eef242baa3"></script>
  <script type="text/javascript" src="/packages/ddp-client.js?hash=98f50c1583d868f0e596ecb98ed32c7eb2bddf6d"></script>
  <script type="text/javascript" src="/packages/ddp.js?hash=6dc7ae4d7e07b3c1c2140c88207b0d1e5e1a0d48"></script>
  <script type="text/javascript" src="/packages/ddp-server.js?hash=d113bccbffeb5a7e546434f1fac70878711c2a7e"></script>
  <script type="text/javascript" src="/packages/allow-deny.js?hash=3f84d98a06ac6f4ce21a196fb538a26f443f2844"></script>
  <script type="text/javascript" src="/packages/insecure.js?hash=4b295c398ffa84184b91d904043e9e8801ba69a8"></script>
  <script type="text/javascript" src="/packages/mongo.js?hash=3037285b99384cbead7ba1aaeb2db56a6649844e"></script>
  <script type="text/javascript" src="/packages/blaze-html-templates.js?hash=c67208d05b555c4228d83b2405f5af35c49b4264"></script>
  <script type="text/javascript" src="/packages/reactive-var.js?hash=b25ee746b44781237ab7802c5c3e26f157d70f79"></script>
  <script type="text/javascript" src="/packages/jquery.js?hash=c334cf567e6848a1be3bd6860af8fe51f4ec80d8"></script>
  <script type="text/javascript" src="/packages/standard-minifier-css.js?hash=4729ce7dffa9ae5758614ef6acc829c97f9d1a7c"></script>
  <script type="text/javascript" src="/packages/standard-minifier-js.js?hash=a031e40f1a0f9fce4faef0ed51e29b013a6db9cd"></script>
  <script type="text/javascript" src="/packages/shell-server.js?hash=4394561ca518e68c6afd82fb18f2ffd2bc857382"></script>
  <script type="text/javascript" src="/packages/autopublish.js?hash=68dc4461d748ea3192f806fccdd29c126ee67487"></script>
  <script type="text/javascript" src="/packages/webapp.js?hash=36c340ee6c6a8d16c5c7d86b37d49ea289c2f94e"></script>
  <script type="text/javascript" src="/packages/livedata.js?hash=1d9db383b44995f92eb98e4cb5147d2d131a01dd"></script>
  <script type="text/javascript" src="/packages/hot-code-push.js?hash=20d98403e9d70c1747f66e39e53c40a698ed52ed"></script>
  <script type="text/javascript" src="/packages/observe-sequence.js?hash=b3cb82139f8fd6c22829b3df6fd2c32bb916a7de"></script>
  <script type="text/javascript" src="/packages/deps.js?hash=c36fc64ce30e924d45bce6a107fff9a632d45275"></script>
  <script type="text/javascript" src="/packages/htmljs.js?hash=8d2db4c368cbbfa312714f5c365a2cf3d06628be"></script>
  <script type="text/javascript" src="/packages/blaze.js?hash=891d5a10d82b5122032ced96aa7f478b9b1eeda3"></script>
  <script type="text/javascript" src="/packages/spacebars.js?hash=dcb91068ed863bb067d30163ef7df2825655ee2f"></script>
  <script type="text/javascript" src="/packages/templating-compiler.js?hash=690bba8fa767827db955ce0fc3d10fc843a3d1a4"></script>
  <script type="text/javascript" src="/packages/templating-runtime.js?hash=749efb29207446a35b1f57122fe3addfc91b48f9"></script>
  <script type="text/javascript" src="/packages/templating.js?hash=e9da1c8d6e477c7c82f09453606c327a7bedafef"></script>
  <script type="text/javascript" src="/packages/launch-screen.js?hash=194b0c013b70a3bd3455d45f1280f5ad49ae27e7"></script>
  <script type="text/javascript" src="/packages/ui.js?hash=fc78c44dfbf2de9fad367ec371fd79f9592aa151"></script>
  <script type="text/javascript" src="/packages/autoupdate.js?hash=06596bbf5334f2c47212fcdc3679f0e8c7a21075"></script>
  <script type="text/javascript" src="/packages/global-imports.js?hash=14975d7caf4850c9c6f57e1bdce3e358a27f49ba"></script>
  <script type="text/javascript" src="/app/app.js?hash=044b7a747a65ba913b2f5411a23532dca9f9c008"></script>


</body>
</html>

**Comment by yanghai100** [comment]
I have copy the source code of myapp page in my last comment but I can read this content in mormal model.  The same problem in my computer. By the way ,I use the chinese charatctor windows version. and I try in ubuntu 16.04 (chinese), is the same problem.

**Comment by yanghai100** [comment]
`<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=ab162e5272bdf82a965260a90b059f552052eab9">
<title>myapp</title>

</head>
<body>



<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.4.2.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22development%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%2210i1905gbxqeq15tkbi6%22%2C%22autoupdateVersion%22%3A%2226274a38a523b86ea7fcedfe2ea66a7c1fcf4346%22%2C%22autoupdateVersionRefreshable%22%3A%22755c0dbaa5052417a882cd6d91c643db4113373f%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>

  <script type="text/javascript" src="/packages/underscore.js?hash=8993f1a8af5a53c8887a593804b7594ee040ef91"></script>
  <script type="text/javascript" src="/packages/meteor.js?hash=f9ccb2ff6079255e5772603b7fc6c401e5161ae6"></script>
  <script type="text/javascript" src="/packages/meteor-base.js?hash=93d647d4f37895a036c061cc57cf6eba719db451"></script>
  <script type="text/javascript" src="/packages/mobile-experience.js?hash=8932e82d8a85c8f775a6518d83363d240724658b"></script>
  <script type="text/javascript" src="/packages/modules-runtime.js?hash=5b5615c907a5b9a4d19081582f04748e2ad64275"></script>
  <script type="text/javascript" src="/packages/modules.js?hash=8bd208e22f101a05f9b945e4089cb46d6548ee6c"></script>
  <script type="text/javascript" src="/packages/es5-shim.js?hash=fabfa8e9e2d0f4157a9d1c29bbabdcf24e2d2e78"></script>
  <script type="text/javascript" src="/packages/promise.js?hash=3ab617c320606d918992f9f7b81c030b2152c359"></script>
  <script type="text/javascript" src="/packages/ecmascript-runtime.js?hash=2c3308cfd5d8e27923a4d9caab1d73abddf96ad8"></script>
  <script type="text/javascript" src="/packages/babel-compiler.js?hash=b00c58b51946517d0662ab00589293b2aa55d8cb"></script>
  <script type="text/javascript" src="/packages/ecmascript.js?hash=32ba8df5a5f394369ec54dd7fbb58279aed7afc1"></script>
  <script type="text/javascript" src="/packages/base64.js?hash=436cac2bc143a581f5edb93822b412ee15a641ab"></script>
  <script type="text/javascript" src="/packages/ejson.js?hash=0ac1c5b2e1a7164cf90e47298f5411133f6590b1"></script>
  <script type="text/javascript" src="/packages/id-map.js?hash=073be1ff6bd3a1dceeda0094b4761e7545568926"></script>
  <script type="text/javascript" src="/packages/ordered-dict.js?hash=4c13482516a43fc43f1708a2b854c547ae6c0322"></script>
  <script type="text/javascript" src="/packages/tracker.js?hash=e52e5febdef644d89e21db20456ef53daa80b912"></script>
  <script type="text/javascript" src="/packages/babel-runtime.js?hash=319717090c2ac435c1269c6623746eec03f17a48"></script>
  <script type="text/javascript" src="/packages/random.js?hash=f640404ff5ee70d6d48ddfb3846f43033005cfd6"></script>
  <script type="text/javascript" src="/packages/mongo-id.js?hash=cc69777cbac99617738749584c6868b4949d52e1"></script>
  <script type="text/javascript" src="/packages/diff-sequence.js?hash=6d33d619a37b4bbd3db717ee6c2a25c5d880b9bd"></script>
  <script type="text/javascript" src="/packages/geojson-utils.js?hash=49d3a92226e81d44af8ae4c2896ef2dda465b906"></script>
  <script type="text/javascript" src="/packages/minimongo.js?hash=8aad8cfd5810181a65321d853cab302b956e5322"></script>
  <script type="text/javascript" src="/packages/check.js?hash=d4de24f57efd5d716b6ce9a7a90bf6a91b307bf4"></script>
  <script type="text/javascript" src="/packages/retry.js?hash=5179d91da075444c09bc870af3e6fcbd8be695b6"></script>
  <script type="text/javascript" src="/packages/ddp-common.js?hash=7e3f0c9d877af74b7eb5219d6bfbe02794a818ca"></script>
  <script type="text/javascript" src="/packages/reload.js?hash=b2d1086fd7bbc28deb93350f437ce0eef242baa3"></script>
  <script type="text/javascript" src="/packages/ddp-client.js?hash=98f50c1583d868f0e596ecb98ed32c7eb2bddf6d"></script>
  <script type="text/javascript" src="/packages/ddp.js?hash=6dc7ae4d7e07b3c1c2140c88207b0d1e5e1a0d48"></script>
  <script type="text/javascript" src="/packages/ddp-server.js?hash=d113bccbffeb5a7e546434f1fac70878711c2a7e"></script>
  <script type="text/javascript" src="/packages/allow-deny.js?hash=3f84d98a06ac6f4ce21a196fb538a26f443f2844"></script>
  <script type="text/javascript" src="/packages/insecure.js?hash=4b295c398ffa84184b91d904043e9e8801ba69a8"></script>
  <script type="text/javascript" src="/packages/mongo.js?hash=3037285b99384cbead7ba1aaeb2db56a6649844e"></script>
  <script type="text/javascript" src="/packages/blaze-html-templates.js?hash=c67208d05b555c4228d83b2405f5af35c49b4264"></script>
  <script type="text/javascript" src="/packages/reactive-var.js?hash=b25ee746b44781237ab7802c5c3e26f157d70f79"></script>
  <script type="text/javascript" src="/packages/jquery.js?hash=c334cf567e6848a1be3bd6860af8fe51f4ec80d8"></script>
  <script type="text/javascript" src="/packages/standard-minifier-css.js?hash=4729ce7dffa9ae5758614ef6acc829c97f9d1a7c"></script>
  <script type="text/javascript" src="/packages/standard-minifier-js.js?hash=a031e40f1a0f9fce4faef0ed51e29b013a6db9cd"></script>
  <script type="text/javascript" src="/packages/shell-server.js?hash=4394561ca518e68c6afd82fb18f2ffd2bc857382"></script>
  <script type="text/javascript" src="/packages/autopublish.js?hash=68dc4461d748ea3192f806fccdd29c126ee67487"></script>
  <script type="text/javascript" src="/packages/webapp.js?hash=36c340ee6c6a8d16c5c7d86b37d49ea289c2f94e"></script>
  <script type="text/javascript" src="/packages/livedata.js?hash=1d9db383b44995f92eb98e4cb5147d2d131a01dd"></script>
  <script type="text/javascript" src="/packages/hot-code-push.js?hash=20d98403e9d70c1747f66e39e53c40a698ed52ed"></script>
  <script type="text/javascript" src="/packages/observe-sequence.js?hash=b3cb82139f8fd6c22829b3df6fd2c32bb916a7de"></script>
  <script type="text/javascript" src="/packages/deps.js?hash=c36fc64ce30e924d45bce6a107fff9a632d45275"></script>
  <script type="text/javascript" src="/packages/htmljs.js?hash=8d2db4c368cbbfa312714f5c365a2cf3d06628be"></script>
  <script type="text/javascript" src="/packages/blaze.js?hash=891d5a10d82b5122032ced96aa7f478b9b1eeda3"></script>
  <script type="text/javascript" src="/packages/spacebars.js?hash=dcb91068ed863bb067d30163ef7df2825655ee2f"></script>
  <script type="text/javascript" src="/packages/templating-compiler.js?hash=690bba8fa767827db955ce0fc3d10fc843a3d1a4"></script>
  <script type="text/javascript" src="/packages/templating-runtime.js?hash=749efb29207446a35b1f57122fe3addfc91b48f9"></script>
  <script type="text/javascript" src="/packages/templating.js?hash=e9da1c8d6e477c7c82f09453606c327a7bedafef"></script>
  <script type="text/javascript" src="/packages/launch-screen.js?hash=194b0c013b70a3bd3455d45f1280f5ad49ae27e7"></script>
  <script type="text/javascript" src="/packages/ui.js?hash=fc78c44dfbf2de9fad367ec371fd79f9592aa151"></script>
  <script type="text/javascript" src="/packages/autoupdate.js?hash=06596bbf5334f2c47212fcdc3679f0e8c7a21075"></script>
  <script type="text/javascript" src="/packages/global-imports.js?hash=14975d7caf4850c9c6f57e1bdce3e358a27f49ba"></script>
  <script type="text/javascript" src="/app/app.js?hash=044b7a747a65ba913b2f5411a23532dca9f9c008"></script>


</body>
</html>`

**Comment by yanghai100** [comment]
[the error page source code.txt](https://github.com/meteor/meteor/files/596442/the.error.page.source.code.txt)

**Comment by abernix** [comment]
@yanghai100 That source code looks correct.  Please try this:

* Go to `http://localhost:3000/` in Internet Explorer
* Open the "F12 Developer Tools" (either push F12 on your keyboard or click it in the :gear: menu)
* Click on "Console"
* Are there any error messages here?

**Comment by yanghai100** [comment]
@abernix  thank you very much!   I use your method .  And  I fond the problem is I had not run the meteor bpm install --save babel-runtime     in my project folder.   And is work well now .  So I need run this command in my ervery new porject ?

**Comment by hwillson** [comment]
@yanghai100 - Any new project created using 1.4.2.1 or later will automatically include the `babel-runtime` dependency in its `package.json`. When you run your first `meteor npm install`, it will be installed. Only projects created before 1.4.2.1 that don't have this dependency in place yet (and have since been updated to >= 1.4.2.1), need to have it added manually.

**Comment by hwillson** [comment]
Since the problem has been found and resolved, I'll close this off - keep us posted if you notice anything else. Thanks!
