### ISSUE TITLE
simple skeleton android login fails

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#8062]
you cannot login to a skelton android app with meteor-developer or ANY login service with callback

error ->invalid redirect URI [400]
YET chrome login is fine !!

scalingo.io provides the ssl 
tests show a skeleton app may or may not work
tests show a LARGE app FAILS but may at time work

**Comment by interfaith** [comment]
now it works !
so removing crosswalk allows the login
ho ho ho

**Comment by interfaith** [comment]
now to add crosswalk

**Comment by interfaith** [comment]
now crosswalk works
something got fixed !!
yeah !!

**Comment by interfaith** [comment]
fixed ! meteor  is fixed for crosswalk/android 3rd party login

**Comment by interfaith** [comment]
some skeleton app may allow twitter login
however larger apps STILL fail
i hope the new crosswalk/webview will allow login

**Comment by interfaith** [comment]
use A 2ND APP IN TWITTER FOR ANDROID via 127.0.0.1 callback
so 2 APPS ARE USED 
meteor did not divulge this TRICK

**Comment by hwillson** [comment]
Thanks for posting this @interfaith - since issue #8097 (that you posted) is almost the exact same as this issue, I'll close this one off.
