### ISSUE TITLE
Meteor wont work with ipv6

### ISSUE THREAD

**Issue by akshatster** [meteor/meteor#8066]
Meteor can't bind with ipv6

Reproduction

```
meteor create demo
BIND_IP="::" meteor
```

then test it with curl:
```
curl http://[::]:3000
```

Gives back
```
curl: (7) Failed to connect to :: port 3000: Connection refused
```

ipv4 works:

```
curl http://0.0.0.0:3000

<!DOCTYPE html>
<html>
...
```

**Comment by abernix** [comment]
Thanks for bringing this up.  I'm not certain, but there's probably some documentation that needs to be updated for this.  If you find any, please open an issue with the [docs repo](https://github.com/meteor/docs), or preferably open a pull-request with the fix!

But to explain, `BIND_IP` isn't intended to work with your development environment.  It's only for the bundled version (i.e. production) which you produce with `meteor build`.

In development, if you need to bind to a specific interface (or *all* interfaces, as you're trying here), you just use `--port`.  Simply add the hostname before the port number.  For example, to bind to all interfaces, use:

    meteor --port 0.0.0.0:3000

For IPv6, it's very similar, just make sure you use the bracket notation to differentiate from the `:port`:

    meteor --port [::]:3000

Please do open issues/submit pull requests to docs if this wasn't clear!
