### ISSUE TITLE
cordova-plugin-crosswalk-webview was release 2.2.0, which requires cordova-android 6.0.0 or newer

### ISSUE THREAD

**Issue by feit** [meteor/meteor#8071]
cordova-plugin-crosswalk-webview was release 2.2.0, which requires cordova-android 6.0.0 or newer

**Comment by feit** [comment]
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/103

**Comment by abernix** [comment]
Is this just an "FYI"?  Are you asking for the Atmosphere `crosswalk` package be updated to `cordova-plugin-crosswalk-webview@2.2.0`?  Are you asking for the Android platform to update from 5.2.2 to 6.x?  Are you running into a problem?  Are you getting an error?

Please be more clear when [opening an issue](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).  Honestly, the issue you linked to makes it sounds like it might be best to wait until they sort out the sem-ver version bump to coincide with the platform update.

**Comment by cyclops24** [comment]
@abernix I can't use crosswalk at all. I post my issue here:
https://github.com/meteor/meteor/issues/8135

Can you see this man?

**Comment by hwillson** [comment]
Closing as we haven't received any response to the additional questions asked in https://github.com/meteor/meteor/issues/8071#issuecomment-261526441 (which were asked to help figure out how to proceed with this issue). Happy to re-open if you can clarify the intent of this issue. Thanks!

**Comment by guilhermedecampo** [comment]
Hi @hwillson this is really a valid issue.

https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#220-november-4-2016

As you can see in the crosswalk project they made cordova-android >= 6.0.0 a requirement and the last mention on cordova-android changes on meteor history is

https://github.com/meteor/meteor/blob/devel/History.md#v142-2016-10-25

So indeed the crosswalk package hosted by meteor does not work.

**Comment by abernix** [comment]
@guilhermedecampo `cordova-plugin-crosswalk-webview` is actually updated to `2.2.0` in Meteor 1.4.3.x, which also updated `cordova-lib` to 6.4.0, `cordova-android` to 6.1.1 and `cordova-ios` to 4.3.0.  Please see [the other updates in #8239](https://github.com/meteor/meteor/pull/8239/files).

Meteor 1.4.3.1 is actually published right now and coming very soon, but we haven't officially announced it yet.

    meteor update --release 1.4.3.1

I just added https://github.com/meteor/meteor/commit/1fd96bd6f567a056f6be6497ae818a5cca63c535, which should have been there already.  Thanks for the note.  If you do encounter additional problems after 1.4.3.1, the request to add some additional information as to what's wrong still stands.  😃

**Comment by guilhermedecampo** [comment]
Thank you guys! You rock as always.
