### ISSUE TITLE
Meteor.findOne except mongo.objectId

### ISSUE THREAD

**Issue by aboobakkar** [meteor/meteor#8072]
![er1](https://cloud.githubusercontent.com/assets/6416738/20429963/b77f62f0-adb7-11e6-906a-3675bd5aca7f.png)
terminal shows data on findOne. but meteor programming 

let data1 = Tasks.findOne({mobile:"9747"}); The output is undefined

**Comment by hwillson** [comment]
Hi @aboobakkar - based on your screenshot, there are two problems:

1. Your `findOne` is trying to match on `mobile` using a string, but your data is stored as a number. You will have better luck with: `Tasks.findOne({ mobile: 9747 })`

2. I'm assuming this is just a typo, but your failed example is using `9747` whereas your data shows `9646`.

This isn't an issue with Meteor, so I'll close this off. Thanks!
