### ISSUE TITLE
Feature request: Build size (ala webpack)

### ISSUE THREAD

**Issue by timbrandin** [meteor/meteor#8073]
Would be great to always see the build size of the project you're working on. That way to know how much impact adding a module adds. It would be interesting both for client and for server, but mostly for the client build. I think it would be sufficient with whatever webpack does.

**Comment by benjamn** [comment]
I agree! Breaking it down by package would also be super helpful, though application `node_modules` get shared between multiple packages. The `meteor/modules` package bears the burden of those `node_modules` files, even though the application and other packages are responsible for which `node_modules` are bundled.

**Comment by mjmasn** [comment]
Of all the things I'd like to see, how big our apps have grown is not one of them 😆

**Comment by timbrandin** [comment]
@benjamn is this a good place to start looking at a solution? https://github.com/meteor/meteor/blob/devel/tools/isobuild/bundler.js#L1174-L1213

**Comment by hwillson** [comment]
Now that we have the [`bundle-visualizer`](https://github.com/meteor/meteor/tree/devel/packages/non-core/bundle-visualizer) (and the `<hash>.stats.json` files that get written alongside file bundles), I think we can close this off. Thanks!
