### ISSUE TITLE
Meteor ships with a module 'crypto' that breaks some 3rd party libraries that depend on node.js crypto

### ISSUE THREAD

**Issue by Netherdrake** [meteor/meteor#8074]
Meteor 1.4.2.3

Replicate:
```
meteor create newproject
cd newproject
```

Edit file `client/main.js` and add the following line on top:
```
var c = require('crypto');
```

Returns
```
Error: Cannot find module 'crypto'
```

![](https://i.gyazo.com/1cb37f6f85181adb57c2895dffb67f1b.png)

How to temporarily fix this:
```
rm -rf node_modules/crypto
```

**Comment by hwillson** [comment]
Hi @Netherdrake - I'm not quite sure what you mean. Using these exact steps:

```
meteor create crypto-test
cd crypto-test
meteor npm install
meteor
```

then replacing the contents of `client/main.js` with the following:

```
const crypto = require('crypto');
console.log(crypto);
```

should give you this:

![screenshot 2016-11-18 14 25 35](https://cloud.githubusercontent.com/assets/137740/20443529/2f141634-ad9b-11e6-8617-3f4f5d5ee81e.png)


Are you seeing something different with a brand new project that has no other dependencies? If so can you please link to a runnable reproduction that shows this happening? Any extra information you can provide regarding what 3rd party libraries are breaking, would be helpful as well. Thanks!

**Comment by Netherdrake** [comment]
I think you might be right.

I've created a new meteor project, and `crypto` import ran fine. I think it might be some other package breaking it.

**Comment by Netherdrake** [comment]
I'm trying to install steem, `npm install --save steem`

**Comment by benjamn** [comment]
Make sure you've installed the latest `meteor-node-stubs` npm package (it should be in the default `package.json` for new Meteor apps).

**Comment by Netherdrake** [comment]
@benjamn I have that.

What happens is, this `crypto` folder appears in my `node_modules/` and then my meteor app crashes with `Uncaught Error: Cannot find module 'crypto'`

If I manually delete that folder, the `steem` library fails to sign things. I have no idea how to debug this (I'm not a javascript/web dev). Any ideas?

**Comment by hwillson** [comment]
Here's a quick repro to help with troubleshooting: https://github.com/hwillson/meteor-issue-8074

**Comment by Netherdrake** [comment]
I found out that the `steem` package has an old version of `crypto` as dependency:
https://www.npmjs.com/package/crypto
https://github.com/adcpm/steemauth/blob/dev/package.json#L30

This does not appear to be a Meteor issue. 

Apologies for raising false alarm.

**Comment by hwillson** [comment]
Just adding for future reference - one of the `steem` maintainers has opened issue adcpm/steemauth#6 to track updating the crypto dependency. Thanks!

**Comment by Netherdrake** [comment]
The crypto dependency in https://github.com/adcpm/steemauth/issues/6 has been resolved, however the library still malfunctions when used in a Meteor app.

I have created the new repo, that includes my dummy account private keys for testing.
https://github.com/Netherdrake/steem-meteor-test

The repo contains 2 versions of the same code, one executed within Meteor and one as HTML browser app.

The Meteor one will fail.

---------

The speculation is that Meteor does something funny with the crypto library while compiling the app.
https://github.com/adcpm/steem/issues/39#issuecomment-261956498

I am not a JS developer, so I cannot confirm this.

**Comment by abernix** [comment]
@Netherdrake Per this comment (https://github.com/adcpm/steem/issues/39#issuecomment-261956498) I believe this issue is fixed.  Your reproduction seems to work now (or at least gets to a different error which doesn't seem to be `crypto` related).

I think a combination of updating `steemauth` to remove it's dependency on the old `crypto` library and updating that dependency in `steem` is the likely resolution.  Happy to reopen if this problem still affects you though!

**Comment by Netherdrake** [comment]
Apologies for not closing the issue.

It has been resolved within `steemauth` package.

**Comment by hems** [comment]
We tried deleting node_modules and doing "meteor npm install", instead of "yarn install" or "npm install" which would install the node_modules using your system node and not the version Meteor uses.

And it.... didn't work :(
