### ISSUE TITLE
Uncaught ReferenceError: App is not defined(…) in mobile-config.js

### ISSUE THREAD

**Issue by jwz104** [meteor/meteor#8077]
I am trying to build an app for android, but meteor can't read the mobile config for some reason.
This mobile-config.js:
```
App.info({
  id: '...',
  name: '...',
  description: '...',
  author: '...',
  email: '...',
  website: '...'
});

App.setPreference('Orientation', 'default');
App.setPreference('AndroidExtraFilesystems', 'files,files-external');
```

This is the error I get:

> Uncaught ReferenceError: App is not defined(…)

I tried making a new project and copied the client folder to the new project, but I still have the same error.
I get this error in the console when I run "meteor build output --server 192.168.64.108:3000" and when I run "meteor run android-device".

When I remove the mobile-config.js file the project runs good. But I really need to set AndroidExtraFilesystems.

How can I fix this?

**Comment by madc0w** [comment]
I don't get it.  This was closed?  Why?  I am seeing the same behavior.

**Comment by jwz104** [comment]
I don't know, I closed this issue two years ago. I don't do meteor anymore😂. Sorry🙄
