### ISSUE TITLE
Meteor iOS run issue - looks new

### ISSUE THREAD

**Issue by premcool** [meteor/meteor#8085]
I recently upgraded to Meteor 1.4.2.3 and with this release my code is building successfully for iOS i.e. Xcodeproj created but not able to run and also not Xcode archive not working and giving too many swift issues. I'm using Xcode 7.2 So I tried creating a test project i.e. meteor create test and added platform iOS, then meteor run iOS  (gets error as below)

=> Started your app.                                                            
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator
   ** BUILD FAILED **
   
   
   The following build commands failed:
   CompileSwift normal x86_64
   /Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/test/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
   CompileSwift normal x86_64
   /Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/test/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
   CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
   (3 failures)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,test.xcodeproj,-target,test,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
   Simulator,build,CONFIGURATION_BUILD_DIR=/Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/prem/Meteor/test/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39

/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/prem/.meteor/packages/meteor-tool/.1.4.2_3.4sdahd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at AppRunner._runOnce (/tools/runners/run-app.js:763:21)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12

---------------------------------------
As indicated in some of the forums, I tried the below all unsuccessfully
1. meteor reset
2. npm init
3. rm -rf .meteor/local/cordova-build
4. Update of web app to 1.4.1(meteor add cordova:cordova-plugin-meteor-webapp@1.4.1)
5. npm  install cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5

Any help would be appreciated, as it has been 2 days since I encountered this issue and running against time to make a release. Thanks.

**Comment by skirunman** [comment]
Can you try to update to Xcode Version 8.1 (8B62)? I was having similar build issues and the update solved them for me.

**Comment by premcool** [comment]
Version issue only. However I cannot upgrade to Xcode 8.1 for different reasons. So downgraded Meteor to my previous version 1.4.1.2 and works good now. Closing issue.

**Comment by dr-dimitru** [comment]
Hello,

I'm facing this issue after updating to `1.4.3.1` for both `meteor run ios` and `meteor run ios-device`

Contents of `.meteor/cordova-plugins`:
```
cordova-plugin-camera@2.3.1
cordova-plugin-crosswalk-webview@2.3.0
cordova-plugin-device@1.1.4
cordova-plugin-globalization@1.0.5
cordova-plugin-inappbrowser@1.6.1
phonegap-plugin-push@1.9.4
```

Error stack:
```
=> App running at: http://192.168.88.252:3000 
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed: /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
   ** BUILD FAILED **
   
   
   The following build commands failed:
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/AssetBundleManager.swift
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/AssetBundle.swift
   CompileSwift normal x86_64 /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/Asset.swift
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/AssetBundleDownloader.swift
   CompileSwift normal x86_64
   /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/AssetManifest.swift
   CompileSwift normal x86_64 /Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/code33chat/Plugins/cordova-plugin-meteor-webapp/Errors.swift
   CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
   (9 failures)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-workspace,code33chat.xcworkspace,-scheme,code33chat,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
   Simulator,name=iPhone
   5s,build,CONFIGURATION_BUILD_DIR=/Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/drdimitru/Sites/code33/code33chat/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/drdimitru/.meteor/packages/meteor-tool/.1.4.3_1.t2jht4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:763:21)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

@abernix could you take a look or forward to someone who deals with Cordova/iOS at MDG?

**Comment by abernix** [comment]
@dr-dimitru Have you tried clearing `.meteor/local/cordova-build` (or even `.meteor/local` / `meteor reset` in general)?  What version were you on before?  Have you tried building the project manually in XCode using the `xcodeproj` file in `.meteor/local/cordova-build/platforms/ios/` so you can get some more insight?  Is this something we can easily reproduce on a brand new project?  What version of XCode are you on?

Sorry, but I've got a bunch of questions. :wink:

**Comment by abernix** [comment]
@dr-dimitru Also, it's an entirely new platform version, so you may want to consider doing:

    meteor remove-platform ios
    meteor add-platform ios

And `android` too, if applicable.

**Comment by dr-dimitru** [comment]
Hi @abernix 

> Sorry, but I've got a bunch of questions.

Good questions though

> What version were you on before?

`METEOR@1.4.2.7`

>  Have you tried building the project manually in XCode

Yes, same errors referring swift code

> Have you tried clearing .meteor/local/cordova-build (or even .meteor/local / meteor reset in general)?

No

> What version of XCode are you on?

`Version 8.2.1 (8C1002)`
`IPHONEOS_DEPLOYMENT_TARGET=8.0`

> Is this something we can easily reproduce on a brand new project?

Not sure, I'm having this on pretty old project

> Also, it's an entirely new platform version, so you may want to consider doing:

That helped, but only for iOS Emulator

When running on device Xcode throws:

```
ld: library not found for -lPods-code33
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Refers to `project/Plugins/CDVInAppBrowser.m/-viewDidUnload`: 
```swift
- (void)viewDidUnload
{
    [self.webView loadHTMLString:nil baseURL:nil]; <-- Null passed to a callee that requires non-null argument
    [CDVUserAgentUtil releaseLock:&_userAgentLockToken];
    [super viewDidUnload];
}
```

Removing `cordova-plugin-inappbrowser` package, makes `Null passed to a callee that requires non-null` disappear, but build remains failing with: 
```
ld: library not found for -lPods-code33
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dr-dimitru** [comment]
Update: 
I've noticed of
```
The Podfile does not contain any dependencies.
```
This message lead me to go to `.meteor/local/cordova-build/platforms/ios` and run `pod install` but it doesn't helped at all.

Also removing all packages listed in `cordova-plugins` doesn't fixed my issue and made those warnings:
```
WARNING: Attempting to install plugin cordova-plugin-globalization@1.0.1, but it should have a minimum version of 1.0.5 to ensure compatibility with the current platform
         versions. Installing the minimum version for convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-camera@2.1.1, but it should have a minimum version of 2.3.1 to ensure compatibility with the current platform versions.
         Installing the minimum version for convenience, but you should adjust your dependencies.
```

 1. Finally running `meteor reset` fixed my issue for `meteor run ios-device`
 2. Installing Cordova packages back - brought same exception back
 3. Running `meteor remove-platform ios`, `meteor reset` and `meteor add-platform ios` again
 4. By the removing/adding cordite packages I find out what `phonegap-plugin-push@1.9.4` was the reason for this issue. I've tested all versions between `v1.9.4` and `v1.8.4`, `v1.8.4` is the only version which passed the build for device. The weird thing is how `v1.9.4` may work while running `meteor run ios`, but not Emulator or device via Xcode? Also I had to run `meteor remove-platform ios && meteor reset && meteor add-platform ios` between all `meteor add cordova:plugin-name` otherwise it keeps failing with same error

I hope it will help to other folks.
@abernix thank you for pointing me to `meteor remove-platform ios && meteor reset && meteor add-platform ios` :)

**Comment by abernix** [comment]
@dr-dimitru, thanks for documenting your findings!

**Comment by jaskinn** [comment]
In the issue that dr-dimitru referenced in phonegap-plugin-push the reply was:

> the reason you are getting that build error
>ld: library not found for -lPods-appName
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>is probably because meteor is building using the .xcodeproj instead of the .xcworkspace which is >now required in cordova-ios. You see cordova-ios may now have multiple projects in a single >workspace.

**Comment by abernix** [comment]
@jaskinn I don't think that's the problem.  We use [essentially `cordova build`](https://github.com/meteor/meteor/blob/adc468f67078ed347e36f753ca3b916b7c3c8565/tools/cordova/project.js#L245-L249) to build the project, not the `.xcodeproj` file directly.  The only time we use the file directly is with [the `run ios-device` command](https://github.com/meteor/meteor/blob/adc468f67078ed347e36f753ca3b916b7c3c8565/tools/cordova/run-targets.js#L52-L54).

I believe it must be something else.

**Comment by dr-dimitru** [comment]
@jaskinn thank you for posting reply of @macdonst

@macdonst could you please respond on it?

@abernix am I understand correctly?:
 - `run ios-device` - uses `.xcodeproj` file directly
 - `run ios` and `meteor build` - uses `cordova build`

If so - it explains why it works on Emulator but not device. And I'm assuming I can build app just fine but not test on device - funny thing we can not test push-notification on Emulator

@abernix should I fill separate meteor issue on using `.xcodeproj` for `run ios-device`?
