### ISSUE TITLE
Download meteor-tool problem

### ISSUE THREAD

**Issue by davidsun3000** [meteor/meteor#8087]
When doing upgrading, it stuck in:
  Downloading meteor-tool@1.3.2-rc.5...     [                            ] 0% 0.0s

tried ping warehouse.meteor.com according to others' suggestions:

PING warehouse.meteor.com (146.88.128.224): 56 data bytes
64 bytes from 146.88.128.224: icmp_seq=0 ttl=39 time=320.706 ms
64 bytes from 146.88.128.224: icmp_seq=1 ttl=39 time=314.600 ms
64 bytes from 146.88.128.224: icmp_seq=2 ttl=39 time=311.657 ms
Request timeout for icmp_seq 3
64 bytes from 146.88.128.224: icmp_seq=4 ttl=39 time=311.771 ms
Request timeout for icmp_seq 5
64 bytes from 146.88.128.224: icmp_seq=6 ttl=39 time=311.522 ms
64 bytes from 146.88.128.224: icmp_seq=7 ttl=39 time=314.051 ms
64 bytes from 146.88.128.224: icmp_seq=8 ttl=39 time=727.359 ms
Request timeout for icmp_seq 9
64 bytes from 146.88.128.224: icmp_seq=10 ttl=39 time=311.187 ms

So my impression is this CDN connection is really bad, previous we didn't have such problems for upgrading or installations. 

Please fix this problem, as we can not use Meteor frame anymore .

**Comment by abernix** [comment]
Apologies for the trouble here, though unfortunately, this looks like a CDN connectivity issue as you diagnosed.  The high(-ish) latency and dropped packets certainly pose a problem for downloading the rather-large Meteor installation.  

I'm not sure if this problem continued for you, but I would suggest you try another CDN [as documented in this issue](https://github.com/meteor/meteor/issues/7806#issuecomment-254125662).  Alternatively, I'd suggest trying another Internet connection.

Sorry there's not a more clear answer here though I've extensively laid out what we've done from our side to improve this in [this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-258397590).
