### ISSUE TITLE
Installation ETIMEDOUT error when creating a new project

### ISSUE THREAD

**Issue by austindsouza** [meteor/meteor#8089]
I am facing the problem when creating a new project as discussed in #6960 
I could able to install meteor on CentOS-7 using the following command :
$ curl https://install.meteor.com/?release=1.4.2.1 | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0  14712      0 --:--:-- --:--:-- --:--:-- 14718
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.4.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

[centos@meteor Development]$ meteor create myapp
=> Errors while creating your project         
                                              
While downloading autoupdate@1.2.11...:
error: ETIMEDOUT

While downloading blaze@2.1.9...:
error: ETIMEDOUT

While downloading blaze-html-templates@1.0.5...:
error: ETIMEDOUT

While downloading blaze-tools@1.0.10...:
error: ETIMEDOUT

While downloading caching-html-compiler@1.0.7...:
error: ETIMEDOUT

While downloading ddp-client@1.2.9...:
error: ETIMEDOUT

While downloading ddp-server@1.2.10...:
error: ETIMEDOUT

While downloading ecmascript@0.6.0...:
error: ETIMEDOUT

While downloading html-tools@1.0.11...:
error: ETIMEDOUT

While downloading htmljs@1.0.11...:
error: ETIMEDOUT

While downloading http@1.1.8...:
error: ETIMEDOUT

While downloading launch-screen@1.0.12...:
error: ETIMEDOUT

While downloading spacebars@1.0.13...:
error: ETIMEDOUT

While downloading spacebars-compiler@1.0.13...:
error: ETIMEDOUT

While downloading templating@1.2.15...:
error: ETIMEDOUT

While downloading templating-compiler@1.2.15...:
error: ETIMEDOUT

While downloading templating-runtime@1.2.15...:
error: ETIMEDOUT

While downloading templating-tools@1.0.5...:
error: ETIMEDOUT

While downloading ui@1.0.12...:
error: ETIMEDOUT

### Steps I followed from #6960 
http://debug.netdna-cdn.com/
You are hitting the MaxCDN Chicago Datacenter

http://checkip.amazonaws.com/
173.161.84.209

traceroute static-meteor.netdna-ssl.com
traceroute to static-meteor.netdna-ssl.com (146.88.135.5), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *

>  I tried uninstalling the meteor and Installed freshly, but same problem exists.

Can you please help me  this.

**Comment by abernix** [comment]
I believe the project directory should be created already when you get that error.  If you go into the `myapp` directory, and then run `meteor` over and over again, does the list of packages which fail (i.e. `error: ETIMEDOUT`) get shorter each time you run it?  How quickly does it fail?

I find it strange that your `traceroute` is failing to return responses on any of the hops to the host.   Out of curiosity, what is the networking situation where you are using this?  Are you going through a proxy?  Is this on a home connection?  Are you behind a strict corporate firewall or anything?

This could be related to #8013.

**Comment by austindsouza** [comment]
Hi abernix ,

Thanks for your reply, actually the problem got solved.

The steps I followed is :  
1) export METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net.
2) Since the meteor was trying to download meteor-tool-1.4.0_1 every time when I tried to start meteor, I uninstalled meteor and installed freshly by : meteor update --release 1.4.0.1.
3) Updated the meteor inside the project : meteor update.
4) Installed/Updated the packages I wanted.

This solved my issue I've been stuck from 2days :)

Thanks & Regards,
Austin.

**Comment by abernix** [comment]
I'll go ahead and close this.  Glad to hear it's working for you now.  I don't understand why it would have been trying to download `meteor-tool-1.4.0_1` on a new 1.4.2.1 project, but it seems you may have been running into your issue under other circumstances than you recreated here so that explains a bit.

Also, please don't use https://install.meteor.com/?release=1.4.2.1 (with the `?release=` argument) unless you know what you're doing.  If it's not clear, that flag downloads a very specific version of the Meteor tool.  In this case, that's an outdated version.  Make sure to only use https://install.meteor.com/ to ensure ensure you get the latest version of the Meteor tool.
