### ISSUE TITLE
Meteor.users update to user.profile forbidden

### ISSUE THREAD

**Issue by belisarius222** [meteor/meteor#809]
This was broken by the recent security change in Meteor 0.5.8.
From the docs: 

> Users are by default allowed to specify their own profile field with `Accounts.createUser` and modify it with `Meteor.users.update`. To allow users to edit additional fields, use `Meteor.users.allow`.

My dev environment has the autopublish and insecure packages turned on.  

Here is an app that throws the "access denied" error: https://github.com/belisarius222/user-permissions-test online at http://user-permissions-test.meteor.com

When I add an `allow` function for `Meteor.users`, it does work correctly.

**Comment by nicholasalanbrown** [comment]
Hmm, I'm stil seeing this issue when running this update on client-side code:
```
Meteor.users.update({_id:Meteor.userId(}, { $set: {'profile.name': name} });
```
I get an "Access denied" error on the client. Has this regressed again, or do I need to specify allow rules to update profile fields?

**Comment by glasser** [comment]
@nicholasalanbrown That seems like a different issue. File a new bug report with a complete reproduction recipe starting with git clone. https://github.com/meteor/meteor/blob/devel/Contributing.md#filing-bug-reports
