### ISSUE TITLE
multiple public or private folders as subfolders

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#8093]
Certain concepts of file structuring in a project might required to have not just one `public/` or `private/` folder at the root level of a meteor app, but having these folders with exactly the same name and known behavior within sub folders (other then `imports/`). 
So imho it would be expected that the build tool copies the contents of a `private` folder somewhere in the project, into `build/programs/server/assets/`, and the same goes for any `public` folders, but with `build/programs/web.browser/app` as the target.

I tried this maneuver in `METEOR@1.4.2.3` m but it didn’t work as described above, instead the subfolders where ignored. 

Edit: sadly same behaviour goes for the `packages` folder, though it ends up in a build error (`error: unknown package in top-level dependencies`, which makes sense, because the added package couldn't be found by the build tool in a certain `packages` subfolder, or in other words: there is no such added package in the top level `packages` folder)

Any thoughts on this would be much appreciated. thx

**Comment by abernix** [comment]
The `private` directory is intended to be used as part of the [Assets API](https://docs.meteor.com/api/assets.html).  The `public` folder is meant to be served directly from the root of your application (i.e. `public/file.txt` should be at `http://example.com/file.txt`).

If these started appearing inside of other folders, it starts to become confusing as to where they would be available on the web.  Whereas right now if you had a `public/images/file.png` file, you would know it would be at `http://example.com/images/file.png`, but with the introduction of a `somedir/public/images/file.png` (as you're suggesting), it's not entirely clear to me how the conflict would be resolved when there was also a `public/somedir/images/file.png`.  Having a single point of entry into the `private` directory makes this conflict simple.

And really, the same sort of situation seems to arise when you introduce that additional dimension into the Assets API.  As of right now, it would be very clear that `Assets.getText('somedir/binary.dat')` would be in `private/somedir/binary.dat`, but by scattering additional `private` directories throughout the project it removes all clarity.

What is your use case that would necessitate this? Why wouldn't you just create additional directories within the existing `public` and `private` directories, as is common practice already?

**Comment by lucendio** [comment]
You are probably right, it might cause some confusion in terms of figuring the right path. To solve this, I would suggest to see the folders (`public`, `private`, `packages`) as their roots (`/`) within their own purpose (which is already the case, e.g. your first example). no matter in which subfolder they are located in. the build-tool moves all content into the same location as it already does (somewhere in `.meteor/local/build`) and symlinks them in `.meteor/local/build/[PLATFORM]/program.json` as it does right now as well.

My use case is very simple. within the root of a meteor app, I'd like to have:

```
/
|
+-- .meteor/
+-- core/	--> sub-module/tree (another repo)
|   +-- ...	--> typical meteor app structure (incl all special folders)
+-- specifics/	--> unique parts, which apply only to this specific meteor-app/project/repo
|   +-- ...	--> typical meteor app structure (incl all special folders)
```

So I can maintain and develop core parts/features/shared code separately from a concrete project. And no, putting the core in a package(s) wont work IMHO, because (A) since ES modules it is considered an anti-pattern and (B) it would cause to much overhead, especially when it's organized in multiple repos.

The good thing is, it is backward compat. and wont break anything (since nobody might have done it in the past, because it would have had break the build).

I am also open to suggestions of other approaches, which might solve the underlying issue (without depending on 3rd party build tools)

**Comment by abernix** [comment]
I'm still not understanding.  First of all, you've indicated desire to follow the ES-modules pattern, but your `core/` and `specifics/` folders are an "anti-pattern" for Meteor ES modules since they are eagerly loaded.  Also, I'm not sure what symlink you are talking about as `program.json` is not a symlink but rather a manifest of files in the bundle.

Ignoring these portions which I don't understand, I still don't see how your suggestion to solve the confusion addresses the problem at all.  You still seem to still be saying that you would have two _different_ paths copied to the _same_ destination – meaning if a user had `/core/public/file.jpg` and `/specifics/public/file.jpg` would both end up as `/file.jpg` on the web?

If so, yes, it would be backward compatible, but again, confusing in the case where a user is wondering why only one of their public files is in the destination.

If you're still keeping your project in a single repo (I'm not sure if you're trying to have a single repo or multiple?), why don't you just come up with a naming convention for sub-directories within `private` and `public` which matches your desired compartmentalization?  So `public/specifics` and `public/core` would match up to the script(s) you have in `/core`.

Or, if you're using submodules, you could just stick a submodule into `/imports/submodule` which has a `private` and `public` directory and then symlink:

* /imports/submodule/private/ => /private/submodule
* /imports/submodule/public/ => /public/submodule

Just some thoughts.

**Comment by lucendio** [comment]
The two folders wont load eagerly, because `c` comes before `s`, but that doesn't matter, if both folders would include no other folders then `public`, `private`, `packages` and `imports`; and using `server`, `client` and `lib` within these two folders would still be possible as well - since we are still in the process of migrating towards ES modules.
In other words, I want to put a typical meteor app structure in both of these folders, but the contents of one (`core`) will be a submodule and managed in a different repo. that enables us to re-use the core in multiple meteor app. All this, in the end, should build to one meteor app - obviously, since the root level contains a `.meteor` folder.

maybe a simple example would make it more clear:
```
/core/public/shared-asset.png        // results in /shared-asset.png
/specifics/public/another-asset.png  // results in /another-asset.png
```
no matter where these special folders are, the contents should be handled and sees as the folders where located in the root level.
and yes, you are right, having two files with the same name in different public folders would (and should) warn the user about the duplicate path, but since this case wont exists - at least not intentionally, I don't see this as a problem. IMHO, nobody would put the same file in different `public` folders.

regarding `program.json`: symlinking in the sense of associating the actual path with the link/url - meaning the builder decides where the actual file goes and under what path/url (and in what platform) the file is accessible.

A naming convention wont work - or at least would cause a lot of overhead, because our main motivation is organizing shared (`core`) parts in a different repos. In other words: one meteor project composed of at least one submodule (`core/`) and project related stuff (`specifics/`), which both might contain a complete meteor structure (w/o `.meteor/`) as well, but building into one actual meteor app.

Regarding your last proposal: you are right, this might work for `public` and `private` folders, but not for `packages`. this folder has to be either in the root level or somewhere outside the project (enabled with `METEOR_PACKAGE_DIRS`)

Does this make it all a bit more clear?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=multiple%20public%20or%20private%20folders%20as%20subfolders&body=Migrated%20from:%20meteor/meteor%238093) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
