### ISSUE TITLE
ddp-client tests are failing if opened on 127.0.0.1:3000 instead of localhost:3000

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8094]
Core package `ddp-client` tests fail if opened on 127.0.0.1:3000 instead of localhost:3000. The reason is `/websocket is a websocket endpoint` test which tries to read content from `/` which has no CORS header so it is a denied cross-origin request.

**Comment by hwillson** [comment]
Replacing `Meteor.absoluteUrl` with `Meteor._relativeToSiteRootUrl` is a quick fix for this (changes submitted via PR #9065).
