### ISSUE TITLE
Add `meteor npm install` step to installer

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#8095]
The Meteor installer (at https://install.meteor.com/) (a private repository) needs to have the `meteor npm install` step added to the instructions (in two places!) to coincide with the change in 41713dacf732642de8e4fce27f4199e3e7847961 and the fact that it is actually necessary now with the `babel-runtime` changes in Meteor 1.4.2.1.

This should help the confusion of the many tutorials which are no longer accurate, at least until #6848 gets attention (if it can ever be).

**Comment by benjamn** [comment]
Is this still necessary with #8108?

**Comment by abernix** [comment]
Does not seem necessary!  I suppose 41713dacf732642de8e4fce27f4199e3e7847961 could be reverted too?  The only thing nice about showing the command is that users become aware of its existence, but that could be communicated differently.
