### ISSUE TITLE
$stateChangeError ReferenceError: Can't find variable: google

### ISSUE THREAD

**Issue by tomzamir** [meteor/meteor#8098]
Hi

when deploying to Galaxy we get issues with Safari entering infinite loop with this error:

$stateChangeError - fired when an error occurs during transition with error: ReferenceError: Can't find variable: google

when deploying with --debug, the issue is resolved.

1. this isn't happening for Chrome/FireFox, 
2. happens for logged in users, once they refresh the page.

Any idea?

I can provide URL in PM

**Comment by abernix** [comment]
It's really hard to say what's going on here without your actual code.  The `--debug` flag on `meteor deploy` avoids minification so you may be running into a problem similar to #7994 or #8020.  The reason you're running into different results in different browsers is that different browsers have [different ECMAScript capabilities](https://kangax.github.io/compat-table/es6/).

This can usually be avoided by ensuring that your app uses the `ecmascript` package and that any Meteor packages that you use (locally or published) properly include a `api.use('ecmascript')` in their `package.js`.  Failure to do that will cause code not to be transpiled into code that can be used by all browsers who may not have the latest ECMAScript features implemented yet.

**Comment by tomzamir** [comment]
Hi

so we think that the script that is causing us the trouble is the google maps api call:

 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?client=xxxx&libraries=places,geometry,visualization,drawing" async defer></script>

any idea how I can tell meteor not to minify this call?

when I comment out this line I reproduce the issue above in Chrome/Firefox.

This also happens locally (so not galaxy related per say) when I "meteor run --production"

any thoughts on this?

**Comment by tomzamir** [comment]
Hi
so so we manage to locate the issue and solve it.

removing "async defer" from the google maps api script call fixed the issue. It has to do with the order that ngmap meteor packaged is loaded in relation to the google maps script. So canceling the async made sure the google script is loaded first.

cheers
