### ISSUE TITLE
need a supported way to set transform for Meteor.users collection

### ISSUE THREAD

**Issue by belisarius222** [meteor/meteor#810]
Right now, I'm using 
`Meteor.users._transform = function(user){...};`, which works just fine so far, but that's a private API call. It would be good to have a supported way to do this in case the transform internals change at some point.  I have quite a few methods in my user transform, and I'd bet that's typical for a large subset of applications.

Maybe something like `Meteor.setUserTransform(function(user){...});` ?

**Comment by derwaldgeist** [comment]
+1 for transforming users. I'm using @glasser's suggestion for now, but this requires to provide the transform on every find(). (Have moved this to a central method, but that's also sub-optimal.)

**Comment by chmanie** [comment]
@glasser 's method doesn't work for me.

I'm basically doing this in a publish function: 

```javascript
return Meteor.users.find({ _id: this.userId }, {
      fields: {
        profile: 1
      },
      transform (user) {
        user.extraField = 'xxx';
        return user;
      }
    });
```

The transform function is never being called. Am I doing something wrong?
