### ISSUE TITLE
Hanging when `node main.js` on a deployment machine

### ISSUE THREAD

**Issue by xareelee** [meteor/meteor#8105]
I bundled my meteor app via `meteor build` on my Mac and execute the `node main.js` on the deployment machine with appropriate settings (see below), but it hung and print nothing after execution. I have no clue and no idea about how to deal with this.

```bash
> node main.js
(print nothing here...)
```

> The code is working well on my machine before bundling.

## Environment

Pack bundle on my Mac. The environment is:

```bash
# MacOS
node --version    # v7.1.0
yarn --version    # 0.17.8
meteor --version  # Meteor 1.4.2.3
```

Deployment machine:

```bash
# CentOS 6.5
node --version      # v6.9.1
yarn --version      # 0.17.8
```

## Steps

On my mac:

```bash
# reinstall node modules via yarn
rm -rf node_modules 
yarn install --production

# pack the bundle
meteor build ./.build --architecture os.linux.x86_64

# copy to server
scp ./.build/my_app.tar.gz root@<server_ip>:/service/my_app/
```

On the deployment server:

```bash
# decompress the bundle
tar zxvf /service/my_app/my_app.tar.gz
cd /service/my_app/bundle

# install node modules by yarn
(cd programs/server && yarn install)

# export env variables
export MONGO_URL=mongodb://<mongo_ip>/my_app
export ROOT_URL=http://<server_public_ip>
export PORT=8080

# execute (hang forever and print nothing)
node main.js
```

After execution, It hangs forever and prints nothing. I tried visit the URL on my browser (`http://<server_ip>:8080/`) but it got `ERR_CONNECTION_TIMED_OUT`.

I didn't use a domain name for `ROOT_URL` and the port 80 has been used by other service (use port 8080 instead of). 

I'm newbie to the server side and node.js, and have no idea how to debug this without any clue.

**Comment by laosb** [comment]
The version of your `node` on the deployment machine should be `4.6.2`. Try that version. If you don't know which version of node to use, just try `meteor node -v` on your development machine and use that version.

Note that the version of your own node install on your development machine is not related to your meteor app, since Meteor use its own version of node. Use `meteor node` and `meteor npm` to call the Meteor node.

**Comment by xareelee** [comment]
@laosb , thanks for your information. 

I changed the version of the node on the deployment machine to be `4.6.2` (still `v7.0.0` on my development machine), but it is still hanging after executing `node main.js`.

```bash
> node main.js
(print nothing here...)
```


I also tried to use `meteor npm install --production` instead of `yarn install --production` on my Mac before bundling, and use `npm install` instead of `yarn install` on the deployment machine (may I use yarn with Meteor?). Nothing changes.

Is there any way to print out where I was stuck?

**Comment by xareelee** [comment]
@laosb I apology for my fault.

I asked my operation team, and there is a firewall blocking ports other than `80`. Now the service is on without print anything.

I recommend that, after executing `node main.js`, it should print something like

```bash
> node main.js
=> App running at: http://<service_ip>:<port>/
```

Is it a good idea?

**Comment by laosb** [comment]
@xareelee Good to see your success!

Anyway, you're encouraged to use `meteor npm` (or `meteor yarn` if you prefer and has yarn installed as your dev dep) so you can ensure that you're using the correct version of node.

It might be confusing to have nothing printed when started successfully, but actually most servers do like this. If you need it (maybe to guide your ops?), just do it yourself by adding a `console.log` statement in `Meteor.startup()`.

**Comment by xareelee** [comment]
@laosb 
Thanks for your advice and information!

**Comment by xareelee** [comment]
If I did not install meteor on the server, could I just use `yarn install` and `node main.js`?

**Comment by abernix** [comment]
@xareelee You are not expected to install `meteor` (a development tool) on your production server.  The bundle created by `meteor build` is simply a Node application and should run on any environment where Node can run.   So to answer your question: yes.
