### ISSUE TITLE
Downloading Meteor tool 1.4.2_1 full download then extrationg long time

### ISSUE THREAD

**Issue by aboobakkar** [meteor/meteor#8107]
Meteor Tool latest all are problem. very careless development resource in meteor develeopment team. my project are stuck.  m

**Comment by hwillson** [comment]
Hi @aboobakkar - sorry to hear you're having trouble! Have you seen #7688? Your problem appears to be a duplicate of that issue. Please try the solutions outlined in that (closed) issue, then post back if you're still having trouble. I'll close this for now - thanks!
