### ISSUE TITLE
Cordova creates an iOS project with deployment target to macOS

### ISSUE THREAD

**Issue by xareelee** [meteor/meteor#8109]
I've asked a question about this on the [stackoverflow](http://stackoverflow.com/questions/40837948/change-xcode-deployment-target-from-macos-to-ios), and it currently is unsolved.

I think this might be a bug too. I found there are many problems in the `.xcodeproj` which Meteor/Cordova creates.

* As mentioned in the [stackoverflow](http://stackoverflow.com/questions/40837948/change-xcode-deployment-target-from-macos-to-ios), the Xcode project created by Meteor/Cordova is misconfiguration with the deployment target to `macOS`.
* `AppIcon` lacks some sizes of pics and leads to fail to archive the app for deployment. Furthermore, there are two different kinds of images in `AppIcon`. This also happened in `LaunchImage`.

![screen shot 2016-11-28 at 14 12 07](https://cloud.githubusercontent.com/assets/804308/20657970/dd83a33e-b574-11e6-956e-2affa82ad87f.png)

> I did not use `App.icons({...})` in **mobile-config.js**. This app is in the prototype phase, and it will only be used in our team not a commercial app. Changing the icon is not the prior job for now.

* The Xcode project use **Swift 2.x**. It might not be a problem now, but will be in the future.

**Comment by xareelee** [comment]
After I removed the mobile platforms, added them back, and built the targets again, the generated `.xcodeproj` is normal now.

**Comment by abernix** [comment]
Presumably, this was a bug in Cordova, or related to Xcode 8 changes that were fixed with the (Meteor) upgrade to Cordova 6.2.

Thanks for reporting back and glad you found a solution!

**Comment by xareelee** [comment]
@abernix How can I know what the version of Cordova which the current Meteor project uses?
If necessary, how can I upgrade Cordova to 6.2 in Meteor?
