### ISSUE TITLE
{{loginButtons}} changes to loggingIn state and hangs on server reload

### ISSUE THREAD

**Issue by belisarius222** [meteor/meteor#811]
If the user is logged in when the server reloads, the `{{loginButtons}}` change from displaying the username to the animation that normally runs when `Meteor.loggingIn()` is `true`.  The button then gets stuck in this state.

Reproduction app here: https://github.com/belisarius222/login-hang-test
screenshot: 
![login-buttons-hanging](https://f.cloud.github.com/assets/874741/257508/2c6f78dc-8c62-11e2-9679-54c168a8f19e.png)

The reproduction code includes a (hacky) function to reload the server by running `touch` on one of the JS files, so you'll have to change a line of code to make it work (or rather, not work :P ) on your local system.  There are more detailed instructions on the github page.

Sanity checks: once the button is hanging, `Meteor.loggingIn()` returns `false`, and `Meteor.user()` returns an object with all the usual suspects for fields, including `_id`.

Calling `Meteor.logout()` from the console successfully logs the user out and the loginButtons state goes back to its normal non-logged-in state.

I'm using Meteor 0.5.8 with autopublish and insecure enabled.  I'm using accounts-base, accounts-ui, and accounts-password.  Tested on chrome and safari on OS X, same behavior on both.

**Comment by viktornord** [comment]
The issue is still present, why is it closed?
