### ISSUE TITLE
iOS PushKit voip silent push causes callbacks to be 1 behind

### ISSUE THREAD

**Issue by stormbkk87** [meteor/meteor#8112]
When a meteor iOS cordova app gets put in the background or suspended state, an arriving voip silent push notification does not fire the cordova javascript callback the first time. Only when a second voip silent push notification is done will the last notification show up, but not the current one. Basically, creating a 1 behind situation. Opening the app into the foreground triggers the most recent callback to arrive.

Example:
    1. App sent to background/suspend
    2. Voip Push arrives with data "PUSH 1"
    3. Nothing fires for Cordova Javascript callback
    4. Voip Push arrives with data "PUSH 2"
    5. Cordova callback fires with data "PUSH 1"
    6. App clicked to foreground
    7. Cordova callback fires with data "PUSH 2"

**Comment by abernix** [comment]
Are you sure this isn't a bug with Cordova itself?  You probably need to file this in the [Cordova Issue Tracker](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel).

If you're sure this is a Meteor bug, you should submit a reproduction.  Please see [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) to see what is expected when opening an issue.

**Comment by stormbkk87** [comment]
Got it. The only thing I can see that points to Meteor is the below error I receive in the XCode console when the first voip push is received. But could have been a fluke.

"Connection timeout. No sockjs heartbeat received."

I'll create a Cordova only project to see if the issue persists and file issue report accordingly. Cheers.

**Comment by stormbkk87** [comment]
I have proven that this is not a Cordova bug. The plugin works as expected with the following Cordova versions.
Node v4.6.1
Cordova iOS v4.2.1

I have created a Meteor application displaying in simple code the issue. Git repos below, instructions in the git README file. 

https://github.com/stormbkk87/meteor-issue-8112

This is my first Meteor bug report, let me know if you need more info. Step by step in the git README.

**Comment by abernix** [comment]
Thanks for the reproduction and additional instructions – they look great, however I don't personally have the paid Apple Developer Program agreement necessary to create the certificates so someone else will have to try to reproduce this.

Last question for now though: Which version of Meteor are you trying this on?

**Comment by stormbkk87** [comment]
@abernix I'm using Meteor 1.4.2.3 with all packages updated.

If you can steer me in the right direction, I can try to debug the Meteor code. Never done it before but I can give a go. My gut says there's a plugin, queue or Promise not passing info to Cordova when in the background. Or maybe the GCDWebServer is getting in the middle of Cordova.

**Comment by abernix** [comment]
The process running in the background is still Cordova – not Meteor, so I'm not entirely sure where to start debugging this. (I will help however I can though!)

But I think that brings up an interesting question about the background permissions of the application.  The documentation for [`cordova-ios-voip-push`](https://github.com/Hitman666/cordova-ios-voip-push#xcode-setup) has a little bit to say about that.  Have you confirmed that the resulting XCode project (outputted by Cordova) has the proper "[Background Mode](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html)" to process the notification?

If you're using `meteor build` to output a project, you should find an `.xcodeproj` file in the `ios/project` directory.  If you open that with XCode, click on the Project in the drawer on the left and then click on the "Capabilities" pane/tab, you should find a "Background Modes" section.  If you open this, what settings are enabled for your project?

**Comment by stormbkk87** [comment]
When I created the "Cordova only" project to make sure it wasn't a Cordova bug, I double checked that all the settings were the same as the meteor project. The "Cordova only" notifications come in sequentially.

Looks like I left out those settings in the Github instructions. Sorry about that. If you don't set the Background modes, nothing comes in.

![background](https://cloud.githubusercontent.com/assets/9250123/21927369/0dc3cefe-d9b8-11e6-8ee8-03b8cf28f5e5.png)

**Comment by stormbkk87** [comment]
Any help understanding how the queuing/timing or DispatchQueue's are setup in Meteor iOS while it is in the background would be a big help. I've tried looking into the WebAppLocalServer.swift when it goes into the background/foreground but no tweaks seem to affect this issue. 

I thought maybe the GCDWebServer was getting in the way by wrapping a DispatchQueue around the Cordova lib calls while in the background. Or maybe even the WKWebView. I also noticed the GCDWebServer stops when the app goes into the background. So, I tried setting GCDWebServerOption_AutomaticallySuspendInBackground to NO. But that didn't help.

The METTimer is another bit of code that uses dispatch queues with background options for blacklisting bundles. But I'm not sure how this affects other plugins.

I'm sure now that this issue is related to queues or semaphores blocking the first async callback on the main queue.

I've even tried wrapping the PushKit callbacks with their own DispatchQueue or adding to the global queue. Then calling the plugin delegate from the main queue when a result comes in. 

    DispatchQueue.main.async {
        self.commandDelegate!.send(result, callbackId: command.callbackId)
    }

When I wrap the code with it's own queue, I notice that the first callback was now not the only one that didn't return. 3 or 4 would queue up and then after the 5th callback, all the previous 3 or 4 would fire to the Meteor side of things. 

Any ideas what to focus on in the Meteor swift code?

**Comment by stormbkk87** [comment]
Oh and I've tried the Meteor 1.5-beta.18 with no success.

**Comment by stormbkk87** [comment]
I have confirmed that this issue is related to the changes made in Meteor after adding the WKWebView and GCDWebServer. PushKit plugin works correctly under Meteor 1.2.1.

**Comment by stormbkk87** [comment]
@abernix Can you shed some light on the functioning of the WKWebView and GCDWebServer in regards to the dispatch queues? Or maybe somewhere else to focus on?

**Comment by stormbkk87** [comment]
More progress. The WKWebView is not processing the first Javascript callback. The "didReceiveScriptMessage" is not called.

**Comment by stormbkk87** [comment]
I have solved this issue and opened a ticket with the Cordova project. However, I don't foresee them doing much about it. We'll see.

The issue is with the cordova-plugin-wkwebview-engine. The WKWebView is restricted in iOS 10 when doing anything repetitive or power intensive while the app is in the background. What I found was that when a Cordova plugin makes a callback to a Javascript function, it wraps the call in  a "setTimeout" function with 0 duration. A common JS strategy, but in this case Apple will not allow a process to repeat in the background wasting battery resources. So, what it seems to do is queue the function call. And then display the behavior in this issue.

For anyone who experiences this and wants a quick hack, you can go into the generated project in XCode and make some changes. 

Hope this helps someone as this issue has stalled my app development for months. Cheers.

1. Find the file ios-wkwebview-exec.js in the XCode project

    YourProjectName/Staging/www/plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec.js

2. Uncomment the setTimeout wrapper or add in your own check if the app is in the background. Not sure if removing the setTimeout will create deadlocks if you have many Cordova plugins. So, a background test may be preferred. I'm only showing the below code to prove that commenting out the setTimeout wrapper fixes the issue. 

```
    iOSExec.nativeCallback = function(callbackId, status, message, keepCallback, debug) {
        var success = status === 0 || status === 1;
        var args = convertMessageToArgsNativeToJs(message);
    
     // setTimeout(function(){
    	    cordova.callbackFromNative(callbackId, success, status, args, keepCallback);
     // }, 0);
    };
```

**Comment by nickmendes** [comment]
Im having the same issue as you do, but Im using voip notifications to provide call-kit to my app, with your hacks everything works until I delete the app from the drawer. Any idea how to fix this, thanks @stormbkk87

**Comment by nickmendes** [comment]
Update:

I was able to get it working with this also: 

https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25/commits/870957c5dad9d0760f1f1fd6173c2c6695391954
