### ISSUE TITLE
[1.4.2.3] published package not working -> module.js:325:15: Cannot find module 'lodash/cloneDeep'

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#8113]
Meteor 1.4.2.x, Windows 10 64-bit, package `omega:meteor-destkop-bundler`.

Well actually I have no idea what have happened but I have published a package with a `1.4.2.x` version (not sure exactly what was used) and it seems that it is broken.

Repro:
```
meteor create test
cd test
meteor add omega:meteor-desktop-bundler@0.2.1
```

```
[[[[[ ~\E\test2 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `meteor-desktop-bundler` from package `omega:meteor-desktop-bundler`:
   module.js:325:15: Cannot find module 'lodash/cloneDeep'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (C:\Users\Omega\AppData\Local\.meteor\packages\omega_meteor-desktop-bundler\0.2.1\plugin.meteor-desktop-bundler.os\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template\lib\index.js:59:42)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load (C:\Users\Omega\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (C:\Users\Omega\AppData\Local\.meteor\packages\omega_meteor-desktop-bundler\0.2.1\plugin.meteor-desktop-bundler.os\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\lib\index.js:525:46)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load (C:\Users\Omega\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.require (C:\tools\isobuild\bundler.js:1681:22)
   at packages/babel-compiler.js:85:7
   at packages/babel-compiler.js:428:4
   at packages/babel-compiler.js:441:3
```

I have just republished it without any changes and it works now. Submitted this because I would like to know if I did something wrong to avoid this in the future...

It seems to be broken because in `.meteor\packages\omega_meteor-desktop-bundler\0.2.1\plugin.meteor-desktop-bundler.os\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-template` `lodash` which is a dependency seems to be bundled incompletely.

**Comment by abernix** [comment]
It's not immediately clear to me what the problem is, but there are differences in the source of your published packages which could provide a clue:

* [0.2.1 source tarball](https://warehouse.meteor.com/sources/JsyBevK2nKEzouwXK/1479935097145/R7jhHcD8KQ/omega:meteor-desktop-bundler-0.2.1-source.tgz)
* [0.2.2 source tarball](https://warehouse.meteor.com/sources/JsyBevK2nKEzouwXK/1480449458133/98Tsr6Aq9P/omega:meteor-desktop-bundler-0.2.2-source.tgz)

And a recursive `diff` on those directories:
```diff
diff -r omega_meteor-desktop-bundler-0.2.1-source/omega_meteor-desktop-bundler/.versions omega_meteor-desktop-bundler-0.2.2-source/omega_meteor-desktop-bundler/.versions
1,4c1,4
< babel-compiler@6.8.0
< babel-runtime@0.1.9
< ecmascript@0.4.4
< ecmascript-runtime@0.2.11
---
> babel-compiler@6.8.5
> babel-runtime@0.1.9_1
> ecmascript@0.4.8
> ecmascript-runtime@0.2.12
6c6
< modules@0.6.2
---
> modules@0.6.5
8,9c8,9
< omega:meteor-desktop-bundler@0.2.1
< promise@0.7.2
---
> omega:meteor-desktop-bundler@0.2.2
> promise@0.7.3
diff -r omega_meteor-desktop-bundler-0.2.1-source/omega_meteor-desktop-bundler/package.js omega_meteor-desktop-bundler-0.2.2-source/omega_meteor-desktop-bundler/package.js
4c4
<     version: '0.2.1',
---
>     version: '0.2.2',
```

There are some older versions of core packages in use there.  `modules@0.6.2`, for example, is from Meteor 1.3.3.  Interesting that it took a jump between those two `publish`s though.

**Comment by wojtkowiak** [comment]
That is weird. I thought that it should not matter what version was used to publish it. I was thinking that the meteor version from package.js is only taken into account and I have a `METEOR@1.3.3` there.

Apart from that I am still not sure to this day if dependency version in build plugin must equal to the one used in the meteor version you want the build plugin to be compatible with. 
https://github.com/wojtkowiak/meteor-desktop/blob/master/plugins/bundler/package.js#L12
I've put 0.4.4 there because it is used by meteor 1.3.3 - not sure if I could specify the newest and still have this working on older meteor version.

**Comment by wojtkowiak** [comment]
Just happened again. Published `0.2.4` and it has the same problem.
It is missing about 2mb of data. That is at least the size difference. It looks exactly like `0.2.1`.

The biggest difference is here `.meteor\packages\omega_meteor-desktop-bundler\0.2.4\plugin.meteor-desktop-bundler.os\npm\node_modules\meteor\babel-compiler\node_modules`
At the wrongly published package there are only two dependencies there while there should a big bunch of them.
![0 2 1](https://cloud.githubusercontent.com/assets/8668306/21068816/a861fa76-be74-11e6-9697-8e8a617dc5ac.png)

That how it looks on `0.2.3`.
![0 2 3](https://cloud.githubusercontent.com/assets/8668306/21068818/aa9226d6-be74-11e6-898d-e362239acc35.png)

I do not have the time currently to dig into how Meteor is packaging those deps so I would appreciate any hints...

**Comment by wojtkowiak** [comment]
Hmm on a second glance, it seems like one was installed by npm2 and the other with npm3, how is that possible?

**Comment by wojtkowiak** [comment]
What is going on, now the `0.2.4` worked in another project...
Seems that it works when installed by older meteor version. 
**Here is a repro that works on my Windows:**
```
meteor create test1 --release=METEOR@1.4.2.3
cd test1
meteor add omega:meteor-desktop-bundler@=0.2.4
```
You will see in `.meteor\packages\omega_meteor-desktop-bundler\0.2.4\plugin.meteor-desktop-bundler.os\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-transform-es2015-modules-commonjs\node_modules\babel-templates\node_modules\lodash` that is has only few files:
![wrong](https://cloud.githubusercontent.com/assets/8668306/21069307/cb5e0368-be78-11e6-9d68-d63b7ed38d6c.png)

Now delete the `0.2.4` from `.meteor\packages\omega_meteor-desktop-bundle`.
```
meteor create test2 --release=METEOR@1.3.4.1
cd test2
meteor add omega:meteor-desktop-bundler@=0.2.4
```
This time all the files are there... and it works also in 1.4.2 now.
![ok](https://cloud.githubusercontent.com/assets/8668306/21069365/6a1b7d32-be79-11e6-9124-9bd5efe91dc2.png)

**Comment by abernix** [comment]
The version of the tool you use to publish is definitely relevant as different versions of the tool will pay attention to different dependencies as releases have changed.  For example, I believe the location that you run it from in the sense that you could be inadvertently including `devDependencies` that may not be desired (see #7958) and also the dependencies you do want are found by the [`ImportScanner`](https://github.com/meteor/meteor/blob/devel/tools/isobuild/import-scanner.js#L1).  Essentially, if you're not `require`-ing the packages, they would just be excluded.

If you prefer to use the existing logic, then using an older release, as you have with `--release=METEOR@1.3.4.1` would work, but the changes were made for various reasons and I believe you can achieve the correct behavior with the recent tool by ensuring the correct dependency chain is defined.

**Comment by wojtkowiak** [comment]
@abernix thanks for your help. So far this did not occur anymore so I had no reason to investigate it further. Closing for now 😃
