### ISSUE TITLE
Unexpected token error without any apparent fix

### ISSUE THREAD

**Issue by alejandroiglesias** [meteor/meteor#8114]
Meteor version: 1.4.2.3
Node version: 4.6.2
Platform: macOS Sierra

After manually editing a package I saw this very strange error that cannot fix by any means.

```
/usr/local/bin/meteor --port 4000
[[[[[ <project-directory> ]]]]]

=> Started proxy.
[BABEL] Note: The code generator has deoptimised the styling of "/client/compatibility/mapbox-gl/v0.26.0/mapbox-gl.js" as it exceeds the max of "100KB".
=> Errors prevented startup:
   
   While computing assigned variables:
   /packages/velocityjs_velocityjs/packages/velocityjs_velocityjs.js:
   Unexpected token (3089:24)
   
=> Your application has errors. Waiting for file change.
```

Steps to reproduce:

1. Create a meteor project
2. Run `meteor add velocityjs:velocityjs`
3. Edit the `.meteor/local/plugin-cache/velocityjs_velocityjs/1.2.1/velocityjs_velocityjs.js` (in my case I pasted the contents from Velocity.js 1.3.2.
4. The Meteor server seems to complain about an incorrect package with that error.

Tried `meteor remove velocityjs:velocityjs && meteor add velocityjs:velocityjs`, `git clean -f -d -x`, `meteor reset`, anything, but the error is still there. Now one thing I noticed after running those commands is that now the `.meteor/local/plugin-cache/velocityjs_velocityjs/1.2.1/` is always empty, even after doing `meteor add velocityjs:velocityjs`.

Can somebody please clarify on the error message? I guess this is not a known issue since I tried to search for it but haven't found anything.
Thanks.

**Comment by alejandroiglesias** [comment]
Ok, it was solved by the last resort fix: reinstalling Meteor (`curl https://install.meteor.com/ | sh`).
Any idea why that could happen?

**Comment by abernix** [comment]
You should not be manually editing files in `~/.meteor/local/` which have been compiled by the `meteor` tool.  I'm sure where you got the idea to do that, but if it's documented in some tutorial somewhere please report it so it can be corrected.  I'm certain that nowhere in the Meteor Docs does it recommend modifying compiled code.

If you need to make changes to a package for your own purposes, you should use the proper method documented in this section on [Overriding Atmoshpere Packages](https://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages).

You may also want to consider submitting a pull request to the actual package as it seems they are willing to get this updated to 1.3.2 but need assistance: julianshapiro/velocity#597

**Comment by abernix** [comment]
It should probably also be pointed out that Meteor [natively supports NPM packages](https://guide.meteor.com/using-npm-packages.html), so you might not even need this package anymore since [VelocityJs is on NPM](https://www.npmjs.com/package/velocity.js).

**Comment by alejandroiglesias** [comment]
@abernix you know the direction I was heading to. 😄 
I just wanted to do a quick check to see if I could get some benefit from the newer version and I wanted to try the latest version from that library (which is not yet on NPM). I haven't got the idea of modifying contents from `.meteor/local/` from any tutorial but my own ideas. I understand it doesn't make any sense, just trying a quick patch to check something.
Thanks for pointing out to the docs on Overriding Atmosphere Packages, that's what I ultimately needed to do.
Still, the error is not too descriptive and it seems weird to me that you need to re-install Meteor if you do this.
Cheers!
