### ISSUE TITLE
formData not working , after append , i got empty form data

### ISSUE THREAD

**Issue by aayushsinghm16** [meteor/meteor#8125]
# This is my code 
    var formData = new FormData();
    formData.append('file',file);
    var options = {
       data:{"file":formData}
       }
    console.log(formData);
    HTTP.call( 'POST','http://localhost:3000/qwe',options, function( error, response ) {
      if ( error ) {console.log( error );}else{console.log(response)}});
## here i m logging formdata but i get 
FormData {}

**Comment by abernix** [comment]
This has nothing to do with Meteor, you're using `FormData` wrong or expecting it to do something it's not intended to do.

`FormData` is a special type of object which is not stringifyable can cannot just be printed out using `console.log`.  You **may** have some luck with [`util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options).  But what you're doing still won't work the way you have it.

Please read the [`FormData` docs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) and also some additional information about how it is serialized [over here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Using_FormData_objects) if you're truly curious.

You should be able to just pass the `formData` in the [`content` option to `HTTP.call`](https://docs.meteor.com/api/http.html#HTTP-call).  You will not want to use `data` (as you are right now) since it overwrites `content`:

```js
var formData = new FormData();
formData.append('file', file);
var options = { content: formData };

HTTP.call( 'POST','http://localhost:3000/qwe', options, ...as above...);
```

**Comment by FredGauld** [comment]
Thanks! That really helped me.  I'm surprised it's not mentionned anywhere in the FormData official documentation that it can't be console.logged.  Good to know!

**Comment by maneeshrao66** [comment]
Hi I have facing same issue formData is showing empty in payload of Chrome browser while sending the formdata to server. Can you please help me?
 
FormData {}.  

  public uploadToServer() {
    let blob  = this.recordRTC instanceof Blob ? this.recordRTC : this.recordRTC.blob;
    let fileType = blob.type.split('/')[0] || 'audio';
    let fileName = (Math.random() * 1000).toString().replace('.', '');
    if (fileType === 'audio') {
      fileName += '.' + (!!navigator.mozGetUserMedia ? 'ogg' : 'wav');
    } else {
      fileName += '.webm';
    }
    // create FormData
    console.log(fileType);
    console.log(fileName);

    var formData: FormData = new FormData();
    console.log(formData);
    formData.append(fileType + '-filename', fileName);
    formData.append(fileType + '-blob', blob);
    var options = { content: formData };

    console.log(options);
     this.dashService.saveRecording(formData).subscribe(
       data => this.saveRecordingSuccess(data),
       error => this.saveRecordingFail(error)
     );
  }

**Comment by daton89** [comment]
if you really need to log data in formData you can use entries method with a for of:

```
		for (var key of formData.entries()) {
			console.log(key[0] + ', ' + key[1])
		}
```

**Comment by Cosqui** [comment]
hello:

I have the problem when adding two images in a dataForm of type src blob empty when adding them to the forData

<img width="543" alt="1" src="https://user-images.githubusercontent.com/21096238/45592704-621b5400-b93a-11e8-8cfc-da3a51bc85b6.png">

TargetaFirmaEntrega.prototype.sendFormData = function(){
    var formData = new FormData()
    
    var firma_rentrega_ = targeta_firma_entrega.sig_entrega
    var firma_responsable_ = targeta_firma_entrega.sig_responsable
    formData.append("firma_entrega",firma_rentrega_)
    formData.append('firma_responsable',firma_responsable_)
    data = {
        'content':formData
    }
  
    
    var request = new XMLHttpRequest()
    request.open("POST",window.location.origin + "/ajax_upload/")
    request.responseType = "blob"
  
    request.setRequestHeader("Content-Type", "application/json");
    request.setRequestHeader("X-CSRFToken", appnova.galletita);
    
    request.send()
   
    
}

**Comment by jerryhsieh** [comment]
You can try 
formData.forEach((value, key) => {                                                                                                                       
      console.log("key %s: value %s", key, value);                                                                                                           
 })

**Comment by Adamkzh** [comment]
I think the problem is the browser takes a too long time to append a base64 image. at the same time, the HTTP call already sent to the back-end server. So you will get empty formData in the server.

**Comment by lawrenceagles** [comment]
Try using the .get() method. Like this:
    `console.log(formData.get("usernaname"))`
    `console.log(formData.get("firstname"))`
As the case maybe.

**Comment by riadhabdelwahed** [comment]
hello
i have a probleme with empty data formData. pleaze help me


 <script type="text/javascript">
        $('body').on('click', '.btn_new_filiere', function (event) {
            $('#modalNewFiliere').modal('show');
            var url=$(this).attr('url');
            $.ajax({
                url: url,
                method: 'POST',
                success: function (result) {
                    $('.modal-body').html(result);
                }
            });
        });
        $('body').on('click', '.save_filiere', function (event) {

           var form = $('#form_add_filiere');
           var formData=new FormData(document.getElementById("form_add_filiere"));

                   alert(formData.form_add_filiere);
                     
            $.ajax({
                type: 'POST',
                cache: false,
                data: formData,
                url: form.attr('action'),
                processData: false,
                contentType: false,

                beforeSend:function(XMLHttpRequest){
                    $('#form_add_filiere').attr('disabled',true);
                    alert('before submit');

                },

            success: function (msg) {
                   if(msg=='ok'){
                       $('#modalNewFiliere').modal('hide');
                   }else{
                       $('.modal-body').html(msg);
                      alert('erreur');
                   }
                }
            });

        })
    </script>

**Comment by Lavanya2021** [comment]
Hii all,
 i have to send the data using FormData like 
{
id:"id",
edit_name:{
"fname":"fname",
"lname":"lname",
"photo":file
}
}

can anyone suggest how to send the data using FormData in angular 6?

Thanks

**Comment by filipenevola** [comment]
Hi @Lavanya2021 it would be better to ask for help in the https://forums.meteor.com/

We use issues only for Meteor things.

**Comment by Kavyababu1794** [comment]
I am trying to attach a file in formData , I tried many ways but couldn't fix this issue

let formData = new FormData();    
formData.append('file','../../../../../assets/file.txt');

this.http.post(this.parameter, formData).subscribe(event => {
      this.api_response_holder = event
        this.loading = false;
    });

and also tried this way

  var request = new XMLHttpRequest();
  request.open('POST', '../../../../../assets/file.txt', true);
  request.send(formData);

In both ways I couldn't achieve., in firstway its not throwing any error but in second way Im getting **404 not found** error even though path is correct.

**Comment by Aymenob** [comment]
for (var key of formData.entries()) {
			console.log(key[0] + ', ' + key[1])
		} i use this and it shows that my data is ready and loaded but when dispatching it becomes empty when i check the payload , does anyone have an idea why ?

**Comment by usama-malik-312** [comment]
console.log( ...formData)

**Comment by marufmarzuq** [comment]
Use this code
`   for (const value of formData.values()) {
      console.log(value);
    }`

**Comment by marufmarzuq** [comment]
You can use this code to console the values inside of a formData
`for (const value of formData.values()) {
      console.log(value);
 }`

**Comment by Zer-0ne** [comment]
const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        if (name === 'image') {
            if (!e.target.files) return;
            const file: File | null = e?.target.files[0];
            setImg(file)
            formData.set('image', file);
         }
        formData.set(name, value);
    }
    
the output of formData value is 
null null null null null
can anyone correct this?

**Comment by ShukurovOzodbek** [comment]
You can log your formdata key as an example
`
console.log(formData.get("usernaname"))
`

or if you want to дщп right away, you can use

`
console.log(...formData)
`

**Comment by rogeriorioli** [comment]
I didn't use formdata and sent the file object directly to the object payload

`
  const handleSubmit = async (event) => {

    event.preventDefault();
    const file = event.target.files[0];
    const options = {
      audio : file
    }
    
    try {
      const response = await api.post('/upload', options, { 
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });
      await getData();
      console.log('Upload successful:', response.data);
    } catch (error) {
      // Handle errors
      console.error('Error uploading file:', error);
    }
  };
`

**Comment by Kbadr1** [comment]
> I didn't use formdata and sent the file object directly to the object payload
> 
> `
> 
> const handleSubmit = async (event) => {
> 
> ```
> event.preventDefault();
> const file = event.target.files[0];
> const options = {
>   audio : file
> }
> 
> try {
>   const response = await api.post('/upload', options, { 
>     headers: {
>       'Content-Type': 'multipart/form-data',
>     },
>   });
>   await getData();
>   console.log('Upload successful:', response.data);
> } catch (error) {
>   // Handle errors
>   console.error('Error uploading file:', error);
> }
> ```
> 
> };
> 
> `

did this work ??

**Comment by abhishekraj15** [comment]
const handleSubmit = (event) => {
    event.preventDefault();
    setIsloading(true);

    console.log("Normal formdata:", formData);

    const formDataToSend = new FormData()
    formDataToSend.append("fullName", formData?.fullName);
    formDataToSend.append("email", formData?.email);
    formDataToSend.append("dob", formData?.dob);
    formDataToSend.append("motherTongue", formData?.motherTongue);
    formDataToSend.append("gender", formData?.gender);
    formDataToSend.append("address", formData?.address);
    formDataToSend.append("state", formData?.state);
    formDataToSend.append("city", formData?.city);
    formDataToSend.append("postalCode", formData?.postalCode);
    formDataToSend.append("experience", formData?.experience);
    formDataToSend.append("qualification", formData?.qualification);
    formDataToSend.append("applied", formData?.applied);
    formDataToSend.append("skills", formData?.skills);
    formDataToSend.append("message", formData?.message);

    if (formData?.file) {
      formDataToSend.append("file", formData?.file);
    }

    console.log("FORMDATA", formDataToSend);
    
    
    console.log("Normal formdata:", formData);  this line will console properly all data but
    console.log("FORMDATA", formDataToSend);  this line console a empty object

**Comment by mdshahbajalam7** [comment]
this is my code 
 const IdProofUploadPromises = data?.id_Proof?.map(async (idProof, index) => {
      if (idProof.img) {
       console.log(idProof.img);
        const formData = new FormData();
         formData.append('file', idProof.img, idProof.img.name);
     console.log(formData, 'formData');
    const response = await axiosInstanceMain.post('/whatsapp/upload', formData);
    const result = await response.data;
      return { ...idProof, img: result.location };
   }
   return idProof;
 });
 
 here i m logging formdata but i get
 FormData {}

**Comment by abhishekraj15** [comment]
Show me the header of this endpoint

**Comment by ParvathyRaju116** [comment]
Hi I have facing same issue formData is showing empty in payload of Chrome browser while sending the formdata to server. Can you please help me?

FormData {}.      

  const handleCreateOrganization = async (e: any) => {
    e.preventDefault(); 
    const formData = new FormData();
    formData.append("organizationLogo", inputData.organizationLogo);        
    formData.append("organizationName", inputData.organizationName);
    formData.append("organizationCountry", inputData.organizationCountry);
    formData.append("organizationIndustry", inputData.organizationIndustry);
    formData.append("addline1", inputData.addline1);
    formData.append("addline2", inputData.addline2);
    formData.append("city", inputData.city);
    formData.append("pincode", inputData.pincode);
    formData.append("state", inputData.state);
    formData.append("organizationPhNum", inputData.organizationPhNum);
    formData.append("website", inputData.website);
    formData.append("baseCurrency", inputData.baseCurrency);
    formData.append("fiscalYear", inputData.fiscalYear);
    formData.append("reportBasis", inputData.reportBasis);
    formData.append("language", inputData.language);
    formData.append("timeZone", inputData.timeZone);
    formData.append("dateFormat", inputData.dateFormat);
    formData.append("dateSplit", inputData.dateSplit);
    formData.append("companyId", inputData.companyId);
    formData.append("companyIdField", inputData.companyIdField);
    formData.append("taxId", inputData.taxId);
    formData.append("taxIdField", inputData.taxIdField);
    // formData.append("addfield", inputData.addfield);
    formData.append("qrLocation", inputData.qrLocation);
    formData.append("qrSignature", inputData.qrSignature);
    formData.append("twitter", inputData.twitter);
    formData.append("insta", inputData.insta);
    formData.append("linkedin", inputData.linkedin);
    formData.append("facebook", inputData.facebook);
    formData.append("accountHolderName", inputData.accountHolderName);
    formData.append("bankName", inputData.bankName);
    formData.append("accNum", inputData.accNum);
    formData.append("ifsc", inputData.ifsc);

    // Log the formData entries
  console.log(formData,"FD");
  console.log(inputData,"ID");
  
  

    try {
        const url = `${endponints.CREATE_ORGANIZATION}`;
        const apiResponse = await createOrganization(url,formData);
        console.log(apiResponse, "api response");
        
        const { response, error } = apiResponse;
        if (!error && response) {
            toast.success(response.data.message);
            console.log(response.data.message, "message");
        } else {
            console.log(error.response.data.message);
            toast.error(error.response.data.message);
        }
    } catch (error) {
        console.log(error, );
    }
};
