### ISSUE TITLE
Unnecessary \n added to head and body

### ISSUE THREAD

**Issue by PEM--** [meteor/meteor#8130]
Adding `\n` to `head` and `body` increases build time for no reason and decrease SEO ranking.

Removing these addition in `isopack.js` would solve this issue: https://github.com/meteor/meteor/blob/devel/tools/isobuild/isopack.js#L1345

**Comment by mitar** [comment]
Why it decreases SEO ranking?

**Comment by PEM--** [comment]
When Panda (Google's ranking algorithm) find unoptimized payload, it decreases its rank when compared to optimized ones. A good rule of thumb here is to check the info provided by PageSpeed insights.

**Comment by mitar** [comment]
If you care about that, shouldn't you put all HTML through a minimizer/optimizer? Because there are also many other newlines being added everywhere.

**Comment by PEM--** [comment]
Indeed, there are other new lines added here and there which should also be removed too.

I agree that adding an HTML minifier would do the trick but would also add a lengthier and unecessary build process which would defeat the purpose of the upcoming release.

**Comment by mjmasn** [comment]
@PEM-- I find it hard to believe whitespace in html decreases SEO ranking, do you have a source? Everything I can find on the web says Google (and other search engines) ignore whitespace. I guess it doesn't hurt to optimise but assuming you have gzip enabled on your server you'd barely save 100 bytes (vs the 1-2 _million_ byte size of the app) by removing whitespace anyway.

**Comment by PEM--** [comment]
OK. I get it. Didn't want this issue to turn into a discussion thread.
