### ISSUE TITLE
addAssets limit, not all files getting bundled

### ISSUE THREAD

**Issue by Narzerus** [meteor/meteor#8134]
Hello, I'm using Meteor 1.4.2.3 in OSX. I'm working on a project where we need to use the `addAssets` method in `package.js` to add a big amount of files.

The thing is that at some point files stopped getting bundled in an unpredictable way.

Here's a snippet of code in our `package.js`

```javascript
api.addAssets(getFilepathsFromFolder('styles/bigbusiness'), 'server');
api.addAssets(getFilepathsFromFolder('styles/bluerock'), 'server');
api.addAssets(getFilepathsFromFolder('styles/greencon'), 'server');
```

`getFilePathsFromFolder` simply looks recursively for all the files it can find in a certain directory. For what I checked this is working correctly and returns an array of paths.

The thing is , if I comment out any 2 lines in the previous snippet, the files that are left are correctly bundled in build time. But if I uncomment one more (meaning there are more files going to be bundled) then some files start to be omitted.

Is there some limit to the amount of assets we can add? Or is this some bug.

Thanks

**Comment by mitar** [comment]
I would suggest that you create a reproduction?

**Comment by Narzerus** [comment]
This issue got duplicated, sorry. Not a bug really
