### ISSUE TITLE
Source maps not generated when CoffeeScript source files are located in project subfolders such as client, server, imports etc.

### ISSUE THREAD

**Issue by JacquesRobin** [meteor/meteor#8138]
The repository: [https://github.com/JacquesRobin/MeteorClickCounterBlazeJadeCoffee](https://github.com/JacquesRobin/MeteorClickCounterBlazeJadeCoffee) contains two branches of the minimal Meteor button click counter example using Blaze with CoffeeScript and Jade templates. 

Both branches contain only two source code files: `main.coffee` and `main.jade`.

They differ only in the location of these two source files:
- In the branch `FilesAtProjectFolderTopLevel` they are in the root project folder.
- In the branch `UnderClientFolderNoImports` they are in the `/client/ `subfolder.

With the first branch, running the `meteor` command generates two source maps files respectively found under:
- `.meteor/local/build/programs/server/app/app.js.map`
- `.meteor/local/build/programs/web.browser/app/app.js.map`

With the second branch, running the `meteor `command fails to generated these source map files. 

This is with meteor 1.4.2.3. on both Windows 7 and OS X El Capitan 10.11.6.
The package dependencies can be found in the file: `.meteor/packages` of both branches.

**Comment by datanotion** [comment]
I'm getting the same issue - causing issues when trying to debug, as coffee files won't show in the console.

**Comment by JacquesRobin** [comment]
Indeed, this bug makes debugging Meteor apps written in CoffeeScript fully unproductive using state-of-the-art IDEs such as WebStorm and VSCode. 

In turn, this lack of working debugging support reduces Meteor documentation statements such as:
> CoffeeScript has been a first-class supported language since Meteor’s early days. Even though today we recommend ES2015, we still intend to support CoffeeScript fully.

into deceptive marketing.

Without source map generation, CoffeeScript is just not fully supported.

**Comment by hwillson** [comment]
Hi @JacquesRobin - your issue sounds related to the recently resolved issue #8281. The fix for this has been merged and will be coming in release 1.4.3.1. While not officially recommended yet, you can try things out using:

```
meteor update --release 1.4.3.1
```

I'll close this for now - please post back if this problem is still not resolved. Thanks for posting this originally!
