### ISSUE TITLE
Meteor.call loses information about object constructors

### ISSUE THREAD

**Issue by ysimidjiyski** [meteor/meteor#8140]
running Meteor 1.4.2.3 on Windows 8.1/Chrome  	54.0.2840.99

Meteor.call() appears to lose information about the constructor of any passed arguments.  This issue becomes particularly noticable when using Meteor.check(), which can match against constructors. If Meteor.call loses information about the argument's type, then Meteor.check()'s constructor-based matching fails.

I've checked the documentation at https://docs.meteor.com/api/methods.html#Meteor-call, and I haven't see anything to indicate that Meteor.call is supposed to lose this information, so I am filing this as a bug.

There is also a small thread on StackOverflow about this issue, but no solutions offered: http://stackoverflow.com/questions/36530084/meteor-check-object-is-instance-of-class

I've created a minimal repro using the default meteor project here:  https://github.com/ysimidjiyski/meteor-check-constructor-issue

Take a look at the README in that repository for details on how to see the issue.  It's pretty straightforward.  

If it turns out that this behavior is already documented, is intentional, and I just failed to find that information, apologies!  I'm still fairly new to Meteor, but I've attempted my due diligence and I haven't found documentation or existing bugs on this issue.

**Comment by abernix** [comment]
This is working as intended and is actually documented in the first link you posted.  Keep in mind that whatever you send over `Meteor.call` is transported between the client and the server as a JSON object.

Specifically, you'll note that the arguments to `Meteor.call` are "EJSON-able Object"s.  If you click on that term you'll see the documentation for EJSON which specifies what is an "EJSON-fiable" object.  Supported by default is anything that JSON natively supports (e.g. `String`, `Number`, etc), but also additional types which have supported explicitly added for them (e.g. `8Int8Array` and `Mongo.ObjectID`).

I'd assume you'd be interested in adding your own user-defined type, and [the docs](https://docs.meteor.com/api/ejson.html#EJSON-addType) explain how to do that as well.

**Comment by ysimidjiyski** [comment]
Thanks for that info -- sorry about the erroneous report!
