### ISSUE TITLE
IE browser error with Number constructor in meteor/check package

### ISSUE THREAD

**Issue by canvas103** [meteor/meteor#8141]
in IE 9> console
>> check(12,Number) 
"Match error: Expected Number" 
>> check(Number(12),Number) 
"Match error: Expected Number" 
>> check(new Number(12),Number)

**Comment by abernix** [comment]
You haven't included enough information to help debug this, but this does not happen in a brand new project on IE9.  Please see [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for what is expected when opening an issue.

I created a new app with `meteor create app` and added a single line in `client/main.js` within `onCreated` to ensure that `check` was available in the global scope:

```js
window.check = require('meteor/check').check;
```

Then, upon checking the Console in IE9, it returns this:

<img width="699" alt="screen shot 2016-12-12 at 6 11 44 pm" src="https://cloud.githubusercontent.com/assets/841294/21106362/7cd0d764-c096-11e6-987f-5d3b5bffba10.png">

Most likely, you have some other library which is overriding or changing `Number.prototype`.  I'm confident that if you try to reproduce this on a new Meteor project, you will not see this happen.  If you can reproduce it in a brand new project, please include that information here with **exact reproduction steps** and someone will be happy to look at it/re-open.
