### ISSUE TITLE
Meteor Not Working At All

### ISSUE THREAD

**Issue by theasimzaidi** [meteor/meteor#8143]
I'm going through the Angular Meteor tutorial on my Macbook and I tried restarting the Socially tutorial after getting lost in it a few times and all of a sudden I'm running into this issue when I tried running meteor it said 'command not found' So I tried reinstalling Meteor and now I'm getting this strange error message (weird, because I am the admin on my computer so I believe I have all rights..) Now I can't find anything online to help me get out of this issue if anyone could please help, thanks!

![screen shot 2016-12-11 at 11 13 54 pm](https://cloud.githubusercontent.com/assets/4612744/21112274/d6f758e8-c06a-11e6-9456-2a23a0ede8fb.png)

**Comment by frank0r** [comment]
just run  **sudo rm -R ~/.meteor** and then run **curl .....** again.

**Comment by abernix** [comment]
Make sure that you're not using `sudo` to run any of the `meteor` commands, ever.  It appears that you must have at some point and now you're encountering permission issues (as expected).

Please remove your Meteor installation by using `sudo rm -rf ~/.meteor` and then reinstall using:

    curl https://install.meteor.com/ | sh
