### ISSUE TITLE
Meteor create --bare should not add the insecure and autopublish packages

### ISSUE THREAD

**Issue by cwohlman** [meteor/meteor#8145]
I believe that the `meteor create --bare` command should not add the insecure and autopublish packages. This command looks as if it's intended for use by experienced meteor devs who want to start a new project without the 'beginner' meteor files, and as such removing autopublish and insecure is probably way more important than removing the initial html, js, and css files (since autopublish and insecure create hidden security vulnerabilities).

I think the same argument could be made for `meteor create --scaffold`.

**Comment by abernix** [comment]
@dburles Your thoughts?

**Comment by dburles** [comment]
Yeah, I think it makes sense to remove them from both

**Comment by abernix** [comment]
@cwohlman Would you be interested in [submitting a pull-request](https://github.com/meteor/meteor/blob/devel/Contributing.md#submitting-pull-requests) for this?

It should only involve removing the (package) lines from [this file](https://github.com/meteor/meteor/blob/e34e236fe089067072c049a65693c8922d24e11e/tools/static-assets/skel-bare/.meteor/packages) which was originally implemented in #7807.  You can run Meteor from a Git checkout by using [these instructions](https://github.com/meteor/meteor/#slow-start-for-developers).

If not, I'll get to this next week, but a PR contribution would certainly be appreciated. :)

**Comment by cwohlman** [comment]
Sure

**Comment by cwohlman** [comment]
Ok, done.

**Comment by cwohlman** [comment]
Note, `meteor create --scaffold` already doesn't add the autopublish and insecure packages, so I didn't need to change anything there.

**Comment by abernix** [comment]
Thank you, @cwohlman!  #8183 was merged and this will be included in a future release of Meteor.
