### ISSUE TITLE
Automatic/unnamed publish (null) subscription should have a ready as well

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8146]
Currently it seems there is no way to know when automatic/unnamed publish (null) subscriptions are ready. So you do not really know if user object is not yet populated with all fields from null subscription, or they are missing. For example, [roles package](https://github.com/alanning/meteor-roles/blob/master/roles/roles_server.js#L21) then uses a named subscription so that one can check if roles are really published (and then [subscribing in startup](https://github.com/alanning/meteor-roles/blob/master/roles/client/subscriptions.js#L21)). This should be unnecessary to do in my opinion.

We should provide a global `ready` for all unnamed publish functions.

**Comment by mitar** [comment]
Is this pull request encouraged?

**Comment by abernix** [comment]
We should start by laying out a more solid proposal and if it sounds good then we can add `confirmed` and `pull-requests-encouraged` onto it if it all sounds good.

This is all per the [Issue Triage](https://github.com/meteor/meteor/blob/devel/IssueTriage.md#feature-requests) procedure, btw.

**Comment by mitar** [comment]
My proposal: I would just add `Meteor.connection.ready()` as a reactive source for all unnamed subscriptions on that connection.

We could have a label which tells what is missing. Or at least a comment.

**Comment by abernix** [comment]
`Meteor.connection.ready()` seems easily misunderstood, especially if it omits named subscriptions, but mostly because to the end-user it seems like a connection-ready and doesn't suggest that it has anything to do with a subscription.

In regard to your other concern: A _lack_ of labels shows what is missing.  If it has a clear plan, it will have `confirmed` and if it's something a community contribution would be accepted on, `pull-requests-encouraged`.

**Comment by mitar** [comment]
A new proposal.

Why we do not have `Meteor.subscriptionsReady()` and `Meteor.unnamedSubscriptionsReady()`? The first one is one which is ready when all current subscriptions is ready. This is what you already mostly want to check anyway.

And those would just be a helpful aliases for default connection. We would augment the return object from `DDP.connection` to have `subscriptionsReady` and `unnamedSubscriptionsReady`.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Automatic%2Funnamed%20publish%20(null)%20subscription%20should%20have%20a%20ready%20as%20well&body=Migrated%20from:%20meteor/meteor%238146) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
