### ISSUE TITLE
Update cordova to the latest 6.4.0 version

### ISSUE THREAD

**Issue by anymos** [meteor/meteor#8155]
Cordova 6.4.0 is available, most of the plugin are still of good use with the previous version.

Unfortunately the latest Cordova notification plugin (https://github.com/phonegap/phonegap-plugin-push) require the latest cordova version 6.4.0. I believe that the notification is a critical plugin for any mobile application, and consequently for Meteor

Accordingly to the discussion started  : https://forums.meteor.com/t/how-to-update-cordova-to-the-latest-6-4-0-in-meteor/31809/1

And the advise given here (https://forums.meteor.com/t/meteor-roadmap-update-12-13-16/32261/5) to have issues added to the roadmap for Meteor next version

Thank you very much in advance

**Comment by abernix** [comment]
Thanks for opening this issue.  I would be in favor of making this two separate issues.  One issue (and PR, hopefully) which handles the update to 6.4.0 and is hopefully more short-term (potentially even in 1.4.3 if someone was to take it on?) and another issue to handle everything after the word "ideally" in the current title :smile: Essentially, addressing the steps necessary (and again, a separate PR) to decouple `cordova-lib`, but in what is more likely a bigger project for a future release.

As to summarizing what was necessary during the last upgrade and likely needs to be looked at for the 6.4.0 upgrade:

* [These changes on `meteor/meteor`](https://github.com/meteor/meteor/compare/cc9882b12df15488a8ff0229a5514a2c43281028...6b0fc9110b6e5fe4b4469f37910fbe109959e858), which broken down, comprise of:
  * cc9882b12df15488a8ff0229a5514a2c43281028
  * 6322a55985c8b25483a3443f848640cdfc837cc7
  * 458c5b40f05ca3a81622dee394148970393ed33a
  * f574b46adceab1db52cd6bcb9ce6086880048ba2
  * e9aa8082dc190fdebcc0e2928ae4b265b7ba4110
  * 6b0fc9110b6e5fe4b4469f37910fbe109959e858
* The last commit above is just a version bump to include the commits in `meteor/cordova-plugin-meteor-webapp` [seen here from `dd2d61...10d4dd`](
https://github.com/meteor/cordova-plugin-meteor-webapp/compare/dd2d61589c27fe41c56778cb9f7bfab41a612fbd...10d4ddbc907b57c70070e7be4eab44a4b069b966), which may not be necessary for going to 6.4.0.

**Comment by skirunman** [comment]
Would be awesome to get the first part of this request, the update to Cordova 6.4.0/iOS 4.3.1/Android 6.1.0 as part of [Meteor 1.4.3 release](https://github.com/meteor/meteor/pull/8123).

**Comment by abernix** [comment]
I've broken this into two issues and left this issue to be solely for the portion pertaining to upgrading Cordova to 6.4.0.  The decoupling of Cordova will be tracked in #8195.

If someone wants to start taking a look at this to make a contribution to Meteor, I'd be happy to help review or point you in the right direction however possible but I think my above notes summarize the best place to start!

**Comment by wojtkowiak** [comment]
@abernix will you handle this or is this more like a 'pull request encouraged'? 🙂

**Comment by abernix** [comment]
@wojtkowiak As I believe this is relatively well laid out above, I'll mark this `pull-requests-encouraged` (Honestly, I should have already).  If you have some time, I'm happy to review! I'm a bit busy with some stuff at the moment but will review asap. 😀

**Comment by wojtkowiak** [comment]
@abernix I have the changes ready but I am unsure what to do next in order to be able to test it.
I do need to make a new dev bundle and make meteor running from checkout to use it? Or is there any other way?

**Comment by wojtkowiak** [comment]
Hmm I will just manually update `cordova-lib` in the bundle that was downloaded - I guess that is the easiest and fastest. Hope that is considered ok when testing.

**Comment by wojtkowiak** [comment]
Is there any chance this could be included in `1.4.3`?

**Comment by abernix** [comment]
Thanks very much for working on this, @wojtkowiak.  You don't need to worry about bumping Meteor package versions, it will be done when the release is published with [this script](https://github.com/meteor/meteor/blob/devel/scripts/admin/bump-all-version-numbers.js#L1) by whoever makes the release.

**Comment by wojtkowiak** [comment]
@abernix, big thanks for this crucial information I was missing about building the bundle. Can I add this info here https://github.com/meteor/meteor/blob/devel/Contributing.md? I guess it might be helpful for other potential contributors.
So far I have conducted the tests by modifying manually the dev bundle that was downloaded by the checkout.

**Comment by abernix** [comment]
@wojtkowiak It's briefly mentioned on the "[Slow Start for Developers](https://github.com/meteor/meteor/#slow-start-for-developers)" section of the `README.md` but I think there should be a single start point for development and we've discussed that briefly in #7823.  I've opened #8267 which is something we should get under way.  Your input/assistance would be appreciated there!

Also, yes, I hope to your Cordova changes into the 1.4.3 cycle.  I'll test/review this week!

**Comment by abernix** [comment]
Thanks to @wojtkowiak, this Cordova 6.4.0 upgrade has been completed in the latest Meteor `1.4.3-beta.3`.  I'd invite any interested parties to take a look and try it out and provide feedback here!  You can update to the latest Meteor beta by running:

    meteor update --release 1.4.3-beta.3

As this is a major Cordova upgrade, the 1.4.3 upgrade will require resubmitting the app to the app store (versus the usual hot code push approach which works on minor updates).

Closing, but please let me know if it's not working properly!
