### ISSUE TITLE
Enhance minimongo to support secondary indexes

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor#8156]
People often use minimongo both on the server side and client side as an in-memory cache, but it doesn't yet support secondary indexes like normal MongoDB.

This enhancement would allow you to create additional indexes with code like this:

`YourCollection._collection._ensureIndex('fieldName');`

[helfer:minimongo-index](https://github.com/helfer/minimongo-index/) was a third-party attempt at this enhancement but it was far from complete and has not been maintained in over a year.

I think this should be added to the Meteor roadmap.

**Comment by abernix** [comment]
Duplicate.  This is a great suggestion, but closing in favor of the existing #5678.  Please add your +1 or comments there, thanks!
