### ISSUE TITLE
Missing users index

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#8158]
I think the following index is missing:
```
Meteor.startup(() => {
  Meteor.users.rawCollection().createIndex({ 'services.password.reset.when': 1 });
});
```

I had some of these queries that caused our database to lock up because this index was missing.

**Comment by stubailo** [comment]
Seems like that would go in here: https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/packages/accounts-password/password_server.js#L1084

Would be great to see a PR!

**Comment by abernix** [comment]
This has been merged.  Thanks for filing this and for the PR, @elie222!

**Comment by elie222** [comment]
No problem!

**Comment by elie222** [comment]
The index on an array wasn't an issue in the end?

**Comment by abernix** [comment]
Well, it's a potential issue at very high scale much in the same way as #8084 and will need to be fixed in a similar way, but for now it's important to implement as-is.
