### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function during build

### ISSUE THREAD

**Issue by kokokenada** [meteor/meteor#8161]
After updating to meteor 1.4.2.3 and updating as many packages as I could, this build error suddenly popped up:
```
W20161215-15:58:06.403(-5)? (STDERR) /Users/kenono/.meteor/packages/npm-mongo/.2.2.11_2.ze8p4a++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:13
W20161215-15:58:06.403(-5)? (STDERR)   Error.captureStackTrace(this, MongoError);
W20161215-15:58:06.403(-5)? (STDERR)         ^
W20161215-15:58:06.404(-5)? (STDERR) 
W20161215-15:58:06.404(-5)? (STDERR) TypeError: Error.captureStackTrace is not a function
W20161215-15:58:06.404(-5)? (STDERR)     at Error.MongoError (/Users/kenono/.meteor/packages/npm-mongo/.2.2.11_2.ze8p4a++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:13:9)
W20161215-15:58:06.404(-5)? (STDERR)     at Function.MongoError.create (/Users/kenono/.meteor/packages/npm-mongo/.2.2.11_2.ze8p4a++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20161215-15:58:06.405(-5)? (STDERR)     at queryCallback (/Users/kenono/.meteor/packages/npm-mongo/.2.2.11_2.ze8p4a++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/cursor.js:213:36)
W20161215-15:58:06.405(-5)? (STDERR)     at /Users/kenono/.meteor/packages/npm-mongo/.2.2.11_2.ze8p4a++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:455:18
W20161215-15:58:06.406(-5)? (STDERR)     at nextTickCallbackWith0Args (node.js:436:9)
W20161215-15:58:06.406(-5)? (STDERR)     at process._tickCallback (node.js:365:13)
```
My package file is
```

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.14                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.1                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.2   # CSS minifier run for production mode
standard-minifier-js@1.2.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.

angular2-compilers
barbatus:angular2-runtime

aldeed:collection2
session@1.1.7
accounts-password@1.3.3
alanning:roles
jalik:ufs
jalik:ufs-gridfs
browser-policy@1.0.9
mys:fonts

shell-server@0.2.1
konecty:mongo-counter
okland:camera-ui
```
A repository is at: https://github.com/kokokenada/for-real-cards

I tried a complete reinstall of meteor as described at http://stackoverflow.com/questions/24686971/how-can-i-completely-uninstall-and-then-reinstall-meteor-js but the build error still persisted.

**Comment by abernix** [comment]
`Error.captureStackTrace` is a [core Node function](https://nodejs.org/api/errors.html).  If it's being reported as "not a function" it's likely that something your package is using (either an NPM or package) is destroying it elsewhere.  Unfortunately, this app reproduction repository is too complicated to quickly find the answer and will take too much debugging to track it down for you.  Please start by eliminating packages and some of the more than 30 NPMs and you'll likely find the problem along the way.  This does not happen in a basic Meteor project (like [Todos](https://github.com/meteor/todos/))

Please provide a more simple reproduction as requested in the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).  Happy to reopen this same issue if you can do that!

**Comment by kokokenada** [comment]
Something spook is going on.  I did a meteor create to see if a new app would work to eliminate environment problems. It worked fine.  I did an experimental roll back of one library (babel) and my original app worked.  When I re-upgraded the library, everything works.  So the same set of npm packages and atmosphere packages are now working.  Looks like it spurious but others have been hit by it #7620

**Comment by abernix** [comment]
I agree that it's spooky, but again, considering that `Error.captureStackTrace` is built into Node and Meteor only [*calls* it in three places](https://github.com/meteor/meteor/search?utf8=%E2%9C%93&q=Error.captureStackTrace), none of which *modify* it in any way – the culprit is almost certainly something else that your app is depending on.
