### ISSUE TITLE
V1.4.2.3 on Windows Server 2012 missing updates when save made too quickly

### ISSUE THREAD

**Issue by pavlism** [meteor/meteor#8164]
If I make a change in one file, then save, then make change in a different file after the hot code push has started, the changes in the second file don't get noticed.  If you r slow enough it will get picked up.  To test this, change some thing in an HTML file, then save and as quickly as you can go change something in a different HTML file.  The second changes don't show up.

This can also happen if the changes are in the same file.  Makes a series of simple changes (like pasting something) and save after one.  Meteor might go through 2 or 3 refreshes but it will miss stuff.  I pasted the same line of code 5 times and got 2 refreshes, but only saw 2 lines.  I tried it again and got 1 refresh and only saw 1 line.

Unfortunately after many years of coding I have developed a habit of saving after every change, so I do actually run into this problem regularly when coding.

I'm also curious if using a better machine would help this?

**Comment by abernix** [comment]
Aside from being a different version of Windows, this sounds like the same issue we just discussed in your other issue #8106, no?  Can we keep them together if it's still happening?

**Comment by pavlism** [comment]
No the other issue was about new files that were created not being picked up, and some random error showing up randomly.  I figured it was either just me, or lots of people would be seeing the problem.

This issue, I think has more to do changes in current files not being noticed.  I'm been working with Meteor for a year or so now, but i'm not really sure how the hot code push works (although I can guess), so I think what's happening is that while it pushing the code, the mechanism that watches for changes in files is either turned off or interfered with.

This one I can reproduce on different machines, and with a brand new meteor project.  Although with a the new project it was much better at picking up the changes.  That makes some sense, more files mean more files to watch for changes.  This should work on any larger project.  I will post a git if you need one, but I'm new to git, and messed some stuff up, so it may take a little time.

**Comment by pavlism** [comment]
https://github.com/pavlism/meteor-bug

**Comment by tab00** [comment]
I have also encountered this numerous times (on Windows 10) and still do (e.g. yesterday and today). i.e. changes made to code that are saved are sometimes not automatically detected. I then need to completely terminate meteor and restart, which is annoying.

Is this problem being solved at all?

**Comment by hwillson** [comment]
There have been several changes made to the way file watchers work in recent versions of Meteor. Please try with a modern version of Meteor (1.5.2 as of today), and post back if you're still having issues. Closing for now - thanks!
