### ISSUE TITLE
Dead link to Spacebars page

### ISSUE THREAD

**Issue by ScottBrenner** [meteor/meteor#8167]
https://www.meteor.com/tutorials/blaze/templates under the **Adding logic and data to templates** header - the link embedded in "Meteor's Spacebars compiler" is dead (points to https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md).

**Comment by abernix** [comment]
Issue moved to [meteor/tutorials #96](https://github.com/meteor/tutorials/issues/96) via [**ZenHub**](https://www.zenhub.com/)

**Comment by abernix** [comment]
Thanks for reporting this.  I've moved this over to [meteor/tutorials](https://github.com/meteor/tutorials) (which is its own repository) and opened up a PR to fix it with that repo. :smile:
