### ISSUE TITLE
readFilesync of undefined when building Meteor docker image on Jenkins 

### ISSUE THREAD

**Issue by fudgecakes** [meteor/meteor#8171]
Meteor version we're using: 1.4.1.3
Docker Version: 1.6.0
Jenkins Version: 2.19.3
Open Shift Version 3.2

When building our docker image on Jenkins, most of our builds we get the following error.

[91minfo�[0m�[91m �[0m�[91merror reading version TypeError: Cannot read property 'readFileSync' of undefined
�[0m�[91minfo error reading version at /root/.meteor/packages/meteor-tool/.1.4.1_3.8dq62w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:42:24
�[0m�[91minfo error reading version�[0m�[91m at Object. (/root/.meteor/packages/meteor-tool/.1.4.1_3.8dq62w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:475:3)

However building our docker image directly on Open Shift works.

**Comment by abernix** [comment]
This is too vague to accurately provide you help.  Does this happen on a blank project?  Does this happen on the latest 1.4.2.3?  Is there more to the stack trace?

Please provide steps to reproduce from a blank project.

**Comment by hwillson** [comment]
Hi @fudgecakes - we haven't heard back from you regarding the additionally requested details in https://github.com/meteor/meteor/issues/8171#issuecomment-268207298. Without these details this type of issue is very difficult to debug. I'll close this issue for now, but will gladly re-open if you're able to provide more specific details on how to reproduce this issue. Thanks for reporting this originally!
