### ISSUE TITLE
Unchanged files are being reloaded by the app cache in some browsers

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#818]
In concept what's supposed to happen when a file is changed (hot code reload) is that the browser will:
- Fetch the app manifest.
- See that the app manifest has changed.
- Retrieve files listed in the manifest.
- Retrieving files follows the standard web request rules: in particular, the browser shouldn't request the file again if the file is already in its file cache and the caching header had enabled caching.

The result is only the changed file(s) are requested from the server: the changed files have a different URL (from the hash), and so are fetched (not being in the file cache); while the unchanged files have the same URL as before, are cached in the file cache, and so don't need to be fetched from the server.

This is working in Firefox but not in Chrome and iOS Safari (the three browsers I've tested so far).  In Chrome and iOS Safari the browser is re-fetching all the files in the app cache after a code change.

This is easy to see server side by adding logging to the server:

```
diff --git a/app/server/server.js b/app/server/server.js
index 8923ff2..ddd23b9 100644
--- a/app/server/server.js
+++ b/app/server/server.js
@@ -176,6 +176,7 @@ var run = function () {

   // webserver
   var app = connect.createServer();
+  app.use(connect.logger('tiny'));
   var static_cacheable_path = path.join(bundle_dir, 'static_cacheable');
   if (fs.existsSync(static_cacheable_path))
     // cacheable files are files that should never change. Typically
```

**Comment by glasser** [comment]
Curious (like with many of the appcache bugs) if thiis is still happening.

**Comment by abernix** [comment]
Closing this as AppCache has been [deprecated from the web standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and is being removed from browsers.

Service Workers are supposed to be the replacement and is being tracked in #5982.
