### ISSUE TITLE
Data not synchronize

### ISSUE THREAD

**Issue by GuofuHuang** [meteor/meteor#8180]
I find out that when Meteor connect to a remote MongoDB database, the reactive data in helpers() won't synchronize as it should be, is that correct?

Is there an easy way to synchronize them?

**Comment by laosb** [comment]
This is not a bug report. Please include more information for us to investigate, eg. The code your app connects to remote MongoDB instance with, your helper code and better, a minimal repro.

Anyway, reactivity should be there out of box.

**Comment by abernix** [comment]
Closing for the above reason.
