### ISSUE TITLE
installation fails with node v7 with an old fibers@0.6.9 package

### ISSUE THREAD

**Issue by scalpel4k** [meteor/meteor#8181]
Hi guys,

I was trying to install meteor but it wasn't successful. The build fails when it tries to compile fibers@0.6.9

> fibers@0.6.9 install /usr/local/lib/node_modules/meteor/node_modules/fibers
> node ./build.js

I don't know what subpackage pulls in this very old version ....

bye Michi

**Comment by abernix** [comment]
You should not be running your Meteor bundle with Node v7.  Currently Meteor 1.4 supports all Node 4 LTS releases.

Please read the [custom deployment](https://guide.meteor.com/deployment.html#custom-deployment) section of the Meteor Guide and use the appropriate version for the Meteor that you are using.  This is also specified in the `README` for the bundle and you can also find the ideal version of Node for your bundle in the `.node_version.txt` in the root of your bundle.

To follow the progress on Node 6 support, please see #6923.
