### ISSUE TITLE
cursor de-dup confused by `undefined`

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#819]
```
Foo.find({x: undefined}).observeChanges({});
Foo.find({}).observeChanges({});
```

You're not really supposed to use `undefined` in Mongo queries but it's easy to do so by accident. Since cursor de-dup uses JSON.stringify to calculate its cache keys, it will consider these to be the same query. But it's likely that the first matches a subset of what the latter does.

We need to either filter `undefined` values out of (server-side) queries very early (to make `{x: undefined}` equivalent to `{}`) or use a different function to create cache keys.

This caused the confusing user issue reported at https://groups.google.com/group/meteor-talk/browse_thread/thread/a178b9a223aa7b2d

**Comment by hwillson** [comment]
There is a more recent discussion about this in #5097, so closing here. Thanks!
