### ISSUE TITLE
accounts-twitter: incorrect URL for Configure Twitter Login (loginButtons)

### ISSUE THREAD

**Issue by ScottBrenner** [meteor/meteor#8190]
After adding `accounts-twitter`, the **Configure Twitter Login** button on the `loginButtons` dropdrown instructs 

> Visit https://dev.twitter.com/apps/new

This URL does not exist, it should be https://apps.twitter.com/app/new.

**Comment by abernix** [comment]
@ScottBrenner Looks like they changed it at some point.  This should be an easy [pull request](https://github.com/meteor/meteor/blob/devel/Contributing.md#submitting-pull-requests), do you mind submitting one and referencing this issue number?

**Comment by ScottBrenner** [comment]
I've just opened this pull request - #8199

**Comment by abernix** [comment]
Thanks for submitting the PR and reporting this issue, @ScottBrenner.  #8199 was merged. :smile:
