### ISSUE TITLE
Add datestamps to history.md

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8193]
Could we add datestamps to new releases in the history.md of this repo?
It doesn't improve Meteor build performance 😛 , but is still useful info..

**Comment by klaussner** [comment]
You can find the release date of each version (including betas and release candidates) here: https://github.com/meteor/meteor/releases.

**Comment by avalanche1** [comment]
Yep, but usually I look at history.md

**Comment by hwillson** [comment]
I've submitted PR #8193 to help with this. Just a quick FYI/reminder - the easiest way to get a full release version list with dates is to run `meteor show METEOR`.

**Comment by stubailo** [comment]
@hwillson your link links back to this issue, instead of the PR

**Comment by hwillson** [comment]
PR #8316 has been merged - closing - thanks for reporting this originally!

**Comment by avalanche1** [comment]
Please note that 1.4.3 once again has no date

**Comment by abernix** [comment]
@avalanche1 That's because Meteor 1.4.3 hasn't been released yet.
