### ISSUE TITLE
Method callback latency variability & spikes

### ISSUE THREAD

**Issue by ppotoplyak** [meteor/meteor#8194]
This is related to #7868 but with scope narrowed to callback latency.

With a server in the EC2 cloud and a Safari/iOS iPhone 5 client on an AT&T cellular link, I am seeing method invocations that occur on a regularly programmed interval.  i.e. the cellular TX side appears reliable.  However, I am seeing unacceptable variability in the client callback latency,  14 to 40 seconds at high times.

I am trying to understand in what layer the latency is introduced? i.e. is this a link issue, Meteor issue, or both.

A minimal repro is [here](https://github.com/ppotoplyak/meteor-issue-7868).  Do a ```meteor run```, open a client and watch the server console for latency info on outstanding callbacks.

Example log:
```
/pit/meteor-issue-7868$ cat .logs/nohup.out.26.dec | grep "not acked via callback for 14 secs" | head 
I20161226-21:39:15.635(-6)? WARNING: call 5842 not acked via callback for 14 secs
I20161226-21:39:15.694(-6)? WARNING: call 5842 not acked via callback for 14 secs
I20161226-21:39:15.695(-6)? WARNING: call 5843 not acked via callback for 14 secs
I20161226-21:39:15.707(-6)? WARNING: call 5842 not acked via callback for 14 secs
I20161226-21:39:15.707(-6)? WARNING: call 5843 not acked via callback for 14 secs
I20161226-21:39:15.734(-6)? WARNING: call 5842 not acked via callback for 14 secs
I20161226-21:39:15.734(-6)? WARNING: call 5843 not acked via callback for 14 secs
I20161226-21:39:15.784(-6)? WARNING: call 5842 not acked via callback for 14 secs
I20161226-21:39:15.784(-6)? WARNING: call 5843 not acked via callback for 14 secs
I20161226-21:39:15.797(-6)? WARNING: call 5842 not acked via callback for 14 secs
```

System info:
```
ubuntu@geo:/pit/meteor-issue-7868$ meteor --version
Meteor 1.4.2.3
ubuntu@geo:/pit/meteor-issue-7868$ meteor list
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.6.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
jquery                 1.11.10  Manipulate the DOM using CSS selectors
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.14  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.1  Dependency tracker to allow reactive callbacks
```

**Comment by mitar** [comment]
One thing to try, maybe disable buffering on the client side by running `Meteor.connection._bufferedWritesInterval = 0;` Not sure if it should help, but maybe you find some differences.

**Comment by hwillson** [comment]
@ppotoplyak Are you still seeing this issue with a recent version of Meteor? I've tried your repro with 1.5.2 and haven't seen any `not acked via callback for X secs` messages. I've only let the repro run for about 1000 calls though - should I keep it running longer or were you seeing latency issues with your repro fairly quickly?

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8194#issuecomment-327831673, I'm not seeing this happen with Meteor 1.5.2. I'll close this for now, but let me know if you still notice this problem. Thanks!
