### ISSUE TITLE
Uncouple Cordova from Meteor releases

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#8195]
This is a split of #8155 (which I'm doing to avoid it getting lost) and was discussed in [this forum post](https://forums.meteor.com/t/how-to-update-cordova-to-the-latest-6-4-0-in-meteor/31809/2) about updating Cordova to 6.4.0.

To quote the most relevant part of that forum post by Martijn:

> I think the main issue holding that back is that `cordova-lib` is currently [included in the dev bundle](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/scripts/dev-bundle-tool-package.js#L57) and is relied on by CLI code in [`commands.js`](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/tools/cli/commands.js) and [`commands-cordova.js`](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/tools/cli/commands-cordova.js). So you probably want to add checks to see whether `cordova-lib` has been installed and show installation instructions if it hasn't.
>
> You may also want to have a look at [the CordovaProject class](https://github.com/meteor/meteor/blob/devel/tools/cordova/project.js) and the [platform/plugin pinning we currently do](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/tools/cordova/project.js#L53-L77).

If anyone wants to help tackle this, please discuss here!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Uncouple%20Cordova%20from%20Meteor%20releases&body=Migrated%20from:%20meteor/meteor%238195) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
