### ISSUE TITLE
Mobile app point to a different server?

### ISSUE THREAD

**Issue by GuofuHuang** [meteor/meteor#8198]
I just got a question about this command:
meteor run ios-device --mobile-server [hostname]

Is it possible that hosting the meteor app in a different server not Galaxy Meteor and point the meteor mobile app to that server?

**Comment by wojtkowiak** [comment]
Yes, that is what the `--mobile-server` is for - to point the mobile app to a certain server address. It can be any address you want so you can host the meteor server yourself.
Please note that stackoverflow or forums.meteor.com are the right place to ask such questions, not here 🙂

**Comment by GuofuHuang** [comment]
Thanks!
