### ISSUE TITLE
way to publish a transformed version of a cursor

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#821]
I was experimenting around with published data to help me with another issue #820 

I have the following in my publish function

``` javascript
Meteor.users._transform = function(doc) {
    if(doc.services.facebook) {
                console.log("transforming");
        delete doc.services.facebook['accessToken']
    }
    return doc;
}
```

So the publish data doesn't seem to account transform (with both _transform and using the method defined in the docs), It does get called I can see it logging "transforming" so if this is intentional in some way there is a wasteful process occurring somewhere

I think I get why it does this, 'transform` might be used more for adding stuff like functionality which may need the same transform function to be passed down to the client so its passed as vanilla

I know the code is ok, because it does work on the client but I don't want the access token to reach the client.

Also is there a better pattern than the above, other methods do use the accessToken but setting transform this way makes it global

**Comment by dandv** [comment]
@glasser: now that GitHub is used to track feature requests, how can this one be revived?

SO questions requesting this: [1](https://stackoverflow.com/questions/18093560/meteor-collection-transform-is-it-done-on-the-server-or-on-the-client-or-it-de), [2](https://stackoverflow.com/a/20895913/1269037), [3](https://stackoverflow.com/questions/18343534/how-to-publish-a-view-transform-of-a-collection-in-meteor), [4](https://stackoverflow.com/questions/28388472/transforming-on-excluded-field-in-meteor-mongo-collection).

**Comment by mitar** [comment]
Hm, I created a nice pluggable API for this in [meteor-middleware](https://github.com/peerlibrary/meteor-middleware). So instead of just providing a transform, you can stack them one on another. This allows for code reuse, permissions checks (like removing or aggregating fields based on permissions), etc.

**Comment by mitar** [comment]
BTW, I have my own stack for all of this: [schemas](https://github.com/peerlibrary/meteor-peerdb), [migrations](https://github.com/peerlibrary/meteor-peerdb-migrations), [joins](https://github.com/peerlibrary/meteor-related), [transforms](https://github.com/peerlibrary/meteor-middleware). :-) I think Meteor already provides enough stuff, except for two things:
* way to officially re-register the same collection
* way to have observe/observeChanges without initial set of documents being processed

**Comment by hitchcott** [comment]
@mitar,

For "way to have observe/observeChanges without initial set of documents being processed", does the `_suppress_initial: true` option solve your problem?

**Comment by mitar** [comment]
`_suppress_initial` is only for MiniMongo, not for MongoDB on the server.

**Comment by glasser** [comment]
Sure, I'll reopen (though it's great to see the community packages that help towards this).

There's some trickiness here --- observeChanges is carefully designed to map directly on to DDP, and putting an extra transform layer in the middle means you need to have more levels of caching or re-querying (not that Meteor doesn't have many of them already).

**Comment by hwillson** [comment]
Hi all - as mentioned in https://github.com/meteor/meteor/issues/821#issuecomment-73390379, Meteor already provides the necessary hooks to implement most of this (with a few small exceptions). Given that there are community packages available to help with this, and that there hasn't been any traction on this issue in over 2 years, I'll close it off as part of the on-going old issue cleanup process. If anyone disagrees with this decision, and would like to see the  specific parts of this issue implemented  that are missing (as mentioned in https://github.com/meteor/meteor/issues/821#issuecomment-73390453), please consider opening a new issue to track those requirements specifically. Thanks!

**Comment by mitar** [comment]
For "way to have observe/observeChanges without initial set of documents being processed" there is already #3694.

For re-registering collections I do not remember if there is anything.
