### ISSUE TITLE
Student pricing for Galaxy deployment?

### ISSUE THREAD

**Issue by rohan** [meteor/meteor#8211]
I'd like to suggest that Galaxy have a special price tier for student developers (i.e., anyone with an active .edu email). Many services do this -- GitHub offers unlimited private repos to students, DigitalOcean offers credit to students for their first year of hosting -- and it would make developing with Meteor much more affordable.

I know Galaxy provides a lot more than a standard hosting service like DO, but it's hard to justify paying $29/mo as a student when DO costs about $5/mo for the same power. Could MDG provide something as part of the GitHub student pack (https://education.github.com/pack)? Their services are typically either $X in credit (DO offers a $50 credit for first-time users, which is about 10 months of service) or a year of free service (which would be about a $360 value for Galaxy).

**Comment by abernix** [comment]
Please contact [Galaxy support](https://galaxy.meteor.com/support) with your suggestion as Galaxy questions are not managed here in the (open-source) Meteor repo. :smile:
