### ISSUE TITLE
Serve .pdf file on mobile

### ISSUE THREAD

**Issue by Testato** [meteor/meteor#8216]
https://forums.meteor.com/t/serve-pdf-file-on-mobile/32793

**Comment by abernix** [comment]
This is not sufficient to open an issue with, especially when you have not specified if you've exhausted all your options.  Additionally, with that being said, this is not a limitation of Meteor and there's likely nothing Meteor can do to fix it.  If anything, it's a limitation of Cordova, which Meteor uses for Mobile applications.

You should consult the resources provided to you in the forums and continue the conversation there.  It does sound like it would work if you did it properly, but might not just work out of the box:

* https://stackoverflow.com/questions/17520348/open-pdf-in-the-phonegap-app-that-is-made-in-html-and-css
* https://stackoverflow.com/questions/26304729/not-able-to-launch-a-pdf-file-in-inappbrowser-in-android

**Comment by Testato** [comment]
I tested all options with negative results.
It is confirmed also by another user on the forum topic.
May you re-open this issue ?

Probably it is only a permission bug, but setting permission on mobile-config.js do not solve the problem.
Maybe it is not a Meteor bug, but it is a Meteor user problem :-)

**Comment by abernix** [comment]
I think if you take this issue up with [Apache Cordova](https://cordova.apache.org/), there _might_ be a solution to it, but again it is not a limitation provided in any way or preventable by Meteor.

Additionally, if you're trying to serve a local PDF in this way, you're probably also running into a limitation put in place intentionally to prevent serving contents of the local file system in the web browser – as this could be a security risk.

Please continue further discussion about this on the forum post.  Thanks!
