### ISSUE TITLE
accounts-base: enroll tokens deleted too soon

### ISSUE THREAD

**Issue by zarvox** [meteor/meteor#8218]
(expanded from https://github.com/meteor/meteor/issues/7794#issuecomment-270253106 and filed as a new issue)

#7817 was intended to allow separate timeouts for enrollment tokens and password reset tokens, so enrollment tokens could last for (by default) 30 days, whereas password reset tokens could be made to expire more quickly (default 3 days).

That pull request appears to have a bug which causes enrollment tokens to be cleaned up under the reset token expiry rules. The net effect is that under the default settings, **enrollment tokens are destroyed after 3 days, rather than after 30 days**.  Regardless of what a developer sets `passwordEnrollTokenExpirationInDays` to in `Accounts.config()`, enrollment tokens will be removed from mongo after `passwordResetTokenExpirationInDays` days.

In particular, when processing password reset token expiry at https://github.com/meteor/meteor/pull/7817/files#diff-2ae5b6c36ab4132c1a2d0e33b5fd8443R1158 a `tokenFilter` with an `$or` specifying the appropriate token reason is passed to `expirePasswordToken`, but in https://github.com/meteor/meteor/pull/7817/files#diff-2ae5b6c36ab4132c1a2d0e33b5fd8443R1081 that `$or` clause is overwritten by the one which only looks at the when field. Perhaps the two clauses should be added to an `$and` clause instead?

Observed in Meteor 1.4.2.3 (accounts-base@1.2.14), but the bug I've identified is still in master as of this writing.

Reproduction:

* Enroll a new user with `Accounts.sendEnrollmentEmail()`
* Wait N days, with N between 3 and 30, or frob that user's enrollment token's `when` sufficiently far into the past to be between `passwordResetTokenExpirationInDays` and `passwordEnrollTokenExpirationInDays`, e.g. in `meteor mongo` shell run (with your new userId):

```
db.users.update({ _id: "p9ZJoQFecMFstfDuv"}, { $set: { "services.password.reset.when": new Date(new Date().getTime() - (4 * 24 * 60  * 60 * 1000)) }})
```

* Wait `EXPIRE_TOKENS_INTERVAL_MS` until the server runs the periodic cleanup function (or trigger it yourself from `meteor shell`; run `Accounts._expirePasswordResetTokens()`)
* Expected behavior: enrollment token is still present in user object, since enrollment tokens should be valid for 30 days
* Observed behavior: enrollment token has been deleted from user object

We're working around this by bumping the validity duration of password reset tokens, but that may not be a palatable option for everyone.

**Comment by mutdmour** [comment]
created a pull request solving this bug #8474

**Comment by vikas0121** [comment]
How can I stop this Accounts._expirePasswordResetTokens() ?
