### ISSUE TITLE
install wekan by meteor

### ISSUE THREAD

**Issue by KingLimbo** [meteor/meteor#8230]
Hello, I'm a student of China, 'I want to in the meteor the latest version of the jacket wenkan source, but when performing "meteor build. The build directory", will download a meteor-tool@1.3.5_1, then this can't afford to have been installed, it jumped 50% and then back to zero, excuse me what's the problem?

**Comment by laosb** [comment]
Hello from a student in China too!

I think it's better to discuss this on [forums](https://forums.meteor.com).

Anyway, sounds like your project is using a previous Meteor version. In China you may need set HTTP_PROXY and HTTPS_PROXY environment vars to your firewall-breaking tools to get better access to Meteor's CDN, which performs badly in China.

You can contact me at 943212310 at QQ too.

**Comment by abernix** [comment]
I believe you're talking about https://github.com/wekan/wekan, but it's not really clear.  I just cloned it (from GitHub), ran it and it worked just fine. 

If you still encounter problems, please provide better information about the problem you're encountering including reproduction steps and information about what platform you're using and the exact error message.
