### ISSUE TITLE
Refactor boilerplate-generator package to remove server dependency on Spacebars/Blaze

### ISSUE THREAD

**Issue by skirunman** [meteor/meteor#8232]
Many Meteor developers are now using React to develop their UI and are not using a jquery reliant UI package like [Blaze](https://github.com/meteor/blaze). However, it is still not possible to completely remove Blaze/Spacebars, and the resulting jquery dependency, from a Meteor project because of the spacebars server side dependency in the [boilerplate-generator](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator) core package, which I believe is the only dependency left in Meteor's set of required core packages.

There have also been many [different threads](https://forums.meteor.com/t/do-i-need-jquery-when-using-react/16393/3) on the Meteor Forum requesting how to remove jquery completely from Meteor as well as github issues https://github.com/meteor/meteor/issues/6844. Even though it is now possible, but not easy, to completely remove jquery from the client bundle, it would be better to be able to completely eliminate Blaze/Spacebars/jquery from a Meteor project.

A cursory glance at the boilerplate-generator source code shows a [dependency on spacebars](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate-generator.js#L88) as well as a [dependency on Blaze](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/boilerplate-generator.js#L34), even though that dependency does not seem to be declared in the[ package.js file](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/package.js).

I'm suggesting a refactor of the boilerplate-generator package to either:
1) make the dependencies on spacebars (and blaze) as weak dependencies 
OR 
2) completely remove these dependencies

In either case I'm assuming an alternative approach to generating the HTML would need to be provided using straight Javascript or a simpler rendering library with a much smaller footprint than Blaze/Spacebars/jquery.

**Comment by stubailo** [comment]
One unfortunate thing here is that it's hard to see if a package is included on the client or server only. For example, in this instance Blaze is only used in the server bundle, so doesn't include any extra code on the client at all. That's probably a separate issue but always seem relevant when I hear about Blaze in boilerplate generator.

**Comment by skirunman** [comment]
@stubailo Yes, I agree part of the issue is the "visibility" as people see the Blaze package listed in their `.meteor/versions` file so assume those resources are built on the client as well. In any case, it seems like it may be possible to completely remove Blaze/Spacebars/jquery from your Meteor app if you are using React, which would be ideal.

**Comment by abernix** [comment]
A feature request that might help with the "visibility" part of this is the recently opened #8073 which is currently in discussion.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Refactor%20boilerplate-generator%20package%20to%20remove%20server%20dependency%20on%20Spacebars%2FBlaze&body=Migrated%20from:%20meteor/meteor%238232) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
