### ISSUE TITLE
Change the default log in behavior to prevent logging in when there is a current user / account creation when there is a current user

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#8234]
Version: 1.4.2
Packages: Too many to count
Expected behavior: trying to login/create account when a connection already has a userId bound to it should THROW.
Repro: Create an account with Meteor Accounts, then create account again on the client.

Shouldnt this throw? it makes no sense to me that we would allow `createUser` to succeed if called from the client

**Comment by stubailo** [comment]
Why should it throw? Is there a situation where this is causing a problem in your app?

**Comment by abhiaiyer91** [comment]
I'm trying to understand the use case where a logged in user would create/login to another account replacing their current session. If Meteor is trying to stay unopinion about how this process is go, is there a way to control the login behavior in this case. Whats weird to me is that you would still allow the user to login and replace the current user.

Analytics, mixpanel for example, relies on a session/distinct id to identify users in analytics. So in the case of this, a user could login over another user and completely rewrite their analytics profile. 

What was the design decision here?

**Comment by merlinpatt** [comment]
I agree that it doesn't make sense to default allow a logged in user to log in as another user. I don't know of any app that allows for this behavior. But giving the option to override seems sensible.

The create condition, on the other hand, is a perfectly reasonable thing for some apps. It shouldn't log the user in immediately after creating, which it doesn't, but there are cases where this is useful. For instance, a teacher needing to create accounts for students.

If anything, this should be changed to "Change the default log in behavior to prevent logging in when there is a current user"

**Comment by stubailo** [comment]
I'm not taking a stand on whether this is a reasonable thing for an application to do. Does the same apply to login? I'm not sure if you can currently call something like `Accounts.loginWithPassword` while logged into a different account, but I wouldn't be surprised if that also worked.

**Comment by abhiaiyer91** [comment]
@stubailo a currently logged in user can call Meteor.loginWithPassword with another account. and the same issue I described happens.

**Comment by abhiaiyer91** [comment]
Yeah I would like to understand the design choice. There is code we will write to work around this. But i dont even think Passportjs allows this.

**Comment by leosco** [comment]
@abhiaiyer91 It's one of those flexibility-over-security situations. Meteor focuses more on the former, so you still need to be vigilant and design your app securely. If you don't want to allow a logged in user to login as a different user without logging out you can write a simple hook using [validateLoginAttempt()](http://docs.meteor.com/api/accounts-multi.html#AccountsServer-validateLoginAttempt)

Haven't tested it myself, but I imagine something like this should work?
```
Accounts.validateLoginAttempt(() => !Meteor.user());
```

**Comment by mjmasn** [comment]
Probably not a bad idea, currently on routes where we need to do something like this we log the existing user out first, so in theory would never try to log in on top of another user. As long as the breaking change is highlighted, the simple fix for anyone whose code is broken is to wrap certain route actions in a Meteor.logout callback. Having the behaviour be a bit more defined is for the better I think.

Example: We have (probably fixable) race conditions between session resume and impersonation token login. Having the error thrown would a) help us identify these areas and b) allow us to catch the error, initiate logout/check logout has now finished and retry the token login.

**Comment by mitar** [comment]
I like this current behavior. Is it really so hard to logout person first if you want a different behavior? But making current behavior if by default we would logout everyone, it would be hard.

**Comment by leosco** [comment]
I agree, I really don't feel like it needs to be a standard that logging in
explicitly forces a logout. If you feel like your app would be more secure
for it, then write your own hook. NBD

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Change%20the%20default%20log%20in%20behavior%20to%20prevent%20logging%20in%20when%20there%20is%20a%20current%20user%20%2F%20account%20creation%20when%20there%20is%20a%20current%20user&body=Migrated%20from:%20meteor/meteor%238234) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
