### ISSUE TITLE
Assets referenced by url() in stylus (not less) do not load when ROOT_URL is set

### ISSUE THREAD

**Issue by evren217** [meteor/meteor#8238]
This issue only occurs with stylus, but not less. ROOT_URL is set to `http://localhost:3000/viewer/`, but Meteor tries to load the following background image set in the stylus by the url `http://localhost:3000/packages/design/assets/theme-icons.png` instead of `http://localhost:3000/viewer/packages/design/assets/theme-icons.png`

```
background: url('/packages/design/assets/theme-icons.png')
```

Meteor Version: 1.4.2.3

**Comment by hwillson** [comment]
Hi @evren217 - sorry for the delay in responding to this; any chance you could put together a small, runnable reproduction demonstrating this issue? Providing a runnable repro will definitely help with troubleshooting (for more info see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by hwillson** [comment]
Since we haven't heard back about a runnable reproduction demonstrating this issue, I'll close this issue for now. Happy to re-open if this problem is still happening, and you're able to provide a repro. Thanks!
