### ISSUE TITLE
Feature request: force-ssl needs a rework

### ISSUE THREAD

**Issue by leosco** [meteor/meteor#8245]
"To simplify development, unencrypted connections from localhost are always accepted over HTTP." - from the [force-ssl](https://atmospherejs.com/meteor/force-ssl) docs page.

I'm not sure why this was decided, but isn't it inconvenient that you can't know if your SSL is configured properly until you build the project for production? I have an SSL proxy set up to operate within the bundled web-server that Meteor runs, using [http-proxy](https://github.com/nodejitsu/node-http-proxy) and I have the force-ssl package installed, but I have no way of knowing if it actually works because in development, apparently it will allow insecure connections from `http://localhost:3000` even if `ROOT_URL = https://localhost` . Before I deploy the project to my server, I need to make sure that WSS is being used, and that insecure connections to the app are redirected to HTTPS or at least blocked.

Are there any tricks or workarounds to confidently test whether or not the app is properly set up for HTTPS in development? What are the best practices for this in Meteor (since documentation is a little sparse on it)?

Edit: did some debugging and I can confirm that WSS works, when accessing the app on HTTPS. I still think that `force-ssl` should actually force the app to use SSL, regardless of whether you're in production or not...

**Comment by hwillson** [comment]
@leosco - It sounds like you've found a workaround for this, but I'll post the workaround I usually use, since it might help. 

1) First create a publicly accessible http/https endpoint using [ngrok](https://ngrok.com), that tunnels back locally to localhost:3000:

```
ngrok http 3000
```

This gives me back forwarding addresses that look like:

```
http://cc09e6a0.ngrok.io -> localhost:3000        
https://cc09e6a0.ngrok.io -> localhost:300 
```

2) Set the assigned ngrok host as the Meteor `ROOT_URL`, and start the local Meteor app in `--production` mode (using production mode here makes sure the `force-ssl` package is triggered):

```
ROOT_URL=https://cc09e6a0.ngrok.io meteor --production
```

3) If you access `http://cc09e6a0.ngrok.io`, you'll be properly redirected to `https://cc09e6a0.ngrok.io`, and can continue with your SSL based testing.

**Comment by abernix** [comment]
If SSL was *forced* in development it would require a SSL certificate for `localhost` to prevent browser security warnings and might actually give many people the feeling that their project was broken or insecure.  Using a redirector service like the above suggestion is a very reasonable way to test.

I'd say that @hwillson's information might be worth demonstrating in the guide in a "Testing SSL in development", but since using `force-ssl` isn't really the recommended way of ensuring SSL in production environments anymore either (https://github.com/meteor/meteor/commit/fe1f167eea5e1201f5d6a3303df4c416d0da7819) so I'm not sure that's really helpful either.

**Comment by leosco** [comment]
@abernix you can just self-sign a certificate for your development use, it's not that hard. Chrome dev tools (and other browsers, I'm sure) has a security tab
![security tab](https://cloud.githubusercontent.com/assets/11724770/23180397/4f13578a-f83f-11e6-9e57-b6e13602d504.png)
where you can follow your SSL pipeline and make sure that your encryption is strong, all your page resources are secure, etc.

Either way, this isn't a big deal, but I think the documentation should reflect that you need to implement a redirect in production. It's considered bad practice to run node instances on port 80, so I run it on port 3000 and use this command:
```
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
```
in the upstart job. So `iptables` will redirect requests to 80 to 3000 and vice versa, and [http-proxy](https://www.npmjs.com/package/http-proxy) will handle all traffic from 80 to 443, using the certificate you specify. And it supports websockets :) 

Having said all of this, I don't really understand what `force-ssl` actually _does_. In my case it doesn't seem to do anything, since I had to do all that setup myself ¯\_(ツ)_/¯

**Comment by leosco** [comment]
@abernix I read your changes to the `force-ssl` docs at https://github.com/meteor/meteor/commit/fe1f167eea5e1201f5d6a3303df4c416d0da7819
My impression is that the package, in it's current state, will be useful to a very small user-base, if any at all. The package could instead be a simple [http-proxy](https://www.npmjs.com/package/http-proxy) implementation like so:
```
import fs from 'fs';
import httpProxy from 'http-proxy';
import appRoot from 'app-root-path';

function setupSSL() {
    const host = 'localhost';
    const port = 3000;

    const target = {
        host,
        port,
    };

    const sshPath = `${appRoot}/ssl/`; // or whatever (could make it an environment var)

    const proxySettings = {
        ssl: {
            key: fs.readFileSync(`${sshPath}server.key`, 'utf-8'),
            cert: fs.readFileSync(`${sshPath}server.crt`, 'utf-8'),
        },
        target,
        // we set secure to false because we're using self-signed certificates
        secure: false,
        ws: true,
        xfwd: true,
    };

    httpProxy.createProxyServer(proxySettings).listen(443);
}

export default { setupSSL };
```

This _does not_ redirect `localhost:3000` to `https://localhost`, however. That would need to be implemented separately.

**Comment by abernix** [comment]
I agree that the `force-ssl` package will be useful for a very small percentage of users, I'm aware that you can self-sign a certificate (easy, but not easy enough) and I'm aware that you shouldn't shouldn't bind your production `node` deployment to port 80.

But this is still not the recommended way of forcing SSL, which should be done at the proxy level where your SSL is terminated (which should not be done by Meteor).  By changing `force-ssl` to implement an SSL proxy, we would be saying that it was recommended to forego that proxy, which we do not recommend.

While it would be possible to create the package you're suggesting, it would be better as a community package, so long as it came with the correct disclaimers.

I *do* think it would be great pull-request if you opened something to the [Custom deployment](https://guide.meteor.com/deployment.html#ssl) docs, stating that not only is it recommended to use SSL, but to force SSL and to reiterate similar statements as were made in the [commit you referenced](https://github.com/meteor/meteor/commit/fe1f167eea5e1201f5d6a3303df4c416d0da7819).  Please do open an issue with `docs` about this, and preferably a PR! 😄
