### ISSUE TITLE
SVG served with text/html mime type

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#8246]
We are running the latest version of meteor and have a bunch of SVG files in our public folder. All of them work fine except one, which works fine on the local environment. There is nothing special per se about the one that is being served with incorrect mime type of `text/html`.

To have a look at the problem, head on over to http://bumpin.com/how-it-works

The second svg for "Create A Campaign" doesn't work.

**Comment by ramezrafla** [comment]
You have two slashes in this SVG path breaking the router -- the output of that URL is therefore HTML text from Meteor this is why you are getting the text/html type

**Comment by hwillson** [comment]
Thanks @ramezrafla, you nailed it. Closing this off - thanks!

**Comment by talha-asad** [comment]
Thanks, @ramezrafla don't know how I missed that.
