### ISSUE TITLE
[accounts-base]: Allow URL of resetPassword, verifyEmail and enrollAccount in email to be properly customized

### ISSUE THREAD

**Issue by lightningboss** [meteor/meteor#8252]
It would be great if you are able to properly customize the URLs of the accounts package. Even though the [Meteor Guide](https://guide.meteor.com/accounts.html#email-flows) shows you how to change the URL, it also explicitly says that the event methods won't work anymore if you do so.

The reason it doesn't work right now is because the URLs are hard-coded in the `accounts-base` package.

I would suggest to add a method that allows you to change the route (without breaking backwards-compatability). For me it seems like it's creating a variable and switching out the hard-coded strings with the proper variables.

**Comment by stubailo** [comment]
One problem, as I remember it from before, is that the callbacks that rely on those URLs rely on the URL checking code running before the package is initialized. So you wouldn't be able to change the URL from your application code before the package uses those values.

So this requires a bit of restructuring of the code there to not read the URL until the app has had a chance to set it.

**Comment by lightningboss** [comment]
Wouldn't that mean that if we ran the code for the URL in a `Meteor.startup`-block would solve the issue? Or are packages initialised before this code is run?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Baccounts-base%5D%3A%20Allow%20URL%20of%20resetPassword%2C%20verifyEmail%20and%20enrollAccount%20in%20email%20to%20be%20properly%20customized&body=Migrated%20from:%20meteor/meteor%238252) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
