### ISSUE TITLE
cordova-plugins file does not allow multiple @ signs on a single line (e.g., for private repo).

### ISSUE THREAD

**Issue by observaInc** [meteor/meteor#8256]
Using Meteor 1.4,1,3.

I would like to be able to use a cordova plugin from a private github repo that requires a username/password.

Using the command:
```
meteor add cordova:sample-package@https://<access-key>@github.com/company/sample-package.git#<sha1>
```

The issue is that this command will put the following line in the .meteor/cordova-plugins file:
```
sample-package@https://<access-key>
```
It loses the git file and the SHA-1.  It should look like this:
```
sample-package@https://<access-key>@github.com/company/sample-package.git#<sha1>
```
Even if the <b>meteor add</b> command worked as expected, the parsing of the cordova-plugins file fails because it now has 2 @ signs on a single line, and will respond with the following error when trying to build.

```
Cordova plugin must specify version:
```

2 step hacky Workaround:
1. After adding the package, I manually go into the cordova-plugins file and change it to contain the full path with access-key and sha1, which puts 2 @ signs on a single line.
2. Alter source code in project-context.js around line 1145 in the meteor tools directory, as follows:

```javascript
      // We just do a standard split here, not utils.parsePackageConstraint,
      // since cordova plugins don't necessary obey the same naming conventions
      // as Meteor packages.
      var parts = line.split('@');
      if (parts.length !== 2) {
        buildmessage.error("Cordova plugin must specify version: " + line, {
```

to this (wrongly indented code is what is added):
```javascript
      // We just do a standard split here, not utils.parsePackageConstraint,
      // since cordova plugins don't necessary obey the same naming conventions
      // as Meteor packages.
      var parts = line.split('@');
          if (parts.length > 2) {
              parts = [parts[0],  parts.slice(1).join('@') ];
          }
      if (parts.length !== 2) {
        buildmessage.error("Cordova plugin must specify version: " + line, {
```

Pretty much all this is doing is if there is more than 1 @ sign found during the split command, then rejoin anything back into a single string following that first @ sign.

I'm not super familiar with the inner workings of meteor and not sure if this bug fix would affect other callers of this method, and don't know how to alter the <b>meteor add</b> command to add private repos correctly.

**Comment by hwillson** [comment]
This was fixed (and merged) in https://github.com/meteor/meteor/pull/9334. Thanks!
