### ISSUE TITLE
Meteor 1.4.2.3 "Error: Cannot find module '../core-js/object/assign'" when using local package

### ISSUE THREAD

**Issue by ejfrancis** [meteor/meteor#8257]
### The Problem

I'm seeing  an error when I'm using a local package. It happens if I use the package via `METEOR_PACKAGE_DIRS` as well as when it's placed inside the `packages/` dir.  The error I'm getting is `Error: Cannot find module '../core-js/object/assign'` . If I remove the local package and don't set `METEOR_PACKAGE_DIRS` builds work fine.

I'm using `METEOR_PACKAGE_DIRS=../parent/`, the directory structure is like this
```
|_parent/                                       <-- METEOR_PACKAGE_DIRS is set to here
   |_<package name>/ 
      |_package.js                              <-- local package
      |_demo/                            
         |_demo meteor app                      <-- demo app that uses local package
```

Using the structure above, `METEOR_PACKAGE_DIRS` is set to "parent", so that the "demo meteor app" in `parent/<package name>/demo/` can live within the package's repo but access the local package from its parent directory at build time.

I've tried not using `METEOR_PACKAGE_DIRS` and just placing the package inside `demo/packages/<package name>` so the demo app can find the package in the `packages/` dir and still see the error.

### Reproduce
To reproduce you can pull down my repo https://github.com/ejfrancis/prosemirror/ at commit df9790547c92fac22ef74c1c74201ee94f781295 (which is on the "test/basic-collab" branch) and running `cd demo && meteor npm install && cd ../ && meteor npm run test`. It will attempt to run two servers inside the demo app in `demo/` on different ports but never gets past the first one running. It will run something like this:

```
METEOR_PACKAGE_DIRS=/Users/efrancis/projects/ NODE_ENV=test  meteor --port 3005
```

----- 

### Error Output 

```
W20170113-17:59:46.941(-8)? (STDERR) Error: Cannot find module '../core-js/object/assign'

W20170113-17:59:46.941(-8)? (STDERR)     at require (packages/modules-runtime.js:109:19)

W20170113-17:59:46.942(-8)? (STDERR)     at meteorInstall.node_modules.meteor.prosemeteor:prosemirror.node_modules.babel-runtime.helpers.extends.js (/Users/efrancis/projects/prosemirror/demo/.meteor/local/build/programs/server/packages/prosemeteor_prosemirror.js:2510:15)

W20170113-17:59:46.942(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)

W20170113-17:59:46.942(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)

W20170113-17:59:46.942(-8)? (STDERR)     at Module.Mp.import (/Users/efrancis/.meteor/packages/modules/.0.7.7.yjn28g++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)

W20170113-17:59:46.942(-8)? (STDERR)     at meteorInstall.node_modules.meteor.prosemeteor:prosemirror.lib.imports.api.documents.both.methods.js (/Users/efrancis/projects/prosemirror/demo/.meteor/local/build/programs/server/packages/prosemeteor_prosemirror.js:2170:207)

W20170113-17:59:46.942(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)

W20170113-17:59:46.942(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)

W20170113-17:59:46.942(-8)? (STDERR)     at Module.Mp.import (/Users/efrancis/.meteor/packages/modules/.0.7.7.yjn28g++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)

W20170113-17:59:46.942(-8)? (STDERR)     at meteorInstall.node_modules.meteor.prosemeteor:prosemirror.lib.imports.api.authority.server.authority.js (/Users/efrancis/projects/prosemirror/demo/.meteor/local/build/programs/server/packages/prosemeteor_prosemirror.js:1424:829)
```

So `node_modules/babel-runtime/helpers/extends.js` is trying to import  `node_modules/babel-runtime/core-js/object/assign`, this fails even though the file is there. This is the contents of `node_modules/babel-runtime/core-js/object`

```
-rw-r--r--  1 efrancis    94 Jul 26 15:09 assign.js
-rw-r--r--  1 efrancis    94 Jul 26 15:09 create.js
-rw-r--r--  1 efrancis   105 Jul 26 15:09 define-properties.js
-rw-r--r--  1 efrancis   103 Jul 26 15:09 define-property.js
-rw-r--r--  1 efrancis    95 Jul 26 15:09 entries.js
-rw-r--r--  1 efrancis    94 Jul 26 15:09 freeze.js
-rw-r--r--  1 efrancis   115 Jul 26 15:09 get-own-property-descriptor.js
-rw-r--r--  1 efrancis   116 Jul 26 15:09 get-own-property-descriptors.js
-rw-r--r--  1 efrancis   110 Jul 26 15:09 get-own-property-names.js
-rw-r--r--  1 efrancis   112 Jul 26 15:09 get-own-property-symbols.js
-rw-r--r--  1 efrancis   104 Jul 26 15:09 get-prototype-of.js
-rw-r--r--  1 efrancis   101 Jul 26 15:09 is-extensible.js
-rw-r--r--  1 efrancis    97 Jul 26 15:09 is-frozen.js
-rw-r--r--  1 efrancis    97 Jul 26 15:09 is-sealed.js
-rw-r--r--  1 efrancis    90 Jul 26 15:09 is.js
-rw-r--r--  1 efrancis    92 Jul 26 15:09 keys.js
-rw-r--r--  1 efrancis   106 Jul 26 15:09 prevent-extensions.js
-rw-r--r--  1 efrancis    92 Jul 26 15:09 seal.js
-rw-r--r--  1 efrancis   104 Jul 26 15:09 set-prototype-of.js
-rw-r--r--  1 efrancis    94 Jul 26 15:09 values.js
```

-------
### System Info
`meteor --version` output: 1.4.2.3
`meteor list` output:
```
accounts-base                       1.2.14  A user account system
blaze-html-templates                1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
dburles:mongo-collection-instances  0.3.5  Access your Mongo instances
ecmascript                          0.6.1  Compiler plugin that supports ES2015+ in all .js files
es5-shim                            4.6.15  Shims and polyfills to improve ECMAScript 5 support
jquery                              1.11.10  Manipulate the DOM using CSS selectors
meteor-base                         1.0.4  Packages that every Meteor app needs
mobile-experience                   1.0.4  Packages for a great mobile user experience
mongo                               1.1.14  Adaptor for using MongoDB and Minimongo over DDP
prosemeteor:prosemirror             0.1.1+ Prosemirror integration for Meteor
reactive-var                        1.0.11  Reactive variable
shell-server                        0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css               1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js                1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                             1.1.1  Dependency tracker to allow reactive callbacks
xolvio:backdoor                     0.2.1  Runs arbitrary code on server
```
package.json content
```
{
  "dependencies": {
    "babel-runtime": "^6.20.0"
  }
}
```

OS: OSX 10.11.6, and Ubuntu 15.04

**Comment by ejfrancis** [comment]
possibly related to #7872

**Comment by ejfrancis** [comment]
@benjamn I've seen some activity of possible fixes to bugs that look related to the build tool chain, are there any new release candidates I should try?

**Comment by abernix** [comment]
There are newer versions available: `1.4.2.6`, `1.4.3-beta.3` and `1.5-beta.3`.  You can try those, but if you'd like help with this, please provide a more simple reproduction demonstrating the problem (without a fully functioning application).

Also, I'll say it's certainly not recommended to nest a full Meteor application inside a Meteor package which is depended upon from the nested application.  This creates a very circular file tree.  If you need to have your package outside, consider having it alongside:

```
- rootDirectory
  + packages
    + package_name
      + package.js
      ` ... other package_name package files
  + app
   + .meteor/
   ` ... other app files
```

and then when you run your app, you can use `METEOR_PACKAGE_DIRS=../packages meteor`.  This is likely the cause of the problem.  Happy to reopen with a more simple reproduction, but please resolve that nested application thing as well.

**Comment by copleykj** [comment]
I've just encountered this same issue and it seems that it's coming from having a node_modules folder inside the directory of the local package. Currently I have several packages installed for linting while deving  meteor packages locally. Obviously this is only an issue with local packages that I've run meteor install on, as node_modules doesn't get into the built package. Any ideas for a work around? Kind of hard to work this way :)

**Comment by jiku** [comment]
Same happens here when linking to local NPM packages, using either `npm link` or `meteor npm link`.

**Comment by abernix** [comment]
@copleykj Open a new issue with a reproduction would be the best way to get this looked at!  This issue is quite old now (and closed).
