### ISSUE TITLE
Viewport bug on Android App ?

### ISSUE THREAD

**Issue by Testato** [meteor/meteor#8264]
https://forums.meteor.com/t/viewport-on-android-app/32827

**Comment by abernix** [comment]
Again, this isn't enough to open an issue with.  Please read [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) and make sure you've provided the information requested IN the issue when you open it (too hard to go back and forth to a forum post).  You should have provided a reproduction repo.

Also, please spend some time proving that this is actually a Meteor bug and not just a general WkWebView bug.  If it happens in Cordova, it will happen in Meteor so you should probably start by testing with that too.  Perhaps you should try posting a question on StackOverflow?
