### ISSUE TITLE
Allow multiple reset and invitation tokens

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8273]
I think it would be also great if one could have multiple reset tokens available at the same time as well. Now that we have expiration of them, we do not have to replace old one with new one. This is important for users because sometimes they request password reset multiple times and it would be great if any of those links would work. Sometimes e-mails come in a different order as well, so the last e-mail does not necessary contain the last reset link.

One more thing is also if you have invite and forget password capability. Then if one invites, and user tries to reset their password, invite e-mail gets invalidated.

**Comment by mitar** [comment]
Can this be looked at and decided if this is something pull requests are encouraged for? Then I could maybe see if I have time to do this and #8084.

**Comment by abernix** [comment]
Did you mean `#8326` instead of `#8273` in your previous comment?

**Comment by mitar** [comment]
Fixed. :-)

**Comment by abernix** [comment]
I'd suggest that we figure out the details of #8084 first and get that PR'd and merged _before_ taking a PR for this.  Obviously the implementation of #8084 should support this (and #8326) easily without a re-write though.  🙂

**Comment by mitar** [comment]
I was thinking about this a bit more and I think it could be done even before #8084, now that we have expiration of tokens based on time. I know #8084 is important, but I think this one would be a much smaller change (and something I could do), while #8084 is something I am not sure I am willing to tackle. :-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20multiple%20reset%20and%20invitation%20tokens&body=Migrated%20from:%20meteor/meteor%238273) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
