### ISSUE TITLE
Meteor Idle CPU utilization is high

### ISSUE THREAD

**Issue by 416serg** [meteor/meteor#8274]
I'm trying to set up my Meteor apps on AWS EB and I've successfully deployed 2. Weird thing is one of them is using 30% CPU when idle, as opposed to 0.3% on the other one. 

Both are running `METEOR@1.4.2.3`, both are on t2.large EC2 instances. I previously had the apps on Galaxy without any issues (have to make the switch because we got a generous amount of credits from AWS)

The only difference is the app that's idle at 30% has Meteor settings be loaded on startup and the other one doesn't use any Meteor settings since it's just used to connect to the DB and display info (as a microservice)

**Comment by abernix** [comment]
Sorry to be so blunt, but you've provided nothing to help debug your situation.

* What have you checked so far?
* Do you see the same problem with a freshly created, empty, Meteor app?
* Do you see the same problem with a freshly created Meteor app with "Meteor settings loaded on startup"?
* What are "Meteor settings"? Do you see the same problem with previous versions of Meteor?
* Have you tried debugging the Node process to see what it's doing?

**Comment by 416serg** [comment]
@abernix you're right, I apologize for not providing further information. Going from deploying with Galaxy (which is super easy and intuitive) to a custom deployment for the first time, I am not sure where to start the debugging process. 

With that said, I don't see the same problem with an app that uses the same packages but doesn't require any `Meteor settings`. I build with `meteor build --directory ../build/ --architecture os.linux.x86_64` and I add an environment variable `METEOR_SETTINGS_FILE` with value `/tmp/settings.json`, where I upload my settings file for the server. I have the following file running at startup on server

```
if (Meteor.isProduction) {
  var meteorFile = process.env.METEOR_SETTINGS_FILE;
  if(meteorFile == undefined) throw new Error(
    'METEOR_SETTINGS_FILE env variable must be defined in production.')
  var fs = Npm.require('fs');
  var pjsonBuf = fs.readFileSync( meteorFile );
  Meteor.settings = JSON.parse( pjsonBuf.toString().trim());
}
```

and on client:

```
if (Meteor.isProduction) {
  // public settings that need to be exposed to the client can be added here
  var publicEnvs = {
    // All of my client settings
  };
  Meteor.settings.public = publicEnvs;
  __meteor_runtime_config__.PUBLIC_SETTINGS = Meteor.settings.public;
}
```

I hope that helps. If you can point me in the right direction to start debugging node processes, it'd be greatly appreciated. I know Galaxy uses AWS hence I was hoping I'd find a more clear way as to the deployment procedures here.

**Comment by ramezrafla** [comment]
@416serg are you using node 4.6.2 -- please search the forum as this issue was faced by many (including myself)

**Comment by 416serg** [comment]
AWS doesn't allow node 4.6.2, switching to 4.6.1, however, did the trick, thanks! I was using Node 6+ and didn't realize.
