### ISSUE TITLE
[Documentation] Documentation fails to mention that "meteor install-sdk android" does nothing

### ISSUE THREAD

**Issue by KernelDeimos** [meteor/meteor#8280]
I realise the documentation isn't part of this repository but I want to make sure this gets some attention so that somebody doesn't get caught up in this like I did.

I assumed that the "Please follow the installation instructions in the mobile guide" message after running `meteor install-sdk android` was an error message - after all, why would a command just be there to display a message which could have been in the documentation?

I spent a lot of time trying to fix this "error" before I realised I could run `meteor add-platform android` without any issues.

I propose that this message.... should just be in the documentation. That would be much less confusing.

**Comment by abernix** [comment]
There is a the [docs repo](https://github.com/meteor/docs) where you could open an issue (or even better, a pull request!) on how to improve the docs! 🤓

But where did you get the idea to run `meteor install-sdk android` from in the first place?

The `meteor install-sdk <platform>` command did use to do something, but is now deprecated.  I realize the fact that it's deprecated could be made more clear in the command (and the help should be changed), but I don't think your argument is fair that it must be an error message – the instruction is pretty clear. 🙂

**Comment by hwillson** [comment]
I agreed with the comments in https://github.com/meteor/meteor/issues/8280#issuecomment-274709800 - the message returned is pretty clear, and points to the proper mobile environment installation prerequisites documentation. If you think anything else should be changed with regards to the documentation, please open a new issue in either the [Docs repo](https://github.com/meteor/docs) or [Guide repo](https://github.com/meteor/guide). Thanks!
