### ISSUE TITLE
Error when running ./meteor test-packages

### ISSUE THREAD

**Issue by pradel** [meteor/meteor#8282]
Hey, I am trying to run the meteor test suite before submitting a pull request but I am getting the following error when I run the tests `Error: Depending on unknown package spacebars-compiler`.

The error appear here meteor/packages/promise/.npm/package/node_modules/meteor-promise/promise_server.js:190.

Meteor devel branch.
Mac os 10.12.2.

## Step to reproduce:
- `git clone https://github.com/meteor/meteor.git`
- `cd meteor`
- `./meteor test-packages`

**Comment by hwillson** [comment]
Hi @pradel - see the [developer instructions in the README](https://github.com/meteor/meteor#slow-start-for-developers). You need to `git clone --recursive https://github.com/meteor/meteor.git`.

**Comment by pradel** [comment]
THanks @hwillson , maybe this could be linked near to this part ? https://github.com/meteor/meteor/blob/devel/Contributing.md#running-tests-on-meteor-core

**Comment by hwillson** [comment]
Thanks for the suggestion @pradel - I agree, things are a bit scattered. The good news is that this will be addressed shortly by #8267. I'll add your suggestion to that issue. Thanks again!
