### ISSUE TITLE
hot code push fail, index.html is not served from __cordova/

### ISSUE THREAD

**Issue by sirpy** [meteor/meteor#8284]
using meteor 1.4.2,
when i access http://localhost:3000/__cordova/ i get 404 result
the log from the android simulator shows that it tries to fetch "/" and results in 404 exception.

After some debugging it looks like "/" is defined as the target for "index.html" in the cordova webapp assets.
Other assests such as app.js are available at http://localhost:3000/__cordova/
looking at the build directory of cordova i see there is an index.html there but it is not served.
also index.html is not found in the manifest.json (dono if this is expected or not)

**Comment by abernix** [comment]
Thanks for filing an issue though I'll close this as the problem you're referring to is too vague to accurately provide help.  A project created with `meteor create test-app && cd test-app && meteor add-platform ios && meteor run ios` does work!

We'd be happy to look into the problem if you could provide a reproduction repository per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) instructions which demonstrates an actual problem.
