### ISSUE TITLE
Subresource Integrity (SRI) support

### ISSUE THREAD

**Issue by juho** [meteor/meteor#8286]
[Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), basically hash-checking for CDN-delivered files is slowly becoming a thing with support in Chrome and Firefox. Haven't noticed anything about this on GitHub so I'm raising an issue here to discuss what needs to be done to support it in the future. 

There's one (1) [post](https://forums.meteor.com/t/lets-make-meteor-the-most-secure-framework-ever-subresource-integrity/9211/5) about it on the forums so far so I understand it's not a huge thing yet, but it'd be nice to have on the roadmap eventually. Unless I'm missing something, I imagine the hash could be calculated rather easily when you run `meteor build` or deploy, and then injected into the script tag.

**Comment by abernix** [comment]
Meteor already does hashing internally for various purposes (cache-busting, etc.) purposes so this would probably fit in really well as I believe it's already stored in the `program.json` of the generated "star" bundle (check around bundler code [here](https://github.com/meteor/meteor/blob/devel/tools/isobuild/bundler.js#L1)).  Unfortunately, it doesn't currently use any of the SRI-supported hashes (SHA256, SHA384, SHA512) to do that (it uses SHA1).

Small speed consideration to consider there, but this might be a relatively easy PR if someone was willing to look at it.

```sh
$ openssl speed sha256 sha512
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
sha1             49444.47k   136852.67k   300421.57k   417013.13k   479489.03k
sha256           34909.98k    83895.28k   142883.64k   180203.46k   198309.35k
sha512           24882.98k   103407.50k   181249.93k   263356.03k   307869.74k
```

**Comment by laosb** [comment]
Had a look around the code - we'll need to replace `watch.sha1` with `watch.sha256`(not many in code, but many in comments) and I'm not sure if it's used somewhere else.

**Comment by mitar** [comment]
In my fork I have already been doing something similar and I have extended in the past `program.json` to simply include also `sha256` keys as well.

**Comment by macsj200** [comment]
@mitar can you include a link to your fork? I'd like to see how you implemented this.

**Comment by mitar** [comment]
Sadly it has not been open sourced. :-(

I think something like that is enough:

```patch
--- bundler.js.orig	2017-05-09 01:00:08.000000000 -0700
+++ bundler.js	2017-05-09 01:00:21.000000000 -0700
@@ -69,6 +69,7 @@
 //        before this file
 //    - size: size of file in bytes
 //    - hash: sha1 hash of the file contents
+//    - sha256: sha256 hash of the file contents
 //    - sourceMap: optional path to source map file (relative to program.json)
 //
 //    Additionally there may be a manifest entry with where equal to
@@ -300,6 +301,7 @@
 
     this._contents = options.data || null; // contents, if known, as a Buffer
     this._hash = options.hash || null; // hash, if known, as a hex string
+    this._sha256 = null; // SHA256 hash, as a hex string
   }
 
   toString() {
@@ -313,6 +315,13 @@
     return this._hash;
   }
 
+  sha256() {
+    if (! this._sha256) {
+      this._sha256 = watch.sha256(this.contents());
+    }
+    return this._sha256;
+  }
+
   // Omit encoding to get a buffer, or provide something like 'utf8'
   // to get a string
   contents(encoding) {
@@ -1295,6 +1304,7 @@
       // Set this now, in case we mutated the file's contents.
       manifestItem.size = file.size();
       manifestItem.hash = file.hash();
+      manifestItem.sha256 = file.sha256();
 
       writeFile(file, builder);
 

 ```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Subresource%20Integrity%20(SRI)%20support&body=Migrated%20from:%20meteor/meteor%238286) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
