### ISSUE TITLE
Cordova can't access video or audio files.

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#8289]
I'm trying to serve a local MP3 file within my Cordova application. Since we are not allowed to access local resources, we have to use Meteor's built in web server to access those files. This works fine with images or text document, but fails with video and audio files.

    WebAppLocalServer.localFileSystemUrl("file:///storage/emulated/0/myapp/test.mp3");
    -> http://localhost:12440/local-filesystem/storage/emulated/0/myapp/test.mp3

If I add the url within an audio tag, the file doesn't start playing. Even if I access it directly within my Cordova app (via link), I only see the audio player, but the file doesn't start playing.

The url generator is working correctly, if I try to access a local image by this:

    WebAppLocalServer.localFileSystemUrl("file:///storage/emulated/0/myapp/test.jpg");
    -> http://localhost:12440/local-filesystem/storage/emulated/0/myapp/test.jpg

I can see the picture within my Cordova application (img tag).

I've tested it on Meteor 1.4 and Android 7.

**Comment by ramezrafla** [comment]
I think we need @martijnwalraven 's input here as I recall he's the developer of the mobile web server. Maybe the server does not support media.

However, from experience with mobile storage, we typically store large files in the local filesystem directly - nothing that iOS and Android store things differently. You mentioned you can't access directly, can't a plugin do that? It's next on our dev horizon, so I may have some insight in a couple of weeks.

**Comment by wojtkowiak** [comment]
Can you debug the app if the chrome://inspect and check if the http request is being made and what is the result of it?

**Comment by dnish** [comment]
Yeah, the response was made but I only get a response length of 2 bytes.

**Comment by martijnwalraven** [comment]
It's been a while since I looked at this, but if I remember correctly the issue might be that the web serving mechanism on Android does not support range requests.

**Comment by ramezrafla** [comment]
@dnish were you able to use actual local storage with a plugin? I don't expect the web server will be altered at this point.

**Comment by ramezrafla** [comment]
Can we close this?

**Comment by dnish** [comment]
@ramezrafla Yeah, we have to use the cordova media plugin to access those files.
