### ISSUE TITLE
[Feature Request] - Make possible to control build process

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8292]
For example, I'd like to be able to:
1. Run macros on source code, eg clean it of development-specific parts before bundling for production
2. Use my own minifier \ uglifier settings

**Comment by hwillson** [comment]
@avalanche1 - Have you looked at the [Build Plugins API](https://docs.meteor.com/api/packagejs.html#build-plugin-api)?

**Comment by avalanche1** [comment]
Mmmm.. not really, but if what I've listed is possible with the current API, I'll be happy to close.

**Comment by stubailo** [comment]
What are some reasons to use your own minifier

**Comment by avalanche1** [comment]
@stubailo, rephrased the  initial post a bit

**Comment by hwillson** [comment]
Hi @avalanche1 - I'd suggest trying out the [Build Plugins API](https://docs.meteor.com/api/packagejs.html#build-plugin-api) to see if it meets your requirements, then consider posting back if there are any parts you think are missing. Based on what you've described though, the build plugins API should meet your needs. For example, Meteor's [standard minifiers are build plugins](https://github.com/meteor/meteor/blob/f0dd494c82244df79b544bdbf590ebecc0412189/packages/standard-minifier-js/package.js#L8-L16), that can be re-implemented/replaced as needed. Closing for now - thanks!
