### ISSUE TITLE
Meteor unexpected token (meteor-promise)

### ISSUE THREAD

**Issue by Ammar-Yousif** [meteor/meteor#8299]
I faced this strange exception when i run meteor application
What this kind of error!!!
i really stuck i can not find any helpful solution on the internet
meteor version (1.4.2.3). I appreciate any help guys.

![capture](https://cloud.githubusercontent.com/assets/9278464/22405354/0703eb5a-e64a-11e6-9bf2-d48d53f6166d.PNG)

**Comment by laosb** [comment]
Hi, 
I think it's better to discuss this on [forums](https://forums.meteor.com). Issues Tacker is a place for bugs and feature requests.

Anyway, when you ask on forums, please attach necessary information, including packages you used. Closing!
