### ISSUE TITLE
Template.currentData() not reactive

### ISSUE THREAD

**Issue by NitroBAY** [meteor/meteor#8300]
Hello,
Template.currentData() states to be reactive but in my project it has never worked (so I've been using the ReactiveVar solutions for months, e.g `Template.currentData().property = new ReactiveVar()`).
For instance 
Template.admin.onRendered(function () {
  this.autorun(() => {
    const currentData = Template.currentData();
    console.log(currentData.couponType);
  });
  Template.currentData().couponType = true;
});
only logs `undefined` but not is not triggered again to log true.

Packages : 
accounts-base@1.2.14
accounts-password@1.3.3
allow-deny@1.0.5
archive:jquery-dotdotdot@1.6.15
arillo:flow-router-helpers@0.5.2
autoupdate@1.3.12
babel-compiler@6.13.0
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.0
blaze-html-templates@1.1.0
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.1.9
caching-html-compiler@1.1.0
callback-hook@1.0.10
check@1.2.4
coffeescript@1.11.1_4
ddp@1.2.5
ddp-client@1.3.2
ddp-common@1.2.8
ddp-rate-limiter@1.0.6
ddp-server@1.3.12
deps@1.0.12
diff-sequence@1.0.7
ecmascript@0.6.1
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
es5-shim@4.6.15
fastclick@1.0.13
fourseven:scss@3.13.0
froatsnook:valid-email@1.0.0
geojson-utils@1.0.10
ground:db@2.0.0-rc.6
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.10
id-map@1.0.9
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.0.12
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
manuel:reactivearray@1.0.5
materialize:materialize@0.97.8
meteor@1.6.0
meteor-base@1.0.4
meteorhacks:kadira@2.30.3
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
minifier-css@1.2.15
minifier-js@1.2.15
minimongo@1.0.19
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.8
momentjs:moment@2.17.1
mongo@1.1.14
mongo-id@1.0.6
mongo-livedata@1.0.12
npm-bcrypt@0.9.2
npm-mongo@2.2.16_1
observe-sequence@1.0.14
ordered-dict@1.0.9
promise@0.8.8
raix:eventddp@0.0.2
raix:eventemitter@0.1.3
raix:eventstate@0.0.4
random@1.0.10
rate-limit@1.0.6
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
rzymek:moment-locale-fr@2.14.1
seba:minifiers-autoprefixer@1.0.1
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.1
softwarerero:accounts-t9n@1.3.7
spacebars@1.0.13
spacebars-compiler@1.1.0
srp@1.0.10
standard-minifier-js@1.2.1
teamon:tinymce@4.4.1
templating@1.3.0
templating-compiler@1.3.0
templating-runtime@1.3.0
templating-tools@1.1.0
tracker@1.1.1
ui@1.0.12
underscore@1.0.10
url@1.0.11
useraccounts:core@1.14.2
useraccounts:flow-routing@1.14.2
useraccounts:materialize@1.14.2
webapp@1.3.12
webapp-hashing@1.0.9
zimme:active-route@2.3.2

I have METEOR 1.4.2.3 but currentData() wasn't a reactive source even in previous versions.

**Comment by hwillson** [comment]
Hi @NitroBAY - for all Blaze related questions, please file issues in the [Blaze repo](https://github.com/meteor/blaze) directly. That being said, `Template.currentData()` should be reactive. The problem likely lies somewhere else in your code. I'd suggest trying to create a small reproduction showing your issue, and posting that in a new issue within the Blaze repo. Chances are that when you put together that repro, you'll notice the problem. Just to add - `Template.currentData` uses [`ReactiveVar`'s internally](https://github.com/meteor/blaze/blob/53ed6b0ff9487ca5be441ca04d29517fef5e2bf2/packages/blaze/builtins.js#L16), so you're probably closer than you think to getting things working. I'll close this here - thanks for reaching out!

**Comment by NitroBAY** [comment]
Thanks a lot. I'll create a repo when I'll have time and post it in the Blaze repo.
