### ISSUE TITLE
Cannot publish package

### ISSUE THREAD

**Issue by deanius** [meteor/meteor#8301]
I end up in an unbreakable cycle of contradictory messages:

- `ETIMEDOUT While uploading build`
- `error: Version already exists`
- `error: No compatible binary build`

I've tried logging out and back in, even publishing under a new name to work around this, and still no dice. 

Am I supposed to use local packages when days go by and I can't publish? Seems like it.

```
~/src/antares (master) $ meteor publish --create
=> Errors while publishing:

While uploading build:
error: Error: ETIMEDOUT

~/src/antares (master *) $
~/src/antares (master *) $ meteor logout
Logged out.
~/src/antares (master *) $ meteor login
Username: deanius
Password:

Logged in as deanius. Thanks for being a Meteor developer!
~/src/antares (master *) $ meteor publish --create
Package already exists. To create a new version of an existing package, do not
use the --create flag!
~/src/antares (master *) $ meteor publish
=> Errors while publishing:

While pre-publishing package deanius:antares-protocol:
error: Version already exists

~/src/antares-example-document-editing (master *) $ meteor add deanius:antares-protocol
 => Errors while adding packages:

While checking for deanius:antares-protocol@0.2.3:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

**Comment by deanius** [comment]
Update- it seems to have published correctly just now, closing

**Comment by Akryum** [comment]
This is regularly happening for me when publishing new versions of `akryum:vue-component`:

```
=> Errors while publishing:                   
                                              
While uploading build:
error: Error: ETIMEDOUT
```

**Comment by abernix** [comment]
@Akryum publishing from what platform and which version of Meteor?

**Comment by Akryum** [comment]
Windows and Linux (there is no native dependencies however), using Meteor 1.4.2.7

**Comment by Akryum** [comment]
Maybe someone else can try publishing it with `publish-for-arch`?

**Comment by smozingo** [comment]
If I'm reading this right, the issue is that you're having timeout issues trying to publish the vue-component app.  For someone else to try that they would need to be an authorized maintainer for the package, yes?

**Comment by Akryum** [comment]
I dont know, maybe they need to be logged in with my meteor account. :|

**Comment by klaussner** [comment]
I got the same error a few weeks ago when I updated one of my packages. The metadata was uploaded and the new version number and README appeared on Atmosphere, but using the update in an app caused a `No compatible binary build found for this package.` error. Atmosphere should only accept and publish a new version if the entire upload was successful.

**Comment by Akryum** [comment]
Maybe someone at MSG can help us publish this package for the time being.

**Comment by abernix** [comment]
@Akryum I just successfully published [`abernix:vue-component@0.8.5`](https://atmospherejs.com/abernix/vue-component) (for testing only – in fact, I flagged it as "unusable" so it won't show in search results) using `meteor publish` from [this folder](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-component), but this code identifies itself as 0.8.5 (according to its `package.js`)

Out of curiosity, if you don't have any binary dependencies in the package, why are you using `meteor publish-for-arch` ?

**Comment by Akryum** [comment]
Because of the same reason in the [klaussnet comment](https://github.com/meteor/meteor/issues/8301#issuecomment-281928660).

**Comment by abernix** [comment]
@Akryum I see.  In that case, if the upload really was corrupted, the version number is probably burned.  I realize it's annoying, but you'll have to bump to the new version and publish again.  If someone wants to look at the Meteor code for it, that'd be great, but I'm assuming it's on the package server side which is not public.  Unfortunately, I'm not sure when that might get looked (or how easy of a fix it would be).  Probably best to just burn the version unless it's becoming super common?

**Comment by Akryum** [comment]
I tried both bumping the version and using `--existing-version` with no success.

![publish-timeout](https://cloud.githubusercontent.com/assets/2798204/23317945/cd2784d2-fad0-11e6-8ab8-ecd77a8b54c1.png)

Every time the error shows up at roughly the same time. Before that, the uploading seems to be pretty stable.

**Comment by abernix** [comment]
@Akryum: Are you behind a firewall or running through a virtualization layer (e.g VirtualBox) that might be blocking WebSockets or have a weird networking stack?

**Comment by Akryum** [comment]
I'm on linux with no VM, no firewall, connected with Ethernet directly to my operator router.

**Comment by abernix** [comment]
@Akryum Can you publish other packages and just not this one?

**Comment by Akryum** [comment]
I can publish smaller packages just fine.

**Comment by Akryum** [comment]
Any news on this? I need to publish a new version of the package for the release of Vue 2.2

**Comment by Akryum** [comment]
I have found a workaround: `meteor admin get-machine` and I then clone the repo and publish from the meteor VM. But this is not very practical. :smile:

**Comment by abernix** [comment]
It works for me too, over a mobile connection, so I'm just not sure what the problem is which would be causing it to fail for you every time.  We use the same facility for [publishing Meteor packages](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L441-L448) and [Meteor releases](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L1007-L1013).

I'm wondering if implementing some sort of retrying would be helpful to you – though I'm not sure if we can do `PUT` with resume ([`PATCH`](https://tools.ietf.org/html/rfc5789) me, maybe?) with the current infrastructure.

**Comment by Akryum** [comment]
Still happening on my cable connection. :disappointed: 

```
While uploading build:
error: Error: ETIMEDOUT
```

**Comment by Akryum** [comment]
Just tried with a wifi hotspot on my phone's 4G+ connection and it works just fine. I think this is just my upload speed being too slow and the build upload timing out before being complete (while the transfer is still in progress). Maybe this timeout could be disabled?
