### ISSUE TITLE
http://localhost:3000/ doesn't work on google

### ISSUE THREAD

**Issue by pavlism** [meteor/meteor#8309]
When seting up google oauth you can't use http://localhost:3000/ as the Authorized JavaScript origins
Google will give you this error: Origin URIs must not contain a path or end with "/": http://localhost:3000/

**Comment by RWizard** [comment]
Try http://lvh.me:3000

**Comment by pavlism** [comment]
http://localhost:3000 works fine, (had to double check).  The screen you get when you click the configuration button says to use http://localhost:3000/ which used to work, but now causes the error and confusion.

**Comment by stubailo** [comment]
Should be easy for someone to send a PR to remove the trailing slash to the Google accounts package!

**Comment by TechplexEngineer** [comment]
@stubailo Would you mind reviewing my PR as I believe you reviewed a previous PR for a previous report of this issue.

**Comment by abernix** [comment]
Thanks, @TechplexEngineer.  This should surface in Meteor 1.4.3.
