### ISSUE TITLE
Meteor could print nicer message for missing Meteor package

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#8313]
Right now, you get a message like:

```
Error: Can't find npm module 'meteor/xolvio:cleaner'.
```

Seems like it would be pretty simple to add a branch to check for starting with `meteor/` and print a message to `meteor add X` instead.

The issue is that the message is actually incorrect, since the problem doesn't have anything to do with `npm`.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20could%20print%20nicer%20message%20for%20missing%20Meteor%20package&body=Migrated%20from:%20meteor/meteor%238313) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
