### ISSUE TITLE
Promise server error on startup

### ISSUE THREAD

**Issue by muffinrecon** [meteor/meteor#8314]
My computer accidently shut down without properly closing the meteor server. Not sure if this is the reason why, but after restarting and trying to start it back up again I get the error below

```
.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected token 

Process finished with exit code 1
```

I tried reinstalling meteor and the problem is still happening. Any ideas?

**Comment by muffinrecon** [comment]
Resolved. Had to reinstall meteor/create a new project and then carry over files to the new project.

**Comment by fidelsam1992** [comment]
I tried this and worked for me:
- Delete .meteor/local directory
- Run ```meteor reset```
- Re run your project again ```meteor run```
