### ISSUE TITLE
standard-minifier-js - Enhancement proposal: customization & adding some defaults

### ISSUE THREAD

**Issue by PEM--** [meteor/meteor#8319]
**Problem**

Isobuild embeds unnecessary codes from server side packages (shell-server, for instance), from `Meteor.isServer` and, for NPM packages that relies on `process.env.NODE_ENV` to remove development helper logic.

**Suggested solution**

`standard-minifier-js` package uses UglifyJS2 for minification and mangling.  We can add additional logic used for the production build to strip off theses unused bytes from the build:

* Text replacements strategies with [`dead_code`](https://github.com/mishoo/UglifyJS2#compressor-options).
* List of filenames that are not imported in the bundled.
* Minification of the aggregated files instead of an aggregation of each minified files.

Exposing UglifyJS2's options, the text replacements and the list of filenames allows Meteor's user to go even deeper.

We have setup a package based on `standard-minifier-js` the that does just that and we have been able to shave more than 10% of our production builds for our customers, making them more on par with webpack builds: https://github.com/ssrwpo/uglifyjs2

Additional note: [link to the Meteor's discussion with @stubailo on this topic](https://forums.meteor.com/t/ssrwpo-uglifyjs2-push-js-minification-a-bit-further/33728/5).

**Comment by PEM--** [comment]
We should close this feature request as #8378 could do it.

**Comment by sethmurphy18** [comment]
I agree with closing, I am coordinating with MDG in #8378 to fix this issue.

**Comment by laosb** [comment]
Thank you @sethmurphy18 and @PEM-- for proposing and making contributions - should be done in #8378
