### ISSUE TITLE
'export {variable}' declaration in coffeescript throws error

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8320]
api.coffee
```
globals = 123
export {globals}
```
throws
```
=> Errors prevented startup:
   
   While building for web.browser:
   imports/config/api.coffee.js:2:75: Unexpected token, expected , (2:75)
   
   While building for os.windows.x86_32:
   imports/config/api.coffee.js:2:75: Unexpected token, expected , (2:75)

```
According to [coffee api](http://coffeescript.org/#modules) this code is quite valid.
Note that this code works just fine
```
globals = 123
export {globals as globs}
```

js version also works fine
```
const globals = 123;
export {globals}
```

**Comment by mitar** [comment]
I do not think Meteor CoffeeScript was upgraded to the version supporting this API in stable Meteor. It will be in 1.4.3 Meteor version.

**Comment by hwillson** [comment]
CoffeeScript was bumped from version 1.12.0 to 1.12.3 in https://github.com/meteor/meteor/commit/a1514223c8609745f9a15ea1f5630440361e288f. Can you try this again with Meteor 1.4.3.1? I’ll close this for now assuming this issue has been fixed, but if you’re still having problems please post back (ideally with a small, runnable reproduction). Thanks!
