### ISSUE TITLE
Getting error in ios production with  in-app purchase plugin

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#8322]
Hello

We have integrate https://github.com/AlexDisler in-app purchase plugin in meteor and now build in productions. We have added loggly logs to tracks logs for user activity.
We found some of user are getting following error code

{"line":60,"column":23,"sourceURL":"http://localhost:12240/plugins/cordova-plugin-inapppurchase/www/index-ios.js"}

We try to reproduce this issue but we are not able.  We have already post issue on 
https://github.com/AlexDisler repository no one has any reply.

Please any one help me if any one has face same issue 

Thanks

**Comment by hwillson** [comment]
Hi @mitiaptest - sorry to hear you're having trouble. This doesn't (initially anyways) sound like an issue with the Meteor core. For this type of problem, you'll likely have better luck reaching out for help on the [Meteor Forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). If you do think this is a problem with the Meteor core, please try to put together a small reproduction showing this issue, and post back. Until such time however, I'll close this issue off. Thanks for reaching out!
