### ISSUE TITLE
When generating a reset and invitation tokens, allow one to add custom metadata

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8326]
Once they are in their own collection, adding extra metadata to each document would be really easy to do. In this way one could store for example which IP requested a reset token, which user invited which other user, and so on.

**Comment by abernix** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository.

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=When%20generating%20a%20reset%20and%20invitation%20tokens%2C%20allow%20one%20to%20add%20custom%20metadata&body=Migrated%20from:%20meteor/meteor%238326) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

😸

**Comment by mitar** [comment]
This has been implemented as part of #8207.
