### ISSUE TITLE
non-imported codes are bundled/minified

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#8332]
I notice that some blaze templates and scripts are not imported but are still present on the client-side. This makes the minified js file very big. Is this avoidable?

**Comment by benjamn** [comment]
Put them in an `imports` directory?

**Comment by WayneUong** [comment]
@benjamn yes all of my importable codes are in the import directory. I selectively import them using a meteor setting like this:

```
switch (Meteor.settings.public.app) {
    case 'main':
        import '../imports/client/main.js';
        break;

    case 'donate':
        import '../imports/client/donate.js';
        break;

    case 'admin':
        import '../imports/client/admin.js';
        break;

    case 'subscribe':
        import '../imports/client/subscribe.js';
        break;
}
```

**Comment by benjamn** [comment]
To remove those files (and their dependencies) from the monolithic initial bundle, you'll need to use [dynamic `import(...)`](https://github.com/tc39/proposal-dynamic-import), a new feature in Meteor 1.5: https://github.com/meteor/meteor/pull/8327#issuecomment-278432593

**Comment by WayneUong** [comment]
Thanks @benjamn
