### ISSUE TITLE
Signed APK does not work.

### ISSUE THREAD

**Issue by rajpa** [meteor/meteor#8333]
I am running Meteor version 1.4.2.3. I have an android apk created out of this meteor app.

When I run the app from meteor it works. i.e this works: meteor run android-device --mobile-server=https://x.y

this does not work--> As soon as I create a signed apk from either mup or from meteor build, the signed apk stops working, whereas the unsigned (debug) apk worked before. The (signed apk) app opens on the phone, shows the index.html but when I click signin on the accounts-ui nothing happens.

The signed apk uploads to the play store, but the downloaded apk shows index.html content and then nothing. I click the sign in button, nothing happens.

I have seen several people raising this issue and have tried all of them, still it doesn't work.

Things I tried:

* change --server, mobile-server flags in several ways
* check ssl certificate intermediaries
* change CN in certificate
* change root_url, DDP url, mobile_root_url, mobile ddp url

Here is the logcat:

02-08 13:13:27.683 3698 9958 E BoostFramework: Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference

Using Chrome Remote Debugging, I am seeing the following in the network headers:

Request URL:http://10.0.2.2:3000/sockjs/info?cb=z3owek1ly6
Request Headers
Provisional headers are shown
Origin:http://localhost:12072
Referer:http://localhost:12072/
User-Agent:Mozilla/5.0 (Linux; Android 6.0.1; SM-N910H Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36
Query String Parameters
view source
view URL encoded
cb:z3owek1ly6

**The app is trying to connect to 10.0.2.2:3000, instead of my server http://x.y:443.**

This is really a showstopper as I am unable to create a working signed APK :(

Please help to fix this asap as I will be unable to distribute my apk via play store.

**Comment by abernix** [comment]
Can you please try with Meteor 1.4.2.6, which was just released?  I think this may be fixed by https://github.com/meteor/meteor/pull/8142 (see related issue: https://github.com/meteor/meteor/issues/6756 and others listed in the PR)

    meteor update --release 1.4.2.6

**Comment by rajpa** [comment]
Awesome @abernix !! Can confirm it works from a clean build (removed .meteor/local and also ~/mybuilddir). Now the signed app is able to connect to the backend server.

Mucho obligissimo! 🥇
