### ISSUE TITLE
meteor run segfaults when watson-developer-cloud@2.17.1 npm package is installed

### ISSUE THREAD

**Issue by nfriedly** [meteor/meteor#8334]
[watson-developer-cloud](https://www.npmjs.com/package/watson-developer-cloud) <= v2.17.1 included a copy of the gh-pages branch in a folder in the npm package. For some reason, the presence of this folder and it's contents causes meteor to segfault.

- What version of Meteor you're using, and the platform(s) you're running it on
  * Meteor 1.4.2.3
  * macOs 10.12.3
- What packages or other dependencies you're using
   * just watson-developer-cloud
- Steps to reproduce:
 ```
meteor create test
cd test
meteor npm install
meteor npm install watson-developer-cloud@2.17.1
meteor
rm -rf node_modules/watson-developer-cloud/gh-pages/
meteor
```

The first `meteor` hits a segmentation fault with various  messages depending on the shell and possibly platform:
* `fish: “meteor” terminated by signal SIGSEGV (Address boundary error)`
* `fish: Job 1, 'meteor' terminated by signal SIGBUS (Misaligned address error)`
* `Segmentation fault (core dumped)`
* `Bus error: 10or web.browser                  /`

I fixed watson-developer-cloud to not include the gh-pages folder in v2.18.0, so if you skip the version tag when installing, meteor should work. But I have no idea how that could translate into a segfault, so I thought you guys might be interested. 

There is a decent amount of html and JS in the gh-pages, and there is supposed to be a symlink named `latest`, although I didn't actually see it...

Initial ticket was at https://github.com/watson-developer-cloud/node-sdk/issues/392

**Comment by hwillson** [comment]
Thanks for reporting this @nfriedly - that is bizarre. Since things are now working properly with the latest version of the `watson-developer-cloud` package (due to your change), and we haven't received any other complaints about this issue, I'll close it for now.
