### ISSUE TITLE
[Question] Optimistic UI - How to re-use it ?

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#8337]
Context
===========

Hello, this is related to the project redis-oplog, https://github.com/cult-of-coders/redis-oplog

Timeline of an optimistic ui update as client:
1. Send call to a method that does a mutation client-side and server-side (an optimistic ui method)
2. Receive DDP collection mutations from the server
3. Receive "ok" for method execution.

If 2 isn't executed, or is executed after 3. It will result into a flicker:
1. Changes are made to the collection on client
2. Receive "ok" for method execution
3. Changes are reverted, because we did not receive any "validation" from the server of the client-side mutations
4. New changes come-in processed by the redis server.

Current solution in redis-oplog, is when we call the method, we synchronously dispatch and diff the changes for all clients in the mutator methods of the collection (update/upsert/insert/remove) and they are performed in sync for all observers running on that meteor instance.

However, this approach is not ok, because it will result in method spikes due to extra processing.

Possible solution:
- Perform a naive update only on the connection id of the invoker

My Question
===========
How can I harness Meteor's way of doing this ? Without having to re-implement the logic of the possible solution.

I need someone with deeper understanding of optimistic-ui to give me a helping hand. Thank you!

**Comment by rajpa** [comment]
Can you create a separate redis channel for the data in method executions?

**Comment by stubailo** [comment]
I mean this is essentially why Meteor's data system is extremely difficult to reimplement in any other way. You need to be able to identify when all of the changes have been synced to the client, the "updated" message in DDP. Meteor's way of doing this relies on timestamps in the oplog, which is a big part of why Meteor doesn't adequately support any other data source.

Perhaps there could be a way of doing this kind of time stamp correlation via Redis, but at first glance it seems like it would be pretty different.

Note: this is all typed on my phone based on memory - someone should look at the actual code.

**Comment by theodorDiaconu** [comment]
@rajpa can't rely on redis for optimistic-ui, that's the thing, it needs to be done in sync before the "method" returns. 

@stubailo 
Indeed it was a way bigger challenge than expected, but this is the final missing piece.

I almost never use Optimistic UI in my apps, since everything happens instantly any way, but for larger-scale I understand the necessity. I will be waiting for other insights, maybe someone can guide me so I can code this faster. Either way there is ALWAYS a solution, and since we came so close to something good it would be a shame not to continue.

**Comment by nadeemja** [comment]
Hi! 

I'm using redis-oplog with optimistic UI. Haven't had any issues, that I know of. 

I'm open to doing experiments that might prove useful. Please let me know.

**Comment by theodorDiaconu** [comment]
@nadeemja nice!
The issue is that it will do additional computing for your method. If you use kadira, you will notice that your methods will take a bit longer to execute due to this. You could do some investigation there.

Optimistic UI is currently stable and working however, it's doing some extra-work that can avoid doing.

**Comment by sebakerckhof** [comment]
What are the trade-offs for the possible solution you mention. E.g. why isn't that good enough?

**Comment by theodorDiaconu** [comment]
@sebakerckhof: 

Main issues:
1. Can't isolate the changes to a single observer, since a publication can be shared, and when I'm performing a change, I'm also updating the internal state of the publication in Redis.

2. The processing of the diff needs to be done in sync, before the method returns => bigger response times for methods.

@stubailo where is the code for optimistic-ui ? I keep searching it but I'm getting lost in the code. Maybe I can get inspired from there. Since you did the article here: https://blog.meteor.com/optimistic-ui-with-meteor-67b5a78c3fcf#.8l54pr265

**Comment by theodorDiaconu** [comment]
I am completely lost in the code. How is Meteor sending those "added"/"changed"/"removed" events before the method yields. Anyone has a clue ?

**Comment by hwillson** [comment]
Hi @theodorDiaconu - take a look at the DDP server's [`Session`](https://github.com/meteor/meteor/blob/f0dd494c82244df79b544bdbf590ebecc0412189/packages/ddp-server/livedata_server.js#L325) class (not to be confused with the `ReactiveDict` based [`Session`](https://github.com/meteor/meteor/tree/devel/packages/session)). Does that help?

Reading over this issue thread, I'm trying to figure out how to help move this forward from an issue triaging point of view. This thread really is more of a discussion, that doesn't have any clear issues or feature requests that can be extracted out, and worked on. How would you guys like to proceed with this? Is there anything actionable here that should be extracted? I'm just wondering if we should keep the discussion going here, or if this thread would be better suited on the forums.

**Comment by theodorDiaconu** [comment]
@hwillson document how optimistic ui works, a sort of lifecycle that would help developers to develop on it in the future. That is my actionable item in my opinion.

**Comment by hwillson** [comment]
Based on the discussion in https://github.com/meteor/meteor/issues/8337#issuecomment-301509277 and https://github.com/meteor/meteor/issues/8337#issuecomment-301510017, this issue is likely better suited in the https://github.com/meteor/docs repo. If anyone is interested in championing this further, please consider opening a new issue in that repo. Closing here - thanks!
