### ISSUE TITLE
Cannot see files transpiled from Coffeescript

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8339]
I'm now making a final transition from 1.1 to 1.4 and am very surprised not to see my individual source files in chrome debugger - but a giant app.js instead.
It should be noted that my project is in Coffeescript.
At 1st I thought it was related to https://github.com/meteor/meteor/issues/8281 and https://github.com/meteor/meteor/issues/8138 and after running release 1.4.3-rc.2 source maps are being generated properly.

Yet I still have problems. Here is how `foo.coffee `looks in chrome debugger:
![image](https://cloud.githubusercontent.com/assets/10534563/22782102/99f99556-eed6-11e6-9362-626170561393.png)
The problem is: I cannot set a breakpoint on any of console.logs (lines 3, 4). It is being automatically reassigned by chrome to line 2.
Essentially, I don't want execution to break on line 2, I want it to break on Meteor.startup callback execution.

In meteor 1.1 I could access `foo.coffee.js` and and set a breakpoint on any line there. In 1.4 all .js files are being bundled into a huge `app.js` which is unwieldy to debug at best.
It is my opinion that we don't need that kind of behaviour in development environment. Can we return to the behaviour used in meteor 1.1?

Or is this the only way possible to build an app when we have ES6 modules?
In that case how could I still debug those console.logs?

```
import {Meteor} from 'meteor/meteor'
Meteor.startup ->
	console.log "restarted at: #{new Date}"
	console.log 123
```

**Comment by abernix** [comment]
Have you looked at or tested the PR/fix attached to those other issues, #8298, which is currently open and pending merge?

Do you mind testing it and see if the solution works for you before it gets merged?  We'd appreciate the additional eyes on it!

**Comment by avalanche1** [comment]
I may be misreading that PR discussion, but I don't see how it relates to the issue that I have submitted.

**Comment by abernix** [comment]
It demonstrates a fix to an (apparently) still-problematic CoffeeScript Sourcemap issue (otherwise, the PR wouldn't be there, right?).

I was simply asking to see if you could test it and see if it does fix the problem so we don't chase down something that's already fixed.  I'm sure you can understand my hesitance to debug this issue when there is a known problem outstanding.

When #8298 lands, please test it!  Thanks!

**Comment by klaussner** [comment]
@avalanche1 In the 1.4.3 release candidate, the CoffeeScript sources are included but the mappings from *app.js* to these sources are incorrect. That's why the Chrome debugger can't relate the `console.log`s in your files to the actual JavaScript code.

**Comment by avalanche1** [comment]
After updating to 1.4.3 source maps are totally absent!

**Comment by hwillson** [comment]
Hi @avalanche1 - is this issue still happening for you? If so, could you first try updating and testing things out with Meteor 1.4.4.1. If that doesn't help, any chance you could put together a small reproduction demonstrating the issue you're seeing? That would greatly help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by hwillson** [comment]
We haven't heard back on this in a few weeks, so I'll close this issue for now. Happy to re-open if this problem is still happening, and you can provide answers to https://github.com/meteor/meteor/issues/8339#issuecomment-293676554. Thanks!
