### ISSUE TITLE
Meteor Angular1 Cordova Android App Goes white Blank screen after build

### ISSUE THREAD

**Issue by NawazKhanMd** [meteor/meteor#8340]
Hai,

i was trying to build a mobile app for a web app which was developed in meteor,  so when i try to run the command meteor run android-device 

i get the build but app seems to be stuck with blank screen, i have gone through most of the other workarounds and fixes but nothing seems to work for me.

in the console.log i have only two logs which does say the event was not fired and in the network page of inspection all the packages are taken from cahe it says that and some of them try to access from the desktop which is ran the meteor run command

after the robot font service hit it stopped
and my app is not loaded  only body and head tag is loaded 

and I am using ui router for routing service

**Comment by NawazKhanMd** [comment]
do we need a virtual host to run my meteor app on mobile?

cuz am running meteor run android-device -p MyIp:3000 --mobile-server virtualHostIpToWhichMobileIsConnected:3000

this gives me a blank screen

am i doing it wrong pls Reply :)

**Comment by NawazKhanMd** [comment]
hai @meteor-bot

**Comment by NawazKhanMd** [comment]
Hai @Slava

**Comment by NawazKhanMd** [comment]
hai @martijnwalraven

**Comment by hwillson** [comment]
Hi @NawazKhanMd - sorry to hear you're having trouble. Requests for help like yours are much better suited for either the [Meteor Forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). GitHub issues are reserved for Meteor bugs and/or feature requests. If you think the issue you're encountering is a Meteor bug, please review the [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines. Thanks!
