### ISSUE TITLE
install script remove exist meteor too fast

### ISSUE THREAD

**Issue by cncolder** [meteor/meteor#8352]
I'm not sure if [https://install.meteor.com]() stay in this repo. When I run `curl https://install.meteor.com | sh`. It remove my existing meteor first. And then download tarball. No confirm! No version check!

Some users like me. Download  meteor is paining. More than 1 hour.

My suggest is download first. Then remove exist meteor and replace it. So I can press `^C` to cancel download.

**Comment by abernix** [comment]
If you already have Meteor installed, why do you need to reinstall?  Unless you are repairing a (somehow) broken installation, you should only need to `curl` the very first time you install.

**Comment by stubailo** [comment]
Perhaps we should add a check to the script that says "this will remove your existing meteor installation - are you trying to update meteor instead?"

**Comment by cncolder** [comment]
@abernix misoperation or forget. page up terminal history.

@stubailo Yes we can tell usage `meteor update --release x.x`. But don't prompt `Y/n`. It will break existing scripts (like CI, Dockerfile). I think we can read env to decide if reinstall. `METEOR_ALLOW_REINSTALL=1 https://install.meteor.com | sh`

**Comment by abernix** [comment]
While an interactive prompt would absolutely break interactive environments, presumably, CI and Docker implementations wouldn't be reinstalling Meteor so they actually wouldn't be broken by the proposal above.

That said, yes, it should still be checked: I think interactivity can be detected reliably with `test -t 0 || test -p /dev/stdin` – even in Docker/via-SSH.  I don't think an environment variable would be proper for this particular implementation.  What do you think, @cncolder?  Would you be interested in submitting a `patch` file or code-snippet for this (as the installer itself isn't on a public repo)?

**Comment by cncolder** [comment]
Sorry @abernix I have no enough skill to write shell script.

Yes environment variable is not good enough. I wish official script maintainer see this and improve by another way.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=install%20script%20remove%20exist%20meteor%20too%20fast&body=Migrated%20from:%20meteor/meteor%238352) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
