### ISSUE TITLE
IOS build errors - Meteor Angular Ionic Cordova

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#8353]
I just build a very simple app based on meteor-ionic-angular using this official whatsapp tutorial:

**Upto this step:**
[https://angular-meteor.com/tutorials/whatsapp/meteor/meteor-server-methods](https://angular-meteor.com/tutorials/whatsapp/meteor/meteor-server-methods)

I am using the latest version of meteor i.e **Meteor 1.4.2.6**
Also patched using:

 `meteor update --patch`

Now when I run my app for ios using this command:

`meteor run ios-device`

It opens my code in Xcode and when I run the build, it gives too many errors:

Here is the screenshot of errors:
[https://cdn-enterprise.discourse.org/meteor/uploads/default/optimized/2X/6/6ff6e47367249d9c95b977ab4d1a105fb55aa027_1_516x500.png](https://cdn-enterprise.discourse.org/meteor/uploads/default/optimized/2X/6/6ff6e47367249d9c95b977ab4d1a105fb55aa027_1_516x500.png)

My XCode version is: **7.3.1**

It works perfect for android. But for IOS I get all these errors.

Is there any workaround to fix these errors?

**Comment by abernix** [comment]
Please update your XCode to version 8 or higher and report back if your problem persists.  Meteor 1.4.2 uses Cordova 6.2 which probably uses Swift 3 which is only supported by XCode 8 (which has been out since September 2016).
