### ISSUE TITLE
[1.4.2.6 Cordova] HCP failed, how to debug?

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#8354]
We're having a problem with our Android Cordova app. We've just upgraded our Meteor version to 1.4.2.6 and did some bigger changes within our app code. After deploying it, our Android app doesn't load the newest version, instead we're getting the older version with some weird behavior (the old code is still loaded within our app - but some client functions stopped working, so there must be an error on client side). Because this is a production app, we are not able to see the error logs, even Kadira doesn't show anything. How can I check what's going wrong there?

If I install the newest Android app (which matches with the current build), everything is working fine.

**Comment by dnish** [comment]
Just fixed the weird behavior which was caused due to a change on server side (one field was set empty). But HCP is still not working, I only get the old version.

**Comment by skirunman** [comment]
HCP will not work if any native code changes such as a Cordova upgrade or any Cordova plugin versions change. Meteor 1.4.3 has a new version of Cordova, v6.4.0. You will have to manually update any devices and refresh any apps in Apple or Google stores. See https://guide.meteor.com/mobile.html#updating-production-apps

**Comment by dnish** [comment]
Ah okay, didn'r recognize the upgrade of Cordova. I guess I can close this issue.

**Comment by skirunman** [comment]
As far as debugging you can hook up Chrome or Safari to your device for remote debugging. See https://guide.meteor.com/mobile.html#remote-debugging-ios

**Comment by dnish** [comment]
@skirunman I know, but this only works if the app is in debug mode. We're using Crosswalk and our app is in production mode, so it doesn't get listed in Developer Tools.

**Comment by dnish** [comment]
@skirunman Nope, all Cordova plugins are on the same version. I just did a regular meteor update and changed some client and server code. The "weird" behavior was caused due to a change within the server code (an optional fields was changed to required). But this was only server side and got fixed. So users on the old app can still use the app, but won't get the latest update.
