### ISSUE TITLE
Meteor 1.4.2 Accounts DDP logs out when page is refreshed

### ISSUE THREAD

**Issue by nosizejosh** [meteor/meteor#8357]
I have two meteor apps A and B. A is the backend(server + client) and B which is the web/mobile app, is a remote client( cleint only). I want my mobile app to use the backend app's Mongo instead of its own. To make it work I created a DDP connection and set it as Accounts.connection. Now, register and login seems work fine but when I refresh the page Meteor server logs me out with the following error.

`Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`

This is how I am achieving connection and login via ddp to remote server

```javascript

export const DDPConnectToRemote = (Meteor.isClient) ? DDP.connect("http://localhost:3000/") : {};

if (DDPConnectToRemote.status().connected){
  	Meteor.connection, Accounts.connection = DDPConnectToRemote;
  	console.log("Connected. working on getting remote users now");
    Meteor.users = new Meteor.Collection('users', {connection: DDPConnectToRemote});
    DDPConnectToRemote.subscribe('users', function() {
      var users = Meteor.users.find();
      console.log(users.count());
    });
	var token = Accounts._storedLoginToken();
  	if(token)  {
  		console.log("token: "+ token);
    	Meteor.loginWithToken(token, function(err){
	      	// this is going to throw error if we logged out
	      	if(err){
	      		console.log(err);
	      	} 
	      	else {
	      		console.log('loginWithToken');
	      	}
    	});
  	}
  }
```

others https://forums.meteor.com/t/accounts-ddp-logs-out-when-page-is-refreshed/8472,  
https://forums.meteor.com/t/accounts-password-accounts-ui-remote-users-trought-ddp/23458/2,
https://forums.meteor.com/t/error-logging-in-with-token-in-two-separate-applications/7382
have posted similar issues with lower version of meteor, I have tried all solutions and still cnat get past this. 
Please help.
@stubailo @benjamn @martijnwalraven

**Comment by nosizejosh** [comment]
@stubailo you answered a similar issue here https://github.com/meteor/meteor/issues/4972 with this 
`You can fix this right now by putting:
        __meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = "the_url";
    somewhere in your app's server-side code. This value is then propagated to the client.
`for a meteor 1.2. 

Is there a better solution for meteor 1.4.2 ? and also using this solution would mean my client part of app A will not function properly as this `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = "the_url";` will mean it will be ignored for the client in app B.

**Comment by hwillson** [comment]
@nosizejosh Are you still encountering this issue with a more recent version of Meteor (e.g. 1.6)? The `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` approach mentioned in https://github.com/meteor/meteor/issues/8357#issuecomment-279233634 has been deprecated. `AccountsCommon` based objects (like `AccountsClient` and `AccountsServer`) now accept a connection object or a `ddpUrl` string, via an `options` object passed into their constructor (you can see the details [here](https://github.com/meteor/meteor/blob/6f716eec93e19e5502b994dac433802581cef93e/packages/accounts-base/accounts_common.js#L199-L217)). 

I'll close this issue for now, but please post back if you're still encountering this problem using  a modern version of Meteor (after trying the updated Accounts API). Thanks!

**Comment by vuhrmeister** [comment]
@hwillson I stumbled upon exact the same issue. 

Obviously there is no clean way of setting up the Accounts connection. There are multiple "solutions" as mentioned above. All of those are trying to get remote Login working.

IMHO for `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` there should be an official API. Everything else is a hack.

The thing is that `Accounts` get [initialized right away](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/client_main.js#L9) when the `accounts-base` package is loaded. Then `_initLocalStorage()` is called before you have the chance to set the `Account`'s connection. Therefore [here](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/localstorage_token.js#L101) it still uses the `Meteor.connection` and doesn't look for the connection we set manually. I know, all those hacks are just hacks, so not officially supported.

Then there is documentation about [AccountsClient](https://docs.meteor.com/api/accounts-multi.html#AccountsClient). But this is only useful if I'm fine having the default `Accounts` instance as well. There are [plenty](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L272) of [functions](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L189) on it which references the default `Accounts` in any case.

I just want to point out again what the scenario is and why we need more flexibility. For simplicity just consider those 3 apps:

> 1. WebApp (or Cordova) for user group A
> 2. WebApp (or Cordova) for user group B 
> 3. The backend (including user management / authentication)
> 
> A and B are working on the same data set, but have a completely different interface (assuming A are end customers and B are retailers).
>
> App 1 & 2 should still point to their origin server for hot code push. But for authentication there must be only one user management. Therefore both frontend apps should reliably use the backend connection for authentication.

I don't know, maybe I miss something in the big picture.

Anyway, setting `__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL` does the trick for me. It's exactly what I am expecting.

**Comment by hwillson** [comment]
Thanks for your feedback @vuhrmeister. Would you be able to open a new feature request for this over in the https://github.com/meteor/meteor-feature-requests repo?

**Comment by vuhrmeister** [comment]
Of course, will do that! Thx
