### ISSUE TITLE
Support METEOR_SETTINGS_PATH

### ISSUE THREAD

**Issue by harishreddy-m** [meteor/meteor#8364]
Setting json content in METEOR_SETTINGS is painful to do, dealing with all escaping of special characters.

https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/meteor/server_environment.js

Is there any reason for not providing an option like METEOR_SETTINGS_PATH?

It is a minor enhancement which improves the experience ten times.

Some dummy code is written here : https://github.com/meteorhacks/meteord/issues/35#issuecomment-279343770

**Comment by elidoran** [comment]
Workaround:

1. git clone https://github.com/meteor/meteor.git
2. do git checkout <commit> for the specific commit of the release version you're currently using (look that up at [releases](https://github.com/meteor/meteor/releases))
3. symlink its "packages/meteor" package into your app's "packages" directory as "meteor"
4. alter the file "server_environment.js" like below
5. provide an absolute path to your settings file as METEOR_SETTINGS_FILE

```javascript
if (process.env.METEOR_SETTINGS) {
  try {
    Meteor.settings = JSON.parse(process.env.METEOR_SETTINGS);
  } catch (e) {
    throw new Error("METEOR_SETTINGS are not valid JSON: " + process.env.METEOR_SETTINGS);
  }
} else if (process.env.METEOR_SETTINGS_FILE) {
  try {
    Meteor.settings = JSON.parse(
      Npm.require('fs').readFileSync(process.env.METEOR_SETTINGS_FILE, 'utf8')
    );
  } catch (e) {
    throw new Error("METEOR_SETTINGS_FILE is not a valid JSON file: " + process.env.METEOR_SETTINGS_FILE);
  }
}
```

This worked both in development mode and in a production build.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Support%20METEOR_SETTINGS_PATH&body=Migrated%20from:%20meteor/meteor%238364) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
