### ISSUE TITLE
Server side call to async method returns Promise object, not value.

### ISSUE THREAD

**Issue by robfallows** [meteor/meteor#8367]
Refer to [this post](https://forums.meteor.com/t/how-to-declare-async-function-myfunction-inside-meteor-methods-so-that-front-end-can-call-it/25991/2) on the Meteor forums and to @benjamn's comments which follow on.

In a nutshell, a `Meteor.call` done on the server does not get the return value of an async method. Instead, it gets the Promise object. This is at variance with the expected behaviour.

This has been observed since v1.3, but the reproduction uses v1.4.2.6:

Reproduction:

    git clone https://github.com/robfallows/promise-issue promise-issue
    cd promise-issue
    meteor npm i
    meteor

The server's console log shows the result of calling the async method (shows `{}` - expected "42"):

    I20170214-11:23:14.415(0)? The answer to the ultimate question of life, the universe and everything is ... {}

The client browser shows the result of calling the async method from the client (shows "42" as expected):

    The answer to the ultimate question of life, the universe and everything is ... 42

**Comment by philcruz** [comment]
I'm seeing this as well.

**Comment by Suppen** [comment]
As a workaround, I exported the method function and imported it where I was using it on the server (in another method), then used `method.call(this)` to get the correct context

**Comment by benjamn** [comment]
This issue should (finally!) be resolved if you run `meteor update --release 1.4.3.3-beta.4` in your application directory, thanks to the commit 0cbd25111d1249a61ca7adce23fad5215408c821 referenced above.

**Comment by robfallows** [comment]
Works like a charm - thank you @benjamn 👍
