### ISSUE TITLE
Documentation Issues Remain Unprocessed

### ISSUE THREAD

**Issue by lazaridis-com** [meteor/meteor#8368]
I have filed some issues re documentation:

meteor/tutorials#100 - Repo and Live Site not in Synch

meteor/tutorials#101 - Provide a Tutorial which keeps the Simplicity Promise

A week has passed without response.

So I file an issue here, at the main project, but seeing the 641 open issues within this repo (up to 4,5 years old), I'm afraid that either I am doing something wrong, or the MDP (meteor development group).

What can I do that the issues get processed, and how can I contribute to the documentation?

**Comment by abernix** [comment]
Thanks for pointing this out.  You're not doing anything wrong, Meteor is a large, actively maintained project and it takes time to get to all the issues.  Your help in contributing is much appreciated.  In this case, it's just not very often that the tutorials get a face-lift, or updates, or pull-requests and it's not a repo that's visited or checked daily.

I'll respond to your issues over there.  Thanks again!

**Comment by lazaridis-com** [comment]
@abernix, you should possibly find a way to get pinged for new issues. Silence can be quite discouraging for a newcomer (I insisted, others just go to the next framework).

**Comment by abernix** [comment]
@lazaridis-com Already solved.  Thanks!

**Comment by lazaridis-com** [comment]
@abernix , I've now a better overview of Meteor and the project. Even trivial PRs within the tutorial project remain unprocessed since over a year, which leads to more users getting distracted/confused by the same issues. A tiny correction was send in 3 times with a PR by different users.

I try to triage the issues/PRs, but the overhead is excessive without commit rights (I file a PR to validate another PR, and then my PR remains unprocessed to).

Any solution to this? Can someone of the team take at least 30 min. a day to look at the issues/PRs, thus they can be closed/merged/rejected?

**Comment by hwillson** [comment]
Hi @lazaridis-com - thanks very much for taking the time to review the outstanding tutorial issues. Your help and feedback are greatly appreciated! I'm planning on diving in and reviewing your comments/updates shortly, and will update the associated issues as needed. Thanks again!

**Comment by abernix** [comment]
@lazaridis-com I saw your work there and thank you (truly!) for taking the time to go through them.  As I've already stated above, it's just a matter of time and I haven't had a chance to review your changes yet.  Either @hwillson or I will review your updates and PRs in the next week.  Also, if it's not clear, the team has a lot of PRs and issues to review and 30 minutes a day for looking at tutorial PRs is not something we're always able to allocate.

We will try to get better at this but your help is very much appreciated – just by providing feedback and opinions you've already made it easier for someone to go through and help clean things up, and that will happen soon.

**Comment by lazaridis-com** [comment]
@abernix @hwillson , all this is not that much about issues/PRs, but more about a defect in your processes. You must fix you dev-processes, thus Issues / PRs are processed quickly. This makes a good impression, avoids duplicates and encourages more contributions.

And in the end, it even saves manpower.

> Also, if it's not clear, the team has a lot of PRs and issues to review and 30 minutes a day for looking at tutorial PRs is not something we're always able to allocate.

You **must** find a way. This is a **must** requirement, just please be aware of this. Especially for the entry-level documentation.

Can be funny, too: "Team member A, you are punished! 1 day issue processing on docs"

**Comment by hwillson** [comment]
@lazaridis-com - yes, ideally all aspects of the Meteor ecosystem (from documentation, to tutorials, to core library code, etc.) would be kept continuously healthy and up to date. In practice however, decisions have to be made regarding where to focus both MDG and community energy, to have the greatest impact on helping the Meteor platform thrive. Everyone is trying hard to keep all parts of the Meteor machine running smoothly, but there are definitely a lot of moving pieces and never enough helpers! The best thing anyone can do to help, is, well, help. Keep doing what you're doing (reviewing old issues / PRs, submitting new issues / feature requests / PR’s, helping with documentation / tutorials, etc.). All contributions like this are definitely welcome! 

As for punishing contributors to an open source project … well, that might not go over so well … 🙂

**Comment by lazaridis-com** [comment]
@hwillson , you're a diplomat. But diplomats do not fix broken systems, they justify them.

Fact is that contributions like mine are a **waste of time a brainpower**. I'm a senior-dev with embedded-system-design experience, and I estimate that I invest around 5 to10 times the time necessary to look over/fix those issues.

It's heavily frustrating to not be able to merge a trivial missing "to", and to see that it simply does not go into the repo. 1 week? that's an eternity for a creative functioning mind in a state of flowing productivity.

> As for punishing contributors to an open source project

Nah, punishing the core-developers of a **commercial** open source product. Big difference!

**Comment by abernix** [comment]
@lazaridis-com Thank you for your tutorial contributions, we will get to them and respond to them as we are able.

As we gain reliable community contributors who help in a positive manner, over a longer period of time they can be promoted to do so on their own.  We openly document and encourage [ways to do so](https://github.com/meteor/meteor/blob/devel/Contributing.md).

While you claim to (now) have a better overview of the Meteor project, you most likely do not understand the extent of all of the project's repositories and the work to be done, where it is needed most, or how we manage our time, after only a few days of helping to review tutorial matters.  While criticism is welcome, debating or attacking our processes under this pretense is not likely to free up more of our (limited) time to review those issues, but we did appreciate your commenting and providing input on the tutorial issues as it will make it easier to handle them efficiently.

> punishing the core-developers of a commercial open source product.

As long as that "open source" term is contained within your desire to punish, I think you're going to find opposition to punishment.  Also, "playful punishment" is really not helpful either – I can assure you that I don't pride myself on the fact that there are PRs awaiting review that I haven't had time for.  Continuing to do the triaging you're doing while understanding the "give-and-take" and maintaining positivity is crucial to your helping any open-source project, ours included.

The initial gentle nudge/reminder was appreciated, but this continued discussion is a bit more than necessary and not really solving our problem so I'm going to lock this thread.  Let's work together to resolve the tutorial issues, in the appropriate venue.

**Comment by benjamn** [comment]
To anyone who comes across this thread in the future, @lazaridis-com has been banned from contributing to repositories within the Meteor Development Group organization. This was my decision, as the tech lead of the Meteor project, after reviewing this thread and others in which @lazaridis-com attempted to shame @abernix and @hwillson for their responses to his contributions. Self-righteousness, sarcasm, and abusive language have no place in this project.
