### ISSUE TITLE
[1.4.2.3, 1.4.2.6] Nested imports have `let` instead of `var` scope

### ISSUE THREAD

**Issue by dolgarev** [meteor/meteor#8369]
Release: Meteor 1.4.2.3 and 1.4.2.6
OS: Linux ... 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Hello guys!

Today I updated the packages for my application via `meteor update --packages-only`, here is a list of the updated packages:
```
accounts-password            upgraded from 1.3.3 to 1.3.4
aslagle:reactive-table       upgraded from 0.8.38 to 0.8.39
babel-compiler               upgraded from 6.13.0 to 6.14.1
blaze                        upgraded from 2.2.0 to 2.3.0
blaze-html-templates         upgraded from 1.0.5 to 1.1.0
caching-html-compiler        upgraded from 1.0.7 to 1.1.0
ddp-client                   upgraded from 1.3.2 to 1.3.3
ddp-server                   upgraded from 1.3.12 to 1.3.13
dferber:prerender            added, version 2.2.2_3
dfischer:prerenderio         removed from your project
ecmascript                   upgraded from 0.6.1 to 0.6.3
http                         upgraded from 1.2.10 to 1.2.11
launch-screen                upgraded from 1.1.0 to 1.1.1
less                         upgraded from 2.7.8 to 2.7.9
logging                      upgraded from 1.1.16 to 1.1.17
mdg:seo                      upgraded from 1.0.1 to 1.1.0
meteor                       upgraded from 1.6.0 to 1.6.1
meteorhacks:kadira           upgraded from 2.30.2 to 2.30.3
minifier-css                 upgraded from 1.2.15 to 1.2.16
minifier-js                  upgraded from 1.2.15 to 1.2.17
minimongo                    upgraded from 1.0.19 to 1.0.20
mobile-status-bar            upgraded from 1.0.13 to 1.0.14
modules                      upgraded from 0.7.7 to 0.7.9
modules-runtime              upgraded from 0.7.7 to 0.7.9
momentjs:moment              upgraded from 2.16.0 to 2.17.1
mongo                        upgraded from 1.1.14 to 1.1.15
npm-mongo                    upgraded from 2.2.11_2 to 2.2.16_1
observe-sequence             upgraded from 1.0.14 to 1.0.15
okgrow:analytics             upgraded from 2.0.1 to 2.1.0
rajit:bootstrap3-datepicker  upgraded from 1.5.1 to 1.6.4
shell-server                 upgraded from 0.2.1 to 0.2.2
spacebars-compiler           upgraded from 1.0.13 to 1.1.0
standard-minifier-css        upgraded from 1.3.2 to 1.3.3
standard-minifier-js         upgraded from 1.2.1 to 1.2.2
templating                   upgraded from 1.2.15 to 1.3.0
templating-compiler          upgraded from 1.2.15 to 1.3.0
templating-runtime           upgraded from 1.2.15 to 1.3.0
templating-tools             upgraded from 1.0.5 to 1.1.0
tracker                      upgraded from 1.1.1 to 1.1.2
url                          upgraded from 1.0.11 to 1.1.0
webapp                       upgraded from 1.3.12 to 1.3.13
```

After this nested import stopped working in my code:
```
import { Meteor } from "meteor/meteor";
import { _ } from "meteor/underscore";
import { RestrictMixin } from "meteor/ziarno:restrict-mixin";

if (Meteor.isServer) {
  import prettyHrtime from "pretty-hrtime";
  import { logger } from "/server/logger"
}

```
Bug: I see a bug **ReferenceError: logger is not defined** (or prettyHrtime) at the server's side.

Update of meteor to the version 1.4.2.6 did not help.

I think that the problem is in the package `babel-compiler`. I created a new project with version of `babel-compiler 6.14.1` and saw the same trouble. But when I run the old code with version `babel-compiler 6.13.0`, this trouble does not appear.

**Comment by benjamn** [comment]
Is `logger` not defined within the `if (Meteor.isServer) {...}` block, or simply not defined after the block? Imported symbols have `let` scope, so the latter is expected (on the server, where `let` is always supported).

You can probably make this work with code like this:
```js
let logger = { log() {} };

if (Meteor.isServer) {
  import prettyHrtime from "pretty-hrtime";
  import { serverLogger } from "/server/logger"
  logger = serverLogger;
}

logger.log("whatever");
```

**Comment by dolgarev** [comment]
Thank you @benjamn !

I have conducted an additional investigation. The problem occurred in the package ecmascript. I created a testing [repo](https://github.com/dolgarev/meteor-nested-import-bug), which has branches `ecmascript-0_6_1` and `ecmascript-0_6_3`. If we run an application from the branch `0_6_1`, the code works properly without any bugs. There is a bus in the branch `0_6_3`.

```
import { Meteor } from 'meteor/meteor'

if (Meteor.isServer) {
  import prettyHrtime from "pretty-hrtime"
}

if (Meteor.isServer) {
  console.log('prettyHrtime', prettyHrtime)
}
```

So I have only question. Which of the branches shows the right behavior?

**Comment by benjamn** [comment]
The right behavior is for `prettyHrtime` to have `let` scope instead of `var` scope. In other words, `ecmascript@0.6.3` is correct.

Have you tried updating to Meteor 1.4.3.1?

**Comment by benjamn** [comment]
If you're not ready to upgrade to Meteor 1.4.3.1, then you can get the old behavior back by putting `ecmascript@=0.6.1` in you `.meteor/packages` file. The automatic upgrade to 0.6.3 included more changes than expected, though the difference you've identified in this issue is probably the most surprising of them.

We'll be able to control automatic package version updates better in future Meteor releases (that's part of what Meteor 1.4.3 did, but that doesn't help with 1.4.2.x unfortunately).

Sorry for the disruption!

**Comment by dolgarev** [comment]
Many thanks! You can close this issue.
