### ISSUE TITLE
Feature Request: "meteor upgrade" from the command line

### ISSUE THREAD

**Issue by camstuart** [meteor/meteor#8371]
My existing projects notify me when a new release or patch for meteor is available and instruct me on how to "update" my project, EG: `meteor update` But this applies to the meteor version on that particular project only.

I would like to be able to "upgrade" my meteor installation without having to locate and use the curl command.

Instead I would issue: `meteor upgrade` to upgrade to the next version (possibly with a prompt telling me my current version, what version I would end up with, and a confirmation "This will upgrade your installed meteor version, are you sure?")

For the moment, I have an alias in my shell environment: 
```bash
alias meteor-upgrade='curl https://install.meteor.com/ | sh'
```

But of course, this is not a natural command, and I often forget it's syntax :\

**Comment by abernix** [comment]
You don't have to locate and use the `curl` command – you can just run `meteor update` outside of your application and it will update your global installation.  In fact, this would be better than using `curl` as it won't delete you're previously installed Meteor and cached packages (which are frequently still needed unless you've updated every app you develop on).

**Comment by camstuart** [comment]
Thanks @abernix
