### ISSUE TITLE
insertMany support

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8377]
Mongo 3.2 seems to have moved to a new naming model: [`insertOne`](https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/), [`insertMany`](https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/), and [`updateOne`](https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/), [`updateMany`](https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/) (replacing the `multi` flag).  It would be nice if `Collections` interface could support this alternative too.  (For example, I've been burned before by not specifying `multi: true`, but am much less likely to forget with `updateOne` and `updateMany`.)  The main feature addition here would be support for `insertMany` (as requested in #1255), at least on the server.

Here is some simple tested CoffeeScript that implements `insertMany` when not specifying a callback (mimicking the existing code for `insert`).  I or someone else can turn this into a fuller PR, but I thought I'd start with this.

```coffeescript
Mongo.Collection.prototype.insertMany = (docs) ->
  if @_isRemoteCollection()
    throw new Error "insertMany supported only on server"
  unless docs
    throw new Error "insertMany requires an argument"
  ## Shallow-copy the documents in case we generate IDs
  docs = (_.extend {}, doc for doc in docs)
  for doc in docs
    if doc._id?
      if not doc._id or not (typeof doc._id == 'string' or doc._id instanceof Mongo.ObjectID)
        throw new Error "Meteor requires document _id fields to be non-empty strings or ObjectIDs"
    else
      doc._id = @_makeNewID()
  @rawCollection().insert docs
  (doc._id for doc in docs)
```

**Comment by lorensr** [comment]
I agree it would be good to mirror the current Mongo API and provide all four methods.

**Comment by hwillson** [comment]
Thanks for the feature request @edemaine, great idea! If no one else has started working on this, I'll take a crack at it.

**Comment by edemaine** [comment]
@hwillson Great!  I haven't started implementing beyond the code above, so go ahead.  Happy to review or help out.

**Comment by mitar** [comment]
But for `insertMany` we could also then extend the `insert` itself to accept an array as the first argument, to satisfy #1255 as well?

**Comment by mitar** [comment]
BTW, there is some logic for bulk inserting, so we should probably try to use that, instead of simply calling insert multiple times. So it should not be just a sugar around insert.

**Comment by hwillson** [comment]
@mitar Actually, I was thinking we'd go one step further and leverage the [Mongo driver's `insertMany`](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#insertMany) functionality directly (I've smoke tested it and it's working properly).

**Comment by mitar** [comment]
Hm, does this also work for Mongo 2.6? Or are we dropping support for it?

**Comment by hwillson** [comment]
It won't work for Mongo 2.6. We'll likely have to add a check / throw an error if people using 2.6 make `*One/*Many` calls. We could consider coming up with a backwards compatible approach for handling this (e.g. having `insertMany` really just make `insert` calls as needed), but I don't think that extra work would be worth it (especially since [Mongo 2.6 reached end of life](https://www.mongodb.com/blog/post/mongodb-2-6-end-of-life) last October).

**Comment by mitar** [comment]
Even 2.6 had a [bulk insert](https://docs.mongodb.com/manual/reference/method/Bulk.insert/). Even node driver had a simple way to do this batch inserting by simply passing [an array](https://mongodb.github.io/node-mongodb-native/api-generated/collection.html#insert).

So I think that the easiest thing would be to:
* change `insert` to allow an array, in that case it preprocesses the array and passes it on to underlying driver ([this Meteor package seems to do the same](https://github.com/mikowals/batch-insert/blob/master/batch-insert-server.js#L129)); this should work with any Mongo database, to my understanding
* add insertOne and insertMany, which also calls underlayaying insertOne and insertMany

**Comment by hwillson** [comment]
Thanks for your input @mitar - I know about the bulk insert and will definitely consider it, but I wasn't planning on changing `insert`'s behaviour with the changes I'm prepping for this issue. It might be nice to first nail down the modern day Mongo `*One/*Many` functions to address this feature request, then consider modifying `insert` to work with arrays in a separate PR (against issue #1255).

**Comment by MohmadAyman** [comment]
Hi guys,
I'm interested in contributing, I've tested an insertMany and an insertOne functions, and they both works only on the server, is that to start a PR with?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=insertMany%20support&body=Migrated%20from:%20meteor/meteor%238377) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
