### ISSUE TITLE
Reduce oauth state size

### ISSUE THREAD

**Issue by cncolder** [meteor/meteor#8385]
Since the readability of json in state is not important. So I think we can reduce its size.

Currently, state generate by:

<https://github.com/meteor/meteor/blob/b8852dd7cc2909be39eab766b57954e225043b68/packages/oauth/oauth_client.js#L41>

A normal example show how big:

```js
// current
> encodeURIComponent(Base64.encode(JSON.stringify({
      loginStyle: 'redirect',
      credentialToken: Random.secret(),
      isCordova: false,
      redirectUrl: 'http://www.example.com'
}))).length
198

// short key
> encodeURIComponent(Base64.encode(JSON.stringify({
      l: 'redirect',
      t: Random.secret(),
      c: false,
      r: 'http://www.example.com'
}))).length
140

// skip Cordova
> encodeURIComponent(Base64.encode(JSON.stringify({
      l: 'redirect',
      t: Random.secret(),
      r: 'http://www.example.com'
}))).length
130

// short login style
> encodeURIComponent(Base64.encode(JSON.stringify({
      l: 'r',
      t: Random.secret(),
      r: 'http://www.example.com'
}))).length
124

// numeric login style, 1 = popup, 2 = redirect
> encodeURIComponent(Base64.encode(JSON.stringify({
      l: 2,
      t: Random.secret(),
      r: 'http://www.example.com'
}))).length
118

// even custom credentialToken
> encodeURIComponent(Base64.encode(JSON.stringify({
      l: 2,
      t: Random.id(),
      r: 'http://www.example.com'
}))).length
80
```

Why I care this size?

Because WeChat(most used in China) oauth2 limit state <= 128 bytes.

**Comment by cncolder** [comment]
I publish a new package. [colder:oauth-short-state](https://atmospherejs.com/colder/oauth-short-state). I wish this can help another.

**Comment by abernix** [comment]
Any idea why WeChat enforces that 128-byte rule?  Is that a part of the OAuth specification?

How can we be sure that a longer `redirectUrl` won't be used and break this under a different circumstances?  (Say, if someone has Meteor deployed under a subdirectory: `https://somedomainname.com/developers/oauth/`)

**Comment by cncolder** [comment]
@abernix Yes you are right. WeChat break specification. I understand this is not meteor issue.

Please close this issue.

My package cannot resolve all. If someone want integrate meteor and WeChat. He must care redirectUrl length.

**Comment by abernix** [comment]
Sorry!  Happy to discuss other solutions, but I don't think that just shortening the variable names is the right solution.  Hopefully your package will help those who need it!
