### ISSUE TITLE
Provide options.checkKeys support for LocalCollection's (Minimongo)

### ISSUE THREAD

**Issue by hwillson** [meteor/meteor#8386]
This feature request comes from the discussion in meteor/meteor#3786. The Mongo restricted field characters that were put in place to address that issue are unfortunately hampering people that are leveraging `.`'s in field names, within `LocalCollection`'s. Since the [Mongo driver supports a way to disable the special character check](https://mongodb.github.io/node-mongodb-native/api-generated/collection.html#insert), it would be helpful if Minimongo supported this functionality as well.  

It's important to note that `options.checkKeys` should only be supported for `LocalCollection`'s, and that it should be `true` by default.

**Comment by mitar** [comment]
Hm, but MongoDB still documents that this is a restriction: https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

**Comment by hwillson** [comment]
Yes it does, but the Mongo driver itself provides a way to disable that restriction. We originally took the hard-lined approach of restricting `.`'s to line up with Mongo's recommendations, but that has unfortunately caused some grief for developers who were relying on being able to use `.`'s with `LocalCollection`'s (so not directly using Minimongo to eventually feed into Mongo, but more like a client side cache). There is a fair bit of back and forth discussion about this in #3786, but the consensus was that we should leverage the Mongo driver's ability to shut this restriction check off.

**Comment by mitar** [comment]
But how do then queries work? If I do `{$set: {update.field.with.dots: 'foobar'}}`, how can Minimongo know how to process this?

**Comment by hwillson** [comment]
The complaints against the change we made are for inserting only (this is alluded to in https://github.com/meteor/meteor/issues/3786#issuecomment-280386957). So for now we can likely just limit `options.checkKeys` support to insert only (even though it is supported on updates within the Mongo driver).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20options.checkKeys%20support%20for%20LocalCollection's%20(Minimongo)&body=Migrated%20from:%20meteor/meteor%238386) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
