### ISSUE TITLE
Feature Request: Moving `node_modules` to `./meteor`, and auto-installing them

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#8387]
I think the changes that NPM/ES6 brought to Meteor are nice, but I have not fully brought into them because I'm pretty happy with Meteor as-is.

Every time I create a new app, I have to run `meteor npm install --save babel-runtime` and then have the `node_modules` folder in my root directory. 

Would it be of interest to hide the `./node_modules/` in the `.meteor/` folder and to auto-install and save NPM packages where possible? I thought it might feel a bit more magical like before.

**Comment by cncolder** [comment]
And then another tools cannot work.

**Comment by stubailo** [comment]
`node_modules` are a completely unavoidable aspect of JavaScript development in today's world, I'm not sure making Meteor the only tool in the world that hides them from you would be a big benefit.

**Comment by stubailo** [comment]
By the way, as of 1.4.3 they come pre-installed so you shouldn't have to run `meteor npm install` manually right after `meteor create`

**Comment by msavin** [comment]
Nice. 

Thanks for informing me, going to close this up.
