### ISSUE TITLE
Make core NPM-installable

### ISSUE THREAD

**Issue by sethmurphy18** [meteor/meteor#8393]
So, I have been using Meteor for quite some time, since Beta 0.6, and I have seen the platform come a long way. However, since I have started helping with Meteor, I have noticed something that may make Meteor as a platform better as a whole, and I think that it would also help with editing core packages, and keep things up to date. Why not make Meteor and its core packages installable via npm. For example, you could have a package, say `@meteor/meteor-cli` that is installed globally, and boom you now have the meteor cli tool. Then, Meteor could be extremely modular, and people could pick the parts they like, and ignore the one's they don't. Say, for example, I like `webpack` more than `isobuild`, I could simply uninstall `@meteor/isobuild` and install `webpack`. It would be a massive undertaking, but I think it would make the platform much better. Just my two cents, though. If this does happen, I would be happy to help with the efforts and start working toward moving the packages from Meteor packages to NPM packages.

**Comment by sethmurphy18** [comment]
On a side note, a change like this would remedy a lot of the major issues that are encouraging pull requests.

**Comment by abernix** [comment]
I'm not sure if there is another issue to track it already so I will leave this open but this is already on the Meteor [`Roadmap.md`](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm) and has been the plan for a [while now](https://github.com/meteor/meteor/pull/7072).

**Comment by sethmurphy18** [comment]
You are very right, it will also create a ton of problems, but it *should, in theory,* be better in the long run, if for no other reason than deployment. What is the current part of Meteor that MDG is trying to convert and are PR's needed?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20core%20NPM-installable&body=Migrated%20from:%20meteor/meteor%238393) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
