### ISSUE TITLE
Unexpected mongo exit code 14. Restarting. Unspecified unrecoverable error. Exit was not clean

### ISSUE THREAD

**Issue by harrydengchao** [meteor/meteor#8396]
* I follow the example of the document to run, encountered this error, I did not find the relevant solution in the Issues, I did not solve this problem.
* Who knows this solution?

```shell
root@71fce9b78899:/web/simple-todos# meteor --allow-superuser

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your permissions, run the following
command from the root of your project:

  sudo chown -Rh <username> .meteor/local

[[[[[ /web/simple-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
Unspecified unrecoverable error. Exit was not clean
root@71fce9b78899:/web/simple-todos#
root@71fce9b78899:/web/simple-todos#
root@71fce9b78899:/web/simple-todos# meteor --version --allow-superuser

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your permissions, run the following
command from the root of your project:

  sudo chown -Rh <username> .meteor/local

Meteor 1.4.2.7
root@71fce9b78899:/web/simple-todos#
root@71fce9b78899:/web/simple-todos# uname -a
Linux 71fce9b78899 4.9.8-moby #1 SMP Wed Feb 8 09:56:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@71fce9b78899:/web/simple-todos#
root@71fce9b78899:/web/simple-todos# node -v
v6.9.5
root@71fce9b78899:/web/simple-todos# npm -v
3.10.10
```

**Comment by harrydengchao** [comment]
try removing the local db folder then running meteor again like this:
```bash
rm -r .meteor/local/db folder
meteor
```
Still can not work

**Comment by abernix** [comment]
Do you have any `/tmp/mongodb-*` files? What if you stop Meteor, delete them, and try again?  Is there another Mongo running (`ps wwax | grep mongo`)? 

Also, in case it's not clear from the above messages, you should consider whether you really need to run Meteor as `root` (superuser).

**Comment by harrydengchao** [comment]
@abernix Hi
I was running in the Docker, I think it can be implemented with root. But it seems that my idea is wrong? It still does not work.
```shell
root@0104a9d8b9c5:/web/simple-todos# rm -r /tmp/mongodb-*
root@0104a9d8b9c5:/web/simple-todos# ps wwax | grep mongo
   488 ?        S+     0:00 grep --color=auto mongo
root@0104a9d8b9c5:/web/simple-todos# ps wwax | grep mongo
root@0104a9d8b9c5:/web/simple-todos# ps wwax | grep mongo
root@0104a9d8b9c5:/web/simple-todos# rm -r .meteor/local/db
root@0104a9d8b9c5:/web/simple-todos# meteor --allow-superuser

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

[[[[[ /web/simple-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
Unspecified unrecoverable error. Exit was not clean
```

**Comment by abernix** [comment]
@harrydengchao Do you have your locale set up properly on that Docker instance?  What happens when you run `locale`?

You may need to add this (or another locale besides `en_US`) to your `Dockerfile`:
```
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
```

Also, try just launching Mongo (from the Meteor bundle), directly and see if you get any helpful messages:

    ~/.meteor/$(dirname $(readlink "$HOME/.meteor/meteor"))/dev_bundle/mongodb/bin/mongod

**Comment by harrydengchao** [comment]
@abernix I follow the method of your operation. Very surprised, I seem to find the reason.
* Docker data may be the problem, I was the directory under Windows mapping to Docker. And then into the Docker in the mapping directory, create Meteor project, start is a failure. However, I created a directory directly in the Docker, and then created the Meteor project, the boot was successful.
* So, I guess it is cross-file system compatibility issues.
---
* In the data volume： 
```shell
root@533c53675f57:/web/simple-todos# ~/.meteor/$(dirname $(readlink "$HOME/.meteor/meteor"))/dev_bundle/mongodb/bin/mongod
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] MongoDB starting : pid=348 port=27017 dbpath=/data/db 64-bit host=533c53675f57
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] db version v3.2.6
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] modules: none
2017-02-22T10:55:49.422+0000 I CONTROL  [initandlisten] build environment:
2017-02-22T10:55:49.423+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-22T10:55:49.423+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-22T10:55:49.423+0000 I CONTROL  [initandlisten] options: {}
2017-02-22T10:55:49.429+0000 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
2017-02-22T10:55:49.430+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
```
---
* Create a directory within the Docker
```shell
root@9aef81f448af:/web1/simple-todos# ~/.meteor/$(dirname $(readlink "$HOME/.meteor/meteor"))/dev_bundle/mongodb/bin/mongod
2017-02-22T10:55:57.021+0000 I CONTROL  [initandlisten] MongoDB starting : pid=488 port=27017 dbpath=/data/db 64-bit host=9aef81f448af
2017-02-22T10:55:57.021+0000 I CONTROL  [initandlisten] db version v3.2.6
2017-02-22T10:55:57.021+0000 I CONTROL  [initandlisten] git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
2017-02-22T10:55:57.021+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-22T10:55:57.021+0000 I CONTROL  [initandlisten] modules: none
2017-02-22T10:55:57.023+0000 I CONTROL  [initandlisten] build environment:
2017-02-22T10:55:57.024+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-22T10:55:57.024+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-22T10:55:57.024+0000 I CONTROL  [initandlisten] options: {}
2017-02-22T10:55:57.032+0000 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
2017-02-22T10:55:57.032+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
```

**Comment by hwillson** [comment]
Hi @harrydengchao - it's a bit difficult to tell from your last message; has this issue been resolved?

**Comment by harrydengchao** [comment]
@hwillson I currently do not have a good solution. Temporarily in Windows to abandon the use of Docker

**Comment by gferreri** [comment]
This same error just popped up for me while spinning up my app in a TravisCI docker container (Ubuntu 14.04.5 LTS). Can the db path be overridden somehow when starting up meteor?

**Comment by harrydengchao** [comment]
@gferreri I'm not sure about that

**Comment by gferreri** [comment]
In my case, it ended up being a corrupted database in my .meteor/local/db folder. My Travis job was caching that directory and restoring it with each build, which led to the failure. As soon as I deleted the cache, the problem was resolved.

**Comment by micdahl** [comment]
Solution for me to run inside of docker with volume from Windows host is to use an additional mongo image instead of Meteors internal mongo db.

So this is my docker-compose.yml:

```
version: "3"
services:
  db:
    expose:
      - "27017"
    image: mongo
  meteor:
    build: ./meteor
    command: meteor --allow-superuser
    environment:
      LC_ALL: "C.UTF-8"
      MONGO_URL: "mongodb://db:27017/"
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/app
    working_dir: /home/app
```

And my Dockerfile:

```
FROM ubuntu:latest
RUN apt-get update && apt-get install -y curl
RUN curl https://install.meteor.com/ | sh
```

**Comment by zhudong10** [comment]
the same with you, sobad

**Comment by Peeta586** [comment]
I have this issue, when I start a meteor app after one meteor app have been running. so I use 'ps -a' and 'kill -9 PID' to kill all of mongod processes. And then when I restart the meteor app, this issue disappeared.

**Comment by stvenyin** [comment]
![image](https://user-images.githubusercontent.com/32395964/54517106-c1b2f480-499b-11e9-8c4c-a1ee85843194.png)

**Comment by stvenyin** [comment]
![image](https://user-images.githubusercontent.com/32395964/54517174-e5763a80-499b-11e9-857c-5a81e7263bd5.png)

**Comment by stvenyin** [comment]
![image](https://user-images.githubusercontent.com/32395964/54517273-2e2df380-499c-11e9-9afc-90ca132973de.png)


Appear to this problem,

**Comment by trusktr** [comment]
What happens if we have a production application with this issue? Deleting the db cache worked for dev, but what about for production where we can't delete data? (It hasn't happened to me yet, but I'm curious in case it does, because for low-traffic production sites, using the local Mongo that ships with Meteor seems like a perfectly fine and easy solution).

**Comment by gabi-lee** [comment]
Here' the stackoverflow thread that related to this:
https://stackoverflow.com/questions/38988365/meteor-unexpected-mongo-exit-code-14-restarting-cant-start-mongo-server

HTH
