### ISSUE TITLE
The update of ecmascript cause issues

### ISSUE THREAD

**Issue by Themandunord** [meteor/meteor#8399]
Hi,

With the last version of ecmascript@0.6.3, a plugin for babel don't work anymore.
This package is https://github.com/ant-design/babel-plugin-import

With the version @0.6.1 of ecmascript, this plugin works great.

Do you have any idea ?

https://github.com/meteor/babel/issues/13
https://github.com/ant-design/babel-plugin-import/issues/117

**Comment by abernix** [comment]
What version of Meteor are you using?

**Comment by Themandunord** [comment]
Hi @abernix 

I use the version 1.4.2.6 at this moment. But same problem with 1.4.2.7

**Comment by abernix** [comment]
If you're using Meteor 1.4.2.x and experience problems like this you'll want to pin your `ecmascript` to 0.6.1 as the 0.6.3 version is only compatible with Meteor 1.4.3.x.  See some additional information on [this comment](https://github.com/meteor/meteor/issues/8369#issuecomment-279849310).

I'd also encourage you to try Meteor 1.4.3.1 and see if it works for you.  It's not currently marked as `recommended` (which means, it becomes the "Default" version for new Meteor installations), but it is believed to be stable and upgrading to Meteor 1.4.3.x from 1.4.2.x should be painless.

If you choose to stay on Meteor 1.4.2.x, you'll want to pin your `ecmascript` by putting `ecmascript@=0.6.1` in your `.meteor/packages` file.

**Comment by abernix** [comment]
Closing, but happy to reopen if that doesn't fix it for you!

**Comment by Themandunord** [comment]
@abernix Thanks, but with Meteor 1.3.1 the babel plugin still not works :/

**Comment by abernix** [comment]
Will you please provide a reproduction repo as instructed in [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)?

**Comment by Themandunord** [comment]
@abernix No problem. I will do that :+1:

**Comment by Themandunord** [comment]
@abernix Here the repo : https://github.com/Themandunord/babel-error
I take the meteor chef base to make this repreoduction app , and I remove many things to keep the repo small.

Tell me if it not necessary to reproduce the bug :)

**Comment by klaussner** [comment]
I think Babel plugins that process `ImportDeclaration`s no longer work since [this commit](https://github.com/meteor/babel/commit/c8815d26f184d2dcae7bdfbeb2190b55337e9092) because `import`s are converted to `module.export` calls before Babel transpilation.

**Comment by abernix** [comment]
@Themandunord Considering `import` statements are already transpiled to `require` statements, what do you need/use `babel-plugin-import` for?

**Comment by Themandunord** [comment]
@abernix it's explain here : https://github.com/ant-design/babel-plugin-import

 It's to avoid to load all components. 
And load css (or less) file.

**Comment by Themandunord** [comment]
@abernix, nous updates ?

**Comment by abernix** [comment]
I haven't had an opportunity to look at your reproduction or analyze a possible fix yet.  Does your project work correctly if you just remove `babel-plugin-import`?

If you need to keep going at the moment, you should use Meteor 1.4.2.7 with `ecmascript@=0.6.1` in your `.meteor/packages` file.

**Comment by Themandunord** [comment]
@abernix Yes for now, I use meteor 14.2.7. But it's not a solution :/

If I remove the babel plugin, the whole package is used, so it's not a good solution too :/

**Comment by lhz516** [comment]
I got the same problem here. According to this issue https://github.com/meteor/babel/issues/13 , it might be caused by the `reifyCompiler`. Hope this can be solved soon.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.4.3.3-beta.3` in your application directory. Please feel free to reopen this issue if it's not resolved for you.

**Comment by Themandunord** [comment]
Hi @benjamn, thanks for that. But when I update to the beta release, I still have the issue :/ 
@lhz516 Have you still got the problem too ?

**Comment by benjamn** [comment]
@Themandunord I definitely did test https://github.com/Themandunord/babel-error before I commented. Perhaps try `meteor reset` to be sure?

**Comment by Themandunord** [comment]
@benjamn I don't doubt your skills ;)
I will test on my other computer tonight, and I reply here :)

**Comment by Themandunord** [comment]
@benjamn Sorry, I don't have access to my computer last night... And I'm going to vacation this week. So I can't try to update my repo.
I will check it as soon as possible.

**Comment by abernix** [comment]
@lhz516 Are you still experiencing this problem after `meteor update --release 1.4.3.3-beta.4`?

**Comment by lhz516** [comment]
@abernix @Themandunord 

I just tested and it still doesn't work. These's still a warning message in the browser console:
```
You are using a whole package of antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
```

Env:
Meteor version: 1.4.3.3-beta.4
ecmascript package version: 0.7.1-beta.4

In `.babelrc`
```
{
  "plugins": [
    ["import", { "libraryName": "antd", "style": true }]
  ]
}
```
In `package.json`
```
···
"dependencies": {
    "antd": "^2.8.1",
    "babel-runtime": "^6.20.0",
    "bcrypt": "^1.0.2",
    "eslint": "^3.17.1",
    "indexof": "0.0.1",
    "meteor-node-stubs": "^0.2.5",
    "moment": "^2.17.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-helmet": "^4.0.0",
    "react-komposer": "^2.0.0",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "react-simple-di": "^1.2.0",
    "simpl-schema": "^0.2.3"
  },
"devDependencies": {
    "babel-plugin-import": "^1.1.1",
    "eslint": "^3.16.1",
    "eslint-plugin-meteor": "^4.0.0",
    "eslint-plugin-react": "^6.10.0"
  }
···
```
---
The expectation of using `babel-plugin-import` is to automatically transfer
```
import { Menu } from 'antd';
```
to
```
import Menu from 'antd/lib/menu';
import 'antd/lib/menu/style';
```

If you need a reproduction project, I can upload the repo to GitHub.

**Comment by abernix** [comment]
Reproductions always welcome!

**Comment by lhz516** [comment]
@abernix 

No problem. I just uploaded a reproduction https://github.com/lhz516/antd-meteor-1.4-babel-bug

**Comment by kvetoslavnovak** [comment]
I can confirm same results as @abernix

**Comment by fangjj** [comment]
I hit the issues in meteor 1.5.2_2, this is a  a reproduction [https://github.com/fangjj/antd-meteor-1.5-debug](url), please help me out! @benjamn

**Comment by fangjj** [comment]
I hit the issues in meteor 1.5.2.2, this is  a reproduction [https://github.com/fangjj/antd-meteor-1.5-debug](url), please help me out! @benjamn @abernix

**Comment by fangjj** [comment]
this issues still in meteor 1.6.

**Comment by avalanche1** [comment]
Same issue on 1.6.1

**Comment by hwillson** [comment]
Thanks @fangjj @avalanche1 - I'll re-open this for now so it doesn't get lost (but I haven't had a chance to verify / look into it).

**Comment by hwillson** [comment]
@fangjj Your reproduction doesn't seem to be available anymore.

@avalanche1 Do you have a reproduction that demonstrates this is still happening with Meteor 1.6.1?

**Comment by fangjj** [comment]
@hwillson i'm sorry, https://github.com/fangjj/antd-meteor-1.6.1-bug this is new repository for it.

**Comment by lhz516** [comment]
I'm glad that this issue is opened again.

In my understanding, `babel-plugin-import` should transform `import { Button } from 'antd'` to `import Button from 'antd/lib/button'` and one line of style importing. However, this plugin needs to run before `babel-preset-meteor`, because `babel-preset-meteor` transforms module import patterns to another shape. In a Meteor project, any Babel plugins in `.babelrc` will run after the Meteor presets. This will make `babel-plugin-import` no longer to work.

It would be great if there's a more flexible way to load custom Babel plugins.
