### ISSUE TITLE
Compiler plugin: use project-level node_modules

### ISSUE THREAD

**Issue by Akryum** [meteor/meteor#8400]
Vue templates are compiled with the [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) npm package, whose version is following the vue core one for each release. Problem is, Meteor compiler plugins must declare the exact version of each npm package they use. This means I have to update `akryum:vue-component` with a version bump each time a new Vue version is released and publish it. This also means developers can end up with a broken app with an `npm update` and they rely solely on me updating the meteor package in a timely manner, which is not ideal.

So, it would be great if Meteor compiler plugins could simply `import` any package in the project `node_modules` and warn the user if they are missing, in a `peerDepency` way (which we can do in standard Meteor packages).

**Comment by wojtkowiak** [comment]
Hey,
this is possible as long as you are compiling a file that resided in the root of the project. Check here https://github.com/meteor/meteor/issues/7451#issuecomment-234631874

**Comment by Akryum** [comment]
So it won't work when compiling files in local meteor packages?

**Comment by wojtkowiak** [comment]
Not really. What I have done to benefit from this is that I am creating a file in the project root directory and the plugin compiles that file. 
https://github.com/wojtkowiak/meteor-desktop/blob/master/plugins/bundler/bundler.js#L30
In my case, I actually need that file there but I do not see much harm in doing that only for the purpose of obtaining the `file.require` from that scope.

**Comment by Akryum** [comment]
This seems quite hacky to me. :/

**Comment by wojtkowiak** [comment]
Yeah, I totally agree that it is hacky. But, quoting Ben:
>Build plugins are built as standalone programs before the rest of the build process runs, because they modify the behavior of the rest of the build process, so there is unfortunately no opportunity for them to benefit from peer dependencies installed in the app.

So `file.require` should not be considered a public/encouraged API. At least it is possible now this way. In my case, I needed that so badly that I have accepted the price.

**Comment by Akryum** [comment]
It's unfortunate as in the general npm ecosystem, importing project-level peer dependencies is the way to go.

**Comment by stubailo** [comment]
One cool thing would be if Meteor build plugins could be defined inside npm packages - then they could easily load peer dependencies etc.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Compiler%20plugin%3A%20use%20project-level%20node_modules&body=Migrated%20from:%20meteor/meteor%238400) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
I think this is the same as this issue: #8905

(Which I find a bug, not a feature request.)

**Comment by mitar** [comment]
So has this ever been really resolved? Later I thought that this works now, but then I think I also still observed that it does not.
