### ISSUE TITLE
Custom error handlers for exceptions at app download time

### ISSUE THREAD

**Issue by domq** [meteor/meteor#8402]
It is currently hard to change what happens when user-supplied code (such as a `WebApp.addHtmlAttributeHook` hook) throws an exception during rendering of the HTTP-served application (I think "boilerplate" is the right terminology). Basically, one can only choose between a plain stack trace typeset with faux `text/plain` (using &lt;br&gt;s, courtesy [finalhandler](https://www.npmjs.com/package/finalhandler)), or an even more spartan ["An error message"](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L661) text for production.

Making the error-catching features of [connect](https://www.npmjs.com/package/connect) accessible to packages / the main app would allow people to at least set up "traditional" (non-single-page) HTTP error handlers.

**Comment by hwillson** [comment]
Closing as #8403 was merged - thanks!
