### ISSUE TITLE
Nested imports stopped working on 1.4.2.7

### ISSUE THREAD

**Issue by imajus** [meteor/meteor#8404]
After updating to Meteor 1.4.2.7 nested import directives doesn't work anymore:
```javascript
import { TestVar1 } from '/imports/server/server-only.js'; // This works fine
if ( Meteor.isServer ) {
  import { TestVar2 } from '/imports/server/server-only.js'; // This variable is not available at runtime
}
```
The bug reproduces on fresh Meteor 1.4.2.7 empty project created with `meteor create --bare`. 
Here's the repo: https://github.com/imajus/meteor-1.4.2.7-import-issue. The POI there are `/imports/server/server-only.js` and `/server/main.js` files. Expected behavior is for Meteor server to output to console "object" then "object", actual is "object" then "undefined".

Temporary workaround for existing Meteor projects I've found is:
```javascript
import { TestVar1 } from '/imports/server/server-only.js'; // This works fine
if ( Meteor.isServer ) {
  var { TestVar2 } = require('/imports/server/server-only.js'); // Now it's fine too
}
```

**Comment by klaussner** [comment]
Since version 0.6.3 of the `ecmascript` package, imported variables are scoped like `let` declarations (instead of `var` declarations), which means that `TestVar2` is only available in the `if` block. See issue #8369.

**Comment by imajus** [comment]
Ah, that's a shame. But I guess the issue can be closed then. Thank you for clarification!

**Comment by abernix** [comment]
You can still use `var` with `require` if you'd like!  However, `let` is definitely more correct for a nested `import`.
