### ISSUE TITLE
Meteor Cordova [Android] CORS problem

### ISSUE THREAD

**Issue by mroftalp** [meteor/meteor#8407]
`XMLHttpRequest cannot load https://www.domain.com/_timesync. Origin null is not allowed by Access-Control-Allow-Origin. Error syncing to server time`

Why is my origin null instead of http://meteor.local? And how to I fix this?

**Comment by MyBoon** [comment]
Wondering the same ... +1

**Comment by ramezrafla** [comment]
Can't comment on specifics but are you using BrowserPolicy?

**Comment by abernix** [comment]
@mroftalp @MyBoon What versions of Meteor are you using?

**Comment by hwillson** [comment]
We haven't heard back regarding more troubleshooting details, so closing for now. Thanks!
