### ISSUE TITLE
Error happening in cordova build android 

### ISSUE THREAD

**Issue by tgeorge1** [meteor/meteor#8408]
I am getting following error even after adding gradle.properties file in /user/.gradle and /ProjectName/platforms/android

I am creating project through GitCMD in my windows machine.

cordova version:6.5.0

ProjectOne>cordova requirements

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-23,android-24,android-25
Gradle: installed

-----------------------------------------------------------------------------------------------------
ProjectOne>cordova build android
ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk\
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
Subproject Path: CordovaLib

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.2.1.
     Required by:
         :android:unspecified
      > Could not resolve com.android.tools.build:gradle:2.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
               > Connect to 10.68.248.34:80 [/10.68.248.34] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.382 secs
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.2.1.
     Required by:
         :android:unspecified
      > Could not resolve com.android.tools.build:gradle:2.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.1/gradle-2.2.1.pom'.
               > Connect to 10.68.248.34:80 [/10.68.248.34] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
-------------------------------------------------------------------------------------------------------------------

**Comment by abernix** [comment]
Can you try this again using Cordova 6.4.0 (which is what Meteor uses and is packaged internally)?  If you still experience the problem, perhaps try using PowerShell or normal `cmd.exe`? And lastly, make sure you're using a version of Android SDK _before_ 25.3.x because of #8464 (currently still unresolved).

**Comment by mortezaahashemi** [comment]
I've got the same problem
How can this problem be solved?

**Comment by hwillson** [comment]
We haven't heard back regarding the comments made in https://github.com/meteor/meteor/issues/8408#issuecomment-295064016, so closing for now.
