### ISSUE TITLE
Meteor 1.5.0.beta.8 npm module seed_random throws error

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8409]
I played around with dynamic imports and looking forward to it!

However i found a problem:

I use seedrandom on the client. It can optionally use "crypto" on the server (and on the client), but that's not needed in my case. It has a try-catch around the require:

https://github.com/davidbau/seedrandom/blob/released/seedrandom.js#L232

when i load seedrandom with import(...) this will throw an error on the client "Cannot find module 'crypto'"

I could install meteor-node-stubs but that would bloat the app.

**Comment by benjamn** [comment]
Is the problem that the `meteor-node-stubs` version of `crypto` contains a lot of code? Installing `meteor-node-stubs` won't add any code to the client except for the stubs you import.

**Comment by benjamn** [comment]
Also, does this work with normal `import "seedrandom"`? I'm not sure why dynamic `import(...)` would behave differently here.

**Comment by macrozone** [comment]
hi @benjamn,

it works with just ` import "seedrandom"`. seedrandom trys to load crypto, fails, but the error is catched.

I guess that with import(...) you're scanning the imported modules for require(...) or so and try to evaulate these...?

i do not want to have crypto installed, because that is also quite big and not needed in my case.

**Comment by hwillson** [comment]
Hi @macrozone - is this still happening with a more recent beta version, like `1.5-beta.17`?

**Comment by macrozone** [comment]
@hwillson I did not have the time to check again, but I will check again as soon as i can.

**Comment by hwillson** [comment]
Since we haven't heard back regarding whether this is still an issue or not (see https://github.com/meteor/meteor/issues/8409#issuecomment-298417674), and since Meteor is now at 1.5.2, I'll close this off. Happy to re-open if this issue is still occurring (and you can ideally provide a reproduction - see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!
