### ISSUE TITLE
npm `.bin` links (e.g. `meteor yarn`) fail prior to first `meteor` run.

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#8410]
### Problem
This problem presents itself most often when using a command like `meteor yarn` or another `meteor npm install`-able command like `jsdoc`, in a CI (or similarly fresh) environment where a Meteor app is run for the first time, when the application being built is not the officially released/recommended version.  In other words, a different from the version installed from `install.meteor.com`.

This might present itself as:

    'yarn' is not a Meteor command.  See 'meteor --help'.

...when you've already run `meteor npm install -g yarn`.

### Why?
Basically, the `yarn` you installed went to the "officially recommended" version of Meteor instead of the version of Meteor that your app uses. Presently, a symlink (or junction, in Windows) is used to point an apps `.meteor/local/dev_bundle` to the appropriate version of Meteor based on its `.meteor/release` (version).  NPM "binaries",  such as `yarn`, which are not shipped natively with Meteor but instead installed into the `dev_bundle` by the developer (e.g. those created with `meteor npm install --global <package>`) are located via this `dev_bundle` link/junction.

Since `meteor npm <command>` [is a thin wrapper](https://github.com/meteor/meteor/blob/devel/tools/cli/dev-bundle-bin-commands.js#L18) around the NPM commands it avoids the normal [`ensureDevBundleLink`](https://github.com/meteor/meteor/blob/907e1d91833eace7e40cc1d796cc7f9d171ceab1/tools/project-context.js#L1442-L1464) which happens deeper in a project execution.  In fact, the `dev_bundle` needed might not even be installed yet.

### Workaround

This can be easily avoided by running `meteor --version` (or any other built-in `meteor` command), prior to the first `meteor <bin-command-like-yarn>`.

### Solution

We need to make the thin wrapper more aware of this and either provide a helpful error message (e.g. ```your `dev_bundle` is wrong, run `meteor` first!```), or have it be less-thin on some executions and perhaps have it go so far as installing the `dev_bundle`, then continuing with its thin-ness.

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
