### ISSUE TITLE
Yarn with Enzyme - Cannot find module 'crypto'

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#8411]
Works:
```
rm -r node_modules
meteor npm install
meteor test --driver-package practicalmeteor:mocha --port 3100
```
Doesn't:
```
rm -r node_modules
meteor yarn install
meteor test --driver-package practicalmeteor:mocha --port 3100
```
Produces:
```
Uncaught Error: Cannot find module 'crypto'
    at require (modules-runtime.js:133)
    at meteorInstall.node_modules.uuid.rng.js (modules.js:51443)
    at fileEvaluate (modules-runtime.js:207)
    at require (modules-runtime.js:130)
    at meteorInstall.node_modules.uuid.uuid.js (modules.js:51257)
    at fileEvaluate (modules-runtime.js:207)
    at require (modules-runtime.js:130)
    at meteorInstall.node_modules.enzyme.build.Utils.js (modules.js:3029)
    at fileEvaluate (modules-runtime.js:207)
    at require (modules-runtime.js:130)
```

Reproduction:
https://github.com/davidworkman9/enzyme-meteor-yarn-issue

**Comment by stubailo** [comment]
@davidworkman9 have you checked to see what is different about the `node_modules` structure you end up with?

**Comment by davidworkman9** [comment]
Yes. They both have the same packages, except Yarn **also** includes:
```
Base64
asn1.js
assert
base64-js
bn.js
brorand
browserify-aes
browserify-cipher
browserify-des
browserify-rsa
browserify-sign
browserify-zlib
buffer
buffer-xor
cipher-base
console-browserify
constants-browserify
create-ecdh
create-hash
create-hmac
crypto-browserify
date-now
des.js
diffie-hellman
domain-browser
elliptic
events
evp_bytestokey
hash.js
http-browserify
https-browserify
ieee754
indexof
miller-rabin
minimalistic-assert
os-browserify
pako
parse-asn1
path-browserify
pbkdf2
process
public-encrypt
punycode
querystring
querystring-es3
randombytes
ripemd160
sha.js
stream-browserify
timers-browserify
tty-browserify
url
util
vm-browserify
```

**Comment by ShinyLeee** [comment]
Facing the same issue.

This error happened in [This line in uuid](https://github.com/defunctzombie/node-uuid/blob/master/rng.js#L1) which be depended by Enzyme.

After compare the difference in `modules.js?hashxxxxx`, I found that `uuid` was placed before all `meteor-node-stubs` packages when use Yarn.

![image](https://cloud.githubusercontent.com/assets/13724426/24078435/b0bc7bd8-0ca8-11e7-98a2-0bf0b6db6e17.png)

**Comment by peterchoo** [comment]
@ShinyLeee Did you ever find a solution to this? I've run into it myself now.

**Comment by hwillson** [comment]
I've updated the original repro to use Meteor 1.5.2, updated the `meteor-node-stubs` dependency to 0.2.11, and re-tested. I can confirm this is no longer an issue. Closing - thanks!
