### ISSUE TITLE
Meteor Android App Internet connectivity issue

### ISSUE THREAD

**Issue by taislam** [meteor/meteor#8415]
Hi All. 

I am facing internet connectivity issue in my app. 
When the app is built on server that is pointed to localhost machine, it's work fine but when server is pointed to any other server, it fail's to connect to internet. App can connect to server but not able to get data from any other api.

Thanks

**Comment by hwillson** [comment]
Hi @taislam - sorry to hear you're having trouble! Unfortunately your issue description doesn't really supply any tangible details that we can help troubleshoot with. Please see  [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for details on how to effectively report a Meteor issue. Please post back with more specific technical details (and ideally a runnable reproduction) demonstrating the problem that your seeing. For more general help, please try posting on the [Meteor Forums](https://forums.meteor.com) and/or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). I'll close this issue for now. Thanks!
