### ISSUE TITLE
random.fraction is only 32 bits

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8421]
In JavaScript, we could have 52 bits of randomness stored in numbers. But it seems [random.fraction](https://github.com/meteor/meteor/blob/devel/packages/random/random.js#L144) uses only 32 bits. There are [ways to improve current function](https://stackoverflow.com/questions/13694626/generating-random-numbers-0-to-1-with-crypto-generatevalues) in this respect.

**Comment by stubailo** [comment]
Is there an application for which having that function return 52 bits of randomness would be significantly better than 32 bits?

**Comment by mitar** [comment]
I mean, in crypto? Guessing 32 bits is only 2^32 iterations.

**Comment by hwillson** [comment]
While it is interesting that we could get up to 52 bits of randomness (and with some hacking possibly 53 bits), I don't think changing `Random.fraction` will gain us much, for the following reasons:

1. The `random` package is pretty much just an internal package, and `Random.fraction` is only used in 2 places ([here](https://github.com/meteor/meteor/blob/b145c7ed4ea603d8e9f87c10da53c00141ebaf94/packages/ddp-client/stream_client_common.js#L39) and [here](https://github.com/meteor/meteor/blob/b145c7ed4ea603d8e9f87c10da53c00141ebaf94/packages/retry/retry.js#L49)). Neither one of these uses requires anything beyond the 32 bits of randomness `Random.fraction` currently supports (it's not being used for crypto). 

2. To get 52 bits of randomness we'd have to extract those 52 bits from two 32 bit blocks. That means we'd be slowing the `Random.fraction` function down (this slowdown might be insignificant with modern hardware, but every bit (see what I did there? 🙂) counts).

3. There are several cryptographically secure random number generators available via npm (like [xorshift](https://www.npmjs.com/package/xorshift)), that can handle 52 bits of randomness. `Random.fraction` is doing what it needs to do for the Meteor core, and developers who need something more extensive can find alternatives via npm.

Given the above, I don't know if there is much to do here. Maybe we can update the `random` README to mention the package is really intended for internal use?

**Comment by mitar** [comment]
> The random package is pretty much just an internal package

What? I am using it all around my code to generate random IDs using `Random.id()`. How else would one generate random IDs looking the same as other IDs in Meteor?

What I like about `random` is that it automatically uses native secure crypto if possible, both on client and server, and otherwise has a good fallbacks. I do not know if there would be really any slowdown both when used with native secure crypto or fallback mechanisms.

> Given the above, I don't know if there is much to do here. Maybe we can update the random README to mention the package is really intended for internal use?

I really feel that this would be a loss. Meteor is great because it has great core packages. I see a trend that you do not want to maintain those great core packages anymore. Random is definitely not just an internal package. It is pretty well documented here:

https://docs.meteor.com/packages/random.html

Making it an internal package would be a change. A sad change because I really think it is made exceptionally well. Here I am proposing how to make it even better, and in all those years using it, is really the only downside I have learned that it has. So I am not sure why improving it and making it perfect would not be a good idea. It would prevent me from having to have both random (because it is internal package) and some other extra package, so double the codebase, just to have good random source.

So my question is, because it feels like that, is this opposition just because you do not feel we should develop more this package, and there are not resource for it? What is preventing you from saying: OK, but pull requests welcome if somebody wants to take it on?

**Comment by klaussner** [comment]
I agree with @mitar that it shouldn't be marked as internal (mainly because of `Random.id`). But I also think that increasing randomness isn't really important for most users of the package.

If you need random numbers for crypto, it's probably better to not rely on a PRNG that can fall back to an algorithm that isn't cryptographically secure (even if it's unlikely). Instead, you could call `crypto.getRandomValues` directly or use a PRNG like Fortuna (implemented in [sjcl](https://github.com/bitwiseshiftleft/sjcl)), which can collect entropy from other sources such as mouse movement, for example, if `crypto.getRandomValues` is not available).

**Comment by hwillson** [comment]
Thanks for the feedback @mitar. I use this package in my code as well, so I understand where you're coming from. 

I guess I'm just questioning the need to make this specific change to `Random.fraction`, for purposes outside of Meteor core's needs, when there are already better (and more actively maintained) 3rd party options for handling this (via npm). 

> What I like about random is that it automatically uses native secure crypto if possible, both on client and server, and otherwise has a good fallbacks.

Yes, but be careful here - the "good fallback" is an implementation based on Alea that is NOT cryptographically strong (actually, it's just barely better than using `Math.random`). This fallback works for Meteor's purposes, but it shouldn't be used for crypto.

> Making it an internal package would be a change. A sad change because I really think it is made exceptionally well.

I was suggesting the idea of marking it as internal to at least let people know that the main intent of this package is to serve Meteor core's needs, but others are welcome to use it if it fits their needs. 

> So my question is, because it feels like that, is this opposition just because you do not feel we should develop more this package, and there are not resource for it? What is preventing you from saying: OK, but pull requests welcome if somebody wants to take it on?

I wasn't trying to imply an opposition to this - I'm just attempting to brainstorm this issue a bit further by questioning its necessity (and to hash out as many details as we can), before we can decide if it should be marked as `pull-requests-encouraged`. This was the only thing preventing me from marking this as `pull-requests-enouraged` - I'm just attempting to drive the discussion forward (as outlined in [Proposing your change](https://github.com/meteor/meteor/blob/devel/Contributing.md#proposing-your-change) section of the Contributing doc).

**Comment by mitar** [comment]
> Yes, but be careful here - the "good fallback" is an implementation based on Alea that is NOT cryptographically strong (actually, it's just barely better than using Math.random). This fallback works for Meteor's purposes, but it shouldn't be used for crypto.

A good point.

> I wasn't trying to imply an opposition to this - I'm just attempting to brainstorm this issue a bit further by questioning its necessity (and to hash out as many details as we can),

I understand it better now, thanks!

> I guess I'm just questioning the need to make this specific change to Random.fraction,

So I agree that there is no real reason why to do it. The only my reason is mostly: oh, we could do it, so why not. :-)

Maybe then instead we should document how many bits are there in fraction. I would maybe add to initial paragraph something that one should not use it when security guarantees are required, because of this automatic fallback.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=random.fraction%20is%20only%2032%20bits&body=Migrated%20from:%20meteor/meteor%238421) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
