### ISSUE TITLE
[Cordova] Can't start run android-device anymore

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#8424]
After upgrading to 1.4.3.1 I was forced to update my SDK tools. If I now try to run

<code>meteor run android-device</code> the building proccess exits with the following error:

    cordova-build/platforms/android/build/outputs/apk/android-debug.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1108650963.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]]

I'm trying to run the app on a Android 7.0 device.

**Comment by abernix** [comment]
Have you tried deleting your `.meteor/local/cordova-build` and trying again?  It's an entirely new platform, so you may want to consider doing:

    meteor remove-platform android
    meteor add-platform android

(and for `ios`, if necessary).

**Comment by dnish** [comment]
@abernix Just tried it, but that didn't work on the first run. I need also to reboot my dev machine to make it work. The funny thing is that I need to reboot on every upgraded Meteor project. So when I've upgraded my project, I need to do:

   meteor remove-platform android
   meteor add-platform android

-> reboot.

**Comment by dnish** [comment]
Have to reopen it, it happens from time to time again, without changing any configuration. Didn't happen before the Meteor update.

**Comment by hwillson** [comment]
This should be fixed as of Meteor 1.5.2. Thanks!
