### ISSUE TITLE
Email package splits lines incorrectly / upgrade mailcomposer

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8425]
Try this on Meteor server (without MAIL_URL set, so that it prints to stdout):

```javascript
Email.send({
  subject: "This is a very long email subject to illustrate how it gets split onto multiple lines"
})
```

The result is this:

```
I20170224-21:23:03.030(-5)? ====== BEGIN MAIL #0 ======
I20170224-21:23:03.030(-5)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20170224-21:23:03.031(-5)? MIME-Version: 1.0
I20170224-21:23:03.031(-5)? Date: Sat, 25 Feb 2017 02:23:03 +0000
I20170224-21:23:03.031(-5)? Subject: This is a very long email subject to illustrate how it gets split
I20170224-21:23:03.031(-5)?         onto multiple lines
I20170224-21:23:03.032(-5)? Content-Type: text/plain; charset=utf-8
I20170224-21:23:03.032(-5)? Content-Transfer-Encoding: quoted-printable
I20170224-21:23:03.032(-5)?
I20170224-21:23:03.032(-5)?
I20170224-21:23:03.033(-5)?
I20170224-21:23:03.033(-5)? ====== END MAIL #0 ======
```

Unfortunately, this behavior seems incorrect.  Specifically, there are 8 spaces before "onto multiple lines", but there should be only one.  According to [RFC822](https://tools.ietf.org/html/rfc822), "Unfolding is accomplished by regarding   CRLF   immediately  followed  by  a  LWSP-char  as equivalent to the LWSP-char."  So while I only asked for one space before "onto" in the subject, I got 8 instead.

Specifically, this results in an actual error when setting MAIL_URL, producing actual email, and reading it in an email client.  At least in Pine, the subject gets eight spaces in the middle, which looks rather silly.  I don't know for sure that it will render incorrectly in all email clients, but it certainly isn't following the RFC822 spec.

I tried to reproduce this error in `node` using `mailcomposer`, but it seems to implement RFC822 correctly:

```javascript
var MailComposer = require('mailcomposer')
var mc = new MailComposer()
mc.addHeader({subject: "This is a very long email subject to illustrate how it gets split onto multiple lines"})
mc.buildHeaders()
```

produces:

```
'Content-Type: text/plain\r\nMessage-ID: <67ed00a7-8695-b5b7-261b-af9d3b033ed5@ibis>\r\nSubject: This is a very long email subject to illustrate how it gets split\r\n onto multiple lines\r\nDate: Sat, 25 Feb 2017 02:31:57 +0000\r\nMIME-Version: 1.0'
```

I couldn't get Mailcomposer 0.1.15 (as used by Meteor) to work at all in Node.  Presumably the bug got fixed between 0.1.15 and the latest version, which is 4.0.1 (!).  Could we please upgrade?

**Comment by abernix** [comment]
Thanks for reporting this!  It would be amazing to get `mailcomposer` upgraded (especially if it would fix this for you) but this isn't high on the Roadmap right now so a community contribution would be awesome!  Would you be interested in helping make a [contribution](https://github.com/meteor/meteor/blob/devel/Contributing.md#making-changes-to-meteor-core) to Meteor by tackling this and submitting a pull-request?

For starters, it would involve bumping the version in [`packages/email/package.js`](https://github.com/meteor/meteor/blob/devel/packages/email/package.js) and obviously some testing, especially of the `accounts*` packages.

Let us know if this is something you could look into!

**Comment by abernix** [comment]
I've marked this as `pull-requests-encouraged` so if you can't look at it, hopefully someone can.  While `mailcomposer` seems to work for sending in general, the version gap is definitely substantial enough that it'd be nice to get that fixed ASAP. :wink:

**Comment by laosb** [comment]
Shall we just update the mailcomposer to 4.0.1? Is there any specific API changes that need to be applied to email package?

**Comment by abernix** [comment]
@laosb See my comment [above](https://github.com/meteor/meteor/issues/8425#issuecomment-282698674).  There's a reason why it's pinned and it needs to be investigated.

> Is there any specific API changes that need to be applied to email package?

Probably!  But that's part of investigating. :wink:

**Comment by edemaine** [comment]
My sense is that, while the API has changed, the Email package uses so little of the API that it's probably fine to just upgrade.  Just needs to be tested.  I haven't modified Meteor before, so I'm not familiar yet with the testing harness, so if others have time feel free; otherwise, I will try to look at this.

**Comment by abernix** [comment]
Agree on the API.

I haven't validated whether this can be reduced (maybe we can just remove some of  dependency?), but the increase is ~500KB.  It's a server-only package, so it's not a huge impact to the client, but it is a large increase.  Given this factor, it'd be reasonable to first consider an alternate package to use in its place, assuming there is something compatible.

**Comment by alfredjkwak** [comment]
Nodemailer https://nodemailer.com is quite popular if considering another package.

**Comment by edemaine** [comment]
Nodemailer seems reasonable, though its unminified size is 380K.  However, I'm not sure that EUPL 1.1 code is compatible with Meteor's MIT license, but I don't quite understand how NPM-included packages work in this regard...  Any experts?

> Nodemailer v3+ is licensed under the European Union Public License 1.1. Previous versions of Nodemailer are licensed under the MIT license. [[https://nodemailer.com/about/license/](https://nodemailer.com/about/license/)]

**Comment by edemaine** [comment]
Inspired by the [mimelib vs. mimelib-noiconv comment](https://github.com/meteor/meteor/blob/331e6e2c98fbad520a40e3f23039ed57c6d486be/packages/email/package.js#L7-L8), I found [nodemailer-noiconv](https://www.npmjs.com/package/nodemailer-noiconv), which is an old (0.2.4, 4 years old) version of nodemailer that seems to be smaller (176K) than the `mailcomposer@0.1.15` currently in Meteor (268K).  Unfortunately, it seems to have the same leading-whitespace bug.  (Test code with this API: `var nm=require('nodemailer-noiconv'); var e = new nm.EmailMessage({ subject: '...really long...' }); e.generateHeaders();`)

In fact, the root issue is with `mimelib-noiconv`: `require('mimelib-noiconv').foldLine('Subject: ...long...')` produces the space issue, while `require('mimelib').foldLines('Subject: ...long...')` does not.  Alas, `mimelib` is 500K larger than `mimelib-noiconv` (I think because of encoding tables).

**Comment by jykae** [comment]
@edemaine EUPL v1.1 compatibility https://joinup.ec.europa.eu/sites/default/files/5b/4e/20/General%20EUPL%20v1.1%20compatibility%20Matrix%20v08.pdf

Also wondered if it's compatible with MIT, compatibility matrix here looks all green for MIT.

How much other packages in Meteor actually depend on this? Could email package be just recommended for users in Meteor guide for example? I understood that Meteor wants to more npm way in future, is that correct?

**Comment by edemaine** [comment]
**Licencing:** `nodemailer` overs no advantages over `mailcomposer`, as they share most of the codebase, and the latter offers the API we want and an MIT license. Thanks for pointing out `nodenvelope`, but it is alas double the size of `mailcomposer`.  (Both, at their core, just use NPM package `buildmail`; `mailcomposer` is roughly the same size as `buildmail`, while `nodenvelope` is much larger.)

**Dropping email package:** I like the `email` package in the Meteor context as it makes it easy for server configuration via the `MAIL_URL` environment variable to specify the SMTP server, with a fallback to printing text, instead of writing code to open connection to server and manually fallback to text output.  No NPM package I've seen does this.  Furthermore, asynchronous calls to remote servers are difficult to do in Meteor, so I don't think it'd be easy to use an NPM package in place of `email` (though of course Meteor's `email` could change to an NPM package).

**My conclusion of the feasible options:**
  1. Upgrade to a newer mailcomposer
  2. Roll our own from scratch

The first choice is IMO reasonable, as `email` isn't a default Meteor package, so users can still make the choice about the size increase, and there doesn't seem a smaller alternative.  The second choice is feasible --- fundamentally, email isn't that hard to generate --- but obviously more work.  @abernix, let me know your thoughts.

**Comment by abernix** [comment]
@edemaine Thanks for the analysis.  As you said, the `email` package certainly offers benefits and I think we'd like to keep it around.  It sounds like updating `mailcomposer` to the latest version is the way to go here: any `Kb` weight here will be server-side and an MIT license would be preferred over the EUPL (which I'm still not clear on, though "I am not a lawyer" certainly applies here.  Alas.)

My vote here would be to move forward – for starters, by bumping the `mailcomposer` version and seeing what happens with existing tests.

**Comment by edemaine** [comment]
I've mostly finished this PR, including a bunch of new test cases, all now passing.  But there is a catch: the [simplesmtp](https://www.npmjs.com/package/simplesmtp) library we use to actually send email (not represented in the tests) relies on the old (0.1) mailcomposer API for getting the message as a stream, and sadly it is deprecated.  simplesmtp recommends migrating to [smtp-connection](https://www.npmjs.com/package/smtp-connection), but that is distributed under EUPL...  (All of these packages are written by the same person.  Perhaps I should write to him...)

**Comment by edemaine** [comment]
One option is to use [smtp-connection@3.2.0](https://github.com/nodemailer/smtp-connection/tree/v3.2.0) which is licensed under MIT...  Adds yet another 500K (because I don't see how to get smtp-connection and mailcomposer to share the nodemailer-shared package... maybe some versions match up).

**Comment by jykae** [comment]
Good deep dive @edemaine 👍  If you are able to combine some elegant & easy to use "email lite" version that is also MIT compatible stuff, maybe it would be worth to package it to npm as well?

**Comment by edemaine** [comment]
PR complete: #8495
