### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word 

### ISSUE THREAD

**Issue by infacq** [meteor/meteor#8426]
Version: **Meteor 1.3.2.4**

I hit this error when run meteor

```bash
let version = require('../package.json').version;
```
my Node version is `6.3.1` and NPM is `3.9.5`. NPM Package messed with the error is [Braintree Payment (2.0.2)](https://github.com/braintree/braintree_node). 

Any Idea what could cause this

**Comment by HenriBeck** [comment]
I would guess this is caused by 'let'

**Comment by abernix** [comment]
Meteor 1.3.2.4 uses Node 0.10.x; your system version of Node doesn't matter in development as `meteor` bundles it's own.  [Meteor 1.3.2.4 is quite old at this point](https://github.com/meteor/meteor/blob/devel/History.md#v1324-2016-04-20)!

NPMs are expected to be transpiled for a specific version of the Node engine and are not retranspiled by Meteor which would commonly result in double-transpilation.  The [`engines` property in the `braintree` NPM](https://github.com/braintree/braintree_node/blob/master/package.json#L19-L21) states that it is only for use in Node 4.x or higher so the transpilation that they've done is expected to work for that range of Node versions.

You should update your Meteor to 1.4.x (preferably a more recent version such as Meteor 1.4.2.7 or 1.4.3.1) or take care to ensure that any NPM modules you use support Node engine versions under 4.x.
