### ISSUE TITLE
Suggest workarounds for nested import when using TypeScript

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8428]
I'm having big issues with Meteor's nested imports in my TypeScript app. Namely: I can't use nested imports in my TypeScript app.

In my methods module (which is shared between client and server to enable latency compensation), I want to import a `utils` module that only makes sense on the server, e.g. because it deals with sending emails.

That's a pretty simple requirement, right? I, however, can't figure out a good way of doing that considering nested imports are non-standard and won't compile in TS.

 * Using `require` wrapped in `if (Meteor.isServer)` instead of `import` works but I lose the type checking, i.e., no-go.
 * Making the `utils` module available on client works but it's obviously not a great solution.

Are there any suggested workarounds please?

**Comment by abernix** [comment]
I'm not familiar with how you've implemented TypeScript in this scenario (perhaps you could elaborate?) but is this an IDE issue or an issue with TypeScript itself?

Aside from using `require(...)` instead of `import`, I'm not sure what to recommend aside from getting TypeScript to support an `allowImportExportEverywhere` in the way that the [Acorn](https://github.com/ternjs/acorn) or [Babylon](https://github.com/babel/babylon/) parsers do.

**Comment by realyze** [comment]
@abernix I'd say it's a generic issue when sharing code between client and server - which is one of the core propositions of Meteor hence my question here and not in TypeScript.

`allowImportExportEverywhere` would definitely work but I don't believe TypeScript will support that anytime soon (or at all considering it's non-standard). Which essentially means I can't share code between client and server if the server code imports a module that's server only.

If I use "raw" `require`, the returned module object will have type `any` which is not useful at all.

**Comment by stubailo** [comment]
Have you tried something like `import xyz = require('module');`? I feel like that still gives you type information. Or will that also not be allowed in a nested place?

**Comment by realyze** [comment]
Actually, I've just stumbled upon https://www.typescriptlang.org/docs/handbook/modules.html#optional-module-loading-and-other-advanced-loading-scenarios which I think is exactly what I need!

(BTW `import xyz = require('module');` has the same problem.)

**Comment by stubailo** [comment]
Wow, that's quite an interesting way to do it. As long as it works I suppose! Might be worth a PR to the typescript guide article.

**Comment by realyze** [comment]
Yeah, good idea, I'd be happy to contribute! I'm pretty sure I'm not alone struggling with this.

**Comment by msand** [comment]
How about isolating the email related logic to a separate server only method / file, and expose that in the appropriate place?

**Comment by realyze** [comment]
@msand But how would you expose it? Say I have a meteor method that adds a message to a thread and sends an email. How would you import the email sending logic into the shared module?

**Comment by msand** [comment]
Well, one possibility is using Meteor.methods() in a separate server only file and Meteor.call() from the shared module
http://docs.meteor.com/api/methods.html#Meteor-methods
http://docs.meteor.com/api/methods.html#Meteor-call

**Comment by realyze** [comment]
Well but then I wouldn't be able to do optimistic UI.

**Comment by msand** [comment]
Isn't the email logic independent of the optimistic UI? Have the shared method handle adding the message to the thread optimistically, and have the server side make a call to the email method if it succeeds. Or am I missing something?

**Comment by msand** [comment]
As in something like
shared.js
`Thread = new Mongo.Collection('thread');
Meteor.methods({
  add: function (message) {
    // .. Check input and auth, etc...
    return Thread.insert(message, err => {
      if (!err && Meteor.isServer) {
        Meteor.call('email', message);
      }
    });
  }
});`

server/email.js
`Meteor.methods({
  email: function (message) {
    // .. Check input and auth, etc...
    // Handle email
  }
});`

client/addMessage.js
`module.exports = message =>Meteor.call('add', message);`

**Comment by realyze** [comment]
Oh sorry, I misunderstood what you were proposing. Your approach would work but it doesn't solve my problem which is that I want to preserve TS type information. The issue isn't the conditional `require` call itself (I can still do that) but rather how to keep the types and really it seems that reference elision and `typeof` is the only way to go. I [blogged about it](http://ideasintosoftware.com/typescript-conditional-imports/), it's not too bad to do it that way.

**Comment by hwillson** [comment]
It doesn't look like there is anything left to do here (a solution was found in https://github.com/meteor/meteor/issues/8428#issuecomment-282920657), so closing. Thanks!
