### ISSUE TITLE
Document Meteor.apply option throwStubExceptions

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#8435]
It would be nice if the `throwStubExceptions` would be [documented as argument for `Meteor.apply`](https://docs.meteor.com/api/methods.html). I found it in a debug session (wondering how and why the simulation does not throw errors).

see https://github.com/meteor/meteor/pull/4202#issuecomment-283070221

**Comment by abernix** [comment]
This should be released when Meteor 1.4.3.2 is released (and is fixed in `devel` now).  Thanks for reporting this!
