### ISSUE TITLE
Npm.depends docs should mention that it takes SHA URLs

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#844]
Feature request: on engine branch, support git repositories in `Npm.depends`, in a same manner as they can be specified in `package.json` in node.js apps.

**Comment by xaiki** [comment]
can we please reconsider this one ?
I'm develloping a meteor app and an npm module hand in hand, and for dev time, it's actually great to be able to pull a git branch for the npm part everytime I change something in the code using it.

wouldn't a big fat warning © saying: "you are doing it wrong, please fix that before deploying" be a good compromise ?

**Comment by glasser** [comment]
We do now support any http/https URL which contains a 40-char sha.

**Comment by mitar** [comment]
Is this documented somewhere?

**Comment by glasser** [comment]
Looks like no.  We'll track this here as a doc [feature request](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).  Pull requests to improve our docs are always welcome!

**Comment by fwevans** [comment]
If you are looking for the exact syntax, this worked for me (example from https://github.com/meteorhacks/npm):
{
  "googleapis": "https://github.com/bradvogel/google-api-nodejs-client/archive/d945dabf416d58177b0c14da64e0d6038f0cc47b.tar.gz"
}

None of the other Git URL formats given in the NPM doc worked for me: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by pward123** [comment]
Any chance of supporting git+sha://git@github.com based urls?
I'm trying to do an npm.depends on a private github repo (not github enterprise)

**Comment by pward123** [comment]
I managed to work around the git+ssh issue by creating my own release of the tools per http://practicalmeteor.com/using-meteor-publish-release-to-extend-the-meteor-command-line-tool.

Thanks to MDG for such an awesome tool and @rbabayoff for his very useful docs!

For those that are interested. You can try out the change with

```
meteor --release pward123:METEOR@1.1.0.3-4
```

The atmosphere package can be found at https://atmospherejs.com/pward123/meteor-tool

The changes I made are at https://github.com/pward123/meteor/tree/npm-git-ssh

**Comment by jzempel** [comment]
:+1: for supporting `git+ssh://...` private repo urls. Allowing `#tag` suffix in addition to `#commit` would be ideal.

**Comment by pward123** [comment]
There's been a number of requests for that feature.  The MDG response in each situation I've seen is that by forcing SHA1, it's harder for people that don't know what they're doing to mess it up and blame meteor. *paraphrased*

**Comment by newswim** [comment]
Not having this is now causing errors with my testing framework --- any word? @gschmidt

**Comment by tmeasday** [comment]
Note that https://github.com/meteor/meteor/pull/5562 is now merged!

**Comment by tmeasday** [comment]
This is fixed in the 1.3 betas, give it a try!
