### ISSUE TITLE
Idea: Emit a warning when publishing Meteor.users cursor without limiting `fields`

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8442]
Currently it's way too simple to accidentally publish the whole user document with all sensitive data (oauth tokens etc) to the client. And you literally never want to do this.

It would be reasonable to at least emit a warning in the server console when a user cursor without `fields` is published.

**Comment by mjmasn** [comment]
If this could have an option to be enabled for _all_ published cursors that would awesome. In my experience it's pretty rare you'd want to publish literally every field on a document to the client.

**Comment by mjmasn** [comment]
Looking at the code I think something could be added relatively easy around this line: https://github.com/meteor/meteor/blob/b24f7167e16dd21344c1a875523d39125df80fb2/packages/mongo/mongo_driver.js#L1195

Does anyone know if the Meteor users collection always called `users`? If so then a basic check could just be:

```javascript
if (!cursorDescription.options.fields && cursorDescription.collectionName === 'users') { 
  //... log something scary
}
```

**Comment by realyze** [comment]
@mjmasn Kudos for looking into this! My gut feeling is that this should be a responsibility of the DDP livedata package rather than Mongo, i.e., I'd put the logic somewhere [here](https://github.com/meteor/meteor/blob/84ed04b8f3b99cf16b5540f2e0193d47e4f8ccf6/packages/ddp-server/livedata_server.js#L1053).

Reason being that Mongo package should provide the API to collections but not mess with the "business logic" (because you can't know who will be calling the API and they might want to get all the fields).

**Comment by realyze** [comment]
BTW just a disclaimer: I'm not familiar with the livedata/DDP package so the above might be the wrong place. What I'm suggesting is that I'd put it somewhere in the `publish`code, maybe even wrap `Meteor.publish` and emit warning in some cases (aspect-oriented style, in a way).

**Comment by mjmasn** [comment]
@realyze good point, I did wonder if there was somewhere better, especially if `observeChanges` is used for any server-side-only stuff where the warning would be meaningless (I have no idea if that's the case or not). At a glance it looks like you should be able to access `res._cursorDescription` / `cur._cursorDescription` depending on single cursor/array of cursors and do the same thing from that part of the code.

**Comment by ramezrafla** [comment]
On the surface it's a good idea, but will add overhead to all livedata cursors (as we have to check each push). Why don't you have a client-side function that checks if `Meteor.users.find().count()` is not greater than 1 and emit error. My guess you will be doing that during testing.

**Comment by realyze** [comment]
@ramezrafla Hmmm I think your suggestion addresses a different concern. It's perfectly legit to have more than one user document published to the client. But it's virtually never legit to publish the _whole_ `user` document, you'll always want a subset of fields. It will add some overhead but negligible (really it's just a check if `fields` is used on the published cursor).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Idea%3A%20Emit%20a%20warning%20when%20publishing%20Meteor.users%20cursor%20without%20limiting%20%60fields%60&body=Migrated%20from:%20meteor/meteor%238442) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
