### ISSUE TITLE
Depending on a private scoped NPM packages in a Meteor package errors with not found

### ISSUE THREAD

**Issue by tyler-johnson** [meteor/meteor#8444]
I am attempting to upgrade from 1.4.1.3 to 1.4.3.1. I have a Meteor package that depends on a private, scoped NPM package. When I run `meteor upgrade` I get a typical NPM not found error, usually what is returned when NPM authentication is not sent with the request. I have also attempted to disable the package, upgrade, and then reenable the package, but Meteor always fails to fetch the package.

This was working 1.4.1.3 and seems to have reverted since then. This is related to #7810, but I am experiencing this with the latest release which *should* have support for this.

**Comment by dr-dimitru** [comment]
Hi @tyler-johnson 

How do you install/depend on local-npm-packages?
Could you post your code-sample?

**Comment by tyler-johnson** [comment]
I have a package in the `packages/` directory with a `package.js` file. This file contains a typical `NPM.depends()` line. The `@private/package` is a private package hosted on the main npmjs.org registry.

```js
Npm.depends({
  "@private/package": "1.2.3"
});
```

Now the package was already added and working with Meteor 1.4.1.3. So now to upgrade to Meteor 1.4.3.2 I run `meteor update`, however this is when Meteor gives me the 404 NPM error and refuses to update.

**Comment by dr-dimitru** [comment]
Try to change version to ["Git URLs as Dependencies"](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

```js
Npm.depends({
  "package-name": "url to git or archive with package"
});
```

**Comment by lnmunhoz** [comment]
@tyler-johnson I did this by adding a package.json file in to my package folder and installing manually using yarn or npm. The import works the same way. You just have to remember to run npm install on your package folder.

**Comment by hwillson** [comment]
@tyler-johnson Are you setting the `NPM_CONFIG_REGISTRY` environment variable?

**Comment by hwillson** [comment]
Closing for now but if this is still happening, please post back (with an answer to https://github.com/meteor/meteor/issues/8444#issuecomment-346477142) and let us know. Thanks!

**Comment by dr-dimitru** [comment]
@hwillson maybe this should be added to the docs? As I see - this is a quite popular question.

##### Local Atmosphere packages
Linking
```shell
# Go to your Meteor App directory
cd meteor_app
# Create and go to projects directory
mkdir projects
cd projects

# Option 1: Link cloned or other local package
ln -s /full/path/to/package/directory

# Option 2: Create new project
meteor create --package package-name
```

##### Install git/local NPM package
Git
```json
{
  "name": "my app",
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "fs-extra": "https://github.com/jprichardson/node-fs-extra/archive/4.0.2.tar.gz"
  }
}
```

Local:
```json
{
  "name": "my app",
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "fs-extra": "file:///full/path/to/local/npm/package"
  }
}
```

##### Add git/local NPM package to Atmosphere package
Git:
```js
Npm.depends({
  "fs-extra": "https://github.com/jprichardson/node-fs-extra/archive/4.0.2.tar.gz"
});
```

Local:
```js
Npm.depends({
  "fs-extra": "file:///full/path/to/local/npm/package"
});
```

**Comment by hwillson** [comment]
By all means @dr-dimitru - using local packages is touched on briefly in the Guide ([here](https://guide.meteor.com/writing-atmosphere-packages.html#local-packages) and [here](https://guide.meteor.com/writing-npm-packages.html#overriding-npm-packages)), but the docs can always be made better. If you don't mind opening an issue for this over in https://github.com/meteor/guide, that would be great - thanks!
