### ISSUE TITLE
Facility for build system to read/watch sections of `package.json`

### ISSUE THREAD

**Issue by mattmccutchen** [meteor/meteor#8445]
@abernix [suggested](https://github.com/meteor/meteor/pull/8165#issuecomment-281669239) that the Meteor build system should have an internal facility to read and watch sections of `package.json` files.  Currently proposed use cases:

- [Configuring automatic updating of app npm dependencies](https://github.com/meteor/meteor/pull/8165)
- [Detecting modules in the app's `node_modules` that are actually Meteor packages](https://github.com/meteor/meteor/issues/6791#issuecomment-208959968) (this one is different because the `package.json` file in question is not the app's)
- [Configuring eagerly loaded entry points for an app](https://github.com/meteor/meteor/issues/8341#issuecomment-278747356)
- [Configuring build plugins for an app](https://github.com/meteor/meteor/issues/7829)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Facility%20for%20build%20system%20to%20read%2Fwatch%20sections%20of%20%60package.json%60&body=Migrated%20from:%20meteor/meteor%238445) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
