### ISSUE TITLE
Unable to import npm packages in Meteor 1.4.3.1 using TypeScript

### ISSUE THREAD

**Issue by nick-lehmann** [meteor/meteor#8447]
My project is based on the Meteor-Angular2-boilerplate provided by @Urigo, using the command below.

```
meteor create --example angular2-boilerplate
```

I have tried to add several packages using `meteor npm install --save package`, namely 'cheerio' and `google`. Importing them via the shell, `import google from 'google'`, works like a charm. However, doing this in server side code does not work, giving me the first error messages on startup and the second when trying to execute it. The same happens for other modules, like cheerio.

```
both/helper/google.api.ts (4, 22): Cannot find module 'google'
````

```
/Users/nicklehmann/Workspace/IA/.meteor/local/build/programs/server/app/app.js:56
        google_1.google(query, function (err, res) {                                            //
                 ^
TypeError: google_1.google is not a function
    at GoogleAPI.testGoogle (both/helper/google.api.ts:11:9)
    at repl:1:-51
    at packages/shell-server/shell-server.js:443:25
    at /Users/nicklehmann/.meteor/packages/promise/.0.8.8.jfvzlb++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
```

Searching the web has not given me a suitable solution. Issue #7999 seemed to discuss a similar problem and suggests it is solved by now. 

I would be more than happy to provide any additional information.

**Comment by hwillson** [comment]
Hi @nick-lehmann - sorry to hear you're having trouble! Would you be able to create a small, runnable reproduction demonstrating this issue? A repro will greatly help with troubleshooting. For more information, see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug). Thanks!

**Comment by abernix** [comment]
@nick-lehmann Does `require('cheerio')` work or does it fail in the same way?  As @hwillson mentioned though, a reproduction would be helpful here.

**Comment by hwillson** [comment]
Hi @nick-lehmann - we haven't heard back regarding the additionally requested details, or a reproduction. Since this issue has been stale for a few weeks, I'll close it off. Happy to re-open if you're able to provide the requested info. Thanks!

**Comment by Adrillex** [comment]
Hi,
I re-open the issue because I think I have the same problem than @nick-lehmann .
I try to import 'youtube-api' module with the angular2-meteor-base but i get a "Cannot read property 'authenticate' of undefined" when trying to use it. The same program with meteor-agularjs is working well, that's why I think it's Typescript's fault.
here is a repo to try the very simple app : https://github.com/Adrillex/youtube-api-test
note that 'fs' won't import too

If you have any question I would be a happy to give you more informations
