### ISSUE TITLE
Connection authentication spam against MongoDB arbiter nodes

### ISSUE THREAD

**Issue by chrisckchang** [meteor/meteor#8449]
The Meteor project is affected by a bug was re-introduced in the 2.2.x version of the MongoDB driver which attempts to authenticate against an arbiter node. Per https://jira.mongodb.org/browse/NODE-927, driver version 2.2.23 or greater contains a fix.

**Comment by one-pereyra** [comment]
+1

**Comment by abernix** [comment]
The `mongodb` npm should be updated to `2.2.24` and released with Meteor 1.4.3.2.  You can try the latest 1.4.3.2 beta and help confirm right now by running:

    meteor update --release 1.4.3.2-beta.0

Please report back if you encounter any problems, and thanks for reporting this!  (And thanks @laosb for starting the pull request!)
