### ISSUE TITLE
Meteor integration with IDE needs "--noprogress" command line parameter

### ISSUE THREAD

**Issue by anstarovoyt** [meteor/meteor#8450]
Hi. We have integration with meteor using meteor cli and stdout and all work fine except one thing:
Stdout cannot correctly show 'progress' operations. 
**"Normal run":**
![image](https://cloud.githubusercontent.com/assets/1753282/23568291/e67bec62-006a-11e7-8b54-7456f321195c.png)

**"IDE run":**
![image](https://cloud.githubusercontent.com/assets/1753282/23568294/ecf864d0-006a-11e7-83b4-9f8e307d6684.png)

Can you provide a command line option or an env variable for forcing 'no progress' mode? 
Another solution is to rework current messages: log the long operation name and separate the progress indication from it.

**Comment by benjamn** [comment]
Try setting `METEOR_HEADLESS=1`, [like we do for CI tests](https://github.com/meteor/meteor/blob/56ad858559c4222fad7d44115a63c3c759fc2abe/scripts/ci.sh#L26). If that doesn't work, try the `--headless` command-line option.

**Comment by hwillson** [comment]
Hi @anstarovoyt - keep us posted if you notice any issues using one of the options outlined in https://github.com/meteor/meteor/issues/8450#issuecomment-284099112. Closing for now - thanks!
