### ISSUE TITLE
curl: (35) Server aborted the SSL handshake

### ISSUE THREAD

**Issue by HyperSimon** [meteor/meteor#8459]
OS: macOS 10.12.1 with Item2

<img width="829" alt="2017-03-06 11 17 20" src="https://cloud.githubusercontent.com/assets/9377192/23616132/ac145e6e-02c3-11e7-9d79-00917644d9e2.png">

I set up the system agent but still happened this error, is there any solution?

**Comment by abernix** [comment]
Are you connecting through a proxy or firewall that might be blocking SSL?

If you look at the install script (by simply browsing to https://install.meteor.com), you'll see that it's just (ultimately) running:

    curl https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.4.3.1/meteor-bootstrap-os.osx.x86_64.tar.gz

It would seem that you have a problem with your computer using SSL.  I'd recommend you take a look at [this StackOverflow](https://stackoverflow.com/questions/17742003/debugging-ssl-handshake) for debugging it – or search for others having the same error (search for: `curl server aborted the ssl handshake`).

You could skip the SSL, but that could be risky as you could end up downloading the file from an untrusted location.  You should understand those risks and how to mitigate them before doing so.

Sorry we can't be more help on this matter! Ultimately, you're going to find that this isn't Meteor's fault, but rather a problem with your computer.

**Comment by HyperSimon** [comment]
Thank you very much
