### ISSUE TITLE
extracting meteor-tool stuck windows 8.1 64x

### ISSUE THREAD

**Issue by Nemra1** [meteor/meteor#8460]
im trying to run Rocket chat developer version app in windows 8.1 64x 4GB RAM CORE i3
and stuck for 5 hours like this also i have 1024 kb/s internet speed and last v of 7z
![2017-03-07_041817](https://cloud.githubusercontent.com/assets/22897987/23638948/6839cc90-02ed-11e7-9a21-09c777cb89a3.png)

**Comment by abernix** [comment]
Can you give the output of `meteor --version` run from **outside** of an app directory?  For example, from your home directory instead of inside `rc53`?

**Comment by Nemra1** [comment]
@abernix abernix Meteor 1.4.2.6

**Comment by hwillson** [comment]
Thanks @Nemra1 - closing.
