### ISSUE TITLE
Broken link in https://guide.meteor.com/react.html#routing

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#8463]
"When using React Router in Meteor, you can follow roughly the same principles as when using Flow Router, but you should also consider the idioms outlined in React Router’s own documentation."

The last word is a hyperlink. The link is broken.

**Comment by hwillson** [comment]
Hi @paulincai - thanks for pointing this out. Would you mind opening an issue about this within the [Guide repo](https://github.com/meteor/guide) itself? Thanks again!

**Comment by paulincai** [comment]
Thanks a lot for pointing out the way to do it. From the place I was reading the documentation was not too obvious so I followed “Contact us”..etc.

It’s done. Great work guys, luv you.
