### ISSUE TITLE
Meteor build issue with some 3rd party packages

### ISSUE THREAD

**Issue by EmirGluhbegovic** [meteor/meteor#8471]
- version: 1.4.3.1
- main additional packages: react, react-dom, amCharts3, amCharts-export 
- I expect the amCharts-export feature to work as tested on a non-meteor project.

At the moment what I get is described in my resolved stackoverflow post:
http://stackoverflow.com/questions/42622507/amcharts-export-with-meteor-react-jsx/42689429#42689429 

-The solution we have is a workaround. I believe the issue has something to do with the way the npm package is made and how meteor builds it.
-Would like an opinion if there is a better way or is this a bug?

**Comment by abernix** [comment]
This is not the place to ask questions but rather a place to report bugs or features.  If you think you've found a bug, please help us fix it by providing a working reproduction (in the form of a basic Meteor app uploaded to GitHub and linked to here), as requested in [the instructions](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) when you opened this issue.  A link to a StackOverflow post is not appropriate.
