### ISSUE TITLE
 MongoError: no valid replicaset members found on Meteor 1.5-beta.10

### ISSUE THREAD

**Issue by josemanuelp** [meteor/meteor#8473]
I'm testing 1.5-beta.10 an application that runs perfectly on Meteor 1.4.x.

Just upgraded to 1.5-beta.10 without any changes but the application crash on startup.

`
W20170309-15:36:43.687(-4)? (STDERR) MongoError: no valid replicaset members found
W20170309-15:36:43.688(-4)? (STDERR)     at Object.Future.wait (/home/criptotec/.meteor/packages/meteor-tool/.1.5
.0-beta.10.1uiybdb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules
/fibers/future.js:449:15)
W20170309-15:36:43.688(-4)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
W20170309-15:36:43.688(-4)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_coll
ection_driver.js:4:16)
W20170309-15:36:43.689(-4)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20170309-15:36:43.690(-4)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
W20170309-15:36:43.690(-4)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:99:40)
W20170309-15:36:43.691(-4)? (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common
.js:23:18)
W20170309-15:36:43.691(-4)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
W20170309-15:36:43.692(-4)? (STDERR)     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
W20170309-15:36:43.692(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170309-15:36:43.692(-4)? (STDERR)     - - - - -
W20170309-15:36:43.693(-4)? (STDERR)     at [object Object]._onTimeout (/home/criptotec/.meteor/packages/npm-mongo/.2.2.16_1.1wbujxc++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/replset.js:684:33)
W20170309-15:36:43.693(-4)? (STDERR)     at Timer.listOnTimeout (timers.js:92:15)
`

My connection string is like the following:

`
MONGO_URL="mongodb://user:password@server1,server2,server3/database?replicaSet=apprs0&authSource=admin"
`

This connection string works perfectly on Meteor 1.4.x.

Any help is appreciated.

Thanks...

**Comment by abernix** [comment]
Have you compared the differences in version numbers of the `mongo` and `npm-mongo` packages?  Can you provide those version differences?  Have you looked at the actual `mongodb` version included in the `npm-mongo` package (which points to the actual [`mongodb`](https://github.com/mongodb/node-mongodb-native) package.  There have been a number of updates and upstream fixes to the mongo driver which we've included in more recent Meteor versions but may not be in Meteor 1.5 (yet, still beta!).

Also, there are a variety of versions of `mongodb` included in various 1.4.x releases and 17 different versions in the Meteor 1.4.x series, so could you be more specific about which versions are working perfectly? :)

**Comment by hwillson** [comment]
Hi @josemanuelp - we haven't heard back from you regarding the questions asked in https://github.com/meteor/meteor/issues/8473#issuecomment-286421332, so I'll close this issue for now. Happy to re-open if you're able to provide the requested details. Thanks!
