### ISSUE TITLE
 Error: Can't find npm module 'crypt' in meteor 1.4.3.1 when build tar ball then on the centos server

### ISSUE THREAD

**Issue by devqin** [meteor/meteor#8477]
47|gjbapp  | Error: Can't find npm module 'crypt'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
47|gjbapp  |     at Object.require (/alidata/www/gjb31/bundle/programs/server/boot.js:200:17)
47|gjbapp  |     at options.fallback (packages/modules-runtime.js:479:18)
47|gjbapp  |     at require (packages/modules-runtime.js:126:16)
47|gjbapp  |     at packages/modules.js:1900:15
47|gjbapp  |     at meteorInstall.node_modules.MD5.md5.js (packages/modules.js:2058:3)
47|gjbapp  |     at fileEvaluate (packages/modules-runtime.js:197:9)
47|gjbapp  |     at require (packages/modules-runtime.js:120:16)
47|gjbapp  |     at meteorInstall.imports.wechat.wxpay.js (imports/wechat/wxpay.js:4:11)
47|gjbapp  |     at fileEvaluate (packages/modules-runtime.js:197:9)
47|gjbapp  |     at require (packages/modules-runtime.js:120:16)

**Comment by benjamn** [comment]
Did you mean `crypto`?

**Comment by seanjsong** [comment]
@devqin I encountered exactly the same problem. I guess you installed the old MD5 module in your node_modules directory, but specified the new md5 module in your package.json. Delete the MD5 directory and run ```meteor npm i``` again work for me.

**Comment by abernix** [comment]
@devqin Does your 👍 on the above comment mean we can close this? :smile:
