### ISSUE TITLE
sshpk with 1.4.3.2

### ISSUE THREAD

**Issue by mokaid** [meteor/meteor#8483]
hello , 
Why the double slashes in the path ?
During deployment with mup 1.2.3
Error : path /bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv

is it a bug ? please advise

**Comment by abernix** [comment]
Thank you for trying to report a bug, but there is not nearly information provided here to help debug this or even begin to determine if this is a bug in your application, one of your `npm`s, `mup`, or anything else. This does not happen on a fresh Meteor project, built and ran with `node`, so we'd need more information to work with.

There are also not "double slashes" in the path which you provided – however, there _is_ a backslash (`\`) – is that what you mean?  Is there more to the error message?  Are you on Windows?  Is this an existing mup deployment?

You can see how I could ask questions all day without more information. :smile:

Please provide a reproduction [as requested](https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md) when you opened the issue and we'd be happy to help!

**Comment by hwillson** [comment]
Closing as we haven't heard back from your regarding the additionally requested information.
