### ISSUE TITLE
Is there native solution for desktop yet?

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#8484]
On meteor.com we see:

<img width="350" alt="screen shot 2017-03-14 at 13 21 58" src="https://cloud.githubusercontent.com/assets/870859/23896148/5d808bfa-08b9-11e7-9786-29d91152a9ad.png">

Ot is it just marketing?

**Comment by benjamn** [comment]
Desktop support is definitely more community-driven than the other platforms, but here are two projects that run Meteor within [Electron](https://electron.atom.io):
* https://github.com/electron-webapps/meteor-electron
* https://github.com/sircharleswatson/Electrometeor

**Comment by ethanwillis** [comment]
@artpolikarpov  https://github.com/wojtkowiak/meteor-desktop/ I've used the two projects benjamn listed along with arboleya's electrify. And this one is definitely the best way to do a meteor app with hot code push and autoupdating.

**Comment by hwillson** [comment]
For more specific details regarding how to best leverage Meteor on the desktop, I'd suggest continuing this discussion on the [Meteor forums](https://forums.meteor.com). There has been a lot of discussion on the forums regarding [Meteor + Electron based solutions](https://forums.meteor.com/search?q=electron) in particular, so community members should be glad to help answer any questions you have. Thanks for reaching out!

**Comment by artpolikarpov** [comment]
Got it! But now I think you can add "desktop and tv" to that sentence :)
