### ISSUE TITLE
Need option to install to an alternative directory.

### ISSUE THREAD

**Issue by JontomXire** [meteor/meteor#8489]
The instructions say to check if a there is already a similar existing issue - how without any sort of issue search (I cannot find it anyway).

I am trying to run Meteor on linux with an automounted NFS home directory with a pretty strict quota on it. I cannto install - it just hangs, presumably because either curl or the install script hits the quota limit (although I never get an email to say so) and so hangs waiting for a write to complete.

I find it very strange that the Meteor devs think everyone in the whole world will want to install Meteor to their home directory - and that every user on a system needs their own install!

Meteor needs a simple way to specify an alternative install directory, perhaps via an environment variable or something that can be picked up by both the install script and the meteor binary (which has somehow ended up in /usr/local/bin as well as ~/.meteor).

**Comment by abernix** [comment]
If you'd like to search existing issues, you can click the "Issues" tab and find a search box directly below it or use the "This Repository" - "Search"  box at the top of every page on the repo (and GitHub).

As to your request, while using a global install shared by multiple users might seem nice in some aspects, it would cause permissions issues for many users who might not be able to install things outside their home directory.  Meteor has no global configuration which would allow the location of the `.meteor` directory to be set, but you are welcome to move the Meteor installation wherever you would like, but currently, the `.meteor` directory does need to be in the home directory, and we currently have no intentions to re-work that, mainly as we start make considerations for a full [transition to npm](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm), which would solve this.

You should be able to easily work around it by just using a symlink: `ln -s /actual/path/to/meteor ~/.meteor`, but you'd need to let it install once and then move it to the `/other/path`, or you'd need to download the tarball (from the [`install.meteor.com` script](https://install.meteor.com/)) and extract it to where you'd like and then make the symlink to that location.

**Comment by hamlet** [comment]
Hi.
The install is actually easy as :
```
export HOME=/path/with/space/
curl https://install.meteor.com/ | sh 
export HOME=/home/user/
ln -s /path/with/space/.meteor/ ~/.meteor
```

Hope it can be useful for others with space-limited homes.
Regards
