### ISSUE TITLE
1.5-beta.11 - React is not defined

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#8490]
I created a bare app, removed blaze and jquery and added static-html. Installed react, and added a react component. Worked fine on 1.4.3.2. Upgraded to 1.5-beta.11 and I get "React is not defined" in the console on the browser. I have to add a single line that contains React in order to surpress this, in every component file. A line as simple as ```React;``` works.

**Comment by benjamn** [comment]
Is `react` in your `package.json` file (not just installed in `node_modules`)?

**Comment by abernix** [comment]
While I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Any way you could make this into an easy reproduction ala [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines?

**Comment by benjamn** [comment]
Or is this something to do with the fact that JSX gets compiled to code that assumes `React` is in scope?

**Comment by davidworkman9** [comment]
Yes react is in my package.json file. If I had to guess, somethings running over the code before it gets compiled from JSX, sees that the React import isn't used, and removes it. I've tried adding the JSX package, but it makes no difference. I'll work on a reproduction, it seems to be any and all components that don't use React outside of the ```<div></div>``` syntax though.

**Comment by davidworkman9** [comment]
I created a [reproduction](https://github.com/davidworkman9/react-undefined-meteor-1.5), it seems to only happen if I include both of these babel plugins:
```transform-class-properties``` and ```transform-dead-code-elimination```

I can have one, or the other, but not both.

**Comment by macrozone** [comment]
@davidworkman9 the same thing happens on meteor@1.4.3.2 when you add "transform-dead-code-elimination"

**Comment by davidworkman9** [comment]
I'm observing the same thing, but I know for a fact that I tested it on 1.4 when I opened this issue and it worked fine. In fact, I have it in another project of mine with no problems.

**Comment by benjamn** [comment]
Is this still a problem that Meteor can solve, or is it a bug in a custom Babel plugin?

**Comment by davidworkman9** [comment]
Under my testing it looks like you guys already solved it lol.  Beta 11 throws an error still but beta 19 doesn't throw the error anymore..

**Comment by benjamn** [comment]
I'll take it! 🤷‍♂️
