### ISSUE TITLE
Provide Rule to Avoid "Comment-Close-Lock" Barbarism.

### ISSUE THREAD

**Issue by lazaridis-com** [meteor/meteor#8492]
@abernix 

I understand that its difficult to say "yes, we are a bit sloppy, and our processes are essentially non-existent, at least for the docs".

But applying `comment-close-lock` is really not the way to go. Its similar to taping the mouth of a person. I personally categorize it as barbarism.

So, please, reopen issue #8368. I can then decide if I comment, or if I ignore your comment as an "typical open-source kiddo" thing.

There is no help for Meteor, if you don't accept your weaknesses, thus you can work on fixing them.

(and forgive me the ironic/sarcastic tone. Its my usual response to violence)

**Comment by abernix** [comment]
You can also have whatever interpretation of my actions you would like, but this is literally the wrong GitHub repo for a discussion about tutorials or docs and #8368 has passed the point of productivity.  Both of those are grounds for locking.  You are trivializing the work that we have to do (and already do) and pretending that you know better or that we are not aware of our flaws.  I do not have to spend time exclaiming Meteor's or my flaws to you or have you strong-arm me into making obvious admissions.  It's a waste of time.

I appreciated you bringing the deficiency in tutorial issue handling to our attention.  Those tutorial issues were not being actively handled (obviously) and I've now expressed gratitude several times for bringing it up.  I also already responded to [your request](https://github.com/meteor/meteor/issues/8368#issuecomment-279768467) to "get pinged" for new issues with an affirmative that I've taken care of it (and I have).

If you wish to provide feedback or review of open issues, submit helpful PRs (both of which you have done) or find other ways to offer meaningful contribution, it would be greatly appreciated (and is very much of great benefit, especially if you can take care of the other 600 issues in this repository which need to be addressed), but if you feel like continuing this unhelpful conversation, on the wrong repository, in the wrong forum, you'll likely be met with another "comment close lock".

**Comment by lazaridis-com** [comment]
Common @abernix , give your ego a little kick and reopen my beloved issue (which you have slayed brutally).

> especially if you can take care of the other 600 issues in this repository which need to be addressed

I will look at the older 20 or 50 (its my method of assessing a project). But first I have to see if the Meteor Project has a decent governance, which ensures that one developer cannot "play wild west" on the public project resources.

**Comment by benjamn** [comment]
To anyone who comes across this thread in the future, @lazaridis-com has been banned from contributing to repositories within the Meteor Development Group organization. This was my decision, as the tech lead of the Meteor project, after reviewing this thread and others in which @lazaridis-com attempted to shame @abernix and @hwillson for their responses to his contributions. Self-righteousness, sarcasm, and abusive language have no place in this project.
