### ISSUE TITLE
'meteor yarn' does not work with homebrew installed yarn

### ISSUE THREAD

**Issue by damonmaria** [meteor/meteor#8493]
I try to install `npm` packages globally as little as possible. One example is `yarn` which I install using homebrew (on Mac) instead. However, with yarn installed this way the `meteor yarn` command cannot find it.

### What version of Meteor you're using, and the platform(s) you're running it on
Meteor 1.4.3.1
MacOS 10.12.3
Homebrew 1.1.10

### What packages or other dependencies you're using
yarn 0.21.3

### The behavior you expect to see
`meteor yarn` to run yarn with the Meteor version of node

### The actual behavior
```
$ meteor yarn
'yarn' is not a Meteor command. See 'meteor --help'.
```

### Workaround
`meteor node $(which yarn)` does work but is obviously a lot harder to type.

**Comment by stubailo** [comment]
Is there a tangible benefit to use homebrew instead of npm install -g?

**Comment by damonmaria** [comment]
It's probably subjective. Homebrew I use to install so many utilities and it's easier to keep them all up to date with a single command. Yarn fits into that category for me. It just happens to be written in javascript. Most other npm packages that want to be installed globally are tied to a particular project, and generally work fine installed locally with the project. The only benefit I can think of installing globally is making the command line to invoke them simpler. But yarn has made that a bit nicer with avoiding the need for the `run` command. e.g. `yarn gulp`, `yarn serverless -- deploy`. 

For example, tools like `serverless` and `gulp` I install locally because I don't want a version change of a globally installed package to break a project when maintaining years down the road. Also, what version works with the project is not tracked in version control. Not such a problem for `yarn` which is pretty stable and backwards compatible but `serverless` and other packages are a completely different story.

**Comment by abernix** [comment]
I fully understand your hesitation in installing Node modules globally.  I think you'll be happy to know that Meteor doesn't interfere with your global installation at all – in fact, you don't even need to install Node or npm to use Meteor, as it ships with its own versions of both which are tested for compatibility.

It's important to make an important distinction here and mention an installation method that's not mentioned above: `meteor npm install -g yarn`.  That `-g`(lobal) flag might be confusing as this does _not_ just install `yarn` globally (on your computer), but rather within the installation of Meteor itself.  In fact, Homebrew, `npm install -g` and `meteor npm install -g` will likely yield installations of `yarn` in entirely different locations.

Using `meteor <command>`, doesn't just instruct a command to use Meteor's Node.js version, it explicitly tells `meteor` to search for (or install) modules within the Meteor installation.  In practice, this installation is located deep in your `$HOME/.meteor/packages/meteor-tool/<version>/<arch>/dev_bundle/lib/node_modules` directory.

If you **want** to use your global installation of `yarn` you should _not_ use `meteor yarn` at all.  However, this is not recommended as this puts the burden of making sure that you are using the correct version of Node.js on you as the developer.  (As of this writing, Meteor (v1.4.3.2) internally uses Node 4.8.0.)  If you just use `yarn`, you will be using the globally installed version of Node.js, which might be a conflicting version.

Ultimately, we can't safely make `meteor yarn` just use your Homebrew version (or other global version) without having Meteor confirm that the version of `yarn` that would be used would invoke the exact same version of Node.js that Meteor ships with.  The recommendation is to use `meteor npm install -g yarn` and then `meteor yarn`.

Hope this helps to explain.  Please close the issue if this helps resolve it for you – or happy to discuss further!

**Comment by damonmaria** [comment]
Thanks @abernix. I did not know that about `meteor npm install -g...`. 

At the moment I actually use a Bash alias: `alias myarn='meteor node $(which yarn)'`

This works because the yarn that homebrew installs is just a JS script:
```
$ head `which yarn`
#!/usr/bin/env node
/* eslint-disable no-var */
/* eslint-disable flowtype/require-valid-file-annotation */
'use strict';
// validate that used node version is supported
var semver = require('semver');
var ver = process.versions.node;
ver = ver.split('-')[0]; // explode and truncate tag from version #511
```

So if yarn is installed this way then running that file with the Meteor version of node gets us the right result. I can confirm this because if I forget and use `yarn` rather than my `myarn` alias in a Meteor project then I get the bcrypt warning on Meteor startup about using the javascript version (because the binary is compiled with the wrong node version). 

So could Meteor, if it can't find yarn installed in it's own or npm's 'global' location, fallback to running the yarn script on the `PATH`?

**Comment by abernix** [comment]
I see.  Yeah, if your `which yarn` was returning the actual `yarn`, that alias would fail as `yarn` launches [as a shell script](https://github.com/yarnpkg/yarn/blob/master/bin/yarn) which `node` wouldn't understand.

In fact, I believe with your current setup,  `yarn` will use [the node from your `PATH`](https://github.com/yarnpkg/yarn/blob/master/bin/yarn#L21) when it tries to install packages and you might run into problems with binary dependencies.  This won't be a problem if you have no binary dependencies, but that doesn't usually last for long in a project.

> So could Meteor, if it can't find yarn installed in it's own or npm's 'global' location, fallback to running the yarn script on the PATH?

Just to clarify, as it is right now, Meteor never looks in npm's global location for `yarn` and Meteor will never be able to find `yarn` unless you install it with `meteor install -g yarn`.  Meteor uses its own versions of `npm` and `node` and never your own, and treats `meteor <command>` the same way.  Currently, any deviation to this might result in the binary dependency problem I've mentioned before.

If you install `meteor npm install -g yarn`, you can do away with your `myarn` alias and just run `meteor yarn`.  You would have a separate version of `yarn` and it wouldn't be installed globally (which is what you said you wanted, based on the first sentence in this issue, right?).

If you _do_ want to use the global `yarn`, you could _probably_ change your `alias` to be:

    alias myarn='PATH="$(meteor npm bin -g):$PATH" yarn'

...and this would cause `yarn` to try Meteor's Node.js _first_ to compile binary dependencies (by changing the search order of the shell `PATH`).

**Comment by damonmaria** [comment]
Again, thanks for the great writeup @abernix. I can see the reasoning why meteor maintains it's own 'global' install location and wouldn't look elsewhere. 

> In fact, I believe with your current setup, yarn will use the node from your PATH when it tries to install packages and you might run into problems with binary dependencies.

As I mentioned in the comment above (https://github.com/meteor/meteor/issues/8493#issuecomment-287302730) invoking yarn with `meteor node $(which yarn)` does get yarn to compile with Meteor's version of node. I can see yarn compile multiple packages at the end but the most obvious is bcrypt, which produces a big fat warning on the console when Meteor starts if it isn't using a binary version. If I `yarn install --force` in any of my Meteor projects (`install --force` forces binaries to be recompiled) then I'll get the bcrypt warning, if I `meteor node $(which yarn) install --force` then there is no warning from bcrypt.

**Comment by damonmaria** [comment]
Maybe an improvement to the error message when running `meteor yarn` without first having `meteor install -g yarn` would help. 

Something along the lines of: `No command 'yarn' found in Meteor install. If you expect this to run a global package then you need to 'meteor install -g yarn' first`.

**Comment by gotjoshua** [comment]
@damonmaria  in your last line, did you mean:

you need to run 'meteor **npm** install -g yarn' first.

?

**Comment by damonmaria** [comment]
@gotjoshua Yes sorry, you are correct.

**Comment by gotjoshua** [comment]
@damonmaria  - maybe you can edit your comment (then we can delete these to keep the thread clean)
