### ISSUE TITLE
[PROJECT] [GOVERNANCE] Censorship Complain

### ISSUE THREAD

**Issue by lazaridis-com** [meteor/meteor#8494]
To the responsible person(s) (CTO, CEO etc.)

I've opened an issue #8368, which was violently comment-close-locked by @abernix (who seems to be the main responsible person for the chaotic situation within the tutorial repo).

I asked within #8492 to "Provide Rule to Avoid "Comment-Close-Lock" Barbarism.", and to open the issue again, thus I can close it once I assess that the issue is solved.

I don't doubt that @abernix is a capable developer. But it is crystal-clear, that his "control-freak" attitude has a very negative influence on the Meteor project. 

A core-developer should not...

* write tests for the code he writes
* write documentation for the system he designs or implements (especially end-user documentation).
* specify the processes which control his results and his behavior within his projects.

And of course, a core-developer should not waste his time in dealing with trivialities like processing contributions like "delete 3rd word in 5th paragraph".

The thing is: do you want more capable developers on board? Even those with Product Management abilities? Or do you want just some more "nicely playing open-source pets" ("pets" with the positive meaning).

In any way, please ensure that issue #8368 is opened again, so I know that I can trust Meteor for my projects.

-

Note to "The Masters of the Buttons": despite you having the technical rights to close this issue, this does not mean that you have the organizational / ethical rights. So please, keep your fingers (and of course your Ego) under control.

**Comment by laosb** [comment]
Personally I think @abernix is doing the right thing. Since we have so many issues/PRs to deal with, let's just stop talking and write code.

Actually @abernix is just recently employed by MDG, and before this he is a really great community guy who helped Meteor greatly.

**Comment by benjamn** [comment]
To anyone who comes across this thread in the future, @lazaridis-com has been banned from contributing to repositories within the Meteor Development Group organization. This was my decision, as the tech lead of the Meteor project, after reviewing this thread and others in which @lazaridis-com attempted to shame @abernix and @hwillson for their responses to his contributions. Self-righteousness, sarcasm, and abusive language have no place in this project.

**Comment by um-wat** [comment]
https://web.archive.org/web/20060913000000/http://en.wikipedia.org/wiki/Ilias_Lazaridis

**Comment by stubailo** [comment]
heh, I'm glad we got to be a part of history.

**Comment by benjamn** [comment]
Thanks for that, @um-wat.
