### ISSUE TITLE
Build fails when importing quasar-framework

### ISSUE THREAD

**Issue by mwarren2** [meteor/meteor#8498]
There's a project I've been working on with the maker of **quasar-framework** to get it working with meteor.
Since the latest couple of releases of meteor I'm stuck with a build error, which happens with the first _import_ statement in quasar src code, which presumably shouldn't be appearing at this stage.

W20170320-10:58:23.268(1)? (STDERR) /Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/packages/modules.js:375
W20170320-10:58:23.269(1)? (STDERR) import TableFilter from './TableFilter.vue'
W20170320-10:58:23.270(1)? (STDERR) ^^^^^^
W20170320-10:58:23.270(1)? (STDERR) 
W20170320-10:58:23.271(1)? (STDERR) SyntaxError: Unexpected reserved word
W20170320-10:58:23.271(1)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170320-10:58:23.271(1)? (STDERR)     at /Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/boot.js:297:30
W20170320-10:58:23.272(1)? (STDERR)     at Array.forEach (native)
W20170320-10:58:23.272(1)? (STDERR)     at Function._.each._.forEach (/Users/malcolm/.meteor/packages/meteor-tool/.1.4.3_2.1oo2nca++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170320-10:58:23.272(1)? (STDERR)     at /Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/boot.js:128:5
W20170320-10:58:23.272(1)? (STDERR)     at /Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/boot.js:352:5
W20170320-10:58:23.273(1)? (STDERR)     at Function.run (/Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/profile.js:510:12)
W20170320-10:58:23.273(1)? (STDERR)     at /Users/malcolm/git/app-template-meteor/.meteor/local/build/programs/server/boot.js:351:11

**To reproduce:**
git clone https://github.com/quasarframework/app-template-meteor.git
meteor npm install
meteor

**Comment by abernix** [comment]
Thanks for the reproduction repository!

As you're probably aware, the error is stemming from [this line](https://github.com/quasarframework/quasar/blob/dev/src/vue-components/data-table/plugins/filter/filter.js#L1) in the `quasar-framework` npm which uses ECMAScript `import` statements.  `import` statements are not natively supported by any browser, or [even by Node.js itself](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c#.apovyx60b), so they must be transpiled into a format which Node.js can understand (CommonJS, typically!)

It's up to npm package authors decide which [`engine`s](https://docs.npmjs.com/files/package.json#engines) (servers, browsers, clients) they would like to support and to provide code in their published package which can be natively executed by those engines.  Their Babel configuration should transpile newer ECMAScript constructs into ones that are supported natively by the engine executing it (Node.js v4 in Meteor's case).  Most packages Babel their code before publishing (`quasar-framework` is [no exception](https://github.com/quasarframework/quasar/blob/dev/.babelrc)), and Meteor doesn't transpile Node.js packages again as this might result in re-transpilation.

In the future, when `import` and `export` are supported natively, this won't be necessary, but unfortunately re-transpiling npm modules which may already be transpiled is something we'd like to avoid and is best left for package authors to handle.

Hope this helps to explain the problem!

**Comment by mwarren2** [comment]
Thanks for the explanation. Thankyou especially for giving me the quasar Babel link so I can quickly get it fixed, that was awesome.

Yes, I'd wrongly assumed that the meteor build also somehow converted the other packages' es6 stuff.
