### ISSUE TITLE
undefined packages after update 1.3.4.2 !!

### ISSUE THREAD

**Issue by mokaid** [meteor/meteor#8506]
Hello , 

With 1.3.4.1 everything was going fine ... I don't what happened when I updated meteor to 1.4.3.2 
I am getting the following in the browser console : 

Uncaught ReferenceError: Npm is not defined
    at spacebars-compiler.js?hash=ba0fb6f…:1252
    at spacebars-compiler.js?hash=ba0fb6f…:1370
    at spacebars-compiler.js?hash=ba0fb6f…:1382
(anonymous) @ spacebars-compiler.js?hash=ba0fb6f…:1252
(anonymous) @ spacebars-compiler.js?hash=ba0fb6f…:1370
(anonymous) @ spacebars-compiler.js?hash=ba0fb6f…:1382
mpowaga_string-template.js?hash=6ebcf7e…:18 Uncaught TypeError: Cannot read property 'SpacebarsCompiler' of undefined
    at mpowaga_string-template.js?hash=6ebcf7e…:18
    at mpowaga_string-template.js?hash=6ebcf7e…:93
(anonymous) @ mpowaga_string-template.js?hash=6ebcf7e…:18
(anonymous) @ mpowaga_string-template.js?hash=6ebcf7e…:93
yogiben_autoform-modals.js?hash=68550b6…:26Uncaught TypeError: Cannot read property 'StringTemplate' of undefined
    at yogiben_autoform-modals.js?hash=68550b6…:26
    at modals.coffee:1
(anonymous) @ yogiben_autoform-modals.js?hash=68550b6…:26
(anonymous) @ modals.coffee:1
kadira_flow-router.js?hash=4b8034f…:519 There is no route for the path: /

how can i solve this ?

**Comment by abernix** [comment]
This is a known Blaze issue which we're working to get resolved.  It is being tracked at meteor/blaze#244.

(You should/might be able to fix this by using the previous version of Blaze you were using before you upgraded).
