### ISSUE TITLE
Can't use async / await anymore

### ISSUE THREAD

**Issue by Fen747** [meteor/meteor#8507]
I do not know for how long exactly I haven't been able to use them anymore, but I can't use `async` / `await` anymore, as everytime I try to use them, I get this kind of error : 

```
=> Errors prevented startup:                  
   
   While building for web.browser:
   imports/ui/Dashboard.jsx:12:16: await is a reserved word (12:16)
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.

```

Yet I know I once used them in production with a previous app, on a previous version, though I do not remember which one exactly.

According to this recent [blog post](https://blog.meteor.com/using-promises-on-the-client-in-meteor-fb4f1c155f84#.6wfpgqovw) by @robfallows, it should be possible to use the `await` keyword client side on meteor.

Edit : `Dashboard.jsx`
```

import React, { Component } from 'react';
import CircularProgress from 'material-ui/CircularProgress';

export default class Dashboard extends Component {
  constructor( props ){
  	super( props );

  	this.state = {
			loading: true,
  	};

  	const toto = await import('/imports/ui/modules/DashboardModule'); // line 12
  	console.log(toto);
  }

  render(){
  	setTimeout(f => this.setState({loading: false}), 3000);
		return (
			<main className="aligner" style={{height: "91vh"}}>
				{	this.state.loading ?
					<CircularProgress className="aligner-item aligner-item-fixed" size={80} thickness={5} />
					:
					<h1>Hello World !</h1>	
				}
			</main>
		);
  }
}
```

**Comment by hwillson** [comment]
Hi @Fen747 - can you show us your `imports/ui/Dashboard.jsx` code, in particular what's happening on line 12?

**Comment by Fen747** [comment]
Done !

**Comment by hwillson** [comment]
Thanks @Fen747 - just to confirm, you're using one of the Meteor 1.5 beta's (since you're making a dynamic `import(...)` call)? If so which version exactly?

**Comment by Fen747** [comment]
Yes, I'm using METEOR@1.5-beta.12.

But the problem also occurs in METEOR@1.5-beta.9 and above. If I remeber right, it might have worked on 8 though.

**Comment by robfallows** [comment]
If you're using `await xxx` you need to declare the  enclosing function as `async`. In this case that would mean declaring `async constructor`, but I'm pretty sure you can't have an async constructor.

**Comment by Fen747** [comment]
So have I no way to write it in a synchronous way ?

Of course it's not needed, I can simply go for the old `.then( cbk )`, but I'd just like to keep my code up to date and as clean as possible

**Comment by Fen747** [comment]
I just rewrote my code like this :

```
let DashboardModule = <h1>Hello World !</h1>;

export default class Dashboard extends Component {
  constructor( props ){
  	super( props );

  	this.state = {
			loading: true,
  	};

  	const _loadDashboardModule = async () => {
			const toto = import('/imports/ui/modules/DashboardModule');
  		//this.setState({ loading: false });
	  	console.log(toto); // Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
  	};

  	_loadDashboardModule();
  }

  render(){
		return (
			<main className="aligner" style={{height: "91vh"}}>
				{	this.state.loading ?
					<CircularProgress className="aligner-item aligner-item-fixed" size={80} thickness={5} />
					:
					<DashboardModule />
				}
			</main>
		);
  }
}
```

But `console.log(toto)` prints `Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}`, then the promise resolve after the log. Wy do I get a promise and not the resolved value ?

**Comment by robfallows** [comment]
You probably meant to use `const toto = await import('/imports/ui/modules/DashboardModule');`

**Comment by Fen747** [comment]
Oh gosh, I've been messing with so much variations of the same files today... Don't know where my head is anymore, sorry !

Thanks a lot guys, you saved my day, big up !
