### ISSUE TITLE
Make it possible to entirely disable progress bars (eg, for CI)

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#8511]
Progress bars are lovely, but in some contexts you want to turn them off, like in CI environments where they end up filling up lots of logs.

Setting METEOR_PRETTY_OUTPUT=0 mostly does this, but a few bits of code call Console.withProgressDisplayVisible, which overrides this.  For example, the springboard code that downloads the appropriate meteor-tool calls this, so it appears to always print a progress bar no matter what.

Is this intentional, or would it be reasonable to have an env var (possibly METEOR_PRETTY_OUTPUT) that entirely turns off progress bars?

**Comment by abernix** [comment]
I believe `METEOR_PRETTY_OUTPUT` was actually meant to make things quite a bit more interesting on the console, for example, adding colors and other "pretty" artifacts that would probably not behave well in a CI environment but give the Meteor tool a fresh-look.

Can you try setting `METEOR_HEADLESS=true`? (Note that this should be `true` or `1` not just `t`). This was added in December (#8037) as a follow-up to the addition of the `--headless` argument (#7814).  We use this in our [CI configuration](https://github.com/meteor/meteor/blob/release-1.4.3.x/scripts/ci.sh#L26) and it seems to work well – but we only springboard within tests, so I'm not sure if it covers _that_ progress bar (though, it should).

**Comment by rbaertsch** [comment]
I tried METEOR_HEADLESS=1 and I'm still getting on meteor release is 1.3.5.1:
   Updating package catalog                  |
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  -
   Updating package catalog                  -
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  |
   Updating package catalog                  |
   Updating package catalog                  |
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  -
   Updating package catalog                  -
   Updating package catalog                  -
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  |
   Updating package catalog                  |
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  -
   Updating package catalog                  \
   Updating package catalog                  |
   Updating package catalog                  |
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  -
   Updating package catalog                  -
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  |
   Updating package catalog                  |
   Updating package catalog                  /
   Updating package catalog                  /
   Updating package catalog                  -
   Updating package catalog                  -
   Updating package catalog                  \
   Updating package catalog                  \
   Updating package catalog                  \

**Comment by hwillson** [comment]
@rbaertsch `METEOR_HEADLESS` support wasn't made available until Meteor 1.4.3 - see https://github.com/meteor/meteor/commit/e804c00e971c6a73d371bffe91718adabd00af79.

**Comment by rbaertsch** [comment]
ok, since my app works on 1.4, I guess it it time...

Robert Baertsch, PhD
Cell #: 831-239-2531

Changing the way the world treats cancer, starting with you.
Visit https://www.cancercommons.org/ <https://www.cancercommons.org/>

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8511#issuecomment-288354112, using `METEOR_HEADLESS=true` should fully disable console progress bars, so I'll close this off. Thanks!
