### ISSUE TITLE
Published package has included tests files as well and now if failing

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8512]
I have recently published a new version of [my package](https://github.com/peerlibrary/meteor-user-extra), `0.1.2`. To my surprise, published package contains also `tests.coffee` file which tries to be loaded when you the app normally loads. Because necessary dependencies are not in place, the whole app starts crashing:

```
W20170322-03:21:56.775(-7)? (STDERR) ReferenceError: ClassyTestCase is not defined
W20170322-03:21:56.775(-7)? (STDERR)     at packages/peerlibrary_user-extra.js:213:4
W20170322-03:21:56.775(-7)? (STDERR)     at packages/peerlibrary_user-extra.js:219:4
W20170322-03:21:56.775(-7)? (STDERR)     at packages/peerlibrary_user-extra.js:226:3
W20170322-03:21:56.776(-7)? (STDERR)     at /Users/user/test-user-extra/.meteor/local/build/programs/server/boot.js:303:34
W20170322-03:21:56.776(-7)? (STDERR)     at Array.forEach (native)
W20170322-03:21:56.776(-7)? (STDERR)     at Function._.each._.forEach (/Users/user/.meteor/packages/meteor-tool/.1.4.3_2.1rewwj7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170322-03:21:56.777(-7)? (STDERR)     at /Users/user/test-user-extra/.meteor/local/build/programs/server/boot.js:128:5
W20170322-03:21:56.778(-7)? (STDERR)     at /Users/user/test-user-extra/.meteor/local/build/programs/server/boot.js:352:5
W20170322-03:21:56.779(-7)? (STDERR)     at Function.run (/Users/user/test-user-extra/.meteor/local/build/programs/server/profile.js:510:12)
W20170322-03:21:56.779(-7)? (STDERR)     at /Users/user/test-user-extra/.meteor/local/build/programs/server/boot.js:351:11
```

This is a really strange situation and regression. The issue is that I made it a patch release, so all users got package automatically updated and now their app is failing for them. :-(

Reproduction: https://github.com/mitar/meteor-issue8512

**Comment by abernix** [comment]
What's the last version of `peerlibrary:user-extra` which worked properly and which version of Meteor did you publish it with?

You could probably fix your emergency by republishing from whatever version you used before, until we get to the bottom of the problem:

    meteor --release <version> publish

**Comment by mitar** [comment]
`0.1.0` was the previous version which worked. I do not know with which Meteor version I published it, but [this was the versions file generated](https://github.com/peerlibrary/meteor-user-extra/commit/165bfafc701c0e27fefe1b07752ba5de3326e352), so maybe we can reverse engineer the version from core package versions?

**Comment by abernix** [comment]
I _believe_ this would have been published with `METEOR@1.1.0.3`.  (I snuck this out of the `sqlite3` database in `~/.meteor/package-metadata/v2.0.1/packages.data.db`.

    sqlite3 ~/.meteor/package-metadata/v2.0.1/packages.data.db "select * from versions where packageName = 'peerlibrary:user-extra'"

**Comment by benjamn** [comment]
When I clone this package into the reproduction app's local `packages` directory, the problem seems to go away. And, as I hoped, the file
```
.meteor/local/build/programs/web.browser/packages/peerlibrary_user-extra.js
```
no longer contains the `tests.coffee.js` file.

Given this, I wonder if the issue is that you have [a very old `api.versionsFrom` line](https://github.com/peerlibrary/meteor-user-extra/blob/beeffa9ed5a3a0fc13845d4dea4d285937ab930c/package.js#L9) in your `package.js` file.

If you really want to maintain compatibility with Meteor 1.0.x, you should be sure to publish the package with that version of Meteor:
```sh
meteor --release 1.0.3.2 publish
```

However, I would strongly recommend updating that `api.versionsFrom` call to something more recent, perhaps the latest `1.3.4.y` release (that is, 1.3.4.4). Judging from voluntary usage statistics, that should work for 80%+ of the Meteor community.

If you want to give yourself room to continue publishing for older versions of Meteor, I would recommend a minor version update (so that you can keep publishing patch updates on the older version line).

**Comment by mitar** [comment]
> When I clone this package into the reproduction app's local packages directory, the problem seems to go away.

Yes.

> Given this, I wonder if the issue is that you have a very old api.versionsFrom line in your package.js file.

Probably. I think you are right that I can fix this on the package side. But Meteor should at least complain, throw and error, or something. This was really a surprise. Publishing and then things starting breaking. Especially because tests do not catch it because if you run things locally, it just works.

**Comment by mitar** [comment]
Aaa. One more case of this. Yesterday I published a new version of my package and today [users are complaining that the package does not work](https://github.com/peerlibrary/meteor-reactive-publish/issues/28). This is really hard to prevent because testing does not catch this (because for tests everything works).

Can this please be resolved?

**Comment by hwillson** [comment]
Using a more recent `api.versionsFrom` version fixes this issue. I agree that publishing a new version of a package and having it stop working unexpectedly for users (when the tests still pass) is painful. Given that this is working as designed however, changes to improve this process are considered feature requests. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Published%20package%20has%20included%20tests%20files%20as%20well%20and%20now%20if%20failing&body=Migrated%20from:%20meteor/meteor%238512) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
