### ISSUE TITLE
Meteor process runs out of memory when trying to build and test a simple package.

### ISSUE THREAD

**Issue by atf-cguerin** [meteor/meteor#8513]
Using meteor 1.4.3.2 on Window 7, while trying to rebuild https://atmospherejs.com/arch/ace-editor which is basically a one file wrapper of Ace Editor (ace.c9.io) that I wanted to fork an improve, running the **test-packages** command crashes meteor with an out of memory error (note that it also crashes the build when adding it as a package to a real project that built fine previously, but it's easier to reproduce like this).

```
git clone --recursive https://github.com/account-archived-270316/meteor-ace-editor.git
cd meteor-ace-editor
meteor test-packages ./
```

gives

```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
   Linking                                   /
<--- Last few GCs --->

   62988 ms: Mark-sweep 698.0 (738.7) -> 698.0 (738.7) MB, 748.8 / 0 ms [allocation failure] [GC in old space requested].
   63740 ms: Mark-sweep 698.0 (738.7) -> 697.9 (738.7) MB, 751.2 / 0 ms [allocation failure] [GC in old space requested].
   64502 ms: Mark-sweep 697.9 (738.7) -> 697.9 (738.7) MB, 762.2 / 0 ms [last resort gc].
   65255 ms: Mark-sweep 697.9 (738.7) -> 697.9 (738.7) MB, 753.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 14A6CC95 <JS Object>
    1: hasPlugin [C:\Users\cguerin\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\babylon\lib\index.js:~154
6] [pc=50A11C57] (this=107FE5AD <a Parser with map 07E634ED>,name=3E7832FD <String[16]: objectRestSpread>)
    2: parseObj [C:\Users\cguerin\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\ba...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

There appears to be no way to avoid the crash from the user side, as none of the options for increasing node's memory allocation limit (basically somehow passing "--max-old-space-size=xxxx" to the node runtime) work:
- NODE_OPTIONS and TOOL_NODE_FLAGS environment variables are ignored.
- the version of node bundled with meteor immediately exits when given "--max-old-space-size=xxxx" on the command line (also occuring with a simple "path_to\node.exe --max-old-space-size=4096 -i").

Some Stackoverflow references: [1](http://stackoverflow.com/questions/42084472/meteor-build-running-our-of-memory) [2](http://stackoverflow.com/questions/32421928/meteor-out-of-memory)

**Comment by abernix** [comment]
Unfortunately, Meteor on Windows does not observe the `TOOL_NODE_FLAGS` environment variable in the same way that Unix systems does, which might help you with this problem.  I've opened PR #8517 to help this, but you can just modify the `meteor.bat` in your `%LocalAppData%\.meteor` directory in the meanwhile.  I was able to raise the memory, but then encountered a different error when it ran:

```
   While computing assigned variables:
   /packages/arch_ace-editor/ace-builds/demo/r.js: Unexpected token, expected ; (20:12)

   While computing assigned variables:
   /packages/local-test_arch_ace-editor/ace-builds/demo/r.js: Unexpected token, expected ; (20:12)
```

There may be multiple errors here.

**Comment by atf-cguerin** [comment]
So, after reading your feedback, I investigated a bit more, and it looks like "--max-old-space-size=4096" was too much for meteor on Windows due to the version of node used by meteor being 32 bits, and I can at least reach the same error message as you got by using values around 1400 (*).

However, while this solves the case of the package as it is right now, I was planning to improve it, and adding a simple `api.use('ecmascript');` in `Package.onUse` brings it to the point where there is no value of _max-old-space-size_ that works (after some much longer processing, I just get a crash without an error message, as if the memory requested was too high even with a value of 1400 despite being sufficient for the base version).

While I understand that developpers can get around this issue thanks to [PAE](https://forums.meteor.com/t/is-meteor-64-bit/19758) on Linux, this is a much more problematic option on Windows (and limited to 4gb instead of 64gb anyway) so unless future versions of meteor can be built in 64 bits (which I understand is also problematic, seeing the comments on the [following](https://github.com/meteor/meteor/issues/6208) [issues](https://github.com/meteor/meteor/issues/6062)) it looks like I'm currently stuck with the modular approach for now.

Since this is well beyond the scope of fixing this specific crash (unless there is an actual memory leak causing that memory growth that you can identify from these steps?), I'll probably have to look for a workaround specific to my project (**) until a future version of meteor.

---

(*) at this point you can get the tests running by simply deleting the ace-builds/demo directory, although it is also strange that those files were causing problems in the first place and it might be another bug, because they are not referenced by the package and not even copied as assets, unlike the main ace source files.

(**) I'll see if I can setup a linux computer and if using a prebuilt package works on windows later, or maybe just write this feature inside of my main application (which does use ecmascript without problem and is already much more complex than that)

**Comment by john-osullivan** [comment]
Why was this closed?  It doesn't look like the issue was resolved and I'm having the exact same issue right now on Meteor 1.5.  If the new version included a fix for this problem, it isn't working on my Windows 10 machine.

**Comment by john-osullivan** [comment]
Thanks for the reply!  In case somebody else stumbles across this, I was able to get around the issue by removing a couple of unused npm libraries and re-running `meteor npm install`.  My system's `npm` is different from Meteor's, I think that using `npm` rather than `meteor npm` was breaking something.

Also found that it tends to happen after a few hot reloads; currently using `meteor-webpack` to bridge the build systems, something in that process might be leaking memory.  Whatever is causing the issue, restarting the terminal and running `meteor reset` tends to fix the issue for me.

**Comment by Xeoncross** [comment]
`export TOOL_NODE_FLAGS="--max-old-space-size=4096"`
