### ISSUE TITLE
meteor runs ok on some machines not others

### ISSUE THREAD

**Issue by interfaith** [meteor/meteor#8514]
Maybe the version of npm/node is the issue. However even the zipped directory
or the meteor build output fails on some machines. It appears to be the mongodb code fails to import the same data with the same result. Yet the development code uses an internal version of node ?

**Comment by hwillson** [comment]
Hi @interfaith - there isn't enough detail here to help troubleshoot. Can you be more specific with regards to the problems you're seeing? Are there any errors or stack traces you can share, or any code that can be tried out to see if the same problem can be re-created? Any additional details you can provide would be greatly appreciated (for more info see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by abernix** [comment]
Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.   Specifically, exact reproduction steps including exact platforms, versions, error messages, anything, etc. would be incredibly helpful.
