### ISSUE TITLE
Meteor 1.4.3.3-beta4 = module.importSync is not a function

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#8526]
So today is March 27th and FB's Graph API has changed. At Workpop we are still operating on 1.4.2.3 This is leading to even bigger problems, but I am just upgrading our app to 1.4.3.3-beta4. After updating and `meteor reset` I'm getting an error:

`module.importSync is not a function`

I'm thinking has to do with the `reify` changes? If @benjamn you wanna see Workpops code let me know. 

If this route does not work, how does a user in an old version of Meteor take advantage of the new accounts-facebook package?

**Comment by benjamn** [comment]
That problem should be fixed by https://github.com/meteor/meteor/pull/8439/commits/0bc4e2e804267eaf4d1e360ef20825c0a5942a15, though I need to release a new RC.

What's the stack trace for that error?
What does your `.meteor/versions` file look like?

**Comment by abhiaiyer91** [comment]
@benjamn we described our flow

https://github.com/meteor/accounts/issues/23

Needless to say this was a terrible experience! I guess we'll hold on upgrade till 1.4.4 is out and stable?

**Comment by benjamn** [comment]
Commented over there: https://github.com/meteor/accounts/issues/23#issuecomment-289628597

It would be helpful if you can confirm that `meteor update --release 1.4.4-rc.2` makes the `module.importSync` problem go away, though please note I am not recommending you use that version in production (unless you have no choice, and it seems to work!).

**Comment by benjamn** [comment]
This should be fixed in 1.4.4(.1), available now via `meteor update`.
