### ISSUE TITLE
Having trouble creating a Meteor package that uses the `ecmascript` package

### ISSUE THREAD

**Issue by manuelro** [meteor/meteor#8527]
I'm creating a Meteor package to simply use arithmetic operations in Blaze via a Template helper. I could not use ES6, it simply says that every keyword in ES6 I use is invalid (export, let, ..., const). First I thought it was something related with `Package.onUse`, I added everything I needed. 

I had to rewrite the entire code to vanilla JS and at the end it says Template is not defined. What's the right way of making use of Meteor's Template object in a package?

I searched the Web but documentation for this is certainly lacking.

You can find the Package I want to publish on Atmosphere here: https://github.com/manuelro/math

**The package.js file:**
```javascript
Package.describe({
  name: 'manuelro:math',
  version: '0.0.8',
  summary: 'Basic arithmetics helper for Meteor',
  git: 'https://github.com/manuelro/math',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.4.3.2');
  api.use(['ecmascript', 'templating@1.3.2'], 'client');
  api.mainModule('math.js');
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('manuelro:math');
  api.mainModule('math-tests.js');
});

```

**Comment by benjamn** [comment]
You're restricting `ecmascript` to the `client`, though `math.js` is evaluated on both `client` and `server`. I suspect this line
```js
api.use(['ecmascript', 'templating@1.3.2'], 'client');
```
should be two lines instead:
```js
api.use('ecmascript');
api.use('templating@1.3.2', 'client');
```

**Comment by manuelro** [comment]
Again, `ReferenceError: Template is not defined`.

**The package.js file:**
```javascript
Package.describe({
  name: 'manuelro:math',
  version: '0.0.9',
  summary: 'Basic arithmetics helper for Meteor',
  git: 'https://github.com/manuelro/math',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.4.3.2');
  api.use('ecmascript');
  api.use('templating@1.3.2', 'client');
  api.mainModule('math.js');
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('manuelro:math');
  api.mainModule('math-tests.js');
});
```

**Comment by manuelro** [comment]
**FIXED**
If you're simply creating a new `Template.helper` which is intended to be used on the client only, it's important to specify the `client` flag on the `mainModule`, otherwise it will load this file on the `server` side as well, and hence throw the `ReferenceError: Template is not defined`. See full configuration below:

```javascript
// package.js
Package.describe({
  name: 'manuelro:blaze-math',
  version: '0.0.1',
  summary: 'Basic arithmetics Meteor helper for Blaze',
  git: 'https://github.com/manuelro/math',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.4.3.2');
  api.use('ecmascript');
  api.use('templating@1.3.2', 'client');
  api.mainModule('math.js', 'client');
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('manuelro:blaze-math');
  api.mainModule('math-tests.js');
});
```

**Comment by abernix** [comment]
That sounds right.  `Template` is not available on the server, so if you use it there, it will fail!

Glad you got it figured out!
