### ISSUE TITLE
can't  use materialui   

### ISSUE THREAD

**Issue by yunfengsay** [meteor/meteor#8530]
I had added vue in my project, but unfortunatly  after i installed vue-material and import vue-material 
i can't run meteor this is the error
```
W20170328-22:37:38.806(8)? (STDERR) export default {
W20170328-22:37:38.807(8)? (STDERR) ^^^^^^
W20170328-22:37:38.807(8)? (STDERR)
W20170328-22:37:38.808(8)? (STDERR) SyntaxError: Unexpected reserved word
W20170328-22:37:38.809(8)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170328-22:37:38.810(8)? (STDERR)     at D:\projects\meteor\meteor-vue2-kit\.meteor\local\build\programs\server\boot.js:297:30
```

this is my code where i import vue-material
```
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'
Vue.use(VueMaterial)
```

**Comment by abernix** [comment]
Do you have the `ecmascript` package in your project? (i.e. does it appear when you run `meteor list`?)

You haven't given one of the most important pieces of information requested when you opened the issue:

> What version of Meteor you're using, and the platform(s) you're running it on

It's clear you're running Windows, but not clear what versions of anything (npm packages included).

If you do have the `ecmascript` package and it's still not working, I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  Thank you for understanding. :)

[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

**Comment by yunfengsay** [comment]
I am sorry for late to reply,
this is my meteor list
```
D:\projects\meteor\meteor-vue2-kit (es6-error)
λ meteor list
accounts-base          1.2.15  A user account system
akryum:vue-component   0.8.15  VueJS single-file components that hot-reloads
akryum:vue-less        0.0.4  Add less support for vue components
autopublish            1.0.7  (For prototyping only) Publish the entire database to all c...
ecmascript             0.6.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the c...
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.16  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.3  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.2.3  Standard javascript minifiers used with Meteor apps by defa...
static-html            1.2.2  Define static page content in .html files
tracker                1.1.2  Dependency tracker to allow reactive callbacks

```
And [this](https://github.com/yunfengsay/meteor-vue2-kit.git) is my project , it is small.

**Comment by abernix** [comment]
I just tried the reproduction you linked and it worked perfectly.   I simply ran:

```sh
$ git clone https://github.com/yunfengsay/meteor-vue2-kit.git
$ cd meteor-vue2-kit
$ meteor npm install
$ meteor
```

Can you offer more information about how we can reproduce this?

**Comment by yunfengsay** [comment]
sorry  the master brunch is normal.
You can check it to es6-error 
or 
```
git clone -b es6-error  https://github.com/yunfengsay/meteor-vue2-kit.git
```
thanks~

**Comment by hwillson** [comment]
Your `es6-error` branch has a few problems:

1. That branch is missing the `ecmascript` package. Run `meteor add ecmascript`.

2. Based on the packages you're using, you're missing a few dependencies. Run:

```
meteor npm install --save autosize element.scrollintoviewifneeded-polyfill
```

3. The source files of the `vue-material` package you're using are being picked up by the Meteor build tool (the files in `meteor-vue2-kit/node_modules/vue-material/src`). These files haven't been run through `vue-material`'s babel build process yet, like the files in `meteor-vue2-kit/node_modules/vue-material/dist` have been. That means the ES2015 JS syntax they're using can't be interpreted. As a quick fix for this, if you completely remove the `meteor-vue2-kit/node_modules/vue-material/src` directory and all contents, your app will work properly. This is likely a problem caused somewhere by the [`akryum:vue-component`](https://github.com/Akryum/vue-meteor/tree/master/packages/vue-component) build plugin. I'd recommend opening an issue there.

Given the above, this doesn't appear to be a Meteor issue, so I'll close it for now. Thanks!
