### ISSUE TITLE
Isolate server tests

### ISSUE THREAD

**Issue by dhrubins** [meteor/meteor#8535]
I noticed while working on #8520, that according to the comment [here in the accounts-password tests](https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_tests_setup.js#L107-L118) it seems that test runs are not isolated on the server. While this is more expedient, we should probably explore ways to isolate server test runs. Or, if I completely missed this in my research and this _is_ possible today, the comment should be updated and we should rewrite those tests to take advantage of the isolation.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Isolate%20server%20tests&body=Migrated%20from:%20meteor/meteor%238535) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
