### ISSUE TITLE
Some minified packages raise ReferenceErrors in Meteor 1.4.4 and 1.5-beta.13

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#8536]
Upgrading back to 1.5-beta-13 fixes the issue, but if I try run it with --production or in a Galaxy container, I get:
```
1be3748….js?meteor_js_resource=true:159 Uncaught ReferenceError: G is not defined
    at 1be3748….js?meteor_js_resource=true:159
    at 1be3748….js?meteor_js_resource=true:159
    at 1be3748….js?meteor_js_resource=true:159
    at 1be3748….js?meteor_js_resource=true:159
(anonymous) @ 1be3748….js?meteor_js_resource=true:159
(anonymous) @ 1be3748….js?meteor_js_resource=true:159
(anonymous) @ 1be3748….js?meteor_js_resource=true:159
(anonymous) @ 1be3748….js?meteor_js_resource=true:159
1be3748….js?meteor_js_resource=true:105 Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
    at 1be3748….js?meteor_js_resource=true:105
    at g (1be3748….js?meteor_js_resource=true:3)
    at HTMLDocument.T (1be3748….js?meteor_js_resource=true:3)
```
Here's the error when I roll back to beta-10
```
Your app is crashing. Here's the latest log:
/.meteor/packages/meteor-tool/.1.5.0-beta.11.ku69ej++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module './accounts_server.js'
    at Function.require.resolve (packages/modules-runtime.js:145:19)
    at Module.resolve (packages/modules-runtime.js:95:25)
    at Module.Mp.importSync (/home/jason/.meteor/packages/modules/.0.9.0-beta.13.df4kx3++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:79:29)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:1:93)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at /var/www/submit/.meteor/local/build/programs/server/packages/accounts-base.js:73:15
    at /var/www/submit/.meteor/local/build/programs/server/packages/accounts-base.js:84:3
    at /var/www/submit/.meteor/local/build/programs/server/boot.js:338:34
    at Array.forEach (native)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by benjamn** [comment]
The upgrade/downgrade path between beta versions is not something we make any promises about. While we're interested in debugging issues in the latest version (`1.5-beta.13`), we can't spend time on older beta versions. To that end, we're probably going to need a [reproduction](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) to help debug the `ReferenceError` (which is probably coming from the minifier).

**Comment by jasongrishkoff** [comment]
The ReferenceError is currently visible on http://submithub.com/

**Comment by benjamn** [comment]
That's helpful, but we really need a minimal reproduction in the form of a repository of source code, if you can put that together. Thanks!

**Comment by benjamn** [comment]
I'm sure I don't have to say this, and you know what you're doing, but please bear in mind you're running a *beta* release in production, so problems are to be expected!

**Comment by jasongrishkoff** [comment]
Yep @benjamn, I take full responsibility for that stupid decision :)

I've shared a repository of my source code, though I won't be surprised if you tell me that's not what you're looking for.

**Comment by benjamn** [comment]
Looks like the `G` error is happening in `harrison:papa-parse`, if that helps with the reproduction (a simple app that uses that package might fail to minify for the same reason).

**Comment by jasongrishkoff** [comment]
You're right, removing that package got rid of the "G" error.  Now we have:

```
f205ad4….js?meteor_js_resource=true:241 Uncaught ReferenceError: X is not defined
    at f205ad4….js?meteor_js_resource=true:241
    at f205ad4….js?meteor_js_resource=true:241
    at f205ad4….js?meteor_js_resource=true:241
    at f205ad4….js?meteor_js_resource=true:241
    at f205ad4….js?meteor_js_resource=true:241
    at f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
(anonymous) @ f205ad4….js?meteor_js_resource=true:241
f205ad4….js?meteor_js_resource=true:137 There is no route for the path: /
w._notfoundRoute @ f205ad4….js?meteor_js_resource=true:137
(anonymous) @ f205ad4….js?meteor_js_resource=true:137
(anonymous) @ f205ad4….js?meteor_js_resource=true:137
Y @ f205ad4….js?meteor_js_resource=true:137
C.dispatch @ f205ad4….js?meteor_js_resource=true:137
C.replace @ f205ad4….js?meteor_js_resource=true:137
D._page.(anonymous function) @ f205ad4….js?meteor_js_resource=true:137
C.start @ f205ad4….js?meteor_js_resource=true:137
C @ f205ad4….js?meteor_js_resource=true:137
w.initialize @ f205ad4….js?meteor_js_resource=true:137
(anonymous) @ f205ad4….js?meteor_js_resource=true:137
g @ f205ad4….js?meteor_js_resource=true:3
T @ f205ad4….js?meteor_js_resource=true:3
f205ad4….js?meteor_js_resource=true:241 Uncaught ReferenceError: Accounts is not defined
    at f205ad4….js?meteor_js_resource=true:241
    at r.Computation._compute (f205ad4….js?meteor_js_resource=true:31)
    at new r.Computation (f205ad4….js?meteor_js_resource=true:31)
    at Object.r.autorun (f205ad4….js?meteor_js_resource=true:31)
    at f205ad4….js?meteor_js_resource=true:241
    at g (f205ad4….js?meteor_js_resource=true:3)
    at HTMLDocument.T (f205ad4….js?meteor_js_resource=true:3)
```

**Comment by jasongrishkoff** [comment]
Progress! Removing mrt:soundcloud hsa gotten me one step closer -- parts of the site are now actually rendering.  Working through a few more bugs; will keep you updated.

**Comment by jasongrishkoff** [comment]
Okay so I've got something up and running, but... seems to cause issues with poetic:materialize-scss as well.  Digging into that now.

**Comment by jasongrishkoff** [comment]
Encountering this issue now (new for this beta version): $or/$and/$nor entries need to be full objects

**Comment by jasongrishkoff** [comment]
Gosh that was painful!  I've successfully reverted back to 1.5-beta-10 by creating a new meteor directory and copying over my imports/packages/whatever.  Needless to say, this seems to be a rather big issue that broke somewhere between beta-10 and beta-13.

**Comment by benjamn** [comment]
> I've shared a repository of my source code

Where would I find that?

**Comment by jasongrishkoff** [comment]
https://github.com/jasongrishkoff/submit-meteor (sent an invite)

I think this should be possible to replicate just by install a few packages, though:
https://atmospherejs.com/mrt/accounts-soundcloud
https://atmospherejs.com/harrison/papa-parse
https://github.com/poetic/meteor-materialize-scss

Seems there's a chance they struggle to minify properly.

**Comment by abernix** [comment]
@jasongrishkoff Is this fixed if you try:

    meteor update --release 1.4.4-rc.7

?

**Comment by jasongrishkoff** [comment]
@abernix I'm currently on 1.5 v13, so... don't think I can risk rolling back to 1.4.4 to test...

**Comment by abernix** [comment]
@JasonGiedymin Any update on this with a more recent 1.5 beta?  For example, `meteor update --release 1.5-beta.16`, which also includes the fix from https://github.com/meteor/meteor/commit/0a73a80b4b09d33f5197ec490567e42ed2eed5b1 which was applied in hopes of fixing this?

**Comment by JasonGiedymin** [comment]
@abernix lol np. Couldn't remember if I had any PRs still open on meteor. Hi gang, long time.

So for meteor I really hope, all node dependencies are pinned to a specific version and there is a manifest hand rolled with SHAs. Through the years I can't tell you how many dozens of issues from a large dep tree where master latest was used, and where even a pinned version was floating with changes. Unfortunately not everyone has the same module strict policies as you. I can post something that at least CI should run that will give you a heads up on floating dep leaf. Knowing the diff helps you figure out what changed and how to tackle the situation. I maybe even can help solve this issue. Think my CLA should still be valid after all these years?

**Comment by jasongrishkoff** [comment]
@abernix thanks for following up. I just tried locally with 1.5-rc.1 and the --production flag, and it seems to be running without any of these errors! Seeing some other issues, but they seem unrelated.
