### ISSUE TITLE
ReferenceError: Plugin is not defined on Meteor 1.4.3.2

### ISSUE THREAD

**Issue by praveennagpal** [meteor/meteor#8541]
I am trying to compile solidity files using the meteor build tool and the solc npm module. But getting the following error, where it says Plugin is not defined as it comes in the first line of caching-compiler package. How do I reference plugin in a package which I am just using?

W20170329-23:07:35.231(5.5)? (STDERR) /Users/praveennagpal/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170329-23:07:35.234(5.5)? (STDERR) 						throw(ex);
W20170329-23:07:35.234(5.5)? (STDERR) 						^
W20170329-23:07:35.235(5.5)? (STDERR) 
W20170329-23:07:35.235(5.5)? (STDERR) ReferenceError: Plugin is not defined
W20170329-23:07:35.236(5.5)? (STDERR)     at meteorInstall.node_modules.meteor.caching-compiler.caching-compiler.js (packages/caching-compiler/caching-compiler.js:1:12)
W20170329-23:07:35.237(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170329-23:07:35.237(5.5)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170329-23:07:35.238(5.5)? (STDERR)     at /Users/praveennagpal/src/GitHub/CT-IBF/packages/framework/.meteor/local/build/programs/server/packages/caching-compiler.js:836:1
W20170329-23:07:35.238(5.5)? (STDERR)     at /Users/praveennagpal/src/GitHub/CT-IBF/packages/framework/.meteor/local/build/programs/server/packages/caching-compiler.js:849:3
W20170329-23:07:35.239(5.5)? (STDERR)     at /Users/praveennagpal/src/GitHub/CT-IBF/packages/framework/.meteor/local/build/programs/server/boot.js:303:34
W20170329-23:07:35.240(5.5)? (STDERR)     at Array.forEach (native)
W20170329-23:07:35.241(5.5)? (STDERR)     at Function._.each._.forEach (/Users/praveennagpal/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170329-23:07:35.242(5.5)? (STDERR)     at /Users/praveennagpal/src/GitHub/CT-IBF/packages/framework/.meteor/local/build/programs/server/boot.js:128:5
W20170329-23:07:35.242(5.5)? (STDERR)     at /Users/praveennagpal/src/GitHub/CT-IBF/packages/framework/.meteor/local/build/programs/server/boot.js:352:5  

Below is what I am using in package.js.

Package.registerBuildPlugin({
    name: "compileSol",
    use: [
      "ecmascript@0.1.0",
  		"isobuild:compiler-plugin",
  		"caching-compiler"
    ],
    sources: [
        "framework/plugin/handler.js",
    ],
	npmDependencies: {
		"solc": "0.4.9"
	}
});

Package.onUse(function (api) {
	api.use("isobuild:compiler-plugin");
});

**Comment by abernix** [comment]
This is explained briefly in [the guide](https://docs.meteor.com/api/packagejs.html#build-plugin-compilers), but you should also try looking at an existing example such as [the compiler for `coffeescript`](https://github.com/meteor/meteor/blob/devel/packages/non-core/coffeescript/package.js#L7).  You will need to depend specifically on the `1.0.0` version of `isobuild:compiler-plugin`, but should not include it in the `registerBuildPlugin`, only in the `onUse`.
