### ISSUE TITLE
Usage of Meteor Caching Compiler in v1.4.3.1

### ISSUE THREAD

**Issue by praveennagpal** [meteor/meteor#8543]
Having integrated solidity compiler using the caching compiler in the Meteor Build Process in v1.2 which worked ok, I am now struggling to get the values of the compiled output (bytecode) in Meteor v1.4.3.1 using the imports (ES2015) app structure proposed in Meteor 1.3.

How do I pass on the value to the packages outside the compiler package as the js file inside which I used to have global variables (without any var) is in the cache and cannot be explicitly imported by js files kept in the import folder? I can see the compiled output only in the server folder files where it is eagerly loaded. But I am not able to get the values of compiled output inside any of the modules/js files in the import folder. Tried package level export without any luck. Can you tell me how this can be done as it worked ok without the modular approach of ES2015?

**Comment by hwillson** [comment]
Issues here are reserved for Meteor bugs. Questions of this nature are better asked on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`). Closing - thanks!
