### ISSUE TITLE
meteor-tool download and extract taking 30-60 minutes

### ISSUE THREAD

**Issue by brg2** [meteor/meteor#8545]
We have several developers on our team loading meteor on windows. The problem is whenever we start our builds in the morning, the command line tool needs to pull down the latest version of meteor-tool. For some reason this process can take a long time. Is there anyway we can bypass the update process? Is there some way to do it in the background? This problem also occurs when building or resetting the project directory. Sometimes the process will go past an hour and we'll have to stop the process. After stopping the process, files become corrupt and we have to reinstall meteor altogether. This can be a burden for us and reduces the productivity we originally gained from the convenience of using the Meteor platform. 

Currently this is on my Win10 machine command prompt:
Extracting meteor-tool@1.4.1_3...

It has been spinning / loading for 20-30 minutes now.

Let me know if there's any other information to further diagnose this issue.

Thank you!

**Comment by hwillson** [comment]
Hi @brg2 - try starting meteor with a `--no-release-check` flag, or setting a `METEOR_NO_RELEASE_CHECK=1` environment variable.

**Comment by hwillson** [comment]
Sorry, I submitted that before my full comment was done. I just wanted to add that this won't fix your problem, but will disable the background release check/update. To find more info about your issue, and hopefully a solution, please take a look at the following similar closed issues:

https://github.com/meteor/meteor/issues?q=is%3Aissue+%22Extracting+meteor-tool%22+is%3Aclosed

**Comment by brg2** [comment]
@hwillson that works!
