### ISSUE TITLE
Error: Match error: Missing key 'ASWAccessKeyId' future.js:280

### ISSUE THREAD

**Issue by rachit2jain** [meteor/meteor#8551]
Error: Match error: Missing key 'AWSAccessKeyId'
W20170331-17:49:33.849(8)? (STDERR)     at exports.check (packages/check.js:57:15)
W20170331-17:49:33.849(8)? (STDERR)     at new Slingshot.Directive (packages/edgee_slingshot.js:325:3)
W20170331-17:49:33.850(8)? (STDERR)     at Object.Slingshot.createDirective (packages/edgee_slingshot.js:295:5)
W20170331-17:49:33.850(8)? (STDERR)     at server/main.js:4:13
W20170331-17:49:33.850(8)? (STDERR)     at Function.time 

I have checked the .pem file. Cant solve it anyhow. Please help

**Comment by hwillson** [comment]
Hi @rachit2jain - this doesn't look like an issue with Meteor. GitHub issues are reserved for Meteor bugs and/or feature requests. For help using Meteor, please try the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). If you think this is an issue with Meteor, please provide a small, runnable reproduction demonstrating the problem. See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more information. Thanks!
