### ISSUE TITLE
Unable to call AccountsCommon#onLogout(func)

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#8559]
My understanding is that I can use AccountsCommon.onLogout().

Meteor API Docs 1.4.3 mentions:

new AccountsCommon(options)
import { AccountsCommon } from 'meteor/accounts-base' . However, AccountCommon returns undefined in this import.

I can call Accounts.onLogin() (as it exists) however, I am not able to call Accounts.onLogout() (I can see that it doesn't exist in the source file which is legit), nor import or call AccountsCommon.onLogout() since the import returns undefined.

**Comment by hwillson** [comment]
Hi @paulincai - the following should work:

```js
import { Accounts } from 'meteor/accounts-base';
console.log(Accounts.onLogout);
```

I agree that this can be a bit misleading though. An explanation of what's happening here can be found in the `accounts-base` [`package.js`](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/accounts-base/package.js#L39-L44):

```js
// Though this "Accounts" symbol is the only official Package export for
// the accounts-base package, modules that import accounts-base will
// have access to anything added to the exports object of the main
// module, including AccountsClient and AccountsServer (those symbols
// just won't be automatically imported as "global" variables).
api.export('Accounts');
```

The API docs aren't exactly wrong as the `import { AccountsCommon } from 'meteor/accounts-base'` statement is valid, based on the [`AccountsCommon` export here](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/accounts-base/accounts_common.js#L10). It's just that this doesn't really help point towards the best way to use the predefined `Accounts` object directly.

I'll open a new issue in the docs repo to track this. Thanks!

**Comment by hwillson** [comment]
I'll close this here @paulincai since we'll now track this in the docs repo via meteor/docs#132. Please post back if you're having further issues. Thanks!
