### ISSUE TITLE
ddp-client.js throws blocking error in safari because of arrow function

### ISSUE THREAD

**Issue by joerex** [meteor/meteor#8561]
Commit b595135 in livedata_connection.js introduces arrow syntax which breaks safari (9.1.2)

**Comment by hwillson** [comment]
Hi @joerex - it shouldn't, as the `ddb-client` package is wired up to use `ecmascript`. Can you explain the issue you're seeing in more detail?

**Comment by joerex** [comment]
Hey @hwillson, thanks for the help. I'm using the ecmascript package. The error's stacktrace:

[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (ddp-client.js:3414)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (ddp.js:14)
	global code (ddp.js:27)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (allow-deny.js:23)
	global code (allow-deny.js:558)
[Error] TypeError: undefined is not an object (evaluating 'Package['allow-deny'].AllowDeny')
	(anonymous function) (mongo.js:17)
	global code (mongo.js:856)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (accounts-base.js:23)
	global code (accounts-base.js:1315)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (accounts-password.js:17)
	global code (accounts-password.js:321)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (alanning_roles.js:18)
	global code (alanning_roles.js:961)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (livedata.js:14)
	global code (livedata.js:31)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (cfs_storage-adapter.js:22)
	global code (cfs_storage-adapter.js:97)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (service-configuration.js:17)
	global code (service-configuration.js:77)
[Error] TypeError: undefined is not an object (evaluating 'Package['service-configuration'].ServiceConfiguration')
	(anonymous function) (google.js:20)
	global code (google.js:200)
[Error] TypeError: undefined is not an object (evaluating 'Package['service-configuration'].ServiceConfiguration')
	(anonymous function) (facebook.js:21)
	global code (facebook.js:163)
[Error] TypeError: undefined is not an object (evaluating 'Package['service-configuration'].ServiceConfiguration')
	(anonymous function) (vijayanant_meteor-yahoo-oauth.js:20)
	global code (vijayanant_meteor-yahoo-oauth.js:211)
[Error] TypeError: undefined is not an object (evaluating 'Package['service-configuration'].ServiceConfiguration')
	(anonymous function) (q42_microsoft.js:21)
	global code (q42_microsoft.js:210)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (matb33_collection-hooks.js:17)
	global code (matb33_collection-hooks.js:876)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (lai_collection-extensions.js:17)
	global code (lai_collection-extensions.js:168)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (dburles_mongo-collection-instances.js:17)
	global code (dburles_mongo-collection-instances.js:67)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (getstream_stream-meteor.js:18)
	global code (getstream_stream-meteor.js:5404)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (ground_util.js:19)
	global code (ground_util.js:161)
[Error] TypeError: Meteor.call is not a function. (In 'Meteor.call', 'Meteor.call' is undefined)
	(anonymous function) (ground_servertime.js:71)
	(anonymous function) (ground_servertime.js:83)
	(anonymous function) (ground_servertime.js:87)
	global code (ground_servertime.js:99)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (raix_stubfence.js:17)
	global code (raix_stubfence.js:151)
[Error] TypeError: undefined is not an object (evaluating 'Package['ground:util']._groundUtil')
	(anonymous function) (ground_db.js:21)
	global code (ground_db.js:1222)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (jcbernack_reactive-aggregate.js:18)
	global code (jcbernack_reactive-aggregate.js:102)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (tmeasday_publish-counts.js:17)
	global code (tmeasday_publish-counts.js:65)
[Error] TypeError: undefined is not a constructor (evaluating 'new Meteor.Collection(METADATA_COLLECTION)')
	(anonymous function) (percolate_find-from-publication.js:82)
	(anonymous function) (percolate_find-from-publication.js:99)
	(anonymous function) (percolate_find-from-publication.js:103)
	global code (percolate_find-from-publication.js:110)
[Error] TypeError: Meteor.status is not a function. (In 'Meteor.status()', 'Meteor.status' is undefined)
	(anonymous function) (mizzao_timesync.js:153)
	_compute (tracker.js:339)
	Computation (tracker.js:229)
	autorun (tracker.js:604)
	(anonymous function) (mizzao_timesync.js:152)
	(anonymous function) (mizzao_timesync.js:207)
	global code (mizzao_timesync.js:220)
[Error] TypeError: undefined is not an object (evaluating 'Package['accounts-base'].Accounts')
	(anonymous function) (mizzao_user-status.js:17)
	global code (mizzao_user-status.js:272)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (aldeed_collection2-core.js:18)
	global code (aldeed_collection2-core.js:745)
[Error] TypeError: undefined is not an object (evaluating 'Package['aldeed:collection2-core'].Collection2')
	(anonymous function) (aldeed_schema-index.js:17)
	global code (aldeed_schema-index.js:144)
[Error] TypeError: undefined is not an object (evaluating 'Package['aldeed:collection2-core'].Collection2')
	(anonymous function) (aldeed_schema-deny.js:17)
	global code (aldeed_schema-deny.js:79)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (xolvio_cleaner.js:17)
	global code (xolvio_cleaner.js:105)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (hwillson_stub-collections.js:17)
	global code (hwillson_stub-collections.js:129)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (cfs_file.js:22)
	global code (cfs_file.js:757)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	(anonymous function) (cfs_tempstore.js:18)
	global code (cfs_tempstore.js:38)
[Error] TypeError: undefined is not an object (evaluating 'FS.File.prototype')
	(anonymous function) (cfs_access-point.js:113)
	(anonymous function) (cfs_access-point.js:219)
	(anonymous function) (cfs_access-point.js:299)
	global code (cfs_access-point.js:306)
[Error] TypeError: undefined is not an object (evaluating 'FS.File.prototype')
	(anonymous function) (cfs_upload-http.js:606)
	(anonymous function) (cfs_upload-http.js:613)
	(anonymous function) (cfs_upload-http.js:617)
	global code (cfs_upload-http.js:624)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (cfs_collection.js:22)
	global code (cfs_collection.js:496)
[Error] TypeError: undefined is not an object (evaluating 'FS.Collection.prototype')
	(anonymous function) (cfs_collection-filters.js:41)
	(anonymous function) (cfs_collection-filters.js:229)
	(anonymous function) (cfs_collection-filters.js:233)
	global code (cfs_collection-filters.js:240)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (cfs_worker.js:18)
	global code (cfs_worker.js:40)
[Error] TypeError: undefined is not an object (evaluating 'Package['ddp-client'].DDP')
	(anonymous function) (autoupdate.js:20)
	global code (autoupdate.js:206)
[Error] TypeError: undefined is not an object (evaluating 'Package.mongo.Mongo')
	global code (global-imports.js:3)
[Error] ReferenceError: Can't find variable: meteorInstall
	global code (app.js:1)

**Comment by abernix** [comment]
This may have been fixed recently with https://github.com/meteor/meteor/commit/e8b5ae673078fc97be524fb1fcef6b99c2787c2c.

@joerex Can you try again with Meteor `1.4.4-rc.6`?

    meteor update --release 1.4.4-rc.6

**Comment by joerex** [comment]
I'm actually using 1.5-beta.13

**Comment by abernix** [comment]
No, this is a fine place for it.  :smile:

Can you provide which version of `ddp-client` is showing in your `.meteor/versions` file?  And if it's anything besides `1.3.4-rc.6`, can you add `ddp-client@=1.3.4-rc.6` to your `.meteor/packages` file to pin it to that version?

**Comment by joerex** [comment]
That worked! I was at rc.1. Thanks @abernix
