### ISSUE TITLE
Paths in Babel plugins are relative to project root but have a leading slash

### ISSUE THREAD

**Issue by klaussner** [meteor/meteor#8566]
Some Babel plugins, for example [babel-plugin-root-import](https://github.com/entwicklerstube/babel-plugin-root-import), use the path of the file they are processing (provided by the build tool) to resolve module paths. Using such plugins with Meteor produces unexpected results because the paths have a leading slash (which makes them absolute) although they are relative to the project root, e.g., `/client/module.js`.

See [this reproduction repo](https://github.com/klaussner/meteor-8566-reproduction).

~I think Meteor should provide "real" absolute paths instead (in this case, `/home/<project path>/client/module.js`).~ (Relative paths are working, too.)

 I put together a [comparison that shows which paths browserify, gulp, Rollup, and webpack are using](https://github.com/klaussner/babel-path-comparison).

Meteor version: 1.4.4-rc.6

**Comment by benjamn** [comment]
How should the absolute path be exposed to the plugin?

**Comment by klaussner** [comment]
Changing [these lines in `babel-compiler`](https://github.com/meteor/meteor/blob/759671dc6c80a8385103d44c6e41c0ab84b002a5/packages/babel-compiler/babel-compiler.js#L81-L84) would work (although I don't know if that would have other consequences). For example, we could replace `"/" + inputFilePath` with `Npm.require("path").resolve(inputFilePath)` or simply `inputFilePath` or `"./" + inputFilePath`. It probably doesn't matter if the path is absolute or relative as long as it's unambiguous.

**Comment by Akarshit** [comment]
@benjamn Hey I would like to do a PR for this issue. Does the solution suggested in the above comment needs to be modified?

**Comment by klaussner** [comment]
Have you started to work on this, @Akarshit? If not, I would just go ahead and create a PR because I have made the changes in my Meteor fork already. :smile:

**Comment by Akarshit** [comment]
@klaussner No, you can create a PR :)
