### ISSUE TITLE
ObserveChanges returns all fields changed, not the specific one in query

### ISSUE THREAD

**Issue by davesierra** [meteor/meteor#8567]
As stated in the docs for observeChanges:
> Establishes a live query that invokes callbacks when the result of the query changes

I do the following query in Mongo
`
Users.find({ _id: userId }, { 'session.lastActive': 1 });
`
The result I get back is the doc with just the _id and session.lastActive fields. Good, I just want to observeChange in that lastActive field, however, if I set that up in Meteor:
```
let query = Users.find({ _id: userId }, { 'session.lastActive': 1 });
var observation = query.observeChanges({
    changed: function(id, fields) {
        console.log('a lastActive was changed', id, fields);
    }
)};
```

I then make a change in user.profile, it detects that change and returns user.profile in fields. Shouldn't it just listen on a change to user.session.lastActive and return that?

Either it's a bug or I'm misunderstanding something.

**Comment by klaussner** [comment]
I think you forgot the `fields` property in the second argument of `Users.find`. :)

```js
Users.find({ _id: userId }, {
  fields: { 'session.lastActive': 1 }
});
```

**Comment by davesierra** [comment]
Great, that was it. 

I suppose I'm misunderstanding the query syntax between Mongo and Meteor. My original query worked in Mongo ([reference](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/)) but not in Meteor, while yours works in Meteor but not in Mongo. Not sure why the difference but if you have anything to share with more information that'd be appreciated.

Thank you @klaussner
