### ISSUE TITLE
babel-runtime module.js:327 error

### ISSUE THREAD

**Issue by bioponx** [meteor/meteor#8568]
receiving error below while trying to run meteor npm install --save babel-runtime, appreciate any suggestions:

module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/t3/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/t3/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:79:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by hwillson** [comment]
Hi @bioponx - does this file exist on your side?

~/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/unsupported.js

**Comment by abernix** [comment]
Can you try this again with Meteor 1.4.4.1 or newer and let us know if the problem persists?  Just running the following should do the trick:

    meteor update

**Comment by hwillson** [comment]
We haven't heard back in a few weeks, so I'll close this off. Happy to re-open if you're still having this problem, and can answer the previously asked questions. Thanks!

**Comment by AnthonyLamot** [comment]
I'm currently experiencing the same problem. 

@hwillson the file does indeed exist.

What I've tried:
- reinstalling NPM / Node
- Installing NVM (https://github.com/creationix/nvm) and using node 4.8.2 (as suggested per https://stackoverflow.com/questions/43245144/meteor-npm-install-save-babel-runtime-error)

I am also getting this error when running `meteor npm` in existing apps.

**Comment by elenapons** [comment]
I had the same problem on 1.5.1. I solved it by downgrading to Meteor 1.4.4.3.

**Comment by abernix** [comment]
@elenapons We certainly don't want you to have to stay on an older version of Meteor.  If you could provide additional information and a reproduction on Meteor 1.5.1, we'll be happy to take a look and hopefully fix it!  I'd suggest removing components in your app until it's as close to a new Meteor app (i.e. such as that created with `meteor create test-app`) as possible while still demonstrating the problem.  Then just upload it to GitHub and open a new issue (this one is quite old and closed).

**Comment by tomasdms** [comment]
I'm getting the same error every time i try to use meteor npm install. i end up using npm install instead but i don't know if that's the right thing to do.
Running Meteor 1.5.1

I even get an error when i run meteor create test-app

and another when i try to run the app for the first time cause babel-runtime npm package fails to install and i have to do it manually with npm install --save babel-runtime. any ideas @elenapons  cause i feel like downgrading is my only choise.

**Comment by tomasdms** [comment]
I created a new issue like you said @abernix 
https://github.com/meteor/meteor/issues/9053

**Comment by mdkshuvo** [comment]
Unable to install babel-runtime. What can i do?
![bable](https://user-images.githubusercontent.com/30826181/33058192-9e677bb8-ceb8-11e7-9797-4ff354c77461.jpg)

**Comment by micahalcorn** [comment]
I have suddenly been getting this `Cannot find module '../lib/utils/unsupported.js'` on two different apps running Meteor `1.6.0.0`. It seems to crop up sometimes when I switch between the two apps and try to run any `meteor` command. I have tried to follow #9053, but the only the solution that works for me is to `curl "https://install.meteor.com/?release=1.6.0" | sh` every time, which removes my existing Meteor installation and starts fresh.
