### ISSUE TITLE
Cannot find module './id_map.js'

### ISSUE THREAD

**Issue by nska02** [meteor/meteor#8572]
**Platform**
macOS Sierra 10.12.4 (latest)

**Problem**
This morning (Friday 7th April CET), prior update of below packages, everything was fine. Now (this afternoon), even after meteor reset and full meteor uninstall, doesn't run.

```
accounts-base      upgraded from 1.2.15 to 1.2.16
accounts-google    upgraded from 1.1.1 to 1.1.2
accounts-password  upgraded from 1.3.4 to 1.3.5
babel-compiler     upgraded from 6.14.1 to 6.18.0
ddp-client         upgraded from 1.3.3 to 1.3.4
ddp-server         upgraded from 1.3.13 to 1.3.14
ecmascript         upgraded from 0.6.3 to 0.7.1
email              upgraded from 1.1.18 to 1.2.0
google-oauth       upgraded from 1.2.0 to 1.2.1
modules            upgraded from 0.7.9 to 0.8.1
modules-runtime    upgraded from 0.7.9 to 0.7.10
rate-limit         upgraded from 1.0.7 to 1.0.8
webapp             upgraded from 1.3.14 to 1.3.15
```

**List of packages**
I think my other installed packages are of no interest as I have also tried running a fresh Meteor project. Still crash.

**Any idea?**
modules-runtime issue?
It is one of the updated packages and seems to be referred to in the error log.

**Error Log**
```
W20170407-15:07:38.408(2)? (STDERR) /Users/arnaudlemaire/Sites/madApp/.meteor/local/build/programs/server/boot.js:356
W20170407-15:07:38.446(2)? (STDERR) }).run();
W20170407-15:07:38.447(2)? (STDERR)    ^
W20170407-15:07:38.447(2)? (STDERR) 
W20170407-15:07:38.447(2)? (STDERR) Error: Cannot find module './id_map.js'
W20170407-15:07:38.447(2)? (STDERR)     at Function.require.resolve (packages/modules-runtime.js:145:19)
W20170407-15:07:38.448(2)? (STDERR)     at Module.resolve (packages/modules-runtime.js:95:25)
W20170407-15:07:38.448(2)? (STDERR)     at Module.Mp.importSync (/Users/arnaudlemaire/.meteor/packages/modules/.0.8.1.17hgl99++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:79:29)
W20170407-15:07:38.448(2)? (STDERR)     at meteorInstall.node_modules.meteor.ddp-client.livedata_connection.js (packages/ddp-client/livedata_connection.js:1:152)
W20170407-15:07:38.449(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170407-15:07:38.449(2)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170407-15:07:38.449(2)? (STDERR)     at /Users/arnaudlemaire/Sites/madApp/.meteor/local/build/programs/server/packages/ddp-client.js:2322:1
W20170407-15:07:38.449(2)? (STDERR)     at /Users/arnaudlemaire/Sites/madApp/.meteor/local/build/programs/server/packages/ddp-client.js:2334:3
W20170407-15:07:38.449(2)? (STDERR)     at /Users/arnaudlemaire/Sites/madApp/.meteor/local/build/programs/server/boot.js:303:34
W20170407-15:07:38.450(2)? (STDERR)     at Array.forEach (native)
```

Thanks for your feedback.

**Comment by abernix** [comment]
> Platform
> macOS Sierra 10.12.4 (latest)

How about what version of Meteor you're using? :smile:

> prior update of below packages

How did you update those packages?  (What command?)

**Comment by abernix** [comment]
What happens if you pin `modules-runtime` to `0.7.9`?:

    meteor add modules-runtime@=0.7.9

(or by manually adding `modules-runtime@=0.7.9` in your `.meteor/packages`)

**Comment by chriscarpenter12** [comment]
I had the same issue as @nska02 this morning too. Pinning `modules-runtime` to `0.7.9` seems to have fixed it to allow my app to start now.

**Comment by gianniskarmas** [comment]
I have the exact same problem today.
Updated with 'meteor update'. 
Also it seems meteor npm version has changed from 4.8.0 to 4.3.0.

One of the following modules created the problem:
```
accounts-base      downgraded from 1.2.16 to 1.2.15
accounts-password  downgraded from 1.3.5 to 1.3.4
ddp-client         downgraded from 1.3.4 to 1.3.3
ddp-server         downgraded from 1.3.14 to 1.3.13
ecmascript         downgraded from 0.7.1 to 0.6.3
modules            downgraded from 0.8.1 to 0.7.9
modules-runtime    downgraded from 0.7.10 to 0.7.9
webapp             downgraded from 1.3.15 to 1.3.14

```

**Comment by claudey** [comment]
@gianniskarmas Must have been `accounts-password` then. Had the same issue, here's my log when I run `meteor add modules-runtime@=0.7.9`

<details>

[14:33:01] ayitey :: ayitey  ➜  ~/Projects/ghtechroundup ‹devel› » meteor add modules-runtime@=0.7.9                                                                                                130 ↵
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: accounts-password 1.3.4, was 1.3.5.
Constraints on package "accounts-password":
* accounts-password@1.3.4 <- top level
* accounts-password@1.3.4 <- top level
* accounts-password@1.1.6 <- vulcan:accounts 1.3.0 <- example-forum 1.3.0

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

</details>

**Comment by abernix** [comment]
Thanks for the updates, @chriscarpenter12 and @claudey.  This is being looked into right now.  If you could **edit** your existing comments above to add your Meteor version number (`meteor --version` from your project directory), that would be super helpful!  (Though we suspect this is only affecting those on the Meteor 1.4.2.x series!)

Also, if `meteor add` doesn't work for you (as @claudey indicated it didn't for them), try just putting `modules-runtime@=0.7.9` in the `.meteor/packages` file directly.

**Comment by benjamn** [comment]
This problem is occurring for two reasons:
* Meteor 1.4 through 1.4.2.7 always update to the latest versions of any packages when you run `meteor update --all-packages` or create a new app, which exposes you to breaking changes to core packages. This behavior was refined in 1.4.3 (see the first bullet point [here](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13)), but there's no way to fix older versions of Meteor without updating to a newer version of Meteor, at which point you might as well update to 1.4.3 or 1.4.4 (out now!).
* This specific [commit](https://github.com/meteor/meteor/pull/8439/commits/0eb52a1fd87f3a1fe1ec69e241a0b73421727d6a) is missing from older versions of Meteor, so `module.importSync` calls are not understood as dependencies, so the imported modules are often missing from the bundle.

I think we can publish a new version of the `reify` npm package and the `babel-compiler` Meteor package that generate `module.import` instead of `module.importSync` calls on older versions of Meteor, but **please try updating to Meteor 1.4.4 in the meantime**, since our ability to preserve backwards compatibility for Meteor 1.4.2.x won't last forever.

**Comment by chriscarpenter12** [comment]
@benjamn It was my intention to update my app to the latest meteor today. This is when things broke. When running `meteor update` I get `This project is already at Meteor 1.4.3.2, the latest release.` Anything else I need to do to get `1.4.4`?

**Comment by gianniskarmas** [comment]
meteor update --release 1.4.4

**Comment by benjamn** [comment]
@chriscarpenter12 The suggestion from @gianniskarmas is correct: Meteor 1.4.4 has been released but not yet "recommended," so a plain `meteor update` still gives you 1.4.3.2.

**Comment by gianniskarmas** [comment]
Thank you @benjamn and @abernix your suggestions and fixes did solve the problem.
v1.4.4 seems pretty stable ;)

**Comment by lovelamp** [comment]
Thanks fellas
issue resolved with the latest version 
using: meteor update --release 1.4.4 as mentioned by @gianniskarmas 

Thanks.
