### ISSUE TITLE
You can't create a Meteor project inside another Meteor project.

### ISSUE THREAD

**Issue by FBosler** [meteor/meteor#8576]
Update: Version back then was: METEOR@1.1.0.3

Hi everybody,

first of all. There has been a similar issue in the past, however it has been closed and I feel like the suggested solution doesn't work for my situation (https://github.com/meteor/meteor/issues/3714).

So I started building an app with a friend about a year and a half ago (Version "METEOR@1.1.0.3"). Both of us got new jobs and didn't really have much time to continue working on our app, which is why we put the operation on hold.

Now I do find myself having some time again and wanted to dust up my meteor skills, for that I wanted to do the tutorial again (needless to say that I am not the smart one out of myself and my buddy). So I installed the newest meteor version. Now when trying to  
`meteor create ~/my_cool_app` 
I get the above error. I searched for /.meteor/packages as suggested in the other post, but I feel like I really shouldn't delete the folder, since there are a LOT of packages in there. Would that kill my ability to continue working on our app?

Cheers

**Comment by laosb** [comment]
Actually you may just do `meteor create my_cool_app` in your home. I guess meteor shouldn't check `~/.meteor` in your case - should be fixed.

**Comment by laosb** [comment]
You can try to create your project under a subfolder in your home

**Comment by laosb** [comment]
Actually I think, meteor should check whether it's a `.meteor` for a project or for the installation.

**Comment by FBosler** [comment]
So I am not sure where exactly you are suggesting I create the project, but just for clarity.
my meteor folder (I think thats my meteor installation) resides in /Users/MyName/.meteor
I can not create a meteor project anywhere. I tried in:
/Users
/Users/MyName
/Users/MyName/Subfolder
/Users/MyName/.meteor

Getting the same error message, no matter what.
Cheers

**Comment by klaussner** [comment]
It should be safe to delete the packages in */Users/MyName/.meteor* because this folder is just a cache of previously downloaded packages. Meteor will re-download them if you try to run an app and it doesn't find the required packages there.

Maybe it would help to reinstall Meteor with `curl https://install.meteor.com/ | sh`, which will remove your previous installation automatically.

**Comment by FBosler** [comment]
Hi Klaussner,

thx alot. Worked as you suggested.

FYI: I did install meteor via the above command, this didn't solve the described bug though. One had to manually delete /.meteor.

Cheers
