### ISSUE TITLE
Make peer NPM deps work in test driver packages with test-packages

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#8577]
@abernix @benjamn 

In https://github.com/meteor/meteor/issues/7500, it says that peer package deps work with test-packages after 1.4.1. I confirmed this, but they don't work in the test driver package itself or any packages that the test driver package depends on. Is this something you could easily fix?

The upshot is that if using `dispatch:mocha` for testing with a client headless driver, you currently DO still need a scaffolding app because `dispatch:mocha` depends on `aldeed:browser-tests`, which does a `require` for the NPM packages it needs, expecting you to have made them available somehow. Example: https://github.com/aldeed/meteor-browser-tests/blob/master/browser/chromedriver.js#L28-L34 This works fine for app testing but not with test-packages.

I don't want to add Npm.depends in `aldeed:browser-tests` itself because I want people to pick whatever versions of the browser drivers work best with their app, and not need to release updates for new versions.

**Comment by macsj200** [comment]
Let's get a small reproducible example of this issue.

**Comment by aldeed** [comment]
@macsj200 @benjamn @hwillson Here is a simple package to show the issue: https://github.com/aldeed/aldeed-test-pkgs-peer

**Comment by hwillson** [comment]
Confirmed - thanks for the repro @aldeed!

**Comment by jamiter** [comment]
Now that 1.6 has been released we can no longer use `practicalmeteor:mocha`. So we tried updating to `meteortesting:mocha`, but ran into this issue.

What to do?

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Comment by serut** [comment]
My meteor package [meteor-coverage](https://github.com/serut/meteor-coverage) has the same issue described here.
If I try to save an NPM dependency in the package, it won't be available while the package is under test. But if I create an empty application and add that same package, it will be available while testing. 

So the workaround for now is to create an empty Meteor app, then setup everything to launch tests from that app.

```
# meteor npm run setup-test
$ rm -rf ./someapp && 
meteor create --bare someapp && 
cd someapp && 
cp ../.coverage.json . && 
meteor npm i --save selenium-webdriver@3 chromedriver &&
mkdir packages &&
ln -s ../../ ./packages/meteor-coverage

# meteor npm test
$ meteor npm run setup-test &&
cd someapp &&
TEST_BROWSER_DRIVER=chrome COVERAGE_VERBOSE=1 COVERAGE=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test-packages --once --driver-package meteortesting:mocha ./packages/meteor-coverage
```

We can conclude there is a diff between `test-packages` inside an app and inside a package.

**Comment by mitar** [comment]
My workaround is to do:

```
$ mkdir -p /tmp/app
$ cat > /tmp/app/package.json
{
  "dependencies": {
    "@babel/runtime": "^7.15.4",
    "jquery": "^3.6.0",
    "meteor-node-stubs": "^1.1.0",
    "puppeteer": "^1.20.0"
  }
}
$ TEST_BROWSER_DRIVER=puppeteer meteor test-packages ./ --once --driver-package meteortesting:mocha --test-app-path /tmp/app
```

This makes `puppeteer` NPM package be installed for tests to get it.
