### ISSUE TITLE
[1.4.4.1] Can't update meteor from 1.4.3.2

### ISSUE THREAD

**Issue by cyclops24** [meteor/meteor#8579]
I try to update one of my project to 1.4.4.1 with `meteor update` command but it returns below output:

```
$ meteor update
This project is already at Meteor 1.4.3.2, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest
version available:
 * standard-minifier-js 1.2.3 (2.0.0 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * minifier-js 1.2.18 (2.0.0 is available)    
To update one or more of these packages, pass their names to 
`meteor update`, or just run `meteor update --all-packages`.
```

What is the problem?

**Comment by laosb** [comment]
Meteor 1.4.4.1 is not the "recommended" version for now, so you should just update manually by `meteor update --release 1.4.4.1`.

**Comment by cyclops24** [comment]
@laosb My project now based on Meteor 1.4.3.2.
What about Meteor 1.4.4 ?? Why Meteor can't update to 1.4.4 ?
Where we can see "recommended versions"?

**Comment by laosb** [comment]
`meteor show METEOR`.

Latest recommended version is the version you can update to without `--release` - they are tested and tried by many. 1.4.4.1 is not a recommended version yet. But you can always update to any version published by using `--release` and a version number.

**Comment by cyclops24** [comment]
@laosb oh it's a new command for me. I can't find this command in [CLI section of docs](http://docs.meteor.com/commandline.html#meteorshow) maybe it's better to mention it there.

**Comment by laosb** [comment]
Actually it wasn't a new command: 

> Shows more information about a specific package or **release**: name, summary, the usernames of its maintainers, and, if specified, its homepage and git URL.

`METEOR` is just the official release.

**Comment by abernix** [comment]
@cyclops24 You're right that the docs certainly don't make it clear that there is a parameter available to `meteor show`.  The command `meteor show --help` shows a bit more detail. 

That's actually a reasonable new addition to the docs in general though, so if you'd be willing to open a PR to further improve it over on [the docs repo](https://github.com/meteor/docs/issues), it would be appreciated!
