### ISSUE TITLE
TCP Timeouts and Creators Update

### ISSUE THREAD

**Issue by ExcelNet-Public** [meteor/meteor#8582]
We are running 1.4.3.2 on Windows 10 x64. We were having many issues with TCP sockets timing out withe the `numtel:mysql` package and thought it was the package. However moving the application to our staging server on the same LAN segment, same firewall, but simply Linux based the problem goes away completely. So, seems more Windows related.

Updated to the Creator's Update over the weekend to get some experience with it before end users start calling in with questions and to see if it helped with the issue above. Now, our app with NO changes produces the following immediately after start:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
It will restart and then seems responsive for a while.

**Comment by ExcelNet-Public** [comment]
We are running 1.4.3.2 on Windows 10 x64.  We were having many issues with TCP sockets timing out withe the numtel:MySQL package and thought it was the package.  However moving the application to our staging server on the same LAN segment, same firewall, but simply Linux based the problem goes away completely.  So, seems more Windows related.

Updated to the Creator's Update over the weekend to get some experience with it before end users start calling in with questions and to see if it helped with the issue above.  Now, our app with NO changes produces the following immediately after start:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

It will restart and then seems responsive for a while.

**Comment by laosb** [comment]
@ExcelNet-Public I prettified your description and get it to the right place.

From your description, it might be an issue of [`numtel:mysql`](https://github.com/numtel/meteor-mysql/) instead of Meteor itself. From its GitHub activity, I could say it is no longer maintained. You may choose not to use it anymore.

**Comment by ExcelNet-Public** [comment]
As mentioned moving it to our Linux based staging server running identical code "fixes" the problem in the first paragraph so I do not think it is package related.  Yes, it seems to be a dead project, but it works for the needs we have (until recently anyhow).

The out of memory is definitely new to the Creator's update.

Thanks for getting things in the right place, appreciate it!

**Comment by laosb** [comment]
Maybe some dependencies of that package has some platform specific problem - I don't really think it's related to Meteor itself. How much memory do you have on your Linux staging server and Windows server?

**Comment by ExcelNet-Public** [comment]
The issue is this is an app that has been in development for over a year working great in that area.  Only over the past couple weeks the problem showed up which seem to coincide with the 1.4.3.1 / .2 updates.  I am not saying it is 100% meteor, just the timing.    

Actually my development machine has 16GB RAM and the staging server is a VM running 8GB.

Appreciate the questions and assistance, thanks!

**Comment by ExcelNet-Public** [comment]
So, I decided it was time for more drastic fixes.  I decided to get try the following:

1. Backed up the project
2. Ran `meteor update` to get things on 1.4.4.1
3. Ran `meteor reset` to clear the project
4. Started up the project

YEAH!!!!  This seems to have "fixed" both of the issues we were reporting above.  Seems that over time there must be some "artifacts" left through the build / upgrade processes that started causing us issues and that certainly needs to be looked at.  But for the issues reported they both appear resolved with these steps.

Please be aware of what the `meteor reset` command will do before running it!  Pretty much a wipe and restart - though of course you do not lose any of your code.
