### ISSUE TITLE
New Google OAuth on Cordova doesn't properly fill the user.service document and/or profile

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8586]
Meteor@1.4

When signing in from Cordova, Meteor@1.4 uses `cordova-plugin-googleplus` but it doesn't properly fetch user data from Google on successful login.

The HTTP call in https://github.com/meteor/meteor/blob/devel/packages/google-oauth/google_server.js#L13-L16 doesn't fetch some important data such as `first_name`, `last_name` or `refresh_token`. The `OAuth.registerService` callback fetches everything correctly but it never seems to be called when logging in from Cordova.

**Comment by benjamn** [comment]
@realyze Please close this issue whenever you can verify that `google-oauth@1.2.2` fixes the problem!

**Comment by benjamn** [comment]
Closing since I believe this is fixed, but please feel free to reopen if you discover otherwise.

Note that the latest version is now `google-oauth@1.2.3`, with the changes in https://github.com/meteor/meteor/pull/8604.
