### ISSUE TITLE
Meteor node debugging does not map origin source files to files on disk.  Required for VS Code.

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#8590]
I have switched over to using Microsoft VS Code as my editor.   I struggled to get the debugger working with meteor for node.  [I think some other folks were running into problems too](https://forums.meteor.com/t/using-visual-studio-code-for-meteor-development/21058/9).

I created [VSCode#22818](https://github.com/Microsoft/vscode/issues/22818) to get the VS Code take on the issue.  I just got a [response](https://github.com/Microsoft/vscode/issues/22818#issuecomment-293671026).  In essence:
- the meteor protocol for source maps (`e.g. meteor://💻app/server/main.js`) is confusing VS Code and they cannot map to the files on disk.  Can this be changed to be more debugger friendly?
- using the [new inspector protocol](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html#debugger_v8_inspector_integration_for_node_js) may be able to handle the way meteor creates source maps?

Either way, I am hoping that the full fidelity of VS Code debugging could be available for debugging meteor node.

**Comment by cantonese84** [comment]
Attempted to debug server code using VS Code on Meteor 1.6-beta.4, but was not able to set break points.  The reason given was "generated code not found (source map problem)?".  If I understand the above the options correctly, running Meteor 1.6-beta.4 should work as it's using the new inspector protocol.  Here is the VS Code launch.json that I used:

    {
      "name": "Server: attach",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "address": "localhost",
      "restart": false,
      "sourceMaps": true,
      "outFiles": ["${workspaceRoot}/.meteor/local/build/programs/server"],
      "localRoot": "${workspaceRoot}",
      "remoteRoot": null
    }

**Comment by MartinBucko** [comment]
@cantonese84  Use `"protocol": "inspector"` (supported from node v6.3+) more here: 
https://github.com/Microsoft/vscode/issues/256#issuecomment-312260958

**Comment by cantonese84** [comment]
@MartinBucko Your launch config works!  Thanks.  However, for me it took a long time for the debug session to start in VS Code.  I noticed the session won't be ready until the debug console shows the message "Debugger did not attach after 5 minutes; continuing."  That looks like the Meteor is still stopping at the first line and won't continue until it times out.  Do you have this problem?

**Comment by MartinBucko** [comment]
@cantonese84 it take max 15sec. to start in meteor in debug mode, even if i remove `.meteor/local/build` directory.
After start it break in debug.js script generated by meteor. This i personally want to disable but i don't now how. Its annoying.. After this i press F5 and it will continue to next breakpoints. You can also adjust `timeout` in launch.json config. But its true 5min. is to long. Maybe some wrong in config.

**Comment by abernix** [comment]
@MartinBucko I believe VS Code debugger supports "[blackboxing](https://github.com/Microsoft/vscode-chrome-debug#skip-files--blackboxing--ignore-files)" so you should be able to add `debug.js` to that configuration to have it skip over that file's `debugger;` breakpoint.  (In versions of Meteor prior to 1.6, I think you'd have to blackbox `main.js`, though it should also work!).

**Comment by MartinBucko** [comment]
@abernix Yes, it is possible, thanks. I found options for that: `"skipFiles": ["debug.js"]` in launch.json ... (An array of glob patterns for files to skip when debugging.)

**Comment by cantonese84** [comment]
The 5 minutes startup delay (or timeout) in VS Code debug is still happening on my Windows 10, with or without `"skipFiles": ["debug.js"]`.  But on my OS X, debug starts normal.  So it seems the problem only happens in Windows 10.  Both environments have the same VS Code, VS Code extensions, and source code.

Also, is there working launch.json configuration for node attach?  Node launch method works fine, but making any change to source takes quite some time for the restart to finish.  I am hoping node attach would be faster.

**Comment by quintstoffers** [comment]
This might be required for Webstorm as well. The debugger connects correctly (using the "chromium remote" configuration), but exectution doesn't stop on breakpoints. Adding `debugger` statements works, but Webstorm isn't able to detect the source file (it navigates to `.meteor/local/build/.../packagename.js` (or `local-test_packagename.js` when running with test-packages).

**Comment by brucejo75** [comment]
With 1.6-rc.9 this has been fixed.  Thanks to @benjamn!!
