### ISSUE TITLE
Is not issue: Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Nemra1** [meteor/meteor#8593]
hello..My Post is not issue or bugs..just i need help in this...
im trying to send text with color from input form 
example 👍:
Chat windows with input form and select color for text ..My Problem ( Text Msg keep in Black and not changed to my Color and delivery to user2 with black color also..
![test](https://cloud.githubusercontent.com/assets/22897987/25002022/7880e0ca-2048-11e7-90a4-ac46859c9063.jpg)
My code
js :
```
<script type="text/javascript">
	function Color(obj) {
		document.getElementById("myTextArea").style.color = obj.value;
			document.getElementById("{{_id}}").style.color = obj.value;					
	}
</script>

```
Html code 
`<textarea  id="myTextArea" dir="auto" name="myTextArea" maxlength="{{maxMessageLength}}" class="message-form-text input-message autogrow-short" placeholder="{{_ 'Message'}}"></textarea>
`
im trynig with .coffe file and add this code
```
Color = (obj) ->
  document.getElementById('myTextArea').style.color = obj.value
  document.getElementById('{{_id}}').style.color = obj.value
  return
```
but no luck...Thanks...

**Comment by hwillson** [comment]
Hi @Nemra1 - GitHub issues are reserved for Meteor bugs and/or feature requests. To get help with using Meteor, please post on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). Thanks!
