### ISSUE TITLE
Nested imports not working anymore with v1.4.4.1

### ISSUE THREAD

**Issue by jay1337** [meteor/meteor#8595]
Hello,

Nested imports in my app do not work anymore with new version 1.4.4.1 (everything was ok with 1.4.3.2).
.
When I try to run my app, I get this error:

`W20170413-16:24:50.671(2)? (STDERR) D:\todo\.meteor\local\build\programs\server\app\app.js:3029
W20170413-16:24:50.848(2)? (STDERR)             import { mailError } from '/server/mailing.js';
W20170413-16:24:50.851(2)? (STDERR)             ^^^^^^
W20170413-16:24:50.853(2)? (STDERR)
W20170413-16:24:50.855(2)? (STDERR) SyntaxError: Unexpected reserved word`

The source code is something like:

`export const myFunction= function(arg) {
        // ...
        const res = otherFunction();
        // ...
	if (arg == res) {
		import { mailError } from '/server/mailing.js';
		mailError("Error !");
	}
       // ...
};
`
Thanks for your help.

**Comment by tab00** [comment]
After updating I'm getting "SyntaxError: Unexpected reserved word" error too, referring to the word `import` with code that looks like this:

```
export const method1 = new ValidatedMethod({
     name: "method1",
     validate: null,
     run() {
         import Pusher from "pusher-client"
     }
 });
``` 

I have so many `import`s all over the place and I don't want to have to rewrite them all to `require`s, so my app is now broken.

Please fix this as soon as possible. Thank you.

**Comment by benjamn** [comment]
Are either of you using `.babelrc` files?

**Comment by tab00** [comment]
No, I don't use  `.babelrc` files.

The error appears at a final stage of build even when I create a skeleton app using `meteor create test` and write a simple function like above.

**Comment by tab00** [comment]
I'm using Windows 10 platform, in case that may be relevant.

**Comment by abernix** [comment]
Posting this forum post here about the same topic: https://forums.meteor.com/t/did-meteor-1-4-4-remove-conditional-imports/35621 (no reproduction, unfortunately).

**Comment by jay1337** [comment]
I don't use `.babelrc` file. I'm using Windows 7.

**Comment by benjamn** [comment]
This should be fixed if you update the `babel-compiler` package to version 6.18.2 by running `meteor update`. Thanks for reporting this issue, and I hope you'll take some time to test beta versions of future Meteor releases, to help identify regressions like this one.

**Comment by jay1337** [comment]
Fixed ! Thanks.

**Comment by tab00** [comment]
It is now indeed fixed. Thank you Ben.
