### ISSUE TITLE
Random silent fails when using Email.send in email@1.2.0

### ISSUE THREAD

**Issue by jbbr** [meteor/meteor#8596]
As already discussed in #8495 I'm creating a new issue for this issue:

After upgrading the email package to 1.2.0 I'm experiencing apparently random problems when using Email.send within Meteor methods.

The problem occurs in approximately 10% of all method calls with Email.send's. Maybe less. **But once it occurred any subsequent mail sends fail.** A restart of the server is required to get it working again.

Meteor project:
- METEOR@1.4.4.1
- email@1.2.0

Example code (server/main.js)
```js
Meteor.methods({
  mailFail() {
    console.log('Starting mail loop...')

    for (let i = 0; i < 10; i++) {
      console.log('Send mail', i)
      try {
        Email.send({
          from: 'Test <test@example.com>',
          to: 'some-real-email@example.com',
          subject: 'Just a test',
          text: 'Does it work? ' + i,
        })
      } catch (e) {
        console.error('got email error', e)
        throw e
      }
    }
    console.log('Method finished')
  }
})
```

When calling from client with `Meteor.call('mailFail', console.log)` multiple times the server output looks like:

```bash
$ MAIL_URL=smtp://user@example.com:password@smtp.mailgun.org:587 meteor
...
=> App running at: http://localhost:3000/
I20170413-17:29:22.738(2)? Starting mail loop...
I20170413-17:29:22.740(2)? Send mail 0
I20170413-17:29:24.868(2)? Send mail 1
I20170413-17:29:25.517(2)? Send mail 2
I20170413-17:29:26.313(2)? Send mail 3
I20170413-17:29:26.977(2)? Send mail 4
I20170413-17:29:27.594(2)? Send mail 5
I20170413-17:29:28.231(2)? Send mail 6
I20170413-17:29:28.848(2)? Send mail 7
I20170413-17:29:29.491(2)? Send mail 8
I20170413-17:29:30.122(2)? Send mail 9
I20170413-17:29:30.745(2)? Method finished
I20170413-17:30:58.121(2)? Starting mail loop...
I20170413-17:30:58.122(2)? Send mail 0
```

In this case the second call resulted in the problem. No email was sent in the second call.
It might take quite a few attempts to reproduce this... 

After the method gets stuck this is the situation:
- Any subsequent call of this method from the same client console does not produce any output in the meteor server console
- When reloading the page in the browser and calling the method again the output stops at "Send mail 0" every time (100% failure rate)
- When restarting the meteor server while the client is still open the method is automatically called again and mail processing works now again (with the ~10% random failure rate)

Other observations:
- Always or almost always the call stops when sending the first mail - if the first mail can be send usually all other mails are sent successfully too
- I'm 60% sure that this problem also occured when using Mailtrap as SMTP. But I wasn't able to reproduce the bug with mailtrap this time. So I might be wrong and it's dependant on the SMTP server used (In this case Mailgun)

**Comment by edemaine** [comment]
Discussion is happening on #8591

**Comment by jbbr** [comment]
Oh well thanks, I have overlooked this issue. I'll watch it.

Just wondering where or when they get the error message 
> 421 Timeout waiting for data from client.

Maybe the mailgun smtp has a very long timeout or something. Because even in a case of a timeout/mail error I would expect the meteor method to continue afterwards and not pause forever.

**Comment by abernix** [comment]
Thanks for reporting.  Closing in favor of #8591.
