### ISSUE TITLE
[Proposal] Use ~ to reference to NPM package in css preprocessors

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8601]
I'm the maintainer of the `fourseven:scss` package.
@ghybs [suggested](https://github.com/fourseven/meteor-scss/issues/246) to add support for using `~` to reference to NPM packages, in line with webpack for Sass and Less.

Webpack needs to distinguish between bootstrap and ~bootstrap, because CSS and Sass/Less files have no special syntax for importing relative files. Writing @import "file" is the same as @import "./file";

I just wanted to ask @benjamn on his input for using this syntax. Since I want to keep behavior similar between different CSS preprocessors like Sass and Less in Meteor..

**Comment by hwillson** [comment]
There hasn't been an answer here and https://github.com/fourseven/meteor-scss/issues/246 has been green flagged to move ahead with the `~` syntax, so I'll close this off. Thanks!
