### ISSUE TITLE
Email 1.2.1 Error: Greeting never received - Nodemailer

### ISSUE THREAD

**Issue by ixdi** [meteor/meteor#8612]
Hi,

The new version of email package 1.2.1 gives us an 
```js
Exception while invoking method 'forgotPassword' { stack: 'Error: Greeting never received\n at Mail._syncSendMail }
```
Maybe it's related with this issue in Nodemailer and the secure option.

[https://github.com/nodemailer/nodemailer/issues/441](https://github.com/nodemailer/nodemailer/issues/441)

Thanks

**Comment by lucfranken** [comment]
Can confirm that this happens also with 1.2.0 updated from 1.1.18 with the standard Meteor update. We are using Mailgun as e-mail provider.

**Comment by deeeed** [comment]
Same issue for me, any known workaround ?

**Comment by abernix** [comment]
This sounds related to the discussion that started [in this thread](https://github.com/meteor/meteor/issues/8591#issuecomment-294713425).

Are any of you using a secure SMTP port number (465, 587, etc.) but using the insecure `smtp:` schema (rather than `smtps:`) in your `MAIL_URL`?

**Comment by deeeed** [comment]
yes :) thanks

**Comment by ixdi** [comment]
Thank you! Sorry about I didn't saw the related issue.

**Comment by hwillson** [comment]
@deeeed @ixdi I can't quite tell from your last comments; did lining up your secure SMTP port number choice with `smtps:` fix this for you? Let us know if this can be closed. Thanks!

**Comment by deeeed** [comment]
@hwillson yes it is fixed **BUT** I had to upgrade node to **4.5.0**.
Apparently "smtps" causes an error with nodemailer for version below 4.5.0:

```
2|YueLaoAp | TypeError: this is not a typed array.
2|YueLaoAp |     at Function.from (native)
2|YueLaoAp |     at LastNewline._flush (/opt/pm2-meteor/YueLaoApp/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/mime-node/last-newline.js:28:26)
2|YueLaoAp |     at LastNewline.<anonymous> (_stream_transform.js:118:12)
2|YueLaoAp |     at LastNewline.g (events.js:260:16)
2|YueLaoAp |     at emitNone (events.js:67:13)
2|YueLaoAp |     at LastNewline.emit (events.js:166:7)
2|YueLaoAp |     at prefinish (_stream_writable.js:471:12)
2|YueLaoAp |     at finishMaybe (_stream_writable.js:479:7)
2|YueLaoAp |     at endWritable (_stream_writable.js:491:3)
2|YueLaoAp |     at LastNewline.Writable.end (_stream_writable.js:456:5)
2|YueLaoAp | 2017-04-22 07:20:45 ERROR uncaughtException: this is not a typed array.
```

[http://stackoverflow.com/questions/42331751/typeerror-this-is-not-a-typed-array-with-ws-js-in-node-js](url)

**Comment by edemaine** [comment]
@deeeed I'm confused: doesn't [Meteor depend on Node 4.8.1](https://blog.meteor.com/announcing-meteor-1-4-4-11027f33e3bf)?

@abernix Should I/we restore the old behavior of "port 465 implies smtps"?  (My personal opinion is that the new behavior is "more correct", but it is also less compatible.)  Otherwise we should put a warning in the release notes.  (Incidentally, I didn't know that [port 465 has been deprecated since 1999, though is still in active use](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Ports).  But I don't see anything about assuming smtp vs. smtps.)

**Comment by deeeed** [comment]
@edemaine right! So the problem was from me using pm2 to run my app and not checking version constraints...

**Comment by ixdi** [comment]
@hwillson Sorry but when we deployed to Galaxy with smtps and email@1.2.1 the error persisted.
```js
Error: Greeting never received
```
So the error is not resolved. There's no advise when we deploy with email@1.2.0

**Comment by edemaine** [comment]
@ixdi What does your MAIL_URL look like?

**Comment by ixdi** [comment]
@edemaine  
```json
"MAIL_URL":"smtps://<user>:<password>@smtp.mailgun.org:465"
```

**Comment by edemaine** [comment]
@ixdi Did you restart/redeploy Meteor after resetting that variable?  Sorry for asking the obvious, but I'm pretty sure it's the smtp vs. smtps issue not yet resolved.  (Regarding your original question, there's no longer a "secure" option in Nodemailer -- it's extracted directly from the URL.)

**Comment by ixdi** [comment]
@edemaine You are right! It's obvious but we deployed without settings.json. 
We have deployed an update now and there's no advise, it's resolved!

Thank you!!

**Comment by edemaine** [comment]
Awesome!!  Sounds like 1.2.1 is working for everyone then.

**Comment by hwillson** [comment]
Excellent news! Closing - thanks everyone!

**Comment by mgscreativa** [comment]
Hi! I just filled another bug here https://github.com/meteor/meteor/issues/8696 I think it's not related with this one so maybe would be wise to check it out...

**Comment by raghavgarg1257** [comment]
I am having same issue, if please someone can confirm if my credentials are wrong.

with 

    MAIL_HOST=ssl://email-smtp.us-east-1.amazonaws.com 

I am getting `ENOTFOUND`, but with

    MAIL_HOST=email-smtp.us-east-1.amazonaws.com 

I am getting `Greeting never received`

**Comment by geraldooi** [comment]
> This sounds related to the discussion that started [in this thread](https://github.com/meteor/meteor/issues/8591#issuecomment-294713425).
> 
> Are any of you using a secure SMTP port number (465, 587, etc.) but using the insecure `smtp:` schema (rather than `smtps:`) in your `MAIL_URL`?

I tried `smtp+starttls`, and it works. Thanks🎉
