### ISSUE TITLE
TAPi18n.__ is not a function

### ISSUE THREAD

**Issue by luixal** [meteor/meteor#8617]
Hi,

I'm trying to include TAPi18n in a meteor package and, after following the instructions in the [Developing Packages](https://github.com/TAPevents/tap-i18n#developing-packages) section, I just keep getting this error:

```
TypeError: TAPi18n.__ is not a function
```

My `package-tap.i18n` file is just like the doc one, changing the `namespace` from `null` to `profile` (because I want these translations to be available to the project using this package):

```json
{
  "translation_function_name": "__",
  "helper_name": "_",
  "languages_files_dir": "lib/i18n",
  "namespace": "project"
}
```
Inside `lib/i18n` there are three translation files (tested in another project so... no problems here, i guess).  Default lang file `en.i18n.json` is included.

In the `package.js` file I have this code for the onUse function:

```javascript
Package.onUse(function(api) {
  api.versionsFrom('1.4.4.1');

  api.use(['tap:i18n@1.8.2'], ['client', 'server']);
  api.addFiles("package-tap.i18n", ["client", "server"]);

  api.use(
    [
      'ecmascript',
      'less@2.7.9', // bug here in less package? (stays @=1.0.14 if no update run)
      // some other dependencies included here
    ]
  );
  api.addFiles(
    [
      // some util files go here.
    ],
    ['client', 'server']
  );

  // include collections files:
  api.addFiles(
    [
      // some other files. Nothing to do with langs
    ],
    ['client', 'server']
  );

  // lang files included here:
  api.addFiles(
    [
      './lib/i18n.js',
      './lib/i18n/es.i18n.json',
      './lib/i18n/ca-ES.i18n.json',
      './lib/i18n/en.i18n.json'
    ],
    ['client', 'server']
  );

  // export public values:
  api.export(
    [
      'TAPi18n', // tried (un)commenting this, no difference
    ],
    ['client', 'server']
  );
  // main module file:
  api.mainModule('dummyPackage.js');
});
```

In the `dummyPackage.js` file, I've included some logging to test errors, like this:

```javascript
console.log('running!');
console.log(TAPi18n);
console.log('yep? ' + I18N.translate('place_name'));
```

I see the _running!_ message. I see some weird when logging the TAPi18n (non initialized I guess):

```
{
  conf: null,
   _enabled: [Function],
  registerHTTPMethod: [Function]
}
```

and when reaching the third line, I got this error:

```
TypeError: TAPi18n.__ is not a function
    at meteorInstall.node_modules.meteor.servo:servo-collections.dummyPackage.js (packages/servo:servo-collections/dummyPackage.js:20:28)
    at fileEvaluate (packages\modules-runtime.js:197:9)
    at require (packages\modules-runtime.js:120:16)
    at C:\Users\laperez.ACSSYC\dev\web\meteor\servo-integrator-aena-pmrs\.meteor\local\build\programs\server\packages\servo_servo-collections.js:8971:15
    at C:\Users\laperez.ACSSYC\dev\web\meteor\servo-integrator-aena-pmrs\.meteor\local\build\programs\server\packages\servo_servo-collections.js:8984:3
    at C:\Users\laperez.ACSSYC\dev\web\meteor\servo-integrator-aena-pmrs\.meteor\local\build\programs\server\boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\laperez.ACSSYC\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\laperez.ACSSYC\dev\web\meteor\servo-integrator-aena-pmrs\.meteor\local\build\programs\server\boot.js:128:5
```

Any ideas about what am I doing wrong?

**Comment by hwillson** [comment]
Hi @luixal - sorry to hear you're having trouble. Just a friendly reminder, Meteor's GitHub issues are reserved for bugs (or feature requests) with Meteor itself. Reaching out for help with third party packages like `tap:i18n` is best handled on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (or within the [tap:i18n repo](https://github.com/TAPevents/tap-i18n/issues) itself). If you're looking for a runnable example that leverages `tap:i18n`, take a look at the Guide's reference app [`todos`](https://github.com/meteor/todos). It sounds like you're already using it in other apps though, so if your problem is coming from using it within a package specifically, maybe try searching existing package based implementations that leverage `tap:i18n`, within GitHub itself (and compare how they're approaching things with what you're doing). For example, the following quick search returns several apps following this approach: https://github.com/search?q=api.addFiles+package-tap.i18n&type=Code&utf8=✓

Closing for now - thanks for reaching out!

**Comment by luixal** [comment]
Hi @hwillson well, it's a bug within code or within documentation...

From the docs:

````
// tap:i18n automatically separates the translation strings of each package to a
    // namespace dedicated to that package, which is used by the package's translation
    // function and helper. Use the namespace option to set a custom namespace for
    // the package. By using the name of another package you can use your package to
    // add to that package or modify its translations. You can also set the namespace to
    // "project" to add translations that will be available in the project level.
    "namespace": null
```

I'm using the ```"namespace": "project"``` option (I want the translations in the package available to the main project) and it is not working at all. If I add a local translation file then it works.

It didn't even work (function TAPi18n.__ is not defined, function `__` inside package isn't defined also) until I added tap:i18n package to the main project, created an i18n directory and a en.i18n.json file... what docs say clearly it's not needed at all.

**Comment by hwillson** [comment]
I meant that GitHub issues in this repo (the main Meteor framework repo) are reserved for issues with the Meteor framework itself. Your issue sounds more like a problem with the [tap:i18n](https://github.com/TAPevents/tap-i18n/issues) package itself (whether it's a bug in the package, missing documentation, or an application problem). In any case, there are many open issues against the Meteor framework itself, all of which take precedence over 3rd party package issues. Honestly, reaching out via the [tap:i18n](https://github.com/TAPevents/tap-i18n/issues) repo, the [Meteor forums](https://forums.meteor.com), or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor), will be your best bet. Thanks!

**Comment by luixal** [comment]
:O

Totally my fault, I was convinced to be posting in the tap:i18n repo. So sorry! :(
