### ISSUE TITLE
Package testing npm requirements not working

### ISSUE THREAD

**Issue by macsj200** [meteor/meteor#8619]
There seem to be a variety of issues associated with loading npm dependencies in the `test-packages` testing context. The primary issue thread I found was https://github.com/meteor/meteor/issues/6827, but it's been closed for a while and seems to not be receiving any attention. I contend that something is wonky in the way npm dependencies are loaded when running the `test-packages` command.

Specifically, I've been running into an issue with `dispatch:mocha` browser tests. I've opened https://github.com/aldeed/meteor-browser-tests/issues/5 (this is the underlying package triggering the issue).

Does anyone have any idea why meteor might be loading npm dependencies strangely in the testing context?

Specifically, I run `TEST_BROWSER_DRIVER=chrome meteor test-packages --driver-package dispatch:mocha` and receive the error message `Error: When running tests with TEST_BROWSER_DRIVER=chrome, you must first "npm i --save-dev selenium-webdriver chromedriver"`. Obviously, I've already run that command at this point, and I'm able to drop into a node shell and `require(...)` the relevant package.

**Comment by hwillson** [comment]
Hi @macsj200 - any chance you could create a small, runnable reproduction demonstrating this issue? Providing a reproduction will not only help with troubleshooting, but will also improve the chances of someone looking into this sooner than later. For more info, see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug). Thanks!

**Comment by aldeed** [comment]
This is the same issue I brought up in https://github.com/meteor/meteor/issues/8577

**Comment by macsj200** [comment]
Closed as duplicate of #8577
