### ISSUE TITLE
Replace SockJS with something that works better in non-browser environments

### ISSUE THREAD

**Issue by hwillson** [meteor/meteor#8621]
As part of the Meteor support for non browser environment discussions in #8615, it was suggested (and PR encouraged) that a replacement for SockJS should be found (if possible/advantageous). Since there will likely be a lot of discussion about a potential replacement, I'm creating this new issue to track that work (and to make sure the other items in #8615 aren't drowned out). 

One thing to note - finding a SockJS replacement will impact several other open issues. I'll list them here to make sure anyone thinking about working on those issues is given a heads up about a potential replacement.

Open SockJS (related) issues: #1285, #4114, #4897, #6389, #6719, #8254, #8317

Relevant bits extracted from #8615:

(from https://github.com/meteor/meteor/issues/8615#issuecomment-295925903)

> Replace SockJS with something that works better in non-browser environments. Unfortunately, socketio-1.7.2.js is much larger than sockjs-0.3.4.js (159KB vs 78.3KB), and I don't think we can justify increasing the size of ddp-client by that much. Could we use something smaller, like https://www.npmjs.com/package/ws, instead?

> In particular, we would be happy to review a pull request to replace SockJS with a smaller library, since that fits nicely into #8327.

(from https://github.com/meteor/meteor/issues/8615#issuecomment-295960575)

> As far as I know WS doesn't use polling, only WebSockets, so I wouldn't consider it to be the ideal solution.

**Comment by mitar** [comment]
Does non-browser environments do not have support for web sockets? I have in the past successfully connected directly to the sock.js web socket endpoint with the web socket library from my embedded device and it worked great. You do not have to use sock.js library itself.

What are examples of other transports?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Replace%20SockJS%20with%20something%20that%20works%20better%20in%20non-browser%20environments&body=Migrated%20from:%20meteor/meteor%238621) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
