### ISSUE TITLE
upon saving the file, it doesnt refresh the browser..  how to make it happen ?

### ISSUE THREAD

**Issue by jpca999** [meteor/meteor#8624]

**Comment by hwillson** [comment]
Sorry to hear you're having trouble @jpca999. From the very few details you've provided, it doesn't sound like you're reporting a bug with Meteor. Please try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) for further assistance. If you feel like you're encountering a Meteor bug, please provide more details explaining the issue. See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more information. Closing for now - thanks!
