### ISSUE TITLE
Accounts.onLogin and Accounts.onLoginFailure seem to be undocumented

### ISSUE THREAD

**Issue by Pushplaybang** [meteor/meteor#8626]
# Scope
I can't seem to find documentation about these account hooks in the Meteor docs, where the documentation or the Accounts package seems to reside.  I've used them often, and as they are quite useful it would be great to add them.

# Work To Be Done
I would be will to help out here, or at the least get it started, but not sure where to begin with contributing to the docs.

## Tasks
- [ ] Add onLogin and onLoginFailure hooks to documentation
- [ ] Add example usuage

**Comment by merlinpatt** [comment]
@Pushplaybang both hooks are documented here http://docs.meteor.com/api/accounts-multi.html#AccountsCommon-onLogin

If you think there needs to be more info, please file an issue on the [docs repo](https://github.com/meteor/docs) or make a Pull Request for [this file](https://github.com/meteor/docs/blob/master/source/api/accounts-multi.md)

**Comment by Pushplaybang** [comment]
so weird, thanks for pointing that out, placement does seem a bit odd though.  cheers.
