### ISSUE TITLE
Installer with silent flag during Docker for Windows build process fails

### ISSUE THREAD

**Issue by staramir** [meteor/meteor#8627]
I am trying to install meteorjs as part of a Dockerfile build process using microsoft/windowsservercore base image.

Using powershell I download the installer using:
```
Invoke-WebRequest -Uri https://install.meteor.com/windows -OutFile InstallMeteor.exe -UseBasicParsing
./InstallMeteor.exe /silent
```

The installer returns without any error code but it doesn't install meteor. I have tried the process using PowerShell in Windows Server 2016 (outside Docker) and it successfully installs meteor however the same process inside a Docker for Windows container will not work.

Are there any flags for the installer that I can use to install using no UI but get verbose output to further troubleshoot the installation process?

**Comment by hwillson** [comment]
Meteor on Windows now uses a new installation process (see https://github.com/meteor/meteor-chocolatey-installer). Sorry nobody got back to you about this, but the Windows installer is no longer supported. Give the new Chocolatey based installer a shot, and post back if you notice any issues. Thanks!
