### ISSUE TITLE
Memory Leak in Node 4.8.1

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#8630]
Node 4.8.1 has a memory leak (https://github.com/nodejs/node/pull/12089) that was fixed in 4.8.2. 

If anyone is experiencing memory leaks in production after updating Node recently this is likely to be the cause. The solution is to update the version of Node on your servers to 4.8.2.

This isn't really a critical issue for the Meteor tool itself as the leak is unlikely to cause issues in development but it may be worth bumping the version anyway (and changing the recommendation to use 4.8.2 in production).

**Comment by hwillson** [comment]
PR #8634 has been merged, so Node 4.8.2 will be coming soon. Thanks for flagging this @mjmasn!

**Comment by abernix** [comment]
This should be available to test in the release candidate for Meteor 1.4.4.2, currently `1.4.4.2-rc.1`:

    meteor update --release 1.4.4.2-rc.1

Please report any problems you encounter!

**Comment by tab00** [comment]
My app in production has been restarting multiple times per day with "out of memory" error, so I hope this gets through soon.

Thank you guys for your work on solving this.

**Comment by dagatsoin** [comment]
@abernix could this solve memory leaks issue on Galaxy?

I have an app which restart each few minutes because memory increases over the time. And it it not the case on my local machine.

**Comment by abernix** [comment]
@dagatsoin Galaxy uses the exact version of Node.js which your local development uses, so yes.  And additionally, there was a memory leak in Node.js itself, so if it was triggered the answer is: absolutely.  😉

I'd recommend upgrading to Meteor 1.4.4.2 and seeing if it goes away for you!  If it does, please do report back.  If it doesn't, then you've likely encountered or created some other kind of memory leak within your app which is unrelated.

**Comment by dagatsoin** [comment]
You made my day!!

Le 4 mai 2017 à 20:53, Jesse Rosenberger <notifications@github.com<mailto:notifications@github.com>> a écrit :


@dagatsoin<https://github.com/dagatsoin> Galaxy uses the exact version of Node.js which your local development uses, so yes. And additionally, there was a memory leak in Node.js itself, so if it was triggered the answer is: absolutely. 😉

I'd recommend upgrading to Meteor 1.4.4.2 and seeing if it goes away for you! If it does, please do report back. If it doesn't, then you've likely encountered or created some other kind of memory leak within your app which is unrelated.
