### ISSUE TITLE
Email - STARTTLS

### ISSUE THREAD

**Issue by samicemalone** [meteor/meteor#8637]
Hi,

The email 1.1.18 package (and earlier) doesn't seem to use the STARTTLS command on a connection string such as MAIL_URL="smtp://server:25"

The email package has since been updated - I've tried 1.2.0 and 1.2.1. Both of these packages are now issuing the STARTTLS command.

We are using a self-signed certificate on our mail server which causes the `Error: unable to verify the first certificate` message.

I appreciate I can trust the certificate locally, or use a globally trusted cert, but it would be nice to able to specify the TLS options for the SMTP transport to be able to ignore verification for example.

Thanks,

Sam

**Comment by amolab** [comment]
Facing the same issue. I see in the email 1.1.18 package  secure flag was being set based on the port in the MAIL_URL. Does it defaults to true now?

**Comment by janikvonrotz** [comment]
Faced the same issue after upgrading to meteor 1.5 and email 1.2.3.

Adding a user and a password to the MAIL_URL variable solved it for me.

Before: `export MAIL_URL='smtp://localhost:1025'`
After: `export MAIL_URL='smtp://user:pw123@localhost:1025'`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Email%20-%20STARTTLS&body=Migrated%20from:%20meteor/meteor%238637) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
