### ISSUE TITLE
Creating and starting project on windows takes too long

### ISSUE THREAD

**Issue by r21meghashyam** [meteor/meteor#8638]
Creating a project takes atleast 15 mins since there is percentage shown while downloading, download process can be understood but extraction does not have any indication other than the package specification. If i leave my pc alone the following line would be forever:
`Extracting meteor-tool@1.4.4_1...         /`
![Cmder](https://cloud.githubusercontent.com/assets/16733388/25436788/028c9dfe-2ab2-11e7-93b2-2dd4870130e8.png)
Not an expert but my guess is that meteor runs on 32 bits nodejs & 7zip which comes with the package. So please make it 64 bit compatible soon.

Please fix this as soon as possible, or if its just for me then please let me know the solution.

System details:
OS: Windows 10
Node: 7.9.0
Meteor: 1.4.4

**Comment by hwillson** [comment]
Hi @r21meghashyam - sorry to hear you're having trouble. In the future, please try searching for similar issues here first, before opening a new issue. This problem has been brought up (and resolved) quite a few times in other issues, like #7688. Please try the suggestions/workarounds listed there first, then add your comments to that issue as/if needed. Thanks!
