### ISSUE TITLE
Meteor with node v6+

### ISSUE THREAD

**Issue by piperun** [meteor/meteor#8647]
I've got a problem currently, in that I'm using a very outdated and unsupported version of a nodejs library and the new one was rewritten to only support nodejs v6+ and from what I've seen meteor is only at v4 currently but I did see that someone had tried building meteor with nodejs v6 and I'm wondering where that project went.

**Comment by hwillson** [comment]
Hi @piperun - see #6923 for the Node 6 upgrade PR. Thanks!

**Comment by piperun** [comment]
@hwillson you're a saint!
