### ISSUE TITLE
react-meteor-data and createContainer error

### ISSUE THREAD

**Issue by zhaoyao91** [meteor/meteor#8650]
Since I add `react-meteor-data` package and use `createContainer` function of it, the browser complains

```
Warning: MeteorDataContainer: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

## versions
- METEOR@1.5-beta.17
- react-meteor-data@0.2.9

**Comment by hwillson** [comment]
Hi @zhaoyao91 - see meteor/react-packages#219 (and the associated PR meteor/react-packages#218). The PR has been merged, so this will be fixed when the next version is published (should be done shortly). Thanks!

**Comment by abernix** [comment]
As the beta seems as it was well-received, I've gone ahead and published `react-meteor-data@0.2.11`.  Please report back if you experience any problems!

**Comment by jasongrishkoff** [comment]
Doesn't this break things for anyone still using mixins?  Just updated to 0.2.11 and it caused all sorts of issues, so I've rolled back to 0.2.9.  Just to confirm, if I want to upgrade to 0.2.11 I'll need to replace all my mixins with the new createContainer approach?

**Comment by hwillson** [comment]
It looks like issue #223 was just opened outlining the same problem. For now stay version pinned at 0.2.9. We'll look into this further. Thanks!

**Comment by DORRITO** [comment]
Phew!  just ran into this issue when reverting some of my react-router code from v4 back to v3 (finally gave up. goodbye days of work!)
'Good' to know it's still a recent issue and being looked into.  Thanks for all the hard work!

**Comment by hwillson** [comment]
@jasongrishkoff @DORRITO - PR https://github.com/meteor/react-packages/pull/224 should help fix this (hopefully we can get it merged/published soon).
