### ISSUE TITLE
Order of merged-stylesheets.css in <head>

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#8651]
A pretty common use case if you're using a third-party UI framework such as Bootstrap is loading it from a CDN, for example using [Helmet](https://github.com/nfl/react-helmet) to inject link tags. . 

The problem is that currently, Meteor's own stylesheet (`merged-stylesheets.css`) gets injected right at the top of the `<head>`, meaning that Bootstrap's CSS will come afterwards and override your own user-defined styles. 

So I would suggest modifying the `boilerplate-generator` package so that Meteor's own stylesheet always comes last. Are there any downsides to doing this?

**Comment by SachaG** [comment]
Relevant forum threads:

- https://forums.meteor.com/t/how-to-load-an-external-css-file-before-the-compressed-css/22504/5
- https://forums.meteor.com/t/load-cdn-many-scripts-before-merged-stylesheets-css-on-the-head-tag/29453/11
- https://forums.meteor.com/t/how-to-make-meteor-append-its-js-files-after-js-libs-from-a-cdn/7114/13

**Comment by hwillson** [comment]
I've definitely run into this problem before as well. With regards to 

> Are there any downsides to doing this?

The only issue I can think of is that just making the merged stylesheets the last referenced file in `<head />` might introduce backwards compatibility issues. There could be cases where devs are relying on the merged stylesheets coming first, then expecting externally referenced stylesheets to override the Meteor merged stylesheets. I think the likelihood of this being the case is low, but it's worth considering.

If we want to introduce this change in a backwards compatible way, we could keep the load order as it is now by default, but add a new flag on `WebAppInternals` called something like `linkBundledCssLast`. When this flag is set to `true`, the Meteor merged stylesheets would get referenced last in `<head />`. So something like:

**server/main.js**

```js
import { Meteor } from 'meteor/meteor';
Meteor.startup(() => {
  WebAppInternals.linkBundledCssLast = true;
});
```

would add `merged-stylesheets.css` last.

I've tested this approach out, and it seems to work well. I can submit these changes in a PR if people think worrying about backcompat is something we should consider.

**Comment by merlinpatt** [comment]
Having backwards compatibility is a good move. And the change going forward should be the opposite. Make the bundle CSS last by default and ask people who rely on it being first to include the necessary line of code.

The reason to do it this way is that it's far more common that people place custom CSS last and therefore would expect it to be last.

**Comment by hwillson** [comment]
Thanks @merlinpatt - anyone currently using Meteor is used to how it's working now though, so it might make sense to keep the default as is (merged stylesheets come first), even though it isn't the best solution. That way we don't run into issues when dev's `meteor update` and find out that for some reason moving the merged stylesheets to the bottom of `<head />` broke their prod app. I agree though - having the merged stylesheets at the bottom should be the default eventually, I just think we'll need to be a bit careful about how we introduce this new default.

Then again, this might be overly cautious for potential edge cases that might not happen. So, I can be easily persuaded either way.

**Comment by mitar** [comment]
Probably even better would be if you could have two stylesheets files, one at the beginning, then head, and one at the end. :-)

**Comment by SachaG** [comment]
Btw, I've been using a [modified version](https://github.com/VulcanJS/Vulcan/blob/devel/packages/_boilerplate-generator/boilerplate_web.browser.html#L2-L6) of `boilerplate-generator` with the CSS at the end and haven't run into any issues so far. I know @comus also looked into using his own custom version, maybe he'll have some suggestions of what could be improved?

**Comment by comus** [comment]
oh, my custom boilerplate-generator use case may be not really related to this css topic.

i just want to reduce meteor packages dependencies. such as i dont use blaze, and i found that my meteor project only boilerplate-generator require blaze for import boilerplate_web.browser.html file. and i want my server get rid of those packages because my project only use react. so i save xxx.html content to a variable instead of import html file
[see](https://github.com/comus/meteor-demo/blob/c44bfc604ec8151266e3211ca3272fc943f085b4/packages/_boilerplate-generator/boilerplate_web.browser.js#L1-L25)

for example an empty meteor project created by `meteor create demo`
after added my custom boilerplate-generator. and remove `blaze-html-templates`

my server can get rid of those packages below

```
blaze                  removed from your project
blaze-html-templates   removed from your project
blaze-tools            removed from your project
caching-compiler       removed from your project
caching-html-compiler  removed from your project
deps                   removed from your project
html-tools             removed from your project
htmljs                 removed from your project
jquery                 removed from your project
observe-sequence       removed from your project
spacebars              removed from your project
spacebars-compiler     removed from your project
templating             removed from your project
templating-compiler    removed from your project
templating-runtime     removed from your project
templating-tools       removed from your project
ui                     removed from your project
```

my suggestion is keep the original css order for backwards compatibility is fine, but may give people chance to completely replace the  boilerplate-generator html content as they want is a good direction too. i mean the default html content can be save in a variable like my modified boilerplate-generator package, just es6 template literals, no blaze
 
```
module.exports = function template (data) {
  return `
<html ${Object.keys(data.htmlAttributes || {}).map(key => `${key}="${data.htmlAttributes[key]}"`).join(' ')}>
<head>
  ${(data.css || []).map(({ url }) => `<link rel="stylesheet" type="text/css" class="__meteor-css__" href="${data.bundledJsCssUrlRewriteHook(url)}">`).join('\n')}
  ${data.head || ''}
  ${data.dynamicHead || ''}
</head>
<body>
  ${data.body || ''}
  ${data.dynamicBody || ''}
  ${data.inlineScriptsAllowed
    ? `<script type='text/javascript'>__meteor_runtime_config__ = JSON.parse(decodeURIComponent(${data.meteorRuntimeConfig}));</script>`
    : `<script type='text/javascript' src='${data.rootUrlPathPrefix}/meteor_runtime_config.js'></script>`
  }
  ${(data.js || []).map(js => `<script type="text/javascript" src="${data.bundledJsCssUrlRewriteHook(js.url)}"></script>`).join('\n')}
  ${(data.additionalStaticJs || []).map(({ contents, pathname }) => (
    data.inlineScriptsAllowed
      ? `<script type='text/javascript'>${contents}</script>`
      : `<script type='text/javascript' src='${data.rootUrlPathPrefix}${pathname}'></script>`
  )).join('\n')}
</body>
</html>
`
```

and then if someone want to change it, just follow some hook to change its part of content or change it completely

**Comment by hwillson** [comment]
Another option - keep everything as it is now (bundled css is loaded first by default), but allow people to override the location of the bundled CSS in a head block, to put it anywhere they want. So something like:

```html
<head>
  <title>meteor-issue-8651</title>
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="METEOR_BUNDLED_CSS_URL" />
</head>
```

If `METEOR_BUNDLED_CSS_URL` shows up in `<head />`, the boilerplate generator will hold off on injecting the css at the top of `<head />`, and instead replace `METEOR_BUNDLED_CSS_URL` with the bundled css URL. This approach let's you put the bundled CSS anywhere; for example you could have it in the middle of external CSS references if needed.

**Comment by mitar** [comment]
@comus, that Blaze is used only on the server side. It should be on the client. So you do not have to worry about it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Order%20of%20merged-stylesheets.css%20in%20%3Chead%3E&body=Migrated%20from:%20meteor/meteor%238651) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
