### ISSUE TITLE
Meteor build packages not included

### ISSUE THREAD

**Issue by tkober** [meteor/meteor#8653]
I am currently trying to generate native versions of a small meteor app I built. When I run them on iOS or Android via the meteor run command it works and `meteor build` with `--debug` also generates an ipa/apk that works as expected. But when I run `meteor build` without `--debug` the web view only shows a white screen. Using remote debugging I noticed an injector error (I use angular 1). I was wondering why and checked the apk/ipa content. There I recognized that in the debug version under `assets/www/application/packages` there is a bunch of .js and .js.map files which simply is not there in the non-debug ipa/apk.

In the `index.html` of the non-debug ipa/apk the imports of these files are also missing.

How can I tell meteor to just copy these obviously required files for non-debug?

**Comment by abernix** [comment]
Could you please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub?  Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction repository, it's very difficult to investigate.  The mobile build is certainly known to work, without the `--debug` flag.

**Comment by bmanturner** [comment]
Just started running into this issue as well. ```android-device``` runs fine, ```build --debug``` runs fine, but ```build``` without the ```--debug``` does not. The server sees the client, but the client doesn't seem to do anything.

**Comment by bmanturner** [comment]
@tkober How did you see the injection error on the non-debug apk?

**Comment by angryrancor** [comment]
Does anyone have a workaround for this?  My team is seeing the same behavior running `meteor build`.  We are running with --server-only, and not using any mobile clients at all...  `bundle/programs/web.browser/packages' only has `meteorhacks_zones` and `nemo64_bootstrap-data` in it.  No other packages.  Building and running with `meteor run` is working fine.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8653#issuecomment-299390297, if anyone can supply a reproduction demonstrating this problem, that would greatly help with troubleshooting (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Since we haven't heard back about this in a while however, I'll close this for now. Thanks!
