### ISSUE TITLE
Can't Get Android emulator running since I have 1.4.4.1 hack installed

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#8655]
Having issues run `meteor run android`:

```
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/adamginsburg/Documents/development/buzzy7/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   { [Error: adb: Command failed with exit code ENOENT] code: 'ENOENT' }
   'Error: adb: Command failed with exit code ENOENT\n    at
   ChildProcess.whenDone
   (/Users/adamginsburg/Documents/development/buzzy7/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)\n
   at emitOne (events.js:77:13)\n    at ChildProcess.emit
   (events.js:169:7)\n    at Process.ChildProcess._handle.onexit
   (internal/child_process.js:209:12)\n    at onErrorNT
   (internal/child_process.js:363:16)\n    at nextTickCallbackWith2Args
   (node.js:511:9)\n    at process._tickCallback (node.js:425:17)'
   at ChildProcess.exitCallback
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/processes.js:137:21)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   
   => awaited here:
   at Function.Promise.await
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova/project.js:978:22)
   at CordovaProject.run$
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova/project.js:428:18)
   at tryCatch
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch

```
Environment:
Meteor 1.4.4.1
Android Studio 2.3.1
OSX 10.12.4

I have the hack as per https://github.com/meteor/meteor/issues/8464#issuecomment-296823234

Since installing the hack I can't seem to get emulators installed via Android Studio
When I try and add a virtual device...
<img width="992" alt="screen shot 2017-04-30 at 7 50 13 pm" src="https://cloud.githubusercontent.com/assets/7233741/25563366/86816624-2dde-11e7-96ef-75fc7fe9f782.png">
<img width="772" alt="screen shot 2017-04-30 at 8 01 22 pm" src="https://cloud.githubusercontent.com/assets/7233741/25563448/e3a99064-2ddf-11e7-97bc-9a5d5eb328a1.png">
<img width="752" alt="screen shot 2017-04-30 at 8 01 04 pm" src="https://cloud.githubusercontent.com/assets/7233741/25563449/e3abf872-2ddf-11e7-83ac-1a721bb7eb08.png">

I get
<img width="413" alt="screen shot 2017-04-30 at 7 50 23 pm" src="https://cloud.githubusercontent.com/assets/7233741/25563372/a2b6f46c-2dde-11e7-8fcb-db8da9c03128.png">
If I ignore error click Next/Finish
<img width="1001" alt="screen shot 2017-04-30 at 7 50 58 pm" src="https://cloud.githubusercontent.com/assets/7233741/25563374/a8f2b4ba-2dde-11e7-8aee-f529496b2a13.png">
I can't seem to find the `idea.log` file.
Anyone else getting this issue?

**Comment by adamgins** [comment]
Doh, 1st problem... when I'd replaced the SDK the emulator was somehow uninstalled.
That said, I not have a separate issue... ie emulator is SDK 26, but it's expecting 25.... mmm perhaps I need to re-install with an older version of Android Studio???

**Comment by adamgins** [comment]
Somehow I have now got the emulator popping up - sorry no idea what changed. (I did reboot).
Now the emulator opens, but it never opens the app.

I have left it running for about 20 mins and all it says is "starting emulator" never seems to end. Any ideas pls?

![screen shot 2017-05-01 at 4 45 40 pm](https://cloud.githubusercontent.com/assets/7233741/25574171/31debea8-2e8f-11e7-9d47-a39668a9b12c.png)
![screen shot 2017-05-01 at 4 50 25 pm](https://cloud.githubusercontent.com/assets/7233741/25574170/31cda5d2-2e8f-11e7-9746-568566c1db4f.png)

**Comment by adamgins** [comment]
Closing this as working... that said, I have no real idea of how I got it working.

**Comment by adamgins** [comment]
Mmm.. thought was done. After I got android working, I got this message when I tried to ios build:

```
Adams-MacBook-Pro-3:buzzy7 adamginsburg$ meteor run ios-device --settings settings.json --mobile-server https://buzzy.buzz
[[[[[ ~/Documents/development/buzzy7 ]]]]]    

=> Started proxy.                             
/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/adamginsburg/.meteor/packages/okgrow_analytics/.2.1.3.1xhw51h++os+web.browser+web.cordova/npm/node_modules/path-is-absolute/.meteor-portable-1.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.fs.readFileSync (fs.js:397:15)
  at wrapper (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1582:34)
  at wrap.makeCacheKey._len2 (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:103:15)
  at optimistic (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:38:17)
  at /Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:283:23
  at wrap.makeCacheKey._len2 (/Users/adamginsburg/.meteor/packages/meteor-tool/.1.4.4_1.1px9bg4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:103:15)
```

**Comment by adamgins** [comment]
Ugh, re opening this I can't get it working again :-( 
I had to `remove-platform/add-platform` to get my borked iOS up running again.
When I toggled back to get running on Android it's now not running and seems like it can't install/start the app on the emulator. I get the spinning `Start app on android emulator`

When I check the emulator it does not seem to be setup with `developer options`. If I manually try and set this up and run the `meteor run android` again it seems to try and open a second emulator and then gets an error ` Can't attach to the Android Emulator` on my mac.

Any ideas, pls?

**Comment by abernix** [comment]
Are you able to start an emulator without Meteor in the picture at all?  For example, by running:

    android avd

Then picking an AVD (Android Virtual Device), pressing the "Start..." button and then clicking "Launch"?  In case it's any help, I'll share my preferences for my fake-Nexus 7 which generally works for me:

![image](https://cloud.githubusercontent.com/assets/841294/25650648/13191352-2fe7-11e7-9c4d-4f70d9c8174d.png)

I'll also point out that there are a variety of conflicts within the HAXM virtualization ecosystem.  For example, up until [this update](https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager) from Intel (which I strongly recommend installing), it wasn't possible to run any multiple of VirtualBox, Docker or the Android emulator within the same host as they would conflict on their interactions with the virtualization engine (which all used HAXM).  See [related](https://www.virtualbox.org/ticket/14294).

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.

**Comment by Rebeccarmstrong** [comment]
This is really amazing! I've never met any one who is doing it better,big shoutout to mitchbourne (@) cyberservices.com, he's absolutely the best when it comes to GRADES CHANGE, FACEBOOK, EMAIL and WHATSAPP in fact he does all sort of hack, interesting part is he works with Proofs. He increased myself and 4 other of my buddies' credit worthiness within 14hours. I can strongly assure you that he's one of the best ethical hackers, It was a blessing meeting him, let him know Miss Rebecca referred you.
