### ISSUE TITLE
[Up for grabs] Switch Meteor's headless browser tests from PhantomJS to Headless Chrome

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#8659]
PhantomJS has been showing its age for several years now, and the new `--headless` support in Chrome 59 seems like a much better fit for running our client-side integration tests: https://developers.google.com/web/updates/2017/04/headless-chrome

Here's an example of a similar issue/discussion on another project (GitLab): https://gitlab.com/gitlab-org/gitlab-ce/issues/30876

Relevant starting points:
* the [script](https://github.com/meteor/meteor/tree/devel/packages/test-in-console/run.sh) that runs our Travis CI tests
* the [script](https://github.com/meteor/meteor/blob/devel/scripts/ci.sh) that runs our Circle CI tests
* [code search](https://github.com/meteor/meteor/search?utf8=%E2%9C%93&q=phantomjs&type=) for "phantomjs"
* [`PhantomClient`](https://github.com/meteor/meteor/blob/fcdf3515730302217ae770c250bdd0eca1715424/tools/tool-testing/selftest.js#L591) used by self-tests
* some [background](https://github.com/meteor/meteor/blob/50d10aeb366d3489172897abd17d92b62f73e440/Development.md#running-meteor-tool-self-tests) about headless browser self-tests

I realize these instructions are woefully incomplete, but I hope this is enough to get discussion started, and (with any luck) identify contributors who would find this work interesting.

**Comment by hwillson** [comment]
I sooooo very badly want to put my hand up for this one - phantom has taken years off my life. The discussion on GitLab leads me to believe we might be early days on this yet, but based on Google's docs it should all be possible. Okay, my hand is half up for this - I'll review the state of things a little more extensively, and post back shortly. Thanks for getting the ball rolling on this!

**Comment by macrozone** [comment]
we already switched to headless firefox in our chimp-tests (running on gitlab ci). 

sidenote: would it be possible to use a headless chrome (or firefox) in spiderable?

**Comment by mitar** [comment]
You just need Selenium and you can already use Chrome, even before headless mode.

I have made a pull request using Circle CI + Sauce Labs to this library: https://github.com/sloisel/numeric/pull/76/files Maybe it can help a bit for Meter as well.

At the end it is pretty straightforward. But it takes some playing.

**Comment by hwillson** [comment]
Quick update - headless Chrome isn't supported on Windows, so I don't think we can move ahead with replacing phantom yet. [Windows support is coming though](https://bugs.chromium.org/p/chromium/issues/detail?id=686608); it looks like it's almost in Chrome Canary.

**Comment by mitar** [comment]
One issue with headless Chrome is that then you are testing only against the Chrome and only against latest versions. Sauce Labs allows you to test also across versions. So you can check if your code works on all browsers you are claiming to support. (Useful for verifying that transpiling really work.) Currently it is unclear on which browser versions Meteor really work. In the past there was a clean list of browsers and versions. I think that is not provided anymore?

Maybe the solution would be to run headless automatically on every pull request and change (to be fast) and then run against old versions daily or something like that.

BTW, Sauce Labs is free for open source projects.

**Comment by hwillson** [comment]
Chrome headless is now supported on Windows, via Chrome 60. We should now be all clear to get started on this.

**Comment by hwillson** [comment]
Migrated to https://github.com/meteor/meteor-feature-requests/issues/254.
