### ISSUE TITLE
Email.send `headers` option broken since Meteor 1.4.4.1

### ISSUE THREAD

**Issue by rijk** [meteor/meteor#8660]
I tracked down this issue to the update from Meteor 1.4.3.2 to Meteor 1.4.4.1. 

`Email.send` output in 1.4.3.2 (email package version 1.1.18):

```
I20170502-14:43:26.329(2)? ====== BEGIN MAIL #0 ======
I20170502-14:43:26.485(2)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20170502-14:43:26.487(2)? MIME-Version: 1.0
I20170502-14:43:26.488(2)? X-SMTPAPI:
I20170502-14:43:26.489(2)?         {"filters":{"templates":{"settings":{"enable":1,"template_id":"ef0e6150-e472-4821-87b1-5a96fffbbe15"}}},"sub":{"%userName%":["test"],"%enrollUrl%":["test"]}}
I20170502-14:43:26.489(2)? Date: Tue, 02 May 2017 12:43:26 +0000
I20170502-14:43:26.490(2)? From: "xxx" <xxx@xxx.com>
I20170502-14:43:26.490(2)? To: xxx@xxx.com
I20170502-14:43:26.491(2)? Subject: Your account has been created
I20170502-14:43:26.491(2)? Content-Type: multipart/alternative;
I20170502-14:43:26.491(2)?         boundary="----mailcomposer-?=_1-1493729006195"
```

`Email.send` output for the exact same code in 1.4.4.1 (email package version 1.2.0):

```
I20170502-14:47:51.168(2)? ====== BEGIN MAIL #0 ======
I20170502-14:47:51.287(2)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20170502-14:47:51.288(2)? Content-Type: multipart/alternative;
I20170502-14:47:51.288(2)?  boundary="--_NmP-10d33eac09c9616b-Part_1"
I20170502-14:47:51.289(2)? From: Transmate <xxx@xxx.com>
I20170502-14:47:51.289(2)? To: xxx@xxx.com
I20170502-14:47:51.289(2)? Subject: Your account has been created
I20170502-14:47:51.290(2)? Message-ID: <5f940533-7231-0d8a-badd-9688ba2ebd98@transmate.eu>
I20170502-14:47:51.290(2)? Date: Tue, 02 May 2017 12:47:51 +0000
I20170502-14:47:51.291(2)? MIME-Version: 1.0
```

Note the omission of the `X-SMTPAPI` header.

Code to trigger the email:

```coffeescript
Email.send
  to: email
  from: "Transmate <xxx@xxx.com>"
  subject: 'Your account has been created'
  text: 'from template'
  html: '<b>from template</b>'
  headers:
    'X-SMTPAPI':
      filters:
        templates:
          settings:
            enable: 1
            template_id: "ef0e6150-e472-4821-87b1-5a96fffbbe15"
      sub:
        '%userName%': [ 'test' ]
        '%enrollUrl%': [ 'test' ]
```

I've looked through the [tests](https://github.com/meteor/meteor/blob/devel/packages/email/email_tests.js) and it doesn't seem like we have to do anything differently with the new version (nor does [the documentation](https://docs.meteor.com/api/email.html) say anything about it).

**Comment by rijk** [comment]
Ok, additional info: it's the object format that breaks it. If the header is a string, like here:

`'X-Meteor-Test': 'a custom header'`

..it does work. But, this was not the previous behaviour.

**Comment by rijk** [comment]
Fixed by wrapping the object in a call to `JSON.stringify`. Leaving this issue open, in case you think the framework should handle this for backwards compatibility.

**Comment by hwillson** [comment]
Hi @rijk - thanks for raising this issue and your follow up. It looks like the older versions of `mailcomposer` were automatically [`stringify`'ing passed in header objects](https://github.com/nodemailer/mailcomposer/blob/6ef1514b9baac189c26ea63b2c3beca342d983d9/lib/mailcomposer.js#L112-L134), whereas the newer versions [are not](https://github.com/nodemailer/nodemailer/blob/5be7c902e953043be3618d747c349f02405f003b/lib/mime-node/index.js#L342-L345). We could consider adding a fix for this on the Meteor side, to make sure we `stringify` any passed in header objects (to remain backwards compatible), or we could instead document this new behaviour and follow `nodemailer`'s lead on this, leaving things as they are now. I guess the best course of action depends on how many people are affected by this, but for now there hasn't been many complaints. My vote is to keep things as they are, but get this difference documented as soon as possible. If we start to hear of more complaints about this breaking backwards compatibility, then we can definitely revisit. Let me know what you think - thanks!

**Comment by abernix** [comment]
Looping @edemaine in for his feedback/thoughts on the matter.

**Comment by rijk** [comment]
Hey Hugh, I guess it's your guys' call. Documenting it is for sure a win/win I think, but maybe this behaviour was kind of undocumented to begin with (judging from the fact I am the first to notice). The workaround works fine, and doesn't look too weird either. So I'm fine leaving it like this personally. Thanks for asking!

**Comment by edemaine** [comment]
Hmm.  I too could go either way.  I do find it worrying that the header just gets silently removed instead of returning an error.  So even if we don't restore the old behavior (it is a little counterintuitive to me...), perhaps we should at least throw an error/warning when an object gets passed in.

Can you test on `email@1.2.1`?  `email@1.2.0` has issues with long-lived connections, so you should update anyway.

**Comment by hwillson** [comment]
PR https://github.com/meteor/meteor/pull/9443 updates the `Email.send` `options.headers` docs to show how to properly add custom header objects using `JSON.stringify`. This was the easiest option, and should hopefully be enough to point people in the right direction.

**Comment by puddicombe** [comment]
Thank you for your previous consideration of this issue, and I'm totally happy with the idea of using stringify, but has the change to the docs been actioned yet? Because I fell foul of this today, referencing the current online docs....
https://docs.meteor.com/api/email.html#Email-send

**Comment by hwillson** [comment]
No, the doc changes haven't been published yet @puddicombe. They'll be coming with the Meteor 1.6.1 release (which will be happening soon - we're now at 1.6.1-rc.1). Sorry about that!
