### ISSUE TITLE
Mongo.collection.upsert crashes if selector is undefined

### ISSUE THREAD

**Issue by ijager** [meteor/meteor#8666]
When doing an upsert

````
SomeCollection.upsert(someObject._id, someObject)
````

If `someObject` was not yet in the database `_id` is undefined. Upsert should recognize that and do an insert instead. However since the latest [commit](https://github.com/meteor/meteor/commit/f4e41cbf1bcb871d1a8e9a63d496bcb57233a8db), Meteor crashes: 

````
W20170504-11:43:40.308(2)? (STDERR) TypeError: Cannot read property '_id' of undefined
W20170504-11:43:40.308(2)? (STDERR)     at [object Object].update (packages/mongo/collection.js:561:18)
W20170504-11:43:40.308(2)? (STDERR)     at [object Object].upsert (packages/mongo/collection.js:675:15)
W20170504-11:43:40.309(2)? (STDERR)     at packages/matb33_collection-hooks.js:710:21
W20170504-11:43:40.309(2)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20170504-11:43:40.310(2)? (STDERR)     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
W20170504-11:43:40.310(2)? (STDERR)     at [object Object].<anonymous> (packages/matb33_collection-hooks.js:709:31)
W20170504-11:43:40.311(2)? (STDERR)     at [object Object].collection.(anonymous function) [as upsert] (packages/matb33_collection-hooks.js:146:21)
````

I think it is because [this line (Collection.js:567):](https://github.com/meteor/meteor/blob/f4e41cbf1bcb871d1a8e9a63d496bcb57233a8db/packages/mongo/collection.js#L567)
````
selector =
     Mongo.Collection._rewriteSelector(selector, { fallbackId: insertedId });
````

Was moved after [this block (Collection.js:561):](https://github.com/meteor/meteor/blob/f4e41cbf1bcb871d1a8e9a63d496bcb57233a8db/packages/mongo/collection.js#L561)
````
  } else if (! selector._id) {
     insertedId = this._makeNewID();
     options.insertedId = insertedId;
  }		      
````

Since it assumes selector is not undefined.

Meteor 1.4.4.x

**Comment by hwillson** [comment]
Thanks for reporting this @ijager - I'll take a look. Sounds like the test suite is missing this combination so it wasn't caught. More details coming shortly.
