### ISSUE TITLE
Can't import BrowserPolicy

### ISSUE THREAD

**Issue by AnthonyAstige** [meteor/meteor#8667]
Running `METEOR@1.4.4.2` on `Ubuntu 16.04.2 LTS` with a fresh installation.

Isolated @ https://github.com/AnthonyAstige/meteor-test-browers-policy/commit/1d73b5ee1629d39aeb734c3bb1525d87dd633729

# Screenshots
 * [Log message on client](https://www.screencast.com/t/RQxrXH2l)
 * [Is empty packages/browser-policy.js expected?](https://www.screencast.com/t/LKnXM57Ti5)

# Related

 * https://github.com/meteor/docs/issues/16
 * https://github.com/meteor/meteor/issues/6766

# Other things I've tried

* Clearing build cache (destroying from in the project `.meteor/local/build` & `.meteor/local/bundler-cache/*`)
* Reinstalling meteor (destroying from my home folder `~/.meteor`)

# Background

I need this to adjust the policy for loading the Stripe api on a galaxy hosted application.

**Comment by benjamn** [comment]
Thanks for reporting this issue, and especially for providing a reproduction. It looks like you're trying to `import { BrowserPolicy } from "meteor/browser-policy"` on the [client](https://github.com/AnthonyAstige/meteor-test-browers-policy/blob/1d73b5ee1629d39aeb734c3bb1525d87dd633729/client/main.js#L5), but it's only available on the [server](https://github.com/meteor/meteor/blob/a89963fdbe5a55d0741cecae6bbb2fe52ca02063/packages/browser-policy/package.js#L10). If you put your code in [`server/main.js`](https://github.com/AnthonyAstige/meteor-test-browers-policy/blob/master/server/main.js) instead, everything should work.

**Comment by AnthonyAstige** [comment]
@benjamn - Ah thank you! Relatively simple oversight, of course it needs to run on the server, it's an HTTP header that needs to be sent. I've got it working locally and presume I'll be able to make it work on Galaxy deployment.  I'll close this issue once I confirm fully and deploy (today or tomorrow).

**Comment by AnthonyAstige** [comment]
Well that was quick, deployment worked and script is now loading from Stripe :)
