### ISSUE TITLE
meteor.com - tutorials for react not refreashing body content

### ISSUE THREAD

**Issue by theboman** [meteor/meteor#8671]
The tutorial section of the website seems to be displaying the wrong content. 

https://www.meteor.com/tutorials/react/creating-an-app (same)
https://www.meteor.com/tutorials/react/components  (same)
https://www.meteor.com/tutorials/react/collections  (same)
https://www.meteor.com/tutorials/react/forms-and-events - wrong content showing creating your first app

**Comment by abernix** [comment]
@theboman You're correct that they are misbehaving, though I've moved this to meteor/tutorials#126, the repository tutorial-related items.  Thanks!  Let's continue over there!
