### ISSUE TITLE
E-mail format is not verified when registering

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8676]
It seems e-mail format is not verified when user is created. This allows one to register an user with `foo@example.com,bar@example.com` as their e-mail. Even if one uses `Accounts.sendVerificationEmail` this works because verification e-mail is sent to both `foo@example.com` and `bar@example.com`, because nodemailer allows one to specify "Comma separated list or an array of recipients email addresses" in `To` field (and other related fields).

Why this could be problematic [one can read in Sandstorm blog post](https://sandstorm.io/news/2017-03-02-security-review#insufficient-e-mail-address-validation).

I would suggest that Meteor checks that wherever e-mail address can be provided it really matches a valid e-mail address format. E-mail address should conform to their format even is user is not doing their verification by sending an e-mail to it.

Moreover, I would suggest that `email` package also verifies e-mail address in its `To` and other fields, and allows one to specify multiple e-mail address only as an array and not with commas. This is how it is currently documented anyway. If you want a "smart" behavior, you can always pass raw options through `mailComposer` option.

**Comment by derwok** [comment]
I think this is not the job of the verification mailer. The verification mailer should mail to the account the user specified when registering. Or to rephrase: when verification mailer finds a problem with the mail address it's already too late (the wrong mail address is already stored in user profile). One must prohibit the user to enter malformed mail addresses to the registration dialog in the first place.

We deal with this issue in the following way (don't argue about the RegExp  :-) ):

``` 
AccountsTemplates.removeField('email');

AccountsTemplates.addFields([
    {
        _id: 'email',
        type: 'email',
        required: true,
        displayName: 'Email',
        re: /^[^\s@]+@([^\s@]+){2,}\.([^\s@]+){2,}$/,
        errStr: 'Invalid email'
    },
   // ....
```

**Comment by mitar** [comment]
Yes, so Meteor should prevent registration with invalid e-mail address so that it is not even stored in user profile. It should do it automatically so that users do not have to think about that. It should be secure by default.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=E-mail%20format%20is%20not%20verified%20when%20registering&body=Migrated%20from:%20meteor/meteor%238676) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
