### ISSUE TITLE
[Windows] Long path not supported

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#8680]
This is for the record only, as this issue is not painful. I found it while testing edge cases for solving issue https://github.com/meteor/meteor/issues/8485. 

Platform: Windows 7
Meteor version: 1.4.4.2

Under Windows, here is what you get when running `meteor` in a folder with a path of 230 characters:
```
C:\aaaaaaaa\bbbbbbbb\cccccccc\dddddddd\eeeeeeee\ffffffff\gggggggg\hhhhhhhh\iiiii
iii\jjjjjjjj\kkkkkkkk\llllllll\mmmmmmmm\nnnnnnnn\oooooooo\pppppppp\qqqqqqqq\rrrr
rrrr\ssssssss\tttttttt\uuuuuuuu\vvvvvvvv\wwwwwwww\xxxxxxxx\myProject11
]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
```

**Comment by Rhywden** [comment]
While this may not solve your issue, here's an FYI:

https://www.ghacks.net/2016/05/27/microsoft-260-long-path-limit/

Valid for Windows 10 only, though.

**Comment by hwillson** [comment]
What's the best approach to address this issue - maybe run a quick (Windows only) app path length check on Tool startup, and dump a friendlier error message if the path is over the limit? I think that would probably be the easiest approach to take here, and cover this edge case (without too much work).

**Comment by steph643** [comment]
Yes, I think a friendlier error message would be enough.

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in a while. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed. Thanks!
