### ISSUE TITLE
Mongo aggregation pipeline support

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8682]
I think it would be great if Meteor finally had full aggregation pipeline support. It could be that then the reactivity drops to polling. This would be better than what seems to be currently the only option and this is to store the output into a collection (which has its own issues: #4947).

So I propose a simple API where you can create a pipeline, and you get back the results. And if that is observed, then it starts polling it every 10 seconds.

I propose this to be for now only server-side feature. For Minimongo we can do another issue, but I do not see this as useful there. While for server-side it would be a great way to for example get data needed to display a chart.

Prior work: #644

**Comment by abernix** [comment]
[MongoDB Views](https://docs.mongodb.com/manual/core/views/) (available in MongoDB 3.4, so **not** the version which comes with `meteor` in development, which is currently 3.2) revolve around the "pipeline" concept.

I recently discovered that if you create a MongoDB View using the `db.createView` MongoDB shell and then `Meteor.publish` that view, ensuring to pass the `disableOplog: true` option to [`Mongo.Collection.prototype.find`](https://docs.meteor.com/api/collections.html#Mongo-Collection-find), it works quite well!  The polling speed can also be customized using `pollingIntervalMs` and `pollingThrottleMs` (documented on the previous link).

MongoDB Views accept most aggregation pipelines, so perhaps an option worth suggesting here.  Of course, we need to evaluate updating to MongoDB 3.4 for this to be available immediately in development, but anyone could play with this right now using their own `mongodb` server and by setting the [`MONGO_URL` environment variable](https://docs.meteor.com/environment-variables.html#MONGO-URL).

**Comment by mitar** [comment]
I think this is a similar to the current workaround using `$out`, no, just more "virtual"? The issue is that with this you cannot easily create one aggregation pipeline per subscription. That would mean one view per subscription. Wouldn't that be a bit too much? (Maybe you even hit the limit of how many you can have at once, there is at least such limit for number of collections you can have.)

But maybe it is more efficient to make a repeated query on the view than running aggregation pipeline repeatedly.

Personally, I would love to see both. I think both views and aggregations could be great to finally do joins in Meteor, with `$lookup` support in aggregation pipelines.

**Comment by leosco** [comment]
Yeah, this would be really great. Currently, the only real alternatives are using `Mongo.Collection.rawCollection()` with `Meteor.wrapAsync()` to get that kind of functionality, and even then, you need to put it in a server method and call it on the client in a `Tracker.autorun` or `$watch` or some other kind of reactive logic.

**Comment by mitar** [comment]
(BTW, there is [server-side autorun](https://github.com/peerlibrary/meteor-server-autorun) available. It does not help here, because aggregation query is not reactive.)

**Comment by Twisterking** [comment]
+1 ... I just implemented a quite complicated aggregate with multiple `$lookup`s inside a `Meteor.method` which is called by the client every X seconds ... currently I am using the [meteorhacks/meteor-aggregate](https://github.com/meteorhacks/meteor-aggregate) package but it would be of course very nice to have it in the core!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Mongo%20aggregation%20pipeline%20support&body=Migrated%20from:%20meteor/meteor%238682) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
