### ISSUE TITLE
Add GTM (Google Tag Manager) Script to all meteor.com entities.

### ISSUE THREAD

**Issue by rezpezz** [meteor/meteor#8683]
**Wanted to add a GTM container on all meteor.com entities. Includes all subdomains Examples include: guide.meteor.com, forumns.meteor.com, galaxy-guide.meteor.com, etc.. The following needs to be added as high in the <head> of the page as possible:**
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MBQ369M');</script>
<!-- End Google Tag Manager -->
```

**Additionally, paste this code immediately after the opening <body> tag:**
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MBQ369M"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

This will allow me to update GA's tracking parameters without the need for engineering resources. Any custom code, will still need development work, but most of the client side tracking can be done by me.

**Comment by benjamn** [comment]
Why as high as possible?

**Comment by rezpezz** [comment]
Those are directions from Google. But I'm assuming that it only needs to be located in the header.

**Comment by abernix** [comment]
@rezpezz This should be live on http://guide.meteor.com and http://docs.meteor.com (all the different versions) thanks to https://github.com/meteor/hexo-theme-meteor/commit/cc51c689a3e543e6fd58331efe0e54d7b6262847 and many commits you can see above in this pull request (each "version" of our docs is a different Git branch, accessible via the version dropdown box on the Docs page).

It is not done on http://galaxy-guide.meteor.com yet as I need to check/fix/update something else first to make that happen (in regards to the re-convergence of the various [`hexo-theme-meteor`](https://github.com/meteor/hexo-theme-meteor) branches).

**Comment by abernix** [comment]
@rezpezz This is now live on Meteor.com.

**Comment by rezpezz** [comment]
Hey, I’m seeing two GTM scripts running. Can we remove one of them?

**Comment by abernix** [comment]
Hmm, the code is only in the page once.  Is it possible that one of them was from my development server running on my laptop?

**Comment by rezpezz** [comment]
This is what I’m seeing when checking Google Tag Assistant.

**Comment by abernix** [comment]
@rezpezz I believe this is now live on all Meteor web properties:

* forums.meteor.com
* ( www . ) meteor.com
* galaxy-guide.meteor.com
* docs.meteor.com
* guide.meteor.com

It should be pointed out that Google Analytics is still active on the aforementioned, but per our (off-GitHub) conversation that should be okay, for now. :)
