### ISSUE TITLE
[Cordova] Update to new version 7.0 release with Meteor 1.5.x release

### ISSUE THREAD

**Issue by skirunman** [meteor/meteor#8686]
The Cordova project just announced a major new release to [Cordova v7.0](https://cordova.apache.org/news/2017/05/04/cordova-7.html) which includes Cordova Android v6.2.2 and Cordova iOS v4.4.0. There are also updates to most of the [Cordova plugins](https://cordova.apache.org/news/2017/05/01/plugins-release.html).

As of Meteor 1.4.4.2 we are using Cordova 6.4.0 with Cordova Android v6.1.1 and Cordova iOS v4.4.0. It would also be great to to update to Cordova Crosswalk 2.3.0, which should be the last official release of Crosswalk.

Ideally we could get issue https://github.com/meteor/meteor/issues/8195 implemented, but in the meantime we can follow the work done in https://github.com/meteor/meteor/pull/8239 to at least support this update.

These changes should be more palatable in a major release like the [1.5 release](https://github.com/meteor/meteor/pull/8327) . Also, this new feature should help with managing the issue of breaking hot code push https://github.com/meteor/meteor/pull/8581 for those that don't want to re-submit their apps.

**Comment by benjamn** [comment]
I would be all for putting this in Meteor 1.5 if there was already a working PR, and 1.5 was still in beta. Let's definitely do this for Meteor 1.5.1.

**Comment by skirunman** [comment]
Looks like there is a [Cordova 7.0.1 release](https://cordova.apache.org/news/2017/05/12/tools-release.html).

Also, with Cordova 7 it looks like there are likely some breaking changes, including moving in the direction of using npm and package.json to specify dependencies instead of config.xml, that it probably makes sense to "bite the bullet" and implement [issue 8195 to make it possible to install Cordova directly from NPM](https://github.com/meteor/meteor/issues/8195).

Unfortunately I don't have time to work on a PR, but I'd be willing to contribute to a bounty for someone to do this work. For non-react-native mobile development I think this unbundling of Cordova is really a critical feature going forward.

**Comment by skirunman** [comment]
Also, doing this update including supporting [Cordova Android 6.2.1+](https://cordova.apache.org/announcements/2017/04/05/android-release.html) should fix issue https://github.com/meteor/meteor/issues/8464

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BCordova%5D%20Update%20to%20new%20version%207.0%20release%20with%20Meteor%201.5.x%20release&body=Migrated%20from:%20meteor/meteor%238686) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by hwillson** [comment]
Sorry, re-opening (this is slotted in the 1.5.1 milestone).

**Comment by kkukielka** [comment]
Will it be merged in 1.5.1 or later? I'm still using old, sad `METEOR@1.4.3.2` for my mobile app :(

**Comment by skirunman** [comment]
I don't think anyone has submitted a PR to fix this issue including #8195

**Comment by kkukielka** [comment]
@skirunman oh. I don't know why I saw `7 commits` instead of `7 comments`. Sorry for useless question :)

**Comment by skirunman** [comment]
PR #8919 has been merged into [Meteor 1.5.2-beta.3](https://github.com/meteor/meteor/tree/release/METEOR%401.5.2-beta.3) release for Cordova 7.0.1 update so please test.

**Comment by abernix** [comment]
This has been released in Meteor 1.5.2.  Thanks so much, @skirunman!
