### ISSUE TITLE
Possible bug with DDPCommon.stringifyDDP

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#8712]
I'm not sure if this is a bug, or bad usage on my part:

When calling a subscription, e.g.: `Meteor.subscribe("thing", {_id: undefined})` the DDP client issues a message as follows: `{"msg":"sub","id":"dSEBM8Xuhhf6WdALH","name":"thing","params":[{}]}`

This results in the subscription returning every `thing` the current user has permission to view, e.g., a lot of `things`.  As opposed to my expectation of the behaviour (which may be wrong) where it returns no `things`

the "bug" appears to be in `DDPCommon.stringifyDDP`

**Comment by hwillson** [comment]
Hi @znewsham - this isn't a bug. `undefined` is not a valid JSON value, which means it can't be used with Meteor's JSON extension [`EJSON`](http://docs.meteor.com/api/ejson.html) (which is being used by DDP). As far as Meteor is concerned, you're sending in an empty object. Thanks!
