### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by elie222** [meteor/meteor#8713]
Our app has been periodically crashing for the past few months. Both in development and production. I know these issues have been raised before. Here is another version of the error that I just saw for the first time:
`Segmentation fault: 11.x86_64`
In the past I've seen:
`Segmentation fault: 11`
exit code error 6
Server write on end error

Will these issues ever get addressed?

**Comment by hwillson** [comment]
Hi @elie222 - this issue is already being tracked in #8648. Please add any additional comments/details to that issue thread. Thanks!
