### ISSUE TITLE
Meteor 1.5-rc.6 Dynamic import

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#8717]
I installed the [dynamic-import](https://atmospherejs.com/meteor/dynamic-import) package but when I try something like 
```
const path = '/imports/ui/pages';
C = await import(`${path}/login`);
```
I got the error: `Error: Cannot find module '/imports/ui/pages/login.js'`
It works with normal import likes `import('/imports/ui/pages/login.js')`

**Comment by klaussner** [comment]
[As explained here](https://github.com/meteor/meteor/pull/8327#issuecomment-288395416) (and [discussed in detail](https://github.com/meteor/meteor/pull/8327#issuecomment-296676051) further down in the comments on the pull request), you have to use string literals with `import(...)`:

> [...] you have to pass a string literal to the `import(...)` function somewhere in your code. We don't attempt any fancy static analysis of dynamic arguments. [...]

**Comment by abernix** [comment]
The above answer is correct, but to directly quote the references in #8327 (the 1.5 pull-request, which is difficult to load now given the extreme size):

@benjamn wrote in https://github.com/meteor/meteor/pull/8327#issuecomment-280876264

> > I also realized that, it doesn't dynamically load paths constructed with variables
>
> It works the same way as require in this regard: dynamic expressions do work as long as the dependency is expressed statically somewhere else in your code. This is possible because Meteor's client-side module system understands how to resolve dynamic strings at runtime (which is not true in webpack or browserify, because they replace module identifier strings with numbers). However, the set of available modules is constrained by the string literals that you, the programmer, explicitly decided to allow to be imported.
>
> This is a deliberate design decision. You don't want clients to be able to request arbitrary modules from the server at runtime. That would be a security risk, not to mention it would require pre-compiling many more files! (Yes, webpack does some clever tricks to understand certain kinds of dynamic expressions, but it doesn't work with arbitrary variables.)
>
> Instead of whitelisting safe modules in a separate configuration file, your code expresses which modules are available by importing them with statically analyzable string literals.
>
> > What's the point?
>
> The point is to avoid downloading the source of the module until you need it. A fully dynamic import(...) would mean you could postpone even knowing that you might need the module until some random client happened to ask for it, and that's not a use case worth supporting.

---

@benjamn wrote in https://github.com/meteor/meteor/pull/8327#issuecomment-288395416

> > From my understanding it should work with const modulePath instead of been rejected
>
> `@anymos` No, you have to pass a string literal to the import(...) function somewhere in your code. We don't attempt any fancy static analysis of dynamic arguments. Your example seems simple enough in isolation, but there's no end to the complexity of inferring variable values in real programs, and a partial solution (inferring the values of some variables some of the time) just means your app will break in unexpected ways as you change your code. Stick to string literals.

---

@benjamn wrote in https://github.com/meteor/meteor/pull/8327#issuecomment-296676051

> > Or, wait, is it a requirement for import('./foo') to be statically analyzable?
> If you want a module to be available for importing, it has to be imported with a string literal somewhere in your code. However, import(x) will work as long as the module named by x is available.
>
> If we come up with a good way of marking modules as available that are not statically imported anywhere, then we could easily make import(x) work. You would just need to whitelist the value of x in some yet-to-be-bikeshedded configuration file. For now, I think static string literals are a pretty elegant way of statically expressing which modules are available, since the code itself serves as the configuration. If you have to whitelist a module somewhere, it's better (more maintainable) to do it where the module gets imported than in a separate configuration file, I think.
