### ISSUE TITLE
Email attachments stopped working with 1.5-rc.6

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#8718]
Hi there,

After my upgrade from 1.5-beta.10 to 1.5-rc6, attachments are all coming through as "attachment-1.pdf" -- a file that can't actually be opened.

```
var attachment = [{
  fileName: '[Indie Shuffle permission] Test Submission.pdf',
  filePath: 'https://s3.amazonaws.com/submithub/pdfs/Prhu9i6hKJCwEAuti-permission.pdf',
  contentType: 'application/pdf'
}]
Email.send({
    to: 'jason@submithub.com', 
    from: 'jason@submithub.com',
    subject: 'Copyright Attachment',
    html: '<p>Hello, here is your attachment!</p>',
    attachments: attachment
})
```
Could this be related to the remote filePath?  I've been using this system for ~9 months now through various releases of Meteor, and this version is the first time this issue has come up :(

**Comment by hwillson** [comment]
Hi @jasongrishkoff - any chance you could put together a small runnable reproduction showing this issue? A reproduction will definitely help get this resolved more quickly. For more info see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug). Thanks!

**Comment by jasongrishkoff** [comment]
Cracked it. I was looking at the mailcomposer documentation and noticed that where I have `fileName` and `filePath`, they're using `filename` and `path`.  I'm not sure if this was a recent change, but up until the upgrade to rc.6, it was working fine with my existing camel case. I'm guessing at some point the standards were changed, and Meteor caught up to reflect that -- and therein my ~1 year old code became obsolete.

**Comment by acomito** [comment]
@jasongrishkoff thanks! I was just trying to track down what happened.

**Comment by mtwalsh** [comment]
@jasongrishkoff thanks! For me I noticed `contents` has changed to `content`!
