### ISSUE TITLE
meteor 1.5 clientside debugging stack trace not helpful

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#8719]
I know this a lower priority feature request, and I wouldn't want it to hold up 1.5 release... but having switched to dynamic imports, it's hard to identify where errors are coming from when developing.  

For example, I forgot to import a function here, very easy to fix, but the stack trace doesn't show me what file it was on, nor even where it was imported from.

![ss](https://puu.sh/w0IjL/6cc7952129.png)

**Comment by hwillson** [comment]
Hi @zeroasterisk - thanks for reporting this. If you have a chance, would you mind putting together a small repro showing this exact error? Your repro could then serve as a quick reference app when working on this, to help make sure error reporting is improved. Thanks!
