### ISSUE TITLE
1.5-rc.6 - Dynamic Imports do not (always) load Common JS modules correctly

### ISSUE THREAD

**Issue by jamiter** [meteor/meteor#8720]
Reporting this as a separate bug as discussed here: https://github.com/meteor/meteor/pull/8327#issuecomment-304095421

Normal imports work as expected:

```js
import zxcvbn from "zxcvbn"

console.log(zxcvbn) // function zxcvbn()
```

Dynamic imports however do not return the function:

```js
import("zxcvbn").then(console.log) // { __esModule: true }
```

Although the module is loaded correctly, demonstrated in this workaround:

```js
const packageName = "zxcvbn"

import("zxcvbn").then({
  const zxcvbn = require(packageName)
  console.log(zxcvbn) // function zxcvbn()
})
```

I deliberately used a string variable for the require statement so it wouldn't load the package unless already available. Putting `require(packageName)` above the `import()` statement would make it throw an error.

Package on github: https://github.com/dropbox/zxcvbn

As @benjamn mentioned, this should work but it doesn't:

```js
import("zxcvbn").then(m => console.log(m.default)) // undefined
```

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.5-rc.7` in your app. Feel free to reopen this issue if you find it's still broken!
