### ISSUE TITLE
Feature: Node 6.10 LTS - V8 perf upgrades and Chrome Dev Tools integration

### ISSUE THREAD

**Issue by rayfoss** [meteor/meteor#8722]
https://youtu.be/EdFDJANJJLs?t=26m5s

Node has had some really cool upgrades since 4.5, better v8 performance but more importantly
Dev Tools will show node instances as demonstrated on the video. Hopefully the bugs that have plagued it in previous versions have been ironed out as well.

I would love a way to use the system node version, force another node version or get a Meteor with it, even if in beta form.

I see 1.5 is planning to release with 4.8.3

**Comment by benjamn** [comment]
Please see this open pull request, which includes an early beta version of Meteor 1.6 using the latest Node, 6.10.3: https://github.com/meteor/meteor/pull/6923

Since the update command is a bit buried in that PR, I'll just give it to you here:
```sh
meteor update --release 1.6-pre.1
```

**Comment by rayfoss** [comment]
also you can jam it into the current version by modding the .meteor/dev_bundle directory.

Can't wait till june 2018!

Thanks

**Comment by benjamn** [comment]
> Can't wait till june 2018!

I sure hope we can beat that deadline 😝

**Comment by rayfoss** [comment]
![screenshot from 2017-05-28 19-13-33](https://cloud.githubusercontent.com/assets/876076/26533172/49f86fce-43da-11e7-98d7-6635ba07ef52.png)
Saweet! it works flawlessly. With 1.6-pre.1 all that's needed is `export NODE_OPTIONS='--inspect'` and you're set.
