### ISSUE TITLE
meteor 1.5-rc.10 on Internet Explorer 11: can't redefine non-configurable property __esModule

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8724]
I have updated an app to 1.5-rc.10 and i get a client error on internet explorer:

SCRIPT5078: Die nicht konfigurierbare Eigenschaft "__esModule" kann nicht neu definiert werden

(should be in english: can't redefine non-configurable property __esModule)

it happens on this line:

`import { useDeps, composeAll, composeWithTracker, compose } from 'mantra-core';`

**Comment by macrozone** [comment]
ok, happens when .babelrc contains the preset "es2015".

By the way, what are the recomended .babelrc settings for meteor?

**Comment by benjamn** [comment]
I believe this will be fixed once `1.5-rc.11` is available (currently publishing).

> By the way, what are the recomended .babelrc settings for meteor?

Our hope is that you shouldn't need a `.babelrc` file at all, but I would specifically caution you that `babel-preset-es2015` and `babel-preset-env` are likely to overlap significantly with `babel-preset-meteor`, which is always included.

**Comment by macrozone** [comment]
@benjamn thx, will check if it works.

I think my other reported issues are all because of babel-preset-es2015. I will verify that

**Comment by benjamn** [comment]
No rush, but please close this issue whenever you can confirm it's fixed in Meteor 1.5.

**Comment by jonasblumer** [comment]
I'm having the same issue

**Comment by pozylon** [comment]
Hi there, same here. Argh IE11 !!!

**Comment by macrozone** [comment]
here is the fix when using storybook:

do not use es2015 for root .babelrc as @benjamn stated.

Add an additional .babelrc inside .storybook folder:

```
{
  "extends": "../.babelrc",
  "presets": ["es2015", "stage-2", "react"]
}
```

**Comment by ffxsam** [comment]
I believe this is what's causing my app to not work at all on IE11. It's making Flow Router choke, and none of my routes work. This is with Meteor 1.5.

**Comment by ffxsam** [comment]
Disregard. Rolled back to Meteor 1.4.x, and I'm still getting the "There is no route for the path: /xyz/abc" error in IE11. I don't get any other details, so this one seems pretty tough to debug. 😢

**Comment by skirunman** [comment]
Can this be closed?

**Comment by hwillson** [comment]
Sounds like this has been resolved. Thanks all!
