### ISSUE TITLE
"referenceError: Clean is not defined" after upgrade meteor 1.4.2.6 ~ 1.4.4.3

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#8729]
meteor --version
Meteor 1.4.2.6

meteor node -v
v4.7.3

meteor npm -v
4.1.2

/lib/lib.js

```js
_ = require('lodash')

Clean = require('lodash-clean')

Is = is = require('is_js')

Dot = dot = require('dot-object')

Sizeof = sizeof = require('object-sizeof')

PrettyBytes = prettyBytes = require('pretty-bytes')

Moment = moment = require('moment')
require('twix')

Faker = faker = require('faker')

React = require('react')

Component = require('react').Component

ComposeAll = require('react-komposer').composeAll

TrackerContainer = Container = require('react-komposer').composeWithTracker

Mount = mount = require('react-mounter').mount

Form2js = form2js = require('form2js').form2js

AppStatusMap = new ReactiveMap()

CreateApp = InitApp = require('/imports')

```

package.json

```json
{
  "name": "my-meteor-starter",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "ag-grid": "^8.0.0",
    "ag-grid-enterprise": "^8.0.0",
    "ag-grid-react": "^8.0.0",
    "babel-runtime": "^6.22.0",
    "bcrypt": "^0.8.7",
    "csv-parser": "^1.11.0",
    "dot-object": "^1.5.4",
    "faker": "^3.1.0",
    "form2js": "^1.0.0",
    "is_js": "^0.9.0",
    "lodash": "^4.17.4",
    "lodash-clean": "^1.0.1",
    "meteor-node-stubs": "^0.2.4",
    "moment": "^2.17.1",
    "object-sizeof": "^1.1.1",
    "pretty-bytes": "^4.0.2",
    "randomcolor": "^0.4.4",
    "react": "^15.4.2",
    "react-addons-shallow-compare": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-komposer": "^1.13.1",
    "react-mounter": "^1.2.0",
    "react-virtualized-select": "^2.2.0",
    "recompose": "^0.20.2",
    "screenfull": "^3.0.2",
    "sift": "^3.2.6",
    "sugar": "^2.0.4",
    "twix": "^1.1.3"
  },
  "devDependencies": {
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-class-properties": "^6.16.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-umd": "^6.18.0",
    "babel-preset-latest": "^6.16.0"
  }
}
```

.babelrc

```json
{
  "plugins": [
    "add-module-exports",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

.meteor/packages

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.14                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.1                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.2   # CSS minifier run for production mode
#https://github.com/meteor/meteor/issues/8020#issuecomment-265758830
abernix:standard-minifier-js@1.2.2
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.6.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.1            # Server-side component of the `meteor shell` command

random@1.0.10
session@1.1.7
jagi:reactive-map

coffeescript@1.11.1_4
stylus

accounts-password@1.3.3
matb33:collection-hooks

kadira:flow-router
kadira:dochead

cultofcoders:grapher
ostrio:files

mikowals:batch-insert
fortawesome:fontawesome
#meteorhacks:kadira
aldeed:collection2-core
aldeed:simple-schema
aldeed:collection2
```

**Comment by crapthings** [comment]
doesn't working after upgrade

```
meteor update
meteor reset
rm -rf node_modules/
meteor npm i
```

**Comment by abernix** [comment]
Does the same problem occur if you remove the `add-module-exports` plugin from your `.babelrc`?

**Comment by crapthings** [comment]
yes, i've remove all babel rc, and switch to babel-env

even update babel-runtime

**Comment by crapthings** [comment]
i've created a new project and copy the same code and its working.

**Comment by jstxx** [comment]
did you try nuking ~/.meteor/packages ?

**Comment by crapthings** [comment]
upgrade to 1.5 still the same

i've put these code onto top of lib.js



fail
```js
A = 1

console.log(A)
```

work
```js
const A = 1

console.log(A)
```

it looks like i can't use global name

ReferenceError: A is not defined
ReferenceError: A is not defined
W20170609-14:30:15.615(8)? (STDERR)     at meteorInstall.lib.lib.js (lib/lib.js:1:1)
W20170609-14:30:15.615(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170609-14:30:15.616(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170609-14:30:15.616(8)? (STDERR)     at /Users/monsterstep/dev/dashboard-app-maker/.meteor/local/build/programs/server/app/app.js:7679:1
W20170609-14:30:15.616(8)? (STDERR)     at /Users/monsterstep/dev/dashboard-app-maker/.meteor/local/build/programs/server/boot.js:338:34
W20170609-14:30:15.617(8)? (STDERR)     at Array.forEach (native)
W20170609-14:30:15.617(8)? (STDERR)     at Function._.each._.forEach (/Users/monsterstep/.meteor/packages/meteor-tool/.1.5.0.1wzlxtu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170609-14:30:15.617(8)? (STDERR)     at /Users/monsterstep/dev/dashboard-app-maker/.meteor/local/build/programs/server/boot.js:158:5
W20170609-14:30:15.618(8)? (STDERR)     at /Users/monsterstep/dev/dashboard-app-maker/.meteor/local/build/programs/server/boot.js:387:5
W20170609-14:30:15.618(8)? (STDERR)     at Function.run (/Users/monsterstep/dev/dashboard-app-maker/.meteor/local/build/programs/server/profile.js:510:12)

**Comment by abernix** [comment]
Where are you using `Clean`? or `A`?  You're only showing where you're defining it.

Also, your reproduction seems quite a bit more complicated with too many other factors (`Faker`, `Form2js`, etc.).  Please simplify things and keep in mind that if you've already created a new project which doesn't exhibit this behavior with the same code, then it seems you might be onto solving the problem.

Ultimately, please provide the most basic reproduction you can provide which clearly shows the problem.

**Comment by crapthings** [comment]
https://github.com/nexushubs/dashboard-app-maker

master is working branch 1.4.2.6

m15 is 1.5.0

**Comment by crapthings** [comment]
reproduce

https://github.com/nexushubs/dashboard-app-maker

master is working branch 1.4.2.6

m15 is 1.5.0

@abernix

**Comment by abernix** [comment]
> Ultimately, please provide the most basic reproduction you can provide which clearly shows the problem.

Providing an entire application (with dozens and dozens of node modules and hundreds of files) to debug is really not appropriate for a basic reproduction.  A truly basic application (created with `meteor create`) does not exhibit this behavior so there was obviously something more complicated happening/conflicting/interfering here.

> yes, i've removed all babel rc, and switch to babel-env

I wasn't trying to suggest that you should replace one Babel plugin with another.  Removing the `env` preset from your `.babelrc` in this application fixed the error you are reporting, but created another which is likely caused by a circular dependency.  You should review the [default file load order](https://guide.meteor.com/structure.html#load-order) and try to trace that.

**Comment by crapthings** [comment]
hmmm i think i should drop part of Eager loading

**Comment by crapthings** [comment]
https://github.com/meteor/meteor/issues/8058
