### ISSUE TITLE
When one Npm.depends version is changed, other NPM packages are lost from Atmosphere package's node_modules

### ISSUE THREAD

**Issue by mattmccutchen** [meteor/meteor#8732]
When a local Atmosphere package depends on multiple NPM packages using `Npm.depends`, and the specified version of one of the NPM packages is changed, the Meteor build system removes the other NPM packages from the shrinkwrap file and the `node_modules` directory, causing the Atmosphere package to fail at runtime.

I originally saw this with Meteor 1.4.4.2 on Linux 64-bit on [this local package](https://bitbucket.org/objsheets/objsheets/src/8cb646bc8dc58a27e5608ac1169bb9f653c7a9e9/packages/hansoft_typescript/package.js?at=master&fileviewer=file-view-default#package.js-15), and the problem is the same with Meteor 1.5.

A small reproduction:
```
git clone https://github.com/mattmccutchen/meteor-npm-dependency-loss-repro
cd meteor-npm-dependency-loss-repro
meteor npm install
meteor  # Application runs fine.

sed -i -e '/install/s/0\.10\.0/0.10.1/' packages/example/package.js
meteor  # Error: Can't find npm module 'optimism'.

git diff packages/example/.npm/package/npm-shrinkwrap.json  # Everything except 'install' is gone.
ls -l packages/example/.npm/package/node_modules/  # Everything except 'install' is gone.

rm packages/example/.npm/package/npm-shrinkwrap.json
meteor  # Now the application is OK again.
```

**Comment by benjamn** [comment]
I seem to recall something like this changing with a recent `npm` upgrade, so you might try installing previous versions of `npm` with `meteor npm install --global npm@x.y.z`. It would be helpful to know which version introduced this problem.

Your workaround of removing the `npm-shrinkwrap.json` file should be adequate (if not convenient) for package authors to publish their packages correctly, in the meantime.

**Comment by mattmccutchen** [comment]
From stepping through the code, it really looks like 434116a is at fault.  The new code installs each dependency that wasn't previously installed, but it doesn't carry over the dependencies that _were_ previously installed.  Of course, if I just revert 434116a, then I get the error about transitive dependencies that it was originally trying to solve.  But if I go back to Meteor 1.4.2.7 (before the upgrade of npm that introduced the problem with transitive dependencies in the first place), then everything works.

**Comment by sebakerckhof** [comment]
@mattmccutchen explanation seems to make sense, since I've been seeing this bug since Meteor 1.4.3.1.
