### ISSUE TITLE
Restrict bundle-visualizer to specific URLs

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#8733]
I just read the announcement about 1.5 and the bundle-visualizer package, which looks like an excellent tool. The one thing that is going to be somewhat annoying is having to remove it every time I need to deploy (or at least ignore the package somehow when I commit).

One fix I can think of that would solve this is some way to restrict the visualizer to specific URLs. The default would be localhost, but this could also be useful for those who have a staging server (or multiple staging servers).

This could probably be done via Meteor settings `Meteor.settings.bundleVisualizer.urls` and an if statement inside the client file `if (Meteor.settings.bundleVisualizer.urls.includes(Meteor.absoluteUrl())`

**Comment by abernix** [comment]
I'm thinking #8739 is going to be a much more appropriate solution to this which will solve the annoyance you've described and will be just as accurate as the result on the staging server and more portable overall.  Remember, the `bundle-visualizer` is just one package.  You're more than welcome to create your own bundle visualizer package which behaves in a different way!
