### ISSUE TITLE
The default command should be meteor help

### ISSUE THREAD

**Issue by nunovieira** [meteor/meteor#8737]
Having "meteor run" as the default command is counter intuitive and unlike any other command interface I've encountered, e.g. angular-cli, cordova, ionic, etc...

A better experience could be achieved by using "meteor help" as the default command.
In other words, typing "meteor" should display help contents, instead of trying to run an application in development mode.

**Comment by hwillson** [comment]
Hi @nunovieira - thanks for your suggestion. While I can understand your point, I think it's safe to say that for every cli that works the way you've identified, you can find another cli that works the way Meteor does. Based on the reactions to this issue alone, I think it's safe to say the default behaviour is going to stay is as, for the foreseeable future. Closing - thanks!
