### ISSUE TITLE
Meteor.logout() and Meteor.call() too slow

### ISSUE THREAD

**Issue by emehmet** [meteor/meteor#8738]
Hi, 

I have a web app. I am living a problem about time of Meteor.logout() and Meteor.call(). When i meteor.logout(), it takes time between about 30-40 sec. Same for Meteor.call() as well. About 200-250 clients use this system on the same time.

if a client see about 100-200 items his on app screen this delay time is so much. but 10-20 items, it's a little well. we get data every 5-10 sec as different times each others on these items. I mean, live screen. 

I don't get this problem when i work this system on diffrent port with same code and same database by the way just use only me. 

I can't figure it. What can be reason it. I need your ideas and help.

**Comment by hwillson** [comment]
Hi @emehmet - Meteor's GitHub issues are reserved for bugs and/or feature requests for the platform itself. If you think you're running into a bug with Meteor then please provide more specific technical details about the problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). For help with using Meteor, please try the [Meteor forums](https://forums.meteor.com) and/or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). Closing for now - happy to re-open if you're able to provide more specific details that help demonstrate this is an issue with Meteor. Thanks!

**Comment by s7dhansh** [comment]
@emehmet I used to get such issues when there existed bugs in my publication functions, which caused too many docs to be published. So the method calls would not return until all the docs were subscribed, and seemed to be hung.
Publications are the best and the worst part of meteor. Learnt to code them properly the hard way :)
