### ISSUE TITLE
Add option to include additional packages

### ISSUE THREAD

**Issue by mpowaga** [meteor/meteor#8739]
In some cases you might want to run meteor with additional packages that are not meant to be saved in `.meteor/packages`. A good example is `bundle-visualizer` package. If you want to temporarily run your app with `bundle-visualizer` these 3 commands are needed:

1. `meteor add bundle-visualizer`
2. `meteor run`
3. `meteor remove bundle-visualizer`

This could be reduced to (as proposed by @abernix in #8735):

`meteor run --addl-packages bundle-visualizer`

Perhaps this option could be added to build command as well.

**Comment by mpowaga** [comment]
Or `--extra-packages` to put more emphasis on a fact that these are additional packages.

**Comment by dr-dimitru** [comment]
I would prefer to have `dependencies` and `devDependencies` as used in NPM. But see no way how this can be done in Meteor.

**Comment by merlinpatt** [comment]
Could bundle-visualizer be made into an NPM package?

**Comment by benjamn** [comment]
@merlinpatt Maybe so! It would be a little awkward because the package uses dynamic `import(...)` syntax, and we don't currently compile modules in `node_modules`, so the npm implementation might have to call `module.dynamicImport` directly, which might make the package useful only in Meteor, but it could work.

**Comment by merlinpatt** [comment]
The other option I can think of would be to add another flag option to packages. I seem to recall that you can mark a package as production only or dev only, so there would need to be a weird 3rd in between option of "production only when also in debug mode."

I'd opt more for making it an npm package. One, as far as I'm aware, it is still the eventual plan to convert meteor over to npm, so this option would align with that goal. Two, even if it's only useful for Meteor, i think that's fine as there are plenty of packages that are only useful to certain frameworks. Three, someone may figure out how to make it work with Meteor and with other frameworks, and putting it on npm early would make it easier for that to happen.

**Comment by abernix** [comment]
At the very least, I'm considering making the sunburst portion an npm package (as `@meteorjs/bundle-visualizer-sunburst`, perhaps?) to encourage anyone who might want to render the same chart in other tools – for example, if [Meteor Dev Tools for Chrome](https://github.com/bakery/meteor-devtools) wanted to include this in the Chrome Dev Tools – they wouldn't need to have to re-write code which could consume the `.stats.json` format.  I was thinking at first to just `Npm.depends` on said npm from `bundle-visualizer`.

@merlinpatt Did you have a particular use case?

**Comment by abernix** [comment]
@mpowaga If you want to resurrect your #8735 to work along the lines of accepting multiple packages (comma-delimited?) we can work out the decision  of `--with-packages` vs `--extra-packages` easily at merge time!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20option%20to%20include%20additional%20packages&body=Migrated%20from:%20meteor/meteor%238739) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
