### ISSUE TITLE
Warning with scoped packages in npm.depends

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8741]
In a meteor package `package.js` file, inside my meteor 1.4.4.2 project, I'm having an `Npm.depends` like:
```
Npm.depends({
  "@sebak/foo-bar: "1.0.0"
});
```

I get:
```
The handle(750) returned by watching /home/seke/dev/blue-new/projects/edu/packages/barco_accounts-saml/.npm/package/node_modules/@sebak is the same with an already watched path(/home/seke/dev/blue-new/packages/barco_accounts-saml/.npm/package/node_modules/@sebak)
...
```

Things seem to work though, so I guess I can safely ignore this?

**Comment by benjamn** [comment]
Yes, those warnings are safe to ignore, though we might be able to silence them. We've prevented similar warnings previously with [this logic](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/fs/safe-watcher.js#L32-L35).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Warning%20with%20scoped%20packages%20in%20npm.depends&body=Migrated%20from:%20meteor/meteor%238741) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
