### ISSUE TITLE
Hook that runs after any templates are dynamically imported

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#8742]
We need to dynamically process each template for this package: https://github.com/themeteorites/blaze-magic-events/issues/8#issuecomment-305465173

Is there a hook that runs every time a template is imported but before it's rendered?

**Comment by seeekr** [comment]
(Developer of the linked package here.) To be more precise, I think what we're looking for is a hook into after **anything** has been imported dynamically. Could be a template, could be a template's supporting JS.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Hook%20that%20runs%20after%20any%20templates%20are%20dynamically%20imported&body=Migrated%20from:%20meteor/meteor%238742) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
