### ISSUE TITLE
Nested exports not working in 1.5

### ISSUE THREAD

**Issue by JWo1F** [meteor/meteor#8746]
Hi! I have a strange behaviour: when I try to export some variables I see a error. For example:

```javascript
// packages/pkg/pkg1.js
export const a = 123;

// packages/pkg/pkg2.js (entry point)
export * from './pkg1.js';

// client/main.js
import { a } from 'meteor/pkg';
console.log(a); // undefined
```

**Comment by rkstar** [comment]
@JWo1F you have to `export {* as a} from './pkg1.js';`

**Comment by JWo1F** [comment]
@rkstar but in 1.4 it's working!

**Comment by hwillson** [comment]
@JWo1F - do you have a `api.mainModule('pkg1.js');` call in your `package.json`?

**Comment by rkstar** [comment]
don't know what to tell you.  `export * from...` has never worked properly for me; meteor or straight up webpack/babel.  `export {default as whatev} from ...` and `export {a} from ...` works fine.

**Comment by JWo1F** [comment]
@hwillson yes, I do.

**Comment by hwillson** [comment]
Hmm - in that case, would you mind posting a small runnable reproduction demonstrating this issue? I just tested this out on my side, and it appears to be working properly with 1.5.

**Comment by JWo1F** [comment]
@hwillson hmm, I create a new project for reproducing it, but all is okay. I'll look into it.

**Comment by JWo1F** [comment]
I'm sorry, all working.
