### ISSUE TITLE
After update to 1.5 Meteor rendering blank pages and no errors

### ISSUE THREAD

**Issue by davidalekna** [meteor/meteor#8748]
Hi, I'm using Angular 1 in my project. I have updated with **meteor update** to 1.5 and running my app after update wouldn't render anything, I can only see blank screen with no errors on browser or server... ? Any help would be appreciated!

**Comment by davidalekna** [comment]
Its meteor-static-templates error. Can be referenced here: [https://github.com/Urigo/meteor-static-templates/issues/15](url)

**Comment by mackbrowne** [comment]
I had this problem, for some reason your link doesn't work

https://github.com/Urigo/meteor-static-templates/issues/15
