### ISSUE TITLE
[accounts-password] package - overwhelming dependencies

### ISSUE THREAD

**Issue by dr-dimitru** [meteor/meteor#8753]
Hello folks,

Since 1.5 release, everyone is talking about optimization and app bundle size, which I thing is great topic.

So, I just noticed about `email` package dependency on `accounts-password`, which I would prefer to be the `{weak: true}` dependency. As we are (*and I believe we're not alone*) not using Meteor' `email` package to send emails, as well as intercept default behavior or simply using Accounts with `{sendVerificationEmail: false}` - we don't need `email` package.

If MGD shares this point of view with me, I can send a PR.
Thank you.

**Comment by benjamn** [comment]
Just curious—what's the impact of that `email` dependency, according to the visualizer?

**Comment by dr-dimitru** [comment]
> according to the visualizer

`0` - it's server package, isn't ?

**Comment by crapthings** [comment]
when u're internal app, and you don't rely on email, only username
there's no necessary to have email

**Comment by mitar** [comment]
But why do you care about email package being loaded on the server side?

**Comment by dr-dimitru** [comment]
Hello @mitar ,

Though isn't bothering me, it will take some resources, potentially interfere with our email implementation, and in case we forgot to intercept it somewhere it will try to send an email.

**Comment by mitar** [comment]
Why would it be interfering? Do you have an example of it interfering? And if you do not set environment variable, e-mail package will just print to stdout, and not really try to send.

**Comment by dr-dimitru** [comment]
> Why would it be interfering?

That was a quick guess, on why I may want to have a `weak` dependency of the package I'm not using.

> Do you have an example of it interfering?

No.

> And if you do not set environment variable, e-mail package will just print to stdout, and not really try to send.

Good, still its crunching bits and bytes.

This is suggestion, to have an email package only if it's used.

---

Other suggestion, *probably for separate ticket*, is interception interface for all outgoing emails from this package, experience with intercepting default behavior was a pain for me.

Something like:
```js
Accounts.onOutgoingEmail((reason, params) => {
  // `reason` {String} - one of 'resetPassword', 'enrollment', 'verification', 'changePassword', 'addEmail', etc.
  // `params` {Object} - {
  //                       user: {Object} - User's object reference
  //                       to: {String} - Primary email
  //                       token: {String} - For emails with a token
  //                       link: {String} - For emails with a link
  //                     }
});
```

So we can easily control emails form (styles, templates, like having different templates for each reason, and etc.), SMTP server(s) we use, and send email or handle it in other way.

**Comment by mitar** [comment]
I think you might be interested in #7949.

**Comment by dr-dimitru** [comment]
Thank you @mitar #7949 fits this one.
Feel free to close in favor of #7949 , or lets start with `{weak: true}` for `email`

**Comment by mitar** [comment]
I will leave this one open to finish discussion about `{weak: true}`.

**Comment by hwillson** [comment]
Hi all - let's move the `{ weak: true }` discussion over to the FR repo. Thanks!

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Baccounts-password%5D%20package%20-%20overwhelming%20dependencies&body=Migrated%20from:%20meteor/meteor%238753) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
