### ISSUE TITLE
Cannot have two user collections in the same database

### ISSUE THREAD

**Issue by ashburnham** [meteor/meteor#8757]
I think that Meteor can be improved by adding a `userCollectionName` option to the accounts-base package. The reason I think this is because:

 - Meteor only allows connection to one database by default
 - There is a use case (I'm facing it!) where you are running multiple meteor apps from a single database where each app has a completely different type of user.

Currently these users are forced into the same collection by the constraints of Meteor, the solution would be to allow them to be stored in two separate collections.

Out use case comes from the need for a customer app, through which our customers interact with us, and a separate app (with completely different codebase/functionality) which our internal team use for various back-office functions. Because they use the same database we are currently forced to mix the two types of users, from the two separate apps, in a single collection. As they are separate entities, we believe this to be bad practice and would like Meteor to allow us to store them in separate collections by setting a `userCollectionName` package.

This option would set the name of the collection assigned to `Accounts.users` and `Meteor.users`. As it is configurable by app, it allows the different apps to have separate user collections in the same database.

**Comment by dr-dimitru** [comment]
@ashburnham I'm sorry, but is there a real purpose to run multiple Meteor apps from a single DB and expect them to have different collections?

In this case I may suggest to Meteor to have default prefix added to each collection, which still a bit weird.

 1. Why not use separate DB in the same `mongod`?
 2. Why not connect app to the other (*second*) MongoDB and use data you need?

**Comment by laosb** [comment]
Though the reason provided is not very convincing, I agree that we should give developers the option, in case they want a different collection for some reasons.

**Comment by crapthings** [comment]
yes you can prefix user login field to simulate multiple user collections

then you auto append prefix field to login event

you can make every thing separate by ddp ...

something like server picker can keep rooturl while u refresh page

https://github.com/partus/meteor-server-picker/blob/master/main.js

**Comment by klaussner** [comment]
> […] is there a real purpose to run multiple Meteor apps from a single DB and expect them to have different collections?

Using the same database for two apps could make sense if data is shared between both apps. However, I think that mixing two types of users in a single collection is not necessarily bad practice.

If you validate logins with [`validateLoginAttempt`](http://docs.meteor.com/api/accounts-multi.html#AccountsServer-validateLoginAttempt) to make sure that members of the dev team cannot log in as customers and vice versa, the two user types would be practically separate, even though they are stored in one collection.

**Comment by zimme** [comment]
Wouldn't it be good to also/instead support an option to provide the specific collection and just not a name for it. This way you could create a specific collection with any connection you want and that would be used for the accounts system.

A case for separate accounts collections when working against the same database could be an admin apps. i.e. you want the admin users to be completely separate from the end-users but still in the same database as the rest of the app as you would be accessing that data.

This could be handled with multiple collections and providing the connection when instantiating the collections but for smaller admin apps this kind of approach could be a simpler solution.

**Comment by dr-dimitru** [comment]
My thoughts from #8758:
I'm suggest to have two options: `collectionName` and `collection` (*I believe no need to add `user` to those properties as `Accounts` package is all about users*).

Where: 
 - `collectionName` {*String*} - Name of the collection
 - `collection` {*Mongo.Collection*} - Instance of `Mongo.Collection`, this allows to attach collection for example with connection to different mongo database, as [mentioned](https://github.com/meteor/meteor/pull/8758#issuecomment-306142452) by @zimme

**Comment by zimme** [comment]
> Where:
> 
> collectionName {String} - Name of the collection
> collection {Mongo.Collection} - Instance of Mongo.Collection, this allows to attach collection for example with connection to different mongo database, as mentioned by @zimme

I believe `collection` should take precedence over `collectionName`.

**Comment by dr-dimitru** [comment]
@zimme how about to accept two types?:

 - `collection` {*String*|*Mongo.Collection*} - Instance of `Mongo.Collection` or collection name as *String*

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Cannot%20have%20two%20user%20collections%20in%20the%20same%20database&body=Migrated%20from:%20meteor/meteor%238757) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
