### ISSUE TITLE
Error updating Meteor from 1.4.4.2 to 1.4.4.3

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#8759]
I am facing errors after updating meteor by running :

`meteor update --patch`

```
=> Meteor 1.5 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   meteor-base 1.0.4, was 1.1.0.
   Constraints on package "meteor-base":
   * meteor-base@1.0.4 <- top level
   * meteor-base@1.0.4 <- top level
   
   To allow potentially incompatible changes to top-level dependencies, you
   must pass --allow-incompatible-update on the command line.
   
=> Your application has errors. Waiting for file change.
```
Is there any workaround to fix this?

**Comment by matteosaporiti** [comment]
I also had this.  
I solved by manually modifying the meteor-base version in .meteor/versions (was @1.1.0, I put @1.0.4).

**Comment by duffar** [comment]
I'm encountering the same issue with incompatible changes to meteor-base and dynamic-import. I too was surprised to see dynamic-imports added to my 1.4.4.x project. 

Kind of disheartening to see this kind of failure in core meteor packages on a patch upgrade. I ran into something similar in the 1.4.2.x patch upgrade. I'm not sure why this isn't showing up in their upgrade testing.

Thanks for the resolution tip. I'll probably give 1.5 a shot or go back to 1.4.4.2 as I don't like being on a hybrid release.

**Comment by AMNeves** [comment]
Had the same problem didnt touch anything updated to 1.5 with meteor update.
Everything works!

**Comment by duffar** [comment]
Same results here. Moving to 1.5 worked. Which I'm happy about. 
But updating to the patch *should* have worked too. Clearly a gap in the upgrade testing path.
Thanks @AMNeves

**Comment by MartiniHenry1988** [comment]
Updating to Meteor 1.5 fixed it for me. So if someone else is facing this issue, just run `meteor update` command again.
