### ISSUE TITLE
Several Problems with cordova on ios when using plugins that start meteor in the background (like geofencing)

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8763]
This is a continuation of https://github.com/meteor/meteor/issues/7018,
but i realized that there are multiple reasons, why a cordova app can crash on startup and the issue above seems not appropriate for the issue that we have.

I also realized that this might be related to the fact that some cordova plugins like https://github.com/transistorsoft/cordova-background-geolocation-lt can start the app in the background.

I created a reproduction:
https://github.com/panter/meteor-ios-background-geo-crash-reproduction

this is a simple app that has a start/stop button that toggles tracking and writes waypoints into a collection.

It's actually not that easy to reproduce every problem we have. So I keep track here of what we can reproduce properly:

1.  [x] app can't start in the background (reproduced below)
2.  [x] assets are not loaded, because local cordova webserver has stopped (seems to be this issue: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27)
3.  [x] app does not resume properly after beeing some time in the background and stays in the splash screen. (reason still unknown, might also be related to 2.)

**reproduction of 1:**

master branch uses default default meteor webview:
https://github.com/panter/meteor-ios-background-geo-crash-reproduction

Here you can reproduce this issue perfectly: 

- start the app in simulator
- click on start-track
- you can simulate a ride by using debug --> location --> freeway ride or so
- go back to home (cmd + shift + h)
- kill the app (cmd + shift + h twice to show all apps, swipe it away)
- wait 10seconds. IOS will relaunch the app in the background because of geofence-events (see https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-boolean-stoponterminate-true for details)
- reopen app, app will crash in the splashscreen without any error

Now, this can be **fixed** by applying: https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25, checkout this branch: https://github.com/panter/meteor-ios-background-geo-crash-reproduction/pull/1

- do the same steps as above
- app will successfully launch in the background and will continue to track waypoints
- app will successfully launch in the foreground if opened again

**Reproduction of 2 and 3**

We applied above fix in our production app, which fixes **1**. but we still have problem **2** and **3**. I have yet to reproduce this issue on the reproduction app, so i will update this issue here if I can successfully reproduce it. I also kindly ask anyone that experience the same issues to try to reproduce this on the reproduction app (please use the fix for **1**: (https://github.com/panter/meteor-ios-background-geo-crash-reproduction/pull/1)

**EDIT:** reproduction of **2**:

- use https://github.com/panter/meteor-ios-background-geo-crash-reproduction/pull/1 which applies https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25
- **run it on a real device** (it does not happen on the simulator)
- start the app, see the meteor logo below the title (this is an image which will be reloaded every second by adding a timestamp to its url)
- lock the device & wait a minute & unlock
- meteor logo is gone, see logs: 

**EDIT 2**: fix for **2**:

after digging around on github and some rubber-ducking sessions I found this: https://github.com/swisspol/GCDWebServer/pull/299

I applied it to my reproduction app... et voila:

- use https://github.com/panter/meteor-ios-background-geo-crash-reproduction/pull/2
- start app on real device
- lock device & wait a minute
- unlock device
- meteor logo is still there!

reproduction of **3**: still TODO

This is the hardest to reproduce. My hope is that its some edgecase and consecutive fault from issue 2, but I still don't know

Edit: 3 seems to have been fixed with 2, i did not experience any white-screen-of-deaths anymore! 👍 

PR for this fix is in the making

**Comment by znewsham** [comment]
@macrozone sorry to dredge this up - I'm currently fighting with this same problem, any chance you could run me through the procedure of using a custom version of the packages you mention? Is it as simple as copying the code into the meteor directory?

**Comment by macrozone** [comment]
@znewsham sorry for the very late answer, this issue was resolved some time ago with the latest cordova-plugin-meteor-webapp (which should be automatically installed usually)

**Comment by filipenevola** [comment]
thanks
