### ISSUE TITLE
Three separate copies of meteor-promise code scattered throughout built meteor bundle

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#8766]
I'm having a really hard time verifying that code within all parts of an async function my app is getting called within a Fiber.  I've been trying to put print statements in meteor-promise to verify that it's actually using `wrapCallback`, but that code exists in three places in the build meteor bundle:
* `bundle/programs/server/packages/promise.js`
* `bundle/programs/server/node_modules/meteor-promise/promise_server.js`
* `bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js`
It appears the third one is what actually gets run.
So what are the first two doing there besides wasting space/making it hard to find where Promise is actually getting monkeypatched?

**Comment by hwillson** [comment]
1. `bundle/programs/server/node_modules/meteor-promise/promise_server.js`
2. `bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js`

Meteor's Promise polyfill (with Fiber support) is maintained via the npm based [`meteor-promise`](https://www.npmjs.com/package/meteor-promise) package. These are the installation locations of this package. `#1` is used by the Meteor Tool, whereas `#2` is used by the server side of Meteor apps (so via Node).

3. `bundle/programs/server/packages/promise.js`

This is the [`promise`](https://github.com/meteor/meteor/tree/e49c9c6fb5759601be442f1999203b8d8bb5b940/packages/promise) wrapper package Meteor applications use to get access to the functionality provided by the npm `meteor-promise` package (on the server). This package depends on the npm based `meteor-promise` package; it's making sure it exists via a `Npm.depends({ 'meteor-promise', ... })` call. That means it's using the version stored at `#2` above. The Meteor Tool doesn't have access to Meteor packages, so it's installing it's own version of `meteor-promise` by requesting it from npm directly, hence the separate install at `#1`.

Hope this helps!
