### ISSUE TITLE
[1.5] Android: Uncaught SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by valorloff** [meteor/meteor#8779]
white screen in default Android browser after upgrade to 1.5, debug shows console errors: 
```
Uncaught SyntaxError: Use of const in strict mode
Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
Cannot read property 'Random' of undefined
...so on
```
there is nothing any files with 'use strict' and 'const' in project.
[look screen shot](https://cdn-enterprise.discourse.org/meteor/uploads/default/optimized/2X/7/795834f8fb7dc761c0bda7b4199dfa7eb5a78754_1_690x492.JPG)

**Comment by abernix** [comment]
I'd guess that error could be coming from an npm (in your `node_modules` directory).  Have you tried clicking on `modules.js?hash=...` to see exactly where the error is? (You should be able to see the path to the file in the comments when you click on that link.)

![](https://cl.ly/2u0i2f0j2h45/Image%202017-06-12%20at%203.14.18%20PM.public.png)

**Comment by valorloff** [comment]
Exactly! 
```
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/fs-extra/package.json                                                                                  //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
exports.name = "fs-extra";                                                                                             // 1
exports.version = "2.1.2";                                                                                             // 2
exports.main = "./lib/index";                                                                                          // 3
                                                                                                                       // 4
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"lib":{"index.js":function(require,exports,module){

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/fs-extra/lib/index.js                                                                                  //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
'use strict'                                                                                                           // 1
                                                                                                                       // 2
const assign = require('./util/assign')                                                                                // 3
                                                                                                                       // 4
const fse = {}                                                                                                         // 5
const gfs = require('graceful-fs')    
```

**Comment by abernix** [comment]
`const` support under `"use strict";` mode (as demonstrated in the code you've revealed here) is a newer addition to the ECMAScript spec and some older browsers may still not support it. You can see [here on CanIUse.com](https://caniuse.com/#feat=const) that the 3rd footnote (i.e. <sup>3</sup>) references the `strict` exclusion, specifically for some Android clients (you can hover over the <sup>3</sup> to see which ones.  I'm guessing the Android you're using is one of those versions.

Why are you having this problem?  Well, [`fs-extra` uses this syntax](https://github.com/jprichardson/node-fs-extra/blob/master/lib/index.js) and it's being shipped to your clients since some package you're using (or your app itself) is `require`-ing or `import`-ing it.

I'm truly not sure if you are intending to ship `fs-extra` to the client or not (as I'm not sure it would be terribly useful on an Android client since it's for file-system operations), but if you don't use it, you may want to look into how that dependency is ending up in the client build and remove it.  If you _do_ need it, then you'll run into this limitation in older implementations.

**Comment by abernix** [comment]
Are you _actually_ using [`fs-extra`](https://www.npmjs.com/package/fs-extra) on the client, somehow?  Or are you just using it on the server and it's (accidentally) getting included in client-side code?

**Comment by valorloff** [comment]
i'm using it locally in /lib/collections.js for image path generation:
```
Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  storagePath: function(fileObj) {
      if (Meteor.isServer) {
           if (fileObj && fileObj._id) {
      const path = Meteor.settings.private.IMG_PATH + fileObj._id.substr(0,3);
      const fs = require('fs-extra');
      fs.ensureDirSync(path);
      return path;
      } else {
      return Meteor.settings.private.IMG_PATH;
        }
    }
  },
```

**Comment by hwillson** [comment]
As discussed in https://github.com/meteor/meteor/issues/8779#issuecomment-308098721, this isn't a Meteor bug. Closing - thanks!
