### ISSUE TITLE
Angular 1 + Meteor 1.2 - Web Application is getting heavier and slower day by day

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#8780]
I have a huge Web Application build on Angular 1 + Meteor 1.2. 
(Migration to 1.4 or 1.5 is not possible for me here due to huge Web and Mobile Apps).

At the start of the Project everything was smooth and fast, but as long as the App started to grow in size, functionalities and database records, it started to get messed up.

- The Web App is getting slower day by day. 
- The behavior is too heavy and slow. 
- Also the build time is taking too much time. Whenever I save some code, it gets more than 3 minutes to build.

4 of my Mongodb collections have exceeded 15000+ records (each).

I am using limited columns in the Publications/Subscriptions and returning limited records. 

What should I do here? My App is totally messed up.

**Comment by stubailo** [comment]
The solutions are all in newer versions - that's why we release them, to make things better and faster. Pretty much all of the things you mentioned have been significantly improved. What's blocking you from updating? Maybe we can work on that.

**Comment by MartiniHenry1988** [comment]
@stubailo The latest Meteor has a structure of imports & exports, which I don't have in Meteor 1.2. Also the version of Angular 1 used $scope & simple javascript and simple $meteor.autorun, but here in Meteor 1.5 we are using Observables, Typescript, etc. So it is a lot different & its really hard for me to migrate everything. It will literally take a lot of months for me to migrate & test everything to the new standards.

**Comment by klaussner** [comment]
You don't have to use `import`/`export`, Observables, or TypeScript. The global namespacing and eager loading still works in 1.5 and you can write the same JavaScript code as in 1.2. Most of the changes in newer versions are backwards compatible, and for everything else there are [migration instructions in the Meteor Guide](https://guide.meteor.com/1.5-migration.html).

**Comment by MartiniHenry1988** [comment]
@klaussner  What about the client changes i.e Angular 1? I am using $scope everywhere

**Comment by klaussner** [comment]
I have never used Angular with Meteor but I don't see why it shouldn't work in Meteor 1.5. Just `meteor update` and try it out! 🙂  If your project is under version control, you can easily go back to the Meteor version you are currently using.

**Comment by laosb** [comment]
Your code should work in Meteor 1.5, just have a try!

**Comment by MartiniHenry1988** [comment]
I ran meteor update, and on client browser console, I am getting this:

```
GET http://localhost:3000/sockjs/info?cb=7cfr43dx1j 200 OK 6ms	 ddp-cli...edb9aec (line 1060)

Error: angular@^1.2.27 not installed. tmeasda...41c29b6 (line 84, col 11)

GET http://localhost:3000/_timesync 200 OK 3ms	http.js...f6d8340 (line 292)


WARNING: Tried to load angular more than once. angular...23e8d67 (line 26326)

GET http://localhost:3000/cfs/servertime 200 OK 6ms	http.js...f6d8340 (line 292)

Error: [$injector:modulerr] Failed to instantiate module MyTestApp due to:
[$injector:modulerr] Failed to instantiate module accounts.ui due to:
[$injector:nomod] Module 'accounts.ui' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=accounts.ui
minErr/<@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:93:12
module/<@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:2059:1
ensure@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:1983:38
module@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:2057:1
loadModules/<@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:4549:22
forEach@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:346:11
loadModules@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:4533:5
loadModules/<@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:4550:40
forEach@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:346:11
loadModules@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:4533:5
createInjector@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:4455:19
bootstrap/doBootstrap@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:1735:20
bootstrap@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:1756:1
angularInit@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:1641:5
@http://localhost:3000/packages/angular_angular.js?hash=ba46867929499f57e7b9be4d72abbbbdd0372009:30734:5
require<.node_modules.meteor.jquery["jquery.js"]/</jQuery.Callbacks/fire@http://localhost:3000/packages/jquery.js?hash=0c5fac3e4b18ec685e561deac3634fb49bc807e5:3200:10
require<.node_modules.meteor.jquery["jquery.js"]/</jQuery.Callbacks/self.fireWith@http://localhost:3000/packages/jquery.js?hash=0c5fac3e4b18ec685e561deac3634fb49bc807e5:3312:7
require<.node_modules.meteor.jquery["jquery.js"]/</<.ready@http://localhost:3000/packages/jquery.js?hash=0c5fac3e4b18ec685e561deac3634fb49bc807e5:3524:1
completed@http://localhost:3000/packages/jquery.js?hash=0c5fac3e4b18ec685e561deac3634fb49bc807e5:3555:3


	

return new ErrorConstructor(message);
```

**Comment by MartiniHenry1988** [comment]
Ok so I have successfully updated my app from 1.2 to 1.5.

When I updated the app to 1.5, it started giving me this message on Meteor server terminal:

```
Your development database is using mmapv1, the old, pre-MongoDB 3.0 database
engine. You should consider upgrading to Wired Tiger, the new engine. The
easiest way to do so in development is to run meteor reset. If you'd like to
migrate your database, please consult
https://docs.mongodb.org/v3.0/release-notes/3.0-upgrade/
```

So what I did was, I had a dump of my whole database, so I imported the database to my updated app and the message is now disappeared. I am concerned that is it really fixed? or is there still some procedure to do?

**Comment by abernix** [comment]
If the message is gone when you restart `meteor`, that's it! :smile:
