### ISSUE TITLE
Specific combination of package updates breaks IE11

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8782]
I apologize in advance for the lack of detailed information. I captured as much as I can though. And as usual, I can't provide a reproduction repo since it's proprietary code.

My app suddenly stopped working in IE11, completely. There was a console error about "No such route". I used `git bisect` to locate the bad commit, and found that it was solely a set of Meteor package updates that broke things. Here's the diff (from good commit to bad commit):

```diff
diff --git a/.meteor/.finished-upgraders b/.meteor/.finished-upgraders
index a802037..2a56593 100644
--- a/.meteor/.finished-upgraders
+++ b/.meteor/.finished-upgraders
@@ -15,3 +15,4 @@ notices-for-facebook-graph-api-2
 1.4.0-remove-old-dev-bundle-link
 1.4.1-add-shell-server-package
 1.4.3-split-account-service-packages
+1.5-add-dynamic-import-package
diff --git a/.meteor/packages b/.meteor/packages
index a017428..8636d50 100644
--- a/.meteor/packages
+++ b/.meteor/packages
@@ -4,14 +4,14 @@
 # 'meteor add' and 'meteor remove' will edit this file for you,
 # but you can also edit it by hand.
 
-meteor-base@1.0.4             # Packages every Meteor app needs to have
+meteor-base@1.1.0             # Packages every Meteor app needs to have
 mobile-experience@1.0.4       # Packages for a great mobile UX
-mongo@1.1.17                   # The database Meteor supports right now
+mongo@1.1.18                   # The database Meteor supports right now
 jquery@1.11.10                  # Helpful client-side library
 tracker@1.1.3                 # Meteor's client-side reactive programming library
 
 es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
-ecmascript@0.7.3              # Enable ECMAScript2015+ syntax in app code
+ecmascript@0.8.0              # Enable ECMAScript2015+ syntax in app code
 
 react-meteor-data
 jagi:astronomy
@@ -19,14 +19,14 @@ random@1.0.10
 static-html@1.1.12_1
 zimme:active-route
 kadira:flow-router
-reactive-dict@1.1.8
+reactive-dict@1.1.9
 universe:i18n
 babrahams:constellation
 mdg:validated-method
 edgee:slingshot
 accounts-password@1.3.6
 standard-minifier-css@1.3.4
-standard-minifier-js@2.0.0
+standard-minifier-js@2.1.0
 practicalmeteor:mocha
 dburles:factory
 hwillson:stub-collections
@@ -37,3 +37,4 @@ session@1.1.7
 mikowals:batch-insert
 ffxsam:galaxy-maintenance
 email@1.2.1
+dynamic-import
diff --git a/.meteor/release b/.meteor/release
index fb6f3bc..025f64e 100644
--- a/.meteor/release
+++ b/.meteor/release
@@ -1 +1 @@
-METEOR@1.4.4.2
+METEOR@1.5
diff --git a/.meteor/versions b/.meteor/versions
index b5192b6..4d9a391 100644
--- a/.meteor/versions
+++ b/.meteor/versions
@@ -1,10 +1,10 @@
-accounts-base@1.2.17
+accounts-base@1.3.0
 accounts-password@1.3.6
 aldeed:template-extension@4.1.0
 allow-deny@1.0.5
 amplify@1.0.0
 autoupdate@1.3.12
-babel-compiler@6.18.2
+babel-compiler@6.19.2
 babel-runtime@1.0.1
 babrahams:constellation@0.4.6
 babrahams:editable-json@0.6.4
@@ -13,7 +13,7 @@ base64@1.0.10
 binary-heap@1.0.10
 blaze@2.3.2
 blaze-tools@1.0.10
-boilerplate-generator@1.0.11
+boilerplate-generator@1.1.0
 caching-compiler@1.1.9
 caching-html-compiler@1.1.2
 callback-hook@1.0.10
@@ -35,11 +35,14 @@ ddp-rate-limiter@1.0.7
 ddp-server@1.3.14
 deps@1.0.12
 diff-sequence@1.0.7
-ecmascript@0.7.3
-ecmascript-runtime@0.3.15
+dynamic-import@0.1.1
+ecmascript@0.8.0
+ecmascript-runtime@0.4.1
+ecmascript-runtime-client@0.4.1
+ecmascript-runtime-server@0.4.1
 edgee:slingshot@0.7.1
 ejson@1.0.13
-email@1.2.1
+email@1.2.3
 es5-shim@4.6.15
 fastclick@1.0.13
 ffxsam:galaxy-maintenance@0.8.2
@@ -52,7 +55,7 @@ htmljs@1.0.11
 http@1.2.12
 hwillson:stub-collections@1.0.3
 id-map@1.0.9
-jagi:astronomy@2.4.3
+jagi:astronomy@2.4.4
 jagi:astronomy-timestamp-behavior@2.0.0
 jquery@1.11.10
 kadira:flow-router@2.12.1
@@ -60,21 +63,21 @@ lai:collection-extensions@0.2.1_1
 lai:ddp-inspector@1.1.9
 launch-screen@1.1.1
 livedata@1.0.18
-localstorage@1.0.12
+localstorage@1.1.0
 logging@1.1.17
 mdg:validated-method@1.1.0
 mdg:validation-error@0.5.1
 meteor@1.6.1
-meteor-base@1.0.4
+meteor-base@1.1.0
 mikowals:batch-insert@1.1.14
 minifier-css@1.2.16
-minifier-js@2.0.0
-minimongo@1.0.23
+minifier-js@2.1.0
+minimongo@1.2.0
 mobile-experience@1.0.4
 mobile-status-bar@1.0.14
-modules@0.8.2
-modules-runtime@0.7.10
-mongo@1.1.17
+modules@0.9.1
+modules-runtime@0.8.0
+mongo@1.1.18
 mongo-id@1.0.6
 mousetrap:mousetrap@1.4.6_1
 npm-bcrypt@0.9.2
@@ -86,11 +89,11 @@ practicalmeteor:loglevel@1.2.0_2
 practicalmeteor:mocha@2.4.5_6
 practicalmeteor:mocha-core@1.0.1
 practicalmeteor:sinon@1.14.1_2
-promise@0.8.8
+promise@0.8.9
 random@1.0.10
 rate-limit@1.0.8
-react-meteor-data@0.2.9
-reactive-dict@1.1.8
+react-meteor-data@0.2.11
+reactive-dict@1.1.9
 reactive-var@1.0.11
 reload@1.1.11
 retry@1.0.9
@@ -103,7 +106,7 @@ spacebars@1.0.15
 spacebars-compiler@1.1.2
 srp@1.0.10
 standard-minifier-css@1.3.4
-standard-minifier-js@2.0.0
+standard-minifier-js@2.1.0
 static-html@1.2.2
 templating@1.3.2
 templating-compiler@1.3.2
@@ -115,9 +118,8 @@ tracker@1.1.3
 u2622:persistent-session@0.4.4
 ui@1.0.13
 underscore@1.0.10
-universe:i18n@1.11.2
-universe:utilities@2.3.3
+universe:i18n@1.14.0
 url@1.1.0
-webapp@1.3.15
+webapp@1.3.16
 webapp-hashing@1.0.9
 zimme:active-route@2.3.2
```

**Comment by abernix** [comment]
Thanks for reporting this.  I realize there are only a couple involved, but it would be very helpful to eliminate the third-party packages as possible sources of problems before continuing.

You can also just revert (or manually change) those lines in your `.meteor/versions` file using the above diff as a reference.  Also, have you tried just creating a brand new 1.5 project using `meteor create` and seeing if that works with IE11?

**Comment by abernix** [comment]
Hmm, this seems to be inconsistent with your comment here: https://github.com/meteor/meteor/issues/8724#issuecomment-307654001.  Are you still getting the same error with Meteor 1.4.x?

**Comment by ffxsam** [comment]
I know, I'm always short on useful info. 😞 This is a tough one to troubleshoot. I can't just remove third party packages, because then my app will break (and for good reason). I've tried downgrading some by editing `.meteor/versions` and `.meteor/packages` directly, but sometimes that yields fatal dependency errors.

My schedule is insane. I'll try to set aside some time to individually upgrade packages until something breaks. Or should I upgrade to 1.5 and then downgrade each package till it works? Whatever will result in no/fewer package version dependency errors.

**Comment by abernix** [comment]
As a suggestion, since core packages are handled in the `meteor` checkout and you're familiar with how to use `git bisect`, instead of doing a `git bisect` on your own app, try running [Meteor from a checkout](https://github.com/meteor/meteor/blob/devel/Development.md#running-from-a-git-checkout) and using the checked out Meteor to run your app.

First, start your app with:

```sh
$ cd /your/app/dir
$ /path/to/meteor-checkout-dir/meteor run
```

This should get your app up and running and it should be broken in the same way you demonstrated (since `devel` is _pretty much_ Meteor 1.5, right now).  You may want to first try with a test app just to make sure your Meteor checkout works (e.g. `/path/to/meteor-checkout-dir/meteor create some-test-app`).

Then, in the Meteor checkout (from another terminal):

```sh
$ cd /path/to/meteor-checkout-dir
$ git bisect start
$ git bisect bad
$ git bisect good release/METEOR@<version> # Where "<version>" is a Meteor version. I've explained below...
```

The `release/METEOR@<version>` is a Git tag corresponding to the exact code of a [Meteor release](https://github.com/meteor/meteor/releases).  So if 1.4.4.2 was the last version that worked, you might do the following:

```
git bisect good release/METEOR@1.4.4.2
```

In between each step of the `git bisect`, you'll want to restart your app by Ctrl-C'ing it and executing the `/path/to/meteor-checkout-dir/meteor run` again.  It can be a _bit_ slow between some releases as it will have to change ["Dev Bundles"](https://github.com/meteor/meteor/blob/devel/Development.md#the-dev-bundle) frequently, and download them.

**Comment by theosp** [comment]
See whether [my comment here](https://github.com/jamiter/meteor/commit/a01cd04cfe2f1c9c1955aa22d6733e0d6eb33ef3#commitcomment-22771824) might help.

**Comment by hwillson** [comment]
@ffxsam - does version pinning to `localstorage@1.0.12` fix your issue?

**Comment by theosp** [comment]
@ffxsam , please do a complete cache cleaning before testing (or test in IE's "In Private" Mode). If the issue you got, is the one that started in v1.1.0 of localstorage , pinning to v1.0.12 alone won't help, as the issue destroys the localstorage on the domain in a way that persist after page reloads.

**Comment by hwillson** [comment]
PR https://github.com/meteor/meteor/pull/8852 has been merged, and should fix this issue. Closing - thanks!
