### ISSUE TITLE
[1.5] Error: nodebuffer is not supported by this browser

### ISSUE THREAD

**Issue by kosmo22** [meteor/meteor#8783]
Since updating from Meteor 1.4.4.2 to Meteor 1.5, I am getting this error in all Browsers (Chrome, Firefox, Safari). If I set back my project to 1.4.4.2, the error goes away.

Exception in delivering result of invoking 'xxxxx': Error: nodebuffer is not supported by this browser
    at Object.exports.checkSupport (http://localhost:3000/packages/modules.js?hash=129639f2b03815385d480f2b4f762862c8b7e0b2:54754:15)
    at JSZip.generate (http://localhost:3000/packages/modules.js?hash=129639f2b03815385d480f2b4f762862c8b7e0b2:54289:15)
(...)

**Comment by abernix** [comment]
This is very likely related to the change that was made in Meteor 1.5 which is reflected in [the `History.md`](https://github.com/meteor/meteor/blob/devel/History.md) for Meteor 1.5.  Specifically, the change of:

> Modules in `node_modules` directories will no longer automatically have access to the `Buffer` polyfill on the client, since that polyfill contributed more than 22KB of minified JavaScript to the client bundle, and was rarely used. If you really need the Buffer API on the client, you should now obtain it explicitly with `require("buffer").Buffer` [Issue #8645](https://github.com/meteor/meteor/issues/8645).

What version of `meteor-node-stubs` are you using in your project? (`meteor npm list meteor-node-stubs`).  And have you reviewed #8645 to see if it fixes your problem already?

**Comment by kosmo22** [comment]
Thanks a lot! I hadn't read the History.md (shame on me).

This workaround solved it for me: https://forums.meteor.com/t/solved-meteor-1-5-buffer-is-not-defined/36902/7

**Comment by abernix** [comment]
Glad that fixed it for you!  I'll go ahead and close this now. :smile:
