### ISSUE TITLE
Emails won't get sent from the meteor anymore! (atleast in Accounts.forgotPassword)

### ISSUE THREAD

**Issue by lehtu** [meteor/meteor#8784]
I show this just a few moments ago, because client reported that reset password didn't work anymore.

Well I started debuggin and figured out that everything works until `Accounts.forgotPassword`
It doesn't run callback function at all. No errors, nothing.

Everything started working after updating following line in our conf:
`process.env.MAIL_URL = 'smtp://' + encod...`
to following:
`process.env.MAIL_URL = 'smtps://' + encod...`

So it's now forced to have `smtps://` in the beginning of MAIL_URL?

This happened on Meteor version 1.4.4.2 and 1.5

**Comment by lehtu** [comment]
At least if the server `smtp.gmail.com`

**Comment by klaussner** [comment]
See https://guide.meteor.com/1.5-migration.html#mail-url 🙂

**Comment by abernix** [comment]
This is mentioned in the [`History.md`](https://github.com/meteor/meteor/blob/devel/History.md#v1442-2017-05-02) as well.  If you're using a secure port, the transport should be "secure" as well – the additional `s` in `smtps://` stands for "secure" and is required for correct configuration.  While this did work in the past, it was considered a mistake. 

There has been a console warning added about this in `email` versions newer than `1.2.3`, thanks to https://github.com/meteor/meteor/pull/8707.
