### ISSUE TITLE
Meteor.method does not return Javascript Set

### ISSUE THREAD

**Issue by priyadarshy** [meteor/meteor#8789]
On the server I wrote a Meteor.method that grabs some values from a collection and returns their _id as a `Set` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)

What I got back on the client was a plain old JS object and I couldn't use the `Set` methods like `has`. Does it not get serialized by the DDP connection?

Version 1.4.2.7

**Comment by abernix** [comment]
Thanks for bringing this up!

The DDP connection utilizes [`EJSON`](https://atmospherejs.com/meteor/ejson) to serialize data which is going over the DDP connection.  While neither `Set` nor `Map` has a built-in way to be serialized into JSON (as they are not JSON-safe), EJSON is intended to be an "extended" JSON format, so it seems plausible that it could be implemented.  That said, this will be a feature request and you should open this as such on the [feature-request repository](https://github.com/meteor/meteor-feature-requests).
