### ISSUE TITLE
which one is the the winner ?

### ISSUE THREAD

**Issue by spyhole** [meteor/meteor#8790]
IronRouter or FlowRouter is default for meteor 1.5?

**Comment by StorytellerCZ** [comment]
https://guide.meteor.com/routing.html#client-side

**Comment by abernix** [comment]
@spyhole Neither is an "official" Meteor integration so neither is the default.  For future reference, [this issue tracker is for bugs in Meteor](https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md).  Your best reference for questions like this is the Meteor Guide, as linked by @StorytellerCZ above, but there are also very good answers if you search the [Meteor Forums](https://forums.meteor.com) – for example, React Router is quite popular if you're using React,

**Comment by spyhole** [comment]
@StorytellerCZ @abernix thanks
