### ISSUE TITLE
Mongo upserts with EJSON based types are no longer working

### ISSUE THREAD

**Issue by hwillson** [meteor/meteor#8794]
Reproduction: https://github.com/hwillson/broken-ejson-upsert

The changes made in https://github.com/meteor/meteor/pull/8776 impact using EJSON based types with Mongo upserts. Attempting something like:

```js
const testCollection = new Mongo.Collection(null);
testCollection.upsert({
  _id: new Mongo.ObjectID()
}, {
  $setOnInsert: {
    a: 123
  }
});
```

will throw a `Meteor does not currently support objects other than ObjectID as ids` error, even though our `_id` is an `ObjectID`. 

cc @sebakerckhof

**Comment by holmrenser** [comment]
I am currently facing this problem, and I think this is what is keeping me from updating to 1.5.
