### ISSUE TITLE
modules@0.9.1 breaks app in Android browser but not desktop browsers

### ISSUE THREAD

**Issue by yourse1f-yourorg** [meteor/meteor#8795]
If I upgrade from 'modules@0.8.0' to 'modules@0.9.1'. I get the following error using 'chrome:inspect' on my app running in the default Android browser in Androidx86 Marshmallow, in a qemu/KVM virtual machine in Ubuntu 14.04LTS:

> Uncaught TypeError: Cannot redefine property: __esModule
>   - defineProperty  (ecmascript-runtime/node_modules/core-js/modules/es6.symbol.js)
>   - setESModule [benjamin/reify -- setESModule()](https://github.com/benjamn/reify/blob/master/lib/runtime/utils.js#L84)
>   - moduleExport  [benjamin/reify -- moduleExport()](https://github.com/benjamn/reify/blob/master/lib/runtime/index.js#L58)
>   - meteorInstall.lib.api.book.author.js  [my app/...author.js](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/AsSub/lib/api/book/author.js#L1)
>   - fileEvaluate  [benjamin/install -- fileEvaluate()](https://github.com/benjamn/install/blob/master/install.js#L316)
>   - require [benjamin/install -- makeRequire()](https://github.com/benjamn/install/blob/master/install.js#L211)
>   - (anonymous function)  [my app/client/main.js](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/trunk/client/main.js#L52)

The exact way I duplicate this is to
 1. clone [the failing commit of my app](https://github.com/warehouseman/meteor-mantra-kickstarter/tree/6f09b3af7d21ce2b7cb28d939f6ed67c26414782/.meteor),
 1. revert the .meteor version control files to [the previous commit](https://github.com/warehouseman/meteor-mantra-kickstarter/tree/f3dac2c10d65d4526e38b0333ee374812ca9189d/.meteor)
     - release
     - packages
     - versions
 1. test (succeeds)
 1. upgrade 'modules-runtime@0.7.10' to 'modules-runtime@0.8.0' :: test (succeeds)
 1. upgrade 'modules@0.8.0' to 'modules@0.9.1' :: test (**FAILS**)
 1. test app in desktop browser (succeeds)

I suspect this is related to [1.5 babelrc doesn't work with babel-plugin-add-module-exports](https://github.com/meteor/meteor/issues/8793), but the issue report has too little context for me to be sure about it.

Note that *I do not build an APK*, I just connect from a VM running Marshmallow to a VM running my app.

**Comment by benjamn** [comment]
Can you try this after running `meteor update --release 1.5.1-beta.1` in your app? Specifically, `modules@0.9.2-beta.1` should address this problem, so make sure that's the version of the `modules` package in your `.meteor/versions` file.

**Comment by benjamn** [comment]
@yourse1f-yourorg Can you try this after running `meteor update --release 1.5.1-beta.1` in your app? Specifically, `modules@0.9.2-beta.1` should address this problem, so make sure that's the version of the `modules` package in your `.meteor/versions` file.

**Comment by yourse1f-yourorg** [comment]
That did the trick.  Thanks so much!
