### ISSUE TITLE
Provide current MongoDB releases with Meteor

### ISSUE THREAD

**Issue by alimgafar** [meteor/meteor#8799]
Meteor 1.5 currently ships with MongoDB 3.2. I think it should ship with 3.4 (MongoDB 3.4 has been out since December 2016). It provides several improvements over 3.2 such as enhanced collation support, a graph lookup stage to the agg pipeline, decimal support, and read-only views. You can find them in the [3.4 Release Notes](https://docs.mongodb.com/manual/release-notes/3.4/).)

MongoDB will likely announce 3.6 at MongoDB World next week with expected release in Fall 2017 (if  the date tracks with past releases). It would be good stay close to current as possible as some issues users face in 3.2 may be ameliorated with 3.4.

**Comment by hwillson** [comment]
Hi @alimgafar - would you mind re-opening this issue as a feature request in the https://github.com/meteor/meteor-feature-requests repo? We'll track it there. Thanks!

**Comment by abernix** [comment]
In addition, it's worth mentioning that if a database provider (such as Mongo Atlas, mLab, etc.) uses MongoDB 3.4 server, Meteor will already work with it just fine as of Meteor 1.4.3.2, thanks to the update of the MongoDB driver.

This is still a good idea to get updated, but I'm just saying it's not immediately clear what the benefits will be when running Meteor in development yet (which is the only place where the pre-packaged MongoDB server comes into play).

**Comment by nathantreid** [comment]
I'd really love to have this. We're using collation, so I'm currently having to install MongoDB 3.4 on all of our developers' computers.

**Comment by hwillson** [comment]
This issue is now being tracked here: https://github.com/meteor/meteor-feature-requests/issues/129

**Comment by alimgafar** [comment]
Hugh,
Thanks for moving the request :-)
