### ISSUE TITLE
Meteor windows installer/uninstaller: a myriad of problems

### ISSUE THREAD

**Issue by santiagopuentep** [meteor/meteor#8802]
Meteor doesn´t unisntall completely leaving lots of files throughout the system. I had to apply a windows image (windows full reset) many times after the uninstaller failed and couldn't do it manually.

Sometimes meteor takes forever to build, sometimes I get ENOTEMPTY errors (like [https://github.com/meteor/meteor/issues/8801](https://github.com/meteor/meteor/issues/8801)).

Reinstalling sometimes fails, and if it doesn't **_forever_** to do it (not a "minute or two").

I think the uninstaller should **_completely_** remove everything, not just the .meteor folder. Many of the problems may be coming from an incomplete cleanup.

I think good support for windows should be be a priority in the meteor roadmap. I would bet many, many, many users are having the same issues. This is extremely frustrating and as much as I love meteor It makes me think seriously about changing to an other system. I can't build a startup on top of it like this and it's a shame because otherwise it's a great platform. The most important thing I think is reliability. At the very least it would be great to be able to confidently reinstall when problems arrise.

Here are some of the files I found when trying to uninstall completely (before full windows reset):

C:\Users\myuser\AppData\Local\.meteor
C:\Users\myuser\AppData\Local\PaxHeader
C:\Users\myuser\AppData\Local\Package Cache
C:\Users\myuser\AppData\Local\.meteorsession

Tons of themporary files in AppData and Windows.

Registry entries:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Current\Installer\UserData\S-1-5-21-3483250909-355789711-1187335-1000\Products\58D19403583F23441B677E7F07ADA438
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Current\Installer\UserData\S-1-5-21-3483250909-355789711-1187335-1000\Products\88942AD2C7821354B9238827C9DB7F1F
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Meteor Development Group
Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules
HKEY_CURRENT_USER\Software
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run\eg ui

Sorry if I'm saying something out of line here. I'm just completely frustrated!

Love you guys anyway.

**Comment by lightsonupstairs** [comment]
I would like to know how to install it after removing it.  I had the same frustrations although I gave up to ubuntu.

**Comment by steph643** [comment]
@santiagopuentep, I share your pain. I develop with Meteor under Windows since v0.8.5 and it has often been a frustrating experience.

**Comment by brucejo75** [comment]
I have had trouble with installs in the past...

I have developed this set of steps that seem to work for me.

1. Do not install new builds in any meteor projects.  You can enter `meteor --help` in a non-meteor directory.  If there is a new build available, it will download all the necessary bits to your `\Users\<username>\Appdata\.meteor` directory.  It will do this without any dependencies within your project and you can make sure it gets fully installed.  You can specify non-supported builds with the `--release` flag.
2. Make sure any editors you use ignore the `.meteor` directory for file search indexing.  Meteor builds emit a lot of new files and the editors can get thoroughly confused.
3. Disable any virus checkers for your project directories and for key build processes: `node.exe`, `code.exe` and `codeHelper.exe`.
4. Plus run with the new 1.5.1, it pulls in a fix for rimraf which attempts more retries before throwing `ENOTEMPTY`.
5. If you can, use an SSD partition for the meteor install at `\Users\<username>\Appdata\.meteor` and for any of your meteor projects.

All of these act to improve the file write times and to not hang onto the file handles well beyond any deletes or writes have completed.

**Comment by hwillson** [comment]
Good news - the old Meteor Windows installation process has been completely replaced in Meteor 1.6. These issues should now be resolved via the new [Chocolatey](https://chocolatey.org/install) installer. Please try upgrading to Meteor 1.6 using [Meteor's new Windows installation process](https://www.meteor.com/install), and if you're still encountering these problems let us know. Thanks!
