### ISSUE TITLE
High CPU usage for Meteor 1.5 on Windows 

### ISSUE THREAD

**Issue by nanda248** [meteor/meteor#8803]
I'm using Meteor 1.5 and node v4.8.3.
Whenever I run meteor in my project, it will use up 100% of my CPU and most of the times it just hangs at "Building the application". My project is not that big and it has only few packages also (shown below). 
blaze-html-templates      1.1.2  
dynamic-import            0.1.0* 
ecmascript                0.8.0  
es5-shim                  4.6.15  
insecure                  1.0.7  
kadira:flow-router        2.12.1  
kevohagan:sweetalert      1.0.0 
materialize:materialize   0.98.0+ 
meteor-base               1.1.0  
meteortoys:allthings      3.0.0  
mobile-experience         1.0.4  
mongo                     1.1.18  
react-meteor-data         0.2.9* 
reactive-var              1.0.11  
shell-server              0.2.3  
standard-minifier-css     1.3.4  
standard-minifier-js      2.1.0  
themeteorchef:bert        2.1.1* 
tracker                   1.1.3  
ultimatejs:tracker-react  1.0.5  

Please refer to screenshots below to see how meteor affects my CPU usage. 
When meteor is not running: https://pasteboard.co/iE4NLWrvx.png
When meteor is running: https://pasteboard.co/iE5Q4NBKA.png  (hang)

Does anyone have any idea on how to make meteor not hang during building the application?

**Comment by benjamn** [comment]
Does it help if you set the `METEOR_DISABLE_FS_FIBERS` environment variable to `1`?

**Comment by nanda248** [comment]
May I know how to set METEOR_DISABLE_FS_FIBERS to 1? Can I do it in command line?

**Comment by benjamn** [comment]
If you're using PowerShell, I believe you run
```sh
$env:METEOR_DISABLE_FS_FIBERS = 1
```
In `cmd.exe`, it would be
```sh
set METEOR_DISABLE_FS_FIBERS 1
```
And then you run `meteor` as usual.

**Comment by brucejo75** [comment]
I have noticed that v1.5 seems to slam my CPU during builds as well.  I believe the culprit in my case is:
`Antimalware Service Executable` aka  `msmpeng.exe` which is part of Defender.

![image](https://user-images.githubusercontent.com/14342237/27261869-99ef58b8-5400-11e7-8be9-26d004927b8c.png)


I believe this runs on all new files created.  Maybe v1.5 is emitting more files than v1.4.4.3?

New builds take a significant time to run because of this I believe.  But once the build is initiated and being rebuilt it is a little more reasonable, but still much slower than v1.4.4.3.

I have a quad core i7 so it seems to be able to push through it.  I also noticed significant improvements when I upgraded my project directory to be on an SSD drive.  Much faster file access.

I do not recommend disabling the Antimalware service but if it is bad enough you can do that.

@benjamn, does v1.5 emit more / larger files than previously?  That could explain the difference between different meteor versions.

**Comment by nanda248** [comment]
I got this "Environment variable METEOR_DISABLE_FS_FIBERS 1 not defined" when I try "set METEOR_DISABLE_FS_FIBERS 1" in cmd.exe. I'm using core i5  and RAM of 8GB with windows10.

**Comment by brucejo75** [comment]
Benjamin's instructions were not quite right, for windows command line you do this:
```
set METEOR_DISABLE_FS_FIBERS=1
```
To unset the variable:
```
set METEOR_DISABLE_FS_FIBERS=
```

**Comment by nanda248** [comment]
Thanks @brucejo75 . I was able to set it. But it didn't help with my problem. It still hand at building the application.
Look at the screenshot: https://pasteboard.co/1fRpCP0G6.png

**Comment by brucejo75** [comment]
Did your install go ok?  I wonder if it is time to try a reinstall of Meteor?

**Comment by nanda248** [comment]
I tried to reinstall Meteor yesterday. It's still the same. It is using 116% of my CPU. There was no error during installation. 
https://pasteboard.co/1BU33OJNn.png

**Comment by brucejo75** [comment]
Just for kicks try shutting down sublime when the build is happening.  Have been seeing reports of people having trouble because sublime/visual code are open during a build and the CPU goes nuts with the editors trying to index all the new emitted files.

If that improves it, you need to add some rules to your editor to ignore the `.meteor` directory.

**Comment by abernix** [comment]
@nanda248 In addition to what @brucejo75 suggested, have you tried removing your existing `node_modules` directory and re-installing them with `meteor npm install`?

**Comment by tab00** [comment]
My whole development system crawls whilst my Meteor 1.5.1 app is running or building. I need to stop the app whenever I need to do any coding. It was difficult even to type this whilst the app was running, until I stopped it.

 I'm using Windows 10.

**Comment by brucejo75** [comment]
@tab00,
For build time CPU usage take a look at issue #8801.  Essentially, applications can and will monitor meteor build directories.  When they do that, they go nuts recalculating their dependencies.  So you need to exclude your build directories from applications that are pegging while Meteor is doing a build.  Examples of problem applications: antivirus, antimalware, editors (VS Code, sublime to name a couple).

For meteor execution, it seems odd that your application would take it down.  Do you have screen shots of the task manager showing busy applications?  Meteor server really only runs node so that is the relevant task for meteor.  If your browser (e.g. chrome) is pegging then your client side would be the problem.  It is possible that you may have an infinite loop somewhere you need to track down.

**Comment by tab00** [comment]
Here is a screen capture that shows node.exe using 100% of a full CPU core constantly (on a quad-core CPU):

![screen capture_process explorer showing node exe](https://user-images.githubusercontent.com/12715448/28950129-a1cdad68-78eb-11e7-9bf7-57080ecda152.png)

No process should normally be occupying a full CPU core constantly unless it is truly doing some real intensive work.

**Comment by brucejo75** [comment]
Hi @tab00, you are correct.  In stable / idle state my node apps occupy less than 5% of CPU.

Have you done any investigations?  Looks like you might be in a tightly repeating loop somewhere?  In one of your publications?  Maybe a method?

Have you created a simple meteor app with [`meteor create`](http://docs.meteor.com/commandline.html#meteorcreate)?  And verified whether it works?

**Comment by AsafAgranat** [comment]
I'm too suffering high CPU load while meteor is running. Node.js  is at around 12% CPU. and Sublime text at around 30%. This really cripples work and heats the computer up.

**Comment by brucejo75** [comment]
@AsafAgranat, try shutting down sublime while running meteor and see what happens.  If you see improvement then you should look at #8801.

**Comment by brettg2** [comment]
We just noticed high CPU usage as well. I've tried the METEOR_DISABLE_FS_FIBERS=1 trick, removed a few libraries/packages, and even cleared the server side code with no effect. The CPU usage starts at 1-10%, then slowly climbs after each hard (no-cache) reload. After a few, the usage can easily climb past 50% and remain there until I restart the meteor process.

![image](https://user-images.githubusercontent.com/6796960/29325889-a3b6c178-81a6-11e7-9e02-c054d3966e10.png)

aldeed:template-extension 4.1.0
alisalaah:jquery-contextmenu 1.6.6
blaze-html-templates 1.1.2
dynamic-import 0.1.1
ecmascript 0.8.2
ecwyne:mathjs 2.7.0
es5-shim 4.6.15
flawless:meteor-toastr 1.0.1
fortawesome:fontawesome 4.7.0
fourseven:scss 3.13.0*
icebrg82:blaze-magic-events 0.0.6
jquery 1.11.10
lepozepo:accounting 1.0.0
meteor 1.7.0*
mizzao:jquery-ui 1.11.4
momentjs:moment 2.18.1
numeral:numeral 1.5.3_1
oaf:moment-duration-format 1.3.2
reactive-dict 1.1.9
reactive-var 1.0.11
robertlowe:persistent-reactive-dict 0.1.2
standard-minifier-css 1.3.4
standard-minifier-js 2.1.1
tracker 1.1.3
webapp 1.3.17

**Comment by tab00** [comment]
I've still been experiencing the consistently high CPU usage with Meteor 1.5.2.

@brucejo75,
> Have you done any investigations?
> 
> Have you created a simple meteor app with meteor create? And verified whether it works?

I've just spent a few hours testing with a simple React app and gradually adding Meteor packages and then NPM packages (without adding any more code).

I have found that the CPU utilization started off well under 10% consistently, and as Meteor and NPM packages were added, it went up to around 19% consistently.

Meteor packages:

accounts-facebook
--
accounts-google
accounts-password
accounts-ui
alanning:roles
aldeed:autoform
aldeed:collection2-core
aldeed:template-extension
arillo:flow-router-helpers
aslagle:reactive-table
audit-argument-checks
babrahams:transactions
biasport:facebook-sdk
blaze-html-templates
browser-policy
check
dschulz:jquery-qrcode
ecmascript
es5-shim
facebook-config-ui
flyandi:reactive-countdown
force-ssl
fortawesome:fontawesome
fourseven:scss
gadicohen:headers
google-config-ui
http
joshowens:shareit
juliancwirko:s-alert
kadira:blaze-layout
kadira:dochead
kadira:flow-router
konecty:mongo-counter
mdg:validated-method
mdg:validation-error
meteor-base
meteorhacks:picker
meteorhacks:ssr
mobile-experience
mongo
natestrauser:connection-banner
okgrow:analytics
peerlibrary:reactive-publish
peerlibrary:user-extra
peppelg:bootstrap-3-modal
percolate:synced-cron
random
react-meteor-data
react-template-helper
reactive-var
reload
retry
sacha:spin
service-configuration
shell-server
simple:imgur
standard-minifier-css
standard-minifier-js
tracker
useraccounts:bootstrap
useraccounts:core
useraccounts:flow-routing


NPM packages:
+-- babel-runtime@6.26.0
+-- bcrypt@1.0.3
+-- bignumber.js@4.0.4
+-- body-parser@1.18.1
+-- bootstrap@4.0.0-beta
+-- bufferutil@3.0.2
+-- cheerio@1.0.0-rc.2
+-- clipboard@1.7.1
+-- dropbox@2.5.9
+-- ellipsize@0.0.3
+-- formidable@1.1.1
+-- jquery@3.2.1
+-- mailgun-js@0.13.1
+-- meteor-node-stubs@0.2.11
+-- moment@2.18.1
+-- numeral@2.0.6
+-- popper.js@1.12.5
+-- prop-types@15.5.10
+-- pusher-client@1.1.0
+-- querystringify@1.0.0
+-- react@15.6.1
+-- react-addons-pure-render-mixin@15.6.0
+-- react-dom@15.6.1
+-- react-helmet@5.2.0
+-- react-modal@2.3.2
+-- react-mounter@1.2.0
+-- react-share@1.16.0
+-- riek@1.1.0
+-- simpl-schema@0.3.2
+-- socket.io-client@2.0.3
+-- uniforms@1.20.3
+-- uniforms-bootstrap4@1.20.3
`-- utf-8-validate@3.0.3

I hope this gets fixed.

**Comment by brucejo75** [comment]
Hi @tab00, what version of  `aldeed:collection2-core` are you using?  I found issues with high CPU on **v2.0.1** so I knocked it back to **v1.2** and all is good.

**Comment by tab00** [comment]
@brucejo75 , I tried a downgrade of  aldeed:collection2-core and the CPU utilization of node.exe dropped to be between 17% and 18% for the small React app. Then I decided to remove aldeed:collection2-core together with aldeed:autoform and aldeed:simple-schema. The CPU utilization still remained between 17% and 18%.

**Comment by brucejo75** [comment]
Are you using [oplog tailing](https://themeteorchef.com/tutorials/setting-up-mongodb-oplog-tailing)?  Or [Redis oplog](https://github.com/cult-of-coders/redis-oplog)?

The main reason the server would suck up cpu cycles is because it is spinning on its observation of mongo cursors.  oplog tailing and redis oplog both help reduce that work.  And packages that add more publications can also be problematic.

You might want to start doing some profiling to detect other issues?

**Comment by tab00** [comment]
I don't use Redis.

Here are some reproducible steps:

After creating a simple default app using the following commands:
```
meteor create test-0001
cd test-0001
meteor
```
The CPU utilization of node stays at around 6%
![image](https://user-images.githubusercontent.com/12715448/30732942-05768842-9f9f-11e7-98c9-ae8e5e2d72cb.png)

If I create a simple default app and then add Meteor and NPM packages using these commands:
```
meteor create test-0002
cd test-0002

meteor add accounts-facebook accounts-google accounts-password accounts-ui alanning:roles aldeed:autoform aldeed:collection2-core aldeed:template-extension arillo:flow-router-helpers aslagle:reactive-table audit-argument-checks babrahams:transactions biasport:facebook-sdk blaze-html-templates browser-policy check dschulz:jquery-qrcode ecmascript es5-shim facebook-config-ui flyandi:reactive-countdown force-ssl fortawesome:fontawesome fourseven:scss gadicohen:headers google-config-ui http joshowens:shareit juliancwirko:s-alert kadira:blaze-layout kadira:dochead kadira:flow-router konecty:mongo-counter mdg:validated-method mdg:validation-error meteor-base

meteor add meteorhacks:picker meteorhacks:ssr mobile-experience mongo natestrauser:connection-banner okgrow:analytics peerlibrary:reactive-publish peerlibrary:user-extra peppelg:bootstrap-3-modal percolate:synced-cron random react-meteor-data react-template-helper reactive-var reload retry sacha:spin service-configuration shell-server simple:imgur standard-minifier-css standard-minifier-js tracker useraccounts:bootstrap useraccounts:core useraccounts:flow-routing

meteor npm install --save bcrypt@1.0.3 bignumber.js@4.0.4 body-parser@1.18.1 bootstrap@4.0.0-beta bufferutil@3.0.2 cheerio@1.0.0-rc.2 clipboard@1.7.1 dropbox@2.5.9 ellipsize@0.0.3 formidable@1.1.1 jquery@3.2.1 mailgun-js@0.13.1 moment@2.18.1 numeral@2.0.6 popper.js@1.12.5 prop-types@15.5.10 pusher-client@1.1.0 querystringify@1.0.0 react@15.6.1 react-addons-pure-render-mixin@15.6.0 react-dom@15.6.1 react-helmet@5.2.0 react-modal@2.3.2 react-mounter@1.2.0 react-share@1.16.0 riek@1.1.0 simpl-schema@0.3.2 socket.io-client@2.0.3 uniforms@1.20.3 uniforms-bootstrap4@1.20.3 utf-8-validate@3.0.3

meteor update
meteor
```
the CPU stays at around 16%
![image](https://user-images.githubusercontent.com/12715448/30733012-53632ef2-9f9f-11e7-80b7-6c3e4de0106f.png)

**Comment by brucejo75** [comment]
I suspect there are 1 or 2 culprits in either the npm packages or meteor packages.  Can you work to isolate?

For example:
Remove half of them, see what you get.  Still high CPU, remove half again until you see a significant change.  Then try to find the 1 or 2 packages with the highest CPU impact.

Are you on the 1.6 beta?  If so, then you can use the chrome tools for debugging.  Maybe you can use the chrome tools for profiling too and then narrow down where your CPU is busy?  May be an easier way to isolate the problem package.

**Comment by tab00** [comment]
Here are some test cases that I've done to try to isolate offending packages, but it seems more like the more packages there are the higher the CPU utilization:

<h1>Test case 0001</h1>
Input: No added packages<br/>
Script:

```
meteor create test-0001
cd test-0001
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 4.5%


<h1>Test case 0002</h1>
Input: All packages<br/>
Script:

```
meteor create test-0002
cd test-0002
meteor add accounts-facebook accounts-google accounts-password accounts-ui alanning:roles aldeed:autoform aldeed:collection2-core aldeed:template-extension arillo:flow-router-helpers aslagle:reactive-table audit-argument-checks babrahams:transactions biasport:facebook-sdk blaze-html-templates browser-policy check dschulz:jquery-qrcode ecmascript es5-shim facebook-config-ui flyandi:reactive-countdown force-ssl fortawesome:fontawesome fourseven:scss gadicohen:headers google-config-ui http joshowens:shareit juliancwirko:s-alert kadira:blaze-layout kadira:dochead kadira:flow-router konecty:mongo-counter mdg:validated-method mdg:validation-error meteor-base
meteor add meteorhacks:picker meteorhacks:ssr mobile-experience mongo natestrauser:connection-banner okgrow:analytics peerlibrary:reactive-publish peerlibrary:user-extra peppelg:bootstrap-3-modal percolate:synced-cron random react-meteor-data react-template-helper reactive-var reload retry sacha:spin service-configuration shell-server simple:imgur standard-minifier-css standard-minifier-js tracker useraccounts:bootstrap useraccounts:core useraccounts:flow-routing
meteor npm install --save bcrypt@1.0.3 bignumber.js@4.0.4 body-parser@1.18.1 bootstrap@4.0.0-beta bufferutil@3.0.2 cheerio@1.0.0-rc.2 clipboard@1.7.1 dropbox@2.5.9 ellipsize@0.0.3 formidable@1.1.1 jquery@3.2.1 mailgun-js@0.13.1 moment@2.18.1 numeral@2.0.6 popper.js@1.12.5 prop-types@15.5.10 pusher-client@1.1.0 querystringify@1.0.0 react@15.6.1 react-addons-pure-render-mixin@15.6.0 react-dom@15.6.1 react-helmet@5.2.0 react-modal@2.3.2 react-mounter@1.2.0 react-share@1.16.0 riek@1.1.0 simpl-schema@0.3.2 socket.io-client@2.0.3 uniforms@1.20.3 uniforms-bootstrap4@1.20.3 utf-8-validate@3.0.3
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 16%


<h1>Test case 0003</h1>
Input: No NPM packages, and no aldeed:collection2-core and no React Meteor packages<br/>
Script:

```
meteor create test-0003
cd test-0003
meteor add accounts-facebook accounts-google accounts-password accounts-ui alanning:roles aldeed:autoform aldeed:template-extension arillo:flow-router-helpers aslagle:reactive-table audit-argument-checks babrahams:transactions biasport:facebook-sdk blaze-html-templates browser-policy check dschulz:jquery-qrcode ecmascript es5-shim facebook-config-ui flyandi:reactive-countdown force-ssl fortawesome:fontawesome fourseven:scss gadicohen:headers google-config-ui http joshowens:shareit juliancwirko:s-alert kadira:blaze-layout kadira:dochead kadira:flow-router konecty:mongo-counter mdg:validated-method mdg:validation-error meteor-base
meteor add meteorhacks:picker meteorhacks:ssr mobile-experience mongo natestrauser:connection-banner okgrow:analytics peerlibrary:reactive-publish peerlibrary:user-extra peppelg:bootstrap-3-modal percolate:synced-cron random reactive-var reload retry sacha:spin service-configuration shell-server simple:imgur standard-minifier-css standard-minifier-js tracker useraccounts:bootstrap useraccounts:core useraccounts:flow-routing
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 8.5%


<h1>Test case 0004</h1>
Input: Only first batch of Meteor packages in test-0003<br/>
Script:

```
meteor create test-0004
cd test-0004
meteor add accounts-facebook accounts-google accounts-password accounts-ui alanning:roles aldeed:autoform aldeed:template-extension arillo:flow-router-helpers aslagle:reactive-table audit-argument-checks babrahams:transactions biasport:facebook-sdk blaze-html-templates browser-policy check dschulz:jquery-qrcode ecmascript es5-shim facebook-config-ui flyandi:reactive-countdown force-ssl fortawesome:fontawesome fourseven:scss gadicohen:headers google-config-ui http joshowens:shareit juliancwirko:s-alert kadira:blaze-layout kadira:dochead kadira:flow-router konecty:mongo-counter mdg:validated-method mdg:validation-error meteor-base
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 9%


<h1>Test case 0005</h1>
Input: Only first half of Meteor packages in test-0004<br/>
Script:

```
meteor create test-0005
cd test-0005
meteor add accounts-facebook accounts-google accounts-password accounts-ui alanning:roles aldeed:autoform aldeed:template-extension arillo:flow-router-helpers aslagle:reactive-table audit-argument-checks babrahams:transactions biasport:facebook-sdk blaze-html-templates browser-policy check dschulz:jquery-qrcode ecmascript
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 5%


<h1>Test case 0006</h1>
Input: Only second half of Meteor packages in test-0004<br/>
Script:

```
meteor create test-0006
cd test-0006
meteor add es5-shim facebook-config-ui flyandi:reactive-countdown force-ssl fortawesome:fontawesome fourseven:scss gadicohen:headers google-config-ui http joshowens:shareit juliancwirko:s-alert kadira:blaze-layout kadira:dochead kadira:flow-router konecty:mongo-counter mdg:validated-method mdg:validation-error meteor-base
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 6.5%


<h1>Test case 0007</h1>
Input: Only All NPM packages<br/>
Script:

```
meteor create test-0007
cd test-0007
meteor npm install --save bcrypt@1.0.3 bignumber.js@4.0.4 body-parser@1.18.1 bootstrap@4.0.0-beta bufferutil@3.0.2 cheerio@1.0.0-rc.2 clipboard@1.7.1 dropbox@2.5.9 ellipsize@0.0.3 formidable@1.1.1 jquery@3.2.1 mailgun-js@0.13.1 moment@2.18.1 numeral@2.0.6 popper.js@1.12.5 prop-types@15.5.10 pusher-client@1.1.0 querystringify@1.0.0 react@15.6.1 react-addons-pure-render-mixin@15.6.0 react-dom@15.6.1 react-helmet@5.2.0 react-modal@2.3.2 react-mounter@1.2.0 react-share@1.16.0 riek@1.1.0 simpl-schema@0.3.2 socket.io-client@2.0.3 uniforms@1.20.3 uniforms-bootstrap4@1.20.3 utf-8-validate@3.0.3
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 9%


<h1>Test case 0008</h1>
Input: Only first half of NPM packages in test-0007<br/>
Script:

```
meteor create test-0008
cd test-0008
meteor npm install --save bcrypt@1.0.3 bignumber.js@4.0.4 body-parser@1.18.1 bootstrap@4.0.0-beta bufferutil@3.0.2 cheerio@1.0.0-rc.2 clipboard@1.7.1 dropbox@2.5.9 ellipsize@0.0.3 formidable@1.1.1 jquery@3.2.1 mailgun-js@0.13.1 moment@2.18.1 numeral@2.0.6 popper.js@1.12.5 prop-types@15.5.10
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 8%


<h1>Test case 0009</h1>
Input: Only second half of NPM packages in test-0007<br/>
Script:

```
meteor create test-0009
cd test-0009
meteor npm install --save pusher-client@1.1.0 querystringify@1.0.0 react@15.6.1 react-addons-pure-render-mixin@15.6.0 react-dom@15.6.1 react-helmet@5.2.0 react-modal@2.3.2 react-mounter@1.2.0 react-share@1.16.0 riek@1.1.0 simpl-schema@0.3.2 socket.io-client@2.0.3 uniforms@1.20.3 uniforms-bootstrap4@1.20.3 utf-8-validate@3.0.3
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 7%


<h1>Test case 0010</h1>
Input: Only second batch of Meteor packages in test-0003 plus accounts-password<br/>
Script:

```
meteor create test-0010
cd test-0010
meteor add meteorhacks:picker meteorhacks:ssr mobile-experience mongo natestrauser:connection-banner okgrow:analytics peerlibrary:reactive-publish peerlibrary:user-extra peppelg:bootstrap-3-modal percolate:synced-cron random reactive-var reload retry sacha:spin service-configuration shell-server simple:imgur standard-minifier-css standard-minifier-js tracker useraccounts:bootstrap useraccounts:core useraccounts:flow-routing accounts-password
meteor update --all-packages
meteor
```
Result: CPU utilization of node.exe = 8%

**Comment by brucejo75** [comment]
You said you do not use Redis, do you use [oplog tailing](https://themeteorchef.com/tutorials/setting-up-mongodb-oplog-tailing)?  If not, you should.

In your instance because the app is idle you would expect the server to be idle.  But Meteor sets up observers on DB queries that you publish, so even a query that returns nothing will incur observer CPU time.

Without oplog tailing Meteor will fire up a number of polling loops checking the status of all of the queries.  As the number of DB queries increases the CPU will increase.

With oplog tailing I believe it spins up a single polling loop that looks at the oplog produced by Mongo, this becomes #query independent so keeps the cpu at a constant rate in idle mode.

Even oplog tailing has problems as the #of active queries increases.  So Redis oplog is a solution more appropriate for many active queries.

**Comment by tab00** [comment]
@brucejo75, oplog tailing is enabled by default in a Meteor development environment, and I have not changed that.

**Comment by brettg2** [comment]
Now we're getting 70-80% idle cpu usage. Really guys, what the heck is going on? This is beyond ridiculous. Please, please help

**Comment by lorenzogm** [comment]
Same here, I had to go back to Meteor 1.4.1.3. There, the idle CPU usage and the build time are decent.

**Comment by brucejo75** [comment]
Entered #9175 which I think pinpoints where the builds started to grow idle CPU: 1.4.2.7 & 1.5.2.2

Maybe MDG can find the offending checkins...

**Comment by tab00** [comment]
How about just adding a 1 ms pause in any infinite loops, even as an interim workaround?

My productivity has been crippled, as I have to keep stopping my app every time I want to do other things, and then restart when I need to see if new code works.

**Comment by SnooHD** [comment]
Facing high CPU as well.
I have laptop with a Pentium duo CPU (2.2Ghz)
For me Meteor 1.5.2.2 runs at 50-60% idle.
Meteor 1.6-rc3 same story

For me it does not slowly grow, but directly hits the 50-60% and stays that way.

**Comment by brucejo75** [comment]
@benjamn, made some commits: https://github.com/meteor/meteor/pull/8728#commits-pushed-da9dac4 that should improve this issue.

Also see: https://github.com/meteor/meteor/issues/9175#issuecomment-335209286

**Comment by rsercano** [comment]
Currently literally can't use meteor 1.5+ on Windows, I got blue screen twice with that issue 👎

**Comment by brucejo75** [comment]
@rsercano,
When Chrome's CPU goes off the chart.  In my case, it has always been an infinite loop in my code.  Do you see the spike for an app created with `meteor create`?

Before you start your app, bring up the developer tools. Navigate to your page and once it starts going just break into the code and then take a look around and find the issue.

**Comment by rsercano** [comment]
@brucejo75 Unfortunately it only happens in Windows and it happens "sometimes" so I don't think it's about my app. Apart from that I'm already opening dev-tools before meteor is u

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9175#issuecomment-336235544, this issue should now be resolved (well, at least more manageable) with Meteor 1.6. If anyone is still encountering  this issue with Meteor 1.6, please open a new issue (this one is getting a bit large and unwieldy). Thanks!
