### ISSUE TITLE
Make upsert behavior fully mongo-compliant

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8806]
Original discussion: https://github.com/meteor/meteor/pull/8796

Currently the upsert behavior is not mongo-compliant when using complex selectors.

Some examples:
Upsert: `{"foo": { "$exists": true }}, { "$setOnInsert": { "bar":" baz" }}`
In mongo would result in an object: `{ "bar": "baz" }`. But with Meteor you would get: `{ "bar": "baz", "foo": {} }`
Upsert: `{ "foo": { "$eq": "test" }},{ "$setOnInsert": { "bar": "baz" }}` should result in
 `{ "foo": "test",  "bar": "baz" }`, but in Meteor you'd get: `{ "bar": "baz", "foo": {} }`
Upsert  `{  "$and": [ { "foo": 123 }] },{ "$setOnInsert": { "bar": "baz" }}` should result in
 `{ "foo": 123,  "bar": "baz" }`, but in Meteor you'd get  `{ "bar": "baz" }`

A different approach is needed to create the `selectorModifier` here:
https://github.com/hwillson/meteor/blob/devel/packages/minimongo/minimongo.js#L786-L790

I've looked into other JS mongo implementations (e.g. `nedb`), but none seem to do it correctly.
So I've searched the mongodb codebase and the relevant functions seem to be:

`applyUpdateOpsForInsert`
https://github.com/mongodb/mongo/blob/master/src/mongo/db/exec/update.h#L137
https://github.com/mongodb/mongo/blob/master/src/mongo/db/exec/update.cpp#L735

and `populateDocumentWithQueryFields` (used by the previous):
https://github.com/mongodb/mongo/blob/master/src/mongo/db/update/update_driver.h#L73
https://github.com/mongodb/mongo/blob/master/src/mongo/db/update/update_driver.cpp#L176

And relevant tests:
https://github.com/mongodb/mongo/blob/master/src/mongo/db/update/update_driver_test.cpp

**Comment by sebakerckhof** [comment]
FYI: I'm gonna try to create a PR for this if I find some time over the weekend, so if somebody already started working on this, now is a good time to speak up :).

**Comment by tellkeygit** [comment]
In an attempt to help students learn cs, we are looking for issues that they can potentially work on.Help us by mentioning our bot "@tellkeygit {#hours}" (to solve the issue). This would help students pick up issues based on their experience. Please take a look at https://www.keygit.info for more details.

**Comment by sebakerckhof** [comment]
Okay, this should be fixed in next 1.6 build now that https://github.com/meteor/meteor/issues/8815 is merged.
