### ISSUE TITLE
Importing CSS/SCSS inside JS triggers a full app refresh

### ISSUE THREAD

**Issue by williamli** [meteor/meteor#8807]
Not sure whether this should be a feature request or can be seen as a bug.

**Meteor Version:** since the introduction of import, 1.3+
**Related Packages:** React, import, CSS, SCSS
**Expected Behavior:** Being able to bundle CSS / SCSS import inside JS file so they can live in their own file structure so that when importing / reusing these "self-bundled" components, we can just import the JS file once without worrying about importing the scss / css files in a separate scss @import file like manifest.scss.

Currently, there is 2 ways to import scss / css.

## Method 1: One way is to have a manifest file that @import other scss / css files like

```
@import "{}/node_modules/normalize-scss/sass/_normalize";
@import "{}/node_modules/breakpoint-sass/stylesheets/breakpoint";

@import "{}/imports/styles/bases/forms";
@import "{}/imports/styles/bases/buttons";
@import "{}/imports/styles/states/loading";

@import "{}/imports/ui/layouts/PanelLayout/PanelLayout";
@import "{}/imports/styles/layouts/page";
@import "{}/imports/ui/pages/HomePage/HomePage";
@import "{}/imports/ui/pages/LoginPage/LoginPage";

@import "{}/imports/ui/components/LoginComponent/LoginComponent";
@import "{}/imports/ui/components/RegistrationComponent/RegistrationComponent";
@import "{}/imports/ui/components/ErrorMessageComponent/ErrorMessageComponent";
@import "{}/imports/ui/components/MenuComponent/MenuComponent";
```

### Pro

- changes in css / scss can be rendered on the fly without app refresh

### Con

- when importing a new component, eg `LoginComponent`, aside from importing the js file inside the js code, we will also need to add it in the `manifest.scss` using @import.

## Method 2: have the component to "self-contain" the scss file by importing the scss file(s) inside the component's js code like

```
import React from 'react';
import classNames from 'classnames';
import {DotLineLoader} from 'react-inline-loaders';
import PropTypes from 'prop-types';

import "/node_modules/react-inline-loaders/dist/app.css";
import "./LoaderComponent.scss";

export default class LoaderComponent extends React.Component {
...
```

### Pro

- LoginComponent can be used by just a js import, no additional @import is required

### Con

- everytime the style file is updated, it will trigger the whole meteor app to rerender.

## Suggestion

- It will be good for the scss file changes to be rendered on the fly even when importing from inside js files

**Comment by arggh** [comment]
Changing a css file when using the package `nathantreid:css-modules` seems to trigger a full refresh as well, like so:

```css
// styles.m.css
.myStyle { background: red; }
```
```html
// component.html
<template name="component"><div class="{{styles.myStyle}}"></div></template>
```
```js
import styles from './styles.m.css';

Template.helpers({
   styles
});
```

ping @nathantreid

**Comment by hwillson** [comment]
Hi @williamli - this is definitely a feature request. Would you mind migrating this over to http://github.com/meteor/meteor-feature-requests? Thanks!
