### ISSUE TITLE
1.6-beta.1 + mquandalle:stylus

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#8810]
Just leaving this here in case it's worth mentioning in the release notes / changelog for 1.6, not sure how widely used the package is. Please close if not.

We've been using the `mquandalle:stylus` package for a long time but it seems it has finally stopped working with Meteor 1.6 due to the stylus version used and the package appears to have been unmaintained for the past 2 years.

Switching to the 'official' MDG `stylus` package works perfectly, just had to edit project-root-relative paths in import statements from `/folder-in-project-root/something/style.styl` to `{}/folder-in-project-root/something/style.styl`

Have left a similar note at https://github.com/mquandalle/meteor-stylus/issues/18

**Comment by coagmano** [comment]
If you liked the extra plugins that shipped in `mquandalle:stylus`, I made a fork of MDG's `stylus` with the plugins from `mquandalle:stylus` at `coagmano:stylus`.

**Comment by hwillson** [comment]
Thanks for sharing these details. This issue is better handled via the https://github.com/mquandalle/meteor-stylus repo, so thank's for opening an issue there. Closing here.
