### ISSUE TITLE
Supply Custom Fields to Accounts.addEmail

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#8813]
I want to use the [Accounts.addEmail](https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_server.js#L916) method, however I have a slight customization on my user emails array that makes it slightly non-standard. Because many emails can be added, I allow the user to specify a `primary` email:

```json
{
  "address": "asf@asf.asf",
  "verified": false,
  "primary": true
}
```

I want to specify that `primary` is `false` when `Accounts.addEmail` is executed, however the method doesn't supply an argument for me to do that. Could there be an optional object parameter so I can specify various fields to meet my business case, whatever that is from project to project?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Supply%20Custom%20Fields%20to%20Accounts.addEmail&body=Migrated%20from:%20meteor/meteor%238813) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
