### ISSUE TITLE
1.6-beta.1 App exits immediately on start (from bundle)

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#8817]
@benjamn Following on from #8808 I think the instant exit is a separate issue that was introduced in 8550412bb0eaa3b80ae8725f3bed128d629b9d61.

Using node inspect and some breakpoints I've narrowed it down to this line: https://github.com/meteor/meteor/blob/release-1.6/tools/static-assets/server/boot.js#L362 that was part of switching to the Node 8 inspector a few days ago. No error is thrown for some reason but commenting out the `if` statement does allow the app to run.

Let me know if you need any more details :)

**Comment by benjamn** [comment]
This should be fixed now, thanks to the commit referenced above.
