### ISSUE TITLE
Http POST automatically does Http GET when calls an REST api url that runs behind a reverse proxy and performs 301 redirects.

### ISSUE THREAD

**Issue by pc-magas** [meteor/meteor#8826]
I have created a nodejs rest api. The api runs behind nginx reverse proxy and the nginx performs 301 http redirects when I call it without https. 

The api is in `http://example.com` and I try to do an HTTP POST in `/dummy` endpoint. Any other HTTP method called in this endpoint by desighn should return 501 Http status code.

Then I did the following code to call the http call:
```
if (Meteor.isServer) {
  Meteor.methods({
    /**
     * Method that allows each user to upload files into the database
     * @param {string} fileName: The name of the file that is going to be uploaded
     * @param {string} fileMime: The mime type of the file that is goint to be uploaded
     * @param {string} fileBase64Data: The data inj base64 encoded form
     * @return The the response of an http call.
     */
    'callRestApi': function callApi(fileName, fileMime, fileBase64Data,) {

      const httpObj = {
        data: {
          filename: fileName,
          file_data: fileBase64Data,
          mime_type: fileMime,
        },

        headers: {
          'Content-type': 'application/json',
        },

        followRedirects: true,
      };

      try {
        let response = HTTP.call("POST" ,"http://example.com/dummy", httpObj);
        console.log(response);
        if (parseInt(response.statusCode,10) !== 201) {
          throw new Error('COuld not call sucessfully the API');
        }
        return JSON.parse(response.content);
      } catch (err) {
        throw err;
      }
    },
  });
}
```
The problem is that when follows the 301 redirect after it does http GET instead of http POST therefore it will return error 501.

I guess that is a library bug.

**Comment by hwillson** [comment]
Hi @pc-magas - instead of (or in addition to) using `followRedirects: true`, can you try `followAllRedirects: true`? That option should be added to the docs (see https://github.com/meteor/meteor/issues/2808 for the history), but first please confirm if that works for you. I'll then open a new issue about this in the docs repo. Thanks!

**Comment by pc-magas** [comment]
I changed the `httpObj` into this:

```
 const httpObj = {
        data: {
          filename: fileName,
          file_data: fileBase64Data,
          mime_type: fileMime,
        },

        headers: {
          'Content-type': 'application/json',
        },

        followRedirects: true,
        followAllRedirects: true
      };
```

Still does an http GET instead of http POST. Same if I change the `httpObj` into this:

```
const httpObj = {
        data: {
          user_id: this.user_id,
          group_id: groupId,
          article_id: articleId,
          filename: fileName,
          file_data: fileBase64Data,
          mime_type: fileMime,
        },

        headers: {
          'Content-type': 'application/json',
        },

        followAllRedirects: true
      };
```

Also I forgot to mention that I use the http version `1.2.12` seen in https://atmospherejs.com/meteor/http

**Comment by pc-magas** [comment]
I tries to change the `httpObj` constant into these:

1 Using both `followAllRedirects: true` and `followRedirects: true`:  
   ```

      const httpObj = {
        data: {
          filename: fileName,
          file_data: fileBase64Data,
          mime_type: fileMime,
        },

        headers: {
          'Content-type': 'application/json',
        },

        followAllRedirects: true,
        followRedirects: true,
      };
   ```
2 Using `followAllRedirects: true` only:
   ```
const httpObj = {
        data: {
          filename: fileName,
          file_data: fileBase64Data,
          mime_type: fileMime,
        },

        headers: {
          'Content-type': 'application/json',
        },

        followAllRedirects: true,
      };
   ```

I still get the very same behaviour. I use the version `1.2.12` of the library.

**Comment by hwillson** [comment]
This issue doesn't appear to be happening that frequently, which means it isn't likely to be worked on anytime soon. If you (or anyone else) is still seeing this issue and are interested in helping out with a fix, please let us know. As part of the on-going old issue cleanup process I'll close this off for now, but will happily re-open it if anyone is still seeing this problem and can lend a hand in fixing it. Thanks!
