### ISSUE TITLE
dynamic import does not work in Meteor 1.5?

### ISSUE THREAD

**Issue by EliArtist** [meteor/meteor#8827]
I'm using Meteor 1.5 in my project and now trying to use dynamic imports like this:
```import('/imports/db').then(db => {```
```            console.log(db);```
```        }); ```

But the server just prints this error:
```Error in imports/ui/components/my-component.html```
```{ [SyntaxError: Unexpected token, expected { (2:14)] pos: 15, loc: Position { line: 2, column: 14 } }```

I'm really stuck on this. Can someone help me?
If you need any more information, I'll provide it

EDIT: If I pull a demo project with dynamic import it's working. I must be missing something obvious :/

**Comment by abernix** [comment]
Are you trying to use a dynamic `import(...)` statement in an HTML file instead of a JavaScript file? (`imports/ui/components/my-component.html`?)

**Comment by rodrilink** [comment]
If you are using Typescript + Angular, use module.dynamicImport(...) directly instead of import(...) then you can modify the Node type definition @types\node or add a custom type definition to avoid your warnings in your IDE (for me Visual Code)

Example:
```
interface NodeModule {
    exports: any;
    require: NodeRequireFunction;
    id: string;
    filename: string;
    loaded: boolean;
    parent: NodeModule | null;
    children: NodeModule[];
    dynamicImport: any;
}
```
Hope this help!!

**Comment by abernix** [comment]
> EDIT: If I pull a demo project with dynamic import it's working. I must be missing something obvious :/

Closing for now.  If you can provide a reproduction, that would be most helpful, but it sounds like this is working properly in a new project so something else must be coming into play.
