### ISSUE TITLE
Meteor.loginWithGoogle without creating a user if the user doesn't exist

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#8829]
Can we have 2 separate functions: `Meteor.loginWithGoogle`, which throws an error if user doesn't exists, and `Meteor.registerWithGoogle`, which throws an error if user already exists in the db?

**Comment by laosb** [comment]
Do you have a specific case for supporting this?

Anyway, it's a feature request. You should post this to https://github.com/meteor/meteor-feature-requests.

**Comment by WayneUong** [comment]
Our user base us not very tech savvy and sometimes they get confused as why a new account is created when they login with Google.

**Comment by hwillson** [comment]
As @laosb mentioned, please consider opening this in the https://github.com/meteor/meteor-feature-requests repo. Closing here - thanks!
