### ISSUE TITLE
Migrating from 1.4.4.2 to 1.5 issue

### ISSUE THREAD

**Issue by Sphincz** [meteor/meteor#8837]
Hello. I updated from 1.4.4.2 to 1.5, and when i ran `meteor` it shows this:

```
W20170622-17:30:24.125(1)? (STDERR) C:\Users\aslra\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170622-17:30:24.125(1)? (STDERR)                                             throw(ex);
W20170622-17:30:24.126(1)? (STDERR)                                             ^
W20170622-17:30:24.126(1)? (STDERR) 
W20170622-17:30:24.127(1)? (STDERR) TypeError: module.makeNsSetter is not a function
W20170622-17:30:24.127(1)? (STDERR)     at meteorInstall.node_modules.meteor.shell-server.main.js (packages/shell-server/main.js:1:55)
W20170622-17:30:24.127(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170622-17:30:24.128(1)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170622-17:30:24.128(1)? (STDERR)     at D:\Horus\Horus Panel\horus\.meteor\local\build\programs\server\packages\shell-server.js:559:15
W20170622-17:30:24.129(1)? (STDERR)     at D:\Horus\Horus Panel\horus\.meteor\local\build\programs\server\packages\shell-server.js:565:3
W20170622-17:30:24.129(1)? (STDERR)     at D:\Horus\Horus Panel\horus\.meteor\local\build\programs\server\boot.js:338:34
W20170622-17:30:24.130(1)? (STDERR)     at Array.forEach (native)
W20170622-17:30:24.130(1)? (STDERR)     at Function._.each._.forEach (C:\Users\aslra\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20170622-17:30:24.130(1)? (STDERR)     at D:\Horus\Horus Panel\horus\.meteor\local\build\programs\server\boot.js:158:5
W20170622-17:30:24.131(1)? (STDERR)     at D:\Horus\Horus Panel\horus\.meteor\local\build\programs\server\boot.js:387:5
```

I already reinstalled Meteor, removed and installed packages and can't resolve this issue. Anyone with this problem? Thank you!

**Comment by benjamn** [comment]
Try `meteor update modules babel-compiler`?

**Comment by Sphincz** [comment]
Thanks! It worked :)

**Comment by SevenZark** [comment]
I'm having a very similar problem, but updating the babel compiler did not fix it for me (Output said I am already at the latest version). 

This happened after running meteor update, although I don't think it upgraded meteor itself. And I don't know how to find a history of package upgrades to try to downgrade each of them to see if that fixes the issue.

I'm getting this on trying to launch my app ('meteor' from command line):

`W20170713-10:43:06.627(-5)? (STDERR) /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/boot.js:391
W20170713-10:43:06.654(-5)? (STDERR) }).run();
W20170713-10:43:06.655(-5)? (STDERR)    ^
W20170713-10:43:06.656(-5)? (STDERR) 
W20170713-10:43:06.656(-5)? (STDERR) TypeError: module.makeNsSetter is not a function
W20170713-10:43:06.657(-5)? (STDERR)     at meteorInstall.node_modules.meteor.shell-server.main.js (packages/shell-server/main.js:1:55)
W20170713-10:43:06.657(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170713-10:43:06.657(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170713-10:43:06.658(-5)? (STDERR)     at /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/packages/shell-server.js:568:15
W20170713-10:43:06.658(-5)? (STDERR)     at /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/packages/shell-server.js:574:3
W20170713-10:43:06.658(-5)? (STDERR)     at /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/boot.js:338:34
W20170713-10:43:06.658(-5)? (STDERR)     at Array.forEach (native)
W20170713-10:43:06.659(-5)? (STDERR)     at Function._.each._.forEach (/Users/[redacted]/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170713-10:43:06.659(-5)? (STDERR)     at /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/boot.js:158:5
W20170713-10:43:06.660(-5)? (STDERR)     at /Users/[redacted]/Source/[redacted]/app/.meteor/local/build/programs/server/boot.js:387:5
`

**Comment by benjamn** [comment]
@SevenZark Try `meteor update modules`?

**Comment by SevenZark** [comment]
That goes like this:

`$ meteor update modules
The specified packages are at their latest compatible versions.`

Then when I run meteor I get the same error as before.

**Comment by SevenZark** [comment]
I also tried uninstalling and re-installing Meteor while also deleting my own local codebase and re-cloning from my git repo. However, I still get the same error. All I know is that meteor update caused this problem, but I don't know which package update specifically broke things. And I have no idea how to get a history of package updates since I gitignore the versions file. :/

**Comment by benjamn** [comment]
What versions do you see for `modules` and `babel-compiler` in `.meteor/versions`? Are there any version constraints on those packages in `.meteor/packages` (they shouldn't even be mentioned there, but anything is possible)?

**Comment by SevenZark** [comment]
I've got:
• babel-compiler@6.20.0-pre.1
• modules@0.10.0-pre.1
• modules-runtime@0.9.0-pre.1

I notice those are pre-release versions, although I didn't explicitly ask for that, which seems odd.

I've pasted the contents of my packages file below, but I don't see any comments about version constraints.

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
static-html             # Define static page content in .html files
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@2.1.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.8.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.4            # Server-side component of the `meteor shell` command
kadira:flow-router
fourseven:scss
maxharris9:classnames
session@1.1.7
react-meteor-data
meteorhacks:aggregate
aldeed:collection2-core@2.0.1
practicalmeteor:mocha
xolvio:cleaner
practicalmeteor:faker
mongo@1.1.19
accounts-base@1.3.1
```

**Comment by SevenZark** [comment]
I finally solved my problem via the scorched earth method, basically just creating a new meteor project and copying over my app source. I don't know what my original problem was, but everything is working now.

**Comment by cr-arostegui** [comment]
I fixed this installing react `meteor npm install --save react` and then I stopped and started again `meteor`
