### ISSUE TITLE
[1.4.2.3] Can't run with `--production`, can't deploy

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8838]
I'm having massive problems here. I'm completely unable to deploy and unable to even run via `--production`. Here's what I get:

```
=> Errors prevented startup:

   While minifying app code:
   eval at <anonymous>
   (/Users/samh/.meteor/packages/standard-minifier-js/.1.2.1.907d5s++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:1545:18: SyntaxError: Unexpected token: punc ())
   at new JS_Parse_Error (eval at <anonymous>
   (/Users/samh/.meteor/packages/standard-minifier-js/.1.2.1.907d5s++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:1545:18)
   at js_error (eval at <anonymous>
   (/Users/samh/.meteor/packages/standard-minifier-js/.1.2.1.907d5s++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:1553:11)
   at croak (eval at <anonymous>
   (/Users/samh/.meteor/packages/standard-minifier-js/.1.2.1.907d5s++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:2089:9)
   at token_error (eval at <anonymous>
   (/Users/samh/.meteor/packages/standard-minifier-js/.1.2.1.907d5s++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
   <anonymous>:2097:9)
   at unexpected (eval at <anonymous>
```
(trimmed many more lines, probably not useful)

The funny thing is, everything was fine, and then suddenly it wasn't. Nobody on our team updated any Meteor packages. I ran `git bisect` to see if maybe it was a problem with the code, but these errors kept happening regardless. I took [this guy's advice](https://github.com/meteor/meteor/issues/8020#issuecomment-306470851) but nothing useful turned up.

Tried removing the standard minifier and installed `abernix:standard-minifier-js@2.1.0` and then ran `meteor --production`, and it just got stuck here for nearly 10 minutes so I gave up:
```
Minifying app code                        /
```

I tried a fresh clone of our project. Tried `rm -rf ~/.meteor`. Someone else on the team can do a `--production` build and deployment, no problems! I've hit a dead end and don't know what else to do here. Any help would be greatly appreciated.

**Comment by mjmasn** [comment]
Can't comment on the actual underlying issue but just deleting the global `~/.meteor` directory probably isn't enough if something got corrupted in your app.

**Warning: doing the following will delete your database and all the data in it if you're using the local meteor one** (you'll be fine if you're using a remote server or running your own (non-meteor) mongo setup locally)

Have you tried a meteor reset (or just delete the local folder inside the .meteor folder in your app's root folder)?

`cd path/to/your/meteor-app && meteor reset`

or 

`rm -rf path/to/your/meteor-app/.meteor/local`

Then try starting your app again. Seems likely this will resolve the issue if previously working git commits no longer work. If not maybe you've inadvertently changed something that is `.gitignore`-d?

**For a less nuclear option given that you've deleted `~/.meteor` already to no avail, I guess you could try cloning your repo from your git server to a new location on your machine and see if it runs before going down the `meteor reset` route.**

**Comment by ffxsam** [comment]
See my first post. Already did a fresh clone, which didn't work.

**Comment by mjmasn** [comment]
Ah my bad, missed that and just read the `rm -rf ~/.meteor` bit, sorry. 

It looks like UglifyJS is hitting es2015+ code - probably an arrow function like `() => { /*...*/ }` given the error message  `Unexpected token: punc ()` would probably be worth seeing if Meteor v1.4.4 or above works for you - it switched from UglifyJS to Babili which can handle this kind of thing.

https://github.com/meteor/meteor/blob/devel/History.md#v144-2017-04-07 

As for why, just a guess but it could be a different version of an npm module version vs your colleague, for a module that's recently started using es2015+ code.

**Comment by benjamn** [comment]
When minification starts failing even though you didn't change anything in your app, often the cause is that some new version of an npm package was released that included problematic syntax, and thus a recent `meteor npm install` silently upgraded you into trouble. Unfortunately, that's just the way npm works (unless you shrinkwrap, which has its own issues). If you can figure out which package changed, you might be able to pin it to an older version in your app's `package.json` file, though answering that question isn't always easy.

The exact minifier version is determined by the `minifier-js` package, so you might try overriding that package locally:
```sh
git clone git@github.com:meteor/meteor.git
cd path/to/your/app
mkdir -p packages
cd packages
ln -s path/to/cloned/meteor/packages/minifier-js ./
```
Now you can edit the [`your/app/packages/minifier-js/minifier.js`](git@github.com:meteor/meteor.git) file until it works in your app. You may want to remove the `Babel.minify` stuff since your version of `babel-compiler` might not (yet) support that API.

If this works, it will probably be due to using a more recent version of the `uglify-js` package.

Good luck!

**Comment by ffxsam** [comment]
@benjamn THANK YOU. `swagger-ui-dist` was the culprit.

**Comment by ffxsam** [comment]
Actually - side note: oddly enough, on someone else's machine (macOS), it works perfectly. Same packages, same codebase, everything. For me, `swagger-ui-dist` causes problems. I don't get it.
