### ISSUE TITLE
Error logging in with token: Error 

### ISSUE THREAD

**Issue by timhaines** [meteor/meteor#884]
If a browser has a resume token that's no longer present on the server side, the browser's console prints 'Error logging in with token: Error' when the site is visited.  

It's a little confusing to see this when you're resetting your DB while testing things.  I think it would be preferable to not show the message.  If you do want to show it, then it would be helpful to reword the message to explain what happened.

**Comment by alexmal0916** [comment]
When i setPassword for the logged in users, the session is expired like above.
I use Meteor 1.0.3.1.

**Comment by alexmal0916** [comment]
oh~i found the solution. it needs to use the changePassword instead of setPassword  in client side.
