### ISSUE TITLE
Command line arguments with spaces

### ISSUE THREAD

**Issue by blongstreth** [meteor/meteor#8840]
Using Meteor command line tool version 1.4 or higher on Windows 10.  I want to be able to execute various Meteor commands which take file names or output paths as command line parameters that have whitespace in the path names.  Currently, this doesn't work.  Here are some simple example commands:

**#1 Build Command**
`
meteor build --directory <output-path>  where output-path is something like C:\Users\FirstName LastName\MyProject\build\foo (whitespace between first and last name)
`
**#2 Run Command**
`
meteor run --settings <settings-file> where settings-file is something like C:\Users\\FirstName LastName\MyProject\settings-development.json (whitespace between first and last name)
`
**#3 Other Commands: Create, etc.**

For now, I will probably use staging files and directories rather than converting file name into 8.3. format.   Please help if possible.

Finally,

I bet this is a problem with all Meteor tool versions and supported Windows OS.

Regards,

Bradley

**Comment by michaeljota** [comment]
For path you have to surround the string into " " as "c:\path with spaces". I don't think this is something with Meteor, but Windows itself, as far I can tell.

**Comment by blongstreth** [comment]
I did use quotes and a few other things.  In order to verify an issue with Meteor, I drilled down until I stopped in cli/main.js.  I "think" I had to alter one of the nested batch files (had to quote or unquote the passed %*).  Once in cli/main.js, I verified the arguments made it into Node.js properly, including the file path with whitespace treated as a single argument.  Since I already altered on batch file (I thnk) and the fact it made it into Node.js world, I figured I would stop there because it goes lower.  At least I know it can be fixed by someone who knows the logic :-)

**Comment by blongstreth** [comment]
So, I managed to figure out the problem code in cli/main.js:

https://github.com/meteor/meteor/blob/release-1.5/tools/cli/main.js#L524-L532

In modified the snippet above by escaping the batPath and any command args with whitespace with double quotes and added the 'shell: true' option to the spawn command.  This is just something I hacked together but it shows that it can be fixed:
```
  if (process.platform === 'win32') {
    process.exit(new Promise(function (resolve) {
      
      // Double quote args with whitespace
      var hasWhitespaceRegEx = /\s/;
      for (var i = 0; i < newArgv.length; i++) {
        var arg = newArgv[i]
        if (hasWhitespaceRegEx.test(arg)) {
            // Check for existing outer double quotes
            newArgv[i] = '"' + arg + '"';
            newArgv[i].replace(/"*(.+)"*/, '"$1"');
        }
      }

      // Double quote command
      var batPath = '"' + files.convertToOSPath(executable + ".bat") + '"';

      var child = require("child_process").spawn(batPath, newArgv, {
        env: process.env,
        stdio: 'inherit',
        shell: true
      }).on('exit', resolve);
    }).await());
  } // Now exec; we're not coming back.
```

**Comment by abernix** [comment]
@blongstreth In addition to filing an issue, thanks for trying to come up with a solution.

As @michaeljota stated, you should almost certainly be putting quotes around any arguments (such as file paths) which have spaces in them.  Though I can see how you might be having a problem with the springboarding (the code at the lines you linked) if your username has a space in it (i.e. `C:\Users\Firstname Lastname`).

In this situation, the Node.js documentation [here](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) makes it seem as though only the command path itself should be quoted – not the arguments (which as I stated above, I believe you should be quoting yourself).

If we can find an answer here, perhaps submitting a pull request would be something you could help with?

**Comment by blongstreth** [comment]
Hello:

@abernix, I tried a few different scenarios to get it to work, including quoting just the command path.  I didn't spend time trying out every possible scenario for I was more interested in making sure things would work.  Also, I would like to avoid doing a pull request (at this time) because I am not familiar enough with the codebase.

What I find interesting is how complex things can get when dealing with command line arguments in Windows (beyond simple stuff).  Here is an interesting article if you are interested:

https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

My purpose for even working with Windows is that I am building a Meteor Gradle plugin and I have to support a few folks who use Windows for development.  I can always work around the issue by using file staging or advise not to use project paths with whitespace.  I rather not do either case long term.

Finally,

Thanks to both you @michaeljota and @abernix for the quick replies.  If I happen to get enough time to familiarize myself with the Meteor tool code, I would consider submitting a patch.  With that said, if anyone is willing to help, would be greatly appreciated.

**Comment by hwillson** [comment]
Hi all - Windows based springboarding issues caused by user home directories with spaces in their names have been cropping up in a few other issues (e.g. https://github.com/meteor/meteor/issues/8878, https://github.com/meteor/meteor/issues/8740, likely others). Since this issue appears to have the most context around the issue, and since there has been some pull request discussion, I'll add the `pull-requests-encouraged` label. For now the focus should be on addressing the following (taken from https://github.com/meteor/meteor/issues/8840#issuecomment-311029386):

> Though I can see how you might be having a problem with the springboarding (the code at the lines you linked) if your username has a space in it (i.e. C:\Users\Firstname Lastname).

If anyone is running into issues caused by having a space in their user home directory name, and is interested in submitting a PR to address this, that would be awesome!

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in a while. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed. Thanks!
