### ISSUE TITLE
IE10: Uint8ClampedArray is undefined (modules.js)

### ISSUE THREAD

**Issue by Twisterking** [meteor/meteor#8843]
Please see [HERE](https://forums.meteor.com/t/ie-10-bug-uint8clampedarray-is-undefined/37493).
This seems to be ecmascript/babel related, but I am completely lost on this!

**Comment by abernix** [comment]
Let's discuss on the forums (in only one spot at a time) until you have a reproduction, per the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).
