### ISSUE TITLE
CSS changes are hot-updated even if migration has been cancelled (appcache)

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8850]
We're using Meteor@1.5 with the `appcache` package.

We show a "update now" / "later" popup when a new version is available. We always return `false` from the `Reload._onMigrate` callback to prevent the reload from happening uncontrollably.

However, the new CSS files are applied regardless of this. Which means the app can look broken until user reloads. Is there any way to prevent CSS from being applied automatically?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=CSS%20changes%20are%20hot-updated%20even%20if%20migration%20has%20been%20cancelled%20(appcache)&body=Migrated%20from:%20meteor/meteor%238850) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
