### ISSUE TITLE
No icon in siri app sugestion

### ISSUE THREAD

**Issue by jstephancc** [meteor/meteor#8854]
Hello,

I'm using Meteor 1.4.4.3 and i want to see icon of my App on Apple device.

I configure mobile-config.js like in documentation.
https://docs.meteor.com/api/mobile-config.html#App-icons

It works, but one icon is missing: In section Siri App Suggestions.

How can i specify this icon? Probably it will be something like icons for spotlight, but different name and size.

I tested it on my iPad with iOS 10.3.2.
![siri](https://user-images.githubusercontent.com/22092109/27633370-2c33b93e-5bff-11e7-8029-39423c89e21c.png)

**Comment by hwillson** [comment]
Hi @jstephancc - the docs appear to be a bit out of date. There is also an `ios_spotlight_3x` option for `120x120`. That might be the one you're interested in.

**Comment by jstephancc** [comment]
Thanks @hwillson for the response.

Also when i open images assets in XCode (8.3.3) some of the icons are missing:

![zrzut ekranu 2017-06-29 o 08 10 40](https://user-images.githubusercontent.com/22092109/27674155-af91889c-5ca4-11e7-9e09-3eadd97e5ea3.png)

**Comment by jstephancc** [comment]
I configure `ios_spotlight_3x` but in Siri suggestion i have still default meteor icon.

**Comment by jstephancc** [comment]
I tested it again on clean project with Meteor 1.5.

I have the log during running the project:
`WARNING: ios_spotlight_3x: unknown key in App.icons configuration. The key may be deprecated.
`

But it works.

On `METEOR@1.4.4.3` it doesn't work.

**Comment by abernix** [comment]
It's not deprecated, in fact, it's just _too_ new. It will work just fine (and that message is _really_ just a `WARNING`).  It's been officially added as an option in Meteor 1.5.1 (thanks to https://github.com/meteor/meteor/commit/fc426146ddcb232982d42f9df350403168acc2ed) and this will resolve the warning in the future.  Meteor 1.5.1 has not been officially released but is still in testing.  You can try in the latest release-candidate by updating to it:

    meteor update --release 1.5.1-rc.1

See #8788 for more information on Meteor 1.5.1 and please report back if it doesn't fix your problem!

Thank you for reporting this! :smile:
