### ISSUE TITLE
Cannot build on 1.5

### ISSUE THREAD

**Issue by erperejildo** [meteor/meteor#8860]
I have followed the instructions posted here: https://guide.meteor.com/1.5-migration.html
Pretty straightforward for me because I was using 1.4.2.6 so no problem at all apart from the build, which is not working on this version.

I was using 1.4.2.6 and everything was working well so I decided to update to 1.4.2.7, tested again and working (I don't think it supposed to be many changes anyway).

So after this I updated finally to 1.5 and again all worked. I also updated all my dependencies. Only when I was going to update my app version on the Android Market I just figured out that I couldn't build it. This is the command that I normally use:

`meteor build ../output-build --server http://recipic.co --mobile-settings ./imports/settings.json` It starts to do everything but at some points it stops with no reason. Can't see any output.

It happens on Windows and Mac

Running the previous command with --verbose I see that it always stops after this line:
`Local package version is up-to-date: webapp-hashing@1.0.9`
BUT it starts to do something else after that and stops automatically with no errors as I said.

I tried also with 1.5rc1 but same.

I asked for help on Meteor forums and Stackoverflow but with no luck

**Comment by abernix** [comment]
To avoid confusion, I'd like to point out that the link you provided is for the migration **to** Meteor 1.4, not to Meteor 1.5.  The 1.5 migration is https://guide.meteor.com/1.5-migration.html.

With that said though, there isn't really anything in the migration to 1.5 that should affect your ability to run a `meteor build`.  Is there any way you can try to narrow this down to something more basic that you can share with us?  You'd need to remove things from your project until the problem goes away.

Before you do that though, you should start with a brand new Meteor project (`meteor create new-project`), add Android as a platform (`meteor add-platform android`) and see if you're able to `meteor build ...` that brand new application.  That will help determine if it's a problem with Meteor, your computer, or the application.

**Comment by erperejildo** [comment]
Link fixed.

The first thing I tried was just remove and add the Android platform (I thought I did that) and I got this:
`meteor remove-platform android`

> While removing platforms:
> error: android: platform is not in this project

`meteor add-platform android`

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'is-property'


Apart from this (which I'm going to investigate) I created another project and I tried to add the platform. I got the same issue

**Comment by abernix** [comment]
Did you try my suggestion in https://github.com/meteor/meteor/issues/7358#issuecomment-231144281 which is known to work?

**Comment by erperejildo** [comment]
I installed the package on the project and globally but I can't access to that path. I have not `is-my-json-valid`

**Comment by erperejildo** [comment]
Ok, what I have done is install this: `npm install -g is-my-json-valid` and follow again your steps.
Now I could add the platform and also the build works perfectly!  :+1:
