### ISSUE TITLE
METEOR_CORDOVA_COMPAT_VERSION_* do not work when set as environement vars on the server

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#8863]
I expected that I could deploy a new server version that was bundled with new cordova plugin versions and just set METEOR_CORDOVA_COMPAT_VERSION_IOS/ANDROID to the old value so that the mobile apps still receive the new server version, but that seems not be the case.

From the guide and from the issue here its unclear whether the server or the mobile apps have to be build with these properties or if the server just can be started with these env-vars.

**Comment by wojtkowiak** [comment]
Hey,

> but that seems not be the case.

what happened? Did you get the information about HCP being incompatible? Have you verified the `__cordova/manifest.json` `cordovaCompatibilityVersion` before and after building with setting the env vars?

**Comment by macrozone** [comment]
hi @wojtkowiak yes, i checked ___cordova/manifest.json and it shows not the variables i have set:

on my server i have the following env-vars:

```
# ....
export ROOT_URL='https://www.domain.com'
METEOR_CORDOVA_COMPAT_VERSION_ANDROID='9238ab3c1f94a7bff1627f29b1f4e2d77a0b8001'
export METEOR_CORDOVA_COMPAT_VERSION_IOS='48b5a71671249cfc60f63c6514f9f29399bd34f4'
```

but my __cordova/manifest.json shows:

```
"cordovaCompatibilityVersions":{"android":"819bb2cd912eb67a200be980b2b0d17e89501230","ios":"72d02c268e9fea1fd7aea556bf54f93e4f318579"},
```

**Comment by wojtkowiak** [comment]
What Meteor version are you using?

**Comment by macrozone** [comment]
@wojtkowiak sorry, 1.5

**Comment by macrozone** [comment]
ok it's clear from the code that it can't be set by environement variables on runtime, because its hard-coded into `programs/web.cordova/program.json`. So i edited this file and changed the values so that my apps still receive the update.

These values have to be present on `meteor build`
I can't really understand why it is implemented this way, maybe there is a reason, but i have now to adjust the build scripts, because i don't specify env-vars on build-time yet, because there was never a need to do so...

**Comment by wojtkowiak** [comment]
> ok it's clear from the code that it can't be set by environement variables on runtime

Yeah, they need to be set while building your app. But maybe this is something to consider for those to be overridable during runtime.

I have updated the guide with a note to make that clear:
https://github.com/meteor/guide/pull/647/files

**Comment by macrozone** [comment]
@wojtkowiak ok thanks for clarifying. I will now split my environement-config into runtime and buildtime.

**Comment by realyze** [comment]
@wojtkowiak Kudos for updating the guide! If I may suggest, it would be good to *explicitly* mention that you need to set the env vars *when building the mobile apps*. Maybe it's just me but I got confused by the wording just yesterday - I had exactly the same problem as @macrozone .
