### ISSUE TITLE
not renew cordova-build and hot reload not wroking

### ISSUE THREAD

**Issue by Denly** [meteor/meteor#8869]
I tried to run 
```ROOT_URL=<the deployed website url> meteor run android-device --mobile-server <the deployed website url> --settings settings.json```

The app does opened in my mobile but it just shows the old version. I tried delete ```.meteor/local/cordova-build``` but it still shows the old version. However after about 30 sec it jumped to the current version. it may be the cache in meteor or cordova load the app from the remote website?

**Comment by hwillson** [comment]
Sorry to hear you're having trouble! There isn't much here to go on, that will help with troubleshooting. Any chance you could supply a reproduction that demonstrates this issue? See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info. Thanks!

**Comment by hwillson** [comment]
We heaven't heard back regarding the additional information requested in https://github.com/meteor/meteor/issues/8869#issuecomment-329165645, so closing for now. Thanks!
