### ISSUE TITLE
[1.5.1-rc.3] $setOnInsert not allowed in allow-deny package ALLOWED_UPDATE_OPERATIONS

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#8873]
According to the comment for `ALLOWED_UPDATE_OPERATIONS` I believe the intent is to keep up to date with Mongo with regards to allowing all simple updates and not those that `does more than just modify its target`.

https://github.com/meteor/meteor/blob/master/packages/allow-deny/allow-deny.js#L354

It raises the exception:

`update failed: Access denied. Operator $setOnInsert not allowed in a restricted collection.`

I'm not sure why it was not supported before, perhaps because it was not supported in MiniMongo until 1.3.x?

But $setOnInsert has been part of Mongo since 2.4

It's causing a bug with simpl-schema npm: https://github.com/aldeed/node-simple-schema/issues/146

**Comment by hexsprite** [comment]
OK I'm pretty sure I'm wrong about my assumption. It seems like $setOnInsert does indeed potentially modify fields other than the target and that's what this is supposed to prevent against.

**Comment by DerekTBrown** [comment]
@hexsprite how so? I can't find any documentation of this.

**Comment by hexsprite** [comment]
OK, on re-reading the original comment and the Mongo docs I stand by the original issue report. `$setOnInsert` is basically the exact same as `$set` except that it only does something if a new document was inserted. So it should be allowed. :)

**Comment by hwillson** [comment]
Due to recent [`allow-deny` security issues](https://blog.meteor.com/meteor-allow-deny-vulnerability-disclosure-baf398f47b25), it has been decided that we will no longer accept any new changes to the `allow-deny` package, and will push towards deprecating it completely. Closing here - thanks!
