### ISSUE TITLE
MongoError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#8875]
I have around **42000 users** in my database. 
I have made a subscription of showing these users and their information for admin.
I show **20 records/users** per page.

When I visit page number **1964**, I get this exception in server console:

**Exception from sub allUsers id SzTYWKd8mK77ybWw2 MongoError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit**.

Here is the code for a subscription:

```
Meteor.publishComposite('allUsers', function(options, queryParams) {

  try{

    if(serverHelperClass.isAdmin(this.userId)){ 
    
      return {
        
        find: function() {
            
            return Meteor.users.find(
              {}, 
              { 
                fields: {_id: 1, createdAt: 1, emails: 1, lastUpdated: 1, 'profile.firstName': 1, 'profile.lastName': 1 },
                limit: 20, skip: 39260, sort: { 'lastUpdated.timeStamp': -1 } 
            });
        }
      };
    }
    return {find:function(){return Meteor.users.find({_id:''});}}; 
  }
  catch (e) {serverHelperClass.throwLog('subscription: allUsersPaginated: '+e.stack, e);}
});
```

Also I feel like this is happening because of the sorting. Do I need to create some index for sorting?

**Comment by abernix** [comment]
> MongoError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

I suppose there is a third option here, which is raise the maximum RAM configuration for Mongo, but the error message here couldn't be much more clear, including the part about it being a `MongoError`.  I'd suggest searching Google or StackOverflow for any part of this error and you'll find the answer.
