### ISSUE TITLE
Meteor Update 1.5 (Opbeat problem) TypeError: Cannot assign to read only property ‘then’ of #<Promise>

### ISSUE THREAD

**Issue by OlandiGitHub** [meteor/meteor#8882]
Hello

I have a problem after update Meteor to the last version 1.5, the problem is with app Opbeat, when set configuration startup

The problem is : TypeError: Cannot assign to read only property 'then' of #

Te line is the next
opbeat = require('opbeat').start({
appId: 'APPID',
organizationId: 'OrganizationID',
secretToken: 'Secret'
})

I don't find what need to fix the problem

Before the update I haven't this problem.

The documentation is [opbeat NodeJS Agent API](https://opbeat.com/docs/articles/nodejs-agent-api/)

**Comment by hwillson** [comment]
Have you tried the `require('opbeat/start')` approach [listed in the docs](https://opbeat.com/docs/articles/nodejs-agent-api/#starting-the-agent)? From the docs:

> If you are using Babel, you need to use the opbeat/start approach.

Meteor uses Babel, so you'll likely have to use this approach, along with setting up a Opbeat config file (see item 2 of the [Configuring the agent](https://opbeat.com/docs/articles/nodejs-agent-api/#configuring-the-agent) section).

**Comment by OlandiGitHub** [comment]
I tried with babel using "require('opbeat/start')", but it doesn't works.
The TypeError disappear but I get another error "Missing organizationId, appId or secretToken".
I tried by adding the file opbeat.js with this : 

module.exports = {
  appId: '<app id>',
  organizationId: '<org id>',
  secretToken: '<token>',
}

This file is located in the folder of the running Server where I launch the opbeat with "require('opbeat/start')"
but again i get the same error.

I also tried to add this values in ENVIRONMENT with this:
process.env.OPBEAT_APP_ID
process.env.OPBEAT_ORGANIZATION_ID
process.env.OPBEAT_SECRET_TOKEN

but it doesn't work either.

**Comment by hwillson** [comment]
Sounds to me like the babel approach is working, but it just can't find your config file. Have you tried specifying a custom path for the config file using `OPBEAT_CONFIG_FILE`, to make sure your app can see the config file? It's hard to verify any of this without seeing code (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Regardless, this really doesn't sound like a Meteor bug - issues here are reserved for problems with the Meteor platform itself. For help with using or integrating with the Meteor platform, I'd suggest trying the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`).
