### ISSUE TITLE
detectMobileServerUrl should return the pathname

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#8883]
When running a regular web app, I can use ROOT_URL to set the absolute path of my app e.g., `http://localhost:3000/admin`. However, when running from cordova, this value is replaced by `http://localhost:3000` regardless of how I pass it in, including if passed in with `--mobile-server`, the culprit seems to be `detectMobileServerUrl`, which only returns the protocol, host and port. Adding pathname to this fixes the problem. Should I submit a PR with the change (it's minor)?

I would also expect that whatever parses the `--server` option will need similar modifications

**Comment by hwillson** [comment]
Yes, a pull request would be reviewed for this. Thanks!

Adding for reference: https://github.com/meteor/meteor/issues/5973#issuecomment-182814577

**Comment by hwillson** [comment]
There hasn't been any traction on this issue in quite some time. If anyone comes across this issue and is interested in working on it, please let us know (it is `pull-requests-encouraged`). Until then however, this issue will be closed. Thanks!
