### ISSUE TITLE
Spiderable.js exception on docker (using mup) even after installing ongoworks:spiderable

### ISSUE THREAD

**Issue by davinderkumar** [meteor/meteor#8884]
I'm getting the same issue with Meteor 1.5/mup-docker/Ubuntu 16 even after installing ongoworks:spiderable package. Error is being thrown by default spiderable package ( packages/spiderable.js). I have installed phantomjs on server as well but it is still there.
Do I need to disable the default package? How? I do not see it in list of installed packages ("meteor list").

> spiderable: phantomjs failed: null 
stderr: 
spiderable: phantomjs failed at http://www.myaddresspin.com/robots.txt: { [Error: Command failed: /usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<'END'
var url = "http://www.myaddresspin.com/robots.txt";// 'url' is assigned to in a statement before this.
var page = require('webpage').create();

>var isReady = function () {
  return page.evaluate(function () {
    if (typeof Meteor === 'undefined'
        || Meteor.status === undefined
        || !Meteor.status().connected) {
      return false;
    }
    if (typeof Package === 'undefined'
        || Package.spiderable === undefined
        || Package.spiderable.Spiderable === undefined) {
      return false;
    }
    return Package.spiderable.Spiderable.isReady();
  });
};

> var dumpPageContent = function () {
  var out = page.content;
  out = out.replace(/<script[^>]+>(.|\n|\r)*?<\/script\s*>/ig, '');
  out = out.replace('<meta name="fragment" content="!">', '');
  console.log(out);
};

> page.open(url, function(status) {
  if (status === 'fail')
    phantom.exit();
});

> setInterval(function() {
  if (isReady()) {
    dumpPageContent();
    phantom.exit();
  }
}, 100);
END

> Can't open '/dev/stdin'
]
  killed: false,
  code: 255,
  signal: null,
  cmd: '/usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<\'END\'\nvar url = "http://www.myaddresspin.com/robots.txt";// \'url\' is assigned to in a statement before this.\nvar page = require(\'webpage\').create();\n\nvar isReady = function () {\n  return page.evaluate(function () {\n    if (typeof Meteor === \'undefined\'\n        || Meteor.status === undefined\n        || !Meteor.status().connected) {\n      return false;\n    }\n    if (typeof Package === \'undefined\'\n        || Package.spiderable === undefined\n        || Package.spiderable.Spiderable === undefined) {\n      return false;\n    }\n    return Package.spiderable.Spiderable.isReady();\n  });\n};\n\nvar dumpPageContent = function () {\n  var out = page.content;\n  out = out.replace(/<script[^>]+>(.|\\n|\\r)*?<\\/script\\s*>/ig, \'\');\n  out = out.replace(\'<meta name="fragment" content="!">\', \'\');\n  console.log(out);\n};\n\npage.open(url, function(status) {\n  if (status === \'fail\')\n    phantom.exit();\n});\n\nsetInterval(function() {\n  if (isReady()) {\n    dumpPageContent();\n    phantom.exit();\n  }\n}, 100);\nEND\n' } 
stderr: Can't open '/dev/stdin'
 
> stdout: 
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor.js:1075:11)
    at [object Object]._.extend.get (packages/meteor.js:1087:12)
    at [object Object].RouteController.lookupOption (packages/iron_router.js:143:29)
    at new Controller.extend.constructor (packages/iron_router.js:103:21)
    at [object Object].ctor (packages/iron_core.js:144:17)
    at Function.Router.createController (packages/iron_router.js:810:18)
    at Function.Router.dispatch (packages/iron_router.js:1335:25)
    at Object.router (packages/iron_router.js:624:12)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
    at packages/spiderable.js:171:11

**Comment by hwillson** [comment]
@davinderkumar I'm a little un-clear on what the Meteor issue is that you're reporting. Are you attempting to use the [spiderable](https://atmospherejs.com/meteor/spiderable) package, and when you try to use this package this is the error you're seeing? Or are you seeing this error when trying to use [ongoworks:spiderable](https://atmospherejs.com/ongoworks/spiderable)?

**Comment by davinderkumar** [comment]
@hwillson I have installed the ongoworks:spiderable package but I'm still getting the above mentioned error from default spiderable package. I think it is meteor issue. Isn't it?
If there is any option to disable the default spiderable package then please let me know.

**Comment by hwillson** [comment]
The Meteor `spiderable` package is only used if you've added it to your project. If it's not listed in your `.meteor/packages` file, then it's not being used. Can you post your `.meteor/packages` file?

**Comment by davinderkumar** [comment]
Here is the packages file

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.18                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
session@1.1.7                 # Client-side reactive dictionary for your app
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.8.0              # Enable ECMAScript2015+ syntax in app code

iron:router
themeteorchef:jquery-validation
accounts-ui@1.1.9
accounts-password@1.3.6
dburles:google-maps
accounts-facebook@1.2.0
service-configuration@1.0.11
cfs:standard-packages
cfs:filesystem
standard-minifier-css@1.3.4
standard-minifier-js@2.1.0
accounts-twitter@1.3.0
ejson@1.0.13
steeve:jquery-qrcode
joshowens:shareit
altapp:recaptcha
sacha:spin
email@1.2.1
mdg:camera
http@1.2.12
chriswessels:slideout
shell-server@0.2.3
dispatch:deep-link
facebook-config-ui@1.0.0
google-config-ui@1.0.0
twitter-config-ui@1.0.0
richsilv:owl-carousel
check@1.2.5
raix:push
accounts-google@1.2.0
mirrorcell:background-geolocation-plus
mirrorcell:geolocation-plus
google-oauth@1.2.4
dynamic-import
reywood:publish-composite
reywood:iron-router-ga
ongoworks:spiderable

**Comment by hwillson** [comment]
It looks like [`joshowens:shareit`](https://atmospherejs.com/joshowens/shareit) has a dependency on `spiderable`, so it's pulling it into your project. You might want to find a replacement for `joshowens:shareit`, or fork it / modify it to not use `spiderable`.

The above being said, at this point this isn't a Meteor core issue. Thanks!

**Comment by davinderkumar** [comment]
Thanks

**Comment by Silverutm** [comment]
Having same issue he had
`meteor list`

`accounts-password            1.5.1  Password support for accounts
alanning:roles               1.2.16  Authorization package for Meteor
aldeed:tabular               2.1.1  Datatables for large or small datasets in Meteor
babrahams:editable-text      0.9.10  Editable text drop-in template helper
blaze-html-templates         1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
check                        1.3.1  Check whether a value matches a pattern
chrismbeckett:toastr         2.1.2_1  Gnome / Growl type non-blocking notifications
cleandersonlobo:sweetalert2  1.5.0  Meteor Package for sweetAlert2: a beautiful replacement for javascript' alert()
ecmascript                   0.11.1  Compiler plugin that supports ES2015+ in all .js files
email                        1.2.3  Send email messages
es5-shim                     4.8.0  Shims and polyfills to improve ECMAScript 5 support
ian:accounts-ui-bootstrap-3  1.2.89  Bootstrap-styled accounts-ui with multi-language support.
iron:router                  1.1.2  Routing specifically designed for Meteor
jquery                       1.11.11  Manipulate the DOM using CSS selectors
meteor-base                  1.4.0  Packages that every Meteor app needs
mizzao:user-status           0.6.7  User connection and idle state tracking for Meteor
mobile-experience            1.0.5  Packages for a great mobile user experience
momentjs:moment              2.22.2  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                        1.5.1  Adaptor for using MongoDB and Minimongo over DDP
ongoworks:spiderable         1.0.7  Docker + Port friendly Spiderable package
perak:codemirror             1.3.1  CodeMirror editor for Meteor >= 1.0
perak:markdown               1.0.5  GitHub flavored markdown parser for Meteor based on marked.js
reactive-var                 1.0.11  Reactive variable
sacha:spin                   2.3.1  Simple spinner package for Meteor
session                      1.1.8  Session variable
shell-server                 0.3.1  Server-side component of the `meteor shell` command.
standard-minifier-css        1.4.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js         2.3.4  Standard javascript minifiers used with Meteor apps by default.
stylus                       2.513.14  Expressive, dynamic, robust CSS
todda00:friendly-slugs       0.6.0  Generate URL friendly slugs from a field with auto-incrementation to ensure unique URLs.
tracker                      1.2.0  Dependency tracker to allow reactive callbacks
underscore                   1.0.10  Collection of small helpers: _.map, _.each, ...
`
