### ISSUE TITLE
meteor bug when using iOS plugins with uialertcontroller

### ISSUE THREAD

**Issue by jarvi5** [meteor/meteor#8891]
I create a fresh Meteor app and a Cordova plugin that shows and alertsheet when clicking a button, then I added the plugin to the meteor app. The app opens the plugin when click the default button that comes with the app. The issue happens when you are in landscape rotate the phone to portrait and then show the alert. It seems that a constraint is added. this is the Xcode console output.

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x17ea1c20 UIView:0x17d951e0.width == - 20   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17ea1c20 UIView:0x17d951e0.width == - 20   (active)>

Once it happens it keeps showing the alert incorrectly when you press the button to show it. if you rotate the phone it gets fixed until yo close the alert. I also test it in a fresh Cordova app and it doesn't happens so I guess Meteor is doing something.

![meteor-alert-controller-bug](https://user-images.githubusercontent.com/20981061/28018307-cf86fd2c-654a-11e7-807a-086eca355acf.gif)

**Comment by hwillson** [comment]
Thanks for reporting this issue. There isn't much here to go on unfortunately, that will help with troubleshooting. Any chance you could supply a reproduction? See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info. Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/meteor/meteor/issues/8891#issuecomment-329167486, so closing for now. Thanks!
