### ISSUE TITLE
Uncaught ReferenceError: pe is not defined @ deployment

### ISSUE THREAD

**Issue by sproleee** [meteor/meteor#8892]
After my latest deployment of my Meteor app, I'm getting this really strange error I've never seen before. Doesn't even register in Google. I'm using Meteor version 1.4.3.

[https://i.gyazo.com/116ee037463039986838de1e5297271d.png](url)

It's this particular function that's causing the issue:

```
function(ae, oe, se) {
                                var le, de;
                                !function(pe, ce) {
                                    "undefined" != typeof ae && ae.exports ? ae.exports = ce() : (le = ce,
                                    de = "function" == typeof le ? le.call(oe, se, oe, ae) : le,
                                    !(void 0 !== de && (ae.exports = de)))
                                }("bowser", function() {
                                    var ce = !0
                                      , ue = pe("undefined" == typeof navigator ? "" : navigator.userAgent);
                                    return ue.test = function(fe) {
                                        for (var me = 0, he; me < fe.length; ++me)
                                            if (he = fe[me],
                                            "string" == typeof he && he in ue)
                                                return !0;
                                        return !1
                                    }
                                    ,
                                    ue._detect = pe,
                                    ue
                                })
                            }
```

This only happens in production mode and I get no such errors in development mode. I'm completely lost here and would appreciate any help.

**Comment by hwillson** [comment]
Sounds like a minification problem. Any chance you could provide a small runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? One thing you could try is replacing the default `standard-minifier-js` package with `abernix:standard-minifier-js` (which uses `uglify-es` behind the scenes). So:

```
meteor remove standard-minifier-js
meteor add abernix:standard-minifier-js
```

**Comment by sproleee** [comment]
@hwillson Thanks for the response.

I'm getting this error when trying to deploy:

```
Building App Bundle Locally
Errors prevented bundling:
While building the application:
error: abernix:standard-minifier-js, standard-minifier-js: multiple
packages registered minifiers for extension "js".

```
Doesn't really make sense since I definitely removed standard-minifier-js completely.

**Comment by sproleee** [comment]
@hwillson Your suggestion ended up solving my problem. Turns out I had another minifier installed and it was indeed a minification problem that was causing my app to crash.

Thanks a ton.

**Comment by hwillson** [comment]
Great to hear @sproleee! Meteor will eventually (well, most likely) be moving to `uglify-es`by default (see https://github.com/meteor/meteor/pull/8698), but if it's working for you then `abernix:standard-minifier-js` is your best bet. Closing - thanks!
