### ISSUE TITLE
Cordova , Google login give error 10 after update meteor 1.5

### ISSUE THREAD

**Issue by aayushsinghm16** [meteor/meteor#8895]
Please provide me with some solution , how to fix google login issue for android and ios.

**Comment by aayushsinghm16** [comment]
updated to meteor 1.5 , but logginWithGoogle return error 
`Meteor.loginWithGoogle({
      requestPermissions: ['https://www.googleapis.com/auth/contacts.readonly','email'],
      requestOfflineToken: {
        google: true
      }
    }, function (err) {
    if (err){
      console.log(err);
      Session.set('errorMessage', err.reason || 'Unknown error');
    }else{
      Session.set("loggin", true);
    }

    });`
 log result 10

**Comment by paulincai** [comment]
Hi,

you mentioned Cordova in the title. Are you using anything like this: https://github.com/EddyVerbruggen/cordova-plugin-googleplus ?

I guess there might be some relation with this: https://github.com/meteor/meteor/issues/8253

Paul

**Comment by aayushsinghm16** [comment]
thanks for response , i just updated meteor.(because google blocking OAuth requests using web-views )
I think meteor 1.5 using cordova-plugin-googleplus
For using new google sign in for android or ios , what steps should i follow , for previous sign in process , we need webClient clientid and secret , 
`ServiceConfiguration.configurations.insert({
    service: "google",
    clientId: "xxxx",
    secret: "xxxx"
  });`
Now what should i do , and how to add my android client id , 
Please help me out , our product depends upon google sign for all 3 platforms web , android and ios 
without it we cant do any thing

**Comment by aayushsinghm16** [comment]
I figured out what was the problem , just followed these step given in
https://github.com/sujith3g/meteor-g-plus
