### ISSUE TITLE
test-packages with --test-app-path does not work anymore

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8897]
It seems `--test-app-path` does not work anymore. I am trying to run in my Meteor 1.5 app:

```
meteor test-packages --show-test-app-path --test-app-path /tmp/meteor-test-packages <package name>
```

And I get the following error:

```
Error: ENOENT: no such file or directory, open '/tmp/meteor-test-packages/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at wrapper (/tools/fs/files.js:1586:35)
    at Object.install (/tools/cli/default-npm-deps.js:20:5)
    at doTestCommand (/tools/cli/commands.js:1599:38)
    at Command.func (/tools/cli/commands.js:1546:10)
    at /tools/cli/main.js:1483:23
```

**Comment by hwillson** [comment]
Looking at the code, as long as you've created the directory ahead of time, your command should work. I don't see any code in place to create this directory if it doesn't exist, or throw an error when it doesn't, so this should be addressed.

**Comment by mitar** [comment]
Oh, maybe I created a dir in the past and I didn't now. I assumed that it will be created automatically.

**Comment by hwillson** [comment]
Yes, it should be handled a bit better - I'll patch things to create the directory first, if it doesn't exist.

**Comment by hwillson** [comment]
PR #8923 was merged, so closing here. Thanks!
