### ISSUE TITLE
bugs when dismissing a plugin view

### ISSUE THREAD

**Issue by jarvi5** [meteor/meteor#8898]
When you dismiss a plugin view if it is in portrait it overlaps the status bar and if its in landscape it show blank screen. Both go normal when you rotate the screen.
![meteor-bugs-when-dismissing-native-views](https://user-images.githubusercontent.com/20981061/28121324-b209318a-66e8-11e7-8a8a-ea57bed92c08.gif)

**Comment by hwillson** [comment]
Hi @jarvi5 - there have been a handful of Cordova updates since this issue was reported. Can you please test things out using Meteor 1.6.0.1, and post back if this issue is still happening? thanks!
