### ISSUE TITLE
[1.6-beta.6] NODE_OPTIONS='--inspect' brakes meteor

### ISSUE THREAD

**Issue by rayfoss** [meteor/meteor#8901]
I'm running meteor 1.6-beta.6

when I use `export NODE_OPTIONS='--inspect'` on MacOS Sierra
it seems to run multiple node instances and fail as inspect tries to use the same port
```
amama@fossmac ~/git/learn$ meteor
Debugger listening on ws://127.0.0.1:9229/38a6d8b0-7ae1-4fdd-ae79-76f08cb45cf9
For help see https://nodejs.org/en/docs/inspector
[[[[[ ~/git/learn ]]]]]

=> Started proxy.
=> Started MongoDB.
W20170712-15:02:09.015(-5)? (STDERR) Starting inspector on 127.0.0.1:9229 failed: address already in use
=> Exited with code: 12
W20170712-15:02:09.555(-5)? (STDERR) Starting inspector on 127.0.0.1:9229 failed: address already in use
=> Exited with code: 12
W20170712-15:02:10.050(-5)? (STDERR) Starting inspector on 127.0.0.1:9229 failed: address already in use
=> Exited with code: 12
=> Your application is crashing. Waiting for file change.
```

This used to work on rc6 if I recall correctly. Is there any way to pass a node option only to the webserver node process?

**Comment by benjamn** [comment]
I think you want either `TOOL_NODE_FLAGS=--inspect` (to debug the build tool) or just `meteor debug` (to debug the application process).

That said, you might simply still have a process listening on port 9229. You can list the processes listening on that port with `lsof -i :9229` (and then use `kill <pid>` as necessary).

**Comment by rayfoss** [comment]
```
export TOOL_NODE_FLAGS=" --inspect"
amama@fossmac ~/git/third_party/meteor-fullboat$ meteor --version
/Users/amama/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node: bad option: --inspect
amama@fossmac ~/git/third_party/meteor-fullboat$ export TOOL_NODE_FLAGS=""
amama@fossmac ~/git/third_party/meteor-fullboat$ meteor --version
Meteor 1.6-beta.6
```
At this point i'll just use the meteor shell and the bakery's devtools, it works so well at home.. may get back to this.

**Comment by benjamn** [comment]
Oh, interesting, somehow it looks like you were using Meteor 1.5 that time (judging from the `/Users/amama/.meteor/packages/meteor-tool/.1.5.0.edxpxb...` part). If that wasn't your intention, you can run meteor with `~/.meteor/meteor`, and if that works you should check `which meteor` to figure out why it gave you the wrong version.

Just to be clear, `--inspect` and `--inspect-brk` only work in Node 7+. In earlier versions of Node, the flags were called `--debug` and `--debug-brk`.
