### ISSUE TITLE
NOT AN ISSUE. Information from Heroku on Node.js vulnerabilities

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#8903]
Meteor 1.5.1 runs on 4.8.4 so no worries. However, please see the communicate from Heroku.

You are receiving this email because you run at least one Node.js application on Heroku.

The Node.js team has announced that a high severity remote Denial of Service (DoS) Constant Hashtable Seeds vulnerability in Node.js versions 4.x through 8.x has been patched in the following versions:

4.8.4

6.11.1

7.10.1

8.1.4

**Detecting if you're vulnerable from the Heroku CLI**

`$ heroku run node -v -a APPNAME`

If your version is less than what's listed above, you will need to upgrade.

The rest of the communicate is not relevant. It only refers to Heroku procedures.

Tx,
Paul

**Comment by joshuacrowley** [comment]
If you're having issues(https://github.com/meteor/meteor/issues/8902) upgrading to 1.5.1  via `meteor update` try `meteor update --release 1.5.1`

**Comment by abernix** [comment]
Meteor 1.5.1 is out though we haven't officially marked it as "recommended" yet, even though it is considered stable.  We will do this tomorrow morning after the final steps in the release process (bootstrapping, etc.) have completed.

For now, please update Meteor using the command that @joshuacrowley helpfully provided above.
