### ISSUE TITLE
Meteor 1.5 needs Node 4.8.4+

### ISSUE THREAD

**Issue by alanwunsche** [meteor/meteor#8904]
Received from HerokuApp, the need to upgrade to Node 4.8.4 +
Our Meteor 1.5 build includes Node 4.8.3; therefore it appears to be a Meteor 1.5 issue?

---------------------------------------
You are receiving this email because you run at least one Node.js application on Heroku.

The Node.js team has announced that a high severity remote Denial of Service (DoS) Constant Hashtable Seeds vulnerability in Node.js versions 4.x through 8.x has been patched in the following versions:

4.8.4
6.11.1
7.10.1
8.1.4
------------------------------

**Comment by joshuacrowley** [comment]
See https://github.com/meteor/meteor/issues/8903
