### ISSUE TITLE
Update 1.5 (Packages problem)

### ISSUE THREAD

**Issue by OlandiGitHub** [meteor/meteor#8907]
Hello

I have a problem when Update to 1.5 

First I have this message after update 
----------------------------------------------------------------------------------------------------------------------------

The following top-level dependencies were not updated to the very latest version available:
 * accounts-password 1.3.7 (1.4.0 is available)
 * mongo 1.1.18 (1.1.19 is available)         
                                              
Newer versions of the following indirect dependencies are available:
 * accounts-base 1.3.0 (1.3.1 is available)   
 * allow-deny 1.0.5 (1.0.6 is available)      
 * ddp 1.2.5 (1.3.0 is available)             
 * ddp-client 1.3.4 (2.0.0 is available)      
 * ddp-server 1.3.14 (2.0.0 is available)     
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.

but if I do "meteor update --all-packages" I get the same message.
If I do "meteor update accounts-base" for example I get 

The specified packages are at their latest compatible versions.

but  never updates this package.

Second problem, I get this error after do "meteor run"
----------------------------------------------------------------------------------------------------------------------------
/home/olandi/.meteor/packages/meteor-tool/.1.5.0.1idt24p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'get' of undefined
at withoutInvocation (packages/meteor.js:443:33)
at bindAndCatch (packages/meteor.js:452:33)
at Object._.extend.defer (packages/meteor.js:514:26)
at [object Object].MongoConnection.tail (packages/mongo/mongo_driver.js:1170:10)
at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:239:50)
at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
at new MongoConnection (packages/mongo/mongo_driver.js:214:25)
at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)

Someone have this problem ?

**Comment by benjamn** [comment]
Try running `meteor update --release 1.5.1` instead of just `meteor update`?

**Comment by StorytellerCZ** [comment]
`meteor update --release 1.5.1` should fix the first issue, for the second one as well with luck, but it still persist with some packages.

**Comment by OlandiGitHub** [comment]
This works great!! 

Thanks
