### ISSUE TITLE
ddp-common error

### ISSUE THREAD

**Issue by formspoint** [meteor/meteor#8908]
I'm on MacOS and Meteor 1.5. 

I have a few project built with Meteor 1.5, but wanted to do a quick demo so I started a green-field project today:

$ meteor create test-project
$ cd /test-project
$ meteor remove autopublish
$ meteor remove insecure
$ metoer npm install --save
$ MONGO_URL=mongodb://localhost:27017/meteor meteor --port 3101

The project starts up, but then I notice errors in the bash console (server) and errors in the browser console (client)

Server errors:
![image](https://user-images.githubusercontent.com/19209125/28187107-239168b8-67e3-11e7-9827-7ab02c6bfd9d.png)

Client errors:

![image](https://user-images.githubusercontent.com/19209125/28187058-f542b084-67e2-11e7-95c5-740de4667bdc.png)

**Comment by formspoint** [comment]
Doing ```meteor update --release 1.5.1``` seems to fix the issue.

**Comment by copleykj** [comment]
#8902

**Comment by mitar** [comment]
Closing in favor of #8902.
