### ISSUE TITLE
login resume tokens never seem to be removed

### ISSUE THREAD

**Issue by kenyee** [meteor/meteor#891]
When signing out, the resume token associated w/ the session should be cleared.
If I look at my db.users collection, some of my test users look like this:

"resume" : { "loginTokens" : [      {       "token" : "DPe8WhMi4dmfwn6DB",  "when" : 1362085063102 },       {        "token" : "apv3RxZ6TNCJoteQX",  "when" : 1363641759164 },       {       "token" : "n3KHssEfm9ZBuEcKg",   "when" : 1363656649366 },       {       "token" : "JwFPku5oPzGWwRksT",   "when" : 1363723115131 },       {       "token" : "3T3Bmqwx355sHbu2D",  "when" : 1363905637608 },        {       "token" : "bXuBF2merTks6DS87",  "when" : 1363907586709 },        {       "token" : "7X3yAehpyNoJZrwMY",  "when" : 1363920449916 },       {       "token" : "6Xg9FcQNrcaLqwdrQ",   "when" : 1363965106618 },       {       "token" : "CEc9b2mXAGAtbgTQG",   "when" : 1363995260314 },       {       "token" : "ayEwFdc9ZcZex3EfD",  "when" : 1364224224856 },        {       "token" : "dFEGiGaRpDrm6Kcdo",  "when" : 1364225647107 },        {       "token" : "t3nazJcbf5n8n36BM",  "when" : 1364226912564 },       {        "token" : "ZaZRn46Y8mdHZMwqg",  "when" : 1364234353422 },       {       "

/accounts-base/accounts_server.js seems to just push new login tokens...it never seems to do pulls to get rid of them.

**Comment by dcsan** [comment]
> unless you disable token expiration

can someone inform me how to do that? I have an app where users get logged out after 24 hours it seems, but we want indefinite tokens.
http://stackoverflow.com/questions/29975790/how-to-extend-lifetime-of-a-meteor-login-token

**Comment by lorensr** [comment]
@dcsan 

http://docs.meteor.com/#/full/accounts_config

loginExpirationInDays Number
The number of days from when a user logs in until their token expires and they are logged out. Defaults to 90. Set to null to disable login expiration.

**Comment by crapthings** [comment]
so will meteor clean login token automatically ?

1. login user1 will generate a login token in user's services.resume.loginTokens
2. login user2 without logout user1 the token is still in user1

will meteor destroy that token?

**Comment by lorensr** [comment]
@crapthings It will clean the login token automatically if it is past the expiration

**Comment by vfonic** [comment]
@lorensr is the "past expiration" defined as a `"when"` value? I have ton of tokens for my users and they don't seem to get cleaned. I'm using the latest stable meteor release (1.6.0.1 I believe).

Here's how it looks for me in the db (removed `hashedToken`):
```js
[{ "when": "2017-10-31T00:48:22.789Z" }, { "when": "2017-10-31T12:04:50.689Z" }, { "when": "2017-10-31T12:24:05.303Z" }, { "when": "2017-10-31T13:40:55.793Z" }, { "when": "2017-10-31T19:32:29.991Z" }, { "when": "2017-11-01T00:39:31.202Z" }, { "when": "2017-11-01T15:08:20.198Z" }, { "when": "2017-11-01T23:43:28.991Z" }, { "when": "2017-11-02T14:56:57.206Z" }, { "when": "2017-11-06T14:19:30.067Z" }, { "when": "2017-11-06T14:52:37.415Z" }, { "when": "2017-11-06T22:03:54.255Z" }, { "when": "2017-11-06T23:46:55.560Z" }, { "when": "2017-11-07T21:25:37.878Z" }, { "when": "2017-11-14T14:23:41.330Z" }, { "when": "2017-11-20T15:57:44.485Z", }]
```

**Comment by menelike** [comment]
Reading the code https://github.com/meteor/meteor/blob/af26e8b052a5135033e561cf4e4347eee585ab3b/packages/accounts-base/accounts_server.js#L1430-L1436 and in particular, https://github.com/meteor/meteor/blob/af26e8b052a5135033e561cf4e4347eee585ab3b/packages/accounts-base/accounts_server.js#L1003-L1035 should be responsible for cleaning up tokens, but it seems the tokens are never removed (`METEOR@1.7.0.3`).
