### ISSUE TITLE
Updating to 1.5.1 causes babel-runtime package error

### ISSUE THREAD

**Issue by asad-nga** [meteor/meteor#8912]
I have updated my meteor version to 1.5.1 due to Heroku vulnerabilities warning.
But now **Error**: The babel-runtime npm package could not be found in your node_modules 
is popping up.

I have tried solution from [babel-issue](https://github.com/meteor/meteor/issues/8032#issuecomment-259431609) as asked by @benjamn but after installing **babel-runtime**  the layout in my model which was earlier working perfectly now shows: **Debug Message: The layout you used here is not properly configured. Check your console for more information.**

**Comment by benjamn** [comment]
It sounds like you fixed the `babel-runtime` problem, and now you have a new, different problem to investigate. Without knowing anything about the layout library you're using, I can only recommend that you should dig into the information in your browser console, and try to understand what needs to be configured, just like the message says. Good luck!

**Comment by fernandoheb** [comment]
I'm facing the same ... in my local version it runs smoothly but i'm trying to host at heroku and when I try to run the app it stops with just the background loaded and with the error:
![image](https://user-images.githubusercontent.com/10677459/28747056-f6084574-746c-11e7-83d2-ea38bbc141fb.png)

**Comment by abernix** [comment]
@fernandoheb Do you have `babel-runtime` in the `dependencies` section of your project's `package.json`?

**Comment by fernandoheb** [comment]
I do have: 
![image](https://user-images.githubusercontent.com/10677459/28796616-9ac37784-7614-11e7-9c8e-69537c13f409.png)
I had it reinstalled just in case, and pushed it again.... same error... I think it has something with the: 
npm install --save babel-runtime

I looked in my configurations in my local version (that is ok) and I run this line after update meteor when I create my VM using a vagrant script.

I think it is not initialized when i send the code to heroku, , or something like this....

Actually I'm very new in this kind of thing so I'm kinda lost in how should i try it =(

I found this documentation https://babeljs.io/docs/plugins/transform-runtime/ but I don't find the .babelrc and don't get how use the other ways....

**Comment by chrischen-melb** [comment]
I put `yarn.lock` in `.slugignore` file to force heroku to use npm instead of yarn, and solved this issue.
