### ISSUE TITLE
prodOnly flag for Meteor packages not recognized in Meteor 1.5.1

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#8918]
After I updated my mobile app from Meteor 1.2 to 1.5.1, the app could not connect to the local development server anymore. It tried to connect to the server via SSL.

I tracked this down to the `force-ssl` package that I included to force my production server to switch into SSL mode. This package had been included in a custom Meteor package that set the `prodOnly` flag like this:

```
Package.describe({
  name: 'my:package',
  summary: 'SSL support',
  prodOnly: true
});

Package.onUse(function(api) {
  api.use('force-ssl');
});
````

In Meteor 1.2, this worked fine and only affected my production builds. But in Meteor 1.5, it also effects my development build. After I removed this package, the app could connect to the dev server again. So it seems as if the `prodOnly` flag isn't supported in 1.5.1 anymore.

**Comment by benjamn** [comment]
What about 1.5? Or, more generally, can you say which version of Meteor seems to have regressed this functionality?

**Comment by derwaldgeist** [comment]
TBH, I don't know. I upgraded from 1.2 to 1.3, but had a lot of problems getting my mobile apps running on this version. So I upgraded to 1.5 in the hope this would help.

**Comment by derwaldgeist** [comment]
Just checked 1.5. The problem exists there, too.

**Comment by derwaldgeist** [comment]
Yeah, that's doable.

**Comment by derwaldgeist** [comment]
Here's the reproduction repo:
https://github.com/derwaldgeist/repro-production-flag

**Comment by derwaldgeist** [comment]
I just found out that the error only appears if you call
`meteor run android-device` immediately after `meteor reset`.

If you call it twice, the app is able to call the Meteor method.

**Comment by derwaldgeist** [comment]
Any news on this? In the meantime, I noticed that this also affects iOS devices. In effect, I have to disable force-ssl any time I want to test my app locally, i.e. with my local dev server.

**Comment by hwillson** [comment]
Hi @derwaldgeist - while triaging issues I just noticed that this issue is a side effect of issue https://github.com/meteor/meteor/issues/8096. Fixing https://github.com/meteor/meteor/issues/8096 will fix this issue. Since it has more history, I'll close this issue (please join in the discussion over in https://github.com/meteor/meteor/issues/8096 - or better yet - help us work on a fix! 🙂). Thanks!

**Comment by derwaldgeist** [comment]
Thanks for the info. The discussion going on in #8096 is indeed quite interesting wasn't aware of that, although I created one of the issues abernix mentions there. :-)
