### ISSUE TITLE
loginExpirationInDays problems

### ISSUE THREAD

**Issue by CalinaCristian** [meteor/meteor#8922]
I'm using loginExpirationInDays with 0.05 as the value (under 0.05 (1.12 hrs) I see it automatically logs you out on refresh for some reason), and I have an interval every 5 minute on the client which checks if the user has any activity and resets it using Accounts.makeClientLoggedIn, using localStorage.getItem('Meteor.loginToken') to get the token. If the user had activity, I reset it to 0.05 and if he doesn't I let 5 more minutes pass without resetting it. I've seen that it doesn't automatically log you out, it only does it on refresh when it expires, so on this interval I also check if it has expired to log the user out.

The problem is that sometimes it randomly logs him out on hot push reload or when some time passes and I can't figure out why (usually this happens randomly on refresh). I do this interval in a tracker.autorun depending on the userId (if he's logged out, I delete the listeners and clear the interval, and if he isn't, I start the interval).

**Comment by SimonSimCity** [comment]
@CalinaCristian I've done a lot of digging to this as well and added a feature-request that you are free to vote for.

In an additional comment on it, I described a lot about the internals of it and I guess you run into that: https://github.com/meteor/meteor-feature-requests/issues/119#issuecomment-309414922

For some reason, it kicks you out one hour before the time defined in `loginExpirationInDays`. I wasn't able to nail it down, but I saw a constant, set to an hour, that was used quite often in this context.

Maybe also the plugin, linked in the comment before (https://github.com/lindleycb/meteor-stale-session/) does exactly what you need, it didn't quite fit for my requirements.

**Comment by hwillson** [comment]
Since a potential solution to this issue is already being tracked as a FR (https://github.com/meteor/meteor-feature-requests/issues/119), let's close it here. Thanks!
