### ISSUE TITLE
[Meteor 1.5.1] Unable to run in iOS with Xcode 8.3.3

### ISSUE THREAD

**Issue by fullhdpixel** [meteor/meteor#8934]
I have the following error when I run _meteor run ios_

Error code 65 for command: xcodebuild with args:

Tried:
- Removing everything in .meteor/local
- Restarting xcode
- Adding meteor webpack (cordova-plugin-meteor-webapp@1.4.2)

> => Errors executing Cordova commands:         
>                                               
>    While running Cordova app for platform iOS with options --emulator:
>    Error: Command failed:                     
>    /.meteor/local/cordova-build/platforms/ios/cordova/run
>    --emulator
>    ** BUILD FAILED **
>    
>    
>    The following build commands failed:
>    CompileSwift normal x86_64
>    /.meteor/local/cordova-build/platforms/ios/AppName
>    Online/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
>    CompileSwift normal x86_64
>    /.meteor/local/cordova-build/platforms/ios/AppName
>    Online/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
>    CompileSwift normal x86_64
>    /.meteor/local/cordova-build/platforms/ios/AppName
>    Online/Plugins/cordova-plugin-meteor-webapp/AssetBundleManager.swift
>    CompileSwift normal x86_64
>    /.meteor/local/cordova-build/platforms/ios/AppName
>    Online/Plugins/cordova-plugin-meteor-webapp/AssetBundle.swift
>    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
>    (5 failures)
>    Error code 65 for command: xcodebuild with args:
>    -xcconfig,/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-workspace,AppName
>    Online.xcworkspace,-scheme,AppName
>    Online,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
>    Simulator,name=iPhone
>    5s,build,CONFIGURATION_BUILD_DIR=/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/.meteor/local/cordova-build/platforms/ios/build/sharedpch
>    at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
>    at emitTwo (events.js:87:13)
>    at ChildProcess.emit (events.js:172:7)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
>    => awaited here:
>    at Function.Promise.await
>    (.meteor/packages/templating-compiler/.1.3.2.x78jlu++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
>    at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
>    at CordovaProject.run$ (/tools/cordova/project.js:261:10)
>    at tryCatch
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
>    at GeneratorFunctionPrototype.invoke [as _invoke]
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
>    at tryCatch
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
>    at invoke
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
>    at
>    .meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
>    at callInvokeWithMethodAndArg
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
>    at AsyncIterator.enqueue
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
>    at AsyncIterator.prototype.(anonymous function) [as next]
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
>    at Object.runtime.async
>    (.meteor/packages/meteor-tool/.1.5.1.zeipre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
>    at
>    .meteor/packages/templating-compiler/.1.3.2.x78jlu++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
>                                               
> .meteor/packages/templating-compiler/.1.3.2.x78jlu++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
>       throw error;
>       ^
> undefined
>  => awaited here:
>     at Function.Promise.await (.meteor/packages/templating-compiler/.1.3.2.x78jlu++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
>     at /tools/cordova/runner.js:98:17
>     at /tools/utils/buildmessage.js:271:13
>     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at /tools/utils/buildmessage.js:264:29
>     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at /tools/utils/buildmessage.js:262:18
>     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at /tools/utils/buildmessage.js:253:23
>     at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at Object.capture (/tools/utils/buildmessage.js:252:19)
>     at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
>     at [object Object]._.extend._runOnce (/tools/runners/run-app.js:777:21)
>     at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
>     at /tools/runners/run-app.js:417:12

**Comment by fullhdpixel** [comment]
![image](https://user-images.githubusercontent.com/7371397/28501308-a55b5ff4-6fd9-11e7-9d58-937cca39fcd7.png)

So many compiler issues showing up.

**Comment by hwillson** [comment]
@fullhdpixel Was this working for you with Meteor 1.5 and `cordova-plugin-meteor-webapp` 1.4.1, or is this a new app using 1.5.1  + `cordova-plugin-meteor-webapp` 1.4.2?

**Comment by fullhdpixel** [comment]
Hi @hwillson, this is an upgraded app to 1.5.1 and includes 1.4.2 cordova-plugin-meteor-webapp. Maybe that is the problem?

I haven't tried working with IOS on 1.5

**Comment by abernix** [comment]
@fullhdpixel What version of both were you using prior to the upgrade?

**Comment by fullhdpixel** [comment]
just METEOR@1.5 previously, but I have not worked with IOS on that version. I can get an ios app working on 1.5, just not with my main app.

**Comment by abernix** [comment]
@fullhdpixel What if you explicitly add `cordova-plugin-meteor-webapp@1.4.1` (instead of `1.4.2`):

I believe this should do the trick:

    meteor add cordova:cordova-plugin-meteor-webapp@1.4.1

**Comment by fullhdpixel** [comment]
No progress, issue still persists.

This is my list of cordova plugins, if that matters

cordova-plugin-appavailability@0.4.2
cordova-plugin-console@1.0.7
cordova-plugin-device@1.1.6
cordova-plugin-file@4.3.3
cordova-plugin-flurryanalytics@1.2.1
cordova-plugin-geolocation@2.4.3
cordova-plugin-googleplus@5.1.1
cordova-plugin-inappbrowser@1.7.1
cordova-plugin-meteor-webapp@1.4.1
cordova-plugin-splashscreen@4.0.3
cordova-plugin-statusbar@2.2.3
cordova-plugin-wkwebview-engine@1.1.3
cordova-plugin-x-socialsharing@5.1.8

**Comment by abernix** [comment]
@fullhdpixel What if you remove your `.meteor/local/cordova-build` directory from your application and also run:

    meteor remove-platform ios
    meteor add-platform ios

?

**Comment by fullhdpixel** [comment]
Already tried several times. Its not a caching issue.

**Comment by abernix** [comment]
Ok, I'll have to ask for a reproduction then.  Basic apps work just fine for me with Meteor 1.5.1 so please provide a basic reproduction with a new Meteor application for further analysis.  Consult the [guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for what's expected, upload it to GitHub and provide a link here.

**Comment by fullhdpixel** [comment]
Reproduction repository: https://github.com/fullhdpixel/ios-zwifterrors

git clone https://github.com/fullhdpixel/ios-zwifterrors.git
meteor run ios-device

Server and client folders are not interesting, just cordova-plugins and packages and maybe mobile-config

**Comment by fullhdpixel** [comment]
@abernix Is the reproduction sufficient like this or do you need more info?

**Comment by derwaldgeist** [comment]
You're missing the Swift bridging header required since Meteor 1.3.

![swift-header](https://user-images.githubusercontent.com/3984535/28817571-ea4519cc-76a8-11e7-835b-9b7e7b7b3aab.png)

This solves the Meteor-related problem. But still the app won't compile since there's still a problem with your plugin `cordova-plugin-flurry-analytics`. If you remove it, the app compiles just fine.

**Comment by fullhdpixel** [comment]
Thanks this resolved this particular issue! Is this mentioned anywhere in official Meteor documentation?

**Comment by fullhdpixel** [comment]
Only there's another error Im seeing, not sure if related to this.

`Apple Mach-O Linker (ld) Error Group: clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by derwaldgeist** [comment]
Unfortunately, the bridging header is not mentioned in the docs. Normally, Meteor would setup this header for you, but in your case this seems to have failed. Could be a side-effect of another plugin. 

But I also had problems with Meteor's approach. Meteor assumes that there is no other bridging header available. My app, however, had its own bridging header in place, which was needed for another Cordova plugin. So I had to create my own hook script to combine both header files into one.

This whole bridging header thing is a mess created by Apple. Instead of enabling Swift to access ObjectiveC code directly, they require you to create these strange bridging headers that only cause problems. Another big problem with Swift is that you have to update your apps with every new Swift version, since there are a lot of breaking changes. I love the language, but I dislike the whole build mess it creates.

**Comment by fullhdpixel** [comment]
Thanks for the help. I managed to get the app working, now I can finally focus on the actual app code. FlurryAnalytics doesn't work however.

**Comment by fullhdpixel** [comment]
For future reference, to solve the Apple Mach-O Linker (ld) Error Group: clang: error: linker command failed with exit code 1 (use -v to see invocation) error.

Make sure to open the .xcworkspace instead of the .xcodeproj file
