### ISSUE TITLE
mouseenter and mouseleave triggering twice only on first run

### ISSUE THREAD

**Issue by michaelcbrook** [meteor/meteor#8935]
I just updated my Meteor to the latest version, 1.5.1, to make sure this wasn't an old issue, but I'm still experiencing it.

For some reason, when I use the mouseenter and mouseleave event triggers on an element, the events each trigger twice the first time they occur. But every time after that, they trigger once as expected.

I know the first thought is to check for bubbling, but this happens even on elements that have no children, and mouseenter and mouseleave should prevent multiple triggers inside children anyway, as opposed to mouseover and mouseout.

Mouseover and mouseout, however, work fine. They will trigger again for children, but that's expected.

Also to note, even though the problem occurs even on elements with no children, I tried adding event.preventDefault(), event.stopPropagation(), and return false for shits and giggles and it still does not fix it. My element is also not changing size or doing any kind of transformation or change in style.

I believe this is a bug, especially since it triggers twice only the first time but not after that. If I'm wrong, I'd appreciate any other valuable insight into this issue.

Thanks!

**Comment by klaussner** [comment]
Could you provide a small reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? :slightly_smiling_face:

**Comment by michaelcbrook** [comment]
Yes, here you go.

https://github.com/michaelcbrook/meteor-mouseenter-bug

`git clone git@github.com:michaelcbrook/meteor-mouseenter-bug.git`

**Comment by hwillson** [comment]
Hi @michaelcbrook - I've looked at your repro and it does look like a bug somewhere, especially since switching to use `mouseover` / `mouseout` works properly. That being said, would you mind re-opening this issue in the https://github.com/meteor/blaze repo? Thanks!
