### ISSUE TITLE
[bug] `meteor` updates itself

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#8938]
Please stop auto-updating the `meteor` CLI. It's quite annoying.

I just want to use Meteor when I want to use it, not wait for downloads! And not possibly introduce bugs when everything is working just fine!

Even when updated, network requests will make it laaaaaaaaaaaaaaaag, especially on slow networks.

A better behavior would be to give a friendly message like

```
Meteor 1.5.1 is available. Upgrade your CLI command with "meteor update cli".
```

or something.

Please, people have complained about this for a while now (I don't want to spend time looking for the threads).

Pleeeeeeeeeease.

**Comment by trusktr** [comment]
I am also willing to bet some people use the `meteor` command _in production_.

I don't think it's a good idea for you to be risking their production applications with auto updates.

**Comment by abernix** [comment]
Nobody should be using the `meteor` tool itself in production, they should be using a built version of their app from `meteor build`.

The auto-updating of the `meteor` command line tool allows Meteor to notify you of (possibly critical) updates to Meteor when they're available.  It downloads in the background and only affects the core `meteor` tool (and any new apps you might create) not the version an existing app uses, which would never be auto-updated.

We'll continue to work on reducing the size of the bundle to improve the network performance, and it's certainly possible that a future version of Meteor will work differently, but this is not a bug.

If you'd like to disable Meteor's auto-updating, just set `METEOR_NO_RELEASE_CHECK` to a true value in your environment.
