### ISSUE TITLE
Collection name from multip databases cannot be named the same

### ISSUE THREAD

**Issue by aadamsx** [meteor/meteor#8939]
Meteor 1.5, latest MacOS.

Even though I have two different drivers from two different databases, when attempting to declare a mongo collection with two different names, Meteor throws and error if the **collection name** is the same (in this case "People").  I think this is a bug.

```javascript
import { Mongo } from 'meteor/mongo';
import { MongoInternals } from 'meteor/mongo';

const db1 = new MongoInternals.RemoteCollectionDriver('mongodb://localhost:27017/db-1');
const People_1 = new Mongo.Collection("People", { _driver: db1 });

const db2 = new MongoInternals.RemoteCollectionDriver('mongodb://localhost:27017/db-2');
const People_2 = new Mongo.Collection("People", { _driver: db2 });
```

**Comment by hwillson** [comment]
@aadamsx Can you try adjusting the options passed into the `Mongo.Collection` constructor to look like:

```js
{ 
  _driver: db2,
  _suppressSameNameError: true
}
```

Please post back if this works properly. If so, we'll look into getting this documented properly. Thanks!

**Comment by formspoint** [comment]
```_suppressSameNameError: true``` stopped the Meteor errors!  Thank you!

**Comment by aadamsx** [comment]
_suppressSameNameError: true stopped the Meteor errors! Thank you!

**Comment by gothicn** [comment]
@aadamsx, not really, only __preventAutopublish_ that works together with autopublish package and does... 
what its name implies...

**Comment by hwillson** [comment]
> If so, we'll look into getting this documented properly.

Thinking about this more, I don't think documenting `_suppressSameNameError` is the right approach. The functionality behind `_suppressSameNameError` has existed from quite some time by default, but the `There is already a collection named X` error is still thrown for historical reasons. It's not really needed anymore, and `_suppressSameNameError` was introduced as a way to allow people to opt-out of seeing the error, and allow for additional prod application testing, before making this option the default. I think we might want to consider doing away with the `_suppressSameNameError` option, as well as removing the thrown `There is already a collection named X` exception. Or maybe better yet -  we make the `_suppressSameNameError` option public, like `suppressSameNameWarning`, keep the default to false, and `console.warn` the `There is already a collection named X` message, instead of throwing it.

**Comment by aadamsx** [comment]
IMHO I think being able to have two or more collections with the same name without an error or even a warning.  A warning IMHO would be annoying as all getout, as there is nothing wrong with this. Maybe a note in the docs about an caveats would suffice for some.

**Comment by mwkrieger** [comment]
I'm having some issues trying to use the _supressSameNameError as well. 

I have a collection on a remote server called 'users'. It's a collection that is managed by a different application altogether - not a Meteor app. I need to read this collection. 

In my Meteor app, I'm using the accounts package and I've reassigned the 'users' collection by doing a Meteor.users = Account.users. I've also defined two remote databases (I'm not using anything local). Code example below:

```
var driver = new MongoInternals.RemoteCollectionDriver(
        mongoURL, {
            oplogUrl: oplogURL
        });

var options = {
        _driver: driver,
        _suppressSameNameError: true
    };

var driver2 = new MongoInternals.RemoteCollectionDriver(
        mongoURL2, {
            oplogUrl: oplogURL2
        });

var options2 = {
        _driver: driver2,
        _suppressSameNameError: true
    };

Accounts.users = new Mongo.Collection('portalusers', options);
Meteor.users = Account.users;

var SSOUsers = new Mongo.Collection('users', options2); <--This is where I get the error, even though there is no other 'users' collection defined anywhere.
```
When I start up Meteor, I get the 'There is already a collection named "users"' error in the console and the app won't run. 

I was under the assumption that the _supressSameNameError flag in the Mongo.Collections options would suppress/bypass this error message and let the app run. 

As a test, I tried defining a different collection thinking it was an issue with the 'user's collection. 

```
var T1 = new Mongo.Collection('test', options);
var T2 = new Mongo.Collection('test', options2);
```
But the same error was thrown - indicating that there was already a collection named test. 

I'm on Meteor 1.5.2.2

Any suggestions? Am I doing something wrong with the flag?

**Comment by hwillson** [comment]
We're going to document the `_suppressSameNameError` option, leaving the current behavior as is. This work is being tracked in https://github.com/meteor/docs/issues/179.

@mwkrieger You're probably running into issue https://github.com/meteor/meteor/issues/7455. See the workaround discussed in https://github.com/meteor/meteor/issues/7455#issuecomment-234843901.
