### ISSUE TITLE
Clientside Meteor.startup function are not executed

### ISSUE THREAD

**Issue by namirsab** [meteor/meteor#8944]
Hey
We have an urgent problem
Client side `Meteor.startup` functions are not running in production. In development they work correctly, even if we run the app with the --production flag.
They are basically ignored.

More info:
If we add in production a `Meteor.startup` function in the console, it gets executed

Any clue?

Thanks in advance!

Meteor version: 1.5

@benjamn @abernix

**Comment by namirsab** [comment]
Okey we found the error. jQuery is magically updated to 3.2.1 in production but not in development. We didn't update it directly, so maybe a package or something updated it. A `Meteor.startup` callback is throwing and that's why half of the `callbackQueue` is not run.

**Comment by namirsab** [comment]
Any clue how is possible that production code has jquery in a different version than development code?

**Comment by namirsab** [comment]
We don't have jquery installed as a direct dependency in our app's `package.json`

**Comment by namirsab** [comment]
To fix the issue we had to pin the version of `jquery` in our `package.json`
How can that be that the same code in different environments selects different jquery versions?

**Comment by abernix** [comment]
We'd love to help but it's quite difficult and virtually impossible to help without a reproduction, any list of Meteor packages, a copy of your `package.json`, a list of packages in your `node_modules` directory, etc., etc. 😃 

Also, you haven't indicated whether this is a new problem with Meteor 1.5 or just a general problem in your project.  If it started with a specific version of Meteor, you should include that as well, but regardless, we'd desire a reproduction.

**Comment by namirsab** [comment]
@abernix  I'd love to give a reproduction too, but we don't know how it's happening and we don't know how to write a minimal reproduction.
The problem is that we can't reproduce it in development.
Anyway, we'll try to figure it out and I'll post any interesting findings.

Thanks!
