### ISSUE TITLE
Error: expected to be _runningOrRunScheduled

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#8950]
I am trying to debug this for hours now but cannot find the root cause. Since I upgraded my app from 1.2 to 1.5.1, I am experiencing weird server crashes that occur when I try to call the `update()` method of the `Meteor.users` collection.

I have several Meteor methods that call this `update()` method. Some work as expected, but some cause the server to crash and restart. The only output I get on the console is this:

```
W20170727-11:45:53.635(2)? (STDERR) /Users/waldgeist/.meteor/packages/meteor-tool/.1.5.1.7d6ojz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170727-11:45:53.636(2)? (STDERR) 						throw(ex);
W20170727-11:45:53.636(2)? (STDERR) 						^
W20170727-11:45:53.637(2)? (STDERR) 
W20170727-11:45:53.637(2)? (STDERR) Error: expected to be _runningOrRunScheduled
W20170727-11:45:53.638(2)? (STDERR)     at [object Object]._.extend._run (packages/meteor.js:797:13)
W20170727-11:45:53.638(2)? (STDERR)     at packages/meteor.js:789:14
```

This happens in this line:
https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/meteor/fiber_helpers.js#L133

I tried to analyse my code and even analysed the call stack in node-inspector. However, I cannot see any differences in the way my Meteor methods are structured and how they call the `update()` method; they seem to be structurally identical and also the call stack is very similar.

Does anybody here know what this error message means and how a state could occur where the "_runningOrRunScheduled" flag is not set correctly?

**Comment by hwillson** [comment]
Sorry to hear @derwaldgeist! This is a difficult one to troubleshoot without seeing any code. Any chance you'd be ale to put together a small, runnable reproduction that demonstrates this problem? Maybe start by cutting code / packages / dependencies out of your app, until the issue goes away (if it does), then base your repro off of that. Thanks!

**Comment by derwaldgeist** [comment]
@hwillson I can try, but this will be very difficult to isolate :-( In the meantime, I created two screenshots of the call stack in node-inspector.

This first screenshot shows the exact code line where the `throw` occurs. One can see clearly that the flag is set to false:

![false 1](https://user-images.githubusercontent.com/3984535/28666535-fec4bdd8-72c7-11e7-93be-ab113191c5c0.png)

This screenshot shows the line where the `_run` has been called (i.e. one level in the call stack).  As you can see, the flag has been set to `true` before setImmediate() is executed. But somehow in the way to the `_run()` call the flag seems to be reset, as you can see in the node-inspector:

![false 2](https://user-images.githubusercontent.com/3984535/28666562-2789d258-72c8-11e7-9958-471c25add6a4.png)

**Comment by derwaldgeist** [comment]
I tried very hard, but I wasn't able to slim the app down to a repro repo. :-( I took the very same code I had in my live app and isolated it, but in this case the problem did not occur.

It seems as if this problem only occurs under certain conditions, if multiple calls database operations are being executed in succession. And it looks like a kind of race condition.

**Comment by derwaldgeist** [comment]
I have now done a sequential upgrade from 1.3.5 up to 1.5.1. It showed that the problem was introduced with 1.5.1. My app works fine up to 1.5, but with 1.5.1 it crashes.

Here's the log of the packages that were updated from 1.5 to 1.5.1:

```
accounts-base              upgraded from 1.3.0 to 1.3.1
accounts-password          upgraded from 1.3.6 to 1.4.0
allow-deny                 upgraded from 1.0.5 to 1.0.6
babel-compiler             upgraded from 6.19.1 to 6.19.4
boilerplate-generator      upgraded from 1.1.0 to 1.1.1
ddp                        upgraded from 1.2.5 to 1.3.0
ddp-client*                upgraded from 1.3.4 to 2.0.0
ddp-common                 upgraded from 1.2.8 to 1.2.9
ddp-server*                upgraded from 1.3.14 to 2.0.0
dynamic-import             upgraded from 0.1.0 to 0.1.1
ecmascript                 upgraded from 0.8.0 to 0.8.1
ecmascript-runtime-client  upgraded from 0.4.1 to 0.4.2
email                      upgraded from 1.2.1 to 1.2.3
meteor                     upgraded from 1.6.1 to 1.7.0
minimongo                  upgraded from 1.2.0 to 1.2.1
modules                    upgraded from 0.9.0 to 0.9.2
mongo                      upgraded from 1.1.18 to 1.1.19
npm-bcrypt                 upgraded from 0.9.2 to 0.9.3
shell-server               upgraded from 0.2.3 to 0.2.4
webapp                     upgraded from 1.3.16 to 1.3.17
```

**Comment by derwaldgeist** [comment]
Unfortunately, Meteor doesn't let me try out each package version individually, as it pins them to a specific Meteor version. How could I check which one is the culprit?

**Comment by abernix** [comment]
@derwaldgeist If you just adjust the versions in `.meteor/versions` back to the pre-upgrade state (using version control) and then, even while the app is running, incrementally update each to the new version number (i.e. the `y` version of `upgraded from x to y` in the output above) you can progressively try select packages.  Some will be less willing than others as they themselves have dependencies on Meteor (as Meteor itself also must provide the functionality that they use!) but many of those should be independent.

With that said though, since you're experiencing the problem with `packages/meteor.js` (from your screenshot) though, I'd probably recommend starting there and changing that back to `meteor@1.6.1`.  This might be related to #8947.

**Comment by derwaldgeist** [comment]
Hi @abernix Thanks for your reply. I tried to manually adjust the packages, but all I tried were reset by the Meteor build tool immediately. For others, touching them made me run into #8947, due to some weird dependencies. But I don't think that #8947 is really related to my case. At least, I now know that my app works fine up to 1.5 and "only" breaks in 1.5.1.

**Comment by abernix** [comment]
What happens if you:

    meteor create --release 1.5 reproduction-app

Then, copy the `versions` and `packages` files from your (other) working 1.5 app to the new app and then successfully break it by doing `meteor update --release 1.5.1`?

If so, can you upload a reproduction **prior** to the update to 1.5.1? :smile:

**Comment by derwaldgeist** [comment]
Sorry for the late reply. I tried hard to find a way to build a repro repo, but without luck so far. It seems as if this problem only occurs under certain conditions.

A little bit about the context of my app: It is using gamification features, i.e. people are awarded with "karma" points and badges for certain activities. To enable this, I am using an internal event bus where components fire events that the gamification service listens to and reacts accordingly. If the event will lead to awards, the user profile is updated.

This mechanism works fine up to 1.5, but in 1.5.1 it happens that some of the database writes fail. I tried to isolate this into a repo repository, using exactly the same logic as in the real app. But interestingly, it didn't break there, although the statement paths are exactly the same. I even debugged it with node-debugger to find any potential differences. Took me hours until I finally gave up. Unfortunately, I'm not able to provide the whole app as a repro repository.

**Comment by abernix** [comment]
Would you be able to reproduce the problem reliably if you [ran Meteor from a Git checkout](https://github.com/meteor/meteor/blob/devel/Development.md#running-from-a-git-checkout) on your own application?  Contrary to the problems you had by changing `.meteor/versions` manually on an actual release (which is constrained by the release itself), if you use a Meteor checkout those constraints are removed and the packages in the checkout are used instead.

There was a `meteor@1.7.1` (the package, not the tool) which could have fixed your problem, if it was in-fact related to #8947.

**Comment by abernix** [comment]
@derwaldgeist Have you tried running from a checkout per my previous comment?

**Comment by hwillson** [comment]
We haven't heard back regarding https://github.com/meteor/meteor/issues/8950#issuecomment-330198860, so I'll close this for now. Happy to re-open if you're still encountering this issue, and can post back with the results of running from a Meteor developer checkout. Thanks!

**Comment by derwaldgeist** [comment]
I was about to close this issue myself, as it didn't appear again after upgrading the app from 1.5.0 to 1.6. But I wasn't sure yet, so I wanted to test a bit more before I send an "all-clear" message :-)

**Comment by derwaldgeist** [comment]
The issue now popped up for the first time under Meteor 1.6. Fortunately, the server did not crash anymore as in Meteor 1.5.1. Here's the log:

```
W20180108-21:06:30.538(1)? (STDERR) Error: expected to be _runningOrRunScheduled
W20180108-21:06:30.538(1)? (STDERR)     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:855:11)
W20180108-21:06:30.539(1)? (STDERR)     at packages/meteor.js:846:12
```

**Comment by derwaldgeist** [comment]
Still happens under 1.6. Server won't crash, but restart. Pretty annoying. How can I re-open this?

**Comment by derwaldgeist** [comment]
I tried to track this down a bit more, using the Node debugger. In the call stack I can see that the problem occurs during execution of the `authenticateStragglers()` function of MongoDB's connection pool. I can only guess there's a racing condition in this code part of `Meteor._SynchronousQueue`:

```js
SQp._scheduleRun = function () {
  var self = this;
  // Already running or scheduled? Do nothing.
  if (self._runningOrRunScheduled)
    return;

  self._runningOrRunScheduled = true;
  setImmediate(function () {
    Fiber(function () {
      self._run();
    }).run();
  });
};
```
It seems as if once `self._run()` is being executed, the flag `self._runningOrRunScheduled` has been set to false again.

**Comment by derwaldgeist** [comment]
Nailed it down further. The problem occurs if I call Meteor.user() inside the Meteor method, which also does a lot of database operations.
