### ISSUE TITLE
[1.6-beta.14] 'super' outside of function or class 

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8955]
Using 1.6-beta.14.
When using 'super' in combination with 'async/await' you get the following error:
`'super' outside of function or class `

Reproduction: https://github.com/sebakerckhof/m16superproblem

I've seen this happen before in another application and then it was due to a bug in babels `transform-async-to-generator`, ie. this bug: https://github.com/babel/babel/issues/3930. However, since async/await is natively supported in node 8 I don't see why I should get this (on the server at least)?

**Comment by abernix** [comment]
This is a bug.  Thanks for reporting it.

I'll take a stab at explaining, but @benjamn will have more information and I think he's still iterating on this:  While Meteor does use native `async`/`await` functions (and the progress in that department is [relatively recent](https://github.com/meteor/babel/commit/a7c81ff7bb40623991cbec24777f7f2fae31a2d8), as you found in the most recent beta), it still uses `Fiber`s on the server which means that the `async` function gets wrapped in [`Promise.asyncApply`](https://github.com/meteor/promise/blob/466b1c820e2b4bcdb3e781ac1baf719afce46fae/promise_server.js#L124-L142).

So on Meteor 1.6, your code is transpiled to (roughly):

```js
class Bar extends Foo {
  constructor() {
    super();
  }

  run() {
    return Promise.asyncApply(async function () {
      await super.run();
    }, this);
  }
}
```

That `super` ends up being a problem though as the environment of the function isn't aware that `super` is valid in that context.  (Of course, `super` internally refers to ([roughly](https://www.ecma-international.org/ecma-262/#sec-getsuperconstructor)) `Object.getPrototypeOf(this)`, but it's just a matter of making the code inside that function aware of that.)

**Comment by benjamn** [comment]
We could make the inner function an `async` arrow function, which would make the `this` argument unnecessary, too. In other words, [this code](https://github.com/meteor/babel/blob/a6a7b5165ec6ffd9d0e62e6fbb316d4e2889a07c/plugins/async-await.js#L32-L42) could be just
```js
innerFn.type = "ArrowFunctionExpression";
```

**Comment by sebakerckhof** [comment]
Can confirm that this is solved in beta 15, thanks

**Comment by abernix** [comment]
Awesome!  Thanks for reporting back, @sebakerckhof. 😄
