### ISSUE TITLE
[1.6-beta.14] Issue with Login tokens for Apollo users

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#8957]
Looks like an issue has been introduced somewhere between `1.6-beta.4` and `1.6-beta.14` around the handling of user login tokens. I noticed this in my Meteor app that uses Apollo. When I try to sign up / sign in (either via Facebook integration or email / password), I'm getting "Invalid Date" computed on the `tokenExpires` field.

I originally posted this in https://github.com/orionsoft/meteor-apollo-accounts/issues/70 , which contains some troubleshooting information I did on this issue.

**Comment by joncursi** [comment]
This issue is still present on the latest beta `METEOR@1.6-beta.23`

**Comment by joncursi** [comment]
Through lots of trial and error (testing each beta out one by one), I've been able to narrow it down to the specific release that introduced the issue: `METEOR@1.6-beta.11`

`beta.10` is the last release that does not have this issue.

**Comment by abernix** [comment]
Could you please post a simple reproduction demonstrating the problem on using Meteor `1.6-beta.23` and (presumably?) the `accounts-password` package?

**Comment by hwillson** [comment]
Hi @joncursi - any luck with putting together a reproduction, as requested in https://github.com/meteor/meteor/issues/8957#issuecomment-324299743?

**Comment by joncursi** [comment]
This appears to have been fixed somewhere along the line. I just tried upgrading to `METEOR@1.6-beta.32` and my sign in / sign up functionality was restored. Closing for now. Thank you!
