### ISSUE TITLE
Packages in non-core can’t reference each other

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor/meteor#8962]
See #8960.

In that PR I created two packages, `coffeescript` and `coffeescript-compiler`, with the former importing the latter. In `coffeescript/package.js`, I have:

```js
Package.registerBuildPlugin({
  use: ['caching-compiler', 'coffeescript-compiler', 'ecmascript'],
```

If these two packages are both in `packages`, running `./meteor test-packages coffeescript` works and the tests pass. Move the packages into `packages/non-core`, which is where `coffeescript` is currently on `devel`, and the `coffeescript` package can’t find `coffeescript-compiler`:

```
   While selecting package versions:
   error: unknown package: coffeescript-compiler
   Required by: coffeescript 10.0.1
```

Seen on OS X, checkout of bd22b331da5f438894e95b9fcd00c4ec7d8ae5c4. See also #8961.

**Comment by benjamn** [comment]
This should be working in recent 1.5.2 beta versions (e.g. the latest one, `1.5.2-beta.9`)!
