### ISSUE TITLE
Standard Content Security Policy for Cordova is missing the android-webview-video-poster scheme

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#8965]
I am trying to get WebRTC work on Meteor 1.5 and Android devices. On one of them, I get the following error message when trying to add the video stream:

```
Refused to load the image 'android-webview-video-poster:default_video_poster/1383114863730884148' because it violates the following Content Security Policy directive: "default-src * gap: data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

It seems as if Android requires yet another CSP for the protocol scheme `android-webview-video-poster:` to be applied for this scenario. The video that I get in this case is only 2x2 pixels size. I'm not sure if the missing CSP is the cause for that, but this warning did not occur in Meteor 1.2, where everything worked.

I tried to override the CSP locally, by providing a local, patched copy of the `boilerplate-generator` for Cordova, but this doesn't work. Although Meteor recognises my local package, it still uses the CSP default boilerplate. Setting a custom CSP via a custom head.html doesn't work either, because this will only add a second CSP that is ignored by Android. I also tried to use the `BrowserPolicy` package, but this doesn't offer to add completely new protocols to the CSP (which would be very helpful in such cases).

It would be great if the protocol scheme could be added, at least for Meteor 1.5 onwards. I cannot use Meteor 1.5.1 at the moment, due to another issue that breaks my server code. Thanks.

**Comment by hashcutdev** [comment]
I've been dealing with this is as well. Basically it seems any html5 video thumbnail/preview image needs the android-webview-video-poster: protocol allowed in the CSP and this is impossible with the current browser-policy package.

**Comment by srtucker22** [comment]
Would also love to see this implemented to get WebRTC video working again.

Also, it seems like this sort of thing [has happened before with a different CSP](https://github.com/meteor/meteor/issues/7772) -- maybe there's a nice way to make the CSP configuration more accessible?

**Comment by derwaldgeist** [comment]
Yes, it would be awesome if the CSP could be set programmatically. The current implementation lets you tweak certain parameters, but not the whole CSP as such.

@srtucker22: I got WebRTC working again by programmatically adding the required Android permissions instead of defining them in the `android-manifest.xml`. This seems to be a side-effect of Meteor requiring SDK 23+ from Meteor 1.3 on, and it only affected devices running Android Marshmallow and beyond. It only works on Crosswalk, though, in a non-Crosswalk app camera access doesn't work as expected. Not sure if this is related to the missing CSP.

**Comment by srtucker22** [comment]
@derwaldgeist You're a beast! I had programmatically added permissions after upgrading to 1.3+, but for whatever reason removed Crosswalk. Adding back Crosswalk did the trick!

BTW, before adding back Crosswalk, I managed to sneak in a forced manual change to the CSP in index.html at some point and the camera was working and seemed fine ¯\_(ツ)_/¯

**Comment by znewsham** [comment]
sorry to re-awaken this, but I came across a similar problem recently, I tried several things to fix, but ultimately this is what stuck - apart from the hideousness of it, I'd be interested to see if anyone forsees any big problems here:

`var oldGBPI = WebAppInternals.generateBoilerplateInstance;
WebAppInternals.generateBoilerplateInstance = function(arch){
  var ret = oldGBPI.apply(this, _.toArray(arguments));
  if(arch === "web.cordova"){
    ret.template = ret.template.replace("default-src *","default-src * android-webview-video-poster:");
    var func = ret.func.toString();
    func = func.replace("default-src *","default-src * android-webview-video-poster:");
    ret.func = eval("ret.func = " + func);
  }
  return ret;
};`

**Comment by inspiraluna** [comment]
I do WebRTC together with meteor 1.6 and the **iosrtc** plugin for iOS right now (https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc)

I put this into index.html in order to make it work
```
<meta http-equiv="Content-Security-Policy" content="default-src * gap: data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:;  connect-src *  data: blob: ws: wss:;">
```

config.xml 
```
<allow-intent href="blob:*" />
<allow-intent href="polyblob:*" />
```
although I am not 100% sure if it needs the "polyblob" thing... 

unfortunately I do have to add this manually everytime I create the iOS app. 
I am still looking for a process to automate this. Is the BrowserPolicy Plugin an option?

**Comment by skirunman** [comment]
@hwillson can we get the Project:mobile tag added to this issue?

**Comment by hwillson** [comment]
Meteor's `webapp` API has been updated to allow callbacks to be registered, that can be used to modify any part of the HTML boilerplate. See [WebAppInternals.registerBoilerplateDataCallback](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/packages/webapp/webapp_server.js#L260) (and for more details and a quick example, see https://github.com/meteor/meteor/issues/9660#issuecomment-365021532). This new API can be used to manipulate `<head />` elements as needed, so I'll close this off. Thanks!

**Comment by derwaldgeist** [comment]
Wow, this is just fantastic! Thanks a lot! 🚀

**Comment by crapthings** [comment]
copy 'boilerplate-generator' from meteor repo and add package name to it.

```js
Package.describe({
  name: 'boilerplate-generator',
  summary: "Generates the boilerplate html from program's manifest",
  version: '1.6.0'
});
```

then in your .meteor/packages

```
boilerplate-generator@1.6.0
```

so default cordova template can be safely override.

to make android works with webrtc

you should have permissions

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />

these two might no needed but i still add it into list
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

**Comment by filipenevola** [comment]
I think is always better to open a new issue referencing the old one
