### ISSUE TITLE
importing a meteor package only use'd in another arch doesn't always throw an error (or succeed)

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#8969]
Meteor 1.5.1.

The key here is that package `a` has `api.use('b', 'client')` but imports 'b' on the server anyway. *and* `b` is separately used by the app.

```
glasser@glasser-lyrid-2 0 /tmp $ git clone https://github.com/glasser/meteor-bug-import-one-arch >/dev/null.
glasser@glasser-lyrid-2 0 /tmp $ cd meteor-bug-import-one-arch/
glasser@glasser-lyrid-2 0 /tmp/meteor-bug-import-one-arch master u= p= $ meteor npm install >/dev/null
glasser@glasser-lyrid-2 0 /tmp/meteor-bug-import-one-arch master u= p= $ meteor
[[[[[ /private/tmp/meteor-bug-import-one-arch ]]]]]

=> Started proxy.
=> Started MongoDB.
I20170731-10:32:17.043(-7)? Got undefined
=> Started your app.

=> App running at: http://localhost:3000/
```

It prints "Got undefined" which is very surprising: I'd expect the import to fail with an error, or maybe to somehow succeed and actually get the name, but instead it silently "succeeds" but fails to provide the requested object.

This caused a feature to silently break in our app (when we did this in the client rather than server).

**Comment by hwillson** [comment]
https://github.com/meteor/meteor/pull/8972 was merged and should help with this. Thanks!
