### ISSUE TITLE
server-render package -- search query, hash and other properties missing from request object

### ISSUE THREAD

**Issue by rehnarama** [meteor/meteor#8980]
# What version of Meteor you're using, and the platform(s) you're running it on
I'm running meteor@1.5.1 on Windows 10
# What packages or other dependencies you're using
Related dependencies:
* server-render@0.1.0
# The behavior you expect to see, and the actual behavior
When Meteor is running on port 3000, and I visit the site at `http://localhost:3000/#hash?search=query` The `request` property in the `sink` object that is passed to the callback in `onPageLoad`, i.e.
```
import { onPageLoad } from "meteor/server-render";
onPageLoad(sink => {
...
  console.log(sink.request);
...
});
```
looks like the following:
```
{
   protocol: null,
   slashes: null,
   auth: null,
   host: null,
   port: null,
   hostname: null,
   hash: null,
   search: '',
   query: {},
   pathname: '/',
   path: '/',
  href: '/' 
}
```
while I expect it to look like
```
{
   protocol: "http",
   slashes: null,
   auth: null,
   host: "localhost",
   port: 3000,
   hostname: "localhost",
   hash: "hash",
   search: "search=query",
   query: {},
   pathname: '/',
   path: '',
  href: '/#hash?search=query' 
}
```
or something along the lines of that (maybe some props are on the wrong keys, I can't seem to find documentation on the request-object).

Furthermore, it would be great if you could access http headers from the request object, but maybe that's a seperate issue.

# An *isolated* way to reproduce the behavior
Reproduction repository: https://github.com/rehnarama/server-render-bug-repro

Created by simply `meteor create` and then `meteor add server-render`. Start the app and go to `http://localhost:3000/#hash?search=query` to see the request object being logged in the server console.

**Comment by AirBorne04** [comment]
hi @rehnarama ,
the behavior you are facing is the correct behavior anything behind the first # is a fragment url which is not sent to the server. Therefore your server request object is not aware of it.

If you sent `http://localhost:3000/?search=query#hash` to the server the server will see `http://localhost:3000/?search=query` this comes from the intention to use the fragment as an in-page navigation therefore the browser is the only instance caring about the part.

here are some more infos about the fragment urls [6 things about fragment urls](https://blog.httpwatch.com/2011/03/01/6-things-you-should-know-about-fragment-urls/)

**Comment by rehnarama** [comment]
Oh okay, of course. Thanks for the explanation. Closing this.
