### ISSUE TITLE
[1.5.1] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ExcelNet-Public** [meteor/meteor#8983]
OK, so today has been a very annoying day so far. Was working on a meteor app until about 10:00pm last evening. This morning shut the system down and as I do EVERY day go to the office. Started machine back up and went to resume development. Same process that has been happening for a year ore more.

This is a Windows 10 x64 machine, running Meteor 1.5.1. This is NOT anything new, it has been running 1.5.1 for a bit no issues. Don’t even believe there were any windows updates since yesterday.

Today however starting my meteor application or even just trying to run **meteor --version** yields me the following:

```
meteor --version
C:\Users\me\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\q\q.js:70
    hasStacks = !!e.stack;
                   ^

RangeError: Maximum call stack size exceeded
```

So I Google the issue and see others having this same issue with past releases. I remove node, remove meteor, clean the directories, restart, reinstall node (4.8.4), reinstall meteor, restart again.

I did see people also wiping their entire user profile and restarting, but this is really NOT an option. Everything else working great.

SAME EXACT ERROR!!! This is a very frustrating developer experience. Help!!!

**Comment by hwillson** [comment]
Hi @ExcelNet-Public - sorry to hear! There was one update pushed out yesterday - the core `meteor` package was bumped to version 1.7.1. To help us troubleshoot, can you try pinning to the older 1.7.0 version to see if that helps?

```
meteor add meteor@=1.7.0
```

**Comment by ExcelNet-Public** [comment]
No, unfortunately I cannot.  The command provided fails as well with the exact same message.  As mentioned in original post cannot even run **meteor --version** without crashing.

**Comment by hwillson** [comment]
Can you try adding it by hand then? Add the following to your `APP_ROOT/.meteor/packages` file:

```
meteor@=1.7.0
```

**Comment by ExcelNet-Public** [comment]
Tried that, makes no difference.  This is not one application specific.  From the command prompt and in ANY of my meteor applications (or a directory that is not a meteor application) the command **meteor --version** fails with the stack error.  About the most basic command I could think of.  

If I look at my %appdata%/./meteor/packages/meteor there is only a 1.7.0 folder listed there.  Think something else is going on.  

Thanks!

**Comment by ExcelNet-Public** [comment]
Don't think this will help, but at this point I am COMPLETELY dead and cannot continue development of my application.  If I try to start my application I get:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart myapp@0.9.5
6 info start myapp@0.9.5
7 verbose unsafe-perm in lifecycle true
8 info myapp@0.9.5 Failed to exec start script
9 verbose stack Error: myapp@0.9.5 start: `meteor --settings settings.json`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid myapp@0.9.5
11 verbose cwd C:\Users\me\meteor\myapp
12 error Windows_NT 10.0.15063
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.8.4
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error myapp@0.9.5 start: `meteor --settings settings.json`
17 error Exit status 1
18 error Failed at the myapp@0.9.5 start script 'meteor --settings settings.json'.
18 error This is most likely a problem with the myapp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     meteor --settings settings.json
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs myapp
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls myapp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Will probably need to see if I cannot just continue development on a VM or something similar since my Windows machine does not seem an option at this point.

Anything further I can collect to figure out this issue?

**Comment by ExcelNet-Public** [comment]
OK, so I kept at this and finally discovered in my profile folder that I had a folder named **node_modules**.  My guess this is where the "global" installs go.  Renamed that to **node_modules-old** and viola meteor started running again!!!

This is still a pretty odd thing as nothing changed from the night before when I was coding away and the next morning when I hoped to be coding again???

Would not mind if somebody can shed light on this further, but the ticket can likely be closed.  Please keep for "historical" reasons and the next person that appears to have these same issues.  Maybe it will save them all the pulling out hair (and I did not have a lot to lose).  Thanks!

**Comment by abernix** [comment]
Great to hear you found a solution!  Can you clarify *exactly* where you found that `node_modules` folder?  Typically, I expect global `node_modules` to reside in `%AppData%\npm` (that is to say, `C:\Users\USERNAME\AppData\npm`).

This could be helpful information for those experiencing this (same issue?) in #7896!

**Comment by ExcelNet-Public** [comment]
For me it was in `C:\Users\USERNAME\node_modules`.  I do not have `%AppData%\npm\node_modules` on my system.  I do have `%AppData%\npm` but it only has an `etc` folder.  Yes, certainly hope it can help as many people as run into this and the other issue seems very similar.  Thanks again

**Comment by tnedich** [comment]
@ExcelNet-Public - this helped me also

**Comment by RickiWeb** [comment]
Thank you for sharing your solution with us @ExcelNet-Public :)) 
You saved my day.

**Comment by kaushik-prasath** [comment]
That helped me a lot.Thanks!

**Comment by hobdawg** [comment]
Wow this worked for me too. Thanks!

**Comment by felixzxk** [comment]
can't thank you any more
