### ISSUE TITLE
1.5.1 - force-ssl redirects to https on localhost in virtual machine

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#8984]
Meteor Version: 1.5.1
Platform: Windows through a Linux Virtual Machine
Package: force-ssl@1.0.14

I am running Meteor locally with `--production --extra-packages bundle-visualizer` but I can't load the app without removing `force-ssl`. If I try `localhost:3000` or `127.0.0.1:3000`, I get redirected to `https://localhost`. If I try `https://localhost:3000`, it says the site can't be reached. 

I suspect that the issue may have something to do with running it through a virtual machine. But I'm not sure why that would cause issues.

**Comment by merlinpatt** [comment]
I was able to replicate this effect by creating the barebones app and add force-ssl.

In my virtual machine, I ran

1. `meteor create test-force-ssl`
2. `cd test-force-ssl`
3. `meteor add force-ssl`
4. `meteor --production`

And I get the exact same effects I described above.

**Comment by AirBorne04** [comment]
Hi,

I was not able to reproduce the issue in an normal environment (non-vm), as you where saying this is the probable reason.

For a quick check on the responsible code I would further investigate (force_ssl_common source)[https://github.com/meteor/meteor/blob/devel/packages/force-ssl-common/force_ssl_common.js] especially line 17, not sure what the sockets remote connections are reporting when connecting into a vm. Having said that i am currently not able running a vm myself and test it. (Did you try to run the linux subsystem on windows 10? I just ran a test on that one and had no issues either)

**Comment by abernix** [comment]
Related: https://github.com/meteor/docs/pull/151#issuecomment-317765988.

**Comment by hwillson** [comment]
The `force-ssl` package is a bit rigid when detecting if you're connecting from a local address. For example (up until recently), if your local address was detected as being an IPv4 address in IPv6 format (so something like `::ffff:127.0.0.1`), this would fail the local check, and kick off the force ssl process. Commit https://github.com/meteor/meteor/commit/62038c45f4f18fd2b879dc0dbf5ef6e96ee04a71 should help address this. After `force-ssl` version 1.0.15 is published, maybe try updating the package and giving your repro another shot, to see if that helps. Thanks!

**Comment by abernix** [comment]
I just published `force-ssl@1.0.15` which includes @hwillson's changes.  You can update by running:

    meteor update force-ssl

Please test and report back if the problem is solved!

**Comment by merlinpatt** [comment]
That didn't work. But I think I figured out the problem.

I added the packages manually and had it log the `forwardedParams.for` keys, which gave me the following

```
127.0.0.1
undefined
127.0.0.1
10.0.2.2
127.0.0.1
undefined
127.0.0.1
10.0.2.2 // offending IP
127.0.0.1
10.0.2.2 // offending IP
```

Upon running `ipconfig`, I got

```
eth0      Link encap:Ethernet  HWaddr 08:00:27:4f:2c:ef
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe4f:2cef/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:130292 errors:0 dropped:0 overruns:0 frame:0
          TX packets:122017 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11895093 (11.8 MB)  TX bytes:85393269 (85.3 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1214110 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1214110 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:189701805 (189.7 MB)  TX bytes:189701805 (189.7 MB)
```

Googling led to a couple relevant snippets (the bold piece is my addition)

> In this mode, every vm is assigned the same IP address (10.0.2.15) because each vm thinks they are on their own isolated network. And when they send their traffic via the gateway (10.0.2.2) ([Source](https://blogs.oracle.com/scoter/networking-in-virtualbox-v2))

> 10.0.2.15 **(as is 10.0.2.2)** is an address that falls in the 10.0.0.0 - 10.255.255.255 range, which is a "private network address" range, per [RFC 1918 (page 4, section 3 states "private access space" for LANs and Intranets and such)](https://tools.ietf.org/pdf/rfc1918.pdf)... typically are internal network addresses for the given local network, in this case the 'network' used by VirtualBox. ([Source](https://askubuntu.com/questions/340512/question-about-ip-address-on-virtualbox-for-a-home-server))

Some solutions would be (with possible downsides)

* Add the specific `10.0.2.2` address
    * There could be other VM tools that utilize different addresses
    * It might be possible someone has a production environment which utilizes a VM with this address (I find this unlikely, but worth noting)
* Add the entire `10....` range
    * I have no idea what kind of effect this could have or the dangers that might stem from it
    * Has the same second downside above
* Utilize some environment variable, Meteor.settings, or both of these (for those that prefer one or the other)
    * I don't see a downside here other than people would have to configure it themselves, but if they're using a VM, then I feel like that's an acceptable fix

@hwillson @abernix thoughts on how these solutions would affect the package?

**Comment by hwillson** [comment]
Sorry for the long delay in responding to this @merlinpatt. I don't think we can hardcode any `10.*` specific IPs, or the entire `10.*` range, as there could be intranet based apps located at those addresses that really do need SSL enforced. I think adjusting `force-ssl` to work with some form of optional whitelisted IP config element (your 3rd option) would probably make the most sense. Since this isn't a Meteor bug however, would you mind opening a new feature request for this over in http://github.com/meteor/meteor-feature-requests? Just a heads up though - using `force-ssl` is no longer a Meteor recommended SSL enforcement approach (see the [last paragraph of the package README](https://github.com/meteor/meteor/tree/1aaeca1cb82f080e15267b1dc4dc724074dc3b1a/packages/force-ssl#purpose)). That means functionality changes to `force-ssl` will likely be seen as low priority by  contributors. If you're interested in submitting a PR to work on this though, that would be great! Let's nail down the spec a little further over in a new feature request, then go from there. Thanks!
