### ISSUE TITLE
Sometimes project keeps reloading on Meteor 1.6-beta.15

### ISSUE THREAD

**Issue by SimonSimCity** [meteor/meteor#8988]
I sadly can't say that much about this problem, but maybe someone who also had this can step in:

I've updated Meteor to `1.6-beta.15` in the hope I could escape from https://github.com/meteor/meteor/issues/8648. It also works quite well ... just once a day (maybe after the 50th reload for testing) I suddenly see that the project keeps rebuilding itself and doesn't finish until I again change a file.

Here's exactly what I do and see:

1. I start the test environment of meteor (`meteor test --settings settings-test.json --driver-package practicalmeteor:mocha --port 3100 --verbose`)
2. After the app is initialized, I open http://localhost:3100/ in my browser, which reloads every time I change the code and the app is rebuilt.
3. After a couple of changes (have now worked 3h without any problem) - maybe 50 changes - I change a file and see that the site for running the tests loads abnormally long.
4. Watching the console I just see `Local package version is up-to-date: '[...]` running over the screen. In order to get more output (since the meteor-tool often overwrites it's last line on the console) I hold down the ENTER key to get a better overview over what happens.

Here I see the following (after removing duplicated and empty lines):

         Downloading missing packages              \
      Local package version is up-to-date: xolvio:backdoor@0.2.1
      Local package version is up-to-date: xolvio:cleaner@0.3.1
         Building the application                  /
         Building for web.browser                  -
         Building the application                  /
         Building for os.osx.x86_64                -
         Building the application                  \
         Reading project metadata                  -
         Scanning local packages                   \
         Preparing project                         \
      Local package version is up-to-date: accounts-base@1.4.0-beta.15
      Local package version is up-to-date: accounts-password@1.5.0-beta.15
         Downloading missing packages              \

To me it now seems that something either in `os.osx.x86_64` or `Building the application` fails, because if I stop meteor and start it into test-mode I get the following order:

    $ meteor test --settings settings-test.json --driver-package practicalmeteor:mocha --port 3100 --verbose
         Selecting package versions                /
      [[[[[ Tests ]]]]]                             
      => Started proxy.                             
      Local package version is up-to-date: accounts-base@1.4.0-beta.15
      Local package version is up-to-date: accounts-password@1.5.0-beta.15
      Local package version is up-to-date: [...]
      Local package version is up-to-date: xolvio:backdoor@0.2.1
      Local package version is up-to-date: xolvio:cleaner@0.3.1
         Downloading missing packages              -
         Building local packages                   \
         Determining active plugins                -
         Building the application                  \
         Building for web.browser                  -
         Building for os.osx.x86_64                |
         Starting your app                         \
      => Started MongoDB.                           
         Starting your app                         |

Anyone having an idea of how to go on debugging? I'm quite assured this error will come again in a few hours.

An interesting fact though:

If I now change a file (and thereby cause a new project-build), the current attempt is aborted and the next one will get through.

**Comment by SimonSimCity** [comment]
Sounds related to https://github.com/meteor/meteor/issues/8942, but the fix for this was already in `Meteor 1.6-beta.15 ` ...

**Comment by crapthings** [comment]
i've found this still happend with METEOR@1.6-beta.23

the process is running, and i just meteor npm i -S a module
