### ISSUE TITLE
Meteor build system caching old code

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#8992]
This may or may not be related to the recent [SegFault issues](https://github.com/meteor/meteor/issues/8648)

Basically, something changed in Meteor's cache when watching for changes in files.

If multiple files change, a cached version can get stuck in Meteor's build system.  Depending on the order of chaos, it seems to cause a segfault on the server, or builds old code into the browser.

Meteor 1.5.1

To reproduce:

1. Open project code in Atom
2. Find a commonly used helper function (both client and server)
3. Use Atom to rename the function across multiple files.
4. Repeat until segfault, or function name didn't change in the browser.  

Happens about 1-2x in 8 hours in my setup, and seems to be related to renaming stuff.

This showed up as a `Helpers.appGoto` being renamed to `Helpers.appPath`in my code, but after the build and refreshing the browser several times, the function continued to be `Helpers.appGoto`.

I had just done a rename in Atom 19 times across 7 files.

I've noticed this a couple other times recently (never happened in 1.4).  I'm building with Ubuntu 16.04

**Comment by hwillson** [comment]
@MichaelJCole It sounds like you're hitting https://github.com/meteor/meteor/issues/8942. A fix has been merged (see https://github.com/meteor/meteor/pull/8943) and should be in `1.5.2`.

**Comment by hwillson** [comment]
Since the fix for this has been merged into 1.5.2 (and will be coming soon), I'll close this for now. Thanks!
