### ISSUE TITLE
BrowserPolicy not defined [Meteor@1.5.1]

### ISSUE THREAD

**Issue by EliArtist** [meteor/meteor#8996]
I was trying really hard to figure this out, but I cant get to work the package "browser-policy".
I added it to meteor and tried to use it, but when running following code I get unexpected results:

`Meteor.startup(() => {
    console.log("Meteor started");
    console.log(BrowserPolicy);
});`

When I import:

`import { BrowserPolicy } from 'meteor/browser-policy';`

console.log will print undefined, when not importing it just throws a reference error.

**Comment by hwillson** [comment]
`browser-policy` is a server side only package. Are you trying to log `BrowserPolicy` on the client side?

In future, please consider posting usage questions like this on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`). Issues here are reserved for Meteor bugs. Thanks!
