### ISSUE TITLE
`App.icons` for iOs are incomplete

### ISSUE THREAD

**Issue by lpender** [meteor/meteor#9006]
Hi!

Using Meteor @ 1.5.1, Os X

*Expected Behavior*

Upon building for iOs, the [current set of app icons](https://docs.meteor.com/api/mobile-config.html#App-icons) should be complete. 

*Actual Behavior*

The current set is as follows:

```
iphone_2x (120x120)
iphone_3x (180x180)
ipad (76x76)
ipad_2x (152x152)
ipad_pro (167x167)
ios_settings (29x29)
ios_settings_2x (58x58)
ios_settings_3x (87x87)
ios_spotlight (40x40)
ios_spotlight_2x (80x80)
```

Leaves the following icons unfilled

iPhone Notification, 2x, 3x, iOs 7-10, 20pt
iPhone App, 1x, 2x, iOs 5,6, 57pt
iPad Notifications, iOs 7-10, 20pt
iPad Spotlight, iOs 5,6, 50pt
iPad App, 1x, 2x, iOS 5,6, 72pt

![image](https://user-images.githubusercontent.com/1406554/29220305-a2a9d3cc-7e88-11e7-8f07-355fae1194ac.png)

Related issue: 

https://github.com/lpender/meteor-assets/issues/10

Thank you!

**Comment by lpender** [comment]
I'm not sure how this works exactly, the PhoneGap docs seem to [missing the notification and watch sizes](http://docs.phonegap.com/phonegap-build/configuring/icons-and-splash/). 

It seems from the documentation above like none of the icons have identifiers. 

I assume that means that each icon is identified purely based on its dimensions.

If that's the case, here's what I would propose adding:

`ios_notification@2x`: `40x40`
`ios_notification@3x`: `60x60` 
`iphone_legacy`: `57x57` 
`iphone_legacy@2x`: `114x114` 
`ipad_spotlight_legacy: `50x50`
`ipad_spotlight_legacy_2x`: `100x100`
`ipad_app_legacy`: `72x172`
`ipad_app_legacy@2x`: `144x144`

The apple watch icons may need to be added too, but I'm leaving that outside the scope of this issue.

**Comment by lpender** [comment]
Also possibly related issue with [phonegap](https://github.com/phonegap/phonegap-plugin-push/issues/1218#issuecomment-321882253) ?

**Comment by lpender** [comment]
I added a PR for the proposed changes above ^^

**Comment by derwaldgeist** [comment]
Can this be fixed in 1.5, too, please? I cannot use 1.5.1 due to #8950 so far, and my app is rejected due to the inconsistent icons. Can patch this in Xcode, of course, but this is easy to miss.

**Comment by abernix** [comment]
@derwaldgeist The PR was merged into `release-1.5.2`, so yes.  See #8913 for updates on the status of that release, which is currently in beta.

**Comment by abernix** [comment]
#9012 was merged, so I'll close this.  Keep an eye out for it in Meteor 1.5.2!

Thanks very much for the PR, @lpender!

**Comment by derwaldgeist** [comment]
@abernix Thanks for the info. But I cannot use 1.5.2, as it will probably contain the same breaking change #8950 as 1.5.1. This is why I asked for downporting this to 1.5.0 (which is working fine for me and does not contain #8950).

**Comment by abernix** [comment]
1.5.0 (1.5) is already released; we can't backport a fix to a version that has already been released.  The next version number in the 1.5-series was 1.5.1.  If that has a bug (which you've indicated that it does), I'd suggest we work on fixing whatever broke for you and hopefully get that into a future 1.5.x.

It's possible that if it's related to a dependency, we can fix it by updating that dependency and not the main `meteor` tool, but it's yet to be determined if that's possible and if the problem lies in `meteor`.

All this would be facilitated by continuing the conversation on the actual bug in https://github.com/meteor/meteor/issues/8950#issuecomment-318668372 where I last responded 18 days ago, looking for a response from you.

**Comment by derwaldgeist** [comment]
> where I last responded 18 days ago, looking for a response from you

Yep, I know. I was trying hard to set-up a repro repository, but without luck so far.
