### ISSUE TITLE
[1.6-beta.18] Invalid babel output

### ISSUE THREAD

**Issue by janowsiany** [meteor/meteor#9013]
I am running `METEOR@1.6-beta.18`, inside my codebase i am doing [object destructuring with rest syntax](https://github.com/janowsiany/meteor-babel-bug-repro/blob/master/server/main.js#L5) which transpiles into: 
```js
var _objectWithoutProperties2 = require("babel-runtime/helpers/objectWithoutProperties");

var _objectWithoutProperties3 = _interopRequireDefault(_objectWithoutProperties2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

const {
  a: {
    b: {
      c
    }
  }
} = settings,
      other = (0, _objectWithoutProperties3.default)(settings.b.a, ["c"]);
```
If you did not noticed the order of the keys in the path for `other` is wrong.

[Expected result is like](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=MYewdgzgLgBA3gQwFzwEYrsANDAdPkKACwFMAnAXypgF4YISooBLMAcwgG4g).
[Repro](https://github.com/janowsiany/meteor-babel-bug-repro)

cc: @benjamn @abernix @hwillson @radekmie @skirunman

**Comment by janowsiany** [comment]
Still reproducible with meteor@1.6-beta.25. @benjamn any clues? I could investigate this problem more deeply if only knew the direction.

**Comment by hexagon6** [comment]
@janowsiany since this is a babel-transform, we should test if this is normal behaviour in babel too.

Meteor uses the following babel-preset for ES-transforms https://github.com/meteor/babel-preset-meteor.

In your case I would think that it is this transform: https://babeljs.io/docs/plugins/transform-object-rest-spread/

@janowsiany you could test it like this: `babel --plugins transform-object-rest-spread script.js` and then compare.

**Comment by janowsiany** [comment]
@benjamn after upgrade up to `meteor@1.6-beta.30` this issue does not occur anymore. I will close this issue but if you have some spare time you could explain what happened.

**Comment by abernix** [comment]
@janowsiany Meteor 1.6 beta.30 uses Babel 7 (beta.0) and Node 8.5.0.  Node 8.5.0 natively supports the syntax that you're trying to use (without Babel).  It could have been an actual bug in Babel, but @benjamn has also been removing unnecessary Babel plugins which are no longer necessary with Node 8.  It's possible that there was a plugin which was still enabled which was not necessary?

**Comment by janowsiany** [comment]
Right, i know about Babel and Node upgrades but shouldn't Babel transpiled syntax be valid in Node 8.5.0 also(if we assume that a plugin was still enabled)? Also checked if it was Babel bug itself but it wasn't(you can check the repro done with Babel REPL in my very first comment), unless it was a bug in Babel 7th(REPL is running 6.x.x i guess). Anyway, it is cool that it is no longer an issue :zap:. CAn't wait for RC.
