### ISSUE TITLE
Ambiguous error message when creating new user is unclear

### ISSUE THREAD

**Issue by brouwer** [meteor/meteor#9019]
When you configure accounts with ambiguousErrorMessages enabled, and call `Accounts.createUser` with a email/username that is already registered, you get the error `Login failure. Please check your username and password`.

This is coming from the `checkForCaseInsensitiveDuplicates` function in [accounts-password/password_server.js](https://github.com/meteor/meteor/blob/e1099dad19ab9169123797477e8e7c02c6532ec6/packages/accounts-password/password_server.js#L210)

It is probably difficult to come up with an error message here that will not give away information to a potential attacker, but the "Login failed" part is a bit misplaced. I propose a more generic error message here, for example "Something went wrong. Please check your username or email".

Additionally the same function is called when calling `Accounts.addEmail` or `Accounts.setUsername`. I can't really think of a scenario where these would need to be called by an unauthorized user, so there is no need to return ambiguous errors. But that would obviously require a bit more work then simply changing the error message :)

**Comment by dhrubins** [comment]
Yeah, as the one that proposed that PR and initially wrote that message, I completely agree with you: we need a better message there. 

How about "Something went wrong. Please check your credentials." which also gets rid of the word "Login" since some people use different terminology like "Sign In" or "Log In".

**Comment by brouwer** [comment]
Sounds good to me. :thumbsup:
