### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by pkitatta** [meteor/meteor#9024]
![image](https://user-images.githubusercontent.com/17586059/29324140-f6775a1c-8197-11e7-8f4a-146372581a02.png)

Hi Meteorites,

I have been working on an ionic meteor project the can be found here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp

The app was working fine in chrome, firefox , android and ios until I upgraded to meteor 1.5.1, and then the above error occurred. I need to point out that the app still functions well in the browser prior to testing in the android where it now fails and produces the above error. After this error has occurred, proceeding tests on firefox fail. Chrome's behavior is on and off; sometimes the app runs and sometimes it fails depending on whether you first run the tests on android.

Environment
Windows 10
node 6.11.2
npm 3.10.10

package.json

```
 {
  "name": "front1",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "api": "cd api && meteor run --settings private/settings.json",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "meteor-client:bundle": "meteor-client bundle -s api"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "angular2-moment": "^1.6.0",
    "babel-runtime": "^6.25.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic-angular": "3.6.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "meteor-node-stubs": "^0.2.11",
    "meteor-rxjs": "^0.4.7",
    "moment": "^2.18.1",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.3",
    "@types/meteor": "^1.4.4",
    "@types/meteor-accounts-phone": "0.0.5",
    "@types/meteor-publish-composite": "0.0.32",
    "@types/underscore": "^1.8.1",
    "babel-minify": "^0.2.0",
    "meteor-typings": "^1.4.1",
    "tmp": "0.0.33",
    "typescript": "2.3.4",
    "typescript-extends": "^1.0.1"
  },
  "description": "whatsapp: An Ionic project",
  "config": {
    "ionic_webpack": "./webpack.config.js"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {}
    },
    "platforms": []
  }
}

```

issue link on GitHub : https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124

So why do I suspect it is a meteor issue? 
1. It started when I upgraded meteor to 1.5.1
2. Because it starts at the point I install the meteor server in the project - this is when mobile tests start failing.

Can anyone help?

**Comment by sxxymzy** [comment]
+1 Same issue

**Comment by lingboz** [comment]
Hi guys,
We have discussed this in another issue as well:
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/121#issuecomment-322407186

Just attached the link in case anyone is interested and would like to join.

The issue was that we saw different behaviors when using different versions of Meteor, we are using a client blunder to bundle meteor scripts, and those scripts have been used with Ionic cordova. 

but all things worked well until several days ago, we could not load any content on devices.

**Comment by blackjack0v0** [comment]
Runtime Error
can't convert undefined to object
Stack
D/<@http://10.11.40.69:8100/build/polyfills.js:1:3456
_require2<.node_modules["core-js"].modules["_redefine.js"]/_module37.exports@http://10.11.40.69:8100/build/main.js:107133:31
_require2<.node_modules["core-js"].modules["_export.js"]/$export@http://10.11.40.69:8100/build/main.js:106922:29
_require2<.node_modules["core-js"].modules["_typed-array.js"]/_module126.exports@http://10.11.40.69:8100/build/main.js:113074:17
_require2<.node_modules["core-js"].modules["es6.typed.uint8-array.js"]@http://10.11.40.69:8100/build/main.js:112534:13
fileEvaluate@http://10.11.40.69:8100/build/main.js:103074:1
_require@http://10.11.40.69:8100/build/main.js:102957:1
_require2<.node_modules.meteor["ecmascript-runtime-client"]["runtime.js"]@http://10.11.40.69:8100/build/main.js:120105:13
fileEvaluate@http://10.11.40.69:8100/build/main.js:103074:1
_require@http://10.11.40.69:8100/build/main.js:102957:1
@http://10.11.40.69:8100/build/main.js:120112:19
@http://10.11.40.69:8100/build/main.js:120026:2
@http://10.11.40.69:8100/build/main.js:97514:1
__webpack_require__@http://10.11.40.69:8100/build/main.js:20:12
@http://10.11.40.69:8100/build/main.js:97489:72
__webpack_require__@http://10.11.40.69:8100/build/main.js:20:12
@http://10.11.40.69:8100/build/main.js:63:18
@http://10.11.40.69:8100/build/main.js:1:1

**Comment by pkitatta** [comment]
@lingboz Thanks for the added detail.

**Comment by hwillson** [comment]
As discussed in https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/121, this doesn't appear to be a Meteor issue. Closing - thanks!

**Comment by pkitatta** [comment]
Hello hwillson, please don't close this issue. Whereas we might have blamed the meteor-client-bundler, it is becoming clear clear to us the the bundler is only guilty of bundling the meteor packages into one file. To be fair, the changes in the meteor-client.js file are caused by the changes in the meteor packages themselves. Please see the latest comments on the thread. It would be nice for someone from the meteor side to join the discussion. Since some of us are developing in ionic, we hope that the marriage between can last.

**Comment by hwillson** [comment]
Thanks for the update @pkitatta - there still really isn't much to go on here that points conclusively towards this being a Meteor issue. Are you able to put together a small, runnable reproduction that clearly demonstrates this is a Meteor core problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))? If so then I'll be glad to re-open this and lend a hand troubleshooting, but until then I'm leaning towards keeping this closed.

**Comment by pkitatta** [comment]
Hi @hwillson. Sorry I meant to say the latest comments on https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124 and not 121. I am not an advanced developer so please forgive my shifting blame on the different components of this app. One day I might say it's the bundler, the next I may say it meteor or ionic or cordova - I am not 100% sure. We hope that people more advanced can help give an absolute position. Anyway here are my simple fact: One day this (referenced) ionic-meteor project is running well with; meteor@1.5&1.5.1, meteor-client-bundler@0.2.1 and ionic@3, on devices as old as android 4.2.2. The next day we get an error all factors above constant. The meteor-client.js is visibly different in both cases - not that I understand much of the meteor package logic, but I can see the difference. Please see the thread herein for variations in discussion.

Thanks to @lingboz you can have a reproduction of the issue. Please see link below.
"
You can downlowd it and run:

$ git clone https://github.com/lingboz/Ionic2CLI-Meteor-WhatsApp-Minimum-Viable.git
$ cd Ionic2CLI-Meteor-WhatsApp-Minimum-Viable
$ npm install
$ ionic cordova run/emulate android

Running this project on Android 5.1 or ios 10.3.3 will produce the error below:"

I can add that running the project on android <5.1 will produce the error.

**Comment by darkbasic** [comment]
Hi, I'm one of the main contributors of the Ionic2CLI-Meteor-WhatsApp tutorial.
I don't use core-js directly in the tutorial, so this is probably an issue in core-js itself or in the way that Meteor uses it.
It would be nice if someone manages to reproduce it in a simple example using only the MeteorCLI.
