### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9029]
I have migrated Meteor App from 1.2.1 to 1.5.1.

When using this app for a while, I get this error in server console:

```
=> Client modified -- refreshing (x3)
W20170821-12:13:02.275(5)? (STDERR) /home/mypc/.meteor/packages/meteor-tool/.1.5.1.rp2652++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170821-12:13:02.276(5)? (STDERR)                         throw(ex);
W20170821-12:13:02.277(5)? (STDERR)                         ^
W20170821-12:13:02.277(5)? (STDERR) 
W20170821-12:13:02.278(5)? (STDERR) RangeError: Maximum call stack size exceeded
=> Exited with code: 1
=> Client modified -- refreshing              
=> Meteor server restarted
```

What could be the issue? Why is my app crashing?

**Comment by MartiniHenry1988** [comment]
@abernix  Thanks for the response, As you mentioned "that something is stuck in a loop somewhere",
I have wrote a code where my query runs after each 15 seconds which check that rather the record is expired or not by comparing the date of a record with the current date, something like this:

```
Meteor.startup(function () {

   cronJobClass = {
    
      startCronJobs: function (){

         Meteor.setInterval(function(){				
			   
            Articles.update({'addedOn.timeStamp': { $lt: new Date().getTime(), flag: 0 }, { $set: { flag: 1 } });
			
         }, 15000);
      } 
   };
});
```

And after that when my app start I call cronJobClass.startCronJobs();

Could that be the issue?

**Comment by abernix** [comment]
I wouldn't expect that code to be causing it.  For the purposes of debugging this, you may have better luck running Meteor 1.6 (which is currently only in _beta_, not officially released) and running `meteor debug` which will allow you to use the new Node.js Chrome DevTools debugging experience.  In there, you'll be able to "Pause on exceptions" and maybe get a better idea of what's going on!

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9029#issuecomment-324007845, without a reproduction this is very difficult to troubleshoot. Closing for now - thanks!
