### ISSUE TITLE
fields specifier doesn't work well for sub-fields

### ISSUE THREAD

**Issue by belisarius222** [meteor/meteor#903]
repro app here:
https://github.com/belisarius222/meteor-pub-fields-test

The problem is that if I publish a nested field, like 'profile.general', the Meteor server will then ignore subsequent publish functions that publish either a) other sub-fields, like 'profile.specific', or b) the entire top-level field (`profile`).  This behavior is undocumented and caused me some problems.   

For performance reasons I'd really like to be able to publish certain parts of all user's profiles in one publish function, and then publish the rest of the profile just for one user at a time using a different publish function.  This works for top-level fields, but a lot of things end up getting stored in `user.profile` since it's editable client-side without custom methods, and not all of the sub-fields there need to be sent from the server on initial page load.

**Comment by Siyfion** [comment]
Well this caught me out completely! I still think that the docs need to be improved, as while it mentions conflicting values, it doesn't say that ***only*** top-level fields are checked. This needs to be made *much, much, much* clearer.

**Comment by BudgieInWA** [comment]
The docs are ***still*** insufficient.
