### ISSUE TITLE
Switch to Nodemailer 4 causes unsecure smtp email to fail. 

### ISSUE THREAD

**Issue by njneer** [meteor/meteor#9032]
Recently updated Meteor to 1.5 and noticed our emails stopped working. Server reports error of 'unable to get local issuer certificate'. Our corporate email relay server does not require authentication. 
MAIL_URL = 'smtp://mail.corp.com:25' had no issues prior to Nodemailer 4 being introduced.

**Comment by njneer** [comment]
You can pass Nodemailer options via MAIL_URL. Issue was with self-signed certificate. For anyone else's reference url change was: MAIL_URL = 'smtp://mail.corp.com:25?tls.rejectUnauthorized=false', check nodemailer docs for available options.

**Comment by abernix** [comment]
Glad you got it fixed and thanks for reporting back with your findings!
