### ISSUE TITLE
Cannot run meteor in Windows 10: Cannot find module C:\Users\..\npm\node_modules\meteor\app\meteor\meteorj.s

### ISSUE THREAD

**Issue by lcnvdl** [meteor/meteor#9050]
Yesterday I've downloaded and installed meteor from the official website (I think that is the last stable version) in Windows 10.

After the installation, I open a new CMD window, and type:
meteor create whatsapp

Then I get:

> module.js:340
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\Users\Lucho\AppData\Roaming\npm\node_modules\meteor\app\meteor\meteor.js'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:289:25)
>     at Function.Module.runMain (module.js:467:10)
>     at startup (node.js:136:18)
>     at node.js:963:3

**Comment by abernix** [comment]
I believe this has to do with a conflicting global installation in your `%AppData%\npm\` (as indicated by the path above).  What if, for the sake of debugging, you temporarily move your `C:\Users\Lucho\AppData\Roaming\npm` directory to a different location (you can move it back afterwards, of course!).

**Comment by hwillson** [comment]
We haven't heard back regarding the additional debugging steps requested in https://github.com/meteor/meteor/issues/9050#issuecomment-325900350, so closing for now. Thanks!
