### ISSUE TITLE
Are there ETAs for Meteor releases?

### ISSUE THREAD

**Issue by yogiben** [meteor/meteor#9051]
I see the [roadmap](https://github.com/meteor/meteor/blob/devel/Roadmap.md) and the various [releases](https://github.com/meteor/meteor/releases) but I'm unable to find an estimation of when the version will be released.

Is there such an estimation and, if so, where can I find it?

**Comment by StorytellerCZ** [comment]
Meteor does not have a set release cycle, hence the next version will be released when ready.

**Comment by abernix** [comment]
The best bet is to check the [current pull requests](https://github.com/meteor/meteor/pulls)!  If you'll review the ["Release 1.5.2" pull request](https://github.com/meteor/meteor/pull/8913) you'll see it should be out very soon.
