### ISSUE TITLE
Client side idStringify error (objects other than ObjectID) also with _id="" after core packages upgrade

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#9060]
**The version of Meteor showing the problem.**
Meteor version: 1.5.1

Packages updated:

```
accounts-base          upgraded from 1.3.1 to 1.3.2
babel-compiler         upgraded from 6.19.4 to 6.20.0
boilerplate-generator  upgraded from 1.1.1 to 1.2.0
ddp-client             upgraded from 2.0.0 to 2.1.0
ejson                  upgraded from 1.0.13 to 1.0.14
minifier-js            upgraded from 2.1.1 to 2.1.2
minimongo              upgraded from 1.2.1 to 1.3.0
modules                upgraded from 0.9.4 to 0.10.0
mongo                  upgraded from 1.1.22 to 1.2.0
mongo-dev-server       added, version 1.0.1
promise                upgraded from 0.8.9 to 0.9.0
webapp                 upgraded from 1.3.17 to 1.3.18
```

**The last version of Meteor where the problem did _not_ occur (if applicable)**
Same version before the update.

**The operating system you're running Meteor on.**
MacOs, but problem also occurs on Ubuntu 16.04.2 LTS Linux local and production. 

**The expected behavior**
Before the update there were no problems with calling `collection.findOne("")` or `collection.findOne({_id:""})`. I expect the function `findOne` to return a falsey value, such as null or undefined.

**The actual behavior.**
Throws error on `collection.findOne({_id:""})` 

```
Error: Meteor does not currently support objects other than ObjectID as ids
idStringify — 436bf8d602463537fc560f5794e92e560aa45dc0.js:56258
get — 436bf8d602463537fc560f5794e92e560aa45dc0.js:56013
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:57512
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:57443:156
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:57495
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:57393
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:45:14769
e — 436bf8d602463537fc560f5794e92e560aa45dc0.js:57658:119
findOne — 436bf8d602463537fc560f5794e92e560aa45dc0.js:62014
```
Is this behavior to be expected now with the updated packages?

I checked the [mongo 2.6 merge](https://github.com/meteor/meteor/pull/8815) and it seems, that it introduces new _id handling?

**A simple reproduction!**
Create a new Meteor project with the above package versions and call findOne({_id:""}) on a arbitrary client side collection.

**Comment by klaussner** [comment]
Here is a reproduction repo: https://github.com/klaussner/meteor-issues/tree/9060. It looks like this bug was introduced by #8893, specifically [this commit](https://github.com/meteor/meteor/commit/92555c32ba40e969a0bd905975961326d2365f1e). The following line assigns the selector object instead of the `_id` to `this._selectorId` if the `_id` in the selector object is an empty string:

https://github.com/meteor/meteor/blob/92555c32ba40e969a0bd905975961326d2365f1e/packages/minimongo/cursor.js#L14
