### ISSUE TITLE
File modifications issues

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#9061]
Meteor 1.5.2
It still happens that modifications do not get picked up always. It may be a duplicate of this [bug](https://github.com/meteor/meteor/issues/9054).
As a workaround, I'm still using METEOR_WATCH_PRIORITIZE_CHANGED=false

**Comment by davidecantini** [comment]
I re-installed 1.5.2, and for some reasons (maybe something went wrong during the first upgrade to 1.5.2), now I don't see that strange behavior anymore. 
So for now I'm closing this. I'll keep on monitoring it and in case, hopefully not, re-open it.

**Comment by abernix** [comment]
Thanks for reporting this!  As you've alluded to yourself, it's very likely the same issue.  Let's keep the conversation in #9054 since this issue alone doesn't provide any suggestions for a reproduction.  If you can provide more precise information, please add it to the other issue! Thanks!
