### ISSUE TITLE
loginExpirationInDays: null, still expiring

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#9066]
### System Info
Meteor version 1.5.2
Manjaro Linux

### Description
I just upgraded our app from Meteor 1.5.1 to 1.5.2
According to the changelog:
```
Accounts.config no longer mistakenly allows tokens to expire when the loginExpirationInDays option is set to null. Issue #5121 PR #8917
```
Logins should expire when `loginExpirationInDays` is set to `null`. Which was already working for us on 1.5.1 and before(eventually it was the default 90 days, and not infinity though). Instead, users get now logged out immediately when the page reloads.

**The expected behavior.**
Sessions shouldn't expire.
**The actual behavior.**
Sessions expire.
**Reproduction**
User get's logged out on page reload
```
Accounts.config({
  loginExpirationInDays: null,
})
```

User doesn't get logged out on pagereload:
```
Accounts.config({
  loginExpirationInDays: 90,
})
```

Best regards,
Lukas

**Comment by jasonswanson** [comment]
This is happening to our application as well with "loginExpirationInDays: null" and Meteor 1.5.2. In addition, we have pages that open up in a new tab, and when this additional tab is opened, the user is now logged out on all tabs immediately.

**Comment by zimme** [comment]
I do believe @stevenhao and #8917 didn't account for the return value, `Infinity`, being used to create a `new Date`, which results in `Invalid Date` and being used in subtractions which results in `-Infinity`. I'm looking at the following functions. https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L237-L249

**Comment by abernix** [comment]
Your diagnosis sounds spot on to me, @zimme.

**Comment by hwillson** [comment]
This problem is being reported in other related issues, like https://github.com/meteor/meteor/issues/9082. This could potentially be a serious bug, so I've elevated the bug status here and marked this as `pull-requests-encouraged`. If anyone is interested in helping out, we'll definitely review a PR for this - thanks!

**Comment by hwillson** [comment]
Quick update - PR https://github.com/meteor/meteor/pull/9113 should help with this.
