### ISSUE TITLE
Bug on windows installation

### ISSUE THREAD

**Issue by eristavi** [meteor/meteor#9071]
If the installation is on C drive and my project folder is in D drive application is not able to start or run the server. Problem is the following

Windows is not recognizing comand such as cd ~/D:/my_app_folder.

**Comment by abernix** [comment]
`cd ~/D:/my_app_folder` would be attempting to go into a `D:` folder in your home directory.  (i.e. `C:\Users\USERNAME\D:\my_app_folder`), no?

Could you please provide more clear information about what you believe to be the problem?  Can you include output from your terminal and an error message?  Also, are you using PowerShell or Cygwin, Windows Subsystem for Linux, etc?

Thanks!

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9071#issuecomment-328762156, without more details explaining what you're trying to do, there isn't much we can do here to help. Closing for now - thanks!
