### ISSUE TITLE
Cordova build fails at AAPT

### ISSUE THREAD

**Issue by gsadhas** [meteor/meteor#9076]
Meteor cordova build fails at AAPT. I'm not sure what I'm doing wrong here. I'm using,
Meteor 1.3.4.4
SDK tools 23.0.1
Build tools 23.0.1
Platform tools 23.0.1 
OS - Mac OS sierra

I think the issue is similar to #6761  Any help is appreciated, thanks!

**Error log:**

While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/xxx/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.

   /Users/xxx/.meteor/local/cordova-build/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3
   : AAPT: Error retrieving parent for item: No resource found that matches the
   given name
   'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
   

   /Users/xxx/.meteor/local/cordova-build/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4
   : AAPT: Error retrieving parent for item: No resource found that matches the
   given name 'android:TextAppearance.Material.Widget.Button.Colored'.
   
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':processDebugResources'.
   > com.android.ide.common.process.ProcessException:
   org.gradle.process.internal.ExecException: Process 'command
   '/Users/xxx/Library/Android/sdk/build-tools/23.0.1/aapt'' finished with
   non-zero exit value 1
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or
   --debug option to get more log output.
   Error code 1 for command:
   /Users/xxx/.meteor/local/cordova-build/platforms/android/gradlew
   with args:
   cdvBuildDebug,-b,/Users/xxx/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
   undefined
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)
                                              
/Users/xxx/.meteor/packages/fourseven_scss/.3.8.1.19wbc3j++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
ExitWithCode:1

**Comment by gsadhas** [comment]
Team, It would be really helpful if someone can shed some light on this issue. I reinstalled the meteor and Android tools but still I'm getting the same issue.

**Comment by abernix** [comment]
While I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.  It's really the only way we can ensure we're testing the same exact scenario as you're encountering.  [Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) 

It would also be worthwhile to include:

 * What version of XCode you're using?
 * How/when this problem started occurring?  (I'm assuming it used to work?)
 * Whether you can reproduce the problem in a newer version of Meteor.  (Meteor 1.3 is quite old.)

**Comment by gsadhas** [comment]
@abernix Sure, let me try your suggestions and update the issue. Thank you for the help!

**Comment by gsadhas** [comment]
@abernix I could not reproduce the issue.

What version of XCode you're using?
 XCode 8.* version

How/when this problem started occurring?
The issue occurred when I uninstall and install the same meteor package.

Whether you can reproduce the problem in a newer version of Meteor.
No, I could not reproduce this in Meteor 1.5. I didn't see any issue.

I did a clean install and upgraded the application to Meteor 1.5. Few of the working source codes were broken and it works after the fix.  May be someone can reproduce the issue, if not, clean install is the fix.

**Comment by hwillson** [comment]
Based on the comments in https://github.com/meteor/meteor/issues/9076#issuecomment-337049490, it sounds like this issue has been resolved. Closing - thanks!
