### ISSUE TITLE
[server-render] Ability to pass navigator / userAgent to the client

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#9079]
I am using the `server-render` package to do SSR on my React-based Meteor app. It's been working great!

I just recently installed the `material-ui` NPM package and my server console started logging the following warning:

```
Warning: Material-UI: userAgent should be supplied in the muiTheme context for server-side rendering.
```

I believe what this is asking, is that the server is rendering my React code without the presence of the `navigator` or `navigator.userAgent` variables, so what the server is rendering is different from what the client is rendering (which defeats the purpose of SSR). (See: https://stackoverflow.com/a/38100609/3810402)

It looks like the `sink` object in `server-render` does not have a `headers` key where I can pick up the user agent on the server, and use that when rendering my React tree. Is this correct? Is there another way to achieve this, or is this indeed a bug / feature request for `server-render`?

**Comment by joncursi** [comment]
In order to get this issue to "go away", I am using this for now:

```js
const muiTheme = getMuiTheme({
  userAgent: Meteor.isClient
    ? navigator.userAgent
    : 'all',
});
```

But I think we should be able to do better than specify the catch-all `userAgent: 'all'` on the server and actually specify the client's user agent.

**Comment by abernix** [comment]
The user agent is only available in a "tidied-up" state [as `sink.request.browser`](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L108-L115), calculated based on the `user-agent` header (thanks, in part, to parsing done by [`useragent`](//npm.im/useragent)), which returns something along the lines of:

```js
{ name: 'chrome', major: 61, minor: 0, patch: 3163 }
``` 

It seems reasonable to open this up to have the full `user-agent` available (and, related, probably other headers too) unless `material-ui` supports something along the lines of I've shown above.

**Comment by abernix** [comment]
We may want to maintain some sort of isomorphic API between the two so it's not `req.headers['user-agent']` in one place and `navigator.userAgent` in the other?

**Comment by hwillson** [comment]
Thanks for suggesting this @joncursi. Would you mind adding your request to the related https://github.com/meteor/meteor-feature-requests/issues/174 feature request? It will help if we can keep all of the requested `server-render` `sink` object changes together.
