### ISSUE TITLE
meteor export default 1.5.2

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9088]
meteor 1.5.2

/imports/collections.js

```js
const Projects = new Mongo.Collection('projects')
const Tasks = new Mongo.Collection('tasks')
const Members = new Mongo.Collection('Members')

export default {
  Projects,
  Tasks,
  Members,
}
```

import { Projects } from '/imports/collections'

console.log(Projects)   undefined ?

**Comment by klaussner** [comment]
Try this:

```js
export {
  Projects,
  Tasks,
  Members,
}
```

**Comment by hwillson** [comment]
Not an issue with Meteor (see https://github.com/meteor/meteor/issues/9088#issuecomment-329111354). Closing - thanks!
