### ISSUE TITLE
Meteor hangs at starting your app

### ISSUE THREAD

**Issue by Harrian** [meteor/meteor#9093]
I'm having some issues running a project on a Ubuntu 16.04.3 LTS VM.  The project "hangs at starting your app" and never continues to launch.

mongod and node processes are running in the background and do appear to be doing things.

fresh example projects do run, and another large project I have runs as well.

`meteor reset` doesn't appear to help

reverting to older versions of the project that were known good do not work

when running with `METEOR_PROFILE=1 METEOR_LOG=debug meteor run --verbose` I get stuck at the following `I20170914-21:23:32.836(-7)? | (#1) Profiling: Server startup`

**Comment by hwillson** [comment]
Sorry to hear @Harrian - any chance you could share the project that's hanging (or a scaled down reproduction)?

**Comment by abernix** [comment]
Does the same project work on a different platform?  Have you tried deleting the app's `.meteor/local` directory?

**Comment by Harrian** [comment]
@hwillson The project isn't doing anything unique yet so I've gone ahead and made it public for now.  (It's useless if I can't work on it anyway) [MeteorChampSelect](https://github.com/Harrian/MeteorChampSelect)

@abernix I have tried running the project on my windows machine as well, had the same issue.  Even with earlier versions of the project. I've also tried rebuilding the my environment in a second VM and got the same issue.

**Comment by hwillson** [comment]
Thanks for sharing your app @Harrian - this is an application error. You have an infinite loop that's being called on server startup:

https://github.com/Harrian/MeteorChampSelect/blob/a90d27a9770e69b837f37c2d0e7f5c98081c5c01/server/methods.js#L15-L16

Comment out that `while` loop and the app will start properly. Closing as this isn't a Meteor issue. Thanks!

**Comment by Harrian** [comment]
@hwillson Doh! Thanks for spotting that!  The API i'm calling to mush have been upgraded without me noticing!
