### ISSUE TITLE
[GALAXY] : CLI warning before deleting deployment

### ISSUE THREAD

**Issue by mikepaszkiewicz** [meteor/meteor#9096]
Tonight I learned the hard way that ```meteor deploy xxx.meteorapp.com -D``` doesn't mean deploy to Galaxy in debug mode. Fault's on me for not checking the docs - either way, a simple prompt (plus perhaps a --force option for CI purposes) would be a big value add for those running production Galaxy deployments with high SLA expectations.

**Comment by abernix** [comment]
Eeps.  I'm sorry you had to experience that! Your request seems super reasonable, but please open this in the [feature requests repository](//github.com/meteor/meteor-feature-requests/issues) so we can keep track of it, get it prioritized and enable contributors to find/work on it.
