### ISSUE TITLE
[1.5.2]Cannot really remove jQuery package

### ISSUE THREAD

**Issue by ShinyLeee** [meteor/meteor#9102]
Since I don't need jQuery in my project I just run `meteor remove jquery` and check the bundle-visualizer result, but why jQuery is still in the bundle?

I can not found jQuery in .meteor/package but in .meteor/versions jQuery is still here.

After I tried delete it in .meteor/versions and run app again,  that thing happens, it added jQuery automatically??!
![image](https://user-images.githubusercontent.com/13724426/30520938-81615126-9be9-11e7-9e35-98ab92e35c43.png)

So is there any way to remove jQuery completely??

**Comment by Deadly0** [comment]
@ShinyLeee Run `meteor list --tree` and you can find with package use `jquery` as dependency

**Comment by ShinyLeee** [comment]
@Deadly0 Thanks, seems I can not get rid of jQuery and Blaze... So many package depend on them...

**Comment by coagmano** [comment]
Then that's dependent on your packages.

Having Meteor without jQuery is as easy as:
```
$ meteor create --bare
```
