### ISSUE TITLE
[1.5.0] Adding local package doesn't work if package is referenced in another package

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9104]
Since a couple of weeks, I'm facing a strange phenomenon with Meteor 1.5.0. When I add a dependency on a new local package to one of my existing local packages, Meteor won't be able to find this package, although it is in the packages/ folder and has a package.js file with the correct package name.

If the server is running at that time, it will break because of this "missing package". If I try to restart it, it also complains about not being able to find the package. If I do a `meteor reset`, however, Meteor is able to find the new package as expected.

I tried to purge the ~/.meteor folder, just in case, but this didn't help either. The only workaround is to do a `meteor reset`, which is cumbersome since Meteor takes a lot of time then to rebuild things.

**Comment by abernix** [comment]
Are you sure this wasn't fixed in more recent 1.5.x releases, specifically Meteor 1.5.2?  This sounds similar to https://github.com/meteor/meteor/pull/9007 (or another issue which I'm recalling, but can't find the issue number for at the moment).

**Comment by derwaldgeist** [comment]
Well, I don't know. I cannot update to newer versions because of #8950. Although I tried for hours to build a reproduction repo for the #8950, I wasn't able to do that. So I am "hoping" someone else will run into 8950 and be able to provide a reproduction repo. :-/

**Comment by sebakerckhof** [comment]
Seems like a duplicate of https://github.com/meteor/meteor/issues/7721

best known workaround is to just delete : `.meteor/local/resolver-result-cache.json` so you don't have to do an entire `meteor reset`

**Comment by derwaldgeist** [comment]
@sebakerckhof Yes, that's a duplicate. Thanks for pointing this out. Closing this issue now.

**Comment by mitar** [comment]
Great workaround for deleting `.meteor/local/resolver-result-cache.json`. Finally I know how to fix this.
