### ISSUE TITLE
Issues regarding Lean node starter file

### ISSUE THREAD

**Issue by nirvanateq** [meteor/meteor#9114]
TypeError:/learn-node/views/layout.pug:4
[💻]     2| html
[💻]     3|   head
[💻]   > 4|     title= `${title} | ${h.siteName}`
[💻]     5|     link(rel='stylesheet', href='/dist/style.css')
[💻]     6|     link(rel="shortcut icon" type="image/png" href="/images/icons/doughnut.png")
[💻]     7|     meta(name="viewport" content="width=device-width, initial-scale=1")
[💻]
[💻] Cannot read property 'siteName' of undefined

**Comment by hwillson** [comment]
Hi @nirvanateq - sorry to hear you're having trouble. Unfortunately you haven't provided enough details here for us to be able to help out. Please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug). Thanks!
