### ISSUE TITLE
Server side only slows down over time on 1.5.2

### ISSUE THREAD

**Issue by aadamsx** [meteor/meteor#9120]
### This bug report:
- Meteor 1.5.2
- The last version of Meteor where the problem did _not_ occur: Meteor 1.4 - 1.5.1.
- The operating system you're running Meteor on: Production AWS Ubuntu EC2 Instance.
- The expected behavior: Keep the same level of performance under similar conditions.
- The actual behavior: Slowed down to a crawl until restarted the instance, then all normal.
      

### Meteor packages:
```
accounts-base          1.3.2
accounts-password      1.4.0 
check                  1.2.5
ecmascript             0.8.2
edgee:slingshot        0.7.1
email                  1.2.3 
es5-shim               4.6.15
meteor-base            1.1.0
mongo                  1.2.0*
peerlibrary:aws-sdk    2.4.9_1 
shell-server           0.2.4
standard-minifier-css  1.3.4*
standard-minifier-js   2.1.1 
xmlbuilder             2.5.15 
```

### package.json:
```
  "dependencies": {
    "babel-runtime": "^6.25.0",
    "bcrypt": "^1.0.2",
    "body-parser": "^1.17.2",
    "casual": "^1.5.14",
    "connect": "^2.30.2",
    "connect-route": "^0.1.5",
    "cors": "^2.8.4",
    "express": "^4.15.4",
    "helmet": "^3.8.1",
    "meteor-node-stubs": "~0.2.4",
    "moment": "^2.18.1"
  }
```

I'm running an Meteor based Express Web API in production (I only use the Server side) and have for the last few months without issues.  I think this particular Meteor-Express Web API started out on Meteor 1.4.  I recently upgraded to Meteor 1.5.2 (from Meteor 1.5.1), and was hit just by a large slow down on the instance.  

When a client made a request to the Express Web API, the code still worked as designed (I could trace the path with my logging turned on), but the process was much slower -- to the point were it timed out on the client.  

I hadn't changed or deployed on that sever for at least a month, so I decided to just restart the instance.  After that I made another call to the same enpoint and it was lighting fast as usual. 

NOTE: I would think replicating something like this would be difficult, as it doesn't happen until much time has passed.  If there's a tool I can use to see if there's a leak somewhere, please let me know and I'll look into it.

**Comment by hwillson** [comment]
Thanks for reporting this @aadamsx. As you mentioned, replicating and troubleshooting something like this is very difficult, especially on this side of things, without some kind of a reproduction (or access to your application code). Unfortunately, there isn't much we can do to help here without more concrete (runnable/repeatable) details. Maybe try reaching out on the [forums](https://forums.meteor.com) for troubleshooting ideas? Closing for now (but please post back if you're able to reliably reproduce this and can supply a reproduction, and we'll happily re-open). Thanks!
