### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9121]
I am getting this error in browser console when the page loads:

`WARNING: Tried to load angular more than once.`

I was using Meteor 1.2.1 and recently I have migrated to 1.5.2, but this error still persists.

I have uploaded my working project on GIT repo:

[https://github.com/MartiniHenry1988/meteor-demo-app](https://github.com/MartiniHenry1988/meteor-demo-app)

What could be the possible reason?

I also face Range Error on server console sometimes, are these related? I am afraid if my app is performing some recursive operations which might be stucked in an infinite loop. Because my Apps behavior is very slow, and it gets slower with time

Here is the reference of that issue which I still face: 

[RangeError: Maximum call stack size exceeded](https://github.com/meteor/meteor/issues/9029)

**Comment by hwillson** [comment]
Hi @MartiniHenry1988 - For the `WARNING: Tried to load angular more than once.` message, I'd suggest taking a look over in the `angular-meteor` repo. There are [several issues](https://github.com/Urigo/angular-meteor/issues?q=is%3Aissue+%22Tried+to+load+angular+more+than+once.%22+is%3Aclosed) in that repo mentioning this problem, all of which have been closed, so you'll likely find the answer there somewhere.

Regarding your `RangeError` issue, it's difficult to say if these problems are related. I've tried your repro and don't see any `RangeError`'s in the console, so there isn't much we can help with there I'm afraid. As mentioned in https://github.com/meteor/meteor/issues/9029, if you can provide a reproduction that shows this error, we'll take a look.
