### ISSUE TITLE
Connection delay causes issues

### ISSUE THREAD

**Issue by devilj** [meteor/meteor#9127]
i'm completely new to MeteorJS, just looking at demos and poking around. it is possible that i'm just missing something really basic.
i'm using meteor with angular-ui-router. if i start with a state that loads data into a controller, i run into issues because DDP has not initialized yet. this is similar to what was described in https://stackoverflow.com/questions/15129827/meteor-how-can-i-tell-when-the-database-is-ready

relevant part of routing config:

                resolve: {
                    location: ($stateParams) => {
                        console.log('find', $stateParams);

                        let handle = setInterval(function () {
                            console.log(Meteor.status().connected, Meteor.status().status);
                            console.log( !!Locations.findOne({code: $stateParams.code}) ? 'found' : 'not found' );
                        }, 100);

                        setTimeout(function () {
                            clearInterval(handle);
                        }, 2000);

                        console.log(Meteor.status().connected, Meteor.status().status);
                        return Locations.findOne({code: $stateParams.code});
                    }
                }

and the output is

> 
> false "connecting"
> false "connecting"
> not found
> true "connected"
> not found
> true "connected"
> not found
> true "connected"
> found
> true "connected"
> found

my question is:
do i understand correctly that the problem here is that for things to work as expected they must happen in this sequence:
1. web socket connection is initiated
2. web socket connection is ready to use
3. minimongo is refreshed
4. collection.findOne
and 4. is running before 3?
if so, what is the suggested workaround?

**Comment by hwillson** [comment]
Hi @devilj - Welcome to the wonderful world of Meteor! Just a heads up, usage questions like this are much better suited on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`). You'll usually get a faster response to this kind of question at one of those locations. GitHub issues are reserved for Meteor bugs, so issue triagers give those types of issues priority. In your case I'd also suggest reading over the [Publications and Data Loading](https://guide.meteor.com/data-loading.html) section of the Guide, in particular the [Subscription readiness](https://guide.meteor.com/data-loading.html#readiness) section. That should help explain what's happening. Best of luck!
