### ISSUE TITLE
Uncaught ReferenceError in mobx.js on production

### ISSUE THREAD

**Issue by jaqua** [meteor/meteor#9128]
While developing the meteor application (reactJS) I do not get any error. But after doing
`meteor build` I'm deploying the node application to a docker container, the application throws the error:

    Uncaught ReferenceError: Ue is not defined at mobx.js

[Screenshot](https://imgur.com/wYR4biN)

I do not understand where `mobx.js` comes from. As there is no problem while developing,
I really don't know where to start fixing this issue.

I found the issue #8537 which also apears only on production. It's not the exact thing, but likley the same...

I am using meteor version 1.5.2

    meteor-base@1.1.0                # Packages every Meteor app needs to have
    mobile-experience@1.0.4          # Packages for a great mobile UX
    mongo@1.2.0                      # The database Meteor supports right now
    reactive-var@1.0.11              # Reactive variable for tracker
    session@1.1.7
    jquery@1.11.10                   # Helpful client-side library
    tracker@1.1.3                    # Meteor's client-side reactive programming library

    standard-minifier-js@2.1.1       # JS minifier run for production mode
    es5-shim@4.6.15                  # ECMAScript 5 compatibility for older browsers.
    ecmascript@0.8.2                 # Enable ECMAScript2015+ syntax in app code
    shell-server@0.2.4               # Server-side component of the `meteor shell` command
    static-html
    react-meteor-data
    random

    fourseven:scss
    less@2.7.9
    juliancwirko:postcss
    semantic:ui

    aldeed:simple-schema
    check@1.2.5
    mdg:validated-method
    tunifight:loggedin-mixin

    universe:i18n

    accounts-password@1.4.0
    alanning:roles

    ostrio:files                     # Meteor Files
    dynamic-import@0.1.1

**Comment by jaqua** [comment]
Solved the problem by replacing `standard-minifier-js@2.1.1` with `abernix:standard-minifier-js`.

I don't know the difference between both packages, but I found multiple issues with similar problems. So maybe at some time the default minifier gets fixed for that.

**Comment by hwillson** [comment]
Glad to hear it's working @jaqua - the changes in `abernix:standard-minifier-js` were merged into Meteor via PR https://github.com/meteor/meteor/pull/8698. They haven't been released yet, but will be coming shortly. Given that the fix for this is coming (and you've found a workaround until it's released), I'll close this off. Thanks!
