### ISSUE TITLE
import function does not handle variable argument

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9129]
This new import capability is Awesome!  But...

If I pass a string argument to the import function, import fails to find the import file.

### Environment
- Meteor 1.5.2
- Windows 10 v1703 (OS Build 15063.608)

### Repro
1. meteor create testImport
2. cd testImport
3. Create 2 test import files `test1.js` & `test2.js` each with just a console.log statement.
```
test1.js: console.log('test1 imported');
test2.js: console.log('test2 imported');
```
4. Add code to import these files on a button click:
```
  'click button'(event, instance) {
    // increment the counter when button is clicked
    instance.counter.set(instance.counter.get() + 1);
    import('../imports/test1');
    let importPath = '../imports/test2';
    import(importPath);
  },
```
5. Run meteor project and click the button

### Result
test2 failed and test1 succeeded.
```
Uncaught (in promise) Error: Cannot find module '../imports/test2'
    at makeMissingError (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:231)
    at Function.require.resolve (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:263)
    at Module.resolve (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:121)
    at modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:183
    at meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:1117
    at <anonymous>
test1.js:1 test1 imported
```

### Expected
Both test1 & test2 to properly import.  Even if test2 path is defined by a variable.

### Workaround
I suspected there was some sort of static analysis going on so I added a unreachable call to import to the file with a and it worked with the path as a variable:

```
Template.hello.events({
  'click button'(event, instance) {
    // increment the counter when button is clicked
    instance.counter.set(instance.counter.get() + 1);
    import('../imports/test1');
    let importPath = '../imports/test2';
    import(importPath);
  },
});

function nevercalled() {
  import('../imports/test2');
}
```
I took a look at the app bundle and noticed that there is a reference to any potentially loaded files in it:
```
"imports":{"test1.js":[],"test2.js":[]}}
```
Without the unreachable import of test2.js it does not show up in that declaration.
### Request

Maybe provide a way to prime the import functionality outside of declaring an unreachable function.  Maybe in `package.json`?

My application supports dynamically extending my client application and the dynamic import capability is a very useful addition to enable more scenarios.

Thanks!

**Comment by klaussner** [comment]
This is a design decision and not a bug, see https://github.com/meteor/meteor/issues/8744#issuecomment-305590558. However, there's a related feature request for supporting dynamic paths: https://github.com/meteor/meteor-feature-requests/issues/167.

Maybe the compiler should output a warning if `import(...)` isn't used with a string constant, given how often this issue comes up. :sweat_smile:
