### ISSUE TITLE
Stuck on updating from 1.5 to 1.5.2

### ISSUE THREAD

**Issue by lampe** [meteor/meteor#9130]
### Problem
When running `meteor update` the process is hanging at `Selecting package Versions`.

* OS: Ubuntu 16.04.1 
* Latest meteor version where it worked 1.5

### CLI Output
```
Opening db file /home/michael_lazarski_2.dev-2/.meteor/package-metadata/v2.0.1/packages.data.db
Local package version is up-to-date: meteor-tool@1.5.0
Opening db file /home/michael_lazarski_2.dev-2/.meteor/package-metadata/v2.0.1/packages.data.db
In remote catalog refresh
Returning sync token:                         
{"lastDeletion":1409018311766,"format":"1.1","packages":1506271904408,"versions":1506324372613,"builds":1506324375161,"releaseTracks":1488939052468,"releaseVersions":1506271793311}
Adding syncToken:                             
{"lastDeletion":1409018311766,"format":"1.1","packages":1506271904408,"versions":1506324372613,"builds":1506324375161,"releaseTracks":1488939052468,"releaseVersions":1506271793311}
Local package version is up-to-date: meteor-tool@1.5.2
Opening db file /home/michael_lazarski_2.dev-2/.meteor/package-metadata/v2.0.1/packages.data.db
In remote catalog refresh
Returning sync token:                         
{"lastDeletion":1409018311766,"format":"1.1","packages":1506271904408,"versions":1506324372613,"builds":1506324375161,"releaseTracks":1488939052468,"releaseVersions":1506271793311}
Adding syncToken:                             
{"lastDeletion":1409018311766,"format":"1.1","packages":1506271904408,"versions":1506324372613,"builds":1506324375161,"releaseTracks":1488939052468,"releaseVersions":1506271793311}
| (#1) Profiling: ProjectContext prepareProjectForBuild
   Selecting package versions  
```

This was run with `METEOR_PROFILE=100` and `METEOR_LOG=debug` but it also happens if we don't pass this. 

This is a big project with a lot of `METEOR_PACKAGES` and `./packages` and atmosphere packages.

On Small Projects I can't reproduce it. So no `simple` reproduction.

**Comment by hwillson** [comment]
It would be great to know if the update process does eventually finish, if you leave it running for a while. Have you tried leaving it running @lampe?

**Comment by crapthings** [comment]
is METEOR_LOG=debug equal to meteor --verbose ?  if not i suggest u do these

1. check your hosts if any warehouse.meteor in their, remove it
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
```

2. stop upgrade process and revert your meteor update from git.
ensure .meteor/versions and .meteor/packages like before.
and you just change meteor verison in this file .meteor/release to METEOR@1.5.2
then  meteor --verbose see where it stucks

**Comment by hwillson** [comment]
We haven't heard back regarding the comments in https://github.com/meteor/meteor/issues/9130#issuecomment-331886625, so closing for now. Thanks!
