### ISSUE TITLE
[1.5.2] The handle(42) returned by watching [file] is the same with an already watched path([file])

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9131]
After upgrading to 1.5.2 I get a lot of these kind of warnings in the console:

`The handle(XX) returned by watching [file] is the same with an already watched path([file])`

The common thing is that it's always for files inside the `.npm/package/node_modules' folder of a local meteor package, e.g.:
`/home/seke/work/wc/packages/barco_edu/.npm/package/node_modules/lodash`

**Comment by hwillson** [comment]
Might be related to https://github.com/meteor/meteor/issues/5923, and https://github.com/meteor/meteor/commit/35da19ab4e2c3ca297c7e6aae55a68fc079900a8.

**Comment by hwillson** [comment]
Hi @sebakerckhof - when you have a chance, could you see if Meteor `1.5.2.1-rc.2` fixes this problem for you? I'm interested in knowing if https://github.com/meteor/meteor/pull/9133/commits/5947df645ac28e38310ac41e4587bcae7e3e8394 helps. Thanks!

**Comment by hwillson** [comment]
Closing for now as this should be fixed in `1.5.2.1` / `1.5.2.2`. Please post back if you're still seeing this issue. Thanks!

**Comment by sebakerckhof** [comment]
@hwillson I'm still seeing this occasionally in 1.5.2.2 and even 1.6.0. Now, I don't have any facts to back this up, but it seems that when this occurs, rebuilds are also way slower.

**Comment by sebakerckhof** [comment]
This was caused by: https://github.com/meteor/meteor/issues/9381 . Npm packages kept re-installing so you got duplicate watchers
