### ISSUE TITLE
[meteor 1.6] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by Rebolon** [meteor/meteor#9132]
On my 1.5.2 Meteor application, i tried an update to 1.6.beta-31. The test was ok on my windows 7 and also on my vagrant (ubuntu). 
I tried to test on my server which is also an ubuntu and it failed.

Here are my configs : 
 * windows 7 + node 6.9.1 + meteor binary to start the app
 * vagrant on ubuntu x64 + node 5.0 + meteor binary to start the app
 * ubuntu server x64 + node 8.4.0  + pm2-meteor deployment

i use nvm to select the correct node version

i can easily restore the previous version of the app on a node 4.8.x and meteor 1.5.2

Here is the error displayed when i run the app with pm2 : 

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at /home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/boot.js:366:18
    at Array.forEach (native)
    at Function._.each._.forEach (/home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/boot.js:194:5
    at /home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/boot.js:437:5
    at Function.run (/home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/profile.js:510:12)
    at /home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/programs/server/boot.js:436:11
```

**Comment by hwillson** [comment]
Can you post the output of `pm2 show [appname]`?

**Comment by Rebolon** [comment]
Argh it shows that it uses node 4.8.3
i don't understand coz i specify 8.5.0 in pm2 settings
i check that


│ status            │ errored                                                                   │
│ name              │ webwatcher-service                                                        │
│ restarts          │ 94                                                                        │
│ uptime            │ 0                                                                         │
│ script path       │ /home/rebolon/deploy-webwatcher-service/webwatcher-service/bundle/main.js │
│ script args       │ N/A                                                                       │
│ error log path    │ /home/rebolon/.pm2/logs/webwatcher-service-error-0.log                    │
│ out log path      │ /home/rebolon/.pm2/logs/webwatcher-service-out-0.log                      │
│ pid path          │ /home/rebolon/.pm2/pids/webwatcher-service-0.pid                          │
│ interpreter       │ node                                                                      │
│ interpreter args  │ N/A                                                                       │
│ script id         │ 0                                                                         │
│ exec cwd          │ /home/rebolon/deploy-webwatcher-service/webwatcher-service                │
│ exec mode         │ fork_mode                                                                 │
│ node.js version   │ 4.8.3                                                                     │
│ watch & reload    │ ✘                                                                         │
│ unstable restarts │ 0                                                                         │
│ created at        │ N/A                                                                       │

**Comment by Rebolon** [comment]
The problem comes from the misuse of nvm.
pm2-meteor seems to be unable to use nvm so i had to set manually the default node with nvm
Hope it will helps someone

**Comment by Pushplaybang** [comment]
@Rebolon  - how?
