### ISSUE TITLE
meteor update fails with no error message

### ISSUE THREAD

**Issue by tab00** [meteor/meteor#9141]
Current version: 1.5.2
Version attempting to update to: 1.5.2.1
Operating system: Microsoft Windows 10

When running `meteor update` in an existing version 1.5.2 app, meteor-tool gets downloaded and extracted and the relevant progress messages appear. Checking the into AppData\Local\.meteor\packages\meteor-tool\ directory, there are 1.5.2 and 1.5.2_1.

However it finishes with no output, i.e. the command prompt becomes ready.
`meteor --version` outputs `Meteor 1.5.2`, which means update failed, as it appears that there was no change.

Then when I try to create a new app by running `meteor create test-4732` it pauses for a while with no output and then returns to the command prompt. No new app directory is created.

Though `meteor create test-4732 --release 1.5.2` works normally.

**Comment by abernix** [comment]
Please try deleting the `1.5.2_1` directory in `%LocalAppData%\.meteor\packages\meteor-tool` and then try creating a Meteor 1.5.2.1 project again.  I've been able to get `1.5.2.1` and `1.5.2.2-rc.0` working on Windows 10, so its possible you've experienced some sort of corrupted install.

**Comment by tab00** [comment]
I should have also mentioned that I had experienced the same problem multiple times when updating within the 1.4.x.x range. I worked around the problem by completely uninstalling meteor and reinstalling the latest official version via  InstallMeteor.exe from meteor.com, and that's exactly how I had to install version 1.5.2 too that I'm using now.

I have deleted the 1.5.2_1 directory from meteor-tool already as otherwise my meteor app would no longer run (no error message and back to the command prompt). So I'm quite sure that your suggestion to try `meteor create --release 1.5.2.1 test-app-name` will not work, as I've tried similarly before on many occasions since the 1.4.x days. I assume that version 1.5.2.2 is also going to be released soon, so I'd rather try with that since each update takes quite some time, and failures waste such time.

What would help is if there would be error messages displayed to help in troubleshooting, so maybe some code could be added so that error messages get printed to the screen (instead of being suppressed).

**Comment by tab00** [comment]
Now that version 1.5.2.2 is out I tried `meteor create --release 1.5.2.2 test-4765`.
The output started with `Downloading meteor-tool@1.5.2_2` then changed to `Extracting meteor-tool@1.5.2_2` for a long time (1h?), then `Downloading meteor-tool@1.5.2_2`, and then the command prompt with no result output or error message appearing. There is no test-4765 directory as expected, so a problem did occur, but we don't know what, as there is no error message.

In `%LocalAppData%\.meteor\packages\meteor-tool` there was only a 1.5.2  directory before (occupying 378MB), and afterwards a new 1.5.2_2 directory (occupying 351MB) was created.

**Comment by hwillson** [comment]
@tab00 Now that Meteor 1.6 is out, would you mind trying a full Windows re-install using the [new installation process](https://www.meteor.com/install), to see if that helps?

**Comment by angelovAlex** [comment]
The same is happening on ubuntu

**Comment by hwillson** [comment]
@angelovAlex Are you updating to Meteor 1.6? Can you provide a screenshot showing the `meteor update` run?

**Comment by angelovAlex** [comment]
If I just run `meteor update` the same happens
```ubuntu@ip-172-31-23-150:~/scicity/scimeteor$ meteor update
```Downloading meteor-tool@1.5.2_2...        \  
and that's for hours...

Before Downloading, there were Downloading, Extracting and now Downloading again. I had that server as a production, I was deploying to it using mup. Now I want to run an app from source but nothing helps. Looks like I have to run a clear instance of ubuntu and try it there.

**Comment by abernix** [comment]
@angelovAlex Can you try just reinstalling Meteor from scratch on that Ubuntu machine?

    curl https://install.meteor.com/ | sh

@tab00 Any updates on re-installing with Chocolatey and updating your apps to Meteor 1.6?

**Comment by tab00** [comment]
I've just managed to install Chocolatey and Meteor 1.6 successfully after uninstallation and deletion of the .meteor directory in AppData\Local.

**Comment by hwillson** [comment]
Since re-installing with Chocolatey fixed the original issue, I'll close this off. @angelovAlex If you're still having issues, please post back with the results of https://github.com/meteor/meteor/issues/9141#issuecomment-344542935. Thanks!
