### ISSUE TITLE
[1.5.2.1][iOS] Mobile app can not connect to the server after sleeping device

### ISSUE THREAD

**Issue by pfafman** [meteor/meteor#9142]
Meteor mobile app on iOS is not waking out of sleep properly.  I believe the localhost server that is on the mobile devices does not start back up after sleeping.

My SetUp

- Meteor 1.5.2.1
- macOS 10.13
- Xcode Version 9.0 (9A235)
- iOS 11.0.1

Reproduce:
 1. Create tutorial app simple-todos  (blaze version), add iOS, launch

```
meteor create simple-todos
cd simple-todos
meteor add-platform ios
meteor run ios-device
```

2. Start it on the mobile iOS device connected to computer

3. Open safari dev console for the running app.  In the console type

```
location.reload()
```
Will reload the app.

4. Sleep the device

5. Wake it up

6. Repeat 3

```
location.reload()
```

You will then see:

```
Failed to load resource: Could not connect to the server.  ...
```

I think this means that the meteor server that runs on the iOS device is dead.  Might also be happening on Android but have not confirmed.

This leads to all sorts of strange behavior on a full blown meteor app.

**Comment by pfafman** [comment]
This may be a duplicate of meteor/cordova-plugin-meteor-webapp#27

**Comment by pfafman** [comment]
This grundmanise/cordova-plugin-meteor-webapp@9a414d8 fixes the issue above.

**Comment by KoenLav** [comment]
We're experiencing the same issue in our application. Downgrading to Meteor 1.4.4.4 resolved the issue.

The issue does not appear on Android platform.

**Comment by KoenLav** [comment]
1.5.2.2 seems to fix the issue as well.

**Comment by YannLeBihan** [comment]
Just tested  in 1.6 with several projects upgraded from 1.5.2.2 + a fresh one : the error happens everywhere, with or without the webapp plugin.

**Comment by Roshdy** [comment]
@YannLeBihan have you found any fix for 1.6?? It's killing me

**Comment by YannLeBihan** [comment]
@Roshdy : yes, @macrozone has been very helpful on [a Meteor forum thread](https://forums.meteor.com/t/how-do-you-reliably-prevent-meteor-cordova-ios-from-losing-its-local-server-connection/40531) by pointing me to a fork he made for the webapp plugin. This solved the problem for me, hope it will for you too.

**Comment by Roshdy** [comment]
Actually i downgraded webapp to 1.4.1 and it's working fine!
I'll wait for 1.4.3, maybe it will have the best of the other 2. Thanks for the hint though

**Comment by hwillson** [comment]
This issue is already being tracked in https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27, and PR https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30 has been submitted to fix it. Since it's already being tracked elsewhere, I'll close it here. Thanks!
