### ISSUE TITLE
User keeps logging out after sometime - [Meteor 1.5.2.1 UPDATED]

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9144]
I just updated my Meteor Server to 1.5.2.1, now the user keeps logging out after sometime,
Is this some security feature or is this a bug?

**Comment by jasongrishkoff** [comment]
This is happening on my side too. Only started after the 1.5.2.1 update. Also see someone mentioned it here: https://forums.meteor.com/t/users-being-logged-out/39543

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9144#issuecomment-332750329, this issue is a duplicate of https://github.com/meteor/meteor/issues/9140.
