### ISSUE TITLE
macOS firewall "do you want the application node to accept incoming network connections?"

### ISSUE THREAD

**Issue by zanot** [meteor/meteor#9147]
Hello.

As a newbie with Meteor, I have been using it for few weeks without any particular problem, but now I am facing with this one, which is "a bit" annoying. I keep having this kind of warning randomly, sometimes when I create a new file, sometimes when I save a modified file (sometimes not), ... And of course when I click "Allow" it does not change anything.
![meteor warning node](https://user-images.githubusercontent.com/4114656/30962814-866f3010-a44b-11e7-9de3-9f2a3b0229c0.png)
The first days when I was trying Meteor, I remember I had such warnings but once I clicked "Allow" it was ok.

I searched similar cases, again and again, and found some solutions (for example like [this one](https://github.com/tj/n/issues/394#issuecomment-285107867), or [the following](https://github.com/tj/n/issues/394#issuecomment-312510914), that I adapted to my situation with Meteor) but they did not work.

My firewall settings are quite simple, I already had node rules, I tried to remove the rules / reboot / add the rules again, but nothing changed.
- First node rule path is : /usr/local/bin
- Second node rule path is : /Users/zekka/.meteor/packages/meteor-tool/.1.5.2_1.1yy0our++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin
![meteor firewall](https://user-images.githubusercontent.com/4114656/30963297-416b8840-a44d-11e7-9186-2125ee35be13.png)

I tried to reinstall Nodejs (without uninstalling it before), reboot, but the warnings are still there.

I do not know what to do anymore 😕   ...

- The version of Meteor showing the problem : Meteor 1.5.2.1
- The operating system you're running Meteor on : macOS Sierra 10.12.6

**Comment by zanot** [comment]
I just found this related issue.
https://github.com/meteor/meteor/issues/9139

**Comment by zanot** [comment]
I just found this related issue. https://github.com/meteor/meteor/issues/9139

**Comment by hwillson** [comment]
A full fix is coming shortly @zanot - let's continue the discussion in https://github.com/meteor/meteor/issues/9139. Closing here - thanks!

**Comment by m-salamon** [comment]
having the same issue when I updated to `node v8.6.0`

**Comment by abernix** [comment]
A release candidate for Meteor 1.5.2.2 has been released which includes this change.  Can you please help test it and confirm whether this issue is fixed?

    meteor update --release 1.5.2.2-rc.0

**Comment by zanot** [comment]
@abernix 
1. Project folder duplicated
2. `cd folder_test`
3. `meteor update --release 1.5.2.2-rc.0`
4. `meteor run`
5. Files duplicated, modified... Everything works well. This issue seems fixed 👍 .
