### ISSUE TITLE
Update 1.5.1 to 1.5.2 cause empty __meteor_runtime_config__

### ISSUE THREAD

**Issue by stefanocudini** [meteor/meteor#9149]
After upgrading to Meteor 1.5.2, I am experiencing a strange bug!  __meteor_runtime_config__ is empty!

the html page *http://localhost:3000/* contains:
```html
<script type="text/javascript">
__meteor_runtime_config__ = JSON.parse(decodeURIComponent(<%= conf %>))
</script>
  <script type="text/javascript" src="<%- src %>"></script>
  <script type="text/javascript" src="<%- src %>"></script>
...
```

later I tried with: *meteor reset*
and also a downgrade: *meteor update --release 1.5.1*
but the issue persist!! 

I can not understand how I can investigate the problem! :frowning: 
(nodejs --version is v8.6.0)

many thanks

**Comment by stefanocudini** [comment]
find a solution... I can suppose this is caused by the package *boilerplate-generator* but this is included (version 1.2.0) in my application

**Comment by stefanocudini** [comment]
the problem is a custom configuration of a standard function of *underscore* **_.template**

I reconfigured _.template function has following
```javascript
_.templateSettings = {
	interpolate: /\{(.+?)\}/g
};
```
this settings block the work of **boilerplate-generator**

**Comment by RobertLowe** [comment]
I can confirm this is a legitimate issue as well, we should not be mixing underscores in user-land and meteor-land...

Thanks for posting this @stefanocudini 

Pinging @benjamn @hwillson @glasser

**Comment by glasser** [comment]
This is probably related to Steven's project this summer.

**Comment by RobertLowe** [comment]
@glasser  This just happen to me.

1. Updated active project from `1.5.2.1` to `1.5.2.2`
2. App would start but content would not be properly interpolated.
3. Found offending:

    _.templateSettings = {
    	interpolate: /\{(.+?)\}/g
    };

4. Removed offending code, issue was resolved. 

So the `_` used by meteor and in user land are mixing. Very leaky. :thinking:

**Comment by hwillson** [comment]
Thanks @RobertLowe - re-opening. I haven't had a chance to look into this yet, but I'll plan on digging in shortly.

**Comment by stefanocudini** [comment]
Thanks @RobertLowe you too!
I solved the problem simply editing my code.. and removing my customization of underscore in templateSettings but I don't sure this is the best way to fix the problem..
I did this because I needed the new Meteor version and could not wait to wait for other official solution...

I've got to study the code that creates the problem, but I think it's not easy to solve at this time, we need to isolate the context with which we use underscore within Meteor over the context in which the user works and I haven't idea how to do it .. goes beyond my knowledge of Meteor

I would appreciate if there was a solution that allows meteor users to modify their template system ^_^

**Comment by RobertLowe** [comment]
Thanks @hwillson ! 👍  

@stefanocudini thanks for posting on the forums and an issue here, it sure saved me a bunch of time! Yes, I think ideally they would be isolated instances.  `_.template(templateString, [settings])` allows for `interpolate` option to be passed in if you like (ex: `_.template("<div>{{thing}}</div>", {interpolate: /\{\{(.+?)\}\}/g} )({thing: 'awesome'});`

**Comment by stefanocudini** [comment]
@RobertLowe  I can tell you exactly... about 3 days of research! ^_^

**Comment by hwillson** [comment]
I've submitted PR #9250 to help address this. The fact that this could happen in the first place isn't great (and as you mentioned @RobertLowe is leaky), but this quick fix should help for now.
