### ISSUE TITLE
[1.5.2.x] android-platform : can not find the gradle

### ISSUE THREAD

**Issue by Fen747** [meteor/meteor#9154]
As I recently started to build a new android app using Meteor, I have tried to add the android-platform and faced the famous 25.3 rev problem. I then updated to v26.02 but faced the same issue described here : [https://forums.meteor.com/t/meteor-cant-find-android-sdk/37506/4]([](https://forums.meteor.com/t/meteor-cant-find-android-sdk/37506/4)) and resolved it thanks to  [https://github.com/meteor/meteor/issues/8464](https://github.com/meteor/meteor/issues/8464).

But I found out that even now my android sdk is correctly set, Meteor does not find the android gradle when I'm using version 1.5.2 :

`meteor remove-platform android && meteor add-platform android
android: removed platform                     
Subproject Path: CordovaLib                  /
android: added platform                       
                                              
Your system does not yet seem to fulfill all requirements to build apps for
Android.
                                              
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
                                              
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✓ Android target                              
✗ Gradle: Could not find an installed version of Gradle either in Android
  Studio,
  or on your system to install the gradle wrapper. Please include gradle 
  in your path, or install Android Studio`

But when I downgrade to 1.5.1, it works just fine. I tried to reproduce the issue on my old PC where the setup is already using android API 23, and the issue is exactly the same after updating Meteor.

And, as a complete newbie about android dev world, I got no idea why this is happening. I read the 1.5.2 patchnote and didn't found any seeminlgy breaking change.

**Comment by babsher** [comment]
I ran into this same problem. From what I can tell meteor is not looking for gradle in a place where it exists or your Android SDK is not being added to the path.

The solution I found was to install gradle manually.

**Comment by paranoico** [comment]
Today we also upgraded and I can confirm issue also and manually installing gradle on ubuntu using the following last version solved the problem, but we had a Meteor behavior slightly different:

> sudo add-apt-repository ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install gradle-ppa

**Comment by babsher** [comment]
Is there any reason meteor could not include the Gradle wrapper as part of it's distribution?

**Comment by MJO9** [comment]
I have the same issue here with Meteor 1.5.2.2 with SDK 26.1.1
I already tried SDK 25.2.5 with no luck

**Comment by sathishc** [comment]
Why does Meteor default to such an old version of Gradle? Have been trying to build an Android apk for the last 5 days with various versions (after manual install) and changing the gradle version, but no success. Even the 2.14.1 version is stuck forever. I have tried letting the build run overnight only to see the message "Building Cordova app for Android" in the morning :( This is very frustrating

**Comment by paranoico** [comment]
After upgrading to Meteor 1.6 yesterday we could uninstall Gradle and after some tries and resets our application started to use Gradle from Android Studio.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9154#issuecomment-341233620, this should hopefully be fixed with Meteor 1.6. If anyone is still encountering this issue with >= 1.6, please post back and let us know. Thanks!

**Comment by bgjitu** [comment]
It was fine on 1.6.0.1 but after upgrading to 1.6.1, I see the following error -
Note - I have not investigated yet but it seems similar here so posting.
>  While building Cordova app for platform Android:
>    Could not find an installed version of Gradle either in Android Studio,
>    or on your system to install the gradle wrapper. Please include gradle 
>    in your path, or install Android Studio

**Comment by adamgins** [comment]
@hwillson I just upgraded to 1.6.1 and I am getting the issue.

**Comment by adamgins** [comment]
@hwillson any comments/help appreciated please

**Comment by babsher** [comment]
Have you tried installing Gradle manually?

**Comment by adamgins** [comment]
@babsher yes, just got that working thanks. 
Although I thought it was mentioned that this would be fixed in 1.6 as per @hwillson 

> If anyone is still encountering this issue with >= 1.6, please post back and let us know. Thanks!

**Comment by Fen747** [comment]
Hello folks

I faced agin the same problem today, and found back this thread and the recently added replies to my issue. This time, with Meteor 1.6.1, installing graddle 2.12.1 with SDKMAN! worked well and solved the problem in no time.

**Comment by IVANLEE99** [comment]
Gradle: not installed 
Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio

**Comment by twentyfortysix** [comment]
this helped on my mac os machine with Android studio installed (Meteor 1.7):
brew install gradle@2.14

**Comment by derwaldgeist** [comment]
> brew install gradle@2.14
How did you do this? As to my knowledge, brew does not offer 2.14 or 2.14.1 of gradle.
