### ISSUE TITLE
Upgrading to Meteor 1.5, mongo connection time-out on large aggregation pipeline task.

### ISSUE THREAD

**Issue by lpgeiger** [meteor/meteor#9155]
Strangely I'm getting connection errors to mongoDB when the mongoDB operations are CPU intensive (on the remote mongo instance).  I wouldn't expect this. The rest of my app works fine. Any ideas?

The version of Meteor showing the problem:
1.5.1
The last version of Meteor where the problem did _not_ occur (if applicable):
1.4.2
The operating system you're running Meteor on:
OSX and in Galaxy

The issue:
Doing an aggregation with $group on a 10gb table works fine in 1.4.2, after updating to 1.5.1 the same code with no changes leads to a:
`
[MongoError: connection 3 to mydb.mongodb.net:27017 timed out] name: 'MongoError', 'connection 3 to mydb.mongodb.net:27017 timed out'
`

**Comment by matadur** [comment]
I was fine with 1.5, now getting massive timeouts with 1.5.2.1 - bad enough that I reverted my deploy. Lots of new code in the deploy tho, so I'm not ready to blame the Meteor update yet.

**Comment by hwillson** [comment]
@lpgeiger Are you still seeing this problem with Meteor `1.5.2.2`?

**Comment by hwillson** [comment]
We haven't heard back regarding whether this is happening with a more recent version of Meteor, so I'll assume that it isn't and close this issue. Please post back if you're still encountering this issue with Meteor 1.5.4 or Meteor 1.6. Thanks!

**Comment by gregory** [comment]
we are getting the a similar issue on 1.6 while doing bulk operations...

**Comment by realyze** [comment]
@hwillson I'm seeing a similar error with Meteor 1.6:
```
Dec 15 21:02:13 sharewaste: Exception while polling query {"collectionName":"users","selector":{"_id":"<userid>","services.resume.loginTokens.hashedToken":"<token>"},"options":{"transform":null,"fields":{"_id":1}}}: MongoError: connection 5 to <mlab url> timed out
```
My database is a pretty small one (cca 2500 users) running on mLab.

**Comment by gregory** [comment]
@hwillson should we reopen this?

**Comment by hwillson** [comment]
Sure thing @gregory - if anyone here can provide some kind of runnable reproduction showing this happening, that would go a long ways towards helping get this resolved.

**Comment by ChuckIrvine** [comment]
I recently modified my local development Meteor configuration to access an mLab mongo instance rather than the default local instance. After doing so, I continually get this error. Perhaps you could do the same to try to reproduce this error.

**Comment by hwillson** [comment]
If anyone is able to provide a reproduction that demonstrates this issue, we'll be glad to take a look. Closing for now.
