### ISSUE TITLE
npm peer requirements (for react-meteor-data) not installed:

### ISSUE THREAD

**Issue by Omar-allahham** [meteor/meteor#9157]
WARNING: npm peer requirements (for react-meteor-data) not installed:
W20170930-01:10:11.612(-7)? (STDERR)  - react@16.0.0 installed, react@15.x needed
W20170930-01:10:11.614(-7)? (STDERR) 
W20170930-01:10:11.615(-7)? (STDERR) Read more about installing npm peer dependencies:
W20170930-01:10:11.615(-7)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20170930-01:10:11.617(-7)? (STDERR)

**Comment by klaussner** [comment]
The peer dependency requirement will be updated for React 16 in the next version of `react-meteor-data` (0.2.14), which should be released soon: https://github.com/meteor/react-packages/pull/232.
