### ISSUE TITLE
1.6-rc.1 Chrome node.js debug confused about 32bit (windows)

### ISSUE THREAD

**Issue by janat08** [meteor/meteor#9163]
### This bug report should include:
- [x] A descriptive title
- [x] The version of Meteor showing the problem.
1.6-rc.1
- [x] The last version of Meteor where the problem did _not_ occur (if applicable)
n/a
- [x] The operating system you're running Meteor on.
Windows 10 64bit
- [x] The expected behavior.
Meteor debug will let chrome connect and debug async
- [x] The actual behavior.
Chrome dev tools need 64bit systems to debug async, which it thinks i'm not on ("platform" which platform I don't know)
```
node:39856) [INSPECTOR_ASYNC_STACK_TRACES_NOT
_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on
32bit platforms. The feature is disabled.
```
- [ ] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)

**Comment by benjamn** [comment]
The warning should go away with https://github.com/meteor/meteor/pull/9173 (and async stack traces should work, too).

**Comment by benjamn** [comment]
Meteor 1.6 will provide native 64-bit support on Windows, though it will require reinstalling Meteor using our new [Chocolatey](https://chocolatey.org/)-based installer. I can confirm this error goes away when the Meteor's Node.js binary is 64-bit (that is, `meteor node -p process.arch` prints `x64`).

**Comment by ignl** [comment]
Hi, I have reinstalled meteor through Chocolatey, but I still have 32 bit meteor. It seems that this [url ](https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64) still downloads 32 bit version.

**Comment by klaussner** [comment]
@ignl See https://github.com/meteor/meteor/pull/8728#issuecomment-340287862. You will have to wait until tomorrow. :smile:

**Comment by ignl** [comment]
@klaussner OK I see. Thanks.
