### ISSUE TITLE
[v1.6-rc.1] Debugger did not attach after 5 minutes; continuing. (windows)

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9165]
Chrome debugger does not immediately connect to running meteor node process.  After 5 minutes the DevTools for node will show the following error: `Debugger did not attach after 5 minutes; continuing.`

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.1

### Steps to repro
1. start meteor: `meteor debug`
2. From Chrome go to url: `chrome://inspect`, click on "Open dedicated DevTools for Node"
3. See Chrome inspector come up, looking like it is running. (note Pause button does not work)
4. Wait 5 Minutes or more.

**Result:** message in console: "Debugger did not attach after 5 minutes; continuing."

### Notes:
- I had put some breakpoints in `app.js` and on continuing the debugger paused at the breakpoints.
- It looks like I can debug.  (without source mapping to my source files)
- On server command window the same error shows up and implies that debugging is not happening, but it is:
```
20171001-17:48:36.461(-7)? (STDERR) Debugger did not attach after 5 minutes; continuing.
```
- If I kill the DevTools for Node then the following displays on the command window:
```
W20171001-17:55:35.858(-7)? (STDERR) Debugger listening on ws://127.0.0.1:9229/e1ea2583-9a64-47d0-bf28-7028886eab3d
W20171001-17:55:35.909(-7)? (STDERR) For help see https://nodejs.org/en/docs/inspector
W20171001-17:55:35.912(-7)? (STDERR) (node:3872) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
W20171001-17:59:52.572(-7)? (STDERR) Debugger attached.
W20171001-17:59:52.574(-7)? (STDERR) Debugger listening on ws://127.0.0.1:9229/e1ea2583-9a64-47d0-bf28-7028886eab3d
W20171001-17:59:52.577(-7)? (STDERR) For help see https://nodejs.org/en/docs/inspector
```

I think the debug mode is a little confused.

**Comment by brucejo75** [comment]
Verified working in 1.6-rc.3
Thanks @benjamn!

**Comment by dlredden** [comment]
It seems that this is an issue with 1.6 (proper) on macOS High Sierra, updated via `meteor update`. I tried on an existing project that I upgraded as well as a new project and experienced the same issue (Debugger did not attach after 5 minutes; continuing.), `meteor debug` hangs for 5 minutes, then finally releases and the site works, just without debugging.

**Comment by brucejo75** [comment]
@dlredden, try `meteor --inspect` or `meteor --inspect-brk`.  see [History.md](https://github.com/meteor/meteor/blob/devel/History.md#v16-2017-10-30) - 4th bullet
