### ISSUE TITLE
[v1.6-rc.1] Debugger source files are not mapped to the downloaded meteor files (e.g. app.js)

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9166]
I ported my app over to `1.6-rc1`.  I was really looking forward to using the marquee debug feature.

I cannot figure out how to get source maps working properly.  I hope that I am missing some setting or something...

**Any/All help is much appreciated!**

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.1

### Repro
- I read the Medium [article](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27).
- I read the Node [article](https://nodejs.org/en/docs/inspector/).
- I made sure my [source map settings were right](https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps).

1. `meteor create test`
2. `cd test`
3. `meteor debug`
4. From Chrome go to url: `chrome://inspect`, click on "Open dedicated DevTools for Node"
See Chrome inspector come up, looking like it is running. (note Pause button does not work)
5. Wait 5 Minutes or more. #9165
6. Message in console: "Debugger did not attach after 5 minutes; continuing."

**Result:** Now I can debug, but...
1. Similar to #8590, None of my source code files are mapped in Chrome.
2. I can see all my code in `.meteor\local\build\programs\server\app\app.js` but nothing is mapped to my source code tree. (see picture)
3. The source code tree has 100's of files from my build bundle and then finally from my project build and then a bunch of other files.  But none of my source files. (see picture)
4. Chrome indicates that a "Source Map detected" and claims "associated files should be added to the file tree" but they do not appear there?  (see picture)

![image](https://user-images.githubusercontent.com/14342237/31060142-e8d8cd1e-a6c2-11e7-92ed-4bb140f31b74.png)

**Comment by benjamn** [comment]
This was "not something that we can actually fix at this time" according to the Node folks last year: https://github.com/nodejs/node/issues/8369

Here's hoping there's anything we can do about it in October 2017. 🤞 

To be clear, this is definitely a Windows-specific problem, as server-side inspector source maps work just fine on other platforms.

**Comment by brucejo75** [comment]
Hi @benjamn, that is unfortunate :confused:.

I spotted this [workaround](https://github.com/nodejs/node/issues/10838#issuecomment-321266341).  I will give it a shot on a build of a meteor project and see if it enables the source maps.

If it does work, is it possible to include it in the meteor startup code for windows?

**Comment by benjamn** [comment]
Sure, please try it. We should probably also switch to inline, base64-encoded source map URLs for server-side files, just so Windows doesn't have to load source maps files from disk. Note: I tried that a few days ago and it did not solve this problem, but it should help.

**Comment by brucejo75** [comment]
Hi @benjamn,

I made a little progress...

In `boot.js` substitute this code for the code at [L327](https://github.com/meteor/meteor/blob/5a6cb704adc594191a64dab8c414e545346b5a7f/tools/static-assets/server/boot.js#L327).
```
    var scriptPath = 'file://' + fileInfoOSPath.replace(/\\/g,'/');
```

I think that node issue [30838](https://github.com/nodejs/node/issues/10838#issuecomment-321266341) basically says that chrome's inspector cannot handle windows paths.

When I use the relative path designation with the URL path format (e.g. `file://<dirpath>/<filename>`) then the inspector sorts them into sections: `(no domain)`, `app` & `packages`.

You have a comment on `boot.js` line [318](https://github.com/meteor/meteor/blob/devel/tools/static-assets/server/boot.js#L318) which may no longer apply with the new `inspector` protocol?

I am battling a case of the flu and need to pass out.  Maybe you can use that info to try the relative path with URL path format...

### My next steps (maybe later tonight)
- fork meteor
- modify boot.js for the builds
- figure out how the source files (elements of the maps) are sent to the debugger and try using the URL path format with the source files.

**Comment by brucejo75** [comment]
Hi @benjamn,

I want to mess around with the prefixing used in the sourcemaps.
For example change from `meteor://💻app` to `file://💻app` and see what happens.

Can you point me to that code?  I am having a  hard time finding it.

Thanks!

**Comment by brucejo75** [comment]
ugh...

I tried a couple of things but no luck.  I was able to get node debugging work in VS Code so I will switch over to that.

Given that Node debugging with Chrome works for OSX maybe this is a 64 bit v. 32 bit issue?

If so, maybe [request 152](https://github.com/meteor/meteor-feature-requests/issues/152) or #9173 will solve this for windows?

Chrome's error statment:
```
node:39856) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
```
Makes me think that chrome has less support for 32bit node debugging.  And maybe the shift to 64bit will sort it out...

**Comment by brucejo75** [comment]
Woo Hoo!!  verified working with 1.6-rc.9

Great to see, thanks @benjamn!

**Comment by airstep** [comment]
Can anybody describe how to attach debugger in VisualCode?

It works only if i write word 'debugger' but not when set breakpoint in IDE... and seems it is not found *.map(s)

Official [documentation](https://github.com/Microsoft/vscode-recipes/tree/master/meteor) didn't help.
