### ISSUE TITLE
Mongo multi-parameter is not being picked up by the collection update method

### ISSUE THREAD

**Issue by aliogaili** [meteor/meteor#9177]
Follow-up on the [ previously self-closed issue](https://github.com/meteor/meteor/issues/5945#issuecomment-334305314). that is still occuring. 
> Updating multiple collections by using {multi: true} is not working https://docs.mongodb.org/manual/reference/method/db.collection.update/#multi-parameter. I am currently having to use a find with a foreach and manually updating the documents one by one. I understand the security issues with regards to using multi from the client, but there's no reason to block it on the server.
> 
> collection.update({}, {}, {multi: true})

### This bug report should include:
- [x] A descriptive title
- [x] The version of Meteor showing the problem.
    1.6-rc.3 production repo, but not sample repo
- [x] The last version of Meteor where the problem did _not_ occur (if applicable)
- [x] The operating system you're running Meteor on.
   MacOS Sierra
- [x] The expected behavior.
   As per the mongo [multi parameter documentation here](https://docs.mongodb.com/manual/reference/method/db.collection.update/#multi-parameter), the update call should update each 
   collection that matches the given criteria. 
- [x] The actual behavior.
   In a simpler repo works perfectly, however the issue is observed in the production repo. Need to confirm with other users who are witnessing this behavior. 
- [x] A **simple** reproduction!
    [Github Repo]( https://github.com/aliogaili/multi-param-issue)

**Comment by abernix** [comment]
Thanks for refiling the issue if it's still happening; the original issue was self-closed, so it wasn't looked at.  I've updated the post above with a checklist of items needed during issue reporting.  Please take some time to include those details.

It's not even clear to me what the specified update would be expected to do:

    collection.update({}, {}, {multi: true})

Update every document with no changes?

**Comment by aliogaili** [comment]
I'll update the issue with more descriptive content.

**Comment by aliogaili** [comment]
@abernix  I tried to create a simple reproduction repo with the to do example and to my surprise, its worked just fine.

My original repo is at 1.6-rc.3 and I updated to example to the same version. 

Original code (not working): 

```
 Posts.update(
        { userId: `${Meteor.userId()}` },
        {
          $set: {
            authorName: `${firstName} ${lastName}`,
            avatarSrc: src
          }
        },
        { multi: true }
      ); 
```

Workaround code (working) :

   ```
 Posts.find({ userId: `${Meteor.userId()}` }).forEach(doc => {
        Posts.update(doc._id, {
          $set: {
            authorName: `${firstName} ${lastName}`,
            avatarSrc: src
          }
        });
      });
```

And the simple repo code: (working!)
```
 Tasks.update(
      { check: false},
      {
        $set: {
          checked: true
        }
      },
      { multi: true }
    );
```
And I can't tell why my original repo code is not working while the sample repo is working.

**Comment by aliogaili** [comment]
I do think there is some issue somewhere, but I can't narrow it. I've asked the other user who is reporting the same issue to attempt reproducing , if not, then I thin I'll close this as well since it's seems specific to the code/project.

**Comment by benlavalley** [comment]
Using any packages that might hook into collection updates -- e.g. collection2/simple schema/collection hooks?

I use all three myself without problems and haven't seen an issue but figured I'd mention some possible things to check out.

Also might help to run the update with a function callback to try and fully log both errors/results. You could also add some additional debugging code to perhaps run a find+count on your update filter then store the filter + results to a collection of your choice, then execute the update and write the resulting updated number of documents as a result. Timestamp it all and when you find inconsistencies maybe check the Mongo logs. You can also enable logging in mongo to store all queries which you can cross-reference if need be.

So far the only times I've run into issues like this were when I was not properly formatting my update request or I had something with collection2/simple-schema rejecting my update.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9177#issuecomment-334436238, without a reliable reproduction demonstrating this issue, there isn't much that can be done here. Closing for now (but happy to re-open if anyone can supply a repro). Thanks!

**Comment by Alameli** [comment]
I've had this issue last night trying to figure it out for long time.

You might be having the same issue as I. If your collection extends Mongo Collection, then you need to make sure that the update() function you overrode includes an extra parameter "multi" and calls super.update(selector, modifier, multi).

Here's an example:

`class SomeCollection extends Mongo.Collection {
  insert(doc, callback) {
     ....
  }
  update(selector, modifier, multi) {
    const result = super.update(selector, modifier, multi);
    // Do something after update
    return result;
  }
  remove(selector) {
    ....
  }
}`

The sample may have worked because it doesn't override the original update function.
