### ISSUE TITLE
Dynamic imports wrongly loads static import dependencies inside packages

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#9182]
When you use `import()` to dynamically import a file, you would expect that all of that file's static `import`s would also be loaded dynamically. In other words, if I load this file dynamically:

```js
import SuperHeavyJSPackage from 'super-heavy-js-package';
```

Then `SuperHeavyJSPackage` will *not* be part of my app bundle. 

While this works fine inside the `imports` directory, it seems like it doesn't inside the `packages` directory. What's more, apparently imports will run even when they shouldn't (for example, inside an `if (false) {...}` block). 

Here's a reproduction I created with help from @Discordius, who found the issue: 

https://github.com/SachaG/dynamic-imports-bug/tree/package

And here's the same code running out of `imports` to compare: 

https://github.com/SachaG/dynamic-imports-bug/tree/imports

It seems like the problem has been around since 1.5 as far as I can tell.

**Comment by benjamn** [comment]
This is definitely a bug!

I don't expect this to mean much to anyone but me, but I've tracked the problem down to [this line](https://github.com/meteor/meteor/blob/255732630d16e2b393e85c5b77f613abcf37dd41/tools/isobuild/import-scanner.js#L898), which is executed when a Meteor package tries to import an npm package from the application `node_modules` directory. Specifically, the mistake seems to be that the `forDynamicImport` parameter is ignored, so we lose the crucial information that `HeavyComponent.jsx` was imported dynamically.

**Comment by Discordius** [comment]
Just as a quick question so I can decide whether to implement a hot fix myself: Do you have any guess how long it will be until I might be able to pull a fix to this? (ideally via npm and not via forking the repo)

**Comment by benjamn** [comment]
@Discordius You can try it now with Meteor 1.6: `meteor update --release 1.6-rc.6`. If you're not ready for that, we will probably back-port this to Meteor 1.5.3 (not yet released).
