### ISSUE TITLE
React todo tutorial needs updating to use withTracker

### ISSUE THREAD

**Issue by ChuckIrvine** [meteor/meteor#9183]
Not sure whether you will think this is a bug or not. The React todo tutorial needs to be updated to use withTracker instead of the deprecated createComponent.

**Comment by abernix** [comment]
@ChuckIrvine Not sure if it's a bug, but the React Todo is handled in https://github.com/meteor/todos/ on the `react` branch, not in this repo.  If you could submit a PR, (it probably needs other updates too, for example to `react` too!) that would be greatly appreciated!

Regardless, thank you for opening this!  At the very least, if you don't have time to update it, please open an issue on that (other) repository!

**Comment by ChuckIrvine** [comment]
I opened an issue in the todos repo. I’m not familiar enough with the new functionality of withTracker to make the changes myself.
