### ISSUE TITLE
Update React Todo to use TypeScript since PropTypes deprecation

### ISSUE THREAD

**Issue by dcantatore** [meteor/meteor#9189]
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

They suggest using the prop-types package but I think using TypeScript would be a better option since it is can be used with all javascript and not intended just for react. There are more pros and cons if searched, open to hear all thoughts.

**Comment by abernix** [comment]
The `todos` repository is not maintained in this GitHub repository.  You're encouraged to explore that line of thought, but please do so on the [Todos issue tracker](https://github.com/meteor/todos/issues).  Thanks! :)
