### ISSUE TITLE
[v1.5+] TypeError: Path must be a string. Received undefined 

### ISSUE THREAD

**Issue by cfnelson** [meteor/meteor#9193]
### Build Process Issue - TypeError: Path must be a string. Received undefined 

When a Meteor 1.5+ app has the [okgrow:analytics@3.0.2](https://github.com/okgrow/analytics) Meteor package added the following error is thrown during the app's build process`TypeError: Path must be a string. Received undefined` full error [here](https://gist.github.com/cfnelson/626de554f1c08abfc4e14e07dbdb9fbd), I believe the error is thrown due to an assertion on the argument being a string (see note on hack below).  

**Note:** Meteor apps prior to `1.5` work fine with `v3.0.2`.

The only significant change made in the package was to bump the version of the package's single npm dependency from `1.0.2` to `1.0.3`. Diff between `v3.0.1` and `v3.0.2` is [here](https://github.com/okgrow/analytics/compare/06fe7dfbc49ad86800348e4b27f2219efff23fc3...8d602b6d9e73867d56357592a5c2a8701076a42a). The npm dependency is [@okgrow/auto-analytics](https://github.com/okgrow/auto-analytics) and its diff is [here](https://github.com/okgrow/auto-analytics/compare/4f0f3f6...master).

**Note:** `okgrow:analytics@3.0.1` was previously released to resolve the build error and was thought to have been resolved by removing `babel-runtime` and a transform from the build process for `@okgrow/auto-analytics`. See original issue reported [here](https://github.com/okgrow/analytics/issues/179)

**Hack:**
I have been able to successful build/run a Meteor App `v1.5.2`, along with the package fully functioning as expected by modifyingMeteor's [wrapPathFunction](https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/tools/static-assets/server/mini-files.js#L75) by hardcoding the below inside its callback function at line [95](https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/tools/static-assets/server/mini-files.js#L95):
```js
if (arguments[0] === 'node_modules/meteor/okgrow:analytics/node_modules/@okgrow/auto-analytics/vendor') {
  arguments[1] = '';
}
```
I logged the parms passed to `wrapPathFunction(name, partialPaths)`  and it's callback function, see below.
```
name:  relative
partialPaths:  undefined
arguments { 
  '0': 'node_modules/meteor/okgrow:analytics/node_modules/@okgrow/auto-analytics/vendor',
  '1': undefined
}
```

I am unsure if this behaviour from Meteor is to be expected or if there is a subtle bug in the build process? 

Potentially I also thought something may have gone wrong in the publish process as there are two `node_modules` in the packages npm dir and it contains two versions of its npm dependency. The below occurs in `os.json, web.browser.json, web.cordova.json`.
```
"node_modules": {
    "npm/node_modules": { <-- Contains @okgrow/auto-analytics v1.0.2 is the old version.
      "packageName": "okgrow:analytics", 
      "local": true
    },
    "npm/node_modules1": { <-- Contains @okgrow/auto-analytics v1.0.3 which is the one we want.
      "packageName": "okgrow:analytics",
      "local": false
    }
```

 I was wondering if you could provide any insight into if this is a potential bug with Meteor's build or publish process or is in fact expected behaviour due to the changes introduced in `v1.5`. Any insight into what is occurring would be greatly appreciated. 😃 

**Example:** You can see an example [here](https://github.com/okgrow/analytics/tree/master/examples/react-router) running prior to Meteor 1.5+.
```
git clone https://github.com/okgrow/analytics.git
cd analytics/examples/react-router
meteor npm install && meteor npm start
// You will have an app running on METEOR@1.4.3.2
// Kill the app and update meteor
meteor update
meteor npm start
// Your app will now throw the TypeError
// You can get the app to run by copying the hack discussed above
// and modifying your local copy of tools/static-assets/server/mini-files.js
```

**Comment by Floriferous** [comment]
Just encountered this issue on 1.6-rc.6

**Comment by benjamn** [comment]
Thanks for the in-depth analysis @cfnelson!

Since there's a [`package.json`](https://github.com/okgrow/analytics/blob/master/package.json) file in the `okgrow:analytics` package, I suspect there may have been a local `node_modules` directory in the package at the time `meteor publish` was run. For better or worse, we do allow local `node_modules` directories in Meteor packages, but it appears the output paths can collide with those of `Npm.depends` dependencies. In practice, using both is relatively uncommon, perhaps because it leads to problems like this!

While that behavior is not ideal, I suspect you can solve this problem by re-publishing `okgrow:analytics` with a new patch version, after making sure there is no `node_modules` directory present.

**Comment by cfnelson** [comment]
@benjamn Thanks for your response! Will give republishing a go and update here shortly. By any chance is the new `.meteorignore` file respected for publishing? Would it make sense to ignore the local `.node_modules` for publishing a package?

**Comment by cfnelson** [comment]
@benjamn Thanks for the help & insight! I can confirm that deleting the local `node_modules` works before publishing! 🎉

**Comment by hwillson** [comment]
I was just hit with this when publishing as well. I usually have a local `node_modules` directory when working on packages, due to my use of `eslint`. I think we should get this documented in the guide/docs, so I'll open PR's accordingly.
