### ISSUE TITLE
[1.6-rc.6] iPhone X misreporting window.screen.availHeight property

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#9208]
Working with 1.6-rc.6 from https://github.com/meteor/meteor/pull/8728

When running Meteor on ios-device and using Xcode Simulator for iPhone X / iOS 11, running a `console.log(window.screen.availHeight)` reports that the availHeight is `667`. This appears to be the height of the iPhone 6/7/8 (or iPhone 6+/7+/8+ with display zoom). I believe the iPhone X should be reporting a value of `812`.

This causes the display to be constricted, with some slight padding on the top, and a lot of padding on the bottom of the screen (white area is usable space):

![screen shot 2017-10-11 at 7 57 40 am](https://user-images.githubusercontent.com/437029/31439420-11c5f956-ae5a-11e7-91fb-198779aef2c7.png)

Perhaps this is a problem of support with/without display zoom, as the iPhone 6/7/8 reports a value of `667` but the iPhone 6+/7+/8+ reports a value of `736`. Otherwise it's because the iPhone X is just not reporting the value correctly.

**Comment by bmanturner** [comment]
Do you have the proper meta ```viewport-fit=cover``` in your header and are you using the new splashscreen sizes?

**Comment by markoshust** [comment]
I'm using `cordova-plugin-statusbar@2.2.3` (most recent version afaik).

I do have `viewport-fit=cover` in my header, and I am using all of the new splashscreen sizes. Still receive the above when within the app. Big header at top, bigger space at bottom. cc @bmanturner

**Comment by bmanturner** [comment]
@markoshust Until they officially bump the version number you'll need to use the commit that contains the fix instead.

```cordova-plugin-statusbar@https://github.com/apache/cordova-plugin-statusbar.git#c45331b95555c5c77b4ed4ca690236a9b077ec4b```

**Comment by markoshust** [comment]
@bmanturner thank you. i tried that version, but no change here. this is what i see on my main login screen:

![screen shot 2017-10-23 at 5 40 50 pm](https://user-images.githubusercontent.com/437029/31914616-5afdfa88-b819-11e7-82b3-e41659f51d77.png)

**Comment by markoshust** [comment]
ok -- i have `viewport-fit=cover` added to my index.html file, however it is not showing/rendering when viewing the source. i'll debug.

**Comment by markoshust** [comment]
it appears `viewport-fit=cover` is actually being added. if you check with another browser, for example Chrome, you will see the tag added (but ignored, as it isn't supported).

if i instead add this:
```
import { WebApp } from 'meteor/webapp';

WebApp.rawConnectHandlers.use(
  Meteor.bindEnvironment((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    req.dynamicHead =
      (req.dynamicHead || '') +
      '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">';

    next();
  })
);
```

i do see everything shift down a bit. now the top/bottom padding is the same, but the height of the app is still too small.

![screen shot 2017-10-23 at 6 12 17 pm](https://user-images.githubusercontent.com/437029/31915805-e7053e84-b81d-11e7-8abb-9c9edacb6a54.png)

**Comment by bmanturner** [comment]
Try using a container of height: 100vh around everything. When I fixed my app for iOS11 I had to change a lot of heights from 100% to 100vh

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by markoshust** [comment]
Thanks. Tried that, no change here.

**Comment by markoshust** [comment]
I think the root of the issue here is that it is not a display concern. `window.screen.availHeight` is still reporting 667, which is incorrect. no matter what i do display or html-tag wise, the height will still be 667.

**Comment by derwaldgeist** [comment]
I’ve seen in your workaround attempt that you added the meta tag to the existing ones in the header. When I tried this, iOS ignored it. This is why I asked for a way to replace the meta tag in #9041.

**Comment by bmanturner** [comment]
I'm using 1.6-rc.16 with the patched cordova-plugin-statusbar and viewport=cover in my header and my app displays fine (after some CSS tweaking)...

![screen shot 2017-10-22 at 5 51 40 pm](https://user-images.githubusercontent.com/8716214/31947969-32206a10-b89b-11e7-9288-09b1f9fae953.png)

**Comment by derwaldgeist** [comment]
@bmanturner How exactly did you set the viewport?

**Comment by bmanturner** [comment]
@derwaldgeist 

```<meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">```

One thing I did notice is that using the new iphonex_portrait splashscreen doesn't work. I had to add the following to my mobile-config.js

```
App.appendToConfig(`
  <splash src="../../../public/resources/ios/splash/Default@3x~universal~anyany.png" />
`);
```

Also make sure you're using a commit of ```cordova-plugin-statusbar``` that includes the iOS11 fix.

**Comment by markoshust** [comment]
@bmanturner note that the new splashscreen value is `iphoneX_portrait` (capital X). seems to be working for me.

yes, indeed looks like my app is riddled with absolute position and old styling concepts. time to move to flexbox and css grid. arg.

adding it to `client/index.html` definitely seems like enough. ios is not displaying the `viewport-fit` attribute with safari inspector -- that said, it is definitely being applied, as chrome is saying `The key "viewport-fit" is not recognized and ignored.` in the console, and styling in ios is changing with the attribute added.

all that said, the root of this ticket, `window.screen.availHeight`, is still being misreported as 667.

**Comment by bmanturner** [comment]
@markoshust That was a typo. iphoneX_portrait did work as far as showing that particular splashscreen, but the screenheight was only right if I used the 'storyboard' splashscreen. I'll try again later to confirm.

**Comment by markoshust** [comment]
hmm I wonder if that is my issue. what is a “storyboard splashscreen”, and
how does it differ from the suggested iPhoneX portrait size?

**Comment by bmanturner** [comment]
Sorry if I wasn't using the proper name for it. It's 2732x2732 and I specify the directory in mobile-config.js

```
App.appendToConfig(`
  <splash src="../../../public/resources/ios/splash/Default@3x~universal~anyany.png" />
`);
```

**Comment by markoshust** [comment]
2732x2732 sounds like an icon (square proportions). Don’t splash screens
need to be in the area of 16:9 aspect ratio? Just want to make sure we are
talking about the same thing.

**Comment by bmanturner** [comment]
Scroll down to 'Launch storyboard images': https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

It's a square so that it can be used in both landscape and portrait.

**Comment by markoshust** [comment]
@bmanturner bingo. the storyboard images fixed it as you proposed with `appendToConfig`. i'll open another issue for meteor to properly support storyboard launch images.

fyi:
`Default@3x~universal~anyany.png` === 2208x2208
`Default@2x~universal~anyany.png` === 2732x2732

they are reverse of what i thought, and that hung me up a little. after adding the storyboard images, the iphone x is properly reporting an `availHeight` of 812. yiptee do! really appreciate everyones help with this one, this was a tough cookie.

**Comment by bmanturner** [comment]
@markoshust 

Were you able to get the new ```safe-area-inset-*``` CSS rules working with cordova? I want to make sure it's a Meteor problem, and not just an issue with my code.

Didn't know how else to ask you.

**Comment by markoshust** [comment]
@bmanturner sorry not using `safe-area-inset-*` rules anywhere

**Comment by markoshust** [comment]
@bmanturner i can confirm all fo the safe-area-inset-* rules work just fine with Meteor. setting the storyboards is crucial to get the correct screen size display on iPhone X.

**Comment by derwaldgeist** [comment]
@markoshust Yeah, setting the splash images correctly solved the problem for me, too. Would have never expect that this is the cause for everything. Very strange. Thanks for the hint!
