### ISSUE TITLE
Meteor.userId() returns another userId

### ISSUE THREAD

**Issue by rolljee** [meteor/meteor#9209]
__The problem__

- From a session connected as a user `zb2NkzZahSoz2QM3D`, I'm initiating a connection to a google api. (Google +APi)
- Once i got the url to be rediected I open a new window from this user session
- Google redirect me back (after accepting some policies) to my application at a specific route `/mycallback`
- I'm using Meteor.userId() on the template route (Iron:router). 
- Surprisingly, Meteor.userId() return a completly different userId `FJk8tLPrAXnrFF2TW` (a random one from my database)

I'm not using private browsing, and I tried using Safari and Chrome browsers. (last version for both of them)

I don't know how to make a better step to reproduce since it only happen when I'm using this third party application (which needs credentials)

First screenshot with the application i'm connected
![screen shot 2017-10-11 at 14 53 08](https://user-images.githubusercontent.com/10114634/31441607-f5c9d7ba-ae93-11e7-8365-dfe5369f330c.png)

The second screenshot after i've been redirected

![screen shot 2017-10-11 at 14 50 22](https://user-images.githubusercontent.com/10114634/31441554-d2f6f5ba-ae93-11e7-9219-4beaff1b876f.png)

**Comment by TheRealNate** [comment]
Do you stay logged in to the other user, or does it just return it that once?

**Comment by hwillson** [comment]
Sorry to hear you're having trouble @rolljee! Unfortunately, there really isn't enough here to help troubleshoot further. If there's anyway you can get a reproduction together, that would really help. I know reproductions aren't always easy to create, but without any extra debugging details we can't really help much. I'll close this for now, but I'll happily re-open if you're able to provide anything that can help point towards or demonstrate a problem. Thanks!
