### ISSUE TITLE
process.cwd() points to the last folder in the packages/ directory during development

### ISSUE THREAD

**Issue by sylvaingi** [meteor/meteor#921]
Since 0.6.0 process.cwd() is not anymore on the root of the project if there are custom packages in the packages/ folder. It now points to the last package in that directory.

It can be observed on https://github.com/avital/meteor-xml2js-npm-demo, within xml2js-demo.js process.cwd() points to "[...]/meteor-xml2js-npm-demo/packages/xml2js".

**Comment by dcsan** [comment]
during dev but not after deployment
