### ISSUE TITLE
make meteor build fail if node_modules is missing

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#9212]
I spent a long time trying to determine why the `meteor build` output was different on my CI server than on my local machine (see #9211) and it took me an embarrassingly long time to realize it was just because I needed to run `meteor npm install` before `meteor build`.

Shouldn't `meteor build` just fail if `node_modules` is missing?  At least if there's a `package.json` present with dependencies in it?  That would save others from wasting time figuring this out.

**Comment by abernix** [comment]
Could you open this in the feature requests repository, per the [`ISSUE_TEMPLATE.md`](https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md)?

> * 💡 Feature requests?
>          Visit the feature request repository (https://github.com/meteor/meteor-feature-requests).

**Comment by jedwards1211** [comment]
Okay, sorry.  I saw this more as a bug than a feature request
