### ISSUE TITLE
Check should return a more descriptive error message

### ISSUE THREAD

**Issue by juho** [meteor/meteor#9220]
`check()` currently returns match errors like:

```
Match error: Expected string, got undefined
```

which don't bubble well. It would be more helpful if it also gave the key it's hanging up on or include a full stack (maybe just in development).

**Comment by hwillson** [comment]
Thanks for submitting this feature request @juho. GitHub issues here are reserved for Meteor bugs however; would you mind re-opening this request over in the Meteor feature request repo (https://github.com/meteor/meteor-feature-requests)?

**Comment by juho** [comment]
Ah sure, thanks
