### ISSUE TITLE
Template.<name>.helрers is not a function

### ISSUE THREAD

**Issue by TheRealNate** [meteor/meteor#9223]
Running on latest version. I'll try making a reproduction but I wanted to report this and see if anybody knows what could be causing this. I tried:

- Npm update
- Meteor update
- Meteor reset
- Changing the name of the template from main to home

Error message in browser console:
`
Uncaught TypeError: Template.home.helрers is not a function
    at main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at app.js?hash=5415e32142665a8e52334683bf28d395ada087bc:681
`

**Comment by hwillson** [comment]
Thanks @TheRealNate - when you say the latest version, do you mean Meteor 1.5.2.2? This issue hasn't been reported by anyone else, so please do provide a reproduction.

**Comment by TheRealNate** [comment]
@hwillson yes, 1.5.2.2, sorry. I'll try and get a reproduction together.

**Comment by TheRealNate** [comment]
Reproduction done. Simply clone it, add the babel runtime package, and run.

https://github.com/TheRealNate/meteor-9223

I'm dumbfounded. I literally removed everything, yet it's still coming. I have absolutely no idea how this is happening.

**Comment by klaussner** [comment]
@TheRealNate There's a wrong character on the first line of `client/main/main.js`. If you look at the output of `xxd client/main/main.js`, you can see that the `p` in `helper` is not encoded correctly:

```
00000000: 5465 6d70 6c61 7465 2e68 6f6d 652e 6865  Template.home.he
00000010: 6cd1 8065 7273 287b 0a0a 2020 7465 7374  l..ers({..  test
...
```

Just re-type the `p`, then it should work. :sweat_smile:

**Comment by TheRealNate** [comment]
@klaussner Wow, thats so weird. Thank you for your help! I better report that to Cloud9 (my IDE service)
