### ISSUE TITLE
[1.5.2.2] Production build fails with UglifyJs error while minifying [OS X]

### ISSUE THREAD

**Issue by dmitry-salnikov** [meteor/meteor#9224]
Both `meteor build` and `meteor --production` fail, with the next error:
```
   While processing files with webpack:webpack (for target os.osx.x86_64):
   server/main.js: server.js from UglifyJs
   Unexpected token: name (newObj) [./~/hoek/lib/index.js:33,0]
```
Development build is running OK.
The steps I've tried with no success:

- revert code base to old version with Meteor 1.5.1, which was packaged OK and still running on production for two months - and failed to build it now, with the same error;
- `rm -rf .meteor/local/bundler-cache`
- `meteor reset && meteor rebuild`
- full meteor reinstall via script;
- `meteor npm cache clean && npm cache clean` (using same versions as meteor's built-in, 4.8.4 + 4.6.1);
- checked out comments on #9138, #9181, #9122, replaced minifier package with `abernix:standard-minifier-js`, didn't help. 

I've googled a bunch of UglifyJS issues, but I can't directly modify configs because of using deprecated build system [thereactivestack-legacy](https://github.com/thereactivestack-legacy/meteor-webpack) with webpack. I've tried to get rid of it (assuming that meteor 1.5 can fully replace it), but I'm not so strong in web dev and was lost in thousands of errors occured.

Project `packages` and `versions` files here: https://gist.github.com/dmitry-salnikov/e91464b82f882c6fe5ac6c83c6a33109. Not sure what else info could be helpful.

Thanks in advance for any thoughts.

**Comment by dmitry-salnikov** [comment]
Thanks @klaussner , here it is: https://gist.github.com/dmitry-salnikov/5fb78fa6a49b4da679f731bf4adb9341

**Comment by klaussner** [comment]
The `request` package (version 2.83.0) in your `node_modules` directory could be the problem. Can you try to downgrade it to version 2.81.0 and run `meteor --production` again?

```
meteor npm install request@2.81.0
```

**Comment by dmitry-salnikov** [comment]
After downgrading request to 2.81.0 build still failing, but error message has changed:
```
   While processing files with alex509:webpack (for target web.browser):
   client/main.js: web.js from UglifyJs
   `comments` is not a supported option
```
Actually, I've figured out that the only right thing to do is to remove completely webpack:webpack and related packages. After a few sleepless nights, it's almost completed, the only remaining thing to fix is `juliancwirko:postcss` which fails the build with 'fs not found' node-related issue.

Anyway, thank you @klaussner for help, your smiley pointed me to the right direction :D

**Comment by hwillson** [comment]
> I've figured out that the only right thing to do is to remove completely webpack:webpack and related packages.

Definitely a good idea given the state of that project. Looks like we're all set here then, so I'll close this off. Thanks!
