### ISSUE TITLE
tab key doesn't work in forms

### ISSUE THREAD

**Issue by AaronVasquez** [meteor/meteor#9229]
I have a simple form. Usually hitting the tab key will move focus to the next input. This seems to be disabled. (I am using Meteor with React). Has anyone else run into this?

```
<form>
  <input />
  <input />
</form>
```

**Comment by hwillson** [comment]
Hi @AaronVasquez - GitHub issues here are reserved for bugs with Meteor itself. This doesn't sound like a Meteor bug, but if you think it is and can provide a runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)), we'll happily take a look. For Meteor and React usability questions, you're better off asking your question on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`). Closing for now - thanks!
