### ISSUE TITLE
1.6-rc.8: Run of builded nodeJS application never ends

### ISSUE THREAD

**Issue by jaqua** [meteor/meteor#9230]
I've build the nodeJS application (`meteor build`) of my meteorJS app. I used 1.6-rc.8.

First I did run 

    (cd programs/server && npm install)

Everything is installed as expected. But if I want to run the application with

    MONGO_URL=mongodb://localhost:27017/myapp ROOT_URL=http://localhost PORT=3000 node main.js

Nothing happens. There is no output at all, so I don't know where to start debugging.

$ node -v: v8.6.0
$ npm -v: 5.3.0

**Comment by klaussner** [comment]
If there's no output, then the server started without errors (and it will run until you stop it), so there should be nothing to debug. :smile: Is your app reachable at `http://localhost:3000`?

**Comment by jaqua** [comment]
No, the app is not reachable. And normaly there appears `App is running at http://localhost:3000`. But this is missing. There is no output at all.

**Comment by klaussner** [comment]
That message is only shown during development, not in a production build.

**Comment by jaqua** [comment]
Oh, sorry. That's my fault.
