### ISSUE TITLE
Unnecessary server restart when changing client files

### ISSUE THREAD

**Issue by fabianfabian** [meteor/meteor#9232]
Starting from an application created with  `meteor create myapp --full` changing any .js file in the folder `/imports/ui` restarts the server even though any of the ui code is not referenced in any server files. Changing .html files is fine and only refreshes the client. Moving the entire `/imports/ui` folder to `/imports/client/ui` (and fixing the import references) seems to fix this problem.

I'm using Meteor 1.5.2.2 on macOS High Sierra.

**Comment by klaussner** [comment]
There's already a feature request for that: https://github.com/meteor/meteor-feature-requests/issues/133. :slightly_smiling_face:
