### ISSUE TITLE
running meteor npm install without a package.json should error gracefully

### ISSUE THREAD

**Issue by chrisbutler** [meteor/meteor#9233]
this makes it look like a permissions issue, but it's actually looking in completely the wrong place

and a simple `meteor npm init -y` solves it, after hours of looking and finally catching it hidden in https://guide.meteor.com/1.3-migration.html

```
meteor npm install --save babel-runtime
npm WARN checkPermissions Missing write access to /Users/CButler/Sites/node_modules
/Users/CButler/Sites
└─┬ babel-runtime@6.26.0
  ├── core-js@2.5.1
  └── regenerator-runtime@0.11.0

npm WARN enoent ENOENT: no such file or directory, open '/Users/CButler/Sites/package.json'
npm WARN Sites No description
npm WARN Sites No repository field.
npm WARN Sites No README data
npm WARN Sites No license field.
npm ERR! path /Users/CButler/Sites/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/CButler/Sites/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/CButler/Sites/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/CButler/Sites/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/CButler/.meteor/packages/meteor-tool/.1.5.2_2.162o8z9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-10-14T19_40_16_142Z-debug.log
```

**Comment by benjamn** [comment]
A `meteor npm ...` command is just a thin wrapper around the same `npm ...` command, and this is the output of `npm install --save babel-runtime` when there's no `package.json` file. Fixing this would require somehow keeping `meteor npm` and `meteor node` from looking for `node_modules` directories outside the current app. While that's tempting, I don't have a good idea how to implement it, and I worry that would have negative consequences for developers who rely on the current behavior.

**Comment by chrisbutler** [comment]
@benjamn that makes sense, i assumed that there was a reason this wasn't already implemented

with that in mind, rather than limiting the behavior of npm install, can we add some kind of stopgap for users upgrading from pre 1.3?

My main concern is that if i do `meteor update` in a < 1.3 app, I can't run the server without installing the babel-runtime, and I can't install that without a `package.json` file... but there's nothing anywhere obvious to indicate this to me...

In order to update, I'd have to know to search for a guide to migrate between these versions, which is probably causing some frustration out there (or even abandonment).

I realize it's kind of ugly to have some conditional logic in the `update` command, but I think a special case for upgrades from < 1.3 that prints an un-missable note about this, and/or a link to the migration guide?

**Comment by hwillson** [comment]
Thanks for reporting this. As mentioned in https://github.com/meteor/meteor/issues/9233#issuecomment-336663097 this is by design, meaning it's not a bug. If you'd like to see changes put in place to improve this, please consider opening a new feature request to track this (http://github.com/meteor/meteor-feature-requests). Thanks!
