### ISSUE TITLE
Exported Arrow functions in meteor not working after meteor 1.6 upgrade  

### ISSUE THREAD

**Issue by avinashpandit** [meteor/meteor#9239]
Server side main.js 

import ExpTest from "./test1"; 
var expTest = new ExpTest('test');

test1.js

expTest  = (test) => {
    var test = test;
    return {
        test: test,
    }
};
export default expTest;

Above code works perfectly fine in meteor 1.5.2.2 
But once i switch from 1.5.2.2 to 1.6-rc.3 , i get following error 

=> Exited with code: 1
W20171016-17:13:19.582(-7)? (STDERR) /Users/avinashpandit/.meteor/packages/meteor-tool/.1.6.0-rc.3.1tm8nak++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171016-17:13:19.582(-7)? (STDERR) 						throw(ex);
W20171016-17:13:19.582(-7)? (STDERR) 						^
W20171016-17:13:19.583(-7)? (STDERR)
W20171016-17:13:19.583(-7)? (STDERR) TypeError: ExpTest is not a constructor
W20171016-17:13:19.583(-7)? (STDERR)     at main.js (server/main.js:8:15)
W20171016-17:13:19.583(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171016-17:13:19.583(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171016-17:13:19.583(-7)? (STDERR)     at /avinash/meteor-projects/cointest/.meteor/local/build/programs/server/app/app.js:220:1
W20171016-17:13:19.583(-7)? (STDERR)     at infos.forEach.info (/avinash/meteor-projects/cointest/.meteor/local/build/programs/server/boot.js:414:13)
W20171016-17:13:19.584(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20171016-17:13:19.584(-7)? (STDERR)     at /avinash/meteor-projects/cointest/.meteor/local/build/programs/server/boot.js:413:9
W20171016-17:13:19.584(-7)? (STDERR)     at /avinash/meteor-projects/cointest/.meteor/local/build/programs/server/boot.js:463:5
W20171016-17:13:19.584(-7)? (STDERR)     at Function.run (/avinash/meteor-projects/cointest/.meteor/local/build/programs/server/profile.js:510:12)
W20171016-17:13:19.585(-7)? (STDERR)     at /avinash/meteor-projects/cointest/.meteor/local/build/programs/server/boot.js:462:11

Following is my package.json and meteor packages under 1.5.2.2
{
  "name": "test1",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.2.4"
  }
}

//packages
meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.2.2                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.1.2    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.8.3              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.4            # Server-side component of the `meteor shell` command

kadira:flow-router      # FlowRouter is a very simple router for Meteor
kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
less@2.7.9                    # Leaner CSS language

practicalmeteor:mocha             # A package for writing and running your meteor app and package tests with mocha
johanbrook:publication-collector  # Test a Meteor publication by collecting its output

vs In meteor 1.6 

meteor-base@1.2.0-rc.3             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.3.0-rc.3                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0-rc.3    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.9.0-rc.3              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.0-rc.3            # Server-side component of the `meteor shell` command

kadira:flow-router      # FlowRouter is a very simple router for Meteor
kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
less@2.7.11-rc.3                    # Leaner CSS language

practicalmeteor:mocha             # A package for writing and running your meteor app and package tests with mocha
johanbrook:publication-collector  # Test a Meteor publication by collecting its output

This is sample files i published. My project uses lots of arrow functions and i don't want to use class declaration instead of arrow functions (too many files to modify ). What could be the issue with arrow functions in meteor 1.6 ?

**Comment by hwillson** [comment]
@avinashpandit I've confirmed the exporting of arrow functions is working with 1.6. Maybe try using a more recent release candidate, like `1.6-rc.13`? If this problem still persists, please consider posting a runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!
