### ISSUE TITLE
No Support For Ipad Pro (Launch Storyboard Images)

### ISSUE THREAD

**Issue by andyrichardson** [meteor/meteor#9240]
**Description**
Meteor apps do not run in native resolution on Ipad Pro (12.6 inch, 1st gen).

**Effected versions**
1.5.2 (current) and older

**Cause**
No support for storyboard images in `mobile-conifg.js`. 

**Proposed solution**
Add storyboard support to `mobile-config.js`
    
    // mobile-config.js
    
    App.launchScreens({
      default_2x_universal_anyany: "resources/splashscreens/Default@2x~universal~anyany.png",
      default_3x_ipad_comany: "resources/splashscreens/Default@3x~ipadl~comany.png",
      ...
    });

**Resources**
See [bug description](http://www.cordovacircus.com/articles/ipad-pro-and-cordova) and [Cordova documentation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/#launch-storyboard-images).

**Comment by hwillson** [comment]
@andyrichardson This was addressed in https://github.com/meteor/meteor/pull/9198, and has been merged. These changes will likely be coming in 1.5.3. Thanks!

**Comment by skirunman** [comment]
@hwillson We may want to re-open this issue as the changes I made in https://github.com/meteor/meteor/pull/9198 for iPad Pro 10.5" and 12.9" were removed in https://github.com/meteor/meteor/pull/9213/commits/0ab32772d3c1a0fee094d17e46b8d7ba05edcb95 as Apple / Xcode 9,  and therefore `cordova-ios`, does not support using static images for these splash screen sizes.

Instead Apple and Cordova recommends using Launch Storyboards. We can add this support to a Meteor Cordova app today in `mobile-config.js`  like

```
App.appendToConfig(`
  <splash src="../../../resources/splash/ios/Default@3x~universal~anyany.png" />
`);
```

I'm not sure if we should make changes to our parsing of `mobile-config.js` to support this or just update the documentation. In any case you can see where[ cordova-ios supports this here](https://github.com/surajpindoria/cordova-ios/blob/c3d24a9f02aa096c2b8951cc6980eefbbd26fd72/bin/templates/scripts/cordova/lib/prepare.js#L777).

**Comment by hwillson** [comment]
Thanks @skirunman - I think documenting this for now is our best bet. I've opened https://github.com/meteor/guide/issues/675 to track this, so we can keep this issue closed. Thanks again!

**Comment by markoshust** [comment]
This ticket should probably be reopened. Xcode is replacing all app launch screens with storyboards in Xcode 11 and moving forward, and there is currently no support in storyboard images in Meteor.

It should probably be recommended in the Meteor guide to just use storyboard images instead of setting all of the app launch sizes, as the latter is super time-consuming. Adding this to mobile-config.js gets the new sizes to work:

```
App.appendToConfig(`
  <platform name="ios">
    <splash src="../../../resources/splash/Default@2x~universal~anyany.png" />
    <splash src="../../../resources/splash/Default@3x~universal~anyany.png" />
  </platform>
`);
```

`Default@2x~universal~anyany.png` is size 2732x2732
`Default@3x~universal~anyany.png` is size 2208x2208

**Comment by markoshust** [comment]
FYI the above is also required for iPhone X support -- without this setting the entire app is wonky (see https://github.com/meteor/meteor/issues/9208 for screenshots). Without this iPhone X does not work/display correctly with Meteor+Cordova.

**Comment by skirunman** [comment]
Meteor Guide was updated to mention using [Story boards](https://guide.meteor.com/mobile.html#configuring-app-icons-and-launch-screens), especially for iPhone X, and the definitions for the unsupported iPad Pros were removed in this commit https://github.com/meteor/meteor/pull/9213/commits/0ab32772d3c1a0fee094d17e46b8d7ba05edcb95 as I mentioned above.

When Xcode 11 comes out I think we will need to integrate in the version of `cordova-ios` that only supports Story boards.

What I would really like to see is this [Feature Request](https://github.com/meteor/meteor-feature-requests/issues/112) implemented to decouple Cordova versions from Meteor.
