### ISSUE TITLE
High import time on accounts-base/server_main.js

### ISSUE THREAD

**Issue by juho** [meteor/meteor#9248]
On 1.5.2.2, from profile:
```
 other require("./node_modules/meteor/accounts-base/server_main.js").4,470 ms (1)
```

This is adding ~4-5 seconds to each reload and is the second largest operation besides the actual build process in our chain right now. I've looked around the code but can't determine exactly what's doing the heavy lifting. Would it be possible to somehow optimize or debug this further?

**Comment by benjamn** [comment]
What version of `accounts-base` do you see in your `.meteor/versions` file?

**Comment by juho** [comment]
`accounts-base@1.3.4`

**Comment by hwillson** [comment]
@juho Have you tried with Meteor 1.6 and if so what profiling times are you seeing?

**Comment by juho** [comment]
We haven't upgraded yet. I'll check back once we do

**Comment by hwillson** [comment]
I'll close this for now, but if you're still seeing this issue after updating to Meteor 1.6.0.1, let us know. Thanks!
