### ISSUE TITLE
First page load is really slow - Angular 1.3 + Meteor 1.5.2.2

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9252]
My application is based on angular 1.3 + Meteor 1.5.2.2
And my page loads are slow, especially the first-page load.

How can I optimize these page loads? Is there any tool or something to debug what is taking so much time?
I have been reading articles, some of them were saying that images should not be placed in `myapp/public` folder, I don't understand what is the purpose of `myapp/public` folder then?

I would really appreciate some good performance tips to boost up my application. Thanks

**Comment by hwillson** [comment]
@MartiniHenry1988 - GitHub issues here are reserved for bugs with Meteor. For help with using the framework and its related ecosystem, please try posting on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (using the tag `meteor`).
