### ISSUE TITLE
Issue with loading ios simualtor on new Mac High Sierra 10.13 

### ISSUE THREAD

**Issue by wildaces215** [meteor/meteor#9253]
Recently Mac updated it operating system and released High Sierra 10.13. I also tryed to build an app using the ios simulator that meteor provides  but it run on iphone 10 with ios 11. Is there a way to change the setting so that I cna run it on say an iphone 6 or iphone 7?

**Comment by bmanturner** [comment]
From the menubar of the simulator app you can select the default device. There is also a menu option that provides additional configuration options. No changes required on MDG's part.
