### ISSUE TITLE
Is this the wrong array index?

### ISSUE THREAD

**Issue by tbsisan** [meteor/meteor#9259]
https://github.com/meteor/meteor/blob/1687537f6ea03312183059fed45f12f350de2f17/packages/ddp-server/livedata_server.js#L938

It seems that it should be 
```javascript
if (httpForwardedCount < 0 || httpForwardedCount >= forwardedFor.length)
      return null;

return forwardedFor[forwardedFor.length - 1 - httpForwardedCount];
```

My DDPRateLimiter was using the wrong IP address because of this.  Also, I would suggest that IPv6 addresses should only rate-limit based on the first 64 bits of the address, since it is free to create new IPv6 addresses?

**Comment by hwillson** [comment]
@tbsisan `httpForwardedCount` is determined by looking at the `HTTP_FORWARDED_COUNT` environment variable. If you're saying that the count subtracted from `forwardedFor.length` should be increased by 1, try bumping your `HTTP_FORWARDED_COUNT` environment variable up by 1.

I know the documentation for this isn't great, but you can find more details here:

- https://docs.meteor.com/environment-variables.html#HTTP-FORWARDED-COUNT
- https://docs.meteor.com/api/connections.html#Meteor-onConnection

Regarding:

> I would suggest that IPv6 addresses should only rate-limit based on the first 64 bits of the address, since it is free to create new IPv6 addresses

Could you open this in a new feature request over in http://github.com/meteor/meteor-feature-requests? Thanks!

**Comment by tbsisan** [comment]
From the Meteor Docs:
```
Set this to however many number of proxies you have running before your Meteor application. For example, if have an NGINX server acting as a proxy before your Meteor application, you would set HTTP_FORWARDED_COUNT=1. If you have a load balancer in front of that NGINX server, the count is 2.
```

What I have is cloudflare, then my app, so x-forwarded-for has 2 IP addresses: my home computer, then cloudflare's.  I set HTTP_FORWARDED_COUNT=1, because there is 1 forwarding proxy.  It seems both that it is intuitive and also explicitly stated in the docs, so I'm not sure what I am missing.  

I will open the suggested feature request.

**Comment by tbsisan** [comment]
I sitll maintain that this is a bug.

**Comment by hwillson** [comment]
@tbsisan Can you dump your socket headers to make sure the `x-forwarded-for` header really has the number of addresses in it you expect?

```js
if (Meteor.isServer) {                                                               
  Meteor.onConnection(connection => {                                                
    console.log(connection.httpHeaders);                                             
  });                                                                                
} 
```
