### ISSUE TITLE
Too slow when download meteor

### ISSUE THREAD

**Issue by leapit** [meteor/meteor#9262]
<img width="631" alt="wx20171027-222030 2x" src="https://user-images.githubusercontent.com/1665671/32108741-3f81eea4-baf8-11e7-8394-1fde65faff18.png">

see above,it really slow,about two hours,now still downloading.

is there something wrong with the host?why  not supply a common way for installing,something like npm.

**Comment by leapit** [comment]
more
<img width="624" alt="wx20171027-224405 2x" src="https://user-images.githubusercontent.com/1665671/32109835-778f2bba-bafb-11e7-940c-272c8d198222.png">

**Comment by Kingbalou** [comment]
same here on windows , it took me like more than half an hour to complete meteor installation ... and my internet connection is not the problem (fiber).

**Comment by hwillson** [comment]
@leapit Is this problem still happening? What happens if you try to download the following file directly?

```
https://static-meteor.netdna-ssl.com/packages-bootstrap/1.6/meteor-bootstrap-os.osx.x86_64.tar.gz
```

@Kingbalou Meteor's new Windows installation process (that leverages [Chocolatey](https://chocolatey.org/packages/meteor)) should be officially available later today/tomorrow. Hopefully you'll find the new installation process to be much better.

**Comment by abernix** [comment]
@Kingbalou The [Chocolatey package](https://chocolatey.org/packages/meteor) is available now, using:

    choco install meteor

If you continue to have problems downloading, please do let us know.  Hopefully the Chocolatey installer will provide more feedback on the console about what is actually happening.  There are `--verbose` and `--debug` flags available which will likely be helpful.

**Comment by leapit** [comment]
@hwillson seems good today,should be a server connection issue,may be the server not stable.

**Comment by Kingbalou** [comment]
I was already using Choco but extracting take so much time ! 
Even using `--verbose` it's just stuck on extracting ...

**Comment by abernix** [comment]
@CorentinDy What if you disable Windows Defender?  The extraction still places a _lot_ of files into the installation directory and if they're all getting scanned, it could be slow.  If you continue to have problems, please check the https://github.com/meteor/meteor-chocolatey-installer/issues repository for an appropriate, possibly related issue.

**Comment by ptyx11** [comment]
This issue is still present. It is taking hours to download on mac

**Comment by Bektaz** [comment]
I have read all the comments and now the problem is still the same. Downloading is too slow even though internet speed is high enough. I couldnt download it completely because it stucks at some percentage and nothing happens. Starting installation process over and over.

**Comment by 564064202** [comment]
it's too slow! do you  want to abandon ??????? so you limit the speed??

**Comment by Shivansh-yadav13** [comment]
On windows, it's too slow

**Comment by the-unfactoring-guru** [comment]
Supposedly is that meteorjs needs 10<=node version <= 14 i tried with every node version in that range and nothing. Come on meteor... >:(

**Comment by Shubham-Rasal** [comment]
No update is given whether the install is going on or not while using npm install.

**Comment by zodern** [comment]
@Shubham-Rasal one of the goals of the npm installer was to do a better job of that. At what step does it not stop giving you updates? What does the terminal show?

**Comment by Shubham-Rasal** [comment]
The npm terminal window is not available. Though I am now trying to install meteor via choco.

**Comment by Shubham-Rasal** [comment]
![image](https://user-images.githubusercontent.com/95695273/185269986-499643ee-3fe1-40cc-845c-380274607057.png)
Here is the choco install pic. It is stuck on 18% for 30 mins.

**Comment by Shubham-Rasal** [comment]
Done with installation 😊. Turning off the antivirus did the trick !!
