### ISSUE TITLE
[Help] Forum account problem

### ISSUE THREAD

**Issue by alexandesigner** [meteor/meteor#9264]
Please, someone can help me with a question about the Forum .. I am with my user without being able to answer the questions, I'v been send contact via email but so far I have not got a return, with whom exactly I can check if there is any problem and help me? 

My username is `alexandesigner`

I would like to participate more in the discussions in the forum, only for this I am opening this question, thank you.

@abernix @benjamn @hwillson I marked you guys for being the most active here and maybe you can help me.

**Comment by hwillson** [comment]
@alexandesigner Your forum account seems to be okay when I check. I've sent you a direct message via the forums; let's continue the troubleshooting over there. Thanks!
