### ISSUE TITLE
Meteor 1.6 - Centos7 - fibers2.0/node-gyp pb

### ISSUE THREAD

**Issue by edsoubsoub** [meteor/meteor#9269]
Hello everyone,
I'm running meteor on centos 7.
I tried to upgrade my docker meteor install to the last 1.6 release and it come that I'm having trouble with the gyp package. (1.5.2 release work perfectly)

Here is the error I'm getting :

Step 5/12 : RUN cd /service/bundle/programs/server ; npm install
 ---> Running in da2b491c75c1

> fibers@2.0.0 install /corpact-manager-1.0.5/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

linux-x64-57 exists; testing
Problem with the binary; manual build incoming
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /corpact-manager-1.0.5/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-28T16_01_18_549Z-debug.log

Thx for helping

**Comment by KoenLav** [comment]
The solution is in your error message:

sudo apt-get install g++ build-essential

(Error: not found: make imdicates that build-essential is not installed.) 
.

**Comment by edsoubsoub** [comment]
My mistake. Thx a lot

**Comment by fcoppolani** [comment]
Hi @edsoubsoub ,
did you manage to install it properly ? We have a quite similar problem (fiber 2.0 on Centos7), but a lib is missing : 

`Error: /lib64/libstdc++.so.6: versionGLIBCXX_3.4.20' not found (required by /opt/rocketchat/rocket.chat.0.60.0-rc.0/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.`


Would you have any tips on this ?

Thanks.

**Comment by edsoubsoub** [comment]
Hello,

Yes, I did exactly what Koen said: sudo apt-get install g++ build-essential

I think libstdc need to be install as well.  

Édouard

**Comment by aryeharmon** [comment]
on centos need to install gcc gcc-c++ kernel-devel

su -    
yum install make automake gcc gcc-c++ kernel-devel
