### ISSUE TITLE
Unvoluntary duplicate updates to mongo

### ISSUE THREAD

**Issue by Segev95** [meteor/meteor#9270]
Hello,

Our team built an [open source kahoot](https://gitlab.com/Dev-Team-BSMH/shablool) and we came across some peculiar [issue.](https://stackoverflow.com/questions/46928618/duplicate-writing-to-mongo)

Some of the request that we send to mongo are written several times (all the fields are exactly the same including the timestamps). We don't know why this duplication is happening.

We’re not sure if the problem rises from misunderstanding of mongodb’s update function or from inconsistency between meteor’s collection’s api and mongo’s api.

If any one has even a hunch of what’s going on we’ll love to get a clue :)

thanks!

**Comment by hwillson** [comment]
@Segev95 This is difficult to help troubleshoot without a runnable reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). That being said, have you tried leveraging a [unique index](https://docs.mongodb.com/manual/core/index-unique/) (along with [`upsert: true`](https://docs.mongodb.com/manual/reference/method/db.collection.update/#update-with-unique-indexes)) to prevent this from happening?

**Comment by abernix** [comment]
Any updates on the reproduction for this, @Segev95?

**Comment by hwillson** [comment]
We haven't received a reproduction for this, so we'll close it for now. Thanks!
