### ISSUE TITLE
[1.6] Starting meteor shell overwrite _ in the main server

### ISSUE THREAD

**Issue by gregory** [meteor/meteor#9276]
#### The version of Meteor showing the problem.
```
$ meteor --version`
 1.6
$ meteor npm version -> 
{ test: '0.0.1',
  npm: '5.4.2',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.8.1',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.42',
  zlib: '1.2.11' }
```
#### The last version of Meteor where the problem did _not_ occur (if applicable)
1.5.2 - which shipped with node version != 8.8.1

#### The operating system you're running Meteor on.

macOs Sierra beta

#### The expected behavior.

when i'm starting meteor shell, i'm not expecting _ to be overwritten on the server side. 

#### The actual behavior.

After starting a shell, _ will be undefined in the server and break the app anywhere it we used _
Stopping the shell doesn't fix the issue. 
This makes it really hard to test things in dev mode. 

#### A **simple** reproduction!

- install meteor 1.6
- write some code that rely on _. You can optionally define _ = require('underscore') (it should be available globally already since underscore ship with meteor)
- start the server
- start a shell
- notice _ is undefined
- notice when you do const _ = require('underscore') and _ is still undefined
- call your function relying on _ and watch it fail. 

This might be related: https://github.com/nodejs/node/issues/14226

**Comment by klaussner** [comment]
You can work around the problem by not relying on the global `_`. If you import or require the `underscore` package, `_` is still available in the module that imports it:

```js
import { _ } from 'meteor/underscore';
```
or
```js
const { _ } = require('meteor/underscore');
```

**Comment by gregory** [comment]
Anyone facing this could run this to import underscore in all the files 
`git grep -l '_\.' ./{lib,server,imports,ANY_OTHER_BACKEND_FOLDER} | xargs -I{} sed -i "" -e '1 s/^/import _ from "meteor\/underscore"\'$'\n/' {}`

**Comment by abernix** [comment]
This is due to https://github.com/nodejs/node/commit/ad8257fa5b in https://github.com/nodejs/node/pull/5535 which changed in Node 6.  We might be able to avoid the problem by `repl.eval`-ing something which sets `_` during the [`packages/shell-server/shell-server.js` `startREPL`](https://github.com/meteor/meteor/blob/release-1.6/packages/shell-server/shell-server.js#L171).

**Comment by gregory** [comment]
it's also breaking all packages relying on _ actually. 

```

I20171031-17:58:59.386(-7)? Exception from sub reactive-table-persons id gpreZ2GjuZ5jaeHnE TypeError: Cannot read property 'isFunction' of undefined
I20171031-17:58:59.386(-7)?     at Subscription.<anonymous> (packages/aslagle_reactive-table.js:283:13)
I20171031-17:58:59.386(-7)?     at Subscription.newPublishFunction (packages/peerlibrary_reactive-publish/server.coffee:191:30)
I20171031-17:58:59.387(-7)?     at Subscription.newFunc (packages/peerlibrary_subscription-data/server.coffee:23:19)
I20171031-17:58:59.387(-7)?     at packages/matb33_collection-hooks.js:307:21
I20171031-17:58:59.387(-7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171031-17:58:59.387(-7)?     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
I20171031-17:58:59.387(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171031-17:58:59.387(-7)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
I20171031-17:58:59.387(-7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171031-17:58:59.388(-7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20171031-17:58:59.388(-7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20171031-17:58:59.388(-7)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20171031-17:58:59.388(-7)?     at packages/ddp-server/livedata_server.js:559:43

```

**Comment by abernix** [comment]
@gregory That last error sheds a different light on the problem.  The `aslagle:reactive-table` doesn't properly depend on `underscore` on the `server` architecture ([see here](https://github.com/aslagle/reactive-table/blob/bdf40f48f9e9dd374a2b77048c0bce65030ecd00/package.js#L12)), even though the [`lib/server.js`](https://github.com/aslagle/reactive-table/blob/bdf40f48f9e9dd374a2b77048c0bce65030ecd00/package.js#L28) dependency uses `_` [on this line](https://github.com/aslagle/reactive-table/blob/bdf40f48f9e9dd374a2b77048c0bce65030ecd00/lib/server.js#L14), which is supplied by the `underscore` package.  The `underscore` dependency in the `package.js` `on_use` section should be expanded to use `underscore` on `server` architecture, in addition to the `client` and the package should be republished.  Can you open an issue with the package maintainer about that?

**Comment by s7dhansh** [comment]
Faced this problem just now.
@abernix @gregory raised an issue in `aslagle:reactive-table`

**Comment by denodaeus** [comment]
Also facing the error when using _.extend in a package -- and the only way it breaks is by my extended object not having the properties it should have (it's just an empty object), which is super super super super annoying.

**Comment by abernix** [comment]
@denodaeus Is your package properly defending its dependency on `_`?  If so, can you resolve the problem until we have a solution for the `meteor shell` by explicitly importing `_` from `meteor/underscore` in the (package) file where it's used?

**Comment by denodaeus** [comment]
@abernix looks like that's a work around for now (it's several packages, but at least we have a work around) -- thanks

**Comment by eyelidlessness** [comment]
For anyone who is in the unfortunate situation that importing underscore or lodash is untenable (in my case due to usage of `_.mixin`), another workaround is to run this in `meteor shell`:

```
const lodash = require('lodash'); // Or underscore
Object.defineProperty(this, '_', { get() { return lodash; } });
```
