### ISSUE TITLE
Downloading release=1.6.0 gives a 403 Forbidden

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9280]
52.23s$ curl https://install.meteor.com/?release=1.6.0 | /bin/sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0   180k      0 --:--:-- --:--:-- --:--:--  180k
Downloading Meteor distribution
curl: (22) The requested URL returned error: 403 Forbidden
Retrying download in 5 seconds...

**Comment by klaussner** [comment]
The version is `1.6`, not `1.6.0`. Try `curl https://install.meteor.com/?release=1.6 | /bin/sh`.
