### ISSUE TITLE
practicalmeteor:mocha failing on 1.6.0

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9282]
I initially posted an issue here:
https://github.com/practicalmeteor/meteor-mocha/issues/94

But their code hasn't changed, and while investigating MochaRunner it does not have the correct methods inside it. Could it be a coffeescript issue ?

**Comment by theodorDiaconu** [comment]
https://github.com/practicalmeteor/meteor-mocha/blob/meteor/meteor/src/lib/MochaRunner.coffee

**Comment by theodorDiaconu** [comment]
Went back to 1.5.2 works flawlessly. Something spooky is going on

**Comment by hwillson** [comment]
Yes, there has been some discussion about this in https://github.com/meteor/meteor/pull/9107. I'd recommend switching over to [`meteortesting:meteor-mocha`](https://github.com/meteortesting/meteor-mocha) if you can, since it's actively maintained.

**Comment by theodorDiaconu** [comment]
Ok, if we're aware, I'll close this.

**Comment by davidworkman9** [comment]
`practicalmeteor:mocha` is what's recommended in the Meteor guide. It should probably be updated if a fix for this isn't likely to come.

**Comment by hwillson** [comment]
@davidworkman9 Would you mind opening a new issue for this over in https://github.com/meteor/guide?

**Comment by davidworkman9** [comment]
(Sure)[https://github.com/meteor/guide/issues/672]!
