### ISSUE TITLE
Fresh download of meteor-tool 1.5.2_2 now fails to compile unchanged source

### ISSUE THREAD

**Issue by vwitana** [meteor/meteor#9286]
Related: https://github.com/meteor/meteor/issues/9256

I successfully built a release version of our app using meteor-tool 1.5.2_2 on  Mon Oct 30 10:56:08 2017 UTC. On the 31st Oct our CI builds started failing, and when I attempted to rebuild the last released app version it failed too with the following error:

 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
 Aborted (core dumped)

This was on Mon Oct 31 11:34:04 2017 UTC. This error can be reproduced with a fresh download of meteor-tool 1.5.2_2  up to the time of filing this bug.

I am able to successfully build the app by copying over an older version of meteor-tool 1.5.2_2 into the broken .meteor directory

I would have expected  the behaviour of a particular version of meteor-tools should remain consistent over time.

**Comment by hwillson** [comment]
The Meteor Tool version should stay consistent, which points to something else being the problem. Is the app working if you upgrade to 1.5.4 or 1.6?

**Comment by hwillson** [comment]
We haven't heard back regarding our questions in https://github.com/meteor/meteor/issues/9286#issuecomment-347653834, so closing for now. Please post back with more details if you're interested in re-opening this issue. Thanks!
