### ISSUE TITLE
[Workaround found] Cannot install non-admin version of Window 64 bit meteor

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9288]
I cannot figure out how to install a non-admin version of Windows 64 bit meteor.

### Environment
- Windows 10 1703 (OS Build 15063.674)

### Attempts
Installed `chocolately` as instructed here: https://chocolatey.org/install using `cmd` window.

#### Attempt 1
1. Tried simply running `choco install meteor` from a non-admin window.  Was notified by `chocolately` that I could not install in a non-admin window.

#### Attempt 2
1. open a  `cmd` window with "run as administrator"
2. `choco install meteor`
3. open regular `cmd ` window
4. `meteor create t64`
5. `cd t64`
6.
```
meteor node
>process
...
arch: 'ia32',
```
I looked at the install at `C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool` and I found this folder `mt-os.windows.x86_32` which implied 32 bit.

#### Attempt 3
1. `choco uninstall meteor`
2. move `C:\Users\Bruce\AppData\Local\.meteor` to `C:\Users\Bruce\AppData\Local\.meteorOLD`
3. open a  `cmd` window with "run as administrator"
4. `choco install meteor`
5. open regular `cmd` window
6. `meteor`

**Result:** `'meteor' is not recognized as an internal or external command,
operable program or batch file.`  Meteor is only installed at `C:\Users\admin\AppData\Local\.meteor`

#### Attempt 4
1. `choco uninstall meteor`
2. cleaned up `C:\Users\Bruce\AppData\Local\.meteor` so it only had an install of meteor 1.5.2.2.
3. `choco install meteor`

**Result:** `'meteor' is not recognized as an internal or external command,
operable program or batch file.`  Meteor is only installed at `C:\Users\admin\AppData\Local\.meteor`

#### Attempt 5
1. after attempt 4 I tried copying the `1.6.0` folder from `C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool` to `C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.6.0`
2. modified `C:\Users\Bruce\AppData\Local\.meteor\meteor.bat` to point to the `1.6.0` folder

**Result**: copy failed.  It notified me that file names were too long for Windows.  When I tried to run `meteor` it failed trying to load a package that was not copied.

### Notes
Essentially, I want an install of 64 bit Windows 64 bit meteor to land here: `C:\Users\Bruce\AppData\Local\.meteor` instead of `C:\Users\admin\AppData\Local\.meteor`.

How can I make that happen?

**Comment by brucejo75** [comment]
# Workaround

- start `cmd` shell in "run as administrator" mode.
- in the command shell change 2 environment variables to your desired location:
```
set LOCALAPPDATA=C:\Users\<USERNAME>\AppData\Local
set USERPROFILE=C:\Users\<USERNAME>
```
- `choco install meteor`

## Result
meteor will install to `C:\Users\<USERNAME>\AppData\Local\.meteor` and all is good with the world!

**Comment by abernix** [comment]
> Essentially, I want an install of 64 bit Windows 64 bit meteor to land here: C:\Users\Bruce\AppData\Local\.meteor instead of C:\Users\admin\AppData\Local\.meteor.

This is the default behavior on Windows 10 for me, though admittedly I don't use `cmd`, but rather PowerShell.  Do you have a different experience based on this factor?  Also, since this seems specifically regarding the installer (and not a general Meteor + Windows problem), this seems like it would be best to open in an issue on the https://github.com/meteor/meteor-chocolatey-installer repository instead of here.

**Comment by brucejo75** [comment]
Moved to [chocolately install #2](https://github.com/meteor/meteor-chocolatey-installer/issues/2)
