### ISSUE TITLE
meteor 1.6 build fails on windows 

### ISSUE THREAD

**Issue by QHose** [meteor/meteor#9290]
hi,

I get this error when I try to build an image for linux arch via windows 10.

![image](https://user-images.githubusercontent.com/12411165/32333429-23e4ad86-bfe8-11e7-9fcc-455e2de939c1.png)

pre 1.6 this worked fine...

my create bundle script:
```
    $PROJECT_ROOT = (Get-Item -Path ".\" -Verbose).FullName
    echo "Build tool project root directory: "$PROJECT_ROOT
    $BASE_APP_NAME = "qrsmeteor"
    $BUILD_DIR = ".\.build"
    $BUNDLE_DIR = $BUILD_DIR+"\bundle"
    $VERSION = Get-Date -format yyyyMMdd-Hmm
    $DOCKER_TAG = "qhose/" + $BASE_APP_NAME + ":" + $VERSION
    Write-Host "Creating a new QRSMeteor docker image, and publish it to docker hub: $DOCKER_TAG"
    
    function Remove-PathToLongDirectory 
    {
        Param(
            [string]$directory
        )
    
        # create a temporary (empty) directory
        $parent = [System.IO.Path]::GetTempPath()
        [string] $name = [System.Guid]::NewGuid()
        $tempDirectory = New-Item -ItemType Directory -Path (Join-Path $parent $name)
    
        robocopy /MIR $tempDirectory.FullName $directory | out-null
        Remove-Item $directory -Force | out-null
        Remove-Item $tempDirectory -Force | out-null
    }
    
    echo "STEP delete old build files"
    Remove-PathToLongDirectory $BUILD_DIR

    echo "STEP build new meteor bundle"
    meteor build --architecture=os.linux.x86_64 --allow-superuser --directory $BUILD_DIR

    echo "STEP copy dockerfile to bundle folder, so docker can build the image"
    Copy-Item Dockerfile $BUNDLE_DIR
    Copy-Item startNode.sh $BUNDLE_DIR
    Copy-Item settings-development-example.json $BUNDLE_DIR    

    echo  "STEP go to bundle dir" 
    cd "$BUNDLE_DIR"

    echo "STEP build the Dockerfile (which has been copied already in the bundle dir)"
    echo "STEP Building Dockerfile via command: docker build -t $DOCKER_TAG"
    docker build "-t" "$DOCKER_TAG" "."

    echo "docker push $DOCKER_TAG"
    docker push "$DOCKER_TAG" 

    #at the end, go back to the folder where we started
    cd $PROJECT_ROOT


```

**Comment by QHose** [comment]
I guess the solution is to change 
`RUN npm install \
  && npm cache clear`

to ` RUN npm install`

**Comment by benjamn** [comment]
Oh wow, I guess `npm` has made it an error to run `npm cache clear` without the `--force` flag? That seems… aggressive… but I guess the solution is either not to clear the cache or (if you really want to clear it) use the `--force` flag.

**Comment by QHose** [comment]
Hi,

Confirmed, the build works successfully without the flag.

PS: in the meteor build docs, the new node version is not (yet) mentioned, it still talks about node 4.8


Martijn Biesbroek
Principal OEM Solution Architect

Mobile: +31 6 46119328
Skype: mbj_qliktech
Email:  Martijn.Biesbroek@qlik.com

Qlik
Evert van de Beekstraat 122
Building B, 6th floor
1118 CN Schiphol

qlik.com<http://www.qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by hwillson** [comment]
> PS: in the meteor build docs, the new node version is not (yet) mentioned, it still talks about node 4.8

@QHose Can you post a link or better yet open an issue about this in either http://github.com/meteor/docs or https://github.com/meteor/guide? Thanks!

**Comment by hwillson** [comment]
Since the original issue here has been dealt with (`npm cache clear` now requires `--force` or it errors), I'll close this off. Thanks!
