### ISSUE TITLE
How can I use DDP as a simple Websocket ? 

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9294]
My intention is simple: I want to dispatch events to a client that subscribes to a publication but I need to bypass the LocalCollections of the client for this. I don't need them stored anywhere, it's just a simple EJSON-able object.

Is this possible to do ?

**Comment by wojtkowiak** [comment]
https://github.com/wojtkowiak/meteor-custom-protocol

**Comment by wojtkowiak** [comment]
I am using my own approach in most of my projects. It's already used on production for more than two years.
The only downside is lack of support for multi instance deployments but that will be added soonish.

**Comment by theodorDiaconu** [comment]
@wojtkowiak exactly what I was looking for. I am planning on integrating this into redis-oplog to have multi-instance simple event communication. Amazing job!

**Comment by wojtkowiak** [comment]
@theodorDiaconu oh that's nice, I have also planned to use redis or a queue to back the multi instance support. If you need any support let me know. I am very interested in this :wink:

**Comment by theodorDiaconu** [comment]
@wojtkowiak sure, created an issue on your repo with some questions. The docs and the code looks very solid.

**Comment by yanickrochon** [comment]
What's the difference with this and `Meteor.methods` ? Is it a question of performance? What is it that this implementation can do that Meteor methods can't?

**Comment by wojtkowiak** [comment]
Basically the main thing is that you can think of it like invoking a client's method. So it provides you an alternative way of server -> client communication (other that pub/sub and method/response which both require polling/asking the server for data).

**Comment by yanickrochon** [comment]
Ah, I see! Thanks.
