### ISSUE TITLE
server-render statusCode 404

### ISSUE THREAD

**Issue by boomfly** [meteor/meteor#9295]
This https://blog.meteor.com/meteor-platform-is-still-alive-5f6426644555 is good tutorial how to use `server-render` package. But how to response 404 status code with `server-render`?

**Comment by boomfly** [comment]
Maybe there have way to do something like this:
```coffeescript
onPageLoad (sink) ->
  context = {}

  App = (props) ->
    <Provider store={store}>
      <StaticRouter location={props.location} context={context}>
        {routes}
      </StaticRouter>
    </Provider>

  html = renderToString(<App location={sink.request.url} />)

  sink.renderIntoElementById('app', html)

  helmet = Helmet.renderStatic()
  sink.appendToHead(helmet.meta.toString())
  sink.appendToHead(helmet.title.toString())
  sink.appendToHead(helmet.link.toString())

  return {statusCode: 404} if context.statusCode is 404
```

**Comment by hwillson** [comment]
Hi @boomfly - there is an open feature request for this over in https://github.com/meteor/meteor-feature-requests/issues/210. Please join in the discussion there. Thanks!
