### ISSUE TITLE
[1.6] SSR has worse performance than 1.5.2

### ISSUE THREAD

**Issue by antoninadert** [meteor/meteor#9297]
Using React SSR and server-render package, I noticed significantly worse performance in my Time to first paint metric since I updated my Meteor app to 1.6 

See https://github.com/antoninadert/proto-starter for a repro: Initialize the package, run google Audit tab (lighthouse) and observe the time to first paint. Then try to update to 1.6 and do the same. The time to first paint is significantly slower.

This may be related to the new server-render package but I'm not able to isolate it as Meteor 1.6 will always upgrade server-render to the latest version (0.2.0)

**Comment by benjamn** [comment]
Can you try running Meteor [from a checkout](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout) and bisecting between `release-1.5.2.2` and `release-1.6`?

**Comment by antoninadert** [comment]
I have no clue how to do this on windows, I did read your document, but when I try to start the new meteor command it does this: 
```
D:\CODE\Meteor\meteor>./meteor --help
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by hwillson** [comment]
@antoninadert Try: 

```
meteor.bat --help
```

Your point is well taken though - we should get the `DEVELOPMENT.md` doc updated with Windows instructions as well. I've made a note - thanks!

**Comment by antoninadert** [comment]
Just for you to know it tells me: 

```
'7z.exe' is not recognized as an internal or external command,
operable program or batch file.
"Please install 7z.exe (7-Zip) and put it into your PATH"
```

I will maybe reinstall it...

**Comment by hwillson** [comment]
Yes, you'll need to install http://www.7-zip.org/download.html (and add it to your `PATH` - another item we need to get into the docs).

**Comment by antoninadert** [comment]
I did
```
set PATH=%PATH%;C:\Program Files\7-Zip\
echo %PATH%
7z
```

now I can do meteor bat

**Comment by antoninadert** [comment]
It didn't work immediately, I got errors. I had to close my cmd and open a new one in admin mode. Now it seems to work.

Can you help me with the bisect as I am a noob in git as well?

**Comment by abernix** [comment]
@antoninadert The [`git bisect` documentation](https://git-scm.com/docs/git-bisect) is quite thorough, but briefly:

```sh
git bisect start <bad-ref> <good-ref>
```

So, from the Meteor checkout directory:

```sh
git bisect start release-1.6 release-1.5.2.2
```

Then, as you land on each bisection-point, in another terminal, you should run `C:\path\to\meteor-checkout\meteor.bat` and observe the behavior.  Once you've taken note, in the first terminal, you can run `git bisect bad` or `git bisect good` and Git will move you to the next commit that's on trial.  Eventually, it will hopefully tell you the exact culprit.

You'll experience some downloads of dev bundles between commits which will take time to download and extract, and you'll probably land on a couple completely broken (for other reasons) bisection points as well.  If you're on a commit which seems to be broken for other reasons, you can use `git bisect skip` to tell Git to try another option nearby.

Hope this helps!

**Comment by benjamn** [comment]
I couldn't have explained it better than @abernix. Just in case this sounds like a chore, once you get the hang of `git bisect`, I think you'll realize what an amazing power-tool it is. Thanks for helping us track this down!

**Comment by antoninadert** [comment]
I' ll do it when I have more time

**Comment by antoninadert** [comment]
Well I don't know what is wrong but I keep pressing git bisect bad and I am always to the same commit

Please note that everytime I run git bisect bad there is no output. 

```
git bisect start 'release-1.6' 'release-1.5.2.2'
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
# bad: [4bbe849b35400f9e6d495b3e9f7105f6c09b50a2] Merge pull request #9107 from GeoffreyBooth/coffee
script-2
git bisect bad 4bbe849b35400f9e6d495b3e9f7105f6c09b50a2
```

**Comment by antoninadert** [comment]
I can still reproduce it. Why don't you give it a try on a windows machine .

Isn't it too early to say you can't reproduce, where you didn't even try on a windows machine?

**Comment by antoninadert** [comment]
Now I am running this error when trying to run the meteor from the checkout in proto-starter:

```
select-string : Cannot find path 'D:\CODE\Meteor\meteor\dev_bundle\.bundle_version.txt' because it
does not exist.
At D:\CODE\Meteor\meteor\scripts\windows\check-dev-bundle.ps1:10 char:20
+ $CURRENT_VERSION = select-string -Path ($CHECKOUT_DIR + "\dev_bundle\.bundle_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\CODE\Meteor\...dle_version.txt:String) [Select-S
   tring], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SelectStringCommand
```

**Comment by antoninadert** [comment]
Just for you to know, I cannot run Meteor anymore by doing the same trick with the current Meteor version. As it worked yesterday and I ran everything in admin mode, I may need to investigate a bit more 
```
D:\CODE\Meteor\meteor>meteor.bat --help
Will get you a dev_bundle for windows_x64 version 8.8.1
Going to download the dependency kit from the Internet
... downloaded
Extracting dev_bundle_windows_x64_8.8.1.tar.gz to the dev_bundle directory
Move-Item : Access to the path 'D:\CODE\Meteor\meteor\dev_bundle_XXX\dev_bundle_windows_x64_8.8.1'
is denied.
At D:\CODE\Meteor\meteor\scripts\windows\download-dev-bundle.ps1:52 char:1
+ Move-Item  $downloaded_path $target_path
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\CODE\Meteor\...ndows_x64_8.8.1:DirectoryInfo) [Move-
   Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemComma
   nd

select-string : Cannot find path 'D:\CODE\Meteor\meteor\dev_bundle\.bundle_version.txt' because it
does not exist.
At D:\CODE\Meteor\meteor\scripts\windows\check-dev-bundle.ps1:10 char:20
+ $CURRENT_VERSION = select-string -Path ($CHECKOUT_DIR + "\dev_bundle\.bundle_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\CODE\Meteor\...dle_version.txt:String) [Select-S
   tring], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SelectStringCommand

The system cannot find the file specified.
Will get you a dev_bundle for windows_x64 version 8.8.1
Skipping download and installing kit from D:\CODE\Meteor\meteor\dev_bundle_windows_x64_8.8.1.tar.gz
Extracting dev_bundle_windows_x64_8.8.1.tar.gz to the dev_bundle directory
Move-Item : Access to the path 'D:\CODE\Meteor\meteor\dev_bundle_XXX\dev_bundle_windows_x64_8.8.1'
is denied.
At D:\CODE\Meteor\meteor\scripts\windows\download-dev-bundle.ps1:52 char:1
+ Move-Item  $downloaded_path $target_path
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\CODE\Meteor\...ndows_x64_8.8.1:DirectoryInfo) [Move-
   Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemComma
   nd

The system cannot find the path specified.
```

**Comment by hwillson** [comment]
@antoninadert The application you've linked to as a reproduction is a bit too large to help with troubleshooting, or demonstrate that this is a problem with Meteor itself (once installed it has 440 top level node dependencies alone). Would you be able to create a smaller, runnable reproduction that shows SSR is slower with Meteor 1.6 (something that includes only what is necessary to demonstrate this issue)? I realize creating a scaled down reproduction can be a pain and takes time, but that way we'll have a much better chance of tracking the real issue down. Thanks!

**Comment by steph643** [comment]
I don't use SSR, but the CPU load seems higher with Meteor 1.6 (under Windows 7). Since I've upgraded from 1.5.2, on the same app, my CPU fan spins like hell.

**Comment by antoninadert** [comment]
I did what you asked for: 
https://github.com/antoninadert/basic-meteor-react-ssr

You can check the first commit, there is no problem with Meteor 1.6,

I then tried to add Viewmodel, and there was still no problem with Meteor 1.6

I then added universal-router, and the problem appeared.

I found the problem when I had this in server/main.js: 
```
const routes = [
  {
    path: '/',
    action() {
      return {
        component:  <App />
      };
    }
  }]
  const router = new UniversalRouter(routes);
  

  function renderPage(thatSink) {
    router.resolve({path: thatSink.request.url.pathname}).then(route  => {
      thatSink.renderIntoElementById("app", renderToString(
        route.component
      ));
    });
  }
```

I had no problem when I had this instead:
```
 function renderPage(thatSink) {
     thatSink.renderIntoElementById("app", renderToString(
       <App />
     ));
     const title = "<title>"+'SSR TEST'+"</title>";
     thatSink.appendToHead(title);
 } 
```


So to recap: 

The problem comes from running the sink.renderIntoElementById method in the callback of Universal Router. 

Can you please check what changed in server-render during the last version that would cause this problem?

I tried to change versions of Universal router but the problem doesn't come from that: the problem is for all versions of Universal Router, so it must be something in server-render that changed this behavior.

I hope it helps

**Comment by antoninadert** [comment]
Is there a way to downgrade server-render package only, while keeping the rest of Meteor 1.6, to check if this is exactly this?

**Comment by hwillson** [comment]
Thanks for the updated repro @antoninadert. I haven't had a chance to look at it yet, but just a quick heads up - you might be interested in PR https://github.com/meteor/meteor/pull/9343. It's adjusting Meteor's `server-render` package to leverage a stream based approach, and help improve performance.

**Comment by antoninadert** [comment]
Hello hwillson, I had a look at PR #9343 but it only leverages another approach and I doubt it is directly related to my problem as I am not using the streaming approach. 

Can you have a look to this problem when you have time ? 

Thanks see you next time

**Comment by klaussner** [comment]
@antoninadert You are calling `await renderPage(sink)` in the function passed to `onPageLoad` but `renderPage` doesn't return a promise. I get the same performance results in Lighthouse with the first (Meteor 1.5.2.2) and last (Meteor 1.6) commit in your reproduction repo when I return the promise:

```js
function renderPage(thatSink) {
  return router.resolve({
    pathname: thatSink.request.url.pathname
  }).then((route) => {
    thatSink.renderIntoElementById("app", renderToString(
      route.component
    ));
  });
}
```

![lighthouse](https://user-images.githubusercontent.com/1312807/34528153-4666e5fe-f0a8-11e7-9af6-b1b191d7bc9a.png)

**Comment by antoninadert** [comment]
Wow that's .. mind-blowing. I thought async/await worked as long as there was a promise somewhere in the function, I didn't know it was necessary to 'return' it. 

I am very thankful to you for finding what was the problem @klaussner, do you have a clue why it used to work like I did and not any more? 

Any way thanks, I think we can close this

**Comment by benjamn** [comment]
@antoninadert You'd be right if the `renderPage` function was `async` (that is, you wouldn't have to explicitly return anything), but right now it's just a normal function that happens to (need to) return a `Promise`. Putting `await` in front of the function call won't actually wait for anything unless the function call returns a `Promise` object. For better or worse, `await <undefined>` is perfectly legal, so it can be hard to spot this kind of mistake.

@klaussner Thanks so much for spotting this!
