### ISSUE TITLE
Meteor 1.6: --debug-brk=55141 is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by Mklueh** [meteor/meteor#9299]
I´m getting this issue after upgrading to Meteor 1.6 and trying to debug my project. My IDE is Webstorm 2017.2.5

> .meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\\dev_bundle\bin\node.exe: --debug-brk=55141 is not allowed in NODE_OPTIONS

Is there any workaround for it already?

**Comment by abernix** [comment]
`--debug-brk` is no longer supported in Meteor 1.6 since the underlying version of Node.js (now Node 8), no longer supports `--debug-brk` (or `--debug`) either.

I'm assuming your current Webstorm configuration is still trying to use the older implementation, though its documentation suggests that it does support the new `--inspect` methodology which uses the Chrome Debugging Protocol.  I'd suggest taking a look at [their documentation](https://www.jetbrains.com/help/webstorm/running-and-debugging-node-js.html#remote_debugging) on the matter and making the appropriate changes!

I hope the experience is as great debugging with WebStorm as it is with Chrome DevTools Remote Debugging and VisualStudio Code!

**Comment by fatso83** [comment]
FYI, @Mklueh, this is fixed in the [release candidate for the upcoming WS version](https://youtrack.jetbrains.com/issue/WEB-29510#comment=27-2534826).

**Comment by jdipallo** [comment]
Hello:
This just halted my development. 1) Is there a workaround? 2) How to go back to previous version without losing my settings. 3) Can I download the Release Candidate? Thank you.

**Comment by benjamn** [comment]
@jdipallo I believe WebStorm 2017.3 is the version you want: https://www.jetbrains.com/webstorm/whatsnew/

Per @abernix's [comment above](https://github.com/meteor/meteor/issues/9299#issuecomment-341931555), this is not a bug in Meteor. The old `--debug-brk` flag is gone for good (and I do mean *good*—the new inspector is infinitely better than what we had before).

**Comment by jdipallo** [comment]
@benjamn Thanks so much for the super quick reply. I will try that version. Is there a way to stop Webstorm from not using that flag? I am using Meteor 1.3.2.4. Yes I know....old project. Things were going just fine before I upgraded. This newest version of Webstorm seemed to think it was a good idea to download in the background, meteor 1.6 and starting using that when i debug. Why is this and can it be prevented? Thank you for you help.

**Comment by benjamn** [comment]
As a matter of fact, older versions of Meteor (including 1.3.x) did download updates in the background, and it was a source of lots of problems, so we stopped letting that happen in [Meteor 1.4.1](https://github.com/meteor/meteor/blob/devel/History.md#v141-2016-08-18):

* Background Meteor updates will no longer modify the `~/.meteor/meteor` symbolic link (or `AppData\Local\.meteor\meteor.bat` on Windows). Instead, developers must explicitly type `meteor update` to begin using a new version of the `meteor` script.

Now that you're on Meteor 1.6 (and yes, please do run `meteor update` if you haven't), the uninvited background update won't happen again; however, there's not much we can do about Meteor 1.3.2.4 at this point. Sorry for the inconvenience!

**Comment by jdipallo** [comment]
Thanks @benjamn. I get the same error with that link you sent. So, I am confused. The version of Webstorm didn't seem to use an updated version of Meteor. Maybe it was and I didn't know. My project at the moment requires Meteor 1.3.2.4. When running my project on the command line either with --release or using the  .meteor/release file specifying 1.3.2.4 I can assure that is the version of Meteor that I am using. Is there no way in Webstore to use a specific version of meteor?

**Comment by jdipallo** [comment]
In addition, I am not using this NODE_OPTION, --debug-brk=51378. Where is this getting set? Thank you

**Comment by jdipallo** [comment]
Hello @benjamn:
Sorry to sound like a broken record but I am stuck.
Is there any way to tell Webstorm to use a specific version of Meteor?? I don't want to use 1.6. I want to use 1.3.2.4. I tried passing --release etc....doesn't work. I did not download/install Meteor 1.6. Webstorm did. Now I can't debug.
Is there some sort of workaround please?
Thank you sincerely.

**Comment by benjamn** [comment]
@jdipallo I honestly have no experience working with Webstorm. Try running
```sh
grep -r NODE_OPTIONS .idea
grep -r debug-brk .idea
```
in your application directory? Also, please seriously consider updating Meteor. The version of Node used by 1.3.2.4 (Node 0.10.x) is no longer maintained, not even with critical security updates. Guides for updating Meteor can be found here: https://guide.meteor.com/1.6-migration.html

**Comment by johnmarty** [comment]
I found meteor executables for every meteor release. Open your system prefs and add the 1.5 exectable to the Meteor config. Then in your projects debug config update it to use the 1.5 executable. You should have it here:

~/.meteor/packages-from-server/localhostX3000/meteor-tool/.1.5.2_2.1md0ura++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/meteor
