### ISSUE TITLE
[1.6] Cannot set property of undefined

### ISSUE THREAD

**Issue by mjmasn** [meteor/meteor#9303]
This is probably a 'working as intended' but it represents a breaking change in 1.6 so I thought I'd mention it here. It's technically a breaking change between babel es2015 preset and native Node 8 support for shorthand object method definitions. 

It seems 

```js
const a = {
    b() { /* do something */ }
}
```

previously transpiled to:

```js
var a = {
    b: function b() { /* do something */ }
};
```

with babel's es2015 preset but is now left as-is due to native support in Node 8. All fine, but it turns out these shorthand methods have no prototype property so trying to set `a.b.prototype.c = function () { }` throws the `cannot set property 'c' of undefined` error.

I can't find any information about these shorthand methods and the prototype property - only that _arrow_ functions have no prototype property - but Node, Chrome and Firefox all have the same behaviour so I'm assuming it's intended and I'll have to rewrite some code :(

**Comment by klaussner** [comment]
The ECMAScript specification distinguishes between normal functions, arrow functions, and methods. The shorthand syntax defines methods, which don't have a prototype, except if they are `constructor`s and their class has a parent class. :nerd_face:

**Comment by mjmasn** [comment]
Well that's that settled 😁 

In the end I only needed to change 2 lines of code across 5 apps for the 1.6 update so I can't complain too much. Testament to the awesome work @benjamn and co have put in on this release 👍
