### ISSUE TITLE
Minifier re-minifies .min.js files in client/compatibility

### ISSUE THREAD

**Issue by juho** [meteor/meteor#9318]
From https://github.com/meteor/meteor/issues/9122#issuecomment-340937143

@sferoze noticed this happening on 1.6, myself on 1.5.2.2 with `standard-minifier-js@2.1.2`.  Seems like a regression as the compiler didn't use to do this (I think?)

Repro:
1. Put https://gist.github.com/juho/d7ba12d2060ea63116538fdc20561c0f (or any other minified .min.js file) in `client/compatibility`
2. Run a production build

Minified files seem to be causing problems after that, throwing unknown variable errors. Switching to `abernix:standard-minifier-js` fixes it for now.

**Comment by hwillson** [comment]
@juho I just tested the minified file you linked to (in `client/compatibility`) with Meteor 1.6 using `--production`, and I don't see any errors. Meteor 1.6 is using `uglify-es` (like `abernix:standard-minifier-js`), and the version Meteor is using has recently been updated (see PR https://github.com/meteor/meteor/pull/9368). Hopefully that means this issue has been resolved. Closing for now, but please post back if you notice differently. Thanks!

**Comment by pkumar-uk** [comment]
I am at meteor version 1.6.0.1. The upgrade seems to work well for most of the new versions of mobile applications but I am facing problem with Android KitKat version(19). Only for this version I am getting the error.
`D/SystemWebChromeClient(27961): http://localhost:12328/8f92cb5dd9ada1fc3f5fa5de7f35db5c81ad8014.js?meteor_js_resource=true: Line 319 : Uncaught TypeError: Variable 'e' has already been declared
I/chromium(27961): [INFO:CONSOLE(319)] "Uncaught TypeError: Variable 'e' has already been declared", source: http://localhost:12328/8f92cb5dd9ada1fc3f5fa5de7f35db5c81ad8014.js?meteor_js_resource=true (319)
D/SystemWebChromeClient(27961): http://localhost:12328/8f92cb5dd9ada1fc3f5fa5de7f35db5c81ad8014.js?meteor_js_resource=true: Line 165 : Uncaught ReferenceError: Router is not defined
I/chromium(27961): [INFO:CONSOLE(165)] "Uncaught ReferenceError: Router is not defined", source: http://localhost:12328/8f92cb5dd9ada1fc3f5fa5de7f35db5c81ad8014.js?meteor_js_resource=true (165)
D

`

I am not sure if it is the same problem, but removing standard-minifier-js package resulted in a Cordova build that seems to work, though the apk size has increased. Is there a fix for this. Please let me know if more information is needed.
