### ISSUE TITLE
Serialport > 4.0.7 : Inappropriate ioctl for device setting custom baud rate of....

### ISSUE THREAD

**Issue by bletual** [meteor/meteor#9322]
- __SerialPort Version__: 6.0.4
- __NodeJS Version__: 8.0.9
- __Operating System__ and __Hardware Platform__: Linux mint (Ubuntu 16.04.1 / 4.8.0-53) / Intel core I5

### Summary of Problem
My application is Meteor 1.6 application (I got the same problem with 1.4 and 1.5)
Up to Serialport 4.0.7, everything is OK
After Serialport 4.0.7 : Inappropriate ioctl for device setting custom baud rate of....

### Steps and Code to Reproduce the Issue
    let deviceFilename = "/dev/AS_SNBC"; // ttyUSB device

    let printerPort = null;

    try {
        printerPort = new SerialPort(deviceFilename);
    }
    catch (err) {
        throw err;
    }

NB : "outside" Meteor 1.6, this code is OK.

**Comment by hwillson** [comment]
@bletual Please provide a reproduction showing this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)).

**Comment by bletual** [comment]
Hi,
I made a mistake in my comment. I can reproduce it only if my device is connected on USB. If I use the serial interface (ttyUSB), it is OK. The way to reproduce : 

Use Serialport 6.0.4 to connect an USB device as mentionned in my first comment.
In my case, I have a thermal printer with 2 interfaces, RS232 and USB. 

If I connect it with the RS232 interface to a FT4232H Quad HS USB-UART/FIFO => ttyUSBx => no problem.

If I connect it with the USB interface directly to an USB 2.0 of my computer => Inappropriate ioctl for device.

A question : why Meteor uses "ioctl" and not "termios" ?

Regards,

Bruno.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9322#issuecomment-342851315, there isn't much we can do to help you here without being able to reproduce this problem. I realize putting together a reproduction takes time, but supplying a runnable reproduction that clearly demonstrates your problem means there is a much greater chance of it getting resolved. As things stand currently, you've listed a few really loose steps relating to a very specific problem you're having with a 3rd party library (that's not part of Meteor core). If you can clearly demonstrate you've found an issue with Meteor itself, we're happy to help you in any way we can. For now though, I'll close this issue. I'm happy to re-open it if you're able to provide the requested reproduction (again, see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by litehacker** [comment]
I have the same problem. Try to remake the C++ project in NodeJS, where I called the usb reader by `int fd = open("/dev/midi1", O_RDWR);
ssize_t size = read(fd, &byte, 1);`
the input data was being saved into `byte` variable. There was no boudrate set previously. Device CASIO 3200
