### ISSUE TITLE
rollupjs, modules inlining and slow cordova loading times

### ISSUE THREAD

**Issue by sirpy** [meteor/meteor#9326]
I've noticed that as your UI grows with modules the cordova application loading time starts to get very slow (6-16 seconds)
Profiling seems to show that most time is spent on loading all the modules.
This article seems to give the answer why this happens, and explains that the difference between webpack and rollupjs module declaration style is the difference. looking at the meteor generated modules.js it in did looks like the webpack style of module definition
https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/

is there a way to write a plugin to package the modules differently?
is this feature planned for future meteor versions?

**Comment by hwillson** [comment]
Hi @sirpy - GitHub issues here are reserved for bugs with Meteor. Meteor questions are better asked on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). You could also consider kickstarting a feature request relating to module inlining over in Meteor's feature request repo, https://github.com/meteor/meteor-feature-requests. Before you do though, check out https://github.com/meteor/meteor-feature-requests/issues/206. Thanks!
