### ISSUE TITLE
Meteor Stylus - unable to import json file from package

### ISSUE THREAD

**Issue by thehopwood** [meteor/meteor#9347]
Using `meteor/stylus` 2.513.13 on Meteor 1.6

I have created a custom package named `test:themes` but seem to be unable to import json file with the following:

/packages/test-themes/package.js
```
Package.onUse(function(api) {
    api.versionsFrom('1.2.1')
    api.addAssets('themes/themes.json', [ 'client', 'server' ])
    api.addFiles('themes/theme-mixin.import.styl', 'client', { isImport: true })
})
```

/packages/test-themes/themes/themes.json
```
{
    ... //json here
}
```

/packages/test-themes/themes/theme-mixin.import.styl
```
data = json('/packages/test_themes/themes/themes.json', { hash: true })
...
```

Results in unable to find file:

```
While processing files with stylus (for target web.browser):
   client/styles/_app.styl: Stylus compiler error: {test:themes}/themes/theme-mixin.import.styl:1:72
   1| @import 'nib'
   -----------------------------------------------------------------------------^
   
   failed to locate .json file /packages/test_themes/themes/themes.json
```

I'm able to access the json file directly in the app ... 

`localhost:3000/packages/test_themes/themes/themes.json`

Is this possible to achieve with the stylus plugin?

**Comment by thehopwood** [comment]
was able to work around with the following:

```
data = json('../../packages/orion-themes/themes/themes.json', { hash: true })
```

but, of course, that requires the path in my package to match where i am importing from which isn't the greatest. It seems absolute and relative paths differ when compiling the stylus files.

**Comment by hwillson** [comment]
Hi @thehopwood - glad to hear you found a workaround. A quick note - Meteor's `stylus` package has been deprecated, and is no longer supported as part of the Meteor project. We recommend finding an alternative 3rd party stylus package to use, like [coagmano:stylus](https://atmospherejs.com/coagmano/stylus). Thanks!
