### ISSUE TITLE
[Question] Implications of not connecting to WS ? (DDP Client)

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9349]
By looking inside ddp-client, I see that Meteor is meant to be connected at all times to the server.
(https://github.com/meteor/meteor/blob/devel/packages/ddp-client/client/client_convenience.js#L47)

Now that Meteor is mature enough we should consider rethinking this approach and allow a lazy-connection that can be started when reactivity is needed. (If I have a blog, shop, presentation page, I may not want my clients to be connected at all times with the server, but maybe on some pages, I need that reactivity back so I want to start the ws connection)

I first posted my idea here: https://forums.meteor.com/t/meteor-scaling-fusion-mode-status-idea/40467

I saw that I can copy the ddp-client package in packages and play with it, but I want to know system-wide implications of not being connected to the server, and I would like some opinions before I dive into this.

**Comment by theodorDiaconu** [comment]
How hard would it be to separate meteor core packages inside a special js. Or maybe not only core packages, but packages in general, because in real scenarios, those won't change too often with each new deployment, and it means it can be cached => better performance.

**Comment by klaussner** [comment]
I think [this feature request](https://github.com/meteor/meteor-feature-requests/issues/168) is similar to your idea.

**Comment by theodorDiaconu** [comment]
@klaussner it is a bit indeed, my idea is to create a toggable version of ddp. By looking at the code, I think it's possible, but I still have to understand the impact it will have on accounts. But the theory is like this:

As soon as the first subscription is started => DDP connection engages
After the last open subscription is stopped => Wait x seconds, stop the connection if no other subscription got in.

Create a `/_meteor`, server side route, that accepts a EJSONable string ({method: "getX", arguments: ["xxx", "yyy"]}), and the client does a XHR request to it. If DDP is open, it should communicate through DDP because it's more efficient. It'll be interesting to see how I can fit it with accounts.

This simple change can have huge impact on performance and it opens Meteor for many sites that don't really need reactivity.

@stubailo @benjamn I'm tagging you because you've worked on the ddp-client, any thoughts on this?

**Comment by theodorDiaconu** [comment]
I already implemented something like this:
https://github.com/cult-of-coders/fusion

It seems to work fine, it works with Accounts.
