### ISSUE TITLE
Undesired reload occurs upon opening a freshly installed app 

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#9350]
Meteor 1.6.

Steps:
1. Uninstall the app (if previously installed)
2. Download and install the app from the store (either apple or google)
3. Open it

Expected behavior:
The app shows up.

Actual behavior:
The app shows up and, after a few seconds, it gets reloaded. On a side note, during that interval, images (hosted on S3) are not showing (Update: as shown by further tests on the simulator, this is the consequence of Meteor.settings being EMPTY!). Only after the refresh, which doesn't make if for an ideal user experience, the behavior is as expected.

This occurs on both iOS and Android. I took a look at the [webapp documentation](https://github.com/meteor/cordova-plugin-meteor-webapp#storing-and-serving-asset-bundles) but haven't found anything that would explain this.

**Comment by klaussner** [comment]
Is there a way to reproduce and debug this locally or does it only happen with apps downloaded from a store?

**Comment by davidecantini** [comment]
It only happens with apps downloaded from a store, locally it works as expected (I doubled checked again now deploying on an Android device).

**Comment by davidecantini** [comment]
From the logs obtained on the iOS simulator, and reported below, I highlight some things I noticed (hopefully they can be helpful to solve the two issues: undesired refresh and Meteor.settings not defined at first)

1. Start serving bundle 70c7cf9e061ab997ca1eb8917215edeb0e000000
2. Start downloading asset manifest from: manifest.json -- https://my.app.com:443/__cordova/
3. Meanwhile Meteor.settings is EMPTY (this causes the url to images not to be found and so it explains the missing images reported in the description of the issue). Why is Meteor.settings empty? It should never be according as reported [here](http://docs.meteor.com/api/core.html#Meteor-settings) The settings.json file is defined properly (it works properly after the first run). Could it be something in the Galaxy environment? Please help.
4. Completed downloading the manifest... start downloading and finished downloading new asset bundle version: b1587ea01835a4571de1c6f378062cd116000000
5. ROOT_URL seems to have changed, new: https://my.app.com/, old: https://my.app.com:443/ (is this all right?)
6. Serving asset bundle version: b1587ea01835a4571de1c6f378062cd116000000 (this explains the unexpected refresh). 

Here are the logs which they above points have been taken from:

## First run, fresh app install:
17:02:04.532409+0100 MyAppName[30664:8412253] +[CATransaction synchronize] called within transaction
17:02:04.616282+0100 MyAppName[30664:8412253] Apache Cordova native platform version 4.5.0 is starting.
17:02:04.616823+0100 MyAppName[30664:8412253] Multi-tasking -> Device: YES, App: YES
17:02:04.878141+0100 MyAppName[30664:8412253] [MC] Lazy loading NSBundle MobileCoreServices.framework
17:02:04.878970+0100 MyAppName[30664:8412253] [MC] Loaded MobileCoreServices.framework
17:02:04.881350+0100 MyAppName[30664:8412253] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/davide/Library/Developer/CoreSimulator/Devices/1C0AFDFE-B683-42F1-8E95-061E17114A2D/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
17:02:06.808059+0100 MyAppName[30664:8412253] CDVWKWebViewEngine will reload WKWebView if required on resume
17:02:06.808250+0100 MyAppName[30664:8412253] Using WKWebView
17:02:06.809438+0100 MyAppName[30664:8412253] [CDVTimer][console] 0.090957ms
17:02:06.809679+0100 MyAppName[30664:8412253] [CDVTimer][handleopenurl] 0.101984ms
17:02:06.811624+0100 MyAppName[30664:8412253] [CDVTimer][intentandnavigationfilter] 1.806974ms
17:02:06.811770+0100 MyAppName[30664:8412253] [CDVTimer][gesturehandler] 0.046015ms
17:02:06.848557+0100 MyAppName[30664:8412253] Serving asset bundle version: 70c7cf9e061ab997ca1eb8917215edeb0e000000
[INFO] GCDWebServer started on port 12999 and reachable at http://localhost:12999/
17:02:06.852802+0100 MyAppName[30664:8412253] [CDVTimer][webapplocalserver] 40.924966ms
17:02:06.940861+0100 MyAppName[30664:8412253] [CDVTimer][splashscreen] 87.898016ms
17:02:06.950164+0100 MyAppName[30664:8412253] [CDVTimer][statusbar] 9.124041ms
17:02:06.951073+0100 MyAppName[30664:8412253] [CDVTimer][universallinks] 0.795007ms
17:02:06.951706+0100 MyAppName[30664:8412253] [CDVTimer][localstorage] 0.532031ms
17:02:06.951808+0100 MyAppName[30664:8412253] [CDVTimer][TotalPluginStartup] 142.973006ms
17:02:07.000858+0100 MyAppName[30664:8412253] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
17:02:07.007090+0100 MyAppName[30664:8412253] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
17:02:17.691899+0100 MyAppName[30664:8412253] Start downloading asset manifest from: manifest.json -- https://my.app.com:443/__cordova/
17:02:17.692593+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:17.692753+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:17.746774+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:17.747099+0100 MyAppName[30664:8412253] Layout subs ready
17:02:17.752405+0100 MyAppName[30664:8412253] No UI language was set yet, best choice:  en
17:02:17.753906+0100 MyAppName[30664:8412253] TAPi18n successfully loaded lang= en
17:02:17.754168+0100 MyAppName[30664:8412253] moment loaded locales: en
17:02:17.754373+0100 MyAppName[30664:8412253] moment set global locale to en returned:  en
17:02:17.754580+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:17.754763+0100 MyAppName[30664:8412253] Layout subs ready
17:02:17.754943+0100 MyAppName[30664:8412253] use previous ui lang: en
17:02:17.755122+0100 MyAppName[30664:8412253] ignore setting lang=en again
17:02:17.772513+0100 MyAppName[30664:8412253] Meteor.settings=    [*** IT SHOULD NOT BE EMPTY! ***]
17:02:21.271893+0100 MyAppName[30664:8413813] Downloaded asset manifest for version: b1587ea01835a4571de1c6f378062cd116000000
17:02:21.278045+0100 MyAppName[30664:8413007] Start downloading assets from bundle with version: b1587ea01835a4571de1c6f378062cd116000000
17:02:21.779358+0100 MyAppName[30664:8413813] [CDVTimer][assetBundleDownload] 500.952005ms
17:02:21.779906+0100 MyAppName[30664:8413812] Finished downloading new asset bundle version: b1587ea01835a4571de1c6f378062cd116000000
17:02:21.784875+0100 MyAppName[30664:8413813] TIC Read Status [2:0x0]: 1:57
17:02:21.785000+0100 MyAppName[30664:8413813] TIC Read Status [2:0x0]: 1:57
17:02:21.798545+0100 MyAppName[30664:8412253] ROOT_URL seems to have changed, new: https://my.app.com/, old: https://my.app.com:443/
17:02:21.799473+0100 MyAppName[30664:8412253] Serving asset bundle version: b1587ea01835a4571de1c6f378062cd116000000
17:02:22.778857+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:22.779514+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:22.858837+0100 MyAppName[30664:8412253] Subscription to currentUser: ready
17:02:22.859108+0100 MyAppName[30664:8412253] Layout subs ready
17:02:22.859343+0100 MyAppName[30664:8412253] use previous ui lang: en
17:02:22.859564+0100 MyAppName[30664:8412253] ignore setting lang=en again
17:02:22.860402+0100 MyAppName[30664:8412253] initial stack=
17:03:20.617133+0100 MyAppName[30664:8416554] TIC Read Status [1:0x604000170380]: 1:57
17:03:20.617357+0100 MyAppName[30664:8416554] TIC Read Status [1:0x604000170380]: 1:57
17:03:20.619836+0100 MyAppName[30664:8416554] TIC Read Status [1:0x0]: 1:57
...


## From the 2nd run on, everything works as expected:

17:26:11.592012+0100 MyAppName[30938:8517302] [CDVTimer][handleopenurl] 0.086010ms
17:26:11.594038+0100 MyAppName[30938:8517302] [CDVTimer][intentandnavigationfilter] 1.901984ms
17:26:11.594200+0100 MyAppName[30938:8517302] [CDVTimer][gesturehandler] 0.060022ms
17:26:11.632954+0100 MyAppName[30938:8517302] Serving asset bundle version: b1587ea01835a4571de1c6f378062cd116000000
[INFO] GCDWebServer started on port 12999 and reachable at http://localhost:12999/
17:26:11.635419+0100 MyAppName[30938:8517302] [CDVTimer][webapplocalserver] 41.108966ms
17:26:11.687247+0100 MyAppName[30938:8517302] [CDVTimer][splashscreen] 51.695943ms
17:26:11.693008+0100 MyAppName[30938:8517302] [CDVTimer][statusbar] 5.617023ms
17:26:11.694077+0100 MyAppName[30938:8517302] [CDVTimer][universallinks] 0.959992ms
17:26:11.694465+0100 MyAppName[30938:8517302] [CDVTimer][localstorage] 0.268996ms
17:26:11.694579+0100 MyAppName[30938:8517302] [CDVTimer][TotalPluginStartup] 103.343010ms
17:26:11.731421+0100 MyAppName[30938:8517302] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
17:26:11.732666+0100 MyAppName[30938:8517302] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
17:26:14.362645+0100 MyAppName[30938:8517302] Subscription to currentUser: ready
17:26:14.363246+0100 MyAppName[30938:8517302] Subscription to currentUser: ready
17:26:14.423020+0100 MyAppName[30938:8517302] Subscription to currentUser: ready
17:26:14.423376+0100 MyAppName[30938:8517302] Layout subs ready
17:26:14.428417+0100 MyAppName[30938:8517302] No UI language was set yet, best choice:  en
17:26:14.429798+0100 MyAppName[30938:8517302] TAPi18n successfully loaded lang= en
17:26:14.430055+0100 MyAppName[30938:8517302] moment loaded locales: en
17:26:14.430279+0100 MyAppName[30938:8517302] moment set global locale to en returned:  en
17:26:14.430530+0100 MyAppName[30938:8517302] Subscription to currentUser: ready
17:26:14.430752+0100 MyAppName[30938:8517302] Layout subs ready
17:26:14.430957+0100 MyAppName[30938:8517302] use previous ui lang: en
17:26:14.431195+0100 MyAppName[30938:8517302] ignore setting lang=en again
...

**Comment by davidecantini** [comment]
After some cleanup, it seems to be gone. Closing it for now. Thank you.
