### ISSUE TITLE
Meteor(Blaze)[1.6] - [TypeError: Buffer.alloc is not a function] Unable to load plugin meteor

### ISSUE THREAD

**Issue by rashmimhatre100** [meteor/meteor#9356]
I am trying to deploy meteor-app on AMAZON-SERVER. Unable to get success while running MUP STOP.

I created exactly /client/lib/init.js, wrote require("buffer").Buffer //not working

var Buffer = require('buffer/').Buffer //not working

Also tried, global.Buffer = function() {} global.Buffer.isBuffer = () => false //not working

And meteor npm update @production // not working

Still getting the same error.

Thanks in Advance!

**Comment by abernix** [comment]
Can you please provide more information?  For example, what do you mean by "not working"?  Is there an error message?

It would be best if you could provide a small Meteor reproduction posted to a GitHub repository, as requested in the instructions for [reporting a bug](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-bug), and link to it here.

Thanks!

**Comment by rashmimhatre100** [comment]
Read many articles which suggests to add buffer stuff in lib etc. But after adding, still I am getting the same error.

**Comment by abernix** [comment]
Can you please provide a small, runnable reproduction?

**Comment by rashmimhatre100** [comment]
Thank you for your reply. Solved issue by updating npm at server.

**Comment by massimosgrelli** [comment]
I'm having the same problem using `mup deploy` on Digital Ocean and I cannot figure out any way to fix this
