### ISSUE TITLE
1.6 : missing babel compilation of Npm dependencies ? = IE breaks

### ISSUE THREAD

**Issue by vparpoil** [meteor/meteor#9357]
Hello everyone, 
I am reporting what feels like a bug, here are the steps to reproduce it : 
- create a new meteor app (Meteor 1.6 used) : `meteor create test`
- add the auth0-js npm dependency : `meteor npm install --save auth0-js`
- add the following line to Template.hello.onCreated : `const auth0 = require('auth0-js');`

Then, in IE 11, I get the following exception in console : `Invalid character`. It points to some code from a npm dependency to `auth0-js` which uses [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), which is a feature not supported in IE :
```javascript
const ua = `node-superagent/${pkg.version}`;
```

Using Template Literals directly in a meteor app js code (like in `client/main.js`) does work on IE 11, maybe because the Babel transcriber is active for Meteor app code ? 

I encounter this issue in development (launching locally the app with `meteor`), and in production (building via `meteor build` and launching via `meteor node main.js`)

It feels that the packages included from the npm ecosystem are not translated to common JS (using Babel transcriber ?) Can someone confirm ? Is it a feature or a bug ? Should I use other steps in building / debugging ?

Here is a [test repo](https://github.com/vparpoil/test-meteor-npm-babel) to reproduce the behavior

Thanks a lot for your work !

**Comment by benjamn** [comment]
Thanks for reporting this, but please direct your attention to the ongoing discussion [here](https://github.com/meteor/meteor-feature-requests/issues/6). Long story short, we hope to address this in Meteor 1.6.1, though it's not clear how best to enable compilation of `node_modules`, since most npm packages are already compiled, and recompliation may not be safe in all cases.
