### ISSUE TITLE
ld: 2 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by LuXiaolin** [meteor/meteor#9365]
duplicate symbol _OBJC_CLASS_$_CDVLogger in:
    /Users/luxiaolin/Library/Developer/Xcode/DerivedData/opaidui-blcmfbyzujzueubdleaxmgohjeto/Build/Intermediates.noindex/opaidui.build/Debug-iphoneos/opaidui.build/Objects-normal/arm64/CDVLogger.o
    /Users/luxiaolin/Library/Developer/Xcode/DerivedData/opaidui-blcmfbyzujzueubdleaxmgohjeto/Build/Products/Debug-iphoneos/libCordova.a(CDVLogger.o)
duplicate symbol _OBJC_METACLASS_$_CDVLogger in:
    /Users/luxiaolin/Library/Developer/Xcode/DerivedData/opaidui-blcmfbyzujzueubdleaxmgohjeto/Build/Intermediates.noindex/opaidui.build/Debug-iphoneos/opaidui.build/Objects-normal/arm64/CDVLogger.o
    /Users/luxiaolin/Library/Developer/Xcode/DerivedData/opaidui-blcmfbyzujzueubdleaxmgohjeto/Build/Products/Debug-iphoneos/libCordova.a(CDVLogger.o)

**Comment by derwaldgeist** [comment]
Hi @LuXiaolin I have the same problem after upgrading to Meteor 1.6. How did you resolve this?

**Comment by derwaldgeist** [comment]
Filed a new issue for this, with some more details:
https://github.com/meteor/meteor/issues/9365
