### ISSUE TITLE
TypeError: require(...).lt is not a function at C:\tools\cli\main.js:595:25

### ISSUE THREAD

**Issue by fahadakhan96** [meteor/meteor#9369]
Meteor stopped working suddenly. It was working until 3 or 4 days ago. This is what I got when using `mup.cmd deploy` today. I tried running multiple meteor commands but I get the same error with all of them. Even just `meteor` or `meteor --version`:
```
C:\Users\fahad\Desktop>meteor create newapp
C:\Users\fahad\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\tools\cli\main.js:1508
}).run();
   ^

TypeError: require(...).lt is not a function
    at C:\tools\cli\main.js:595:25
```

**Comment by benjamn** [comment]
With Chocolatey it's much easier to remove and reinstall Meteor on Windows now. I don't know if this will help, and I'm not claiming it's an ideal solution, but it would help determine if this is a persistent problem, or some sort of corrupt Meteor installation:
```sh
choco uninstall meteor
choco install meteor
```

**Comment by fahadakhan96** [comment]
Already tried that. Also tried reinstalling Node.js. Didn't work. Still the same problem.

**Comment by abernix** [comment]
Does the following directory exist on your system?

    C:\Users\fahad\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\semver

Does it have both `semver.js` and a `package.json` within it?

**Comment by fahadakhan96** [comment]
> Does it have both `semver.js` and a `package.json` within it?
Yes.

**Comment by hwillson** [comment]
@fahadakhan96 Do you by chance have an `EMACS` environment variable set with a value of `t`?

**Comment by fahadakhan96** [comment]
@hwillson I didn't at that time. I have now reinstalled my Windows and have moved all development to Ubuntu so I will not be able to help further regarding this issue. @abernix I'm not sure if I should close this issue, so I leave that upto you. 

Cheers!

**Comment by hwillson** [comment]
Sounds good @fahadakhan96 - we'll close this for now then. Thanks!
