### ISSUE TITLE
Meteor runs in production mode by default in Windows

### ISSUE THREAD

**Issue by pilarArr** [meteor/meteor#9372]
### This bug report should include:
- [x] A descriptive title
- [x] The version of Meteor showing the problem.
- [x] The last version of Meteor where the problem did _not_ occur (if applicable)
- [x] The operating system you're running Meteor on.
- [x] The expected behavior.
- [x] The actual behavior.
- [x] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)

## Meteor runs by default in production mode in Windows10

As stated in the title Meteor runs by default in production mode when using a windows machine.
My version of Windows is 10 (x64).

I had this problem in Meteor 1.5, then did a complete uninstall of meteor to install the new Meteor 1.6 with Chocolatey and the problem persists. I can't know in which version of meteor it worked.

 This is a huge problem for me since any code I have in a `Meteor.isDeveloment` conditional does not run.

### Simple reproduction in Windows 10.

1. First create a simple meteor app
```
meteor create simple-todos
cd simple-todos
```

2. On the `main.js` file on server write.
```
console.log(Meteor.isProduction);
console.log(Meteor.isDevelopment);
```

3. Run meteor.

#### Expected behaviour
```bash
meteor
... meteor runs
false
true
```

#### Actual behaviour
```bash
meteor
... meteor runs
true
false
```

I did this test on a macOS machine and it works as expected

**Comment by abernix** [comment]
Do you have a `NODE_ENV` variable set on Windows?

#### Command Prompt (`cmd.exe`)
The output of:
    SET NODE_ENV
#### PowerShell
    $env:NODE_ENV

**Comment by pilarArr** [comment]
Not that I'm aware of.
The output of that comand in **`cmd.exe`** is

`Enviromnent variable NODE_ENV not defined`

**Comment by pilarArr** [comment]
I've tried installing meteor in another windows computer and it works as expected.
I'm going to try to delete and reinstall node to check if that fixes it.

**Comment by claudiutraistaru** [comment]
@pilarArr did the reinstall solved the issue?
 I had the issue https://github.com/meteor/meteor/issues/9358 .My solving was to use test mode , but it seems that meteor was running on production mode and hence my chimp issues. 
```
console.log(Meteor.isProduction);
console.log(Meteor.isDevelopment);
```
has the output:
```
I20171115-23:32:34.662(2)? true
I20171115-23:32:34.731(2)? false
```
so , on my side reinstalling did not solve the issue.

**Comment by claudiutraistaru** [comment]
Furthermore , 
```
console.log(process.env.NODE_ENV)
```
has the ouptut
```
production
```
The temporar workaround for this is to start meteor like this:
```
set NODE_ENV=development && meteor
```

**Comment by pilarArr** [comment]
@claudiutraistaru I've just removed `node` and after running meteor everything works as expected.

I'm going to install node again and check if it still works. I'll get back to you with the results.

**Comment by pilarArr** [comment]
It worked in the minimal example, after reinstalling `node` it worked on the first run.

Then I started my project which had the error still. And when I tried to run the minimal example again is set to production again. I don't understand what happened.

Thanks for you workaround @claudiutraistaru, I guess I'll be using that until I find out what is happening

**Comment by pilarArr** [comment]
I ended up defining `NODE_ENV` in windows environment variables

**Comment by pilarArr** [comment]
An update on this issue.

Looks like Atom sets `NODE_ENV` to `production`. For anyone using Atom, you have to manually set `NODE_ENV` to `development` when running meteor. But if you do this the git tab stops working.

**Comment by claudiutraistaru** [comment]
Also for anyone running terminal packages in atom you could configure to auto set node_env to development on treminal start , more details here: https://github.com/platformio/platformio-atom-ide-terminal/issues/15
