### ISSUE TITLE
In Meteor not able to call server side function from client in Mobile App(android) working fine in web app

### ISSUE THREAD

**Issue by prachi708** [meteor/meteor#9385]
In Meteor my app is working fine as webapp, whereas when I made its package for android using command

       Meteor build ~/Desktop --server=http://appname.meteorapp.com --Debug

and then install that package on android then on calling any of server side side function it is giving 404 error saying Meteor Method not found.

My code is import/api/MemberData.js

        import { Mongo } from 'meteor/mongo';
        export const Members = new Mongo.Collection('Members'); 
server/ServerMethod.js

        Meteor.startup(() => {
        Meteor.methods({
             'LoginMember': function(data) {  //my function for which error is showing not exist
             }
           })
       })
/imports/ui/components/LoginComponent.js

          Meteor.call('LoginMember',{'email':email,'password':password},function(err,res){
                     if(err){
                alert(err)
                   }else{
            console.log(res);
             }
            })

**Comment by hwillson** [comment]
GitHub issues here are reserved for bugs with the Meteor platform itself, not application bugs. Calling Meteor methods from mobile devices definitely works, so you might want to reach out for help on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Thanks!
