### ISSUE TITLE
Partially downloaded files are applied with HCP (Cordova)

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#9387]
**Partially downloaded files are considered ok to be applied causing an app to stop working completely
Scenario (successfully reproduced on Android, this should not happen on iOS):**

- An ongoing HCP update download is interrupted (due to internet issues, i.e. connection drop on 3G GSM connection)
- A JS file is not completely downloaded but still saved to the Download directory.
- During the next update the Download dir is moved to become a PartialDownload directory.
- The damaged file is not downloaded again but is copied from the PartialDownload.
- App fails to start with `SyntaxError: unexpected end of input` (depending on where the file is cut the error is different)
![image](https://user-images.githubusercontent.com/8668306/32950475-bfff6fde-cba6-11e7-8b60-3181404e87c2.png)

Mechanism of the problem. 
https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/android/AssetBundleDownloader.java#L98
The IOUtils.writeToFile synchronously blocks but in the background the file is still downloaded and the contents are saved to disk as they arrive. If the connection is interrupted it will throw here and the partially downloaded file is kept and later considered as ok because the plugin does not redownload any previously downloaded file. So when it tries to download the update once again it uses the file without checking if it is correct.

How to reproduce:
1. Limit simultaneous connection to 1 https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/android/AssetBundleDownloader.java#L49
2. Create a virtual android with simulated low bandwith
3. Add a log with the file name here so you can track what file is downloaded https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/android/AssetBundleDownloader.java#L94
4. Shut down internet connection during download of any bigger file (might be useful to add a big npm package to the project, or just use --production so one big js would be downloaded)
5. Inspect the files on the device and check the file was left in an incomplete state
6. Restart app.

In theory the faulty version recovery mechanism should work and make that issues less critical but...
https://github.com/meteor/meteor/issues/9386

In general there are some other long standing issues such as https://github.com/meteor/meteor/issues/8063 that I can also confirm
and I have the feeling that the webapp cordova plugin does not get the attention it should looking at the issues/pull requests. 
Almost everyone I know uses a fork for their production apps (such as https://github.com/bmanturner/cordova-plugin-meteor-webapp) so this is not a good sign.

Of course I do not want to complain only so next week I will propose some fixes for the both issues and submit PRs.

**Comment by hwillson** [comment]
@wojtkowiak We'll continue to track this via your https://github.com/meteor/cordova-plugin-meteor-webapp/pull/38 PR, and close it here. If there are any additional issues relating to the `cordova-plugin-meteor-webapp` plugin that need to be opened, we'll create them in the https://github.com/meteor/cordova-plugin-meteor-webapp repo, to keep everything in one place. Thanks!
