### ISSUE TITLE
Stuck at "Starting your app" even for newly created example app

### ISSUE THREAD

**Issue by tab00** [meteor/meteor#9394]
- [ ] The version of Meteor showing the problem.
1.6

- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
1.5.2

- [ ] The operating system you're running Meteor on.
Windows 10 64 bit

- [ ] The expected behavior.
App runs.

- [ ] The actual behavior.
Output:
Started proxy.
Starting your app                         -

Progress spinner spins indefinitely.

- [ ] A **simple** reproduction!
`meteor create test-001`
`cd test-001`
`meteor`

**Comment by crapthings** [comment]
try 

meteor create test-001
cd test-001
meteor --verbose

check why it stucks

**Comment by tab00** [comment]
It may be related to auto-containment by Comodo Internet Security.

**Comment by abernix** [comment]
@tab00 You're probably in the best position to test your theory since you've reported this issue.  Does the problem go away if you disable Comodo Internet Security?

**Comment by tab00** [comment]
I think disabling the Auto-Containment feature in Comodo Internet Security helped to have MongoDB run, as well as `meteor npm`.

I can now run my app (and run `meteor npm`) even without disabling Auto-Containment. Maybe it needed to be disabled for first-time only, during which executed processes can be whitelisted.

I haven't experimented much as I've been busy with a lot of work. But I'll report back if I come across related problems.

**Comment by yogesh249** [comment]
I did a meteor reset, and it worked fine. Last time I had to shutdown abruptly using Ctrl+C because I don't know how else I should shut it down....

But meteor reset is not a solution, as it wipes out all the data in the database.

I am using meteor version 1.8.0.2, Please post if anyone has a solution to this problem.
