### ISSUE TITLE
Meteor.server is undocumented and therefore not in the meteor.d.ts

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#9399]
The new [ddp-graceful-shutdown package](https://github.com/meteor/ddp-graceful-shutdown)  is documented that you have to pass Meteor.server when initialising it.  But this member isn't documented, and it is also not declared in Meteor.d.ts.

This means that the instructions for ddp-graceful-shutdown don't work for Typescript users.

The work-around is simply to use Meteor['server'] instead, but this is not ideal. It seems that it should be documented as some legitimate packages might need it. It was renamed from default_server about 4 years ago (as a DDP convenience).
https://github.com/meteor/meteor/blob/84ed04b8f3b99cf16b5540f2e0193d47e4f8ccf6/packages/ddp-server/server_convenience.js#L6

I notice that the accounts system (oauth_common.js, accounts_server.js), and ddp-heartbeat package also use it.

**Comment by hwillson** [comment]
Thanks for reporting this @sdarnell - would you mind opening this issue over in http://github.com/meteor/docs instead?

**Comment by sdarnell** [comment]
Righty-oh: https://github.com/meteor/docs/issues/168
