### ISSUE TITLE
Mongo Query dynamic field behavior

### ISSUE THREAD

**Issue by axelvaindal** [meteor/meteor#9400]
Hi,

I'm using a publication of users based on a nested field : 

```javascript

// Schema 
{
    following:
    {
        "userId": {endedAt: null, startedAt: Date},
        "userId": {endedAt: null, startedAt: Date}
     }
} 

Meteor.publish("user_followers", function(userId)
{
    let followRelation = "following." + userId; 
    let followRelationDate = followRelation + ".endedAt"; 

    // This returns an empty array
    return Meteor.users.find(
    {
          followRelation: {$exists: true}, 
          followRelationDate: {$type: "null"}
    }); 
});
```
The weird behavior here is that if I replace the variable in the find query with outputted value of `followRelation` and `followRelationDate` variables, this is working as it should.
See : 

```javascript
Meteor.publish("user_followers", function(userId)
{
    // This returns a correct match of specified document
    return Meteor.users.find(
    {
          "following.PBKgeWNCMxQcWpabT": {$exists: true}, 
          "following.PBKgeWNCMxQcWpabT.endedAt": {$type: "null"}
    }); 
});
```

Is there any particular reason I cannot use these dynamic variable to match specific set of documents or is it a bug ?

Environment : Meteor 1.6
NODE_ENV : development
OS : Ubuntu Server 14.04 LTS

Note: 
I'm not using array to store this particular use case for stockage performance reasons and for other performance reason I would rather not hack this with a `$where` operator (which will become so much consuming in performance as the object grows). This issue is mainly about whether or not passing string values for specified dynamic nested field is working or not in publications.

**Comment by klaussner** [comment]
The query object in your first code snippet contains the keys `'followRelation'` and `'followRelationDate'` because you are not using the respective variables. I think what you really want to do is this:

```js
Meteor.users.find({
  [followRelation]: { $exists: true }, 
  [followRelationDate]: { $type: 'null' }
});
```

**Comment by axelvaindal** [comment]
Two hours of research for two brackets forgotten, and an unneeded issue opened at 11pm.
Thought they were on. (Guess it's time to go get some sleep).
Sorry for time wasting, thanks a lot @klaussner !
