### ISSUE TITLE
Public assets not loaded if there is a symlink in public/

### ISSUE THREAD

**Issue by averissimo** [meteor/meteor#9403]
*Version:* up until 1.6 *(included)*
*OS:* Ubuntu 16.10

*Expected behavior:* Start an app in development or production and is ready to be used
*Actual behavior:* Assets from public directory are not retrieved

Cause of problem: symlink in public diretory

How to reproduce: https://github.com/averissimo/meteor-bug-public-imgs
1. Start app which should show image
1. Stop app
1. Go to public diretory and run `ln -s ../node-modules/font-awesome/fonts fonts`
1. Start app and verify that it does not show image as image below
1. Update some code in the app to force restart and it works again

![image](https://user-images.githubusercontent.com/211358/33092984-a5420e5e-cef3-11e7-8705-ec3c7aa649ee.png)

**small note:** I have been dealing with this bug for quite some time now in a personal project and did not find any other mention of this anywhere else (maybe just here: #9293 but I'm not sure if it is the same)

If this was already reported or stated somewhere in the documentation then I am sorry, I could not find it :)

**Comment by hwillson** [comment]
Thanks for reporting this @averissimo - actually there is another issue that's already tracking this, https://github.com/meteor/meteor/issues/7013. Let's continue the discussion over there. Thanks!

**Comment by averissimo** [comment]
thanks, I tried to find if it was already reported but obviously failed!
