### ISSUE TITLE
`Meteor._get` method throws error when passed null

### ISSUE THREAD

**Issue by vfonic** [meteor/meteor#9405]
## The expected behavior.

I'd expect `_get` method to either:
1) Return the property requested
or
2) Return undefined if the property doesn't exist (or its value is undefined)

## The actual behavior.

`Meteor._get(null, 'asd')` throws an error:
```
VM147:3 Uncaught TypeError: Cannot use 'in' operator to search for 'asd' in null
    at _get (<anonymous>:3:24)
    at <anonymous>:1:1
```

## A **simple** reproduction!

Open any Meteor web app. Run `Meteor._get(null, 'asd')` in browser console.

Here's the modified code that I use:
```js
_get = function (obj /* , arguments */) {
  for (let i = 1; i < arguments.length; i++) {
    if (obj == null || typeof obj !== 'object') {
      return undefined;
    }
    obj = obj[arguments[i]];
  }
  return obj;
};
```

PS I believe we could make this function public (remove the underscore and/or change the name). I find myself needing to access certain sub-property a lot of times and, instead of doing:
```js
if (user && user.profile && user.profile.profilePic) { ... }
```

I prefer doing:
```js
if (_get(user, 'profile', 'profilePic') { ... }
```

It's shorter and easier to read.

Ruby on Rails provides similar method called `try`: https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/lib/active_support/core_ext/object/try.rb

The difference is that `try` needs to be chained (per property depth) (`user.try(:profile).try(:profilePic)`) and `try` method has good test coverage (I actually created this issue because I wanted to make modifications to `Meteor._get`, to show that it fails for null passed): https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/test/core_ext/object/try_test.rb

**Comment by abernix** [comment]
Any reason not to use a more well-defined/tested/feature-complete implementation like [Lodash's `_.get`](https://lodash.com/docs/4.17.4#get)?

**Comment by vfonic** [comment]
Hey @abernix!

This is great suggestion indeed. I was looking into switching to lodash from underscore, but since a huge part of my project's codebase depends on underscore, I haven't made the switch yet.

I'll look into switching, I guess that would be the simplest solution.

Feel free to close the issue if you think it's no longer relevant.
Thanks!

**Comment by abernix** [comment]
Great! I'll close this as we don't even use `Meteor._get` internally right now so its future is certainly dated (and I'm excited about that!).  There's really no reason for us to maintain our own method like this.  If the need arises internally for something like this in the future, it will be with a utility similar to that that provided by Lodash.

You may also be interested in Lodash's `_.unset`, `_.set`, `_.update`, etc., all of which you can start incrementally adopting alongside Underscore today, via something like:

```js
import { get as lodashGet } from 'lodash';
```
or

```js
import lodashGet from 'lodash.get';
```

and using as such:

```js
lodashGet('a.b.c');
```

Of course this will be dependent on you having `meteor npm install`-ed the module you're using (e.g. `lodash.get` or `lodash`).  For more information, consult the Lodash docs, or the forums!

**Comment by vfonic** [comment]
Great! No idea why I thought it's underscore or lodash. I'll start gradually replacing underscore with lodash. Thanks for the help and quick answer!
