### ISSUE TITLE
appcache and dynamic-imports don't play well together

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#9407]
It looks like appcache and dynamic-imports don't play well together. Appcache adds all the additional packages (those not in the initial bundle) to the app.manifest individually (conclusion based on looking in app.manifest), to instruct the browser to grab all those - but dynamic-imports doesn't seem to grab those files from the appcache. The effect is that the app won't load in offline mode, when it needs to grab a dynamic module (even if the module should be in the indexedDB cache - I'm not certain why that doesn't work - maybe this is the bug).

I confirmed this by disabling my use of dynamic-imports through React Loadable to get my app working offline - I have not confirmed my assumptions about _why_ it failed with any tests, though I did quickly read through the dynamic-imports package source, and didn't see anything which would indicate it's trying to load from appcache.

Additionally, if my assumptions are correct, we are double loading dynamic modules, which is not desired - once through appcache manifest, and once over DDP and stored in indexedDB.

Suggested solution - only add the initial bundle and CSS to the appcache manifest (or all the initial packages in development mode), and use a prefetch model to grab dynamic-modules over DDP and store in indexedDB (like it already does on demand) when the app is ready.

Alternative solution - make dynamic-imports load additional modules from appcache instead of over DDP/indexedDB, when that is appropriate. This solution is less desirable due to limits with the (deprecated) appcache tech. For exmaple, I have one app which it has been very difficult to get my bundle size down under the appcache file size limit imposed by iOS Safari, and that can [cause all kinds of horrendous side effects](https://alistapart.com/article/application-cache-is-a-douchebag).

More notes about general offline support [in this forum post](https://forums.meteor.com/t/appcache-and-dynamic-import-incompatible/40652).

**Comment by benjamn** [comment]
If the `appcache` package is in use, I'm inclined to say dynamic modules should get eagerly prefetched over DDP ([or soon HTTP](https://github.com/meteor/meteor/pull/9384)) and stored (as usual) directly in IndexedDB. In other words, I don't think dynamic `import()` should read from `appcache`, but I agree that the app should fetch all available dynamic modules eagerly, to make sure everything is available offline.

**Comment by CaptainN** [comment]
It sounds like we are on the same page. So the tasks would be:

1. Add eager loading capability somewhere - to either appcache or dynamic-imports. (Is there already a way to queue up files for dynamic import?)
2. Stop including dynamic modules in the appcache app.manifest to avoid double loading (and reduce pressure on appcache).

For 2. would it be enough to filter on files that start with '/dynamic/' and avoid putting them in the manifest?

For 1. We would need to take that same filtered list, and deliver it to the client, to be eagerly loaded (perhaps in some deprioritized queue).

**Comment by CaptainN** [comment]
The PR takes care of loading extra dynamic modules into the appcache that'll never be used.

I have some thoughts and questions on preloading:

1. Is there already a way to precache dynamic modules? Looks like maybe we can loop through the meteor manifest (like is done in appcache) and call `module.prefetch` for all "dynamic js" resource types (and maybe json /dynamic/....map files?)
2. It might be nice to load these files over a web worker. In an app I'm building now, preloading assets caused a lot of jank (mongo documents and images). I wonder whether it would cause less jank to load them in a web worker (or service worker eventually) which still has access to indexeddb.
3. Where should an attempt to preload dynamic js resources go - appcache or dynamic-imports?

**Comment by hwillson** [comment]
@CaptainN Thanks for your work on this via https://github.com/meteor/meteor/pull/9434. Now that the main issue here has been addressed (`#2` from https://github.com/meteor/meteor/issues/9407#issuecomment-346477016), would you mind opening a new feature request over in http://github.com/meteor/meteor-feature-requests to track your preloading ideas? The remaining ideas/comments here aren't directly related to an outstanding bug, so  let's track them in the FR repo. Closing - thanks!
