### ISSUE TITLE
duplicate key error since 1.6 `WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error 

### ISSUE THREAD

**Issue by QHose** [meteor/meteor#9408]
hey guys, 

Sorry for this vague description, but I really have the feeling that since meteor 1.6 I suddenly get 
![image](https://user-images.githubusercontent.com/12411165/33141031-20b1f4c8-cfb2-11e7-9177-35878cdb5c96.png)
```
WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error index: meteor.apiLogs.$_id_ dup key: { : ObjectId('5a15b1841ff9473df471d0ad') }","op":{"action":"Save app","url":"https://github.com/QHose/QRSMeteor/blob/master/imports/api/server/QRSFunctionsApp.js#L127","request":"App with GUID 3255e706-96c0-4a23-9689-f25b4f22e00e has been saved to disk","createDate":"2017-11-22T17:19:05.700Z","generationUserId":"pttLnhqxiP8QQaRDb","_id":"5a15b1841ff9473df471d0ad"}})
W20171122-18:19:05.751(1)? (STDERR)     at Function.MongoError.create (C:\Users\Qlikexternal\AppData\Local\.meteor\packages\npm-mongo\2.2.33\npm\node_modules\mongodb-core\lib\error.js:31:11)```
```

@robfallows  you helped me before with this, and I suspect this is caused because I use `rawCollection` inserts?

```
 export function REST_Log(call, userId = 'Not defined') {
    call.createDate = new Date();
    call.generationUserId = userId;
    if (Meteor.isServer) {
        APILogs.rawCollection().insert(call);
    } else {
        APILogs.insert(call);
    }
    return;

}
```

I needed this fix, because the mongo insert is done inside a async await (previously, after a call to an external API)

```
async function reloadAppAndReplaceScriptviaEngine(appId, newAppName, streamId, customer, customerDataFolder, scriptReplace, generationUserId) {
    console.log('--------------------------REPLACE SCRIPT AND RELOAD APP');

    //set the app ID to be used in the enigma connection to the engine API
    var config = Object.assign({}, enigmaServerConfig);
    config.appId = appId;

    try {
        //save the app
        var call = {};
        call.action = 'Save app'
        call.url = gitHubLinks.saveApp;
        call.request = 'App with GUID ' + appId + ' has been saved to disk';
        REST_Log(call, generationUserId);  //ISSUE OCCURS HERE
        await qix.app.doSave();

        REST_Log(call, generationUserId);
    } catch (error) {
        console.error('error in reloadAppAndReplaceScriptviaEngine via Enigma.JS, did you used the correct schema definition in the settings.json file?', error);
    }
```
thanks!

**Comment by QHose** [comment]
funny, If I just remove the `rawCollection` it now works fine

``` import { Mongo } from 'meteor/mongo';

export const APILogs = new Mongo.Collection('apiLogs');

export function REST_Log(call, userId = 'Not defined') {
    call.createDate = new Date();
    call.generationUserId = userId;
    APILogs.insert(call); 
} ```

**Comment by robfallows** [comment]
Basically, using `rawCollection` completely bypasses the way Meteor expects client and server inserts to work for optimistic UI. That includes generation of an `_id` on the client, which will match the `_id` used on the server for the actual insert.

What's happening in your example is that your client does an `insert` - which is then performed on the server using an Optimistic UI method. Then (before or after, depending on timing) you make an explicit insert using `rawCollection`, which means one of your inserts will fail with a duplicate key error (whichever gets there last will fail). (Or vice versa).

So, either don't use `rawCollection`, in which case Meteor will handle it for you, or use `rawCollection` on the server, but don't use anything on the client. The client will update anyway thanks to pub/sub - it may just take a few ms longer.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9408#issuecomment-346618884, this is not a Meteor issue (thanks @robfallows!).

**Comment by QHose** [comment]
Thanks a lot!

Verstuurd vanaf mijn iPhone

Op 23 nov. 2017 om 15:09 heeft Hugh Willson <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


As mentioned in #9408 (comment)<https://github.com/meteor/meteor/issues/9408#issuecomment-346618884>, this is not a Meteor issue (thanks @robfallows<https://github.com/robfallows>!).
