### ISSUE TITLE
CORS - iOS - Cordova

### ISSUE THREAD

**Issue by flean** [meteor/meteor#9417]
Trying to load stripe on iOS - Cordova, I've done this 

**mobile-config**
```
App.accessRule("https://*.stripe.com/*");
App.accessRule("https://*.stripe.com/*",{ type: 'navigation' });
App.accessRule("https://*.stripe.com/*",{ type: 'network' });
```

**Browser Policy**
```
	trusted = [
		'*.stripe.com'
	]
	_.each trusted, (origin) ->
		BrowserPolicy.content.allowOriginForAll(origin)
```
**Error in Client**
```Unable to post message to https://js.stripe.com. Recipient has origin http://localhost:12088.```

Suggestions on how to fix this? Thanks

**Comment by hwillson** [comment]
Hi @flean - GitHub issues here are reserved for issues with the Meteor core itself. This appears to be an application / 3rd party package configuration issue, and is not directly a bug with Meteor. Please try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`) for help. If you still feel like this is a bug with Meteor, please consider posting a small runnable reproduction that clearly demonstrates this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!
