### ISSUE TITLE
coffeescript dynamic-import not working

### ISSUE THREAD

**Issue by boomfly** [meteor/meteor#9418]
This code produce the error:

`import('/imports/ui/lib/jquery.particleground.min.js').then (result) -> console.log result`

Output:

```
Errors prevented startup:

While building for web.browser:
imports/ui/pages/landing/LandingPage.coffee:13:11: unexpected (

While building for os.osx.x86_64:
imports/ui/pages/landing/LandingPage.coffee:13:11: unexpected (

Your application has errors. Waiting for file change.
```

Mb dynamic-import with coffeescript have different approach?

**Comment by boomfly** [comment]
I found workaround:

```
module.dynamicImport('/imports/ui/lib/jquery.particleground.min.js').then (result) ->
```

**Comment by klaussner** [comment]
Dynamic imports are not (yet?) supported in CoffeeScript, so I think using `module.dynamicImport` directly is your only option. :slightly_smiling_face:
