### ISSUE TITLE
Meteor 1.6 breaks FlowRouter browser back navigation to initially loaded page

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9419]
After I upgraded my FlowRouter-based Meteor 1.5 app to 1.6, the browser back button doesn't work if the previous page is the initially loaded page of the app (i.e. the first page that was loaded, e.g. by reloading the app).

In this case, FlowRouter throws an error:

```js
index.js:380 Uncaught TypeError: Cannot read property '0' of undefined
    at new Context (http://localhost:3030/packages/kadira_flow-router.js?hash=efa30c014ae98f03c2b46e0157cd8b8888078379:513:21)
    at Function.page.replace (http://localhost:3030/packages/kadira_flow-router.js?hash=efa30c014ae98f03c2b46e0157cd8b8888078379:404:15)
    at Function.self._page.(anonymous function) [as replace] (http://localhost:3030/packages/kadira_flow-router.js?hash=efa30c014ae98f03c2b46e0157cd8b8888078379:2241:16)
    at onpopstate (http://localhost:3030/packages/kadira_flow-router.js?hash=efa30c014ae98f03c2b46e0157cd8b8888078379:664:14)
```

The error is caused by this call:
https://github.com/kadirahq/flow-router/blob/fb268d5ed3586b577faae27c3511ef84eaa7335d/client/router.js#L382
but actually pops up in the `pages`  node module:
https://github.com/visionmedia/page.js/blob/f241eafdc6b0a6545e27ad4dd82bcdeb305e7564/index.js#L380

If I downgrade my app to 1.5, it works again.

**Comment by abernix** [comment]
Have you tried using a more actively maintained fork of FlowRouter?  I believe that [`ostrio:flow-router-extra`](https://atmospherejs.com/ostrio/flow-router-extra) is still being maintained thanks to the work of @dr-dimitru, where as the Kadira version of FlowRouter is no longer being maintained ([for comparison](//github.com/kadirahq/flow-router)).

**Comment by hwillson** [comment]
If the suggestions in https://github.com/meteor/meteor/issues/9419#issuecomment-347129928 don't help, any chance you can provide a small runnable reproduction showing this happening?

**Comment by dr-dimitru** [comment]
@abernix thank you for mentioning our package, yes, we're always keep it up to date and test with every Meteor release, auto-tests is included.

@derwaldgeist I'm recommend to update to [`ostrio:flow-router-extra`](https://github.com/VeliovGroup/flow-router), which is pure replacement to original package. You will only need to import `FlowRouter` or make it global.

Also you might be interested to take a look on [this similar issue](https://github.com/VeliovGroup/flow-router/issues/32), but honestly - I think your issue is in outdated NPM dependency of `page` package.

**Comment by derwaldgeist** [comment]
@abernix No, I haven't tried this with ostrio:flow-router-extra, because tbh I don't like its overall concept. It mixes the original FlowRouter with a lot of stuff that, at least in my opinion, does not belong in a core router package. I also had the impression that the original FlowRouter was still recommended by MDG, but that maybe wrong.

@hwillson I can try to build a reproduction repository. In theory, this shouldn't be that tricky, because the problem occurs as soon as I upgrade the Meteor platform from 1.5 to 1.6.

**Comment by dr-dimitru** [comment]
> I don't like its overall concept

As I'm always saying - You don't have to use "Extra" features, it will work fine with original approach.

> I also had the impression that the original FlowRouter was still recommended by MDG, but that maybe wrong.

I guess we're in intermediate state:
 - [Pending Guide PR](https://github.com/meteor/guide/pull/640)
 - [Recommended by Blaze](http://blazejs.org/guide/routing.html#Flow-Router-Extra), but original FR has no deprecation notice
 - Somewhere else we had a discussion about transitioning to FR-Extra in a guide, forums, etc.

**Comment by derwaldgeist** [comment]
@dr-dimitru Thanks for sharing your thoughts. Don't get me wrong, I really appreciate that someone picked up FlowRouter and developed it further. I just liked the more "puristic", opinionated approach the original FlowRouter had and wanted to keep that. If all extra stuff is optional, then I'll give it another try.

**Comment by dr-dimitru** [comment]
@derwaldgeist np. Let me know how switching packages work for you.

**Comment by derwaldgeist** [comment]
I just had a look at the docs and now recall the most important reason that kept me from using it when I checked it last time: It's tight dependency on Blaze. Although my app is a mix of Blaze of React at the moment, I want to switch everything to pure React in the future. So having a router that's coupled with Blaze didn't make sense to me. ReactRouter, on the other hand, didn't work with Blaze, so I kept the original FlowRouter for now.

**Comment by derwaldgeist** [comment]
Ah, thumbs up for https://github.com/VeliovGroup/flow-router/issues/33 👍

**Comment by dr-dimitru** [comment]
@derwaldgeist I remember your request, it was few month ago, to remember it better and not miss in next release, just created https://github.com/VeliovGroup/flow-router/issues/33

We keep monthly updates/releases, so it should be delivered by end of the year.

**Comment by derwaldgeist** [comment]
Haha, I didn't even remember I made that request. Guess I'm getting old. :-)

**Comment by derwaldgeist** [comment]
This is strange. I tried to create a reproduction repo, without success so far. In the reproduction, it works as expected. But it my app it doesn't. I could boil this down to one significant difference in the `PopStateEvent` that is fired when I click on the back button:
- In the reproduction repo (and in my app running on Meteor 1.5), the event's `state` property is set to `{path: '/'}`.
- Once I upgrade my app to 1.6, however, the `state` becomes `{referrer: ''}`. This is why in the FlowRouter code `path` is set to undefined an trying to access `path[0]` fails.
I wonder what may cause this?

**Comment by derwaldgeist** [comment]
OK, I found the culprit. It is caused by the `okgrow:analytics` package which "monkey patches" `history.pushState()`. This monkey patch seems to work on Meteor 1.5, but not on 1.6.

**Comment by derwaldgeist** [comment]
Filed the problem under https://github.com/okgrow/analytics/issues/203

**Comment by dr-dimitru** [comment]
@derwaldgeist is it happens in both original FR and Extra?

**Comment by cfnelson** [comment]
@derwaldgeist Thanks again for reporting this issue. This has been fixed in our auto-analytics package with [PR #19](https://github.com/okgrow/auto-analytics/pull/19).

For anyone interested in the details please read the short summary below:

The issue was introduced in [v1.0.3](https://github.com/okgrow/auto-analytics/releases/tag/v1.0.3) of [@okgrow/auto-analytics](https://github.com/okgrow/auto-analytics). This bug seems to have affected `Flow Router` due to it's usage of the `window.history` API and its manipulation of `history.state`. 

**Please Note:** The cause for the bug was not due the `window.history.pushState()`  `"monkey patch"` as suggested above. 

The cause for the bug came from our usage of `window.history.replaceState()` on first page load. We use `replaceState()` to set the `referrer` key in `history.state` as state is `null` or `{}` on an initial page load. We were not checking for or copying across any existing state, this has been fixed in [PR #19](https://github.com/okgrow/auto-analytics/pull/19) 

**Additional Comments:**

The current `Flow Router` implementation is throwing an error as it assumes that the `path` exists in the `history.state` object.

If you run into similar issues as reported above with `Flow Router` it is most likely due to the `history.state` object having been modified.

**Comment by derwaldgeist** [comment]
@cfnelson Wow, that was fast. Highly appreciated! Thanks. In fact I wasn’t 100% sure if it was the “monkey patch” method or FR’s “creative” way of doing things :-) I only noticed that history.pushState had eben overridden by the monkey patch and the problem disappeared when I disabled the package.

@dr-dimitru I’m not sure. I tried to do a replacement of FR with FR extra for a couple of my routes, but this was overridden by other packages that still used FR. So replacing FR would have meant to replace FR in about 50-60 of my packages, which I will do at a later point of time. I was happy to find the root issue along the way, so I stopped trying out all potential side cases.

**Comment by derwaldgeist** [comment]
@cfnelson I’m curious to know why this problem did not appear in Meteor 1.5. Did you find this out?

**Comment by cfnelson** [comment]
@derwaldgeist No problems. It was your investigation that made the issue and cause clear to me. It helped a lot! 🎉 

I tested locally using our [flow router example](https://github.com/okgrow/analytics/tree/master/examples/flow-router) & surprisingly was able to reproduce using Meteor `1.5.2`, I could be mistaken about the version but I didn't dig any further as I only needed a working reproduction to test the fix I had. 

One possibility is when you upgraded to Meteor 1.6 the analytics package also updated which introduced the bug.

**Comment by dylanmcgowan** [comment]
I've been stuck on this bug for about a month and thought it had to do with `flow-router`...  Will you be updating the meteor package any time soon? Or should I refactor my app to use the npm package? If refactoring's the case, does`{"people": true}` still work with meteor user accounts?  And does this package work with `meteor --settings`?

**Comment by cfnelson** [comment]
@dylanmcgowan A fix for both the npm & atmosphere package has been published.  😄 Check out [okgrow:analytics@v3.0.5](https://github.com/okgrow/analytics/releases/tag/v3.0.5) for the details or just run `meteor update`. 👍
