### ISSUE TITLE
Meteor not fully working on Windows Subsystem for Linux (WSL) [with workaround]

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9426]
I have been working to get Meteor up and running under Windows Subsystem for Linux (WSL).  I have met with some pretty good success, but I am now blocked on one issue.  Also, I am finding that I really like the `bash` shell.

I can run a single `meteor` instance.  If I try to run a 2nd instance I get an error:
```
Error: SQLITE_IOERR: disk I/O error
```

(Why am I running a 2nd instance?  I have a microservice and 2 client apps using it)

This appears to be because of: https://github.com/Microsoft/WSL/issues/1927
Also related: https://github.com/Microsoft/WSL/issues/2395

Also, others are seeing this as well: https://forums.meteor.com/t/meteor-create-error-in-vagrant-box/9133

### Workaround?
These bugs claim that the issue can be worked around if WAL mode is disabled for SQLite access.  I hacked my local version of the tools by changing this line:
https://github.com/meteor/meteor/blob/devel/tools/packaging/catalog/catalog-remote.js#L144
to
```
self._execute('PRAGMA journal_mode=TRUNCATE');
```
And it worked!

#### Option 1 new environment variable
Add an environment variable, `METEOR_SQLITE_JOURNAL_MODE`.  If `METEOR_SQLITE_JOURNAL_MODE` is set then open SQLite with `journal_mode=$METEOR_SQLITE_JOURNAL_MODE`.

A flag like this may be useful for users that are seeing this issue.

#### Option 2 change journal mode
or could simply make the change to `TRUNCATE`.

Let me know if you want me to submit a PR for this.

### Environment
- Window 10 Version 1709 (OS Build 16299.64)
- WSL Ubuntu Release: 16.04

### Repro
1. Get meteor running on WSL essentially it is the same as for Ubuntu
2. Start meteor instance using port `3080`
3. Verify it works.
4. Start a 2nd meteor instance using port `4000`

**Result:** fails with `Error: SQLITE_IOERR: disk I/O error`

### Full Output
```
bruce@DEVPC:/mnt/e/u/mroot/meris$ meteor npm start

> MERIS@1.0.0 start /mnt/e/u/mroot/meris
> meteor npm run startl


> MERIS@1.0.0 startl /mnt/e/u/mroot/meris
> env ROOT_URL=$LOCAL_URL meteor -p $PORT --mobile-server $LOCAL_URL --settings settings-development.json

Retrying after error { Error: SQLITE_IOERR: disk I/O error
=> awaited here:
at Promise.await
(/home/bruce/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
at /tools/packaging/catalog/catalog-remote.js:144:10
at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
at /tools/cli/main.js:869:20 errno: 10, code: 'SQLITE_IOERR' }
Retrying after error { Error: SQLITE_IOERR: disk I/O error
=> awaited here:
at Promise.await
(/home/bruce/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
at /tools/packaging/catalog/catalog-remote.js:144:10
at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
at /tools/cli/main.js:869:20 errno: 10, code: 'SQLITE_IOERR' }
/home/bruce/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: SQLITE_IOERR: disk I/O error
 => awaited here:
    at Promise.await (/home/bruce/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
    at /tools/packaging/catalog/catalog-remote.js:144:10
    at Db._retry (/tools/packaging/catalog/catalog-remote.js:156:16)
    at new Db (/tools/packaging/catalog/catalog-remote.js:143:8)
    at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:700:15)
    at /tools/cli/main.js:869:20
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MERIS@1.0.0 startl: `env ROOT_URL=$LOCAL_URL meteor -p $PORT --mobile-server $LOCAL_URL --settings settings-development.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MERIS@1.0.0 startl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2017-11-28T03_30_25_126Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MERIS@1.0.0 start: `meteor npm run startl`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MERIS@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2017-11-28T03_30_25_153Z-debug.log.log
```

**Comment by hwillson** [comment]
@brucejo75 Thanks for your detailed findings on this! Please don't hate me, but would you mind moving this discussion over to https://github.com/meteor/meteor-feature-requests? FR https://github.com/meteor/meteor-feature-requests/issues/154 relates to this, so you might want to add these details there. Getting Meteor fully working with Windows Subsystem for Linux would be awesome, but we're trying to keep issues here reserved for bugs only. Thanks!

**Comment by brucejo75** [comment]
@hwillson,

No worries!

Will PR OK be granted from the feature request?  I think enabling a workaround via an environment variable is a pretty good solution?

Thanks!

**Comment by abernix** [comment]
@brucejo75 We prefer automatic detection over additional configuration (which requires discovery and implementation by users who are experiencing the problem).  If that's not possible, or this needs to be explored without breaking for another segment of users, then an environment variable might be a temporary option, but I'd like to avoid considering that as a solution.  If you're confident in the solution (and can reason around and downsides to that change) I'd suggest we detect and make the change for everyone.  Happy to discuss further in a FR!
