### ISSUE TITLE
[1.6] [Windows x64] Cannot start application after upgrade

### ISSUE THREAD

**Issue by ExcelNet-Public** [meteor/meteor#9427]
System is Windows 10 x64 build 1709 with current updates

Performed the upgrade in Windows from 1.5.2.4 to 1.6 and everything seemed to process according to plan.  That is right up until I try to run any application that we have on our development box!  When I run it as I have been for the previous releases I get the following:

```
>meteor --settings settings.json
[[[[[ C:\Users\lweidig\meteor\excel.net ]]]]]

=> Started proxy.
=> Started MongoDB.
W20171129-09:53:08.739(-6)? (STDERR) C:\Users\lweidig\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20171129-09:53:08.896(-6)? (STDERR)                                            throw(ex);
W20171129-09:53:08.912(-6)? (STDERR)                                            ^
W20171129-09:53:08.928(-6)? (STDERR)
W20171129-09:53:08.945(-6)? (STDERR) Error: Cannot find module 'meteor/tools'
W20171129-09:53:08.964(-6)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171129-09:53:08.968(-6)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20171129-09:53:08.970(-6)? (STDERR)     at Object.require (C:\Users\lweidig\meteor\excel.net\.meteor\local\build\programs\server\boot.js:287:32)
W20171129-09:53:08.971(-6)? (STDERR)     at makeInstallerOptions.fallback (packages\modules-runtime.js:651:18)
W20171129-09:53:08.972(-6)? (STDERR)     at require (packages\modules-runtime.js:244:16)
W20171129-09:53:08.973(-6)? (STDERR)     at base.js (imports/startup/server/devices/customer/base.js:1:308)
W20171129-09:53:08.974(-6)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171129-09:53:08.975(-6)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20171129-09:53:08.976(-6)? (STDERR)     at index.js (imports/startup/server/devices/index.js:1:14)
W20171129-09:53:08.977(-6)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171129-09:53:08.977(-6)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20171129-09:53:08.980(-6)? (STDERR)     at index.js (imports/startup/server/index.js:1:321)
W20171129-09:53:08.981(-6)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171129-09:53:08.982(-6)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20171129-09:53:08.983(-6)? (STDERR)     at main.js (server/main.js:1:14)
W20171129-09:53:08.984(-6)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
=> Exited with code: 1
```

We do use locally created packages as well for the development of our applications.  Wondering if this issue could also be related to [https://github.com/meteor/meteor/issues/9287](https://github.com/meteor/meteor/issues/9287)?  Would be nearly impossible to have anything useful removing the local packages.

Have tried running meteor create test16 and then starting that empty application.  It does indeed work, though not very exciting, I did click the button 5 times :).

Have tried uninstalling the external mode version I have on system, though it was 8.8.1 as well.  Tried running a meteor reset on the application.  Tried meteor npm rebuild,meteor npm update, metoer npm install...  All to no avail.  Happy to provide any additional details needed to get this back up and going.  We need development to continue, but have to be using tools that are supported with their latest releases, not to mention we would like the node upgrade for MANY reasons also.  

Thanks in advance!

**Comment by benjamn** [comment]
Can you paste your `packages/tools/package.js` file here (assuming you have a local packages called `tools`)?

**Comment by ExcelNet-Public** [comment]
I am so sorry to have wasted time, there was literally this line in my code:

`import { Package } from 'meteor/tools';
`

Though I have NO clue how that was added.!
