### ISSUE TITLE
[1.6.1] dynamic-import stopped working (503 Service Unavailable)

### ISSUE THREAD

**Issue by bmanturner** [meteor/meteor#9428]
Ran into a problem updating to 1.6.1-beta.11 (from 1.6). Dynamic import stopped working for me. This issue was also experienced by @alexgzhou [here](https://github.com/meteor/meteor/pull/9274#issuecomment-346768135) in transition from beta.8 to beta.9

Tested like this:
```import('redux-thunk').then(c => console.log(c))```

Ran it in 1.6 and received desired result. Upgraded to 1.6.1-beta.11 and it never resolved. 

While troubleshooting I did the following (which did work, but obviously doesn't give me the benefit of dynamic import):

```
import 'redux-thunk';
import('redux-thunk').then(c => console.log(c));
```

Additional notes:
* I import this within a meteor package
* I use onPageLoad on the server
* I use ```WebApp.connectHandlers.use``` to register '/apple-app-site-association' and '/_hooks/patreon-update' endpoints
* I use ```WebApp.rawConnectHandlers.use``` to set CORS/cache headers (and I do call next())
* Network shows call to ```__dynamicImport``` but it eventually (503)

**Comment by bmanturner** [comment]
I found the culprit in my own codebase. It doesn't matter if ```dynamic-import``` is loaded before or after this.

```
WebApp.connectHandlers.use(bodyParser.json()).use('/_hooks/patreon-update', (req, res, next) => {
  // ...
});
```

When I remove ```.use(bodyParser.json())``` it works again.

**Comment by bmanturner** [comment]
I guess this was a silly one on my part? Here's my fix:

```
WebApp.connectHandlers.use('/_hooks/patreon-update', bodyParser.json()).use((req, res, next) => {
  // ...
});
```

@benjamn Let me know if you think I should close this.

**Comment by bmanturner** [comment]
Here's my fix.

```
WebApp.connectHandlers.use('/_hooks/patreon-update', bodyParser.json()).use('/_hooks/patreon-update', (req, res, next) => {
  // ...
});
```

@benjamn Let me know if I should close this issue. Thanks.

**Comment by benjamn** [comment]
@bmanturner Thanks for digging into this! I think we should keep the issue open, because these kinds of middleware mis-cooperation problems are clearly somewhat common (more than one report already, and 1.6.1 is only in beta), so we should find a way of avoiding these problems.
