### ISSUE TITLE
Reactive data to <select> method with Blaze ? 

### ISSUE THREAD

**Issue by ramintagizade** [meteor/meteor#9431]
I am trying to achieve infinite scrolling but not possible to achieve reactivity , select options with Materialize dropdown style not updating dynamically when subscriptions ready .  I see in console that new Data has arrived when scrolled to bottom in a helper method , but it is not rendering in template . 

    <template name="icons">
       
      {{#if newData}}
      <i class="material-icons"> <span class="iconsclass">{{this.icon}}</span></i>
      <select class="iconsSelect" id="icons" name="icon">
         <option value="tab"  data-id="tab"> {{this.icon}} </option>
         {{Debug icons}} 
        {{#each icons}} 
          <option value="{{this.icon}}" data-id={{this.icon}}><i class="material-icons">{{this.icon}}</i></option> 
        {{/each}}
        {{#unless Template.subscriptionsReady}}
          {{> iconSpinner}}
        {{/unless}}
      </select>
      {{/if}}
      
</template>
  
     <template name="iconSpinner">
        <option>Icons loading ...</option>
     </template>

**Comment by hwillson** [comment]
Hi @ramintagizade - GitHub issues here are reserved for bugs with Meteor itself. For help with using Meteor, please try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Thanks!
