### ISSUE TITLE
Refresh takes excessive amount of time

### ISSUE THREAD

**Issue by Praunda** [meteor/meteor#9432]
I am new to meteor but one thing that didn't get why refreshing takes a lot of time? To be honest I never refreshed the localhost by just saving, I have to stop the running terminal and re run the meteor command. Is there any solutions that you can offer? I am using Ubuntu as my OS.

**Comment by hwillson** [comment]
Hi @Praunda - welcome to the wonderful world of Meteor! 🙂 Rebuilding / refreshing your application while working with the Meteor Tool shouldn't take long, unless something is unintentionally slowing that process down. To troubleshoot further, can you provide more specific details about your setup? If you can provide a runnable reproduction that shows the rebuild taking a while, that would be ideal. But at the very least, could you please answer:

- What version of Meteor are you using?
- Are you using a new application or an existing application?
- How big is your application?
- What packages (Meteor packages and npm) is your application using?
- When you say refreshing take a lot of time, how much time do you mean?
- Can you try running your application like `METEOR_PROFILE=1 meteor` and post the profiling results?

Thanks!

**Comment by hwillson** [comment]
Closing as we haven't hard back regarding the extra requested details in https://github.com/meteor/meteor/issues/9432#issuecomment-348475082. Happy to re-open once those details are provided. Thanks!
