### ISSUE TITLE
Using our own Authentication service with Meteor Account

### ISSUE THREAD

**Issue by renganatha10** [meteor/meteor#9436]
HI Team

We are building system which has separate Authentication service. What are the ways to bind our Authentication service to Meteor one

So if try to access the Methods in Accounts packages i should able to access those methods 
http://docs.meteor.com/api/accounts.html#Meteor-user

**Comment by hwillson** [comment]
Hi @renganatha10 - Issues here are reserved for bugs with Meteor itself. For assistance with using Meteor, please try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Thanks!
