### ISSUE TITLE
Multiple manual publication of the same document causes "Exception in queued task: Error: Removed nonexistent document"

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#944]
If I have two `observeChanges()` listeners both sending `remove()` changes to a subscription on the same document, when that document is removed, the second fails, repeatedly outputting: 

```
Exception in queued task: Error: Removed nonexistent document AvPkPDGDt6AxTWvsX
```

It's quite bad as it basically kills the Meteor server.

**Reproduction:**
1. `git clone https://github.com/tmeasday/meteor-double-publication-remove-bug.git`
2. `cd meteor-double-publication-remove-bug; meteor`

In console, type:
1. `Posts.insert({foo: 'bar'});`
2. `Meteor.call('removePosts');`

**Observed behaviour:**
1. Server console spews out errors, app becomes unresponsive.

**Expected behaviour:**
1. Document is removed from subscription.

The code might seem a little weird but it can happen in complex use cases of https://github.com/erundook/meteor-publish-with-relations. Although it probably should be avoided, it shouldn't kill your server if you do do it I would have thought :)

**Comment by patrickml** [comment]
any updates?

**Comment by tmeasday** [comment]
@patrickml I'm not sure you are seeing the same error -- the issue I was describing blows up the server, which is quite different to what you describe here..?

**Comment by patrickml** [comment]
You are correct. My issue had to do with the removed non existent document
-- not necessarily an infinite loop. It turned out I was still returning a
cursor and observing changes to transform documents in order to add a flag
to the document. It was a simple fix. Thanks for the reply tho.
