### ISSUE TITLE
[1.6] Linux bundle fails to start (Error: Cannot find module "fibers/future")

### ISSUE THREAD

**Issue by naho2081** [meteor/meteor#9452]
OS: ```Ubuntu 14.04.4```
Build command (build is successful): ```meteor build --architecture os.linux.x86_64 --directory ..```
Node.js version: `v8.3.0`
New Meteor version: `1.6`
Previous Meteor version: `1.4.2.3`

`cd bundle/`
```NODE_ENV="production" MONGO_URL="__mongo-url__"  ROOT_URL="http://project.com" node main.js```

Error:
```
/home/project/bundle/programs/server/boot.js:467
}).run();
   ^

Error: Cannot find module "fibers/future"
    at Object.require (/home/project/bundle/programs/server/boot.js:294:24)
    at packages/meteor.js:143:20
    at packages/meteor.js:313:4
    at packages/meteor.js:1444:3
    at infos.forEach.info (/home/project/bundle/programs/server/boot.js:414:13)
    at Array.forEach (<anonymous>)
    at /home/project/bundle/programs/server/boot.js:413:9
    at /home/project/bundle/programs/server/boot.js:463:5
    at Function.run (/home/project/bundle/programs/server/profile.js:510:12)
    at /home/project/bundle/programs/server/boot.js:462:11
```

How this can be fixed?

**Comment by klaussner** [comment]
Did you run `npm install` in the `programs/server` directory of the build? See https://guide.meteor.com/deployment.html#custom-deployment, especially the second code snippet in that section.

**Comment by naho2081** [comment]
@klaussner thanks much! This helped to fix the issue.
I have missed this line `(cd programs/server && npm install)`
