### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE 

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9453]
I am facing this error while sending http call from server to server.

`Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE`

I have created Rest Apis on 2 different servers using Meteor Package: 

`nimble:restivus`

They both communicate each other, on one server I get this error each time it is called. Both servers are based on SLL HTTPS.

Any idea what is going wrong here?

**Comment by hwillson** [comment]
This sounds like an issue with how you have your SSL certificate setup on the problematic server. Google around a bit and you'll find countless reports of people hitting this error, stemming from SSL cert misconfiguration (like failing to properly bundle intermediate CA's). If you're looking for a workaround that doesn't involve fixing the SSL setup, take a look at https://www.npmjs.com/package/ssl-root-cas. Either way, this doesn't appear to be a Meteor issue. Thanks!
