### ISSUE TITLE
What's changed in v1.6.0.1 vs v1.6.0?

### ISSUE THREAD

**Issue by vfonic** [meteor/meteor#9461]
I just saw a message that a new (patch? pre?) version of meteor is available.

I wanted to check what's new, but can't find anything in the Changelog: https://github.com/meteor/meteor/blob/9cae673e1d104d4b36180822edce0b63c533dc44/History.md

I think providing "users" of the package with the changes since the last version, is the best way for them to update to the latest versions. Is there anything to how rails does it?
 (http://weblog.rubyonrails.org/2017/9/27/Rails-4-2-10-released/)

PS What's the versioning scheme that meteor follows? Is it [SemVer](https://semver.org/)?

**Comment by hwillson** [comment]
Hi @vfonic - see the `History.md` in the `devel` or `master` branch:

https://github.com/meteor/meteor/blob/master/History.md#v1601-2017-12-08

We try to make sure all important changes are broken out in the `History.md`. No, Meteor releases do not follow SemVer.

**Comment by vfonic** [comment]
Found it!

https://github.com/meteor/meteor/blob/devel/History.md#v1601-2017-12-08

I followed the docs.meteor.com changelog: http://docs.meteor.com/changelog.html

The `code` git submodule should be updated here:
https://github.com/meteor/docs

**Comment by hwillson** [comment]
Oh, yes - updating the changelog at that location is a bit of a manual process. We'll make sure that get's fixed. Thanks for the reminder!

**Comment by abernix** [comment]
Updated!  http://docs.meteor.com/changelog.html

As stated above, the most recent version is always here in this repository, but we do try to get the docs version updated as quickly as possible too.  Thanks for the ping!

**Comment by vfonic** [comment]
Thanks for answering so promptly! 🎉
