### ISSUE TITLE
 Error on deploy 1.6.1-beta18 - TypeError: Object.getOwnPropertyDescriptors is not a function

### ISSUE THREAD

**Issue by Gervwyk** [meteor/meteor#9470]
Deployment with Meteor version 1.6.1-beta18
Did not have this problem in 1.6
Error is given on deployment using `meteor-now` see:
```
TypeError: Object.getOwnPropertyDescriptors is not a function
 at insert (packages/mongo/collection.js:435:12)
 at updateVersions (packages/autoupdate.js:125:20)
 at packages/autoupdate.js:189:3
 at Function.time (/usr/src/app/bundle/programs/server/profile.js:309:28)
 at /usr/src/app/bundle/programs/server/boot.js:423:13
 at /usr/src/app/bundle/programs/server/boot.js:464:5
 at Function.run (/usr/src/app/bundle/programs/server/profile.js:510:12)
 at /usr/src/app/bundle/programs/server/boot.js:462:11
```
[stackof question](https://stackoverflow.com/questions/47799606/cant-deploy-meteor-app-in-zeit-object-getownpropertydescriptors-is-not-a-functi#)

I looked at change commits and think it might be related to where getOwnPropertyDescriptor was introduced:
https://github.com/meteor/meteor/commit/7f8ed5692ed5390bc6e2f4b7b63cae1036fb4410

**Comment by Themandunord** [comment]
Same error when I deploy to zeit 👍

**Comment by benjamn** [comment]
What version of `ecmascript-runtime-client` do you see in `.meteor/versions`? And what version do you see in `node_modules/core-js/package.json`?

The polyfill for `Object.getOwnPropertyDescriptors` should be coming from [here](https://github.com/meteor/meteor/blob/9b056f5e911513fb3df716bd524d504cceb863f4/packages/ecmascript-runtime-client/runtime.js#L41), since `core-js/es7/object.js` includes that polyfill [here](https://github.com/zloirock/core-js/blob/e1c6719a107b92d21125178b859026a04d5d4686/es7/object.js#L1).

**Comment by Themandunord** [comment]
```
ecmascript@0.10.0-beta161.18
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.0-beta161.18
ecmascript-runtime-server@0.5.0
```


```
{
  "_args": [
    [
      "core-js@2.5.3",
      "C:\\DEV\\Mantra Kickstarter 2"
    ]
  ],
  "_from": "core-js@2.5.3",
  "_id": "core-js@2.5.3",
  "_inBundle": false,
  "_integrity": "sha1-isw4NFgk8W2DZbfJtCWRaOjtYD4=",
  "_location": "/core-js",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "core-js@2.5.3",
    "name": "core-js",
    "escapedName": "core-js",
    "rawSpec": "2.5.3",
    "saveSpec": null,
    "fetchSpec": "2.5.3"
  },
  "_requiredBy": [
    "/@babel/runtime",
    "/babel-register",
    "/babel-runtime",
    "/recast"
  ],
  "_resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz",
  "_spec": "2.5.3",
  "_where": "C:\\DEV\\Mantra Kickstarter 2",
  "bugs": {
    "url": "https://github.com/zloirock/core-js/issues"
  },
  "description": "Standard library",
  "devDependencies": {
    "LiveScript": "1.3.x",
    "es-observable-tests": "0.2.x",
    "eslint": "4.13.x",
    "eslint-plugin-import": "2.8.x",
    "grunt": "^1.0.1",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-clean": "^1.1.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-uglify": "3.2.x",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-karma": "^2.0.0",
    "grunt-livescript": "0.6.x",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-firefox-launcher": "^1.0.1",
    "karma-ie-launcher": "^1.0.0",
    "karma-phantomjs-launcher": "1.0.x",
    "karma-qunit": "1.2.x",
    "phantomjs-prebuilt": "2.1.x",
    "promises-aplus-tests": "^2.1.2",
    "qunitjs": "2.4.x",
    "temp": "^0.8.3",
    "webpack": "^3.10.0"
  },
  "homepage": "https://github.com/zloirock/core-js#readme",
  "keywords": [
    "ES3",
    "ES5",
    "ES6",
    "ES7",
    "ES2015",
    "ES2016",
    "ES2017",
    "ECMAScript 3",
    "ECMAScript 5",
    "ECMAScript 6",
    "ECMAScript 7",
    "ECMAScript 2015",
    "ECMAScript 2016",
    "ECMAScript 2017",
    "Harmony",
    "Strawman",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Promise",
    "Symbol",
    "TypedArray",
    "setImmediate",
    "Dict",
    "polyfill",
    "shim"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "core-js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zloirock/core-js.git"
  },
  "scripts": {
    "grunt": "grunt",
    "lint": "eslint ./",
    "observables-tests": "node tests/observables/adapter && node tests/observables/adapter-library",
    "promises-tests": "promises-aplus-tests tests/promises-aplus/adapter",
    "test": "npm run grunt clean copy && npm run lint && npm run grunt livescript client karma:default && npm run grunt library karma:library && npm run promises-tests && npm run observables-tests && lsc tests/commonjs"
  },
  "version": "2.5.3"
}

```

**Comment by benjamn** [comment]
Oh, wait, I see this error is happening on the server, and we assume `Object.getOwnPropertyDescriptors` exists on the server (because we assume you're using Node 8.9.3). Are you sure Zeit is using Node 8.9.x to run the deployed app?

**Comment by Themandunord** [comment]
> We're running the latest version of Node.js by default. In order to customize which version of Node should be run within your deployment, you can specify the enginesfield in package.json.

**Comment by Themandunord** [comment]
I force the engine to use 8.9.x version of node. But same issue.
And I don't see the node version on the logs :/

**Comment by Gervwyk** [comment]
https://zeit.co/docs/deployment-types/node#custom-node.js-configuration
also looking into this. Trying to figure out if meteor-now is settings something in the docker file, but not really finding anything.
https://github.com/jkrup/meteor-now/search?utf8=%E2%9C%93&q=node&type=
never worked with docker so not sure what to look for.

**Comment by Lepozepo** [comment]
I think [this](https://github.com/jkrup/meteor-now/blob/master/src/api/docker.js#L9) needs `node:carbon` instead of `node:boron` if you're using `meteor-now` to deploy @Gervwyk @orozcorp

**Comment by timneutkens** [comment]
@Lepozepo I've created a PR based on your comment 👍

**Comment by timneutkens** [comment]
New version of meteor-now is out! https://github.com/jkrup/meteor-now/pull/91#issuecomment-353240729

**Comment by hwillson** [comment]
This issue was resolved by https://github.com/jkrup/meteor-now/pull/91. Closing - thanks!

**Comment by timneutkens** [comment]
👌

**Comment by inromualdo** [comment]
Hi 
What is the solution of this issue. I deploy with passenger and ngInx.

**Comment by janat08** [comment]
Using node 8
