### ISSUE TITLE
METEOR_PROFILE is broken

### ISSUE THREAD

**Issue by ofpiyush** [meteor/meteor#9472]
Meteor version : 1.6.0.1
Last version it did not happen on : 1.5.2.2
OS: Darwin
Expected behaviour: See entire profile data
Actual behaviour: Profile data is only visible for `ProjectContext prepareProjectForBuild`
## Steps to reproduce
```bash
meteor create yolo
cd yolo
METEOR_PROFILE=100 meteor build ../out 
```

## Output will look like

```
 (#1) Profiling: ProjectContext prepareProjectForBuild
|  Building local packages                   /
| ProjectContext prepareProjectForBuild.........................1,872 ms (1)
| ├─ _resolveConstraints..........................................635 ms (1)
| │  ├─ bundler.readJsImage.......................................177 ms (1)
| │  │  └─ meteorNpm.rebuildIfNonPortable.........................159 ms (11)
| │  │     └─ meteorNpm.isPortable                                153 ms (207)
| │  └─ JsImage#load..............................................413 ms (1)
| │     └─ runJavaScript packages/npm-mongo.js....................135 ms (1)
| │        └─ Npm.require("mongodb")                              135 ms (1)
| └─ _buildLocalPackages........................................1,125 ms (1)
|    └─ IsopackCache Load local isopack.........................1,070 ms (75)
|       └─ Isopack#initFromPath.................................1,006 ms (75)
|          ├─ files.read                                          137 ms (594)
|          ├─ bundler.readJsImage.................................322 ms (5)
|          │  └─ meteorNpm.rebuildIfNonPortable...................298 ms (25)
|          │     └─ meteorNpm.isPortable..........................285 ms (558)
|          │        └─ optimistic readJsonOrNull..................134 ms (500)
|          │           └─ optimistic readFile.....................116 ms (500)
|          │              └─ files.readFile                       104 ms (500)
|          ├─ meteorNpm.rebuildIfNonPortable......................298 ms (19)
|          │  └─ meteorNpm.isPortable.............................289 ms (398)
|          │     ├─ optimistic lstat                              123 ms (398)
|          │     └─ optimistic readJsonOrNull                     105 ms (352)
|          └─ other Isopack#initFromPath                          103 ms
|
| Top leaves:
| files.readFile.............................................372 ms (1510)
| files.read.................................................137 ms (594)
| other Isopack#initFromPath.................................103 ms (75)
|
| (#1) Total: 1,872 ms (ProjectContext prepareProjectForBuild)
|
```

**Comment by benjamn** [comment]
What happens if you use a smaller threshold (milliseconds), like `METEOR_PROFILE=10`?

**Comment by ofpiyush** [comment]
@benjamn I tried with 1, nothing changes. 

I opened the code, tried a bunch of tricks, wrapping buildCommand's invocation with `Profile.run("build",()=>{return buildCommand(options)});` helped bring back some profile information.

Is it possible that some `.run` calls have gone missing?

**Comment by benjamn** [comment]
If you've tried other Meteor versions, does it work with the latest 1.5.x version, 1.5.4.1? What about 1.6?

**Comment by ofpiyush** [comment]
@benjamn sadly, my local isn't that clean right now and while debugging this, I have added quite a few profile points that I needed to fix my build. 

Reproducing is rather straight forward, if you have various clean envs.
If no one makes any progress on this, I will try again this weekend.

Other than that, If I come across something obvious, I will post here.

Eg: tarball is really slow. I used the `--directory` flag and tar gzipped using linux command, saved almost a minute in my build time. That and minification were the worst offenders in my build.

Should I make a separate issue for it?

**Comment by hwillson** [comment]
@ofpiyush I just tested going back as far as Meteor 1.4.4.5, and the `ProjectContext prepareProjectForBuild` step is the only step that is ever reported for me, when using `meteor build`. Using `METEOR_PROFILE` with `meteor run` covers all of the additional steps as expected (across all versions), but it doesn't look like `meteor build` was ever setup to cover more than the `ProjectContext prepareProjectForBuild` step. I don't think this is a regression. Have you seen differently?

If this functionality hasn't existed before and you think it should be added, then please consider closing this issue here and opening a feature request over in http://github.com/meteor/meteor-feature-requests/issues. Thanks!

**Comment by ofpiyush** [comment]
@hwillson oh you're right. It could be possible that I am confusing between `build` and `run`

Sure, I will open the feature request :)

Thanks again!
