### ISSUE TITLE
Meteor doesn’t logout

### ISSUE THREAD

**Issue by neutron92** [meteor/meteor#9475]
METEOR@1.5.2.2

I can’t logout with Meteor.logout(function(err){
console.log(“loginot”,err);
})

**Comment by menelike** [comment]
@neutron92 It's always helpful to add some details to a bug report, at least the specific Meteor version is needed to give other's a chance to reproduce your issue.

**Comment by neutron92** [comment]
METEOR@1.5.2.2

**Comment by hwillson** [comment]
@neutron92 Please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor). You haven't given us much to go on here, and `Meteor.logout` is being used by countless others without any problems. If there is some specific code combination that is preventing `Meteor.logout` from working for you, then we'll need to see more details to help figure out the problem (ideally in the form of a small runnable reproduction). I'll close this issue for now, but I'm happy to re-open it if you can provide more details. Thanks!
