### ISSUE TITLE
Mongo queries slower on production bundle

### ISSUE THREAD

**Issue by dolle39** [meteor/meteor#9478]
I have an issue with monqo queries running slow after building the meteor app for production. But the problem is not in dev mode (i.e. `meteor run`). And with slow I mean up to 10 times slower!

I have batch job which makes multiple updates on a collection as well as alot of reads from the same collection and other collections.

First I though it was hardware related but then I ran the production bundle on the same machine as which I develop but it was slow on dev machine as well. 

I then managed to narrow down the problem to  slow mongo queries. I,e (`Collection.find(...), Collection.update(...)`)

I build the app with the following command:

```
ARCHITECTURE=os.linux.x86_64
mkdir -p /tmp/meteor/builds && meteor build /tmp/meteor/builds --architecture ${ARCHITECTURE}
```

Then I made sure that it was not related to wrong version of mongo or wrong version of node. So I used the binaries which comes packages with meteor. I start the mongo process in the exact same way as `meteor run` does;

`/home/user/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod  --bind_ip 127.0.0.1 --port 3001 --dbpath /home/user/workspace/myApp/app/.meteor/local/db --oplogSize 8 --replSet meteor --nojournal`

This made no difference. And I should also point out that I have restored the same database as I use in production so its nothing special about the database.

I have set the environment variables for mongo;

```
export MONGO_URL="mongodb://127.0.0.1:3001/meteor?replicaSet=meteor"
export MONGO_OPLOPG_URL="mongodb://127.0.0.1:3001/local?replicaSet=meteor"
```
Also I have seen that if I comment out the place where I update the collection in the batch job, all other find queries run fast:

`   //MyCol.update(item._id, updateDoc); // Commenting out this lines make all queries run faster`

Note: This statement is not updating any indexes.

This statement will be synchronous so why is it slowing down the database?

If this is not a meteor bug then what is the difference between `meteor run` and the bundled app using the exact same environment as dev, including node, mongo etc.?

**Comment by Deadly0** [comment]
@dolle39 Did you try to run `meteor run --production` on your local machine? Is it works slow or fast?

**Comment by hwillson** [comment]
@dolle39 To help verify that this is a Meteor issue, could you please put together a small runnable reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)) that shows this happening? Something along the lines of a small app that runs a couple of Mongo queries and dumps timing information, along with step by step instructions for seeing the slowdown when running in dev versus prod mode. Thanks!

**Comment by dolle39** [comment]
I have figured out what causes the problem but I don't understand why there is a difference between production and development.

So the slow queries is seen when a client subscribes on the same collection which is updated in the batch-job. 

I have created a repository so that the problem can easily be reproduced.

Please clone: https://github.com/dolle39/test-meteor-problem-slow-prod

I have branched of the todos example project. 

When started. Please open up the debugger and in the console run:

`Meteor.call('myBatchJobFillDatabase', 10000)`

This inserts documents in the TestCol collection which we will also subscribe on.

Then to update the collection with a batch job run:

Meteor.call('myBatchJobUpdate', "test-name")

You will see the list to the left update. 

Now in the server terminal see the timing for each `findOne()` call. These are alot slower when running a bundled app.

I have tested for architecture linux x86_64 and with the latest version of meteor. Build by running: 
$ARCHITECTURE=os.linux.x86_64
$mkdir -p /tmp/meteor/builds && meteor build /tmp/meteor/builds --architecture ${ARCHITECTURE}

Please let me know if you have further questions on how to reproduce.

Regards

**Comment by klaussner** [comment]
@dolle39 You have a typo in your `MONGO_OPLOG_URL` environment variable (`OPLOPG` instead of `OPLOG`), so the Meteor server falls back to the (slower) poll-and-diff algorithm to compute updates for subscriptions.

**Comment by dolle39** [comment]
Oh man, how could I miss that! Thanks @klaussner !

Well it works after I change to the correct env-name.

But how come server side queries get slower without OPLOG aswell? I thought it only had to do with meteor being able to detect new changes and publish content faster?

**Comment by klaussner** [comment]
@dolle39 I think you are just measuring the wrong thing due to the way Fibers work. When `Collection.findOne` is called, the current Fiber yields, which means that its execution is paused until the query result is available. During this idle time, Node can execute the poll-and-diff triggered by the `update` call before. Therefore, you are not only measuring the execution time of the `findOne` call but also the execution time of poll-and-diff.
