### ISSUE TITLE
Latest versions of some official cordova plugins require cordova-android 6.3.0

### ISSUE THREAD

**Issue by davidecantini** [meteor/meteor#9479]
The latest versions of some official cordova plugins (e.g. the camera plugin) require cordova-android 6.3.0, i.e. cannot be used in the current stable Meteor version.

I see in the [v.next](https://github.com/meteor/meteor/blob/devel/History.md#vnext)  that "... cordova-android has been updated to version 6.3.0 ...", so, since 1.6.1 is still in beta (and, looking at 1.6 history, it may need some more time before being released), would it be possible to have a point release to make cordova-android 6.3.0 available already?

Thanks

**Comment by hwillson** [comment]
Meteor 1.6.1 will be released shortly (there have been 18 beta releases so we're almost there). Pushing out a 1.6.0.2 release with the updated `cordova-android` changes would take time away from getting the 1.6.1 release out, so we're staying focused on 1.6.1. Thanks!

**Comment by davidecantini** [comment]
That's good news (thought it'd need some more weeks).
