### ISSUE TITLE
Update to 1.6 causing IE11 transpiling issue from node_module on client (sanitize-html)

### ISSUE THREAD

**Issue by etyp** [meteor/meteor#9480]
Since upgrading to 1.6, our app has stopped working in IE11 on all versions of Windows. We've narrowed it down by commenting out most app code only to find that certain node modules cause it. The module included here as an example is [sanitize-html](https://github.com/punkave/sanitize-html), but I believe multiple modules cause this.

Meteor version: 1.6.x
Running Meteor from: macOS Sierra 10.12.6
Opening in Windows 10/8.1/7 with IE 11
Did not happen with Meteor 1.5.x
Expected: App should load with no issues
Actual: App throws tons of errors client side (see below)

```
[Excluding many similar errors for brevity]
Unable to get property 'Mongo' of undefined or null reference
'meteorInstall' is undefined
```

[Simple reproduction in Meteor app](https://github.com/etyp/meteor-ie-compile-issue). Note: this was just made by:
```
$ meteor create --fullapp meteor-ie-compile-issue
$ meteor npm i --save sanitize-html
```

Then include [sanitize-html](https://github.com/punkave/sanitize-html) on [client/main.js](https://github.com/etyp/meteor-ie-compile-issue/blob/master/client/main.js#L3). If commented out, it works again.

**Comment by etyp** [comment]
Update: it seems like the issue stems from requiring [postcss](https://github.com/postcss/postcss) in the [sanitize-html](https://github.com/punkave/sanitize-html) package.

Anybody else having issues with postcss in 1.6?

**Comment by etyp** [comment]
Another update, looks like removing [chalk](https://github.com/chalk/chalk) from [postcss](https://github.com/postcss/postcss) solves it as well. Will continue digging...

**Comment by etyp** [comment]
Updating to sanitize-html@1.1.14 resolved the issue. https://github.com/meteor/meteor/issues/9446#issuecomment-350362935

**Comment by hwillson** [comment]
This was a known `sanitize-html` issue - see https://github.com/punkave/sanitize-html/issues/187 and https://github.com/punkave/sanitize-html/issues/189. PR https://github.com/punkave/sanitize-html/pull/190 was accepted to fix this issue, so try updating to the most recent `sanitize-html` version to see if that helps. If not, please consider reporting this issue over in the https://github.com/punkave/sanitize-html repo. Closing here - thanks!
