### ISSUE TITLE
swift 4 configuration error

### ISSUE THREAD

**Issue by TwinkleTrivedi** [meteor/meteor#9481]
while(sqlite3_step(nonQuery) == SQLITE_ROW)
                {
                    let UID = String(cString: UnsafePointer<CChar>(sqlite3_column_text(nonQuery, 0)))
                    
                    let Fname = String(cString: UnsafePointer<CChar>(sqlite3_column_text(nonQuery, 1)))
                    
                    let Lname = String(cString: UnsafePointer<CChar>(sqlite3_column_text(nonQuery, 2)))
                
                    arrData.append(UID)
                    arrData.append(Fname)
                    arrData.append(Lname)

**Comment by TwinkleTrivedi** [comment]
shows error in DataService.swift file

**Comment by hwillson** [comment]
Please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor).
