### ISSUE TITLE
No feedback on OAuth redirect style login failure

### ISSUE THREAD

**Issue by elmarti** [meteor/meteor#9490]
Meteor 1.6 Ubuntu 16

If the OAuth redirect flow fails to create a new user after calling `_pageLoadLogin`, there should be some useful feedback. 
At present I am getting the error: 
```
{"isClientSafe":true,"error":145546287,"reason":"No matching login attempt found","message":"No matching login attempt found [145546287]","errorType":"Meteor.Error"}
```
at https://github.com/meteor/meteor/blob/cc472785641edc8d5d6c5da152ff00166c3d6e72/packages/accounts-base/accounts_client.js#L279
Whilst developing the following OAuth package
https://github.com/elmarti/meteor-accounts-monzo

**Comment by hwillson** [comment]
Hi @elmarti - this isn't a bug (it's working as designed) so would you mind re-opening this request over in http://github.com/meteor/meteor-feature-requests? Thanks!
