### ISSUE TITLE
Unexpected mongo exit code 0. Restarting.

### ISSUE THREAD

**Issue by danilaml** [meteor/meteor#9493]
I'm running meteor in a Docker container with Ubuntu 16.04 as it's base.

Sometimes, my docker instance will get multiple 
```
Unexpected mongo exit code 0. Restarting.
```
Warning/errors. The instance itself appears to still run after that but there is no further log output and interactions with mongo become buggy.

What could be the cause of this error and how do I fix it/diagnose it?
I don't know hot to reproduce it but it happens sometimes on one of my containers.

**Comment by hwillson** [comment]
A few questions:

1. What version of Meteor are you using?
2. Can you expand on "interactions with mongo become buggy"; how do they become buggy - is Mongo running, is it unresponsive, is it slow, etc.

**Comment by elmarti** [comment]
Also, do you have an example repo of your docker setup, or something downstream that you've cloned from?

**Comment by hwillson** [comment]
We haven't heard back regarding https://github.com/meteor/meteor/issues/9493#issuecomment-353611692, so closing for now.
