### ISSUE TITLE
Latest version of package is not used unless version is explicitly specified

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#9502]
This is something I've noticed a few times now when users clone the [Vulcan Starter repo](https://github.com/VulcanJS/Vulcan-Starter).

Vulcan uses a package-based architecture, which means it relies on Atmosphere to serve the core Vulcan code as packages. I initially left all package versions blank in the Starter app in the hopes that Meteor would automatically use the latest package version available, but that doesn't appear to always be the case. For example, some Vulcan packages will randomly use version `1.3.2` instead of the latest, `1.8.1`. 

I ended up specifying all versions to ensure the bug doesn't happen, but it still seems weird to me. Is this the intended behavior? Is there any reason why Meteor wouldn't always select the latest version? Maybe this indicates a dependency conflict somewhere?

**Comment by hwillson** [comment]
Thanks for reporting this @SachaG - this is a known issue, and is being tracked in https://github.com/meteor/meteor/issues/9284 (see https://github.com/meteor/meteor/issues/9284#issuecomment-341776394 specifically). Closing here - thanks!

**Comment by SachaG** [comment]
Thanks, good to know you guys are aware of this :)
