### ISSUE TITLE
Tracker doesn't work with expected result, it rerun times.

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9503]
the correct behavior 1

```javascript
a = Tracker.autorun(() => {
  console.log('level 1')
  Tracker.nonreactive(() => {
    console.log('level 2')
    console.log('ts is', Session.get('ts'))
    Tracker.autorun(c => {
        console.log('level 3')
        console.log('should i print times?', Session.get('ts'))
    })
  })
})

Session.set('ts', Date.now())
```

```
main.js:2 level 1
main.js:4 level 2
main.js:5 ts is undefined
main.js:7 level 3
main.js:8 should i print times? undefined
main.js:7 level 3
main.js:8 should i print times? 1514438419524
```

then i add collection reactive source to level 1

```javascript
a = Tracker.autorun(() => {
  console.log('level 1')
  console.log('add collection reactive source', Test.find().count())
  Tracker.nonreactive(() => {
    console.log('level 2')
    console.log('ts is', Session.get('ts'))
    Tracker.autorun(c => {
        console.log('level 3')
        console.log('should i print times?', Session.get('ts'))
    })
  })
})

Session.set('ts', Date.now())
```

the log looks okay, because there're 5000 docs sent, i did't wait it for ready, so it print times.

```
main.js:2 level 1
main.js:3 add collection reactive source 0
main.js:5 level 2
main.js:6 ts is undefined
main.js:8 level 3
main.js:9 should i print times? undefined
main.js:8 level 3
main.js:9 should i print times? 1514438677263
main.js:2 level 1
main.js:3 add collection reactive source 5000
main.js:5 level 2
main.js:6 ts is 1514438677263
main.js:8 level 3
main.js:9 should i print times? 1514438677263
```

### BUT WHEN U CLEAN CONSOLE AND CHANGE the level 3

```javascript
Session.set('ts', Date.now())
```

### it prints two times with same Session value, and collection.count() doesn't change too its still 5000 docs, and the level 3 doesn't relative to level1

```
Session.set('ts', Date.now())
undefined
main.js:8 level 3
main.js:9 should i print times? 1514438838492
main.js:8 level 3
main.js:9 should i print times? 1514438838492
```

why ? is this a bug or by design ?

reproduce

https://github.com/crapthings/tracker-issue-9503

**Comment by klaussner** [comment]
If `Tracker.autorun` calls are nested, inner calls are stopped when the outer call reruns. However, your level-3 autorun is inside a `Tracker.nonreactive` function, so it's not aware of the outer level-1 call. Therefore, it's not stopped automatically when the collection count changes, which means that you are creating an additional level-3 autorun in each rerun of the level-1 call. You have to stop the computation manually. For example:

```js
a = Tracker.autorun(() => {
  let computation

  console.log('level 1')
  console.log('add collection reactive source', Test.find().count())

  Tracker.nonreactive(() => {
    console.log('level 2')
    console.log('ts is', Session.get('ts'))

    computation = Tracker.autorun(c => {
      console.log('level 3')
      console.log('should i print times?', Session.get('ts'))
    })
  })

  Tracker.onInvalidate(() => {
    computation.stop()
  })
})

Session.set('ts', Date.now())
```

**Comment by crapthings** [comment]
```javascript
a = Tracker.autorun(() => {
  let computation

  console.log('level 1')
  console.log('add collection reactive source', Session.get('another'))

  Tracker.nonreactive(() => {
    console.log('level 2')
    console.log('ts is', Session.get('ts'))

    computation = Tracker.autorun(c => {
      console.log('level 3')
      console.log('should i print times?', Session.get('ts'))
    })
  })

})

Session.set('ts', Date.now())
```

@klaussner  but why this only print once ?

**Comment by klaussner** [comment]
If you call `Session.set("another", "foo")` and then `Session.set("ts", Date.now())` in the browser console, the level-3 autorun will be called twice.

**Comment by crapthings** [comment]
@klaussner  level1 count() still the same records set, nothing has change after it was shipped, no added, no removed, no updated, it shouldn't cause nested rerun right? so its kinda like NOT set Session.set('another', 'foo') to new value.

then i  set level3 value i think it shouldn't cause level 1 rerun, because level 2 is nonreactive.

**Comment by crapthings** [comment]
okay i think i know what's going on here.

i sent 5k records without wait for sub ready, level 1 rerun times during sending in batch, the count changes and "creating an additional level-3 autorun in each rerun of the level-1 call".

**Comment by crapthings** [comment]
@klaussner 

any possible to know the batch is ready (idle or not any recomputation), if i don't want to use a subscribe? something like debounce but solved in a Tracker fashion.

![image](https://user-images.githubusercontent.com/1147704/112590065-2cc21c00-8e3d-11eb-8ff3-fe507c82eaed.png)

```
Meteor.startup(function () {
  Tracker.autorun(function (computation) {
    console.log(Posts.find().fetch())
  })
})
```

```
import faker from 'faker'

Meteor.publish(null, function () {
  return Posts.find()
})

Meteor.startup(function () {
  // Posts.remove({})
  if (Posts.findOne()) return
  console.log('prepare insert')
  const posts = _.times(2000, () => ({
    text: faker.lorem.sentences(),
  }))

  console.log(Posts.rawCollection().insertMany(posts))
})
```
