### ISSUE TITLE
Don't make process Object a global in the browser

### ISSUE THREAD

**Issue by gunn** [meteor/meteor#9508]
Defining `window.process`causes trouble with other libraries that also define and/or reference it, and and can lead to difficult to track down bugs. E.g. https://github.com/Microsoft/monaco-editor/issues/681

**Comment by hwillson** [comment]
Hi @gunn - defining a client side `process` object was done to improve Meteor's compatibility with npm installed client side packages. See #6167, #6198, #6055, and #6056 for more info. If you're interested in having this changed in any way, please open a new feature request over in https://github.com/meteor/meteor-feature-requests. Thanks!
