### ISSUE TITLE
less error why

### ISSUE THREAD

**Issue by LiuSuY** [meteor/meteor#9509]
![4](https://user-images.githubusercontent.com/25116549/34459556-582164ee-ee2e-11e7-9ce2-06ebc8acc9ac.png)

**Comment by hwillson** [comment]
Hi @LiuSuY - there isn't much to go on here. Can you provide a small runnable reproduction that shows this happening? See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor). Thanks!

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/34592432-e6897bf8-f1fe-11e7-9897-87791afe257f.png)

try to build it outside project folder ?

**Comment by LiuSuY** [comment]
And then there's this operation

**Comment by crapthings** [comment]
try something like

>meteor build d:\meteor_app

**Comment by hwillson** [comment]
Hi @LiuSuY - have you tried the suggestion outlined in https://github.com/meteor/meteor/issues/9509#issuecomment-355452662? Let us know if you're still encountering this issue, and can supply additional troubleshooting details (ideally a reproduction of some kind). Closing for now - thanks!

**Comment by LiuSuY** [comment]
使用liunx一切正常
