### ISSUE TITLE
Meteor call() timeout?

### ISSUE THREAD

**Issue by pedrofg** [meteor/meteor#9511]
Is there any predefined timeout on Meteor.call() function? Suppose the server is overloaded and takes way too long to answer back what is going to happen? The HTTP has a timeout in the connection, how about the meteor? How do i handle it?

**Comment by hwillson** [comment]
Meteor's DDP implementation (which handles Method calls) uses bidirectional heartbeats between the client and server, to know when there are connection issues (like disconnects, timeouts, etc.). You don't need to explicitly set a timeout for `Meteor.call`'s as the timeout is handled automatically by DDP's [Heartbeat](https://github.com/meteor/meteor/blob/da67406b890667be25eb3461b1e74dbf07cee1f9/packages/ddp-common/heartbeat.js) implementation. The default timeout is 15 seconds and can be overridden if needed, but you shouldn't have to worry about it.

If a timeout occurs during a `Meteor.call`, an exception will be thrown that you can then handle. If you want to test this out create a dummy Method that when called starts an infinite loop. Call this Method from your client, then call a `Meteor.disconnect()` to simulate a lost connection (or timeout).

In future though, please consider posting Meteor usage questions on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Issues here are reserved for Meteor bugs. Thanks!
