### ISSUE TITLE
Meteor not working reliably on Mac Android Emulator: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by cdcv** [meteor/meteor#9513]
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
1.6
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
1.6 (it's intermittent)
- [x] The operating system you're running Meteor on.
Mac OS 10.12.6
- [x] The expected behavior.
After building a meteor app using meteor run android..., the app opens in Android Emulator and connects to meteor server reproducibly.
- [x] The actual behavior.
After building a meteor app using meteor run android..., the app opens in Android Emulator and sometimes it connects to meteor server, sometimes it doesn't.
When it doesn't it gives the error: 
GET https://localhost/sockjs/info?cb=wk974n6x_8 net::ERR_CONNECTION_REFUSED
In addition, Meteor.status() returns 'waiting' and Meteor.connect() fails, along with hot code push.
The EXACT SAME configuration of the code, settings, etc sometimes work, sometimes not.
Have tried a lot of things to correct this, including even deleting the app from the Emulator and restarting the whole Mac and therefore all of the different elements: still there is not a reproducible way to get a connection to the meteor server.

- [ ] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)
Don't have a simple reproduction.

I have spent much of the last week of my life just trying to build a Meteor app on Android and get all of the relevant components to work together correctly.  I see lots of other posts of people having similar problems.  I sure wish that MDG would focus energy on making this work better.  I'd much prefer this to more JS features in the next release.  Also, perhaps it would be worth considering a paid service that maintains a WORKING version of meteor that is capable of correctly building to web, android, ios.  This is what I spend ridiculous amounts of time each build trying to get to work.  I'd rather support MDG by paying for this than for Galaxy.

Thanks

**Comment by cdcv** [comment]
It appears that this was solved through the removal of the force-ssl package.  Have not verified this, but it appears to be working now on android-device.

**Comment by crapthings** [comment]
after check we don't have force-ssl on our app, but we have another issue on android device which is similar too this (i think) maybe on a slow device like old phone, emu etc...

can u try it on a real device

**Comment by hwillson** [comment]
Glad to hear it's working again @cdcv - have you been able to confirm if `force-ssl` was the culprit? Closing for now since it sounds like this issue was resolved.

@crapthings - I see you've opened a separate issue, so let's continue the discussion over in https://github.com/meteor/meteor/issues/9498. Thanks!
