### ISSUE TITLE
meteor not using environment variable

### ISSUE THREAD

**Issue by andrew4alive** [meteor/meteor#9520]
Hi,

i try to run meteor on window 10 cmd by create a **bat** file.

@ECHO OFF

set PORT=8001
set MONGO_URL=""

cmd /k

when i run meteor, it not using any of the set variable, it still listening at port 3000.
Error: listen EACCES 0.0.0.0:3000

i user PORT 3000 for other purpose, if i use "meteor run --port  8001 ", then every thing is running smoothly 

currently i want to use PORT 8001 and custom MONG_URL

did i do it the wrong way?

**Comment by klaussner** [comment]
The `PORT` environment variable is only for production, as [documented here](http://docs.meteor.com/environment-variables.html#PORT), so you have to use `--port` to listen on port 8001.

**Comment by andrew4alive** [comment]
can i set MONGO_URL??

**Comment by klaussner** [comment]
Yes, you can use `MONGO_URL` and `MONGO_OPLOG_URL` in development and production.
