### ISSUE TITLE
Cannot both export a variable and set it as api.export at the same time in CoffeeScript 2

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#9524]
So I am trying to do something like:

```coffee
export class Foo
   constructor: ->
```

```js
Package.onUse(function (api) {
  api.use([
    'coffeescript@2.0.3_1',
    'ecmascript',
  ]);

  api.export('Foo');

  api.addFiles('foo.coffee');
});
```

But when I look at `Package.my_package.Foo` it is undefined.

Example package where I am trying this: https://github.com/peerlibrary/meteor-middleware/tree/9fb78c857f0a8baacb737eaac99414227ab57c24

Using Meteor 1.6.0.1 and new CoffeeScript 2 on Linux.

cc @GeoffreyBooth

**Comment by benjamn** [comment]
What happens if you change `api.addFiles` to `api.mainModule`?

**Comment by mitar** [comment]
OK, this works. But I see this more as a workaround. But maybe it is really time that I update my packages to this pattern.

**Comment by GeoffreyBooth** [comment]
So it sounds like this isn’t a CoffeeScript thing? It compiles `export class Foo` to `export var Foo = class Foo {};` which I presume should work?

**Comment by mitar** [comment]
I think that because there is `var Foo` there it makes it local and overrides the global symbol used for the `api.export`. It should probably be `export Foo = class Foo {};` if `Foo` is among `api.export` symbols.

**Comment by GeoffreyBooth** [comment]
The only way to declare a global variable in CoffeeScript is to attach it to `window` or `global`, i.e. `global.Foo`. Though Meteor has a custom hack where `@Foo` at the top-level scope of a .coffee file would also make a variable global, within the context of Meteor’s custom build pipeline. So maybe you need `export class @Foo`.

**Comment by mitar** [comment]
`export class @Foo` does not, triggers a parsing error, `Unexpected token`.

Where should I open issues with this `coffescript` package? I think I found a bug.

**Comment by mitar** [comment]
I mean, even the most basic export and import and subclass does not work. :-)

https://github.com/mitar/meteor-coffeescript-issue

**Comment by GeoffreyBooth** [comment]
The `coffeescript` package is part of the `meteor` repo, so this is the place.

It’s also a bit behind the latest CoffeeScript (2.1.1). Do you mind manually replacing the `coffeescript` folder in your `node_modules` of your Meteor app with the latest version, and seeing if that makes a difference?

**Comment by mitar** [comment]
Replacing it directly doesn't really work because it recreated, but I made it. It does not fix it.

**Comment by mitar** [comment]
I will open a new issue.

**Comment by mitar** [comment]
Done: #9528
