### ISSUE TITLE
1.6 on Windows won't even run example or blank apps

### ISSUE THREAD

**Issue by mdingena** [meteor/meteor#9525]
- [ ] The version of Meteor showing the problem.
I've tried `1.6` through `chocolatey`, then downgraded to `1.5.4.1` and `1.4.4.3`. All have this problem.

- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
It used to be `1.4.4.3`, but ever since upgrading to `1.6` I can't get rid of the problem.

- [ ] The operating system you're running Meteor on.
Windows 7 Ultimate 64-bit

- [ ] The expected behavior.
Expected to see Simple Todos application, or default Meteor Hello World for blank project.

- [ ] The actual behavior.

```
PS D:\GitHub> meteor create test
Created a new Meteor app in 'test'.

To run your new app:
  cd test
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

PS D:\GitHub> cd test
PS D:\GitHub\test> meteor
[[[[[ ~\D\GitHub\test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.
```

![image](https://user-images.githubusercontent.com/13388489/34772401-1cab0366-f608-11e7-832b-6f1391fedac2.png)

**Comment by hwillson** [comment]
@mdingena Please post the output from `meteor node -p "module.paths"`.

**Comment by mdingena** [comment]
```
PS D:\GitHub> cd .\test
PS D:\GitHub\test> meteor node -p "module.paths"
[ 'D:\\GitHub\\test\\node_modules',
  'D:\\GitHub\\node_modules',
  'D:\\node_modules' ]
```

**Comment by mdingena** [comment]
Things I tried to get Meteor to work, without success:

- Uninstall Mongo (I had a standalone installation).
- Uninstall Node 8.9.1 (I had a standalone installation).
- Uninstall and reinstall Meteor 1.6 through `choco install meteor`.

**Comment by hwillson** [comment]
@mdingena Can you try temporarily renaming your `D:\\GitHub\\node_modules` and `D:\\node_modules` directories to something else (e.g. `D:\\GitHub\\node_modules.bak`)? That should help rule out if something is interfering higher up in your Node path.

**Comment by mdingena** [comment]
@hwillson that's the thing, there are no `D:\\GitHub\\node_modules` or `D:\\node_modules` directories. There never were. Before 1.6, I knew where Meteor was installed. With `choco install meteor` I'm not exactly sure what happens behind the scenes.

I thought of something that might be important to know, and are possibly a cause of my problem (but I don't know how to verify this). I use Windows juctions to put some a couple of Windows folders on my `D:` partition, while Windows still thinks they are on `C:`.

![image](https://user-images.githubusercontent.com/13388489/34891415-cb93e612-f7d5-11e7-99c1-695a9543896c.png)

Either way, I don't have these `node_modules` directories anywhere except inside project directories.

**Comment by hwillson** [comment]
Thanks for the update @mdingena - to see if junctions are the cause of this issue, try creating and running your Meteor app on the same physical drive you installed Meteor on. So if you installed it on your `C` drive, try creating/running a Meteor app on that drive.

**Comment by mdingena** [comment]
@hwillson It occurred to me I could do that, indeed. It didn't work, however. I got the same behavior: the console indicates that Meteor has started without problems, but the browser reports numerous errors, all related to missing `meteorInstall` or properties of other undefined objects.

Also, like with projects on `D:`, after creating a project on `C:`, there were no `node_modules` directories to be found above the project directory. The output of `meteor node -p "module.paths"` was similar to calling it from a project in `D:`.

**Comment by mdingena** [comment]
This is blocking any kind of usage of Meteor for me. I just can't use it, not even after a clean reinstall. Why isn't it working?

**Comment by abernix** [comment]
The problem could very well be related to the junctions you have in place which relocate what are arguably critical system paths, onto another drive.  A lot has changed since Meteor 1.4.4.3, but have you tried creating a project using the `--release 1.4.4.3` flag to see if it still exhibits the same behavior?

    meteor create --release 1.4.4.3 test-1443

Perhaps you have another workstation you could try which has `Program Files`, `Users`, etc. located on the same drive as the operating system (and preferably, has everything on `C:` which is the only configuration we test)?

**Comment by mdingena** [comment]
@abernix I have tried creating blank app with the release flag, as well as downgrading my global meteor installation followed by creating a blank app. Both have the same behavior.

I need to stress that Meteor seems to be working in the command line. Unlike other issues I've read here, the console just shows the normal messages you expect when a project has launched successfully. It is then only on the localhost page itself where the errors occur. I'm not exactly sure what this is telling us. `choco` seems to install Meteor just fine, and the `meteor` commands work as expected.

I don't have another workstation on hand unfortunately, but using a different machine introduces so many other variables, any one of which could "solve" the problem. I'm sure a fresh Windows install won't have these problems. But that's not something I can do right now.

I order to continue troubleshooting, what else can I do? Why can't the browser find those modules? Where the heck is Meteor even installed? With the Windows installer, I could at least point the installation somewhere. Now it just seems to magically exist in my system. `choco` isn't very transparent about that during the installation process.

One thing I'm trying to do now is use the old Meteor installer (after `choco uninstall meteor`). I've got a really old one from 2015, but I think those installers try to download the latest Meteor anyways. After that, I'll see if I need to manually upgrade it to 1.6, and see if that solves the problem.

**Comment by mdingena** [comment]
Sorry. No luck there. Still a clean command line, and a browser console filled with errors.

**Comment by mdingena** [comment]
Nearly all browser errors complain about not being able to read the `meteorInstall` property of `undefined`. Looking at some of those errors in more detail, it becomes clear that `Package.modules` is not defined.

![image](https://user-images.githubusercontent.com/13388489/35220768-da020ea0-ff77-11e7-9436-ee01bbe7d4aa.png)

**Comment by mdingena** [comment]
Any other ideas I can try? Perhaps you could tell me the ultimate and absolute way of removing Meteor and all of its traces from my system completely? I get the feeling that I'm stuck with the problem after reinstalling Meteor because I didn't properly clean it up.

**Comment by hwillson** [comment]
The ultimate way to remove Meteor on Windows is `choco uninstall meteor`, followed by making sure your `%LocalAppData%\.meteor` directory was completely removed.

**Comment by hwillson** [comment]
Closing for now due to inactivity - please post back if you're still encountering issues. Thanks!

**Comment by trusktr** [comment]
Possibly related: https://github.com/meteor/meteor/issues/11668
