### ISSUE TITLE
CoffeeScript: Cannot extend a class imported from a package

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#9528]
Reproduction: https://github.com/mitar/meteor-coffeescript-issue

Error:

```
W20180110-12:46:56.224(-8)? (STDERR) TypeError: Class constructor Foo cannot be invoked without 'new'
W20180110-12:46:56.224(-8)? (STDERR)     at new Bar (tests.coffee:5:5)
W20180110-12:46:56.225(-8)? (STDERR)     at tests.coffee (packages/local-test_meteor-coffeescript-issue/tests.coffee:5:1)
W20180110-12:46:56.225(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180110-12:46:56.225(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
```

Meteor 1.6.0.1.

cc @GeoffreyBooth

**Comment by benjamn** [comment]
As you may already know, this is a general problem that comes from mixing native and compiled `ECMAScript` classes. Specifically, a *native* superclass constructor must be invoked using `super` from the child class constructor, whereas a *compiled* superclass constructor must be called as a function against `this` (which should be `instaceof Foo`). If `coffeescript` generates native `class` syntax for `Foo`, then it should also generate native `super` syntax for `Bar`.

After digging into @mitar's reproduction, I can confirm that `coffeescript-compiler` is compiling `Foo` and `Bar` consistently; however, there's a bug in `CachedCoffeeScriptCompiler#getCacheKey` that allows code compiled for `web.browser` to be accidentally used on the server. Fortunately, we can fix that with a new patch version of the `coffeescript-*` packages. I'll submit a PR for that momentarily.

**Comment by mitar** [comment]
Awesome! Thanks so much!

**Comment by GeoffreyBooth** [comment]
Thanks, good catch @benjamn! For the record, it seems like the issue you're referring to is this one: https://github.com/jashkenas/coffeescript/issues/4233, which was resolved by compiling to the `class` keyword in CoffeeScript 2.
