### ISSUE TITLE
Webview - Android - Chromium - awareness for Mojo BudgetService.

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#9529]
Please refer to this link for awareness as 1.6.1 is using the same Cordova versions: http://mail-archives.apache.org/mod_mbox/cordova-issues/201712.mbox/%3CJIRA.13125833.1513674684000.515184.1513895100484@Atlassian.JIRA%3E

Server log from run android-device with cordova-plugin-meteor-webapp@1.4.1 and 1.4.2: 

`I20180111-02:45:44.497(4)? E/chromium(14605): [ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::BudgetService exposed by: content_browser

I20180111-02:45:44.502(4)? E/chromium(14605): [ERROR:BudgetService.cpp(167)] Unable to connect to the Mojo BudgetService.
`
I am running with Meteor 1.6.0.1.

No issue running the apps however, I had some issues due to a cordova Push package and I suspected "Mojo BudgetService" for 5-6 hours until I realized the Push was actually my problem. So this topic is not breaking Android, it just display the message in console.

**Comment by crapthings** [comment]
i've seen similar issue before. will this cause https://github.com/meteor/meteor/issues/9498

**Comment by hwillson** [comment]
As mentioned in the `cordova-issues` mailing list link you provided (and the [previous message in the thread](http://mail-archives.apache.org/mod_mbox/cordova-issues/201712.mbox/%3cJIRA.13125833.1513674684000.491855.1513683000075@Atlassian.JIRA%3e)), this is not a Meteor or Cordova issue. This issue should be reported to the [Chromium](http://www.chromium.org/for-testers/bug-reporting-guidelines) project itself. 

Given that this issue doesn't seem to impact Meteor based Cordova apps (the error message is just logged), I'll close this for now. If this becomes more of an issue, please post back and let us know.  Thanks!
