### ISSUE TITLE
Missing bcrypt field in services.password crashes server

### ISSUE THREAD

**Issue by juho** [meteor/meteor#9536]
When logging in with `accounts-password`, if the `bcrypt` field is missing in the user doc's `services.password`, the entire server crashes:

```
TypeError: cb is not a function at /Users/jh/dev/app/node_modules/bcrypt/bcrypt.js:150:13 at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

User doc:
```js
{
  _id: "n76XD4qFqBcw2QLpM",
  emails: [
    {
      address: "example@example.com",
      verified: false
    }
  ],
  profile: {
    firstname: "Admin",
    lastname: "Admin"
  },
  services: {
    password: {}
  }
}
```

**Comment by hwillson** [comment]
Hi @juho - can you supply a reproduction that shows this happening? A missing bcrypt field is handled by `accounts-password` [here](https://github.com/meteor/meteor/blob/9236202115c803c1c362e1b692214b2fe317d8cd/packages/accounts-password/password_server.js#L301-L304), and I've confirmed this is working properly.

**Comment by juho** [comment]
Ah ha, I think that might be newer than what we have. Sorry I just dumped this in here while crunching.
