### ISSUE TITLE
`meteor run android-device` appears to break with the latest version of android studio

### ISSUE THREAD

**Issue by cwohlman** [meteor/meteor#9538]
I'm currently running meteor 1.5.1 and just tried adding android as a supported platform to my app, however I'm getting an error running the app on android. A full description of the error is below, but I think the underlying issue is the latest version of the android sdk is incompatible with the version of cordova in meteor 1.5.

I think that at a minimum the guide should mention the maximum compatible version of the android sdk for meteor 1.5, also I think that the meteor cli should provide a hint about this issue if possible.

Note: I ran into issues updating my project to meteor 1.6 and don't know if the issue is fixed in that version.

Here's the error I was getting:

```
npm run start-android

> xxx@ start-android XXX
> meteor run --settings settings.json android-device

                                              
Your system does not yet seem to fulfill all requirements to build apps for Android.
                                              
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
                                              
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: Android SDK not found. Make sure that it is installed. If it is not at the default
  location, set the ANDROID_HOME environment variable.
✗ Gradle: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
  Looked here: /Users/joshuaohlman/Library/Android/sdk/tools/templates/gradle/wrapper
                     
```

This [line](https://github.com/apache/cordova-android/blob/5.0.x/bin/lib/check_reqs.js#L249) is the cause of the problem as it relies on the now depricated android list targets command.

```
android list targets --compact
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "list targets --compact"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```

**Comment by cwohlman** [comment]
I believe a workaround for this is to downgrade android sdk versions. I'll update this comment with the correct version once I succeed at that.

**Comment by cwohlman** [comment]
This issue seems related, though it's closed & I'm definitely still running into the current issue: https://github.com/meteor/meteor/issues/8464

**Comment by benjamn** [comment]
If you update to Meteor 1.6.1 (`meteor update --release 1.6.1-rc.6`), I believe the right Android API version is 26 (though 27 is now available, too).

**Comment by abernix** [comment]
Word of warning to anyone trying Google Android API level 27:  API 27 will be problematic until (recently submitted & merged) https://github.com/dvoiss/android-versions/pull/11 has been published and `android-cordova` updates to use that new version.  Else, when attempting to use API 27, it's likely developers will meet with: [[CB-13571]: 'semver' property not found block the emulator](https://issues.apache.org/jira/browse/CB-13571), which will at least result in a more graceful error message thanks to https://github.com/apache/cordova-android/pull/422.

We currently maintain [our own version of `cordova-android`](https://github.com/meteor/cordova-android), so it should be easier to bump.  Though there isn't a `package-lock.json` for our `cordova-android` and it's installed automatically when using `meteor add-platform android`.  Therefore, I believe that upon re-adding the platform, the indirect dependency should just pickup the changes when the new `android-versions` is published.  Of course, we can help this process by releasing a new version of the tool as well: Something to consider for 1.6.2.

**Comment by abernix** [comment]
We have updated this and it's possible to use Android Studio 27 now.  Thanks!

Ref: #10416
