### ISSUE TITLE
meteor has no --version option

### ISSUE THREAD

**Issue by nhhockeyplayer** [meteor/meteor#9544]
platform meteor-1.6.0.1

meteor has no --version option

we are unable to know quickly what version we are using from command prompt

**Comment by klaussner** [comment]
It does have a `--version` option. 🙂  Run `meteor --version` in any directory to get the current version or in a Meteor project directory to get the version used in the project.

**Comment by benjamn** [comment]
Thanks @klaussner. This is likely a spammer/troll, jfyi.
