### ISSUE TITLE
archetype project/app generator incomplete

### ISSUE THREAD

**Issue by nhhockeyplayer** [meteor/meteor#9545]
platform meteor-1.6.0.1
windows 7
node v9.3.0
npm 5.6.0

when generating a app/project (using meteor archetype)

meteor create myapp

the package.json has no build commands centric to meteor
yet meteor wraps npm and angular-cli ?
we are left guessing what will work with meteor

these newly generated apps should be thoroughly cultivated with all sorts of npm build commands that meteor will accept

apps currently not runnable as of yet with this user

**Comment by klaussner** [comment]
Can you be more specific about which type of build command you expect in `package.json`? Meteor apps are typically started (during development) by simply running `meteor` or `npm start` in the project directory. If you want to build a production bundle, use [`meteor build [...]`](http://docs.meteor.com/commandline.html#meteorbuild).

**Comment by hwillson** [comment]
I agree with @klaussner, and in any case this isn't a bug. Please submit Meteor feature requests over in http://github.com/meteor/meteor-feature-requests. Issues here are reserved for bugs with the Meteor platform.
