### ISSUE TITLE
new projects should default to typescript instead of javascript

### ISSUE THREAD

**Issue by nhhockeyplayer** [meteor/meteor#9547]
platform meteor-1.6.0.1
windows 7
node v9.3.0
npm 5.6.0

meteor create myapp

this command creates JS files 

it should characterize typescript *.ts modules to be in sync with its next gen platform theology

**Comment by hwillson** [comment]
Please open feature requests over in http://github.com/meteor/meteor-feature-requests. Issues here are reserved for Meteor bugs.
