### ISSUE TITLE
1.6.1-rc6 Cordova plugin 'cordova-plugin-facebook4' - rebuild cordova issue

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#9548]
1.6.0.1 Everything was fine. Update done last night to the latest version in repo.

Running on OSX High Sierra.

I use NPM "bas-meteor-facebook-login": "^1.1.0"

In 1.6.1 rc6 I tried cordova plugins:

1. `cordova-plugin-facebook4@https://github.com/Basgrani-Org/cordova-plugin-facebook4.git#ee8aab56ee6c1f822dcab9ede1db1944100935b4`

2. `cordova-plugin-facebook4@1.9.1`
Same behavior as follows. Start from a meteor reset. build ios-device. Stop. build ios-device again.

This was fine in 1.6.0.1 with the first plugin.

` While removing plugins                     

cordova-plugin-actionsheet,cordova-plugin-android-fingerprint-auth,cordova-plugin-device,cordova-plugin-dialogs,cordova-plugin-facebook4,cordova-plugin-geolocation,cordova-plugin-googleplus,cordova-plugin-inappbrowser,cordova-plugin-meteor-webapp,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-touch-id,cordova-plugin-vibration,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,cordova-plugin-x-socialsharing,cordova.plugins.diagnostic,es6-promise-plugin,ionic-plugin-keyboard,uk.co.workingedge.phonegap.plugin.launchnavigator

   from Cordova project:

   Cordova error: **Cannot find plugin.xml for plugin "cordova-plugin-facebook4". Please try adding it again.**
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option
   to help diagnose the issue.)`

I can only build cordova if I do meteor reset or manually delete 'cordova-build' folder

OBSERVATIONS: after a meteor reset and successfully run an ios-build I can see the facebook plugin under cordova-build/plugins. I stop meteor, I can still see it. I run ios-device again, the cordova-plugin-facebook4 folder disappears then I get the error in the server console.

![screen shot 2018-01-17 at 22 57 36](https://user-images.githubusercontent.com/26188915/35061188-e0fc2ea8-fbd9-11e7-97ae-8af22d8f8c72.png)

**Comment by paulincai** [comment]
I started a brand new project from 0. The same issue occurs.
cordova-plugin-facebook4 together with any other plugin/s - results in the above error.
cordova-plugin-facebook4 alone - no issue
any other plugins together, without cordova-plugin-facebook4 - no issues

**Comment by benjamn** [comment]
Having spent a few hours attempting to work around this problem in Meteor's Cordova code, I have to say: adding and removing plugins is a mess on the `cordova-lib` / `plugman` side. Specifically, adding plugins often fails if the plugin was ever partially added (or incompletely removed) before, and removing plugins fails if any parts of the plugin are missing. In other words, these operations are nowhere near as forceful/idempotent/forgiving as they should be, and we will probably need to fork the `cordova-lib` npm package to fix this. Unfortunately, that will have to wait for Meteor 1.6.2. In the meantime, removing `.meteor/local/cordova-build` after adding or removing Cordova plugins seems to be the most reliable workaround for these problems.

**Comment by paulincai** [comment]
@benjamn I, personally, have absolutely no problem with it but this prevents a user from customizing some things on Android.

If you want some (custom) icons for notifications or custom sound, you need to add into the Android/res folder which you cannot do since the folder doesn't exist at the time you start the build. If you add it during a run android-device you lose it indeed when you have to do the build.

I never tried so far but I will try to take the Android project into Android Studio and do it from there.

**Comment by cunneen** [comment]
We also have this problem with 1.6.1. `meteor reset` fixes it (and for production releases we've found it's needed anyway to clear invalidly cached values).

@paulincai : can you put the resources under a `cordova-build-override/platforms/android` folder under your meteor project?

**Comment by wojtkowiak** [comment]
This is very problematic as the cordova build can be very unstable and bad things can happen as the CI can sometime push a production release that is not working (due to some cordova plugins not being installed). 

Here is an example from the logs, first the `whitelist` plugin is removed, then added but actually the remove finishes after the add resulting in a missing plugin.

First it calls uninstall as cordova plugins are cleared on every build:
```
> meteor run android-device --verbose  --mobile-server=`ifconfig | grep 'inet ' | grep '\.5\.' | awk '{print $2}'`:3000

%% Calling plugman.uninstall on plugin "cordova-plugin-whitelist" for platform "android"
```
Then adds again:
```
Adding plugin cordova-plugin-whitelist@1.3.2 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-whitelist@1.3.2"
%% Calling plugman.install on plugin "/Users/zhadzlik/Projects/mextal.viedome/viedome/.meteor/local/cordova-build/plugins/cordova-plugin-whitelist" for platform "android
%% Plugin "cordova-plugin-whitelist" already installed on android.
%% Calling plugman.install on plugin "/Users/zhadzlik/Projects/mextal.viedome/viedome/.meteor/local/cordova-build/plugins/cordova-plugin-whitelist" for platform "ios
%% Plugin "cordova-plugin-whitelist" already installed on ios.
%% No scripts found for hook "after_plugin_add".
```
but after a second the previously called uninstall finishes:
```
%% Finding scripts for "before_plugin_uninstall" hook from plugin cordova-plugin-whitelist on android platform only.
%% No scripts found for hook "before_plugin_uninstall".
%% Uninstalling cordova-plugin-whitelist from android
%% Beginning processing of action stack for android project...
%% Calling plugman.uninstall on plugin "cordova-plugin-whitelist" for platform "ios"
%% Removing "cordova-plugin-whitelist"
%% Deleted "cordova-plugin-whitelist"
```
The result is that the plugin is missing.

@benjamn please take a look at:
https://github.com/darqs/meteor/commit/df9ed5900e6a49f9e790447f6bdbe188094228d4

This is not fix for the cause (as this would require cordova integration rewrite) but at least alleviates the core problems as it will either actually install all plugins or fail the build - which for now should be a big improvement in this situation.

I can not promise anything but we will take a look if we would be able to rewrite some of cordova integration logic later.

In the meantime it would be very appreciated if we could include this now. Let me know what you all think.

**Comment by abernix** [comment]
@wojtkowiak I know there's a lot of updates to Cordova in Meteor 1.8.1 — can you confirm whether or not this is still problematic?

https://github.com/meteor/meteor/pull/10416 https://github.com/meteor/meteor/pull/10339
