### ISSUE TITLE
1.6.1-rc6 Cordova  cordova-plugin-statusbar and cordova-plugin-splashscreen console messages

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#9549]
When I run ios-device with the Meteor default cordova setup (no extra plugins added), this message is displayed in the server console:

`WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a minimum
         version of 2.3.0 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.`

`
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have a minimum
         version of 4.1.0 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.`

I personally add the updated versions from their respective repos.

**Comment by benjamn** [comment]
I've seen these warnings too, and haven't been able to figure out where they might be coming from. The only versions you'll find in the Meteor codebase for those packages are 2.3.0 and 4.1.0, respectively.

**Comment by paulincai** [comment]
https://github.com/meteor/meteor/pull/8913#issuecomment-325428788  :)

**Comment by skirunman** [comment]
My guess is we are seeing these messages as we only updated to `cordova-plugin-statusbar@2.3.0` and `cordova-plugin-splashscreen@4.1.0` and not all the plugins that were released at the same time https://cordova.apache.org/news/2017/11/10/plugins-release.html

So likely some of our older pinned plugin versions have a dependency on the older versions. (just my educated guess)

**Comment by skirunman** [comment]
I think we should check if this is solved with https://github.com/meteor/meteor/pull/10810

**Comment by skirunman** [comment]
@filipenevola?

**Comment by filipenevola** [comment]
I don't see these warning after updating all the plugins in 1.10. If you still see these please reopen.

You can try 1.10 updating to latest beta. Right now it is beta.4, meteor update - - release 1.10-beta.4
