### ISSUE TITLE
running debugging server increases cpu usage dramatically

### ISSUE THREAD

**Issue by modev** [meteor/meteor#9555]
I am pretty new to Meteor, but I am pretty sure this is not a normal behavior. When running the `meteor` command in order to start the development server the CPU usage increases dramatically. When the server is running, my system and my code editor (Visual Studio Code) isn't usable anymore. The CPU usage peaks at 100% and sometimes even causes my system to crash. I have a few packages installed as listed below (but these packages don't change anything about this behavior. I tried it with a blank project as well).
- react-meteor-data
- fourseven:scss
- react
- react-dom
My computer is running Windows 10 x64 on an AMD FX-8320. 
Is there any way I can fix this issue?

**Comment by benjamn** [comment]
How exactly are you enabling the debugger when running the `meteor` command?

**Comment by modev** [comment]
Sorry, my description was a little bit inaccurate. The local development server which is started by default when running the `meteor` command is causing the issues.

**Comment by benjamn** [comment]
Ah, I see. In the past, some Windows developers have discovered that anti-virus software can be a bit too aggressive about scanning temporary files created by the Meteor build process: https://github.com/meteor/meteor/issues/9175, https://github.com/meteor/meteor/issues/8803

To get a sense for where the `meteor.bat` command is spending its time, you can also run Meteor with profiling enabled by setting the environment variable `METEOR_PROFILE` to a number (I usually use `20`, which means you'll only see things that took longer than 20 milliseconds, though you can go higher or lower). In Powershell, I believe the way to do this is
```sh
$env.METEOR_PROFILE = 20
meteor run
```
This will display a lot of information, so feel free to paste the output here if it doesn't make sense. If you see anything particularly egregious, that could help identify the source of the problem.

If `METEOR_PROFILE` doesn't provide any clues, you can also run `meteor --inspect-brk` and connect to the process via Chrome DevTools, which has some fancy profiling tools like a timeline, flame chart, call graph, etc.

**Comment by modev** [comment]
I've already tried it with Antivirus disabled. Profiling with `meteor run` didn't provide any clues. Only the MongoDB startup took some time which is normal I guess. Chrome profiling didn't help as well. I'll try to reinstall Meteor, maybe this will help.

**Comment by hwillson** [comment]
Hi @modev - is this problem still happening? Any luck with re-installing Meteor? If this is still happening, any chance you could provide a small runnable reproduction?

**Comment by modev** [comment]
Hi, sorry, I completely forgot about this issue. Yes, a complete reinstallation of meteor solved it. I really don't know why this was happening

**Comment by hwillson** [comment]
Great to hear it's working - thanks for the update!
