### ISSUE TITLE
[1.5.1][BUG] Packages are not pinned down correctly

### ISSUE THREAD

**Issue by sylido** [meteor/meteor#9563]
Running Meteor on a Ubuntu VM 14.04 and 16.04.

Was expecting that doing `meteor update --packages-only` would update all the packages to their latest version that is compatible with the specified Meteor release version.

Was expecting that installing all packages anew after cloning a repository with a Meteor release specified as 1.5.1 would install the latest packages compatible with that version of Meteor.

Result from both of these actions is that newer versions of the packages are installed, but the actual build fails to complete or completes but the app never starts with no Errors or Warnings, just doesn't run.

List of packages as listed in package.json

> ecmascript@0.8.1              # Enable ECMAScript2015+ syntax in app code
> es5-shim@4.6.15               # ECMAScript 5 compatibility for older browsers.
> meteor-base@1.1.0           # Packages every Meteor app needs to have
> mobile-experience@1.0.4  # Packages for a great mobile UX
> mongo@1.1.19                  # The database Meteor supports right now
> session@1.1.7                    # Client-side reactive dictionary for your app
> tracker@1.1.3                     # Meteor's client-side reactive programming library
> 
> perak:mysql-shadow
> phuocd:slickgrid
> accounts-base@1.3.1
> http@1.2.12
> email@1.2.3
> ejson@1.0.13
> random@1.0.10
> iron:router
> matb33:collection-hooks
> copleykj:livestamp
> less@2.7.9
> reactive-dict@1.1.9
> accounts-password@1.4.0
> rajit:bootstrap3-datepicker
> mizzao:bootboxjs
> zimme:active-route
> momentjs:moment
> mrt:nprogress
> numeral:numeral
> underscorestring:underscore.string
> rl6:meteor-google-charts
> rubaxa:sortable
> aldeed:autoform
> aldeed:collection2
> comerc:autoform-selectize
> jeremy:selectize
> chhib:selectize-bootstrap-3
> mikowals:batch-insert
> alanning:roles
> sergeyt:typeahead
> jaywon:meteor-node-uuid
> accolver:twilio-meteor
> check@1.2.5
> gadicohen:headers
> reywood:publish-composite
> gentlenode:spiderable-ssl
> nourharidy:ssl
> stevezhu:lodash
> aldeed:template-extension
> abpetkov:switchery
> mrt:chosen-package
> postrednik:meteor-rangeslider
> meteorhacks:async
> bshamblen:morrisjs
> tkornblit:icheck
> reactive-var@1.0.11
> mpowaga:autoform-summernote
> peerlibrary:aws-sdk
> izzilab:shelljs
> peerlibrary:fs
> okgrow:router-autoscroll
> mdg:validation-error
> meteorhacks:fast-render
> djedi:sanitize-html
> rl6:amcharts
> standard-minifier-css@1.3.4
> standard-minifier-js@2.1.1
> rollypolly:sparkline
> twbs:bootstrap
> stylus@2.513.9
> useraccounts:iron-routing
> useraccounts:core
> doctorpangloss:method-hooks
> useraccounts:bootstrap
> aldeed:autoform-bs-datepicker
> yogiben:autoform-file
> bshamblen:jquery-querybuilder
> veto44:bootstrap-select
> mvitanov:query-builder-mongo
> zuuk:stale-session
> risul:bootstrap-colorpicker
> bigdsk:inputmask
> lookback:emails
> dalgard:jade
> shell-server@0.2.4
> cfs:standard-packages
> cfs:gridfs
> hitchcott:method-hooks
> meteorhacks:aggregate
> peerlibrary:blaze-components
> ostrio:cookies
> markdown@1.0.12
> verron:autosize
> dynamic-import@0.1.1
> fortawesome:fontawesome
> msavin:mongol
> msavin:jetsetter
> chfritz:filedrop
> ostrio:files
> meteorhacks:kadira

Steps to recreate would be to make the simplest project using --release 1.5.1 and then add the above listed packages to your .meteor/package file, then try to start the project with `meteor`.

**Comment by hwillson** [comment]
Thanks for reporting this @sylido. This is a known issue, but won't be worked on further. For the full backstory, see https://github.com/meteor/meteor/issues/9543#issuecomment-359415227 (which you probably already have since you're part of that thread). Thanks!

**Comment by sylido** [comment]
Hey @hwillson thanks for the reply, I do understand the priorities of the team lie in the future, not the past, so I guess it's on everybody to upgrade on time. This has happened once before with the 0.x versions where the version of meteor wasn't being respected and newest meteor-tool was getting downloaded/installed - which in turn broke all dependencies.

Having a place like the .meteor/packages or ./meteor/versions files where you can completely manually override package versions would be very helpful to avoid meteor's code trying to figure out which package is compatible with what. I wouldn't think people wouldn't mind having at least the option to try and salvage some stuff before they upgrade. Thanks !
