### ISSUE TITLE
https://install.meteor.com meteor version is still 1.6.0.1

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#9578]
Could you change it to latest release 1.6.1?

**Comment by hwillson** [comment]
1.6.1 hasn't been officially "recommended" yet (it should be very soon!). When it is, the version will be updated on https://install.meteor.com. When in doubt, run `meteor show METEOR` to see which versions have been officially recommended.

**Comment by abernix** [comment]
Meteor 1.6.1 is now officially marked as "recommended", meaning it will be the default for `curl https://install.meteor.com/ | sh` and `choco install meteor` (for Windows).  For developers with Meteor already installed, there's no need to re-install.  Simply running `meteor update` in an existing project directory or `meteor create`-ing a new project will use 1.6.1.

Here's [the blog post](https://blog.meteor.com/announcing-meteor-1-6-1-50aad71da4e6) by @benjamn with all the beautiful details!
