### ISSUE TITLE
Dynamic import causes errors in Mongo package.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#9580]
## This bug report should include:
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem. **1.6.0.1**
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [x] The operating system you're running Meteor on. **Chrome OS (Ubuntu Xenial via Crouton)**
- [x] The expected behavior. **No error**
- [x] The actual behavior. **Causes an error!**
- [x] A **simple** reproduction! **See the next comment for reproduction.**

## Problem:

Basically, static imports yields no error, but importing the same things with dynamic `import()`s causes an error in the imported package.

The error happens when I have a single `main.js` entry point like the following which handles bootstrapping both client and server in the same file:

```js
import meteorStartup from '@awaitbox/meteor-startup'

// entry point
~async function main() {

    if (Meteor.isClient) {

        const [
            {default: Vue},
            {routerFactory},
            {default: MainLayout},
        ] = await Promise.all([
            import('vue'),
            import('/imports/startup/client/routes'),
            import('/imports/ui/layouts/main-layout.vue'),
            import('/imports/startup/client/setup-vue'),
            meteorStartup(),
        ])

        // bootstrap the Vue app
        new Vue({
            el: '#ui-root',
            router: routerFactory.create(),
            ...MainLayout
        })

        console.log('client side started')

    }
    else if (Meteor.isServer) {

        const [{createFixtures}] = await Promise.all([
            import('/imports/startup/server/fixtures'),
            import('/imports/startup/server/register-api'),
            meteorStartup(),
        ])

        createFixtures()

        console.log('server side started')

    }

}()
```

in this case, the `import('/imports/startup/server/register-api'),` import (which does not export anything, only starts up a `new Mongo.Collection`) causes an error in the `meteor/mongo` package:

```
W20180126-01:43:52.065(-8)? (STDERR) (node:733) TypeError: Cannot read property 'open' of undefined
W20180126-01:43:52.150(-8)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:105:38)
W20180126-01:43:52.150(-8)? (STDERR)     at messages.js (imports/api/messages/messages.js:5:25)
W20180126-01:43:52.151(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180126-01:43:52.152(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180126-01:43:52.152(-8)? (STDERR)     at methods.js (imports/api/messages/methods.js:1:171)
W20180126-01:43:52.152(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180126-01:43:52.153(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180126-01:43:52.153(-8)? (STDERR)     at register-api.js (imports/startup/server/register-api.js:1:179)
W20180126-01:43:52.153(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180126-01:43:52.154(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:238:16)
W20180126-01:43:52.154(-8)? (STDERR)  => awaited here:
W20180126-01:43:52.155(-8)? (STDERR)     at Function.Promise.await (/home/trusktr/.meteor/packages/promise/.0.10.0.5xcm95.d4eij++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20180126-01:43:52.155(-8)? (STDERR)     at Promise.asyncApply (main.js:32:15)
W20180126-01:43:52.155(-8)? (STDERR)     at /home/trusktr/.meteor/packages/promise/.0.10.0.5xcm95.d4eij++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180126-01:43:52.156(-8)? (STDERR) (node:733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
W20180126-01:43:52.157(-8)? (STDERR)     at emitWarning (internal/process/promises.js:78:15)
W20180126-01:43:52.157(-8)? (STDERR)     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
W20180126-01:43:52.158(-8)? (STDERR)     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
W20180126-01:43:52.158(-8)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:131:7)
W20180126-01:43:52.158(-8)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## The odd thing is,

if I split this single main.js file into two files, `client/main.js` and `server/main.js` which use only static imports and not dynamic imports, then everything works perfectly! For example, the files look like this:

```js
// server/main.js
import meteorStartup from '@awaitbox/meteor-startup'
import {createFixtures} from '/imports/startup/server/fixtures'
import '/imports/startup/server/register-api'

// server entry point
~async function main() {

    await meteorStartup()

    createFixtures()

    console.log('server side started')

}()
```

```js
// client/main.js
import meteorStartup from '@awaitbox/meteor-startup'
import Vue from 'vue'
import {routerFactory} from '/imports/startup/client/routes'
import MainLayout from '/imports/ui/layouts/main-layout.vue'
import '/imports/startup/client/setup-vue'

// client entry point
~async function main() {

    await meteorStartup()

    // bootstrap the Vue app
    new Vue({
        el: '#ui-root',
        router: routerFactory.create(),
        ...MainLayout
    })

    console.log('client side started')

}()
```

As you can see, the result should be practically the same. At least, it's not obvious why the deferred loading of the modules would cause an error and the immediate version not. In fact, it seems like making a `new Mongo.Collection` _later_ would avoid causing an error due to APIs not being ready.

From the above stack trace, messages.js is _very_ simple, it's just:

```js
import { Mongo } from 'meteor/mongo';
export const Messages = new Mongo.Collection('messages'); // this causes the error according to the stack
```

I'll post a reproduction....

**Comment by trusktr** [comment]
Here's a reproduction: https://github.com/trusktr/trusktr.io/tree/meteor-issue-9580

Clone it, then

```sh
npm i
NODE_OPTIONS="--trace-warnings" meteor
```

and you'll get the error.

`NODE_OPTIONS="--trace-warnings"` is required because otherwise the error will be completely unhelpful without a stack trace. It happens as a rejected promise because of dynamic imports promise-based. 

Then, stop the server and run the following to fix the error by switching to the files that use only static imports:

```sh
mv main.js main.js.off
mv client/main.js.off client/main.js
mv server/main.js.off server/main.js
NODE_OPTIONS="--trace-warnings" meteor
```

Now you will no longer get the error.

Note that `meteorStartup()` is a very simple wrapper that returns a promise that resolves when Meteor is ready using `Meteor.startup()` internally. Other than that, I don't see anything that would be causing this error in the user space, unless I've overlooked something, but the only difference is conerting from dynamic imports to static imports that fixes the problem, without touching any of the code that is imported, so that leads me to believe that the problem is caused by the dynamic import somehow.

**Comment by hwillson** [comment]
@trusktr Looking at your server side dynamic import calls

```js
...
} else if (Meteor.isServer) {
  const [{createFixtures}] = await Promise.all([
    import('/imports/startup/server/fixtures'),
    import('/imports/startup/server/register-api'),
    meteorStartup(),
  ]);
  createFixtures();
...
```

both your `fixtures` and `register-api` calls attempt to create a new server side Mongo connection, since they both use your `Messages` collection. Since these calls are happening asynchronously, they're both trying to create the needed Mongo connection first. Meteor protects against multiple calls coming in at the same time, each trying to create the initial Mongo connection, by wrapping the call to create the initial connection in an underscore `_.once` call. You can see that happening here:

https://github.com/meteor/meteor/blob/5fba1fd3e29ae5b16fc9a27c2e6f85a5bf69d7f7/packages/mongo/remote_collection_driver.js#L26-L39

So the first time the new Mongo connection is attempted to be setup (by one of your dynamic import calls), the incoming request is allowed to call `MongoInternals.defaultRemoteCollectionDriver`. The second request that comes in (from another one of your dynamic import calls) is blocked from running `MongoInternals.defaultRemoteCollectionDriver`, and instead gets back `undefined` (since the new Mongo connection hasn't finished setting itself up yet).

To verify that this is what's happening, temporarily change your server side dynamic import code block to look like this:

```js
...
} else if (Meteor.isServer) {
  MongoInternals.defaultRemoteCollectionDriver();   
  const [{createFixtures}] = await Promise.all([
    import('/imports/startup/server/fixtures'),
    import('/imports/startup/server/register-api'),
    meteorStartup(),
  ]);
  createFixtures();
...
```

So here we're forcing the initial mongo connection to be setup first, before proceeding with your dynamic import calls, which gets rid of the error you're seeing. Another way to get this working is by splitting up your dynamic import calls to make sure at least one call that initiates the Mongo connection, runs first. So something like:

```js
...
} else if (Meteor.isServer) {
  const {createFixtures} =
    await import('/imports/startup/server/fixtures');
  
  await Promise.all([
    import('/imports/startup/server/register-api'),
    meteorStartup(),
  ]);
  
  createFixtures();
...
```

Since this hasn't been a commonly reported problem, for now we'll just use this issue comment as documentation of the issue. If this issue becomes more prevalent / popular, we'll look into addressing this in core. Thanks for submitting this issue!

**Comment by trusktr** [comment]
Thanks, that's very good to know!
