### ISSUE TITLE
Build goes out of memory - 1.6.0.1

### ISSUE THREAD

**Issue by PolGuixe** [meteor/meteor#9582]
- Version: 1.6.0.1
- MacOS 10.13.2

This is a weird error. On a new machine MBP 15" 2017, when trying to deploy to make a build -deploy to galaxy, `--production` flag, ...- it runs out of memory:

```
   Minifying app code                        \
<--- Last few GCs --->

[1225:0x102801e00]   257826 ms: Mark-sweep 1390.5 (1546.1) -> 1390.5 (1546.1) MB, 1153.5 / 0.1 ms  allocation failure GC in old space requested
[1225:0x102801e00]   259049 ms: Mark-sweep 1390.5 (1546.1) -> 1390.5 (1507.1) MB, 1222.2 / 0.1 ms  last resort GC in old space requested
[1225:0x102801e00]   260306 ms: Mark-sweep 1390.5 (1507.1) -> 1390.5 (1501.6) MB, 1256.9 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1b75197a5ee1 <JSObject>
    0: builtin exit frame: slice(this=0x1b751424c9a1 <JSArray[1232183]>)

    1: clone [/Users/polguixe/.meteor/packages/standard-minifier-js/.2.2.3.fd3562.vtpy++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:~630] [pc=0x71f45e352f3](this=0x1b751424c8f9 <State map = 0x1b759956f021>,skipArrays=0x1b7508f02311 <undefined>)
 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

However, the same exact project builds on older machines without issues 🤷‍♂️  :
- MBP 13” Late 2013 MacOS 10.13.2
- Mac Mini 2013
- MBP 13” Late 2011

Any idea? The logic tells me that must be something with the new machine, however, I have no idea... the only change we did to the older machines was related to this issue which seems to be solved on newer versions of Meteor https://github.com/meteor/meteor/issues/6952

I know this issues might be related somehow to https://github.com/meteor/meteor/issues/9568, however, I didn't want to interfere with their discussion.

**Comment by hwillson** [comment]
@PolGuixe Please interfere with the discussion in https://github.com/meteor/meteor/issues/9568! 🙂 This is almost certainly related to https://github.com/meteor/meteor/issues/9568, so let's keep the discussion all in one place. Closing here - thanks!
