### ISSUE TITLE
Meteor._reload.onMigrate is undefined

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#9585]
Just upgraded to Meteor 1.6.1 and I had this piece of code in my client js to stop hot refreshes:
```
Meteor._reload.onMigrate(function() {
                return [false]
            })
```
This is as seen in https://stackoverflow.com/questions/27682888/how-can-i-disable-live-reload-in-meteor

The error that pops up is `Uncaught TypeError: Cannot read property 'onMigrate' of undefined`

Was this deprecated in the new version?  If so, how should I prevent a hot reload?

**Comment by hwillson** [comment]
Yes, `Meteor._reload` was removed in https://github.com/meteor/meteor/commit/14dbfb4c2b52dadefa1cf79c1fc5e28aee2ad7d0. It has been deprecated for quite some time. Try `Reload._onMigrate`.

**Comment by jasongrishkoff** [comment]
Thanks, that does the trick!
