### ISSUE TITLE
@babel/runtime npm package could not be found in your node_modules

### ISSUE THREAD

**Issue by tab00** [meteor/meteor#9589]
- [ ] The version of Meteor showing the problem.
1.6.1

- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
1.6.0.1

- [ ] The operating system you're running Meteor on.
Windows 10

- [ ] The expected behavior.
App runs without error.

- [ ] The actual behavior.
Error output:
```
Unable to resolve some modules:

  "@babel/runtime/helpers/inheritsLoose" in
/C/Users/-/Documents/Meteor/Projects/simple-todos-react/imports/ui/App.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime
```
```
Error: The @babel/runtime npm package could not be found in your node_modules
directory. Please run the following command to install it:

  meteor npm install --save @babel/runtime

    at babel-runtime.js (packages\babel-runtime.js:25:9)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at packages\babel-runtime.js:132:15
    at packages\babel-runtime.js:139:3
```

- [ ] A **simple** reproduction!
git clone https://github.com/meteor/simple-todos-react
cd simple-todos-react
meteor update --all-packages
meteor npm install
meteor npm update react react-dom
meteor

**Comment by tab00** [comment]
I've just noticed in https://github.com/meteor/meteor/blob/dfc07025580960ea40833c1340217695ab9601c4/History.md that I do actually need to install `@babel/runtime` even though I already have `babel/runtime`.

**Comment by hwillson** [comment]
Correct - see also: https://blog.meteor.com/announcing-meteor-1-6-1-50aad71da4e6
