### ISSUE TITLE
[1.6.1] Cordova plugins using ext.postBuildExtras cause cdvassets.manifest not to be created

### ISSUE THREAD

**Issue by BudgieInWA** [meteor/meteor#9590]
The issue is well described in #7600 and is reproduced in https://github.com/BudgieInWA/meteor-cordova-postBuildExtras-bug.

I am opening this new issue because this bug continues to effect us, even in Meteor 1.6, and the previous issue remains closed.

**Comment by hwillson** [comment]
Thanks @BudgieInWA - I'll re-open #7600 so we're able to track all of this in one place.
