### ISSUE TITLE
Meteor-tool 1.6.1 stuck on extracting

### ISSUE THREAD

**Issue by LookItsBlu** [meteor/meteor#9592]
Hi!

I've now been spending around 2 hours on an issue with meteor 1.6.0 not being able to update to 1.6.1, since said update gets stuck trying to extract meteor-tool

I've seen previous issues (https://github.com/meteor/meteor/issues/7688#issuecomment-260819083, https://github.com/meteor/meteor/issues/8871#issuecomment-316411859) about people recommending to replace 7zip in
`C:\Users\<user>\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin`
however, this did not solve any of my issues.

I've also seen this comment: https://github.com/meteor/meteor/issues/7688#issuecomment-360987929 recommending to do a complete uninstall/reinstall of meteor via `choco uninstall meteor`, however I just get an error that choco cannot find the package anymore(?)

I've also tried completely disabling windows defender as recommended multiple time in this issue: https://github.com/meteor/meteor/issues/7688#issuecomment-297297466, no luck still

I'm using a windows 10 pc with the latest update

**Comment by hwillson** [comment]
@LookItsBlu Can you try the steps listed in https://github.com/meteor/meteor/issues/7688#issuecomment-360987929 an report back?

**Comment by LookItsBlu** [comment]
thanks for the quick response!
I did, that's actualy the comment I was alluding to about the complete reinstall (will add a link to the comments I saw to help with this)

the exact error I get form chocolatey when trying to uninstall is "meteor is not installed. cannot uninstall a non-existent package", however typing the meteor command does actualy try and start the update still, meaning that it is still there

**Comment by LookItsBlu** [comment]
I'm trying to update again and the package gets downloaded again after waiting on extracting for a bit, could it be that the archive download is corrupted?

**Comment by LookItsBlu** [comment]
Alright because of the corrupted download assumption I assumed that the version of meteor I had somehow got corrupted, which would've explained chocolatey not finding it, so I decided to reinstal meteor using chocolatey __without__ uninstalling it, and I was able to finaly fix the issue by doing so

the last thing that happened since last time I've used meteor on this pc was the windows fall creator update, so I guess that might've been the cause of the corruption, no idea for sure however

**Comment by abernix** [comment]
On Windows, there is really only one place that Meteor is installed, and that's within the `%LocalAppData%\.meteor` directory (this means `C:\Users\USERNAME\AppData\Local\.meteor`).  Specifically, there is a `meteor.bat` in that directory which calls the individual versions of the `meteor-tool` in a more nested directory.  To completely uninstall Meteor, you really need only delete the `%LocalAppData%\.meteor` directory.  You can optionally remove it from your `$PATH` (or `$Env:Path`), via the control panel's "Environment Variables", but that part is optional.

If `meteor` was still available on the command line then some part of an uninstallation has failed.  If you tried uninstalling with the Windows' Remove Programs (and found "Meteor" in there at all), then that means that you had installed Meteor with the GUI installer (`InstallMeteor.exe`).  That installer (and it's bundled uninstaller) was not always properly uninstalling Meteor, which could have produced the problem you encountered here.

The new Chocolatey Meteor installer `choco install meteor`, [makes effort](https://github.com/meteor/meteor-chocolatey-installer/blob/d34c24628085d32ebe7322eb23c2c0f0c8880075/tools/chocolateyinstall.ps1#L15-L19) to remove the existing installation, even during a fresh install.

Anyhow, I hope that you'll have greater success and less trouble now that you've got over that hump.  Perhaps, as you said, there was some corruption from other angles, though I'd point most fingers at the old installer, if you had used that at any point.  Closing this, but please do ping for a re-open if you continue to experience problems!

**Comment by mohamedmansour** [comment]
Note, I am having this exact issue as well, stuck at extracting, any ideas what I should do? @abernix :

```
C:\WINDOWS\system32>choco install meteor
Chocolatey v0.10.8
Installing the following packages:
meteor
By installing you accept licenses for the packages.

meteor v0.0.2 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Yes

Extracting C:\Users\Mohamed\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar.gz to C:\Users\Mohamed\AppData\Local\Temp\chocolatey\meteor\0.0.2...
C:\Users\Mohamed\AppData\Local\Temp\chocolatey\meteor\0.0.2
Extracting C:\Users\Mohamed\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteor-bootstrap-os.windows.x86_64.tar to C:\Users\Mohamed\AppData\Local...

```

**Comment by abernix** [comment]
@mohamedmansour Did you disable your anti-virus (including Windows Defender, Norton, McAfee, etc.)?  Extraction and creating the complex directory structure required by deep `node_modules` trees (not just `meteor`, but for Node modules in general) can be quite slow if file scanning tools are enabled.

**Comment by mattjstevenson** [comment]
When installing Meteor via 'choco install meteor' I get stuck for a very long period on the extraction of Meteor. Even when a clean reinstall was done (which might not matter due to the fact chocolatey removes any previously installed or failed installs of meteor before reinstalling), it still has me stuck on the extraction. Any ideas? I realise this is quite an old post but any help would be appreciated.

**Comment by atomoc** [comment]
I have the same thing, I thought one of them and tried [your solution](https://github.com/meteor/meteor/issues/9592#issuecomment-361541711), it doesn’t help at all, why did they close it?

**Comment by atomoc** [comment]
Enjoy the solution!
