### ISSUE TITLE
[1.6.1] dynamic-import no longer then-able

### ISSUE THREAD

**Issue by dhrubins** [meteor/meteor#9594]
Moving from dynamic-import v0.2.1 to v0.3.0 in Meteor 1.6.1 causes quite a bit of our dynamic import code to break since the dynamic import promise never seems to get resolved. 

For example:
```import ('./foo').then(() => console.log('broken; never logs to console'))```

I'll start work on a minimal reproduction.

**Comment by dhrubins** [comment]
It's strange - I can only reproduce this in our full app, not in a fresh Meteor app, so I'm closing out this issue for now. From what I can tell the promise isn't getting resolved because the client just never gets a response from the server.

**Comment by dhrubins** [comment]
FWIW, here's a workaround ```new Promise(resolve => resolve(require('./foo'))).then(() => console.log('annoying, but works fine'))```

**Comment by benjamn** [comment]
That workaround includes the code in the JS bundle, rather than loading the code dynamically. If there's a real problem here, more information would be useful, especially if you can provide a reproduction. What's happening with the `fetch` HTTP requests? Can you set a breakpoint in the `dynamic-import/server.js` file to see how the request is getting handled?

**Comment by dhrubins** [comment]
Ah, thanks a million! That helped me isolate the problem to the way the request was being handled. I recalled some of our code that used `body-parser`, which apparently chokes on multipart requests. So, this is definitely confined to our App, and is not a general Meteor issue.

Here's what we were doing:
```
import { Picker } from 'meteor/meteorhacks:picker'
import bodyParser from 'body-parser'
Picker.middleware(bodyParser.urlencoded({ extended: false, limit: '10mb' }))
Picker.middleware(bodyParser.json())
```
I suppose it's time for us to replace `body-parser` with `busboy`.
