### ISSUE TITLE
[1.6.1] Missing Reflect in Internet Explorer 11 when app includes a class that extends a built-in class

### ISSUE THREAD

**Issue by y-ich** [meteor/meteor#9598]
Accessing an app by IE11 causes '"Reflect" is not defined' error in modules.js.

To reproduce it,
1. meteor create reproduction.
2. cd reproduction
3. add the following code into client/main.js.

    class DummyError extends Error {}

4. invoke meteor
5. access the page by IE11.

Doesn't Babel 7 support IE11?

**Comment by abernix** [comment]
This seems related to changes in the way built-ins (e.g. `Date`, `Uint16Array`, `Error`, ...) are able to be extended in Babel 7 (surfacing in https://github.com/babel/babel/pull/7020).

In Babel's [`wrapNativeSuper`](https://github.com/babel/babel/blob/252ea5a966c1968d8aac21a1a81c6d45173e57dd/packages/babel-helpers/src/helpers.js#L434), the use of `typeof Reflect`  is transpiled (when published) to use Babel's own [`_typeof` helper function](https://github.com/babel/babel/blob/252ea5a966c1968d8aac21a1a81c6d45173e57dd/packages/babel-helpers/src/helpers.js#L12-L26), which IE11 takes issue with (throws) as `Reflect` is undeclared.  It ends up looking like this when shipped to the client:

```js
var _construct = _typeof(Reflect) === "object" && _Reflect$construct || function _construct(Parent, args, Class) {
  var Constructor,
      a = [null];
  a.push.apply(a, args);
  Constructor = Parent.bind.apply(Parent, a);
  return _sPO(new Constructor(), Class.prototype);
};
```

A native `typeof Reflect` in IE11 does return `"undefined"`, as expected, but the problem arises specifically with the use of `_typeof(Reflect)`.  So if the line above is changed to the following, everything seems to work okay in IE11:

```js
var _construct = Reflect && _typeof(Reflect) === "object" && _Reflect$construct || function _construct(Parent, args, Class) {
```

I suppose Meteor could fix this by shipping `Reflect` polyfills in [`ecmascript-runtime-client`](https://github.com/meteor/meteor/blob/17eaa5bd6f9f4837c6c22001c30bfd65e5d28496/packages/ecmascript-runtime-client/runtime.js), but this does seem like a bug in Babel and seeing as IE11 is one of two so-called "modern browsers" which [doesn't natively support `Reflect`](https://kangax.github.io/compat-table/es6/#test-Reflect), it seems like a waste to ship that polyfill if we can avoid it.

This is my take, however @benjamn may know the cleanest way to fix this.

**Comment by benjamn** [comment]
I believe we can make this work with a patch update to `ecmascript-runtime-client` by adding just the `Reflect.construct` polyfill (which is a small subset of the whole `Reflect` polyfill). Then in Meteor 1.6.2 we can restrict that polyfill to legacy browsers (#9439), since modern browsers (as we're defining them—anything with native `async`/`await`) should all have native support for `Reflect.construct`.
