### ISSUE TITLE
Noninitial mobile "run" raises "Uh oh! … Cannot find module … pods.json".

### ISSUE THREAD

**Issue by davinderkumar** [meteor/meteor#9601]
I'm getting the following error when trying to run the project again,

> %% Error during processing of action! Attempting to revert...
>=> Errors executing Cordova commands:                                                      
>   While removing plugins                     
>   cordova-plugin-camera,cordova-plugin-compat,cordova-plugin-contacts,cordova-plugin-inappbrowser,cordova-plugin-ios-non-exempt-encryption,cordova-plugin-meteor-webapp,cordova-plugin-opensettings,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-wkwebview-engine,cordova-plugin-x-socialsharing,es6-promise-plugin,org.flybuy.nativeutils,phonegap-plugin-push
>   from Cordova project:
>   Error: Uh oh!                              
>   Cannot find module '<path>/.meteor/local/cordova-build/platforms/ios/pods.json'
>   at Function.Module._resolveFilename (module.js:536:15)
>   at Function.Module._load (module.js:466:25)
>  at Module.require (module.js:579:17)
>   at require (internal/module.js:11:18)
>   at uninstall (/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:133:40)
>   at ActionStack.process (/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
>   at PluginManager.doOperation
>   (/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
>   at PluginManager.removePlugin
>   (/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:148:17)
   at Api.removePlugin (/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:317:10)
   at handleUninstall
   (/Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:329:6)
   at
   /Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:312:20
   at _fulfilled
   (/Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
   at
   /Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:509:49
   at flush
   (/Users/davinder/.meteor/packages/meteor-tool/.1.6.0_1.1k1mh2i++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
   => awaited here:

Edit:
I'm using Mac OS 10.12.6 (16G1036)

**Comment by hwillson** [comment]
@davinderkumar Any chance you could share a small runnable reproduction that has this problem?

**Comment by abernix** [comment]
I'm certainly curious if the detail identified in your other issue, https://github.com/meteor/meteor/issues/9602#issuecomment-361736342, is related to this unexpected/bizarre error.

**Comment by davinderkumar** [comment]
No. It is not related. I'm still getting the issue.

@hwillson 
Here is sample app 
[app.zip](https://github.com/meteor/meteor/files/1682865/app.zip)
First time it works fine, but second time gives the error.
let me know if you see it

**Comment by davinderkumar** [comment]
here is updated one
[app.zip](https://github.com/meteor/meteor/files/1684143/app.zip)
