### ISSUE TITLE
Latest meteor/jquery package vulnerable to XXS

### ISSUE THREAD

**Issue by ryanmtaylor** [meteor/meteor#9605]
`meteor/jquery` package gives jQuery version 1.11.2 – the 1.x branch is no longer maintained and 1.12.1 is the latest version not vulnerable to the following XXS bug: https://snyk.io/vuln/npm:jquery:20150627

The bug was fixed in 1.12.0, then there was an update in 1.12.1, but unfortunately the bug fix was rolled back in 1.12.2 meaning versions 1.12.2-1.12.4 (latest 1.x) are also vulnerable.

Can somebody update the `meteor/jquery` package to simply use jQuery 1.12.1?

More info: https://github.com/jquery/jquery/issues/2432

**Comment by benjamn** [comment]
Just a note that you can `meteor npm install jquery@1.12.1` (or any version for that matter) in your application's `node_modules` directory, and the `meteor/jquery` package will [use that instead](https://github.com/meteor/meteor/blob/17eaa5bd6f9f4837c6c22001c30bfd65e5d28496/packages/jquery/main.js#L4).
