### ISSUE TITLE
Passing settings file in when running bundled server?

### ISSUE THREAD

**Issue by benknowles** [meteor/meteor#961]
In development you can do:

`meteor --settings settings.json`

I would have thought this would work in production:

`PORT=1337 MONGO_URL=mongodb://localhost:27017/meteor ROOT_URL=http://redacted:1337 node main.js --settings /home/redacted/settings.json`

but nothing happens, and the settings inside "public" aren't accessible via Meteor.settings in the console.

Is there some magical environmental variable to pass them in or is it not yet supported?

**Comment by Zeioth** [comment]
Alternative solution for those using AWS beanstalk, since settings.json is not included in the project build.

URL: http://stackoverflow.com/a/34774239/2010764
