### ISSUE TITLE
[1.6.1] Cannot read property 'getContentsAsString' when minifying CSS.

### ISSUE THREAD

**Issue by delay** [meteor/meteor#9610]
I recently updated a project to 1.6.1 from 1.6.0.1.  When I run it, I get the following error.

```
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   packages/minifyStdCSS_plugin.js:130:34: Cannot read property 'getContentsAsString' of undefined
   at packages/minifyStdCSS_plugin.js:130:34
   at Array.map (<anonymous>)
   at packages/minifyStdCSS_plugin.js:129:32
   at CssToolsMinifier.processFilesForBundle (packages/minifyStdCSS_plugin.js:33:16)
```

I tried removing my entire stylesheet and tried running it and still receive the same error.  
If I remove the standard-minifier-css plugin,  the app runs without any trouble. 
If I downgrade to 1.6.0.1 build of meteor it also runs fine with standard-css-minifier plugin installed.  

Thanks for any help!

**Comment by abernix** [comment]
Thanks for filing this issue.  It would be so helpful if you could provide a small, runnable reproduction (in the form of a small new Meteor app) which demonstrates the problem.  This may involve simplifying/minimizing your existing project until it exhibits the problem without all the other pieces and you can share it with us.

**Comment by delay** [comment]
I tracked down the problem and made a simple repository to demonstrate the trouble.  
https://github.com/delay/css-trouble

The file /packages/delay-jasny-bootstrap/jasny-bootstrap.css.map is failing in being parsed and minimized by the new css minimizer in meteor 1.6.1. It worked fine in previous builds.  I don't know very much about css.map files as I am just utilizing this package in my project.  Anyway I hope this helps.  The package is based off this project. http://www.jasny.net/bootstrap/

**Comment by hwillson** [comment]
Hi @delay - you shouldn't include a `.map` file with your package. It will be taken care of by Meteor. The fact that you had things setup like this with 1.6.0.1 and it was working was not intentional. Meteor 1.6.1's newer [`PostCSS`](http://postcss.org) based CSS handling process is more strict in certain areas (which it should be), which is likely the cause of the error you received. So, removing the `.map` is the right course of action. Thanks!
