### ISSUE TITLE
[1.6.1] [1.6.0.1] js minification failed after upgrading from 1.5 - How can I find where the issue is?

### ISSUE THREAD

**Issue by lowi** [meteor/meteor#9613]
I am using the standard-minifier-js package and I have this error upon minification:

`
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While minifying app code:
   /Users/lowi/.meteor/packages/standard-minifier-js/.2.3.1.11iz5tq.uij3++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:840:15: Unexpected token
   (1:5108716)
   at _class.raise (/Users/lowi/.meteor/packages/standard-minifier-js/.2.3.1.11iz5tq.uij3++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:840:15)
   at _class.unexpected
   (/Users/lowi/.meteor/packages/standard-minifier-js/.2.3.1.11iz5tq.uij3++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:2236:16)
   at _class.parseStatementContent
   (/Users/lowi/.meteor/packages/standard-minifier-js/.2.3.1.11iz5tq.uij3++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:4256:32)
   at _class.parseStatement
   (/Users/lowi/.meteor/packages/standard-minifier-js/.2.3.1.11iz5tq.uij3++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:4230:17)
   at _class.parseStatement
`

How can I find out which .js file is causing this issue?
(I have attached my package dependency tree)
[tree.txt](https://github.com/meteor/meteor/files/1682035/tree.txt)

**Comment by dokithonon** [comment]
+1

**Comment by bailon** [comment]
I have the same issue when deploying to Heroku, but it started with the transition from 1.6 to 1.6.0.1.

**Comment by hwillson** [comment]
@lowi Any chance you can provide a small runnable reproduction that shows this happening?

**Comment by lowi** [comment]
@hwillson I'll have a look if I can get a small reproduction system. Otherwise I was thinking of modifying the babel-compiler/node_modules/babylon/lib/index.js to output the name of the file on which it's failing.

**Comment by hwillson** [comment]
Actually, if you don't mind setting up a [developer checkout](https://github.com/meteor/meteor/blob/63ed2e250cf310cb8161a84f7e5dcfa0908eddac/DEVELOPMENT.md), you'll probably have more luck debugging directly in the `standard-minifier-js` [`minify-js.js` ](https://github.com/meteor/meteor/blob/63ed2e250cf310cb8161a84f7e5dcfa0908eddac/packages/standard-minifier-js/plugin/minify-js.js) file. 

I'm still interested in getting ahold of a failing reproduction if you have time though, as I'd like to use it as a base for potentially improving the minifier error handling. Dealing with minification errors is one of the most commonly reported issues here, so it would be great to help improve this process a bit.

**Comment by lowi** [comment]
@hwillson I'll try tomorrow with the developer checkout and will try to provide you with a small runnable reproduction if possible.

**Comment by lowi** [comment]
I tried running from the developer checkout, and I get this error with coffeescript package:
```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.0.3_4.
   Constraints on package "coffeescript":
   * coffeescript@=2.0.3_4 <- top level
   * coffeescript@1.0.4 <- tap:i18n 1.8.2
```

**Comment by hwillson** [comment]
Closing for now due to inactivity - please post back with any updates. Thanks!
