### ISSUE TITLE
Performance of files.renameDirAlmostAtomically

### ISSUE THREAD

**Issue by sotarules** [meteor/meteor#9614]
This longstanding issue has been reported before and has been closed (issue #8602), but is still happening on Meteor 1.6.1 (Windows 7 64-bit).

I'd say maybe 25% of the time, when I make a coding change and save (in development mode), Meteor will require more than a minute to build.  Clearly the bottleneck is in **files.renameDirAlmostAtomically** (note that I leave profiling on now by default).

I'm running on a Samsung 850 EVO SSD (500GB) which should help mitigate I/O bottlenecks.  My machine is 3930K (running at 4.4Ghz) with 32GB of RAM.  In theory, this should run like a bat out of hell.  So I wanted to reopen with the question: what could function **files.renameDirAlmostAtomically** possibly be doing that would take this long?

Thanks in advance for your attention.  BTW I love Meteor and now I'm using React exclusively for the front end.
```
| Top leaves:
| other files.renameDirAlmostAtomically..................170,314 ms (2)
| files.stat..............................................10,746 ms (54132)
| files.writeFile..........................................2,689 ms (332)
| Babel.compile............................................1,005 ms (848)
| files.mkdir................................................990 ms (4930)
| files.rm_recursive.........................................731 ms (294)
| files.readdir..............................................695 ms (4973)
| linker File#getPrelinkedOutput.............................685 ms (264)
| getPrelinkedFiles toStringWithSourceMap....................386 ms (1)
| files.rename...............................................196 ms (347)
| files.readFile.............................................113 ms (1393)
| files.symlink..............................................106 ms (576)
|
| (#5) Total: 190,381 ms (Rebuild App)
```

**Comment by benjamn** [comment]
I believe the culprit is [`files.rename`](https://github.com/meteor/meteor/blob/0f0ef96611fe3b78424775399e3b3805b1bbfb5b/tools/fs/files.js#L1727-L1757), which falls back to `files.cp_r` if the rename fails more than ten times due to file system errors like `EBUSY`. Unfortunately, there are all kinds of reasons why Windows might refuse to rename a directory. Super frustrating!

**Comment by sotarules** [comment]
I have some new information that may or may not make sense: if I run Meteor in a command window that has **Administrator** privileges, the app rebuilds in just 5 seconds (plus 2 .5 seconds for server startup).  So this lends credibility to the idea that we have some kind of permissions issue.
