### ISSUE TITLE
1.6.1 Dynamic import + css z-index compression fails

### ISSUE THREAD

**Issue by larswolter** [meteor/meteor#9616]
When using css in dynamic imports, the z-index in the css does not get "optimized" as it is with the default css by the postcss minifier in 1.6.1 in production.
Therefor dynamically imported css is wrongly stacked. This did not happen in the 1.6.0.1 of Meteor

**Reproduction:** 
meteor create cssbug
add ./client/imports/import.css with Content 'h1 { z-index: 250 }'
add Content 'h2 { z-index: 350 }' to ./client/main.css
add dynamic-import to .packages
add Content 'Meteor.startup(() => { import('./imports/import.css'); })' to ./client/main.js
run with --production

**Expected behavior:**
In the Brower Elements observe the styles of the h1 and h2 Elements. h2 z-index should be bigger then h1

**Actual behavior:**
h2 z-index is 1 and h1 z-index is 250

**Comment by klaussner** [comment]
[`cssnano`](https://github.com/ben-eb/cssnano) uses some unsafe optimizations by default when it minifies CSS, including [`z-index` rebasing](http://cssnano.co/optimisations/zindex/). According to the "Risk of breakage" section, it assumes that the CSS is concatenated before minification, which is not the case for `import`ed CSS.

I'll try to get a PR ready this weekend. 🙂
