### ISSUE TITLE
Facts package unwarranted coupling with blaze/templating

### ISSUE THREAD

**Issue by FGM** [meteor/meteor#9617]
| Info                                              | Details                                                      |
|:--------------------------------------------|:-----------------------------------------------------|
| Meteor versions                           |  0.6.7-rc2 to 1.6.2-beta4                          |
| Last version without the problem | 0.6.7-rc1 (package was not present yet) |
| OS                                                | any                                                          |
| Reproduction                                | `git clone https://github.com/meteor/meteor && cat packages/facts/package.js` | 

## Description of the problem

The Facts package provides two unrelated services: 

* gathering the facts "hook" implementation results to expose them for further use without manually addressing the internal structures of Meteor (think `facts-base`)
* a simple way to expose these results in Blaze templates (think `facts-ui`)

## Expected behavior

Have the UI be an optional package (`facts-ui`) or find a way to make it available only if templating is present, instead of requiring it. The list of dependencies should then just be:

```
facts@1.0.9                                   
├── ddp@1.4.0 (expanded above)                
├── mongo@1.3.1 (top level)                   
└── underscore@1.0.10                 
```

## Actual behavior

All applications using this package bring in this whole list of dependencies:

```
facts@1.0.9                                   
├── ddp@1.4.0 (expanded above)                
├── mongo@1.3.1 (top level)                   
├─┬ templating@1.3.2                          
│ ├─┬ templating-compiler@1.3.3               
│ │ ├─┬ caching-html-compiler@1.1.2           
│ │ │ ├─┬ caching-compiler@1.1.9              
│ │ │ │ ├── ecmascript@0.9.0 (top level)      
│ │ │ │ └── random@1.0.10 (expanded above)    
│ │ │ ├── ecmascript@0.9.0 (top level)        
│ │ │ ├─┬ templating-tools@1.1.2              
│ │ │ │ ├── ecmascript@0.9.0 (top level)      
│ │ │ │ ├─┬ spacebars-compiler@1.1.3          
│ │ │ │ │ ├─┬ blaze-tools@1.0.10              
│ │ │ │ │ │ ├─┬ htmljs@1.0.11                 
│ │ │ │ │ │ │ └── deps@1.0.12 (expanded above)
│ │ │ │ │ │ └── underscore@1.0.10             
│ │ │ │ │ ├─┬ html-tools@1.0.11               
│ │ │ │ │ │ └── htmljs@1.0.11 (expanded above)
│ │ │ │ │ ├── htmljs@1.0.11 (expanded above)  
│ │ │ │ │ └── underscore@1.0.10               
│ │ │ │ └── underscore@1.0.10                 
│ │ │ └── underscore@1.0.10                   
│ │ ├── ecmascript@0.9.0 (top level)          
│ │ └── templating-tools@1.1.2 (expanded above)
│ └─┬ templating-runtime@1.3.2                
│   ├─┬ blaze@2.3.2                           
│   │ ├── check@1.2.5 (top level)             
│   │ ├── htmljs@1.0.11 (expanded above)      
│   │ ├── jquery@1.11.10 (expanded above)     
│   │ ├─┬ observe-sequence@1.0.16             
│   │ │ ├── diff-sequence@1.0.7 (expanded above)
│   │ │ ├── mongo-id@1.0.6 (expanded above)   
│   │ │ ├── random@1.0.10 (expanded above)    
│   │ │ ├── tracker@1.1.3                     
│   │ │ └── underscore@1.0.10                 
│   │ ├── ordered-dict@1.0.9 (expanded above) 
│   │ ├── reactive-var@1.0.11 (top level)     
│   │ ├── tracker@1.1.3                       
│   │ └── underscore@1.0.10                   
│   ├─┬ spacebars@1.0.15                      
│   │ ├── blaze@2.3.2 (expanded above)        
│   │ ├── htmljs@1.0.11 (expanded above)      
│   │ ├── observe-sequence@1.0.16 (expanded above)
│   │ ├── tracker@1.1.3                       
│   │ └── underscore@1.0.10                   
│   ├── templating-compiler@1.3.3 (expanded above)
│   └── underscore@1.0.10                     
└── underscore@1.0.10                 
```

## Suggested fix

Convert to a wrapper package for compatibility (`facts`), use two separate packages (`facts-base` and `facts-ui`). I can submit a PR.

**Comment by hwillson** [comment]
@FGM This sounds quite reasonable, and if you're interested in working on a PR, great! One thing though - would you mind re-opening this issue over in the http://github.com/meteor/meteor-feature-requests repo? We're trying to make sure issues here are related to Meteor bugs. If you can move this over to the FR repo, I'll mark it as `pull-requests-encouraged`. Thanks!

**Comment by FGM** [comment]
Done: https://github.com/meteor/meteor-feature-requests/issues/262
