### ISSUE TITLE
[1.6.1] Using babel-preset-es2015 / env fails

### ISSUE THREAD

**Issue by nelsyeung** [meteor/meteor#9625]
### Reproduction steps
```
meteor create test
cd test
npm i -D babel-preset-es2015  # can also use babel-preset-env
```
Add the following to `package.json`
```
"babel": {
  "presets": [
    "es2015"
  ]
},
```
Run `npm start`

#### Error
Subset of the error messages:
```
While processing files with ecmascript (for target web.browser):

/Users/nelsyeung/.meteor/packages/ecmascript/.0.10.0.5xtfip.b6xls++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/scope/index.js:921:13:
   Cannot read property 'bindings' of null
   at Scope.moveBindingTo
   (/Users/nelsyeung/.meteor/packages/ecmascript/.0.10.0.5xtfip.b6xls++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/scope/index.js:921:13)
   at convertBlockScopedToVar
```

### Investigation
From #7096, it was suggested to install `babel-plugin-transform-runtime`:
```
npm i -D babel-plugin-transform-runtime
```
Add the following to `package.json`
```
"babel": {
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-runtime"
  ]
},
```
Subset of the new error messages:
```
   While processing files with ecmascript (for target web.browser):
   /Users/nelsyeung/Documents/test/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12: this.setDynamic is not a function
   at PluginPass.pre (/Users/nelsyeung/Documents/test/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
   at transformFile
   (/Users/nelsyeung/.meteor/packages/ecmascript/.0.10.0.5xtfip.b6xls++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:97:25)
   at runSync
```
Perhaps this problem is not to do with meteor due to https://github.com/babel/babel-loader/issues/560?

I cannot use `jest` because of this.

**Comment by klaussner** [comment]
- [You should use `@babel/preset-env` instead of `babel-preset-2015`](https://babeljs.io/env/) with Babel 7 and Meteor 1.6.1. This seems to be the cause of the `Cannot read property 'bindings' of null` error.
- Meteor already compiles JavaScript with `babel-preset-meteor`, so using `@babel/preset-env` [isn't necessary](https://github.com/meteor/meteor/issues/9571#issuecomment-360223847) for development and production builds. To use the preset only for testing tools like Jest, you can specify in your `.babelrc` file that it should be used the "test" environment:

```json
{
  "env": {
    "test": {
      "presets": ["@babel/preset-env"]
    }
  }
}
```

**Comment by nelsyeung** [comment]
OK, this all makes sense. I didn't actually realize that Meteor uses babel 7 now, that's great to know! Too blog post on the web seems to suggest just putting in the presets without using the test env and so I thought it should work perfectly. Thank you for this perfect explanation, everything works fine now. I apologize for this issue.
