### ISSUE TITLE
[1.6.2-beta.4] Not possible to use decorators with Meteor / babel?

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#9628]
In #9571, I asked about why Babel crashed with my .babelrc, and was told that I had to remove this line `["@babel/plugin-proposal-class-properties", { "loose" : true }]` from my custom .babelrc, because it was already provided by Meteor. I did that, and Babel stopped complaining. However, I got stuck on bug #9577, where Meteor would not send the dynamically required files.

I now believe the reason for this is that Babel crashes when compiling these files, however, this somehow happens at runtime... I made the import into a normal (not dynamic) import, and when I start Meteor and it builds all packages etc, I get no errors, but when I try to load the page, I get the warning about 

```js
store.js:1 Uncaught Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2.
    at _initializerWarningHelper (store.js:1)
    at new Store (app.js?hash=c448ff9aa122aa0fbf3988cdcfc25ec793249cba:5079)
    at index.js (index.js:8)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at export.js (export.js:1)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at exportComponent.js (exportComponent.js:1)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
```

Thus it's explicitly asking me to not put the class-properties plugin before the decorator plugin, but I have no control over this, since it's provided by Meteor?

**Comment by benjamn** [comment]
Interesting, this leads me to believe that Meteor should enable `loose` mode when we register the class properties plugin.

**Comment by benjamn** [comment]
Can you try this again after running
```sh
meteor update babel-compiler ecmascript
```
to get versions 7.0.2 and 0.10.2, respectively? You still don't need to include the class properties plugin in your `.babelrc` file, but the version of the class properties plugin provided by Meteor should now be in `loose` mode, which should eliminate this error from the decorators plugin.

**Comment by houshuang** [comment]
I did `meteor update babel-compiler ecmascript`, but it seems to only update ecmascript to the desired version. When I manually changed the version of babel-compiler in `.meteor/versions`, I got this message on startup:

```
Changes to your project's package version selections:

babel-compiler  upgraded from 7.0.2 to 7.1.0-beta162.4
```

And the same error in the browser.

I am running release Meteor 1.6.2-beta.4.

**Comment by houshuang** [comment]
I downgraded Meteor to 1.6.1, which allowed me to get the correct versions of ecmascript and babel-compiler, but it did not solve the issue. I've reduced my `.babelrc` file to the following minimal setup:

```
{ "plugins": [ "@babel/plugin-proposal-decorators"] }
```

**Comment by benjamn** [comment]
Ah sorry, the recent change means it's now safe to put
```js
{
  "plugins": [
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    "@babel/plugin-proposal-decorators"
  ]
}
```
back into your `.babelrc` file, and the two class properties plugins will no longer conflict.

The backstory is that any `plugins` in a `.babelrc` file run (and finish running, completely) before `babel-preset-meteor` runs, so your `@babel/plugin-proposal-decorators` plugin runs by itself, before anything else, and that's why it thinks `@babel/plugin-proposal-class-properties` isn't also running (even though it will run, later).

This stuff is tricky for sure, but this is exactly why dependencies between Babel plugins are so problematic. Things won't get much easier until a version of the decorators plugin is released that doesn't depend on the class properties plugin.

**Comment by houshuang** [comment]
Yes, this seems to have solved it. Thanks!

**Comment by damonmaria** [comment]
On `METEOR@1.6.1` I'm getting the same error from the opening comment in this issue while using the `.babelrc` from https://github.com/meteor/meteor/issues/9628#issuecomment-362861507.

`Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2.`

That's with:
```
babel-compiler@7.0.4
ecmascript@0.10.4
```

Which exceed the versions of these packages mentioned above.

**Comment by trusktr** [comment]
Adding to Ben's last comment, you'd also need to run `meteor npm install @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-decorators`.

**Comment by filipenevola** [comment]
Check Meteor 1.12 😉
