### ISSUE TITLE
[1.6.1] minification of css replaces strings with random characters

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#9633]
Using animate.css under 1.6.0.1 worked fine, but starting with 1.6.1 all strings in css not in quotes are being replaced by randomized characters, so 
```
.bounce {
  -webkit-animation-name: bounce;
  animation-name: bounce;
  -webkit-transform-origin: center bottom;
  transform-origin: center bottom;
}
```
becomes
```
.bounce {
    -webkit-animation-name: a;
    animation-name: a;
    -webkit-transform-origin: center bottom;
    transform-origin: center bottom
}
```

**Comment by klaussner** [comment]
I think this is related to https://github.com/meteor/meteor/issues/9616#issuecomment-362552416 – pull request coming soon! :smile:

**Comment by jamgold** [comment]
@klaussner thanks, also for adding the note about importing, that should have been a much better workaround than editing the animate.css file :)
