### ISSUE TITLE
Promise.prototype.finally missing

### ISSUE THREAD

**Issue by runarberg** [meteor/meteor#9639]
Now that [`Promise.prototype.finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) is a part of the ECMAScript spec, it would be nice to be able to use it in my meteor applications as well. However, it is still annoyingly missing from Meteor 1.6.1 despite being present in `@babel/runtime/core-js`.

**Comment by hwillson** [comment]
Thanks for the suggestion - this is a feature request so normally we'd ask to have this moved over to the http://github.com/meteor/meteor-feature-requests repo, but in this case the changes are quite small, so PR #9663 has been submitted to help with this.
