### ISSUE TITLE
Running Meteor app in a subfolder

### ISSUE THREAD

**Issue by nikhildaga** [meteor/meteor#964]
Is it possible to run a meteor app in a subfolder ... 
e.g. domain.com/meteor instead of domain.com

By using proxy, I was able to point domain.com/meteor/ to domain.com:3000 but all the files still take base path as domain.com instead of domain.com/meteor/  and therefore, return 404.

**Comment by Huljo** [comment]
The webapp still not working in a subfolder behind nginx in my case.

Im trying to install Rocket.chat in a subfolder but the webapp package rejected the URL (ROOT_URL=http://www.domain.com/chat/) and throw "Unknown path" if I run nginx in front.

[The Rocket.chat issue](https://github.com/RocketChat/Rocket.Chat/issues/4546)
