### ISSUE TITLE
accounts-facebook not working in Cordova (iOS/Android) with Error: "Not Logged In: You are not logged in. Please login and try again."

### ISSUE THREAD

**Issue by eyeswideopen** [meteor/meteor#9643]
The mentioned error appears when Meteor.loginWithFacebook() is called within the Facebook Popup/Redirect.
After closing the callback is not called.

**THE LOGIN WORKS IN THE BROWSER, ONLY MOBILE FAILS**

Reproducable with this minimal test environment:
clean meteor project (version 1.6.1)

Added packages:
```
accounts-facebook      1.3.1
service-configuration  1.0.11
```

Added platforms:
```
iOS
android
```

Configuration of the FB service (with service-configuration) in server/main.js:
```
ServiceConfiguration.configurations.remove({
  service: "facebook"
});

ServiceConfiguration.configurations.insert({
  service: "facebook",
  appId: "1718573305025155",
  secret: "<myAppSecret>",
  loginStyle: "redirect"
});
```

Test call of Meteor login:
```
Meteor.loginWithFacebook({
      requestPermissions: ['user_friends', 'public_profile', 'email']
    }, (err) => {
      if (err) {
        console.log(err)
      } else {
        // successful login!
        console.log("success")
      }
    });
```

results in:
<img width="767" alt="screen shot 2018-02-06 at 13 40 32" src="https://user-images.githubusercontent.com/2435748/35860227-95c53a28-0b43-11e8-82b7-34d1e8e5369e.png">

**Comment by paulincai** [comment]
I went down that path and it never worked for me. I believe it is related to some changes made by FB to disallow oauth via web within native apps or so. I am sure this has been discussed extensively in the Forum and Git.

What works for me in Meteor 1.6.1 is 
NPM: "bas-meteor-facebook-login": "^1.1.0"
Cordova: cordova-plugin-facebook4@1.9.1
In mobile-config.js : 
`
App.configurePlugin('cordova-plugin-facebook4', {
  APP_ID: '*************8',
  APP_NAME: 'Yorappname'
})
`
Settings.json:
`"oAuth": {
      "facebook": {
        "appId": "**********",
        "secret": "_____________________"
      }}
`
Also you may see my comment [here](https://github.com/jeduan/cordova-plugin-facebook4/issues/612#issuecomment-359627767) for the Android side of things. It won't work without that hash. I am not sure it can work in anything other than the production/signed app.

I use separate servers for mobile and browser but for you, if you serve both, I think you will keep what you have for browser and add the part for Cordova and handle them in something like: if (Meteor.isCordova) ....

**Comment by jimmythigpen** [comment]
I am having a similar issue, same error. Using Meteor 1.3.2.4 and accounts facebook. Facebook is requiring that we use an OAuth redirect URLs and strict mode for logging in. They will be flipping the switch in March. I have been unable to get this working. 

![image](https://user-images.githubusercontent.com/9611366/36757581-f8baeaea-1bdf-11e8-9dad-12b7ef4f13ac.png)

**Comment by hwillson** [comment]
Just dropping a reference - this issue is related to https://github.com/meteor/meteor/issues/9713.

**Comment by hwillson** [comment]
I don't have a fix ready for this, but I'll document why this is happening (in development anyways). The `redirect_uri` that's being set here:

https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/packages/facebook-oauth/facebook_client.js#L35

ends up looking something like `http://173.30.140.110:3000/_oauth/facebook` when run through Cordova (so using a local development IP). This doesn't match the default OAuth redirect URI we're asking people to configure with Facebook:

![screenshot 2018-03-07 07 33 21](https://user-images.githubusercontent.com/137740/37092431-e830a9ee-21d9-11e8-8252-490c01434069.png)

Facebook requires them to match exactly. Modifying the `redirect_uri` to match before sending it over to Facebook gets past the not logged in error and allows the login popup to load properly.

Marking as `pull-requests-encouraged` if anyone is interested in digging into this further. Thanks!

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Comment by yehr59** [comment]
hello, 
someone have a good solution for this ? 
I need my iOS and Android app connect with facebook. But have same error.

I'm actually working around `cordova-plugin-facebook4`, but it's a little hard...

**Comment by paulincai** [comment]
@yehr59 you have my answer above. Works like a charm.

**Comment by yehr59** [comment]
`Settings.json:` where is the file location ?

**Comment by yehr59** [comment]
My code is : 
`facebookConnectPlugin.login(permissions, fbLoginSuccess, fbLoginFail);`

`fbLoginSuccess ` return user state **connected**, but not create new user like `Meteor.loginWithFacebook`...

**Comment by paulincai** [comment]
@yehr59 well ... in dev, local station should be right under the app's folder (beside mobile-config.js) when you deploy somewhere, you have to have this data under config variables. For instance, I host with Heroku so I have that data under Projectname / Settings/ Config Variables

**Comment by paulincai** [comment]
@yehr59 did you use Accounts.onCreateUser((options, user) => { ... }) to add Facebook data to the user?

**Comment by yehr59** [comment]
yeah in server side : 
`Accounts.onCreateUser(function(options, user) {
  if (! user.services.facebook) {
    // Use provided profile in options, or create an empty object
    user.profile = options.profile || {};
    // Assigns first and last names to the newly created user object
    user.private = {};
    user.private.gender = options.gender;
    user.private.brithday = options.brithday;
    user.private.first_name = options.first_name;
    user.private.last_name = options.last_name;
    user.private.name = [options.first_name, options.last_name].join(' ');
    // Returns the user object
  }else{
    let fb = user.services.facebook;
    // Use provided profile in options, or create an empty object
    user.profile = options.profile || {};

    user.private = {};
    user.private.brithday = fb.brithday;
    user.private.first_name = fb.first_name;
    ...
    user.private.last_name = fb.last_name;
    user.private.locale = fb.locale;
    user.private.name = fb.name;
    user.private.user_location = fb.locale;
  }
  return user;
});`

**Comment by paulincai** [comment]
@yehr59 I think we're a little ... async.  I am on skype: paulailincai just in case you don't figure it out.

**Comment by paulincai** [comment]
https://www.npmjs.com/package/bas-meteor-facebook-login

`FB_API.login(function(err) {`
        ` if (err) {`
            ` console.log(err);`
       `} else {`
            `console.log('login...');`
       `}`
`});`

I use that except that i don't have accounts-facebook
With Meteor 1.6.1.1 I user cordova-plugin-facebook4@1.9.1  (not what is mentioned in the npm instructions)

**Comment by yehr59** [comment]
Ok thx, i will try tomorrow !

**Comment by paulincai** [comment]
I am glad it worked. My projects Mobile and Web are separated on two ... projects.
You can indeed do an 'if' there and run web via Meteor.loginWithFacebook .

In a previous comment I said that on mobile I don't use accounts-facebook. So in case you removed it, you need it back.

One comment, if your app touches in any way Europe or European citizens, please consider GDPR and request minimum data from FB and follow the GDPR guidelines.

**Comment by yehr59** [comment]
Thank you very much for your help.

We have already planned the gdrp, in France it is a very important topic in start-ups and in large companies.

**Comment by lucnat** [comment]
If anyone is still interested in this: Just use redirect method instead of popup. It works.
