### ISSUE TITLE
How do I setup auto-deploy from GitHub repo to Meteor Galaxy?

### ISSUE THREAD

**Issue by pedrofg** [meteor/meteor#9645]
Hello, the idea here is to every time a specific branch of my repository (GitLab) is updated it should make a new deploy to the Meteor Galaxy. Has anyone done it? Do you know a tutorial for this?

**Comment by skirunman** [comment]
Definitely possible. I think this question would be better asked on https://forums.meteor.com/ so if you close this here and ask there I'll respond there.

**Comment by pedrofg** [comment]
Thanks. https://forums.meteor.com/t/how-do-i-setup-auto-deploy-from-gitlab-repo-to-meteor-galaxy/42057

**Comment by skirunman** [comment]
I'll try to help out on the forums, you should close this now.
