### ISSUE TITLE
Meteor.http no longer works, must move to HTTP

### ISSUE THREAD

**Issue by hashcutdev** [meteor/meteor#9646]
Just FYI, in the new version 1.6.1, Meteor.http calls no longer work. They must be changed to HTTP.

I have some old code on the client that makes Meteor.http.get() calls that were no longer working. Changing to HTTP.get() works fine.

I don't think I've ever seen a deprecation notice, but it was working through version 1.6.0.1.

It's no big deal, but maybe in your upgrade notice, you could make a quick note of the deprecation?

**Comment by abernix** [comment]
`Meteor.http` was renamed to `HTTP` in Meteor 0.6.5, over four years ago, and this deprecation was listed in [the change log for Meteor 1.6.1](https://github.com/meteor/meteor/blob/devel/History.md#v161-2018-01-19).

We can't list all the details of every upgrade in the upgrade notice on the console, and we try to avoid breaking changes altogether, but it's certainly encouraged to read the change log for each new version.  This could have been messaged better through `console.warn`-ings when it was originally decided to rename it, and we'll try to make sure we're more clear about those deprecations when they happen in the future.  Sorry you got bit by this!

**Comment by hashcutdev** [comment]
Sorry, I read through the changelog again just now and saw the notice. I completely missed it the first time I read it. Must have been a brain farct :-)

Yeah, I agree, it's a minor enough issue that it doesn't require a console.warn(). I was more suggesting to put it in the changelog but I see now it's already there.

My project is actually only 3 years old, but when I first started, I was using online guides which still had the old syntax. So, FWIW, I wouldn't have seen any warnings done at the time of the initial deprecation either. Not sure if there's a way to capture everyone who slips through the cracks, but at the very least, thanks for making the changeover painless! :-)
