### ISSUE TITLE
Unable to set bcryptRounds

### ISSUE THREAD

**Issue by morloy** [meteor/meteor#9651]
It's currently impossible to change the value of `bcryptRounds` using `Accounts.config`.

The problem is in [password_server.js](https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_server.js#L25), which gets evaluated before it's possible to actually call `Accounts.config`.

**Comment by mjmasn** [comment]
Sounds similar to https://github.com/meteor/meteor/issues/7455

**Comment by morloy** [comment]
A very simple fix for this problem would be to write
```
Accounts._bcryptRounds = function () {
  return Accounts._options.bcryptRounds || 10;
}
```

If this is an accepted solution I can open a PR.

**Comment by hwillson** [comment]
Nice catch @morloy! Yes, we'll definitely review a PR for this (and your suggested solution sounds reasonable). Thanks!

**Comment by kaiquewdev** [comment]
Javascript has a lower typed system, that implementation express an immutable condition.

**Comment by kaiquewdev** [comment]
"_variables" have a meaning of a private variable.

**Comment by linhpqq** [comment]
How i change default Salt Round password in Rocket Chat (from 10 to 11) ???
