### ISSUE TITLE
Windows 10 - Persist data is not reliable

### ISSUE THREAD

**Issue by ifahrentholz** [meteor/meteor#9655]
Hi, I've a problem when persisting data to MongoDB.
As I found out the problem did not exist on version 1.4 - but now I'm using version 1.6 on Windows 10.

To reproduce that you can checkout my repository (https://github.com/ifahrentholz/score-keep).

1. Run meteor npm install
2. Start meteor with "meteor"
3. Open browser and add some items
4. Stop meteor (Ctrl+C)
5. Start meteor again and you see that the data was not saved ...
6. If that does'nt happen on first try do the steps above a second time and you should see the problem

I also tried that on my mac and there this bug doesn't appears. 
Also I've worked through your tutorial ("Simple Todos") and there's the same problem..

- [ ] Meteor showing the problem is: 1.6.
- [ ] The last version of Meteor where the problem did _not_ occur is: 1.4

**Comment by ifahrentholz** [comment]
It seems like this is a problem with the MongoDB version included in the meteor package.
If I install MongoDB "Standalone" and register mongo_url via "SET MONGO_URL=mongodb://localhost:27017/meteor" to force meteor to use the standalone MongoDB installation everything works fast without seconds of delay on persisting data.

**Comment by hwillson** [comment]
Sorry to hear you're having trouble @ifahrentholz. This isn't a common problem. Have you updated your Windows Meteor installation using the newer [Chocolatey based installer](https://www.meteor.com/install)?

**Comment by ifahrentholz** [comment]
Yes I installed Meteor using chocolatey version 0.10.8

**Comment by hwillson** [comment]
Wow, that is a strange one @ifahrentholz. It really looks as though when you kill/restart Meteor, it's automatically running a `meteor reset` first. Meteor stores its Mongo db in your apps `.meteor/local/db` directory. Maybe dump a list of the contents of that directory before you kill/restart Meteor, then look in that directory again. Are all of the same files there or did some/all of them get wiped? This will be a very tricky issue to troubleshoot without being able to re-create it, which is something I haven't been able to do unfortunately. Can you maybe try a full uninstall of Meteor (`choco meteor uninstall`, then make sure %LocalAppData%/.meteor has been removed), then re-install to see if that helps?

**Comment by ifahrentholz** [comment]
Hm, I've tried to delete some files from the `.meteor/local/db` while the App was running. And yes some files were automatically recreated. I think thats normal.. 

Also I've now uninstalled meteor with `choco uninstall meteor` and did a manual check in `%LocalAppData%` that `.meteor` was removed completely.. then I've reinstalled meteor with `choco install meteor`..

Unfortunately the problem still occurs.

Now that I think about what could be different on my machine I've came accross the idea that maybe that error occurs here since I'm using Windows 10 on my Mac via Bootcamp installation. But thats just guessing...

**Comment by JamesFalero** [comment]
ifahrentholz, I know this question is a month old but if you have it available, try reproducing the problem on an actual install of windows 10 and let us know how it goes.

If you don't have a pc with windows 10 installed I'll go head and attempt to reproduce the bug.

**Comment by ifahrentholz** [comment]
Hi @JamesFalero actually I have a full windows 10 installation on my Mac Computer via Bootcamp. Thats all I can do since I don't own an PC. But I want to point out that it's real Windows 10 on an own Partition (not just an VM).
