### ISSUE TITLE
1.6 -> 1.6.1 - WebApp.connectHandlers no longer getting some Meteor boilerplate?

### ISSUE THREAD

**Issue by benlavalley** [meteor/meteor#9660]
After updating from Meteor 1.6 to 1.6.1 it seems WebApp.connectHandlers functions don't seem to contain Meteor's <script> tag entry with it's primary JS payload when parsing the HTML they recieve.

I spent several hours today checking out what was going wrong - perhaps the result of [this change](https://github.com/meteor/meteor/commit/9a391d9b04dac40758c6f791db2b622505235aa8#diff-79c5e18978e1bfa64cbb9edb380f2920) or something like it regarding the webapp package?

It seems the handler can see the CSS boilerplate, but not the Javascript. 

This broke a really [fun and effective hack](https://github.com/benlavalley/lightspeed/blob/master/lightSpeed.js) I invented which made for literally instantaneous page loads when combined with some custom SSR.

**Comment by benlavalley** [comment]
Easily reproduced with this server-side code:
```
import { WebApp } from 'meteor/webapp';

WebApp.connectHandlers.use(function(req, res, next) {
  let originalWrite = res.write;
  res.write = function(chunk, encoding) {
	if(encoding === undefined && /^<!DOCTYPE html>/.test(chunk)) {
	  chunk = chunk.toString();
	  console.log('Response chunk is: ',chunk);
	}
	originalWrite.call(res, chunk, encoding);
  }
  next();
});
```
In 1.6.0.1, it will return:
 ```
I20180211-04:58:04.103(-5)? Response chunk is:  <!DOCTYPE html>
I20180211-04:58:04.103(-5)? <html>
I20180211-04:58:04.104(-5)? <head>
I20180211-04:58:04.104(-5)?   <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=1a165863f95fc2ba4d6af1034a1380b15db31f19">
I20180211-04:58:04.104(-5)? <title>webHandlerTest</title>
I20180211-04:58:04.104(-5)? 
I20180211-04:58:04.104(-5)? </head>
I20180211-04:58:04.105(-5)? <body>
I20180211-04:58:04.105(-5)? 
I20180211-04:58:04.105(-5)? 
I20180211-04:58:04.105(-5)? 
I20180211-04:58:04.105(-5)?   <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.6.0.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22development%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%22u9990g3z12e7.loyjzquyz71p%22%2C%22autoupdateVersion%22%3A%22e78b653083202e3e0d7327b32ce1afdbe0716493%22%2C%22autoupdateVersionRefreshable%22%3A%226cfb2372a511df667f4eaf83fb972282250a3080%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"))</script>
I20180211-04:58:04.105(-5)? 
I20180211-04:58:04.105(-5)?   <script type="text/javascript" src="/packages/meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a"></script>
I20180211-04:58:04.105(-5)?   <script type="text/javascript" src="/packages/meteor-base.js?hash=a4d07a6b394e56bbe6ccc773c95e7cdb3434960d"></script>
I20180211-04:58:04.105(-5)?   <script type="text/javascript" src="/packages/mobile-experience.js?hash=8ded3e69a3e367f321ab9a2b52e3ecdd2661a365"></script>
<more scripts here, cut for brevity>
I20180211-04:58:04.114(-5)? 
I20180211-04:58:04.114(-5)? 
I20180211-04:58:04.114(-5)? </body>
I20180211-04:58:04.115(-5)? </html>


```

In 1.6.1, it will return:
```
I20180211-05:04:39.693(-5)? Response chunk is:  <!DOCTYPE html>
I20180211-05:04:39.695(-5)? <html>
I20180211-05:04:39.695(-5)? <head>
I20180211-05:04:39.695(-5)?   <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=1a165863f95fc2ba4d6af1034a1380b15db31f19">
I20180211-05:04:39.695(-5)? <title>webHandlerTest</title>
I20180211-05:04:39.696(-5)? 
I20180211-05:04:39.696(-5)? </head>
I20180211-05:04:39.696(-5)? <body>
```

**Comment by hwillson** [comment]
These `WebApp` changes were intentional. You're not seeing the JS payload when using this approach because Meteor's web boilerplate is now loaded asynchronously, and isn't ready when your middleware fires. 

The good news is that there is now a `WebAppInternals.registerBoilerplateDataCallback` API that will allow you to register a callback, to manipulate boilerplate data, on each request (see https://github.com/meteor/meteor/commit/7ac873d0e129d83a5869e05a61cacc9f81ec133e). You could use this to replace your existing hack, by manipulating the JS and `body` within a defined callback:

```js
WebAppInternals.registerBoilerplateDataCallback('someKey', (request, data, arch) => {
  // `data.js` holds all of the referenced JS files, which you can then use, 
  // clear out, setup your window.onload, and add it to `data.body`
});
```

This way you're now using a supported API, instead of relying on the no longer supported (and now quite broken) `meteorhacks:inject-initial` 3rd party package. 

Closing for now since this isn't a bug (but if you want to see any of this changed, please consider opening a feature request over in http://github.com/meteor/meteor-feature-requests). Thanks!

**Comment by benlavalley** [comment]
Thanks @hwillson , I found this and was messing with it a bit yesterday. It seemed to provide more structure around the boilerplate and I wasn't sure if I would be able to add my little onload trick but I will be working on it :)
