### ISSUE TITLE
Issue building android app

### ISSUE THREAD

**Issue by upolymorph** [meteor/meteor#9661]
I am currently using meteor 1.6.1 and a project that was compiling with meteor 1.4 is not able to build an android app being stucked with the error message with building it using cordova and gradle:
ANDROID_HOME=/Users/arnaud/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
%% Running command: /Volumes/Atlas/dev/02-beamrocks/src/.meteor/local/cordova-build/platforms/android/gradlew cdvBuildRelease -b /Volumes/Atlas/dev/02-beamrocks/src/.meteor/local/cordova-build/platforms/android/build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
   Building Cordova app for Android          -
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for pdvnaqbg7za16k3dxusuk6cf (/Volumes/Atlas/dev/02-beamrocks/.gradle/caches/2.13/scripts-remapped/settings_aqwnw93598b6funfv04dirx2n/pdvnaqbg7za16k3dxusuk6cf/settings57408229).
> Could not open settings generic class cache for settings file '/Volumes/Atlas/dev/02-beamrocks/src/.meteor/local/cordova-build/platforms/android/settings.gradle' (/Volumes/Atlas/dev/02-beamrocks/.gradle/caches/2.13/scripts/pdvnaqbg7za16k3dxusuk6cf/settings/settings57408229).
   > java.nio.channels.OverlappingFileLockException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

It seems that it could cause by usage of gradle daemon but I can't find a way or a documentation on how to disable gradle daemon through meteor configuration file or use ant rather than gradle.
Could someone advise?
Thanks in advance

**Comment by hwillson** [comment]
Are you using a standalone version of Gradle? If not, can you try installing one? See the [Android prerequisites](https://guide.meteor.com/mobile.html#installing-prerequisites-android) section of the Guide for more details.

**Comment by upolymorph** [comment]
Yes I followed the android prerequisites, the issue seems to come from the latest Android SDK tools 26.1.1 where templates floder and thus the gradle wrappers is missing and that these tools seems to use totally differently the environment varaiables such as ANDROID_HOME ...

**Comment by eskan** [comment]
@upolymorph may be it's not related to this :
https://github.com/meteor/meteor/issues/9746
but there's issue with **com.android.support:support-v4:+** that matches with a beta version
adding this plugin is a way to get a stable gradle version
https://github.com/dpa99c/cordova-android-support-gradle-release
