### ISSUE TITLE
Galaxy, Upload existent database and images 

### ISSUE THREAD

**Issue by pedrofg** [meteor/meteor#9664]
Hello, I have an app deployed at Meteor Galaxy and I am trying to upload existent images to the server. Is there any way I could have access to the server file system? The idea here is to not have to upload each file again through the website since I already have the existent database connected to those files. Is there any way we could do the same as having an FTP server and just copy the files to the server folder?

**Comment by hwillson** [comment]
Issues here are reserved for bugs with the Meteor platform itself. Galaxy related questions should be asked using the Galaxy support option available through the Galaxy admin. 

As a quick answer though - no, you cannot get direct access using something like FTP/SFTP. There are several ways you can work around this (by using a Node based web accessible file manager for example), but your absolute best bet to handle uploads that will change regularly is to store them outside of Galaxy, and reference them accordingly (so store them using a database, something like Amazon S3, https://cloudinary.com, etc.). The reason for this is that [Galaxy file system based storage is temporary and limited](http://galaxy-guide.meteor.com/file-storage.html). 

For further help with this, please try posting on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Thanks!
