### ISSUE TITLE
1.6.1 apk location after build

### ISSUE THREAD

**Issue by carljdp** [meteor/meteor#9672]
Since we **upgraded** from 1.6.0.1 **to 1.6.1** , `android-release-unsigned.apk` is no longer copied from  *\<build-output-directory\>/android/project/build/outputs/apk* to the *\<build-output-directory\>/android* folder (like in previous meteor versions) as [documented here in the docs](https://guide.meteor.com/mobile.html#submitting-android)

**Tested on:**  
- Ubuntu 17.01  
- Kali GNU/Linux Rolling (4.14.0)  

**Expected behavior:**  
Expected to find release-unsigned.apk in *\<build-output-directory\>/android* after a successful build  

**Actual behavior:**
No *.apk file found in *\<build-output-directory\>/android* after a successful build  

**Reproduction recipe:** (on linux)
1. Clone `git clone https://github.com/carljdp/meteor-apk-location-bug.git && cd meteor-apk-location-bug`
1.  Build `meteor build ../build --architecture os.linux.x86_64 --directory --server=127.0.0.1:3000`
1. Inspect the build folder: `cd ../build/android && ls -a`

**Comment by jensdev** [comment]
I am also experiencing this issue. Please fix

**Comment by KoenLav** [comment]
Same issue here, we are using meteor-launch (https://github.com/NewSpring/meteor-launch) and it expects the APK to be there.

**Comment by macrozone** [comment]
my custom build scripts also failed and it took me some time to figure out what was going on. 

This is a breaking change and I am now wondering whether i should adapt my build scripts to use the new location 🤔

**Comment by davidecantini** [comment]
@macrozone That will definitely fix your issue (until the location might need to be changed again in the future, but that will surely be mentioned in the release notes)

**Comment by mg91** [comment]
Hi,
This video can be very helpful.
Check: https://youtu.be/lg6G52-guBw

**Comment by macrozone** [comment]
wow. meteor 1.8.1 with newest cordova managed once more to move the built apk! No wonder, that cordova has such a bad reputation. They just break stuff with every release for no reason.  Sorry for the rant, this is not meteor's fault, but cordovas...
