### ISSUE TITLE
1.6.0.1 -> 1.6.1, Client code ecmascript: Cannot find module 'core-js/modules/es7.string.pad-start'

### ISSUE THREAD

**Issue by thomasf1** [meteor/meteor#9673]
I´ve upgraded from 1.6.0.1 -> 1.6.1. Now the client/browser code seems completely broken, linkely related to Babel 7.

The first issue coming up in the Browser console is:
"Cannot find module 'core-js/modules/es7.string.pad-start" in the ecmascript runtime at

```javascript
// ECMAScript 2017 polyfills.
require("core-js/es7/array");
require("core-js/es7/object");
require("core-js/modules/es7.string.pad-start"); <-- here
require("core-js/modules/es7.string.pad-end");
```javascript

This prevents even the Meteor object being loaded / accessible via the console.

I´ve tried upgrading all packages and forcing a upgrade of the ecmascript and coffeescript packages, as well as removing some packages but no luck so far.

**Comment by thomasf1** [comment]
I´ve solved the issue, it was related to the package.json / NPM build and partly had to do with one of the npm packages requiring some Xcode tools not installed. Fixed that with 'xcode-select --install'

**Comment by bsbechtel** [comment]
I'm seeing the same issue. What was the problem you had with the package.json/NPM build? I ran the `xcode-select --install` command and didn't have any luck.
