### ISSUE TITLE
Error adding package mhagmajer:server-router on Windows

### ISSUE THREAD

**Issue by marcpmichel** [meteor/meteor#9675]
On Windows, trying to add the package crashes with the following error.
Works as expected on Linux and OSX.
Tested on a working Meteor 1.6.0.1 app we are working on 
and on a brand new Meteor 1.6.1 app .

The package maintainer asked me to open an issue here with the following comment: 
"That might be related some incorrect handling of file names on Windows by Meteor package manager.".

```
meteor add mhagmajer:server-router
C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\xxx\AppData\Local\Temp\mt-1l8591f.zq4xl\os\definitions\flow_v0.46.x\mhagmajer:server-router_v1.x.x.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.wrapper [as open] (C:\tools\fs\files.js:1564:35)
...
```

**Comment by michaelcerne** [comment]
Any updates?
