### ISSUE TITLE
Meteor is getting downloading every time even-though it is installed [ docker ] 

### ISSUE THREAD

**Issue by jeyanthimuthuram** [meteor/meteor#9683]
* ❗️ Bug? -> Yes

### Details:
I installed the meteor inside the docker using my custom Dockerfile the same way as ( https://github.com/abernix/meteord , https://github.com/abernix/meteord/blob/master/base/scripts/lib/install_meteor.sh#L3)  

It got installed fine, but whenever I move my app and try to do a `meteor -v` 

```
Step 3/11 : ADD . /home/test/xxxxxx
 ---> 0d3e4c3b5829
Step 4/11 : ENV METEOR_ALLOW_SUPERUSER true
 ---> Running in f486d0d683b9
 ---> 019eeaaf5029
Removing intermediate container f486d0d683b9
Step 5/11 : RUN cd /home/test/xxxxxx/        && sudo chmod -R 777 /home/test/xxxxxx         && meteor npm install         && mkdir /home/test/xxxxxx/out/          && meteor build --server-only --directory /home/test/xxxxx/out/
 ---> Running in abcfc021a11e
Downloading Meteor distribution
This is your first time using Meteor!
Installing a Meteor distribution in your home directory.

> bcrypt@1.0.3 install /home/test/xxxx/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/home/test/xxxxx/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> phantomjs-prebuilt@2.1.16 install /home/test/xxxxxx/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
```
here if you see the `step 5`, it is again getting installed by downloading ,which I feel time and bandwidth consuming , 

It would be better if there is a it can install from cache which I installed on top of docker already !

**Comment by hwillson** [comment]
Hi @jeyanthimuthuram - this isn't a bug, it's a feature request. Please consider moving this issue over to the http://github.com/meteor/meteor-feature-requests repo. Thanks!
