### ISSUE TITLE
Why does Meteor not throw errors in method calls?

### ISSUE THREAD

**Issue by morloy** [meteor/meteor#9684]
We use Sentry to report errors in our production code. However, the Meteor methods don't throw errors when they fail. Instead they call the weird `_debug` function and even deconstruct the `Error` object, removing valuable debug information.

Is there any explanation by the dev team about this choice of behavior?
If not, I would be very happy if you could the include some changes to make methods throw real errors, not some random debug messages: https://github.com/meteor/meteor/compare/devel...morloy:fix/throwMethodErrors

**Comment by mitar** [comment]
You mean on the client side?

I never use Meteor methods directly, but have a wrapping code which wraps all method calls and definitions. Similar to [validated method](https://github.com/meteor/validated-method). So you can handle then errors like you want and call any logging code.

**Comment by mitar** [comment]
But I do remember there being issues for being able to intercept those errors before. I agree that there should be a standard way to do so.

**Comment by morloy** [comment]
Yes, client side.

Meteor handles errors on methods internally (the `ddp-client` and `bindEnvirontment`). Thus there's no way for packages like `validated-method` to access the actual error object.

**Comment by mitar** [comment]
Ehm. Why don't you log method errors from server on the server itself?

You can wrap (with a library) all your method call on servers with try/catch and then log it, before rethrowing it to the client to show it to the client?

**Comment by morloy** [comment]
Server-side errors are not an issue. These get sanitized and sent to the client. The problem is that the client does not throw any errors. Instead there's only a not-so-informative message through `_debug()`.

**Comment by hwillson** [comment]
Hi @morloy - Meteor 1.6.2 will include some error handling changes (see https://github.com/meteor/meteor/pull/9654), but to continue the discussion on further changes, please move this issue over to the http://github.com/meteor/meteor-feature-requests repo. Issues here are reserved for bugs with Meteor core itself, and the current error handling infrastructure is working as designed. For a thorough explanation of why Method error handling works the way it works, see the Guide's [Method error handling](https://guide.meteor.com/methods.html#errors) section. Thanks!

**Comment by morloy** [comment]
@hwillson thanks for the hint to #9654. That's exactly the issue that I was describing here.
However, it only fixes the behavior if a callback is explicitly given to a method call.
