### ISSUE TITLE
accounts-password: verifying an email logs a user in even if there's no password set

### ISSUE THREAD

**Issue by anschutz** [meteor/meteor#9686]
One is automatically logged in after following an email verification link no matter if he has a password set or not.

**Steps to reproduce**
 - Create an account without a password on the server (`Accounts.createUser()`)
 - Request a verification email for the user you just created (`Accounts.sendVerificationEmail()`)
 - Follow the link in the email

**Expected behavior**
An error is thrown. E.g. "user has no password set"

**Actual behavior**
User is logged in without having to set a password.

The use case is inviting users to sign up with `Accounts.sendEnrollmentEmail()`. Those who expect an invitation sometimes fail to find enrollment emails and start desperately clicking around the login pages until they decide to "verify" their email. If they manage to verify their email (and immediately get logged in) before enrolling the account, they assume that the sign up process is complete. As a result those users don't have any means of logging back in once they log out (unless they request a new password, of course).

**Comment by hwillson** [comment]
Confirmed; great catch @anschutz - thanks!

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
