### ISSUE TITLE
Add 'meteor remove' command

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#9687]
Can we have a 'meteor remove' command to uninstall meteor in a clean way? I mean w\o manually deleting meteor folder.
For example when a new Meteor release comes out - I'd like to get rid of old Meteor version altogether to save space on disk.

**Comment by axelvaindal** [comment]
This seems like a feature request.
Meteor feature request are tracked in another repository and this issue is likely to be closed by a MDG member.
You should ask for this feature [here](https://github.com/meteor/meteor-feature-requests/issues) 🙂

**Comment by avalanche1** [comment]
https://github.com/meteor/meteor-feature-requests/issues/272
