### ISSUE TITLE
How to manipulate dynamically imported code (add instruments for code-coverage)

### ISSUE THREAD

**Issue by SimonSimCity** [meteor/meteor#9704]
In order to include dynamically imported code in the code-coverage, created by https://github.com/serut/meteor-coverage I need a hook where I can manipulate the code returned by the `dynamic-import` module.

A very easy way would be to do this on a server side by a hook that allows me to manipulate the code returned by this line: https://github.com/meteor/meteor/blob/e24eec2084ee37e2a27f75057b5ae596fdaf72b6/packages/dynamic-import/server.js#L72

Another suggestion by me would be to include code-coverage into the core of Meteor, since it's a so low-level thing ... I'd be happy to help implementing either.

**Comment by hwillson** [comment]
@SimonSimCity Would you mind moving this request over to the http://github.com/meteor/meteor-feature-requests repo? Issues here are reserved for Meteor bugs. Thanks!

**Comment by SimonSimCity** [comment]
True, thanks for the hint 😄
