### ISSUE TITLE
Mongo.Collection.{call,apply}(this, ...) breaks multi-level inheritance in browser

### ISSUE THREAD

**Issue by sprohaska** [meteor/meteor#9706]
<https://github.com/meteor/meteor/commit/b06a6af335427d57ac47963a6989ced482f5e5f9> breaks multi-level inheritance in the browser. The following code skips `A.constructor()` in the browser:

```javascript
import { Mongo } from 'meteor/mongo';

// delete Mongo.Collection.call;

class A extends Mongo.Collection {
    constructor() {
        console.log('A');
        super();
    }
}

class B extends A {
    constructor() {
        console.log('B');
        super();
    }
}

const b = new B();
```

It prints only `B`. When disabling the call hack with `delete Mongo.Collection.call`, the example correctly prints `B`, `A`.

A package where it matters is `vsivsi:job-collection`. The call hack breaks `class JobCollection extends share.JobCollectionBase` <https://github.com/vsivsi/meteor-job-collection/blob/master/src/client.coffee#L30>, where `JobCollectionBase extends Mongo.Collection` <https://github.com/vsivsi/meteor-job-collection/blob/master/src/shared.coffee#L81>. A workaround is:

```javascript
origCall = Mongo.Collection.call;
jobs = new JobCollection(...);
Mongo.Collection.call = origCall;
```

**Comment by sprohaska** [comment]
Thanks for the quick reply.

The issue does not appear in a fresh app, because it uses `mongo@1.4.4`, which includes the revert <https://github.com/meteor/meteor/commit/17eaa5bd6f9f4837c6c22001c30bfd65e5d28496> of the   `Mongo.Collection.{call,apply}(this, ...)` commit <https://github.com/meteor/meteor/commit/b06a6af335427d57ac47963a6989ced482f5e5f9>, which I was complaining about.

I was able to fix an existing app using `meteor update mongo` to upgrade to `mongo@1.4.4`. I previously only ran `meteor update --release 1.6.1`, which resulted in `mongo@1.4.2`.

My conclusion is that one should always explicitly upgrade package `mongo` when upgrading to 1.6.1, like:

```
meteor update --release 1.6.1
meteor update mongo
```

I think the issue can be closed.

**Comment by hwillson** [comment]
Thanks for the follow up @sprohaska - glad to hear the issue is resolved.
