### ISSUE TITLE
Meteor 1.6.1: meteorhacks/inject-data and abecks/meteor-inject-data don't work anymore

### ISSUE THREAD

**Issue by mhagmajer** [meteor/meteor#9708]
I created a bare Meteor 1.6.1 project with `meteor create test1` and added one of the commonly used inject data packages [meteorhacks:inject-data](https://github.com/meteorhacks/inject-data) or [staringatlights:inject-data](https://github.com/abecks/meteor-inject-data).

Then I put the following instructions to inject data in `server/main.js`:
```js
WebApp.connectHandlers.use((req, res, next) => {
  InjectData.pushData(res, 'some-key', { test: 1 });
  next();
});
```

`curl -s http://localhost:3000/ | head` gives the injected data as expected:
```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=1a165863f95fc2ba4d6af1034a1380b15db31f19">
<title>test1</title>

<script type="text/inject-data">%7B%22some-key%22%3A%7B%22test%22%3A1%7D%7D</script>
<script src="/packages/es5-shim/es5-shim-sham.js"></script>
</head>
<body>
```
However, when user agent is set to a Chrome browser, `curl -sH "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" http://localhost:3000/ | head` **doesn't return the injected data**:
```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=1a165863f95fc2ba4d6af1034a1380b15db31f19">
<title>test1</title>

</head>
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.6.1%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22development%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%22l3qhynei6twp.vb1oydzu9vnh%22%2C%22autoupdateVersion%22%3A%220cd629ff2d82cab72001dd91396665cc4c03bcf0%22%2C%22autoupdateVersionRefreshable%22%3A%22a5ab987170094da36a43546e9ce2ffb456656b4c%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"))</script>
```

Can anyone share thoughts on why that is?

**Comment by hwillson** [comment]
Hi @mhagmajer - unfortunately those packages haven't stayed up to date with `WebApp` API changes. Unless those packages are updated, I would recommend dropping them and using the [`WebAppInternals.registerBoilerplateDataCallback`](https://github.com/meteor/meteor/blob/b4690a2541fd104cbfba1c269a31755996e5855e/packages/webapp/webapp_server.js#L260) API instead. For more details, see https://github.com/meteor/meteor/issues/9660#issuecomment-365021532.
