### ISSUE TITLE
Meteor accounts-facebook Valid OAuth redirect URIs issue Facebook March update

### ISSUE THREAD

**Issue by jimmythigpen** [meteor/meteor#9713]
I'm using meter version 1.3.2.4

I wasn't sure where to post this issue, so please advise if this issue should go somewhere else.

Facebook has announced that Valid OAuth redirect URIs must be included for apps using their service starting in March.

"In March, we're making a security update to your app settings that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field below.This update comes in response to malicious activity we saw on our platform, and we want to protect your app or website by requiring a new strict mode for redirect URIs."

I am adding what is the correct OAuth redirect URI for my application http://myapp.com/_oauth/facebook?close

After adding this redirect URI I'm getting an error in the oauth popup when trying to login:

Not Logged In: You are not logged in. Please login and try again.

Any ideas here?

**Comment by hwillson** [comment]
Hi @jimmythigpen - this is the right place to report this. I haven't had a chance to look into this closely yet, but I'm highly skeptical of this code in the `oauth` package ...

https://github.com/meteor/meteor/blob/b4690a2541fd104cbfba1c269a31755996e5855e/packages/oauth/oauth_common.js#L5-L11

I'll aim to take a look hopefully later today (unless someone beats me to it!). Thanks!

**Comment by brianlukoff** [comment]
I had the same issue -- it seems to be fixed by giving Facebook a version of the redirect URI without the "?close" query string.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9713#issuecomment-369813451, please try removing the `?close` part of your redirect URI when configuring it with Facebook. Once upon a time Meteor accounts used this parameter, but it's no longer required. I've verified that removing the `?close` parameter works with Meteor 1.6.1, so I'll close this for now.

**Comment by VikR0001** [comment]
Something may have changed -- I could not log in via Facebook until my redirect url **did** contain `?close`.

**Comment by marsimeau** [comment]
Adding `?close` just fixed the issue for me too.

**Comment by VladimirDev93** [comment]
Adding the `?close` in the redirect URI fixed the issue for me. For some reason `/_oauth/facebook` was not valid, but `/_oauth/facebook?close` is valid. 

- Meteor 1.8.1
- accounts-facebook@1.3.2
- Facebook v3.2 API
