### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by yanickrochon** [meteor/meteor#9718]
Brand new project with Meteor 1.6.1; I have a single route, and inside this route I hide the loading backdrop with this code :

```js
$('.loader').addClass('hidden');
```
It works in development mode, however it fails in production

> ReferenceError: $ is not defined

# Reproduction

## main.js

```js
Meteor.startup(() => {
  console.log("*** LOADED");
  console.log($);
});
console.log("*** INIT");
console.log($);
```

> *** INIT
> Uncaught ReferenceError: $ is not defined
> *** LOADED
> Uncaught ReferenceError: $ is not defined

Start with `meteor run --production`

**Comment by elmarti** [comment]
Hi, it looks like jQuery is no longer bundled in by default; I just tried creating a new project, then running `meteor list` (list all packages) and jQuery isn't there. 

If I'm right then this could be remedied by running `meteor add jquery`.

**Comment by elmarti** [comment]
Output from running `meteor list`

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.0   # CSS minifier run for production mode
standard-minifier-js@2.3.1    # JS minifier run for production mode
es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
```

**Comment by hwillson** [comment]
As @elmarti mentioned, `jquery` is no longer included by default as a dependent package, for new projects. You can `meteor add jquery` if needed, or better yet use a more recent version of jquery from npm (`meteor npm install --save jquery`). For more details, see https://github.com/meteor/meteor/pull/8388. Thanks!

**Comment by yanickrochon** [comment]
I did the latter. Thanks.
