### ISSUE TITLE
Cordova error: Failed to fetch plugin

### ISSUE THREAD

**Issue by miranos** [meteor/meteor#9722]
Hi,

When i try to build an Android application with meteor:
meteor build ../android --mobile-settings settings.json --server=https://m.domain.com

I receive this error log:
```

Subproject Path: CordovaLibt                 \
%% support for subdirectories is deprecated and will be removed in Cordova@7
=> Errors executing Cordova commands:

   While adding plugin
   https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab0405
ae9d3521bd4037c5a37
   to Cordova project:
   Cordova error: Failed to fetch plugin
   https://github.com/meteor/cordova-plugin-googleplus.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: C:\Program Files (x86)\Git\cmd\git.exe: Command failed with exit
   code 128 Error output:
   Cloning into 'C:\Users\xxx\AppData\Local\Temp\git\1520370471200'...
   fatal: unable to access
   'https://github.com/meteor/cordova-plugin-googleplus.git/':
   error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol
   version
   (If the error message contains suggestions for a fix, note that this
   may not apply to the Meteor integration. You can try running again with
   the --verbose option to help diagnose the issue.)



```

My meteor version: 1.5.1

Web application generated correctly !

Thank you

**Comment by hwillson** [comment]
Can you try with Meteor 1.6.1 and post back if that helps? If not, any chance you could provide a small runnable reproduction that shows this issue?

**Comment by miranos** [comment]
I am under Windows, when i try to update to 1.6.1 it take very long time without finishing the installation !

So, i just reinstalled meteor 1.5.1, rested the prodject, remove node_modules folder, and when i try again, i have the same issue !

I can't provide the project file very sorry for that !

Is there a way that i can remove google plus plugin from the project and retry again ?

I just tested with:
`meteor remove cordova:cordova-plugin-googleplus`

I receive:
`Cordova plugin cordova-plugin-googleplus is not in this project.`

Is there anyway to bypass this problem please ?

**Comment by hwillson** [comment]
@miranos Which version of the Windows git client are you using? You might want to update to the latest version, to see if that helps (reference: https://github.com/meteor/meteor/issues/9247).

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/meteor/meteor/issues/9722#issuecomment-372334873, so closing for now. Thanks!
