### ISSUE TITLE
[1.6.2 beta 12] Cannot read property 'Dependency' of undefined

### ISSUE THREAD

**Issue by tcastelli** [meteor/meteor#9727]
I just tried to run a project using simple schema package with the latest beta and found out there's an error when booting and it won't go further.
````
TypeError: Cannot read property 'Dependency' of undefined
W20180308-10:08:45.955(1)? (STDERR)     at packages/aldeed_simple-schema.js:1542:45
W20180308-10:08:45.955(1)? (STDERR)     at packages/aldeed_simple-schema.js:2160:4
W20180308-10:08:45.955(1)? (STDERR)     at packages/aldeed_simple-schema.js:3128:3
````
Looking at the file to blame, this is the code that seems to be looking for Dependency
````
var Deps = Package.tracker.Deps;
....
SimpleSchema._depsGlobalMessages = new Deps.Dependency();
````

So i'm guessing maybe a change on tracker removed the old Deps naming context?

UPDATE:
Looking through last commits in the tracker package I've seen exactly what I was guessing :|
#9611 
I will try to open an issue at simple-schema repo and hope @aldeed can do a quick update :)

**Comment by aldeed** [comment]
@tcastelli Switch to the NPM package. 😉 

But yeah, this can be closed in favor of https://github.com/aldeed/meteor-simple-schema/issues/730

**Comment by aldeed** [comment]
Although I will point out, @benjamn, that this should have been a 2.0.0 release of the Tracker package since you removed deprecations.

**Comment by tcastelli** [comment]
I'll close this, as you suggested in favor of aldeed/meteor-simple-schema#730
