### ISSUE TITLE
[cordova]  how to include resource-file

### ISSUE THREAD

**Issue by eskan** [meteor/meteor#9729]
Hi ,
is there a way to include resource files from **mobile-config.js** ? that will be converted in cordova config.xml like this

```
<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```
or
```
<platform name="ios">
  <resource-file src="GoogleService-Info.plist" />
</platform>
```
Those files are needed by cordova plugins that use Google Service like **phonegap-plugin-push**

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md
Regards,

**Comment by hwillson** [comment]
GitHub issues here are reserved for bugs with the Meteor platform itself. For usage questions, please try reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Thanks!

**Comment by eskan** [comment]
@hwillson .. this issue was badly written  .. may you please re-open it.

**Comment by hwillson** [comment]
Hmm - I'm not quite seeing why this should be re-opened here @eskan? It sounds like you're asking a usage question, not reporting a Meteor bug. GitHub issues here are for bugs only. If you are reporting a bug, please add clarification here in the issue comments, and we'll decide if this issue should be re-opened. As it stands currently however, this sounds like a question (and should be asked in the forums / SO). If it's a feature request, then it should go over in http://github.com/meteor/meteor-feature-requests. Thanks!

**Comment by eskan** [comment]
oups !! @hwillson .. you're right it's more a feature request .. 1 sorry and 2 thanks
