### ISSUE TITLE
This regex may be stucked by input strings.

### ISSUE THREAD

**Issue by 2bdenny** [meteor/meteor#9731]
https://github.com/meteor/meteor/blob/74b8c595b7097f4a96139999b2150958703541b3/packages/markdown/showdown.js#L415

We tested all regexes in the project and found this regex may be stucked by input strings like: `\n\n<!--\n\n<!--------<\n\n<!------------------------------------->]Vx0\n\n\n------!!<\n\n\n\n]-----<!]Vx0\n\n-------<!`

**Comment by hwillson** [comment]
Thanks @2bdenny - this is known. We're currently considering deprecating this (and the `showdown`) package from core.
