### ISSUE TITLE
Socket.io with uWS instead SockJS

### ISSUE THREAD

**Issue by Maxpain177** [meteor/meteor#9735]
I propose to change `SockJS` with `Socket.io` (for long polling as fallback) + `UWS` (uWebSockets, which is faster, than any JavaScript WebSocket implementation, because it's written as C++ module, with built-in support `permessage-deflate`).

I think this will give a big performance boost for meteor server and less CPU consumption.

**Comment by hwillson** [comment]
Thanks @Maxpain177 - this is already being tracked here: https://github.com/meteor/meteor-feature-requests/issues/41
