### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by psharneja** [meteor/meteor#9742]
Installed Meteor and it gives me this error, tried reinstalling many a times but still the same
C:\Users\pr293504\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\tools\fs\files.js:59
var useParsedSourceMap = function (pathForSourceMap) {
                                  ^

RangeError: Maximum call stack size exceeded
PS C:\WINDOWS\system32> meteor --version
C:\Users\pr293504\node_modules\underscore\underscore.js:1267
  _.has = function(obj, key) {
                  ^

RangeError: Maximum call stack size exceeded

- [ 1.6.1/ Latest/ Chocolatey shows 0.0.2] The version of Meteor showing the problem.
- [ Showing error since first install of this version] The last version of Meteor where the problem did _not_ occur, if applicable.
- [ Win 10x64 Version 1709] The operating system you're running Meteor on

**Comment by sunpreetsingh19** [comment]
There's a pretty good issue thread about this [here]( https://github.com/meteor/meteor/issues/7896). The most effective solution seems to be outlined in this [comment](https://github.com/meteor/meteor/issues/7896#issuecomment-292659481).

**Comment by psharneja** [comment]
sadly, even that didn't work sunpreet... it's been 2 days since i'm trying different ways out, above is one of those....

**Comment by psharneja** [comment]
reinstalled meteor in other(D) drive, its working now.
