### ISSUE TITLE
Version 1.6.1 - Node 8.10  - segmentation fault (core dumped)

### ISSUE THREAD

**Issue by B-Stefan** [meteor/meteor#9745]
## This bug report should include:
- [x] The version of Meteor showing the problem. 
1.6.1
- [x] The operating system you're running Meteor on. 
Docker 17.12.0 - Ubuntu Ubuntu 16.10 (4.8.0)
- [x] The expected behavior.
The application should run without errors 
- [x] The actual behavior.
Application randomly restart with the error message:  segmentation fault (core dumped) 
- [x] A **simple** reproduction!

1. Use Meteor 1.6.1
2. Create a docker image that contains the compiled version of your application with 
``` 
FROM node:8
``` 
3. Put some load on your application 
4. After 2-10 minutes you will get this error 

Quick fix: Just change from `node:8` to `node:8.9.4` in your dockerfile

**Comment by abernix** [comment]
Your issue here is slightly contradicting because the body of the issue references Node 8, but the subject references Node 9.  Even still, I think your problem is related to #9725 and, yes, it seems that it would be best to deploy with Node 8.9.4 until we figure it out.

**Comment by B-Stefan** [comment]
Sorry, my mistake. 

I modified the title to the correct node version. I didn't found this pull-request during my search. 
But it seems to be the same problem. 

Thanks for the quick response!
