### ISSUE TITLE
Widget app can’t use dynamic import since 1.6.1

### ISSUE THREAD

**Issue by joaomframos** [meteor/meteor#9747]
In order to allow us to load our widget into our clients’ pages, we load all scripts that would be available on the app’s default url and inject them into a srcless iframe.
Thanks to environment variables such as DDP_DEFAULT_CONNECTION_URL, we are able to establish a DDP connection from our clients’ webpages to our servers.

We have recently began updating to Meteor 1.6.1 (from 1.6) and we are now having issues due to the changes on dynamic-imports to be processed via HTTP.

The main problem is that the requests are now made to the host location of the page where the widget was injected instead of where our servers are running.

After thorough analysis, we realized that the issue can be pinpointed to https://github.com/meteor/meteor/commit/4aeb453c7b0a0a9556a11ea1928e63ab11302ef4#diff-9101f5ff2815f508b49f8c7dbdc85299

We do understand the reasoning behind this change but it doesn’t suit our use case. Given the fact that we are also setting ROOT_URL, the Meteor.absoluteUrl() approach would be working for us.

Would you please consider providing us with a setting that allows us to toggle the way that url is built? This way more use cases would be covered.

Unless an alternative as the one previously suggested arises, we are stuck on Meteor 1.6.0.1 and will not be able to upgrade going forward.

**Comment by hwillson** [comment]
Thanks @joaomframos - you bring up a fair point. While the changes made are more helpful in a lot of cases, they do reduce some flexibility. We'll discuss this further and post back shortly.

**Comment by joaomframos** [comment]
@hwillson any updates on the issue ?

**Comment by joaomframos** [comment]
It has been close to two months already and yet no updates. What is the plan going forward?

@hwillson Recently I also discovered that this issue also prevents every app that uses ROOT_URL from using dynamic imports.

Is there even a way of updating meteor but downgrading dynamic-imports back to 0.2.0 ?
I have already tried the standard version selection on .meteor/packages and even METEOR_OFFLINE_CATALOG but the package is always autoupdated on the app start to 0.3.0.

Plus, there's also an issue with 0.2.0 as it's loading the sourcemaps from location.host aswell which leads to fail request.

**Comment by benjamn** [comment]
I believe this should be fixed if you run `meteor update --release 1.7-rc.8`, thanks to these commits:
* Set default `Meteor.absoluteUrl` `ROOT_URL` from `window.location` (5f131ffe3bfeecff33bb3ab91145d6d1abcab563)
* Use `Meteor.absoluteUrl` again in dynamic-import `fetchMissing` function (3b77bb51973cfbd98488a7203fc6d87c5c871a01)

@joaomframos Can you confirm that dynamic `import()` works for your app with `1.7-rc.8`? I suspect the source maps issue will not be fixed (yet), but dynamic imports should work now.

**Comment by joaomframos** [comment]
The dynamic import requests now reach the server but fail to be processed.
Based on Devtools network the requested is made with POST as the request method but once it reaches the server, the request says that the method is OPTIONS.


`W20180513-02:12:18.446(1)? (STDERR) (node:12850) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: 'OPTIONS' === 'POST'
W20180513-02:12:18.446(1)? (STDERR)     at middleware (packages/dynamic-import.js:84:10)
W20180513-02:12:18.447(1)? (STDERR)     at /home/jr/.meteor/packages/promise/.0.11.0-rc17.8.1h94ih6.j7sy++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180513-02:12:18.447(1)? (STDERR) (node:12850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
W20180513-02:12:18.447(1)? (STDERR) (node:12850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any ideas?

**Comment by benjamn** [comment]
This was news to me (🏳️‍🌈💫), but the `OPTIONS` request is a [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) sent when the page URL and the requested URL have a different origin. Problems related to dynamic `import()` and CORS are being tracked in this issue: https://github.com/meteor/meteor/issues/9888. The good news is that this should be fixed in `1.7.-rc.9` (out soon).

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-rc.9`.

**Comment by joaomframos** [comment]
I noticed it was out and was already testing.
Wanted to confirm what I thought and indeed it doesn't work due to this commit.

https://github.com/meteor/meteor/commit/8566c2ce24026a46ea1ad56cd1d3f9156332e05c

Notice that we are pretty much back on the first stage.

In this case, location is always defined. I am using the app inside a sourceless iframe so the location is inherited from the parent window and therefore my request is being made towards the page in which we injected the widget.

**Comment by joaomframos** [comment]
Exactly the same as the main document's window.

This is the result while debugging inside dynamic-import.js, and the location variable content stringified:
"{"href":"http://localhost:1337/","ancestorOrigins":{"0":"http://localhost:1337"},"origin":"http://localhost:1337","protocol":"http:","host":"localhost:1337","hostname":"localhost","port":"1337","pathname":"/","search":"","hash":""}"

Meanwhile if I do window.frameElement.ownerDocument.defaultView.location to access the main document window's location I have this:

"{"href":"http://localhost:1337/","ancestorOrigins":{},"origin":"http://localhost:1337","protocol":"http:","host":"localhost:1337","hostname":"localhost","port":"1337","pathname":"/","search":"","hash":""}"

**Comment by benjamn** [comment]
Please feel free to close this issue whenever you have a moment to confirm that `meteor update --release 1.7-rc.10` fixes the problem.

**Comment by joaomframos** [comment]
Can confirm that dynamic imports are working.
Sourcemaps still remain a problem but we can do workaround that.
Thanks !
