### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by sandeep9177** [meteor/meteor#9749]
C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

RangeError: Maximum call stack size exceeded

How can i slove this problem

**Comment by hwillson** [comment]
There are several possible reasons for this error. Have you tried searching through [closed issues](https://github.com/meteor/meteor/issues?q=is%3Aissue+is%3Aclosed) for similar problems and their solutions? For example, have you tried the steps outlined in https://github.com/meteor/meteor/issues/7896#issuecomment-292659481 to see if that helps? Without more specific troubleshooting details (like a small runnable reproduction that demonstrates this problem), there isn't much we can do to help here. If you can provide additional information that will help with troubleshooting, we'll be happy to re-open this issue. Thanks!
