### ISSUE TITLE
asynchronous code

### ISSUE THREAD

**Issue by yashvadhvani** [meteor/meteor#9754]
The issue related to Asynchronous code is a huge bug here i am making an web application on blockchain using  web3 and the Asynchronous methods returning undefined how to make them return something as i tried promises and async await everything failed please reply as soon as possible here is my code 
function storage() {
    var web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:8545"));
       
    web3.personal.unlockAccount(web3.eth.accounts[0], '', 1000000);
    
    const input = fs.readFileSync('/home/yash/Desktop/Ipfsdone/server/Files/DataStoreContract.sol');
    const output = solc.compile(input.toString(), 1);
    const bytecode = output.contracts[':DataTransfer'].bytecode;
    const abi = JSON.parse(output.contracts[':DataTransfer'].interface);
    var gasEstimate = web3.eth.estimateGas({ data: '0x' + bytecode });
    const contract = web3.eth.contract(abi);
    let addr;
    
    
        contract.new({ data: '0x' + bytecode, from: web3.eth.coinbase, gas: gasEstimate }, (err, res) => {
            if (err) {
                   return err;
            } else {
                    if (res.address) {
                           
                            let data={'address': res.address, 'abi': abi};
                            jsonfile.writeFileSync('/home/yash/Desktop/Ipfsdone/server/Files/ContractInformation.json',data,{spaces: 2, EOL: '\r\n'}, function (err) {
                                    if (err) {
                                        return console.log(err);
                                    }
                                    console.log("The file was saved!");
                                }); 
                                
                            return res.address;
                    }
                }
       
    });
returning this to another function is returning undefined but when you log this here it works fine

**Comment by benjamn** [comment]
I'm guessing `jsonfile.writeFileSync` doesn't actually take a callback function, and never calls it if you do provide one.

**Comment by yashvadhvani** [comment]
actully that is not my issue i want this function to return the return value but it returns undefined so the reading and writing of file is not an issue sir
