### ISSUE TITLE
1.6.1 SSR import css in component

### ISSUE THREAD

**Issue by Blurri** [meteor/meteor#9758]
we try to to setup a meteor 1.6.1 app with server side rendering, now we get a unexpected token error when we try to load a css file from a node module in a component like this.

``` import 'slick-carousel/slick/slick-theme.css';
import ‘slick-carousel/slick/slick.css'
```

error: 
```
xxx/webapp/node_modules/slick-carousel/slick/slick-theme.css:1
(function (exports, require, module, __filename, __dirname) { @charset 'UTF-8';
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at npmRequire (xxx/webapp/.meteor/local/build/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:697:18)
    at fileEvaluate (packages/modules-runtime.js:342:20)
    at require (packages/modules-runtime.js:238:16)
    at Swiper.js (imports/ui/core/components/Swiper.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at ImageList.js (imports/ui/analyze/components/ImageList.js:1:265)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at ImageList.js (imports/ui/analyze/containers/ImageList.js:1:348)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

is it not possible to do this with ssr? do I need to copy the css files into the project ?

**Comment by hwillson** [comment]
@Blurri Any chance you could provide a small runnable reproduction that shows this happening?

**Comment by Minivera** [comment]
I can also reproduce the issue on any application I work on that uses React ssr and Meteor.

The only fix I found is to wrap the css import in `Meteor.isClient`, for example;

```
if (Meteor.isClient)
{
	import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';
}
```

But this make all styles in the application flicker on first load as they aren't applied when rendering on the server.

I can try to build a demo of what is happening if needed, this is a very annoying issue.

**Comment by faburem** [comment]
This is in fact quite easy to reproduce and will affect anybody trying to use SSR with a CSS framework.
Here is how I reproduced it using [bulma](bulma.io) as an example:

1. meteor create ssr-example
2. meteor npm i bulma
3. meteor add server-render
4. in server/main.js add the following:
`import { onPageLoad } from 'meteor/server-render'`
`   onPageLoad((sink) => { `
`     import('bulma/css/bulma.css').then((bulma) => {`
``       sink.appendToHead(`<style>${bulma.default}</style>`);``
`       sink.appendToBody('<button class="button is-primary">Bulma button</button>')`
`     })`
`   })`
5. open localhost:3000 in your browser

=> error thrown in the server console
`UnhandledPromiseRejectionWarning: ~/ssr-example/node_modules/bulma/css/bulma.css:2`
`@-webkit-keyframes spinAround {`

I think most devs would assume this to work in an SSR scenario.

**Comment by antoninadert** [comment]
Hello there, 

Any update on this? Will we be able to import CSS files and interpret them server-side before serving them to the client using server-render package ?

Right now I need to put my CSS into the `both` folder so that it will load both on client and server, but there is no way to attach the CSS to a specific React component by doing so

**Comment by Ezerskaya** [comment]
@Minivera Hello, please, tell about how you fix your problem with "But this make all styles in the application flicker on the first load as they aren't applied when rendering on the server."

**Comment by Minivera** [comment]
I changed job since and I am not using meteor anymore, but I still remember the solution I used at the time. My solution was to get the css file from node_modules and copy the content over to my scss files. Very dirty solution, but I needed to get going fast and it worked for what I needed.

**Comment by Ezerskaya** [comment]
@Minivera thank you, so much for your answer!

**Comment by antoninadert** [comment]
I don't believe this has been solved properly and should still be in the roadmap I believe it has not been solved. Any update on this ?

**Comment by filipenevola** [comment]
Hi @antoninadert , I just labeled as `confirmed` so stale bot is going to ignore it.

Can you add this to the SSR documentation item in the Roadmap.md? So we can double check it when writing this new documentation (cc @CaptainN)

**Comment by CaptainN** [comment]
I haven't seen this, because I work around this by default. When you include css using the ES import method, changes to CSS cause full application rebuild (during development). If you import it instead from a `main.css` file in the client folder, you get instant refresh, and side step this issue. The only down side is that you don't get integrated code splitting (though I'm not sure how well that works anyway), but I haven't found that to be a problem.

I know that doesn't answer the issue at hand, but I wanted to offer something for possible inclusion in documentation. To fix this, the CSS bundler in meteor should probably be modified to support server rendering. It would probably involved setting up a callback model similar to what `staringatlights:fast-render` does.

**Comment by far1s** [comment]
It would be really great if we could put this into the Roadmap @filipenevola. The meteor CSS bundler needs to get an option to ignore CSS imports (see https://github.com/cherrry/ignore-loader). Even if you work around this issue with the solution provided by @CaptainN (by loading all your CSS into the main.css file), you will still have that problem as soon as you import 3rd party components that import CSS. This makes SSR not usable for our app.

**Comment by filipenevola** [comment]
Hi @far1s are you willing to write a PR for this? I would be glad to review and merge.

**Comment by macrozone** [comment]
revisiting an older meteor project i am surprised to learn that this issue still is unsolved. since meteor does not use webpack and implements bundling itself, this issue here should be solved by the core-team and not by the community. just my 2 cents.

**Comment by Saeed-Bahrami** [comment]
It has been a year since this issue was opened.
Has anyone really addressed this important issue?
Maybe that's why so many people can't use meteor .

**Comment by Saeed-Bahrami** [comment]
@filipenevola @CaptainN @hwillson @macrozone @Blurri 

and i talk about this in forums : 

[css-files-in-meteor-react-ssr](https://forums.meteor.com/t/css-files-in-meteor-react-ssr/54012)

**Please Guide us .**

**Comment by eugle** [comment]
Now in 2021, is babel-plugin-import not available in meteor? Is this a problem that can't be solved and can only be used like this
