### ISSUE TITLE
Trying to upgrade to 1.6.2-beta.13 fails on Mac osx

### ISSUE THREAD

**Issue by SaniMusic** [meteor/meteor#9759]
Running:
$meteor update --release 1.6.2-beta.13

Returns:
This project uses Meteor 1.6.2-beta.13, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@1.6.1 to pin this app to the newest compatible release.

Maybe I'm missing something?

Mac osx high sierra
node v8.7.0
npm 5.4.2

**Comment by benjamn** [comment]
That can happen if you try updating before the new version of `meteor-tool` is fully published. Try again in a few minutes (or now)?

**Comment by SaniMusic** [comment]
hehe :) 

Same issue.. maybe takes a bit longer?

**Comment by benjamn** [comment]
Try running `meteor refresh` to update the package database? Sometimes that helps…

**Comment by SaniMusic** [comment]
Worked! Thanks a lot! :)
