### ISSUE TITLE
Issue in Meteor app creation

### ISSUE THREAD

**Issue by Vijaypalamani** [meteor/meteor#9766]
You can't create a Meteor project inside another Meteor project.

C:\Windows\system32>meteor create myapp1
C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\Windows\system32\cmd.exe /c C:\Users\DELL\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install --production=false
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2018-03-23T15_38_43_652Z-debug.log
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2018-03-23T15_38_43_652Z-debug.log

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:36:20
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:801:36)
    at C:\tools\cli\main.js:1523:15

How to resolve this issue

**Comment by benjamn** [comment]
You need to install `git.exe` on your system globally, since npm now depends on it: https://git-scm.com/download/win

**Comment by Vijaypalamani** [comment]
please provide the after the installation git.exe

**Comment by Vijaypalamani** [comment]
Benjamn,

please provide the after the installation git.exe

**Comment by benjamn** [comment]
Either remove the application directory and rerun `meteor create ...` or just `cd` into to application directory and rerun `meteor npm install`.

I'm happy to help because these are relatively easy questions, but in the future please just read the error messages and try doing what they suggest. ✌️

**Comment by Vijaypalamani** [comment]
resolved it now thx
