### ISSUE TITLE
Install fail on OS X with meteor 1.6.1

### ISSUE THREAD

**Issue by Andrew-Au** [meteor/meteor#9770]
OS X 10.12.6

Had previous meteor install (1.4 or 1.5).  Had various issues after updating.  Went for clean install.
Removed:
- ~/bin/meteor
- /usr/local/bin/meteor
- ~/.meteor

Downloaded new version of meteor: (v1.6.1)

> % curl https://install.meteor.com/ | sh

Created new project:

> % meteor create analytics
> /Users/awhite/.meteor/packages/meteor-tool/.1.6.1.194wnfx.1kqp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
>       throw error;
>       ^
> 
> Error: Error: Could not install npm dependencies for test-packages: Command failed: /Users/awhite/.meteor/packages/meteor-tool/.1.6.1.194wnfx.1kqp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm install --production=false
> npm ERR! Cannot read property 'match' of undefined
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/awhite/.npm/_logs/2018-03-26T06_09_27_412Z-debug.log
> npm ERR! Cannot read property 'match' of undefined
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/awhite/.npm/_logs/2018-03-26T06_09_27_412Z-debug.log
> 
>     at Object.error (/tools/utils/buildmessage.js:430:11)
>     at /tools/cli/default-npm-deps.js:36:20
>     at /tools/utils/buildmessage.js:334:18
>     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at /tools/utils/buildmessage.js:333:36
>     at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
>     at Object.install (/tools/cli/default-npm-deps.js:27:27)
>     at Command.func (/tools/cli/commands.js:801:36)
>     at /tools/cli/main.js:1523:15
> zsh: exit 1     meteor create analytics
> 

Tried this several times with same result.

[2018-03-26T05_43_25_850Z-debug.log](https://github.com/meteor/meteor/files/1846485/2018-03-26T05_43_25_850Z-debug.log)

For comparison, 1.5.4.1 works:

> % meteor create analytics --release 1.5.4.1
> Created a new Meteor app in 'analytics'.                                           
> 
> To run your new app:                          
>   cd analytics                                
>   meteor                                      
>                                               
> If you are new to Meteor, try some of the learning resources here:
>   https://www.meteor.com/tutorials            
>                                               
> meteor create --bare to create an empty app.  
> meteor create --full to create a scaffolded app.
>

**Comment by Andrew-Au** [comment]
1.6.0.1 failed with the same error.

**Comment by paulincai** [comment]
Hi there, just an idea. Did you update babel?

How about you remove everything related to babel and add these in package.json:
`"@babel/core": "^7.0.0-beta.42",
    "@babel/runtime": "^7.0.0-beta.42"`
Then if you use plugins migrate them to 7 :
`"@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.42",`
    `"@babel/plugin-transform-runtime": "^7.0.0-beta.42",`
    `"@babel/preset-env": "^7.0.0-beta.42",`
   ` "@babel/preset-react": "^7.0.0-beta.42"`

**Comment by hwillson** [comment]
First run

```bash
meteor npm cache verify
```

then try to create a new app. If that doesn't work, try running

```bash
meteor npm cache clean --force
```

You shouldn't have to manually clear the cache with npm 5.x, but it's worth a shot.

Interestingly enough, whatever is happening has exposed a bug in the version of the [`pacote`](https://github.com/meteor/pacote) package Meteor is using. We're using a forked version of 7.0.2, which has the following:

https://github.com/zkat/pacote/blob/fd3d7e272c5de001295271a3747d2fac0422a17a/extract.js#L46

Based on the error you're seeing, assuming that `err.code` exists is not a safe assumption. I've checked upstream and this code block has been updated, so we should consider rebasing our fork against a newer `pacote` version.

**Comment by Andrew-Au** [comment]
Cache verify succeeded:
> % meteor npm cache verify
> Cache verified and compressed (~/.npm/_cacache):
> Content verified: 161 (2812517 bytes)
> Index entries: 239
> Finished in 0.521s

Same error occurred.  Force cleaned cache, same error occurred.

Tried removing both .meteor and .npm and then re-running 'meteor create myapp'.  Meteor distro downloaded and then same error occurred.

Is there a guide somewhere how to get a completely clean install?  The act of running Meteor seems to generate a number of dot-files.  I don't know if it will make a difference but if I can get a clean slate it will reduce the possibility that this is a dirty config problem.

**Comment by nethermead** [comment]
If you're an admin on your mac, you could try creating a new OS X user which will have a clean home directory.

**Comment by eskan** [comment]
OSX 10.13.3
I can't reproduce this

**Comment by hwillson** [comment]
Regarding https://github.com/meteor/meteor/issues/9770#issuecomment-376249754, we're using version 7.0.2 of the forked `pacote` package to line up with the version npm 5.6.0 expects. When we update to npm >= 5.8.0, we'll update to `pacote` >= 7.6.1, which has a fix for the error handling bug (anything after `pacote` version 7.4.0 has the fix).

**Comment by Andrew-Au** [comment]
Tried with a clean (unprivileged) account.  "meteor create myapp" worked.

So there's something in my work environment that causes the error.  However, it ...
1. is not inside .meteor or .npm (since deleting them completely makes no difference)
1. does not affect meteor version 5, only version 6

Stuff to note that might or might not be relevant:
* I have an empty ~/.cordova/lib
* I have a ~/.meteorsession (last updated Dec 2015)
* I'm using zsh rather than bash
* something in ~/Library ?

Is it worth trying deleting .cordova and .meteorsession and retry-ing?

**Comment by bosung90** [comment]
Having same problem on meteor 1.6.1.1 windows 10

**Comment by pkl6612** [comment]
In the new environment, there are the same mistakes error

**Comment by dbranizor** [comment]
Got the same error with latest version of Meteor on Windows 10. Had to delete the node_modules folder and run yarn install vs the meteor npm intall commands.
