### ISSUE TITLE
NODE_ENV replaced on build for web browser bundle

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#9779]
Using Meteor 1.6.0.1 running on Ubuntu (for dev and production)

I have a line of code `const env = process.env.NODE_ENV == "development" ? "production" : process.env.NODE_ENV` - so in my development environment I can filter some data pretending to be production, but in my staging/production env - it uses the correct filter. 

After deploying to my staging environment, the generated code looks like this (paraphrased)

`env = "production"`

However, typing `process.env.NODE_ENV` into the console on the browser in staging gives "staging" which is what I would expect. 

This even happens if I do `env = eval('process.env.NODE_ENV == "development" ? "production" : process.env.NODE_ENV')`

To avoid this behaviour, I need to do 

    str = "process.....";
    if(someCondition) str = "";
    env = eval(str);

I have seen this babel plugin: https://www.npmjs.com/package/babel-plugin-transform-node-env-inline but I'm not sure if Meteor uses it, or how to disable it if it does

**Comment by znewsham** [comment]
Hi @hwillson I'm 100% sure that its set to staging, but its set to staging at runtime, NOT at build time. If I run `process.env.NODE_ENV` in a chrome console, I get `staging`.

Also, I think I mislead you a little - the bug IS on the client side. I think you've identified the spot that the "bug" exists, I guess we (and maybe others too?) dont often utilise `process.env.NODE_ENV` on the client, and as such this doesn't come up often

**Comment by Rongky** [comment]
Yes. I confirm this is happening. So instead of using process.env.NODE_ENV in the client side, I have opted in setting the node_env inside the settings.json files (dev, staging & prod) which is being read by mup during deployment. And getting the node_env thru Meteor.settings.public.node_env, the results are accurate.

**Comment by brookback** [comment]
We're also seeing this exact bug:

- `process.env.NODE_ENV` is `testing` when running in JS console
- Actual value of `process.env.NODE_ENV` in the code is inlined to `production`

**Comment by awatson1978** [comment]
We're also experiencing this issue.  My hunch is that it's simply a regression in one of the commonly used packages.  Here are our packages we're currently using and able to replicate the issue with:

```
meteor-base@1.4.0
ecmascript@0.12.3
es5-shim@4.8.0
check@1.3.1
tracker@1.2.0
session@1.2.0
email
underscore@1.0.10
momentjs:moment
react-meteor-data@0.2.15
less@2.8.0
mongo@1.6.0
aldeed:collection2@3.0.0
dburles:collection-helpers
reywood:publish-composite
mdg:validated-method
mdg:validation-error
dburles:mongo-collection-instances
browser-policy@1.1.0
audit-argument-checks@1.0.7
dynamic-import@0.5.0
universe:i18n
alanning:roles
accounts-base@1.4.3
accounts-password@1.5.1
accounts-ui@1.3.1
crosswalk@1.7.1
mobile-experience@1.0.5
chriswessels:hammer
juliancwirko:postcss@1.0.0-beta.11
standard-minifier-js@2.4.0
ddp-rate-limiter@1.0.7
simple:json-routes
simple:dev-error-overlay
percolate:synced-cron
```

@brookback @Rongky @znewsham - Could you take a quick look at your `.meteor/packages` file and/or your `.meteor/versions` file and compare to the above and help us narrow down the list of packages that are common to each of our apps?

**Comment by j0nd0n7** [comment]
I'm using dotenv and I see this behaviour too on v1.8.
I wonder if some of you found a solution.

**Comment by znewsham** [comment]
@j0nd0n7 Not a good solution, I ended up writing a helper to get the `NODE_ENV` that cannot be replaced at build time. 

```
Meteor.NODE_ENV = () => {
  let envString = "process.env.NODE_ENV";
  if (!process) {
    envString = "";
  }
  return eval(envString);
};
```

both the eval and the if statement are required
