### ISSUE TITLE
[1.6.2-beta.14] Cordova app not loading assets from public

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#9782]
Problematic version: 1.6.2-beta.14
Last version without problem: 1.6.1
Operating system: Ubuntu 16.04 + Android 8.1

Expected behavior: Assets like fonts and images from public directory must be displayed
Actual behavior: Assets are not being loaded. There is an error of Download Failure in the console

**Comment by CaptainN** [comment]
This may be related to the same core cause of the prefixes showing in appcache (for `web.browser.legacy` and therefor `defaultArch`) - I wonder if a fix in `bundler.js` (as described in [this comment](https://github.com/meteor/meteor/pull/9776#issuecomment-377334009)) could address this too.

**Comment by benjamn** [comment]
Is this fixed after running `meteor update --release 1.7-beta.26`?

**Comment by rj-david** [comment]
@benjamn, I was just running 1.6.1.1 and updated to 1.7-beta.26 using the update command you gave above.

The assets are still NOT loading.

Just to give additional details, I have the following in my css saved under the client folder:

`@import url(font_awesome/css/font-awesome.min.css);`

I have the file public/font_awesome/css/font-awesome.min.css

**Comment by crapthings** [comment]
https://github.com/meteor/meteor/issues/9846

**Comment by benjamn** [comment]
https://github.com/meteor/meteor/pull/9776#issuecomment-385180806

**Comment by crapthings** [comment]
part of assets are missing after upgrade cordova-plugin-meteor-webapp@1.4.1 to cordova-plugin-meteor-webapp@1.6.0

![image](https://user-images.githubusercontent.com/1147704/39512150-6d153aca-4e22-11e8-88d9-2ab090d5a9c5.png)

**Comment by crapthings** [comment]
our old app was built with 1.4.2.3
bug assets images/ won't display after build with 1.7b28

**Comment by crapthings** [comment]
@benjamn reproduce

![image](https://user-images.githubusercontent.com/1147704/39557000-0ffb830e-4eb7-11e8-9e42-b958e013e835.png)

![image](https://user-images.githubusercontent.com/1147704/39557060-84718116-4eb7-11e8-9e40-4de137706d95.png)

https://github.com/crapthings/meteor-9782

**Comment by rj-david** [comment]
@benjamn, I can confirm that my previous CSS issue was fixed in 1.7-beta.28

The problem now is as posted by @crapthings above. I have the file `public/favicon.ico` and when I run the cordova app, I'm getting this error for the favicon:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-rc.1` (see commits linked above).

**Comment by crapthings** [comment]
rc1 solved, i can see background image from asset

**Comment by rj-david** [comment]
confirmed solved in 1.7-rc.1
