### ISSUE TITLE
Meteor application not display the page after update METEOR@1.4.3.2 to METEOR@1.6.0.1

### ISSUE THREAD

**Issue by kalaharsath** [meteor/meteor#9792]
Hi,
i have developed meteor application version 1.4.3.2  its working fine . Whenever i have updated to 1.6.0.1 version it will display the empty screen but no error.

**Console is like this ,**
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
W20180402-17:56:19.963(5.5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20180402-17:56:20.009(5.5)? (STDERR) While this implementation will work correctly, it is known to be
W20180402-17:56:20.011(5.5)? (STDERR) approximately three times slower than the native implementation.
W20180402-17:56:20.012(5.5)? (STDERR) In order to use the native implementation instead, run
W20180402-17:56:20.013(5.5)? (STDERR)
W20180402-17:56:20.015(5.5)? (STDERR)   meteor npm install --save bcrypt
W20180402-17:56:20.015(5.5)? (STDERR)
W20180402-17:56:20.016(5.5)? (STDERR) in the root directory of your application.
=> Started your app.

=> App running at: http://localhost:3000/

**pckages.json**
 Meteor packages used by this project, one per line.
 Check this file (and the other files in this directory) into your repository.

 'meteor add' and 'meteor remove' will edit this file for you,
 but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.16                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.2                 # Meteor's client-side reactive programming library
standard-minifier-css@1.3.4   # CSS minifier run for production mode

es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
shell-server@0.2.3            # Server-side component of the `meteor shell` command
pbastowski:angular-babel
urigo:static-templates
accounts-ui@1.1.9
accounts-password@1.3.4
dotansimha:accounts-ui-angular
npm-bcrypt@0.9.2
check@1.2.5
simple:rest
simple:json-routes
simple:rest-accounts-password
http@1.2.12
session@1.1.7
email@1.1.18
alanning:roles
cfs:filesystem
cfs:standard-packages
cfs:http-methods
underscore@1.0.10
accounts-base@1.2.15
meteorhacks:ssr
momentjs:moment
chrismbeckett:toastr
tmeasday:publish-counts
meteorhacks:aggregate
quackware:ical-generator
drewy:pikaday-time
percolate:synced-cron
u2622:persistent-session
udondan:jszip
localstorage
mizzao:user-status
usefulio:sync-methods
mizzao:timesync
nilsdannemann:pdfmake

Please any one help me , Advance thanks,

**Comment by axelvaindal** [comment]
hi @kalaharsath,

There was some breaking changes between Meteor v1.4 to v1.6.
First of all, I suggest you follow this [guide](https://guide.meteor.com/1.5-migration.html) to migrate from v1.4 to v1.5, if you haven't done it yet.
After that, you can follow the [guide](https://guide.meteor.com/1.6-migration.html) to migrate from v1.5 to v1.6, if you haven't done it yet.

The v1.5 migration should be quite painless, considering there was not much breaking changes.
The v1.6 may be more tricky, considering the Node version has been updated.

You should make sure there is no incompatible packages inside your `node_modules` that would cause the client to crash. As your server console seems clean (except from the `bcrypt` warning), I assume the problem is client side. You must have something displayed in your browser console when your app is running which may indicate the source of the problem in your project.

**Comment by kalaharsath** [comment]
hi axelvaindal,

**Comment by kalaharsath** [comment]
Hi axelvaindal,
i follow as you guided,
shall i update like these commands
meteor npm install --save-dev babel-eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-meteor eslint-plugin-react eslint-plugin-jsx-a11y eslint-import-resolver-meteor eslint @meteorjs/eslint-config-meteor 
Please give me the clarifications.

**Comment by axelvaindal** [comment]
@kalaharsath 

You can update the packages you mentioned to their latest version, if they are compatible with the node version bundled with the Meteor version you're using. I assume it shouldn't be a problem here based on the package you're using.
Then again, I'm not sure the problem you're facing is coming from these packages. You must have an error message at the top of your browser console when running the app which will more likely give us more insight about the problem you're facing.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/9792#issuecomment-377938789, please follow the upgrade instructions in the Guide. If you run into any issues that you feel are bugs with Meteor itself, please open a new issue. Thanks!
