### ISSUE TITLE
Babel runtime not found

### ISSUE THREAD

**Issue by airstep** [meteor/meteor#9801]
`W20180406-12:58:23.630(3)? (STDERR) /home/taras/work/personal/ionic/postman/src/api/.meteor/local/build/programs/server/boot.js:475
W20180406-12:58:23.704(3)? (STDERR) }).run();
W20180406-12:58:23.705(3)? (STDERR)    ^
W20180406-12:58:23.706(3)? (STDERR)
W20180406-12:58:23.706(3)? (STDERR) Error: The @babel/runtime npm package could not be found in your node_modules
W20180406-12:58:23.707(3)? (STDERR) directory. Please run the following command to install it:
W20180406-12:58:23.708(3)? (STDERR)
W20180406-12:58:23.708(3)? (STDERR)   meteor npm install --save @babel/runtime`

What I must to do? meteor npm install --save babel/runtime <-- not helped

**Comment by klaussner** [comment]
Try `meteor npm install --save @babel/runtime` (with the `@`). 🙂

**Comment by airstep** [comment]
For sure it was with @, but github cut it off...

**Comment by klaussner** [comment]
Could you create a small runnable reproduction that demonstrates the problem? Also, which Meteor version are you using and what's listed in your `package.json` file under `dependencies`?

**Comment by airstep** [comment]
Sorry the project is huge. I just downgrade meteor to 1.6.0.1 and error is disapear.

` meteor update --release 1.6.0.1
                                              
Changes to your project's package version selections from updating the release:
                                              
autoupdate                 downgraded from 1.4.0 to 1.3.12
babel-compiler*            downgraded from 7.0.7 to 6.24.7
babel-runtime              downgraded from 1.2.0 to 1.1.1
boilerplate-generator      downgraded from 1.4.0 to 1.3.1
callback-hook              downgraded from 1.1.0 to 1.0.10
check                      downgraded from 1.3.0 to 1.2.5
ddp-client                 downgraded from 2.3.1 to 2.2.0
ddp-common                 downgraded from 1.4.0 to 1.3.0
ddp-server                 downgraded from 2.1.2 to 2.1.1
diff-sequence              downgraded from 1.1.0 to 1.0.7
dynamic-import             downgraded from 0.3.0 to 0.2.1
ecmascript                 downgraded from 0.10.6 to 0.9.0
ecmascript-runtime-client  downgraded from 0.6.0 to 0.5.0
es5-shim                   downgraded from 4.7.0 to 4.6.15
http                       downgraded from 1.4.0 to 1.3.0
id-map                     downgraded from 1.1.0 to 1.0.9
meteor-base                downgraded from 1.3.0 to 1.2.0
minifier-css               downgraded from 1.3.0 to 1.2.16
minifier-js                downgraded from 2.3.1 to 2.2.2
mongo                      downgraded from 1.4.2 to 1.3.1
ordered-dict               downgraded from 1.1.0 to 1.0.9
random                     downgraded from 1.1.0 to 1.0.10
reload                     downgraded from 1.2.0 to 1.1.11
retry                      downgraded from 1.1.0 to 1.0.9
server-render              removed from your project
shim-common                removed from your project
socket-stream-client       removed from your project
standard-minifier-css      downgraded from 1.4.0 to 1.3.5
standard-minifier-js       downgraded from 2.3.1 to 2.2.3
url                        downgraded from 1.2.0 to 1.1.0
webapp                     downgraded from 1.5.0 to 1.4.0`

babel/runtime was ended with 7...44

**Comment by hwillson** [comment]
@airstep As requested in https://github.com/meteor/meteor/issues/9801#issuecomment-379466384, can you please provide us with:

> which Meteor version are you using and what's listed in your `package.json` file under `dependencies`

**Comment by airstep** [comment]
1.6.1.1 - I tried to use this one and have problems. For now I downgrade it to 1.6.0.1

**Comment by hwillson** [comment]
After updating to 1.6.1 or 1.6.1.1 though, what did you have in your `package.json` when you tried to run your app? Can you post the full file? We want to make sure everything looks okay with your `@babel/runtime` config.

**Comment by airstep** [comment]
`  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/tsc-wrapped": "^4.4.6",
    "@babel/runtime": "^7.0.0-beta.44",
    "@ionic-native/admob-pro": "^4.4.0",
    "@ionic-native/app-version": "^4.5.3",
    "@ionic-native/camera": "^4.4.0",
    "@ionic-native/clipboard": "^4.5.3",
    "@ionic-native/contacts": "^4.5.3",
    "@ionic-native/core": "4.3.3",
    "@ionic-native/crop": "^4.4.0",
    "@ionic-native/device-accounts": "^4.4.2",
    "@ionic-native/diagnostic": "^4.4.0",
    "@ionic-native/fcm": "^4.4.0",
    "@ionic-native/file": "^4.4.0",
    "@ionic-native/firebase": "^4.5.3",
    "@ionic-native/geolocation": "^4.4.0",
    "@ionic-native/image-picker": "^4.4.0",
    "@ionic-native/in-app-browser": "^4.4.0",
    "@ionic-native/in-app-purchase": "^4.4.0",
    "@ionic-native/keyboard": "^4.4.2",
    "@ionic-native/media": "^4.4.2",
    "@ionic-native/network": "^4.4.0",
    "@ionic-native/sim": "^4.4.0",
    "@ionic-native/social-sharing": "^4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic-native/vibration": "^4.4.0",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "@types/lodash": "^4.14.85",
    "@types/meteor-publish-composite": "0.0.33",
    "angular-linky": "^1.2.2",
    "angular2-moment": "^1.7.0",
    "animate.css": "^3.5.2",
    "autolinker": "^1.6.2",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "com.synconset.imagepicker": "git+https://github.com/darkbasic/ImagePicker.git",
    "cordova-android": "6.4.0",
    "cordova-clipboard": "^1.1.1",
    "cordova-multidex": "git+https://github.com/jwall149/cordova-multidex.git",
    "cordova-plugin-admobpro": "^2.29.27",
    "cordova-plugin-admobpro-firebase": "^2.29.29",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^3.0.0",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-device-accounts": "git+https://github.com/airstep/cordova-device-accounts.git",
    "cordova-plugin-extension": "^1.5.3",
    "cordova-plugin-facebook4": "git+https://github.com/darkbasic/cordova-plugin-facebook4.git",
    "cordova-plugin-fcm": "^2.1.2",
    "cordova-plugin-file": "^5.0.0",
    "cordova-plugin-firebase": "^0.1.25",
    "cordova-plugin-geolocation": "^3.0.0",
    "cordova-plugin-inappbrowser": "^1.7.2",
    "cordova-plugin-inapppurchase": "^1.2.0",
    "cordova-plugin-media": "^4.0.0",
    "cordova-plugin-network-information": "^1.3.4",
    "cordova-plugin-sim": "^1.3.3",
    "cordova-plugin-smsreceiver": "^1.0.0",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.3.0",
    "cordova-plugin-vibration": "^2.1.6",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.2.1",
    "cordova-support-google-services": "^1.0.0",
    "cordova.plugins.diagnostic": "^3.7.2",
    "css-animator": "^2.1.1",
    "es6-promise-plugin": "^4.1.0",
    "fb": "^2.0.0",
    "flag-icon-css": "^2.8.0",
    "font-awesome": "^4.7.0",
    "gm": "^1.23.1",
    "horoscope": "^2.0.1",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "lodash": "^4.17.4",
    "me.tonny.cordova.plugins.multidex": "https://github.com/jwall149/cordova-multidex",
    "meteor-node-stubs": "^0.2.11",
    "meteor-rxjs": "^0.4.8",
    "moment": "^2.19.1",
    "node-fetch": "^1.7.3",
    "rxjs": "5.5.2",
    "sharp": "^0.18.4",
    "sw-toolbox": "3.6.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.0",
    "@types/bluebird": "^3.5.18",
    "@types/meteor": "^1.4.12",
    "@types/meteor-accounts-phone": "0.0.5",
    "@types/meteor-collection-hooks": "^0.8.3",
    "@types/node-fetch": "^1.6.7",
    "@types/underscore": "^1.8.5",
    "ionic": "3.20.0",
    "mup": "^1.3.7",
    "rimraf": "^2.6.2",
    "tmp": "0.0.33",
    "typescript": "^2.6.1",
    "typescript-extends": "^1.0.1",
    "ws": "^3.3.2"
  },
`

**Comment by airstep** [comment]
Sorry guys, today it works for me somehow....
