### ISSUE TITLE
Android device build failed

### ISSUE THREAD

**Issue by rahul606** [meteor/meteor#9810]
Hi, I am compiling meteor app on mac and ubuntu for android device. On both machines, I am facing this below error:

> Command failed with exit code 1 Error output:\nFAILURE: Build failed with an
> exception.\n\n* What went wrong:\nCould not determine the dependencies of
> task
> ‘:cordova-plugin-background-app:background-activity-lib:compileDebugAidl’.\n>
> Could not resolve all task dependencies for configuration
> ‘:cordova-plugin-background-app:background-activity-lib:debugCompileClasspath’.\n
> 
> Could not resolve project :CordovaLib.\n Required by:\n
> project :cordova-plugin-background-app:background-activity-lib\n >
> Project :cordova-plugin-background-app:background-activity-lib declares a
> dependency from configuration ‘debugCompile’ to configuration ‘debug’
> which is not declared in the descriptor for project :CordovaLib

Latest meteor version with cordova 6.4.0

**Comment by batcode007** [comment]
remove your cordova-plugins and re-install. Worked for me.
rm -rf .meteor/local/cordova-plugins
