### ISSUE TITLE
Package Server is Down

### ISSUE THREAD

**Issue by guardlawn** [meteor/meteor#9813]
All meteor update / meteor add commands return 500 server error.

**Comment by hwillson** [comment]
Ouch! Confirmed, thanks @guardlawn - we're on it!

**Comment by guardlawn** [comment]
Better ye the thee.  Thanks!

**Comment by benjamn** [comment]
Can folks try again now?

**Comment by dixicoin** [comment]
Working for me now, thanks very much!

**Comment by abernix** [comment]
This problem is now resolved and the package server should be operating normally again.

Thanks for your patience while we ensured everything was working properly.
