### ISSUE TITLE
Collection insert/upsert followed immediately by remove may remove data not intended for deletion

### ISSUE THREAD

**Issue by laddi** [meteor/meteor#9820]
Ok, so, the problem is probably not something people run into every day and also not easily explainable or reproducable, especially when running locally.  But here goes...

We have a fairly large codebase running in Meteor that is fetching data from outside APIs and storing it in Collections for reactivity.  We even have fetches running on intervals to keep it up to date.  What we do is add a `lastUpdated` `Date` field to our data on every run and then remove all data that falls outside the scope of that date.  But what we've been seeing, and this goes back many version of Meteor, is that sometimes the data we insert/upsert also gets deleted.

Our theory is this, especially since we haven't been able to reproduce this locally and only observed this in production:  Because of latency between Meteor and MongoDB the data we just updated is still not updated in MongoDB when we trigger the removal.  Therefore we are sometimes (rarely, thankfully) removing "good" data when we shouldn't.

So our question is this:  Is it possible to "wait" for the insert/upsert action to be truly finished before we call our removal?

And, follow-up question:  Would it be possible to make Collection actions promisable if/when needed?  `Collection.insert({...}, { promise: true }).then(...)`

**Comment by hwillson** [comment]
Hi @laddi:

> Is it possible to "wait" for the insert/upsert action to be truly finished before we call our removal?

I don't quite follow your question here as Meteor's Collection API does this by default. For example, if you run an `insert` with a callback, that callback is only called after the insert has completed (or if there was an error). See the [docs](https://docs.meteor.com/api/collections.html#Mongo-Collection-insert) for more info.

> Would it be possible to make Collection actions promisable if/when needed? Collection.insert({...}, { promise: true }).then(...)

Meteor's Minimongo/Mongo implementation doesn't currently leverage Promises, but if that's something you would like to see added, please consider opening a feature request over in http://github.com/meteor/meteor-feature-requests. In the meantime you could always consider implementing your own Minimongo/Mongo Promise wrapping layer, that converts their callback approach into a Promise based approach.

**Comment by laddi** [comment]
I was thinking more in the lines that if I don't provide a callback then the function would be called synchronously.  But maybe we'll just create our own wrapper, as you suggested...
