### ISSUE TITLE
meteor 1.6.1 - cookies are not persistent in cordova

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#9821]
We have an app where we disabled websockets and which is served through a load-balancer. This sets a cookie "route".

This seems to have worked before, but now its broken since latest version. I can't exactly tell, what caused this to break, but i see the following behavior:

- the server sends in the cookie with the first response. 
- the client doesn't send any cookies, so the server has to send a new one with each request
- this breaks the communication through sockjs, because each request might land on the wrong backend

is there a special cookie policy for cordova that has been changed?

**Comment by macrozone** [comment]
could be the same issue: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22

once again, wkwebview... can someone confirm this problem?

**Comment by hwillson** [comment]
@macrozone Just to confirm, is this working if you switch back to using Meteor 1.6.0?

**Comment by kirkroyster** [comment]
Yes, this is the same issue.  My scenario is Wakanda (apache server) on the back end, exactly as you say it sends the cookie, but the Apple wkwebview does not return the cookie.  This is presently under detailed review by a senior developer and I will communicate what they come up with as this is a show stopper for a hybrid application on iOS that must maintain a session (e.g. many apps have this basic requirement).  Further comments within a week.

**Comment by macrozone** [comment]
@hwillson @kirkroyster sorry, i forgot about this. Have to check whether this is still the case

**Comment by macrozone** [comment]
Can't tell if this issue is still around, so i close
