### ISSUE TITLE
Is everybody on Holiday? Not one commit in the last 11 days. Never happended before...

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#9822]
Subject says it all...

**Comment by hwillson** [comment]
Ouch, I don't know how we missed this @jorisroling - marking as `confirmed` `bug` and `pull-requests-encouraged`! 😸 

More seriously though, people are still here and new changes are coming. 1.6.2 (release version might change) is in beta (and 🤞will be coming soon), so please test if you have a chance and fire over any feedback. Thanks!

**Comment by jorisroling** [comment]
Ah, good to hear. Thanks for the feedback. (will give my 16.2-beta20 feedback now)
