### ISSUE TITLE
Unhelpful error: "It doesn't make sense to be adding something we know exists:"

### ISSUE THREAD

**Issue by timhaines** [meteor/meteor#983]
I saw this error today.

"It doesn't make sense to be adding something we know exists:"

It seems it's thrown in _LivedataConnection._process_added - perhaps it could be adjusted to be more framework user friendly?

**Comment by nicolsondsouza** [comment]
Hi, another question.
I was avoiding this issue by modifying the core Meteor.Collection.prototype._insert function,
But as per new Mongo.Collection, I don't see this function.
So could you guide what replaces 
Meteor.Collection.prototype._insert function
with
Mongo.Collection.prototype._insert

Thanks

**Comment by glasser** [comment]
Note that this was probably caused by the bug fixed by #5104.

**Comment by sasikanth513** [comment]
+1 for that PR
