### ISSUE TITLE
Could not resolve com.android.tools.build:gradle:3.0.0.

### ISSUE THREAD

**Issue by mrae75** [meteor/meteor#9835]
**please help**
**meteor build d:\  --server=localhost:5000**

=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error: cmd: Command failed with exit code 1 Error output:
   FAILURE: Build failed with an exception.

   * What went wrong:
   A problem occurred configuring root project 'android'.
   > Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.0.
   Required by:
   project :
   > Could not resolve com.android.tools.build:gradle:3.0.0.
   > Could not get resource
   'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom'.
   > Could not GET
   'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom'.
   > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/108.168.243.150] failed: Connection timed out:
   connect

   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
   output.

   * Get more help at https://help.gradle.org

   BUILD FAILED in 54s
   at ChildProcess.whenDone
   (D:\node_dev\meteor1\.meteor\local\cordova-build\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
   at emitTwo (events.js:126:13)
   at ChildProcess.emit (events.js:214:7)
   at maybeClose (internal/child_process.js:925:16)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by hwillson** [comment]
Have you followed the [Android development pre-requisites](https://guide.meteor.com/mobile.html#installing-prerequisites-android) listed in the Guide (in particular, the part that mentions what to do if Gradle can't be found)?

**Comment by mrae75** [comment]
Yes, properly installed
