### ISSUE TITLE
how to import a third javascript 

### ISSUE THREAD

**Issue by jihadwk** [meteor/meteor#9837]
I put a file in client directory,but I can't use it . A varible can't use.when I improt xx from '../client/xx',can't find module .long time ago ,everything is global.now what I should do .meteor version:1.6

**Comment by crapthings** [comment]
1. https://atmospherejs.com

> meteor add package:name

2. https://www.npmjs.com/

cli
> meteor npm i @package/name

js
> import Name from '@package/name'

3. ./imports/module.js
 
js from root path
> import ModuleName from '/imports/module.js'

js from relative path
> import ModuleName from './imports/module.js'

4. any other folders that use eager loading
but u most time u avoid using eager loading, use it wisely

5. from publish folder, cdn html script src etc...

**Comment by hwillson** [comment]
@jihadwk Please read the [Application Structure](https://guide.meteor.com/structure.html) section of the Guide to get a better understanding of how globals, `import`'s, eager vs. lazy-loading, etc. work with modern day Meteor. If you have any further questions after reading that section, please reach out via the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Issues here are reserved for bugs with Meteor itself. Thanks!
