### ISSUE TITLE
meteor 1.6.2 breaks ie11

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9839]
missing promise then after add polyfill, many syntax error like fat arrow used everywhere in meteor package.

https://github.com/meteor/meteor/blob/7cd4947780162b8cc4d6f4713c005c9533eb5a1e/packages/base64/base64.js

https://github.com/meteor/meteor/blob/devel/packages/base64/base64.js

![image](https://user-images.githubusercontent.com/1147704/39223228-57e9b7b6-4873-11e8-8ad5-fc2bc63d1c94.png)

### reproduce

meteor create testie1611
then upgrade to 162

**Comment by crapthings** [comment]
https://github.com/meteor/meteor/blob/devel/Roadmap.md#different-js-bundles-for-modern-versus-legacy-browsers

how to use legacy browser bundle ?

**Comment by benjamn** [comment]
Thanks for bringing this to our attention!

Related issue: https://github.com/meteor/meteor/issues/9818

It sounds like the solution is to adjust the modern/legacy test to exclude IE10 and IE11 (and anything earlier).

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-beta.25`. Please reopen (or create a new issue) if you discover otherwise!

**Comment by crapthings** [comment]
great it works~
