### ISSUE TITLE
[1.7] Electron always served legacy files

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9852]
Electron is always served the legacy version, because it is not included in any of the `setMinimumBrowserVersions` calls.

E.g. electron 2.0-beta.7 gets identified as:
`{ name: 'electron', major: 2, minor: 0, patch: 0 }

Since the versioning is different, we can not use the alias system.

So either it needs to get added to the `setMinimumBrowserVersions` calls, or we could use this to translate: https://www.npmjs.com/package/electron-to-chromium . But that needs to be kept up to date.

**Comment by benjamn** [comment]
Good catch! I think we should specify `electron` minimums explicitly in the `setMinimumBrowserVersions` calls. Any idea what version of Electron first supported `async`/`await` natively?

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-rc.1` (see commit linked above).

**Comment by sebakerckhof** [comment]
Fix confirmed in rc.1. Thanks for the fast resolution and glad to see we've reached RC stage.
