### ISSUE TITLE
Accounts.loginWithPassword / Meteor.loginWithPassword is not a function [server]

### ISSUE THREAD

**Issue by tesseracttech** [meteor/meteor#9859]
I have set up a REST Api using **nimble:restivus** and am trying to log into my meteor server from a standalone react app. 

However when I try to use either Meteor.loginWithPassword or Accounts.loginWithPassword I get the following error: 

Accounts.loginWithPassword is not a function.
Meteor.loginWithPassword is not a function.

I have imported: 

import { Meteor } from "meteor/meteor";
import { Accounts } from "meteor/accounts-base";

I have also tried JsonRoutes but the issue is the same. I have tried Node v6, v7, v8.

Any help would be appreciated.

**Comment by sebakerckhof** [comment]
Maybe a stupid question, but do you have the `accounts-password` package installed?
What is the contents of the `.meteor/versions` file of your project.

**Comment by InfinityLabTechnology** [comment]
accounts-base@1.4.2
accounts-facebook@1.3.1
accounts-github@1.4.1
accounts-google@1.3.1
accounts-oauth@1.1.15
accounts-password@1.5.1
alanning:roles@1.2.16
aldeed:collection2-core@2.1.2
allow-deny@1.1.0
autoupdate@1.4.0
babel-compiler@7.0.6
babel-runtime@1.2.2
base64@1.0.11
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.1
coffeescript@1.0.17
ddp@1.4.0
ddp-client@2.3.2
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.3.0
ecmascript@0.10.6
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.2
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
facebook-oauth@1.4.0
fastclick@1.0.13
geojson-utils@1.0.10
github-oauth@1.2.0
google-oauth@1.2.5
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
id-map@1.1.0
jquery@1.11.11
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
meteor@1.8.6
meteor-base@1.3.0
meteor-platform@1.2.6
minifier-css@1.3.1
minifier-js@2.3.4
minimongo@1.4.4
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.5
modules-runtime@0.9.2
mongo@1.4.5
mongo-dev-server@1.1.0
mongo-id@1.0.7
nimble:restivus@0.8.12
npm-bcrypt@0.9.3
npm-mongo@2.2.34
oauth@1.2.3
oauth2@1.2.0
observe-sequence@1.0.16
ordered-dict@1.1.0
promise@0.10.2
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.13
server-render@0.3.0
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
simple:json-routes@2.1.0
socket-stream-client@0.1.0
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.1
standard-minifier-js@2.3.3
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.2.0
webapp@1.5.0
webapp-hashing@1.0.9

**Comment by InfinityLabTechnology** [comment]
I tried downgrading to Meteor 1.4 and Node 6 but no luck either.

**Comment by aadamsx** [comment]
I'm on Meteor 1.6 and built a Web API using Express and the Meteor Accounts package.  No issues with auth from clients.  In fact I use the Accounts package extensively with this API.

I also had this working with Meteor 1.5

**Comment by sebakerckhof** [comment]
Can you create a small reproduction repository?
Also, these kind of questions are better suited for the forums since it's very likely not a bug.

**Comment by jorgeer** [comment]
[loginWithPassword](https://docs.meteor.com/api/accounts.html#Meteor-loginWithPassword) is a client-only function in the accounts package.

You might be looking for [this.setUserId](https://docs.meteor.com/api/methods.html#DDPCommon-MethodInvocation-setUserId)

**Comment by quidama** [comment]
Maybe you can make loginWithPassword working without 
'import Meteor from 'meteor/meteor'

In my case it was worked

**Comment by klaussner** [comment]
As explained in https://github.com/meteor/meteor/issues/9859#issuecomment-387679669, `loginWithPassword` only works on the client.

**Comment by BrianKaizuntus** [comment]
But how to use the "loginWithPassword" function on server side of meteor?

**Comment by klaussner** [comment]
I think you can't log in a user on the server. A login has to originate on the client.
