### ISSUE TITLE
cannot find module  'meteor/service-configuration'

### ISSUE THREAD

**Issue by xxxshppee7xxx** [meteor/meteor#9860]
i have a problem here and tried every thing to fix it but still dont work:
this is my main.ts :

import { Meteor } from 'meteor/meteor';
import { ServiceConfiguration } from 'meteor/service-configuration';

Meteor.startup(() => {
     ServiceConfiguration.configurations.upsert(
              { service: 'facebook' },
     {
       $set: {
             appId: 'xxxx',
             loginStyle: 'redirect',
             secret: 'xxxxx',
       },
     }
   );
 });
and this is the bug :
cannot find module 'meteor/service-configuration'
can you answer me plz ??

Before reporting a bug, please check for existing or closed issues
first and read the instructions for filing a bug report:
https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor

### This bug report should include:
- [ ] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [ ] The version of Meteor showing the problem.
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [ ] The operating system you're running Meteor on.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [x] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)

### Independent packages

Please ensure your issue is opened in the appropriate repository:

* Feature Requests: https://github.com/meteor/meteor-feature-requests
* Blaze: https://github.com/meteor/blaze/
* Docs: https://github.com/meteor/docs/
* Guide: https://github.com/meteor/guide
-->

**Comment by xxxshppee7xxx** [comment]
i tried that but also didn't work
this is my packages file: 
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.19                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@2.1.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
shell-server@0.2.4            # Server-side component of the `meteor shell` command
vue-templates
ts-decorators
accounts-base
http
accounts-facebook
service-configuration

**Comment by sebakerckhof** [comment]
Could you create a minimal reproduction repository? That would very much increase the chances of someone being able to track down what goes wrong. But it's very likely not a bug.

**Comment by xxxshppee7xxx** [comment]
i get the app from github this is the link of repository : 
https://github.com/andrei-markeev/finnlingo
can you see what is the bug?

**Comment by klaussner** [comment]
@xxxshppee7xxx That's not a Meteor bug. The error message comes from the TypeScript compiler because the typings (https://github.com/meteor-typings/meteor) don't include the `meteor/service-configuration` module. The error doesn't prevent the app from being built but if you still want to get rid of the message, you can declare the module yourself in `app/typings/globals/meteor/index.d.ts`:

```ts
declare module "meteor/service-configuration" {
  module ServiceConfiguration {
    var configurations: Mongo.Collection<any>;
  }
}

declare module ServiceConfiguration {
  var configurations: Mongo.Collection<any>;
}
```

The app is built without errors but I don't know TypeScript very well, so I'm not sure if that's a good way to do it. :slightly_smiling_face:
