### ISSUE TITLE
[1.6.1.1] Windows April Update: Cannot find module 'fibers'

### ISSUE THREAD

**Issue by Rhywden** [meteor/meteor#9863]
Long story short: After the latest Windows April Update a previously working 1.6.1.1 installation now yields this:

![image](https://user-images.githubusercontent.com/84586/39668104-e22d9b46-50c4-11e8-8bbc-f4721479be65.png)

**Comment by atfera** [comment]
I have the same issue, also after the April update, and now I can't go back to the old version because I deleted the old save \o/ (taken me +30 GB on my SSD :P )
I'm using the Linux bash on Windows to start my Meteor app and it's working fine for the moment, but I don't think it's the best solution for various reasons.

**Comment by thewebkid** [comment]
Slightly different error (Meteor 1.6.0.1),  but I am sure it is related to windows update. Burned 2 dev days flattening and reinstalling dev environments because I couldn't find anything online about this issue:  

```
W20180507-19:35:11.809(-7)? (STDERR) Error: EPERM: operation not permitted, stat 'C:\src\Analytics-Insights\app\.meteor\local\build\programs\server\node_modules'
W20180507-19:35:11.809(-7)? (STDERR)     at Object.realpathSync (fs.js:1670:17)
W20180507-19:35:11.809(-7)? (STDERR)     at toRealPath (module.js:156:13)
W20180507-19:35:11.809(-7)? (STDERR)     at tryFile (module.js:152:22)
W20180507-19:35:11.809(-7)? (STDERR)     at tryExtensions (module.js:164:22)
W20180507-19:35:11.809(-7)? (STDERR)     at Function.Module._findPath (module.js:217:20)
W20180507-19:35:11.810(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:534:25)
W20180507-19:35:11.810(-7)? (STDERR)     at Function.Module._load (module.js:466:25)
W20180507-19:35:11.810(-7)? (STDERR)     at Module.require (module.js:579:17)
W20180507-19:35:11.810(-7)? (STDERR)     at require (internal/module.js:11:18)
W20180507-19:35:11.810(-7)? (STDERR)     at Object.require (C:\src\Analytics-Insights\app\.meteor\local\build\programs\server\boot.js:283:20)
```

**Comment by Rhywden** [comment]
In the meantime, here's a workaround on how to keep your files in Windows, using the Linux Subsystem:
https://forums.meteor.com/t/workaround-for-windows-10-users-with-current-problems-fibers-not-found/43574

**Comment by lhz516** [comment]
Same thing for 1.7-rc.6

**Comment by gc87** [comment]
I have the same issue，I'm use choco to install meteor1.6.1.1 on Windows 10 1803.

**Comment by zodern** [comment]
Meteor 1.5 and older work, so I ran a git bisect today. The cause is eded3230396aced36192cd41ea11c5c74d2e98ab. Windows no longer throws an error when creating a symlink, so https://github.com/meteor/meteor/commit/eded3230396aced36192cd41ea11c5c74d2e98ab#diff-075e9c46ed726aa6f6c8ec1288336f6dR744 is never run.

**Comment by benjamn** [comment]
@zodern Are you saying that Windows fails to create the symlink, but doesn't throw any kind of error to report the failure?

**Comment by zodern** [comment]
![image](https://user-images.githubusercontent.com/8175744/39961464-1479e140-55fc-11e8-87f8-6ab84b366984.png)

It is created, but it is using the default type of `file` instead of using `junction`.

**Comment by marcoroche** [comment]
Same issue and don't have enough space to install Linux.

**Comment by NitroBAY** [comment]
@thewebkid I have the same issue than you, what is going on RN ?? 2 weeks later unfixed ? Why ? Have Meteor's team tracked down the issue yet ? I'm confused that windows  support broke with not that much noise even though how widely Windows and Meteor are used ??

**Comment by benjamn** [comment]
Try updating to Meteor 1.7 with `meteor update --release 1.7-rc.13`?

**Comment by lanmower** [comment]
I'm confused too, this makes android development impossible on windows.

**Comment by lanmower** [comment]
This is so critical I don't understand why its not being fixed.

**Comment by marcoroche** [comment]
Every time we do an update we still have to deal with `Error: Cannot find module 'dezalgo'`

It could be nice to include this command too in your future patch

`meteor npm i -g write-file-atomic path-is-inside async-some dezalgo`

With the 2 patches it works, I can carry on debugging without installing Linux.

**Comment by lanmower** [comment]
Same results here. Migrating to linux in the late stages of development
would be a huge undertaking. Just happy we got it to start.

**Comment by thewebkid** [comment]
I can say in all honesty this was a factor in me quitting my job - and meteor along with it. Bye bye fibers, blaze, tracker.autorun, slow to no windows compile time... 

Start my new job monday (c:

**Comment by stvenyin** [comment]
![1](https://user-images.githubusercontent.com/32395964/54012673-b567b400-41b1-11e9-91e2-2f8df6bc09cb.jpg)

**Comment by stvenyin** [comment]
![2](https://user-images.githubusercontent.com/32395964/54012714-d8926380-41b1-11e9-8d1e-a0484fd2b7ea.jpg)

**Comment by stvenyin** [comment]
me too.
