### ISSUE TITLE
App.accessRule not working as expected

### ISSUE THREAD

**Issue by EliArtist** [meteor/meteor#9864]
I was having issues with links in the android build of my meteor project for quite a while.

Figured out the problem was caused by the `App.accessRule` in mobile-config.js as it produced only the access-tag in the resulting config.xml. But according to the [meteor guide](https://guide.meteor.com/mobile.html#domain-whitelisting) it should produce three tags: access, allow-navigation and allow-intent.

Am I missing something here or is this a bug?

**Comment by adamgins** [comment]
@EliArtist wondering if you solved this... perhaps this is the reason I keep getting 

```
deviceready has not fired after 5 seconds.
cordova.js:1211 Channel not fired: onDOMContentLoaded
```
?

**Comment by EliArtist** [comment]
@adamgins Didn't really solve this. I found a workaround but its a pain. I just build with meteor, then change the resulting config and build the apk with Android-Studio (same for XCode).
Hope they fix this as soon as possible
