### ISSUE TITLE
Meteor 1.6.1 - error while running Meteor

### ISSUE THREAD

**Issue by Chidan** [meteor/meteor#9868]
Hallo Guys,

Doesnt seem to go anywhere with the new meteor 1.6.1.1 release on windows.
When I create a new project copy some files on client and server from different project (basically my custom react boiler plate) I get the below error.

 in the root directory of your application.
W20180507-15:53:32.341(2)? (STDERR) C:\Users\I033099\AppData\Local\.meteor\packages\meteor-tool\1.6.1_1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20180507-15:53:32.351(2)? (STDERR)                                             throw(ex);
W20180507-15:53:32.354(2)? (STDERR)                                             ^
W20180507-15:53:32.355(2)? (STDERR)
W20180507-15:53:32.356(2)? (STDERR) TypeError: Cannot read property 'length' of undefined
W20180507-15:53:32.358(2)? (STDERR)     at getProtohost (C:\Users\I033099\AppData\Local\.meteor\packages\webapp\1.5.0\npm\node_modules\connect\index.js:270:11)
W20180507-15:53:32.359(2)? (STDERR)     at Function.handle (C:\Users\I033099\AppData\Local\.meteor\packages\webapp\1.5.0\npm\node_modules\connect\index.js:121:19)
W20180507-15:53:32.360(2)? (STDERR)     at Object.app [as rawConnectHandlers] (C:\Users\I033099\AppData\Local\.meteor\packages\webapp\1.5.0\npm\node_modules\connect\index.js:51:37)
W20180507-15:53:32.362(2)? (STDERR)     at Meteor.startup (server/main.js:8:12)
W20180507-15:53:32.365(2)? (STDERR)     at Function.time (C:\Chidu\Projects\Trade\.meteor\local\build\programs\server\profile.js:309:28)
W20180507-15:53:32.369(2)? (STDERR)     at C:\Chidu\Projects\Trade\.meteor\local\build\programs\server\boot.js:427:13
W20180507-15:53:32.371(2)? (STDERR)     at C:\Chidu\Projects\Trade\.meteor\local\build\programs\server\boot.js:472:5
W20180507-15:53:32.372(2)? (STDERR)     at Function.run (C:\Chidu\Projects\Trade\.meteor\local\build\programs\server\profile.js:510:12)
W20180507-15:53:32.373(2)? (STDERR)     at C:\Chidu\Projects\Trade\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

 I have uninstalled and installed the meteor many times but still the error :(

**Comment by benjamn** [comment]
What code do you have around line 8 of `server/main.js`?

**Comment by Chidan** [comment]
Oops sorry typo..
