### ISSUE TITLE
[1.6.1.1] inputFile.require incorrectly uses the `browser` field.

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#9870]
I'm using Meteor 1.6.1.1 on Windows, and am trying to load a locally installed npm package for use in a build plugin using `inputFile.require`. 
Expected behavior: Since the npm package is being run in Node during the build step, it should be loaded using the `main` entry in the package's package.json file.

Actual behavior: Meteor loads the package using the `browser` entry in package.json, even though the package is not being loaded in the browser.

The package is `vue-template-compiler` and the package.json includes both a `main: 'index.js'` entry and a `browser: 'browser.js'` entry. When I use `inputFile.require` while compiling files for the web, Meteor uses the `browser` field instead of the `main` field. However, since the require is being called in the build process it should always use the `main` entry. In this case, the effect is that it prevents the plugin from performing a version check for compatibility.

**Comment by benjamn** [comment]
I believe this will be fixed if you run `meteor update --release 1.7-rc.7` (see the tests included in the commit linked above).
