### ISSUE TITLE
Updating from 1.6.1.1 to 1.7-rc.2 leads to Mongo exit code 62

### ISSUE THREAD

**Issue by schlaegerz** [meteor/meteor#9871]
Tried upgrading my app to 1.7-rc.2 and mongo seems to have a problem. I have a really big project so not sure if I can narrow it down at all but here is the output: 

=> Started proxy.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Unexpected mongo exit code 62. Restarting.
Can't start Mongo server.

**Comment by schlaegerz** [comment]
I got this error output from that command:

2018-05-08T09:14:01.602-0700 F CONTROL  [initandlisten] ** IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details.
2018-05-08T09:14:01.602-0700 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2018-05-08T09:14:01.602-0700 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2018-05-08T09:14:01.602-0700 I REPL     [initandlisten] shutdown: removing all drop-pending collections...
2018-05-08T09:14:01.602-0700 I REPL     [initandlisten] shutdown: removing checkpointTimestamp collection...
2018-05-08T09:14:01.602-0700 I STORAGE  [WTOplogJournalThread] oplog journal thread loop shutting down
2018-05-08T09:14:01.602-0700 I STORAGE  [initandlisten] WiredTigerKVEngine shutting down
2018-05-08T09:14:01.735-0700 I STORAGE  [initandlisten] WiredTiger message [1525796041:735593][83099:0x7fff959d4380], txn-recover: Set global recovery timestamp: 0
2018-05-08T09:14:01.856-0700 I STORAGE  [initandlisten] shutdown: removing fs lock...
2018-05-08T09:14:01.856-0700 I CONTROL  [initandlisten] now exiting
2018-05-08T09:14:01.856-0700 I CONTROL  [initandlisten] shutting down with code:62


Then when I tried to rerun meteor I got the same issue

**Comment by crapthings** [comment]
if u are not in production, try meteor reset and mongorestore your database.

**Comment by schlaegerz** [comment]
I was just trying to get a little bit ahead on some work for the new meteor version, this looks like it might cause issues with my mongo and switching back and forth between versions. I will just wait for new meteor to be released, but I still think this is something that should be looked at before release.

**Comment by jbbr** [comment]
I got the same problem after upgrading from `1.6.1` to `1.7-rc10` for testing purpose.

When trying to use the repair command I get:

```sql
2018-05-16T02:57:07.917+0200 F CONTROL  [initandlisten] ** IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details.
2018-05-16T02:57:07.917+0200 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2018-05-16T02:57:07.917+0200 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2018-05-16T02:57:07.917+0200 I REPL     [initandlisten] shutdown: removing all drop-pending collections...
2018-05-16T02:57:07.917+0200 I REPL     [initandlisten] shutdown: removing checkpointTimestamp collection...
2018-05-16T02:57:07.918+0200 I STORAGE  [WTOplogJournalThread] oplog journal thread loop shutting down
2018-05-16T02:57:07.918+0200 I STORAGE  [initandlisten] WiredTigerKVEngine shutting down
2018-05-16T02:57:08.072+0200 I STORAGE  [initandlisten] WiredTiger message [1526432228:72275][28653:0x7f386fea39c0], txn-recover: Set global recovery timestamp: 0
2018-05-16T02:57:08.220+0200 I STORAGE  [initandlisten] shutdown: removing fs lock...
2018-05-16T02:57:08.220+0200 I CONTROL  [initandlisten] now exiting
2018-05-16T02:57:08.220+0200 I CONTROL  [initandlisten] shutting down with code:62
```

**Comment by ramezrafla** [comment]
I think the answer may lie here from Mongo doc:
https://docs.mongodb.com/manual/release-notes/3.6-upgrade-replica-set/

> To upgrade from a version earlier than the 3.4-series, you must successively upgrade major releases until you have upgraded to 3.4-series. For example, if you are running a 3.2-series, you must upgrade first to upgrade first to 3.4 before you can upgrade to 3.6.

This isn't a Meteor problem, it uses the official Mongo DB driver.

**Comment by macrozone** [comment]
@ramezrafla any idea how to do this upgrade? which mongodb version did meteor 1.6.1 use ?

**Comment by schlaegerz** [comment]
Figured it out.

From mongo shell before you update you need to run

db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )

This really should be automated somehow, this is going to be a headache for a lot of people

**Comment by sferoze** [comment]
@schlaegerz thanks! I didn't want to meteor reset my local database, and also did not want to mongodump and restore. Running that one command was the easiest and best solution!

**Comment by greggman** [comment]
> before you update

DOH! 😭

**Comment by lightningboss** [comment]
@greggman it even works after you update!
What I did:
In one terminal, start your database using mongod: `mongod -dbpath appPath/.meteor/local/db` and in another start mongo: `mongo localhost:27017/meteor`. There you can use the command, for me this fixed the issue! :)

**Comment by SachaG** [comment]
Ran into the same thing. What worked for me:

- Downgrade back to 1.6.1
- Fix [this issue](https://forums.meteor.com/t/solved-cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-meteor-to-1-6-1-1/43034) that popped up for some reason.
- Run `db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )`

**Comment by noahsw** [comment]
How will this solution work for production databases? I use meteor-up

**Comment by meteorplus** [comment]
@noahsw may be run a post script in mup to run thatn mongodb script but this should be linked to mup repo too as an important issue!

**Comment by leemind** [comment]
Thank you guys - you saved me.  @lightningboss saved the day, but what wasn't obvious was *which* mongod to use.  I had to find mongo & mongod from the previous (1.6.1) release and use that.  
I found it: .meteor/packages/meteor-tool/1.6.1_1/mt-os.osx.x86_64/dev_bundle/mongodb/bin/mongod and that worked a treat.  Still worried about deploying to production though

**Comment by kennyhyun** [comment]
You can `db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )` without downgrade by running 
old mongodb by 
`~/.meteor/packages/meteor-tool/1.6.1/mt-os.XXX/dev_bundle/mongodb/bin/mongod --dbpath ./.meteor/local/db`

**Comment by joshperrin** [comment]
I'm running a production database on Compose with MongoDB 3.2.10.

Does anyone know if this will be an issue and how I work around it?

**Comment by SachaG** [comment]
@joshperrin I think this issue is only about the built-in local Mongo database that comes with Meteor. Your app will keep working the same with your production database, or you can also upgrade it if you prefer.

**Comment by derwaldgeist** [comment]
Ran into the same problem. IMHO there should be a warning issued by the meteor tool for this.

**Comment by tonyonodi** [comment]
I'm having the same issue currently, I've downgraded to an older version of meteor but when I try to do

`> db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } ) `

**Comment by tonyonodi** [comment]
I'm having the same issue currently, I've downgraded to an older version of meteor but when I try to do

`> meteor mongo`
`> db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } ) `

I get the error

```
{
        "ok" : 0,
        "errmsg" : "no such command: 'setFeatureCompatibilityVersion', bad cmd: '{ setFeatureCompatibilityVersion: "3.4" }'",
        "code" : 59
}
```
I'm on MongoDB shell version: 3.2.15

**Comment by leemind** [comment]
@tonyonodi I think you have answered your own question.  MongoDB 3.2, obviously can't set a compatibility with 3.4

**Comment by fangjj** [comment]
You can do without downgrade by running old mongodb by
~/.meteor/packages/meteor-tool/1.6.1/mt-os.XXX/dev_bundle/mongodb/bin/mongod --dbpath ./meteor_xxxx_project/.meteor/local/db

~/.meteor/packages/meteor-tool/1.6.1/mt-os.XXX/dev_bundle/mongodb/bin/mongo
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )

**Comment by SachaG** [comment]
Same issue for Meteor 1.8, but this time you'll need to set it to 3.6 before upgrading: 

> The 3.6 instance must have featureCompatibilityVersion set to 3.6.

From https://docs.mongodb.com/manual/release-notes/4.0-upgrade-standalone/

@benjamn it seems this should be handled by the upgrade process, or at least mentioned in the announcement post?

**Comment by RealHandy** [comment]
@fangjj solution also fixed the problem for me on 1.8 on Windows. FYI, on windows, I was on 1.7.0_5, so the path to the old mongodb was this:
`C:\Users\<user name>\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_64\dev_bundle\mongodb\bin\mongod --dbpath .\.meteor\local\db`

**Comment by ShaggyDude** [comment]
Reading this after I just started the downgrade install of 1.6.1.1 lol. Better late than never.

**Comment by GeoffreyBooth** [comment]
FYI if you have Docker installed you can open the database using whichever version of Mongo you want:

```bash
docker run -d -v ./.meteor/local/db --name db mongo:3.4 # or :3.6 or :4 etc.
docker exec -it db mongo # Use Mongo prompt to enter commands
docker stop db && docker rm db
```

**Comment by Bandit** [comment]
None of the above worked for me. Had to mongodump, meteor reset, and mongorestore by doing the following:

`~/.meteor/packages/meteor-tool/1.6.1_1/mt-os.osx.x86_64/dev_bundle/mongodb/bin/mongod --dbpath ./.meteor/local/db`
[in another prompt] `mongodump`
`meteor reset`
`mongorestore -h 127.0.0.1 --port 3001 ./dump`

Very annoying to work out the exact commands needed to do this. Why isn't this performed automatically by the upgrade process?

**Comment by SachaG** [comment]
As a quick note in case this helps someone (I just got good old error 62 with Meteor 1.10.1) you can also do the following to dump and restore, assuming you can get your db running: 

1. `mongodump -h 127.0.0.1:3001 -d meteor`
2. `mongorestore -h 127.0.0.1:3001 -d meteor dump/meteor`
