### ISSUE TITLE
[Workaround] [Chrome v66+] Chrome Node debugger fails to set breakpoints

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9875]
I can no longer set breakpoints in my meteor code.  I can put debugger statements in and step through the code, But setting breakpoints no longer works.

I think this happened after a Chrome update, so it is probably a Chrome issue with Meteor?

I noticed it started happening when I started seeing this icon in the network tab at the upper left:

![chrome icon](https://user-images.githubusercontent.com/14342237/39846831-a493b1bc-53b2-11e8-98d5-e571fb3271ca.png)

Maybe a source map problem?

### Environment:
- Chrome Version 66.0.3359.139 (Official Build) (64-bit)
- meteor@1.6.1.1
- node 8.11.1
- npm 5.8.0
- Windows 10

**Comment by benjamn** [comment]
I'm not sure whether this is a Chrome issue or a Node inspector issue, but (thankfully?) I don't think it's a source maps issue, because when I turn off JS source maps, and let the inspector stop on this `debugger` statement (in `server/main.js`), I still can't get the inspector to stop at a breakpoint that I've set on the `console.log` line:
```js
Meteor.startup(() => {
  debugger;
  console.log(module.id);
});
```
This also seems to imply it's not a fibers issue, since there's certainly no `Fiber.yield` between the `debugger` and the `console.log`, which is good news (i.e., it's not another case of #9275).

**Comment by benjamn** [comment]
Ok, I've now tried it in Chrome stable, beta, dev, and canary, and encountered the same problem in every one, so I think it's safe to rule out the Chrome update as the root cause. Which leaves Node 8.11.1. We haven't been able to update Windows to 8.11.2-rc.1 yet because the `process.release.headersUrl` is wrong, but it might be worth a try (running Meteor from a checkout) just to see if this happens to be fixed in 8.11.2.

**Comment by brucejo75** [comment]
But I have successfully set breakpoints with `meteor@1.6.1.1` prior to yesterday (which is when I believe I got updated to Chrome 66.)

I cannot find a way to load down-level versions of Chrome (e.g 65).  Are you aware of any?

**Comment by brucejo75** [comment]
Hi @benjamn , I did some poking around and found this [node bug](https://github.com/nodejs/node/issues/19273) which spawned this [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=820728).

But I also noticed that the paths in the debug tools are messed up,  In my case it thinks the root path is `file:///mnt/e/u/mroot/meris/.meteor/local/build/main.js`, including `main.js`.

If I hover over other folders in the debug tools I see the messed up path.  See picture.

Does this look like a node issue?  or can Meteor control this?

![chrome debugger issue](https://user-images.githubusercontent.com/14342237/40018587-82ea2966-5771-11e8-9c4b-6057b7e74388.png)

**Comment by RealHandy** [comment]
Same issue here. "debugger" line in the server code breaks execution at that point, but UI breakpoints in the chrome debugger do not stop execution.

**Comment by brucejo75** [comment]
Hi @benjamn, I am trying to make sense of your [comment](https://github.com/meteor/meteor/issues/9875#issuecomment-388100122):
> because the `process.release.headersUrl` is wrong, but it might be worth a try (running Meteor from a checkout) just to see if this happens to be fixed in 8.11.2.

Are you talking about https://github.com/nodejs/node/issues/20066?

My read is that `process.release.headersUrl` behavior has changed and it is messing Meteor up 
 here:
https://github.com/meteor/meteor/blob/b7ea61783886d495297c85367426c50f115275e7/scripts/generate-dev-bundle.ps1#L146.

**Comment by benjamn** [comment]
All I was referring to is this comment: https://github.com/nodejs/node/pull/20478#issuecomment-387181249. Specifically, the Windows build of Node 8.11.2-rc.1 somehow has a `process.release.headersUrl` that's slightly wrong. This will presumably be fixed when 8.11.2 is finalized. I don't think this has anything to do with source maps.

**Comment by brucejo75** [comment]
But this is busted in 8.11.1?  Have not tried with meteor 1.7 builds.

**Comment by benjamn** [comment]
I also found this issue, which seems similar: https://bugs.chromium.org/p/chromium/issues/detail?id=838891

**Comment by benjamn** [comment]
By the way, I'm now able to reproduce this problem on OSX (not just Windows).

**Comment by brucejo75** [comment]
Similiar issue: https://github.com/ChromeDevTools/devtools-protocol/issues/103

**Comment by brucejo75** [comment]
## Workarounds
see: https://github.com/ChromeDevTools/devtools-protocol/issues/103#issuecomment-392767630

The gist
### Use NIM
https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

This works still.  To set it up:
1. install [NIM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj)
2. enable it
3. Click on green NIM icon in upper right corner
4. Set your debug session settings (host & port)

you can set it to automatically connect or manually

### Manually navigate to the debugger

prepend
```
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=
```

To the host ip, port and id

For example, my instance of Meteor is displaying  this line on startup:
```
Debugger listening on ws://127.0.0.1:5838/8382a21a-1352-4cc1-a3b2-b643a011d630
```

For this example the IP, port & id are:
![debug url](https://user-images.githubusercontent.com/14342237/40947356-255db3b0-6817-11e8-84ed-fdc67a174fe0.png)


I can get a working debug session with breakpoints by navigating to this URL in chrome:
```
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5838/8382a21a-1352-4cc1-a3b2-b643a011d630
```

**Comment by lcampanis** [comment]
+1

**Comment by tehXor** [comment]
Starting with Chrom v69 the workarounds don't work anymore for me.

Be it with NIM or a manually opened dedicated inspector window on chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws= the behaviour is the same than in the default dev-tools - so break points no longer work.

This is annoying... I'm not sure though if it would work with newer node versions or if there are other workarounds meanwhile?

**Comment by june07** [comment]
Newest version 1.0.0 of NiM works.  See end of thread for details:
https://bugs.chromium.org/p/chromium/issues/detail?id=883481

**Comment by brucejo75** [comment]
With the next version of Chrome (v72+) this should be back to working order, the NIM workaround will not be necessary at that point.

Setting breakpoints is [working with canary](https://github.com/ChromeDevTools/devtools-protocol/issues/103#issuecomment-429649817).

**Comment by brucejo75** [comment]
With Google Chrome: `Version 71.0.3578.80 (Official Build) (64-bit)` this issue is now resolved.

This updated last week sometime.  I have been using it since its release and happily breakpoints are being hit.

Closing....
