### ISSUE TITLE
[1.6.1.1] meteor build produces inconsistent bundles when run on different machines

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#9878]
Hey,

I've been digging why I do receive an initial HCP on cordova/electron build after app install and it seems that the bundle has a small difference if you make your builds on many machines. 
The difference in the bundle is in `packages/modules.js`. The package.json of `@babel/runtime` is included and it contains as `_where` field with path that can be different on different machines: ` "_where": "D:\\projekty\\project",` 

```javascript

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/@babel/runtime/package.json                                                                            //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
module.exports = {
  "_from": "@babel/runtime@7.0.0-beta.46",
  "_id": "@babel/runtime@7.0.0-beta.46",
  "_inBundle": false,
  "_integrity": "sha512-/3a3USMKk54BEHhDgY8rtxtaQOs4bp4aQwo6SDtdwmrXmgSgEusWuXNX5oIs/nwzmTD9o8wz2EyAjA+uHDMmJA==",
  "_location": "/@babel/runtime",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@babel/runtime@7.0.0-beta.46",
    "name": "@babel/runtime",
    "escapedName": "@babel%2fruntime",
    "scope": "@babel",
    "rawSpec": "7.0.0-beta.46",
    "saveSpec": null,
    "fetchSpec": "7.0.0-beta.46"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.0.0-beta.46.tgz",
  "_shasum": "466a9c0498f6d12d054a185981eef742d59d4871",
  "_spec": "@babel/runtime@7.0.0-beta.46",
  "_where": "D:\\projekty\\project",
  "author": {
    "name": "Sebastian McKenzie",
    "email": "sebmck@gmail.com"
  },
  "bundleDependencies": false,
  "dependencies": {
    "core-js": "^2.5.3",
    "regenerator-runtime": "^0.11.1"
  },
  "deprecated": false,
  "description": "babel selfContained runtime",
  "devDependencies": {
    "@babel/core": "7.0.0-beta.46",
    "@babel/helpers": "7.0.0-beta.46",
    "@babel/plugin-transform-runtime": "7.0.0-beta.46",
    "@babel/preset-env": "7.0.0-beta.46",
    "@babel/types": "7.0.0-beta.46"
  },
  "license": "MIT",
  "name": "@babel/runtime",
  "repository": {
    "type": "git",
    "url": "https://github.com/babel/babel/tree/master/packages/babel-runtime"
  },
  "version": "7.0.0-beta.46"
};
```

**Comment by wojtkowiak** [comment]
This will also happen if you have Jenkins and you have two jobs, one for container, one for android - they will run from different paths so even on the same machine you can get initial HCP after fresh app install.

**Comment by benjamn** [comment]
That field is added by the `npm` command-line tool, not the Meteor build process, so I'm not sure there's anything we can do about it, without explicitly modifying `package.json` after it's written.

**Comment by KoenLav** [comment]
We have been experiencing the same issue.

@benjamn I guess this issue should be reported at either Npm or babel/runtime then?

**Comment by abernix** [comment]
@wojtkowiak The contents of the `package.json` are generated by npm, but the snippet you've presented above is generated from the Meteor linker, which is responsible for bundling the `node_modules` content.  I do know that the `_where` field is metadata added by `npm`, but do you have any idea why the `_where` field is being used?

It's possible that some fields prefixed with underscores (like `_where`) are an important performance tool for npm to quickly validate `node_modules` trees, but I'm curious if we could strip these prefixed fields during linking, which I believe happens [here](https://github.com/meteor/meteor/blob/1aabda8fcf6dfbd31a1d11e6ff7d8b74e1defcf9/tools/isobuild/linker.js)?

Thoughts?

**Comment by wojtkowiak** [comment]
It seems that NPM is aware of the problem:
https://github.com/npm/npm/issues/10393
https://github.com/npm/npm/issues/12110

There is even a package for that: https://www.npmjs.com/package/removeNPMAbsolutePaths

I will create a PR but I apologize upfront for putting the logic in my very best guess for where it should be 🙂

**Comment by wojtkowiak** [comment]
Any chance of resolving this with `1.7.1`?

**Comment by wojtkowiak** [comment]
@abernix @benjamn sorry for pinging 🙂  but this has a high priority for me as in my current CI setup I am not able to even workaround this by building from the same path as I am building ios/android/desktop clients for my project.

**Comment by wojtkowiak** [comment]
Anyone? 🙂

**Comment by georgyberdyshev** [comment]
Hello @wojtkowiak,

as workaround you could update your CI setup to use yarn instead of npm.

As the _where field is specific to npm, it will not be included by yarn.

Georgy
