### ISSUE TITLE
[1.7] Deployment issue

### ISSUE THREAD

**Issue by andycanderson** [meteor/meteor#9879]
After upgrading from Meteor 1.6.1.1 to version 1.7-rc.6 and deploying to galaxy error on client side console is observed. 

```Mixed Content: The page at 'APP_URL' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'WS_URL'. This endpoint should be available via WSS. Insecure access is deprecated.```

**Comment by benjamn** [comment]
I believe this will be fixed if you run `meteor update --release 1.7-rc.7` and redeploy.
