### ISSUE TITLE
Default packaged jQuery has XSS vuln

### ISSUE THREAD

**Issue by elmarti** [meteor/meteor#9881]
`meteor/jquery` is installed by default and provides jQuery v1.
There is an XSS vulnerability found which affects versions 1.4+, for which the advisory is to upgrade to 3.x https://nodesecurity.io/advisories/328, which I assume means this won't be fixed. 

This is problematic and can also cause build errors if the standard npm package is used 
```
npm WARN notice [SECURITY] jquery has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=jquery&version=1.12.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

**Comment by CaptainN** [comment]
Some additional note: this isn't really the same thing, but you can override the default version of jquery by putting the latest version of jquery in your package.json - then meteor will use that one.

In my testing there are compatibility problems with that in the ecosystem (Blaze seems to work just fine). Certain things in Aldeed's AutoForm don't work right with jquery 3+ and the current version of twbs:bootstrap in atmosphere is only at version 3.3.6, which doesn't support jquery 3+ (there is a version 3.3.7 in the github repo, but it doesn't seem to have been pushed to atmosphere).

**Comment by elmarti** [comment]
Yeah, that's exactly the same boat that I'm in, numerous projects using Bootstrap 3 and Autoform, so it's a fork in the road!

**Comment by CaptainN** [comment]
You can grab the `twbs:bootstrap` package from the v3 branch, and put that in your local `packages` folder, to gain compatibility with jquery 3. The issues in autoform are likely harder to deal with.

**Comment by axelvaindal** [comment]
As Meteor is slowly (but surely!) migrating all packages to `npm` it is safe to assume, you shouldn't use the embedded `jQuery` for real apps.
Based on this [commit](https://github.com/meteor/meteor/commit/56ac7657799f6cf49a3743a779984aedc20cc059), and the fact that `jQuery` was moved to non-core, I suppose upgrading `jQuery` is not an option and the objective is to be less dependent on the provided version (perhaps even removing the embedded version one day).

Feel free to remove the current version of `jQuery` and use the one from `npm`. This should fix your issue.
However, I agree perhaps documentation should be updated to take note of this fact 🙂

**Comment by elmarti** [comment]
Not sure if `wontfix`
