### ISSUE TITLE
[1.7-rc.8] Dynamic imports broken due to CORS

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9888]
This commit: https://github.com/meteor/meteor/commit/3b77bb51973cfbd98488a7203fc6d87c5c871a01
Breaks dynamic imports when you visit the app via anything else than what's defined as ROOT_URL, due to CORS not working with dynamic imports:

```
 (STDERR) (node:17221) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: 'OPTIONS' === 'POST'
W20180514-11:51:10.124(2)? (STDERR)     at middleware (packages/dynamic-import.js:85:10)
W20180514-11:51:10.124(2)? (STDERR)     at /home/seba/.meteor/packages/promise/.0.11.0-rc17.8.11if8y9.p01x++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180514-11:51:10.124(2)? (STDERR) (node:17221) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

Then on the client-side I'd get:
```
Failed to load https://dev.local/__meteor__/dynamic-import/fetch: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://client.dev.local' is therefore not allowed access. The response had HTTP status code 504.
```

The reason I'd need this is that we have a multi-tenant system where each tenant has a subdomain. But this would break for any app which is accessible via multiple URLs and has to set a ROOT_URL.

This would still work if you don't set a ROOT_URL, which is why that commit was reverted in the first place, but that breaks `Meteor.absoluteUrl` on the server side, so it's not a viable solution IMO.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-rc.9`, thanks to two separate commits (either of which would have fixed the problem by itself):
- 6c91a4f0c3be2c770ce40ca663e92afe77ab9dcd
- c4b5707747ce3c5bf339b62940da84628680a1d3

**Comment by benjamn** [comment]
Thinking about this some more, `Meteor.absoluteUrl` would be the right solution if the CORS problem is solved, and `location.host` doesn't work in situations (like #9747) where the Meteor server is not running on the `location.host` domain, and `ROOT_URL` is set to a different domain.

Since I believe c4b5707747ce3c5bf339b62940da84628680a1d3 solves the CORS problem, perhaps we should use `Meteor.absoluteUrl` for dynamic `import()`s, instead of `location.host`? Is there any downside to making cross-origin dynamic `import()` requests, as long as CORS allows them?

**Comment by crapthings** [comment]
Sorry, this project uses Meteor 1.7-rc.9, which is not installed and could not be downloaded. Please check to make sure that you are online.
