### ISSUE TITLE
Change Mongodb Version

### ISSUE THREAD

**Issue by delatorremario** [meteor/meteor#9890]
I need change local meteor mongo version from 3.2 to 3.6.
Is there a way to change the version or update it?

**Comment by benjamn** [comment]
You can update to Meteor 1.7: `meteor update --release 1.7-rc.11` (we're very close to the final release if you're not comfortable using a release candidate).

**Comment by hwillson** [comment]
Meteor 1.7 has been officially released, and uses Mongo 3.6.
