### ISSUE TITLE
Bundle visualizer request fails on a app with ROOT_URL

### ISSUE THREAD

**Issue by joaomframos** [meteor/meteor#9891]
The use case is pretty much the same as #9747.

Bundle visualizer stats file is requested directly to location.host while the app is loaded on a different URL due to ROOT_URL being defined.

I'm having this issue on 1.7 rc10 but it seems like that the issue is widespread across other branches. I have had this problem all the way since 1.5, at least, if not mistaken, but never had the time to look into it.

Check url variable definition on:
https://github.com/meteor/meteor/blob/release-1.7/packages/non-core/bundle-visualizer/client.js

**Comment by joaomframos** [comment]
Tested this again with Meteor 1.8 and it's working now.

**Comment by shenrenguo** [comment]
I meet same problem with meteor 1.8.1. 
chrome prompts: ERR_EMPTY_RESPONSE
