### ISSUE TITLE
Rebuild kicks off before all files are saved to disk

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9896]
### Environment
Windows 10
Meteor 1.6.1.1
Node 8.11.1

### Repro
Essentially, what is happening is that I am in VSCode and I save multiple files at once via save all command.  If Meteor is monitoring one of the files directly it starts a build pretty fast.  But I think because of timing it misses the changes to other files that were saved after the file that kicks it off.

This is intermittent, but when it happens I end up chasing down a fix that I already made.  The code in Chrome development tools does not match the code on disk.  Then I do a rebuild.,

### Suggest

Once a file update is detected wait 500 msec? to fire the build?  This will save me 10 minutes once every couple of days.

### Workaround
- stop running process and restart the build

**Comment by veered** [comment]
Would be nice if this were configurable https://github.com/meteor/meteor/blob/devel/tools/fs/watch.js#L503

**Comment by benjamn** [comment]
I would take a quick PR to change that `100` to the value of `process.env.METEOR_FILE_WATCH_COALESCE_MS`, with 100 as a default.
