### ISSUE TITLE
Symbol.asyncIterator undefined

### ISSUE THREAD

**Issue by dobesv** [meteor/meteor#9897]
The ecmascript babel compiler has a babel plugin to transpile async generators, but doesn't include a polyfill to define `Symbol.asyncIterator`.

Supporting this should require importing the appropriate `core-js` module during app initialization:

https://github.com/zloirock/core-js#stage-3-proposals

**Comment by benjamn** [comment]
@dmihal That works, but is definitely overkill. If you run
```sh
meteor --production --extra-packages bundle-visualizer
```
you'll see a *lot* of extra code from `babel-polyfill` and `core-js`, when all you needed was the `Symbol.asyncIterator` polyfill.

**Comment by dobesv** [comment]
Yeah, that's the workaround.  I had to add a meteor package to do this so
that the polyfill was available for other packages to use, e.g.
meteor-apollo.

**Comment by Rockettomatoo** [comment]
I have the same issue and found [babel/babel #7467](https://github.com/babel/babel/issues/7467). There they say, it works if you use `@babel/plugin-transform-runtime` with options `{ corejs: true }` but it didn't work for me (`@babel/plugin-transform-runtime` [is suggested](https://babeljs.io/docs/en/babel-runtime#usage) to use with `@babel/runtime` which meteor use. 

Also, I installed `@babel/plugin-proposal-async-generator-functions`, `@babel/plugin-transform-async-to-generator` and adjusted my `.babelrc` accordingly. None of that worked. 

Just out of confusion: Shouldn't I be able to modify my babel setup through my `.babelrc` without interference from meteor?

I will now look to manually import an appropriate polyfill although I wonder why `@babel/plugin-transform-runtime` with the corejs option doesn't work.

I also asked this on [SO](https://stackoverflow.com/questions/56595401/typeerror-object-is-not-async-iterable-with-async-generator-function) but it didn't get much attention so I'm searching for help here now (also there's a repro for the problem in case you need it).

**Comment by dobesv** [comment]
Even if you update your Babel configuration it only tries to fix your own code.  The code in node modules is not processed using Babel in meteor.

**Comment by Rockettomatoo** [comment]
@dobesv maybe I should clarify more: In my reproduction, neither `Symbol.asyncIterator` nor `myAsyncGenerator()[Symbol.asyncIterator]` are defined. According to the linked babel issue this should work with either `@babel/plugin-transform-runtime` and option `{ corejs: 3 }` (to load the appropriate polyfill or a newer node version (`v.10.x` or newer I think).

From my POV, this is not a matter of whether this happens in my own code or not but the fact that either some polyfills are not loaded or some transformation doesn't happen.

I tried several babel plugins and configurations but I didn't get it to work. Since babel itself seems to work (according to their issue) I guess that this is somewhat meteor related.

Here is my repro:
```js
// Meteor v.1.8.1

// package.json
{
  "devDependencies": {
    "@babel/plugin-proposal-async-generator-functions": "^7.2.0",
    "@babel/plugin-transform-async-to-generator": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
  },
  "dependencies": {
    "@babel/runtime": "^7.4.5"
  }
}

// .babelrc
{
  "presets": ["env"],
  "plugins": [
    ["@babel/transform-runtime", { "corejs": 3 }],
    "@babel/transform-async-to-generator",
    "@babel/proposal-async-generator-functions"
  ]
}

// server/main.js
async function* counter(max) {
  let count = 0;
  while(count < max) {
    yield Promise.resolve(count++);
  }
}
(async () => {
  for await (const num of counter(3)) {
    console.log(num);
  }
})();
```
the async loop throws an error `TypeError: Object is not async iterateable`.

**Comment by dobesv** [comment]
Okay, I don't know then.

**Comment by Rockettomatoo** [comment]
Just a quick follow up on my findings:

I tried importing
```js
import 'core-js/modules/es7.symbol.async-iterator'
```
and
```js
import 'core-js/es7/symbol'
```
I have `core-js@2.6.9` installed. Neither of the above worked for me.

@benjamn @dmihal do you have any ideas?

**Comment by Rockettomatoo** [comment]
Hello @benjamn,
thanks for the work you've done!
I'm wondering if this also ensures that async generators work properly? In my current 1.8.1 project, an async generator does not produce an object with an `Symbol.asyncIterator` property. For a repro have a look at [my comment above.](https://github.com/meteor/meteor/issues/9897#issuecomment-502968045)

Also is there a release date for `v1.8.2` already? Would be looking forward for this release!

Thanks in advance!
