### ISSUE TITLE
ReactiveSearch : Missing modules emitter bufferutil utf-8-validate

### ISSUE THREAD

**Issue by durdenx** [meteor/meteor#9900]
Hi,
I try to use [ReactiveSearch ](https://opensource.appbase.io/reactivesearch/) with meteor but the app crash if i import it just like this: 

```js
import { ReactiveBase } from "@appbaseio/reactivesearch";

Meteor.startup(() => {
  render(
   <ReactiveBase
        app="car-store"
        credentials="cf7QByt5e:d2d60548-82a9-43cc-8b40-93cbbe75c34c"
    >
         <App  />
  </ReactiveBase>,
document.getElementById("app"));
```

Meteor give the the message below:
> If you notice problems related to these missing modules, consider running:
> 
>   meteor npm install --save emitter bufferutil utf-8-validate

if i install those packages i get that message:

> Uncaught TypeError: Emitter is not a constructor

An issue has been opened on reactivesearch repo (they say this is a "meteor specific error")   : https://github.com/appbaseio/reactivesearch/issues/323

Repo to reproduce the error : https://github.com/durdenx/reactive-search-meteor-error
```
git clone git@github.com:durdenx/reactive-search-meteor-error.git
npm install
meteor
```

**Comment by benjamn** [comment]
It would really help if you could provide a simple, runnable reproduction.

Taking a wild guess in the meantime: does your app use the `meteor-node-stubs` npm package?

**Comment by benjamn** [comment]
Also, it looks like the `emitter` package [defines `global.emitter`](https://github.com/iwillwen/node-emitter/blob/2c96b239dfcdbf77939d9661a98b25ba2d04c888/dist/emitter.js#L11), whereas your error mentions `Emitter` (with a capital `E`)…

**Comment by durdenx** [comment]
Thanks for you help.

I created a repo here to reproduce the error: https://github.com/durdenx/reactive-search-meteor-error
```
git clone git@github.com:durdenx/reactive-search-meteor-error.git
npm install
meteor
```

This is a fresh meteor install with reactjs. `meteor-node-stub` is installed.

Actually the error occurs when we add that line:
`import { ReactiveBase } from "@appbaseio/reactivesearch";`

You can see it in `/imports/App.js`

**Comment by yaroslavhorokhovets** [comment]
as
![save](https://user-images.githubusercontent.com/113622705/219980753-3707928f-233e-44e0-896c-9c097dccc866.jpg)
