### ISSUE TITLE
App is crashing on client side

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#9904]
After upgrading our app to Meteor 1.6.1.1 we have serious issues on the client side. The app freezes after several seconds and crashes. The problem only occurs when the user creates a user account or is already logged in. Guest visitors don't have this issue. If I revert back to 1.6.1, everything is working fine again.

This is how our profile looks like:

<img width="1732" alt="bildschirmfoto 2018-05-24 um 18 04 25" src="https://user-images.githubusercontent.com/7636313/40497607-f57aaf4c-5f7c-11e8-9681-16dfdb85bb2c.png">

In dev mode, we saw a lot of EJSON.clone calls instead of the anonymous functions. This are our packages after upgrading to the latest Meteor version:

<img width="642" alt="bildschirmfoto 2018-05-24 um 17 52 05" src="https://user-images.githubusercontent.com/7636313/40497654-13e289be-5f7d-11e8-9e43-868bcba9bc46.png">
<img width="615" alt="bildschirmfoto 2018-05-24 um 17 52 10" src="https://user-images.githubusercontent.com/7636313/40497655-140bd378-5f7d-11e8-9bac-1238759f18cf.png">

Any idea what's causing the issue? I've already tried to remove the third party packages like redis-oplog and spiderable, but the problem still occurs after that. Tested in Chrome and Safari.

**Comment by dnish** [comment]
After downgrading I've also noticed that the problem is still there, but it only happens on older account. If I use private mode and create a new account, everything is working fine, even after reload.

**Comment by vuhrmeister** [comment]
I have the same or similar issue, but I couldn't find any reproducible cause. Chrome tab freezes, CPU goes high, but no errors or so. Also I only experienced it in dev mode since the app is not in production yet.
Don't know if it's related or if it's even Meteor related.

**Comment by dnish** [comment]
It must be related to Meteor, LiveData is handled by the core. Just wondering that this happens only on older accounts. Suddenly started and reverting back to an older release didn't solve the problem.

**Comment by StorytellerCZ** [comment]
Does the app reloads after the crash?
In my case user login and registration are not a problem. Instead after a while (seems to be always at least a couple of minutes) the client side crashes (but without freezing the browser or anything like that) and reloads. Is this similar to what you are experiencing?
I have been thinking that there might be some sort of memory leak.

**Comment by vuhrmeister** [comment]
For me it's actually freezing so that I also can't reload the page. I need to close the tab and open a new one.

**Comment by StorytellerCZ** [comment]
Strange, in my case the client is able to recover by reloading (doesn't even seem to reload the window, just my React app).
What about the observation that this happens to logged users? So far I wasn't able to entirely confirm that as in my (and I would say most apps) if you are not logged in there is less going on and less data being send to client so if there is an issue say with something like memory leak it will take much longer to manifest.

**Comment by vuhrmeister** [comment]
It always happened while logged in. But I am rarely logged out so I can't say for sure that it's only happening logged in.
Also, honestly, I didn't experience that issue for a long time since I rarely worked on that app where it happened. I have to apps which work together and I only experienced it in one app even if the base setup is pretty the same for both. So right now I can't give any more input. Will observe that issue again when I develop more on the app in question.

**Comment by StorytellerCZ** [comment]
OK, so I think I have figured my case. Seem to be that I was using too many subscription on a given page in combination with `ccorcos:subs-cache`. Or at least when I reduced all those subscriptions into one composite one the issue went away (as far as I can observe).
