### ISSUE TITLE
[1.7] Regression importing .graphql files

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#9919]
### Background

After resolving #9899, Reaction Commerce app was working great on https://github.com/reactioncommerce/reaction/pull/4265/commits/e1dc5ca3dfe8973b5fae9a9c3aeb9419fcc26f38 

### Issue

I then updated it from `1.7-rc.11` to `1.7` final (https://github.com/reactioncommerce/reaction/pull/4265/commits/63cfce2fbbb1df9ede2fd25003b6644ff571d355). It appears that this requires updating to Babel `7.0.0-beta.49` (History.md is not super clear on this). So I did that, but now it can't find the `.graphql` files, which previously were correctly imported thanks to the `babel-plugin-inline-import` plugin.

```
/Users/eric/DevProjects/reaction/node_modules/babel-plugin-inline-import/build/helper.js:72:15: Path './account.graphql'
   could not be found for
   '/Users/eric/DevProjects/reaction/Users/eric/DevProjects/reaction/imports/plugins/core/graphql/server/schemas/index.js'
```

### Reproduction

Run the app in the branch in [this PR](https://github.com/reactioncommerce/reaction/pull/4265), commit `63cfce2`. See error on startup.

### Solution

I'm submitting as a bug since this broke between `1.7-rc.11` and `1.7`, but I realize there are many layers here (Meteor / ecmascript pkg / babel preset/ babel inline import plugin), so it may be more of a configuration issue.

Note that the Jest integration tests and a pure Node app in the same repo both use similar Babel config and don't have any problem importing the `.graphql` files. So I'm guessing this might be an issue with those files not being copied somewhere by Meteor.

**Comment by benjamn** [comment]
It sounds like the `babel-plugin-inline-import` package needs to updated to work with the latest Babel beta versions.

**Comment by chrisranjana** [comment]
I experienced the same issue Path './account.graphql' could not be found for
"
So is there a fix available or commenting the block is the only alternative as of now ?

**Comment by aldeed** [comment]
@chrisranjana `babel-plugin-inline-import@3.0.0` has the fix
