### ISSUE TITLE
DevTools fails to parse SourceMap for isPlainObject

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#9922]
Meteor Version: 1.6.1.1
OS: Mac 10.13.1

Expected Behavior: DevTools should parse the sourcemap for isPlainObject and not produce the error.

Actual Behavior: DevTools gives this error `DevTools failed to parse SourceMap: http://localhost:3500/packages/isPlainObject.js.map`

To reproduce

* `meteor create --bare`
* `npm install --save airbnb-prop-types`
* Create a simple `main.html` file
* Create a client side file importing `airbnb-prop-types` (i.e. `client/airbnbImport.js`)
* Open the console
* You should now see the error

#7977 (failing to parse SourceMap) is related but the fix (Empty Cache and Hard Reload) did not fix the issue.

**Comment by LucasPadovan** [comment]
Having the same issue in a fairly new project 
![imagen](https://user-images.githubusercontent.com/993291/40893710-e17fc9fa-6779-11e8-9e3b-0549ddb6e1c6.png)

Checked under .meteor/local/build/programs/web.browser/packages and isPlainObject is missing.
Tried the previous mentioned fixes but didn't worked either.

OS is indistinct as I've tested it in the 3 major ones and it works.
Meteor version: 1.6.1.1
