### ISSUE TITLE
Error while building for android using meteor

### ISSUE THREAD

**Issue by akhilrameshcordova** [meteor/meteor#9923]
Hi, i'm trying to build a meteor app for android (Meteor 1.4.3.1)
Now when i try to run a build i get this
Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /home/user/git_repo/educore/_lms/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:font
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontStyle
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontVariationSettings
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontWeight
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:ttcIndex
   
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':processDebugResources'.
   > com.android.ide.common.process.ProcessException: Failed to execute aapt
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or
   --debug option to get more log output.
   { [Error:
   /home/user/git_repo/educore/_lms/.meteor/local/cordova-build/platforms/android/gradlew:
   Command failed with exit code 1 Error output:
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:font
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontStyle
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontVariationSettings
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontWeight
   ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute
   android:ttcIndex
   
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':processDebugResources'.
   > com.android.ide.common.process.ProcessException: Failed to execute aapt
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or
   --debug option to get more log output.] code: 1 } 'Error:
   /home/user/git_repo/educore/_lms/.meteor/local/cordova-build/platforms/android/gradlew:
   Command failed with exit code 1 Error output:\nNote: Some input files use or
   override a deprecated API.\nNote: Recompile with -Xlint:deprecation for
   details.\nNote: Some input files use or override a deprecated API.\nNote:
   Recompile with -Xlint:deprecation for details.\nERROR: In
   <declare-styleable> FontFamilyFont, unable to find attribute
   android:font\nERROR: In <declare-styleable> FontFamilyFont, unable to find
   attribute android:fontStyle\nERROR: In <declare-styleable> FontFamilyFont,
   unable to find attribute android:fontVariationSettings\nERROR: In
   <declare-styleable> FontFamilyFont, unable to find attribute
   android:fontWeight\nERROR: In <declare-styleable> FontFamilyFont, unable to
   find attribute android:ttcIndex\n\n\nFAILURE: Build failed with an
   exception.\n\n* What went wrong:\nExecution failed for task
   \':processDebugResources\'.\n>
   com.android.ide.common.process.ProcessException: Failed to execute aapt\n\n*
   Try:\nRun with --stacktrace option to get the stack trace. Run with --info
   or --debug option to get more log output.\n    at ChildProcess.whenDone
   (/home/user/git_repo/educore/_lms/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)\n
   at emitTwo (events.js:87:13)\n    at ChildProcess.emit
   (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n
   at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)'
   at ChildProcess.exitCallback
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/processes.js:137:21)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   
   => awaited here:
   at Function.Promise.await
   (/home/user/.meteor/packages/less/.2.7.9.1d9nobq++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova/project.js:994:22)
   at CordovaProject.run$
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova/project.js:440:18)
   at tryCatch
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /home/user/.meteor/packages/less/.2.7.9.1d9nobq++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
   
                                              
/home/user/.meteor/packages/less/.2.7.9.1d9nobq++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
  at Function.Promise.await (/home/user/.meteor/packages/less/.2.7.9.1d9nobq++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova/runner.js:163:17
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:291:13
  at [object Object]._.extend.withValue (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:110:14)
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:282:29
  at [object Object]._.extend.withValue (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:110:14)
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:280:18
  at [object Object]._.extend.withValue (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:110:14)
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:270:23
  at [object Object]._.extend.withValue (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:110:14)
  at Object.capture (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:269:19)
  at CordovaRunner.startRunTargets (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova/runner.js:160:35)
  at [object Object]._.extend._runOnce (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:851:21)
  at [object Object]._.extend._fiber (/home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:960:28)
  at /home/user/.meteor/packages/meteor-tool/.1.4.3_1.kfal6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:467:12

**Comment by davidecantini** [comment]
At first sight, reading the title, I thought you might have the same issue on Android that I reported in another bug, but then I notice that you're using Meteor 1.4.3.1.
Just out of curiosity, why do you need to use such an old version instead of the latest one?

**Comment by sraita** [comment]
@akhilrameshcordova 
I have the same issue on Android, and also the same logs in console:
```
ERROR: In FontFamilyFont, unable to find attribute
android:font
ERROR: In FontFamilyFont, unable to find attribute
android:fontStyle
ERROR: In FontFamilyFont, unable to find attribute
android:fontVariationSettings
ERROR: In FontFamilyFont, unable to find attribute
android:fontWeight
ERROR: In FontFamilyFont, unable to find attribute
android:ttcIndex
```

```
com.android.ide.common.process.ProcessException: Failed to execute aapt
```

after add the plugin: `cordova-android-support-gradle-release@1.2.0` and  add  code `App.setPreference("android-targetSdkVersion", "23");`  at `mobile-config.js` the issue was fixed!

**Comment by akhilrameshcordova** [comment]
Thank you sraita 

 after add these plugins:
 cordova-android-support-gradle-release@1.4.3 and add code  and 
cordova-android@6 
then add npm package
npm install xml2js

and run the project 
then remove then cordova-android@6 
Change version  cordova-android-support-gradle-release@1.2.0
delete coordova build folder from local
then run the project issue was fixed

**Comment by bbchoe** [comment]
@akhilrameshcordova @sraita thanks.  These two steps in particular helped me successfully built the Android APK:
- `meteor add cordova:cordova-android-support-gradle-release@1.2.0`
- `npm install xml2js`

However, when I eventually try to run the Android Cordova application on a device or in an emulator, it crashes after the splash screen and I get the message '<App> keeps stopping'. Some error output that seems like it might be relevant:
` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv;
        at com.google.android.gms.iid.zzo.<init>(Unknown Source)
        at com.google.android.gms.iid.zzo.<init>(Unknown Source)
        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
        at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
        at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzv" on path: DexPathList[ ...`

Any ideas on what changed in the last couple months to cause the Android build process to start failing? And ideas on solutions would be much appreciated.
