### ISSUE TITLE
Cannot publish package due to version constraints

### ISSUE THREAD

**Issue by ochicf** [meteor/meteor#9929]
Hi,

I'm getting this error while trying to publish a package:

```
$ meteor publish
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint vulcan:core@1.10.1 is not satisfied by vulcan:core 1.3.0.
Constraints on package "vulcan:core":
* vulcan:core@1.10.1 <- origenstudio:vulcan-files 0.0.2
```

If I check for existing versions of `vulcan:core`:

```
$ meteor show --show-all vulcan:core
Package: vulcan:core@1.10.1
Maintainers: vulcan
Git: https://github.com/VulcanJS/Vulcan.git
Implies: vulcan:lib

Vulcan core package, used internally.

Versions:
  1.3.0   March 23rd, 2017
  1.3.1   April 9th, 2017
  1.3.2   April 10th, 2017
  1.4.0   June 12th, 2017       installed
  1.5.0   June 12th, 2017
  1.6.0   July 26th, 2017
  1.6.1   August 1st, 2017
  1.7.0   August 2nd, 2017      installed
  1.8.0   October 6th, 2017     installed
  1.8.1   December 27th, 2017
  1.8.2   December 28th, 2017   installed
  1.8.3   January 11th, 2018
  1.8.4   January 20th, 2018
  1.8.5   January 20th, 2018
  1.8.6   January 28th, 2018
  1.8.7   January 29th, 2018
  1.8.8   February 3rd, 2018
  1.8.9   February 3rd, 2018
  1.8.11  March 6th, 2018       installed
  1.9.0   April 17th, 2018
  1.9.1   April 21st, 2018
  1.10.0  May 4th, 2018         installed
  1.10.1  May 18th, 2018        installed
```

The version I'm requiring does exists, but the version resolved seems to be the very first published for this package.

My Meteor version:

```
$ meteor --version
Meteor 1.6.1.1
```

The `package.js` of the package I want to publish:

```
Package.describe({
  name: 'origenstudio:vulcan-files',
  version: '0.0.2',
  summary: 'Provides Vulcan with the capability of uploading files to server using Meteor-Files',
  git: 'https://github.com/OrigenStudio/vulcan-files',
  documentation: 'README.md'
});

Package.onUse(api => {
  api.versionsFrom('1.6.0.1');

  api.use([
    'ecmascript',
    'vulcan:core@1.10.1',
    'ostrio:files@1.9.11',
    'origenstudio:files-helpers@0.0.2'
  ]);

  api.mainModule('lib/server/main.js', 'server');
  api.mainModule('lib/client/main.js', 'client');
});
```

Thank you in advance.

**Comment by ochicf** [comment]
As an additional info, I've tried to publish by specifying the `--release` parameter to meteor.

```
$ meteor publish --release 1.6.0.1
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint vulcan:core@1.10.1 is not satisfied by vulcan:core 1.3.0.
Constraints on package "vulcan:core":
* vulcan:core@1.10.1 <- origenstudio:vulcan-files 0.0.2

Conflict: Constraint ostrio:files@1.9.11 is not satisfied by ostrio:files 1.9.7.
Constraints on package "ostrio:files":
* ostrio:files@1.9.11 <- origenstudio:vulcan-files 0.0.2
```

As you can see with an older version it prints an additional error, so I though of doing the same withversions `1.6.1.2` and `1.7` and `1.7.0.1` without any luck (I got the same error as with `1.6.1.1`).

**Comment by benjamn** [comment]
Try updating `api.versionsFrom('1.6.0.1')` to `api.versionsFrom('1.6.1')`?

I'm guessing `vulcan:core` depends on a version of some Meteor core package (likely `babel-compiler`) that was different in Meteor 1.6.0.1 than it is in Meteor 1.6.1.1. So if you're using `vulcan:core@1.10.1`, then you're effectively already restricting your package to Meteor 1.6.1, so using `api.versionsFrom('1.6.1')` shouldn't limit the audience of your package any further.

If you don't actually need `vulcan:core@1.10.1`, then you could change that version constraint to `@1.3.0` to allow any version.

**Comment by ochicf** [comment]
Hi @benjamn,

I finally managed to publish the package. I placed the package inside the `packages` folder of an existing meteor@1.6.1 project and it allowed me to publish it. If I have the package anywhere NOT inside a meteor project, then it won't let me publish it.

Is this the expected behavior? I'd never experienced that when publishing any other package.

Thanks.
