### ISSUE TITLE
http://speakerkit.meteor.com/ is down but is referenced on YouTube

### ISSUE THREAD

**Issue by mturley** [meteor/meteor#9930]
Fails to load in Chrome:

![screen shot 2018-06-01 at 1 45 53 pm](https://user-images.githubusercontent.com/811963/40855271-2c43c204-65a2-11e8-97f1-a23b9474bd0b.png)

Cannot be resolved by icmp ping:

![screen shot 2018-06-01 at 1 46 41 pm](https://user-images.githubusercontent.com/811963/40855304-40d33cea-65a2-11e8-8b27-6df7d0cb37d9.png)

Is referenced in the description at https://www.youtube.com/user/MeteorVideos

![screen shot 2018-06-01 at 1 47 15 pm](https://user-images.githubusercontent.com/811963/40855378-6c6f544c-65a2-11e8-9e63-144579eff13c.png)

Love these videos by the way :)

**Comment by elmarti** [comment]
I can't speak for that site in particular, but being able to freely deploy to a meteor.com subdomain was retired a year or 2 ago so it's likely that this URL will never work again.

**Comment by mturley** [comment]
Makes sense, I guess I am more reporting an issue in that video description then.

**Comment by elmarti** [comment]
Still an issue

**Comment by filipenevola** [comment]
hi @mturley thanks for reporting.

Is this video linked somewhere or did you find just browsing in the channel?

I just fixed the description.

BTW, we are going to have new content in the youtube channel soon 😉

**Comment by mturley** [comment]
@filipenevola I think it used to be featured on the meteor.com homepage, I can't remember how I got there but I thought it was from the site. Looks like it's not there anymore though. Thanks for responding!

**Comment by copleykj** [comment]
Looks like it has been moved from a subdomain to page in the main site. There is a link in the footer nav of meteor.com

https://www.meteor.com/speaker-kit
