### ISSUE TITLE
npm audit/update issues with meteor npm@5.10

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#9932]
_Disclaimer:_
I'm not sure if this would be better suited
- on the npm github issues (seems to be an issue with 5.10 in general)
- or a feature request in the feature request repo (works with npm@6.1)
- it's an issue we face with meteor 1.7 for us so I opened it here

We're using jest-cli and some other npm packages which contain(according to npm audit) vulnerable packages as dependencies. 

`meteor npm audit` shows some help to fix most of the problems like e.g.
```
# Run  npm update fill-range --depth 11  to resolve 43 vulnerabilities
```
which results in an error with `meteor npm`
[2018-06-03T15_13_19_332Z-debug.log](https://github.com/meteor/meteor/files/2066063/2018-06-03T15_13_19_332Z-debug.log)

but runs fine using `npm@6.1`

**Comment by benjamn** [comment]
Did you run `npm update ...` or `meteor npm update ...`?

**Comment by sakulstra** [comment]
@benjamn thanks for looking into this. The log is from running `meteor npm update fill-range --depth 11` as you can see in the last few lines
```
67 verbose stack TypeError: Cannot read property 'filter' of undefined
67 verbose stack     at outdated_ (/home/lukass/.meteor/packages/meteor-tool/.1.7.0.1oz93n1.utqr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/outdated.js:205:57)
(...)
```

I get a similar error when running `nvm use 5.10 && npm update fill-range --depth 11` though.

When running with a more recent version of npm(6.1) though the issue is fixed.
If i got the npm wiki right, they don't usually do updates for older version as they don't follow any LTS schedule... so I thought the proper solution would be to update meteors npm version to 6.1 instead - that's why i opened the issue here and not over there.

**Comment by benjamn** [comment]
Yeah, `npm@5.10.0` was an effort to backport some `npm@6` features to `npm@5`: https://github.com/npm/npm/releases/tag/v5.10.0

You might be able to update your own `meteor npm` version by running
```
meteor npm install --global npm@latest
```
You're right that Meteor will need to publish a new release after updating npm, since this trick won't work automatically for anyone else working on your project, but it might be enough to enable you to debug the audit issues?

**Comment by sakulstra** [comment]
This seems to work just fine:
```
meteor npm i -g npm@latest
meteor npm audit fix
```

Is it generally "save" to just update/change the npm version shipped with meteor? I thought it's somehow patched and wasn't sure if updating breaks sth under the hood.

**Comment by benjamn** [comment]
No, we don't patch npm currently, so updating it should be safe. The primary risk is that something might have changed in terms of how shrinkwrap/`package-lock.json` files are processed, which could interfere with Meteor's automatic installation of `Npm.depends`-style package dependencies. If you have any local Meteor packages that have npm dependencies, just be on the lookout for problems there.

**Comment by lmachens** [comment]
Any idea why it is not updating on Windows? I tried to run this as admin but it still have the old npm version.
```
> meteor npm i -g npm@latest

C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\npm -> C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\node_modules\npm\bin\npm-cli.js
C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\npx -> C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\node_modules\npm\bin\npx-cli.js
+ npm@6.1.0
updated 1 package in 15.423s

> meteor npm --version

5.10.0
```

**Comment by sakulstra** [comment]
the issue seems to be solved at least for me by upgrading to latest meteor so i'll close it for now
