### ISSUE TITLE
1.7.0.1 changes file load order

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#9935]
After updating to `v1.7.0.1`, globals created by Atmosphere packages are no longer present on startup. They used to work both in `v1.5.x` and `v1.6.x`, where globals created by packages were available when the app was started.

Moving the app code that relies on the global variable inside a `Meteor.startup` callback fixes the situation.

So, for example, having:

- a package that creates a global `MySpecialClass`
- ...and the following app code:

```js
// lib/methods/test/mySpecialClass.js

MySpecialClass.methods = {};
```

...will throw this error on startup:

```
W20180604-17:31:17.703(3)? (STDERR) TypeError: Cannot set property 'methods' of undefined
W20180604-17:31:17.704(3)? (STDERR)     at mySpecialClass.js (lib/methods/test/mySpecialClass.js:3:1)
W20180604-17:31:17.704(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180604-17:31:17.704(3)? (STDERR)     at require (packages/modules-runtime.js:238:16)
```

Update process went like this:

```
$ meteor update --release 1.7.0.1
Changes to your project's package version selections from
updating the release:
babel-compiler             upgraded from 7.0.9 to 7.1.0
boilerplate-generator      upgraded from 1.4.0 to 1.5.0
ddp-server                 upgraded from 2.1.2 to 2.2.0
dynamic-import             upgraded from 0.3.0 to 0.4.0
ecmascript                 upgraded from 0.10.9 to 0.11.0
ecmascript-runtime         upgraded from 0.5.0 to 0.7.0
ecmascript-runtime-client  upgraded from 0.6.2 to 0.7.1
ecmascript-runtime-server  upgraded from 0.5.0 to 0.7.0
es5-shim                   upgraded from 4.7.3 to 4.8.0
facebook-oauth             upgraded from 1.4.1 to 1.5.0
meteor                     upgraded from 1.8.6 to 1.9.0
meteor-base                upgraded from 1.3.0 to 1.4.0
modern-browsers            added, version 0.1.1
modules                    upgraded from 0.11.8 to 0.12.0
modules-runtime            upgraded from 0.9.2 to 0.10.0
mongo                      upgraded from 1.4.7 to 1.5.0
npm-mongo*                 upgraded from 2.2.34 to 3.0.7
promise                    upgraded from 0.10.2 to 0.11.1
server-render              removed from your project
shim-common                removed from your project
socket-stream-client       upgraded from 0.1.0 to 0.2.1
tracker                    upgraded from 1.1.3 to 1.2.0
webapp                     upgraded from 1.5.0 to 1.6.0

$ meteor yarn add @babel/runtime@latest meteor-node-stubs@latest
yarn add v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
├─ @babel/runtime@7.0.0-beta.49
└─ meteor-node-stubs@0.4.1
info All dependencies
├─ @babel/runtime@7.0.0-beta.49
├─ builtin-status-codes@3.0.0
├─ meteor-node-stubs@0.4.1
├─ stream-http@2.8.3
└─ to-arraybuffer@1.0.1
✨  Done in 23.11s.
```

**Comment by benjamn** [comment]
I think we need to know more about the package that exports the `MySpecialClass` global in order to investigate this. I don't know of anything that changed in Meteor 1.7 that should have affected this.

**Comment by arggh** [comment]
I'll try to squeeze a reproduction out of our app.

**Comment by arggh** [comment]
I started working on the repro and immediately figured out the cause. For some reason, in the `package.json` the main module is declared like so:

```js
api.mainModule('models.js', ['client', 'server']);
api.mainModule('serverExtends.js', 'server');
```

Apparently this has worked with `1.5.x` and `1.6.x`, even if it seems a bit sketchy. Should it work?

**Comment by benjamn** [comment]
That *should* just override the main module on the server to be `serverExtends.js` instead of `models.js`, which means `models.js` would not run on the server (unless it is imported by `serverExtends.js`), but I could be wrong about that!

**Comment by arggh** [comment]
It _used_ to work just fine, stuff in `models.js` did run in server. I'm happy to close this issue and refactor our rogue package to make more sense. Unless this issue is worth keeping open for further research into why this used to work and now doesn't?

**Comment by arggh** [comment]
Content of `serverExtends.js` is just one import,

```
import './collections/server/guests';
```

→ `guests.js` doesn't import anything besides a single npm package.

**Comment by benjamn** [comment]
Ah, in that case, you could just change it to `api.addFiles('serverExtends.js', 'server')` so that it doesn't override the `api.mainModule`.

**Comment by arggh** [comment]
Thanks, this was an easy fix.

Clearly _something_ has changed in how the file loading from packages works, since the same package works and loads `models.js` on the server with Meteor `1.6.x`, but not with `1.7.0.1`, but I'll still close this issue since the code wasn't _supposed_ to be working in the first place.
