### ISSUE TITLE
[1.7.0.1] Meteor.wrapAsync no longer works, returning a cursor instead of ajax results

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9936]
We use `Meteor.wrapAsync` to access the collection aggregation up until meteor 1.6. But after upgrading to 1.7.0.1, the returned result is now a ‌`AggregationCursor` and no longer a aggregation result.

```
let rawDonations = Donations.rawCollection();
let rawAggregate = Meteor.wrapAsync(rawDonations.aggregate, rawDonations);
let res = rawAggregate(pipeline);
res => AggregationCursor
```

**Comment by spencern** [comment]
I think we may be seeing this in Reaction as well.

**Comment by sabativi** [comment]
I think it is a change on the mongo driver, add a .toArray at the end, this will return a promise that you can get on the client.
I may be wrong but this works for me, my app is in production with 1.7 and it is the only things that I had to do.

**Comment by WayneUong** [comment]
@sabativi Works wonderfully. But I struggle to find a way to resolve the promise. I need to get the results, and process them before returning them to clients. I know await can do that but I have to put it in an async function, which is not always possible.

**Comment by klaussner** [comment]
@sabativi is right, the new 3.x version of the MongoDB driver passes an `AggregationCursor` to the callback, whereas the 2.x version passed the aggregation result. From the [driver changelog](https://github.com/mongodb/node-mongodb-native/blob/885aeeb7e35303d31ba74453dac41433ffa49414/CHANGES_3.0.0.md#collectionprototypeaggregate):

> `Collection.prototype.aggregate` now returns a cursor if a callback is provided. It used to return the resulting documents which is the same as calling `cursor.toArray()` on the cursor we now pass to the callback.

The callback arguments are documented here: http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#~aggregationCallback.

@WayneUong You can use Meteor's `Promise.await` in non-`async` functions:

```js
import { Promise } from "meteor/promise";

// `aggregate` returns a cursor, so you don't need a callback or `wrapAsync`!
const result = Promise.await(rawDonations.aggregate(pipeline).toArray());
```
