### ISSUE TITLE
dynamic-imports broken on electron due to unsupported CORS header

### ISSUE THREAD

**Issue by call-a3** [meteor/meteor#9952]
dynamic-imports allows remote origins to fetch the imports by settings CORS headers, but does so by setting the `Access-Control-Allow-Headers` header to `*`.
As referenced by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Compatibility_notes, this is not supported in all recent browsers. For my case specifically, it's not supported by the version of chromium included in the latest electron.

A simple fix (for which I will soon create a PR) would (in my opinion) be to bounce back the `Access-Control-Request-Headers` header value from the options request if it is provided.

**Comment by benjamn** [comment]
Sounds reasonable! Just in case you have any trouble finding the relevant code, [here](https://github.com/meteor/meteor/blob/38f570abc096b1042f555b7b646dc4ea10fee06e/packages/dynamic-import/server.js#L69) it is.

**Comment by benjamn** [comment]
This should be fixed in `dynamic-import@0.4.1`, which you can update to by running `meteor update dynamic-import` (as long as you're using Meteor 1.7.x).
