### ISSUE TITLE
[1.7] Any client should be able to request any <hash>.{js,css,...} asset

### ISSUE THREAD

**Issue by morloy** [meteor/meteor#9953]
Currently, Meteor returns different content based on the User-Agent. This breaks the setup with a CDN such as CloudFront (which uses "Amazon CloudFront" as UA).

Since the JS files are named by their hash, everything should fine. However, Meteor returns a 404 if you access the "modern" JS bundle using a "legacy" UA!

The easiest fix would be to include the modern JS files also in the legacy bundle.
Another option could be to use different public addresses for each bundle (e. g. `/web.browser/5c8f3031f7e146f0a3d07cadb12848c04bb176b5.js?meteor_js_resource=true`).

**Comment by benjamn** [comment]
It surprises me that a CDN would not forward the end-user client UA when reading through from the origin? A CDN needs to be able to serve both modern and legacy assets, so forcing a single UA of its own choosing seems unacceptable…

**Comment by morloy** [comment]
The purpose of the CDN is to minimize interaction with the original server. But the CDN can’t decide between modern and legacy itself. So, either the CDN needs to cache a different file *per each UA*, or the content must be independent of the UA.

**Comment by benjamn** [comment]
> So, either the CDN needs to cache a different file *per each UA*

That's why [we set the `Vary: User-Agent` header](https://github.com/meteor/meteor/blob/38f570abc096b1042f555b7b646dc4ea10fee06e/packages/webapp/webapp_server.js#L428-L432) on all responses that could be either modern or legacy (182c426c6d9d1ce0fc725c8a6f93fae96ac81c4e). A CDN that forwards the original UA and reads from the origin only when it hasn't previously cached the resource should be able to get this right.

**Comment by benjamn** [comment]
Ok, I see what you mean. This could be an good opportunity to put Lambda functions in front of CloudFront, to categorize user agents as modern or legacy before requesting resources from the CDN, but that's beginning to sound pretty complicated.

By the way, during the 1.7 beta process, we did try prefixing static asset URLs like you mentioned, but it ended up causing too many problems for resolving relative URLs, especially in CSS files (see https://github.com/meteor/meteor/pull/9849).

I agree making all `web.*` static resources available to any client in production is a practical solution to this problem.

**Comment by morloy** [comment]
What’s the difference between modern and legacy assets? It looks like, they’re the same, except the boilerplate pointing to different JS assets, right?
Then it would make sense to distinguish only in exactly that file and leave the rest the same.
Or, go even further, and make the distinction client side.

**Comment by benjamn** [comment]
Sorry, I'm using the word "asset" in a generic sense here: any static resource served via HTTP, including JS, CSS, images, etc.

In Meteor, there's also a notion of assets added with `api.addAssets` or placed in the `public/` folder. While it's possible to have a single asset path that has different modern and legacy versions, that's not recommended and probably doesn't make much sense, so I think for the most part we can assume there is no difference between modern and legacy assets (except for JS or CSS, where Meteor chooses the production filename hash).

**Comment by morloy** [comment]
For the record, I found a reasonable workaround:
1. In CloudFront, set the User-Agent to that of a modern browser (Distributions->Origins->Origin Custom Headers)
2. Conditionally enable the CDN in the boilerplate only for modern browsers
```
WebAppInternals.registerBoilerplateDataCallback('cdn', (req, data, arch) => {
  if (arch === 'web.browser') {
    data.bundledJsCssUrlRewriteHook = url => `${cdnUrl}${url}`; // eslint-disable-line no-param-reassign
  }
  return true;
});
```

**Comment by benjamn** [comment]
As long as that doesn't put too much load on your servers, it definitely works!

**Comment by morloy** [comment]
Wow, thanks for fixing this issue so fast, @benjamn!
