### ISSUE TITLE
[1.7.0.1] Building the application when testing has become very slow

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9956]
I'm sure this is related to the double bundling, but is there any way to opt out of it ?

Previously app was restarting in 5-6 seconds, now it takes over 15s

**Comment by benjamn** [comment]
Have you tried building the application with `meteor run` at least once before running `meteor test`? Testing creates a new temporary `.meteor/local` directory, but it tries to symlink back to the existing one, so it might help if you already have a `.meteor/local` directory from a previous non-test build.

**Comment by theodorDiaconu** [comment]
Tried the run, unfortunately does not work. Still super slow.
