### ISSUE TITLE
Meteor create --minimal is forcing meteor server restart on client changes

### ISSUE THREAD

**Issue by Maxim-Filimonov** [meteor/meteor#9960]
I have been using --minimal template on my project and starting to notice some strange behavior - every time I change a template or CSS file meteor restarts the whole server which leads to full page reload.
`--full` template doesn't have the same problem when used with the same version - edit any style it triggers `client modified` and hot reload instead of full server restart.
I have just tried it on [a newly created](https://github.com/Maxim-Filimonov/meteor_bug_minimal_server_restart) project and it's still the same problem. 
```
=> meteor
# edit main.css in any way
=> Server modified -- restartin  [ProgressDisplayFull keepalivI20180607-17:54:37.161(8)? Greetings from /server/main.js!
=> Meteor server restarted
```
Do I need to add an extra package to make it work without full server restart?

**Comment by Maxim-Filimonov** [comment]
After adding `hot-code-push ddp` it fixed the problem. Now is the bigger question does meteor minimal really make sense without those things? Maybe i'm misunderstanding use case for minimal

**Comment by met5678** [comment]
+1 agree, `DDP` and `hot-code-push` seem to me like foundational selling-points of Meteor and it feels a bit weird to have them not there, even in the `minimal` version.

**Comment by mitar** [comment]
Still relevant.

**Comment by mitar** [comment]
Still relevant.

**Comment by StorytellerCZ** [comment]
Just adding `hot-code-push` is enough. `ddp` is included in it.
