### ISSUE TITLE
App doesn't work properly on db re-connection in production

### ISSUE THREAD

**Issue by filosof86** [meteor/meteor#9962]
Hi guys,

Version: METEOR@1.6.0.1
OS: CentOS Linux release 7.4.1708

STR:
1. Deploy meteor bundle and install it on the CentOS server.

2. Create MongoDB replication set for meteor app which consists of 3 nodes.
The following ENV variables are defined:
MONGO_URL=mongodb://<first_mongo_instance>:3001,<second_mongo_instance>:3001,<third_mongo_instance>:3001/meteor?replicaSet=meteor
MONGO_OPLOG_URL=mongodb://<first_mongo_instance>:3001,<second_mongo_instance>:3001,<third_mongo_instance>:3001/local?replicaSet=meteor

3. Set up Nginx server as a proxy for meteor application.

4. Shut down 2 or three mongo nodes, wait for some time, so the app throws some errors like "connection refused" or 'failed to connect to server', etc.

5. Start the MongoDB replica again
6. Check the application state via a browser.
7. Try to update something in the DB to check the reactivity

The actual behavior: the app is hung until it's restarted, it doesn't update any reactive data, the periodical tasks are not performed, a WebSocket connection is established, but it doesn't populate any data, just 'pings'.

The expected result: the meteor server is crashed on DB connection errors with some error code > 0. 

Remarks:
The application works correctly while changing the Primary node within the replica set but not always, unfortunately. And it is always stuck when no DB connection available at all.
I believe something similar has already been fixed within https://github.com/meteor/meteor/issues/3038
However, it seems that the fix doesn't work for the production app.

Thank you in advance.

**Comment by veered** [comment]
This might resolve your issue https://github.com/meteor/meteor/commit/afb7d23d045602cd7f9d4b7ae61081c4bcc3b12f

This change is in Meteor 1.7

**Comment by veered** [comment]
If you want to force the server to crash when DB connection errors happen, you could hook into the DB event handlers. Here is some code we use for logging DB connection issues:

```
let Mongo = MongoInternals.defaultRemoteCollectionDriver().mongo,
     db = Mongo.db,
     multiplexers = Mongo._observeMultiplexers
;

db.s.topology.on('close', err =>  {
  console.log(err.stack);
  console.log(`The following observes are active \n${_.keys(multiplexers).join('\n')}`);
});
db.s.topology.on('reconnect', data => console.log('Successfully reconnected to mongo', data));
db.s.topology.on('reconnectFailed', data => console.log('Failed to reconnect to mongo', data));
db.s.topology.on('left', data => console.log('A server left the replica set', data));
db.s.topology.on('joined', data => console.log('A server joined the replica set', data));
```

I slightly modified this code when copying it from our codebase, so apologies if it's slightly wrong. But the gist of it ought to be correct.

**Comment by filosof86** [comment]
Hi @veered 

Thank you very much for your reply!
Yes, I've actually implemented the workaround with 'MongoInternals' in my app already, but your example is more extended than the code I'm using, so it will be useful for me, thanks.

About https://github.com/meteor/meteor/commit/afb7d23d045602cd7f9d4b7ae61081c4bcc3b12f

Do I have to update the meteor version to 1.7 or it will be enough just to update 'npm-mongo' like it was said in https://github.com/meteor/meteor/issues/8598
Is it possible to update that package instead of updating all the stuff considering the meteor version I use now?

TIA

**Comment by filosof86** [comment]
OK, then. Thank you for your help!
