### ISSUE TITLE
meteor shell is unresponsive after reconnecting

### ISSUE THREAD

**Issue by dariusj18** [meteor/meteor#9964]
Meteor version 1.7.0.1
Windows 10 Pro version 1803 build 17134.48 (April 2018 update)
Powershell 5.1.17134.48(and windows cmd as well)
Expected to be able to do anything.

```> Server unavailable (waiting to reconnect)

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

>
```

After this happens, I cannot type anything, nor hit CTRL-C to break execution.

**Comment by smeijer** [comment]
Same here. Meteor 1.8 on Windows 10.

**Comment by foobarbecue** [comment]
further activity

**Comment by filipenevola** [comment]
thanks @foobarbecue , I already labeled it as `confirmed` then stale bot is going to ignore it.

**Comment by smeijer** [comment]
I guess stale bot doesn't listen to that label any more?

**Comment by filipenevola** [comment]
@smeijer I was renaming the labels but I had a problem in my back and I had to stop in the middle, sorry, the renaming was finished already and stale bot updated.

**Comment by StorytellerCZ** [comment]
Tested on Ubuntu and no problem. Most likely the hanging Windows issue.
