### ISSUE TITLE
Less waiting for rebuilds when changing files

### ISSUE THREAD

**Issue by dobesv** [meteor/meteor#9969]
Currently it takes 30-120 seconds to build our meteor app.

When we run meteor, it automatically starts to rebuild as soon as it detects a change.  However, I often make a few changes in a row.  When I do that, I have to wait for the first build to complete and then I have to wait for a subsequent build to complete.  It would be great if the first build were terminated immediately if I made another change, so I only have to wait for one build to complete.

Also, it would be really great if the server continued to run while a rebuild was running.  I often wish that while I was waiting I could do a little more testing or whatever in the app.  However, the meteor server is killed immediately so I can't do much, only things that are client only.

**Comment by dobesv** [comment]
Rebuilds used to take over a minute minimum until I upgraded to a faster computer with 64GB of RAM, NVMe SSD drives, and a hexacore Intel processor.  Initial builds are usually double rebuild time.

I don't know why builds are so long, I probably google every week about build times and I've tried filing an issue here with meteor but I've never made any real progress on the matter.

I'm still using meteor 1.6 because 1.7 breaks our app all kinds of weird ways.

**Comment by pmogollons** [comment]
@dobesv I had a related issue and tracked down to the semantic-ui package that uses less. My builds were taking 10 secs, I removed semantic and now it takes less than 4, and it will be faster when we are able to disable legacy bundle on development.

If you are using semantic-ui or another big package that uses less you can try removing it and checking if that improves your build speed.

Hope that helps.

**Comment by benjamn** [comment]
> I'm still using meteor 1.6 because 1.7 breaks our app all kinds of weird ways.

I look forward to the issues that you will file about those problems. Because Meteor is a framework that attempts to provide an upgrade path, there's this strange inversion of responsibility, where it feels like Meteor's fault when something breaks, even if that blame is completely misplaced. The only way forward is to share your problems with people who could help you, so that we can sort out what you could be doing differently from actual bugs that Meteor needs to fix.

**Comment by dobesv** [comment]
Yeah, I've wanted to file some issues but first I need to extract a reproduction or understand the cause of the issue(s).  So far it's all just total head-scratchers for me.  The finger points at meteor 1.7 because the issues occur in 1.7 but not in 1.6.

**Comment by dobesv** [comment]
@pmogollons We're not using that package as far as I know, but experimenting with removing packages does seem like a good idea.  I guess I had thought the offending package would show up in the meteor profile output somehow.  But maybe it's hidden between the lines somewhere.

**Comment by dobesv** [comment]
![image](https://user-images.githubusercontent.com/327833/41679224-539c8f90-7482-11e8-8938-39a1679dfdaf.png)

![image](https://user-images.githubusercontent.com/327833/41679295-8fbcb536-7482-11e8-8ed6-95618f695758.png)

**Comment by veered** [comment]
Could you please upload the actual `.cpuprofile` file?

**Comment by dobesv** [comment]
[meteor-app-profiles.zip](https://github.com/meteor/meteor/files/2120896/meteor-app-profiles.zip)

**Comment by veered** [comment]
Do you have a lot of stuff in your `node_modules/` folder?

**Comment by dobesv** [comment]
Our list of direct dependencies doesn't seem too out of control, though.  A quick scan through doesn't show anything that stands out as low hanging fruit we could eliminate.

```
  "dependencies": {
    "@babel/polyfill": "7.0.0-beta.49",
    "@babel/runtime": "7.0.0-beta.49",
    "@meteorjs/ddp-graceful-shutdown": "0.9.2",
    "@okgrow/auto-analytics": "2.0.0",
    "apollo-cache-inmemory": "1.2.2",
    "apollo-client": "2.3.2",
    "apollo-link": "1.2.2",
    "apollo-link-debounce": "2.0.0",
    "apollo-link-error": "1.1.0",
    "apollo-link-http": "1.5.4",
    "apollo-link-retry": "2.2.4",
    "apollo-link-serialize": "2.0.0",
    "apollo-link-ws": "1.0.8",
    "apollo-server-express": "1.3.6",
    "async-each": "1.0.1",
    "aws-sdk": "2.257.1",
    "axios": "0.18.0",
    "bcrypt": "1.0.3",
    "bluebird": "3.5.1",
    "body-parser": "1.18.3",
    "bourbon": "4.3.4",
    "bunyan": "1.8.12",
    "cloudconvert": "1.1.2",
    "color": "2.0.1",
    "cors": "2.8.4",
    "dataloader": "1.4.0",
    "draft-js": "0.10.5",
    "draft-js-alignment-plugin": "2.0.3",
    "draft-js-anchor-plugin": "2.0.2",
    "draft-js-drag-n-drop-plugin": "2.0.3",
    "draft-js-emoji-plugin": "2.0.6",
    "draft-js-export-html": "1.2.0",
    "draft-js-focus-plugin": "2.0.4",
    "draft-js-image-plugin": "2.0.5",
    "draft-js-inline-toolbar-plugin": "2.0.3",
    "draft-js-plugins-editor": "2.0.8",
    "draft-js-resizeable-plugin": "2.0.6",
    "epimetheus": "1.0.55",
    "express": "4.16.3",
    "faker": "3.1.0",
    "graphql": "14.0.0-rc.1",
    "graphql-redis-subscriptions": "1.5.0",
    "graphql-tag": "2.9.2",
    "graphql-tools": "3.0.2",
    "graphql-type-json": "0.2.1",
    "hiredis": "0.5.0",
    "hubspot": "1.3.0",
    "immutability-helper": "2.7.0",
    "immutable": "3.8.2",
    "intercom-client": "2.9.1",
    "ioredis": "3.2.2",
    "iterall": "1.2.2",
    "ix": "2.3.5",
    "jquery": "3.3.1",
    "katex": "0.9.0",
    "lodash": "4.17.5",
    "meteor-node-stubs": "0.3.3",
    "mixpanel-browser": "2.19.0",
    "moment": "2.22.2",
    "mongodb": "3.0.10",
    "msr": "1.3.4",
    "node-uuid": "1.4.8",
    "normalize.css": "4.2.0",
    "papaparse": "4.3.7",
    "paper": "0.11.5",
    "postal": "2.0.5",
    "prop-types": "15.6.1",
    "radium": "0.24.0",
    "rc-slider": "8.6.1",
    "react": "16.4.0",
    "react-addons-pure-render-mixin": "15.6.2",
    "react-addons-shallow-compare": "15.6.2",
    "react-addons-update": "15.6.2",
    "react-apollo": "2.1.4",
    "react-create-class": "1.0.0",
    "react-datetime": "2.14.0",
    "react-dnd": "2.6.0",
    "react-dnd-html5-backend": "2.6.0",
    "react-dnd-multi-backend": "3.1.2",
    "react-dnd-touch-backend": "0.4.0",
    "react-dom": "16.4.0",
    "react-helmet": "5.2.0",
    "react-load-script": "0.0.6",
    "react-loadable": "5.4.0",
    "react-modal": "3.4.5",
    "react-mounter": "1.2.0",
    "react-notification-system": "0.2.17",
    "react-popover": "0.5.7",
    "react-popper": "0.10.4",
    "react-rating": "1.1.2",
    "react-resize-detector": "2.3.0",
    "react-responsive": "4.1.0",
    "react-router": "4.3.1",
    "react-router-dom": "4.3.1",
    "react-s3-uploader": "4.8.0",
    "react-select": "1.2.1",
    "react-stripe-elements": "2.0.0",
    "react-textarea-autosize": "6.1.0",
    "react-timeago": "4.1.9",
    "react-virtualized": "9.19.1",
    "react-waypoint": "8.0.1",
    "rebass": "1.0.7",
    "recompose": "0.27.1",
    "redis": "2.8.0",
    "redis-eventemitter": "2.0.1",
    "redux": "4.0.0",
    "sanitize-html": "1.18.2",
    "simpl-schema": "0.3.2",
    "stripe": "4.22.0",
    "styled-components": "3.3.2",
    "subscriptions-transport-ws": "0.9.5",
    "ts-custom-error": "2.2.1",
    "unfetch": "3.0.0",
    "uuid": "3.2.1",
    "v8-profiler": "5.7.0",
    "webfontloader": "1.6.28",
    "webpack": "3.10.0",
    "zipcodes": "6.0.0"
  },
```

**Comment by veered** [comment]
I would say that definitely counts as "a lot of stuff", at least by size on disk :)

Apart from trying out #9825 and #9983, I think it's definitely worth seeing if there are any packages that are responsible for most of that size (using `du` on the subfolders in `node_modules`).

**Comment by benjamn** [comment]
@dobesv To be clear, I will never use the size of your `node_modules` as an excuse for giving up on helping you. Your dependencies list does indeed look pretty reasonable, and Meteor should work well regardless of how large your transitive dependency tree gets. However, it's possible that we're doing some kind of expensive work that's proportional to the number of top-level packages in `node_modules`, and that would definitely be a contributing factor to your long rebuild times.

**Comment by veered** [comment]
@benjamn The profile is spending most of the time in `_scanFile`, which is going super slow because the optimistic cache is recomputing on every file being scanned. Here's a small section of the flamechart where that's happening:

<img width="1161" alt="screen shot 2018-06-20 at 4 38 59 pm" src="https://user-images.githubusercontent.com/247408/41690021-7b04bef6-74a8-11e8-977a-b56da6c21101.png">
.

**Comment by dobesv** [comment]
I guess if it has to scan / touch / process every single files in node_modules, then even at 1ms per file that's 180 seconds.  So perhaps node_modules is the issue.  However, other build systems don't seem to have this issue, they just load whatever they need from there instead of reading everything.

**Comment by pagesrichie** [comment]
On a previous project of mine, I had 3/4 the size of his node_modules and I did notice things running slower.

@benjamn Plz do let us know when you've fixed the LESS slow compiling on multiple issue, and which meteor beta version when it's released, looking forward to applying it to my project!

**Comment by pagesrichie** [comment]
On a previous project of mine, I had 3/4 the size of his node_modules and I did notice things running slower.

@benjamn Plz do let us know when you've fixed the LESS slow compiling on multiple issue, and which meteor beta version when it's released, looking forward to applying it to my project as currently the less compiling is sloooow!

**Comment by benjamn** [comment]
@pagesrichie Try updating to the latest Meteor 1.7.1 beta?
```sh
meteor update --release 1.7.1-beta.17
```
