### ISSUE TITLE
Overriding core package locally does not work

### ISSUE THREAD

**Issue by ayalpani** [meteor/meteor#9978]
Hi, 

a few days ago I opened this issue https://github.com/meteor/meteor/issues/9970 about a hard-coded value in the boilerplate-generator package. @benjamn hinted me to copying the package locally which worked perfectly, initially. 

This is what I did:

1. created a `packages` folder in my project's root folder
2. copied `boilerplate-generator` folder from meteor into the `packages` folder. Results in `/myproject/packages/boilerplate-generator`
3. Changed code in `template-web.cordova.js`
4. Just to be sure, I deleted `rm -rf ~/.meteor/packages/boilerplate-generator`
5. `meteor add boilerplate-generator`
6. `meteor run android-device`

Don't know what happened but while this **did** work last week, it **doesn't anymore** today. It always falls back to the `boilerplate-generator` code from the core, ignoring my locally changed package. I have no idea why. 

To be sure my local package is added when using `meteor add`, I locally changed the description in `package.js` of `boilerplate-generator`. 

```
$ meteor add boilerplate-generator
                                              
boilerplate-generator: You are reading my changed description!
```
Also:

```
$ meteor list

...
boilerplate-generator                           1.4.0+ You are reading my changed description!
...
```

So obviously my local version is added but not used. 

How can this possibly happen? If it doesn't use my local version, where does it fall back to then?
Any help is appreciated, thanks!

**Comment by Sanjo** [comment]
Have you tried `meteor reset` ([Docs](https://docs.meteor.com/commandline.html#meteorreset))? If that doesn't work, try Meteor 1.6, there it defenitely worked for me some days ago. I haven't tried 1.7 and I also haven't run for android-device.

**Comment by ayalpani** [comment]
Hi @Sanjo, I am already using Meteor 1.6.1.2

Unfortunately `meteor reset` didn't change anything, my local package ist still being ignored.

**Comment by benjamn** [comment]
Oh, if you're using Meteor 1.6.1.2, then Meteor may be forcing the same core package versions that were current when 1.6.1.2 was released (including `boilerplate-generator`). Maybe checkout the `origin/release-1.6.1.2` branch of Meteor and copy [`packages/boilerplate-generator`](https://github.com/meteor/meteor/blob/release-1.6.1.2/packages/boilerplate-generator/) from that, with your changes applied?

**Comment by ayalpani** [comment]
Hi @benjamn !

I followed these steps:

1. downloaded https://github.com/meteor/meteor/releases/tag/release/METEOR@1.6.1.2
2. unpacked and modified `packages/boilerplate-generator` to local `packages` folder
3. `meteor remove boilerplate-generator`
4. `meteor add boilerplate-generator` => shows success message with my changed package-description 
visible
5. `meteor run android-device`

Unfortunately, the build still ignores my local package. 

> Meteor may be forcing the same core package versions that were current when 1.6.1.2 was release

From which directory would the build take the actual source code for `boilerplate-generator` from, when it enforces?

**Comment by benjamn** [comment]
Likely `~/.meteor/packages/boilerplate-generator/1.4.0` (or whatever version it decides to use).

**Comment by ayalpani** [comment]
Ok, so I thought if that's the case, why not directly change the code in `~/.meteor/packages/boilerplate-generator/1.4.0`

I did but it did have no effect. Still, the default boilerplate is used. 

Then, I tried this:

In between steps 2 and 3 of my previous post, I deleted the directory you mentioned:

1. downloaded https://github.com/meteor/meteor/releases/tag/release/METEOR@1.6.1.2
2. unpacked and modified `packages/boilerplate-generator` to local `packages` folder
+ deleted `rm -rf ~/.meteor/packages/boilerplate-generator/`
3. `meteor remove boilerplate-generator`
4. `meteor add boilerplate-generator` => shows success message with my changed package-description 
visible
5. `meteor run android-device`

Also, with no effect on my app. And - other than I had expected - the directory  `~/.meteor/packages/boilerplate-generator/1.4.0` isn't restored by `meteor run android-device`

So as far as I understand, there is only one version of the boilerplate code available on my computer, located in my project-local packages directory. But then, where does the code come from, that is compiled into my app?

**Comment by ayalpani** [comment]
Unfortunately it also does not seem to work for a complete new meteor (1.7.0.1) project:

```
rm -rf replace-boilerplate-generator                          # cleanup
rm -rf meteor-1.7.0.1                                         # cleanup
rm -rf ~/.meteor                                              # cleanup
meteor --version                                              # install packages in ~/.meteor
git clone https://github.com/meteor/meteor.git meteor-1.7.0.1 # get meteor code 
cd meteor-1.7.0.1                                             # change dir
git checkout release-1.7.0.1                                  # checkout correct version
cd ..                                                         # change dir
meteor create replace-boilerplate-generator                   # create new meteor project
cd replace-boilerplate-generator                              # jump into project folder
meteor update --release 1.7.0.1                               # make sure we have the right version
mkdir packages                                                # create local packages folder
cd packages/                                                  # jump into packages folder
ln -s ../../meteor-1.7.0.1/packages/boilerplate-generator .   # link boilerplate-generator
subl boilerplate-generator/template-web.cordova.js            # change boilerplate-generator code
cd ..                                                         # jump back to project root
meteor remove boilerplate-generator                           # remove boilerplate-generator
meteor add boilerplate-generator                              # add boilerplate-generator
meteor add-platform android                                   # add android platform
meteor run android-device                                     # run meteor
```

**Comment by ayalpani** [comment]
Now I have followed the same steps as in my previous post on a different computer. Also here, the changes I make to boilerplate-generator code in local packages folder are totally ignored. 

I have spent a whole week trying to change the value of the Content-Security-Policy meta tag. So much effort for such a seemingly simple task. I am open for any radical ideas on how to move forward with this. @benjamn maybe you still have an idea what I could try out?

**Comment by obonyojimmy** [comment]
@ayalpani not a solution but a suggestion to the meteor group, where we could have an option on meteor which would do a patch of atmosphere package to local package, ie `meteor add someone:package --patch` , also struggling to override an atmosphere package of type `testOnly` ie `meteortesting:mocha`

**Comment by gladenko** [comment]
I have same problem this is a big problem

**Comment by crapthings** [comment]
can't override CSP on cordova
