### ISSUE TITLE
Deep merging of documents

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#998]
Currently Meteor allows partially publishing and document which you can then merge when you publish additional fields. If I understand correctly from the documentation (where this feature is documented just in one comment to the code, I may add) this works only on top-level fields. Are there any plans to add support also for nested fields? And even partially published lists?

In fact, documentation is a bit confusing on this. So both partial and full document publish issue an "added" call. In one part, documentation is saying that in such case when there are multiple sources of the same document which document "wins" is arbitrary. And then in account package it is written in a code comment that fields are merged.

**Comment by brettle** [comment]
@mitar, in [this comment](https://github.com/meteor/meteor/issues/998#issuecomment-38113820) you suggest looking at the Meteor Roadmap for a discussion of merging. Which card are you referring to? None of the current cards immediately jump out to me as related to this issue. Thanks!

**Comment by mitar** [comment]
I think [this one](https://trello.com/c/kMkw800Z/53-official-ddp-specification).
