### ISSUE TITLE
1.7.0.1 breaks AWS cloud9 development workflow 

### ISSUE THREAD

**Issue by elmarti** [meteor/meteor#9986]
Cloud9 is a browser based IDE which provides a UI to an Amazon AMI (linux/SUSE) instance. I had been using the original Cloud9 for for 3 years and AWS Cloud9 for the past year with Meteor and without problem. 

Since upgrading to to 1.7, it appears to forcefully use the `ROOT_URL` as the websocket uri, which, due to the limitations of Cloud9, prevents it from working properly. 

**Workaround**
You can set the `ROOT_URL`, either at runtime, or in the startup command, the key limitation in AWS cloud9  is that the workspace testing URL is dynamic and having `ROOT_URL` set to anything but `127.0.0.1` means an error is logged whenever Meteor is run. You will have to find the preview URL through the preview button and ignore the error that is logged by C9. It seems to be running OK with this workaround.

Not sure if there's an actionable that could come from this, might be useful to anyone else using C9

**Comment by elmarti** [comment]
![screenshot 2018-06-12 at 20 20 18](https://user-images.githubusercontent.com/4789968/41312094-20002e62-6e7e-11e8-8a8f-005818326fc7.png)

**Comment by benjamn** [comment]
I'm minutes away from releasing a new version of `socket-stream-client` that goes back to using `SockJS` in modern browsers, rather than a native `WebSocket`: https://github.com/meteor/meteor/pull/9985

I'm not 100% sure, but I suspect running `meteor update socket-stream-client` will solve this problem for you.

**Comment by elmarti** [comment]
Hi @benjamn, thanks a bunch, upgrading `socket-stream-client` seems to have resolved the issue.
