### ISSUE TITLE
[1.7] After updating from 1.6.1.1.  package SessionAmplify is broken

### ISSUE THREAD

**Issue by MastroLindus** [meteor/meteor#9988]
I have a project running 1.6.1.1 that uses atmosphere package SessionAmplify that underlying extends Session to override it's set method.
In 1.6.1.1 SessionAmplify correctly has a get function to retrieve a stored variable.
If I update to 1.7, SessionAmplify.get is undefined. 
No other changes have been made, and I can consistently reproduce it/fix it by switching from/to my 1.7 branch.

I am not really sure what the root cause of this new behaviour.
It looks like SessionAmplify is not really maintained right now.
I know there's a chance that this is not a bug of meteor but of  the package itself requiring some updates.
Is there another supported and more up-to-date way to store a variable in a local session without having it erased after a page refresh ? (That's the problem I have with the normal Meteor.Session api).

**Comment by evolross** [comment]
See https://github.com/meteor/meteor/issues/9918

**Comment by MastroLindus** [comment]
> See #9918

Might be related. The package used is different, as the error, but both errors look like have the same root cause of a behaviour change around session handling between 1.6 and 1.7

The source code of the package I use is quite simple:
`SessionAmplify = _.extend({}, Session, {
  keys: _.object(_.map(amplify.store(), function(value, key) {
    return [key, JSON.stringify(value)]
  })),
  set: function (key, value) {
    Session.set.apply(this, arguments);
    amplify.store(key, value);
  },
});`

So some of the changes of 1.7 is making this code not extending session properly (and not getting the get() function for example).

**Comment by MastroLindus** [comment]
Looking more into this, I found out that the root cause of the difference in runtime behaviour is the following:
_.extend underlying uses the "for.. in" loop that iterates over all the enumerable properties of an object and of its prototype
in 1.6:
Session.__proto__.propertyIsEnumerable("get")  returns true
in 1.7
Session.__proto__.propertyIsEnumerable("get") returns false (and many other keys).

**Comment by duncanthrax** [comment]
If you're looking for a quick solution to get SessionAmplify to work, this did it for me:

1) Remove SessionAmplify package from Meteor or node.
2) Add this to your client-side code:

```
  SessionAmplify = Object.create(Session);
  Object.assign(SessionAmplify, {
    keys: _.object(_.map(amplify.store(), function(value, key) {
      return [key, JSON.stringify(value)]
    })),
    set: function (key, value) {
      Session.set.apply(this, arguments);
      amplify.store(key, value);
    }
  });
```

**Comment by goodideal** [comment]
Good hack...
