### ISSUE TITLE
Periodic crashes with "Exited with code: 3221225477"

### ISSUE THREAD

**Issue by gregdeon** [meteor/meteor#9992]
I'm developing with Meteor 1.6.1.2 on Windows 10. Running the server locally, my shell occasionally prints
```
Exited with code: 3221225477
Meteor server restarted
```
I think this exit code means my program crashed due to a segfault. This happens pretty randomly - sometimes 30 seconds apart, other times 5 minutes apart. It also appears to happen more often when I refresh the page.

At first, I thought that this might be an issue related to fibers -- I saw that #9796 had similar issues. I tried printing `Fiber.fibersCreated` regularly but this looked pretty stable with under 12 fibers. 

The real problem that I have is that I can't get any more information out of this error message. What can I do to debug this problem?

**Comment by gregdeon** [comment]
I tried uploading to Galaxy and didn't see any issues within an hour. I think this might be a Windows-specific problem.

**Comment by menelike** [comment]
We had some problems with node versions mentioned in https://github.com/meteor/meteor/issues/9804#issuecomment-379677831, we switched to an older node version to solve that. Do you know if this still happens in Meteor 1.7.0.3 (current release)?

**Comment by benjamn** [comment]
Node 8.11.0 and 8.11.1 were the versions that caused frequent segmentation faults in Meteor apps (https://github.com/meteor/meteor/issues/9797). I would strongly recommend using Node 8.11.3.

**Comment by gregdeon** [comment]
I'm not sure if this happens in the current release. I'm using 1.6.1.2 to get around the Windows 10 update problems (#9863).

Great info about the Node segfaults. I could try using Node 8.11.3 - is there a way to update this within Meteor, or is there one specific version of Node for each Meteor release?

**Comment by 2004hp** [comment]
Hi folks, 

Just adding a quick me too.

On a machine that ran meteor fine two months ago after a meteor update today to the current meteor and the recommended 1.7 babel & meteor node updates I am getting the same error message in my apps and also the simplest "meteor create simple-todos --bare":

"C:\lrproj>
>meteor create simple-todos
>meteor create sim-todos --bare

C:\lrproj> cd sim-todos
C:\lrproj\sim-todos>meteor
[[[[[ C:\lrproj\sim-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 3221225477. Restarting.
Unexpected mongo exit code 3221225477. Restarting.
Unexpected mongo exit code 3221225477. Restarting.
Can't start Mongo server.

C:\lrproj\sim-todos>"

**Comment by vladbalan** [comment]
This 

> 
> 
> I'm developing with Meteor 1.6.1.2 on Windows 10. Running the server locally, my shell occasionally prints
> 
> ```
> Exited with code: 3221225477
> Meteor server restarted
> ```
> 

For whom it may concern, I found that removing some of the server side `console.log`s makes this problem go away. YMMV

**Comment by ProjazzPlayzz** [comment]
Error 3221225477 is hex 0xC000005 which is an access violation. You should step through the code in the debugger to identify cause of the problem. That's about all I can suggest without any further relevant information.
