### ISSUE TITLE
Meteor install: curl: (22) The requested URL returned error: 416

### ISSUE THREAD

**Issue by raphaelarias** [meteor/meteor#9997]
After trying to update my Meteor app to 1.7.0.3 and after that failed and revert branches didn't work because of the error (https://github.com/meteor/meteor/issues/9946), I've tried to uninstall Meteor and install it again.

Now the install fails:
<img width="571" alt="screen shot 2018-06-15 at 8 05 42 pm" src="https://user-images.githubusercontent.com/5008166/41462913-d5c28ece-70d7-11e8-8401-8dbc3e941e73.png">

Would you know what is happening?

**Comment by raphaelarias** [comment]
PS: After a while it apparently started starting the app, but it fails with no message:
<img width="603" alt="screen shot 2018-06-15 at 8 10 36 pm" src="https://user-images.githubusercontent.com/5008166/41463008-3e24a4b6-70d8-11e8-8275-abeae4d3f40e.png">

**Comment by raphaelarias** [comment]
Here is the logs running with --verbose:

=> [HMR] Dev server listening on port 3003.
=> Started MongoDB.                           
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6

**Comment by abernix** [comment]
This is two different errors, and the second should be reported in the issue you already linked to (#9946).

The first screenshot you've posted is a network problem, either with the CDN provider or your own Internet, or somewhere in between — probably temporary and hopefully isolated (it works fine for me right now).  HTTP status code 416 usually means that that it's unable to fetch a range of data and the first failure (`EOF`) seems to indicate that the initial fetch was interrupted.

Please try again from another connection or try at a later time.

**Comment by abernix** [comment]
Of course, if anyone continues to have this problem, please do let us know, but since it's a network problem please include some information that might help us diagnose the problem (e.g. geographical region, etc.)

**Comment by rroslan** [comment]
3 times I downloaded 100% and I get same error and keeps on repeating
curl: (22) The requested URL returned error: 416
Retrying download in 5 seconds...

**Comment by rroslan** [comment]
After downloading 100%, this following error:
curl: (56) Unexpected EOF
Retrying download in 5 seconds...

**Comment by benmort** [comment]
any news on this?

**Comment by abernix** [comment]
@benmort @rroslan Let's take this to a more active/open issue, since this does seem to be affecting multiple people.

Please post your geographic region and IP address (found via http://checkip.amazonaws.com/, if you're not sure) in #10173 as your `+1`?

**Comment by gaba5** [comment]
same thing happened to me

**Comment by lucianogavaz** [comment]
please anybody have a solution

**Comment by adim86** [comment]
Happened to me:

Nigeria (West Africa)
IP: 154.66.54.193

**Comment by ShrabaneeM** [comment]
Facing the same issue. Any solution or cause for this? 
I have tried several times. 
Trying in Ubuntu 18.04.

**Comment by gaurav-kungwani** [comment]
leave anything as going , it will itself resolve it

**Comment by GowthamRayar** [comment]
Still facing the Issue, @gaurav-kungwani how long will it take to resolve itself?
